### ISSUE TITLE
Error to run project

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#10]
Salut,

J'ai cloné le projet pour pouvoir le tester sur ma machine et, à terme, pouvoir contribuer quand j'aurai du temps.

J'ai suivi les instructions du projet de PDP mais j'obtiens toujours l'erreur suivante :

``` console
ImportError: No module named smileys
```

Quelqu'un serait en mesure de m'aider ? Ca serait vraiment top ! :)

**Comment by Ge0** [comment]
J'ai la même erreur pour info, si ça peut rassurer notre ami Andr0 :o)

Edit : si ça se trouve on n'en est qu'au début, j'ai pas installé tout ce qu'il y avait dans "requirements.txt", ni vérifié si c'était déjà présent sur ma bécane. xD

**Comment by GerardPaligot** [comment]
Carrément parce que je commençais à me dire que j'étais le seul ...

**Comment by Ge0** [comment]
le seul à avoir clone et setup ? sans doute, puisque je pense (mais je peux me tromper) que l'erreur est due au manque d'un module qui n'aurait pas été ajouté sur le dépôt.

Maintenant on est deux !

**Comment by firm1** [comment]
Le problème vient du fait que la librairies des smileys n'a pas été rajoutée dans le fichier des requirements.

C'est corrigé dans [ce commit](https://github.com/Taluu/ZesteDeSavoir/commit/570822c7803893d9dfdcb4f09b920d0a2d2fabe8#diff-b4ef698db8ca845e5845c4618278f29a).

refaites `pip install requirements.txt`

**Comment by GerardPaligot** [comment]
Tu clotures vite. ^^

J'ai synchronisé mon clone du projet pour avoir la mise à jour du fichier `requirements.txt` mais il refusait de m'installer django-smileys avec `pip`. Par contre, il a bien voulu me l'installer avec `easy_install`.

J'ai donc lancé le projet et j'obtiens directement une erreur sur mon navigateur du type `ImportError` en me disant qu'il n'existe pas de module appelé lxml : `No module named lxml`.

**Comment by firm1** [comment]
Ah ouais. En fait, j'ai tellement fait de modif que j'ai oublié de préciser tout ce qu'il faut installer.

Globalement quand tu as un souci de ce type, il suffit de faire `pip install <nom_du_package>` et dans ton cas, tu dois faire `pip install lxml`

Je corrige le requirements pour faire cette MAJ.

C'est aussi pour ça que j'aime bien que les gens essayent, ça me permet de voir des trucs que j'ai zappé.

**Comment by GerardPaligot** [comment]
Ok, il a bien voulu installer `lxml` mais il veut le module `git` qu'il ne trouve pas avec `pip` ou `easy_install`.

**Comment by firm1** [comment]
ah oui.

`easy_install GitPython`

**Comment by GerardPaligot** [comment]
Bien, à première vue on est bon sur les modules. Par contre, j'ai des erreurs avec la base de données avec une erreur `DatabaseError` en me disant :

```
no such table: forum_category
```

**Comment by firm1** [comment]
Tu as bien fait : `python manage.py syncdb` et ensuite `python manage.py migrate` ?

**Comment by GerardPaligot** [comment]
Non, ma faute. J'ai lancé les commandes et maintenant tout fonctionne.

Merci en tout cas, je vais enfin pouvoir regarder un peu le projet. :)

**Comment by firm1** [comment]
Surtout n'oublie pas qu'il faut créer les catégories/forum de test dans l'admin `127.0.0.1:8080\admin\`

Pense aussi à te créer une ligne dans les profils utilisateurs pour avoir un minimum de data.

Il faudra à terme mettre à disposition des développeurs des données de test à charger automatiquement.

**Comment by geoffreyc** [comment]
J'ai beau essayer j'arrive pas a la faire tourner dans un environnement apache + mod_wsgi :/

**Comment by geoffreyc** [comment]
Quelqu'un a déjà réussi ou vous tourner tous en local?

**Comment by firm1** [comment]
Pas besoin d'installer une quelconque apache et mod_wsgi pour faire tourner la version locale.

Quand tu as fait : `python manage.py syncdb`
puis : `python manage.py syncdb`
Il suffit de faire dans ta console :`python manage.py runserver`

Et ensuite tu vas sur : `127.0.0.1:8080`

ça marchera. ne t'embete même pas à installer en local apache et cie

**Comment by geoffreyc** [comment]
Justement j’essaie de le faire tourner sur mon dédié (vraiment pour de l’entraînement personnel, j'ai jamais deployed une app Django et je voulais voir si j'y arrivai). Mais pas moyen :/

**Comment by firm1** [comment]
C'est possible de le deployer sur dédié, mais c'est assez simple. Je pourrais te copier/coller la procédure mais je n'ai pas accès à mon dédié en ssh au boulot.

ça attendra le week end.

**Comment by geoffreyc** [comment]
Sympa merci =)

**Comment by geoffreyc** [comment]
Ah, c'est sûrement parce que j'utilise mod_ruid2, aparement c'est pas tres tres compatible ...

**Comment by ChantyTaguan** [comment]
Pfiou, j'ai finalement réussi à installer tout ça en local.

Sous MacOS X, il est nécessaire d'installer Command Line Tools, via XCode (et donc nécessaire d'avoir XCode, quoiqu'il soit sans doute possible d'avoir l'un sans l'autre). Ca vaudra sans doute la peine de le mentionner dans le README

**Comment by firm1** [comment]
Etant donné que je suis étranger aux outils MacOS, je pense que Taguan va faire profiter aux autres de son expérience sur les système de la pomme.

**Comment by Coy0te** [comment]
Je confirme que tu peux récupérer CLT sans XCode sous Mac OS.

**Comment by firm1** [comment]
Comme je le disais donc :

> C'est possible de le deployer sur dédié, mais c'est assez simple. Je pourrais te copier/coller la procédure mais je n'ai pas accès à mon dédié en ssh au boulot.
> 
> ça attendra le week end.

A rajouter à la fin de mon fichier apache2.conf

```

Alias /static/admin/ /usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/

AliasMatch ^/([^/]*\.css) /var/www/lebonprojet.tk/lebonprojet/static/css/$1

Alias /media/ /var/www/lebonprojet.tk/lebonprojet/media/
Alias /static/ /var/www/lebonprojet.tk/lebonprojet/static/

<Directory /var/www/lebonprojet.tk/lebonprojet/static>
Order deny,allow
Allow from all
</Directory>

<Directory /var/www/lebonprojet.tk/lebonprojet/media>
Order deny,allow
Allow from all
</Directory>

WSGIScriptAlias / /var/www/lebonprojet.tk/lebonprojet/zds/wsgi.py
WSGIPythonPath /var/www/lebonprojet.tk/lebonprojet/
<Directory /var/www/lebonprojet.tk/lebonprojet/zds>
   <Files wsgi.py>
       Order deny,allow
       Allow from all granted
   </Files>
</Directory>

```

Compiler les fichiers static avec la commande suivante : `python manage.py collectstatic`

**Comment by ShigeruM** [comment]
Salut,

J'essaie d'installer tout ceci sur Windows. Aucun vrai problème jusqu'à l'ultime runserver, qui me sort ceci :

```
0 errors found
Unhandled exception in thread started by <function wrapper at 0x025D2330>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 93, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    "quit_command": quit_command,
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 65,in write
    if ending and not msg.endswith(ending):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 1: ordinal not in range(128)
```

J'ai beau me creuser la tête depuis tout à l'heure, je ne vois pas pourquoi j'ai cette erreur. Quelqu'un aurait une idée ?

Edit : il suffisait que je post pour trouver une solution. En commentant la section suivante dans le settings.py, je n'ai plus de problème : 

```
# Python is platform-independent...or is it?
if platform.system() == "Windows":
    locale.setlocale(locale.LC_TIME, 'fra')
else:
    locale.setlocale(locale.LC_TIME, 'fr_FR.UTF-8')
```

Willard, tu me dirais 2 mots de ce passage ? Je vois bien l'idée, mais je ne comprends pas bien pourquoi ce petit bout de spécifique Windows vautre le lancement du serveur.

Bisous

**Comment by firm1** [comment]
Je ne sais pas sur quel Windows tu tourne, mais ce bout de code permet de au site d'adopter l'encodage en langue Française. Etant donné que [WIndows fait toujours les choses différemment](http://msdn.microsoft.com/en-us/library/39cwe7zf%28vs.71%29.aspx) , il faut faire du spécifique.
Par contre, peux tu me dire si tu n'as pas de problème d'encodage sur Windows par la suite ?

Merci Shig.

**Comment by ShigeruM** [comment]
Je suis sur Windows 8.1 sur une tablette Samsung ATIV Tab 3 (c'est bien Windows 8.1, pas RT).

Désormais j'arrive à lancer le serveur mais j'obtiens cette erreur au chargement de la page :

```
ValueError at /
invalid literal for int() with base 10: 'Membre'

Request Method:  GET
Request URL:    http://127.0.0.1:8000/
Django Version: 1.6
Exception Type: ValueError
Exception Value:    
invalid literal for int() with base 10: 'Membre'
Exception Location:  C:\Python27\lib\site-packages\django\forms\fields.py in __init__, line 202
Python Executable:  C:\Python27\python.exe
Python Version: 2.7.5
```

Là encore je n'ai pas trouvé de solution... Je ne sais pas si c'est lié au précédent problème et au fait que j'ai commenté le bout vu plus haut.

**Comment by firm1** [comment]
Aie, ça ne me donne pas beaucoup d'informations. Je suis tenté de te demander, de me donner la liste entière de tes logs. Si possible un screenshot de toute la page d'erreur. Parce que là comme ça, je ne peux pas savoir quelle fonction à failed

**Comment by ShigeruM** [comment]
Le problème semblait venir de ma version de Django : 1.6. Les requirements indiquent bien >= 1.5 et < 1.6 mais j'avais déjà la version 1.6 sur mon PC. Après avoir réinstaller la version 1.5, je n'ai plus besoin de commenter la section spécifique à Windows cité plus haut. De plus, l'erreur "invalid literal for int() with base 10: 'Membre'" venait d'une différence dans la définition d'un CharField entre Django 1.5 et 1.6.

La doc de Django 1.5 dit :

> CharField has one extra required argument:
> CharField.max_length
> [...]

et celle de 1.6 : 

> Has two optional arguments for validation:
> max_length 
> [...]

Or, la partie qui posait problème est dans la définition du UserGalleryForm :

```
user= forms.CharField('Membre', required=False)
```

Selon lui, 'Membre' n'est pas un entier. Pfff. Donc ok, mais là où je ne pige pas, c'est que ce code passe avec Django 1.5 et pas 1.6 ! D'après ce que je lis dans les 2 docs, ça devrait être l'inverse. Quelqu'un comprend ?

Bon en tout cas ça ne m'empêchera pas d'avancer. J'avais qu'à suivre à la lettre les requirements, ça m'apprendra.
