### ISSUE TITLE
Les signatures ne filtrent pas les citations

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1000]
Le texte des signatures devrait être limité aux fonctionnalités suivantes :
- texte plat
- gras
- italique
- lien

Or, [on peut voir ici](http://zestedesavoir.com/forums/sujet/395/reorganisation-de-lordre-dun-tutoriel-par-dragdrop/?page=1#p3718) qu'un utilisateur a réussi à utiliser une citation ce qui me semble incohérent et qui casse le design au passage.

**Comment by ArnaudCalmettes** [comment]
Ce serait un bug si c'était contraire aux requirements.  

Problème : on n'a pas de requirements.

Solution : thread en devzone pour en décider.

**Comment by Alex-D** [comment]
Ca avait déjà été décidé ainsi, il y a des mois. Du coup, je ne vois pas l'utilité d'en débattre de nouveau sachant qu'on sait déjà ce qu'on veut.

Edit : sachant que ça peut casser à la fois la sémantique et la mise en forme/page, je considère que c'est quelque chose à corriger rapidement.

**Comment by SpaceFox** [comment]
On avait eu cette discussion il y a des mois _à propos des signatures de la
v4 du SdZ_, ça c'est certain.

Par contre je suis complètement incapable de retrouver cette décision
_concernant ZdS_.

J'ai bien les tickets #131 et #367 qui causent de signatures (en
particulier de limiter la taille), mais pas de limitations en
fonctionnalités.

**Comment by Coy0te** [comment]
Je suis certain également qu'on en avait déjà discuté avec Christophe au moment où il développait les fonctionnalités markdown, et qu'on avait conclu qu'il fallait limiter au strict minimum.

Je pense qu'à l'époque, ça a dû se faire sur la première ML.

**Comment by SpaceFox** [comment]
Pour info, la suite de la discussion est sauvegardée ici : http://preprod.zestedesavoir.com/forums/sujet/409/les-signatures/

**Comment by SpaceFox** [comment]
Corrigé, mergé, fermé
