### ISSUE TITLE
Les tests JS Hint ne fonctionnent pas

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1006]
En déployant ZdS je me suis rendu compte d'une incohérence dans le code JS.

Il s'agit de [celle ligne](https://github.com/zestedesavoir/zds-site/blob/beta-0.2/assets/js/keyboard-navigation.js#L15) est est censée ne pas passer coté travis (obligation d'utiliser des doubles cote), mais qui a été visiblement mergée via [cette PR](https://github.com/zestedesavoir/zds-site/pull/985).

J'en déduis donc que JS Hint n'est pas vérifié par travis.

A corriger donc.

**Comment by Alex-D** [comment]
Ils fonctionnent localement, car c'est grâce à JSHint que j'ai pu le voir et que je l'ai corrigé. Il doit manquer un petit quelque chose dans la configuration de Travis pour le prendre en compte.

Du coup, ping @sandhose :)

**Comment by sandhose** [comment]
[Voila pourquoi :-°](https://github.com/zestedesavoir/zds-site/blob/beta-0.2/Gulpfile.js#L149)

M'en occupe

**Comment by Eskimon** [comment]
C'est QuAlitisé, mergé toussa = je ferme !
