### ISSUE TITLE
Nettoyage de la base de PROD

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1008]
Pour passer en bêta publique, on doit faire un grand nettoyage de la base.

L'idée est de :
1. Avoir la base actuelle comme base de préprod (pratique pour les tests et fait "sauvegarde" au cas où on a dégagé un truc de trop)
2. Faire un nettoyage drastique de la base de prod.

Par "Nettoyage drastique", j'entends :
- On conserve la structure des forums
- On postite tous les topics intéressants à conserver et uniquement eux
- On conserve les post-its
- On conserve les utilisateurs qui ont posté dans les post-it
- On dé-postite ce qui n'a pas vocation à rester postité

Tout le reste, **absolument tout le reste** dégage. Ceci inclus au moins :
- Tous les articles, y compris les commentaires et données hors base (Git)
- Tous les tutos, y compris les commentaires données hors base (Git)
- Tous les MP
- Tous les comptes qui n'ont pas au moins 1 message conservé
- Tous les topics qui n'ont pas été postités
- Toutes les galleries et toutes les images (à l'exception de celles qui seraient utilisées dans un topic conservé)
- Toutes les alertes de toutes sortes

**Comment by Alex-D** [comment]
> postité

Épinglé *

>  toutes les images (à l'exception de celles qui seraient utilisées dans un topic conservé)

Ca me semble chaud à gérer...

> Toutes les galleries et toutes les images

Galerie ne prends qu'un l en français... :-° #easytroll

Plus sérieusement, il ne faut pas oublier de supprimer les fichiers au delà de la simple table en base.

**Comment by ArnaudCalmettes** [comment]
C'est prévu. On fera ça en tout début de semaine prochaine (puisque les
accès sont coupés dimanche soir à minuit).

Arnaud

**Comment by ArnaudCalmettes** [comment]
Voilà. La base en prod est clean.

**Comment by ArnaudCalmettes** [comment]
Vu le nombre de backups que SpaceFox a faits, je pense qu'on peut fermer cette issue, du coup.
