### ISSUE TITLE
Markdown : les titres mal interprétés

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#101]
Actuellement il y'a un bug dans le markdown des titres.

Si j'écris le code markdown suivant: 

``` text
#Titre1
```

le rendu html est le suivant (Notez bien qu'en plus d'interpreter la ligne, le T a disparu)

``` html
<h3>itre1</h3>
```

Au lieu de rendre ceci : 

``` html
<p>#Titre1</p>
```

Normalement, quand il n'ya pas d'espace après le dièze, il ne faut pas interpréter le caractère comme étant un titre.

**Comment by cgabard** [comment]
Hum ok, je regarderais ça ce soir.

**Comment by cgabard** [comment]
Par contre je ne pense pas que ta dernière phrase soit vrai. En l'absence d'espace le titre était précédemment rendu de la même façon. Dans ton ex le seule point deconnant par rapport a avant est la première lettre bouffée

**Comment by cgabard** [comment]
Je n'ai pas d'instance locale pour vérifier mais si je me fit à la regexp utilisé pour les titres : https://github.com/waylan/Python-Markdown/blob/master/markdown/blockprocessors.py#L414 tu verras qu'il n'y aucune condition sur les espaces. Je veux bien la rajouter mais ce n'est pas le comportement de base. 

Ensuite la lettre bouffé, je pense que c'est ma tentative d'empecher un titre avec trop de `#` d'etre interprétée comme un titre de niveau max + le contenu commençant par # (je ne suis pas un pro des RE et j'avais oublié un detail). 

Soit je vire cette contrainte (qui n'est de toute façon pas en accord avec le fonctionnement précédent) soit je rajoute ta contrainte d'espace (qui le résoud d'elle même). Une préférence ?

**Comment by firm1** [comment]
Etant donné que le comportement de base de python-markdown, n'a pas de contrainte sur les espaces, et que pandoc, [n'a pas non plus de contrainte sur les espaces](http://johnmacfarlane.net/pandoc/try/?text=%23Titre1&from=markdown&to=html), j'en déduis que c'est la syntaxe officielle.

Donc, j'ai envie de dire, qu'il ne faut pas faire la connerie que j'ai dis plus tôt en fin de mon message.

En gros, Il faut juste éviter de virer la première lettre des titres.

**Comment by cgabard** [comment]
Le fait qu'il y n'y ai pas cette contrainte fait que, de base, ça : 
`####### 7 dièses`
sera transformé en  : 
`<h6># 7 dièses</h6>`

Veut on vraiment ça ?

Rajouter la contrainte de l'espace n'est pas génant : nos titres restent compatible avec ceux de pandoc, simplement nous on est plus contraint. 

Le prob est qu'on s'éloigne un peu du fonctionnement classique de markdown.

**Comment by cgabard** [comment]
Etrangement, mon example produit : `<p id="dièses">7 dièses</p>` dans pandoc...

**Comment by firm1** [comment]
> Etrangement, mon example produit : `<p id="dièses">7 dièses</p>` dans pandoc...

En effet, et ça me parait une bonne solution de l'envisager ainsi et au moins on reste dans le comportement normal de markdown.

**Comment by cgabard** [comment]
Bah je ne suis pas surs que produire un p quand il y a trop de dièses soit le comportement normal de markdown. Autant rester dans le comportement precedent de python markdown. Reste a savoir maintenant si on force l'espace ou pas.

**Comment by firm1** [comment]
> Reste a savoir maintenant si on force l'espace ou pas.

Je dirais pas de contrainte d'espace pour ne pas rajouter des contraintes pas forcément utiles.

**Comment by cgabard** [comment]
Ok. Etant au boulot, j'ai directement patché sur github. Normalement c'est réglé.
