### ISSUE TITLE
Ajouter les boutons d'action dans le menu latéral sur mobile

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1011]
Les éléments du menu latéral contenus dans les formulaires ne sont pas pris en compte lors de la construction du menu latéral sur mobile.

Il faut "simplement" ajouter ceux-ci au menu.

**Comment by SpaceFox** [comment]
Question de noob : le tag "difficile" était là pour indiquer un problème particulièrement chiant à régler.

Quel est la difficulté ici, et que peut-on faire pour t'aider à la réduire ?

**Comment by Alex-D** [comment]
Il n'y a aucun moyen de m'aider à ce niveau :/

C'est difficile car le menu latéral est construit à la volée en JS, et il faut donc à la fois le designer mais le construire.

Le soucis c'est d'arriver à mettre les boutons (qui sont donc inclus dans des formulaires suites aux fix des CSRF) et ça va prendre un peu de temps.

Jusqu'ici j'avais une classe sur les liens à coller dans le menu. Là avec les formulaires ça devient un poil plus délicat (soucis avec les id, les labels, l'accessibilité, etc).

**Comment by Alex-D** [comment]
A valider -> merger -> fermer :)
