### ISSUE TITLE
Une JS fait tout planter sur les pages proposant "..." dans leur pagination

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1013]
Il faut revoir l'id de l'élément "..." pour qu'il ne contienne pas de "/".

**Comment by ArnaudCalmettes** [comment]
Y'en a d'autres des issues bloquantes pour la bêta publique de ce genre qui ne sont pas référencées [ici](http://zestedesavoir.com/forums/sujet/429/fin-de-la-beta-privee/) parce qu'elles n'ont pas encore été créées ?

**Comment by Alex-D** [comment]
Pas que je sache. Je les rajouterais ici si j'en trouve d'autres.

**Comment by ArnaudCalmettes** [comment]
Non mais tu te rends compte que ce genre de truc fait mentir les estimations de charge pour tout le monde ? S'il y en a d'autres il faut les ouvrir tout de suite et les référencer immédiatement. Sinon comment veux-tu que les gens s'organisent alors qu'on est déjà en plein shitstorm ?

**Comment by Alex-D** [comment]
Tu te rends compte que t'es _encore_ en train de me lyncher en public parce que je ne rapporte pas les bugs sur Github, alors que c'est notamment parce que je n'ai pas le temps ?

Je suis désolé de ne pas l'avoir fait avant, ça prend peu de temps à résoudre, je le ferais ce soir ou demain, mais j'ai aussi d'autres choses à faire à côté qui m'empêche de signaler ce genre de choses sur Github. Surtout que c'était un bug rapporté sur le forum.

**Comment by ArnaudCalmettes** [comment]
Je ne suis pas en train de te "lyncher", simplement je te rappelle qu'on est en train de boucler cette bêta pour hier et que le seul outil fiable dont je dispose pour coordonner et anticiper l'effort de façon à ce que personne ne perde de temps, c'est les issues GitHub. J'ai précisé dès le début dans le thread d'organisation qu'il était prioritaire qu'on crée ces issues avant de partir dans ce rush pour que d'autres puissent les prendre et s'en occuper en fonction de leurs disponibilités.

Jusqu'ici la liste d'issues était stable et on commençait à voir le bout du tunnel, donc si on a d'autres mauvaises surprises à avoir, il vaut mieux que ce soit maintenant, sinon je suis incapable de donner une date pour la fin de cette milestone, et ça nuit à tout le monde : les devs, la com' et les visiteurs.

**Comment by Alex-D** [comment]
En fait, je viens de voir que le bug est a priori déjà corrigé dans une PR #987 en attente depuis quasi 10 jours.

**Comment by ArnaudCalmettes** [comment]
OK, ça passe l'issue cash en validation. Je préfère ce genre de surprises. :)

PS : Ma remarque sur l'organisation reste valable, cela dit.

**Comment by Alex-D** [comment]
> Ma remarque sur l'organisation reste valable, cela dit.

Je la comprend. Simplement que j'ai du ne pas la rapporter du fait que je l'avais déjà corrigé et qu'entre temps j'ai oublié que c'est pour ça que je ne l'avais pas rapporté...

Mais globalement : manque de QA...

**Comment by ArnaudCalmettes** [comment]
Oui j'ai bien compris et du coup je reconnais que tu n'y étais pour rien si l'issue n'était pas présente. 
On a du monde qui arrive pour faire la QA.

**Comment by Alex-D** [comment]
> On a du monde qui arrive pour faire la QA.

Good ça :)

Je pense que cette PR n'a pas été validée simplement parce qu'il faut créer au moins deux pages de commentaires ou de topics pour vérifier qu'elle est correcte, et qu'on manque de fixtures (c'est en cours par @Eskimon si mes souvenirs sont bons). Pour l'avoir fait pour le test, c'est super long et chiant à faire.
