### ISSUE TITLE
404 sur les pages suivantes dans résultat de recherche

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#1018]
Étapes pour reproduire : 
1. Faire une recherche qui retourne plus d'une page de résultats
2. Choisir une page autre que la première page
3. Obtenir un 404

**Comment by Eskimon** [comment]
D'apres ca : https://github.com/zestedesavoir/zds-site/issues/708 ton probleme serait un doublon de ca: https://github.com/zestedesavoir/zds-site/issues/953 et serait resolu par le merge de ca: https://github.com/zestedesavoir/zds-site/pull/987

**Comment by vhf** [comment]
Bien vu. Je laisse quand même cette issue ouverte jusqu'à résolution du problème.

**Comment by Alex-D** [comment]
Je confirme.

**Comment by Alex-D** [comment]
Du coup ça a été corrigé avec le merge de la #987 .
