### ISSUE TITLE
[Smiley] Ooops devien <smiley>ops...

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#102]
Le smiley Oo doit changer d'alias, pour un truc du genre O_o.

Je viens de tomber par hasard sur un tuto où l'auteur a écrit "Oops" en début de phrase, et où ça s'est retrouvé découpé en un smiley et un "ops" collé juste après.

**Comment by cgabard** [comment]
Ha ouais, j'ai foutu plusieurs alias en speed pour tester, celui-ci n'etait pas forcément judicieux.

Actuellement il y a ces 4 là : "o_O", "oO", "O_o", "Oo" 

Le 2 et le 4 ne sont pas forcément pertinent, je te l'accorde. Je vais les virer.

**Comment by cgabard** [comment]
La liste complete est là : https://github.com/Taluu/ZesteDeSavoir/blob/master/zds/utils/templatetags/smileysDef.py

J'ai commité le changement, donc je ferme, faut juste attendre que @firm1 pousse en prod

**Comment by firm1** [comment]
C'est en prod et ça marche. Merci pour ta réactivité.
