### ISSUE TITLE
Internal Server Error lors de l'upload d'images

### ISSUE THREAD

**Issue by 0hexit** [zestedesavoir/zds-site#1022]
Lorsque j'essaie de mettre en ligne une image dans une galerie, j'obtiens une erreur : "Internal Server Error". J'ai l'impression que le problème est apparu depuis la mise à jour du serveur de prod il y a quelques heures.

Ça doit être lié à la config du serveur car sur mon installation locale, l'upload fonctionne très bien.

**Comment by firm1** [comment]
Durant la maintenance d'hier soir, un `python manage.py migrate` a été oublié.

ça marche mieux maintenant.

**Comment by SpaceFox** [comment]
Je ne comprends pas, parce que je l'ai fait ce `python manage.py migrate`...

Ou alors c'est lié à l'état du fichier `settings_prod.py` et à ce qu'y a ajouté @ArnaudCalmettes.

**Comment by firm1** [comment]
Tu as du le faire sur une mauvaise branche/commit car là je viens de le passer et la migrations sur la table des images n'était pas faite.

**Comment by SpaceFox** [comment]
Uniquement sur celle des images ?

**Comment by firm1** [comment]
> Uniquement sur celle des images ?

J'ai passé le migrate partout, mais il m'a juste signalé l'évolution des tables des images.

**Comment by SpaceFox** [comment]
Alors c'est du au fait que dans le fichiers `settings_prod.py` on trouve une surchage **complète** de `INSTALLED_APPS` et de `MIDDLEWARE_CLASSES`, qui n'ont strictement rien à foutre là.

Quand @ArnaudCalmettes  a mis à jour ces valeurs, il a oublié de lancer la migration, et j'ai pas pensé que comme je l'ai fait avant il faudrait le refaire.

Conclusion : on doit **vraiment** nettoyer ce fichier. 90% des informations qu'il contient n'ont strictement rien à y faire.
