### ISSUE TITLE
Nettoyer le fichier settings_prod.py

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1023]
Il faut nettoyer le fichier `settings_prod.py` qui contient des masses d'informations qui n'ont rien à y faire.

Ça n'est pas strictement urgent puisque la prod marche aujourd'hui, mais vu qu'on a une grosse coupure autant en profiter.

PS : je m'en occupe ce soir.

**Comment by firm1** [comment]
> Il faut nettoyer le fichier settings_prod.py, qui contient des masses d'informations qui n'ont rien à y faire.

Hmmm, je pense plutot qu'elle sont toutes utiles.

Les surchagers d'Installed App sont là pour éviter d'avoir le DEBUG_TOOLBAR sur la prod. Si tu vire cette surcharge, tu auras très problablement la debug toolbar qui remontera (suffit de regarder l'ordre des appels)

Les surcharges de middlewares sont là en cas de bug incompréhensible. Le middleware Lastvisit à tendance à masquer la bonne erreur dans les logs, donc en général quand tout est surchargé, il suffit de décocher dans le settings_prod un middleware pour retrouver le bon log d'erreur, si tu le vire, au moindre bug, tu auras du mal à la le localiser.

Le reste des infos aussi est important.

**Comment by SpaceFox** [comment]
Mon problème est qu'actuellement toute mise en prod qui touche à ces paramètre qui sont **écrasés** par ce fichier risque d'échouer.
C'est exactement ce qui est arrivé hier par exemple.

D'autre part ce fichier est critique. Pour moi, la production doit coller au plus près de ce qui est testé et donc dans Git. Le fichier `settings_prod.py` devrait donc être très petit, à l'heure actuelle il est juste énorme.

> Les surchagers d'Installed App sont là pour éviter d'avoir le DEBUG_TOOLBAR sur la prod. 

Alors ça veut dire que la debug toolbar est mal appelée dans le fichier `settings.py`. Elle ne doit pas être rangée au milieu des autres mais ajoutée aux applications uniquement lorsque le mode debug est activé.

> Les surcharges de middlewares sont là en cas de bug incompréhensible.

Est-ce que ça nécessite **vraiment** d'avoir une copie des middlewares dans un autre fichier, avec tout ce que ça implique en terme de cohérence entre la base de code et la version en prod ?

**Comment by firm1** [comment]
> Alors ça veut dire que la debug toolbar est mal appelée dans le fichier settings.py. Elle ne doit pas être rangée au milieu des autres mais ajoutée aux applications uniquement lorsque le mode debug est activé.

En effet, sauf que le mode debug se désactive à la fin du fichier (lorsqu'on surcharge la variable DEBUG dans le settings_prod.py). Faudrait essayer de l'activer à la fin (après l'import du settings_prod).

> Est-ce que ça nécessite vraiment d'avoir une copie des middlewares dans un autre fichier, avec tout ce que ça implique en terme de cohérence entre la base de code et la version en prod ?

ça je ne sais pas trop. Mais faut faire des essais. C'était juste pour rappeler pourquoi est-ce que les surcharges sont arrivés là

**Comment by gustavi** [comment]
UP !
Le fichier `settings_prod.py` est là pour écraser certains paramètre du `settings.py` (`DEBUG = False`, accès base de données, etc) et il donc possible qu'il soit assez gros mais globalement, tout ce qui peut être accessible au publique et qui n'est pas spécifique à la prod doit de trouver dans le `settings.py` et non le `settings_prod.py`.

**Comment by gustavi** [comment]
UP ! Ping @SpaceFox, c'est toujours d'actualité ça ?

**Comment by SpaceFox** [comment]
Oui, sauf si quelqu'un y a touché sans prévenir :)

**Comment by GerardPaligot** [comment]
@SpaceFox Qui est compétent pour faire ça ? Ce fichier n'est pas dans le dépôt.

**Comment by SpaceFox** [comment]
Toute personne ayant accès à la prod.

**Comment by gustavi** [comment]
J'ai entièrement nettoyé le fichier sur la prod. Organisé, commenté, tout beau tout propre !

Juste pour les inquiets : 

```
$ python manage.py validate
System check identified no issues (0 silenced).
```
