### ISSUE TITLE
Augmenter la limite mémoire de Latex

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1024]
Un bug que je pensais avoir noté sur github, mais qui visiblement n'était pas fait.

Pour certains tutos avec de nombreuses images, lors de la production du PDF, Latex refuse de convertir les fichier et renvoi l'erreur `! TeX capacity exceeded`

Il doit donc y avoir un moyen d'étendre la limite mémoire de Latex.

**Comment by Luthaf** [comment]
Mes deux centimes sur le sujet (Je participe à ZdS \o/) : si vous utilisez TeXLive, il faut simplement éditer le fichier texmf.cnf. Voir [cette réponse](http://tex.stackexchange.com/a/7954) sur SO.

**Comment by firm1** [comment]
Merci a toi, on utilise bien Texlive, et la limite a été étendu.
