### ISSUE TITLE
Back to top

### ISSUE THREAD

**Issue by coma94** [zestedesavoir/zds-site#1026]
J'en remet encore une couche, mais le problème des _back to top_ n'est toujours pas résolu.

Pour ceux qui ne m'ont toujours pas vu râler: lorsqu'on scroll rapidement dans la page, on est ramené en haut une fois la pages chargée à 100%.  
Sur PC c'est juste chiant, mais sur mobile, où le chargement est plus lent, ça rend la navigation quasi impossible, où alors en attendant 3 minutes que la page soit chargée avant de commencer à scroller.

Ça me le fait systématiquement, quel que soit le navigateur et le système (windows, linux, android), et uniquement sur ZdS (je n'arrive à le reproduire sur aucun autre site).

Nouvelle info: quand j'actualise la page je suis également ramené en haut, au lieu que le navigateur me laisse au même endroit comme sur les autres sites.

Je m'étonne de ne voir personne d'autre bouger pour ça, j'ai presque l'impression que ça vient de chez moi, si c'est le cas je suis preneur d'une solution.

**Comment by vhf** [comment]
Je confirme avoir le même problème sur mobile et sur PC.

**Comment by vhf** [comment]
Ok, alors en commentant les lignes suivantes : 

```
/**
 * Hide address bar
 */
if(!window.location.hash) {
    window.addEventListener("load",function() {
        setTimeout(function(){
            window.scrollTo(0, 1);
            window.scrollTo(0, 0);
        }, 0);
    });
}
```

Le comportement du scroll est à nouveau normal.

@Alex-D, que peut-on faire pour cette issue ?

**Comment by Alex-D** [comment]
J'avais déjà testé pourtant et ça ne résolvait pas le problème.

Au pire ça peut dégager, mais c'est assez étrange.

**Comment by vhf** [comment]
Est-ce que quelqu'un peut confirmer que virer ce bout de code résout le problème ?

**Comment by vhf** [comment]
Résolu par #1037 .
