### ISSUE TITLE
Personnaliser les pages d'erreurs pour les rendre plus agréables

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#1028]
Bon, paraît qu'en 2014, il faut customiser les pages d'erreurs.
Mais il faut le faire bien, sans oublier d'où l'on vient.

Je propose donc : 

500 : Clem qui dit "J'ai tout cassé" ou sa version plus personnelle "zeste ou cassé" (un truc du genre)
401/403 : Clem qui dit "Vous ne zesterez pas"
404 : "Es-tu perdu noble étranger/zesteur"
400 : "Mauvais zeste"

Je sais pas ce que ça vaut, mais je pense que ça peut être sympa de pousser certains délires jusqu'au bout, non?

**Comment by Axylium** [comment]
Pour apporter ma pierre à l'édifice, si vous voulez, je peux m'en occuper.

**Comment by Eskimon** [comment]
Alors go :D Si le projet est open-source c'est bien pour recevoir des contributions du genre je pense :)

Tant que tu respectes la charte graphique (via les templates) tout devrait bien se passer ;) (il doit _peut-être_ y avoir des images de la mascotte qui traîne quelque part...)

(Et si tu as des questions sur l'utilisation des templates, je pense que @sandhose ou @Alex-D pourront t'aider sans souci !)

**Comment by Axylium** [comment]
D'acc' ! 

Je vais voir pour sûrement en contacter un des deux, puisque j'ai un peu de mal à faire tourner une version local de ZdS chez moi. Donc un peu d'aide ne serait pas de refus. :) 

Pour les images de la mascotte, j'ai fais un peu le tour des dossiers, et je n'ai vu aucune d'elle ! ;)

**Comment by Alex-D** [comment]
Je n'ai rien contre la personnalisation des pages d'erreurs, seulement il y a des choses à faire en amont pour garantir une certaine uniformisation : créer une maquette type des pages d'erreurs.

Aussi, il faudrait intégrer la mascotte sur la page d'accueil (je sais je suis à la bourre là dessus) pour que ces pages d'erreur prennent sens, sinon on ne comprendra pas.

**Comment by Alex-D** [comment]
Voilà ce que je propose : 

![Erreur 500](http://storage.alex-d.fr/zestedesavoir/zds-erreur-500.png)

![Erreur 403](http://storage.alex-d.fr/zestedesavoir/zds-erreur-403.png)

![Erreur 404](http://storage.alex-d.fr/zestedesavoir/zds-erreur-404.png)

Ce ne sont que des maquettes, il faut encore les intégrer et les rendre fluides (responsives).

**Comment by sandhose** [comment]
J'aime beaucoup!

Je verrais bien un gros champ de recherche sur la 404, qui s' "auto-rempli" en fonction de l'url (je sais pas exactement comment, mais bon...)

**Comment by Alex-D** [comment]
Pour la recherche, ça me semble pas très pertinent sachant que l'URL ça peut être tout et n'importe quoi.

**Comment by denisalb57** [comment]
J'aime bien ses nouvelles pages d'erreurs 
Par contre je verrais bien le texte qui l'accompagne plus personnalisé a la sauce clémentine\zesteur

**Comment by Alex-D** [comment]
Le but de ces pages est de rester clair, si on peut éviter de mettre trop de "zeste"-truc dedans, c'est mieux.

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis plus d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.

**Comment by pierre-24** [comment]
De toute façon, dans les faits, c'est déjà Clem :)
