### ISSUE TITLE
Le compteur de karma ne se met pas à jour lors du vote

### ISSUE THREAD

**Issue by Taluu** [zestedesavoir/zds-site#1033]
Hello,

Quand on up / down vote un message, autant le curseur prend bien la bonne couleur (vert si +1, rouge sinon), ou la perd si on annule notre vote, mais le compteur (+1, +2, ... etc) ne se met pas à jour.

Il faut rafraîchir la page pour qu'il se mette à jour.

**Comment by vhf** [comment]
Salut, oui c'est noté.

@sandhose a une PR sous le coude qui corrige ça.

**Comment by Taluu** [comment]
Fixé lors du merge de #1035
