### ISSUE TITLE
La barre d'affichage des cookies prend trop de place.

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1045]
Os : Windows
Navigateur : FF 22

**Problème** : Je trouve l'affichage un peu Grossier.

A voir sur la préprod.

Screenshoot.

![cookies](https://cloud.githubusercontent.com/assets/6066015/3481389/587c3b6e-0370-11e4-96e9-a8ac8f28b29f.PNG)

**Comment by Eskimon** [comment]
Os : Ubuntu 12.04
Navigateur :  Chrome 35.0.1916.153

![screenshot from 2014-07-04 13 44 44](https://cloud.githubusercontent.com/assets/761168/3481404/bb8f0dd0-0370-11e4-8fbc-6d8ab1415a9f.png)

**Comment by Eskimon** [comment]
Et je sais que j'aurais pu donner mon avis plus tot, mais je trouve le bouton/lien "ici" pas adapte... j'aurais plutot vu le terme "refuser" (dans un bouton ?) qui montre une prise de position que "ici" qui donne l'impression qu'on va etre redirige autre part...

**Comment by firm1** [comment]
> je trouve le bouton/lien "ici" pas adapte... j'aurais plutot vu le terme "refuser" (dans un bouton ?) qui montre une prise de position que "ici" qui donne l'impression qu'on va etre redirige autre part...

+1

**Comment by SpaceFox** [comment]
+1 aussi.

Ce qui me chagrine en fait, c'est que lien pour refuser est pratiquement invisible. Pour moi il devrait avoir le même traitement que les autres.

**Comment by vhf** [comment]
Je trouve cette barre très bien. Elle répond exactement aux exigences de la CNIL, où le "ici" est aussi un petit lien : http://www.cnil.fr/vos-obligations/sites-web-cookies-et-autres-traceurs/outils-et-codes-sources/la-mesure-daudience/#c5584

**Comment by Coy0te** [comment]
@SpaceFox : c'est un détail, mais là au moins le réflexe des gens qui ne lisent pas c'est de cliquer sur OK. C'est pas ce qu'il y a de plus éthique, mais si on veut des stats qui tiennent la route, on a plutôt intérêt à ne pas mettre le bouton refuser en aussi gros que le bouton OK... :/

Par contre, je suis d'accord que le fonctionnement du lien "ici" est ambigu.

**Comment by Eskimon** [comment]
En meme temps la CNIL donne une ligne directrice pas une obligation. Si on estime que l'on veut informer l'utilisateur différemment et mettre des termes sans ambiguïtés on peu aussi non ? (parce que vraiment le "ici" stylise comme un lien mais fonctionnant comme un bouton je trouve ca genant, + la semantique du ici...)

On peut rajouter "anonyme" en gras pour rassurer le lecteur ?

> [...] Mesure d'audience **anonyme** [...]

**Comment by SpaceFox** [comment]
>  C'est pas ce qu'il y a de plus éthique, mais si on veut des stats qui tiennent la route, on a plutôt intérêt à ne pas mettre le bouton refuser en aussi gros que le bouton OK... :/

Je préfère avoir un site ethique que des stats précises, mais c'est un avis personnel.

**Comment by vhf** [comment]
Pour moi la priorité n'est pas éduquer les gens sur ce qu'est un Cookie et ce qu'on en fait, mais sur respecter les exigences de la CNIL.

**Comment by SpaceFox** [comment]
> Pour moi la priorité n'est pas éduquer les gens sur ce qu'est un Cookie et ce qu'on en fait, mais sur respecter les exigences de la CNIL.

+1. Pour moi on est en train de discuter le futur là, le site sortir en bêta publique avec la version actuelle du bandeau.

**Comment by Coy0te** [comment]
> Je préfère avoir un site ethique que des stats précises, mais c'est un avis personnel.

Tu extrapoles un peu trop loin. C'est pas éthique vs stats, mais plutôt parfaitement éthique vs suffisamment éthique.

**Comment by firm1** [comment]
Moi ça m'embête juste que la police soit aussi grosse et que la barre me prend 2 ligne pour rien. ça ne devrait pas être aussi aggressif pour les yeux

**Comment by ShigeruM** [comment]
Quel que soit le choix fait par le visiteur, la barre disparaît. On se
moque donc un peu qu'elle fasse une ou deux lignes.

**Comment by firm1** [comment]
> Quel que soit le choix fait par le visiteur, la barre disparaît

Si l'utilisateur choisit de ne pas choisir, et bah il est bien emmerdé.

**Comment by SpaceFox** [comment]
> Si l'utilisateur choisit de ne pas choisir, et bah il est bien emmerdé.

Je crois que c'est exactement le but de ce genre de message, en fait : te
faire choisir.

**Comment by ShigeruM** [comment]
Je voulais dire par là que ça ne concernera que quelques visiteurs (ceux
qui choisissent de ne pas choisir pour une raison obscure donc) et qu'à
partir de là, on se moque un peu d'avoir une ou deux lignes pour cette
barre.

**Comment by Alex-D** [comment]
> Si l'utilisateur choisit de ne pas choisir, et bah il est bien emmerdé.

Je réup, la barre se masquera à la page suivante on considérant que tu as accepté, comme indiqué par la CNIL.

Ce sujet peut être clos, c'est destiné à fonctionner sur toutes les largeurs, je ne peux pas faire un truc qui soit beau partout, je fais donc en sorte que ce soit beau là où c'est possible.

Pour le lien VS bouton, j'y ai songé, mais ça nécessite de revoir la formulation pour pas grand chose je trouve. Les gens qui refusent on de toute façon la plupart du temps une extension navigateur qui fait que dans tous les cas ça sera bloqué.

Pour moi cette bannière est une ânerie décidée par des politiques à la base, je ne pense pas qu'il soit utile d'y passer son temps, et cette issue peut être close.

**Comment by sandhose** [comment]
Je suppose que l'on peut considérer cette issue comme résolue par la PR #1132
