### ISSUE TITLE
Un moyen simple d'écrire des tableaux en markdown

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1048]
Je ne sais pas si vous avez déjà essayé, mais faire un tableau en mardkdown est assez chiant et on a 3 chances sur 4 de se rater.

L'idée est donc d'avoir via un bouton au dessus de la zone de rédaction, une boite modale dans laquelle on éditerait un tableau, et en validant, le contenu devra être inséré dans la zone de texte.

Pour information, la lib [fox js](https://github.com/jamesgpearce/foxjs) facilite grandement le travail à ce niveau.

**Comment by SpaceFox** [comment]
Excellente idée.

**Comment by Alex-D** [comment]
L'idée n'est pas nouvelle. Tu en fais déjà mention ici : https://github.com/zestedesavoir/zds-site/issues/59

> la lib fox js facilite grandement le travail à ce niveau.

Elle ne sert à rien dans notre cas : il faut déjà avoir le code ASCII pour qu'elle fasse quoi que ce soit. Ou alors je n'ai pas compris l'intérêt de la lib.

Dans tous les cas, cette issue est un doublon, je la ferme donc et invite tout le monde à en discuter sur la #59.
