### ISSUE TITLE
Impossible d'éditer un tutoriel

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#1058]
Après avoir importé un tutoriel SdZ, en essayant d’éditer son intro (modification de la catégorie par exemple), on tombe sur une "Internal Server Error".

J'ai testé avec les deux tutoriels actuellement sur la page d'accueil : "Dissimuler un texte dans une image" et "Débuter avec Windows 8". Pour le tuto Windows 8, j'ai essayé avant et après validation, le problème est le même.

En revanche l'édition d'extrait ne semble pas poser de problème.

**Comment by vhf** [comment]
On peut avoir une copie du-dit tuto pour débugger ? (Par email ou par MP, volontiers.

**Comment by ShigeruM** [comment]
Une copie du tuto ? Il suffit de prendre le tuto Windows 8 actuellement sur
la home sur la prod. Plus simplement, il suffit de :
- créer un nouveau mini-tuto (pas essayé avec un big mais Windows 8 étant
  un big, j'imagine que c'est pareil) ;
- ajouter un extrait (le bug ne se produit pas sans extrait) ;
- essayer de modifier l'introduction du tuto ;
- constater l'erreur.

Je viens de faire cela à l'instant sur la prod. Si vous n'arrivez pas à
reproduire le bug, je vous donnerai davantage de détails encore.

2014-07-06 16:19 GMT+02:00 victor felder notifications@github.com:

**Comment by vhf** [comment]
En fait c'est bon avec les tutos des fixtures, merci !
