### ISSUE TITLE
[Markdown] Liens automatiques et meta-liens

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#106]
### Idée de base

Apres une petite lecture [de l'aide au markdown se StackOverflow](http://stackoverflow.com/markdown) j'ai trouvé une idée sympa qu'on pourrait réutiliser.

L'idée est de pré-définir des liens abrégés.
### Liens abrégées

Déjà, de quoi je parle ? De ce genre de chose intégré à markdown de base :

```
Vous pouvez chercher sur [Google]

blabla

[google]: http://www.google.com "Le site google"
```

qui produit le html suivant : 

``` html
<p>Vous pouvez chercher sur <a href="http://www.google.com" title="Le site google">Google</a></p>
<p>blabla</p>
```
### Predefinition

Ma proposition est, vous vous en doutez, d'en définir un certain nombre.
#### Sites connues

La premiere utilisation possible est de prédéfinir une liste de site connue tel que Zeste de savoir himself (accessible avec `[zds]` par ex) ou google, stackoverflow, etc. On peut espérer pour ces sites là de les avoir au moins biens écrit avec un title qui va bien.

Tous ces liens pourraient être stockés dans la db et éditable par les staff.
#### Liens internes

Cela peut faire gagner du temps à la modération en définissant des liens `[règles]` ou `[CGU]` que l'on cite souvent en modération. Ou `[Forum:C]` pour diriger un membre vers le bon forum.

Tous ces liens pourraient être stockés dans la db et éditable par les staff.
#### Meta liens

Une utilisation plus interessante encore pourrait être de faire des meta-liens. Par exemple, sur le forum [VDD] pourrait générer un `<a href="URLDuMessageAuDessus" title="mon Voisin Du Dessus">VDD</a>`.

L'exemple là est un peu gadget mais on peut imaginer un `[POEdit]` pour un liens vers l'édition du message du PO qui pourrait du coup être super facilement inséré quand on demande a un membre d'éditer son message. 

Ces Meta liens ne peuvent pas facilement etre fait en ligne mais en python je pense que leur génération sera assez facile.
### Alors ?

Le plus compliqué dans cette extension, c'est de définir les liens. Du coté python-markdown cela va être ultra facile à ajouter. Si l'utilisateur en re-definit un dans son message, il ecrasera[1] juste localement notre définition donc ce n'est pas du tout contraignant.

Vous en pensez quoi ?

[1]: L'inverse est possible aussi mais me parrait moins pertinent

**Comment by Thunderseb** [comment]
Ca existait sur le SdZ via la balise lien. Trop méconnu, jamais utilisé. 

Perso je ne suis pas trop pour, car peu utile amha.

**Comment by SpaceFox** [comment]
+1 Ths.
En fait j'ai découvert l'existence de ce truc sur le SdZ en voulant éditer
un de mes messages : comme ces nouilles ne stockaient que le HTML final
(... no comment.) ils avaient un dé-parseur HTML --> zCode, qui du coup
transformait par exemple les liens vers Wikipedia en trucs comme <wiki
langue="fr">La page Wikipédia</wiki> (syntaxe non garantie)

**Comment by Coy0te** [comment]
C'était `<lien type="wikipedia" url="..." langue="en">...</lien>` pour la syntaxe zCode wiki, et les tutos en sont plein... Il y avait les mêmes pour Google, la doc PHP et la doc C.

Perso, je pense que c'est un gadget que certains d'entre nous utiliseront (les actifs habitués de ZdS), mais presque personne d'autre.

**Comment by Alex-D** [comment]
Inutile.

Quand tu cite le lien vers l'edition de l'OP : c'est pas terrible. Le but c'est que le membre sache le faire sur les topics futurs. Si tu lui donne un lien, il ne saura pas forcément qu'il existe un lien d'édition...

Pour les différents forums : dropdown du header, clic droit, copier l'url... même pas besoin de changer de page.

Je comprends l'intérêt mais c'est vouloir en rajouter pour pas grand chose. Il y a déjà pas mal de choses à assimiler pour connaître toutes les features actuelles, pas la peine d'en rajouter je pense.

PS : KISS ?

**Comment by cgabard** [comment]
Boarf, je trouvait l'idée sympa, c'etait simple à implémenter et utile. Ça n'allourdissait pas non plus la syntaxe puisque c'etait simplement des liens prédéfinit. Mais bon ça n'a pas l'air de faire l'hunanimité, les issues sont faites pour ça. Je ferme.

**Comment by Coy0te** [comment]
Si on y revient un jour, ça serait pas encore plus simple qu'on en fasse une liste en dur dans le JS de Ths ?

**Comment by cgabard** [comment]
> Si on y revient un jour, ça serait pas encore plus simple qu'on en fasse une liste en dur dans le JS de Ths ?

Le prob est que du coup ce n'est pas accessible aux gens qui n'ont pas JS Activé. Et Andro qui faisait une version mobile va se retrouver à recopier ce fonctionnement.

En soit l'inclure en python est ultra simple, c'est juste un dictionnaire a compléter (les clés etant le champ raccourcis et la valeur l'url de destination). Ce n'est pas beaucoup plus compliqué, voir moins car ça l'obligerais à parser le texte pour les remplacer.
