### ISSUE TITLE
[tutos] Introduction et Conclusion mis à "None" après déplacement d'un extrait

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#1060]
Après déplacement d'un extrait, l'Intro et la Conclusion d'un tuto deviennent `None`.

**Comment by artragis** [comment]
Uniquement si elles sont vides, non?

**Comment by vhf** [comment]
Non.

Si elles sont remplies, elles deviennent `None` quand même.

Elles deviennent `None` dans tous les cas, en fait.

**Comment by artragis** [comment]
bizarre, j'ai pas ce bug sur un mini tuto
Je regarde sur un big tuto.

**Comment by artragis** [comment]
J'ai corrigé le bug, je crée des tests unitaires puis je lance une PR.
