### ISSUE TITLE
Problèmes d'indexation Solr

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1062]
Suite à la MEP de ce soir, j'ai trouvé des erreurs d'indexation Solr  sur ce tuto : http://zestedesavoir.com/tutoriels/190/dissimuler-un-texte-dans-une-image/

> "SearchFieldError: The model '<Chapter: <minituto 'Dissimuler un texte dans une image'>>' has an empty model_attr 'part' and doesn't allow a default or null value."

Je suppose parce que c'est parce qu'il a été cassé par le bug de déplacement des parties, mais c'est à vérifier.

**Comment by SpaceFox** [comment]
J'en ai encore où sur l'indexation de la MEP de la RC2 :S

**Comment by artragis** [comment]
Depuis, tu l'as eu?
Si oui sur le même tuto?

**Comment by artragis** [comment]
est-ce que la mep a causé un nouveau bug de ce côté?

**Comment by SpaceFox** [comment]
Je pense que c'est lié aux bugs des tutos mal publiés. A voir avec la correction idoine.

**Comment by SpaceFox** [comment]
J'ai encore le problème sur [ce tuto](http://zestedesavoir.com/tutoriels/205/la-recherche-dinformations-sur-internet/), bien qu'il ai l'air indexé au moins en partie.

A voir si le re-publier ne règlerait pas le problème ?

**Comment by firm1** [comment]
Je ne sais pas si c'est lié, mais j'ai l'impression que le texte des extrait n'est pas indexé comme il faut.

Typiquement [si je cherche le terme "windows" dans les extraits](http://zestedesavoir.com/rechercher/?q=windows&models=article.article&models=tutorial.chapter&models=tutorial.extract), je ne trouve rien, c'est bizarre.

**Comment by artragis** [comment]
Les extraits sont-ils indexés au moins?

**Comment by SpaceFox** [comment]
Je regarde ça.

**Comment by SpaceFox** [comment]
Visiblement la moindre erreur dans l'indexation arrête l'indexation de toute la suite... et comme je crois bien qu'on a des erreurs dans les indexations de tutos...

**Comment by SpaceFox** [comment]
Alors, c'est très con en fait, et l'indexation des chapitres ne peux pas fonctionner.
- Si on a un big-tuto, un Chapitre appartient à une Partie
- Si on a un mini-tuto, un Chapitre appartient à un Tuto
- Le modèle d'indexation Solr considère qu'un Chapitre _doit_ avoir une Partie **et** un Tuto...

**Comment by artragis** [comment]
je dis ça comme ça, mais **by design**, si on implémente la ZEP 12 ça règlera ce problème. Devons-nous dépenser de l'énergie pour régler un problème qui ne peut se poser dans la nouvelle architecture?

**Comment by SpaceFox** [comment]
Oui, parce que ça m'a pris environ 10 minutes à corriger :)

Et comme ça on peut chercher dans notre contenu en attendant l'implémentation de la ZEP-12 (qui promet d'être grosse).

**Comment by firm1** [comment]
Y'a pas que ça. Il me semble aussi que tout ce qui est indexé ici c'est : 
- les titres des tutoriels/parties/chapitres
- les chemins vers les markdown des tutoriels/parties/chapitres

Le contenu (introduction/conclusion/extrait) n'est jamais indexé. Pour la simple et bonne raison que ce sont les champs qui sont appelé à l'indexation au lieu d'appeler les fonctions qui renvoient le contenu.

**Comment by SpaceFox** [comment]
Je viens de tester, j'ai bien récupéré le mot-clef dans le contenu d'un mini-tuto. Il est même surligné et tout !

**Comment by SpaceFox** [comment]
Pour moi c'est corrigé et mergé, mais j'aimerais bien que @firm1  détaille son message précédent avant de fermer.

**Comment by firm1** [comment]
Ptet bien que ça a été corrigé alors il faudrait vérifier dans Sole lui même ce qui est réellement indexé.

**Comment by SpaceFox** [comment]
Je viens de vérifier et ça fonctionne. Je ne sais pas comment ça marche, ni pourquoi tu pensais que ça ne marcherait pas.

J'ai mis la version actuelle de master en préprod pour vérifier, cf par exemple : http://preprod.zestedesavoir.com/rechercher/?q=windows&models=tutorial.extract

**Comment by SpaceFox** [comment]
Bon, visiblement ça marche en préprod. On rouvrira en cas de problème.
