### ISSUE TITLE
Notifications sur mobile

### ISSUE THREAD

**Issue by coma94** [zestedesavoir/zds-site#1063]
Depuis ce matin les menus deroulant notifications, MP et alertes ne fonctionnent plus sur mobile. Testé sur firefox et chrome mobile.

(Version v1.0-RC1/1a6a5ca)

**Comment by Alex-D** [comment]
Déjà corrigé :)

EDIT : avec cette PR : https://github.com/zestedesavoir/zds-site/pull/1073

**Comment by Eskimon** [comment]
Corrigé :)
