### ISSUE TITLE
Visibilité de tous les forums

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#1065]
En allant dans les sous-catégories de forum ["Communauté"](http://zestedesavoir.com/forums/communaute/) ou ["Savoir"](http://zestedesavoir.com/forums/savoirs/) via le fil d’Ariane, non seulement la liste n'est pas restreinte à cette seule catégorie, mais surtout tous les forums y sont visibles, y compris ceux dont on est pas censé avoir acces (zone staff, corbeille, etc.)

Capture de démonstration chez moi, a gauche la vue général des forums, à droite la page communauté

![bug](https://cloud.githubusercontent.com/assets/6103932/3492432/e9401edc-05a9-11e4-800e-93f61cc51637.png)

**Comment by Eskimon** [comment]
C'est réglé !
