### ISSUE TITLE
BLOQUANT SORTIE PUBLIQUE : Référencement et "rel="canonical""

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1066]
Tout est ici : http://zestedesavoir.com/forums/sujet/448/le-referencement-de-zds/

Je n'ai pas trouvé d'issue Github à propos de ce sujet pourtant complètement bloquant.

Qu'en est-il en réalité ?  Qu'est-ce qui a été fait ? Pas fait ?
Qu'est-ce qui doit être fait pour l'ouverture au public ?

**Comment by SpaceFox** [comment]
https://zestedesavoir.com/forums/sujet/449/actions-pour-louverture/

**Comment by Eskimon** [comment]
@firm1 vient de pousser une branche... https://github.com/zestedesavoir/zds-site/tree/hotfix_issue_1066

**Comment by SpaceFox** [comment]
Corrigé + mergé = fermé.
