### ISSUE TITLE
BLOQUANT SORTIE PUBLIQUE :  Erreur 500 aléatoire sur home

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#1067]
Sur la home du site on a une erreur 500 aléatoire. J'ai l'impression que ça vient des manipulations sur mon tuto, car j'ai eu pas mal d'erreur 500 (lors de l'édition, de la validation notamment). 

Je pense que l'élément déclencheur a été la tentative de validation du tutoriel qui a causé une erreur 500 (testé par @SpaceFox et moi). 

J'ai l'impression que cela touche maintenant tout ce qui est tutoriel (je n'arrive pas à le réimpoter là, après avoir essayé de le supprimer).

**Comment by cgabard** [comment]
Il y aurait une corruption dans la db ?

**Comment by geoffreyc** [comment]
J'ai redémarré gunicorn, ca vous lance toujours les erreurs aléatoires?

On Mon, Jul 7, 2014 at 10:29 AM, Christophe Gabard <notifications@github.com

**Comment by cgabard** [comment]
Plus chez moi

**Comment by SpaceFox** [comment]
https://zestedesavoir.com/forums/sujet/449/actions-pour-louverture/

**Comment by Eskimon** [comment]
Idem chez moi c'est bon, la home et l'edition des tutos (qui provoquait tout deux des 500)

**Comment by cgabard** [comment]
"Dans le doute, redémarrez"

**Comment by geoffreyc** [comment]
Je pense que ça vient du fait q'un worker gunicorn avait crashé, et que
quand il s'occupait de la request en cours, il renvoyait une 500 error.

Je me documenterais sur la meilleur solution pour y remédier, pour qu'au
moins gunicorn se redémarre tout seul quand ca arrive.

**Comment by devock** [comment]
Pour moi c'est ok.

**Comment by ShigeruM** [comment]
Pas bon pour moi, j'ai toujours une 500 quand j'essaire d'éditer un tuto ("Algorithmique pour l'apprenti programmeur" en l'occurrence).

**Comment by vhf** [comment]
@ShigeruM cf. #1068

**Comment by cgabard** [comment]
C'est de retour, je ré-ouvre. 

NB: Shig import/envoie en validation des tutos en ce moment, il semblerait donc que ça confirme la source que mentionnait devock

**Comment by delphiki** [comment]
C'est systématique pour moi sur les pages d'historique de validation des tuto.

**Comment by cgabard** [comment]
Oui en fait il semblerait que quelque chose fasse planter le systeme et une fois que c'est arrivé on a des erreurs 500 tant que gunicorn n'est pas redémarré

**Comment by ShigeruM** [comment]
Je viens de faire quelques tests et j'ai les résultats suivants, si ça peut aider :
- Erreur 500 lors de la validation du big tuto "Développez votre site web avec le framework Symfony2". Depuis j'ai une 500 sur la home.
- J'ai pu valider sans problème le mini tuto " Introduction à l'injection de dépendances en PHP", par contre j’avais une erreur 500 quand j’essaiyais de l’afficher. Après quelques minutes, il semblerait que ça soit revenu à la normal.
- J'ai pu valider sans problème le big tuto "Analysez des données avec Excel". Il s’affiche bien.

En somme je vois surtout un problème lors de la validation du tuto "Développez votre site web avec le framework Symfony2".

Je ne trouve pas de points communs aux actions qui provoquent ces erreurs 500 (parfois c’est à la validation, parfois c’est à l’affichage, parfois c’est un big tuto et parfois un mini, etc.).

**Comment by firm1** [comment]
C'est corrigé (et en prod).

Cependant il faudra reimporter les tutos qui on été importé le lundi 07 juillet. La structure interne a été endommagé par un bug lors de l'édition.

**Comment by Eskimon** [comment]
J'ajouterais qu'il faut etre vigilant sur cette histoire d'erreur 500, notamment au niveau de la validation puisque c'est ce qui semblait poser probleme
