### ISSUE TITLE
Telechargement des tutos : markdown et html

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#107]
Le telechargement des tutos au format markdown a été ajouté recement. J'ai vu sur la PR que c'est uniquement pour les tests pour le moment. Cependant je pense que ce serait bien de proposer aussi cette feaure a terme pour les auteurs.

Au passage je pense que la possibilité de télécharger le html du tuto serait utile. Ou au moins de pouvoir visualiser le tuto en entier. Dans un premier temps pour les tests de conversions toujours. Et parce que cette option caché etait assez appréciée à l'époque sdz, ce que je peux comprendre : Visualiser le tuto en entier sans devoir changer de pages.

**Comment by SpaceFox** [comment]
>  Ou au moins de pouvoir visualiser le tuto en entier. [...] Et parce que
> cette option caché etait assez appréciée à l'époque sdz, ce que je peux
> comprendre : Visualiser le tuto en entier sans devoir changer de pages.

C'était aussi super pratique pour la validation (en tous cas, je m'en
servais souvent pour valider).

Le 22 janvier 2014 10:47, Christophe Gabard notifications@github.com a
écrit :

**Comment by ShigeruM** [comment]
Très utile pour la rédaction aussi (avoir une vue d'ensemble, rechercher
dans tout le tuto...).

De manière générale, plus on propose de formats de sortie, mieux c'est. Si
on a les outils et qu'il "suffit" d'ajouter le bouton pour le permettre, ce
sera très apprécié.

**Comment by firm1** [comment]
Je suis tout à fait pour, mais je m'attelle déjà à ce que le format soit dispo en pdf, si je réussi ça (pour le moment je me heurte à pas mal de problématique), le reste (markdown, html, epub, etc.) sera vachement simple.

**Comment by cgabard** [comment]
Je te l'ai déjà dit : tu aurais moins de prob si tu faisais manger à pandoc le html générer par notre python-markdown. Générer une page html complete peut etre fait facilement avec le code actuel. Et tu prends cette page complete en entrée de pandoc, au moins dans cette première étape.

**Comment by firm1** [comment]
Que ce soit avec markdown ou avec le html comme source, il faut que mes
images soient toutes téléchargées en local et que les url des images soient
relatives pour que pandoc produise ce qu'il faut.

Il faut donc régler ce problème d'images relatives.

Le 22 janvier 2014 11:53, Christophe Gabard notifications@github.com a
écrit :

**Comment by cgabard** [comment]
Ha certe. Mais en soit on doit générer du html valide et donc que pandoc peut manger. Ce qui n'est pas le cas de notre markdown qui n'est pas spécialement standard.

**Comment by firm1** [comment]
Ouaip, on est d'accord.

Le 22 janvier 2014 12:07, Christophe Gabard notifications@github.com a
écrit :

**Comment by firm1** [comment]
C'est fixé, je ferme
