### ISSUE TITLE
Apparition de la mention "None" dans le titre d'un tuto non validé

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#1071]
Sur la page d'un tuto hors ligne (non validé), le titre est complété par la mention " - None".

**Comment by vhf** [comment]
Comment reproduire ce bug ?

**Comment by Eskimon** [comment]
Tu crees un (mini-?)tuto et dans la page de plus haut niveau (celle qui liste les extraits pour les minituto) tu peux voir le titre "< titre du tuto > - None"

![screenshot from 2014-07-07 13 05 44](https://cloud.githubusercontent.com/assets/761168/3494483/b0cade44-05c6-11e4-9dd6-9091fa41caa4.png)
