### ISSUE TITLE
Notifications MP après avoir quitté le MP

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1076]
J'ai beau avoir quitté un MP, je vois les notifications, un clic dessus et la notification disparaît mais j'ai bien une 403.

Quelque chose cloche à ce niveau.

**Comment by firm1** [comment]
Peuxt-tu détailler la procédure ? Je n'arrive pas à reproduire le bug.

Quand tu parles des notifications ? tu parles des notifications par mail ? normalement quand tu veux quitter un MP tu : 
- va dans le MP : le MP est donc considéré comme lu et donc tu n'a plus rien dans la notif
- clique sur quitte quitter le MP : tu sors de la liste des participants

Donc, j'ai beau lire ton issue, je ne comprends pas à quel moment tu bug.

**Comment by Alex-D** [comment]
Nop, je parle des notifications dans le menu en haut.

En gros, j'ai eu un MP avec Eskimon et Sandhose. J'ai parlé dedans et tout. J'ai quitté. Ils ont certainement continué à causer, et du coup j'ai reçu une notif (une seule fois par contre).

**Comment by firm1** [comment]
Te souviens tu du jour ou tu as quitter ce MP et du moment ou tu as vu la notif ? Quelqu'un d'autre arrive a reproduire ce bug ?

**Comment by Eskimon** [comment]
C'était cet aprem. J'ai été le seul à posté, sandhose n'a jamais répondu.

**Comment by firm1** [comment]
Encore d'autres questions (je suis obligé si vos rapports sont pas détaillés :-p )
- Qui était l'auteur du MP ?
- Alex avant de quitter le MP qui était l'auteur du dernier message ?

**Comment by Alex-D** [comment]
Seul @Eskimon peut répondre du coup... j'suis plus dedans pour check. Je pense que c'était Eskimon l'auteur et aussi l'auteur du dernier message.

**Comment by Eskimon** [comment]
Erf... firm1 si je t'ajoute au MP ca peut aider ? parce que je sais pas quand Alex a quitté, si c'était avant ou apres que je réponde... je suppose avant s'il a recu la notif fantome...

**Comment by firm1** [comment]
Je m'occuperai pas forcément de l'issue, c'est juste que je la trouve pas trop claire. Donc m'ajouter au MP ne changera rien. Mais si on sait reproduire le problème, on a plus de chance que quelqu'un le résolve.

**Comment by poulp** [comment]
pareil j'arrive pas à reproduire le problème

**Comment by Eskimon** [comment]
Est-ce que ca c'est deja reproduit chez qqun ou c'etait un coup de pas de bol a l'epoque des 500 ?

**Comment by firm1** [comment]
Des nouvelles ici ? Je ne reproduis toujours pas le bug.

**Comment by Eskimon** [comment]
idem, jamais eu de problemes comme ca... Je penche pour un coup de pas de bol a l'epoque des 500 causé par la validation...

**Comment by firm1** [comment]
Je ferme donc
