### ISSUE TITLE
Barre de pagination vide

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1078]
En bas des articles/tutos, la barre de pagination apparait meme s'il n'y a pas de réactions (ou pas assez pour paginer).

Il faudrait la virer/cacher s'il n'y a pas de quoi paginer.

**Comment by 0hexit** [comment]
Je n'arrive pas à reproduire le bug. T'es sur quelle build ?

**Comment by Eskimon** [comment]
C'est vu en prod', mais je retrouve plus ou... C'était vrai sur l'article de bienvenu quand le site était fermé je crois...

**Comment by 0hexit** [comment]
Bizarre. En local (branche master), la barre de pagination n'apparaît pas, qu'il y ait aucun ou plusieurs commentaires.

**Comment by ArnaudCalmettes** [comment]
Je l'ai constaté également lundi.

**Comment by Alex-D** [comment]
Yop ! This is not a bug, this is a feature !

Ca n'est pas la pagination des réactions, mais la pagination pour aller d'un article à un autre. Je n'ai pas mis de condition car dans le cas d'une utilisation normale du site, il y aura **toujours** plus qu'un article. Inutile de rajouter un test là où ça n'est pas utile.

Si vous y tenez absolument, je peux mettre le test, mais au prochain article posté, ça sera déjà inutile.

**Comment by SpaceFox** [comment]
Ah OK, merci.

Alors il n'y a pas de problème ici, donc je ferme :)
