### ISSUE TITLE
Bulletin d'adhesion international

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1079]
Dans le bulletin d’adhésion à l'association, il faut spécifier son code postal.
Ce dernier est limité à 5 caractères, Pourquoi ?

Je me doute que c'est une cause "historique" mais si vous demandez le pays, vous sous entendez qu'on peut adhérer depuis autre part que la France… et du coup la restriction du code postal n'est plus valide (par exemple chez moi le format c'est <xx-yyy>)

Il serait donc de bon ton de lever ce genre de limite en le rendant peut-être facultatif (certains rare pays n'en possède pas) et en ne faisant pas de restriction sur sa syntaxe.

**Comment by SpaceFox** [comment]
Plus généralement je simplifierais le formulaire complet en  :
- Nom (placeholder : "M/Mme Prénom Nom")
- Adresse courriel
- Adresse (champ multi-lignes, placeholder : "Votre adresse complète, y
  compris le pays")
- Pourquoi voulez-vous adhérer

L'avantage c'est qu'avec ces champs, tous obligatoires, on gère absolument
tous les cas d'adresses / noms foireux qui puissent exister dans le monde.
Et on ne se pose plus jamais la question.

**Comment by Alex-D** [comment]
Le tag front est à retirer ici, le formulaire est complètement géré par le back.

**Comment by Eskimon** [comment]
La phase 1 agrandissant le champ de code postal est faite.
La phase 2 d'internationalisation plus simple du formulaire etant une V2, je laisse le ticket ouvert et passe le label "validation" a "evolution"

**Comment by Alex-D** [comment]
Change également le milestone alors :)

**Comment by Eskimon** [comment]
> Change également le milestone alors :)

Arf ! C'est fait, merci du rappel ^^ Je l'ai passé en 1.x pour pas que ca traine non plus !

**Comment by Alex-D** [comment]
Avec les modifications apportées dans la #1406, le soucis ne se présente plus, je considère donc ce ticket comme résolu, je ferme.
