### ISSUE TITLE
Evolution des outils markdown (python-markdown, pandoc)

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#108]
**note** : C'est une issue long terme, j'ai créé une _milestone_ pour le caractériser
### Contexte

Actuellement dans le code de Zds nous utilisons un markdown personalisée comme langage de rédaction. L'interpréteur utilisé pour générer le html est python-markdown avec un jeu d'extensions personnalisé. Pour générer des pdf et ebook nous envisageons d'utiliser Pandoc qui prend comme entrée de nombreux formats mais prioritairement un markdown avec plusieurs similitudes au notre.
### Evolution Court terme

Le plus simple pour générer les pdf et ebook va être de demander à Pandoc de nous les générer a partir du html produit par python-markdown. Ce html étant valide, la conversion devrait être possible sans trop d'ajustements. 
### Suite 

Cette chaine de conversion n'etant pas idéal, il serait pertinent de la simplifier. L'idéal etant qu'un convertisseur devrait pouvoir prendre notre markdown en entrée et nous fournir un fichier de sortie, quelque soit son type, sans chainer les conversions. 
### Piste
- Pandoc : Il pourrait en soit etre notre seul et unique convertisseur. Il pourrait générer à la fois le html, pdf et ebook. Problème : Même si le markdown proposé l'est avec tout un tas d'extensions activable ou non, il ne semble pas possible d'écrire des extensions perso. La seule solution serait de les injecter directement dans les sources. Problème : C'est écrit en haskell. Avons nous quelqu'un de compétent, dispo et motivé pour ça ? 
- Python-markdown : ne peut générer que du html actuellement. Lui faire générer du md compatible pandoc demande pas mal de modifs
- Autres outils ?

**Comment by firm1** [comment]
Pourquoi ne pas tous simplement adopter le scénario suivant ?

markdown_zds (avec extension) -> markdown_pandoc -> ALL

Le 22 janvier 2014 15:46, Christophe Gabard notifications@github.com a
écrit :

**Comment by cgabard** [comment]
> markdown_zds (avec extension) -> markdown_pandoc -> ALL

C'est l'option envisagé actuellement. Seulement on conserve un format intermédiaire. Et ensuite le convertisseur notre markdown -> markdown pandoc n'est pas si anodin que ça. Avec toutes les contraintes et possibilités, ce n'est pas faisable avec de simples regexp. 

Mais en l'absence de mailleur solution, c'est ce que je pensais faire. J'ai ouvert ce ticket pour voir si il n'y aurait pas d'autres solutions envisageables.

**Comment by cgabard** [comment]
Pour plus de détails, actuellement je m'oriente vers patcher python-markdown et, surtout, les extensions pour insérer le max d'infos sémantique à la génération de l'arbre en mémoire pour pouvoir re-générer un markdown compatible pandoc à la place du html en sortie. Le markdown de sortie pourrat changer (les bold passant de `**` à `__` par exemple, les titres soulignés à ceux avec `#` devant, etc.) mais tant que la sémantique est respecté, le format de sortie devrait etre convenable.

**Comment by firm1** [comment]
J'ai vu que cette issue a été [explicitée dans le dépot zmarkdown](https://github.com/zestedesavoir/Python-ZMarkdown/issues/27), donc je pense qu'on peut fermer celle-ci.
