### ISSUE TITLE
Bandeau cookie sur mobile affiche en permanence

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#1081]
Le bandeau d'info pour les cookies est affiché sur mobile systématiquement et sur toutes les pages, même si on a déjà donné son accord ce qui rend la navigation mobile ultra pénible.

Au moins sur FF android

**Comment by vhf** [comment]
Je confirme Chrome/Android.

**Comment by devock** [comment]
Chez moi c'est ok : Chrome/Android

**Comment by ArnaudCalmettes** [comment]
Je constate le même bug: Chrome 35.0.1916.141 / Android 4.4.2.

Arnaud

2014-07-07 19:24 GMT+02:00 devock notifications@github.com:

**Comment by Eskimon** [comment]
Opera Mini 7.5.33361 / Android 2.3.5 (lol)

Idem, bandeau qui revient tout le temps...
