### ISSUE TITLE
La licence des tutos n'est pas affichée

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1083]
L'information de licence des tutos est bien en base, mais n'est affichée nulle part sur le front... il faudrait corriger ça sans trop tarder :)

**Comment by Eskimon** [comment]
C'est à dire ? Le champ "description" de la licence ?

**Comment by Alex-D** [comment]
Je ne peux plus changer les tags youpi... il faudrait rajouter le tag front, et m'y assigner.

Je peux le faire relativement rapidement je pense.

**Comment by SpaceFox** [comment]
Fait.

**Comment by Alex-D** [comment]
"Facile" : Ah ah ... je ne sais pas qui a mis ça.

Je travail dessus en ce moment, pour le début je vais juste mettre un rendu texte, ça m'aura nécessité d'aller bidouiller dans le views.py pour rendre visible certaines variables.

Par ailleurs, j'aimerais avoir un rendu graphique (avec des icônes) comme prévu par les maquettes. Et du coup il me faudrait le format de `licence.code` qu'a choisi @firm1 

Enfin : licence en anglais s'écrit license. Tout le code est en anglais, mais ça, c'est en français. Pas très grave, juste que c'est perturbant ^^

**Comment by SpaceFox** [comment]
En première approche, afficher en front une info back sans vraiment de transformation, ça ne paraissait pas spécialement difficile.

Après c'est comme tout, on est jamais à l'abri de difficultés cachées (les facilités cachées existent mais sont curieusement plus rares...)

**Comment by Alex-D** [comment]
Juste pour ajouter une petite note positive : j'ai du merdouiller en local, l'information était bien présente. Par contre elle diffère selon qu'on est sur un tuto public ou brouillon (JSON ou BDD).

C'était finalement bien un label "facile" qui collait à la situation.

Mea culpa donc.

**Comment by firm1** [comment]
> Par contre elle diffère selon qu'on est sur un tuto public ou brouillon
> (JSON ou BDD).

Hmm. Si a un moment on va chercher la licence en BD pour l'affichage c'est
que le bug n'est pas vraiment fixé. La licence est toujours dans le JSON
quelque soit l'État du tuto.
 Le 9 juil. 2014 21:37, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
Bah partout je fais tutorial.licence. D'un côté j'ai le retour BDD, de l'autre j'ai le retour JSON.

EDIT : et pour le coup j'ai pas touché au back.

**Comment by firm1** [comment]
Dans ce cas va falloir repasser dessus alors je pense.
Le 9 juil. 2014 23:52, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
Il y a plein de trucs qui sont issues de la BDD sur la version publique à ce que je me souvienne, faudrait que je refasse des tests, mais pendant un moment on pouvait changer les tags, le titre, l'image, etc. Et tout ça était répercuté en public :/

**Comment by firm1** [comment]
Les choses ont bien évolués depuis.

Techniquement, tout ce qu'on voit dans le JSON (titre, description,
licence) devrait être ce qui est affiché. Si c'est pas le cas, il y'a
visiblement un bug
Le 10 juil. 2014 00:04, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
Je pense qu'il faudrait figer les tags aussi dedans. Je (tu ?) crée une issue dédiée du coup ?

**Comment by firm1** [comment]
Les tags, le logo de l'image, bref ... Les metadonnées.
Le 10 juil. 2014 00:08, "Alexandre Demode" notifications@github.com a
écrit :
