### ISSUE TITLE
Erreur 500 dans la liste des tutoriels/articles d'un membre

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1084]
[Via paspro](http://zestedesavoir.com/forums/sujet/453/erreur-500-dans-la-liste-des-tutorielsarticles-dun-membre/?page=1#p4488)

Lorsque que l'on est sur le profil d'un membre, nous avons accès à la liste des tutoriels/articles qu'il a rédigé. Sur cette page, si on modifie l'adresse de manière à envoyer autre chose qu'un nombre en lieu et place de l'ID du membre, le serveur retourne une erreur 500.
- Url d'origine : http://zestedesavoir.com/tutoriels/recherche/254/
- Url modifiée ("aza" remplace mon ID et ça plante) http://zestedesavoir.com/tutoriels/recherche/aza/

L'erreur 500 semble indiquer qu'il n'y a aucune vérification quant à la nature du paramètre passé … assez fâcheux :(

Je pense qu'il faudrait un get_objet_or_404 quelque part...

**Comment by artragis** [comment]
pff et eskimon qui me grille...
