### ISSUE TITLE
Erreur 500 à l'export du tuto windows

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#1086]
Je remonte l'erreur parce que c'est un dégat collatéral de l'issue #1068 .
Comme nous n'avons pas d'autres big tuto sur le site, je ne peux pas dire quoi que ce soit.
En tout cas l'export au format pdf du bigtuto windows ne fonctionne pas.

**Comment by firm1** [comment]
Plus d'erreur 500 a l'export.
