### ISSUE TITLE
Erreur 500 sur le fil d'ariane des membres

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#1088]
Le fil d'ariane des membres mène à un lien mal formé (modèle slug plutôt que id). C'est sûrement lié à #556. Signalé [ici](http://zestedesavoir.com/forums/sujet/460/erreur-500-lien-foireux-dans-le-fil-dariane-forums-pseudo-membres/)

**Comment by firm1** [comment]
Je prends !

**Comment by Alex-D** [comment]
Doublon avec la https://github.com/zestedesavoir/zds-site/issues/1095

**Comment by Eskimon** [comment]
Mergé = fermé :)
