### ISSUE TITLE
Impossible d'accéder à la doc' de Markdown du site

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1089]
Via [benyhex](http://zestedesavoir.com/forums/sujet/457/erreur-500-doc-markdown/?page=1#p4546) : 

> N'étant pas un pro du Markdown j'ai souhaité en savoir plus sur sa syntaxe.
> Lors du post (rapide) d'une réponse j'ai cliqué sur "Afficher l'aide Markdown" et là aucun souci.
> Mais quand je clique sur l'url : Voir la documentation complète (cf copie d'écran) j'obtiens une erreur 500

Autrement dit, lien en dur qui a bougé.

**Comment by Eskimon** [comment]
poke @Alex-D ;)

**Comment by Alex-D** [comment]
Comme dit sur IRC : le soucis vient du fait que l'article a été supprimé... je travaille sur la validation, il y a eu un oubli côté front (et peut-être côté back) autour de la validation des articles.

J'y travaille donc.

**Comment by Eskimon** [comment]
Ok, je laisse ouvert pour le monitoring, ca sera fermé avec l'erreur 500 je pense.

**Comment by Alex-D** [comment]
Plop ! C'est à fermer, ça a été résolu :)
