### ISSUE TITLE
Utiliser object en lieu et place de iframe pour les videos

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#109]
Actuellement les balises videos produisent pour bon nombre de fournisseurs un objet html iframe. Un element object serait meilleur pour l'accessibilité (dixit @Alex-D :D )

**Comment by cgabard** [comment]
pour moi/pour info : Ce problème est plus subtil qu'il n'y parrait. En soit cela pourrait etre réglé en une ligne MAIS pour une raison mystérieuse le contenu mit dans les balises "object" disparaissent dans le html final. A priori dans les traitements précedents (vérifié pendant l'extension video et celle des legende) l'arbre en mémoire contient bien encore son contenu. Ce contenu disparait donc soit au niveau du parseur arbre -> html, soit c'est django qui le virre... A creuser

**Comment by firm1** [comment]
C'est normal que [les vidéos ne s'affichent pas](http://preprod.zestedesavoir.com/forums/sujet/8/les-renards-dirigent-le-monde?page=1#p73) ?

**Comment by cgabard** [comment]
En effet le iframe dans la balise video ne semble pas passer alors que chez moi ça passait, je regarderait ça

**Comment by Alex-D** [comment]
Je rajoute que pour les liens YouTube il serait intéressant de rajouter `?html5=True` dans l'url pour être full HTML5 chez qui le peut : chargement plus rapide + pas de flash.

**Comment by cgabard** [comment]
Il y a plusieurs probs : Les iframes dans les balises videos dans une balise figure ne semblent pas rendu chez moi (cf dernie liens de firm1). A voir à quels endroits le prob se pose. Peut etre une limitation de navigateurs.

Le deuxième prob est que, suite a ton conseil, j'ai voulu passer par un element type "object" flash. Mais ça ne marche pas. Dans markdown j'injecte bien les bon sous elements parameters dans l'arbre DOM mais sur la page rendu ils ont disparues. 

Je n'ai pas encore vérifié si c'est markdown qui les vire ou si c'est Django...

**Comment by Alex-D** [comment]
C'est un peu bizarre cette histoire :/
Je ferais des tests en full HTML pour voir.

**Comment by cgabard** [comment]
Bon dans un premier temps, pour la beta je vais "fixer" cette issue sans la corriger.

Un iframe dans une balise video n'est pas rendue au moins par FF. Cela fait probablement une bonne raison pour ne pas l'utiliser.

Enfin passer aux object avec le module actuel pose des problèmes. Sachant que youtube recommande les iframe et que je n'ai pas beaucoup de temps, je vais remettre l'utilisation des iframe pour youtube.

**Comment by Alex-D** [comment]
Perso, ça me va. C'est pas super important dans l'absolu.

**Comment by cgabard** [comment]
C'est mergé, je ferme tant que l'utilisation des iframe n'est pas un probleme critique.
