### ISSUE TITLE
Impossible de filtrer les forum par catégorie

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#1090]
Lorsqu'on arrive sur le lien zestedesavoir.com/forums/communaute il montre la liste de tous les forums en ométant les deux catégories, c'est tout. Les forums qui ne font pas partie de communauté sont quand même affichés.
A noter que le problème est le même si on va sur zestedesavoir.com/forums/savoirs
Problème signalé [ici](http://zestedesavoir.com/forums/sujet/454/classement-des-forums-dans-longlet-communaute/)

**Comment by firm1** [comment]
Je prends !

**Comment by Eskimon** [comment]
C'est réglé !
