### ISSUE TITLE
La liste des topics par tag envoie une 500

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#1092]
aller sur une url du type http://zestedesavoir.com/forums/sujets/tag/9/regression/ envoie une 500. C'est une régression par rapport à la béta privée.

**Comment by Eskimon** [comment]
voici un lien de ce qui a été récemment fait sur les tags si jamais ca peut aider : https://github.com/zestedesavoir/zds-site/issues/994

**Comment by artragis** [comment]
Non, le problème c'est les optimisations faites par @firm1.
Quand il fait des truc comme ça : `.exclude(Q(forum__group__isnull=False) & ~Q(forum__group__in=u.groups.all()))`.
Désolé, mais là mes connaissances sont dépassées. Je ne peux rien faire, si ce n'est dire que la variable u (la préposition qui précède a été autocensurée) n'existe pas.

**Comment by Eskimon** [comment]
u c'est utilisé pour user je parie... c'est dans quel fichier/ligne ?

**Comment by artragis** [comment]
`zds/forum/views.py` à partir de la ligne 873 (c'est mis plusieurs fois dans la fonction).
