### ISSUE TITLE
Erreur 500 lors de la réservation d'un tuto en validation

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#1094]
Lorsqu'un compte staff réserve un tuto en validation, il tombe sur une erreur 500. Le tuto est néanmoins bel et bien réservé.

Pour reproduire il suffit d'essayer de réserver un tuto en attente de validation.

**Comment by vhf** [comment]
Pas réussi à reproduire le bug en local.

**Comment by ShigeruM** [comment]
Le problème ne se présente plus sur la prod. Je ne sais pas si cela est dû aux MEP d'hier soir. Toujours est-il que ça fonctionne à nouveau donc je ferme.
