### ISSUE TITLE
Lien erronné dans le fil d'Ariane Forums -> Pseudo -> Membres

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1095]
[Via btw03](http://zestedesavoir.com/forums/sujet/460/erreur-500-lien-foireux-dans-le-fil-dariane-forums-pseudo-membres/#p4525)

Sur la page qui liste les sujets crées par un membre (http://zestedesavoir.com/forums/sujets/membre/229/), le lien sur le texte "Sujets crées" du fil d'Ariane pointe vers http://zestedesavoir.com/forums/sujets/membre/btw03/ (dans mon cas), ce qui lance une erreur 500 quand on clique dessus vu que l'url de la page à l'air d'être avec l'ID du membre.

Ca a l'air d'être la même chose dans le cas de la consultation des messages postés.

**Comment by Alex-D** [comment]
C'est du front, faudrait changer le tag :)

**Comment by Eskimon** [comment]
Hop mergé, fermé !
