### ISSUE TITLE
Bouton d'aide au markdown qui se promène

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1099]
Le bouton d'aide au markdown se promène.

Au lieu de rester sagement en dessous de la zone de texte, il a tendance à partir en bas a gauche dans la sidebar...

**Comment by viki53** [comment]
+1 

Chez moi, en tout cas que la page de rédaction d'une partie de tuto, il arrive carrément à s'incruster en partie dans le footer.

J'ai fait un screen si ça vous intéresse : http://zestedesavoir.com/media/galleries/333/e516a0d4-cc89-4765-8e69-73eee52fe5ec.png

**Comment by Alex-D** [comment]
A Valider, puis fermer :)

**Comment by Eskimon** [comment]
C'est beaucoup mieux mais ca bugouille encore un peu (ca décale d'une ligne les boutons de réponses)...

Ca m'est arrivé lorsque j'ai fait un nouveau sujet (répondre a un sujet marche bien en revanche)

![screenshot from 2014-07-14 10 39 01](https://cloud.githubusercontent.com/assets/761168/3568596/246899f6-0b33-11e4-8f19-c644eeb490b3.png)

**Comment by Eskimon** [comment]
J'enleve le label "Bloquant V1" car la version actuelle est largement utilisable meme avec le petit defaut susmentionne.

**Comment by Alex-D** [comment]
> C'est beaucoup mieux mais ca bugouille encore un peu

J'ai vu, et c'est voulu. Dans cette configuration, le bouton est lié au champ, tandis que dans les formulaires "répondre" en bas des pages c'est lié au champ mais il n'y en a qu'un donc je peux me permettre de gagner de la place.

Le problème, s'il en est un, n'est donc pas soluble. C'était donc bien à fermer.

**Comment by Eskimon** [comment]
Ok, je referme :)
