### ISSUE TITLE
Make a newsletter teasing system

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#11]
il faudrait mettre en place une page d'accueil avec un champ permettant de rentrer son adresse mail afin d'être tenu informé de la sortie officielle du site. Je pourrai donner l'URL aux auteurs pour qu'ils s'y ajoutent.

Ca permettra de faire un peu de teasing et de "collecter" des utilisateurs potentiels, qui seront dispos une fois le site ouvert.

**Comment by Thunderseb** [comment]
Ouais, ça me permettra de commencer à démarcher les auteurs

**Comment by firm1** [comment]
Le backend de la Newsletter est terminé.

Voir [ce commit](https://github.com/Taluu/ZesteDeSavoir/commit/6763e2369654b5d0b84974ae0f31d4261f12fb74)
