### ISSUE TITLE
Ajouter la gestion de la licence pour les articles

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1109]
Actuellement les articles n'ont aucun choix de licence. Il me semble qu'il devrait également être possible de sélectionner une licence comme pour les tutoriels.

**Comment by pierre-24** [comment]
Je prend, je pense avoir une idée de comment faire.
(j'ai pas le droit de me l'assigner, si quelqu'un pouvais)

**Comment by Eskimon** [comment]
> (j'ai pas le droit de me l'assigner, si quelqu'un pouvais)

Voila cadeau !

> Je prend, je pense avoir une idée de comment faire.

Je n'ai pas regarde le code, peut-etre est-il possible de s'inspirer du code des tutos

**Comment by pierre-24** [comment]
> Je n'ai pas regarde le code, peut-etre est-il possible de s'inspirer du code des tutos

Exactement ce que je comptais faire (j'ai d'ailleurs regardé ledit code avant :p ). Loin de moi l'idée de réinventer la roue.

**Comment by pierre-24** [comment]
Fermé, donc :)
