### ISSUE TITLE
Un attribut pubDate dans les flux RSS

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1113]
[Via Javier](http://zestedesavoir.com/forums/sujet/478/un-attribut-pubdate-dans-les-flux-rss/)

> Je suis en train de faire mon petit projet de site qui agrège les différents "pouls" de ZdS (RSS, Twitter, et peut-être IRC qui sait) pour mettre ça dans une petite timeline sympa mais comme y'a pas d'attribut pubDate c'est un peu pourri pour agréger les sources (bah ouais, comment je sais si le message a été posté avant ou après le Tweet moi :( )
> 
> D'avance merci ;)

**Comment by artragis** [comment]
I take.

**Comment by 0hexit** [comment]
A fermer.
