### ISSUE TITLE
Reactions sur Article (Tuto?), lien erronne

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1114]
Le lien ou l'ancre de la pagination pour les réactions sur les articles (et les tutos ?) ne fonctionne pas comme il devrait...

Lorsque l'on change de page de réactions, on est renvoyé en haut de l'article plutôt qu'au niveau des commentaires.

Ce comportement peut-etre observe sur l'article : http://zestedesavoir.com/articles/30/bienvenue-sur-la-beta-de-zeste-de-savoir/

**Comment by Alex-D** [comment]
Ca va être chaud patate à corriger ça par contre... faut nécessairement passer une variable qui indique le nom de l'ancre, je ne vois pas d'autre solution (pas possible de le gérer de façon dynamique et automatique partout).
