### ISSUE TITLE
suppression des chapitres d'un big-tutoriel inopérante

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#1119]
Supprimer un chapitre d'un bigtuto ne met pas à jour le sommaire du tuto car si le changement est mis en place côté système de fichier, il ne l'est pas en bdd.
Signalé [ici](http://zestedesavoir.com/forums/sujet/514/bug-suppression-des-chapitres-dun-big-tutoriel/?page=1#p5195)

**Comment by firm1** [comment]
C'est corrigé (et en prod).

Je ferme.
