### ISSUE TITLE
Impossible de voir les tuto en cours de validation

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#112]
Quand je vais dans l'interface degestion des tutos et que je cloque sur n'importe quel tuto en validation, je ne peux pas le voir. Pourquoi ?

**Comment by firm1** [comment]
> Pourquoi ?

Parce que **actuellement** pour consulter un tuto en validation, il faut soit être son validateur (s'assigner le tuto avant qu'il ne soit en ligne), soit être l'un des auteurs du tuto.

Après, je ne sais pas si c'est le comportement qu'on souhaite obtenir. Mais je l'avais codé ainsi.

**Comment by dreherch** [comment]
Le comportement souhaité, ce serait d'avoir un groupe qui peut lire les
tutos en rédaction et validation (ce groupe étant probablement le Staff).
Tiens, d'ailleurs, il faudra l'indiquer dans les CGU qu'on peut lire le
contenu en cours d'écriture (même si sa publication doit faire l'objet d'un
accord de l'auteur, conformément à la loi).

**Comment by cgabard** [comment]
> Après, je ne sais pas si c'est le comportement qu'on souhaite obtenir. Mais je l'avais codé ainsi.

A la limite je peux comprendre, mais dans ce cas ne met pas de liens qui mene vers un 404.

Perso pour moi je pense que tu devrais laisser la possibilité aux autres staff de le consulter. Ça permetrat au validateur officiel de demander un avis à certains de ces collegues. Par contre seul celui qui est le validateur assigné devrait pouvoir le mettre en ligne.

Sinon du coup je ne vois pas le pseudo du validateur assigné aux tutos alors qu'il y a la colone de présente.

**Comment by firm1** [comment]
On va faire comme la dit @JacenSolo je pense que c'est le meilleur compromis.

> Sinon du coup je ne vois pas le pseudo du validateur assigné aux tutos alors qu'il y a la colone de présente.

ça se sont les cas ou l'auteur était staff et donc il a validé son tuto de lui même.

Mais en soit, il faudrait que tous les staff puissent lire/valider tous les tutos.

**Comment by firm1** [comment]
La PR précédente fixe le bug.

Je ferme
