### ISSUE TITLE
La page de présentation de l'asso n'est pas claire

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1121]
Il faudrait donner le montant de l'adhésion aussi et dire que ça n'ouvre aucun droit sur le site. Peut-être mettre un petit laïus sur le fait que ça permet de participer à l'AG annulle où le CA est élu, que donc ça permet de peser dans les orientations de l'asso, etc.

**Comment by Fumble** [comment]
Informations à reprendre également sur le formulaire d'adhésion.

**Comment by Eskimon** [comment]
Merged, je ferme !
