### ISSUE TITLE
Favoris

### ISSUE THREAD

**Issue by viki53** [zestedesavoir/zds-site#1122]
Petite feature que je trouve intéressante : des favoris.

En gros qu'on puisse marquer (épingler) des topics ou des tutos (voire autre chose) pour pouvoir y accéder rapidement plus tard (via la sidebar, par exemple) depuis n'importe quelle page (ou presque) du site.

La deuxième partie, qui dépend de la première mais peut être développée a posteriori : être tenu au courant des nouveautés de ces favoris. Par exemple les mises à jour du tuto (qu'il soit en bêta ou non) ou les réponses au topic via une notification.

Le post d'origine sur le forum : http://zestedesavoir.com/forums/sujet/512/favoris/

**Comment by Eskimon** [comment]
J'avais pas vu, mettre a mettre en relation avec ca non ? https://github.com/zestedesavoir/zds-site/issues/585

**Comment by viki53** [comment]
Plus ou moins, oui. D'un côté c'est pour être averti des modifs, de l'autre pour retenir l'avancement façon marque-page dans un livre…

**Comment by cgabard** [comment]
Ce ticket est prit en charge par la zep 06. on a aucun interet a garder ce ticket ouvert je pense. Ce n'est qu'une sous-partie de la zep 06. La zep n'étant pas validé -> A fermer

**Comment by gustavi** [comment]
Oui. Je ferme.

**Comment by Eskimon** [comment]
Lien vers la ZEP 6 : http://zestedesavoir.com/forums/sujet/678/zep-06-favoris-et-autres-suivi-dactivite/
