### ISSUE TITLE
[Galeries] Impossible d'éditer le titre/légende d'une image sans la réuploader

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1123]
Quand on édite une image dans une galerie, toute modification nécessite de réuploader l'image, sinon on a l'indication "champs requis" sur l'input file.

Aussi, il faudrait changer le bouton "Ajouter" en "Editer".

**Comment by poulp** [comment]
Oui, on peut pas mettre de valeur par défaut sur un champ fichier, une solution serait de mettre le champ image à `required = False` et de splitter en deux formulaires. Un pour l'ajout, l'autre pour l'édition.

**Comment by Alex-D** [comment]
Je pense que c'est la seule solution propre (deux formulaires distincts).

**Comment by SpaceFox** [comment]
Je prends.

**Comment by Eskimon** [comment]
Merged, je ferme !

**Comment by Eskimon** [comment]
Apparemment cette resolution aurait cassee les galleries...
QQun peut verifier ? (ping @Florianboux ?)
http://zestedesavoir.com/forums/sujet/768/le-style-des-boutons-semble-se-casser-la-figure/?page=1#p10216

**Comment by pierre-24** [comment]
Objectivement, je doute un peu que le problème viennent "simplement" de cette PR, qui a été mergé dans _master_ il y a 10 jours, et depuis, la galerie fonctionnait toujours (et fonctionne encore en local chez moi alors que j'ai pas mis à niveau).

En plus je comprend pas l'erreur --"

**Comment by pierre-24** [comment]
**EDIT:** Par contre, si on remplace "image" par "img" dans `zds/gallery/views.py` (plus particulièrement `edit_image()`) et dans la template, ça refonctionne de nouveau. Donc peut-être que "image" est employé quelque par et est écrasé !

**Comment by Axylium** [comment]
J'ai testé la branche de @SpaceFox chez moi en local, est tout est ok.

**Comment by pierre-24** [comment]
Nan, c'est pas la branche de Spacefox, c'est une branche de ... @Alex-D : dans [templates/base.html à la ligne 48](https://github.com/zestedesavoir/zds-site/blob/master/templates/base.html#L48), y'a un `{% captureas image %}` (issus de [ce commit là](https://github.com/zestedesavoir/zds-site/commit/cc95b4613a9d8cab1d15b6fcfc8bacc30cac7f01)). Du coup `image` est violemment écrasé, et marche plus sur la template [/templates/gallery/edit.html](https://github.com/zestedesavoir/zds-site/blob/master/templates/gallery/image/edit.html) qui fait lui aussi appel à une variable `image`. Du coup, comme je l'ai dit, si l'un ou l'autre change de nom, ça fonctionne de nouveau.

À voir ce qu'on fait.

**Comment by Eskimon** [comment]
Et ca vient de [cette PR](https://github.com/zestedesavoir/zds-site/pull/1235) apparemment...

**Comment by pierre-24** [comment]
C'est ce que je pensais aussi, mais j'avais pas de preuve. Du coup, je suis pas content de @firm1 : la QA, c'est un truc sérieux ^^

**Comment by Alex-D** [comment]
Je réouvre, et je m'en charge. En gros, faut pas que j'utilise la variable `image` car elle est déjà utilisée ailleurs ?

**Comment by pierre-24** [comment]
Exactement :)

**Comment by Alex-D** [comment]
A valider dans la #1258.
