### ISSUE TITLE
[Galeries] Limite d'upload imprécise, aucun message d'erreur

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1124]
J'ai voulu envoyer une image de plusieurs Mo dans une galerie. Elle n'est passée qu'en deçà de 1 Mo. Est-ce qu'il y a une limitation de ce côté ? Car ça n'est pas clair du tout.

Aussi, l'image était très grande, genre plus de 5000px de large, mais je pense que c'est le poids qui a empêché l'upload.

De plus, lors de l'erreur, on a aucune message d'erreur, le formulaire nous revient, pré-rempli, sans l'image.

**Comment by Axylium** [comment]
Après test, c'est effectivement le poids qui pose problème et non la taille de l'image ! Les images de plus de 1Mo, ne passent pas le formulaire.

**Comment by firm1** [comment]
Pour information, on limite la taille des images (vous vous en doutez que notre serveur n'as pas de disque illimité). Le paramètre est réglé [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L258) actuellement à 1Mo donc.

Mais il faut prévénir l'utilisateur de ce problème lorsque c'est le cas. La solution est assez simple au final, il suffit d'aller [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/gallery/views.py#L278) enlever la condition `and request.FILES["physical"].size < settings.IMAGE_MAX_SIZE` et ajouter plutot ce controle à dans le [formulaire directement](https://github.com/zestedesavoir/zds-site/blob/dev/zds/gallery/forms.py#L108) en rajoutant un méthode clean qui vérifie la taille de l'image. La méthode clean ressemblerait à un truc du genre (à vérifier la syntaxe) : 

```
def clean(self):
        cleaned_data = super(ImageForm, self).clean()

        physical= cleaned_data.get('physical')

        if physical.size < settings.IMAGE_MAX_SIZE :
            self._errors['physical'] = self.error_class([u'Votre image est trop lourde, la limite autorisée est de : ' + str(settings.IMAGE_MAX_SIZE / 1024) + ' Ko)'])
        return cleaned_data
```

Ce qui aura pour conséquence d'afficher le message d'erreur à l'utilisateur s'il tente un upload au dela de la limite.

Ne vous génez donc surtout pas pour corriger le problème.

**Comment by Axylium** [comment]
Je vais essayer de m'en occuper ce matin.

**Comment by Axylium** [comment]
Quelque chose que @Eskimon a relevé et il me semble qu'il n'a pas tord, cette ligne : 

`if physical.size < settings.IMAGE_MAX_SIZE :`

Ne devrait pas plutôt être : `if physical.size > settings.IMAGE_MAX_SIZE :`
Car c'est si l'image est trop lourde qu'on retourne une erreur et non le contraire.

**Comment by Eskimon** [comment]
Test et dis nous :D C'est souvent le moyen le plus rapide ;)

**Comment by firm1** [comment]
> Test et dis nous :D C'est souvent le moyen le plus rapide ;)

+1

mais oui, je me suis trompé sur l'opérateur. je l'écris comme ça à la louche hein, j'ai pas testé vraiment.

**Comment by Axylium** [comment]
@firm1 je t'ai envoyé un MP sur ZdS à cause d'un problème que je rencontre !

**Comment by Axylium** [comment]
Ping @Eskimon.

Il faudrait fermer, vu que c'est merger. ;)
