### ISSUE TITLE
Bannière de cookies : les cookies d'Analytics passent quand même

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#1125]
Je me suis rendu compte de deux choses pour les cookies des stats : 
- Si on refuse d'avoir des cookies, on les a quand même (_ga apparait)
- Je viens de vérifier : on doit avoir le consentement du visiteur avant de pouvoir exécuter les stats (même pour la 1ère fois) et sur ZdS il s'affiche avant d'avoir fait son choix.

En fait il manque juste, à priori, la condition qui permet d'exécuter le code de google tag manager si jamais le cookie de consentement n'est pas présent ou s'il est à false.

**Comment by sandhose** [comment]
En fait, c'est que GA est quand même lancé si l'utilisateur n'a rien choisis, d'où les cookies qui restent... Pour moi, c'est le comportement normal, a moins que le CNIL en ai décidé autrement

—

**Comment by devock** [comment]
La CNIL dit : 

> d'un consentement préalable de l'utilisateur avant le stockage d'informations sur l'équipement d'un utilisateur ou l'accès à des informations déjà stockées.

http://www.cnil.fr/vos-obligations/sites-web-cookies-et-autres-traceurs/que-dit-la-loi/

Donc on doit exécuter le GA après la décision de l'utilisateur.

Avant de fait cette issue j'ai testé le scénario suivant : 
- J'ai supprimé tous les cookies de ZdS
- J'ai refusé les cookies 
- J'ai supprimé le cookie _ga
- J'ai réactualisé la page
- J'ai zieuté les cookies et _ga était de retour. 

De toute façon ça se voit au code, le seul bout de code que j'ai vu dans le JS pour ça c'est la partie "on place le cookie avec la réponse de la personne".

**Comment by devock** [comment]
En regardant sur GA, je vois bien qu'il arrive à me pister.

**Comment by Alex-D** [comment]
Il aurait manqué le tag front à cette issue.

La PR est en attente de validation -> merge.
