### ISSUE TITLE
Historique de validation: Erreur 500

### ISSUE THREAD

**Issue by coma94** [zestedesavoir/zds-site#1126]
Lorsqu'on veut consulter l'historique de validation d'un tuto (staff) on a une erreur 500 systématique.

**Comment by coma94** [comment]
Lorsque l'on consulte cet historique depuis un compte non-staff on a une Erreur **403**.

**Comment by Alex-D** [comment]
> Lorsque l'on consulte cet historique depuis un compte non-staff on a une Erreur 403.

Hum, c'est normal en fait, après réflexion. La page d'historique présente la possibilité de réserver la validation du tuto, du coup c'est dédié au staff.

L'historique des version est lui dédié aux membres.

Est-ce que tu as le bouton "historique de validation" quand t'es non-staff ?

**Comment by Eskimon** [comment]
> Est-ce que tu as le bouton "historique de validation" quand t'es non-staff ?

Oui (sur ma local)

**Comment by Alex-D** [comment]
C'est à fermer : corrigé dans la #1111
