### ISSUE TITLE
Intro et conclusion non retournés à l'affichage/édition

### ISSUE THREAD

**Issue by viki53** [zestedesavoir/zds-site#1128]
J'ai pas réussi à trouver d'issue qui évoque le sujet, pourtant ça a été évoqué dans le forums.

À l'affichage ou à l'édition d'un chapitre, l'introduction et la conclusion ne sont pas affichés, pourtant elles sont bien présentes dans l'archive et mises à jour.

Du coup, pour toute modification il vaut mieux avoir une archive de côté pour avoir une base dans le `textarea`. Et pour la lecture, il faut se passer des intros/conclus des chapitres…

Si ça pouvait être réglé assez rapidement (et passé en prod, pour le coup), ce serait cool. :) 

[EDIT] D'ailleurs, je viens d'avoir le même genre de problème à l'édition d'un extrait : le titre était présent dans l'input, mais pas de contenu dans le textarea

**Comment by artragis** [comment]
Etrange étrange... les formulaires sont pourtant bien remplis côté back.

**Comment by artragis** [comment]
Quoi que, j'ai un doute : Lorsqu'on fait un view_any, pour accéder au dépôt, on fait : 

``` python
chapter["intro"] = get_blob(repo.commit(sha).tree,
                                            chapter["introduction"])
chapter["conclu"] = get_blob(repo.commit(sha).tree,
                                             chapter["conclusion"])
```

alors que quand on remplit les form, on fait : 

``` python
ChapterForm({"title": chapter.title,
                                "introduction": chapter.get_introduction(),
                                "conclusion": chapter.get_conclusion()})
```

**Comment by viki53** [comment]
J'y connais pas grand chose en python, mais si les méthodes en question ne renvoient rien, on est mal barrés… \o/ 

Enfin, tout ça pour dire que j'aimerais bien pouvoir continuer à rédiger mon tuto tranquille, sans avoir à me demander si mes contenus sont bien lisibles…  

J'ai déjà assez à faire pour tout rédiger et pondre le code qui va avec :-°

**Comment by Alex-D** [comment]
Le tag front est à retirer sur cette issue. Le front utilise les formulaires construits par le back donc ça ne peut pas venir de là.

**Comment by Eskimon** [comment]
Apparemment ce souci apparait aussi de temps en temps sur le contenu...

http://zestedesavoir.com/forums/sujet/626/problemes-daffichage-du-contenu-des-extraits-a-ledition/

**Comment by firm1** [comment]
C'est fait (et en prod).

Il se peut que la structure interne de vos tutos ait été endommagé par le bug. N'hésitez pas a le faire savoir.

**Comment by viki53** [comment]
Ça a pas l'air d'être au point, du moins chez moi : les intros et conclusions actuelles ont sauté. 

Heureusement que j'ai une copie en local pour ré-importer une bonne partie…

Par contre vu que j'avais envoyé en validation, ça se passe comment une fois que j'ai ré-importé ? J'envoie à nouveau ? Vous avez déjà les bons contenus ?

**Comment by Alex-D** [comment]
> J'envoie à nouveau ?

Oiui, quand tu envoie en validation, ça pointe sur le dernier commit au moment de la validation. Du coup si tu fais d'autres commits après, toi tu les vois, mais pas les validos. En tous cas, c'est ça en théorie.

**Comment by firm1** [comment]
Vik : le fait que tu ais perdu les intro actuelles est normal. Le bug faisait que tout ce que tu editais depuis allais dans une sorte de noir.
Il faut donc (mais ça tu l'as compris) refaire tes intros (heureusement que tu as penser a sauver l'archive, sinon on t'aurais filé ça en piochant sur le serveur).

En ce qui concerne la validation, tu dois mettre a jour ta version de validation pour que les validos voient la dernière version que tu souhaite proposer.

Désolé pour les désagréments donc.

**Comment by viki53** [comment]
Pas de souci, tout est fait de mon côté, ça m'a pris 5 minutes. Plus qu'à attendre la validation (d'ailleurs, je sais pas comment ça se passe par rapport à une partie qui n'est pas à publier — mais c'est un autre sujet).

J'avais commencé à faire des backups réguliers quand j'ai vu que les intros/conclus étaient pas affichées : la première fois je voulais voir si c'était enregistré, puis j'ai préféré garder un backup _au cas où_… Et j'ai bien fait ^^

**Comment by Eskimon** [comment]
Juste pour rassurer les autres auteurs : Rien n'est perdu cependant ! Il faut juste contacter les admins pour récupérer le contenu "absent"

**Comment by firm1** [comment]
> d'ailleurs, je sais pas comment ça se passe par rapport à une partie qui n'est pas à publier 

Pour le moment tu envoi tout ce que tu as en validation d'un coup.

Pour contourner le problème pour le moment tu peux supprimer la partie qui n'est pas utile (v2), envoyer cette version là en validation et ensuite repartir de ta version initiale (v1) avec la partie que tu étais en train de rédiger. ainsi la v2 sera celle en validation avec uniquement le contenu que tu veux, et pendant ce temps tu continuera si tu veux la rédaction de la v1 -> v3 -> v4
