### ISSUE TITLE
Double post + déconnexion

### ISSUE THREAD

**Issue by amorison** [zestedesavoir/zds-site#1129]
On a un cas de double post dans la même minute créé sans action spéciale de l'utilisateur :
http://zestedesavoir.com/forums/sujet/527/outils-du-web/?page=1#p5621

J'ai demandé à Forever par MP ce qui s'était passé, il m'a répondu :

> Je ne l'ai pas fait par moi même [le second message], d'ailleurs, quand j'essaye d'accéder au sujet (avec ton lien ou autre), je reçois une erreur 500 + je me fais déconnecter.

OS et navigateur utilisé par Forever : Windows 8.1, Chrome 24/25 (c'est une vieille version ça, ça explique peut être une partie du problème ?)

**Comment by tleb** [comment]
Version exact: Windows 7 professionel + Chrome 24.0.1312.56 m
(Je suis Forever.)

**Comment by Eskimon** [comment]
Sans plus d'infos ca va etre chaud patate :D (mais je sais que ca va pas etre possible d'avoir plus d'infos malheureusement).

Les devs backs des idees ou chercher ? Ca pourrait etre un coup de malchance a cause du plantage malheureux de gunicorn pendant qu'on jouait avec la validation ?

**Comment by tleb** [comment]
Désolé, c'est vrai que c'est pas très précis, mais demandais, je peut essayer d'aider. ^^

Le plus gros problème, c'est que je peut même pas voir le sujet, quelqu'un peut supprimer mon message, voir si sa change quelque chose, même si je doute.

**Comment by cgabard** [comment]
NON, si ça te dérange pas trop, ce serait cool qu'on ne le supprime pas. Car ça veut dire que l'on est capable de générer une erreur sur ça et qu'en activant les log au moment où tu tenterais d'y accéder, on pourrait récupérer des infos sur pourquoi toi tu as une erreur 500. @firm1 : tu peux pas activer la bt vers un fichier de log et voir avec lui pour qu'il accede au sujet, que tu puisse récupérer la bt ?

**Comment by tleb** [comment]
Pas de problème.

**Comment by Eskimon** [comment]
Du nouveau a ce propos ?
Ca s'est deja reproduit ? C'etait ptet un coup de pas de bol a l'epoque des erreurs 500 recurrentes ?

**Comment by tleb** [comment]
Personne ne m'a contacté, dites moi qui je dois contacter, et je le fais. ^^
Je ne peux toujours pas me connecter au sujet, si c'était juste un coup de pas de bol, je veux bien voir avec un admin comment on peut faire pour résoudre mon cas, parce que j'aimerai bien lire les réponses. :+1:

**Comment by firm1** [comment]
> Le plus gros problème, c'est que je peut même pas voir le sujet

Quand tu dis que tu ne peux plus voir le sujet, qu'est ce que ça signifie exactement ?
- Dans la [liste des sujets](http://zestedesavoir.com/forums/savoirs/site-web/) est-ce que tu vois le sujet ?
- Si oui, en cliquant sur ledit sujet, est-ce que tu obtiens une page d'erreur ? Si oui quelle type de page d'erreur ? 404 ? 403 ?

Merci d'avance

**Comment by tleb** [comment]
- Je le vois dans la liste des sujets.
- Je clique dessus, erreur 500 + je suis déconnecté.
- Je peut regarder le profil du créateur sans problème.

**Comment by firm1** [comment]
Je viens de faire une PR qui devrait te redonner l'accès à ce sujet, il faudra attendre le passage de la QA et la prochaine MEP.

**Comment by tleb** [comment]
| Abbr | Signification |
| --- | --- |
| PR | Pull request |
| QA | Quality assess ? |
| MEP | ? |

Désolé. _(C'est aussi une occasion de tester un peu de markdown, m'entraîner...)_

**Comment by Eskimon** [comment]
| Abbr | Signification |
| --- | --- |
| PR | Pull Request |
| QA | Quality Assurance |
| MEP | Mise En Prod'(uction) |

**Comment by Eskimon** [comment]
Le merge est fait sur master, plus qu'à attendre que ca passe en prod' (je laisse @firm1 faire le reste du suivi :) )

**Comment by Eskimon** [comment]
Il y aura moyen d'avancer la dessus ?

**Comment by tleb** [comment]
Est-ce que ce soit possible que le problème ne vienne pas du double post en lui même, mais plus du fait que _Outils du web_ soit écrit deux fois dans _Notifications du Forum_ (clique sur _Toutes les notifications_).

**Comment by zopieux** [comment]
L'erreur 500 étant visiblement reproductible, que disent les [logs Django](https://docs.djangoproject.com/en/1.5/topics/logging/) quand TheoLeb se prend la 500 ? Si vous n'avez pas de logs, n'attendez pas une seconde et [activez-les](https://docs.djangoproject.com/en/1.5/topics/logging/) pour pouvoir debug.

**Comment by firm1** [comment]
Les logs sont activés, et il me semble que le bug est corrigé.

@TheoLeb  peux-t-il confirmer ?

**Comment by tleb** [comment]
En effet, le problème est réglé, il venait d'où ?

**Comment by firm1** [comment]
Le problème de la déconnexion venait d'[ici](https://github.com/zestedesavoir/zds-site/pull/1177/files).

Je ferme donc.
