### ISSUE TITLE
Conversion du zCode en Markdown à l'import des tutos

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#113]
Je ne sais pas si la fonctionnalité a déjà été implémentée (il me semblait que oui) mais quand j'importe un tuto, il ne convertit pas le zCode en Markdown.

Si ce n'est pas déjà fait, il faudrait appliquer la conversion pendant l'import.

**Comment by cgabard** [comment]
Il y a un convertisseur presque pret : https://github.com/Taluu/ZesteDeSavoir/issues/13 que nous préparre @Coy0te . Je crois qu'il n'est juste pas branché sur zds. Tu confirme @firm1  ?

**Comment by firm1** [comment]
Etant donné que Coyote bosse sur le convertisseur ztuto -> markdown, et qu'il le fait en Java, on a décidé de le faire de manière externe à zds.

Pour importer ton tuto maintenant, il faut que tu demandes à @Coy0te de le parser (ou que tu utilise [son parseur](https://github.com/Coy0te/parseTuto) pour le faire).

Le but étant qu'il parse tous les tutos d'abord et après on l'importe sur ZdS.

**Comment by GerardPaligot** [comment]
Ah ok, je me disais bien qu'il devait y avoir quelque chose. Je vois qu'il utilise une adresse absolue pour référencer les tutos. Du coup, je vais me contenter d'attendre que Coyote merge le tout. :)

Thanks de la réponse.

**Comment by firm1** [comment]
Normalement, quand tu télécharges son code, il suffit de remplacer sur [cette ligne](https://github.com/Coy0te/parseTuto/blob/master/src/zds/parseTuto/TestJSoup.java#L43) le repertoire local ou se trouve ton fichier (en ayant pris soin de donner une extension .xml à ton tuto).

Tu lances execute le TestJSoup.java et en 3 secondes, ton fichier est parsé.

Tu le renomme en .tuto pour pouvoir l'importé sur ZdS.

C'est ce que je fais actuellement.

**Comment by GerardPaligot** [comment]
Ok, j'aurais du lire ton message avant de tester. Je suis resté 5 minutes bloquées parce que j'avais laissé .tuto. :)

Le parser est performant. Comme tu dis, en 3 secondes il a parsé mon big tuto. Cela dit, c'est normal, il utilise Jsoup comme librairie.

Par contre, je ne ferme pas encore cette issue parce qu'il faudrait modifier ou supprimer la fonctionnalité d'import actuelle.

**Comment by firm1** [comment]
Je me vois mal intégrer ce parseur(ztuto -> mardown) dans les sources du site. Étant donné que ça sera utilisé une seule fois en one shoot pour fournir une source de fichier convenable. C'est donc plutôt un utilitaire.
Modifier la fonction d'import actuelle pour qu'elle utilise le parseur Java c'est surtout du travail pour pas grand chose au final.

**Comment by GerardPaligot** [comment]
Non, je voyais plutôt modifier la fonction d'import pour importer notre propre système d'import et pas celui de la v3 du Site du Zéro.

Actuellement, nous mettons à disposition des utilisateurs, en prod, une fonction d'import qui se base sur un algorithme qui ne sera jamais utile (sauf pour nous).

**Comment by Coy0te** [comment]
Faudrait créer une autre issue pour cette évolution, le titre de celle-là est trompeur.
