### ISSUE TITLE
[staff] Impossible d'éditer les tutos

### ISSUE THREAD

**Issue by coma94** [zestedesavoir/zds-site#1130]
En tant que staff on peut éditer les intro/conclusion des tutoriels hors-ligne d'un autre membre, mais pas le contenu du tuto.

C'est peut être volontaire, mais je pense que ça serait pratique de pouvoir corriger des erreurs de typo sans avoir à demander à l'auteur à chaque fois.

**Comment by coma94** [comment]
En attendant que ça soit corrigé il suffit de se mettre co-auteur (en prévenant l'auteur bien sur), de faire les corrections puis de se retirer.

**Comment by firm1** [comment]
It's done.
