### ISSUE TITLE
Ajouter un message de commit

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1133]
Ca serait sympa si, quand on fait une modification de tuto/articles, on puisse ajouter un message de commit pour préciser ce que l'on a fait. (encore plus utile quand on est multi-auteur). Je ne crois pas avoir vu la fonctionnalité sur le site ni trouve de ticket a ce sujet...

**Comment by firm1** [comment]
Mergé -> je ferme

**Comment by firm1** [comment]
Mergé -> je ferme
