### ISSUE TITLE
Mettre en avant les tags

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1134]
Afin de pouvoir mettre en avant l'utilisation des tags sur le forum, lors de la création d'un topic, je pense qu'il faudrait mettre un placeholder dans l'input de saisie.

En regardant vite fait le code, il suffit de modifier [cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/forms.py#L22) et remplacer le texte : 
`'required': 'required',` par 

``` python
'required': 'required', 
'placeholder': '[Tag 1][Tag 2] Titre de mon sujet',
```

**Comment by Eskimon** [comment]
Gros pluzin !

**Comment by artragis** [comment]
je rejoins @Eskimon +1

**Comment by SpaceFox** [comment]
+1

2014-07-10 15:57 GMT+02:00 artragis notifications@github.com:

**Comment by Eskimon** [comment]
Je prends comme placeholder pour post freeze (je garde au chaud comme "issue d'entrainement" pour des jeunes recrues)
