### ISSUE TITLE
Envoi de MP validation

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1135]
Lorsque la validation refuse (et accepte) un tuto (article ?) un MP de justification est envoye a chaque auteur. Un MP globale avec tout les auteurs seraient mieux !

**Comment by coma94** [comment]
Je veux bien essayer de régler ça :)

**Comment by Eskimon** [comment]
^^ fais toi plaisir mais n'oublie pas qu'on est en Freeze, donc ca sera pas intégrer avant un moment

**Comment by coma94** [comment]
C'est l'occasion de me familiariser avec le code :) .
Du coup je propose quand même une PR ?

**Comment by Eskimon** [comment]
(Je me suis mis en assignee comme "placeholder" ;) )

Fais le dev sur une branche chez toi, puis quand le freeze est levé tu mets à jour ta branche et lance la PR a ce moment-là, je pense que ce sera le mieux pour pas risquer de violer le freeze par mégarde

**Comment by coma94** [comment]
Ça marche !

**Comment by Eskimon** [comment]
@coma94 tu auras le temps de t'en occuper ou tu préfères que qqun prenne le relais ?

**Comment by Eskimon** [comment]
Ca se passe par ici pour les tutos:
- refus : https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L302
- validation : https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L378

Pour les articles
- refus: https://github.com/zestedesavoir/zds-site/blob/dev/zds/article/views.py#L516
- valide: https://github.com/zestedesavoir/zds-site/blob/dev/zds/article/views.py#L614

**Comment by coma94** [comment]
J'ai déjà ça codé dans un coin !
Je PR dans quelques jours le temps de mettre à jour mon code avec la versoin actuelle de zds.

**Comment by Eskimon** [comment]
Tout roule :) merci @coma94 et @firm1 :)
