### ISSUE TITLE
Gravatar: passer l'email en minuscule

### ISSUE THREAD

**Issue by Glaived** [zestedesavoir/zds-site#1136]
Bonjour,
Sur le système pour appliquer les gravatar, l'email est pris tel quel, donc si on retrouve une majuscule dans l'adresse email, cela donnera un hash différent pour le gravatar

**Comment by firm1** [comment]
En vérifiant dans le code de zds rapidement, il suffit d'aller sur [cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/models.py#L121), et changer ceci : 
`md5(self.user.email).hexdigest())`
en 
`md5(self.user.email.lower()).hexdigest())`

Et zouh la Pull Request

**Comment by Glaived** [comment]
N'étant pas dev python je laisse la communauté faire le pull request ^^

**Comment by 0hexit** [comment]
Je fais la PR, merci.

**Comment by cgabard** [comment]
Hahaha 3 PR ! Tu as eu un peu de mal on dirait :p

**Comment by 0hexit** [comment]
Ah oui ^^ La première fois, j'ai mergé sur dev et la deuxième, j'ai voulu merger sur master alors que j'avais les fichiers de la branche dev (ça m'a ajouté plein de commits non voulus)...
