### ISSUE TITLE
[Editeur] [Smileys] Différents packs et intégration

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#1143]
Hello le monde !

J'ouvre ce nouveau ticket pour discuter un p'tit truc !

J'viens vous parler d'une petite feature. Je sais, on est en mode freeze jusqu'à la sortie publique, mais bon, on peut quand même parler ! :-)

Vous le savez peut-être, ou pas, mais [Piwit](http://zestedesavoir.com/membres/voir/Piwit/), s'est lancé dans la [création de smileys à l'effigie de Clem la mascotte](http://zestedesavoir.com/forums/sujet/538/clem-sur-le-devant-de-la-scene/) !

Seulement vient la question de l'intégration. Déjà vous, voulez-vous les intégrer à l'éditeur ?

Car après j'ai aussi pensé, qu'on pourrait laisser les membres créer leur propre pack de smiley, qu'ils soumettraient à une validation et qui les intégrerais à l'éditeur.

Mais après, comment voyez-vous cela ? [Sur le forum](http://zestedesavoir.com/forums/sujet/538/clem-sur-le-devant-de-la-scene/?page=2#p6214) j'ai proposé un système permettant à l'utilisateur dans ses paramètres de cocher les packs qu'il désire voir et utiliser.

Viki quant à lui, [à proposer](http://zestedesavoir.com/forums/sujet/538/clem-sur-le-devant-de-la-scene/?page=2#p6224) un style d'onglet, différent pour chaque packs, mais apparemment ça serait plus complexe à mettre en place.

**Comment by cgabard** [comment]
Perso je n'ai rien contre proposé plusieurs pack. Mais je serais plus pour proposer à chaque utilisateur quels smiley il préfère car un utilisateur ne verra qu'une seule sorte de smiley et restera cohérent partout Vs Choix du simey par l'auteur d'un message et donc potentiellement différent à chaque message. Et je ne parle même pas du fait qu'on pourrait alors les mixer dans un même message. Enfin ça obligerais d'intégrer dans le parseur un symbole par smiley par pack, ce qui va en faire vite beaucoup. 

Donc pour moi : Un seul jeu de smiley actif a la fois, choisi par l'utilisateur.

**Comment by Alex-D** [comment]
+1 à l'idée de @cgabard, sinon ça va être le foutoir ^^

**Comment by Axylium** [comment]
Effectivement, l'idée de @cgabard, me paraît être la meilleure !

**Comment by s-afchar** [comment]
(Je suis Piwit)
Mais alors je supprime les smileys spéciaux ?! (ceux qui n'ont pas d'équivalent "smiley SdZ")
Par exemple[ le pop-corn demandé par Eskimon](http://zestedesavoir.com/forums/sujet/538/clem-sur-le-devant-de-la-scene/?page=9#p16817).

**Comment by Alex-D** [comment]
Tu peux le garder, mais faudra rentrer l'URL avec `![]()` pour le mettre, et non un smiley type " :) "

**Comment by s-afchar** [comment]
Ce ne seront donc pas des smileys mais des images.

J'ai publié [ce message](http://zestedesavoir.com/forums/sujet/538/clem-sur-le-devant-de-la-scene/?page=9#p16886) sur le fofo avant d'avoir vu ta réponse, tu peux y répondre pour que tout le monde voit ta réponse.

**Comment by Eskimon** [comment]
A mon avis pour tout les cas de "smileys spéciaux/étendus", il faudra voir sur une ZEP en particulier et figer le comportement à avoir, histoire que tout le monde aient la meme reference. Si un jour un nouveau smiley arrive il suffira de laisser l'écriture "litteral" (genre :ninja: ) si le smiley n'existe pas dans le pack

**Comment by Alex-D** [comment]
Je pense en effet qu'il va falloir voir à étendre les smileys pour offrir plus de possibilités aux contributeurs externes, so +1 pour les choses type :ninja: ou :popcorn:

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis plus d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.

**Comment by Eskimon** [comment]
C'est aussi inclus dans la [ZEP-14](https://zestedesavoir.com/forums/sujet/1009/zep-14-refonte-de-lassistant-dedition-markdown/) :)

**Comment by s-afchar** [comment]
Au dernières nouvelles pour la partie "smileys clem" on avait ça : https://zestedesavoir.com/forums/sujet/538/clem-sur-le-devant-de-la-scene/?page=13#p48802 avec une bonne idée de MaxRoyo. 

De mon côté je n'ai vraiment pas eu le temps de finir les Clemojis (adapter l'idée de Max et créer les smileys manquants) car j'ai eu beaucoup...beaucoup...beaucoup de problèmes d'ordi depuis Juin et pas assez de temps avant et maintenant.

Peut-être que la meilleure solution serait que j'ouvre un nouveau topic afin que quelqu'un les termine à ma place ou qu'on puisse en rediscuter afin d'apporter de nouvelles idées etc... :smile: 

---

Pour info, tous les fichiers sont là : https://github.com/SimpleSoftwares/Clemojis/tree/master/V2.1
