### ISSUE TITLE
Les flèches du menu sont mal dessinées 

### ISSUE THREAD

**Issue by thauti** [zestedesavoir/zds-site#1144]
Je ne sais pas si elles sont générées  en CSS ou si c'est des images, mais les flèches à gauche de "Tutoriels" et "Forum" ont quelques pixels qui débordent surtout sur le côté gauche.
PS: J'imagine bien que c'est pas du tout urgent, mais une fois qu'on l'a vu on ne voit plus que ça :(

**Comment by sandhose** [comment]
Je suis pas sur de comprendre ce que tu veux dire :(

Ces flèches sont créées via un `border`. Peux-tu préciser la version de ton navigateur, ton OS, et envoyer une petite screenshot ?

**Comment by thauti** [comment]
Désolé de répondre aussi tardivement
Ça me le fait sur tout les OS et tout les navigateurs, et je suis en 1080p
![capture d cran - 20072014 - 15 59 25](https://cloud.githubusercontent.com/assets/4258438/3637631/430879de-1016-11e4-96a3-52e99d04506e.png)

**Comment by Alex-D** [comment]
Je ne peux rien faire pour toi, chez tout le monde ça fonctionne bien.

Cette issue est à fermée car non-bloquante et non-résoluble.

**Comment by amorison** [comment]
Hmmm, ça me fait la même chose sur Firefox 30, archlinux à jour et sur Windows également. 1366*768. M'enfin, ce n'est pas très important effectivement. Tu sais d'où ça peut venir ? (par curiosité)

**Comment by Axylium** [comment]
Ça le fait également chez moi, sur Firefox 27.0, Ubuntu 13.04, avec une résolution qui est la même que @aMorison, soit de 1366*768. 

(C'était juste pour prévenir que ça ne le fait pas que chez lui, mais comme dit, ce n'est absolument pas bloquant).

**Comment by Alex-D** [comment]
> Tu sais d'où ça peut venir ?

Ca vient de Gecko qui est un moteur de rendu vieillissant. Et du fait que j'utilise un trick CSS pas propre. Ca sera corrigé en même temps que les menus au survol avec séparation lien / flèche, etc.

**Comment by Eskimon** [comment]
Merci @gustavi !
