### ISSUE TITLE
Les flux des articles sont quasiment vides

### ISSUE THREAD

**Issue by 0hexit** [zestedesavoir/zds-site#1146]
Si on regarde les deux flux [RSS](http://zestedesavoir.com/articles/flux/rss/) et [Atom](http://zestedesavoir.com/articles/flux/atom/) des articles, on peut voir qu'il manque pas mal d'informations.

_Signalé dans la PR #1118_

**Comment by 0hexit** [comment]
Je prends la PR.

**Comment by Eskimon** [comment]
Te la voila assignée !

**Comment by devock** [comment]
C'est corrigé et mergé. Je clos.
