### ISSUE TITLE
Commentaire au validateur

### ISSUE THREAD

**Issue by coma94** [zestedesavoir/zds-site#1148]
Lorsque l'on envoie un tuto/article en validation, on peut laisser un message au validateur (très pratique pour indiquer nos modifications).

En tant que validateur, où peut-on retrouver ce message? Dans l'historique de validation (qui est actuellement en erreur 500) ou ailleurs ?

**Comment by Eskimon** [comment]
Tu arrives 36h trop tard, cette info a été ajoute dans la PR https://github.com/zestedesavoir/zds-site/pull/1111 :)

Elle est ainsi visible en haut du tuto/article si l'auteur a laisse un message ;)

Je ferme donc !

**Comment by coma94** [comment]
Ok merci ^^
