### ISSUE TITLE
Quelques remarques sur les tags

### ISSUE THREAD

**Issue by amorison** [zestedesavoir/zds-site#1149]
Hello !

D'abord, la remarque sans intérêt : le tag LaTeX actuel n'a pas de T majuscule (LateX au lieu de LaTeX).

Ensuite, comment se passe l'ajout de tags ? J'ai des idées de tutos scientifiques, mais il existe seulement le tag "Mathématiques". Il faudrait _a minima_ un tag "Sciences naturelles" (ou whatever de parlant) qui regroupe physique, chimie, biologie, géosciences ; au mieux un tag pour chacune de ces catégories.

**Comment by cgabard** [comment]
Les tags sont créés au besoin par les valido. Il suffit que tu le précise à la validation et il sera ajouté.

**Comment by Eskimon** [comment]
Mais ce ticket fais bien d'etre la, il faut trouver un moyen elegant de le preciser quelques part...

**Comment by amorison** [comment]
@cgabard : OK, merci !

Pour préciser ça, une simple phrase au niveau du choix du tag du style "Si vous avez besoin d'un tag inexistant, contacter un validateur" avec lien qui pointe vers une liste de valido (si on a ça), ça pourrait le faire, non ?

**Comment by cgabard** [comment]
Même pas, tu dois avoir un champ pour laisser un commentaire au validateur, non ? Tu peux le mettre là. Sinon faudrait le rajouter. Cela doit être dans ce formulaire qu'il faut faire la demande, pas renvoyer à un MP

**Comment by amorison** [comment]
Effectivement, je n'y avais pas pensé. Donc plutôt un message du genre "Si vous avez besoin d'un tag inexistant, précisez-le lors de l'envoi du tuto en validation".

**Comment by Eskimon** [comment]
Oui mais ca l'auteur le sait pas avant d'envoyer en validation, et donc pourrait etre inquieter et se dire "Merde mon tuto a pas sa place ici !"

grille par @aMorison

**Comment by Eskimon** [comment]
Je prends comme placeholder pour post freeze (je garde au chaud comme "issue d'entrainement" pour des jeunes recrues)

**Comment by Eskimon** [comment]
J'avais completement oublie ce truc, j'essaie de rajouter le bout de texte ASAP !

**Comment by Alex-D** [comment]
Le petit texte est rajouté, LaTeX est bien écrit, c'est donc tout bon ! Je ferme :)
