### ISSUE TITLE
Accès à l'historique d'un tutoriel

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#115]
Comment se fait-il que je puisse accéder à l'historique d'un tutoriel dont je ne suis pas l'auteur ? Par exemple, pour [ce tutoriel](http://zestedesavoir.com/tutoriels/historique/16/fonctionnement-des-ordinateurs-de-zero/), je peux accéder à son historique.

Si nous regardons le code de [cette méthode](https://github.com/Taluu/ZesteDeSavoir/blob/master/zds/tutorial/views.py#L174), elle est bien annotée pour que nous (staff) puissions y accéder mais le [test](https://github.com/Taluu/ZesteDeSavoir/blob/master/zds/tutorial/views.py#L178) me semble un peu bizarre.

Cela ne devrait-il pas être :

``` python
if not tutorial.on_line \
   or request.user not in tutorial.authors.all():
    raise Http404
```

Puis, nous pouvons visualiser l'historique d'un tutoriel que s'il est publié ? Ca me semble utile aussi s'il est à l'état de brouillon.

**Comment by GerardPaligot** [comment]
Même chose pour [cette méthode](https://github.com/Taluu/ZesteDeSavoir/blob/master/zds/tutorial/views.py#L234) un peu plus loin.

**Comment by firm1** [comment]
A vu de nez c'est un peu le bordel quand même au niveau des permissions je crois.

Faut s'y pencher.

**Comment by GerardPaligot** [comment]
Nous sommes d'accord. Ca m'amène à ma question suivante : Comment gérer efficacement les permissions ? Il me semble que nous avons deux informations pour gérer les permissions :
- Les groupes : Comment pouvons-nous tester l'appartenance d'un membre dans un groupe pour savoir s'il est dans le groupe "staff" ou non ?
- Les permissions comme `tutorial.change_tutorial` mais je n'ai aucune idée où est-ce que tu attaches ces permissions à un utilisateur. Quand je fais une recherche, je ne trouve que des utilisations de cette permission. Comment sont-elles gérer ?

Si tu m'envoies vers la documentation, ça m'ira aussi.

**Comment by firm1** [comment]
Pour information la gestion des permissions par les groupes est une pratique pas très propre. Car au moindre changement du nom du groupe, il faut se retaper le bousin.

Les permissions de type `<class>.change_<class>` sont des permissions automatiquement créer lors de la création d'une classe dans le modèle de la base. Je t'invite à lire la [doc à ce sujet](https://docs.djangoproject.com/fr/1.5/ref/models/options/#table-names).

En attendant, j'ai corrigé la gestion des droits sur les tutos en général.

**Comment by GerardPaligot** [comment]
Hell, il existe une documentation Django en français ...

Merci pour la documentation, je lirais ça.

**Comment by firm1** [comment]
> Hell, il existe une documentation Django en français ...

Oui, mais il faut savoir que toute la doc n'a pas encore été traduite en Français. En général via google tu tombera toujours sur les liens anglophones. Ce que tu fais, c'est de remplacer dans l'url "en" par "fr" pour savoir si cette partie a été traduite.

Bonne lecture.
