### ISSUE TITLE
Version non visible sur page 403

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1151]
La version du site n'est pas visible sur la page d'erreur 403.

(et 404 ? et 500 ?)

Je reserve pour Amarok qui l'as trouvé et veux essayer de résoudre

**Comment by AmarOk1412** [comment]
I am here.
Je forkerais, clonerais et travaillerais sur ma branche demain je pense. Je préviendrais si je n'ai pas le temps de le faire :)

**Comment by Eskimon** [comment]
Pas d'urgence pas d'inquiétude !!!

**Comment by ArnaudCalmettes** [comment]
> Je reserve pour Amarok qui l'as trouvé et veux essayer de résoudre

J'ai ajouté AmarOk1412 au groupe "assignés" et lui ai transmis le ticket.

Bienvenue à toi !

**Comment by AmarOk1412** [comment]
Juste dire que c'est pareil avec la 404.
Merci nohar :)

**Comment by AmarOk1412** [comment]
ZdS fonctionne bien chez moi.
J'ai localisé le bug, par contre je découvre Django donc je vois pas trop la cause.
En gros, que ce soit 403/404/500.html, les 3 n'éxécutent pas les fonctions de **init.py** donc git_version.url et git_version.name. 
Vous pouvez aussi essayer de copier le contenu de home.html dans 404.html vous verrez que les fonctions ne marchent pas non plus.

**Comment by SpaceFox** [comment]
AMHA les pages "d'erreur" 403/404/500 doivent être **purement statiques**, et donc ne faire aucun appel d'aucune sorte au serveur Python (Gunicorn).

Pourquoi ? Parce qu'elles peuvent être appelées si le serveur python est mort. C'est typiquement le cas d'utilisation de la page d'erreur 500.

Donc si elle nécessite de faire un appel à un serveur HS... on va avoir un problème !

**Comment by SpaceFox** [comment]
PS : comme vous l'avez compris... ça implique de faire une croix sur le numéro de version sur ces pages.

**Comment by AmarOk1412** [comment]
Ok, c'est bien ce que je pensais. Impossibilité d'aller toucher les fonctions...
Du coup, j'enleverais Version: pour ces pages. Merci de la précision SpaceFox

**Comment by sandhose** [comment]
@SpaceFox: Pour moi, seul les erreurs 5xx doivent être statiques, car ce sont celles qui concernent une erreur serveur. Les erreurs 4xx sont relatives au contenu, aux autorisations, et peuvent, voir doivent être dynamiques.

—

**Comment by firm1** [comment]
Je confirme les propos de @sandhose . Les seules les erreurs de type 5xx sont statiques. Les 4xx doivent être dynamiques, et on doit pouvoir retrouver la version en dessous.

Pour résoudre ce problème, étant donné que les fichiers init.py ne sont pas appelés, il faudrait créer un filtre/tag dans le répertoire templatetag, qui lui cherchera la bonne version de git (en appelant la fonction du fichier **init**.py).

Par contre il faut faire attention à ce que le tag/filtre ne soit appelé que pour des pages d'erreurs (il ralentirait les perfs s'il était appelé dans toutes les pages). Pour cela, il faudra aller dans le fichier `template/base.html` et transformer la partie qui sert a l'affichage de version en block `{% block version %} {% endblock %}` et la surcharger dans les pages 404 et 403

**Comment by AmarOk1412** [comment]
Juste pour dire que ce bug a un peu disparu de ma tête et que je m'occupe surtout de l'extension firefox en ce moment, donc si quelqu'un veut bien prendre le bug.

**Comment by Alex-D** [comment]
Je mets à jour cette issue en retirant @AmarOk1412 qui a l'air d'être sur autre chose et en mettant le bon tag : c'est un soucis de back et non de front.

**Comment by Nodraak** [comment]
Sur une erreur 500, en plus du tag de version git, le fait qu'on soit log-é disparait (l'icone et les menus en haut a droite)

**Comment by Alex-D** [comment]
Sur une 500, c'est normal, erreur interne ça bloque pas mal de choses et la session doit en faire partie.

**Comment by AmarOk1412** [comment]
Oups oui, j'avais zappé cette issue et je suis un peu pris.

**Comment by gustavi** [comment]
Ça sera corrigé avec https://github.com/zestedesavoir/zds-site/issues/1712.

Dans le cas où #1712 ne passe pas, il faudra surcharger les fonctions qui se trouvent [ici](https://github.com/django/django/blob/master/django/views/defaults.py) pour leur ajouter les variables qui manquent (et c'est vraiment pas propre).

**Comment by Eskimon** [comment]
le fix de gustavi corrige ca :) (mais on va attendre le merge)

**Comment by Eskimon** [comment]
MErci @gustavi

**Comment by gustavi** [comment]
\o/
