### ISSUE TITLE
Boutons et éditeur en lecture seule

### ISSUE THREAD

**Issue by Maxou44** [zestedesavoir/zds-site#1153]
Suite à un post, la réponse est bloqué, on ne peut pas répondre avant un certain temps pour limiter le double post, néanmoins les boutons de mise en formes, eux, fonctionnent toujours, il est possible de cliquer dessus et ça modifie texte d'information.

Une simple condition en JS pour vérifier si l’éditeur est en readonly devrai résoudre le problème ;)

**Comment by Alex-D** [comment]
J'ai opté pour une autre solution qui résout le problème plus proprement selon moi.

Si on ne peut pas poster de nouveau message, alors on a pas de formulaire. Et alors on a le message d'avertissement formaté d'une façon plus jolie et plus lisible.

Voyez la PR #1664 pour avoir une idée du rendu.

**Comment by Alex-D** [comment]
Corrigé. Mergé.
