### ISSUE TITLE
Impossible de supprimer une partie

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#1154]
Il est actuellement impossible de supprimer une partie d'un bigtuto.
En effet, bien qu'une url soit disponible dans le fichier views.py, nous avons : 
- une absence d'accès côté front (pas de croix "supprimer")
- une méthode de suppression qui est incomplète (a minima, pas de répercussion de la modif dans la bdd)
- aucun test unitaire pour vérifier que ça fonctionne.
# Ce qu'il faut absolument implémenter pour corriger cette issue :
- le bouton "supprimer"
- la suppression d'une partie dans un bigtuto doit être répercutée : 
  - sur le système de fichier/dépôt git
  - sur le sommaire (disparition)
  - sur le sommaire (numérotation)
  - dans la base de données
  - dans la navigation précédent/suivant
- De même tous les chapitres d'une partie supprimée doivent
  - disparaître du dépôt git
  - disparaître du manifeste
  - disparaître de la base de données
  - ne plus apparaître dans la navigation précédent/suivant
# Ce qui est testable unitairement côté back (python) :
- suppression du système de fichier/dépôt (os.path.isfile()) 
- suppression dans le manifest.json (fonction dump_json de l'objet Tutorial)
- suppression dans la base de données (Parts.objects.count())

**Comment by pierre-24** [comment]
@SpaceFox : du coup, cette issue est normalement réglée.

**Comment by Eskimon** [comment]
Je ferme des qu'on a bien fignoler les derniers tests en preprod !

**Comment by firm1** [comment]
C'est en prod, je ferme donc :-p
