### ISSUE TITLE
Conserver la lecture zen de page en page

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1156]
Le principe serait d'automatiquement réactivé, côté client, la lecture zen lors de la navigation au sein d'un tutoriel.

La solution technique à adopter est l'usage de `sessionStorage` car scopé à l'onglet courant. Ainsi, on est certain que l'utilisateur peut continuer à naviguer normalement sur ses autres onglets, et dans l'onglet concerné, l'utilisateur sera obligé de quitter le zen mode pour revenir à une navigation classique.

Ca implique donc de modifier une variable dans `sessionStorage` (`zenMode` à tout hasard) qui vaudrait `true` ou `false` selon que c'est activé ou non.

Cette petite feature sera à ajouter dans le fichier `zen-mode.js` (ou un truc du genre, s'il est renommé d'ici là).

**Comment by AlexRNL** [comment]
Doublon de #1150 !

**Comment by Alex-D** [comment]
Haaa mais il n'a pas prévenu... Pour le coup mon issue est plus détaillée ça serait mieux de garder la mienne je pense.

**Comment by gustavi** [comment]
Corrigé ! Merci @Situphen !
