### ISSUE TITLE
Mauvaise police sur les liens (tutos / articles / pages statiques)

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1159]
Suite à un commit quelque part entre la v1.0-RC3 et la v1.0-RC4, la police des liens dans les pages tutos, articles et statiques est mauvaise : il manque l'appel à "Merryweather" et on se retrouve avec du "Liberation Serif", qui n'a pas _vraiment_ la même tronche.

Si j'en crois Firebug (mais sur un fichier minifié), le problème serait sur une directive :

```
.main .content-container .article-content a, .main .content-container .article-content ol, .main .content-container .article-content p, .main .content-container .article-content ul:not(.pagination) {
```

**Comment by 0hexit** [comment]
J'ai l'impression que le bug n'est plus d'actualité non ? Sur [cette page statique](http://zestedesavoir.com/pages/) par exemple, c'est bien la police Merriweather qui est utilisée.

Edit : en fait, c'est ok sous Chrome mais ça n'est pas bon sous Firefox. Je n'ai rien dit.

**Comment by SpaceFox** [comment]
Pas chez moi, cache vidé et tout.

**Comment by 0hexit** [comment]
J'ai compris d'où ça vient. Je fais la PR :)

**Comment by SpaceFox** [comment]
Je confirme le bug : Windows tous navigateurs, Linux tous navigateurs,
problème vérifié différents outils d'analyse du CSS.

Par contre comme c'est une régression, il reste invisible tant que
l'ancienne version des statiques est dans le cache navigateur.

**Comment by 0hexit** [comment]
En effet, j'avais oublié de vider le cache avant de tester (honte à moi)...

**Comment by devock** [comment]
C'est corrigé et mergé, je clos.
