### ISSUE TITLE
[Téléchargement PDF] Erreur sur un tuto

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#116]
Pourquoi l'export PDF sur ce tuto ne marche pas ?
=> http://zestedesavoir.com/tutoriels/15/les-maths-pour-tous/

Je l'ai dépublié/revalidé en pensant que ça venait du fait que le tuto avait été validé avant la mise en place de l'export, mais apparemment ça n'a pas résolu le problème. Pourquoi ?

**Comment by firm1** [comment]
Le problème vient du fait que l'export des tutos en pdf n'est pas encore totalement fonctionnel. Il y'a une conversion markdown zds vers markdown pandoc qui doit être faite avant la génération des pdf.

Pour info l'erreur qui a empêché ton export est la suivante : `! Package amsmath Error: \begin{align*} allowed only in paragraph mode`

**Comment by firm1** [comment]
Les problèmes pures de conversion en pdf ont été réglés normalement grâce à la prise en compte du moteur xetex pour une prise en compte plus étendu de l'utf8.

Je ferme donc cette issue.
