### ISSUE TITLE
Edition des messages dans un sujet vérouillé

### ISSUE THREAD

**Issue by geoffroyw** [zestedesavoir/zds-site#1160]
Comme décrit sur [forum](http://zestedesavoir.com/forums/sujet/588/edition-des-messages-possibles-dans-les-sujets-verrouilles/?page=1#p7144), le front empêche l'édition d'un message dans un topic locké (attribut `disabled="True"`), mais le back s'en moque et autorise l'édition d'un tel message. Du coup, faudrait aligner les comportements front et back.

**Comment by Eskimon** [comment]
Merged, je ferme
