### ISSUE TITLE
Le mp envoyé lors de la publication d'un article n'est pas formaté

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#1163]
Quand un article est publié, le message envoyé à l'utilisateur n'est pas formaté.

**Comportement attendu**
Un mp avec le contenu suivant : "Félicitations [nom de l'auteur] ! Ton zeste [Titre de l'article] est maintenant publié ! Les lecteurs du monde entier peuvent venir le lire et réagir a son sujet. Je te conseille de rester a leur écoute afin d'apporter des corrections/compléments. Un Article vivant et a jour est bien plus lu qu'un sujet abandonné !". Le titre de l'article doit être un lien hypertext vers l'article.

**Comportement réel** 
Le mp a le contenu suivant : "Félicitations {0} ! Ton zeste {1}"

**Comment reproduire le bogue** 
1. Créer un article 
2. Faire une demande de validation
3. Publier l'article
4. Consulter les messages de l'auteur

**Comment by DevHugo** [comment]
Je prends. 

Dans la branche, trois commit:
- Un commit pour corriger le problème concernant le formatage: https://github.com/DevHugo/zds-site/commit/ab473ea6ba94d9d72c38780ee5b899ccaaff4f61.
- Un commit pour corriger le lien dans le mp: https://github.com/DevHugo/zds-site/commit/0f395ee6bc7bd003f3ede216c186baba7c48bbe3.
- Un commit pour la remise en forme aux normes pep8 : https://github.com/DevHugo/zds-site/commit/0f5327ea581ced6e047cee81b7608a13e90c2f70

Puis-je faire une pull request ? Sur la branche master ou sur la branche dev ? (Ce n'est pas prioritaire même si cela reste un bogue).

**Comment by 0hexit** [comment]
Bien sûr, toute PR est la bienvenue ! Elle doit être faite sur la branche master ;)

PS : Je me suis permis de commenter un des commits pour signaler des petites fautes d'orthographe.

**Comment by DevHugo** [comment]
Effectivement. Pour la majuscule, à article, je pense que c'est fait exprès. 

Faudrait voir si on met le contenu du mp dans un template, cela me parais plus propre
La question est aussi, une deuxième PR pour les corrections orthographique ou on fait ça dans la même ?

Pour les tutoriels, le mp contient aussi des fautes d'orthographe : 

> Félicitations  ! Ton zeste … a été publié par … ! Les lecteurs du monde entier peuvent venir  
> l'éplucher et réagir a son sujet. Je te conseille de rester a leur écoute afin d'apporter des 
> corrections/compléments. Un Tutoriel vivant et a jour est bien plus lu qu'un sujet abandonné !

Correction: a en à

**Comment by 0hexit** [comment]
Non vraiment, il faut enlever la majuscule :) Elle relève surtout d'une mauvaise habitude d'écriture.

Vu qu'on est en période freeze (donc uniquement des corrections de bugs), je ne pense pas qu'il faille instaurer de template(s). Mais plus tard, je suis d'accord, il faudra tout mettre dans un template.

Sinon, puisqu'il y a aussi des fautes dans le MP pour les tutoriels, je pense qu'il est mieux de séparer en 2 PR : une pour corriger tout ce qui concerne le MP des articles (formatage et fautes) et une pour corriger tout ce qui concerne le MP des tutos (ou alors en 2 PR comme tu l'as décrit).

**Comment by SpaceFox** [comment]
Mergé --> Fermé
