### ISSUE TITLE
[Forum]Non unicité des ancres des notes de bas de page

### ISSUE THREAD

**Issue by geoffroyw** [zestedesavoir/zds-site#1164]
Comme signalé sur le [forum](http://zestedesavoir.com/forums/sujet/639/les-notes-de-bas-de-pages/?page=1#p7220), les ancres des notes de bas de page ne sont pas unique au sein d'une même page (HTML).

Par exemple, si deux posts affichés sur la même page ont une note de bas de page, on va se retrouver avec deux ancres  `#fn-1` et `#fnref-1` dans l'HTML. Du coup, on se retrouve toujours redirigé vers la première instance de cet ancre.

**Comment by firm1** [comment]
En fait il s'agit d'une issue en lien avec une autre coté markdown [ici](https://github.com/zestedesavoir/Python-ZMarkdown/issues/31).

**Comment by Taluu** [comment]
Oui c'est un problème connu (je l'avais reporté lors des beta privés, et on a ouvert le ticket mentionné par @firm1 : zestedesavoir/Python-ZMarkdown#31). C'est aussi vrai pour les mini-tutos ou chapitres de big-tutos.

J'ai changé le tag front par un tag markdown, vu que c'est plus une histoire de communication back / markdown.

**Comment by Nodraak** [comment]
Le même bug avait été reporté pour pdp, un [_hack_ comme ça](https://bitbucket.org/MicroJoe/progdupeupl/pull-request/66/fixed-issue-105/diff) est il viable (après l'appel à l'interpréteur markdown donc), ou vous souhaitez un _fix_ plus propre (modifier le code de l'interpréteur lui même donc) ?

Ps : Évidement modifier le code de Python-ZMarkdown serait plus propre, mais pour ca il faut quelqu'un qui connaisse le code pour savoir comment transmettre l'id unique jusqu'a la fonction qui s'occupe des _footnotes_.

Edit : cf PR #1399

**Comment by Alex-D** [comment]
A mon sens, les bugs Markdown vont sur le repo Markdown, donc cette issue n'a pas lieu d'être, donc je la ferme.
