### ISSUE TITLE
Designer le chapitrage des tutoriels

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1170]
Actuellement, le design n'est pas "fini", il n'est que le résultat de gros oeuvre. Il faudrait que les finitions soient faites au niveau du chapitrage des tutoriels, autant sur la page d'accueil d'un tuto que sur chaque partie.

Il faut également revoir la sémantique des listes pour passer en listes ordonnées. Il y a certainement d'autres détails du genre à ajuster.

**Comment by Deuchnord** [comment]
Je suis d'accord, le sommaire ne fait pas complètement « fini », c'est dommage.

Je propose un design comme celui-ci : 

![suggest-amelioration-sommairetutos](https://cloud.githubusercontent.com/assets/7600265/3595400/39c7805a-0cb4-11e4-8238-41ef89eddb1d.jpg)

La police utilisée est celle proposée dans le body du CSS du site. J'ai également retiré le soulignement, mais ce dernier peut se réafficher en passant la souris sur les liens (je l'ai retiré parce que je trouvais que ça surchargeait un peu). J'ai également mis un <h2> avec le mot « Sommaire » et dont j'ai changé la couleur pour celle du reste de la page (inherit), et j'ai entouré le tout d'une div avec un padding de 30px et un fond de la même couleur que celle du sidebar à gauche (#F0F0F0).

Voilà, qu'en pensez-vous ? ^^

**Comment by Alex-D** [comment]
J'en pense que ça ne colle pas au reste fait comme ça :/

Mais ne t'inquiètes pas, le soucis ça n'est pas tellement les idées, mais le fait qu'on soit en gel, on ne fait que des corrections de bugs, donc je n'ai pas le "droit" de m'attarder là dessus.

**Comment by Deuchnord** [comment]
No problem, ce n'étais qu'une suggestion :3
Bon courage pour votre chasse aux derniers bugs !

**Comment by Alex-D** [comment]
Mergé il y a un mois.
