### ISSUE TITLE
Afficher les derniers messages lorsqu'une réponse a été postée entre temps (MP, Articles, Tutos)

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1172]
Quand on rédige une réponse à un MP/Articles/Tutos, et qu'un autre a répondu entre temps, on a une page séparée et on a uniquement le formulaire. Il faudrait afficher les derniers messages, comme sur le forum et ainsi aligner les comportements.

Autant pour le front, je vois comment faire, autant : est-ce que le back renvoi ça actuellement ? Si non, il faudrait déjà implémenter ça.

**Comment by Eskimon** [comment]
Ca fait deux fois :D Les grands esprits !!

https://github.com/zestedesavoir/zds-site/issues/1152

Je ferme la mienne, la tienne étant plus détaillé ;)

**Comment by Eskimon** [comment]
Je modifie ton titre pour étendre cette correction aux articles/tutoriels pour obtenir le même comportement ;)

**Comment by Eskimon** [comment]
C'est réglé !
