### ISSUE TITLE
Informer d'ajout d'un nouvel auteur

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1173]
Lorsqu'un nouvel auteur est ajouté à la rédaction d'un tutoriel/article, il n'est pas prévenu.
L'envoi d'un MP automatique (depuis la personne qui l'ajoute ou depuis un bot ?) serait plus que pratique !

**Comment by Alex-D** [comment]
Depuis le bot selon moi. "Machin t'a ajouté au tuto/article Truc". Avec le lien qui va bien.

**Comment by Nodraak** [comment]
Je prend.
- Envoie d'un message lors de l'ajout d'un auteur :

> Bonjour **username**,
> Tu as été ajouté comme auteur au tutoriel [titre](http://url).
> Bonne rédaction ! _ou_ Tu peux maintenant commencer à rédiger !
- Envoie d'un message lors de la suppression d'un auteur :

> Bonjour **username**,
> Tu as été supprimé des auteurs du tutoriel [titre](http://url).

Le mp est envoyé avec `send_mp`, mais j'ai du mal a comprendre l'utilité des paramètres `leave` et `direct`. Je vais laisser les valeurs par défaut. (Comprendre : une petite doc serai utile, autant les autres paramètres sont explicites, autant là c'est un peu obscure).

**Comment by firm1** [comment]
Pour les informations a savoir (oui il faut que je documente ça):
- direct : permet d'envoyer un mail directement sans envoyer un mp d'abord (utiliser pour avertir un membre qu'il a été ban), ça n'a pas de sens de lui envoyer un mp pour ça sur le site.
- leave : c'est le paramètre qui permet au bot qui envoie les MP de sortir du MP à l'instant ou il l'a envoyé. Utile pour les MP d'informations pour pas que le membre puisse converser avec le BOT

**Comment by Eskimon** [comment]
Je me met en assignee pour signaler que le ticket est réservé par @Nodraak .

Il ne faut pas oublier d'appliquer aussi ce comportement pour les articles.

Pour ce qui est du message, ca me semble tres bien et suffisant ! peut etre rajouter un 

> Tu peux retrouver cet article/tuto en cliquant sur le lien "Mes tutoriels/articles" dans ton menu de profil

**Comment by Eskimon** [comment]
Hop, c'est fait !
