### ISSUE TITLE
Double citation

### ISSUE THREAD

**Issue by Maxou44** [zestedesavoir/zds-site#1175]
Lorsque l'on cite un message on est renvoyé sur l’éditeur, si ensuite on cite à nouveau un message se trouvant sur la page, on est de nouveau redirigé sur un nouvel éditeur (Et on perd notre message en cours de rédaction). Il serait intéressant de l'ajouter au message en cours au lieu d'ouvrir un nouvel éditeur.

**Comment by Eskimon** [comment]
Doublon de cela ? https://github.com/zestedesavoir/zds-site/issues/454

**Comment by Maxou44** [comment]
Oups, en effet ;)
