### ISSUE TITLE
[Tutoriel] Erreur 500 en accédant à une partie supprimée

### ISSUE THREAD

**Issue by geoffroyw** [zestedesavoir/zds-site#1178]
Firm1 a supprimé la partie 6 - les services du tutoriel Symfony. 
Maintenant, si on tente d'accéder à une sous-partie de la partie 6 (http://zestedesavoir.com/tutoriels/324/developpez-votre-site-web-avec-le-framework-symfony2/398/les-services/2013/backup/ par exemple), on se prend une erreur 500 alors qu'une erreur 404 est plus adaptée.

**Comment by firm1** [comment]
Fx'd
