### ISSUE TITLE
La home manque d'explications

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1181]
Je viens de discuter avec deux personnes, l'une qui ne connait rien au contexte et l'autre qui connait vite fait OCR.

Il en ressort que :
1. Si tu ne sais pas à l'avance de quoi parle le site, rien ne l'indique clairement sur la home et l'onglet est fermé sans aller plus loin.
2. Si le visiteur qui connait le lien avec le sdz/ocr que de loin pense qu'on est limités à l'informatique.

Nous n'avions pas perçu ce problème car tous nos visiteurs jusqu'ici nous connaissent et ont probablement lu l'une de nos moult explications quelque part. Or, ce n'est pas du tout le cas des visiteurs qui vont arriver chez nous "par hasard".

Il me parait donc **primordial** d'éclaircir ces points **pour la sortie publique**. Un visiteur perdu parce qu'il ne comprends pas le site ne reviendra probablement pas avant un moment.

La solution la plus simple me parait être un bloc sur la page d'accueil.

**Comment by pierre-24** [comment]
Faudrait pas un topic sur le forum dev pour discuter vite fait de ce qui doit se trouver dans ce cadre ? Et pour réfléchir trente seconde au design de celui-ci ?

**Comment by Alex-D** [comment]
Voilà ce que je vous propose pour discuter : 

http://zestedesavoir.com/forums/sujet/669/zep-04-nouvelle-page-daccueil/

**Comment by SpaceFox** [comment]
Excellente initiative, mais elle n'évite pas la création d'un bloc
explicatif en attendant (puisqu'elle ne sera jamais prête pour la v1)
Le 15 juil. 2014 01:56, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by pierre-24** [comment]
ça n'empêche que ça doit être discuté, séparément si il faut.

(il y a eu le cas avec le bandeau pour les cookies ou une PR avait été refusée pour absence de discution)

**Comment by Alex-D** [comment]
> elle n'évite pas la création d'un bloc explicatif en attendant

On en parle là-bas en fait :)

**Comment by SpaceFox** [comment]
Je pingue ici pour que ce ne soit pas oublié :-)

**Comment by Alex-D** [comment]
Si quelqu'un pouvait me l'assigner. Je vais commencer à travailler de manière effective dessus.

**Comment by Alex-D** [comment]
A valider, merger, puis fermer :)

**Comment by firm1** [comment]
Je réouvre ici parce que je vois que l'issue n'a pas été pris en compte comme il le fallait.

L'urgence était (il me semble) d'avoir un texte informatif sur le home. En gros les points suivants ne sont pas couverts : 

> Il en ressort que :
> - Si tu ne sais pas à l'avance de quoi parle le site, rien ne l'indique clairement sur la home et l'onglet est fermé sans aller plus loin.
> - Si le visiteur qui connait le lien avec le sdz/ocr que de loin pense qu'on est limités à l'informatique.

**Comment by Eskimon** [comment]
@firm1 Tu as teste en allant sur le site sans être membre ?

**Comment by firm1** [comment]
Ah oki en effet, je n'ai pa vu la condition.

Je ferme donc.
