### ISSUE TITLE
Bandeau orange sur les bétas

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1182]
Bug tout bête : 

Quand on est sur les bétas des tutos, on retrouve parfois les "ce tuto n'as pas d'introduction/conclusion" du mode _offline_. Ça serait bien de les enlever :)

(si vous trouvez que ça rentre en V1, vous pouvez me l'assigner, ça prendra 30 secondes à tout casser, d'ailleurs, je suis à peu près responsable de cet oubli).

**Comment by Eskimon** [comment]
C'est si genant que ca ce banderau ? Tu peux faire une capture d'ecran je vois pas a quoi ca ressemble ^^ ?
Sinon cadeau, je te l'assigne. Et comme c'est un bug ca rentre dans les corrections du freeze.

**Comment by pierre-24** [comment]
Capture d'écran : 

![Bandeau orange ](http://zestedesavoir.com//media/galleries/407/8cae7b4d-8860-4e53-84b5-857e65718613.png.960x960_q85.png)

[à voir en vrai ici](http://zestedesavoir.com/tutoriels/off/342/tutoriel-de-test/) :-)

**Comment by Eskimon** [comment]
Et sur la version live il n'y a pas ce bandeau c'est ca ?

**Comment by pierre-24** [comment]
Exactement :)

(d'ailleurs ça n'aurais pas de sens)

**Comment by Eskimon** [comment]
Vu que c'est un bug, je suppose que ca peut être corrigé malgré le freeze. Mais c'est clair que comme tu disais c'est pas urgent ^^ Si tu veux le faire vas-y (ou on laisse ca a qqun de plus débutant pour un entrainement ?)

**Comment by pierre-24** [comment]
Si tu trouve un débutant, je passe volontiers la main, c'est vraiment l'affaire de deux minutes (et de quelques `if`) pour corriger ça :)

**Comment by Eskimon** [comment]
@Florianboux si tu veux t’entraîner ;)

**Comment by Axylium** [comment]
Yep, je vais voir si je peux faire quelque chose de potable. ^^

**Comment by pierre-24** [comment]
Alors @Eskimon  peut te l'assigner :)

**Comment by Eskimon** [comment]
Ça aurais été avec plaisir, mais @Florianboux n'est pas encore dans la liste (poke @ArnaudCalmettes ) du coup je me met en placeholder pour garder la place au chaud et montrer que qqun est dessus :)

**Comment by ArnaudCalmettes** [comment]
Done.

Ne pas hésiter à me MP sur le site pour ce genre de trucs. ;)

**Comment by pierre-24** [comment]
Aaaah, vous avez été trop vite, j'ai pas eu le temps de faire QA, donc vous en avez oublié un dans `/templates/tutorial/includes/chapter.part.html` !!

ping @Florianboux :p

**Comment by devock** [comment]
My bad, j'ai suivi bêtement les instructions de la QA. Soit @Florianboux refait une PR, soit je revert et tu corrige ça. 
Qu'elle est la meilleure des pratiques ? 

En attendant, je réouvre.

**Comment by pierre-24** [comment]
Là, je suis occupé sur autre chose, et j'aurais de toute façon pas le temps avant ce soir (et j'ai une autre issue à traiter). Donc pour le moment, je laisse @Florianboux si il le désire, si c'est pas réglé d'ici demain, je reprendrai la main :)

**Comment by firm1** [comment]
Pour éviter ce genre de pépins a l'avenir, il faut prendre l'habitude coté QA de tester les choses au delà des recommendations, car en général ce que le dev vous demande de tester, en fait il l'a déjà fait chez lui.

**Comment by pierre-24** [comment]
Là, en l’occurrence, ledit _dev'_ est novice et c'est (c'était) sa première PR. Du coup, je pense qu'il n'était pas tout à fait conscient de ça.

**Comment by devock** [comment]
@firm1 d'où le "bêtement" dans ma phrase, je ferai gaffe la prochaine fois.

**Comment by cgabard** [comment]
@pierre-24 : Je pense qu'en l'occurence il ne jette pas la pierre au dev mais à celui qui a fait la QA, @devock , pour ne pas avoir été plus loin que les indications de base. Mais bref c'est pas grave

**Comment by Axylium** [comment]
Bon, désolé pour cette QA un peu hasardeuse !

Pour rester simple, je vais faire une seconde PR, pour compléter ce qu'il manque.

**Comment by pierre-24** [comment]
Ok. Et au moment ou tu l'as fait, fait moi une "@" invocation, pour que je checke que t'en a pas oublié ;)

**Comment by Eskimon** [comment]
> Bon, désolé pour cette QA un peu hasardeuse !

T'excuse pas, c'est pas toi qui est fait la QA (Quality Assurance) mais devock donc tout est de sa faute (niark niark niark !)

Toi tu as fait la PR (Pull Request) qui s'est avéré incomplète, c'est pas dramatique ;)

**Comment by cgabard** [comment]
Oui t'inquiete pas @Florianboux c'etait a @devock de s'en rendre compte. Mais comme on a une super équipe de dev, ça a été détecté rapidement donc pas de soucis !

**Comment by pierre-24** [comment]
à fermer  !
