### ISSUE TITLE
Impossible de supprimer la licence d'un tutoriel

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1183]
Ainsi [que je l'ai dit sur le forum](http://zestedesavoir.com/forums/sujet/668/enlever-la-licence-ne-fonctionne-pas/) : 

>  Quand on donne une licence à un tutoriel et qu'ensuite on l'enlève (qu'on sélectionne "------------" dans la liste déroulante), la licence n'est pas modifiée et reste à sa valeur précédente.

Ce bug est dû au fait que si la valeur de la liste est remis à `""` (chaine vide), le _back_ n'en tient pas compte (`if request.POST['licence']` et ainsi de suite).

**Comment by Eskimon** [comment]
Est-ce vraiment un bug en fait ? Car cette licence vide "-------" ne devrait pas exister. Le droit francais implique que les droits d'auteurs sont inalienable, donc CC-BY est a priori le champ qui devrait etre par defaut... (et dans ce cas la question/Bug ne se pose plus)

**Comment by pierre-24** [comment]
Faudrait voir. C'est pas Arius le spécialiste en droit ?

**Comment by Eskimon** [comment]
Si, tu peux le MP si tu veux :) (et ajoute moi dans la conversation ca m’intéresse :) )

**Comment by pierre-24** [comment]
Fait :)

**Comment by cgabard** [comment]
Oui enfin je pense que le "----" ne correspond pas à un CC-0 qui ne peut exister en France mais a une licence de non diffusion. L'équivalent d'un logiciel privateur en gros. En absence de licence l'auteur garde tous les droits, personne n'a le droit d'y toucher. Donc il y a bien une différence avec la cc-by qui elle autorise la libre re-diffusion et le modifs.

**Comment by Eskimon** [comment]
Dans ces cas la faudrait marquer clairement "Tout droits réservés" plutôt que des tirets...

**Comment by SpaceFox** [comment]
Plussun, pour moi toutes les licences devraient être clairement explicitées et il devrait être impossible de ne pas choisir.

**Comment by Eskimon** [comment]
Apparemment cette licence "------" qui fait bugguer semblerait etre un relicat de vieux trucs... Si qqun a acces a l'interface django, il pourrait jeter un oeil la dessus ? Ca expliquerait pourquoi quand on veut selectionner cette licence le controlleur se plante... (d'ailleurs a verifier dans tutos/articles mais est-ce que la licence est bien mis comme "nullable=false" ?

**Comment by pierre-24** [comment]
Non, elle l'es pas, et j'avais justement _bugfixé_ ça pour les articles. Après, si il faut complètement virer ça, why not (y'a pas le `nullable=false`).

**Comment by firm1** [comment]
En fait la vrai signification du '----' c'est "Choisissez votre licence". Il devrait être renommé ainsi.

C'est pour celà que lorsqu'une licence est choisie, tu ne peux plus choisir ça, et lorsqu'une licence n'est pas choisie, il te demande d'en choisir une.

Pour le cas du "pas de licence", il faudrait juste rajouter en base la licence `CC-0` dans la liste est ça devrait aller/être cohérent.

En gros, 2 actions : 
- rajouter une licence en base qui s'appelle "CC-0"
- renommer les `----` en `Choissisez une licence`.

Tant qu'a faire, on pourrait rajouter d'une manière ou d'une autre un description de la licence qu'on choisi qui s'affiche en dessous en javascript (on a dejà la description des licences stockées en base).

**Comment by pierre-24** [comment]
Et [vous saviez pas le dire avant ?](https://github.com/zestedesavoir/zds-site/pull/1180) ?!?

> Tant qu'a faire, on pourrait rajouter d'une manière ou d'une autre un description de la licence qu'on choisi qui s'affiche en dessous en javascript (on a dejà la description des licences stockées en base).

Freeze, toussa ...

**Comment by cgabard** [comment]
Non pas de CC-0, elle est equivalente à une CC-BY en France.

Par contre il faut une licence "tout droit réservé" pour le contenu "non CC"

Christophe.

2014-07-18 12:41 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by pierre-24** [comment]
Je plussoie @cgabard avec une citation d'Arius via MP : 

> Non. Il faut un choix dans la liste qui indique clairement que l'auteur désire garder ses droits. Ce n'est pas à nous, peu importe que ZdS soit né d'une volonté de libre partage de la connaissance, de "forcer" un auteur à choisir une licence CC(y compris la CC0) si celui-ci ne le souhaite pas. C'est son oeuvre, il lui appartient de décider quels droits donner ou non. En revanche, il est de notre "devoir" (d'honnêteté et de transparence) de fournir aux auteurs plusieurs options - les licences CC mais aussi une option indiquant qu'il désire garder ses droits - et laisser les auteurs décider de ce qui est le mieux selon eux. Ne pas ajouter la possibilité de dire "mes droits sont réservés", c'est forcer la main.

**Comment by firm1** [comment]
Donc en résumé, il y'a donc deux actions à mener : 
- renommer les `----` en `Choissisez une licence`
- rajouter une licence en base qui s'appelle "Tout droit réservé"

**Comment by Eskimon** [comment]
- Mettre la licence en `nullable = false` dans le modèle
- Mettre la licence en `required` dans le formulaire

**Comment by firm1** [comment]
Eskimon, non justement.

Si tu interdis d'avoir une licence vide dans ta bd, ça peut devenir chiant pour l'auteur qui ne sait pas trop quelle licence il veut lorsqu'il crée son tutoriel. Pour de nombreuses raisons. C'est un peu comme les catégories, elle ne sont pas obligatoires, mais si tu envois en validation ton tutoriels sans licence et sans le ranger, et bah ça passera pas.

Quand le membre lambda vient créer son tutoriel, il n'a pas forcément d'idée précise sur comment il souhaite le diffuser, donc ça ne doit pas être bloquant pour lui. On devrait avoir un minimum de champs obligatoire à ce niveau. On a l'avantage que la validation vérifiera ce genre de chose.

**Comment by Eskimon** [comment]
Oui mais légalement ca signifie quoi "pas de licence" ? C'est pas égale a "Tout droits réservé" ?

Ma question reformule : On gère comment le cas de la licence vide et/ou On gère comment si l'auteur reste sur "Choisissez une licence" ?

**Comment by SpaceFox** [comment]
On peut laisser une option "choisissez votre licence" qui ne devra jamais
être choisie à la validation.

D'autre part je laisserais CC-0 pour les auteurs non français.

**Comment by firm1** [comment]
> Ma question reformule : On gère comment le cas de la licence vide et/ou On gère comment si l'auteur reste sur "Choisissez une licence" ?

la consignes des validos c'est , refuser ça

**Comment by cgabard** [comment]
Pourquoi ne pas mettre le "Choisissez une licence" dans la db comme les
autres ? Du coup ce texte sera visible partout où la licence doit
s'afficher et ça aura le mérite d'etre visible, pour le membre comme pour
le valido, qu'il n'a pas encore complété cette option.

Christophe.

2014-07-18 14:22 GMT+02:00 Eskimon notifications@github.com:

**Comment by firm1** [comment]
> Pourquoi ne pas mettre le "Choisissez une licence"

"Choissez une licence" n'est pas une licence .. lol

Si aujourd'hui un auteur décide d'envoyer son tuto en validation alors qu'il n'est dans aucune catégorie, le valido devra refuser son tutoriel.

Si l'auteur envoi en validation un tuto sans la licence, le valido refuse de publier

Si l'auteur envoi en validation son tuto sans logo , refus de validation.

Donc tout devrait rouler

**Comment by Eskimon** [comment]
> Si l'auteur envoi en **validation un tuto sans la licence**, le **valido refuse de publier**

Donc la licence ne devrais pas pouvoir etre nullable... non ?

**Comment by cgabard** [comment]
En fait firm1 veut éviter que ce champ soit obligatoire à la création du
tuto pour ne pas bloquer les potentiels auteurs qui ne savent pas quoi
choisir pour ce champ. Il vaut mieux que les valido expliquent aux auteurs
qu'il faut choisir une licence, en leur renvoyant vers des infos sur le
sujet, si ils n'ont pas choisis que de bloquer la création si l'auteur ne
sais pas quoi mettre.

Christophe.

2014-07-18 14:58 GMT+02:00 Eskimon notifications@github.com:

**Comment by firm1** [comment]
@cgabard  a tout dit

**Comment by ArnaudCalmettes** [comment]
Je pense que c'est casse-gueule. Par défaut, le droit français considère que tous les droits de l'oeuvre sont réservés à l'auteur, donc il **faut** mettre cette valeur par défaut.

Les validos ont autre chose à faire que de vérifier les licences. Ce n'est pas leur boulot.

**Comment by Alex-D** [comment]
Du coup, c'est pas un bug, c'est une feature ? Si oui, on peut clore cette issue je pense.

**Comment by pierre-24** [comment]
Non, parce que il faut qu'on la garde en tête. Je dirais juste la reculer un peu, sans mentir (voir [mon avis sur le sujet](http://zestedesavoir.com/forums/sujet/876/les-issues-pour-la-v1/?page=1#p12491)).

**Comment by ArnaudCalmettes** [comment]
Conclusion : 
- Ajouter un champ "tous droits réservés" qui fait office de licence par défaut (ce qui correspond à la réalité aux yeux de la loi).
- Retirer le "-------" : les tutos prennent par défaut la licence "tous droits réservés".

**Comment by pierre-24** [comment]
Pourrait-tu ajouter ce champ dans la base de donnée ainsi que son `pk` dans le settings.py (par exemple `DEFAULT_LICENCE_PK` ou un truc du genre) ? Je veux bien ensuite me charger de faire correspondre les formulaires.

EDIT : il devrait au moins y avoir deux licences dans les fixtures, dont celle là. Je peux également m'en charger le cas échéant.

**Comment by ArnaudCalmettes** [comment]
Moi personnellement non, je ne peux pas prendre cette action.

**Comment by pierre-24** [comment]
Il me manque juste les droits d'admins pour rajouter une licence, en fait, le reste, je peux le faire tout seul ^^ 

qui  dois-je pinger (un superuser sur le site, autrement dit) ?

**Comment by Eskimon** [comment]
@firm1

**Comment by pierre-24** [comment]
On en est ou, ici ?

**Comment by SpaceFox** [comment]
J'ai créé la licence "Tous droits réservés" d'ID 7.

Est-ce que ça te suffit @pierre-24 ?

**Comment by pierre-24** [comment]
Je vais normalement pouvoir faire quelque chose à partir de là, donc un très grand merci :)

(ps: assignez moi cette issue)

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé !
