### ISSUE TITLE
Le code Google Tag Manager

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#1184]
J'ai remarqué une baisse des stats de Google Analytics sur le site, au départ je pensais à un soucis dans GA, car il me mettait un message d'erreur, mais finalement ça n'a pas l'air d'être le problème.

Je pense qu'il y a clairement un soucis dans le code et surtout que la baisse de trafic correspond à la MEP du 11 juillet qui incluait la PR #1132 

En théorie, le code GTM devrait apparaître après l'id gtm mais avec l'inspecteur de code de chrome il n’apparaît pas donc si quelqu'un peut regarder ça rapidement.

**Comment by devock** [comment]
Pour compléter : le code à l'air de s'exécuter de temps en temps mais il y a une baisse de 90% dans les stats...

**Comment by SpaceFox** [comment]
Il y a eu une.baisse sensible de trafic ce WE prolongé.
À croiser avec les stats Munin.

**Comment by devock** [comment]
Ce n'est pas lié, la fonction temps réelle ne fonctionne même pas alors qu'elle le devrait. Là si je navigue sur le site, GA m'indique qu'il y a 0 utilisateur actif sur le site alors que j'y suis et qu'il devrait mettre au moins 1 utilisateur actif.

**Comment by SpaceFox** [comment]
Ah non, pas 90% la baisse dans Munin…

**Comment by devock** [comment]
Bon je viens de faire un test plus poussé : 
- Si je supprime le cookie _ga et le cookie hasconsent
- Que je fais F5 
- Que je ré-accepte les cookies pour GA : le code est bien exécuté, j'ai bien dans l'inspecteur de code de Chrome la balise script de GTM qui apparaît.

Jusque là c'est normal. 

Par contre, ensuite si je navigue, même si hasconsent est à true le script de GTM n'apparait plus dans l'inspecteur de code de Chrome. 

EDIT : correction de mon commentaire qui ne s'affichait pas complètement.

**Comment by Alex-D** [comment]
> Par contre, ensuite si je navigue, même si hasconsent est à true le script de GTM n'apparait plus dans l'inspecteur de code de Chrome.

C'est assez étrange, je vais y jeter un oeil.

**Comment by Alex-D** [comment]
A valider !

**Comment by Eskimon** [comment]
Merged, je ferme !
