### ISSUE TITLE
Erreur dans le module de recherche

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1186]
J'obtiens une erreur 500 en recherchant le terme "Android" sur le site.

URL : http://zestedesavoir.com/rechercher/?q=Android

**Comment by DevHugo** [comment]
Blender, ne marche pas non plus. C'est pas liés au fait qu'il est pas de résultat, ni à la majuscule. Bizarre.

**Comment by Eskimon** [comment]
@firm1 : on a toujours pas de fichiers de log sur la prod pour analyser ce genre de chose ?

**Comment by gustavi** [comment]
Ça semble résolu, je n'ai plus de 500.

**Comment by firm1** [comment]
> @firm1 : on a toujours pas de fichiers de log sur la prod pour analyser ce genre de chose ?

si si, mais vu qu'il est sur le serveur, je peux pas le lire tant que j'ai pas de pc de travail sous la main

> Ça semble résolu, je n'ai plus de 500.

A mon avis c'est pas résolu dans le sens ou hier c'était uniquement sur le mot "Android" ça pourrait réapparaitre sur un autre mot.

**Comment by Eskimon** [comment]
Ca va etre marrant a debuggue :)

Si un jour tu as 5 minutes pour choper les logs hesite pas a les uploader qque part :)

**Comment by DevHugo** [comment]
Blender, ne marche toujours pas. 

J'ai trouvé un truc intéressent, si on décoche l'option "Parties des tutoriels", la ça marche, peut-être une piste.

[Exemple](http://zestedesavoir.com/rechercher/?q=Blender&models=article.article&models=tutorial.chapter&models=tutorial.extract&models=forum.post&models=forum.topic&models=tutorial.tutorial)

**Comment by Eskimon** [comment]
Est-ce que solr irait pas taper dans des chapitres devenus 404 quand les tutos se mettent a jour etc (auquel cas les recentes modifs du code pourront ameliorer ca) ? J'il l'impression qu'il y a un souci de parametrage la dessus... mais comme je connais rien a solr...

**Comment by DevHugo** [comment]
Pour moi, l’expression même de "Parties des tutoriels" est pas très "claire". 

Bizarre, aussi il ne trouve pas les articles même si on copie-colle le titre de l'article.

Autres cas qui ne marchent pas, tous les articles: et, donc, ... .

**Comment by DevHugo** [comment]
De plus en plus bizarre, si l'utilisateur tape 3D directement, marche. Si l'utilisateur coche la case "Parties des tutoriels", une jolie 405.

**Comment by firm1** [comment]
Je ne sais pas si on a eu une évolution du modèle des tutos sans MAJ du [modèle solr](https://github.com/zestedesavoir/zds-site/blob/dev/output_solr.txt) ça pourrait venir de là.

ça peut venir aussi des templates qui utilise des objets sans vérifier s'il sont à `None` ou pas.

Bref, c'est pas méchant comme issue.

**Comment by zopieux** [comment]
http://zestedesavoir.com/rechercher/?q=cat%C3%A9gori
http://zestedesavoir.com/rechercher/?q=cat%C3%A9gorie

Je ne trouve pas de pattern qui cause ces 500. J'en conclus à un bug contextuel en fonction des résultats. Ce ticket doit être **marqué prioritaire/bloquant**.

**Comment by gustavi** [comment]
Je pense que c'est lié aux accents non ? Les seules 500 que j'ai eu c'était des recherches avec des accents.

**Comment by zopieux** [comment]
C'est très probable mais il faut noter que « caté » voire « é » ne provoque pas de bug.

**Comment by firm1** [comment]
Pour moi le souci vient de là

> ça peut venir aussi des templates qui utilise des objets sans vérifier s'il sont à `None` ou pas.

**Comment by Alex-D** [comment]
Il y a déjà 1000 conditions de partout dans le template. Et sans log on ne peux même pas savoir d'où ça vient. Du coup, est-ce que tu pourrais sortir un log de la prod @firm1 ?

**Comment by firm1** [comment]
> Du coup, est-ce que tu pourrais sortir un log de la prod @firm1 ?

Je sortirait un log quand j'aurai un ssh de dispo sur pc. Je n'y pense jamais

**Comment by Alex-D** [comment]
C'est corrigé, je ferme.

**Comment by Eskimon** [comment]
A monitorer tout de même, j'ai pas l'impression que c’était qu'une affaire d'accents puisque certains mots-clés sans accents passait quand même en 500 il me semble...

**Comment by firm1** [comment]
> A monitorer tout de même, j'ai pas l'impression que c’était qu'une affaire d'accents puisque certains mots-clés sans accents passait quand même en 500 il me semble...

+1  , je rouvre l'issue, car ce n'est pas qu'un problème d'accent.

**Comment by Eskimon** [comment]
Bon c'est vraiment random... Apparemment elyppirre a une 500 avec _%2521_ alors qu'Arius et moi meme n'avons juste aucun resultat.

**Comment by Alex-D** [comment]
Dans tous les cas, le patch est pas en prod il me semble... donc c'est difficile de savoir où on en est : 
- les bugs ne surviennent qu'en prod
- nos derniers patchs ne sont pas en prod
- il faudrait les logs des dites erreurs

**Comment by artragis** [comment]
à 15h08, le 31/07 (version RC7), blender me donne une 500.

**Comment by gustavi** [comment]
J'en ai également mangé de partout.

**Comment by Alex-D** [comment]
Sans backtrace / log on avancera jamais là dessus.

**Comment by DevHugo** [comment]
En local, avec une première indexation avec solr (juste des messages du forum) j'ai cette stack-trace, si j'utilise le mot clé "Rédiger" : https://gist.github.com/DevHugo/bf1b5ae3b61a698d9aee. J'ai jamais utilisé solr avant peut-être c'est mon installation qui foire.

Pour installer solr, j'ai suivi la doc de firm1 avait faite dans une PR.

**Comment by SpaceFox** [comment]
J'ai branché un outil supervision de logs sur la prod (sentry, merci à @gustavi ) - dont je ne peux malheureusement pas donner les accès en public, c'est un test sans aucune sécurité.

Pour l'instant je n'arrive pas à avoir d'erreur... on verra demain midi.

**Comment by zopieux** [comment]
```
full_html = "%s" % response
```

Il semblerait que `response` ne soit pas une chaîne Unicode mais des bytes, d'où l'erreur.

**Comment by Eskimon** [comment]
Au passage, voici un bout de log pour la recherche blender :
`VariableDoesNotExist: Failed lookup for key [topic] in u'<Partie pour D\xe9butez dans la 3D avec Blender, 2>'`
ce qui semble confirmer zopieux

**Comment by SpaceFox** [comment]
Hmm, ça semble lié au bug des tutos en bêta qui plantent. A voir après la prochaine MEP.

**Comment by firm1** [comment]
Pour info, ça ne venait pas de la ligne remontée par @Zopieux . Le bug est normalement corrigé par la PR #1331 , il devrait disparaître après la MEP

**Comment by firm1** [comment]
Fx'd
