### ISSUE TITLE
Erreur 500 dans les profils

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1187]
Il y a des erreurs 500 dans les liens vers les articles/tutos a partir d'un profil.

Cette erreur est visible sur le profil de devock par exemple : http://zestedesavoir.com/membres/voir/devock/

Si on essaie de voir dans la partie "Activites":
- Ses tutos en beta : **OK**
- Ses tutos publiés : **NOT OK, 500**
- Ses articles en ligne : **NOT OK, 500** 
- Ses sujets créés : **OK**
- Ses messages postés : **OK**

L'erreur peut-être reproduite en tant que staff ou comme membre lambda/déconnecté.

**Comment by Eskimon** [comment]
Erreur de type : NoReverseMatch
Facile a reproduire en local, je corrige ca tout a l'heure !

**Comment by Eskimon** [comment]
Je reouvre, erreure toujours presente apparemment... weird
http://zestedesavoir.com/forums/sujet/715/le-langage-ruby/#p11053

**Comment by Eskimon** [comment]
Le probleme est que l'on cherche à acceder au tuto dans le dossier 'tutoriels-public' plutot que 'tutoriels-private'... Comme je suis complètement à la ramasse dans cette histoire sur les tutos, je laisse @firm1 @pierre-24 @artragis @gustavi s'en occuper :D

BroTip :
/zds/tutorial/views.py in find_tuto -> ligne 2098 `mandata = tutorial.load_dic(mandata)`
/zds/tutorial/models.py -> ligne 190 `mandata['get_introduction_online'] = self.get_introduction_online()`

(facile à reproduire en local, suffit d'avoir un tuto en beta)

**Comment by pierre-24** [comment]
Aller, je prend.

**Comment by SpaceFox** [comment]
Je vois plein de PR fermées sur cette issue. Est-elle corrigé ? Si non, que reste-t-il ?

**Comment by Alex-D** [comment]
Si j'ai bien compris, la PR #1314 est censée corriger le bug.

**Comment by pierre-24** [comment]
Je reprend, la PR #1314 n'est plus à l'ordre du jour.

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé
