### ISSUE TITLE
Un chapitre ne peut plus etre supprimé une fois en ligne

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1189]
Pour un big-tuto, un chapitre ne peux pas etre supprimé (pourtant un extrait ou une partie peuvent). A l'emplacement de la croix de suppression on trouve "ce chapitre ne peut etre supprimé car publié".

Ce n'est pas le comportement attendu, il faudrait pouvoir le supprimer tout de même.

Est-ce un test front qui bloque ou est-ce le back ?

**Comment by firm1** [comment]
> Est-ce un test front qui bloque ou est-ce le back ?

C'est un test front qui bloque, car dans les tests on voit bien que [c'est possible de supprimer un chapitre](https://github.com/zestedesavoir/zds-site/blob/master/zds/tutorial/tests.py#L784).

**Comment by Eskimon** [comment]
Ok cool, ca devrait etre assez simple a resoudre du coup :)

**Comment by Eskimon** [comment]
Bon c'est réparé (pas si simple que ca, il y avait un bug dans le bug : bugception)... La solution est implémenté mais j'aimerais faire un test (car je pouvqis générer de la 500 plutot que de la 404 une fois le test enlevé) donc il faut patienter ;)
Les tests seront inspiré (voir doublon donc j'attends) de ceux prévus dans cette PR : https://github.com/zestedesavoir/zds-site/pull/1179

**Comment by Eskimon** [comment]
Si qqun maitrisant les tutos veut prendre le relais, moi je suis un peu largué ^^

**Comment by SpaceFox** [comment]
On en est où ici ?

**Comment by Alex-D** [comment]
Au delà de la condition front qui n'affiche pas le bouton, il y a des soucis back, @Eskimon a abandonné, je pense qu'il va falloir que @firm1 y jette un oeil.

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé
