### ISSUE TITLE
Bug : plusieurs informations des articles ne sont pas versionnées

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1195]
De la manière dont est écrit actuelement la fonction `view_online()` (dans [/zds/article/view.py à la ligne 132](https://github.com/zestedesavoir/zds-site/blob/dev/zds/article/views.py#L132)), tout changement du `manifest.json` en _off_ se répercute directement sur la version _online_ (donc titre, sous titre et ainsi de suite), tout simplement parce que y'a pas l'histoire de `repo` (qui est présente dans `view()`).

Bref, si c'est bloquant, assignez la moi, j'ai identifié le problème (sauf si vous êtes motivé, je laisse la main)

**Comment by Eskimon** [comment]
Cadeau ! Ca me parait mine de rien assez important...

**Comment by pierre-24** [comment]
J'attend l'avis de @ArnaudCalmettes sur le milestone avant ;)

(et le cas échéant, je couplerait ça avec #754 )

**Comment by firm1** [comment]
On dirait que la PR #1261 a un impact positif sur cette issue.

On peut la fermer ?

**Comment by pierre-24** [comment]
Oui, puisque t'as activé le versionnage des articles !
