### ISSUE TITLE
Pagination en double sur la lecture zen

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#1196]
Via [PG06 sur le forum](https://zestedesavoir.com/forums/sujet/682/pages-des-commentaires-en-double/)

---

Sur les articles et les tutoriels, quand nous passons en lecture zen, les commentaires disparaissent, mais la pagination reste. Ce qui fait qu'en plus de nous retrouver avec une pagination inutile, elle apparaît en double.

Vu que une image est mieux que de long discours voici : 

![](http://img11.hostingpics.net/pics/845103zen.jpg)

**Comment by Alex-D** [comment]
Ah bah oui, j'ai masqué les commentaires, mais pas leur pagination :D

Je fais un patch now.

**Comment by sandhose** [comment]
Fix'd, merci Alex
