### ISSUE TITLE
Message indiquant que l'utilisateur n'a créé aucun sujet

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#1197]
Via [Gustavi sur le forum](http://zestedesavoir.com/forums/sujet/683/problemes-lies-au-membre-clem/)

---

Quand on va sur le profil d'un utilisateur qui n'a encore créé aucun sujet, au lieu d'avoir un message l'indiquant, le tableau apparaît.

Je pense, que je m'en occupe, ça doit pouvoir se faire avec des conditions. Me faudrait juste l'appuie d'un _aîné_, pour me lancer.

**Comment by gustavi** [comment]
J'ai créé une PR https://github.com/zestedesavoir/zds-site/pull/1198 (4 lignes à rajouter).

**Comment by Axylium** [comment]
Faudra voir, pour que quelqu'un te l'assigne.

Et avant de faire la PR, n'oublies pas de lire les règles à propos de ces dernières. ;)

**Comment by Eskimon** [comment]
Je me met en placeholder :)
