### ISSUE TITLE
Bug : lien de citation retourne 404 dans les commentaires d'articles

### ISSUE THREAD

**Issue by jcval** [zestedesavoir/zds-site#1199]
Dans les commentaires d'articles (exemple ici http://zestedesavoir.com/articles/41/bilan-de-la-premiere-semaine/?page=2#p8349), le lien sur le pseudo d'une citation qui pointe vers le message cité retourne 404, il manque http://zestedesavoir.com

**Comment by Eskimon** [comment]
Il y a pas le meme probleme dans les MP d'ailleurs ? (et ptet aussi dans les commentaires de tuto ?)

**Comment by firm1** [comment]
Pour fixer ce bug

### Sur les articles

allez [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/article/views.py#L910) et remplacer : 

``` python
text = u'{0}Source:[{1}]({2})'.format(
                text,
                reaction_cite.author.username,
                reaction_cite.get_absolute_url())
```

par 

``` python
text = u'{0}Source:[{1}]({2}{3})'.format(
                text,
                reaction_cite.author.username,
                settings.SITE_URL,
                reaction_cite.get_absolute_url())
```

### Sur les tutoriels

Allez [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L2913) et remplacer : 

``` python
text = u"{0}Source:[{1}]({2})".format(
                text,
                note_cite.author.username,
                note_cite.get_absolute_url())
```

par

``` python
text = u"{0}Source:[{1}]({2}{3})".format(
                text,
                note_cite.author.username,
                settings.SITE_URL,
                note_cite.get_absolute_url())
```

### Sur les MPs

Allez [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/mp/views.py#L365) et remplacer : 

``` python
text = u'{0}Source:[{1}]({2})'.format(
                text,
                post_cite.author.username,
                post_cite.get_absolute_url())
```

par

``` python
text = u"{0}Source:[{1}]({2}{3})".format(
                text,
                post_cite.author.username,
                settings.SITE_URL,
                post_cite.get_absolute_url())
```

Faudra penser à faire une factoriser ça un jour d'ailleurs.

**Comment by Axylium** [comment]
Je m'en occupe. ;)

**Comment by Axylium** [comment]
Bon, j'ai rajouté la ligne partout, mais j'ai toujours le même problème. Lors de la citation il me met simplement : http://127.0.0.1:8000/
