### ISSUE TITLE
'Settings' object has no attribute 'CRISPY_TEMPLATE_PACK' error

### ISSUE THREAD

**Issue by ChantyTaguan** [zestedesavoir/zds-site#12]
En allant sur la page d'inscription, j'ai une erreur 'Settings' object has no attribute 'CRISPY_TEMPLATE_PACK' error.

Visiblement un souci avec la version de crispy forms.

(Dirty) Quick fix : désinstaller django-crispy-forms puis le réinstaller mais la version 1.3.2

```
pip uninstall django-crispy-forms
pip install django-crispy-forms==1.3.2
```

Doit y avoir moyen de s'arranger pour que ça fonctionne avec la dernière version, pas encore vérifié.

**Comment by Ge0** [comment]
(Merci Taguan, ta méthode est parfaite et marche du feu de Dieu)

**Comment by delphiki** [comment]
On peut aussi ajouter :

``` python
CRISPY_TEMPLATE_PACK='bootstrap'
```

dans les settings.

**Comment by hadrienj** [comment]
Merci delphiki !
