### ISSUE TITLE
[Validation] Historique des messages au validateur

### ISSUE THREAD

**Issue by coma94** [zestedesavoir/zds-site#1200]
Dans l'historique de validation, on ne dispose que des status successifs de la validation (accepté/refusé) et pas les messages envoyé par l'auteur et le validateur.

Je pense qu'il serait utile de pouvoir consulter ce "dialogue" dans l'historique, par exemple pour vérifier que les points à corrigés l'ont bien été. Cela permettrait à des validateurs de se relayer sur la validation d'un tuto.  

Je ne me rend pas compte de la difficulté de la tâche, si les messages sont actuellement totalement supprimés cela demandera un stockage en BDD supplémentaire.

**Comment by Alex-D** [comment]
Il me semble que c'est un simple problème de front. Je vais y jeter un oeil.

**Comment by Alex-D** [comment]
Corrigé, je ferme. Ca arrivera à la prochaine MEP.
