### ISSUE TITLE
[Validation] Url de la version originale auto-remplie

### ISSUE THREAD

**Issue by coma94** [zestedesavoir/zds-site#1201]
Lorsque l'url a été renseignée à la première validation du tuto, il serait bien que le champ soit auto-rempli lors des validations suivantes, afin d'éviter un éventuel oubli.

**Comment by coma94** [comment]
J'essaye de m'y mettre

**Comment by coma94** [comment]
On ferme lorsque c'est en prod c'est ça ?

**Comment by Eskimon** [comment]
Oui pardon j'ai zoublié ! Voila Pouf!

**Comment by coma94** [comment]
J'ai toujours ce bug en prod.. La PR est mergée en dev mais pas en master ni en prod...  
Est-ce normal (donc prévu) ? Un oubli ?

C'est assez chiant de devoir aller vérifier la source de la page pour trouver un "canonical" à chaque re-validation d'un tuto...

**Comment by Alex-D** [comment]
> La PR est mergée en dev mais pas en master ni en prod...

A l'heure où j'écris ce message, c'est même plus sur la branche dev... mais sinon oui ça sera remis sur master.
