### ISSUE TITLE
Afficher la version du site sur la page de profil

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1202]
[Via Krostar](http://zestedesavoir.com/forums/sujet/694/affichage-de-la-version-du-site-en-bas-a-gauche)

La version du site ne s'affiche pas en bas a gauche dans [la page de profil](http://zestedesavoir.com/membres/parametres/profil/).

**Comment by Alex-D** [comment]
A noter que le même problème apparaît sur les pages de recherche.

Il faudrait assigner @gustavi à la tâche.
