### ISSUE TITLE
Affichage des box de la homepage décalés

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#121]
En essayant de me brancher sur la branche intégration, en local, j'ai remarqué que en l'état (en téléchargeant le main.css sur le ftp d'Alex) que la sidebar qui est censé être a gauche est complètement décalée sur le bas. Ce qui donne un affichage presque barbare.

Le même comportement survient dans le topic d'un forum ou la sidebar qui est censé être a gauche est décalée vers le bas.

Il faudrait corriger ce bug.

**Comment by Alex-D** [comment]
> Il faudrait corriger ce bug.

Thanks captain obvious...

Plus sérieusement, comme d'hab : navigateur, version, résolution d'écran, screenshot, ...

Merci ;)

**Comment by firm1** [comment]
Je l'ai testé sous Chromium hier.

Ceci dit, quand je le merge sur la [preprod](preprod.zestedesavoir.com) il a l'air de marcher normalement. Peut-etre un merge foireux de ma part, à creuser.

**Comment by Alex-D** [comment]
Il y a des bugs quand les colonnes sont vides, mais à partir du moment où il y a quelque chose dedans, tout fonctionne. Par principe, les colonnes ne seront jamais vides donc je n'ai pas corrigé ce bug.
