### ISSUE TITLE
Le versionnage ne marche pas partout

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1212]
[extension de l'issue #1195]

Ce bug concerne autant les articles que les tutoriels et vient d'un problème très simple : les informations de la BDD sont, quoiqu'il arrive, toujours les informations du dernier _draft_ en date. Ce qui signifie que si le titre à changé depuis la dernière validation (par exemple, mais pas seulement), sur certaines pages, c'est le titre du _draft_ qui est employé, et pareil pour le sous-titre, la miniature et ainsi de suite.

Quelles pages ? Toutes celles de pur accès à la BDD sans récupération du `manifest.json` à postériori, autrement dit, toutes les pages de listing de tutoriels et d'artcles. En vrac (liste non-exhaustive) : 
- La page d’accueil
- La page de listing d'article
- Toutes les pages de listing de tutoriel, que ce soit avec ou sans catégorie
- Les listings correspondants sur les pages d'utilisateurs (articles publié/tutoriels publié/tutoriels en béta)
- Listing personnels (Mes articles/Mes tutoriels)

Bref, tout ces cas ou aller récupérer les JSON correspondant alourdiraient l'affichage (bête exemple, sur la liste de tuto, aller récupérer 100 JSON, c'est 100 accès disques de trop).

J'entrevois deux solution à ça (largement inspirée d'une discution avec @Alex-D  sur IRC, donc venant principalement de lui) : 
- Dupliquer tout les champs en BDD : `title_public` et `title_draft` et ainsi de suite. La plus dure à maintenir mais en fait la plus efficace. "Pire" encore, créer une table ArticleDraft et `TutorielDraft`avec une clé étrangère dans un sens ou dans l'autre.
- Faire en sorte que la BDD ne contiennent que des champ correspondant à la version publique : on optimise les perfos pour les versions publiques (puisque pur accès BDD) et on charge les version _draft_ en allant chercher À CHAQUE FOIS les infos dans le `manifest.json`.  Ce qui demanderait, coté code, de modfier plus de chose que pour l'idée précédente, mais qui serait plus facile à maintenir par la suite, selon moi.
-  Autre chose ?

Bref, grosse issue pas facile du tout.

**Comment by Alex-D** [comment]
La première solution, je l'avais balancé à l'arrache, mais c'est sale et pas du tout dans l'esprit qui est visé à terme : rendre les tuto/articles indépendants de la BDD à travers le repo git qui serait indépendant.

Perso j'avais énoncé et préféré la solution 2 (la BDD ne gère que la version en prod).

**Comment by firm1** [comment]
>  les informations de la BDD sont, quoiqu'il arrive, toujours les informations du dernier draft en date

ça c'est normal.

> Ce qui signifie que si le titre à changé depuis la dernière validation (par exemple, mais pas seulement), sur certaines pages, c'est le titre du draft qui est employé, et pareil pour le sous-titre, la miniature et ainsi de suite

Ce n'est pas vraiment vrai. Le titre, le sous-titre, du tutoriel sont dans le fichier manifest.json. Et il est versionné. Ce qui a donc pour conséquence que le titre, et sous titres que tu vois correspond a chaque fois à la version en cours. Si je prend par exemple le [tuto blender](559) actuellement en ligne, en offline il n'a pas le même titre ni sous titre. C'est bien la preuve que c'est versionné.

Pour ce qui est des licence, elle sont stockée, mais je ne sais pas si c'est la version json qui est affichée ou la version draft.

Les miniature ne sont quant à elle pas stockée dans le json.

Mais globalement il faut se dire que tout ce qui est dans le fichier manifest.json est/sera utilisé.

> Quelles pages ? Toutes celles de pur accès à la BDD sans récupération du manifest.json à postériori, autrement dit, toutes les pages de listing de tutoriels et d'artcles. En vrac (liste non-exhaustive) :
> - La page d’accueil
> - La page de listing d'article
> - Toutes les pages de listing de tutoriel, que ce soit avec ou sans catégorie
> - Les listings correspondants sur les pages d'utilisateurs (articles publié/tutoriels publié/tutoriels en béta)
> - Listing personnels (Mes articles/Mes tutoriels)
- la page d'acceuil affiche ce qu'elle doit afficher, la version versionnée
- la page de listing de tous les articles/tutoriels affiche la mauvaise version (uniquement la version draft) => **c'est un bug**
- Les listings correspondants sur les pages d'utilisateurs => **c'est un bug aussi**
- Listing personnels => c'est normal qu'on affiche que les dernières version (ici les draft)

> Bref, tout ces cas ou aller récupérer les JSON correspondant alourdiraient l'affichage (bête exemple, sur la liste de tuto, aller récupérer 100 JSON, c'est 100 accès disques de trop)

Non non, parce que c'est ce qui est fait aujourd'hui en partie, sauf les parties buggués. Sur la home par exemple, on récupère les 5 json des 5 derniers tutos pour faire l'affichage, et ça ne nous coute que 0.05 s ce bloc (merci usjon). L'idée est d'en faire de même sur le listing des tutoriels (qui sera lui aussi paginé à terme). Allez lire 100 json pour afficher leurs titres/sous titres c'est pas la mort.

> J'entrevois deux solution à ça (largement inspirée d'une discution avec @Alex-D sur IRC, donc venant principalement de lui) : 

La solution qui consiste à dupliquer en base n'est pas une bonne solution. Pourquoi ?
- on charge la base pour rien
- l'idée c'est d'évoluer sur un système séparé en branche (un branche master, une branche validation, une branche publique, une branche beta et plein de PRs)
- l'idée a terme aussi est de ne plus jamais avoir à piquer dans la bd pour lire un tutoriel et rester full git.
- a terme on aimerait avoir des dépots auto suffisant, donc si on commence a trop s'appuyer sur la bd aujourd'hui ça ne fera que double emploi.

Voili, voualou.

**Comment by pierre-24** [comment]
> la page d'acceuil affiche ce qu'elle doit afficher, la version versionnée

Faux, j'ai testé sur les articles et ça passe pas. Vraiment et très sincèrement. 

> si on commence a trop s'appuyer sur la bd aujourd'hui ça ne fera que double emploi.

Je suis d'accord à 200%

>  Sur la home par exemple, on récupère les 5 json des 5 derniers tutos pour faire l'affichage, et ça ne nous coute que 0.05 s ce bloc (merci usjon). L'idée est d'en faire de même sur le listing des tutoriels (qui sera lui aussi paginé à terme). Allez lire 100 json pour afficher leurs titres/sous titres c'est pas la mort.

Je te crois sur parole, si tu le dis. Si tu pense que c'est ce qu'il faut faire, alors je ne peux qu'encourager la personne qui sera responsable à le faire au plus vite, parce que pour le moment, c'est un peu vexant ^^

**Comment by firm1** [comment]
> Faux, j'ai testé sur les articles et ça passe pas. Vraiment et très sincèrement

Elle marche donc sur les tutoriels, mais pas sur les articles de la page d'acceuil. Donc il y'a un bug sur les articles de la page d'acceuil.

> alors je ne peux qu'encourager la personne qui sera responsable à le faire au plus vite

Pour le listings des tutos, on peut s'inspirer de ce qui est fait sur la page d'acceuil. Et ensuite s'inspirer de ça pour les articles (en fait je croyais que je l'avais déjà fait).

Normalement ça ne prend pas du temps, vu que la façon de faire est déjà dans le code.

**Comment by Alex-D** [comment]
Je viens de voir que les dates de création et de publication ne sont pas dans le JSON non plus, donc pas versionnés.

**Comment by firm1** [comment]
Fx'd
