### ISSUE TITLE
Problèmes dans la configuration du certificat SSL

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#1213]
Je viens de passer le site par le SSLCheck de GlobalSign, et voici les résultats: https://sslcheck.globalsign.com/fr/sslcheck?host=zestedesavoir.com#176.31.187.88

On peut noter ici quelques problemes de configuration qui n'ont pas l'air trop compliqués à régler, comme un manque de certains [certificats intermédiares](https://sslcheck.globalsign.com/fr/help/89716664?testTime=1405590801113&ipAddress=176.31.187.88&serverSignature=nginx&dlCertsQueryString=host%3Dzestedesavoir.com%26endpoint_id%3D5D120EE3DC3147E9B47C89E1FF01CE8F84198310%26id%3D5D120EE3DC3147E9B47C89E1FF01CE8F84198310%26id%3DEB4234D098B0AB9FF41B6B08F7CC642EEF0E2C45&isSet=true&severity=1&hmac=97600ec166b07362c45887eadff2c407ff935e0e), ou le fait que l'utilisateur doive renégocier les clés à chaque connexion, et qu'elles sont pas [gardées avec la session](https://sslcheck.globalsign.com/fr/help/0989e998?testTime=1405590801113&ipAddress=176.31.187.88&serverSignature=nginx&isSet=true&severity=2&hmac=cce8bc5bcfbd07447b95c42cba56897bb1c82936).

Voila, si quelqu'un ayant accès à la prod veut bien régler tous ces petits soucis :)

**Comment by SpaceFox** [comment]
Des nouvelles sur cette issue ?

**Comment by Eskimon** [comment]
Ca fait 2 mois sans nouvelles, du nouveau ?

**Comment by Ge0** [comment]
Navré pour l'attente.

J'ai normalement corrigé les deux problèmes soulevés par sandhose. Quelqu'un peut-il relancer les tests et confirmer ?

**Comment by Eskimon** [comment]
Perso je sais pas trop comment ca marche mais voici le lien pour le test : https://sslcheck.globalsign.com/fr/sslcheck?host=zestedesavoir.com#176.31.187.88

**Comment by Ge0** [comment]
Bon, je ne suis pas vraiment au fait en ce qui concerne cette fameuse attaque "BEAST" mais je me charge de la corriger dès que possible.

**Comment by Ge0** [comment]
Encore moi.

Juste pour dire qu'il n'est apparemment pas simple de pousser la sécurité des mécanismes de chiffrement au maximum. Je m'explique : 
- Si j'active les chiffrements forts par défaut, le test m'informe que le serveur est potentiellement vulnérable aux attaques vulnérables de type BEAST. On a quand même un score de "A".
- Si j'active l'algorithme de chiffrement RC4 en priorité, alors nous sommes _a priori_ en sécurité face aux attaques de type BEAST **mais** ledit algorithme n'est pas considéré comme pérenne dans le temps. Cf. https://www.schneier.com/blog/archives/2013/03/new_rc4_attack.html

Il m'a fallu faire un choix et j'ai choisi de ne pas utiliser RC4. Si un connaisseur pouvait me donner son avis, je serais preneur.

**Comment by Eskimon** [comment]
Est-ce pertinent de garder ce ticket ouvert ? Je viens de relancer le test, on obtient une note de 100/100 sur 2 des 4 marqueurs et 90/100 sur les deux restants (et une partie des resolutions est equivalente a "paye un certificat plus cher !")

**Comment by firm1** [comment]
> Est-ce pertinent de garder ce ticket ouvert ?

Pour les raisons que tu cites, non.
