### ISSUE TITLE
[Sidebar] Menu accordeon pour les catégories

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#122]
Comme on peut le voir sur la [page d'accueil suivante](http://preprod.zestedesavoir.com/), les catégories de tuto prennent vraiment beaucoup trop de place en longueur. Il faut beaucoup scroller pour arriver ou on veut.

L'idée est donc de mettre un menu accordeon pour les sous catégories.

**Comment by GerardPaligot** [comment]
On n'avait pas parlé d'un menu accordéon (faisable en 2 lignes de code :-°)
?

**Comment by Alex-D** [comment]
De manière générale, chaque partie de de la sidebar doit pouvoir être rétractable en rajoutant une classe ou autre attribut HTML à l'élément concerné.

**Comment by Alex-D** [comment]
L'accordéon est implémenté, il restera le CSS à faire pour ajouter une flèche, etc. Mais la base est là.

**Comment by SpaceFox** [comment]
Je ne suis pas certain de comprendre : c'est corrigé ou c'est pas corrigé ?
S'il reste des trucs à faire, cette issue a avancé mais n'est pas encore
close.

2014-04-10 9:49 GMT+02:00 DEMODE Alexandre notifications@github.com:

**Comment by Alex-D** [comment]
Le menu fonctionne. C'est pas une histoire de correction, c'est une histoire qu'avant il n'y en avait pas, maintenant il y en a et c'est disponible et expliqué dans le wiki.

Ce que je dis c'est que esthétiquement/ergonomiquement il faudra améliorer, mais en soi c'est utilisable actuellement.

**Comment by SpaceFox** [comment]
OK :)

Le 10 avril 2014 09:53, DEMODE Alexandre notifications@github.com a écrit
:

**Comment by firm1** [comment]
Afin d'avoir un bon suivi des issues, faudrait tout de même garder le workflow suivant (sinon on s'y perd vite).

`Nouvelle Issue -> Branche de correction -> Pull Request -> Merge -> Fermeture de l'issue`.

Cette issue n'a pas reçu de PR ni de merge, donc je ne sais pas si on peut vraiment la considérer comme cloturée.

**Comment by Alex-D** [comment]
Je travail sur la branche intégration. Je ne peux plus faire de request sur la dev car tout y est changé. Donc elle est fermée pour moi. Si ça vous fait plaisir de laisser un truc ouvert qui sera de toute façon mergé dans les jours qui viennent, soit.
