### ISSUE TITLE
Modifier le titre d'un chapitre ne permet plus d'éditer ses extraits

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1225]
Via [Ymox sur le forum](http://zestedesavoir.com/forums/sujet/726/contenu-qui-disparait-a-ledition-dun-extrait/?page=1#p9192) : 

Lorsqu'on change le nom d'un chapitre, le texte des extraits qu'il contient n'est pas conservé et ils repassent blanc quand ont les éditent, alors que le chapitre est affiché correctement. Quand on regarde dans le `manifest.json`, on se rend compte que les chemins pointent encore sur les anciens fichiers `.md`, ce qui n'est pas sencé poser problème, mais qui apparament en pose à l'édition. Bref, mon petit doigt me dit qu'il y a quelque chose à aller chercher dans `edit_extract()` ([dans views.py à la ligne 1843](https://github.com/zestedesavoir/zds-site/blob/master/zds/tutorial/views.py#L1843)).

**Comment by pierre-24** [comment]
MàJ : lorsqu'on regarde un peu ce qui se passe, on se rend compte que Extract.get_text() ([models.py, ligne 887](https://github.com/zestedesavoir/zds-site/blob/master/zds/tutorial/models.py#L887)) va chercher un fichier qui n'exite plus, parce que le slug du chapter est pas bon dans le path qui est employé dans cette fonction. À noter que le problème se produit également quand on modifie le titre de la partie, slug pas bon pour la partie et ça plante aussi. J'en déduit que mettre à jour TOUT LES PATHs du `manifest.json` est une bonne idée, ou bricoler autour de ça.

**Comment by pierre-24** [comment]
MàJ : quand on fait un peu le tour de ce qui se passe, voilà ce qu'on voit.

Dans `view_chapter()` ([views.py à la ligne 1424](https://github.com/zestedesavoir/zds-site/blob/master/zds/tutorial/views.py#L1424)), on remarque que le texte de l'extrait est récupéré via `get_blob()` (définie [là](https://github.com/zestedesavoir/zds-site/blob/master/zds/utils/tutorials.py#L93)) et qui fait très probablement appel aux fonctions de la librairie git (qui est le crétin qui a été écrire `from git import *` ?). À l'inverse, `get_text()` fait du "simple" `open()` → `read()` → `close()`. Si git fonctionne bien comme je pense qu'il fonctionne, voilà la cause du problème --"

**Comment by firm1** [comment]
Fx'd
