### ISSUE TITLE
Archives du tuto contienent tout les anciennes modif's

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1226]
Je ne sais pas ce qui se passe quand on télécharge une archive de son tutoriel, mais il y a plein de choses qui ne devraient pas s'y trouver. Par exemple, ici : 

![screen-1](https://cloud.githubusercontent.com/assets/7889675/3619964/5a9013b4-0dfa-11e4-8bc6-09c33ef0b162.png)

On peut voir que dans l'archive, le dossier concernant l'ancienne partie est dans l'archive alors qu'il n'est plus dans la version du site du tutoriel. La situation est la même pour les tutoriels, comme ont peu le voir sur ce screen : 

![screenshot-un-big-tuto tar](https://cloud.githubusercontent.com/assets/7889675/3619998/8dc47aa4-0dfa-11e4-9dbf-497d77664de5.png)

Quand on renomme les chapitres, le _pk_ reste le même (ce qui est normal) et les dossiers de l'archive sont dupliqués, alors qu'une fois encore, ce n'est pas le cas sur la version du site.

J'en déduis donc que la création de l'archive se fait en prenant TOUT les snapshots du tutos, pour une raison que je ne comprend pas.

**Comment by firm1** [comment]
la seule piste que je vois (à explorer sérieusement) :  Quand on supprime un fichier on le supprime [juste physiquement](https://github.com/zestedesavoir/zds-site/blob/master/zds/tutorial/views.py#L2408) on ne fait aucune action git dessus (track/untrack). idem pour le [changement de titre](https://github.com/zestedesavoir/zds-site/blob/master/zds/tutorial/views.py#L2413).

Il me semble qu'il y'a une action git à faire quand on modifie/supprime un fichier.

Faut-il untracker l'ancien ?

**Comment by pierre-24** [comment]
> Faut-il untracker l'ancien ?

Si c'est comme git, non.

> Il me semble qu'il y'a une action git à faire quand on modifie/supprime un fichier.

Tu me fais rire, parce que ça fait au moins deux issues que je le dis ^^ Par mimétisme de git, oui, il y a surement un truc à faire dans `maj_repo_*()`

**Comment by firm1** [comment]
> Par mimétisme de git, oui, il y a surement un truc à faire dans maj_repo_*()

Ouaip, mais du coup (je m'adresse a ceux qui bosse avec git en ligne de commande) : quand vous supprimer un fichier physiquement de votre dépot, quelles sont les commandes qui vous saississez par la suite avant de committer ?

**Comment by pierre-24** [comment]
`git rm`. Puis `git commit` :)

**Comment by firm1** [comment]
Et lorsque tu renommes un fichier, physiquement.

``` bash
#renommage de mon chapitre
sudo mv 12_mon-chapitre 12_mon-chapitre_modifie

# Quels sont les commandes git qui sont faites ici ?

# Je commit mes changements
git commit -m "rennomage de mon chapitre"
```

**Comment by pierre-24** [comment]
`sudo` ? t'as pas peur, toi ^^ Plus sérieusement, y'a `git mv` bien entendu :)

**Comment by firm1** [comment]
> Plus sérieusement, y'a git mv bien entendu :)

Et dans mon exemple, quelle commande est-ce que tu saisirais exactement  (je dis ça parce que je sais pas hein et la flemme de chercher :p ) ?

**Comment by pierre-24** [comment]
Tu fait pas le mv, tu fais direct `git mv 12_mon-chapitre 12_mon-chapitre_modifie` tu `git add 12_mon-chapitre_modifie` et tu `git commit`. End of the story :)

**Comment by firm1** [comment]
Donc, on sait donc ce qui nous reste à faire pour corriger l'issue.

[Ici](https://github.com/zestedesavoir/zds-site/blob/master/zds/tutorial/views.py#L2408) au lieu de modifier physiquement a coup de `os.rename`, on modifier "gitativement" à coup de `index.move()`.

Et ça fait des chocapics

**Comment by pierre-24** [comment]
Tout les `maj_repo_*()`, en fait, mais oui :)

**Comment by firm1** [comment]
Voila

**Comment by Alex-D** [comment]
> git mv 12_mon-chapitre 12_mon-chapitre_modifie tu git add 12_mon-chapitre_modifie et tu git commit. End of the story :)

Juste pour dire, un `git mv` devrait être suffisant, pas besoin de `git add` il me semble.

**Comment by pierre-24** [comment]
Je prend. Ça devrait pas être monstrueusement long à faire ;)

**Comment by Eskimon** [comment]
Tu avais eu le temps de regarder ou on laisse tomber au profit de ZEP-12 ?

**Comment by pierre-24** [comment]
Objectivement, c'est pas réelement bloquant. C'est frustrant, mais pas réelement bloquant. Donc je la garde en tête, mais ça viendra de toute façon avec la ZEP-12. Autrement dit, je veux bien garder l'assignation.

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
Need Test

**Comment by pierre-24** [comment]
D'après moi et mes quelques tests préliminaires, c'est bon, mais effectivement, QA needed :)
