### ISSUE TITLE
Galerie non renommée si le tuto change de nom

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1227]
Via [mathiasmch, sur le forum](http://zestedesavoir.com/membres/voir/mathiasmch/) : 

> Lorsque l'on modifie le nom d'un tutoriel, celui de sa galerie n'est pas mis à jour. Je ne sais pas si ça peut avoir des conséquences par la suite…

**Comment by gustavi** [comment]
Je peux m'en occuper.

**Comment by pierre-24** [comment]
Je t'en prie. Fait quand même gaffe que @ArnaudCalmettes n'as pas donné de _milestone_ pour cette issue, donc demande son avis avant.

**Comment by gustavi** [comment]
Je suis dessus.

**Comment by pierre-24** [comment]
À fermer.

**Comment by gustavi** [comment]
http://i.imgur.com/GdpZkrX.png
