### ISSUE TITLE
Ajout d'un champ de filtre par tag

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1229]
Lorsque les forums sont un peu rempli, il devient difficile de trouver ce qui nous intéresse vraiment.
L'ajout de filtre par tag (un champ a remplir pour ajouter/supprimer les tags qui nous intéresse serait un plus sympa !)

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis plus d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.
