### ISSUE TITLE
Beaucoup d'espace perdu dans les dropdown

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#123]
Comme le montre le [screen suivant](http://i.imgur.com/z2edUsv.png), on perd beaucoup d'espace dans les dropdowns. Ce qui peut être chiant quand on un petit écran.

**Comment by Alex-D** [comment]
Les dropdowns manquent d'un peu de d'algo, tout simplement ;)

**Comment by GerardPaligot** [comment]
Ca veut dire quoi manquer d'algo ?

**Comment by Alex-D** [comment]
En gros, dans la construction des dropdowns, faut rajouter un peu d'algo pour que ça gère correctement les colonnes, histoire d'avoir quelque chose de bien réparti. Là c'est complètement random et ça part dans tous les sens.

Je m'en chargerais, d'ici là c'est pas gênant.

**Comment by Alex-D** [comment]
Vu ce qu'on a pour l'instant dans ces dropdown, je ne peux pas tester et globalement on ne perd pas de place du tout.

Si le problème réapparaît un jour, on pourra rouvrir, d'ici là je ferme.
