### ISSUE TITLE
Les topics des forums privés sont dans le sitemap

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#1230]
Actuellement, dans le sitemap (http://zestedesavoir.com/sitemap-topics.xml) les topics des forums privés sont répertoriés. 

Il faut les virer, car ils sont privés et aussi parce que Google essaye d'y accéder et qu'il a des erreurs  403 qui sont mauvaises pour nous.

**Comment by Axylium** [comment]
Sachant que @firm1 a réglé le problème, il faudrait penser à fermer ici. :)
