### ISSUE TITLE
Redimensionner les avatars dans les notifications

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#124]
Après [intégration de la home](http://preprod.zestedesavoir.com/), je me rends compte que l'avatar dans la zone de notification est trop grand par rapport à ce qui devrait être.

Il faut une règle css qui dimensionne ces avatars au mieux.

**Comment by Alex-D** [comment]
Fixé dans le commit https://github.com/Taluu/ZesteDeSavoir/commit/7ab051aa26a00158b843f5562a1dce7fc253fc17
