### ISSUE TITLE
Plusieurs « alt » manquent

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#1241]
Via [Girgias](http://zestedesavoir.com/membres/voir/Girgias/) sur le [forum](http://zestedesavoir.com/forums/sujet/742/tag-alt-manquant-sur-les-images/?page=1#p9743)

---

Il reporte que plusieurs "alt" manquent à différent endroit dans le site _(cf. voir ses captures)_

Si quelqu'un pourrait me l'assigner car je la prends et m'en occupe dès maintenant.

**Comment by Alex-D** [comment]
Je viens spawnkill : il n'y a rien à toucher à ce niveau. Les alt sont présents, ils sont vides, c'est donc parfaitement correct.

**Comment by Axylium** [comment]
Pas de soucis !
