### ISSUE TITLE
Dé-réservation d'un tutorial ne marche pas bien

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1243]
Via [Natalya sur le forum](http://zestedesavoir.com/forums/sujet/740/annulation-de-reservation-des-tutoriels-a-valider/#p9717) : 

> Procédure de reproduction : Avec un compte Staff, sur la page http://zestedesavoir.com/tutoriels/validation/ Tenter de dé-réserver un tuto autre que le premier tutoriel réservé de la liste [...]
> Comportement observé : Une petite fenêtre nous demande de confirmer qu'on veut bien supprimer la réservation d'un tuto en indiquant le nom du validateur ayant réservé le premier tuto réservé de la liste. En validant, le premier tuto réservé de la liste est dé-réservé, en lieu et place de celui qu'on souhaitait dé-réserver.

**Comment by gustavi** [comment]
Je suis dessus.

(Ça vient du front.)
