### ISSUE TITLE
Duplication requêtes SQL PR #1239

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1244]
Lorsqu'il y a {{ foo.all|pluralize }}, une deuxième requête identique est crée. Les problèmes viennent de la PR #1239.

https://github.com/zestedesavoir/zds-site/pull/1239#issuecomment-49514439

Je vais corriger ça avec des {% with %}.

**Comment by Alex-D** [comment]
On généraliser à l'issue #1245.
