### ISSUE TITLE
Optimisation générale des requêtes SQL

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1245]
Il faudrait une relecture générale pour évites des duplications et ainsi augmenter le nombre de requêtes SQL.

Simple exemple, dans /mp/id/slug/ on a http://i.imgur.com/J0ZYvVj.png, 4 fois la même requête.

À fixer dans le back et non le front.

**Comment by Alex-D** [comment]
Ca n'est pas aux templates de corriger ça :/

C'est au back d'envoyer les bonnes données avec des jointures et tout qui va bien.

**Comment by gustavi** [comment]
Non mais une partie dans les templates doit être optimisée. On a du code qui fait plusieurs fois la même chose, à corriger avec des {% with %}.

**Comment by firm1** [comment]
Il y'a bien des choses à optimiser des deux cotés (backend et frontend) au niveau des requêtes.

Ceci dit, en modifiant l'un ou l'autre, il faut penser optimisation désormais.

**Comment by Alex-D** [comment]
On optimise pas des requêtes dans le front. Le front ne fait qu'afficher ce que le back envoie.

La seule optimisation acceptable dans le front, c'est du cache de sortie HTML sur des blocs qui ne changent pas beaucoup (genre les dropdown du header, l'accueil, etc).

**Comment by SpaceFox** [comment]
On a encore du travail ici ?

**Comment by GerardPaligot** [comment]
De toute façon, c'est une issue beaucoup trop vague qui pourrait ne jamais se fermer.

**Comment by Eskimon** [comment]
Absolument, comme le dit @GerardPaligot le ticket n'est pas assez précisé pour pouvoir faire une action de résolution. Du coup je ferme au profit de ticket (ceux sur les slow queries) plus pertinent.
