### ISSUE TITLE
Import de tutoriel (.tuto) en zcode : Erreur 500

### ISSUE THREAD

**Issue by sylafrs** [zestedesavoir/zds-site#1249]
Tout est dans le titre.

J'ai essayé avec deux tutoriels un big et un normal.
Je n'ai pas mis de .zip pour les images et ai directement mis le .tuto dans le champ "tutoriel à importer".

La page me renvoie sur une erreur 500 à la validation du formulaire.

**Edit** :
- Si je met un .zip comportant le .tuto dans le premier champ : Erreur 404
- Si je met ce même zip dans le second champs en remettant le .tuto dans le premier : ça marche.
  - En revanche, sauf pour les parties, le zcode n'est pas géré.. mais bon, c'est déjà ça : je vais m'en occuper :p

![Résultat](https://cloud.githubusercontent.com/assets/967253/3637176/b0dbf7ec-0ff8-11e4-8f34-ef2470706e0c.png)

**Comment by Eskimon** [comment]
Donc si j'ai bien suivi, tout se passe bien si tu met les bonnes choses dans les bons champs, mais comme la regle generale "Never Trust User Input" le dit, il faut rajouter des controles sur le champ du formulaire pour le renvoyer si une erreur arrive... ?

**Comment by sylafrs** [comment]
Le problème c'est que les champs ne précisent pas quel type de fichier il faut mettre.

Il faudrait faire deux choses :
- En cas d'erreur : expliquer ce qu'il faut changer (au lieu d'une page 404 ou 500)
- Faire en sorte que les champs (fichiers) n'acceptent que les .tuto / .zip (selon le champ)

**Comment by Axylium** [comment]
> Le problème c'est que les champs ne précisent pas quel type de fichier il faut mettre.

C'est clairement indiquer : 
- **Sélectionnez le tutoriel à importer** : sous-entendu le _.tuto_
- **Fichier zip contenant les images du tutoriel** : le fichier _.zip_

Pour les contrôles sur les champs, je suis d'accord. Je vais essayer de m'en occuper. ;)

**Comment by Alex-D** [comment]
> sous-entendu le .tuto

En fait, c'est un .tuto préparsé qu'il faut renseigner. C'est pas le même format que sur le SdZ. 

Cette page d'import ne sert à rien en réalité. On devrait plutôt virer ce bloc et mettre un lien pour faire une demande aux staff pour assigner le tuto au membre ou alors convertir son tuto et lui assigner.

Car au final, seuls les auteurs qui ont reçu un mail pour leur expliquer le fonctionnement peuvent comprendre le délire.

**Comment by firm1** [comment]
> Cette page d'import ne sert à rien en réalité. On devrait plutôt virer ce
> bloc

Ne surtout pas faire ça.

Elle sert ne sers pas a tout le monde, mais elle sert quand même.
Le 20 juil. 2014 23:10, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
> Elle sert ne sers pas a tout le monde, mais elle sert quand même.

Alors il faut mettre un pavé en expliquant comment faire et à quoi ça sert.

**Comment by Coy0te** [comment]
+1 pour ajouter un gros pavé : 

> Vous êtes l'auteur d'un cours sur le SdZ ? Nous l'avons récupéré pour vous ! Il est disponible hors-ligne et n'attend plus que votre accord pour être publié, il vous suffit d'en faire la demande à un membre du Staff via le forum ou directement par MP.

**Comment by Alex-D** [comment]
Ok je rajoute ça :)

**Comment by Alex-D** [comment]
Voilà, reste plus qu'à @Florianboux à faire un truc joli côté back :)

**Comment by Axylium** [comment]
Ouaip, je vais m'en occupe dès que je rentre chez moi ce soir.

**Comment by Eskimon** [comment]
Du coup @Florianboux , maintenant que ton PC est réparé (il me semble) tu vas pouvoir terminer ce que tu avais commencé ?

**Comment by Axylium** [comment]
Yes ! Je m'y remets dès que je peux, comprenez : demain à la première heure !

**Comment by Eskimon** [comment]
ping @Florianboux ca roule avec la rentrée ? tu as besoin d'aide ?

**Comment by Axylium** [comment]
Nope, c'est un peu chaud avec la reprise des cours.. J'ai un peu de mal à tout gérer je dois l'avouer, donc si quelqu'un veut reprendre pas de soucis ! J'essayerai de m'en occuper ce week-end, si ça n'a pas encore été repris. ;)

**Comment by Eskimon** [comment]
Ca peut bien attendre le weekend ne t'inquiete pas. Mais n'hesite pas a communiquer si tu as besoin d'un repreneur ou d'un coup de main ;)

**Comment by Axylium** [comment]
Bon, si quelqu'un veut reprendre ici, qu'il se fasse une joie ! 

Niveau cours, je suis légèrement surpassé et ils me prennent un temps fou. Donc je n'ai plus trop le temps de coder.

**Comment by Eskimon** [comment]
Faudra d'ailleurs voir ca post-v1.1 vu qu'on pourra aussi faire l'import de tuto zds (et non pas uniquement sdz vous m'suivez ?) . Bref, je veux bien m'en occuper :)

**Comment by Alex-D** [comment]
Je crois bien qu'on a fait le tour de tous les problèmes rencontrés : on a l'import d'archive depuis ZdS et un contrôle des champs avec un texte explicatif pour l'import de tuto depuis l'ex-SdZ.

Bravo à vous :)
