### ISSUE TITLE
Conflit dans le format du markdown

### ISSUE THREAD

**Issue by sylafrs** [zestedesavoir/zds-site#1250]
Il y a un souci avec le markdown lorsque l'on veut insérer une 'touche' dans un 'tableau' étant donné que les deux objets utilisent le caractère |

Edit : non, le problème ne vient pas de là, le tableau crash sans les || de toutes les manières.

**Comment by sylafrs** [comment]
L'erreur n'arrive qu'avec le cell span row

**Comment by sylafrs** [comment]
Arf, en fait j'ai fermé cet 'issue' pour en ouvrir une meilleure qui détaille davantage le problème..
https://github.com/zestedesavoir/zds-site/issues/1251

**Comment by Axylium** [comment]
Évite les doublons, surtout ici.

Tu aurais pu simplement éditer ton premier message ici. ;)

**Comment by Eskimon** [comment]
Bon, je referme pour éviter le doublon avec #1251 mais c'est vrai qu'il faut faire attention à garder GH propre sinon on ne va pas s'y retrouver le jour où l'on fera des recherches...
