### ISSUE TITLE
Cell span row ne fonctionne pas

### ISSUE THREAD

**Issue by sylafrs** [zestedesavoir/zds-site#1251]
Je suis en train de remettre le format dans mon tuto qui provient de la v3 et tente de fusionner des cellules en utilisant la méthode du tuto sur le markdown du site, mais cela ne fonctionne pas :

![sans titre](https://cloud.githubusercontent.com/assets/967253/3637455/e4de6d88-100a-11e4-967c-981b1362b53a.png)

Un autre exemple sur le site : http://zestedesavoir.com/forums/sujet/748/tableaux-la-fusion-de-cellules-verticale-en-fin-de-ligne/

**Comment by sylafrs** [comment]
> Fichier : https://github.com/zestedesavoir/Python-ZMarkdown/blob/master-zds/markdown/extensions/grid_tables.py

**Comment by Axylium** [comment]
Faudrait voir avec celui qui s'occupe du MD du site. (ping @cgabard)

**Comment by Alex-D** [comment]
Du coup, c'est à aller rapporter sur le [repo du parseur markdown](https://github.com/zestedesavoir/Python-ZMarkdown), et fermer cette issue.

**Comment by sylafrs** [comment]
https://github.com/zestedesavoir/Python-ZMarkdown/issues/44
