### ISSUE TITLE
Lecture zen d'un article : les paginateurs de commentaires s'affichent

### ISSUE THREAD

**Issue by jcval** [zestedesavoir/zds-site#1254]
Lors de la lecture d'un **article** en mode zen, les paginateurs des commentaires s'affichent, bien que les commentaires aient été masqués.

Tout fonctionne bien pour la lecture zen d'un tutoriel.

**Comment by Alex-D** [comment]
Doublon avec celle là : https://github.com/zestedesavoir/zds-site/issues/1196 non ?

Ca a été corrigé mais pas mis en production il me semble.
