### ISSUE TITLE
Problème de pluriel sur les +1/-1 de commentaires

### ISSUE THREAD

**Issue by mlorant** [zestedesavoir/zds-site#1256]
Lorsqu'un commentaire à un seul +1, l'infobulle est "1 personnes ont trouvé ce message utile". Un peu petit coup de `pluralize` sur les templates serait utile pour afficher "1 personne a trouvé" plutôt :)

**Comment by DevHugo** [comment]
Y'a un double espace à corriger aussi entre le chiffre et personnes. Même remarque dans les -1 aussi.

**Comment by Alex-D** [comment]
Je m'en charge :)

**Comment by Alex-D** [comment]
A valider dans la #1258
