### ISSUE TITLE
[Ortho] Correction dans le bandeau de Clem'

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#1257]
Il faudrait corriger "a but non lucratif" par "à but non lucratif" dans cette ligne : 
=> https://github.com/zestedesavoir/zds-site/blob/ed304337966a8aac02c6257d15e1a04a7cabb12e/templates/home.html#L56

Il s'agit du bandeau affiché aux non connectés.

**Comment by Alex-D** [comment]
Merci, je corrige ça :)

**Comment by Alex-D** [comment]
A tester sur la #1258
