### ISSUE TITLE
[Edition d'un tutoriel] Aperçu puis envoyer -> "Une nouvelle version a été postée avant que vous ne validiez."

### ISSUE THREAD

**Issue by Ge0** [zestedesavoir/zds-site#1259]
Tout est dans le titre.

Lorsque j'édite une partie d'un tutoriel ( au moyen de cette page http://zestedesavoir.com/tutoriels/editer/extrait/?extrait=XXXX ), si je clique sur Aperçu et ensuite "Valider", j'obtiens le message d'erreur qui suit :+1: 

```
Une nouvelle version a été postée avant que vous ne validiez.
```

et la zone de saisie (textarea) contient la version précédente / sauvegardée du tutoriel.

Il est obligatoire de valider sans passer par la prévisualisation pour ne pas perdre le travail effectué.

**Comment by pierre-24** [comment]
ping @artragis, parce que c'est probablement lié à ta PR. @Ge0 : t'es bien sur la version de _dev_ là ? Parce que la PR implémentant ce comportement est pas encore arrivée en _prod_

**Comment by Ge0** [comment]
C'est en prod que j'ai ce souci.

**Comment by artragis** [comment]
J'ai pas ce problème sur la prod... La version actuelle est Version : v1.0-RC6.1/35e8888.  
Actuellement, quand je change un extrait, je n'ai pas ce problème.
Coécris-tu ton tutoriel?

**Comment by Ge0** [comment]
Non mais nous sommes deux auteurs.

**Comment by artragis** [comment]
C'est pour ça : ton coauteur a posté une version pendant que toi tu éditais.  
Comme on était en freeze et que le module de diff n'était pas totalement près, on a corrigé le bug d'écrasement sans pour autant donner un aperçu du conflit.

Une résolution plus poussé viendra sûrement plus tard, mais elle n'est pas d'actualité.  
Pour l'instant, une seule solution : réécris ta modification. Surtout ne fait pas "précédent" car tu auras toujours le même problème.

**Comment by pierre-24** [comment]
Non, il a raison. Je sais pas ce que cette PR fout là, puisque je suis certain qu'on l'as mergée APRÈS la MEP, mais toujours est-il qu'elle y est. Pour obtenir le comportement que décrit @Ge0 , il "suffit" d'appuyer DEUX FOIS sur "apperçu" à la suite. Je suis certain de mon coup, j'ai testé sur un tutoriel ou j'était tout seul comme auteur :)

**Comment by artragis** [comment]
il y a eu une MEP (RC6.**1**) après ma PR qui n'a juste pas été annoncée sur le site.  
Par contre je dois avouer que je ne comprends pas pourquoi le "aperçu" bug, théoriquement il renvoie l'aperçu **avant** le test. Je verrifierai ça ce soir et je corrigerai le bug. J'avoue que je n'ai pas vérifié le cas du double clic sur aperçu. Et que la QA non plus.

**Comment by pierre-24** [comment]
Non, et comme la QA c'était moi, je suis (au moins) aussi fautif que toi.

**Comment by pierre-24** [comment]
**EDIT:** ça le fait aussi quand on fait une fois "aperçu" puis "envoyer".

**Comment by artragis** [comment]
PR envoyée pour corriger.
