### ISSUE TITLE
Impossible d'éditer un article

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#126]
Il est possible de créer un nouvel article, de le publier et le dépublier, mais il est impossible de l'éditer après coup.

**Comment by firm1** [comment]
Ce bug est tout bidon. L'explication est que c'était prévu de ne pas modifier une version qui est publiée. Sauf que quand on édite, on ne modifie jamais la version elle même. Donc je vais le corriger dès que possible.

**Comment by GerardPaligot** [comment]
Hello, je me charge de cette issue. Par contre, j'ai un peu analysé le code des articles. Il y a quand même beaucoup de bugs. Je vais donc couvrir un peu plus que cette seule issue.

**Comment by GerardPaligot** [comment]
Ca fait depuis hier que je développe pour cette issue et le problème ne me semble pas si anodin (ou "bidon") que ça. Les articles ont un cycle de vie (voire la figure ci-dessous). Les utilisateurs peuvent faire certaines actions en fonction de ces états.

![articlestate](https://f.cloud.github.com/assets/1913901/2195002/7a88c4ac-9895-11e3-969e-9d5b8e587d0f.png)

J'ai rajouté quelques états et selon moi, voici comment nous devrions implémenter cette issue :
- DRAFT : Un utilisateur crée un brouillon qui pourrait devenir un article. Pour le moment, seulement l'auteur de l'article peut l'éditer.
- REREADING : L'utilisateur a fini de poser la structure (voire rien du tout, juste lancer l'idée d'un sujet), il demande la contribution des utilisateurs. A partir de là, tout le monde peut contribuer. A chaque fois qu'un utilisateur contribue, il figure dans les contributeurs.
- PENDING : Les contributeurs soumettent leur article à la validation.
- RESERVED : Etat optionnel mais un validateur veut s'occuper personnellement de la validation de l'article. Il le réserve.
- PUBLISHED : L'article a été accepté. Il est publié sur le site. Il n'est plus éditable par les contributeurs. Seulement les membres du staff peuvent éditer pour l'une ou l'autre faute.

Qu'est-ce que vous en pensez ?

**Comment by GerardPaligot** [comment]
Petite mise à jour du diagramme d'état juste au dessus.

**Comment by cgabard** [comment]
Je pense 2-3 choses : 
- On devrait pouvoir sauter directement l'etat REREADING : Je n'ai pas forcément envie que d'autres contribues.
- Du coup, si il est refusé, dans quel etat revient il ?
- Je trouve dommage qu'on ne puisse pas revenir dans un etat DRAFT/REREADING. Pour un article type "news" je comprend bien, pour un article plus général cela empeche de facilement mettre a jour après publications. Parce que un an après l'article peut toujours etre pertinent avec peu de modifs. Ou si j'écrit une série d'article sur une meme thematique, à la sortie de l'episode 3 je pourrais aimer mettre a jour le 2 pour préciser à la fin "Retrouver la suite ICI + liens", etc.

De manière général je me pose les interogations suivantes : 
- Les articles ne sont pas sur la même base de code (vers. git) que les tutos ?
- Quel est la différence profonde entre un article et un mini tuto mis a part que l'article on veut l'afficher dans le flux d'actu du site ? La différence est sémantique mais le backend ne peut il pas etre identique ?

**Comment by SpaceFox** [comment]
\o/ un diagramme d'états !

Le 18 février 2014 13:15, Christophe Gabard notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
> - On devrait pouvoir sauter directement l'etat REREADING : Je n'ai pas forcément envie que d'autres contribues.

Je trouve ça dommage. L'esprit du site est quand même de rendre le travail collaboratif.

> - Du coup, si il est refusé, dans quel etat revient il ?

Il y a une flèche de PENDING vers REREADING.

> - Je trouve dommage qu'on ne puisse pas revenir dans un etat DRAFT/REREADING. Pour un article type "news" je comprend bien, pour un article plus général cela empeche de facilement mettre a jour après publications. Parce que un an après l'article peut toujours etre pertinent avec peu de modifs. Ou si j'écrit une série d'article sur une meme thematique, à la sortie de l'episode 3 je pourrais aimer mettre a jour le 2 pour préciser à la fin "Retrouver la suite ICI + liens", etc.

Alors il faut se mettre d'accord. Pour moi, des articles n'ont pas une raison d'être édités une fois qu'ils sont publiés. En plus, techniquement, ça demanderait un sous-état pour garder l'état PUBLISHED mais rajouter un sous cycle de vie pour la validation du nouveau contenu. Franchement, en tout cas pour la première version, je trouve que ça complexifie le process pour pas grand chose.

> - Les articles ne sont pas sur la même base de code (vers. git) que les tutos ?

Oui et non. Les articles ont un repo git mais un seul. Ils n'ont pas un repo public et privé.

> - Quel est la différence profonde entre un article et un mini tuto mis a part que l'article on veut l'afficher dans le flux d'actu du site ? La différence est sémantique mais le backend ne peut il pas etre identique ?

Ca c'est aux anciens newsers qu'il faut demander.

> \o/ un diagramme d'états !

Euh, oui. C'est mal ? ^^°

**Comment by geoffreyc** [comment]
2014-02-18 12:32 GMT+00:00 Gerard notifications@github.com:

> Alors il faut se mettre d'accord. Pour moi, des articles n'ont pas une
> raison d'être édités une fois qu'ils sont publiés.

"Alors il faut se mettre d'accord. Pour moi, des articles n'ont pas une
raison d'être édités une fois qu'ils sont publiés." Pourquoi donc?

**Comment by GerardPaligot** [comment]
> "Alors il faut se mettre d'accord. Pour moi, des articles n'ont pas une
> raison d'être édités une fois qu'ils sont publiés." Pourquoi donc?

Parce qu'un article est une news pour moi. Après, si nous nous mettons tous d'accord pour dire qu'un article n'est pas une news et que des contributions peuvent survenir après sa publication, faut me le dire cash. :)

**Comment by SpaceFox** [comment]
Je te le dis cash alors :)

Pour moi un article est plutôt un tuto, seul le but est différent. En
particulier, un article peut être mis à jour (pour corriger une erreur,
pour signaler que la technologie est obsolète, pour le mettre à jour tout
simplement, ...)

Maintenant ce n'est que mon avis personnel sur la question.

**Comment by GerardPaligot** [comment]
Ok. Alors actuellement, les articles ne peuvent pas être édités une fois PUBLISHED et ils n'ont qu'un seul repository git. Il lui faut donc un repo private et un repo public. Si nous optons pour cette architecture, un article devient un mini-tuto.

Ne serait-il pas plus malin d'utiliser les mini-tutos comme article ?

**Comment by SpaceFox** [comment]
> Ne serait-il pas plus malin d'utiliser les mini-tutos comme article ?

De mon point de vue, si, complètement.

**Comment by GerardPaligot** [comment]
Ca c'est vraiment chiant parce que j'ai perdu toute ma journée d'hier sur quelque chose qui ne sert à rien pour finir ... Ca m'apprendra à pas mettre les choses au clair dès le début.

**Comment by SpaceFox** [comment]
Après ce n'est que ma vision des choses, à re-croiser avec celles des
autres !

**Comment by cgabard** [comment]
> Parce qu'un article est une news pour moi.

Je pense que tu touche là le point crutial. Pour moi il y a 3 types semantiques différents : 
1. Les news : Pour informer sur l'actu, Pas grave si elles ne peuvent pas être éditer (on peut imaginer a termes faire afficher automatiquement un bandeau "attention cette news a plus de 6 mois, les infos peuvent etre erronés".) Pour moi elles peuvent obligatoirement passer par le statut relecture communautaire, cela ne me choque pas.
2. Les mini-tutos : pour apprendre un truc, de manière courte. Type tout ce qui était appelé comme tel sur feu-sdz. Ils doivent suivre le workflow des tutos classiques
3. Les articles : Pour moi, un peu entre les deux. Je les imagines tels que des articles académiques. Pour moi ils doivent pouvoir suivre le workflows des tutos MAIS pouvoir etre injecté (à la première publication ?) dans le flux de news.

Dans cette dernière catégorie je mettrais par exemple [cet article de nohar](http://progdupeu.pl/articles/34/dropbox-a-des-fuites) qui n'est pour moi pas vraiment une news, ni vraiment un tutos. Cela serait pareil si je rédigeais un article sur un point donnée de Vision par Ordinateur (ex: Comment reconnaitre les visages dans une photo ?). Ce n'est pas une news a proprement parlé, pas vraiment un tuto mais dans tous les cas domage de ne pas les faire passer par le flux d'actu.

Mais ce n'est que mon point de vue.

**Comment by SpaceFox** [comment]
100% d'accord avec Christophe, qui a pris le temps de détailler (merci à
lui, que la bière coule à flots dans sa bouche en remerciements).

Le 18 février 2014 13:56, Christophe Gabard notifications@github.com a
écrit :

**Comment by cgabard** [comment]
Après il est peut etre un peu tard et/ou compliqué d'introduire maintenant ces 3 sémantiques différentes. Peut etre que le plus simple est de faire choir la sémantique d'article dans l'une des deux autres.

**Comment by firm1** [comment]
Ah j'arrive peut-être après la bataille (ou pendant). Mais je préfère signaler qu'il y'a un gros malentendu dans cette discussion. Je n'ai pas le temps de plus détailler tout de suite, je le ferais un peu plus tard. Mais en attendant, éviter de faire travailler vos cerveaux sur cette discussion svp.

**Comment by cgabard** [comment]
@firm1 : Ok on attend ton point de vue mais on est tous partit de cette phrase : "Je vais donc couvrir un peu plus que cette seule issue." 

En gros il a ouvert la discussion à plus que le prob des articles en voulant refactoriser le système completement, on partage nos avis sur la question donc.

**Comment by GerardPaligot** [comment]
> 1. Les articles : Pour moi, un peu entre les deux. Je les imagines tels que des articles académiques. Pour moi ils doivent pouvoir suivre le workflows des tutos MAIS pouvoir etre injecté (à la première publication ?) dans le flux de news.

L'utilisation est différente mais son implémentation est strictement identique aux mini-tutoriels. Est-ce qu'il vaut mieux une duplication de code ou un moyen pour identifier un mini-tuto comme un article ou un mini-tuto.

> Ah j'arrive peut-être après la bataille (ou pendant). Mais je préfère signaler qu'il y'a un gros malentendu dans cette discussion. Je n'ai pas le temps de plus détailler tout de suite, je le ferais un peu plus tard. Mais en attendant, éviter de faire travailler vos cerveaux sur cette discussion svp.

Oui, il y aurait de quoi parler. Le module article est vraiment bugué. J'ai passé toute ma journée d'hier de bug fixe en bug fixe ...

**Comment by firm1** [comment]
Pour refactoriser, il faut d'abord comprendre exactement comment ça marche aujourd'hui.

> Les articles ont un cycle de vie (voire la figure ci-dessous). Les utilisateurs peuvent faire certaines actions en fonction de ces états.

Je n'ai pas compris si le state diagram c'est le système que tu proposes, ou c'est ce que tu penses être la façon de fonctionner aujourd'hui.
Dans tous les cas, un article est versionné, et du coup le diagramme d'état n'est pas la meilleure manière de représenter son cycle de vie étant donné qu'une instance d'article (l'objet qui est persisté en base) peut avoir au même moment plusieurs état (car celu-ci à plusieurs versions).

> Oui et non. Les articles ont un repo git mais un seul. Ils n'ont pas un repo public et privé.

Il y'a une petite astuce de ce coté, les articles et tutos coté repo fonctionnent pareils. Il n'y a qu'un seul repo (privé) pour chacun, c'est juste que les tutos public sont dans un dossier à part (non versionné) et les articles publics (étant donné que c'est juste un fichier .html) sont dans le même dossier que la version privée. Mais la version public n'est pas versionnée elle.

En gros le schéma ci-dessous montre ce qui se passe vraiment lorsqu'on fait des actions sur un article et donne une idée du workflow actuel.

![](http://i.imgur.com/RzfHAFl.png)

> Le module article est vraiment bugué. J'ai passé toute ma journée d'hier de bug fixe en bug fixe

ça c'est la magie de git.

**Comment by cgabard** [comment]
Ha je ne parle pas du tout d'implementation là. Evidement vaut mieux éviter les duplications de codes. Je parle vraiment coté utilisateur. Si ça peut etre réglé en rajoutant un flag "Article" sur un mini tuto qui le modifie comme ça nous arange dans le wrkflow, moi ça me va.

**Comment by GerardPaligot** [comment]
> Je n'ai pas compris si le state diagram c'est le système que tu proposes, ou c'est ce que tu penses être la façon de fonctionner aujourd'hui.

C'est ce que je propose. La solution actuellement mise en oeuvre sur la branche dev ou master me semble vraiment pas souple.

> Dans tous les cas, un article est versionné, et du coup le diagramme d'état n'est pas la meilleure manière de représenter son cycle de vie étant donné qu'une instance d'article (l'objet qui est persisté en base) peut avoir au même moment plusieurs état (car celu-ci à plusieurs versions).

Ah bon ? Comment c'est possible ? La version enregistrée pour sha_public, sha_draft et sha_validation sont utilisées par git pour afficher une version correspondante du contenu de l'article ? Si oui, alors ça peut être intéressant et ce ne sont plus des états. Si non, alors il n'y a aucune raison d'avoir plusieurs états.

> Il y'a une petite astuce de ce coté, les articles et tutos coté repo fonctionnent pareils. Il n'y a qu'un seul repo (privé) pour chacun, c'est juste que les tutos public sont dans un dossier à part (non versionné) et les articles publics (étant donné que c'est juste un fichier .html) sont dans le même dossier que la version privée. Mais la version public n'est pas versionnée elle.

C'est bien ce dont j'avais peur. Du coup, pour les articles, tu mélanges les deux et la version .md peut être différente de la version .html. Je trouve ça vraiment pas beau comme choix de conception.

> En gros le schéma ci-dessous montre ce qui se passe vraiment lorsqu'on fait des actions sur un article et donne une idée du workflow actuel.

L'image est vraiment issue de manipulations sur les articles ? Il y a une sha_beta qui n'existe pas dans son modèle de données.

> ça c'est la magie de git.

Comment ça ?

**Comment by GerardPaligot** [comment]
> Ha je ne parle pas du tout d'implementation là. Evidement vaut mieux éviter les duplications de codes. Je parle vraiment coté utilisateur. Si ça peut etre réglé en rajoutant un flag "Article" sur un mini tuto qui le modifie comme ça nous arange dans le wrkflow, moi ça me va.

Si on supporte tes 3 sémantiques, le flag ne convient malheureusement plus.

**Comment by cgabard** [comment]
Je suis un peu paumé de toute façon avec ce qu'il y a actuellement

**Comment by firm1** [comment]
> Ah bon ? Comment c'est possible ? La version enregistrée pour sha_public, sha_draft et sha_validation sont utilisées par git pour afficher une version correspondante du contenu de l'article ?

Dans la base, on enregistre que les pointeurs (sha) des différentes versions (beta, draft, public, etc.). Etant donné qu'avec un sha1 tu retrouves dans un repo git l'état de l'article correspondant, le système va donc (en fonction de tes droits et de ta demande) te délivrer la bonne version (draft, beta, validation, public) de ton article. ça te permet en gros de continuer sur ton tuto pendant qu'une partie est en validation. Ou encore de continuer la rédaction pendant qu'une version précise est en beta.

> C'est bien ce dont j'avais peur. Du coup, pour les articles, tu mélanges les deux et la version .md peut être différente de la version .html. 

Non justement. le fichier .md que tu vois dans le répertoire c'est le dernier fichier en cours. Mais sauf qu'ici ce fichier à un passé, et l'identifiant de chaque instant de son passé est le sha1.
Le fichier .html qu'on peut aussi nommer .public.html, n'est au final que le "cache" de la version désigné comme publique. On peut aussi créer un dossier à part comme on a fait avec les tutos, mais je ne trouve pas ça forcément pertinent d'en faire un dossier uniquement pour stocker un seul fichier html par article.

> L'image est vraiment issue de manipulations sur les articles ? Il y a une sha_beta qui n'existe pas dans son modèle de données.

Ah la sha_beta je crois qu'elle n'est présente que dans les tutos, oublie là pour les articles ça n'a pas de sens.

> Comment ça ?

Bah parce qu'en regardant de plus près, tu verras que j'ai pas mal patché la lib gitpython pour résoudre certains trucs.

**Comment by GerardPaligot** [comment]
> Je suis un peu paumé de toute façon avec ce qu'il y a actuellement

Le problème c'est que tout le monde est un peu paumé excepté firm1. Je regrette vraiment le manque de documentation.

@firm1 : Pour ce qui concerne le versionning avec sha, j'ai capté le mécanisme. Je reviens sur le problème de documentation que je soulève dans ma réponse à Christophe.

> Bah parce qu'en regardant de plus près, tu verras que j'ai pas mal patché la lib gitpython pour résoudre certains trucs.

Je peux te donner des exemples précis si tu veux mais tout n'est pas lié à l'utilisation de git.

Désolé, je critique pas mal depuis quelques postes sur cette issue mais travailler jusqu'à 2h du matin toute la journée d'hier pour au final me dire que c'est inutile parce qu'il n'y a eu aucune analyse à la base et aucune documentation sur l'implémentation actuelle, ça fait un peu chier quand même.

**Comment by cgabard** [comment]
C'est peut etre mes commentaires qui t'on perturbé... Je ne suis pas surs que rajouter cette sémantique d'article, qui aurait dut etre discuté plus tôt. J'aurais put y penser plus tot. Et on peut s'en sortir sans. Par exemple en faisant des mini-tuto, rangé dans une catégorie Article. Pour les annoncer, on peut très bien faire une mini news dédié systématiquement a la main avec le résumé. 

Changer tout le système actuel ne me semble pas le plus pertinent aujourd'hui, on devrait attendre une v2 pour ça je pense. Car en soit, moi perso je découplerais totalement les 2 (site & gestion des tutos) avec ces derniers implémentés avec des hooks git plutot que de devoir faire tant de manips douteuses depuis git-python. Un tel système bien fait permetrait, entre autre, d'ouvrir l'accès en ssh aux auteurs, le site ne serait qu'un front end pour ça. Et ça découplerais les rôles et les projets, on aurait d'un coté le code de "zds, le site" et de l'autre un code d'un système de publication basé sur git. Ce qui faciliterai son utilisation ailleurs que sur le site.

Mais ça, ça demande d'y reflechir plus profondément et de faire un vrai travail de conception, qu'on pourrat faire avec les retours de la v1.
Donc oublie un peu tout ce que j'ai dit, on se debrouillera très bien avec les mini tutos et les articles types news que tu as corrigés.

**Comment by GerardPaligot** [comment]
Je suis d'accord avec ton poste. Pour moi, dans un premier temps, il faut quand même aller au plus simple. Je me pose simplement toujours la question sur les similarités entre les mini-tutos et les articles. Pour ce point, j'aimerais l'avis de firm1. :)

> Changer tout le système actuel ne me semble pas le plus pertinent aujourd'hui, on devrait attendre une v2 pour ça je pense. Car en soit, moi perso je découplerais totalement les 2 (site & gestion des tutos) avec ces derniers implémentés avec des hooks git plutot que de devoir faire tant de manips douteuses depuis git-python. Un tel système bien fait permetrait, entre autre, d'ouvrir l'accès en ssh aux auteurs, le site ne serait qu'un front end pour ça. Et ça découplerais les rôles et les projets, on aurait d'un coté le code de "zds, le site" et de l'autre un code d'un système de publication basé sur git. Ce qui faciliterai son utilisation ailleurs que sur le site.

C'est une idée vraiment sympa. Très CLAIRE. :)

> C'est peut etre mes commentaires qui t'on perturbé...

Je ne suis pas réellement perturbé. Je n'aime simplement pas bosser pour rien (comme personne). Je n'ai pas l'habitude de ce genre de gestion de projets. Je préfère des trucs plus réfléchis à la base. Mais passons. :)

**Comment by cgabard** [comment]
Je pense qu'on est tous peu satisfait de la gestion du projet, on paye l'absence de chef de projet. Il va vraiment falloir y réfléchir une fois la v1 publié

**Comment by GerardPaligot** [comment]
Ce pull request devrait résoudre cette issue : https://github.com/Taluu/ZesteDeSavoir/pull/163

**Comment by GerardPaligot** [comment]
Bug corrigé dans la PR #163. Je ferme.
