### ISSUE TITLE
Captcha à l'inscription

### ISSUE THREAD

**Issue by zopieux** [zestedesavoir/zds-site#1262]
Mieux vaux prévenir que guérir. Il me semble crucial de munir la page d'inscription d'un _captcha_, même si l'on sait combien c'est énervant.

**Comment by Eskimon** [comment]
Est-ce vraiment nécessaire (vrai question) ? On filtre deja les emails poubelles pour nous prevenir de pas mal de bot...

**Comment by gustavi** [comment]
On peut rajouter une question assez simple type addition/multiplication.

Sinon Django-Simple-Captcha est assez bien foutu et devrait faire l'affaire https://github.com/mbi/django-simple-captcha .

**Comment by Eskimon** [comment]
A mon avis ca vaut largement une discussion avant de lancer du développement...

Je pense qu'un sujet dans la zone dev du site serait le bienvenu (peut-etre pas sous forme de zep non plus, mais au moins pour en discuter plus ouvertement)

**Comment by Alex-D** [comment]
On avait déjà discuté il y a quelques mois de tout ça et on avait déduis qu'on souhaitait une page d'inscription la plus simple possible : le minimum de champs.

Pour les bots, je pense qu'il faudrait attendre de voir. Globalement, avec la blacklist de noms de domaine d'email, ça devrait déjà bloquer beaucoup de bots.

**Comment by zopieux** [comment]
> il faudrait attendre de voir

C'est pour ce genre de réaction que j'ai commencé mon message par « mieux prévenir que guérir. »

**Comment by Eskimon** [comment]
Je vous propose de continuer la question sur le site lui-même, étant donne que c'est un choix plus philosophique que technique http://zestedesavoir.com/forums/sujet/871/captcha-or-not-captcha/

**Comment by gustavi** [comment]
UP ici ! On fait quoi ? L'idée serait d'avoir un système prêt à être utilisé mais activable seulement si une option dans le `settings.py` est cochée.

Ça permettrai le jour où on commence à se manger du SPAM : 
- De ne pas avoir à développer ça dans l'urgence (et donc sûrement pas très proprement) ;
- De pouvoir l'activer sans faire un hotfix.

**Comment by SpaceFox** [comment]
Ce sera _toujours_ une bonne idée ici, si quelqu'un est motivé…

**Comment by Eskimon** [comment]
Bon du coup j'ai fait la PR avec NoCaptcha et un paramètre dans le settings.py pour activer ou non le module.

**Comment by GerardPaligot** [comment]
Merci @Eskimon.
