### ISSUE TITLE
Possibilité de suivre un tag

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1264]
Il serait bien d'ajouter un suivi comme pour un topic mais pour les tags.

Ils seraient listés à la manière des topics dans la colonne de gauche.

**Comment by Eskimon** [comment]
C'est pas un peu pareil que ca : https://github.com/zestedesavoir/zds-site/issues/1229 (et auquel cas on pourrait centraliser sur un seul ticket ?)

**Comment by gustavi** [comment]
Pourquoi pas, bien que ce ne soit pas vraiment la même chose.

**Comment by Taluu** [comment]
Perso je trouve que ça n'a strictement rien à voir avec ce ticket. On parle de deux choses : d'un coté un **filtre** des tags, et l'autre le **suivi** d'un tag

**Comment by lthms** [comment]
Je suis parfaitement d'accord avec cette suggestion. Mais dans ce cas, il faudrait peut-être essayer d'orienter le choix des tags ? Actuellement, rien n'empêche d'avoir deux tags Ocaml et Caml qui cohabitent, et c'est dommage si on veut mettre en place un suivi, non ?

**Comment by gustavi** [comment]
J'ai envie de dire que OCaml != Caml. Ça fait 2 tags, qui ne sont pas les mêmes. Je pense qu'il ne faut pas les "fusionner" ou les "regrouper".

On a fait le choix de limiter le nombre de tags suivis à 20 pour le moment pour des soucis de performance (nombre de requêtes SQL). Qu'en pensez vous ? (On va optimisez ensuite mais ce n'est pas la priorité pour le moment, on augmentera cette limite plus tard). Peut être stocker cette valeur dans le _settings.py_, ce serait plus propre et plus flexible.

**Comment by geoffroyw** [comment]
On peut avoir deux tags JS et Javascript qui cohabitent. Et dans ce cas, ce sont strictement les mêmes.

**Comment by Alex-D** [comment]
À part que : 

Comment on fait pour faire comprendre à un ordinateur que deux choses sont les mêmes si "JS" != "JavaScript" pour lui ?

Faut établir un dictionnaire des synonymes. Qui a envie d'en faire un ? Personne.

**Comment by Situphen** [comment]
Ce sera résolu avec la ZEP 24 sur les notifications (faudra penser à le fermer lors du merge de la PR).

Une question que se demandait @ChantyTaguan est : est-ce qu'on prend en compte la casse des caractères ? Est-ce que "python" est pareil que "Python" ?

Lié à https://github.com/ChantyTaguan/zds-site/issues/3

**Comment by SpaceFox** [comment]
Plusieurs mois après : vous avez fait un choix @Situphen ?

**Comment by GerardPaligot** [comment]
Plus personne ne dev la ZEP-24.

**Comment by SpaceFox** [comment]
:(

**Comment by GerardPaligot** [comment]
Ni @ChantyTaguan, ni moi ne développons pour ZdS et @Situphen a autre chose à faire pour le moment.

**Comment by SpaceFox** [comment]
Vous savez si vous y reviendrez dans un futur prévisible ?

**Comment by GerardPaligot** [comment]
Pas la moindre. Pour ma part, je ne suis même pas certain de développer l'API des forums, alors celle-ci.

**Comment by GerardPaligot** [comment]
Je m'assigne cette issue puisque mes contributions pour zds ont repries. Cela rentre dans le cadre de la ZEP-24.

**Comment by FanJiyong** [comment]
Petit Up sur cette fonctionnalité.

Pensez-vous qu'il est possible d'ajouter que le site un système d'aide à la complétion basé sur les tag existant ?

**Comment by pierre-24** [comment]
> Pensez-vous qu'il est possible d'ajouter que le site un système d'aide à la complétion basé sur les tag existant ?

C'est déjà le cas dans la prochaine version, [voir bêta](https://beta.zestedesavoir.com/forums/sujet/nouveau/?forum=2) :)

**Comment by ChantyTaguan** [comment]
Coucou,

J'essaye de reprendre mes contributions, et quoi de mieux que la ZEP-24 pour faire ça ? Je suis donc en train de développer cette fonctionnalité. Maintenant que l'auto-complétion sur les tags a été implémentée, elle a encore plus de sens donc let's go !
