### ISSUE TITLE
Erreur 500 : ce n'est pas aux visiteurs de reporter les problèmes

### ISSUE THREAD

**Issue by zopieux** [zestedesavoir/zds-site#1265]
La page d'erreur 500, sur laquelle je tombe hélas assez souvent, indique actuellement :

> Si vous voyez cette page, c'est que vous avez trouvé un bug. Merci de rapporter cette erreur en expliquant comment vous avez procédé pour tomber sur cette page.

Or, si Django est capable de dire qu'il a crashé, vous avez les logs et vous pouvez être prévenus automatiquement (avec l'URL exacte et la traceback complète, bien plus utile qu'un imprécis « j'ai cliqué là et j'utilise tel navigateur » — entre nous, vous avez déjà vu un bug de backend être causé par une version de navigateur ?).

Merci donc de **mettre en place un système de logging approprié, avec alertes**. Dans l'idéal, les rapports devraient être publics une fois nettoyés de toute information confidentielle.

Ce bug est partiellement lié à #1028.

**Comment by firm1** [comment]
> Merci donc de mettre en place un système de logging approprié, avec alertes.

Il y'a bien évidemment un système de logging actuellement qui écrit dans des fichiers de logs sur le serveur. Pour les alertes, ça peut très rapidement polluer une boite mail si on a un gros bug, mais en effet ça serait une bonne idée.

Mais c'est souvent plus rapide/pratique si un utilisateur vient nous dire comment il en est arrivé à trouver l'erreur.

**Comment by firm1** [comment]
ça c'est fait.
