### ISSUE TITLE
Erreur dans la modification d'un extrait

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1266]
Via [dosmpm sur le forum](http://zestedesavoir.com/forums/sujet/799/probleme-dedition-dextraits/?page=1#p10764) : 

> L'édition d'un extrait édite effectivement l'extrait, mais le texte de base est celui du premier extrait. Quelque soit l'extrait qu'on edite, on a donc la sensation d'éditer le premier extrait.

Ajout perso : le bug n'advient que sur les mini-tutos.

**Comment by firm1** [comment]
En validation

**Comment by firm1** [comment]
Fx'd
