### ISSUE TITLE
Creer des branches sur un tuto/article

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#127]
Actuellement, dans un tuto, lorsqu'on créer/modifie un tuto/article, on écrit dans un fichier versionné par git sur la branche **master** du tuto/article.

Le fait est qu'on ne peut pas encore travailler sur plusieurs branches différentes, pour les merger plus tard dans la branche principale.

L'idée est donc de : 
- Enlever toute dépendance entre les tutos/parties/chapitres/extraits et leurs équivalents en base de donnée (se baser uniquement sur le manifest).
- Donner la possibilité aux utilisateurs de créer une branche
- Donner la possibilité de comparer et de faire une PR sur une autre branche.
- Donner la possibilité de merger (et/ou résoudre des conflits de merge) d'une branche à une autre.

**Comment by cgabard** [comment]
Ce ticket est prit en charge par la zep 08, on a aucun interet a garder ce ticket ouvert je pense. Ce n'est qu'une sous-partie de la zep 08.

**Comment by firm1** [comment]
Pas faux, je ferme aussi.

**Comment by Eskimon** [comment]
Lien vers la ZEP : http://zestedesavoir.com/forums/sujet/724/zep-08-utilisation-de-git-pour-gerer-les-tutos-et-articles/
