### ISSUE TITLE
Lien "X Réactions" d'un article sur la home

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#1273]
Via [zyhou sur le forum](http://zestedesavoir.com/forums/sujet/809/acceder-directement-au-commentaire-des-articles-a-partir-de-la-home/?page=1#p10955)

---

Les commentaires des articles ne sont pas accessible sur la page d'accueil du site. Sûrement dû à un problème de lien !

**Comment by Alex-D** [comment]
Pensant que c'était du au front, j'ai cherché, c'est en fait du au back et plus précisément à la PR #1261 qui a retiré la visibilité d'un objet qui était récupérable via _get_last_reaction_. 

Reste plus qu'à merger.

**Comment by firm1** [comment]
Je n'ai pas encore pu tester mais d'après le code que j'ai lu de correction, le lien des réactions va renvoyé vers le dernier message et non le dernier **message lu** par le membre.

Il faut donc corriger ce point.

**Comment by Alex-D** [comment]
Il manque encore une méthode renvoyée vers les templates alors, c'est quelle méthode qui permet de récupérer ça ?

**Comment by firm1** [comment]
J'ai pas les moyens de farfouiller le code là, mais c'est un truc dans le style `get_last_read_réaction()`
