### ISSUE TITLE
Problèmes de versionning

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1281]
Reproduire le bug est assez simple : 
- Créer un tuto, nommé "titre-1" et donc la description est "description-1"
- Passer le tutoriel en bêta
- Éditer le tuto, changer le titre pour "titre-2" et pour "description-2"
- Bien entendu, lorsqu'on visite la bêta, le titre et la description ne sont pas bonne

Le problème, il est simple ; une fois encore, c'est le flou artistique entre ce qui récupéré dans le `manifest.JSON` et ce qui vient de la base. Le titre et la description viennent de la base, c'est bien entendu ceux là qui passent au front et pas ceux du JSON. Et cette fois, pas de correction à la `self.title = mandata['title']` dans `view_tutorial()` qui ne feront que reporter le problème jusqu'au moment ou on décidera de versionner autre chose.

Il FAUT réfléchir plus intelligemment à des fonctions qui récupèrent les infos du JSON et vont mettre à jour les infos convenablement DANS LES MODÈLES, et pas jouer avec `load_json_from_public()` et `load_dic()`, qui font que ressortir des dicos qui sont la moitié du temps mal employés. Comme ça, on arrête de manipuler ces dicos et on bosse direct avec les objets, on gagne en factorisation et en facilité de lecture/debugging et on reporte le code sur les modèles, ou ça doit être (dixit MVC).

ping à @firm1 que j'avais prévenu sur #1212 que ça allait arriver.

**Comment by firm1** [comment]
Je me désasigne d'ici. Je reprendrais quand j'aurai le temps si quelqu'un ne l'a pas fait encore.

**Comment by firm1** [comment]
Et je pense que cette issue devrait rentrer dans la milestone v1 car son titre devrait être "Problème de versionning".

Ce qu'on voit dans les historique des tutoriels ne correspond pas toujours à la réalité

**Comment by pierre-24** [comment]
J'approuve le changement de milestone le cas échéant.

**Comment by pierre-24** [comment]
Je reprend. J'ai une PR quasiment prète (#1280) et je sais ou est le bug.

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé
