### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1282]
Quelques améliorations sympatiques pour les RSS : 
- Des RSS par sujet (ça se fait par exemple sur les forums de Wordpress) ;
- Des RSS pour ses notifications (je vous invite à lire cette issue : https://github.com/zestedesavoir/zds-site/issues/495) ;
- Des RSS par tutoriel (modifications, commentaires).

(RSS et ATOM)

_Mis à jour le 19 novembre 2014_

**Comment by pierre-24** [comment]
Je pense que ça s'intégrerai magnifiquement bien avec une éventuelle API qui a exactement les mêmes buts. Après, ça repousserai la _feature_ a dans des siècles.

**Comment by Alex-D** [comment]
Une API ?

Comme je l'ai dit sur le topic API, ce qu'il manque, ce sont des models bien faits, de telle sorte que sortir un RSS ou un JSON de "tous les sujets du forum FFF" ça se fait en un appel de fonction.

Et si c'est déjà le cas actuellement, alors il n'y a qu'à.

**Comment by Eskimon** [comment]
Mergé !!

**Comment by pierre-24** [comment]
.. Pas tout à fait, on a pas tenu compte des "améliorations sympas" de gustavi. Bon, le RSS pour les notifs, avec l'extention navigateur, c'est un peu _useless_. Par contre, j'aimerai qu'on garde en tête l'idée du RSS pour les modifs de tutos et leur commentaires ... Ça peut être sympa.

**Comment by Eskimon** [comment]
Je réouvre alors pour faire une deuxieme PR plus tard ;)

**Comment by gustavi** [comment]
Ça semble fixé.

**Comment by firm1** [comment]
Pas fixé totalement. J'avais volontairement mis de coté l'implémentation des "Améliorations Sympa" vu que ça n'a pas été discutté/validé quelque part.

Mais il faut du coup soit ouvrir une discussion dessus sur le forum, soit en parler ici, car en l'état l'issue n'est pas terminée.

**Comment by SpaceFox** [comment]
On en est où ici ?

**Comment by pierre-24** [comment]
Rien n'as changé :)

**Comment by gustavi** [comment]
Est-ce que vous voulez que je mette en place les 3 choses proposées ?

**Comment by pierre-24** [comment]
oui :)

**Comment by GerardPaligot** [comment]
@gustavi Tu as avancé sur cette issue ? :)

**Comment by gustavi** [comment]
J'attends le merge de la ZEP-24 et je reprends ça ! Si ça tarde je ferai ça en 2 PR. N'hésite pas à me ping si j'oublie ça ;)
