### ISSUE TITLE
Coloration syntaxique multiple langage

### ISSUE THREAD

**Issue by YoruNoHikage** [zestedesavoir/zds-site#1287]
Je ne sais pas comment fonctionne la coloration de code mais je me retrouve embêté car je souhaiterai colorer une requête HTTP en même temps que du code JSON.

Highlight.js le fait à ce que je vois, donc c'est possible.
On peut imaginer un système comme ça si ça n'est pas déjà existant d'une autre manière : 

``````
```http+json
HTTP/1.1 200 OK
...

{
    "foo" : "bar"
}
```
``````

**Comment by Alex-D** [comment]
Ping @cgabard je pense :)

**Comment by cgabard** [comment]
On utilise pygment et c'est lui qui gère ça. En l'occurence certains sont déjà autorisés (`html+php`, `html+django`, etc.). le `http` est supporté, le `json` est supporté mais pas les deux ensembles. Tous ceux dispo [sont listés ici](http://pygments.org/docs/lexers/).

Pour moi ce n'est pas de notre ressort directement. On a deux solutions : 
- quelqu'un va ajouter ce support dans pygments (et donc on peut fermer le ticket car ça ne nous regarde pas)
- on change de système de coloration pour un qui gère ça (pour Highlight.js par ex mais qui fait la coloration coté client et necessite de mettre a jour le front et markdown et donc on doit laisser le ticket ouvert)

**Comment by YoruNoHikage** [comment]
J'ai fouillé un peu dans le code du HttpLexer et j'ai trouvé !
**Il parse le contenu en fonction du Content-Type précisé dans les headers de la requête.**

Il n'y a donc pas besoin de faire de modifications mais il serait bon de le préciser dans l'aide au markdown ou ailleurs. :)

Je ferme l'issue pour le coup !

**Comment by cgabard** [comment]
Chouette. En fait il faudrait faire un guide avancé. Il y a pleins de
détails de ce genre qui intéresseront les habitués mais pas la majorité des
utilisateurs. Il vaudrait donc mieux faire deux version : les trucs
basiques + tous le reste

**Comment by YoruNoHikage** [comment]
Un genre de fourre-tout avec des astuces propres à un truc ? 
C'est bien mais quand on en a beaucoup. :/

**Comment by cgabard** [comment]
Bas sur le markdown il y en a plein. Le tuto actuel est bien chargé.
