### ISSUE TITLE
Impossible de mettre à jour la version en validation d'un article

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1289]
Autant dans les tutoriels, l'auteur peut mettre à jour la version en validation, autant ça n'est pas possible dans les articles. Il faudrait donc offrir cette possibilité.

**Comment by pierre-24** [comment]
EDIT : @Alex-D  va l'intégrer dans #1275

**Comment by Alex-D** [comment]
Voilà qui est fait. Je ferme.
