### ISSUE TITLE
Adapter la nouvelle syntaxe markdown des auteurs de citations

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#129]
La syntaxe markdown concernant les auteurs d'une citation [a évoluée](https://github.com/Taluu/ZesteDeSavoir/pull/118). Désormais il faut faire ainsi :

```
  > Ma super citation
    : [nom de la source](url)
```

ou

```
  > Ma super citation
    : nom de la source
```

Il faudra donc faire évoluer le back-end en conséquence, qui, pour l'instant, se contente d'écrire : 

```
**auteur a écrit**
> blabla
```

Il faudra aussi corriger le parseur .tuto -> markdown qui est resté sur la syntaxe en cours de discussions qui est la suivante : 

```
  =[nom de la source]
  > Ma super citation
```

Il faudra finalement que le front-end adapte cette modification en stylisant un peu mieux tout ça.

**Comment by cgabard** [comment]
La syntaxe peut aussi etre : 

```
> Ma citation
Source : nom de la source
```

ou avec le liens : 

```
> Ma citation
Source : [nom de la source](url)
```

Perso ce serait bien d'utiliser celle-ci en back, elle est plus claire je trouve

**Comment by Coy0te** [comment]
> Il faudra aussi corriger le parseur .tuto -> markdown qui est resté sur la syntaxe en cours de discussions [...]

C'est fait et [en ligne depuis une semaine](https://github.com/Coy0te/parseTuto/blob/master/src/zds/parseTuto/TestJSoup.java#L408).

**Comment by firm1** [comment]
C'est corrigé aussi en ce qui concerne le back-end.

Avec la syntaxe contenant : `source`
