### ISSUE TITLE
Erreur 500 sur la page "tout les tutoriels"

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1291]
Tout est dans le titre : il n'est plus possible d'accéder à cette page : http://zestedesavoir.com/tutoriels/ .... À noter que c'est pas le cas sur `master`.

**Comment by Eskimon** [comment]
Donc faudra sortir les logs de la prod' (poke @firm1 @SpaceFox )

**Comment by Alex-D** [comment]
Pour une raison inconnue a priori, la page fonctionne de nouveau...

**Comment by Eskimon** [comment]
Ce matin la page marche toujours... Effet de bord des validations échouées qui ont fait partir en 500 un des workers gunicorn ?

**Comment by Alex-D** [comment]
On serait tous arrivés sur le même worker ? Assez étrange... Je verrais plutôt une manip de quelqu'un qui n'aurait rien dit (n'ayant pas forcément connaissance de cette issue).

**Comment by Eskimon** [comment]
Faut-il laissé ouvert ? C'est irreproducible et ca sent le bug random du à l'infra / autre chose que le menu lui meme (donc indébuggable)

**Comment by SpaceFox** [comment]
Je ferme, on réouvrira si ça réapparait.
