### ISSUE TITLE
Le staff ne peut pas envoyer un article en validation

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1293]
Comment reproduire le bug
- Un utilisateur crée un article
- Le staff (sans être dans la liste des auteurs) demande la validation de cet article. La modale apparait bien, mais rien ne se passe et l'article n'est pas envoyé en validation (il n'apparait pas dans la liste des articles à valider).

Tip : très probablement dans `modify()` (donc [ligne 438 de views.py](https://github.com/zestedesavoir/zds-site/blob/master/zds/article/views.py#L438)).

**Comment by Alex-D** [comment]
Ca va être corrigé dans la #1275

**Comment by Alex-D** [comment]
Corrigé et mergé, je ferme.
