### ISSUE TITLE
Retour à la première page après suivi du sujet sur forum

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1295]
via [btw03 sur le forum](http://zestedesavoir.com/forums/sujet/853/retour-a-la-premiere-page-du-topic-apres-avoir-clique-sur-suivre-ce-sujet/?page=1#p11898) : 

> Sur un topic composé de plusieurs pages, après avoir cliqué sur "Suivre ce sujet" alors qu'on est sur une page autre que la première, on se retrouve redirigé vers la première page du topic. Je m'attendais à rester sur la page en cours.
> Le comportement est le même lorsqu'on clique sur "Ne plus suivre ce sujet".

Après discutions, il semblerai que la bonne solution serait de rediriger vers la page ou se trouvais la personne qui a cliqué sur le lien.

**Comment by gustavi** [comment]
Je prends.

**Comment by Alex-D** [comment]
Corrigé et mergé, je ferme.
