### ISSUE TITLE
Message d'erreur incorrect quand on se trompe sur l'adresse mail

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1296]
via ache sur IRC : 

> Quand on veut changer son adresse et qu'on fait une faute de frappe,  le message d'erreur n'est pas le bon. Il affiche  "Entrer un nom d'utilisateur".

**Comment by SpaceFox** [comment]
C'est corrigé ?

**Comment by Alex-D** [comment]
Yep, corrigé et mergé, je ferme :)
