### ISSUE TITLE
Focus des formulaires

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1297]
Comme l'as fait remarquer ache sur IRC, il n'y a pas de focus sur le champ "login" du formulaire de connexion. De manière générale, le focus n'est pas présent sur un certain nombre des formulaires que j'ai pu visiter (login, paramètres du compte, édition de tutos et autres). Oubli ou fonctionnalité ?

ping @Alex-D :)

**Comment by Alex-D** [comment]
Tu parles d'un auto-focus quand on arrive sur la page ?

Si oui, pour la page login c'est un oubli. Pour tout le reste des pages, ça n'a pas lieu d'être.

**Comment by pierre-24** [comment]
Ok, c'était juste pour être sur que ça avait été réfléchi :)

**Comment by Alex-D** [comment]
Corrigé et mergé. Je ferme.
