### ISSUE TITLE
MP à soi-même

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1298]
Rien n'empêche de s'envoyer un MP à soit-même (puisqu'on peut se sélectionner soit-même dans la liste des participants), mais aussi et surtout, rien n'empêche d'être le seul dans la conversation.

**Comment by Eskimon** [comment]
C'est mergé, je ferme !

**Comment by Axylium** [comment]
Il faudrait réouvrir de ce côté ! [Le bug est toujours présent](http://zestedesavoir.com/forums/sujet/1180/bug-envoi-dun-mp-a-soi-meme/?page=1#p19478).

**Comment by pierre-24** [comment]
Oui et non. En gros, il manque un test pour dire que si, **après vérification des pseudos**, la liste des destinataire est vide, ça passe pas.

**Comment by Alex-D** [comment]
Du coup, c'est vraiment un bug : on peut actuellement envoyer un MP sans participants.

**Comment by pierre-24** [comment]
Je prend. Je vois comment régler ça. J'en profiterais pour nous rajouter de
la couverture :)

**Comment by Eskimon** [comment]
Vas sur IRC alors, @Florianboux est deja dessus

**Comment by Axylium** [comment]
Je n'ai encore rien fait, étant donné que je ne suis pas arriver à reproduire le bug en local. Donc si il sait comment régler ça, rapidement, je laisse la main ! ;-)

**Comment by pierre-24** [comment]
Bon. À fortiori, la réouverture n'as pas lieu d'être. En effet, la dernière PR a avoir touché à ça (#1378) n'as pas été incluse dans la dernière MEP. Comme on arrive pas à reproduire le bug sur _master_ (mais bien sur _prod_ et _dev_), j'en déduis qu'il faut "simplement" attendre que ça passe en prod' :)

**Comment by Eskimon** [comment]
Je propose qu'on attende la prochaine MEP et qu'on ferme a ce moment la si tout va bien...

**Comment by SpaceFox** [comment]
Le bug n'est corrigé qu'à moitié : je suis bloqué si j'essaie d'envoyer un MP à SpaceFox, mais pas à spacefox.

C'est complexe à tester parce que cet imb****e de SQLite n'est pas sensible à la casse, contrairement à MySQL...

Le bug étant un bug v1.x mergé par convenance, il ne bloque pas la MEP de la v1.0 (sauf si bien sûr quelqu'un trouve un fix rapide).

**Comment by pierre-24** [comment]
Y'à un fix fait par @poulp et qui agit non plus sur le formulaire mais [directement sur la fonction d'envoi](https://github.com/zestedesavoir/zds-site/blob/dev/zds/mp/views.py#L182) pour bloquer les trucs a ce moment là. Mais comme l'as dis spacefox, c'est chaud à tester ...

**Comment by Eskimon** [comment]
Cette PR a réglé le souci non ? https://github.com/zestedesavoir/zds-site/pull/1431

(dans ce cas : v1.1 et a fermer :) )

**Comment by Eskimon** [comment]
Ok pour fermeture ?

**Comment by pierre-24** [comment]
J'attendrais vraiment la préprod pour être certain (faudrait un tag "préprod" pour ce genre de cas, genre on ferme mais on place le tag pour y faire attention).

**Comment by Alex-D** [comment]
Si on fait ça avec toutes les issues, on a pas fini... si on voit que le soucis est encore présent ou rouvrira, mais si on s'amuser à laisser ouvertes toutes les issues tant qu'elles ne sont pas en prod, ça va être infernal.

**Comment by Eskimon** [comment]
Bon... je viens de tester en preprod, si j'ecris a EsKimOn je peux bien m'ecrire a moi meme...

**Comment by SpaceFox** [comment]
C'est normal, il y avait une opération documentée je ne sais où qui donc n'a pas été faite...

**Comment by Eskimon** [comment]
Ok... Faudra prevenir quand ca sera ok alors, histoire de pas oublier de retester :)

**Comment by SpaceFox** [comment]
J'en parle ici
https://zestedesavoir.com/forums/sujet/1313/prets-pour-la-v11/?page=1#p22686
et si personne ne se dévoue pour le faire, ça devra attendre jusqu'à
dimanche soir...

2014-09-25 10:07 GMT+02:00 Eskimon notifications@github.com:
