### ISSUE TITLE
Le Menu fout le camp

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#130]
Comme on peut le vois dans l'image suivante :
![menu-decadence](https://f.cloud.github.com/assets/6066015/2049440/5a849eee-8a60-11e3-8282-3c3f67a7502c.png)

**Le menu fout le camp.**

Pour reproduire ce bug, il faut : 
- Aller sur preprod.zestedesavoir.com
- Cliquer sur le menu Tutoriel
- Cliquer ensuite sur le menu Forum.

Le problème vient du fait que le menu "tutoriel" ne se ferme pas lorsqu'on clique sur autre chose que lui même.

**Comment by GerardPaligot** [comment]
Indique ton navigateur, version, etc. parce qu'il se ferme bien chez moi.

**Comment by firm1** [comment]
Je teste sous : Chrome Version 32.0.1700.76

**Comment by firm1** [comment]
Je me rend compte que j'ai mal décrit la reproduction du bug. Voici la version correcte.
- Aller sur preprod.zestedesavoir.com
- Cliquer sur le menu Tutoriel
- Cliquer sur "Tous les tutoriels" ou sur n'importe qu'elle sous catégorie
- Cliquer ensuite sur le menu Forum.

**Comment by GerardPaligot** [comment]
Ok, j'ai le bug aussi alors.

**Comment by cgabard** [comment]
Idem sur FF26/Linux

**Comment by Alex-D** [comment]
Ah oui, mais là le problème vient du back, à cause de la classe "active" qui devrait être changée en "current" pour coller à mon CSS.
