### ISSUE TITLE
Mise à jour de la validation retire la réservation

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1304]
Lorsque l'on met à jour la version en validation, le valido qui avait réservé n'est plus identifié.

C'est dû au fait que lors d'une mise à jour, on supprime simplement l'ancienne version de l'objet validation, et qu'on en crée un nouveau.

Il faudrait donc soit : 
- mettre à jour l'objet validation en cours
- en créer un nouveau, mais en prenant en compte la réservation potentielle

La solution la plus simple me semble de rechercher l'objet validation en cours, et de mettre à jour son attribut "version" avec la version envoyée.

**Comment by firm1** [comment]
Si la mise à jour de validation se fait de manière transparente pour le valido, il risque de ne jamais se retrouver dans ses lectures.

Il faudrait le notifier (mp) qu'il y'a eu une mise à jour sur le tuto qu'il a réservé.

Imagines que tu es valido et que tu finis de lire un chapitre et que celui-ci est modifié en douce par un auteur. Tu risque de laisser passer des problèmes.

**Comment by Alex-D** [comment]
+1 pour le MP.

Avec l'historique y a moyen de s'y retrouver :) C'est là tout l'intérêt d'avoir une gestion de versions.

**Comment by firm1** [comment]
Fx'd
