### ISSUE TITLE
Ordre des messages en zone Staff

### ISSUE THREAD

**Issue by Fumble** [zestedesavoir/zds-site#1308]
Salut,
Dans un des sujets du forum Staff, mon message était le dernier. Aujourd'hui Micmaths a posté et quand j'accède au sujet, son message est placé avant le mien.

Je ne sais pas si c'est reproductible ailleurs.

Voir capture ci-jointe.

![bug_staff](https://cloud.githubusercontent.com/assets/634461/3714564/6c3668f8-15b0-11e4-8201-0b3f898c61e4.png)

**Comment by Alex-D** [comment]
Un message qui date du 1er mai, c'est impossible il me semble... sachant qu'on RàZ en juin. Tu aurais le lien ?

**Comment by Fumble** [comment]
Sans doute pas les sujets Staff ==> http://zestedesavoir.com/forums/sujet/3/bienvenue-chers-membres-du-staff/

**Comment by Alex-D** [comment]
Je soupçonne un bug mystique venant du fait que le topic date d'avant plein de changements sur les schémas/models et qui n'a pas subit la RàZ.

Je pense qu'on peut se permettre de zapper ça de part le fait que ça n'arrive pas sur tous les autres sujets qui datent donc d'après la RàZ propre.

**Comment by gustavi** [comment]
Je confirme qu'il est impossible de le reproduire sur un environnement de dev.
