### ISSUE TITLE
Les signatures n'adoptent pas le style

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#131]
Le problème est légèrement technique quand même, et je ne saurai trop dire si c'est à cause du markdown, ou a cause du design. 

Il suffit d'aller sur le topic [suivant](http://preprod.zestedesavoir.com/forums/sujet/8/les-renards-dirigent-le-monde?page=1#p72), pour constater que la signature n'est pas affichée comme elle le devrait. Pour info, elle devrait être affichée comme [par ici](http://zds.alex-d.fr/forum-topic-member.html?#).

Le back-end fait normalement bien son boulot ici, et voici le bout de code du template chargé d'afficher la signature.

``` python
{% with profile=post.author|profile %}
      <p class="signature">{{profile.sign|emarkdown}}</p>
{% endwith %}
```

Normalement dans mon cas, ça devrait rendre ceci : 

``` html
<div class="message-bottom">
    <p class="signature">
        <div class="markdown"><p>Je suis membre de developfutur et j'aime <a href="www.developfutur.com">ça</a></p></div>
    </p>
</div>
```

mais ça rend plutot ceci : 

``` html
<div class="message-bottom">
    <p class="signature"></p>
    <div class="markdown"><p>Je suis membre de developfutur et j'aime <a href="www.developfutur.com">ça</a></p></div>
    <p></p>
</div>
```

Chose étrange, quand j'enlève la conversion markdown de la signature, la signature rentre dans la bonne balise, mais du coup le texte n'est plus interprété.

J'ai donc l'impression que la fonction `emarkdown` fait automatiquement un saut à la ligne. Ce qui conduit à la fermeture de ma balise `<p class="signature">`.
## Pour corriger ça, il y'a deux manière de faire :
- Option 1 : le front propose une balise différente de <p> pour la signature ou un div par dessus
- Option 2 : le back corrige la fonction emarkdown pour ne plus créer de saut de ligne. _Le problème ici étant que je n'ai aucune idée de l'impact de cette modification sur le comportement général de l'interprétation markdown ailleurs_

**Comment by cgabard** [comment]
> J'ai donc l'impression que la fonction emarkdown fait automatiquement un saut à la ligne. Ce qui conduit à la fermeture de ma balise <p class="signature">.

Tu peux détailler ça ? Dans quel sens un saut de ligne serait inséré ? Un br ? un `\n` ?

Perso je n'avais pas trop détaillé ça, car cela demande des modifs dans python-markdown, mais je pensais pour les signatures creer une autre fonction de parsage dans python-markdown pour ne faire passer que les trucs "inline". Car tout ce qui n'est pas inline ne devrait pas etre parsable dans la signature.

Donc si j'étais toi, je ferais une nouvelle fonction "emarkdown_inline" qui actuellement fait la même chose que "emarkdown" actuel (je mettrais à jour quand j'aurais rajouter cette possibilité de ne passer que les inlines), utilise là pour les signatures, et eventuellement, entoure le résultat d'un "strip()" pour virer les `\n` eventuels. Dans tous les cas, une fonction de parsage specifique au signature serait une bonne idée.

Pendant que j'y suis, ça veut dire que django interprete et potentiellement modifie le html généré avant de l'insérer dans les templates. Tu as des détails là dessus ? Un moyen de savoir ce que ça fait ? Car ça pourrait expliquer mes probs avec les "param" disparessants dans les balises "objects"

**Comment by cgabard** [comment]
PS: Dans les commentaires de tuto : http://preprod.zestedesavoir.com/articles/12/rediger-sur-zds?page=1#p61 il n'y a meme pas la class signature

**Comment by firm1** [comment]
> PS: Dans les commentaires de tuto : il n'y a meme pas la class signature

ça c'est parce que je n'ai pas encore intégré cette partie.

Pour ton message précédent je répondrais quand j'aurai mangé.

**Comment by firm1** [comment]
> Tu peux détailler ça ? Dans quel sens un saut de ligne serait inséré ? Un br ? un \n ?

Je ne sais pas quel type de saut est inséré. Je n'ai pas accès à une console python pour faire le test actuellement, je te dirais ça quand j'aurai inspecté un peu plus.

> Perso je n'avais pas trop détailler ça, car cela demande des modifs dans python-markdown, mais je pensais pour les signatures creer une autre fonction de parsage dans python-markdown pour ne faire passer que les trucs "inline". Car tout ce qui n'est pas inline ne devrait pas etre parsable dans la signature.

Effectivement, j'y avais pensé, mais je ne savais pas encore trop à quel niveau il fallait agir. Je ne maîtrise pas assez le fonctionnement de python-markdown pour le dire, mais il n'y a pas moyen d'interdire l'interprétation de certaines balises markdown autrement qu'en triturant la lib ? Autrement dit, une fonction emarkdown_inline qui n'autorise que des trucs commes (gras, italique, lien) necessaite t-elle la modification de la lib python-markdown ?

> Pendant que j'y suis, ça veut dire que django interprete et potentiellement modifie le html généré avant de l'insérer dans les templates. Tu as des détails là dessus ? Un moyen de savoir ce que ça fait ? Car ça pourrait expliquer mes probs avec les "param" disparessants dans les balises "objects"

Je n'ai pas eu le temps de poussé la reflexion aussi loin, je te donnerai des nouvelles dès que j'en saurai plus.

**Comment by cgabard** [comment]
En fait non pas besoin de forcément modifier python-markdown. On peut s'en sortir en n'activant que les extensions que l'on veut + virer les trucs pré-intégré qu'on ne veut pas. Mais je trouvais ça plus propre de faire une fonction dédié : avec le même paramétrage elle ne traite que le inline. Ça éviterais de mettre a jour plusieurs endroits si on rajoute une extension. 

Pour le reste, j'attends de tes news mais dans tous les cas un "emarkdown_inline" serait pratique car on ne sait jamais, ça pourrait dervir ailleurs que dans les signatures.

**Comment by cgabard** [comment]
Au passage, pour les signatures, tu as vraiment besoin que le html fournit soit dans un div "markdown" ?
Et vu comment c'est fait dans la fonction emarkdown, il n'y a aucun saut de lignes avant/apres le div à la sortie de la fonction

**Comment by firm1** [comment]
> Au passage, pour les signatures, tu as vraiment besoin que le html fournit soit dans un div "markdown" ?

Non, je m'en fou.

> Et vu comment c'est fait dans la fonction emarkdown, il n'y a aucun saut de lignes avant/apres le div à la sortie de la fonction

Je viens de voir ça. Mais du coup, je me demande pourquoi est-ce que le html est rendu aussi bizarrement plus haut. Enquête a mener

**Comment by cgabard** [comment]
> Non, je m'en fou.

Avec la PR que j'ai fait, il va etre facile a virer dans ce cas là

**Comment by firm1** [comment]
Bon bah, ça me fait planter le serveur : http://preprod.zestedesavoir.com/forums/sujet/8/les-renards-dirigent-le-monde?page=1#p72

**Comment by cgabard** [comment]
tu as la BT qu'on sache pourquoi ?

**Comment by firm1** [comment]
J'ai un truc bizarre, mais c'est sur mon smartphone, donc c'est un peu galère

**Comment by firm1** [comment]
Le truc qui me surprend quand même c'est qu'après avoir viré le [`div class="markdown"`](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/utils/templatetags/emarkdown.py#L102), dans [ce tuto](http://preprod.zestedesavoir.com/tutoriels/18/alignement-memoire-et-endianess/#2-endianness), on en trouve encore dans le html ... Weird ...

**Comment by cgabard** [comment]
Le html des tutos n'est pas en cache ?

**Comment by firm1** [comment]
Haha, si. Lol. J'oublie à chaque fois putain

**Comment by cgabard** [comment]
:+1:

**Comment by firm1** [comment]
En fait, après avoir regardé un peu tout ça de plus près. Déjà la ligne qui fait tourner le serveur en while, c'était : `md.parser.blockprocessors.clear()`

Quand je la vire, ça tourne, mais le parseur retourne toujours le texte entre les balise `<p></p>` ce qui casse donc la balise `<p class="signature"></p>` parente.
En fouinant un peu la lib python-markdown, on dirait que la balise `<p>` est toujours rajoutée par le paragraphblockprocessor. J'ai tenté tant bien que mal de le poper, mais ça marche pas.

Ma question : peux-tu modifier `emarkdown_inline`  pour que l'on ai une chaîne sans les balise `<p>` ?

**Comment by cgabard** [comment]
Yep, des que j'ai du temps

**Comment by Alex-D** [comment]
Quelqu'un a une idée sur ce bug ?

Au pire, je peux prendre le code actuel, retirer le `p.signature` et styliser directement le `<p>` mais c'est moins funky, mais ça passerait sans bug.

**Comment by cgabard** [comment]
Oui il faut que j'aille trifouiller markdown mais j'ai pas encore eu le temps. En attendant je peux te faire un fix rapide : ne pas faire passer la signature dans markdown.

**Comment by Alex-D** [comment]
En effet ça peut faire l'affaire temporairement. Je retirerais le filtre lors de mon prochain commit.
À noter que la branche intégration est en travaux donc ça bug possiblement de partout.

**Comment by cgabard** [comment]
A priori le prob est que markdown inclu forcément le texte dans un paragraphe. C'est loin d'etre choquant dans le cas général mais pour notre cas à nous, c'est un peu pénible. Je vais essayer de le faire prochainement mais ces dernierers semaines des soucis persos ne me l'ont pas permis

**Comment by Alex-D** [comment]
Est-ce que ce bug est corrigé avec le dépôt du parseur spécifique à ZdS ? Si oui, c'est clos du coup, non ?

**Comment by firm1** [comment]
[Il est pas encore corrigé](http://preprod.zestedesavoir.com/articles/21/rediger-sur-zds?page=1#p94).

**Comment by Alex-D** [comment]
Punaise, il y a même un <p> vide en dessous... le parseur fait un peu ce qu'il veut on dirait :/

**Comment by cgabard** [comment]
C'est marrant car sur mobile ça pose pas de soucis d'affichage.

Btw je tenterai de faire le fix des que je peux. Si c'est pénalisant, en attendant firm1 peut désactiver le markdown dans la signature.

Mais si j'ai bien compris, au niveau signature il faut virer le p englobant ?

**Comment by cgabard** [comment]
C'est marrant car sur mobile ça pose pas de soucis d'affichage.

Btw je tenterai de faire le fix des que je peux. Si c'est pénalisant, en attendant firm1 peut désactiver le markdown dans la signature.

Mais si j'ai bien compris, au niveau signature il faut virer le p englobant ?

**Comment by firm1** [comment]
> Mais si j'ai bien compris, au niveau signature il faut virer le p englobant ?

Ouais

**Comment by Alex-D** [comment]
En fait, le design est déjà prévu pour utiliser un <p> avec une certaine
classe. Du coup ça casse tout. Donc oui, il faudrait ne pas avoir de <p> du
tout.

Thanks :-)

**Comment by cgabard** [comment]
OK. J'ai rajouté le tag markdown sur cette issue et je m'en occupe quand je peux

**Comment by firm1** [comment]
bon bah avec le design en cours, cette tache est fixée.

Je ferme.
