### ISSUE TITLE
Utiliser une version custom de Modernizr pour augmenter la vitesse de chargement

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1311]
@sandhose avait voulu utiliser Modernizr en tant que dépendance bower, mais il se trouve qu'il n'est pas ainsi possible de limiter les fonctionnalités dont on a besoin.

Il faudrait donc remettre en place un version custom de Modernizr avec le strict minimum.

Les effets de cette "désoptimisation" sont que sur mobile on a un chargement en deux voire trois temps : header très grand, écran gris foncé, rendu final.

**Comment by SpaceFox** [comment]
> Les effets de cette "désoptimisation" sont que sur mobile on a un chargement en deux voire trois temps : header très grand, écran gris foncé, rendu final.

Je ne comprends pas très bien : la version actuelle a ces problèmes, et tu proposes de corriger ça. J'ai bon ?

**Comment by Alex-D** [comment]
> la version actuelle a ces problèmes, et tu proposes de corriger ça.

Oui, elle a des problème, c'est un bug que je trouve assez gênant, mais qui n'est pas trivial à résoudre si on veut le faire proprement (utiliser gulp/bower). Donc je pense que je vais faire ça de façon "sale" et mettre la version custom de Modernizr dans le repo directement.

**Comment by Alex-D** [comment]
Mergé -> fermé.
