### ISSUE TITLE
Pygments : PHP "non embarqué"

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1312]
Je crois qu'on utilise Pygments sur le site... si non, il faut retrouver l'équivalent.

Mon problème est que les codes PHP nécessitent l'ouverture systématique de la balise `<?php` pour être coloriés.

Ce devrait être le cas avec le lexer "php+html" mais pas avec le lexer "php".

À priori il y a un paramètre à passer à Pygments pour qu'il ne requière pas cette balise avec le lexer "php" : http://pygments.org/docs/lexers/#pygments.lexers.web.PhpLexer

**Comment by cgabard** [comment]
Tiens je l'avais pas vu celui là.

Alors techniquement c'est dans le markdown qu'il faut le mettre ce ticket, c'est lui qui englobe pygment.

Pour le résoudre, juste [apres l'étape de création du lexer](https://github.com/zestedesavoir/Python-ZMarkdown/blob/master-zds/markdown/extensions/codehilite.py#L127) il faut regarder si c'est un lexer php et, le cas échéant, activer l'option.

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis plus d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.
