### ISSUE TITLE
Petite incohérence de type faisant échouer un test de la branche dev

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1315]
J'ai mergé master dans dev, mais il se trouve qu'un bugfix de master fait planter un test ajouté dans dev.

@poulp si tu pouvais jeter un oeil ça serait niquel. C'est ton test il me semble : `test_fail_get_with_username_not_exist` qui échoue. Pour les détails, ça se passe ici : 
https://travis-ci.org/zestedesavoir/zds-site/builds/31104220

**Comment by Alex-D** [comment]
Ok, j'ai trouvé, ça vient d'un de mes fix en fait. Le test est bon.

**Comment by SpaceFox** [comment]
> Ok, j'ai trouvé, ça vient d'un de mes fix en fait. Le test est bon.

Ça veut dire qu'on a réussi à merger quelque chose qui ne passait pas les tests ?!

**Comment by Eskimon** [comment]
Nan c'est le merge master -> dev pour rétablir la version de dev si j'ai bien suivi (et du coup avec des differences puisque dev n'est pas iso avec master)

**Comment by firm1** [comment]
C'est pour celà qu'il vaudrait mieux faire une PR pour les merges master-> dev, et ainsi faire une QA avant de valider tout ça.

**Comment by SpaceFox** [comment]
Surtout, il faut **toujours** jouer les tests avant de pousser quoi que ce soit sur le dépôt principal !

**Comment by Alex-D** [comment]
Vous vous enflammez pour rien : 
- j'ai fait un bugfix sur master
- poulp a rajouté des tests sur dev
- j'ai mergé master dans dev : un des tests ne passait pas
- j'ai corrigé mon bugfix pour qu'il passe le test

Je ne vois pas où il y a un problème.

>  il faut toujours jouer les tests avant de pousser quoi que ce soit sur le dépôt principal !

Pour ça il faudrait que je puisse les jouer sur Windows, ce qui n'est pas le cas à l'heure actuelle. Aussi il faut pandoc : sur Windows c'est juste une blague. Donc le code étant stable sur master, il ne s'agissait qu'un d'un truc infime.

Je conclurais par dire qu'encore une fois vous vous excitez après que j'ai fait une PR corrective, qui fonctionne et qui est mergée. Donc je ferme cette issue.
