### ISSUE TITLE
[Ortho] Correction mineure dans le message d'édition

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#1317]
Il faudrait remplacer "Edité" par "Édité" dans cette ligne : 

=> https://github.com/zestedesavoir/zds-site/blob/24161830d639169c7092c83e7f75d20c0c5f1ba9/templates/misc/message.part.html#L178

**Comment by Eskimon** [comment]
Est-ce qu'on peut autoriser **exceptionnellement** la modif' direct sur la branche master ? C'est un peu pénible de faire une PR **juste pour une lettre**...

(si on me repond "nan!" je comprend aussi)

**Comment by Coy0te** [comment]
On m'a déjà répondu "non" par le passé, donc je te le dis à mon tour : non ! :D

**Comment by gustavi** [comment]
Ce n'est pas le seul, j'avais reporté plusieurs problèmes d'accent sur le forum. Autant grouper.

**Comment by pierre-24** [comment]
Qui se lance pour une PR "orthographe" ?

**Comment by Eskimon** [comment]
Si on me liste les fautes d'ici ce soir je peux le faire en rentrant chez moi (IRC a partir de 16h15) (mais me demandez pas non plus d'aller relire les xx pages du sujet "Les petits pixels")

**Comment by DevHugo** [comment]
Si cela dérange personne, je prends

**Comment by Alex-D** [comment]
Validé et mergé.
