### ISSUE TITLE
Chapitres du tuto Windows 8 inaccessibles

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#1318]
Aucun chapitre du tuto Windows 8 n'est accessible : http://zestedesavoir.com/tutoriels/189/debutez-en-informatique-avec-windows-8/

Erreur 500 à chaque fois. 

Je me permets un ticket GH car le problème a été signalé sur l'adresse email de l'asso.

**Comment by SpaceFox** [comment]
On a des erreurs du genre :

```
[ERROR] -- 2014-07-29 15:42:38,564 -- base : Internal Server Error: /tutoriels/189/debutez-en-informatique-avec-windows-8/221/premiers-pas/1346/les-differents-elements-a-lecran/
Traceback (most recent call last):
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/zdsenv/ZesteDeSavoir/zds/tutorial/views.py", line 1559, in view_chapter_online
    "r")
IOError: [Errno 2] No such file or directory: u'/opt/zdsenv/ZesteDeSavoir/tutoriels-public/189_debutez-en-informatique-avec-windows-8/221_premiers-pas/1346_les-differents-elements-a-lecran/introduction.md.html'
```

Si je vais dans le dossier, j'ai bien les .md mais pas les .html

C'est comme si la validation avait foiré la génération des .html.

**Comment by ShigeruM** [comment]
Je viens d'essayer de le revalider. J'ai eu une erreur 500 lors de la validation. J'imagine que les fichier .html n'ont pas été créés car il y a toujours une 500 lors de l'affichage d'un chapitre.

**Comment by SpaceFox** [comment]
J'ai les erreurs suivantes dans les logs :

```
IOError: [Errno 2] No such file or directory: u'/opt/zdsenv/ZesteDeSavoir/tutoriels-public/189_debutez-en-informatique-avec-windows-8/221_premiers-pas/1345_windows-cest-quoi-au-juste/introduction.md.html'
[ERROR] -- 2014-07-29 17:51:22,690 -- base : Internal Server Error: /membres/connexion/
Traceback (most recent call last):
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/zdsenv/ZesteDeSavoir/zds/member/views.py", line 563, in login_view
    + "?next=" + str(next_page)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 15: ordinal not in range(128)
[ERROR] -- 2014-07-29 17:56:19,166 -- base : Internal Server Error: /tutoriels/189/debutez-en-informatique-avec-windows-8/221/premiers-pas/1346/les-differents-elements-a-lecran/
Traceback (most recent call last):
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/zdsenv/ZesteDeSavoir/zds/tutorial/views.py", line 1559, in view_chapter_online
    "r")
IOError: [Errno 2] No such file or directory: u'/opt/zdsenv/ZesteDeSavoir/tutoriels-public/189_debutez-en-informatique-avec-windows-8/221_premiers-pas/1346_les-differents-elements-a-lecran/introduction.md.html'
[ERROR] -- 2014-07-29 17:56:54,508 -- base : Internal Server Error: /tutoriels/validation/valid/
Traceback (most recent call last):
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/zdsenv/ZesteDeSavoir/zds/member/decorator.py", line 20, in _can_write_and_read_now
    return func(request, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/zdsenv/ZesteDeSavoir/zds/tutorial/views.py", line 351, in valid_tutorial
    (output, err) = MEP(tutorial, tutorial.sha_validation)
  File "/opt/zdsenv/ZesteDeSavoir/zds/tutorial/views.py", line 2900, in MEP
    out_file = open(os.path.join(tutorial.get_prod_path(), fichier), "w")
IOError: [Errno 2] No such file or directory: u'/opt/zdsenv/ZesteDeSavoir/tutoriels-public/189_debutez-en-informatique-avec-windows-8/1345_windows-cest-quoi-au-juste/introduction.md'
[ERROR] -- 2014-07-29 17:57:32,514 -- base : Internal Server Error: /tutoriels/off/255/analysez-des-donnees-avec-excel/284/les-bases-du-langage-vba/1599/premiers-pas-en-vba/Templates/images/smilies/siffle.png
Traceback (most recent call last):
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 199, in get_response
    response = middleware_method(request, response)
  File "/opt/zdsenv/ZesteDeSavoir/zds/middlewares/profile.py", line 90, in process_response
    if (settings.DEBUG or request.user.is_superuser) and 'prof' in request.GET:

```

**Comment by Eskimon** [comment]
Ahhhh l'encodage :) C'est chouette ca !!

> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 15: ordinal not in range(128)

**Comment by ShigeruM** [comment]
Tu as moyen d'identifier le(s) caractère(s) qui posent problème ? Je peux
refaire une passe sur le tuto s'il le faut.

**Comment by Eskimon** [comment]
apparemment ce serait un 'é' c'est bizarre...

**Comment by gustavi** [comment]
Je suppose que c'est encore python2 + unicode. Vivement qu'on passe à python3.

**Comment by SpaceFox** [comment]
http://upload.kisai.info/win8/17_big_709467-debutez-en-informatique-avec-windows-8.tuto
http://upload.kisai.info/win8/images.zip

**Comment by SpaceFox** [comment]
PS :

> Je suppose que c'est encore python2 + unicode. Vivement qu'on passe à python3.

Aux dernières nouvelles, il n'y avait pas lib de gestion de Git compatible python3 :(

**Comment by Eskimon** [comment]
Bon... En SQLite ou en MySQL tout passe bien chez moi...

**Comment by SpaceFox** [comment]
Je commence à soupçonner un problème immonde de tenue en charge à un niveau bizarre.

Parce que le problème n'est pas reproductible en préprod. Pire : il n'était pas reproductible en prod il y a 15 minutes (i.e. à une heure où il n'y a personne).

Les erreurs qu'on voit dans les logs ont l'air aléatoires, parce que si on va sur les pages incriminées, en général elles fonctionnent.

C'est comme si "quelque chose" nous disait d'aller nous faire foutre et renvoyait de temps à autre des données incohérentes. J'aurais bien dit qu'on a des problèmes de deadlock SQL ou tout autre connerie du même acabit, mais je n'ai aucun indice en ce sens.

En première approche (ça vaut ce que ça vaut), c'est comme si _la lecture de fichiers_ renvoyait des informations parcellaires... ce qui n'a aucun sens !

On devrait y voir plus clair demain avec les premiers logs Sentry (à l'heure actuelle, ils restent désespérément vides).

Plans d'actions possibles :
1. On arrive à trouver et traiter la cause racine grâce aux logs. C'est l'idéal.
2. Les erreurs semblent concerner un tout petit nombre de lignes de code. Si c'est bien le cas (à vérifier avec les logs), on peut mettre des sécurités paranoïaques à ces endroits pour gérer le fait que _l'action qui ne devrait jamais planter, plante_.

**Comment by Eskimon** [comment]
> C'est comme si "quelque chose" nous disait d'aller nous faire foutre et renvoyait de temps à autre des données incohérentes. J'aurais bien dit qu'on a des problèmes de deadlock SQL ou tout autre connerie du même acabit, mais je n'ai aucun indice en ce sens.

Possible... Je te rappel que lors de la beta privée on avait eu une couille comme ca quand on ouvrait les notifs dans des onglets non ?

**Comment by SpaceFox** [comment]
Certes mais c'était reproductible (compliqué mais reproductible). Alors que
là...

**Comment by SpaceFox** [comment]
Il faudrait tester de re-publier le tuto une fois la PR #1322 mergée. Si possible un soir quand y'a plus grand-monde :)

**Comment by firm1** [comment]
[Fx'd](http://zestedesavoir.com/tutoriels/446/debutez-en-informatique-avec-windows-8/)
