### ISSUE TITLE
Inscrire un auteur aux reactions de tutos/articles

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1319]
Lorsqu'un auteur publie un article (et idem pour tuto ?) il n'est pas automatiquement ajouté aux suivis des reactions (tant qu'il ne poste pas). C'est dommage !

**Comment by Eskimon** [comment]
Au passage, rajouter un bouton dans la sidebar "suivre/quitter les reactions de ce tuto/article" serait pas mal je pense

**Comment by artragis** [comment]
Je suis en train de regarder ça. Et je dois avouer que c'est bizarre.

La classe `ArticleRead` (et son équivalent pour les tuto) demande absolument une _réaction_.
Ce qui signifie qu'il faut absolument qu'il y ait une réponse pour que la chose soit prise en compte.

Mais pire, cela ne se met pas à jour à la _lecture_ de l'article mais lorsqu'on poste. Du coup actuellement, ça sera complexe de faire un subscribe/unsubscribe sauf à modifier un peu le modèle en ne donnant pas comme obligatoire l'utilisation de la `Reaction`.

**Comment by firm1** [comment]
Tu regardes dans le mauvais sens on dirait.

Le suivi (via les notif) des réactions d'un article, d'un tuto et d'un topic de forum n'est pas pareil.

Pour le forum on se base sur une la classe `TopicFollowed` et `TopicRead` alors que dans le cas des articles et tutos, on se base uniquement sur `ArticleRead` ou `TutorialRead`, en partant du principe que pour suivre il faut poster.

Résoudre cette issue reviendrait donc a crée les tables `TutorialFollowed` et `ArticleFollowed` et d'adapter le calcul pour les notification.

Mais très sincèrement, pour éviter de pourrir le modèle de donnée ainsi que les fichiers de migrations, je vous conseille d'attendre le passage de la ZEP 12 vu que cette issue n'est pas urgentissime.

**Comment by artragis** [comment]
C'est plus ou moins ce que je disais.

Et OK pour la ZEP 12.

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
On l'avait oublié.

2015-04-16 14:23 GMT+02:00 Eskimon notifications@github.com:

**Comment by Situphen** [comment]
Ping @ChantyTaguan (ZEP 24) aussi pour faire gaffe à ne pas l'enlever par mégarde lors du rebasage (après le merge de la ZEP 12) ! :)

**Comment by artragis** [comment]
la zep12 ajoute cette fonctionnalité.

**Comment by Situphen** [comment]
Je sais, je prévenait juste @ChantyTaguan qu'après le merge de la ZEP 12, il rebasera sa branche et qu'il doit faire attention à ne pas enlever ce que vous venez d'ajouter ;)

**Comment by ChantyTaguan** [comment]
A mon avis le mécanisme de notification aura tellement changé que ça reviendra surtout à virer tout ce qui a trait aux anciennes notifs pour remplacer par le nouveau mécanisme. Et ce comportement étant prévu déjà dans la ZEP-24, ça devrait bien être pris en compte.
