### ISSUE TITLE
Clém' est légèrement coupée !

### ISSUE THREAD

**Issue by YoruNoHikage** [zestedesavoir/zds-site#1324]
Vous allez dire que je suis tatillon mais sur la page d'accueil, en fonction de la taille de la page (je suis en 1366x768) Clém est légèrement coupée à cause du redimensionnement CSS. Je précise bien (ayant testé avec la vue adaptative de Firefox) qu'elle n'est pas coupée pour toutes les définitions d'écran.

![Clem' coupée](https://cloud.githubusercontent.com/assets/969003/3751029/7a453b7a-17fb-11e4-86cb-c701a14be431.png)
Clem' coupée

![Clem avec width: 39px en plus](https://cloud.githubusercontent.com/assets/969003/3751030/7a54d3b4-17fb-11e4-837d-2b6811e459a7.png)
Clem avec `width: 39px` en plus

**Comment by Alex-D** [comment]
C'est à cause de Gecko qui rend mal les images qui ne sont pas dimensionnées (un reflow qui manque) je verrais si j'ai le temps de patcher ça pour la prochaine MEP.

**Comment by Alex-D** [comment]
Corrigé, testé, approuvé, mergé, je ferme :)

Ca arrivera donc dans une prochaine mise en prod'
