### ISSUE TITLE
Rajouter mhchem dans la liste des packets chargés par MathJax

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1328]
En temps que chimiste, je trouverai réellement utile de charger le [paquet `mchchem`](http://docs.mathjax.org/en/latest/tex.html#mhchem), qui simplifie largement l'écriture de formules chimiques ainsi que d'équation (chimiques, toujours) :)

**Comment by Eskimon** [comment]
Merged -> closed !
