### ISSUE TITLE
Le formulaire pour adhérer à l'association reste remplis une fois ce dernier envoyé

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1330]
Tout est dans le titre, il faut juste ajouter _form = MonFormulaire()_ après le _if ...is_valid()_ pour vider le contenu actuel.

**Comment by Nodraak** [comment]
> Tout est dans le titre, il faut juste ajouter form = MonFormulaire() après le if ...is_valid() pour vider le contenu actuel.

Il faut faire ça après que le mail soit parti, pour ne pas envoyer uniquement des mails vides.

**Comment by Alex-D** [comment]
C'est mergé !
