### ISSUE TITLE
Validation partielle de big-tuto

### ISSUE THREAD

**Issue by coma94** [zestedesavoir/zds-site#1334]
Il serait vraiment utile de pouvoir valider partiellement des big-tuto, en choisissant quels chapitres passer en ligne.

Ça permet aux auteurs de publier un cours avant qu'il ne soit totalement fini, et pour un gros tuto c'est quasi indispensable.

Ça pose également problème pour certains tutos importés, étant donné que le sdz proposait cette fonctionnalité. Par exemple le tuto Zbrush, qui a des chapitres en cours de rédaction.

**Comment by SpaceFox** [comment]
Vous (surtout @firm1) m'arrêterez si je dis des conneries, mais je pense qu'ici on a des difficultés techniques qui rendent la chose assez délicate.

Si mes souvenirs ne me trahissent pas, "valider" ou "mettre en bêta" revient à désigner une version Git et à dire "celle-ci est publiée".

On voit bien le problème ici : on publie _toute_ la version, donc _toutes_ les parties de cette version. Pour faire une publication partielle, on a besoin de :
- Lister quelque part les parties à publier ou non
- Utiliser cette liste pour n'afficher que les parties marquées comme telles :
  - Soit se servir de ces informations pour ne générer que les HTML qui vont bien
  - Soit se servir de ces informations pour créer une branche Git qui ne contient que les sources qui vont bien (et publier cette branche)
  - Une autre idée plus intelligente

Dans tous les cas, c'est du lourd qui va nécessiter beaucoup de tests.

**Comment by Alex-D** [comment]
Suffirait pas de mettre un booléen dans le manifest ? L'auteur (et staff) verrait tout quand c'est en brouillon, puis en beta et en public, il faudrait afficher une modale pour sélectionner (plein de checkbox) les parties / chapitres qu'on veut, et donc en beta et en public, on ne verrait que ces dites parties.

Ca permet entre autres :
- de garder les parties/chapitres choisis lors de la beta au passage à la validation (pas besoin de re-check tout)
- de ne pas toucher aux fichiers sources
- le filtre serait assez simple : un simple booléen
- pas de nouvelle branche ou autre
- tout ce qui est construit se basant sur le manifest, on est certain que tout est cohérent.

**Comment by SpaceFox** [comment]
Je ne comprends pas ce que ferait ce booléen, ni comment tu gères les problématiques que je soulève avec ta proposition.

**Comment by Alex-D** [comment]
Le booléen dirait si oui ou non on  rend visible publiquement la partie/chapitre. Donc ça résout ton premier point (on a la liste des parties à publier ou non).

Vu qu'on sait ce qu'on doit publier ou non avec ce boolean (qui est présent pour chaque partie/chapitre) on peut construire tout à partir de là : sommaire, fichiers, HTML, etc.

**Comment by SpaceFox** [comment]
En fait, c'est la première de mes propositions avec une idée d'implémentation pour la liste des parties à publier ?

**Comment by Alex-D** [comment]
Yep, je trouve que c'est suffisant comme solution (puisqu'il ne faut qu'un booléen), donc j'approuve cette solution. Désolé si ça n'étais pas très clair :/

**Comment by firm1** [comment]
Cette fonctionnalité étant très demandée, je vais m'y coller ce week end.

Pour la petite histoire voici ce que je compte faire (à vous de me dire si ça convient) : 
- Au moment de la demande de validation/mise à jour de la version de validation, lister l'ensemble des extraits du tutoriel et demander à l'utilisateur de selectionner les extraits qu'il souhaite envoyer en validation.
- Par déduction, le chapitre ne partira en validation que si un de ses extraits à été sélectionné
- Par déduction aussi la partie ne va en validation que si un de ses chapitre y va
- Quand le valido consulte la version en validation, il ne voit que les parties/chapitres/extraits qui ont été envoyés.
- Lorsque le tuto est validé seul les parties/chapitres/extraits qui ont été envoyés en validation sont visibles en ligne, et dans les exports (pdf, html, markdown)
- Si l'auteur ou le valido consulte une autre version que la version en validation ou la version publique il peut tout voir

---

Pour ce schema de fonctionnement j'arrive à visualiser son implémentation technique, par contre, j'ai juste une question (qui peut changer conceptuellement les choses) : **Faut-il inclure aussi la mise en beta partielle ?**. Personnellement je pense que non, car c'est de la beta, donc on s'en fou, mais je me trompe peut-être.

**Comment by Alex-D** [comment]
> Faut-il inclure aussi la mise en beta partielle ?

Pour moi, oui. On veut des retours sur une version iso de ce qu'on est susceptible de publier, pas sur un brouillon que tu as mis dans un chapitre à part.

**Comment by firm1** [comment]
Dans ce cas on verra pour la beta partielle une autre fois. Je vais commencer une première itération sur la validation uniquement.

**Comment by cgabard** [comment]
C'est pas en prod ça maintenant ?

**Comment by firm1** [comment]
Nope (la PR est toujours en zone de PR)

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
on aimerait que ça y soit, pas encore codé, je pense que je vais la passer
en "need help".

2015-04-16 14:21 GMT+02:00 Eskimon notifications@github.com:

**Comment by SpaceFox** [comment]
Finalement c'est dans la ZEP-12 ça ?

**Comment by GerardPaligot** [comment]
Non

**Comment by Eskimon** [comment]
Exact, ca a été relégué en évo sous peine de ralentir la mise en route de la zep-12 pour quelque chose d'utile mais non primordiale dans un premier temps

**Comment by AmarOk1412** [comment]
Possible d'augmenter la priorité de ce ticket ? ça a re-été demandé cette semaine cc @artragis ?

**Comment by artragis** [comment]
voilou les gens, j'ai fait la PR
