### ISSUE TITLE
Erreur 500 / IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1335]
Trouvé dans Sentry : on a un certain nombre d'erreurs qui correspondent à ce schéma :

> zds.tutorial.models in get_introduction_online
> IOError: [Errno 2] No such file or directory: u'[...]'

Avec le fichier manquant toujours de la forme "/opt/zdsenv/ZesteDeSavoir/tutoriels-public/[dossier d'un tuto en bêta]/introduction.md.html"

L'URL incriminée est toujours une URL de recherche.

Apparemment il y a un cas lors qu'on utilise la recherche et qu'on tombe sur un tuto en bêta, on appelle ceci :

```
File "django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "zds/tutorial/views.py", line 2100, in find_tuto
    mandata = tutorial.load_dic(mandata)
  File "zds/tutorial/models.py", line 190, in load_dic
    mandata['get_introduction_online'] = self.get_introduction_online()
  File "zds/tutorial/models.py", line 270, in get_introduction_online
    "r")
```

Or, `get_introduction_online` n'est **pas** disponible puisque le tuto **n'est pas en ligne**, il est en bêta.

Ceci devrait permettre de retrouver le cas d'utilisation du bug et de le corriger.

Si besoin de précisions, me demander un accès Sentry.

**Comment by Eskimon** [comment]
et ce meme bug n'est il pas celui qui.fait planter les profils (en cliquant sur le bouton "beta" ? (jai plus la ticket en tete mais c'est assigne a @pierre_24

**Comment by SpaceFox** [comment]
Je ne sais pas, c'est à tester.

**Comment by pierre-24** [comment]
C'est effectivement réglé par #1322 normalement.

**Comment by SpaceFox** [comment]
C'est sans doute ça, à vérifier quand la PR sera mergée !

**Comment by firm1** [comment]
Fx'd
