### ISSUE TITLE
Erreur 500 / VariableDoesNotExist: Failed lookup for key [topic] in 

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1336]
Trouvé dans Sentry : on a un certain nombre d'erreurs qui correspondent à ce schéma :

> search/search.html
> VariableDoesNotExist: Failed lookup for key [topic] in u"[...]"

La key "topic" est toujours le titre d'un tuto.

L'erreur vient quand on essaie d'afficher des résultats dans **les parties de tutoriels**, exemples :
- http://zestedesavoir.com/rechercher/?q=blender&models=tutorial.part
- http://zestedesavoir.com/rechercher/?q=algorithmique&models=tutorial.part

Ces mot-clefs avec tous les autres types de résultats fonctionne.

L'erreur est lancée dans search/search.html at line 86 (celle qui dit "highligh...") :

```
{% else %}
     <a href="{{ result.object.get_absolute_url }}" class="topic-title-link navigable-link">
         <div class="topic-title">
             {% highlight result.object.topic.title with query html_tag "mark" %}
         </div>
 {% endif %}
         <div class="topic-subtitle">
```

Pour plus de détails, me demander un accès à Sentry.

**Comment by artragis** [comment]
[Cette PR](https://github.com/zestedesavoir/zds-site/pull/1331) doit avoir corrigé cette issue.

**Comment by SpaceFox** [comment]
OK, donc à vérifier quand la PR #1331 sera mise en prod (j'attends la #1322 pour ce faire).

**Comment by firm1** [comment]
Fx'd
