### ISSUE TITLE
Erreur 500 / AttributeError: 'WSGIRequest' object has no attribute 'user'

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1337]
Trouvée dans Sentry : on a pas mal d'erreurs de ce genre :

> zds.middlewares.profile in process_response
> AttributeError: 'WSGIRequest' object has no attribute 'user'

Toutes les requêtes sur lesquelles on a ces erreurs sont des requêtes qui n'auraient jamais dû êtres servies par Django (images etc.)

Donc quand dans zds/middlewares/profile.py  à la ligne 90 on arrive à cette condition :

``` python
if (settings.DEBUG or request.user.is_superuser) and 'prof' in request.GET:
```

il se peut que `request.user` n'existe pas et ça renvoie une erreur 500.

Réparation :
1. Faire en sorte que Django ne serve plus n'importe quoi (ticket #1338 )
2. Corriger le test pour vérifier l'existence de `request.user` avant d'y accéder

**Comment by gustavi** [comment]
Issue 1337 \o/

**Comment by gustavi** [comment]
Plus sérieusement il faut un if request.user avant (ou peut le mettre dans cette condition mais ça risque de surcharger).

**Comment by firm1** [comment]
Je précise que ce fichier (`zds/middlewares/profile.py`) n'est visible que sur le serveur, pour du profiling uniquement.

**Comment by SpaceFox** [comment]
> Je précise que ce fichier (`zds/middlewares/profile.py`) n'est visible que sur le serveur, pour du profiling uniquement.

Heu... on a un fichier hors conf qui n'est pas sur Git ? Alors la première chose à faire est l'y mettre !

**Comment by SpaceFox** [comment]
@firm1 je suppose que c'est toi qui a créé ce fichier et donc qui sait à qui il sert ?

Pourrais-tu au moins l'envoyer mettre sur le dépôt avec un commentaire pertinent quant à son utilité et son utilisation ? (comme ça quelqu'un pourra corriger le bug si tu n'as pas le temps de le faire).

**Comment by firm1** [comment]
> @firm1 je suppose que c'est toi qui a créé ce fichier et donc qui sait à qui il sert ?

Oui, il sert à faire du profiling après une MEP pour savoir si on eu des pertes/améliorations de perfs sur le serveur. Je le remonterai dans le dépot quand j'aurai accès au serveur. mais en soit celui qui a accès au serveur peut aller le chercher dans `zds/middlewares/` et rajouter l'intergiciel dans le `settings.py`. Rien de bien méchant

**Comment by firm1** [comment]
C'est mergé, je ferme.
