### ISSUE TITLE
Bugs de download pendant la validation

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1338]
Trouvée dans Sentry : on a pas mal d'erreurs de ce genre :

> zds.middlewares.profile in process_response
> AttributeError: 'WSGIRequest' object has no attribute 'user'

Toutes les requêtes sur lesquelles on a ces erreurs sont des requêtes qui n'auraient jamais dû êtres servies par Django (images etc.)

Il faut s'assurer que les fichiers image ne puissent pas arriver jusqu'aux processus Django (vraisemblablement une erreur de conf du fichier Nginx).

**Comment by firm1** [comment]
Le titre de l'issue est trompeur, il n'ya pas de problème de configuration de nginx ici. Les images statiques sont bien servient par nginx.

Le problème désigné par sentry ici est celui des images innacessibles dans les tutos. Pendant la publication d'un tutoriel, zds essaye de télécharger toutes les images d'un tutoriel (s'il ne les a pas en local). Dans sa tentative de téléchargement, si le lien d'une image est abolu (elle commence par "www", "http", "https"), il la télécharge. Mais il y'a visiblement certains cas, qui ne sont pas traités, et on se retrouve avec des urls invalides.

C'est en gros, le problème énnoncé ici par sentry.

**Comment by SpaceFox** [comment]
Je ne comprends plus du coup. Dans quel cas on arrive dans ce cas ? Au moment de la publication ?

**Comment by firm1** [comment]
> Au moment de la publication ?

[ouaip](https://github.com/firm1/zds-site/blob/dev/zds/tutorial/views.py#L2791)

**Comment by SpaceFox** [comment]
OK ; du coup comment corriger le problème ? Y'a des erreurs à catcher ? Des erreurs à remonter à l'utilisateur ?

**Comment by firm1** [comment]
Il faut mener une enquête

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé
