### ISSUE TITLE
Erreur 500 / zds.member.views in login_view

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1339]
Trouvée dans Sentry :

> zds.member.views in login_view
> UnicodeEncodeError: 'ascii' codec can't encode character u'[...]' in position [...]: ordinal not in range(128)

Erreur de gestion d'encodage très simple à reproduire :
1. Déconnectez-vous
2. Allez sur une page de membre dont le pseudo contient un caractère non-ASCII ([exemple](http://zestedesavoir.com/membres/voir/Anashka%C3%AFa/))
3. Cliquez sur "Connexion". On obtient une URL comme celle-ci http://zestedesavoir.com/membres/connexion/?next=/membres/voir/Anashka%C3%AFa/ et l'erreur 500 incriminée

Tout simplement, dans zds/member/views.py à la ligne 561 on a :

``` python
+ "?next=" + str(next_page)
```

et `str()` suppose de l'ASCII.

**Comment by artragis** [comment]
remplacer `str` par `slugify` fonctionnerait, non?

**Comment by Alex-D** [comment]
J'avais eu le problème sur append_to_get. J'ai tout simplement retiré le `str` et ça a fonctionné car la variable est déjà une String.

Après, je ne suis pas un expert mais je peux dire "Ca marche, c'est prouvé par la clinique QA".

**Comment by firm1** [comment]
> remplacer str par slugify fonctionnerait, non?

hum, non, ça renverrait juste l'utilisateur vers une 404

La solution d'Alex me semble bonne, si jamais elle ne marche pas, il suffirait d'encoder la variable next_page au lieu du str

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé
