### ISSUE TITLE
Compresser les images sur le site

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1341]
Les images du site ne sont pas du tout optimisés. Que se soit en back end ou en front-end, c'est assez lourd et ça n'aide pas à l'amélioration des performances de chargement.

Coté back-end, il faut se servir de [ce bout de doc](http://easy-thumbnails.readthedocs.org/en/latest/ref/optimize/) pour compresser sans perte et donc optimiser le chargement des pages.

Coté front-end, la priorité devrait être de compresser la sprite. L'idéal serait que gulp fasse la compression lors du build.

**Comment by Alex-D** [comment]
> compresser la sprite

C'est à dire ?

Il faut aussi refaire la version `@1x`, actuellement tout le monde est sur la version haute définition (dite `@2x` ou retina).

**Comment by pierre-24** [comment]
@firm1 : ces outils d'opti sont ils accessible facilement ? Sous question importante, SUR TOUT LES OS ? (sinon, c'est _prod_ seulement, parce que la config' m'as pas l'air d'aimer les gens sous Windows, dans le lien que tu proposes)

**Comment by firm1** [comment]
**Alex-D a écrit**

> C'est à dire ?

C'est à dire compresser les images sans perte, un peu comme si tu les passais sous [pngoptimiser](http://psydk.org/pngoptimizer).
La sprite même en @2x est déjà trop lourde, on pourrait réduire son poids d'au moins 20%, et les connexion lentes vous remercierons. Il faudra en faire de même pour la sprite en @1x.

L'idée étant d'automatiser tout ça par gulp, je n'ai pas encore regardé comment, mais ça devrait être faisable.

**pierre-24 a écrit**

> ces outils d'opti sont ils accessible facilement ? Sous question importante, SUR TOUT LES OS ?

Etant donné qu'on tourne en prod sur debian, il faudrait des outils qui compressent sans perte en priorité sur linux. Le travail a faire ici coté back-end est de benchmarker les outils dispo et stable sous linux de compression, et qui s'intègrent avec easy_thumbnails. Une fois ceci fais, il ne restera plus qu'a les installer en preprod, et rajouter dans le settings_prod les paramètres de `THUMBNAIL_OPTIMIZE_COMMAND`. Ce n'est pas une necessité pour le developpeur, et il n'aura pas besoin de ces outils au quotidien.

**Comment by Alex-D** [comment]
> et les connexion lentes vous remercierons

Please, je suis en 512kbps, je sais ce qu'est une connexion lente. Et ce qui est lent sur le site, c'est certainement pas les assets, mais le back qui met des plombes à générer et à envoyer le HTML...

Pour moi, l'optimisation de ces images est à faire par gulp à la génération du dossier dist, en rajoutant un filtre aux tâches concernées, et non à faire par le back avec easy_thumbnails (qui est fait pour faire des miniatures, en gros).

**Comment by SpaceFox** [comment]
Pour info, j'ai navigué sur le site une semaine en GPRS cet été (i.e. du
56k si tu captes à fond et que tu es seul sur l'antenne)... Eh bien ça
reste parfaitement utilisable. Lent, mais utilisable. Quelle que soit
l'optimisation, elle n'est pas urgente.

**Comment by firm1** [comment]
> Pour moi, l'optimisation de ces images est à faire par gulp à la génération du dossier dist, en rajoutant un filtre aux tâches concernées, et non à faire par le back avec easy_thumbnails (qui est fait pour faire des miniatures, en gros).

L'optimisation est a faire des deux coté. 
- gulp doit ,dans [cette task](https://github.com/zestedesavoir/zds-site/blob/dev/Gulpfile.js#L78) créer une sprite compréssée (sans perte).
- easy_thumbnails [est déjà paramétré en mode optimisé](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L164), il suffit d'installer sur la prod un outil d'optimisation d'images testé en amont et tout roule.

Que le site tourne sur des connexion de 12k c'est bien, mais si on peut optimiser, on optimise, ça ne mange pas de pain, ça fait gagner vitesse de chargement et surtout c'est l'affaire d'une **demie heure**.

Donc oui, elle n'est pas urgente, mais ça reste a faire.

**Comment by pierre-24** [comment]
Haw, vous tapez pas dessus ! 

Donc ... Oui, c'est important de compresser et d'optimiser, mais y'a surement plus important à faire avant (genre ... Taper un cache, parce que je suis d'accord avec Alex-D que certaines pages moulinent méchament et qu'à coté de ça, les images, c'est trois fois rien, preuve en est sur la page du forum : 

![screenshot](https://cloud.githubusercontent.com/assets/7889675/3855109/8d73ce28-1ee0-11e4-8dee-f8401065c6e4.png)

L'image qui met le plus de temps à charger, c'est le gif de l'avatar de Talus, c'est pour dire)

Y'à aussi le fait que l'opti' coté easy_thumbnail est uniquement unixienne/linuxienne, et l'opti coté gulb me semble l'être aussi (ou alors, on invente un bô script qui fait le _wrap_ entre les OS), donc on ajoute encore des dépendances (utiles, ceci dit), qui ne peuvent être mis en place que coté serveur. Ou je veux en venir avec tout ça ? C'est qu'on peut encore dire ce qu'on veut, c'est un machin qui doit être fait par un admin à un moment ou un autre, pas par quelqu'un d'autre, et que donc en soi, y'a aucune matière à débat : si c'est là, tant mieux, si c'est pas là, tant pis, mais ça ne touchera jamais le dev' ^^ (par contre, faudra bien faire attention à pas l'écraser).

PS : tout les belges qui ont pas de chance sont en connexion 512K. Mais de toute façon, j'ai les temps de génération des pages sur ma machine (et j'aurais pu être méchant et sortir le temps de génération de la page d'un chapitre d'un tuto, je suis à 4 secondes sur ma machine, qui est pas non plus toute vieille ... Mais, ça, je sais qu'on cherche à faire des efforts :) )

**Comment by firm1** [comment]
Pour information ici, en rajoutant ceci dans le settings_prod (actuellement sur la preprod).

``` python
THUMBNAIL_OPTIMIZE_COMMAND = { 
'png': '/usr/bin/optipng {filename}',
 'gif': '/usr/bin/optipng {filename}', 
'jpeg': '/usr/bin/jpegoptim {filename}' 
}
```

Et en lançant les commandes :

``` bash
apt-get install optipng
apt-get install jpegoptim
```

Ça roule, les images ajoutées dans la galerie sont compressée sans perte.

**Comment by Alex-D** [comment]
Le front compresse déjà les sprites, donc a priori c'est déjà tout bon. Il ne manque, à la limite, que le `@1x` mais tout le reste est good.

**Comment by firm1** [comment]
> Le front compresse déjà les sprites,

C'est pas ce que me dis Google pagespeed.
Le 25 août 2014 19:08, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by sandhose** [comment]
Lors du build gulp, on passe toutes les images par [gulp-imagemin](https://github.com/sindresorhus/gulp-imagemin), qui utilise [différents plugins](https://github.com/imagemin/imagemin#plugins) pour optimiser les images en fonction du format.

Alors effectivement, on peut éventuellement optimiser la génération du sprite (qui est faite par [spritesmith](https://github.com/Ensighten/spritesmith)), et utiliser l'algorithme `binary-tree` au lieu de l'algorithme `top-down`, qui est celui par défaut.

C'est possible aussi que l'optimisation des images se fasse _avant_ la génération du sprite, ce qui fait qu'il n'est pas tout à fait optimisé.

Bon bah pour le coup, _PR incoming_

**Comment by Alex-D** [comment]
Juste pour info, j'avais déjà fait les tests d'optimisation décrits par @sandhose mais ça ne changeait rien du tout : du vide (transparent) ça ne pèse rien sur une image, donc l'optimisation se joue à quelques octets et beaucoup de problèmes d'alignements VS quelques octets de plus (mais vraiment peu) et pas de soucis en retina.

> C'est pas ce que me dis Google pagespeed.

Il ne faut pas croire Google PageSpeed tout le temps non plus. On est pas à 1ko près. A priori @sandhose n'avait pas configuré le truc tip top (c'est assez chiant pour trouver le bon compromis) et donc ça devrait aller mieux après ses petites modifications si j'ai bien suivi.

**Comment by sandhose** [comment]
Par rapport au PageSpeed, il râle juste à cause du sprite et des uploads. La PR #1396 optimise ce sprite

**Comment by firm1** [comment]
A faire sur la prod (ce n'est pas encore le cas en sachant que c'est déjà sur la preprod) , donc c'est coté Infra.

> Pour information ici, en rajoutant ceci dans le settings_prod (actuellement sur la preprod).
> 
> ``` python
> THUMBNAIL_OPTIMIZE_COMMAND = { 
> 'png': '/usr/bin/optipng {filename}',
>  'gif': '/usr/bin/optipng {filename}', 
> 'jpeg': '/usr/bin/jpegoptim {filename}' 
> }
> ```
> 
> Et en lançant les commandes :
> 
> ``` bash
> apt-get install optipng
> apt-get install jpegoptim
> ```
> 
> Ça roule, les images ajoutées dans la galerie sont compressée sans perte.

**Comment by sandhose** [comment]
Qu'en est-il des images déjà générées ? Est-ce qu'elles seront optimisées automatiquement, ou faut le faire manuellement ?

**Comment by firm1** [comment]
Les images déjà générés resteront non optimisées.

**Comment by sandhose** [comment]
Hum, ok... Au cas où, il est possible de tout optimiser d'un coup sans avoir a le faire fichier par fichier avec [imagemin](https://www.npmjs.org/package/imagemin). C'est le même outil qu'on utilise pour l'optimisation des images côté front

**Comment by firm1** [comment]
C'est pas aussi trivial. On optimise pas la source de l'image mais la
version rendue.

**Comment by Alex-D** [comment]
Qu'est-ce qui empêche de lancer un script sur le dossier qui réoptimise chaque image ?

**Comment by firm1** [comment]
Ce n'est pas possible tout simplement.
Le 3 sept. 2014 20:01, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by SpaceFox** [comment]
Une question de volumétrie, ou autre chose ?

**Comment by firm1** [comment]
Compresser la source des images ne donne aucune garantie de la
disponibilité des miniatures existantes.

**Comment by sandhose** [comment]
J'ai pas compris le problème. Pour moi, l'idée c'était juste de lancer un script qui cherche _toutes_ les images uploadées (dossier /media de mémoire), et de les passer par imagemin pour les optimiser...

**Comment by Alex-D** [comment]
Ce que je disais, c'est tout comme @sandhose du coup je ne comprends pas où se situe le problème. A priori toutes les images sont dans un même dossier (originales et redimensionnées) donc peut lancer un truc qui couvre absolument toutes les images (originales et miniatures et tout), non ?

**Comment by SpaceFox** [comment]
Je ne comprends plus rien non plus. @firm1 je crois qu'il est temps de faire une explication complète.

**Comment by firm1** [comment]
La flemme là de me refarcir la doc : http://easy-thumbnails.readthedocs.org/en/2.1/

**Comment by Alex-D** [comment]
Là on ne dit pas de repasser par easy-thumbnails mais de faire tourner un script externe (genre avec node.js) qui va compresser l'existant, après easy continue son taf pour la suite des événements.

**Comment by Alex-D** [comment]
C'est fait pour ce qui est du sprite côté front avec la #1396 de @sandhose que je viens de merger.

**Comment by SpaceFox** [comment]
Il reste des trucs à faire ici ?

**Comment by Alex-D** [comment]
~~Oui pour le front.~~

**Comment by Alex-D** [comment]
Correction : pour le front c'est fini, à vous de voir pour le back.

**Comment by firm1** [comment]
> Il reste des trucs à faire ici ?

Quelqu'un a t-il fait ce qui est indiqué [ici](https://github.com/zestedesavoir/zds-site/issues/1341#issuecomment-54322349) ?

**Comment by sandhose** [comment]
**Toutes** les images contenues dans assets/images et assets/smileys sont optimisées lors du build gulp (via imagemin), avant d'être copiées respectivement vers dist/images et dist/smileys. Il y avait une issue par rapport à l'optimisation du sprite (le dist/images/sprite@2x.png), mais elle a été reglé. Toutes les images gérées par le front sont donc maintenant optimisées.

**Comment by gustavi** [comment]
On en est où ici ? cc @SpaceFox et les gens qui ont accès à l'infra.

**Comment by SpaceFox** [comment]
C'est nulle part, c'est à ajouter à la liste des trucs à faire pour la release sinon ça ne sera jamais fait.

**Comment by SpaceFox** [comment]
C'est fait !
