### ISSUE TITLE
Erreur 500 lors du retour a l'accueil

### ISSUE THREAD

**Issue by QuanticPotato** [zestedesavoir/zds-site#1343]
Ca m'embête un peu de poster ce bug (j'imagine qu'il a déjà été reporté), mais si ca peut aider le site ;). 
Donc voila j'ai tout simplement eu une erreur 500 en revenant sur la page d'accueil (en cliquant sur l'image "Zeste de savoir" en haut à gauche). Je revenais de cette page : http://zestedesavoir.com/forums/sujet/769/cherchez-lerreur-linux-edition/?page=9#p14938
Je ne peux rien vous dire de plus sur mon historique (je ne m'en souviens pas et je ne pensais pas tomber sur cette erreur x) ).

**Comment by ShigeruM** [comment]
Et moi je suis tombé dessus en tapant l'adresse directement. Serait-ce lié
à la re-publication du tuto Photoshop ?

**Comment by QuanticPotato** [comment]
En tout cas je viens de retomber dessus (de la même facon, en quittant http://zestedesavoir.com/forums/sujet/381/les-bugs-ameliorations-ou-suggestions-deja-reportes/). Je n'ai eut aucune utilisation spéciale, simplement de la lecture de sujets (forum).

**Comment by QuanticPotato** [comment]
En fait pour reproduire le bug (chez moi du moins), il suffit simplement de cliquer plein de fois sur l'image Zeste de Savoir (en haut à gauche), et l'erreur va survenir au bout d'un moment.

Ce ne serait pas dûe à un message de clem (je n'ai pas regardé le code, mais c'est la seul chose qui change sur la page) ?

**Comment by Axylium** [comment]
Un tuto ou un article est entrain d'être publié à mon avis, c'est ce qui cause ces erreurs.

**Comment by ChantyTaguan** [comment]
Yep, c'est moi qui tente de publier un tuto et qui me mange des erreurs 500.

A un moment ça va marcher, ou j'abandonne ?

**Comment by Eskimon** [comment]
abandonne. Ca va juste planter les workers gunicorn qui font tourner le site :D

**Comment by firm1** [comment]
Juste pour rappeler que [cette PR](https://github.com/zestedesavoir/zds-site/pull/1322) est censé résoudre ces problèmes d'erreurs 500.

Tant qu'on ne la passe pas en QA puis MEP, on se mangera toujours dans erreur 500.

**Comment by pierre-24** [comment]
@firm1 : la plupart, oui, mais je ne touche pas à la validation, normalement. Enfin, bref, QA qui veut (artragis a du abandonner pour des raisons d'encodage UTF-8).

**Comment by firm1** [comment]
> @firm1 : la plupart, oui, mais je ne touche pas à la validation

Je crois que tu sous estime un peu ta PR, crois moi, en lisant les logs, ta PR corrige les soucis.

**Comment by pierre-24** [comment]
Je ne peux pas lire les logs, mais je te crois sur parole ^^

**Comment by SpaceFox** [comment]
Gunicorn redémarré.

**Comment by SpaceFox** [comment]
Attention, les erreurs rencontrées lors du plantage suite à la publication d'un tuto ne sont pas celles rencontrées auparavant.

Cf les logs, qui sont assez explicites.

MP pour me demander un accès aux logs.

**Comment by pierre-24** [comment]
S'il s'agit de l'erreur mentionnée sur IRC (zds/tutorial/models.py ? in load_json_for_public ligne 213), alors si, c'est entre autre le sujet de cette PR :)

**Comment by SpaceFox** [comment]
Tant mieux :)

**Comment by firm1** [comment]
Fx'd

**Comment by cgabard** [comment]
Il faudrait réouvrir ce ticket. nohar a tenté de publier un tuto qui a re-générer ce genre de soucis ce matin.

**Comment by SpaceFox** [comment]
Fait.

**Comment by Eskimon** [comment]
On a une idee de vers quelle heure ca c'est passe histoire de pas éplucher tout les logs ?

**Comment by SpaceFox** [comment]
Utilise Sentry, y'a pas douze milliards de logs dessus.

**Comment by cgabard** [comment]
Vers 10:42 environ
(c'est à cette heure que nohar s'est plain de l'erreur 500 à la publi).

C'est le tuto qu'il devait publier hier je crois qui a posé prob.

**Comment by Eskimon** [comment]
Ca doit etre ca alors:
`IOError: [Errno 2] No such file or directory: u'/opt/zdsenv/ZesteDeSavoir/tutoriels-public/286_la-memoire/1874_introduction/introduction.md'`

Et la stacktrace qui va bien:

```
Stacktrace (most recent call last):

  File "django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "zds/member/decorator.py", line 20, in _can_write_and_read_now
    return func(request, *args, **kwargs)
  File "django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "zds/tutorial/views.py", line 354, in valid_tutorial
    (output, err) = MEP(tutorial, tutorial.sha_validation)
  File "zds/tutorial/views.py", line 2948, in MEP
    out_file = open(os.path.join(tutorial.get_prod_path(), fichier), "w")
```

**Comment by firm1** [comment]
Ce sont des tutoriels qui font parti des tutoriels importés pendant la beta publique. Et au vu des logs, il me semble cassé de l'intérieur. On ne peut plus rien faire pour ce tutoriel, il faudra le recréer.

**Comment by Eskimon** [comment]
Le problème venant des tutos, ce ticket doit-il rester ouvert ?

**Comment by gustavi** [comment]
Il semblerait qu'il reste très peu d'erreur lié à ce problème et elle sont fixés (3 erreur sur la dernière semaine).

Si c'est les tuto importés de la beta publique alors il faudrait les fixer un par un non ? Je vois pas comment dans le back on peut éviter ça si le problème vient des tutos eux même.

**Comment by cgabard** [comment]
En effet mais il reste une question : comment peut on fixer les tutos qui
font planter la home ?

Christophe.

2014-10-28 10:26 GMT+01:00 Laville Augustin notifications@github.com:

**Comment by gustavi** [comment]
@cgabard je viens juste de reporter l'erreur qui n'est pas la même : https://github.com/zestedesavoir/zds-site/issues/1639

**Comment by Eskimon** [comment]
Toujours besoin de ce ticket ? Quelles sont les actions a faire ?

**Comment by firm1** [comment]
Ce ticket n'est qu'une mauvaise conséquence d'un ou plusieurs autres problèmes.

Il vaut mieux fermer ici car ça fait doublons avec les autres tickets de bugs.
