### ISSUE TITLE
[UX] Amélioration de l'expérience utilisateur - Formulaire de connexion

### ISSUE THREAD

**Issue by MikeElghali** [zestedesavoir/zds-site#1345]
Bonjour,

Je suis nouvellement inscrit sur zds, et je souhaite apporter ma contribution à l'amélioration du site.
Je vous expose donc mes idées d'amélioration concernant l'ergonomie, le graphisme ou la typographie.
## Le formulaire de connexion

![connexion zeste de savoir 2014-08-07 06-45-33](https://cloud.githubusercontent.com/assets/2301050/3837415/c2da5c2e-1ded-11e4-8268-877edae80c29.png)
#### Idées d'amélioration :
- Le label `Identifiant` n'est pas clair : il peut s'agir soit de l'adresse électronique soit du nom d'utilisateur. 
  **Correction applicable** : `Nom d'utilisateur`
- Le label `Mot magique` n'est pas homogène sur l'ensemble du site : nous retrouvons `mot de passe` ailleurs dans les paramètres du profil de l'utilisateur.
  **Correction applicable** : `Mot de passe`
- Le label `Connexion automatique` n'est pas pertinent : il s'agit de la durée de la session et non de l'action de se connecter.
  **Correction applicable** : `Se souvenir de moi`
- Le bouton `Annuler` n'est ici pas pertinent : le formulaire de connexion est la première étape. Il n'y a aucune action encore entrepris de la part de l'utilisateur.
  **Correction applicable** :  suppression du bouton annuler
- L'astérisque en rouge signalant que le champ est requis pour la soummission du formulaire n'est pas pertinent dans un formulaire de connexion : il est communément admis que pour se connecter il faut saisir obligatoirement un identifiant et un mot de passe.
  **Correction applicable** :  suppression des astérisques

Cordialement,
Jaoued

**Comment by Alex-D** [comment]
D'accord pour tous les points, sauf le dernier : c'est comme ça sur tout le site, on ne va pas s'amuser à retirer ces astérisques exclusivement sur cette page.

**Comment by MikeElghali** [comment]
Bonjour,

Effectivement, les astérisques sont présents sur les autres formulaires du site.

Pour la v2, il serait intéressant d'intégrer les dernières recherches en terme d'expérience utilisateur, notamment la suppression de ces astérisques au profit d'une indication pour les champs optionnels.

De manière classique, avec les astérisques : 
`____________________*`
`____________________*`
`____________________`
`____________________*`

UX améliorée, sans les astérisques : 

`____________________`
`____________________`
`____________________(optionnel)`
`____________________`

Avec la manière classique, les utilisateurs s'empresseront de remplir tous les champ obligatoires et laisseront les champs optionnels vide.

Avec la deuxième approche, les utilisateurs rempliront les champs requis mais seront davantage poussés à remplir les autres. C'est une approche dite volontaire. Étant donné que dans la deuxième approche, l'utilisateur n'est pas contraint visuellement de remplir un champ donné, il sera plus à même de prendre son temps pour remplir les autres.

Cordialement,
Jaoued

**Comment by Alex-D** [comment]
Merci pour tes remarques, j'ai appliqué ce qui était faisable par rapport à notre architecture.

Mergé, je ferme.
