### ISSUE TITLE
[UX] Amélioration de l'expérience utilisateur - Boutons d'action

### ISSUE THREAD

**Issue by MikeElghali** [zestedesavoir/zds-site#1346]
Bonjour,

Je suis nouvellement inscrit sur zds, et je souhaite apporter ma contribution à l'amélioration du site.
Je vous expose donc mes idées d'amélioration concernant l'ergonomie, le graphisme ou la typographie.
## Les boutons d'action

URL : http://zestedesavoir.com/membres/parametres/profil/
![mon profil paramtres zeste de savoir 2014-08-07 06-36-36](https://cloud.githubusercontent.com/assets/2301050/3837630/3e877248-1df4-11e4-80a0-661a34758d0a.png)

URL : http://zestedesavoir.com/membres/parametres/user/
![pseudo et e-mail parametres zeste de savoir 2014-08-07 06-37-40](https://cloud.githubusercontent.com/assets/2301050/3837634/5a492ca6-1df4-11e4-9cfe-5001f58e1589.png)
#### Idées d'amélioration :
- Le nom du bouton `Editer mon profil` porte à confusion : doit-on cliquer dessus pour pouvoir l'éditer ou pour sauvegarder ?
  **Correction applicable** : Renommer en `Sauvegarder`
- Le nom du bouton `Changer` peut etre plus générique en ne se basant pas sur son contexte : dès qu'il s'agit de sauvegarder une **modification** d'un formulaire le nom du bouton n'a plus besoin de s'adapter au contexte. Ceci a pour avantage d'alleger le travail cognitif de l'utilisateur.
  **Correction applicable** : Renommer en `Sauvegarder`
- Le bouton `Annuler` n'est pas pertinent : il redirige simplemement vers la page d'accueil et n'annule donc pas une action entrepris dans le formulaire.
  **Correction applicable** : Supprimer le bouton `Annuler`
- Les boutons ayant pour fonction la sauvegarde des données d'un formulaire doivent être différenciés au niveau de la couleur de fond.
  **Correction applicable** : appliquer un fond de couleur vert en adéquation avec le reste du site
- Les boutons d'action critiques tel que l'annulation ou la suppression doivent être moins visible que les autres.
  **Correction applicable** : `background-color: transparent; text-decoration: underline`

Cordialement,
Jaoued

**Comment by Alex-D** [comment]
Info : la plupart des boutons sont gérés dans les `forms.py` du back.

> Correction applicable : appliquer un fond de couleur vert en adéquation avec le reste du site

Nulle part il n'y a du vert pour les boutons de validation, tout est bleu foncé. Donc je ne comprend ni le gain ni le "avec le reste du site".

> Les boutons d'action critiques tel que l'annulation ou la suppression doivent être moins visible que les autres.

En fait, il y a déjà le style `.btn-grey` qui est fait pour ça.

**Comment by MikeElghali** [comment]
Bonjour,

Ce que je voulais dire c'est qu'il est préférable de différencier les boutons d'action qui agisse sur les données de l'utilisateur. et les deux couleurs les plus connus sont la nuance de rouge pour tout ce qui est suppression de données et la nuance de vert pour la sauvegarde de données.

L'utilisateur sait ainsi, en un clein d'oeil, le rôle du bouton concerné.

Ce n'est pas obligatoire, mais tout comme le lien vers la page d'accueil sur le logo, l'utilisateur est tout a fait habitué à cela.

Pour le deuxième point, j'ai testé votre classe, et c'est nickel.

Cordialement,
Jaoued

**Comment by Alex-D** [comment]
Voilà, les correctifs recommandés ont été globalement appliqués. Merci pour tes remarques.

Mergé, je ferme.

**Comment by Eskimon** [comment]
Le vert pétant comme ca pour les boutons est franchement bien bien moche... Le bleu d'avant était vraiment plus élégant...
Je vois pas pourquoi un bouton de connexion ou d'enregistrement devrait être absolument vert pour être compris, le texte est quand même la pour ca non ?

**Comment by MikeElghali** [comment]
Tu as un screen pour que je regarde ça ?

C'est une convention. et c'est bien plus visible que le texte. 

Le tout est de mettre la couleur de nuance vert en adéquation avec la nuance des autres couleurs.

Je pourrai aider si j'ai un screen de ce bouton.

**Comment by Alex-D** [comment]
J'ai mis le même vert que celui du karma, sinon ça élargit encore la palette et ça va devenir le carnaval. Au pire on test, si c'est vraiment pas terrible on reviendra au bleu.
