### ISSUE TITLE
[UX] Amélioration de l'expérience utilisateur - Navigation

### ISSUE THREAD

**Issue by MikeElghali** [zestedesavoir/zds-site#1347]
Bonjour,

Je suis nouvellement inscrit sur zds, et je souhaite apporter ma contribution à l'amélioration du site.
Je vous expose donc mes idées d'amélioration concernant l'ergonomie, le graphisme ou la typographie
## La navigation

![mon profil parametres zeste de savoir 2014-08-07 07-21-44](https://cloud.githubusercontent.com/assets/2301050/3838037/16fb115a-1dfc-11e4-9095-99d6d01c4f0f.png)

![jaoued membres zeste de savoir 2014-08-07 06-39-46](https://cloud.githubusercontent.com/assets/2301050/3838039/1c80f400-1dfc-11e4-92ec-a1c900763f71.png)

![tous les tutoriels tutoriels zeste de savoir 2014-08-07 08-24-55](https://cloud.githubusercontent.com/assets/2301050/3838045/2ec5857c-1dfc-11e4-9d3a-91e9976349b3.png)

![php tutoriels zeste de savoir 2014-08-07 08-25-39](https://cloud.githubusercontent.com/assets/2301050/3838048/32ab2e58-1dfc-11e4-92e0-7f61f5b31f72.png)

![dveloppez votre site web avec le framework symfony2 tutoriels zeste de savoir 2014-08-07 08-36-57](https://cloud.githubusercontent.com/assets/2301050/3838091/5466a864-1dfd-11e4-80eb-536f02bb6ff3.png)

![bienvenue sur zeste de savoir messagerie prive zeste de savoir 2014-08-07 07-24-43](https://cloud.githubusercontent.com/assets/2301050/3838095/70f64b06-1dfd-11e4-9de2-d4a177e42437.png)
#### Idées d'amélioration :
- Le nommage des liens n'est pas homogène : nous retrouvons, par exemple, `Profil` et `Mon profil` **Correction applicable** : renommer de la même façon tous les liens qui dirigent vers la même page.
- Le fil d'Ariane n'est pas fidèle à l'arborescence du menu : par exemple, si nous cliquons sur le lien `PHP` du menu `TURORIELS` le fil d'Ariane affiche `Accueil -> Tutoriels -> PHP`.
  **Correction applicable** : ajouter le noeud parent pour avoir `Accueil -> Tutoriels -> Web -> PHP`
- De même lorsque l'on clique sur un tutoriel, nous ne voyons pas à quelle catégorie il appartient.
  **Correction applicable** : ajouter les noeuds parents pour avoir par exemple `Accueil -> Tutoriels -> Web -> PHP -> Développez votre site web avec le framework Symfony2`
- Le gabarit du site n'est pas toujours cohérent dans son contenu : la zone de navigation est définie sur la gauche. L'utilisateur s'attend donc à retrouver à cet emplacement des liens de navigation. Or, il y trouve parfois des boutons d'action ce qui n'est donc pas pertinent.
  **Correction applicable** : déplacer les boutons d'actions en dehors de la zone de navigation. De préférence en haut de la section à laquelle elle s'applique.

Cordialement,
Jaoued

**Comment by Alex-D** [comment]
> Or, il y trouve parfois des boutons d'action ce qui n'est donc pas pertinent.

Sur certaines pages, il y a 15 - 20 liens. Et si on les retire de la sidebar, elle est vide ou presque. Sur mobile, ça a l'avantage d'être accessible tout le temps, sans encombrer la page avec des boutons pas utilisés souvent.

Si tu as une idée de _où mettre tous ces boutons d'actions_ on peut y réfléchir, mais à l'heure actuelle, c'est la solution la plus souple que j'ai pu trouver.

**Comment by MikeElghali** [comment]
Bonjour,

Avez-vous une URL pour que je puisse voir un exemple de page comportant de nombreux liens ?

Cordialement,
Jaoued

**Comment by Alex-D** [comment]
Il faut être admin et être sur un tutoriel et là on a un florilège de boutons d'actions.

Exemple : 

![Tutoriel en beta et en validation](http://storage.alex-d.fr/zestedesavoir/capture-looong-actions.jpg)

**Comment by Alex-D** [comment]
J'ai réfléchi au fil d'Ariane, le soucis est que ce sont des tags catégorisés, il est donc incohérent de ranger un tutoriel dans un de ces tags de façon "prioritaire".

Pour la sidebar, comme énoncé, rien ne changera à cause du nombre de boutons disponibles.

Pour le fil d'Ariane d'un tag, cela viendra également avec le temps, mais il sera possible de filtrer par la catégorie mère uniquement puis de descendre en filtrant davantage. On pourra retrouver un même tag dans plusieurs catégories, et donc afficher Site Web alors qu'on regarde une techno qui n'est pas uniquement dédiée au Web, cela devient incompréhensible pour l'utilisateur si on commence à entre-mêler les choses.

Finalement je ne retiendrais que le premier point.

**Comment by Alex-D** [comment]
C'est fait, mergé, donc on ferme. Merci à toi pour tes remarques :)

**Comment by MikeElghali** [comment]
Bonjour,
Bravo à toi et ton équipe pour le travail que vous faites. 
Je suis pas mal pris en ce moment mais dès que j'aurai un moment de libre je reviendrai vers vous pour de nouvelles idées / remarques.

Bon courage !
