### ISSUE TITLE
Ajouter la date de naissance au formulaire d'adhésion à l'association?

### ISSUE THREAD

**Issue by Fumble** [zestedesavoir/zds-site#1349]
A voir mais cela pourrait être utile pout au moins pouvoir prévoir de possibles litiges.
D'après la loi, un mineur peut adhérer à une association loi 1901 avec l'accord verbale ou tacite de ses parents.

Ma demande n'a pas pour but de "fliquer" les futurs mambres mais juste de savoir dans quels cas on pourra potentiellement avoir les parents qui viennent nous demander ce que fait leur enfant dans notre association.

Pensez-vous que c'est donc utile d'avoir cette donnée sur nos ashérents ou pas?

L'explication prise sur http://www.associations.gouv.fr/642-capacite-d-etre-adherent.html

Le mineur non émancipé reste sous l’autorité de ses parents jusqu’à sa majorité ou son émancipation "sauf dans le cas où la loi ou l’usage autorise les mineurs à agir eux-mêmes". (art. 389-3 et 450 du code civil).

Ainsi en est-il du droit d’adhésion du mineur. "Le mineur qui adhère à une association est présumé avoir reçu une autorisation verbale de ses parents. La jurisprudence considère même que cette autorisation peut être tacite et résulter du fait que les parents ne sont pas opposés à l’exercice de la vie associative (TGI Seine 13.02.65)

D’ailleurs, dans le cas du mineur non émancipé, une réponse ministérielle confirme la possibilité de faire partie d’une association : " l’article 1er de la loi du 1er juillet 1901 dispose que l’association est régie quant à sa validité par les principes généraux du droit applicables aux contrats et obligations, principes selon lesquels les mineurs sont incapables de contracter (C. civil, art. 1108 et 1124). Mais, des travaux préparatoires de la même loi, il résulte que les mineurs peuvent faire partie d’associations avec l’autorisation tantôt écrite et expresse, tantôt tacite et présumée de leurs parents ou tuteurs " (Rép. min. n° 19419 JOANQ du 28 août 1971, p. 4019).

S’agissant du versement d’une cotisation par un mineur non émancipé, il est d’usage de considérer que celui-ci est possible sans autorisation du titulaire de l’autorité parentale, dès lors que le montant de la cotisation n’excède pas ce qu’il est convenu d’appeler " argent de poche " (en cas de litige, l’appréciation relèvera du juge du fond).

**Comment by Alex-D** [comment]
Ceci a été fait dans la #1406, je ferme :)
