### ISSUE TITLE
Liens vers les fiches de Wikimedia

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#1351]
Je l'ai [signalé sur le forum](http://zestedesavoir.com/forums/sujet/984/les-liens-vers-wikimedia-ne-fonctionnent-pas/?page=1#p15299) pour que la visibilité soit maximal, mais je viens aussi le signaler ici.

Les liens vers les **fiches** détaillées du Commons de Wikimedia, ne fonctionnent pas.

Par-exemple ce genre d'URL ne passe pas : `http://commons.wikimedia.org/wiki/File:Swallow_flying_drinking.jpg`

À mon avis, zMD aimerait l'afficher en image, mais ne comprend pas que c'est un lien et non une image du fait que Wikimedia mettent l'extension de cette dernière à l'URL.

(ping @cgabard)

**Comment by Alex-D** [comment]
J'ai mis ça sur le bon dépôt : [zMD#47](https://github.com/zestedesavoir/Python-ZMarkdown/issues/47)
