### ISSUE TITLE
ZdS ne se lance plus sous Windows

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1353]
Comme vu dans la PR #1322 ZdS ne se lance plus sous Windows mais crache une erreur :

```
Validating models...

0 errors found
Unhandled exception in thread started by <function wrapper at 0x0000000003F33B38>
Traceback (most recent call last):
  File "C:\Users\SpaceFox\.virtualenvs\zdsenv\lib\site-packages\django\utils\autoreload.py", line 93, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\SpaceFox\.virtualenvs\zdsenv\lib\site-packages\django\core\management\commands\runserver.py", line 104,
 in inner_run
    now = now.decode('utf-8')
  File "C:\Users\SpaceFox\.virtualenvs\zdsenv\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfb in position 2: invalid start byte
```

Le bug n'est pas présent sous Linux, et reste présent si on remonte dans les versions aussi loin que le tag v1.0-RC1 (base neuve, fichiers .pyc supprimés), qui lui fonctionnait très bien sous Windows à l'époque.

Ceci ressemble donc très fortement à un bug apporté par l'une de nos dépendances.

**Comment by SpaceFox** [comment]
Vu que l'octet fautif est toujours 0xbf et qu'il correspond bien [à un caractère unicode valide](http://www.fileformat.info/info/unicode/char/bf/index.htm), j'ai recherché les occurrences de ce caractère dans notre base de code (fichiers .py)
- Dans le code lui-même : absent (au moins en tant que caractère unicode "¿")
- Dans les dépendances, il est présent 8 fois,toujours dans pygal mais à chaque fois dans des tests :

```
Search "¿" (8 hits in 2 files)
  C:\Users\SpaceFox\.virtualenvs\zdsenv\Lib\site-packages\pygal\test\test_config.py (2 hits)
    Line 267:     line.no_data_text = u("þæ®þæ€€&ĳ¿’€")
    Line 269:     assert q(".text-overlay text").text() == u("þæ®þæ€€&ĳ¿’€")
  C:\Users\SpaceFox\.virtualenvs\zdsenv\Lib\site-packages\pygal\test\test_graph.py (6 hits)
    Line 245:         'label': u('{\}Â°ĳæð©&×&<—×€¿_…\{_…')
    Line 256:     chart.x_labels = [u('&œ'), u('¿?'), u('††††††††'), 'unicode <3']
    Line 267:         'label': eval("u'{\}Â°ĳæð©&×&<—×€¿_…\{_…'")
    Line 278:     chart.x_labels = eval("[u'&œ', u'¿?', u'††††††††', 'unicode <3']")
    Line 289:         'label': eval("'{\}Â°ĳæð©&×&<—×€¿_…\{_…'")
    Line 300:     chart.x_labels = eval("['&œ', '¿?', '††††††††', 'unicode <3']")
Search "¿" (0 hits in 0 files)
```

J'étends ma recherche.

**Comment by SpaceFox** [comment]
Recherche binaire : les seules séries d'octets "BF" que je trouve sur l'intégralité du projet, c'est soit des images, soit des fichiers python compilés...

**Comment by SpaceFox** [comment]
Quant au dossier d'installation du Virtualenv rien de mieux : les rares fichiers non-binaires qui contiennent cette séquence d'octets sont des fichiers .py, soit à cause d'un BOM (qui ne change rien une fois supprimé), soit parce que c'est des chaînes de caractères dans une langue bizarre et en général dans des tests justement pour tester ces cas particuliers...

**Comment by SpaceFox** [comment]
Bon. Je me suis rappelé que "python"  = "on te file les sources" et "y'a rien à compiler" donc "tu peux hacker comme un gros porc".

Et là, c'est le drame !

Il suffit donc de lire le message d'erreur, qui nous parle du fichier `C:\Users\SpaceFox\.virtualenvs\zdsenv\lib\site-packages\django\core\management\commands\runserver.py` ligne 107. Qu'est-ce qu'on y trouve ?

``` python
        now = datetime.now().strftime('%B %d, %Y - %X')
        if six.PY2:
            now = now.decode('utf-8')
```

On plante sur la dernière ligne : on ne peut pas décoder le "now". Que peut-il donc contenir ?! Améliorons le script !

``` python
        now = datetime.now().strftime('%B %d, %Y - %X')
        if six.PY2:
            print 'LOOK : '
            print now
            print 'SEE ?'
            now = now.decode('utf-8')
```

Nouvelle sortie du programme !

```
LOOK :
ao¹t 09, 2014 - 00:56:41
SEE ?
```

Maintenant, un peu d'histoire : on bosse à plusieurs sur ce projet depuis, disons, mars.
- mars
- avril
- mai
- juin
- juillet
- août

Rien ne vous saute aux yeux ?

Vraiment ?

"Août", c'est le premier nom de mois à contenir un caractère non-ASCII. Le truc est tellement mal branlé (et n'a été testé, comme d'hab je suppose, **que** en anglais) qu'il t'explose à la gueule dès que tu as un caractère non-ASCII dans ton nom de mois.

On notera aussi l'intelligence de forcer le format de date US (mois jour année) mais en gardant la locale du PC pour l'affichage.

Bref, combo Windows + caractères non-ASCII mal gérés par les américains + cas rare = boum !

**Correction simple**

On attend septembre :D

**Vraie correction**

On devrait pouvoir hacker le fichier en attendant d'avoir une vraie correction. Par contre, qui contacter pour faire ça ? Mystère...

**Comment by firm1** [comment]
> On attend septembre

:dancer: 

Je suis plié devant ce rapport ... ZdS c'est magique, Microsoft et Django nous demandent d'arrêter de bosser en été, et d'attendre la rentrée.

**Comment by SpaceFox** [comment]
Tu noteras qu'on ne peut pas bosser en hiver non plus (décembre et février) :D

**Comment by psycopy** [comment]
Bonsoir,

Le caractère "û" C3BB existe en UTF-8, mais pas 0xFB (c'est de l'ISO-8895-1). À priori le fichier n'est pas encodé en UTF-8,

**Comment by SpaceFox** [comment]
Yep, c'est ça : Python s'attends à ce que le système renvoie une chaîne UTF8 pour la date, mais Windows s'en bat les noix.

Je ne trouve pas de moyen de demander à Windows de nous sortir ça en UTF8... on peut toujours imaginer que les développeurs sous Windows utilise l'anglais (locale = 'eng' dans le settings.py), mais je préfère faire des tests avant de faire une PR à ce sujet.

**Comment by SpaceFox** [comment]
Bilan des courses : tout ça parce qu'on force, dans le settings.py :

``` python
if platform.system() == "Windows":
    locale.setlocale(locale.LC_TIME, 'fra')
else:
    locale.setlocale(locale.LC_TIME, 'fr_FR.UTF-8')
```

On peut demander de l'UTF8 explicitement avec Linux (et Mac ?), mais pas Windows.

Ce soir on en est là :
- On a un cas vraiment invraisemblable, puisqu'il faut, pour que ça plante :
  1. Que l'utilisateur utilise la localisation (setting `USE_L10N = True`) avec une locale susceptible de lui sortir des caractères non-ASCII
  2. **et** que le générateur (ici Windows) sorte autre chose que de l'UTF8
  3. **et** que dans ces caractères il y ait des séquences interdites en UTF8 (par exemple, aujourd'hui en russe, ça "marche" : ça affiche probablement n'importe quoi mais ça ne plante pas)
     Pour moi on est bons pour rapporter le bug, mais où ? Django ? Python ?
- Le paramètre en question ne sert **qu'à la localisation**, et j'ai **l'impression** qu'on ne s'en sert pas : on a pas d'input dépendant de la langue (décimal) et on force toutes les dates que j'ai vues avec un format personnalisé ; et plus curieusement avec une **langue** personnalisée : même en déclarant la locale en russe ou en anglais on a toujours du français sur le front.
- D'où la question : ne devrait-on pas supprimer purement et simplement ce paramètre ? (il faut étudier sérieusement les impacts)
- Sinon, en attendant on devrait pouvoir laisser la locale en anglais (`locale.setlocale(locale.LC_TIME, 'eng')`) pour les développeurs Windows. C'est un peu dommage mais je pense que ça marche comme solution de secours. A tester aussi.

**Comment by Alex-D** [comment]
Moi je dis : GG Python / Windows.

Sinon, je +1 le fait de virer la locale car le front utilise partout soit le filtre format_date (créé par @SpaceFox et donc on a la main dessus), soit le filtre date mais avec une chaîne pour avoir un format custom en paramètre.

A la limite, il faut vérifier que partout ça fonctionne bien (faire un test sur la preprod, sur Win et Mac) et si ça fonctionne aussi bien sans ce paramètre, on peut se permettre de le retirer.

**Comment by psycopy** [comment]
La locale LC_TIME pour un Windows en Français semble être `"French_France.1252"`.

**Comment by pierre-24** [comment]
Et on peut pas aller pousser ça chez Django ? Parce que c'est un bug, l'air de rien (j'ai pas dit que le correctif serait immédiat, mais voilà, quoi ^^)

**Comment by Alex-D** [comment]
> La locale LC_TIME pour un Windows en Français semble être "French_France.1252".

Le but c'est que ça fonctionne partout. Si la ligne ne sert à rien : on la retire, et c'est réglé sans artifice.

**Comment by SpaceFox** [comment]
Le ticket Django, pour ceux que ça intéresse : https://code.djangoproject.com/ticket/23265

**Comment by Alex-D** [comment]
Testé et mergé, c'est fermé :)
