### ISSUE TITLE
Documenter le fonctionnement du site (back)

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1356]
Aujourd'hui un développeur qui arrive sur le site et qui veut contribuer au back ne sait pas vraiment par où commencer.

On a des bouts de documentation à droite à gauche, mais aucun point d'entrée qui permettrait à un débutant de savoir par où commencer et où se renseigner en cas de doute.

Ce devrait être un fichier Markdown dans le dépôt avec les autres. Il peut contenir des liens vers des ressources externes si elles sont pérennes.

**Comment by firm1** [comment]
Si quelqu'un peut s'occuper de ça, qu'il se fasse plaisir. Il y'a pas mal d'éléments de réponse sur le forum.

**Comment by Eskimon** [comment]
Quelle devrait être la portée d'une telle doc ? Expliquer le fonctionnement de chacun des modules ? Le role entre eux ?

**Comment by SpaceFox** [comment]
Quel pourcentage de complétude de la doc avons-nous atteint ?

**Comment by pierre-24** [comment]
Je sais pas si on peut quantifier la "couverture" de la doc. Ce que je vois personelement, c'est encore beaucoup de "A venir" (au moins pour les articles et les forums, et le module de MP n'est pas dans la liste, et éventuelement pas non plus tout le bazar associé à la recherche et aux "pages", alors qu'ils s'agit aussi de modules dans le code). Au delà de ça, [j'avais posé la question de la portée d'une telle doc](http://zestedesavoir.com/forums/sujet/1230/la-documentation-de-zds/) avec des réponses plutôt favorables, donc y'a ce portage là à faire. Viens alors selon moi une nouvelle question : est ce qu'il s'agit d'une doc type "ce machin là ce trouve là en cliquant sur le bouton bidule" ou également une documentation du code genre "la fonction `bidule()` du fichier machin.py renvoi les 83 derniers utilisateurs à avoir passé la souris sur l'image de clem'"  ?

**Comment by gustavi** [comment]
Un problème sur la milestone non ?

**Comment by Eskimon** [comment]
Rendu ou en est la doc sur RTD, peut on considerer ce ticket comme OK ?

**Comment by pierre-24** [comment]
Je confirme :)

**Comment by Eskimon** [comment]
Merci :) (et encore bravo a tous pour la doc !!)
