### ISSUE TITLE
Montée de version de Solr : 3.5 --> 4.9

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1359]
Aujourd'hui, notre Solr de prod est en [version 3.5](https://github.com/zestedesavoir/zds-site/pull/1313#issuecomment-51718450), qui date de fin 2011.

A moins qu'on ait une vraie raison de ne pas le faire, autant passer à Solr 4.9, ce qui nous fera bénéficier de corrections de bugs, d'améliorations de performances, de nouvelles fonctionnalités, etc.

**Comment by firm1** [comment]
ça c'est fait.

Je ferme.
