### ISSUE TITLE
Les validateurs et admin ne devraient pas être capable de modifier un tuto/article si la license ne le permet pas

### ISSUE THREAD

**Issue by Nicofuma** [zestedesavoir/zds-site#1364]
Les licenses "CC-ND" et "Tous droits réservés" d'autorisent pas la modification du contenu protégé par le droit d'auteur. Par conséquent nul autre que le(s) auteur(s) ne devrai(en)t être en mesure d'éditer les articles/tutos/oeuvres en questions.

Mais d'après ce que j'ai pu lire sur le forum et [cette ligne](https://github.com/zestedesavoir/zds-site/blob/master/zds/tutorial/views.py#L550) ce n'est pas le cas.

**Comment by Eskimon** [comment]
Juste une question, une correction orthographique est-elle une atteinte au droit d'auteur ?

**Comment by Nicofuma** [comment]
pour moi une faute d'orthographe pouvant être une volonté artistique, la corriger est une enfreinte au droit d'auteur... mais bon je ne suis pas spécialiste donc quelqu'un d'autre saura certainement apporter une réponse plus précise.

Au passage, il se pose aussi la question de la modération sur le forum : a-t-on besoins d'ajouter une clause dans les CGU disant explicitement que en postant sur le forum on accorde à ZdS le droit d'altérer les posts en question si ceux-ci sont en infraction avec les dites-CGU (sachant que dans tous les cas, license ou pas, les modérateur peuvent se contenter de cacher les messages au lieu de les modifier/altérer)

**Comment by Eskimon** [comment]
Pour ce qui est du forum, tu acceptes le respect des CGU en utilisant le forum, donc t'engages à ne pas avoir de propos qui pourrait etre censuré. Si tu ne respectes pas les CGU je suppose qu'il est logique que les modos puissent censurer tout ou partie du message incriminé. (la encore, ce n'est pas une réponse absolu, juste mon avis)

**Comment by Nicofuma** [comment]
censurer tout le message (le cacher ou le supprimer donc) c'est normal et certains qu'on a le droit de le faire, par contre censurer seulement une partie du message... dans le sens le plus strict de la loi... franchement je sais pas^^
Je vais poster tout ça sur le forum ce soir, ainsi Arius (et éventuellement d'autres spécialistes) pourront répondre :)

**Comment by pierre-24** [comment]
Je suis la discution pour éventuellement en tenir compte dans #1363

**Comment by Nicofuma** [comment]
http://zestedesavoir.com/forums/sujet/1034/licences-et-modification-des-tutosarticles-par-les-validateurs/

**Comment by Eskimon** [comment]
D'après la discution mené sur le lien ci-dessus, je pense que l'on peut clore ce ticket avec la conclusion suivante : "Nous sommes entre gens civilisés, s'il y a modification l'auteur en sera conscient, averti et donc tout ira bien".

Merci pour le soulèvement de la question qui fut très intéressant !
