### ISSUE TITLE
Plus de mise à jour de la validation et de la béta

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1366]
Via [mewtow sur le forum](http://zestedesavoir.com/forums/sujet/1031/mise-a-jour-des-tutoriels-en-validation-totalement-petee/?page=1#p16030) : 

> Il est impossible de mettre à jour des tutoriels en cours validation : le bouton de mise à jour n'est pas accessible, et est remplacé par le bouton de premier envoi en validation. Ça me l'a fait sur deux tutoriels différents, donc je pense qu'il s'agit vraiment d'un bug. Celui-ci est apparu récemment : il n'était pas là il y a deux-trois jours.

D'ores et déjà, je peux annoncer qu'il s'agit d'une régression idiote introduite par ma propre PR #1322, je peux même dire qu'elle est due à ce qui se passe [ligne 206 de model.py](https://github.com/zestedesavoir/zds-site/blob/master/zds/tutorial/models.py#L206) et ce qui suis sur les 3 lignes suivantes. J'en déduis même que la béta le fera aussi, même si ça n'as pas été signalé.

Bref, assignez moi l'issue, le patch arrive d'ici 5 minutes.

**Comment by firm1** [comment]
Mergé, je ferme.
