### ISSUE TITLE
Liens généré via markdown non fonctionnels

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#137]
Les liens générés par markdown dont l'url n'est pas précédé par http:// ne fonctionnent pas.

Je propose que le parseur rajoute http:// devant l'url s'il n'y a pas de protocole.

**Comment by firm1** [comment]
En effet ... je plussoie.

**Comment by cgabard** [comment]
Je veux bien. Mais du coup il ne serait plus possible de mettre des liens relatifs, non ?

**Comment by cgabard** [comment]
Au passage j'aimerai bien un exemple ou s'est gênant, je ne suis pas sur que ça vienne de markdown mais de Django qui semble triturer le HTML par endroit

**Comment by firm1** [comment]
> Je veux bien. Mais du coup il ne serait plus possible de mettre des liens relatifs, non ?

J'y pensais bien, mais il n y'a aucun cas d'utilisation dans lequel un membre peut poster un lien contenant un chemin relatif.

> Au passage j'aimerai bien un exemple ou s'est gênant, je ne suis pas sur que ça vienne de markdown mais de Django qui semble triturer le HTML par endroit

Il suffit de rentrer ceci par exemple : 
`[lien](www.google.com)`

il est converti en : 
`<a href="www.google.com">lien</a>`

Du coup en cliquant dessus, tu vas sur la page : 
`http://zestedesavoir.com/forum/message/www.google.com`

Alors que tu le http est rajouté, tout va bien.

**Comment by cgabard** [comment]
Indeed, mais c'est un prob de HTML ça, c'est pas tellement la faute de markdown si tu fous de la merde dans ton liens. Enfin, ça devrait pas être trop chiant a rajouter

**Comment by cgabard** [comment]
A venir dans la prochaine PR

**Comment by firm1** [comment]
Au vu du code je pense que c'est fixé
