### ISSUE TITLE
[Markdown] Bug de rendu des boutons dans une liste

### ISSUE THREAD

**Issue by mlorant** [zestedesavoir/zds-site#1370]
Lorsque j'écris des boutons type `<kbd>` dans une liste, le rendu simule un tableau illisible : 

Extrait : 

```
- ||Ctrl-B|| pour mettre en gras (fait apparaitre `** **`)
- ||Ctrl-I|| pour mettre en italique (fait apparaitre `* *`)
- ||Ctrl-L|| pour ouvrir le pop-in d'ajout de liens
- ||Ctrl-K|| pour indenter un bloc (très utile en cas de sélection)
- D'autres exemples peuvent être visible sur [cette page de S.O](http://stackoverflow.com/questions/ask), mais les plus utiles sont là.
```

Résultat : 
![capture](https://cloud.githubusercontent.com/assets/532337/3889815/8d58d55e-2215-11e4-9451-c0fa6b897cef.PNG)

**Comment by Axylium** [comment]
C'est connu ! C'est le MD se mélange un peu les pinceaux puisque tu as des `|` aligner donc il croit qu'il doit générer un tableau.

Dans ce genre de cas, pour faire une liste, il est plutôt conseiller d'utiliser d'autres items du genre : `+` ou `*` ou d'insérer une ligne vide entre chaque item de ta liste.

**Edit :** Et en fait, les issues lié au MD sont plutôt à mettre [ici](https://github.com/zestedesavoir/Python-ZMarkdown)

**Comment by mlorant** [comment]
1. En effet, ça marche bien avec des `+` à la place des `-`
2. Au temps pour moi, je n'avais pas <strike>vu</strike> regardé que le markdown était géré dans un repo à part sous forme de fork

Je ferme ici du coup, en considérant "résolu". Si ça semble être assez utile pour faire un correctif, j'invite quiconque le souhaite à rouvrir une issue sur l'autre repo :)

**Comment by Axylium** [comment]
Pas de souci ! C'est vrai qu'il est un peu cacher.

Je vais le faire, pour mettre les gens qui s'occupent du zMD au courant (même si je pense qu'ils le sont déjà fortement) et avoir un suivi de tout ça.

Merci de ton report en tout cas !
