### ISSUE TITLE
le https n'est pas forcé sur la page de validation de login/inscription

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#1376]
ZDS supporte le https (yay!!), mais par contre, nous laissons des données aussi sensibles que les mots de passe ou e-mail transiter via http lors de la connexion. Ne serait-il pas plus utile et sécurisé de forcer toutes les urls commençant par `/membres/` d'être exécuté via https.

Cela renforcerait la confiance envers notre site et son [référencement](http://www.nextinpact.com/news/88925-google-va-favoriser-sites-accessibles-en-https-dans-ses-resultats.htm).

**Comment by Alex-D** [comment]
Encore une issue infra qui ne me semble pas liée au code...

**Comment by Coy0te** [comment]
+1, forcer le https, au moins sur les pages de connexion/inscription, me paraît nécessaire.

**Comment by Alex-D** [comment]
Eskimon a mis le tag back, mais encore une fois : c'est de l'infra et non du back selon moi.

**Comment by Eskimon** [comment]
yep, quand je vois un souci infra je met le tag back... mais maintenant que tu as rajoute le.tag infra ca ira mieux :)

**Comment by Eskimon** [comment]
Est-ce réellement compliquer à mettre en oeuvre ? Ce serait quand meme sympa de le proposer et Google semble favoriser les sites sécurisé dans son référencement

**Comment by Alex-D** [comment]
De façon générale, est-ce qu'on aurait pas intérêt à passer tout le site en HTTPS ? Est-ce que ça pose des soucis chez certaines personnes dans certains cas ?

**Comment by SpaceFox** [comment]
Quel intérêt d'avoir un site comme le nôtre en full HTTPS ?

Le 1 octobre 2014 01:12, Alexandre Demode notifications@github.com a
écrit :

**Comment by Eskimon** [comment]
Faire plaisir a google ? En tout cas la page de login semble le minimum...

**Comment by SpaceFox** [comment]
On pourrait avoir une source fiable sur ce point ? La dernière fois que
j'ai entendu parler de cette histoire d'influence du HTTPS sur le
référencement, c'était 1. à la marge et 2. sur la possibilité d'avoir du
HTTPS partout (et pas sur du HTTPS forcé partout).

Le HTTPS n'a du sens sur ce site que sur :
1. Les pages de connexion
2. Les pages personnelles privées (MP, édition du profil)
3. L'admin (réelle et les pages d'admin en front)
4. Éventuellement sur les pages des contenus pas encore publiés

Tout le reste (soit 99% du site) est public dont y forcer le HTTPS n'a
aucun sens.

2014-10-01 8:10 GMT+02:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
http://googlewebmastercentral.blogspot.fr/2014/08/https-as-ranking-signal.html

Pas mal de sources avec la recherche "google referencement https"

**Comment by Alex-D** [comment]
Je m'explique : à quoi bon protéger la page de connexion si quand on retourne sur les autres pages, on repasse en HTTP et donc on peut nous prendre notre cookie de connexion sur le réseau ?

Donc je réitère ma proposition plus précisément : oui au HTTPS sur la page de connexion ET sur toutes les pages à partir du moment où on est connecté.

**Comment by Situphen** [comment]
Sera réglé par #2494

**Comment by SpaceFox** [comment]
WTF c'est pas fait ça ?!

**Comment by GerardPaligot** [comment]
La PR de @Situphen n'a jamais été mergée.

**Comment by Situphen** [comment]
Il faut faire un test sur un serveur avec HTTPS, or il n'y a que les serveurs de ZdS pour ça ! Donc je peux rebaser ça et après la ZEP-12 on met ma PR en bêta ?

**Comment by SpaceFox** [comment]
OK.

**Comment by pierre-24** [comment]
(et l'ancienne bêta, on l'as encore ?)

**Comment by Eskimon** [comment]
Voilà qui est fait, enfin \o/ !
