### ISSUE TITLE
Navigation au clavier (droite/gauche) dans un tuto

### ISSUE THREAD

**Issue by sylafrs** [zestedesavoir/zds-site#1377]
Le principe est simple : passer au chapitre précédent/suivant avec les flèches gauche/droite dans un tutoriel.

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis plus d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.
