### ISSUE TITLE
Le parseur markdown ne reconnaît pas les URLs contenant des `:`

### ISSUE THREAD

**Issue by gasche** [zestedesavoir/zds-site#1381]
J'ai essayé de poster l'[adresse suivante](https://gitorious.org/gasche-snippets/anagram-path/source/aa16730b68cec4f7e13fd09a68cdc0dc1f98d787:defi.ml) sur un topic du ZdS. Mon message bien été renvoyé mais l'URL a été remplacée par `http:///`, rendant le lien invalide. Le problème vient des deux points au milieu de l'URL (pourtant valides), car utiliser manuellement leur encodage `%3A` à la place fait ré-apparaître l'URL.

Il est problématique que zds-markdown ne gère pas cette URL, mais encore plus gênant que je n'ai pas été prévenu de cette perte d'information au moment de la prévisualisation ou envoi du message (sinon j'aurai pu contourner au moment de l'écriture, au lieu d'apprendre quelques jours après que tous les liens sont en fait morts).

**Comment by Eskimon** [comment]
Salut !

Merci du retour, cependant ce type de bug concerne le parseur markdown qui est géré sur [un autre dépôt](https://github.com/zestedesavoir/Python-ZMarkdown/). Tu pourrais au choix [faire un ticket là-bas](https://github.com/zestedesavoir/Python-ZMarkdown/issues/) ou enrichir [ce ticket la](https://github.com/zestedesavoir/Python-ZMarkdown/issues/46).

Je ferme donc ici car ce n'est pas le bon dépôt.

Merci quand meme !

**Comment by gasche** [comment]
Je ne suis que moyen satisfait du fait que ce soit aux utilisateurs non-développeurs qui rapportent les bugs d'aller ré-ouvrir le bug au bon endroit. Ton explication est claire et me donne tout ce qu'il faut, mais ça reste à moi de payer le coût d'un problème technique de votre plateforme (pas moyen de déplacer facilement des bugs contrairement à d'autres bugtrackers multi-projets). Il me semblerait plus normal que ce soit plutôt au développeur actif, qui est habitué à ces outils, de re-poster le bugreport au bon endroit -- ce qui permet en plus de le tagger comme il faut du premier coup, de le formater comme vous avez l'habitude de le faire, etc.

PS: reposté: [bug #50](https://github.com/zestedesavoir/Python-ZMarkdown/issues/50).

**Comment by firm1** [comment]
Il faut quand même savoir que ZdS est un projet communautaire, ou tout le monde peut potentiellement apporter quelque chose. Que l'on sot développeur ou pas, j'aime bien la démarche d'Eskimon ici qui prend du temps pour expliquer comment reporter un bug au bon endroit sur github, plutot que de le faire lui même.
Les "developpeurs actifs" travaillent tous sur leur temps libre et ne sont pas toujours dispo pour faire le boulot, et même si c'était le cas, s'ils faisait tout, on ne serait plus vraiment un projet communautaire.

**Comment by gasche** [comment]
C'est juste, mais en même temps un contributeur très occasionnel a peut-être hésité entre poster un rapport ou juste ignorer le problème (boarf quelqu'un d'autre le signalera bien à ma place), et lui demander de faire un deuxième rapport ailleurs est une façon d'élever le coût de cette contribution (minime), et donc risque de diminuer le nombre de contributions qui vont jusqu'au bout.

Il y a un compromis à trouver qui est délicat, mais je pense qu'à première approximation "on déroule le tapis rouge pour les premières contributions, tout en montrant aux gens comment le faire eux-mêmes pour la fois suivante" est un bon mode de fonctionnement.

(Bien sûr je ne dis pas ça pour moi personnellement, ma réponse à Eskimon était un commentaire méta sur l'expérience de contribution; je teste ça aussi.)

**Comment by Alex-D** [comment]
Du coup, je ferme ici :)

La suite là-bas [zMD#50](https://github.com/zestedesavoir/Python-ZMarkdown/issues/50)
