### ISSUE TITLE
[Tuto] Impossible de supprimer un chapitre

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#1382]
Sur certains cours, le lien "supprimer le chapitre" est absent de l'interface d'édition d'un tuto (pour un membre du Staff au moins, je n'ai pas fait tester par l'auteur lui-même). 

Je ne sais pas si le problème vient du front ou du back, à tester sur ce tuto par exemple : 
=> **EDIT : lien supprimé par firm1 car 403 si on est pas staff**

La suppression du tuto entier, ou d'une partie du tuto, ou encore d'un extrait d'un chapitre, semblent par contre fonctionner. Seuls les chapitres semblent déconner.

[Edit] Pour info, d'après firm1 il s'agit d'une regression due à la dernière MEP.

**Comment by Eskimon** [comment]
cette issue avait deja ete rapportee, il faudrait la retrouver et la rouvrir je pense (pour le suivi). je l'aurais.bien fait mais je suis avec mon telephone...

**Comment by firm1** [comment]
Tu parles surement de [cette issue](https://github.com/zestedesavoir/zds-site/issues/1189) ? Ce n'est pas exactement la même (à en croire le libellé)

**Comment by artragis** [comment]
quel est l'état du tuto? Hier j'ai supprimé deux chapitres qui avaient pourtant du contenu et ça a bien marché.

**Comment by Coy0te** [comment]
Le tuto est en attente de validation.

**Comment by artragis** [comment]
ceci expliquant peut être cela. Le mien est en rédaction.

**Comment by Coy0te** [comment]
J'ai refusé le cours et l'ai renvoyé à l'auteur, on verra s'il arrive à
supprimer le chapitre.

**Comment by Coy0te** [comment]
En tout cas moi, maintenant que son cours est en cours de rédaction, je
n'arrive toujours pas à supprimer le chapitre. Je pense que le souci vient
de la structure du cours en lui-même. Il s'agit d'un cours importé depuis
le SdZ, il y a de grande chance que le souci vienne de par là.

**Comment by Coy0te** [comment]
Quelqu'un a changé qqchose ? Parce que ce soir l'auteur a réussi à
supprimer le chapitre sans problème.

C'est donc juste pour moi avec mes petits pouvoirs de staff que ça ne
marche pas. Est-ce que ça serait pas juste un pb de front ?

**Comment by SpaceFox** [comment]
À priori personne n'a rien changé, donc ce serait un problème front / une restriction des membres du staff.

Je regarde ça.

**Comment by SpaceFox** [comment]
C'est visiblement un problème de front. Je regarde plus en détail.

**Comment by SpaceFox** [comment]
Il manquait une permission.

Par contre, je me suis rendu compte que la gestion des actions de suppression est complètement incohérente : parfois c'est dans "actions", parfois c'est un item spécifique "suppression".

AMHA il y a un gros boulot de refonte de l'ergonomie de l'édition des tutos, en particulier des big-tutos. On a déjà quelques pistes [ici](http://zestedesavoir.com/forums/sujet/1083/creation-de-tutoriel/)

**Comment by SpaceFox** [comment]
Corrigé, mergé, fermé.
