### ISSUE TITLE
Les balises de code ne sont pas formatées pas dans les listes

### ISSUE THREAD

**Issue by gasche** [zestedesavoir/zds-site#1385]
Le [message suivant](http://zestedesavoir.com/forums/sujet/935/trichons-au-jeu-des-anagrammes-vivants/?page=3#p17192) contient des balises `<code>` dans des listes que le style CSS ne rend pas correctement. J'avais d'abord pensé à un bug markdown mais les balises sont bien présentes dans le HTML généré.

**Comment by Alex-D** [comment]
Ca vient bien du fait qu'ils sont dans des listes, moi j'ai filtré sur les paragraphes. C'est assez simple à corriger.

**Comment by Nodraak** [comment]
> Ca vient bien du fait qu'ils sont dans des listes, moi j'ai filtré sur les paragraphes. C'est assez simple à corriger.

J'ai rapidement cherché, mais j'ai rien trouvé.

Si je ne me trompe pas : la classe responsable est `code`, on a des attributs éparpillés, mais avec un _grep_ on trouve deux fichiers : `_pygments.scss` et `_all-supports.scss`. Nul pars je ne vois la mention d'un `p` ou d'une coloration de la fonte, j'ai du louper quelque chose ...

**Comment by Alex-D** [comment]
Correctif fonctionnel mergé, je ferme.
