### ISSUE TITLE
Disparition Google Tag Manager

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#1387]
Je suis désolé mais je vais faire une issue assez rapide, mais j'ai pas le temps de faire plus et il faut que ça soit corrigé rapidement. 

En gros mêmes symptômes que #1184 et ce depuis la dernière MEP. Il n'y a plus de stats actuellement !!!!!

**Comment by SpaceFox** [comment]
Je comprends pas, parce que le code JS est bien en place. Le Tag Manager est bien détecté par mon Ghostery.

Est-ce que quelqu'un du front a une idée ?

**Comment by devock** [comment]
Bon dans le doute j'ai juste revalidé Tag Manager et ça fonctionne... désolé pour l'issue un peu rapide...
