### ISSUE TITLE
Erreur 500 pour certaines urls au lieu de 404

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1389]
Si on consulte des topics comme celui ci : 

http://zestedesavoir.com/forums/sujet/605/lanalyse-de-projet-comment-reussir-son-projet-avant-meme-de-le-coder/?page=2

On a des erreurs 500 car le numéro de page n'est pas au bon format (numérique). On devrait par défaut rediriger sur la page 1.

En créant un topic sur un forum dont l'id n'existe pas, on a une erreur 500 aussi.

http://zestedesavoir.com/forums/sujet/nouveau/?forum=16r

On devrait avoir une 404 à la place.

**Comment by SpaceFox** [comment]
> Si on consulte des topics comme celui ci :
> 
> http://zestedesavoir.com/forums/sujet/605/lanalyse-de-projet-comment-reussir-son-projet-avant-meme-de-le-coder/?page=2
> 
> On a des erreurs 500 car le numéro de page n'est pas au bon format (numérique). On devrait par défaut rediriger sur la page 1.

Plutôt une 404 non ? Là on demande explicitement une page qui n'existe pas.

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé

**Comment by Eskimon** [comment]
En cliquant sur le bouton ca marche mieux ;)
