### ISSUE TITLE
Allonger le nombre de caractères limites dans la signature des forums

### ISSUE THREAD

**Issue by ghost** [zestedesavoir/zds-site#1393]
Salut !

Petite suggestion : allonger le nombre de caractères max pour rédiger sa signature.

En effet quand on veut mettre un lien ou deux, ça prend vite de la place...

Iz it possibeul ?

Merci d'avance, et pour votre boulot sur le site ;)

**Comment by Axylium** [comment]
Il y a eu un débat [sur le site](http://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?&page=21#p17299) à ce propos très récemment, si tu ne l'aurais pas vu, il a un peu dériver, mais bon. 

Sinon, pour te répondre, il faudrait voir avec Alex, je pense. Donc ping @Alex-D.  ^^

**Comment by ghost** [comment]
Oké merci ;)

**Comment by Axylium** [comment]
J'en profite pour en parler là, vu que ça traite des signatures. Quand nous avons une signature _longue_ et qu'on est auteur du sujet, et que donc que nous avons : « _cette réponse m'a aidé_ », cette dernière phrase, vient s'apposer sur le dessus de la signature et empêche de ce fait de voir le reste.

![capture du 2014-08-30 18 29 16](https://cloud.githubusercontent.com/assets/4312887/4099555/eda8bcf2-3062-11e4-92b9-f821faeb2112.png)

**Comment by Alex-D** [comment]
C'est voulu. Le site est fluide, c'est impossible de garantir que la signature sera complètement affichée correctement sur tous les supports.

**Comment by Alex-D** [comment]
Du coup, je considère ce ticket comme résolu, car tout ce que vous me dites est voulu, pensé et réfléchi (bien que discutable, mais il faut bien faire des choix à un moment).

**Comment by SpaceFox** [comment]
Pour moi le problème n'est pas résolu : le sujet d'origine, c'est la longueur du champ technique qui empêche de mettre plusieurs liens si le href des liens est trop long.

La taille d'affichage dont parle @Florianboux  est à moitié un HS - mais je suis d'accord, ce point est résolu.

**Comment by Alex-D** [comment]
Exact, j'avais mal interprêté en relisant, je n'avais pas le bon point de vue.

Du coup, c'est un soucis purement back et une solution qui avait été énoncée est de :
- mettre une longueur de champ assez longue, à la fois à l'input et au champ en BDD
- parser la chaîne de MD à HTML, puis faire un striptags et tester si cette longueur est inférieure à celle que l'on souhaite

**Comment by firm1** [comment]
Pour information, pour résoudre cette issue, il faudrait
- faire sauter la limite des 250 caractères en modifiant [cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/models.py#L56) par ça : 

``` python
sign = models.TextField('Signature', max_length=1000, blank=True)
```
- lancer la génération des fichiers de migrations (en ligne de commande) : 

``` bash
python manage.py schemamigration member --auto
```

Et ça devrait faire une jolie PR !

**Comment by Eskimon** [comment]
C'est pas suffisant, il faudra tout de meme limite en longueur la signature "rendu en MD" si on veut pas que des petits malins mettent des signatures qui font des kilometres mais que l'on affiche pas.

**Comment by firm1** [comment]
> si on veut pas que des petits malins mettent des signatures qui font des kilometres mais que l'on affiche pas.

s'il a un écrans quifait des kilomètres à l'instar de sa signature, ça sera affiché :) 

On ne peut pas juger de la limite au poil près (ça dépend du support), donc si le mec met un message super long, tout dépend de son écran.

**Comment by Eskimon** [comment]
Et le mec qui te met l'integrale des miserables dans sa signature ?

**Comment by firm1** [comment]
> Et le mec qui te met l'integrale des miserables dans sa signature ?

En effet :). J'édite mon message donc.

**Comment by SpaceFox** [comment]
C'est toujours d'actualité @Situphen ?

**Comment by Situphen** [comment]
Bah c'est [le débat communautaire](https://zestedesavoir.com/forums/sujet/3298/signature-trop-longue-tronquee/) qui coince !

Tout le monde semble d'accord pour agrandir le nombre de caractères dans les signatures. Mais ça coince sur est-ce qu'on ajoute la possibilité de cliquer sur la signature pour voir la signature complète (une vidéo est disponible [ici](https://drive.google.com/file/d/0ByCc7U2bgTkbb243Wk5nVHoxeVU/view?usp=sharing)) ? Des gens pour, d'autres contre. Dans les derniers messages, il me semble avoir un peu un consensus pour tester et voir si les gens abusent du truc ou pas.

Je pense que le mieux est que tu discutes ça avec Eskimon et que vous décidiez si oui ou non on teste ça ! En tout cas, ça sert à rien de débattre plus longtemps pour un truc aussi mineur que ça... :)

**Comment by Eskimon** [comment]
Bon, je vais dans ma grande sagesse trancher le souci : On pousse à 2000 et on autorise l'affichage complet au clic sur la signature (pas de nouveaux boutons et attention à ne pas empêcher les clics sur URL)

**Comment by SpaceFox** [comment]
Je plusseoie la solution de @Eskimon .

**Comment by Situphen** [comment]
Bah normalement ma PR #2782 respecte ça donc on peut la QAtiser !
