### ISSUE TITLE
Les images d'entête des tuto/chapitres ne sont pas correctement dimensionnés

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#140]
Si on regarde par exemple le tutoriel [suivant](http://preprod.zestedesavoir.com/tutoriels/16/fonctionnement-des-ordinateurs-de-zero/), on peut voir dans l'entête du tuto (à coté du titre) que l'image du tuto déborde un peu trop sur les cotés.

Il faudrait redimensionner ça à coup de css.

**Comment by Alex-D** [comment]
Redimensionner en CSS, ça va déformer l'image, je tiens juste à le signaler.

Pour moi le back doit délivrer une image carrée dans l'idéal.

**Comment by cgabard** [comment]
@Alex-D : Chez moi (FF26/Linux) ça ressemble surtout à un bug de front : 
![test](https://f.cloud.github.com/assets/6103932/2089040/31d2ffe2-8e82-11e3-8e0f-e1fd76b1f647.png)

**Comment by firm1** [comment]
> Redimensionner en CSS, ça va déformer l'image, je tiens juste à le signaler.

Tu peux fixer au moins un max-height pour corriger ça sans déformer l'image.

> Pour moi le back doit délivrer une image carrée dans l'idéal.

Si l'auteur mets une image rectangle, on ne va pas croper son image. Et le back ne peux pas juste délivrer toutes les images à la bonne taille selon là ou on se trouve. ça signifierait stocker au moins 10 images juste pour le logo d'un tutoriel.

**Comment by Alex-D** [comment]
Nan mais @cgabard je sais ce que ça donne, et je comprend de quoi il est question, c'est en gros le même soucis que pour les avatars.

Dans l'idéal, en effet il faudrait plusieurs images sur le back ou uniformiser pour avoir toujours la même image. Mais bon, visiblement on est plutôt parti sur du redimensionnement bourrin en front. J'aimerais simplement être sûr d'une chose : il y a une taille maximale ? Histoire qu'on ne se retrouve pas avec du 500x500 redimensionné en CSS.

**Comment by firm1** [comment]
Actuellement coté back les images existent toutes en 3 versions : 
- thumb : 80x80 (paramétrable)
- medium : celle qui t'es délivrée actuellement. (paramétrable aussi)
- normal : la taille normale uploadée

Donc, si tu redimensionnes en css, ça ne coute que dalle et je ne peux pas me permettre de stocker une immensitée de version d'image coté back. 3 c'est largement suffisant.

**Comment by Alex-D** [comment]
En l'occurence l'image finale du design fait ~ 50x50. Il serait plus logique de mettre la 80x80 du coup. Je verrais ça quand je changerais la taille.

En effet, trois tailles me semble raisonnable, si on les règle correctement.

Je peux dors et déjà te dire de passer de 80x80 à 60x60. L'accueil utilisant du 60x60 et les tutos du 50x50, ça sera suffisant au niveau du thumb.

**Comment by firm1** [comment]
Par sécurité, j'aimerai tout même que le front fasse la réduction d'image. Quand ça sera fait, j'ajusterait mes paramètres (3 variables à modifier dans mon setings)

**Comment by Alex-D** [comment]
Oui, bien entendu !
Ce sont bel et bien des oublis de ma part.

**Comment by Alex-D** [comment]
Fixé dans le commit https://github.com/Taluu/ZesteDeSavoir/commit/7ab051aa26a00158b843f5562a1dce7fc253fc17
