### ISSUE TITLE
Refonte de l'affichage des participants aux MP

### ISSUE THREAD

**Issue by jcval** [zestedesavoir/zds-site#1408]
Sur la page d'accueil des MP (https://zestedesavoir.com/mp/), l'affichage des participants se casse la figure lorsqu'il y en a beaucoup :
- à une époque ils chevauchaient sur le MP suivant
- maintenant ils semblent être masqués par le MP suivant

**Proposition :**

En afficher un nombre fixe (dont on est sûr que ça rentre sur n'importe quelle résolution d'écran) et afficher "et xx autres". Le survol sur "et xx autres" afficherait une liste déroulante / tooltip / popover avec   les autres.

**Comment by Alex-D** [comment]
> En afficher un nombre fixe 

This is not possible.

Pour moi la seule vraie solution viable c'est que ça augmente en hauteur sans péter la mise en page.

**Comment by jcval** [comment]
> This is not possible.

Pourquoi ?

**Comment by Alex-D** [comment]
Parce qu'on ne peut pas prévoir toutes les largeurs et qu'on afficher plus de participants sur ordi que sur un téléphone en 320px de large. Donc pour moi, ça doit être fluide (le principe même du front du site) plutôt que de fixer arbitrairement un nombre à afficher après quoi on mettrait "et X autres".

Si on prend le cas d'un mobile type HTC Wildfire, ça m'étonnerais pas qu'on ne puisse pas mettre plus de 2 participants. Pire encore : on ne connais pas la taille des pseudos... on ne peux vraiment rien prévoir donc.

**Comment by Eskimon** [comment]
J'ai un HTC Desire (pas loin du Wildfire) et effectivement on est a 2 participants et encore le design a du mal a passer (mais la on tape dans les vieiiiilles resolutions)

**Comment by firm1** [comment]
Ce problème est réglé avec les récentes corrections. Je ferme donc ici.
