### ISSUE TITLE
Styliser les bloc customs

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#141]
Actuellement les blocs customs de type `warning`, `error`, `question` ne sont pas stylisées. Le markdown renvoie pourtant les résultats html suivants : 
- `class="warning ico-after"`
- `class="error ico-after"`
- `class="question ico-after"`
- `class="information ico-after"`

En ce qui concerne les informations, le css attend une class nommée "info" alors qu'on lui envoit une classe nommée "information".

Il faudrait dont styliser tous ces blocs.

**Comment by Alex-D** [comment]
Fixé dans le commit https://github.com/Taluu/ZesteDeSavoir/commit/7ab051aa26a00158b843f5562a1dce7fc253fc17
