### ISSUE TITLE
MathJax HS sur le site

### ISSUE THREAD

**Issue by amorison** [zestedesavoir/zds-site#1411]
Hello,

je viens de voir que le MathJax est HS sur le site, il n'est simplement pas interprété (voir [ce sujet par exemple](http://zestedesavoir.com/forums/sujet/641/exemple-de-normes-non-equivalentes/)).

J'ai eu un petit temps d'attente lors de la connexion avec https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js (d'où sont chargés les JS). Le problème vient dont peut être de chez eux, mais il n'y a aucun soucis sur la page d'accueil du site de MathJax...

**Comment by firm1** [comment]
Il faut changer le cdn `https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js` par `http://cdn.mathjax.org/mathjax/latest/MathJax.js`

**Comment by Alex-D** [comment]
Ou sinon, on se décide enfin à récupérer tous les JS dont on a besoin et à les inclure dans notre processus de minification des JS.

**Comment by firm1** [comment]
Fx'd

**Comment by firm1** [comment]
Je ré-ouvre cette issue, car, Mathjax est down !

**Comment by SpaceFox** [comment]
Il va falloir être plus précis, parce que chez moi ça marche nickel.

**Comment by firm1** [comment]
C'est revenu.
