### ISSUE TITLE
La branche dev est cassée

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1416]
L'[énorme merge ](https://github.com/zestedesavoir/zds-site/compare/9581825f79...4c9b3a82d7) de master vers la dev, a cassé la branche dev, les tests ne passent donc plus sur dev et travis ne build donc plus dessus.

Il faudrait réparer la dev assez urgemment, car les PRs en attente ne passent pas non plus le build à cause de ça. :(

**Comment by SpaceFox** [comment]
Je prends.

**Comment by Alex-D** [comment]
Ca a été mergé donc ceci est résolu, je ferme.
