### ISSUE TITLE
Les titres de type lien rendent mal

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#142]
Actuellement dans les cours on a le rendu suivant : 
![good_title](https://f.cloud.github.com/assets/6066015/2089043/387df784-8e82-11e3-90bf-3a879e4bfa31.PNG)

Au lieu d'avoir un rendu du style suivant : 
![bad_title](https://f.cloud.github.com/assets/6066015/2089041/3219aa82-8e82-11e3-9d71-f58a175dd79a.png)

Le html du premier rendu est le suivant : 

``` html
        <h2 id="1-les-chiffres-et-les-nombres">
            <a href="#1-les-chiffres-et-les-nombres">
                Les chiffres et les nombres
            </a>
        </h2>
```

Et celui du deuxième est le suivant: 

``` html
 <h2>I - Le Document Object Model</h2>
```

Ce qui signifie qu'il faut styliser aussi les balise `<h2>` qui ont un contenu de type `<a>` pour avoir un truc uniforme.

**Comment by Alex-D** [comment]
En clair, c'est mal de faire ça. Il serait plus adapté de rajouter une icône portant le lien comme on le voit sur les docs un peu partout (ou les wiki).

Pour le coup, c'est plutôt dû à un non respect de ce que j'ai fait dans mon HTML (même si je n'ai pas mis l'icône pour le lien, je l'accorde).

**Comment by firm1** [comment]
> Pour le coup, c'est plutôt dû à un non respect de ce que j'ai fait dans mon HTML (même si je n'ai pas mis l'icône pour le lien, je l'accorde).

Je ne fait que suivre tes "consignes" :) . Quand tu aura prévu le permalink, ça sera ajouté. Donc, a toi de faire le choix la dessus.

**Comment by geoffreyc** [comment]
"En clair, c'est mal de faire ça." Pourquoi donc?

2014-02-05 firm1 notifications@github.com:

**Comment by Alex-D** [comment]
Ergonomiquement déjà d'une.

Est-ce que si tu cherche à avoir un permalink, ton premier réflexe sera de cliquer sur le titre ? Moi, je cherche plutôt une icône de lien ou une icône de paragraphe à côté de ce titre, parfois au survol de celui-ci.

Vous en pensez quoi ?

**Comment by SpaceFox** [comment]
Pour moi ça dépend de l'UI. Si le titre réagit au survol, ça va me paraître
logique que c'est un lien direct vers ce titre.
Si le titre ne réagit pas par contre, là je vais chercher une icône ou
quelque chose du genre.

Le 6 février 2014 13:46, DEMODE Alexandre notifications@github.com a
écrit :

**Comment by cgabard** [comment]
Comme SpaceFox : Je vais aller chercher "vers le titre". Si celui-ci change de couleurs/apparence, je suppose que c'est le permalink. Sinon je m'attend à trouver un symbole type # a coté pour celui ci

**Comment by Alex-D** [comment]
J'ai corrigé ça dans le commit suivant : https://github.com/Taluu/ZesteDeSavoir/commit/ebde69adb8fa4435401aa16901b754773f6022e8
