### ISSUE TITLE
Optimisation de l'affichage des post-its

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1421]
[via Eskimon](http://zestedesavoir.com/forums/sujet/1188/optimisation-de-laffichage-des-post-its/)

Sur certains forums, les post-it prennent pas mal de place. Ca pourrait etre sympa de les reduire en diminuant leur hauteur en supprimant l'auteur et la date de publication (puisque un post-it n'a que peu d'empreinte dans le temps).

Voici une idee rapide du rend, c'est subtil mais c'est un debut.

![](http://zestedesavoir.com/media/galleries/321/b11229b0-bbff-4b5e-90c9-233bb9719bf1.png.960x960_q85.jpg)

Apparemment ca a l'air de plaire et d'etre approuve, donc je fais ce ticket !

**Comment by Alex-D** [comment]
Je vois l'idée. Le soucis c'est que ça ajoute du code à maintenir et que si le topic est post-it + résolu + fermé : à gauche il n'y aura pas assez de place pour les trois icônes.

Du coup il faut trouver un compromis au niveau des icônes, et il faut se dire qu'il va y avoir du code "dupliqué" car deux formes de topic à maintenir.

**Comment by firm1** [comment]
> Du coup il faut trouver un compromis au niveau des icônes, et il faut se dire qu'il va y avoir du code "dupliqué" car deux formes de topic à maintenir.

Le besoin doit primer sur la technique. On ne peut pas offrir une ihm toute moche et pas ergonomique sous prétexte que le code ne doit pas être dupliqué.

**Comment by Eskimon** [comment]
Un post-it doit-il / peut-il etre resolu ? Est-ce pertinent ? Car si c'est juste pour cette icone, on la filtre sur l'affichage des post-its... C'est ptet pas elegant, mais le fait que je dois scroller pour voir au dela des deux premiers sujet c'est pas ultime non plus...

**Comment by Alex-D** [comment]
Ok dac, donc on se dit qu'on ne met pas les post-it en résolu et en fermé en même temps.

> Le besoin doit primer sur la technique.

Certes, c'est juste la prévention, je n'ai pas dit "NON, CA FAIT DU CODE EN PLUS", je dis simplement que ça va légèrement complexifier le maintient du code et augmenter la probabilité de bugs sur un code qui n'est même pas encore achevé (sur mobile c'est un peu n'importe quoi).

**Comment by Eskimon** [comment]
"on" je sais pas, mais moi ca me derange pas de l'imaginer comme ca. Ca va perdre en coherence quand on utilisera les fitlres resolus/non resolus par contre (car l'indicateur visuel ne sera plus la).

Sinon une deuxieme solution pourrait pkoi pas de mettre les icones en ligne pour les post its.

Encore une fois j'ai pas de solution miracle, juste le probleme :D

**Comment by Alex-D** [comment]
> mettre les icones en ligne

Certainement pas, encore une fois faut penser multi-support et sur mobile c'est déjà le boxon de tout rentrer, si tu mange la moitié de la largeur de l'écran avec 3 icônes, c'est la misère.

Ce n'est de toute façon pas urgent, je verrais ce que je pourrais faire au moment voulu :)

**Comment by ghost** [comment]
J'ai fais quelques maquettes d'un rendu possible : 

![Imgur](http://i.imgur.com/TeA9860.png)

Différencier les post-its lu ou non lu ? (Limité à une semaine ?)
![Imgur](http://i.imgur.com/IXAmmug.png)

Cliquer sur le logo pour afficher/masquer les détails ?
![Imgur](http://i.imgur.com/yc02UyF.png)

**Comment by gustavi** [comment]
> (Limité à une semaine ?)

Surtout pas ! Il m'arrive de ne pas passer sur le forum pendant plus d'une semaine et j'aime bien suivre ce qu'il s'y passe.

**Comment by GerardPaligot** [comment]
Pour moi, le problème n'est pas forcément là où vous semblez le croire. Un sujet en post-it, c'est quoi ? C'est un sujet que nous voulons mettre en avant parce qu'il est intéressant, utile et/ou comporte des règles relatives au forum dans lequel il a été posté. Partant de là, il faut qu'il soit **visible** par les membres.

Cependant, je suis d'accord que les post-its dans la Dev Zone prennent trop de place. Dans un écran modeste, il serait possible de ne voir que les post-its avant de voir les autres sujets. Mais le problème ne serait-il pas plutôt qu'il y a trop de post-it ?

**Comment by ghost** [comment]
> Mais le problème ne serait-il pas plutôt qu'il y a trop de post-it ?

Je trouve que certain sujet devrait être en post-it alors qu'ils ne le sont pas. Peut-être revoir l'assignement et la présentation des posts-it, dans un même sujet comme une FAQ.

**Comment by SpaceFox** [comment]
Le sujet est intéressant mais à débattre sur les forums. C'est de
l'organisation du site, pas du code.

**Comment by GerardPaligot** [comment]
Je suis d'accord avec @SpaceFox et un [sujet est déjà créé sur les forums](https://zestedesavoir.com/forums/sujet/1188/optimisation-de-laffichage-des-post-its/?page=4) pour en parler. Dès qu'une décision est prise par la communauté, il sera encore temps de créer une nouvelle issue avec la spec voulue.
