### ISSUE TITLE
Optimisation des signalements

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1422]
Il y a deux petites optimisations qui pourrait etre faite assez simplement sur les signalements:
- L'une concerne l'input de texte. Il est assez étroit. Un textarea serait plus confortable.

![screenshot from 2014-09-02 11 13 25](https://cloud.githubusercontent.com/assets/761168/4116175/fca9c9be-3281-11e4-94cf-e3ed54fff153.png)
![screenshot from 2014-09-02 11 14 12](https://cloud.githubusercontent.com/assets/761168/4116174/fca86ad8-3281-11e4-8433-40e6e0c0b1c4.png)
- L'autre concerne le rendu des signalements, un petit padding a droite serait sympa pour eviter de passer sous le bouton resoudre

![screenshot from 2014-09-02 11 14 20](https://cloud.githubusercontent.com/assets/761168/4116186/172770c0-3282-11e4-88a3-aab613ff9ad1.png)
![screenshot from 2014-09-02 11 14 49](https://cloud.githubusercontent.com/assets/761168/4116187/172d7ba0-3282-11e4-8ca1-bbe66cce4e84.png)

**Comment by Alex-D** [comment]
Oula tu as pété un plomb sur les tags toi, t'as cliqué partout ?

+1 pour le textarea.

Pour ce qui est de "Résoudre" je ne sais plus quel est le problème mais je sais qu'il y avait un truc qui m'embêtait pour rajouter une marge, faudrait que je réessaye.

**Comment by Eskimon** [comment]
Il y a un bug et une evo, du coup deux tags...

Pour le résoudre, pour la capture d’écran j'ai mis un padding-right a l'arrache et ca a fait le résultat visible, mais je me rappel plus s'il y avait une classe particulière sur cette boite (et donc du coup s'il y avait effet de bord ou pas)

**Comment by Alex-D** [comment]
Faut penser aussi aux mobiles, tablettes, mini-PC, etc. Du coup faut tester dans toutes les résolutions, etc. C'était peut-être par pure flemme que je ne l'avais pas mis, mais il me semble qu'il y avait une vraie raison quand même.

**Comment by Alex-D** [comment]
Fait, mergé, je ferme.

**Comment by Eskimon** [comment]
Ca fail un max les signalements sur la preprod...

![screenshot from 2014-09-25 10 10 54](https://cloud.githubusercontent.com/assets/761168/4401296/9ba55eb4-448b-11e4-91a0-6aef44269e65.png)

**Comment by Alex-D** [comment]
Heu... dis moi que tu n'as pas utilisé le filtre markdown là ? Parce que pour les messages de validation c'est OK, mais pour les messages de modération, non. C'est du texte brut qu'il faut.

**Comment by Eskimon** [comment]
C'est quoi le rapport avec le mardkdown ? Tu parles de ma PR ? Si oui vu qu'elle est encore en review ca risque pas d'avoir un quelquonque rapport.

**Comment by Alex-D** [comment]
Oui je parlais de cette PR là. On a quasi rien touché sur ces box là, et le bug est totalement WTF :/

**Comment by Alex-D** [comment]
J'ai trouvé, ça vient d'une autre PR que j'avais faite, l'une et l'autre n'étaient pas compatible visiblement. C'est désormais corrigé. À tester :)

**Comment by Eskimon** [comment]
Ok
