### ISSUE TITLE
Afficher la miniature dans la liste des images d'une galerie

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1429]
Actuellement c'est la grande image qui est chargée, alors qu'on a une miniature à disposition, du coup la page prend des plombes à charger.

**Comment by Eskimon** [comment]
Pour la personne qui veut corriger, il faut changer `img.physical.url` par `image.physical.gallery.url` si je dis pas de betises, a la ligne suivante. ( @Alex-D tu confirmes ?)

https://github.com/zestedesavoir/zds-site/blob/dev/templates/gallery/gallery/details.html#L83

**Comment by Alex-D** [comment]
Ca doit être un truc de ce genre là oui, c'est pas grand chose.

**Comment by Alex-D** [comment]
Voilà qui est fait, je ferme.
