### ISSUE TITLE
Les images dans les tutos trop larges explosent le design mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#143]
Je teste sous chrome mobile sous Android en mode portrait.
En allant sur ce lien : http://preprod.zestedesavoir.com/tutoriels/15/les-maths-pour-tous/niveau-6/interro-surprise-decimaux-fractions-et-ordres/#3-la-droite-mystere

Malheureusement quand l'image est trop large elle déborde sur la largeur prévue. Et donc du coup c'est presque impossible d'accéder au menu en slidant par la gauche. Et par curiosité, quand je slide sur la droite, j'ai u' espace noir de ce coté et vide.

Je pense qu'il faudrait limiter (avec un max-width) la largeur des images contenus dans un tuto pour régler ce problème.
On observe aussi le même problème sur mobile si j'écris un mot très long sans espace.

**Comment by Alex-D** [comment]
Yep

Tout le design du contenu est à faire globalement. Doit y avoir le même genre de bug si tu mets une image de 5000px sur un PC ^^

**Comment by Alex-D** [comment]
Fixé dans le commit https://github.com/Taluu/ZesteDeSavoir/commit/7ab051aa26a00158b843f5562a1dce7fc253fc17
