### ISSUE TITLE
Mettre à jour les dépendances NPM

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#1430]
https://david-dm.org/zestedesavoir/zds-site

Comme on peut le voir sur ce site, nos dépendances front sont pas tout à fait à jour. C'est pas hyper-bloquant, mais je sais que ça peut poser problème à l'install sur certains système (de mémoire, la version utilisée de gulp.spritesmith a posé problème lors de mes tests avec Docker, alors que la dernière marche très bien)

Une PR est déjà ouverte: #1398

**Comment by Eskimon** [comment]
Meged, je ferme :)
