### ISSUE TITLE
Les tests front lancés par travis ne sont pas optimaux par rapport à ce qu'on a

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1432]
Actuellement, travis se contente de vérifier que les JS sont valides, or il serait préférable de tester tout le Gulpfile en construisant le zip `pack.zip` qui nécessite de passer dans toutes les taches (sauf watch, mais ça on ne peut pas le tester et ça n'influe pas sur le bon fonctionnement du reste, simple confort durant le développement).

**Comment by Eskimon** [comment]
Du coup on peut fermer ici ?

**Comment by Alex-D** [comment]
Exact : mergé -> fermé.
