### ISSUE TITLE
Ajouter les liens vers les réseaux sociaux sur le site

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1436]
[Source](http://zestedesavoir.com/forums/sujet/1184/acces-depuis-le-site/)

La suggestion est simple et intéressante : ajouter les liens vers Twitter, Facebook et G+ sur le site.

Une solution toute indiquée semble être le pied de page, a minima.

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé
