### ISSUE TITLE
Diff sur les articles

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1443]
On a actuellement des diffs sur les tutoriels, il faudrait faire de même sur les articles.

**Comment by SpaceFox** [comment]
Ca viendra sans doute avec la ZEP d'unification des articles et tutos (mais
je plusseoie l'idée).

2014-09-04 3:06 GMT+02:00 Alexandre Demode notifications@github.com:

**Comment by artragis** [comment]
C'est presque obligatoire que l'unification article/tutoriel apportera cette fonctionnalité.

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
Implémenté sur la ZEP 12, il faudra juste passer un coup de front sur cette
page.

2015-04-16 14:25 GMT+02:00 Eskimon notifications@github.com:

**Comment by pierre-24** [comment]
Et pas que de front, je sais pas ce que fout la lib' qui génère les diffs, mais c'est pas clair.
