### ISSUE TITLE
[Staff] Ajouter les métadonnées des utilisateurs

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1444]
Il manque, par rapport à ce qui était prévu à la base : 
- le karma de l'utilisateur (par rapport à ses sanctions)
- ses adresses IP

Les éléments front sont globalement prêts.

**Comment by Eskimon** [comment]
> Les éléments front sont globalement prêts.

C'est a dire que c'est pret dans le front mais le back le renvoi pas ou le contraire ? (je suppose que le back te les renvoi pas vu le tag "Back" ;) )

**Comment by Alex-D** [comment]
C'est inexistant côté back pour le karma (a priori) et les IPs je suppose qu'elles sont quelque part mais on a aucune vue dessus.

Et en gros, [le front est prêt à accueillir tout ça](https://github.com/zestedesavoir/zds-site/blob/dev/templates/misc/message_user.html#L13).

**Comment by Eskimon** [comment]
Avis aux membres staff, avez vous vraiment besoin de ca ?

**Comment by Eskimon** [comment]
Si quand je reviens fin avril/début mai j'ai pas de nouvelles, je considérerais le ticket comme bon a fermer.

( @Situphen si tu peux contacter des staff pendant mon absence pour leur demander leur avis ce serait cool)

**Comment by Situphen** [comment]
Donc il faut leur demander s'ils ont besoin d'avoir les adresses IP des membres à côter des messages ?

**Comment by Eskimon** [comment]
et le karma voui dans l'idee c'est ca

**Comment by Situphen** [comment]
Je fais ça !

**Comment by SpaceFox** [comment]
Ici c'est bon, non ?

**Comment by Situphen** [comment]
Le design a été intégré par Alex-D il y a longtemps et le back par Eskimon (il me semble) un peu après. Mais le front n'a pas été dé-commenté (alors qu'il fonctionne sinon). Je viens d'envoyer une capture d'écran au Staff pour voir si ça leur convient, puis je ferai une PR avec les éventuels modifs demandées ! :)

**Comment by gustavi** [comment]
ping @Situphen !

**Comment by GerardPaligot** [comment]
@Situphen tu as eu le temps de t'en occuper ?

**Comment by Situphen** [comment]
Je viens de m'y remettre dessus à l'instant. C'est assez simple à faire.

Par contre, comme l'avait dit Alex-D, il n'y a aucune vue listant les IPs d'un utilisateur ! Seul la dernière IP de l'utilisateur est affichée sur son profil. C'est gênant ou pas ?

Au pire on fait seulement une première itération avec le karma ?

**Comment by GerardPaligot** [comment]
Rien n'empêche d'afficher la dernière IP connue de l'utilisateur déjà. :)

**Comment by Situphen** [comment]
En fait, Alex-D a seulement prévu un lien vers la page listant les IPs de l'utilisateur je crois :

![version-alex-d](https://cloud.githubusercontent.com/assets/6664636/13027580/a00da35a-d254-11e5-9c43-9b30a653afc7.png)

Le rectangle affichant le karma et celui affichant "IPs" sont pour l'instant 2 liens pointant vers le profil de l'utilisateur.

Je propose un seul rectangle avec le karma pointant vers le profil de l'utilisateur :

![version-situphen](https://cloud.githubusercontent.com/assets/6664636/13027579/a00ccf7a-d254-11e5-8f07-ed7fe15d7944.png)

**Comment by GerardPaligot** [comment]
Partons là dessus alors.

**Comment by AmauryCarrade** [comment]
Ne serait-il pas mieux d'afficher le karma uniquement lorsqu'il est non-nul ? Afin d'alléger l'interface.

**Comment by gustavi** [comment]
À voir selon les besoins du staff

**Comment by Situphen** [comment]
Je demande ça aux Staff, j'ai déjà un MP avec eux !

**Comment by Situphen** [comment]
Proposition approuvé par des staffeux.

![version-situphen](https://cloud.githubusercontent.com/assets/6664636/13027924/23191828-d260-11e5-8765-d20230918e0e.png)
