### ISSUE TITLE
Page 404 :. Ajout de Clem

### ISSUE THREAD

**Issue by Glaived** [zestedesavoir/zds-site#1447]
Bonjour,
Me demandez pas pourquoi, mais j'ai pensé qu'il serait bon, d'ajouter Clem sur la page 404, voir d'autres pages d'erreurs, avec pour idée qu'elle est des yeux de chien battus, et un _sourire triste_

Qu'en pensez vous ?

**Comment by Alex-D** [comment]
Doublon : https://github.com/zestedesavoir/zds-site/issues/1028

Déjà prévu et partiellement fait.
