### ISSUE TITLE
Badge de suivi des dépendances python du projet

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1448]
Avec la PR #1418 , on va fixer les dépendances python, par contre, pour éviter de suivre chaque dépendances tous les jours, il serait fort souhaitable de rajouter un badge dans le readme qui analyse la qualité de nos requirementss.

Il suffit donc pour un admin du dépot de créer le badge ici : https://requires.io/ et de le rajouter dans le readme.

**Comment by SpaceFox** [comment]
Excellente idée !

**Comment by SpaceFox** [comment]
Sur quels projets de ZesteDeSavoir en a-t-on besoin ? Juste zds-site ? (tant que j'y suis hein...)

**Comment by firm1** [comment]
Tout ceux qui ont des dépendances a mon avis.

**Comment by sandhose** [comment]
Du coup, on pourrait rajouter au passage le badge [David](http://david-dm.com/), qui track les dépendances npm

[![Dependency Status](https://david-dm.org/zestedesavoir/zds-site.svg)](https://david-dm.org/zestedesavoir/zds-site)

**Comment by SpaceFox** [comment]
C'est bizarre comme truc : les badges ont le nom de la branche dans l'URL. Du coup, comment je fais pour avoir un badge cohérent avec la branche courante ?

Exemple : [![Requirements Status](https://requires.io/github/zestedesavoir/zds-site/requirements.png?branch=dev)](https://requires.io/github/zestedesavoir/zds-site/requirements/?branch=dev)

**Comment by SpaceFox** [comment]
C'est fait ici !
