### ISSUE TITLE
Incohérence dans la soumission

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1450]
Lorsqu'on soumet un tutoriel, les commentaires de validations se font dans un `input`, alors que c'est dans un `textarea` pour les articles (ce qui me semble d'ailleurs plus logique). C'est pareil pour les modales de validation des tutoriels (ou de refus). Pour moi, `textarea` est plus adapté.

**Comment by Eskimon** [comment]
Pour les commentaires de demande de validation de tutoriels c'est la: https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/forms.py#L368

Pour la validation de validation: https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/forms.py#L405
Pour refus de validation: https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/forms.py#L447

Donc finalement c'est du back (alors que pour les articles c'est du front...)

**Comment by pierre-24** [comment]
Peu m'importe que ce soit du back ou du front, le fait est que ça serait mieux si c'était cohérent ;)

**Comment by Eskimon** [comment]
Je m'en occupe :)

**Comment by Alex-D** [comment]
Voilà qui est mergé :)
