### ISSUE TITLE
Interprétation des textes des modales

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1452]
Les textes des modales ne sont jamais intérpretées. Par exemple, le texte issus de la demande de validation d'un article ou d'un tutoriel (bien qu'il ne s'agisse pas d'un champ de type `textarea`) est reproduit tel quel, sans retours à la ligne. C'est également le cas du texte de signalement d'un post.

**Comment by Alex-D** [comment]
Je tiens à signaler que le fait que ça sorte des modales n'est pas lié techniquement, c'est juste qu'il se trouve que les zones de saisie concernées sont globalement celles qui sont dans les modales (validation, signalement, ...)

**Comment by Eskimon** [comment]
J'ai le sentiment que globalement c'est réglé avec ca non ? https://github.com/zestedesavoir/zds-site/pull/1548

**Comment by Alex-D** [comment]
Je confirme pour l'avoir testé que c'est bon. So, it's closed :)
