### ISSUE TITLE
Empêcher le référencement des tutos en beta

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#1453]
On a actuellement des erreurs 500 dans le Google Webmaster Tools sur les tutoriels en beta. 

Donc si un tuto est en beta il ne doit pas être référencé, car l'url change dès que l'on met à jour son tutoriel, pour cela  il faut afficher le balise meta suivante : 

`<meta name="robots" content="noindex">`

**Comment by Eskimon** [comment]
C'est réglé !
