### ISSUE TITLE
Adresse mail de contact inutilisables

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1454]
Certaines pages (au moins la page de contact et les CGU) utilisent l'adresse association@zestedesavoir.com ; or si j'ai bien compris seules certaines personnes (CA de l'association) peuvent envoyer des informations sur cette adresse...

Il faudrait :
- Soit l'ouvrir à tous
- Soit changer l'adresse par une adresse utilisable par tous (mais qui ?)

**Comment by firm1** [comment]
On ne pourrais pas tout simplement rediriger "association@zestedesavoir.com" vers l'adresse gmail de comm qui, elle rajouterai une règle de redirection vers le groupe CA ?

**Comment by Eskimon** [comment]
Du nouveau ?

**Comment by Eskimon** [comment]
Ping !

**Comment by gustavi** [comment]
Est-ce que c'est vraiment une issue ça ?

**Comment by ChantyTaguan** [comment]
Plop ! Cette adresse est présente sur la page "asso" et sur la page "contact". Il serait bon de trouver une solution. Soit on vire cette adresse purement et simplement, et tout passe par communication@@zestedesavoir.com, soit on débloque association@zestedesavoir.com, mais en l'état, ça fait pas sérieux...

**Comment by firm1** [comment]
Juste pour dire qu'en plus de la page asso et de la page contact, cette adresse est présente aussi dans les CGU. D'un point de vue légal ça ne fait pas très propre.

Je propose qu'on adopte l'idée de @ChantyTaguan ici, en remplaçant temporairement l'adresse de l'asso par communication@zestedesavoir.com.

Pour celà, rien de plus simple que d'aller modifier dans le setting de prod le paramètre [suivant](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L313) avec la bonne adresse. Et le changement sera repercuté sur toutes les pages.

**Comment by firm1** [comment]
> Je propose qu'on adopte l'idée de @ChantyTaguan ici, en remplaçant temporairement l'adresse de l'asso par communication@zestedesavoir.com.

[ça c'est fait](http://zestedesavoir.com/pages/contact/).

**Comment by Eskimon** [comment]
Le ticket est resolu via l'utilisation de la boite mail de communication non ? On peut fermer ?

**Comment by Eskimon** [comment]
ping !!

**Comment by ChantyTaguan** [comment]
Plop ! Le ticket étant toujours ouvert, je profite de celui-ci (ce sera l'occasion de le fermer ^__^). L'adresse email communication@zestedesavoir.com semble ne plus fonctionner. Je ne sais pas depuis quand mais je soupçonne la migration sur le nouveau serveur.

Je peux ouvrir un nouveau ticket si vous préférez mais vu que le titre correspondait nickel...

**Comment by ChantyTaguan** [comment]
Ping ? C'est quand même pas mal gênant que l'asso/la comm ne puisse plus être contactées...
