### ISSUE TITLE
Multi ajout de destinataires dans les MPs

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1457]
Pour le moment, il est possible d'ajouter le même destinataires plusieurs fois dans dans un MP. Ça n'impacte heureusement pas l'envoi du MP (qui n'est pas envoyé en double), c'est une considération qui est plutôt d'ordre esthétique dans ce cas.

**Comment by gustavi** [comment]
Corrigé dans #1886, je ferme.
