### ISSUE TITLE
On devrait télécharger les archives de tutoriels en ZIP et non en tar

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1458]
Ainsi que discuté avec la PR #1342, le choix du tar pour le format des archives de tutoriels est certes facile à mettre en place du coté code mais pas forcément facile à employer, car il s'agit d'un format qui n'est pas utilisable par défaut sur Windows. Pour assez peu de coup de développement, je pense qu'il serait intéressant de passer à des archives au format zip, qui sont elles accessible par défaut sous Windows.

**Comment by pierre-24** [comment]
Je prend !

**Comment by Eskimon** [comment]
Ca roule !
