### ISSUE TITLE
Groupe "dev"

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#146]
Je propose d'ajouter un groupe d'utilisateur au site, "dev" qui serait invisible de l'extérieur (ces membres n'auraient pas de badges visibles).

Les membres de ce groupe, temporaire ou permanent en fonction de leur implication et des besoins, auraient alors accès à certaines informations et données supplémentaires sur le site, inutile pour le commun des membres, mais utiles pour deboguer.

Par exemple : A priori je vais m'occuper de la conversion vers le markdown de pandoc et vers les formats pdf et ebooks qui en résultes. Je prépare la fonctionnalité avec des codes markdown de tests puis, quand ce sera terminé, je pourrais vérifier le résultat avec les tutos qui seront importés. Cependant, à ce moment là, ou plus tard lorsque le site sera lancé, des problèmes pourront arriver : rendu du pdf différent ce que attendu voir aucun pdf si pandoc plante à cause du markdown mal formé. Pour deboguer ça, j'aurais besoin du markdown d'entrée, de référence, qui est envoyé en transformation (concaténation des différentes parties + meta données). Ce fichier n'a aucun besoin d'etre fournit aux membres, eux ne devraient pouvoir que télécharger le pdf ou l'ebook (voir visualiser le html en entier). Mais ce fichier me serait très utile pour résoudre ces bugs. Un bouton "telecharger le fichier md" pourrait alors etre ajouté pour me permettre de le récupérer, ou tout autre dev s'en occupant. Il ne serait alors visible qu'aux membres du groupe dev. 

Cet exemple illustre, je pense, bien la problématique : permettre aux dev de récupérer des infos et données intermédiaires. Je ne pense pas par contre, pour des raisons de securité, que les membres dev aient forcément à etre staff tout comme le groupe "dev" ne devrait permettre que de récupérer des infos et données, mais pas de modifier des données en prod.

**Comment by firm1** [comment]
Je comprend bien l'utilité de cette catégorie dev, mais l'inconvénient c'est que cela donne un accès (même si c'est pour des correctifs) aux données sensibles en production.

Le dev devrait normalement pouvoir s'en sortir avec une description du bug, ainsi que la méthode de reproduction de celui-ci, accompagné par exemple du log de l'erreur.

Et pour celà, je préfère mettre en place le [logging de django](https://docs.djangoproject.com/en/dev/topics/logging/) , qui, pour chaque type d'erreur va alerter la mailing list des developpeurs.

Il suffira donc de virer de la ML ceux qui ne veulent pas être tenu au courant.

L'idée au final étant de ne pas donner accès à du contenu à n'importe qui en prod sous pretexte qu'on est dev.

**Comment by cgabard** [comment]
> Je comprend bien l'utilité de cette catégorie dev, mais l'inconvénient c'est que cela donne un accès (même si c'est pour des correctifs) aux données sensibles en production.

C'est pourquoi je proposais, entre autre, que l'on ne reste pas de manière permanente à ce groupe. De plus, si on sait que certaines données sont sensibles, il suffit de ne pas les mettre accessible au groupe dev. Une donnée trop sensible ne devrait etre accessible qu'à l'admin qui peut choisir de donner ce genre d'infos à d'autres dev au besoin. Cependants certaines infos pourraient être dispo sans que ce soit dangereux (cf mon exemple).

> Le dev devrait normalement pouvoir s'en sortir avec une description du bug, ainsi que la méthode de reproduction de celui-ci, accompagné par exemple du log de l'erreur.

Si pandoc plante pendant la conversion en pdf d'un big tuto, au moment du passage latex -> pdf, je fais comment sans les sources pour évaluer le lieu qui pose prob ? Il va me cracher une erreur latex, je n'aurais pas le latex qu'il a généré ni même le markdown dans son ensemble qui me permetrait de reproduire le bug. Dans un tel cas je peux t'assurer qu'il y a 90% de chances que je te réponde "file moi le md qui reproduit ça, sinon je fais rien". Car tester une a une toutes les mini partie d'un big tuto, en espérant que ce ne soit pas l'assemblage qui ai posé prob, non merci.

> Et pour celà, je préfère mettre en place le logging de django , qui, pour chaque type d'erreur va alerter la mailing list des developpeurs.

Mon but n'est pas d'etre au courant d'un bug, mais de pouvoir résoudre des issues qui vont forcément arriver car le rendu pdf ne sera pas exactement comme prévu dans un big tuto de 500 pages. C'est tres différent. Il peut très bien ne pas y avoir d'erreur dans les logs mais avoir un prob de rendu.

Au final je cherchais un moyen de généraliser mon besoin mais je vais plus simple : Je vais avoir besoin, rapidement, d'un bouton "télécharger le md" qui me fournirat le md qui est envoyé à pandoc. Tant que j'ai ce bouton ou un moyen simple d'accéder à ce fichier, peut m'importe comment c'est géré en fait.

**Comment by ShigeruM** [comment]
> Ce fichier n'a aucun besoin d'etre fournit aux membres, eux ne devraient
> pouvoir que télécharger le pdf ou l'ebook (voir visualiser le html en
> entier).

Pourquoi ne pas permettre aux membres d'avoir leur export md ? Ce serait
simplement un format supplémentaire accessible. Si la mécanique est faite
pour les dev, autant la mettre à la dispo de tous. Du coup ça répondrait à
ton besoin à court terme mais aussi au besoin de qui le voudra.

Le 6 février 2014 13:05, Christophe Gabard notifications@github.com a
écrit :

**Comment by cgabard** [comment]
Oui et non shig. En fait cela ne correspond pas vraiment aux sources.

Les sources d'un tuto, c'est un dossier contenant l'ensemble des fichiers markdown, les images et un fichier TOC avec les meta données. Celui-ci on peut permettre le téléchargement, au moins à l'auteur (en public je ne sais pas). Ce qui m'interesse moi c'est un fichier markdown intermédiaire qui est construit en concaténant tous les markdown individuels et rajoutant dedans les noms de chapitres/parties et les meta données. En soit il n'a pas à sortir lui normalement, c'est vraiment une conversion intermédiare.

Cela-di, si on peut télécharger les sources d'un tutos, je devrait pouvoir générer l'intérmédiaire en local pour reproduire les bugs.

**Comment by ShigeruM** [comment]
Ah ok je vois. Bon je retourne à mes occupations et j'arrête de m'immiscer
dans les discussions techniques. :-)

Le 6 février 2014 13:29, Christophe Gabard notifications@github.com a
écrit :

**Comment by cgabard** [comment]
Non non reste ! D'autant plus que la disponibilité des sources que tu souligne est interessant à poser.

**Comment by firm1** [comment]
> Pourquoi ne pas permettre aux membres d'avoir leur export md ? Ce serait
> simplement un format supplémentaire accessible.

je plussoie cette proposition pour ton cas @cgabard . On peut très bien donner la possibilité aux auteurs (et uniquement à eux) de downloader la version "compilée" markdown.

Ainsi, si un membre te signale un pb, tu lui demandes de t'envoyer cette version compactée pour bosser dessus. Elle est toujours générée même si la conversion vers latex échoue.

Mais j'ai vraiment une réticence à offrir à n'importe qui avec son compte dev, les droits sur les versions sources d'un tutoriel dont il n'est pas l'auteur.

**Comment by dreherch** [comment]
En même temps, c'est un droit dont dispose tout le staff, pour pouvoir
corriger les fautes d'orthographe des tutos.

**Comment by cgabard** [comment]
@firm1 : A supposer que c'est l'auteur du tuto qui se rend compte du prob.

Je crois que ce que tu n'avais pas bien compris c'est que je ne comptais pas donner ces droits à n'importe qui ni en permanence mais qu'ils existent pour les donner exceptionnellement au besoin.

Après tant que tu permet de télécharger ce fichier intermédiaire, moi je m'en fout.

**Comment by firm1** [comment]
> Je crois que ce que tu n'avais pas bien compris c'est que je ne comptais pas donner ces droits à n'importe qui ni en permanence mais qu'ils existent pour les donner exceptionnellement au besoin.

Je sais bien, mais ça me fais souvent peur ce genre de choses. Surtout que si ce statut (dev) existe avec des accès spécifique, je n'ai pas forcément envie de me demander si je dois faire confiance à quelqu'un qui contribue au code, avant de lui filer ce statut.

**Comment by cgabard** [comment]
Pour moi ce n'est pas ça que tu aurais dut te demander, mais plutot "est ce que ces infos sont critique ?"

En l'occurence mon exemple montrait bien que je ne voulais pas mettre a disposition des infos sensibles, juste des trucs utiles et non dangereux. Du coup si aucune données sensibles n'est mit a disposition de ce groupe, pas de soucis pour ajouter quelqu'un.

Bref, pas d'accord, je ferme, tant que je peux récup le md je m'en fout un peu :)

**Comment by firm1** [comment]
Autant dans ton exemple les données ne sont pas critiques, autant dans certains cas, on peut toucher à des trucs critiques. C'est pour ça que ça me refroidi un peu. Normalement tout les trucs pas critiques seront aussi dispos via le staff. Ainsi le dev qui n'est pas staff peut demander un export de ce qu'il veut à un membre du staff.

'fin bref, c'est un statut à étudier tout de même, pour bien définir ces accès afin de ne laisser aucune porte ouverte. je penses donc qu'on réouvrira cette issue.

**Comment by cgabard** [comment]
Certes mais pour moi staff et dev sont deux status différents.

Typiquement un staff n'a pas besoin de ce markdown intermédiare. Tout comme un dev n'a pas besoin d'avoir des pouvoir de modération (sauf si il veut deboguer un truc dedans).

A partir du moment que tu sais que tu as un groupe dev, tu ne met pas à dispo des infos critique. Je comprend pas trop le soucis puisque pour qu'une infos soit visible à un membre dev, il faudrat que ça passe dans le processus de PR & co.

Et encore une fois, pour moi, les membres de ce groupe n'ont pas à être permanent.

Enfin bref

**Comment by firm1** [comment]
Bon, en attendant je te mets à dispo par exemple le téléchargement version Markdown (juste pour les staff actuellement).

Suffit d'aller par exemple sur un [tuto précis](http://preprod.zestedesavoir.com/tutoriels/16/fonctionnement-des-ordinateurs-de-zero/) et en bas du sommaire, tu auras les version markdown pure sur lesquelles je passe la commande pandoc.

**Comment by cgabard** [comment]
thanks
