### ISSUE TITLE
Téléchargement de l'archive : pas de versionning

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1460]
Quand on télécharge l'archive d'un tutoriel, c'est toujours la dernière version (donc _draft_) qui sort, et non la version en ligne.

**Comment by Eskimon** [comment]
Est-ce vraiment un problème ? C'est plutôt normal non ? (a moins que tu parles du cas ou une personne non auteur télécharge la version public ?)

**Comment by pierre-24** [comment]
C'est de ça dont je veux parler. En gros, sur la version publique des tutos, actuelement, y'a moyen d'avoir les modifs en preview :p

**Comment by pierre-24** [comment]
Je prend, j'ai trouvé comment faire et je vais coupler ça à #1458 (à l'aide de `ZipFile.writestr()`, [voir ici](https://docs.python.org/2/library/zipfile.html#zipfile.ZipFile.writestr) ). Comme ça, on fait pas un fix pour les tar qui sert à rien.

**Comment by Eskimon** [comment]
Tout marche ici !
