### ISSUE TITLE
Mise en cache des archives

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1463]
Les archives correspondants au tutoriels et articles dans leur version publiée devrait être mis en cache afin de ne pas être régénérée à chaque fois.

**Comment by SpaceFox** [comment]
Je pensais que c'était fait tiens. Mais AMHA c'est du back et pas de l'infra.

**Comment by pierre-24** [comment]
C'est pas le cas et quand bien même je ne sais pas ou j'irais stocker ça dans la structure du site actuellement :)

**Comment by SpaceFox** [comment]
Est-ce toujours d'actualité avec la ZEP-12 ?

**Comment by pierre-24** [comment]
Nope, ça, c'est corrigé, tout est mis en cache sur la version publiée. Ça fait partie du travail pour "éviter les machins inutiles pour que ça aie vite" :)
