### ISSUE TITLE
Possibilité de mettre un tuto en favori

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#147]
Actuellement, il est impossible de mettre un tuto en favori pour y avoir accès rapidement.

Une bonne chose serait de proposer cette fonctionnalité.

**Comment by cgabard** [comment]
Ce ticket est prit en charge par la zep 06. on a aucun interet a garder ce ticket ouvert je pense. Ce n'est qu'une sous-partie de la zep 06. La zep n'étant pas validé -> A fermer

**Comment by gustavi** [comment]
Oui. Je ferme.

**Comment by Eskimon** [comment]
Lien vers la ZEP 6 : http://zestedesavoir.com/forums/sujet/678/zep-06-favoris-et-autres-suivi-dactivite/

**Comment by gustavi** [comment]
(Merci @Eskimon de passer derrière moi :D )
