### ISSUE TITLE
[Admin Tutos] URL canonique

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#1470]
Lorsqu'on souhaite demander la validation d'un tuto, ou en publier un, on doit rentrer un champ "URL de la version originale", pour renseigner correctement le lien canonical dans le cas des tutos importés d'autre sites.

C'est très bien, sauf qu'à chaque nouvelle demande de validation ou publication d'un cours dont l'URL est pourtant déjà renseignée, on doit la fournir à nouveau...

Il faut pré-remplir le champ avec l'URL déjà enregistrée lors de la précédente publication, c'est pas viable autrement.

**Comment by Eskimon** [comment]
Ca m'a l'air deja réglé dans le code :

https://github.com/zestedesavoir/zds-site/blob/581572fcd7dfd9c2487ab43a175b9fb9701e3a8a/zds/tutorial/views.py#L888

(et ca c'est pour la version actuellement en ligne : https://github.com/zestedesavoir/zds-site/blob/9dc0e98d371047ba5c8fbcae2d29b611fcc7a26c/zds/tutorial/views.py#L725 )

Qqun pour confirmer ?

**Comment by Coy0te** [comment]
Et c'est censé marcher en prod ? Ou bien ça n'a pas encore été poussé ?

2014-09-08 9:31 GMT+02:00 Eskimon notifications@github.com:

**Comment by firm1** [comment]
D'après les link d'Eskimon, c'est déjà en prod

**Comment by Coy0te** [comment]
Vous reproduisez, ou c'est juste moi ?

Testez de demander à valider le tuto Pixologic par exemple; il contient
déjà un canonical mais ne le préremplit pas lors de la demande de
validation.

**Comment by Eskimon** [comment]
Non, d'apres mes liens en prod ce n'est pas present, mais si qqun essaie de reproduire sur une version a jour en local ca devrait etre bon.

Desole je me suis mal exprime plus tot. En resume : OK dans le code (lien 1) mais pas encore en prod (lien 2).

**Comment by Eskimon** [comment]
Je confirme après test en local, c'est déjà présent dans la branche de dev. Je ferme.
