### ISSUE TITLE
Le sous titre est souligné au hover dans les MP

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1474]
Sur la liste des MP, lorsqu'on passe la souris sur le mp, le Titre du MP se souligne. Normal. Le truc pas beau c'est que le Sous-titre du mp se souligne aussi…

**Comment by Alex-D** [comment]
C'est pas un bug, c'est un lien, il est souligné, c'est normal. Il s'agit là d'un simple problème d’esthétique. Merci d'éviter de tout mettre dans "BUG" qui me semble regrouper les choses les plus urgentes à corriger.

**Comment by firm1** [comment]
Dans ce cas, c'est un problème de sémantique, un sous titre ne devrait pas être un lien. Et donc c'est bien un bug il me semble.

**Comment by Alex-D** [comment]
Pourquoi donc le sous-titre ne devrait pas être dans le lien ? S'il n'est pas dans le lien, un aveugle qui liste les liens n'aura que le titre et perdra l'information du sous-titre, renforçant alors l'idée que j'ai émise à ce sujet en disant que les sous-titre sont inutiles.

**Comment by Eskimon** [comment]
Et donc ?

**Comment by Alex-D** [comment]
Donc, je masque le soulignement au survol sur le sous-titre et on est OK ?

**Comment by Eskimon** [comment]
Moi ca me va :)

**Comment by firm1** [comment]
moi aussi

**Comment by Eskimon** [comment]
réglé
