### ISSUE TITLE
Plus d'icones pour le design

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1475]
Actuellement le site dispose d'un nombre assez limité d'icones il en faudrait un peu plus pour illustrer certains bouton. La liste actuelle des icones disponibles est [celle-ci](https://github.com/zestedesavoir/zds-site/tree/dev/assets/images/sprite%402x).

Il manque donc : 
## Des icones sociales

La [ZEP-07](http://zestedesavoir.com/forums/sujet/709/zep-07-champs-personnalises-dans-le-profil/), le footer, ainsi que [cette PR](https://github.com/zestedesavoir/zds-site/pull/1424) en ont/auront besoin.

Il s'agit ici de déssiner les icones pour facebook, twitter, google+, foursquare, github, etc.
## Les autres icones
- Une icone dédiée à l'affichage d'un post masqué : sur mobile, on a la même icone pour afficher un message masqué et pour juste le consulter sans l'afficher. Il faut donc distinguer les deux
- Une icone "Etre notifié par courriel" : actuellement on utilise l'icone de citation d'un message pour ça. Ce n'est pas ergonomique

Toutes les icones devront respecter le format existant pour rester cohérentes dans la sprite.

Il y'en a peut être d'autres (dans ce cas il faudrait compléter la liste)

**Comment by Alex-D** [comment]
Il faut une liste précise des icônes souhaitées, là comme ça on ne peut pas faire grand chose sans qu'on se pointe deux jours après avec un "en fait faudrait rajouter cette icône là".

En soit, c'est assez simple d'en rajouter, mais c'est mieux de tout faire d'un coup, notamment s'il y a de l'automatisation à faire.

**Comment by firm1** [comment]
> Il faut une liste précise des icônes souhaitées, là comme ça on ne peut pas faire grand chose sans qu'on se pointe deux jours après avec un "en fait faudrait rajouter cette icône là".

Itération, itération ...

Voilà déjà une liste des icones identifiée. On ne pourra jamais prévoir toute les icones du site jusqu'à la v42. De toute façon ce n'est pas comme ci rajouter une icone demain allait obliger à revoir toutes les autres.

**Comment by Alex-D** [comment]
Je me doute, mais itération = moins d'automatisation = perte de temps. Si à cet instant tu sais de quoi tu as besoin, liste-le et on gagnera tous du temps :)

**Comment by firm1** [comment]
> Je me doute, mais itération = moins d'automatisation = perte de temps.

Je ne vois pas a quel moment on perd du temps, il suffit de rajouter les icones adéquates dans le dossier adéquat et gulp les mets dans la sprite adéquate et voila. D'autres personnes pouront se servir ensuite.

> Si à cet instant tu sais de quoi tu as besoin, liste-le et on gagnera tous du temps :)

La liste que j'ai mis dans le premier post est la liste de celles dont le besoin se fait sentir, donc c'est "à faire" de toute façon.

**Comment by Alex-D** [comment]
> Je ne vois pas a quel moment on perd du temps

Faire des icônes, les redimensionner, les mettre aux coloris du site, ça prend du temps si on veut le faire correctement, d'où une certainement automatisation. Pour la suite, en effet, c'est très simple.

> La liste que j'ai mis dans le premier post est la liste de celles dont le besoin se fait sentir, donc c'est "à faire" de toute façon.

Okédac !
