### ISSUE TITLE
Lisser le logo du site

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1476]
Lorsqu'on rapproche un peu nos yeux du logo, on constate qu'il est pas mal pixélisé, et ça ne rend pas joli.

Il faudrait un truc assez propre en svg.

**Comment by Alex-D** [comment]
Le logo est déjà en `@2x`, s'il est pixelisé, c'est soit que ton écran est en `@3x` (rare pour l'instant) soit qu'il a une mauvaise qualité.

**Comment by firm1** [comment]
Perso quand je vais ici : http://zestedesavoir.com/static/images/logo@2x.png je vois encore des gros pixel partout.

**Comment by SpaceFox** [comment]
Je confirme que le logo @x2 est baveux.

**Comment by Alex-D** [comment]
Oh, en effet, ça doit être l'ancienne version qui a traversé les époques... je corrigerais ça, on a une version vectorielle dans les cartons de toute façon.
