### ISSUE TITLE
Les titres des tutoriels et articles long sont invisibles

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1477]
Actuellement dans la [liste des tutoriels](http://zestedesavoir.com/tutoriels/), le texte affiché est limité à 35 caractères. Pour les tutoriels avec un long titre, ce n'est pas très pratique.

La preuve en image

![](http://i.imgur.com/3JpziaR.png)

Il faudrait : 
- soit réduire la taille de la police
- soit faire passer le texte sur plusieurs lignes

**Comment by Alex-D** [comment]
Il n'y avait pas déjà une issue à ce sujet ?

Sinon la solution qui sera adoptée ne sera ni l'une ni l'autre, mais afficher le titre complet au survol.

EDIT : Et aussi, passer sur 2 colonnes au lieu de 3 pour avoir plus de largeur.

**Comment by SpaceFox** [comment]
Je ne trouve pas ça pratique personnellement, devoir survoler pour avoir le
titre complet.

Le 8 septembre 2014 14:00, Alexandre Demode notifications@github.com a
écrit :

**Comment by Eskimon** [comment]
http://zestedesavoir.com/forums/sujet/823/page-des-tutoriels/

**Comment by cgabard** [comment]
> Je ne trouve pas ça pratique personnellement, devoir survoler pour avoir le titre complet.

Moi non plus. Ça a été décidé/acté où ça ? J'ai pas vu passer le débat

**Comment by Alex-D** [comment]
La solution optée dans cette PR est : 
- afficher le titre complet au survol
- diminuer le nombre de colonnes pour laisser plus de place en largeur et donc voir le titre de façon plus ample

On ne peut pas garantir un affichage optimal sur toutes les résolutions. Quand Firm1 dit "c'est limité à X caractères" c'est faux. C'est limité à X caractères par rapport à sa résolution, qu'il n'a pas mentionné et donc je ne peux pas tester dans son cas précis (et ça serait inutile). Je me suis donc arrangé pour qu'il y ait un maximum de texte visible sur la plupart des résolutions.

**Comment by Alex-D** [comment]
> Ça a été décidé/acté où ça ?

Nul part.

**Comment by cgabard** [comment]
> >    Ça a été décidé/acté où ça ?
> 
> Nul part.

Il faudrait peut être commencé par ça donc, non ?

**Comment by Alex-D** [comment]
Coucou, juste pour dire que j'avais fait une PR qui résolvait le problème il y a deux mois et que le débat n'a pas été ouvert (pour moi il n'y a pas de débat, donc je ne l'ouvrirais pas). On a donc actuellement toujours le problème.

Mais, pour moi ça rentre dans le cadre de la réfacto de l'accueil : le design d'un item vers un tutoriel va changer sur l'accueil et donc ça doit changer sur la liste des tutoriels également. Pareil pour les articles. Est-ce que ça vous semble logique ?

**Comment by gustavi** [comment]
Je suis d'accord avec ça.

**Comment by Eskimon** [comment]
Dites, les elements sont tous dans des h3. Est-ce qu'on pourrait pas avoir le titre aussi dans l'attribut "title" des h3 pour ainsi avoir un titre qui s'affiche au survol en tooltip ? Ca marchera toujours, c'est pas un bricolage js ou quoi que ce soit, les gens sont habitues a ce genre de comportement...

Maintenant est-ce qu'une mauvaise pratique web l'en empeche ?

Je dis ca parce qu'a l'heure actuelle on a plus de tooltip...

**Comment by ghost** [comment]
Je prends.
