### ISSUE TITLE
Lien vers les réseaux sociaux dans le footer

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1486]
Lorsqu'on arrive sur le site, on ne retrouve aucun lien vers les réseaux sociaux. C'est pas tip top pour nous.

Solution : rajouter dans le footer au mois notre twitter et facebook.

**Comment by SpaceFox** [comment]
Si possible, éviter que cette feature oblige l'utilisateur à télécharger les tonnes de JS et de traceurs desdits réseaux sur chaque page.

**Comment by Alex-D** [comment]
On va se contenter de liens, je suis contre les boutons qui affichent le nombre de personnes qui ont aimé/follow car ça alourdi pour rien les pages.

**Comment by poulp** [comment]
doublon #1436

**Comment by firm1** [comment]
Pas faux
