### ISSUE TITLE
Les catégories de tutoriels suivent un ordre d'affichage inconnu

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1487]
Que se soit sur la page d'acceuil ou dans la topbar, on ne sait pas vraiment quel est l'ordre d'affichage des catégories et sous catégories.

Solution : définir des positions pour les catégories (pour éviter d'avoir la catégories Autres en première position par exemple) et ranger par ordre alphabetique pour les sous catégories.

**Comment by gustavi** [comment]
Corrigé avec #1797
