### ISSUE TITLE
Positionnement du bouton sur la page de recherche avancée

### ISSUE THREAD

**Issue by LucasGrugru** [zestedesavoir/zds-site#1492]
Il semble y avoir un problème de positionnement du bouton d'envoi sur la page de recherche avancée. Le bouton se place en dessous de la barre de recherche (cf. screen).
Je suis sur Mint Cinnamon/FF v30.0

![sans titre](https://cloud.githubusercontent.com/assets/1902806/4216702/a79d695a-38dd-11e4-8366-c92b21f48401.png)

**Comment by Alex-D** [comment]
"This is not a bug, this is a feature"

C'est complètement voulu, ça utilise le design global des formulaires, ils sont tous comme ça :)

Toutefois il y a un correctif qui va arriver prochainement en prod qui va espacer le champ et le bouton pour qu'ils ne soient plus collés.
