### ISSUE TITLE
Augmenter la limite LaTeX

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1493]
Les bigtutos ont du mal à passer le process de validation car Latex (texlive) bloque au bout d'un certain nombre de caractères. C'est en tout cas ce qui ressort dans les logs d'échec de conversion pdf.

Il faudrait donc augmenter la limite des caractères.

Attention : ce n'est pas la même problématique que [cette issue](https://github.com/zestedesavoir/zds-site/issues/1024)

**Comment by Eskimon** [comment]
Du nouveau ? Le tuto Arduino arrivera bientot dans la validation et est assez consequent en termes de volumes et d'images je pense... Ca permettera un bon gros tests des familles :D

**Comment by SpaceFox** [comment]
On a une idée du où et du combien ?

**Comment by Coy0te** [comment]
On a des exemples de big-tutos dont la conversion PDF foire ?

**Comment by SpaceFox** [comment]
Ma précédente question est toujours d'actualité.

2014-12-11 14:36 GMT+01:00 Coyote notifications@github.com:

**Comment by firm1** [comment]
Il faut regarder le fichier de log pandoc sur la prod

firm1

**Comment by Eskimon** [comment]
> On a des exemples de big-tutos dont la conversion PDF foire ?

Pas de pdf pour ce tuto tres recent :https://zestedesavoir.com/tutoriels/688/administrez-vos-bases-de-donnees-avec-mysql/

**Comment by gustavi** [comment]
Quelqu'un a tenté quelques chose sur la préprod ? Je peux essayer de voir ça si vous voulez.

**Comment by firm1** [comment]
> Pas de pdf pour ce tuto tres recent :https://zestedesavoir.com/tutoriels/688/administrez-vos-bases-de-donnees-avec-mysql/

Pour info je viens de réussir à générer le pdf de ce tuto en republiant le tuto après avoir remplacé les caractères interdits par pandoc qui étaient présent dans le tuto.

Notons que le tuto mysql contient  _904940_ caractères et _25_ images alors que celui sur arduino contient _794 690_ caractères et 342 images.

Donc si le tuto mysql a réussi a passé, je crois que bon nombre de tuto passerons aussi, à la seule conditions qu'ils ne contiennent pas de caractères interdits par pandoc.

**Comment by Coy0te** [comment]
De quels caractères il s'agit ? On peut inclure ça dans nos règles internes
de validation pour éviter ce problèmes.

**Comment by gustavi** [comment]
Sur celui d'Arduino j’obtiens l'erreur suivante : 

```
pandoc: Error producing PDF from TeX source.
! Missing $ inserted.
<inserted text> 
                $
l.12597 ... obtient : \$ \frac{458 \times 5}{1024}

----> Arduino : Premiers pas en informatique embarquée
```

Après vérification c'est bon dans le tuto Arduino ...

``` markdown
+ Avec un produit en croix on obtient : $ \frac{458 \times 5}{1024} = 2.235V $ ;
+ En utilisant le pas calculé plus haut on obtient : $ 458 \times 4.88 = 2.235V $ .
```

Et après une autre vérification c'est pas un problème de nombre de caractères ou de nombre de lignes ou de nombre de formules mathématiques.

Je sèche là.

EDIT : une piste de @pierre-24 : le « \ » dans « \$ » qui ne devrait pas se trouver là ?

**Comment by pierre-24** [comment]
À force d'essais erreurs, j'ai fini par trouver : ce code plantera `$ a + b = c $` mais ce code ne plantera pas `$a + b = c $`. Autrement dit, pas d'espace directement après le premier `$` d'une formule. Le bugfix me semble relativement _obvious_, mais c'est coté pandoc qu'il faut le faire (ou au moment de la génération dans [export_tutorial_to_md()](https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/tutorials.py#L116) avec du _find and replace_ un peu cochon).

**Comment by gustavi** [comment]
OK gg @pierre-24 ! PING @cgabard !

**Comment by Eskimon** [comment]
Arf c'est con, je mettais un point d'honneur à en mettre partout... va falloir que je fasse un gros traitement de masse sur le tuto du coup...

**Comment by pierre-24** [comment]
Un trouver remplacer :/

**Comment by Eskimon** [comment]
Oui, mais j'aimerais garder un espace avant et apres la formule pour le confort de lecture, donc faut pas que je fasse un chercher/remplacer trop naif sinon je vais perdre ces derniers ;)

**Comment by cgabard** [comment]
C'est étrange mais ça supposerai un bug coté pandoc ça, non ?

**Comment by pierre-24** [comment]
Plus que très probablement. On a aussi #1927 dans le même genre, si ça t'intéresse :)

**Comment by Eskimon** [comment]
Je suppose que l'on peut laisser trainer ce ticket en attendant la ZEP-5 ?

**Comment by cgabard** [comment]
Je serai pour le fermer. On va pas maintenir la version actuel et les bugs les concernant ne seront plus valide avec le basculement de la Zep-5. Je le fermerai en "won't fix"

**Comment by Eskimon** [comment]
Ca me va :)

Motif de fermeture : plus d'actualité et won't fix !
