### ISSUE TITLE
Revoir la structure des chapitres des tutoriels

### ISSUE THREAD

**Issue by ghost** [zestedesavoir/zds-site#1498]
Bonjour à tous.

Je suis en train de rédiger un tutoriel, et il y a un truc qui m'agace dans la structure : quand on créé un chapitre, on doit obligatoirement rédiger une intro et une conclusion à ce chapitre. Je trouve ça dommage car pour ceux qui comme moi ne veulent pas mettre d'intro et de conclusion à chaque chapitre, ça fait très moche de voir écrit « Il n'y a aucune introduction » au milieu du tuto.

Serais-ce donc possible de laisser l'intro et la conclusion de chaque chapitre comme une option ? Du genre avec un menu « Ajouter une introduction », etc. ?

Merci pour l'attention portée à ma demande.
Vinm.

**Comment by firm1** [comment]
Actuellement les introduction et conclusion sont déjà optionnels. Le marqueur que tu vois en zone de rédaction est là juste pour pas que l'auteur l'oublie, mais une fois publié, on ne voit plus c'est fameux marqueur "Il n'y a aucune introduction".

**Comment by ghost** [comment]
Okay c'est super, merci beaucoup ! :)
