### ISSUE TITLE
Improve date display in tutorial history view

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#15]
Actuellement, l'affichage de la date dans l'historique de modification d'un tutoriel n'est pas une date à proprement parlé. C'est une succession de chiffre (cf. image ci-dessous).
L'idée est d'afficher la date correctement dans cette vue dans un format lisible par les humains.

![](http://i.imgur.com/s37bJrq.png)

Cette date correspond au retour de la fonction [suivante](http://pythonhosted.org/GitPython/0.3.1/reference.html#git.refs.log.RefLogEntry.time) de la lib gitpython.

**Comment by Taluu** [comment]
... C'est pas un timestamp unix ? :o

**Comment by firm1** [comment]
>  C'est pas un timestamp unix ?

Si, et je pense savoir comment le corriger. Mais je reporte déjà le bug pour ne pas l'oublier

**Comment by firm1** [comment]
Ce bug est désormais corrigé. La date et l'heure s'affichent désormais comme il faut.
