### ISSUE TITLE
Mauvais message lorsque l'on a pas les droits d'accès

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#150]
Lorsque je tente d'accéder à une page à laquelle je n'ai pas accès, je suis redirigé vers la page de login. Si je suis déjà connecté, la page de login redirige automatiquement vers une page où j'ai le message :

> Vous êtes déjà connecté.

Or, le souci est que cela devrait afficher un message type

> Vous n'avez pas les droits suffisants pour accéder à cette page.

Exemeple lorsque j'essaye d'accéder au lien suivant sans les droits nécessaires :

http://preprod.zestedesavoir.com/tutoriels/comparaison/18/alignement-memoire-et-endianess/%3Fsha%3Dc99a93842480fdc353d4504e896a3299e5ae34f8/

**Comment by firm1** [comment]
Le lien sus cité ne me donne pas plus d'informations, on dirait qu'il est erroné.

**Comment by Alex-D** [comment]
C'est un lien que tu as donné pour exemple de diff. J'ai tenté de le suivre. Quand bien même il est erroné je devrais avoir une 404. Si je n'ai pas les droits, je devrais avoir une 403.

Dans tous les cas, il y a un truc pas logique.

**Comment by firm1** [comment]
Bah, là moi je tombe sur un 404, elle a pas encore la design de la 404 finale parce que le site est en mode DEBUG free.

Donc, j'ai du mal a reproduire le bug que tu décris.

**Comment by GerardPaligot** [comment]
En fait, cette page est lancée automatiquement avec les annotations `@permission_required`. Si l'utilisateur n'a pas les permissions, il est automatiquement redirigé vers la page d'authentification.

Une solution propre serait de rediriger vers une page 403 Forbidden. Vous en pensez quoi ?

**Comment by firm1** [comment]
@GerardPaligot : +1

L'astuce étant de remplacer tout les `@permission_required('maclasse.ma_permission')` par `@permission_required('maclasse.ma_permission', raise_exception=True)` pour renvoyer des 403 à la place de la redirection vers la login url.

Plus d'information [ici](https://docs.djangoproject.com/fr/1.5/topics/auth/default/#the-permission-required-decorator):

**Comment by GerardPaligot** [comment]
PR ici : https://github.com/Taluu/ZesteDeSavoir/pull/161
