### ISSUE TITLE
Un menu alerte validations

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1503]
Aujourd'hui il existe un menu d'alertes modération qui montre le nombre d'alertes de modérations.

Il serait interessant d'avoir la même chose pour la validation, le compteur afficherait pour le staff, le nombre de tutoriels en attente de prise en charge d'un validateur. Et dans la zone déroulante on aura la liste des tutoriels triés par date d'envoi en validation.

**Comment by Alex-D** [comment]
Tu vois ça comment ?

Personnellement j'imagine qu'on garde une seule icône en haut (car sinon il faut refaire la version PC, tablette et mobile, pas cool) qui comptabilise tous les types d'alertes. Quand on l'ouvre on aurait des onglets pour alterner comme bon nous semble entre les diverses catégories.

On peut aussi imaginer que l'onglet afficher en premier est le dernier qui a été ouvert (via localStorage).

**Comment by firm1** [comment]
Je le vois assez basiquement en fait. 2 nouvelles icones à droite de celles des alertes modérations pour d'un coté les alertes validations et de l'autre, les alertes articles.

Si on mets tout dans la même icone elle deviendrait inutile car tout le monde n'est pas toujours concerné par tout les types d'alertes et ça serait contre productifs. Les 3 types d'alertes doivent avoir une bonne visibilité de manière indépendante.

**Comment by Alex-D** [comment]
Mettre 3 icônes comment ? Car là en l'état actuel, rajouter 2 icônes ça me semble carrément overkill et ça alourdir le design, sur mobile ça ne rentrera plus sur les petits devices et il y aura une grosse différence entre staff / non-staff.

**Comment by SpaceFox** [comment]
Fonctionnellement, il faut au moins 2 icônes : une pour la modération, et
une autre pour la validation (tous contenus).

Le 12 septembre 2014 17:50, Alexandre Demode notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
Ca me semble plus raisonnable. Même si le design n'a pas été pensé pour et du coup ça va demande un peu de travail pour que ça rentre dans tous les cas sans tout casser.

Du coup, on aurait :
- pour les membres : MP, Notifs, Paramètres, Avatar ;
- pour le staff : MP, Notifs, Modération, Validation, Avatar/Paramètres

Paradoxe spatial, il faut donc trouver une astuce à ce niveau.

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis plus d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.
