### ISSUE TITLE
Double clic sur le bouton répondre = 403

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1504]
[Via le forum](http://zestedesavoir.com/forums/sujet/1251/erreur-403-lors-dun-double-post)

Lorsqu'un utilisateur clic sur le bouton "Répondre" (ou sur un bouton en général je suppose), le bouton n'est pas bloque et donc le temps que la page revienne on peut recliquer sur le même bouton. Comme le site est bien fait on se prend une 403, mais c'est pas très agréable. Il faudrait bloquer le bouton une fois le premier clic dessus fait.

**Comment by Alex-D** [comment]
Voilà un petit patch qui devrait éviter à beaucoup d'être frustrés :)
