### ISSUE TITLE
Les articles n'ont pas de galeries

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1509]
C'est étrange, les articles n'ont pas de galerie automatique pour stocker leurs images et les partager entre auteurs. Est-ce bien normal ? Ne faudrait-il pas un comportement aligne sur celui des tutos (en attente la grosse refonte) ?

**Comment by artragis** [comment]
Peut-on ajouter un tag "zep12" pour indiquer que ce genre d'issue ou #1319  par exemple.
Parce que finalement c'est bien le refactoring des tutos et articles qui contiendra _par conception_ ce genre de débugage.

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
Implémenté, testé, migré, magique.

2015-04-16 14:26 GMT+02:00 Eskimon notifications@github.com:
