### ISSUE TITLE
La doc de déploiement de ZdS sur le serveur est outdated

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1510]
- L'adresse IP mentionnée dans [la doc](https://github.com/zestedesavoir/zds-site/blob/dev/doc/deploy.md) (`178.32.53.245`) pour la preprod est erronée.
- [Ici](https://github.com/zestedesavoir/zds-site/blob/dev/doc/deploy.md#clone-du-repo-et-configuration-de-prod) on demande de taper des commandes, sans aucune mention de l'user qui doit faire des `mkdir` et des permissions sur les répertoires
- `touch zds/settings_prod.py` et `vim zds/settings_prod.py` font doublons
- les config nginx sur `location /author-files/`, `location /roundcube/`, `location /stats/`, `location /teasing/` n'ont pas lieu d'être dans la doc
- Au niveau de la [conf solr](https://github.com/zestedesavoir/zds-site/blob/dev/doc/deploy.md#configuration-solr) le `directory=/opt/zdsenv/ZesteDeSavoir/apache-solr/example` n'est plus d'actualité

Et il y'a peut être encore autres choses.

**Comment by gustavi** [comment]
Une partie a été corrigée dans d'autres issues je pense aux IP notamment).

**Comment by firm1** [comment]
Cette issue est désormais corrigée.

**Comment by SpaceFox** [comment]
Heu, par quel miracle ? Il n'y a pas de PR mergée qui correspond à ce ticket.

**Comment by firm1** [comment]
ça a été fixé via la #2187
