### ISSUE TITLE
Erreur 500 si on essaye de lire un article pas encore publié

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1518]
Il suffit d'aller sur ce lien : http://zestedesavoir.com/articles/89/t/

L'article dont l'id est 89 est crée et en cours de rédaction, mais n'étant pas encore publié, si je tente d'y accéder comme s'il était déjà publié, je me prend une erreur 500 au lieu d'une 404.

Dans les logs on peut voir ceci :

``` bash
IOError: [Errno 2] No such file or directory: u'/opt/zdsenv/ZesteDeSavoir/articles-data/89_la-lifi-la-technologie-de-communication-par-la-lumiere/text.md.html'
```

**Comment by Eskimon** [comment]
Plus précisément:

```
Stacktrace (appel le plus récent en dernier) : 

  File "django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "zds/article/views.py", line 134, in view_online
    "r")
```

**Comment by Alex-D** [comment]
Validé, mergé, fermé.

Merci @Eskimon :)

**Comment by Eskimon** [comment]
Dans quelle version ce merge a t'il ete fait ?

**Comment by Alex-D** [comment]
C'était dans la 1.1, désolé.

**Comment by Eskimon** [comment]
Un truc m'échappe, si c'était dans la 1.1 le bug devrait pas être visible en prod' (ni en préprod')

**Comment by Alex-D** [comment]
Pourtant j'ai vérifié les dates et c'est bien en 1.1. Quand bien même ça serait 1.1b c'est quand même en prod. Et si c'est en 1.2, faut check sur la preprod pour en être sûr, mais je ne comprendrais plus rien à la logique du temps :-°
