### ISSUE TITLE
Possibilité d'accéder à un chapitre après sa suppression

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1519]
Comme [indiqué par Luthaf sur le forum](http://zestedesavoir.com/forums/sujet/1283/suppression-partielle-des-chapitres-sur-un-big-tuto/) :
1. Dans un onglet de navigateur A, créer un big tuto avec un chapitre.
2. Dans un onglet B, accéder à ce chapitre et le supprimer.
3. Revenir sur l'onglet A et recharger la page : le chapitre est toujours accessible.

Cause possible : à priori, je pense que la cause est à chercher dans [maj_repo_chapter()](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L2717) ou [modify_chapter()](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L1866), avec préférence pour cette dernière option. En particulier, regarder pour quoi [sur cette ligne là](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L1937), il est écrit `"maj"` et non `"del"` comme `maj_repo_chapter()` le voudrait.

**Comment by artragis** [comment]
je ne pense pas que ça soit à cause de ça. En effet le "maj repo part" permet de mettre à jour la partie après qu'on a supprimé le chapitre qui lui était associé.

A mon humble avis, il y a pas mal de chose à changer pour le coup parce que le "maj repo..." est à changer de base dans la ZEP12. Et quand on commencera à développer cette fonctionnalité, on utilisera les conventions django pour recoder ces fonctions plutôt que des fonctions spaghetti comme on l'a actuellement.

**Comment by pierre-24** [comment]
> je ne pense pas que ça soit à cause de ça. En effet le "maj repo part" permet de mettre à jour la partie après qu'on a supprimé le chapitre qui lui était associé.

Pas faux. Faudrait voir alors ce qui se passe dans le manifest, parce que si le chapitre apparaît quand même, c'est qu'a un endroit, les tests ne se font pas (le fait que les fichiers markdowns correspondant existent toujours est l'objet d'une autre issue ... Qu'il faudrait que je finisse). 

> A mon humble avis, il y a pas mal de chose à changer pour le coup parce que le "maj repo..." est à changer de base dans la ZEP12. Et quand on commencera à développer cette fonctionnalité, on utilisera les conventions django pour recoder ces fonctions plutôt que des fonctions spaghetti comme on l'a actuellement.

On est bien d'accord. Maintenant, la question est de savoir si le bug est "urgent" ou si on peut attendre l'implémentation de la ZEP-12 (miam) pour le régler.

**Comment by firm1** [comment]
Etant donné la nature du bug, je ne pense pas qu'il soit urgentissime. Cependant, si la résolution du bug est triviale (je ne l'ai pas encore regardé de prêt donc je ne peux pas dire) autant le résoudre, au contraire si ça doit prendre plus de 3h (dev+tests+qa), autant passer ces heures sur la ZEP-12.

**Comment by Luthaf** [comment]
Alors concernant le tuto qui m'a fait découvrir ce problème, après téléchargement, édition à la main du manifest.json et suppression des fichiers puis upload, le problème est réparé. 

C'est une manière comme une autre de fixer les tutos cassés.

**Comment by Eskimon** [comment]
Au point ou on en est, je tag en zep-12 ;)

**Comment by artragis** [comment]
^^

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
Need test, mais il me semble que @pierre-24 https://github.com/pierre-24
a déjà intégré ça dans les TU de base.

2015-04-16 14:28 GMT+02:00 Eskimon notifications@github.com:

**Comment by pierre-24** [comment]
Yep, c'est dans les T.U., donc on devrait être bon là dessus ;)

(need QA, as usual)
