### ISSUE TITLE
Galerie : le mode "lecture" ne sert actuelement sert à rien

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1522]
Aujourd'hui, lorsqu'un utilisateur est en mode "lecture" dans une gallerie, il peut juste accéder à la page listant les images contenant celle-ci et pas l'une d'entre elle, car il recoit alors une erreur 403. ces utilsateurs devraient au moins pouvoir accéder à la page de l'image pour obtenir les codes markdown de l'image/miniature/...

**Comment by artragis** [comment]
Je prends, que quelqu'un me l'assigne. Deadline prévue : lundi 6 octobre.

**Comment by Alex-D** [comment]
Le mode lecture fonctionnera désormais (mergé)
