### ISSUE TITLE
Sommaire vide sur les tutoriels en beta/en rédaction

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1528]
Si on va sur un tutoriel, en bêta par exemple : http://zestedesavoir.com/tutoriels/off/412/ruby-on-rails-de-zero-a-la-mise-en-production/

On peut voir que le sommaire **de la sidebar** est vide.

Le bug est récent car j'avais passé pas mal de temps pour que ça fonctionne dans tous les cas. Il y a donc eu une modification des modèles ou des vues qui a cassé ce sommaire.

**Comment by Alex-D** [comment]
Je tiens à insister sur cette issue. Elle est **bloquante** selon moi.

Dans les états _Hors ligne_ et _Bêta_, sur un big tuto, le sommaire n'est pas affiché sur l'accueil du tutoriel et sur les chapitres. Il est par contre disponible lorsque l'on est sur une partie du tutoriel.

Cela veut dire que la navigation au sein d'un tutoriel demande de repasser systématiquement par l'accueil du dit tutoriel pour le rédiger ou le lire en bêta. Je trouve donc cela **bloquant**.

**Comment by SpaceFox** [comment]
Définition de "bloquant" : _"une fonctionnalité **majeure** du site n'est pas disponible **du tout**, ce qui bloque l'utilisation du site"_ (définition communément admise).

Là c'est chiant, je suis d'accord, mais n'empêche en rien l'utilisation du site y compris sur les tutos en bêta.

**Comment by Alex-D** [comment]
En soi, c'est selon moi le coeur du site que je considère donc comme une fonctionnalité majeure qui nuit à l'UX. En admettant que ce ne soit pas bloquant, j'ai donc appliqué le tag adéquat : **Régression** qui pour le coup me semble plus juste.

Selon moi, **ce doit être _impérativement_ corrigé dans la v1.2**

**Comment by SpaceFox** [comment]
> Selon moi, ce doit être impérativement corrigé dans la v1.2

On a déjà essayé d'attendre une correction précise pour lancer une release. On a tous vu ce que ça donne. Je propose qu'on apprenne de nos erreurs et qu'on ne recommence pas.

Ceci n'enlève rien au caractère régressif de ce bug.

**Comment by Eskimon** [comment]
J'ai ptet pas tout suivi, mais c'est pas deja corrige par la PR en cours de firm1 juste au dessus ?

**Comment by Alex-D** [comment]
> On a déjà essayé d'attendre une correction précise pour lancer une release. 

En gros, "ce doit être impérativement corrigé dans la v1.2" => ce doit être corrigé en priorité parmi les fix de la v1.2

Et @firm1 affirme que sa PR corrige déjà le bug, donc ça ne devrait pas nous bloquer dans le temps.

**Comment by Eskimon** [comment]
En reprenant l'exemple de l'OP tout semble OK non ? (en tout cas pour un tuto en redaction tout semble bon)

**Comment by firm1** [comment]
> En reprenant l'exemple de l'OP tout semble OK non ?

Pas vraiment, l'OP parle du sommaire de la sidebar, et non du sommaire au centre

**Comment by Eskimon** [comment]
Ah ok, my bad

**Comment by Eskimon** [comment]
Et je confirme que la PR de @firm1 répare le sommaire latéral

**Comment by gustavi** [comment]
Du nouveau ici ? Le bug est encore présent.

**Comment by Eskimon** [comment]
Oui je suppose vu que la PR de firm1 n'a pas été mergee et est abandonnée pour le moment.

**Comment by Eskimon** [comment]
voilou
