### ISSUE TITLE
Apparement il n'existe pas d'url pour la désinscription

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#1532]
Alors que tout fonctionne sur les branches de développement réservées à la désinscription, aucune url ne semble mener à `membres/desinscrire/attention/` empêchant ainsi toute désinscription.

**Comment by Alex-D** [comment]
Je n'ai pas bien saisi le soucis, côté back c'est ici : 

https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/urls.py#L10

et côté front, c'est là : 

https://github.com/zestedesavoir/zds-site/blob/dev/templates/member/settings/base.html#L31

Donc pour moi, c'est tout bon (si ce n'est que la modification d'indentation que j'avais demandé n'a pas été faite :-° ).

**Comment by artragis** [comment]
Sur la préprod on a néanmoins un 404 :( peut être une mauvaise config
des utilisateurs externe et anonyme mais ça ne devrait pas entrer en
compte pour la page d'avertissement /!\

**Comment by firm1** [comment]
Il y'a surtout un problème dans le code. Les urls [desinscription](https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/urls.py#L10) et [attention](https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/urls.py#L11) sont en conflits.

Quand tu demandes `/membres/desinscrire/attention/` il pense que tu demandes `/membres/desinscrire/` (voila pourquoi j'insiste pour avoir des tests unitaire sur toute la chaine) et vu que utilisateur annonyme et auteur externes n'ont pas été mappées sur la preprod, il ne les trouvent pas.

En résumé, pour corriger cette issue, il faut : 
- modifier les urls qui sont en conflits (back)
- mapper les utilisateurs annonymes et externe (infra)

**Comment by artragis** [comment]
c'est étrange, en version de dev il ne fait pas cette erreur, j'ai bel
et bien accès à attention. J'avoue ne pas comprendre là.

**Comment by firm1** [comment]
ça c'est surrement du à la configuration spécifique sur nginx de la prod. Qui est : "si une url saisie ne se termine pas par `/` rajoute un `/` dans l'url".

C'est la raison pour laquelle la version de dev n'a pas ce problème. Mais quoiqu'il en soit ça reste une mauvaise pratique dans le nommage des urls

**Comment by artragis** [comment]
Testé en préprod : ça marche impec, 2 be close.

**Comment by Eskimon** [comment]
Voila voila !
