### ISSUE TITLE
Système pour ne pas oublier les actions spécifiques lors du déploiement

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1533]
Trouver un système pour noter quelque part toutes les actions spécifiques à faire lors du déploiement **et** afficher au moins un avertissement lors du lancement du script.

Si ce système implique la doc, ces actions doivent être regroupées dans une seule page (il n'est pas question d'aller éplucher la doc avant tout déploiement) et doit permettre de savoir facilement ce qui est à faire et ce qui a été fait lors du déploiement d'une version précédente.

**Comment by firm1** [comment]
Cette issue ressemble a un doublon de celle-ci : #1510 qui est censée regrouper et versionner entre deux tags le delta des modifications à appliquer.

**Comment by SpaceFox** [comment]
Non, ça n'a rien à voir, l'issue #1510 concerne la mise à jour de la doc de déploiement et ne parle absolument pas de ce dont tu parles.

**Comment by SpaceFox** [comment]
Ce ticket est important pour éviter que tout les processus de déploiement doivent être faits par la même personne en permanence. Si la doc est complète, toute personne de confiance ayant un accès aux serveurs devrait pouvoir mettre en (pré-)production, éventuellement avec le _soutien_ de quelqu'un d'expérimenté.

**Comment by Alex-D** [comment]
> SpaceFox removed the Infra label 14 hours ago
> 
> toute personne de confiance ayant un accès aux serveurs devrait pouvoir mettre en (pré-)production

On parle bien d'infra là non ? Ou est-ce qu'on parle d'une MEP de façon générale (donc, par exemple sur un autre serveur pour lancer un autre site, etc) ?

**Comment by SpaceFox** [comment]
À priori on parle bien d'un dev ou d'une procédure à mettre en place quelque part, pas spécifiquement d'une tâche d'infra - ce que désigne ce tag.

**Comment by SpaceFox** [comment]
Corrigé et mergé --> Fermé.
