### ISSUE TITLE
Incohérences dans nos settings

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1540]
``` python
BOT_ACCOUNT = 'Clem'
ANONYMOUS_USER = "anonymous"
EXTERNAL_USER = "Auteur externe"
```

D'une manière générale, j'ai l'impression que faire le ménage dans le `settings.py` ne fera pas de mal.

**Comment by SpaceFox** [comment]
D'autre part j'ai l'impression qu'on a des paramètres dans le settings_prods.py de préprod qu'on a pas en prod...

**Comment by firm1** [comment]
> ``` python
> BOT_ACCOUNT = 'Clem'
> ANONYMOUS_USER = "anonymous"
> EXTERNAL_USER = "Auteur externe"
> ```
> 
> D'une manière générale, j'ai l'impression que faire le ménage dans le `settings.py` ne fera pas de mal.

Moi je ne vois pas d'incohérence là. Ce sont des paramètres fonctionnels (c'est à dire destiné à être mise à jour dans le settings de prod). Donc au final ce qui est marqué dans le settings.py, on s'en fou un peu tant que c'est cohérent avec nos fixtures. Quelqu'un voudra peut-être appeler son utilisateur annonyme tartanpion s'il veut demain.

**Comment by SpaceFox** [comment]
Ben nos comptes techniques s'appellent `_ACCOUNT` et `_USER`. Elle est là l'incohérence. (En plus du franglais dans les paramètres par défaut mais ça c'est du détail).

**Comment by firm1** [comment]
Ah en effet :)

**Comment by firm1** [comment]
Fixé -> mergé.

On ferme donc
