### ISSUE TITLE
Rendre l'utilisateur anonyme injoignable

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1541]
Actuellement, l'utilisateur anonyme prend la place de n'importe quel utilisateur lorsqu'il se desinscrit.
- on peut encore envoyer des MP à ce membre, ce qui ne devrait pas être le cas, vu qu'il n'y a personne au bout du fil.
- La zone "Derniers sujet crées" ne devrait pas exister pour l'utilisateur annonyme
- On ne devrait pas pouvoir ajouter l'utilisateur anonyme comme co-auteur

**Comment by Alex-D** [comment]
C'est assez ennuyeux de créer des issues qui mêlent back et front sans aucun détail sur la répartition.

> on peut encore envoyer des MP à ce membre, ce qui ne devrait pas être le cas, vu qu'il n'y a personne au bout du fil.

Purement back.

> La zone "Derniers sujet crées" ne devrait pas exister pour l'utilisateur anonyme

Ca rejoint une chose que j'avais déjà dite : la page membre "Anonyme" et "Auteur Externe" n'ont aucun sens. Soit on les retire purement et simplement (en retirant tous les liens qui pointeraient vers ces pages), soit on redirige vers une page statique qui explique le pourquoi c'est écrit "Anonyme".

> On ne devrait pas pouvoir ajouter l'utilisateur anonyme comme co-auteur

C'est à peu de chose près similaire au premier point. Tout comme, selon moi, on ne devrait pas pouvoir mettre "Auteur externe" en co-auteur.

---

Au final c'est que du back. Pas vraiment de front sur cette issue, de mon point de vue.

**Comment by SpaceFox** [comment]
> C'est assez ennuyeux de créer des issues qui mêlent back et front sans aucun détail sur la répartition.

Personnellement ça ne me pose aucun problème. C'est même quelque chose qui arrive, genre "tout le temps" dans la vraie vie : l'issue proposée est fonctionnelle, aux développeurs de faire en sorte que les différents aspects du problèmes soient traités proprement. Si les différentes parties de la résolutions sont faites en des temps très différents pour une raison X ou Y, alors là on peut séparer l'issue en plusieurs issues indépendantes.

> Ca rejoint une chose que j'avais déjà dite : la page membre "Anonyme" et "Auteur Externe" n'ont aucun sens. Soit on les retire purement et simplement (en retirant tous les liens qui pointeraient vers ces pages), soit on redirige vers une page statique qui explique le pourquoi c'est écrit "Anonyme".

Ou alors on se sert intelligemment des fonctionnalités à disposition pour éviter du dev inutile, et on utilise les biographies de ces 2 page pour en expliquer les tenants et aboutissants. On arrive au même résultat que les "pages statiques" avec très exactement 0 secondes de dev.

> Tout comme, selon moi, on ne devrait pas pouvoir mettre "Auteur externe" en co-auteur.

Je vois des raisons légitimes de mettre "Auteur externe" en co-auteur. Par exemple la reprise en interne d'un tuto importé d'abord par un auteur exerne.

**Comment by Eskimon** [comment]
> Ou alors on se sert intelligemment des fonctionnalités à disposition pour éviter du dev inutile, et on utilise les biographies de ces 2 page pour en expliquer les tenants et aboutissants. On arrive au même résultat que les "pages statiques" avec très exactement 0 secondes de dev.

+1 (mais genre très gros +1)

**Comment by Alex-D** [comment]
> On arrive au même résultat que les "pages statiques" avec très exactement 0 secondes de dev.

C'est une alternative raisonnable, mais qui nécessite un peu de dev tout de même : masquer les stats dans la sidebar et les différentes informations du genre (articles, tutoriels, sujets, etc).

Et ce qu'on va me dire c'est : "suffit de le faire dans le template" à quoi je répondrais : il suffit de le faire côté back : si anonyme, ça renvoie un tableau vide pour les tutos, articles et sujets.

Du coup, c'est une issue purement back, toujours selon moi.

> Je vois des raisons légitimes de mettre "Auteur externe" en co-auteur. Par exemple la reprise en interne d'un tuto importé d'abord par un auteur exerne.

D'ac, je n'avais pas pensé à cette possibilité.

**Comment by Eskimon** [comment]
Bon, comme on peut le voir dans la discussion sur la PR ci-dessus, on se prend toujours les infos car ca passe par le profile. Il y a deux solutions:
- Le back renvoi une info supplémentaire "is_bot" et le template est modifié pour filtrer les éléments a afficher si oui ou non on affiche un bot (j'ai une PR pour ca de prête en local si vous le souhaiter). Ca marche mais c'est crade car rajoute une grosse louche de logique dans le template.
- Plan B, on retourne pas la meme page si c'est un bot ou un user normal (ma solution préférée, plus propre). Si on retient ca, une personne du front a juste a prendre le filtre de la PR en cours ci dessus et dévié vers le bon template.

A vous de voir...

**Comment by Alex-D** [comment]
> Le back renvoi une info supplémentaire "is_bot"

Je ne suis pas pour cette logique

>  on retourne pas la meme page si c'est un bot ou un user normal

Je ne suis pas pour non plus : quand je l'ai proposé on m'a dit que c'était idiot car ça faisait deux pages à maintenir. Et je comprends que ce soit pénible, donc je préfère la solution qui suit :

Mon alternative énoncée dans la PR est que pour anonyme, les getters tuto/articles ne retournent rien (on en aura besoin nul part : c'est le but même de l'anonymisation).

**Comment by Eskimon** [comment]
Ca c'est fait

**Comment by SpaceFox** [comment]
Cf ce commentaire : https://github.com/zestedesavoir/zds-site/pull/1865#issuecomment-70381328

**Comment by SpaceFox** [comment]
OK, ça a marché.

**Comment by firm1** [comment]
Je ré-ouvre cette issue, car en préprod, sur le profil de l'utilisateur anonyme, ce dernier a encore le bouton "Envoyer une message privé" dans la sidebar : http://preprod.zestedesavoir.com/membres/voir/anonyme/

**Comment by artragis** [comment]
je ne peux pas corriger le problème car la branche de release n'existe 
pas sur le dépôt @Spacefox.

**Comment by SpaceFox** [comment]
WTF ? En effet, c'est corrigé.
