### ISSUE TITLE
Lorsqu'on se désinscrit, on est toujours trouvable

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1542]
Lorsqu'un utilisateur se désinscrit, toutes ses traces ne disparaissent pas forcément.

Il suffit de taper son ancien pseudo dans la recherche pour se rendre compte qu'on arrive à retrouver les messages que ce dernier a posté.

**Comment by Eskimon** [comment]
C'est pas du au fait que Solr ne s'est pas réactualisé entre temps ?

**Comment by artragis** [comment]
ça veut dire qu'il faut qu'un worker passe pour rebuilder l'index solr.

Actuellement, je ne sais pas faire ça et comme c'est intestable en version de dev, je touche pas à ça.
Maintenant soyons pragmatiques : le worker finira par repasser et donc par changer les contenus. Donc là on est OK, non?

**Comment by SpaceFox** [comment]
De mémoire il passe toutes les 30 minutes en préprod et en prod.

**Comment by firm1** [comment]
En effet, une fois la tache cron passée, ça va mieux
