### ISSUE TITLE
Les tutoriels deviennent inaccessibles si on les renomme

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1544]
[Ce tutoriel](http://zestedesavoir.com/tutoriels/339/apprenez-la-sculpture-numerique-avec-pixologic-zbrush/) est devenu innacessible en ligne

**Comment by SpaceFox** [comment]
[Errno 2] No such file or directory:
u'/opt/zdsenv/ZesteDeSavoir/tutoriels-public/339_apprenez-la-sculpture-numerique-avec-pixologic-zbrush/introduction.md.html'

Stacktrace (appel le plus récent en dernier) :

  File "django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "zds/tutorial/views.py", line 762, in view_tutorial_online
    tutorial.load_introduction_and_conclusion(mandata, public=True)
  File "zds/tutorial/models.py", line 240, in load_introduction_and_conclusion
    mandata['get_introduction_online'] = self.get_introduction_online()
  File "zds/tutorial/models.py", line 306, in get_introduction_online
    "r")

**Comment by firm1** [comment]
Nouveau cas d'erreur 500 : http://zestedesavoir.com/tutoriels/475/la-cryptographie-asymetrique-rsa/677/la-theorie/3168/le-dechiffrement/#1-lutilisation-de-la-cle-privee

Et c'est pareil sur tous les chapitres suivants du même tutoriel

**Comment by SpaceFox** [comment]
Hmmm et je ne reçois pas d'alerte Sentry à propos de cette erreur. Alors que sur le premier me renvoie systématiquement l'erreur que j'ai déjà mentionné.

**Comment by Eskimon** [comment]
QQun ayant accès a la prod' pourrait voir ce qui cloche avec ce dossier ? Format incorrect ? nouveau format pour les nouveaux tutos ? Quel est la différence avec les autres dossiers ?

**Comment by firm1** [comment]
En téléchargeant l'archive du tutoriel je ne remarque rien de bien méchant. A mon avis, étant donné que ces derniers jours il y'avait des problème d'accès IO sur le serveur de prod, quelque chose (echec de connexion à la bd, problème de lecture, ...) à fait foirer la validation. Le problème étant que lorsque la validation foire, il n'y a aucune routine pour nettoyer après.

Là ce qu'il faudra faire je pense c'est de modifier le code pour rajouter une routine de nettoyage (suppression de la version publique et synchro des sha) après echec d'une validation.

Pour les tutos présentement, je pense qu'en ajustant tout simplement les sha dans la bd pour faire comme s'il n'était pas publié et en le re validant, ça devrait aller. Attention, je ne suis pas à 100% sur de ma dernière affirmation.

**Comment by Eskimon** [comment]
Une raison vient d'etre identifiee (tout du moins pour le tuto pixologic), le renommage du tuto entraîne l'erreur 500. En effet, je pense (j'ai pas lu le code) que le slug est mis a jour mais pas le nom du dossier, du coup le contrôleur retrouve plus le chemin correctement... (pour blinder ca on pourrait utiliser juste l'id dans le nom des dossiers non ?)

**Comment by cgabard** [comment]
> Une raison vient d'etre identifiee (tout du moins pour le tuto pixologic), le renommage du tuto entraîne l'erreur 500. 

Tu remarque que ton tuto sur les ultrason provoque la meme chose depuis son renommage

**Comment by Eskimon** [comment]
Yep, et j'ai remis le vieux nom et tout est rentre dans l'ordre. C'est ce comportement couple a une remarque de coyote qui a mis la puce a l'oreille sur le renommage+slug.

**Comment by Coy0te** [comment]
Je confirme, repasser à l'ancien nom fonctionne aussi pour http://zestedesavoir.com/tutoriels/339/apprenez-la-sculpture-digitale-avec-pixologic-zbrush/ .

**Comment by Eskimon** [comment]
A t'on le même comportement sur un article ?

**Comment by firm1** [comment]
Est-ce que vous arrivez à reproduire le bug sur la preprod ?

**Comment by Eskimon** [comment]
Yep, sur la preprod je viens de casser le tuto sur la recherche d'informations par exemple.

**Comment by firm1** [comment]
Juste pour remonter un peu cette issue qui est **très** bloquante tout de même.

**Comment by gustavi** [comment]
Fixé !
