### ISSUE TITLE
Ajout d'actions inbox dans nos mails

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1545]
https://developers.google.com/gmail/actions/actions/actions-overview

Parce que c'est quand même vachement pratique (cf celles de Github).

**Comment by Alex-D** [comment]
Tu pense qu'il faudrait en mettre sur/vers quoi ?

Il faut établir au moins une ébauche de liste des choses que l'on veut rendre accessible de cette façon.

**Comment by Situphen** [comment]
Up !

Je plussoie Alex-D :

> Il faut établir au moins une ébauche de liste des choses que l'on veut rendre accessible de cette façon.

Il faut aussi voir si c'est générique à plusieurs messagerie ou réservé à GMail.

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis plus d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.
