### ISSUE TITLE
Bug dans les liens RSS

### ISSUE THREAD

**Issue by germinolegrand** [zestedesavoir/zds-site#1546]
Les flux rss sont buggés, en effet je viens de recevoir une notification pour un nouvel article, et le lien est le suivant : http://zestedesavoir.com/articles/off/94/la-vulnerabilite-shellshock/

Il s'agit du lien offline, et non public.

**Comment by Eskimon** [comment]
Voila, PR en cours !

**Comment by firm1** [comment]
Je ré-ouvre ce ticket car en 1.2 j'ai encore les lien des [flux rss des articles](http://zestedesavoir.com/articles/flux/rss/) qui pointent vers la version offline.

**Comment by firm1** [comment]
Vraiment corrigé cette fois-ci
