### ISSUE TITLE
[Tutoriels] Liste des catégories de tutoriels

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#156]
Design et intégration de la liste des catégories de tutoriels.

Il faudrait discuter de la présentation ici, si on se contente de lister comme dans le menu déroulant ou si l'on fait quelque chose d'un peu plus avancé.

Il faut également décider des informations à afficher et celles à mettre en valeur.

**Comment by firm1** [comment]
C'est fixé -> mergée et en prod.

Je ferme en attendant le design final.

**Comment by Alex-D** [comment]
Je suis "bloqué", en prod il n'y a pas cette page.
Je ne sais pas comment je dois m'y prendre pour récupérer les catégories : est-ce que je fais la même chose que dans le header ?

**Comment by firm1** [comment]
Cette issue devrait s'appeler liste des tutoriels de chaque catégories.

Le header jouant déjà le rôle d'élément de filtre. En gros le même page que
la prod ici : www.zestedesavoir.com/tutoriels
Le 25 mai 2014 04:06, "DEMODE Alexandre" notifications@github.com a écrit
:

**Comment by Alex-D** [comment]
En fait, y en a un autre pour ça : https://github.com/Taluu/ZesteDeSavoir/issues/158

Là on parle de la "home" des tutoriels. Mais j'ai trouvé une solution pendant mon sommeil.

**Comment by Alex-D** [comment]
Fait sur ma branche.
