### ISSUE TITLE
Le mot « licence » est doublé

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#1560]
Salut le monde. :)

Juste pour signaler un petit bug - _rien de bien méchant_ - qui apparaît sur l'historique des versions d'un tutoriel. En fait, devant la licence, le mot « licence » est répété, ce qui donne ceci : 

![capture du 2014-10-02 09 30 17](https://cloud.githubusercontent.com/assets/4312887/4487941/2a523c48-4a06-11e4-9de9-de91847b5847.png)

**Comment by Eskimon** [comment]
En fait le souci c'est que dans l'admin Django les licences sont marquees comme "Licence CC-BY" par exemple plutot que juste "CC-BY" (vu qu'on a aussi "Touts droits reserves"). Il faudrait aligner et decider d'un comportement pour savoir si oui ou non on vire le mot licence dans le nom des licences ou dans le titre du texte mis en cause

**Comment by Alex-D** [comment]
Si c'est ça, ça veut dire que dans le back, il faut sauvegarder "Licence CC-BY..." dans le manifest. Actuellement il y a une différence entre le manifest et ce qui sort de l'admin (en tous cas la dernière fois que j'ai regardé).

Après, c'est simplement un mot à retirer dans les templates, rien de bien compliqué.

**Comment by Alex-D** [comment]
Pour le front, j'ai soumis la PR #1573 qui retire le mot "Licence" en trop. Mais cela va demander de faire des modifications dans l'admin et une mise à jour des manifest pour que le mot "Licence" soit ajouté devant "CC-BY" et compagnie, à moins qu'on laisse juste "CC-BY" tout seul, mais ça n'est pas très clair.

En somme, une fois cette PR mergé c'est du ressort de l'infra.

**Comment by Alex-D** [comment]
Voilà qui est mergé, ça devrait arriver en preprod bientôt. Il faut donc que les admins mettent à jour (ou pas, selon le choix qui est fait) le nom des licences.

**Comment by SpaceFox** [comment]
OK, donc voici l'exemple typique de _"pourquoi il ne faut pas rajouter une PR à une release même si elle a l'air complètement inoffensive"_ et aussi de _"pourquoi il faut systématiquement QA une PR même quand elle a l'air complètement con"_.

Pourquoi ?

Parce que certes, la PR #1573 corrige le rendu dans l'historique des versions... sauf que la réalité est plus compliquée que ça.

La page corrigée est, si je ne m'abuse, la même qui sert pour l'affichage sur l'historique des versions, mais aussi partout ailleurs. Seule change la provenance des données de licence.

Or, la table "Licence" a 3 champs : code, titre et description. Le code est interne et ne doit pas être affiché. Reste le titre ; et la description dont on ne fait rien aujourd'hui.

Problème : **le _seul_ morceau de back-office qui renvoie le bon champ (titre) est justement celui de l'historique**. Tous les autres renvoient le code, ce qui est complètement stupide.

Et en base de données, j'ai systématiquement le titre qui est correctement remplit ("Licence CC-BY") et le code qui est, par pure coïncidence, le nom de la licence seul ("CC-BY").

Résultat : maintenant en v1.1, on a l'affichage "Licence CC-BY" qui est correct dans l'historique du tuto... et l'affichage erroné "CC-BY" partout ailleurs !

Puisque l'information affichée est le code, i.e. l'ID technique, je ne peux pas le changer sans risquer des effets de bord imprévisibles.

Je pense que cette mésaventure vous montre l'intérêt de tester toutes les PR et de refuser de les merger à l'aveugle, même quand elles paraissent inoffensives.

**Comment by SpaceFox** [comment]
PS : Pas la peine de se jeter sur un ticket "bloquant" ou sur un hotfix, ça n'en faut vraiment pas la peine.

**Comment by Alex-D** [comment]
Au back de renvoyer ce qu'il faut, ça n'était certes pas pressé, je ne sais plus pourquoi j'ai fait ça sur la release. Aussi, c'est mieux d'avoir retiré "Licence" rapidement pour ne pas avoir de "Licence Tous droits réservés" qui est bien plus moche que de sombres histoires d'historiques, même si c'est pas top, j'entends bien.

## The solution

En gros, pour régler le soucis, il faut que côté back, quand le JSON est chargé, la licence renvoyée au front soit le title récupérée en BDD grâce à l'ID du JSON (et non l'ID directement). A partir de là, ça rentrera dans l'ordre.

**Comment by Eskimon** [comment]
J'ai pas tout suivi avec l'excitation autour du bordel, mais c'est bon ou pas ?

A fermer ? (et modifier en prod' les licences concernées ?)

**Comment by SpaceFox** [comment]
Heu non pas du tout, je l'ai sortie de la v1.1 justement parce qu'elle est buggée !

Il ne faut surtout pas toucher les licences en prod, qui sont OK, et modifier le back pour afficher le nom des licences et pas leurs codes.

**Comment by Eskimon** [comment]
Ok, merci de la clarification :)

---

Début de recherche:
- Le modèle de la licence montre que l'affichage "littéral" de la licence est correct : https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/models.py#L142

J'ai pas ete capable de trouver ou est-ce qu'on renvoie uniquement le code de la licence. En general on renvoi "toute" l'objet licence au template, donc je vois pas trop ou est le probleme de back...

QQun pourrait résumer ou est vraiment le souci ?

**Comment by Alex-D** [comment]
Le modèle à la base il est beau, mais c'est pas ça qui est renvoyé par la suite.

En gros, la licence est versionnée dans le manifest et c'est ça qui est renvoyé. Donc il faut que le back aille chercher le `title` qui correspond au code de la licence qui se trouve dans le manifest.

Partout dans les templates j'ai fait comme ça :

```
{{ tutorial.licence }}
```

Donc il ne reste plus qu'au back à renvoyer le bon résultat.

~~Je pense que ça se passe dans le `load_dic`, seulement je n'y vois aucune référence à la licence. Du coup ça serait une donnée issue de :~~

```
tutorial = get_object_or_404(Tutorial, pk=tutorial_pk)
```

~~Et si c'était ça, ça voudrait dire que c'est juste que la jointure n'est pas faite et que donc on a le code (l'id) de la licence au lieu d'avoir son title (si c'était bien l'objet qui se trouvait là).~~

~~Et du coup je rajouterais : le lazy laoding, c'est bien quand on le maîtrise. Là on ne sait pas d'où sortent les données, c'est un peu gênant.~~

**Comment by Alex-D** [comment]
Je viens de faire un test sur la preprod, la licence est bien versionnée, donc a priori elle vient du manifest, mais je n'ai aucune idée de où c'est chargé...

**Comment by Alex-D** [comment]
`load_dic` charge en fait les données qui viennent de la BDD (auteurs, etc) donc la licence n'est pas concernée ici.

Donc visiblement, [ça vient de là](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L1284) : 

``` python
    repo = Repo(tutorial.get_path())
    manifest = get_blob(repo.commit(sha).tree, "manifest.json")
    mandata = json_reader.loads(manifest)
    tutorial.load_dic(mandata, sha=sha)
```

C'est le `json_reader.loads` qui charge le manifest et qui charge donc brutalement la licence. Il faut faire une passe supplémentaire pour "transformer" le code de la licence en son objet (en allant faire une requête dans la BDD).

**Comment by Eskimon** [comment]
Bon j'ai testé, effectivement ca marche... Par contre c'est moche car ca oblige a faire une requête SQL de plus pour récupérer le titre, c'est triste...

**Comment by Alex-D** [comment]
Pourquoi c'est moche ? On stock un ID on récupère le titre en BDD, quoi de plus normal ?

**Comment by Eskimon** [comment]
Bah pourquoi pas stocker la licence littéralement directement en fait ?

**Comment by Alex-D** [comment]
Heu ? Ca c'est moche par contre.

Par exemple, une chose qui manque à l'heure actuelle, c'est un lien vers le détail de la licence. Pour faire ça il faudrait rajouter une propriété à l'objet Licence. Si on stoque en texte, il faudra encore patcher le back et ainsi de suite. Si on fait une requête, on récupère l'objet, on a le title et le lien à la fois.

C'est qu'une requête par page, c'est pas dingue à côté des dizaines de requêtes qu'on a sur toutes les pages.

A noter qu'on peut pas profiter d'une jointure en l'état actuel car il me semble que la licence stockée dans le tuto est la dernière licence appliquée et non la licence utilisée en ligne, et de toute façon si la licence diffère entre la beta et la publique, ça va être le boxon, donc c'est selon moi la seule solution viable cette requête supplémentaire.

**Comment by firm1** [comment]
J'aimerai pouvoir passer une code review par ici avant que ce soit mergé.

A lire les échanges, il y'a un truc qui cloche et qui ne devrait pas.
Le 10 oct. 2014 19:30, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by SpaceFox** [comment]
Merger quoi ? Y'a pas de PR en cours.

**Comment by Alex-D** [comment]
> A lire les échanges, il y'a un truc qui cloche et qui ne devrait pas.

Le truc qui cloche me semble pas tant clocher que ça.
- On stock le code dans le JSON
- Donc, on doit récupérer en BDD le libellé qui correspond au code sauvegardé

**Comment by firm1** [comment]
Je n'ai pas tout lu en profondeur, mais vu que ça touche la structure des tutoriels, j'aimerai quand même passer une revue dessus quand la PR partira.

**Comment by Eskimon** [comment]
Voila _une_ solution.

**Comment by firm1** [comment]
Fix'd.
