### ISSUE TITLE
Liens dans le flux Atom sur les articles

### ISSUE THREAD

**Issue by emersion** [zestedesavoir/zds-site#1562]
Les liens des articles dans le flux Atom est incorrect. J'ai par exemple http://zestedesavoir.com/articles/off/84/un-zeste-sans-fin-chapitre-2/ au lieu de http://zestedesavoir.com/articles/84/un-zeste-sans-fin-chapitre-2/

Avec le `off/` comme actuellement, je tombe sur une erreur 403 (_Vous n'avez pas les droits suffisants pour accéder à cette page._). Si je l'enlève j'accède à l'article.

Il y a la même erreur avec le flux RSS.

**Comment by Eskimon** [comment]
48h de retard :D

https://github.com/zestedesavoir/zds-site/issues/1546
