### ISSUE TITLE
Impossible de télécharger l'archive du tutoriel bêta

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#1569]
Bonjour,
Entre la béta et le site actuel, deux comportement existent quant au téléchargement de l'archive pour les tutos en béta test.
# Sur le site

Pour le peu qu'on soit membre et que le tutoriel soit en béta : 
- le bouton "archive" apparait
- en cliquant dessus, on peut télécharger l'archive targz du tutoriel 
# Sur la preprod
- le bouton "archive apparaît"
- en cliquant dessus, **si on n'est pas auteur**, on obtient une 403.

A mon sens le comportement "403" de la preprod est _logique_, mais comme le bouton appraît et est cliquable, c'est le comportement global du site en prod qui est _cohérent_.

**Comment by Alex-D** [comment]
Solution : n'afficher ce bouton que pour les auteurs. C'est bien cela ?

**Comment by artragis** [comment]
Yep. Dans le cas de la béta test.

**Comment by Alex-D** [comment]
C'est pas le cas même quand le tuto est en ligne ? Il me semble que l'archive n'est disponible que pour le staff et pour les auteurs.

**Comment by Alex-D** [comment]
Voilà qui devrait être corrigé dans la PR #1572, un peu longue à tester mais qui devrait faire son job :)

**Comment by SpaceFox** [comment]
Du coup ce bug attendra la prochaine version pour être corrigé. Après tout, le téléchargement d'archives en bêta n'est pas non plus super critique.

**Comment by Alex-D** [comment]
Voilà qui est corrigé et mergé.
