### ISSUE TITLE
Boîtes modales

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#157]
Design et intégrations de boîtes modales réutilisables et modulables au maximum.

**Comment by firm1** [comment]
C'est fixé -> mergée et en prod.

Je ferme en attendant le design final.

**Comment by Alex-D** [comment]
C'est fait dans les commits précédants celui-ci : https://github.com/Taluu/ZesteDeSavoir/commit/5acb4fc2d9067224c67348239eae78f497c38c97
