### ISSUE TITLE
La roue dentée n'affiche pas le menu sur FF

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#1570]
Sur FF, en résolution large (1920/1080), je vois trois boutons en entête :
- les messages privés
- les notifs
- la roue dentée

puis à côté de ça mon avatar.

Sur le site, en prod, le clic sur l'avatar et la roue dentée ont **le même comportement** depuis la RC5.  
Sur la preprod, le clic sur la roue dentée fait "clignoter" le menu utilisateur, un deuxième clic donne à la roue dentée le comportement qu'elle a sur mobile (redirige vers la page d'édition du profil).

Système : 
- Windows 8.1
- Firefox 32 ou IE 11

**Comment by Axylium** [comment]
Je confirme, avec la config suivante : 
- Linux/Ubuntu 14.04 LTS
- Firefox 32

Il faudrait voir avec @Alex-D c'est lui qui avait précédemment réglé ce bug.

**Comment by Alex-D** [comment]
J'ai fait les tests suivants, sur Windows 8.1 : 
- Sur la prod actuelle v1.0b 9dc0e98 : 
  - Firefox 31.0 : **OK**
  - Firefox 32.0.2 : **OK**
  - Firefox 32.0.3 : **OK**
  - Internet Explorer 11.0.9600.17278 : **OK**
  - Chrome toutes versions : **OK** (pas la même logique de focus, donc pas de bug)
- Sur la preprod actuelle v1.1-RC2 497bd3c : 
  - Firefox 32.0.3 : **Pas OK**, s'ouvre et ferme, puis au deuxième clic on est redirigé vers les paramètres
  - Chrome : **Pas OK**, ça fonctionne la première fois, mais la deuxième ça renvoie vers les paramètres
  - Internet Explorer 11.0... : **Pas OK**, exactement pareil que Firefox

---

Le diff du fichier : https://github.com/zestedesavoir/zds-site/compare/9dc0e98d371047ba5c8fbcae2d29b611fcc7a26c...497bd3c7819d882c355d66d86c46524726631b86#diff-38

Le soucis vient du fait que jQuery (et c'est peut-être même dû au JS, j'ai pas étudié la question de façon avancée) ne sait pas mettre d'écouteur d'événement avec une sélection dynamique (rajoute l'écouteur sur les éléments rajoutés dynamiquement en JS après l'ajout de l'écouteur principal). Je fais un patch là dessus rapidement.

**Comment by Alex-D** [comment]
Voilà un bon gros patch, j'ai corrigé au passage les problèmes de navigation au clavier qui étaient présent à ce niveau également (tabulation toussa), ainsi qu'une légère erreur de tabindex que j'ai commise dans le code HTML du site.

Après ça, ça devrait être bon :)

**Comment by Eskimon** [comment]
J'enleve le tag bloquant, le site est toujours utilisable avec ce bug.

**Comment by SpaceFox** [comment]
Corrigé et mergé --> Fermé.
