### ISSUE TITLE
Le karma n'est plus "voted" sur les membres récents

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1577]
[Sujet du forum](http://zestedesavoir.com/forums/sujet/1376/les-pouces-vertrouge/)

Un nouveau membre signale que lorsqu'il vote, après rechargement de la page son vote est bien compté mais il n'a pas de retour visuel (vert/rouge) sur celui qu'il a cliqué.

**Comment by Axylium** [comment]
Peut-être faudrait-il réouvrir ici. J'ai actuellement le même problème que le membre du post, depuis peu.

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé.

**Comment by Situphen** [comment]
Il faut réouvrir car le problème est réapparu pour certains membres ! https://zestedesavoir.com/forums/sujet/1376/les-pouces-vertrouge/?page=2#p50815 Je pense que c'est le _template tag_ `profile` qui bug chez certains membres et pas d'autres !

**Comment by Eskimon** [comment]
@Situphen on peut refermer ici ?

**Comment by Situphen** [comment]
Non, #2560 ne corrige pas le problème !

**Comment by Eskimon** [comment]
Alors là c'est mystique !!

Test sur la beta :
- Avec mon vieux compte Eskimon : Je plussoie -> rafraichit -> tout roule
- Avec un nouveau compte bidon :  Je plussoie -> rafraichit -> le simbole du pouce n'est pas vert !

W.T.F !

**Comment by SpaceFox** [comment]
Je soupçonne un problème d'identifiant dans les tables user et profile.

Ton compte a les mêmes ID dans les 2 tables mais ce n'est pas le cas des
nouveaux comptes… il suffit qu'on enregistre l'un et recherche l'autre pour
que ça foire.

**Comment by Eskimon** [comment]
Oh comme c'est bien vu !!

Tout se joue là donc : https://github.com/zestedesavoir/zds-site/blob/dev/templates/misc/message.part.html#L283

**Comment by Eskimon** [comment]
@SpaceFox tu pourrais trouver de combien d'indices est le décalage des id entre `profile` et `user` . Parce que la c'est inquiétant comme problème je trouve. Et surtout "a part la fusion de profile et user comment resoudre les problemes ici" ?

**Comment by SpaceFox** [comment]
Y'a 1 de décalage : les derniers IDs sont de  2717 / 2718.

Le dernier membre avec les IDs communs est le n°756 "Le Berger".
Le premier avec des IDs différents est le 757 (member_profile) / 758 (user_id) "captain28".

On parle de gens qui se sont enregistrées le 24 juillet 2014.

**Comment by Eskimon** [comment]
Quels sont les impacts si on décide de faire un reset des id a partir de l'id 750 par exemple (histoire de réaligner les deux tables) ?

**Comment by SpaceFox** [comment]
On ne fait pas.

Ce sont des IDs techniques, ça doit fonctionner même si les IDs sont complètement différents d'une table à l'autre.

Et si on est incapables de gérer ça proprement, on fusionne ces deux tables.

**Comment by Eskimon** [comment]
> Ce sont des IDs techniques, ça doit fonctionner même si les IDs sont complètement différents d'une table à l'autre.

De toute évidence pour Django c'est pas le cas... Problème du framework ou on a fait une merde quelque part ?

**Comment by SpaceFox** [comment]
On a forcément fait de la merde quelque part, en se mélangeant les pinceaux entre `member_profile.id` et `auth_user.id` : comme à la base c'était les mêmes (alors qu'absolument rien ne le garantit), on est parti du principe que c'était les mêmes et qu'on pouvait utiliser indifféremment l'un ou l'autre.

**Comment by GerardPaligot** [comment]
On me rappelle comment on peut merge ces 2 tables ?

**Comment by Eskimon** [comment]
> On me rappelle comment on peut merge ces 2 tables ?

Avec plaisir ! https://github.com/zestedesavoir/zds-site/issues/2295

**Comment by Eskimon** [comment]
@firm1 avait corrigé ce truc, je ferme :)
