### ISSUE TITLE
On peut s'écrire un MP à soi-même en changeant la casse

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1581]
Si je m'écris un MP à moi-même mais avec une autre casse (ex : SpaceFox --> spacefox), le système ne détecte pas que c'est moi et donc m'envoie le MP à moi-même.

C'est un effet de bord de la correction de #738 : la vérification de pseudo est maintenant sensible à la casse donc cette ligne https://github.com/zestedesavoir/zds-site/blob/dev/zds/mp/forms.py#L81 ne couvre plus tous les cas.

**Comment by Eskimon** [comment]
rajouter un `toLower()` suffirait ?

**Comment by SpaceFox** [comment]
Je ne sais pas, c'est quoi la technique habituelle pour faire une
comparaison de chaînes de caractères sans tenir compte de la casse en
python ?
C'est ça qu'il suffit d'appliquer.

2014-10-08 8:12 GMT+02:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
StackOverflow répond `lower()` :D

**Comment by SpaceFox** [comment]
GG !

Le premier motivé peut faire la modif.

Rappel : c'est encore à tester sur du MySQL **et** avec la table auth_user en utf8_bin.

**Comment by Eskimon** [comment]
Je suis un peu perdu avec ce message : http://zestedesavoir.com/forums/sujet/1313/prets-pour-la-v11/?page=3#p23995

C'est en `utf8_bin` ou en `utf8_general_ci`qu'il faut mettre la table au final ?

**Comment by Eskimon** [comment]
Finalement j'ai opté pour la méthode "même solution que pour la création de compte". Je trouvais ca plus joli si c'était aligné.

**Comment by SpaceFox** [comment]
La réponse était là : http://zestedesavoir.com/forums/sujet/1313/prets-pour-la-v11/?page=3#p24010

Il faut bien que la table soit en utf8_bin pour que la correction du ticket  #738 fonctionne.

**Comment by SpaceFox** [comment]
Mergé, corrigé, fermé.
