### ISSUE TITLE
Galerie : répétition de l'unité de mesure lors de l'upload d'une image trop lourde.

### ISSUE THREAD

**Issue by jcval** [zestedesavoir/zds-site#1585]
![image](https://cloud.githubusercontent.com/assets/4648693/4588782/ce32beac-5049-11e4-8657-ff60cd29915c.png)

**Comment by Alex-D** [comment]
Dans l'absolu, il faudrait le convertir en Mo, ça sera plus simple je trouve, non ?

**Comment by Alex-D** [comment]
Le soucis vient de là : https://github.com/zestedesavoir/zds-site/blob/dev/zds/gallery/forms.py#L151

Faudrait penser au passage à être uniforme sur les unités : https://github.com/zestedesavoir/zds-site/blob/dev/zds/gallery/forms.py#L123

C'est un peu la foire au boudin :D

**Comment by Alex-D** [comment]
Mergé.
