### ISSUE TITLE
Freeze du navigateur sur l'article Zeste Sans Fin

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#1587]
Si je tente d'accéder à l'article [Zeste Sans Fin - Chapitre 2](http://zestedesavoir.com/articles/84/un-zeste-sans-fin-chapitre-2/) la pagê du navigateur freeze et plus possible de faire quoi que ce soit.

Cela ne semble pas lié à un navigateur (testé sur FF, Chrome, etc.) et le coupable semble être le fichier `zestedesavoir.com/static/all.min.js`.

[Sujet du bug sur ZdS](http://zestedesavoir.com/forums/sujet/1408/zeste-sans-fin-mouline/?page=1#p24297)

**Comment by SpaceFox** [comment]
Ce bug peut mériter un hotfix au besoin.

Demandez-moi si la procédure n'est pas claire (c'est celle standard du
Giflow).

**Comment by Coy0te** [comment]
J'ai dépublié et republié le cours, ça n'a rien changé, le problème persiste. 

Par ailleurs, il n'y a aucun problème sur la version hors-ligne du cours, elle s'affiche sans problème.

**Comment by Eskimon** [comment]
Il faudrait publier, aller voir la page en mode "no javascript", regarder si un nouveau commentaire semble mettre le boxon et agir en conséquence ?

**Comment by Coy0te** [comment]
J'ai répondu sur le sujet ZdS.

**Comment by cgabard** [comment]
Ping @Alex-D ou @sandhose , cela semble être un conflit entre les spoiler et mathjax (cf le sujet). Le html semble correcte, c'est au niveau du JS que ça part en vrille
