### ISSUE TITLE
Mettre en production zds v1.2

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1588]
En attendant, une solution plus propre à l'issue #1533 , on va rouvrir tout de suite un ticket destiné à regrouper l'ensemble des choses necessaires pour la MEP de la v1.2 de zds. C'est donc une tâche Infra ici.

Je vous encourage à signaler ici toute modification importante à faire manuellement pour la MEP 1.2
## Installation d'outils

Pour l"instant, aucun nouvel outil à installer pour la MEP
### le settings_prod.py
- Remplacer `SITE_URL = 'http://zestedesavoir.com'` par `ZDS_APP['site']['url'] = 'http://zestedesavoir.com'`
- Remplacer `ANONYMOUS_USER = "anonyme"` par `ZDS_APP['member']['anonymous_account'] = 'anonyme'`
- Remplacer `EXTERNAL_USER = "Auteur externe"` par `ZDS_APP['member']['external_account'] = 'Auteur externe'`
- Remplacer `BOT_ACCOUNT = 'Clem'` par `ZDS_APP['member']['bot_account'] = 'Clem'`
- Remplacer `BETA_FORUM_ID = x` par `ZDS_APP['forum']['beta_forum_id'] = x`
## Changelog de 1.1 vers 1.2
- Les variables spécifiques au site sont désormais centralisées au même endroit, ce qui rend l'application zds-site plus ouverte aux forks.
- ...

**Comment by SpaceFox** [comment]
En fait au lieu de rédiger dans cette issue, il suffit de créer un fichier nommé par exemple `update.md` qui contiendrait :

``` markdown

Actions à faire pour mettre en prod la version : v1.2
=====================================================

Ticket : #1234
--------------
1. Action 1
2. Action 2
```

Toute personne qui fait un ticket qui ajoute des actions spécifiques de mise à jour rajoute un bloc de ce genre **à la fin du fichier** :

```
Ticket : #1234
--------------
1. Action 1
2. Action 2
```

Quand la branche concernée sera mergée, le bloc viendra naturellement à la fin du fichier et donc sera naturellement bien placé.

Au moment de la release, on rajoute un séparateur pour la version suivante :

```
Actions à faire pour mettre en prod la version : v1.2
=====================================================
```

Il suffit d'ajouter un avertissement dans le script de déploiement "avez-vous bien appliqué les mises à jour spécifiques" ? et le boulot est fait.

**Comment by SpaceFox** [comment]
Quant au changelog, je le génère à partir de la liste des tickets mergés
dans la version déployée (représenté sur Github par les milestones).

**Comment by Eskimon** [comment]
D'ailleurs a ce sujet, dois t-on appliquer la milestone sur les PR ? Pour l'instant je le faisais mais je suis pas sur que ce soit pertinent car au final la PR peut etre retrouve via le ticket et du coup ca fait du "bruit" quand on filtre sur la milestone

**Comment by SpaceFox** [comment]
Non, pas de milestone sur les PR sauf si elles ne corrigent pas entièrement
le ticket.

**Comment by firm1** [comment]
J'y ai pensé le fichier dans le dépot, mais je n'ai aucune idée si c'est une solution efficace. Et j'avoue que je ne sais pas s'il doit aller dans la doc sphinx ou juste un simple markdown.

J'aurai tendance à dire que ça devrai aller dans la doc sphinx, et du coup je ne vais pas pouvoir faire la PR qui va bien (manque d'outils toussa), donc je laisse cette issue en pense bête pour pas oublier des trucs a faire juste par manque d'outils.

**Comment by firm1** [comment]
Pour le changelog je pense qu'il doit figurer dans la doc, ne serait-ce que pour ceux qui réutiliseront notre code, afin de suivre les évolutions de celui-ci.

**Comment by Taluu** [comment]
'Faudrait séparer "version du code" et "version du site". Ainsi, le code publie ses versions (1.1, 1.2, ... etc), et le site, qui l'utilise, vis sa vie en dehors du dépôt du code.

Et donc quand y'a une release du code, faire ce genre de tickets... mais [en release](https://github.com/zestedesavoir/zds-site/releases).

**Comment by SpaceFox** [comment]
J'ai pas compris.

**Comment by Alex-D** [comment]
En gros, il faut séparer la version du code et la version du site.

On peut avoir le site en v1.0 tandis que le code est en 0.9-RC ou que sais-je, simplement en jouant sur les tags (version du code) VS les releases (version du site).

**Comment by Taluu** [comment]
Et utiliser le module de release de Github pour les changelogs d'une version specifique depuis la version précédente. Exemple : https://github.com/Behat/Behat/releases (j'ai pris un repo au pif qui utilisait cette feature)

**Comment by SpaceFox** [comment]
Quel intérêt ? (à séparer les versions site et code)

Le 10 octobre 2014 16:42, Alexandre Demode notifications@github.com a
écrit :

**Comment by SpaceFox** [comment]
J'ai l'impression que notre page de release
https://github.com/zestedesavoir/zds-site/releases est HS depuis qu'on a
dit que "master" s'appelait en fait "prod".

Le 10 octobre 2014 16:46, Baptiste Clavié notifications@github.com a
écrit :

**Comment by firm1** [comment]
Idem, je ne vois pas l'interet d'avoir une version du site vu que la seule composante versionnable du site c'est son code.

Pour le changelogs est-ce que c'est possible de faire ça automatiquement @Taluu ? car sinon c'est après coup, et on a des risque d'oubli.

**Comment by Alex-D** [comment]
Nop, en haut tu as "Show 5 newer tags" et il y a bien les tags, mais sans commentaire de release donc ils sont masqués.

**Comment by Taluu** [comment]
Et tu a aussi la possibilité de voir les commits effectués depuis une version. On peut aussi cibler n'importe quelle branche / tag au fait.

**Comment by SpaceFox** [comment]
Hmmm il faudra que je creuse ça alors. Merci pour le tuyau.

Le 10 octobre 2014 17:02, Baptiste Clavié notifications@github.com a
écrit :

**Comment by SpaceFox** [comment]
Corrigé et mergé --> Fermé.

**Comment by SpaceFox** [comment]
Alors, @firm1, tes instructions concernant le ZDS_APP ne fonctionnent absolument pas.

Les mises à jour de l'objet ZDS_APP se font sur un objet qui vient d'un autre fichier... et donc qui est invisible... et donc qui ne peut pas être mis à jour. Remplacé, OK. Pas mis à jour.

Donc je suis obligé de copier **tout** l'objet ZDS_APP pour que ça marche (parce que si je ne copie que les clés qui ont changé, ça pète).

Et comme il fait appel à SITE_ROOT, je suis obligé de le redéclarer.

Ce qui m'impose d'importer "os". Et de spécifier l'encodage de mon fichier.

Résultat : mon fichier `settings_prod.py` ressemble maintenant à ceci en préprod, ce qui est absolument ingérable.

Outre le fait que comme ce fichier redéclare les `INSTALLED_APPS` pour eh bien pas de raison, je me retrouvais à essayer d'utiliser une app obsolète.

``` python
# coding: utf-8

import os

DEBUG = False

THUMBNAIL_OPTIMIZE_COMMAND = {
    'png': '/usr/bin/optipng {filename}',
    'gif': '/usr/bin/optipng {filename}',
    'jpeg': '/usr/bin/jpegoptim {filename}'
}
SITE_ROOT = os.path.realpath(os.path.dirname(os.path.dirname(__file__)))
ZDS_APP = {
    'site': {
        'name': u"ZesteDeSavoir",
        'litteral_name': u"Zeste de Savoir",
        'slogan': u"Zeste de Savoir, la connaissance pour tous et sans pépins",
        'abbr': u"zds",
        'url': u"http://127.0.0.1:8000",
        'dns': u"zestedesavoir.com",
        'email_contact': u"communication@zestedesavoir.com",
        'email_noreply': u"noreply@zestedesavoir.com",
        'repository': u"https://github.com/zestedesavoir/zds-site",
        'short_description': u"",
        'long_description': u"Zeste de Savoir est un site de partage de connaissances "
                            u"sur lequel vous trouverez des tutoriels de tous niveaux, "
                            u"des articles et des forums d'entraide animés par et pour "
                            u"la communauté.",
        'year': u"2014",
        'association': {
            'name': u"Zeste de Savoir",
            'fee': u"30 €",
            'email': u"association@zestedesavoir.com",
            'email_ca': u"ca-zeste-de-savoir@googlegroups.com"
        },
        'licenses': {
            'logo': {
                'code': u"CC-BY",
                'title': u"Creative Commons License",
                'description': u"Licence Creative Commons Attribution - Pas d’Utilisation Commerciale - Partage dans les Mêmes Conditions 4.0 International.",
                'url_image': u"http://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png",
                'url_license': u"http://creativecommons.org/licenses/by-nc-sa/4.0/",
                'author': u"MaxRoyo"
            },
            'cookies': {
                'code': u"CC-BY",
                'title': u"Licence Creative Commons",
                'description': u"licence Creative Commons Attribution 4.0 International",
                'url_image': u"http://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png",
                'url_license': u"http://creativecommons.org/licenses/by-nc-sa/4.0/"
            },
            'source': {
                'code' : u"GPL v3",
                'url_license': u"http://www.gnu.org/licenses/gpl-3.0.html",
                'provider_name': u"Progdupeupl",
                'provider_url': u"http://progdupeu.pl",
            }
        },
        'hosting': {
            'name': u"OVH",
            'address': u"2 rue Kellermann - 59100 Roubaix - France"
        },
        'cnil': u"1771020",
    },
    'member': {
        'bot_account': u"admin",
        'anonymous_account': u"anonymous",
        'external_account': u"external",
        'members_per_page': 100,
    },
    'gallery': {
        'image_max_size': 1024 * 1024,
    },
    'article': {
        'repo_path': os.path.join(SITE_ROOT, 'articles-data'),
    },
    'tutorial': {
        'repo_path': os.path.join(SITE_ROOT, 'tutoriels-private'),
        'repo_public_path': os.path.join(SITE_ROOT, 'tutoriels-public'),
        'default_license_pk': 7
    },
    'forum': {
        'posts_per_page': 21,
        'topics_per_page': 21,
        'spam_limit_seconds': 60 * 15,
        'spam_limit_participant': 2,
        'followed_topics_per_page': 21,
        'beta_forum_id': 1,
        'max_post_length': 1000000,
        'top_tag_max': 5,
    }
}

ZDS_APP['member']['anonymous_account'] = 'anonyme'
ZDS_APP['member']['external_account'] = 'Auteur externe'
ZDS_APP['member']['bot_account'] = 'Clem'

ZDS_APP['forum']['beta_forum_id'] = 23
TOP_TAG_MAX = 5

ZDS_APP['site']['url'] = 'http://preprod.zestedesavoir.com'

DATABASES = {
    'default': {
    'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dummy',
        'USER': 'dummy',
        'PASSWORD': 'dummy',
        'HOST': 'dummy',
        'PORT': 'dummy',
        'CONN_MAX_AGE': 600,
    }
}

SDZ_TUTO_DIR = '/home/zds/tutos_sdzv3/Sources_md'

ALLOWED_HOSTS = ['*']

PANDOC_LOC = '/home/zds/.cabal/bin/'

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.humanize',

    'easy_thumbnails',
    'easy_thumbnails.optimize',
    'south',
    'crispy_forms',
    'crispy_forms_foundation',
    'email_obfuscator',
    'pipeline',
    'haystack',
    'munin',

    # Apps DB tables are created in THIS order by default
    # --> Order is CRITICAL to properly handle foreign keys
    'zds.utils',
    'zds.pages',
    'zds.gallery',
    'zds.mp',
    'zds.article',
    'zds.forum',
    'zds.tutorial',
    'zds.member',
    # Uncomment the next line to enable the admin:
    'django.contrib.admin',
    # Uncomment the next line to enable admin documentation:
    # 'django.contrib.admindocs',

    'raven.contrib.django.raven_compat',
)

MIDDLEWARE_CLASSES = (
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # Uncomment the next line for simple clickjacking protection:
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'zds.utils.ThreadLocals',
    'zds.middlewares.SetLastVisitMiddleware.SetLastVisitMiddleware',
    'zds.middlewares.profile.ProfileMiddleware',
)

EMAIL_USE_TLS = False
EMAIL_HOST = 'smtp.zestedesavoir.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = 'site@zestedesavoir.com'
EMAIL_HOST_PASSWORD = 'dummy'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/var/tmp/django_cache',
    }
}
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
PANDOC_LOG = '/opt/zdsenv/logs/pandoc.log'
PANDOC_LOG_STATE = True

LOGGING = {
   'version': 1,
   'disable_existing_loggers': True,
   'formatters': {
       'verbose': {
           'format': '[%(levelname)s] -- %(asctime)s -- %(module)s : %(message)s'
       },
       'simple': {
           'format': '[%(levelname)s] %(message)s'
       },
   },
   'handlers': {
       'django_log':{
           'level': 'WARNING',
           'class': 'logging.FileHandler',
           'filename': '/opt/zdsenv/logs/logging.django.log',
           'formatter': 'verbose'
       },
   'generator_log':{
           'level': 'WARNING',
           'class': 'logging.FileHandler',
           'filename': '/opt/zdsenv/logs/generator.log',
           'formatter': 'verbose'
       },
       'mail_admins': {
           'level': 'ERROR',
           'class': 'django.utils.log.AdminEmailHandler',
       }
   },
   'loggers': {
       'django': {
           'handlers': ['django_log'],
           'propagate': True,
           'level': 'WARNING',
       },
       'django.request': {
           'handlers': ['mail_admins', 'django_log'],
           'level': 'ERROR',
           'propagate': False,
       },
       'generator': {
           'handlers': ['generator_log'],
           'level': 'WARNING',
       }
   }
}

RAVEN_CONFIG = {
    'dsn': 'http://<bla bla bla>@sentry.kisai.info/4',
}
```

**Comment by firm1** [comment]
Il y'a pas de raison que ça soit aussi immense. Je suis certain de l'avoir déjà fait chez moi pourtant.

**Comment by SpaceFox** [comment]
Peut-être, mais c'est ce que j'ai constaté en préprod. Tu peux essayer de ton côté si tu trouves mieux.

**Comment by SpaceFox** [comment]
Je viens de penser à un truc : est-ce qu'un import de ZDS_APP ne suffirait pas en fait ?

(Il faut vraiment que je me mette sérieusement au Python moi).

**Comment by SpaceFox** [comment]
> Je viens de penser à un truc : est-ce qu'un import de ZDS_APP ne suffirait pas en fait ?

Ça fonctionne semble-t-il. Du coup tout ce qui est au-dessus n'est plus d'actualité et cette issue est résolue.

**Comment by firm1** [comment]
Je crois que dans la même lancée, tu peux virer tout le contenu des variables `MIDDLEWARE_CLASSES` `THUMBNAIL_ALIASES` et `INSTALLED_APPS` car, elles ne servent plus à rien ici et/ou font doublons avec le settings.py. Et la dernière lance même des trucs que le projet n'utilise pas.

**Comment by SpaceFox** [comment]
OK.

2014-11-03 18:27 GMT+01:00 firm1 notifications@github.com:

**Comment by firm1** [comment]
Je réouvre ici, car le fichier update.md doit être MAJ pour prendre en compte l'ajout de l'import de ZDS_APP dans le settings_prod.py

**Comment by SpaceFox** [comment]
Je ne comprends pas l'intérêt de rouvrir ça après la MEP ?!

**Comment by firm1** [comment]
Pour qu'on pense à mettre à jour ce fichier car il n'est pas bon pour le moment. J'ai hésité entre ouvrir ici et ouvrir une autre issue.

**Comment by SpaceFox** [comment]
Mettre à jour quel fichier ? Je ne comprends rien à ce que tu dis...

**Comment by firm1** [comment]
[ce fichier](https://github.com/zestedesavoir/zds-site/blob/dev/update.md) ne prend pas en compte les remarques faites [ici](https://github.com/zestedesavoir/zds-site/issues/1588#issuecomment-61425538)

**Comment by SpaceFox** [comment]
J'ai envie de dire : OSEF, les environnements le prennent en compte. Et personne d'autre n'utilise ZdS donc n'utiliseront ce bout du fichier.

**Comment by Situphen** [comment]
On ferme ici ?
