### ISSUE TITLE
[Intégration] Contenu rédactionnel

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#159]
Terminer d'intégrer tous les éléments de contenu en CSS puis vérifier/adapter au parseur markdown.

**Comment by firm1** [comment]
Après merge de la PR, je note tout de même qu'il manque des éléments de contenu rédactionnel manquant.
- pygments n'est pas intégré
- les tableaux ne sont pas designé
- les légendes des images ne sont pas bien formées (voir [ici](http://preprod.zestedesavoir.com/forums/sujet/7/rediger-sur-zds))

**Comment by Alex-D** [comment]
pygments ce n'est pas du server-side only ? En l'état le code HTML retourné ne permet aucune coloration à ce que j'ai vu. Ca ne retourne que `<code><pre>` ou un truc comme ça.
- Les tableaux sont à faire en effet
- Les légendes d'image : il manque un peu de style, je corrige ça ce soir.

**Comment by firm1** [comment]
> pygments ce n'est pas du server-side only ?

[non](https://github.com/Taluu/ZesteDeSavoir/blob/master/assets/sass/_pygments.scss)

**Comment by Alex-D** [comment]
Ok d'ac, je le rajouterais aussi ce soir alors :)

Je verrais pour faire un thème cohérent avec le site au passage.

**Comment by cgabard** [comment]
Oui je confirme, il faut juste inclure un CSS comprenant le style des différents élements 

[Ici](http://preprod.zestedesavoir.com/forums/sujet/7/rediger-sur-zds?page=2#p77) il y a un exemple de code qui devrait être coloré (regarde la structure). Ceux dans le tuto ne sont pas forcément évident car shigerum a forcé le mode "texte (ie non coloré car pygment ne sait pas colorer notre syntaxe de markdown)

**Comment by Alex-D** [comment]
Merci pour le message de test !

**Comment by Alex-D** [comment]
TODO actuelle :
- Rajouter un display: block sur les figcaption
- Styliser les tableaux

Si vous voyez d'autres choses à ce niveau là, rajoutez :)

**Comment by Alex-D** [comment]
Me reste que les tableaux. Je les ferais demain, si vous voyez d'autres choses c'est le moment !

**Comment by Alex-D** [comment]
Tout ça est fait.
