### ISSUE TITLE
Rajouter un bouton "Signaler une faute" 

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1594]
En attendant la ZEP-8 et son lot de nouveauté géniale, ne serait-il pas une bonne idée de rajouter un bouton "Signaler une faute" en bas des tutos/article (entre contenu et zone de commentaire). Ainsi, cela éviterais de voir le fil des commentaires "pollués" par des messages signalant des typos.

**Comment by Alex-D** [comment]
Niveau front ça se cantonne (a priori) à un bouton et une modale associé, rien de nouveau donc.

Côté back, à mon avis, il faut faire au plus simple : pourquoi pas tout simplement un MP ?

**Comment by Eskimon** [comment]
J'ai une solution quasi fonctionnelle avec une modale contenant un text area (ou un lien vers MP) et preque tout marche (il faut juste que je tests quelques cas). La PR arrive très vite.

**Comment by Eskimon** [comment]
Merfi @pierre_24

**Comment by Eskimon** [comment]
Je viens juste dire un gros merci a @pierre-24 . Je reçois régulièrement des petites corrections de typo via cet outil et ca fait plaisir d’améliorer la qualité de son contenu !
