### ISSUE TITLE
[DEV] La branche dev ne passe plus les tests

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1596]
Suites à des soucis de tests sur des PR, j'ai relancé les tests sur dev (qui étaient bons à ce moment là). Il se trouve que les tests ne passent plus.

Il faudrait donc corriger le problème sur dev pour que tout le monde puisse continuer à développer tranquillement :)

Le build concerné : https://travis-ci.org/zestedesavoir/zds-site/builds/37703425

**Comment by SpaceFox** [comment]
Heu, on a pas Travis qui est sensé empêcher ça ?!
Le 12 oct. 2014 17:32, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
Pour une raison inconnue, hier ça buildait et c'était tout vert sur un merge que j'ai fait. Et là c'est rouge.

Et l'erreur a l'air d'être un truc d'encodage ou je ne sais quel truc étrange du genre.

**Comment by Eskimon** [comment]
J'ai trouvé, et c'est lolesque :) on s'amuse à faire une comparaison de date avec un date codée en dur... seulement depuis quelques jours, la date testé n'est plus représenté de la même facon car elle a dépassé l'année (entre maintenant et cette date en dure fautive)...

Le test : https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/templatetags/tests/tests_date.py#L99
La date : https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/templatetags/tests/tests_date.py#L16

**Comment by Eskimon** [comment]
PR en cours :)

**Comment by Alex-D** [comment]
Hallelujah !

**Comment by Alex-D** [comment]
Fix by @Eskimon on peut reprendre les PR :)

NB : Il faut rebase les diverses PR qui ne passent pas pour que ce correctif prenne effet.

En étant sur la branche : 

```
git fetch upstream
git rebase -i upstream/dev
```

Vérifiez (grâce au mode interactif) que le rebase fait bien ce qu'il faut, et validez \o/
