### ISSUE TITLE
Faire évoluer la structure des tutoriels et des articles

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#1599]
Le projet étant encore en plein développement actif, la structure des tutoriels et des articles évoluent mais **aucune migration n'est faite sur la structure des anciens tutoriels et articles**. Les développeurs back-end doivent donc développer **en sachant que** la structure précédente était différente et donc gérer tous les cas possibles (ils essayent en tout cas).

Ne pas migrer ces structures ont de gros impacts dans le développement :
- Les nouveaux développeurs ne peuvent pas être tenus au courant et n'ont pas toutes les clés en main pour contribuer efficacement ;
- Les développeurs actifs doivent gérer de plus en plus de cas au fur à mesure que ces structures évoluent (exemple avec un cas qui semblait simple à la base https://github.com/zestedesavoir/zds-site/issues/1560) ;
- Un jour, ça ne sera juste plus maintenable.

Cependant, la solution n'est pas triviale puisqu'il faut pouvoir réécrire l'historique git des fichiers concernés par une migration (le `manifest` par exemple) tout en refaisant une synchronisations avec les commits en base de données.

PS : J'ai mentionné les tutoriels et les articles parce que, à l'heure d'aujourd'hui, ce sont les seuls modules affectés mais il pourrait arriver d'avoir d'autres modules sujet à cette issue à l'avenir.

**Comment by Alex-D** [comment]
> tout en refaisant une synchronisations avec les commits en base de données.

C'est à dire ? Pour les hash public, beta et tout ?

**Comment by Taluu** [comment]
wait wait wait, j'ai vu "réécrire l'historique", j'ai lu, et.... NON !

Si la structure change, il **faut** faire une migration (une commande, mettre à jour les exemples, les fixtures, ... etc), mais NE SURTOUT PAS changer l'historique ! Que faire si quelqu'un a besoin, pour une raison x ou y de checkout une version spécifique ?

Normalement si la structure change, c'est **DEPUIS** que la structure a changée que les éléments doivent être migrés... pas avant ou pendant ! Sinon on risque d'avoir des éléments qui dépassent la version qui est utilisée

Il ne faut en effet ne **pas** faire de gestion des versions précédentes, il faut toujours se concentrer sur la version actuelle hein. Et _ajouter_ une migration dès qu'une structure change. Réécrire l'historique est une chose très périlleuse, surtout sur un dépot publique.

**Comment by Taluu** [comment]
Enfin après je peux avoir mal interpréter le ticket, et c'est ce que j'espère..

**Comment by Taluu** [comment]
OK j'ai donc en effet mal interprété le ticket ; il s'agissait en fait des repos des **tutos**

Ca peut en effet poser probllème, et la facon actuelle de faire les choses est en effet pas viable. Mais, je doute que réécrire l'historique soit tout aussi viable... que faire des types qui ont dl leur tuto ?

L'idée serait peut-etre de versionner par des versions le module de tuto / articles de facon indépendante, et d'indiquer la version utilisée dans le manifest ? C'est tout aussi peu viable ceci dit.... Donc ouais c'est une véritable problématique :/

**Comment by artragis** [comment]
Juste une question : est-ce que cette issue a à voir avec la ZEP 12 ou bien les petites évolutions style ZEP 3 ou import d'archive?

**Comment by Alex-D** [comment]
Ca a à voir avec toute modification qui impliquerait une modification du manifest.json en gros.

Donc a priori ZEP-12, ZEP-08 sont concernées. La ZEP-03 non.

**Comment by artragis** [comment]
Donc la question que je me pose est : 
Durant l'implantation d'une ZEP, doit-on être : 
- rétrocompatible ? i.e dire "si les nouveaux éléments n'existent pas, on utilise un comportement par défaut"
- migrable à la manière python 2 -> python 3 : i.e on crée une moulinette qui migre.

Notons que l'un comme l'autre peuvent demander un gros travail alors autant se décider tout de suite clairement.

**Comment by Alex-D** [comment]
Tu as résumé à ta façon ce que @GerardPaligot disait dans le premier message. C'est tout le problème et c'est ici qu'on en parle, et donc il faut y réfléchir. En sachant que la migration = réécrire l'historique git du repo du tutoriel, cf les messages de @Taluu pour comprendre les problèmes que ça soulève.

**Comment by artragis** [comment]
Justement, je n'ai pas compris pourquoi il faut réécrire l'historique...

**Comment by Alex-D** [comment]
Parce que si on affiche une ancienne version d'un tutoriel qui a un manifest qui ne colle pas aux exigences de la version actuelle, ça va planter. Typiquement si on change la structure du JSON pour quelque chose de différent (genre déplacer l'introduction, ou changer le nom de la clé) et bien il faudra répercuter la modification sur tout l'historique afin de pouvoir visionner n'importe quelle version du dit tutoriel.

**Comment by Luthaf** [comment]
Pourquoi ne pas ajouter un numéro de version dans le `manifest.json` (la version actuelle est la version 1), et avoir du code de chargement de tuto spécifique à la version ? Pour le moment, c'est `load_tuto_v1` qui est utilisé.

Si un jour la structure est modifiée, le numéro de version passe à 2, et on écrit la fonction `load_tuto_v2`. Devant tout ça, un dispatcher se charge d’appeler les bonne fonction selon le numéro de version. Comme ça, pas besoin de réécrire l'historique. 

Il faut toutefois maintenir les anciennes fonctions, et toujours avoir `load_tuto_v1` fonctionnelle quand la version principale est `v18`. Ce n'est sans doutes pas si grave que ça, l’accès aux très anciennes versions des tutos n'étant sans doutes pas une chose courante.

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
Implémenté, testé, et même plusieurs passe de front + web design là dessus.

2015-04-16 14:27 GMT+02:00 Eskimon notifications@github.com:

**Comment by pierre-24** [comment]
Je ne me rappellais même pas que Luthaf avait déjà proposé ce qu'il nous a fallu tant de temps à reproposer ;)
