### ISSUE TITLE
Associate the committer at nick member

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#16]
Les commits actuels sur les tutoriels sont tous attribués par défaut à l'utilisateur Django. Ce qui fait qu'on ne sait pas quel auteur à précisément modifié une partie du tutoriel puisque l'auteur est le même et ce, pour tout les tutoriels.

On peut le voir dans l'image suivante.
![](http://i.imgur.com/s37bJrq.png)

**Comment by Taluu** [comment]
Me semble que normalement tu peux spécifier lel nom d'un auteur via un commit (genre `git commit --author`), non ?

**Comment by firm1** [comment]
> Me semble que normalement tu peux spécifier lel nom d'un auteur via un commit (genre `git commit --author` ), non ?

Oui, le problème étant que j'utilise une lib python pour ça (la doc est légèrement mal écrite), et donc, je ne m'amuse pas à rédiger des commandes git dans le code. 

Actuellement l'objet python que j'utilise pour faire un commit est l'[index](http://pythonhosted.org/GitPython/0.3.2/reference.html#module-git.index.base). Cependant sa méthode commit ne me permet pas de spécifier l'auteur directement. Il faut donc trouver un moyen de rajouter l'auteur à l'index avant le commit.

En gros, faut lire la doc pausément quoi

**Comment by Coy0te** [comment]
Si jamais c'est toujours foutu pareil, voilà ce qui a été répondu au mec qu'a posé la même question y'a 2 ans : 
=> https://groups.google.com/forum/#!topic/git-python/8fVNeLwJM_o

**Comment by firm1** [comment]
Ouais, j'ai bien vu cette solution, mais je la trouve über crade. Je ne m'y pencherai qu'en dernier (mais alors vraiment dernier) recours.
Je le vois déjà gros comme un poisson le coup de : "j'edite mon tuto et la modif porte le nom de quelqu'un qui éditait un autre tuto en même temps". Du coup, on va éviter te toucher les variable d'environnement git. Au pire, je passe par les commandes git.

**Comment by Coy0te** [comment]
Je connais pas la lib ni comment on l'utilise dans notre cas, mais l'objet `Commit` a quant à lui une propriété author, entre autres du genre : 

```
comm = Commit(repo, Commit.NULL_BIN_SHA, tree, 
      author, author_time, author_offset, 
      committer, committer_time, committer_offset,
      message, parents, conf_encoding)
```

Il doit y avoir un moyen de se baser là-dessus de manière propre.

**Comment by firm1** [comment]
> Il doit y avoir un moyen de se baser là-dessus de manière propre.

Yop ça c'est certain. Mais il faut vraiment plonger le nez pour se rendre compte de la perversité de cette lib. Mais après comme je l'ai dis :

> En gros, faut lire la doc pausément quoi

**Comment by firm1** [comment]
Cette issue a été réglée depuis longtemps déjà. je ferme
