### ISSUE TITLE
[Intégration] Formulaires crispy

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#160]
Crispy est le "gestionnaire de formulaires" utilisé sur le projet. Il faudrait voir à adapter certains rendus de champs dans les templates pour avoir un rendu uniforme, sémantiquement correct et accessible.

Typiquement, on y trouve des choses comme 

``` html
<label>
    Le label
    <input ...>
</label>
```

Ce qui n'est pas tout à fait correct.

Il serait préférable d'avoir quelque chose comme

``` html
<label for="idinput">Le label</label>
<input id="idinput" ...>
```

**Comment by geoffreyc** [comment]
Il me semblait qu'a la base, crispy etait juste utilisé en attendant que
les formulaires soit designés. Je vois pas trop l'interet de continuer a
utiliser cette lib?

2014-02-14 10:31 GMT+00:00 DEMODE Alexandre notifications@github.com:

**Comment by firm1** [comment]
> Il faudrait voir à adapter certains rendus de champs dans les templates pour avoir un rendu uniforme, sémantiquement correct et accessible.

Attention, tous les formulaires actuels ne sont pas rendus par crispy. Le cas que tu cite par exemple, ne vient pas de crispy. Si tu veux un exemple de rendu crispy regarde plutot [celui-ci](http://zestedesavoir.com/membres/parametres/profil).

> Il me semblait qu'a la base, crispy etait juste utilisé en attendant que les formulaires soit designés. Je vois pas trop l'interet de continuer a utiliser cette lib?

Juste pour précision, on a la lib `crispy` et la lib `crispy foundation`. Il n'y a aucun intérêt de se séparer de la lib `crispy`. Mais la lib `crispy foundation` devra disparaître. Après, on peut se débarrasser complètement de crispy, mais il faudrait réécrire tout les templates associés (environ 25).

Bref, c'est au bon vouloir de celui qui s'en occupera.

**Comment by Alex-D** [comment]
Sauf erreur de ma part, crispy est une lib de type FormBuilder non ?
Si oui, il faut la garder, sinon il faut en utiliser une pour la simple et bonne raison que ce genre de librairie permet d'uniformiser le rendu des champs dans tout le site via quelques templates, ou alors si il y a une autre façon de faire avec Django je veux bien la connaître.

**Comment by firm1** [comment]
C'est bien une lib de Form. Et j'avais déjà préconisé à l'époque de la conserver, mais à l'époque certains parlaient de se passer de crispy. Je n'ai jamais trop compris pourquoi, donc comme d'hab, ça sera selon les envie de l’intégrateur.

> ce genre de librairie permet d'uniformiser le rendu des champs dans tout le site via quelques templates

Comme je l'ai dit plus haut, crispy actuellement est très couplé à foundation. Donc il faudra regarder ça de plus près.

**Comment by GerardPaligot** [comment]
> Comme je l'ai dit plus haut, crispy actuellement est très couplé à foundation. Donc il faudra regarder ça de plus près.

Le découplage est vraiment très simple. Je me suis documenté un peu plus sur crispy. Je me charge donc de cette issue en adoptant le CSS d'Alex-D à tous les formulaires du système.

**Comment by GerardPaligot** [comment]
Cette issue a été corrigée dans les PRs #179, #181 et #183.

Je ferme.
