### ISSUE TITLE
Garbage collector automatique sur les dépôts Git techniques

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1600]
Aujourd'hui on a aucune forme de maintenance sur nos dépôts Git "techniques".

Résultats : tous les objets sont chacun dans leurs fichiers, ce qui donne un dépôt énorme pour sa taille et un nombre de fichiers hallucinants.

Mon idée est de faire passer régulièrement (toutes les semaines ?) un script de ce genre sur l'ensemble des dépôts git des articles et des tutos (publics comme privés) :

```
#!/bin/bash
for d in *
do
        if [ -d "$d" ]; then
                git gc --aggressive
        fi
done
```

Les connaisseurs de Git (ping @Taluu par exemple), est-ce que ça vous paraît être une bonne idée ? Est-ce qu'il y aurait des problèmes à faire ça ?

En tous cas la sauvegarde apprécierait !

**Comment by Taluu** [comment]
Je n'ai jamais utilisé la commade `gc` à la main, mais je n'y vois pas trop de contre-indication ; par contre, vu qu'en général ce genre de tâche (enfin quand c'est automatique) prend du temps, faudra voir si faudrait pas fragmenter cette commade (y aller par lots) ?

**Comment by SpaceFox** [comment]
"Prends du temps", c'est relatif. Je ne pense pas qu'on en ait pour plus
d'une heure sur le premier lancement et plus d'un quart d'heure à chaque
fois après. Ça peut se lancer la nuit, typiquement avant la sauvegarde.

Pour la petite histoire, gc n'est pas sensée être lancée tant que le dépôt
ne râle pas qu'il en a besoin, sauf que le seuil de déclenchement est ultra
haut. Au boulot, on a réduit un dépôt de 1,4 Go à 550 Mo rien qu'avec ça...
et curieusement, c'est _beaucoup_ plus réactif maintenant :D

Je me doute bien qu'on obtiendra jamais une telle amélioration sur ces
dépôts, qui sont beaucoup moins sollicités. Mais si ça peut maintenir un
état propre et un nombre de fichiers raisonnables sans exploser par
ailleurs, ça me paraît bon à prendre.

Le 16 octobre 2014 10:35, Baptiste Clavié notifications@github.com a
écrit :

**Comment by Taluu** [comment]
Ouais mais sauf qu'on a beaucoup de tutos, c'est juste ca auquel il faut faire attention

**Comment by firm1** [comment]
Il ne faut surtout pas mettre ça en place sans tester LONGUEMENT tout ça (y compris l'historique).

Pour info : https://github.com/gitpython-developers/GitPython/issues/61

**Comment by SpaceFox** [comment]
Si je comprends bien ce que tu décris ici est un problème GitPython qui donc ne concerne pas ce que je propose ?

**Comment by firm1** [comment]
Oui d'où le fait de s'assurer que GitPython arrive a lire correctement un
dépôt après passage de GC.

**Comment by SpaceFox** [comment]
Je profite du fait que je réaligne la préprod avec les tutos actuel pour passer le GC sur la préprod. On verra bien ce que ça donne.

**Comment by cgabard** [comment]
@SpaceFox : un retour du coup ?

sinon : 

> Pour la petite histoire, gc n'est pas sensée être lancée tant que le dépôt ne râle pas qu'il en a besoin, sauf que le seuil de déclenchement est ultra haut.

Est ce que la solution ne serait pas plus simplement de configurer le seuil plus bas pour les tutos ? connaissant git, doit bien y avoir une conf facile a régler pour ça

**Comment by SpaceFox** [comment]
Bah pour l'instant aucun problème.

Comme ce n'a pas été MEP, je la passe sur une version future.

**Comment by SpaceFox** [comment]
Bon en fait ça a été perdu, et globalement on s'en fout. Je ferme.
