### ISSUE TITLE
Bug dans la recherche (pagination & résultats)

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#1601]
Salut. :)

Juste pour prévenir d'un bug, lorsque qu'on fait une recherche avec le terme « _staff_ ». On obtient des résultats qu'à partir de la page **6** et ces derniers sont à chaque fois qu'au nombre de deux, toutes les deux pages.. ! 

Quelques captures pour illustrer mon propos : 

![capture du 2014-10-16 20 59 06](https://cloud.githubusercontent.com/assets/4312887/4668619/a07b9548-5566-11e4-9417-8951e99f2df8.png)
![capture du 2014-10-16 20 59 44](https://cloud.githubusercontent.com/assets/4312887/4668622/a4c3f3f2-5566-11e4-8506-521370888a90.png)

Ma configuration est la suivante : 
- Linux/Ubuntu 14.04 LTS
- Firefox en version 32.0.3

**Comment by Eskimon** [comment]
Du a cette PR : https://github.com/zestedesavoir/zds-site/pull/1384

**Comment by SpaceFox** [comment]
Du coup c'est pas un bug. C'est un fonctionnement moche qu'il faudra corriger un jour, mais ça c'est le boulot du ticket #983.
