### ISSUE TITLE
Les liens auto sont rendus en double

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#1604]
En utilisant une URL auto, le code généré, est celui là : 

``` html
<a href="http://zestedesavoir.com"></a>

<a href="http://zestedesavoir.com">

    http://zestedesavoir.com

</a>
```

On voit bien que tout est en double.

**Comment by Axylium** [comment]
Ça ne devrait pas se trouver dans le dépôt MD de ZDS ?

Car c'est dû à une mauvaise génération du MD, non ?

**Comment by Alex-D** [comment]
+1 Go sur zMD, et je crois qu'un truc similaire a déjà été signalé.
