### ISSUE TITLE
La publication d'un tuto a cassé l'historique Git

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1605]
Cf http://zestedesavoir.com/membres/voir/Dominus%20Carnufex/

Ce qui s'est passé : une action (à priori la publication, vues les dates et heures), a forcé la branche "master" à revenir sur un vieux commit (celui publié). Cette action est notée "reset: moving to 21ef0f32a7f6e2a2fe4a714e81119feb5c5c2373" dans l'historique.

Résultat : tous les commits faits après le commit publié deviennent invisibles... ce qui a donné l'impression aux auteurs de perdre 3 semaines de travail.

Ce qui a été fait pour récupérer le truc :
1. Forcer le dernier commit en tant que "master" directement dans le fichier du dépôt Git.
2. MAJ la working copy
3. MAJ le SHA du commit "draft" dans la base

Autant dire que c'est casse-pieds en plus de nécessiter les droits superadmin...

Il faut trouver pourquoi le master a été reset et corriger ça.

**Comment by SpaceFox** [comment]
Bon visiblement on a plus eu aucun problème de ce genre... je garde le ticket ouvert au cas où.

**Comment by Eskimon** [comment]
3 mois après a-t-on toujours besoin du ticket ou tout semble ok ?

**Comment by firm1** [comment]
On ne l'a plus revu depuis, je pense qu'on peut le fermer et l'ouvrir au
pire si besoin.

2015-04-16 14:33 GMT+02:00 Eskimon notifications@github.com:
