### ISSUE TITLE
Décalage des pouces sur mobile

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1606]
Le bug en question : http://i.imgur.com/9Ye8fSq.png.

Il n'apparait que sur les pouces où l'on n'a pas voté.

Testé sur Firefox mobile dernière version/Android 4.x (CyanogenMod)/Nexus 4.

**Comment by Alex-D** [comment]
J'avais déjà vu le bug, mais j'ai jamais trop compris le pourquoi du comment, faudrait que je m'y re-penche.

C'est pas vraiment un bug, un glitch visuel si on veut, mais pas un bug.

**Comment by SpaceFox** [comment]
Un élément qui ne fonctionne pas comme prévu, c'est un bug. Même ultra-mineur, ça reste un bug.

**Comment by Alex-D** [comment]
On a décidément jamais la même définition du bug. Mais soit, disons que c'est un bug.

**Comment by SpaceFox** [comment]
Je veux bien ta définition du bug si ce n'est pas "un comportement imprévu".

**Comment by GerardPaligot** [comment]
A partir du moment où il y a un comportement non désiré pour une fonctionnalité donnée (même visuel), c'est un bug. Il est peut-être inutile de continuer ce débat assez ridicule. :)

**Comment by Alex-D** [comment]
Corrigé. Validé. Mergé.
