### ISSUE TITLE
La mise à jour d'une tutoriel en beta remet le message par défaut dans le forum

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1607]
Reporté via le forum par [Aabu](https://zestedesavoir.com/forums/sujet/1456/mettre-a-jour-la-beta-remet-les-messages-par-defaut/) : 

> Salut,
> 
> Tous les messages automatiques voient leurs contenus changés par le contenu par défaut lorsqu'on met à jour la béta avec une nouvelle version.
> 
> Exemple ici : http://zestedesavoir.com/forums/sujet/1443/introduction-aux-regimes-sinusoidaux-en-electronique/?page=1#p25059
> 
> On voit bien ça sur les dates de modification.
> 
> Le système ne devrait toucher qu'au dernier message, vu que le premier message est personnalisable et ne devrait pas être automatiquement modifié ensuite… Ou alors pour rechercher des liens de béta et les changer automatiquement. Mais dans ce cas autant garder en accessible tous les liens "béta", ou utiliser un lien automatique vers la dernière version en béta.
> 
> Je suis un peu contrarié parce que j'ai pas de sauvegarde de mon premier message. Tant pis ! Pour le moment je vais évidemment par remodifier.
> 
> A+

**Comment by Eskimon** [comment]
Ok, merci @firm1 et @pierre-24 :)
