### ISSUE TITLE
Notification fantôme lors d'une dépublication

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1608]
Via les forums pas [Coyote](https://zestedesavoir.com/forums/sujet/1454/notification-fantome/) : 

> ### Comment reproduire
> 
> J'ai participé à une discussion dans les commentaires d'un tutoriel, et j'étais donc régulièrement notifié des nouveaux messages. Le hic, c'est que le cours en question a été dépublié (passé hors-ligne) avant que je ne puisse lire les nouveaux commentaires postés.
> 
> Du coup, je me retrouve avec une notification fantôme qui ne disparaît pas, parce que le lien vers le quel elle pointe est une 404.
> ### Pistes de correction
> 
> Un moyen brut de régler le souci serait d'aller supprimer purement et simplement les entrées de la table des notifs correspondant au tutoriel dès lors qu'il est dépublié. Ou moins abruptement, de les passer en statut "lu" pour qu'elles n'apparaissent plus dans la barre des notifs.

Je propose de passer le message en « lu » puis de laisser un message indiquant que le cours en question n'est plus disponible. Peut-être élargir à d'autres contenus qui pourraient poser le même problème.

**Comment by Eskimon** [comment]
Ca roule, merci @firm1 !
