### ISSUE TITLE
Export de galeries

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#1617]
Je pense que de la même façon qu'il est possible d'exporter un tuto ou d'importer une gallerie il serait utile de permettre l'export de galleries. En fait quand on exporte les sources d'un tutos, on a pas les images. 

Je ne vous cache pas que c'est entre autre pour un besoin personnel (mais lié au dev du site) que je le propose : l'export avec support complet de notre markdown vers les pdf avance et va arriver dans une situation testable d'ici quelques semaines je pense. Et les tests vont devoir être fais de manière importantes car ce n'est pas une fonction anodine, d'autant plus qu'a terme le but est que le même parseur prenne en charge le rendu html qui est lui encore plus critique.

Pouvoir télécharger toutes les images d'un coup d'une gallerie me permetrait ainsi de les demander facilement aux auteurs et ainsi faire des tests sur des tutos en entier. 

J'imagine que cela serait utile pour tout le monde, on peut par exemple aussi penser aux editeurs off-line qui auront besoin de l'export pour récupérer les images en local.

Enfin cette fonction est assez trivial à implémenter. Si il est possible de récupérer la liste de tous les fichiers d'une gallerie, faire un zip avec ne dois pas faire plus que 3 lignes.

**Comment by SpaceFox** [comment]
Je suis un peu perdu sur ce ticket.

**Comment by GerardPaligot** [comment]
J'avais été super réactif (https://github.com/zestedesavoir/zds-site/issues/1619) mais une histoire de cache est venue tout bousiller.

**Comment by SpaceFox** [comment]
… et évidemment on a jamais été foutus de statuer dessus…

**Comment by GerardPaligot** [comment]
Je serais disposé à reprendre mon travail ici mais j'aimerais statuer sur les corrections à apporter dans ma précédente tentative de PR. Comment nous procédons ?

**Comment by SpaceFox** [comment]
On peut récapituler quel était le problème et quelles sont les solutions ?

**Comment by GerardPaligot** [comment]
Le dernier comportement de ma PR était le suivant :

> Bien, j'ai un peu bossé sur la PR. Voici comment j'ai fais évolué la fonctionnalité :
> - Si le dossier du cache n'existe pas, alors on le crée.
> - Si l'archive de la galerie voulue existe déjà et que la date de la dernière image est plus grand que la date de création de l'archive, alors on supprime l'archive et on positionne un flag à `True`.
> - Si le flag est à `True`, alors on génère une nouvelle archive pour la galerie.
> - Si la taille maximum pour le cache est atteint, on supprime la plus vieille archive dans le cache.
> 
> Voilà, normalement les tests vont passés maintenant (merci @cgabard) et les règles pep8 devraient être respectées.

Si c'est ok, je corrige le petit bug rapporté par @artragis. Sinon, on me dit comment faire évoluer ce comportement pour avoir quelque chose de parfait.
