### ISSUE TITLE
Les tags masquent le titre des sujets sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1620]
![screenshot_2014-10-24-13-10-53](https://cloud.githubusercontent.com/assets/6066015/4768730/1b8b053a-5b6f-11e4-89a1-3b7a62d5debe.png)

 Tout est dans le titre (et sur l'image). Quand on au moins 3 tags on ne voit plus le titre.

Smartphone Android/Chrome.

**Comment by Alex-D** [comment]
C'est un bug qui est résolu par une PR en cours.

**Comment by SpaceFox** [comment]
Corrigé, mergé, fermé.
