### ISSUE TITLE
Internationalisation du site

### ISSUE THREAD

**Issue by thauti** [zestedesavoir/zds-site#1621]
Suite à cette discution : http://zestedesavoir.com/forums/sujet/1505/traduire-le-site/

Est-il envisageable (et pertinent) de mettre en place les outils d'internationalisation de Django, afin de faciliter la traduction du site.
Sachant que cela implique de revoir tout le code afin d'enlever le texte brut.

La question de faire des commits/PR/issues en anglais et faire traduire la documentation du dépôt, est aussi envisageable.

**Comment by cgabard** [comment]
> Est-il envisageable (et pertinent) de mettre en place les outils d'internationalisation de Django, afin de faciliter la traduction du site.

C'est envisageable et pertinent.

>  Sachant que cela implique de revoir tout le code afin d'enlever le texte brut.

On le savait, on avait fait le choix de ne pas le faire tant que personne en avait besoin. C'est le cas maintenant !

> La question de faire des commits/PR/issues en anglais et faire traduire la documentation du dépôt, est aussi envisageable.

A priori on partirait pour autoriser ticket et PR en anglais, sans les imposer pour autant. Je pense qu'une transition en douceur ne fera pas de mal.

**Comment by GerardPaligot** [comment]
Dans un souci d'"opensourcification", ça me semble nécessaire. Et je regrette la décision qui avait été prise à l'époque de tout faire en français mais c'est du passé.

**Comment by SpaceFox** [comment]
Ben c'était pas vraiment prévu que quelqu'un d'autre se serve réellement du code du site, et encore moins aussi vite !

Plus sérieusement, de mon point de vue (qui se discute donc) :
1. Code en anglais
2. Commentaires en anglais
3. Messages de commits en anglais
4. PR et issues en français ou en anglais

Pourquoi toujours du français sur les PR et les issues ? Par pragmatisme. Aujourd'hui, toute l'équipe de dev et tous les utilisateurs sont francophones. Malgré cela, on a parfois du mal à se comprendre et à se mettre d'accord.

Donc, évitons d'introduire des incompréhensions supplémentaires en imposant l'anglais comme langue de travail. C'est particulièrement important pour les éléments non triviaux, qui nécessitent une vraie réflexion et argumentation.

Les issues et PR en anglais sont par contre acceptées en particulier si des anglophones veulent contribuer.

**Comment by GerardPaligot** [comment]
Je ne pense pas que tout doit être en anglais. Comme tu le dis, nous avons parfois du mal à se comprendre en français alors en anglais, ça risque d'être encore pire. Je pense que le code, les commentaires, les commits **et la documentation** doivent être en anglais.

Pour les issues et les PRs, le premier message peut être en anglais (c'est même mieux pour que les anglophones puissent au moins comprendre de quoi nous discutons) mais après, nous pouvons basculer en français.

Et si c'est un contributeur anglophone, alors rester en anglais bien évidemment.

**Comment by SpaceFox** [comment]
Ah oui, la doc bien entendu doit être en anglais.

**Comment by firm1** [comment]
> Ah oui, la doc bien entendu doit être en anglais.

Je ne serais pas si catégorique. Car ça signifie non seulement de traduire toute [la doc actuelle](http://zds-site.readthedocs.org/fr/latest/), mais aussi que la nouvelle doc soit produite automatiquement et uniquement en anglais.

ZdS est developpé aujourd'hui par des francophones, je serais plutot pour dire que l'obligation de rédiger la doc liée aux nouvelles features doit être faite en français, et en ouvrant la traduction de celle-ci vers l'anglais.

Ne nous leurrons pas, si on force le developpeur à rédiger la doc en anglais, alors que ce n'est pas sa langue de base, on rajoute une (encore) barrière à l'entrée aux developpeurs actuels pour le bien de developpeurs actuellements inexistants.

**Comment by thauti** [comment]
Ou, mais bon c'est pas une urgence absolue, il peut très bien y avoir du temps entre la publication de la version Française et la version Anglaise.
Surtout qu'au final il n'y a pas grand chose à traduire (même si c'est vraiment ennuyeux à faire ça) si chacun en fait une petite partie pendant 1 mois, ça passe.

**Comment by GerardPaligot** [comment]
@firm1 : Je peux comprendre l'argument pour les issues et les PRs, pas pour la documentation.

**Comment by SpaceFox** [comment]
Bon ben apparemment c'est fait !
