### ISSUE TITLE
Améliorer l'accessibilité des listes de topics

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1626]
Tout est ici : http://zestedesavoir.com/forums/sujet/1516/accessibilite-de-zds-aux-lecteurs-decran-et-au-clavier/?page=1#p26154

> Ma première requête va être la suivante: améliorer la simplicité d'utilisation des pages « liste de topics » pour le clavier. Je dis première requête parce qu'il risque d'y en avoir bientôt d'autres.
> 
> Les pages « liste de topics » est à mon sens celles les moins pratiques de tout le site aujourd'hui quand on navigue au lecteur d'écran. Voilà pourquoi je commence par celle-là. La liste des topics n'a aucune sémantique utile pour les lecteurs d'écran permettant une lecture plus simple actuellement. Si on veut choisir un sujet à aller voir, on n'a qu'une seule possibilité: appuyer des centaines de fois sur tab jusqu'à tomber sur quelque chose qui a l'air interressant; au passage, on se tape des liens moins utile comme le profil de l'auteur, celui de la dernière réponse, des mots-clés pas toujours en nombre égal ce qui complexifie encore un peu.
> 
> Plusieurs possibilités pour faire mieux :
> 
> Possibilité1: Revenir à des tableaux classiques ! Ca peut vous paraître bizarre, car on vous a probablement toujours dit que les tableaux étaient à réserver à des données tabulaires. Eh bien, en fait, une liste où on retrouve pour chaque ligne les mêmes informations (titre, auteur, nombre  de réponses, mots-clés, dernière réponse), c'est pourtant bien des données tabulaires, où chaque titre de sujet est une cellule d'en-tête. D'ailleurs, visuellement, je suis presque sûr que l'information est présentée dans des colonnes bien organisées. Alors pourquoi un ramassis de span informe ??? Pour un lecteur d'écran c'est plus simple un tableau dans ce cas, car on a des moyens de naviguer par ligne ou par colonne au lieu de se taper toutes les cellules dans l'ordre à la suite. Par conséquent, pas besoin de lire l'auteur, le nombre de réponses, les mots-clés et le dernier posteur des sujets dont le titre ne m'intéresse de toute façon pas; par ailleurs, il n'est pas mauvais de rappeler que le titre est la porte d'entrée d'un sujet, c'est ce qui va me permettre de décider si je clique ou pas pour le lire.
> 
> Possibilité 2: différencier les titres de sujets en les mettant en `<h1-6>`. Sachant que le titre de sujet est l'information la plus importante et que le reste (auteur, mots-clés, etc.) le sont beaucoup moins, c'est un choix qui paraît affreusement logique, plutôt que l'actuel ramassis de span informes. Avec un lecteur d'écran, c'est plus facile car on a une fonctionnalité pour naviguer rapidement de titre en titre, et ce sur toutes les plateformes, aussi bien PC que mobile. Si les titres étaient en `<h1-6>`, alors de nouveau, plus besoin de se taper les métadonnées d'un sujet qui ne m'intéresse pas. Si ça ne m'intéresse pas, zoup, je passe au titre suivant, et donc au titre de sujet suivant.
> 
> [...]
> 
> Note: j'ai fait exactement la même suggestion sur PDP il y a quelque temps, et ils l'ont fait; ils ont choisi la possibilité n°2.

**Comment by GerardPaligot** [comment]
Son sujet semble avoir comme objectif de recenser toutes les améliorations liées à l'accessibilité, pas uniquement sur les listes des topics. Il faudrait peut-être copier coller de son message tout ce qui est lié à ces listes.

**Comment by Alex-D** [comment]
Personnellement, je préfère qu'on en parle sur le site avant de créer des issues telles que celle-ci. Ca permettra d'éviter d'avoir soit des issues qui englobent trop de choses, soit des issues trop petites.

Il faut analyser la chose avant de s'emballer en somme.

**Comment by SpaceFox** [comment]
@GerardPaligot tu as raison, je rajoute la partie du message qui concerne ce ticket dans le 1er message. Comme ça, si le sujet couvre autre chose et/ou dévie, on aura un ticket propre.

@Alex-D il y a clairement un problème d'accessibilité, décrit avec précision par l'une des rares personnes à même de nous faire un retour sur l'utilisation _exacte_ et non _supposée_ d'un lecteur d'écran. Le ticket a donc tout à fait lieu d'être.

Tu noteras qu'il ne présume pas de la manière de résoudre le problème pour l'instant, seulement du fait qu'il y a un problème et qu'il faut le corriger.

**Comment by Alex-D** [comment]
Des h4 ont été rajouté, testé, mergé. Ca arrivera donc dans la 1.3.

Pour d'autres soucis d'accessibilité, il faudra créer un ticket par problème. Ici le soucis des listes de sujets a été considéré.
