### ISSUE TITLE
Message d'avertissement pas en UTF8 = 500

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1631]
Ce message d'erreur n'est pas en utf8 et donc entraîne un message d'erreur:

https://github.com/zestedesavoir/zds-site/blob/dev/zds/gallery/views.py#L112

(question subsidiaire, comment a t'il passe la QA ?)

Pour resoudre si vous avez 5 minutes : Rajouter un "u" devant la declaration de la chaine pour la passer en unicode.
Bonus : rajouter un TU...

**Comment by Situphen** [comment]
Je m'occupe de ça en même temps que l'issue #1633. Par contre pour les TU, je n'en ai jamais fait mais je veux bien essayer.

**Comment by Eskimon** [comment]
Pour les tests, regarde ce qui se fait dans `zds/members/tests/` :) et n’hésite pas a demander :)

**Comment by gustavi** [comment]
Plus d'infos sur le bug (j'avais ouvert une autre issue sans faire exprès).

Reproduire le bug : 
- Créer un tutoriel avec un caractère accentué (« é » par exemple)
- Essayer de supprimer la galerie associé

Les logs en détail : 

```
zds.gallery.views in modify_gallery
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-7: ordinal not in range(128)

Stacktrace (most recent call last):
  File "django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "zds/member/decorator.py", line 19, in _can_write_and_read_now
    return func(request, *args, **kwargs)
  File "django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "zds/gallery/views.py", line 112, in modify_gallery
    gallery.title))
```

**Comment by gustavi** [comment]
Est-ce qu'il est possible de rendre les titres des issues qui concernent des 500 un peu plus explicites ?

**Comment by SpaceFox** [comment]
Mergé.
