### ISSUE TITLE
Rendre les messages d'erreur et d'avertissement plus cohérents entre eux

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#1633]
Il faut corriger les fautes si il y en a et mettre un verbe et un point à tous les messages (ou ne pas en mettre à tous les messages).

Dans certains messages on tutoie et dans d'autres on vouvoie, il faut donc choisir soit l'un, soit l'autre.

_Si quelqu'un qui a les droits peut m'assigner à cette issue, ce serait cool ! :)_

**Comment by Eskimon** [comment]
> Dans certains messages on tutoie et dans d'autres on vouvoie, il faut donc choisir soit l'un, soit l'autre.

Non ca c'est voulu. Dans certains il y a une relation d’autorité ou le tutoiement ne passerait pas (cas d'un ban par exemple)

**Comment by Situphen** [comment]
Ok, bah du coup, je vais faire attention à ça !

**Comment by Eskimon** [comment]
Comme d'hab, si tu as une question n’hésite pas :) (ca sera dommage de corriger pour rien des tournures qui n'en avait pas spécialement besoin)

**Comment by SpaceFox** [comment]
Mergé.
