### ISSUE TITLE
Les images .svg font planter la publication d'un tuto

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1634]
En essyant de publier un tuto je suis tombé sur une 500 car le tuto contient des images avec une extension svg.

**Comment by Eskimon** [comment]
Et la solution serait quoi ? Trouver un moyen de tolérer les svg ou les interdire ?

**Comment by firm1** [comment]
Si possible les tolérer, sinon, appliquer le même traitement que celui
actuellement appliqué sur les liens d'images introuvables, c'est a dire
remplacer par un carré noir dans les exports (car c'est au niveau de
l'export que ça plante)

**Comment by gustavi** [comment]
Les logs :

```
Stacktrace (most recent call last):
  File "django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "zds/member/decorator.py", line 19, in _can_write_and_read_now
    return func(request, *args, **kwargs)
  File "django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "zds/tutorial/views.py", line 356, in valid_tutorial
    (output, err) = mep(tutorial, tutorial.sha_validation)
  File "zds/tutorial/views.py", line 3104, in mep
    get_url_images(md_file_contenu, tutorial.get_prod_path())
  File "zds/tutorial/views.py", line 2998, in get_url_images
    im.save(os.path.join(pt, "images", filename))
  File "PIL/Image.py", line 1670, in save
    raise KeyError(ext)  # unknown extension
```

Il faudrait retourner autre chose qu'une 500, même si c'est pas un fichier image. C'est au niveau de Django qu'on doit vérifier ça, avant de l'envoyer a PIL.

Je sais pas comment c'est géré aujourd'hui (mimetype ?) mais faut éviter de retourner des 500.

**Comment by firm1** [comment]
Corrigé.

**Comment by Eskimon** [comment]
Vu que plus rien n'est dans la v1.7 puisque revert, il faudrait pas virer ca en "futur proche" et se donner le temps de bien faire les choses ?

**Comment by GerardPaligot** [comment]
Si, tout à fait.

**Comment by firm1** [comment]
> il faudrait pas virer ca en "futur proche" et se donner le temps de bien faire les choses ?

A priori la PR de correction bloque uniquement sur un problème d'installation du package cairo sur OS X. Une fois la bonne façon de faire trouvée, le problème sera réglé.

**Comment by Eskimon** [comment]
Mais sera t-il regle pour ne pas bloquer la release ? A priori comme la feature n'existe plus en 1.7 elle ne devrait donc plus etre en hotfix non ?

**Comment by SpaceFox** [comment]
Elle n'est _pas_ en hotfix. Et non, ce n'est pas bloquant pour la release.

**Comment by Eskimon** [comment]
C'est passé !!! Bravo à tous !!
