### ISSUE TITLE
UnboundLocalError: local variable 'gallery' referenced before assignment

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1636]
Erreur 500 via Sentry (titre à changer quand on a plus d'info sur le problème exact) dans zds.gallery.views in modify_gallery.

Les logs : 

```
Stacktrace (most recent call last):

  File "django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "zds/member/decorator.py", line 19, in _can_write_and_read_now
    return func(request, *args, **kwargs)
  File "django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "zds/gallery/views.py", line 178, in modify_gallery
    return redirect(gallery.get_absolute_url())
```

Event at Oct. 27, 2014, 9:44 a.m.

Ping @Eskimon c'est toi qui a fait l'erreur ( http://zdsappserver/galerie/modifier/).

En revanche il semblerait que  ça vienne de http://preprod.zestedesavoir.com alors que ça arrive sur le Sentry de la prod. Ping @SpaceFox tu peux lancer un test sur la preprod pour vérifier que ça fonctionne bien ?

**Comment by Eskimon** [comment]
> Ping @Eskimon c'est toi qui a fait l'erreur ( http://zdsappserver/galerie/modifier/).

Je sais je l'ai fait exprès pour tester la reproduction et si le problème est bien ou je pensais ;)

Doublon : https://github.com/zestedesavoir/zds-site/issues/1631 ;)

**Comment by gustavi** [comment]
Non je pense pas que ce soit la même erreur. Il semblerait que la variable `gallery` ne soit pas définie (donc c'est pas un problème d'utf8).

**Comment by Alex-D** [comment]
`galery` ? C'est `gallery` partout dans le code normalement.

**Comment by Eskimon** [comment]
c'est juste @gustavi qui c'est trompe en ecriveant, c'est bien `gallery` partout dans le code

**Comment by gustavi** [comment]
C'est du franglais !!!

On peut savoir comment t'as réussi à faire péter ça @Eskimon ?

**Comment by Eskimon** [comment]
Arf j'avais pas vu ton message... J'avais casse ca en renommant ma galerie avec un caractère accentué. Du coup je sais pas si ca va etre simple a reproduire puisque cette histoire de caractère est corrigée.

**Comment by firm1** [comment]
Euh ... c'est normal que je ne trouve pas le bouton pour editer/renommer une gallerie ?

**Comment by Eskimon** [comment]
C'est ptet moi qui dit de la merde... Plutôt en supprimant en fait...

**Comment by firm1** [comment]
De mon coté, je n'arrive pas a reproduire avec toutes les bidouilles possibles sur les galleries.

Peut-être un conséquence heureuse d'une autre correction ? Du coup cette issue a t-elle lieu d'exister ?

**Comment by Eskimon** [comment]
J'aurais tendance a dire que, comme explique dans mon premier message, ce n'etait qu'une consequence d'un autre bug lie a l'UTF8 et qui a ete corrige.

**Comment by firm1** [comment]
bon bah on ferme alors. On réouvrira si necessaire quand ça se reproduira
