### ISSUE TITLE
Mauvaise redirection sur « zestedesavoir.com/tutoriels/telecharger/html/%3Ftutoriel%3D<n> »

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1638]
Quand on essaye d'accéder à « http://zestedesavoir.com/tutoriels/telecharger/html/%3Ftutoriel%3D432 », un « / » est automatiquement rajouté à la fin et fait tout planter (ce qui n'est pas le cas avec http://zestedesavoir.com/tutoriels/telecharger/html/?tutoriel=432). Je suppose que ça vient de `APPEND_SLASH` qui est à `True` par défaut (est c'est bien ; https://docs.djangoproject.com/en/dev/ref/settings/#append-slash) mais un certain nombre de personnes ont eu accès à ce lien (dont Google Bot).

Il faudrait vérifier dans `zds/tutorial/views.py` ligne 2904 que `request.GET["tutoriel"]` est bien un int, si c'est pas le cas on check si c'est un int suivit de « / » et on vire le « / » ?

Autre problème : comment à l'heure actuelle 50 personnes ont eu un lien foireux ? Ça concerne plusieurs tutoriels.

**Comment by Alex-D** [comment]
C'est pas ngnix qui rajoute le slash ?

**Comment by firm1** [comment]
> C'est pas ngnix qui rajoute le slash ?

si

**Comment by Eskimon** [comment]
Issue non fermé, fermeture auto a cause du nom d'un commit...

**Comment by gustavi** [comment]
Bon c'est pas vraiment une issue, on n'a plus ce problème.
