### ISSUE TITLE
Adresse email avec des caractères spéciaux provoque des 500 avec gravatar

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1640]
On a un membre qui a une adresse email avec un caractère spécial dedans et ça lève une exception quand on appelle cette ligne : https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/models.py#L123.

L'email ressemble à : `<foo>@\xfbgmail.com`

Le gros souci c'est que ça affecte toutes les pages où il y a l'avatar de ce membre.

Est-ce qu'il est normal qu'il puisse avoir une adresse email comme celle-ci ?
Si ce n'est pas normal, comment a-t-il fait ? (en modifiant son adresse mail ?)

Il faut également régler ce problème d'UTF8 sur l'appel `get_avatar_url` (au niveau de gravatar).

Les logs : http://paste.awesom.eu/0hjp

**Comment by Eskimon** [comment]
> Est-ce qu'il est normal qu'il puisse avoir une adresse email comme celle-ci ?

A priori dorénavant oui : http://fr.wikipedia.org/wiki/Adresse_%C3%A9lectronique

En gros, ne suffirait-il pas de passer simplement en unicode la chaîne (rajout du 'u').

**Comment by SpaceFox** [comment]
Je crois qu'il va falloir faire un patch "unicode", qui colle des "u"
devant TOUTES les chaînes de caractères du code.

**Comment by gustavi** [comment]
Ou alors on passe à python3 et plus de problème !

**Comment by SpaceFox** [comment]
Si tu corriges les dépendances qui ne supportent pas Python 3, ça peut se
faire !

2014-10-28 11:52 GMT+01:00 Laville Augustin notifications@github.com:

**Comment by GerardPaligot** [comment]
Je relance cette issue parce qu'elle n'a toujours pas été corrigée (malgré une tentative de PR) et qu'elle est toujours en prod.

**Comment by Eskimon** [comment]
Le souci c'est que si on la résout c'est du cote de git que ca merde... Donc il y a deux solutions:
- Passer a Python 3 :)
- Interdire les caractères alakon dans les emails

**Comment by Xalfen** [comment]
Interdire les caractères spéciaux dans les adresses emails, c'est aussi explicitement ne pas appliquer les RFC correspondantes. Perso, j'utilise les "+" dans mes emails pour me retrouver dans les différents sites où je suis inscrit (et aussi savoir d'où vient un mail si ton adresse a été leakée par exemple). Je trouverais ça un bête

**Comment by Eskimon** [comment]
Enfin corrigé :) Merci à tous !
