### ISSUE TITLE
Autoriser les adresses mail avec des caractères non-ASCII

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1642]
Aujourd'hui il n'est pas possible de s'enregistrer avec des caractères non-ASCII. Ça serait bien qu'on puisse le faire pour respecter les différentes RFC (cf. http://fr.wikipedia.org/wiki/Adresse_%C3%A9lectronique ).

**Comment by SpaceFox** [comment]
(Je fais mon chieur sur le titre, mais ces caractères ne sont "spéciaux" que pour les anglophones).

**Comment by gustavi** [comment]
(Pas faux mais j'ai suivi Wikipédia http://fr.wikipedia.org/wiki/Aide:Liste_de_caract%C3%A8res_sp%C3%A9ciaux ;) )

**Comment by Eskimon** [comment]
En fait je suis pas sur qu'il y ait un probleme ici... Sur ma version locale en mysql j'arrive à créer un compte avec accent sans souci

**Comment by Eskimon** [comment]
Autant pour moi, ca marche si le domaine est non-ascii mais pas la partie avant le @

**Comment by Eskimon** [comment]
Bon, c'est une limite de Django, on n'y peut rien... https://code.djangoproject.com/ticket/21859

**Comment by gustavi** [comment]
Il suffit de réécrire temporairement une fonction du validateur : https://docs.djangoproject.com/en/dev/_modules/django/core/validators/#EmailValidator

**Comment by Eskimon** [comment]
Ca en vaut vraiment la peine ? (si oui faut transformer le ticket en evolution plutot que bug)

**Comment by firm1** [comment]
> Ca en vaut vraiment la peine ?

je pense que oui, perso.

> si oui faut transformer le ticket en evolution plutot que bug

je pense que oui aussi (fait)

**Comment by SpaceFox** [comment]
Ce ticket n'intéresse personne depuis près d'un an **et** son équivalent chez Django depuis encore plus longtemps. Je ferme, rouvrira qui veut - mais AMHA il vaut mieux le corriger à la source.
