### ISSUE TITLE
Profil : rendre la section "Article" de la sidebar plus "logique" 

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1643]
Source:[Jérôme Deuchnord](http://zestedesavoir.com/forums/sujet/1424/profil-rendre-la-section-article-de-la-sidebar-plus-logique/?page=1#p24490)

---

Hello,

Je me permets une petite suggestion quant à l'affichage de la section _Articles_ de la sidebar : je trouve pour ma part qu'elle manque de « logique » (au sens humain du terme, pas au sens mathématique).

Voici par exemple ce que l'on peut voir sur mon profil au moment où j'écris mon message :

![La section *Articles* de la sidebar](http://i.imgur.com/BXZsNnc.png)

En réalité, j'ai trois articles :
- 2 sont en ligne
- 1 est en attente de validation
- Aucun n'est en cours de rédaction

*_Il faudrait donc revoir un peu cette partie-là pour que la partie *En cours de rédaction_ reflète ce qui l'est réellement. Personnellement, je considère comme en cours de rédaction tout article qui :
- n'est pas en ligne ni en validation
- _ou_ qui est en ligne mais dont une version plus récente, mais pas encore publiée (correctif, toussa), a été enregistrée.**

**Comment by Deuchnord** [comment]
Il faudrait que je mette plus souvent mes suggestions et rapports de bugs sur Github :/

**Comment by Eskimon** [comment]
Nan pas obligé, ca nous permet aussi de filtrer les doublons etc si jamais.
Passer par le forum permet de discuter surtout (pour les évolutions notamment)

**Comment by Deuchnord** [comment]
Ah, d'accord. :)

**Comment by Alex-D** [comment]
Faudrait juste soustraire ceux qui sont en ligne et en bêta à ceux en rédaction au final non ?

**Comment by gustavi** [comment]
Oui. Je suis dessus, PR demain matin.

**Comment by gustavi** [comment]
Le léger souci que j'ai c'est qu'en fait un article est toujours en brouillon.

**Comment by Eskimon** [comment]
Il y a pas un moyen de faire une comparaison de dates entre date de publication et date de dernière édition (si une telle donnée existe)

**Comment by gustavi** [comment]
je vais regarder ça, ça me semble assez hard comme solution.

**Comment by gustavi** [comment]
SI jamais un article est « brouillon » et « validation » on fait quoi ? On l'affiche dans les deux ? Ça me semble le mieux.

**Comment by firm1** [comment]
La règle de fait être : un article/tuto est en brouillon/rédaction si et seulement si la version draft est différente de la version publique. Autrement dit, si `sha_draft <> sha_public`

**Comment by Deuchnord** [comment]
Hmmm, en fait je n'avais pas envisagé ce cas particulier : un article 
peut être en validation et avoir été modifié, mais la version en 
validation reste en validation. Je pencherais donc effectivement plus 
pour la proposition d'Augustin, puisque la version en validation peut 
très bien être mise en ligne avant l'envoi en validation de l'état en 
brouillon (avis subjectif, pour ouvrir le débat :P). C'est donc un cas à 
part où un tuto/article a toutes ses raisons d'être mis dans deux 
sections en même temps :/
