### ISSUE TITLE
L'icône des tutoriels chevauche le texte

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1644]
Tout est sur l'image 
![screenshot_2014-10-29-00-17-31](https://cloud.githubusercontent.com/assets/6066015/4818845/d57139ce-5ef8-11e4-8218-7f4a6b778ad7.png)

**Comment by Alex-D** [comment]
Corrigé. Validé. Mergé.

**Comment by Eskimon** [comment]
Il faudra réouvrir, ce n'est pas corrigé : http://preprod.zestedesavoir.com/forums/sujet/1751/chevauchement-icone-tutoriels-et-texte/

**Comment by Eskimon** [comment]
Bon je referme ici, le ticket pour les titres h2 sera la : https://github.com/zestedesavoir/zds-site/issues/1808
