### ISSUE TITLE
Du texte qui se chevauche dans le sommaire global d'un big tuto

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1645]
Tout en image (cf. [lien en préprod](http://preprod.zestedesavoir.com/tutoriels/403/apprenez-a-programmer-avec-ada/), Chapitre 7).

Navigateur Chrome 37.

![capture d ecran de 2014-10-29 00 38 04](https://cloud.githubusercontent.com/assets/6066015/4819022/b31af772-5efb-11e4-9203-872cb9689e57.png)

**Comment by Alex-D** [comment]
Il interdire les titres de plus de 4 mots :-°

Faut "juste" rajouter une marge à droite.

**Comment by Alex-D** [comment]
Mergé en release.
