### ISSUE TITLE
Le logo sur la page « À propos » rend très mal

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1650]
Vu sur la preprod : http://preprod.zestedesavoir.com/pages/apropos/.

Le bug en question pour les autres : http://i.imgur.com/Xu7VX2x.png .

PING @Alex-D : il faudrait rajouter un background sur l'image ?

**Comment by gustavi** [comment]
Il semblerait que ce soit OK sur dev mais j'ai pas vu de commit qui parle de ça. Bug ou bien oublie de la mise à jour du pack.zip ?

**Comment by Alex-D** [comment]
> il faudrait rajouter un background sur l'image ?

Non. C'est juste que l'image utilisée est celle du logo en haut à gauche, il faudrait sortir une autre image pour cet endroit ou alors sortir une déclinaison du logo pour fond clair.

**Comment by Alex-D** [comment]
> Bug ou bien oublie de la mise à jour du pack.zip ?

La version en prod n'est pas bonne (pour une raison inconnue) donc ça se peut oui.

**Comment by SpaceFox** [comment]
> La version en prod n'est pas bonne (pour une raison inconnue) donc ça se
> peut oui.

Vu que c'est 100% automatisé, ça me fait peur là.

Le 29 octobre 2014 17:39, Alexandre Demode notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
Moi je t'ai déjà dit que l'image n'était pas à jour, chaque fois tu rejette la faute sur node et tout les outils front. Tout ce que je peux dire c'est que partout où je m'en sert (Win 8, Win 8.1, Debian Squeeze) ça fonctionne sans que je n'ai à bidouiller.

**Comment by SpaceFox** [comment]
Ça va bien la paranoïa oui ? Où est-ce que je dis ici que c'est la faute à Node ?

Je dis ici que toute la chaîne de déploiement est automatisée. Toute. La récupération Git et tout.

Donc je ne comprends pas comment on peut avoir _un_ élément qui foire en plein milieu. _Tous_ les éléments j'aurais compris, mais _un_ c'est vraiment bizarre. 

Ça implique forcément qu'on a un bout de processus non maîtrisé dans le lot, ce qui me fait peur, parce que un bout de processus non maîtrisé = une merde à plus ou moins long terme (d'ailleurs ça a commencé).

 Et ça ne présume absolument pas de la source du problème !

D'autre part la procédure de déploiement n'utilise pas de pack.zip : elle recompile tout le front.

Donc si je résume, on a un problème de front qui ne se met pas correctement à jour (en prod et en préprod), ce qui a pour effet de bord d'avoir une image foireuse.
Est-ce que c'est bien ça ?

Si oui, ce n'est pas "facile" du tout.

**Comment by Alex-D** [comment]
> elle recompile tout le front.

Je le sais bien, mais elle produit le pack.zip qui est utilisé par les dev pour la branche de développement. Donc c'est cohérents qu'ils n'aient pas le logo transparent si sur la prod c'est l'ancien logo avec fond.

> on a un problème de front qui ne se met pas correctement à jour (en prod et en préprod)

Non, en préprod ça fonctionne impec. Il n'y a que la prod qui a foiré et que sur cette image.

Mon avis est qu'il y a du y avoir une tambouille d'utilisateurs/droit/chmod sur le fichier en question. Sachant que ça passe par imagemin qui lance un nouveau processus pour la compression des images (ça peut peut-être poser problème). Ce qui expliquerait que malgré la mise à jour via gulp, le fichier ne soit pas mis à jour. Mais pour ça il faudrait checker ça sur le serveur pour en être certain.

**Comment by Alex-D** [comment]
Corrigé, testé, mergé. Arrivera en 1.3.

**Comment by Axylium** [comment]
Il faudrait rouvrir ici. Le bug ici, est toujours présent sur la v1.3.

**Comment by Eskimon** [comment]
Voila c'est vraiment réparé maintenant
