### ISSUE TITLE
Un membre banni ET en lecture seule a un mauvais statut

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1651]
Si un membre est banni ET mis en lecture seule (redondant mais admettons) alors le statut sous son avatar est absent au lieu de mentionner le "BANNI" (visible uniquement pour les staff)

Pour cela il faut changer la priorité de l'un sur l'autre dans le filtre: https://github.com/zestedesavoir/zds-site/blob/92da3bef853066b6ffa44c53f3c3c590b9565430/zds/utils/templatetags/profile.py#L38

**Comment by Eskimon** [comment]
Ah nan, ca n'a pas l'air de venir de la en fait... Du coup je comprend pas, en prod un membre est banni et pourtant rien ne s'affiche sous son avatar...

**Comment by Alex-D** [comment]
Il y a peut être quelque chose à voir par ici aussi : 
https://github.com/zestedesavoir/zds-site/blob/dev/templates/misc/badge.part.html

**Comment by Alex-D** [comment]
En local je ne peux rien faire, si je LS ou Ban j'ai cette stack d'erreur : 

```
Environment:


Request Method: POST
Request URL: http://localhost:3000/membres/profil/modifier/2/

Django Version: 1.6.8
Python Version: 2.7.8
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps',
 'django.contrib.humanize',
 'easy_thumbnails',
 'easy_thumbnails.optimize',
 'south',
 'crispy_forms',
 'email_obfuscator',
 'haystack',
 'munin',
 'zds.utils',
 'zds.pages',
 'zds.gallery',
 'zds.mp',
 'zds.article',
 'zds.forum',
 'zds.tutorial',
 'zds.member',
 'django.contrib.admin',
 'debug_toolbar')
Installed Middleware:
(u'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'zds.utils.ThreadLocals',
 'zds.middlewares.SetLastVisitMiddleware.SetLastVisitMiddleware',
 'zds.middlewares.profile.ProfileMiddleware')


Traceback:
File "A:\django\zdsenv\lib\site-packages\django\core\handlers\base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "a:\django\ZesteDeSavoir\zds\member\decorator.py" in _can_write_and_read_now
  19.         return func(request, *args, **kwargs)
File "A:\django\zdsenv\lib\site-packages\django\contrib\auth\decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "A:\django\zdsenv\lib\site-packages\django\db\transaction.py" in inner
  371.                 return func(*args, **kwargs)
File "a:\django\ZesteDeSavoir\zds\member\views.py" in modify_profile
  349.                            detail,

Exception Type: UnboundLocalError at /membres/profil/modifier/2/
Exception Value: local variable 'detail' referenced before assignment
```

**Comment by gustavi** [comment]
Oui `detail` n'est pas défini par défaut. Il faudrait la mettre à `''` ou `None` (ou une vraie valeur en fonction de ce qui se passe).

**Comment by Alex-D** [comment]
Donc c'est un bug bloquant de la 1.2 si je comprends bien ?

`None` me semble plus propre que `''`

**Comment by Eskimon** [comment]
Je me désengage, j'ai pas trop de temps/énergie en ce moment

**Comment by ChantyTaguan** [comment]
Ca a l'air réglé ça. A fermer ?

**Comment by Eskimon** [comment]
> Ca a l'air réglé ça. A fermer ?

Par quel magie ? (il y avait un membre qui était dans ces deux cas, faudrait le retrouver)

**Comment by ChantyTaguan** [comment]
Aucune idée, mais je viens de tester en local (sur dev) et j'ai bien l'étiquette banni sur un membre banni+LS.

Sauf si c'est un cas particulier, auquel cas faudrait des détails pour pouvoir reproduire.

**Comment by Eskimon** [comment]
Ouai faudrait que je retrouve le membre qui générait ca...

**Comment by Eskimon** [comment]
J'ai retrouve le membre, et je ne vois plus le souci... bref, je ferme !

**Comment by Eskimon** [comment]
En fait j'ai trouve ce qui pose probleme, ce sont les membres pas encore active... Dans la sidebar on les voit comme banni+LS alors qu'ils sont simplement pas active...

**Comment by Eskimon** [comment]
Je vais faire un nouveau ticket pour ca...
