### ISSUE TITLE
Le filtre du contenu en validation par catégorie ne marche pas

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1653]
L'url concernée est celle-la `/tutoriels/validation/?subcategory=17`

Elle devrait lister l'ensemble des tutoriels en validation mais pour la sous catégorie 17. Elle ne marche pas pour l'instant car elle renvoie tous les tutoriels en validation.

Il en est de même pour les articles.

**Comment by Eskimon** [comment]
Euh ca vient d'où ca ? car dans les URL je viens qui repond a ce schéma

**Comment by poulp** [comment]
Je n'arrive pas à reproduire le bug. J'ai crée deux tutoriels appartenant à deux catégories différentes sous le même utilisateur, mais le filtre marche bien.

**Comment by firm1** [comment]
> Je n'arrive pas à reproduire le bug. J'ai crée deux tutoriels appartenant à deux catégories différentes sous le même utilisateur, mais le filtre marche bien.

Je viens de retester actuellement en prod (et en préprod) et ça ne marche toujours pas.

C'est bizarre

**Comment by poulp** [comment]
Est ce que la catégorie 17 existe bien sur la prod ?

**Comment by firm1** [comment]
Oui.

Pour avoir ce lien, je vais dans la list des tutos en validation, et je clique sur une catégorie au hasard en dessous du libellé des tutos.

Tu ne reproduis pas en local ?

**Comment by ChantyTaguan** [comment]
Plop, je viens de tester aussi en local, et le filtre fonctionne effectivement...

**Comment by Eskimon** [comment]
En prod ca ne fonctionne toujours pas, j'envoie Ge0 a l'attaque :D

**Comment by Eskimon** [comment]
Ca doit se passer dans cette méthode : https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L113

**Comment by Ge0** [comment]
Plop,

Juste pour dire que j'ai bien reçu les directives d'Eskimon et que je traite ce bogue au plus vite.

**Comment by Eskimon** [comment]
Pour qui veut, la correction devrait etre la meme que celle-ci : https://github.com/zestedesavoir/zds-site/pull/2539

**Comment by pierre-24** [comment]
Corrigé :)
