### ISSUE TITLE
La date de dernière mise à jour d'un tuto est fausse

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1654]
La date de dernière mise à jour d'un tuto n'est pas mise à jour lorsqu'on modifie les extraits du tutoriel.

Ce qui fait donc que la date de dernière mise à jour affichée est souvent fausse. Et peut porter à confusion

**Comment by gustavi** [comment]
Je prends.

**Comment by firm1** [comment]
Je réouvre cette issue, car elle n'a pas été corrigée comme il faut.

Visiblement la correction ne fait qu'utiliser le champ `update` en base de donnée. Ce qui rend donc la date de dernière mise à jour fausse quand on consulte une version antérieur d'un tutoriel.

On se retrouve donc avec des choses tordu comme : 
- mon tuto est publié
- je modifie mon tuto hors ligne
- la date de dernière mise à jour en ligne correspond à la date de dernière mise à jour de mon tuto offline

La bonne façon de faire serait d'afficher la date du **commit** lié a une version particulière.

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
je sais pas. J'ajoute aux ticket "need test"

2015-04-16 14:36 GMT+02:00 Eskimon notifications@github.com:
