### ISSUE TITLE
Erreur 500 si je tente de lire un article ne rédaction via son url publique

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1655]
L'url en cause est celle là : `http://zestedesavoir.com/articles/105/crime/`

Etant donné que l'article est en cours de rédaction seulement, et que je tente d'y acceder via son url publique, j'ai une erreur 500 au lieu d'avoir tout simplement une 404.

Précision : l'erreur survient que je soit connecté ou pas. Staff ou pas.

**Comment by Eskimon** [comment]
C'est pas pareil que ca ?

https://github.com/zestedesavoir/zds-site/issues/1518

**Comment by firm1** [comment]
On dirait bien. Mais pourquoi c'est pas corrigé du coup ?

**Comment by Eskimon** [comment]
La bonne question... c'est ptet en preprod ?

**Comment by firm1** [comment]
En effet, c'est en preprod. :( je ferme ici donc
