### ISSUE TITLE
Banissement et envoie de MP

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#1657]
Salut tout le monde !

J'ai pu remarqué en faisant joue-joue avec ma version locale de ZdS, que quand un modo bannit un membre, ce dernier reçoit un MP.. Or, si le membre est bannit, il ne va pas pouvoir lire ses MPs.. Ne serait-il pas plus pertinnent d'envoyer un e-mail dans ce cas ?

**Comment by SpaceFox** [comment]
Bien vu, en effet :)

**Comment by firm1** [comment]
Ici le MP est là surtout pour garder une trace coté membre sur le site. Quand un membre est sanctionné il reçoit 1 MP et 1 Mail. Le mail en question contient le même message que le MP. Dans ton cas, vu que tu testais en local je suppose que tu n'a pas pu apprecier la fonctionnalité mail

**Comment by Eskimon** [comment]
Un moyen simple de verifier est de s'assurer de bien activer le backend mail dans la console (je me rappel plus de la ligne, je retrouve ca ce soir)

Cependant il me semble que le comportement est correct... Florian si tu veux contact moi par MP et je te ban sur la preprod :D (puis te deban après évidemment)...

**Comment by Axylium** [comment]
D'acc' ! Merci des précisions !

> Un moyen simple de verifier est de s'assurer de bien activer le backend mail dans la console (je me rappel plus de la ligne, je retrouve ca ce soir)

Ouaip je sais, mais je ne m'amuse pas toujours à rajouté cette ligne. ^^

Je ferme donc !
