### ISSUE TITLE
Problème statistiques modération

### ISSUE THREAD

**Issue by jcval** [zestedesavoir/zds-site#1665]
Prérequis : groupe staff.

Situation : j'ai un message signalé. Lorsque je consulte mon profil, la statistique "Alertes actives" vaut 0. Par contre, si un autre staff consulte mon profil, je suppose qu'il est affiché 1 (à confirmer).

**Comment by Eskimon** [comment]
Alerte active je vois 0 aussi sur ton profil

**Comment by jcval** [comment]
Par contre, tout fonctionne sur l'autre alerte. Peut être est-ce lié au groupe.

@Eskimon : peux tu rajouter les tags ?

**Comment by Eskimon** [comment]
Pour ceux que ca interesse, c'est ici que ca se passe:

Dans le template : https://github.com/zestedesavoir/zds-site/blob/dev/templates/member/profile.html#L396
Dans le modele : https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/models.py#L200

**Comment by Eskimon** [comment]
> Par contre, tout fonctionne sur l'autre alerte. Peut être est-ce lié au groupe.

Tu peux expliquer ?

**Comment by gustavi** [comment]
Est-ce que tu peux expliquer en détails comment reproduire le bug @jcval ?

**Comment by jcval** [comment]
Alors le prérequis, c'est être Staff (ping @Eskimon)

Etape 1 : quelqu'un **autre que moi** signale un de mes messages (https://zestedesavoir.com/forums/sujet/1557/erreur-500-sur-une-page-du-listing-des-membres/?page=1#p26981)

Etape 2 : je vais dans mon profil, rubrique modération > statistiques. Je vois : Alertes actives : 0

**Comment by Eskimon** [comment]
Ce qui me semble normal, moi (qui ai fait le signalement) voit bien 1 dans mes alertes actives

**Comment by Eskimon** [comment]
En gros le "alertes actives" presente le nombre de signalement que le membre a en cours. Si tu fait un signalement tu devrais le voir s'incrementer tant que l'alerte est pas resolu

**Comment by Eskimon** [comment]
Ok, apres discussion et eclaircissememt, pas de bug ici !

Pour rappel, voici ce que voit le staff :
- x alertes en cours que le membre a émise
- x messages que le membre s'est fait moderer
