### ISSUE TITLE
Problème d'affichage sur « Tous les articles »

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1666]
Le bug en question : https://i.imgur.com/0jIZu9v.png.

**Comment by Alex-D** [comment]
Ça va être corrigé avec la nouvelle accueil, cf ZEP 4 qui change le style des items.

Et il aurait fallu plus de précision : URL, taille d'écran, navigateur, etc.

**Comment by gustavi** [comment]
Firefox 32.0.3 (ArchLinux), http://zestedesavoir.com/articles/, 1600*900

**Comment by Eskimon** [comment]
Je met le mot-cle ZEP-4 pour m'en souvenir.

**Comment by Situphen** [comment]
Est corrigé par #2646 !
