### ISSUE TITLE
La liste des topics sur mobile s'affiche mal

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1669]
Tout en image (depuis le passage en 1.2)

Chrome sur Android

![screenshot_2014-11-05-22-58-32](https://cloud.githubusercontent.com/assets/6066015/4926922/625ad45a-6537-11e4-9d3e-8c557a93c5fe.png)

**Comment by Alex-D** [comment]
J'ai un hotfix.

**Comment by Alex-D** [comment]
Done. A valider.

**Comment by gustavi** [comment]
C'est en preprod.
