### ISSUE TITLE
La liste des topics s'affiche très mal sur PC en 90%

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1670]
Chrome 37 sur PC, voir la capture. Le bug est introduit depuis la v1.2

![capture d ecran de 2014-11-05 23 16 09](https://cloud.githubusercontent.com/assets/6066015/4927212/81c50bf6-6539-11e4-8238-ada65080d1d1.png)

**Comment by SpaceFox** [comment]
Aucun problème sous Chrome 38.0.2125.111 m.

Essaie de mettre ton cache à jour ?

**Comment by firm1** [comment]
Cache mis à jour et ça ne change rien.

**Comment by Axylium** [comment]
Sous Firefox 33.0 je n'ai pas ce problème qui apparaît sur les pages de topics, par-contre, je l'ai sur les pages de profils.

Cache mis à jour !

**Comment by SpaceFox** [comment]
Non reproductible sous Windows 8 : Chrome 38 / Opera 25 / IE11 / FF32.

Merci d'envoyer les URLs des pages problématiques.

**Comment by firm1** [comment]
Firefox 32 (ubuntu), c'est moins pire, mais il y'a aussi un bug.

url : http://zestedesavoir.com/forums/sujets/tag/218/beta/

![capture d ecran de 2014-11-05 23 29 57](https://cloud.githubusercontent.com/assets/6066015/4927443/7bcaaec0-653b-11e4-8148-0abccc181bce.png)

**Comment by Axylium** [comment]
Par-exemple sur ma page de profil : http://zestedesavoir.com/membres/voir/Flori%40n.B/

Et je rectifie aussi ce que j'ai dit avant, je l'ai également sur les forums. Dès qu'un sous-titre passe sur deux lignes.

Pour info je l'ai sur : Firefox 33.0 & Chromium 37.0.2062.120 (le tout sous ubuntu)

**Comment by Alex-D** [comment]
Doublon de #1669 qui a déjà son petit patch en attente.

**Comment by firm1** [comment]
Je ré-ouvre ici, car le problème n'est pas résolu sur PC (Cf capture). J'ai encore des sous titres qui se décalent vers la droite. 

Chrome 37.

![capture d ecran de 2014-11-12 08 19 09](https://cloud.githubusercontent.com/assets/6066015/5006645/3bb6d772-6a46-11e4-9a22-b89ab15c1bb8.png)

**Comment by Situphen** [comment]
Je n'ai pas ce bug sur Firefox 34 et Chrome 39, tu peux revérifier ?

**Comment by gustavi** [comment]
Moi je n'ai pas ce bug (Firefox/Arch).

**Comment by Eskimon** [comment]
Je n'ai jamais vu ce bug non plus

**Comment by Situphen** [comment]
@firm1 tu as toujours ce bug ou on peut fermer ?

**Comment by firm1** [comment]
Le bug est tjours présent.

firm1

**Comment by Situphen** [comment]
Quel navigateur ?
Quel OS ?
Quel version (prod, dev...) ?

**Comment by firm1** [comment]
C'etait sur Chrome 37 ubuntu en v1.2.

J'ai pas vérifié si ça se reproduit en 1.3, mais a ma connaissance rien n'a été fait en 1.3 pour corriger ça.

**Comment by Situphen** [comment]
Ce serait cool si tu pouvais vérifier en v1.3 et sur la branche dev ! :)

**Comment by gustavi** [comment]
@firm1 est-ce que c'est encore présent ?

**Comment by ghost** [comment]
@firm1 est-ce que c'est encore présent ?

**Comment by firm1** [comment]
Ouaip.

![decale](https://cloud.githubusercontent.com/assets/6066015/6124397/6ddd1b9a-b10d-11e4-8d40-9be8b4095cdb.PNG)

**Comment by SpaceFox** [comment]
J'ai fini par comprendre : c'est parce que tu es dézoomé.

Ce n'est pas l'utilisation normale du front. Donc soit je ferme ici en mode "wontfix", soit je le laisse mais en évolution non prioritaire.

**Comment by SpaceFox** [comment]
PS : la prochaine fois que tu signales des bugs de design, vérifie que tu es bien à 100% d'affichage, ou alors indique le clairement dans l'issue.

**Comment by A-312** [comment]
C'est quasiment impossible de faire un css compatible au zoom... Je pense qu'il faudrait fermer.

**Comment by ghost** [comment]
Ca doit être des petits détails qui ont une différence de quelques pixels ou dixièmes de pixel...

**Comment by firm1** [comment]
Ah oui, je pensais l'avoir précisé dans le premier post. Je navigue sur ZdS toujours en dezoom 90%. Etant donné qu'on est sur des tailles de type em/rem, on devrait quand même avoir un bon affichage à 90%.

Du coup le marquer en evolution serait pas mal.

**Comment by SpaceFox** [comment]
Voilà.

**Comment by artragis** [comment]
Il semblerait que ça n'ai plus lieu.

**Comment by SpaceFox** [comment]
Alors on ferme.
