### ISSUE TITLE
Affichage des tags dans un topic

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1671]
Sur ce [topic](http://zestedesavoir.com/forums/sujet/1463/suggestion-http-https-www-ou-pas/?page=1#p27653) j'ai l'affichage ci-dessous. Sur l'affichage des tags en haut à droite en bleu, on n'a pas de séparation entre le tag http et le tag suggestion (on est censé avoir une ligne verticale blanche qui sépare les deux comme a coté). Alors qu'il s'agit en réalité de deux tags différents.

Chrome 37 sur PC.

![capture d ecran de 2014-11-05 23 22 17](https://cloud.githubusercontent.com/assets/6066015/4927280/3b6ac76c-653a-11e4-80bd-f5c216504bf2.png)

**Comment by SpaceFox** [comment]
Non reproductible sous Windows 8 : Chrome 38 / Opera 25 / IE11 / FF32.

Vérifie ton cache.

**Comment by Alex-D** [comment]
Ca doit être lié à tes pilotes graphiques. Et dans l'absolu c'est méga mineur et très spécifique (à priori c'est ta config matérielle/logiciel bas niveau plus que navigateur).

**Comment by GerardPaligot** [comment]
> ta config matérielle/logiciel bas niveau plus que navigateur

Whaaaaaaat ?! Comment la config matérielle peut influencer du CSS dans une page web ?

**Comment by Eskimon** [comment]
antialiasing, résolution et autre joyeuseté j'imagine ?

**Comment by firm1** [comment]
Je veux bien "imaginer" que c'est ma confi matérielle, mais je ne vois pas comment ça ne pourrais se produire que sur un malheureux boutons qui traine au fond de l'écran.

J'ai jamais vu ça

**Comment by GerardPaligot** [comment]
Je rejoins à 100% @firm1. Je trouve juste ça surréaliste.

**Comment by SpaceFox** [comment]
100% d'accord, je ne pige pas.

**Comment by Alex-D** [comment]
Bah écoutez : 
- il y a une propriété CSS qui fonctionne partout sauf chez @firm1 
- dans une configuration logiciel iso à la sienne on obtient pas le bug

Donc :
- je ne peux pas le reproduire
- je ne peux pas le corriger

La seule raison qui peut affecter ça c'est un bug de Blink ou un problème de sa config matériel / drivers.

Surtout qu'il y a du flotant et que le flotant ça n'a jamais été ce qu'il y a de plus précis.

**Comment by gustavi** [comment]
UP @firm1 ! C'est toujours présent ? Sur la preprod également ?

**Comment by ghost** [comment]
@firm1 est-ce que c'est encore présent ?

**Comment by firm1** [comment]
Je viens de reproduite le bug, et en même temps je me suis rendu compte que c'est parce que j'étais à un zoom de 80%, donc ce n'est pas vraiment un bug, je ferme donc.
