### ISSUE TITLE
Les emails sont illisibles sur la page de profil

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1672]
Sur ma page de profil, mon email est devenu illisible (depuis la v1.2) :
 http://zestedesavoir.com/membres/voir/firm1/#infos-generales

Tout ce que je vois c'est ça : `E-mail : %s`

Chrome 37 / Ubuntu

**Comment by Alex-D** [comment]
https://github.com/zestedesavoir/zds-site/blob/dev/templates/member/profile.html#L64

Le front est OK. Ca vient du back (tout du moins, du Python).

**Comment by firm1** [comment]
Comment ça se fait que ça marchait bien avant et que ça a pété à la MEP de la 1.2 ?

**Comment by Alex-D** [comment]
Est-ce que ça pourrait venir du filtre `email_obfuscator` ?

**Comment by firm1** [comment]
> Est-ce que ça pourrait venir du filtre email_obfuscator ?

J'aurai dit oui s'il avait changé entre la v1.1 et la v1.2, mais ce n'est pas le cas

**Comment by Alex-D** [comment]
C'est aussi ce qui me semble étrange. Le front n'a pas été touché à ce niveau là non plus (en tous cas je n'y ai pas touché).

Donc ça pourrait venir de la PR qui filtre le contenu affiché pour les comptes bot qui foirerait dans le cas de cet attribut pour les membres ?

**Comment by poulp** [comment]
Si ça vient bien de _email_obfuscator_, la version pypi est plus ancienne que le repo dans lequel il a ajouté un fix pour ce problème, faut installer la version la plus récente et ça fonctionne : `pip install git+https://github.com/morninj/djangomail-obfuscator.git`

**Comment by firm1** [comment]
Tu nous fait une joli PR ? je suppose qu'il suffit de modifier le fichier requirements.txt ?

**Comment by firm1** [comment]
C'est fixé.

Merci à @poulp content de te revoir sur notre dépot.
