### ISSUE TITLE
Affichage des tutoriels en beta depuis un profil membre est cassé

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1673]
url : http://zestedesavoir.com/tutoriels/recherche/174/?type=beta

Chrome 37/Ubuntu 

![capture d ecran de 2014-11-05 23 41 25](https://cloud.githubusercontent.com/assets/6066015/4927596/facac8e4-653c-11e4-8f60-2e4cd5c558db.png)

**Comment by Alex-D** [comment]
J'ai trouvé la source du bug, je fais un patch dans les jours à venir.

**Comment by ghost** [comment]
Bug d'actualité ?

**Comment by Eskimon** [comment]
Chez moi ca marche bien sur Chrome/Ubuntu et Chrome/Android 4.4.4. Si qqun peut confirmer sur un autre navigateur on peut fermer.

**Comment by firm1** [comment]
Je confirme que ce bug est corrigé. On peut donc le fermer
