### ISSUE TITLE
Le logo sur la page à propos pointe sur la preprod.

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1674]
via [Luthaf](http://zestedesavoir.com/forums/sujet/1596/lien-vers-la-preprod-sur-la-page-da-propos/)

> Lorsque je vais sur la page à-propos, je me prend une demande d'authentification HTTP pour le domaine preprod.zestedesavoir.com. Il doit donc y avoir un lien en trop qui traine sur cette page.

En effet en allant sur [la page en question](http://zestedesavoir.com/pages/apropos/), on voit le souci.

**Comment by Alex-D** [comment]
A mon avis c'est lié à #1676

**Comment by Alex-D** [comment]
J'ai regroupé ici : #1690
