### ISSUE TITLE
Lien vers la preprod dans les emails de notifications

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1676]
via [Luthaf](http://zestedesavoir.com/forums/sujet/1597/liens-vers-la-preprod-dans-les-email-de-notifs-mp/)

> C'est le jour dites-donc ! (et j'en ai un troisième \o/)
> 
> Donc dans les mails de notifs de MP, le liens pointe vers la préprod. Pour reproduire : demandez-moi, je vous envoie un MP, dans l'email que vous recevez, le lien est vers preprod.zestedesavoir.com.

Je penche ici pour un problème dans le settings_prod.py

**Comment by Alex-D** [comment]
Je justifie le tag bloquant : c'est un problème général qui touche donc les emails d'inscription et de confirmation. C'est donc bloquant car a priori il n'est plus possible de s'inscrire.

**Comment by Alex-D** [comment]
J'ai regroupé ici : #1690
