### ISSUE TITLE
Erreur 500 en essayant de résoudre une alerte

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1677]
Comme on peut le voir dans la capture ci-dessous, j'ai tenté de résoudre une alerte sur un topic du forum beta et j'ai une erreur 500 sur l'url : http://zestedesavoir.com/forums/resolution_alerte/

PS : l'alerte n'est toujours pas résolue.

![capture d ecran de 2014-11-05 23 59 22](https://cloud.githubusercontent.com/assets/6066015/4927934/b880d278-653f-11e4-8202-ed54b9755105.png)

**Comment by Alex-D** [comment]
J'apporte un complément : ça plante uniquement si on met un message. Si on laisse la zone vide, ça passe. Donc il doit y avoir un soucis au niveau de la gestion du message dans le MP ou quelque chose de ce style.

**Comment by Eskimon** [comment]
Ca doit etre ma faute je pense : https://github.com/zestedesavoir/zds-site/pull/1514

**Comment by gustavi** [comment]
J'ai trouvé d'où ça vient avec Sentry : 

```
AttributeError: 'Settings' object has no attribute 'BOT_ACCOUNT'

Stacktrace (most recent call last):

  File "django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "zds/member/decorator.py", line 19, in _can_write_and_read_now
    return func(request, *args, **kwargs)
  File "django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "zds/forum/views.py", line 311, in solve_alert
    bot = get_object_or_404(User, username=settings.BOT_ACCOUNT)
  File "django/conf/__init__.py", line 55, in __getattr__
    return getattr(self._wrapped, name)
```

**Comment by Eskimon** [comment]
Pour corriger, utiliser la variable d'opensourcisation

**Comment by Eskimon** [comment]
Je prend, j'ai la correction + TU

**Comment by gustavi** [comment]
C'est en preprod.
