### ISSUE TITLE
Rediriger www.zestedesavoir.com vers zestedesavoir.com (ou l'inverse)

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1679]
Yop !

Les www sont facultatif, on a donc deux URLs possible pour toutes les pages, donc c'est pas cool, notamment pour le référencement, les cookies, le localStorage, etc. Car c'est un sous-domaine donc c'est gênant.

Il faudrait donc rediriger http://zestedesavoir.com vers http://www.zestedesavoir.com (ou l'inverse)

Personnellement, je trouve que les www sont inutiles et qu'ils sont un vestige historique devenu obsolète.

Il me semble pourtant que ça avait été fait à un moment donné.

**Comment by firm1** [comment]
Ceci est déjà fait.
