### ISSUE TITLE
Erreur sur les notifications

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#168]
Je ne comprends pas l'erreur mais elle est provoquée par [cette ligne](https://github.com/Taluu/ZesteDeSavoir/blob/dev/templates/base.html#L192) selon le debugger de Django. 

J'ai pour l'instant commenté les lignes en question pour pouvoir continuer à développer.

**Comment by firm1** [comment]
Corrigée. Je ferme.
