### ISSUE TITLE
Les liens des miniatures ne sont pas préfixés

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1680]
Les liens des miniatures générées sont pas préfixés de `http://zestedesavoir.com`, du coup lors d'un clic on n'est pas renvoyé vers le site mais vers `/media/blablabla.png` au lieu de `http://zestedesavoir.com/media/blablabla.png`

**Comment by Alex-D** [comment]
~~Est-ce que ça n'est pas encore lié à #1676 à cause d'un problème de configuration du coup ?~~

J'ai dit une ânerie.

**Comment by Alex-D** [comment]
En théorie, quand tu es sur un domaine, et que tu fais `/quelquechose` ça doit fonctionner. Donc j'ai du mal à comprendre le bug. Tu as une page où le bug est visible ?

**Comment by Eskimon** [comment]
Test simple : Ajoute une image dans une gallerie puis colle le texte de la miniature (celle avec le lien) dans un sujet (fofo ? teste sur MP perso). Tu verras quand tu clic sur l'image ca bug

**Comment by Alex-D** [comment]
Bug de Markdown en fait.

**Comment by Alex-D** [comment]
Voilà rapporté : #54

En attendant on peut toujours rajouter le domaine comme tu dis, ~~mais ça veut dire qu'on aura des liens pétés en preprod par exemple.~~ En fait ça fonctionnera.

**Comment by firm1** [comment]
Fixé.
