### ISSUE TITLE
Erreur 500 si la pagination n'est pas un int

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1682]
Quand on accède à url?page=_autre_chose_qu_un_int_ on se mange une belle 500, il serait peut-être préférable de renvoyer la page 1.

Le bout de code à modifier dans `zds/article/views.py` (ligne 166) est :

```
    try:
        page_nbr = int(request.GET['page'])
    except KeyError:
        page_nbr = 1
```

qu'il faudrait remplacer par : 

```
    try:
        page_nbr = int(request.GET['page'])
    except KeyError:
        page_nbr = 1
    except ValueError:
        page_nbr = 1
```

Il faudrait même le faire de partout et peut-être mettre cette fonction dans `misc`.

**Comment by Alex-D** [comment]
Non. La bonne solution est de renvoyer une 404. La page demandée est introuvable, c'est texto le cas dans lequel on rentre.

**Comment by SpaceFox** [comment]
+1 Alex.

Le 6 novembre 2014 11:59, Alexandre Demode notifications@github.com a
écrit :

**Comment by firm1** [comment]
Fixé
