### ISSUE TITLE
Le menu de gauche de la page profil d'un membre incompréhensible sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1683]
L'image parle d'elle même dans la zone d'activité.

Qu'est ce qui est en ligne ? Qu'est ce qui est en beta ?

Chrome/Android

![screenshot_2014-11-06-12-24-41](https://cloud.githubusercontent.com/assets/6066015/4935021/bf18c092-65a7-11e4-8119-8204fec658b0.png)

**Comment by Alex-D** [comment]
Ah en effet il manque un niveau. Ca se met à jour assez simplement.

Je vois d'ailleurs que les compteurs sont mal positionnés.

**Comment by Eskimon** [comment]
Ca fait 6 mois que ca traîne pour un problème qui semble pourtant trivial. @Situphen tu penses avoir le temps de jeter un oeil ?

**Comment by Eskimon** [comment]
Merci @Situphen :)
