### ISSUE TITLE
Les liens automatiques des sujets en beta, pointent sur la preprod

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1684]
Sur [ce topic](http://zestedesavoir.com/forums/sujet/1603/redorer-votre-blason-sur-google-search-le-personal-branding/) crée automatiquement, le lien pointe sur la preprod.

**Comment by Axylium** [comment]
Petite question peut-être bête, mais bon. Ne serait-il pas plus pertinent d'ouvrir une seul issue pour tout ça ? Car nous savons maintenant que la plupart (tous ?) des liens pointent vers la préprod'. Et, apparement de ce que j'ai compris cela vient du même bug. Ouvrir un sujet pour chaque lien n'est-ce pas trop ?

**Comment by Alex-D** [comment]
J'ai regroupé ici : #1690

**Comment by SpaceFox** [comment]
Le paramètre est corrigé mais il faut éditer les 1ers messages de tous les topics de mis en bêta créés aujourd'hui.

**Comment by firm1** [comment]
Les sujets en questions on été corrigé.

Je ferme ici donc.
