### ISSUE TITLE
Le bouton de lecture zen est mal placé

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1685]
Comme on peut le voir sur l'image ci-dessous.

Firefox 33.
Windows 7
Url : http://zestedesavoir.com/tutoriels/234/creer-un-jeu-html5-avec-quintus/275/quelques-manipulations-de-base/1551/vocabulaire-de-base/

![bouggi](https://cloud.githubusercontent.com/assets/6066015/4937914/b6d2b512-65c7-11e4-830e-5fa63bca727d.PNG)

**Comment by Alex-D** [comment]
En fait ce sont les tags qui ne sont pas à leur place.

**Comment by gustavi** [comment]
Il semblerait que ça se résolve facilement : 

> Résolu dans l'inspecteur en supprimant la marge négative du haut.

via #1813

**Comment by firm1** [comment]
> Il semblerait que ça se résolve facilement : 

En fait cette solution ne fonctionne pas pour tous les cas. Le problème c'est que sur la page incriminée, on affiche pas la licence, et donc ça pète tout.

**Comment by Situphen** [comment]
Je viens de regarder et le bouton est mal placé sur tous les tutoriels et les articles qui n'ont pas de description. Ce qui fait que les tags se heurtent à la licence et bloque sur leur gauche le bouton "Lecture Zen" !

**Comment by gustavi** [comment]
Corrigé ! Merci @Situphen !
