### ISSUE TITLE
Manque de cohérence dans l'affichage des licences

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1686]
Windows 7
Firefox 33

Tutoriel Quintus.

[url générale du tutoriel](http://zestedesavoir.com/tutoriels/234/creer-un-jeu-html5-avec-quintus/)

Affichage.
![step1](https://cloud.githubusercontent.com/assets/6066015/4938019/8603536e-65c8-11e4-8318-7c63fc475853.PNG)

[url d'un chapitre du même tutoriel](http://zestedesavoir.com/tutoriels/234/creer-un-jeu-html5-avec-quintus/275/quelques-manipulations-de-base/1551/vocabulaire-de-base/) : 

Affichage.

![step2](https://cloud.githubusercontent.com/assets/6066015/4938016/824206e4-65c8-11e4-8858-af2d42e2e3b9.PNG)

**Problème** : d'un coté on a "Licence CC BY-NC-ND" de l'autre on a juste "CC BY-NC-ND"

**Comment by firm1** [comment]
Le bug est décidément présent un peu partout. sur la page d'historique (du même tutoriel) on voit le mot licence qui apparait deux fois (cf. image).

![topo](https://cloud.githubusercontent.com/assets/6066015/4938311/89d6b434-65ca-11e4-8725-6a0042b2e0d8.PNG)

**Comment by Eskimon** [comment]
Doublon ? https://github.com/zestedesavoir/zds-site/issues/1560

**Comment by firm1** [comment]
Ah en effet :)
