### ISSUE TITLE
Mauvaise optimisation de l'espace dans la liste des forums

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1687]
Windows 7
Firefox 33

url : http://zestedesavoir.com/forums/

Le tout en image.

![nextbref](https://cloud.githubusercontent.com/assets/6066015/4938201/bb7a0b36-65c9-11e4-88d8-c8edd606a6a6.PNG)

**Comment by Alex-D** [comment]
Ca n'est pas un bug. Mais une suggestion : ça fonctionne et c'est le comportement souhaité jusqu'à preuve du contraire.

La justification est simple : c'est calqué sur la grille de la liste des sujets. Si on veut changer les largeurs ici, on augmente le risque d'incohérence entre cette page et celle de la liste des sujets.

**Comment by firm1** [comment]
Je ne sais pas d'ou vient cette suggestion, mais je trouve ça (d'un point de vue utilisateur pur) bugué.

J'ai de la place, mais elle n'est pas utilisée. L'utilisateur n'a pas besoin de savoir que le code est ré-utilisé ou pas, tout ce qu'il voit c'est qu'il y'a de l'espace qui est perdu sur la page.

**Comment by Alex-D** [comment]
Pas optimisé != bugué. On va arrêter de dire sans arrêt que tout est bugué. C'est impossible de savoir ce qui est prioritaire ou non après.

Bref. Il faut en discuter sur le forum et rapatrier le résultat de la discussion ici. Il faut savoir ce que les gens veulent qu'on affiche, où et comment.

**Comment by Eskimon** [comment]
> L'utilisateur n'a pas besoin de savoir que le code est ré-utilisé ou pas, tout ce qu'il voit c'est qu'il y'a de l'espace qui est perdu sur la page.

Toutafé

**Comment by GerardPaligot** [comment]
Ce "bug" est loin de me choquer. Là est toute la difficulté dans le responsive design. Toi tu vois de la place, une autre personne n'en verra pas tant que ça avec un écran plus petit.

**Comment by ghost** [comment]
Personnellement ça ne me choque pas, peut-être l'ajuster avec du JS ?

**Comment by GerardPaligot** [comment]
Bien, je vais répondre en ma qualité de chef de projet alors. Aujourd'hui, cette issue est remontée que par un seul membre, @firm1. Bien que son avis compte autant que tous les membres de la communauté, il n'en reste pas moins le seul à rapporter ça comme gênant. Si un sujet est créé sur ZdS et que plusieurs membres trouvent ça gênant, il sera toujours tant de rouvrir cette issue ou de créer une nouvelle issue avec la spec attendue. En attendant, je ferme donc.
