### ISSUE TITLE
Le bouton lecture zen se trouve sur des pages où il ne devrait pas

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1688]
Windows 7
Firefox 33

On aperçoit le bouton "lecture zen" dans l'historique d'un tutoriel. [ici par exemple](http://zestedesavoir.com/tutoriels/historique/234/creer-un-jeu-html5-avec-quintus/)

Ce n'est pas une page de lecture de contenu, donc le bouton "lecture zen" ne devrait pas y être

**Comment by Alex-D** [comment]
La détection est automatique et en JS : s'il y a un titre + date + ... (voir le JS pour les détails) ça considère que c'est une page de contenu.

Donc, au niveau du code _c'est_ une page de contenu. Du coup, en ce sens c'est cohérent.

La solution serait alors d'ajouter une classe sur toutes les pages où il faut rajouter le bouton : beaucoup plus lourd mais plus sûr (puisqu'on sélectionne exactement les pages que l'on veut).

**Comment by SpaceFox** [comment]
> La solution serait alors d'ajouter une classe sur toutes les pages où il faut rajouter le bouton : beaucoup plus lourd mais plus sûr (puisqu'on sélectionne exactement les pages que l'on veut).

Heu oui, c'est à faire comme ça... je ne pige même pas la logique de "la détection automatique en JS".

**Comment by Alex-D** [comment]
Ca a été fait à un moment où les templates bougeaient pas mal, donc la solution d'une détection sans toucher aux templates était pratique. Mais à terme c'est naze. Tout comme d'autres trucs tels que l'aide Markdown, etc.
