### ISSUE TITLE
Sous titres et messages d'informations

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#169]
Actuellement, les sous-titres d'un Forum ne sont pas designé sur ZdS.

Je vois pourtant que [ici](http://zds.alex-d.fr/forum-topic-staff.html) c'est déjà designé, mais ce n'est pas encore effectif en [preprod](http://preprod.zestedesavoir.com/forums/sujet/7/rediger-sur-zds?page=2#p77) on dirait.

Autre chose aussi. Lorsqu'un topic est locké ou résolu, il faudrait un message en haut pour signaler que le topic est locké ou résolu.

**Comment by Alex-D** [comment]
Il manque juste la classe subtitle sur l'élément.
Je l'ajouterais ce soir.

**Comment by firm1** [comment]
C'est fixé, je ferme
