### ISSUE TITLE
Manque de cohérence dans l'affichage du bouton d'aide markdown

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1691]
Firefox 33
Windows 7

Cf. Image. Dans la première capture, on voit que le bouton "Afficher l'aide markdown" n'est pas sur la même ligne que les boutons "Aperçu" et "Envoyer"

**Le mauvais exemple** : 

![eloigne](https://cloud.githubusercontent.com/assets/6066015/4939519/a45a1bb2-65d3-11e4-8732-c46f39094872.PNG)

**Le bon exemple** : 

![gud](https://cloud.githubusercontent.com/assets/6066015/4939534/c32963cc-65d3-11e4-8c46-57e5075ed5d0.PNG)

**Comment by Alex-D** [comment]
Très honnêtement, ça fait un nombre de fois incalculable que c'est remonté et que je réponds à chaque fois : #465 et #464

C'est pas nouveau, et on est pas magicien.

**Résumé** :

Le formulaire de réponse à un sujet est soigné : je l'ai recodé de A à Z en shintant la gestion des formulaire du back, puisque non adapté.

Sur les formulaires des tutos, édition de message, etc. J'ai laissé le back faire car trop compliqué de réinventé la roue quand il y a de la gestion de validation de formulaire.

La solution est simple et je la demande depuis perpette : faire un template pack, notamment pour avoir un nouveau type de champ personnalisé pour l'éditeur markdown (plutôt que de bidouiller avec des classes à chaque fois, on aurait un type de champ précis dans le back). Aussi, le bouton et l'aide passeraient dans ce template pack plutôt que de fix dégueu en JS.

**Comment by firm1** [comment]
Sur mobile c'est pire. Le bouton d'aide est caché derrière les boutons aperçu et envoyer. Cf. Screen.

![screenshot_2014-11-07-17-49-52](https://cloud.githubusercontent.com/assets/6066015/4956865/8868e542-669f-11e4-9a72-34d21ccd3484.png)

**Comment by Alex-D** [comment]
Y la PR #1558 qui a corrigé ça. Vérifie ton cache ou alors il y a un soucis.

**Comment by firm1** [comment]
Il y'a bien un souci. Cache verifié

**Comment by Alex-D** [comment]
J'ai en effet le même rendu :/ Pourtant la PR visait à corriger tout ça... je regarderais.

**Comment by Eskimon** [comment]
Ca existe encore ce problème ?

**Comment by firm1** [comment]
bug toujours présent

**Comment by gustavi** [comment]
Alors j'ai identifié le bug mais je ne sais pas le corriger.

Ça vient du fichier https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/markdown-help.js.

En gros ça ajoute le bouton après `.md-editor` sauf que cette classe ne se trouve pas partout au même endroit.

Sur la création d'un topic ça vient sur le `textarea` sauf que celui-ci est encapsulé dans d'autres `<div>` donc control-groups. On a donc un comportement foireux.

Sur l'envoi d'un message c'est correct puisque le `textarea` est "seul".

Si quelqu'un a une idée je suis preneur.

**Comment by Situphen** [comment]
Comme l'a dit Alex-D plus haut :

> La solution est simple et je la demande depuis perpette : faire un template pack, notamment pour avoir un nouveau type de champ personnalisé pour l'éditeur markdown (plutôt que de bidouiller avec des classes à chaque fois, on aurait un type de champ précis dans le back).

Actuellement on utilise `django-crispy-forms` donc on est complètement dépendant des choix de leurs _templates_. Si on veut changer des trucs (pour résoudre ce problème par exemple), il faut faire un fork.

**Comment by gustavi** [comment]
Je pense vraiment qu'on peut se passer de faire un fork avec un peu de bidouille. Il suffit de mettre l'attribut `.md-editor` au bon endroit, quitte à le renommer.

**Comment by Situphen** [comment]
Je te laisse essayer... Si tu y arrives sans foirer et sans que ce soit trop crade, GG
