### ISSUE TITLE
La croix des alert-box n'est pas centrée

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1692]
Firefox 33
Windows 7

Le problème en image.

![label](https://cloud.githubusercontent.com/assets/6066015/4939694/eab0f4e0-65d4-11e4-9fe1-23122ba62dea.PNG)

**Comment by Alex-D** [comment]
J'ai vu ça tout à l'heure, je n'ai pas trop compris le pourquoi du comment.

**Comment by SpaceFox** [comment]
Corrigé, mergé, fermé !
