### ISSUE TITLE
Erreur 500 quand on télécharge un tuto pas encore créé

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1694]
Il suffit d'aller sur [ce lien](http://zestedesavoir.com/tutoriels/telecharger/?tutoriel=), pour avoir une erreur 500.

J'ai réussi à l'avoir en tentant de télécharger (puisque le lien m'était proposé) un tutoriel sans l'avoir crée depuis via ce [lien](http://zestedesavoir.com/tutoriels/nouveau/tutoriel/) et en cliquant sur archive.

**Comment by Alex-D** [comment]
Soucis de template. Faudrait juste retirer le bloc de la sidebar quand c'est pas utile.

**Comment by Eskimon** [comment]
C'est merge, c'es ferme !
