### ISSUE TITLE
[ZEP-04] Intégration de la nouvelle page d'accueil

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1699]
Dépendance : #1700

Intégrer la nouvelle page d'accueil selon la [ZEP-04](http://zestedesavoir.com/forums/sujet/669/zep-04-nouvelle-page-daccueil/).

**Comment by A-312** [comment]
Je prend, je vous tiens au courant. (La première PR sera établie avant samedi 21).

**Comment by abdelaz3r** [comment]
Je prends. Je dois regarder avec sandhose comment on s'organise, installer tout le projet et après je commence l'intégration.

**Comment by Eskimon** [comment]
SVP communiquez aussi avec A-312 et formez un MP/equipe pour bosser la dessus. Si on se retrouve avec deux PR on va jamais s'en sortir et se serais vraiment dommage...

Donc je resume, personne bossant ici :
- @sandhose 
- @abdelaz3r 
- @A-312

**Comment by Situphen** [comment]
Je peux aider aussi !

@abdelaz3r : Tu peux me contacter au moindre problème lors de l'installation ! AMHA le mieux est IRC (https://smoothirc.net/qwebchat/ sur le canal `zds-dev`) mais tu peux aussi par MP sur ZdS.

**Comment by ghost** [comment]
J'espère que ça sera vite réglé.

**Comment by Situphen** [comment]
La PR est faite ! #2646

**Comment by Situphen** [comment]
Maintenant on peut fermer !
