### ISSUE TITLE
Limit the amount of SQL queries on main pages

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#17]
J'ai survolé le code de quelques pages clés du site (liste des forums, des sujets d'un forum, etc.), et sauf erreur de ma part, actuellement niveau consommation de ressources on est proche d'un chalutier soviétique à contre vent (&copy; Ths) !

Pas mal de getters s'appuyant sur des méthodes DAO ([exemple](https://github.com/Taluu/ZesteDeSavoir/blob/master/zds/forum/models.py#L79)) sont directement appelés depuis les templates ([exemple](https://github.com/Taluu/ZesteDeSavoir/blob/master/templates/forum/forums_common.part.html#L21)).

À moins qu'un truc m'échappe dans le fonctionnement de Django, il faudra revoir la conception ici, ça sera un des premiers bottlenecks niveau perfs quand y'aura de la fréquentation sur le site.

**Comment by SpaceFox** [comment]
Je me plante peut-être (j'ai jamais vraiment joué avec Django et la dernière fois, c'était la v1.0 ou 1.1...) mais il me semble qu'il existe :
1. Une option (barre de dev ou logs) pour voir les requêtes vraiment générées
2. Une autre option pour activer certaines jointures (peut-être activée par défaut maintenant)

L'un dans l'autre, le template qui appelle directement la couche DAO, ça m'étonne aussi.
C'est peut-être valable dans le concept parce que l'ORM met les caches qui vont bien là où il faut, mais c'est à vérifier.

PS : J'ai les compétences, les outils et la connexion pour lancer un tir de charges sur le bouzin quand on en aura besoin :)
Nul doute que des petits malins vont essayer de jouer avec le site, autant le faire nous d'abord.

**Comment by Coy0te** [comment]
J'imagine aussi que l'ORM de django est au moins aussi bien foutu que JPA de ce point de vue là (et probablement mieux même, rien que de part sa syntaxe). 

Mais de l'idée que je m'en fais à première vue, jointures activées ou pas, et cache activé ou pas, quand au sein d'une boucle tu fais appel à un count, ça lancera au final... une chiée de requêtes count. Multiplie ça par le nombre de visiteurs de la page, et bam, ça fait des Chocapics ! :-*

_(La seule solution viable que je vois, c'est la dénormalisation de certaines tables, avec par exemple l'ajout d'un compteur de topics sur la table forum, et d'un compteur de posts sur la table topic. Ça compliquera un peu les update, mais les select seront bien plus légers.)_

Mais c'est juste une proposition d'amélioration lointaine, je relève ce point dès maintenant pour qu'on ne l'oublie pas plus tard.

**Comment by firm1** [comment]
Je suis d'accord avec Coyote. Les optimisations comme celle là seront utilies. Par contre, on est loin du chalutier soviétique hien. D'après le debuggeur en place, ce n'est clairement pas ce genre de requête qui dérange le serveur, la conso est negligeable.

**Comment by Alex-D** [comment]
Moi de ce que j'ai vu dans mon début d'intégration, ce sont des tests qui devraient être faits en SQL et qui sont faits dans la vue... C'est à la fois lié et non lié au sujet, donc j'en profite pour le dire.

[Exemple ici](https://github.com/Taluu/ZesteDeSavoir/blob/master/templates/home.html#L65)

**Comment by firm1** [comment]
> Moi de ce que j'ai vu dans mon début d'intégration, ce sont des tests qui devraient être faits en SQL et qui sont faits dans la vue... c'est juste dégueulasse.

Ahem. Je pense que tu n'as pas bien compris l'architecture du code.
- Les tests sont fait à la fois dans :
  - Les vues (view.py) : et renvoient des 404 pour le moment quand quelqu'un n'est pas authorisé à consulter la vue
  - Les templates (fichier .html) : et permettent d'afficher certaines chose par rapport à l'état de la situation.

Ce n'est pas degueulasse comme tu dis, ce qui serait dégueulasse serait de faire 4 templates uniquement pour gérer les différents cas de vue sur un topic (invité, membres, staff, etc.) ou encore faire 4 fonction dans view.py pour rendre presque le me même résultat.

**Comment by Alex-D** [comment]
Non, je ne suis pas d'accord.
Il s'agit là de la page d'accueil, tu es donc à la fois sur une vue séparée et un html séparé. Donc, tu te dois de faire le test dans la requête SQL directement... et si l'archi de ton projet ne le permet pas, alors c'est bancale...

Imaginons, nous avons 1000 visiteurs qui passent sur cette home, alors 1000 fois tu vas parcourir TOUS les tutos, pour n'afficher que les tutos en ligne, alors tu vas chercher les derniers tutos et filtrer dans le template uniquement les tutos en ligne... Deux solutions :
- Ton test dans la vue ne sert à rien (et du coup, pas de souchis) ;
- Tu fais un test dans la vue et donc baisse les perfs, et si on met le résultat de la requête en cache, alors à chaque affichage on va se taper le test : pas super.

**Comment by firm1** [comment]
Ah bah sur l’accueil, les derniers tutos renvoyés ne sont que des tutos en ligne. Le test dans le template que tu link pour ainsi dire peut-être enlevé sans souci.

Ma remarque précédente portait plus généralement sur les autres tests que tu pourras trouvé sur les templates. Il sont nécessaires !

**Comment by Taluu** [comment]
Quand il y a vraiment un cas différent, oui, mais dans le cadre de la page d'accueil comme linké par @Alex-D, non. D'ailleurs, même sur les autres pages (je n'ai pas encore trop regardé), de manière général, vaut mieux se baser sur le SQL ou le métier en général, et éviter de faire ce genre de tests dans la vue. Tout comme la vérification de droits en fait.

Elle est utile quand on veut ajouter un "plus" : par exemple, sur un forum, afficher les outils de modé pour un post. Savoir que si l'utilisateur est un modo+ ==> affichage de suppression, edition, ... etc

Mais, c'est pas au template de le faire dans le cas où "j'ai ma liste... j'affiche que si c'est un modo+, sinon j'affiche autre chose". Ça emmêle plus qu'autre chose, et ça demande aussi des perfs de bourrin pour rien.

Je répète, je n'ai pas encore trop eu l'occasion de regarder, je parle donc au sens **général** du terme.

Peace.

**Comment by firm1** [comment]
> vaut mieux se baser sur le SQL ou le métier en général, et éviter de faire ce genre de tests dans la vue.
> Comme je l'ai déjà précisé, tout ce qui se trouve actuellement dans mes fichiers '.html" a été écrit pour que l'intégrateur repère assez rapidement ce dont il aura besoin pour intégrer son code html. Etant donné que je ne connait pas le schémas de travail qu'a décidé d'utiliser Alex-D dans la structure HTML de son design, je trouve ça chiant de coder un fichier propre qui sera de toute façon mis à la poubelle.

Moralité de l'histoire : S'il y'a des remarques pour moi, il faut les faire sur le backend (à savoir les fichier .py ), tous les autres fichiers (html, css, etc.) doivent être fait comme prévu par Alex-D ('fin il me semble)

**Comment by firm1** [comment]
Je passe la serpillière et je ferme aussi ici.
