### ISSUE TITLE
[ZEP-04] Sujets chauds

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1700]
Il faut quelqu'un qui s’attelle assez rapidement au dev back pour sortir 10 "sujets chauds" comme défini dans la [ZEP-04](http://zestedesavoir.com/forums/sujet/669/zep-04-nouvelle-page-daccueil/) pour permettre au front d'avancer sur cette section de la page d'accueil, cf #1699

**Comment by Eskimon** [comment]
Rappel, dans un premier temps les sujets chauds sont les x derniers sujets ayant recu une réponse

La discussion sur les sujets chaud se passe ici : https://zestedesavoir.com/forums/sujet/1213/un-sujet-chaud-quest-ce-que-cest/

**Comment by Eskimon** [comment]
Ping !

Si un dev back est motive pour ca ( @firm1 ?), la premiere iteration est pas tres dure a faire car doit "simplement" renvoyer les x derniers sujets ayant recu une reponse. Ca permettra a la zep-4 d'avancer sans verrou des que les dev front ont un peu de dispo (vacances d'ici fin avril)

**Comment by GerardPaligot** [comment]
https://github.com/sandhose/zds-site/pull/7 ?

**Comment by Eskimon** [comment]
Ah bah nickel ca !

**Comment by gustavi** [comment]
C'est outdated ça non ?

**Comment by GerardPaligot** [comment]
Tout à fait.

**Comment by Axylium** [comment]
Si je peux me permettre, pourquoi donc ? Il me semble que les derniers sujets ont été mis sur la home pour débloquer la ZEP et qu'elle continue, mais qu'il était toujours convenu de mettre les sujets chauds sur la home, quand [ils auront été définit](https://zestedesavoir.com/forums/sujet/1213/un-sujet-chaud-quest-ce-que-cest/), non ? (Bon d'accord, le sujet est sans activité depuis des lustres, mais bon..)

**Comment by GerardPaligot** [comment]
@Florianboux Tout à fait mais tant que ce n'est pas décidé par la communauté, ça ne sert à rien d'avoir un ticket sur GitHub. :)

**Comment by Axylium** [comment]
Ah ok, je comprends mieux ! Mais vu que tu avais répondu oui à @gustavi pour le _outdated_, je pensais que ça voulait dire complètement abandonné.. ^^

**Comment by GerardPaligot** [comment]
Non, mais ça sert à rien d'avoir une issue sur GitHub si la fonctionnalité à implémenter n'est pas définie. Si la communauté se met d'accord sur la question, on pourra créer une nouvelle issue qui viendra expliquer en détail la spec. :)

**Comment by Axylium** [comment]
Oui oui, j'avais compris, ne t'en fais pas. ;)

**Comment by Eskimon** [comment]
Je cale l'étiquette "Zombie" qu'il suffira de virer quand le sujet sera réveillé :)
