### ISSUE TITLE
Outils statistique sur les posts des membres

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1701]
Comme expliqué ici : https://zestedesavoir.com/forums/sujet/1611/bout-de-code-inutile/?page=1#p28186

un bout de code pour generer un graphe des posts/jour est propose au staff. Cet outil genere un fichier image tout le temps, pour tout le monde, a chaque visite de profil. C'est peu productif.

Il faut donc :
- Faire le rendu seulement si un staff visite le profil (back)
- Renvoyer le chemin de l'image si un staff visite le profil (back)
- Placer cette image dans le profil (+ CSS) (front)

**Comment by Eskimon** [comment]
Je m'occuperais des deux premiers points.

**Comment by Alex-D** [comment]
Note relativement important : l'image est en réalité un SVG généré par le back, c'est pour ça qu'on peut la styliser en CSS.

**Comment by firm1** [comment]
C'est fixé
