### ISSUE TITLE
Blanc sur le côté droit de la home

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#1702]
Lorsque vous êtes sur la home, si vous slidez vers la droite, vous pouvez voir du blanc apparaitre (cf. image ci-dessous). Ce bug semble se rencontrer seulement sur la home page.

Ma configuration :
Macbook pro 15 pouces
Navigateur Google Chrome, version 38.0.2125.111

![capture d ecran 2014-11-07 a 14 37 28](https://cloud.githubusercontent.com/assets/1913901/4953647/8b4b33ee-6683-11e4-93b6-ab91f05fbf78.png)

**Comment by firm1** [comment]
J'ai moi aussi le bug sur Windows 7 / Firefox.

Et visiblement viki [l'a aussi](http://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=24#p28222)

**Comment by Axylium** [comment]
J'ai testé sous Firefox (v33.0) et Chromium (v37.0.2062.120) et je n'ai pas ce bug. Le tout sur Ubuntu 14.04.

**Comment by Alex-D** [comment]
Faut rajouter un 

```
width: auto;
```

ici : https://github.com/zestedesavoir/zds-site/blob/dev/assets/scss/_wide.scss#L347

**Comment by Axylium** [comment]
Le changement est a envoyé où ? Branche `dev` ou autre ?

**Comment by Eskimon** [comment]
dev. C'est un bugfix rien de compromettant pour la vie du site et son fonctionnement habituel

**Comment by firm1** [comment]
Fixé
