### ISSUE TITLE
Incohérence dans les couleurs des boutons de validation/confirmation

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1703]
Les boutons de validation/confirmation sur le site sont tous de couleur verte. Par contre les boutons de validation des modales restent de couleur bleue. Ce qui fait que lorsqu'on clique sur le bouton, on voit un effet vert sur sur bouton bleu (cf. l'image). Ce n'est pas cohérent.

![nope](https://cloud.githubusercontent.com/assets/6066015/4953825/a755947e-6685-11e4-8f39-f0d0638fb697.png)

**Comment by Alex-D** [comment]
C'est même étrange qu'il ne soit pas grisé puisqu'il est cliqué. (T'as dû en suer pour faire le screen :D)

J'ai dû oublier le cas des modales dans mon traitement visuel du bug "double clic".

**Comment by Eskimon** [comment]
@Situphen ou @sandhose chaud pour faire ca ? Ca devrait pas prendre trop longtemps j'imagine ? (juste changer la couleur du hover ?)

**Comment by Situphen** [comment]
Je m'en occupe. J'ai réglé le problème des couleurs et je vais me pencher sur celui du gris absent !

**Comment by Situphen** [comment]
En fait, le bouton de confirmation des modales devient bien gris mais pas tout de suite ! Je n'ai pas trouvé le pourquoi du comment, je vais continuer à chercher mais si je trouve pas, tampis...

![modal-submitted-disabled](https://cloud.githubusercontent.com/assets/6664636/5237989/d969feac-78a8-11e4-8293-bd8e2259b562.png)

Par ailleurs, le bouton se met tout de suite en gris sur mobile (Nexus 5 sous Android 5.0 avec FF 33 et Chrome 39) ! @sandhose, une idée ?

**Comment by gustavi** [comment]
Fixé dans #1830 !
