### ISSUE TITLE
Incohérence dans les numéros de pages du forum

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1704]
Si je demande la page 18 (qui n'existe pas) du forum programmation par exemple via l'url `http://zestedesavoir.com/forums/savoirs/programmation/?page=18` je tombe sur la dernière page du forum, qui n'est pas la page 18 mais la page 6.

On devrait renvoyer une 404 car la page 18 n'existe pas.

**Comment by Alex-D** [comment]
Doublon avec #1682
