### ISSUE TITLE
Impossible de poster une image dans une galerie depuis son mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1706]
Le bouton qui permet de rajouter une image dans une gallerie n'existe pas.

**Comment by Alex-D** [comment]
Problème de template. Il manque les classes pour indiquer au JS de rajouter le bloc dans la sidebar mobile.

Dans l'absolu, ça devrait même être un bouton d'action principal, plutôt que de créer une galerie à partir du moment où on est dans une galerie.

**Comment by Eskimon** [comment]
Super, je le cherchais récemment ! Merci @firm1 et @pierre-24 pour la QA :)
