### ISSUE TITLE
Rendre le settings.py plus uniforme et documenté

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1707]
Il y a quelques soucis dans le `settings.py` : 
- parenthèses inutiles https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L192
- import au plein milieu du fichier https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L262
- on a l'utilisation de guillemets simples et de guillemets doubles (ex : https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L275)

C'est relativement trivial mais ce serait bien de nettoyer un peu ce fichier.

Ça manque aussi de commentaires (ex : un lien vers la doc de Haystack [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L250) à la manière des nouveaux fichiers générés par Django.

De plus une documentation de `ZDS_APP` serait une bonne chose https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L273 . Je suis même pour sortir ce fichiers du `settings.py` et l'importer à la manière du `settings_prod.py`.

L'idée serait de partir sur un fichier de conf généré par Django 16 ou 1.7 et de remettre nos infos dedans.

**Comment by SpaceFox** [comment]
Bonne idée, à cumuler avec #1023 je pense.

**Comment by gustavi** [comment]
Je prends, je fais ça dans la soirée ou demain.

**Comment by SpaceFox** [comment]
En fait c'est pas corrigé ici.

**Comment by Eskimon** [comment]
Il reste quoi a faire ici ?

**Comment by SpaceFox** [comment]
Bonne question.

**Comment by artragis** [comment]
J epense qu'on peut fermer ici, non?
