### ISSUE TITLE
Une date trop longue casse le design d'un message du forum sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1709]
Tout est sur le screen.

Galaxy S3/Android/Chrome

![screenshot_2014-11-08-14-41-53](https://cloud.githubusercontent.com/assets/6066015/4964292/c3e7785c-6755-11e4-892a-7ed101ee4b7c.png)

**Comment by gustavi** [comment]
je changerai le `novembre` en `nov` sur mobile (Django le fait très bien)

**Comment by Alex-D** [comment]
C'est déjà reporté quelque part. On peut éventuellement passer le format de la date sur mobile à jj/mm/aa à hh:mm (rajouter `:True` derrière le filtre de la date) et changer selon qu'on est sur mobile ou ordi/tablette.

**Comment by Eskimon** [comment]
Merci @Situphen :)
