### ISSUE TITLE
render_template() n'a pas lieux d'être

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1712]
En essayant de résoudre #1151 je me suis rendu compte qu'une chose assez mauvais a été faire depuis le début du site : `render_template()`. En effet, cette fonction a pour but de remplacer `render()` et ainsi permettre l'ajout de variables présentes dans tous les templates (ex : la version du site). Or ce n'est **pas** la bonne manière, il vaut mieux utiliser un `context_processor`.

Quelques liens pour comprendre ce que c'est : 
- https://docs.djangoproject.com/en/dev/ref/templates/api/#writing-your-own-context-processors
- http://www.formation-django.fr/framework-django/zoom-sur/context-processor.html
- http://www.b-list.org/weblog/2006/jun/14/django-tips-template-context-processors/

Changer cela permet entre autre de corriger #1151.

Je préfère savoir si tout le monde est OK pour changer cela avant de faire quoi que ce soit.

_PS : je ne blâme personne hein, ça se trouve ce morceau de code vient de PDP_

**Comment by SpaceFox** [comment]
Pour l'avoir utilisé sur un projet perso (j'ai découvert ça la semaine dernière et j'ai oublié d'en parler ici, honte !), je confirme que c'est super efficace. Et je confirme que ça vient de PDP.

**Comment by GerardPaligot** [comment]
Question peut-être bête mais pourquoi c'est mieux d'utiliser `context_processor` ?

**Comment by gustavi** [comment]
Parce que si jamais autre chose que la fonction `render_template()` est utilisé (ce qui est le cas des pages 403 et 404) alors les variables sont quand même passées au template.
