### ISSUE TITLE
Réorganiser toute la documentation back

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1713]
La solution décidée dans le [ZDS-meeting 3](https://zestedesavoir.com/forums/sujet/1095/un-zestmeeting/?page=5#p27789) est la suivante : « On dégage toute la doc ce qui est old (GH et forums) sauf le README et le CONTRIBUTING et on centralise dans la doc accessible via readthedoc. »

À faire : 
- Mettre à jour la doc si nécessaire
- Réorganiser la doc sur GH
- Nettoyer les forums (merci @SpaceFox )

**Comment by SpaceFox** [comment]
Attention ça nécessite aussi du ménage côté forums !

Le 8 novembre 2014 20:08, Laville Augustin notifications@github.com a
écrit :

**Comment by firm1** [comment]
On en est ou ici, quelque chose à été entrepris pour ça ?

**Comment by gustavi** [comment]
Non ! Idéalement il faudrait mettre toute la doc à jour concernant notre workflow (excepté le CONTYBUTING.md) et tout mettre dans un tuto. Je crois que c'est ce qui avait été acté.

**Comment by gustavi** [comment]
Je suis dessus (sous la forme d'un tuto sur le ZdS pour le moment comme décidé pendant le ZdS meeting 3). On en reparle au prochain ZdS meeting !

**Comment by firm1** [comment]
> Je suis dessus (sous la forme d'un tuto sur le ZdS pour le moment comme
> décidé pendant le ZdS meeting 3)

Pourquoi sous la forme d'un tuto ? La documentation du code devrait être
disponible dans le dépôts git normalement non ?

firm1
Le 3 déc. 2014 16:37, "Laville Augustin" notifications@github.com a écrit
:

**Comment by gustavi** [comment]
Non, on parle de la documentation qui concerne : 
- le workflow utilisé ici ;
- la QA et co. ;
- etc.

En gros c'est une centralisation de certains topics de ZdS et éventuellements de certaines choses qui trainent ici.

**Comment by firm1** [comment]
Il me semble qu'il y'a un guide du contributeur pour ça en cours de rédaction. Par ailleurs, pour moi l'issue ici concerne plus la doc front-end et des trucs [comme ça](https://github.com/zestedesavoir/zds-site/blob/dev/doc/deploy.md)

**Comment by gustavi** [comment]
Si la personne qui fait ça veut bien me contacter par MP c'est avec plaisir, on pourra éventuellement fusionner notre travail, sachant que j'ai fait pas mal de copié/collé de sujets existants que j'ai ensuite adaptés.

**Comment by Eskimon** [comment]
gustavi, envoi un MP à Arius, il est un peu _lead_ sur ce tuto :)

**Comment by gustavi** [comment]
Fait ! Je fermerai ici quand ce sera terminé.

**Comment by firm1** [comment]
On peut fermer ici, je pense.

**Comment by Situphen** [comment]
Avec la PR qui vient d'être mergée on peut fermer ici ?

**Comment by SpaceFox** [comment]
Oui.
