### ISSUE TITLE
Passer à libgit2

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1714]
Comme décidé dans le [ZDS-meeting 3](https://zestedesavoir.com/forums/sujet/1095/un-zestmeeting/?page=5#p27789) on passe à libgit2. Il faut adapter donc le code en fonction.

**Comment by SpaceFox** [comment]
C'est un bout de la ZEP-12 ça ou non ?

**Comment by GerardPaligot** [comment]
Pas d'après nos [requirements](https://github.com/zestedesavoir/zds-site/blob/dev/requirements.txt#L18).

**Comment by SpaceFox** [comment]
OK, le compte rendu de zds meeting laissait penser le contraire.

**Comment by pierre-24** [comment]
La ZEP-08, en fait :)

**Comment by Situphen** [comment]
[GitPython](https://github.com/gitpython-developers/GitPython) m'a l'air maintenu et est compatible Python 3, le ticket est-il toujours d'actualité ?

**Comment by artragis** [comment]
je clos.
