### ISSUE TITLE
Coder comme il faut « assets/js/find-solved-topics.js »

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1716]
De le but de résoudre la #308 il faudrait nettoyer ce fichier. PING @Alex-D et @sandhose ça semble très simple.

**Comment by Alex-D** [comment]
Il n'y a pas à nettoyer, il faut coder la fonctionnalité.

**Comment by ghost** [comment]
Issue similaire à la #736 ?

**Comment by Eskimon** [comment]
Yep doublon.
