### ISSUE TITLE
Mettre l'icône en background pour .search-more

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1717]
De le but de résoudre la #308 il faudrait nettoyer ce fichier. La ligne en question : https://github.com/zestedesavoir/zds-site/blob/dev/assets/scss/_all-supports.scss#L566

**Comment by Alex-D** [comment]
Attention : il faut gérer le "+" sur ordinateur ET sur mobile (ça change de couleur, il faut donc deux icônes à ajouter dans le sprite).

**Comment by Situphen** [comment]
C'était quoi le but de cette issue ? Ne pas avoir un "+" dans le code HTML ? Car rajouter deux images dans le sprite juste pour un "+", c'est un peu gros ! J'ai une alternative, mettre le "+" dans le CSS, ça vous va ? Ping @gustavi

**Comment by Situphen** [comment]
Up @gustavi !

**Comment by gustavi** [comment]
Aucune idée @Situphen ! Faut que tu demandes à @Alex-D en MP sur ZdS pour savoir pourquoi il a mis un TODO.

**Comment by Eskimon** [comment]
Si j'ai bien suivi on est bon ici. @Situphen tu confirmes que tout le ticket est réglé ?

**Comment by Situphen** [comment]
Bah ma PR améliore le code mais je ne sais pas si ça résout le ticket. Il
faudrait demander à Alex-D !

**Comment by sandhose** [comment]
C'est mergé, je ferme
