### ISSUE TITLE
Nettoyer le fichier « scss/_icons.scss »

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1718]
De le but de résoudre la #308 il faudrait nettoyer ce fichier. C'est une issue 2 en 1 puisqu'il il y a 3 TODO (logique quand tu nous tiens) : 
- https://github.com/zestedesavoir/zds-site/blob/dev/assets/scss/_icons.scss#L12
- https://github.com/zestedesavoir/zds-site/blob/dev/assets/scss/_icons.scss#L114
- https://github.com/zestedesavoir/zds-site/blob/dev/assets/scss/_icons.scss#L297

(les deux dernières étant très liées)

**Comment by Alex-D** [comment]
En gros, il faut :
- faire les icônes manquantes
- balancer ça à l'automatisation pour ressortir tout au format @1x depuis le @2x.

**Comment by SpaceFox** [comment]
C'est corrigé et mergé, encore merci !
