### ISSUE TITLE
Comprendre comment designer l'export dans « tutorial/export.html »

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1719]
De le but de résoudre la #308 il faudrait nettoyer ce fichier. Le TODO en question que je ne comprends pas : https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorial/export.html#L5

PING @Alex-D : tu l'as introduit dans https://github.com/zestedesavoir/zds-site/commit/4417446fde4fac513ec9e04ba2ed41474871ef83, est-ce que c'est corrigé ?

**Comment by Alex-D** [comment]
Nop. Je n'ai jamais regardé la sortie HTML à vrai dire. Mais c'est à faire.

**Comment by cgabard** [comment]
Le todo n'existe plus dans le code.... On ferme ?

**Comment by cgabard** [comment]
(au pire ça devait être réglé par le ticket sur les todo, aucun interet à gardé celui ci)

**Comment by gustavi** [comment]
Ça semble avoir été corrigé.
