### ISSUE TITLE
Ajouter les metadatas pour les utilisateurs

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1720]
De le but de résoudre la #308 il faudrait nettoyer ce fichier et pour cela ajouter les métadonnées à https://github.com/zestedesavoir/zds-site/blob/dev/templates/misc/message_user.html#L13.

**Comment by Alex-D** [comment]
C'est déjà en cours par Eskimon sur la PR #1566

**Comment by firm1** [comment]
Ça c'est fait. On dit merci a @Eskimon
