### ISSUE TITLE
Améliorer les tests can_read_now et can_write_now pour le modèle utilisateur

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1722]
De le but de résoudre la #308 il faudrait nettoyer ce fichier et donc ajouter les test qui manquent.
- https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/tests/tests_models.py#L268
- https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/tests/tests_models.py#L275

**Comment by GerardPaligot** [comment]
Les TODO indiquent qu'il manque des asserts mais quoi comme assert ?

**Comment by gustavi** [comment]
Je n'en ai absolument aucune idée.

**Comment by GerardPaligot** [comment]
Sans information supplémentaire, je suis pour une PR qui retire ces TODO.

**Comment by LudovicDrtt** [comment]
D'après le commit de sha `2fca311cd98039b4eb3e163a6ab1d843342b8083` c'est un caribou prénommé @Eskimon qui a écrit ces todo. Peut-être qu'avec chance il se rappelle ce qui manque.

**Comment by vhf** [comment]
Hésitez pas à regarder le rapport de coverage pour voir quels tests manquent.

**Comment by Anto59290** [comment]
A été mergé ;)

**Comment by pierre-24** [comment]
Ok :)
