### ISSUE TITLE
Le FRONT est cassé sur la recherche

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1723]
Tout est cassé sur http://zestedesavoir.com/rechercher/?q=django par exemple (http://i.imgur.com/2CpO9zv.png). Ça me semble assez urgent.

PING @Alex-D @sandhose

**Comment by Axylium** [comment]
Je dirais un doublon de la #1669.

C'est car ça passe sur deux lignes.

**Comment by gustavi** [comment]
Non je ne pense pas, ça me le fait via un PC.

**Comment by Axylium** [comment]
Oui, mais c'est la même chose, et le même problème. Regarde la #1670 @Alex-D redirige vers la #1669.

**Comment by gustavi** [comment]
À voir si son hotfix corrige ça.

**Comment by Alex-D** [comment]
C'est certain que c'est un doublon de #1669. Le style utilisé est le même. #factorisation !
