### ISSUE TITLE
Versionner les fichiers statiques

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1724]
Comme on a été plusieurs à le voir, lors de la mep 1.2 on avait encore les anciens fichiers statiques en cache. Il faut donc les versionner pour éviter que ça se reproduise.

Je m'en occupe.

**Comment by Situphen** [comment]
Vous entendez quoi par versionner les fichiers statiques ? Mettre "main.v1-3.min.css" au lieu de "main.min.css" ?

**Comment by Eskimon** [comment]
vi

**Comment by gustavi** [comment]
Je suis en train de voir comment on peut faire ça proprement, sachant qu'il faudrait le faire avec Django.

**Comment by Situphen** [comment]
@gustavi : tu auras sûrement à toucher aux outils front donc si tu as besoin d'aide, ping moi ou @sandhose ! ;)

**Comment by gustavi** [comment]
Oui, je regarde les semaines qui arrivent ;)

**Comment by sandhose** [comment]
Il est possible de mettre en place un plugin genre [gulp-rev](https://www.npmjs.com/package/gulp-rev), qui calcule un hash pour chaque fichier, qui le rajoute au nom de fichier (genre `dist/css/main-0abf4.min.css`), et sort l'association pour chaque fichier dans un manifest au format JSON... 

Du fait que c'est le contenu du fichier qui est hashé, et pas juste un string aléatoire permet de garder en cache les ressources qui ont pas changées entre deux générations

Après, faut voir avec Django pour qu'il utilise ce manifest pour mettre le lien vers les bonnes ressources (et ça, je sais pas faire :p )

**Comment by gustavi** [comment]
Le principal souci c'est que c'est pas au front de faire ça. Comme je l'ai dit plus haut je proposerai une solution.

**Comment by SpaceFox** [comment]
Solution fonctionnelle et mergée, je ferme.
