### ISSUE TITLE
Les modales n'ont pas de hauteur dynamique

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1727]
Via [2ohm](http://zestedesavoir.com/membres/voir/2ohm/) sur [le forum](http://zestedesavoir.com/forums/sujet/1638/zone-dedition-limitee-lors-de-la-demande-de-validation/) : 

> Lorsque l'on soumet un tutoriel ou un article, on peut accompagner la soumission d'un message. Lorsque l'on souhaite agrandir la zone d'édition, la fenêtre ne suit pas. (Sur l'image ci-dessous, on voit que la poignée qui permet d'agrandir la zone de texte est passée sous le bouton de confirmation.)

J'ai essayé de reproduire le bug et voici ce que j'ai réussi à obtenir : http://i.imgur.com/pgxB3I1.png

Je cite @sandhose sur IRC à propos de cela : 

> soit, on empêche d'agrandir le textarea, soit faut revoir les modales pour qu'elles aient une taille dynamique (à mon avis, c'est une source de régressions, si on fait ça...)

**Comment by SpaceFox** [comment]
Corrigé et mergé --> Fermé
