### ISSUE TITLE
Pas de liens pour télécharger l'archive d'un tuto récent

### ISSUE THREAD

**Issue by Luthaf** [zestedesavoir/zds-site#1736]
Pour reproduire : créer un nouveau tuto, aller sur la page principale du tuto, et paf, pas de section "Télécharger" ni de lien "Archive". 

Le lien direct (`/tutoriels/telecharger/?tutoriel=<id>`) fonctionne toutefois.

**EDIT (gustavi)** : Une fois la 1.3 en prod vérifier si le bug est toujours présent. Ensuite on peut fermer si c'est bon.

**Comment by gustavi** [comment]
Je n'ai pas ce bug en local mais il est présent sur la prod. Étrange.

**Comment by poulp** [comment]
J'arrive pas à le reproduire en local non plus

**Comment by firm1** [comment]
Le bug a très certainement été fixé par cette PR https://github.com/zestedesavoir/zds-site/pull/1741

**Comment by firm1** [comment]
Je confirme que la PR a corrigé le problème.

**Comment by Luthaf** [comment]
Il semblerai que ce ne soit pas encore résolu sur le site. Je ne trouve toujours pas ce lien =)

**Comment by gustavi** [comment]
@Luthaf on peut avoir plus de précisions sur le(s) tutoriel(s) en question ?

**Comment by Luthaf** [comment]
Alors c'est le cas pour le mien (615/la-ligne-de-commande), et celui sur la botanique de Marypop. Ça ne semble toucher que des tutos créés récemment (moins de un ou deux mois).

**Comment by Eskimon** [comment]
Cette PR aurait-elle corrigée ce problème ? https://github.com/zestedesavoir/zds-site/pull/2371

**Comment by Luthaf** [comment]
Elle est en prod ? Si c'est le cas, je ne vois toujours pas le lien =(

**Comment by Eskimon** [comment]
Elle était :D a cause des evenements recents de lag, on a testé de revenir en v1.6, hors cette modif vient en 1.7...

**Comment by Eskimon** [comment]
On peut fermer ici non ? @Luthaf tu confirmes (car c'est maintenant la bonne version en prod' ) ?

**Comment by Luthaf** [comment]
Alors je suis sur mobile cette semaine, mais je n'ai toujours pas le lien dans le menu à gauche. Il est bien censé être après suppression ?

Sinon je regarderai sur desktop la semaine prochaine !

**Comment by Eskimon** [comment]
OK, petite précision : on parle bien de l'**archive** du tuto. Cette dernière doit être dispo pour un auteur sur son propre contenu mais pas pour un lecteur lambda (connecté ou non)

**Comment by Luthaf** [comment]
Yep, c'est bien à ça que je pense. Sur le tuto en question (ligne de commande), j'ai uniquement ça : 
![capture d ecran 2015-04-25 a 21 26 10](https://cloud.githubusercontent.com/assets/6141587/7334411/d8fcf0c6-eb91-11e4-8f33-4e48de787bfb.png)
Le point 7. étant la fin du sommaire

**Comment by Eskimon** [comment]
Et tu es bien auteur de ce tuto c'est bien ça ?

Tu es sur l'interface hors ligne du tuto ? C'est un tuto déjà publié (je suis presque certain de toutes les réponses mais autant éclaircir :) ) .
Tu pourrais poster le lien du tuto et un staff pourrait ensuite me dire s'il voit le lien de téléchargement ?

**Comment by Luthaf** [comment]
Alors le lien sur lequel je consulte le tuto est le suivant : http://zestedesavoir.com/tutoriels/off/615/la-ligne-de-commande/, donc bien le lien off, pour un tuto non publié. Je suis bien auteur de ce tuto.

**Comment by Luthaf** [comment]
Ah ben tiens, j'y vais pour revérifier aujourd'hui, et voilà que le lien est de retour ! Pour moi et pour l'autre personne qui avait ce problème =)

Problème résolu !
