### ISSUE TITLE
Réorganisation du code SASS

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#1738]
La partie SASS du front doit être réorganisée. Je propose une séparation par module, et par page, pour les styles spécifiques. Ca donnerait un truc comme ça:

```
assets/scss/
 |- style.scss
 |- _variables.scss
 |- mixins/
 |   |- _display-flex.scss
 |   \- _sprite-pos.scss
 |- components/
 |   |- _base.scss
 |   |- _typography.scss
 |   |- _layout.scss
 |   |- _icons.scss 
 |   |- _pygments.scss 
 |   |- _buttons.scss 
 |   |- _modals.scss
 |   |- _editor.scss
 |   |- _nav.scss
 |   |- _header.scss
 |   |- _footer.scss
 |   |- _sidebar.scss
 |   |- _lists.scss
 |   |- _dropdowns.scss
 |   \- _forms.scss
 \- pages/
     |- _home.scss
     |- forum/
     |   |- _topics-list.scss
     |   |- _topic-view.scss
     |   |- _topic-create.scss
     |   \- _topic-edit.scss 
     |- messages/
     |   |- _messages-list.scss
     |   |- _message-view.scss
     |   |- _message-create.scss
     |   \- _message-edit.scss
     |- tutorials/
     |   |- _tutorials-list.scss
     |   |- _tutorial-view.scss
     |   |- _tutorial-create.scss
     |   \- _tutorial-edit.scss
     |- ...
     \- ...
```

Ce qu'il y a dans "scss/pages/" n'est pas encore tout à fait clair, et risque de changer au fur et à mesure que j'avance dans la réorganisation. Je suis en train de la faire en ce moment même

**Comment by firm1** [comment]
Comme ça, à première vue il manque les modules suivants : 
- breadcrumb
- accordion
- pagination
- topbar (différent de dropdown)
- label (ou tag)
- ...

Je ne vois pas non plus le sens de `scss/pages/` car on a pas mal de composant qui se retrouvent a plusieurs niveau.

**Comment by sandhose** [comment]
La topbar, je la pensais dans la nav, et/ou dans le header. A voir

Pour les autres, je vais voir, je sais pas si ça a réellement un sens d'avoir des fichiers de 5 lignes (je pense notamment aux labels), alors qu'ils peuvent peut-être se caser autre part. Je vais voir ça au fur et à mesure

Pour le dossier pages, c'est pour les pages spécifiques. Je pense notamment à la home, mais aussi à la vue grille des galeries... Je pensais mettre la dedans tout ce qui n'est pas réutilisable ; si j'ai mis forum/messages/tutos la dedans, c'était surtout pour montrer le principe, mais je pense bien qu'il n'y aura que peu de style spé pour certaines pages.

**Comment by firm1** [comment]
> Pour les autres, je vais voir, je sais pas si ça a réellement un sens d'avoir des fichiers de 5 lignes (je pense notamment aux labels)

Ah j'ai écrits label, mais je pensais plutôt à alert (pour les erreurs, warning, etc.) qui apparaissent plus haut.

Pour le dossiers pages, oui, on verra, je ne pense pas qu'on aura grand chose dedans. Car même sur la home, pour moi ce sont plutôt de composants "box" qu'on devrait avoir.

**Comment by SpaceFox** [comment]
C'est corrigé et mergé, encore merci !
