### ISSUE TITLE
Utiliser les scripts npm pour gulp et bower

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#1739]
npm depuis la version 2.0 permet de spécifier des arguments aux scripts. Ça nous permet de wrapper bower et gulp entièrement dans le projet, et plus en dépendance globale.

Concrètement, ça permet d'enlever l'étape `npm install -g gulp bower`, qui devait, dans certaines install de node se lancer en root, ce qui posait problème. Du coup, le build gulp se ferait par `npm run-script gulp -- [task]`, au lieu de `gulp [task]` (à noter que si gulp est installé globalement, l'ancienne syntaxe sera toujours dispo).

En gros, les scripts npm sont l'équivalent du `manage.py` django.

La marche à suivre est de rajouter un script `gulp` et un script `bower` dans le `package.json`, pointant sur l'installation locale de bower et de gulp (dans `node_modules/`). Il faut peut-être rajouter `bower` aux dépendances npm dans ce cas la.

**Comment by Eskimon** [comment]
Hop c'est fait !
