### ISSUE TITLE
Rajouter un lien qui explique les licences lors de création d'un tuto/article

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1744]
L'idée c'est de rajouter un lien explicatif de la licence à coté de la zone de choix des licences pour que l'auteur puisse être informé lors de son choix.

L'idéal étant de rajouter dans le settings.py un paramètre pour l'url explicative des licence qui sera visible lors de la création d'un tuto/article.

**Comment by gustavi** [comment]
Il y a le tuto sur les CC où il est possible de remprendre un synthèse pour celles-ci. Je pense qu'un rapide tuto pour servir à cela, où tout est synthétique, quitte à renvoyer vers des liens plus précis.

**Comment by firm1** [comment]
C'est même plus simple que ça. Juste faire comme précisé dans l'image ci-dessous.

![capture](https://cloud.githubusercontent.com/assets/6066015/5027127/d014bfa2-6b2b-11e4-8a39-7f622cd032d4.PNG)

**Comment by gustavi** [comment]
Je m'en occupe.

**Comment by gustavi** [comment]
Un truc comme cela ça va http://i.imgur.com/g7BNBcv.png ?

**Comment by Eskimon** [comment]
Très bien pour moi !
