### ISSUE TITLE
GitPython & PythonMarkdown comme Git submodule

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#175]
Actuellement il y a deux libs que nous utilisons dans une version patché : 
- GitPython
- Python-Markdown

Pour la première je ne sais pas mais pour la seconde, l'intégration des patchs dans la version officiel n'est pas pour tout de suite. Et certaines modifs ne seront jamais acceptés (pour générer le markdown pandoc). Et enfin nous utilisons certaines modifs pas encore releasé dans une version officiel.

Actuellement on a ajouté des scripts pour cloner le dépot officiel, faire un checkout sur la version qui nous interesse et appliquer des patchs. Mais ce process est lourd. Et en plus on a aucune garantie qu'il est bien appliqué lors d'une mise en prod.

Je propose pour alléger le système et d'inclure ces deux projets directement dans notre arbre de sources. Et fain de continuer a pouvoir profiter des améliorations upstream, et ne pas mélanger les commits des deux projets, de les inclures sous forme de submodule (qui sont justement fait pour des cas comme ça).

**Comment by firm1** [comment]
> Je propose pour alléger le système et d'inclure ces deux projets directement dans notre arbre de sources

Je suis d'accord avec cette proposition, j'y ai déjà pensé. Mais je ne sais pas techniquement comment le gérer. Je ne maitrise pas les submodules git et tout le tralala.

**Comment by cgabard** [comment]
> Je ne maitrise pas les submodules git et tout le tralala.

C'est ce qui me fait peur un peu justement, c'est une fonctionnalité avancé de Git, que va t'il se passer avec des personnes qui ne maitrisent pas ?

**Comment by firm1** [comment]
Bon j'ai beaucoup réfléchi ces derniers jours à ce problème. Parmi les scénarios que j'ai exploré, sur le long terme, pour faire court, j'en suis arrivé à la conclusion qu'il faut qu'on publie une lib python-zmarkdown.

**Pourquoi ?**
Parce que, il ne faut pas se le cacher, nous avons fait énormément de modification sur la lib python-markdown de base. Aujourd'hui elle est plutôt destinée à un usage exclusif à zds. Sur le long terme, pour pouvoir l'utiliser au mieux, elle subira encore des modification (pour pandoc notamment), donc j'ai tendance à penser qu'il faudrait faire le fork franc.
L'idée étant de renommer le fork en 'python-zmarkdown', en faire un package propre et le publier sur pypi (afin d'être disponible via pip). Avec le temps, je pense que cette nouvelle bibliothèque servira à d'autres personnes pour des problématiques de gestion de contenu.

Pour ce qui est de la lib Gitpython que j'ai modifié, j'ai fait un PR récemment sur le depot officiel. J'attends une réponse. Mais en soit le patch n'étant pas très conséquent, on a pas besoin de forker cette lib.

Qu'en pensez vous ?

**Comment by SpaceFox** [comment]
Dans l'absolue ça me paraît être une bonne idée.

**Comment by cgabard** [comment]
Pourquoi pas... Mais il va falloir essayer de garder au max la compatibilité avec le projet upstream. Mais on pourrait avec ça libérer le dépots zds des extensions markdowns qui pourront alors être directement intégré dans notre version (ce qui ne fera pas de conflits avec l'existant).

**Comment by cgabard** [comment]
A noter que Python-Markdown est sous licence BSD donc cela ne sera pas problématique

**Comment by firm1** [comment]
Ouaip la licence ne posera pas de conflit avec celle de zds.

> Mais il va falloir essayer de garder au max la compatibilité avec le projet upstream

Tout à fait.

>  Mais on pourrait avec ça libérer le dépots zds des extensions markdowns qui pourront alors être directement intégré dans notre version

C'est le but.

Du coup, faudrait mettre le truc sur le dépot de l'organisation zestedesavoir et faire un package à publier.

@cgabard tu penses pouvoir t'en occuper ?

**Comment by cgabard** [comment]
Oui mais ça veut dire qu'il faut que je puisse gérer un dépot sur l'orga et qu'il va être publique dès que je le fait. Mais oui je vais essayer de m'en occuper cette semaine, j'en profiterais pour régler l'issue #201

**Comment by cgabard** [comment]
@Taluu ou celui qui a créé l'organisation, serait il possible de forker https://github.com/waylan/Python-Markdown et de le renommer en Python-zMarkdown ? 

Je veux bien le renommer moi même si on me donne les droits sur le dépots forké
Je veux bien le forker moi même si on me donne le droit de creer/korker sur l'organisation (pas le cas actuellement)

**Comment by firm1** [comment]
Je n'ai pas les permissions pour le fork moi non plus. Ce serait cool que tout le monde puisse avoir les pleins droits ce l'orga

**Comment by cgabard** [comment]
Ou au moins qu'il y ai un groupe "owners" clair de suffisament de personnes. 

Après moi ça ne me choque pas que l'admisitration soit restreinte à quelques noms seulement.

**Comment by firm1** [comment]
ça y est c'est forké https://github.com/zeste-de-savoir

**Comment by Taluu** [comment]
J'ai créé des groupes pour l'orga pour gérer les droits dessus. Un groupe de contributeur core, dont vous faites tous parti ; un groupe owner (ou y'a que moi pour l'instant ; je peux ajouter encore qqs membres dedans, mais je ne pense pas que mettre tous ceux des contrib soit très judicieux comme l'a dit @cgabard).

J'ai donc forké et donné les droits admin au groupe des dev. Je pense rajouter @firm1 et @cgabard dans le groupe admin de l'orga, vu que ce sont vous deux qui à priori auront le plus besoin de manipuler les orgas, ainsi que le bureau tant qu'a faire

**Comment by firm1** [comment]
Et moi je viens de renommer en python-zmarkdown.

@cgabard a toi de jouer maintenant

**Comment by cgabard** [comment]
Ok, cool merci.

J'ai rajouté SpaceFox dans les dev puisqu'il est en plein dedans. 

Pour l'orga général, dans owner, je rajouterais bien @GerardPaligot qui est un des plus gros contributeur aussi.

**Comment by cgabard** [comment]
Je m'en occuperais cette semaine, pas ce soir.

**Comment by firm1** [comment]
ça ne presse pas t'inquiète. C'est juste pour faire avancer l'issue

**Comment by Taluu** [comment]
Je ne pense pas que parce que @GerardPaligot est un contributeur (aussi prolifique soit-il) qu'il devrait avoir accès à la gestion de l'orga. La gestion du repo, peut-être, mais pas celle de l'orga.

J'en ai profité pour créer le groupe du Bureau, qu'ils aient aussi un accès d'admin à l'orga tant qu'a faire

**Comment by cgabard** [comment]
> J'en ai profité pour créer le groupe du Bureau, qu'ils aient aussi un accès d'admin à l'orga tant qu'a faire

Justement, est ce qu'on les lie ? Il va peut être falloir faire une commission technique dans l'asso et que ce soit ces membres qui est accès au dépot (+ le président à la limite juste pour "assurer" qu'il y ai toujours un représentant)

**Comment by cgabard** [comment]
bref, c'est plus n prob de l'asso ça, tant qu'il y a plusieurs personnes qui ont accès, on est plus safe

**Comment by cgabard** [comment]
Python-markdown est maintenant un fork dédié et est mis a jour via pip.

GitPython utilise la version patché de @firm1 directement dans pip. Cette issue n'a donc plus lieu d'etre, je ferme
