### ISSUE TITLE
Remplacer les dépendances npm dépréciées

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#1750]
Comme l'a dit frim1 [ici](https://github.com/zestedesavoir/zds-site/issues/1529#issuecomment-63075369), les dépendances npm sont dans le rouge ! [![Dependency Status](https://david-dm.org/zestedesavoir/zds-site.svg)](https://david-dm.org/zestedesavoir/zds-site)

Je propose qu'on dépoussière un peu ! Je veux bien essayer de le faire...

**Comment by Situphen** [comment]
Les dépendances dépréciées données par david-dm.org sont :
- gulp-compass --> On ne l'utilise plus donc à la poubelle.
- gulp-load-plugins --> Il nous permet de ne pas avoir à lister toutes les dépendances gulp dans le Gulpfile.js donc, sauf si on trouve un remplaçant, il reste.
- gulp-newer
- gulp-sass --> Il permet de faire SCSS -> CSS donc, sauf remplaçant, il reste
- gulp-uglify --> Sert à pour le JS donc, sauf remplaçant, il reste
- jshint-stylish

``` shell
npm WARN deprecated gulp-rimraf@0.1.1: Use npmjs.org/del instead, see https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md
```

npm nous informe que `gulp-rimraf` est déprécié et qu'il est préférable d'utiliser `del` à la place.

A mon avis, david-dm.org n'est pas très fiable sur les dépendances dépréciées...

**Comment by sandhose** [comment]
Je viens de le faire, il s'agissait juste de mettre à jour certaines dépendances, pas de les remplacer ou quoi que ce soit... Il y a pour ça un utilitaire qui s'appelle `david` (`npm install -g david`), et qui permet d'avoir un truc de ce genre la:

``` shell
[sandhose@sandhose-desktop:~/Projets/zds-site on dev]
% david

Outdated Dependencies

gulp-autoprefixer (package: 0.0.9, latest: 1.0.1)
gulp-flatten (package: 0.0.2, latest: 0.0.4)
gulp-load-plugins (package: ^0.5.1, latest: 0.7.1)
gulp-newer (package: ^0.3.0, latest: 0.4.0)
gulp-imagemin (package: ^1.0.1, latest: 2.0.0)
gulp-uglify (package: ^0.3.0, latest: 1.0.1)
gulp-sass (package: ^0.7.2, latest: 1.1.0)
jshint-stylish (package: ^0.4.0, latest: 1.0.0)

npm install --save gulp-autoprefixer@1.0.1 gulp-flatten@0.0.4 gulp-load-plugins@0.7.1 gulp-newer@0.4.0 gulp-imagemin@2.0.0 gulp-uglify@1.0.1 gulp-sass@1.1.0 jshint-stylish@1.0.0
```

Du coup, suffit de lancer la commande qu'il donne en dessous pour mettre à jour toutes les dépendances...

Après, suffisait de virer `gulp-compass` et `gulp-rimraf` (`npm remove --save gulp-compass gulp-rimraf`), d'installer `del` (`npm install --save del`), et d'adapter [comme je l'ai fait dans ma PR](https://github.com/zestedesavoir/zds-site/pull/1752/files#diff-878989239e07228f7903fde98f450ed9R32)

**Comment by Situphen** [comment]
La PR #1752 a été mergé donc cette issue doit être fermé !
