### ISSUE TITLE
L'alignement des boxs des filtres de la recherches est mauvais

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1755]
Le bug en images : http://i.imgur.com/2mafnc9.png sur https://zestedesavoir.com/rechercher/.

Je l'ai avec sous ArchLinux avec Firefox 33.1 et Chromium 38.0.

EDIT : une PR avait été faite mais abandonnée : https://github.com/zestedesavoir/zds-site/issues/1755. Vous pouvez vous fonder là dessus.

**Comment by arirawr** [comment]
En fixant!

**Comment by ghost** [comment]
Je prends suffit de faire correspondre "height" et "line-height".

**Comment by pierre-24** [comment]
Fix'd
