### ISSUE TITLE
Absence de « Cochez pour dérouler les menus au survol » sur sa page de profil

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1759]
Le bug en image : http://i.imgur.com/ne60ZQs.png. Ça se produit sur plusieurs navigateurs et OS donc ça vient des dernière modifications (PING @firm1 l'internationalisation ?) sachant que c'est pas sur la prod.

**Comment by gustavi** [comment]
Ça semble avoir été résolu tout seul. Quelqu'un confirme ?

**Comment by Eskimon** [comment]
Pourtant j'ai un fix pour ca ici : https://github.com/zestedesavoir/zds-site/pull/1770
