### ISSUE TITLE
Bug design sidebar

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#176]
Firefox 20.

url : preprod.zestedesavoir.com
Problème : les sidebar foutes le camp
Preuve en Image : 
![bug display](https://f.cloud.github.com/assets/6066015/2217824/d8b12ebe-9a22-11e3-94a3-6f7c4be5ccbb.PNG)

**Comment by GerardPaligot** [comment]
Firefox 24.0. Aucun problème.

Tu as des informations complémentaires pour reproduire le bug ?

**Comment by cgabard** [comment]
Pas de soucis non plus sur FF 27

**Comment by ShigeruM** [comment]
Ni sur Chrome 32.

2014-02-20 12:55 GMT+01:00 Christophe Gabard notifications@github.com:

**Comment by firm1** [comment]
> Tu as des informations complémentaires pour reproduire le bug ?

Je sais pas ... installer Firefox 20 ?

Sinon,  c'est une résolution  1280 x 1024

**Comment by SpaceFox** [comment]
> Je sais pas ... installer Firefox 20 ?

Firefox 20 n'est ni la version courante, ni une version ESR. Elle est de
plus raisonnablement ancienne (plus d'un an).
Elle n'a donc pas à être supportée.
Ce bug n'en est donc pas un.

**Comment by firm1** [comment]
> Firefox 20 n'est ni la version courante, ni une version ESR. Elle est de plus raisonnablement ancienne (plus d'un an). Elle n'a donc pas à être supportée. Ce bug n'en est donc pas un.

Je ne sais pas si dans les lycée/écoles/université/... tout le monde est à jour. Donc ça peut être problématique.

D'autant plus que là, je suis sur un pc au taff que je n'ai pas l'habitude d'utiliser. Donc, ça veut dire qu'il y'a des gens qui l'utilisent.

Pour plus de précisions, voici le about:config filtré sur les infos modifiés par l'utilisateur : 

![about](https://f.cloud.github.com/assets/6066015/2218428/53aac6ba-9a2e-11e3-960a-620f267c347b.png)

**Comment by SpaceFox** [comment]
Vue la part de marché annoncée, je persiste dans mon analyse :
http://fr.wikipedia.org/wiki/Mozilla_Firefox#Part_de_march.C3.A9 (et 0.14%
pour cette version seule selon les données sources).

**Comment by firm1** [comment]
> Vue la part de marché annoncée, je persiste dans mon analyse 

Avoue que ça parait tout de même dingue de se dire qu'on ne peut pas supporter un navigateur [sortie en avril 2013](http://fr.wikipedia.org/wiki/Historique_des_sorties_de_Mozilla_Firefox), c'est à dire, qui a juste 10 mois aujourd'hui.

**Comment by SpaceFox** [comment]
Ça me paraît moins dingue que de se faire chier pour 0,14% des utilisateurs
(merci les MAJ forcées).
Ce qui est sans doute moins que les gens qui naviguent sans JS ou les
aveugles.

**Comment by firm1** [comment]
> Ça me paraît moins dingue que de **se faire chier** pour 0,14% des utilisateurs

Je peux comprendre que le site ne soit pas pleinement fonctionnel sous cette version, mais qu'il soit aussi inutilisable, me semble quand même gros.

Après si on suit ta logique, [IE8 est censé être le browser le plus utilisé avec 20,6% de PDM](http://www.clubic.com/navigateur-internet/actualite-609994-navigateur-ie11-10.html), sauf que zds a aussi un affichage foireux sur IE8. On fait quoi dans ce cas ?

**Comment by SpaceFox** [comment]
Si on a effectivement 20% des utilisateurs qui tentent de venir avec IE8,
on doit le supporter, tout à fait. En mode dégradé si besoin, mais
utilisable.

**Comment by firm1** [comment]
Je ne sais pas ce que tu appelles mode dégradé, mais sous IE8 ce sont les box qui foutent le camp d'un peu partout. Pour 20,6% de PDM j'aurai perso exigé un affichage nickel.

**Comment by cgabard** [comment]
On est tous d'accord là dessus je pense, mais ça change legerement de prob que ce bug sur FF 20. Si @Alex-D doit passer du temps, je prefere que ce soit sur les bugs de IE8 que sur celui-ci

**Comment by SpaceFox** [comment]
C'est une histoire de compromis entre réalité des utilisateurs et
complexité technique.
Mon point de vue général sur la question, c'est :
- Navigateur moderne et utilisé : on gère
- Navigateur antique : on s'en coche _sauf_ s'il reste très utilisé.
  Dans ce dernier cas, on fait le minimum pour que le site soit utilisable
  (sauf si bien entendu avoir un affichage parfait ne demande presque aucun
  boulot).

De cette manière, on ne passe du temps que sur les bugs qui impactent
_vraiment_ les clients (et pas 2/3 VIP - nous sommes des VIP sur notre
projet).

Aussi curieux que ça puisse paraître, je range ton FF 20 dans la catégorie
"Antique" : il n'est pas vieux, mais n'est plus sensé être utilisé : les
versions courantes sont mises à jour automatiquement, les gros sites sont
sensés utiliser les versions ESR. Personne n'est sensé encore tourner sur
un FF20 aujourd'hui (et dans les faits c'est le cas).
Le problème de IE est que la v8 est encore officiellement supportée, et ce
jusque avril...

**Comment by Alex-D** [comment]
Pas besoin de faire des discours d'orateurs.

Je connais le bug, il est du à l'utilisation de `display: flex`. Propriété récente mais qui en théorie est supportée, cf http://caniuse.com/#feat=flexbox

J'abandonne Fx20 (puisqu'il est sensé le supporter) mais pour IE8 et 9 il faut visiblement patcher car non supporté, donc je ferais un truc à l'ancienne avec des float dégueulasses.

**Comment by GerardPaligot** [comment]
Je me permets de retirer cette issue de la milestone pour la bêta. Ce n'est pas un bug urgent et ça serait vraiment bien d'éviter de rajouter des issues à cette milestone.

**Comment by Alex-D** [comment]
Je ne pense pas corriger ce bug pour Fx 20. Je ferais des tests un peu plus tard au niveau des navigateurs "ancienne génération"
