### ISSUE TITLE
Ajouter la possibilité de déplacer un chapitre d'un tutoriel d'une partie à une autre

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1762]
Via [Guy](https://zestedesavoir.com/membres/voir/Guy/) sur le [forum](https://zestedesavoir.com/forums/sujet/1691/deplacements-de-chapitres-dans-un-tutoriel-en-redaction/) : 

> Une petite proposition, qui pourrait m'être utile : avoir la possibilité de déplacer un chapitre d'un tutoriel d'une partie à une autre. Cela peut être utile pour les personnes comme moi qui remodèlent souvent le plan de leur tutoriel.
> 
> C'est sincèrement marginalement utile, et c'est plus une proposition à implémenter en dernier recours.
> 
> Merci d'avance.

**Comment by Eskimon** [comment]
A mon avis ca attendra plutot la ZEP 12 non ?

**Comment by gustavi** [comment]
Oui, je l'ai informé que c'est pris en compte mais qu'on attend la ZEP-12 avant de faire quoi que ce soit.

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
Implémenté et globalement testé !

2015-04-16 14:43 GMT+02:00 Eskimon notifications@github.com:

**Comment by pierre-24** [comment]
Y'a encore deux ou trois éceuils, mais on se rapproche d'un truc fonctionnel, artragis a fait un travail magique là dessus.
