### ISSUE TITLE
Décalage sur la pages de tous les forums sur mobile.

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1764]
Le bug en image : http://imgur.com/PgTiGRX

Pour reproduire aller sur cette page et essayer de faire un scroll sur la droite.

Vu avec Firefox mobile 33.1 / Android 4.3.1 (Cyanogenmod 10) / Nexus 4

**Comment by Alex-D** [comment]
Faut : 
- soit jouer sur le `width` avec un `calc` en retirant le padding.
- soit jouer avec `box-sizing`
- soit tenter un `width: auto;` (mais j'ai des doutes)

**Comment by Situphen** [comment]
Je confirme que le bug est bien présent quand la sidebar est cachée (donc que sur les smartphones et les tablettes en mode portrait). Je confirme sur Chrome et Firefox avec Nexus 5 et Nexus 10 sous Android 5.0
