### ISSUE TITLE
Doublons dans les résultats de la recherche

### ISSUE THREAD

**Issue by Nodraak** [zestedesavoir/zds-site#1766]
Lorsque qu'une recherche correspond au titre et au texte d'un topic du forum, ce topic apparaît deux fois dans les résultats.

Exemple avec "croustillante" 
![image](https://cloud.githubusercontent.com/assets/4773741/5067937/d70ebf90-6e48-11e4-8ba7-181ccfb0216f.jpg)

**Comment by firm1** [comment]
c'est parce que le premier lien est le lien du topic et le deuxième lien est le lien du message (vu que ce n'est pas précisé en filtre)

**Comment by Nodraak** [comment]
Justement, il faudrait filtrer les doublons via la `pk` du topic (ou article ou tutoriel)

**Comment by firm1** [comment]
> Justement, il faudrait filtrer les doublons via la pk du topic (ou article ou tutoriel)

C'est un peu plus compliqué que ça.

Si on cherche un mot, il peut se retrouver dans le titre d'un topic, dans un message de la page1, dans un message de la page 6 et dans un message de la page 10.

Actuellement les resultats de la recherchent renvoient un lien pour chaque message. Si on filtre sur le pk, on risque de renvoyer à chaque fois sur le premier post. Et du coup si le topic à 10 pages, le membre risque de ne pas trouver ce qu'il veut.

**Comment by Nodraak** [comment]
Effectivement, j'ai créé l'issue un peu rapidement ...

Je ferme donc.
