### ISSUE TITLE
Ticket sur l’internationalisation

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1767]
Voici un petit ticket pour recenser les soucis et corrections a apporter sur la traduction. Merci de l'utiliser comme reference dans vos futures PR notamment.

**Comment by Eskimon** [comment]
Un souci ici : https://github.com/zestedesavoir/zds-site/blob/dev/templates/base.html#L537

le 'A' n'est pas inclus dans la chaine a traduire https://www.transifex.com/projects/p/zestedesavoir/translate/#en/djangopo-65/37178698?translated=no

**Comment by Eskimon** [comment]
Je propose que "validation" soit traduit en "review", qui est semantiquement correct et adapte je pense.

**Comment by firm1** [comment]
Je profite du ticket pour dire que chaque personne qui modifie, lors du dev, une ligne de texte à traduire dans le code, doit penser à mettre à jour le .po avec cette ligne de commande : `python manage.py makemessages -l en`

**Comment by Eskimon** [comment]
@firm1 dans ce morceau, les blocs trans sont a mon avis pas les bienvenus car ce sont des variables get...

https://github.com/zestedesavoir/zds-site/blob/dev/templates/forum/post/new.html#L45

**Comment by firm1** [comment]
> @firm1 dans ce morceau, les blocs trans sont a mon avis pas les bienvenus car ce sont des variables get...

Tu as totalement raison. :) je crois que la fatigue commencer à prendre le dessus.

**Comment by Eskimon** [comment]
Ici la traduction devrait etre une seule chaine avec les balises https://github.com/zestedesavoir/zds-site/blob/dev/templates/forum/post/new.html#L33

**Comment by Eskimon** [comment]
Le E doit faire parti de la chaine https://github.com/zestedesavoir/zds-site/blob/dev/templates/forum/topic/index.html#L183

Idem ici https://github.com/zestedesavoir/zds-site/blob/dev/templates/gallery/gallery/details.html#L42

Et la c'est le O https://github.com/zestedesavoir/zds-site/blob/dev/templates/member/profile.html#L465

le e : https://github.com/zestedesavoir/zds-site/blob/dev/templates/member/forgot_password/index.html#L7

**Comment by firm1** [comment]
On a un problème aussi ici : https://github.com/zestedesavoir/zds-site/blob/dev/templates/article/view.html#L85 . Le é est en dehors.

Problème là aussi https://github.com/zestedesavoir/zds-site/blob/dev/templates/email/forgot_password/confirm.html#L16 . Le é est sorti

ici aussi :  https://github.com/zestedesavoir/zds-site/blob/dev/templates/pages/alerts.html#L41 : il faut externaliser dans un `with` les variable dans les blocks

**Comment by Eskimon** [comment]
tout les messages au dessus de la PR sont corrigé normalement

**Comment by firm1** [comment]
> tout les messages au dessus de la PR sont corrigé normalement

Possible de synchro avec transifex ?

**Comment by SpaceFox** [comment]
`CommandError: Can't find msgfmt. Make sure you have GNU gettext tools 0.15 or newer installed.`

Visiblement le `update.md` n'a pas été mis à jour.

**Comment by SpaceFox** [comment]
À ajouter au `update.md`: `apt-get install gettext`

**Comment by Eskimon** [comment]
Difficile de blamer qui que ce soit, c'est surement le genre de truc qu'on peut pas forcément se rendre compte car c'est ptet un paquet souvent installé ? (en tout cas quand j'ai commencé à jouer avec l'internationalisation j'ai pas eu ce souci de paquet à installer)

**Comment by SpaceFox** [comment]
C'est pas un blâme, c'est un constat.

**Comment by Eskimon** [comment]
Voila une partie des choses de faites

**Comment by gustavi** [comment]
Encore un petit souci : http://preprod.zestedesavoir.com/forums/sujet/1768/probleme-affichage-lors-de-linscription/

**Comment by Situphen** [comment]
[Ici](https://github.com/zestedesavoir/zds-site/blob/dev/templates/forum/post/new.html#L33) il faut inclure le `<strong>` dans la chaîne car il y a le `</strong>` dedans.

**Comment by firm1** [comment]
On a quasi plus rien ici. Je ferme.
