### ISSUE TITLE
[Forum] : Alertes non affichés sous un post

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#177]
Les alertes de modération ne sont pas affichées dans la vue staff.

**Comment by ShigeruM** [comment]
Et on ne peut pas les résoudre d'ailleurs.

**Comment by Alex-D** [comment]
Est-ce qu'il serait possible que quelqu'un du back affiche ça dans une div moche pour que je puisse savoir ce qu'il faut mettre en forme ?

Merci de préciser dans quelle template ça se trouve =D

**Comment by firm1** [comment]
C'est fixé -> mergée et en prod.

Je ferme en attendant le design final.

**Comment by Alex-D** [comment]
Fait sur ma branche.
