### ISSUE TITLE
La taille de la police est différente entre un texte et une puce sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1774]
Tout est sur l'image ci-dessous.

Chrome/Android.

![screenshot_2014-11-19-17-28-32](https://cloud.githubusercontent.com/assets/6066015/5109490/e11e6b46-7011-11e4-9062-069d8727fac5.png)

**Comment by SpaceFox** [comment]
J'aime beaucoup ton exemple :-°

2014-11-19 17:31 GMT+01:00 firm1 notifications@github.com:

**Comment by gustavi** [comment]
Corrigé et mergé dans #1819 !
