### ISSUE TITLE
Mauvais lien de citation dans les commentaires des tutoriels

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1776]
Lorsqu'on cite une personne dans un tutoriel le lien vers son pseudo est faux.

La ligne qui est foireuse est la suivante : https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/models.py#L476

Il faut rajouter le domaine.

Par la même occasion lorsqu'on est déjà en train de cite quelque chose et qu'on reclique sur un lien « Citer » on a une page 404 car ça ne retourne pas la bonne URL. Ça vient du `?tutorial=<foo>` où `foo` est vide.

Des tests unitaires là dessus ça serait cool aussi.

**Comment by Eskimon** [comment]
J'men charge, mais ca vient pas du modele mais de la vue (qui a pas un comportement aligné avec les autres...)

**Comment by firm1** [comment]
Fixé.

Merci le caribou

**Comment by gustavi** [comment]
Euh @Eskimon le deuxième souci est fixé ? 

> Par la même occasion lorsqu'on est déjà en train de cite quelque chose et qu'on reclique sur un lien « Citer » on a une page 404 car ça ne retourne pas la bonne URL. Ça vient du ?tutorial=<foo> où foo est vide.

**Comment by Eskimon** [comment]
Nan j'avais pas vu ca... Du coup je rouvre !

**Comment by SpaceFox** [comment]
On peut rouvrir un autre ticket avec le problème qui reste ? Parce que si on commence à _sortir_ des issues de la milestone, je n'arriverai jamais à savoir ce qu'il y a dedans !

**Comment by gustavi** [comment]
OK je fais ça.

**Comment by Eskimon** [comment]
Yep désolé tu as bien raison
