### ISSUE TITLE
[suggestion] Ajouter les images lors de l'import/export d'un tutoriel

### ISSUE THREAD

**Issue by Luthaf** [zestedesavoir/zds-site#1780]
Il serait intéressant d'ajouter la galerie liée à un tutoriel lors de l'exportation du tutoriel sous forme d'archive. Et pourquoi pas d'ajouter un support pour l'ajout d'images à la galerie lors de l'import d'une archive dans un tutoriel.

Idéalement, il serait même possible d'ajouter des images hors-ligne, de les référencer dans le code markdown, et que le code markdown soit automatiquement mis à jour pour modifier les liens vers les images.

Edit: Désolé pour l'envoi trop rapide ...

**Comment by Eskimon** [comment]
Le ticket https://github.com/zestedesavoir/zds-site/issues/1617 sera un prerequis.

**Comment by Situphen** [comment]
@pierre-24 @artragis Si je crois [ça](https://zestedesavoir.com/forums/sujet/846/zep-12-refonte-du-principe-des-tutoriels-et-articles/?page=19#p58125) :

> Ce matin, j'ai aussi commité une version expérimentale de l'import d'image en même temps que l'archive des tuto. 

C'est dans la ZEP 12 ?

**Comment by pierre-24** [comment]
Ah, tient, oui ! On as essayé de reproduire ce que ce passait quand on importait des *.tuto

**Comment by artragis** [comment]
du coup on ne fait que la moitié de l'issue puisque l'export ne s'en 
occupe pas.
