### ISSUE TITLE
Références croisées dans les tutoriels

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1783]
**Déplacé ici : https://github.com/zestedesavoir/Python-ZMarkdown/issues/56**

Via [Luthaf](http://zestedesavoir.com/membres/voir/Luthaf/) sur le [forum](http://zestedesavoir.com/forums/sujet/1735/references-croisees-dans-les-tutoriels/?page=1#p30446) : 

> Il serait intéressant d'avoir un système de références croisées à l'intérieur d'un tutoriel : on met un label quelque part, et on peut insérer dans un autre extrait un lien vers ce label.
> 
> Je n'ai pas trop d'avis sur la syntaxe, quelque chose comme !<nom_du_label>, que l'on utilise sous la forme [ma référence](nom_du_label) par exemple. Pour l'implémentation, cela exige d'avoir quelque part une table avec toutes les références, qui est mise à jour d'une manière ou d'une autre.
> 
> Des ancres devrait faire l'affaire pour la sortie HTML, et la traduction en LaTeX est immédiate.

Je reporte ici pour pas qu'on oublie.

**Comment by Axylium** [comment]
J'aurais plus vu ça dans le repo de Python-zMarkdown !

**Comment by gustavi** [comment]
OK je déplace alors ! Désolé !
