### ISSUE TITLE
Le nom du site n'est pas présent dans les mails de MP

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1784]
On a le droit à un : 

> foo vous a envoyé un message privé sur .

lorsqu'on reçoit un mail suite à un nouveau MP. Souci de template, je suis dessus.

**Comment by viki53** [comment]
Hello, ça a pas été mis en prod ? J'ai le même problème (mail reçu ce matin, même chose sur un reçu hier)…

https://www.dropbox.com/s/77n08ttfk17cup9/Capture%20d%27%C3%A9cran%202015-01-05%2010.25.18.png?dl=0

**Comment by Eskimon** [comment]
Vu que la seule PR référençant cette issue est encore ouverte je dirais que c'est normal...

**Comment by viki53** [comment]
Effectivement, j'ai regardé le status de l'issue à la place. Ça passera bientôt ? Parce que c'est quand même handicapant je trouve.

Au passage, si y'avait moyen d'ajouter un lien vers le site en footer de tous les mails ce serait un plus je pense…

**Comment by Eskimon** [comment]
Il faudrait carrement un vrai beau template pour les mails, car la c'est un peu...primaire

**Comment by Situphen** [comment]
Il a encore des problèmes lors de la réponse à un message privé ([voir ce sujet](https://zestedesavoir.com/forums/sujet/3257/notification-de-messages-prives-par-mail/)) !

**Comment by Eskimon** [comment]
Je viens de tester sur la beta et j'ai la grosse impression que tout marche bien...

**Comment by Eskimon** [comment]
tout semble ok maintenant
