### ISSUE TITLE
Mettre du cache sur la version de git (présente sur toutes les pages)

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1789]
Cette issue est prête à être résolue une fois qu'on aura du cache qui fonctionne bien sur la prod.

Le fichier à modifier est le context_processor (une fois ma PR pushée) : http://paste.awesom.eu/dBvY

Ça peut sembler doublon avec d'autres issues mais là c'est vraiment trivial à faire une fois que tout est bon niveau infra.

**Comment by firm1** [comment]
Je trouve que ça fait doublon avec cette issue #417 . Car il ne faut pas mettre de cache que sur la version de git, mais aussi sur les notifications, le nombre de messages, les derniers tutoriels publiés, les catégories, etc. Bref, mettre du cache sur chaque élément qui touche toutes les pages. et donc c'est le propre de l'issue #417

**Comment by gustavi** [comment]
Oui mais là c'est déjà codé et assez urgent parce que c'est assez violent comme c'est fait aujourd'hui ! J'attends de savoir ce qu'on fait pour le cache et je PR directement.

**Comment by firm1** [comment]
> parce que c'est assez violent comme c'est fait aujourd'hui ! 

Il me semble justement que par rapport aux autres éléments de la page c'est assez négligeable. Du coup je ne dirais pas que c'est urgent :)

**Comment by gustavi** [comment]
À voir mais des qu'on a du cache de dispo (autre chose qu'un fichier dans dans /tmp) ça vaut le coup de rajouter ça.

**Comment by Situphen** [comment]
C'est toujours d'actualité ?

Je pense que c'est plutôt du Back que de l'Infra, non ?

**Comment by SpaceFox** [comment]
Edit : Rien  dit.

**Comment by SpaceFox** [comment]
Bon, ça n'apporte rien vu le temps perdu ailleurs. Je ferme.
