### ISSUE TITLE
Faute de frappe sur « Remarques sur cette utilisateur »

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1791]
Via la preprod en 1.3 : 

> `Remarques sur cette utilisateur` à remplacer par `Remarques sur cet utilisateur`
> [elyppire933](http://preprod.zestedesavoir.com/forums/sujet/1742/synthese-de-karma/?page=1#p30613)

Ça concerne https://github.com/zestedesavoir/zds-site/blob/defea39fcc6b0db273a6d96732255bd6a110dce8/templates/member/profile.html#L78

**Comment by Eskimon** [comment]
Je l'ai déjà corrigé ici : https://github.com/zestedesavoir/zds-site/pull/1770

Mais comme personne ne QA mes PR :(
