### ISSUE TITLE
Décalage sur la page d'accueil sur les tablettes mode portrait

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#1792]
Bug trouvé en mode portrait avec Chrome (version 39 je crois) sur la tablette Nexus 10 sous Android 5.0

Pour retrouver le bug, il suffit d'aller sur la page d'accueil et de glisser la page vers la gauche, comme si il y avait un menu caché à droite.

[J'éditerai pour mettre une capture d'écran]

**Comment by Eskimon** [comment]
C'est pareil que ca ? https://github.com/zestedesavoir/zds-site/issues/1702

Si oui alors à fermer et une PR est prête et attend la QA : https://github.com/zestedesavoir/zds-site/pull/1705

**Comment by Situphen** [comment]
Oui, c'est un doublon, désolé !

**Comment by firm1** [comment]
Zouu
