### ISSUE TITLE
Mauvais lien de citation lorsqu'on est déjà en train de citer quelqu'un (articles)

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1794]
Lorsqu'on est déjà en train de cite quelque chose et qu'on reclique sur un lien « Citer » on a une page 404 car ça ne retourne pas la bonne URL. Ça vient du ?article=<foo> où foo est vide.

Ceci concerne les articles

**Comment by Eskimon** [comment]
@gustavi tu peux reproduire le fix de https://github.com/zestedesavoir/zds-site/issues/1787 mais pour les articles ?

**Comment by gustavi** [comment]
Oui je m'en occupe.

**Comment by pierre-24** [comment]
J'allais justement dire que je prenais, mais @firm1  a été plus rapide que moi :o

**Comment by gustavi** [comment]
Fixé dans #1894 !
