### ISSUE TITLE
Check and validate code updates before push !

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#18]
Préface : mon anglais est merdique, le titre est peut-être dégueulasse, mais visiblement la mode est au titrage anglophone.

Je met ce message pour attirer votre attention sur certaines modifications qui ne sont pas cool, comme par exemple [celle-ci](https://github.com/Taluu/ZesteDeSavoir/commit/8cf54f96559b9da306ea9bdbb6f1eba650d3afac) qui m'a fait perdre pas mal de temps, tout simplement parce qu'elle a entre autre exclu le dossier _assets_ des commits à venir. Par ailleurs, ces lignes n'ont pas été commentés, donc à la première lecture, j'ai cru que c'était lié à MacOS, or pas du tout.

Bref, là c'est dralliw, demain ça sera peut-être un autre. Le gitignore est un fichier sensible.

Merci :)

**Comment by firm1** [comment]
Oh, je m'excuse pour la bourde, pour ma défense c'est mon editeur qui gère les ignore, et j'ai fourché sur un bouton.

Sinon, tu as raison oui, mais de toute façon le process va changer une fois que le code se stabilisera un peu a savoir.
- Bosser sur une branche de Dev
- Faire des PR sur la master
- Une PR ne sera validée que si elle est conforme
- lancer le script de déploiement sur le serveur de prod

Merci pour la note tout de même

**Comment by Taluu** [comment]
J'essaierai de faire un guide de contribution quand j'aurai un peu plus de temps pour le faire (d'ici la semaine prochaine probablement ?) via un good old fichier CONTRIBUTING.md

**Comment by dreherch** [comment]
J'ai une question sur le dev web : on tourne avec la master en prod ? On ne tourne pas avec une branche stable ? J'ai l'habitude d'avoir la master avec toutes les dernières modifs fonctionnelles, des branches de dev pour les développements en cours qui cassent certaines fonctionnalités, et les branches stables pour ce qui est en prod (ce qui permet de corriger un bug en prod sans ajouter les nouvelles features pas encore testées (on teste une nouvelle feature sur branche de dev, on teste l'intégration sur master, et on crée une branche stable pour mettre en prod (généralement, on tire la branche quand on est full-feature, et on fait les correctifs dessus, ce qui évite de bloquer master)

**Comment by firm1** [comment]
@JacenSolo : En effet c'est la meilleure façon de tourner. Stable + Master + Dev

**Comment by Taluu** [comment]
En fait, j'avais dans l'idée de faire dans la forme suivante (qui est en gros la même que tu présentes @JacenSolo, même dans le cas du dev web - sisi) :
- Une branche master, stable, qui est la prod, qui accueille éventuellement des hotfixes
- Une branche develop, qui elle accueille la candidate à la prod (une prp en somme) et dans laquelle les hotfixes sont mergés à intervalles réguliers
- Chaque feature sont développées dans des branches propres qui seront mergées dans la develop une fois qu'elles sont considérées comme "stables" et "finies", et sont également régulièrement rebasée par rapport à la develop

**Comment by firm1** [comment]
En gros ça peut marcher à coup de :
- Une branche par feature instable : pour isoler les choses pas prêtes du tout
- Une branche dev : qui sert aux développements et que tous les devs peuvent puller chez eux sans casser des trucs importants.
- Une branche master : qui accueille la préprod (et on peut donc déployer une sorte de preprod.zestedesavoir.com )
- Une branche stable : qui fait office de prod, c'est sur celle là que s'appuie le script de déploiement sur le serveur

L'idée étant que la branche dev reste commune à tous les devs.

**Comment by Taluu** [comment]
Je pense que lorsqu'on fait une branche de dev, autant qu'elle serve pour la preprod avant un merge dans la master (ça demande donc de la freezer à ce moment, sauf hotfixes pour la preprod), plutôt que de gérer plusieurs branches principales.

Parce qu'après, faire un hotfixe sur la branche stable (un truc important qui merde, et qu'on a des travaux en cours sur la branche de dev qu'on veut pas forcément encore merger dans la stable), c'est galère après, car faut la merger dans 3 branches différentes. Surtout que la branche "master" n'évoluerait alors peu ou pas.

En gros, pour la preprod, autant se contenter d'un commit fixé quand on a besoin de tester... Sinon, ça risque de plus nous emmêler qu'autre chose

**Comment by dreherch** [comment]
Normalement, un fix, ça se fait sur master et sur les branches stables actives. Sur les branches de dev, on s'en fiche, elles sont là pour développer une feature donnée, c'est pas grave si il y a des bugs dans le reste. Quand la feature fonctionne, on merge la branche de dev sur master, et on peut même supprimer la branche de dev (juste l'étiquette, pas les commits, qui ne peuvent de toutes façons pas l'être, vu qu'ils précèdent master, de par le merge).

En gros, j'arrive sur l'idée de Willard, avec 
- les branches que je dis "de dev", qui contiennent les features instables
- la branche que je nomme master et que willard nomme dev, qui est normalement fonctionnelle, et qui sert à tous les développeurs (sans forcément avoir le droit de commiter dessus, vu qu'on est en open-source. C'est comme la branche principale de Linux, les gens font leur dev à partir de là, mais seules quelques personnes peuvent réellement commiter dessus)
- La branche stable en prod

La différence, c'est au niveau de la branche master de Willard. Elle est chiante, parce qu'il faut appliquer dessus toutes les commits de la branche dev de willard (ma master). Pour faire une mise en prod, je tire simplement une nouvelle branche stable, je la mets sur le serveur de préprod, et, quand les tests sont finis (et les éventuels bugs fixés), je peux passer en prod cette nouvelle branche. Idéalement, cette phase devrait être assez courte, parce que pendant cette phase, on est obligés d'appliquer les bugs fix sur master, sur la nouvelle stable et possiblement sur l'ancienne stable (qui est en prod). C'est pas grand chose, mais, à force, c'est chiant.

**Comment by Taluu** [comment]
> En gros, j'arrive sur l'idée de Willard, avec 
> - les branches que je dis "de dev", qui contiennent les features instables
> - la branche que je nomme master et que willard nomme dev, qui est normalement fonctionnelle, et qui sert à tous les développeurs (sans forcément avoir le droit de commiter dessus, vu qu'on est en open-source. C'est comme la branche principale de Linux, les gens font leur dev à partir de là, mais seules quelques personnes peuvent réellement commiter dessus)
> - La branche stable en prod

@dralliw  mettait également une branche de pre-prod en plus de la "dev", alors que ça c'est effectivement comment je procède habituellement. En gros on a deux branches "stables actives", sur lesquels sont fait les hotfixes si besoin.

Enfin bref, on est d'accord donc, pas besoin de faire une troisième branche stable juste pour les tests en preprod...

**Comment by firm1** [comment]
Je n'ai pas forcément beaucoup d'xp dans tout ce qui tourne autour de git. Donc, vous pouvez créer les branches, je m'en accommoderais :-P

**Comment by dreherch** [comment]
en m'interdisant d'utiliser le mot master, willard propose
- n branches de dev de feature
- une branche ou on intègre toutes les features finies
- une branche préprod
- une branche prod

De mon coté il y a
- n branches de dev de feature
- une branche où on intègre toutes les features finies
- une branche prod (ou 2, quand on est en train de préparer la prochaine prod)

Ma solution convient à un monde où on fait des livraisons logicielles, genre "dans 2 semaines je livre une version à BMW", et on ne fait de la préprod que quand on sait qu'on va livrer. La solution de willard c'est d'avoir une préprod en continu pour pouvoir passer en prod quand on veut. Ca fait un peu esprit "agile", mais du coup, je ne sais pas comment on décide "ok c'est testé et débuggé, on passe en prod". Je ne suis pas trop adepte des mises en prod au feeling, mais mon approche par releases n'est peut être pas pertinente pour un site web.

**Comment by Taluu** [comment]
Bah le coup de la mise en prod via la création d'une branche "stable", c'est un peu un tag en somme (on tag sur une version sur la branche de dev / master, et on déploie à cet instant t par `git co (tag)`), et la master peut servir de pre-prod continue.

Il y a toujours n branches de dev features (stables, pas stable, qui seront mergées dans master / dev / ponies / whatever une fois stables et vérifiées), et une branche master qui elle suit le dév stable de l'appli. Quand on veut faire  une release, on tag sur une version, et y'aura alors un `git checkout` dessus par la prod...

**Comment by firm1** [comment]
> Bah le coup de la mise en prod via la création d'une branche "stable", c'est un peu un tag en somme

Je précise que l'idée à moyen terme est d'avoir un script automatique sur le serveur qui fait la MEP à partir du repo. Si on se met à jouer avec les tags, faudra faire les MEP à la main, et ça ce serait une mauvaise pratique sur le moyen terme.

L'idée d'avoir une branche qui fait la préprod en continue, permet d'isoler la préprod du dev. Si je dit. Ma version 5 est en préprod vous pouvez la tester. Je dois quand même disposer d'un autre repo pour continuer mon taff pendant que la preprod reste immobile. A la fin de la phase de test en préprod, on passe en prod. C'est lourd comme workflow je sais, mais ça isole bien les taches et c'est pas comme si on fera des MEP tous les jours.

**Comment by Taluu** [comment]
Ben justement, la branche de dev continue, mais on s'en fiche pour la pre-prod, ce sera de toutes manières géré en parallèle... de toutes manières, qui dit pre-prod dit en général freeze de la branche de dev au cas où, d'ou le fait de confondre les deux...

Je me base sur le workflow qui est populaire et a bien donné ses preuves, du [git workflow](http://nvie.com/posts/a-successful-git-branching-model/), auquel on peut même éventuellement plus se pencher vers le [Github flow](http://scottchacon.com/2011/08/31/github-flow.html) qui n'est pas pourri et supprime carrément le concept de la branche de dev principale, qui est le socle des branches de dev features.

Je ne suis absolument pas fan des mises en prod automatiques (trop de magie)... Vaut mieux lancer en prod quand on sait que ça tourne... en sachant pertinemment que la branche "master" est toujours stable. Et quand je dis "toujours stable", c'est **_toujours_ stable**.

Du coup on a toujours une pre-prod qui tourne sur la master, et la prod est juste figée à un état (un commit / arbre en f) issu d'un moment m

**Comment by firm1** [comment]
> Je ne suis absolument pas fan des mises en prod automatiques (trop de magie)
> Je parle de MEP par script auto, pas de MEP auto :-P 

La MEP par script auto, c'est en gros, tu te connectes au serveur, tu lance le script MEP, qui lui va faire le merge adéquat de la branche prod, il va aussi faire les update de la bd en cas de besoin, ainsi que compiler les css si besoin. Il y'a des taches à faire lors de la MEP qu'il vaut mieux éviter de faire faire par des humains.

**Comment by Alex-D** [comment]
Bah si c'est ça le script alors tout le monde est d'accord :)
Il va simplement chercher sur le master pour se mettre à jour, c'est impec'
selon moi.

**Comment by Taluu** [comment]
> La MEP par script auto, c'est en gros, tu te connectes au serveur, tu lance le script MEP, qui lui va faire le merge adéquat de la branche prod, il va aussi faire les update de la bd en cas de besoin, ainsi que compiler les css si besoin. Il y'a des taches à faire lors de la MEP qu'il vaut mieux éviter de faire faire par des humains.

Dans ce cas, pas besoin non plus d'avoir 5 branches stables, une suffit amplement. D'accord il y a un script de déploiement (fabric / whatever), mais suffit de puller la master, éventuellement checkout sur un commit précédent si on veut déployer une version pas tout à fait edge-case, et lancer en effet le script qui lui va faire les différentes opérations.

Il faut garder en tête que la mise en prod sera pas faite par le premier péon qui passe par là, mais par quelqu'un ayant les accès au serveur (et ils ne devraient / doivent pas être nombreux)

**Comment by dreherch** [comment]
http://nvie.com/posts/a-successful-git-branching-model/ J'aime pas ce modèle : la branche master ne sert à rien, autant tagger les release branch. Idéalement, une release c'est juste un tag sur developp (enfin moi j'utilise master pour ça). Dans la réalité, il y a toujours des bugs, et on veut pouvoir corriger un bug sans mettre en prod les features apparues depuis. C'est pour ça qu'on fait des branches stables.

**Comment by Taluu** [comment]
Justement la branche master _est_ la branche stable... toi tu t'en tapes, t'utilises la branche de dev. Dans ton référentiel, la branche master est la branche "stable", et la branche "develop" est la "master". Ca ne change pas grand chose de ton modèle...

**Comment by Alex-D** [comment]
Selon moi, la master est la branche de dev comme @Taluu l'a souligné.
J'ai l'impression que tout le monde est d'accord mais ne se comprend pas :p
Liste à puces :
- master : pour le développement (qui doit rester stable, utilisable) et qui sert pour la pré-prod
- stable : pour la mise en prod
- plein de branches à part qui seront ensuite rebase sur la master pour le dev
