### ISSUE TITLE
[Article/Tuto] [Sécurité] les métadonnées publiées sont modifiables par un auteur

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#180]
Description du bug : Lorsqu'un article ou un tutoriel est en ligne, un auteur peu s'amuser à modifier les métadonnées (image, auteurs, titre, description, licence) étant donné qu'on laisse toujours la possibilité à un auteur de modifier son article/tuto après coup.

Cause : Le problème vient du fait que les versions online et offline diffèrent uniquement par le contenu. Les métadonnées de la version offline et online sont partagées (base de donnée). Pourtant il existe bien un fichier manifest qui stocke les métadonnées de la version offline d'un coté et de la version online de l'autre. Mais il n'est pas utilisé

Piste de résolution : 
- Dissocier la source des métadonnées pour les version on et off en se basant sur le fichier manifest.
- Interdire la modification des métadonnées lorsqu'un article est publié (a voir pour les tutos).

**Comment by GerardPaligot** [comment]
Description supplémentaire pour la piste : Dissocier la source des métadonnées pour les versions on et off en se basant sur le fichier manifest.

Lorsqu'un article est offline, il ne fait que utiliser (en lecture et édition) les méta données disponibles sur le repository git. Cela permettra de versionner les méta données dans le fichier manifest.json. Ce n'est qu'à la publication que les données seront enregistrées en base.

Lorsqu'une version d'un article passe en online, il met à jour ses méta données dans la base de données pour pourvoir accéder à ses informations rapidement. Ces méta données en base sont modifiables qu'à la publication d'une version. Sinon, elles ne sont que consultables.

J'apporte des informations complémentaires parce que j'y avais réfléchis lors de ma refactorisation du module article et que ça me semble vraiment la meilleure piste.

**Comment by firm1** [comment]
Cette issue est fixé. Je ferme donc.
