### ISSUE TITLE
{{ meta_image }} renvoi une mauvaise adresse 

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#1804]
Dans template/base.html est utilisé le tag `{{ meta_image }}` qui doit retourner l'url de l'image liée à la page en cours (par exemple l'icone d'un tuto quand on est sur un tuto). Ce tag est notamment utilisé pour les meta og:image de Facebook. 

Le problème est que l'adresse renvoyée est mauvaise, elle  commence par `http://zdsappserver/`.

**Comment by Eskimon** [comment]
CE truc de meta_image c'est censé venir d'où dans le back ? Car on le voit uniquement dans les templates...

**Comment by Eskimon** [comment]
Ok
