### ISSUE TITLE
L'icône des titres h2 chevauche le texte sur mobile

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1808]
Le probleme est le meme que sur https://github.com/zestedesavoir/zds-site/issues/1644

La correction devrait consister simplement a reproduire le fix https://github.com/zestedesavoir/zds-site/pull/1660 sur les titres h2.

Source : http://preprod.zestedesavoir.com/forums/sujet/1751/chevauchement-icone-tutoriels-et-texte/?page=1#p30686

**Comment by gustavi** [comment]
Corrigé et mergé dans #1818
