### ISSUE TITLE
Aligner le comportement anti-spam pour les tutos

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1809]
Pour les commentaires sur les pages de tutoriels, la zone de texte ne disparait pas pendant les 15 minutes qui suivent l'envoi d'un message, et le bouton "Citer" et aussi présent.

Du coup on a l'impression de pouvoir encore écrire (il n'y a pas le rectangle orange indiquant "Vous venez de poster. Merci de patienter au moins 15 minutes entre deux messages consécutifs afin de limiter le flood.") et quand on veut poster on se prend une erreur 403 en pleine figure !

Il faudrait avoir le comportement de la PR https://github.com/zestedesavoir/zds-site/pull/1664

Source : http://preprod.zestedesavoir.com/forums/sujet/1755/zone-de-texte-des-tutos-apres-post/?page=1#p30685

**Comment by Situphen** [comment]
J'ai fait la PR qui règle le problème. Par contre, c'est pas du front mais du back ! ;)

**Comment by gustavi** [comment]
Corrigé et mergé dans #1816
