### ISSUE TITLE
Rendre le nombre de derniers articles/tutos paramétrés

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1812]
Le nombre de derniers tuto/articles est en dur dans le code. Il serait mieux d'avoir un setting pour ca...

Voici l'endroit a changer :

https://github.com/zestedesavoir/zds-site/blob/1077c3bb04f368e358b95343cefa4877ad424fec/zds/tutorial/models.py#L458
et
https://github.com/zestedesavoir/zds-site/blob/dev/zds/article/models.py#L307

**Comment by firm1** [comment]
Fx'd
