### ISSUE TITLE
Tags mal positionné dans les tutoriels

### ISSUE THREAD

**Issue by Akryum** [zestedesavoir/zds-site#1813]
La liste des tags sur la page d'accueil d'un tutoriel est mal positionnée (sous Firefox) :
![zds - bug tags mal positionnes tuto](https://cloud.githubusercontent.com/assets/2798204/5226661/dc1ebb82-76f1-11e4-8dd1-3694562831ef.png)

Résolu dans l'inspecteur en supprimant la marge négative du haut :
![zds - bug tags mal positionnes tuto - css](https://cloud.githubusercontent.com/assets/2798204/5226666/f5787e06-76f1-11e4-948b-bcfb9f48e492.png)

**Comment by firm1** [comment]
on dirait un doublon de #1685 non ?

**Comment by Eskimon** [comment]
Yep ca y ressemble fortement...

**Comment by gustavi** [comment]
Ouais, doublon. Merci quand même @Akryum !
