### ISSUE TITLE
Interprétation des formules de MathJax dans les formulaires

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#1817]
Rapporté [depuis la preprod](http://preprod.zestedesavoir.com/forums/sujet/1760/interpretation-des-formules-dans-un-formulaire/), le bug est l'interprétation des formules MathJax dans tous les formulaires.

Or, AMHA, MathJax ne devrait pas être autorisé dans les `input` des formulaires (car il cause une déformation du design très importante).

Formulaires où le bug a été testé :
- titres et tags des messages du forum
- pseudo du membre
- site web du membre (pas important)
- signature du membre (la signature peut devenir très grande en taille et avoir des erreurs de MathJax)

Formulaires non testés :
- titre des articles et tutoriels
- titre des messages privés
- message de signalement aux modérateurs

**Comment by Situphen** [comment]
@gustavi : Bien que le bug soit visible, c'est un bug _back_ et non _front_ ! :)

**Comment by Eskimon** [comment]
opinion de Kje

---

Réponse - deux possibilités :
- Soit tu l'interdit dans certaines balises (h1, etc.)
- Plus sûrs, tu ne l'autorise que dans des balises mathjax. En effet, regarde les sources de ce message, le markdown insére les formules dans des balises <mathjax>. Du coup c'est facile de distinguer celle dans le texte des autres.

**Comment by gustavi** [comment]
+1 pour la seconde solution

**Comment by Eskimon** [comment]
Oui je me dis aussi +1 pour la deuxieme

**Comment by pierre-24** [comment]
Ce que vous proposez est bien en théorie, mais inapplicable en pratique, parce que MathJax n'offre pas cette option. On en avait déjà discuté sur #1310 pour une autre raison, et y'avais pas moyen de faire des trucs subtils. Dans tout les cas, pour ce qui concerne MathJax, il faut appeller @aMorison !
