### ISSUE TITLE
Retour sur la milestone 28/02

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#182]
Salut,

Je m'adresse ici pour l'équipe technique afin de discuter du déroulement de la milestone où la deadline a été fixée le 28/02. Pour cette milestone, nous avons réalisé les issues suivantes : #16, #75, #125, #126, #150, #151, #153, #162, #168.

Sur 30 issues, nous en avons réalisé 9. C'est-à-dire 30% de la milestone. Vu les issues réalisées par rapport aux ressources humaines disponibles sur une durée de 2 semaines sur notre temps libre, la progression de la milestone me semble assez logique.

Pour la planification de la prochaine milestone, j'aimerais que nous en parlons ensemble. Qui devrait être disponible ? Et, en fonction des ressources humaines, pour quand planifions la seconde milestone pour une alpha 0.2 (cf. mail envoyé sur la ML de ZdS) ?

**Comment by firm1** [comment]
Mon emploi du temps me dit que je pourrai recommencer à produire du code à partir du mois d'avril. Du coup pour une milestone alpha 0.2 il faudrait voir avec les ressources disponibles.

Je reste toujours dispo pour reviewer des PR (sans les tester forcément).

**Comment by GerardPaligot** [comment]
Personnellement, je termine ma semaine de congé pour commencer mon stage. Je serais donc moins disponible mais toujours focus sur le projet lorsque je rentrerais du taff. Mon focus se fera essentiellement sur la gestion des tutos et sur les retours des membres du groupe.

> Mon emploi du temps me dit que je pourrai recommencer à produire du code à partir du mois d'avril.

Super nouvelle ça ! :)

Les interventions d'@Alex-D (front), @cgabard (markdown), @Coy0te (import tuto) et @Thunderseb (éditeur) sur cette issue sont les bienvenues puisque vous avez des issues dans la précédente milestone.

**Comment by Coy0te** [comment]
Au sujet de mon issue, c'est-à-dire la conversion zCode -> md et l'upload des tutos sur le serveur de ZdS, j'ai pris du retard parce que j'étais pendant un mois en Chine et j'ai déménagé dans la foulée à mon retour en France, et depuis j'ai toujours pas reçu ma p_t_*n de Freebox.....

Les cours convertis en md sont déjà prêts sur mon poste en local, il ne me reste plus qu'à packager les images dans des zip et à uploader ça sur le serveur. Donc, dès que j'ai une connexion internet, c'est terminé ! :)

**Comment by GerardPaligot** [comment]
Super, je peux donc t'inclure dans la prochaine milestone. Ca serait bien qu'@Alex-D et @cgabard prennent le temps de passer sur cette issue. Comme ça, on peut vite s'organiser pour la prochaine milestone.

**Comment by Alex-D** [comment]
Pour ma part, j'ai pris un max de retard sur ce que j'avais prévu, et je m'en excuse (certains diront que je n'ai pas à m'excuser, mais je le fais quand même).

Je travail sur le peu de temps que j'ai sur les maquettes des différentes pages manquantes : la page profil, liste des tutos, liste des articles.

Après ça, la plupart des issues front-end vont fondre d'un coup. Certaines issues front sont en réalité de l'intégration niveau template et du coup j'estime que ça ne me concerne pas directement.

**Comment by GerardPaligot** [comment]
@Alex-D, en estimant large, quelles [tâches front-end](https://github.com/Taluu/ZesteDeSavoir/issues?labels=front-end&milestone=&page=1&state=open) tu estimes pouvoir réaliser pour un sprint de 2 semaines ?

> Pour ma part, j'ai pris un max de retard sur ce que j'avais prévu, et je m'en excuse (certains diront que je n'ai pas à m'excuser, mais je le fais quand même).

Nous faisons tous ce projet sur notre temps libre. Pas besoin de s'excuser.

**Comment by Alex-D** [comment]
Dans les deux prochaines semaines : je ne peux rien estimer, j'ai presque envie de dire : aucun pour être sûr de ne pas dire de connerie.

**Comment by GerardPaligot** [comment]
Très bien, j'inclus pas d'issues front-end dans la prochaine milestone. :) Si quelqu'un pouvait demander à @cgabard de passer, ça serait cool de savoir si j'inclus des issues markdown ou si je repars sur un sprint en solo.

**Comment by cgabard** [comment]
Yo. 

Me concernant, sincèrement, je ne sais pas. La majorité des issues sont soft et rapide a corriger ou le seront si on diagnostic bien le soucis. 

Le prob est que je ne sais pas quand je pourrais m'en occuper, j'ai d'autres problèmes perso plus important qui me mangent mon temps libre actuellement.

Je vais essayer de m'en occuper un de ces jours mais je ne peux rien promettre pour le moment.

**Comment by GerardPaligot** [comment]
Ca marche, je ne compte pas tes issues dans la prochaine milestone aussi alors. Est-ce que tes issues sont bloquantes pour l'export de @Coy0te ?

**Comment by cgabard** [comment]
Je ne pense pas, ce sont des bugs plus que Ajouts de syntaxes.

**Comment by GerardPaligot** [comment]
Très bien. Je vais créer la milestone ce midi.
