### ISSUE TITLE
Le positionnement des catégories des forums ne fonctionne pas

### ISSUE THREAD

**Issue by poulp** [zestedesavoir/zds-site#1822]
Au niveau du back on a bien un attribut _position_ mais aucun tri n'est appliqué lors de la récupération en bdd.

**Comment by gustavi** [comment]
J'ai réussi à fixer ça avec des tonnes de scotch mais faut revoir l'ensemble je pense. http://paste.awesom.eu/gbid

**Comment by SpaceFox** [comment]
Corrigé.
