### ISSUE TITLE
Dans « Tous les forums » le lien vers le dernier message est faux

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1823]
Dans le preprod j'ai http://i.imgur.com/VIO8eIH.png alors que http://i.imgur.com/SJfgOzy.png

**Comment by gustavi** [comment]
Pour moi c'est https://github.com/zestedesavoir/zds-site/blob/67d034ba8395685216df6bae8c328adb0bc53072/zds/forum/models.py#L106 qui fait tout planter.

Cependant je n'arrive pas à reproduire en version de dev.

Je suis en train d'investiguer sur la preprod.

**Comment by gustavi** [comment]
Il faut remplacer `position` par `pubdate` (testé en live et validé sur la preprod). @firm1 pourquoi avoir utilisé `position` ?

**Comment by SpaceFox** [comment]
C'est mergé.

**Comment by firm1** [comment]
Mais le filtre par pubdate est une horreur justement.  On avait des bugs
"uniquement sur mysql" avec ça qu'on ne voyais pas en dev. Ça expliquait
entre autre les doubles posts aléatoires en prod.

J'ai du en oublier un (position) lors du fix. Mais en AUCUN cas il faut
filtrer par pubdate.

firm1

**Comment by SpaceFox** [comment]
@firm1 : https://github.com/zestedesavoir/zds-site/pull/1773#issuecomment-64990471

**Comment by gustavi** [comment]
@firm1 il se trouve que si tu filtres par `position` tu as un résultat faux ! Il vaut mieux quelque chose de pas optimisé que quelque chose de faux.

**Comment by firm1** [comment]
Si le filtre par position ne marche pas, ça signifie que le bug c'est "La
mise à jour du champ position". Et c'est donc ça qu'il faut fixer.

Là tu deplace le problème tout simplement.

firm1
Le 30 nov. 2014 18:35, "Laville Augustin" notifications@github.com a
écrit :

**Comment by SpaceFox** [comment]
J'ai besoin d'un statut clair sur cette issue avant de pouvoir la considérée comme vraiment fermée.
1. Est-ce que c'est corrigé ?
2. Est-ce que ça peut se produire ailleurs ?
3. Est-ce que ça risque de péter les tests que @firm1  a corrigé par ailleurs ?

**Comment by gustavi** [comment]
@firm1 le mieux est de filtrer par `pk` ce qui donne la position absolue par rapport à tous les messages.

**Comment by firm1** [comment]
> @firm1 le mieux est de filtrer par pk ce qui donne la position absolue par rapport à tous les messages.

C'est une mauvaise pratique d'utiliser les id/pk pour le tri.

Le tri par pubdate ici est justifié ... ça n'impactera pas les tests négativement. Il s'agit du last_message d'un forum, pas d'un topic particulier.

**Comment by SpaceFox** [comment]
- Le tri par PK ne fonctionne pas dans le cas général parce que rien ne te dit qu'une PK, qui est un ID purement technique, va être séquentiel.
- Le tri par pubdate _ne fonctionne pas_ parce que la granularité de la date n'est pas assez fine (à la seconde, et il peut y avoir moins d'une seconde entre 2 messages).

Donc soit on part sur le cas particulier de notre PK si on a la garantie qu'elle est séquentielle, soit (et c'est sans doute la bonne solution) on trouve un autre critère de tri.

**Comment by Coy0te** [comment]
Une source pour appuyer le fait que les tris par PK (lorsqu'il s'agit d'id numériques) ne sont pas une bonne pratique ? Dans la plupart des SGBD il s'agit d'un champ indexé par défaut, donc justement parfait pour le tri.

**Comment by firm1** [comment]
@Coyote : 
C'est tout simple. Si tu as 10 messages, les pk vont aller de 1 à 5.

Si tu supprime les messages 2 et 3, les autres pks ne bougents pas. Il te reste donc les messages 1, 4, 5

Maintenant si tu crées un nouvau message, **CERTAINS SGBD** vont te créer le nouveau message avec la pk = 2. Le critère de tri devient faux.

C'est pour ça que c'est une pratique déconseillé en conception de base de donnée.

**Comment by SpaceFox** [comment]
Même au-delà de ça, absolument rien ne te garantit que la PK automatique va te générer des IDs "dans l'ordre". C'est _généralement_ le cas, mais en aucun cas une garantie.

**Comment by firm1** [comment]
oui, voilà.

Ceci dit, ça ne me dérange pas qu'on utilise la date de publication pour ça, plutot que de faire rentrer un nouvel élément de tri qui va ramener son lots de regressions, ainsi que son lot de lenteur (car un index en plus dans la table pour chaque message)

Je rapelle ici qu'on parle de tri sur l'ensemble des messages d'un forum. La granularité a la seconde est déjà amplement suffisante. Si deux messages sont postés à la même seconde, ça ne me parait pas anormal qu'il se battent en duel, car de toute façon l'affichage l'utilisateur n'a que la vision à la seconde.

**Comment by Coy0te** [comment]
Ok. Je conçois que ça puisse être considéré comme une mauvaise pratique,
dans le sens où si un jour il y a modif de la BDD, recréation de séquences,
ou migration vers un SGBD exotique, on s'expose à un risque.

Par contre, pour ce qui est de l'argument du "rien ne te le garantit",
l'auto-increment en MySQL, le serial en pgsql, etc... toutes ces options
sont justement des moyens de garantir qu'un id n'est utilisé qu'une seule
fois, et qu' après suppression il n'y aura pas de recyclage.

Anyway, point eclairci, merci. :-)

**Comment by SpaceFox** [comment]
C'est parce que ta PK automatique vient du SGBD. Dans le framework maison de ma boîte, la PK est générée par l'application (pour une sombre histoire de cache)... et n'est "pas tout à fait" séquentielle. On a eu des problèmes exactement à cause de ça : des devs qui l'ont crue séquentielle, l'ont utilisée pour trier... et ça a tout pété.

**Comment by firm1** [comment]
> la PK est générée par l'application (pour une sombre histoire de cache)

Même pour du cache ... il ne faut jamais générer le PK par l'application. On le faisais il y'a 10 ans parce que les SGBD n'était pas bon, mais aujourd'hui, ça ne doit plus se faire.

Pour revenir au sujet : cette issue, devrait être close. Quelqu'un a une idée de pourquoi elle est encore ouverte ?

**Comment by SpaceFox** [comment]
> Même pour du cache ... il ne faut jamais générer le PK par l'application.
> On le faisais il y'a 10 ans parce que les SGBD n'était pas bon, mais
> aujourd'hui, ça ne doit plus se faire.

D'où le terme "sombre histoire". Et si on pouvait éviter de lancer ici les
trolls du boulot, ce serait sympa.

**Comment by firm1** [comment]
A fermer donc ici ?

**Comment by gustavi** [comment]
Oui.
