### ISSUE TITLE
Lien des notifications pointant vers le premier message du topic au lieu du dernier !

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#1831]
Reporté [ici](http://preprod.zestedesavoir.com/forums/sujet/1758/lien-des-notifications/) par PG06 et confirmé par @Eskimon et moi :

> Lorsqu'on reçoit une notification, celle-ci pointe vers le premier message de la première page du topic, et pas au dernier message non lu, comme c'était le cas avant.

Ce bug est une **régression** et exige un **hotfix** ! Ce bug **n'est pas** corrigé par la PR #1828 !

**Comment by gustavi** [comment]
Est-ce que vous pouvez essayé de reproduire avec la version de dev actuelle ? @Situphen @Eskimon ?

Je n'arrive pas à reproduire.

**Comment by Situphen** [comment]
Je l'ai reproduit en faisant la QA de ta PR #1828 :
- Créer un sujet par user
- Poster une réponse avec admin
- Vérifier que le lien de la barre de notifications est HS avec user

**Comment by gustavi** [comment]
Ma barre de notification est OK, pas le lien dans la liste des topics en revanche.

Je n'aurai pas le temps de fixer ça ce soir.

**Comment by firm1** [comment]
C'est corrigé ici
