### ISSUE TITLE
dependances de development sur requirements.txt

### ISSUE THREAD

**Issue by steenzout** [zestedesavoir/zds-site#1842]
Les dependances de development sont inclues dans le fichier requirements.txt.
Dans les instructions d'installation il est écrit:

```
pip install --upgrade -r requirements.txt
```

donc, l'installation du site implique l'installation des outils de development.

cela ne devrait pas être le cas.

je m'en charge.

**Comment by poulp** [comment]
http://stackoverflow.com/questions/17803829/how-to-customize-a-requirements-txt-for-multiple-environments

C'est vrai que ça serait mieux de structurer les requirements, mais ce genre de modification est à prendre avec des pincettes (modifier en conséquence le script pour Travis, au niveau de la prod/infra si un script est utilisé il faut voir comment ça se passe, etc.)

**Comment by steenzout** [comment]
je suis d'accord mais il faut pas installer plus qu'on a besoin pour avoir le logiciel en production.

travis a passer les testes et j'ai fait ma contribution.
a vous de me dire si vous etes satisfait.

**Comment by Eskimon** [comment]
Je me suis permis de supprimer le cartouche (necessaire seulement pour les Pull Requests).

Sinon bonne observation, j'ai fait quelques retours sur la PR :)

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé
