### ISSUE TITLE
[Article] sha à afficher via l'historique

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#185]
Scénario :
1. Pour un auteur, se rendre sur la version draft de son article.
2. Affichez l'historique des versions.
3. Cliquez sur la version désirée.

Piste pour le bug : La version donnée en paramètre GET ne semble pas être utilisée puisque le système affiche constamment la dernière version de l'article.

**Comment by firm1** [comment]
Cette issue est fixée. je ferme
