### ISSUE TITLE
Partager les ressources sur les réseaux sociaux

### ISSUE THREAD

**Issue by poulp** [zestedesavoir/zds-site#1850]
Permettre le partage des articles/tutoriels sur les réseaux sociaux. On pourrait imaginer des boutons sans mouchard pour optimiser le chargement des pages concernées.

Source : https://zestedesavoir.com/forums/sujet/1749/partager-les-ressources-sur-les-reseaux-sociaux

**Comment by firm1** [comment]
Doublons de #588 ?

**Comment by Eskimon** [comment]
Pas vraiment. 588 a un but editorial tandis que celle-ci serait plutot pour qu'un utilisateur lambda puisse partager un contenu si je ne me trompe pas

**Comment by poulp** [comment]
c'est ça, c'est l'utilisateur lambda qui partage sur le réseau social de son choix

**Comment by Situphen** [comment]
Bon, le code HTML et JS est presque prêt. Par contre, je met où les boutons ? Dans la sidebar ? En haut ? En bas ?

**Comment by poulp** [comment]
Je dirais à la fin de la ressource, ça suit le sens de la lecture.

**Comment by Situphen** [comment]
Si c'est à la fin des articles et des mini-tutos, pour les big-tutos on met à la fin du sommaire ? Ou à la fin de chaque sommaires, parties et extraits ?

**Comment by poulp** [comment]
A la fin de tout les cas possible

**Comment by Eskimon** [comment]
Pourquoi pas tout le temps dans la sidebar ? Dans une rubrique "partager" ?

**Comment by Eskimon** [comment]
par contre pourquoi du js ? Je croyais qu'on se contentait de lien simple qui évitait de charger et tracker quoi que ce soit ?

**Comment by poulp** [comment]
faudrait l'avis d'un ergonome

**Comment by Situphen** [comment]
C'est effectivement plus simple à mettre en place dans la sidebar, mais on perd en visibilité ! **(EDIT :** Je pense que je vais partir sur la sidebar pour l'instant car je ne suis pas designer et on pourra toujours refaire une PR pour changer la position des boutons !**)**

Le code fonctionne sans JS. Le JS est juste là pour ouvrir le lien dans une nouvelle fenêtre à la bonne taille au lieu d'un onglet, ce qui est plus pratique.

**Comment by Eskimon** [comment]
> Le JS est juste là pour ouvrir le lien dans une nouvelle fenêtre à la bonne taille au lieu d'un onglet, ce qui est plus pratique.

J'ai pas compris...

On est bien d'accord que le but est juste de proposer un lien sans tracking, rien de plus ni de moins ? (comme c'est proposé ici https://zestedesavoir.com/forums/sujet/1749/partager-les-ressources-sur-les-reseaux-sociaux/#p30858)

**Comment by Situphen** [comment]
À la fin de [cet article](http://korben.info/le-creator-ci20-un-nouveau-concurrent-du-raspberry-pi.html) il y a des **liens** pour partager vers les réseaux sociaux. Teste avec et sans JS.

Je pense que j'aurai le temps de faire un truc fonctionnel demain après-midi donc si tu ne vois toujours pas de quoi je parle, tu pourras tester de toi-même ! :)

**Comment by firm1** [comment]
Deux choses pour moi ici : 
- d'accord avec @Eskimon pour la sidebar dans une rubrique "partager"
- Pas besoin de JS ici, je pense. On ne dois pas ouvrir dans une fenettre séparée, ça doit rester un lien comme un autre. Le membre aura le choix pour ouvrir dans un nouvel nouvel onglet s'il veut. C'est comme ça que sont tout les liens du site, on reste donc cohérent et on ne change pas les habitude

**Comment by Situphen** [comment]
Sauf que ce ce sont de simple lien. AMHA, l'utilisateur s'attend à ce qu'il y ait le même effet que les boutons officiels. Je trouve que ne pas mettre le code JS est rendre cette fonctionnalité moins utilisable ! Ping DTC @SpaceFox : quel est ton avis ?

**Comment by Situphen** [comment]
J'ai fait un truc potables sur ma branche `fix_1850` (https://github.com/Situphen/zds-site/tree/fix_1850).

Il y a des liens vers Facebook, Twitter, Google+ et vers un email.

Les pages concernées sont pour l'instant les articles et les tutoriels (parties et chapitres inclus) même si je pense qu'il serait bien d'ouvrir ça aux tutoriels BETA.

J'ai laissé le JS pour que vous voyez ce que s'est.

**EDIT :** Vous pouvez maintenant aller voir ma PR #1858 !

**Comment by firm1** [comment]
C'est fixé.

Merci bien.

**Comment by Eskimon** [comment]
Dites, c'est normal qu'on puisse pas faire de meme sur les fofos ?

**Comment by gustavi** [comment]
Ça pourrait être bien mais dans ce cas il faut faire une autre issue.
