### ISSUE TITLE
Notation des messages : voir qui a voté

### ISSUE THREAD

**Issue by poulp** [zestedesavoir/zds-site#1851]
Via [le sondage sur le forum](https://zestedesavoir.com/forums/sujet/1017/systeme-de-notation-des-messages), ou en est la discussion à ce niveau ?

**Comment by Eskimon** [comment]
Il faudrait faire un point sur le fofo qui est plus adapte a une discussion _fonctionnel_ compare a GH.

**Comment by firm1** [comment]
Pour info la spec est [encours de spec sur le forum](http://zestedesavoir.com/forums/sujet/2235/1-1-avec-affichage-des-votants/)

**Comment by Eskimon** [comment]
Bon, je vais ici aussi trancher via ma grande sagesse et son autorité associé en vous dévoilant la spec' finale :

Pour l'aspect graphique :

Les votants seront affichés suite à un clic sur un bouton. Le clic chargera une modale affichant la liste des avatars des votants, chacun souligné par un trait rouge ou vert selon la nature du vote. Les avatars seront clickables pour aller vers le profil du membre. Un hover affiche le pseudo du membre.

Pour l'aspect technique :

Chargement AJAX. Tout les votes précédents une certaine pk de [Comment[Dis]Like](https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/models.py#L265) (rempli dans le settings.py) ne devront pas être affiché -> Règle de respect d'accord tacite antérieur à cette décision. Un bout d'implémentation de la récupération AJAX est faite ici : https://github.com/zestedesavoir/zds-site/pull/2947 .

@SpaceFox j'oublie quelque chose ?

@sandhose tu as un peu de temps pour finir ce que j'avais commencé pour y mettre tes idées qui semblaient convaincre ?

**Comment by SpaceFox** [comment]
Comment on affiche les (dis)like anonymes ? Si on se contente de ne pas les montrer, ça risque d'être incompréhensible pour les utilisateurs. Idéalement, on aurait un truc comme « … et XY votes anonymes ».

**Comment by GerardPaligot** [comment]
On a oublié de fermé ici.
