### ISSUE TITLE
[Article] Aperçu de l'article

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#186]
Scénario :
1. Lancez la procédure de la création d'un article.
2. Renseignez des valeurs pour les champs, ceux obligatoirement minimum.
3. Cliquez sur le bouton "Aperçu" pour voir un aperçu de l'article créé.

Piste pour le bug : Tester quelle bouton submit est utilisé, preview ou answer pour lancer la prévisualisation ou la soumission de l'article.

**Comment by firm1** [comment]
Cette issue est fixée. Je ferme
