### ISSUE TITLE
cyclic imports

### ISSUE THREAD

**Issue by steenzout** [zestedesavoir/zds-site#1860]
a verifier...
1.  zds/gallery/**init**.py Line 1
   Cyclic import (zds.tutorial.models -> zds.utils.models)
2. zds/gallery/**init**.py Line 1
   Cyclic import (zds.tutorial.models -> zds.utils.tutorials)
3. zds/gallery/**init**.py Line 1
   Cyclic import (zds.tutorial.models -> zds.utils.tutorials -> zds.utils.models)

**Comment by gustavi** [comment]
@steenzout tu ne veux pas faire un petit effort pour les issues ? Là on ne comprend rien.

**Comment by steenzout** [comment]
landscape.io a fait un rapport sur la possibilite d'avoir un module A qui fait un import d'un module B et C mais module C fait un import de B donc.

A->B+C
C->B

ca peut donner des problèmes selon l'ordre des imports mais meme si c'est pas un problème, ca c'est un "code smell".
probablement, c'est mieux de faire un refactoring et faire bouger un code sur un autre / nouveau module.

j'ai regarde le code mais j'ai pas pu découvrir le problème.
désolée, mais c'est 3 du matin ici donc si j'aurais le temps demain je ferai un autre commentaire si non voila l'avertissement.

tu peux fermer le issue si tu crois qu'il y a pas un "cyclic import".

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis près d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.
