### ISSUE TITLE
Eviter le rechargement de la page pour les actions d'un topic

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1868]
Comme on peut le remarquer sur le screen ci-dessous, si on clique sur les boutons rouge, la page est rechargée.

L'idée de l'issue est d'utiliser la technologie Ajax pour envoyer les requêtes vers le serveur afin d'éviter les rechargement de page.

![ajax](https://cloud.githubusercontent.com/assets/6066015/5337370/d48ce456-7ec7-11e4-85e4-b1438cd2405f.PNG)

**Comment by SpaceFox** [comment]
\o/

**Comment by firm1** [comment]
Done
