### ISSUE TITLE
Label vide pour une checkbox du profil

### ISSUE THREAD

**Issue by Luthaf** [zestedesavoir/zds-site#1871]
Actuellement, j'ai ça sur mon profil : 

![capture d ecran 2014-12-08 a 23 00 21](https://cloud.githubusercontent.com/assets/6141587/5348328/149fdd0c-7f2f-11e4-8c13-6da032ea1444.png)

Légèrement problématique : dois-je me désinscrire ou m'inscrire à cette option mystère ^-^ ?

Edit : toujours vrai en 1.3.

**Comment by Eskimon** [comment]
Arf j’étais persuade de l'avoir corrige celui-ci...

**Comment by Eskimon** [comment]
Pour qui veut corriger au plus tot, il faudra mettre en unicode la chaine ici : https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/forms.py#L274

**Comment by firm1** [comment]
Corrigé :)
