### ISSUE TITLE
Message de suivi perdu après demande d'aperçu de l'extrait modifié

### ISSUE THREAD

**Issue by AlexRNL** [zestedesavoir/zds-site#1874]
Je viens d'essayer la fonctionnalité qui permet de préciser un message de commit lors de la modification d'un extrait d'un tutoriel (#1133). Ça marche bien, mais lorsqu'on demande un aperçu de son extrait, le contenu du message de suivi est perdu et il faut le réécrire.

Il serait plus pratique que la valeur du champs soit sauvegardé entre les différents aperçus :)

**Comment by pierre-24** [comment]
Je prends :)

**Comment by gustavi** [comment]
Corrigé et mergé dans #1899 !
