### ISSUE TITLE
Lien de telechargement de la doc de solr down

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1875]
Dans la [doc d'install de solr](https://github.com/zestedesavoir/zds-site/blob/f3f4e481c50f195644d77c5f270a27bc2777afa4/doc/install-solr.md), le lien de téléchargement renvoi vers une 404.

**Comment by Eskimon** [comment]
Ils ont change leur systeme de numerotation de versions ? Je trouve pas de 4.9 mais que des 1.4...

http://apache.crihan.fr/lucene/solr/

**Comment by SpaceFox** [comment]
C'est ton lien qui est foireux : la bonne racine du miroir est
http://apache.crihan.fr/dist/lucene/solr/ (le tien ne contient que des
versions ancestrales).

2014-12-09 8:28 GMT+01:00 Eskimon notifications@github.com:

**Comment by firm1** [comment]
C'est fixé. Merci a @DevHugo
