### ISSUE TITLE
Code de template Django affiché dans la page d’inscription

### ISSUE THREAD

**Issue by antoyo** [zestedesavoir/zds-site#1878]
Bonsoir.
Dans la page d’inscription, on voit du code de template Django :

```
{% trans "Les informations demandées dans le formulaire suivant sont nécessaires afin de poursuivre votre inscription" %}.
```

Cela devrait afficher le texte (éventuellement) traduit au lieu du code de template Django.

Merci de corriger cela.

**Comment by firm1** [comment]
Merci pour ton rapport.

Tu m'as l'air de savoir comment lire le code. ça te dirais de t'essayer aux pull requests ?

**Comment by antoyo** [comment]
Oui, bien sûr que ça m’intéresse.
J’ai fait un pull request pour un autre bug cependant, car celui-ci est déjà corrigé en dev.
Désolé d’avoir reporté un bug déjà corrigé.
