### ISSUE TITLE
Code de template Django dans la version texte du courriel MP: Bienvenue sur ZesteDeSavoir

### ISSUE THREAD

**Issue by antoyo** [zestedesavoir/zds-site#1879]
Bonjour.
Il y a du code de template Django dans la version texte du courriel intitulé « zds - MP: Bienvenue sur ZesteDeSavoir » :

`{% trans "Cordialement,
L’équipe" %}`

La version HTML ne contient pas du code de template Django, c’est seulement la version texte du message qui en contient.

Merci de corriger cela.

**Comment by antoyo** [comment]
Je prends.

**Comment by firm1** [comment]
ça c'est fait.

Merci pour la correction rapide.
