### ISSUE TITLE
Mauvais liens dans le MP de bienvenue

### ISSUE THREAD

**Issue by antoyo** [zestedesavoir/zds-site#1880]
Bonsoir.
Le MP de bienvenue contient le début de texte suivant :

> Bonjour antoyo,
> 
> Ton compte a été activé, et tu es donc officiellement membre de la communauté de http://zestedesavoir.com/forums/.
> 
> http://zestedesavoir.com/forums/ est une communauté dont le but est de diffuser des connaissances au plus grand nombre.

Je crois que les liens devraient être http://zestedesavoir.com/ au lieu de http://zestedesavoir.com/forums/forums/, non ?

**Comment by gustavi** [comment]
Oui je confirme que ce n'est pas bon. Ça a du être introduit dans la v1.3.

**Comment by antoyo** [comment]
Je me demandais s’il devrait y avoir des tests pour ce genre de cas (courriels, MPs).
De cette manière ça éviterait les régressions.
Qu’en pensez-vous ?

**Comment by gustavi** [comment]
@antoyo : ça va venir avec la refacto des templates des emails (je bosse dessus rapidement).
