### ISSUE TITLE
Texte manquant dans le courriel de confirmation d’inscription

### ISSUE THREAD

**Issue by antoyo** [zestedesavoir/zds-site#1881]
Bonjour.
Le texte du courriel de confirmation d’inscription débute par :

> Bonjour &lt;strong>antoyo&lt;/strong>,
> 
> Vous vous êtes inscrit sur  et nous vous en remercions.

Il manque du texte après le mot `sur`.
Vous vouliez sans doute dire :

> Vous vous êtes inscrit sur Zeste de Savoir et nous vous en remercions.

Par ailleurs, la version texte contient du code HTML, mais ça a déjà été reporté.

**Comment by gustavi** [comment]
C'est connu et en cours de correction. Merci du retour !

**Comment by gustavi** [comment]
Doublon de #1784
