### ISSUE TITLE
Mauvais lien pour "Ne plus suivre" sur certaines pages

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#1884]
Reporté ici : https://zestedesavoir.com/forums/sujet/1888/erreur-404-lorsque-lon-clique-sur-ne-plus-suivre/?page=1#p33536

Le lien "Ne plus suivre" mène vers "/forums/sujet/editer/" ce qui donne une 404. Ce bug est présent sur les pages du type "Forums" et "Forums - Communauté" mais pas sur les pages du type "Forums - Communauté - Bugs et Suggestions".

**Comment by SpaceFox** [comment]
Corrigé + mergé = fermé
