### ISSUE TITLE
Re-générer le fichier de traduction en production

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#1885]
Depuis que le code est prêt à être traduit, on voit pas mal de "bugs" comme [celui-ci](https://zestedesavoir.com/forums/sujet/1881/probleme-avec-laffichage-du-message/?page=1#p33352). C'est pourquoi il serait bien re-générer le fichier de traduction à chaque MEP et de le faire pour la version actuelle en prod (soit en ligne de commande, soit via un hotfix ou par la version v1.3b) !

**Comment by SpaceFox** [comment]
Je ne comprends pas. Pour moi ce fichier était sensé être régénéré à chaque
fois qu'on touche une chaîne de caractères.

Quelles sont les bonnes pratiques ?
Quels sont les impacts de forcer les générations à chaque MEP ?

**Comment by Situphen** [comment]
Bah normalement quand quelqu'un touche une chaîne, il doit re-générer le
fichier de traduction. Apparemment tout le monde ne fait pas ça donc il
faudrait le re-générer pour éviter des erreurs d'affichage. Je ne crois pas
qu'il y ait de gros d'impacts si l'on fait ça lors de la MEP. Ping @firm1

**Comment by firm1** [comment]
Bon pour faire court (je detaille quand j'ai un clavier) :
- non Stipuphen la génération du fichier en prod est déjà automatique quand on MEP (cf. Script de mep)
- quand bien même ce n'était pas fait, le fichier .po n'est pas utilisé dans notre cas car on a qu'une langue
- au zest meeting on s' est dit (cf. le compte rendu) que le fichiet ne sera plus généré par les devs, uniquement lors des releases.

En gros, tu te trompe de solution.  Le problème qu'on a ce sont les chaines qui bugs. Mais la solution c'est de passer la 1.4 pour les correctifs. 

Voilà, je suis ptet pas clair, mais j'ai plus de batterie :(

**Comment by Situphen** [comment]
Je n'ai bien compris mais je vous fait confiance ! ;)

**Comment by SpaceFox** [comment]
Normalement c'est OK avec la v1.4, du coup il faut juste vérifier que c'est bon ?

**Comment by firm1** [comment]
Je confirme qu'ici il n'y a rien a faire. Je ferme donc.
