### ISSUE TITLE
Dépassement des -1/+1 avec les longues signatures

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1889]
Reporté sur via [forum](https://zestedesavoir.com/forums/sujet/1905/signatures-et-1/).

Une image vaut mieux que toutes les explications du monde : http://i.imgur.com/qww9t9a.png

Ça le fait sous Firefox, ailleurs surement aussi.

**Comment by Situphen** [comment]
La PR #1890 a été mergé donc cette issue doit être fermé !
