### ISSUE TITLE
Supprimer ou corriger ce qui est inutile sur les 500

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1893]
En gros ce qui est inutile ou foireux sur les 500 qui sont des pages fixes : 
- version/nom du site absent
- boutons connexion/Identification

**Comment by ghost** [comment]
Comment peut-on générer une erreur 500 en local, pour reproduire la même situation pour corriger ce problème ?

**Comment by gustavi** [comment]
Je crois que c'est fixé ça ? PING @SpaceFox ?

**Comment by Eskimon** [comment]
Ici non ? https://github.com/zestedesavoir/zds-site/pull/2236

**Comment by SpaceFox** [comment]
Oui, en fait on a fait un doublon et on l'a corrigé. Donc ici c'est bon.
