### ISSUE TITLE
Changement de licence impossible en local

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1896]
Comment reproduire le bug : 
- Créer un tuto
- Changer la licence pour n'importe quoi d'autre que la licence par défaut "tout droit réservé".
- Tenter d'éditer le tuto et ce manger une erreur `index out of range`

À priori, ça n'arrive que sur la version de dev et pas sur la prod. À priori, j'ai déjà la solution.

**Comment by gustavi** [comment]
Corrigé dans #1896
