### ISSUE TITLE
[proposition] "une version plus récente existe"

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1898]
Lorsqu'on est plusieurs sur un tutoriel/article, il arrive qu'on édite le même texte. Actuellement, un mécanisme de "protection" indique qu'une version plus récente a été écrite, tout en affichant le texte de cette nouvelle version. Autrement dit, l'ancien texte est écrasé, sans qu'il ne soit possible de le récupérer (bien entendu, c'est toujours possible avec le bouton "précédent" sur les navigos moderne). 

Ne serait-il pas plus intelligent de proposer l'ancien ET le nouveau texte ?

**Comment by gustavi** [comment]
Pourquoi pas. @pierre-24 c'est mieux de faire ce genre de proposition sur le forum ;)

**Comment by pierre-24** [comment]
Fait : https://zestedesavoir.com/forums/sujet/1922/une-version-plus-recente-existe/ :)

**Comment by Eskimon** [comment]
Est-ce que la ZEP-12 touche a ca ou pas ?

**Comment by pierre-24** [comment]
Non, c'est une évolution ;)

**Comment by Arnaud-D** [comment]
Doublon de #6643
