### ISSUE TITLE
ZdS need more tests

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#19]
Comme toute application qui a pour but d'être opensourcée, il faut un maximum de tests pour toutes les contrôles et vues existantes.

La bonne pratique voudrait que ceux qui font des tests, ne soient pas ceux qui ont le nez dans le développement. Je vais éviter de faire l'apologie de l'utilité des tests dans une application/site, mais j'encourage bon nombre de personnes à rédiger des tests pour ZdS.

Pour éviter que mise à jour ne crée de la régression, le développeur consciencieux (à terme ça sera l'équipe de validation du repo) lancera l'ensemble des tests pour s'assurer qu'aucun feature n'est cassée.

Il y'a trois niveaux de contributions à cette issue : 
- Faire une liste (en langage naturel) détaillé (non exhaustive) des tests à rédiger, quelqu'un se chargera de les rédiger.
- Rédiger les tests simple (test de création, test de maj, test de suppression en cascade)
- Rédiger des tests complexes (import d'un tuto, inscription d'un membre)

Je commence avec une liste (non exhaustive) de quelques tests (je ferais une MAJ avec la liste des autres) : 
## Liste des Tests
- Inscription d'un membre
  - un membre qui a saisi toutes les informations obligatoire doit pouvoir être présent en base, avec un profil.
  - un membre dont l'email ou le pseudo est déjà présent en base ne doit pas pouvoir s'inscrire
  - un membre déjà connecté de dois pas avoir accès à la vue d'inscription
  - ...
- Connexion d'un utilisateur
  - un membre dont le login est présent en base et le mot de passe correct doit pouvoir se connecter
  - un membre dont le login n'existe pas en base ne dois pas pouvoir se connecter
  - un membre n'ayant pas de profil (table profil) ne doit pas pouvoir se connecter
  - ...
- Création d'un topic
  - un invité ne doit pas pouvoir créer un topic
  - un membre qui saisi toutes les infos obligatoires doit pouvoir créer son topic
  - un topic crée doit être lié à son premier post
  - la position du premier post doit être égale à 1
  - ...
## Documentation sur les tests django : 
- [Doc Officielle](https://docs.djangoproject.com/en/1.3/topics/testing/)
- [Tuto OC](http://fr.openclassrooms.com/informatique/cours/developpez-votre-site-web-avec-le-framework-django/les-tests-unitaires-3)

**Comment by GerardPaligot** [comment]
> La bonne pratique voudrait que ceux qui font des tests, ne soient pas ceux qui ont le nez dans le développement. Je vais éviter de faire l'apologie de l'utilité des tests dans une application/site, mais j'encourage bon nombre de personnes à rédiger des tests pour ZdS.

J'ai regardé vite fait le code. Effectivement, j'ai été étonné de ne pas voir de tests. Mais pour toi, la bonne pratique, serait de déléguer les tests à des personnes externes (entendre par là, des personnes qui n'ont pas développées les fonctionnalités concernées) ? Pour moi, un développeur se charge d'une fonctionnalité dans son ensemble. Elle passe à l'état "fini" lorsqu'il l'a développée et lui-même testée.

J'ai aucune objection à laisser le développement des tests à d'autres mais je trouve ça quand même un peu bizarre.

**Comment by dreherch** [comment]
Les tests unitaires sont à faire par le développeur, ça permet d'assurer une bonne couverture de tests vu que le test est du coup fait en boite blanche, par contre, pour les tests d'intégration, ça me semble être une bonne pratique de les faire écrire par un tiers, en boite noire,

**Comment by firm1** [comment]
Il y'a une notion de vocabulaire à préciser ici. Ce que j'entends quand vous parlez de tiers (c'est pour ça que je n'utilise pas ce vocabulaire), c'est celui qui n'y connait rien au code de ZdS.

Et quand je parle de celui qui n'a pas le nez dans le code, c'est celui, qui connaît plus ou moins le code, sa structure, mais qui n'a pas codé la fonctionnalité à tester. Pour la simple raison que celui qui code rédigera des tests biaisée par sa vision et ne sera peut-etre pas exhaustif.

Pour l'exemple, quelqu'un fait un commit qui concerne la mise en place du déplacement d'un topic vers un autre forum. Il s'agit d'un traitement fonctionnel et donc le dev qui connait la structure de code est à même de rédiger les tests en se disant. Je crée un topic dans un forum, j'essaye de deplacer le topic vers un autre forum, je vérifie que le topic n'existe plus dans l'ancien forum, et je vérifie qu'il existe désormais dans le nouveau forum.

C'est comme ça que je le vois.

**Comment by SpaceFox** [comment]
Je suis assez d'accord avec Jacen.
En fait, de mon point de vue on a idéalement besoin de trois séries de tests :
1. Des tests unitaires, écrits et lancés par le développeur.
   Ils permettent de vérifier que le code fait bien ce pourquoi il est prévu (vérification technique).
   Ils sont faits avec le moteur de tests de Django.
   Le test est lancé au développement et aux modifications de la portion de code qu'il vérifie.
2. Des tests d'intégration : quand on merge une nouvelle fonctionnalité / corrige un bug, quelqu'un **d'autre que le développeur** teste cette fonctionnalité.
   Ils permettent de voir si la fonctionnalité marche bien comme prévu (vérification fonctionnelle). Ils permettent aussi de détecter d'éventuelles erreurs d'interface, etc.
   Ils sont faits avec le navigateur (ou toute autre interface utilisée par la fonctionnalité, par exemple la ligne de commande pour un import de tuto en CLI.
   Le test est lancé au moment du merge sur la branche principale.
3. Des tests de non-régression, écrits par qui veut et lancés automatiquement.
   Ils permettent de vérifier que les fonctionnalités déjà développées fonctionnent toujours comme prévu (vérification fonctionnelle)Ils sont fait avec un outil prévu à cet effet, par exemple Selenium (robot de pilotage de navigateur).
   Le test est lancé avant la MEP.
   Idéalement, ces tests sont basés sur les IDs dans le code HTML (résistance aux modifications d'intégration), et ne peuvent pas être automatisés tant qu'on a pas une intégration FO à peu près stable, puisque toute modification dans l'intégration est susceptible de faire planter ces tests.

Par ordre de priorité et d'importance pour la qualité finale, je dirais 2 - 3 - 1 (en supposant de bons développeurs).

**Comment by firm1** [comment]
@SpaceFox : 
Le fait est que le moteur de django te permet de faire des tests sur à peu près tous et donc de les automatiser.

Si je prend ton découpage, le 1 représente environ 40% des tests codé, le 2 représente 30% des tests écrits et 30% des tests IHM, et le 3 en fait c'est un mix du 1 et du 2.

**Comment by SpaceFox** [comment]
Je ne suis complètement pas d'accord.

D'une part parce que si j'en crois la doc, le moteur de tests de Django ne permet pas de faire les TNR (point 3) correctement notamment à cause de ce point :
_"Use in-browser frameworks such as Twill and Selenium to test rendered HTML and the behavior of Web pages, namely JavaScript functionality."_

D'autre part parce que le point 3 (TNR) n'est _en aucun cas_ un mix entre des tests unitaires et des tests d'intégration.
Le but des tests de non-régression, c'est de vérifier _fonctionnellement_ (donc pas comme un test unitaire) le fonctionnement d'une partie de l'application _dont on a déjà validé le fonctionnement_ (donc pas comme un test d'intégration).

Enfin parce que de mon point de vue, les tests d'intégration (point 2) doivent être faits par des humains. L'apport de l'humain est justement tout l'intérêt de ce type de test.

**Comment by firm1** [comment]
Les TNR se déclinent en TNR techniques et TNR fonctionnels.

Les TNR techniques sont automatisés, les TNR fonctionnels peuvent être tous faits par les humains, mais étant donné qu'il faut limiter les tests fait par les humains, on automatise au maximum les tests fonctionnels. D'où ma répartition.

Si je me réfère encore une fois à la fonctionnalité présentée plus haut: "déplacement d'un topic". Elle doit être testée  à chaque correction/évolution et pour éviter qu'un humain se coltine ce test à chaque fois, on l'automatise et voila.

**Comment by geoffreyc** [comment]
Faut aussi le voir comme ca: L'humain est paresseux, et même avec la
meilleurs des volontés, au final tout les tests ne seront pas fait a chaque
fois " Le changement X n'aurait en théorie pas d’influence sur la partie Y
du site, pas la peine ne re-tester manuellement"... Donc autant avoir le
plus de test auto possible, complétés par des tests humains si besoin.

2013/12/13 dralliw notifications@github.com

**Comment by SpaceFox** [comment]
Les TNR fonctionnels doivent être aussi automatisés, c'est pour ça qu'on a des outils de pilotage de clients, comme Selenium. Auquel on peut tout à fait faire manger des trucs du style "déplacer un topic".

En fait pour moi, TNR = fonctionnel. Je ne vois pas bien ce que tu entends pas TNR technique (j'ai l'impression que ça rejoint les tests unitaires ?)

**Comment by geoffreyc** [comment]
Out of interest (j'ai jamais utilisé ce genre de logiciels de "pilotage de
clients"): Comment tu détermines si un test est successful ou pas?

2013/12/13 SpaceFox notifications@github.com

**Comment by SpaceFox** [comment]
Comme avec tous les autres logiciels de tests : tu mets des assertions.
Typiquement, c'est "la page telle nom", "l'élément HTML d'ID XYZ a la valeur ABCD", etc.

Par exemple,  tu peux faire un test qui prends un topic de nom X, le déplace de la catégorie A vers la catégorie B, puis va vérifier qu'il n'est plus dans la catégorie A et est bien dans la catégorie B (pour bien faire, il faut aussi vérifier les conditions initiales).

L'énorme avantage c'est que tu testes directement ce que va utiliser le client. Donc si y'a un JS foireux, un bouton qui manque, ... le test va planter.

**Comment by Taluu** [comment]
A mon taff, on fait la chose suivante ; 
- Les tests sont rédigés par les développeurs qui font leur feature (surtout les unitaires, je suis cependant d'accord que pour les tests fonctionnels, on devrait le faire par quelqu'un d'autre en mode boite noire)
- 2 types de tests : les tests backend (marche par api, ce qui n'est pas le cas ici donc osef) et tests frontend
- Chaque type de tests ont deux sous-tests : les tests unitaires et fonctionnels

Donc niveau backend, on fait les tests unitaires, et front, ce serait le point de vue "client final". Il existe de bons outils pour ça dans d'autre langage (Cucumber en Ruby, qui a lancé ce genre de tests fonctionnels, plus souvent catégorisés en "test d'acceptation", et en PHP je pense par exemple à Behat qui est grosso merdo un portage de Cucumber), je pense qu'on peut aisément en trouver un équivalent en Python. Quand je dis "le client final peut comprendre ce que fait l'app", c'est parce que ce genre de tests se rédigent sous la forme suivante :

``` cucumber
Feature: Post a message on ZdS' forums

Scenario: Reply to a topic
  Given I am connected as "test" with "<passwd>" on "/forums/topic...."
  When I write "something" in the textarea <id textare>
    And I click on "Envoyer"
  Then I should see "soemthing" in the list of messages of this topic
```

Après je pense qu'on devrait isoler les tests JS des tests principaux (des tests python, du back donc), qui lui se chargera de mocker le back justement. Ca demande un peu plus de maintenance, certes, mais ça permet de bien séparer les deux développement au besoin.

Sinon pour les tests automatiques, une fois le code rendu public, je suggère d'utiliser Travis-CI, avec un hook github qui à chaque push sur une des branches du répo (et lors d'une activité sur une pull-request, y compris son ouverture) va lancer les tests automatiques. Un peu à la jenkins pour les javateux, mais en moins compliqué, ne demande pas de serveur à configurer, bien qu'il soit peut-être moins complet.

Et pour les tests d'intégration, comme l'a présenté @SpaceFox, je pense pas qu'un test automatique soit nécessaire. Par contre, vu qu'on bossera par PRs, un autre dév **devra** faire une code review (et pourquoi pas le tester manuellement en effet si c'est touchy).

En tout cas, c'est comme ça que je le vois

**Comment by firm1** [comment]
@Taluu  globalement je suis d'accord avec toi.

En gros, si on arrive à une architecture comme exposé [ici](http://www.miximum.fr/tutos/1408-tests-avances-avec-django), ce serait pas mal.

Je n'aurais clairement pas le temps de m'y coller à court terme, mais si quelqu'un de motivé pourrait initialiser le work flow (fichiers test vide -> coverage -> travis -> ... ) ça serait déjà pas mal.

**Comment by firm1** [comment]
> Je n'aurais clairement pas le temps de m'y coller à court terme, mais si quelqu'un de motivé pourrait initialiser le work flow (fichiers test vide -> coverage -> travis -> ... ) ça serait déjà pas mal.

Etant donné que je n'ai plus trop le temps ni les moyens de tester les PRs, je vais essayer de trouver du temps pour monter assez rapidement une base pour certains tests sur des vues critiques, histoire de ne pas laisser passer des commits buggués.
Avec un peu de chance on pourra consulter, dès demain matin, sur une plateforme d'intégration continue (travis-ci) les résultats des tests unitaires qui sont listés dans le premier message de ce topic.

**Comment by SpaceFox** [comment]
À propos de tests, j'ai un peu de temps devant moi et j'ai installé le
projet. Sauf que j'ai une merde, le truc démarre mais me crache des erreurs.
Est-ce que quelqu'un sera dispo ce soir pour me donner un coup de main pour
faire marcher le bousin ?

**Comment by firm1** [comment]
> Est-ce que quelqu'un sera dispo ce soir pour me donner un coup de main pour faire marcher le bousin ?

Je pourrai éventuellement filer un coup de main, vu que je bosserai dessus en rentrant chez moi (donc ça ne sera pas avant minuit)

**Comment by firm1** [comment]
Le repo actuel étant privé, impossible de mettre en place Travis, même si tout est déjà configuré pour. C'est dommage.

Est-ce que @Taluu qui dispose du compte privé peut essayer de connecter ce repo à travis ?

**Comment by Taluu** [comment]
Le soucis, c'est que pour les dépots privés, Travis est payant, [et coute une blinde](https://travis-ci.com/plans)... Ce sera donc pour quand le dépot deviendra public. Ou alors en attendant, faire tourner ca sur une preprod en effet, qui surveille chaque commit (sur la develop, ou toutes les branches ?)

**Comment by firm1** [comment]
Bah j'ai cru voir qu'ils proposent un trial ? Mais pas moyen de le lier de mon côté.

**Comment by Taluu** [comment]
Sauf que 100 builds c'est un peu limite... Et j'ai l'impression de pas pouvoir le lier non plus

**Comment by firm1** [comment]
> Sauf que 100 builds c'est un peu limite.

C'est déjà mieux que rien en attendant l'ouverture. Et puis, il suffit de builder uniquement sur les PR. C'est principalement ce qui m'interesse personnellement.

**Comment by firm1** [comment]
C'est bon, travis est en route uniquement pour le PR.

le resultat d'un build est visible directement sur le readme ainsi : 

[![Build Status](https://magnum.travis-ci.com/Taluu/ZesteDeSavoir.png?token=Cu35XY4F6RcYoPgjjcbA)](https://magnum.travis-ci.com/Taluu/ZesteDeSavoir)

On verra ainsi d'un coup d'oeil si une PR casse les tests ou pas, ce qui nous permettra de nous concentrer sur l'évolution apporté par la PR sans se poser les questions de non regressions.

**Comment by GerardPaligot** [comment]
Sorry, je l'ai peut-etre manque. Travis, ca permet quoi ?

**Comment by firm1** [comment]
> Sorry, je l'ai peut-etre manque. Travis, ca permet quoi ?

Pour résumer, c'est une plateforme d'intégration qui permet de lancer tous les tests unitaires d'une projet à chaque nouveau commit/PR/etc.
ça permet de voir en un coup d'oeil (sans avoir besoin de tester complètement une PR) qu'aucune régression n'a été introduite.
Biensur, pour que ce soit efficace, il faut écrire un maximum de tests. Il faudra ensuite intégrer une lib (coverage) de calcul du pourcentage de couverture des tests  pour avoir une vision encore plus éclairée.

**Comment by GerardPaligot** [comment]
Ok, c'est un equivalent de Jenkins en fait.

**Comment by firm1** [comment]
Toutafè

**Comment by firm1** [comment]
Update : 

J'ai rajouté des tests : 
- la demande de validation d'un tuto : pour l'instant on vérifie juste qu'on a pas d'erreur
- la publication d'un tuto : pour l'instant on vérifie juste qu'on a pas d'erreur
- l'ajout d'une nouvelle note sur un tuto publié

Les tests que j'écris en ce moment concernent surtout les utilisateurs déjà connectés. Je verrais ensuite pour ceux non connectés.

Pour votre culture, je vous conseille de lire l'implémentation des factories (fixtures de tests automatiques) des tutos avec la création automatique des fichiers markdown et repo git.

**Comment by firm1** [comment]
Bon, pour la première fois le checkeur de tests est au vert. En gros, tous les tests que nous avons écrit jusqu’à présent marchent.

Je ferme donc cette issue. Et j'encourage les devs à rester sur le même cap pour atteindre un taux de couverture de 100% de tests.

**Comment by cgabard** [comment]
Je me permet de réouvir cette issue car nous n'avons plus qu'un seul build possible sur travis.

On fait quoi maintenant ?

**Comment by firm1** [comment]
> On fait quoi maintenant ?

On aura pas trop le choix que d'ouvrir le code le plus tôt possible. Ce qui nous donnera enfin accès tous les autres services (surtout coveralls qui me manque)

**Comment by SpaceFox** [comment]
On libère le projet et ça nous permet d'avoir une infinité de builds sur
Travis (si j'ai bien tout pigé).

Le 25 avril 2014 15:32, Christophe Gabard notifications@github.com a
écrit :

**Comment by geoffreyc** [comment]
Apres, tant qu'il n'y a pas de "fuite", le project peut tres bien etre
ouvert entant que publique sur github, et les chances que des gens tombent
dessus sont minimes, non?

2014-04-25 14:36 GMT+01:00 SpaceFox notifications@github.com:

**Comment by Alex-D** [comment]
Ca va apparaître sur nos profils (je pense là notamment au mien, qui est pas mal regardé) et donc c'est grillé en mois de deux.

**Comment by firm1** [comment]
Non mais on peut très bien vivre sans travis hein, on arrivais à faire sans avant (c'est juste un peu plus chiant). 

Mais d'un autre coté, au point ou nous en sommes, je ne vois plus de raison (hormis l'effet de surprise) de se cacher !

**Comment by Alex-D** [comment]
Avant d'ouvrir, même non-officiellement, il faudrait un minimum nettoyer en tous cas. Par ailleurs, les tests sont runnables en local je pense, donc pas tellement un problème en soi. C'est juste moins pratique.

**Comment by cgabard** [comment]
Le seul problème que je vois avec l'ouverture est que là on a pas vraiment d'espace de discussion associé d'ouvert. Ce qui va être genant si certains tombent dessus et veulent poser des questions.

Du coup, la beta, on la lance quand ?

**Comment by Coy0te** [comment]
> Du coup, la beta, on la lance quand ?

Quand tu auras réparé [zmarkdown](https://github.com/Taluu/ZesteDeSavoir/issues/322)... :p

**Comment by firm1** [comment]
Travis est re-ouvert, ainsi que coveralls pour le taux de couverture des tests.

Cette issue peut fermer

**Comment by coma94** [comment]
En tant que débutant ne connaissant pas ces outils avant d'être (un peu) impliqué dans zds, je me demande, sur que se base coveralls pour proposer une telle info?

**Comment by firm1** [comment]
>  je me demande, sur que se base coveralls pour proposer une telle info?

De ce que j'en sais pour coveralls, il lance l'execution de tous les tests, et il identifie le nombre de lignes dans les fichiers qui n'ont pas été exécutés (si le programme n'est pas rentré dans un `else` par exemple).

Une fois qu'il a la partie de code non exécutée, il détermine un pourcetange, en fonction de plusieurs paramètres.

C'est un exercice très intéressant a reproduire.

**Comment by Eskimon** [comment]
Je suis en train de regarder pour refactoriser les tests comme propose dans quelques ouvrages de bonnes pratiques en separant en trois fichiers :
- test_forms.py
- test_views.py
- test_models.py

J'ai bientôt fini de le faire pour member (qui a un coverall pas très glorieux et qui est assez simple a faire pour commencer). Je propose une PR pour ce module des que c'est prêt !
