### ISSUE TITLE
[Article] Aperçu d'une réaction d'un article

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#190]
Scénario :
- Afficher un article en ligne.
- Remplir le textearea prévu pour la réaction.
- Cliquez sur le bouton "Aperçu", le texte de la réaction n'est pas affiché.

Piste pour le bug : La valeur du texte de la réaction n'est pas affichée dans le template de la prévisualisation, voire le texte n'est pas envoyé au template.

**Comment by firm1** [comment]
Il suffit d'aller à la [ligne suivante](https://github.com/Taluu/ZesteDeSavoir/blob/dev/templates/article/answer.html#L40) et modifier le code suivant : 

``` html
{% if text %}
    {% include "forum/previsualization.part.html" %}
{% endif %}
```

par 

``` html
{% if form.text %}
    {% with text=form.text %}
        {% include "forum/previsualization.part.html" %}
    {% endwith %}
{% endif %}
```

**Comment by GerardPaligot** [comment]
Ah effectivement. C'est plus jolie que de passer un `text` au template.

(Merci beaucoup pour toutes les revues sur les issues. @Ge0 voulait justement commencer à contribuer)

**Comment by Ge0** [comment]
Je confirme les dires de @GerardPaligot, je me remets dans le bain doucement. Merci :)

**Comment by SpaceFox** [comment]
C'est plus joli, mais ça marche pas :(

Donc soit je passe un text au template comme c'est fait partout ailleurs, soit je laisse quelqu'un d'autre regarder pourquoi la sollution de @firm1 me crache : 

> AttributeError at /articles/message/nouveau
> 'BoundField' object has no attribute 'strip'

sur la ligne 6 de "templates/forum/previsualization.part.html"  (c'est le `|emarkdown` qui provoque cette erreur, sans ça la prévisualisation marche - mais sans le markdown.

Dans tous les cas, je n'ai pas la moindre idée de comment écrire un test automatique qui couvre ce cas.

**Comment by SpaceFox** [comment]
Corrigé, PR, mergé --> Fermé
