### ISSUE TITLE
[suggestion] Afficher les noms complets sur la page des tutoriels

### ISSUE THREAD

**Issue by fxmarty** [zestedesavoir/zds-site#1900]
A un niveau de zoom plus élevé que celui par défaut, certains titres sur les pages [Tous les tutoriels](https://zestedesavoir.com/tutoriels/), ses sous-parties, et sur la page [Tous les articles](https://zestedesavoir.com/articles/) ne sont pas affichés dans leur totalité, des "..." remplaçant la fin des titres.
Voici un screenshot peut-être plus explicite :
![test10](https://cloud.githubusercontent.com/assets/9808326/5426080/9c1c8a28-833a-11e4-9737-e402bee4a22e.png)

Il serait peut-être intéressant pour le confort de lecture de pouvoir quand même afficher les titres complets, pourquoi pas sur deux lignes.

**Comment by gustavi** [comment]
Je crois que c'est prévu avec la ZEP-04. Il me semble même qu'une issue est déjà ouverte.

Merci de retour mais à l'avenir il serait bien de passer par le forum pour toute suggestion !

**Comment by fxmarty** [comment]
Oui, j'ai ouvert le ticket avant de voir qu'il y avait un sous-forum et même un topic consacré à ce genre de mini-problème...

Désolé pour le dérangement.
