### ISSUE TITLE
[Hotfix v1.4] La connexion via les réseaux sociaux renvoie vers le mauvais nom de domaine

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1903]
Ou plus exactement utilise le nom de domaine interne, qui n'est pas le nom de domaine public. Exemple avec twitter : http://zdsappserver/complete/twitter/

**Comment by ghost** [comment]
Pareil pour Google+

![Imgur](http://i.imgur.com/ltBojuN.png)

**Comment by gustavi** [comment]
Peut-être faire des tests en préprod avec https://stackoverflow.com/a/21295321

**Comment by Eskimon** [comment]
Faudrait envoyer un MP a firm1 qui a bosse la dessus mais s'est mis un peu en stand-by du dev pour le moment...

**Comment by SpaceFox** [comment]
Toujours pas d'idée ici ?

Si personne n'a d'idée, peut-on au moins dégager la fonctionnalité cassée du front ?

**Comment by firm1** [comment]
Bon, je viens de passer sur la preprod et la prod, c'était bien un problème infra. J'ai corrigé la conf de nginx afin de ne plus exposer le nom interne, et maintenant ça marche.

Je ferme donc.
