### ISSUE TITLE
[Hotfix v1.4] La page de la ZEP-3 n'est pas accessible

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1904]
Erreur :

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)

template : tutorial/tutorial/help.html at line 58

Cf Sentry pour les détails.

**Comment by pierre-24** [comment]
Y'a moyen que tu me balance les détails SEntry concernant par MP ou un truc du genre ? Merci :)

**Comment by pierre-24** [comment]
Je crois que je tiens l'erreur, attention, c'est un peu subtil.
- Créer un tutoriel avec un user A, dont le titre comporte des accents. Demander de l'aide. Si on visite alors la page de demande d'aide, on a pas d'erreur
- Se connecter avec un utilisateur B, visiter la page d'aide: boum, erreur unicode.
- Si l'user A désactive sa demande d'aide, tout redevient normal. Si on demande de l'aide sur un tuto dont le titre est sans accent, pas de problème.

Dès lors, je suis quasi certain que l'erreur a rapport avec la fonction d'envoi de MP associé à une demande d'aide. Plus précisément [la dans le model.py](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/models.py#L143). Et je suis presque sur que la résolution est de taper un `u` quelque part. Sur ce, je demande assignation et je poste un bugfix ASAP :)

(j'ai aucun mérite, ça se trouve en grosse partie dans Sentry, encore merci @SpaceFox au passage :) )

**Comment by SpaceFox** [comment]
Hop, assigné !

**Comment by artragis** [comment]
En fait c'est pas de la rustine, c'est exactement ce qui va corriger l'erreur selon moi. Je n'ai pas trop le temps de QA, mais là ça va sûrement être ce qui va tout débugger.

Par contre, a-t-on prévu le cas où le titre contiendrait des guillemets?  Plutôt que de donner le titre complet, je pense que le slug serait clairement adapté.

**Comment by Eskimon** [comment]
Problème réglé, je ferme.
