### ISSUE TITLE
[Hotfix1.4] Tout les sujets sont marqués comme résolu

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1906]
Comme [reporté sur la préprod](http://preprod.zestedesavoir.com/forums/sujet/1787/tous-les-sujets-sont-marques-comme-resolus/?page=1#p30770), quand on visite un sujet, il apparaît systématiquement avec le bandeau vert indiquant que l'auteur a trouvé une solution a son problème. L'exemple est tout simplement le sujet que j'ai mis en lien ... Que je n'ai pas sélectionné comme résolu. D'ailleurs, j'ai toujours le bouton "marquer comme résolu" (qui fonctionne).

**Comment by pierre-24** [comment]
Piste de résolution : y'a un truc pas net dans la template correspondante, [ligne 67 du fichier template/forum/topic/index.html](https://github.com/zestedesavoir/zds-site/blob/dev/templates/forum/topic/index.html#L67).

**Comment by Situphen** [comment]
Le code est bon, c'est juste le CSS qui est manquant. Cependant je pense que c'est mieux de passer par le Back pour ce genre d'alerte ! ;)

La question est : y-a-t-il un problème si on passe par le back ?

**Comment by pierre-24** [comment]
Dévellope un peu ce que tu entends par "passer par le back" ?

**Comment by Situphen** [comment]
**Actuellement**, le message est tout le temps envoyé, il est caché en CSS.

**Dans l'idéal**, le message est envoyé que quand il faut. (Avec un `{% if ... %}`)

**Comment by pierre-24** [comment]
... C'était le cas avant. Puis, j'ai pas trop compris pourquoi, @firm1 a fait un truc pour faire de l'AJAX (en fait, si c'est logique, mais en pratique ça foire), et a mis en place cette solution ou le message est toujours envoyé. C'est pas le cas actuellement sur la prod, par exemple, c'est assez récent ([regarde l'historique du fichier](https://github.com/zestedesavoir/zds-site/blame/dev/templates/forum/topic/index.html#L67) pour t'en convaincre)

**Comment by Situphen** [comment]
Non mais en fait il n'y a pas d'erreur ici ! C'est comme pour l'histoire des dates sur des messages, c'est le CSS qui est mal généré sur la préprod !

**Comment by pierre-24** [comment]
Ah, j'allais justement faire un message avec ça. Bon, ça explique :)

Ping @SpaceFox  ?

**Comment by SpaceFox** [comment]
Comment on vérifie ça ? Comment on régénère ledit CSS ?

**Comment by Situphen** [comment]
On vérifie ça en regardant le fichier main.css. Moi j'ai vérifié et il y a bien des trucs qui manquent dedans.

@SpaceFox : Tu peux faire un `npm run-script gulp clean && npm run-script  gulp build` ?

**Comment by SpaceFox** [comment]
Hmmm, ce que tu me dis là me pose problème parce que je n'ai pas `npm run-script gulp build` dans [le script de déploiement](https://github.com/SpaceFox/zds-site/blob/dev/server/deploy.sh).

J'ai l'impression qu'il faudrait mettre ce script à jour.

**Comment by Situphen** [comment]
Non le script est à jour. Je savais pas que le script utilisé était "pack" et non "build".

Du coup, tu peux faire :

``` shell
gulp clean
gulp pack
```

**Comment by pierre-24** [comment]
Moi j'utilise `gulp build` en local, et ça marche aussi :)

**Comment by SpaceFox** [comment]
Du coup, le bon script qui est sensé fonctionner 100% des fois, c'est
lequel ? (je suis un peu paumé là).

2014-12-15 8:07 GMT+01:00 Pierre Beaujean notifications@github.com:

**Comment by pierre-24** [comment]
Si je comprend un peu comment c'est fait, "pack" est quasiment un alias de "build", mais y'a une broutille avec un zip en plus qu'il génère dans `/dist/`. D'après des tests que j'ai fait chez moi, l'un et l'autre génèrent bien les bons trucs pour le site. La commande "pack" me semble en fait liée aux devs qui n'ont pas envie de jouer avec le front, et qui se servent du fameux "pack.zip" à placer à la main dans `dist`. Du pareil au même, donc, mais il FAUT garder `pack`, selon moi.

**Comment by Situphen** [comment]
Voilà, @pierre-24 a tout compris ! :)

**Comment by Situphen** [comment]
@SpaceFox : tu as fait `gulp clean && gulp pack` ? tu as bien vidé le cache nginx ?

**Comment by SpaceFox** [comment]
Je n'ai rien fait du tout pour l'instant, puisqu'il me fallait la vraie
commande _et_ que je rentre chez moi. Je vous tiens au courant quand c'est
fait.

2014-12-15 18:46 GMT+01:00 Situphen notifications@github.com:

**Comment by sandhose** [comment]
Pour être vraiment sûr: 
- `npm install -g npm` -> update npm, pour être sûr d'être en 2.x.x ; si ça plante, lances-le en root (ca dépend de l'installation...)
- vires le dossier `dist/`, `node_modules/` et `assets/bower_components/`
- `npm install` dans le projet (installe les dépendances)
- Vérifies qu'il y a bien le dossier `assets/bower_components/` qui s'est recrée, si c'est pas le cas (ça devrait...): `npm run bower -- install`
- `npm run gulp -- build` -> Compile le tout, devrait créer le dossier `dist/`

Si avec ça, ça marche pas, je sais pas... :-°

**Comment by SpaceFox** [comment]
Ca marche nickel, merci !

Du coup je ferme ici, c'est corrigé.
