### ISSUE TITLE
Gulp recrée les images et les smileys après un changement de dossier

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#1907]
Reporté [sur le forum](https://zestedesavoir.com/forums/sujet/1921/gulp-fait-nimporte-quoi-sur-ma-version-du-zds) :

```
├── ZdS ← ANCIEN DOSSIER CONTENANT LES SOURCES
│   └── main
│       └── assets ← DOSSIER QUE GULP S'AMUSE À RECRÉER À CHAQUE FOIS
│           ├── images
│           └── smileys
└── zds-site  ← POSITION ACTUELLE DES SOURCES
│   └── assets
│       └── images ← vide sauf le sprite
│       └── smileys ← vide
│       └── js
│       └── scss
│       └── ...
```

Le problème vient de la dépendance "imagemin" qui met en cache les images minimisées. La faute revient à `$.cache()` que l'on trouve à [la ligne 110](https://github.com/zestedesavoir/zds-site/blob/dev/Gulpfile.js#L110) et à [la ligne 118](https://github.com/zestedesavoir/zds-site/blob/dev/Gulpfile.js#L118) !

**Comment by pierre-24** [comment]
Fixé par #1908
