### ISSUE TITLE
[Article] Champs vide d'une réaction d'un article

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#191]
Scénario :
- Afficher un article en ligne.
- Ne pas remplir le textearea prévu pour la réaction.
- Cliquez sur le bouton "Envoyer", une erreur 404 est lancée.

**Comment by firm1** [comment]
Cette erreur est [voulue](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/article/views.py#L688) étant donné que toutes les erreurs fonctionnelles backend actuelles renvoient une 404.

Ceci dit, avant, il y'avait une [erreur JS](https://github.com/Taluu/ZesteDeSavoir/blob/5a9fa8930fc3c2a81af5b7de9c5d71700d3d65e9/templates/article/view_online.html#L255) qui se déclenchait quand on postait un message vide. Je ne sais pas trop qui l'a viré, ni pourquoi, mais ça évitait pour ceux qui on du JS d'activer de devoir atteindre le serveur pour rien.

Donc, à court terme, il faudrait rajouter ce bloc pour corriger le souci. A long terme, il faudrait changer le raise 404 du back-end par un affichage d'erreur construit via une fonction clean de la form.

**Comment by firm1** [comment]
Fixé et mergé. Je ferme
