### ISSUE TITLE
Des forums en double

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#1913]
Suite à une réorganisation du staff et de leurs groupes sur l'instance zestedesavoir.com, un bug est apparu dans la liste des forums disponibles :

![capture d ecran 2014-12-15 a 14 54 27](https://cloud.githubusercontent.com/assets/1913901/5436768/71886aa8-846a-11e4-95a7-23df52a8baf2.png)

Le forum "Zone Staff" apparait 2 fois. Je soupçonne le fait que j'appartiens à deux groupes qui ont tous les deux le droit de voir ce forum "Zone Staff". Du coup, le back me le renvoi 2 fois.

**Comment by pierre-24** [comment]
Mmh. Ça me fait penser que les fixtures devraient contenir un forum staff pour ce genre de test, faut que j'écrive une issue à ce sujet.

Du reste, j'avoue que j'ai du mal à voir ou ça se passe dans le code :/

**Comment by Eskimon** [comment]
Corrigé, merci @firm1
