### ISSUE TITLE
[Hotfix v1.4] Aperçu d'un post impossible

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1915]
Comme [reporté sur le forum de la préprod'](http://preprod.zestedesavoir.com/forums/sujet/1792/apercu-lors-de-ledition-dun-message/) par Vinc' que je remercie au passage, parce que j'arrivais pas à mettre le doigt dessus,

> Lorsque j'ai édité divers messages sur le forum, impossible d'obtenir d'aperçu !
> Cela ne semble concerner que le premier message des sujets.
> 
> PS : Ce bug se produit également lors de la création d'un nouveau sujet sur le forum, je viens d'en faire l'expérience !

Alors, il y a erreur Django, et c'est une `raise MultiValueDictKeyError(repr(key))` en rapport avec [la ligne 240 de zds/forum/views.py](https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/views.py#L240). Plus précisément, il trouve pas `title` dans la requête POST. Pourquoi ? J'avoue que j'ai pas encore eux le temps de regarder à ça, mais je pense que l'erreur est cernée, elle devrait pas s’échapper longtemps.

PS: quelqu'un sais ce qui se passe coté AJAX sur le forum ? Y'a plein de mention à de l'AJAX, mais j'arrive pas à voir si cette erreur est lié à ça.

**Comment by Situphen** [comment]
Il y a la PR #1867 qui touche à la prévisualisation ([ici](https://github.com/zestedesavoir/zds-site/pull/1867/files#diff-37d34ac341508430e3ef0b8fbe0cae8bR128)). Ping @firm1

**Comment by pierre-24** [comment]
Bwah, à vue de nez, je dirais qu'il tente de faire une preview en ajax mais qu'il la plante parce que le paramètre `title` est pas recherché par le script que t'as mis en lien et pas balancé en POST au back. Ça me semble facile à régler, mais je suis pas à l'aise avec le front. Tu sais le faire,  @Situphen ? Sinon, je peux regarder moi-même, mais je promet rien :)

**Comment by Situphen** [comment]
Je n'ai pas le temps ce soir, je m'y penche demain. J'en profiterai sûrement pour régler quelques mauvaises pratiques.

**Comment by SpaceFox** [comment]
Si on pouvait limiter le hotfix aux strictes corrections et corriger les mauvaises pratiques dans la branche de dev, ce serait génial :)

**Comment by SpaceFox** [comment]
Corrigé, mergé, fermé.
