### ISSUE TITLE
Impossible d'accéder aux tutoriels

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#1916]
Via Ache sur la préprod : 

> Quand je vais dans le menu "Tutoriels" pour sélectioner une catégorie, tous les liens même vers la page courante. Du coup, plus aucun tutoriel n'est accessible.
> 
> Je suis le seul ?

Et, je confirme le bug, en effet, toute les catégories ramène sur la page courante !

**Comment by pierre-24** [comment]
Je vois: à première vue, le [template correspondant](https://github.com/zestedesavoir/zds-site/blob/dev/templates/base.html#L182) s'attend à ce que le back lui renvoit un objet `Subcategory`, alors que [c'est un string qui est renvoyé](https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/templatetags/topbar.py#L89). 

Commment régler ça ?
- Renvoyer effectivement l'objet ;
- Renvoyer juste le pk de la `Subcategory`, avec un `{% url %}` le front devrait s'en sortir de lui-même.

Dans tout les cas, pas un truc très long à corriger.

**Comment by pierre-24** [comment]
... J'avais 10 minutes ;)

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé
