### ISSUE TITLE
[Membre] Message privé avec un membre

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#192]
Scénario :
- Afficher le profil d'un membre.
- Cliquez sur "Message Privé" pour lui envoyer un message privé.
- Le membre n'est pas ajouté automatiquement dans la liste des participants.

Piste pour le bug : Les identifiants du membre n'est pas donnés a la création du message privé.

**Comment by firm1** [comment]
Il suffit de modifier [cette ligne](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/mp/views.py#L151) par :

``` python
if 'username' in request.GET:
    try:
        #check that username in url is in the database
        dest = User.objetcs.get(username=request.GET['username']).username
    except KeyError:
        dest = None

form = PrivateTopicForm(initial = {
                'participants': dest
            })
```

**Comment by firm1** [comment]
C'est corrigé, je ferme
