### ISSUE TITLE
Ajouter un compteur du nombre de sujets créés non visibles pour un simple membre

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1920]
Via le [Forum](http://zestedesavoir.com/forums/sujet/1936/compteur-de-sujets-crees-errone/?page=1#p34485) : 

La solution proposée par @cgabard semble dégager un consensus :  « on indique clairement où sont les autres, genre une phrase en dessous de la liste comme "+ 4 sujets dans un forum dont vous ne disposez pas les droits de lectures" ».

**Comment by pierre-24** [comment]
Je propose une pitite infobulle en plus pour préciser qu'il n'y a rien de secret là dedans mais que ces forums sont nécéssaires à la bonne gestion du site. Ou une page.

**Comment by gustavi** [comment]
:+1:

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis près d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.
