### ISSUE TITLE
Ajouter un bouton pour rédiger un tuto et pour aider à la réaction dans le dropdown du menu

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1921]
Proposé par @cgabard (encore lui !) sur [l'article de la ZEP-03](http://zestedesavoir.com/articles/140/premiere-zep-developpee-sur-zeste-de-savoir/?page=2#p34918) : 

« Dans la grande liste de catégorie quand tu clique sur "Tutoriel" ? On pourrait rajouter ici deux bouton, un pour en rédiger et un pour aider. »

Ça permettrait à ces 2 pages d'être plus facilement accessibles.

**Comment by Eskimon** [comment]
Apparemment cette proposition doit etre discute plus en profondeur, tout le monde ne semble pas en phase avec ce qui serait bien de faire.

**Comment by Situphen** [comment]
Je crois que cette idée a été abandonnée vu qu'il y aura un gros bouton sur la nouvelle page d'accueil ?

**Comment by Eskimon** [comment]
Il manque quand meme de la visibilité pour le "aider les auteurs"

**Comment by Situphen** [comment]
Je pense que l'on peut ajouter ça sur la page d'accueil. Il faudrait juste demander l'avis aux membres sur le sujet de la ZEP !

**Comment by Eskimon** [comment]
Sur les fofos ca semblait apprécier:
- ici : https://zestedesavoir.com/forums/sujet/669/zep-04-nouvelle-page-daccueil/?page=25#p34936
- puis la : https://zestedesavoir.com/forums/sujet/669/zep-04-nouvelle-page-daccueil/?page=33#p35803
- puis une autre fois https://zestedesavoir.com/articles/140/premiere-zep-developpee-sur-zeste-de-savoir/?page=2#p34917

silvouplééééé

**Comment by SpaceFox** [comment]
Je plusseoie le caribou : ça a l'air assez demandé pour qu'on le fasse.

**Comment by motet-a** [comment]
Il y a désormais une belle section en bas de la bibliothèque :

![image](https://user-images.githubusercontent.com/15378830/32145685-13eed7ee-bccd-11e7-8628-6e7f32164885.png)

Je ne pense pas que ce soit la peine de rajouter des choses dans le menu.

**Comment by artragis** [comment]
@sandhose on clos?

**Comment by gllmc** [comment]
J'ai quand même un doute par rapport à ça : c'est en effet bien mis en avant sur l'accueil de la bibliothèque. Par contre, je pense pas que ce soit une page sur laquelle on aille beaucoup (elle n'est accessible qu'avec `Accéder à tous les contenus de la bibliothèque`).

**Comment by Vanadiae** [comment]
Ticket a fermé (feature déjà présente) @artragis. Au passage j'ai le bouton close issue. Est-ce que je peux fermer les tickets inutiles ou je continue à te ping?

**Comment by artragis** [comment]
Continue de ping pour l'instant.
