### ISSUE TITLE
[Hotfix v1.4] La redirection après connexion ne fonctionne pas

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#1923]
Pour retrouver le bug :
- Se déconnecter
- Aller sur un article
- Comme vous n'êtes pas connectés, il y a aura le bouton connexion à la fin des commentaires
- Cela va vous rediriger vers /membres/connexion/?next=/articles/pk/nom-de-l-article
- Connectez-vous
- (Voilà le bug :) Vous n'êtes redirigés vers l'article mais vers la page d'accueil

**Comment by gustavi** [comment]
Corrigé dans #1924 !
