### ISSUE TITLE
Catégories du forum qui se superposent

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#1925]
Reporté par cariopes sur le forum ([ici]()) :

> Si la taille de la largeur de la fenêtre est comprise entre 960px et 995px le sous titre "Beta zone des tutos et articles" dépasse sur la ligne du dessous.
> Le problème se répercute aussi si on place son curseur sur le lien ce qui à pour effet de le décaler sur la ligne du dessous et cela jusqu'à 1025px…

![le bug en image](https://zestedesavoir.com/media/galleries/1287/d6a7b400-babd-421a-842c-9d312e4e4e23.png.960x960_q85.jpg)

**Comment by ghost** [comment]
Quel est la solution envisagée ? Remplacer le texte en trop par "..." ?

**Comment by Eskimon** [comment]
> Quel est la solution envisagée ? Remplacer le texte en trop par "..." ?

Ce serait frustrant quand on voit toutes la place disponible a droite...

**Comment by SpaceFox** [comment]
+1 Eskimon.

**Comment by ghost** [comment]
Je n'avais pas fais attention, je prends.

**Comment by ghost** [comment]
![Imgur](http://i.imgur.com/oHnTclc.png)

Je n'ai pas réussi à faire mieux en css.

**EDIT :** Je vais devoir changer de méthode.

**Comment by Situphen** [comment]
@A-312 : Tu peux utiliser du JS vu que le dropdown est déjà géré en JS ! ;)

**Comment by firm1** [comment]
Je ferme ici en tagguant en 1.7, aucune de idée de ou ça finira

**Comment by SpaceFox** [comment]
è_é

**Comment by SpaceFox** [comment]
Argumentaire plus poussé : ces milestones sont le **seul** moyen à peu près fiable dont on dispose pour savoir ce qu'il y a dans une release. C'est donc **interdit** de jouer avec.

**Comment by firm1** [comment]
C'est pour ça que je le signale. Etant donné que la release 1.7 ne déploie pas, je ne sais pas ce qu'il en deviendra

**Comment by SpaceFox** [comment]
Moi non plus. Mais dans ce cas il ne fallait pas la mettre dans la v1.7...
