### ISSUE TITLE
Pandoc et les chemins Windows

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1927]
j'ai trouvé un bug relativement ridicule (en fait, je m'étonne que Pandoc n'y aie pas pensé) : lorsqu'on écrit un tutoriel contenant un chemin Windows type `C:\Program Files\`, la génération du pdf ne fonctionne pas. Raison plus que probable, parce que je l'ai vue passer sur IRC, c'est tout simplement que le `\` n'est pas échappé et que donc LaTeX se plante dessus parce que `Undefined control sequence. \Program`.

**Comment by firm1** [comment]
C'est plus un problème de markdown ça non ? faudrait le reporter ailleurs je suppose.

**Comment by Eskimon** [comment]
On fait quoi ici ? On a pas d'utilisateur windows et ca ressemble plus a un bug a transmettre a pandoc non ?

**Comment by firm1** [comment]
C'est un problème pandoc. On a pas besoin d'être sur windows pour tester, il suffit de rajouter un chemin du style `C:/Windows/` dans un texte pour que la génération du pdf plante a cause de latex. Il faut penser à demander aux auteurs d'échapper leur chemin Windows.

**Comment by Eskimon** [comment]
@cgabard tu connais le depot pour transmettre ca à Pandoc ?

**Comment by GerardPaligot** [comment]
@cgabard Est-ce que tu serais confirmer ou infirmer le bug ? Savoir si c'est toujours d'actualité.

**Comment by cgabard** [comment]
J'ai rien pour tester là. Ça m'étonne mais faudrait tester sur un pandoc pour vérifier

**Comment by AmarOk1412** [comment]
@artragis à fermer
