### ISSUE TITLE
Le filtre de la zep3 n'est pas au point

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#1928]
Sur la page d'aide de la zep-3, des tutos apparaissent dans la liste de demande d'aides alors qu'ils ne devraient pas (car ni en beta et aucune demande d'aides d’activées)

Le probleme se situe ici mais je vois pas pourquoi de tel tutos passe dans la liste tout de meme... : https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L3618

Dans l'illustration suivante, les deux premiers tutos n'ont rien a faire la...

![screenshot from 2014-12-19 09 11 50](https://cloud.githubusercontent.com/assets/761168/5501707/66e6fcde-875f-11e4-89b1-eab45fe96e89.png)

**Comment by poulp** [comment]
Quand on regarde le profil de Auteur externe on remarque deux tutos en bêta, mais impossible de les afficher

**Comment by Eskimon** [comment]
> Quand on regarde le profil de Auteur externe on remarque deux tutos en bêta, mais impossible de les afficher

Ca c'est a cause de cette histoire de pagination que j'ai reportée ici https://github.com/zestedesavoir/zds-site/issues/1929

**Comment by poulp** [comment]
non c'est pas ce que je voulais dire, impossible de les afficher à cette adresse : http://preprod.zestedesavoir.com/tutoriels/recherche/242/?type=beta , du coup je soupçonne ces deux premiers tuto d'avoir un truc louche avec la bêta, d'où leur affichage sur la page d'aide

**Comment by poulp** [comment]
quelqu'un a réussi à reproduire en local ?

**Comment by pierre-24** [comment]
Impossible de reproduire quoique ce soit en local me concernant. 

J'ai peut-être une idée ceci dit. Comme il s'agit de vieux tuto datant d'OC, éventuelement, le champ `sha_beta` peut être vide (`""`), mais pas égal à `Null`. Pour faire disparaitre ça, je parie qu'un admin qui passe par là et qui active puis déasctive la béta de ce tuto devrait faire rentrer ça dans l'ordre.

(c'est juste du guess, hein, comme j'ai pas accès à la bdd pour des raisons évidentes)

**Comment by pierre-24** [comment]
Oki, je viens de faire faire le test d'activer puis désactiver la béta à l'aide de @SpaceFox sur le tuto "Google Maps JavaScript API V3". Vous pouvez constater que le tuto a bien disparu comme je l'avais espéré de la liste d'aide. 

(et qu'il n'y a plus [qu'un seul tuto en béta pour auteur externe](http://preprod.zestedesavoir.com/membres/voir/Auteur%20externe/), alors qu'il y en avais deux avant, comme l'as fait remarquer @poulp)

J'en déduit trois choses : 
1. Il est très simple à priori de régler le bug à la main, et ça devrait pas toucher beaucoup de tutoriels, éventuellement des anciens.
2. Éventulement, le test pour aller chercher des tutos en béta devrait être `Tutorial.objet.filter(sha_beta__isnull=False).exclude(sha_beta="")` et non pas seulement `Tutorial.objet.filter(sha_beta__isnull=False)` comme c'est le cas un peu partout aujourd'hui. (j'ouvre une issue, mais c'est pas critique)
3. Un débat de fond : est ce qu'un tuto qui est donné à auteur externe ne devrait pas être systématiquement "en attente de repreneur" ? (j'ouvre un topic sur le forum).

**Comment by poulp** [comment]
> Éventulement, le test pour aller chercher des tutos en béta devrait être Tutorial.objet.filter(sha_beta__isnull=False).exclude(sha_beta="") et non pas seulement Tutorial.objet.filter(sha_beta__isnull=False) comme c'est le cas un peu partout aujourd'hui. (j'ouvre une issue, mais c'est pas critique)

Si il y a beaucoup de tutos touchés, un script de migration doit pas être long à écrire. Pour la mep quelle solution : script de migration(ou à la main) ou le rajout du filtre sur la requête ?

**Comment by pierre-24** [comment]
Je n'ai jamais écrit de script de migration, mais je te crois sur parole. 

Laisse moi deviner, un truc comme ça ?

``` python
tutos_problématiques = Tutorial.objet.get(sha_beta='').all()
for tuto in tuto_problématiques:
  tuto.sha_beta = None
  tuto.save()
```

**Comment by poulp** [comment]
yes tout simplement

**Comment by SpaceFox** [comment]
Pour info, en prod, il y a 4 tutos problématiques :

```
select * from tutorial_tutorial where sha_beta = '';
```

| ID | Titre |
| --- | --- |
| 215 | Google Maps JavaScript API V3 |
| 218 | La récursivité |
| 283 | Réaliser une PirateBox |
| 539 | Réaliser un télémètre à ultrasons |

**Comment by poulp** [comment]
Faudrait aussi localisé le moment où c'est passé de null/quelque chose à "" pour le sha_beta

**Comment by pierre-24** [comment]
À priori, [c'est moi](https://github.com/zestedesavoir/zds-site/commit/00f2d0e5fabf1e10a7a2c59c195843add8d77cea) qui ai été imposer ça en dur à l'époque ou j'ai réécrit une partie du code de gestion de la bêta (la ligne en question n'as pas changé depuis). Y'à aussi un [commit de firm1](https://github.com/zestedesavoir/zds-site/commit/da299351d0451848e6b19eb55fb0a10e08e8e3e3) d'à peu près ce moment là qui bloque le comportement en base de donnée. À partir de ce moment là, je pense qu'il n'est plus possible qu'un tuto aie été créé sans que le champ ne soit par défaut à `None`, soit assez tôt dans la vie du site. Je ne me souviens plus chronologiquement quand on a décidé la RàZ de tout le site, mais ça doit être aussi dans ces eaux là.

**Comment by Eskimon** [comment]
bon c'est rassurant tout ca car je voyais pas trop ou la reuete pouvait merder :D

**Comment by Eskimon** [comment]
Faudra du coup qu'un staff passe sur les 4 tutos qui ont besoin de cette mise à jour

**Comment by gustavi** [comment]
Note : un filtre par catégorie ça serait sympa aussi.

**Comment by Eskimon** [comment]
J'ai fait un passage furtif de mise en beta pour les tutos incrimines (puis ai mis le sujet auto a la poubelle), ca semble regler le probleme. Il me reste un seul tuto a faire qui n'est pas de moi ou auteur externe mais de vinm, je le contact en MP pour lui expliquer. Du coup je ferme ici car ce n'est pas un bug reproductible et qui a raison d'etre.

Merci du coup de main pour le diagnostique !

**Comment by Eskimon** [comment]
Par contre @pierre-24 :

> Un débat de fond : est ce qu'un tuto qui est donné à auteur externe ne devrait pas être systématiquement "en attente de repreneur" ? (**j'ouvre un topic sur le forum**).

J'ai pas vu le sujet, il est fait ou pas ? Car a mon avis c'est une bonne idée...

**Comment by pierre-24** [comment]
Bien vu, j'avais oublié. Oubli réparé : 

https://zestedesavoir.com/forums/sujet/2015/tutoriel-en-attente-de-repreneur-si-le-membre-se-desinscrit/
