### ISSUE TITLE
La couleur de fond du footer a changée

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1932]
En passant sur la préprod, j'ai remarqué que la couleur du background du footer du site a changée (ça ne faisait pas partie des évolutions de la 1.4 il me semble), et du coup ça rend moins bien dans le footer je trouve.

Dans la version 1.3 (en prod) c'est pourtant correct.

couleur du footer en prod : #042432
couleur du footer en préprod : #084561

Navigateur : firefox 33
OS : Windows

**Comment by Situphen** [comment]
Ce n'est pas un bug, c'est @Alex-D qui [avait changé ça](https://github.com/zestedesavoir/zds-site/commit/2d863769162c45014fdf20dab1974a14c486dd42#diff-f00f3aa7f238e444f350cbb1a7d0df38L3046)) pour mettre la même couleur que le header.

**Comment by gustavi** [comment]
On est d'accord que c'est pas un bug ?

**Comment by Situphen** [comment]
Ce n'est pas un bug.
