### ISSUE TITLE
Faille de sécurité dans Git

### ISSUE THREAD

**Issue by Fumble** [zestedesavoir/zds-site#1933]
A voir si on est impacté et si il faut mettre à jour nos libs: http://article.gmane.org/gmane.linux.kernel/1853266

Par contre, mettez vos clients (ligne de commande, IHM...) à jour.

**Comment by pierre-24** [comment]
Le repo en lui-même n'est surement pas touché, à moins que github n'emploi un système de fichier qui ne tient pas compte de la casse (m'étonnerai). Par contre, c'est important de mettre git à jour.

@firm1 : quid de GitPython, du coup ?

**Comment by gustavi** [comment]
UP @firm1 !

**Comment by Eskimon** [comment]
Apres 4 mois on fait quoi ??

**Comment by SpaceFox** [comment]
A priori y'a rien à faire surtout que les serveurs sont maintenus à jour avec les MAJ de sécurité.

Donc, on ferme.
