### ISSUE TITLE
Problème d'affichage catégorie sur la home page

### ISSUE THREAD

**Issue by poulp** [zestedesavoir/zds-site#1934]
(Firefox 33/Ubuntu) Les sous catégories ne s'affichent pas: 
![capture](https://cloud.githubusercontent.com/assets/819246/5508068/6305346a-87a9-11e4-8652-d8fa5975c6f2.png)

**Comment by pierre-24** [comment]
Pareil ici (Chrome/39.0, Debian)

**Comment by pierre-24** [comment]
... Mais à priori réglé par #1935 que je viens de QA.

**Comment by SpaceFox** [comment]
"A priori" ou "réglé" ?

**Comment by pierre-24** [comment]
Réglé (je viens de tester la différence :) )

**Comment by SpaceFox** [comment]
OK, alors ici c'est fermé :)
