### ISSUE TITLE
Utiliser le dropdown désactive les modales

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1936]
Alors, celui là, je l'ai pas trop compris. Tout est dans le titre.
- Prenons une page avec une boite modale : validation d'un tutoriel. Créer un tuto, demander la validation. Vous pouvez faire apparaître cette boite modale autant de fois que vous voulez (évidement à condition d'appuyer sur annuler à chaque fois)
- Utilisez n'importe quel élément de dropdown : impossible ensuite de faire réapparaître cette fenêtre. Je n'ai pas d'erreur JS dans la console Chrome.

Marche avec n'importe quel modale (par exemple, signalement sur un forum, publication d'un tuto ... Toussa).

À noter que ce bug est déjà présent sur la prod.

**Comment by poulp** [comment]
ça m'arrive aussi, je l'ai remarqué quand j'ai qa la #1595 : 

> Et en bonus un bug chelou que je ne pourrais expliquer, j'ai aucune erreur sur la console js : Quand je clique sur mon image de profil, ça m'ouvre le menu normal, je le referme en re cliquant sur mon image de profil, et la quand je clique sur le bouton pour proposer une correction la modal ne s'affiche plus.

**Comment by pierre-24** [comment]
Bien vu, je me disais aussi que quelqu'un en avais déjà parlé :)

**Comment by ghost** [comment]
Il faudrait envisager de réécrire proprement cette fonction, ou en tout cas de la "nettoyer".
