### ISSUE TITLE
Problème de syncronisation avec Read The Docs

### ISSUE THREAD

**Issue by istandre** [zestedesavoir/zds-site#1938]
Deux points :
**Premièrement**, les fichiers d'installations sur github sont désuets comparativement à la [documentation officielle de zds](http://zds-site.readthedocs.org/fr/latest/index.html) :
- [install-linux.md](https://github.com/zestedesavoir/zds-site/blob/dev/doc/install-linux.md)
- [install-os-x.md](https://github.com/zestedesavoir/zds-site/blob/dev/doc/install-os-x.md)
- [install-windows.md](https://github.com/zestedesavoir/zds-site/blob/dev/doc/install-windows.md)

Devons nous les supprimer ou renvoyer l'utilisateur vers la documentation à jour ?

**Deuxièmement**, la documentation officielle ne semble pas avoir été synchronisée avec les derniers changements enregistrés sous github. Par exemple, pour l'installation sous Linux dans la section [Lancer Zds](http://zds-site.readthedocs.org/fr/latest/install/install-linux.html#lancer-zds), la première commande est fausse et devrait plutôt être `pip install --upgrade -r requirements.txt -r requirements-dev.txt`. Or, dans la [documentation de sphinx dans github](https://github.com/zestedesavoir/zds-site/blob/dev/doc/sphinx/source/install/install-linux.rst#lancer-zds), le fichier est bon.

**Comment by gustavi** [comment]
**Premièrement** : doublon de #1713

**Deuxièmement** : qui a mis en place ça ? ping @SpaceFox

**Comment by pierre-24** [comment]
Il me semble que c'est @firm1  qui gère ça. Sauf qu'il est en congé dévellopement, donc faut lui envoyer un MP sur le site. Mais je confirme que readthedoc est pas à jour.

_EDIT (gustavi) : MP envoyé_

**Comment by firm1** [comment]
synchro faite. Mais pour que ce soit automatique, il faut rajouter dans les hooks github la commande `curl -X POST http://readthedocs.org/build/zds-site` a lancer à chaque merge dans dev. Celle-ci lancera la compil de la doc

**Comment by pierre-24** [comment]
Ping @SpaceFox  ?

**Comment by SpaceFox** [comment]
Je regarde.

Si je comprends bien, le problème est que quand on met à jour nos fichiers le site n'est pas à jour, c'est bien ça ? Et c'est corrigé par le hook ?

**Comment by gustavi** [comment]
Exactement.

**Comment by SpaceFox** [comment]
Alors j'ai besoin d'infos supplémentaires (@firm1 par MP, ou au moins les accès qui me permettent de récupérer lesdites infos).

L'interface pour ajouter un webhook à Github me demande :
- Payload URL : je suppose que c'est http://readthedocs.org/build/zds-site
- Content-type (json ou URL encoded)
- Secret
- Quels types d'events lancent le hook ("push", "tout", "à la main") : je suppose que c'est "push".

**Comment by firm1** [comment]
La doc est ici :
http://read-the-docs.readthedocs.org/en/latest/webhooks.html#github

firm1

**Comment by SpaceFox** [comment]
OK merci, c'est ajouté.

**Comment by gustavi** [comment]
C'est bon ici @SpaceFox ?

**Comment by gustavi** [comment]
C'est réglé ici.
