### ISSUE TITLE
Ajouter la possibilité de pouvoir annuler une demande de validation

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1939]
Tout est dans le titre. Actuellement quand on envoie quelque chose en validation on ne peut pas faire marche arrière.

**Comment by poulp** [comment]
Et si un staff réserve la publication, toujours possibilité d'annuler ?

**Comment by Axylium** [comment]
Je ne pense pas. Car sinon pour eux ça risque de devenir à compliquer à gérer. Je pense notamment à ce genre de cas : « _j'ai réservé le tuto HTML, où est-il passé ?!_ ». 

Après, un système de notification côté staff, disant que le tutoriel a été retiré de la validation peut régler ce problème. Ou, dans le tableau de validation, le tuto rester quelques jours, avec la mention « _annulé_ » à côté de celui-ci.

Mais personnellement, je pense vraiment, qu'une fois que le tuto est réellement rentré dans le process de validation - _entendez par là, réservé par un staff_ - il doit y rester. Mais cela, n'est que mon avis !

**Comment by Eskimon** [comment]
je suis plus mitigé. pour moi un auteur devrait avoir.les.plein.pouvoir sur son tuto. du coup s'il estime que finalement ce qu'il a envoyé en validatio n'est pas au niveau de ce qu'il veut publier alors je vois pas de raisons qu'il ne puisse pas annuler une etape editoriale

**Comment by poulp** [comment]
Je suis l'avis d'Eskimon, un auteur fait ce qu'il veut de son tuto, mais en même temps je me met à la place de celui qui relit. Imaginons le mec il a déjà relu la moitié du document, l'auteur annule :/ faudrait peut être prévoir un genre de note/post-it accroché au tuto visible pour le staff.

**Comment by Axylium** [comment]
Ah, mais je suis entièrement d'accord sur le fait que l'auteur fait absolument ce qu'il veut de son tutoriel. Mais comme le dit @poulp je pense surtout au valido derrière, pour qui ça peut-être peinant de voir un tuto sur lequel il a passé du temps, disparaître comme cela.

Après, tout comme comme la validation, lorsque le membre retire son tuto on peut imaginer un textarea où il pourrait laisser un message à son validateur !

**Comment by poulp** [comment]
> Après, tout comme comme la validation, lorsque le membre retire son tuto on peut imaginer un textarea où il pourrait laisser un message à son validateur !

un mp de courtoisie ;)

**Comment by Eskimon** [comment]
Le valido est au service de l'auteur, pas le contraire...

Le MP (automatique) de courtoisie me parait une bonne idee par contre. Et si ca peut vous rassurer, rien n'est perdu, le staff peut toujours relire le tuto pour s'avancer dans le truc (oui un staff peut voir les tutos non public/beta)

**Comment by gustavi** [comment]
C'est codé (avec un MP et tout) ! Je suis sur les tests unitaires là.

**Comment by Eskimon** [comment]
Je ré-ouvre ce ticket.

Comme mentionnée dans le ticket #2071 , un souci subsiste. J'ai donc annulé ce commit dans la PR #2182 afin de ne pas bloquer la release 1.5.

Pour continuer cette feature, il faudra donc faire un cherry-pick du commit 0286f043ea8cb2e7c7d67c571f9acabe859f9cec puis corriger les soucis.
