### ISSUE TITLE
[Membre] Sanction temporaire

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#194]
Scénario :
- Afficher le profil d'un membre.
- Renseigner une sanction temporaire pour la lecture seule ou ôter une sanction (n'importe laquelle).
- Une erreur `DatabaseError` est lancée.

``` console
DatabaseError at /membres/profil/modifier/10
value too long for type character varying(15)
```

**Comment by firm1** [comment]
Ce bug vient du fait que dans le modèle donnée, le type de ban a été prévu pour [tenir sur 15 caractères](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/member/models.py#L190).

Pour résoudre ce bug, il suffit d'étendre la valeur max 15 à 80 dans le modèle de données. ne pas oublier de faire `python manage.py schemamigration member --auto` pour crée le fichier de migration du modèle avant de faire une PR.

**Comment by SpaceFox** [comment]
Attention : ce bug n'est pas reproductible avec SQLite...

**Comment by SpaceFox** [comment]
Avec MySQL c'est encore pire : la sanction s'applique mais on a pas l'historique :)

**Comment by SpaceFox** [comment]
En fait, y'a plusieurs trucs derrière ce bug :
1. modify_profile dans members/view.py n'est pas transactionnel (ça c'est rien, c'est juste une annotation à ajouter)
2. A l'heure actuelle, le champ Ban.type dans member n'est pas contraint - d'où le bug rencontré d'ailleurs.

La solution propre au point 2 nécessiterait pas mal de boulot, puisqu'il faudrait créer la contrainte et surtout bidouiller la vue pour afficher la "traduction" de la clé - à l'heure actuelle, le type de ban est directement la valeur en base.

@GerardPaligot , @firm1 , pensez-vous que ça vaille le coup de se faire chier à coller une contrainte là-dessus ? Ou on se contente d'agrandir le champ et ça marche direct ?

**Comment by firm1** [comment]
> Ou on se contente d'agrandir le champ et ça marche direct ?

Cette solution me semble la plus concialiante :)

**Comment by SpaceFox** [comment]
J'ai une erreur lorsque j'essaie d'utiliser la ProfileFactory de zsd.member.factories :

> TypeError: 'username' is an invalid keyword argument for this function

Vue l'heure je regarderai demain. Je préviens juste, que si quelqu'un a déjà eu et corrigé le problème qu'il me fasse signe, sinon tant pis, je me débrouillerai :)

**Comment by firm1** [comment]
Je viens de lire la description de la ProfileFactory et je me rends compte que je l'ai mal ecrite.
En fait elle ne doit pas heriter de UserFactory, car l'user est une foreign key de Profile.

En gros, il faut corriger le bébé.  Je vois bien comment le faire, faut juste que je chope une clavier et de l'internet et je te repare ça.

**Comment by firm1** [comment]
Fixé, Mergé, Pushé, Testé -> Je ferme
