### ISSUE TITLE
Une virgule en trop sur un sujet quand on met à jour sa bêta

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1940]
Pour reproduire : 
- Mettre tuto sujet en bêta
- Le modifier
- Mettre la nouvelle version en bêta
- Aller sur le sujet dédié dans le forum « Bêta »

Une image : http://i.imgur.com/dwKAqZG.png

**Comment by Situphen** [comment]
~~Je pense plutôt que c'est le pseudo qui est absent !~~ J'ai rien dit.
