### ISSUE TITLE
Décalage des icones sur la page d'aide aux tutoriels

### ISSUE THREAD

**Issue by poulp** [zestedesavoir/zds-site#1943]
Firefox 33/Ubuntu : 
![iconzep3](https://cloud.githubusercontent.com/assets/819246/5516319/499fe414-8896-11e4-92fb-83b918250df8.png)

**Comment by gustavi** [comment]
On peut avoir plus d'informations sur la résolution ?

**Comment by poulp** [comment]
euh entre temps j'ai maj firefox et j'ai plus le bug. je suis en 1920 x 1080

**Comment by gustavi** [comment]
Je pense que ça vient du cache. Bon, je ferme ici.
