### ISSUE TITLE
Tri sur la ZEP-03

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1944]
J'avais pas vu, mais ... C'est les plus anciennes demandes d'aide (ou autrement placé, les tutos les plus vieux) qui sont placé en premier sur la page d'aide issue de la ZEP-03. Pour moi, ce n'est pas le choix le plus intelligent ;)

À partir de là, plusieurs solutions s'affrontent : 
- Inverser l'ordre : les tutos les plus jeunes en premier
- Trier sur base de la date de dernière modification. Attention ceci dit aux effet pervers de cette méthode (il suffit en pratique de ne rien modifier du tout et d'appuyer sur le bouton pour que ça fonctionne et qu'on remonte premier).

Ceci dit, c'est pas critique.

**Comment by poulp** [comment]
Dans l'absolu je serais pour un tri dynamique sur les tutos. Mais en l'état je pencherais sur un inversement de l'ordre (jeune en premier).

**Comment by pierre-24** [comment]
A terme, je suis pour un tri dynamique tel qu'il soit :)

Après, faut voir aussi ce que les utilisateurs feront exactement de cet outil. Actuellement, et c'est logique, il n'y a que des tutos en béta, mais y faudra voir quand les auteurs demanderont effectivement de l'aide quelle tendance ressort.

**Comment by SpaceFox** [comment]
J'ai une PR mergée là-dessus, je peux considérer le ticket comme fermé ?

**Comment by Eskimon** [comment]
yep

**Comment by Eskimon** [comment]
C'est bizarre, en prod ca se comporte pas vraiment comme je le pensais... aurais-je fait une betise dans mon filtre ?

@pierre-24 tu en penses quoi (je te prends a partie car tu m'as aidé avec ta QA ^^ )

**Comment by pierre-24** [comment]
En effet, le comportement est un peu différent de ce à quoi je m'attendais. Ceci dit, je pense que le "problème" provient de l'inclusion de "update", auquel j'ai pas forcément pensé quand j'ai fait la QA: dès que tu fais une modif', `update` est mis à jour (ou en tout cas c'est ce que j'entend par "update" et ce qui est à peu près le cas dans le code, modulo l'état du module des tutos), du coup à mon avis, tu fausse le truc. Faudrait peut-être essayer avec `-pubdate` voire jouer avec `create_at` ([voir ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/models.py#L70)).

Dans tout les cas, c'est assez complexe à QA : la mini-liste de 5 ou 10 tutos que je peux créer pour une QA ne reflète en rien la réalité de la liste en ligne, qui varie au gré des utilisateurs. Et comme on a plus fait de MàJ prod <-> préprod depuis longtemps, c'est chaud à tester en bêta aussi ;)
