### ISSUE TITLE
Mauvais URL dans les RSS

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1948]
Sur la preprod, les lien des RSS pointent vers http://zestedesavoir.com.

Je n'ai cependant pas ce problème sur ma version de dev.

**Comment by Situphen** [comment]
Sur quelle page ?

**Comment by gustavi** [comment]
RSS tuto par exemple (http://preprod.zestedesavoir.com/tutoriels/flux/rss/)

**Comment by Eskimon** [comment]
J'ai pas compris, c'est quoi le souci ? (au cas ou, c'est la que ca se passe : https://github.com/zestedesavoir/zds-site/blob/3e6d292983f747ed4201a38f3cae44562105eff7/zds/article/feeds.py#L40)

**Comment by gustavi** [comment]
Va sur le flux et regarde l'URL d'un tuto. Il pointe vers la prod et non la preprod (alors que le tuto est sur la preprod).

**Comment by Eskimon** [comment]
Probablement du aux settings de la pre-prod ? Car voici comment l'url online est faite : https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/models.py#L127

**Comment by Eskimon** [comment]
Bon j'ai essaye de reproduire et j'ai une erreur 500... Je sais pas si c'est du a la 1.8 ou a la preprod car ca marche bien en prod...

**Comment by Situphen** [comment]
> ImproperlyConfigured: You're using the Django "sites framework" without having set the SITE_ID setting. Create a site in your database and set the SITE_ID setting to fix this error.

Donc c'est apparemment dû à https://github.com/SpaceFox/zds-site/commit/c4605fd1997e478128b6e1cdf831637862293832

**EDIT :** Oui, ça fonctionne avec le revert du commit !

**Comment by Eskimon** [comment]
Solution simple, il faut mettre:
- Aller dans le back-end Django
- Aller dans la rubrique `Sites`
- Changer le nom de domaine de la seule ligne présente pour y mettre `beta.zestedesavoir.com`

mais pour ca il faut etre super-user (ping @SpaceFox et @firm1 ;) )

**Comment by SpaceFox** [comment]
Manip faite, si quelqu'un peut confirmer que ça fonctionne ?

**Comment by sandhose** [comment]
Testé sur les tutos et sur les articles, en RSS et en ATOM : les liens mènent bien vers la bêta ; je ferme
