### ISSUE TITLE
Ajouter un RSS pour les tutoriels en bêta.

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1949]
Personnellement j'aimerai bien savoir quand un tuto est mis en bêta c'est pourquoi ajouter un flux RSS pour les tutos en bêta serait intéressant. C'est n'est pas très compliqué à faire.

**Comment by poulp** [comment]
+1

**Comment by Eskimon** [comment]
Est-ce que le feed "nouveaux sujets" dans le [fofo beta](https://zestedesavoir.com/forums/communaute/beta-zone/) ne ferait pas l'affaire par hasard ? (histoire d'éviter de redévelopper quelque chose qui existe...)

**Comment by Eskimon** [comment]
Je ferme ici, a mon avis une solution équivaudrait a réinventer la solution que je donne juste au-dessus.
