### ISSUE TITLE
[MP] Editer son message dans un MP

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#195]
Scénario :
- Se rendre dans une discussion privée (MP) où le dernier message est le votre et posté il y a moins de 15 minutes.
- Editer le message.
- Prévisualiser ou envoyer le message pour lancer une exception `MultiValueDictKeyError`.

``` console
MultiValueDictKeyError at /mp/message/editer
"Key 'text' not found in <QueryDict: {u'csrfmiddlewaretoken': [u'TqcjRrLcdekPdeWcrngGzc89zxU58d7W'], u'preview': [u''], u'last_post': [u'']}>"
```

**Comment by firm1** [comment]
Concernant ce bug il y'a deux choses : 
- On ne doit pas afficher le bouton éditer un message sur le dernier message qu'on a posté il y'a 15 minutes (condition d'affichage à rajouter dans le template)
- Dans le cas ou l'utilisateur se retrouve sur cette page parce qu'il connait l'url et les données en post en passant par curl par exemple, il faut, pour resoudre ce bug proprement, rajouter dans le forms.py une fonction clean pour déclarer invalide un post qui ne contient pas de variable 'text'. Car l'erreur ci-dessus est déclenchée parce que l'input de nom 'text' est disabled, et donc, lors de l'envoi du submit, celui-ci n'est pas posté.

**Comment by firm1** [comment]
Fixé et mergé. Je ferme
