### ISSUE TITLE
Pas d'icônes pour les chapitres d'un tuto

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1950]
comme reporté par [tit_tounou sur le forum](https://zestedesavoir.com/forums/sujet/563/des-vignettes-sur-les-chapitres-de-tuto/?page=2#p35650) : 

> Désolé de faire ressurgir le sujet mais la possibilité de mettre une icône du tutoriel existe, seulement les icônes ne s'affichent pas

Et il a raison: le champ existe, mais n'est pas employé par les templates. C'est tout bête à régler, du coup ;)

**Comment by Situphen** [comment]
@SpaceFox, il y a une raison pour ne pas afficher les images ou c'est juste un oubli ?

**Comment by SpaceFox** [comment]
Un oubli je pense.

**Comment by Eskimon** [comment]
> C'est tout bête à régler, du coup ;)

Ca demande quoi ? Un ajout dans les formulaires + une intégration dans le front ?

**Comment by pierre-24** [comment]
Le formulaire existe déjà, donc vérifier que le back balance bien l'info et l'intégrer dans le front :)

**Comment by Situphen** [comment]
Pensez à vérifier que les images ont bien une taille restreinte !

**Comment by Eskimon** [comment]
> Pensez à vérifier que les images ont bien une taille restreinte !

C'est pas le boulot de la lib' d'image qui génère les miniatures automatiquement ?

**Comment by gustavi** [comment]
Si si.

**Comment by Eskimon** [comment]
Je met ici un mot cle : EDIT (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
Non implémenté pour l'instant et aucune raison que ça le soit dans la
version 1 de la ZEP 12, tu peux enlever le tag.

2015-04-16 14:53 GMT+02:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
Ca marche :)

**Comment by pierre-24** [comment]
Effectivement. À réflexion, ceci touche au très délicat problème du versionage des images, donc c'est un gros truc, en fait.

**Comment by GerardPaligot** [comment]
Pire qu'un gros truc, cette issue demande un re-disign complet des sommaires pour tous les types de contenu, pour toutes les tailles d'écran. @sandhose tu confirmes ?

Est-ce que nous voulons vraiment afficher des images pour les chapitres ? Cela n'a jamais été utilisé depuis la toute première version de ZdS et cela n'a jamais gêné personne à part tit_tounou sur les forums.

**Comment by gustavi** [comment]
Et je pense même qu'il souhaitait plutôt faire remonter une incohérence qu'un manque.

**Comment by sandhose** [comment]
Je confirme que c'est pas simple comme évolution, et que clairement, c'est pas prioritaire

**Comment by Situphen** [comment]
Du coup, faut vérifier qu'il n'y a plus le champ "icone" de visible dans le formulaire des chapitres ?

**Comment by GerardPaligot** [comment]
Je serais pour retirer simplement ce champs de la base.

**Comment by artragis** [comment]
Il me semble que ça l'est déjà puisque les chapitres sont désormais 
uniquement gérés par git (et non plus par la bdd) et que l'objet 
Container n'a pas d'attribut "logo".

**Comment by GerardPaligot** [comment]
@artragis Ca serait cool. Dès que c'est confirmé, on peut fermer alors.

**Comment by artragis** [comment]
confirmé.
