### ISSUE TITLE
La date de dernière mise à jour des articles n'est pas toujours mise à jour

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1952]
Tout est dans le titre : quand on lit le code de la [fonction `edit()` des articles](https://github.com/zestedesavoir/zds-site/blob/dev/zds/article/views.py#L301), en fait, on ne met jamais à jour le champ `update` de la classe Article. Très simple à régler ;)

**Comment by pierre-24** [comment]
PS: auto-assignation, please :)

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé.
