### ISSUE TITLE
Impossible de mettre en bêta avec la bonne version sur la page d'historique

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1957]
Comme reporté sur la [préprod' par Vinc'](http://preprod.zestedesavoir.com/forums/sujet/1769/mise-en-beta-des-tutoriel/#p30837), il n'est pas (plus?) possible de mettre en bêta à partir de l'historique de version d'un tutoriel. La solution passe probablement par l'édition de [la ligne 102 du template history.html](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorial/tutorial/history.html#L102), ou, si cette ligne est correcte, se demander pourquoi ce n'est pas la bonne version qui est envoyée en bêta.

**Comment by pierre-24** [comment]
Petite idée qui m'est venue comme ça : des boites modales sont créées pour chaque ligne du tableau, mais appelées via un code unique `#activ-beta`. Donc en fait, c'est un bug front, pas back, et je parie qu'il suffit de rendre cet identifiant là unique pour chaque boite en lui collant le `sha_beta` en question.

EDIT: d'ailleurs, le code de la boite est répété deux fois, avec des `{% if %}`, y'aurai probablement moyen d'éviter des copies de codes.

**Comment by pierre-24** [comment]
Aller, hop, auto-assignation, je vais faire ça :)

**Comment by gustavi** [comment]
Corrigé ! Ça arrive en **1.5** ! Merci @pierre-24 !
