### ISSUE TITLE
Afficher le nom du forum dans les résultats de recherche

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1958]
Reporté via le [forum](https://zestedesavoir.com/forums/sujet/1995/afficher-le-nom-du-forum-dans-les-resultats-de-recherche/?page=1#p35684) : 

> Je viens d'utiliser la fonction recherche, et je me disais que dans le cas où les résultats sont des messages du forum, afficher le nom du forum dans les résultats pourraient être pas mal. Ça permettrait par exemple de distinguer aisément les résultats de la Dev Zone/Bugs et Suggestions de ceux des forums Programmation et Sites Web.

**Comment by A-312** [comment]
Je prends.

**Comment by ghost** [comment]
Finalement je ne prend pas il faut solr pour tester.

**Comment by gustavi** [comment]
Fixé dans #3215.
