### ISSUE TITLE
Mauvaise gestion d'erreur 404

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#1962]
Ici http://zestedesavoir.com/membres/?page=18 on a aucune erreur alors que la page n'existe pas, il faut lever une 404.

**Comment by gustavi** [comment]
Le premier bug est connu et déjà reporté. J'édite pour ne laisser que le second.

**Comment by Eskimon** [comment]
M'etonnerais pas que le second fasse parti des resolutions try/except recente aussi.

**Comment by gustavi** [comment]
C'est pas en preprod en tous cas.

**Comment by Eskimon** [comment]
Alors faudra aller fouiller par ici : https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/views.py#L72

**Comment by Situphen** [comment]
Le bug n'est pas résolu sur upstream/dev !

**Comment by SpaceFox** [comment]
Yep, pour moi c'est les 2 exceptions aux lignes 76 et 79 qui gèrent les cas
"proprement" alors qu'elles devraient se contenter d'envoyer chier avec une
404.

2014-12-22 16:52 GMT+01:00 Situphen notifications@github.com:

**Comment by gustavi** [comment]
Corrigé et mergé ! Merci @Situphen !
