### ISSUE TITLE
1.4 : Date en double

### ISSUE THREAD

**Issue by AmarOk1412** [zestedesavoir/zds-site#1967]
Je pense qu'une image vaut mieux qu'une explication.  
Voici ce que l'on peut trouver pour les messages du forum et les commentaires :  
![capture du 2014-12-22 20 18 11](https://cloud.githubusercontent.com/assets/1888628/5529720/cc4ac5c8-8a17-11e4-9ab5-74e8235946d1.png)  
L'heure de post est affichée 2 fois en 2 format différents

**Comment by SpaceFox** [comment]
Tu es tombé pendant que le front était partiellement buildé. Vérifie mais normalement c'est OK.

**Comment by Axylium** [comment]
À fermer alors, non ?

**Comment by SpaceFox** [comment]
J'attends qu'il confirme.

**Comment by AmarOk1412** [comment]
En effet. Du coup je ferme.
