### ISSUE TITLE
Encore des catégories vides

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#1968]
Comme [reporté par Vayel sur le forum](https://zestedesavoir.com/forums/sujet/2004/menu-deroulant-vide-dans-tous-les-tutoriels/?page=1#p35919), sur la page "tout les tutoriels", quand on clique sur une catégorie, elle est vide et du blanc apparaît.

Bref, comme #1916 et #1934. Bon... Qui a changé ça, sérieusement, ça fait 3x, là.

**Comment by SpaceFox** [comment]
git blame ?

Le 22 décembre 2014 21:09, Pierre Beaujean notifications@github.com a
écrit :

**Comment by poulp** [comment]
ça vient de moi quand j'ai modifié les templatetags pour avoir les catégories de tuto ordonnées

**Comment by pierre-24** [comment]
Ah, ok. Bon ... Je vais tenter de faire le tour de manière exhaustive pour être sur de plus revoir le bug.

**Comment by poulp** [comment]
Pour cette issue ça vient du template tutorial/index.html, logiquement ça concerne tout les templates qui ne se base pas sur le template de base pour la sidebar catégories des tutoriels
