### ISSUE TITLE
Impossible de publier un tuto

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#197]
Actuellement, en assayant de publier un tuto, on tombe sur une erreur 403.

Piste de résolution : Le champs csrf n'est pas mentionné.

**Comment by GerardPaligot** [comment]
Je sais, ce n'est pas tres explicite,, mais je m'en occupe deja sur l'issue #187.

**Comment by GerardPaligot** [comment]
Je confirme m'en occuper dans l'issue 187. Je viens de l'implémenter. Je ferme donc cette issue.
