### ISSUE TITLE
Impossible de se connecter via les réseaux sociaux

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1972]
Quand j'essaye de me connecter, je suis ré dirigé vers une adresse au nom de "zdsappserver".

Par ailleurs côté Sentry il y'a un message qui me fait penser que les tables n'ont pas été générées. 

```
ProgrammingError: (1146, "Table 'zdsdb.social_auth_usersocialauth' doesn't exist")
```

**Comment by SpaceFox** [comment]
> Quand j'essaye de me connecter, je suis ré dirigé vers une adresse au nom de "zdsappserver".

Si quelqu'un a la moindre idée d'où ça peut venir...

> Par ailleurs côté Sentry il y'a un message qui me fait penser que les tables n'ont pas été générées.
> 
> ```
> ProgrammingError: (1146, "Table 'zdsdb.social_auth_usersocialauth' doesn't exist")
> ```

C'est pour le moins curieux, parce que je n'ai eu aucune erreur à la migration des tables.

Comme pour le reste, si la correction n'est pas prête ce soir... quelqu'un d'autre devra la déployer ou ça attendra le 5 janvier.

**Comment by DevHugo** [comment]
La connection à partir de facebook, ne fonctionne pas non plus.

Erreur est la suivante : "Application non configurée: Les développeurs de cette application ne l’ont pas correctement configurée pour se connecter à Facebook.".

Et si on trace, les requêtes HTTP, on s'apercoit que la requête est : https://www.facebook.com/dialog/oauth?state=ZgVqhGAiV19xFIEi9xp2NL1PIkgzt1aC&redirect_uri=http://zdsappserver/complete?facebook=&redirect_state=ZgVqhGAiV19xFIEi9xp2NL1PIkgzt1aC&client_id=397505420415808.

**Comment by DevHugo** [comment]
1. Si tu pouvais jeter un coup d'oeil à la variable: LOGIN_REDIRECT_URL dans le settings.py. Sachant qu'on a pas le droit de mettre des variables, faut que la chaine soit mise directement.
2. Pour google, faudrait changer l'adresse de redirection dans le google app console, de http en https.

Petite aide, même si tu remplace l'adresse zdsappserver par zestedesavoir.com, tu tombe sur une erreur 500. Donc c'est possible, que ça soit les tables.

**Comment by pierre-24** [comment]
Ce que tu dis est intéressant, mais il faudrait regarder qu'elle est la valeur de cette variable en prod', parce que c'est pas pareil que dans le `settings.py` normal (peut-être que cette variable n'est pas touchée, mais faudrait pouvoir le checker).

**Comment by SpaceFox** [comment]
On a encore quelque chose ici ? Ça ne fait pas doublon avec #1903 ?

**Comment by firm1** [comment]
Bon, je viens de passer sur la preprod et la prod, c'était bien un problème infra. J'ai corrigé la conf de nginx afin de ne plus exposer le nom interne, et maintenant ça marche.

Je ferme donc.
