### ISSUE TITLE
Les boutons d'actions dans la sidebar ne sont pas ajaxifiés sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1973]
Quand (depuis mon mobile) je follow/unfollow un topic ou que je le marque en résolu, j'ai droit a une page qui se recharge. 

Sur Chrome comme sur Firefox.

Le bouton citer lui marche très bien

**Comment by ghost** [comment]
Je prends.

**Comment by ghost** [comment]
Le problème vient de la PR : #2226. Qui a été partiellement réalisé.

**Comment by ghost** [comment]
J'ai corrigé le problème pour : 
- Marquer comme résolu
- Suivre ce sujet
- Être notifié par courriel

Pas besoin d'être sur mobile, suffit de diminuer la largeur de la page.

**Comment by firm1** [comment]
Je ré-ouvre cette issue car la correction ne prend pas en compte un cas.

Scénario:
- Depuis mon mobile, je vais sur un sujet que je ne suivais pas
- Je vais dans la sidebar
- Je clique sur "Etre notifié par mail"
- **Problème : le bouton du dessus me demande encore si je veux suivre le sujet alors que la demande de notification par mail signifie qu'on suit déjà le topic.**

Le comportement de l'ajax sur mobile n'a donc pas le meme comportement que sur pc.

**Comment by ghost** [comment]
Je ne comprends quel "bouton du dessus" ?

**Comment by Eskimon** [comment]
> Je ne comprends quel "bouton du dessus" ?

Lorsqu'on suit par email, le bouton "suivre ce sujet" doit automatiquement etre clique aussi. Et si on on suit pas email, lorsque l'on clique sur "arreter de suivre le sujet" le suivi par email doit etre arrete aussi.

J'ai mal QA, je n'avais pas pense a l'implication de l'un avec l'autre.

**Comment by ghost** [comment]
> J'ai mal QA, je n'avais pas pense a l'implication de l'un avec l'autre.

C'est surtout ma faute. ^^"

**Comment by firm1** [comment]
C'est résolu
