### ISSUE TITLE
[Hotfix v1.4] Aperçu des commentaires des articles et tutoriels impossible

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#1980]
Lorsque vous créer un commentaire sur un tutoriel ou un article et que vous voulez voir l'aperçu, rien n'apparaît ! (Problème similaire à #1915)

**Comment by gustavi** [comment]
Un peu plus de description ça ne peut pas faire de mal.

**Comment by pierre-24** [comment]
Fixé.
