### ISSUE TITLE
Superposition date et boutons d'actions de ses messages en petite résolution d'écran

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#1987]
[Reporté sur le forum par Vayel.](https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=25#p36164) Lorsque vous êtes connecté et que vous avez une résolution d'écran assez faible (environ 1000px), la date et les boutons d'actions ("citer", "signaler"...) se superposent sur les messages que vous avez écris.

Pour reproduire le bug :
- Aller sur son profil puis "Messages postés"
- Choisir un message avec une grande date (par exemple "mardi 23 décembre 2014 à 12h34")
- Cliquer sur le lien pour y aller
- Constater quelque chose comme https://zestedesavoir.com/media/galleries/972/877b29a8-2a9d-4179-bb33-3b203e7fe50a.png

**Comment by gustavi** [comment]
Encore une fois il faut passer sur une petite date. Plein d'exemples dans le code. Peut-être mettre ça dans un tempalte dans misc.

**Comment by gustavi** [comment]
Corrigé ! Merci @Situphen !
