### ISSUE TITLE
Mettre un lien pour partager sur Diaspora*

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#1990]
[Demandé par Dominus Carnufex sur l'article de la v1.4](https://zestedesavoir.com/articles/133/zds-passe-en-version-14/?page=1#p36216) :

> Serait-il envisageable d'intégrer diaspora\* dans la liste des réseaux sociaux vers lesquels partager un tuto ?

Je propose d'utiliser [cet outil](https://sharetodiaspora.github.io/about/) qui est open-source ([et sur GitHub](https://github.com/sharetodiaspora/sharetodiaspora.github.com)).

**Comment by gustavi** [comment]
_Rien dit_

**Comment by SpaceFox** [comment]
https://zestedesavoir.com/articles/133/zds-passe-en-version-14/?page=1#p36248
