### ISSUE TITLE
Lecture zen non centrée, problème de marges

### ISSUE THREAD

**Issue by poulp** [zestedesavoir/zds-site#1992]
Vu sur Firefox34/Ubuntu :

![zen](https://cloud.githubusercontent.com/assets/819246/5550641/dc1b7c74-8baa-11e4-971e-2de2a87f406f.png)

**Comment by Situphen** [comment]
Normalement ce sera corrigé dans la v1.5 par la PR #1837, non ?

**Comment by sandhose** [comment]
Je confirme
