### ISSUE TITLE
Erreur 500 lors de consultation de l'historique d'un article

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#1994]
J'ai une erreur 500 sur la consultation de l'historique des versions d'un article en redaction. Arius a eu le problème aussi.

Le bug semble être arrivé avec la 1.4

**Comment by gustavi** [comment]
Il semblerai que c'est le `{% crispy formJs %}` qui fait planter le truc. 

D'ailleurs @firm1 c'est toi qui l'a introduit. Une raison particulière ?
