### ISSUE TITLE
Utiliser un template lors de la prévisualisation en AJAX

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#1995]
Actuellement, lors de la prévisualisation en AJAX, le back ne retourne que le texte en HTML sans les balises qui l'entoure ([ici pour le forum](https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/views.py#L488)) et les balises HTML sont ancrées en dure dans le JS ([ici](https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/action-ajax.js#L146)). Le problème est qu'il n'y a pas d’internationalisation ici et que si on change les templates, il faut changer le JS. Ce qu'il faudrait, c'est que le back renvoie tout l'HTML (à partir de [ce template](https://github.com/zestedesavoir/zds-site/blob/dev/templates/misc/previsualization.part.html)) et que le JS ne fasse que l'afficher !

**Comment by sandhose** [comment]
A noter que la prévisualisation se fait sur `/forums/messages/nouveau?sujet=XXX`, ce qui est... pas approprié (pour pas dire complètement dégueu :x )

J'aurais bien vu un truc genre `/api/markdown/render`, mais ça implique que l'API "de base" soit en place
