### ISSUE TITLE
Ne pas référencer le téléchargement d'un tutoriel

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#1999]
Le problème reporté sur le [forum](http://zestedesavoir.com/forums/sujet/2041/mettre-un-no-followno-index-pour-le-telechargement-de-tutoriel/) : 

> Bonjour,
> 
> En cherchant sur Google un bug dans mon code, il m'a proposé un tutoriel de votre site :
> 
> ![Image utilisateur](http://image.noelshack.com/fichiers/2014/52/1419594710-capture.jpg)
> 
> Donc en voulant cliquer pour voir le dit tuto ça m'a DL un html, ce que je trouve pénible. Donc je propose que les robots ne référencent pas ces pages vu qu'elles sont déjà référencé sur le site en lui même.
> 
> Merci
> Source:[hotgeart](http://zestedesavoir.com/forums/sujet/2041/mettre-un-no-followno-index-pour-le-telechargement-de-tutoriel/?page=1#p36432)

**Comment by Situphen** [comment]
C'est pas vraiment de l'infra mais plutôt du back. Il y a deux moyens de faire ça, soit avec le robots.txt, soit, la méthode je pense la plus adaptée, avec des attributs sur les liens.

**Comment by Situphen** [comment]
@pierre-24 @artragis : les urls de téléchargements ont été changées par la ZEP 12 ? :)

**Comment by pierre-24** [comment]
On a un ticket pour ça, donc c'est au programme :)
