### ISSUE TITLE
LaTeX et la balise « secret » ne passent pas lors de la prévisualisation

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#2000]
Reporté sur le [forum](http://zestedesavoir.com/forums/sujet/2045/apercu-et-latex/?page=1#p36471) : 

> Je ne sais pas si c'est normal, mais il est impossible d'avoir un aperçu de ce que l'on écrit pour faire des formules de maths (j'ai cru comprendre que c'était LaTeX), alors que le message posté fonctionne entièrement bien entendu.
> 
> ![](http://image.noelshack.com/fichiers/2014/52/1419621804-sans-titre.png)
> 
> Et en même temps, la balise secret de fonctionne pas dans l'aperçu (je m'en suis rendu compte en rédigeant)
> 
> ![](http://image.noelshack.com/fichiers/2014/52/1419621934-sans-titre.png)
> Source:[Ricocotam](http://zestedesavoir.com/forums/sujet/2045/apercu-et-latex/?page=1#p36471)

**Comment by ghost** [comment]
Je prends.

**Comment by Eskimon** [comment]
Laissons ouvert il reste **prévisualisation du latex** a faire dans ce ticket

**Comment by Eskimon** [comment]
Nickel, si je dis pas de betise on a un apercu completement fonctionnel maintenant :)
