### ISSUE TITLE
Rendre les tableaux et les formules MathJax responsives

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2001]
Si l'on prend [ce tutoriel](http://zestedesavoir.com/tutoriels/335/creez-des-applications-pour-android/420/les-bases-indispensables-a-toute-application/2137/les-ressources/) en exemple, sur mobile en mode portrait (Nexus 5 avec Firefox 34 pour moi), les tableaux créent une marge noire à droite.

![screenshot_2014-12-27-16-02-07](https://cloud.githubusercontent.com/assets/6664636/5561604/e13eb3ee-8de2-11e4-98f3-eb5113070dee.png)

Ce problème est aussi présent avec les formules MathJax.

**Comment by cgabard** [comment]
[En cours de merge](https://github.com/zestedesavoir/zds-site/pull/2291)

**Comment by Situphen** [comment]
Ça a été corrigé et mergé donc je ferme ! Merci @cgabard :)
