### ISSUE TITLE
Certaines couleurs sont stockées en dur dans le code scss

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#2003]
Par exemple la couleur du hover de `.dropdown-link-all` (_all-support.scss ligne 201). Il faudrait les externaliser.

La liste de ce que j'ai trouvé qui m'a gêné : 
- `.dropdown-link-all` (bordure + fond)
- `.home-full-description-text h2` (bordure)

**Comment by pierre-24** [comment]
ça a déjà été mentionné quelque part par @sandhose, si je ne m'abuse (la PR noël, si je dis pas de bétises).

**Comment by ghost** [comment]
Facile à faire mais il faut choisir quels noms de variable utiliser, pour qu'ils soient claires et correspondent entre eux.

**Comment by Situphen** [comment]
J'ai commencé à faire un peu le ménage, j'ai tout mis sur [cette branche](https://github.com/Situphen/zds-site/tree/fix-2003-variabilize-scss-colors) et vous pouvez vous l'avancée du travail [ici](https://github.com/Situphen/zds-site/compare/fix-2003-variabilize-scss-colors).

Pour l'instant pour faciliter le travail plus tard, j'ai mis toutes les valeurs hexadécimal en majuscule (par exemple, `#fff` est devenu `#FFF`) et au minimum (par exemple `#CCCCCC` est devenu `#CCC`).
En ce qui concerne la variabilisation, on a quelques variables (par exemple `$color-danger`) qui ne sont pas tout le temps utilisées, c'est fini ! Merci `sed` !

Il reste beaucoup de travail à faire. Mais comme l'a dit @A-312, le plus compliqué sera surement de trouver des noms clairs !

@gustavi : Pour le fork, tu as variabilisé de ton côté certaines couleurs ou tu les as juste remplacées dans le code ?

**Comment by gustavi** [comment]
J'ai tout remplacé comme un gros dégueux ;) De tout façon vu comme les membres du fork ont pas l'air d'avoir envie de se sortir les doigts, ça va rester comme ça un moment dont t'inquiète pas !

**Comment by GerardPaligot** [comment]
Je sais que beaucoup de refacto se sont lancés côté front depuis 1 an (quasi jour pour jour maintenant). Qu'est ce qu'en disent notre dev front @sandhose ?

**Comment by sandhose** [comment]
C'est le genre de refacto qu'est pas prioritaire _pour le moment_, mais qui arrivera un jour. 

En cours, y'a l'éditeur, PostCSS, puis dans un futur plus ou moins lointain, tout passer sur browserify, eslint pour linter le front, des vrais tests pour le front, et remplacer gulp par des scripts npm/un makefile. Du coup ouais, peut-être que la variabilisation des couleurs arrivera post-PostCSS (#3305), mais c'est pas prioritaire

**Comment by Situphen** [comment]
En fait, le plus dur avec la variabilisation des couleurs, c'est de trouver quel nom leur donner amha. J'ai pas trouvé de méthode magique sur Internet, faudrait regarder dans d'autres projets open-sources comment ils font.

**Comment by orandin** [comment]
À défaut d'avoir une nomenclature pour les variables, je propose cette forme :

`color- nom du composant - attribut(s) CSS`

Ce qui donnerait par exemple pour les couleurs issues du composant `accessibility`, ceci :

```
$color-accessibility-background: #062E41;
$color-accessibility-a-color: #EEE;
$color-accessibility-a-hover: #FFF;
```

On obtient des variables verbeuses, mais de ce fait parlantes.

**Comment by Situphen** [comment]
Sauf que les couleurs des composants sont réutilisés un peu partout donc ça le fait pas. Mais c'est vrai faut qu'on avance sur ce sujet. Faudrait voir comment les autres projets open-source font.

**Comment by orandin** [comment]
Rien ne nous empêche de réutiliser les couleurs à la manière de Bootstrap : 
https://github.com/twbs/bootstrap/blob/master/less/variables.less#L664

Je trouve cette méthode intéressante. Tout est à un seul endroit. La modification des couleurs de façon ciblée sur un composant par exemple est plus simple. Néanmoins, en contrepartie, on se retrouve avec beaucoup de variables verbeuses _(gros fichier)_. 

Par contre, coté AngularJS avec Material Design et le framework Foundation, ils ont fait le choix de définir des variables globales puis des variables plus spécifiques aux composants en début de fichier : 

_Material Design_
- https://github.com/angular/material/blob/master/src/core/style/variables.scss
- https://github.com/angular/material/blob/master/src/components/menu/menu.scss

_Foundation_
- https://github.com/zurb/foundation-sites/blob/develop/scss/_global.scss
- https://github.com/zurb/foundation-sites/blob/develop/scss/components/_accordion.scss

Leur méthode met l'accent sur la modularité.

**Comment by Situphen** [comment]
Je suis pour faire ça comme Fondation !

**Comment by A-312** [comment]
Oui c'est assez simple de commencer par créer des variables pour les couleurs du sites, puis de les affecter à des variables pour chaque éléments spécifiques. Ca ajoute un plus pour l'aspect "forkable" de zds.

**Comment by nils-van-zuijlen** [comment]
Et on ne pourra pas raisonnablement ajouter de thème sombre (#3372) tant que toutes les couleurs n'auront pas été mises dans des variables.
