### ISSUE TITLE
Problèmes d'adresses IP dans la documentation

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#2006]
Visiblement une erreur c'est glissée dans cette page : https://github.com/zestedesavoir/zds-site/blob/dev/doc/deploy.md#param%C3%A8tres-sp%C3%A9cifiques

**Comment by pierre-24** [comment]
?!?

**Comment by GerardPaligot** [comment]
Pour rendre plus explicite le problème, les IPs sur la page de documentation citées par @gustavi affiche des IP v4 et v6 pour le serveur de pre-prod et prod erronées.
