### ISSUE TITLE
AJAXifier l'édition des messages 

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#2008]
Reporté sur le [forum](http://zestedesavoir.com/forums/sujet/2067/ajaxifier-ledition-des-messages/?page=1#p36650) : 

> Je pense qu'il serait agréable de pouvoir éditer un message sans que la page ne se recharge. C'est moins brutal et ça permet de ne pas trop perdre le fil de la conversation. Surtout quand c'est pour corriger une faute d'orthographe.

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis près d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.

**Comment by Eskimon** [comment]
Je trouve dommage de fermer des tickets-idées. A mon avis le souci ne vient pas de l'intérêt, mais plutôt de la priorité des choses.

**Comment by Situphen** [comment]
Surtout du quotient `intérêt/difficulté technique` !
