### ISSUE TITLE
Plus d'informations sur Debian-backports dans la doc

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#2009]
Un lien vers la doc d'installation serait un minimum (http://backports.debian.org/Instructions/), quelques instructions seraient encore mieux.

La page concernée : https://github.com/zestedesavoir/zds-site/blob/dev/doc/gulp.md

Par ailleurs, la méthode proposé dans la doc de ZDS semble **fausse** et **ne fonctionne pas**.

J'ai du utiliser `curl -sL https://deb.nodesource.com/setup | bash -`.

**Comment by SpaceFox** [comment]
Nop, toute la partie "debian" de la doc est fausse en fait...

2014-12-28 9:58 GMT+01:00 Laville Augustin notifications@github.com:

**Comment by pierre-24** [comment]
Complètement à coté de la place, je confirme. Au delà de ça, est ce que c'est le rôle de ZdS de décrire la procédure d'installation de node pour chaque Linux ? (vraie question).

**Comment by gustavi** [comment]
@pierre-24 sur Debian je pense que c'est une bonne chose car c'est là dessus que tourne la prod donc si on fait un fork (ce que j'ai fais) on aura tendance à choisir Debian. Pour le reste je suis d'accord de dire que c'est inutile. Debian + Ubuntu ça me semble bien.

**Comment by Eskimon** [comment]
Je ping ici pour savoir "concrètement il faut quoi ?"

**Comment by pierre-24** [comment]
corriger la partie "front" de la doc d'install linux, si je me souviens bien ?!?

**Comment by Situphen** [comment]
Up ! [La documentation d'installation du _front-end_ sur Debian](http://zds-site.readthedocs.org/fr/latest/install/frontend-install.html#debian) est correcte ? Si non, quelles commandes faut-il utiliser ?

**Comment by pierre-24** [comment]
La dernière fois que j'ai réinstallé toute la stack (le mois passé), ça marchais toujours :)

(sinon, tu m'aurais entendu, crois moi :p)

Évidement, ça t'installe une version antédiluvienne et un `sudo npm install -g npm` est d'usage.

**Comment by Situphen** [comment]
> Évidement, ça t'installe une version antédiluvienne et un `sudo npm install -g npm` est d'usage.

C'est le cas sur tous les OS et c'est aussi dans la documentation (un peu plus bas) en gras ! :)

**Comment by Eskimon** [comment]
Up, faut-il garder ce ticket ouvert ?

**Comment by SpaceFox** [comment]
Up ?

**Comment by gustavi** [comment]
Faut que quelqu'un avec Debian sous la main test.

**Comment by GerardPaligot** [comment]
Qui a une debian sous la main qui pourrait vérifier que tout semble correct dans la doc ?

**Comment by Situphen** [comment]
Si quelqu'un compte vérifier ça, autant le faire directement sur ma PR #3370 de mise à jour de la doc d'installation !

**Comment by GerardPaligot** [comment]
La PR a été mergée mais cette issue est restée ouverte. Quelqu'un peut me confirmer que tout est ok ?

**Comment by gustavi** [comment]
Lors de ma dernière installation sous Debian c'était OK.
