### ISSUE TITLE
Mise à jour vers python-markdown 2.4

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#201]
Une nouvelle version de python-markdown est sortie. Elle apporte entre autre l'option de mise en surbreillance des lignes de codes. Ce baser sur cette version stable serait dès lors plus safe. Pour autant nous ne pourrons toujours pas nous permettre de rester sur une version upstream. Le support d'intervalle de surbrillance ainsi que le début de numérotation, ne peuvent pas vraiment être implémentés sans toucher aux sources.

**Comment by firm1** [comment]
Mon avis sur la question est que Python-markdown n'étant pas trop éloigné
de notre fonctionnement actuel, on peut rester sur notre logique de patch
spécifique.

C'est à dire, quand Christophe aura du temps de libre, regarder si leur
nouvelle feature (surbrillance) est compatible avec la notre et si possible
l'intégrer chez nous et donc de recréer un patch se basant sur la dernière
version de python-markdown (pour profiter des autres MAJ).

Je pense donc que le moment de la séparation viendra clairement le jour ou
il faudra faire du markdown-zds vers pandoc. Là on aura assez de légitimé
pour se séparer de python-markdown et en faire un projet opensource dans un
dépot différent de zds mais sous la même organisation github.

Voili, voulou pour mon avis.

Le 17 mars 2014 13:08, Christophe Gabard notifications@github.com a écrit
:

**Comment by cgabard** [comment]
J'ai pas été très clair je m'en rend compte. En realité leur implémentation de la mise en surbrillance, est la notre. C'est la première raison qui m'a fait utiliser une version "depuis source" : cette fonctionnalité était déjà implémenté mais pas dispo dans la version dispo avec pip. Avec cette version 2.4, c'est maintenant le cas.

Ensuite on ne peut toujours pas se passer de patch pour les probs d'intervalles et de start_numbering. Mais au lieu de checkouter un hash particulier avant d'appliquer les patchs, je vais pouvoir le faire depuis le tag de la v. 2.4.

Et au passage je vais regarder si on ne peut pas le faire directement depuis pip/disutils du coup, ça nous eviterais de dl tout le dépot.

**Comment by firm1** [comment]
Ok, tout va bien alors. On te laisse suivre ce dossier tranquillement et de
faire les PRs qui vont bien.

Le 17 mars 2014 15:17, Christophe Gabard notifications@github.com a écrit
:

**Comment by SpaceFox** [comment]
Et puis, ça a un côté assez classe de faire une MAJ d'une lib pour pouvoir
récupérer ses propres modifications :)

**Comment by cgabard** [comment]
En fait ce ne sont pas nos modifs celles-ci, les notre sont en attente car il voudrait que je le propose à pygment avant. Mais le truc c'est que c'est loin d'etre aussi simple que ça donc j'ai un peu laissé tombé.

**Comment by cgabard** [comment]
Cela a été fait dans une PR précédente, je ferme
