### ISSUE TITLE
Documenter l'installation et la configuration de Sorl

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#2010]
Dans le doc on a seulement « ??? » (https://github.com/zestedesavoir/zds-site/blob/dev/doc/deploy.md#solr)

**Comment by poulp** [comment]
J'imagine qu'il faut reprendre le fichier https://github.com/zestedesavoir/zds-site/blob/dev/doc/install-solr.md

**Comment by gustavi** [comment]
Oh oui, je ne l'avais pas vu celui là ! Merci @poulp !

**Comment by pierre-24** [comment]
Z'en profiteriez bien pour le sortir et aller taper ça sur SPHINX, nan ? :p

**Comment by firm1** [comment]
Cette issue est maintenant corrigée.

**Comment by SpaceFox** [comment]
Là aussi, il manque une PR mergée qui correspond à la fermeture de ce ticket.

D'autre part, attention aux milestones : si ça correspond à une PR qui était déjà mergée depuis un moment, il est possible qu'en fait ce soit sur la v1.6.

**Comment by firm1** [comment]
ça a été fixé via la #2187

Et en effet, fait en 1.6
