### ISSUE TITLE
Lien d'adhésion toujours présent même si abence d'association

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#2013]
Dans `base.html` on a une condition sur la page « Association » mais il en manque une sur « Adhérer ».

**Comment by firm1** [comment]
Je réouvre cette issue car le lien Adhesion est toujours présent sur cette page `http://beta.zestedesavoir.com/pages/` que se soit en mode déconnecté ou s'il n'y a pas association derrière.

**Comment by Eskimon** [comment]
Merge et deplace en v1.8
