### ISSUE TITLE
Ajout d'un bouton « Envoyer et continuer d'éditer »

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#2015]
Une fonctionnalités qui me manque beaucoup : celle de pouvoir envoyer une modification sur un article ou un tutoriel tout en continuant d'éditer cet article ou ce tutoriel. Simple redirection sur la page d'édition, ça me semble assez facile à mettre en place et très utile quand comme moi on "sauvegarde" son travaille ç chaque modification de paragraphe.

**Comment by gustavi** [comment]
En fait c'est plus complexe que ça n'en a l'air, il faut toucher à cripsy.

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis près d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.
