### ISSUE TITLE
Condition in tutorial/edit_extract

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#202]
Hello,

Je suis un peu embêté. Je suis dans le refactoring des mini-tutos et je suis tombé sur une [condition](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/tutorial/views.py#L1559) que je comprends tout simplement pas. :)

Si @firm1 pouvait m'éclairer, ça serait top parce que c'est vraiment vraiment moche !

**Comment by GerardPaligot** [comment]
Ok, je pense l'avoir compris mais il fallait relever la chose et j'aimerais confirmation de ce que je pense.

**Comment by firm1** [comment]
Ahem.

le code en lui même c'est celui-ci

``` python
b = extract.chapter.part
if b and (not request.user in extract.chapter.part.tutorial.authors.all())\
```

Il signifie en gros : si il s'agit de l'extrait d'un big tuto et que l'utilisateur qui travaille est l'utilisateur en cours .... alors

**Comment by firm1** [comment]
la booléenne `b` est surtout là pour s'assurer que la condition n'explose pas quand c'est du mini tuto.

**Comment by GerardPaligot** [comment]
Un boolean ? euh ... quand celui qui a écrit les lignes de code ne les comprend même plus, ça devient grave. ^^

Voici comment j'ai compris ta "condition" :

``` python
# Récupère la partie du chapitre.
b = extract.chapter.part
# Si il existe une partie pour le chapitre, on se trouve dans un big tuto 
# donc on regarde si l'utilisateur se trouve dans les auteurs du tutoriel
# cette partie.
if b and (not request.user in extract.chapter.part.tutorial.authors.all())\
# Sinon, s'il n'existe pas une partie, c'est qu'on se trouve dans un mini
# tuto donc on vérifie que l'utilisateur se trouve dans les auteurs du tutoriel
# du seul et unique chapitre d'un mini tuto.
        or not b and (not request.user in extract.chapter.tutorial.authors.all()):
    raise Http404
```

**Comment by firm1** [comment]
> Un boolean ? euh ... quand celui qui a écrit les lignes de code ne les comprend même plus, ça devient grave. ^^

Booléen parce que je l'utilise surtout pour dire "si b existe", donc il joue plus un rôle de booléen ici. C'est la magie pythonnesque.

Mais oui, tu as bien compris le code. Après je t'autorise à le modifier de façon plus lisible. Mais bon, ça me semblait plutot clair

**Comment by GerardPaligot** [comment]
Ca te semble plutôt clair ? O.O

Non, non, il y a plusieurs choses qui ne vont pas dans cette condition :
- Déjà tu nommes pas ta variable b, c'est juste aberrant. C'est un peu comme définir une variable java `boolean boolean`. Bon, on est d'accord on ne pourra pas le faire parce que `boolean` est un mot clé réservé mais l'idée est la même.
- Quand tu écris une condition de 3 lignes, tu as 2 solutions : tu simplifies ta condition ou tu la commentes. Dans le second cas, il faut pouvoir sérieusement motiver son choix de laisser une telle condition.

Bon, c'est un détail. J'ai réussi à comprendre la condition mais je trouve ça vraiment moche comme condition et je me devais de le soulever. :)

**Comment by firm1** [comment]
:)

boarf, c'est toujours plus simple de lire/modifier quand ça marche déjà.
Dis toi surtout que c'est le genre de chose que j'ai modifié tellement de fois que quand ça marche (oui parce que ça ne marche pas du premier coup, ni du deuxième), je ne me soucie pas forcément du reste, surtout quand tu n'est pas sur que ça ne va pas changer demain, parce qu'on est pas à l'abri d'une surprise de lib.

**Comment by GerardPaligot** [comment]
Mouais ... On va dire que chacun code un peu comme il veut mais faut garder à l'esprit que c'est quand même un projet communautaire. Il faut au moins commenter.

Sur ce, je peux fermer l'issue.
