### ISSUE TITLE
La position des forums n'est pas gérée

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#2022]
Actuellement, on peut spécifier une position pour un forum or ce n'est pas géré dans le code.

Il faut rajouter `.order_by('position_in_category')` ligne 19 de `topbar.py` (ce fichier est juste immonde) et un peu plus bas.

**Comment by gustavi** [comment]
J'ai réussi à fixer ça avec des tonnes de scotch mais faut revoir l'ensemble je pense. http://paste.awesom.eu/gbid

**Comment by poulp** [comment]
doublon avec #1822
