### ISSUE TITLE
[RFC] Ajouter un bot IRC pour le chat Zest de savoir

### ISSUE THREAD

**Issue by Nek-** [zestedesavoir/zds-site#2024]
Hello,

Ce n'est pas vraiment un problème en tant que tel, évidemment. Mais l'idée c'est de savoir si ça vous dit d'intégrer un bot à l'application ZdS qui fonctionnerait sur IRC, on pourrait récupérer des infos du site etc.

Le but ici est d'avoir l'aval de l'équipe de ZdS et ensuite de définir quelles pourraient être les fonctionnalités du bot.

**Comment by gustavi** [comment]
J'en avais commencé un qui qui listait les nouvelles issues de GH ainsi que les nouveaux sujets de B&S et DEv Zone sur `#zds-dev` et un qui listait les nouveaux artciles/tutos sur `#zestedesavoir`.

**Comment by Nek-** [comment]
à part de zds je présume?

**Comment by gustavi** [comment]
Oui.

Juste comme ça, le forum est plus approprié pour ce genre de suggestion !

**Comment by Eskimon** [comment]
Yep un sujet sur le forum Bugs Et Suggestions serait nickel pour discuter plus facilement et ainsi lister toutes les possibilités de notre imagination !

**Comment by gustavi** [comment]
@Nek- peux-tu ouvrir un sujet sur le forum qu'on ferme ici ?

**Comment by Nek-** [comment]
[Proposition sur zds](http://zestedesavoir.com/forums/sujet/2129/ajouter-un-bot-irc-pour-le-chat-zest-de-savoir/?page=1)

**Comment by gustavi** [comment]
Merci
