### ISSUE TITLE
Pouvoir (ne plus) suivre un article ou un tutoriel

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2025]
[Reporté par WinXaito sur le forum](https://zestedesavoir.com/forums/sujet/2111/ne-plus-suivre-un-article-petit-alignement-de-case-a-cocher/?page=1#p37486) :

> je ne sais pas si ça a déjà été dit, (J'ai recherché un petit coup mais n'ai rien trouvé), je n'ai pas vu la possibilité de ne plus suivre un "Article". Car j'ai remarqué qu'à chaque fois qu'un commentaire est dit dans l'article, j'en suis notifié (Pour autant que j'aie mis un commentaire), mais l'article ne fait pas partie des "Sujet suivi".

**Comment by ChantyTaguan** [comment]
Hello,

J'aurais bien envie de m'occuper de ceci. Après lecture du code, je vois qu'on a pas de structure dédiée pour le suivi des articles et des tutos. On regarde simplement si on a écrit un commentaire sur l'article/le tuto et si y a des réponses non lues. Pour les forums par contre, y a un modèle dédié.

Du coup, c'est l'occasion de peut-être penser encore plus loin et faire des notifs complètement générales (liées à un sujet du forum, un article, un tuto, mais éventuellement à d'autres choses, genre les futures tribunes libres).
Est-ce qu'il y a déjà eu une discussion à ce sujet ? Est-ce que ça mérite carrément une ZEP (pas l'impression) ?
Est-ce qu'éventuellement y a une manière classique d'implémenter ce genre de truc avec Django/python ?

**Comment by Eskimon** [comment]
Le truc c'est que le code actuel concernant les reactions sur articles/tuto est loin d'etre propre. Il est duplique de partout et c'est pas la joie. Normalement cette duplication va degager avec la ZEP-12 en cours de dev', mais je sais pas si ca un impact "factorisant" vis a vis des réactions du forum... (ping @pierre-24 && @gustavi || @artragis ^^)

**Comment by artragis** [comment]
A priori non. Il faudra implémenter ça une fois la zep 12 développée.

**Comment by pierre-24** [comment]
On va pas tout bloquer parce que ZEP-12 non plus (je voudrais pas être pessimiste, mais ça va prendre un peu de temps à dev, la ZEP-12). Donc on peut très clairement lancer une ZEP, et ça va pas être bloquant, à mon sens ;)

**Comment by artragis** [comment]
oui, c'est à vous de vvoir. mais c'est pas la zep 12 qui va dev la 
fonctionnalité.

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
autoquote

> oui, c'est à vous de vvoir. mais c'est pas la zep 12 qui va dev la
> fonctionnalité.

2015-04-16 14:55 GMT+02:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
ok :) Mais comme un peu plus tot on parlais du suivi auto pour l'auteur, est-ce que ca ne pourrait pas s'en inspirer ?

**Comment by artragis** [comment]
Dans le futur il **faudra** s'en inspirer, pour l'instant c'est un peu...
difficile.

2015-04-16 15:13 GMT+02:00 Eskimon notifications@github.com:

**Comment by artragis** [comment]
Au pire à voir avec celui qui va dev l'inscription de l'auteur. #Pasmoi

**Comment by Eskimon** [comment]
Je tag evolution, la feature n'existant pas elle ne peut pas être bugguée :-°

**Comment by Situphen** [comment]
Faudra se rappeler de fermer ici lors du merge de la ZEP 24 !

**Comment by GerardPaligot** [comment]
@Situphen Toutafé. Je me l'assigne pour y penser.
