### ISSUE TITLE
On ne peut pas déplacer un sujet épinglé

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#2027]
Le dropdown ne s'affiche pas.

Pour reproduire : 
- Créer un sujet sur le forum
- Le mettre épinglé
- Essayer de le déplacer

**Comment by ChantyTaguan** [comment]
J'ai pas de souci pour déplacer un sujet épinglé personnellement, ni en local ni en prod.

**Comment by DevHugo** [comment]
Pas de souci en local, non plus !

**Comment by gustavi** [comment]
Effectivement je n'ai plus ce bug. Étrange. Je ferme donc.
