### ISSUE TITLE
Résoudre un bug une fois pour toute

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#203]
Dernièrement, j'ai remarqué que certains bugs corrigé dans le passé son réapparus à un moment.

J'ai donc trouvé du temps pour créer une architecture de code pour les tests. J'ai fais exprès dans le fichier de tests de présenter différents cas d'utilisation (post, get, connexion, etc.) afin que ce fichier serve de base aux devs pour construire les autres tests sur le même modèle.

**J'aimerais, dans une optique de ne plus avoir à créer des regressions, que pour chaque feature/correction de bug crée, le développeur rédige un test de sa feature. ça permettra de s'assurer qu'une feature implémentée ne sera plus jamais buguée.**

Pour le coté technique, l'architecture de tests est basé sur la bibliothèque factory_boy qui permet de créer des fixtures à la volée de manière assez flexible pour suivre les évolutions.

Pour ceux qui ne sont pas familiers avec les tests, sachez que c'est assez simple. Si on prend un exemple que j'ai écrit : 

``` python
def test_answer(self):
        '''
        To test all aspects of answer
        '''
        #create an user
        user1 = UserFactory()
        #create one topic
        topic1 = TopicFactory(forum=self.forum11, author=self.user)
        #create 3 posts on topic
        post1 = PostFactory(topic=topic1, author=self.user, position = 1)
        post2 = PostFactory(topic=topic1, author=self.user, position = 2)
        post3 = PostFactory(topic=topic1, author=user1, position = 3)

        #test view answer on this context        
        result = self.client.post(
                        reverse('zds.forum.views.answer')+'?sujet={0}'.format(topic1.pk), 
                        {
                          'last_post' : topic1.last_message.pk,
                          'text': u'C\'est tout simplement l\'histoire de la ville de Paris que je voudrais vous conter '
                        },
                        follow=False)

        #check that http response is good        
        self.assertEqual(result.status_code, 302)

        #check topic's number
        self.assertEqual(Topic.objects.all().count(), 1)

        #check post's number
        self.assertEqual(Post.objects.all().count(), 4)

        #check topic and post
        self.assertEqual(post1.topic, topic1)
        self.assertEqual(post2.topic, topic1)
        self.assertEqual(post3.topic, topic1)

        #check values
        self.assertEqual(Post.objects.get(pk=4).topic, topic1)
        self.assertEqual(Post.objects.get(pk=4).position, 4)
        self.assertEqual(Post.objects.get(pk=4).editor, None)        
        self.assertEqual(Post.objects.get(pk=4).text, u'C\'est tout simplement l\'histoire de la ville de Paris que je voudrais vous conter ')
```

Les commentaires parlent d'eux même. Les tests se font toujours en 3 phases : 
- Je crée mon contexte
- Je simule ce que j'ai envie de tester
- Je vérifie que les résultats dans la base sont ceux attendus.

N'hésitez pas en cas de question.

**Comment by GerardPaligot** [comment]
Super initiative mais juste pour savoir : Est-ce que tu as un exemple avec les formulaires ?

Sinon, je suis d'avis d'appliquer ça dès le sprint pour l'alpha 0.3 et donc de ne plus faire de PR sans tests associés sous peine de le refuser directement.

**Comment by firm1** [comment]
> Est-ce que tu as un exemple avec les formulaires ?

Etant donné qu'un formulaire est utilisé dans 1 une plusieurs vue (view) en post, pour tester un formulaire, tu dois obligatoirement tester toutes les vues qui lui sont associées. 
C'est le cas par exemple du test de [création d'un topic](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/forum/tests.py#L33) qui vérifie que la création d'un topic se passe bien et donc utilise les formulaires.

> Sinon, je suis d'avis d'appliquer ça dès le sprint pour l'alpha 0.3 et donc de ne plus faire de PR sans tests associés sous peine de le refuser directement.

Je ne serais pas aussi strict pour ceux qui n'ont pas encore un bon niveau en django. Mais oui, c'est ce qu'il faudra viser pour l'avenir.

**Comment by firm1** [comment]
Bon, d'après les stats de couverture de tests, nous en sommes actuellement à 51% des tests couverts back-end couverts.

Je ferme donc cette issue, que je vais plutôt noter quelque part dans la doc du projet. Dans un paragraphe "Bonne pratiques"
