### ISSUE TITLE
Le partge pas mail d'un article/tutoriel ne fonctionne pas

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#2030]
Reporté via le [forum](http://zestedesavoir.com/forums/sujet/2124/partage-par-e-mail-dun-article-tutoriel/?page=1#p37737) : 

> j'ai remarqué que quand on cliquait sur "Envoyer par e-mail" dans la section partage (Sur un article ou un tutoriel), rien ne se passait. Le seul moyen est d'ouvrir le lien dans un nouvel onglet.

Il semblerait que ça vienne du lien qui est faux.

**Comment by ChantyTaguan** [comment]
En local, tout fonctionne. De même en prod, si je fais un clic droit -> ouvrir le lien dans un nouvel onglet, ça fonctionne correctement.

Par contre, un simple clic donne une erreur 403 dans la console JS : 

```
POST http://zestedesavoir.com/tutoriels/247/tout-savoir-sur-les-ssd-solid-states-drives/ 403 (FORBIDDEN)    all.min.js:3 
Y.cors.e.crossDomain.send
Z.extend.ajax
(anonymous function)
Z.event.dispatch
m.handle
```

**Comment by Situphen** [comment]
A fermer car réglé par #2226 !
