### ISSUE TITLE
Problème de saisi d'un membre dans l'ajout d'un auteur

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#2031]
Via le [forum](http://zestedesavoir.com/forums/sujet/2135/ajout-dun-auteur-fonctionnant-mal/#p37866) : 

> J'ai voulu ajouter un auteur à un article en collaboration, j'ai copié/collé le pseudo dans l'interface mais s'il a validé (à savoir retour vers l'article en question), ça n'a pas été réellement pris en compte. Mais je n'ai pas eu de messages d'erreurs pour autant. Pour que cela fonctionne, j'ai du saisir manuellement son nom pour le cliquer sur sa suggestion dans la barre de saisie et là ça a correctement fonctionné.
> 
> Pour moi le copier/coller aurait du fonctionner, et en cas d'erreurs de saisis, avoir une erreur correspondante.

**Comment by ChantyTaguan** [comment]
Je prends. Je peux ? :-)

D'après mes tests, ça fonctionne si le pseudo de l'auteur est parfaitement orthographié. Par contre, effectivement, aucun message ne s'affiche si le pseudo n'existe pas, et on ne vire pas les éventuels espaces avant/après le pseudo donné.

Donc, 
1/ j'ajouterais un trim sur la recherche à partir du pseudo donné
2/ j'ajouterais évidemment un message d'erreur si on ne trouve pas d'user correspondant

PR demain, là, dodo !

**Comment by Eskimon** [comment]
it is done :) Beau travail d'équipe d'ailleurs :)
