### ISSUE TITLE
Nouvelle balise : "encart" ou "annexe"

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2033]
De mon point de vue, il nous manque une balise "encart" ou "annexe" dans le markdown, de la même manière qu'on a les attention / question / etc.

Elle servirait à mettre du contenu annexe au texte principal du tuto ou de l'article, tels que des résumés, des preuves, des explications complémentaire, etc.

On les retrouve souvent dans les publications de vulgarisation scientifique dans des encarts (avec le cadre autour du texte et tout) ; je ne sais pas trop comment on pourrait rendre ça sur le web.

**Comment by Situphen** [comment]
Note aux devs du Markdown : AMHA, il faudrait utiliser la balise `<aside>` (avec une classe pour le design).

**Comment by GerardPaligot** [comment]
C'est pas une issue pour le projet Python-ZMarkdown plutôt ?

**Comment by Situphen** [comment]
+1

**Comment by GerardPaligot** [comment]
Issue créée : https://github.com/zestedesavoir/Python-ZMarkdown/issues/104
