### ISSUE TITLE
Erreur 404 sur le bouton "ne plus suivre" sur le forum

### ISSUE THREAD

**Issue by PierreGaudichon** [zestedesavoir/zds-site#2036]
Sur la page d'acceuil des forums, la liste des sujets suivis a un bouton par sujet qui propose de ne plus suivre le sujet. Lors du clic, le site revoie une erreur 404. L'url de la page 404 est `http://zestedesavoir.com/forums/sujet/editer/`.

Par contre, je peux supprimer le sujet de la liste des suivis lorsque je suis sur la page du sujet en question.

**Comment by Eskimon** [comment]
Je pense que c'est un doublon de l'erreur qui est réglée :) https://github.com/zestedesavoir/zds-site/issues/1884

**Comment by firm1** [comment]
En effet doublon, et donc corrigé.
