### ISSUE TITLE
Ajaxification du bouton "cette réponse m'a aidée"

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2041]
[Via Fulbert](https://zestedesavoir.com/forums/sujet/2160/liens-vers-le-comptes-zds-sur-les-reseaux-sociaux/?page=1#p38423):

Il faudrait ajaxifier le bouton "Cette reponse m'a aidee" pour eviter le rechargement de toute la page.

S'inspirer de la PR https://github.com/zestedesavoir/zds-site/pull/1867

**Comment by Cydonia7** [comment]
Je m'en occupe !

**Comment by Eskimon** [comment]
Ca roule, merci !!

**Comment by GerardPaligot** [comment]
Merci à @Situphen et @pierre-24 pour la QA.
