### ISSUE TITLE
Rendre les vidéos responsive

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2044]
Sur mobile, il y a une marge noire à droite quand la page contient une vidéo. Il faudrait rendre les vidéos responsive.

[Reporté par Vince sur le fork DansTonCube](http://danstoncube.fr/forums/sujet/44/affichage-articles/), ce bug est aussi présent sur ZdS :

![Image du bug](http://uprapide.com/thumbs/invite/screenshot-2015-01-06-23-13-33-2.jpg)

**Comment by Eskimon** [comment]
Toujours vrai ca ?

**Comment by Situphen** [comment]
Oui, et il faut vraiment que je mette ça dans ma to-do list pour que le site soit complètement responsive !
