### ISSUE TITLE
[Staff] Afficher si un compte n'est pas activé

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2045]
Lorsqu'un staff visualise un profil, il voit dans le bas de la sidebar des actions sur le banissement. Ces actions ne devrait pas etre visible si le compte du membre n'est pas activé.

Un message devrait aussi etre visible quelque part pour signaler que le compte n'est pas activée.

Pour le premier point, il suffit d'englober le passage suivant avec un `if usr.is_active` (ou un truc de cet acabit) https://github.com/zestedesavoir/zds-site/blob/dev/templates/member/profile.html#L497

**Comment by Eskimon** [comment]
Il me semble avoir vu la mention "DEAD" sur certains compte, c'est une correction partielle de ca ?

**Comment by SpaceFox** [comment]
On dirait même une correction complète.

**Comment by Eskimon** [comment]
C'est a dire ? La sidebar n'affiche plus les actions de moderation sur ces comptes la ? Ca serait bien de trouver la PR qui a fait ca :D

**Comment by SpaceFox** [comment]
Ha non, je ne suis certain que de "Un message devrait aussi etre visible quelque part pour signaler que le compte n'est pas activée."

**Comment by firm1** [comment]
Je confirme que l'issue est corrigée de manière complète via une de mes PRs

**Comment by Eskimon** [comment]
Donc pour résumer :
- Un badge DEAD pour les membres non active
- La sidebar de moderation non visible

???

**Comment by firm1** [comment]
C'est ça

**Comment by Eskimon** [comment]
Ok je ferme ! (ca serait cool de trouver la PR / milestone a appliquer cependant)

**Comment by firm1** [comment]
Pour le suivi, la PR est celle-ci : #2425
