### ISSUE TITLE
Page de profil : Un staff devrait pouvoir voir l'email d'un membre

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2046]
Pour différentes raisons d'administrations, il serait pratique que les staff puissent voir l'email du membre sur la page de profil de ce dernier.

Pour cela il faut modifier la condition ici : https://github.com/zestedesavoir/zds-site/blob/dev/templates/member/profile.html#L63

(indice : perms.member.change_profile return true si je suis staff)

**Comment by GerardPaligot** [comment]
Quel est le scénario qui le justifie ? Un membre n'a pas forcément envie de divulguer son e-mail, même au staff. Et si nous le faisons quand même, il faut signaler dans les paramètres utilisateurs qu'il peut cacher son e-mail mais qu'il ne le sera pas au staff.

**Comment by Eskimon** [comment]
Par exemple si un membre galère a activer son compte, alors un super-user pourra le faire. Cependant il faut l'email pour cela si je dis pas de betise. (mais je me trompe peut-être).

**Comment by GerardPaligot** [comment]
Non, c'est une case à cocher dans l'administration. L'e-mail n'est pas nécessaire pour qu'un super-user active le compte d'un membre.

Edit : D'ailleurs, le super-user peut voir l'e-mail dans l'interface admin ...

**Comment by Eskimon** [comment]
Je ferme, ca ne semble effectivement pas réclamé par le staff et les super-user ont ce qui leur faut !
