### ISSUE TITLE
La boite modale ne s'affiche pas dans certains cas

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2047]
Scénario 1 : 
- Je vais sur un forum
- Je clique sur "Tutoriels" dans la barre du haut
- Je clique ensuite dans le vide car je ne veux pas aller dans les tutoriels
- Je clique ensuite sur le point de suspension dans la pagination pour aller à un numéro de page précis
- **La boite modale ne s'affiche pas**

Scenario 2 : 
- Je vais sur un topic
- Je clique sur "Tutoriels" dans la barre du haut
- Je clique ensuite dans le vide car je ne veux pas aller dans les tutoriels
- Je clique ensuite sur le bouton déplacer
- **La boite modale ne s'affiche pas**

Navigateur : firefox 32
OS : Windows

**Comment by poulp** [comment]
je pense que c'est liée #1936

**Comment by Eskimon** [comment]
Doublon de 1936 effectivement
