### ISSUE TITLE
Confirmer la fermeture d'un topic

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2048]
Fermer un topic est une action de modération. Cependant, quand on est sur mobile, on pourrait cliquer par inadvertance sur le bouton "fermer un sujet".

Pour éviter que ça arrive, il faudrait une boite modale qui permette de confirmer cette action.

**Comment by GerardPaligot** [comment]
Je ne suis pas fan de cette suggestion. Comment peux-tu appuyer par inadvertance sur ce bouton alors qu'il se trouve dans la sidebar sur mobile (et sur le site) ?

**Comment by firm1** [comment]
Je suis déjà tombé plusieurs fois sur le cas en tentant de déplacer un topic ou en essayant de mettre un topic en post-it. Sur mobile, la plupart du temps

**Comment by Eskimon** [comment]
Idem, quand j'etais staff je me suis deja fait surprendre en voulant aller trop vite

**Comment by SpaceFox** [comment]
Je confirme que ça m'est déjà arrivé.

**Comment by ChantyTaguan** [comment]
Itou !

**Comment by Eskimon** [comment]
Vu qu'on arrivait a un ratio de 4 contre 1 en peu de temps, j'ai juge utile de merger histoire d'eviter de voir une PR traîner "administrativement". Je propose qu'on laisse une periode d'adaptation a nos chers staffeux et si vraiment ca gene il suffira de revert la PR :)

Du coup je ferme et merci a @DevHugo pour l'implementation
