### ISSUE TITLE
Problème de 404  dans la navigation par tag

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2049]
L'url suivante : `/forums/sujets/tag/48/python/?page=4` devrait renvoyer une 404 car la page 4 n'existe pas.

C'est mauvais pour le SEO.

**Comment by SpaceFox** [comment]
> C'est mauvais pour le SEO.

Cette URL en particulier (avec le mauvais numéro de page) est référencée quelque part ?

Qu'est-ce que ça renvoi aujourd'hui ?

**Comment by Eskimon** [comment]
Ok, merci @firm1 et @GerardPaligot
