### ISSUE TITLE
Impossible d'éditer un main topic

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#205]
Scénario : 
1. Créer un topic
2. Cliquer sur éditer
   Problème : Impossible de modifier le titre/soustitre de ce topic alors qu'on en est l'auteur.

Il existe un [test dessus](https://magnum.travis-ci.com/Taluu/ZesteDeSavoir/builds/2981874), qui échoue actuellement.

**Comment by Ge0** [comment]
Je prends.

J'ai bidouillé à droite à gauche pour essayer de comprendre ce qui se passe.

D'abord et avant tout, où se trouve le lien pour éditer un **sujet** et non pas un **message**, qui sont deux choses différentes au vu du code ?

**Comment by firm1** [comment]
Voici un [aperçu code à l'époque quand ça marchait encore](https://github.com/Taluu/ZesteDeSavoir/blob/1fe5a12f306ee8bd4a40e639bb06557e929193eb/zds/forum/views.py#L415).

Il me semble que pour resoudre le bug il faut : 
- ajouter sur [cette ligne](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/forum/views.py#L445), le bloc de code suivant : 

``` python
# Modifying the thread info
            if g_topic:
                g_topic.title = request.POST['title']
                g_topic.subtitle = request.POST['subtitle']
                g_topic.save()
```
- modifier ensuite le bloc suivant : 

``` python
form = PostForm(initial = {
        'text': post.text
    })
```

par : 

``` python
if g_topic:
    form = TopicForm(g_topic, request.user, initial = {
        'title ': g_topic.title,
        'subtitle': g_topic.subtitle,
        'text': post.text
    })
else:
    form = PostForm(g_topic, request.user, initial = {
        'text': post.text
    })
```

Et s'il y'a des erreurs ... faut debugguer.

**Comment by firm1** [comment]
C'est fixé, je ferme
