### ISSUE TITLE
Le site n'a pas de titre 1

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2051]
Le site a des h2, des h3, des h4, mais jamais de h1. C'est pourant une bonne pratique pour le référencement.

**Comment by SpaceFox** [comment]
Pour moi il va falloir détailler ce ticket, à commencer par indiquer les pages impactées.

**Comment by GerardPaligot** [comment]
Il me semblait qu' @Alex-D avait ses raisons à l'époque. Malheureusement, cela remonte à bien trop longtemps. Je ne serais pas en mesure de vous l'expliquer.

**Comment by nils-van-zuijlen** [comment]
Maintenant que le site a un h1 sur ses pages, ce ticket peut être fermé.
