### ISSUE TITLE
Incohérence dans l'affichage des licences d'un tutoriel/article

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2052]
Quand on visite un tutoriel ou article hors ligne et en ligne, la licence n'est pas la même.

La preuve en image

[Version hors ligne](https://zestedesavoir.com/tutoriels/off/234/creer-un-jeu-html5-avec-quintus/) : 

![offline](https://cloud.githubusercontent.com/assets/6066015/5723876/c4611966-9b47-11e4-8ec9-b991668a3ee2.PNG)

[Version en ligne](https://zestedesavoir.com/tutoriels/234/creer-un-jeu-html5-avec-quintus/) :

![online](https://cloud.githubusercontent.com/assets/6066015/5723877/c85b037e-9b47-11e4-9716-e4fd93272ad5.PNG)

**Comment by SpaceFox** [comment]
C'est juste un bug d'affichage qui d'ailleurs pour moi était corrigé depuis
longtemps.

**Comment by ghost** [comment]
C'est le back qui envois "Licence".

**Comment by Eskimon** [comment]
Et voila !
