### ISSUE TITLE
Problème d'encodage avec l'utilisation de certains e-mail (avec accent)

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2053]
Salut,

J'ai eu une erreur 500 avec un affichage non voulu. Lorsque je désire consulter la page 4 de l'un de mes MPs (avec @gustavi et @ChantyTaguan), je me retrouve avec ce qui semblerait être une erreur 500 :

```
{% extends "base.html" %} {% load i18n %} {% block title %} {% trans "Erreur 500" %} {% endblock %} {% block headline %} {% trans "Erreur 500" %} {% endblock %} {% block breadcrumb %}
{% trans "Erreur 500" %}
{% endblock %} {# No sidebar on this page #} {% block body_class %}no-sidebar{% endblock %} {% block sidebar %}{% endblock %} {% block content %}
{% blocktrans with url_forum="http://zestedesavoir.com/forums/communaute/bug-suggestions/" %} Si vous voyez cette page, c'est que vous avez trouvÃ© un bug. Merci de rapporter cette erreur en expliquant comment vous avez procÃ©dÃ© pour tomber sur cette page en crÃ©ant un sujet sur le forum Bugs et Suggestions.Merci de votre aide {% endblocktrans %} !

{% blocktrans with url_bugtracker="https://github.com/zestedesavoir/zds-site/issues?q=is%3Aopen+is%3Aissue+500" %} Si vous Ãªtes curieux, voici une liste des sujets ouverts Ã  ce propos sur le bug tracker public de l'association {% endblocktrans %}.

{% endblock %}
```

> **Note :** J'ai donc rencontré une vraie erreur cachée derrière celle-ci mais il faut quelqu'un avec un accès à Sentry pour consulter cette erreur et faire le ticket.

Edit : Le bug a été trouvé plus bas dans [ce ticket](https://github.com/zestedesavoir/zds-site/issues/2053#issuecomment-69908131).

> Dans Sentry, la seule erreur ayant eu lieu il y a environ une heure c'est:
> 
> `UnicodeEncodeError: 'ascii' codec can't encode character u'\xfb' in position 9: ordinal not in range(128)`
> 
> du a ca : 
> 
> ```
> File "zds/member/models.py", line 123, in get_avatar_url
>     md5(self.user.email.lower()).hexdigest())
> ```
> 
> Source: Eskimon

**Comment by Eskimon** [comment]
Il y a pas une histoire de "ce genre d'erreur est retourne quand le serveur a vraiment crasher (et non pas juste "la logique du site est incohérente" ?

**Comment by GerardPaligot** [comment]
@Eskimon : A première vue, c'est gunicorn qui a eu un problème. Tout est normal maintenant. Cf. [ce message](https://zestedesavoir.com/forums/sujet/2202/vilaine-erreur-sur-les-forums/?page=1#p39428) sur les forums de ZdS.

Par contre, il y a vraiment une erreur 500 qui traine et il faudrait voir pourquoi.

**Comment by Eskimon** [comment]
Dans Sentry, la seule erreur ayant eu lieu il y a environ une heure c'est:

`UnicodeEncodeError: 'ascii' codec can't encode character u'\xfb' in position 9: ordinal not in range(128)`

du a ca : 

```
File "zds/member/models.py", line 123, in get_avatar_url
    md5(self.user.email.lower()).hexdigest())
```

**Comment by Eskimon** [comment]
Pour corriger, il faudrait un 'u' devant cette chaine. C'est bizarre il me semblait que ca avait ete fait il y a longtemps...

https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/models.py#L128

**Comment by GerardPaligot** [comment]
Ok, je renomme le sujet pour expliciter ce bug.

**Comment by Eskimon** [comment]
Dans ce cas c'est doublon de cela : https://github.com/zestedesavoir/zds-site/issues/1640

**Comment by GerardPaligot** [comment]
Bien, je ferme ici.
