### ISSUE TITLE
Le site n'est pas compatible IE9

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2054]
Navigateur : **IE9**
OS : **Windows 7**

Screenshot de la home

![](http://zestedesavoir.com/media/galleries/241/540d223f-f628-497c-b4f4-4e55b9fa6cbb.png.960x960_q85.png)

Screeeshot d'un topic :

![](http://zestedesavoir.com/media/galleries/241/ac4ee723-4323-47f8-b97c-99679e987864.png.960x960_q85.png)

En fait c'est le cas sur la sidebar dans toutes les pages.

**Comment by SpaceFox** [comment]
Pour information, IE9 c'est 0,39 % du trafic global (22ème rang) sur le dernier mois, et 0,49 % du trafic global (31ème rang) depuis l'ouverture au public.

Donc si ça amuse quelqu'un de le corriger OK, mais ça reste un problème ultra-mineur.

**Comment by ghost** [comment]
Y'a le même bug sous Blueflap et la zone pour écrire le message est carée aussi (c'est psa tout à fait la même chose, mais tant qu'on y est ...)

**Comment by gustavi** [comment]
@Bat41 honnêtement c'est encore plus spécifique donc je doute que quelqu'un soit motivé pour ça ! Surtout que IE9 ne représente qu'une infime partie du trafic. Après si tu corriges ça c'est avec plaisir :)

Mais bon, toute personne qui se respecte n'utilise pas IE.

**Comment by SpaceFox** [comment]
> Mais bon, toute personne qui se respecte n'utilise pas IE.

Bah, IE11 est devenu un navigateur tout à fait acceptable (et à sa sortie, c'était même le plus performant niveau JS).

**Comment by ghost** [comment]
Je prends.

**Comment by SpaceFox** [comment]
Très honnêtement @A-312, je pense que n'importe lequel de 208 autres issues ouvertes est plus utile que celle-ci. Cf les chiffres un peu plus haut dans la conversation.

**Comment by GerardPaligot** [comment]
Merci @A-312, issue corrigée !
