### ISSUE TITLE
Un code de tracking est present en dur dans le code

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2058]
[Via le fork "danstoncube.fr"](https://github.com/DansTonCubeFr/danstoncube.fr/issues/7)

Dans un fichier de javascript, un code de tracking Google Analytics est present en dur. Ce dernier doit absolument etre externalise dans le fichier de settings.

https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/cookies-banner.js#L15

**Comment by SpaceFox** [comment]
J'avoue que je ne comprends pas bien ce que ce tag fait dans ce fichier.

2015-01-16 12:16 GMT+01:00 Eskimon notifications@github.com:

**Comment by GerardPaligot** [comment]
Merci à @Situphen de s'en être occupé. Merci à @pierre-24 pour la QA.
