### ISSUE TITLE
Erreur dans le template du mail d'oubli du mot de passe, d'inscription

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2060]
## Template de réinitialisation de mot de passe

Le mail de réinitialisation du mot de passe en prod, utilise les variables app.site.url, app.site.litteral_name et app.site.name qui ne sont pas définis.

Le mail reçu :

> Bonjour Hugo, 
> 
> Vous recevez ce message parce qu'une réinitialisation du mot de passe de votre compte utilisateur a 
> été demandée sur . 
> 
> ATTENTION
> Si vous n'avez pas demandé une réinitialisation du mot de passe, IGNOREZ et EFFACEZ ce courriel 
> immédiatement ! Continuez uniquement si vous souhaitez que votre mot de passe soit réinitialisé !
> 
> Cliquez ou recopiez simplement le lien et complétez le reste du formulaire : 
> http://zestedesavoir.com/membres/new_password/?token=youLooseTheGame
> 
> Cordialement, 
> L'équipe 
> - Mail de réinitialisation du mot de passe

Le mail que je devrais recevoir : 

> Bonjour Hugo, 
> 
> Vous recevez ce message parce qu'une réinitialisation du mot de passe de votre compte utilisateur a 
> été demandée sur **<a href="zestedesavoir.com">zestedesavoir.com</a>**. 
> 
> ATTENTION
> Si vous n'avez pas demandé une réinitialisation du mot de passe, IGNOREZ et EFFACEZ ce courriel 
> immédiatement ! Continuez uniquement si vous souhaitez que votre mot de passe soit réinitialisé !
> 
> Cliquez ou recopiez simplement le lien et complétez le reste du formulaire : 
> http://zestedesavoir.com/membres/new_password/?token=youLooseTheGame
> 
> Cordialement, 
> L'équipe **de zeste de savoir**
> - Mail de réinitialisation du mot de passe
## Template d'inscription

Même problème.

Pour les devs:
- Voir les fichiers dans le dossier templates/email/*
- Pour le serveur de mail, pour recevoir les mails en local: [http://stackoverflow.com/questions/10624965/django-email-backend-with-local-smtp](http://stackoverflow.com/questions/10624965/django-email-backend-with-local-smtp)
- Au choix: documenter les variables et ajouter sur la prod ou les changer dans les templates.

**Comment by gustavi** [comment]
C'est connu, je crois même que j'ai une PR en cours dessus. Merci du retour.

**Comment by DevHugo** [comment]
Tu parle de ça: [https://github.com/zestedesavoir/zds-site/pull/1785](https://github.com/zestedesavoir/zds-site/pull/1785), d'aprés une relecture rapide c'est que pour les mps !

Donc faut faire le reste, rajouter deux paramétres dans le render ^^ (je le fais si tu veux, no souci).

Ferme, si tu peux, je vais ajouter en commentaire, de ne pas oublier les autres templates: celui d'inscription, d'oubli de mot de passe.

**Comment by Eskimon** [comment]
Alors go @DevHugo si tu sais ou corriger tout ca c'est avec plaisir :)

**Comment by DevHugo** [comment]
Je fais ça se soir, si j'ai le temps.

**Comment by gustavi** [comment]
Corrigé et mergé ! Merci @DevHugo !
