### ISSUE TITLE
impossible de se désincrire

### ISSUE THREAD

**Issue by ghost** [zestedesavoir/zds-site#2062]
bonjour, il n'est pas possible de se désinscrire, que faire ? j'obtiens une erreur 500 !

**Comment by GerardPaligot** [comment]
Il faudrait quelqu'un avec un accès Sentry ici (cc @SpaceFox, @gustavi).

@folaefolc Nous sommes désolé que tu veuilles nous quitter de ZdS. :)

**Comment by gustavi** [comment]
@folaefolc je peux avoir l'heure de ta tentative de désinscription ?

**Comment by ghost** [comment]
il y a pile poil 5h, et je viens de réessayer !

**Comment by SpaceFox** [comment]
OK... ici https://github.com/zestedesavoir/zds-site/blob/dev/server/deploy.sh#L62 on considère que **toutes** les tables de la base utilisent South et donc la mise à jour avec `python manage.py migrate`.

Or apparemment certains modules (dont l'authentification par boutons sociaux) utilisent encore la mise à jour avec `python manage.py syncdb`.

Il manquait donc ces tables :

social_auth_association
social_auth_code
social_auth_nonce
social_auth_usersocialauth

J'ai lancé la création de ces tables sur les environnements :

```
$ python manage.py syncdb
Syncing...
Creating tables ...
Creating table social_auth_usersocialauth
Creating table social_auth_nonce
Creating table social_auth_association
Creating table social_auth_code
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.messages
 > django.contrib.staticfiles
 > django.contrib.sitemaps
 > django.contrib.humanize
 > south
 > crispy_forms
 > haystack
 > munin
 > social.apps.django_app.default
 > django.contrib.admin
 > debug_toolbar
 > raven.contrib.django.raven_compat

Not synced (use migrations):
 - easy_thumbnails
 - zds.utils
 - zds.pages
 - zds.gallery
 - zds.mp
 - zds.article
 - zds.forum
 - zds.tutorial
 - zds.member
(use ./manage.py migrate to migrate these)
```

Peut-on tester ?

**Comment by Eskimon** [comment]
(ca devrait aussi régler l'authentification par réseaux sociaux du coup...)

**Comment by ghost** [comment]
c'est bon, j'ai réussis :) merci
