### ISSUE TITLE
Il n'ya pas de ligne de césure entre le texte et la conclusion

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2066]
Je lisais [ce mini tutoriel](http://zestedesavoir.com/tutoriels/692/comment-reussir-votre-entretien-dembauche/) super interessant, et au niveau de la conclusion, il manque une balise &lt;hr /&gt; entre le dernier extrait et la conlusion sur la version en ligne.

La balise est pourtant présente sur la version hors ligne du tutoriel.

**Comment by ghost** [comment]
Je prends.
