### ISSUE TITLE
Le filtre par catégorie ne marche pas sur l'interface de validation des articles

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2067]
A l'instant sur la préprod en alant sur l'url : http://preprod.zestedesavoir.com/articles/validation/?subcategory=61 qui est censée renvoyer touts les articles en validation de la catégorie interview, je n'obtiens pas le résultat escompté.

Il me semble que ça a été corrigé du coté de la validation des tutoriels, mais pas dans les articles.

**Comment by SpaceFox** [comment]
C'est utilisé beaucoup comme fonctionnalité ? (pour pouvoir prioriser cette issue)

**Comment by firm1** [comment]
> C'est utilisé beaucoup comme fonctionnalité ?

Comment savoir ça ?

Il faut demander aux valido, mais vu que ça ne marche pas depuis au moins 4 mois, ça ne doit pas être utilisé

**Comment by Eskimon** [comment]
Personne ne s'en ai jamais plaint dans mes souvenirs

**Comment by firm1** [comment]
> Personne ne s'en ai jamais plaint dans mes souvenirs

si, moi :)

**Comment by Eskimon** [comment]
Réglé !

**Comment by Eskimon** [comment]
Je viens de tester sur la beta 1.8 et ca semble marcher bizarrement... Ca filtre mais ca renvoi pas ce qu'il faut...

**Comment by Eskimon** [comment]
Je suis plus staff sur la preprod, on peut me redonner les droits ou vérifier pour moi ?

**Comment by SpaceFox** [comment]
Tu es à nouveau staff sur la bêta :)

2015-05-17 10:43 GMT+02:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
Ca semble fonctionner
