### ISSUE TITLE
Impossible de publier un article

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2068]
## Attention ce bug est très bloquant

A l'instant à allant sur la préprod, je réserve un article dans la zone de validation. L'article se nomme "Trivial Computation et simplification matérielle des calculs".

Le seul problème étant qu'en arrivant sur l'article, je n'ai pas de bouton de validation à ma portée.

Un bug qui risque de bloquer la validation des articles.

**Comment by Eskimon** [comment]
J'ai reussi a faire apparaitre le bouton, mais effectivement il y a un truc bizarre...
Je m'explique...
- L'article est dans la liste, non reserve.
- Je click sur "reserver" et atteri sur l'article, cependant dans la sidebar rien n'affiche un etat "en validation" puisque je peux demander la validation pour ce dernier...
- Je demande la validation
- Je peux de nouveau reserver
- Puis publier (je suppose)

(et du coup j'ai fait buguer le truc car l'article apparait deux fois en zone de validation)

**Comment by SpaceFox** [comment]
Personnellement je n'arrive pas à reproduire en local (installation tellement fraîche que même l'OS est neuf, SQLite).

L'article est dans la liste, non réservé. Quand je clique sur "réserver", il est bien réservé et je peux le valider normalement.

Testé avec le compte admin qui se réserve son propre tuto, et le compte admin qui réserve le tuto de user.

**Comment by firm1** [comment]
Je n'ai pas essayé en local, c'est ce que j'obtiens en passant sur la préprod.

**Comment by SpaceFox** [comment]
Je ne nie pas. Je dis juste que je ne peux pas corriger quelque chose que
je ne peux pas reproduire.

Il faudra que j'essaie sur une base MySQL.

2015-01-22 11:53 GMT+01:00 firm1 notifications@github.com:

**Comment by SpaceFox** [comment]
J'ai réussi à reproduire en préprod. Cela dit, à la différence d'Eskimon, je ne duplique pas l'article dans la liste... c'est très mystérieux

**Comment by SpaceFox** [comment]
Je suis incapable de reproduire en préprod (v1.5-RC2) ou en local... est-ce que quelqu'un a encore le bug en préprod ?

**Comment by Eskimon** [comment]
J'arrive a reserver et publier comme il faut j'ai l'impression. Par contre on a des reliquats de bug car un article est present plusieurs fois dans la zone de validation et j'arrive pas le virer de la...

**Comment by SpaceFox** [comment]
@Eskimon les reliquats sont en local ou en préprod ?

**Comment by Eskimon** [comment]
Je sais pas si j'ai bien compris ta question. En preprod, on a des articles en doubon/triplons dans la zone de validation alors que ce n'est pas cense pouvoir arriver. Je ne sais pas comment nettoyer ca et je ne me rappelle plus les conditions qui faisaient apparaître les doublons.

Ce bug de doublon existe depuis longtemps mais avait ete corrige, seulement je ne sais pas si les doublons en preprod etait la avant le fix ou pas (s'il n'y etait pas alors on a une regression)

**Comment by SpaceFox** [comment]
Bon, on a réussi à publier des articles avec la v1.5, c'est donc que ce bug étrange est bel est bien corrigé. Je ferme.
