### ISSUE TITLE
Les parties d'un big tuto se déplacent sans mon accord

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2069]
Quand je veux déplacer une partie, je vais sur la partie en question, je déroule la zone "avant/après", si je clique dans la zone de liste la partie est déplacée avant même que je n'ai appuyé sur "déplacer".

Testé en préprod.

**Comment by firm1** [comment]
Pour info, j'ai le même souci quand je déplace un chapitre

**Comment by Eskimon** [comment]
Ca c'est le cas depuis toujours (j'ai meme fini par penser que c'etait voulu)

**Comment by firm1** [comment]
> Ca c'est le cas depuis toujours (j'ai meme fini par penser que c'etait voulu)

Ce n'est pas ergonomique en tout cas :)

**Comment by Eskimon** [comment]
La ZEP-12 corrigera ca d’après mes tests :)

**Comment by Situphen** [comment]
Ping @pierre-24 @artragis : la ZEP 12 règle ça ? :)

**Comment by pierre-24** [comment]
Très bonne question, ça ressemble à du JS qui en fait trop, non ?

**Comment by Situphen** [comment]
Je n'ai pas réussi à reproduire le bug sur la ZEP 12 (via `zds.francoisdambrine.me`) que se soit avec Firefox ou Chrome.

**Comment by artragis** [comment]
il fut un temps où j'avais ce bug, mais je pense qu'il a été corrigé à un moment donné. Je ne saurai pas en dire plus pour l'instant. Mais je pense que la PR de @pierre-24 sur les modales a été salutaire.

**Comment by Eskimon** [comment]
Idem après tout mes tests de déplacements sur la ZEP-12 ca ne m'a jamais arrivé... Je propose qu'on attende cependant le merge de la ZEP-12 pour fermer ici (histoire de s'en rappeler, plusieurs tickets ayant déjà le mot-clé pour revenir dessus plus tard)
