### ISSUE TITLE
Mauvais message affiché dans l'historique de validation

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2070]
Testé en préprod.

J'ai un tutoriel, je le soumets à la validation, j'annule la demande de validation.

Si on consulte l'historique de validation, on a le message suivant : "Ce tutoriel n'a jamais été soumis en validation. "

Ce qui est faux, puisque je l'ai soumis et j'ai annulé la soumission par la suite.

**Comment by SpaceFox** [comment]
Je me demande à quel point c'est pas volontaire ça.

**Comment by firm1** [comment]
> Je me demande à quel point c'est pas volontaire ça.

Ce n'est pourtant pas cohérent avec la réalité.

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
Je pene que non seulement nous n'avons pas résolu le bug mais qu'en plus j'ai volontairement imité le comportement actuel.

**Comment by Eskimon** [comment]
Cette feature n'existant pas dans la base de code actuelle, je ferme ce ticket.
