### ISSUE TITLE
L'historique de validation est écrasé dans certains cas

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2071]
Comme je le craignais ([cf ce commentaire](https://github.com/zestedesavoir/zds-site/pull/1960#issuecomment-69355052)) un bug permet à un auteur de nettoyer son historique de validation quand il veut.

Scenario : 
1. Je mets mon tuto en validation
2. mon tutoriel est refusé pour x ou y raison, et le valido prend le temps d'expliquer pourquoi
3. je renvoit mon tuto en validation, puis j'annule la validation
4. L'historique de validation est écrasé

Et donc un autre validation qui passe par là perd tout ce qu'avait noté le premier valido à l'étape 2.

Je pense que ce bug est **bloquant**, car il introduira une **faille** s'il passe en prod (la version actuelle est OK).

**Comment by SpaceFox** [comment]
Dans la mesure où la grande majorité des retours pertinents de validation se font par MP, je mets un bémol sur le "bloquant".

D'autre part, évites de trop détailler les failles sur un tracker public. Celle-là ça va encore, mais bon.

**Comment by GerardPaligot** [comment]
Parce que nous avons un bug tracker privé pour détailler les failles ? ...

**Comment by SpaceFox** [comment]
Non, mais on a les MP et pourquoi pas les mails. D'où la fameuse mailing list que je proposais l'autre jour...

Dans tous les cas, une vraie faille de sécurité **ne doit pas** être reportée en public !

**Comment by firm1** [comment]
Je ne l'aurai pas reporté en public si la faille était déjà en prod. Pour le moment ce n'est pas encore en prod, donc tant mieux, et il faudra éviter que ça arrive.

**Comment by GerardPaligot** [comment]
@SpaceFox Je ne comprends pas ton point de vue mais c'est toi le DIT. Donc, ok.

**Comment by SpaceFox** [comment]
Je ne vois pas ce que tu ne peux pas comprendre, honnêtement.

**Comment by GerardPaligot** [comment]
Nous sommes ici pour développer un projet open-source qui accepte les contributions de n'importe qui. Si nous commençons à rapporter des bugs/failles en message privé aussi, on ne s'en sortira plus. Soit, c'est pas le lieu pour en discuter.

**Comment by SpaceFox** [comment]
> Si nous commençons à rapporter des bugs/failles en message privé aussi, on ne s'en sortira plus. 

Je ne parle **que des failles de sécurité** et je suis désolé, ce n'est tout simplement pas négociable !

OK, on est un projet open-source qui accepte les contributions de n'importe qui. Et alors ? Est-ce que ça veut dire qu'il faut qu'on expose nos failles en public, en mode _"Regardez, hackez-nous ! C'est facile, on vous donne même la marche à suivre, c'est open bar !"_.

Soyons sérieux deux minutes : non. Jamais. **Tous les frameworks web et site webs open-source sérieux prennent la peine de séparer les problèmes de sécurité des bugs standard**, tu peux vérifier toi-même. Et s'ils le font, c'est qu'il y a une raison.

C'est d'autant plus vrai pour nous qu'on a pas, contrairement aux gros systèmes, les ressources pour corriger ces failles rapidement.

Il ne faut pas croire qu'on est à l'abri parce qu'on est relativement peu connus. Rien que le fait d'avoir une IP publique et référencée un minimum sur les moteurs de recherche nous envoie tellement de bots et de cochonneries du genre qu'on a préféré mettre un firewall qui bloque tout accès au port SSH qui ne vient pas d'IP explicitement autorisées - et pourtant ça a des côtés très chiants.

**Comment by GerardPaligot** [comment]
Non mais ça m'apprendra à donner mon avis. C'est toi le DIT, c'est toi qui décide. Point. Vous faites comme vous voulez, je m'en fous au final. Je ne suis qu'un simple contributeur.

**Comment by SpaceFox** [comment]
Je veux bien que les gens donnent leurs avis, j'ai pas de problème avec ça. Mais là :
- On en a déjà parlé en privé
- [Tu débarques avec un message ironique](https://github.com/zestedesavoir/zds-site/issues/2071#issuecomment-70485099) pour ne pas dire plus
- Tu proposes quelque chose qui va à l'encontre de toutes les bonnes pratiques
- Tu n'argumentes en aucune manière

Je pense que tu comprendras que tout ça cumulé, ça énerve !

**Comment by firm1** [comment]
En même temps l'issue "creer un espace privée pour les failles" existe quelque part. C'est juste que aucune documentation ne mentionne le cycle de vie d'une faille. :)

**Comment by SpaceFox** [comment]
Argument valable pour toute personne qui n'était pas dans le MP qui parlait de ça. Perdu, tu y étais ;)

**Comment by firm1** [comment]
Bah ce n'est pas une faille. Car ce n'est pas en prod.

**Comment by SpaceFox** [comment]
J'ai précisé ce point dans le message d'origine (c'était ça ou commencer à jouer avec les mots avec toi, et franchement, j'ai pas envie. Non parce que ton premier message disait quand même explicitement que c'était une faille).

**Comment by Eskimon** [comment]
Bon, pour revenir au bug...

On a deux solutions ici:
- Quelqu'un qui comprend le mécanisme de validation fait un joli fix + TU
- Je balance un revert du commit de la PR sus-nommée pour annuler ce changement. Ce revert pourra alors être "re-revert" à son tour pour continuer et corriger ce qui posait problème.

Je propose que si d'ici fin janvier (10 jours) la solution 1 ne peut-être appliquée alors la 2 doit-être mise en oeuvre.

**Comment by SpaceFox** [comment]
Est-ce que quelqu'un sait comment corriger ce problème ?

**Comment by SpaceFox** [comment]
Bon visiblement non. Si @Eskimon  ou quelqu'un d'autre peut revert le commit fautif comme proposé, ce serait génial.

**Comment by Eskimon** [comment]
Bon j'ai essaye depuis l'interface GH qui propose le bouton "revert" mais ca apporte du bordel. Je ferais donc ca proprement depuis mon PC et vous envoie ca se soir.

**Comment by Eskimon** [comment]
Voila, revert en PR.

**Comment by SpaceFox** [comment]
Corrigé --> fermé
