### ISSUE TITLE
Impossible d'ajouter quelqu'un d'autre à une galerie

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2072]
Je vais sur une gallerie, je clique sur "ajouter un utilisateur", je choisi un utilisateur, et je valide.

En revenant sur la gallerie, je ne vois pas l'utilisateur en question comme ayant été ajouté en lecture seule à la gallerie

**Comment by gustavi** [comment]
Corrigé et mergé ! Merci @poulp !
