### ISSUE TITLE
Tentative de signalement de faute, et rejet

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2075]
J'ai essayé de signaler une faute dans le tuto Arduino en préprod, on m'a proposé de faire un MP si mon message est trop long, ce que j'ai fais.

Par contre, le titre du MP est rempli automatiquement et est donc super long :  `Je voudrais signaler une faute dans le tutoriel "Arduino : Premiers pas en informatique embarquée"`

Quand je fini de taper mon message, à la validation, celui-ci est refusé parce que le titre est trop long. Il faut que le titre soit écourté automatiquement.

**Comment by SpaceFox** [comment]
> Il faut que le titre soit écourté automatiquement.

Jamais. Il faut adapter le texte et les limites de champs pour que ça rentre correctement.

**Comment by firm1** [comment]
Le texte dépend du titre du tutoriel aussi. Donc quelqu'un devra couper le texte de toute façon.
