### ISSUE TITLE
Page profil, les extraits de messages sont affiches en html

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2076]
> Je me suis rendu compte quand on va dans la liste des messages posté par un utilisateur (moi en l’occurrence vu que j'étais curieux ^^) on vois apparaître un résumé de chacun de ses messages.  
> Je me suis rendu compte que j'ai commencé un de mes message par du code. Du coup le résumé de ce message commence lui même par ce code (logique) ce qui est plus perturbant c'est que l'on vois les numéro de ligne de code devant ce code, ce qui n'a pas de sens.
> 
> Vous pouvez en avoir [un exemple ici](https://zestedesavoir.com/forums/messages/1757/), regardez à la date du mardi 30 décembre 2014 à 11h31.
> Source:[La source](http://zestedesavoir.com/forums/sujet/2151/enlever-numero-de-ligne-de-code-dans-le-resume-des-messages/?page=1#p38105)

**Comment by AmarOk1412** [comment]
@artragis à fermer. cf https://zestedesavoir.com/forums/messages/1757/?page=16

**Comment by Situphen** [comment]
Euh, moi je vois encore les numéros de ligne donc ce n'est pas bon, si ?

**Comment by rezemika** [comment]
Je viens de tester sur la bêta ([ici](https://beta.zestedesavoir.com/forums/sujet/9377/hey/)), c'est toujours d'actualité.

`1 2 3# A simple script. print("Hello world!") exit(0) Juste un petit test.`

Je vais faire quelques recherches, je vous tiens au courant si je trouves d'où ça vient.

**Comment by motet-a** [comment]
La manière la plus propre de régler le problème qui me vient en tête est de faire un rendu vers du texte brut depuis le moteur de Markdown. Mais c’est pas simple puisque le rendu HTML de chaque message est mis en cache, et je ne pense pas que ça vaille le coup de faire pareil avec du texte brut.
