### ISSUE TITLE
Mobile : Le bouton de signalement de faute empiète sur les commentaires

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2077]
Testé en préprod sur Chrome/Android

Voir le screenshoot.

![screenshot_2015-01-19-13-08-28](https://cloud.githubusercontent.com/assets/6066015/5800562/650f89b4-9fe0-11e4-92c5-24d074687f1e.png)

**Comment by SpaceFox** [comment]
Quelles versions ?

2015-01-19 13:38 GMT+01:00 firm1 notifications@github.com:

**Comment by firm1** [comment]
version : 39.0.2171.93

**Comment by Eskimon** [comment]
Une solution serait que [ce bloc h3](https://github.com/zestedesavoir/zds-site/blob/9599ed3e5793ef3b57eb031212c7529477b65ba6/templates/tutorial/tutorial/view_online.html#L112) passe dans le morceau include suivant (donc dans la section). Ca a le merite de fonctionner et d'etre semantiquement plus correcte... Mais je suis pas sur de ce que ca implique...
