### ISSUE TITLE
Pas de bouton pour signaler des fautes sur un article

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2078]
Le bouton de signalement de faute est présent dans un tutoriel, mais pas dans un article. Pourtant un article peut sortir aussi avec des fautes.

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
à tester.

2015-04-16 14:52 GMT+02:00 Eskimon notifications@github.com:

**Comment by firm1** [comment]
Il me semble que ce problème est déjà réglé avec ce commit :
https://github.com/zestedesavoir/zds-site/commit/e13f8dcec03d0dd97336e3df144bb6e2923fccf3

**Comment by Eskimon** [comment]
Yep, en v1.7 :)
