### ISSUE TITLE
Le topic de beta ne s'en va pas avec le tutoriel

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2079]
Si je supprimer un tutoriel qui a été passé en beta, le topic de beta reste toujours présent.

Il faudrait au minimum que le topic soit envoyé dans la corbeille, et idéalement, le topic devrait être supprimé en même temps que le tutoriel.

**Comment by Eskimon** [comment]
La release n'ayant pas bien eu lieu, je suppose qu'elle sera refaite apres le weekend et du coup j'ai ajoute ce ticket a la version 1.7 :)
