### ISSUE TITLE
zeste de savoir a 36% de duplicate content en interne

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2080]
Une analyse sur [siteliner](http://www.siteliner.com/zestedesavoir.com?siteliner=site-dashboard&siteliner-sort=scan_time&siteliner-from=1&siteliner-message=) révèle que le site zestedesavoir.com aujourd'hui à 36% de duplicate content interne.

Ce n'est pas bon.

**Comment by Eskimon** [comment]
Ca veut dire quoi "duplicate content interne." ?

**Comment by SpaceFox** [comment]
Est-ce que ça a une représentativité quelconque, quand je lis : "Siteliner
scanned 297 pages of 3,901 found on your site. " ?

2015-01-19 16:06 GMT+01:00 Eskimon notifications@github.com:

**Comment by firm1** [comment]
un exemple de deux pages en duplicate content interne : 

1 : http://zestedesavoir.com/tutoriels/692/comment-reussir-votre-entretien-dembauche/
2 : http://zestedesavoir.com/tutoriels/692/c/

Deux url différentes qui renvoient la même page, le même contenu.

On peut permettre aux deux url précédente d'exister, mais l'une devrait rediriger vers l'autre.

**Comment by firm1** [comment]
> Est-ce que ça a une représentativité quelconque, quand je lis : "Siteliner scanned 297 pages of 3,901 found on your site. " ?

Heuresement qu'ils ne scannent pas tout, car je crois qu'en réalité on en est à plus de 70% de duplicate.

Si je reprend mon exemple, tu remplace xxx dans http://zestedesavoir.com/tutoriels/692/<xxx>/ par n'importe quoi et hop, un nouveau duplicate.

**Comment by SpaceFox** [comment]
D'autre part, si j'en crois cet outils, leur "duplicate content" ma l'air
étrange comme analyse :
http://www.siteliner.com/zestedesavoir.com?siteliner=site-duplicate&siteliner-sort=match_words&siteliner-from=1&siteliner-message=

Déjà il me signale que "forums/savoirs/site-web/" est le 100% duplicate
content de "forums/savoirs/site-web/"... forcément c'est 2x la même page
sans paramètres supplémentaires !

J'ai l'impression que le gros du vrai problème qu'il signale se trouve à 2
niveaux :
1. Les "/?page=1" vs "/" (forcément, c'est la même page !)
2. Les gens qui ont joué avec les URLs (genre le tuto en
   /tutoriels/123456/vrai-slug/ vs /tutoriels/123456/nimportequoi). Là c'est
   une connerie de conception : ID + slug dans la même URL, et on ne vérifie
   pas le slug, donc on peut y mettre n'importe quoi.

2015-01-19 16:13 GMT+01:00 SpaceFox ujueseo.yeou@gmail.com:

**Comment by SpaceFox** [comment]
... non mais avec un exemple aussi pourri, on a 100% de duplicate, parce
qu'on a virtuellement une infinité de slugs sur ces URLs et seulement un
nombre fini d'URLs valides.

Les robots n'inventent pas des URLs (sinon ils auraient 100% de 404). Le
problème c'est qu'on a vraiment des gens qui ont changé ces URLs, donc les
URLs avec les mauvais slugs se promènent dans la nature et sont indexées.
Pour l'instant, le plus urgent est de faire une redirection de ces URLs
vers la bonne.

Ma question sur le scan complet, c'est qu'avec même pas 10% du contenu
scanné, on a pas la moindre idée de savoir si les chiffres sont
représentatifs de quoi que ce soit !

Donc, à moins que ce scan incomplet n'utilise une méthode inconnue pour
sortir des stats valables ; pour l'instant on ne peut rien en déduire sur
le taux de duplicate content interne. Rien, dans le sens "absolument aucune
conclusion".

Ce qui ne nous empêche pas de noter les problèmes remontés (cette histoire
d'URL foireuse et de ?page=1) et de les corriger.

**Comment by Situphen** [comment]
> Déjà il me signale que "forums/savoirs/site-web/" est le 100% duplicate content de "forums/savoirs/site-web/"... forcément c'est 2x la même page sans paramètres supplémentaires !

C'est parce qu'il définit que http://zestedesavoir.com/un-truc n'est pas pareil que https://zestedesavoir.com/un-truc !

**Comment by gustavi** [comment]
Le problème c'est qu'actuellement on vérifie uniquement le `pk` et non le couple `pk` + `slug`.

**Comment by SpaceFox** [comment]
Pour commencer on a un truc à faire ici : quand on accède à une URL par PK + slug, il faut :
1. Vérifier que les 2 soient cohérents (je sais que c'est fait dans au moins un cas)
2. S'ils sont incohérents, la PK a raison. Donc on doit avoir une redirection permanente vers l'URL avec le bon slug (exemple : /tuto/1234/slug_foireux renvoie toujours vers /tuto/1234/bon_slug).

**Comment by Eskimon** [comment]
Ce ticket a-t-il une réelle valeur ajoutée ou peut-il être fermé ? (en sachant que le souci des slugs non vérifié est dorénavant réglé)

**Comment by pierre-24** [comment]
Ben après qu'on aie mergé la PR de @artragis sur la suppression totale des anciens modules articles/tutos, faudrait voir comment le chiffre a évolué (en mieux, j'espère :-° )

**Comment by Eskimon** [comment]
il a pas tellement évolué, mais j'ai des gros doutes sur la pertinence de l'outil quand même... (parce que bon, moins de 10% des pages testés, et la plupart du temps c'est à cause du paramètre &page=

**Comment by artragis** [comment]
ma pr n'a pas été mergée eskimon :p

**Comment by Eskimon** [comment]
Arf oui je pense avoir mal compris la remarque, mais mon commentaire sur la pertinence de l'outil reste entier

**Comment by GerardPaligot** [comment]
Je suis du même avis du caribou.

**Comment by GerardPaligot** [comment]
- Aucune activité sur l'issue depuis plusieurs mois.
- Pertinence douteuse de l'outil utilisé.
- Il pourrait y avoir un travail à faire sur le couplage `pk` + `slug` mais cette issue ne traite pas directement de ça. Si vous jugez ça vraiment pertinent, je vous invite à ouvrir un autre ticket.

Donc, je ferme. Libre à vous de rouvrir si vous jugez ça toujours pertinent mais j'émettrais de grosses réserves.
