### ISSUE TITLE
Editer un message par du vide valide le message et garde l'ancien

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2081]
Scenario : 
- Je poste dans un topic
- J'edite le post en renseignant la chaine (entre guillemet) :"    "
- Je valide le message.

Le post est envoyé, et l'ancien message est conservé.

La bonne chose a faire serait de refuser le message et afficher un message d'erreur

**Comment by Eskimon** [comment]
je fais ca

**Comment by Eskimon** [comment]
En fait je fais pas, j'ai pas trop de temps...
