### ISSUE TITLE
Le raccourci clavier Ctrl + Enter n'est pas limité

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2082]
Le raccourci Ctrl + Enter qui permet d'envoyer un post n'est pas limité à Ctrl + Enter.

Si je fais Ctrl + Alt + Enter ou Ctrl + Shift + Enter, le message est tout de même posté.

Cette fonctionnalité n'étant pas documentée, je ne sait pas ce qui a été prévu à la base. Pour moi, on devrait limité le raccourci clavier à Ctrl + Enter.

**Comment by Situphen** [comment]
Le ticket concerné était #814. Donc on n'envoie pas quand il y a Shift, Alt ou Alt Gr en plus de Ctrl + Enter ? Ça devrait être simple avec http://api.jquery.com/event.which/

**EDIT :** On fait passer ça en hotfix ou pas ?

**Comment by gustavi** [comment]
Corrigé et mergé ! Merci @Situphen !
