### ISSUE TITLE
Slow queries : requêtes sans limites !

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2085]
Je fais une passe sur le slow-query-log de prod. Contrairement à ce que son nom indique, ce log stocke aussi les requêtes qui nécessitent des tables temporaires.

Il y a pas mal de monde puisque depuis ce matin environ 03h, j'ai déjà 7462 entrées dans ce log...

Qu'est-ce qu'on y trouve ?

Une requête qui récupère **tous** les MP sans aucun critère de sélection !

Elle n'est pas lancée très souvent, mais c'est une garantie de péter à plus ou moins moyen terme.

```
SELECT 
    `mp_privatetopic`.`id`,
    `mp_privatetopic`.`title`,
    `mp_privatetopic`.`subtitle`,
    `mp_privatetopic`.`author_id`,
    `mp_privatetopic`.`last_message_id`,
    `mp_privatetopic`.`pubdate`
FROM
    `mp_privatetopic`;
```

**Comment by Eskimon** [comment]
> Une requête qui récupère tous les MP sans aucun critère de sélection !

WTF ?

**Comment by SpaceFox** [comment]
Exactement !

**Comment by poulp** [comment]
Aucun moyen rapide de localiser l'endroit ou une telle requête est envoyée ?

**Comment by SpaceFox** [comment]
C'est LE problème des ORMs...

2015-01-19 22:17 GMT+01:00 poulp notifications@github.com:

**Comment by SpaceFox** [comment]
D'une manière générale, j'ai l'impression que le module des MP est à inspecter de près car il envoie pas mal de requêtes dans ce log - pour des raisons pas toujours bien claires...

**Comment by Eskimon** [comment]
Je sais pas ou poster donc je met ici ca a l'air assez globale : Un bout de tuto qui se lit bien et vit sur l'ORM Django et des petites opti : http://www.formation-django.fr/framework-django/zoom-sur/orm-django.html

**Comment by Eskimon** [comment]
Et ca aussi tant qu'on y est : https://docs.djangoproject.com/fr/1.7/topics/db/optimization/

**Comment by Eskimon** [comment]
Faudrait surveiller ca à la prochaine release. Etant donnée que le module des MP a été refondu par @GerardPaligot pour l'API des MP on aura ptet du changement ici.

**Comment by GerardPaligot** [comment]
Je ne vois vraiment pas où cette requête pourrait être faite

**Comment by GerardPaligot** [comment]
Je rectifie ce que je viens de dire. @SpaceFox, c'est très possible que la requête soit faite par [munin](https://github.com/zestedesavoir/zds-site/blob/dev/zds/munin/views.py#L24).

Ca expliquerait d'ailleurs le fait qu'elle n'est pas exécutée souvent.

**Comment by SpaceFox** [comment]
C'est bizarre alors, parce que d'après la ligne que tu donnes ça devrait être un `select count(*)...` .

**Comment by GerardPaligot** [comment]
Mh c'est vrai mais c'est le seul que je vois faire ce genre de requête sur absolument tous les MPs. Il n'y a pas moyen de faire une requête via munin et vérifier si la requête SQL de ce ticket est lancée en même temps ?

**Comment by artragis** [comment]
> C'est bizarre alors, parce que d'après la ligne que tu donnes ça devrait être un

oui mais non, les requêtes munin font tous un .all() avant de faire les count().

**Comment by artragis** [comment]
cette requête est-elle encore apparente?

**Comment by GerardPaligot** [comment]
J'aimerais savoir aussi ce qu'il en est de cette requête. :)

**Comment by GerardPaligot** [comment]
@SpaceFox, @gustavi et @vhf Vous avez un moyen de voir si cette requête est toujours exécutée ?

**Comment by vhf** [comment]
Oui. Non.
