### ISSUE TITLE
Slow queries : une requête qui lit beaucoup de lignes

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2086]
Je fais une passe sur le slow-query-log de prod. Contrairement à ce que son nom indique, ce log stocke aussi les requêtes qui nécessitent des tables temporaires.

Il y a pas mal de monde puisque depuis ce matin environ 03h, j'ai déjà 7462 entrées dans ce log...

Qu'est-ce qu'on y trouve ?

Une requête qui n'est capable de se trier qu'à partir d'une table temporaire, ce qui force l'examen de près de 100 000 lignes. En fait ce qui est étrange, c'est que cette requête ne soit paramétrée en aucune façon.

```
SELECT 
    `utils_comment`.`id`,
    `utils_comment`.`author_id`,
    `utils_comment`.`editor_id`,
    `utils_comment`.`ip_address`,
    `utils_comment`.`position`,
    `utils_comment`.`text`,
    `utils_comment`.`text_html`,
    `utils_comment`.`like`,
    `utils_comment`.`dislike`,
    `utils_comment`.`pubdate`,
    `utils_comment`.`update`,
    `utils_comment`.`is_visible`,
    `utils_comment`.`text_hidden`,
    `forum_post`.`comment_ptr_id`,
    `forum_post`.`topic_id`,
    `forum_post`.`is_useful`
FROM
    `forum_post`
        INNER JOIN
    `forum_topic` ON (`forum_post`.`topic_id` = `forum_topic`.`id`)
        INNER JOIN
    `forum_forum` ON (`forum_topic`.`forum_id` = `forum_forum`.`id`)
        LEFT OUTER JOIN
    `forum_forum_group` ON (`forum_forum`.`id` = `forum_forum_group`.`forum_id`)
        INNER JOIN
    `utils_comment` ON (`forum_post`.`comment_ptr_id` = `utils_comment`.`id`)
WHERE
    `forum_forum_group`.`group_id` IS NULL
ORDER BY `utils_comment`.`pubdate` DESC
LIMIT 21;
```

**Comment by Eskimon** [comment]
Bon apparemment ca bricole du coté des forums ca... peut-être qu'avec la refonte du module des forums qui sera bientôt mergée ca impactera ? Bref, a surveiller dans le dev qui arrive

**Comment by GerardPaligot** [comment]
D'après ce que j'en vois de la clause WHERE, ça se traduit en Django par : `topic__forum__group__isnull=True`. Sachant ça, une recherche là dessus nous mène à 4 occurrences à 1 seul endroit, [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/feeds.py#L27).

Cette partie n'est pas touchée par mon refactoring.

**Comment by GerardPaligot** [comment]
@SpaceFox, @gustavi et @vhf Vous avez un moyen de voir si cette requête est toujours exécutée ?

**Comment by gustavi** [comment]
Je ne sais pas comment @SpaceFox faisait pour obtenir ces infos en prod.

**Comment by SpaceFox** [comment]
En analysant les slow queries avec les outils standards pour ce faire.

2016-07-18 14:49 GMT+02:00 Laville Augustin notifications@github.com:

**Comment by vhf** [comment]
@gustavi : `/var/log/mysql/mysql-slow.log`

La requête en question n'est plus présente dans les logs il me semble. Par contre on en a d'autres de gênantes.

**Comment by vhf** [comment]
Celle-ci est particulièrement étrange : 

Elle retourne 97'000 lignes en moyenne, mais n'est partie que 12 fois, ce qui est peu (la slow query qui a le plus tourné est une requête de la home, avec 6487 occurrences).

``` sql
# Count: 12  Time=0.19s (2s)  Lock=0.00s (0s)  Rows=97098.1 (1165177)

SELECT `forum_post`.`comment_ptr_id`
FROM `forum_post`
INNER JOIN `utils_comment` ON (`forum_post`.`comment_ptr_id` = `utils_comment`.`id`)
WHERE (`utils_comment`.`is_visible` = N
       AND `utils_comment`.`position` > N);
```

Idem ici, rare mais trop grosse : 

``` sql
# Count: 11  Time=0.00s (0s)  Lock=0.00s (0s)  Rows=6095.4 (67049)

SELECT `forum_topic`.`id`
FROM `forum_topic`;
```

La requête la plus lente qu'on a est celle-ci : 

``` sql
# Count: 93  Time=0.87s (80s)  Lock=0.00s (0s)  Rows=21.0 (1953)

SELECT `utils_comment`.`id`,
       `utils_comment`.`author_id`,
       `utils_comment`.`editor_id`,
       `utils_comment`.`ip_address`,
       `utils_comment`.`position`,
       `utils_comment`.`text`,
       `utils_comment`.`text_html`,
       `utils_comment`.`like`,
       `utils_comment`.`dislike`,
       `utils_comment`.`pubdate`,
       `utils_comment`.`update`,
       `utils_comment`.`update_index_date`,
       `utils_comment`.`is_visible`,
       `utils_comment`.`text_hidden`,
       `forum_post`.`comment_ptr_id`,
       `forum_post`.`topic_id`,
       `forum_post`.`is_useful`
FROM `forum_post`
INNER JOIN `forum_topic` ON (`forum_post`.`topic_id` = `forum_topic`.`id`)
INNER JOIN `forum_forum` ON (`forum_topic`.`forum_id` = `forum_forum`.`id`)
LEFT OUTER JOIN `forum_forum_group` ON (`forum_forum`.`id` = `forum_forum_group`.`forum_id`)
INNER JOIN `utils_comment` ON (`forum_post`.`comment_ptr_id` = `utils_comment`.`id`)
WHERE `forum_forum_group`.`group_id` IS NULL
ORDER BY `utils_comment`.`pubdate` DESC LIMIT N;
```

**Comment by SpaceFox** [comment]
Sachant que si personne n'a modifié le réglage, sont considérées comme slow
queries les requêtes factuellement lentes et celles qui ont un critère sans
index.

2016-07-18 17:31 GMT+02:00 victor felder notifications@github.com:

**Comment by vhf** [comment]
Je me suis penché sur une slow query qui revenait régulièrement et qui scannait ~67'000 lignes. En fait c'est une stats Munin.

**Comment by gustavi** [comment]
C'est lancé par Munin directelent ou par Munin via Django ?

**Comment by vhf** [comment]
Via Django. Ce qu'il fallait comprendre c'est qu'au final c'est pas du tout important, il faut juste garder en tête en regardant les slow queries qu'elles impactent pas toutes les perfs du site. Munin passe chaque 5 minutes. Si on a 4-5 queries de 0.3s chaque 5 minutes, c'est pas urgent d'améliorer notre django-munin.

Si on a une query de 0.3s sur la homepage ou sur les forums, là c'est la mort et c'est haute priorité de régler ça.
