### ISSUE TITLE
Nombre délirant de requêtes sur les pages forum

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2094]
Petite analyse sur les requêtes SQL :

Même [avec mon fix](https://github.com/zestedesavoir/zds-site/pull/2093), en mode connecté, je compte :
- 665 requêtes sur la home des forums (en première approche surtout la requête 1) (je me suis reconnecté pour vérifier ce chiffre tellement il me paraît débile, mais il est authentique).
- Plus de  300 requêtes sur les pages catégorie (en fonction de la page). Là je sais pas trop, c'est le foutoir et il faudrait creuser.
- 200 à plus de 300 requêtes sur les pages des forums (en fonction de la page). Là je sais pas trop, c'est le foutoir et il faudrait creuser.

À noter que je ne peux pas tester les pages avec des topics, il faudrait que je re-bascule sur l'autre BDD ou que j'importe les topics de prod.

En mode déconnecté, c'est déjà mieux, ce qui me fait dire qu'on peut énormément soigner le header en mode connecté. Néanmoins :
- 4 requêtes pour le menu principal qu'on pourrait facilement mettre en cache sans problème de cohérence, je pense
- 79 requêtes pour la home des forums. Ce qui me fait dire qu'on a un énorme problème avec le mode connecté, qui fait infiniment plus de requêtes que ce qu'il devrait. A voir avec un compte non-staff si on a le même problème.
- Environ 180 requêtes pour les catégories. Là c'est beaucoup plus proche du mode connecté.
- 70 à 80 requêtes sur les pages des forums.

Vraiment, l'immense différence entre le mode connecté et le mode non connecté m'inquiète, et cette différence ne s'explique pas que par le header.

Requête 1 :

```
SELECT 
    `utils_comment`.`id`,
    `utils_comment`.`author_id`,
    `utils_comment`.`editor_id`,
    `utils_comment`.`ip_address`,
    `utils_comment`.`position`,
    `utils_comment`.`text`,
    `utils_comment`.`text_html`,
    `utils_comment`.`like`,
    `utils_comment`.`dislike`,
    `utils_comment`.`pubdate`,
    `utils_comment`.`update`,
    `utils_comment`.`is_visible`,
    `utils_comment`.`text_hidden`,
    `forum_post`.`comment_ptr_id`,
    `forum_post`.`topic_id`,
    `forum_post`.`is_useful`
FROM
    `forum_post`
        INNER JOIN
    `utils_comment` ON (`forum_post`.`comment_ptr_id` = `utils_comment`.`id`)
WHERE
    `forum_post`.`comment_ptr_id` = <id commentaire>
```

Source : templates/forum/includes/forums.part.html ligne 9 : `<div class="topic-description {% if user.is_authenticated and not forum.is_read %}unread{% endif %}">`

**Comment by SpaceFox** [comment]
Voici le coupable : https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/models.py#L125

Je crois que cet exemple est l'illustration parfaite du danger des ORM :)

**Comment by SpaceFox** [comment]
Tout ça pour... afficher une classe qui n'est pas utilisée ! On indique dans le code quels forums contiennent des messages non lus, mais on affiche _jamais_ cette information à l'utilisateur ! (PS : sur les pages forums et catégorie en tous cas...)

**Comment by GerardPaligot** [comment]
Quand je demande à PyCharm les occurrences de la méthode `is_read`, il m'indique 0. Ce code ne semble jamais exécuté.

**Comment by SpaceFox** [comment]
Je n'en trouve qu'une seule, ici : https://github.com/zestedesavoir/zds-site/blob/dev/templates/forum/includes/forums.part.html#L9

Et comme le fait d'avoir cette classe ne change en rien le design, je ne vais pas me prendre la tête et vais tout simplement dégager le tout.

**Comment by GerardPaligot** [comment]
Autant pour moi, j'ignorais qu'il était possible de faire des choses aussi dégueulasse.

**Comment by SpaceFox** [comment]
Ouais, la boucle for planquée dans une méthode qui est elle-même dans une boucle for, ça devient vite très violent...

**Comment by Eskimon** [comment]
Comment êtes-vous arrivée a la conclusion que unread n'est jamais utilisée ?

EDIT : my bad, j'ai confondu Topic / Forum je crois

**Comment by SpaceFox** [comment]
> EDIT : my bad, j'ai confondu Topic / Forum je crois

Je pense que la réponse est dans cette phrase :)

**Comment by gustavi** [comment]
Il y eu une époque où j'avais râlé là dessus #1245 ! Encore une fois, mettre du cache serait pas trop mal si le serveur SQL souffre un peu.

**Comment by SpaceFox** [comment]
> Encore une fois, mettre du cache serait pas trop mal si le serveur SQL souffre un peu.

Non, c'est cacher le problème sous le tapis. En plus le serveur SQL ne souffre pas : c'est Python qui souffre à préparer et traiter les appels.

Là par exemple le serveur de prod a un uptime de  de 8 jour 18 heures ; les consommation CPU sont dans l'ordre d'importance :
1. 8h50 pour chacun des 7 threads Gunicorn
2. 2h50 pour le thread Solr (majoritairement de l'indexation je suppose) + quelques threads vers 15 minutes
3. 13 minutes pour le thread bacula (sauvegarde)
4. 13 minutes pour freshclam (on a ça nous ?)
5. 10 minutes pour clam (idem)
6. 9 minutes 40 pour le 1er thread mysql

La plupart de nos appels "en trop" sont dus à de mauvaises conception. On doit corriger ces conceptions, pas mettre du cache.

**Comment by gustavi** [comment]
Ah mais je suis entièrement d'accord avec toi ! À partir du moment où on est large sur MySQL c'est parfait :)

**Comment by SpaceFox** [comment]
BTW, oui, ça aurait du être corrigé il y a longtemps. On ne l'a pas fait parce que avec peu de volume, le truc tenait très bien et que donc on avait plus urgent à faire.

Maintenant, on s'aperçoit que ça commence à partir en vrille... donc coup, il faut faire quelque chose.

**Comment by SpaceFox** [comment]
Alors j'ai pas le nombre de requêtes et les bases ne sont pas strictement identiques (parce que j'ai la flemme de rapatrier les données des tutos et articles en réalité) entre la préprod et la prod. Néanmoins, en jouant avec l'outil de trace déployé avec l'application, en mode connecté (condition nécessaire pour que ça fonctionne) :
- La home passe de 138540 function calls à 100163 function calls (facteur 1,38)
- L'accueil des forums passe de 492135 function calls à 213706 function calls (facteur 2,3 !)
- L'accueil du bar à smoothies passe de 334446 function calls à 288397 function calls (facteur 1,16)
- Le topic de présentation passe de 378354 function calls à 333840 function calls (facteur 1,13)

Bien évidemment ces chiffres sont très parcellaires et discutables mais ça donne déjà une petite idée.

L'effet est très visible sur l'accueil des forums, qui était l'objet de cette PR.

Sur les pages de forums et de topic, le problème d'affichage des membres (cf #2089) semble plus important. On passe aussi pas mal de temps sur la génération de templates, et là on rejoint #617.
