### ISSUE TITLE
Erreur 500 lors de la création d'un topic avec un mauvais paramètre

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2095]
url concernée : `http://preprod.zestedesavoir.com/forums/sujet/nouveau/?forum=f`

Ceci nous donne une erreur 500

**Comment by Eskimon** [comment]
Que serait-le mieux venu ? Une 404 ?

Pour qui veut faire la correction, ca se passe ici : https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/views.py#L234

Il faut rajouter un `int()` et un catch pour que ca donne un truc comme ca:

```
try:
    forum_pk = int(request.GET["forum"])
except KeyError:
    # problem in variable format
    raise Http404
except ValueError:
    # It is not an integer id !
    raise Http404
```

**Comment by poulp** [comment]
Une erreur 400 est elle adaptée dans ce cas ?

**Comment by Eskimon** [comment]
Moa ca m'irait.

Si toutes ces erreurs pouvaient être traites dans une seule PR ce serait super...

**Comment by gustavi** [comment]
Je suis dessus, faut juste faire une review de toutes les vues, ça va prendre du temps.
