### ISSUE TITLE
la page d'erreur 500 manque de certaines informations

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2096]
Quand on tombe sur la page 500, dans le footer, on voit des informations incomplètes.
- La version n'a pas a être affichée sur la page, mais on voit le mot version, sans le libellé de la version
- La date n'est pas affichée
- Le lien vers l'association n'est pas présent non plus

Screen

![capture](https://cloud.githubusercontent.com/assets/6066015/5813098/eb77810e-a077-11e4-811b-97bf1596d0a7.PNG)

**Comment by SpaceFox** [comment]
Corrigé et mergé.
