### ISSUE TITLE
Le lien du forum Bug et Suggestion de la page 500 n'est pas le bon

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2097]
Quand on est sur une page d'erreur 500, le lien vers le forum bug et suggestion est en dur dans le code. Ce qui fait qu'en préprod, on se retrouve avec un lien qui renvoi vers la prod.

Pas très joli, parce que l'on pourrait poster son bug en prod. De plus le jour ou on change de bugtracker il faudra faire une MEP juste pour modifier ce lien.

**Comment by SpaceFox** [comment]
Corrigé et fermé.
