### ISSUE TITLE
Erreur 500 lors de l'edition malencontreuse d'un message de forum

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2098]
url impactée : `http://preprod.zestedesavoir.com/forums/message/editer/?message=x`

On ne devrait jamais avoir d'erreur 500

**Comment by Eskimon** [comment]
Ca se passe ici: https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/views.py#L613

Il faut la même correction (adaptée bien sur) que pour https://github.com/zestedesavoir/zds-site/issues/2095

**Comment by GerardPaligot** [comment]
Corrigé. Merci à @gustavi et @pierre-24 pour le rebase.
