### ISSUE TITLE
Impossible de cliquer sur "se souvenir de moi" à la connexion

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2101]
Sur la page de connexion, comme on peut le voir dans le screen, si je clique sur "Se souvenir de moi", la case n'est jamais cochée. On dirait qu'elle est désactivée.

Navigateur : Chrome 39.0.2171.99 
OS : Windows 7

**PS : ça marche en prod, mais pas en préprod**

Screen : 
![souvenir](https://cloud.githubusercontent.com/assets/6066015/5813512/129b633e-a07f-11e4-945d-37e7f2b17d8a.PNG)

**Comment by Eskimon** [comment]
@SpaceFox (ou la personne ayant fait la release) : la commande pour générer les traductions a t-elle été faite pendant la release ? J'ai l'impression que c'est la seule chose qui a changée a ce niveau. (oui je sais c'est pas dans le script, ca a du etre oublie).

@firm1 c'est possible que ce soit ca ?

Dans tout les cas, voici le dernier commit ayant eu lieu sur `zds/member/forms.py` https://github.com/zestedesavoir/zds-site/commit/dbbf5552f2c0a28b8b13749cb10bd0b3e6f4181d

**Comment by SpaceFox** [comment]
Si ce n'est pas dans le script, ce ne sera jamais fait…

**Comment by firm1** [comment]
> @firm1 c'est possible que ce soit ca ?

Impossible, c'est un problème de pur front.

**Comment by Eskimon** [comment]
Le bouton fonctionne bien sur ma version locale syncro sur la branche de release. Un fix a du etre poussé ?

**Comment by SpaceFox** [comment]
Ce serait le 2ème bug qui se corrige par magie sur cette branche. Moi ça commence à m'inquiéter...

**Comment by Situphen** [comment]
En fait, ça vient du sprite. Il n'y a pas plus d'images dans `assets/images/sprite@2x/` que dans `assets/images/sprite/` ! Avant, on utilisait tout le temps le `sprite@2x` donc il n'y avait aucun problèmes, mais vu que maintenant on utilise un des deux en fonction de la résolution, ça pause problème... J'essayerai de régler ça demain, si je n'y arrive pas il faudra voir avec @sandhose.

**Comment by Eskimon** [comment]
C'est quoi le rapport avec une checkbox ?

**Comment by sandhose** [comment]
@Situphen Rien à voir: le sprite @1x, c'est juste le @2x redimensionné, donc ça devrait pas poser problème

**Comment by sandhose** [comment]
La règle existe pour le sprite @2x (donc rétina), mais pas pour le "normal". Comme avant on utilisait forcément le sprite rétina, on avait pas le problème. Au passage, vu le code, je dirais que le problème est aussi présent sur les radio. Pour fixer ça, il suffit à priori de rajouter `@include sprite();` [à cet endroit](https://github.com/zestedesavoir/zds-site/blob/c805788c43e744cf51ad9152f1ebfb8a0d452057/assets/scss/_form.scss#L282) (si qqn pouvait s'en occuper, ça m'arrangerait, ping @Situphen :-° )

**Comment by Situphen** [comment]
@Eskimon : on utilise une image à la place de la croix par défaut des checkboxs, et elle est dans le sprite.

@sandhose : je vais essayer de corriger ça demain soir. AMHA, il faudra revoir la génération du sprite car on je vois pas pourquoi on a deux dossier `sprite/` et `sprite@2x`, et des images (logo...) qui ne sont pas dans le sprite. (**EDIT** : Je ferai sûrement une PR demain.)
