### ISSUE TITLE
Erreur 500 lors de l'edition malencontreuse d'un message de mp

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2102]
Url incriminée : `http://preprod.zestedesavoir.com/mp/message/editer/?message=x`

On ne devrait jamais avoir d'erreur 500

**Comment by Eskimon** [comment]
Ca se passe ici: https://github.com/zestedesavoir/zds-site/blob/dev/zds/mp/views.py#L422

Appliquer correction similaire a ici: https://github.com/zestedesavoir/zds-site/issues/2095#issuecomment-70612247

**Comment by GerardPaligot** [comment]
Corrigé. Merci à @gustavi et @pierre-24 pour le rebase.
