### ISSUE TITLE
Erreur 500 lors de l’édition malencontreuse d'un commentaire de tutoriel

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2103]
Url incriminée : `http://preprod.zestedesavoir.com/tutoriels/message/editer/?message=x`

On ne devrait jamais avoir d'erreur 500

**Comment by Eskimon** [comment]
Ca se passe ici: https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L3512

Appliquer correction similaire a ici: https://github.com/zestedesavoir/zds-site/issues/2095#issuecomment-70612247

**Comment by GerardPaligot** [comment]
Corrigé. Merci à @gustavi et @pierre-24 pour le rebase.
