### ISSUE TITLE
Fil d'ariane lors de l'édition d'un message incohérent entre les mps et les forums

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2105]
Quand j'edite un message de MP, dans le fil d'ariane avant `Éditer un message`, le lien derrière le titre du mp me renvoit vers l'**édition du message**

Quand j'édite un message de forum, dans le fil d'ariane avant `Éditer un message`, le lien derrière le titre du topic me renvoit **vers le topic**.

Il faudrait harmoniser ça.

**Comment by gustavi** [comment]
Corrigé et mergé ! Merci @Situphen !
