### ISSUE TITLE
Impossible d'ajouter un auteur pendant l'édition d'un article

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2106]
Scénario  : 
- Je crée un article
- Je clique dans la sidebar sur editer
- Je clique dans la sidebar sur "Gérer les auteurs"
- Non seulement il y'a personne dans la liste (même pas moi), mais je ne peux pas en rajouter

**Comment by A-312** [comment]
Je prends.

**Comment by ghost** [comment]
Ca semble être un problème de back. La vue  n'a pas toutes les variables (authors.all).
- http://127.0.0.1:8000/articles/historique/2/article-unity-3d/ - fonctionne pas
- http://127.0.0.1:8000/articles/off/2/article-unity-3d/ - fonctionne

**Comment by Eskimon** [comment]
ok
