### ISSUE TITLE
Erreur 500 lors de l’édition malencontreuse d'un article

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2107]
Url incriminée : `http://preprod.zestedesavoir.com/articles/editer/?article=xx`

On ne devrait jamais avoir d'erreur 500

**Comment by Eskimon** [comment]
Ca se passe ici: https://github.com/zestedesavoir/zds-site/blob/dev/zds/article/views.py#L304

Appliquer correction similaire a ici: https://github.com/zestedesavoir/zds-site/issues/2095#issuecomment-70612247

**Comment by GerardPaligot** [comment]
Corrigé. Merci à @gustavi et @pierre-24 pour le rebase.
