### ISSUE TITLE
Erreur 500 lors du téléchargement d'un article inexistant

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2112]
Urls incriminée : `http://beta.zestedesavoir.com/articles/telecharger/?article=x`

On ne devrait jamais avoir d'erreur 500

**Comment by Eskimon** [comment]
Ca se passe ici: https://github.com/zestedesavoir/zds-site/blob/dev/zds/article/views.py#L483

Appliquer correction similaire a ici: https://github.com/zestedesavoir/zds-site/issues/2095#issuecomment-70612247

**Comment by gustavi** [comment]
Corrigé et mergé ! Merci @DevHugo !
