### ISSUE TITLE
Le formulaire de demande de reinitialisation n'accepte pas les emails

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2113]
Le texte (cf. capture ci-dessous) nous dit pourtant qu'en rentrant notre email, on pourra demander la reinit de notre mot de passe. Le problème c'est qu'il n'accepte que les pseudo et pas les emails.

![courriel_id](https://cloud.githubusercontent.com/assets/6066015/5815751/e2914f4a-a098-11e4-9d47-bef750da791e.PNG)

**Comment by Eskimon** [comment]
Ok, la sémantique du texte a ete change pour palier a cette erreur.

Maintenant, est-ce utile de proposer l'adresse email ? Si oui il faudrait changer/creer un ticket en "evolution" "futur lointain" pour ajouter la fonctionnalité.

**Comment by firm1** [comment]
Je dirais qu'il faut créer un ticket evolution pour pouvoir reinitialiser depuis son email, sans le pseudo

**Comment by SpaceFox** [comment]
Le texte est corrigé, ce ticket est maintenant une évolution pour ajouter la fonctionnalité.

**Comment by DevHugo** [comment]
Je prends.

**Comment by Axylium** [comment]
HS qui n'a rien à voir, mais pour @DevHugo : Je te vois de plus en plus ici ! Si tu participes au développement activement, demande à @SpaceFox ou @ArnaudCalmettes de te passer dans la team. Ça permettra de t'assigner les issues plus facilement. ;)

**Comment by gustavi** [comment]
En fait il faudrait surtout un second groupe « Contributeurs occasionnels » pour ceux qui contribuent de temps en temps ou alors depuis pas très longtemps avec juste la possibilité d'être assigné à une issue.

**Comment by SpaceFox** [comment]
C'est une excellente idée, si tu sais comment faire.

**Comment by SpaceFox** [comment]
En fait, le groupe existe mais avec un autre nom :)

@DevHugo je t'ai envoyé une invitation.

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé.
