### ISSUE TITLE
Le responsive cassé si je refuse les cookies

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2114]
Le responsive est cassé quand je refuse de me faire pister.

Navigateur : Chrome/Android

Screen : 

![](https://www.dropbox.com/s/tq0d1fpwqskdaqf/Screenshot_2015-01-20-10-19-26.png)

**Comment by Situphen** [comment]
Je ne réussi pas à reproduire le bug. Ton screenshot n'est pas affiché, tu peux en remettre un s'il te plait ? :)

**Comment by Situphen** [comment]
Bon, en prenant le lien directement dans l'HTML, j'ai pu voir le screen. Je n'ai pas réussi à avoir ton bug. Tu peux réessayer ? :)

**Comment by firm1** [comment]
J'ai toujours le bug.

**Comment by Situphen** [comment]
Tu as vidé le cache ? Quelle version d'Android ? Quelle version de Chrome ?

**Comment by firm1** [comment]
Cache vidé plusieurs fois.
url : http://beta.zestedesavoir.com
Navigateur : Chrome 39.0.2171.93
OS : Android 4.3
Smartphone : Galaxy S3
Ecran : 4.8 pouces
Resolution : 720 x 1280 pixels

**Comment by Eskimon** [comment]
Je viens de faire le test sur mon téléphone et tout marche bien:

url : http://beta.zestedesavoir.com
Navigateur : Chrome 40.0.2214.89
OS : Android 4.4.4
Smartphone : OnePlus One
Ecran : 5.5 pouces
Résolution : 1080 x 1920 pixels (Full HD)

**Comment by GerardPaligot** [comment]
Je viens de faire le test sur mes téléphones et tout fonctionne bien :

url : http://beta.zestedesavoir.com
Navigateur : Chrome 39.0.2171.93
OS : Android 5.0.1
Smartphone : Nexus 4
Ecran : 4.7 pouces
Résolution : 1280 x 768

url : http://beta.zestedesavoir.com
Navigateur : Chrome 39.0.2171.93
OS : Android 4.4.4
Smartphone : Galaxy Nexus
Ecran : 4.6 pouces
Résolution : 720 x 1280

**Comment by SpaceFox** [comment]
Non reproductible non plus ici.

url : http://beta.zestedesavoir.com
Navigateur : Opera 26.0.1656.87080
OS : Android 4.4.4
Smartphone : Galaxy S4
Ecran : 4.0 pouces
Résolution : 1080 x 1920

**Comment by firm1** [comment]
Bon le bug est arrivé en prod. Et je l'ai aussi sur un autre smartphone.

Navigateur : Chrome 40
OS: Android 4.4.4
Smartphone : One Plus
Écran : 5.5 pouces

![screenshot_2015-02-02-12-32-19](https://cloud.githubusercontent.com/assets/6066015/5999940/e4a3d0e8-aad7-11e4-9a4b-6ff4095334e0.png)

**Comment by Situphen** [comment]
Tu es vraiment damné ! J'ai essayé de le reproduire sans succès ! :(

**Comment by GerardPaligot** [comment]
@firm1 Est-ce que tu pourrais nous donner ta manipulation exacte (étape par étape) pour reproduire le bug ?

**Comment by firm1** [comment]
Je sais pas trop comment j'arrive là. Tout ce que je sais c'est que sur Chrome je ne suis pas pisté par analytics et après quelques moments de navigation, la home devient comme ça.

Si je reinitialise tout, tout va bien.

**Comment by AmarOk1412** [comment]
Yo. Je confirme le bug. Par contre il me semble vraiment random. Sur les forums l'affichage est encore pire des fois et quand je tente de reproduire le bug, je n'ai plus ce probleme :D  
Navigateur: Firefox 35  
OS: Android 4.1.2  
Smartphone: Motorola Razr i  
Écran: 4.5 pouces  
![screenshot_2015-02-06-17-53-24](https://cloud.githubusercontent.com/assets/1888628/6083553/c1068f4a-ae29-11e4-95db-a7798bd7dc15.png)

**Comment by Axylium** [comment]
Je confirme aussi le bug de mon côté sur la version IE d'un Windows Phone.

Par-contre comme le dit @AmarOk1412 c'est assez aléatoire. Une page peut s'afficher correctement, si je la recharge tout pête..

**Comment by Situphen** [comment]
Vous aviez ce problème avant ?

**Comment by Axylium** [comment]
Moi, non. Je l'ai depuis la v1.5. 

-----Message d'origine-----
De : "Situphen" notifications@github.com
Envoyé : ‎06/‎02/‎2015 18:57
À : "zestedesavoir/zds-site" zds-site@noreply.github.com
Cc : "Flori@n.B"
Objet : Re: [zds-site] Le responsive cassé si je refuse les cookies (#2114)

Vous avez ce problème avant ?

**Comment by AmarOk1412** [comment]
1.5 aussi

**Comment by Eskimon** [comment]
Ca semble bien un souci de 1.5 puisque pour firm1 c'était sur la beta lors de la release et maintenant pour les deux VDD c'est sur la prod qui vient de passer en 1.5.

**Comment by Situphen** [comment]
Je pense que vous pouvez taguer ce ticket en "Régression".

@sandhose : Ça pourrait du faite qu'il y a plus de _media queries_ qu'avant, ce qui ferait "bugger" le navigateur ? Tu en penses quoi ?

**Comment by Eskimon** [comment]
En v1.6 ca le faisait toujours ?
Même question pour la 1.7 avec le changement des trucs sur le bandeau des cookies.

**Comment by AmarOk1412** [comment]
J'ai encore eu le probleme aujourd'hui en 1.6, pas testé la 1.7

**Comment by Situphen** [comment]
@AmarOk : Avec le tracking Google Analytics accepté ou refusé ?

**Comment by Eskimon** [comment]
Ce problème existe-t-il toujours ?

**Comment by Eskimon** [comment]
Je viens de tester sur la beta (avec Ubuntu / Chrome retaillé pour lancer le responsive) et tout semble OK, je ferme.

Si vous souhaitez rouvrir, merci de préciser la version du site (présente dans le footer), si seulement certaines pages bug, et le support de test (mobile, pc, navigateur...)

**Comment by Situphen** [comment]
Vu que c'est aléatoire, il n'est pas vraiment possible de tester.

**Comment by Axylium** [comment]
Perso pour ma part, je rectifie ce que j'ai dis. Car je crois que ça vient plus de ma connexion que du site en lui-même. Car en wifi tout est nickel, cependant sur ma connexion 4G le site n'est plus responsive.

Donc est effectivement, vu que c'est super aléatoire à tester ça risque d'être chaud..
