### ISSUE TITLE
Les +1/-1 ne sont pas supprimé lors de la désinscription

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2115]
Lorsqu'un membre se désinscrit, ses +1/-1 ne sont pas supprimé. En effet, ces derniers sont dénormalisé dans le modele des forums pour des raisons de performances. Cependant il faut tout de meme les retrancher quand l'utilisateur nous quitte.

**Comment by SpaceFox** [comment]
Si avec la PR on pouvait avoir un bout de script SQL pour recalculer les
valeurs dénormalisées à partir de la source, ce serait la perfection :)

**Comment by Cydonia7** [comment]
Je vais tenter ça du coup (cc @Eskimon)

**Comment by Eskimon** [comment]
Super :)

( @SpaceFox si tu as les pouvoirs tu peux ajouter Cydonia7 dans l'orga pour pouvoir le mettre comme "assignee" a la tache ?)

**Comment by Eskimon** [comment]
@Cydonia7 Tout se passera dans cette methode : https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/views.py#L107

Dans un premier temps, il faudra a un moment trouver tout les +1/-1 qu'une personne a fait et les ajouter/retrancher aux messages concernés.

Dans un second temps on regardera pour faire le script de SpaceFox pour recalculer tout les scores

**Comment by Cydonia7** [comment]
Je n'ai pas les droits pour m'assigner moi-même.

Par contre, si je me trompe pas, tout est géré dans la classe Comment et il n'y a aucune mise en cache de faite donc au final il suffit de virer les CommentLike / CommentDislike (je t'ai envoyé un MP plus détaillé à ce sujet @Eskimon)

**Comment by Eskimon** [comment]
Hop je t'ai répondu a propos de l'analyse :)

**Comment by SpaceFox** [comment]
Corrigé et mergé, merci à tous.
