### ISSUE TITLE
L'affichage des tags est cassé sur l'historique d'un tuto

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2122]
En allant sur **l'historique d'un tutoriel**, on se rend compte la position des tags est cassée (cf screen), avec la licence qui descend toute seule.

Il s'agit d'une regression puisque ça fonctionne très bien en prod, mais pas en preprod.

Navigateur Firefox 34/Windows

Screeen : ![historique_false](https://cloud.githubusercontent.com/assets/6066015/5833938/caee16aa-a158-11e4-86f5-117217bbcbb0.PNG)

**Comment by GerardPaligot** [comment]
Le bug ne semble pas apparaitre sur Chrome 39.0.2171.99/OS X.

Edit : Autant pour moi, mon cerveau n'a pas voulu lire "En allant sur l'historique d'un tutoriel". :)

**Comment by gustavi** [comment]
Corrigé et mergé ! Merci @Situphen !
