### ISSUE TITLE
L'historique d'un tutoriel ne nous dit pas quelle version du tuto est en ligne

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2124]
Quand j'ai un tutoriel en ligne, et que je vais dans l'historique de mon tutoriel, impossible de savoir quel est la version en ligne, puisqu'elle n'est pas précisée.

**Comment by firm1** [comment]
Je réouvre ici car l'issue ne me semble pas terminé. On remarque que les balises `<LI>` ont été rajoutée dans la table d'historique, mais il manque le style ces qui va avec.

![tmp_9223-screenshot_2015-02-16-11-23-20-1169894047](https://cloud.githubusercontent.com/assets/6066015/6210348/109e24c6-b5cf-11e4-9713-6725a8fc0980.png)

**Comment by SpaceFox** [comment]
Je ne vois pas le problème ?

2015-02-16 11:29 GMT+01:00 firm1 notifications@github.com:

**Comment by firm1** [comment]
Non seulement la police est trop grande mais il manque qu'un identificateurs visuel qui indique que c'est une liste

**Comment by SpaceFox** [comment]
L'issue est en prod, donc je la ferme. Merci de refaire une issue avec le nouveau problème.
