### ISSUE TITLE
Minituto, incohérence d'affichage du plan entre la version hors ligne et la version en ligne

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2126]
Sur la version en ligne, on affiche entre l'intro et le premier extrait la liste des extrait avec un lien qui mène vers ceux-ci, ce qui n'est pas le cas sur la version hors ligne.

Capture version hors ligne : 

![verite_offline](https://cloud.githubusercontent.com/assets/6066015/5834298/4e632b62-a15c-11e4-881c-69932d839ee7.PNG)

Capture version en ligne : 

![verite_online](https://cloud.githubusercontent.com/assets/6066015/5834300/539fd3a0-a15c-11e4-817b-49d47de83163.PNG)

**Comment by firm1** [comment]
Je réouvre cette issue car elle n'a pas été correctement corrigée.

On aperçois encore une différence entre la version hors ligne et l version en ligne. C'est la fameuse ligne `<hr />` qui l'ont retrouve avant le plan (dans la version hors ligne) et que l'on ne voit pas dans la version en ligne.

**Comment by Eskimon** [comment]
Donc on a rajoute un `hr` a la fin (avant la conclusion) et il en manque une aussi au début ?

**Comment by SpaceFox** [comment]
Cette issue est en prod donc je la ferme. Merci de réouvrir un ticket avec le nouveau problème.
