### ISSUE TITLE
Les titres dans la recherche sont tronqués

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2129]
Les titres des topics affichés dans la recherche sont souvent tronqués sans raison apparente (cf. screen). Il faudrait afficher les titre au complet pour que ce soit plus lisible.

![search-state](https://cloud.githubusercontent.com/assets/6066015/5855670/24e02eae-a23b-11e4-8b7a-84e611c613f4.PNG)

**Comment by Eskimon** [comment]
Bon j'ai regardé un peu, j'ai l'impression que c'est le filtre de coloration qui dit "je colore et vire ce qu'il y a avant" car si je le dégage j'ai ca:

![capture](https://cloud.githubusercontent.com/assets/761168/7669870/12b3c458-fc8a-11e4-8bcd-637d8ff2e750.PNG)

Comparé à ça si je le laisse:

![capture](https://cloud.githubusercontent.com/assets/761168/7669871/34d59c82-fc8a-11e4-988f-7fce1f8de1d6.PNG)

**Comment by Eskimon** [comment]
Long story short, il faut bricoler `highlight` pour avoir un resultat potable : 
- http://grokbase.com/t/gg/django-haystack/132nqw4zrk/showing-more-of-the-highlighted-context
- http://django-haystack.readthedocs.org/en/latest/highlighting.html

**Comment by pierre-24** [comment]
C'est mergé ;)
