### ISSUE TITLE
Signaler une faute dans un chapître donne le mauvais titre de MP

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2130]
Scénario:
- Je vais dans un chapitre d'un tutoriel publié. Par exemple [celui-ci](http://beta.zestedesavoir.com/tutoriels/335/creez-des-applications-pour-android/425/annexes/2163/larchitecture-dandroid/)
- Je clique sur "Signaler une faute dans ce chapitre", une modale s'ouvre
- Je clique sur "Envoyer un MP à l'auteur"

Un nouvel MP est crée avec le titre suivant : `Je voudrais signaler une faute dans le tutoriel "Créez des applications pour Android"`

On devrait plutot avoir le message `Je voudrais signaler une faute dans le tutoriel  "L'architecture d'Android"`

**Comment by poulp** [comment]
c'est pas plutôt `Je voudrais signaler une faute dans le chapitre "L'architecture d'Android"` ?

**Comment by firm1** [comment]
Ouais bien vu

**Comment by DevHugo** [comment]
Normalement, on est bon ici, on peut fermer.

**Comment by GerardPaligot** [comment]
Il y a eu une PR mais elle n'a pas été mergée. Ca été corrigé où ?

**Comment by DevHugo** [comment]
J'ai pas retrouvé la PR d'origine, mais sur la branche dev, ça marche (https://github.com/zestedesavoir/zds-site/blob/b8012fad6ccf756648b211fe50785ba0c0f0e897/templates/tutorial/includes/warn_typo.part.html) .

Git blame : 
https://github.com/zestedesavoir/zds-site/blame/b8012fad6ccf756648b211fe50785ba0c0f0e897/templates/tutorial/includes/warn_typo.part.html

**Comment by Eskimon** [comment]
Ok, merci @poulp !
