### ISSUE TITLE
Affichage d'une partie d'un tutoriel incohérent entre la version en ligne et la version hors ligne

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2132]
L'affichage d'une partie d'un tutoriel hors ligne d'un tutoriel n'est pas la même que la version en ligne.

Exemple hors ligne : http://beta.zestedesavoir.com/tutoriels/off/335/creez-des-applications-pour-android/420/les-bases-indispensables-a-toute-application/

Exemple online : http://beta.zestedesavoir.com/tutoriels/335/creez-des-applications-pour-android/420/les-bases-indispensables-a-toute-application/

**Comment by SpaceFox** [comment]
Corrigé et mergé.
