### ISSUE TITLE
Impossible de selectionner les articles d'une sous catégories

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2134]
En allant sur la page de tous les articles, il est impossible de filtrer pour avoir des articles appartement à une seule sous-catégorie. C'est pourtant déjà faisable avec les tutoriels.

Avoir donc une colonnes "Catégories des articles" dans la sidebar ne serait pas un mal.

**Comment by SpaceFox** [comment]
Corrigé et mergé --> Fermé.

**Comment by firm1** [comment]
Je ré-ouvre cette issue, car elle ne marche pas comme prévue.

Il y a bien toutes les catégories dans la [section des articles](http://beta.zestedesavoir.com/articles/), mais en cliquant sur les sous catégories, elles renvoient vers les tutoriels, et non vers les articles.

**Comment by SpaceFox** [comment]
Cf la #2407 pour ce problème spécifique. Je ferme ici.
