### ISSUE TITLE
Travis utilise la mauvaise version de npm

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2135]
La documentation d'installation des outils front demande à avoir la version 2 de npm.

Cependant travis utilise : 
- node : 0.10.33
- npm : 1.4.28

On a donc une décorrélation entre la documentation et travis, et c'est donc difficile de se fier à travis concernant le front.

**Comment by Situphen** [comment]
Normalement ta PR #2138 règle ça.

**Comment by SpaceFox** [comment]
Corrigé et mergé --> Fermé.
