### ISSUE TITLE
Lenteur de déploiement avec la nouvelle procédure

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2140]
Depuis qu'on est passé à la nouvelle procédure de build et de déploiement du front, c'est beaucoup plus long qu'avant.

En particulier, le build du front compile en particulier du code en C ou C++, ce qui me paraît louche...

Le log généré est complètement monstrueux (> 172 ko) : http://pastebin.com/TDsdbZnz

Est-ce que quelqu'un du front (cc @sandhose @Situphen ) peut regarder si c'est normal ?

**Comment by gustavi** [comment]
@SpaceFox sinon tout se passe bien avec tout ce qui est `collectstatic` ?

**Comment by SpaceFox** [comment]
Yep, ça `collectstatic` marche nickel - cf la fin des logs.

**Comment by SpaceFox** [comment]
Ping @sandhose  et @Situphen

**Comment by Situphen** [comment]
Je pense que c'est normal mais j'aimerais bien l'avis de @sandhose !

**Comment by sandhose** [comment]
### Pourquoi il compile du C/C++ ?

Certains modules node utilisent des bindings C pour soit combler certains manques de fonctionnalité dans node (ex: syscalls kernel, ou interaction avec d'autres packages "natifs"), soit pour des questions de performances. Le module en question, lwip, est un module permettant de manipuler les images, et utilise entre autre libpng et libjpeg pour des questions de perfs. Comme ils ne fournissent pas de ces parties "natives" précompilées, il les compile à la volée depuis les sources. lwip est utilisé par css-sprite pour la génération de sprite.

### C'est toujours aussi lent ?

Non. npm dispose d'un système de cache qui évite de devoir tout retélécharger, et recompiler, même sur une installation fraîche. Vu que c'est la première fois que ça installait certains modules (en l’occurrence, par exemple lwip), il a du tout télécharger et compiler. Ca n'arrivera que la première fois, et éventuellement lors de grosses mises à jour des dépendances.

### Est-ce qu'on peut y faire quelque chose ?

A part en faisant ça en local, et en envoyant ça directement ça sur le serveur, on sera obligé de faire ça à chaque MEP (même si comme dit, ça devrait être plus rapide lors des prochaines MEPP)

**Comment by SpaceFox** [comment]
> Vu que c'est la première fois que ça installait certains modules (en l’occurrence, par exemple lwip)

Attention, ici c'était le déploiement de la **v1.5-RC2**, les modules étaient sensé déjà être présents dans la v1.5-RC1.

Est-ce que ce sont des modules qui ont été ajoutés par un hotfix ou est-ce qu'on a un problème qui fait que le cache n'a pas fait son office correctement ?

**Comment by sandhose** [comment]
Ok my bad, en fait dans le deploy.sh, c'est npm update qui est utilisé, qui va parcourir _toutes_ les dépendances et sous dépendances et les mettre à jour à la dernière version _possible_... Du coup forcément, ça prend trois plombes, et certains packets sont mis à jour, alors que c'est pas nécessaire...

**Comment by SpaceFox** [comment]
OK, donc si tu peux me dire ce qu'il faut corriger - ou faire la PR pour corriger ça - ce serait super :)

(Sur la branche de release si PR tu fais).

**Comment by sandhose** [comment]
J'ai pas d'env de dev opé sous la main, et pas trop le temps de m'en occuper ; tu peux le faire ? Juste à changer dans [cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/server/deploy.sh#L51) le `update` par `install`... Je peux t'assurer à 100% que ça marchera, donc bon :)

**Comment by Situphen** [comment]
Je fais ça ce soir si vous voulez !

**Comment by SpaceFox** [comment]
Correction mergée. J'attends le test en préprod pour fermer ici.

**Comment by Situphen** [comment]
On ferme ici ?

**Comment by SpaceFox** [comment]
A oui exact.
