### ISSUE TITLE
Affichage intro/conclusion chapitre des tutos

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#2141]
Via Mewtow sur le forum

> Bonjour.
> 
> Quand on consulte un big-tutoriel en ligne, les introductions et conclusions ne s'affichent pas. J'ai essayé avec plusieurs tutoriels (et pas que les miens), sur plusieurs PC différents, et le problème survient sur tous les PC testés. Par contre, les introductions et conclusions sont visibles sur les versions hors-ligne et dans l'éditeur.
> 
> Est-ce que le bug est connu ou non ? Je n'ai pas trouvé de trace de connaissance du problème ni sur ce forum ni sur github.

Et en effet, après quelque rapides _tests_ sur différents big-tuto en ligne, les introductions et les conclusions de **chapitre** (j'insiste sur ce fait, car ce n'est pas précisé dans son message), sont absents !

**Comment by SpaceFox** [comment]
On est d'accord pour dire que c'est bien un bug en prod aujourd'hui et pas que en bêta ?

**Comment by Axylium** [comment]
Ça a été reporté par Mewtow sur le forum, donc oui pour la prod. Puis j'ai moi-même regardé sur cette dernière. 

-----Message d'origine-----
De : "SpaceFox" notifications@github.com
Envoyé : ‎27/‎01/‎2015 10:13
À : "zestedesavoir/zds-site" zds-site@noreply.github.com
Objet : Re: [zds-site] Affichage intro/conclusion chapitre des tutos (#2141)

On est d'accord pour dire que c'est bien un bug en prod aujourd'hui et pas que en bêta ?

**Comment by pierre-24** [comment]
Je prend.

**Comment by Eskimon** [comment]
Nickel, bravo @pierre-24 pour la rapidité et l’efficacité !
