### ISSUE TITLE
Petite faute lors de la validation de l'inscription 

### ISSUE THREAD

**Issue by Torejy** [zestedesavoir/zds-site#2142]
Dans la validation du formulaire d'inscription, lorsque le usename est vide, on a :
msg = _(u'Le nom d\'utilisateur ne peut-être vide')
et non
msg = _(u'Le nom d\'utilisateur ne peut être vide')

https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/forms.py#L163

**Comment by SpaceFox** [comment]
Merci, n'hésite pas à faire la PR correspondante si tu sais exactement où est le problème et comment le corriger !

**Comment by DevHugo** [comment]
Faut fermer.

**Comment by gustavi** [comment]
Corrigé et mergé ! Merci @Torejy !
