### ISSUE TITLE
Preprod : Erreur 500 sur tout les profils

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#2152]
Via __Forever : 

> Salut,
> 
> Tout les profils que j'ai testé répondent par Erreur 500.
> 
> Testé:
> - [SpaceFox](http://beta.zestedesavoir.com/membres/voir/SpaceFox/) ;
> - [Nek](http://beta.zestedesavoir.com/membres/voir/Nek/) ;
> - [gustavi](http://beta.zestedesavoir.com/membres/voir/gustavi/) ;
> - [le mien aussi](http://beta.zestedesavoir.com/membres/voir/__forever/).

Effectivement, on se prends une erreur 500 sur les profils mentionnés ci-dessus, mais également avec **tout les profils du site**. L'erreur ne se trouve pas en prod, donc, je suppose que ça été ammené avec la v1.5 (je n'ai pas pu tester en local).

**Comment by SpaceFox** [comment]
Source :
"TemplateSyntaxError Root Cause
Could not parse the remainder: '!profile.is_private' from '!profile.is_private'"

Dans : member/profile.html at line 213

Ça m'étonne qu'un truc pareil ait pu passer les tests en fait.

**Comment by Eskimon** [comment]
> Ça m'étonne qu'un truc pareil ait pu passer les tests en fait.

Parce que la QA se serait concentre sur seulement les profils traite ? C'est balot effectivement

**Comment by SpaceFox** [comment]
Même les tests unitaires en fait. "Aucun profil affichable" ça veut dire qu'on a aucun test unitaire qui affiche ces profils ?

**Comment by artragis** [comment]
C'est moi qui ait introduit le bug. J'ai testé vite fait, ça marchait, mais j'ai sûrement fait une erreur dans mon test. Par contre la QA a dit "c'est bon pour moi", du coup je comprends pas.

**Comment by SpaceFox** [comment]
@artragis tu as le temps de corriger le bug ou quelqu'un d'autre s'en charge ?

**Comment by GerardPaligot** [comment]
> Même les tests unitaires en fait. "Aucun profil affichable" ça veut dire qu'on a aucun test unitaire qui affiche ces profils ?

J'étais aussi étonné que toi pendant le développement de la ZEP-17. C'est pourquoi, je les ai rajouté dans la [PR de la ZEP](https://github.com/zestedesavoir/zds-site/pull/2167/files#diff-3faca8bf94c4192b3d380f14a9c82270R92).

**Comment by pierre-24** [comment]
**tout le monde:** la QA c'est moi et j'avais en tête que ça fonctionnais quand je l'ai fait, je suis peut-être passé à coté de quelque chose, donc _my bad_ (c'est bien la PR qui concernait les bots, nan ?). Bon. Je vais régler ça, parce que c'est correction en une ligne. Et comme @GerardPaligot a mis le TU des profils dans la ZEP-17, avec votre permission, je ne vais pas écrire de TU cette fois-ci.

**Comment by GerardPaligot** [comment]
@pierre-24 : Tu viens de pinger https://github.com/tout. :-°

**Comment by pierre-24** [comment]
Fait ch***.

Bref.

TL;DR : je prend.

**Comment by artragis** [comment]
pas du tout le temps, désolé.

**Comment by SpaceFox** [comment]
Pas de pb, le tout c'est que personne n'attendre que tu le fasse :)

2015-01-29 13:41 GMT+01:00 artragis notifications@github.com:

**Comment by Eskimon** [comment]
C'est réparé, merci @pierre-24 pour l'efficacité !
