### ISSUE TITLE
L'ajax des +1/-1 n'est pas cohérent en cas d'égalité

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2154]
Scenario : 
- Je vais sur un message ou quelqu'un à mis en +1
- Je clique un -1

le problème : il y'a encore la barre verte en dessous du +1 comme si la victoire appartenait au +1

En actualisant la page on voit bien qu'on ne devrait plus avoir de barre en dessous.

**Comment by Eskimon** [comment]
Done, merci @Situphen !
