### ISSUE TITLE
Migrer le fichier des quotes dans la base de donnée

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2155]
Aujourd'hui on se base sur un fichier pour faire defiler des phrases aléatoires sur la home.

Non seulement ça signifie qu'il faut faire une PR+MEP pour rajouter un nouvelle phrase, mais en plus ce n'est pas génial pour les perfs comparé à la base de donnée.

**Comment by SpaceFox** [comment]
On avait déjà eu ce débat au moment d'ajouter ces citations, non ?

> mais en plus ce n'est pas génial pour les perfs comparé à la base de donnée.

C'est une supposition ou une réalité sourcée avec des chiffres ?

**Comment by firm1** [comment]
> C'est une supposition ou une réalité sourcée avec des chiffres ?

bah niveau scalabilité, plus il y'aura de lignes de le fichier, plus la base de donnée sera un meilleur choix.

**Comment by SpaceFox** [comment]
Même réponse que sur #2156: faites une PR là-dessus si ça vous amuse, mais il y a une infinité de choses plus intelligentes à faire d'abord. Tout ce qui est marqué "Bloquant" ou "BUG".

**Comment by GerardPaligot** [comment]
Même conclusion que la PR linké par notre renard juste au dessus : https://github.com/zestedesavoir/zds-site/issues/2156#issuecomment-183652059
