### ISSUE TITLE
Migrer le fichier des mails interdits dans la base de donnée

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2156]
Aujourd'hui on se base sur un fichier pour retrouver les emails interdits à l'inscription et à la modification de l'email. Sauf que : 
- ça implique de passer par tout le process de release pour juste faire une mise à jour dans les adresses interdite. En cas de problème urgent, étant donné que c'est un point de sécurité, si jamais on doit corriger le tir rapidement, on ne sera pas aussi réactif.
- les perfs sont moins bonne du fais qu'on passe en lecture de fichier classique plutôt que par une base de donnée.

**Comment by SpaceFox** [comment]
> En cas de problème urgent, étant donné que c'est un point de sécurité, si jamais on doit corriger le tir rapidement, on ne sera pas aussi réactif.

En fait si, parce qu'il suffit d'aller modifier le fichier directement sur le serveur. Le vrai problème est qu'on aura une désynchronisation.

> les perfs sont moins bonne du fais qu'on passe en lecture de fichier classique plutôt que par une base de donnée.

C'est une supposition ou une réalité sourcée avec des chiffres ?

**Comment by firm1** [comment]
> C'est une supposition ou une réalité sourcée avec des chiffres ?

Ce fichier a déjà 535 lignes, pas besoin de calculer pour voir que c'est plus lent que de lire une table indexée.

**Comment by SpaceFox** [comment]
Sauf qu'un appel en base a un overhead non négligeable en particulier parce que fait à travers un ORM (et ce n'est pas hypothétique : aujourd'hui la majorité du temps passé à exécuter du code sur ZdS, c'est dans l'ORM). C'est pour ça que sans chiffre, l'argument ne tient pas.

Par exemple, [les sources sur le net n'ont pas l'air aussi convaincues que toi](http://stackoverflow.com/questions/4210057/is-a-file-read-faster-than-reading-data-from-the-database) - bien que je te l'accorde, elles ne sont pas faciles à trouver.

**Comment by firm1** [comment]
> Par exemple, les sources sur le net n'ont pas l'air aussi convaincues que toi

Le net n'est pas une source fiable.

Après si ça amuse quelqu'un de faire une étude scientifique pour comprendre pourquoi la solution qui consiste à lire un fichier ici n'est pas une bonne façon de faire, soit, mais moi je trouve pas ça amusant. :(

**Comment by SpaceFox** [comment]
> Le net n'est pas une source fiable.

C'est toujours plus fiable que des suppositions hypothétiques basées sur aucune vérification !

Je ne sais pas. C'est bien ça mon problème : je ne sais **vraiment** pas.

J'aimerais bien que tu comprennes que je ne fais pas ça pour t'emmerder  mais parce qu'ici on a une vraie question sans réponse. Aujourd'hui, toute utilisation de l'ORM a un overhead important, à tel point qu'on passe une majorité du temps de calcul de ZdS dans cet ORM.

... en fait je ne sais même pas pourquoi on se prends la tête là dessus. Ce bout de code n'a aucune importance en terme de performances tellement il est appelé peu souvent - et il n'est pas assez long pour provoquer des lenteurs au processus d'inscription.

Le problème de perfs n'en est pas un. Le problème de réactivité n'en est pas un non plus.

Donc si quelqu'un veut s'amuser à faire une PR là-dessus, pourquoi pas. Mais très honnêtement, il y a environ 100x plus intelligent et urgent à faire, comme par exemple tout ce qui est marqué "Bloquant" puis tout ce qui est marqué "BUG".

L'important est qu'une PR ne soit pas basée sur des suppositions tirées d'un chapeau. On en a déjà beaucoup trop.

J'ajoute qu'une PR devrait venir avec un moyen de re-charger les interdictions mail qu'on a déjà.

**Comment by firm1** [comment]
C'est bien pour ça que l'issue est tagguée en "évolution". Je ne pense pas avoir dis que c'est urgent, ni gravement impactant (quoique je me demande si tu ne me trolle pas là car c'est trop gros).

L'issue est là pour faire mieux tout simplement.

**Comment by SpaceFox** [comment]
Je ne prétends pas ça. Je remets simplement en doute le fait que ce soit "mieux".

**Comment by firm1** [comment]
Don't feed the ... :)

**Comment by SpaceFox** [comment]
Je suis sérieux.

**Comment by Eskimon** [comment]
Bon, j'ai pas d'arguments quantitatif a apporter ici mais plutot "philosophiques" en partant du principe que le gain de perf est minime dans un sens ou l'autre voire inexistant :
- Tout d'abord, ce fichier est uniquement appelé a la création d'un compte ou au changement d'email. Ça représente moins de 20 appels par jour pour le moment. Le jour ou on aura des milliers d'inscriptions par jour on pourra s’inquiéter des perfs :D
- Ensuite, on est pour le partage des infos et du savoir. Sur ce coup-la c'est un avantage et un inconvénient:
  - Un petit malin saura d'avance quels fournisseurs ne pas s'emmerder a tester
  - Mais notre philosophie est aussi d'aider les autres, et si fournir une liste de fournisseur banni ça peut aider alors je suis content
- Enfin, si quelqu'un veut rajouter un fournisseur en comparant notre liste a d'autres références il peut. Si c'est en BDD il ne peut pas et donc on y perd une contribution utile.

Tout ça pour dire que je suis contre un éventuel changement de comment les choses sont traites a l'heure actuelle.

**Comment by SpaceFox** [comment]
> Mais notre philosophie est aussi d'aider les autres, et si fournir une liste de fournisseur banni ça peut aider alors je suis content

D'ailleurs, on a déjà eu une PR pour étoffer sérieusement cette liste.

**Comment by GerardPaligot** [comment]
Sachant que le caribou (CdP) et notre renard de l'espace (DTC) sont d'accords sur le fait que, pour le moment, c'est pas mal de garder le fichier plutôt que de transférer ces données en base, je ferme.

Si un jour, nous avons un problème de performance à cause de ça, nous ouvrirons une nouvelle issue (ou celle-ci) pour faire la manipulation. En attendant ...

**Comment by gustavi** [comment]
L'idéal serait de stocker la liste en cache avec un temps assez long. Ça évite d'ouvrir le fichier à chaque fois, on gagnerait en perf.

**Comment by GerardPaligot** [comment]
@gustavi Si on me montre que nous avons des problèmes de performance à cause de ce fichier, je veux bien re-ouvrir l'issue ou en créer une nouvelle mais je doute qu'on arrive à me le prouver. Ne cherchons pas des problèmes là où il y en a pas (on a déjà bien assez de problème ailleurs).
