### ISSUE TITLE
Les tests ne passent pas sur Windows

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2158]
En lançant les tests sur une machine Windows 8.1, je me suis rendu compte qu'ils ne passent pas tous. Il y'en aivait 3 en echecs et 6 en failures.

Je ne pense pas qu'on ait arreté le support de zds sur Windows

**Comment by SpaceFox** [comment]
C'est très dommage mais ça n'est pas bloquant dans ce sens où ça n'empêche pas le site de fonctionner correctement (merci Travis).

**Comment by firm1** [comment]
C'est bloquant pour le developpeur qui travaille sur Windows ...

**Comment by SpaceFox** [comment]
Les tags ont une signification : "Bloquant", ça veut dire que le site déconne gravement, au point de pouvoir provoquer l'annulation d'une release. Ça ne veut pas dire qu'un développeur n'a plus 100% de la couverture des tests active (ce qui d'ailleurs à ma connaissance n'a **jamais** été le cas, pour cause de Pandoc).

**Comment by GerardPaligot** [comment]
Ok, cette issue n'est pas bloquante comme tu sembles l'entendre mais elle est quand même urgente à régler ! Si des développeurs Windows sont dispos ...

**Comment by Eskimon** [comment]
On a pas statue la dessus mais est-ce qu'on est d'accord pour fermer une fois la PR de doc avec avertissement mergee ?

**Comment by Situphen** [comment]
Up ! On fait quoi ?

**Comment by Eskimon** [comment]
[L'avertissement est la](http://zds-site.readthedocs.org/fr/latest/install/backend-windows-install.html), je ferme puisqu'on pourra pas faire mieux sans contributeurs sur cette plateforme.
