### ISSUE TITLE
Il n'y a plus d'alertes sur les messages non lus

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2160]
Je n'ai plus d'alertes (entendez par là la petite boite rouge sur l'icone des messages) qui m'indique le nombre de MP non lus.

Il s'agit d'une regression introduit avec la 1.5 que je qualifierait de bloquante quand même car la fonctionnalité est très utilisée.

Screen : 

![new_member](https://cloud.githubusercontent.com/assets/6066015/5916651/a31a48e6-a613-11e4-8a76-d9a4382dc2fe.PNG)

**Comment by gustavi** [comment]
@firm1 j'ai bien le nombre sur la version de dev et la préprod ...

**Comment by firm1** [comment]
Screen or it didn't happen :)

**Comment by poulp** [comment]
Quand j'envoie des mp avec les différents utilisateurs de ma version dev ça fonctionne. Par contre lorsque que je publie un article ou un tutoriel je retrouve le bug pour l'auteur de la publi, le mp est marqué non lu mais pas d'alerte sur la top bar.

**Comment by firm1** [comment]
On dirait que la PR qui a cassé la fonctionnalité [est la suivante](https://github.com/zestedesavoir/zds-site/pull/2093), si ça peut aider

**Comment by Eskimon** [comment]
La encore, si on ne trouve pas de solution je peux fournir le revert...

**Comment by SpaceFox** [comment]
Ouais, enfin... entre le bout de code qui est en train d'exploser le serveur et celui qui n'affiche pas de notification dans certains cas, je ne suis pas certain de savoir lequel je préfère...

**Comment by Eskimon** [comment]
En tout cas je confirme, c'est bien ca qui fout le boxon (j'ai fait le revert en local, tout est rentré dans l'ordre)

**Comment by SpaceFox** [comment]
D'autre part, je ne m'explique pas la différence qu'il peut y avoir entre un "vrai" MP et un MP auto. Parce que si j'ai bien compris, c'est les notifications des MP auto qui déconnent.

Ce qui sous-entendrait qu'on a un problème dans l'envoi de MP auto qui ne fonctionne pas comme prévu.

**Comment by SpaceFox** [comment]
PS : Je ne nie pas que le problème est apparu avec ma PR hein.

Par contre je me demande vraiment :
- Si le problème vient de la "nouvelle" méthode de récupération des MP non lus ou s'il vient de la méthode d'envoi des MP automatiques.
- S'il vaut mieux avoir cette fonctionnalité ou s'il vaut mieux alléger la charge du serveur.

Les deux questions sont de vraies questions ; je me penche sur la première ce WE si personne n'y touche d'ici là.

**Comment by firm1** [comment]
D'après mon enquête (2-3 tests en preprod) il s'avère que le problème ne survient pas "pour les mp automatiques" mais plutot **pour les MPs ou je suis le seul participant**.

Donc les MP autos rentrent dans la clause, mais si quelqu'un envoi un mp puis se désinscrit, il tombe dans la même case et le bug apparait.

My 2 cents

**Comment by Eskimon** [comment]
Ah tiens oui je confirme que c'est juste le MP auto qui déconne... Du coup c'est "moins grave mais dommage quand meme".

Petit tip pour pas faire deux fois la requete (d'apres ton commentaire),

```
    topics = list(privatetopics_unread)
    return {'unread': topics, 'total': len(topics)}
```

Comme ca `list` fera la requete et ensuite `len` fera le comptage du truc récupéré

**Comment by poulp** [comment]
Ok j'arrive à reproduire le bug partout, il suffit de créer un nouveau mp avec un participant et de le quitter.

**Comment by SpaceFox** [comment]
Merci @Eskimon  pour le tip.

@firm1 ah oui, j'avais complètement oublié qu'un MP pouvait avoir un seul participant. sans être lu... du coup ça ne m'étonne pas que ce cas ne soit pas géré. Merci pour l'info, maintenant qu'on sait d'où ça vient ça va être beaucoup plus simple à corriger !

**Comment by Eskimon** [comment]
> pour les MPs ou je suis le seul participant.

Je confirme completement ce point... J'ai fait un MP avec admin et user, envoyé une réponse avec user puis virer user de la conversation. Je rafraichit alors l'accueil pour admin et je ne vois pas la notif.

**Comment by Eskimon** [comment]
good job tout le monde les gens !

**Comment by gustavi** [comment]
Note : on peut aussi accéder à la taille d'une `list` ou d'un `dict` (et d'un `tuple` / `str`) via `{{ foor|lenght }}` dans les templates. Ça reste toujours moins performant qu'un `len()`.
