### ISSUE TITLE
Lors de la désinscription, impossible de savoir ce que devient les images que j'ai uploadé

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2161]
Voici le texte que j'ai qui m'explique ce qui va se passer si je me désinscris : 

> Attention firm1, vous êtes sur le point de vous désinscrire de Zeste de Savoir. Voici ce qu'implique cette action qui ne peut être annulée :
> 
>    Toutes vos conversations privées (MP) seront perdues ;
>   Tous vos messages de forums seront anonymisés ;
>    Votre compte et tout ses détails seront supprimés, cela signifie que l'adresse courriel (firm1@zestedesavoir.com) sera effacée du système et votre pseudo (firm1) sera libéré et utilisable par un autre membre ;
>    Vos tutoriels et articles non publiés (brouillon, bêta ou en cours de validation) seront supprimés sans possibilité de récuperation (sauf si d'autres auteurs sont présents lors de la rédaction) ;
>    Vos tutoriels et articles publiés subiront les modifications suivantes :
>        si vous étiez seul, ils seront placés sous la gouvernance du compte "Auteur Externe", sauf demande contraire de votre part à un membre du staff avant votre désinscription ;
>        si vous étiez plusieurs auteurs, vous quitterez le groupe de rédacteurs. Les autres pourront dès lors continuer sans vous.
> 
> Si vous souhaitez poursuivre votre désinscription, cliquez sur le bouton Me désinscrire ci-dessous. Sinon il n'est pas encore trop tard ... 

Je ne sais donc pas ce que deviendra mes galleries d'images

**Comment by tvxb1** [comment]
Je prends cette issue, ça me semble être bien pour me lancer dans la contribution au code :)

**Comment by Situphen** [comment]
@theofabry : tu es en où ? :)
