### ISSUE TITLE
La barre du haut n'est pas compatible écran 10 pouces

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2163]
Via Solid sur le forum

> J'ai vu que ce bug d'affichage existait toujours sur la beta 1.5, donc je viens le signaler ici.
> 
> ![](http://zestedesavoir.com/media/galleries/374/5074ef69-22c5-4f30-9651-900c86f8982f.png.960x960_q85.jpg)
> 
> Dans le menu du forum, "beta zone des tutos et articles" vient au dessus de "l'association".
> 
> Aussi, la petite fleche de déroulement se superpose à "Tutoriels".
> 
> PS : Ecran 10 pouces, Firefox 33, Ubuntu 14.10

**Comment by Eskimon** [comment]
Retour de Solid sur ce bug:

> Plus de problème avec la ligne "beta zone des tutos et articles".
> Toutefois la flèche de déroulement se superpose toujours au menu "tutoriels". Ça n'a pas changé.

(version 15.5)
