### ISSUE TITLE
Problème de typo dans la doc

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2164]
J'ouvre cette issue pour lister les problèmes de typos dans la doc.

[Installation du frontend](http://zds-site.readthedocs.org/fr/latest/install/frontend-install.html)

>  Installez Node.JS et npm grâce aux instructions qui suivent !

Il s'agit plutot de `Node.js`

> Certaines dépendances utilisent `node` au lieu de ``nodejs`, pour y remédier :

Il y'a une quote en trop

> Les instructions détaillées pour toutes les distributions se trouvent dans la **documentation officielle** (en anglais).

Les asterisques se baladent dans le texte

> Pour npm, il suffit de le mettre à jour avec cette commande :
> 
> `sudo npm install -g npm`

Pas besoin de `sudo` pour mettre à jour npm

> `clean` : Nettoie le dossier ``dist/`

On a une quote en trop

> Si vous voulez utiliser directement la commande `gulp [tâche]` au lieu de ``npm run gulp – [tâche]`, il vous faut lancer cette commande avec les droits administrateurs

On a une quote en trop

> Si ça ne fonctionne pas, vous pouvez le faire manuellement grâce à ``rm -rI node_modules/`.

On a une quote en trop

**Comment by SpaceFox** [comment]
Tu n'as pas les droits pour ouvrir directement une PR pour modifier le fichier (via l'éditeur Github) sur ce genre de problèmes ?

Ça doit pouvoir s'arranger, parce qu'ici c'est plus rapide que de faire le ticket :)

**Comment by firm1** [comment]
Je n'ai pas de branche sur mon fork assez synchro avec le repo officiel pour faire ça.

**Comment by SpaceFox** [comment]
Je parlais de faire la branche directement sur le dépôt source (d'où la
nécessité de droits).

Oui, je sais, c'est sale bla bla bla... mais franchement pour des typo, je
n'y vois pas de problème.

2015-01-27 15:52 GMT+01:00 firm1 notifications@github.com:

**Comment by Situphen** [comment]
> On a une quote en trop

C'est du reStructured Text donc il faut deux quotes ; il en manque effectivement une.

> Pas besoin de `sudo` pour mettre à jour npm

Si tu as déjà les droits administrateurs oui, sinon, non.

Si je fais `npm install -g npm`, j'obtiens :

``` shell
npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "npm"
npm ERR! node v0.10.25
npm ERR! npm  v2.1.7
npm ERR! path /usr/bin/npm
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, unlink '/usr/bin/npm'
npm ERR!  { [Error: EACCES, unlink '/usr/bin/npm'] errno: 3, code: 'EACCES', path: '/usr/bin/npm' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/usr/bin/npm'
npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/bin/npm'] errno: 3, code: 'EACCES', path: '/usr/bin/npm' }

npm ERR! Please include the following file with any support request:
npm ERR!     /home/situphen/npm-debug.log
```

---

Je fais une PR pour corriger ça.

**Comment by Situphen** [comment]
PR mergée donc à fermer !
