### ISSUE TITLE
Certaines 404/403 ne sont pas designés

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2165]
url incriminées : `http://beta.zestedesavoir.com/static/papa`

On obtiens une erreur 404 moins belle que les autres.

EDIT : voir https://zestedesavoir.com/forums/sujet/2164/mettre-clem-sur-les-pages-derreur/?page=1

**Comment by firm1** [comment]
Il en va de même pour certaines 403 : `http://beta.zestedesavoir.com/static/`

**Comment by SpaceFox** [comment]
Ah oui, il semblerait que la règle des statics soit prioritaire sur celle
des 404.

Pour moi c'est un argument pour la séparation des statics sur un
sous-domaine particulier.

2015-01-27 16:02 GMT+01:00 firm1 notifications@github.com:

**Comment by Situphen** [comment]
Je pense que c'est juste qu'actuellement les 403 et 404 désignés sont en template Django et que comme les fichiers statiques sont génés directement par nginx, c'est nginx qui envoie en cas de 404 ou 403 sur le `/static/`.

**Comment by gustavi** [comment]
Exactement @Situphen !

**Comment by firm1** [comment]
> Je pense que c'est juste qu'actuellement les 403 et 404 désignés sont en template Django et que comme les fichiers statiques sont génés directement par nginx, c'est nginx qui envoie en cas de 404 ou 403 sur le /static/.

C'est bien le cas, mais on peut aussi designer les pages renvoyée par nginx comme c'est le cas de la [page de maintenance](https://github.com/zestedesavoir/zds-site/blob/dev/errors/maintenance.html). Ce n'est pas le plus urgent, mais ça serait tout de même plus propre.

**Comment by gustavi** [comment]
La solution est assez simple, il faut dans un premier temps faire les templates semblables à https://github.com/zestedesavoir/zds-site/blob/dev/errors/500.html puis intégrer cela à nginx comme décrit dans ce tutoriel https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-to-use-custom-error-pages-on-ubuntu-14-04

**Comment by Nodraak** [comment]
Dans l'absolu, au lieu de dire a Nginx de renvoyer tel fichier html pour une 404, on pourrait lui dire d'appeler django, qui renverrais alors la 404 customisée.

Ca évite de devoir mettre à jour un fichier html à chaque changement du template 404 django.

Un truc dans le genre :

```
        error_page 404 /custom_404.html;
        location = /custom_404.html {
               proxy_pass http://zdsappserver;
               // ... proxy_reverse machin ... bref toute la conf qui correspond a `location /`
        }
```

**Comment by gustavi** [comment]
Voir https://zestedesavoir.com/forums/sujet/2164/mettre-clem-sur-les-pages-derreur/

**Comment by Situphen** [comment]
J'ai commencé un petit boulot [sur cette branche](https://github.com/Situphen/zds-site/tree/error-pages-clem). J'ai modifié les gabarits et mis les images de Jyong, il ne reste plus que du CSS à mettre ! @sandhose, tu peux t'en occuper ?

**Comment by sandhose** [comment]
@Situphen Hm, tu as dû oublier de `git add` les images, puisqu'elles sont pas dans ton commit :no_mouth: 

Aussi, j'ai peur que jiyong ait fourni les images que en @1x, donc pas adaptée aux écrans rétina

**Comment by SpaceFox** [comment]
On a autre chose que du « @1x » sur ce site ?!

**Comment by sandhose** [comment]
@SpaceFox toutes les icônes/les logos (sauf les boutons de l'éditeur) sont en @2x. Si y'a pas de @2x sur les uploads, c'est surtout parce que les thumbnails sont pas déclarées dans cette taille, mais techniquement, y'aurait vraiment de quoi. Et oui, le @2x c'est important, perso je le vois direct sur mon mac quand l'image est pas en @2x, et c'est... moche. C'est pas si visible que ça pour des grandes images, mais pour des trucs type logo/icônes, c'est flagrant.

**Comment by SpaceFox** [comment]
Ha mais c'est une bonne nouvelle, c'est juste que je pensais qu'on en avait pas :)

**Comment by Situphen** [comment]
@sandhose En effet, j'avais oublié le `git add`, voilà qui est fait maintenant ! ;)

**Comment by lypwig** [comment]
Topics associés : [ici](https://zestedesavoir.com/forums/sujet/8715/ajouter-des-images-de-clem-sur-les-pages-derreur) et [ici](https://zestedesavoir.com/forums/sujet/2164/mettre-clem-sur-les-pages-derreur/).

**Comment by gustavi** [comment]
Note : l'issue ici concerne les pages d'erreurs de nginx et non celles de Django

Donc le message ci-dessus est faux.

**Comment by A-312** [comment]
Je peux m'en occuper (janvier), donc c'est les erreurs dans "errors" ?

**Comment by A-312** [comment]
> Dans l'absolu, au lieu de dire a Nginx de renvoyer tel fichier html pour une 404, on pourrait lui dire d'appeler django, qui renverrais alors la 404 customisée.

@Situphen / @artragis Si je fais les erreurs customs une personne avec les droit pourra modifier la configuration nginx pour lier les erreurs aux pages customs ?

**Comment by A-312** [comment]
400 : https://github.com/zestedesavoir/documents-communication/blob/master/illustrations/clem_Jiyong/svg/clem%20bored.svg
401 & 403 : https://github.com/zestedesavoir/documents-communication/blob/master/illustrations/clem_Jiyong/svg/clembodygard.svg
404 https://github.com/zestedesavoir/documents-communication/blob/master/illustrations/clem_Jiyong/svg/clem%20is%20lost.svg
500 https://github.com/zestedesavoir/documents-communication/blob/master/illustrations/clem_Jiyong/svg/clem%20burn.svg

A voir si on doit ajouter des erreurs : https://github.com/zestedesavoir/zds-site/tree/dev/errors mais ça serait bien de déléguer les erreurs 40X à django.

Modifier : 
  - https://github.com/zestedesavoir/zds-site/blob/dev/templates/500.html
  - https://github.com/zestedesavoir/zds-site/blob/dev/templates/404.html
  - https://github.com/zestedesavoir/zds-site/blob/dev/templates/403.html

**Comment by philippemilink** [comment]
Résolu par la PR #6098.

Je viens d'activer les pages d'erreur qui étaient désactivées sur la bêta, donc maintenant on a le même rendu en terme de pages d'erreur sur la prod et la bêta.

**Comment by Situphen** [comment]
Alors je suppose que je les avais désactivé sur la bêta pour faire quelques essais. En fait, un des soucis depuis qu'on a mis en place des pages d'erreurs personnalisées pour les fichiers statiques c'est qu'elles s'appliquent aussi aux autres pages. Là où auparavant on avait les pages 404 et 403 servies par Django avec le gabarit du site web, là on obtient une page sans moyen de retourner au site web, sauf à appuyer sur le bouton précédent du navigateur. C'est assez brutal je trouve.

Je ne sais pas trop quelle est la solution entre améliorer les pages d'erreur statiques pour les rendre moins brutal, ou modifier la configuration nginx pour garder les pages d'erreurs dynamiques de Django quand c'est possible, ou les deux. À réfléchir.
