### ISSUE TITLE
Le fichier pack.zip contenant le build du front n'est plus accessible

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2166]
Le fichier pack.zip contenait l'ensemble des fichier du front pour ceux qui ne voulaient/pouvaient pas installer les outils du front. Depuis la 1.5 ce fichier n'est plus généré, ce qui rend donc l'installation de la stack front obligatoire pour les developpeurs.

Sur la prod l'url est : http://zestedesavoir.com/static/pack.zip

Sur la beta l'url est : http://beta.zestedesavoir.com/static/pack.zip

Dans un cas le fichier est téléchargeable, dans le second cas, il est introuvable.

**Comment by SpaceFox** [comment]
Question : avec la simplification de l'installation du front, et maintenant que la doc correspondante devrait être correcte, ce fichier est-il encore nécessaire ?

**Comment by firm1** [comment]
J'en sais trop rien, je ne l'ai jamais utilisé, mais je remarque juste qu'il a disparu sans raison apparente.

**Comment by Situphen** [comment]
@sandhose l'a effectivement enlevé lors des changements récents des tâches Gulp. Si vous jugez nécessaire qu'il soit présent, ça ne devrait pas prendre trop de temps de remettre ça en place.

**Comment by SpaceFox** [comment]
Je propose que pour s'éviter du travail inutile, on attende que quelqu'un en ait besoin.

**Comment by Situphen** [comment]
Du coup on ferme ?

**Comment by SpaceFox** [comment]
Ouais, je ferme et on rouvrira au besoin.
