### ISSUE TITLE
Marquer un sujet comme non résolu enlève l'avertissement de flood

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2168]
Scenario : 
- Créer un topic : un bandeau s'affiche avec le message "Vous venez de poster. Merci de patienter au moins 15 minutes entre deux messages consécutifs afin de limiter le flood."
- marquer ce topic comme résolu
- actualiser votre page (F5)
- marquez ensuite comme non résolu

Le fameux bandeau a disparu sans raison apparente.

**Comment by ghost** [comment]
Je prends.

**Comment by Situphen** [comment]
Corrigé par #2226 donc à fermer. Il faut aussi fermer #2244 qui n'est plus utile.
