### ISSUE TITLE
Transférer le reste de la documentation dans le dossier Sphinx

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2170]
Aujourd'hui, la documentation du backend est sur Sphinx (`doc/sphinx/source`. Cependant, il reste quelques documentations en markdown qu'il faudrait transférer.
- supprimer `doc/backend-linux-install.md`, `doc/backend-windows-install.md`, `doc/backend-os-x-install.md` et `doc/frontend-install.md` car ils sont maintenant sur Sphinx
- corriger `doc/deploy.md` (mettre un lien vers la documentation d'installation de solr et vers le script de déploiement) et le `README.md`
- mettre `doc/install-solr.md` en reStructured text et les transférer sur Sphinx

Je ne sais pas s'il faut transférer `doc/workflow.md` et `doc/deploy.md` sur Sphinx. Qu'en pensez-vous ?

Je m'attribue ce ticket.

**Comment by GerardPaligot** [comment]
Pour moi, le README doit rester à la racine du projet. C'est le point d'entré principal à la documentation (tant au niveau de GitHub que sur les clones de tous les développeurs).

**Comment by SpaceFox** [comment]
Le README.md et le CONTRIBUTING.md doivent rester à leur place du fait de leurs rôles spécifiques dans Github.

Le reste doit partir sur Sphinx.

**Comment by firm1** [comment]
+1 pour @SpaceFox et @GerardPaligot 

le deploy.md quant à lui n'[est plus a jour par contre](https://github.com/zestedesavoir/zds-site/issues/1510)

**Comment by SpaceFox** [comment]
Et voilà, c'est mergé.

**Comment by poulp** [comment]
Le build de la doc est cassé

**Comment by SpaceFox** [comment]
Oui, cf #2241

**Comment by Situphen** [comment]
@SpaceFox : je crois qu'il voulait dire que la doc ne s'est pas mise à jour sur http://zds-site.readthedocs.org

**Comment by SpaceFox** [comment]
Ah. Possible. Je sais pas, je n'ai pas la moindre idée de comment c'est fait.
