### ISSUE TITLE
L'avertissement de reponse entre-temps est mal affiche

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2176]
L'avertissement signalant qu'il y a eu une reponse entre-temps s'affiche mal : "{% trans "Au moins un nouveau message a été posté dans la discussion pendant que vous rédigiez le votre" %}."

C'est du a la balise strong qui traine dans la chaine d'internationalisation ici : https://github.com/zestedesavoir/zds-site/blob/dev/templates/forum/post/new.html#L33

Il faut la remplacer par:

```
{% blocktrans %}<strong>Au moins un nouveau message a été posté</strong> dans la discussion pendant que vous rédigiez le votre.{% endblocktrans %}
```

Merci A-312 sur IRC pour l'analyse :)

**Comment by Torejy** [comment]
Je prends !

**Comment by gustavi** [comment]
On peut ajouter @Torejy aux contributeurs occasionnels pour l'assigner ici ? PING @SpaceFox

**Comment by Torejy** [comment]
Il y a le même problème sur ce template aussi.
https://github.com/zestedesavoir/zds-site/blob/d2b279fdb56e7f515a3960a1acc82002a56615f0/templates/forum/post/new.html#L33

**Comment by gustavi** [comment]
Tu peux faire d'une PR deux coups ;)

**Comment by SpaceFox** [comment]
> On peut ajouter @Torejy aux contributeurs occasionnels pour l'assigner ici ? PING @SpaceFox

Invitation envoyée.

**Comment by Torejy** [comment]
C'est bête mais c'est justement les lignes que ma PR corrige. :p
