### ISSUE TITLE
Icones de filtres de type d'articles changent de manière incohérente

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2178]
Les icones des filtres de la sibebar qui permettent de filtrer changent sans raison apparente. Regardez les screens.
## Aucun filtre

![filter_no](https://cloud.githubusercontent.com/assets/6066015/5958377/30333c36-a7c4-11e4-9713-c3a0be4b5c92.PNG)
## Filtre bouillons

![filter_draft](https://cloud.githubusercontent.com/assets/6066015/5958379/34f74f14-a7c4-11e4-9d55-49c373053635.PNG)
## Filtre validations

![filter_valida](https://cloud.githubusercontent.com/assets/6066015/5958383/39617048-a7c4-11e4-88ab-fc93f022e9f6.PNG)
## Filtre publics

![filter_public](https://cloud.githubusercontent.com/assets/6066015/5958387/4109c156-a7c4-11e4-9d39-2db7cb99d1f4.PNG)

**Comment by gustavi** [comment]
Problème trouvé : ça vient de la classe `unread` qui a un comportement étrange.

PING @sandhose @Situphen

**Comment by Eskimon** [comment]
Est-ce que ca pourrait venir de la bricole de @SpaceFox https://github.com/zestedesavoir/zds-site/pull/2120 ?

**Comment by gustavi** [comment]
Je ne pense pas, il n'a pas touché aux fichiers SCSS.

**Comment by Situphen** [comment]
Le problème c'est que la classe "unread" correspond aussi à une icône (https://github.com/zestedesavoir/zds-site/blob/dev/assets/scss/_icons.scss#L41). Ce qu'il faut c'est changer le nom de cette classe https://github.com/zestedesavoir/zds-site/blob/dev/assets/scss/_all-supports.scss#L866 par un autre (et aussi modifier les templates) !

**Comment by ghost** [comment]
J'ai corrigé le problème avec une class "selected".
