### ISSUE TITLE
Les adresses emails des pages de contacts sont capturables par les bots

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2179]
Autant pour afficher le mail d'un membre sur sa page profil, on utilise un filtre qui nous permet de masquer l'adresse email aux bots, autant les pour les adresses mails de la page contact, cgu, et asso, on a pas de filtre.

Il serait bon d'appliquer le même filtre (email_obfuscator) sur tous les adresses emails affichés.

**Comment by gustavi** [comment]
Je suis dessus mais actuellement on ne peut pas ajouter un sojet au mailto. 3 options : 
- On supprime le sujet pour le template `pages/template.html`
- J'ajoute un templatetag et je crée une PR sur le projet
- On vire la dépendance et on inclue le code dans nos templatetag vu qu'il est extrêmement simple (https://github.com/morninj/django-email-obfuscator/blob/master/email_obfuscator/templatetags/email_obfuscator.py).

J'ai une préférence pour la 3ème mais je préfère avoir plusieurs avis.

**Comment by DevHugo** [comment]
Je partirais sur la troisième solution, faut aussi voir pour l'attribut target="_top".

**Comment by SpaceFox** [comment]
D'accord pour la 3ème.
