### ISSUE TITLE
Configurer landscape

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2183]
Récemment, nous avons intégré [landscape](https://github.com/zestedesavoir/zds-site/pull/2173), un analyseur static pour mesurer la "santé" de notre code sur plusieurs critères. Avec l'une de mes [PRs](https://github.com/zestedesavoir/zds-site/pull/2167#issuecomment-72098369), j'ai tenté de diminuer les erreurs et les avertissements que cet outil signalait.

Même s'il y avait des remarques pertinentes, j'ai l'impression qu'elles ne le sont pas toutes et qu'il faudrait donc configurer cet outil pour pas qu'il nous signal de fausses erreurs.

**Comment by gustavi** [comment]
#2197 devrait régler une partie des problèmes je l'espère.

**Comment by GerardPaligot** [comment]
Est-ce que nous sommes satisfait de landscape (et clore cette issue) ou est-ce qu'il y a encore des choses à configurer ?

**Comment by Eskimon** [comment]
Je vote pour la fermeture...

**Comment by GerardPaligot** [comment]
Je vote pour la fermeture de landscape...

**Comment by Eskimon** [comment]
Pourquoi ? Ça marche pas si mal non ? (en tout cas perso il m'arrive de m'en servir et je sais que je ne suis pas le seul)

**Comment by Situphen** [comment]
C'est bon ici ?

**Comment by Eskimon** [comment]
Je ferme ce ticket. Landscape semble bien marcher depuis un moment maintenant
