### ISSUE TITLE
Vidéos YouTube qui ne s'affichent plus

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2199]
Je viens de remarquer que les vidéos YouTube ne s'affiche plus sur le site (par exemple sur [ce sujet](https://zestedesavoir.com/forums/sujet/544/mettons-en-musique-la-communaute/?page=7#p36834)) ! Je pense que ça doit venir du récent passage de YouTube en full HTML5, ce qui fait que l'on ne peut plus utiliser des `<iframe>`.

J'ai ce bug sur Firefox et Chrome sous Kubuntu 14.04 et Android 5.0.

**Comment by Situphen** [comment]
YouTube compte bien se passer d'HTML [d'après Numerama](http://www.numerama.com/magazine/32035-youtube-passe-au-html5-par-defaut.html). Cependant :

> Google va aussi mettre en retrait l'ancien code d'intégration Flash ("object") et son API Flash. L'entreprise souhaite désormais que tous les internautes utilisent l'API "iframe", qui utilisera la technologie la plus adaptée au navigateur.

Et elle propose le code suivant :

``` html
<iframe width="420" height="315" src="https://www.youtube.com/embed/qZUUha7gvr4" frameborder="0" allowfullscreen></iframe>
```

Or, nous utilisons bien un `<iframe>` très similaire dans nos pages ! Bref, c'est bizarre ! Quelqu'un a le même bug que moi ?

**Comment by gustavi** [comment]
Bug confirmé (Firefox / Archlinux).

**Comment by Situphen** [comment]
Bug trouvé : on utilise "http" alors qu'il faut utiliser "https" !

**Comment by Situphen** [comment]
Pourtant d'après le code (https://github.com/zestedesavoir/Python-ZMarkdown/blob/master-zds/markdown/extensions/video.py#L139) on génère bien un "https" !

**Comment by Situphen** [comment]
Bug non présent en local et en béta, seulement en prod !

**Comment by Situphen** [comment]
|  | HTTP | HTTPS |
| --- | --- | --- |
| Local | Pas de bug | ? |
| Prod | Pas de bug | Bug |
| Béta | Pas de bug | Bug |

**Comment by gustavi** [comment]
Tu veux pas éditer tes commentaires @Situphen ? Là ça devient pénibles les notifications !

**Comment by Axylium** [comment]
Pour ce qui est de la non présence des vidéos Youtube via le HTTPS c'est connu depuis un bon moment. Il me semble néanmoins que c'est un problème lié à notre markdown.. ping @cgabard

**Comment by Eskimon** [comment]
euh... c'est pas nouveau ce probleme, @cgabard a meme fait un update du markdown pour forcer le passage des videos en https donc normalement elle devrait toujours bien s'afficher si les requirements sont a jour

**Comment by Situphen** [comment]
@Eskimon : cette modification a été faite avant ou après le passage en béta de la v1.5 ? autrement dit, est-ce que le bug devrait être résolu sur la béta ?

**Comment by Eskimon** [comment]
Je viens de test en beta, je peux afficher des vidéos http(s) que je sois connecté en http(s), donc pour moi tout va bien

**Comment by Situphen** [comment]
C'est bon pour moi aussi : je ferme !

**Comment by gustavi** [comment]
On fermera quand on aura confirmation que tout est OK sur la prod.

**Comment by Axylium** [comment]
Je viens de tester sur la bêta, pour moi tout comme Eskimon, c'est bon !

Par-contre sur la prod, c'est une autre histoire..

**Comment by cgabard** [comment]
A noter, sur la prod, que le changement changeant le rendu html ET que les sujets sont mit en caches, des sujets avec vidéos dont le cache html a été généré avant la mise en prod peuvent encore poser problèmes.

En fait il faut vérifier sur la prod que les nouveaux sujet et messages se comportent bien. Si oui, le bug est bien fixé coté markdown et il faudrait dévalider le cache des messages après pour forcer à re-générer le html des sujets qui contenaient déjà des vidéos.

**Comment by cgabard** [comment]
http://zestedesavoir.com/forums/sujet/1035/les-players-youtube-ne-saffichent-pas-en-https/?page=1#p42008

A priori c'est bon sur les nouveaux messages

**Comment by firm1** [comment]
On a une date précise de la dernière mise a jour de Python-ZMarkdown en
prod ? Je peux faire un refresh du cache des forums sur la prod si besoin.

Le lun. 2 févr. 2015 09:49, Christophe Gabard notifications@github.com a
écrit :

**Comment by firm1** [comment]
J'ai lancé le script suivant sur la préprod (je suppose qu'il n' y avait pas grand monde connecté dessus) pour raffraichir le cache.

``` python
from datetime import datetime
from zds.utils.templatetags.emarkdown import emarkdown
from zds.forum.models import Post


start_date = None
end_date = datetime(2015, 1, 1)

posts = Post.objects

# nombre de posts sur la preprod : 25553

if end_date:
    posts = posts.filter(pubdate__lte=end_date)
if start_date:
    posts = posts.filter(pubdate__gte=start_date)

# nombre de posts sur la preprod après réduction : 25530

for post in posts:
    post.text_html = emarkdown(post.text)
    post.save()

# temps écoulé 160 sec = 2 min 40 sec
```

Conclusion, on devrait être dans les mêmes tons pour la prod (entre 3 à 4 min).

On pourrais l'inclure comme commande d'ailleurs. Mais je n'ai pas mes outils de dev à portée.

**Comment by cgabard** [comment]
> On a une date précise de la dernière mise a jour de Python-ZMarkdown en
> prod ?

L'historique git du fichier requierement devrait te donner une date facile
MAIS le cache n'a pas forcément été re-généré à la dernière mise a jour.
Donc je pense que le plus simple serait peut être de forcer une
re-génération total.

Christophe.

**Comment by firm1** [comment]
Etant donné que la PR correspondante est [celle-ci](https://github.com/zestedesavoir/zds-site/pull/1978) mergée le 27 dec, je suppose que la correction a été poussée dans la 1.5 qui a été mise en prod le 01/02/2015.

Donc autant le faire sur tous les posts ?

**Comment by firm1** [comment]
Le script a été rejoué en prod pour raffraichir les anciens caches sur les forums.

Le périmètre était tous les posts qui ont été crée avant le 01 fev 2015, il y'en avait 35 971 et ça a pris ~5 min.

Je ferme donc cette issue

**Comment by Eskimon** [comment]
Il faudrait rejouer ca sur les tutos/articles aussi : https://zestedesavoir.com/tutoriels/613/ajouter-des-sorties-numeriques-a-larduino-le-74hc595/

**Comment by Situphen** [comment]
On peut pas mettre un script dans `server/` qui supprime tous les caches avec des paramètres ? Je vous préviens déjà que je compte modifier la génération de certains éléments Markdown prochainement donc on aura encore besoin du script ! :D

**Comment by firm1** [comment]
> Il faudrait rejouer ca sur les tutos/articles aussi 

Mon script précédent ne peut pas marcher sur les tutos articles. Voici le script qui fonctionnerait bien.

Je n'ai pas d'outil de dev à dispo, dont je ne peux pas faire de PR, donc n'hésitez pas à la faire pour moi (il faudra cependant ajouter sa documentation). Le script sera utilisable avec une commande du style `python manage.py refresh_tutorials ids=672,152` et `python manage.py refresh_articles ids=672,152`

``` python
#zds/utils/management/commands/refresh_tutorials.py

# coding: utf-8

from django.core.management.base import BaseCommand
from zds.tutorial.models import Tutorial, mep
from zds import settings
import os

class Command(BaseCommand):
    args = 'id=1,2,3,4,5'
    help = 'Refesh public tutorials'
    # python manage.py refresh_tutorials id=3,4

    def handle(self, *args, **options):
        ids = []

        for arg in args:
            ps = arg.split("=")
            if len(ps) < 2:
                self.stdout.write(u"Vous devez fournir les identifiants des tutoriels à raffraichir ")
                return
            else:
                if ps[0] in ["id", "ids"]:
                    ids = ps[1].split(",")

            tutorials = Tutorial.objects.filter(pk__in=ids, sha_public__isnull=False).all()
            self.stdout.write(u"Raffraichissement des tutoriels dont les ids sont les suivants :  {}".format(ids))

        for tutorial in tutorials:
            mep(tutorial, tutorial.sha_public)
            self.stdout.write(u"{} : OK".format(tutorial.title))

```

``` python
#zds/utils/management/commands/refresh_articles.py

# coding: utf-8

from django.core.management.base import BaseCommand
from zds.article.models import Article, mep
from zds import settings
import os

class Command(BaseCommand):
    args = 'id=1,2,3,4,5'
    help = 'Refesh public articles'
    # python manage.py refresh_articles id=3,4

    def handle(self, *args, **options):
        ids = []

        for arg in args:
            ps = arg.split("=")
            if len(ps) < 2:
                self.stdout.write(u"Vous devez fournir les identifiants des articles à raffraichir ")
                return
            else:
                if ps[0] in ["id", "ids"]:
                    ids = ps[1].split(",")

            articles = Article.objects.filter(pk__in=ids, sha_public__isnull=False).all()
            self.stdout.write(u"Raffraichissement des articles dont les ids sont les suivants :  {}".format(ids))

        for article in articles:
            mep(article, article.sha_public)
            self.stdout.write(u"{} : OK".format(article.title))

```
