### ISSUE TITLE
Les branches de dev et de prod sont cassées.

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2202]
Le dernier commit qui est passé en prod est [celui-là](https://github.com/zestedesavoir/zds-site/commit/c3056a10cb571994a9ebaeba95ba006906c08d3d), son build travis correspond à [celui-ci](https://travis-ci.org/zestedesavoir/zds-site/builds/49104769).

On constate que la branche crache 2 erreurs au niveau des tests back

Je note ça en bloquant quand on est sur la branche de prod et qu'il faut hotfixer au plus vite pour pouvoir merger quelque chose.

**Comment by firm1** [comment]
On a aussi le meme problème sur [la branche de dev](https://travis-ci.org/zestedesavoir/zds-site/jobs/49104750)

**Comment by GerardPaligot** [comment]
Comment est-ce possible que nous ayons ces branches cassées ?

**Comment by SpaceFox** [comment]
Je me pose exactement la même question.

Ces deux branches viennent de la branche de release, dont le dernier commit est `6eeb2c7e575921e369769c6c51159751ecb2d353`, qui correspond au merge de [cette PR](https://github.com/zestedesavoir/zds-site/pull/2194).

Je soupçonne un problème de Travis, parce que [si on regarde l'historique](https://travis-ci.org/zestedesavoir/zds-site/builds) :
- Le [build 2774](https://travis-ci.org/zestedesavoir/zds-site/builds/49088974) qui correspond au merge de la PR (je ne trouve pas le build de ma branche avant le merge) est HS.
- Le [build 2778](https://travis-ci.org/zestedesavoir/zds-site/builds/49104748) du merge dans `dev` est HS aussi.
- Le [build 2779](https://travis-ci.org/zestedesavoir/zds-site/builds/49104769) du merge dans `prod` est HS aussi. Jusque là c'est cohérent.
- **Mais** le [build 2780](https://travis-ci.org/zestedesavoir/zds-site/builds/49104786) qui correspond au tag `v1.5` est OK... **alors qu'il correspond au même commit que le build 2774 !** (commit `a466f71e42ac60218aa8c56d2c3af5657c730db2`

Donc, je relance ces builds et on verra bien si ça change quelque chose.

**Comment by SpaceFox** [comment]
Youpie, c'est magique : j'ai relancé les builds 2774, 2778 et 2779. Le 2774 passe, pas les autres.

Je me demande à quel point il n'y a pas une collision entre les tests (une sombre question d'ordre pour que ça marche).

**Comment by firm1** [comment]
D'après travis, quand ça foire, le problème vient des tests qui ont été rajouté avec [cette PR](https://github.com/zestedesavoir/zds-site/pull/2194/files).

**Comment by SpaceFox** [comment]
... je vais arrêter de me prendre la tête à faire marcher ZdS si mes interlocuteurs ne prennent pas la peine de lire mes messages.

**Comment by SpaceFox** [comment]
1. https://github.com/zestedesavoir/zds-site/issues/2202#issuecomment-72425243
2. https://github.com/zestedesavoir/zds-site/issues/2202#issuecomment-72428691

**Comment by firm1** [comment]
Biensur que je lis, mais le problème est que justement on a un delta [entre le tag 1.5 et la branche prod](https://github.com/zestedesavoir/zds-site/compare/v1.5...prod).

Donc, il y'a une désynchro quelque part

**Comment by SpaceFox** [comment]
... je ne comprends pas : ton lien dit justement qu'il **n'y a pas** de delta : "0 files changed". Pour te convaincre, [un cas où il y a un delta](https://github.com/zestedesavoir/zds-site/compare/v1.4...prod#files_bucket).

Le seul truc inhabituel de cette release, c'est que la version de Git Flow que j'ai utilisé n'est pas la même que d'habitude, et a collé le tag sur le dernier commit de la branche de release au lieu de le coller sur le merge sur prod. Ce qui ne change rien : c'est le même contenu !

D'autre part, le build 2774 dont je parle plus haut présentait bien le problème. Et ne le présente plus.

**Comment by firm1** [comment]
Quand j'ai crée l'issue le 2774 n'avais pas le souci.

'fin bref, on dirait que ça marche aléatoirement, mais pour corriger, il faut taper dans les deux tests qui failed.

**Comment by SpaceFox** [comment]
> Quand j'ai crée l'issue le 2774 n'avais pas le souci.

... soit y'a un cache quelque part dans Travis que je n'ai pas vu à jour, soit quelqu'un a relancé le build entre ta création d'issue et la mienne et ça a foiré, soit je ne sais pas. Mais quand je suis arrivé sur la liste tout à l'heure, le build était daté de la date du merge.

Et quand bien même, ça n'explique pas le fait que 2774 marche mais pas le 2778, alors qu'ils correspondent très exactement à la même base de code.

**Comment by firm1** [comment]
Et voilà, à la fin du build, le 2774 remarche :) .

**Comment by SpaceFox** [comment]
Oui, mais pourquoi pas les 2 autres ? Celui sur `dev` ça pourrait s'expliquer s'il y avait une autre erreur, mais celui sur `prod` qui correspond très exactement au même code ?!

**Comment by firm1** [comment]
Y'a pas de secret, faut checkouter, et lancer les tests en local plusieurs fois pour comprendre pourquoi sa plante de manière alétoire.

**Comment by DevHugo** [comment]
TLDR: À jour sur dev et des erreurs différentes.

Je suis à jours sur les branches, mon dernier commit de ma branche dev étant le 0caa64e7ae9472fa57e1c59abf1b236598236cae ou plus connus sous le nom de « Finish V1.5 ».

Les tests ne passent pas mais pas avec les mêmes erreurs qu'au dessus : http://pastebin.com/zwUF3evM.
Encore plus drôle, si je demmande qu'à passer le premier test qui fail sous PyCharm, il passe correctement !

**Comment by SpaceFox** [comment]
WTF ?!

**Comment by DevHugo** [comment]
Peut-être que c'est pas liés, cela peut-être juste mon environnement mais bon.

**Comment by firm1** [comment]
@DevHugo ton problème c'est que [tu es sous windows](https://github.com/zestedesavoir/zds-site/issues/2158) :)

**Comment by DevHugo** [comment]
Je suis sous ArchLinux, je vais faire une ré-installation et voir ce que ça donne.

**Comment by firm1** [comment]
Ah donc c'est pas que windows alors :) Car j'ai eu les même erreurs que toi quand j'ai lancé les tests sur windows.

**Comment by DevHugo** [comment]
Pour mes tests qui passent pas, uniquement, j'ai continué un peu l'investiguation, quand j'affiche la valeurs de self dans PrivatePostForm de zds/mp/forms.py. 

J'avais des affichages comme ça: 

``` html
<tr><th><label for="id_text">ee :</label></th><td><textarea cols="40" id="id_text" name="text" placeholder="Votre message au format Markdown." required="required" rows="10">
blabla</textarea></td></tr>
```

or aucun test dans ce fichier, n'utilise la chaine « blabla » mais dans le fichier tests/test_forms.py cette chaine existe. Dans le fichiers des forms, on ajoute donc des réponses avec « blabla ». Collisions des tests. Donc j'ai supprimé ce fichier la, self contient maintennant la bonne valeur mais les tests ne marchent toujours pas /o/.

Aprés, dans le clean du formulaire PrivatePostForm, j'ai ajouté deux affichages: 

``` python
        print self.data['text'] + " vs "
        print text
```

Text est la variable contennant le contenu du message aprés le clean. Les tests me renvoient  « answer vs 

``` html
<bound method CharField.clean of <django.forms.fields.CharField object at 0x7f1750d8cad0>>
```

» 
Donc le .clean() du formulaire pourris la valeur. Dunno why. 

Voila si ça inspire quelqu'un.

PS: peut-être que le fait que le champ, s'apelle text, fait peut-être buggé le truc

**Comment by pierre-24** [comment]
Bon, l'erreur commence a se répandre, ça devient lourd, on l'as systématiquement, maintenant.

**Comment by GerardPaligot** [comment]
Il y a des pistes à ce sujet ? Je tente de reproduire le bug en local, pas moyen ...

**Comment by SpaceFox** [comment]
OK, donc :
- L'erreur ne semble survenir qu'avec MySQL
- C'est un problème de collision entre tests. Comment ça ? Comme ça :
1. `python manage.py test zds/utils` passe nickel. Pas de bol, c'est avec ça que j'ai développé.
2. `python manage.py test` pète...

Si quelqu'un a une idée, je prends. Moi je nage dans le mystère le plus complet.

**Comment by SpaceFox** [comment]
Réduisons le scope : `python manage.py test zds/mp zds/utils` pète aussi. C'est donc bien un problème de collision entre le module de MP et les tests de l'utilitaire qui utilise les MP.

~~Et si je mettais ces derniers tests dans le module de MP ? Est-ce que ça vous paraît correct ?~~

Edit : que ceux qui se posaient la question se rassurent : déplacer le module de tests ne change rien au fait que le test ne fonctionne pas.

PS : détail amusant, `python manage.py test zds/utils zds/mp` lui ne pète pas...

**Comment by SpaceFox** [comment]
La piste la plus probable serait qu'il manque un bout de contexte et que ma source qui disait "sisi les templatetags se testent comme des méthodes normales" s'avérait fausse.

Cela dit, j'ai pas de solution pour ce soir donc ça attendra encore un peu.

Lorsqu'on met une trace dans la méthode, on voit qu'elle fonctionne comme prévu lorsqu'elle est appelée pendant les tests de vue des MP.

**Comment by GerardPaligot** [comment]
Le contexte ne semble pas être la solution finalement. J'ai mis à jour les [tests](https://github.com/GerardPaligot/zds-site/blob/dev/zds/utils/templatetags/tests/tests_interventions.py) par rapport à la [documentation](http://test-driven-django-development.readthedocs.org/en/latest/07-templatetags.html) et des exemples concrets [ici](https://github.com/django/django/blob/master/django/contrib/flatpages/tests/test_templatetags.py) et [là](http://stackoverflow.com/questions/10597423/how-to-get-optional-parameters-for-custom-template-tags-in-django) (où le "ici" sont des tests de tags directement dans django lui-même) et [Travis ne reste pas content](https://travis-ci.org/GerardPaligot/zds-site/jobs/49395587).

Très sincèrement, je commence à sécher. J'y ai passé une bonne partie de la soirée.

**Comment by SpaceFox** [comment]
OK, ça commence à devenir mystique comme truc...

**Comment by GerardPaligot** [comment]
La solution de facilité temporaire serait d'inverser les modules dans la configuration de Travis mais c'est sale ...

**Comment by GerardPaligot** [comment]
Par le plus grand des hasards, est-ce que une base de données est créée pour chaque classe de tests (ce que je ne pense pas) ou une pour tous les tests ? Si c'est la seconde solution, serait-t-il possible que les utilisateurs utilisées dans tes tests @SpaceFox soient aussi utilisées dans le module des MPs et donc que tu ne maitrises pas totalement l'environnement dans lequel tu exécutes les tests ?

**Comment by SpaceFox** [comment]
J'y ai pensé. J'ai affiché les objets `Users.objects.all()` (et aussi les MP) dans le log lors de l'arrivée dans la méthode de test, et cette liste était bien vide.

**Comment by GerardPaligot** [comment]
Est-ce que tu as vérifié aussi que l'état de la base était correct après le setUp ? C'est-à-dire d'avoir bien 2 utilisateurs dans un MP et un message dans cette conversation (si je me souviens bien du test) ? Et ceci dans le cas où tu exécutes le test seul ou à la suite du module des MPs ?

**Comment by SpaceFox** [comment]
Non - et je ne sais pas faire ça autrement qu'à grand coups de débugger et de traces.

**Comment by GerardPaligot** [comment]
Ca serait intéressant de savoir si l'état qu'on veut tester est bien correct à chaque fois parce que :
- Si l'état est correct dans toutes les situations, le bug est vraiment mystique et je m'avoue vaincu.
- Sinon, il y a forcément un lien avec les tests des MPs et/ou l'usage des factories (nous sommes pas à l'abri d'un bug là dedans aussi).

**Comment by GerardPaligot** [comment]
Je re-ouvre, la branche dev semble à nouveau cassé ...

Exemple : https://github.com/zestedesavoir/zds-site/pull/2236 et https://github.com/zestedesavoir/zds-site/pull/2238

**Comment by SpaceFox** [comment]
C'est pas les mêmes erreurs. Il faut rouvrir une issue et y mettre les nouveaux problèmes.
