### ISSUE TITLE
Impossible de télécharger la version markdown d'un tuto quand on est invité

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2203]
C'est peut être voulu (et dans ce cas on peut fermer), mais il est impossible en tant qu'invité de télécharger la version markdown d'un tutoriel publié.

Et pourtant toutes les autres version sont téléchargeable.

**Comment by Situphen** [comment]
@SpaceFox actuellement le téléchargement du fichier Markdown est réservé aux auteurs et aux Staff. Est-ce qu'on doit l'autoriser aux autres ?

**Comment by SpaceFox** [comment]
Je n'en vois pas l'intérêt.

**Comment by Eskimon** [comment]
Donc on ferme. Si qqun le réclame alors on re-ouvrira.
