### ISSUE TITLE
Du code mort et faux à supprimer dans les tutoriels

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2205]
Fonction incriminée 1 : [view_tutorial](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L796)
Fonction incriminée 2 : [export_tutorial_to_md](https://github.com/zestedesavoir/zds-site/blob/f3851a4cf4260c8022dc077f096950e00d1f3da1/zds/utils/tutorials.py#L116)

Il s'agit dans les deux cas, de la ligne `chapter["position_in_tutorial"] = cpt_c * cpt_p` à supprimer.

Elle est fausse car ici `cpt_c` représente le numéro du chapitre et `cpt_p` le numéro de la partie : 

Si on considère l'exemple suivant : 

```
p1
    c1.1 : 1
    c1.2 : 2
    c1.3 : 3
p2
    c2.1 : 4
    c2.2 : 5
    c2.3 : 6
    c2.4 : 7
p3
    c2.5 : 8
    c2.6 : 9
    c2.7 : 10
    c2.8 : 11
```

on se rend bien compte le chapitre c2.1 à la position 4 dans le tutoriel, alors que d'après le code, le chapitre 2.1 à la position `2x1 = 2` dans le tutoriel.

Le code étant inutilisé dans les templates, on peut le supprimer

**Comment by Eskimon** [comment]
Est-ce que la ZEP-12 ne va pas s'en occuper ?

**Comment by pierre-24** [comment]
Très clairement, ce bout de code va disparaitre avec la ZEP-12. Donc est-ce critique, ou pas ?

**Comment by SpaceFox** [comment]
Non. Ça attendra la ZEP-12.
