### ISSUE TITLE
Faute d'orthographe qui s'immisce

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2209]
Quand quelqu'un a réservé un tutoriel en validation et qu'on veut le retirer de la personne, on a le message suivant : "La validation de ce tutoriel est actuellement réservé par xxx . Êtes-vous certain**s** de vouloir le retirer ? "

Il ne devrait pas y avoir de "s" a certain.

**Comment by DevHugo** [comment]
Pour les motivés, c'est sur la ligne 439 du fichier templates/tutorial/tutorial/view.html.

**Comment by SpaceFox** [comment]
C'est fait, merci :)

**Comment by firm1** [comment]
Bon je ré-ouvre désolé, mais je viens de remarquer que je n'ai pas cité toutes les erreurs de la phrase.

"La validation de ce tutoriel est actuellement réservé par xxx . Êtes-vous certains de vouloir le retirer ?"

Il y'avait le problème de "s" à certain, et il faut un "e" à la fin de "réservé"

**Comment by DevHugo** [comment]
Excuse, ma faute, j'ai pas vérifié.
