### ISSUE TITLE
Impossible de se connecter à partir de Facebook

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2217]
Il est impossible de se connecter avec le réseau social de facebook. Une erreur apparait: « Application non configurée: Les développeurs de cette application ne l’ont pas correctement configurée pour se connecter à Facebook. » 

Donc la variable, SOCIAL_AUTH_FACEBOOK_KEY dans le setting.py doit-être mal configuré ou le compte associé ne posséde pas les bonnes url de callback.

Sentry : [là](https://sentry.sandhose.fr/zeste-de-savoir/backend-l7/issues/506/) et [là](https://sentry.sandhose.fr/zeste-de-savoir/backend-l7/issues/505/)

**Comment by Eskimon** [comment]
Je ferme il me semble que tout est bon ici !

**Comment by DevHugo** [comment]
Ça marche pas en prod donc faut pas fermer. Je pense pas que ça soit un probléme au niveau du code mais de la config en prod (La secret key). 

2015-04-21 13:40 GMT+02:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
Il me semblait pourtant avoir vu des gens connecte via Facebook oO (la plupart des pseudo `prenom.nom` je crois)

**Comment by DevHugo** [comment]
Sûrement par g+

**Comment by Eskimon** [comment]
Ah oui j'y pensais plus a lui...

**Comment by Eskimon** [comment]
On pourrait verifier qu'il y a bien une cle pour facebook en prod ?

**Comment by DevHugo** [comment]
Faut attendre que je fasse une PR avant. Facebook n'enregistre pas les emails par-défaut.

Comme Twitter.

**Comment by pierre-24** [comment]
Ok, merci @DevHugo !

**Comment by firm1** [comment]
Ce ticket ne fonctionne pas en beta. Je le réouvre

**Comment by pierre-24** [comment]
Oui, mais est ce que les identifiants pour l'API facebook sont bon sur la bêta ?

(je crois que pour faire la QA, j'avais du "emprunter" le compte  Facebook de @DevHugo et que ça ne fonctionnait qu'avec lui, donc je commencerai par regarder de ce coté là)

**Comment by Eskimon** [comment]
Je sais pas si les identifiants sont bons ou pas mais il y a bien une clé API pour FB, Twitter et G+ dans le settings_prod.py de la préprod

**Comment by pierre-24** [comment]
Compare avec celle de la _prod_ si tu le peux :)

**Comment by Eskimon** [comment]
Je n'ai pas l'accès prod'

**Comment by DevHugo** [comment]
Même sur la prod, les clefs sont pas les bonnes. Faut accéder au compte Facebook et regarder la config pour voir ce qui cloche. Surement que les clefs sont celle de test. Le message d'erreur dit: 

> Application non configurée: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

Heureusement pour nous, on aura pas besoin de faire valider l'app, selon la documentation: 

> Which permissions require review?
> Review is not required to ask for the three basic permissions: public_profile, user_friends and email.

**Comment by pierre-24** [comment]
Ping @SpaceFox ?

**Comment by pierre-24** [comment]
(ou quicquonque qui aie accès aux bons fichiers)

**Comment by Eskimon** [comment]
on est comment ici ? Perso j'ai pas accès au compte facebook, mais @ShigeruM oui :)

**Comment by ShigeruM** [comment]
J'essaie de regarder demain dans la journée.

**Comment by Eskimon** [comment]
ok, MP moi si des choses sont a faire/voir sur le serveur

**Comment by GerardPaligot** [comment]
@ShigeruM Qu'est ce qu'il en est ? :)

**Comment by ShigeruM** [comment]
La dernière fois que j'ai regardé, je n'ai pas trouvé. Je n'ai pas les compétences nécessaires ni, malheureusement , le temps d'acquérir ces compétences en ce moment. Je suis désolé, mais je passe la main.

**Comment by Eskimon** [comment]
J'essaierai de voir avec elyppire

**Comment by GerardPaligot** [comment]
@Eskimon Tu as contacté elyppire au sujet de cette issue ? Elle est quand même ennuyante.

**Comment by gustavi** [comment]
Elle est même bloquante. On perd une des fonctionnalités majeures, à savoir la connexion :/

**Comment by SpaceFox** [comment]
Ça ne peut pas être bloquant, c'est là depuis plus d'un an. En fait, c'en est presque au stade du « en fait tout le monde s'en fout tellement qu'on pourrait tout aussi bien abandonner la fonctionnalité ».

**Comment by gustavi** [comment]
Juste pour information, 78 membres ont été affectés par ce problème.

**Comment by SpaceFox** [comment]
Huh ? Comment on a ce chiffre ?

**Comment by gustavi** [comment]
![http://i.imgur.com/c3GpDpG.png](http://i.imgur.com/c3GpDpG.png)

**Comment by gustavi** [comment]
Quand j'essaye de m'inscrire avec Facebook sur la prod http://i.imgur.com/0O1WhLz.png

Je pense juste que ce sont nos clés API qui sont mauvaises, qui possède les droits là dessus ? cc @SpaceFox

**Comment by SpaceFox** [comment]
Aucune idée, demande au bureau.

**Comment by gustavi** [comment]
@firm1 est-ce toi qui les a ? Si oui peux-tu me les faire passer en privé ?

**Comment by firm1** [comment]
@gustavi malheureusement non je n'ai pas clés de ce compte.

Ceci dit toute la comm a les clés. Et @cgabard et @ArnaudCalmettes en tant que président et vices de l'asso devraient les avoir aussi.

**Comment by cgabard** [comment]
Je n'ai pas (encore) accès au compte FB mais il y a pas une différence entre le compte FB de la page et ces accès à l'API ?

**Comment by firm1** [comment]
> il y a pas une différence entre le compte FB de la page et ces accès à l'API ?

les accès aux clés de l'API sont gérés sur le compte Facebook de Clem

**Comment by GerardPaligot** [comment]
Qui sont les personnes avec les accès au facebook ?

cc @cgabard, @gustavi, @vhf

**Comment by vhf** [comment]
Nous on l'a pas. @cgabard, tu nous le donnes dans le notepad identifiants techniques ?

**Comment by cgabard** [comment]
Il ne me semble pas les avoir ou alors faudrait que je fouille. Demandez à Shigerum il les aura et ça ira plus vite.

**Comment by GerardPaligot** [comment]
Je me charge de le contacter par MP sur ZdS.

**Comment by gustavi** [comment]
Le papa noël est passé et c'est good ici ! Inscription + connexion fonctionnent sur la prod !

Pour la beta faut créer une autre application, etc, etc, etc donc on ne laisse ça que sur la prod (vue que personne n'utilise ça).
