### ISSUE TITLE
Amélioration des performances des forums

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2222]
Les forums (accueil, catégorie, forum lui-même) font des quantités délirantes de requête.

Je crains que la correction de tout ceci n'oblige pas mal de dénormalisation...

Liste non exhaustive :
- 1 requête par sujet suivi
- Accueil
  - 1 requête par forum pour en récupérer les infos
  - 1 requête par forum pour récupérer l'URL, entre autres du dernier message non lu
  - 1 requête par forum pour récupérer les infos du dernier message non lu
  - 1 requête par forum pour récupérer le nombre de topics
  - 1 requête par forum pour récupérer le nombre de posts
- Catégorie : 8 requêtes par forum dont au moins celle de détection des topics non lus en double
- Topic : 6 requêtes par message
  - 1 pour savoir s'il y a des alertes sur le message
  - 1 pour les +1
  - 1 pour les -1
  - 2 pour afficher le badge sous l'avatar du membre (sisi... elle est en double)
  - 1 pour savoir si on a le droit d'afficher le bouton de citation

Résultat des courses : en mode connecté, on s'en tire rarement à moins de 250 requêtes par page.

**Comment by artragis** [comment]
> 1 pour les +1
> 1 pour les -1

j'ai déjà largement amélioré ça dans la zep12 pour les réactions au tuto, voilà comment je fais : 

``` python
 reaction_ids = [reaction.pk for reaction in context['reactions']]
        user_votes = CommentDislike.objects\
            .select_related('note')\
            .filter(user__pk=self.request.user.pk, comments__pk__in=reaction_ids)\
            .all()
        context["user_dislike_dict"] = {reaction.pk: "dislike" for reaction in user_votes}
        user_votes = CommentLike.objects\
            .select_related('note')\
            .filter(user__pk=self.request.user.pk, comments__pk__in=reaction_ids)\
            .all()
        context["user_like_dict"] = {reaction.pk: "like" for reaction in user_votes}
```

**Comment by Eskimon** [comment]
Ce ticket peut-il etre ferme avec la PR "precalcul" d' @artragis ou on garde encore pour plus d'opti ?

**Comment by artragis** [comment]
Etant donné que ce ticket ne donnait aucun objectif réel, il faudra qu'on
regarde en prod ce que ça donne.

Pour l'instant, oui, faut le fermer pour éviter de s'y perdre avec un trop
grand nombre de tickets mais là faudra aller plus loin plus tard.

2015-06-18 11:37 GMT+02:00 Eskimon notifications@github.com:
