### ISSUE TITLE
Améliorer la documentation "Installation du backend sous Windows"

### ISSUE THREAD

**Issue by ghost** [zestedesavoir/zds-site#2227]
Bonjour,

Il faudrait amélioration [la documentation sous Windows](https://github.com/zestedesavoir/zds-site/blob/dev/doc/sphinx/source/install/backend-windows-install.rst), elle n'est pas assez précise.

Je trouves qu'il faudrait ajouter ces mentions :

Il est conseillé de lancer à chaque fois PowerShell en administrateur pour les étapes suivantes et choisissez un répertoire pour le zds par exemple : 

```
cd C:\dev\zestedesavoir
```
- Téléchargez et installez les outils suivants :
  - [PowerShell 3.0+](http://www.microsoft.com/fr-fr/download/details.aspx?id=40855)
  - [Git](http://git-scm.com/download/win) (Git pour Eclipse ne suffit pas ; associez les .sh)
  - ~~[gettext](https://www.gnu.org/software/gettext/)~~ <-- Expliquer ce qui faut faire avec.
- [Téléchargez et installez Python 2.7](https://www.python.org/download/releases/2.7/)
- Installez setuptools : Démarrez Powershell et lancez la commande suivante : `(Invoke-WebRequest https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py).Content | python -`
- Décompressez l'archive setuptools-_XX.X.X_.zip.
- Avec la commande `cd setuptools-XX.X.X`, ouvrer le répertoire possèdant _easy_install.py_.
- Installez pip et tox : `python easy_install.py pip tox`.
- Vous devriez avoir un nouveau répertoire `C:\Python27\Scripts`, rajoutez le dans le PATH (variable d'environnement).
- Réinstallez easyinstall : `python easy_install.py easyinstall`, ça vous permettra de l'utiliser partout, (supprimez l'ancien package).
- Redémarrez Powershell (pour recharger la variable d'environnement PATH).
- Installez Virtualenv avec les commandes suivante : 
  - `pip install virtualenv`
  - `pip install virtualenvwrapper-powershell`
- Désactivez la sécurité sur les script powershell (mode administrateur obligatoire) : `Set-ExecutionPolicy RemoteSigned`, pour autoriser `Import-Module`.
- Créez votre workspace dédié à ZdS (mode administrateur obligatoire).
  - `set $env:WORKON_HOME`
  - ~~`mkdir '~\.virtualenvs'`~~ <== inutile ?
  - `Import-Module virtualenvwrapper`, (_la console PowerShell pourrait hurler ici, mais normalement ça passe, en cas de deuxième essai vous ne devriez plus avoir d'erreur_).
  - `New-VirtualEnvironment zdsenv --no-site-packages`
- Clonez le dépot git _via la console git_ (et pas via powershell) windows: `git clone https://github.com/zestedesavoir/zds-site.git`

(?) Si vous avez `(zdsenv)` à gauche de la zone de saisie, c'est que vous êtes dans l'environnement _zdsenv_.

```
(zdsenv)PS C:\dev\zestedesavoir\
```
# Installation des outils front-end

Il vous faut la version 2.5.0 de npm (et non la version 1.4.X), pour connaitre votre version : `npm -v`. Pour mettre à jour npm, vous avez [trois possibilités](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows), l'une d'elle est de faire `npm install npm` dans le dossier `C:\Program Files (x86)\nodejs`.

Veillez à respecter [ces conditions](https://github.com/TooTallNate/node-gyp#installation), avant de faire  `npm install` (dans l'ordre d'installation) : 
- [Visual C++ 2010 Express](http://go.microsoft.com/?linkid=9709949).
- [Windows 7 64-bit SDK](http://www.microsoft.com/en-us/download/details.aspx?id=8279), si vous êtes en 64bits.  
  **En cas de problème, suivre [ces instructions](http://www.mathworks.com/matlabcentral/answers/95039#answer_104391) :**
  - Désinstallez : **Microsoft Visual C++ 2010 redistributable packages (x86 et x64)**, _dans le panneau de configuration_.
  - Relancez **Windows 7 64-bit SDK**, décochez "**Visual C++ Compilers**" et "**Microsoft Visual C++ 2010**".
  - Appliquez ce patch : [SDK 7.1](http://www.microsoft.com/en-us/download/details.aspx?id=4422).
  - Réinstallez (ils se sont peut-être déjà résintallés tous seuls) [Microsoft Visual C++ 2010 redistributable x64](http://www.microsoft.com/en-us/download/details.aspx?id=14632) et [Microsoft Visual C++ 2010 redistributable x86](http://www.microsoft.com/en-us/download/details.aspx?id=5555).
- Vous devez posséder [Visual Studio Express 2013 pour Windows Desktop](https://app.vssps.visualstudio.com/profile/review?download=true&family=VisualStudioExpressDesktop), la version 2012 ne suffit pas, forcez l'utilisation de vs 2013 comme ceci : `npm install --msvs_version=2013`, il est même conseillé de faire `npm config set msvs_version 2013`, pour les futurs installation.

Il vous faut installer les outils du front-end. Pour cela, rendez-vous sur [la documentation dédiée](frontend-install.html).
# Suite de l'installation
- Dans la console PowerShell via l'environnement zdsenv installez les dépendances.
  - `easy_install lxml`
  - `pip install -r requirements.txt -r requirements-dev.txt`
  - `python manage.py syncdb`
  - `python manage.py migrate`
  - `python manage.py runserver`
- ~~Pour redémarrer virtualenv les fois suivantes : `~\.virtualenvs\zdsenv\Scripts\activate.ps1`~~ Ca ne fonctionne pas comme ça.

Pour faire fonctionner ZdS dans son ensemble vous devez installer les outils LateX et Pandoc.
- Téléchagez et installez [MikTex](http://miktex.org/download)
- Téléchargez et installez [Pandoc](https://github.com/jgm/pandoc/releases)
# FAQ :
#### En cas de problème avec la commande `pip` :
- Vérifiez d'avoir ajouté correctement le chemin vers `C:\Python27\Scripts`. 
- Si vous n'avez pas `pip.exe` à l'intérieur, réinstallez pip (avec `easy_install pip`). 
- Si ils vous dit que vous l'avez déjà, nettoyez ce dossier : `C:\Python27\Lib\site-packages`.

**Comment by Situphen** [comment]
@A-312 : Il y a déjà ma PR #2187 qui modifie les documentations. Pour éviter d'avoir des conflits, je propose que tu attendes le merge de ma PR pour faire la tienne ou que tu fasses une PR sur ma branche. ;)

**Comment by A-312** [comment]
Pour l'instant je n'ai pas réussi à installer sur Windows, donc la documentation ne sera pas modifié.

**Comment by ghost** [comment]
Je te laisse le rajouter à ta PR comme tu l'as mentionné sur IRC, c'est le plus simple.

**Comment by Situphen** [comment]
AMHA, le plus simple est que ce soit toi qui fasse les modifications quand ma PR sera mergée. Pourquoi ? Vu que tu es sur Windows ça te prendre beaucoup moins de temps qu'à moi !

**Comment by ghost** [comment]
D'accord je le fais après que ta PR soit mergée.

**Comment by Situphen** [comment]
Elle a été mergée donc tu peux le faire dès maintenant ! ;)
