### ISSUE TITLE
Remplacer caffeinehit/django-oauth2-provider

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2229]
Comme indiqué partout dans les docs, notre fournisseur d'authentification oauth2 sur l'API est caffeinehit/django-oauth2-provider.

Ce projet [n'est pas compatible avec Django 1.7](https://github.com/zestedesavoir/zds-site/pull/2167#issuecomment-71936587). Pire, son [dernier commit date du 18 mars 2014](https://github.com/caffeinehit/django-oauth2-provider/commit/6b5bc0d3ad706d2aaa47fa476f38406cddd01236) et [le domaine principal est mort](http://www.caffeinehit.com), donc [la PR de compatibilité Django 1.7](https://github.com/caffeinehit/django-oauth2-provider/pull/84) ne sera _jamais_ mergée.

On a donc un problème **bloquant** pour le merge de [la PR de passage à Django 1.7](https://github.com/zestedesavoir/zds-site/pull/1905), et heureusement 3 solutions parce que cette bibliothèque est sous licence MIT.
1. On récupère l'un des [172 forks dont au moins 5 ont déjà une branche "compatibilité Django 1.7"](https://github.com/caffeinehit/django-oauth2-provider/network). Si possible celui qui a l'air le plus maintenu et intégré aux outils genre Pip.
2. On fait notre 173ème fork et 6ème branche de compatibilité Django 1.7 - sans espoir que ce soit jamais remonté dans l'upstream puisqu'il est mort.
3. On trouve une autre bibliothèque de gestion d'oauth2.

Qu'en pensez-vous ?

**Comment by firm1** [comment]
Je ne sais pas s'il faut réouvrir l'issue ou la rennomer, mais visiblement [la nouvelle bibliothèque](https://github.com/evonove/django-oauth-toolkit) n'est pas non plus compatible django 1.7 meme si elle a déjà plus de chance de passer dessus, ce n'est pas encore le cas.

Il y'a bien Zopieux [qui a tenté une PR](https://github.com/evonove/django-oauth-toolkit/pull/186) en ce sens, mais ça n'a pas aboutit.

**Comment by SpaceFox** [comment]
Je lis :

> Django 1.4, 1.5, 1.6, 1.7

D'autre part, [la branche avec Django 1.7](https://github.com/zestedesavoir/zds-site/pull/1905) semble fonctionner.

La PR de Zopieux concerne des cas particulier : est-ce qu'on peut s'assurer que ça nous concerne ?
