### ISSUE TITLE
L'autocompletion ne fonctionne plus

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2230]
Il n'est plus possible d'avoir l'autocomplétion sur la liste des membres quand on crée un message privé

**Comment by GerardPaligot** [comment]
Sera corrigé avec https://github.com/zestedesavoir/zds-site/pull/2228

**Comment by SpaceFox** [comment]
Devrait être OK, mais j'attends quand même le test en QA avec un vrai environnement pour fermer ici.

**Comment by GerardPaligot** [comment]
L'autocompletion semble fonctionner mais ... enfin je vous laisse juger par vous-même :

![capture d ecran 2015-02-08 a 19 46 02](https://cloud.githubusercontent.com/assets/1913901/6097819/34b6bef4-afcb-11e4-915d-93d89de51053.png)

Ceci n'étant plus lié à du back, je retire le label "Back" en "Front".

**Comment by SpaceFox** [comment]
Uh ? Bizarre...

**Comment by ghost** [comment]
Le _autocomplete.scss n'est pas include dans le main.scss.

Je prends.

**Comment by SpaceFox** [comment]
Pensez à attribuer l'issue à une version quand vous la fermez (sinon on va les oublier dans la liste des issues de la prochaine release).

**Comment by firm1** [comment]
Je ré-ouvre cette issue, car l'autocomplétion a un léger problème d'affichage quand on ajoute un auteur à un tutoriel/article (cf screen).

Navigateur : Firefox 35

![capture d ecran de 2015-02-14 23 32 37](https://cloud.githubusercontent.com/assets/6066015/6202535/6fd9f93a-b4f1-11e4-90be-501352a6fae7.png)

**Comment by Situphen** [comment]
A fermer car corrigé par #2323 !
