### ISSUE TITLE
Impossible de modifier son mot de passe

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2233]
Scenario.
- Je vais sur la page : http://beta.zestedesavoir.com/membres/parametres/compte/
- **le premier problème est que j'ai un message qui m'indique que certains champs sont obligatoire comme si j'avais soumis un formulaire**
- je modifie mon mot de passe
- je n'ai aucun messge d'erreur, mais en vrai **Le mot de passe est resté le meme**

**Comment by gustavi** [comment]
Bug assez étrange, ce formulaire n'a pas été modifié par la ZEP-17 (pour la partie « Ce champ est obligatoire »).
