### ISSUE TITLE
Question: Peut-on rencontrer un problème de sécurité si on ouvre le port du zds ?

### ISSUE THREAD

**Issue by ghost** [zestedesavoir/zds-site#2239]
Bonjour,

Je voudrais savoir si le fait d'ouvrir le port du zds (8000) sous Windows, pour donner accès à la copie qu'on a en local à d'autres internautes, ne cause pas de problème de sécurité spécifique ?

A312.

**Comment by Situphen** [comment]
Si ce n'est que ta copie local, je ne vois pas pourquoi ça causerait des problèmes vu que le code source est ouvert ! ;)

**Comment by ghost** [comment]
(Faute de frappe dans le numéro de l'issue, mon fix n'a rien avoir avec cette issue).
