### ISSUE TITLE
Possible d'envoyer des messages vides en MP et sur les forums

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#2245]
Via PG06 sur la bêta. 

> Bonjour ! :)
> 
> J'ai découvert qu'on ne pouvait pas poster de messages vides ou ne contenant que des espaces, mais en revanche c'est possible en mettant en forme cet ensemble vide, par exemple avec ** ** ou même simplement ****, puisque dans ce cas le Markdown n'affiche pas ces caractères, mais la zone de test n'est pas vide.
> 
> [Voici un exemple.](http://beta.zestedesavoir.com/forums/sujet/1793/sujet-de-test-whatever/?page=1#p30875)
> Source:[PG06](http://preprod.zestedesavoir.com/forums/sujet/1813/possibilite-decrire-un-message-vide/?page=1#p30874)

Et, effectivement c'est possible..

**Comment by Axylium** [comment]
Ce problème s'étend jusqu'au topics. On peut facilement créer un topic vide via l'ajout dans le titre de `$`.

**Comment by Situphen** [comment]
Le message d'exemple de PG06 n'est pas vide, il contient un `<hr/>`, c'est-à-dire un barre de séparation.

De toute façon, c'est utopique que penser que ZdS peut analyser le message et voir s'il contient vraiment un message ou juste du code HTML. Si jamais un message comme ça est trouvé, on le signale et les modérateurs font leur boulot !

**Comment by Axylium** [comment]
> Le message d'exemple de PG06 n'est pas vide, il contient un <hr/>, c'est-à-dire un barre de séparation. 

Ce `<hr />` est automatiquement rajouté. J'ai testé moi-même ce bug avec un message vide.

> De toute façon, c'est utopique que penser que ZdS peut analyser le message et voir s'il contient vraiment un message ou juste du code HTML. Si jamais un message comme ça est trouvé, on le signale et les modérateurs font leur boulot !

Oui mais bon, si on pourrait éviter d'avoir une faille qui permettrait à des p'tits malins de faire les fifous, ça serait cool. :) Au-moins ce bug est connu et l'issue qui va avec, créée.

**Comment by firm1** [comment]
Pour ce bug, la façon de faire assez propre serait de vérifier le formulaire à coup de [striptag](https://docs.djangoproject.com/en/1.7/ref/templates/builtins/#striptags) sur le html.

**Comment by GerardPaligot** [comment]
Est-ce qu'on veut vraiment corriger ça ? Je veux dire : oui on empêche de poster des messages vides mais la manière de contourner la règle est ridicule et ne fait vraiment pas de mal hormis le fait qu'un membre peut effectivement créer un message qui parait vide.

**Comment by Eskimon** [comment]
Je suis assez d'accord. Je le passe en zombie pour garder une trace, mais la correction me semble illusoire...
