### ISSUE TITLE
La doc ReadTheDocs ne builde plus

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2246]
La doc ReadTheDocs ne builde plus.

On a un log d'erreurs ici : https://readthedocs.org/builds/zds-site/2293784/

Personnellement je n'y comprends rien. Je soupçonne le fait qu'on ait déplacé notre répertoire de sources de la doc... sauf que je ne trouve nulle trace de paramètre permettant de changer ça dans ReadTheDocs.

En fait, je ne trouve nulle trace de paramètre tout court. Par exemple, j'aimerais bien faire ça propre, lui demander de sortir une doc par version + dev... mais comment ?

**Comment by poulp** [comment]
Dans le menu admin normalement on peut choisir les version à mettre à disposition (latest, master (branches), 1.4, 1.5 (tag) etc.) et toujours dans le même menu, si le dossier doc a bougé, il faut faire pointer vers le fichier `conf.py`

**Comment by SpaceFox** [comment]
Alors je ne sais pas où est ce menu admin. Soit je ne l'ai pas dans l'interface de readthedocs, soit il est ailleurs.

**Comment by poulp** [comment]
![readoc](https://cloud.githubusercontent.com/assets/819246/6094114/a7b52670-af1c-11e4-81b0-985570c49bdb.png)

**Comment by SpaceFox** [comment]
C'est bien ce que je dis : je n'ai pas ce menu.

**Comment by poulp** [comment]
Il faut être identifié et proprio du dépôt

**Comment by SpaceFox** [comment]
En fait, je ne comprends rien à l'interface de cet outils (ceux qui l'ont conçue devraient prendre des cours d'ergonomie, c'est une catastrophe).

Une fois un compte créé, je peux aller sur le projet de ZdS. Je peux faire certaines actions, comme relancer des builds. Par contre, je ne peux rien faire côté gestion, même pas le mettre en bookmark - alors en demander la propriété...

**Comment by poulp** [comment]
Ben normalement il doit y avoir une personne admin ( celle qui a crée le compte sur readthedocs, qui est ce ? ) qui a accès à la gestion, elle peut aussi ajouter des personnes avec les même droits.

**Comment by Situphen** [comment]
Normalement il devrait y avoir un compte admin du projet, non ? Il faudrait demander à nohar ou @devock s'ils savent.

**Comment by SpaceFox** [comment]
> celle qui a crée le compte sur readthedocs, qui est ce ?

Pas la moindre idée. On peut savoir ça sans faire une enquête ?

**Comment by poulp** [comment]
> Pas la moindre idée. On peut savoir ça sans faire une enquête ?

Sur la page d'acceuil du projet : Owners -> zestedesavoir
Voila j'imagine qu'il faudra une enquête ^^

**Comment by SpaceFox** [comment]
C'est donc la 2ème fois ce soir que je regrette de dépendre d'un outil externe...

**Comment by pierre-24** [comment]
C'est @firm1 qui l'as créé. Et de base, c'est plutôt fiable. De base ...

**Comment by firm1** [comment]
Il y'a pas de secret. Deux choses se sont passés ici : 
- La doc est passée de `doc/sphinx/source` à `doc/source` et donc readthedocs était un peu perdu
- [Cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/doc/source/conf.py#L18) (qui fait planter la compil de la doc) a été rajoutée.

J'ai revus les paramètres de readthedocs ( @SpaceFox je t'envoi les ids en effet ), mais il manque le problème dans le code qui persiste.

**Comment by pierre-24** [comment]
Ping @Situphen  ?

**Comment by SpaceFox** [comment]
@firm1 tu n'oublieras pas de m'envoyer les IDs :)

**Comment by SpaceFox** [comment]
Quelqu'un peut vérifier sur le site si c'est OK maintenant ?

**Comment by Situphen** [comment]
C'est OK pour la version web et l'ePub. Je verrai si je peux faire quelque chose pour la version PDF !

**EDIT :** La version pdf échoue car il y a des caractères unicodes (├) dans la partie sur le design. D'après ce commentaires sur le dépôt de readthedocs https://github.com/rtfd/readthedocs.org/issues/416#issuecomment-61596994 il y aurait une solution.

**Comment by poulp** [comment]
Le build des anciennes versions ne marche pas, je sais pas si c'est important, mais à préciser.

**Comment by SpaceFox** [comment]
OK. J'avais activé les versions anciennes surtout "pour faire bien", je dégagerai toutes celles qui foirent.

@Situphen j'attends ton retour pour fermer ici.

**Comment by Situphen** [comment]
Le PDF s'est bien généré donc on peut fermer !
