### ISSUE TITLE
Pourquoi tox et comment ça marche ?

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2247]
Quelqu'un m'explique c'est quoi cette daube de `tox` et ce que ça fout dans notre projet ?

Si j'en crois le commentaire initial de la PR #2138 :

> Maintenant on a les commandes suivantes pour lancer les tests : 
> - `tox -e flake8` : tester la syntaxe pep8
> - `tox -e back` : test du back end sur sqlite (la commande prend en compte flake)
> - `tox -e back_mysql` : test du back end sur mysql (pour travis)
> - `tox -e front` : tests du front
> - `tox -e docs` : tester la génération de la docs

Première question : comment se fait-il que ces commandes ne soient pas documentées ?

Aujourd'hui, sur une branche `dev` à jour :
- `tox -e flake8` ne fonctionne pas
- `tox -e back` est inutilisable parce que s'amuse à réinstaller toutes les dépendances. Cool. J'ai **déjà** toutes les dépendances. Pourquoi ça les réinstalle ?
- `tox -e back_mysql` est inutilisable parce que s'amuse à réinstaller toutes les dépendances. Cool. J'ai **déjà** toutes les dépendances. Pourquoi ça les réinstalle ?
- `tox -e front` ne fonctionne pas
- `tox -e docs` ne fonctionne pas

A noter que cet outil est tellement bien foutu qu'après avoir explosé et indiqué en rouge des tonnes d'erreurs, il affiche quand même que tout s'est bien passé en vert.
# Pile d'erreurs avec `tox -e flake8`

```
(zds-env)spacefox@Azathoth:~/PycharmProjects/zds-site$ tox -e flake8
flake8 runtests: PYTHONHASHSEED='1171347419'
flake8 runtests: commands[0] | flake8
WARNING:test command found but not installed in testenv
  cmd: /home/spacefox/virtualenvs/zds-env/bin/flake8
  env: /home/spacefox/PycharmProjects/zds-site/.tox/flake8
Maybe forgot to specify a dependency?
___________________________________ summary ____________________________________
  flake8: commands succeeded
  congratulations :)
```
# Pile d'erreurs avec `tox -e front`

```
(zds-env)spacefox@Azathoth:~/PycharmProjects/zds-site$ tox -e front
front runtests: PYTHONHASHSEED='1737368232'
front runtests: commands[0] | npm install npm -g
WARNING:test command found but not installed in testenv
  cmd: /usr/bin/npm
  env: /home/spacefox/PycharmProjects/zds-site/.tox/front
Maybe forgot to specify a dependency?
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "node" "/usr/bin/npm" "install" "npm" "-g"
npm ERR! node v0.10.36
npm ERR! npm  v2.4.1
npm ERR! path /usr/bin/npm
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, unlink '/usr/bin/npm'
npm ERR!  { [Error: EACCES, unlink '/usr/bin/npm'] errno: 3, code: 'EACCES', path: '/usr/bin/npm' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/usr/bin/npm'
npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/bin/npm'] errno: 3, code: 'EACCES', path: '/usr/bin/npm' }

npm ERR! Please include the following file with any support request:
npm ERR!     /home/spacefox/PycharmProjects/zds-site/npm-debug.log
ERROR: InvocationError: '/usr/bin/npm install npm -g'
front runtests: commands[1] | npm install
WARNING:test command found but not installed in testenv
  cmd: /usr/bin/npm
  env: /home/spacefox/PycharmProjects/zds-site/.tox/front
Maybe forgot to specify a dependency?
front runtests: commands[2] | npm run travis
WARNING:test command found but not installed in testenv
  cmd: /usr/bin/npm
  env: /home/spacefox/PycharmProjects/zds-site/.tox/front
Maybe forgot to specify a dependency?

> zds-site@0.2.0 travis /home/spacefox/PycharmProjects/zds-site
> gulp travis

[22:47:51] Using gulpfile ~/PycharmProjects/zds-site/Gulpfile.js
[22:47:51] Starting 'jshint'...
[22:47:52] Starting 'sprite'...
[22:47:52] Starting 'vendors-js'...
[22:47:52] Starting 'vendors-css'...
[22:47:52] Starting 'scripts'...
[22:47:52] Finished 'vendors-css' after 263 ms
[22:47:52] Finished 'vendors-js' after 296 ms
[22:47:52] Starting 'vendors'...
[22:47:52] 'Scripts (vendors)' all files 247.39 kB
[22:47:53] 'Scripts (vendors, minified)' all files 247.39 kB
[22:47:53] Finished 'vendors' after 1.16 s
[22:47:53] 'Scripts' all files 88.99 kB
[22:47:53] Finished 'jshint' after 1.89 s
[22:47:53] Starting 'test'...
[22:47:53] Finished 'test' after 4.41 μs
[22:47:54] 'Scripts (minified)' all files 42.65 kB
[22:47:54] Finished 'scripts' after 1.98 s
[22:47:54] Starting 'merge-scripts'...
[22:47:54] 'Scripts (all)' all files 336.38 kB
[22:47:55] 'Scripts (all, minified)' all files 126.83 kB
[22:47:55] Finished 'merge-scripts' after 1.19 s
[22:47:55] Finished 'sprite' after 3.42 s
[22:47:55] Starting 'stylesheet'...
[22:47:56] 'Stylesheet' all files 181.91 kB
[22:47:56] 'Stylesheet (minified)' all files 141.56 kB
[22:47:56] Finished 'stylesheet' after 1.02 s
[22:47:56] Starting 'images'...
[22:47:58] gulp-imagemin: Minified 41 images (saved 24.22 kB - 13.5%)
[22:47:58] 'Images' all files 155.84 kB
[22:47:58] Finished 'images' after 1.54 s
[22:47:58] Starting 'build'...
[22:47:58] Finished 'build' after 14 μs
[22:47:58] Starting 'travis'...
[22:47:58] Finished 'travis' after 14 μs
___________________________________ summary ____________________________________
ERROR:   front: commands failed
```
# Pile d'erreurs avec `tox -e docs`

```
(zds-env)spacefox@Azathoth:~/PycharmProjects/zds-site$ tox -e docs
docs runtests: PYTHONHASHSEED='3682303987'
docs runtests: commands[0] | make
WARNING:test command found but not installed in testenv
  cmd: /usr/bin/make
  env: /home/spacefox/PycharmProjects/zds-site/.tox/docs
Maybe forgot to specify a dependency?
Please use `make <target>' where <target> is one of
  html       to make standalone HTML files
  dirhtml    to make HTML files named index.html in directories
  singlehtml to make a single large HTML file
  pickle     to make pickle files
  json       to make JSON files
  htmlhelp   to make HTML files and a HTML help project
  qthelp     to make HTML files and a qthelp project
  devhelp    to make HTML files and a Devhelp project
  epub       to make an epub
  latex      to make LaTeX files, you can set PAPER=a4 or PAPER=letter
  latexpdf   to make LaTeX files and run them through pdflatex
  latexpdfja to make LaTeX files and run them through platex/dvipdfmx
  text       to make text files
  man        to make manual pages
  texinfo    to make Texinfo files
  info       to make Texinfo files and run them through makeinfo
  gettext    to make PO message catalogs
  changes    to make an overview of all changed/added/deprecated items
  xml        to make Docutils-native XML files
  pseudoxml  to make pseudoxml-XML files for display purposes
  linkcheck  to check all external links for integrity
  doctest    to run all doctests embedded in the documentation (if enabled)
___________________________________ summary ____________________________________
  docs: commands succeeded
  congratulations :)
```

Pour une fois que je décide de faire confiance quant à l'utilité d'un outil, j'obtiens un truc qui pète et qui n'est pas correctement documenté. Et après on me reproche de vouloir tout comprendre et tout contrôler ce qui rentre ou non dans ce projet...

Qu'est-ce qu'il faut que je fasse ? Que je ralentisse le projet en interdisant strictement toute PR qui n'apporte pas un outil qui est à la fois fiable, utile et qui vient avec sa documentation correcte pour notre projet ?

**Comment by SpaceFox** [comment]
PS : en quoi c'est problématique ? Aujourd'hui Travis ne passe plus à cause de bugs incompréhensibles, cf https://github.com/zestedesavoir/zds-site/issues/2241, et ni @gustavi ni moi ne pouvons reproduire le problème en local... Autrement dit, ça bloque tous les merge.

**Comment by SpaceFox** [comment]
Allez, et encore une... je me retrouve avec des comportements différents en local et sur Travis.

En local, sur [ce commit](https://github.com/zestedesavoir/zds-site/commit/4b5b7dbb0a9d898c372b7fb378612913e74789c0), les tests passent.

Sur Travis, j'ai une erreur que je ne pige pas : https://travis-ci.org/zestedesavoir/zds-site/jobs/49908422

Je fais quoi ? Je dois absolument passer 1/2h et bouffer quelques centaines de Mo d'espace disque à chaque fois que je veux faire un commit parce que je dois lancer la version "tox" des tests, celle qui me réinstalle l'univers ?

**Comment by firm1** [comment]
> Première question : comment se fait-il que ces commandes ne soient pas documentées ?

Visiblement [le dernier merge sur la doc](https://github.com/zestedesavoir/zds-site/pull/2187) a écrasé la documentation que j'avais rajouté à ce sujet. J'imagine que si ça a été QA/mergé, c'est que ça convenait.

Pour le reste des erreurs, ça ressemble pas mal à un problème entre l'écran et le clavier :) . Il faudrait investiguer plus.

**Comment by SpaceFox** [comment]
Oui, la doc a rétabli les anciennes pratique pour le lancement de tests back... justement à cause de ce que j'indique ici ! [Parce que tox est inutilisable pour tester le back, vu que ça réinstalle tout](https://github.com/zestedesavoir/zds-site/pull/2187/files#r23900977).

D'autre part, pas de bol, je viens de vérifier : les seules commandes écrasées, c'est celles de lancement des tests back. Toutes les autres sont laissées telles quelles. En particulier, toute la procédure d'installation et la manière de lancer les tests flake8. Qui ne fonctionnent pas en l'état.

Le problème particulier du #2241 venait visiblement d'une MAJ de flake8, il est désormais hors scope.

**Comment by SpaceFox** [comment]
Si demain soir je n'ai pas d'explication claire ici, tox saute.

**Comment by firm1** [comment]
Reprenons un peu ici les problèmes rencontrés. Si j'ai bien compris la pile de messages : 
- **les commandes tox ne sont pas documentées** : elles ont pourtant été écrasées dans le contributing et le readme, donc j'ai du mal à voir ou est-ce qu'elles pourraient apparaitre.
- **les tests flake8 ne fonctionnaient pas** : à priori le problème était du à une mise à jour de flake8 et non à cause de tox lui même. Donc ce n'est plus un problème
- **les tests back qui réinstallent les dépendances** : c'est normal, car tox a la capacité de gérer plusieurs environnements (python26, python27, python3x, etc.). Il se crée donc ses propres environnements virtuels à l'intérieur de ton projet pour démarrer les tests, afin de s'assurer que l'environnement de test est crée automatiquement et pas par l'utilisateur. Ceci dit, il ne rétéléchage les dependances que la première fois , donc ça reste utilisable en local, même si son intéret principal est sur travis.
- **les tests du front ne marchent** ? Je crois que le problème ne concerne pas tox ici non plus. VIsiblement tu as mal installé npm chez toi et il te demande les accès administrateur. Tox ou pas, m'est avis que ça ne marche pas non plus.
- **les test de doc ne marchent pas non plus** ? le message d'erreur le mentionne pourtant. Il manque la cible de génération de doc. Par exemple `tox -e docs html` pour générer la doc hml, ou `tox -e docs pdf` pour la doc en pdf

Le principal intérêt de tox ici est de paralleliser les traitements au niveau du serveur d'intégration (travis). Notons que le temps passé sur Travis est passé de plus de 30 min à moins de 15 min. Ce qui n'est pas négligeable et les problème mentionné par cette issue sont clairement indépendant de l'outil tox. Y'a t-il une vrai raison pour le faire sauter ?

Sinon, je m'interroge sur le caractère bloquant de cette issue.

**Comment by SpaceFox** [comment]
- **les commandes tox ne sont pas documentées** : Comme dit plus haut, les 3 morceaux de docs que tu avait mis ont été écrasés parce qu'inutilisables. Si ça concernait spécifiquement Travis, il fallait faire un bout de doc qui en parlait.
- **les tests flake8 ne fonctionnaient pas** : C'est un problème parce que Tox étant tellement merdique à utiliser (lentissme dans un contexte de dev, bouffe une place monstre) que ce test n'était pas lancé de la même manière en dev (sans tox) que sur travis (avec). Et donc le problème en devenait invisible tant qu'on arrivait pas sur travis. Un outil qui est tellement chiant à utiliser que les gens passent par autre chose et donc tombent sur des problèmes qui ne sont pas reproductibles en local sans y passer des plombes, si, c'est un problème.
- **les tests back qui réinstallent les dépendances** : c'est un problème parce que du coup toute tentative de test en dev met 10 ans. Même sans retélécharger les dépendances, c'est lent. C'est tellement peu utilisable [que les devs ont préféré le dégager le la doc que l'utiliser](https://github.com/zestedesavoir/zds-site/pull/2187/files#r23900977). Du coup, on a des incohérences entre ce qui est testé en local et ce qui est testé sur notre intégraiton.
- **les tests du front ne marchent** : mon installation du front fonctionne parfaitement, puisqu'elle me génère le front nickel, à la première installation et aux updates. De plus, il me semblait que l'intérêt de tox était justement de réinstaller l'univers... là tu dis que le problème, c'est que mon installation que j'ai faite à la main n'est pas bonne. Non seulement l'outil est incapable de faire fonctionner une installation qui par ailleurs ne pose aucun problème ; mais en plus il est incohérent avec ce qu'il est sensé faire. [Et ne je suis pas le seul à avoir des problèmes](https://github.com/zestedesavoir/zds-site/pull/2138#issuecomment-72709440)
- **les test de doc ne marchent pas non plus** : Ah oui, je suis sensé deviner que la commande indiquée dans la PR est fausse. Ce qui donne une idée de la qualité de la PR et de sa QA d'ailleurs.

Donc, si je résume :

**Positif**
- On passe de 30 à 15 minutes sur les build Travis
- ... et c'est tout !

**Négatif**
- Lenteur en dev
- Lourdeur en dev
- Bugs avec les tests front
- Premiers points = pas utilisé en dev = problèmes qui apparaissent sur Travis mais pas en dev
- [Je ne suis pas le seul à râler](https://twitter.com/Situphen/status/568362254145609728), @Situphen  aussi.

Emmerder tout le monde pour gagner 15 minutes sur des build, franchement, on s'en cogne. Les très rares pull request qui sont mergées dans les 30 minutes le sont sans tenir compte de Travis, parce qu'il s'agit de coquilles.

Donc, il n'y a pas le moindre intérêt à garder cet outil, qui est plus toxique qu'autre chose.

PS : on a pas les ressources sur ce projet pour s'emmerder avec des outils foireux en dev. De plus, rien ne presse dans l'intégration. Donc, cet outil, dans la mesure où il n'est pas neutre pour les dev, n'a rien à faire dans le projet.

**Comment by firm1** [comment]
> C'est un problème parce que Tox étant tellement merdique à utiliser (lentissme dans un contexte de dev, bouffe une place monstre) que ce test n'était pas lancé de la même manière en dev (sans tox) que sur travis (avec). Et donc le problème en devenait invisible tant qu'on arrivait pas sur travis.

Encore une fois si le problème ici était que les dépendances en local des devs n'étaient pas à jour. Tox ou pas tox, travis aurait gueulé de la même façon. Idem pour les incohérences local vs travis. Si le dev n'est pas a jour dans ses dépendances, il y'aura forcément un souci. Donc cet argument n'est pas valable.

> Ah oui, je suis sensé deviner que la commande indiquée dans la PR est fausse

Là il faut une mise à jour à faire sur la documentation.

> **Négatif**
> - Lenteur en dev
> - Lourdeur en dev
> - Bugs avec les tests front : **indépendant de tox**
> - Premiers points = pas utilisé en dev = problèmes qui apparaissent sur Travis mais pas en dev : **j'ai expliqué pourquoi le premier point n'est pas lié à tox**
> - Je ne suis pas le seul à râler, @Situphen aussi. : **je crois qu'il y'en a aussi qui ralent sur le temps des builds**

Désolé, mais je pense vraiment que tu grossi volontairement le trait, avec une pincée de mauvaise foi. Donc si tu veux faire sauter tox, fais le, mais je n'ai pas envie de perdre du temps à argumenter pour rien.

**Comment by SpaceFox** [comment]
> Tox ou pas tox, travis aurait gueulé de la même façon.

Alors on a un problème de gestion des tests. J'ai pas le temps d'aller vérifier dans les tickets, mais il me semble bien avoir lu des choses comme "j'ai bien MAJ mes dépendances locales et je ne reproduit pas".

> Là il faut une mise à jour à faire sur la documentation.

Non, ça n'a rien à voir avec la doc. Le problème ici, c'est que tu as fait une PR avec des instructions qui ne peuvent pas passer, et que la QA n'a pas été faite parce que personne n'a remarqué que ces instructions étaient foireuses.

> Bugs avec les tests front : indépendant de tox

J'ai déjà expliqué pourquoi si, il y a un problème d'interaction entre les tests front, tox, et l'installation front. Tu ne peux pas simplement prétendre le contraire.
Si npm doit être installé d'une manière spécifique pour que tox le prenne en compte, cette spécificité doit être expliquée !

> je crois qu'il y'en a aussi qui ralent sur le temps des builds

Mis à part toi, je ne me rappelle pas avoir vu râler sur les temps de build. Et encore, c'est juste un détail, parce que la question est là : qu'est-ce que ça apporte, _concrètement_, d'avoir un build plus rapide ? Rien. Ça ne permet pas de merger plus vite. Ça ne permet pas une meilleure réactivité dans le développement. Parce que ce n'est pas du tout un point bloquant.

Le seul cas d'utilisation que je vois, c'est réagir plus vite à une erreur qui arrive dans un build travis. Or :
1. On a pas de contraintes de temps de réaction
2. Si tu découvres un problème dans un build travis c'est :
   - Soit que travis chie dans la colle (ça arrive pas mal en ce moment), et c'est un problème indépendant de la PR, qui n'empêche pas qu'on la merge, et qui nécessite une correction séparée (on en a pas mal en ce moment)
   - Soit que tu n'as pas (ou mal) lancé les tests en local, et là il n'y a pas d'excuse, si tu perds du temps à cause de ça c'est de ta faute

Je rappelle, une fois de plus, que le but - et le **seul** but - des outils non indispensables au fonctionnement de l'application, c'est de **simplifier** la vie des développeurs. C'est d'autant plus vrai qu'on a un projet bénévole où chacun fait ça sur son temps libre et selon son envie, il est donc primordial de simplifier au maximum la vie des développeurs et d'éviter de leur faire perdre du temps avec des machins inutiles.

Ici, si on fait la balance bénéfice-problèmes de tox en ne conservant _que_ les points hors de toute discussion, on a quoi ? Ceci :
- \+ gain de 15 minutes sur les builds Travis
- \- lourdeur forte à la première utilisation (téléchargement + installation)
- \- lourdeur à chaque utilisation (installation)
- \- spécificités à l'installation d'outils déjà compliqués à installer (je ne compte même plus les gens qui sont venus sur IRC pour trouver de l'aide pour faire fonctionner le front)

Donc, je ne vois pas l'intérêt de cet outil pour notre projet. Pour un projet d'entreprise, OK. Mais ce ne sont pas nos contraintes. A moins que je n'ai oublié des points dans ma liste, cet outil apporte plus de contraintes que de bénéfices à Zeste de Savoir et donc doit sauter.

**Comment by firm1** [comment]
> Alors on a un problème de gestion des tests. J'ai pas le temps d'aller vérifier dans les tickets, mais il me semble bien avoir lu des choses comme "j'ai bien MAJ mes dépendances locales et je ne reproduit pas".

tox ne fais pas de magie, [il se contente d'executer les commandes que tout le monde connait](https://github.com/zestedesavoir/zds-site/blob/dev/tox.ini). La seule chose qu'il t'assure c'est que les tests seront lancés dans un environnement semblable à celui qu'on à décrit (dans les dépendances).

> Non, ça n'a rien à voir avec la doc. Le problème ici, c'est que tu as fait une PR avec des instructions qui ne peuvent pas passer, et que la QA n'a pas été faite parce que personne n'a remarqué que ces instructions étaient foireuses.

En effet les instructions de QA n'étaient pas précises. Mais dans la PR, [la commande en elle même est commentée](https://github.com/zestedesavoir/zds-site/pull/2138/files#diff-b91f3d5bd63fcd17221b267e851608e8R31) avec `to call this use`tox -e docs -- html``. Mais bon, là n'est pas le propos.

> Mis à part toi, je ne me rappelle pas avoir vu râler sur les temps de build.

un autre exemple qui me vient en tête là comme ça [ici](http://zestedesavoir.com/forums/sujet/1494/augmenter-la-vitesse-de-travis-pour-les-pr-back/)

> Je rappelle, une fois de plus, que le but - et le seul but - des outils non indispensables au fonctionnement de l'application, c'est de simplifier la vie des développeurs

On parle ici d'une dépendance pip qui n'est pas obligatoire en dev et améliore la qualité de la PR en amont. En lançant la commande tox on est plus proche de l'environnement cible. Les outils sont la aussi pour améliorer la qualité sinon on mettre flake8 aussi à la porte.

> Ici, si on fait la balance bénéfice-problèmes de tox en ne conservant que les points hors de toute discussion, on a [...]

Là visiblement il y'a un mélange de problèmes qui n'ont rien a voir. Les causes des problèmes sont ailleurs (flake8 -> maj de dependances; front -> droit d'admin, etc.). Mais bon, puisque ton avis me semble déjà tranché, ça ne sert à rien que je perdre du temps à discutter.

**Comment by SpaceFox** [comment]
Pour en finir ici, j'aimerais vraiment beaucoup une PR qui indique dans la doc clairement c'est quoi tox, à quoi ça sert et comment on s'en sert...

**Comment by SpaceFox** [comment]
Non mais franchement... Pourquoi la batterie de test qui est sensée utiliser SQLite exige une dépendance à MySQL ?

"Documentation" :

> `tox -e back`  : test du back end sur sqlite (la commande prend en compte flake)

Réalité :

```
(zds-env)spacefox@Azathoth:~/PycharmProjects/zds-site$ tox -e back
back runtests: PYTHONHASHSEED='139251052'
back runtests: commands[0] | coverage run --source=. /home/spacefox/PycharmProjects/zds-site/manage.py test
Traceback (most recent call last):
  File "/home/spacefox/PycharmProjects/zds-site/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/spacefox/PycharmProjects/zds-site/.tox/back/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/spacefox/PycharmProjects/zds-site/.tox/back/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/spacefox/PycharmProjects/zds-site/.tox/back/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/spacefox/PycharmProjects/zds-site/.tox/back/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/spacefox/PycharmProjects/zds-site/.tox/back/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/spacefox/PycharmProjects/zds-site/.tox/back/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 40, in <module>
    class Permission(models.Model):
  File "/home/spacefox/PycharmProjects/zds-site/.tox/back/local/lib/python2.7/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, **kwargs))
  File "/home/spacefox/PycharmProjects/zds-site/.tox/back/local/lib/python2.7/site-packages/django/db/models/base.py", line 297, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/spacefox/PycharmProjects/zds-site/.tox/back/local/lib/python2.7/site-packages/django/db/models/options.py", line 166, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/spacefox/PycharmProjects/zds-site/.tox/back/local/lib/python2.7/site-packages/django/db/__init__.py", line 40, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/spacefox/PycharmProjects/zds-site/.tox/back/local/lib/python2.7/site-packages/django/db/utils.py", line 242, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/spacefox/PycharmProjects/zds-site/.tox/back/local/lib/python2.7/site-packages/django/db/utils.py", line 108, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/spacefox/PycharmProjects/zds-site/.tox/back/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 18, in <module>
    raise ImproperlyConfigured("Error loading MySQLdb module: %s" % e)
ImproperlyConfigured: Error loading MySQLdb module: No module named MySQLdb
ERROR: InvocationError: '/home/spacefox/PycharmProjects/zds-site/.tox/back/bin/coverage run --source=. /home/spacefox/PycharmProjects/zds-site/manage.py test'
```

PS : J'ajoute que c'est normal, puisque quand on demande un test sous MySQL, on demande bien l'installation de la dépendance MySQL :

```
(zds-env)spacefox@Azathoth:~/PycharmProjects/zds-site$ tox -e back_mysql
back_mysql create: /home/spacefox/PycharmProjects/zds-site/.tox/back_mysql
back_mysql installdeps: -r/home/spacefox/PycharmProjects/zds-site/requirements.txt, -r/home/spacefox/PycharmProjects/zds-site/requirements-dev.txt, MySQL-python, ujson
```

@firm1 on a une chance d'avoir une vraie conf de Tox qui fonctionne et une vraie doc sur la manière de l'utiliser, ou bien tu as officiellement abandonné la maintenance de cette fonctionnalité au sein de ZdS ?

**Comment by SpaceFox** [comment]
En fait, c'est la doc de `tox -e back` : il ne lance **pas** le test sur SQLite mais **sur la base spécifiée dans les settings**. Ce qui est très différent : si comme moi vous avez MySQL dans les settings... ça va planter. Parce que du coup il manquera la dépendance...

**Comment by SpaceFox** [comment]
@firm1 j'attends toujours une vraie doc ici... ne me dis pas que tu n'as pas le temps, tu as déjà ouvert au moins 4 PR depuis !

**Comment by firm1** [comment]
Dans ma todolist. Ça arrive.

**Comment by SpaceFox** [comment]
Une semaine après, on en est où ?

**Comment by firm1** [comment]
La PR ne devrait plus tarder, c'est dans le pipe. Il faut compter 2-3 jours.

**Comment by SpaceFox** [comment]
>  Il faut compter 2-3 jours.

Ça fait 4 jours et tu fais encore des PR sur des détails qui n'ont rien à voir. Ça va vraiment commencer à m'énerver, tu sais ?

**Comment by firm1** [comment]
Sorry, pas eu le temps de finaliser ça (ce n'est faisable uniquement chez moi)

**Comment by SpaceFox** [comment]
Du coup, quelle est la nouvelle deadline ?

**Comment by firm1** [comment]
J'essaye pour cette nuit et dans le pire des cas la nuit du mardi.

**Comment by Eskimon** [comment]
Doc mergee. A completer en cas de souci.
