### ISSUE TITLE
Test qui ne passe pas en local

### ISSUE THREAD

**Issue by poulp** [zestedesavoir/zds-site#2254]
```
======================================================================
FAIL: test_unregister (zds.member.tests.tests_views.MemberTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/programmation/github/zdsenv/zds-site/zds/member/tests/tests_views.py", line 286, in test_unregister
    self.assertFalse(os.path.exists(writingTutorialAloneGallerPath))
AssertionError: True is not false

----------------------------------------------------------------------
Ran 462 tests in 181.249s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

J'ai ce test qui ne passe pas en local, quelqu'un aurait rencontré le même problème ?

Pour infos je fait passer les tests avec sqlite.

**Comment by gustavi** [comment]
J'ai corrigé ça normalement dans #2252, à confirmer.

**Comment by poulp** [comment]
Nop l'erreur persiste.

**Comment by gustavi** [comment]
Je n'ai pas cette erreur. Tu peux essayer avec un env propre ?

**Comment by Situphen** [comment]
L'erreur persiste comme @poulp chez moi !

**Comment by poulp** [comment]
Je viens d'essayer avec un environnement propre et toujours la même erreur.

**Comment by Eskimon** [comment]
Ca bug toujours ? (il me semble que non...) Si oui, quelle plateforme ?

**Comment by Situphen** [comment]
L'erreur persiste :

```
======================================================================
FAIL: test_unregister (zds.member.tests.tests_views.MemberTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/situphen/Documents/Dev/Python/zdsenv/zds-site/zds/member/tests/tests_views.py", line 352, in test_unregister
    self.assertFalse(os.path.exists(writing_tutorial_alone_galler_path))
AssertionError: True is not false
```

C'est apparemment dû à https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/tests/tests_views.py#L352 et corrigé par #2538 d'après @firm1 (je ne peux pas vérifier actuellement) !

Je tourne sur Kubuntu 14.04.

Je vais retester avec une base de données propre !

**Comment by Eskimon** [comment]
Chez moi ca marche (requirements à jour étou)

**Comment by Eskimon** [comment]
Bon chez moi ca marche sur un environnement à jour et chez @GerardPaligot avec deux environnements différents ca marche aussi... Donc je ferme.

**Comment by GerardPaligot** [comment]
Sur OS X Mavericks et Yosemite, tous les tests passent.

**Comment by Situphen** [comment]
Je retesterai la semaine prochaine pour bien vérifier.

**EDIT :** Je n'ai plus l'erreur.
