### ISSUE TITLE
Problème d'alignement avec le markdown

### ISSUE THREAD

**Issue by ghost** [zestedesavoir/zds-site#2256]
Bonjour,

Il y a un problème d'alignement, lorsque deux centrages sont séparés par un alignement à droite. 

```
-> center <-

-> right ->

left

-> center <-
```

On obtient ceci :

> <div align=center>

center

right ->

left

-> center
</div>

**Comment by Axylium** [comment]
Cette issue aurait plus sa place au sein de: [zestedesavoir/Python-ZMarkdown](https://github.com/zestedesavoir/Python-ZMarkdown)

**Comment by ghost** [comment]
Je ne connaissais pas merci
