### ISSUE TITLE
Image PHP avec boucle infinie

### ISSUE THREAD

**Issue by Chaoxys** [zestedesavoir/zds-site#2260]
Salut,

Comme demandé, je fais un ticket ici.

Lorsqu'on inclut une image sous le format http://monsite.com/image.php (dans une réponse sur le forum par exemple) ou le script fait une boucle infinie, cela génère des appels venant du site d'où est appelée l'image en continu quand on charge le sujet sur ZdS. Un peu embêtant pour le lecteur. Je n'ai pas laissé l'exemple sur le site pour n'embêter personne, mais si nécessaire, je remettrai.

**Comment by ghost** [comment]
Je ne pense pas qu'on puisse faire quelques choses, c'est le navigateur qui est fautif.

**Comment by gustavi** [comment]
Je ferme ici car ce n'est pas une vraie issue.
