### ISSUE TITLE
Actualiser le site fait disparaitre le message d'avertissement de la CNIL

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2266]
Si je vais pour la première fois sur le site, j'ai bien une barre qui me dit `Ce site utilise Google Analytics. En poursuivant votre navigation sur ce site, vous nous autorisez à déposer des cookies à des fins de mesure d'audience. Pour s'opposer à ce dépôt vous pouvez cliquer ici`.

Cependant, si je fais un _refresh_ de la page, le message disparait.

Sauf que je n'ai ni accepté, ni refusé d'être pisté. Je ne sais donc pas ce qui se passe.

**Comment by SpaceFox** [comment]
C'est le comportement voulu, il me semble documenté par la CNIL : si tu ne fais rien et que tu continues à naviguer, on considère que tu acceptes. Rafraîchir la page, c'est un comportement qui est assimilé pour des raisons techniques à "continuer à naviguer".

Après, c'est vrai que c'est pas ultra clair pour le visiteur... ça mériterait d'être amélioré, mais je ne pense pas que ce soit une priorité.

**Comment by A-312** [comment]
Je prends, je corrigerai ça demain.

**Comment by ghost** [comment]
Vu que cliquer sur le bouton "Ok" n'est pas demandé par la CNIL, je trouve que le code actuel fonctionne très bien.

**Comment by Situphen** [comment]
Du coup on fait quoi si l'utilisateur ne clique pas ? On considère qu'il accepte ou on continue d'affiche le bandeau ?

**Comment by ghost** [comment]
Pourquoi utiliser COOKIE EU ? Alors que le code interne fonctionne très bien ?

**Comment by Situphen** [comment]
@A-312 : Pour fixer #2058 sans avoir besoin de redévelopper quelque chose qui existe déjà, qui est propre, qui fonctionne bien et qui sera maintenu

**Comment by ghost** [comment]
Suffit de faire une meta et de l'ajouter dans le code ?

**Comment by Situphen** [comment]
@A-312 : Cookies EU Banner supporte Do Not Track et corrige quelques erreurs qu'il y a actuellement dans le code. https://zestedesavoir.com/forums/sujet/2301/amelioration-de-la-gestion-des-cookies/#p41133

**Comment by ghost** [comment]
`window.navigator.doNotTrack`

Ce n'est pas très dure... Des erreurs ? J'ai vérifié le fonctionnement de la bannière, et je ne vois pas le soucis.

**Comment by Situphen** [comment]
Je laisse @SpaceFox trancher sur l'intégration ou non de Cookies EU Banner.

**Comment by ghost** [comment]
Je suis le seul à être choqué d'utiliser une dépendance externe, alors que le code actuel fonctionne très bien, et necessite qu'un minuscule changement ?

Si les modifications des précédents particiapants n'ont pas de valeur...

**Comment by Eskimon** [comment]
Perso le fonctionnement actuel me va aussi (modulo  qu'on variabilise le code GA). On est dans les clous légalement, autant pas s’embêter.
D'autant plus que 0 utilisateur n'a émis de plainte à ce sujet.

**Comment by Situphen** [comment]
> Je suis le seul à être choqué d'utiliser une dépendance externe

Tu n'es pas le seul, il y en a d'autres dans [ce sujet](https://zestedesavoir.com/forums/sujet/2301/amelioration-de-la-gestion-des-cookies).

> le code actuel fonctionne très bien

Il fonctionne mais ne respecte pas toutes les règles de la CNIL.

> necessite qu'un minuscule changement ?

Pour moi les changements à faire ne sont pas si petits que ça.

> Si les modifications des précédents particiapants n'ont pas de valeur...

Elles ont de la valeur ! Les modifications du code font partie de la vie de l'open-source. Et puis, là c'est Alex-D qui a tout codé donc vu que c'est lui qui a proposé l'utilisation de son package, je pense qu'il est d'accord pour qu'on enlève son ancien fichier. Et puis, il y a toujours un historique vu que c'est versionné !

**Comment by Eskimon** [comment]
> Il fonctionne mais ne respecte pas toutes les règles de la CNIL.

Quelles règles ne le sont pas ? Parce que dans mes souvenirs la CNIL c'est simple : "Si l'utilisateur ne clic pas alors il accepte".

**Comment by Situphen** [comment]
Source : https://zestedesavoir.com/forums/sujet/2301/amelioration-de-la-gestion-des-cookies/#p41133

> Le code actuel ne prend pas en compte DoNotTrack.
> 
> Si on se rend sur la page "En savoir plus" les cookies sont acceptés, or si on clic sur le lien du bandeau pour aller vers cette page, le choix ne devrait pas encore être fait. Le bandeau devrait être encore visible. Ce que fait la classe que j'ai réalisé.

**Comment by Eskimon** [comment]
> Si on se rend sur la page "En savoir plus" les cookies sont acceptés, or si on clic sur le lien du bandeau pour aller vers cette page, le choix ne devrait pas encore être fait. Le bandeau devrait être encore visible. Ce que fait la classe que j'ai réalisé.

Perso ca ca me va comme argument :)

**Comment by SpaceFox** [comment]
La "prise en compte" du DoNotTrack [n'est qu'une recommendation](http://www.cnil.fr/documentation/deliberations/deliberation/delib/300/) et non une obligation légale.

Le comportement de la page "En savoir plus" était assez curieusement celui du code source fourni par la CNIL à l'époque où on a implémenté ce truc. Par contre, la version actuelle a l'air plus au point. Peut-être que le plus simple est de reprendre [le code de la CNIL](http://www.cnil.fr/vos-obligations/sites-web-cookies-et-autres-traceurs/outils-et-codes-sources/la-mesure-daudience/) qui nous permet, de manière très logique, de respecter à 100% ses recommandations sans dépendances externes ni réflexion de notre part ?

Pour moi, [le vrai problème se situe ici](https://github.com/Situphen/zds-site/commit/e6a2ca1eee8f5d52ac263a3bcdf475ec1c36cf55#commitcomment-9722179).

**Comment by Situphen** [comment]
Du coup on fait quoi si l'utilisateur ne clique pas ? On considère qu'il accepte ou on continue d'affiche le bandeau ?

**Comment by ghost** [comment]
Il y a un passage sur le site de la CNIL qui dit que continuer de naviguer est assimiler à un consentment.

**Comment by Alex-D** [comment]
Au passage :

> On considère qu'il accepte ou on continue d'affiche le bandeau ?

C'est juste [un booléen en deuxième paramètre](https://github.com/Alex-D/Cookies-EU-banner#waitaccept) ça.

**Comment by SpaceFox** [comment]
Je confirme qu'on ne se fait pas chier et qu'on assimile ça à un consentement.

**Comment by Situphen** [comment]
OK

**Comment by Situphen** [comment]
Du coup on fait quoi ? On intègre Cookies EU banner ou on code une solution maison ?

**Comment by GerardPaligot** [comment]
Merci à @Situphen de s'en être occupé. Merci à @pierre-24 pour la QA.
