### ISSUE TITLE
Erreur 500 lors de la recherche d'un sujet

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2268]
Url incriminée : `http://beta.zestedesavoir.com/forums/sujets/recherche/`

On ne devrait jamais avoir d'erreur 500

**Comment by A-312** [comment]
Tu as oublié le paramètre : 

http://beta.zestedesavoir.com/forums/sujets/recherche/?q=sujet

**Comment by ghost** [comment]
La page plante car il manque les paramètres.

Je m'en occupe.

**Comment by gustavi** [comment]
@SpaceFox tu peux ajouter @A-312 au groupe des assignés ? Tout comme @Situphen

**Comment by SpaceFox** [comment]
Invitations envoyées (je pensais que c'était fait depuis longtemps pour @Situphen !)
