### ISSUE TITLE
Passer à Python 3

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#2272]
Ce passage semble nécessaire pour beaucoup de choses. Cette issue à pour but de lister les applications externes qui ne sont pas encore compatibles ainsi que les problèmes éventuels.

Aussi pour qu'on ne se marche pieds et qu'on ne soit pas 36 à bosser chacun dans son coin.

Les discussions se font sur le forum : https://zestedesavoir.com/forums/sujet/2257/migration-python-3

Une liste de ce qui pose encore problème et de ce qui va être changer.
## Infra
- [x] supervisor : d'après @SpaceFox on a [deux options](https://github.com/zestedesavoir/zds-site/issues/2272#issuecomment-73692100) 
- [x] Mysql-python : https://pypi.python.org/pypi/mysqlclient semble assez bien fonctionner et est recommandé par le projet Django
- [x] python-memcached : remplacé par https://pypi.python.org/pypi/python3-memcached/
## Back
- [x] Python-ZMarkdown : en cours
## Front
- [x] node-gyp : pas de changement, on spécifie juste à npm d'utiliser python2.

**Comment by SpaceFox** [comment]
Concernant le cas de supervisor :
- Soit on reste sur une version courante de Debian sur nos environnements, donc le plus simple c'est d'utiliser python3 pour le site et python2 pour supervisor. Sauf erreur de ma part, supervisor ne sert qu'à superviser et lancer des processus, qui peuvent être eux dans n'importe quel langage.
- Soit on mettra à jour vers une Debian 8, qui utilise systemd, donc supervisor deviendra inutile.

Je ne sais pas ce que vous en pensez mais de ce que j'en comprends, il n'y a pas de problème ici.

**Comment by gustavi** [comment]
Merci @SpaceFox de l'info. Je pense que migrer vers Debian 8 peut être une bonne chose sachant qu'en plus on va devoir refaire un venv.

**Comment by sandhose** [comment]
Comme dit sur le forum, pour node-gyp, suffit de dire à npm où se trouve python2 via `npm config set python /path/to/executable/python2.7` ; comme dit, c'est à faire qu'une seule fois, et que dans le cas où python2 n'est pas l'exécutable par défaut

**Comment by SpaceFox** [comment]
Pour info, le merge de cette PR passera ZdS (le code) en v2.0 :)

**Comment by firm1** [comment]
Bon, j'ai commencer à regarder un peu par ici, parce qu'il faut quand même vivre dans la modernité un jour. Et la combinaison gagnante est la suivante pour une migration vers python3 : 
- Python-Zmarkdown : est maintenant compatible python3
- Pour mysql, on a [mysql-python-connector](https://dev.mysql.com/downloads/connector/python/) qui passe avec brio les essais
- python3-memcached à la place de python-memcached
- django-munin : j'ai fait une PR de compatibilité pour python3 à l'upstream et maintenant que je fais partie de leur association, la release devrait être rapide.
- supervisor : pas besoin de le quitter. Etant donné que python2 et python3 peuvent cohabiter sur la même machine, il suffira de crée un virtualenv avec python3 pour le projet, et les autres services infra peuvent rester sur python2 par defaut.

---

Par contre, là ou ça va faire mal c'est que la PR va toucher tout le projet (j'ignore) les impacts sur la ZEP-12 mais a vu de nez, ils devraient être mineures.

La question est donc : la PR est à preparer pour quand ? la release 1.8 ou la release 1.9 ?

**Comment by SpaceFox** [comment]
> La question est donc : la PR est à preparer pour quand ? la release 1.8 ou la release 1.9 ?

Par définition (cf le message avant le tien) ce sera la v2.0 :)

Comme cette modification va imposer d'énormes changement d'infrastructure (probablement une réinstallation complète du serveur), je préfère ne pas la voir dans la release 1.8, laquelle va déjà être assez délicate comme ça.

**Comment by firm1** [comment]
Je pensais pareil, mais du coup il faudra éviter de rajouter une ZEP dans la 2.0.

**Comment by Situphen** [comment]
On comptait pas sortir la ZEP 04 pour la v2.0 ?

**Comment by SpaceFox** [comment]
Non. On comptait la sortir dès que possible.

**Comment by GerardPaligot** [comment]
Maintenant que nous avons notre nouveau serveur, nous en sommes où ici ?

**Comment by SpaceFox** [comment]
Le verrou Debian 8 a sauté, il faut vérifier le reste mais d'un point de vue infra pure, on peut passer à python 3.

**Comment by Situphen** [comment]
Faut rebaser la PR et vérifier pour le front et pour Travis !

**Comment by Eskimon** [comment]
En gros post-release ZEP-12 on peut faire une release technique juste pour faire passer le venv à python 3 ? Ca vous irait ? (On sait si toutes nos dépendances sont compatibles py3 ? ). Pour info la version py3 sur la prod est `Python 3.4.2`

**Comment by pierre-24** [comment]
Moi, j'approuve :)

**Comment by SpaceFox** [comment]
Je remonte ce sujet pour signaler que [les dernières versions de certaines de nos dépendances](http://cairosvg.org) commencent à **requérir** Python 3 pour fonctionner.

**Comment by motet-a** [comment]
Corrigé par #4673.
