### ISSUE TITLE
Les tags du tutoriel pour son sujet dans la Bêta-zone 

### ISSUE THREAD

**Issue by Vayel** [zestedesavoir/zds-site#2274]
Pour plus de clarté dans la bêta-zone,il serait bien d'ajouter automatiquement au sujet associé à un tutoriel les tags de ce dernier.

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
to be tested, il me semble avoir vu le bout de code qui le fait.

2015-04-16 14:59 GMT+02:00 Eskimon notifications@github.com:
