### ISSUE TITLE
Incohérence sur le nombre de messages d'un membre

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#2275]
Les 2 pages en questions : https://zestedesavoir.com/membres/voir/Iris13/ https://zestedesavoir.com/forums/messages/1927/.

On a 3 messages alors que aucun n'est affiché.

**Comment by SpaceFox** [comment]
Chez moi c'est cohérent. Je pense que c'est parce que les 3 messages en question sont modérés, et que donc tu ne peux pas les voir sans avoir les droits staff.

**Comment by gustavi** [comment]
Oui effectivement. Dans ce cas on doit changer le nombre de messages qu'un simple membre peut voir non ?

**Comment by SpaceFox** [comment]
Si ça ne nécessite pas des requêtes dans une boucle, oui :)

Au pire, il suffit de rajouter pour les non-staff un message du genre :
"des messages modérés peuvent ne pas apparaître dans cette liste" ou un
truc du genre.

Le 10 février 2015 16:15, Laville Augustin notifications@github.com a
écrit :
