### ISSUE TITLE
Possible de se sélectionner pendant l'autocomplétion

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2276]
Il s'agit d'une regression certainement due à la ZEP17. Mais avant, lorsqu'on faisant de l'autocomplétion pour rechercher un membre en créant un MP, le membre lui même n'était pas proposé dans la liste. Ce qui est normal puisqu'on ne peut pas s'écrire à soit même.

On a donc une regression à ce niveau.

**Comment by GerardPaligot** [comment]
Notons que ce n'est pas une régression importante puisque le back effectuera après la vérification.

**Comment by ghost** [comment]
Je m'en occupe.
