### ISSUE TITLE
Bug sidebar qui ne fait pas toute la hauteur

### ISSUE THREAD

**Issue by ghost** [zestedesavoir/zds-site#2277]
Bonjour,

Sur les navigateurs chromes (webkit), firefox, .... La sidebar ne fait pas toute la hauteur.

![Imgur](http://i.imgur.com/uHQayvz.png)

**Comment by SpaceFox** [comment]
C'est voulu non ?

**Comment by ghost** [comment]
Je ne pense pas, je laisse cette issue pour plus tard, il faudra surement utiliser la même méthode que la PR #2263.

**Comment by SpaceFox** [comment]
Vérifie avant de « corriger ». Un « bug » présent sous Chrome ET Firefox
que personne n'a déclaré n'est sans doute pas un bug…

**Comment by SpaceFox** [comment]
Peux-tu indiquer avec quelle version des navigateurs et du code tu reproduits ?

PS : OK, c'est sur la version en bêta. Essaie d'indiquer ça clairement dans l'issue, ça évitera d'y réfléchir :)

**Comment by GerardPaligot** [comment]
@sandhose Est-ce vraiment non voulu ?

**Comment by sandhose** [comment]
Je ne suis pas responsable du design initial, donc je ne pourrais pas répondre quant aux intentions initiales. Maintenant, si j'avais à réécrire le front, cette sidebar prendrait probablement toute la hauteur.

**Comment by pierre-24** [comment]
Semblerait que ça soit réglé ;)
