### ISSUE TITLE
Bug affichage message

### ISSUE THREAD

**Issue by jcval** [zestedesavoir/zds-site#2280]
Lorsque quelqu'un a posté pendant que l'on rédigeait, on a :

{% trans "Au moins un nouveau message a été posté dans la discussion pendant que vous rédigiez le votre" %}.

**Comment by Eskimon** [comment]
Ahah la cavalerie qui arrive trop tard :D

Déjà reporté : https://github.com/zestedesavoir/zds-site/issues/2176
et corrigé : https://github.com/zestedesavoir/zds-site/pull/2225

**Comment by SpaceFox** [comment]
Déjà corrigé dans la #2195, mais merci quand même :)

**Comment by SpaceFox** [comment]
Combo !

**Comment by Eskimon** [comment]
> Combo !

Que dalle ! Je t'ai grillé un point c'est tout !

**Comment by jcval** [comment]
Bon, faut vraiment que j'apprenne à rechercher des informations sur internet...

**Comment by Eskimon** [comment]
cette perche... https://zestedesavoir.com/tutoriels/205/la-recherche-dinformations-sur-internet/

**Comment by jcval** [comment]
Tiens, c'est moi qui ai co-rédigé ce truc ? ;)
