### ISSUE TITLE
Message non lu non notifié

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2284]
Actuellement en prod, lorsqu'on veut marquer un sujet comme non lu avec un message qui n'est pas le dernier du sujet, la notification n'est pas rajoutée dans mon centre de notifications.

C'est sans doute du "Back" mais c'est à vérifier.

**Comment by poulp** [comment]
De mon côté ça fonctionne, c'est un sujet en particulier ou sur n'importe lequel ?

**Comment by GerardPaligot** [comment]
Effectivement, précision : Quand on marque le premier message d'un sujet comme non lu, aucune notification.

**Comment by poulp** [comment]
Ah d'accord, mais il me semble que c'est voulu, si on marque le premier message d'un sujet non lu c'est tout le sujet qui est non lu, et un sujet non lu n’emmène pas de notifications. Enfin à voir avec ceux qui ont développé le module.

**Comment by SpaceFox** [comment]
Je pense que @poulp a la bonne explication.

Une solution serait alors, quand on clique sur le bouton "message non lu" d'un 1er message, de marque ce message en "non lu" **et** de marquer le sujet comme suivi. Ainsi, il apparaîtrait dans les notifications.

**Comment by GerardPaligot** [comment]
> Une solution serait alors, quand on clique sur le bouton "message non lu" d'un 1er message, de marque ce message en "non lu" et de marquer le sujet comme suivi. Ainsi, il apparaîtrait dans les notifications.

J'aime cette solution parce qu'en cliquant sur "Non lu", je m'attendais à avoir le sujet dans mes notifications (premier message ou non).

**Comment by GerardPaligot** [comment]
Ce n'est pas un bug puisque le comportement voulu mais une évolution (voir message https://github.com/zestedesavoir/zds-site/issues/2284#issuecomment-73881520)

**Comment by GerardPaligot** [comment]
Aujourd'hui, marquer un message comme non lu rajoute bien une notification (merci au récent refactoring).
