### ISSUE TITLE
URL pour lister les membres ou les MPs via l'API absente de la doc

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2286]
Url : http://beta.zestedesavoir.com/api/

On retrouve l'ensemble des urls de l'API sauf celle qui permet de lister tous les membres a savoir http://beta.zestedesavoir.com/membres/

**Comment by SpaceFox** [comment]
C'est un problème d'infra : l'URL est bien présente en dev mais pas sur la version déployée en bêta... si quelqu'un a la moindre idée de ce qui peut être la cause de ceci, je prends. Parce que personnellement je sèche.

(PS : pour une fois que _j'ajoute_ le tag "infra" ^^ )

**Comment by gustavi** [comment]
Aujourd'hui on a la même chose des deux côtés. SAUF qu'il en manque des deux côtés ...

**Comment by GerardPaligot** [comment]
@gustavi Tu peux être plus précis ?

**Comment by GerardPaligot** [comment]
@Un-Cornichon Je sais que tu voyais ça comme un petit défi ? Envie de te lancer sérieusement dedans ? :)

**Comment by vhf** [comment]
Donc comme ce ticket est absolument incompréhensible, voici une tentative de résumé du problème :
- https://zestedesavoir.com/api/ liste les endpoints de l'API
- https://zestedesavoir.com/api/membres/ est un endpoint valide et documenté dans le backend, mais est absent de la documentation pour une raison inconnue

Une piste serait de se plonger dans la magie de swagger pour comprendre pourquoi il n'extrait pas la doc de cet endpoint. Je ne suis pas sûr que le tag "infra" soit pertinent ici.

**Comment by GerardPaligot** [comment]
Le tag "infra" est présent parce que le bug n'est pas reproductible en local.

**Comment by rom1504** [comment]
Pour info ce sont ces deux lignes qui sont censées permettre la détection de cet endpoint:
- https://github.com/zestedesavoir/zds-site/blob/20d324eb32eeb45871d2638f2de06049b701a019/zds/urls.py#L99 : tout /api/membres/
- https://github.com/zestedesavoir/zds-site/blob/20d324eb32eeb45871d2638f2de06049b701a019/zds/member/api/urls.py#L9 : la liste des membres en particulier

voir aussi https://github.com/marcgibbons/django-rest-swagger#quick-start

**Comment by rom1504** [comment]
Il y a eu des modifs depuis la prod https://github.com/zestedesavoir/zds-site/blob/prod/zds/member/api/urls.py , notamment cette string vide (le fait d'utiliser la fonction pattern). Ça m'étonnerait pas que ce soit le problème (qui est du coup réglé sur la version dev)

**Comment by GerardPaligot** [comment]
Pour une raison que j'ignore, le souci est réglé sur la bêta avec la version v18.

**Comment by SpaceFox** [comment]
Ça a toujours marché en bêta, cf la première réponse.

**Comment by GerardPaligot** [comment]
Justement, le premier message concerne la bêta.

**Comment by SpaceFox** [comment]
Ah oui, pardon, dans mon souvenir c'étais cassé en prod mais pas en bêta…

**Comment by GerardPaligot** [comment]
Le nouveau serveur doit régler le souci puisque la documentation des listes des membres et des MPs s'affichent dorénavent.

**Comment by DevHugo** [comment]
Je [confirme](https://jsfiddle.net/fnqcssmr/5/) o/ (Testé avec firefox).
