### ISSUE TITLE
Problème de taille entre les boutons connexion et inscription sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2287]
Navigateur firefox.
Os : Android
Smartphone : One plus

![tmp_29984-screenshot_2015-02-11-18-39-02-1640495332](https://cloud.githubusercontent.com/assets/6066015/6152482/d5545e26-b21d-11e4-923c-c3edbd60b458.png)

**Comment by ghost** [comment]
Le problème se situe ici : https://github.com/zestedesavoir/zds-site/blob/3eedb9f9a855107bbde8f8a2fdd09473a8c19b41/assets/scss/components/_alert-box.scss#L90

Elle apparait suite à la réoganisation du CSS par shandhose (#2057). 
Avant c'était cette règle qui s'appliqué : https://github.com/zestedesavoir/zds-site/blob/3eedb9f9a855107bbde8f8a2fdd09473a8c19b41/assets/scss/base/_forms.scss#L117

**Comment by Fulbert** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/4991264/6157952/86469696-b1fa-11e4-986b-3f47830dd95f.png)

Problème presque similaire sur desktop.

**Comment by Situphen** [comment]
@SpaceFox : ça passe en betafix ou en simple fix ?

**Comment by SpaceFox** [comment]
On s'en fout, c'est un détail, c'est un simple fix.

**Comment by Eskimon** [comment]
Merci @firm1 et @pierre-24 :)
