### ISSUE TITLE
Cliquer sur la banniere de désactivation de Google analytics ne fait pas partir la zone bleu

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2288]
Navigateur : Chrome 39
Os : Android

Quand je clique sur "OK" (cf. Screen) rien ne se passe. Je suis obligé de rafraîchir pour que la zone bleue disparaisse.

![tmp_29984-screenshot_2015-02-11-19-03-46809985689](https://cloud.githubusercontent.com/assets/6066015/6152985/7caafe98-b221-11e4-9c77-c7a3665f3aef.png)

**Comment by Eskimon** [comment]
C'est toujours vrai ca ?

**Comment by Situphen** [comment]
UP !

> C'est toujours vrai ca ?

**Comment by Eskimon** [comment]
Je viens de tester à l'instant et tout semble OK.
