### ISSUE TITLE
Problème d'affichage de "suivant" dans l'aide aux auteurs sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2289]
Navigateur : Chrome 37
Os : Android

![screenshot_2015-02-11-19-16-11](https://cloud.githubusercontent.com/assets/6066015/6153125/afbfc858-b222-11e4-971f-76892e4a9035.png)

**Comment by ghost** [comment]
Pas sûr que ça soit facile, il faut trouver une solution qui fonctionne.

A partir d'une largeur de 360 c'est problèmatique : 360x640 et 320x480. Peut-être tronquer les mots.

![Imgur](http://i.imgur.com/WxnCy0G.png) ![Imgur](http://i.imgur.com/AHWoRPe.png)

**Comment by gustavi** [comment]
Je pense qu'on peux même supprimer les mots à parti d'un certain taille. J'avais également constaté ce problème sur mon ZTE Open C.

**Comment by Situphen** [comment]
Je plussoie @gustavi : le mieux est de tronquer les mots ; les flèches sont assez compréhensibles !

**Comment by SpaceFox** [comment]
Je plusseoie, pour moi les flèches se suffisent très bien à elles-mêmes.

**Comment by Eskimon** [comment]
Ok, merci @firm1 et @pierre-24
