### ISSUE TITLE
Problème d'alignement dans les filtres du besoin de l'aide aux auteurs

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2293]
url : http://beta.zestedesavoir.com/tutoriels/aides/

On voit bien dans la capture que "Annuler le filtre" est décalé par rapport aux autres

Navigateur : Firefox
OS : Windows

![besoin-aligned](https://cloud.githubusercontent.com/assets/6066015/6164964/3ee8297c-b2a4-11e4-8a6b-a0ab6dbeaf46.PNG)

**Comment by ghost** [comment]
C'est peut-être voulu ? (Le tag bug c'est un peu fort).

**Comment by Eskimon** [comment]
C'est un bug, mais on a pas vraiment de parade (a part jouer avec le CSS) car la methode d'affichage n'est pas la meme (l'un utilise un affichage via le CSS alors que l'autre c'est une "vrai" image qui est utilisee

**Comment by GerardPaligot** [comment]
J'avais notifié la chose lorsque c'était en développement et ça n'a pas changé depuis. Comment la QA a pu dire ok à ça ?

**Comment by Eskimon** [comment]
Parce que la QA avait déjà pas mal de chat a fouetter la dessus et on est passe a cote "parce que c'est franchement pas dramatique" ? Je suis d'accord qu'on aurait pu passer encore un peu de temps a peaufiner, mais a l’époque on avait 0 dev front pour nous filer un coup de main et des outils front qui n'en faisait qu'a leur tête, donc la ZEP serait encore reste en pause pour si peu.

**Comment by ghost** [comment]
![Imgur](http://i.imgur.com/rmwAswP.png)

Vous aimez comme ça ?

**Comment by Eskimon** [comment]
Nickel (sur mobile aussi ?)

**Comment by firm1** [comment]
J'aime

**Comment by ghost** [comment]
![capture d ecran 2015-02-12 a 15 51 08](https://cloud.githubusercontent.com/assets/10801383/6169608/00662570-b2cf-11e4-8e6a-04b3c9be9672.png)

Vu que l'image est plus petite ça donne l'impression que c'est plus grand, je peux réduire la hauteur : 
![capture d ecran 2015-02-12 a 15 52 45](https://cloud.githubusercontent.com/assets/10801383/6169651/4f63aa80-b2cf-11e4-86be-eb4da8b106eb.png)

**Comment by Eskimon** [comment]
Je suis content :)

**Comment by firm1** [comment]
Moi aussi

**Comment by GerardPaligot** [comment]
Partout ailleurs, sur la version desktop, les icones ne sont pas plus à gauche ?
