### ISSUE TITLE
API : paramètres pour le ban mal nommés

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2294]
Lorsqu'on regarde la doc de l'API, et plus précisément l'appel POST sur `/api/membres/{pk}/ban/`, on voit que l'url accepte en POST les paramètres `ls-jrs` et `ls-text` (cf capture ci-dessous).

Ces paramètres sont mal adaptés car non seulement ce sont les paramètres utilisés pour `/api/membres/{pk}/lecture-seule/` , mais on s'attendrait plutôt à `ban-jrs` et `ban-text`.

Je n'ai pas regardé plus loin pour savoir si le problème est dans le code ou dans la doc, donc je vais tagguer large.

![param-ban](https://cloud.githubusercontent.com/assets/6066015/6165008/ae905e98-b2a4-11e4-85cc-c632d115c8d3.PNG)

**Comment by GerardPaligot** [comment]
C'est dans la documentation.

**Comment by Eskimon** [comment]
ok
