### ISSUE TITLE
le détail du membre renvoyé par l'API est incohérent avec celui renvoyé par le site

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2295]
# Résultat de l'API
## membre dont l'id est 957

Il s'agit du membre "anonyme"

![decalage-1](https://cloud.githubusercontent.com/assets/6066015/6165325/4f981586-b2a7-11e4-8135-1809482a77bb.PNG)
## membre dont l'id est 958

Il s'agit du membre "Sebajuste"

![decalage-2](https://cloud.githubusercontent.com/assets/6066015/6165327/4f9f9c70-b2a7-11e4-977f-c33e50582a6e.PNG)
# Résultat du site
## membre dont l'id est 958

Il s'agit du membre "anonyme"

![decalage-3](https://cloud.githubusercontent.com/assets/6066015/6165326/4f9e1c9c-b2a7-11e4-81cf-499520be35bb.PNG)

Le site et l'API ne renvoient donc pas les même informations.

**Comment by GerardPaligot** [comment]
L'incohérence commence à apparaitre à partir de `http://beta.zestedesavoir.com/forums/sujets/membre/757/` qui correspond à une 404 sur le site mais à captain28 dans l'API.

Je me demande si c'est pas une incohérence dans les données de la bêta.

**Comment by SpaceFox** [comment]
Je ne comprends pas comment c'est possible d'avoir une incohérence alors
qu'on est sensé récupérer les données par ID.

Le 12 février 2015 11:21, Gérard Paligot notifications@github.com a écrit
:

**Comment by GerardPaligot** [comment]
@SpaceFox Ca m'échappe aussi. Je ne sais pas pour la page précisée par @firm1 mais je suis sûr à 100% que l'API se base sur la pk du `Profile` pour renvoyer un utilisateur. (https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/api/serializers.py#L60)

**Comment by GerardPaligot** [comment]
Faut pas chercher plus loin : https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/views.py#L970

**Comment by GerardPaligot** [comment]
Je retire le tag API, cela ne concerne pas l'API.

**Comment by firm1** [comment]
Hmm, j'ai un doute quand même. La table User étant la table centrale, l'API devrait se baser sur celle-ci. La table profile n'est qu'une table satellite au final, et on voit bien qu'il y'a une desynchro entre ses ids et les ids de la table user.

Est-ce qu'il y'a une raison importante pour laquelle l'API est basée sur le profile plutot que sur le User ?

**Comment by GerardPaligot** [comment]
Oui, il y en avait plusieurs :
- Il a fallu faire un choix entre `User` et `Profile` et ne pas jongler avec les deux.
- A l'époque de ce choix, on se disait que ça serait bien d'utiliser au plus possible le `Profile` plutôt que `User`. La discussion avait commencé suite à la pagination qui faisait à chaque fois une requête à partir de l'`User` pour avoir le `Profile` associé.
- Cela oblige les serializers de l'API de se baser sur `User` et non plus sur `Profile`. Ce qui les complexifierait vraiment **énormément**.

**Comment by firm1** [comment]
Bon, je laisse ça au DTC ( cc @SpaceFox ) mais, c'est une mauvaise idée de se trainer une désyncrho pareille.

**Comment by SpaceFox** [comment]
> La table User étant la table centrale

En fait, ton erreur est là : la table `User` n'est **pas** la table centrale, c'est bien `Profile` qui l'est. Ou plus exactement, ce sont les deux qui la sont.

Théoriquement, c'est une seule et même table (solution officielle Django depuis la dépréciation de la solution qui était utilisée jusqu'au passage à Django 1.6). Sauf que les modifications que ça impliquait étaient trop lourdes, donc on a appliqué l'autre solution officielle Django : [coller une relation 1..1 entre les 2 tables](https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/models.py#L36). Le problème étant que comme `User` fait partie du modèle standard, elle n'a pas été modifiée, donc il n'y a pas de contrainte depuis `User` vers `Profile`.

La théorie, c'est qu'on devrait toujours et en tous cas pouvoir faire, indifféremment `profile.user` et `user.profile`.

Là où il y a quelques chose de bizarre, c'est qu'il semblerait qu'on ait pas une correspondance exacte entre les clés primaires de ces 2 tables. C'est très étonnant, parce que la technique standard de ce genre de montage serait d'avoir `Profile.id = User.id` avec en plus une clé étrangère entre ces 2 champs.

Sauf que ce crétin d'ORM Django a créé, sur `Profile`, un `id` en auto-increment **et** un `user_id`.

Je ne sais pas trop par quel miracle, mais un jour on s'est retrouvé avec un `User` sans son `Profile`, ce qui ne devrait jamais arriver.

Quoiqu'il en soit, l'API **doit** se baser sur `Profile` et non sur `User` pour les raisons suivantes :
1. L'API a besoin de données qui sont dans `Profile` et non dans `User`
2. `Profile` a un champ `user_id` qui est une clé étrangère unique non nullable vers `User`. Ce qui nous garantit que tout  `Profile` renvoie vers un unique `User`. Ceci implique qu'en récupérant les données sur les `Profile`, on ne récupère **que** des données cohérentes, alors qu'en récupérant des  `User` on peut tomber sur des données corrompues.

D'autre part, comme les IDs de ces deux tables sont incohérents entre eux, à cause de Django qui fait un peu n'importe quoi dans sa conception, il va falloir utiliser, à travers toute l'API, quel est l'ID de l'utilisateur entre `User.id` et `Profile.id`. Et s'y tenir, sous peine de surprises...

PS : mon avis personnel est de n'utiliser **que** des `Profile.id` partout. En fait, l'idéal serait même de fusionner ces deux tables, mais là on atteint un chantier bien lourd...

**Comment by Eskimon** [comment]
Question peut-etre conne : Dans nos modele de tutos et autre chose on link toujours vers User non ? Du coup est-ce qu'on pourrait pas faire un coup de patch pour:
- Ajouter le lien sur les id (pour que `Profile` suive `User`)
- Forcer le recopiage de tout les id de User vers Profile ?

**Comment by firm1** [comment]
> En fait, ton erreur est là : la table User n'est pas la table centrale, c'est bien Profile qui l'est. Ou plus exactement, ce sont les deux qui la sont.

Ce n'est pas ce que me dit mysql. la table member_profile contient un "id_user" qui représente la clé étrangère de user dans profile. La table auth_user quant à elle ne contient aucune clé étrangère. Donc on a aucune contrainte d'intégrité au niveau de la base qui nous dit force à avoir un profile associé à chaque user. On peut donc avoir (niveau bd) un user sans profil associé, mais on ne peut pas avoir un profile sans user. Voila une des raison qui me fait dire que la table user est centrale.

L'autre raison étant que dans le code existant, la plupart des liaison sont faites à partir du pk d'un user (voir [ici](https://github.com/zestedesavoir/zds-site/search?l=python&q=%22user.pk%22&type=Code&utf8=%E2%9C%93) et [ici](https://github.com/zestedesavoir/zds-site/search?utf8=%E2%9C%93&q=%22usr.pk%22&type=Code)). Donc, jusqu'ici la table User a toujours été la table centrale.

Maintenant, si on veut tout migrer sur du profile, il faut le faire partout de peur de trainer des incohérences comme celles qu'on a en ce moment.

**Comment by SpaceFox** [comment]
Je ne sais pas pourquoi je me fais chier à pondre un pavé d'explication si c'est pour que tu ne le lise pas. Sérieusement.

**Comment by SpaceFox** [comment]
Pour d'aider :
1. La logique de fonctionnement a été **inversée** par rapport à ZdS pré Django 1.6
2. Les données de `Profile` te garantissent la cohérence avec `User` et pas l'inverse, ce qui fait que **fonctionnellement** `Profile` est la table principale.

Mais encore une fois, cette notion de table principale n'a pas vraiment de sens : on ne devrait jamais récupérer l'une sans l'autre.

**Comment by firm1** [comment]
C'est lu, mais ce que j'explique c'est que ce qui théoriquement devrait être une relation 1..1 n'est pas le cas en pratique, donc partant de là, profile n'est qu'une table satellite.

Donc il est plus judicieux (vu l'état de nos données) de linker la table centrale (user d'après le modèle physique de la base). C'est tout aussi bénéfique pour les perfs. Car on a toujours besoin des infos contenus dans user, et donc si on base tout sur profile, chaque qu'appel nécessitera une jointure avec user.

**Comment by SpaceFox** [comment]
>  mais ce que j'explique c'est que ce qui théoriquement devrait être une relation 1..1 n'est pas le cas en pratique, donc partant de là, profile n'est qu'une table satellite.

J'explique ce qu'il en est dans mon pavé, et pourquoi contrairement à ce que tu imagines, Profile reste la table principale qui fait foi dans ce qui est important dans nos données.

>  Donc il est plus judicieux (vu l'état de nos données) de linker la table centrale (user d'après le modèle physique de la base). C'est tout aussi bénéfique pour les perfs. Car on a toujours besoin des infos contenus dans user, et donc si on base tout sur profile, chaque qu'appel nécessitera une jointure avec user.

J'ai écrit tout un pavé pour expliquer pourquoi ceci c'est faux. En particulier parce qu'aujourd'hui, et je me répète, et je commence à détester ça, tout appel à l'une des tables nécessite un appel à l'autre.

**Comment by firm1** [comment]
J'ai peut être mal compris, donc j'aimerai des eclaircissements. Mais en quoi, baser les appels sur profile, nous évitera d'appeler à chaque fois `profile.user` ?

Car, aujourd'hui, un topic, un post, un mp, un tutoriel, un article, un groupe,.. est basé sur la clé étrangère d'un user.

**Comment by SpaceFox** [comment]
> nous évitera d'appeler à chaque fois profile.user ?

Réponse :

>  tout appel à l'une des tables nécessite un appel à l'autre.

OK, on va la faire encore plus courte : la seule solution vraiment propre, c'est de fusionner ces tables. Point.

**Comment by firm1** [comment]
> tout appel à l'une des tables nécessite un appel à l'autre.

Si c'est bien le cas, en effet, l'une ou l'autre c'est pareil au niveau perfs. Mais du coup pour résoudre l'issue on passe en profile partout ailleurs ?

**Comment by Eskimon** [comment]
Ca peut ptet eclaircir les choses ? https://zestedesavoir.com/forums/sujet/2016/le-bar-back/?page=2#p44530

**Comment by SpaceFox** [comment]
Oui et non : techniquement, on voit bien que les liens se font vers users,
ce qu'on savait.

Mais ça ne change rien au fond du problème : aujourd'hui nos 2 tables sont
intimement liées au point qu'elles devraient être fusionnées. Et la vraie
donnée qui fait foi, c'est bel et bien Profile qui la porte, parce que
Profile garantit qu'il y a un User derrière alors que l'inverse est faux.

2015-02-18 20:46 GMT+01:00 Eskimon notifications@github.com:

**Comment by GerardPaligot** [comment]
Quelle est la décision pour finir ? Devons-nous fermer cette issue pour en créer une nouvelle qui explique qu'il faut changez toutes les dépendances à User partout pour Profile ?

**Comment by SpaceFox** [comment]
Au point où on en est et vu que l'API est finie, j'aimerais bien savoir si c'est faisable de revenir à un modèle à table unique. Parce que ça nous simplifierait bien la vie (une fois en place, parce que la PR pour faire ça risque d'être un poil complexe).

**Comment by GerardPaligot** [comment]
Du côté de l'API, si je n'ai plus qu'une table (donc si Profile est fusionné avec User), je vais pouvoir faire fondre du code parce que je me suis cassé la tête à afficher sur un seul niveau toutes les informations. Donc, avoir quelque chose comme ceci :

``` json
{
  "pk": 42,
  "username": "Andr0",
  "email": "andro@zds.com",
  ...
}
```

Plutôt que :

``` json
{
  "user": {
    "pk": 42,
    "username": "Andr0",
    "email": "andro@zds.com"
  },
  ...
}
```

Je ne peux que encourager cette fusion du côté de l'API.

**Comment by GerardPaligot** [comment]
J'ai l'impression que c'est le bug User/Profile ici, duplicate?

**Comment by SpaceFox** [comment]
Doublon.
