### ISSUE TITLE
L'url de l'avatar renvoyée par l'API est souvent relative, souvent absolue

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2296]
L'API fournit pour l'url de l'avatar soit une url absolue, soit une url relative, c'est une mauvaise pratique.

Soit on fournit une url absolue, soit on fournit une url relative. Ce n'est pas au client de l'API de deviner les règles pour savoir quand rajouter le nom de domaine du serveur.

Capture d'écran d'un rendu de l'API avec url relative.

![signature](https://cloud.githubusercontent.com/assets/6066015/6165541/1cadfed6-b2a9-11e4-9493-087ca3b41528.PNG)

**Comment by GerardPaligot** [comment]
Elle ne fait que renvoyer ce qui est sauvegardé en base. La mauvaise pratique pourrait donc se situer dans la gestion de l'avatar dans le modèle ?

**Comment by Eskimon** [comment]
Bien joué @firm1 !
