### ISSUE TITLE
L'API renvoit du html pour certaines 404 au lieu du json

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2297]
Voici une url dont la 404 renvoyée est normale (c'est à dire du json avec une 404) : `http://beta.zestedesavoir.com/api/membres/3/`

Voici une url dont la 404 renvoyée n'est pas bonne : `http://beta.zestedesavoir.com/api/membres/c/`.

Dans la deuxième url, on a toute la partie html du site. Ce n'est pas un comportement normal pour une API.

**Comment by Eskimon** [comment]
L'une est une 404 "venant du back" et l'autre "venant de nginx" mais effectivement c'est un souci

**Comment by GerardPaligot** [comment]
C'est un souci mais venant de qui ? L'URL enregistrée dans le back de l'API, c'est une URL avec des chiffres et non pas des lettres. Cela me semble donc normal que la main soit laissé à nginx. N'est-ce pas un problème d'infra du coup ?
