### ISSUE TITLE
Il est possible d'envoyer un MP a un membre qui n'a pas encore activé son compte

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2299]
Le membre est question : `http://beta.zestedesavoir.com/membres/voir/asilajan/`

Son compte n'est pas activé, mais je peux quand même lui envoyer un message.

**Comment by Situphen** [comment]
Franchement, est-ce réellement un problème qu'un membre puisse envoyer un message privé à un autre membre non activé ?

**Comment by firm1** [comment]
Par principe un membre non activé n'est pas censé être joignable.

**Comment by Eskimon** [comment]
Yep,
- Le nom active se prendra un email pour un MP auquel il ne pourra pas repondre
- L'expediteur n'a aucune info que ce message restera sans reponse pour le moment

D'une maniere generale, les membres non active ne devrait pas etre visible/ajoutable sur aucun truc (co-auteur, MP...)

**Comment by A-312** [comment]
C'est plus une évolution qu'un bug.

**Comment by SpaceFox** [comment]
Non pour le coup, je suis d'accord avec @firm1 : le comportement actuel n'a aucune logique, c'est donc un bug.

**Comment by Eskimon** [comment]
ok
