### ISSUE TITLE
Impossible de voir un tuto offline quand on est staff

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#230]
Mon compte est staff. Quand je veux voir un tuto offline (exemple : http://preprod.zestedesavoir.com/tutoriels/off/32/3d-temps-reel-avec-irrlicht/ ) j'ai une 403.

De plus, quand on clique sur "Tous les tutoriels" depuis le menu "Tutoriels" de la barre du haut, les liens des tutos de la liste pointent sur les tutos offline, qu'on soit connecté en staff ou déconnecté. Il me semble plus logique que ces liens pointent vers les tutos publiés.

PS : Désolé si ça a déjà été remonté, je n'ai pas trouvé.

**Comment by ShigeruM** [comment]
Idem pour les articles en fait (que ce soit pour les liens ou pour l'accès offline).

**Comment by firm1** [comment]
Le bug est fixé et en prod.

Merci, je ferme
