### ISSUE TITLE
Un membre non activé n'a pas de badge et une sidebar fausse 

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2300]
Un profil qui n'a pas été active (pas de clique sur le lien d'activation) ne possède pas de badge avec cette information et a une sidebar erronée qui laisse penser que le membre est LS + Banni.

**Comment by GerardPaligot** [comment]
Corrigé. Merci à @firm1 pour le fix et @pierre-24 et @SpaceFox pour la QA.
