### ISSUE TITLE
Impossible de voir le profil de certains membres avec des caractères particuliers

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2301]
Le membre en question est `&#34;a`.

Scénario : 
- je vais dans nouveau MP : http://beta.zestedesavoir.com/mp/nouveau/
- Je saisi le pseudo ci-dessus dans les participants
- Je rempli le autres colonnes obligatoires
- J'envoi le MP
- Je clique sur l'icone du membre qui apparait dans la liste des participants
- J'ai une 404 sur son profil.

**Comment by Eskimon** [comment]
Car l'URL est automatiquement transformée en `http://beta.zestedesavoir.com/membres/voir/&/#34;a/` (notez le slash qui s'est immiscé entre le `&` et le `#`)

**Comment by Situphen** [comment]
Le problème c'est que l'on encode pas les liens qui s'affichent sur le site !

**Comment by ghost** [comment]
Il suffit de de encoder la valeur avant de l'utiliser ?

J'esssayerai peut-être de faire cette issue.

**Comment by Eskimon** [comment]
ok

**Comment by GerardPaligot** [comment]
Je re-ouvre cette issue. J'ai créé l'utilisateur `&#34;b` sur la bêta et j'ai une erreur 500 quand je vais sur son profil à partir des participants d'un MP.

Lien généré vers son profil : http://beta.zestedesavoir.com/membres/voir/&/#34;b/

**Comment by Eskimon** [comment]
Yep je confirme sur Chrome et Firefox... c'est bizarre quand meme que le TU passe pourtant et la QA etait bonne oO

**Comment by SpaceFox** [comment]
Corrigé et mergé.

**Comment by yapper-git** [comment]
Ce bug n'est pas résolu et devrait être réouvert.

En effet:
- Connectez-vous sur la béta avec comme username `$ïtréma /slash #hash @arobase$` et mot de passe `itrema` (sans caractères spéciaux).
- Rendez-vous à la liste des MP, sélectionner un MP.
- Les liens sur les MP ne fonctionnent pas (s'ils contiennent &, espaces etc.) ! Par contre ceux où il y a la liste des participants OUI !! La QA a dû se trouver à ce niveau-là… Il faut tester le lien juste à côté de la date 'Il y a X minutes/jours' !

**Comment by yapper-git** [comment]
Le problème est simple à corriger, comme évoqué dans #2788 le urlquote est à mettre dans settings.py et non là où il a été mis (models.py).

**Comment by pierre-24** [comment]
Donc ça c'est bon, merci @yapper-git  :)
