### ISSUE TITLE
L'url de l'API n'est pas la bonne

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2302]
Selon la spec l'API devrait être dispo en prod sur :  `api.zestedesavoir.com` et en beta sur `api.beta.zestedesavoir.com`.

L'url pour la version en bêta n'est pas fonctionnelle malgré [la création du nom de domaine](http://zestedesavoir.com/forums/sujet/2320/creer-un-sous-domaine-pour-lapi/?page=1#p41998).

Vu comme ça on pourrait penser que c'est un problème de pur infra (redirection) mais c'est plus complexe que ça. Car si on regarde les retours de l'api sur cette url `http://beta.zestedesavoir.com/api/membres/`, on voit tout de suite dans le contenu de next `http://beta.zestedesavoir.com/api/membres/?page=2`.Il faudra donc que le back s'aligne sur les urls next et previous un peu partout pour que les urls de l'api restent cohérente.

Donc on devrait avoir pour le cas suscité la valeur de next équivalente à `http://api.beta.zestedesavoir.com/membres/?page=2`

Comme d'habitude dans le doute, je taggue large.

**Comment by Eskimon** [comment]
hum... ping @Ge0 ?

**Comment by Situphen** [comment]
Up ?

**Comment by Eskimon** [comment]
il faut ping @Un-Cornichon ;)

**Comment by ghost** [comment]
Pour le contenu renvoyé par l'API je ne pense pas être compétent, néanmoins êtes vous certains que les noms de domaine sont créés correctement ? 
dig api.beta.zestedesavoir.com +short et dig api.zestedesavoir.com +short, ne me retourne aucune adresse IP.

**Comment by Eskimon** [comment]
Je me demande si finalement on ferait pas mieux de rester sur notre format qui fonctionne et approuver plutot que de s'embeter à aller s'établir sur un nouveau sous-domaine... @SpaceFox tu en penses quoi ?

**Comment by SpaceFox** [comment]
Je suis d'accord.
