### ISSUE TITLE
Libellé Administration réduit dans la sidebar

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2304]
Le libellé "Administration" de la sidebar est devenu "Admin" dans la visualisation d'un tutoriel en hors-ligne.

Le bug n'est pas présent en prod, mais en beta, donc il s'agit d'une régression.
## PROD

[Url](http://zestedesavoir.com/tutoriels/329/algorithmique-pour-lapprenti-programmeur/399/presentation-de-la-notion-de-complexite-algorithmique/2018/quest-ce-quun-algorithme/)

Screen : 
![sidebar-1](https://cloud.githubusercontent.com/assets/6066015/6168567/b2d17592-b2c6-11e4-9a83-5efc39100ace.PNG)
## BETA

[Url](http://beta.zestedesavoir.com/tutoriels/329/algorithmique-pour-lapprenti-programmeur/399/presentation-de-la-notion-de-complexite-algorithmique/2018/quest-ce-quun-algorithme/)

Screen : 
![sidebar-2](https://cloud.githubusercontent.com/assets/6066015/6168569/b80d45d6-b2c6-11e4-8cea-76b0576c896f.PNG)

**Comment by ghost** [comment]
Réoganisation CSS foireuse. Je prends.

**Comment by SpaceFox** [comment]
Une réorganisation CSS peut changer un libellé ?!

**Comment by ghost** [comment]
@SpaceFox oui :

```
<h3>Admin<span class="wide">istration</span></h3>
```

**Comment by SpaceFox** [comment]
OK... je vais vomir et je reviens.

**Comment by GerardPaligot** [comment]
Un renard de l'espace qui vomit dans son casque, c'est pas un peu crade ? ^^

**Comment by SpaceFox** [comment]
J'enlève mon casque pour ce faire !

**Comment by ghost** [comment]
Un renard ça utilise quoi comme navigateur ? ^^"

**Comment by firm1** [comment]
Comment tu réussit à respirer sans ton casque ? ^^

**Comment by SpaceFox** [comment]
> Un renard ça utilise quoi comme navigateur ? ^^"

Opera.

> Comment tu réussit à respirer sans ton casque ? ^^

J'ai aussi un truc qu'on appelle un vaisseau spatial hein.

Et si on revenait au sujet ?

**Comment by ghost** [comment]
Erreur sur la syntaxe :

```
@media only screen and ($media-extra-wide) { }
```

Au lieu de : 

```
@media only screen and #{$media-extra-wide} { }
```
