### ISSUE TITLE
Il est possible d'envoyer un MP à l'auteur externe

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2305]
D'après la PR #1865 il dervait être impossible d'envoyer un MP au compte Auteur Externe et au compte anonyme.

Cependant, c'est possible en ce qui concerne le compte Auteur Externe. Comment faire ?

Scénario : 
- Je vais sur un tutoriel rédigé par un auteur externe : [celui-ci par exemple](http://beta.zestedesavoir.com/tutoriels/489/le-tri-par-selection/)
- Je clique sur le bouton "Signaler une faute dans ce tutoriel"
- Je tape quelque chose dans la zone de texte
- Je clique sur envoyer

Voilà, j'ai maintenant un MP avec le fameux auteur externe.

**Comment by SpaceFox** [comment]
Pour moi, le vrai problème, c'est qu'on peut signaler une faute sur un tutoriels où il n'y aura personne pour corriger. Le MP n'étant qu'un effet de bord.

**Comment by firm1** [comment]
Du coup c'est fermé ici.
