### ISSUE TITLE
La recherche ne marche ni pour les chapitres, ni pour les parties, ni pour les extraits d'un tutoriel

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2307]
Rechercher dans un chapitre, partie, ou extrait d'un tutoriel ne renvoi rien (cf. capture).

On est a mon avis sur une régression. C'est dommage quand on sait que la fonctionnalité est très mise en avant.

![search-bug](https://cloud.githubusercontent.com/assets/6066015/6170486/5787ff3a-b2d5-11e4-9925-1e7a3282bb30.PNG)

**Comment by Eskimon** [comment]
On est sur que solr tourne bien sur la preprod ? (j'approuve le mot clé de recherche :D )

**Comment by firm1** [comment]
> On est sur que solr tourne bien sur la preprod ?

Aucun moyen de vérifier là tout de suite, mais étant donné que j'ai un résultat (dont le tuto Arduino) si je coche "tutoriel" dans la sidebar, je suppose que oui.

**Comment by SpaceFox** [comment]
Est-ce que c'est pas un problème de données ? Peut-être qu'il n'y a tout
simplement pas le tuto arduino sur la préprod.

**Comment by firm1** [comment]
[Normalement oui](http://beta.zestedesavoir.com/tutoriels/537/arduino-premiers-pas-en-informatique-embarquee/)

**Comment by ghost** [comment]
Comment on peut installer solr en local ? (Où se passe la configuration ?)

**Comment by firm1** [comment]
Tout est la pour solr : http://zds-site.readthedocs.org/fr/latest/install/install-solr.html

**Comment by gustavi** [comment]
Bon je le dis ici mais c'est valable pour d'autres issues : @firm1 est-ce que tu peux mettre une milestone sur les issues que tu crées **s'il te plait** ?

**Comment by Eskimon** [comment]
Je viens de faire un test en prod, ca marche, je ferme
