### ISSUE TITLE
Erreur 500 sur le diff d'un nouveau tutoriel

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2308]
Scénario : 
- Je crée un mini-tuto
- Je vais dans l'historique
- Je clique sur l'unique lien de diff
- J'ai une erreur 500

Donc OK, le scénario est rare, mais on ne devrait pas avoir d'erreur 500.

**Comment by DevHugo** [comment]
L'erreur est sur cette ligne: https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L214.

L'erreur se produit aussi dans se scénario:
- Je crée un mini-tuto
- Je fait des modifications
- Je vais dans l'historique
- Je clique sur le premier lien de diff
- => Le diff est vide.

La commande qu'il pourrait exécuter est git diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 < Hash du premier commit > pour le premier diff.

cf: http://stackoverflow.com/questions/9765453/gits-semi-secret-empty-tree

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
To be tested.

2015-04-16 14:59 GMT+02:00 Eskimon notifications@github.com:
