### ISSUE TITLE
Aucune action possible dans une galerie depuis son mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2309]
Dans une de mes galeries sur mobile je ne peux pas faire d'action (ajouter une image, supprimer une galerie, etc.) car elle n'existent pas dans la sidebar (cf. Screen)

![tmp_3065-screenshot_2015-02-12-17-18-38661574998](https://cloud.githubusercontent.com/assets/6066015/6171571/ce2174a4-b2db-11e4-8c3a-e8a232ecb771.png)

**Comment by ghost** [comment]
Je la prend.

Il manque le bouton "Ajouter une image" et "Importer une archive".

**Comment by Eskimon** [comment]
Je viens de tester sur mobile, les boutons sont bien la (serveur beta, 15.5.1). Je ferme.
