### ISSUE TITLE
Liens vers les catégories de tutos dans la sidebar

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#231]
Depuis la page d'accueil, tous les liens vers les catégories de tutos dans la sidebar (PHP, HTML, CSS... jusqu'à Biologie) mènent à une liste de tous les tutos publiés. Bref les catégories ne semblent pas en place ou en tout cas pas utilisées comme filtre sur cette page.

**Comment by firm1** [comment]
Le bug est fixé et en prod.

Merci, je ferme
