### ISSUE TITLE
Les cases a cocher ont un rendu étrange sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2310]
Navigateur : Firefox
Os : Android
Smartphone : one Plus

![tmp_3065-screenshot_2015-02-12-17-32-24-132311335](https://cloud.githubusercontent.com/assets/6066015/6171799/588a4584-b2dd-11e4-879c-3be6f6f1810b.png)

**Comment by Situphen** [comment]
Je prends

**Comment by Eskimon** [comment]
Toujours vrai ca ?

**Comment by Situphen** [comment]
Bug encore présent sur Firefox. Je laisse quiconque veut le résoudre le faire !

**Comment by artragis** [comment]
Toujours vrai?

**Comment by firm1** [comment]
Alllways truuuuue

![screenshot_2015-10-13-13-55-14](https://cloud.githubusercontent.com/assets/6066015/10454082/3ef5b2b8-71b2-11e5-8d48-7761ecb4149d.png)

**Comment by Eskimon** [comment]
Moi je vois carrément pas la coche dedans... (One Plus Lollipop Chrome)

**Comment by Situphen** [comment]
Je n'arrive pas à trouver pourquoi ça bug sur Chrome Mobile et les solutions sur Internet ne correspondent pas au code HTML généré par notre dépendance donc, à moins que @sandhose ait le temps de chercher et trouver une solution, je vais supprimer la personnalisation des boutons _checkbox_ et _radio_.

**Comment by sandhose** [comment]
J'ai voulu prendre, mais c'est finalement plus lourd à faire que prévu. Il faudrait passer par des pseudo-éléments type `:after` sur le label pour recréer le visuel du checkbox, et utiliser le pseudo-sélecteur `:checked` pour gérer l'état, tout en "cachant" le checkbox original. Je vais essayer de le faire, mais peut-être pas tout de suite, pour le coup :v

**Comment by GerardPaligot** [comment]
J'ai une PR mergée associée à cette issue. C'est bon ici @sandhose ?
