### ISSUE TITLE
Galerie : Problème d'affichage des boutons radios

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2311]
En essayant d'ajouter des utilisateurs a une galerie sur mobile, j'ai un affichage étrange.

Navigateur : Firefox
Os : Android

![tmp_3065-screenshot_2015-02-12-17-59-541707345936](https://cloud.githubusercontent.com/assets/6066015/6172484/6c0fe466-b2e1-11e4-93d3-a9457d929910.png)

**Comment by Situphen** [comment]
Je prends

**Comment by ghost** [comment]
@Situphen Peut-être en profiter pour régler aussi ce problème : https://github.com/zestedesavoir/zds-site/issues/1755 (toujours avec les boutons radios/checkbox).

En plus les checkbox ne semblent pas aligné dans le screen (sans parler de l'indentation).

**Comment by Situphen** [comment]
Je ne pense pas que ce ticket et #1755 ont quelque chose à voir en commun. Et puis, une PR pour un ticket, c'est la règle !

**Comment by ghost** [comment]
@Situphen Le code de radio n'est pas top, il faudrait normaliser ceci. Alors qu'il y a que 4 pages avec...

https://github.com/zestedesavoir/zds-site/search?l=html&q=checkbox&type=Code&utf8=%E2%9C%93

On arrive avec aucune règle commune, il faudrait peut-être normaliser ceci via une autre issue. Après cette issue peut toujours être fermé, pour laisser place à une issue plus générale, c'est qu'un détail.

**Comment by Situphen** [comment]
@A-312 : Je vois pas en quoi il est pas propre ! Mais si tu peux le rendre plus propre, fais une PR ;)

**Comment by ghost** [comment]
Instable #2273, pourtant le css que j'ai appliqué c'est ceux du profil.

Je te fais ce commentaire, car tu as l'intention de faire aussi la #2310, qui s'applique au checkbox.

**Comment by Situphen** [comment]
@A-312 : Corrige ces tickets si tu as la solution, je n'ai pas eu le temps de regarder encore !

**Comment by gustavi** [comment]
Suite à deux tests avec deux personnes différentes ça semble corrigé. Tu peux me confirmer ça @firm1 ?

**Comment by firm1** [comment]
Yes c'est corrigé ça (en prod en tout cas). Par contre je ne sais pas dans quelle version mais je ferme.
