### ISSUE TITLE
Throttling partagé entre tous les utilisateurs

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2317]
Sur la release 1.6, actuellement sur la bêta, le throttling semble partagé entre tous les utilisateurs. Dès qu'un utilisateur arrive à la limite, tout le monde se mange des codes 429.

**Comment by GerardPaligot** [comment]
Il semble possible de forcer DRF à identifier un utilisateur par son IP :

> The X-Forwarded-For and Remote-Addr HTTP headers are used to uniquely identify client IP addresses for throttling. If the X-Forwarded-For header is present then it will be used, otherwise the value of the Remote-Addr header will be used.
> 
> **If you need to strictly identify unique client IP addresses, you'll need to first configure the number of application proxies that the API runs behind by setting the NUM_PROXIES setting. This setting should be an integer of zero or more. If set to non-zero then the client IP will be identified as being the last IP address in the X-Forwarded-For header, once any application proxy IP addresses have first been excluded. If set to zero, then the Remote-Addr header will always be used as the identifying IP address.**
> 
> It is important to understand that if you configure the NUM_PROXIES setting, then all clients behind a unique NAT'd gateway will be treated as a single client.
> 
> Further context on how the X-Forwarded-For header works, and identifying a remote client IP can be found here.

Source:  [Documentation](http://www.django-rest-framework.org/api-guide/throttling/#how-clients-are-identified)

**Comment by SpaceFox** [comment]
Ce que je voudrais d'abord vérifier, c'est si Nginx envoie correctement les `X-Forwarderd-For` et `Remode-Addr` aux processus Django.

**Comment by GerardPaligot** [comment]
Bien, je te laisse vérifier ça. Par contre, je pourrais difficilement résoudre cette issue moi-même étant donné que le throttling ne fonctionne pas chez moi.

**Comment by SpaceFox** [comment]
Il semblerait que le problème vienne d'une erreur de configuration du proxy cache : les clés de conf que reçoit memcached sont toutes de ce type (et ce quelle que soit l'IP de la personne qui utilise l'application) :

> &lt;30 get :1:throttle_anon_127.0.0.1
> &gt;30 sending key :1:throttle_anon_127.0.0.1

**Comment by GerardPaligot** [comment]
Ok, est-ce que tu as une idée de comment corriger le bug ? Si c'est du côté code ou infra ?

**Comment by SpaceFox** [comment]
à priori c'est de l'infra, je suis en train de scruter la chose.

**Comment by SpaceFox** [comment]
Bon alors, c'est définitif : **personne** ne comprends et sait faire fonctionner les requêtes de X-forward et consorts avec nginx en mode reverse proxy. C'est à tel point que sur les 10 premiers résultats Google, tu as 10 manières différentes de les traiter... dont 9 plus ou moins partiellement fausses.

Avant, on avait ça :

```
proxy_set_header X-Forwarded-Host $server_name;
proxy_set_header X-Forwaded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header REMOTE_ADDR $remote_addr;
proxy_set_header Host $http_host;
proxy_redirect off;
```

Ce qui ne fonctionne pas comme voulu.

A priori, cette configuration fait le taff :

```
proxy_redirect     off;
proxy_set_header   Host             $host;
proxy_set_header   X-Real-IP        $remote_addr;
proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
```

Ce qui me donne bien dans memcached (en supposant que mon ip soit `123.123.123.123`) :

```
<30 get :1:throttle_user_123.123.123.123
>30 sending key :1:throttle_user_123.123.123.123
```

Faudra que j'essaie avec IPv6 tiens.

**Comment by SpaceFox** [comment]
PS : il semblerait qu'il n'y ait pas d'IPv6 en bêta. C'est normal ?

**Comment by SpaceFox** [comment]
PPS (oui je spamme) : avant de fermer, je voudrais tester ce que ça donne en IPv6 et avoir la confirmation de quelqu'un d'autre.

**Comment by GerardPaligot** [comment]
Ok, donc si je comprends bien. Le problème est résolu ?

IPv6 : Tu parles encore de l'infra ou c'est l'API qui supporte pas l'IPv6 ?

**Comment by SpaceFox** [comment]
J'ai pas de résolution DNS de beta.zestedesavoir.com ou preprod.zestedesavoir.com sur une adresse IPv6, donc je ne peux pas tester le throttling pour un utilisateur IPv6.

Normalement le problème est résolu, mis à part un test tiers et un tests sur IPv6.

**Comment by GerardPaligot** [comment]
Je confirme que le throttling fonctionne en mode anonyme et connecté avec leurs limitations respectives.

**Comment by firm1** [comment]
o/ 

Autre chose à vérifier aussi. On a vu que l'autocomplemtion se basait sur l'API. Est-ce que ça signifie que l'autocomplétion sera aussi soumise aux mêmes règles de throttling qu'un utilisateur normal ?

**Comment by GerardPaligot** [comment]
> Autre chose à vérifier aussi. On a vu que l'autocomplemtion se basait sur l'API. Est-ce que ça signifie que l'autocomplétion sera aussi soumise aux mêmes règles de throttling qu'un utilisateur normal ?

Je me suis posé la question aussi et je ne sais pas trop. Mais, si oui, ça sera le taux d'un utilisateur connecté fixé à 2000 requêtes. Nous sommes large mais ça mérite d'être testé.

**Comment by GerardPaligot** [comment]
Est-ce que cette issue peut être close ? Elle est marquée bloquante pour la release-1.6 mais j'ai l'impression que plus rien ne le justifie.

**Comment by SpaceFox** [comment]
J'aimerais bien savoir si on peut tester l'IPv6 en bêta, et si non comment on peut améliorer ça.

**Comment by firm1** [comment]
> Je me suis posé la question aussi et je ne sais pas trop. Mais, si oui, ça sera le taux d'un utilisateur connecté fixé à 2000 requêtes. Nous sommes large mais ça mérite d'être testé.

Après vérification, l'autocomplétion (ajax) n'est pas soumise au throttling utilisateur, mais au throttling anonyme, et donc 60 requetes par heure.

ça monte très vite en plus.

Scénario : Avec 10 participants dont le pseudo a au moins 6 caractères. A chaque fois que je tape une lettre, une requête est lancée à l'API. Et donc étant donné que je tape les 5 premières lettres à la main en me trompant un peu, ça me coute au moins (5+2)x10 = 70 requêtes à l'API.

J'explose mon quota facilement au bout de 2 MPs

**Comment by GerardPaligot** [comment]
Et c'est certainement due au fait que l'authentification est différente entre le site et l'API. Ca c'est un problème ...

**Comment by firm1** [comment]
Pas vraiment, ici, le [script Javascript](https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/autocompletion.js#L284) qui se charge de l'autocomplétion ne fait jamais d'authentification. Il se connecte directement en GET et il utilise donc mon adresse IP en tant que utilisateur anonyme de l'API

**Comment by GerardPaligot** [comment]
Tu voudrais que, pour chaque appel à cette fonction, il s'authentifie avant ? Ca semble pas super propre et la table des tokens va monter en flèche (une ligne par token générée en base de données).

**Comment by firm1** [comment]
Non, pas pour chaque appel, mais au chargement du site le JS devrait se connecter une seule fois à l'API et executer les requêtes par la suite avec son token (un vrai client JS quoi, comme on en fait avec Angular/Ember et cie). Sauf que je viens de me souvenir que l'API ne gère pas le CORS :(

La deuxième solution serait que django expose une vue de recherche et le script JS n'aurait qu'à appeler l'url django et pas l'url de l'API.

**Comment by GerardPaligot** [comment]
Si la configuration donnée par Javier fonctionne, ce soir l'API supportera le CORS.

**Comment by firm1** [comment]
Yop et dans ce cas il restera juste a faire la partie JS.

**Comment by GerardPaligot** [comment]
L'issue semble converger vers un nouveau problème. Le throttling a été corrigée mais le front doit effectuer des requêtes authentifiées pour récupérer la liste des utilisateurs dans l'auto-completion. Pouvons-nous clore cette issue bloquante pour la création d'une autre (non bloquante) ?

**Comment by SpaceFox** [comment]
Le throttling marche en IPv6, donc cette issue est corrigée.

Par contre, que se passe-t-il @GerardPaligot si le problème que tu mentionnes n'est pas corrigé ?

**Comment by GerardPaligot** [comment]
Il n'y a plus d'autocompletion. Rapporté par @firm1 un [peu plus haut](https://github.com/zestedesavoir/zds-site/issues/2317#issuecomment-75541049).

**Comment by SpaceFox** [comment]
Pas bloquant :)

**Comment by firm1** [comment]
Je réouvre ici, car le throlling est encore partagé sur la prod.

c'était le cas avec [simbilou](http://zestedesavoir.com/forums/sujet/2549/jouons-avec-lapi-des-membres/?page=1#p45788), et moi même.

PS : cette issue n'est assignée à aucune milestone

**Comment by SpaceFox** [comment]
J'ai chié une conf, déjà signalé, en cours de correction.
