### ISSUE TITLE
L'extrait d'un message masqué est affiché sur la page "Sujets créés par..."

### ISSUE THREAD

**Issue by Fulbert** [zestedesavoir/zds-site#2319]
Signalé lors de la QA de #2285, [ici](https://github.com/zestedesavoir/zds-site/pull/2285#issuecomment-73946128).

Lorsque qu'un message est masqué et qu'il est le premier message d'un sujet, alors son extrait est toujours disponible sur la page _Sujets créés par ..._. Cf. [ici](http://beta.zestedesavoir.com/forums/sujets/membre/328/) (premier lien).

C'est pas un gros problème, car à priori si le premier message est masqué, j'imagine que le sujet est déplacé dans un forum corbeille, auquel cas il ne devrait plus être visible dans la liste des sujets créés (?).

D'ailleurs le titre de cette page contient une faute d'orthographe, je crois bien.

**Comment by GerardPaligot** [comment]
Corrigé, merci @Fulbert !

**Comment by Fulbert** [comment]
Merci @Eskimon et à toi surtout d'avoir pris le temps de m'expliquer quelques détails. :)

**Comment by Fulbert** [comment]
En ce qui concerne la page "Messages postés", les messages masqués n'apparaissaient pas dans le tableau pour les membres simples (non-admin). Donc la condition dupliquée pour cette page par @Eskimon me semble inutile voir contraignante, car du coup l'extrait ne s'affiche pas pour les admins qui sont les seuls à le voir...

C'est franchement du détail... Le compromis serait d'indiqué que le message est masqué (fond de couleur ou paragraphe "Masqué par _[admin]_ : _[raison]_" + extrait.
