### ISSUE TITLE
Lien "Archive" présent sur la page "Tous les tutoriels"

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#232]
Sur la page "Tous les tutoriels" (accessible depuis le menu "Tutoriels" de la barre du haut), il y a un lien "Archive" sous "Télécharger", dans la sidebar. Cela n'a pas de sens et renvoie d'ailleurs une erreur (semble manquer un numéro de tuto dans l'URL, ce qui est logique puisqu'on n'est pas sur un tuto).

**Comment by firm1** [comment]
Le bug est fixé et en prod.

Merci, je ferme
