### ISSUE TITLE
L'auto complétion ne fonctionne pas

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2320]
Sur la 1.6 RC1, l'auto complétion ne marche jamais.

**Comment by GerardPaligot** [comment]
C'est sans aucun doute lié au throttling (https://github.com/zestedesavoir/zds-site/issues/2317)

**Comment by Situphen** [comment]
SI elle fonctionne lors de la création d'un message privé. Par contre, elle ne fonctionne pas lors de l'ajout d'un membre à un message privé, mais c'est un bug Front !

**Comment by SpaceFox** [comment]
Corrigé.
