### ISSUE TITLE
Compteur de membres erroné dans la liste des membres

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2324]
Actuellement sur la 1.6 RC1 en allant sur le lien : http://beta.zestedesavoir.com/membres/

On voit que le nombre de membre est égal à 100 et pourtant il y'en a bien plus.

**Comment by GerardPaligot** [comment]
L'API n'est pas concerné ici.

**Comment by Eskimon** [comment]
> L'API n'est pas concerné ici.

Effectivement, c'est plus au niveau du refactoring que ca cloche. Ce qui se passe c'est que l'on renvoie toujours xx membres par page du paginator et du coup comme on affiche "members.count" on se retrouve à afficher xx. Il faudrait j'imagine retourner une variable supplémentaire "total" mais avec le nouveau "format" du module je galère un peu à voir comment faire

**Comment by GerardPaligot** [comment]
Comme j'avais retiré le tag API, j'avais complètement oublié cette issue. PR faite du coup.

@Eskimon : En fait, la solution que tu as proposé m'a fait peur. Fallait absolument que je propose la solution propre. ^^

**Comment by Eskimon** [comment]
Voila ca c'est fait rapidement et proprement :)
