### ISSUE TITLE
Le nom de l'association est manquant dans le mail de demande d'adhésion

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2325]
En testant l'adhesion à l'association, les membres du CA ont reçu ceci.

> Bonjour, membres du CA,
> 
> Le membre firm1 souhaiterait adhérer à .
> 
> ```
> Identité : Mr. Test
> Adresse courriel : firm1@monmail.com
> Date de naissance : 12/02/2010
> Adresse :
> 
> 12 rue du test, 1351 TEST
> ```
> 
> Raison de cette demande :
> 
> Pour le test
> 
> Cliquez ici pour voir son profil sur le site : http://preprod.zestedesavoir.com/membres/voir/firm1/.
> 
> Cordialement,

Il manque le nom de l'association après "adhérer à"

**Comment by Eskimon** [comment]
meme correction qu'ici : https://github.com/zestedesavoir/zds-site/pull/2091/files

**Comment by DevHugo** [comment]
Cette issue est résolue par https://github.com/zestedesavoir/zds-site/pull/2378. Je viens de tester en local, pouvons nous fermer cette issue ?

**Comment by firm1** [comment]
Et hop, d'une pierre deux coup. Merci @Situphen
