### ISSUE TITLE
Message d'autorisation d'écriture illogique

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2327]
Le texte du message ressemble à un message de sanction (cf. capture).

![typo-auto-ls](https://cloud.githubusercontent.com/assets/6066015/6188386/b3bf9ae0-b390-11e4-8e4d-f188c705928c.PNG)

**Comment by SpaceFox** [comment]
Tiens je pensais qu'il avait été corrigé celui-ci. On doit déjà avoir un ticket du genre qui traine.
