### ISSUE TITLE
Problème de cache dans les appels à l'API

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2329]
Scénario : 
- Je me connecte en tant que firm1
- Je change mon username pour devenir firm2
- J'envoi un mp à un membre
- Je retourne encore changer mon username pour redevenir firm1
- Je vais dans une de mes galleries d'image
- Je choisi d'ajouter un utilisateur à ma gallerie
- Je commence à saisir "fir" et dans la liste des propositions j'ai "firm2" alors que ce username est censé ne plus exister

Il y'a donc visiblement un problème de cache quelque part étant donné que l'ajout d'un utilisateur demande l'accès à l'API

**Comment by GerardPaligot** [comment]
> J'envoi un mp à un membre

Sous-entendu, je fais un appel à l'API pour récupérer un membre via l'auto completion qui fait un appel à l'API et qui le met en cache, je suppose ?

Si c'est bien ça, le cache a été placé à 15 minutes sur l'API.

**Comment by SpaceFox** [comment]
Dans un monde idéal, changer le nom d'un utilisateur invalide les caches
qui contiennent cet utilisateur - et seulement eux.

Seulement, y'a moyen que ce soit tellement complexe à mettre en cache que
le cache de 15 minutes reste une meilleure solution.

Le 13 février 2015 15:37, Gérard Paligot notifications@github.com a écrit
:

**Comment by firm1** [comment]
> Sous-entendu, je fais un appel à l'API pour récupérer un membre via l'auto completion qui fait un appel à l'API et qui le met en cache, je suppose ?

Je suppose que c'est à cause de ça, mais je n'étais pas sur à 100 %.

Par contre, on a un petit bout de doc qui donne les parametrages en terme de cache sur le serveur et ce que ça implique en gros ?

Parce que du coup je me demande si ça veut dire qu'un utilisateur peut s'inscrire, et reste invisible pendant 15 minutes. En gros, est-ce que l'invalidation du cache est mise en place ?

EDIT : d'après SpaceFox il n'y aurait pas d'invalidation. C'est confirmé ?

**Comment by GerardPaligot** [comment]
> Par contre, on a un petit bout de doc qui donne les parametrages en terme de cache sur le serveur et ce que ça implique en gros ?

J'ai prévu d'améliorer la documentation de l'API ce week-end. Mon week-end vient de se libérer. Je vais pouvoir travailler là dessus.

> Parce que du coup je me demande si ça veut dire qu'un utilisateur peut s'inscrire, et reste invisible pendant 15 minutes. En gros, est-ce que l'invalidation du cache est mise en place ?

Il faut que je vérifie dans la documentation.

**Comment by GerardPaligot** [comment]
En faisant une rapide recherche sur la [documentation du cache avec DRF-Extensions](http://chibisov.github.io/drf-extensions/docs/#caching) (bibliothèque pour intégrer le cache dans l'API), il ne mentionne nulle part une invalidation. Simplement la possibilité de pouvoir appliquer un _timeout_ (que j'ai fixé à 15 minutes).

Concernant la documentation, vous pouvez en voir une nouvelle version sur cette [PR](https://github.com/zestedesavoir/zds-site/pull/2342).

**Comment by GerardPaligot** [comment]
Que faut-il faire pour cette issue encore ?

**Comment by Eskimon** [comment]
ping

**Comment by Situphen** [comment]
Est-ce encore d'actualité ? Si oui, que faire pour résoudre ça ?

**Comment by GerardPaligot** [comment]
Je ne sais pas trop si je dois créer une nouvelle issue ou juste compléter cette issue. Dans tous les cas, voici des informations complémentaires concernant les problèmes de cache sur l'API.

Il y a bien un problème.

Un scénario simple :
1. Dans une conversation, poster un message (à partir de l'API ou non).
2. Demandez la liste des messages de la dite conversation.
3. Constatez que le dernier message créé n'apparait pas.

Le cache semble faire effet alors qu'il devrait être invalidé (puisque nous avons ajouté un nouveau message dans la conversation) et renvoyer la liste des messages avec le nouveau message fraichement créé.

Personnellement, j'aimerais bien trouvé une solution pour les besoins de ZMessenger. 

Nouveau problème : Je ne trouve aucun moyen de conserver du cache tout en résolvant le problème. Pire, je n'ai aucun moyen de faire des tests en local pour savoir si je parviens à corriger le problème.

Du coup, je suis bloqué et ouvert à toutes les propositions ...

**Comment by GerardPaligot** [comment]
Une issue est en cours sur le dépôt drf-extensions : https://github.com/chibisov/drf-extensions/issues/120
