### ISSUE TITLE
Le front de la zone d'administration ne fonctionne pas

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2331]
Url concernée : http://beta.zestedesavoir.com/admin/

La page n'a pas de design (malgré le raffraichissement du cache). Il semblerait donc que la procédure de MEP ne mette pas à jour le front de la zone d'admin.

**Comment by SpaceFox** [comment]
Je suppose un effet de bord de https://github.com/zestedesavoir/zds-site/pull/2242.

**Comment by Situphen** [comment]
Je n'ai pas ce problème en local. Sur la béta, il manque la version avec hash (https://beta.zestedesavoir.com/static/admin/css/base.c8269a10a4bc.css) mais la version sans hash (https://beta.zestedesavoir.com/static/admin/css/base.css) est bien présente. Les autres modules n'ont pas l'air d'être touchés.

**Comment by SpaceFox** [comment]
J'ai pourtant suivi très scrupuleusement les instructions fournies dans le
update.md lors de la MEP.

**Comment by gustavi** [comment]
@SpaceFox faut vérifier la config de nginx.

**Comment by Eskimon** [comment]
Ca marche ici  ?

**Comment by SpaceFox** [comment]
Oui.
