### ISSUE TITLE
Liens comptes sociaux footer - version mobile

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#2332]
Sur la version mobile du site (_Windows Phone 8.1 - IE_), les liens vers les comptes sociaux de ZdS se superposent aux autres liens, comme le montre la capture suivante : 

![wp_ss_20150213_0002](https://cloud.githubusercontent.com/assets/4312887/6196031/8691a664-b3d4-11e4-85f4-077ce41d00ab.png)

Ce n'est pas une régression, je l'ai depuis la v1.5, mais je pensais que ça avait été corrigé pour la v1.6 !

**Comment by ghost** [comment]
Ce bug est lié à IE (même sur PC). ^^" Je crois qu'il gère mal `flex`, par contre avec IE9 ça fonctionne.

Je la prend.

**Comment by A-312** [comment]
Je la prend.

**Comment by ghost** [comment]
Je ferais la correction lorsque la PR #2263 sera acceptée.

**Comment by firm1** [comment]
Corrigé, merci @A-312
