### ISSUE TITLE
Libellé réduit dans la sidebar des tutoriels

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2335]
Meme problème que la #2304.

En prod : http://zestedesavoir.com/tutoriels/

En beta : http://beta.zestedesavoir.com/tutoriels/

Dans la sidebar on peut apercevoir que le libellé "Catégories de tutoriels" est réduit sur PC.

**Comment by ghost** [comment]
Étrange, la correction de la PR #2312 devrait s'appliquer.

Peut être prendre en compte la remarque de @SpaceFox : 

> Les moteurs de recherche gèrent correctement ce genre de blague ?

https://github.com/zestedesavoir/zds-site/search?l=html&q=class%3D%22wide%22&type=Code&utf8=%E2%9C%93

**Comment by SpaceFox** [comment]
Ouais, j'aimerais bien une réponse à cette question...

**Comment by Eskimon** [comment]
En tout cas ca semble etre corrige (en tout cas je reproduis pas en v1.8).

Reste la question sur le SEO

**Comment by Eskimon** [comment]
Bon, puisque personne ne répond j'ai fait 5 minutes de googling:

Long story short (et de ce que j'en comprends "google le vit bien", le sujet et ses sources sont là : http://stackoverflow.com/questions/11228368/does-breaking-a-word-with-a-span-tag-effect-seo , je ferme ici.
