### ISSUE TITLE
Les titres de MPs sont coupés alors qu'il y'a de la place

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2336]
Scénario : 
- Je crée un tutoriel dont le titre est "Le monde la vie, la france, l'huile le feu et les océans de l'amour valentins"
- Je l'envoi en beta
- Je reçoit un MP dont le titre est "Tutoriel en beta : Le monde la vie, la france, l'huile le feu et les océans de l"

Le MP a donc été coupé à 80 caractères alors que selon la PR #2151 un titre de MP peut avoir 130 caractères

**Comment by GerardPaligot** [comment]
Corrigé. Merci à @firm1 pour le fix et @pierre-24 pour la QA.
