### ISSUE TITLE
Incohérence entre le nombre de notifs affiches et la page "toutes les notifs"

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2346]
Je ne sais plus comment j'en suis arrivé a ce bug mais je me retrouve avec 0 notifs d'après le compteur de notifs en haut. Mais quand je vais voir voir toutes mes notifs je découvre qu'il y'en a une graissée.

![tmp_12976-screenshot_2015-02-16-11-58-28-1169894047](https://cloud.githubusercontent.com/assets/6066015/6211857/cf7701ce-b5de-11e4-9781-45ad30a7c5c2.png)

**Comment by GerardPaligot** [comment]
Par hasard, est-ce que tu auras cliqué sur "Non lu" sur le premier message d'un sujet ?

**Comment by firm1** [comment]
C'est possible, je me souviens plus de tout ce que j'ai fais.

**Comment by GerardPaligot** [comment]
Balancer le bug sans savoir comment le reproduire, c'est pas génial ...

Cela dit, la manipulation que j'indique arrive au même état que le tiens. Cela pourrait donc être un doublon à l'issue https://github.com/zestedesavoir/zds-site/issues/2284.

**Comment by firm1** [comment]
en effet, je viens d'essayer avec la meme manip, on arrive on au meme resultat. Donc ça doit etre un doublon.
