### ISSUE TITLE
Problème de build du front sur debian

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2352]
J'ai essayé de builder le front de zds sur un environnement propre sur une debian 7 64 bits sans succès. Étant donné que c'est quasi la même conf que la produit je me que le problème doit certainement se trouver entre ma chaise et mon clavier.

L'erreur survient pendant le `npm install` et concerne node-gyp

```
pathwatcher.target.mk:90: recipe for target 'Release/obj.target/pathwatcher/src/main.o' failed
make: *** [Release/obj.target/pathwatcher/src/main.o] Error 1
make: Leaving directory '/opt/1/zds-site/node_modules/css-sprite/node_modules/gaze/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node/node-v0.11.16/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 2.6.32-042stab103.6
gyp ERR! command "node" "/usr/local/node/node-v0.11.16/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/1/zds-site/node_modules/css-sprite/node_modules/gaze
gyp ERR! node -v v0.11.16
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
\
```

J'ai pourtant les pré-requis installés (make, GCC 4.7, python2.7.8).

Quelqu'un voit ou est le problème ?

**Comment by Situphen** [comment]
Je sais pas pourquoi ça a buggé. Fait `rm -rI node_modules/`et essaye de réinstaller. Le problème vient peut-être des dépendances qui ne sont pas en strictes. La PR #2353 devrait arranger ça...

**Comment by firm1** [comment]
c'est bizarre quand meme. J'essayerai avec ta branche du coup.

**Comment by firm1** [comment]
Bon, j'ai compris le problème finalement. node-sass n'est supporté que par `node 0.10.x`. Moi j'avais installé la version 0.11.16 et ça ne marchait pas.

Donc information à retenir : ne pas mettre à jour la preprod/prod sur sa version de nodejs. Et du coup, ça me fait penser à cette PR #2351 qu'il faudra tester sur une debian quand même.

Je ferme donc.
