### ISSUE TITLE
Autocomplétion mp validation du formulaire

### ISSUE THREAD

**Issue by poulp** [zestedesavoir/zds-site#2355]
Quand je veux écrire un mp et que j'ajoute un participant via l'auto-complétion, par exemple user, ça me donne `user,` ce qui invalide le formulaire. Il faudrait juste avoir `user`.

**Comment by GerardPaligot** [comment]
Via la bêta ?

**Comment by poulp** [comment]
Oui c'est présent sur la bêta

**Comment by SpaceFox** [comment]
Je ratisse large, il faudra dégager les labels non pertinents.

**Comment by GerardPaligot** [comment]
C'est clairement du front. Le back, plus précisément l'API, ne fait que renvoyer un tableau avec la liste des utilisateurs. Rien de plus.

**Comment by Situphen** [comment]
C'est plutôt au Back de gérer la virgule et l'espace, sinon l'utilisateur ne pourra pas rentrer plusieurs pseudos dans le champ !

**Comment by Eskimon** [comment]
A noter : le comportement de l'autocompletion est le même en prod (ajout de la virgule etou) mais le back se comporte bien, le message est bien envoyé.

**Comment by Eskimon** [comment]
Un `git blame` nous indique que la derniere modification date d'il y a 14 jours par...@poulp !

https://github.com/zestedesavoir/zds-site/blame/dev/zds/mp/forms.py#L79

C'est ce commit qui semble embeter le formulaire : https://github.com/zestedesavoir/zds-site/commit/8be73f7db59b0645087a5a960a572dcdf05d9654 dans cette PR : https://github.com/zestedesavoir/zds-site/pull/2216

**Comment by GerardPaligot** [comment]
![](http://image.noelshack.com/fichiers/2013/30/1374518815-35734259.jpg)

Hum, sorry.

**Comment by Eskimon** [comment]
`git blame`, la commande du petit délateur !

**Comment by poulp** [comment]
Oui effectivement c'est moi qui ai mis en place la contrainte au niveau du formulaire en oubliant de changer le comportement du front

**Comment by Eskimon** [comment]
(J'en profite pour m'excuser éventuellement pour mon comportement (histoire qu'on soit sur la même longueur d'onde), je ne jette pas la pierre, je cherche juste a trouver la solution :) . Que ce soit toi ou un autre qui a introduit le "problème" c'est pas bien grave ^^ . Le reste n'est qu'humour bien entendu).

Le fix sera a faire sur la branche de release.

**Comment by poulp** [comment]
On est sur la même longueur d'onde, pas de soucis ;)

**Comment by SpaceFox** [comment]
Corrigé.
