### ISSUE TITLE
La bêta n'a pas d'IPv6

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2356]
Pour autant que je sache, la bêta ne répond pas en IPv6. Ce qui nous empêche de tester certains points particuliers (notamment avec l'API).

Aux dernières nouvelles, l'IPv6 c'était environ 10% du trafic.

**Comment by Ge0** [comment]
Hello.

Comment on teste l'accès à ZdS en IPV6 ?

**Comment by SpaceFox** [comment]
Pour moi la première chose à faire c'est de vérifier qu'on a bien une entrée IPv6 dans le DNS pour la bêta.

**Comment by gustavi** [comment]
Pour info : 

```
\_o<  host zestedesavoir.com
zestedesavoir.com has address 176.31.187.88
zestedesavoir.com has IPv6 address 2001:41d0:52:100::b4f
zestedesavoir.com mail is handled by 1 vps41247.ovh.net.
zestedesavoir.com mail is handled by 2 redirect.ovh.net.


\_o<  host beta.zestedesavoir.com
beta.zestedesavoir.com has address 46.105.246.77
```

**Comment by SpaceFox** [comment]
En fait la préprod n'a pas d'adresse IPv6 publique, seulement une adresse en `fe80:` qui correspond à une adresse "locale lien".

Je ne sais pas si on peut corriger ça...

**Comment by geoffreyc** [comment]
Yop ! Normalement, beta.zestedesavoir.com est accessible via ipV6 maintenant :)

Tenez moi au courant si il y a un soucis ;)

**Comment by SpaceFox** [comment]
Je confirme que ça marche :)

**Comment by GerardPaligot** [comment]
Du coup, l'issue est close ?

**Comment by SpaceFox** [comment]
Il faut juste vérifier que le throttling fonctionne en IPv6, ce que je n'ai pas eu le temps de tester hier.

**Comment by SpaceFox** [comment]
C'est clos ici, au fait.
