### ISSUE TITLE
Le wiki de github n'est pas à jour

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2359]
Le [wiki du github](https://github.com/zestedesavoir/zds-site/wiki) n'est pas du tout à jours. Il faudrait le mettre à jours car il contient des données érronnées sur l'installation et sur d'autre truc aussi. C'est beaucoup de doublons avec la doc existante.

Je suis pour supprimer la page.

**Comment by Situphen** [comment]
Je plussoie fortement ! @SpaceFox ? @firm1 ?

**Comment by SpaceFox** [comment]
J'avais oublié qu'il existait... je le supprime, oui. Merci.

**Comment by SpaceFox** [comment]
Et voilà !
