### ISSUE TITLE
Soumettre un formulaire avec CMD+Enter

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2363]
Il m'a semblé qu'un jour, il était possible de soumettre un formulaire avec la combinaison CMD+Enter (et non CTRL+Enter qui elle fonctionne).
- Soit c'était possible et nous avons une régression puisque CMD+Enter ne fonctionne plus en production.
- Soit c'était pas possible et cela devient une suggestion. C'est plus agréable pour les utilisateurs OS X.

J'asperge donc les tags et vous rectifiez les devs front.

**Comment by Situphen** [comment]
C'était possible avant que l'on restreigne les touches Alt, Shift et Meta. Or, Meta est apparemment le nom de la touche Command en JavaScript.

Je prend le ticket. Pour moi, c'est une évolution et non pas un bug ! :)

**Comment by GerardPaligot** [comment]
C'est corrigé. Merci @Situphen !
