### ISSUE TITLE
Saut à la ligne avec la soumission par CTRL+Enter

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2364]
Lorsque je veux soumettre un formulaire avec le raccourci CTRL+Enter, mon texte fait un saut à la ligne après la soumission (il n'apparait donc pas dans le message final) mais c'est toujours troublant et à chaque fois, je vérifie que mon texte est bien comme il faut.

Si c'est possible, faudrait éviter cette action après la soumission du formulaire.

Bug disponible en production.

**Comment by Situphen** [comment]
Je prends. Là aussi, je vois plutôt ça comme une évolution.

**Comment by Eskimon** [comment]
Non c'est un bug si la ligne est rajouté sans le consentement de l'auteur.

**Comment by Situphen** [comment]
Je n'ai pas réussi à refaire le bug, cependant je pense que ma PR résoud le problème. @GerardPaligot : tu peux QA ? :)

**Comment by GerardPaligot** [comment]
Je QA ce soir.

**Comment by GerardPaligot** [comment]
C'est corrigé. Merci @Situphen !
