### ISSUE TITLE
L'auto complétion ne fonctionne pas sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2365]
En essayant d'envoyer un MP , je n'ai pas l'auto complétion dans la liste des participants.

Smartphone : One Plus.
Os : Android
Navigateur : Firefox

![tmp_1128-screenshot_2015-02-23-09-52-26526993474](https://cloud.githubusercontent.com/assets/6066015/6325013/0993968e-bb42-11e4-8aa0-1eeffc3a3951.png)

**Comment by Situphen** [comment]
AMHA, c'est plutôt une évolution non ?

**Comment by firm1** [comment]
Bah une incohérence PC vs mobile c'est plus un bug

**Comment by SpaceFox** [comment]
Non, pas forcément.

**Comment by Situphen** [comment]
Je viens de tester quelques manipulations et il s'avère que les événements sur lesquels on se base actuellement (`keyup` et `keydown`) ne sont pas créé quand on est sur un téléphone.

Apparemment, ce serait en partie à cause de suggestion de mot quand l'on tape sur un clavier virtuel comme expliqué en anglais [ici](https://code.google.com/p/chromium/issues/detail?id=118639#c7) :

> For developers, I think it is better to avoid expecting keycode on android.
> The problem is that there are a lot of text suggestion related changes. For example, you type "go", "good" and "gossip"will show up in the text suggestion. The user might click "good" and "gossip" to change the current text input, and it will also clear the composition under "go". If developers are expecting keycode, it is hard to deal with the case above as there is no keycode for user selections.
> 229 is the composition keycode for chrome, it is sent when user either hit a key or hit a selection.

@sandhose, @A-312 : Avez vous une idée pour résoudre ce ticket ? Moi, ça me parait difficile...

**Comment by ghost** [comment]
J'ai regardé sur internet certain parle de l'event `input`.

https://developer.mozilla.org/en-US/docs/Web/Events/input

**Comment by Eskimon** [comment]
Je viens de tester sur mon telephone (OnePlus One Kitkat Chrome) et ca a l'air de fonctionner, je ferme
