### ISSUE TITLE
Doublon dans la sidebar d'édition d'un MP

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2366]
En editant mon MP, j'ai deux fois le lien "Nouvelle conversation" dans la sidebar.

Le screen : 
![inception](https://cloud.githubusercontent.com/assets/6066015/6327811/9eba499c-bb60-11e4-98f0-b79fec9ab49e.PNG)

**Comment by GerardPaligot** [comment]
Corrigé. Merci @Situphen !
