### ISSUE TITLE
Erreur page des paramètres du profil

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#237]
La page des paramètres du profil ne s'affiche pas, une erreur est affichée. J'utilise le lien dans la box qui s'affiche quand on clique sur son avatar dans la barre en haut à droite.

Erreur :
TypeError at /membres/parametres/profil
unsupported operand type(s) for +=: 'NoneType' and 'str'

Lien vers la page en erreur : http://preprod.zestedesavoir.com/membres/parametres/profil

**Comment by firm1** [comment]
La PR précédente fixe le bug, et c'est en prod.

merci, je ferme
