### ISSUE TITLE
Afficher son profil par l'API sans spécifier un identifiant

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2374]
Actuellement, pour récupérer ses informations par l'API, soit l'utilisateur connait son identifiant et il n'y a pas de problèmes, soit il doit d'abord trouver son identifiant dans la liste des membres puis refaire une requête pour récupérer ses informations.

Une évolution intéressante serait de récupérer ses informations par une URL du style `/api/membres/mon_profil/`.

**Comment by SpaceFox** [comment]
Corrigé.
