### ISSUE TITLE
Utiliser le markdown pour éviter de doubler les templates des emails ?

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2377]
Actuellement pour chaque message on a une version html et une autre en texte. C'est assez pénible à maintenir et je pense que l'on pourrait utiliser le markdown pour s'en affranchir ! Le markdown est lisible, donc on pourrait l'utiliser directement pour la version en texte. Vu que l'on peut le transformer en html, on peut l'utiliser pour la version html. Est-ce que ça vous convient ?

**Comment by SpaceFox** [comment]
Je ne pense pas : les mails répondent à des règles très particulières, je ne suis pas sûr du tout qu'un HTML généré sera correct.

**Comment by Situphen** [comment]
A mon avis si l'on utilise juste le markdown pour le gras, les liens et les titres, on en devrait pas avoir trop de problèmes.

**Comment by A-312** [comment]
Dans certain mail, il me semble qu'il y a la formulation du type `cliquez ici` pour un lien, par exemple :  https://github.com/zestedesavoir/zds-site/blob/dev/templates/email/member/confirm_registration.html#L16

**Comment by artragis** [comment]
Je clos le ticket. Il est vraiment nécessaire d'avoir un rendu html + le rendu text en alternative.
