### ISSUE TITLE
Lien d'avatar irrecuperable

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2385]
via l'API on ne peut pas obtenir l'avatar d'un membre dont l'image est servie par gravatar. En effet, le lien gravatar n'est pas donnée et ne peut être déduit après coup car il faut l'email du membre. Il faut donc que l'API serve ce lien tout prêt.

( @SpaceFox je ne sais pas quel milestone mettre. Est-on dans le cadre d'un bug simple ou passons nous cela dans du hotfix ?)

**Comment by GerardPaligot** [comment]
Tu t'es basé sur quoi pour placer le tag "Facile" ? Perso, je n'ai aucune idée de comment générer l'URL de l'avatar gravatar et ce n'est pas si simple de compléter de l'information dans une réponse de l'API (surtout pour des nouveaux devs sur l'API).

**Comment by SpaceFox** [comment]
Ce n'est pas un hotfix, ça ne bloque rien.

**Comment by Eskimon** [comment]
> Tu t'es basé sur quoi pour placer le tag "Facile" ?

Sur mon expérience :) je sais ou trouver et comment générer le lien sans souci :D Pour info, c'est dans le modele `member` ici : https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/models.py#L126

**Comment by Eskimon** [comment]
Bien joué @firm1 !
