### ISSUE TITLE
Revoir la gestion de l'autocomplétion sur le site

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2386]
Actuellement, l’auto complétion sur le site utilise l'API, ce qui est très bien. Le problème c'est que le front-end ne se connecte pas en tant que client de l'API pour pouvoir passer sur un throlling raisonnable.

La conséquence étant donc que l’auto complétion ne marche plus après 60 requêtes à l'API dans l'heure. Le nombre de requête vers l'API évoluant assez vite lors d'une recherche d'un membre (une requête pour chaque caractère saisi) , on atteint rapidement la limite.

Autant le dev saura pourquoi, autant le pur utilisateur ne saura pas d’où vient le problème, et l'assimilera à un bug (qui plus est aléatoire).

La solution propre serait donc que le front s'authentifie à l'API une et une seule fois à l'ouverture du site et par la suite utilise son token pour faire ses requêtes en JS.

**Comment by Situphen** [comment]
Par contre, il a une durée d'expiration le token ? Si non, faut-il lui en mettre une ?

**Comment by GerardPaligot** [comment]
J'ai fais des recherches à ce sujet. Il faudrait tester [SessionAuthentication](http://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication) qui, si je le comprend bien, utilise les sessions Django pour passer l'utilisateur à l'état authentifié auprès de l'API. Cela résoudrait donc le problème exposé ci-présent avec une seule ligne de code à rajouter à la suite de [cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L222) et à tester dans un environnement où le throttling fonctionne.

``` python
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.ext.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
```

> Par contre, il a une durée d'expiration le token ? Si non, faut-il lui en mettre une ?

Pour répondre quand même, le token a une durée d'expiration renseignée quand tu fais la requête pour récupérer les tokens d'authentification. Plus d'information dans la [documentation](http://zds-site.readthedocs.org/fr/v1.6/api.html#authentification).

**Comment by Situphen** [comment]
Je viens de tester l'autocomplétion en appuyant sur toutes les touches pour que mon navigateur envoie plus de 60 requêtes au serveur, sans que je n'ai de 304 et j'ai réussi. L'autocomplétion fonctionne toujours bien après 100 requêtes ! Les logs du serveur sont [ici](http://pastebin.com/Dp5bRttb).

**Comment by GerardPaligot** [comment]
Qu'est-ce que tu as testé @Situphen ? Sur quel serveur ? Un serveur avec un throttling correctement configuré ?

**Comment by Situphen** [comment]
J'ai testé avec le serveur par défaut de Django mais vu ce que tu me demandes, je me pose en effet la question de savoir s'il faut un vrai serveur devant ou pas !

**Comment by GerardPaligot** [comment]
Le problème n'est pas de devoir tester sur une serveur de production ou non. Le problème c'est que je ne sais pas quelles sont les modifications que tu as fais pour que ça fonctionne chez toi en local et si tu as un throttling qui fonctionne à la base ou non. :)

**Comment by Situphen** [comment]
Je n'ai fait aucune modification et je suis à jour avec upstream/dev (le dépôt officiel).

J'ai testé 2000 requêtes et j'ai réussi mais au milieu j'ai coupé sans faire exprès le serveur donc je sais pas si le test reste correct.

**Comment by Situphen** [comment]
Bon, je confirme que le problème a été rencontré en prod

**Comment by Eskimon** [comment]
Ca marche du feu de dieu ton astuce @GerardPaligot !!

**Comment by pierre-24** [comment]
Merci @Eskimon du coup !

**Comment by Eskimon** [comment]
Par contre faut s'assurer qu'on a un ticket sur le souci de copier/coller
