### ISSUE TITLE
[POST ZEP-25] Revoir les limitations sur les titres et les tags

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#2388]
Comme décrit [ici](https://zestedesavoir.com/forums/sujet/2455/un-champ-pour-les-tags/?page=1#p46018), la limitation à 128 caractères entre en conflit avec le fait que les tags sont compris à l'intérieur du titre.

Deux possibilités sont envisageables : 
- externaliser les tags dans un autre champs
- faire en sorte que la vérification de la longeur se fasse _après_ le parsing des tags.

Pour ma part je préfère la deuxième solution. 

Quoi qu'il arrive, vous pouvez m'assigner à cette tâche.

**Comment by Situphen** [comment]
La limitation du titre est à 80 caractères (voir https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/models.py#L132) ! Aussi, il faut penser à changer ça https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/forms.py#L20 car sinon le champ HTML aura toujours un attribut `maxlength` à 80 !

**Comment by artragis** [comment]
Yep, comme je le disais, il y a des choses à déporter.

Soit on crée un nouveau champ pour le form helper qui faire le parsing du tag, soit met la validation dans toutes les actions. Je ne sais pas si le premier est possible mais si c'est le cas il respecte la philosophie DRY.

**Comment by GerardPaligot** [comment]
Alors de tête, il m'a semblé lire les forums le développement d'un champ dédié aux tags et que @gustavi s'en chargait. Tu confirmes ?

**Comment by gustavi** [comment]
Je confirme. Je fais ça post ZEP-25 :)

**Comment by Karnaj** [comment]
Le ticket est à fermer, non ?

**Comment by vhf** [comment]
Nope.

**Comment by GerardPaligot** [comment]
Pourtant, un champ est dédié aux tags maintenant.

**Comment by vhf** [comment]
Ah j'ai raté ça, très bien.

**Comment by vhf** [comment]
Je veux bien que quelqu'un trouve la PR qui fait ça et la lie à ce ticket, ça documenterait le truc.

**Comment by Karnaj** [comment]
C’est #3803 je crois. Et ça permet aussi de fermer #2499 normalement.

**Comment by vhf** [comment]
Bien vu. Impossible à deviner d'après le titre de la PR, merci d'avoir creusé.
