### ISSUE TITLE
Label clci/survol incompréhensible dans les paramètres

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#239]
Dans les paramètres (http://preprod.zestedesavoir.com/membres/parametres/profil), le label de la case à cocher permettant de choisir l'ouverture des menus au survol ou au clic ne veut rien dire : "Dérouler les menus au survol de la souris ou au clic" --> on ne sait pas si cocher = clic ou si cocher = survol.

Il faudrait remplacer le label par quelque chose comme "Activer le déroulement des menus au clic plutôt qu'au survol.".

**Comment by firm1** [comment]
Je me demande même s'il ne faut pas carrément masquer cette option, étant donné que le design n'est pas encore prêt pour ça.

**Comment by ShigeruM** [comment]
Clairement. C'est bien un truc qui peut venir plus tard.

**Comment by firm1** [comment]
ça y est c'est fixé. C'est mergé, c'est en prod.
