### ISSUE TITLE
Les topics ne sont plus épinglés dans la navigation par tag

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2390]
Naviguant via le [tag zep](https://zestedesavoir.com/forums/sujets/tag/51/zep/), on se rend compte que les sujets épinglés ne sont plus en haut de la liste, comme lors de la navigation par forum.

**Comment by SpaceFox** [comment]
Je crois que c'est volontaire.

**Comment by GerardPaligot** [comment]
Ca me ferait bizarre d'épingler les sujets avec la navigation par tag.

**Comment by firm1** [comment]
Si c'est voulu, alors on ferme l'issue
