### ISSUE TITLE
Est-ce qu'on utilise un pool de connexions sur ZdS ?

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2391]
Salut les devs,

J'ai l'impression, au vu des stats Munin, qu'on utilise absolument pas de pooling sur les connexions à la base de données.

Donc, on s'emmerderait à ouvrir une nouvelle connexion à chaque requête... et on a des pages franchement lourdes en requêtes !

Il se trouve qu'il y a [une forme de pooling intégré à Django depuis la v1.6](https://docs.djangoproject.com/en/1.6/ref/databases/#persistent-connections) - mais je ne sais pas ce qu'il vaut.

Je me demande si mettre ceci en place ne résoudrait pas aussi les problèmes de connexion dans Travis.

Quelles sont les "bonnes pratiques" dans ce domaine ?

Qu'en pensez-vous ?

**Comment by firm1** [comment]
On est bien en mode persistent en preprod/prod et le `CONN_MAX_AGE` est fixé à 10 minutes.

En gros toutes les 10 minutes django réinitialise une nouvelle connexion à la base de donnée.

Par contre [ce n'est pas le cas dans travis](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings_test.py)

**Comment by SpaceFox** [comment]
Ce qui m'inquiète alors c'est que ce paramètre [ne soit pas déclaré dans le settings.py](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py)

**Comment by firm1** [comment]
Il est dans la settings_prod (ça fait partie de la conf spécifique de prod), c'est une option du dictionnaire `DATABASES`

**Comment by SpaceFox** [comment]
Il faut vraiment qu'on discute de  ce qui est mis dans ce fichiers settings_prod.py. Pour moi ce n'est pas normal qu'on se retrouve à y mettre des valeurs sans qu'elles soient (au moins avec une valeur par défaut) dans le fichier settings.py.

Pourquoi  ? Parce que du coup les développeurs n'ont pas conscience de l'existence de ces paramètres. Par exemple, tous mes tests sur les gains des améliorations SQL de la v1.6 ont été fait sans ce paramètre. Ils sont donc tous faux...

**Comment by GerardPaligot** [comment]
A mon sens, ce débat aurait sa place dans le prochain Zest'Meeting.

**Comment by firm1** [comment]
> Pourquoi ? Parce que du coup les développeurs n'ont pas conscience de l'existence de ces paramètres. Par exemple

Entièrement d'accord, et en plus il y'a déjà une [issue sur le sujet](https://github.com/zestedesavoir/zds-site/issues/1023)

**Comment by SpaceFox** [comment]
OK, donc :
- Je laisse ouvert ici, parce que j'aimerais bien savoir si on est conformes aux bonnes pratiques en la matière. Entre autres la durée des connexions.
- On parle du settings_prod.py au prochain zest'meeting.

**Comment by artragis** [comment]
COmme on a parlé du settings_prod, on fait quoi du coup?

**Comment by Situphen** [comment]
Up ! Quelqu'un sait "si on est conformes aux bonnes pratiques en la matière. Entre autres la durée des connexions." ?

**Comment by Eskimon** [comment]
Je viens de regarder, en preprod on est a 600. Je trouve ca un peu surprenant car la plupart des trucs que je lis parlait plutot de l'echelle de la minute voire des dizaines de secondes.

Au cas ou, la doc est la : https://docs.djangoproject.com/en/1.7/ref/databases/#persistent-database-connections

**Comment by motet-a** [comment]
C’est toujours d’actualité ?
