### ISSUE TITLE
Les sujets privés ne sont pas si privés que ça

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2392]
Via poliorcetics [sur le forum](http://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=27#p46178), il est possible en tant que membre simple ou invités de voir les titres/sous titre des topics sur la page de profil d'un membre du staff.

ça ressemble à une regression du refactoring des membres

Voir screen : 

![probleme-secu](https://cloud.githubusercontent.com/assets/6066015/6445299/4cd8dce4-c103-11e4-822e-99e7bbf23401.PNG)

**Comment by SpaceFox** [comment]
Je suis presque sûr que c'est une régression aussi.

**Comment by GerardPaligot** [comment]
Chose surprenante puisque la requête pour récupérer cette liste des sujets n'a pas changé.

[Requête sur la version 1.5-RC3](https://github.com/zestedesavoir/zds-site/blob/v1.5-RC3/zds/member/views.py#L253)

[Requête sur la version 1.6](https://github.com/zestedesavoir/zds-site/blob/v1.6/zds/forum/managers.py#L13)

**Comment by firm1** [comment]
@GerardPaligot sur les deux liens que tu montres, on voit bien que la méthode à changé.

Avant on avait 

```
exclude(Q(forum__group__isnull=False) & ~Q(forum__group__in=request.user.groups.all()))
```

Après on a 

```
exclude(Q(forum__group__isnull=False) & ~Q(forum__group__in=author.groups.all()))
```

La regression est bien là

**Comment by GerardPaligot** [comment]
Bien vu, je ne l'avais pas remarqué. Est-ce un hotfix ou une PR pour la release 1.7 ?

**Comment by Eskimon** [comment]
Je dirais hotfix car c'est un bug apparu dans la release

**Comment by SpaceFox** [comment]
+1, et la fuite d'infos privées, c'est pas cool.

**Comment by GerardPaligot** [comment]
Bien, je m'en occupe ce soir alors.

**Comment by SpaceFox** [comment]
@GerardPaligot tu as pu t'en occuper ?

**Comment by GerardPaligot** [comment]
Sorry, j'avais complètement oublié ! Du coup, je l'ai fais maintenant. Sur quelle branche je dois faire ma PR ?

**Comment by SpaceFox** [comment]
`prod`, c'est un hotfix.

**Comment by GerardPaligot** [comment]
PR faite.

**Comment by firm1** [comment]
C'est corrigé, donc c'est fermé. Merci @GerardPaligot
