### ISSUE TITLE
Impossible de modifier le titre/sous-titre d'un MP

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2393]
Actuellement quand on crée un MP, il n'est plus possible de modifier le titre/sous titre de celui-ci.

C'est dommage car j'aimerai pouvoir modifier une faute d'orthographe dans mon MP qui ne fait pas très sérieux du coup.

**Comment by Eskimon** [comment]
A mettre dans la v1.9 (ping @SpaceFox )

**Comment by Eskimon** [comment]
Merci @poulp :)

**Comment by SpaceFox** [comment]
Oups, j'avais oublié de créer la milestone !
