### ISSUE TITLE
Il est possible de créer un topic/mp sans titre apparent

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2394]
Scénario : 
- Allez sur l'url suivante : http://beta.zestedesavoir.com/forums/sujet/nouveau/?forum=16
- Saisir dans la le titre la chaine `$ $`
- Remplir le contenu du message
- Valider

Le topic ressemblera à ça : 

![vide](https://cloud.githubusercontent.com/assets/6066015/6464805/1826eb70-c1bd-11e4-88c3-d30b4da197f8.PNG)

**Comment by GerardPaligot** [comment]
Pourquoi `$ $` ?

**Comment by SpaceFox** [comment]
C'est toujours le même problème du LaTeX dans les titres.

2015-03-03 15:58 GMT+01:00 Gérard Paligot notifications@github.com:

**Comment by Situphen** [comment]
Similaire à #2245 et #1817.
