### ISSUE TITLE
Un membre banni peut encore envoyer des MPs tant qu'il n'est pas déconnecté

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2396]
Lorsqu'on ban un membre, celui-ci n'est pas déconnecté automatiquement, et donc il peut encore faire des choses comme envoyer des MPs à qui il veut.

C'est une regression de la refacto du module des membres, car avant, la session du membre banni était tuée lors du ban.

**Comment by GerardPaligot** [comment]
> C'est une regression de la refacto du module des membres, car avant, la session du membre banni était tuée lors du ban.

Qu'est ce qui faisait ça ?

**Comment by SpaceFox** [comment]
Aucune idée, mais je suis pratiquement certain d'avoir testé cette fonctionnalité. Note le "pratiquement" :)

**Comment by firm1** [comment]
> Qu'est ce qui faisait ça ?

Il me semble qu'on capturait la session du membre à bannir, et on la killait. Ce qui fait que l'utilisateur était déconnecté automatiquement. ça devrait pouvoir être fait facilement en remontant dans l'historique de modification.

**Comment by GerardPaligot** [comment]
Si c'était bien [cette ligne ci](https://github.com/zestedesavoir/zds-site/blob/v1.5-RC3/zds/member/views.py#L331) qui faisait la déconnexion. Elle le fait toujours via [cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/commons.py#L381) où `profile` est bien l'[utilisateur à bannir](https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/views.py#L358).

Es-tu bien sûr du bug ?

**Comment by firm1** [comment]
> Es-tu bien sûr du bug ?

Oui je suis sur du bug

**Comment by Eskimon** [comment]
Je confirme aussi la présence du problème sur ma branche de dev. et je viens de balancer un fix :)

**Comment by pierre-24** [comment]
Et c'est corrigé et mergé !
