### ISSUE TITLE
Doublon de vues dans l'édition d'un MP

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2397]
Pendant mon refactoring dans le module des MPs, je suis tombé sur deux méthodes dans les vues : [edit](https://github.com/zestedesavoir/zds-site/blob/dev/zds/mp/views.py#L249) et [add_participant](https://github.com/zestedesavoir/zds-site/blob/dev/zds/mp/views.py#L524).

J'aimerais que quelqu'un me confirme (ou m'infirme), que ce sont bien deux implémentations différentes pour la même fonctionnalité.

**Comment by Situphen** [comment]
Je confirme ! D'ailleurs, la vue "edit" n'est même pas utilisée dans les templates...

**Comment by GerardPaligot** [comment]
Merci de confirmer ma conclusion. Je vais fusionner les deux.

Je ferme.

**Comment by Situphen** [comment]
N'oublie pas de fusionner aussi les tests ! ;)

**Comment by GerardPaligot** [comment]
`add_participant` n'est qu'une version plus complexe de `edit`. Du coup, la fusion est simple. :)
