### ISSUE TITLE
Envoi d'un message sur une page qui n'est pas la dernière

### ISSUE THREAD

**Issue by Deuchnord** [zestedesavoir/zds-site#2399]
Je ne sais pas si je suis le seul, mais personnellement j'ai souvent tendance à ne pas voir qu'il y a une nouvelle page qui est apparue sur un sujet de forum, ce qui fait que je commente souvent sans avoir vu les tous derniers messages en date. Assez embêtant, car il m'est déjà arrivé de me retrouver en total HS à cause de ça…

Le plus simple serait peut-être d'afficher une petite alerte au-dessus de la zone de saisie pour signaler l'existence de pages après celle sur laquelle on se trouve…

**Comment by Axylium** [comment]
C'est vrai, que ça pourrait être pas mal ! Ça permettrait d'éviter pas mal de confusions !

**Comment by GerardPaligot** [comment]
L'évolution est sympa et simple. Nous avons toutes les infos avec la pagination, il suffit d'afficher le message si on est pas à la dernière page. Je tag facile pour des potentiels nouveaux contributeurs. ;)

**Comment by pierre-24** [comment]
Voilà qui est fait :)
