### ISSUE TITLE
Chapter matching query does not exist

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#24]
Salut,

J'ai testé l'import de tutoriels en local et sur le serveur de développement, j'obtiens toujours une erreur. J'ai bien essayé de regarder le code pour l'import d'un tuto mais elle semble vraiment complexe. :)

J'obtiens l'erreur suivante :

```
DoesNotExist at /tutoriels/importer/
Chapter matching query does not exist.
```

Quelqu'un à une idée ?

**Comment by cgabard** [comment]
L'import de .tuto n'est pas encore complet du tout. Une préversion a été mise en place par @dralliw mais c'est que pour les tests rapides il me semble.

**Comment by GerardPaligot** [comment]
Ca n'empêche pas de débugger ou de comprendre les erreurs de la version actuelle. :)

**Comment by cgabard** [comment]
En fait cette version est aussi en stand-by. Tant que le langage markdown utilisé n'est pas fini, et donc la conversion markdown -> html, on ne peut finir le convertisseur zcode -> markdown.

Après je ne l'ai pas utilisé donc je ne te dirais pas plus.

**Comment by cgabard** [comment]
Bonne chance du coup :)

**Comment by firm1** [comment]
Je confirme, le module d'import n'est pas finalisé, et la raison c'est que la gestion des tuto est clairement la partie la plus complexe du site avec l'intégration du versionning.
Là logique dans le code y est, mais c'est encore instable. Par exemple le prochain commit que je ferai rajoutera des champs dans les tables, etc. Donc tout ce que tu peux faire, c'est de lire et comprendre ou encore essayer de resoudre des micro parties indépendantes comme finir la fonction "tuto_to_markdown"

**Comment by firm1** [comment]
Mon commit du matin a résolu ce bug pour les mini-tuto et donc on a une base stable de ce coté là.

Mon commit de demain corrigera le bug des big-tutos

**Comment by firm1** [comment]
Bug résolu. On peut désormais suivre le process de création d'un tuto jusqu’à sa publication.
