### ISSUE TITLE
Erreur lors de l'accès à la page des paramètres

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#240]
Lorsque je vais sur http://preprod.zestedesavoir.com/membres/parametres/profil j'ai une erreur : 

TypeError at /membres/parametres/profil
unsupported operand type(s) for +=: 'NoneType' and 'str'
Request Method: GET
Request URL:    http://178.32.53.245:8001/membres/parametres/profil
Django Version: 1.5.5
Exception Type: TypeError
Exception Value:  
unsupported operand type(s) for +=: 'NoneType' and 'str'
Exception Location: /opt/zdsenv/ZesteDeSavoir/zds/member/forms.py in **init**, line 200

**Comment by firm1** [comment]
Humm.

Il s'agit de la [même issue qu'a reportée ShigeruM hier](https://github.com/Taluu/ZesteDeSavoir/issues/237), et elle a pourtant été fixée. Je me demande si tu ne la pas testée pendant que je bidouillais le serveur.

Peux-tu refaire un essai ?

**Comment by devock** [comment]
En effet, j'ai du aller sur ZdS au mauvais moment, du coup, l'issue n'a plus lieu d'être.
