### ISSUE TITLE
Cesser de faire réindexer toujours la même chose à Solr

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2402]
Aujourd'hui, toutes les demi-heures, on réindexe l'intégralité du contenu de ZdS.
Autant dire que ça ne va pas pouvoir durer bien longtemps, parce que c'est de plus en plus long.

L'idée est de trouver une combine pour indexer fréquemment le _nouveau_ contenu (pourquoi pas carrément à sa publication, si c'est faisable).

On peut imaginer de réinitialiser l'index de façon propre (c'est de toute manière recommandé) de temps en temps, toutes les nuits ou toutes les semaines par exemple.

**Comment by firm1** [comment]
On a une idée de la consommation de la réindexation actuellement sur la prod ?

**Comment by SpaceFox** [comment]
Beaucoup trop. Genre, un cœur à 100% pendant plus de 5 minutes toutes les demi-heures... sans tenir compte des requêtes débiles que ça provoque, du genre "va lire toute la base" puis "va lire tous les tutos publiés".

**Comment by gustavi** [comment]
Mergé. Merci @SpaceFox.

**Comment by SpaceFox** [comment]
Je me permet de réouvrir parce que la solution est partielle (même si elle nous laisse pas mal d'air), il faudrait trouver :
1. Un moyen d'indexer delta les contenus (difficile)
2. De reset l'index de temps en temps (bonnes pratiques Solr)

**Comment by gllmc** [comment]
Je pense qu'on peut fermer cette issue maintenant que #4096 est mergée. :)

**Comment by pierre-24** [comment]
Anéfé :)
