### ISSUE TITLE
Incohérence entre les +1/-1 en mode invité et en mode connecté.

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2403]
Quand on est en mode invité et que le message a reçu plus de positifs que de négatifs, on se retrouve avec le pouce coloré. Chose que l'on a pas lorsque l'on est connecté et que l'on a pas voté.

Le gras sur le pouce est censé dire qu'on a voté pour le message. Ça n'a donc pas de sens de l'avoir quand on est en mode invité.

Screen : mode connecté (pas voté)

![tmp_21435-screenshot_2015-03-05-23-52-18-491051963](https://cloud.githubusercontent.com/assets/6066015/6516570/5c958456-c393-11e4-9c30-8f005ea18292.png)

Screen : mode invité

![tmp_21435-screenshot_2015-03-05-23-53-331314296605](https://cloud.githubusercontent.com/assets/6066015/6516578/711be618-c393-11e4-9318-0d4ee0bd1c94.png)

**Comment by Situphen** [comment]
Doublon de #1683 ?

**Comment by Eskimon** [comment]
merci @poulp :)
