### ISSUE TITLE
Libellé incomplet dans la sidebar sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2404]
Firefox/Android/One Plus.

Voir Screen.

![tmp_21435-6 mars 2015 002512 cet1913268008](https://cloud.githubusercontent.com/assets/6066015/6517045/7876b574-c397-11e4-9542-0c7e24cdc3ff.jpg)

**Comment by Situphen** [comment]
Doublon de #1683 ?

**Comment by Eskimon** [comment]
Yep doublon
