### ISSUE TITLE
Erreur 500 sur un tutoriel (en validation)

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2405]
Dans l'espace de validation des tutoriels, ce [tutoriel](https://zestedesavoir.com/tutoriels/off/625/le-developpement-durable-en-entreprise-la-rse/?version=60daa67e3336c3003080e4b6e2f74008da01243d) provoque une erreur 500 lorsqu'on veut y accéder.

Ping @SpaceFox pour connaitre l'erreur via Sentry.

**Comment by SpaceFox** [comment]
> **BadObject** Root Cause
> BadObject: 60daa67e3336c3003080e4b6e2f74008da01243d

```
Stacktrace (appel le plus récent en dernier) : 

  File "django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "zds/tutorial/views.py", line 827, in view_tutorial
    manifest = get_blob(repo.commit(sha).tree, "manifest.json")
  File "git/repo/base.py", line 410, in commit
    return self.rev_parse(text_type(rev) + "^0")
  File "git/repo/fun.py", line 184, in rev_parse
    obj = name_to_object(repo, rev[:start])
  File "git/repo/fun.py", line 119, in name_to_object
    return Object.new_from_sha(repo, hex_to_bin(hexsha))
  File "git/objects/base.py", line 65, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "gitdb/db/base.py", line 205, in info
    return self._db_query(sha).info(sha)
  File "gitdb/db/base.py", line 192, in _db_query
    raise BadObject(sha)
```

Bizarre...

**Comment by DevHugo** [comment]
Si on demmande gentillement à l'auteur, on pourrait avoir le .git, tu pense ?

**Comment by GerardPaligot** [comment]
Le bug est bizarre.

Le tutoriel est accessible via ce [lien](https://zestedesavoir.com/tutoriels/off/625/le-developpement-durable-en-entreprise-la-rse/) mais il est vide tout autant que son historique.

ping @artragis pour savoir ce qu'ils ont fais.

**Comment by artragis** [comment]
En fait, le tuto **est** vide.
je l'avais mis en validation en y mettant une fausse version et il 
m'affichait "une autre version de ce tutoriel est en validation". En 
local, cela créait des problèmes côté validateur quand il voulait 
afficher un tuto, mais comme je ne suis pas validateur sur le site en 
prod, je n'ai même pas pu tester et pour éviter qu'ils ne se retrouvent 
avec un truc qui les envoient sur une 500, j'ai remis en "validation" 
avec la bonne version mais j'ai oublié de leur dire de refuser la 
validation dare dare.

**Comment by artragis** [comment]
reporté sur #2400

**Comment by GerardPaligot** [comment]
Du coup, cette issue peut être fermée ?

**Comment by artragis** [comment]
Eh bien soit celle-ci soit #2400 puisqu'elles ont trait au même bug.
Celle-ci a le bon goût d'avoir un traceback de la part de munin, donc je
pense que c'est plutôt la #2400 qu'il faut fermer et donne comme doublon de
#2405.

2015-03-13 9:26 GMT+01:00 Gérard Paligot notifications@github.com:

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

@artragis tu peux relire et fermer si besoin le ticket sus-mentionnée ?

**Comment by artragis** [comment]
Ce soir

**Comment by Eskimon** [comment]
Du nouveau @artragis ?

**Comment by artragis** [comment]
#oups.

2015-04-21 14:01 GMT+02:00 Eskimon notifications@github.com:

**Comment by artragis** [comment]
Ah, oui ,je me souviens de cette erreur. Déjà corrigée et QAtisée, faut juste que je mette un TU pour éviter les régressions dans le futur.

**Comment by artragis** [comment]
dans la zep 12 cette issue est QAtisée et a son TU. tu peux ajouter le tag ZEP12.
