### ISSUE TITLE
Les catégories d'article renvoient vers les tutos

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2407]
Sur la page de listing des articles (https://zestedesavoir.com/articles/) on a une jolie collection de catégories. Qui renvoient toutes vers les catégories des _tutos_.

C'est là qu'on voit que cette fonctionnalité a l'air très utilisée.

Je ne sais pas si c'est un bug ou une régression de la v1.6.

**Comment by firm1** [comment]
[Déjà signalé](https://github.com/zestedesavoir/zds-site/issues/2134#issuecomment-74095406)

**Comment by SpaceFox** [comment]
Je garde cette issue parce qu'elle décrit directement le problème alors, c'est bien plus clair que l'autre.

**Comment by GerardPaligot** [comment]
Merci @DevHugo, je ferme.
