### ISSUE TITLE
Accès à une galerie dont on n'est pas proprio

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#241]
Il y a plusieurs bugs concernant les droits d'accès aux galeries : 
- Quand j'essaye d'accéder à une galerie qui n'est pas la mienne (http://preprod.zestedesavoir.com/galerie/32/3d-temps-reel-avec-irrlicht par exemple), j'obtiens une erreur 404 au lieu d'une 403.
- Je peux accéder à la page d'ajout d'une image dans une galerie, galerie dont je ne suis pas le proprio, exemple http://preprod.zestedesavoir.com/galerie/image/ajouter/32 (suffit de changer l'ID pour tester). Par contre, quand on remplie le formulaire d'ajout et qu'on le valide, on a une erreur 404, au lieu d'une 403.

**Comment by firm1** [comment]
Fixé, je ferme
