### ISSUE TITLE
Tox ne gère pas correctement les BDD pour les tests

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2410]
Théoriquement, présente 2 moyens de lancer les tests back :
- `tox -e back` : test du back end sur sqlite (la commande prend en compte flake)
- `tox -e back_mysql` : test du back end sur mysql (pour travis)

Or, Tox ne gère pas correctement les données de connexion : il utilise celles présentes dans le `settings.py` et l'éventuel `settings_prod.py`.

Conséquences :
1. Si en dev j'ai une BDD MySQL, je ne peux plus lancer `tox -e back` pour vérifier que ça passera bien avec SQLite : Tox va essayer de lancer les tests sur MySQL (puisque c'est la base déclarée dans les settings) **sans** installer la dépendance à MySQL. Donc ça va planter sur une dépendance MySQL manquante.
2. Je ne sais pas comment la commande `tox -e back_mysql` détermine la BDD à utiliser, mais c'est foireux :
   - Si je n'ai aucun paramètre de base défini, j'obtiens des erreurs délirantes et irreproductibles par ailleurs dans ma BDD. [Exemple](https://github.com/zestedesavoir/zds-site/pull/1905#issuecomment-77751657). Pourquoi ? Parce qu'alors **tox utilise SQLite !**. Je ne sais même pas où il crée sa BDD de test...
   - Si j'ai une BDD MySQL déclarée, tout passe crème. Avec la base `toto` il crée et utilise la base `test_toto`, comme prévu.
3. Tox garde des informations dans son cache / dossier de travail. Du coup, un même test lancé 2x de suite peut produire des résultats différents ! (non reproduction du point 2 par exemple).

**Conséquences pour le projet :**
1. Depuis qu'on a Tox sur Travis, ce dernier teste avec SQLite et non MySQL !
2. On obtient des [faux positifs](https://github.com/zestedesavoir/zds-site/pull/1905#issuecomment-77751657) sur certaines PR.

Comment reproduire :
1. Récupérer la branche de dev et une BDD MySQL. Lancez le projet sous MySQL et vérifier que tout tourne.
2. Avant chaque test, **supprimez le dossier .tox s'il existe** pour éviter l'effet du point 3.
3. Vérification que le système utilise un SQLite systématiquement :
   1. Arrêtez votre serveur MySQL et vérifier qu'il ne tourne plus
   2. Vérifiez qu'il n'y a aucune autre conf d'accès à la BDD que la conf standard dans votre `settings.py` **et** votre éventuel `settings_prod.py`
   3. Lancez `tox -e back` et vérifiez que ça marche
   4. Lancez `tox -e back_mysql` et vérifiez que contre toute logique, ça marche quand même
4. Vérification que le système utilise la conf des settings systématiquement :
   1. Ajoutez la conf d'accès à votre `settings.py` ou `settings_prod.py`
   2. Toujours serveur MySQL arrêté, lancez `tox -e back` et vérifiez que le système plante parce qu'il essaie d'utiliser MySQL alors que la dépendance n'est pas installée
   3. Lancez votre serveur MySQL. En supposant que votre base s'appelle `zdsdb`, vérifiez la présence de `zdsdb`. Lancez `tox -e back_mysql` et _pendant que le test tourne_, vérifiez que la base `tests_zdsdb` a été créée et est utilisée.

Devant l'importance de l'impact de ce problème, j'hésite presque à le passer en bloquant.

**Comment by SpaceFox** [comment]
PS : Je me demande aussi si ce n'est pas la source des erreurs "MySQL has gone away" : parce que du coup MySQL ne reçoit aucune requête...

**Comment by firm1** [comment]
Je pense que cette issue n'a plus lieu d’être étant donné qu'on a pu voir en creusant le sujet et en Zest'Meeting que le problème ne vient pas de tox.

Les problèmes de cette issue n'arrivent que dans le cadre de la PR de passage à [django 1.7](https://github.com/zestedesavoir/zds-site/issues/1905) le reste du projet fonctionnant toujours bien, la conclusion évidente me parait être que le problème vient de la PR.

Donc on peut fermer ici, et ne conserver que la #2247 qui se charge de documenter tox ?

**Comment by SpaceFox** [comment]
> Les problèmes de cette issue n'arrivent que dans le cadre de la PR de passage à django 1.7 le reste du projet fonctionnant toujours bien, la conclusion évidente me parait être que le problème vient de la PR.

Tu devrais lire la PR en question : le problème vient au moins en partie du couple Tox + Travis... c'est expliqué dans la PR. Je l'explique partout et je ne sais pas comment te le faire comprendre. Et ce bout de dialogue de sourds commence à m'épuiser.

**Comment by firm1** [comment]
Je récapitule pour être sur : 
- Tox permet d'encapsuler un workflow de test. Aujourd'hui nous en avons 3 (back, back_mysql, front)
- Encapsuler signifie qu'il charge les dépendances spécifiques à chaque workflow et lance tests (d'ailleurs il reprend les commandes `python manage.py test blabla` )
- C'est grâce à ce principe qu'on peut paralléliser dans travis sans tout charger à chaque fois (et donc qu'on gagne du temps).
- Tout ce qui précède marche bien avec Django 1.6 et le reste de la stack
- Avec la PR de django 1.7 on a deux soucis : un pb de lancement des tests sous Mysql et l'autre d'app unique (appelons ceci le problème X)
- Le problème est difficile a debugguer car il n'est pas reproductible en local (appelons ceci le problème Y)
- le problème Y est l'objet de cette issue
- Cependant on a remarqué que tox gère les bases de données quand elles sont surchargées comme il faut (settings_prod.py), et que travis utilise bien mysql et non SQlite comme on le voudrait.
- Étant donné que le problème X n'apparait que sur une PR, le travail doit être fait sur la PR en question, et pas sur tox.
- Quant au problème Y, les dernières infos tendent à montrer qu'il y'a un problème dans la conf de travis liée à django 1.7, à voir aussi, mais toujours sur la PR en question.

J'ai bon ?

**Comment by Eskimon** [comment]
Du coup ca en est ou ici ?

**Comment by firm1** [comment]
PR en cours, need QA

**Comment by Eskimon** [comment]
Doc mergee. A completer en cas de souci.
