### ISSUE TITLE
MathJaX est cassé sur dev ?

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2419]
Je ne sais pas si c'est juste moi ou si c'est vraiment un bug, mais quand même. Quand j'emplois le code suivant : `Avec $U$ le potentiel, défini par $\sum_i K\,(\theta-\theta_i)$.`, j'obtiens ceci:

![screenshot from 2015-03-11 21 12 21](https://cloud.githubusercontent.com/assets/7889675/6610288/8f97f092-c833-11e4-9b41-2a2e98009551.png)

Autrement dit, le code _inline_ est intérpreté comme du code _block_ et c'est moche. Très moche.

Alors j'ai essayé deux navigateurs (chrome et firefox), vérifié la console de chacun des deux, rien, et rien de neuf coté mathjax qui justifierai ça. Par contre, ça marche en prod, mais pas quand je charge la branche de _prod_ en local. J'ai bien fait `npm run gulp -- build` entre les coups, bien entendu.

Bref, soit c'est moi, soit c'est un bug. Quelqu'un saurait confirmer ?

**Comment by Eskimon** [comment]
@cgabard ca viendrait pas plutot du markdown ? Un piti bug qui se serait glissé dans les corrections récentes ?

**Comment by pierre-24** [comment]
Possible aussi. Est ce que quelqu'un d'autre confirme le bug, au fait (sur _dev_, donc, pas besoin d'une branche particulière).

**Comment by DevHugo** [comment]
J'ai la même chose mais je suis pas sur que mon installation soit bonne.

**Comment by cgabard** [comment]
quelqu'un pourrait me coller ici le html du code qui pose problème ?

**Comment by DevHugo** [comment]
<p>Avec</p>

<div class="mathjax-wrapper">
<mathjax>
    <span style="color: inherit;" class="MathJax_Preview"></span>
    <span style="" id="MathJax-Element-1-Frame" class="MathJax">
        <nobr>
            <span style="width: 0.891em; display: inline-block;" role="math" id="MathJax-Span-1" class="math">
                <span style="display: inline-block; position: relative; width: 0.767em; height: 0px; font-size: 113%;">
                    <span style="position: absolute; clip: rect(3.133em, 1000em, 4.17em, -1000em); top: -3.982em; left: 0em;">
                        <span id="MathJax-Span-2" class="mrow">
                            <span style="font-family: MathJax_Math; font-style: italic;" id="MathJax-Span-3" class="mi">
                                U
                                <span style="display: inline-block; overflow: hidden; height: 1px; width: 0.084em;">
                                </span>
                            </span>
                        </span>
                        <span style="display: inline-block; width: 0px; height: 3.982em;"></span>
                    </span>
                </span>
                <span style="border-left: 0em solid; display: inline-block; overflow: hidden; width: 0px; height: 0.922em; vertical-align: -0.087em;"></span>
            </span>
        </nobr>
    </span>
    <script id="MathJax-Element-1" type="math/tex">U</script>
</mathjax>
</div> le potentiel, défini par <div class="mathjax-wrapper">
<mathjax>
    <span style="color: inherit;" class="MathJax_Preview"></span>
    <span style="" id="MathJax-Element-2-Frame" class="MathJax">
        <nobr>
            <span style="width: 6.641em; display: inline-block;" role="math" id="MathJax-Span-4" class="math">
                <span style="display: inline-block; position: relative; width: 5.855em; height: 0px; font-size: 113%;">
                    <span style="position: absolute; clip: rect(3.066em, 1000em, 4.441em, -1000em); top: -3.982em; left: 0em;">
                        <span id="MathJax-Span-5" class="mrow">
                            <span id="MathJax-Span-6" class="munderover">
                                <span style="display: inline-block; position: relative; width: 1.375em; height: 0px;">
                                    <span style="position: absolute; clip: rect(3.066em, 1000em, 4.398em, -1000em); top: -3.982em; left: 0em;">
                                        <span style="font-family: MathJax_Size1; vertical-align: 0em;"
                                              id="MathJax-Span-7" class="mo">∑
                                        </span>
                                        <span style="display: inline-block; width: 0px; height: 3.982em;"></span>
                                    </span>
                                    <span style="position: absolute; top: -3.697em; left: 1.056em;">
                                        <span style="font-size: 70.7%; font-family: MathJax_Math; font-style: italic;"
                                              id="MathJax-Span-8" class="mi">i
                                        </span>
                                        <span style="display: inline-block; width: 0px; height: 3.982em;"></span>
                                    </span>
                                </span>
                            </span>
                            <span style="font-family: MathJax_Math; font-style: italic; padding-left: 0.167em;"
                                  id="MathJax-Span-9" class="mi">K
                                <span style="display: inline-block; overflow: hidden; height: 1px; width: 0.04em;"></span>
                            </span>
                            <span style="height: 0em; vertical-align: 0em; width: 0.167em; display: inline-block; overflow: hidden;"
                                  id="MathJax-Span-10" class="mspace"></span>
                            <span style="font-family: MathJax_Main;" id="MathJax-Span-11" class="mo">(</span>
                            <span style="font-family: MathJax_Math; font-style: italic;" id="MathJax-Span-12"
                                  class="mi">θ
                            </span>
                            <span style="font-family: MathJax_Main; padding-left: 0.222em;" id="MathJax-Span-13"
                                  class="mo">−
                            </span>
                            <span style="padding-left: 0.222em;" id="MathJax-Span-14" class="msubsup">
                                <span style="display: inline-block; position: relative; width: 0.788em; height: 0px;">
                                    <span style="position: absolute; clip: rect(3.111em, 1000em, 4.158em, -1000em); top: -3.982em; left: 0em;">
                                        <span style="font-family: MathJax_Math; font-style: italic;"
                                              id="MathJax-Span-15" class="mi">θ
                                        </span>
                                        <span style="display: inline-block; width: 0px; height: 3.982em;"></span>
                                    </span>
                                    <span style="position: absolute; top: -3.832em; left: 0.469em;">
                                        <span style="font-size: 70.7%; font-family: MathJax_Math; font-style: italic;"
                                              id="MathJax-Span-16" class="mi">i
                                        </span>
                                        <span style="display: inline-block; width: 0px; height: 3.982em;"></span>
                                    </span>
                                </span>
                            </span>
                            <span style="font-family: MathJax_Main;" id="MathJax-Span-17" class="mo">)</span>
                        </span>
                        <span style="display: inline-block; width: 0px; height: 3.982em;">
                        </span>
                    </span>
                </span>
                <span style="border-left: 0em solid; display: inline-block; overflow: hidden; width: 0px; height: 1.304em; vertical-align: -0.394em;"></span>
            </span>
        </nobr>
    </span>
    <script id="MathJax-Element-2" type="math/tex">\sum_i K\,(\theta-\theta_i)</script>
</mathjax>
</div>

---

`````` html
<p>Avec</p>
<div class="mathjax-wrapper">
<mathjax>
    <span style="color: inherit;" class="MathJax_Preview"></span>
    <span style="" id="MathJax-Element-1-Frame" class="MathJax">
        <nobr>
            <span style="width: 0.891em; display: inline-block;" role="math" id="MathJax-Span-1" class="math">
                <span style="display: inline-block; position: relative; width: 0.767em; height: 0px; font-size: 113%;">
                    <span style="position: absolute; clip: rect(3.133em, 1000em, 4.17em, -1000em); top: -3.982em; left: 0em;">
                        <span id="MathJax-Span-2" class="mrow">
                            <span style="font-family: MathJax_Math; font-style: italic;" id="MathJax-Span-3" class="mi">
                                U
                                <span style="display: inline-block; overflow: hidden; height: 1px; width: 0.084em;">

                                </span>
                            </span>
                        </span>
                        <span style="display: inline-block; width: 0px; height: 3.982em;"></span>
                    </span>
                </span>
                <span style="border-left: 0em solid; display: inline-block; overflow: hidden; width: 0px; height: 0.922em; vertical-align: -0.087em;"></span>
            </span>
        </nobr>
    </span>
    <script id="MathJax-Element-1" type="math/tex">U</script>
</mathjax>
</div> le potentiel, défini par <div class="mathjax-wrapper">
<mathjax>
    <span style="color: inherit;" class="MathJax_Preview"></span>
    <span style="" id="MathJax-Element-2-Frame" class="MathJax">
        <nobr>
            <span style="width: 6.641em; display: inline-block;" role="math" id="MathJax-Span-4" class="math">
                <span style="display: inline-block; position: relative; width: 5.855em; height: 0px; font-size: 113%;">
                    <span style="position: absolute; clip: rect(3.066em, 1000em, 4.441em, -1000em); top: -3.982em; left: 0em;">
                        <span id="MathJax-Span-5" class="mrow">
                            <span id="MathJax-Span-6" class="munderover">
                                <span style="display: inline-block; position: relative; width: 1.375em; height: 0px;">
                                    <span style="position: absolute; clip: rect(3.066em, 1000em, 4.398em, -1000em); top: -3.982em; left: 0em;">
                                        <span style="font-family: MathJax_Size1; vertical-align: 0em;"
                                              id="MathJax-Span-7" class="mo">∑
                                        </span>
                                        <span style="display: inline-block; width: 0px; height: 3.982em;"></span>
                                    </span>
                                    <span style="position: absolute; top: -3.697em; left: 1.056em;">
                                        <span style="font-size: 70.7%; font-family: MathJax_Math; font-style: italic;"
                                              id="MathJax-Span-8" class="mi">i
                                        </span>
                                        <span style="display: inline-block; width: 0px; height: 3.982em;"></span>
                                    </span>
                                </span>
                            </span>
                            <span style="font-family: MathJax_Math; font-style: italic; padding-left: 0.167em;"
                                  id="MathJax-Span-9" class="mi">K
                                <span style="display: inline-block; overflow: hidden; height: 1px; width: 0.04em;"></span>
                            </span>
                            <span style="height: 0em; vertical-align: 0em; width: 0.167em; display: inline-block; overflow: hidden;"
                                  id="MathJax-Span-10" class="mspace"></span>
                            <span style="font-family: MathJax_Main;" id="MathJax-Span-11" class="mo">(</span>
                            <span style="font-family: MathJax_Math; font-style: italic;" id="MathJax-Span-12"
                                  class="mi">θ
                            </span>
                            <span style="font-family: MathJax_Main; padding-left: 0.222em;" id="MathJax-Span-13"
                                  class="mo">−
                            </span>
                            <span style="padding-left: 0.222em;" id="MathJax-Span-14" class="msubsup">
                                <span style="display: inline-block; position: relative; width: 0.788em; height: 0px;">
                                    <span style="position: absolute; clip: rect(3.111em, 1000em, 4.158em, -1000em); top: -3.982em; left: 0em;">
                                        <span style="font-family: MathJax_Math; font-style: italic;"
                                              id="MathJax-Span-15" class="mi">θ
                                        </span>
                                        <span style="display: inline-block; width: 0px; height: 3.982em;"></span>
                                    </span>
                                    <span style="position: absolute; top: -3.832em; left: 0.469em;">
                                        <span style="font-size: 70.7%; font-family: MathJax_Math; font-style: italic;"
                                              id="MathJax-Span-16" class="mi">i
                                        </span>
                                        <span style="display: inline-block; width: 0px; height: 3.982em;"></span>
                                    </span>
                                </span>
                            </span>
                            <span style="font-family: MathJax_Main;" id="MathJax-Span-17" class="mo">)</span>
                        </span>
                        <span style="display: inline-block; width: 0px; height: 3.982em;">

                        </span>
                    </span>
                </span>
                <span style="border-left: 0em solid; display: inline-block; overflow: hidden; width: 0px; height: 1.304em; vertical-align: -0.394em;"></span>
            </span>
        </nobr>
    </span>
    <script id="MathJax-Element-2" type="math/tex">\sum_i K\,(\theta-\theta_i)</script>
</mathjax>
</div>```
``````

**Comment by cgabard** [comment]
Tu n'aurai pas, par hasard, utilisé l'inspection plutôt que les sources ?
Car c'est vraiment les sources HTML brut avant le passage du JS qu'il faut
vérifier

Christophe

**Comment by DevHugo** [comment]
ah ok excuse, j'avais compris ce que tu voulais.

**Comment by firm1** [comment]
Est-ce que ce bug ne devrait pas passer bloquant pour la release 1.7 ? Car je viens de l'essayer sur la beta, et comme le dis @pierre-24 c'est moche.

Si on pouvait hotfix ça, ça serait top.

**Comment by pierre-24** [comment]
Ah. Je me disais aussi que j'avais pas rêvé. Sauf que le problème est peut-être bien coté markdown et pas coté back/front. @cgabard , un avis là dessus ?

(sinon, du coup, oui pour qu'il passe en bloquant !!)

**Comment by cgabard** [comment]
pfff. Bon bin je vais aller directement voir sur la beta pour essayer de vous donner mon avis sur la question.

**Comment by cgabard** [comment]
Ok oui je pense que ça vient du markdown, je vais faire un hotfix

**Comment by cgabard** [comment]
hotfix un peu à l'arrache car ça va pas etre facile ce WE de m'en occuper

**Comment by Eskimon** [comment]
On peut fermer ici non ?

**Comment by pierre-24** [comment]
Absolument d'accord.
