### ISSUE TITLE
Impossible de créer un MP 

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#242]
Il est impossible de créer un mp quand on passe par la boite de réception, par contre si la variable username est passé en paramètre dans l'url, on peut envoyer un nouveau mp 

L'erreur est : 

UnboundLocalError at /mp/nouveau
local variable 'dest' referenced before assignment
Request Method: GET
Request URL:    http://178.32.53.245:8001/mp/nouveau
Django Version: 1.5.5
Exception Type: UnboundLocalError
Exception Value:  
local variable 'dest' referenced before assignment
Exception Location: /opt/zdsenv/ZesteDeSavoir/zds/mp/views.py in new, line 221

**Comment by firm1** [comment]
It's fixed
