### ISSUE TITLE
La branche de dev ne builde plus

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2420]
Les tests front ne passent plus sur la branche de dev depuis le merge de la PR #2398

[Voir travis](https://travis-ci.org/zestedesavoir/zds-site/builds/54064939)

Etant donné que la PR en question ne touche pas au front, je soupçonne que le problème vienne de node-gyp (moins probable car on est toujours sur la version 1.0.2) ou de npm (moins probable aussi car on est toujours sur la version 2.7.0), ou carrément dans les dépendances cachées.

A voir donc, en attendant je taggue large.

**Comment by GerardPaligot** [comment]
On a tenté de le relancer ? Parce que ma PR est toujours passée avant ça.

**Comment by SpaceFox** [comment]
Je rappelle les règles de gestion Travis : un build n'est vraiment échoué que lorsque :
1. Ce plantage est systématique (donc après au moins une relance)
2. Reproductible en local

Si ces 2 points ne sont pas satisfaits, on doit partir du principe que Travis fait de la merde.

**Comment by firm1** [comment]
Après relance de Travis. Tout va mieux.

Bizarre, et du coup je ferme.

**Comment by SpaceFox** [comment]
Bienvenue dans le monde merveilleux de Travis…
