### ISSUE TITLE
Le nombre de tutos ayant besoin d'aide n'est pas juste

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2421]
Si on va sur : http://zestedesavoir.com/tutoriels/aides/

D'après le titre, il y a 20 tutos qui ont besoin d'aide. Ce qui n'est pas le cas en réalité puisque les 20 ne concernent que le première page.

**Comment by GerardPaligot** [comment]
Merci à @artragis pour le fix et @pierre-24 pour la QA.
