### ISSUE TITLE
Manque de cohérence dans le marquage de l'obligation de contenu

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2422]
Lorsque je souhaite créer un MP, j'ai 4 champs : 
- Participants
- Titre
- Sous-titre
- Texte

A coté des 2 premiers il y'a une étoile pour me préciser que les champs sont obligatoires. Cependant, il n y'a aucune étoile devant Texte. On pourrait donc penser que ce champs est facultatif, mais non.

La solution serait d'avoir une étoile devant le titre "Texte"

**Comment by GerardPaligot** [comment]
Je confirme ce soir mais je pense avoir résolu cette incohérence dans mon refactoring du module des MPs.

**Comment by Eskimon** [comment]
@GerardPaligot tu confirmes que le bug n'est plus ?

En tout cas j'ai pas teste mais selon le code (https://github.com/zestedesavoir/zds-site/blob/dev/zds/mp/forms.py#L45) ca devrait etre bon...

**Comment by GerardPaligot** [comment]
Ouaip, je confirme.

**Comment by Eskimon** [comment]
Ok, je close !
