### ISSUE TITLE
Url des messages privés incorrecte

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2423]
Depuis le refracto de @GerardPaligot, les urls des mps sont devenues `http://127.0.0.1:8000/mp/39/<bound%20method PrivateTopic.slug of <PrivateTopic%3A Cocuu>>/messages/` !

**Comment by GerardPaligot** [comment]
Je ne parviens pas à reproduire le bug. Est-ce que tu pourrais m'indiquer la manipulation à suivre ?

Edit : C'est bon, j'ai trouvé.

**Comment by firm1** [comment]
Corrigé, merci @GerardPaligot
