### ISSUE TITLE
Une page de paramètres pour les courriels

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2428]
[Depuis le forum](http://zestedesavoir.com/forums/sujet/2622/des-parametres-pour-la-notification-par-email/?page=1#p47445) :

> Je propose d'ajouter un autre formulaire pour gérer les paramètres des notifications par email ? Il serait disponible à l'adresse "/membres/parametres/notifications".
> 
> Il y aurait alors plusieurs options :
> - recevoir un email lorsqu'un membre m'envoi un mp
> - recevoir un email lorsqu'un membre m'ajoute à un mp
> - recevoir un email lorsqu'un membre répond à un mp

Comme précisé dans le sujet, les checkboxs doivent être décochées par défaut !

**Comment by GerardPaligot** [comment]
C'est quelque chose qui ne rentre pas forcément dans le cadre de la ZEP-24 mais qui nécessite son développement en tout cas.

**Comment by AmarOk1412** [comment]
Donc de nouveau valable aujourd'hui :)

**Comment by nils-van-zuijlen** [comment]
Hum, est-ce que c'est encore d’actualité ? Certes, les options ne sont pas aussi détaillées, mais je pense que ça suffit pour la plupart des gens, non ?

**Comment by gllmc** [comment]
Actuellement, il n'est pas possible de désactiver les e-mails pour les nouveaux MP, ça me semble assez gênant. :/
