### ISSUE TITLE
Problème de hauteur du menu Tutoriels

### ISSUE THREAD

**Issue by Deuchnord** [zestedesavoir/zds-site#2429]
Le menu _Tutoriels_ commence à prendre beaucoup de place en hauteur sur les petits écrans et nécessite un scroll, ce qui est peu agréable. Même si ce n'est pas urgent pour le moment, il faudra tout de même voir pour résoudre ça avant que cela ne devienne vraiment un problème avec l'explosion du nombre de catégories.

Voici par exemple ce que cela donne sur mon écran 15 pouces :

![capture du 2015-03-15 10 07 09](https://cloud.githubusercontent.com/assets/7600265/6655338/26a7e116-cafc-11e4-8669-60fe4dcd7bbd.png)

**Comment by Situphen** [comment]
Je pense que ce sera en partie résolu avec [la ZEP 25](https://zestedesavoir.com/forums/sujet/2378/zep-25-categorisation-des-articles-et-tutoriels/) car elle réduira le nom de catégories et de tags.

**Comment by Deuchnord** [comment]
Effectivement, je vais suivre ça de près :)

**Comment by GerardPaligot** [comment]
J'assigne l'issue à @gustavi pour qu'il pense à lier cette issue à la ZEP qu'il a développé.

**Comment by gustavi** [comment]
Merci, c'est ajouté à la ZEP-25 :)

**Comment by SpaceFox** [comment]
Corrigé.
