### ISSUE TITLE
Erreur 404 lors d'une recherche

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#243]
Erreur 404 lorsque l'on effectue une recherche, à priori l'url n'est pas présente dans le fichier de routes zds.urls

**Comment by SpaceFox** [comment]
En fait, soit il y a une logique qui m'échappe complètement, soit il manque un bout de l'application.

J'ai bien un template "search.html", des "search_indexes.py", ... mais rien qui ressemble à une utilisation de tout ça.

**Comment by firm1** [comment]
Euh en fait sur la preprod solr n'est pas installé/configuré (c'est long et
chiant a faire, donc je l'ai pas fais) et il me semble que j'avais enlevé
l'app recherche des fichiers url en attendant d'avoir un modèle de donné
stable. Vu qu'il faut refaire a chaque fois le lien models-> xml a chaque
évolution de la bd pour faire tourner les indexs de solr.

**Comment by SpaceFox** [comment]
OK :)

**Comment by SpaceFox** [comment]
J'ai l'impression que c'est corrigé ça. Vous confirmez ?

**Comment by firm1** [comment]
Corrigé je confirme.

**Comment by SpaceFox** [comment]
Du coup, je ferme :)
