### ISSUE TITLE
[Forum] Impossible d'éditer un sujet 

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#244]
J'ai été étonné de ne pas voir d'issue pour ça, mais il est impossible d'éditer le premier message d'un sujet, l'erreur retourné : 

AttributeError at /forums/message/editer
'Topic' object has no attribute 'get'
Request Method: GET
Request URL:    http://178.32.53.245:8001/forums/message/editer?message=99
Django Version: 1.5.5
Exception Type: AttributeError
Exception Value:  
'Topic' object has no attribute 'get'

**Comment by firm1** [comment]
Fixé, mergé et en prod.

Je ferme
