### ISSUE TITLE
Impossible de builder le front

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2443]
Sur un système nouvelle installé Ubuntu 14.10, j'ai essayé pas mal de trucs pour builder le front. Mes tentatives se soldent malheuresement par un echec. Meme en suivant la doc officielle ça n'a pas l'air de marcher, que ce soit en sudo ou pas.

A chaque fois, c'est le message suivant qui m'est renvoyé : 

``` bash
> lwip@0.0.6 install /home/firm1/prj/zds-site/node_modules/css-sprite/node_modules/lwip
> node-gyp rebuild

Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-31-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/firm1/prj/zds-site/node_modules/css-sprite/node_modules/lwip
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

> node-sass@2.0.1 install /home/firm1/prj/zds-site/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js


> node-sass@2.0.1 postinstall /home/firm1/prj/zds-site/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

`linux-x64-node-0.10` exists; testing
Binary is fine; exiting
npm ERR! Linux 3.16.0-31-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.36
npm ERR! npm  v2.7.1
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lwip@0.0.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/firm1/prj/zds-site/npm-debug.log
```

Je tourne avec node v0.10.36 et npm  v2.7.1.
Ma version de Gcc est la 4.9

Quelqu'un peut-il m'éclairer sur ce problème ?

**Comment by sandhose** [comment]
A priori c'est parce que tu as une version de gyp installée globalement qui entre en conflit avec celle de node-gyp... (voir https://github.com/TooTallNate/node-gyp/issues/363#issuecomment-33212812 )

**Comment by firm1** [comment]
Comment je peux supprimer ma version globale de gyp ? Et surtout un mystère pour moi, c'est comment j'ai pu l'installer ?

**Comment by sandhose** [comment]
Je sais pas, tu as un jour touché à un projet Google ? (chromium, android...)

Sinon c'est soit installé via apt, soit via pip... Tu peux déjà voir où il est installé via `python -c 'import gyp; print gyp.__file__'`

**Comment by firm1** [comment]
Ah c'est ptet Android, mais ça m'étonnerait.

SInon, il est visiblement installé ici `/usr/lib/python2.7/dist-packages/gyp/__init__.pyc`. Mais du coup si je le vire/modifie ça aura un impact sur un autre soft quelque part ?

Tu penses qu'il y'a pas moyen de gérer ce conflit ?

**Comment by sandhose** [comment]
A priori, si tu es dans un virtualenv, les paquets python globaux sont ignorés, donc ça devrait ignorer l'installation globale si tu te trouves dans un virtualenv quand tu installe les deps npm

**Comment by firm1** [comment]
J'ai déjà essayé étant dans le virtualenv, mais étant donné que je suis obligé de passer en sudo, npm tape quand meme dans le global.

La j'ai tenté le truc du gars dans l'issue, et ça à l'air de fonctionner.

faudrait marquer ça dans une doc.

**Comment by sandhose** [comment]
Pourquoi tu es obligé de passer en sudo ? npm install se fait (plus) en root, hein ! (surtout pas !)

**Comment by firm1** [comment]
Bah quand je le fais sans le sudo il m'emerde sur les droits de fichiers.

Je suppose que c'est a cause de l'update qui nécessite les droits root.

**Comment by firm1** [comment]
Ce problème étant résolu, je ferme ici. Je ne le rattache à aucune milestone car il s'agit d'une simple question.

**Comment by SpaceFox** [comment]
Ben du coup on ne sait pas comment tu as résolu le problème ?

**Comment by firm1** [comment]
Exactement comme dans le lien linké par @sandhose , c'est à dire : 
1. `python -c 'import gyp; print gyp.__file__'` => `/usr/lib/python2.7/site-packages/gyp/__init__.pyc`
2. `mv /usr/lib/python2.7/site-packages/gyp /usr/lib/python2.7/site-packages/gyp_backup`
3. `npm install` et là ça marche.

Mais le seul souci c'est que pour bosser sur d'autres trucs qui utilise gyp chez moi, je vais devoir renommer le dossier à chaque fois. Mais bon, ça marche au moins comme hotfix
