### ISSUE TITLE
La v1.7-RC1 ne déploie pas

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2446]
Des détails ici : https://zestedesavoir.com/forums/sujet/2692/jai-voulu-deployer-la-v17-rc1/

Je rappelle à tout hasard que le principal intérêt des PR, c'est de pouvoir faire une revue de code.

**Comment by SpaceFox** [comment]
Pour ceux qui ne l'auraient pas vu : https://zestedesavoir.com/forums/sujet/2692/jai-voulu-deployer-la-v17-rc1/?page=1#p50056

Mon avertissement est tout à fait sérieux.

**Comment by SpaceFox** [comment]
Ne pas fermer tant que le release.md n'est pas corrigé.

**Comment by Eskimon** [comment]
Merci @SpaceFox :) (et @pierre-24 dévoué a la QA !)

**Comment by Eskimon** [comment]
Oups mauvais bouton, le release.md n'est pas encore merge

**Comment by SpaceFox** [comment]
Le.vrai nom du fichier est update.md en fait 😃

**Comment by Eskimon** [comment]
reclosation alors !!
