### ISSUE TITLE
[Forum] Impossible d'éditer une réponse

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#245]
Le bug semble similaire mais l'erreur retournée n'est pas là même que l'issue que je viens de faire, quand j'essaye d'éditer une réponse sur le forum j'ai l'erreur suivante : 

AttributeError at /forums/message/editer
'NoneType' object has no attribute 'pk'
Request Method: GET
Request URL:    http://178.32.53.245:8001/forums/message/editer?message=100
Django Version: 1.5.5
Exception Type: AttributeError
Exception Value:  
'NoneType' object has no attribute 'pk'

**Comment by firm1** [comment]
Fix.
