### ISSUE TITLE
Galerie : ne pas changer l'url lors d'une MAJ 

### ISSUE THREAD

**Issue by Vayel** [zestedesavoir/zds-site#2452]
Reporté d'[ici](http://zestedesavoir.com/forums/sujet/2706/galerie-ne-pas-changer-lurl-lors-dune-maj/).

Quand on ajoute une image dans une galerie et que l'on met à jour cette image, l'url est changée, ce qui nous oblige à éditer tous les messages où l'image apparait. Peut-être serait-il préférable de conserver l'ancienne url, pour que l'image se mette à jour dans les messages automatiquement.

Par contre, comme l'ancienne image sera alors définitivement supprimée, il pourrait être judicieux d'afficher un message indiquant cela :

> En mettant à jour cette image, vous l'écrasez. Si vous souhaitez la conserver, créez plutôt une nouvelle image.

**Comment by firm1** [comment]
On s'est rendu compte que cette fonctionnalité pourrait induire d'autres problèmes/failles. La décision a été prise de ne pas l'implémenter.

Je ferme donc l'issue car on ne peut pas la corriger.

**Comment by SpaceFox** [comment]
Au-delà de ça, changer l'image sans en changer l'URL provoquerait des problèmes de cohérence de cache côté navigateur (actuellement toutes nos images sont servies avec un cache navigateur très long, 1 an de mémoire).

**Comment by viki53** [comment]
Du coup il faudrait peut-être mettre un messages pour l'utilisateur, histoire de le prévenir que l'URL va changer (et qu'il faudra donc mettre à jour toutes les références).

Ou supprimer la fonctionnalité tout simplement.
