### ISSUE TITLE
Erreur lors d'ajout d'un membre à une galerie

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#246]
Quand on veut ajouter un membre dans une galerie si le membre n'existe pas ou si le champ est vide on a une erreur 404 sur /galerie/modifier

**Comment by SpaceFox** [comment]
@firm1 c'est encore ouvert ici, c'est volontaire ou c'est une erreur ?

**Comment by firm1** [comment]
C'est volontaire,  elle n'est pas encore corrigée

**Comment by firm1** [comment]
C'est bon, cette fois ci, c'est fixé.

Je ferme
