### ISSUE TITLE
Build automatiquement le front a chaque release avec Travis

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#2471]
En regardant dans le code de react-native, j'ai remarqué qu'ils utilisent travis pour build automatiquement leur doc, et la push sur le répo à chaque push sur leur branche master. 

Voir https://github.com/facebook/react-native/blob/master/.travis.yml

On peut peut-être mettre en place un système similaire pour build le front à chaque push sur une branche release-XX. Un prérequis d'un tel système serait de créer un utilisateur que travis utiliserait pour push.

**Comment by Eskimon** [comment]
> En regardant dans le code de react-native, j'ai remarqué qu'ils utilisent travis pour vos automatiquement leur donc et la push sur le répo a chaque push sur leur branche master.

Tu copieras 100 fois "Je me relierais [l'autocorrect] avant de poster avec mon téléphone" :D

**Comment by sandhose** [comment]
Ca va comme ça ? c:

http://s.sandhose.fr/punition.html

Je corrigerais ça a midi, puisque apparement, on peut pas le faire depuis la version mobile de GitHub... :-°

**Comment by sandhose** [comment]
Bon, mes tests sont plutôt concluants :D 

https://github.com/sandhose/zds-site/commit/08f4637667980d8e6aa0915e19d3c0eab9848a32 et https://github.com/zestedesavoir/zds-site/commit/1e7b834f776b2071dc787771b08f7ee54bbdcf30
https://travis-ci.org/sandhose/zds-site/jobs/56259430

**Comment by pierre-24** [comment]
Yeah, gros merci à @sandhose sur celle là, je pense que c'est @SpaceFox qui va être content :)
