### ISSUE TITLE
Documentation de l'API : inaccessible

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#2472]
Tout est dans le titre. La documentaion de l'API est totalement inaccessible. Quand on tente d'y accéder on obtient cette page : 

![capture du 2015-03-28 20 33 18](https://cloud.githubusercontent.com/assets/4312887/6882577/166dd268-d58a-11e4-9689-a516d005cf26.png)

J'ai testé sur Chromium également et, c'est la même chose. Par-contre, quand on y accède en `http**s**`, bien que ça déconne la page s'affiche tout de même ! 

ping @GerardPaligot ! :)

**Comment by Situphen** [comment]
La documentation de l'API n'est disponible qu'en HTTP et pas en HTTPS. L'adresse pour accéder à l'api est "/api/" et non pas "/api/api-docs/" !

**Comment by Axylium** [comment]
> La documentation de l'API n'est disponible qu'en HTTP et pas en HTTPS

Je le sais. Ce n'était qu'à titre de comparaison.

> L'adresse pour accéder à l'api est "/api/" et non pas "/api/api-docs/" !

Bizarre, j'ai suivi le lien dans le footer.. Pourtant il est bon. 

Bon, sinon, je n'ai rien dis !
