### ISSUE TITLE
Pas de formulaire sur la page de biographie

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2480]
Très très simple et très très bête: intégrer le formulaire habituel d'édition de texte markdown pour la biographie.

![screenshot from 2015-04-02 14 36 32](https://cloud.githubusercontent.com/assets/7889675/6970758/a5bc62b8-d945-11e4-813b-4dfda271409d.png)

(attention ceci dit à gérer la prévisualisation)

**Comment by Eskimon** [comment]
Si j'en crois [la pseudo-doc front](http://zestedesavoir.github.io/zds-site/#/interface-utilisateur/formulaires) :

> Sur n'importe quel textarea, ajoutez la classe md-editor et il se passera alors :
> - transformation du champ en éditeur riche (boutons d'assistance à l'édition, ...) ;
> - ajout de l'aide Markdown en dessous du formulaire.

Mais comme sur la doc front cette démo ne marche elle-même pas, je ne sais pas a quel point c'est exact.

**Comment by pierre-24** [comment]
Oh, tient, ça faisait longtemps que je l'avais plus vue, celle là. Ça serait d'ailleurs peut-être bien d'en remonter une partie dans la doc officielle nouvellement créée.

Plus sérieusement, si c'est aussi simple que ça ... Taggue "facile" :p

**Comment by Eskimon** [comment]
Tag mis :) mais je te dis, entre doc de plus de 6 mois et réalité il y a ptet des changements... (tu m'diras, c'est vite testé au moins !!)

**Comment by firm1** [comment]
> Plus sérieusement, si c'est aussi simple que ça ... Taggue "facile" :p 

Il y'a pas a dire, c'est facile a rajouter le menu d'édition là. Mais le plus corsé, et le moins evident, est de rajouter la previsualisation. Du coup, je ne pense pas que ça soit si facile.

**Comment by pierre-24** [comment]
Ah,oui, j'oubliais "corrigé et mergé, je ferme" :)

**Comment by Eskimon** [comment]
Reste plus qu'à cliquer sur le bouton "fermer" alors :-°

**Comment by pierre-24** [comment]
Bien vu :-°
