### ISSUE TITLE
ReadTheDoc ne compile plus notre documentation

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2483]
L'heure est grave. #2451, qui était sencé améliorer notre documentation, [l'a toute cassée](https://readthedocs.org/builds/zds-site/2528932/), alors qu'elle compile très bien chez moi, [chez artragis](https://github.com/zestedesavoir/zds-site/pull/2451#issuecomment-89277094) et @firm1 [avait même réussi à la déployer sur un serveur](https://github.com/zestedesavoir/zds-site/pull/2451#issuecomment-88910229).

Deux solutions: soit il y a un truc qui va pas chez ReadTheDoc (mais j'arrive pas à voir si on a une version différente de sphinx par rapport à la leur), soit y'a un souchi avec Sphinx. La dernière option est la plus "inquiétante".

Un peu de lecture:
- http://stackoverflow.com/questions/22761486/sphinx-documentation-locally-works-but-not-on-read-the-docs
- https://github.com/sphinx-doc/sphinx/issues/1725

Et pour tester ça, ça va pas être facile, par ailleurs (va falloir faire des pushs sur une branche sur laquelle RTD est activé).

**Comment by pierre-24** [comment]
Note: RTD [semble coincer sur ce fichier](https://github.com/zestedesavoir/zds-site/blob/dev/doc/source/back-end-code/article.rst) en nous crachant une erreur d'encodage. Ce fichier est le premier de la série a employer `autodoc` pour lire le _docstring_. C'est très probablement lié.

**Comment by artragis** [comment]
ALors c'est étrange : 
- au boulot (ubuntu 14.04) je n'ai pas ce problème
- chez moi (xubuntu 14.10) je l'ai.

j'ai observé le fichier et rien n'indique la présence d'un unicode...
ça pue le nom de local mal configure

chez moi ça dit ça : 

``` bash
LANG=fr_FR.UTF-8
LANGUAGE=fr_FR
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

**Comment by pierre-24** [comment]
Bon, moi j'ai ça (Debian/Jessie)

``` bash
pierre@pc:~$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Forcément, mon PC étant en anglais, j'ai la _locale_ anglaise partout. Je sais plus pourquoi, mais la doc précise à un moment qu'on doit avoir la locale française pour que ça fonctionne. Donc je l'ai aussi :

``` bash
pierre@pc:~$ locale -a
C
C.UTF-8
en_US.utf8
fr_BE.utf8
fr_FR.utf8
POSIX
```

Va savoir ^^

**Comment by pierre-24** [comment]
(je peux m'amuser à switcher au français pour tester, si ça vous amuse)

**Comment by artragis** [comment]
J'ai trouvé ! 

ça foire avec python 2.7.8

ça marche avec python 2.7.9 !

**Comment by pierre-24** [comment]
Ah. Intéréssant :) ... Bon, comment qu'on met la bonne version de python chez RTD ?

**Comment by artragis** [comment]
et du coup je sais pas pourquoi ça foire avec 2.7.8.

**Comment by pierre-24** [comment]
Le bug a, on dirait, évolué. Soit [ça passe, mais il se plaint qu'il trouve pas GIT](https://readthedocs.org/builds/zds-site/2544823/) (sur v1.7-RC3); soit [ça plante total](https://readthedocs.org/builds/zds-site/2544822/) (sur la version stable, donc je dirais la _dev_). Pour le premier cas, je crois qu'il y a un requirement a ajouter quelque part.

Dans tout les cas, what the f**\* ???

**Comment by firm1** [comment]
Sur dev : 

J'ai rajouté le fichier `requirements.txt` a la conf de readthedocs, le résultat de la compilation donne [ceci](https://readthedocs.org/builds/zds-site/2546648/) : 
- d'un coté il n'arrive pas a installer tous les paquets (dépendances systèmes pour compilations manquants)
- de l'autre coté on dirait que python-zmarkdown est pas bien packagé pour lui.

J'ai alors, demandé à ce qu'il passe non plus par le requirements.txt mais pas le setup.py pour tout installer, et là il s'en sort [plutot pas mal](https://readthedocs.org/builds/zds-site/2546689/). Il ne reste que les warnings suivants : 

```
/var/build/user_builds/zds-site/checkouts/stable/doc/source/utils/templatetags.rst:111: WARNING: Inline substitution_reference start-string without end-string.
/var/build/user_builds/zds-site/checkouts/stable/doc/source/utils/templatetags.rst:121: WARNING: Inline substitution_reference start-string without end-string.
/var/build/user_builds/zds-site/checkouts/stable/doc/source/utils/templatetags.rst:137: WARNING: Inline substitution_reference start-string without end-string.
/var/build/user_builds/zds-site/checkouts/stable/doc/source/install/includes/git-pre-hook.rst:: WARNING: document isn't included in any toctree
WARNING: html_static_path entry u'/var/build/user_builds/zds-site/checkouts/stable/doc/source/_static' does not exist
```

**Comment by pierre-24** [comment]
Il s'en sort effectivement assez bien, ça, ça a l'air d'être des typos dans nos docstrings. Par contre, j'arrive pas à voir le résultat ([et si le résultat est celui-là, il nous plante encore la moitié des docstrings](http://zds-site.readthedocs.org/fr/v1.7-RC3/back-end-code/private-message.html))

**Comment by firm1** [comment]
Ton lien pointe sur la Relase 1-7 alors que mon buid a été fait sur la dev.

Je m'en vais relancer le build de la release pour voir

**Comment by pierre-24** [comment]
Si "latest", c'est "dev", [la constatation est la même](http://zds-site.readthedocs.org/fr/latest/back-end-code/member.html) :'(

**Comment by firm1** [comment]
En effet, je n'ai pas regardé plus en détail, je vais voir ce qu'il en journée. Mais ayant essayer la compil en local, ça ne marche pas non plus. J'ai des warnings aussi

**Comment by pierre-24** [comment]
J'ai les warning sur v1.7-RC3 (mais c'est encore la vieille doc). Et sur upstream/dev, je compile sans problème. What the f**********\* !!!!

![screenshot from 2015-04-07 20 25 44](https://cloud.githubusercontent.com/assets/7889675/7036530/5b306050-dd64-11e4-8775-76dcb262d7de.png)

**Comment by firm1** [comment]
Bon visiblement il n'arrive pas [à compiler lastest non plus](https://readthedocs.org/builds/zds-site/2546751/) qui fait reférence à dev. a cause de [la nouvelle lib GeoIP](https://github.com/zestedesavoir/zds-site/issues/2520)

**Comment by pierre-24** [comment]
Ah. Intéréssant (oui, je sais, j'arrive deux jour plus tard). On sait faire quelque chose pour ça ? (à part aller raler chez RTD ?)

**Comment by SpaceFox** [comment]
J'ai mergé le revert de GeoIP, par contre je ne sais pas si ça règle le problème ici.

**Comment by pierre-24** [comment]
On ne le saura que quand #2616 sera réglé, mais je pense que ça va nettement améliorer le truc, donc d'avance merci ;)

**Comment by firm1** [comment]
Par ailleurs, notons que [la documentation de la v15.5](http://zds-site.readthedocs.org/fr/v15.5/) est HS, elle ne compile pas non plus

**Comment by pierre-24** [comment]
... J'en ai marre. Vraiment, là.

**Comment by Eskimon** [comment]
Cay bon :) Merci @pierre-24 pour toute l'investigation !!
