### ISSUE TITLE
[version 1.7] La bannière "cookies" disparaît quand on clique sur "en savoir plus"

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2487]
Comme je l'avais mentionné à l'époque avec #2313, y'a un soucis avec `eu-cookies-banner`; Personnellement, la bannière disparaît quand je clique sur "en savoir plus". Debian/jessie et Chrome/41.0 et Firefox/31.5. J'avais finalement à l'époque réussi à reproduire le truc, mais j'avais d'énorme problème de _front_. Donc, _my bad_ sur celle là, mais très clairement, ça marche pas en bêta.

**Comment by Situphen** [comment]
Bon, l'erreur vient de la version 1.4 de [Cookies-EU-banner](https://github.com/Alex-D/Cookies-EU-banner). Quand j'ai commencé ma PR ils étaient à la 1.3 mais comme la version n'est pas en strict dans le `package.json`, tu as installé la 1.4 qui était sortie entre temps.

Bref, je fais une PR chez eux. Après qu'ils l'aient accepté et qu'ils aient fais une release, je ferai une PR de beta-fix ici !

**Comment by pierre-24** [comment]
... Et j'ai probablement utilisé la 1.3 pour finalement avoir le bon comportement, ceci explique celà. Bon, une fois encore ZdS contribue aux projets libres ;)

**Comment by SpaceFox** [comment]
Donc si je comprends bien, on a ajouté une dépendance pour "mieux gérer" le coup des cookies CNIL et à la place de ça, on se retrouve avec une dépendance dont la mise à jour pète complètement la gestion des cookies CNIL ?

Est-ce qu'on ne pourrait pas plutôt soit rester sur une version fonctionnelle, soit utiliser un système fiable ?

**Comment by Situphen** [comment]
> Donc si je comprends bien, on a ajouté une dépendance pour "mieux gérer" le coup des cookies CNIL et à la place de ça, on se retrouve avec une dépendance dont la mise à jour pète complètement la gestion des cookies CNIL ?

La mise à jour a pété une partie de la gestion, celle qui fait en sorte que quand tu cliques sur "En savoir plus", tu n'es pas encore tracké et la bannière s'affiche. Le reste fonctionne bien.

> Est-ce qu'on ne pourrait pas plutôt soit rester sur une version fonctionnelle, soit utiliser un système fiable ?

On a deux solutions :
- soit on prend la version 1.3 ;
- soit on attend que ma PR https://github.com/Alex-D/Cookies-EU-banner/pull/8 soit mergée et qu'une nouvelle version soit créée.

Dans tous les cas je mettrai cette dépendance en strict pour que ce cas ne se reproduise plus !

**Comment by SpaceFox** [comment]
> La mise à jour a pété une partie de la gestion, celle qui fait en sorte que quand tu cliques sur "En savoir plus", tu n'es pas encore tracké et la bannière s'affiche. Le reste fonctionne bien.

C'est dommage, c'était justement **l'argument** qui nous a fait passer à cette dépendance de mémoire.

On va voir la réactivité de l'upstream à intégrer la PR, mais dans tous les cas ça ne doit pas ralentir notre release (un peu moins de 2 semaines pour que ce soit réintégré ici donc).

**Comment by pierre-24** [comment]
On va aider: c'est  @Alex-D qui est derrière eu-cookies-banner. Ping ;)

**Comment by Alex-D** [comment]
C'est corrigé par @Situphen et mergé. C'était un simple `_` qui manquait.

**Comment by Alex-D** [comment]
J'ai déployé la 1.2.6, vous pouvez la mettre en tant que version "fixe" dans votre `package.json` (sans le `^`), ça évitera les surprises.

**Comment by SpaceFox** [comment]
OK, merci @Alex-D  pour la réactivité !

**Comment by Eskimon** [comment]
C'est réparé
