### ISSUE TITLE
Page d'aide des auteurs : le compteur a disparu

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2488]
En direct [de la preprod](http://beta.zestedesavoir.com/tutoriels/aides/?page=1).

Avant, il me semble qu'on avait une valeur, maintenant on a rien.

Capture : 
![ooops](https://cloud.githubusercontent.com/assets/6066015/6983876/15034a78-da23-11e4-931d-6ff5fefa5ae6.PNG)

**Comment by Eskimon** [comment]
En prod il y a une valeur en tout cas

**Comment by pierre-24** [comment]
Je confirme qu'il y a un souchi par là.

**Comment by SpaceFox** [comment]
C'est corrigé, merci.
