### ISSUE TITLE
Ajouter des utilisateurs injoignables à une conversation privée

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2490]
Serveur : Bêta
Version : v1.7-RC2

Scénario :
- Créez une nouvelle conversation avec des utilisateurs joignables (ou rendez-vous à une conversation existante).
- Cliquez sur "Ajouter un membre" et spécifiez "test2" qui est un utilisateur injoignable.
- Validez et constatez que l'utilisateur injoignable figure bien dans la liste des participants.

Informations complémentaires :

Il est impossible de rajouter des utilisateurs injoignables à la création d'une conversation privée. Le bug est donc rencontrée uniquement dans le cas du scénario.

**Comment by Eskimon** [comment]
Je viens de tester des choses sur la beta (v15.5.1):
- Rajouter `anonyme` dans un de mes MP existant = j'ai bien un message d'interdiction
- Signaler une erreur dans un tuto d'Auteur externe uniqement = j'ai bien un message d'interdiction
- Signaler une erreur dans un tuto avec Externe + Auteurs reels = le MP auto part correctement.

Pour moi cet ticket est donc réglé !
