### ISSUE TITLE
La liste des derniers sujets créés dans le profil sont mal affichées

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2491]
Serveur : Bêta
Version : v1.7-RC2
Système : OS X
Navigateur : Google Chrome Version 41.0.2272.118 (64-bit)

Scénario :
- Si votre compte ne dispose pas de sujets, allez en créer quelques uns sur les forums.
- Rendez-vous sur votre profil dans la section "Derniers sujets créés".
- Constatez que la liste n'est pas bien affichée.

Voici un item de la liste actuellement en prod (v1.6c) :
![capture d ecran 2015-04-03 a 23 38 44](https://cloud.githubusercontent.com/assets/1913901/6989399/27353408-da5b-11e4-9206-ec8e66734530.png)

Voici un item de la liste sur la bêta :
![capture d ecran 2015-04-03 a 23 38 55](https://cloud.githubusercontent.com/assets/1913901/6989406/33e39b90-da5b-11e4-9faa-af0ecf67bb62.png)

Un autre item de la liste encore pire sur la bêta :
![capture d ecran 2015-04-03 a 23 44 43](https://cloud.githubusercontent.com/assets/1913901/6989431/7c2c6e4a-da5b-11e4-9b7e-cf4a329335cc.png)

Le bug saute aux yeux.

Informations complémentaires :

Lorsque vous proposerez un fix, n'oubliez pas de tester tous les cas (sujet résolu, sujet verrouillé et d'autres si vous en voyez).

**Comment by Eskimon** [comment]
Je suis sur portable donc c'est galère pour retrouver les tickets mais il me semble (presque certain) que c'est un merge que j'ai fait et dont ma sa était malheureusement incomplète (elle était correcte pour le bugfix mais j'ai pas vu assez tôt cet effet de bord). 
La PR fautive était faite par A-312 sibmes souvenirs sont bons et concernait l'icone "résolu" dans la liste des sujets. C'était un fix de css.

Je vous laisse faire la recherche github :D

**Comment by Eskimon** [comment]
Voili voila la source des soucis je crois : https://github.com/zestedesavoir/zds-site/pull/2340

**Comment by ghost** [comment]
Le problème c'est qu'en rajoutant `min-width:35px;`, les autres éléments sont décalé, il faut surement supprimer un `min-width: XX%;` de la div au milieu ou autre pour éviter ce rendu.

https://github.com/A-312/zds-site/commit/47c04687c8d9b7bb090971084f6c7cc72d9c71d2#diff-bd4bff66b6594772a0597ce6205214c2R85

![index](https://cloud.githubusercontent.com/assets/10801383/7001200/352973c8-dc34-11e4-97c0-dbb355b08e81.png)

Peut-être aussi corriger l'espace blanc à droite ? Ça aidera à corriger le problème.

**Comment by Eskimon** [comment]
Bon, comme la release doit avancer il y a deux solutions :
1. Un fix est proposé
2. Les commits de la PR sus-mentionné sont revert.

Comme A-312 n'est plus sur github, j'ai bien peur que le plan B sera mis en oeuvre. Dites le moi et je ferais le nécessaire pour revert.

**Comment by SpaceFox** [comment]
A moins que quelqu'un ne soit capable de remplacer A-312 au pied levé, je crains que le revert ne soit en effet indispensable...

**Comment by Eskimon** [comment]
J'ai préparée la PR de revert (2530), je laisse le DTC trancher sur le meilleur moment pour l'appliquer.

**Comment by SpaceFox** [comment]
Vu que les "fix" c'était à propos d'icônes écrasées par du texte, c'est mineur par rapport aux problèmes apportés par le "fix".

Du coup, ben on QA ton revert et on merge :)

**Comment by SpaceFox** [comment]
Corrigé, merci.
