### ISSUE TITLE
Impossible de cliquer sur une conversation privée dans les notifications

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2492]
Serveur : Bêta
Version : v1.7-RC2
Système : OS X
Navigateur : Google Chrome Version 41.0.2272.118 (64-bit)

Scénario :
- Faite le nécessaire pour avoir une notification dans vos conversations privées.
- Tentez de cliquez dessus. Si vous n'êtes pas dirigé vers la conversation, vous avez rencontré le bug sinon répétez le scénario. Il n'arrive qu'une 1/3 chez moi.

**Comment by Eskimon** [comment]
Yep j'ai constate ca aussi pour des notifs normal. Est-ce que ca serait pas la encore du a un comportement indesirables du javascript comme pour https://github.com/zestedesavoir/zds-site/issues/2486 ?

**Comment by Situphen** [comment]
Effectivement c'est le même bug !

**Comment by Eskimon** [comment]
Réglé !
