### ISSUE TITLE
Impossible de valider le formulaire de connexion avec CMD+Enter

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2493]
Serveur : Bêta
Version : v1.7-RC2
Système : OS X
Navigateur : Google Chrome Version 41.0.2272.118 (64-bit)

Scénario :
- Rendez-vous sur la page de connexion.
- Remplissez les champs d'identification.
- Validez avec le raccourci CMD+Enter.
- Constatez que votre formulaire n'est pas soumit.

Informations complémentaires :

CTRL+Enter fonctionne correctement.

**Comment by Situphen** [comment]
Ce n'est pas un bug ! Les raccourcis CTRL+ENTER et CMD+ENTER ne sont prévus que pour l'éditeur Markdown. Si CTRL-ENTER fonctionne, ça doit venir du navigateur.

**Comment by GerardPaligot** [comment]
Ok, j'avais un doute. Je ferme.
