### ISSUE TITLE
L'item avec la pseudo de l'utilisateur dans la sidebar n'ouvre pas le profil

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2495]
Serveur : Bêta
Version : v1.7-RC2
Système : Nexus 4
Navigateur : Google Chrome Version 41.0.2272.96

Scénario :
- Connectez-vous sur votre téléphone.
- Ouvrez le menu latéral.
- Dans la première section "Mon compte", cliquez sur votre pseudo.
- Constatez que vous vous trouvez dans vos paramètres et pas sur votre profil.

**Comment by Situphen** [comment]
Je sais pas si c'est vraiment un bug. Le titre au-dessus de l'avatar est "Mon Compte" donc il correspond bien au lien !

**Comment by GerardPaligot** [comment]
Personnellement, je m'attendais à me rendre sur mon profil. C'est stupide de mettre en avant les paramètres utilisateur via cet item.

**Comment by Eskimon** [comment]
Idem je trouve le comportement "non attendu". Par contre ce sera a corriger en dev et non pas hotfix car c'est déjà comme ça en prod.

**Comment by Eskimon** [comment]
Réglé !
