### ISSUE TITLE
Manque de cohérence dans la sidebar

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2496]
Serveur : Bêta
Version : v1.7-RC2
Système : Nexus 4
Navigateur : Google Chrome Version 41.0.2272.96

Scénario :
- Connectez-vous et ouvre la sidebar.
- Constatez que :
  - La section "navigation" devrait se nommer "paramètres" (et figurez en bas de la sidebar ?)
  - L'item avec votre pseudo sélectionne le titre et l'item lorsque vous appuyez dessus.

**Comment by Eskimon** [comment]
Ceci n'etant pas propre a la v1.7, je met en jalon 1.x

**Comment by SpaceFox** [comment]
Dans tous les cas, seules les issues _corrigées et mergées_ ont droit à un numéro de version précis.

**Comment by SpaceFox** [comment]
Un éventuel bug bloquant serait sans milestone (ou en v1.x) et surtout labellisé "bloquant".

**Comment by Karnaj** [comment]
J'ai l'impression que ce problème est réglé.

**Comment by Situphen** [comment]
J'ai aussi cette impression.

**Comment by Arnaud-D** [comment]
> L'item avec votre pseudo sélectionne le titre et l'item lorsque vous appuyez dessus.

Ce problème-là est toujours d'actualité. Le lien englobe tout le titre, alors que ce n'est pas le cas pour les autres liens de la sidebar.

![image](https://user-images.githubusercontent.com/35631001/79386439-6c646080-7f6a-11ea-9c77-5d5e3d2675b8.png)

**Comment by Karnaj** [comment]
Ah, j'avais pas compris le problème. En vrai, ce bouton est quasiment invisible pour moi sur mobile vu qu'il y a **deux** autres moyens d'accéder à son profil, il a un autre lien dans la sidebar dans le bloc `Mon compte` et on peut cliquer sur l'image de profil en haut à droite. Si j'étais de mauvaise foi, je proposerais de supprimer le titre « Mon profil », l'image et le lien du menu mobile. ;)

**Comment by Arnaud-D** [comment]
> Si j'étais de mauvaise foi, je proposerais de supprimer le titre « Mon profil », l'image et le lien du menu mobile. ;)

En vérité, c'est peut être la meilleure solution...

**Comment by Karnaj** [comment]
Dans le [template du header](https://github.com/zestedesavoir/zds-site/blob/64786485c74c5002b4f4c1eb1cbac694be7133d6/templates/header.html#L332), on change la classe de la balise `<a>` dans laquelle on a l'image et le nom d'utilisateur. Elle vaut `dont-click-if-sidebar`, on remplace par `mobile-menu-hide` pour le cacher si on est sur mobile.

**Comment by helmasaur** [comment]
Vous souhaitez cacher le nom de la catégorie ou carrément toute la catégorie (incluant l'avatar et le pseudonyme ?). Sinon, si l'on n'est pas sur mobile, ce bloc s'affiche où ? Supprimer la balise `<a>` ne serait pas mieux encore ?

**Comment by AmauryCarrade** [comment]
Sans ce bloc, si on n'est pas sur mobile, il s'affiche au même endroit que sur mobile, à savoir en haut à droite du site (ou dans le menu associé, sur l'entrée « Mon profil »).

À titre personnel, ça ne me choquerait pas de retirer complètement cette partie du menu mobile latéral, vu que c'est un direct doublon.

**Comment by helmasaur** [comment]
En supprimant ce morceau de code, je ne vois aucune différence sur la version ordinateur :

```html
<a href="/membres/voir/admin/" class="dont-click-if-sidebar mobile-menu-imported mobile-menu-link mobile-menu-bloc" title="Mon profil" data-title="Mon profil">
    <img src="https://secure.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?d=identicon" alt="Mon compte" class="avatar">
    <span class="username label">admin</span>
</a>
```

Ça ne supprime que le bloc entouré de pointillés de [cette image](https://github.com/zestedesavoir/zds-site/issues/2496#issuecomment-614264535). Du coup, soit je fais comme @Karnaj l'a dit, soit je supprime le nœud entier. N'aillant pas assez de connaissance, je préfère demander et ne pas faire d'erreur.

**Comment by AmauryCarrade** [comment]
Sauf erreur c'est un élément spécifique à la barre latérale, donc je serais partisan de l'enlever complètement.

Au pire, il y aura une QA :)
