### ISSUE TITLE
Tableau des derniers messages postés mal formé

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2497]
Serveur : Bêta
Version : v1.7-RC2
Système : OS X
Navigateur : Google Chrome Version 41.0.2272.118 (64-bit)

Scénario :
- Rendez-vous dans les [derniers messages de cshark](http://beta.zestedesavoir.com/forums/messages/247/).
- Constatez que le tableau n'est pas bien formé.

![capture d ecran 2015-04-04 a 00 19 12](https://cloud.githubusercontent.com/assets/1913901/6989767/676fc6fa-da60-11e4-8435-4f44feaa6e41.png)

**Comment by Eskimon** [comment]
Pour info, c'est un effet pervers des titres qui n'ont pas de cesure (en l'occurence une formule mathjax a la con).

Si on compare à un [profil "normal"](http://beta.zestedesavoir.com/forums/messages/255/) tout va bien.

En considérant que les titres/sous-titres sont censé être des mots et non pas juste un ensemble de lettre collées, le bug est vraiment en priorité faible je pense...

**Comment by artragis** [comment]
Nous pourrons noter que ce bug n'apparait plus https://beta.zestedesavoir.com/forums/sujets/membre/82/.

**Comment by GerardPaligot** [comment]
Tu as un sujet avec une formule mathjax dans ta liste ?

**Comment by artragis** [comment]
J'en crée un alorsz.

2015-10-13 13:57 GMT+02:00 Gérard Paligot notifications@github.com:

**Comment by artragis** [comment]
voilà

**Comment by GerardPaligot** [comment]
Alors c'est bon !

**Comment by Eskimon** [comment]
J'ai pas compris en quoi c'est corrigé ? (ou alors j'ai pas compris ou était le bug)

**Comment by GerardPaligot** [comment]
Le bug était : Sur la liste des messages d'un utilisateur, si l'un des titres des sujets listés comportait une formule Math, les colonnes étaient toutes pétées. Ca n'est plus le cas (cf. lien de @artragis).
