### ISSUE TITLE
Les membres non joignables peuvent être ajoutés comme auteur

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2498]
Serveur : Bêta
Version : v1.7-RC2
Système : OS X
Navigateur : Google Chrome Version 41.0.2272.118 (64-bit)

Scénario :
- Créez une publication ou rendez-vous à une publication existante.
- Rajoutez un auteur non joignable.
- Constatez qu'il figure dans les auteurs.

Informations complémentaires :

Il **faut** refactoriser la gestion de l'ajout de participants à n'importe quel concept (MP, tutoriel, article, etc.) pour ne pas répéter les règles partout !

**Comment by Eskimon** [comment]
En beta 15.5.1

Je viens d'essayer d'ajouter anonyme ou l'auteur externe a un de mes tutos/article, ca me le refuse correctement. Je considere ce ticket comme ok.
