### ISSUE TITLE
Le sujet d'un tutoriel en bêta possède un titre trop long si le tutoriel a un titre d'une taille max

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2499]
Serveur : Bêta
Version : v1.7-RC2
Système : OS X
Navigateur : Google Chrome Version 41.0.2272.118 (64-bit)

Scénario :
- Créez un tutoriel avec un titre de la taille maximum.
- Placez le tutoriel en bêta et constatez que le sujet est bien créé.
- Tentez d'éditer le premier message du sujet.
- Validez l'édition et constatez qu'il signal que le titre est trop long d'un caractère.

**Comment by Eskimon** [comment]
C'est meme plus qu'un seul caractere... La limite de longeur pour un titre de tuto est de [80 caracteres](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/models.py#L51). Celle d'un sujet de [fofo idem](https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/models.py#L87). MAIS, la beta rajoute deux tags (`[beta][tutoriel]`)et un espace. On a donc 17 caractères de differences.

Je ne vois pas trop de solution simple pour corriger ca (a part augmenter la limite des titres de fofo a 100 caractères ?)

**Comment by GerardPaligot** [comment]
J'ai jamais compris pourquoi nous déduisons les tags à partir du titre. Pour moi, ça doit être un champ à part un peu à la StackOverflow.

**Comment by SpaceFox** [comment]
Ca, c'est une excellente idée d'evol !

2015-05-19 14:12 GMT+02:00 Gérard Paligot notifications@github.com:
