### ISSUE TITLE
Erreur récupération mot de passe

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#250]
Lorsque l'on tente de récupérer son mot de passe, si on rentre un mot de passe inexistant on a une erreur 404.

**Comment by SpaceFox** [comment]
Qu'entends-tu par "un mot de passe inexistant" ?

**Comment by devock** [comment]
Il faut lire "pseudo inexistant"... j'ai du zapper la relecture.

**Comment by firm1** [comment]
Fixé et mergé.

je ferme.
