### ISSUE TITLE
Les titres 2 dans le menu latéral ne sont pas affichés

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2500]
Serveur : Bêta
Version : v1.7-RC2
Système : Nexus 4
Navigateur : Google Chrome Version 41.0.2272.96

Scénario :
- Rendez-vous sur votre profil
- Affichez le menu latéral et constatez, par exemple, que vous ne voyez pas les sous sections "Tutoriels", "Articles" et "Forums" dans la section "Activité".

**Comment by firm1** [comment]
Celui ci est un doublon de je ne sais plus quelle issue. Je l'avais déclare
d'ailleurs

Le sam. 4 avr. 2015 01:17, Gérard Paligot notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
https://github.com/zestedesavoir/zds-site/issues/1683 qui date de novembre 2014 ?

**Comment by firm1** [comment]
Ouaip

Le sam. 4 avr. 2015 10:47, Gérard Paligot notifications@github.com a
écrit :
