### ISSUE TITLE
Impossible de contacter l'ensemble des auteurs d'une publication via l'action du menu latéral

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2501]
Serveur : Bêta
Version : v1.7-RC2
Système : OS X
Navigateur : Google Chrome Version 41.0.2272.118 (64-bit)

Scénario :
- Connectez-vous avec un membre avec les pouvoirs du staff.
- Rendez-vous sur la version hors ligne d'une publication avec plusieurs auteurs (par exemple, [celui-ci](http://beta.zestedesavoir.com/articles/41/bilan-de-la-premiere-semaine/))
- Cliquez sur l'action "Envoyer un MP aux auteurs".
- Constatez que seulement le dernier auteur figure dans les participants de la conversation.

**Comment by Eskimon** [comment]
Je suis pas staff, est-ce que tu reproduis aussi sur prod ou c'est propre a la v1.7 ?

**Comment by GerardPaligot** [comment]
En prod ça fonctionne, c'est une regression ici.

**Comment by Eskimon** [comment]
Ca vient de se commit je pense : https://github.com/zestedesavoir/zds-site/commit/ef9c7a555db7df9cddc84c74b418629ef930559c

**Comment by Eskimon** [comment]
PR en cours :)

**Comment by SpaceFox** [comment]
C'est corrigé, merci.
