### ISSUE TITLE
Le bouton "voir la version en ligne" n'est pas bien affiché dans le menu latéral

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2502]
Serveur : Bêta
Version : v1.7-RC2
Système : OS X
Navigateur : Google Chrome Version 41.0.2272.118 (64-bit)

Scénario :
- Rendez-vous sur la version hors ligne d'une publication publiée.
- Constatez que le bouton "Voir la version en ligne" n'est pas bien affiché.

![capture d ecran 2015-04-04 a 01 26 41](https://cloud.githubusercontent.com/assets/1913901/6990304/e4e63bce-da69-11e4-9431-4cd99f9a747d.png)

**Comment by Eskimon** [comment]
[Le template n'a pas l'air d'avoir ete edite](https://github.com/zestedesavoir/zds-site/commit/519bd37a6cc6e6f905f532e6b606bedef674f259) donc a priori ca viendrait du css de la classe "wide", cependant c'est curieux je n'ai pas le meme texte en beta et en prod' pour le meme vieux tuto...

**Comment by Situphen** [comment]
Ça a l'air effectivement d'être la classe "wide". C'est présent à d'autres endroits dans les tempates et je ne sais pas à quoi elle sert donc je me méfie.

**Comment by Eskimon** [comment]
Elle sert à afficher un texte dans sa version littéral sur les écrans larges si je dis pas de betises (documentation, tu me manques !)

**Comment by poulp** [comment]
La même sur le serveur bêta avec firefox : 

![deplacer](https://cloud.githubusercontent.com/assets/819246/7153215/aec080f8-e348-11e4-806c-b9849617744c.png)

**Comment by Situphen** [comment]
Voici la réponse que j'ai eu d'Alex-D (il y a quelques temps déjà) à mon message privé :

> Normalement ça sert à afficher une version courte et une version longue du texte selon la largeur d'écran. Ca ne fait qu'un simple display inline/none. Le line-height ne devrait pas être altéré par cette classe là.

En fait c'est tout simple à résoudre, une PR arrive bientôt !
