### ISSUE TITLE
drawer gauche gène le scroll sur mobile

### ISSUE THREAD

**Issue by ghost** [zestedesavoir/zds-site#2506]
Le drawer gauche apparaît dès que je scolle down (sur Nexus 5) et prend la place de tout l'écran.
Cela m'arrive souvent mais impossible de le prendre en vidéo car au moment ou je publie cette issue tout fonctionne.

**Comment by Situphen** [comment]
Tu veux parler du menu pour mobile ?

**Comment by Eskimon** [comment]
@forkmind quel navigateur/version ?

**Comment by ghost** [comment]
Firefox et Chrome. Tous les deux en dernière version. 
@Situphen Oui du menu pour mobile.

**Comment by Situphen** [comment]
Ça m'arrive aussi de temps en temps et du coup quand je scrolle avec mon doigt je le fais en diagonal pour éviter le problème :D

**Comment by WinXaito** [comment]
Maintenant que l'on parle de mobile, je me permet juste de dire que sur Windows phone ce n'est pas pratique quand on veut ouvrir le menu en faisant un scroll horizontal, car WP nous ramène sur la page précédente :p

**Comment by Situphen** [comment]
@WinXaito : bah dans ce cas là il y a le bouton ! ;)

**Comment by Situphen** [comment]
@WinXaito : Pour résumer, le problème est que quand tu veux ouvrir le menu en scrollant horizontalement, Windows Phone te ramène sur la page précédente ?

**Comment by GerardPaligot** [comment]
Je n'ai jamais eu aucun problème, cette issue est-elle encore pertinente ?

**Comment by Eskimon** [comment]
Perso sur OnePlus One Lollipop + Chrome j'ai le drawer qui pop lors d'un gros scroll mais qui reprend sa place correctement quand le scroll termine. Ca sent plus le bug du navigo que du site pour le coup.

Pour ce qui est des "gestes" de Windows Phone, on ne peut rien y faire (à part rappeler que le menu est aussi dispo en haut à gauche).

Du coup faute de mieux je ferme ici.
