### ISSUE TITLE
Passage à Django 1.8

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2507]
Django 1.8 étant sorti, ce serait pas mal qu'on attende pas la sortie de la 1.9 pour s'y mettre. Lundi soir, on s'arrange avec @GerardPaligot  pour merger la branche de la v1.7.

En première approche d'après le changelog, cette migration devrait être moins coton que celle vers Django 1.7.

Néanmoins, à savoir 2 choses à ce sujet :
- [Ce genre de gag](https://docs.djangoproject.com/en/1.8/releases/1.8/#django-conf-urls-patterns) va quand même faire un diff immonde qui sera ultra-chiant à rebaser, à voir avec les ZEP en cours.
- La v1.8 débloque le passage du moteur de templates à Jinja 2 (dans une autre PR), et là c'est bon pour les perfs :)

**Comment by pierre-24** [comment]
De toute façon, le rebase va être énorme (et chiant) quoiqu'il arrive, donc ça sert à rien de retarder l'échéance. Faites, les ZEP suivront (de force).

**Comment by artragis** [comment]
> à voir avec les ZEP en cours.

étant donné qu'on utilise les CBV, je dirais que la ZEP 12 aura un nombre très faible de problèmes. Typiquement simplement remplacer la première ligne par `[` et la dernière par `]`. Du moins j'espère avoir tout compris.

**Comment by SpaceFox** [comment]
# La migration est _bloquée_

Je ne peux plus avancer seul. La migration vers Django 1.8 **nécessite impérativement l'aide** de quelqu'un d'expérimenté pour avancer.

Cf [la PR pour les détails](https://github.com/zestedesavoir/zds-site/pull/2518).

**Comment by Situphen** [comment]
On peut enfin fermer ! \o/
