### ISSUE TITLE
Avertissement anti-déterrage de sujet

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2509]
Pour éviter que des sujets soient déterrer, on pourrait mettre en place un avertissement au dessus de l'éditeur quand la dernière réponse date d'un certain temps. Un peu comme ce que fait OpenClassrooms :

![capture d'écran de leur avertissement](https://pbs.twimg.com/media/CB8Gt2iWMAAoVU6.jpg)

(_Note :_ Il n'y a aucun filtre de couleur orange en réalité) Qu'en pensez-vous ?

**Comment by SpaceFox** [comment]
> Un peu comme ce que fait OpenClassroom

Tiens ? Ils ont implémenté cette fonctionnalité que le staff leur avait suggéré il y a au moins 5 ans maintenant ? C'est cool, et c'est une bonne idée.

En fait on ne l'a pas encore fait parce qu'on avait pas encore de sujets à déterrer. Je me demande s'il n'y a pas déjà une issue à ce sujet d'ailleurs.

**Comment by Situphen** [comment]
Je pense qu'on peut commencer à développer en place ce système, mieux vaut prévenir que guérir !

**Comment by pierre-24** [comment]
Ça me semble relativement facile à mettre en place, faut juste s'accorder sur la limite de temps.

**Comment by Eskimon** [comment]
> Je pense qu'on peut commencer à développer en place ce système, mieux vaut prévenir que guérir !

Dans l'ordre des priorités un système anti-bot sur la page d'inscription serait mieux avant (désactivable via le settings.py) ^^

Sinon a la louche je dirais que "3 mois c'est bien" :D (et au final sans gravite puisque ca n’empêche pas de poster...)

**Comment by Situphen** [comment]
Un système anti-bot c'est quand même bien plus complexe à mettre en place !

Trois mois ça me va perso.

**Comment by GerardPaligot** [comment]
Merci à @Situphen pour la feature et @pierre-24 pour la QA.
