### ISSUE TITLE
[Forum] Espaces insécables dans le contenu

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#251]
@firm1 a corrigé le problème des espaces insécables dans le contenu mais on a une erreur 404 si on envoi un contenu (que se soit lors de la création d'un sujet ou lors d'une réponse) qui ne contient qu'un espace insécable.

**Comment by SpaceFox** [comment]
Généralisation : un obtient une 404 lorsqu'un contenu ne contient pas de caractère imprimable.

**Comment by firm1** [comment]
Fixé, mergé
