### ISSUE TITLE
Relase 1.7 : le slug dans un mp incorect

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2510]
Version : Beta 1.7-RC2

Scénario : 
- J'ai crée un MP avec 1 participant "test"
- J'ai cliqué sur "Ajouter un membre" et j'ai rajouté "test2"
- L'url de mon MP est devenu : `http://beta.zestedesavoir.com/mp/3101/%3Cbound%20method%20PrivateTopic.slug%20of%20%3CPrivateTopic%3A%20test%3E%3E/messages/`

Il y'a donc un petit problème par là.

**Comment by Eskimon** [comment]
Je suppose que ca vient d'ici ? https://github.com/zestedesavoir/zds-site/pull/2424

( @SpaceFox on marque en milestone 1.7 pour s'y retrouver ?)

**Comment by GerardPaligot** [comment]
@Eskimon : Ce que tu link, c'est ma PR incomplète pour corriger l'erreur (qui avait déjà été remonté pour d'autres cas).

La correction du bug est extrêmement simple : changer `self.object.slug` en `self.object.slug()` [ici](https://github.com/zestedesavoir/zds-site/blob/01cc3534f09f19c94d0f6f0c1caebe70f47a4fbb/zds/mp/views.py#L205).

**Comment by Eskimon** [comment]
Ok super :) je tag facile du coup :)

**Comment by SpaceFox** [comment]
Par contre c'est bloquant si on ne peut plus utiliser les MP.

**Comment by GerardPaligot** [comment]
Non, non, on peut utiliser les MPs. Les slugs ne sont pas utilisés dans le back, c'est juste pour faire des URLs jolies ...

**Comment by Eskimon** [comment]
Réglé
