### ISSUE TITLE
l'url du détail d'un mp est incohérente

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2511]
Actuellement l'url d'un de mes message privé est la suivante : `http://beta.zestedesavoir.com/mp/3086/hey/messages/` autrement dit, le pattern est le suivant `http://beta.zestedesavoir.com/mp/<id>/<slug>/messages/`.

Intercalé l'id et le slug entre "mp" et "message" n'a aucune logique.

**Comment by firm1** [comment]
On a le même problème sur l'url d'édition d'un MP. ça ressemble a ça : `http://beta.zestedesavoir.com/mp/<id_mp>/<slug_mp>/messages/<id_post>/editer/`.

ça me semble particulièrement tordu aussi.

**Comment by GerardPaligot** [comment]
`/mp/` : J'entre dans la ressource des MPs
`/<id>/<slug>/` : Je récupère le MP donné
`/messages/` : Je récupère les messages du MP dans lequel je me trouve
`/<id>/` : Je récupère le message donné du MP dans lequel je me trouve
`/editer/` : Verbe pour savoir quoi faire.

Je ne vois rien d'incohérent et ça l'est par rapport à la ZEP sur ce même sujet : https://zestedesavoir.com/forums/sujet/2558/zep-26-rendre-les-urls-plus-coherentes/

**Comment by SpaceFox** [comment]
Je suis d'accord avec @GerardPaligot

**Comment by firm1** [comment]
Voici comment pour moi les urls devraient apparaitre.
- la liste des mps: `/mp/` (ça devrait même être au pluriel, mais passons)
- la liste des messages d'un mp : `/mp/messages/<id>/<slug>/`
- editer un message privé : `/mp/messages/editer/<id_message>/`

Il ne faut pas confondre url de site (elle doivent être un minimum lisible) et url de l'api.

**Comment by GerardPaligot** [comment]
La chose que tu décris, c'est plus ou moins ce qui est actuellement en prod et qui ne convient à personne.

**Comment by firm1** [comment]
Dans ce cas, je vais aller voir du coté du forum alors.

**Comment by GerardPaligot** [comment]
Histoire d'être clair, je n'ai rien contre re-changer les URLs des MPs, je ne veux simplement pas les changer 36 000 fois. Alors oui, je pense qu'en discuter sur les forums est une bonne idée pour se mettre d'accord définitivement.

**Comment by Eskimon** [comment]
Du coup il y a une décision finale ou besoin de débattre ?

**Comment by GerardPaligot** [comment]
Il y a besoin de débattre mais ça se passe sur ce [sujet](https://zestedesavoir.com/forums/sujet/2558/zep-26-rendre-les-urls-plus-coherentes/?page=2#p50732) des forums de ZdS.

**Comment by GerardPaligot** [comment]
Est-ce que cette issue est encore utile si l'idée de firm1 n'a pas été retenue et que @Situphen proposait une meilleure solution dans le cadre de sa ZEP sur la cohérence des URLs ?

**Comment by Eskimon** [comment]
Faute de nouveaux commentaires, ce ticket sera a fermer lors du prochain nettoyage.

**Comment by GerardPaligot** [comment]
Tiens, je suis en train de faire ce nettoyage. ^^
