### ISSUE TITLE
La pagination est affichée dans un MP avec une seule page

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2512]
Un MP qui contient au moins une réponse possède l'affichage de la pagination alors que le MP ne fait qu'une seule page. La pagination ne doit s'afficher que pour un nombre de page supérieur à 1.

C'est une regression, car on a pas le problème en prod.

**Comment by GerardPaligot** [comment]
Tu peux appuyer ton bug par une capture ? Je ne le comprends pas.

**Comment by firm1** [comment]
Avec une capture c'est mieux en effet : 

![alone-pagin](https://cloud.githubusercontent.com/assets/6066015/7026508/5b77cf2c-dd4a-11e4-8b2b-97781a5101ba.PNG)

**Comment by GerardPaligot** [comment]
Ok, je viens de comprendre pourquoi je n'arrivais pas à reproduire le bug. Il apparait uniquement quand il n'y a que 2 membres dans la conversation privée.

**Comment by SpaceFox** [comment]
Corrigé.
