### ISSUE TITLE
Enlever la notification lorsque l'on masque un message

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2515]
## Note : ne pas dev, sera dans la ZEP-24

Actuellement, lorsqu'un message est masqué, la notification associé reste. Ce qui veut dire que si un membre spamme les forums et que ses messages sont cachés du Staff, la boite à notification restera polluée !

Quelques extraits de log IRC :

> [Titi_Alone] phdphdphd a pollué le forum avec ses messages...
> [Titi_Alone] Faudrait une feature qui ne te notifie pas lorsque le message en question a été supprimé.
> 
> [Eskimon] Situphen, ticket sur quoi §
> [Eskimon] ?
> [Situphen] suppression de la notification lorsque le message est caché
> [Eskimon] ma foi c'est pas con comme evo ^^
> [AmarOk] +1
> [Xia] +2

**Comment by Situphen** [comment]
@ChantyTaguan ça pourrait être développé avec la ZEP 24 ?

**Comment by GerardPaligot** [comment]
Ah tiens, @gustavi avait dev cette fonctionnalité et je l'ai récupéré dans la ZEP-24. Je la link dans ma PR.
