### ISSUE TITLE
Bug aléatoire de Travis sur la branche de dev

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2519]
Depuis le passage sous django 1.7 en dev, la branche de dev est devenue instable, elle builde une fois sur deux.
- la PR en question #1905 son build n'est pas passé ([cf. travis](https://travis-ci.org/zestedesavoir/zds-site/jobs/57406674))
- la PR #2371 (qui n'a rien a voir avec l'erreur) à ensuite été mergée dans dev, et là travis est passé ([cf travis](https://travis-ci.org/zestedesavoir/zds-site/builds/57469834))
- la PR #2463 (qui n'a rien a voir non plus avec l'ereur) à été mergée, mais elle ne builde pas.

Et à chaque fois, l'erreur alétoire qui revient c'est : 

``` bash
ImproperlyConfigured: Application labels aren't unique, duplicates: mp
```

Je taggue l'issue comme bloquant, car il est bien embetant.

**Comment by SpaceFox** [comment]
J'ai changé le titre pour quelque chose de plus pertinent.

À noter que je n'arrive pas à reproduire ce comportement en local, que ce soit via tox ou directement en lançant les tests, et ce quel que soit le SGBD.

PS : Pendant les derniers travaux sur la branche de Django 1.7, j'avais l'impression que ça arrivait quand 2 builds existaient en parallèle. Comme si Travis n'isolait pas bien ses SGBD.

**Comment by GerardPaligot** [comment]
Est-ce que nous avons essayé de donner un autre nom au module `mp` ? https://docs.djangoproject.com/fr/1.7/ref/applications/#for-application-authors

**Comment by pierre-24** [comment]
Peut-être regarder à ceci:http://stackoverflow.com/questions/24319558/how-to-resolve-django-core-exceptions-improperlyconfigured-application-labels ? 

M'enfin, le fait que ça apparaisse une fois sur deux n'as aucun sens.

**Comment by SpaceFox** [comment]
Je connais ce lien depuis que j'ai vu ce bug, mais il n'aide en rien : je n'ai pas réussi à trouver de conflit de noms potentiel.

**Comment by pierre-24** [comment]
Je sais, j'ai regardé aussi. Le problème est que Google ne renvois que des solutions du genre --"

**Comment by SpaceFox** [comment]
A noter que ce problème [semblait avoir été réglé sur la PR #1905](https://github.com/zestedesavoir/zds-site/pull/1905) par le fait de demander à Travis de tester le front en 1 tâche et plus en 2 tâches en parallèle... mais il semble être revenu depuis.

J'ai l'impression, même si ça n'a aucun sens, que Travis isole mal ses BDD MySQL. Et que du coup quand on a 2 tests qui tournent sur la même base, le 2ème test pète.

J'ai aussi l'impression qu'on a un problème dans notre module de MP, puisqu'il semblerait que ce soit aussi lui qui fait chier dans la PR Django 1.8.

**Comment by GerardPaligot** [comment]
> J'ai aussi l'impression qu'on a un problème dans notre module de MP, puisqu'il semblerait que ce soit aussi lui qui fait chier dans la PR Django 1.8.

C'est ce que je me dis depuis hier soir.

**Comment by Eskimon** [comment]
Donc on peut fermer ici non ?

**Comment by GerardPaligot** [comment]
Tout à fait.

**Comment by firm1** [comment]
Toutafè

2015-04-16 17:05 GMT+02:00 Eskimon notifications@github.com:
