### ISSUE TITLE
[Article] Espaces insécables

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#252]
Alors il est possible de créer un article avec pour titre un espace insécable. Ca engendre deux problèmes : 
- Quand je valide la création de l'article, j'ai l'erreur suivante : 
  
  > OSError at /articles/nouveau
  > [Errno 17] File exists: '/opt/zdsenv/ZesteDeSavoir/articles-data/'
- Et quand j'essaye d'aller voir un article avec un titre vide j'ai une erreur 404, j'ai une url du genre : /articles/off/25/

**Comment by devock** [comment]
En fait, la première erreur est dû au fait qu'un article du même titre existe déjà, le bug est reproductible si vous écrivez deux articles avec le même titre (par exemple : "test", vu que j'ai déjà 2 articles portants ce nom), par contre l'article se créer bien.

**Comment by SpaceFox** [comment]
Même problème avec tous les caractères non-imprimables.

**Comment by SpaceFox** [comment]
@firm1 je pars du principe que tu as oublié d'enlever le "required = False" dans le champ text de ArticleForm après avoir ajouté le required dans les attrs du widget.

D'autre part, c'est volontaire la possibilité de créer des articles sans sous-catégorie ?

**Comment by SpaceFox** [comment]
On a le même bug dans le formulaire de création d'un topic. Je corrige tant que j'y suis.

**Comment by firm1** [comment]
C'est fixé, je ferme
