### ISSUE TITLE
Problème d'installation de la dépendance GeoIP

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2520]
La version de GeoIP ayant changée récemment, il s'agit maintenant d'un binding C à compiler. Le seul problème est que ça ne compile pas sur un mon OS Ubuntu 14.10.

La problème se règle en installant `sudo apt-get install libgeoip-dev`, mais il faut le préciser dans la documentation d'installation, ainsi que dans le fichier update.md dans les actions à réaliser.

Par ailleurs, je l'ai déjà souligné, mais il faudrait penser à mettre à jour la documentation Windows pour ce paquet.

**Comment by Luthaf** [comment]
Idem pour OS X, j'ai du installer geoip via homebrew pour réussir à tester la PR #2462, avec `brew install geoip`.

**Comment by Eskimon** [comment]
Merfi @pierre-24 et tout les autres !

**Comment by pierre-24** [comment]
Un merci tout spécialement à @Situphen ;)

**Comment by Situphen** [comment]
> Un merci tout spécialement à @Situphen ;)

A votre service !
