### ISSUE TITLE
On ne distingue plus les sujets non lus et les sujets lus dans la sidebar

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2521]
Jusqu'ici on arrivait à faire la différence entre un sujet non lu (en gras) et un sujet lu, parmi les topics que l'on suit en regardant la sidebar.

Depuis la v1.7 (actuellement en beta), la graisse n'est plus présente sur les sujets non lu, alors qu'on voit toujours qu'il le sont dans les notifications.

Une capture pour expliquer (j'ai 3 topics non lu, et pas de graisse) : 

![perte de graisse](https://cloud.githubusercontent.com/assets/6066015/7049269/87f5c184-de18-11e4-820a-6ae74f98403d.PNG)

**Comment by SpaceFox** [comment]
Corrigé.
