### ISSUE TITLE
Paramètre "Afficher les signatures des autres membres" obligatoire

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#253]
Le paramètre "Afficher les signatures des autres membres" est obligatoire, on ne peut pas le décocher. 
Est-ce que la fonctionnalité est en place ? Si oui, il faut corriger le bug, si non, on peut envisager de supprimer le paramètre dans un premier temps.

**Comment by SpaceFox** [comment]
Ça a été corrigé par quelqu'un ? Je ne reproduis pas :(

**Comment by firm1** [comment]
Quand je l'ai regardé ce bug, en fait pour le reproduire il faut decocher
les 2 cases (mail et signature), Il accepterra pas.

**Comment by devock** [comment]
Toujours présent. Peut-être une précision qui a son importance : c'est un compte membre et non staff.

**Comment by SpaceFox** [comment]
On est d'accord pour dire que la fonctionnalité n'est pas en place et que pour l'instant je masque l'option ?

**Comment by firm1** [comment]
Ça prend autant de temps de masquer l'option que de mettee la
fonctionnalité en place (rajouter une condition dans le template
topic.html).

Donc je préfère qu'on corrige le bug si possible quand même.

**Comment by SpaceFox** [comment]
OK je fais ça alors

**Comment by firm1** [comment]
C'est corrigé. 
Je ferme.
