### ISSUE TITLE
La version mobile n'est pas adapté à la taille de l'écran venant de Feedly

### ISSUE THREAD

**Issue by ghost** [zestedesavoir/zds-site#2533]
La version mobile n'est pas adapté lorsque je veux voir la suite d'un article en cliquant sur un lien dans mon lecteur de flux RSS : l'affichage est celui d'un desktop. Cela n'advient pas lorsque je vais sur le site directement depuis un navigateur.

**Comment by Situphen** [comment]
~~Quel est ton lecteur RSS ?~~ Je n'ai rien dit, c'est marqué dans le titre ^^

Je teste ça ma semaine qui arrive.

**Comment by Situphen** [comment]
Ça s'adapte très bien sur le site http://feedly.com ! Tu utilises le site ou une des applications ?

**Comment by Situphen** [comment]
@forkmind : Up !

**Comment by Situphen** [comment]
@forkmind : Up up !

> Ça s'adapte très bien sur le site http://feedly.com ! Tu utilises le site ou une des applications ?

**Comment by GerardPaligot** [comment]
D'après @Situphen, le RSS s'affiche très bien depuis feedly.com. Je ferme.

Libre à @forkmind de réagir à ce dernier ping.
