### ISSUE TITLE
Virer les banni et non-activé de la liste des membres

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2534]
Afin d'être le plus transparent possible à l'égard de la communauté, n'afficher que les membres réellement actif (donc pas les banni ni les non-activé) serait plus précis et pertinent.
Fatalement le site perdra quelques membres (probablement une petite dizaine de multi et de banni, je ne sais pas pour les non-activé) mais ça me semble "intellectuellement honnête".

TODO:
- [x] Supprimer les inactifs de la liste ( #2611 )
- [x] Supprimer les bannis de la liste
- [x] Supprimer les robots de la liste

**Comment by SpaceFox** [comment]
Pour info, les stats là tout de suite c'est :
- 2051 membres actifs "normaux"
- 17 bannis
- 1 membre en lecture seule
- 2 membres bannis _et_ en LS
- 153 comptes inactifs

**Comment by Eskimon** [comment]
Donc sur 2224 membres on en a 153 inactifs et 17 bannis, ce qui fait presque 7.5% du total des membres.

**Comment by firm1** [comment]
Dans la liste, il faudrait peut être aussi ne pas afficher les bot ? Car par définition ce ne sont pas des membres.

**Comment by GerardPaligot** [comment]
@Eskimon Pourquoi tu n'as pas fais la requête pour les 3 conditions dans ta PR ? :)

**Comment by Eskimon** [comment]
Parce qu'à l'époque je voyais pas comment simplement virer les membres d'un groupe ou selon certaines conditions ^^ Faudra que je reregarde (sauf si qqun sait et peut le faire rapidement, ca se passe ici : https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/views.py#L47

**Comment by Eskimon** [comment]
Voila qui est fait !
