### ISSUE TITLE
Documentation : installation de zds sous GNU/Linux

### ISSUE THREAD

**Issue by francoisthire** [zestedesavoir/zds-site#2536]
Je viens de faire l'installation de zds en suivant cette [documentation](http://zds-site.readthedocs.org/fr/latest/install/backend-linux-install.html).

Premièrement, la phrase qui dit que _les commandes sont génériques et indépendantes de la distribution_ est clairement fausse. Puisque les commandes et les paquets listés utilisent apt-get donc c'est pour Debian et ses dérivées. Il faudrait plutôt dire que c'est pour des distributions dérivées de Debian.

Second point, il manque une dépendance qui est geoip : `apt-get geoip` .

**Comment by Eskimon** [comment]
> Second point, il manque une dépendance qui est geoip : apt-get geoip 

Yep, c'est en cours de correction sur la PR #2526 :)

**Comment by pierre-24** [comment]
Je suis "pas d'accord" avec toi, Saroupille, sur le second point: apt-get, quand il installe "libgeoip-dev", installe automatiquement "geoip" (ou alors, ton apt-get est pas normal, mais c'est [dans les dépendances du paquet](https://packages.debian.org/sid/libgeoip-dev), et je prend l'exemple de débian par facilité mais c'est pareil chez Ubuntu). 

Pour le premier point ... Moui, je vais changer ça.

**Comment by pierre-24** [comment]
PS: sous Debian, le paquet "geoip" n'existe pas.

**Comment by pierre-24** [comment]
@Saroupille : [j'ai tenu compte de tes remarques ici](https://github.com/pierre-24/zds-site/blob/661beac3964221e62f3137998eb4b4a604842725/doc/source/install/backend-linux-install.rst), n'hésites pas à me dire si ça ne te convient pas ou si tu trouves que c'est pas clair :)

**Comment by SpaceFox** [comment]
Le lien en bas de page est HS.

**Comment by pierre-24** [comment]
Bien vu :)

**Comment by pierre-24** [comment]
... Changé.

**Comment by francoisthire** [comment]
@pierre-24 : Pour le petit commentaire, oui. Pour ma part, sur arch, certains noms de paquets sont différents (mais par chance ils devaient être déjà installés). 

Pour le paquet sous arch c'est bien geoip. Sous debian, ya un paquet geoip-bin ça doit être ça non ?

**Comment by pierre-24** [comment]
C'est ça, mais comme je dis, il est en dépendance du paquet `*-dev`, donc ça m'étonne que tu doives explicitement l'installer sous une autre distribution (quoique je peux comprendre la logique derrière). Dans tout les cas, j'ai donc rajouté un test pour être sur que geoip est installé, si tu pouvais me confirmer qu'il fonctionne, ce serai super (c'est simplement essayer `geoiplookup zestedesavoir.com`). D'avance merci :)

**Comment by francoisthire** [comment]
Yep, niquel !

**Comment by pierre-24** [comment]
Ah, t'as été trop vite, ici ;)

On a pour habitude de ne fermer une issue que si la PR correspondante (la mienne dans ce cas) est mergée, ainsi on peut "suivre" les problèmes et leur résolution. Donc si tu pouvais la réouvrir, ce serait cool.

**Comment by pierre-24** [comment]
(quelqu'un se chargera de la fermer quand ce sera bon, je te rassure)

**Comment by Eskimon** [comment]
Et voila !
