### ISSUE TITLE
[version 1.7] On ne peut plus télécharger l'archive de son propre tutoriel si celui-ci n'est pas en bêta

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2542]
En direct de la bêta de ZdS; comme le titre l'indique : 

![Avec bêta](https://cloud.githubusercontent.com/assets/7889675/7143005/bf45f564-e2aa-11e4-81c1-ee557987b5c8.png)
Image: Avec bêta

![Sans la bêta](https://cloud.githubusercontent.com/assets/7889675/7143014/d2c4273c-e2aa-11e4-90b4-e031594e1c2d.png)
Image: sans bêta

**Comment by pierre-24** [comment]
Je demande par ailleurs auto-assignation.

**Comment by Eskimon** [comment]
Voila !!

**Comment by pierre-24** [comment]
J'ai rien dit, en fait #2371 s'occupe déjà de ça, ce sera pour la version suivante. Vivement que cette v1.7 soit mergée, je mélange tout --"
