### ISSUE TITLE
Site inaccessible

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2543]
Bonsoir,

je ne sais pas si je poste à la bonne place, mais le site est inaccessible. Erreur 500 en montrant le code source du template.

http://cloud.winlap.ch/pic/402.jpg

Bonne soirée.

**Comment by WinXaito** [comment]
Ah edit, toute mes excuses. Je viens de voir que ça a été corrigé !

**Comment by GerardPaligot** [comment]
Salut @WinXaito,

Merci pour ticket. En fait, il s'agit de la mise en production de la version 1.7 de ZdS.

Elle est maintenant terminée, tout est revenue à la normale.

@SpaceFox Faudrait d'ailleurs penser à une page de maintenance un jour.

**Comment by SpaceFox** [comment]
Y'a une page de maintenance... qui fonctionne tant que la MEP ne m'explose pas à la tronche.

Parce que oui, la MEP m'a **encore** explosé à la tronche.

**Comment by WinXaito** [comment]
Ok je vois ;) 
(Juste par curiosité, les grands site on aussi se genre de problème lors de la mise en prod de nouvelle version de leur site ? Genre facebook, google, ... ?)

**Comment by pierre-24** [comment]
Aïe. Ça sens le post explosif sur le forum dev', ça.

**Comment by SpaceFox** [comment]
Non, c'est juste NPM qui a planté lors d'une MAJ... la routine quoi

**Comment by SpaceFox** [comment]
@WinXaito Non, ils ont des infras (chères) qui permettent la MEP sans interruption de service. Les moyens peuvent aussi se permettre les MEP en heures creuses (mais y'a pas moyen que je me lève à  5h du mat pour faire ça)

**Comment by pierre-24** [comment]
Bon, bon. Je vais voir ce que je peux faire pour #2482 ...

**Comment by WinXaito** [comment]
Je comprend tout à fait !
Merci. Vous pouvez clore se post :)
