### ISSUE TITLE
Problème d'affichage de la bannière cookies sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2544]
Voir la capture

Navigo : Firefox

![tmp_11463-screenshot_2015-04-14-22-08-05943782424](https://cloud.githubusercontent.com/assets/6066015/7146316/fc5485fe-e2f2-11e4-8d14-4052bdd70106.png)

**Comment by SpaceFox** [comment]
Oooooh de la QA en prod ;)

**Comment by Eskimon** [comment]
On a une idée du pourquoi/comment résoudre ? Ca peut peut-être intéressé @Alex-D de savoir ca si ca peut se reproduire chez lui sur d'autres sites qu'il gère.

**Comment by pierre-24** [comment]
C'est corrigé, merci @Situphen :)
