### ISSUE TITLE
Pouvoir éditer le titre d'un message privé

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2545]
Il est devenu impossible d'éditer le titre d'un message privé. En éditant le premier post on tombe sur le même formulaire que n'importe quel post alors que l'on devrait pouvoir éditer le titre !

**Comment by SpaceFox** [comment]
Je ne suis pas sûr que ça a jamais été possible d'éditer le titre d'un MP.

**Comment by Situphen** [comment]
Ah en effet sur la 1.6 on ne pouvait pas non plus !

Bah du coup je propose qu'on met en place cette fonctionnalité car actuellement si on se trompe dans le titre on ne peut pas se corriger...

**Comment by poulp** [comment]
doublon de #2393

**Comment by GerardPaligot** [comment]
Ouaip, je ferme ici.
