### ISSUE TITLE
Changer le middleware de sécurité

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2547]
Django 1.8 arrive avec un nouveau middleware de sécurité : https://docs.djangoproject.com/en/1.8/ref/middleware/#django.middleware.security.SecurityMiddleware

A voir ce qui peut nous intéresser là-dedans.

**Comment by SpaceFox** [comment]
En attente du merge de Django 1.8 : https://github.com/zestedesavoir/zds-site/pull/2546

**Comment by GerardPaligot** [comment]
La nouvelle PR de Django 1.8 : https://github.com/zestedesavoir/zds-site/pull/3331

**Comment by vhf** [comment]
Encore d'actualité @GerardPaligot @SpaceFox ?

**Comment by gustavi** [comment]
Pas mal de trucs sympas niveau sécu, à creuser pour voir ce qui peut m'intéresser et qui ne ferait pas doublon avec ce que fait nginx.

**Comment by Situphen** [comment]
Pas besoin car nginx s'en occupe déjà.
