### ISSUE TITLE
[Django 1.8] Nouvelle manière d'initialiser les données des tests

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2548]
Django 1.8 arrive avec une nouvelle manière d'initialiser les tests : https://docs.djangoproject.com/en/1.8/releases/1.8/#testcase-data-setup

Je ne sais pas si ça pourrait nous intéresser.

**Comment by SpaceFox** [comment]
En attente du merge de Django 1.8 : https://github.com/zestedesavoir/zds-site/pull/2546

**Comment by pierre-24** [comment]
À première vue, je dirais ... Au cas par cas, mais très probablement.

**Comment by GerardPaligot** [comment]
Nouvelle PR de Django 1.8 : https://github.com/zestedesavoir/zds-site/pull/3331

**Comment by vhf** [comment]
Encore d'actualité @GerardPaligot @SpaceFox ?

**Comment by GerardPaligot** [comment]
Oui, sans doute.

**Comment by gustavi** [comment]
Pour avoir fait des tests sur zds.gallery ça veut dire réécrire énormément de nos tests car « Be careful not to modify any objects created in setUpTestData() in your test methods. Modifications to in-memory objects from setup work done at the class level will persist between test methods. If you do need to modify them, you could reload them in the setUp() method with refresh_from_db(), for example. » donc je ferme ça, ça ne change pas grand chose pour nous.
