### ISSUE TITLE
[Django 1.8] Simplifier la gestion des droits

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2549]
Django 1.8 permet à `has_perm()` et `has_module_perm()` de lever directement des `PermissionDenied`  ce qui pourrait simplifier notre gestion des droits.

Cf https://docs.djangoproject.com/en/1.8/releases/1.8/#django-contrib-auth

**Comment by SpaceFox** [comment]
En attente du merge de Django 1.8 : https://github.com/zestedesavoir/zds-site/pull/2546

**Comment by GerardPaligot** [comment]
Nouvelle PR de Django 1.8 : https://github.com/zestedesavoir/zds-site/pull/3331

**Comment by vhf** [comment]
Encore d'actualité @GerardPaligot @SpaceFox ?

**Comment by gustavi** [comment]
En fait faut refaire le système des droits proprement. Ça prendra un peu plus de temps mais ça évite de mettre du scotch un peu partout dans notre code à chaque fois.

**Comment by gllmc** [comment]
Maintenant que #4181 est ouverte, cette issue est obsolète, non ?

**Comment by pierre-24** [comment]
Maintenant, oui. T'as l'oeil ;)
