### ISSUE TITLE
[Django 1.8] Utiliser les nouveaux patterns d'URL

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2551]
Django 1.8 déprécie le système de patterns d'URL actuel pour le remplacer par un beaucoup plus simple et logique : https://docs.djangoproject.com/en/1.8/releases/1.8/#django-conf-urls-patterns

Il faudra s'y mettre. C'est très simple (ça peut presque se faire entièrement à coup d'expressions régulières) mais :
1. Il ne faut pas oublier de modifier _tous_ les `reverse`
2. Ça touche à peu près tous les fichiers... donc il faudra bloquer tout merge quand la PR sera en cours pour éviter des conflits ultra-chiants.

**Comment by SpaceFox** [comment]
En attente du merge de Django 1.8 : https://github.com/zestedesavoir/zds-site/pull/2546

**Comment by pierre-24** [comment]
À noter que le modèle CBV (class based view) demande déjà une telle construction, ce qui signifie qu'il n'y aura pas besoin de le faire sur les modules ou l'API est déjà passé, ni sur article/tuto quand la ZEP-12 sera arrivée.

**Comment by GerardPaligot** [comment]
Nouvelle PR de Django 1.8 : https://github.com/zestedesavoir/zds-site/pull/3331

**Comment by GerardPaligot** [comment]
@gustavi Tu n'as pas fais cette modification partout ?

**Comment by gustavi** [comment]
Oui c'est fait depuis un moment ça.
