### ISSUE TITLE
Galerie : Le formulaire d'ajout d'utilisateur est très moche

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2552]
Une image vaut mieux que mille mots:

![screenshot from 2015-04-15 09 03 38](https://cloud.githubusercontent.com/assets/761168/7153627/53bcb8ce-e34e-11e4-8728-04f3d49d7dc5.png)

 (screenshot pris en version 1.7 et problème déjà présent en 1.6)

**Comment by firm1** [comment]
C'est un doublon de je ne sais plus quelle issue que j'avais créé

**Comment by Eskimon** [comment]
Trouve ! https://github.com/zestedesavoir/zds-site/issues/2311
