### ISSUE TITLE
Galerie : On ne peut pas supprimer un utilisateur

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2553]
Si on ajoute qqun a une galerie, on ne pourra plus le supprimer ou modifier ses droits Lecture/Ecriture ensuite.

**Comment by poulp** [comment]
Du coup comment ça se passe au niveaux des droits, doit-on créer un niveau supérieur ?
- Lecture : voir la galerie
- Ecriture : voir/modifier la galerie
- Owner : voir/modifier la galerie + gestion des utilisateurs

**Comment by Eskimon** [comment]
Dans un premier temps "KISS" en gardant juste R/W non ? Celui qui a le droit d’écriture a reçu la confiance du contrib original pour pouvoir gérer la galerie et donc ajouter d'autres personnes.

Dans un second temps le "owner" (administration) serait effectivement pas une mauvaise idée je pense.

**Comment by Eskimon** [comment]
@poulp tu avais deja pas mal travaille la dessus, tu pourrais reprendre une partie peut-etre non ? https://github.com/zestedesavoir/zds-site/pull/1309

Sinon je ferme ici, ce ticket est un doublon de https://github.com/zestedesavoir/zds-site/issues/839
