### ISSUE TITLE
Galerie : On ne peut pas renommer une galerie

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2554]
Tout est dans le titre, on ne peut pas renommer une galerie.

**Comment by pierre-24** [comment]
... Et si, avec #2505, on peut ;)

**Comment by Eskimon** [comment]
TU es sur ? De ce que je me rappel en faisant la QA : "Le back le peut mais le front le propose pas" c'est ca ?

**Comment by poulp** [comment]
Je viens de tester et on peut changer titre/sous-titre de la galerie via un formulaire d'édition.

**Comment by poulp** [comment]
Par contre il y a une faute : `Éditer la gallerie`

**Comment by Eskimon** [comment]
J’essaierai de faire une PR ce soir pour corriger ca si personne ne la fait avant :) ( @poulp peut-etre ;) ?)

**Comment by Eskimon** [comment]
et bien voila, c'est fait :)
