### ISSUE TITLE
Galerie : Miniature qui subsiste après suppression d'images

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2555]
Si je supprime une image de ma galerie, la source est bien supprimée du disque mais pas les miniatures apparemment, et donc ça bouffe de l'espace disque pour des trucs "fantômes".

**Comment by SpaceFox** [comment]
Il me semble que ces miniatures sont gérées comme un cache. Par contre il faudrait voir la doc pour confirmer et savoir comment invalider.

**Comment by pierre-24** [comment]
Ping @firm1 pour easy_thumbnails ?

**Comment by Eskimon** [comment]
J'ai regardé un peu cet aprem, j'ai rien vu parlant de cache (mais j'ai lu en diagonale), par contre c'est certain dans le code on fait absolument rien pour les virer puisqu'on se contente juste de virer l'original. Bref, je regarde pour corriger ca ce weekend :)

**Comment by pierre-24** [comment]
Corrigé et mergé, je ferme :)
