### ISSUE TITLE
MP : Gros souci d'affichage

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2556]
[Via PG06](https://zestedesavoir.com/forums/sujet/2861/mp-de-plusieurs-pages/):

Les MPs de plusieurs pages ont un gros problème : à chaque page, le premier message de la page apparait, puis la totalité des messages s'affiche entièrement (de la première page à la dernière) sans discontinuité. Donc dès que le nombre de pages est important le chargement est très lent et pour ceux qui n'ont pas un PC très puissant (comme moi) tout ralentit voire se fige.

Et si on essaye de retrouver un message via son lien, on tombe sur une erreur 404 puisque la notion de "page" n'existe plus.

Eskimon: Ce problème vient du déploiement de la version 1.7 ?

@GerardPaligot une idee de pourquoi ?
@SpaceFox c'est très problématique pour certains utilisateurs et franchement pénible en général. On passe en bloquant ?

**Comment by GerardPaligot** [comment]
Oui, je sais d'où vient le problème. La pagination, c'est vraiment casse pied quand tu veux récupérer le dernier message de la page précédente ... J'avais fais des tests pour être sûr que ça fonctionne, j'avais demandé à la QA de créer plusieurs pages mais il semble que c'est quand même passé à travers.

Je m'en charge ce soir.

PS : C'est tellement long à charger que ça en devient bloquant. J'ai rajouté le tag.

**Comment by SpaceFox** [comment]
Je confirme le côté bloquant, surtout que je sais qu'il existe des très très longs MP (et encore, je pense ne pas être dans un des plus longs).

**Comment by GerardPaligot** [comment]
Faut donner une version ici pour la milestone ?
