### ISSUE TITLE
MP et pagination : Plusieurs bugs

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2557]
Dans la liste des MP
- Les fleches precedente/suivante ne marche plus
- Mais cliquer sur un nombre marche (c'est deja ca)
- Mais l'affichage du nombre de la page actuelle est inexistant (cf capture ci-dessous)

@GerardPaligot je suppose que la aussi tu as des idées ^^

---

![Page 8 sélectionnées dans les mps](https://cloud.githubusercontent.com/assets/761168/7159744/a2568498-e384-11e4-8346-11a297132729.png)
Page 8 sélectionnées dans les mps

---

![Sur le forum](https://cloud.githubusercontent.com/assets/761168/7159740/994fc684-e384-11e4-827a-1e5808baef01.png)
Page 9 sélectionnées dans les mps

**Comment by GerardPaligot** [comment]
Je ne sais pas si c'est un bug du back ou du front.

**Comment by Eskimon** [comment]
Vu que ca touche que les MP (apparemment) et qu'on a eu un refacto la dessus, j'aurais tendance a dire back...

**Comment by GerardPaligot** [comment]
Le code est refactorisé du côté back et front. Donc sûrement (parce que à ma connaissance personne n'a touché à la pagination à part moi) mais faut confirmer.

**Comment by GerardPaligot** [comment]
Dans tous les cas, c'est une régression.

**Comment by GerardPaligot** [comment]
Faut fermer avec une version donnée ici pour la milestone ?
