### ISSUE TITLE
Problème d'affichage dans les sujets suivis

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2561]
Je me suis retrouvé avec un problème de rendu dans la zone des sujets suivis.

![bug_pause](https://cloud.githubusercontent.com/assets/6066015/7177075/1dcff7e0-e424-11e4-81e7-15b75e207df8.PNG)

C'est la première fois que je vois ce bouton à cet endroit sur un sujet que je follow. Le sujet était pourtant ouvert au moment ou j'ai fait la capture.

**Comment by Eskimon** [comment]
J'avais eu des delires pareils a l'epoque ou les outils front marchait pas si bien (lol), c'etait du a un sprite mal genere ou une bricole du genre je sais plus (mais la ce serait bizarre de pas avoir deux fois la meme icone)

**Comment by Alex-D** [comment]
Le soucis doit être lié à ça : http://zestedesavoir.com/static/sprite@2x.png (err 404)

**Comment by Eskimon** [comment]
@firm1 tu confirmes que ce n'est plus là maintenant que le front est rentré dans l'ordre ?

**Comment by firm1** [comment]
Je n'ai pas revu ce problème depuis, je suppose donc que c'était la faute au front mal généré. Je ferme donc
