### ISSUE TITLE
Erreur d'encodage et validation de tuto qui plante

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2563]
Lors de mes récentes QA, j'ai voulu importer - valider - publier le tuto Irllicht qui est dans les fixtures.
Je suis donc sur dev avec mes requirements à jour.
Quand je veux cliquer sur valider, ca commence a mouliner puis m'envoi bouler avec l'erreur et la stacktrace suivante:

`UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 65: ordinal not in range(128)`

`The string that could not be encoded/decoded was: la générat`

```
Internal Server Error: /tutoriels/validation/valid/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/eskimon/Documents/ZestedeSavoir/zds/member/decorator.py", line 25, in _can_write_and_read_now
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/eskimon/Documents/ZestedeSavoir/zds/tutorial/views.py", line 351, in valid_tutorial
    (output, err) = mep(tutorial, tutorial.sha_validation)
  File "/home/eskimon/Documents/ZestedeSavoir/zds/tutorial/views.py", line 3262, in mep
    html_file.write(emarkdown(md_file_contenu, is_js))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 65: ordinal not in range(128)
```

Je tag bloquant car c'est critique si la publication se vautre à cause des caractères accentués. si qqun peut reproduire ce serait cool, mon environnement ayant tellement été secoué avec toutes mes QA et les récents changements que l'on ne sais jamais...

**Comment by Eskimon** [comment]
Bon je ne comprends pas. J'ai essayé de refaire un tuto simple (big tuto avec peu de chose, juste une partie, un chapitre, deux exraits) et en mettant des accents un peu partout sur les titres et les contenus ainsi que dans les messages de commits et ça passe. Je ne comprends pas.

**Comment by firm1** [comment]
Peut-être la fonction d'import qui fait mal son job ?

**Comment by Eskimon** [comment]
Aucune idée, pourtant on y a pas touché depuis longtemps et elle marchait bien avant oO

**Comment by cgabard** [comment]
Tu as le contenu exact de la partie de tuto qui pose problème ? Dans la version du markdown utilisé actuellement sur le site des accents dans les liens peuvent générer ce problème. Si c'est ça, j'ai fais un hotfix ce matin et la toute derniere version de python-zmarkdown n'a plus le bug. Par contre on est pas à l'abris d'une autre erreur de ce genre.

Il faudrait réussir a isoler l'extrait qui pose problème.

**Comment by Eskimon** [comment]
J'ai essayé avec ton update de ce matin et c'était pas mieux. Je ne sais pas exactement quel extrait pose souci, vous pouvez reproduire avec le big tuto des fixtures (désolé je dois me sauver !)

**Comment by pierre-24** [comment]
C'est d'autant plus étonnant que, de tête, ce tuto fait partie des test lancés par Travis à chaque fois. Je teste ça plus tard.

**Comment by Eskimon** [comment]
@pierre-24 tu as pu tester ?

**Comment by pierre-24** [comment]
#oups :p

**Comment by pierre-24** [comment]
Corrigé par #2588 et #2607 !!!

**Comment by SpaceFox** [comment]
Si ça a été corrigé par le hotfix, c'est dans la v1.7.
