### ISSUE TITLE
Impossible de se connecter à l'administration

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2564]
Quand on visite `127.0.0.1:8000/admin/` en étant pas connecté, on recois cette erreur

> You're using the Django "sites framework" without having set the SITE_ID setting. Create a site in your database and set the SITE_ID setting to fix this error.

... Elle disparaît quand on se connecte avec un compte admin via le site.

**Comment by Eskimon** [comment]
Est-ce vraiment un problème ?

**Comment by pierre-24** [comment]
Bah je le dis surtout parce que ça pourrais venir d'un problème plus profond (je me souviens avoir vu @SpaceFox parler à plusieurs reprises de `SITE_ID`)

**Comment by SpaceFox** [comment]
Je pensais l'avoir corrigé ce truc ?!

Tu es sur quelle version ?

**Comment by pierre-24** [comment]
À priori `upstream/dev`, dernière du nom.

**Comment by WinXaito** [comment]
Ne faut t'il pas rajouter quelque chose comme (Dans le settings.py)

``` python
SITE_ID = 1
```

(Toutes mes excuses si je dis des bêtises, je suis en train d'apprendre django et python. Je me dis que pour progresser un bon moyen est de suivre vos conversation et regarder le code ...)

**Comment by pierre-24** [comment]
Peut-être. Sinon, une autre idée, c'est tout simplement qu'il y a pas la bonne fixture au bon endroit ^^

**Comment by Eskimon** [comment]
Ca semble bien fonctionner maintenant (surement via https://github.com/zestedesavoir/zds-site/pull/2605 ), je ferme
