### ISSUE TITLE
Intégrer linthub au projet

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2568]
Toujours dans un but d'augmenter notre qualité de code, j'aimerais proposer linthub qui, en 2 mots,  un outil qui ajoute des commentaires dans le code source d'une PR pour signaler toutes les petites fautes que ferait le contributeur.

Vous pouvez retrouver toutes les informations utiles sur le [site internet](https://linthub.io/) de l'outil avec des démos sur le rendu d'une PR.

Je ping nos 2 gestionnaires @Eskimon et @SpaceFox.

**Comment by SpaceFox** [comment]
Un peu comme Landscape/Flake8 mais en plus clair non ?

**Comment by GerardPaligot** [comment]
C'est un peu l'idée mais ça concerne que le code précis de la PR alors que flake reste sur tout le projet et landscape ... bah j'ai jamais trop compris sa portée.

**Comment by Eskimon** [comment]
En tout cas sur leur [PR de démo](https://github.com/linthubot/linthub-demo/pull/1) ca a de la gueule...

**Comment by Eskimon** [comment]
Bref, je dirais bien "pourquoi pas", au moins c'est plus clair que landscape car l'information vient a nous clairement plutôt que d'aller la chercher sur landscape ou le résumé Travis. Du coup si on fait ca je propose de garder flake tout de même pour pas qu'on aille merger les PR trop sales et éventuellement virer landscape a un moment ou a un autre

**Comment by GerardPaligot** [comment]
Ok, je testerais l'outil la semaine prochaine et je donnerais un feedback sur cette issue.

**Comment by Situphen** [comment]
Je suis pour aussi ! Il faut par contre vérifier que pour le JS il utilise bien notre configuration de JSHint (le fichier `.jshintrc` de notre dépôt et pas le sien).

**Comment by firm1** [comment]
@GerardPaligot ton test à donné quelque chose ?

Je le vois plus comme une alternative à landscape. flake8 lui reste toujours necessaire. La seule chose que je n'arrive pas à savoir c'est jusqu'ou va l'intégration de linthub avec le code python. Landscape à la particularité de creuser vraiment profondément et on peut même lui passer nos requirements pour cadrer l'analyse. Est-ce que linthub est-il aussi fin ?

PS : c'est le genre de discussion qui a sa place plutôt dans la dev-zone je pense.

**Comment by GerardPaligot** [comment]
> @GerardPaligot ton test à donné quelque chose ?

Je suis en contact avec le développeur de l'outil. D'après la [documentation](http://docs.linthub.io/), il est possible de remonter des commentaires par rapport aux standards : flake8 pour [Python](http://docs.linthub.io/user/configuration/#Python) et JSHint pour [JS](http://docs.linthub.io/user/configuration/#Javascript) mais pas encore de spécifier nos propres spécifications héritées des standards. Il va le faire prochainement.

> Je le vois plus comme une alternative à landscape.

Tout à fait. Il faudra juger si LintHub est un bon outil et s'il est plus pertinent que landscape. Flake8, lui, reste dans le projet.

> PS : c'est le genre de discussion qui a sa place plutôt dans la dev-zone je pense.

Pour moi non justement parce que nous parlons d'une fonctionnalité pure GitHub qui n'intéresse pas les membres de ZdS.

**Comment by Eskimon** [comment]
@GerardPaligot Tu avais pu teste un peu ou pas ? On fait quoi de ce ticket ?

**Comment by GerardPaligot** [comment]
Le gars de linthub semblait emballé qu'un projet comme le notre s'intéresse à son projet puis plus de réponses à mes e-mails et je n'ai ni le temps, ni trop l'envie de me pencher sur la question.

**Comment by GerardPaligot** [comment]
Cela dit, je reste convaincu de l'utilité de l'outil.

**Comment by Eskimon** [comment]
C'est vrai que ca a l'air sexy comme truc. C'est complique a intégrer ? On peut faire un test sur genre quelques semaines et voir comment ca se comporte

**Comment by GerardPaligot** [comment]
A l'époque, j'avais fais un test super rapide pour afficher des erreurs PEP8 sur une branche (https://github.com/GerardPaligot/zds-site/pull/15) mais non concluante. Après, j'avais vraiment pas cherché beaucoup.

**Comment by Eskimon** [comment]
Euh... elle est ou leur doc ?

**Comment by GerardPaligot** [comment]
Leur e-mail :)

**Comment by Eskimon** [comment]
Je partais pour dire ca "Arf... On veut vraiment essayer d’intégrer un truc avec pour dos "leur email" ?" puis j'osais tellement pas croire que c'etait possible que je suis retourner sur leur GH pour enfin trouver ca... http://docs.linthub.io/

**Comment by Eskimon** [comment]
Ca fait un peu peur la liste des autorisations demandées (même si je suppose qu'elles sont justifiées) et leur page d'explication a ce sujet envoie évidemment sur une 404...

**Comment by GerardPaligot** [comment]
Ah oui, j'avais oublié cette page. Sorry. Faut dire, elle est bien cachée.

**Comment by Eskimon** [comment]
Bon, des motivés pour ca ou pas ?

**Comment by Eskimon** [comment]
Je ferme ce ticket, je pense que parti comme on est personne ne s'occupera de ca.
