### ISSUE TITLE
Lenteur sur le site ?

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2569]
Bonjour,

Le chargement d'une page met entre 3 et 30 sec à se charger. C'est assez random.

Je suis le seul ?

**Comment by Eskimon** [comment]
Nop, c'est global et c'est lié à l'hébergement, pas au site en lui même donc on peut malheureusement pas y faire grand chose :(

Du coup je ferme le ticket car il n'est pas lié au code ;) (on attend des nouvelles d'OVH)
