### ISSUE TITLE
Les top tags ne sont pas triés

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2572]
Les top tags ne sont pas triés correctement. Pour reproduire le problème, créer des sujets avec des tags et vérifier que les top tags ne sont pas triés correctement.

**Comment by Eskimon** [comment]
define: triés correctement (dans quel ordre ?)

**Comment by DevHugo** [comment]
Logiquement, le tag le plus utilisé devrait être en premier et ainsi de suite. D’après ce que je comprend du code. Mais c'est pas le cas. L'algorithme le trie en fonction de l'id à cause du bug

**Comment by GerardPaligot** [comment]
J'ai une PR mergée qui link cette issue. Qu'est ce qu'il en est @artragis et @DevHugo ?

**Comment by DevHugo** [comment]
Je pense que artragis à résolu le souci avec sa PR. Tu peux donc fermer.
Le 13 févr. 2016 1:26 PM, "Gérard Paligot" notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
J'attends juste la confirmation de @artragis alors. :)

**Comment by artragis** [comment]
En effet ça devrait être bon.

**Comment by GerardPaligot** [comment]
Merci à vous 2 !
