### ISSUE TITLE
Error 500 en navigant sur le site

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2580]
Bonsoir,

se soir en navigant sur le site, je me retrouve avec une Erreur 500.
En réactualisant c'est tout bon. J'ai donc essayer quelques fois d'actualiser le site et de naviguer dessus. J'ai eu 4 erreur 500. (3 sur la page d'accueil, 1 sur la page article).

WinXaito

**Comment by Eskimon** [comment]
Yep ca arrive quand un des process gunicorn se plante (le plus dur est de trouver pourquoi). Ca se fait rare cependant ces temps-ci ^^ @SpaceFox et/ou @firm1 vous pouvez relancer et avez une idée de ce qui s'est passé ?

**Comment by SpaceFox** [comment]
C'est relancé depuis un moment mais je ne sais pas ce qui s'est passé.

**Comment by Eskimon** [comment]
J'ai cru comprendre que c'est une validation couplée à la dernière mise a jour du markdown (*.6) qui aurait fait ça.

**Comment by Correus80** [comment]
Bonjour,
Meme probleme en voulant consulter les sujets suivants:
Capteurs analogiques et la suite
Même en réactualisant, l'erreur 500 survient toujours.
Merci

**Comment by WinXaito** [comment]
> Correus80 commented just now  
> Bonjour,
> Meme probleme en voulant consulter les sujets suivants:
> Capteurs analogiques et la suite
> Même en réactualisant, l'erreur 500 survient toujours.
> Merci

En effet, ceci n'est pas le même type d'erreur.
C'est une erreur causé par le tutoriel (Si je ne dis pas de bêtise).  

Je ne saurai retrouver le post qui traite ceci @Eskimon @SpaceFox 

[edit] Lien: https://zestedesavoir.com/tutoriels/820/la-fabrication-numerique/1079/arduino/4455/semaine-4-capteurs-analogiques/

**Comment by Eskimon** [comment]
On sait que les 500 viennent de la validation qui plantent à cause de https://github.com/zestedesavoir/zds-site/issues/2584 , du coup je ferme ici car ce ticket ne nous apprendra rien de plus ^^
