### ISSUE TITLE
Petite correction (Front-End si je ne dis pas de bêtise ?)

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2581]
Bonsoir,

Il faudrait ici changer l'année, également le montant (Qui est de 20€ si je ne me trompe pas ?)

![Problème avec l'année](http://cloud.winlap.ch/pic/403.jpg) #C'est moi ou les images ne fonctionne pas ?

L'url du coup: [Image du problème](http://cloud.winlap.ch/pic/403.jpg)

(Et je ne suis pas sur de se que j'ai mis dans le titre, je suis dans le monde de git et Github depuis pas longtemps. Donc j'essaye de placé les mots que je lis, style Front-End, Back-end, ... comme je le perçois.)

**Comment by Eskimon** [comment]
Les images fonctionnent normalement...

Sinon tu arrives une douzaine d'heures trop tard, la correction est déjà parti en route ce matin :D https://github.com/zestedesavoir/zds-site/pull/2577

Je ferme donc ici :)
