### ISSUE TITLE
La barre des cookies ne disparaît pas

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2582]
La barre des cookies ne disparait pas quand on clique sur le bouton ok, et elle n'est pas designée non plus.

CF. capture

![capture du 2015-04-22 00 06 11](https://cloud.githubusercontent.com/assets/6066015/7263651/d314e602-e883-11e4-9369-e97e0d29c8f2.png)

**Comment by SpaceFox** [comment]
Tu as **encore** un problème de cache (testé et validé sur les 2 environnements).

Par contre, ce que je ne pige pas, c'est que dans mes souvenirs on avait fait une PR pour activer le mode "les ressources ont un ID qui change à chaque MAJ pour éviter les problèmes de cache", justement.

Quelqu'un sait pourquoi ça ne fonctionne pas / plus ? cc @Situphen @sandhose .

PS : "Encore" pour le fait que ça revienne alors que ça devrait pas, pas pour toi.

**Comment by Situphen** [comment]
> Quelqu'un sait pourquoi ça ne fonctionne pas / plus ?

C'est sûrement dû aux changements de versions v1.7 --> v1.7b --> v1.6c --> v1.7b...

**Comment by SpaceFox** [comment]
@firm1 ton problème était en prod ou en bêta ?

**Comment by AlexRNL** [comment]
De mon côté, j'ai eu le problème sur la prod hier, qui s'est bien résolu avec le vidage du cache.

**Comment by firm1** [comment]
Le problème était en prod. Vraiment bizarre cette histoire de cache, en raffraichisant maintenant il s'en va.

A fermer du coup

**Comment by SpaceFox** [comment]
Pas forcément : j'ai l'impression que le système prévu pour gérer ces problèmes de cache est HS.

Exemples de ressources utilisées en front :
- https://zestedesavoir.com/static/images/clem-home-quote.png
- https://zestedesavoir.com/static/css/main.min.css

Ça m'a tout l'air d'être des URLs directes.

**Comment by SpaceFox** [comment]
Ah ben oui c'est normal : cette ligne https://github.com/zestedesavoir/zds-site/blob/dev/update.md#issue-1724 a été commentée en prod...

**Comment by SpaceFox** [comment]
Corrigé : j'ai réactivé la conf correcte.

**Comment by SpaceFox** [comment]
Vous voulez rire ? Ça a aussi corrigé l'utilisation bizarre de Memcached. Visiblement, cette fonctionnalité de Django utilise le cache...
