### ISSUE TITLE
Les erreurs markdown stoppent la publication

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2584]
N'importe quelle erreur markdown, entraînant l'apparition du message `Une erreur est survenue dans la génération de texte Markdown. Veuillez rapporter le bug.` dans un article/tutoriel bloque le processus de génération et génère des possibles erreurs 500. [Voir un exemple ici](https://zestedesavoir.com/forums/sujet/2942/erreur-500-sur-la-page-daccueil/?page=1#p52981) !

**Comment by artragis** [comment]
(pas un bug, une régression)

**Comment by Eskimon** [comment]
Et voila ce sera corrigé au moins en 1.8, par contre on fait comment pour la prod @pierre-24 ?

**Comment by pierre-24** [comment]
#2588 règle le problème, donc ton tuto passe.

**Comment by pierre-24** [comment]
Corrigé par #2588 et #2607.

**Comment by SpaceFox** [comment]
Même remarque que dans l'autre : si c'est corrigé dans le hotfix, c'est dans la v1.7.

**Comment by pierre-24** [comment]
Toutàfé, mes excuses. Par contre... Cette milestone n'existe pas/plus, donc je met rien ?

**Comment by SpaceFox** [comment]
Elle existe, il faut aller la chercher dans "fermées".

**Comment by pierre-24** [comment]
Merci :)
