### ISSUE TITLE
L'objet du mail de création d'un MP n'est pas le meme que celui de la réponse

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2586]
Le bug est visible depuis la version 1.7 de zds en prod. Lorsqu'on reçoit le mail de création d'un MP, l'objet du mail s'intitule "Zeste de savoir - blabla" alors que les objets des réponses s'intitulent "ZdS - blabla" ce qui crée deux fils de discussion inutiles dans les boites mails.

Il faudrait aligner les objets pour un meme MP.

**Comment by Situphen** [comment]
Il faut juste changer `['abbr']` par `['litteral_name']` sur [cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/zds/mp/views.py#L399) !

**Comment by pierre-24** [comment]
Corrigé et mergé ;)
