### ISSUE TITLE
Les noms de domaines supplémentaires de ZdS ne redirigent pas sur le NDD principal

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2589]
zestedesavoir.com a d'autres noms de domaines supplémentaires tels que `zestedesavoir.net`, `zestedesavoir.org`, `zestedesavoir.fr` et autres jouyeusetés.

Le problème c'est que les autres domaines sont censé rediriger sur le nom de domaine principal. Ce n'est pourtant pas le cas. ça ressemble a un problème d'infra, donc je taggue en conséquence.

**Comment by Situphen** [comment]
~~La redirection fonctionne bien en HTTPS même si il y a une erreur "Connexion non certifiée".~~

On accède bien à Zeste de Savoir via ".org", ".net" et ".fr" en HTTPS même si il y a une erreur "Connexion non certifiée". Par contre, c'est un accès direct, sans redirection !

**Comment by Axylium** [comment]
Pour ma part, sous Firefox quand je tente d'accèder à un autre des domaines que le `.com` je me mange une 404 de nginx !

**Edit :** Je viens de tilter. J'suis sans le https sur ces domaines. En le rajoutant, je tombe sur le même comportement que @Situphen

**Comment by WinXaito** [comment]
En effet, on peu accéder avec le https. Par contre étrange, si je met le "www", je me choppe une _connexion non certifié_ par contre avec le https mais sans le "www", le site s'affiche bien.

Sans redirection bien entendu

**Comment by firm1** [comment]
J'ignore si c'est à cause de [cette action](https://github.com/zestedesavoir/zds-site/issues/2658#issuecomment-100891144), mais cette issue à évoluée.

Maintenant, en http les redirections fonctionnent bien, cependant, en https, la redirection ne se fait jamais, si j'étais sur une `.org` ma naviguation continue en `.org` au lieu de me rediriger sur le `.com`.

L'impact n'égatif est que coté SEO on se tire des balles dans le pied car on se crée des duplicate content de nous même. J'aurai tendance à le trouver grave comme problème.

**Comment by Situphen** [comment]
Je plussoie que c'est assez bloquant !

**Comment by firm1** [comment]
Du coup je rajoute le tag bloquant ici.

Une fois qu'on est sanctionné par Google ça sera difficile de se refaire notre SEO

**Comment by Eskimon** [comment]
ping @Ge0 :)

**Comment by Situphen** [comment]
Up ! Il y a un risque que ça nous plombe notre référencement !

Par exemple, si on recherche ["zeste de savoir" avec Qwant](https://www.qwant.com/?q=zeste%20de%20savoir) on obtient :
- "zestedesavoir.com" ;
- "https://zestedesavoir.fr" ;
- "https://zestedesavoir.fr/api/".

La première est bonne mais les deux autres ne devraient pas exister !

**Comment by firm1** [comment]
Coup de théatre, l'issue a à nouveau changé de forme (qu'est ce qui s'est passé ?)

Maintenant : http:/zestedesavoir.[fr|net|org] redirige bien vers le .com 

Le problème restant est que **https**:/zestedesavoir.[fr|net|org] ne fait pas de redirection. Donc les moteurs de recherche, ils considèrent qu'il s'agit d'un site différent, et peuvent donc pénaliser ces noms de domaines là.

L'issue est toujours bloquante donc.

**Comment by GerardPaligot** [comment]
Cette issue est-elle bloquante par rapport à la release 15.5.1 ?

**Comment by Situphen** [comment]
C'est séparé de la _release_ mais ça reste bloquant !

**Comment by Situphen** [comment]
Du coup, @Ge0 tu aurais le temps de remettre ces redirections? Si Ge0 ne peut pas, qui pourrait le faire ?

**Comment by Eskimon** [comment]
ping @Un-Cornichon :) (ou @sandhose si tu as des idées :) )

**Comment by Situphen** [comment]
Ça a été résolu et ça fonctionne bien donc on peut fermer ! :)

**Comment by Eskimon** [comment]
Tu es sur ? Car aller sur le .net en HTTPS merdouille j'ai l'impression

Date: Sun, 27 Sep 2015 02:01:20 -0700

**Comment by Situphen** [comment]
> Tu es sur ? Car aller sur le .net en HTTPS merdouille j'ai l'impression

Car on n'a pas de certificats pour les domaines supplémentaires ! Ce serait une amélioration à apporter effectivement.

**Comment by ghost** [comment]
Il est possible d'acheter des certificats multi-domaines, mais tout de suite ce n'est plus du tout le même budget, et sinon pour tous les autres domaines on peut prendre le temps d'en générer des gratuits cher starttls, ou encore mieux d'attendre https://letsencrypt.org/
