### ISSUE TITLE
[Bêta v1.8] Les flux rss ne fonctionnent plus => erreur 500

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2590]
En direct de la beta, il est impossible d'avoir les flux rss en cliquant sur les liens correspondant. On se prend une erreur 500.

C'est donc une regression, puisque ça marche en prod.

**Comment by DevHugo** [comment]
https://github.com/zestedesavoir/zds-site/issues/2564, j'ai exactement la même erreur, quand j'essaye d’accéder au flux en local.

«You're using the Django "sites framework" without having set the SITE_ID setting. Create a site in your database and set the SITE_ID setting to fix this error.»

Ajouter SITE_ID=1 marche mais aucune idée des conséquences.

**Comment by SpaceFox** [comment]
On dirait un effet de bord merdique de [ce commit](https://github.com/SpaceFox/zds-site/commit/c4605fd1997e478128b6e1cdf831637862293832). J'espère juste que l'on peut faire fonctionner ces RSS sans avoir besoin de ce paramètre.

**Comment by SpaceFox** [comment]
PS : Si vous pouviez indiquer quelque chose comme "bêta v1.8" dans le titre, ce serait génial.

**Comment by DevHugo** [comment]
Source: https://docs.djangoproject.com/en/1.8/ref/contrib/sites/#how-django-uses-the-sites-framework

En gros, ce que j'ai compris de la documentation, c'est que c'est pas obligatoire mais fortement conseillé de l'utiliser ce module multi-site, même quand on a un seul site comme nous.

> Although it’s not required that you use the sites framework, it’s strongly encouraged, because Django 
> takes advantage of it in a few places. 

En gros, il précise après que c'est utilisé pour le RSS pour deux choses, pour établir les urls si on précise pas l'adresse complète, ce qui est notre cas. C'est aussi utilisé pour le title et la description. 
C'est aussi utiliser pour d'autre trucs, je te laisse lire le petit paragraphe.

Pourquoi un ? car c'est l'id dans la base de données de l'enregistrement ou y'a les infos du domain et du nom. La table s’appelle: django_site.

**Comment by Eskimon** [comment]
Réglé, merci @SpaceFox !
