### ISSUE TITLE
[beta 1.8] Le fichier sitemaps est devenu indisponible => erreur 500

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2591]
url incriminée : `http://beta.zestedesavoir.com/sitemap.xml`

On obtient une erreur 500, ce qui est fort dommage pour notre SEO. C'est une regression et ça me semble très bloquant. Je taggue en conséquence.

Je pense que c'est lié au même problème que #2590

**Comment by Eskimon** [comment]
Réglé, merci @SpaceFox !
