### ISSUE TITLE
Les légendes des tableau ne sont plus intérpretées

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2595]
Via [Ymox sur le forum](https://zestedesavoir.com/forums/sujet/2981/legendes-de-tableaux-plus-rendues-correctement/): 

> J'ai constaté un comportement qui m'interpelle. En train de changer quelques éléments dans les FAQs PHP et Symfony, j'ai voulu modifier un message avec un tableau, et ce dernier avait une légende. Le code Markdown est le suivant :
> 
> ```
> **Valeur**|`isset($a)`|`empty($a)`
> ---|---|---
> `$a = ''`|**`true`**|**`true`**
> `$a = 1`|**`true`**|`false`
> `$a = 0`|**`true`**|**`true`**
> `unset($a)`|`false`|**`true`**
> `$a = ' '`|**`true`**|`false`
> `$a = 'a'`|**`true`**|`false`
> `$a = null`|`false`|**`true`**
> `$a = false`|**`true`**|**`true`**
> `$a = true`|**`true`**|`false`
> Table:**Table de vérité**
> ```
> 
> Code:Le Markdown incriminé
> (...)
> 
> J'ai aussi essayé de mettre une ligne vide entre le tableau et la "légende", mais du coup, j'ai le tableau puis une ligne 
> 
> Table:**Table de vérité**
> 
> Ce n'est pas bloquant le moins du monde, mais je trouve juste un peu ennuyeux  ;)
> Source:[Ymox](http://zestedesavoir.com/forums/sujet/2981/legendes-de-tableaux-plus-rendues-correctement/?page=1#p53682)

**Comment by Eskimon** [comment]
C'est un problème markdown, je ferme ici.
