### ISSUE TITLE
Lien de l'API

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2596]
Bonjour,

peut-être que je me trompe, mais il me semble que la dernière fois que j'avais regarder, ce n'étais pas comme ça.

Le lien dans le footer nous amène ici: https://zestedesavoir.com/api/ ... pas très explicite comme message. Qui nous donne ensutie une url pour aller ici: https://zestedesavoir.com/api/api-docs/ On peut voir dans "apis", que nous avons a disposition l'API des membres: https://zestedesavoir.com/api/membres/ 

Pour le dernière lien indiquer, pas de problème, mais je me demandais si nous devions pas possèder une clé pour obtenir ces informations ?

Sinon ensuite on voit le champs <next> qui nous indique cette url: http://zestedesavoir.com/api/membres/?page=2 Mais qui amène tout de même sur la page 1.

Je sais que l'API est en cours de dev, mais je me demandais tout de même si c'étais normal d'avoir ceci en prod.

WinXaito

**Comment by GerardPaligot** [comment]
Salut,

Je n'ai pas compris toutes tes questions alors je vais répondre à 2 que j'ai compris :

> Pour le dernière lien indiquer, pas de problème, mais je me demandais si nous devions pas possèder une clé pour obtenir ces informations ?

C'est un peu comme si tu disais que nous devrions être connecté pour aller sur [cette page](https://zestedesavoir.com/membres/) qui liste les membres du site (pas à travers l'API). Nous avons fais le choix de mettre des informations publiques et privées, la liste des membres est une information publique mais nous ne donnons pas toutes les informations.

> Sinon ensuite on voit le champs qui nous indique cette url: http://zestedesavoir.com/api/membres/?page=2 Mais qui amène tout de même sur la page 1.

Vu les récents problèmes du serveur et du cache qui ont encore continué par après, je ne serais pas étonné qu'il faut faire quelque chose niveau serveur sur le cache. ping @SpaceFox

**Comment by Eskimon** [comment]
Du nouveau pour ce sujet ?

**Comment by WinXaito** [comment]
> Sinon ensuite on voit le champs qui nous indique cette url: http://zestedesavoir.com/api/membres/?page=2 Mais qui amène tout de même sur la page 1.

J'ai remarqué que par moment ça fonctionnais, un problème de cache je dirais ... (En fait je viens de remarquer que c'est ce qu'a dit @GerardPaligot)

Sinon rien de plus pour ma part.

**Comment by SpaceFox** [comment]
En fait les problèmes de cache n'avaient aucun rapport avec l'API.

**Comment by GerardPaligot** [comment]
Non mais depuis ces perturbations, il y a des problèmes de cache avec l'API (les problèmes qu'on avait avant que je fasse évoluer le code pour spécifier des clés sur l'API pour le cache si tu te souviens).

En gros, en prod, que tu fais une requête pour avoir la première page des membres (par exemple) et que tu fais une seconde requête pour avoir la seconde page, il te renvoie toujours la première.

**Comment by Situphen** [comment]
On en est où ici ? Je n'arrive pas à comprendre le problème !

**Comment by GerardPaligot** [comment]
https://github.com/zestedesavoir/zds-site/pull/2761 devrait régler le problème de cette issue.

**Comment by Situphen** [comment]
#2761 a été reprise par @Eskimon en #2816 donc je ferme !
