### ISSUE TITLE
Ancre sur le premier message d'une page X

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2599]
Lorsque l'on change de page via le bouton suivant (ou page x), la nouvelle page chargée commence tout en haut, avec le header étou. Ca serait sympa de commencer avec le premier message de la nouvelle page pour pas avoir a scroller (surtout sur mobile)

**Comment by GerardPaligot** [comment]
Tu es certain que tu veux cette fonctionnalité ? Parce que soit tu salis le back (bidouiller la liste des messages de la pagination ou faire des requêtes supplémentaires), soit tu salis le front avec des conditions pour savoir si une variable potentielle existe.

Tout ça pour dire que je suis ne suis pas un fan de cette fonctionnalité.

**Comment by Eskimon** [comment]
Ouai je vois. En soit c'est pas dramatique hein, j'avais pas pensé que ce serait si contraignant. Je laisse plus de gens s'exprimer puis je fermerait si personne ne parle...

**Comment by martinqt** [comment]
Bonjour, je débarque donc veuillez excuser mon éventuelle mauvaise idée.

Vu que le premier message de chaque page (à part la première) est une "redite" et qu'il porte la classe CSS `repeated`, il ne serait pas possible à l'endroit où la classe est ajoutée de mettre en plus un `id` du genre `first`?

**Comment by Eskimon** [comment]
> Vu que le premier message de chaque page (à part la première) est une "redite" et qu'il porte la classe CSS repeated, il ne serait pas possible à l'endroit où la classe est ajoutée de mettre en plus un id du genre first?

C'est pas con du tout ca (et `last` quand on revient en arriere ?). A voir comment integrer ca :)

**Comment by pierre-24** [comment]
Dans quelle mesure est ce que cette issues est pertinente ? Pour les contenus, c'est le cas, et pour les fofos bwah ...

**Comment by vhf** [comment]
J'y vois pas un grand avantage, je propose qu'on ferme. (Au passage, l'implémentation à coup d'ajouter des `id` était peut-être une idée valide à l'époque, mais ce serait une boucherie maintenant. Chaque message a déjà un `id`.)

**Comment by pierre-24** [comment]
Bon ;)
