### ISSUE TITLE
Force slug uniqueness in URLs

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#26]
Je ne suis pas certain du fonctionnement de Django et de ZdS ici, mais j'ai l'impression qu'il manque un `unique=true` dans [cette ligne de code](https://github.com/Taluu/ZesteDeSavoir/blob/master/zds/forum/models.py#L67).

J'ai bon ou pas ? Si la contrainte d'unicité n'est pas respectée, et que deux forums de titres identiques sont créés dans une catégorie, a priori ça va merder (ok, c'est un cas tordu, mais ça mange pas de pain de faire ça propre).

(N.B : si oui, le cas se présente peut-être dans d'autres entités.)

Par ailleurs, j'ai une autre question : c'est pas un peu crade de créer une URL de type `/forums/sujet/<id>/<slug>` ?

Par exemple, on peut accéder au sujet http://www.zestedesavoir.com/forums/sujet/1/bienvenue-sur-zds en rentrant [n'importe quoi à la place du slug](http://www.zestedesavoir.com/forums/sujet/1/c-la-fete-issi). Là encore, je ne fais que supposer et j'espère me tromper, mais je pense que point de vue SEO, ça ne plaira pas aux bots.

**Comment by GerardPaligot** [comment]
Je tiens à dire que le slug n'est pas unique non plus pour les tutoriels.

**Comment by SpaceFox** [comment]
Personnellement je me limiterais à des URLs style /forums/sujet/<id>.
Mais je ne sais pas ce que ça implique en terme d'expérience utilisateur et
de SEO (normalement "plus rien" pour ce dernier point).

**Comment by firm1** [comment]
Les urls ont été codés de telle façon que le slug ne soit pas unique pour donner la possibilité à plusieurs topic d'avoir le même nom. On ne peut pas se permettre de ne passer que des urls du type `/forums/sujet/<slug>` parce que j'ai plus confiance en faisant une recherche (jointure) sur un id plutot que sur un slug.

>  Si la contrainte d'unicité n'est pas respectée, et que deux forums de titres identiques sont créés dans une catégorie, a priori ça va merder

A priori non, parce que l'id précède le slug dans l'url

> on peut accéder au sujet http://www.zestedesavoir.com/forums/sujet/1/bienvenue-sur-zds en rentrant n'importe quoi à la place du slug. 

Oui, parce qu'on se base uniquement sur l'id, le slug est là juste pour donner une indication visuelle pour celui qui lit l'url ou pour le SEO. en sachant que si tu tapes  `http://www.zestedesavoir.com/forums/sujet/1/bi` tu es redirigé sur la bonne url.

**Comment by Coy0te** [comment]
Non, pour les forums il n'y a pas d'id dans l'url, juste un slug : http://www.zestedesavoir.com/forums/site-web/html-et-css/

En ce qui concerne les URLs des sujets, je comprends tout à fait l'intérêt d'un id face à un slug, je me demande simplement si c'est pas un peu crade. Mais si les redirections effectuées sont des 301, perso ça me va, c'est ok niveau SEO.

**Comment by firm1** [comment]
> Non, pour les forums il n'y a pas d'id dans l'url, juste un slug : http://www.zestedesavoir.com/forums/site-web/html-et-css/

Oui, ça c'est parce que les forums ne sont pas crée par n'importe qui et uniquement via l'interface d'admin et on est certains de ne pas créer deux forum du même nom/slug.

> Mais si les redirections effectuées sont des 301, perso ça me va, c'est ok niveau SEO.

Ce sont bien des 301.

**Comment by Taluu** [comment]
> > Non, pour les forums il n'y a pas d'id dans l'url, juste un slug : http://www.zestedesavoir.com/forums/site-web/html-et-css/
> 
> Oui, ça c'est parce que les forums ne sont pas crée par n'importe qui et uniquement via l'interface d'admin et on est certains de ne pas créer deux forum du même nom/slug.

Never trust user input ! Même si on connaît bien les types aptes à faire ce genre de modifs. Le système de slug (tout court, sans id) avec un champ unique est pas trop mal ; si l'url existe déjà, alors un détrompeur peut être ajouté (`bienvenu-sur-zds-2`). Garder un id qui est normalement destiné à un usage _interne_ (sinon bonjour le bruteforce pour tomber sur tous les topics) ne _devrait_ pas être dévoilé... !

**Comment by firm1** [comment]
Le truc c'est que les forums et catégories, sont crée directement via l'interface d'admin et le slug est saisi carrément à la main. Donc de coté, impossible de merder vu qu'on ira jamais au dela de 30 forums dans toute notre existence. si on mets un id dans cette url `http://www.zestedesavoir.com/forums/site-web/html-et-css/` ça sera illisible.

Pour les topics,si on ne mets pas d'id, en sachant que le slug bouge en même temps que le titre du topic, il faudra faire une requête de plus à chaque création/modification. 

C'est vraiment si sale que ça pour vous les id dans l'url des topic ? parce que je vois pas mal de forum qui mettent leur id dedans aussi.

**Comment by Taluu** [comment]
Bah ca n'empêche pas le bruteforcing sur les urls ! Qui m'empêche de tenter d'accéder au topic 3 ? au 4 ? Qui me dit pas que c'est dans la corbeille / un forum privé ?

OK y'a les droits qui se chargeront de ça, mais ça reste un risque assez grand quand même !

Et de plus, faire une requête en plus lors de la création / modification n'est pas non plus insurmontable (on parle pas de 20 requêtes, on parle d'une requête), qui est faite par rapport à la lecture genre 1/10000 au bas mot... Donc c'est pas ça qui fera tomber un serveur.

L'idée est d'éviter de rentrer les slugs à la main, car ce n'est pas le but d'un slug. Il est censé être unique / généré automatiquement selon une ou plusieurs colonnes (ici, le nom du forum / nom du topic). Osef qu'il puisse être changé, surtout modifier le titre d'un sujet est peut-être 1/100000 modifications (donc par rapport à la lecture, le calcul ne se fait même plus).

**Comment by SpaceFox** [comment]
Pour moi, ce qui est sale, c'est cette manie de ne _pas_ mettre d'IDs dans
les URLs.

Le "tout au slug" date de l'époque où l'URL était importante pour le SEO,
ce qui n'est plus le cas.
Se baser sur un slug pur pour retrouver un topic n'apporte, de mon point de
vue, que des inconvénients :
- Le topic est introuvable si renommé (cf le OCR). OK c'est rare, mais
  c'est tellement chiant quand ça arrive...
- C'est beaucoup plus consommateur en terme de ressources BDD (gestions de
  strings au lieu d'entiers à chaque lecture)
- On est obligés de faire des fonctions compliquées pour garantir le slug
  unique même quand les gens font des titres identiques ou avec des
  caractères pourris.

> Bah ca n'empêche pas le bruteforcing sur les urls ! Qui m'empêche de
> tenter d'accéder au topic 3 ? au 4 ? Qui me dit pas que c'est dans la
> corbeille / un forum privé ?

Et qu'est-ce qu'on en a à faire qu'il essaie d'accéder au topic 3 ou 4 ?
Il y a une vérification des droits qui est là pour ça : si l'attaquant
tombe sur un topic auquel il n'a pas accès... ben il n'y aura pas accès. Il
aura juste gagné une URL. La belle affaire.

> OK y'a les droits qui se chargeront de ça, mais ça reste un risque assez
> grand quand même !

Je ne vois vraiment pas où il y a un risque. Les droits sont là pour ça. La
sécurité par l'obscurité, c'est juste inefficace.

Le 20 décembre 2013 11:18, Baptiste Clavié notifications@github.com a
écrit :

**Comment by firm1** [comment]
> Pour moi, ce qui est sale, c'est cette manie de ne _pas_ mettre d'IDs dans
> les URLs. 

On est d'accord, c'est pour ça que je préfère mettre l'ID (pour les raisons que tu cites) et le slug (pour l'utilisateur qui sait à la vue de l'url de quoi parle le topic).

Pour le reste je suis d'accord avec Spacefox, les droits sont préférables de ce point de vue pour gérer la sécurité.

**Comment by Taluu** [comment]
Enfin je pense quand même que le slug ne devrait pas être rentré à la main sur les forums / catégories. Et je trouve pas ça homogène de ne pas avoir d'id dans les forums et en avoir dans les topics du coup, mais bon, osef je suppose...

**Comment by Coy0te** [comment]
Même avis que SpaceFox ici, sur tous les points qu'il a relevés.

À côté de ça je reste convaincu que faire confiance au mec du staff pour la création d'un forum ou d'une catégorie, c'est pas très judicieux. Placer un simple `unique=true`dans le SlugField des Models du forum et des catégories, ça ne coûte rien et ça permettra au moins que le mec se mange une exception si jamais il se trompe. C'est d'autant plus simple qu'on s'en fout que ce soit pas géré de manière user-friendly, l'important est juste de pas pouvoir se retrouver avec deux slugs identiques.

**Donc pour résumer, je suis ok pour garder les URL comme elles sont actuellement, mais je pousse pour que tu rajoutes l'unicité sur les SlugField de Forum et Categorie.**

**Comment by firm1** [comment]
> À côté de ça je reste convaincu que faire confiance au mec du staff pour la création d'un forum ou d'une catégorie, c'est pas très judicieux

C'est pour ça que le staff n'as pas accès à l'admin django. Seul les élus pourront créer des catégories/forum. Mais en soit tu as raison, rajouter un unique = True pour ces cas là, ne mange pas de pain. je tacherai de le faire dans mon prochain commit.

**Comment by Taluu** [comment]
Je pense également qu'il faut laisser le slug se générer automatiquement (j'essaye aussi vraiment de pousser ce point) par rapport au nom du forum (et pourquoi pas de sa catégorie parente)

**Comment by firm1** [comment]
> Je pense également qu'il faut laisser le slug se générer automatiquement

ça nécessite de 1h de developpement (back+front+tests) pour une feature qui ne sera utilisée que pendant 30 minutes (1min par forum)  dans toute l'existence de ZdS. 

C'est typiquement le genre de chose que je classe genre N°134 dans ma liste de chose à faire. :-)
