### ISSUE TITLE
[beta 1.8] La géolocalisation des adresses IP ne fonctionne plus sur IPv6

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2600]
Il s'agit d'une regression depuis le passage à la lib GeoIP. Lorsqu'on est connecté en IP v6, le système ne sait pas nous localiser.

Un exemple : 

prod (1.7) : http://zestedesavoir.com/membres/voir/shine-neko/

preprod (1.8) : http://beta.zestedesavoir.com/membres/voir/Shine-neko/

Dans la 1.8 on ne voit aucune information relative à la localisation de l'utilisateur

**Comment by SpaceFox** [comment]
A vérifier qu'il y a bien les données de géoloc d'IPv6 (pour ce que ça sert...)

**Comment by firm1** [comment]
Les données de géoloc sont normalement [là](https://github.com/zestedesavoir/zds-site/tree/dev/geodata)

**Comment by SpaceFox** [comment]
Ah oui. Par contre je vois que ce n'est pas la même adresse IP en prod et
en bêta, donc je ne sais pas si c'est parce qu'il manque des données ou
parce qu'elle n'est pas localisable (ce qui est très fréquent sur les IPv6).

2015-04-28 16:11 GMT+02:00 firm1 notifications@github.com:

**Comment by pierre-24** [comment]
Ça va pas être drôle à tester en local, ça. À priori, y'a pas moyen d'aller éditer l'IP de l'utilisateur en BDD de manière à avoir des "vrais" adresses IPs ? Quelqu'un a des adresses IPs à proposer qui correspondent à de vraies positions ?

Moi: `96.255.231.204`, Washington DC, si vous voulez tenter

**Comment by Eskimon** [comment]
> Moi: 96.255.231.204, Washington DC, si vous voulez tenter

Elle a une drôle de tête ton IPV6 :-°

**Comment by pierre-24** [comment]
... J'ai pas d'IP v6 :'( (quoique peut être à l'unif, et encore)

**Comment by SpaceFox** [comment]
Tu devrais pouvoir en mettre une à la main dans la base. Sinon, il faut un
TU...

2015-05-02 14:13 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by pierre-24** [comment]
D'où ma question: est ce que quelqu'un à une adresse IPv6 à prêter ?

**Comment by SpaceFox** [comment]
Je confirme (avec les IPs déclarés dans le bug puisque j'y ai accès) que c'est un vrai bug et pas un problème d'IP non localisable.

**Comment by SpaceFox** [comment]
Et du coup c'est corrigé. Merci à tous !

**Comment by GerardPaligot** [comment]
On ferme du coup ?

**Comment by SpaceFox** [comment]
Beuh ? Je pensais l'avoir fermé !
