### ISSUE TITLE
Présence de fichiers inutiles dans le dépot

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2604]
Le projet contient des fichiers de données de geolocalisation qui alourdissent le dépot. Il faudrait supprimer ceux qui ne sont pas utiles.

L'emplacement des fichier : https://github.com/zestedesavoir/zds-site/tree/dev/geodata

La liste des fichiers à supprimer : 
- GeoIP.dat
- GeoIPASNum.dat
- GeoIPASNumv6.dat
- GeoIPv6.dat 

Les seuls fichiers utiles sont GeoLiteCity.dat et GeoLiteCityv6.dat.

**Comment by Eskimon** [comment]
Réglé :)
