### ISSUE TITLE
Problème d'UTF-8 dans les images à la publication

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2606]
Comme l'as découvert [Kje ici](https://github.com/zestedesavoir/zds-site/pull/2585#issuecomment-96833628), mettre un accent dans un nom d'image rend le _back_ pas très heureux pendant la publication.

**Comment by Eskimon** [comment]
Et voila ce sera corrigé au moins en 1.8, merci @pierre-24 !
