### ISSUE TITLE
Le champ licence passe par défaut à la première valeur de la liste lors de l'édition

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2613]
> Lorsque l'on clique sur "Éditer" pour modifier l'introduction de notre tutoriel, la licence passe par défaut à la première valeur de la liste : Licence CC BY. Je pense que c'est un bug vu que les autres champs, y compris le choix de sous-catégorie(s), sont bien conservés. Ou alors si ça n'en est pas un, je suggère d'améliorer cela pour éviter de re-sélectionner à chaque fois.
> - Smokiev

Source: https://zestedesavoir.com/forums/sujet/3024/editeur-de-tutoriel/

Enfait, le ModelChoiceField à besoin de l'id et on lui passe le titre. 
Cf: https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L1244 et 
https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L1161

http://stackoverflow.com/questions/1336900/django-modelchoicefield-and-initial-value

**Comment by Situphen** [comment]
Bug confirmé !

**Comment by Eskimon** [comment]
Il me semble que ca marchait bien avant (mais sans certitude), du coup je passe ca en régression.

**Comment by Situphen** [comment]
Moi aussi il me semble que ça fonctionnait bien mais pas de certitude non plus ! Je viens de regarder la vue et le formulaire de tutoriel, ça n'a presque pas changé récemment (à part un peu la ZEP 3). Bref, à investiguer plus en détail !

**Comment by Situphen** [comment]
Bug aussi présent sur la ZEP 12 (c'est logique).

@DevHugo, tu vois comment résoudre le problème ?

**Comment by DevHugo** [comment]
Je pense sans certitude. Si tu as une idée, fais le sinon assigne moi, et je fais ça demain. C'est pas un problème urgent.

**Comment by DevHugo** [comment]
Done, c'était facile à corriger.

**Comment by pierre-24** [comment]
> Bug aussi présent sur la ZEP 12 (c'est logique).

Hey, quand c'est comme ça, faut le dire :o

**Comment by pierre-24** [comment]
Corrigé et mergé.
