### ISSUE TITLE
Documentation qui ne compile plus : `ugettext`

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2616]
Récement, RTD a décidé de changer de raison pour ne pas compiler la documentation. Comme vous pouvez le voir [par exemple ici](https://readthedocs.org/builds/zds-site/2696781/), l'erreur est maintenant `AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.`. Autrement dit, on va essayer d'éviter les `ugettext` dans le code ;)

**Comment by Eskimon** [comment]
Hop tout roule, merci @pierre-24 !
