### ISSUE TITLE
Plus de stats IE11 et Safari depuis la v1.7

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2621]
Depuis la mise en place de la v1.7 et le changement du mode de gestion des cookies, Google Analytics ne voit pratiquement plus aucun IE11 et Safari.

Est-ce le comportement voulu ou est-ce que le nouveau système plante avec les navigateurs ? CC @Alex-D

**Comment by Situphen** [comment]
C'est toujours d'actualité ? Si oui j'enverrai un MP @Alex-D car je crois qu'il a mis les notifications du dépôt en silencieux.

**Comment by SpaceFox** [comment]
C'est toujours d'actualité.

**Comment by Situphen** [comment]
MP envoyé !

**Comment by Situphen** [comment]
@Alex-D m'a dit :

> Certainement le DoNotTrack activé par défaut ![:)](https://zestedesavoir.com/static/smileys/smile.png)

Après une petite recherche, il semblerait que Do Not Track est activé par défaut sur IE 11 :

> Do Not Track remains turned on by default in Internet Explorer 11 and Windows 8.1 Preview
> -- [Softpedia News](http://news.softpedia.com/news/Microsoft-Changes-IE11-Do-Not-Track-Behavior-in-Windows-8-1-365325.shtml)
> 
> When using the "Express" settings upon installation, a Do Not Track option is enabled by default for Internet Explorer 10 and Windows 8
> -- [Wikipedia](http://en.wikipedia.org/wiki/Do_Not_Track#Internet_Explorer_10_default_setting_controversy)

Je n'ai rien trouvé pour Safari.

Comme je le disais à @Alex-D par MP :

> Ce n'est pas forcément la faute à EU Cookies Banner, ça peut très bien être Google Analytics ou simplement que nos visiteurs n'utilisent plus ces deux navigateurs mais j'envisage toutes les possibilités ! ![:)](https://zestedesavoir.com/static/smileys/smile.png)

Même si ma dernière hypothèse semble très très peu probable ! :D

**Comment by SpaceFox** [comment]
Les gens qui arrêtent d'utiliser un outil le jour où on met EU Cookies Banner en prod ? J'ai un gros, gros doute...

**Comment by Situphen** [comment]
Je m'auto-cite :

> Même si ma dernière hypothèse semble très très peu probable ! :D

**Comment by Situphen** [comment]
@SpaceFox : Toujours aucun stat ?

**Comment by SpaceFox** [comment]
@Situphen aucune.

**Comment by GerardPaligot** [comment]
@SpaceFox Toujours rien ? Tu mentionnes Safari dans ton [article des 4k membres](https://zestedesavoir.com/articles/1120/quand-soudain-vous-etes-4-000/).

**Comment by SpaceFox** [comment]
On s'en fout en fait.
