### ISSUE TITLE
Plus moyen de générer un fichier .pid avec Gunicorn

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2622]
Je n'arrive plus à faire en sorte que Gunicorn avec la nouvelle config crée un fichier .pid.
Du coup, on a plus de stats Gunicorn (occupation mémoire et nombre de workers utilisés) dans les stats Munin.

Si quelqu'un a une idée...

**Comment by firm1** [comment]
Il faudrait déjà savoir sur quelle configuration repose gunicorn actuellement, [la documentation](http://zds-site.readthedocs.org/fr/latest/install/deploy-in-production.html#gunicorn) et le fichier [update.md](https://github.com/zestedesavoir/zds-site/blob/dev/update.md#d%C3%A9ploiement-de-django-17) se contredisent sur ce point.

**Comment by SpaceFox** [comment]
Ici aussi la doc n'est pas à jour.

**Comment by Eskimon** [comment]
Est-ce toujours pertinent/utile ou pas ?

**Comment by SpaceFox** [comment]
Oui si on veut avoir les stats Gunicorn.

Maintenant il est lancé avec systemd.

**Comment by GerardPaligot** [comment]
@vhf @gustavi Une idée pour faire avancer cette issue ?

**Comment by vhf** [comment]
Réglé.

```
mkdir /run/gunicorn
chown zds /run/gunicorn
```
