### ISSUE TITLE
Grosse augmentation des temps de réponse sur la v15.5

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2623]
Suite au déploiement de la v15.5 en prod, certaines pages sont _beaucoup_ plus lentes à afficher qu'avant :

![responsetimes](https://cloud.githubusercontent.com/assets/5786268/7449601/43b89ace-f23a-11e4-8eeb-1bace0d71a7e.png)

Si quelqu'un a une idée de pourquoi...

**Comment by firm1** [comment]
Dans quelle mesure la conf infra (gunicorn, nginx, settings.py, mysql) a été modifiée pendant la MEP ?

**Comment by SpaceFox** [comment]
En infra seule la conf Gunicorn a changé. Mais je ne vois pas comment ça
peut parfois rien changer et parfois doubler les temps de réponse.

**Comment by firm1** [comment]
> En infra seule la conf Gunicorn a changé. Mais je ne vois pas comment ça peut parfois rien changer et parfois doubler les temps de réponse.

Tu as le delta du changement de la conf gunicorn ? je ne sais pas si je dois me fier à la doc ou au fichier update.md pour ça

**Comment by SpaceFox** [comment]
Le fichier update.

**Comment by pierre-24** [comment]
J'ai _peut être_ une idée. Ce qu'on voit, c'est donc que ce qui prend méchamment un coup, c'est les pages avec posts. Or, en travaillant sur la ZEP-12, je faisais justement la réflexion à atragis que les perfs se faisaient méchament flinguées quand on commençait à ajouter les posts, parce que le nombre de requête mysql augmente de manière démentielle avec le nombre de post sur une page donnée (4 par post, si j'ai bien compris). Ce qui fait qu’actuellement, un tuto pas très chargé (2 commentaires), et on tape à 28 reqêtes sur la home, contre 58 sur un bête tuto à 5 commentaires : 

![screenshot from 2015-05-04 20 55 56](https://cloud.githubusercontent.com/assets/7889675/7465552/02b59a66-f2a0-11e4-918d-b0ee92cf0fe1.png)

... Et d'une manière ou d'une autre, j'ai l'impression que c'est même pire quand il y a 3 utilisateurs.

Je vous avoue que j'ai la flemme de _downgrader_ une fois encore mon dépôt (je le ferait si ça vous amuse), mais je me souviens pas que le nombre était aussi énorme avant.

Le problème, c'est que j'arrive pas à trouver un indice dans les graphes de munins (5 minutes qu'il m'a fallu pour retomber sur le mot de passe!) pour corroborer mon hypothèse. 

Quand à la cause, j'ai envie de dire "Django 1.7", mais là, j'accuse sans preuves.

**Comment by SpaceFox** [comment]
Je sais qu'actuellement chaque affichage de message provoque des requêtes, notamment à cause du badge sous l'utilisateur ;  et encore plus en mode connecté à cause des diverses icônes à calculer. C'est notamment l'objet de #2222.

Du coup, c'est clair que si Django 1.7, pour une raison X ou Y, est plus lent à traiter ces requêtes (la BDD et le connecteur n'ont pas changé), on a un impact fort sur les performances.

Je crois que hélas le seul moyen d'en être sûr, c'est d'installer les 2 versions v1.7 / v15.5 sur une base MySQL, en mode debug désactivé (pour éviter les lenteurs dues au mode debug) et de comparer...

**Comment by pierre-24** [comment]
Je vais voir si je peux faire ça (va falloir que je joue avec mysql ^^)

**Comment by SpaceFox** [comment]
Pour éviter de pourrir ce ticket, je vais faire mon rapport sur les forums, ça me permettra d'utiliser les balises "secret"...

PS : C'est ici : https://www.zestedesavoir.com/forums/sujet/3090/analyse-des-lenteurs-depuis-le-passage-a-en-v155/#p55846

**Comment by SpaceFox** [comment]
Conclusion :
1. Il faut traquer et éliminer les requêtes supplémentaires qui sont apparues en particulier sur les catégories de forum, et je suppose sur les pages de de tutos et d'articles (je ne peux pas les tester en local). En particulier les requêtes genre `SELECT ••• FROM`auth_user`WHERE`auth_user`.`id`= 258 LIMIT 21`
2. Il semblerait que l'on passe plus de temps dans les templates, mais c'est à voir si ce n'est pas un effet de bord du point 1.

**Comment by SpaceFox** [comment]
Je pense qu'on ne vas pas couper à ce genre de test à chaque version par contre :(

**Comment by pierre-24** [comment]
Bon, j'avais vu juste (mais j'ai pas de mérite, je l'avais déjà vu sur la ZEP-12). 

Pour faire avancer les choses, j'ajouterai que les requêtes en question viennent d'endroit très précis. Typiquement, un endroit qui génère au moins une requête par _post_, c'est la [template des badges](https://github.com/zestedesavoir/zds-site/blob/dev/templates/misc/badge.part.html) (check des permissions à chaque coup pour afficher le badge "ADMIN"/_whatever_). L'autre truc, c'est [la template d'affichage du message lui-même](https://github.com/zestedesavoir/zds-site/blob/dev/templates/misc/message_user.html), ou on choppe quasi systématiquement la requête pour choper le _profile_ de l'user (ça, évidement, on y peut rien tant qu'on a pas fait disparaitre un des deux ^^). Ça fait déjà deux requêtes par post, sur une page qui en compte 20, ça fait 40 requêtes. 

À ça, on peut également rajouter la [template de "base" des forums](https://github.com/zestedesavoir/zds-site/blob/dev/templates/forum/base.html), qui fait un paquet monstre de requête (une à deux, je sais pas trop en fonction de quoi) par sujet suivi (entre autre pour récupérer à chaque fois le dernier sujet lu), ce qui peut vite être important. 

Finalement, mais sans trop m'avancer, je pointerai du doigt [la vue `topic()`](https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/views.py#L123). Vu comment @artragis a du se démener pour réduire le nombre de nombre de requêtes sur la ZEP-12, j'ai l'impression qu'il y a du comportement pas très opti non plus là derrière. J'espère me tromper, et je laisse @artragis vous dire comment il a fait.

Bref, va falloir faire des jointures un peu partout (`prefetch_related()` et `get_related()` dans le langage de Django). 

Dans tout les cas, ces fichiers ont été modifiés pour la dernière fois il y a un certains temps, tout du moins sur les points fautifs que j'ai donné ci-dessus. Autrement dit, le _driver_ mysql a du vachement régresser de Django 1.6 à là 1.7 pour que les perfs soient aussi dégeu d'un coup. Ou alors, on a touché à un truc qui fait une réaction en cascade, mais je viens encore de relire la liste des tickets de la v15.5, je vois pas quoi.

**Comment by artragis** [comment]
Le gros problème c'est le templatetag profile qui recharge le profile à 
chaque fois !
Il serait 100 fois mieux qu'il le charge une fois et qu'il le stocke 
dans la propriété "user.profile" quitte même à créer une propriété adhoc 
style "full_profile" qui charge toutes les permissions.

**Comment by Eskimon** [comment]
[Cette PR](https://github.com/zestedesavoir/zds-site/pull/2785) ne devrait-elle pas inclure ce ticket ?

**Comment by artragis** [comment]
Si.

2015-06-17 11:47 GMT+02:00 Eskimon notifications@github.com:

**Comment by artragis** [comment]
mais en même temps ça ne résoud pas tous les problèmes, juste une partie, ce n'est qu'une première passe.

**Comment by Situphen** [comment]
Qu'en est-il suite au passage en v15.6 ?

**Comment by pierre-24** [comment]
Ben d'après Spacefox, pas des masse.

**Comment by artragis** [comment]
D'après ce que j'ai vu, on a eu droit à une baisse de la volatilité. Il faut comprendre que quand on fait beaucoup de recherches, mysql met un minimum de cache, ce qui fait baisser le temps de réponse, mais quand ce cache est expiré, le temps de réponse augmente fortement. Là on a globalement stabilisé le temps de réponse au même niveau (ou très très très légèrement inférieur) que le niveau moyen de la v15.5 MAIS comme on n'est pas en "iso fonctionnel" à cause des bugs, il se peut que les chiffres changent dans un sens comme dans un autre.

Notons aussi que les augmentations de "perfs" que je permets dans mes PR ne font que baisser la demande **des membres connectés** du "pire des cas" c'est à dire "un dialogue entre membres du staff et liké ou disliké par presque tout le monde". Le "meilleur des cas" (un topic/article avec 3/4 participants non staff) et le "cas moyen" (un topic avec 8 participants différents sur une page, nombre moyen de votes par message 7/8) ne sont que très peu impactés ou juste très légèrement. N'oublions pas que nos goulets d'étranglement sont : 
- le module de tuto (mais la ZEP-12 est plus que prometeuse à ce niveau)
- les notifications et plus globalement le menu du haut (mais on ne le mesure pas avec munin). 

Il suffira donc qu'on ait eu plus de trafic de membres connectés pour que les non connectés ait subit des dégats collatéraux style "légère perte de perf". Il faudrait demander à spacefox si après le creu de mai la popularité du site est de nouveau sur un pente ascendante.

N'oublions aps aussi que depuis ce gap fonctionnel on s'est aussi tappé plusieurs ralentissement du serveur à cause d'ovh, ça se voit assez clairement dans mon monitoring [dareboos](http://dareboost.com) (pour avoir les pdfs dites le moi, mais ça n'intéressera que peu les dev back).

**Comment by Eskimon** [comment]
Quid de ce ticket ? Je suppose qu'on attendra le retour de @SpaceFox pour évaluer si faut le fermer ou pas. Merci de le rappeler début décembre :)

**Comment by GerardPaligot** [comment]
@SpaceFox Alors, avons-nous toujours des soucis de performance après les contributions de @artragis ?

**Comment by artragis** [comment]
On peut pas savoir tant que la v16 n'est pas en prod

**Comment by GerardPaligot** [comment]
Ta PR a été mergée depuis longtemps non ? La v15.5 est liée à l'ancien système de version me semble.

**Comment by artragis** [comment]
Il y a eu du mauvais avec la v12 (augmentation du tr dans les articles). 
Il faut attendre le travail le plus récent pour avoir ça.

**Comment by GerardPaligot** [comment]
Ok, alors je garde à l'esprit de vérifier ça la v16 en production.

**Comment by artragis** [comment]
Maintenant on peut fermer : 

![mepv16-perfs](https://cloud.githubusercontent.com/assets/1523653/13136110/0585e5f6-d617-11e5-8c1b-00e952b7eeb6.png)

**Comment by SpaceFox** [comment]
Yep, merci à tous !

**Comment by pierre-24** [comment]
Waw, merci @artragis :)
