### ISSUE TITLE
Liens morts dans le fichier README

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2624]
Le fichier README contient dans la section [En savoir Plus](https://github.com/zestedesavoir/zds-site#en-savoir-plus), un le lien intitulé : `Comment déployer ZDS sur un serveur de production ?` qui pointe vers une 404, il faudrait le mettre à jour.

Dans la même lancée, le lien "Comment contribuer : comprendre comment suivre le workflow (sur zds)" pointe sur le site zestedesavoir.com . Il faudrait l'intégrer (dans le but de centraliser) dans la documentation sous sphinx

**Comment by Situphen** [comment]
Il faut remplacer `[Comment déployer ZDS sur un serveur de production ?](http://zds-site.readthedocs.org/fr/latest/install/deploiement-production.html)` par `[Comment déployer ZDS sur un serveur de production ?](http://zds-site.readthedocs.org/fr/latest/install/deploy-in-production.html)`.

**Comment by pierre-24** [comment]
Hop, c'est corrigé, merci @DevHugo !
