### ISSUE TITLE
Question : le build du front sera t-il OP pour la prochaine release ?

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2625]
En passant en revue la nouvelle démarche de build du front lors des reelase, je me pose quelques question.
1. Il me semble d'après le script travis que le front ne buildera que **si et seulement si, on crée un tag**. Le problème est que la mise en préprod se fait généralement sans tag (uniquement à partir d'une branche release-xx). Etant donné que le le build npm a disparu du fichier de déploiement, j'en viens à la conclusion que la procédure de mise en beta a changé (un tag par version mise en préprod). Si c'est le cas, on risque d'avoir beaucoup trop de tag au final (et il me semble qu'on a aucun intéret à tagguer une version de release).
2. Le build du front est censé générer un deuxième tag du nom de `vAA.MM-nom-de-code-build`. C'est ce tag qui sera finalement déployé. Le problème c'est qu'en dehors du fait qu'on aura à chaque fois, quasi deux tags en double (un sans le front, et l'autre avec le front), on risque de ce retrouver avec dans le footer du site un nom à rallonge `xxxx-build`.

Ce sont quelques points que je découvre et donc je m'intérroge pour savoir si c'est bien ce que l'on veut. Surtout que le nouveau fonctionnement ne me semble pas en accord avec ce que l'on peut lire [dans la documentation](http://zds-site.readthedocs.org/fr/latest/workflow.html#id1) de déploiement

**Comment by Eskimon** [comment]
La PR qui fait tout ca est la et j'ai deja mis en lumiere certains points : https://github.com/zestedesavoir/zds-site/pull/2482#issuecomment-94201422

**Comment by firm1** [comment]
Si la release se base bien sur les tags, on a donc un problème de [doc](http://zds-site.readthedocs.org/fr/latest/workflow.html#id1).

**Comment by SpaceFox** [comment]
Houlà, à peu près toutes tes suppositions sont fausses @firm1. La doc est complètement pas à jour (en fait j'ignorais sont existence à cette doc ci, et apparemment toutes les personnes qui ont fait la QA aussi).
- Tout déploiement se fait par tag. Toujours et ça a toujours été le cas, y compris en bêta
- [Le nombre de tags n'est pas un problème](https://github.com/torvalds/linux/releases)
- Regarde le code de déploiement : il checkoute le tag `vx.y-nomdecode-build` mais crée une branche `x.y-nomdecode` et c'est bien `x.y-nomdecode` qui est affiché dans le footer.

**Comment by firm1** [comment]
Merci des réponses, je laisse ouvert du coup pour que l'on mette à jour la documentation en ce sens.

**Comment by pierre-24** [comment]
Il semblerai que ça fonctionne ?

**Comment by sandhose** [comment]
Oui, ça a été utilisé lors du déploiement de la v15.5.1 en bêta. Je ferme, donc
