### ISSUE TITLE
Liste des forums en doubles

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2626]
Url incriminée : http://zestedesavoir.com/forums/communaute/

Le forum staff est affiché en double pour les membres qui appartiennent aux groupes CA et Staff en même temps. En sachant que les deux groupes ont accès au même forum, ça crée des doublons.

**Comment by SpaceFox** [comment]
Marrant, on l'avait corrigée dans le menu celle-là !

**Comment by DevHugo** [comment]
C'est pas de la 'Régression' ?

**Comment by firm1** [comment]
Aucune idée, je suis incapable de dire si ça marchait correctement avant

**Comment by Eskimon** [comment]
Je met en régression car [une PR](https://github.com/zestedesavoir/zds-site/pull/2442) avait déjà corrigé ce problème... (c'est toi qui l'avait faite @firm1 ^^ )

**Comment by Eskimon** [comment]
J'ai l'impression que ca a ete corrige avec la refacto des fofos, je ne reproduis pas en local... je ferme donc mais ca serait bien de vérifier ca en preprod (j’essaierai d'y repenser)

**Comment by GerardPaligot** [comment]
Rendons à césar ce qui appartient à césar, ça avait été corrigé avant mon refactoring et, de tête, par @firm1.
