### ISSUE TITLE
Erreur sur les profils quand on est admin

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2631]
À mon avis, on a été trop vite quand on a viré GeoIP. Quand on va sur un profil en temps qu'admin, on a une erreur dans la template, sur `{{ profile.get_city }}`.

**Comment by SpaceFox** [comment]
Quel environnement et version ? Je ne reproduit ni sur la prod, ni sur la bêta.

**Comment by Eskimon** [comment]
(PS Un `bug` EST une `regression` donc pas la peine de mettre les deux ;) )

**Comment by Eskimon** [comment]
@SpaceFox surement en local puisque le revert a été fait récemment et ne doit pas encore être dans une version déployée

**Comment by SpaceFox** [comment]
Nop, le revert est en prod : [la PR portait sur la branche de release 1.8](https://github.com/zestedesavoir/zds-site/pull/2609) qui a été déployée sous le nom v15.5.

**Comment by Eskimon** [comment]
Ah ok my bad. Du coup comment @pierre-24 a teste et quelle semble etre l'erreur ? Parce qu'idem en beta (ou je suis staff) j'ai pas de souci et en prod (ou je suis lambda) ca roule aussi.

@pierre-24 le revert avait touche aux requirements, les tiens sont ils a jour ?

**Comment by pierre-24** [comment]
Désolé, il était tard le soir. J'ai l'erreur sur _dev_, donc en local (je suis pas staff, je peux pas voir l'erreur en prod ;) ), avec mes _requirements_ à jour :)

**Comment by Situphen** [comment]
En local, que ce soit sur `v15.5-clementine` ou `upstream/dev`, avec mes dépendances `apt-get` et `pip` à jour, j'ai cette erreur quand je vais sur un profil avec "admin" :

``` bash
  File "/home/situphen/Documents/Dev/Python/zdsenv/zds-site/zds/member/models.py", line 134, in get_city
    geo['city'], geo['country_name'])
TypeError: 'NoneType' object has no attribute '__getitem__'
[10/May/2015 14:10:50] "GET /membres/voir/admin/ HTTP/1.1" 500 2081064
```

**Comment by Situphen** [comment]
C'est bizarre que l'on ait pas l'erreur en prod !

---

Corrigé et mergé. Merci @Eskimon ! :)
