### ISSUE TITLE
Impossible de remettre un champ de son profil à `False`

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2632]
Quand on fait un `PUT /api/membres/{pk}` et qu'on passe `shown_sign: False` ou `shown_email: False`, la valeur reste à `True`. Preuve en est:

![screenshot from 2015-05-04 22 33 11](https://cloud.githubusercontent.com/assets/7889675/7466245/8dcec76e-f2ad-11e4-8ff2-59df97b7c762.png)

À noter que si on balance n'importe quoi, on recoit bien l'erreur "ceci n'est pas un booléen", donc ça, c'est OK. Et j'ai essayé avec `False`, `false` et `0`, rien à faire.

**Comment by DevHugo** [comment]
Enfait, c'est pour tous les champs boolean: shown_sign, shown_email, hover_or_click, email_for_answer.

Ça vient d'ici : https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/api/serializers.py#L167.

`python
validated_data.get('show_sign', instance.show_sign) or instance.show_sign
`
Pour cet exemple, validated_data.get('show_sign', instance.show_sign) renvoi False mais 
instance.show_sign renvoi True. Comme c'est un operateur 'or', Vrai ou Faux renvoi toujours vrai.

**Comment by DevHugo** [comment]
> Issue here: When a model has a default we simply set required=False on the serializer field, and allow the model instance to use it's default when setting the value. Because empty text and boolean fields are coerced to an empty value by the serializer field that doesn't work.
> Source: https://github.com/tomchristie/django-rest-framework/issues/1101

Ce qui est totalement logique dans illogique.

**Comment by GerardPaligot** [comment]
Merci à @DevHugo pour le fix et @pierre-24 pour la QA.

Ping notre CdP @Eskimon pour savoir si j'ai bien positionné la milestone.

**Comment by Eskimon** [comment]
Arf vu que les milestones ont mysteurieusement change de nom je dirais "oui parce qu'il y a que celle la..." @SpaceFox des choses a dire ?

**Comment by pierre-24** [comment]
Moi c'est ce que je met depuis 2 semaines :-°

**Comment by SpaceFox** [comment]
C'est bien ça : que mettre d'autre comme nom de version puisque le numéro de la prochaine est encore inconnu ?
