### ISSUE TITLE
Erreur 500 lors de l'édition malencontreuse d'un message du forum

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2633]
url incriminée : http://zestedesavoir.com/forums/message/editer/?message=plazza/

On tombe sur une erreur 50. La bienséance voudrait qu'on n'ait jamais d'erreur 500 dans la vie.

**Comment by Eskimon** [comment]
Ca se passe ici: https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/views.py#L665

Il manque une conversion en `int`

La même chose pourrait être faite ici d'ailleurs : https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/views.py#L625

**Comment by Eskimon** [comment]
Je prends

**Comment by SpaceFox** [comment]
C'est une vraie erreur que tu as obtenue en appuyant sur un bouton ou tu as fait n'importe quoi avec les paramètres ?

**Comment by Eskimon** [comment]
> C'est une vraie erreur que tu as obtenue en appuyant sur un bouton ou tu as fait n'importe quoi avec les paramètres ?

Il faut bricoler les paramètres. Mais la remarque "ne pas avoir de 500" reste vrai tout de même.

**Comment by SpaceFox** [comment]
Ouais mais ça change complètement la priorité du truc : si c'est en appuyant sur un bouton c'est urgent, si c'est en jouant avec les paramètres on s'en fout, ça ne met pas en danger le site et l'utilisateur n'a qu'à pas jouer avec les paramètres :)

**Comment by Eskimon** [comment]
Tout a fait :) Mais j'ai juste dit je prends car je sais très bien comment corriger et faire le TU, le tout en 5 minutes ^^

**Comment by firm1** [comment]
Comme le souligne Eskimon, on ne tombe pas dessus par hasard, faut le chercher. Donc oui, en priorité faible, après si c'est faisable rapidement, c'est toujours ça de corrigé

**Comment by Eskimon** [comment]
Voila.

**Comment by Situphen** [comment]
Corrigé. Merci @Eskimon !
