### ISSUE TITLE
Erreur 500 lors de la consultation malencrontreuse d'un tutoriel

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2636]
Url incriminée : http://zestedesavoir.com/tutoriels/off/813/le-langage-c/?version=e83ef9065bcacea987fdf1554e5b744becdeba0c/

On tombe sur une erreur 50. La bienséance voudrait qu'on n'ait jamais d'erreur 500 dans la vie.

**Comment by Eskimon** [comment]
Est-ce que c'est similaire a ca : https://github.com/zestedesavoir/zds-site/issues/2405

Du coup @artragis et @pierre-24 la ZEP-12 protege-t-elle de cela ?

**Comment by firm1** [comment]
> Est-ce que c'est similaire a ca : #2405

Pas vraiment, c'est un autre problème.

**Comment by artragis** [comment]
théoriquement, oui, je fais le TU ce midi. Je vais d'abord manger néanmoins.

2015-05-05 11:55 GMT+02:00 firm1 notifications@github.com:

**Comment by artragis** [comment]
TU + QA déjà faite, la ZEP 12 envoie une 403 comme sur la version en ligne.
