### ISSUE TITLE
Incohérence dans les libellés de catégorie de la sidebar

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2637]
Le libellé de la catégorie des tutoriels et différent selon ou on se trouve.

Sur la [home](http://zestedesavoir.com/) on a : 

![all-home](https://cloud.githubusercontent.com/assets/6066015/7472334/b64fe2fc-f331-11e4-9b1e-5795947f4432.PNG)

Dans la page [tous les tutoriels](http://zestedesavoir.com/tutoriels/) on a :

![all-tutis](https://cloud.githubusercontent.com/assets/6066015/7472335/bb8b9bd0-f331-11e4-8433-bfd23d20e9bc.PNG)

Il doit y avoir moyen de factoriser ce template, et de rendre les deux cohérent.

**Comment by Situphen** [comment]
Vu que c'est supprimé de la page d'accueil dans la ZEP 4, c'est la peine de fixer ça ?

**Comment by firm1** [comment]
> Vu que c'est supprimé de la page d'accueil dans la ZEP 4, c'est la peine de fixer ça ?

C'est de la priorité très très très faible, donc ça sera fermé quand la ZEP-4 sera mergée

**Comment by SpaceFox** [comment]
Pour être exact, vu que la ZEP-4 est presque prête, c'est abandonné _maintenant_.
