### ISSUE TITLE
citation d'un extrait de site web

### ISSUE THREAD

**Issue by wtuuju** [zestedesavoir/zds-site#2638]
Bonjour,

Je ne sais pas trop si c'est un bug ou une mauvaise utilisation du markdown, mais voilà : 

J'ai cité un site web, à l'aide de " > " ainsi que Source:[ohax.fr] http://ohax.fr/oubliez-pachydermique-adblock-plus-ublock-origin-est-arrive (j'ai retiré les parenteses car githib interprete aussi le markdown...) juste après. Comme pour citer un membre.

On voit bien ohax.fr mais le lien envoie sur ohax.fr et non http://ohax.fr/oubliez-pachydermique-adblock-plus-ublock-origin-est-arrive.

L'URL de mon post : https://zestedesavoir.com/forums/sujet/2137/applications-les-indispensables-de-la-communaute/?page=2#p55606

**Comment by Situphen** [comment]
Rappel du code Markdown qui bug :

```
Source:[ohax](http://ohax.fr/oubliez-pachydermique-adblock-plus-ublock-origin-est-arrive)
```

Ça a l'air d'être dû à `[ohax.fr]` car avec `[ohax]` ça fonctionne !

Ping @cgabard :)

**Comment by firm1** [comment]
L'issue est peut-être à déplacer sur le dépot zmarkdown non ?

**Comment by wtuuju** [comment]
> Ça a l'air d'être dû à [ohax.fr] car avec [ohax] ça fonctionne !

Bah après on pourrait penser que ohax est un membre, et non un site web.

EDIT : on pourrait mettre une icône qui indique que le lien est externe, comme sur wikipedia ?

**Comment by cgabard** [comment]
Ha oui en fait il y a déjà un ticket pour ça. C'est parce que `ohax.fr` est détecté comme un lien. Ça génére un lien (auto) dans le liens de base. C'est connu et il y a déjà un ticket pour ça.

**Comment by wtuuju** [comment]
> Ha oui en fait il y a déjà un ticket pour ça. C'est parce que ohax.fr est détecté comme un lien. Ça génére un lien (auto) dans le liens de base. C'est connu et il y a déjà un ticket pour ça. 

Je ferme alors
