### ISSUE TITLE
Passer à une version supérieure à django 1.7.7 pour la prochaine release

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2640]
Le projet django a annoncé [la version 1.7.8 de django](https://docs.djangoproject.com/en/1.8/releases/1.7.8/) qui corrige un problème de la version 1.7.7 qui nous concerne. 

Pour rappelle en prod, c'est la version 1.7.7 qui est actuellement déployée.

La bonne nouvelle c'est qu'étant donné que le passage a django 1.7 ne modifiait pas la base de donnée, on est tranquille, la base n'est pas corrompue. Cependant, c'est un point de vigilance, la prochaine _release_ qui mettra à jour la base de donnée devra mettre à jour la version de django avant pour ne pas alterer les données de prod.

**Comment by SpaceFox** [comment]
Je me demande si ça n'expliquerait pas les merdes qu'on a eu à la tentative
de passage à Django 1.8 du coup.

**Comment by firm1** [comment]
> Je me demande si ça n'expliquerait pas les merdes qu'on a eu à la
> tentative de passage à Django 1.8 du coup.

Je sais pas il y'avait pas de migration de base non plus pour django 1.8

**Comment by SpaceFox** [comment]
Il y en a, parce que Django 1.8 fait plus de contrôles au niveau des requêtes et déclarations de modèles, et certaines ne passent plus aujourd'hui... _dont des gestion de `null`_.

[Cf la 1ère tentative de PR par exemple](https://github.com/zestedesavoir/zds-site/pull/2518/files).

**Comment by firm1** [comment]
Faudrait se repencher dessus alors. Si ça permet de passer à django 1.8
c'est tout benef

**Comment by pierre-24** [comment]
Mergé !

Ça veux dire qu'on va pouvoir se repencher sur Django 1.8, du coup ... Normalement ^^
