### ISSUE TITLE
Erreur 500 lors de la citation malencontreuse d'un MP

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2642]
Environnement : production

Url incriminée : `http://zestedesavoir.com/mp/<id_mp>/bisou/messages/creer/?cite=x`

remplacer `<id_mp>` par l'id d'un mp dans lequel vous êtes

On tombe sur une erreur 500. La bienséance voudrait qu'on n'ait jamais d'erreur 500 dans la vie.

**Comment by Eskimon** [comment]
Perso j'obtiens une 403 (version 15.5b). Tu peux retester pour être sur ? Et si ca bug toujours re-expliquer comment tu fais car je vois pas la.

**Comment by firm1** [comment]
@Eskimon Moi j'obtiens toujours une erreur 500. Peut-être parce que je suis staff cela dit.

Voici un MP qu'on a en commun, fait un essai : http://zestedesavoir.com/mp/5387/bisou/messages/creer/?cite=x

**Comment by Eskimon** [comment]
Je viens de comprendre, ce qui pose problème c'est le `x` non ?

**Comment by firm1** [comment]
> Je viens de comprendre, ce qui pose problème c'est le x non ?

Je suppose oui

**Comment by GerardPaligot** [comment]
Quand on spécifie un MP où on ne dispose pas les accès (par exemple, je suis pas dans votre MP identifié par `5387`), j'obtiens une 403 parce que je suis stoppé avec la récupération de l'identifiant spécifié pour la citation.

Donc quand tu es dans le MP et que tu mets n'importe quoi dans `cite`, ça merdouille.

**Comment by Eskimon** [comment]
Et j'avais anticipe et ca a ete regle via cette PR normalement : https://github.com/zestedesavoir/zds-site/pull/2634

Il y a meme un TU :)

**Comment by firm1** [comment]
Bizarre @Eskimon la PR que tu linke, ne touche pas aux fichiers des MPs, donc je ne pense pas que ça règle le souci :)

**Comment by GerardPaligot** [comment]
@Eskimon Tu règles le même problème mais pour les forums.

**Comment by Eskimon** [comment]
Arf oui XD Bon bah je vais refaire ca :)
