### ISSUE TITLE
Page de connexion: Effet bizarre

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2649]
Bonjour,

j'avais déjà inscrit ça dans "Les petits pixel", mais je n'y ai jamais reçu de réponse.  
Je me permet donc de poster ici.

Le problème:
- Un effet bizarre se produit quand je me rend sur la page de connexion, (Uniquement sur la page de connexion)

Os: Windows 7
Navigateur: Firefox dev edition (Sur firefox normal aussi, mais de façon aléatoire et moins prononcé)

Preuve:
- https://www.youtube.com/watch?v=y4qB6q2E-Ck

Etant donnée que je trouve ce "bug" extrêment étrange, je ne sais pas s'il est propre à moi (Mais bon je ne verrais pas pourquoi uniquement sur ZdS et uniquement sur la page de connexion)

WinXaito

**Comment by Situphen** [comment]
Je ne sais pas trop s'il faut considérer ça comme un bug.

**Comment by WinXaito** [comment]
C'est ce n'est que du visuel, mais je ne trouve pas ça très glamour ... Pour savoir, le problème se produit-il aussi chez vous ?

**Comment by Eskimon** [comment]
Ah j'ai ptet trouvé un truc... Perso chez moi par défaut ca ne le fais pas, MAIS si je m'amuse à faire des ctrl+F5 pour rafraîchir la page alors là ca me le fais... J'ai du mal à vraiment qualifié ca comme un bug car on est pas vraiment dans le comportement attendu d'un utilisateur...

**Comment by Situphen** [comment]
Moi ça me le fait sans que je m'amuse à faire Ctrl+F5 ! C'est vrai que ça doit être assez énervant à la longue mais je suppose que la majorité des utilisateurs restent connectés et donc ne voient cette page que peut souvent. J'hésite entre Bug et Evolution...

**Comment by Eskimon** [comment]
Ah bah si tu arrives à reproduire sans insisté nickel....

Clairement c'est un bug par contre, c'est un comportement indésirable. Je vois pas ou on pourrais évoluer ici :D

**Comment by WinXaito** [comment]
Moi c'est effectivement à chaque actualisation ou clique sur le bouton "Connexion", je ne m'amuse pas à faire des ctrl + f5 :)

**Comment by WinXaito** [comment]
Du nouveau par ici ?

**Comment by Situphen** [comment]
@WinXaito : Je suis en pause de dev pendant quelques semaines et @sandhose passe des examens (si je dis pas de bétises) donc il faudra attendre un peu :)

**Comment by sandhose** [comment]
J'ai effectivement la première épreuve de Bac demain matin :-°

L'issue en soit est assez relou à gérer, parce qu'elle vient du fait qu'on applique une transition sur [quasi systématiquement](https://github.com/zestedesavoir/zds-site/search?utf8=%E2%9C%93&q=%24transition-duration) **toutes** les propriétés sur les boutons et autres liens ; du coup, certains navigateurs calculent les propriétés CSS au fur et a mesure que la page charge, et finissent par faire une transition entre les deux "états"...

La solution serait donc de faire le tri dans les transitions, et n'animer que le nécessaire (donc essentiellement `color` et `background-color`...)
