### ISSUE TITLE
Impossible d'activer un compte si pas d'email d'activation

### ISSUE THREAD

**Issue by jonathanpoelen** [zestedesavoir/zds-site#2655]
Bonjour,

Il a quelque temps (1 mois ?), je mettais inscrit sur zds mais n'avait pas reçut de mail d'activation. Aujourd'hui, je tente de me connecter mais un joli message me dit d'activer mon compte. Je peux modifier mon pass  sans aucun changement :'(.

Comme je n'ai pas trouvé comment renvoyer un mail d'activation, j'ai fini par créer un nouveau compte, l'ancien étant déjà utilisé...

Il serait bien de supprimer les comptes en attente (et une option pour renvoyer le mail ?)

**Comment by DevHugo** [comment]
Les admins comme firm1 peuvent faire en sorte de valider ton compte mais il va leur falloir le nom de l'ancien compte et celui du nouveau en attendant la nouvelle fonctionnalitée.

**Comment by jonathanpoelen** [comment]
Oki,
le nouveau: jo.link.noir
l'ancien : jo_link_noir

**Comment by firm1** [comment]
Ton ancien compte (jo_link_noir) est maintenant activé, je te laisse le prendre en main et désinscrire le "nouveau" jo.link.noir ?

**Comment by jonathanpoelen** [comment]
Ok, c'est bon. J'ai pu accéder à l'ancien et supprimer le nouveau.
Merci.

**Comment by pierre-24** [comment]
C'est bon, on peut désormais recevoir à nouveau un mail de confirmation, merci @DevHugo :)
