### ISSUE TITLE
Afficher les sujets suivis depuis plus d'un an

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2657]
Il s'agit d'un bug, déclaré par mon homologue venu tout droit du futur ^^. On ne le voit pas encore aujourd'hui car le site n'a pas encore 1 an d'existance, mais comme on peut le voir en jetant un coup d'oeil au [code](https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/templatetags/interventions.py#L30), si je follow un topic vieux de plus d'un an, il n'apparraitra pas dans la liste des sujets suivis qu'on voit dans la sidebar. Le code actuel est prévu uniquement pour les sujets de moins d'un an.

Le risque qu'un utilisateur rencontre ce bug est très très faible, car ça signifierait que le membre ne s'est pas connecté depuis un an sur le site. Donc la priorité est très très faible. Mais ça reste un bug tout de même.

**Comment by SpaceFox** [comment]
Globalement, tout ce bout de code m'a l'air bien compliqué pour pas
grand-chose.

**Comment by Situphen** [comment]
@ChantyTaguan : Est-ce que la ZEP 24 touche à ce bout de code ? Est-ce que vous pouvez régler ce problème ?

**Comment by ChantyTaguan** [comment]
Oui, on touche à ce bout de code, mais pour l'instant, sans modifier ce comportement. Mais on peut corriger ça oui :)

**Comment by GerardPaligot** [comment]
Je rajoute cette issue dans ma PR de la ZEP-24 qui devrait corriger cette issue. :)

**Comment by gustavi** [comment]
J'ai corrigé ça je crois bien.

**Comment by gustavi** [comment]
Mergé dans ZEP-24.
