### ISSUE TITLE
Problème de connexion en IPv6 en https

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2658]
> Il semble que le serveur soit mal configuré et refuse les connexions https (mais pas en http) sur son ipv6. Quelques logs pour mettre en avant le problème : 
> 
> ``` bash
> saucisson@ArchTosh:~$ nmap -6 zestedesavoir.com -p 443,80
> 
> Starting Nmap 6.47 ( http://nmap.org ) at 2015-05-10 01:25 CEST
> Nmap scan report for zestedesavoir.com (2001:41d0:52:100::b4f)
> Host is up (0.014s latency).
> PORT    STATE  SERVICE
> 80/tcp  open   http
> 443/tcp closed https
> ```
> 
> Source:[Cornichon](http://zestedesavoir.com/forums/sujet/3113/mauvaise-configuration-ipv6/?page=1#p56205)

Je taggue en bloquant, car ça me parait tout de même handicapant

**Comment by SpaceFox** [comment]
C'est pas bloquant dans la mesure où ça n'empêche pas l'accès au service.

Ça et le fait que ça m'étonne, parce que chez moi je suis en IPv6 et je n'ai pas de problème. Je vérifierai.

**Comment by Ge0** [comment]
Hello,

J'ai mis la configuration à jour et c'est normalement ok. Si quelqu'un pouvait tester pour confirmer...

**Comment by firm1** [comment]
> J'ai mis la configuration à jour et c'est normalement ok.

Ne pas oublier de reporter la conf sur la préprod du coup.

**Comment by SpaceFox** [comment]
> Ne pas oublier de reporter la conf sur la préprod du coup.

Argh.

**Comment by Situphen** [comment]
Corrigé par @SpaceFox !
