### ISSUE TITLE
Le fichier AUTHORS n'est pas à jour

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2659]
Le [fichier des contributeurs](https://github.com/zestedesavoir/zds-site/blob/dev/AUTHORS) n'est pas à jour. Il y'a **au moins** @DevHugo qui contribue pas mal depuis un moment qui n'y est pas encore.

**Comment by DevHugo** [comment]
Personnellement, pour faire très simple, je m'en fout royalement d'être dans ce fichier ^^. Après la question peut-être élargie, à quoi sert réellement ce fichier et comment on le maintient  =) !

**Comment by pierre-24** [comment]
De manière générale, [la liste des contributeurs du dépot](https://github.com/zestedesavoir/zds-site/network/members) est plus à jour, non ?

**Comment by DevHugo** [comment]
Si y'a pas de raison légale pourquoi le garder ?

**Comment by Eskimon** [comment]
Plutot ca pierre-24 : https://github.com/orgs/zestedesavoir/people

**Comment by pierre-24** [comment]
Oui, mais cette page là renseigne uniquement les personnes "reconnues" qui font des contributions régulières. Par exemple, Alex-D n'y est plus, alors que sans lui, ZdS serait probablement nul part. Non ?

**Comment by Eskimon** [comment]
Du coup on met celle-ci et en avant guingamp : https://github.com/zestedesavoir/zds-site/graphs/contributors

**Comment by pierre-24** [comment]
Mergé, donc merci @Eskimon  :)
