### ISSUE TITLE
Markdown : la valeur par defaut du langage du code doit être le texte

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#266]
Il s'agit d'un problème d'affichage qui est illustré sur [ce post](http://preprod.zestedesavoir.com/forums/sujet/12/mon-nouveau-super-sujet?page=1#p105)

On voit très clairement que lorsqu'on ne précise pas le langage pour le code, le markdown (ou pygments je sais plus) va essayer de deviner ce qui est à l'extérieur. Et en voyant une quote pas fermée, il réagit en l'entourant de rouge.

Une façon simple de résoudre ce problème serait de faire en sorte que lorsqu'un text est saisi entre les ``` sans précision du code, il ait le même comportement que si on avait saisi le code de type `text`

**Comment by cgabard** [comment]
ok, avec le fork ça ne devrait pas être dur à faire

**Comment by cgabard** [comment]
Je me demande si du coup il ne faudrait pas plutôt en faire une issue [sur le fork directement](https://github.com/zeste-de-savoir/Python-ZMarkdown)

**Comment by firm1** [comment]
hm, c'est pas con et c'est logique.

**Comment by cgabard** [comment]
Pour compléter, il me semble que lorsqu'il tente de deviner le langage il renvoit une pseudo probabilité. Il faudrait voir si elle ne permet pas de régler ça : si le meilleur langage détecté à une proba inférieur à un seuil, on ne prend pas de risque et on passe en texte.

Cela à l'avantage que pour les debutants qui ne préciseront pas le langage, la coloration syntaxique pourrat être activée toute seule. Par contre ça risque d'en surprendre de temps en temps (des fois elle s'active, des fois non) mais il faudrat simplement expliquer que parfois le moteur n'arrive pas à détecter le langage avec assez de confiance

**Comment by firm1** [comment]
> Cela à l'avantage que pour les debutants qui ne préciseront pas le langage, la coloration syntaxique pourrat être activée toute seule. Par contre ça risque d'en surprendre de temps en temps

Perso, je ne trouve pas ça forcément propre, d'avoir un affichage qui varie selon certaines règles mystiques que je ne maîtrise pas.

De plus, en lisant la doc [à ce niveau](https://pythonhosted.org/Markdown/extensions/code_hilite.html#when-no-language-is-defined), je constate qu'il existe un paramètres qui permet d'empêcher la lib de deviner le langage. Pour moi c'est là qu'il faudrait taper. ça offre l'avantage d'un parsing encore plus performant étant donné qu'il n'aura plus besoin de chercher à deviner.

> Note : When no language is defined, the Pygments highlighting engine will try to guess the language (unless guess_lang is set to False). Upon failure, the same behavior will happen as described above.

**Comment by cgabard** [comment]
Ok, si tu prefère, ça me va. Je peux probablement te faire un rapide fix du coup

**Comment by cgabard** [comment]
Normalement corrigé, je ferme

**Comment by firm1** [comment]
Je confirme que le [fix marche magnifiquement bien](http://preprod.zestedesavoir.com/forums/sujet/12/mon-nouveau-super-sujet?page=1#p105).

Merci pour la réactivité.
