### ISSUE TITLE
Il y'a des boutons inutilisables dans les MPs

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2662]
Scénario : 
- Allez dans un MP que vous partagez avec quelqu'un
- Allez sur un message et faites clic-droit sur le bouton citer, puis "copier le lien"
- Coller le lien dans la barre d'adresse de votre navigateur préféré et validez

**Problème** : on constate que dans la liste des messages en dessous, on a des boutons "signalez", "masquer" qui n'ont pas lieu d'être car on ne peut pas signaler un MP ni masquer son message normalement.

**Comment by GerardPaligot** [comment]
Tu cherches la merde @firm1 ! ^^

**Comment by DevHugo** [comment]
https://github.com/zestedesavoir/zds-site/blob/dev/templates/mp/post/new.html#L65 manque un with can_hide=False.

Mais c'est vrai que la tu as dépassé le niveau de fourberie pour trouver des bugs là.

**Comment by Eskimon** [comment]
Et voila, c'est corrigé !
