### ISSUE TITLE
Passer aux build dans des container sur travis

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#2664]
Travis a actuellement deux infrastructure pour les build. L'ancienne, que l'on utilise actuellement, virtualise entièrement un environnement linux. Une nouvelle architecture utilisant des container (type Docker) est [depuis quelques mois disponible](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/), et propose des builds bien plus rapide (démarre plus rapidement, et permet d'utiliser le cache).

Cependant, le passage vers cette infrastructure demande de ne plus rien lancer en root, et que les paquets apt que l'on utilise soient dans la liste [des paquets dans cette liste](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise), pour des raisons de sécurité. La plupart de ceux que l'on utilise sont dans cette liste, sauf tout ce qui est `texlive[-*]`, et `python-mysqldb`.

Plus d'info [dans leur doc](http://docs.travis-ci.com/user/workers/container-based-infrastructure/), et dans [cet article](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/)

**Comment by GerardPaligot** [comment]
Quel est l'objectif de cette issue si nous avons des dépendances non compatibles ? De trouver des alternatives compatibles ?

**Comment by sandhose** [comment]
Ouais, c'est pour voir si c'est éventuellement possible, histoire
d'accélérer les builds. On a eu le problème ce soir par exemple,
l'architecture de build legacy de travis était surchargé, et les builds ont
mis 20 min a démarrer...

Le lun. 11 mai 2015 23:54, Gérard Paligot notifications@github.com a
écrit :

**Comment by DevHugo** [comment]
On peut aussi proposer les binaires comme expliqué dans la doc.

> If you require sudo, for instance to install Ubuntu packages, a workaround is to use precompiled binaries, uploading them to S3 and downloading them as part of your build, installing them into a non-root directory.
