### ISSUE TITLE
[Beta 15.5.1] Le design de la page d'aide aux tutos est tout cassé

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2667]
Server: Beta
Version: v15.5½-RC1/c5e6bcc
Page incriminée: http://beta.zestedesavoir.com/tutoriels/aides/

Une image vaut mieux qu'un long discours (cache rafraichie):

![capture du 2015-05-12 22 20 25](https://cloud.githubusercontent.com/assets/761168/7597620/1b53a7f6-f8f5-11e4-9de9-d0ab983fcfd5.png)

Et la version correcte en prod donne:
![capture du 2015-05-12 22 20 51](https://cloud.githubusercontent.com/assets/761168/7597644/316a6bba-f8f5-11e4-8184-f0c2073b5c5b.png)

ping @sandhose et @Situphen ;)

**Comment by sandhose** [comment]
Pour cette page, j'ai rapidement fait cette aprem un design pour les éléments de cette page, qui reprend le design des éléments sur l'accueil:

![](http://s.sandhose.fr/zestedesavoir/help-item.gif)

(il s'agit de l'animation au hover, et elle sera bien sûr plus rapide et plus clean "en vraie", c'est juste pour montrer l'idée)

Je sais pas si j'aurais le temps de l'implémenter ; ping @Situphen, si tu as le temps

**Comment by Situphen** [comment]
Je n'aurais pas le temps et puis du bugfix reste du bugfix : on se contente de résoudre le problème, point final !

J'aime super bien l'idée (quoique que c'est un peu trop gris) ! Je crois avoir entendu parlé qu'il y aura peut-être une deuxième itération de la ZEP 3, je te conseille donc de proposer ton idée sur le forum. ;)

**Comment by sandhose** [comment]
PR ouverte: #2717

**Comment by GerardPaligot** [comment]
Merci @sandhose pour le fix !
