### ISSUE TITLE
[Beta 15.5.1] Sur le serveur les articles n'ont pas d'icône

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2668]
Sur le serveur de bêta (Version : v15.5½-RC1/c5e6bcc), les articles n'ont pas d'icônes. Ce n'est pas simplement un problème d'image indisponible : l'icône n'est pas définie dans le HTML.

**Comment by Eskimon** [comment]
Je pense que ta migration a buggue... Dans ma page "Mes articles" certains ont une image. d'autres pas...

![screenshot from 2015-05-13 09 34 41](https://cloud.githubusercontent.com/assets/761168/7605790/6323c864-f953-11e4-96a3-29b45f9103d3.png)

**Comment by SpaceFox** [comment]
C'est bizarre... Qu'est-ce qu'il y a eu comme modifications à ce sujet ?
D'où proviennent les images des articles ?

2015-05-13 9:35 GMT+02:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
Ohhhh j'ai peur...

Voici deux URL d'illustrations d'articles prises en prod (pour comparer l'article qui marche et celui qui marche pas):
- Interview Spacefox : `/media/articles/44/8a06fd25-16f6-430f-81e0-d60aab649c6f.png.60x60_q85_crop.jpg`
- Interview Piwit : `/media/articles/None/ff119055-4a61-446d-b7e6-5af37fb979ba.jpg.60x60_q85_crop.jpg`

Tu vois pourquoi j'ai peur ?

**Comment by pierre-24** [comment]
Moi je vois pas, je devrais ?

**Comment by Eskimon** [comment]
Dans la première (qui marche) on a un id, dans la deuxième (qui marche pas) on a `None`

**Comment by pierre-24** [comment]
Oui, ça j'ai vu, mais la question, c'est qu'est ce qui s'est passé pour que ça arrive, d'autant que dans mes souvenirs,  [ce lien là est copié en dur en BDD par le modèle](https://github.com/zestedesavoir/zds-site/blob/dev/zds/article/models.py#L67). Donc à priori, je commencerai par voter pour un truc qui a pas fonctionné dans le _dump_ de la BDD.

**Comment by Eskimon** [comment]
Justement, ces deux adresses viennent de la **prod**

**Comment by pierre-24** [comment]
Aaaaah, j'avais pas fait attention, toutes mes excuses. 

Ceci étant dit, je crois qu'on à deux problèmes différents, ici: et d'un, on a ce truc bizarre sur l'image de l'interview de Piwit, mais qui n’apparaît que pour celui là (en prod, donc je viens d'aller vérifier). À mon avis, fausse manip ou on a du bousiller notre BDD à un moment.

De l'autre, on à cette histoire d'image. Là, il va falloir aller regarder ce que contient la table "gallery_image" en BDD avant de se prononcer (Spacefox, c'est à toi).

**Comment by Eskimon** [comment]
Ah mon avis le "bousillage de BDD" entraine aussi la merde sur la preprod...

**Comment by Eskimon** [comment]
Du coup je suis le seul a etre inquiet de voir un `None` comme id ?

**Comment by pierre-24** [comment]
Ben là, en l'occurence, c'est uniquement sur l'article que tu as cité. Pour moi, c'est pas ça le problème :o

**Comment by firm1** [comment]
ça ressemble très fortement à un problème de migration (et anonymisation) de la base de donnée de prod vers la beta (donc plutot infra finalement). J'ai publié un article recemment et visiblement on a bien l'image de son article.

Est-ce qu'on peut vérifier que la migration des datas a bien réussie ?

**Comment by SpaceFox** [comment]
_Data_, même au pluriel.

J'ai déjà une API complète avec cette faute au boulot, c'est pas pour la retrouver ici :)

**Comment by firm1** [comment]
hihi, j'ai trouvé un nouveau moyen de te troller alors :)

**Comment by SpaceFox** [comment]
N'essaie même pas.

**Comment by Eskimon** [comment]
Donc il y a que moi que ca derange que **en prod** j'ai des images d'articles avec des pk et d'autres avec des None ?

**Comment by SpaceFox** [comment]
Non, ça me dérange aussi...

**Comment by pierre-24** [comment]
C'est ennuyeux, mais pas critique. Pour moi, ça veux dire que pour une raison donnée, ces articles là ont vu l'upload de l'image être complètement bousillé. [Et c'est pas étonnant, parce que je m'étonne de la manière dont c'est écrit dans le code](https://github.com/zestedesavoir/zds-site/blob/dev/zds/article/models.py#L203) ([et plus précisément ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/article/models.py#L39), à mon avis ça arrive quand on uploade l'image en même temps qu'on crée l'article), je vous avoue que je suis pas étonné que ça bugge. Mais c'est pas grave, dans le sens ou le dossier `None` existe tout de même et qu'il est censé être transféré avec le reste du contenu de `/media/` quand on fait des `rsync` pour les galeries (puisque stocké dans le même coin). Si ça vous choque tant que ça, je parie que réuploader l'image va régler le problème, et bonus, c'est une info non-versionnée, donc pas besoin de revalider les articles en question ;)

Une fois encore, c'est pas ça le problème, pour moi !

**Comment by pierre-24** [comment]
Je confirme: créer un article en remplissant le champ "image" à la création envoi l'image dans un dossier `None` (parce que `pk` est pas défini au moment de la création), réuploader l'image la balance au bon endroit :)

**Comment by GerardPaligot** [comment]
On a un bug identifié ici ? On sait si c'est à cause d'une mauvaise manipulation sur la preprod ?

**Comment by Eskimon** [comment]
C'est pas une mauvaise manip non. Pour résumé : lorsqu'on crée un article avec immédiatement une image, cette dernière est chargée sur le disque dans un dossier 'None' au lieu de l'id. Apparemment la prod' le vit bien mais le passage en preprod (et nouvelle page d'accueil?) a mis en évidence ce bug (qui sera corrigée en zep-12 j'imagine)

**Comment by pierre-24** [comment]
> qui sera corrigée en zep-12 j'imagine

Oui, c'est corrigé. Et logiquement, le script de migration remettra tout au bon endroit dans une galerie qui va bien. Reste à ce demander pourquoi les images qui sont pas dans un dossier `None` s'affichent quand même pas.

**Comment by Eskimon** [comment]
> Reste à ce demander pourquoi les images qui sont pas dans un dossier None s'affichent quand même pas.

J'ai l'impression que ce sont tout simplement des fichiers manquants. En effet, le dossier `media/articles/None/` existe bien en preprod et possède quelques images (5 + leur miniatures). Si je prend par exemple l'interview sur Taguan, en prod on constate que la source est bien dans ce dossier mais en preprod je ne vois pas l'image pour autant.

Question @SpaceFox , est-il possible que des fichiers n'aient pas été copié lors du transfert ?

**Comment by SpaceFox** [comment]
C'est possible oui.

**Comment by pierre-24** [comment]
Et donc ?

**Comment by SpaceFox** [comment]
Vu que tous les articles en prod ont un article, c'était bien un problème de synchro.

Je ferme ici.
