### ISSUE TITLE
[Beta 15.5.1] Problèmes de performances / liste des tutos

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2669]
La liste des tutos est devenue **beaucoup** plus lourde avec la nouvelle version (Version : v15.5½-RC1/c5e6bcc). En mode connecté avec un compte admin :
- Avant : 383102 function calls (370015 primitive calls)
- Après : 665289 function calls (646091 primitive calls)

Il faut vérifier et réduire ça sous peine d'avoir des désagréables surprise sle jour de la MEP.

**Comment by GerardPaligot** [comment]
On a un indice de quelque chose ? La vue sur cette page n'a pas changé depuis un bon moment.

**Comment by SpaceFox** [comment]
C'est le passage au nouvel affichage des blocs.

**Comment by GerardPaligot** [comment]
Donc, c'est un problème front non ?

**Comment by SpaceFox** [comment]
Ben, pas vraiment non.

**Comment by SpaceFox** [comment]
Brace yourselves, Memcached is coming!

**Comment by pierre-24** [comment]
Caching _merged_ !
