### ISSUE TITLE
[Beta 15.5.1] Ajouter la taille voulue de l'image dans l'interface des unes

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2670]
L'interface d'admin des Unes de la nouvelle page d'accueil n'indique pas la taille voulue pour l'image. Ce serait plus pratique si c'était le cas.

**Comment by Eskimon** [comment]
On peut completer au choix le label ou le placeholder ici : https://github.com/zestedesavoir/zds-site/blob/dev/zds/featured/forms.py#L50

(PS le format est 228x228 px tu confirmes @sandhose  ?)

**Comment by sandhose** [comment]
Je confirme, c'est bien 228x228

**Comment by GerardPaligot** [comment]
Merci à @sandhose pour le fix.
