### ISSUE TITLE
[Beta 15.5.1] Problèmes de performances / accueil

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2671]
La page d'accueil est devenue sensiblement plus lourde avec la nouvelle version (Version : v15.5½-RC1/c5e6bcc). En mode connecté avec un compte admin :

Avant : 116163 function calls (113347 primitive calls)
Après : 199479 function calls (195344 primitive calls)

Il faut vérifier et réduire ça sous peine d'avoir des désagréables surprises le jour de la MEP.

**Comment by Eskimon** [comment]
Je suppose que ça vient de l'affichage de plus d’éléments (comme les forums par exemple), du coup peut-on vraiment y faire grand chose ?

**Comment by SpaceFox** [comment]
1. Il faut vérifier que l'affichage est fait de manière efficace
2. C'est la page la plus affichée du site, donc elle doit être performante. Au pire, on peut commencer à jouer avec les caches.

**Comment by SpaceFox** [comment]
La PR de @GerardPaligot remet le compteur d'appels de méthodes à une valeur proche de l'actuelle, donc je considère ce ticket comme fermé.
