### ISSUE TITLE
[Beta 15.5.1] Typos sur le texte d'accueil en mode déconnecté

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2673]
Il y a des typos sur le nouveau texte d'accueil en mode déconnecté ("annimés" par exemple).

Plus généralement, on pourrait améliorer ce texte, ne serait-ce que par de la mise en forme.

**Comment by firm1** [comment]
Pour ce qui est de la typo, on a aussi `Tout les membres peuvent écrire et publier des tutoriels`. C'est **Tous les membres**

**Comment by firm1** [comment]
"par et pour les communautés. " => "par et pour **la communauté**."

**Comment by firm1** [comment]
"et garanti sans publicité, le site est géré et".

C'est un point qu'il faudrait à la place de la virgule par exemple.
