### ISSUE TITLE
Les filtres de tags "complexes" sur les articles ne fonctionnent pas

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2674]
Aucun des filtres de tags sur les articles qui est plus compliqué que "un seul mot" (exemples : "GNU/Linux", "1er avril", ...) ne fonctionne pas (le filtre n'est pas actif et on voit tout).

Ce n'est pas un bug de la nouvelle version 15.5.1 (il est déjà en prod) mais il devient gênant parce que les tags sont **beaucoup** plus visibles avec la nouvelle home et les nouvelles pages de tutos / articles.

Tout est OK en ce qui concerne les tags des tutos.

**Comment by Eskimon** [comment]
Faudrait essayer de comparer avec les tutos... Mais sinon coucou les copains de la ZEP-12 ( @artragis et @pierre-24 ) je suppose que chez vous la solution sera bien générique :)

**Comment by artragis** [comment]
chez nous les tags des tutos et des articles sont les mêmes donc faudra juste tester.

**Comment by Eskimon** [comment]
Et j'ai trouve le souci ! C'est "simplement" que l'on passe le nom du tag plutot que son slug pour faire le href ici : https://github.com/zestedesavoir/zds-site/blob/dev/templates/article/includes/article_item.part.html#L76

(du coup c'est vite corrige :) )

**Comment by pierre-24** [comment]
Je sais plus si c'est le nom ou le slug que j'ai retenu au final dans la ZEP-12 ;)

**Comment by pierre-24** [comment]
... [On est bon côté ZEP-12](https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/tutorialv2/includes/content_online_item.part.html#L27) !

**Comment by GerardPaligot** [comment]
Merci à @Eskimon pour le fix et @DevHugo pour la QA.

**Comment by firm1** [comment]
Je réouvre cette issue, car, elle n'est pas corrigée entièrement.

En allant [ici](http://beta.zestedesavoir.com/articles/) ou [là](http://beta.zestedesavoir.com/) et en cliquant sur le tag "Gnu/Linux" on tombe sur le bug.

La correction doit aussi être appliquée sur les nouveaux items.

**Comment by pierre-24** [comment]
Moui. Sauf que à priori, cette issue est taguée "version de développement", et donc n'est PAS corrigée dans cette bêta ;)

**Comment by firm1** [comment]
En effet, je me suis quelque peu emmêlé les pinceaux entre les versions

Le mar. 26 mai 2015 12:56, Pierre Beaujean notifications@github.com a
écrit :
