### ISSUE TITLE
[Beta 15.5.1] Erreur de punchline sur mobile

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2675]
Sur mobile en mode déconnecté, le site affiche : _"Zeste de Savoir, le site de partage de connaissances, sans pépins !"_.

Ce devrait être _"Zeste de Savoir, la connaissance pour tous et sans pépins"_.

**Comment by GerardPaligot** [comment]
Merci à @sandhose pour le fix.
