### ISSUE TITLE
[Beta 15.5.1] Manque un espace dans les catégories de tutoriels sur l'accueil

### ISSUE THREAD

**Issue by Luuka** [zestedesavoir/zds-site#2676]
Sur la page d'accueil dans la partie `Derniers tutoriels` : Il manque un espace avant le "et" dans la liste des catégories des tutoriels.

![betazds](https://cloud.githubusercontent.com/assets/5896831/7599784/517c2140-f905-11e4-80a4-d6e772b91640.jpg)

**Comment by Eskimon** [comment]
Un petit espace ici : https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorial/includes/tutorial_item.part.html#L21

**Comment by SpaceFox** [comment]
Corrigé, merci !

**Comment by Eskimon** [comment]
Pourquoi c'est réouvert ?

**Comment by Situphen** [comment]
Erreur, désolé :(
