### ISSUE TITLE
[Beta 15.5.1] Les unes ne s'affichent pas sur mobile

### ISSUE THREAD

**Issue by Fulbert** [zestedesavoir/zds-site#2678]
Sur Chrome (42.0.2311.111) et Firefox (38.0) sur Samsung Galaxy SIII (Android 4.3).
Le bug est présent que l'on soit connecté ou non.

![screenshot_2015-05-12-16-51-17](https://cloud.githubusercontent.com/assets/4991264/7601157/84aedf3c-f8c7-11e4-94aa-84d4c1f12258.png)

J'imagine que c'est parce qu'il y a qu'une seule une pour le moment sur la beta (en tout cas j'en vois qu'une qui s'affiche sur desktop).

**Comment by Eskimon** [comment]
Ca viendrait pas de ca : https://github.com/zestedesavoir/zds-site/blob/fb0cb8e94e534836e5159f372c48a20b9765cc70/assets/scss/pages/_home.scss#L327 ? et que du coup comme on a qu'une seule Une ca fout la merde

**Comment by sandhose** [comment]
C'est effectivement le fait qu'on a qu'une seule une, puisque les deux dernières sont enlevées sur mobile. Je ferme, donc
