### ISSUE TITLE
[Beta 15.5.1] Erreur 500 lors de la consultation d'un tutoriel

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2681]
Url incriminée :http://beta.zestedesavoir.com/tutoriels/388/les-cartes-graphiques/516/pipeline-non-programmable/2536/rasterization/

Le problème n'existe pas en prod par contre : http://zestedesavoir.com/tutoriels/388/les-cartes-graphiques/516/pipeline-non-programmable/2536/rasterization/

**Comment by Eskimon** [comment]
hum sans stacktrace ca va etre dur...

**Comment by pierre-24** [comment]
... Sentry est mort, 502 bad gateway :/

http://sentry.kisai.info/

ping @SpaceFox

**Comment by SpaceFox** [comment]
Ha, j'ai oublié de le remettre en route quand j'ai réinstallé mon serveur...

2015-05-13 15:37 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by Eskimon** [comment]
Je passe en bloquant, on peut pas se permettre de se prendre des 500 a la lecture des tutos.

**Comment by GerardPaligot** [comment]
Faudrait quand même la stacktrace puisque le bug est reproductible facilement.

**Comment by Eskimon** [comment]
Bon, on fait comment ici ? Car si ce bug est pas corrigé alors pas de release (on va pas s'amuser a prendre le risque de voir tout nos tutos pété...)

**Comment by GerardPaligot** [comment]
Faut juste trouver un moyen de récupérer la stacktrace. Après, on pourra bosser dessus.

**Comment by pierre-24** [comment]
Yep. Quitte à ce qu'un dev' provoque l'erreur exprès pendant que l'autre regarde le log.

**Comment by GerardPaligot** [comment]
@SpaceFox ou @firm1, vous pouvez vous en charger ?

**Comment by SpaceFox** [comment]
J'essaierai d'y penser demain soir, fais-moi signe si j'oublie.

**Comment by SpaceFox** [comment]
L'erreur est :

```
[ERROR] -- 2015-05-24 23:47:01,096 -- base : Internal Server Error: /tutoriels/388/les-cartes-graphiques/516/pipeline-non-programmable/2536/rasterization/
Traceback (most recent call last):
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/zdsenv/ZesteDeSavoir/zds/tutorial/views.py", line 1815, in view_chapter_online
    "r")
IOError: [Errno 2] No such file or directory: u'/opt/zdsenv/ZesteDeSavoir/tutoriels-public/388_les-cartes-graphiques/516_pipeline-non-programmable/2536_rasterization/introduction.md.html'
```

On dirait un problème de synchronisation des données prod --> bêta, puisque sur la bêta dans ce tuto le sous-dossier 516 s'appelle _516_les-composants-dune-carte-graphique_ et non _516_pipeline-non-programmable_.

À noter que sur la prod, c'est bien _516_les-composants-dune-carte-graphique_ qui est présent et attendu.

C'est très facilement explicable si ce dossier a été renommé entre l'export de la BDD pendant la nuit, et la copie des données des tutos le soir.

**Comment by pierre-24** [comment]
Mouais. Ça va être dur de faire plus que ça ... Non ?

**Comment by Eskimon** [comment]
Ah moins d'avoir un autre tuto qui bug aussi... QQun a-t-il eu une erreur sur un autre tuto ?

**Comment by SpaceFox** [comment]
Si quelqu'un a le courage de vérifier l'historique d'édition de ce tuto en prod ?

**Comment by Eskimon** [comment]
Voici les dates vues en prod' : http://pastebin.com/YaQC8gSB

**Comment by pierre-24** [comment]
Pourquoi il y a deux fois "en ligne" ?

**Comment by Situphen** [comment]
Qu'est-ce qu'on peut faire ici ?

**Comment by Eskimon** [comment]
Bon j'ai testé des trucs en long/large/travers avec un nouveau tuto et je n'arrive pas à reproduire de scénario mettant un tuto en vrac. Je pense vraiment qu'on est tombé sur un coup de pas de bol sur le moment ou la copie des données a été faite. Je ferme car j'ai bien peur qu'on ne trouvera pas de meilleur explication...

**Comment by firm1** [comment]
Peut-être dans ce cas il faudra refaire la copie des données alors et croiser les doigts pour que ce soit vraiment ça ? J'aurai laissé l'issue ouverte en passant le tag coté infra.

**Comment by Eskimon** [comment]
La copie de donnée prend un certain temps quand même. Si tu veux le faire je t'en prie (idem @SpaceFox ) et dans ce cas je te laisse ré-ouvrir le ticket :) Mais sinon faute de mieux on peut rien faire. J'ai trainer sur plusieurs autres big-tutos sans aucun souci.

**Comment by firm1** [comment]
Je comprend bien, je dis juste que le problème de fond du coup est un problème infra ('fin j'espère) et donc plus bloquant. C'est grave de laisser le ticket ouvert au moins pour que quelqu'un pense à le corriger ?

**Comment by Eskimon** [comment]
Dans ces cas-là ne vaudrait-il pas mieux faire un autre ticket du genre "Faire un script fiable de synchro prod-preprod" ? Parce que là on aura une discussion qui n'aura plus rien à voir

**Comment by SpaceFox** [comment]
C'est pas un problème de script de synchro à mon avis. C'est tout simplement que vue que la copie est très longue, on ne peut pas garantir une cohérence parfaite entre l'état de la BDD et l'état des dépôts Git.

Il n'y a que 2 moyens de garantir ça :
1. Arrêter l'application le temps de la copie
2. Avoir un système de fichier qui gère les snapshots et utiliser cette fonctionnalité

**Comment by firm1** [comment]
Y'a pas moyen de faire la copie depuis le serveur de sauvegarde plutot ?

**Comment by SpaceFox** [comment]
Non. Récupérer une sauvegarde depuis le serveur de sauvegarde, c'est chiant.

PS : C'est normal que ce soit chiant. C'est un Bacula, et donc c'est un outil de sauvegarde (qui gère l'historique, la rétention, etc...), pas un outil de "je copie dans un coin".
