### ISSUE TITLE
Url de création d'un message privé absente de la doc

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2688]
La [doc de l'API](http://beta.zestedesavoir.com/api/) répertorie un ensemble d'url et pas celle de création d'un mp.

**Comment by GerardPaligot** [comment]
Toujours le même problème que d'habitude. Les URLs du premier niveau ne s'affichent pas sur la bêta/prod alors qu'elle s'affiche bien en local chez tout le monde. Je change le tags et je préviens @SpaceFox.

**Comment by GerardPaligot** [comment]
Cette issue est directement liée à cette issue (https://github.com/zestedesavoir/zds-site/issues/2286). Je ferme ici.
