### ISSUE TITLE
[v15.5-1/2] Le site n'est plus compatible IE9

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2689]
Alors que la page d'acceuil étaient pleinement compatible IE9 en v15.5 (comme en témoigne les screens suivants), la page d'acceuil n'est plus du tout compatible IE9. Je suppose qu'il s'agit d'une regression sauf si on a décidé à un moment l'arrêt du support de IE9.

**Ancienne Home (v15.5)** : 

![ie-good](https://cloud.githubusercontent.com/assets/6066015/7611294/d271396a-f983-11e4-91c4-32192491b0e7.PNG)

**Nouvelle Home (v15.5-1/2)** : 

![ie-1](https://cloud.githubusercontent.com/assets/6066015/7611297/d7ed8a06-f983-11e4-8357-0cf9ed276f97.PNG)

![ie-2](https://cloud.githubusercontent.com/assets/6066015/7611300/dc840612-f983-11e4-8285-29b462e6dfa1.PNG)

![ie-3](https://cloud.githubusercontent.com/assets/6066015/7611301/e218f97a-f983-11e4-9ef1-a6e6a959bad4.PNG)

**Comment by GerardPaligot** [comment]
Je demande confirmation à @SpaceFox mais il semble avoir donné le feu vert pour stopper la compatibilité.

**Comment by SpaceFox** [comment]
En fait ce n'est même pas une régression : [Zeste de Savoir n'a _jamais_ supporté IE9](https://github.com/zestedesavoir/zds-site/issues/2054#issuecomment-70379227). Le support n'a existé que parce que A-312 a voulu faire la PR de support un jour.
