### ISSUE TITLE
Les tests fronts ne passent plus sur Travis

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2690]
Tout est dans le titre.

Ping @sandhose et @Situphen

**Comment by pierre-24** [comment]
Le problème se situant au niveau de `python-gyp`. Ça peut être passager comme ça peut être un vrai bug méchant.

**Comment by Situphen** [comment]
Le problème vient de "lwip", une dépendance de "gulp-sass". C'est pas la première fois (en faite c'est tout le temps elle qui foire).

Trois solutions :
- attendre que ça passe ;
- utiliser "npm shrinkwrap" (je pense que ça pourrait résoudre ça mais ça y crée un fichier de 20000 lignes environ) ;
- changer pour utiliser le vrai logiciel sass mais faut installer ruby et tout le bouzin derrière.

Il faudrait voir s'il n'y a pas des alternatives JS à "gulp-sass", ce serait la meilleur solution.

**Comment by pierre-24** [comment]
Bon. Heureusement que c'est pas arrivé hier soir, sinon j'entend déjà @SpaceFox crier d'ici. Par contre, c'est particulièrement ennuyeux puisqu'il y a plein de bugfix de la page d'accueil qui concernent le _front_. D'ailleurs, question: est ce qu'il y a éventuellement moyen d'utiliser celui buildé par Travis hier ? Parce que évidement, ce matin, j'ai du faire un `npm install`. Je vous laisse imaginer l'état de ma version locale actuellement --"

**Comment by SpaceFox** [comment]
Je crois qu'il devient **urgent** de trouver une stack **fiable** pour le front. Vraiment.
