### ISSUE TITLE
Les tests backs ne génèrent plus les fichiers pandoc

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2691]
Tout est dans le titre mais ils cherchent des choses dans les templates, je tag donc front.

``` console
pandoc: Could not find data file templates/default.html
pandoc: Could not find data file templates/default.epub
```

**Comment by Eskimon** [comment]
En local ? Sur Travis ?

**Comment by sandhose** [comment]
C'était dû au fait que tox exposait plus les variables d'environnement. Ca a donc été fixé avec ma PR récente sur travis. Je ferme
