### ISSUE TITLE
[Beta 15.5.1] La rubrique mes tutoriels me renvoit vers la version online d'un tutoriel

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2692]
Page incriminée : http://beta.zestedesavoir.com/membres/tutoriels/

**Problème** : Toutes les urls de mes tutoriels en cours d'écriture pointent vers la version online plutôt que vers la version offline. Ce qui fait que la plupart du temps, mes tutos non publiés me renvoient vers une 404

**Comment by GerardPaligot** [comment]
Merci à @sandhose pour le fix.
