### ISSUE TITLE
[Beta 15.5.1] Le menu d'accessibilité ne fonctionne plus

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2693]
Avec la nouvelle page d'acceuil le menu dédié à l'accessibilité de nous ramène plus au bon endroit. Pour ce qui ne l'ont jamais vu, il ressemble à ça : 

![accessibilite](https://cloud.githubusercontent.com/assets/6066015/7614152/3de4d196-f995-11e4-9765-5c1aa24fad86.PNG)

Pour y acceder, il suffit d'aller sur beta.zestedesavoir.com et d'appuyer sur la touche `TAB` de votre clavier. Il permet aux mal voyants d'acceder rapidement aux menus, au contenu, ou a la recherche.

Le problème c'est que depuis la nouvelle Home ce menu ne fonctionne plus. C'est donc une regression pour l'accessibilité.

**Comment by SpaceFox** [comment]
Pour être tout à fait honnête, j'ignorais jusqu'à l'existence de ce menu.
Peut-on vérifier qu'elle est bien documentée quelque part ?

**Comment by firm1** [comment]
> Peut-on vérifier qu'elle est bien documentée quelque part ?

Ce n'est clairement pas documenté ce truc

**Comment by sandhose** [comment]
Euh, il fonctionne bien...
Le menu va bien... Au menu ;  le contenu, c'est à partir du texte de présentation, et la recherche va bien sur le champ de recherche...

**Comment by Eskimon** [comment]
Oui j'ai l'impression que ca marche aussi, en tout cas le comportement est le meme qu'en prod et personne ne s'en ai jamais plaint...

**Comment by sandhose** [comment]
On peut fermer, du coup ?

**Comment by firm1** [comment]
Z'etes sur qu'il fonctionne bien ? Chez moi (firefox) j'ai perdu en accessibilité. 
- Lorsque je décide d'aller vers le menu, il m'y amène : pas de problème.
- Lorsque je décide d'aller à la recherche : il m'y amène, mais le problème c'est que je ne peut pas saisir dans cette recherche, donc je suis obligé d'utiliser ma souris pour que le cusrseur y soit : **pas ok**
- Lorsque je décide d'aller au contenu : il m'emmene, au niveau de la puchnline, et je dois (à coup de tab) reparcourir tout depuis en haut. (il faut essayer sur la prod pour s'en rendre compte).  : **pas ok**

Je réouvre donc :)

**Comment by Eskimon** [comment]
> Lorsque je décide d'aller à la recherche : il m'y amène, mais le problème c'est que je ne peut pas saisir dans cette recherche, donc je suis obligé d'utiliser ma souris pour que le cusrseur y soit : pas ok

C'est deja comme ca en prod' en tout cas.

Du coup je vois pourquoi reouvrir, mais on est d'accord c'est du bug, pas de la regression ?

**Comment by firm1** [comment]
> C'est deja comme ca en prod' en tout cas.

Non, en prod, je fais ça : 
- `<Tab>`
- "Aller à la recherche"
- `<Enter>`
- `<Tab>`
- Je peux saisir ce que je veux dans la recherche.
- `<Enter>`
- J'ai mon résultat de recherche

**Comment by Eskimon** [comment]
pas sur chrome :( (mais effectivement oui sur Firefox)

**Comment by firm1** [comment]
Donc on a bien regraissé ?

**Comment by Eskimon** [comment]
Vi effectivement sur FF :)

**Comment by Eskimon** [comment]
Toujours pas OK sur Chrome. Quand je selectionne "aller a la recherche" puis fais `<tab>` je retourne au menu d'accessibilite

**Comment by pierre-24** [comment]
Donc, ça, @sandhose l'as fait ;)
