### ISSUE TITLE
[Beta 15.5.1] Nouvelle home et Windows Phone

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#2694]
En testant la préprod sur mon WP, j'ai pu remarqué que la nouvelle home avait des problèmes au niveau des articles, quand il y a plusieurs auteurs (+ 2 en particulier ou deux avec un long pseudo).

Voyez par vous-même : 

![wp_ss_20150513_0001](https://cloud.githubusercontent.com/assets/4312887/7614234/cc892906-f995-11e4-8bfd-6ca3801c6e8b.png)

ping @sandhose @Situphen

**Comment by Situphen** [comment]
Je renommerais ça en "Nouvelle home et petits écrans" ! :D

Note : Il faudrait passer les dates dans un format plus court et couper les auteurs avec "...". Ou mettre tout en police plus petite mais au risque que ce soit quasiment illisible !

**Comment by Axylium** [comment]
> Je renommerais ça en "Nouvelle home et petits écrans" ! :D

Ah, je ne sais pas, je n'ai pas pu tester sur d'autres terminaux et vu que c'est Internet Explorer, j'ai pas chercher plus loin.. ^^

**Comment by GerardPaligot** [comment]
Merci à @sandhose pour le fix.
