### ISSUE TITLE
Derniers sujets sur la Home : la date sur mobile n'est pas optimisée 

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2695]
Sur mobile on à en général pas beaucoup de place. Et il faudrait éviter d'afficher la date literralle pour optimiser la place. Cf screen (paysage).

![13 mai 2015 181424 gmt 0200](https://cloud.githubusercontent.com/assets/6066015/7615213/59898462-f99c-11e4-866d-a136e7446c5b.jpg)

**Comment by Eskimon** [comment]
hum... je sais pas s'il faut tagger Bug ou Regression...

**Comment by GerardPaligot** [comment]
Je dirais une évolution en fait puisque c'est déjà comme ça et que c'est pas un bug d'affichage, juste un confort d'utilisation.

**Comment by Situphen** [comment]
Ce sera sûrement réglé en même temps que #2694 ! ;)

**Comment by GerardPaligot** [comment]
Merci à @sandhose pour le fix.
