### ISSUE TITLE
Se débarrasser de Tox (ou trouver un moyen de le fiabiliser)

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2699]
Comme on peut le constater à cette adresse https://travis-ci.org/sandhose/zds-site/jobs/62471904#L640 ; Tox a décidé, seul, sans aucune intervention de notre part, de **ne plus** exposer les variables d'environnement.

La conséquence, c'est que plus aucun build front ne fonctionne.

Ceci viendrait du fait que sa version n'est pas fixée, et que surprise ! on est passés en v2.0.0. Je vous laisse lire le changelog : https://tox.readthedocs.org/en/latest/changelog.html#id2

Il est donc **urgent** de faire quelque chose - et quelle que soit la solution retenue d'ailleurs - tant que ce but est atteint : nos builds doivent être **fiables** et **reproductibles**. Il est hors de question qu'on continue à perdre des heures et des heures à cause de conneries de ce genre.

Toute nouvelle solution doit être pérenne. S'il s'agit de fixer la version de Tox à une version < 2.0.0, la PR doit s'accompagner de la date de fin de support de cette version - et elle doit être assez lointaine pour être acceptable.

**Comment by Eskimon** [comment]
Le souci est rentré dans l'ordre, la version de tox est la plus récente et est fixée (comme pour toute nos dépendances en fait) pour éviter les surprises futures du même genre. Je ferme car un paquet suffisant de PR viennent de passer Travis avec ce comportement sans souci :)
