### ISSUE TITLE
Ressources to test the project

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#27]
Salut,

J'aimerais discuter sur les divers ressources nécessaires pour tester les différents aspects implémentés dans le projet Django.  

Dans un premier temps, j'aimerais savoir deux choses :
- Est-ce que quelqu'un serait me fournir un .tuto qui fonctionne avec l'implémentation actuelle de l'import des tutoriels ?
- Comment est-ce que je peux créer des forums ?

Merci d'avance pour vos réponses.

**Comment by firm1** [comment]
> Est-ce que quelqu'un serait me fournir un .tuto qui fonctionne avec l'implémentation actuelle de l'import des tutoriels ?

Je  l'ai déjà dit dans une autre issue, la partie des tuto a été volontairement shootée par moi parce que je suis en train de bosser dessus et je devrais fournir un patch assez rapidement. Donc je demande de la patiente. Cependant, la dernière version qui permet d'importer moyennement un tuto se trouve [ici](https://github.com/Taluu/ZesteDeSavoir/tree/caeb58258232f858f5c4e42ae1523876e8c363e5)

> Comment est-ce que je peux créer des forums ?

Tu t'imagines bien que ce n'est pas le truc qu'on fera tous les jours, c'est pourquoi la seule manière de le créer est d'aller dans l'interface d'admin `127.0.0.1:8000/admin` et d'aller créer une catégorie et ensuite un forum dans cette catégorie.

**Comment by GerardPaligot** [comment]
> Je l'ai déjà dit dans une autre issue, la partie des tuto a été volontairement shootée par moi parce que je suis en train de bosser dessus et je devrais fournir un patch assez rapidement. Donc je demande de la patiente. Cependant, la dernière version qui permet d'importer moyennement un tuto se trouve ici.

Ouais, je sais. Ce que je demandais, c'est un fichier .tuto compatible avec ton implémentation actuelle.

> Tu t'imagines bien que ce n'est pas le truc qu'on fera tous les jours, c'est pourquoi la seule manière de le créer est d'aller dans l'interface d'admin 127.0.0.1:8000/admin et d'aller créer une catégorie et ensuite un forum dans cette catégorie.

Super, merci bien.

**Comment by firm1** [comment]
> Ouais, je sais. Ce que je demandais, c'est un fichier .tuto compatible avec ton implémentation actuelle.

Ah mais n'importe quel .tuto (celui de ton tutoriel sur android par exemple) est compatible avec mon implémentation.

**Comment by GerardPaligot** [comment]
Justement, il ne l'est pas. Il plante avant la fin de l'importation. :)

**Comment by firm1** [comment]
> Justement, il ne l'est pas. Il plante avant la fin de l'importation. :)

Oui c'est normal, tout simplement parce que le code actuel concernant l'import/création du tuto est foireux.

**Comment by GerardPaligot** [comment]
Ok, je dois comprendre qu'aucun fichier .tuto fonctionne pour le moment ?

**Comment by firm1** [comment]
Oui voila.

Sauf si tu crée une branche à partir de la version que j'ai linkée plus haut. Les .tuto marchent sur celle là.

**Comment by GerardPaligot** [comment]
Ok, inutile de se presser. Je vais attendre que tu fasses tes modifications tranquillement.

**Comment by GerardPaligot** [comment]
Dans cette ordre d'idée de disposer des ressources pour tester, je suis en train d'écrire des fixtures pour pouvoir bénéficier de données statiques en local.

**Comment by GerardPaligot** [comment]
Des fixtures sont maintenant à disposition. Issue plus utile.
