### ISSUE TITLE
[Beta 15.5.1] Les fichiers statiques ne sont plus versionnés

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2700]
Sur la bêta, les fichiers statiques ne sont plus versionnés (il n'y a plus de hash dans l'URL), du coup les visiteurs ont des problèmes de cache, puisque ces ressources ont un cache navigateur de 1 an.

J'ai vérifié l'infra, toutes les règles demandées dans la PR #2242 qui implémentait ceci semblent respectées.

@Situphen ou @sandhose vous voyez quelque chose avec le nouveau déploiement / build du front qui a pu casser ça ?

**Comment by Situphen** [comment]
Je pense que le script de déploiement est bon. Je pencherais plus sur une mauvaise configuration de Django suite au passage à la 1.7

**Comment by SpaceFox** [comment]
Ben, la conf sur la prod est bonne, et elle est en Django 1.7.

**Comment by Eskimon** [comment]
(Est-ce que ca mérite vraiment une mention "bloquant" ?)

**Comment by SpaceFox** [comment]
Si la moitié des visiteurs qui reviennent a une home cassée, oui.

**Comment by SpaceFox** [comment]
Par contre, ça a fonctionné donc c'est bien une régression.

**Comment by sandhose** [comment]
Bah, le site va mal s'afficher chez quasiment tout le monde, et demander au utilisateurs de vider leur cache n'est pas une solution

**Comment by Situphen** [comment]
Esty que quelqu'un peut tester le fonctionnement en local ? (Il faut suivre les instructions de #2242)

**Comment by sandhose** [comment]
Apparemment, c'était un problème de config propre à la bêta, @SpaceFox a corrigé ça ; je ferme

**Comment by SpaceFox** [comment]
Oui mais non. Je suis dessus, il y a quand même un truc à faire, donc ça reste ouvert.

**Comment by Situphen** [comment]
Donc c'est un problème Infra et non pas Front ?

**Comment by SpaceFox** [comment]
C'est un problème de conf infra + code.

**Comment by GerardPaligot** [comment]
> Oui mais non. Je suis dessus, il y a quand même un truc à faire, donc ça reste ouvert.

C'est quoi qu'il reste à faire et qui justifie le bloquant ?

**Comment by sandhose** [comment]
Si on règle pas cette issue, la home ne s'affichera pas correctement
(genre, pas du tout) , a moins que l'on vide le cache côté client.

Mais sinon, a part le merge de la PR, y'a rien a faire :)

**Comment by pierre-24** [comment]
Maintenant que la PR est mergée, c'est bon ?

**Comment by SpaceFox** [comment]
Oui.
