### ISSUE TITLE
Comportement de l'edit des MP

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2702]
Via moi-même sur le forum, les +1 semblent être d'accord (+8 -0)

A l'heure actuelle on peut éditer nos MP si un des participants n'a pas encore répondu au sujet.

Je trouve ce comportement trop permissif et assez perturbant. En effet, impossible de savoir si mon EDIT sera visible ou non par l'autre (car pas de nouvelles notifs). Du coup je pense qu'il serait plus pertinent de bloquer les edit des que le sujet a été lue plutôt que répondu, afin de s'assurer de la visibilité de nos correspondances.

**Comment by GerardPaligot** [comment]
On pourrait même aller plus loin non ? Genre afficher "Lu par membre X et Y". :)

**Comment by Eskimon** [comment]
Moui, ca tombe un peu dans le flicage, j'aime moyen...

**Comment by GerardPaligot** [comment]
Le "flicage" existe déjà puisqu'on peut dire à tout moment ce qui a été lu et jusqu'à où pour tous les contenus pour tous les utilisateurs. Contrairement à toi, je propose simplement de l'afficher visuellement. Après, "Lu par membre X et Y" est peut-être trop explicite. Nous pourrions opté par "Lu par certains membres". Le problème avec ta proposition à toi, c'est que nous allons refusé l'édition d'un message sans pouvoir lui donner la raison pour des raisons de flicage.

**Comment by SpaceFox** [comment]
Sur le SdZ, il y avait un message qui disait à peu près « Impossible d'éditer votre message car il a déjà été lu » (sans préciser par qui), je ne crois pas que ça ait jamais posé le moindre problème.
