### ISSUE TITLE
Ne pas afficher les bannis dans l'autocomplete

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2707]
Lorsque l'on rédige un MP (ou qu'on utilise l'autocomplete en général) il serait bon de ne pas afficher les membres bannis, ou alors de les afficher avec une mention précisant qu'ils sont bannis et ne pas pouvoir les sélectionner.

Source : https://zestedesavoir.com/forums/sujet/3157/envoyer-un-mp-a-un-membre-banni/

**Comment by sandhose** [comment]
C'est lié à l'API membres, qui retourne _tous_ les membres par défaut, même les bannis, et, à ce que sache, il y a pas moyen de filtrer... ping @GerardPaligot

**Comment by GerardPaligot** [comment]
Je confirme, l'API des membres ne permet pas de filtrer mais c'est une fonctionnalité qui peut-être développé par qui veut.

**Comment by GerardPaligot** [comment]
Je tag API puisque l'autocompletion est directement cablé à l'API.

**Comment by Anto59290** [comment]
Je m'en suis chargé, la PR arrive bientot
