### ISSUE TITLE
[15.5.1] Les liens des derniers messages ne sont pas clicables

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2710]
Avec la nouvelle Home, les derniers sujets crée sont bien a leur place. Cependant, on a l'information qui nous dit qu'il y'a une dernière réponse, mais ce n'est pas un lien clicable. Du coup depuis la Homme on ne peut arriver qu'au premier message du topic.

Il serait bien de rendre le lien "Derniere réponse" clicable

![no-clicable](https://cloud.githubusercontent.com/assets/6066015/7649919/b7a86648-faf1-11e4-9fcf-8b6f1aedb2dd.PNG)

Je taggue en evolution par contre.

**Comment by sandhose** [comment]
J'adore toujours autant tes montages sur Gimp, @firm1  <3

Sinon, si on rend la dernière réponse cliquable, le membre ne le sera plus (impossible de faire des liens "imbriqués"). Mais je pense pas que ca soit gênant, et effectivement, que la dernière réponse soit cliquable semble important.

Par contre, est-ce que ca doit être la dernière réponse, ou comme sur le forum, la première réponse "non lue" (si le topic a déjà été vu une fois) ?

**Comment by Eskimon** [comment]
Ca sent plus le paint que le gimp :D

**Comment by SpaceFox** [comment]
On peut tout à fait mettre un lien sur "dernière réponse" et un autre sur le nom du membre.

**Comment by sandhose** [comment]
@SpaceFox: C'est ce que j'ai fait finalement (cf. #2715 )

![](https://cloud.githubusercontent.com/assets/1549952/7665681/f7967358-fbc3-11e4-98d4-b8ab1a5be25c.png)

**Comment by Eskimon** [comment]
Le lien devrait pas etre "juste" sur la date ?

**Comment by sandhose** [comment]
C'est pas le cas sur le forum, pourquoi ça le serait ici ?

![image](https://cloud.githubusercontent.com/assets/1549952/7666750/91c65660-fbf0-11e4-8683-109b3435f239.png)

Ça me parait logique que l'on arrive sur la dernière réponse lorsque l'on clique sur "Dernière réponse"...

**Comment by Eskimon** [comment]
Ah ok, j'avais jamais remarqué alors XD (cliquant toujours sur la date, une habitude surement...)

**Comment by GerardPaligot** [comment]
Merci @sandhose pour le fix!
