### ISSUE TITLE
😂

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2713]
PouruPourquoi  le

**Comment by SpaceFox** [comment]
@firm1 ça va ?

**Comment by GerardPaligot** [comment]
Avoir un accès à Internet quand on est bourré, c'est jamais une bonne idée.

**Comment by SpaceFox** [comment]
Ou alors il a filé son téléphone à son petit neveu ?

**Comment by firm1** [comment]
Je ne sais que penser :( . Je crois que c'est l'effet du thé en fin de soirée.

Désolé pour la gène.
