### ISSUE TITLE
[Beta 15.5.1] Nouvelle home et catégorie des tutos

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/zds-site#2714]
Sur la nouvelle home, quand un tuto possède plus catégories, entre la première et le « _et_ », il manque un espace.
- « _Dans Ordinateurset Electronique [...]_ » ;
- « _Dans JavaScriptet NodeJS [...]_ » ;
- Etc, etc..

![capture du 2015-05-16 01 53 53](https://cloud.githubusercontent.com/assets/4312887/7663677/fd2aa9b0-fb6e-11e4-88b1-257afc4cc553.png)

**Comment by Eskimon** [comment]
Déjà remonté, déjà corrigée ;)

**Comment by Axylium** [comment]
Ah pardon ! J'avais pas vu l'issue à ce sujet passée !
