### ISSUE TITLE
Django ne sait pas quand la requête passe en HTTPS

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#2718]
Django n'a aucun moyen de savoir si la page a été récupéré en HTTPS ou non. Du coup, `request.build_absolute_url` retourne toujours une URL en HTTP, et `request.is_secure` est toujours à `false`. Ca impacte notamment la [doc de l'API](http://zestedesavoir.com/api/) qui n'arrive pas a charger, puisque la page fait une XHR en HTTP et pas en HTTPS, ce qui est bloqué sur la plupart des navigateurs modernes (Chrome et Firefox en tout cas).

Pour régler ça, il faut rajouter dans le `settings_prod.py`: `SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTOCOL', 'https')`, et dans la config du site nginx, dans le bloc `location /`: `proxy_set_header  X-Forwarded-Protocol  $scheme;`.

Voir https://docs.djangoproject.com/en/1.8/ref/settings/#secure-proxy-ssl-header

ping @SpaceFox

**Comment by SpaceFox** [comment]
Attention à la version de Django quand vous regardez la doc :)

**Comment by GerardPaligot** [comment]
Tout à fait, cela dit c'est une solution non spécifique à Django 1.8. C'est aussi la réponse à l'issue que j'avais créé : https://github.com/marcgibbons/django-rest-swagger/issues/220

**Comment by SpaceFox** [comment]
Tout à fait, mais tous les liens récents que j'ai vu passer contenait 1.8 dans l'URL.

**Comment by Situphen** [comment]
Corrigé par @SpaceFox !
