### ISSUE TITLE
Erreur 500 sur l'API

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2721]
Bonjour,

sur internet explorer j'obtiens une erreur à cette url: http://zestedesavoir.com/api/membres/1234/
Mais pas sur firefox.

(J'ai essayer http et https sur IE, pareil).
(Opéra ça fonctionne).

WinXaito

**Comment by Situphen** [comment]
Quelle version d'IE ? :)

**Comment by WinXaito** [comment]
IE 11 (En modifiant pour avoir l'affichage d'une autre version pareil, après je ne sais pas si ça reprend que l'affichage ou le comportement entier)

**Comment by SpaceFox** [comment]
On ne supporte que IE11.

Cela dit, ça a l'air mystique...

C'est reproductible sur la bêta ?

**Comment by Situphen** [comment]
C'est possible d'avoir une capture d'écran de l'erreur rencontrée ? :)

**Comment by WinXaito** [comment]
http://cloud.winlap.ch/pic/413.jpg

http://cloud.winlap.ch/pic/414.jpg

Voilà

**Comment by DevHugo** [comment]
Son adresse est en http et pas en https. Tous les navigateurs ont l'air de forcer le https mais pas ie.

**Comment by Situphen** [comment]
Ça ne change rien : la page fonctionne bien en HTTP !

![La preuve en image](http://i.gyazo.com/f65dfa8b7fe3522246e73c3818f5a53b.png)

**Comment by WinXaito** [comment]
Comme je l'ai dit:

> (J'ai essayer http et https sur IE, pareil).

![En https](https://cloud.githubusercontent.com/assets/8223773/7684591/968c1fd4-fd87-11e4-8917-48b47df1d82d.PNG)

**Comment by GerardPaligot** [comment]
D'après les tests que j'ai fais avec Sandhose, IE mentionne comme header `Accept: text/html` et ne spécifie jamais `application/xml` ou `application/json` dans `Accept`. Ca fait alors crasher DRF mais je pense que c'est un bug dans la librairie et pas chez nous (puisque la stacktrace ne mentionne aucune occurrence chez nous).

**Comment by Eskimon** [comment]
Hum. Du coup est-il pertinent de garder ce ticket ouvert ?

**Comment by GerardPaligot** [comment]
Il faudrait au moins un morceau de documentation je pense. Ca pourrait être pas mal de prévenir nos utilisateurs d'API de ce genre de problème.

**Comment by gustavi** [comment]
Je ferme, c'est un doublon de #3096 :)
