### ISSUE TITLE
Rapatrier le serveur Sentry sur un serveur de l'association

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2722]
Bonjour les gens,

Suite à ma réinstallation de serveur, le serveur Sentry qui existait est mort.

J'ai essayé de réinstaller la dernière version (7.4.3, la dernière disponible sur Pip)... sauf que ce dernier déconne complètement même en suivant à la lettre les instructions.

Donc... ben, il n'y a plus de Sentry jusqu'à nouvel ordre :(

**Comment by artragis** [comment]
juste pour dire que, au moins temporairement, sandhose en a un.

**Comment by Eskimon** [comment]
Du coup comment on gère ici ? @sandhose en a un qui marche. On s'en contente ou on en réinstall sur l'ancienne préprod que l'on nous prete (ou on demande à @Un-Cornichon de nous préter un bout de VM pour en installer un ?)

**Comment by ghost** [comment]
De mon coté c'est tout à fait possible. Par contre ça sera derrière un reverse proxy pour tout ce qui est HTTP(s), et des ports non standards pour les trucs très commun genre SSH.

**Comment by artragis** [comment]
ping @Fumble et @SpaceFox qu'en dit l'assoc ce truc est marqué "régression" donc c'est prioritaire.

**Comment by SpaceFox** [comment]
Idéalement ça devrait être pérennisé sur un serveur de l'association.

**Comment by GerardPaligot** [comment]
@SpaceFox L'ancienne prod n'est pas un serveur pérennisé par l'association ?

**Comment by gustavi** [comment]
Pourquoi ne pas avoir (je sais pas comment fonctionne la prod niveau serveur, faut que je me mette à jour) un VPS dédié à ce genre de choses ? On peut mettre dessus Sentry et Munin par exemple et ça ne couterai que 31€08 par an ce qui est assez peu. Mais je pense que cette discussion devrait avoir lieu sur le forum.

**Comment by GerardPaligot** [comment]
> Mais je pense que cette discussion devrait avoir lieu sur le forum.

Avec le CA, les membres s'en foutent un peu.

**Comment by artragis** [comment]
> Pourquoi ne pas avoir (je sais pas comment fonctionne la prod niveau
> serveur, faut que je me mette à jour) un VPS dédié à ce genre de choses ?
> On peut mettre dessus Sentry et Munin par exemple et ça ne couterai que
> 31€08 par an ce qui est assez peu. Mais je pense que cette discussion
> devrait avoir lieu sur le forum.

en soit la preprod actuelle peut très bien servir de serveur sentry + munin.

2015-11-23 9:39 GMT+01:00 Gérard Paligot notifications@github.com:

**Comment by gustavi** [comment]
Ça peut si on ne casse pas la preprod trop souvent ;) Après je suis un partisan de 1 service = 1 serveur (ce que la virtualisation permet de faire) mais c'est assez utopique !

**Comment by gustavi** [comment]
Étant donné qu'on a un serveur Sentry fonctionnel, est-ce que cette issue est toujours pertinente ?

**Comment by GerardPaligot** [comment]
Pour l'instant, on a un Sentry sur le serveur de @sandhose mais c'est clairment pas l'idéal. Il faudrait l'héberger sur un serveur ZdS. Est-ce qu'il y a moyen de faire ça @Un-Cornichon ?

**Comment by SpaceFox** [comment]
L'asso n'a pas de serveur dédié pour ça pour l'instant. AMHA ça va attendre l'AG.

**Comment by GerardPaligot** [comment]
Bien, alors nous gardons ça à l'esprit pour en parler à l'AG.

**Comment by GerardPaligot** [comment]
@gustavi @vhf N'oublions pas cette issue pour la prochaine réunion qui discutera d'argent ! :)

**Comment by vhf** [comment]
La prochaine réunion tu veux dire ?

**Comment by GerardPaligot** [comment]
édité, au temps pour moi.

**Comment by Situphen** [comment]
Je ferme car on a décidé d'utiliser directement sentry.io
