### ISSUE TITLE
Déplacement des éléments d'un contenu

### ISSUE THREAD

**Issue by Vayel** [zestedesavoir/zds-site#2723]
Il serait apprécié, je pense, d'avoir à sa disposition une page pour déplacer les éléments d'un contenu. En effet, il faut actuellement se rendre sur l'élément concerné pour accéder au bouton de déplacement. Ce n'est pas très pratique.

**Comment by GerardPaligot** [comment]
Cela me semble être une fonctionnalité à discuter avec la communauté. La spec est super vague et on ne sait pas si c'est voulu par la communauté. Je ferme et dès qu'une spec précise est donnée, on s'y attèle.
