### ISSUE TITLE
Un bout de template qui ne peut pas fonctionner

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2725]
Dans les templates, on trouve à au moins un endroit : `{{ zds.settings.ZDS_APP.forum.posts_per_page }}`.

Cette syntaxe ne renvoie rien et donc le code associé ne fonctionne probablement pas comme prévu.

**Comment by Situphen** [comment]
C'est introduit par #1901.

@artragis : Tu dois connaître cette partie vu que tu as fait la PR donc peut-être que tu sais si c'est grave ou pas ? :)

**Comment by GerardPaligot** [comment]
Ces paramètres sont utilisés dans la pagination mais ne seront plus nécessaires après le merge de https://github.com/zestedesavoir/zds-site/pull/2697.

**Comment by Eskimon** [comment]
Le merge sus-mentionne ayant eu lieu, on peut fermer ici ? (je suppose que non vu qu'on trouve la syntaxe encore ici : https://github.com/zestedesavoir/zds-site/blob/8e61c96bed981f8968ed64c3377010b6fc95b85c/templates/forum/base.html#L75 )

**Comment by artragis** [comment]
Je l'avais fait à l'époque pour deux raisons :
- je suis un gars du back qui n'y connaissait pas encore trop à django
  (j'étais pas encore passé par la zep12) et que les templates me
  paraissaient ultra complexes
- je me souviens avoir galéré pendant deux/trois heures pour corriger les
  "mais" de la QA de @pierre-24 tellement c'était ingérable. En fait mon
  erreur a été de ne pas mettre "TODO rendre ça plus propre quand une
  personne qui s'y connait passera".
