### ISSUE TITLE
Erreurs 404 non générées sur certaines pages

### ISSUE THREAD

**Issue by yapper-git** [zestedesavoir/zds-site#2728]
Certaines pages devraient générées des erreurs 404 au lieu d'afficher le contenu des pages.
J'ai découvert ce bug en voulant corriger des erreurs dans les liens sur la page des CGU, un oubli de mailto produit actuellement un lien vers http://zestedesavoir.com/pages/cgu/communication@zestedesavoir.com qui affiche la page des CGU. Or une erreur 404 devrait être générée. Peu importe la suite de l'URL cela fonctionne et ce pour plusieurs pages...
Il manque un `$` à la fin de certaines expressions régulières dans zds/pages/urls.py.

De plus le fichier urls.py importe pages.views mais ne l'utilise à aucun moment.
Du coup je me demande si je supprime l'import de views (ligne 5) ou bien si j'utilise par exemple `views.about` au lieu de `'zds.pages.views.about'` ?

Je veux bien bien me charger de faire une PR pour corriger ces bugs :)

EDIT: Je n'arrive pas à m'assigner à cette issue (comme suggéré par CONTRIBUTING.md), problèmes de droits ?

**Comment by Eskimon** [comment]
> EDIT: Je n'arrive pas à m'assigner à cette issue (comme suggéré par CONTRIBUTING.md), problèmes de droits ?

Tout a fait, et voila qui est fait :)

**Comment by Situphen** [comment]
> Certaines pages devraient générées des erreurs 404 au lieu d'afficher le contenu des pages.
> J'ai découvert ce bug en voulant corriger des erreurs dans les liens sur la page des CGU, un oubli de mailto produit actuellement un lien vers http://zestedesavoir.com/pages/cgu/communication@zestedesavoir.com qui affiche la page des CGU. Or une erreur 404 devrait être générée. Peu importe la suite de l'URL cela fonctionne et ce pour plusieurs pages...
> Il manque un `$` à la fin de certaines expressions régulières dans zds/pages/urls.py.

C'est ça, bien vu ! ;)

> De plus le fichier urls.py importe pages.views mais ne l'utilise à aucun moment.
> Du coup je me demande si je supprime l'import de views (ligne 5) ou bien si j'utilise par exemple `views.about` au lieu de `'zds.pages.views.about'` ?

Ça dépend des devs car on a pas de règle définies pour ça. Ici, je pense que le plus simple est de supprimer l'importation de `views`.

> Je veux bien bien me charger de faire une PR pour corriger ces bugs :)

Merci

> EDIT: Je n'arrive pas à m'assigner à cette issue (comme suggéré par CONTRIBUTING.md), problèmes de droits ?

C'est ça, problèmes de droits ;D

**EDIT :** Grillé par le caribou !

---

N'hésites pas à poser des questions sur ZdS (tu as un compte ?) ou IRC (`irc.smoothirc.net` canal `#zds-dev`) !

**Comment by yapper-git** [comment]
Je viens de repérer d'autres pages concernées, par exemple : http://zestedesavoir.com/rechercher/opensearch.xmlqsdqsd
Je vais faire un autre commit et voir s'il n'y en a pas d'autres encore.

EDIT: De plus le . n'est pas échappé, donc ceci fonctionne : http://zestedesavoir.com/rechercher/opensearch~xml

**Comment by yapper-git** [comment]
Voilà j'ai parcouru les _urls.py_ et vérifier à la main s'il n'y avait pas d'autres oublis, cela semble OK.

**Comment by yapper-git** [comment]
J'oubliai de vous remercier pour vos réponses @Eskimon et @Situphen !
Oui j'ai un compte sur ZdS mais avec le pseudo [yvand](http://zestedesavoir.com/membres/voir/yvand/).
