### ISSUE TITLE
[Beta 15.5.1] Les sujets cachés sont affichés sur la home

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2731]
Serveur : Bêta
Version : v15.5½-RC1
Système : OS X
Navigateur : Google Chrome Version 41.0.2272.118 (64-bit)

Scénario :
- Créez un sujet non accessible à tous les utilisateurs.
- Constatez que le sujet est visible par tout le monde sur la home.

**Comment by Eskimon** [comment]
Je suis dessus :)

**Comment by Eskimon** [comment]
Voilou !

**Comment by pierre-24** [comment]
Merci Eskimon, c'est mergé :)
