### ISSUE TITLE
[Beta 15.5.1] Erreur 500 à la consultation des tutoriels d'un membre

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2735]
Serveur : Bêta
Version : v15.5½-RC1
Système : OS X
Navigateur : Google Chrome Version 41.0.2272.118 (64-bit)

Scénario :
1. Rendez-vous sur n'importe quel profil (par exemple, [moi](http://beta.zestedesavoir.com/membres/voir/Andr0/)).
2. Consultez mes tutoriels en ligne via la sidebar sur le lien "En ligne" de la catégorie "Tutoriels".
3. Constatez une erreur 500.

Reporté par [yvand](https://zestedesavoir.com/forums/sujet/3142/tres-cher-ami-aurez-vous-lextreme-obligeance-de-tester-la-v1551/?page=2#p57931).

**Comment by GerardPaligot** [comment]
Je change le tag de Back en Front après vérification. Je m'assigne la tâche.

**Comment by yapper-git** [comment]
Le lien (ancre) dans la sidebar vers "Derniers articles" ne fonctionne pas (même en prod), par exemple : http://beta.zestedesavoir.com/membres/voir/Andr0/#derniers-articles à cause d'une [typo](https://github.com/yapper-git/zds-site/commit/9f64a7c72188751e9ee2363bc182dc325e732791)

J'ai ajouté un correctif dans ma PR, voir #2726.

**Comment by Eskimon** [comment]
Nickel :)

**Comment by Eskimon** [comment]
J'en ai profite pour faire un petit check, et apparemment c'est le seul endroit ou un `with` manquait

**Comment by GerardPaligot** [comment]
Oui, j'ai fais la vérification aussi hier soir. Par contre, PyCharm me signal **beaucoup** d'erreur front dans les templates sur l'usage de "=" et "==". Faudrait peut-être se pencher là dessus. Ca me stress le rouge dans un projet. :)
