### ISSUE TITLE
Impossible de synchroniser la base de données

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2736]
Serveur : Local
Branche : release-v15.5.1 (dernier commit 253a6e3)
Système : OS X
Navigateur : Google Chrome Version 41.0.2272.118 (64-bit)

Scénario :
1. Supprimez votre base de données locale pour être certain que vous allez générer la base la plus clean possible.
2. Exécutez la commande pour générer la base et appliquez les migrations `python manage.py syncdb`.
3. Constatez que la migration n'a pas pu se faire avec le message suivant :

``` console
$ python manage.py syncdb
CommandError: Conflicting migrations detected (0002_auto_20150412_2234, 0003_alter_email_max_length in default).
To fix them run 'python manage.py makemigrations --merge'
```

Je marque bloquant au risque de voir @SpaceFox rencontrer ce problème en prod et devenir fou.

**Comment by Eskimon** [comment]
Il me semble que ce probleme avait ete sur une vieille migration non ? Si tu repars de zéro tout se passe bien ? Car j'ai fait plusieurs fois la réinstall récemment pour tester une VM et j'ai jamais eu de souci

**Comment by GerardPaligot** [comment]
J'ai créé une branche à jour par rapport à `release-v15.5.1` (donc aucun changement git), j'ai supprimé mon `base.db`, j'ai installé les dépendances puis j'ai voulu synchronisé les données.

Mise à part refaire un git clone, je ne vois pas comment être plus propre.

**Comment by Eskimon** [comment]
Et tu as essayé de faire ce que django te propose ou pas ? Du coup ce problème doit être vraiment récent (PR des fofos ?) car il n'y a pas si longtemps il n'existait pas

**Comment by GerardPaligot** [comment]
> Et tu as essayé de faire ce que django te propose ou pas ?

Je viens à l'instant et après la migration passe. Par contre, il a fait la migration dans mon installation de Django dans virtualenv. Du coup, je ne sais pas si c'est mon installation ou non. Dans tous les cas, je retire le bloquant.

> Du coup ce problème doit être vraiment récent (PR des fofos ?) car il n'y a pas si longtemps il n'existait pas

On est sur la branche de release, ça ne peut pas être le refactoring des fofos qui est mergé dans dev.

**Comment by GerardPaligot** [comment]
Bon, je tiens juste à signaler que le merge suggéré à complètement péter mon environnement de dev.

**Comment by Eskimon** [comment]
Quelle merge ?

**Comment by Eskimon** [comment]
J'ai rien dit en fait, je croyais que tu parlais git mais en fait tu parlais Django...

**Comment by GerardPaligot** [comment]
Je pense qu'on peut fermer cette issue. Je suppose que c'était lié à mon environnement mais gardons à l'esprit que si ça arrive en prod, faut pas merge et faut trouver une autre solution. :)

**Comment by Eskimon** [comment]
Il y a un souci quelque part mais j'arrive pas a trouver ou... Surtout que faire le "merge" des migrations semble effectivement foutre joyeusement en l'air les migrations... Bref. Je sais pas sur quelles pied danser ici. :/

**Comment by GerardPaligot** [comment]
Bien, j'ai testé sur un autre environnement et j'ai encore eu le problème. A mon avis, quand je passe d'une branche synchronisée via dev vers une branche synchronisée avec la release, ça pète mon environnement.

**Comment by Eskimon** [comment]
La release ayant été fermée et mergee dans dev, doit-on garder ce ticket ?

**Comment by Eskimon** [comment]
J'ai l'impression que le probleme est regle ici. J'ai pas mal joue avec ma BDD recement et chez moi tout marchait. Je ferme, a rouvrir si plus d'infos.
