### ISSUE TITLE
[Beta 15.5.1] Aider les auteurs : icones non grisées

### ISSUE THREAD

**Issue by DonKnacki** [zestedesavoir/zds-site#2738]
Serveur : Bêta
Version : v15.5½-RC1
Système : windows 7
Navigateur : Firefox 38.0.1

Scénario :

Sur ce lien : http://beta.zestedesavoir.com/tutoriels/aides/

les icones ne sont pas grisées même lorsque le tuta n'a pas besoin d'aide sur un domaine 
exemple "Une introduction à Ruby "
Je vois parfaitement les icônes "Tutoriel jamais publié" et "Ne cherche aucun illustrateur"
A noter que le tooltip est bon et même les filtres fonctionnent

**Comment by Eskimon** [comment]
Les soucis de la page d'aide ont ete regle, ils ne sont juste pas encore remis en preproduction. Je viens de verifier ce ticket et tout semble Ok dans la branche de release. Je ferme :) .

Merci quand meme de la vigilance @DonKnacki :)
