### ISSUE TITLE
[beta 15.5.1] Les liens dans le message d'acceuil sont mal contrastés

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2739]
Sur la release en cours (derniers commits), quand on est pas connecté, le message d'accueil contient des liens dont le contraste fait mal aux yeux (en tout cas au miens).

Des liens oranges seraient préférables ici.

Screenshoot : 

![link-not-real](https://cloud.githubusercontent.com/assets/6066015/7772092/572047cc-009c-11e5-93e4-d7e67d3ec89d.PNG)

**Comment by SpaceFox** [comment]
[Déjà corrigé](https://github.com/zestedesavoir/zds-site/pull/2704#issuecomment-102149480)

**Comment by firm1** [comment]
Ah, je front mal généré je suppose.

**Comment by Eskimon** [comment]
Pas généré tout court, certains commits sont pas encore remis en préprod c'est tout.
