### ISSUE TITLE
[beta 15.5.1] Le lien de présentation de l'association ne pointe vers rien

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2740]
Screen : 
![pointu](https://cloud.githubusercontent.com/assets/6066015/7774591/ad5e98ae-00ac-11e5-9cff-389f9186f2f6.PNG)

Le lien qui est censé pointer vers l'url de présentation de l'association (comme on peut le voir sur le l'image ci-dessous ) ne pointe vers rien.

La faute à une variable `url_association` oubliée [ici](https://github.com/zestedesavoir/zds-site/blob/release-v15.5.1/templates/home.html#L21)

**Comment by pierre-24** [comment]
Merci à @Situphen de ne pas avoir écouté mes bêtises, c'est corrigé et mergé :)
