### ISSUE TITLE
Retirer la taille fixe sur les légendes

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2742]
Aujourd'hui, quand on soumet une image dans une galerie, les légendes ont une taille fixe. Par contre, à l'usage, nous pouvons avoir des légendes sans aucune limite. Chose qui me semble bien plus logique.

Il faudrait donc uniformiser ce comportement en faisant sauter cette limite.

**Comment by helmasaur** [comment]
Quand on parle de taille, il s'agit de celle de la police en point ou de la longueur de la chaîne de caractères ?

**Comment by Vanadiae** [comment]
> longueur de la chaîne de caractères

**Comment by helmasaur** [comment]
J'imagine que ça se joue au niveau du champ de texte mais est-ce qu'il y au ne taille prédéfinie dans la base de données ?

**Comment by A-312** [comment]
https://github.com/zestedesavoir/zds-site/blob/1ec7094118f7c3f0149e1063f0572260373e7f36/zds/gallery/models.py#L110

**Comment by helmasaur** [comment]
J'avais vu ça du côté formulaire mais au niveau de la table, il n'y aura aucun soucis ?

**Comment by artragis** [comment]
bah comme tu vois côté bdd on a mis une max_length de 80

**Comment by A-312** [comment]
Django s'occupe de la partie DB pour nous grâce à son ORM

**Comment by helmasaur** [comment]
Je ne comprends pas ce qui est demandé pour le coup. Le champ de texte est limité à 80 caractères (ce qui correspond à la base de données).

**Comment by A-312** [comment]
Ce n'est plus d'actualité il me semble

**Comment by helmasaur** [comment]
Si c'est le cas, ça fait un ticket de moins et sans rien faire. Naviguons vers 200 !

**Comment by A-312** [comment]
~~J'ai dis une grosse bêtise, je parlais d'autres choses.~~

Il faudrait remplacer `max_length=80` par `max_length=300`. ;)

**Comment by helmasaur** [comment]
En quoi 300 est une légende sans limite ? Ce n'est même pas la limite d'un type de chaîne de caractères.

**Comment by A-312** [comment]
> En quoi 300 est une légende sans limite ? Ce n'est même pas la limite d'un type de chaîne de caractères.

Il ne faut pas confondre légende et zone de texte, peut-être que 80 c'est court, mais la taille d'un tweet doit être largement suffisant.

**Comment by artragis** [comment]
On peut aussi mettre un textfield complet sans max length. Ce n'est pas vraiment gênant si la légende est sans limite puis qu'on ne fait pas de recherche sur la légende. Le ticket dit "plus aucune limite" donc autant ne mettre aucune limite @A-312

**Comment by artragis** [comment]
donc pour résoudre le ticket

- changer le type de field
- créer une migration grâce à `python manage.py makemigrations`
- faire tourner la commande `python manage.py migrate`
- faire un git add sur le fichier de migration qui a été créé
- s'assurer que la page des galeries n'est pas cassée à cause du nouveau type de field.

**Comment by A-312** [comment]
Au dessus de 80 mots, ce n'est plus une légende mais une description, c'est assez désagréable les images avec une légende trop grande, je trouve que c'est un mauvais usage. Quel est l'intérêt d'avoir 1000 mots pour la légende d'une image ?

300 mots c'est déjà bien: voici 280 mots: `![Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis arcu aliquet, dapibus lectus in, molestie tellus. Nam tempus condimentum velit sed faucibus. Fusce tortor purus, tristique a mi in, consectetur ultrices enim. Suspendisse quis efficitur nulla. Nam eu quam tortor.]()`

![image](https://user-images.githubusercontent.com/18501150/73121236-8187af80-3f78-11ea-9b1f-0165c40649da.png)

Je ne suis pas sûr de voir l'intérêt d'avoir : `![Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis arcu aliquet, dapibus lectus in, molestie tellus. Nam tempus condimentum velit sed faucibus. Fusce tortor purus, tristique a mi in, consectetur ultrices enim. Suspendisse quis efficitur nulla. Nam eu quam tortor. Aenean volutpat dolor tellus, aliquam consequat tortor elementum vitae. Phasellus nec fringilla erat, sed sagittis leo. Mauris rhoncus nec lorem sit amet vestibulum. Suspendisse nec finibus sapien. Mauris convallis, mi mattis maximus feugiat, ante mauris tincidunt velit, non varius purus sapien ut ante. Suspendisse quam magna, laoreet vel semper in, tincidunt id felis. Curabitur auctor ipsum quis turpis bibendum elementum. Quisque venenatis accumsan urna. Cras lacus justo, gravida condimentum odio ultrices, sagittis euismod purus. Suspendisse nunc sem, pretium id pulvinar eget, suscipit id nisi. Mauris ut purus sit amet quam rutrum pharetra. Donec non est sem. Integer laoreet consequat imperdiet. Aenean elementum mollis nulla id fringilla. Sed sed lectus laoreet, dapibus est ut, facilisis leo.]()`

![image](https://user-images.githubusercontent.com/18501150/73121176-9d3e8600-3f77-11ea-8dfb-588079b9d097.png)

Je préfère nettement : 

![image](https://user-images.githubusercontent.com/18501150/73121199-02927700-3f78-11ea-9b6f-36cf871bc4eb.png)


```js
![Lorem ipsum dolor sit amet, consectetur adipiscing elit.]()

Nam tempus condimentum velit sed faucibus. Fusce tortor purus, tristique a mi in, consectetur ultrices enim. Suspendisse quis efficitur nulla. Nam eu quam tortor. Aenean volutpat dolor tellus, aliquam consequat tortor elementum vitae. Phasellus nec fringilla erat, sed sagittis leo. Mauris rhoncus nec lorem sit amet vestibulum. Suspendisse nec finibus sapien. Mauris convallis, mi mattis maximus feugiat, ante mauris tincidunt velit, non varius purus sapien ut ante. Suspendisse quam magna, laoreet vel semper in, tincidunt id felis.

Curabitur auctor ipsum quis turpis bibendum elementum. Quisque venenatis accumsan urna. Cras lacus justo, gravida condimentum odio ultrices, sagittis euismod purus. Suspendisse nunc sem, pretium id pulvinar eget, suscipit id nisi. Mauris ut purus sit amet quam rutrum pharetra. Donec non est sem. Integer laoreet consequat imperdiet. Aenean elementum mollis nulla id fringilla. Sed sed lectus laoreet, dapibus est ut, facilisis leo.
```

--------

Si vraiment on accepte les légendes sans limite, il faudrait améliorer le rendu. Pour les images avec une très grande description.
