### ISSUE TITLE
Ajouter une estimation du temps de lecture calculé automatiquement

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2743]
Comme nos contenus ont une durée de lecture _très_ variée dans un même "type de contenu", je me dis qu'il serait intéressant d'y adjoindre une durée estimée de lecture :
- Article
- Page de tuto
- Intégralité du big et moyen tuto

**Intérêts :**
1. Le lecteur a une idée du temps dont il va avoir besoin
2. L'auteur a une idée du temps qu'il va demander au lecteur
3. L'auteur peut équilibrer ses parties de texte

**Comment faire ?**

C'est assez simple : un lecteur moyen lit entre 1500 et 2000 SEC (Signes Espaces Comprises) à la minute (c'est d'ailleurs pour ça qu'un "feuillet standard" donc une page de livre fait 1500 SEC).

On peut donc prendre le nombre de caractères du contenu et le diviser par 1500 ou 2000 (disons 2000 pour tenir compte de la mise en forme etc, et du fait que je pense que nos lecteurs sont plus rapides que la moyenne) et obtenir le nombre de minutes de lecture du contenu pour un lecteur moyen.

Bien sûr, comme cet indicateur est imprécis, il faut l'arrondir. Le plus efficace serait peut-être d'afficher un "ordre de grandeur" et de partir sur une suite à peu près logarithmique, par exemple :
- Moins de 5 minutes
- 5 minutes
- 10 minutes
- 15 minutes
- 20 minutes
- 30 minutes
- 40 minutes
- 1 heure
- ...

**Comment by Situphen** [comment]
Je pense que ça aurait dans un premier temps plus sa place dans le forum Bugs & Suggestion pour que la communauté puisse discuter !

Sinon, je ne sais pas trop si c'est bien car le temps de lecture dépend énormément du lecteur !

**Comment by Eskimon** [comment]
Perso j'aime beaucoup cette idée (a dire vrai un truc similaire mais moins bien formulé m’était venu en tête a la lecture du sujet idoine sur le forum).

> Sinon, je ne sais pas trop si c'est bien car le temps de lecture dépend énormément du lecteur !

C'est pour ça que @SpaceFox sort une "moyenne". Le lecteur régulier de ZdS sera habitue aux nombres et saura que pour lui le "20 minutes" est en fait un "15 minutes" par exemple, et pour le lecteur occasionnel ce sera juste une indication.

**Comment by Emeric54** [comment]
L'idée étant intéressante, je me permets de remonter cette issue.

> Je pense que ça aurait dans un premier temps plus sa place dans le forum Bugs & Suggestion pour que la communauté puisse discuter !

C'est certainement ce qu'il faudrait faire, afin d'avoir l'avis des différents auteurs et des lecteurs. Tu as le temps @SpaceFox ?(sinon, je peux m'en charger).

**Comment by SpaceFox** [comment]
Charge-t-en, je ne pourrai pas avant 3 bonnes semaines :)

**Comment by Eskimon** [comment]
@Emeric54 même pas besoin de passer par le fofo. L'idée est bonne et aucun débat ne sont nécessaire. Du coup "vas-y pour la dev' si elle te plait :) "

**Comment by Emeric54** [comment]
A la base, je parlais uniquement de la création du topic, mais finalement, il peut-être intéressant pour moi d'essayer de développer cette fonctionnalité :) (du coup, je serais peut-être amené a solliciter de l'aide).

**Comment by Eskimon** [comment]
> du coup, je serais peut-être amené a solliciter de l'aide

Avec plaisir tu le sais bien :)

Indice : il faudra rajouter un champ dans le modèle pour calculer le temps de lecture lorsque la validation est faite (afin de pas recalculer à chaque affichage). C'est le plus "compliqué" à faire, ensuite il faudra rajouter l'information au bon endroit dans les templates et en avant :)

**Comment by GerardPaligot** [comment]
@Emeric54 Tu as eu envie de te lancer dans cette issue pour finir ? :)

**Comment by Emeric54** [comment]
@GerardPaligot Je n'ai plus rien. Je garde ça dans un coin de ma tête, si jamais un jour j'ai le temps et l'envie. Du coup, tu peux retirer mon assignement pour le moment :)

**Comment by Anto59290** [comment]
Je travaille sur une PR pour cette Evolution. Quelques choix que je fait, a voir si cela vous parrait bon.
- La vitesse de lecture SEC devient un parametres du fichier Settings
- La fonction compte betement tous les caractères du contenu (images et formules comprises) pour éviter un parsing complexe.

**Comment by SpaceFox** [comment]
Nickel.

**Comment by Anto59290** [comment]
Comme la PR joue sur les contenus publiés, il y faudra aussi executer un script de migration qui fera le tour des contenus publiés pour compter leur nombre de SEC et enregistrer en BDD. Le script sera inclut dans la PR, mais il risque de prendre un petit peu de temps en prod : le script fait un traverse et quelques operations sur tous les contenus publiés. Tout sera notifié dans le fichier UPDATE.

**Comment by Anto59290** [comment]
Je suis de retour, je suis chaud, je reprend ce ticket !

**Comment by pierre-24** [comment]
Et voilà qui est fait, merci @Anto59290 :)
