### ISSUE TITLE
[Beta 15.5.1]Liste des tutoriels pas toujours par 3

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#2745]
Lorsqu'on n'est pas connecté (pas testé avec un membre connecté) et qu'on va sur la page de la liste de tous les tutos, on se retrouve avec les 5 premiers qui singent la home page alors que la norme sur cette page là c'est 3 contenu par ligne. Du coup sur la première ligne on en a 5 et les contenus 2 à 5 sont plus petits et donc moins lisibles.

firefox 38 Xubuntu 15.04 écran 15.5'' 16/9 1024p

![ug_tuto](https://cloud.githubusercontent.com/assets/1523653/7789348/9794b5b4-025d-11e5-91d1-c1c3c9471a93.png)

**Comment by sandhose** [comment]
Ca, c'est un problème de cache je dirais... Je pense que c'est la version "mini" qui est mise en cache à cause de la home, et c'est celle la qui est rendue sur la page d'index des tutos... Je sais pas trop comment marche ce cache, donc ping @SpaceFox

**Comment by SpaceFox** [comment]
Putain, c'est pour ça que je _déteste_ cette possibilité d'avoir des paramètres facultatifs... surtout quand comme ici lesdits paramètres ne sont précisés nulle part dans le fichier appelé.

**Comment by SpaceFox** [comment]
Je note aussi que la manière de gérer les version bêta sur `tutorial_item.part.html` est totalement incohérent avec son pendant `article_item.part.html`. J'espère que la ZEP-12 corrigera ça.

**Comment by pierre-24** [comment]
Il faudra qu'on fasse de la "doc de template" ? :p 

Sur un ton plus sérieux, oui, la ZEP-12 règle ça, puisque la gestion revient deux fois au même, ou presque (y'a une subtilité avec les commentaires).

**Comment by pierre-24** [comment]
Oups, j'avais oublié de le fermer :)
