### ISSUE TITLE
[bêta 15.5.1] On est renvoyé sur la bêta des tutoriels et non sur la version brouillon

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2747]
Il y a intrinsèquement un problème [avec la template `tutorial_item.part.html`](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorial/includes/tutorial_item.part.html):
- Créer un tutoriel, le mettre en bêta
- Rajouter un extrait au tutoriel
- Revenir sur la page qui liste les tutoriels de l'auteur et cliquer sur le lien du tuto

... Et on est renvoyé sur la version bêta et non sur la version brouillon. Et c'est logique:

``` html
{% captureas link %}
    {% if beta %}
        {{ tutorial.get_absolute_url_beta }}
    {% else %}
        {{ tutorial.get_absolute_url_online }}
    {% endif %}
{% endcaptureas %}
```

... Appelle l'URL de la bêta, quand elle existe, et non la version brouillon (quand la bêta n'existe pas, c'est bien la version brouillon qui est appelée, et j'imagine que c'est ça qui a motivé ce bout de code).

Du coup, eh bien il va falloir rajouter un paramètre, pas trop le choix.

**Comment by SpaceFox** [comment]
Est-ce vraiment un problème vu que c'est comme ça depuis l'origine et que personne ne s'est plaint du fonctionnement jusqu'ici ?

**Comment by pierre-24** [comment]
Que du contraire, c'est tout nouveau de la ZEP-04 !

**Comment by SpaceFox** [comment]
Heu, non : https://github.com/zestedesavoir/zds-site/blob/prod/templates/tutorial/includes/tutorial_item.part.html

**Comment by pierre-24** [comment]
[Oui mais non, en fait](https://github.com/zestedesavoir/zds-site/blob/prod/templates/tutorial/member/index.html#L77) !

Le `tutorial_item.part.html` était pas appelé pour généré la page "mes tutoriels", à l'époque, donc le cas ne se présentait pas (et c'était toujours bien la version brouillon)

**Comment by pierre-24** [comment]
Pas un problème de cache à proprement parler, il faut reprendre #2748 !

**Comment by pierre-24** [comment]
C'est fixé, au fait ;)

**Comment by SpaceFox** [comment]
> C'est fixé, au fait ;)

J'espère plutôt que c'est corrigé, sinon c'est inquiétant :-°
