### ISSUE TITLE
[15.5.1] Dernier message non lu d'un article

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2749]
En allant sur là bêta (depuis un mobile) et en cliquant sur le nombre de réactions du dernier article publié "essai", je suis dirigé vers là première reaction plutôt que vers là troisième (puisque j'ai déjà consulté toutes les réactions une fois).

**Comment by Situphen** [comment]
~~Problème de cache ?~~ Rien dit il n'y a pas de cache sur ces tiems là.

**Comment by sandhose** [comment]
J'ai tout de même l'impression que c'est un problème de cache, mais la, je vois pas comment contourner le problème, puisque cela change en fonction de l'utilisateur, et change régulièrement... 

Du coup, soit on abandonne cette feature, soit on le fait côté back (genre via un argument dans l'url, pour rediriger vers la dernière réaction), soit on abandonne le cache sur cette page, avec les problèmes de performances qui vont avec...

Si c'est pas trop compliqué, je pencherais vers la deuxième solution, c'est à dire créer une URL type `/articles/{id}/{slug}/reactions` qui redirige vers `/articles/{id}/{slug}/?page=X#pXXXX` (url récupérable via `article.last_read_reaction.get_absolute_url`)

**Comment by pierre-24** [comment]
Ok ici :)
