### ISSUE TITLE
[15.5.1] Quiproquo sur l'auteur de la dernière réponse

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2750]
Sur la HOME quand on lit "dernière réponse , par yoch" on s'attend à lire le message de yoch en cliquant sur ce lien. Or ici on arrive sur le dernier message non lu qui n'est pas forcément celui de yoch.

![tmp_32712-26 mai 2015 091430 gmt 0200-1037565967](https://cloud.githubusercontent.com/assets/6066015/7807005/e1135288-0387-11e5-9916-3af52a198cf0.jpg)

Je me demande dans qu'elle mesure c'est pertinent de marquer le pseudo du dernier répondant.

**Comment by Situphen** [comment]
On a le même problème sur la liste des sujets du forum actuellement.

**Comment by AlexRNL** [comment]
Yes, j'en avais parlé dans #1523.

**Comment by GerardPaligot** [comment]
Dans les 2 cas on parle des sujets, c'est donc une duplication de l'issue d'@AlexRNL.
