### ISSUE TITLE
[beta 15.5.1] L'API est kaputt => erreur 500

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2753]
Url incriminée : http://beta.zestedesavoir.com/api/membres/

On obtient une erreur 500. Ce problème a donc plusieurs conséquences diverses et variées et plus ou moins embettantes. Telles que : 
- L'autocomplémention ne fonctionne plus nulle part sur le site
- La doc de l'API ne fonctionne plus
- Une erreur 500 c'est jamais jolie

**NB** : l'erreur survient en mode connecté ou non.

Il s'agit donc pour moi d'une regression, mais je ne saurais dire si c'est de l'infra ou du back. Dans le doute je taggue serré.

**Comment by GerardPaligot** [comment]
C'est en tout cas bloquant mais je comprends pas comment c'est possible alors qu'il n'y a eu aucune modification sur l'API des membres depuis des semaines, voire des mois.

**Comment by Eskimon** [comment]
Il faudrait vraiment que l'outil de monitoring qui nous remontait les erreurs reviennent en vie.

**Comment by SpaceFox** [comment]
Si quelqu'un a un serveur… personnellement je n'ai pus le temps ni la
patience de déboguer Sentry.

**Comment by DevHugo** [comment]
J'ai pas le souci en local, donc c'est uniquement sur la plateforme de beta.

**Comment by GerardPaligot** [comment]
Est-ce que @firm1 ou @SpaceFox peuvent nous fournir la stacktrace de la bêta ? Je suis tenté de rajouter le tag "infra" puisque nous ne parvenons pas à reproduire en local.

**Comment by Eskimon** [comment]
Voila la stacktrace, c'est la même erreur que pour la désinscription non ?

```
[ERROR] -- 2015-06-04 11:20:58,904 -- base : Internal Server Error: /api/membres/
Traceback (most recent call last):
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/rest_framework/views.py", line 440, in dispatch
    self.initial(request, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/rest_framework/views.py", line 354, in initial
    self.perform_authentication(request)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/rest_framework/views.py", line 292, in perform_authentication
    request.user
  File "/opt/zdsenv/local/lib/python2.7/site-packages/rest_framework/request.py", line 491, in __getattribute__
    return super(Request, self).__getattribute__(attr)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/rest_framework/request.py", line 266, in user
    self._authenticate()
  File "/opt/zdsenv/local/lib/python2.7/site-packages/rest_framework/request.py", line 454, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/oauth2_provider/ext/rest_framework/authentication.py", line 18, in authenticate
    valid, r = oauthlib_core.verify_request(request, scopes=[])
  File "/opt/zdsenv/local/lib/python2.7/site-packages/oauth2_provider/oauth2_backends.py", line 135, in verify_request
    valid, r = self.server.verify_request(uri, http_method, body, headers, scopes=scopes)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/resource.py", line 75, in verify_request
    return token_type_handler.validate_request(request), request
  File "/opt/zdsenv/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/tokens.py", line 280, in validate_request
    token, request.scopes, request)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/oauth2_provider/oauth2_validators.py", line 217, in validate_bearer_token
    token=token)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'oauth2_provider_application.skip_authorization' in 'field list'")
```

**Comment by GerardPaligot** [comment]
Tout à fait et comme pour la désinscription, je pense que le souci se situe côté infra du serveur de bêta. D'autant plus que @DevHugo a vérifié et il n'a pas le problème en local.

**Comment by Eskimon** [comment]
> je pense que le souci se situe côté infra du serveur de bêta

Du genre ? Requirements pas a jour ? BDD pas migrate ? Il y a des choses simples que je peux tester ?

**Comment by DevHugo** [comment]
Quelque truc sur le sujet:
- https://github.com/evonove/django-oauth-toolkit/issues/219
- https://github.com/evonove/django-oauth-toolkit/issues/236

Comme ça, je dirais requirements pas à jours.

2015-06-04 11:34 GMT+02:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
Nop j'ai vérifié:

```
$ pip show django-oauth-toolkit
---
Name: django-oauth-toolkit
Version: 0.8.1
```

**Comment by DevHugo** [comment]
Les migrations alors ?

**Comment by Eskimon** [comment]
C'est là que le bât blesse, j'ai peut de tenter un `python manage.py migrate` et de mettre en vrac la BDD :D

**Comment by DevHugo** [comment]
Fait pas ça, si ça marche pas, je vais me sentir coupable =)

**Comment by DevHugo** [comment]
Tu peux tenter un manage.py migrate --list

**Comment by Eskimon** [comment]
Bien vu...

```
$ python manage.py migrate --list
admin
 [X] 0001_initial
article
 [X] 0001_initial
auth
 [X] 0001_initial
contenttypes
 [X] 0001_initial
default
 [X] 0001_initial
 [X] 0002_add_related_name
 [X] 0003_alter_email_max_length
easy_thumbnails
 [X] 0001_initial
 [X] 0002_thumbnaildimensions
forum
 [X] 0001_initial
 [X] 0002_auto_20150410_1505
gallery
 [X] 0001_initial
 [X] 0002_auto_20150409_2122
member
 [X] 0001_initial
mp
 [X] 0001_initial
 [X] 0002_auto_20150416_1750
oauth2_provider
 [ ] 0001_initial
pages
 (no migrations)
sessions
 [X] 0001_initial
sites
 [X] 0001_initial
tutorial
 [X] 0001_initial
utils
 [X] 0001_initial
```

**Comment by DevHugo** [comment]
/o/

**Comment by Eskimon** [comment]
Du coup en mode fifou je lance le migrate ou pas #jesuissurderien @SpaceFox tu en penses quoi (et le cas échéant faudra noter ca quelque part)

**Comment by GerardPaligot** [comment]
Attendons l'avis de @SpaceFox mais de toute façon, nous sommes sur le serveur de bêta. Dans tous les cas, c'est pas dramatique.

**Comment by Eskimon** [comment]
Ouai c'est pas dramatique mais si on peut éviter de devoir remettre une BDD sur pied depuis un backup c'est aussi bien

**Comment by Eskimon** [comment]
Du coup @SpaceFox on peut tenter de mettre cette migration ??

**Comment by Eskimon** [comment]
Faut qu'on avance, je ferais la migration dans l’après midi pour voir ce qui se passe. @SpaceFox il faudra remplir un document qque part pour le suivi ? Car normalement ce truc se fait automatiquement lors des maj non ?

**Comment by SpaceFox** [comment]
Oui, c'est fait automatiquement.

**Comment by Eskimon** [comment]
Du coup on a une idee de pourquoi l'initiale de `oauth2_provider` n'est pas passée ?

**Comment by artragis** [comment]
j'ai tendance à penser qu'on un mis un "fake" devant celle-ci comme pour les thumbnail?

**Comment by Eskimon** [comment]
> j'ai tendance à penser qu'on un mis un "fake" devant celle-ci comme pour les thumbnail?

C'est a dire ? (notamment "pourquoi on aurait fait ca" et "de quoi les thumbnails ?"

**Comment by artragis** [comment]
la lib easythumbnails étant de base compatible django 1.7, lorsqu'il y a eu migration, la [doc](https://github.com/zestedesavoir/zds-site/blob/dev/update.md#issue-1455-django-17) nous a dit de mettre un `--fake` pour migrer cette application là. Il se peut que par erreur, par extrapolation ou encore par choix technique on ait fait la même chose pour les oauth-provider.

**Comment by Eskimon** [comment]
Bon j'ai tente de faire la migration qui manque en faisant `python manage.py migrate oauth2_provider` ou `python manage.py migrate oauth2_provider 0001_initial` mais dans un cas comme dans l'autre j'ai le droit a une stacktrace qui se finit par `django.db.utils.OperationalError: (1050, "Table 'oauth2_provider_application' already exists")`

Des idées ?

**Comment by artragis** [comment]
fake it.

(en fait mon assertion était dans le mauvais sens) `python manage.py migrate
--fake oauth2_provider`

2015-06-15 11:46 GMT+02:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
mais si je la fake du coup j'aurais toujours le souci original non ? (probleme de colonne inexistante)

**Comment by Eskimon** [comment]
Bon j'ai trouve sur la preprod' (je ne peux pas verifier en prod').
1. On utilise plus South depuis Django 1.7
2. On a 3 migrations via South pour oauth et une (initial) pour "non-south django 1.7"
3. La migration south numero 3 est cense (entre autre) creer la colonne qui fait bugguer l'affaire
4. Une fois cette migration faite, on pourra fake la migration initial non-south je pense

Question : Comment executer une migration South quand on utilise plus South...

**Comment by Eskimon** [comment]
(Au passage, ce souci vient de la mise à jour de django-oauth-toolkit

-django-oauth-toolkit==0.7.2
+django-oauth-toolkit==0.8.1

Cette mise à jour à été faite dans le but d'avoir toutes nos dépendances à jour proprement. Un moyen simple de contourner le souci **temporairement** serait de revenir en arrière sur la version de ce package.

**Comment by DevHugo** [comment]
C'est possible de créé la colonne à la main ?

Edit:

Voila les trois solutions officielle:

> 1. Migrate your databases using South and then fake the initial migration.
> 2. Otherwise you can provide your own custom migrations for DOT as documented
>    [here](https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-MIGRATION_MODULES)
> 3. Or you can add the column manually with a script and then fake the initial migration.

**Comment by Eskimon** [comment]
- La solution 1 me plait personnellement, mais comment qu'on fait ?
- La solution 2 me semble hors de propos
- La 3 me semble un bon "dernier recours pourquoi pas si c'est pas trop chaud"

**Comment by Eskimon** [comment]
Je trouve 0 doc/explication pour lancer une migration South spécifique lorsqu'on est passé a Django 1.7.
Du coup la solution 3 me semble la seule restante... Cela signifie qu'il faut reussir a me pondre le SQL qui execute ceci:

```
# Adding field 'Application.skip_authorization'
db.add_column(u'oauth2_provider_application',
              'skip_authorization',
              self.gf('django.db.models.fields.BooleanField')(default=False),
              keep_default=False)


# Changing field 'AccessToken.user'
db.alter_column(u'oauth2_provider_accesstoken',
                'user_id',
                self.gf('django.db.models.fields.related.ForeignKey')(to=orm['%s.%s' % (User._meta.app_label, User._meta.object_name)],
                null=True))

```

**Comment by artragis** [comment]
ALTER TABLE oauth2_provider_application ADD COLUMN skip_authorization
TINYINT NOT NULL DEFAULT 0;
ALTER TABLE oauth2_provider_accesstoken ADD CONSTRAINT
fk_user_oauth2_provider_accesstoken FOREIGN KEY(user_id) REFERENCES(
auth_user.id);

2015-06-16 8:50 GMT+02:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
Si tu es sur de toi je lance la manœuvre en mode copie/colle en preprod et consigne ca dans le update.md si tout marche

**Comment by artragis** [comment]
Je suis sûr de moi pour la première. Pour la seconde, je fais "ce qui demande le moins de
noeuds au cerveau" mais c'est pas "certain".

**Comment by Eskimon** [comment]
La premiere passe bien mais pas la seconde, je regarde mais si tu as vois pourquoi hesite pas !

```
mysql> ALTER TABLE oauth2_provider_application ADD COLUMN skip_authorization TINYINT NOT NULL DEFAULT 0;
Query OK, 16 rows affected (0.02 sec)
Records: 16  Duplicates: 0  Warnings: 0

mysql> ALTER TABLE oauth2_provider_accesstoken ADD CONSTRAINT fk_user_oauth2_provider_accesstoken FOREIGN KEY(user_id) REFERENCES(auth_user.id);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(auth_user.id)' at line 1
```

**Comment by artragis** [comment]
Oui je vois pourquoi :

`ALTER TABLE oauth2_provider_accesstoken ADD CONSTRAINT
fk_user_oauth2_provider_accesstoken FOREIGN KEY(user_id) REFERENCES
auth_user(id);`

CF [ici](http://www.w3schools.com/sql/sql_foreignkey.asp)

2015-06-16 10:08 GMT+02:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
:D je lisais la même chose a l'instant :D

et BOUUUUMMMMM tout remarche !!

Je fais la PR de suite pour informer de la démarche a faire :) Gros merci a tous !!

**Comment by artragis** [comment]
Bientôt le lancement de la v15.06 alors!

**Comment by Eskimon** [comment]
Et voila, PR lancée !! (et moi j'ai level up sur ma "prise de confiance sur la preprod" :D )

**Comment by pierre-24** [comment]
Et c'est mergé !
