### ISSUE TITLE
[beta 15.5.1] Impossible de créer une Une dont l'url est trop longue

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2755]
J'ai voulu créer une Une dont l'url serait [celle-ci](http://www.alvencapital.com/en/actualites/investissements/openclassrooms-boucle-une-seconde-levee-de-fonds-d%E2%80%991me-aupres-d%E2%80%99alven-capital/). Mauvaise idée, l'url de rentre pas dans la zone dédiée.

J'hésite à noter en bug ou évolution ...

**Comment by pierre-24** [comment]
Je dirais bug.

**Comment by Eskimon** [comment]
Le souci vient de la taille des URL fixé à 128 caractères. https://github.com/zestedesavoir/zds-site/blob/dev/zds/featured/models.py#L21 

@GerardPaligot tu as écris ce bout de code, il y avait une raison pour imposer une taille max ou pas ? (je serais tenté de dire "on fait comme ca dans les autres modules" )

**Comment by GerardPaligot** [comment]
> "on fait comme ca dans les autres modules"

**Comment by Eskimon** [comment]
Donc la question mystère sera "pourquoi / selon quelle norme on a fait comme ca dans les autres modules" :D

**Comment by GerardPaligot** [comment]
Quand je l'ai fais, je me suis dis qu'il y avait sans doute une raison à ce nombre. Sachant que les navigateurs acceptent des URLs de 255 caractères, la raison était sans doute mauvaise (si tant bien même il y en avait une).

**Comment by Eskimon** [comment]
Apparemment il existe une sorte de consensus autour de la taille "2000 caractères".
Il me semble sage d'allonger nos restrictions pour suivre cela.

http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers
http://boutell.com/newfaq/misc/urllength.html

**Comment by pierre-24** [comment]
C'est bon, merci @Eskimon :)
