### ISSUE TITLE
Nettoyage du gitignore

### ISSUE THREAD

**Issue by Taluu** [zestedesavoir/zds-site#276]
Dans le .gitignore, il a pleins de merde qui sont pas forcément spécifiques au projet... Mais à la conf de l'utilisateur.

Je pense aux trucs d'eclipse. De VisualStudio. De mac. De windows. ...etc. Ce n'est pas au gitignore du projet d'ignorer tout ça... Mais à la conf globale de l'utilisateur (un .gitignore à la racine de leur répertoire `$HOME` ou équivalent) !

Sinon, faut traiter **tous** les cas, et dans ce cas, bonne chance... Parce que qui nous dit que les type de LlamaOs vont pas avoir des merdes committées aussi si on suit le même raisonnement ?

Faudrait aussi autoriser le répertoire bin, ou alors autoriser à la main certains fichiers bien spécifiques (suffit de faire un `[bB]in/*` suivi d'un `![bB]in/binaire`). D'ailleurs je suis pas sûr que la casse change tant que ça suivant les environnements, si ? :o

**Comment by Alex-D** [comment]
J'avais rajouté ça car c'était proposé par Github et que par expérience, les merdes arrivent vite...
No sé pour le répertoire bin, mais j'ai rarement (jamais ?) vu /Bin avec une majuscule.

**Comment by SpaceFox** [comment]
Personnellement, je vois ça comme une technique de défense qui est
discutable mais qui ne fait pas de mal.
Ce n'est pas au projet d'exclure tout ça ; mais au moins on est sûr de ne
pas se retrouver avec ces merdes ci dans le projet. Et du coup c'est
cohérent avec le fait que ce fichier ne cherche pas à être exhaustif.

**Comment by firm1** [comment]
Moi je suis partagé sur la question.

Le fichier .gitignore n'est presque pas consulté par les humains. Le seul problème survient lorsque git essaye de faire une opération, il va donc checker ce fichier et ça peut être plus ou moins long selon la taille et la pertinence de celui-ci.

D'autre part, y'a pas mal de doublons dans dans le gitignore qu'on peut deja virer.

Mais globalement je n'ai pas trop d'avis là dessus, ça ne m'handicape pas trop, mais je peux comprendre que ça fait un peu bordelique comme gitignore.

**Comment by firm1** [comment]
bon j'ai nettoyé un peu ce fichier. 

J'ai surtout viré tout ce qui est VisualStudio (qui irait développer zds avec ?) et quelques trucs.

J'ai rajouté aussi d'autres trucs liés au projet.

J'ai fais le choix d'ignorer les craps de windows et mac qui peuvent remonter. Et le fichier me semble plus léger là.
