### ISSUE TITLE
Les sujets masqués sont quand même affichés dans la recherche

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2762]
[Reporté par quark67 sur le forum](https://zestedesavoir.com/forums/sujet/3297/le-moteur-de-recherche-du-forum-affiche-du-texte-masque/) :

> Bonjour, en faisant une recherche sur le mot « signature », comme ici : [https://zestedesavoir.com/rechercher/?q=signature](https://zestedesavoir.com/rechercher/?q=signature), je constate qu'il est affiché, parmi les résultats, du texte qui a été par la suite masqué par son auteur.
> 
> Par exemple pour ma part, sur la première page de résultats (mais ça risque de changer puisque j'introduis un nouveau sujet avec le mot « signature »), j'ai ceci :
> 
> ![](http://img15.hostingpics.net/pics/641567Capturedcran20150530195752.png)
> 
> Vous voyez que le résultat du 12 décembre 2014 à 18h06 comporte du texte, parlant d'une résolution. Or, en cliquant sur le lien en question, [https://zestedesavoir.com/forums/sujet/1907/petit-bug-daffichage-quand-la-signature-est-trop-longue/](https://zestedesavoir.com/forums/sujet/1907/petit-bug-daffichage-quand-la-signature-est-trop-longue/), le texte en question n'est plus visible (c'est le texte masqué par l'auteur ultérieurement, je suppose).
> 
> J'en conclus que le moteur de recherche de Zeste de Savoir affiche du texte qui a été masqué. Je considère cela comme étant un bug, étant donné que l'auteur a voulu masquer le texte en question, tandis que le moteur de recherche n'en tient pas compte.

**Comment by DevHugo** [comment]
Je prend. Je vais faire des PR Solr dans la semaine.

**Comment by Situphen** [comment]
Merci @DevHugo ! :)
