### ISSUE TITLE
Boost les champs de la recherche sur les topics et sur les posts

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2769]
Il serait bien de booster les champs, c'est une bonne pratique.

**EDIT**: voir http://django-haystack.readthedocs.org/en/latest/boost.htm

**Comment by GerardPaligot** [comment]
Qu'est-ce que ça veut dire "booster" les champs de la recherche ?

**Comment by DevHugo** [comment]
C'est pour spécifier à Solr (le moteur de recherche) que certains champs ont plus d'importance que d'autre. Par exemple: les mots dans le titre d'une actualitée sont plus important que ceux du sous titres. C'est un exemple bidon mais c'est juste pour l'idée. 
C'est pour augmenter la pertinence.

Plus de docs:

http://django-haystack.readthedocs.org/en/latest/boost.html

**Comment by pierre-24** [comment]
C'est implémenté, et *tunable* :)
