### ISSUE TITLE
Mettre à jour la page "à propos"

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#277]
Aujourd'hui la page "A propos" est celle de Progdupeupl - de toutes façons, y'a pas encore de lien pour y accéder, mais ça ferait tache de MEP avec cette page.

**Comment by firm1** [comment]
J'ai mis à jour la page avec nos infos à nous.

Manque plus que la licence du logo (mais ça c'est déjà une autre issue), donc je ferme celle-ci.

**Comment by Eskimon** [comment]
Ce serait bien si @Sandhose ou @Alex-D pouvait faire un petit tour rapide sur cette page pour mettre a jour les outils de front utilise...
(et corriger la premier phrase qui sonne tres tres bizarre !)

**Comment by Alex-D** [comment]
Le soucis c'est que le front il change tous les jours en ce moment, donc on attends quelques jours pour que ça se stabilise pour MàJ.

Typiquement on passe de Compass/Ruby à SASS+floppée de plugins gulp+node.js
