### ISSUE TITLE
Le taux de couverture du code affiche à 0%

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2773]
En ce moment, le taux de couverture du code est de 0%.

Le dernier build travis indique ce job [coveralls](https://coveralls.io/jobs/6327685) dans lequel acune donnée n'a été remontée.

Notons que l'avant dernier build pointait sur ce [job coveralls](https://coveralls.io/jobs/6291357) qui indiquait quant à lui 83.81% de couverture.

**Comment by Eskimon** [comment]
Ca se serait pas regle tout seul et c'etait pas juste un bug du service coveralls ? Sur la home page GH je vois bien le badge et la bonne couverture.

**Comment by firm1** [comment]
Indeed. C'est réglay
