### ISSUE TITLE
Aucun message pour nous confirmer de la prise en compte des alertes du forum

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2775]
Ce bug est visible uniquement sur la version de dev.

Scénario : 
- Je me connecte en tant qu'un simple membre
- Je signale un message
- Je n'ai plus le fameux message qui s'affiche en vert qui me dit `Une alerte a été envoyée à l'équipe concernant ce message.` comme c'est le cas en prod et en beta.

Je suppose donc qu'il s'agit d'une regression de la refacto des forums.

**Comment by Eskimon** [comment]
- Est-ce que l'alerte est cependant bien envoyée ? (tu la vois en tant qu'admin)
- Est-ce que tu as le meme comportement si tu fais l'alerte avec admin ?

Car c'est bizarre, faire l'alerte est appelée [ici](https://github.com/zestedesavoir/zds-site/blob/8e61c96bed981f8968ed64c3377010b6fc95b85c/zds/forum/views.py#L469) et balance le message [la](https://github.com/zestedesavoir/zds-site/blob/8e61c96bed981f8968ed64c3377010b6fc95b85c/zds/forum/commons.py#L115).

**Comment by firm1** [comment]
> Est-ce que l'alerte est cependant bien envoyée ? (tu la vois en tant qu'admin)

En tant qu'admin je ne la vois pas.

> Est-ce que tu as le meme comportement si tu fais l'alerte avec admin ?

oui, même comportement

**Comment by Eskimon** [comment]
Ok, donc c'est carrément l'alerte qui est pas créée on dirait.

**Comment by Eskimon** [comment]
Je viens de tester sur ma version dev et moi je vois bien l'alerte dans le menu de l'admin et sur le message alerté mais effectivement le message flash n’apparaît jamais.

**Comment by Eskimon** [comment]
Bon, en fait il y a carrément 0 messages qui s'affiche (par exemple pour l’édition en tant que modo)

**Comment by Eskimon** [comment]
Et on a aussi perdu les messages dans les MP en fait... a l'aide @GerardPaligot :D

**Comment by GerardPaligot** [comment]
Là maintenant, je n'ai pas le temps mais il me semble que j'ai rien refactorisé sur les alertes parce que c'était hors scope de la ZEP API forum.

**Comment by Eskimon** [comment]
C'est pas les alertes le souci (elles fonctionnent) mais c'est la gestion des "messages flash d'informations" (ils ont aussi disparu des MP)

**Comment by GerardPaligot** [comment]
C'est bizarre. Ils sont pourtant créé dans le back.

**Comment by Eskimon** [comment]
Bon j'ai regarde un peu et je crois que ce sont TOUT les messages flash qui ont disparu (le module des tutos encore intouche n'en affiche plus non plus).

Les messages sont censee etre affiche ici : https://github.com/zestedesavoir/zds-site/blob/dev/templates/base.html#L522 et la derniere fois que ca a ete touche c'est par @Situphen ici : https://github.com/zestedesavoir/zds-site/commit/8a443e8f870caa3b4e20e65a3c59986b2ec4eb1d

Sinon faut regarder siun setting plus globale a changer a ce sujet

**Comment by Eskimon** [comment]
J'ai l'impression qu'ils ont disparu en prod' aussi du coup d'ailleurs...

**Comment by Eskimon** [comment]
Je retire ce que j'ai dit sur le commit précédemment mentionne, je l'ai revert et ca n'a rien change dans ma copie locale...

**Comment by GerardPaligot** [comment]
![capture d ecran 2015-06-03 a 16 26 43](https://cloud.githubusercontent.com/assets/1913901/7962416/7e9af35e-0a0d-11e5-8d4c-6fb73bd2d8e6.png)

Avec une version à jour par rapport à dev

**Comment by firm1** [comment]
@GerardPaligot on tient un mystère là. Je viens d'essayer avec n'importe quel type de user, et pas moyen de voir le message flash :(

**Comment by Eskimon** [comment]
Idem, j'ai beau repartir sur une BDD propre et tout il y a pas moyen d'avoir ce message !

**Comment by GerardPaligot** [comment]
Je vous jure que j'ai pas photoshopé ma capture. ^^°

Voici ce que j'ai fais :
1. J'ai créé une toute nouvelle branche synchronisé avec dev de l'upstream.
2. J'ai mis à jour mes dépendances.
3. J'ai mis à jour le front.
4. J'ai supprimé ma base existante et je l'ai regénéré avec un `syncdb`.
5. Je me suis connecté avec un user.
6. J'ai signalé le message de la capture.

**Comment by firm1** [comment]
Dans ton scénar, tu as bien fait un `migrate` aussi ?

**Comment by GerardPaligot** [comment]
Non, pourquoi je devrais faire un `migrate` ? Ce n'est plus censé être utilisé depuis Django 1.7, non ?

**Comment by Situphen** [comment]
> Non, pourquoi je devrais faire un `migrate` ? Ce n'est plus censé être utilisé depuis Django 1.7, non ?

Je crois plutôt que c'est `syncdb` qui n'est plus sensé être utilisé.

**Comment by GerardPaligot** [comment]
@Situphen Je ne fais plus que des `syncdb` depuis des semaines et cette commande fait toutes les migrations :

``` console
python manage.py syncdb
Operations to perform:
  Synchronize unmigrated apps: corsheaders, munin, debug_toolbar, sitemaps, rest_framework_swagger, featured, rest_framework, haystack, crispy_forms
  Apply all migrations: oauth2_provider, forum, sessions, admin, utils, sites, auth, gallery, member, default, contenttypes, mp, article, easy_thumbnails, tutorial
Synchronizing apps without migrations:
  Creating tables...
    Creating table munin_test
    Creating table corsheaders_corsmodel
    Creating table featured_featuredresource_authors
    Creating table featured_featuredresource
    Creating table featured_featuredmessage
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying utils.0001_initial... OK
  Applying article.0001_initial... OK
  Applying default.0001_initial... OK
  Applying default.0002_add_related_name... OK
  Applying default.0003_alter_email_max_length... OK
  Applying easy_thumbnails.0001_initial... OK
  Applying easy_thumbnails.0002_thumbnaildimensions... OK
  Applying forum.0001_initial... OK
  Applying forum.0002_auto_20150410_1505... OK
  Applying gallery.0001_initial... OK
  Applying gallery.0002_auto_20150409_2122... OK
  Applying member.0001_initial... OK
  Applying mp.0001_initial... OK
  Applying mp.0002_auto_20150416_1750... OK
  Applying oauth2_provider.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying tutorial.0001_initial... OK
```

**Comment by SpaceFox** [comment]
syncdb est obsolète et est devenu un alias de migrate :
https://docs.djangoproject.com/fr/1.7/ref/django-admin/#syncdb

Cf aussi
https://github.com/zestedesavoir/zds-site/blob/dev/README.md#mettre-à-jour-votre-version-locale-de-zds

2015-06-03 16:41 GMT+02:00 Gérard Paligot notifications@github.com:

**Comment by GerardPaligot** [comment]
Ok, faut plus que je l'utilise mais comme c'est un alias, c'est tout pareil.

Cela dit, j'ai quand même regénéré la base de données avec un `migrate` (pour être certain) et le message s'affiche bien.

Est-ce que vous êtes sûr que vous avez bien généré le front ?

**Comment by firm1** [comment]
Front regénéré, cache nettoyé. Rien a faire, je ne vois rien.

C'est magique :) Mais on est deux à avoir le problème donc c'est potentiellement un vrai problème

**Comment by GerardPaligot** [comment]
Rien à faire, avec un user ou un admin. Je vois tout (enfin les alertes en rouge uniquement par admin bien sûr).

![capture d ecran 2015-06-03 a 16 53 10](https://cloud.githubusercontent.com/assets/1913901/7963064/1c78ac9e-0a11-11e5-800c-22acb7af8143.png)

**Comment by GerardPaligot** [comment]
Je viens de tester sur Chrome, Firefox et Safari. Tout fonctionne chez moi.

Je ne sais pas du tout comment c'est possible que ça ne fonctionne pas chez vous.

**Comment by SpaceFox** [comment]
Quelles bases de données sont utilisées de part et d'autre ?

**Comment by GerardPaligot** [comment]
SQLite chez moi.

**Comment by firm1** [comment]
SQLite aussi mon capitaine !!!

**Comment by WinXaito** [comment]
C'est toujours marrant à résoudre ce genre de situation :p

**Comment by SpaceFox** [comment]
Phoque. Une théorie qui s'envole.

**Comment by Eskimon** [comment]
Ca passe pas par les cookies aussi pour ce genre de truc ?

**Comment by Eskimon** [comment]
Bon alors la c'est mystique. Je viens de simplement me checkout sur la branche dev a jour en local et ca marche en partie... Quand je veux editer un post de fofo en tant qu'admin j'ai un avertissement (donc bien) mais quand je quitte un MP j'ai pas le message de confirmation (donc pas bien) par exemple

**Comment by Eskimon** [comment]
Bon j'en perds mon latin, c'est trop mystique pour moi la...

Exemple : module des MP.
Scenario : Quitter un MP soit depuis le MP lui meme ou soit depuis la liste des MP

Cas 1 : Depuis le MP lui meme : Tout marche
Le code est ici : https://github.com/zestedesavoir/zds-site/blob/dev/zds/mp/views.py#L144

Cas 2 : Depuis la liste des MP : Ca ne marche pas.
Le code est ici : https://github.com/zestedesavoir/zds-site/blob/dev/zds/mp/views.py#L220

Pour ce dernier, j'ai rajoute une ligne pour ajouter un message a envoyer evidemment (non presente initialement). Mon message existe (vérifié via [ca](https://docs.djangoproject.com/en/1.8/ref/contrib/messages/#displaying-messages)) mais rien ne s'affiche. Pourtant les deux methodes sont tres tres similaires bodayl !

QQun a une idee ?

**Comment by Eskimon** [comment]
Bon, je viens de faire des tests en beta, j'ai bien les messages flash comme il faut il me semble. Je ferme donc, le mystère restera entier...
