### ISSUE TITLE
Les sens caché des pouces n'est plus lisibles

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2776]
A noter que le problème ne se voit que sur à l'instant ou j'écris ces lignes.

Dans le forum, il y'a des pouces rouges et des pouces verts. Avant la refacto des forums, quand on allait en survol sur le pouce rouge ou le pouce verts, on avait un message qui disait "**Ce message est utile (x personnes ont trouvé ce message utile)**".
Maintenant on a plus que le message qui dit "**Ce message est utile**".

On perd donc en l'accessibilité puisque pour l'aveugle, il devient impossible de connaitre la signification du "1".

Etant donné que ce n'était pas le cas avant, je taggue en regression.

**Comment by Eskimon** [comment]
Sur ma version dev a jour locale j'ai ca pourtant :

![screenshot from 2015-06-01 15 37 08](https://cloud.githubusercontent.com/assets/761168/7914035/84d162f2-0874-11e5-9f82-7ff356fe917f.png)

**Comment by Eskimon** [comment]
(je tag back car a priori s'il y a un souci il vient du back vu que c'est la qu'a eu lieu la refacto)

**Comment by firm1** [comment]
La preuve que je suis très très à jour et que je vois toujours le bug :)

![goupille](https://cloud.githubusercontent.com/assets/6066015/7914120/4b0ae7ae-0875-11e5-81a4-f9696d25c86c.png)

**Comment by Eskimon** [comment]
Et si tu mets un deuxième pouce (via le grand choix user/staff/admin) ca donne quoi ?

(c'etait pas une attaque hein, je voulais juste rapporter ce que moi je voyais ^^' )

**Comment by firm1** [comment]
Bien vu. Le bug se transforme (un problème de comptage).

![goupille](https://cloud.githubusercontent.com/assets/6066015/7914546/f0127c24-0877-11e5-942f-cee6f62d46b6.png)

**Comment by SpaceFox** [comment]
Ça ressemble à des fixtures incomplètes. Cette info est dénormalisée.

**Comment by Eskimon** [comment]
Je dirais pourtant que c'est bien une régression, on a un offset de 1 on dirait. Les fixtures ont pas bouge et si tu crées a la main tu as le même problème.

**Comment by Eskimon** [comment]
@GerardPaligot j'ai essaye de comprendre comment fonctionne les +1/-1 avec la nouvelle architecture mais j'ai un peu du mal. Notamment je comprend pas pourquoi on voit pas directement dans le modèle un champ portant le nombre de [dis]like comme avant...

Si tu as 5 minutes pour faire un petit topo je suis preneur :)

**Comment by GerardPaligot** [comment]
https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/models.py#L188 ?

J'ai refactorisé que les vues. J'ai pas touché aux modèles.

**Comment by Eskimon** [comment]
rha excuse moi je suis un boulet. J'etais dans l'idee que le compteur appartenait a `Post` et que `Comment` etait un truc Django :( #boulay

Sinon Je viens de refaire des tests, le comportement est en fait comme en prod'...
- S'il n'y a pas de +/-1 le message indique "Ce message est [in]utile".
- S'il y a des +/-1 On a comme ci-dessus ET entres parenthèses la version littéral du compteur
- Si je clique quand il n'y a rien, le compteur est mis a jour MAIS le tooltip ne l'est pas, il faut recharger la page pour ca.

@firm1 on est d'accord sur ce comportement ? J'ai le meme en prod et en dev local

**Comment by firm1** [comment]
> @firm1 on est d'accord sur ce comportement ? J'ai le meme en prod et en dev local

En effet, je viens de voir. Il faut actualiser la page pour que ce soit pris en compte et donc le bug est le même sur la prod.

C'est donc un bug et non une regression.

**Comment by Eskimon** [comment]
Par contre c'est du front ca, c'est au javascript de mettre a jour le morceau de texte

**Comment by pierre-24** [comment]
Et on est bon :)
