### ISSUE TITLE
L'édition du premier post d'un topic ne permet pas de modifier le titre/sous-titre

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2777]
Scénario : 
- Créer un topic
- Cliquer sur editer

**Problème** : je ne vois plus le champ "titre" et "sous-titre"

Je taggue donc en regression.

**Comment by GerardPaligot** [comment]
Regarde dans ta sidebar.

**Comment by firm1** [comment]
> Regarde dans ta sidebar.

En effet, je vois dans la sidebar le bouton "Editer le sujet" qui fait le taff, dans ce cas pourquoi ne pas avoir conservé le fonctionnement actuel à ce niveau. C'est déroutant je trouve d'avoir deux bouton d'édition pour un même message qui permettent de faire deux choses différentes.

**Comment by GerardPaligot** [comment]
Question de point de vue. Je trouve bien plus bizarre de jouer avec 2 formulaires en fonction du message et d'avoir un truc qui était horrible dans le back avec une tonne de conditions.

**Comment by SpaceFox** [comment]
La vraie règle, c'est qu'il faut que ce soit ergonomique pour l'utilisateur.

**Comment by GerardPaligot** [comment]
Et c'est quoi qui est ergonomique pour l'utilisateur ?

**Comment by SpaceFox** [comment]
Qu'il ne se pose pas de question de savoir comment éditer quel bout du message. Ici visiblement ça ne fonctionne pas vraiment.

**Comment by firm1** [comment]
C'est bien mon problème aussi le coté ergonomique (qui doit primer sur la technique).

![buisson](https://cloud.githubusercontent.com/assets/6066015/7915900/cd528e5a-0880-11e5-8c51-126a235d86c1.PNG)

Dans cette image, je m'attend à ce que le bouton 1 me permette de modifier mon message, titre et sous-titre. S'il ne le permet pas, alors pourquoi le conserver ?

**Comment by GerardPaligot** [comment]
Je ne suis pas un pro de l'ergonomie mais avoir un bouton "Editer" où le comportement change en fonction du contexte et mettre l'action d'édition d'un sujet avec la création d'un sujet, ça me semble vraiment pas déconnant.

De toute façon, je peux me tromper mais je pense que personne ici n'est expert en ergonomie.

**Comment by Situphen** [comment]
> Je ne suis pas un pro de l'ergonomie mais avoir un bouton "Editer" où le comportement change en fonction du contexte et mettre l'action d'édition d'un sujet avec la création d'un sujet, ça me semble vraiment pas déconnant.

Je pense que la plupart des utilisateurs s'attendent à pouvoir modifier le titre et le sous-titre du sujet en éditant le premier message car ils ont rentré le titre et le sous-titre. Peut-être que remettre l'ancien comportement en remplaçant "Éditer le sujet" à la place de "Éditer" sur le premier message déroutera moins l'utilisateur ?

> De toute façon, je peux me tromper mais je pense que personne ici n'est expert en ergonomie.

Personne ici n'est expert Django.
Personne ici n'est expert jQuery.
...
Personne ici n'est expert.

Mais chaque avis compte ! :)

**Comment by Eskimon** [comment]
Perso j'aimais aussi le comportement précédent :( ...

**Comment by GerardPaligot** [comment]
> Perso j'aimais aussi le comportement précédent :( ...

Pas cool, c'est toi qui a QA le refacto ...

**Comment by Eskimon** [comment]
Oui je sais. Pour me défense la QA des fofos est quand même assez monstrueuse en terme de tout les comportements a voir, penser, tester. Effectivement j'ai pas du tout pensé a l’édition du premier message d'un post, je ne le nie pas et j'en suis désolé.

**Comment by GerardPaligot** [comment]
Dans tous les cas, pour moi c'est un problème front. Du côté back, nous devons gardons une distinction dans les vues pour ne pas avoir des vues qui font n'importe quoi. Nous venons quand même de [ça](https://github.com/zestedesavoir/zds-site/blob/7147114dfb50c32336d4e61a6140634d735b362f/zds/forum/views.py#L657-L813) pour arriver à [ça](https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/views.py#L223-L255).

La vue précédente gérait les [actions sur un poste](https://github.com/zestedesavoir/zds-site/blob/7147114dfb50c32336d4e61a6140634d735b362f/zds/forum/views.py#L696-L724) (masquer, afficher et aleter un message) et la gestion de 2 formulaires avec 2 gestions différents avec ce genre de [condition](https://github.com/zestedesavoir/zds-site/blob/7147114dfb50c32336d4e61a6140634d735b362f/zds/forum/views.py#L730-L737) un peu partout dans le code.

Donc si vous voulez retrouver le comportement initial (je désapprouve mais je semble être le seul ...), c'est au front d'appeler la vue appropriée en fonction du contexte.

**Comment by Eskimon** [comment]
Sur le principe (point de vue back) je suis complètement d'accord avec toi. Du coup pourrais tu dire ce que le front/template devrait faire pour atteindre le bon endroit ? 

et a l'utilisation, une fois qu'on a compris que le bouton etait la c'est pas si genant en fait... je retire donc mon precedent commentaire, l'utilisation est pas tellement genante, c'est plutot qu'on est hyper habitue a l'ancien systeme et que donc on est deroute, mais en soit c'est un comportement assez logique

**Comment by GerardPaligot** [comment]
Récupérer l'URL du nouveau bouton pour éditer un sujet et la remplacer avec l'URL d'édition d'un message lorsqu'il s'agit du premier message d'un sujet.

**Comment by Situphen** [comment]
Au niveau des templates ?

**Comment by GerardPaligot** [comment]
Oui

**Comment by Eskimon** [comment]
Je propose de laisser comme ca et voir comment la communauté réagit. En soi le comportement est finalement plutot logique aussi bien techniquement qu’ergonomiquement (vraiment, je trouve).

Bref, je ferme et l'on rouvrira si vraiment ca pose problème a trop le monde.

(Argument sans valeur, même GH sépare l’édition du titre de l’édition du premier post.
