### ISSUE TITLE
Un invité ne peut pas voir les signatures du forum

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2778]
Le problème n'est visible que sur la branche de dev.

Lorsque je suis non connecté, je ne peux pas voir les signature des membres dans le forum, alors que c'est le cas en prod.

Chose étrange parce qu'on voit bien les signature quand on va sur les commentaires des articles/tutoriels, mais pas dans le forum.

J'imagine qu'on a une regression dus à la refacto des forums. Et le fait que le comportement soit différent entre les commentaires d'articles et les forums me fait pensé qu'il y'a un problème de front qui s'est glissé aussi. Je taggue large donc !

**Comment by Eskimon** [comment]
:D nos tests qui se contredisent <3 (maintenant va falloir comprendre pkoi on a un truc different :D )

Version : dev/3e91b08

![screenshot from 2015-06-02 10 52 08](https://cloud.githubusercontent.com/assets/761168/7932020/7e6e20a2-0915-11e5-9855-2cfa01d5d0e7.png)

**Comment by firm1** [comment]
Je n'exclu pas l'hypothèse que c'est moi qui ait mal testé. Je te confirme
ça à mon prochain passage général.

**Comment by Eskimon** [comment]
QQun pour donner un autre avis ?

**Comment by firm1** [comment]
Je crois que mon oeil a rippé. J'ai testé et tout va bien.

Sorry.
