### ISSUE TITLE
Google Analytics commence à grogner sur les redirections du site

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2779]
**Google Analytics a écit**

> La propriété ZDS Site reçoit des données de plusieurs noms d'hôtes redondants. En voici certains :
> 
> ```
> www.zestedesavoir.com
> zestedesavoir.com
> ```
> 
> Les noms d'hôtes redondants sont comptabilisés comme des lignes distinctes dans les rapports. Par conséquent, les appels transmis à la même page sur votre site à partir de noms d'hôtes différents seront répartis sur plusieurs lignes. Les données étant réparties sur plusieurs lignes, le trafic indiqué vers des pages spécifiques sera inférieur à la réalité.
> 
> Pour éviter ce problème, pensez à configurer une redirection 301 entre deux de vos noms d'hôtes redondants. Vous pouvez également utiliser un filtre "Rechercher et remplacer" pour supprimer l'élément "www." dans les noms d'hôtes.

Le problème me semble être au niveau de la redirection dns entre `www.zestedesavoir.com` et `zestedesavoir.com`.

ça ressemble donc fortement à de l'infra, je taggue en conséquence.

**Comment by SpaceFox** [comment]
Ce devrait être réglé par #2757

**Comment by Eskimon** [comment]
C'est confirmé ?

**Comment by gustavi** [comment]
@SpaceFox c'est corrigé, tu confirmes ?

**Comment by SpaceFox** [comment]
Je confirme.
