### ISSUE TITLE
La structure schema.org (et donc l'accessibilité) des forums est un peu cassée

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2780]
Le problème est visible uniquement sur la branche de dev en ce moment.

Les moteurs de recherches (Google, Yahoo, etc.) utilisent la structure schema.org pour savoir comment est organisé notre site. Et donc, notre forum avant fonctionnait ainsi.
1. le premier post était marqué comme étant une question (cf. attribut [Question](https://schema.org/Question))
2. les réponses aux topics étaient marqués comme étant des réponses possibles (cf. attribut [suggestedAnswer](https://schema.org/suggestedAnswer))
3. les réponses ayant aidés étaient marqués comme des réponses à la question posée (cf. Attribut [acceptedAnswer](https://schema.org/acceptedAnswer)).

On dirait que la refacto des forums à cassé **l'étape 2**, car on ne retrouve plus la propriété (suggestedAnswer) dans le code html.

J'en déduis que c'est donc une regression.

**Comment by Situphen** [comment]
La structure schema.org du fil d'ariane est cassé sur certaines pages aussi. Globalement, il faudrait que quelqu'un s'y connaissant en accessibilité viennent nous aider !

**Comment by Eskimon** [comment]
Aucune régression ici quand je compare Prod/Beta/dev
1. Depuis quand ? Je ne trouve rien sur la prod' à ce sujet ? Dois-je remonter encore ?
2. C'est le cas si la réponse possède un karma positif (+1>-1)
3. C'est le cas si la réponse est marqué comme "Cette réponse m'a aidée"

La seule chose qui pourrait être à faire et mettre comme "Question" le premier post d'un thread de forum (uniquement de forum, ca n'a pas de sens pour les articles/tutos)

Je tag évolution pour ce dernier point.

@Situphen tu pourras faire un ticket sur cette histoire de fil d'ariane cassé pour qu'on analyse ca ?

**Comment by Situphen** [comment]
C'est fait avec #2803 ! ;)

**Comment by rezemika** [comment]
Up ! :)

Je viens de jeter un coup d'oeil au [schéma d'un topic](https://search.google.com/structured-data/testing-tool?hl=fr#url=https%3A%2F%2Fzestedesavoir.com%2Fforums%2Fsujet%2F9447%2Fgoose-search%2F). Apparemment, tous les posts sont maintenant marqués comme des réponses ("Answer") vraies ou fausses ("An answer offered to a question; perhaps correct, perhaps opinionated or wrong.").

Du coup, le ticket est-il encore d'actualité ?
