### ISSUE TITLE
Perte de proportionnalité d'une source linkée sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2781]
Navigateur Firefox
OS : Android
Smartphone : Galaxy S6 Edge
Problème : la police de la source est trop grande par rapport au reste du texte
Environnement : prod
Screen : 
![2 juin 2015 175419 gmt 0200](https://cloud.githubusercontent.com/assets/6066015/7940397/db9827ce-0950-11e5-8f8f-7184e232c2ba.jpg)

**Comment by artragis** [comment]
Heu, est-ce vraiment un bug?

Il semblerait que la source soit toujours plus grosse que le  texte cité que ce soit ou non sur mobile.

Actuellement la règle est située [ici](https://github.com/zestedesavoir/zds-site/blob/dev/assets/scss/layout/_content.scss#L359). Pour clore proprement ce ticket, je vois deux solutions qui ne sont pas mutuellement exclusives:
- diminuer la taille (1.4rem par exemple)
- variabiliser la taille 

Je ping @sandhose et @Situphen pour qu'ils donnent leur avis, et je ferais la PR qui va bien.

par contre on n'est certainement pas dans un "bug" ici.

**Comment by Situphen** [comment]
Perso, je suis pas spécialiste des tailles donc j'en sais rien. :)

**Comment by pierre-24** [comment]
Si je peux rajouter, il y a un problème quand on a un lien dans la source : 

![screenshot from 2015-12-03 17 56 35](https://cloud.githubusercontent.com/assets/7889675/11567427/554899c4-99e7-11e5-982a-2a5e7e71e494.png)

On voit qu'effectivement, le lien est plus grand que le texte.

**Comment by firm1** [comment]
J'ajouterai même que si on remonte a quelques versions plus tôt on constate  que c'est une régression jamais remarquée. 
Car a l'origine ça n'a pas été  codé ainsi.
