### ISSUE TITLE
Le compte admin ne peut plus faire de modération de topic.

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2783]
Ce problème n'existait pas hier en dev, donc j'imagine que c'est un effet de bord de la PR #2758

**Scénario :**
- Je pars d'un environnement clean, je fais un `python manage.py syncdb`, puis un `python manage.py migrate`
- Je charge les fixtures simples : `python manage.py loaddata fixtures/*.yaml`
- Je me connecte en tant que admin/admin
- Je vais sur un topic par exemple `/forums/sujet/4/rediger-sur-zestedesavoir/`

**Problème** : je ne vois plus les boutons qui permet de passer un sujet en résolu, ni les boutons de modération. Cependant, je peux toujours voir la dernière IP d'un membre et j'arbore toujours le badge staff.

J'en déduis donc qu'on est sur une regression.

**Comment by Eskimon** [comment]
Je tag même bloquant car sans modération les modos vont pas faire les malins longtemps :D

**Comment by Eskimon** [comment]
Et j'invoque @artragis qui aura ptet une idée...

**Comment by artragis** [comment]
voilà mon effet de bord :(

je regarde de plus prêt, mais c'est sûrement à cause de la gestion bien foireuse des autorisations à l'heure actuelle. du coup je vais voir si j'ai pas mis une condition là où il fallait pas.

**Comment by SpaceFox** [comment]
Normalement corrigé.
