### ISSUE TITLE
Les alertes rouges sanglantes ne se voient/lisent plus dans les commentaires d'article/tutoriel

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2787]
Ce bug est visible uniquement sur la version de dev, j'imagine que c'est un effet de bord de la PR #2758 
- Lorsque je signale un message dans le forum en tant qu'admin, je vois l'alerte sanglante : cool
- Lorsque je signale un message dans les comm d'un article en tant qu'admin, je ne vois pas l'alerte sanglante quand je vais sur le message ne question : **pas cool**
- Lorsque je signale un message dans les comm d'un tutoriel en tant qu'admin, je ne vois pas l'alerte sanglante quand je vais sur le message ne question  : **pas cool**

Je taggue large pour le coup.

**Comment by Eskimon** [comment]
Etant donne que le seul bout qui a change et qui explique cela c'est ca : https://github.com/zestedesavoir/zds-site/blame/dev/templates/misc/message.part.html#L204 je fais un ping @artragis ^^ Je suppose que c'est un `with` qui manque :)

**Comment by artragis** [comment]
pas normal mais possible.

**Comment by Eskimon** [comment]
C'est corrigé
