### ISSUE TITLE
Erreur dans la génération du markdown

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2789]
Bonsoir à tous,  
en testant un petit truc, je suis tomber sur une erreur dans la génération du markdown.

![zds_bug_10](https://cloud.githubusercontent.com/assets/8223773/7967212/f34020e2-0a28-11e5-9f30-2b29ba5a82a6.PNG)

Bon après pour tomber sur ce bug j'ai ... peut-être un poil forcé :')

![zds_bug_11](https://cloud.githubusercontent.com/assets/8223773/7967214/f7e0e0aa-0a28-11e5-8fb2-17585c6ad934.PNG)

WinXaito

Edit:  
ps avant de tomber sur ça on obient ça
![zds_bug_12](https://cloud.githubusercontent.com/assets/8223773/7967260/293155cc-0a29-11e5-9b10-f39de8636630.PNG)

**Comment by Eskimon** [comment]
hum... on va vraiment garder un ticket pour ca ? (de toute façon si la réponse est oui il faudra le même sur le [dépôt markdown](https://github.com/zestedesavoir/Python-ZMarkdown) )

**Comment by WinXaito** [comment]
Bien entendu j'ai mis ça en particulier pour plaisanter, après si quelqu'un est motivé à corrigé ça ...

**Comment by Eskimon** [comment]
(en tout cas ca m'aura fait sourire :D )

**Comment by GerardPaligot** [comment]
Je suis presque content que notre Markdown nous disent que nous ne pouvons pas le faire.
