### ISSUE TITLE
Page de contact

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#279]
Faire une page de contact.
Voir sur la ML ce qu'on met dessus (contacts pour l'asso ? Le site lui-même ? Les deux ? etc.)

**Comment by Fumble** [comment]
Cela dépend.
Est-ce qu'on dissocie Zestedesavoir.com et le site de l'asso ou est-ce que Zestedesavoir.com est _de facto_ le site de l'asso?

**Comment by cgabard** [comment]
Perso je pense que tant que Zestedesavoir.com est le seul produit de l'asso, il ne fait pas de sens de séparer les 2. Donc sur la page de contact préciser 
- Les contacts techniques lié au site : 
  - ML
  - Le github pour les issues
  - Eventuellement un responsable technique du site au seins de l'asso
- Les contacts lié a l'asso : 
  - principalement le mail front de l'asso

**Comment by firm1** [comment]
+1 pour mon voisin du dessus.

**Comment by devock** [comment]
+1 aussi

Pour les mails : mail direct ou formulaire de contact ? Dans tous les cas, quel mail pour l'asso ? Pour les mails en @zestedesavoir.com je n'ai pas eu de réponse claire sur la possibilité d'en faire (juste un "je crois pas, mais je ne suis pas sûr", si les personnes ayant accès au manager peuvent vérifier.

Pour le responsable technique : il faut un volontaire et le CA de l'asso devra valider ça (on rentre dans la notion de groupe travail dans le RI)

**Comment by geoffreyc** [comment]
A l'heure actuel on peut créer des redirections mail (donc
devock@zestedesavoir.com -> devock@whatever.com)
On ne peut pas créer de boites mails. Je pense personnellement qu'il serait
judicieux de mettre en place un serveur mail bien configuré. A l'heure
actuel on peut recevoir des mails vers des adresses @zestedesavoir, mais en
envoyer sans se faire mettre en spam sera déjà plus complexe.

2014-04-10 16:05 GMT+01:00 devock notifications@github.com:

**Comment by firm1** [comment]
> A l'heure actuel on peut créer des redirections mail (donc
> devock@zestedesavoir.com -> devock@whatever.com)

J'avais essayé d'en créer une association@zestedesavoir.com mais à chaque envoie de mail dessus ça fail. Du coup j'ai un doute.

**Comment by geoffreyc** [comment]
Effectivement, je pense que ca vient du fait que le domaine utilise le
service anycast. On a donc bien besoin d'un serveur mail sur le serveur de
prod

2014-04-10 16:21 GMT+01:00 firm1 notifications@github.com:

**Comment by firm1** [comment]
Avec les redirections mails, j'en ai profité pour créer la page contact avec les informations adéquates.

Si on sont incomplètes, n'hésitez pas à compléter, je ferme.
