### ISSUE TITLE
Lien sur le pseudo lorsque l'on signale une erreur

### ISSUE THREAD

**Issue by La-source** [zestedesavoir/zds-site#2790]
Bonjour,

J'ai signalé une erreur dans un tuto, ce qui a créé un MP pour les auteurs dudit tuto.
Dans ce MP automatique le html donne:

```
<a href="http://zestedesavoir.com/membres/voir/La%252520source/">La source</a> souhaite vous proposer une correction pour votre tutoriel
```

Donc dans mon pseudo il y a un problème dans le lien vu que sa ne mène pas sur mon profil.

**Comment by GerardPaligot** [comment]
Merci @La-source mais @firm1 a déjà créé l'[issue](https://github.com/zestedesavoir/zds-site/issues/2788) pour ton bug. :)

**Comment by La-source** [comment]
D'accord... désolé ><' je n'avais jamais ajouté d'issue sur GitHub et je me suis dit que je pourrai essayé de le faire moi-même.

Sa m'apprendra a pas regarder avant :D
