### ISSUE TITLE
Le compteur d'alertes ne va pas au delà de dix

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2793]
Le compteur d'alerte est quelque peu trompeur, car au delà de 10 alertes le compteur reste bloqué. Si on a plus de 10 alertes, difficile de le savoir.

Le problème est aussi en prod (mais vu qu'en général on a une équipe très réactive sur les alertes, on ne le voit jamais). Mais on ne sait jamais si les modos décident de faire la grève un jour ... :D

**Comment by Eskimon** [comment]
Tu pourrais expliquer plus ? Car je me souviens d'il y a quelques mois le compteur etait grimpe a 42 sans broncher :D

Tu as teste sur la preprod ou sur dev ou autre ?

**Comment by Eskimon** [comment]
C'est bon en fait j'ai vu et trouve pourquoi !

https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/templatetags/interventions.py#L156

Je corrige ca

**Comment by pierre-24** [comment]
Merci @Eskimon ... Et @GerardPaligot pour la QA ;)
