### ISSUE TITLE
Un staff peut se sanctionner lui même

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2794]
Il existe une petite incohérence dans les droits sur les sanctions.

Un staff peut se sanctionner lui même. ça ne devrait pas être faisable car si quelqu'un fait ça, c'est très probablement qu'il a confondu de page.

**Comment by Eskimon** [comment]
Tu parles des lectures seules et autres banissement c'est bien ca ?

**Comment by firm1** [comment]
Ouaip

**Comment by Eskimon** [comment]
Merged = à fermer :)
