### ISSUE TITLE
L'affichage de mes articles en brouillon est troublant

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2795]
Lorsque je vais dans ma rubrique article, j'ai l'affichage de mes articles en brouillon qui affiche une bulle alors que la bulle est bien vide (normal on est en brouillon).

Il faudrait peut être ne pas afficher la bulle si elle n'a pas d'utilité dans cette rubrique ?

![brouillonay](https://cloud.githubusercontent.com/assets/6066015/7987806/156755f2-0ae0-11e5-90db-1fb209d08466.PNG)

**Comment by Eskimon** [comment]
Bon pire que ca, le nombre de reactions ne remonte carrement pas j'ai l'impression...

**Comment by pierre-24** [comment]
En même temps, c'est logique: l'article n'ayant jamais été publié, il ne peut pas avoir de réactions ;)

**Comment by Eskimon** [comment]
Bon j'ai regle le souci d'affichage ici, mais on a un autre souci qui fait que le commit https://github.com/zestedesavoir/zds-site/commit/0e4b35cb09ba897c46b65b0c8f136b6f24bb7c73 ne renvoi plus le nombre de reactions

**Comment by pierre-24** [comment]
Mmmh ... Quelle branche, chez toi ?

**Comment by Eskimon** [comment]
sur dev

**Comment by pierre-24** [comment]
C'est pour ça que je la trouvais pas ^^

Par contre, tu dis que le commit introduisait déjà le problème ou que ta correction à induit le problème ? (pour un peu savoir ou je dois chercher)

**Comment by pierre-24** [comment]
C'est parti pour une QA d'une heure ;)

**Comment by Eskimon** [comment]
Je resume :

Le probleme de firm1 c'est la bulle, j'ai une PR pour ca https://github.com/zestedesavoir/zds-site/pull/2797

Mon souci est parrallele, c'est une regression sur l'affichage du nombre de reactions. Ca ne marche carrement plus a cause du commit sus-linke. (et meriterait surement une nouvelle issue)

**Comment by pierre-24** [comment]
Merci @Eskimon  :)
