### ISSUE TITLE
Le staff "voit" les articles des autres membres comme si c'etait les siens

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2796]
Probleme bizarre sur ma branche dev...
- Je cree un article avec user
- Je me log avec admin
- Dans la page "tout mes articles" je vois l'article de user

![screenshot from 2015-06-05 10 22 20](https://cloud.githubusercontent.com/assets/761168/8002208/36ec297c-0b6d-11e5-8ce6-0a846104dba1.png)

(Je tag Back car c'est ce dernier qui renvoi trop de choses)

**Comment by GerardPaligot** [comment]
Effet de bord des précalculs, possible ? ( @artragis )

**Comment by artragis** [comment]
si je comprenais le titre, je pourrais te répondre.

2015-06-05 10:33 GMT+02:00 Gérard Paligot notifications@github.com:

**Comment by Eskimon** [comment]
J'ai retitre mais la description est plutot correcte je pense

**Comment by artragis** [comment]
il m'a fallu un moment pour percuter en fait. c'est le "mes" qui est étrange.
C'est _peut être_ un effet de bord de ma PR, mais ça peut aussi en être un du changement de design dans la v4

**Comment by Eskimon** [comment]
@artragis ca vient bien de toi j'ai l'impression car c'est cette ligne qui pose souci je pense : https://github.com/zestedesavoir/zds-site/blame/dev/zds/member/views.py#L488 via ce commit https://github.com/zestedesavoir/zds-site/commit/0e4b35cb09ba897c46b65b0c8f136b6f24bb7c73

**Comment by artragis** [comment]
en effet, je vois pourquoi.

2015-06-05 11:16 GMT+02:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
Tu pourras jeter un oeil ici en meme temps : https://github.com/zestedesavoir/zds-site/issues/2795#issuecomment-109214259

Car c'est induit par le meme commit :)

**Comment by Eskimon** [comment]
C'est corrigé
