### ISSUE TITLE
Passage à Solr 5

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2802]
Le passage à Solr 5 pour nous développeurs aurait plusieurs avantages:
- Fini le schema.xml o/, c'est moins chiant pour la QA.
- Possibilité de partager la configuration entre plusieurs coeurs
- Corrections de bugs
- [Un outil de stastique](https://cwiki.apache.org/confluence/display/solr/The+Stats+Component) très très intéressent 
- Solr est un serveur en standalone. Plus de war ! 
- [et plein d'autre](https://cwiki.apache.org/confluence/display/solr/Major+Changes+from+Solr+4+to+Solr+5)

En bref, que du bonheur ! Y'aura que trés peu de changement dans le code en plus !

Maintenant les mauvaises nouvelles, Haystack n'est pas compatible, mais la [PR est en cours et à juste besoin d'une relecture de code](https://github.com/django-haystack/django-haystack/pull/1148).

**Comment by SpaceFox** [comment]
> as well as an installation script for setting up a "production"
> installation of Solr on *nix platforms managed via /etc/init.d.

J'espère qu'ils gèrent aussi systemd

Sinon je me demande bien comment vont être gérées les options de
configuration : structure des documents à indexer, stemming, gestion des
spécificités des langues, etc. La présentation est floue à ce sujet.
Le 6 juin 2015 12:54, "Hugo Courtecuisse" notifications@github.com a
écrit :

**Comment by DevHugo** [comment]
325 issues sont ouverte la-bas avec ces deux tags, on est pas prêt d'avoir Solr 5.

**Comment by DevHugo** [comment]
Share the love: «  Yes – if it's a clean branch with test coverage it won't take very long for me to merge ! ». Donc on peut penser que ça sera dans un mois ou deux maximum.

**Comment by gllmc** [comment]
Vu qu'elle n'est pas référencée, je précise que cette issue pourra être fermée quand #4096 sera mergée. :)

**Comment by DevHugo** [comment]
J'avais complètement tord au passage.
