### ISSUE TITLE
La recherche renvoi dans la description none.

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2808]
Comme on peut le voir dans le premier résultat, la première description est à None.

![bug_recherche_none](https://cloud.githubusercontent.com/assets/6099338/8044534/aa822112-0e2d-11e5-9f74-01c0565f46ec.png)

@Eskimon : Cela peut t-il faire bugger https://github.com/zestedesavoir/zds-site/pull/2786, dans ce cas la on pourrais avoir des conséquences assez bizarre ?

**Comment by Eskimon** [comment]
> @Eskimon : Cela peut t-il faire bugger #2786, dans ce cas la on pourrais avoir des conséquences assez bizarre ?

Je ne pense pas non, il y a un test pour s'assurer de cela normalement.

**Comment by DevHugo** [comment]
Ok. Good to merge so. Désolé du dérangement.

**Comment by Eskimon** [comment]
@DevHugo du coup ce ticket a-t-il une raison d'être ou pas ?

**Comment by DevHugo** [comment]
Je pense que ça ne se reproduiras plus après la zep-12. On peut fermer donc.
