### ISSUE TITLE
Erreur 500 sur une url modifiée d'un minitutoriel publié

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2809]
Le bug se trouve actuellement en production.

Url incriminée : http://zestedesavoir.com/tutoriels/631/les-compteurs-numeriques/72/ko/

On ne devrait jamais avoir d'erreur 500 dan la vie.

**Comment by Eskimon** [comment]
Qu'en pense la ZEP-12 ? (ping @artragis et @pierre-24 :) )

**Comment by pierre-24** [comment]
Que logiquement, on évite un certain nombres de ce genre de chose, donc qu'on est normalement OK, mais sans déployer la ZEP-12 en prod', j'en mettrais pas ma main à couper.

**Comment by artragis** [comment]
En tout cas http://beta.zestedesavoir.com/tutoriels/631/les-compteurs-numeriques/72/ko/ ne donne pas de 500.

**Comment by Eskimon** [comment]
Plus de 500 ici. Sans information supplémentaire le ticket ne pourra être traité. Je ferme.
