### ISSUE TITLE
passage à Django 1.6

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#281]
Tout est dans le titre.

**Comment by SpaceFox** [comment]
En première approche la migration Django 1.5 --> 1.6 n'a pas l'air trop violente, je vais tenter ça.

**Comment by firm1** [comment]
Le père Noël du jour s'appelle Spacefox et il nous a offert un joli cadeau.

Migration avec succès sur django 1.6

**Comment by cgabard** [comment]
Merci pere noël !

**Comment by Taluu** [comment]
Merci père renard !
