### ISSUE TITLE
Suppression du chapitre lors de la suppression d'un d'icone de chapitre

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2812]
Une erreur 404 apparaît et bloque l'édition du tutoriel lorsqu'un supprime une icone d'un chapitre.

Pour reproduire le bug, suivez les étapes:
- Créé un big-tuto, créé une partie et un chapitre
- Éditer un chapitre et ajouter un icone pour le chapitre
- Aller dans votre galerie et supprimer l'icone
- Tenter d'editer le chapitre

Ping zep-12: @artragis et @pierre-24

**Comment by DevHugo** [comment]
J'ai l’impression qu'il supprime le chapitre, dans la base de données, ce qui serait très embêtant ! Mais pas dans le .git donc on est sauvé. Mais faut absolument supprimer ce champs qui sert à rien.

**Comment by DevHugo** [comment]
Je confirme, on a oublié un `on_delete=models.SET_NULL` dans le modèle des chapters !

C'est __BLOQUANT__ la ! => @Situphen

**Comment by pierre-24** [comment]
Coté ZEP-12, le champ n'existe tout simplement plus, donc on est _safe_ à ce niveau là. Côté _back_ actuel, effectivement, c'est un problème (mais dans tout les cas, faut pas trop aller chipoter sa galerie, c'est sensible, ces petites bêtes là). Enfin, si il suffit de rajouter un `on_delete`, ça va vite.

... De la à être bloquant ?

**Comment by Eskimon** [comment]
C'est genant, pas bloquant. Ce serait bloquant si on pouvait plus rédiger/consulter de tutos du tout. Je reconnais que c'est chiant comme souci, mais il existe depuis des mois (je suppose) et c'est la première fois qu'on en entend parler. Alors bloquant me parait excessif.

**Comment by pierre-24** [comment]
D'autant que si on le corrige vite, il peut passer dans la prochaine release :-)

**Comment by Eskimon** [comment]
Allez zou, voici un quick fix qui se contente juste de virer le champ du formulaire en attendant la ZEP-12.

**Comment by artragis** [comment]
en passant elle est pour quand la prochaine release puisqu'il n'y a plus de
ticket bloquant?

2015-06-17 10:13 GMT+02:00 Eskimon notifications@github.com:

**Comment by SpaceFox** [comment]
Je la lance ce soir.

**Comment by Eskimon** [comment]
> puisqu'il n'y a plus de ticket bloquant?

Si faut regler au moins ca 2727 non ?

**Comment by artragis** [comment]
On a pas détruit le cache?

2015-06-17 11:02 GMT+02:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
> On a pas détruit le cache?

Plus ou moins, il y a une PR pour le revert et une autre pour regler des soucis d'API

**Comment by artragis** [comment]
Ah ok, comme rien n'était marqué "bloquant" dans les pr je pensais que tout
avait déjà été mergé.

**Comment by pierre-24** [comment]
Voilà :)
