### ISSUE TITLE
Le compte anonyme a une dernière date de visite incohérente

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2814]
(via saroupille sur IRC)

Lorsqu'un utilisateur se desinscrit, il passe tout ses posts au compte anonyme. Hors ce dernier n'est utilise par personne et donc a une date de dernier passage sur le site datant de 2014. On tombe dans la situation amusante ou anonyme a reussi a poster _apres_ etre passe sur le site pour la derniere fois ^^

Pour avoir un truc coherent et nickel, il faudrait que la date de derniere visite (https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/models.py#L91) soit mise a jour lorsqu'un membre se desinscrit (ici par exemple https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/views.py#L417)

**Comment by SpaceFox** [comment]
Ou plus simplement masquer la date de dernière connexion sur les comptes qui ne peuvent pas se connecter.

**Comment by Eskimon** [comment]
C'est meme mieux je pense oui

**Comment by pierre-24** [comment]
Voilà qui est fait :)
