### ISSUE TITLE
[Reminder] Reverse le code de la pagination

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2817]
La correction de la pagination inclue une correction temporaire. Celle-ci devra être modifiée lorsqu'une correction dans la librairie: [drf-extension](https://github.com/chibisov/drf-extensions) (custom extensions for Django REST Framework) sera proposé dans [ce fichier](https://github.com/chibisov/drf-extensions/blob/master/rest_framework_extensions/key_constructor/bits.py#L166). 

Les actions suivante sont à éffectuer: 
- Reverse le commit [b502832dd45af37a627396d634a7eb130df35dac](https://github.com/Eskimon/zds-site/commit/b502832dd45af37a627396d634a7eb130df35dac)

OU
- Supprimer le fichier: [zds/api/DJRF3xPaginationKeyBit.py](https://github.com/zestedesavoir/zds-site/blob/dev/zds/api/DJRF3xPaginationKeyBit.py)
- Chaque instruction DJRF3xPaginationKeyBit() devrait être remplacé par bits.PaginationKeyBit()

Il faut donc lire régulièrement les ["changelog"](http://chibisov.github.io/drf-extensions/docs/#release-notes) ici.

Plus d'infos: 
- [La PR accepté](https://github.com/zestedesavoir/zds-site/pull/2816/files)
  - [La PR de base](https://github.com/zestedesavoir/zds-site/pull/2761)
- [L'issue concerné](https://github.com/zestedesavoir/zds-site/issues/2727)

**Comment by vhf** [comment]
Ping @devhugo :p

**Comment by GerardPaligot** [comment]
La pagination a été fixée chez drf-extension ?

Je vois [ce commit](https://github.com/chibisov/drf-extensions/commit/f85a636e42b6ea27e9945963041e2483e65ecf92) qui est nommé "Fixed PaginationKeyBit" et juste derrière [ce commit](https://github.com/chibisov/drf-extensions/commit/3a040b96435a48527c7d3566dfab4b6fe4bae3ea) qui revert le premier commit.

**Comment by DevHugo** [comment]
Je fait ça dans la semaine !

**Comment by DevHugo** [comment]
~~Ouai, c'est bizarre mais sur la branche de release, c'est le code du premier commit et sur la branche master aussi.~~

Eh ba non enfait.

Je tente au pire y'a un tu, que j'avais fait qui teste donc normallement pas de souci :) ! 

**Edit: eh ba ça marche pas, faut encore attendre !**

**Comment by artragis** [comment]
hello on en est où ici?

**Comment by DevHugo** [comment]
La classe n'a plus l'air d'exister et le comportement marche en prod donc je suppose que quelqu'un a du revert le commit et comme le problème à été résolu dans la librairie, ça fonctionne.

**Comment by artragis** [comment]
\o/
