### ISSUE TITLE
[15.6] Impossible d'indexer un tutoriel dont une partie n'est pas publié

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2819]
Il est impossible d'indexer un tutoriel dont une des parties n'est pas indexés.

Comment reproduire:
- Créé un tutoriel avec une partie et publier le.
- Ajouter une partie
- Indexer

**Comment by Eskimon** [comment]
Je met meme "bloquant" car ca fait planter l'indexation solr et donc potentiellement on indexera plus rien.

**Comment by DevHugo** [comment]
Ça indexe tous avant le plantage enfait mais ça fait pas le reste de l'indexation.

**Comment by pierre-24** [comment]
Bref, c'est bloquant quand même.

**Comment by DevHugo** [comment]
Je dit pas le contraire, c'était juste pour l'info quoi.

**Comment by DevHugo** [comment]
@Eskimon ça serait possible de cherry-pick un commit et de me dire si la recherche passe bien ? ça te demande beaucoup de travail ?

**Comment by pierre-24** [comment]
Ah, zut ... Ta PR pointait sur _dev_ et pas sur la branche de release. Et je l'ai mergée :/

**Comment by DevHugo** [comment]
Je refais une Proposition dans quelques minutes

**Comment by pierre-24** [comment]
Là n'est pas le problème, c'est que j'ai mergé une PR au mauvais endroit :/

**Comment by pierre-24** [comment]
Mieux. Après, faut voir si il faut faire un commit de revert ou pas.

@Eskimon ?

**Comment by Eskimon** [comment]
Hum bonne question... Si on fait d'autres commits dans les memes fichiers ca risque de mal se mettre effecivtement... Du coup j'ouvre le revert via le bouton idoine dans la PR fautive ;)
