### ISSUE TITLE
Repenser les tutos de manière plus interactive

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#282]
Actuellement les tutos sont très tournés texte. Pourtant avec l'interactivité du web, il y a probablement beaucoup plus a faire. 

J'ouvre cette issue pour en parler et partager des idées sur le sujet, le but n'est pas d'implémenter des choses mais échanger sur le sujet.

En particulier voici deux liens d'exemples de cours plus modernes dont on pourrait s'inspirer (ce sont des points d'entrées, explorez les exemples) : 
- https://github.com/GitbookIO/gitbook
- http://interactivepython.org/runestone/static/thinkcspy/index.html

N'hesitez pas à en rajouter

**Comment by firm1** [comment]
L'interactivité dans les tutos est clairement un plus.

Rajouter des exercices par exemple dans les tutos pourrait être un point à explorer. Pour faire simple on pourrait rajouter des exercices à la fin de chaque extrait d'un tuto.

Le seul détail assez difficile a gérer est celui de savoir, quel type d'exercice on souhaite demander ?

Pour faire du QCM, c'est assez basique, par contre si on essaye de faire des exercices de type code, c'est déjà plus complexe.

Ce qui nous serait utile, serait une API sur laquelle on se connecte en ligne, on envoi un morceau de code avec le type de code (js, python, c, etc.) et l'API nous retourne le résultat de l'execution du code en console. ça nous permettrait à terme de proposer des exercices de code interactifs dans les tutos.

**Comment by cgabard** [comment]
Ce meta ticket est prit en charge par plusieurs zeps existantes voir est partiellement implémenté. Je ferme.

**Comment by Eskimon** [comment]
Lien vers une des ZEP : http://zestedesavoir.com/forums/sujet/822/zep-10-module-dexercices/
