### ISSUE TITLE
[15.6] Amélioration du module des Unes et de la phrase "Nouveau !"

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2820]
Via [Shigerum](https://zestedesavoir.com/membres/voir/ShigeruM/) :
### Sur le message d'info
- [x] Il serait bien de pouvoir ne pas afficher de message du tout. Là, à partir du moment où on en a mis un une fois, on peut le remplacer par un autre, mais pas le supprimer. Or il arrivera qu'on n'ait rien à dire.
- [x] Il serait bien de pouvoir modifier la mention "Nouveau". Parfois on voudra probablement passer des messages sur des sujets qui ne sont pas forcément "nouveaux" ("Urgent", "Info" etc...)
- [x] Charger dans le formulaire le dernier message posté (pour corriger rapidement une faute par exemple)
### Sur les Unes
- [x] Il serait pas mal de ne pas rendre obligatoire le champ "Auteur". Dans certains cas, ça n'a pas beaucoup de sens. Exemple : le CdS sur les arbres. Sur la bêta j'ai mis "c_pages" comme auteur alors que c'est le truc communautaire par excellence.
- [ ] C'est sûrement plus chiant à faire, mais pouvoir avoir la main sur l'ordre des unes serait chouette. Là, elles sont classées par date de dernière modif. Donc si on se rend compte d'une coquille sur la 5ème Une, elle repasse en tête (à moins de faire une modif bidon sur les 4 autres, dans le bon ordre…). On voudra aussi probablement mettre en Une certains trucs plus longtemps que d'autres.

**Comment by ShigeruM** [comment]
Pour moi il y a deux choses :
- Pouvoir supprimer la mention "nouveau" pour pouvoir afficher un message qui n'a rien de "nouveau" mais qui a un intérêt tout de même.
- Pouvoir supprimer totalement le message (mention "nouveau" ou pas) quand on n'a rien à dire.

Après c'est peut-être à voir comme une évolution de la feature qui, en l'état, fait bien le job tout de même.

**Comment by Eskimon** [comment]
J'ai mis a jour mon premier post pour refleter ca

**Comment by Eskimon** [comment]
@ShigeruM j'ai une question pour toi. À l'heure actuelle lorsqu'une Une est mise à jour elle repasse devant toute les autres. Si on vire la mise à jour de la date lors de la modification, elle restera à sa place mais tu n'auras plus moyen de la déplacer (à part en en créant une nouvelle qui repassera devant). Est-ce que ca t'irais comme solution dans un premier temps (puis plus tard implémenté un vrai système de tri) ?

**Comment by ShigeruM** [comment]
Tu veux dire qu'il y aurait une checkbox "mettre à jour la date de modif Oui/Non" ? Un peu comme lors de la publication des tutos ? Si c'est ça, oui, ça peut être pas mal !

**Comment by Eskimon** [comment]
Ah j'avais pas pensé à la checkbox mais oui ca pourrait un moyen simple de faire ca dans un premier temps :) . Je met l'idée en oeuvre dans le weekend ou la semaine du coup :)

**Comment by ShigeruM** [comment]
Tu es exceptionnel comme Caribou, on te l'a déjà dit ?

**Comment by Eskimon** [comment]
:blush:

**Comment by Eskimon** [comment]
@ShigeruM voila les modifications apportées à présent (en attente de QA mais je te tiens informé histoire d'avoir des retours !):

### Phrase "Nouveau"
- Le "Nouveau" est changeable en autre chose si tu veux (champ libre).
- Tout les champs sont facultatifs. Si un champ est vide alors il ne s'affichera pas sur la page d'accueil.

### Les Unes
- Les auteurs sont maintenant un champ libre (texte de 100 caractères max.) et facultatif
- Les Unes apparaissent en ordre anté-chronologique dans ta liste d'édition. La plus récente sera alors logiquement en haut puis on descend vers la plus ancienne.
- Une checkbox te de demandera si tu veux mettre à jour la Une pour la faire remonter en premier (mise à jour de la date de publication en interne). Cette checkbox est présente mais sans effet lors d'une création de Une.

Enfin, dans un module comme dans l'autre les champs URL impose des URL (commence par `http://`)

voili voilou, si tu as d'autres remarques à faire hésite pas !

(PS: Les changements ne sont pas encore visible en préprod' !)

**Comment by artragis** [comment]
> (commence par http://)

le https est-il accepté?

**Comment by Eskimon** [comment]
> le https est-il accepté?

Oui bien sur. Je voulais juste dire qu'il fallait une adresse web et non pas un texte quelconque.

**Comment by artragis** [comment]
ok, merci.

**Comment by Eskimon** [comment]
Les differentes idees de la com' ont ete integre, je propose qu'on en reste la pour ce ticket et que l'on voit comment le besoin evolue avant d'aller faire plus de dev. Je ferme et laisse les gens de la com' nous faire des retours apres utilisation.
