### ISSUE TITLE
L'affichage des dates sur la home en version mobile n'est pas optimal

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2828]
Tout est dans le titre et aussi visible sur le scène suivant.

![screenshot_2015-06-18-15-44-57](https://cloud.githubusercontent.com/assets/6066015/8232777/848e4510-15d2-11e5-99ac-9288fa26989a.png)

**Comment by GerardPaligot** [comment]
C'est quoi le problème ?

**Comment by firm1** [comment]
Au lieu d'écrire Mardi 28 avril 2015, on devrait avoir "28/04/2015"

**Comment by GerardPaligot** [comment]
Pourquoi donc ? Sur la home actuelle, c'est le même format et ça n'a jamais dérangé personne, moi encore moins.

**Comment by firm1** [comment]
Avant tout n'étaient pas entassé dans une boite, on se sent un peu à l'étroit du coup.

**Comment by GerardPaligot** [comment]
Entassé, c'est un bien grand mot mais je vois ce que tu veux dire.

Cela dit, je reste contre cette fonctionnalité. Si nous avons la place pour mettre toute la date, autant ne pas s'en priver.

**Comment by SpaceFox** [comment]
100% d'accord avec Andr0 ici.

**Comment by GerardPaligot** [comment]
Bien, si un jour cela dérange la communauté, il sera encore temps d'ouvrir une issue pour demander de faire la modification mais aujourd'hui, autant le CdP que le DTC sont d'accord pour dire que si on peut afficher toute la date, autant ne pas s'en priver. Je ferme.
