### ISSUE TITLE
human_date.py from ProgMod

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#283]
Quel est l'intérêt de se promener avec un filtre human_date (dans utils/templatetags/humane_date.py) alors qu'on a un standard pour ça ?
https://docs.djangoproject.com/en/dev/ref/contrib/humanize/#naturaltime (localisé)

**Comment by firm1** [comment]
Aucun intérêt ... à virer :-)

**Comment by firm1** [comment]
Fixée -> mergée -> en prod.

Merci, je ferme
