### ISSUE TITLE
Améliorer l'éditeur

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2830]
Aujourd'hui, je me concentre beaucoup plus sur le contenu de ZdS, notamment dans le cadre de ce [projet](https://zestedesavoir.com/forums/sujet/3404/learn-it-faire-ses-listes-de-vocabulaire/).

Je suis donc passé de l'autre côté de la "barrière" : utilisez ce que nous développons. Je peux vous dire que l'éditeur est juste horrible à utiliser pour écrire du contenu. J'ai identifié plusieurs raisons :
- **La zone de saisie est minuscule**. La première chose que je fais, c'est l'étendre au maximum de l'écran pour avoir une vision globale de ce que je fais.
- **Aucun retour visuel de ce que je fais**. Je dois toujours cliquer sur "Aperçu", regardez ce que ça donne puis, à nouveau, agrandir ma zone de saisie parce qu'elle se réduit automatiquement.
- **Aucune sauvegarde automatique de ce que j'écris**. Je ne compte plus le contenu que je perds rien qu'avec un rafraichissement accidentel. C'est très très très frustrant de perdre un contenu de plusieurs pages.

Donc globalement, qu'est ce que je fais ? J'ouvre stackedit.io et j'écris mon contenu là dessus. Puis, quand j'ai terminé, je copie colle dans ZdS.

Alors, je vois 2 améliorations possibles :
- Il faut améliorer notre éditeur (voir point suivant) mais aussi être compatible avec d'autres éditeurs Markdown. Je ne sais pas du tout comment ça fonctionne techniquement mais je sais que stackedit et Google Doc peuvent se lier pour créer du contenu. Les documents Google Doc peuvent automatiquement rediriger vers un document stackedit.
- Améliorer notre éditeur en consacrant une page entière pour ça, en retirant la sidebar et conserver juste l'en-tête, l'éditeur à gauche et le rendu à droite.

Je tag back aussi parce que je pense qu'il peut y avoir des tâches Back aussi. Notamment ce qui est lié à la sauvegarde des textes d'un utilisateur.

**Comment by Eskimon** [comment]
Coucou ! As tu vu la ZEP sur le sujet ou pas ? Je pense que tes idées seraient pas mal la bas :)

https://zestedesavoir.com/forums/sujet/1009/zep-14-refonte-de-lassistant-dedition-markdown/

**Comment by GerardPaligot** [comment]
Oh. On ferme cette issue ?

**Comment by Eskimon** [comment]
Je pense oui, histoire de concentrer les discussions avec le plus grand nombre :)
