### ISSUE TITLE
Importer une liste de .tuto présent dans un dossier

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2831]
Avant le merge de la ZEP-12, il faut avoir la possibilité de migrer un dossier avec des .tutos pour convertir tous ces tutoriels dans le format ZdS et ainsi pouvoir se débarrasser du support des .tutos dans Zeste de Savoir.

Ca permettra après de migrer ces tutoriels dans le nouveau format des contenus de la ZEP-12.

**Comment by pierre-24** [comment]
Justement, je disais ce matin à @Eskimon que j'avais complètement oublié cette histoire de .tuto et qu'il fallait que je me penche dessus ce weekend. Donc ...
- Soit on converti les .tuto (et donc faut écrire un script) et on ne développe plus cette fonctionnalité
- Soit on la code et donc pas besoin de convertir

J'avoue que la première option est séduisante, mais si c'est moi qui l'écrit, je coderai direct ZEP-12-_friendly_ pour éviter les problèmes.

(j'en profite pour importer @artragis pour qu'il participe à la discussion)

**Comment by GerardPaligot** [comment]
Ca vous concerne directement alors je vous laisse gérer. Sachez simplement que l'équipe ZdS accepte d'importer tous les .tuto en privé sur l'auteur Auteur externe. Sachant qu'un script de conversion .tutos -> zmarkdown est déjà dispo. Autant opter sur cette conversion puis d'utiliser votre script pour passer du zmarkdown au zep12.

.tutos : Tutoriel format SdZ
zmarkdown : Format ZdS pré ZEP-12
zep12 : Format ZdS post ZEP-12

**Comment by artragis** [comment]
Si le script .tuto->zmarkdown donne vraiment un dossier tel qu'on l'a dans
zds v1, moi je prends. Sinon, effectivement va falloir passer par un truc
fait par nos propres soins car actuellement c'est un simple .xml

**Comment by pierre-24** [comment]
... D'autant que pour rappel, on prend les tutos v1 (enfin, sauf si c'est mac qui les compresse :p )

**Comment by artragis** [comment]
(sauf si c'est mac qui les compresse en ligne de commande à la bourrin)

2015-06-19 15:55 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by GerardPaligot** [comment]
> (sauf si c'est mac qui les compresse en ligne de commande à la bourrin)

Je n'avais pas utilisé la ligne de commande.

**Comment by pierre-24** [comment]
Mouais, stop le /trolling/.

Tout ça pour dire que si on a un outil qui fait .tuto → v1, alors on a 
besoin de rien faire.

**Comment by GerardPaligot** [comment]
Je ne sais pas pour vous mais moi je ne trollais pas. L'archive que j'avais faites était un ZIP tout à fait standard sur OS X et utilisé par tous ses utilisateurs.

> Tout ça pour dire que si on a un outil qui fait .tuto → v1, alors on a besoin de rien faire.

Vous, potentiellement pas. Mais pour le staff, il faut un outil qui prend plusieurs .tutos pour faire tous les imports.

**Comment by Eskimon** [comment]
Du coup... on a fait quoi au final ici :s ?

**Comment by GerardPaligot** [comment]
Faut que le staff (ou une autre personne compétente) se charge de la migration de tous les .tutos dans un format zds.

**Comment by firm1** [comment]
C'est pas un peu trop tard. La zep 12 est passée donc on ne peut plus
recuperer les .tutos non convertis.

Sauf si on developpe un script pour ça

Le dim. 1 nov. 2015 17:09, Gérard Paligot notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
@firm1 Ce qui est cool avec Git, c'est que tu peux retourner dans le passé. :)

**Comment by pierre-24** [comment]
Et quand bien même, rien de l'ancien module n'as encore disparu (voir `/oldtutorial/`, toussa ...)

**Comment by firm1** [comment]
On va pas retourner dans le passé en prod quand même, si ? Parce que c'est
la bas que se trouve tous les .tuto a migrer.

Le oldtutorial il me semble qu'il ne donne pas l'acces a la liaison des
profils aux .tuto on est obligé de le faire via l'import et donc ça suppose
que l'auteur soit en possession de son .tuto en local (ce qui n'est pas
toujours le cas).

Le lun. 2 nov. 2015 15:04, Pierre Beaujean notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
> On va pas retourner dans le passé en prod quand même, si ? Parce que c'est
> la bas que se trouve tous les .tuto a migrer.

C'est l'équipe technique ici. Des données sur la prod, on peut aller les chercher si c'est nécessaire. Faut pas dramatiser les choses comme ça. :)

**Comment by firm1** [comment]
Non mais ce n'est pas dramatique, je répondais juste a ta remarque qui disais que le staff doit se charger de la migration. Ce n'est plus du ressort du staff puisqu'ils n'ont plus l'interface pour le faire. Donc soit on fait un script pour migrer les .tutos , soit on copie en ssh depuis la prod tous les tutoriels à importés et le staff le fait un par un via l'interface `oldtutoriels`

Mais le fond de la pensée étant qu'il y'a une action à faire coté technique au préalable

**Comment by GerardPaligot** [comment]
Nous sommes d'accord. Il faudrait donc que vous créez un sujet dans la zone staff pour décider des tutoriels que vous désirez conserver. Puis l'équipe technique fera le nécessaire.

**Comment by GerardPaligot** [comment]
@artragis @pierre-24 Vous confirmez que cette issue n'est plus nécessaire ?

**Comment by artragis** [comment]
Pour l'instant laisse là ouverte.

**Comment by GerardPaligot** [comment]
On ne supporte plus les .tuto depuis v19.
