### ISSUE TITLE
Filtre "roman"

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#284]
Le filtre "roman" (utils/templatetags/roman.py) sert-il à quelque chose ?

**Comment by firm1** [comment]
Il sert pour la numérotation des parties/chapitres (je sais plus trop, je ne suis pas en mesure de verifier)

**Comment by firm1** [comment]
> Le filtre "roman" (utils/templatetags/roman.py) sert-il à quelque chose ?

Après recherche, il est encore utilisé pour la numérotation dans le sommaire.

**Comment by SpaceFox** [comment]
OK, ça répond à la question, donc je ferme :)
