### ISSUE TITLE
Le script de déploiement ne vérifie pas l'existence du tag a déployer

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2842]
Le script de déploiement ne vérifie pas l'existence du tag a déployer et du coup ca plante au milieu de nulle part si jamais il est absent. Il faudrait que l'existence du tag soit vérifié avant le lancement du mode maintenance et tout le tsoin-tsoin.

(donc bouger ca au debut par exemple https://github.com/zestedesavoir/zds-site/blob/dev/scripts/deploy.sh#L42 )

**Comment by pierre-24** [comment]
... Bloquant, non ?

**Comment by Eskimon** [comment]
Pas vraiment, le script marche bien c'est juste que si la personne qui déploie est rapide alors le tag est pas encore prêt et du coup ca merde.

**Comment by SpaceFox** [comment]
Non, c'est juste chiant quand tu fais une release un peu à l'arrache et que tu as oublié qu'il fallait attendre.

Le vrai problème, c'est que le script laisse le système dans un état instable.

**Comment by GerardPaligot** [comment]
@gustavi @vhf J'ai cru comprendre que vous modifiez le script de déploiement. Vous savez jeter un oeil à cette issue ?

**Comment by vhf** [comment]
@gustavi Si tu galères on peut regarder ensemble. Je t'assigne ici.

**Comment by gustavi** [comment]
Ça a été corrigé depuis
