### ISSUE TITLE
[15.6] Les boutons de formulaires sont mal lisible

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2849]
Sur la beta (15.6) les couleurs des boutons de formulaires (tout du moins ceux disant "Apercu/Valider") ont change de contraste et deviennent difficile a lire.

Avant:
![screenshot from 2015-06-24 13 41 28](https://cloud.githubusercontent.com/assets/761168/8329104/f9ee79e4-1a76-11e5-995e-66e84c384bbb.png)

Apres:
![screenshot from 2015-06-24 13 41 34](https://cloud.githubusercontent.com/assets/761168/8329106/fdcb8bce-1a76-11e5-9b26-9e6662ff3d73.png)

**Comment by artragis** [comment]
Il en est de même pour le bouton "Lecture ZEN":

Avant:
![old_zen](https://cloud.githubusercontent.com/assets/1523653/8390676/3a911222-1ca2-11e5-9a75-c58c44bf775d.PNG)

Après 15.6
![new_zen](https://cloud.githubusercontent.com/assets/1523653/8390678/43f30ea6-1ca2-11e5-8e7c-6bf3208495a3.PNG)

**Comment by Situphen** [comment]
Étant donné que le texte n'est plus visible facilement, je pense que c'est Bloquant ! J'essaye de voir ça ce soir. @sandhose, si tu as le temps de le faire avant moi, ne te gêne pas ;)

**Comment by Situphen** [comment]
Le bug est vraiment bizarre ! On dirait que c'est Firefox qui interprète différemment le CSS.

| Béta | Prod |
| --- | --- |
| ![Situation 1](http://i.gyazo.com/abb0ae72ceae89435db3f58984c9b9a5.png) | ![Situation 1](http://i.gyazo.com/2a2714f2108dc9af45662accb04c61ad.png) |
| ![Situation 2](http://i.gyazo.com/9903b1a0f8aecefa2d69252ee4e326bb.png) | ![Situation 2](http://i.gyazo.com/abd390b0f11a65a88dae1681f7960088.png) |

Je me demande si c'est dû aux modifications SCSS du commit https://github.com/zestedesavoir/zds-site/commit/61235dd93c6ee402136b738832279c52f8d2b24a...

**Comment by sandhose** [comment]
Si, `git bisect` vient de m'informer que c'est ta faute, @Situphen :^)

C'est corrigé dans la #2858

**Comment by Situphen** [comment]
Corrigé ! Merci @sandhose :)

**Comment by Eskimon** [comment]
Pour info ce bug ne devait pas être considéré comme bloquant. Ilbedt gênant oui mais n'empêche pas l'utilisation du site et ne compromet pas la sécurité des données.

**Comment by Situphen** [comment]
> mais n'empêche pas l'utilisation

pour moi si ça empêche l'utilisation du site !

**Comment by artragis** [comment]
on est obligé de se disputer pour un truc déjà corrigé?
