### ISSUE TITLE
Le filtre upfirstletter

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#285]
Le filtre upfirstletter (utils/templatetags/upfirstletter.py) semble être une redite de (celui-ci)[https://docs.djangoproject.com/en/1.6/ref/templates/builtins/#capfirst], à ceci près qu'il semble adapté pour contourner un bug de humane_date.
Pour moi, soit human_date est inutile (cf issue #283 ) et il doit sauter, soit human_date est utile et c'est cette human_date qui doit être corrigée. Donc dans tous les cas ce filtre n'a pas lieu d'être.

**Comment by firm1** [comment]
C'est fixée -> mergée -> en prod.

Merci, je ferme.
