### ISSUE TITLE
Impossible d'acceder à la documentation de l'API en prod [15.5]

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2851]
Url incriminée : https://zestedesavoir.com/api/
Navigateur : Firefox

Le screen obtenu : 
![cors-1](https://cloud.githubusercontent.com/assets/6066015/8330355/1b07380a-1a81-11e5-9f78-bac73eb299e0.PNG)

Le contenu de ma console JS : 

![cors-2](https://cloud.githubusercontent.com/assets/6066015/8330351/17749c8c-1a81-11e5-992f-0aa6493125ff.PNG)

Etant donné que le problème n'est pas présent en beta, je soupçonne un pb d'infra.

**Comment by DevHugo** [comment]
Marche sur la beta, faudrait vérifier le paramètre « CORS_ORIGIN_ALLOW_ALL » dans la config de prod et vérifier ce cas la, https://github.com/ottoyiu/django-cors-headers/issues/50.

**Comment by Situphen** [comment]
Moi en HTTPS j'ai toujours l'erreur "fetching resource list: http://zestedesavoir.com/api/api-docs/" mais en HTTP ça fonctionne normalement sur la prod !

**Comment by Eskimon** [comment]
Ca a l'air de dépendre du navigo

**Comment by Situphen** [comment]
Bah moi c'est Firefox comme @firm1 ! FF 38.0

**Comment by sandhose** [comment]
C'est lié à #2718, et sera fixé avec la PR #2757

**Comment by pierre-24** [comment]
Bon, ça, au moins, c'est réglé:

![screenshot from 2015-07-05 11 09 42](https://cloud.githubusercontent.com/assets/7889675/8511059/60246c9a-2306-11e5-85f0-01cb2c6083cb.png)
