### ISSUE TITLE
Impossible d'utiliser les critères de recherche sur mobile 

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2857]
Quand on fait une recherche sur mobile on ne peut pas utiliser les critères de recherche car il ne sont pas visible. En effet, ils sont dans la barre à droite et cette barre n'est pas visible.

**Comment by Luuka** [comment]
Je viens de regarder le code, à l'origine les critères sont censés être déplacés vers le menu mobile, le problème se situe dans la fonction `appendToSidebar` [ici](https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/mobile-menu.js#L165) qui ne gère pas l'import des listes à puces.

Au passage l'attribut `data-title` des critères de recherche est erroné [ici](https://github.com/zestedesavoir/zds-site/blob/dev/templates/search/search.html#L42)

Après je m'interroge un peu sur la pertinence d'avoir les critères cachés dans le menu, peut être juste les mettre au dessus de la barre de recherche ? (par contre je ne sais pas si c'est faisable simplement) :)

**Comment by DevHugo** [comment]
> Je viens de regarder le code, à l'origine les critères sont censés être déplacés vers le menu mobile, le problème se situe dans la fonction appendToSidebar ici qui ne gère pas l'import des listes à puces.

Ok, merci, ça m'évite de debug le truc.

> Après je m'interroge un peu sur la pertinence d'avoir les critères cachés dans le menu, peut être juste les mettre au dessus de la barre de recherche ? (par contre je ne sais pas si c'est faisable simplement) :)

Ouai, je pense que ça serait mieux en-dessous. J'aurais pas eu le réflexe d'aller dans le menu.

**Comment by pierre-24** [comment]
Fix'd :)
