### ISSUE TITLE
La fixature topics.yml n'a pas de text_html de remplis

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2860]
Dans le fichier, fixatures/topics.yml, il manque un attribut `text_html` dans le `Comment` avec l'id 5, du coup, quand on affiche la fixatures, on voit le sujet vide. 

Dans le genre, pas important, on peut pas faire moins!

**Comment by pierre-24** [comment]
C'est aussi le genre de "connerie" qui prend 30 secondes à corriger ;)

**Comment by DevHugo** [comment]
Faut juste rajouter les ""+ partout sur la chaine HTML. Donc c'est un peu long ou on supprime cette fixature

**Comment by artragis** [comment]
"fixture". C'est typiquement le genre de fixture qui doit être chargée avec `load_factory_data` qui elle appellera "update_text" et fera le save adequat.

**Comment by gllmc** [comment]
J'enlève le tag `Facile` vu que la solution "simple" (ajout d'un `text_html`) serait ingérable (cf #3082).
