### ISSUE TITLE
[beta 15.6] Les méta des tutos dans l'affichage de petite liste sont plus sur 2 lignes

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#2861]
Les auteurs + catégories des items de la liste des tutoriels sur 2 colonnes sur l'accueil sont actuellement sur une ligne, alors qu'il devraient être sur deux.

Comment ils sont:
![image](https://cloud.githubusercontent.com/assets/1549952/8398347/dcf29f42-1dea-11e5-9ae1-c39552f09850.png)

Comment il devraient être:
![image](https://cloud.githubusercontent.com/assets/1549952/8398346/ce7926b6-1dea-11e5-81b3-dfe4bc9542df.png)

Je vais corriger ça, sur la branche de release (parce que je veux pas une MEP avec ça sur la home :p )

**Comment by sandhose** [comment]
Eh bien ça a été introduit par moi-même, par la 182c2f1 ; my bad

C'est réglé avec #2862

**Comment by pierre-24** [comment]
Ça, c'est réglé, BTW ;)
