### ISSUE TITLE
L'outil de diff est complexe à utiliser

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2863]
Plusieurs problèmes ont été reportés ([là](https://zestedesavoir.com/forums/sujet/3490/interface-de-lhistorique-des-versions/?page=1#p63126) et [là](https://zestedesavoir.com/forums/sujet/2850/voir-ce-qui-a-ete-modifie-entre-plusieurs-versions-dun-article/#p51470)). Outre la demande pour avoir un diff sur les articles (#1443, qui sera offerte par la ZEP-12), cette interface n'est pas pratique. 

> - Sur la page d'historique, la date s'affiche en anglais.
> - Sur l'interface **Diff**, les noms des nouveaux fichiers n'apparaissent pas.
> - Sur l'interface **Diff**, on pourrait clarifier quelle version est à gauche et à droite.
> - Sur l'interface **Diff**, j'ai l'impression qu'on compare la version actuelle à la version avant le commit, mais pas les modifications apportées par le commit. Il serait plus logique de voir ce qu'un commit a modifié, ou de laisser le choix à l'utilisateur des versions à comparer (par exemple pour voir les modifications apportées entre deux mises en validation).

**Comment by yapper-git** [comment]
> Sur la page d'historique, la date s'affiche en anglais.

D'ailleurs la légende aussi était en anglais mais je l'ai supprimé dans ma PR #2952.

Pour la date, c'est à cause de ce code:
https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/templatetags/date.py#L73

Je me demande comment coder cela et quoi afficher ??
En modifiant `__ABS_HUMAN_TIME_FMT = "%d %b %Y, %H:%M:%S"` il est simple de ne pas afficher le N° du mois mais dans ce cas c'est peut-être moins élégeant… Sinon il est possible de laisser django gérer (lui donner un datetime) mais cela affiche par défaut: `juil. 31, 2015, 9:13 matin` par ex. **Dites-moi la syntaxe que vous voulez et je tâcherai de faire la modification dans la PR.**

> Sur l'interface Diff, les noms des nouveaux fichiers n'apparaissent pas.

Bug corrigé dans par #2952 

> Sur l'interface Diff, on pourrait clarifier quelle version est à gauche et à droite.

Je ne sais pas si c'est important de préciser car comme d'hab
- gauche = version1, a priori plus ancienne (en général commit précédent)
- droite = version2, a priori plus récente (en général commit actuel)

> Sur l'interface Diff, j'ai l'impression qu'on compare la version actuelle à la version avant le commit, mais pas les modifications apportées par le commit. Il serait plus logique de voir ce qu'un commit a modifié, ou de laisser le choix à l'utilisateur des versions à comparer (par exemple pour voir les modifications apportées entre deux mises en validation).

Bug corrigé dans par #2952
