### ISSUE TITLE
[Beta 15.6] Pas de message en avant affiche "NOUVEAU" quand même

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2865]
Serveur : Bêta
Version : v15.6-RC3
Système : OS X
Navigateur : Google Chrome Version 43.0.2357.130 (64-bit)

Scénario :

Rendez-vous sur la page d'accueil et constatez le mot "Nouveau!" sans aucun message.

Au cas où quelqu'un aurait mis un message entre temps, voici un rendu au moment où j'ai constaté le bug :

![capture d ecran 2015-06-29 a 18 08 31](https://cloud.githubusercontent.com/assets/1913901/8412436/41dc2ae6-1e8a-11e5-9198-160581a3b30d.png)

**Comment by Eskimon** [comment]
En fait c'est pas censé arriver. Là c'est juste que la mise en prod' de la nouvelle façon de faire a fait sauter le message précédent mais en soi ça devrait pas se reproduire. Donc en gros le fait de pouvoir juste mettre un titre de bug = "It's not a bug, it's a feature!" (ça faisait longtemps tiens !)

**Comment by Situphen** [comment]
Je pense qu'on devrait mettre le message en obligatoire, non ?

**Comment by Eskimon** [comment]
Seul les gens de la com' ont besoin de cet outil. Je pense qu'on peux leur faire confiance sur l'utilisation et du coup si un jour ils ont besoin que du titre bah ils peuvent. Mais a priori oui il y aura toujours un texte (mais encore une fois, on doit pouvoir faire confiance aux gars de la com' :)

**Comment by GerardPaligot** [comment]
J'aime pas trop l'argument : faisons confiance à l'utilisateur, aussi qualifié peuvent-ils l'être à l'heure actuelle.

**Comment by ShigeruM** [comment]
Je pense que c'est parfait comme ça. Il pourrait arriver qu'on ne mette qu'une accroche sans message, pourquoi pas. Rendre le message obligatoire serait ajouter une contrainte là où il n'y en a pas besoin, donc ça complique le système (relativement) inutilement.

Je viens de tester sur la bêta, c'est vraiment top comme ça. Merci aux devs !
