### ISSUE TITLE
Erreur 500 lors de la modification de l'image d'un tutoriel déjà publié.

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2866]
Prerequis : 
- Etre staff

Scénario : 
1. Aller sur un article déjà publié qui ne vous appartient pas
2. Consulter la version hors ligne de l'article
3. ajouter une image et valider
4. **Pouf : Erreur 500**

Précision : je ne reproduis pas le bug avec mes propres articles, je ne reproduis pas le bug sur des articles non publics.

J'ignore si je dois tagguer en bloquant (car c'est peut être du au problème de synchro preprod <-> prod). Bref, dans le doute, je taggue serré.

**Comment by artragis** [comment]
à tester sur la béta pour voir si ça a changé?

**Comment by Eskimon** [comment]
On parle bien du logo de l'article ? Si oui alors ca semble marcher puisque j'arrive à changer l'image de l'article sur la pierre de lait. (j'ai une erreur à la publication mais je pense que c'est du à la génération pdf)
