### ISSUE TITLE
Les dates de la Homepage qui jouent à cache-cache

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2867]
OS : Windows 7
Navigateur : Firefox 38
Température extérieure : **28°C**
Zoom : 100%

Comme on peut le voir dans la capture d'écran ci-dessous, la date de publication d'un tutoriel essaye de se cacher.

![cachette](https://cloud.githubusercontent.com/assets/6066015/8434029/53c2467c-1f49-11e5-9d85-c7deea92d357.PNG)

**Comment by GerardPaligot** [comment]
Se passe quoi si on a, en plus, une description sur 2 lignes à ce niveau ? Genre on publie un nouveau tutoriel et on fait passer le tuto Arduino dans la liste d'en dessous.

PS : Je ne fais que le mentionner mais je n'ai jamais aimé ces 2 colonnes pour la suite des tutoriels.

**Comment by firm1** [comment]
@GerardPaligot ça donne ça : 

![plink](https://cloud.githubusercontent.com/assets/6066015/8454633/5bf3f8a2-1fff-11e5-8d06-d1932eac3c3b.PNG)

**Comment by GerardPaligot** [comment]
Ah d'accord, l'espace n'était pas destiné à afficher la description. Ca va être quelque chose à revoir.

**Comment by Situphen** [comment]
@SpaceFox : On doit faire le fix en dev ou en prod ?

**Comment by SpaceFox** [comment]
dev

**Comment by Eskimon** [comment]
Ca me semble ok.
