### ISSUE TITLE
[beta] Les catégories des forums ne respectent pas l'ordre défini dans le tri

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2868]
Petite comparaison entre la [prod](https://zestedesavoir.com/forums/) et la [beta](https://beta.zestedesavoir.com/forums/)

Sur la beta, la catégorie Communauté apparait en premier, alors que d'après l'ordre définit c'est d'abord Savoirs qui doit apparaitre. D'autant plus que le comportement est incohérent avec celui de la topbar.

Il s'agit donc d'une regression de la nouvelle release.

**Comment by GerardPaligot** [comment]
C'est du back. J'avais vu passer le bug pendant mon refacto mais j'ai zappé de le corriger.

**Comment by GerardPaligot** [comment]
Pour information à celui qui va corriger le bug :

Les informations de la topbar sont récupérées [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/templatetags/topbar.py#L19) et la liste des catégories avec ses forums sont traitées [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/views.py#L35). Et avant, les deux utilisaient `topbar.py`.

D'un point de vue personnel, je trouve l'implémentation de `topbar.py` horrible mais ce n'est que mon avis personnel.

**Comment by Situphen** [comment]
Le bug  l'air cloisonné à la preprod vu qu'il n'est pas présent en prod.

**Comment by Eskimon** [comment]
La version en prod' étant plus récente que ce ticket et fonctionnant correctement je considère que c'est fermable...
