### ISSUE TITLE
Revoir l'ordre des tutoriels qui ont besoin d'aide

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2872]
Récemment, j'ai commencé la rédaction d'un tutoriel sur Zeste de Savoir et j'ai mentionné que j'avais besoin d'un illustrateur pour l'icône de mon tutoriel. Une fois mon tutoriel créé, j'ai quand même été vérifié dans la liste des tutoriels qui ont besoin d'aide et je m'aperçois que le miens ne figurait pas dans la liste, ou plutôt c'est ce que je me suis dis.

En fait, mon tutoriel est bien dans la liste mais il ne figure pas dans les premiers de la liste. J'ai l'impression que les premiers tutoriels sont les tutoriels qui ont le plus de besoins. Selon moi, ce n'est pas logique et ça pose 2 problèmes :
1. Un effet pervers pourrait être que n'importe quel auteur peut spécifier qu'il a besoin de toutes les aides pour s'assurer d'être en haut de la liste.
2. Des tutoriels pourraient rester en haut de la liste pendant des mois s'ils ne trouvent pas d'aide alors que d'autres tutoriels pourraient avoir d'aide.

Je m'attends donc à avoir un ordre chronologique plutôt qu'un ordre en fonction des besoins. Les filtres sont là pour les besoins justement.

Qu'est ce que vous en pensez ?

**Comment by Eskimon** [comment]
C'est pas con du tout. Ca fait longtemps on s'était dit qu'il fallait revoir l'ordre d'affichage, mais je sais plus si on était revenu un peu dessus ou pas...

**Comment by Karnaj** [comment]
Il faut rajouter `order_by('update_date')` [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_contents.py#L1528), non ?

**Comment by pierre-24** [comment]
Oui. Ceci dit, une réflexion plus globale à ce sujet [à lieu ici](https://zestedesavoir.com/forums/sujet/4967/zep-03b-page-resumant-les-tutos-en-redaction-amelioration/) :)

**Comment by Karnaj** [comment]
Ok. On attend que cette ZEP soit validée ou on applique cette solution en attendant ?

**Comment by pierre-24** [comment]
Moi, ça m'est égal. Qu'en dise @vhf et @GerardPaligot ?

**Comment by vhf** [comment]
Je suis en faveur de toute refactorisation de [ceci](https://github.com/zestedesavoir/zds-site/blob/5e5bd2a7262aed0b0d79ec03308db51c73a83de9/zds/tutorialv2/views/views_contents.py#L1513), et si la personne qui s'en charge rajoute l'`order_by` en question, ça me va.

Au programme : Renommer la classe. Corriger le commentaire. Enlever les if/else if avec des strings magiques hardcodées.

Idem [ici](https://github.com/zestedesavoir/zds-site/blob/5e5bd2a7262aed0b0d79ec03308db51c73a83de9/zds/utils/models.py#L324), refactorer ça dans la même PR svp. Correcteur, illustrateur, repreneur ne sont pas des aides à la rédaction. Aussi y'a probablement une bonne raison mais je la connais pas, pourquoi cette classe est dans `utils` ?

**Comment by pierre-24** [comment]
Même si tu as raison, je pense qu'il y a des manières plus sympa de le dire. Bref.

> Renommer la classe

et 

> Correcteur, illustrateur, repreneur ne sont pas des aides à la rédaction

Je t'avoue que ... Si. Définitivement, un correcteur est une aide à la rédaction (et je sais de quoi je parle), un illustrateur encore plus, à la limite àa se discute pour reprenneur. La page [ZEP-03](https://zestedesavoir.com/forums/sujet/666/zep-03-page-resumant-les-tutos-en-redaction/?) mentionnait à plusieurs endroit le terme "aide" (et le code est donc infesté de _help_ dans tout les coins, ça a été pensé comme ça). Sincèrement, je vois pas quel mot irai mieux, et quand bien même ... Le nom `HelpWriting` est assez explicite pour qu'on comprenne ce que c'est. 

> Corriger le commentaire.

J'imagine que c'est en rapport avec ce qu'il y a au dessus, mais si c'est la phrase en elle même, j'ai pas compris ce que tu ne comprenais pas dans la phrase (et tu peux pas dire ça sans dire ce qui te dérange).

> lever les if/else if avec des strings magiques hardcodées.

Là, on est d'accord.

> Aussi y'a probablement une bonne raison mais je la connais pas, pourquoi cette classe est dans utils ?

Probablement pour la même raison que `Tag` y es, parce qu'elle est appelée à plusieurs endroits.  Parfois, c'est aussi pour éviter les imports cycliques (c'est par exemple pour ça que la plupart des fonctions de [ce fichier](https://github.com/zestedesavoir/zds-site/blob/5e5bd2a7262aed0b0d79ec03308db51c73a83de9/zds/tutorialv2/utils.py) font les `import` directement dans la fonction, alors que je suis pas sur que ce soit une bonne pratique). La raison étant probablement aussi "c'était là, on l'as laissé là".

**Comment by GerardPaligot** [comment]
Dans la mesure où un ticket a été créé pour le refactor, @Karnaj tu peux te contenter de changer la query et de la tester pour cette issue. Si tu veux prendre l'issue bien entendu ... (:

**Comment by Karnaj** [comment]
Je veux bien m’en charger. :)

**Comment by pierre-24** [comment]
Pour `oder_by()`, c'est fait ;)
