### ISSUE TITLE
[beta] Problème de mise en forme dans le texte du MP de changement de groupe

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2875]
Lorsque l'on modifie le groupe d'un membre via l'interface de promotion (en enlevant des groupes), le texte reçu par MP est mal formé. Celui que j'ai reçu ressemblait à celui-ci

> Bonjour fooooo,
> 
> Un administrateur vient de modifier les groupes auxquels vous appartenez.  
> * Vous ne faites partie d'aucun groupe

On voit l'étoile au lieu de voir la puce. Il manque donc un espace quelque part dans une template markdown.

**Comment by Situphen** [comment]
Ça se passe [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/views.py#L1030)

**Comment by Eskimon** [comment]
Je viens de test sur ma version local et tout marche correctement pour ma part

![capture du 2015-09-27 15 02 39](https://cloud.githubusercontent.com/assets/761168/10122906/ec628b10-6528-11e5-8c97-0600580c4751.png)
