### ISSUE TITLE
Rendre plus accessible les tutoriels qui ont besoin d'aide

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2876]
Aujourd'hui, pour voir la liste des tutoriels qui ont besoin d'aide, nous sommes obligé de se rendre sur la liste des tutoriels, puis de cliquer sur "Aider les auteurs" pour afficher la liste des tutoriels qui ont besoin d'aide.

Hormis le nom du lien "Aider les auteurs" que je trouve très mal choisis parce qu'on s'attends pas forcément à une liste de tutoriels, c'est juste horrible de se rendre sur cette page même quand on est motivé pour y aller. Je n'imagine même pas quand on pense pas forcément à s'y rendre.

PS : Je sais que c'est un problème connu mais aucune issue ne concernait ce problème.

**Comment by Emeric54** [comment]
Oui, et c'est bien gênant. Je suis persuadé que cette page pourrait être beaucoup plus utilisée, notamment si elle gagnait en visibilité.

Je crois que @sandhose et/ou @Situphen avaient des idées pour ça, mais je ne sais plus exactement quoi. Vous vous en souvenez ?

**Comment by Emeric54** [comment]
L'issue #1921 pourrait résoudre ce problème.

**Comment by GerardPaligot** [comment]
Je pense qu'une plus grande réflexion doit être faite que l'issue #1921

**Comment by GerardPaligot** [comment]
Je ferme ici. Elle fait doublons avec #1921 qui liste déjà les sujets des forums de ZdS pour montrer que c'est demandé.
