### ISSUE TITLE
[beta] Problème d'affichage au survol de mes tutoriels

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2879]
Lorsque je passe la souris sur un de mes tutoriels en cours d'écriture dans la liste des tutoriels, j'ai un affichage `None` qui n'a pas de sens (cf. capture).

![why-o-why](https://cloud.githubusercontent.com/assets/6066015/8473613/487c1104-20ab-11e5-9231-40c77bddbb61.png)

J'en déduis qu'on tient une regression là aussi.

**Comment by artragis** [comment]
il semblerait que la "pubdate" ne soit pas forcément mise, ce qui génère un `None` [ici](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorial/includes/tutorial_item.part.html#L25)

**Comment by firm1** [comment]
> il semblerait que la "pubdate" ne soit pas forcément mise

Ce qui est normal puisque mes tutoriels n'étaient pas publiés

**Comment by artragis** [comment]
Je n'en sais pas plus.
