### ISSUE TITLE
La licence n'est pas conservée à l'édition d'un tutoriel

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2881]
Scénario :
1. Création d'un tutoriel avec une licence donnée (par exemple, CC BY-NC-SA).
2. Editez ce même tutoriel et constatez qu'il positionne la licence sur CC BY.
3. Constatez que si vous validez votre édition sans toucher à la licence, elle est positionnée à CC BY.

Un changement de licence est donc super vite arrivé.

cc @artragis et @pierre-24 pour savoir si c'est corrigé dans la ZEP-12.

**Comment by firm1** [comment]
Le bug est connu et déjà fixé dans la prochaine release.

Le jeu. 2 juil. 2015 17:52, Gérard Paligot notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
Effectivement, je viens de tester en bêta. Je ferme.
