### ISSUE TITLE
Mauvaise qualité des icônes d'un tutoriel

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2882]
Sur l'un de mes tutoriels, je lui ai ajouté une icône. Cette icône est plutôt grande puisqu'elle fait 128x128. Ce qui semble largement suffisant au vue de l'espace prévu sur Zeste de Savoir.

Cependant, une diminution de la qualité se fait nettement ressentir et l'icône n'est alors plus aussi jolie. Je trouve ce bug assez gênant parce que Zeste de Savoir n'est déjà pas très axé sur le visuel mais si en plus, on réduit fortement la qualité de petites images, cela devient très difficile d'avoir quelque chose de jolie.

PS : Vous pouvez retrouvé le rendu de l'icône sur ma liste des tutos en bêta actuel via [ce lien](https://zestedesavoir.com/membres/tutoriels/?type=beta&sort=abc) sur le tuto Intégrer un menu latéral en Material Design.

PS 2 : Je ne sais pas si c'est du front ou un traitement back, je ne mentionne donc rien.

**Comment by Situphen** [comment]
> PS 2 : Je ne sais pas si c'est du front ou un traitement back, je ne mentionne donc rien.

Je ne vois pas comment ça pourrait être du Front. De plus, le Back transforme les images en JPEG et les réduits donc ça doit venir de la bibliothèque qui gère ça !

[Ce n'est pas la première fois que c'est reporté](https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=28#p48794) et je trouve que c'est vraiment dommage cette perte de qualité ! Personnellement, sur mes tutoriels je met la version PNG et pas JPEG (j'enlève le `.960x960_q85.jpg` de `f4182b67-c605-4f2f-a0a3-7e8dbd4c502f.png.960x960_q85.jpg`).

**Comment by artragis** [comment]
Je pense avoir trouvé une piste : il faudrait sûrement passer un paramètre supplémentaire à notre thumbnailfield.

Voilà il semblerait que ça soit, dans la classe Image : 

``` python
physical = ThumbnailerImageField(upload_to=image_path, max_length=200, resize_source={"quality": 100})
```

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé

**Comment by GerardPaligot** [comment]
Cette issue est embarquée dans la v14 et la qualité de l'image ZdS sur le [dernier article](https://zestedesavoir.com/articles/978/zeste-de-savoir-passe-en-version-14-et-complete-lapi-avec-les-mp/) est dégueulasse. Je re-ouvre le ticket.

**Comment by gustavi** [comment]
C'est juste parce que l'image en question est dégueulasse. Je fais une màj de cette image ainsi que sur les anciens articles avec la fameuse image.
