### ISSUE TITLE
La progression des chapitres n'inclut pas les sommaires des parties 

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2883]
[Reporté par Dominus Carnufex sur le forum](https://zestedesavoir.com/forums/sujet/3545/la-progression-des-chapitres-ninclut-pas-les-sommaires-des-parties/) :

> En haut et en bas d'un chapitre de big-tuto, il y a un bandeau de navigation qui permet d'aller au chapitre précédent ou au chapitre suivant. Seulement, lorsqu'on est sur le dernier chapitre d'une partie, le lien « Suivant » pointe vers le premier chapitre de la partie suivante, et vice-versa, passant sous silence le sommaire de ladite partie suivante.

**Comment by pierre-24** [comment]
Et après plus d'un an, c'est fait :)
