### ISSUE TITLE
La recherche sur le contenu ne fonctionne plus

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2885]
En prod.

Url incriminée : http://zestedesavoir.com/rechercher/?q=android&models=article.article&models=tutorial.chapter&models=tutorial.extract&models=tutorial.part&models=tutorial.tutorial

Explication : Je recherche "android" dans les tutoriels, articles, parties, et/ou chapitres. Et je n'obtiens aucun résultat.

Il semblerait donc que la recherche dans le contenu ne fonctionne plus ce qui rend la barre de recherche de la nouvelle page, presque inutile. :(

J'hésite à le tagguer en bloquant.

**Comment by pierre-24** [comment]
@DevHugo ?

**Comment by DevHugo** [comment]
Faut tester en local et voir si ça marche.

**Comment by DevHugo** [comment]
Je sais pourquoi c'est la dernière PR. Je voulais pas la faire au dernier moment sans tester en preprod. Reverse la dernière PR et ça sera bon.

**Comment by pierre-24** [comment]
Arf :p 

... Y'a pas moyen de faire plus "subtil" ? J'veux dire, si tu _revert_ ce que t'as fait, tu réintroduit un bug (certes, pas méchant).

**Comment by DevHugo** [comment]
Il est pas dérangeant en tous cas moins que celui aujourd'hui

**Comment by DevHugo** [comment]
Le fix si vous voulez pas, faire le revert QUE JE CONSEILLE FORTEMENT ! Je pense qu'on a eu la preuve que le code mergé sans tests sur la préprod + du code pas testé unitairement, ça marche pas.

**Comment by DevHugo** [comment]
On peut fermer du coup

**Comment by pierre-24** [comment]
On peut. J'ai testé, [ce sujet](https://zestedesavoir.com/forums/sujet/3629/conseils-pour-un-projet-domotique/), qui a été créé il y a deux heure au moment ou je poste ce message, est toujours bien indexé et les tutos/articles le sont jusque ici. J'espère qu'on est bon :)
