### ISSUE TITLE
Urgent : Certificat HTTPS expiré

### ISSUE THREAD

**Issue by Augustin-FL** [zestedesavoir/zds-site#2886]
Le certificat HTTPS de ZDS était valide du 1er juillet 2014 au 3 juillet 2015. 

Le bug a été reporté dans [un sujet du forum](http://zestedesavoir.com/forums/sujet/3562/certificat-de-securite-expire/)

**Comment by pierre-24** [comment]
Ping @Un-Cornichon ?

**Comment by WinXaito** [comment]
Je confirme que c'est asser bloquant et urgent ça ..

**Comment by SpaceFox** [comment]
[L'explication ici](http://zestedesavoir.com/forums/sujet/3429/la-release-v156/?page=5#p64433).

**Comment by artragis** [comment]
C'est bon maintenant, non?

**Comment by Augustin-FL** [comment]
Oui. enfin pas complètement, mais ce n'est plus la même issue : 

(ne tenez pas compte du nom chelou du certificat, cela vient du fait que j'utilise avast)

![](https://cloud.githubusercontent.com/assets/9406403/8542070/1f9fdf54-2493-11e5-868e-5d6efe9cb181.jpg)

**Comment by SpaceFox** [comment]
[zestedesavoir.com obtient un grade A+](https://www.ssllabs.com/ssltest/analyze.html?d=zestedesavoir.com&latest), je crois qu'on ne pourra pas faire mieux.

Concernant les ressources non sécurisées, on a pas le choix : on a des ressources externes (avatars, images, ...) qui ne sont pas gérés par nous et pas forcément accessibles en HTTPS (mon avatar par exemple, ne le sera probablement jamais).

Donc ce n'est pas un bug, c'est un comportement auquel on a aucune solution simple (et même les solutions complexes posent tout un tas de problèmes plus importants que cet avertissement).
