### ISSUE TITLE
[v15.6]Certaines ressources sont chargées en http

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#2888]
Les ressources des unes sont chargées en http et ce même si on est en https.

**Comment by SpaceFox** [comment]
Ca c'est facile, il suffit de mettre du protocol-relative ou de forcer le HTTPS (du HTTPS dans du HTTP ne pose pas de problème).

Je m'en occupe après avoir rétabli le HTTPS.

**Comment by SpaceFox** [comment]
C'est corrigé, il faudra juste que l'équipe comm' fasse attention à mettre des liens protocol-relative.

Par contre, on ne peut rien faire pour les ressources externes (avatars par exemple).

**Comment by artragis** [comment]
Ok. Merci.

façon si les avatar sont issus de ressources externes c'est pas une 
faille en soit.

**Comment by artragis** [comment]
Apparemment les équipes de com' n'ont toujours pas le réflexe de mettre du protocol relative, du coup on a encore une ressource en http lorsqu'on charge la une sur la nouvelle page d'accueil. faudrait presque faire un re.sub(r"http://(www.){0,1}zestedesavoir.[a-z]{2,3}", "", featured_image_path)

**Comment by SpaceFox** [comment]
Parce qu'en fait l'interface demande une URL, et que si tu mets du protocol relative elle refuse l'enregistrement... il y a un vrai dev à faire, là.

**Comment by artragis** [comment]
ok
Donc faut forcer https

**Comment by Situphen** [comment]
Est-ce qu'on a vraiment besoin de vérifier que c'est une URL valide ? La prévisualisation en direct suffit pour voir si ça fonctionne, non ?

**Comment by Eskimon** [comment]
plop pour résumer il faut faire quoi ? Du dev ou former les gars de la com' ?

**Comment by pierre-24** [comment]
Y'a moyen de faire du dev' en mettant [un validateur](https://docs.djangoproject.com/en/1.8/ref/forms/validation/#using-validators), et en utilisant [un `UrlValidator()`](https://docs.djangoproject.com/en/1.8/ref/validators/#urlvalidator) dont on aurait modifié le `schemes` pour ne lui faire contenir que `https` :)

(mais on peut de toute façon "former" les gars de la com' d'ici là)

**Comment by artragis** [comment]
je suis pour faire un petit dev.

**Comment by artragis** [comment]
Non, c'est un poil plus complexe que ça :

le https ne doit être forcé QUE sur les urls qui pointent vers zds or 
aujourd'hui je peux faire une url vers un autre site (par exemple si 
l'interview de zds sur Graine d'Utopie, on va les envoyer chez eux).
Donc il faut que ton validation fasse quelque chose genre :

``` python
if ZDS_APP['base_name'] in url and url.startswith("http:") :
     url = url.replace('http:', 'https:')
```

**Comment by pierre-24** [comment]
OK, ici on est bon :)

**Comment by gustavi** [comment]
Ça ne semble pas entièrement fixé (cf pages de mp).

D'ailleurs pourquoi le [v15.6] ?

**Comment by artragis** [comment]
en fait c'est fixé sur les featured MAIS pour une raison que j'ignore :
- l'avatar est toujours en http
- par défaut le code d'insertion des galleries prend du http

2015-12-10 13:31 GMT+01:00 Laville Augustin notifications@github.com:

**Comment by gustavi** [comment]
Donc je ré-ouvre.

**Comment by SpaceFox** [comment]
> l'avatar est toujours en http

Attention, certains avatars sont sur des sites externes et donc **ne peuvent pas** être chargés en HTTPS…

**Comment by gustavi** [comment]
Le problème ce sont les membres qui utilisent une image sur ZdS et qui utilisent du http. Faudrait forcer le https.

**Comment by artragis** [comment]
Oui mais ça OSEF car ça dérange pas la sécurisation de NOTRE connexion.
les avatar qui doivent être traités sont ceux de zds.
