### ISSUE TITLE
"No module named crispy_forms_foundation"

### ISSUE THREAD

**Issue by Ge0** [zestedesavoir/zds-site#289]
Après tentative de redéploiement de ZesteDeSavoir, voici ce qu'on obtient après avoir réinstallé les "requirements" :

``` console
ge0@kosmik ~/ZesteDeSavoir (dev)$ python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 69, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/south/management/commands/__init__.py", line 10, in <module>
    import django.template.loaders.app_directories
  File "/usr/lib/python2.7/dist-packages/django/template/loaders/app_directories.py", line 23, in <module>
    raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
django.core.exceptions.ImproperlyConfigured: ImportError crispy_forms_foundation: No module named crispy_forms_foundation
```

N.B. : J'ai bien fait l'installation en "root", tout s'est installé sans souci, mais la commande pour le "syncb" plante. Une idée ?

**Comment by firm1** [comment]
Deux petites questions : 
- tu utilises virtualenv ?
- si non, peux-tu me donner le résultat de la commande `pip freeze` ?

**Comment by cgabard** [comment]
@firm1 : crispy-forms-foundation est il encore necessaire ? Si non, faut le virer du requierements.txt

@Ge0 : si tu as fais `pip install --user -r requirements.txt` en root, ça peut se comprendre. le flag `--user` dit d'installer les packages a l'utilisateur courant. Si tu as connecté en tant que root, il va les mettre dans son home a lui. Et donc pas accessible aux autres. De là 3 solutions : 
- tu fais une instal propre avec virtualenv
- tu refais la commande, en root, sans le `--user` si tu n'a pas peur pour ton système (car les packages vont remplacer ceux de ta distrib)
- tu fais l'install avec le `--user` sans être logué root.

Sinon, tu es sur quelle distrib ?

**Comment by cgabard** [comment]
@firm1 : [crispy-forms-foundation est encore utilisé dans 4 fichiers](https://github.com/Taluu/ZesteDeSavoir/search?q=crispy_forms_foundation&ref=cmdform&type=Code)

**Comment by Ge0** [comment]
@cgabard je suis sous Debian

Merci pour vos retours

**Comment by firm1** [comment]
C'est bizarre, j'ai fais une descente sur la preprod (une debian) et elle passe bien sans souci.

Du coup, peux-tu donner le résultat de `pip freeze` ? pour comparer avec la version de la preprod ?

**Comment by cgabard** [comment]
Je maintient : si il a installé avec le flag `--user` en tant que root, puis essais de lancer en tant qu'utilisateur, c'est tout a fait normal que les dépendances ne soient pas trouvées !

**Comment by firm1** [comment]
En effet et donc dans ce cas il faudrait tout désinstaller et réinstaller sans le flag `--user`. Donc je suppose : 
- `pip uninstall -r requirements.txt`
- `pip install -r requirements.txt`

Pour avoir un truc propre et fonctionnel.

**Comment by cgabard** [comment]
Si c'est ça, a la limite, c'est pas trop grave. il peut fouiller dans le home de root pour les virer.

Par contre pour l'installation il faut faire : 
- soit en root `pip install -r requirements.txt` ce qui va les installer au niveau système
- soit en tant qu'utilisateur normal `pip install --user -r requirements.txt` ce qui va les installer au niveau de son home.

**Comment by geoffreyc** [comment]
Je suis entrain de voir pour faire un script qui lance l'installation du
repo en un clique, mais django me sort ca:
ImportError: No module named six

A priori, six n'est pas dans le requirements.txt ?

2014-04-10 16:49 GMT+01:00 Christophe Gabard notifications@github.com:

**Comment by cgabard** [comment]
A priori, six est une dépendance de django, pas directement de notre projet. Et ils sont censés l'inclure directement puisqu'ils en ont une version "custom"... C'est donc assez etrange

**Comment by geoffreyc** [comment]
Je pense avoir comprit d'ou ça vient, si une exception est "raised"
(connais pas le mot francais?) pendant l'install pip de requirements.txt,
tout s'arrête (les autres lib ne s'installent pas) et ça passe a la
prochaine commande dans le script. En l'occurrence moi ca tribuche sur lxml.

2014-04-11 12:20 GMT+01:00 Christophe Gabard notifications@github.com:

**Comment by cgabard** [comment]
Ha ok :) et du coup, c'est quoi l'erreur avec lxml ? tu es sur windows ou linux ?

**Comment by geoffreyc** [comment]
Il se compilé pas, au final il me faillait:
apt-get install python-virtualenv
apt-get install libxml2-dev
apt-get install libxslt1-dev

Tout va bien maintenant :)

2014-04-11 12:30 GMT+01:00 Christophe Gabard notifications@github.com:

**Comment by firm1** [comment]
> Il se compilé pas

Pour lxml il vaut mieux l'installer avec easy_install (c'est comme ça que j'ai documenté sous windows) et ça permettra de rendre ton script plus extensible aux autres environnement linux (les apt-get c'est surtout pour des debian like)

**Comment by geoffreyc** [comment]
Ouai c'est ce que je vais faire ducoup.

Le script n'a aucune commande du type "apt-get" justement pour que ce soit
un poil portable, en partant du principe que la personne installe git et la
bonne version de python avant de faire tourner le script (je laisse aussi
le choix a la personne de faire tourner le script sous virtualenv ou pas,
ca marchera a coup sur sous virtualenv, peut etre moins sans).

2014-04-11 14:17 GMT+01:00 firm1 notifications@github.com:

**Comment by firm1** [comment]
Cette issue as t-elle encore lieu d'être ? Le bug reste non reproductible et on dirait plutot une erreur de manipulation plutôt qu'un vrai problème d'install.

Pense a fermer l'issue.

**Comment by Ge0** [comment]
Bonne idée, je la rouvrirai si le problème persiste.

Merci à vous tous.
