### ISSUE TITLE
La sidebar dans la recherche n'est pas correct

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2893]
Serveur : Prod
Version : v15.6-cedrat
Système : Android
Navigateur : Google Chrome

Scénario :
1. Connectez-vous à Zeste de Savoir sur votre mobile.
2. Rendez-vous sur la recherche.
3. Ouvrez la sidebar et constatez que les différents types de recherche ne sont pas disponibles.

![screenshot_2015-07-05-01-09-50](https://cloud.githubusercontent.com/assets/1913901/8518707/0d8e526c-23cd-11e5-9fc7-4b30c4d75130.png)

Notes :
1. Il ne devrait pas afficher les sujets suivis mais les différents types de recherche.
2. Le bug est rencontré aussi en mode non connecté.

**Comment by DevHugo** [comment]
C'est pas un doublon de https://github.com/zestedesavoir/zds-site/issues/2857 ?

**Comment by firm1** [comment]
C'est un doublon comme le mentione @DevHugo
