### ISSUE TITLE
Les Unes ne s'affichent pas correctement sur certains téléphones mobiles et navigateurs

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2897]
[Reporté via Twitter](https://twitter.com/A_Somme/status/617972243591745538), les Unes ne s'affichent pas correctement sur le Lumia 830 avec Internet Explorer 11 (elles devraient être centrées) :

![Image](https://pbs.twimg.com/media/CJN6enbWUAAbbuH.jpg:large)

**Comment by SpaceFox** [comment]
Si j'étais taquin, je dirais que selon nos stats, on a pratiquement aucune
visite IE11 :-°

**Comment by Situphen** [comment]
Ouais, mais c'est quand même la dernière version d'IE (enfin, je crois) donc si c'est simple à fixer je pense que ça vaut le coup ! :)

**Comment by SpaceFox** [comment]
Nop, c'est pas ça, c'est que IE11 se met en mode "pas de suivi" par défaut :)

**Comment by WinXaito** [comment]
Je confirme aussi le cas sur Lumia 625

**Comment by Augustin-FL** [comment]
en effet, @SpaceFox  a raison, c'est bien le navigateur qui fake son user agent et certaines données js par défaut. Voir [cette page](http://wmpoweruser.com/wp8-1-update-1s-ie-user-agent-pretends-to-be-android-4-0-and-ios-7-good-enough-to-fool-gmail/).

**Comment by GerardPaligot** [comment]
@WinXaito Si tu as toujours un Lumia, tu pourrais faire une capture pour récupérer le visuel du bug ?

**Comment by WinXaito** [comment]
Avec plaisir, je te donne ça tout de suite.

**Comment by WinXaito** [comment]
![wp_ss_20160717_0001](https://cloud.githubusercontent.com/assets/8223773/16902927/8bf51152-4c6e-11e6-8515-730ece562686.jpg)

Les images ne sont toujours pas centré.

**Comment by GerardPaligot** [comment]
Merci @WinXaito !

**Comment by nils-van-zuijlen** [comment]
@WinXaito Est-ce que le bug est toujours présent ?

**Comment by gllmc** [comment]
Sans doute, mais veut-on encore supporter IE ? Il me semble qu'on avait décidé d'abandonner son support.

**Comment by Augustin-FL** [comment]
Je vote pour fermer cette issue, vu que le support d'IE est abandonné

**Comment by Situphen** [comment]
Allons-y fermons ce ticket
