### ISSUE TITLE
La page d'accueil s'affiche très mal sur Opéra mobile

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2898]
[Reporté via Twitter](https://twitter.com/A_Somme/status/617986931922702336), la page d'accueil s'affiche très mal sur Windows Phone avec Opéra 8.0.4.73.

![Image](https://pbs.twimg.com/media/CJOH1rLWEAAu_gJ.jpg)

**Comment by GerardPaligot** [comment]
Who care? :-°

**Comment by Eskimon** [comment]
[D'après wikipédia](https://fr.wikipedia.org/wiki/Opera#Versions_pr.C3.A9-Chromium_.281996-2012.29) Opéra 8.0 date de 2005. Je vais donc me contenter de "LoL" et fermer ce ticket.
