### ISSUE TITLE
La bulle des commentaires superposée aux auteurs d'articles sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2899]
Navigateur : firefox
Os : Android

Dans la page de listing de tous les articles sur mobile, on constate que la bulle se superpose avec le nom de l'auteur. Alors que la meme bulle sur la page d'accueil a un decalage pour eviter ce probleme.

Screen : 

![6 juillet 2015 190645 gmt 0200](https://cloud.githubusercontent.com/assets/6066015/8528324/b390f332-2412-11e5-8d84-67109fe2ceec.jpg)

**Comment by pierre-24** [comment]
Hop :)
