### ISSUE TITLE
IP address information

### ISSUE THREAD

**Issue by Ge0** [zestedesavoir/zds-site#29]
En plus d'avoir notre IP remplacée par celle du serveur, il est aisément possible de la falsifier en spécifiant des en-têtes HTTP comme X-Forwarded-For (et peut-être d'autres).

Il serait intéressant, d'une part, de vérifier que l'IP transmise dans les en-têtes HTTP soit correcte (quatre numéros de 0 à 255, séparés par des points) et, d'autre part, de mémoriser les 2 IP (celle du "device" effectif ainsi que celle fournie par les en-têtes).

En effet, s'il s'agit d'un proxy dont le but premier est d'anonymiser la source, vous vous doutez bien qu'il n'y aura aucune indication de la véritable IP source dans les en-tête HTTP. Si l'information est présente, c'est peut-être parce que le membre se trouve derrière un proxy d'école / d'entreprise, mais dans la grande majorité des cas l'IP récupérée sera de classe privée (cf le cas de Shigerum avec son ip en 10.x...).

**Comment by SpaceFox** [comment]
> vérifier que l'IP transmise dans les en-têtes HTTP soit correcte (quatre
> numéros de 0 à 255, séparés par des points)

Ou un format d'IPv6 correct. Je ne sais pas si le serveur est accessible en
IPv6, mais je sais que par exemple je sors en IPv6 sur le net, donc s'il
l'est, je vais renvoyer une IPv6.

**Comment by firm1** [comment]
Le serveur n'est pas encore configuré au poil, mais il supporte l'IPv6.

@Ge0 : Merci pour l'explication, ce bug est classé 8e dans ma liste de taches. Du coup, si quelqu'un veut le corriger avant moi, la méthode à corriger c'est [celle-ci](https://github.com/Taluu/ZesteDeSavoir/blob/master/zds/forum/views.py#L640). Même pas besoin de démarrer django pour corriger le script.

**Comment by Ge0** [comment]
Oh, le code est en effet très clair et limpide. J'ai eu la chance de tester X-Forwarded-For à la place d'autres champs comme Client-Ip par exemple.

Je veux bien essayer de m'en occuper ! Ca me fera faire quelque chose...

**Comment by firm1** [comment]
> Je veux bien essayer de m'en occuper ! Ca me fera faire quelque chose...

Etant donné que mon niveau en adresses réseaux n'est pas au beau fixe, tu seras certainement plus efficace que moi sur ça.

**Comment by SpaceFox** [comment]
BTW pour continuer sur les IPv6 : je ne sais pas si on stocke les IPs, mais
si oui, il faut s'assurer que le champ prévu à cet effet est assez long
pour enregistrer de l'IPv6.

**Comment by Ge0** [comment]
@SpaceFox tout à fait, d'autant plus qu'une erreur est déclenchée quand l'IP dépasse 15 caractères.

Je me renseignerai quant au support des IPv6.

**Comment by firm1** [comment]
Est-ce vraiment utiles de stocker des IPv6 ? l'idée c'est d'utiliser ce champ pour la modération. Si on a deux types d'adresses (ipv4 et ipv6) dans le même champs, ça risque d'être un peu le bordayle non ?

**Comment by SpaceFox** [comment]
Ben c'est la vérité. Si le site est configuré correctement, le visiteur
peut arriver avec une IPv4 et une IPv6, donc tu n'as pas le choix.

Cela dit, c'est sans doute pas très urgent, les visiteurs en IPv6 risquent
d'être principalement moi-même depuis chez moi et quelques geeks. Il faut
juste s'assurer que ça ne crashe rien - surtout vu le public visé.

**Comment by Ge0** [comment]
Je ne sais pas encore, j'ai très peu étudié l'essort de l'IPv6 mais je suis sûr d'une chose : il faut anticiper...

**Comment by SpaceFox** [comment]
putain faut que je me relise moi.

Dans le message précédent :
- c'est la _réalité_ (pas vérité)
- le visiteur peut arriver avec une IPv4 _ou_ (et pas et) une IPv6

**Comment by Ge0** [comment]
Je pense tout de même qu'on a compris l'idée @SpaceFox (enfin moi j'avais compris pour le "ou" tout du moins).

**Comment by firm1** [comment]
Mdr spacefox.

Ok, c'est noté.

@Ge0 : je vais repousser la limite des 15 chars réservé à ce champs et tu t'occupe de nous peaufiner cette méthode pour recupérer la vraie ip (4 ou 6) ?

**Comment by Ge0** [comment]
@dralliw c'est ça :)

**Comment by Coy0te** [comment]
À part la gestion des IP longues à rajouter (IPv6), a priori y'a rien à corriger dans la méthode, elle est supposée fonctionner dans les cas "normaux".

En fait j'ai pas compris : 
- quel est l'intérêt de stocker plusieurs IP ?
- quel est l'intérêt de vérifier le contenu du champ ?

Si quelqu'un veut spoofer, il va spoofer, peu importe que les données qu'il entre soient semblables à des adresses IP ou du gros n'importe quoi. Donc autant garder une méthode simple et légère qui va fonctionner dans 99,9% des cas (ce qui est le cas de le méthode actuelle). 

Le reste, j'ai envie de dire si on voit qu'un type écrit "fuck zds" dans une en-tête HTTP, on pourra se contenter de bannir son compte.

P.S : le problème des IP foireuses qu'on rencontre actuellement sur zestedesavoir.com, c'est à cause de la conf de nginx et de son reverse proxy, c'est pas un souci au niveau de la méthode.

**Comment by Ge0** [comment]
> quel est l'intérêt de stocker plusieurs IP ?
> A vue d'oeil je dirais que ça sert à fliquer.
> 
> quel est l'intérêt de vérifier le contenu du champ ?
> Pour vérifier qu'il s'agit d'une IP valide.
> 
> Si quelqu'un veut spoofer, il va spoofer, peu importe que les données qu'il entre soient semblables à des adresses IP ou du gros n'importe quoi. Donc autant garder une méthode simple et légère qui va fonctionner dans 99,9% des cas (ce qui est le cas de le méthode actuelle). 

Le spoofing IP ne fonctionne pas sur un "WAN". C'est surtout valable dans un réseau local. Ici on parle de méthodes qui permettent d'obtenir une IP différente de ton propre poste de travail. Et le code en vigueur permettrait de récupérer l'IP _véritable_ de la source (tu n'as qu'à voir l'IP qui a été assignée par Shigerum).

Si mes souvenirs sont bons, sur la v3 on listait les IP "REMOTE_ADDR" et les IP pseudo-véritables, celles qu'on récupérait dans un champ HTTP. 

> Le reste, j'ai envie de dire si on voit qu'un type écrit "fuck zds" dans une en-tête HTTP, on pourra se contenter de bannir son compte.

.... Oui ? Commencer par loguer peut-être ! :)

**Comment by firm1** [comment]
Après avoir configuré le reverse DNS de nginx le code marche désormais pour les ipv4. Avec en bonus la géolocalisation par ip dans le profil du membre.

**Comment by Coy0te** [comment]
@firm1 : petite régression, c'est à nouveau l'IP du serveur qui est récupérée et affichée.

**Comment by firm1** [comment]
> petite régression, c'est à nouveau l'IP du serveur qui est récupérée et affichée.

Oui, oui [c'est une regression connue](https://github.com/Taluu/ZesteDeSavoir/commit/99a8f3fcc6cc30e7647dffdfca0b7c76ce78411c#commitcomment-4999875).

**Comment by Coy0te** [comment]
Mince, pas vu. Comment on peut suivre/être averti ce genre de discussions internes ?

**Comment by firm1** [comment]
Bah moi je reçois systématiquement un mail pour toutes les conneries quel l'on se dit.
