### ISSUE TITLE
Organisation des templates

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#290]
De retour dans le code, je me rend compte qu'il y a _énormément_ de templates.

J'en arrive donc à la question suivante : ne faudrait-il pas créer un niveau de dossier supplémentaire et mieux nommer les fichiers (vu qu'il seront dans des dossiers) ?

J'ai pour habitude de procéder en 3 niveaux :
- /
- /module
- /module/action

Pour les tutoriels par exemple on pourrait avoir :
- /base.html (comme actuellement)
- /tutorials
  - /base.html (commun à toutes les pages tutoriel côté client
  - /base_admin.html (commun aux pages d'admin)
- /tutorials/validation
  - /base.html
  - /index.html
  - ...

Par ailleurs, je ne comprends pas l'utilité de plein de fichier, notamment dans le dossier tutorials. Il y a des fichiers qui ont l'air de copié/collés non achevés :/

Il y a à mon avis un gros refactoring à faire de ce côté là.

Enfin, il serait bien de factoriser au maximum les templates, j'ai croisé des gros blocs copié/collé pour un nom de variable qui change dans un cas ou un autre.

**Comment by cgabard** [comment]
> Il y a à mon avis un gros refactoring à faire de ce côté là.

Probablement, je n'y ai jamais touché. C'est la personne qui aura le courage de le faire qui decidera. Concernant l'organisation, je m'en fout totalement personnellement et je considère que c'est la personne qui va se charger de les maintenir/developper de s'organiser. Donc si tu t'en occupe, fais comme ça t'arrange.

**Comment by firm1** [comment]
> Pour les tutoriels par exemple on pourrait avoir : [...] /base_admin.html (commun aux pages d'admin)

Actuellement on gère la différence entre un admin et un membre normal dans le code avec une simple conditions. Si on procède selon le découpage que tu propose, on risque d'avoir une autre base_membre.html pour tous les membres inscrit mais pas admin. En gros, on fragmente pour un intéret pas forcément utile.

> Il y a à mon avis un gros refactoring à faire de ce côté là.

Je suis de l'avis de Christophe là. Celui qui s'en occupe le conçoit comme il veut.

NB : globalement la structure de templates actuelle est la suivante : 

![flux template](https://cloud.githubusercontent.com/assets/6066015/2669001/1c208dae-c0be-11e3-8c05-3c28e90acdf2.png)

**Comment by Alex-D** [comment]
Rien n'empêche d'étendre la base du niveau supérieur si le besoin n'existe pas.

**Comment by Alex-D** [comment]
Voilà donc sur la branche intégration les templates sont réorganisées, nettoyées et il ne reste "plus qu'à" merger avec la branche de la beta...

**Comment by Alex-D** [comment]
Le merge est terminé dans le commit suivant : https://github.com/Taluu/ZesteDeSavoir/commit/4e2ff5700ec552683ee86b9e19213bf89d86b175
