### ISSUE TITLE
L'affichage des pseudos dans la liste des tutoriels / article déconne

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2900]
L'affichage du pseudo "Bat'" n'est pas correct.

![bug](https://cloud.githubusercontent.com/assets/6099338/8538835/07cccad8-2473-11e5-8849-c645a0c34875.png)

Possible de voir le comportement sur la page: https://zestedesavoir.com/tutoriels/?tag=dot-net

**Comment by yapper-git** [comment]
Je viens de regarder, cela vient du tag _captureas_ définit dans `zds/utils/templatetags/captureas.py`.

La définition de la fonction render est la suivante:

``` python
    def render(self, context):
        """
        Render the node list to the variable name.

        :param context: Current context.
        :return: Empty string
        :rtype: str
        """
        output = self.__node_list.render(context)
        context[self.__variable_name] = output.strip()
        return ''
```

Or `output` est une chaîne de caractère _safe_ (de type `django.utils.safestring.SafeText`). Or l'ajout de .strip() transforme la chaîne et son nouveau type devient `unicode` ! Ainsi le code reçu est échappé automatiquement puis à nouveau du fait que la chaîne ne soit pas sûre (_safe_).

Voilà donc je propose d'ajouter un appel à mark_safe (ou virer le strip).
Voici le patch pour l'ajout de mark_safe.

``` patch
ddiff --git a/zds/utils/templatetags/captureas.py b/zds/utils/templatetags/captureas.py
index d9d0aa1..4d1db59 100644
--- a/zds/utils/templatetags/captureas.py
+++ b/zds/utils/templatetags/captureas.py
@@ -1,6 +1,7 @@
 # -*- coding: utf-8 -*-

 from django import template
+from django.utils.safestring import mark_safe

 register = template.Library()

@@ -54,5 +55,5 @@ class CaptureasNode(template.Node):
         :rtype: str
         """
         output = self.__node_list.render(context)
-        context[self.__variable_name] = output.strip()
+        context[self.__variable_name] = mark_safe(output.strip())
         return ''
```

J'ai testé cela fonctionne. Je peux proposer une PR basique pour corriger le bug si vous voulez ! Dites-le moi.

**Comment by DevHugo** [comment]
Je pense que tu as raison, bien vu. Tu peux proposer une PR, si tu veux sinon quelqu'un le fera.

**Comment by yapper-git** [comment]
Je vais la faire dans un instant alors ;)
