### ISSUE TITLE
Tous les sujets sont marqué comme lu

### ISSUE THREAD

**Issue by La-source** [zestedesavoir/zds-site#2901]
Bonjour,

Je suis face à un bug très gênant... depuis la publication de la nouvelle version, hormis les sujets suivi où je vois lorsqu'il y a une nouvelle réponse. Tous les autres sujet me sont affiché comme lu alors que ce n'est clairement pas le cas. Il y a des forums où je ne mes clairement jamais les pieds et même là bas tous es marqué comme lu.

**Comment by artragis** [comment]
Connu via #2873 corrigé par #2889 et sera sûrement envoyé en prod quand #2891 sera prêt.

**Comment by La-source** [comment]
D'accord... le titre de l'autre sujet était pas super clair du coup je m'étais dis que c'était pas sa ><'
