### ISSUE TITLE
Impossible de rechercher certainnes informations au delà de la première page

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2902]
**Scénario 1:**
- Aller sur la page de recherche : `http://zestedesavoir.com/rechercher/`
- Saisir dans la zone de recherche : `&ab`
- Constatez qu'il y'a des résultats sur plusieurs pages
- Cliquer sur suivant
- **Pouf : une erreur 404**

**Scénario 2:**
- Aller sur la page de recherche : `http://zestedesavoir.com/rechercher/`
- Saisir dans la zone de recherche : `#1`
- Constatez qu'il y'a des résultats sur plusieurs pages
- Cliquer sur suivant
- **Pouf : le vide s'empare de nous**

**Comment by pierre-24** [comment]
@DevHugo ? :)

**Comment by DevHugo** [comment]
Il passe des trucs chelou des les url sans ça, ça fonctionne, c'est pas ma top priorité, je t'avoue.
