### ISSUE TITLE
Le menu de gauche sur mobile presente une zone de sujets suivis vide

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2903]
Lorsque je vais sur la page de recherche, sur le mznu de gauche il y'a une zone "sujets suivis" qui n'a rien a y faire.

Screen:
![7 juillet 2015 174342 gmt 0200](https://cloud.githubusercontent.com/assets/6066015/8550297/1014378c-24d0-11e5-80fb-9c3b2268a64f.jpg)

**Comment by Luuka** [comment]
J'en ai parlé brièvement ici : #2857

`Sujets suivis` est une erreur, c'est l'attribut `data-title` [ici](https://github.com/zestedesavoir/zds-site/blob/dev/templates/search/search.html#L42) qui est faux et c'est lui qui est utilisé pour créer les titres dans le menu.

Cette partie est en réalité censée contenir les critères de recherches sauf que la fonction [appendToSidebar](https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/mobile-menu.js#L165) ne gère pas l'import des listes à puces du corps de la page vers le menu.

**Comment by Situphen** [comment]
Pour moi c'est effectivement un doublon de #2857
