### ISSUE TITLE
Question : qu'est-ce qui a été fait sur la v15.6 en terme de performances ?

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2904]
Je viens de voir que la page d'accueil affiche, pour un article :

> par vous, Eskimon et Situphen

Or, il me semblait qu'on avait fait sauter la détection du "vous" pour des raisons de performances.

Est-ce qu'on est sûr que nos améliorations ont bien été mergées dans la version qui est en prod aujourd'hui ?

**Comment by Situphen** [comment]
Non, si je me souviens bien on l'avait fait sauté lors de la mise en place du cache (car sinon ça aurait été trop compliqué) mais du coup on a du le remettre lorsqu'on a enlevé le cache !

Franchement, ça ne doit pas affecter grand chose en terme de performances, c'est simplement [un `if` sur deux variables](https://github.com/zestedesavoir/zds-site/blob/dev/templates/article/includes/article_item.part.html#L15) !

**Comment by SpaceFox** [comment]
En fait ma question portait plus sur le fait qu'on ait pu annuler des
optimisations réelles suite à cet suppression du cache.

**Comment by Situphen** [comment]
> Franchement, ça ne doit pas affecter grand chose en terme de performances, c'est simplement [un `if` sur deux variables](https://github.com/zestedesavoir/zds-site/blob/dev/templates/article/includes/article_item.part.html#L15) !

**Comment by SpaceFox** [comment]
En général, pas sur ce point en particulier...

**Comment by Situphen** [comment]
A part peut-être [la suppression de `get_reaction_count`](https://github.com/zestedesavoir/zds-site/pull/2756/files#diff-0f648be912b8425368891940d2abe333R216), il n'y a pas eu d'améliorations autre que le cache, si ?

**Comment by SpaceFox** [comment]
Il n'y avait pas des tas d'améliorations sur les requêtes ?!

**Comment by Situphen** [comment]
Ça n'a pas été fait en même temps que le cache. Ça a été fait par #2785 !

**Comment by SpaceFox** [comment]
Mais c'est pas du tout ce que je dit !
Le post d'origine ne parle pas de cache et dit très explicitement :

> Question : qu'est-ce qui a été fait sur la v15.6 en terme de performances ?

Je ne comprend même pas comment on peut en arriver à ce débat !

**Comment by Situphen** [comment]
Je crois qu'il n'y a que #2785 et #2724 concernant tout le site. Il y en a sûrement quelques autres liées à la recherche et l'indexation qui ont du améliorer les performances aussi.

**Comment by artragis** [comment]
globalement, nous avons abaissé pas mal le nombre de requêtes quand il y a des "j'aime" ou des badges à afficher. Mes précalculs ne concernent que ce que j'ai pu remarquer durant la zep12, pas autre chose. Notre bottleneck se situe au niveau des notifications qui chargent énormément de choses en lazy et sans trop regarder ce qu'ils font.

**Comment by pierre-24** [comment]
A priori réglé ;)

**Comment by artragis** [comment]
non

**Comment by pierre-24** [comment]
ah :o

**Comment by Situphen** [comment]
Up ! Ça en est où ?

**Comment by Eskimon** [comment]
cette version date, ce ticket a encore raison d'être ?

**Comment by gustavi** [comment]
UP

**Comment by SpaceFox** [comment]
Plus de raison d'être ici.
