### ISSUE TITLE
Courriels lors d'une réponse à un message privé aux mauvaises personnes

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2905]
[Reporté via le forum :](https://zestedesavoir.com/forums/sujet/3578/alerte-email-message-prive/?page=1#p65005)

> Bon, on a fait quelques tests avec les compères, et l'explication qui semble se profiler, c'est que :
> - l'OP ne reçoit jamais de mail de notification ;
> - les autres reçoivent systématiquement un mail de notification, même pour leurs propres messages ;
> - le mail de notification attribue systématiquement le dernier message envoyé à l'OP.
> 
> La manière la plus économique de décrire le problème, et je pense la raison pour laquelle ça bogue, c'est que le module de ZdS chargé d'envoyer les notifs mail aux bonnes personnes considère systématiquement l'OP comme l'auteur du dernier message posté. Cela expliquerait le texte du mail, le fait que l'OP ne reçoive jamais (puisqu'il est censé l'avoir écrit) et que les autres reçoivent toujours (puisque c'est censé être l'OP qui a écrit). Je sais pas si je suis clair ?

**Comment by DevHugo** [comment]
C'est sur cette ligne, je pense https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/mps.py#L107.

On se demande qui a introduit le bug, hein, _part en sifflotant_.

**Comment by artragis** [comment]
on dirait que ça doit être fermé ça.

**Comment by artragis** [comment]
@Eskimon

**Comment by DevHugo** [comment]
Je crois que j'ai vu encore des soucis en prod ... à confirmer !

**Comment by Eskimon** [comment]
Yep j'ai pas l'impression que c'est corrigé non plus d'après les PR

**Comment by Berdes** [comment]
Je confirme : j'ai toujours le bug. En tout cas, je reçois un mail quand je réponds à un MP (et je ne suis pas l'OP). Je vais demander à l'OP s'il est sensé recevoir des mails de notification et s'il en reçoit réellement.

**Comment by DevHugo** [comment]
Le nom est bon dans le mail ?

**Comment by Berdes** [comment]
Dans le mail que je reçois (et comme dans le bug original), c'est le nom de l'OP qui apparaît comme expéditeur de ma réponse.

**Comment by Berdes** [comment]
L'OP viens de me dire qu'il n'est pas sensé recevoir de notification et qu'il n'en reçoit pas. Donc ça colle a priori au bug de base.

**Comment by DevHugo** [comment]
Ça le fait toujours ?

**Comment by firm1** [comment]
Toujours chez moi

Le sam. 31 oct. 2015 15:17, Hugo Courtecuisse notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
Cette issue devrait être corrigée par la ZEP-24, même déjà dans ma PR. Je la mentionne dans ma PR.

**Comment by gustavi** [comment]
Mergé dans ZEP-24.
