### ISSUE TITLE
Supprimer une galerie depuis la galerie 

### ISSUE THREAD

**Issue by Vayel** [zestedesavoir/zds-site#2909]
> Bonjour,
> 
> Actuellement, pour supprimer une galerie, il faut se rendre sur la page des galeries, cocher celle à supprimer et remonter tout en haut pour le faire. Ce serait chouette d'avoir un bouton "Supprimer la galerie" dans la galerie elle-même.
> 
> Merci.

https://zestedesavoir.com/forums/sujet/3544/supprimer-une-galerie-depuis-la-galerie/

**Comment by gustavi** [comment]
Corrigé dans #3216.
