### ISSUE TITLE
Tutoriels : boutton pour revenir au sommaire

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2910]
Par [Halarp27](https://zestedesavoir.com/membres/voir/Halarp27/):

> Bonjour, cela concerne les tutoriels comprenant plusieurs chapitres et/ou parties (ex : Débutez dans la 3D avec Blender). Actuellement lorsque l'on est en train de lire un chapitre pour pouvoir revenir au sommaire il faut cliquer sur le titre du tutoriel dans la seconde barre horizontale, pour ma part je ne trouve pas cela très pratique, de plus lorsque l'on est en lecture zen il est tout simplement impossible de revenir au sommaire.
> 
> Selon moi, il serais plus pratique d'ajouter un bouton "Home" juste à gauche de la barre de navigation entre les chapitres. Ainsi revenir au sommaire serais plus pratique et sera alors faisable en lecture zen.

Source: https://zestedesavoir.com/forums/sujet/3622/tutoriels-button-pour-revenir-au-sommaire/

**Comment by Anto59290** [comment]
Je prends (@Anto59290)

**Comment by Karnaj** [comment]
@Anto59290 t’es toujours dessus ?

**Comment by Anto59290** [comment]
Negatif ;)

**Comment by Karnaj** [comment]
Je vais essayer de m’en occuper alors.

**Comment by pierre-24** [comment]
Merci @Karnaj :)
