### ISSUE TITLE
Ajouter les membres de l'équipe de communication sur la page contact

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2911]
Je pense qu'il serait bien d'ajouter les membres de l'équipe de communication sur la page de contact pour que les membres puissent les contacter directement via le site.

D'ailleurs, on pourrait même rajouter un bouton "Contacter cette équipe" pour toutes les équipes, ce qui préparerait un message avec tous les membres de l'équipe en destinataire.

Qu'en pensez-vous ?

**Comment by SpaceFox** [comment]
Maintenant qu'on a un groupe, ça devrait même être super simple à faire :)

**Comment by Situphen** [comment]
J'aurais besoin du nom du groupe, si tu peux me le donner s'il te plait :)

Pour les liens de contact je pense qu'on va être obliger de faire une boucle de plus pour chaque groupe :( Après, on peut mettre si besoin un cache sur cette page sans trop se casser la tête.

**Comment by gustavi** [comment]
Je pense qu'il faudrait faire quelque chose de flexible à ce niveau et pourquoi pas stocker ces informations dans le _settings.py_. L'ajout et le retrait d'un groupe serait alors bien plus facile.

**Comment by Situphen** [comment]
@gustavi : En fait, on n'en a même pas besoin si on se base sur la base de donnée directement ! Quand il n'y a personne dans un groupe en base de donnée, il faut juste ne pas afficher ce groupe et sa définition donc on n'a plus besoin de paramètres dans le `settings.py`.

**Comment by gustavi** [comment]
Je parlais de stocker le nom de groupe et la définition. Ça permet plus de souplesse.

**Comment by Situphen** [comment]
Les définitions je ne sais pas si ce serait possible facilement vu qu'il y a des variables comme les adresses de courriel à afficher. À voir.

**Comment by poulp** [comment]
Je partirais sur la solution de stocker ces informations, on aurait un modèle qui regrouperait un lien vers le groupe et une description. La description pourrait se faire au format markdown mais le hic que je vois c'est qu'on peut pas faire de mailto :/ Et au niveau de la création de ces modèle de passer directement par l'interface admin.

**Comment by gustavi** [comment]
Cette page devrait être revue bientôt donc ne vous engagez pas dessus pour le moment ;)

**Comment by Emeric54** [comment]
On peut fermer ici.
