### ISSUE TITLE
Indexer les unes

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2929]
Ça serait bien qu'on puisse rechercher dans les anciennes une avec le moteur de recherche.

**Comment by Situphen** [comment]
Je suis contre ! A quoi ça servirait ? Les Unes pointent la plupart du temps vers une ressource interne à ZdS, donc autant que la recherche retourne cette ressource plutôt qu'une Une (qui est comme un raccourci vers cette ressource) !

**Comment by DevHugo** [comment]
C'était pour que si tu utilise un mot dans le titre de la une, tu soit rediriger vers le contenu ^^. Aprés le titre en tout cas pour les premières, semble être les mêmes que le titre du sujet donc pas très  utile pour l'instant.

Je pensais aussi à faire en sorte que si Solr voit un document qui était en une, il le priorise par rapport aux autres documents

**Comment by Eskimon** [comment]
> Je pensais aussi à faire en sorte que si Solr voit un document qui était en une, il le priorise par rapport aux autres documents

Pourquoi ? Un contenu en Une n'est pas forcément de meilleure qualité qu'un autre, il sert juste à mettre en évidence une création pendant un laps de temps.

Grosso modo je pense que ce ticket ne sera jamais pris en charge au vu des autres développement à faire avant, je le ferme donc, à rouvrir au besoin.

**Comment by DevHugo** [comment]
Ok, je comprend vos arguments.
