### ISSUE TITLE
ajouter des liens RSS/ATOM dans le head sur certaines pages

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2933]
[via Nax](https://zestedesavoir.com/forums/sujet/3658/ajouter-les-liens-des-flux-rss-atom-dans-le-header/#p66054)

Bonjour, il faudrait rajouter des liens RSS/ATOM de type

``` html
<link rel="alternate" type="application/rss+xml" title="Nouveaux articles (RSS)" href="https://zestedesavoir.com/articles/flux/rss/"/>
<link rel="alternate" type="application/atom+xml" title="Nouveaux articles (ATOM)" href="https://zestedesavoir.com/articles/flux/atom/"/>
```

Pour les articles, tutoriel et forum dans le header du site pour pouvoir les ouvrir avec les outils intégré aux navigateurs.
Source:[nax](http://zestedesavoir.com/forums/sujet/3658/ajouter-les-liens-des-flux-rss-atom-dans-le-header/?page=1#p66054)

**Comment by artragis** [comment]
Je tag pour que la partie "article/tuto" soit dans la zep-12.
