### ISSUE TITLE
Recevoir un email lors du réponse sur le forum automatique

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2934]
Bonjour,

je me demandais, y aurait-il la possibilité de mettre dans les paramètres "Recevoir par défaut un email lors de la réponse sur un forum" donc plutôt comme actuellement de devoir mettre "Je veux recevoir un email lorsqu'une réponse est posté sur ce topic" que se soit par défaut "Je ne veux pas recevoir d'email concernant ce topic".

Voir même, une option "Recevoir un email par défaut lors d'une réponse sur les topics que nous avons créer".

**Comment by Situphen** [comment]
AMHA il faudrait carrément faire une page pour le paramétrage des notifications ! Le mieux est sûrement d'en parler sur [le sujet de la ZEP 24](https://zestedesavoir.com/forums/sujet/2251/zep-24-refonte-et-enrichissement-des-notifications/). :)

**Comment by Eskimon** [comment]
Yep, go ZEP-24, je ferme ici pour éviter le doublon.
