### ISSUE TITLE
L'url de l'adresse du sitemap.xml est codé en dur

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2938]
Fichier impacté : [robots.txt](https://github.com/zestedesavoir/zds-site/blob/dev/robots.txt)

On voit que l'url du sitemap.xml est codé en dur. Ce qui fait qu'en beta on se retrouve avec l'url de la prod par exemple.

C'est pas gravissime, mais ça reste un tout petit bug quand même.

**Comment by WinXaito** [comment]
Bonjour,

si j'ai bien compris, il faudrait juste remplacer `Sitemap: http://zestedesavoir.com/sitemap.xml` par `Sitemap: /sitemap.xml` ?

Si ce n'est que ça, est-ce que ça embeterais quelqu'un que je le fasse ? :p Car j'aimerais bien un peu posté sur des projets OpenSource, mais j'ai un peu de pêne a m'y faire...

**Comment by Eskimon** [comment]
Fais toi plaisir :)

Ta solution devrais marcher, sinon faudra simplement ajouter ce champ : https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L376

**Comment by WinXaito** [comment]
Bon et bien je prend alors :p

**Comment by SpaceFox** [comment]
> Ta solution devrais marcher, sinon faudra simplement ajouter ce champ : https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L376

C'est pas un fichier statique le robots.txt ?

**Comment by WinXaito** [comment]
[edit]  
Problème réglé:p

**Comment by Eskimon** [comment]
> C'est pas un fichier statique le robots.txt ?

Ca devrait se jouer par la je suppose... https://github.com/zestedesavoir/zds-site/blob/dev/zds/urls.py

**Comment by WinXaito** [comment]
Une petite question, est-ce normal que quand je lance mon instance du zds en local je ne vois pas les styles ? Car /static/css/main.min.css est introuvable, j'ai loupé quelque chose ?

**Comment by Eskimon** [comment]
au choix, soit tu `git checkout` un des tags `*-build` soit tu build le front toi meme avec npm

**Comment by WinXaito** [comment]
Ah je vois, et il y a une possibilité de merge une modification d'une branche sur une build pour tester mais de garder ça branche active ?

(Et au passage, en utilisant la v15.6-cadrat-build, j'obtiens une erreur 404 en voulant aller sur /robots.txt)

**Comment by Eskimon** [comment]
> Ah je vois, et il y a une possibilité de merge une modification d'une branche sur une build pour tester mais de garder ça branche active ?

J'ai pas compris :(

**Comment by Eskimon** [comment]
et sinon `/sitemap.xml` ca donne quoi ?

**Comment by WinXaito** [comment]
``` xml
<sitemapindex>
  <sitemap>
    <loc>http://example.com/sitemap-articles.xml</loc>
  </sitemap>
  <sitemap>
    <loc>http://example.com/sitemap-tags.xml</loc>
  </sitemap>
  ...
</sitemapindex>
```

[edit]  
ça ne vient pas de ma modif, c'est également le cas sur la branche dev et v15.6-cedrat-build

**Comment by WinXaito** [comment]
> > Ah je vois, et il y a une possibilité de merge une modification d'une branche sur une build pour tester mais de garder ça branche active ?
> 
> J'ai pas compris :(

Ce que je voulais dire, c'est que j'ai fais ma modif sur la branche `winxaito`, mais pour ne pas devoir recompiler le front, j'utilise la version `v15.6-cedrat-build`. Donc je voulais savoir si je pouvais merge winxaito dans la v15.6, mais garder tout de même ma branche winxaito pour la pull request plus tard

**Comment by Eskimon** [comment]
Ce que tu fais c'est que tu récupères les fichiers du front (le dossier `/dist`) et après tu devrais pouvoir repartir de n'importe quelle branche (comme `dev` par exemple). Car si tu fais une PR qui démarre de la branche de release et que tu veux proposer un patch dans `dev` ca risque de foutre la merde en ramenant toute les modifs de release dans dev

**Comment by WinXaito** [comment]
Ah je vois c'est bon, merci.

Par contre le robots.txt je ne peux toujours pas y accéder ?!

[edit] Est-ce par-ce que je ne passe pas par un serveur tel que Apache ou Nginx ?

**Comment by pierre-24** [comment]
Puisque la norme dit que l'adresse doit être absolue, cet issue n'as plus lieu d'être, si ?

**Comment by WinXaito** [comment]
En effet on peut la fermer

**Comment by Situphen** [comment]
Il n'y a pas moyen de templatiser `robots.txt` pour paramètriser le nom de domaine ?

**Comment by WinXaito** [comment]
Je ne sais pas si dans la config de nginx on peut rediriger vers un fichier python ? Si oui je pense que ça devrait être faisable.
