### ISSUE TITLE
Supprimer chapitre : erreur 404 

### ISSUE THREAD

**Issue by Vayel** [zestedesavoir/zds-site#2939]
> Bonjour,
> 
> J'ai voulu supprimer un chapitre d'un big-tuto et suis tombé sur une erreur 500 je crois (avec le template affiché). Le chapitre n'a pas été supprimé et quand j'essaye de le faire, j'obtiens une 404.
> 
> Je peux ajouter des gens au contenu si certains veulent voir ça plus en détails.
> 
> Merci.
> Source:[Vayel](http://zestedesavoir.com/forums/sujet/3696/supprimer-chapitre-erreur-404/?page=1#p66594)

**Comment by pierre-24** [comment]
Ce qui m'étonne un peu, c'est qu'il est pas remonté par Sentry :/

**Comment by Vayel** [comment]
Le chapitre a disparu. Il fallait probablement fermer le tutoriel.

**Comment by pierre-24** [comment]
Donc on garde le ticket, ou bien ?

**Comment by Vayel** [comment]
En fait non. Pardon, j'ai raconté n'importe. Il s'est passé cela : 
- Clic sur le bouton de suppression du chapitre
- Erreur 500 (affichage du template)
- Retour à la page précédente
- Clic sur le bouton de suppression du chapitre
- Erreur 404

En fait, le chapitre a bien été supprimé, j'ai juste eu un problème de redirection dû à une erreur 500 comme on en rencontre de temps en temps.

**Comment by WinXaito** [comment]
Si j'ai bien compris c'est parce qu'en revenant en arrière, ton navigateur n'a pas réacutalisé la page donc le bouton de suppression était toujours la alors qu'il ne le devait pas ?

**Comment by Vayel** [comment]
Oui.

Il est possible qu'il soit resté même après réactualisation, mais je ne me souviens plus trop.

**Comment by WinXaito** [comment]
> Il est possible qu'il soit resté même après réactualisation, mais je ne me souviens plus trop.

Si le bouton reste après actualisation, à ce moment la ça serait un bug non ?

**Comment by Vayel** [comment]
Oui. Mais le bug serait surtout que la chapitre reste, puisque le bouton est dans le chapitre. Mais vu que c'est réglé et que je n'ai pas plus de détails, on perdrait probablement notre temps à en consacrer à un problème aussi minime.

**Comment by WinXaito** [comment]
Ah autant pour moi, si le bouton se trouve dans la partie supprimé, il ne sera forcément plus la si la suppression réussi.

**Comment by Vayel** [comment]
Du coup je ferme ou quelqu'un veut approfondir la question ?

**Comment by WinXaito** [comment]
Selon moi ça doit être bon :)

**Comment by Vayel** [comment]
Je me trouve face à la même situation. Quelqu'un veut-il jeter un coup d'oeil au tutoriel concerné ?

**Comment by pierre-24** [comment]
De quel tuto s'agit-t-il ? (met le lien, le staff y aura accès).

**Comment by Vayel** [comment]
Je rêve, le chapitre vient de disparaître... Mais du coup, je crois savoir ce qui en est à l'origine : 
- Suppression d'un chapitre
- Erreur 500
- Chapitre toujours présent
- Suppression du chapitre
- Erreur 404
- Chapitre toujours présent
- Suppression du chapitre
- Erreur 404
- Chapitre toujours présent
- Création d'un chapitre (dans la même partie)
- Chapitre précédent disparu

Le tutoriel est : https://zestedesavoir.com/tutoriels/off/1111/betas-commentaires/1355/tutoriels/

**Comment by Vayel** [comment]
Ca recommence : https://zestedesavoir.com/tutoriels/off/1111/betas-commentaires/1355/tutoriels/5360/fonctionnement-des-ordinateurs-de-zero/?version=4dc17932b3c2e2bb94c482d8e15ec9db89bc956a

**Comment by Vayel** [comment]
Je confirme : la création d'un chapitre dans la partie du chapitre dont la suppression mène à une 500 puis à des 404 supprime le chapitre problématique.

Peut-être faudrait-il ré-ouvrir l'issue ?
