### ISSUE TITLE
Authentification Google | Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by Oza94** [zestedesavoir/zds-site#2941]
Hello, je ne me suis pas connecté depuis quelques semaine sur ZDS. Je me suis inscrit via Google. Au moment de me connecter via Google j'ai cette jolie erreur d'OAuth2 Google:

Url:

```
https://accounts.google.com/o/oauth2/auth?scope=https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.profile&state=o95qBAskyaqaiV98MWDlr7kZGljgN3Hn&redirect_uri=https://zestedesavoir.com/complete/google-oauth2/&response_type=code&client_id=1091336687263-70sdbncjavqc9n0ub88or5dec9nlb7ak.apps.googleusercontent.com
```

Détails de la requête:

```
The redirect URI in the request: https://zestedesavoir.com/complete/google-oauth2/ did not match a registered redirect URI.

response_type=code
scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
redirect_uri=https://zestedesavoir.com/complete/google-oauth2/
state=o95qBAskyaqaiV98MWDlr7kZGljgN3Hn
client_id=1091336687263-70sdbncjavqc9n0ub88or5dec9nlb7ak.apps.googleusercontent.com
```

Après reset password via email je peux me connecter.

Vous pouvez régler ce genre d'erreur directement via la console Google sans déploiement en ajoutant la redirect_uri `https://zestedesavoir.com/complete/google-oauth2/`, après je ne connais pas les détails du problème et je pense que la solution est moins naïve ^^

**Comment by Eskimon** [comment]
ping @ShigeruM @ChantyTaguan vous pouvez jeter un oeil à ca ?

**Comment by Oza94** [comment]
By the way j'en profite pour remonter que les [scopes que vous utilisez sont dépréciés](https://developers.google.com/+/web/api/rest/oauth). Il faut remplacer:

| Déprécié | Actuel |
| :-- | :-- |
| `https://www.googleapis.com/auth/userinfo.profile` | `profile` |
| `https://www.googleapis.com/auth/userinfo.email` | `email` |

Je peux ouvrir une seconde issue si besoin.

**Comment by DevHugo** [comment]
Pour les scopes, c'est géré par la librairie ["python-social-auth"](https://github.com/omab/python-social-auth). Faudrait voir comment on peut configurer ça, mais j'ai pas trop d'espoir. 

Créé une autre issue, serait bien, car je ne pense pas que les deux soucis soient liés.

**Comment by Oza94** [comment]
Pour les scope j'ai ouvert l'issue directement sur python-social-auth. Fwi j'ai restesté a l'instant et j'ai toujours le problème de redirect_uri_mismatch.

**Comment by Situphen** [comment]
Up ! [Quelqu'un d'autre a apparemment cette erreur.](https://twitter.com/Fanfan54T/status/636485313569910784)

**Comment by fanfan54old** [comment]
C'est moi qui ai rencontré l'erreur
Finalement j'ai pu me connecter en choisissant un mot de passe via la procédure "Mot de passe oublié", je me suis rappelé de mon pseudo et ai effectué un login traditionnel id/mdp.
Mais le login Google est bien impossible, que l'on soit déjà inscrit ou non, la procédure OAuth échoue. J'ai vérifié en créant un nouveau compte avec un nouveau compte Google, idem. Erreur 400.

**Comment by Oza94** [comment]
@Situphen je connais bien les APIs Google et ce problème peut très probablement se régler en 5 minutes montre en main. Il s'agit d'ajouter l'URL de prod de redirection OAuth aux URLs de callback autorisées dans la console Google: https://console.developers.google.com. Attention à bien ajouter l'URL de prod au client_id qui est utilisé en prod. 

Si quelqu'un dispose d'accès en contributeur au compte Google et connait le client id utilisé en production je peux l'aider à faire la manip' (via skype ou autre). 

La connexion via Google est un confort non-négligeable à mon sens :)

**Comment by WinXaito** [comment]
> La connexion via Google est un confort non-négligeable à mon sens :)

Il n'est pas prévu de l'abandonner, un simple bug :)

**Comment by ChantyTaguan** [comment]
Plop, je viens de tomber sur ceci. J'ai normalement ajouté l'url de redirection en prod aux urls autorisées. @Oza94 , si tu sais re-tester à l'occasion :)

**Comment by Oza94** [comment]
Testé à l'instant j'ai toujours la même erreur:

```
Request Details
scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
response_type=code
state=bYdpgFL85nGpvlVXR1gfE0rf2Vy6PvvW
redirect_uri=https://zestedesavoir.com/complete/google-oauth2/
client_id=1091336687263-70sdbncjavqc9n0ub88or5dec9nlb7ak.apps.googleusercontent.com
```

Je refais un test en début d'après midi, normalement la propagation est quasi-instantanée mais on sait jamais :)

**Comment by DevHugo** [comment]
Je confirme que ça marche pas.

**Comment by ChantyTaguan** [comment]
Arf.... My bad, mauvais projet. Ca devrait être mieux là.

**Comment by Oza94** [comment]
Je confirme que ça fonctionne, merci @ChantyTaguan !

**Comment by DevHugo** [comment]
Bravo, tu peux faire la même chose sur Facebook maintenant :P !

Tu as gagné, mes félicitations ^^
