### ISSUE TITLE
Bug d'affiche sur mobile sans javascript

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2942]
Voici une image de ce à quoi ressemble le site quand nous réduisons la page et que nous n'avons pas javascript activé.

Sur mon natel (Lumia 625 Windows phone), cette affichage ce produit pendant 1 petite seconde parfois avant que javascript ce charge de remettre le bon affichage.

![zds_view](https://cloud.githubusercontent.com/assets/8223773/8851014/dbcd6d70-314c-11e5-9369-a7d42b90bbe9.png)

[edit]  
Il me semble que ce soit encore pire avec le message concernant google analytics. (Message qui ne s'affiche plus en étant déconnecté et en ayant supprimé les cookies ??)

**Comment by Situphen** [comment]
Ton premier point est normalement traité en CSS. Il ne devrait pas y avoir de bug que le JS soit activé ou non. Est-ce que quand tu actives le JavaScript tu as le même problème ? Si oui, c'est peut-être que ton navigateur met du temps à calculer le CSS.

Pour le deuxième point, le message d'avertissement des cookies est géré en JS et ne s'affiche pas quand le JS est désactivé car le traceur de Google Analytics est en JS aussi.

**Comment by WinXaito** [comment]
Etrange, même avec JS activé et les cookies désactivé et supprimé le message ne s'affiche pas.

J'ai testé sur Opera et Firefox et voici ce que j'obtitens:

Avec Javacsript activé:
![zds_view_2](https://cloud.githubusercontent.com/assets/8223773/8853161/b89a9d70-3159-11e5-987f-02e1bfe96714.png)

Sans javascript: 
![zds_view_3](https://cloud.githubusercontent.com/assets/8223773/8853166/bf1268cc-3159-11e5-86d9-d8c061173984.png)

J'ai recontrolé sur mon téléphone, lors du chargement de la page j'ai l'affiche du "Sans javascript" et une fois la page chargé le style ce modifie pour devenir comme "Avec javascript", donc je suis casiment certain que ça vient de javascript.

Ps: Il y a quelques petits bug avec la bannière de Google analytics quand on augmente et réduis la page (Que j'ai eu sur Opera)

**Comment by sandhose** [comment]
En réalité, cette affichage est plus ou moins "voulu", puisque sans JS, on a pas de barre latérale... Mais comme il faut quand même pouvoir accéder au menu, on l'affiche de cette manière. Rien de choquant la dedans, sauf peut-être la licence, qui doit être en `position: absolute` ou un truc dans le genre, et éventuellement le titre qui pourrait être plus large est mieux aligné...

**Comment by sandhose** [comment]
Et pour la barre des cookies, par défaut elle s'affiche pas sans JS, simplement parce qu'on a pas d'analytics sans JS... Donc elle a aucun sens si le JS n'est pas activé

**Comment by WinXaito** [comment]
> En réalité, cette affichage est plus ou moins "voulu", puisque sans JS, on a pas de barre latérale... Mais comme il faut quand même pouvoir accéder au menu, on l'affiche de cette manière. Rien de choquant la dedans, sauf peut-être la licence, qui doit être en position: absolute ou un truc dans le genre, et éventuellement le titre qui pourrait être plus large est mieux aligné...

Je ne l'avais pas vu comme ça, c'est totalement justifié du coup.

> Et pour la barre des cookies, par défaut elle s'affiche pas sans JS, simplement parce qu'on a pas d'analytics sans JS... Donc elle a aucun sens si le JS n'est pas activé

J'ai testé sur Firefox en gardant JS activé et les cookies supprimé et/ou désactivé, cette barre ne veux pas venir.

**Comment by sandhose** [comment]
> > Et pour la barre des cookies, par défaut elle s'affiche pas sans JS, simplement parce qu'on a pas d'analytics sans JS... Donc elle a aucun sens si le JS n'est pas activé
> 
> J'ai testé sur Firefox en gardant JS activé et les cookies supprimé et/ou désactivé, cette barre ne veux pas venir.

Elle ne s'affiche que sur la première visite. Essaie en navigation privée, ou en vidant tes cookies

**Comment by WinXaito** [comment]
Même avec les cookies vidés et en navigations privée cette barre n'apparait pas chez moi.

**Comment by sandhose** [comment]
Hum, sûrement le DoNotTrack qui est activé, qui désactive le tracking...

**Comment by WinXaito** [comment]
Ah oui je l'avais oublié, dans mes souvenirs c'est comme les boutons "Facebook, twitter, ..." qui sont désactivé par AdBlock. Je crois qu'il désactive également Google analytics...

**Comment by WinXaito** [comment]
Du coup je pense qu'on peut fermer cette issue, sauf éventuellement pour la liscence sur firefox qui est un peu affiche n'importe comment et afficher le titre en entier ...
