### ISSUE TITLE
Subtitle dans l'historique des tutoriels

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2944]
Bonjour,

en rédigeant mon tutoriel j'ai remarqué une petite différence entre l'affichage du tutoriel et celle de l'historique:

![Vue normal](https://cloud.githubusercontent.com/assets/8223773/8913437/5ffee3a4-3499-11e5-9fa8-764c8a83dfd6.png)

![Vue historique](https://cloud.githubusercontent.com/assets/8223773/8913439/627b61c0-3499-11e5-8c3e-c56a82507056.png)

J'ai controlé dans le code, et effectivement:

dans [templates/tutorial/tutorial/view.html](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorial/tutorial/view.html#L36) nous avons:

``` html
{% if tutorial.description %}
  <h2 class="subtitle">
    {{ tutorial.description }}
  </h2>
{% endif %}
```

alors que dans [templates/tutorial/tutorial/history.html](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorial/tutorial/history.html#L42) nous avons:

``` html
<h2 class="subtitle">
  {{ tutorial.description }}
</h2>
```

Je trouve plus correcte la version du view.html, car ça me semble illogique de laisser un `<h2>` vide.

Si vous validez, je veux bien prendre cette issue en charge :)

WinXaito

**Comment by Eskimon** [comment]
Yep fais toi plaisir avec ca :)

**Comment by WinXaito** [comment]
Très bien je m'y lance tout de suite alors :)

[edit]  
Juste une question, si on a déjà fork le projet il y a un moment sur notre compte, comment on le met à jour sans le "defork" et le "refork" ?

**Comment by DevHugo** [comment]
je crois que tu veux parler de la commande `git pull`. Tu fais un `git checkout nom_branche` puis tu fait un `git pull`

**Comment by WinXaito** [comment]
Hm oui cette commande est pour le local non ?

Imaginons, je fork le projet sur mon compte, et que quelqu'un fait une modification, la modification sera faite sur mon compte aussi ?

Car si elle n'est pas faite, et que je fais un `git pull` sur mon compte, la modification ne sera quand même pas créer ? Je pense que je me mélange un peu les pinceaux :p

**Comment by WinXaito** [comment]
J'ai un petit soucis, j'ai éditer le fichier avec **notepad++**, mais une fois que j'ai `commit` et `push`, les incrémentations ne joue plus ... https://github.com/WinXaito/zds-site/blob/winxaito/templates/tutorial/tutorial/history.html#L42

**Comment by pierre-24** [comment]
À mon avis, notepad++ intègre directement des tabulations, alors qu'on préfère les espaces :)

**Comment by WinXaito** [comment]
Merci, j'ai donc fait avec des espaces.

J'ai maintenant installer le backend et ce qu'il faut pour le serveur jusque la ça fonctionne, par contre maintenant j'aimerais lancer `gulp` pour me faire le frontend, mais j'obtiens des erreurs:

```
root@WinXaito:/home/kevin/www/www.zds.com/zds-site# npm run gulp -- build

> zds-site@0.2.0 gulp /home/kevin/www/www.zds.com/zds-site
> gulp "build"

[21:32:19] Using gulpfile /home/kevin/www/www.zds.com/zds-site/Gulpfile.js
[21:32:19] Starting 'sprite'...
[21:32:19] 'sprite' errored after 33 ms
[21:32:19] Error: PluggableError: lwip not found.
    at formatError (/home/kevin/www/www.zds.com/zds-site/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/home/kevin/www/www.zds.com/zds-site/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (/home/kevin/www/www.zds.com/zds-site/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /home/kevin/www/www.zds.com/zds-site/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/home/kevin/www/www.zds.com/zds-site/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/home/kevin/www/www.zds.com/zds-site/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:36:10)
    at Gulp.Orchestrator._runTask (/home/kevin/www/www.zds.com/zds-site/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/kevin/www/www.zds.com/zds-site/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/kevin/www/www.zds.com/zds-site/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /home/kevin/www/www.zds.com/zds-site/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Linux 3.2.0-4-686-pae
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "gulp" "--" "build"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! zds-site@0.2.0 gulp: `gulp "build"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zds-site@0.2.0 gulp script 'gulp "build"'.
npm ERR! This is most likely a problem with the zds-site package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp "build"
npm ERR! You can get their info via:
npm ERR!     npm owner ls zds-site
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kevin/www/www.zds.com/zds-site/npm-debug.log
```

Et le contenu du fichier npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'gulp', '--', 'build' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'pregulp', 'gulp', 'postgulp' ]
6 info pregulp zds-site@0.2.0
7 info gulp zds-site@0.2.0
8 verbose unsafe-perm in lifecycle true
9 info zds-site@0.2.0 Failed to exec gulp script
10 verbose stack Error: zds-site@0.2.0 gulp: `gulp "build"`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid zds-site@0.2.0
12 verbose cwd /home/kevin/www/www.zds.com/zds-site
13 error Linux 3.2.0-4-686-pae
14 error argv "/usr/bin/node" "/usr/bin/npm" "run" "gulp" "--" "build"
15 error node v0.12.7
16 error npm  v2.11.3
17 error code ELIFECYCLE
18 error zds-site@0.2.0 gulp: `gulp "build"`
18 error Exit status 1
19 error Failed at the zds-site@0.2.0 gulp script 'gulp "build"'.
19 error This is most likely a problem with the zds-site package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     gulp "build"
19 error You can get their info via:
19 error     npm owner ls zds-site
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by DevHugo** [comment]
Je suis loin d'être un pro avec les outils front, normalement si tu met Node à jours de la version 0.10 à 0.12, faut ré-installer la librairie à la main. Essaye donc de supprimer le dossier node_modules et tente un `npm uninstall lwip` et `npm install lwip`.

**Comment by WinXaito** [comment]
Hm non ça ne marche pas :/

**Comment by Situphen** [comment]
@WinXaito, quand tu crées une nouvelle branche, il faut partir de `upstream/dev` pour avoir les dernières modifications. On a donc :

```
git fetch upstream
git checkout upstream/dev
git checkout ma-branche
```

Est-ce que `npm run gulp -- build` fonctionne après ces commandes ?

**Comment by WinXaito** [comment]
La commande `git fetch upstream` me retourne 

``` text
fatal: 'upstream' does not appear to be a git repository
fatal: The remote end hung up unexpectedly
```

**Comment by Fumble** [comment]
As-tu fais un `git remote add upstream https://github.com/zestedesavoir/zds-site.git` sur ton fork?
Pour le savoir, fais `git remote -v` pour voir si le dépot original est ajouté en tant que dépôt distant.

Chez moi, ça donne ça:

```
Fumble@FUMBLE-PC ~/git/zds-site (dev)
$ git remote -v
origin  git@github.com:Fumble/zds-site.git (fetch)
origin  git@github.com:Fumble/zds-site.git (push)
upstream        https://github.com/zestedesavoir/zds-site.git (fetch)
upstream        https://github.com/zestedesavoir/zds-site.git (push)
```

Ensuite, pour garder ton dépôt local et le fork sur GitHub à jour (je prends la branche dev en local sur le fork comme exemple):

```
git fetch upstream
git merge upstream/dev
git push origin dev
```

**Comment by WinXaito** [comment]
Ah merci Fumble, en effet je n'avais pas l'upstream,
mais ça ne change rien pour `npm run gulp -- build`, toujours la même erreur :/

**Comment by Eskimon** [comment]
@WinXaito tu pourras venir faire un tour [sur IRC](https://zestedesavoir.com/forums/sujet/500/zestedesavoir-sur-smoothirc-le-canal-irc-de-zeste-de-savoir/) demain pour qu'on voit ensemble ce qui pose problème ?

**Comment by WinXaito** [comment]
Oui bien sur, je vais voir pour essayer de trouver un moment :) Merci !

**Comment by Situphen** [comment]
@WinXaito : Tu as retenté un `npm install` ?

J'essayerai de passer ce soir sur IRC mais je ne promets rien.

**Comment by WinXaito** [comment]
Oui,

mais je crois enfin avoir trouvé la solution en lisant un peu mieux les messages d'erreur, je vous tiens au zeste

**Comment by WinXaito** [comment]
Merci à @Eskimon et @sandhose pour m'avoir aider sur IRC, voici en deux mots le soucis que j'ai eu si quelqu'un l'a aussi:

Il fallait installer `make, build-essential et g++`,
Ensuite il fallait également installer `GraphicsMagick`,

Il fallait ajouter `engine: "gm",`

``` javascript
gulp.task("sprite", function() {
  return sprite.src({
      cssPath: "../" + imagesDir + "/",
      dimension: [{ ratio: 1, dpi: 72 },
                  { ratio: 2, dpi: 192 }],
      margin: 0,
      src: path.join(sourceDir, imagesDir, spriteDir, "*"),
      style: "_sprite.scss",
      template: path.join(sourceDir, sassDir, "sprite-template.hbs"),
      engine: "gm",
    })
    .pipe($.if("*.png", gulp.dest(path.join(destDir, imagesDir)), gulp.dest(path.join(sourceDir, sassDir))));
});
```

Et il faut finalement commenter cette ligne:

``` javascript
/**
 * Process images files
 */
gulp.task("images",  ["stylesheet"], function() {
  return gulp.src(path.join(sourceDir, "{" + imagesDir + ",smileys}", "*.{jpg,png,gif}"))
    //.pipe($.imagemin(imageminConfig))
    .pipe($.size({ title: "Images" }))
    .pipe(gulp.dest(destDir));
});
```

**Comment by yapper-git** [comment]
Ce ticket devrait désormais être fermé car la PR #2945 doit avoir corrigé le problème.

**Comment by pierre-24** [comment]
Bien vu :)
