### ISSUE TITLE
La documentation ne builde plus depuis la 15.6b

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2946]
Comme en témoigne le badge correspondant ( [![Documentation Status](https://readthedocs.org/projects/zds-site/badge/?version=latest)](https://readthedocs.org/projects/zds-site/?badge=latest) ), la documentation de zeste de savoir ne builde plus depuis le 13 juillet 2015.

Le commit par lequel le loup est entré dans le bergerie est  [celui-ci](https://github.com/zestedesavoir/zds-site/commit/12cfc4921aa7ed49ce7d8aa0ea39815eeeafb5af)

Ce qui a eu pour effet le premier build en echec de la doc qu'on peut voir [là](https://readthedocs.org/builds/zds-site/3078645/). Dès lors, on remarques que la doc n'a plus buildée.

Je taggue donc en regression, car ça fonctionnait pourtant bien avant.

**Comment by pierre-24** [comment]
Fait ch*** !!!

Il va encore falloir faire de la magie noire :/

**Comment by artragis** [comment]
Magie noire puissance 1000 oO

**Comment by pierre-24** [comment]
Plus sérieusement, c'est la même erreur qu'avant (il manque `django-debug-toolbar`), alors qu'on avait fait en sorte qu'il revienne. Je vote donc que ce soit la MàJ de sécurité de Django qui nous aie remis dedans.

**Comment by poulp** [comment]
Je viens de regarder le build et ça donne ça : 

```
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    pkgs = [str(pkg.req) for pkg in parse_requirements('requirements.txt')]
  File "/home/docs/checkouts/readthedocs.org/user_builds/zds-site/envs/latest/local/lib/python2.7/site-packages/pip/req/req_file.py", line 72, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'
```

Comment ça pourrais venir de `debug-toolbar` ? D’après ce que j'ai vu sur le net ça à plutôt l'air d'être un problème avec pip

**Comment by Situphen** [comment]
J'en sais rien. Ce bug est ultra bizarre car il est apparu avec le _commit_ d'un changement mineur de version de Dango (mise à jour de sécurité) qui ne touche pas `django-toolbar` !

**Comment by pquentin** [comment]
En regardant ce que dit @poulp, il semblerait que vous utilisez une fonction `parse_requirements` de pip qui a changé de signature dans pip 6.0. Essayez avec `session=None` ou avec `session=uuid.uuid()`.

**Comment by pquentin** [comment]
En fait en local j'ai eu le même souci que dans le build RTD (pas le problème de pip), et je crois que Read the Docs ne prend pas en compte le fichier requirements-dev.txt. Dans mon cas, django-debug-toolbar n'était tout simplement pas installé, et l'installer a réglé le souci. 

Selon les docs, "If you have the Use Virtualenv option enabled, we will run setup.py install on your package, installing it into a virtual environment. You can also define additional packages to install with the Requirements File option." C'est à faire par un admin sur RTD ?

(Ensuite la PR de @Situphen pourra régler la suite, j'imagine.)

**Comment by pierre-24** [comment]
Situphen vient de nous réparer ça ;)
