### ISSUE TITLE
Message incohérent dans une popup

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2949]
Bonjour,

je ne sais pas si c'est voulu mais ça me parrait étrange le `warning *`, (Popup d'attribution d'une remarque sur un membre)

![zds_err_4](https://cloud.githubusercontent.com/assets/8223773/8987817/2d76de0e-36e3-11e5-9875-25d3f9725767.png)

**Comment by WinXaito** [comment]
Je pense vite m'occuper de cette issue, j'ai penser à un truc du style de "Commentaire *" Plutôt que "Warning", des objections avant que je commence ?

**Comment by Eskimon** [comment]
Yep "Commentaire" c'est bien :)

**Comment by WinXaito** [comment]
Okay donc je prend :)

**Comment by WinXaito** [comment]
@pierre-24 ou quelqu'un d'autre du coup, comme ça a été merger on peut fermé :) Merci !

**Comment by firm1** [comment]
En effet
