### ISSUE TITLE
Petit soucis de style

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2950]
Bonjour, 

cette après midi je m'embetais un peu, j'ai donc effectuer pas mal de petit test sur une version local pour retrouver quelques anomalies.

Possibilité d'avoir des champs vide (Dans tous le site). (Caractère: `alt + 0143`)

![zds_style_2](https://cloud.githubusercontent.com/assets/8223773/8990976/e5d691b2-36f5-11e5-9973-fbdeb4b522f4.png)
![zds_style_1](https://cloud.githubusercontent.com/assets/8223773/8990979/e5dc51ba-36f5-11e5-9238-4c865c2d57a0.png)

Problème avec les longs pseudo (Eventuellemetn réduire la limite ?)

![zds_longpseudo_2](https://cloud.githubusercontent.com/assets/8223773/8990977/e5da3c04-36f5-11e5-9370-42c1745e4f1b.png)
![zds_longpseudo_1](https://cloud.githubusercontent.com/assets/8223773/8990978/e5dbf256-36f5-11e5-8b35-2ace8fe23a55.png)

WinXaito

**Comment by Situphen** [comment]
> Possibilité d'avoir des champs vide

Dans les exemples que tu cites, les champs ne sont pas vides, ils sont remplis avec des caractères invisibles. Je ne sais pas trop si on peut y faire quelque chose. En tous cas, ce n'est pas super gênant car si quelqu'un s'amuse avec ça, il sera sanctionné par le Staff !

> Problème avec les longs pseudo (Eventuellemetn réduire la limite ?)

Peut-être mettre une limite, mais laquelle ?

**Comment by WinXaito** [comment]
Ce que l'ont pourrait faire avec les pseudos c'est mettre une limite et filtrer les caractère alphanumérique comme twitter

**Comment by yapper-git** [comment]
Il ne faut pas oublier que certains membres actuels ont déjà des pseudos contenant des espaces, apostrophes, accents etc.

**Comment by Eskimon** [comment]
Faudrait faire des recherches dans les tickets pour ces histoires de pseudo car il me semble qu'on en a déjà parlé il y a très longtemps.

Sinon pour les caractères invisibles ça me semble compliqué d'y faire quoi que ce soit...

Du coup je ferme, d’expérience je serais prêt à parier que ce ticket ne verra jamais de correction.

**Comment by WinXaito** [comment]
M'enfin y a rien à faire pour le style ? Un display none .. on verrait plus rien mais c'est toujours mieux que des trucs superposé .. Je trouve moyen.. m'enfin.

**Comment by pquentin** [comment]
Oui les pseudos Unicode c'est à prendre au sérieux, cf. https://labs.spotify.com/2013/06/18/creative-usernames/

**Comment by GerardPaligot** [comment]
@WinXaito Quand j'entends quelqu'un qui dit ou sous-entend que "il suffit de faire ça", c'est très rarement le cas.

Sinon, je me range du côte du caribou. Vu que nous acceptons tous les caractères dans les pseudos depuis la création du site, ça me semble difficile de mettre en place une solution qui reste compatible avec absolument tous les pseudos sur absolument tous les navigateurs (ordinateurs et mobiles compris).

**Comment by WinXaito** [comment]
Oui bien entendu, je veux pas faire le type qui dise "Faite ça comme ça bande d’incapable c'est tout facile"..

Bien loin de moi cette idée, je dis simplement que ça ne fait pas très pro ceci .. donc avant de fermer et dire on laisse ça comme ça, je trouvais que ça méritait réflexion. Après bien entendu il faut que quelqu'un le fasse.

![](https://cloud.githubusercontent.com/assets/8223773/8990977/e5da3c04-36f5-11e5-9370-42c1745e4f1b.png)
