### ISSUE TITLE
suivants/precedents qui prennent de la place sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2953]
En prod, les fleches suivant/precedents de la pagination sont ecrit en toute lettre alors qu'elles avaient ete sumprimees sur mobile. On ne devrait voir que les fleches sans le texte.

Il me semble que c'est une regression.

![screenshot_2015-08-06-13-25-20](https://cloud.githubusercontent.com/assets/6066015/9110545/d6e962c6-3c3e-11e5-859a-050529b2059c.png)

**Comment by Situphen** [comment]
C'est connu. C'est un problème qu'on ne rencontre qu'avec le gabarit `paginator.html` qui est un fork de `pagination.part.html` pour les vues en CBV.

**Comment by pierre-24** [comment]
Mais qui tend à prendre la place du premier partout ;)

**Comment by firm1** [comment]
> C'est connu.

On a un ticket la dessus ?

**Comment by Situphen** [comment]
#2597

**Comment by Eskimon** [comment]
Je ferme ici pour doublon
