### ISSUE TITLE
403 lors du téléchargment d'un tutoriel en Mardown 

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2954]
Bonjour,

il a été reporté dans la DevZone ce problème (https://zestedesavoir.com/forums/sujet/3805/403-lors-du-telechargment-dun-tutoriel-en-mardown/)

On nous signale qu'un auteur ayant été ajouté à un tutoriel ne peux pas télécharger le tutoriel au format Markdown.

**Comment by artragis** [comment]
à vérifier, mais il me semble que la zep12 le rend disponible. Si ce n'est pas le cas c'est qu'on a volontairement copié le comportement et du coup, @Situphen il faudra tagger ça évolution et non bug.

**Comment by Situphen** [comment]
Pour moi c'est un bug car un auteur devrait pouvoir télécharger son tutoriel au format MarkDown !

**Comment by WinXaito** [comment]
Il faut voir si la Zep12 règle le problème, si ce n'est pas le cas je trouve aussi que ça devrait être classé en tant que Bug. Car je ne vois pas pourquoi un auteur n'aurait pas le droit de télécharger son tutoriel au format markdown.

**Comment by artragis** [comment]
Il le peut, justement à l'heure actuelle (en prod) y'a que lui qui le peut.

**Comment by Situphen** [comment]
> un auteur ayant été ajouté à un tutoriel ne peux pas télécharger le tutoriel au format Markdown

Apparemment on ne peut pas...

**Comment by artragis** [comment]
Ah, il faut donc vérifier ça sur la zep12, mais il me semble que c'est OK.

**Comment by Eskimon** [comment]
du coup @artragis en ZEP12 ca donne quoi ? (ou @pierre-24 )

**Comment by pierre-24** [comment]
Testé unitairement et approuvé ;)

**Comment by artragis** [comment]
ça devrait être bon (404) à voir dès que la beta est up.
