### ISSUE TITLE
Lien sujet bêta dans le contenu

### ISSUE THREAD

**Issue by Vayel** [zestedesavoir/zds-site#2955]
A l'instar de "Consulter la version en bêta", il serait pratique d'avoir un lien "Consulter le sujet de bêta" dans le menu de gauche d'un contenu.

**Comment by Situphen** [comment]
Il faudrait pour cela lier le tutoriel avec le sujet de la bêta.

**Comment by Vayel** [comment]
De toute façon, on en aura besoin pour la [ZEP-18](https://zestedesavoir.com/forums/sujet/1793/zep-18-amelioration-de-lergonomie-de-validation/#p32981).

**Comment by artragis** [comment]
> l faudrait pour cela lier le tutoriel avec le sujet de la bêta.

#2956

**Comment by GerardPaligot** [comment]
Le lien est maintenant disponible depuis le merge de la ZEP-12.
