### ISSUE TITLE
La page d'erreur 500 doit être du html seul, sans langage de template django

### ISSUE THREAD

**Issue by Nodraak** [zestedesavoir/zds-site#2957]
Ca cest le mal : https://github.com/zestedesavoir/zds-site/blob/dev/templates/500.html
Si le serveur plante vraiment, django ne peut même plus interpréter les templates, et on obtient ça :
![screenshot](https://cloud.githubusercontent.com/assets/4773741/9135567/3abd63f8-3d0f-11e5-9254-1c01b3da89a5.png)
La page qu'il faudrait utiliser à la place [existe déjà](https://github.com/zestedesavoir/zds-site/blob/dev/errors/500.html). Il faudrait modifier la [conf nginx](https://github.com/zestedesavoir/zds-site/blob/dev/doc/source/install/deploy-in-production.rst#nginx) : a priori la ligne `root /opt/zdsenv/ZesteDeSavoir/templates/;` pour retourner la bonne page.

**Comment by WinXaito** [comment]
C'est présent à chaque Erreur 500 ? Est-ce que le problème est régulier / Arrive souvent ?

[edit]  
https://github.com/zestedesavoir/zds-site/issues/2543 J'avais déjà ouvert une issue pareil, je propose éventuellement de réouvrir celle-là pour avoir ce qui a déjà été dit.

**Comment by Nodraak** [comment]
> présent à chaque Erreur 500 ?

J'imagine que oui, mais j'ai pas l'habitude de me prendre des erreurs 500 ^^

En tout cas c'est pas dans les bonnes pratiques d'avoir une page d'erreur 500 qui a besoin de django pour être rendue, puisque son but est justement d'être affichée quand django plante.

**Comment by WinXaito** [comment]
En effet, je n'ai encore jamais eu vu cette proposition qui me semble bonne.

(On peu garder le code de la 500 actuel et simplement copier le code source une fois rendu .. histoire que si un style change on puisse mettre l'erreur 500 à jour sans trop de problème)

**Comment by Situphen** [comment]
En fait, il y a deux pages d'erreur 500 : une statique et une dynamique avec Django.

Je crois que ça se passe comme ça : si un bug dans le code python provoque une 500, la page dynamique est appelée ; si tout le site est cassé (par exemple un problème de connexion entre nginx et Gunicorn, deux logiciels sur le serveur), la page 500 statique s'affiche. Malheureusement, il arrive qu'un des _workers_ de Gunicorn (qui fait la liaison entre nginx et Python) plante, que ça génère une erreur 500 et que la page 500 dynamique soit appelée sans être passée par Django. C'est ce dernier cas qu'il faut résoudre.

**Comment by SpaceFox** [comment]
Sinon on ne se prends pas le chou et on décide que « erreur 500 --> page
d'erreur statique ».

**Comment by WinXaito** [comment]
> Sinon on ne se prends pas le chou et on décide que « erreur 500 --> page d'erreur statique ».

ça serait la solution la plus sur

**Comment by Situphen** [comment]
On ne peut pas rendre statique la page dynamique car : elle ne sera plus dynamique ; ça fera doublon avec l'actuelle page statique. L'avantage de la page dynamique (quand on peut l'afficher correctement) est que contrairement à la page statique elle contient le menu, les notifications, le nombre de messages privés, etc. L'utilisateur est donc moins perdu !

**Comment by WinXaito** [comment]
> On ne peut pas rendre statique la page dynamique car : elle ne sera plus dynamique ; ça fera doublon avec l'actuelle page statique. L'avantage de la page dynamique (quand on peut l'afficher correctement) est que contrairement à la page statique elle contient le menu, les notifications, le nombre de messages privés, etc. L'utilisateur est donc moins perdu !

On ne peut pas ajouter un menu sur la 500 ? Et pour les notification mettre un bouton du type `Retantez un chargement de la page` ?

**Comment by SpaceFox** [comment]
Très honnêtement, je ne vois pas l'intérêt d'une page d'erreur dynamique, surtout dans le cas d'une erreur 500.

**Comment by Nodraak** [comment]
Une page 500 peut potentiellement être appelée sans django de disponible, il ne faut donc rien faire qui depende de django.

Situphen a écrit :

> [...] L'utilisateur est donc moins perdu !

Je suis d'accord que l'utilisateur est moins perdu, mais une erreur 500 n'arrive pas à chaque requête (enfin j'espère !). En plus on a les couleurs et le logo de zds, avec un gentil message et un lien vers la page d'acueil ca devrait aller

**Comment by Situphen** [comment]
> Je suis d'accord que l'utilisateur est moins perdu, mais une erreur 500 n'arrive pas à chaque requête (enfin j'espère !). En plus on a les couleurs et le logo de zds, avec un gentil message et un lien vers la page d'acueil ca devrait aller

Oui ça ira très bien. Je soulignait juste que la page 500 dynamique est utile mais si on ne peut pas la laisser sans se casser la tête, virons-là !

**Comment by sandhose** [comment]
Je viens de voir en préprod, c'est le `templates/` qui est utilisé en root pour les erreurs 500, alors que ça devrait être `errors/`...

Du coup, pour fixer ça, en préprod j'ai changé ce bloc:

```
    # Error pages
    error_page 500 502 503 504 /500.html;
    location /500.html {
        root /opt/zdsenv/ZesteDeSavoir/templates/;
    }
```

par

```
    # Error pages
    error_page 500 502 503 504 /errors/500.html;
    location /errors/ {
        alias /opt/zdsenv/ZesteDeSavoir/errors/;
    }
```

Pourquoi `alias` plutôt que `root` ? Parce que y'a aussi les images + css des erreurs qui sont la dedans et qui doivent être accessibles

---

ping @SpaceFox @Un-Cornichon : l'un de vous peut faire la modif en prod ?

**Comment by Situphen** [comment]
`/nick MrDocumentation`
et faudra une PR qui modifie la doc pour quelle soit à jour !
`/nick situphen`

**Comment by sandhose** [comment]
hum, autant faire ça dans la #2918 ? (si elle bouge un jour celle la :v )

**Comment by Situphen** [comment]
oui, pourquoi pas !

**Comment by yapper-git** [comment]
On a droit à une erreur 500 remplie de template Django aujourd'hui :

```
{% extends "base.html" %} {% load i18n %} {% block title %} {% trans "Erreur 500" %} {% endblock %} {% block headline %} {% trans "Erreur 500" %} {% endblock %} {% block breadcrumb %}
{% trans "Erreur 500" %}
{% endblock %} {# No sidebar on this page #} {% block body_class %}no-sidebar{% endblock %} {% block sidebar %}{% endblock %} {% block content %}

{% blocktrans with url_forum=app.site.forum_feedback_users %} Si vous voyez cette page, c'est que vous avez trouvÃ© un bug. Merci de rapporter cette erreur en expliquant comment vous avez procÃ©dÃ© pour tomber sur cette page en crÃ©ant un sujet sur le forum Bugs et Suggestions. Merci de votre aide {% endblocktrans %} !

{% blocktrans with url_bugtracker=app.site.bugtracker %} Si vous Ãªtes curieux, voici une liste des sujets ouverts Ã  ce propos sur le bug tracker public de l'association {% endblocktrans %}.
{% endblock %}
```

**Comment by artragis** [comment]
Si mes souvenirs sont justes cela a été changé lorsque l'ancien serveur a crashé, aujourd'hui les pages 500 ne sont plus générées à la volée, non? @sandhose @Eskimon ?

**Comment by Eskimon** [comment]
:-° faudrait générer une 500 sur la beta pour voir... @firm1 il sait bien faire ca :)

**Comment by firm1** [comment]
[facile](https://beta.zestedesavoir.com/contenus/reactions/ajouter/?cite=75912&pk=205)

**Comment by Eskimon** [comment]
Ca semble bon alors...

Ca a été reporté en prod' un jour pour valider la correction ?

**Comment by Situphen** [comment]
@Eskimon Euh, là c'est le _template_ qui est affiché donc je ne crois pas que ce soit bon !

**Comment by pierre-24** [comment]
Si jamais, oui, le bug de Firm1 est déjà corrigé ;) (c'est pour la prochaine RC)

**Comment by Eskimon** [comment]
En fait c'est bon, j'ai eu une autre 500 pour autre chose qui était bien la bonne page :)

**Comment by Situphen** [comment]
Justement le ticket est à pour avoir la même erreur 500 partout ! Donc ce n'est pas réglé (sur la beta au moins).

**Comment by Eskimon** [comment]
hum... est-ce pertinent ? Si une "grosse erreur 500" apparait on ne peut pas afficher le site normalement (car Django pété), mais si c'est une "petite 500" alors c'est quand même "moins pire" d'avoir au moins tout ce qui va avec le site non ?

**Comment by Situphen** [comment]
C'est ce qu'on a actuellement ! Sauf que quand c'est Gunicorn qui pète, il affiche l'erreur 500 "dynamique" mais sans la passer à Django donc on se retrouve avec du texte de _template_ (comme l'image tout en haut du ticket)  !

**Comment by Eskimon** [comment]
He bien justement non, plus maintenant sur la beta. À la place on a un truc full page qui fait propre :)

**Comment by Situphen** [comment]
Là c'est parce qu Gunicorn n'est pas pété. Ou sinon faut m'expliquer comment vous avez fait car là je vois pas comment c'est possible !

**Comment by Eskimon** [comment]
En publiant un tuto un peu gros je me prend automatiquement un timeout ;)

**Comment by pierre-24** [comment]
On sait :)

**Comment by Eskimon** [comment]
Apparemment pas tous ^^ Je parlais juste de ca pour justifier mes experiences des différents types d'erreur 500 ^^

**Comment by Eskimon** [comment]
Il me semble que tout est bon ici non ? Qqun saurait générer les deux types de 500
1. Lorsque c'est un souci de notre code (mais normalement c'est rare ^^ )
2. Lorsque c'est un souci au dela de notre code (timeout ou worker planté)

**Comment by Nodraak** [comment]
Il faudrait qq un qui a accès à la beta, pour :
1. Lever une exception quelconque : erreur de syntaxe, vue Django qui retourne `None`, ...
2. Arrêter Gunicorn sans toucher à nginx

**Comment by sandhose** [comment]
Done.
![image](https://cloud.githubusercontent.com/assets/1549952/10868971/97c9888c-809f-11e5-878f-b633c0c9d624.png)

**Comment by sandhose** [comment]
Ok, on a testé avec @Nodraak, pour l'instant, si c'est Django qui renvoi une 500, on a le template 500 de Django (ce qui est pas bon, puisque du coup, si le template 500 plante, par exemple, on a une magnifique `Internal server error`.)

Du coup, il faut ajouter la directive `proxy_intercept_errors on;` au bloc `location /` dans `/etc/nginx/sites-available/zestedesavoir`, pour que quand le code d'erreur est égal à `50{0,2,3,4}` (les valeurs spécifiés par la directive `error_page`), ce soit nginx qui s'occupe de la page d'erreur. C'est en place sur la bêta du coup, faut que quelqu'un fasse pareil sur la prod

**Comment by Eskimon** [comment]
normalement c'est bon.

**Comment by Situphen** [comment]
Désolé de UP, mais [le template Django `500.html`](https://github.com/zestedesavoir/zds-site/blob/dev/templates/500.html) sert encore à quelque chose ?

**Comment by gustavi** [comment]
Normalement oui

**Comment by Nodraak** [comment]
Je dirais oui aussi.

Si Django plante, il vas d'abord essayer d'interpréter ce template. Si Django est vraiment bien planté, nginx detecte que Django est mort et vas alors servir la page d'erreur statique.

**Comment by sandhose** [comment]
Normalement non.

Parce que si Django renvoie une 500 à nginx ou lui fait un timeout, nginx va de toutes façons servir la 500 statique, indépendamment de si Django a renvoyé quelque chose ou non. Normalement.

**Comment by Nodraak** [comment]
Après avoir testé, je confirme que Django interprete le template 500.html, et que Nginx le renvoie correctement.

Si on retire ce template (et éventuellement la ligne `handler500 = "zds.pages.views.custom_error_500"` de `zds/urls.py`), Nginx retournera quoi qu'il arrive la page d'erreur statique.
