### ISSUE TITLE
zds down en production

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2958]
LeLeite zds est down depuis environ 1h, la page d'erreur 500 ne fonctionne pas. On dirait qu'il s'agit d'un probleme de niveau infra.

Etant donné qu'il n y a plus de moyens de communication (mp innaccessible) j'ouvre cette issue (bloquante) pour tenir au courant la communauté.

**Comment by Situphen** [comment]
Pour ce qui est de la page d'erreur qui ne s'affiche pas correctement, c'est #2957 qu'il faut regarder !

**Comment by Eskimon** [comment]
On m'a dit sur Twitter que c'était probablement un souci d'hébergeur,  ca semble cohérent vu que la release récente n'a pas encore été faite...

**Comment by WinXaito** [comment]
Ah ben voilà pourquoi ça mouline dans le vide xD J'ai tort de toujours accusé ma connexion èé

**Comment by WinXaito** [comment]
Hm je viens de remarquer que le site n'est pas down, seulement MEGA lent (Analyse réseau avec firefox, résultat 2min39 pour charger la page :))

Edit: Une moyenne de chargement de 3min à 6min pour afficher la page la ... Par contre je comprend pas pourquoi je me choppe pas un "Timeout" ou quelque chose du genre avant...

**Comment by Eskimon** [comment]
à priori : http://travaux.ovh.net/?do=details&id=14354

**Comment by DevHugo** [comment]
Plus qu'a attendre donc.

**Comment by Fumble** [comment]
Ca semblait être revenu ce matin, mais là, c'est reparti pour un tour.

**Comment by WinXaito** [comment]
Ce n'est plus les 6min de hier, mais la j'ai encore de 3 à 20 sec de chargement quand tout vas bien

**Comment by DevHugo** [comment]
Ça à l'air d'aller mieux depuis hier ~23h. Depuis le reboot des machines par OVH.

**Comment by DevHugo** [comment]
et ça recommence !

**Comment by DevHugo** [comment]
Down en prod ! C'est prévu en maintenance, ce soir ?

**Comment by RignonNoel** [comment]
Hum ce n'est donc pas de mon côté... Moi qui cherche comme un idiot depuis 30minutes..
Vous avez penser a faire un serveur de status dans le futur? Histoire que l'on trouve facilement si c'est vos service ou nous le problème.

**Comment by devock** [comment]
La maintenance a été "forcée" par ovh, l'installation du nouveau serveur est en cours par SpaceFox !

**Comment by DevHugo** [comment]
On dit 'Merci' Spacefox ^^ ! 

On pourrais mettre une page de status sur le serveur de la beta si y'en a pour qui trouvent ça utile.

**Comment by Augustin-FL** [comment]
en attendant, a défaut d'avoir une page de statut, on peux utiliser [ce site](http://isup.me/zestedesavoir.com)

**Comment by Situphen** [comment]
Ou sinon on peut aussi [rechercher "is zestedesavoir.com down" sur DuckDuckGo](https://duckduckgo.com/?q=is+zestedesavoir.com+down&ia=answer) ! ;)

**Comment by devock** [comment]
Pour info, la propagation des DNS est en cours (ça a sévèrement merdé au niveau d'ovh, en mode "simple" on avait l'impression d'avoir modifié des DNS, mais on a vu par hasard qu'en mode textuel la zone dns n'avait pas été modifiée...).
Pour le moment, il n'y a pas d'https (vos navigateurs vont surement vous forcer vers le https), SpaceFox regarde ça au plus vite.
Il manquera la recherche aussi, mais SpaceFox n'a pas eu le temps de réinstaller ça. 

Donc si cela se trouve vous y avez de nouveau accès en http.

**Comment by Situphen** [comment]
Chez moi en navigation privée, Firefox ne force pas l'HTTPS donc j'ai pu y accéder. Le site est super rapide !

Pour information, la version déployée est `15.6-cedrat` alors que ça aurait dû être `15.6b-cedrat` mais je ne vais pas chipoter sur ça. :)

**Comment by pierre-24** [comment]
Plus que ça, on a une v15.7 qui n'attend que d'être déployée :p

**Comment by DevHugo** [comment]
Pour forcer chrome à ne pus vous rediriger vers le site http, vous pouvez suivre ces instructions:
- Taper dans votre barre d'adresse: `chrome://net-internals`
- Dans le menu déroulant en haut à gauche, sélectionner "HSTS"
- Entrer zestedesavoir.com dans le champ dans la section Delete domain et appuyer sur le bouton delete domain.

Source: http://superuser.com/questions/565409/chrome-how-to-stop-redirect-from-http-to-https

**Comment by SpaceFox** [comment]
Le HTTPS est de retour, mais en auto-signé. @Ge0 tu as eu mon message ?

**Comment by SpaceFox** [comment]
J'ai redéployé la v15.6b-cedrat

**Comment by Situphen** [comment]
@SpaceFox, tu as pas vu ça ? :)

> Plus que ça, on a une v15.7 qui n'attend que d'être déployée :p

**Comment by SpaceFox** [comment]
Si. Mais c'est hors de question que je fasse ça tant que la plate-forme n'est pas stabilisée.

**Comment by pierre-24** [comment]
C'est sage.

**Comment by SpaceFox** [comment]
![wget_page-day](https://cloud.githubusercontent.com/assets/5786268/9356678/a20a8884-4682-11e5-8bb9-d25838c9a9ee.png)

**Comment by DevHugo** [comment]
Quand la plateforme sera stabilisé, cela sera possible de récupérer à la main, les modifications sur les tutos ? Genre un diff aux auteurs.

**Comment by accor-ecocea** [comment]
> Quand la plateforme sera stabilisé, cela sera possible de récupérer à la main, les modifications sur les tutos ? Genre un diff aux auteurs.

Comment ça ?

**Comment by SpaceFox** [comment]
Comment ça ?

**Comment by DevHugo** [comment]
Y'a des auteurs qui se plaignent, qu'une partie de leurs contenu rédigé un peu avant la maintenance, on disparu (voir avec carnufex).

L'idée était de sélectionner les commits entre la sauvegarde d'hier, trois heures du mat, de généré un diff et de l'appliquer à la demande des auteurs.

**Comment by SpaceFox** [comment]
Hélas non. « Les données du 18/08 entre 3h du matin et minuit, heure de Paris, sont perdues. » ça veut très exactement dire ce que ça veut dire… on ne peut rien faire.

**Comment by Davidbrcz** [comment]
Firefox 40 : 
Le site est inaccessible à cause du certificat SSL auto signé et de l'utilisation de HSTS. y'a pas moyen d'ajouter une exception de sécurité. Par contre ca marche en navigation privée (va comprendre). Donc le site est techniquement up, mais en fait non...

**Comment by RignonNoel** [comment]
C'est vraiment bizarre que en mode navigation privé il ne détecte pas cela... Je connaissait pas l'astuce.
Cependant j'éviterai de trop utiliser l'astuce qui te met dans l'insécurité :/

**Comment by Situphen** [comment]
> l'astuce qui te met dans l'insécurité :/

??

**Comment by RignonNoel** [comment]
Bah je sais pas comment tu appel une astuce qui t'amène peut être sur une copie qui se fait passer pour le site officiel.
Une clef c'est pas juste pour payer des factures en plus, c'est aussi pour des raisons de sécurité.

**Comment by DevHugo** [comment]
Tu peux aussi désactiver HSTS pour le domaine zestedesavoir.com comme ça, tu as toujours ton empreinte qui est checké.

**Comment by RignonNoel** [comment]
@DevHugo Ouais enfin a ce rythme autant le désactiver dans Apache plutôt que de demander a tout les utilisateurs de faire une manip.

En général on évite de demander à tout le monde de baisser le bouclier.

**Comment by artragis** [comment]
- on est sur nginx
- c'est un imprévu
- on est en train de le régler ce problème, on n'a juste aucun ETA parce que c'est IMPREVU
- passer en http c'est pas baisser le bouclier, c'est aller s'empaler sur l'épée adverse
- laissons le temps aux sysadmin, ils font tout leur possible.

**Comment by SpaceFox** [comment]
Et à ma connaissance HSTS _est_ désactivé sur le serveur, mais le client ne le sait pas tant qu'on a pas oublié le site…

Ping @Un-Cornichon pour confirmation

**Comment by ghost** [comment]
C'est exactement le principe de HSTS, qui est prévu pour fonctionner commer ça. Le principe de HSTS est d'ajouter une entête qui dit "je sais faire du HTTPS pendant au moins x mois" (la durée est en générale de un an). Ceci permet de faire en sorte, que quoi qu'il arrive le navigateur se connecte en HTTPS même quand on lui demande du HTTP, et vérifie ainsi, via le certificat, l'identité du serveur.
Ça ajoute donc un niveau de sécurité non négligeable pour les utilisateurs en temps normal, mais présente donc effectivement des problèmes lors d'un incident comme celui que nous avons actuellement.

Je confirme que HSTS est désactivé actuellement sur le serveur, mais une fois encore, c'est prévu pour fonctionner comme ça, si ça n'était pas une panne mais une attaque, on en serait fort content. À noter que HSTS nécessite d'avoir un certificat valide et signé par une autorité connu. Ça peut sembler criticable (et ça l'est), mais c'est cohérent avec le fonctionnement actuel du système de sécurité que sont les certificat et les authorités de certification.

**Comment by ghost** [comment]
@RignonNoel Passer en navigation privée n'est pas une « astuce » pour que le HSTS ne fonctionne pas. 
Les navigateurs en mode privé ne garde aucun cache d'une session à l'autre, et n'utilise pas le cache du mode classique, et donc oui mécaniquement le HSTS est inutile puisque c'est typiquement une information gardée sur le long terme dans un coin du navigateur « tiens je sais que lui il faut lui parler en HTTPS ». Tu auras exactement le même « problème » si tu vides ton cache et historique, ton navigateur n'aura plus l'information, jusqu'à ce que tu re accèdes au site en HTTPS et que celui ci te présente l'entête HSTS qui va bien.

Mais c'est un choix que tu fais plainement et volontairement. C'est le principe même de la navigation privée : ne pas laisser de trace en local.

**Comment by Augustin-FL** [comment]
Question : pourquoi a on remis un certificat autosigné et non le certificat original?

Ou même en admettant que que personne n'ait conservé de sauvegarde du certificat original/que la personne qui la détient ne soit pas joignable/etc... Est ce qu'il ne serait pas mieux de racheter un certificat chez OVH ? (ou même de s'en faire un gratuitement sur [GlobalSign](https://www.globalsign.com/en/ssl/ssl-open-source/) ou [startSSL](https://www.startssl.com/?lang=fr), carrément?)

**Comment by RignonNoel** [comment]
@Un-Cornichon Oui c'est ce que j'ai cru comprendre au fur et a mesure des réponse. Je pensais que la navigation privé utilisé quand même le cache existant mais simplement ne le modifier pas. Merci de cette précision ;)

**Comment by ghost** [comment]
@gusfl Parce que nous n'avons plus le certificat original, et un certificat signé arrive.

**Comment by SpaceFox** [comment]
> **Overall Rating A+**
> 
> This server supports TLS_FALLBACK_SCSV to prevent protocol downgrade attacks.
> This server supports HTTP Strict Transport Security with long duration. Grade set to A+.

Source : https://www.ssllabs.com/ssltest/analyze.html?d=zestedesavoir.com

Du coup, je ferme ici \o/
