### ISSUE TITLE
Erreur 500 si un fichier HTML n'existe pas

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2959]
Via SENTRY (http://sentry.sandhose.fr/zeste-de-savoir/backend/group/60/)

> IOError: [Errno 2] No such file or directory: u'/opt/zdsenv/ZesteDeSavoir/tutoriels-public/296_wamp-developper-avec-php-ajax-html-sous-windows/392_lenvironnement/2280_wamp/introduction.md.html'

**Comment by Situphen** [comment]
Pourquoi ce fichier est inexistant ? A quoi correspond-t-il ?

**Comment by pierre-24** [comment]
> Pourquoi ce fichier est inexistant

_No fucking idea_. Il est généré à la publication, va savoir pourquoi il a disparu. 

>  A quoi correspond-t-il ?

Le texte d'introduction parsé en HTML et près à être affiché si nécessaire.

À noter qu'un bugfix temporaire est de republier le tuto en question, à priori.

**Comment by Ymox** [comment]
Si je comprends bien, si le tutoriel n'est actuellement plus accessible aux 3/4, c'est parce qu'on est en attente de la ZEP-12 ?

Pour éventuellement aider, les chapitres qui posent problème n'ont pas été édité directement (du moins pas que je m'en souvienne – comprendre par là qu'il n'y a pas eu de modification des introductions et conclusions), mais en revanche tous les chapitres actuellement inaccessibles ont vu un ou plusieurs de leurs extraits modifiés. Je crois bien qu'Arius a tenté plusieurs fois de valider, mais apparemment ça ne regénère pas les fichiers manquants, vu que l'erreur persiste. Nous n'avons plus que la version offline (correspondant à la version en validation) qui fonctionne.

**Comment by Situphen** [comment]
> Si je comprends bien, si le tutoriel n'est actuellement plus accessible aux 3/4, c'est parce qu'on est en attente de la ZEP-12 ?

Non, c'est plutôt "on ne sait pas pourquoi ce bug arrive mais la ZEP 12 résout ça normalement".

**Comment by pierre-24** [comment]
De manière générale, j'ai l'impression que les tutos ont pas aimé du tout le changement de serveur et les bugs à répétitions. La ZEP-12 devrait régler ça parce qu'on en profite pour "nettoyer" les dépôt, donc ça devrait aller mieux. Mais c'est vrai que c'est particulièrement pénible pour les auteurs. Si quelqu'un a accès à la prod, ça vaudrait le coup d'aller faire un tour dans le dépot et de faire un `git status`.

**Comment by GerardPaligot** [comment]
@pierre-24 @artragis Est-ce que cette issue est devenue obsolète ou non avec le merge de la ZEP-12 ?

**Comment by GerardPaligot** [comment]
Dans tous les cas, je retire le bug facile.

**Comment by artragis** [comment]
ça fait une 404 (c'est ce qu'on attend, surtout dans la zep-12 qui prégénère chaque chapitre en entier) donc on peut fermer.

En tout cas les tutos qui était touchés par ce bug ont bien été rerendu disponibles par la migration zep-12 quand les sources étaient encore dispo sur le filesystème. Tu peux fermer.
