### ISSUE TITLE
Page de présentation de Markdown

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#296]
Le site a une page de présentation du Markdown à cette adresse : /pages/markdown

La meilleure idée me semble de la garder, mais dans ce cas il faudra la mettre à jour :
- Pour supprimer les références à ProgDuPeupl
- Pour y inclure nos spécificités

**Comment by cgabard** [comment]
@ShigeruM a commencé a faire une page/tuto sur notre markdown. Une pré-version est dans les fixtures du site. Depuis il a ajouté des trucs et devait l'avoir mit en tuto. Il faudrait qu'il nous dise ce qu'il en est !

**Comment by ShigeruM** [comment]
Ce que j'ai fait est en ligne sur la pré-prod sous la forme d'un article :
http://preprod.zestedesavoir.com/articles/21/rediger-sur-zds

Comme ce n'est qu'une pré-prod, je garde bien sûr une version bien au chaud
chez moi.

Normalement c'est à jour. En tout cas je ne crois pas avoir vu passer de
modification de syntaxe impactante. Si j'ai loupé un truc, n'hésitez pas à
me le dire et je mettrai à jour.

Le 14 avril 2014 09:27, Christophe Gabard notifications@github.com a
écrit :

**Comment by SpaceFox** [comment]
J'ai supprimé la page HTML statique puisqu'on a un bel article dynamique pour ça :)

**Comment by SpaceFox** [comment]
Corrigé et mergé.
