### ISSUE TITLE
Erreur avec SMTP sur la prod'

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2961]
Je cite Sentry:

> SMTP AUTH extension not supported by server.
> Source: [là](http://sentry.sandhose.fr/zeste-de-savoir/backend/group/86/)

**Comment by SpaceFox** [comment]
C'est bloquant parce que les nouveaux inscrits ne peuvent plus s'identifier…

**Comment by Situphen** [comment]
Et aussi parce que dans certains cas, il y a l'air d'avoir des erreurs 500 lors de la création d'un message sur le forum !

**Comment by SpaceFox** [comment]
Ouais, et là y'a aussi de la correction de code à faire…

**Comment by pierre-24** [comment]
?

**Comment by Situphen** [comment]
Je suppose que @SpaceFox veut dire qu'il ne devrait jamais avoir d'erreurs 500 (et qu'il faut modifier le code en conséquence) !

**Comment by SpaceFox** [comment]
Et surtout que « échouer à envoyer un mail » n'est pas une raison valable pour empêcher de poster !

**Comment by pierre-24** [comment]
Du coup, on est bon, non ?

**Comment by Situphen** [comment]
Normalement oui
