### ISSUE TITLE
On ne peut plus envoyer d'images (plus de miniature générées)

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#2962]
J'ai essayé d'envoyer une image, aucune miniature n'a été générée.

**Comment by pierre-24** [comment]
Écartons l'obvious: on a bien toutes les libraires jpg, png et consoeur ?

**Comment by Situphen** [comment]
Je cite @SpaceFox :

```
[23:08] <spacefox> le certif et les mails sont bloquants, pas les images
```

Bien que cela reste gênant et à résoudre, ce n'est pas bloquant.

**Comment by pierre-24** [comment]
J'ajoute que les miniatures de png fonctionnent, celles de JPEG pas.

**Comment by SpaceFox** [comment]
`libjpeg8` a disparu de Debian 8, et le remplaçant que j'ai vu n'a pas l'air de fonctionner.

En même temps c'est louche car de mémoire Pillow mettait 10 ans à s'installer avec pip mais là c'est presque instantané.

**Comment by pierre-24** [comment]
C'est bloquant, en fait: si quelqu'un vient à changer son icône, son article/tuto devient inacessible, mais aussi la page de demande d'aide si il demande de l'aide, la page des bêta de l'auteur si le tuto est en bêta, et je vous laisse imaginer ce qui arrive si le tuto/l'article est publié, voir en page d'acceil (je rappelle que cette information n'est pas versionnée, donc a un effet immédiat).

**Comment by pierre-24** [comment]
C'est bloquant. Blackline est complètement coincé, il ne peut plus rien faire, parce qu'il a eu le malheur de changer de miniature. Et quand je dis plus rien, c'est plus moyen d'accéder à aucun de ces tutos.

**Comment by SpaceFox** [comment]
J'ai bien compris, mais je n'ai aucune idée là…

**Comment by pierre-24** [comment]
Ben j'en ai bien, mais c'est cochon dans tout les cas:
1. Reprendre les paquets qui vont bien de _wheezy_ et tenter une installation en croisant les doigts
2. Trouver un remplacant (la librairie peut pas avoir changé de spec' d'un coup) et faire un `ln -s` qui va bien
3. Trouver un remplacant à Pillow

Aucune solution ne m'enchante particulièrement.

[sur le RTD  de pillow](http://pillow.readthedocs.org/en/latest/installation.html), ils mentionnent que pour eux, la libjpeg 6, 8 et 9 fonctionne. Y'a aussi moyen d'essayer avec [la version turbo](https://packages.debian.org/jessie/libjpeg62-turbo). J'ai malheureusement fait l'erreur de passer de Debian 8 à Mint, donc je peux pas tester moi-même, mais si vraiment t'as peur de bousiller la prod', je peux me faire une virtualbox.

**Comment by SpaceFox** [comment]
> Reprendre les paquets qui vont bien de wheezy et tenter une installation en croisant les doigts

No way.

> Trouver un remplacant à Pillow

J'y crois pas

Pour le reste j'attends que ma sauvegarde forcée se finisse.

**Comment by pierre-24** [comment]
[on peut aussi aller chercher les paquets dans _stretch_](https://packages.debian.org/search?searchon=names&keywords=libjpeg), mais c'est probablement non aussi ^^

**Comment by Situphen** [comment]
Vous savez comment son gérer les paquets sur Debian ? Dans le meilleur des cas, il faudrait demander aux personnes qui gèrent `lbjpeg8` de le rendre disponible pour Jessie.

**Comment by pierre-24** [comment]
Ou pire encore, on peut compiler la lib nous-même.

**Comment by pierre-24** [comment]
Mais plus sérieusement, [la turbo](https://packages.debian.org/jessie/amd64/libjpeg62-turbo-dev/filelist) semble proposer une version très proche [de l'ancienne 8 de wheezy](https://packages.debian.org/wheezy/amd64/libjpeg8-dev/filelist).

**Comment by SpaceFox** [comment]
Je vais essayer des trucs.

2015-08-22 0:28 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by SpaceFox** [comment]
Et je sais pour la turbo : https://github.com/zestedesavoir/zds-site/issues/2962#issuecomment-133200375

**Comment by SpaceFox** [comment]
Les versions récentes de Ubuntu ou Linux nécessitent de créer des liens à la main :

```
sudo ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib
sudo ln -s /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib
sudo ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib
```

Normalement ça fonctionne, pouvez-vous confirmer ?

**Comment by pierre-24** [comment]
ça fonctionne très bien. Faut éditer la doc pour le noter :)

**Comment by Situphen** [comment]
Du coup le bug est résolu ? Il était bizarre.

**Comment by pierre-24** [comment]
Ben c'était un bug infra, quoi, pas de code.

**Comment by Situphen** [comment]
En gros, le paquet `libjpeg8` créait les liens symboliques à l'installation mais vu qu'on utilise le turbo, il faut les faire à la main ? Ou on les avait fait à la main sur l'ancien serveur et on a oublié de le mettre dans la doc ?

**Comment by pierre-24** [comment]
Surtout que le paquet `libjpeg8` n'existe plus dans Debian 8, donc il a fallu employer une autre librairie et créer des liens pour que Pillow soit pas perdu.

**Comment by Situphen** [comment]
Je réouvre car c'est plutôt Bloquant ! Plus d'infos [ici](https://zestedesavoir.com/forums/sujet/3991/erreur-500-lorsque-jessaye-dacceder-a-ma-gallerie/?page=2#p72889)

**Comment by Eskimon** [comment]
normalement tout est OK :)
