### ISSUE TITLE
Réception d'un message lors d'un post

### ISSUE THREAD

**Issue by GuillaumeGomez** [zestedesavoir/zds-site#2965]
Bonjour,

Je me suis rendu compte à plusieurs reprises que je recevais un mail me disant qu'il y avait un nouveau message dans une discussion (privée entre plusieurs membres) alors que c'était moi qui venait de poster. Serait-il possible d'enlever l'envoi de mail lorsque c'est nous-même qui postons le message (ou au moins ajouter une option le permettant) ?

Merci d'avance !

**Comment by Vayel** [comment]
Ce bug est [connu](https://zestedesavoir.com/forums/sujet/3578/alerte-email-message-prive/). :)

**Comment by Situphen** [comment]
Étant donné que c'est un doublon de #2905, je ferme ici. La discussion peut continuer sur le forum ou sur l'autre ticket.
