### ISSUE TITLE
La page de roadmap

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#297]
Le site a une page de roadmap ici : /pages/roadmap

Est-ce qu'on la garde ?
Si oui, qui la maintient à jour ?

**Comment by cgabard** [comment]
Hum... Je ne sais pas si une roadmap est une si bonne idée. Rien qu'a voir nos dev, ils ne pas réguliers et les fonctionnalités viennent en fonction des besoins et envies. Les seuls trucs qui sont prévisibles se sont les resolutions de bugs.

Je serais plus pour qu'on fasse une news régulièrement, genre avant/apres chaque mis a jour de master, qui recense les dernières modifs et ce qui est prévu de changer

**Comment by ShigeruM** [comment]
Je me permets un +1 à mon voisin du dessus. Une roadmap sans assurance que
les annonces seront livrées dans les temps, c'est casse-gueule.

Le 14 avril 2014 09:26, Christophe Gabard notifications@github.com a
écrit :

**Comment by SpaceFox** [comment]
Je note : supprimer la roadmap ce soir :) (je suis d'accord avec vous)

**Comment by SpaceFox** [comment]
Fait et poussé sur la branche issues_pages_statiques, mais pas encore mergé dans dev (on pourrait tant qu'on ne supprime pas cette branche avant que ces issues ne soient toutes fermées)

**Comment by SpaceFox** [comment]
Corrigé et mergé.
