### ISSUE TITLE
Correction de couleur dans le footer

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2971]
Comme l'a fait remarquer Wizix https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=32#p70984 les séparations du footer ne sont pas de la même couleur que le reste.

Edit: Sur version mobile j'ai oublier de préciser

Qu'en pensez-vous ? Est-ce voulu ? 

Sinon on peut m'attribuer l'issue et je corrigerai ça.

**Comment by Situphen** [comment]
Merci @WinXaito :)
