### ISSUE TITLE
Le pseudo du membre qui s'affiche mal dans la liste des tutoriel

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2973]
Url incriminée : http://zestedesavoir.com/tutoriels/?tag=c-sharp

On voit que le membre dont le pseudo est `Bat'` se retrouve avec le pseudo `Bat&#39;`.

**Comment by WinXaito** [comment]
C'était pas déjà signaler ça ? En tout cas il me semble déjà avoir vu trace de ce bug.

**Comment by yapper-git** [comment]
> C'était pas déjà signaler ça ? En tout cas il me semble déjà avoir vu trace de ce bug.

En effet cela semble identique à l'issue #2900 (voir aussi la PR #2951 correspondante).

**Comment by Situphen** [comment]
Étant donné que c'est normalement corrigé dans `upstream/dev`, je me permets de fermer le ticket ! Puis de toutes façons c'est un doublon de #2900.
