### ISSUE TITLE
Retardement dans l'affichage des boutons de l'éditeur

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2975]
Les boutons de l'éditeur apparaissent 0,5 - 1 seconde après le chargement de la page ce qui provoque des décalages assez genant.

Et je prend directement cette issue en charge, enfin du moins je vais essayer selon ce que @artragis m'a donné comme indication.

++

**Comment by Situphen** [comment]
C'est normal car l'éditeur est codé en Javascript donc il y a un temps d'attente entre l'affichage de la page et l'exécution du code JS.

**Comment by WinXaito** [comment]
Artragis ne m'as pourtant pas parler de cela est semblais assez sur de la source puisque c'est lui qui avait codé cette parti. Mais ma correction se fera côté Django ... donc j'ai justement un doute. Mais dans tous les cas supprimer quelque chose d'inutile est toujours mieux

**Comment by pierre-24** [comment]
Je crois que tu confond d'issue, en fait. @artragis parlait d'un autre problème :-°

**Comment by WinXaito** [comment]
Euh sur ? Ou alors j'ai très mal compris

[edit]
Moi vais aller faire dodo la, j'aurai eu l'air assez con comme ça...

**Comment by pierre-24** [comment]
Il y a eu quiproquo, de fait :)
