### ISSUE TITLE
Le serveur mail de la preprod ne fonctionne plus

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2976]
Le serveur mail n'est plus fonctionnel sur la beta ce qui provoque des erreur 500 sur certaines fonctions, et surtout empêche de réaliser certains tests.

Il faut savoir que ce serveur (de preprod) passe par celui de la prod à travers un utilisateur. Et suite à la réinstallation du serveur de prod, le serveur mail n'a visiblement pas été configuré (l'utilisateur en question ne doit pas exister avec le mot de passe qui va bien). Un problème infra donc

**Comment by SpaceFox** [comment]
Personnellement j'ignorais l'existence de ce rebond (et je ne vois pas sa justification). M'enfin, ce n'est pas le premier truc non documenté ou inconnu qu'on découvre en réinstallant la prod :(

**Comment by pierre-24** [comment]
Pataper, mais ce qui m'étonne toujours, c'est de lire "encore un truc non documenté dans l'infra" ... Et de ne jamais le documenter.

(pataper, hein!)

**Comment by GerardPaligot** [comment]
@Un-Cornichon @sandhose @SpaceFox Toujours aucun serveur mail sur la bêta ?

**Comment by SpaceFox** [comment]
Pas à ma connaissance.

**Comment by gustavi** [comment]
Je peux éventuellement regarder si tu veux @SpaceFox

**Comment by GerardPaligot** [comment]
@gustavi Moi je veux bien que tu regardes ça quand tu as du temps. ^^

**Comment by pierre-24** [comment]
C'est toujours d'actualité, ça ?
