### ISSUE TITLE
Un template qui n'est pas variabilisé

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2977]
Comme on peut le constater dans le template [opensearch.xml](https://github.com/zestedesavoir/zds-site/blob/3e91b083ee882396abf4dc0d508595d9bdb101d7/templates/search/opensearch.xml#L13) il y'a une valeur en dur qui y traine.

Il faut remplacer la ligne : 

``` python
<Contact>http://zestedesavoir.com/pages/contact/</Contact>
```

par 

``` python
<Contact>{% url "zds.pages.views.contact" %}</Contact>
```

**Comment by Situphen** [comment]
Je précise que `{% URL %}` génère une URL relative et pas absolue. Est-ce gênant ?

**Comment by firm1** [comment]
En lisant la [spécification officielle](http://www.opensearch.org/Specifications/OpenSearch/1.1/Draft_5) je me rend
compte que cette balise attend surtout une adresse mail.

**Comment by gustavi** [comment]
Je vais m'occuper de ça.
