### ISSUE TITLE
Lien entre l'ajout d'une image et la galerie

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#2978]
Je trouve qu'il pourrait être pratique dans l'éditeur > bouton "Ajouter une image" de proposer une case "Galerie" qui nous ouvrir une autre popup par exemple avec une liste des nos images en galerie voir même un input pour nous permettre de directement ajouter une image à la galerie.

ça éviterais de devoirs switcher sur deux onglets pour rédiger un message.

**Comment by Situphen** [comment]
C'est prévu avec la ZEP 14 sur l'éditeur Markdown je crois !

**Comment by WinXaito** [comment]
Okay :) (Une ZEP déjà lancé ou juste une idée de ZEP ?)

**Comment by Situphen** [comment]
Une ZEP que je dirais presque finie d'être rédigée mais en attente de dev

**Comment by WinXaito** [comment]
Okay merci
Du coup je clos ça ici :)
