### ISSUE TITLE
La dépendance Cairo merdouille sur OS X

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2984]
Voulant relancer une instance de ZdS en local, j'ai du me confronter à une grosse mise à jour de ce qu'il me restait sur mon poste de travail. Tout s'est bien passé hormis une chose : **cairo**.

Malgré des cleans de mes dépendances et une remise à zéro de mon virtualenv, rien à faire. La dépendance cairo est manquante et je ne peux rien lancer.

Je ne sais pas encore si le problème vient de moi ou si l'installation sur OS X a évolué par rapport à la documentation d'installation de ZdS mais je voulais simplement signalé sur quoi j'ai passé une bonne partie de ma soirée. :)

Je reviens rapidement sur des tests avec un autre mac que j'ai sous la main.

**Comment by DevHugo** [comment]
J'ai un mac sous la main, tu veux que je fasse un test ?

**Comment by GerardPaligot** [comment]
@DevHugo Carrément !

**Comment by GerardPaligot** [comment]
Et si tu peux te souvenir des commandes que tu auras fais, ça serait génial !

**Comment by DevHugo** [comment]
Désolé, je m'en souvient plus. Je peux tenter une nouvelle installation, si
tu veux pour tester.

**Comment by GerardPaligot** [comment]
Déjà si tu me dis que tu parviens à utiliser la dernière version de ZdS sur ton mac avec un environnement existant, c'est déjà ça.

**Comment by DevHugo** [comment]
Je tente une installation après-demain, je te dit ça.

**Comment by geoffroyw** [comment]
Je n'avais jamais installé ZDS sur mon Mac (OS X Yosemite 10.10.5 (14F27)), du coup j'ai suivi les instruction disponibles [ici](https://github.com/zestedesavoir/zds-site/blob/dev/doc/source/install/backend-os-x-install.rst). J'ai rencontré deux erreurs liées à Cairo que je rapporte plus bas ainsi que comment je les ai résolues (Ce sont les seules que j'ai rencontrées).

Tout a parfaitement fonctionné jusqu'à `pip install --upgrade -r requirements.txt -r requirements-dev.txt` qui a planté avec l'erreur suivante:

```
Collecting cairocffi (from CairoSVG==1.0.13->-r requirements.txt (line 18))
  Downloading cairocffi-0.7.2.tar.gz (75kB)
    100% |████████████████████████████████| 77kB 29.8MB/s 
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/cffi/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'cffi' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    No local packages or download links found for cffi>=1.1.0
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/4c/7kkvr1f54gn5zrthwphfc8nc0000gn/T/pip-build-n29F_9/cairocffi/setup.py", line 65, in <module>
        **cffi_args
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/geoffroy/.virtualenvs/zdsenv/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/geoffroy/.virtualenvs/zdsenv/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/geoffroy/.virtualenvs/zdsenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 830, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/geoffroy/.virtualenvs/zdsenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1075, in best_match
        return self.obtain(req, installer)
      File "/Users/geoffroy/.virtualenvs/zdsenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1087, in obtain
        return installer(requirement)
      File "/Users/geoffroy/.virtualenvs/zdsenv/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/geoffroy/.virtualenvs/zdsenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cffi>=1.1.0')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4c/7kkvr1f54gn5zrthwphfc8nc0000gn/T/pip-build-n29F_9/cairocffi
```

J'ai lancé un `pip install cffi>=1.1.0`pour voir. Ça a fonctionné.
Le `pip install --upgrade -r requirements.txt -r requirements-dev.txt` que j'ai lancé dans la foulée à lui aussi fonctionné.

J'ai tenté un `python manage.py runserver` qui a lamentablement échoué avec 

```
    import cairo  # pycairo
ImportError: No module named cairo
```

Du coup j'ai désinstallé cairo avec homebrew `brew uninstall cairo`et je l'ai installé avec port `sudo port install cairo` et ça a marché !

**Comment by GerardPaligot** [comment]
Il était une fois un petit bugdroid.

Ce petit bugdroid voulait se lancer dans une aventure périlleuse, il voulait contribuer à un projet immense où d'autres androïde y avait laissé leurs processeurs. Mais notre brave petit bugdroid n'avait peur de rien et se lançait à corps perdu dans cette aventure !

Bien vite, notre petit héros rencontra son premier obstacle. Dans ce projet, une petite dépendance, nommé cairo, lui faisait fasse et lui tenait tête. Impossible pour notre bugdroid d'aller de l'avant. Il tenta de contourner l'obstacle, de lui rentrer dedans, de le combattre mais à chaque fois, ces tentatives se soldaient par un échec. Notre héros était désespéré et il attendit le lendemain pour lancer une nouvelle offensive contre ce terrible ennemi.

Rusé, notre petit bugdroid attendit la nuit tombée pour déstabiliser son ennemi. Il établit un plan d'attaque précis, il mit en ordre toutes ses affaires et prépara toutes ses armes et se lança dans une ultime bataille contre Cairo. Après de longues minutes de combat, notre petit héros parvenu à mettre à mal son ennemi et tout content, il pu continuer son chemin.

Cependant, entre temps, il découvrit qu'une autre personne avait déjà combattu cet ennemi et qu'il avait expliqué comment le vaincre juste après l'obstacle. C'est ainsi que notre bugdroid se suicida dans un fossé pensant qu'il était voué à un destin de mer**.

...

Vous l'aurez compris, j'ai trouvé la solution à mon problème au moment précis où @geoffroyw poste son message qui correspond exactement à mon problème ... PR pour bientôt et merci quand même @geoffroyw ! ^^

**Comment by pquentin** [comment]
@geoffroyw ton erreur pip n'était que temporaire : PyPI était down au moment où il a cherché cffi. Je ne pense qu'avec un nouveau virtualenv `pip install --upgrade -r requirements.txt -r requirements-dev.txt` fonctionnerai du premier coup. (En tout cas je n'ai pas eu ce souci sur OS X).

Pour Cairo et homebrew, en fait il faut installer py2cairo (ce sera py3cairo quand ZdS sera passé à Python 3). Il faut suivre les caveats indiqués par homebrew pour que Python trouve bien les modules installés. J'imagine que MacPorts a installé les bindings Python avec Cairo, tout simplement.

**Comment by DevHugo** [comment]
Je me souvient avoir eu la même erreur, y'a 2-3 mois.

@Andr0 ton histoire m'a fait rire pour un premier jour, c'était pas gagné.
Le 8 sept. 2015 7:56 AM, "Quentin Pradet" notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
@pquentin C'est répondu sur ma PR. https://github.com/zestedesavoir/zds-site/pull/2987#issuecomment-138463613 :)

@DevHugo Je ne sais pas qui s'est Andr0 mais je ne connais pas perso. :-°
