### ISSUE TITLE
La promotion d'un membre au statut de staff ne lui donne pas de badge tout de suite

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2985]
Un membre (ancien CA) a été promu au grade de staff. Il est tout content, mais sont badge vert ne s'allume pas.

A première vue, le problème vient de [ce commit](https://github.com/zestedesavoir/zds-site/commit/7f8d7cc30e686c30c0ac1b0c4009ce0e56a6f2fd) d'"optimisation" qui me semble un peu tordu. Les conditions ne me semblent pas cohérente.

Le fait est que le statut d'un membre (staff ou pas) semble "mis dans un cache applicatif" (il faut une action spéciale pour le refresh) qui fait que le badge vert de notre nouveau staff ne s'allumera qu'après un `restart` de gunicorn.

Il s'agit donc d'une regression, mais ça ne me semble pas bloquant non plus.

**Comment by artragis** [comment]
> user.pk in perms['forum.change_post'] and perms['forum.change_post'][user.pk]:

j'ai fumé quoi ce jour là?

**Comment by GerardPaligot** [comment]
![](http://m.memegen.com/hajts2.jpg)

Hum ... sorry.

**Comment by gustavi** [comment]
C'est peut-être à cause de cache, à essayer de déconnecter/reconnecter.

**Comment by GerardPaligot** [comment]
C'est toujours le cas ? @firm1 @gustavi ?

**Comment by gustavi** [comment]
En fait l'apparition du badge Staff est à refaire correctement car aujoud'hui c'est assez mal foutu.

**Comment by pierre-24** [comment]
Voilà qui est fait, merci @GCodeur :)
