### ISSUE TITLE
La beta est innacessible

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2986]
ça fait déjà environ 15 min que la beta est devenu innaccesible. L'erreur semble dire qu'il s'agit d'une erreur 500.

![erreor500](https://cloud.githubusercontent.com/assets/6066015/9719317/6dffffc8-5583-11e5-914a-6403e704f19b.PNG)

J'ouvre ce ticket pour suivre l'état d'avancement de chose (et surtout savoir quand le problème sera résolu).

J'hésite a tagguer back ou infra, dans le doute, je m'abstiens.

**Comment by firm1** [comment]
Bon, je viens de refresh et c'est de nouveau up :)

**Comment by Situphen** [comment]
Euh, je trouve que c'est un peu tôt pour ouvrir un ticket si la bêta est arrêtée depuis 15 minutes ! Au bout de quelques heures, peut-être qu'on peut se demander pourquoi mais là il se peut que ce soit juste quelqu'un qui travaille dessus. Il vaut mieux passer sur IRC pour demander ça.

**Comment by SpaceFox** [comment]
Un gros +1.

**Comment by firm1** [comment]
ça a coupé, et vu que ce n'était pas la page de maintenance, j'ai fais le ticket.

Je ne vois pas trop ce que ça change d'ouvrir le ticket plutot que d'aller sur irc (si ce n'est me donner plus de travail), mais ok la prochaine fois je vais essayer de faire ça.

**Comment by SpaceFox** [comment]
Le ticket spamme tout le monde.

**Comment by pierre-24** [comment]
Il est ceci dit intéréssant de constater que la maintenance sur la bêta génère toujours cette page et non la page de maintenance, c'est pas la première fois.

@sandhose, un avis là dessus ?

**Comment by sandhose** [comment]
Simplement parce que la page de maintenance, c'est une config nginx à activer. Or, pendant que je fais les resets complets, j'active pas cette page parce que bah, c'est pas la peine, et donc on a l'erreur 500 par défaut, puisque nginx arrive pas à accéder à l'upstream, au serveur gunicorn.
