### ISSUE TITLE
L'import d'images par zip ne marche pas correctement

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2988]
L'import  d'images par zip est buggué. Lorsque l'on importe les images n'ont pas de miniatures, ni de lien markdown pour les télécharger... bref, c'est pas utilisable :(

**Comment by Situphen** [comment]
Euh, ça sera sûrement corrigé avec la ZEP 12, non ?

**Comment by pierre-24** [comment]
Ooooh que oui :)

https://beta.zestedesavoir.com/contenus/importer/archive/nouveau/ :

![screenshot from 2015-09-10 19 47 13](https://cloud.githubusercontent.com/assets/7889675/9796125/bf603072-57f4-11e5-8680-3ebedb42f83b.png)

**Comment by Eskimon** [comment]
Nan c'est carrément la lib image qui semble déconner, même en import classique les liens ne sont plus généré, ni les miniatures, ni les formats "classiques" (l'image est chargée pleine résolution)

**Comment by Eskimon** [comment]
Il doit manquer quelque chose quelques part dans la réinstall du serveur

**Comment by Situphen** [comment]
Lié au problème avec les JPEG alors ?

**Comment by pierre-24** [comment]
Je linke la précédente issue : #2962 !

**Comment by GerardPaligot** [comment]
@pierre-24 Je pense que @Eskimon ne parlait pas des imports d'une galerie pour un tutoriel mais les imports d'image pour une galerie.

**Comment by pierre-24** [comment]
... Oui :-°

**Comment by pierre-24** [comment]
(c'est dès qu'on prononce le mot ZEP-12, je suis tout fou ^^ )

**Comment by pierre-24** [comment]
Cornichon c'est courageusement porté volontaire pour [tenter d'y voir plus claire avec cette solution stackoverflow](http://stackoverflow.com/questions/24396727/find-which-libjpeg-is-being-used-by-pil-pillow/24397115#24397115). Voici le résultat:

```
(zdsenv)zds@vps192382:/opt/zdsenv$ ldd /opt/zdsenv/local/lib/python2.7/site-packages/PIL/_imaging.so  
linux-vdso.so.1 (0x00007fffbedbc000) 
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fc752aad000) 
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc752890000) 
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc7524e7000) 
/lib64/ld-linux-x86-64.so.2 (0x00007fc752f13000)
```

Autrement dit, pillow n'as pas été compilé avec le support jpeg, pas cette fois-ci.

**Comment by SpaceFox** [comment]
WTF ? Il me semblait que ça avais été corrigé !

**Comment by pierre-24** [comment]
Presque certains que ça l'était, mais depuis à peu près le 7 septembre, Sentry nous recrache des erreurs o_O

**Comment by firm1** [comment]
ça ne serait pas une regression de la récente version (gaston) ? elle a été déployée le 03 septembre normalement.

**Comment by Eskimon** [comment]
Ok tout remarche :)
