### ISSUE TITLE
Référencement catastrophique sur les forums

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2989]
Aujourd'hui, j'ai découvert un nouveau sujet sur Zeste de Savoir. Le projet d'un nouveau membre qui est venu présenter son [nouveau jeu Android](https://zestedesavoir.com/forums/sujet/4015/mozzies-night/). Jusque là, rien de bien surprenant.

J'ai alors décidé de savoir d'où est-ce qu'il venait en rentrant son jeu dans le moteur de recherche Google. J'ai alors pu savoir qu'il devait sans doute venir d'OpenClassrooms puisqu'il y a une présentation de son jeu sur cette plateforme aussi (et sur developpez.net).

![capture d ecran 2015-09-13 a 12 55 23](https://cloud.githubusercontent.com/assets/1913901/9836374/6138d97a-5a17-11e5-99bd-8121a4b79a9f.png)

Par contre, comme en témoigne la capture juste au dessus, Zeste de Savoir ne figure pas dans la liste. Plus grave encore, il ne figure sur **aucune** page de la recherche (j'ai été jusqu'à la page 12 !). En fait, c'est simple. Zeste de Savoir n'est pas **visible** de l'extérieur et je trouve ça **très problématique**.

(Là je prends ma casquette d'auteur) En tant qu'auteur, j'aimerais justifier mon choix de mettre mon contenu sur Zeste de Savoir pour bénéficier d'une meilleur visibilité mais ce n'est pas le cas. Bien au contraire, aujourd'hui, je pense que mettre mon contenu sur une plateforme de blogging répandue comme Medium ou Blogspot me sera plus bénéfique que Zeste de Savoir.

Il me semble donc urgent de remédier à notre référencement sur Zeste de Savoir !

PS : Je ne suis pas certain de savoir si c'est ici que je dois poster ce problème mais dans le doute, je sais que je toucherais les bonnes personnes au moins.

**Comment by Situphen** [comment]
Il faut trouver quelqu'un qui s'y connaisse en SEO...

**Comment by pierre-24** [comment]
@firm1  ?

**Comment by GerardPaligot** [comment]
Alors après quelques tests, j'ai l'impression que les tutoriels sont plus ou moins bien référencés (ouf) mais que le forum ne l'est pas du tout. "Mozzies night zeste de savoir" sur Google et je n'obtiens aucun résultat pertinent. Pire, j'obtiens des résultats sur la liste des tutoriels, la liste des forums ou la page d'accueil mais il ne semble pas vouloir rentrer dans les forums, juste l'éviter.

![capture d ecran 2015-09-13 a 13 28 05](https://cloud.githubusercontent.com/assets/1913901/9836464/5b185ad0-5a1b-11e5-8c44-5e1377096e4b.png)

**Comment by WinXaito** [comment]
Je pense que le problème viennent de la ..

![zds_seo_1](https://cloud.githubusercontent.com/assets/8223773/9836463/3e0019f6-5a1b-11e5-89e7-ecfd3ade3d3f.png)

Le contenu des tutoriels n'est pas réferencer j'ai l'impression ...

**Comment by SpaceFox** [comment]
Le topic chez nous a 2h, celui sur OC 1h.

Il s'agit sans doute d'un bête problème de passage du robot Google, à voir à quelle fréquence on lui demande de passer dans le sitemap.xml.

Si le topic était là depuis 2 jours et toujours invisible des moteurs de recherche, j'aurais compris ta réaction. En l'état, elle me semble franchement déplacée.

**Comment by SpaceFox** [comment]
Quant aux forums, ils sont bel et bien référencés. Il te suffit de prendre un sujet un poil plus vieux. Comme « zep-34 » par exemple (qui n'a pas 24h).

**Comment by GerardPaligot** [comment]
> elle me semble franchement déplacée

Euh ... pardon ?
1. Tout le monde ne connait pas le référencement. Dans mon cas, c'est un domaine qui m'est totalement inconnu.
2. Je ne fais que constater les choses. Je fais une recherche, je vois que Google a référencé toutes les autres plateformes sauf la notre (alors que les sujets sur les autres forums sont récents).
3. Je n'ai aucune idée de comment est configurer notre référencement auprès de Google. Je ne savais même pas qu'il y avait un temps donné à Google pour référencer le contenu.
4. Mon intention n'était pas de troller, d'être irrespectueux ou quoi que ce soit d'autre. Par contre, ton message à toi est agressif et irrespectueux. J'aurais été un nouveau membre et tu aurais répondu comme ça, j'aurais refermé ma page web et je serais plus retourné sur ZdS (où du moins, sur le côté dev).

Soit. Sur ce, fait ce que tu veux de cette issue ...

**Comment by SpaceFox** [comment]
Ma réponse n'aurait pas été la même si par exemple l'auteur du topic était venu créer le ticket : lui ne connaît pas le site (il s'est inscrit pour l'occasion).

Toi, si. Tu nous connais depuis plus d'un an mais ça ne t'as pas empêché de pondre tout un pavé sur ta non-visibilité en tant qu'auteur et de venir ouvrir un ticket en mode catastrophe. Or, depuis le temps que tu bosses sur ce projet, tu nous connais, tu as vu les articles sur les stats, et tu devrais donc savoir que c'est quelque chose qu'on surveille un minimum.
Que toi, avec ta bouteille et ta connaissance de la gestion du projet, puisse supposer que en plus d'un an _personne_ ne se soit rendu compte que les forums ne soient pas indexés par les moteurs de recherche me laisse pantois. Subséquemment, oui, tes messages dans le ton me paraissent franchement déplacés. Que tu poses la question me paraît normal ; que tu viennes hurler à la catastrophe comme tu l'as fait, moins.

---

Cela dit, on a sans doute sous-estimé la fréquence des nouveaux topics à la création du site, et jamais pris la peine de les changer. [Il y a des réglages ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/urls.py#L16). J'ai l'impression aussi que le sitemap n'est pas tout à fait complet (la page d'accueil par exemple).
Je ne sais pas l'impact de ces réglages, par exemple OC ne semble pas avoir de sitemap fonctionnel, celui de dvp.com n'a pas l'air de contenir les topics.

D'autre part, il me semble que les moteurs de recherchent indexent plus fréquemment les sites qui changent souvent et qui ont une grosse audience (à confirmer). Si c'est bien le cas, c'est normal que ZdS soit moins souvent visité par les robots que ses concurrents, et on ne peut pas y faire grand-chose…

**Comment by GerardPaligot** [comment]
Bien, on va éviter d'en faire tout un fromage parce que je pense que toi comme moi pouvons exploser sur le sujet. Simplement que j'ai vu passer sur IRC des problèmes avec le sitemap récemment, que je ne connais vraiment **pas du tout** le référencement (et plus largement le dev web) et que c'est la raison pour laquelle j'ai posté un [second message](https://github.com/zestedesavoir/zds-site/issues/2989#issuecomment-139862274) pour apporter des informations complémentaires afin de moins dramatiser la situation.

Ceci dit, même si je suis un habitué du projet, ça ne m'empêche pas de me tromper et ça ne t'empêche pas de venir me répondre correctement. Il suffit de dire simplement les choses et tout se passe bien pour tout le monde.

---

Si je comprends bien les réglages, nous demandons à Google d'indexer les tutoriels et les articles hebdomadairement et les sujets toutes les heures ? Alors je suis étonné de ne pas voir le sujet concerné par cette issue dans le [référencement Google](https://www.google.fr/search?q=site%3Azestedesavoir.com+mozzie+night&oq=site%3Azestedesavoir.com+mozzie+night&aqs=chrome..69i57j69i58.212j0j7&sourceid=chrome&es_sm=119&ie=UTF-8) (au moment où j'écris ces lignes) et d'avoir une période si importante pour les tutoriels et les articles.

Est-ce que ça coute de réduire ce temps pour demander un référencement plus fréquent ?

**Comment by WinXaito** [comment]
De ce que je connais sur le référencement, oui google passe beaucoup plus fréquement sur les sites à grande audience et sur les quels il y a du changement.

Et il est vrai que 2h ce n'est pas grand chose, il faudra retesté dans 5-6h pour avoir une plus grande chance d'être indexé.

Côté analytics on a des status sur les passages des moteurs de recherches pour se faire une idée @SpaceFox ?

**Comment by SpaceFox** [comment]
De ce que j'en sais (mais là encore je ne suis pas expert SEO, loin de là) les fréquences données dans le sitemap ne sont qu'indicatives, les moteurs de recherche en font ce qu'ils en veulent. Possiblement rien, donc…

Pour les passages des moteurs de recherche, il faudrait éplucher les logs nginx.

**Comment by WinXaito** [comment]
![zds_seo_2](https://cloud.githubusercontent.com/assets/8223773/9837898/78d3453e-5a4e-11e5-9253-b41f14bb6dc0.png)

Résultat en première place ! Donc autant dire que notre référencement est très bon, il faut juste attendre un petit peu plus longtemps ;)

**Comment by Situphen** [comment]
Rien pour l'instant sur Qwant mais je regarde de temps en temps !

**Comment by Eskimon** [comment]
J'utilise rarement google, voici ce que j'obtiens : 

![capture du 2015-09-26 20 13 51](https://cloud.githubusercontent.com/assets/761168/10119055/5874f25a-648b-11e5-9e74-396e8170d4e6.png)

Ca semble donc bien se passer côté référencement, juste que google ne nous prioritise pas comparé à des sites plus gros (il me semble aussi avoir lu que les crawlers passent plus souvent sur les sites à plus fort contenu)

**Comment by Situphen** [comment]
Toujours rien sur Qwant  ! :(

**Comment by SpaceFox** [comment]
Ça existe les gens qui utilisent Qwant ?

2015-09-26 20:36 GMT+02:00 Situphen notifications@github.com:

**Comment by Situphen** [comment]
> Ça existe les gens qui utilisent Qwant ?

Moi et au minimum Korben (de korben.info)

**Comment by SpaceFox** [comment]
Oui mais Korben n'est pas une référence.

2015-09-26 21:42 GMT+02:00 Situphen notifications@github.com:

**Comment by Eskimon** [comment]
Don't feed the troll.

Date: Sat, 26 Sep 2015 12:47:11 -0700
