### ISSUE TITLE
Le membre en LS ne peut pas lire les pages statiques

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#299]
Le membre en LS ne peut pas lire les pages statiques : elles ont toutes le décorateur `@can_read_now`.

Personnellement ça me paraît complètement bizarre, ces pages sont sensées être publiques.
Quelqu'un voit un inconvénient à ce que je les rende publiques ?

**Comment by firm1** [comment]
Aucun inconvénient,  que des avantages.

Je dis donc +1

**Comment by firm1** [comment]
En te relisant, je me demande s'il y'a pas un truc qui cloche. le décorateur `@can_read_now` est censé interdire uniquement d'écrire pas de lire. Si tu es LS normalement tu peux tout lire mais tu ne peux pas écrire.

Donc en gros, un LS doit pouvoir lire les pages statiques, mais un Banni ne doit pouvoir rien lire, sauf s'il se déconnecte.

**Comment by SpaceFox** [comment]
Au temps pour moi, c'est que les membres bannis.

En fait, si je comprends bien la ligne 20 de /zds/member/decorator.py, ce décorateur est là surtout pour déconnecter les membres qu'on viendrait de bannir. J'ai bon ?
(Parce que dans la majorité des cas, la page sera lisible même pour un utilisateur déconnecté).

**Comment by firm1** [comment]
> En fait, si je comprends bien la ligne 20 de /zds/member/decorator.py, ce décorateur est là surtout pour déconnecter les membres qu'on viendrait de bannir. J'ai bon ?

Tu as bon. Vaut mieux être membre invité plutot qu'être banni.

Du coup, je ferme.
