### ISSUE TITLE
[Beta zep-12] "Comparer les versions" inutilisable une deuxième fois

### ISSUE THREAD

**Issue by AlexRNL** [zestedesavoir/zds-site#2990]
Le bouton qui permet de comparer différentes versions d'un tutoriel/article n'est pas utilisable une seconde fois.

En effet, si on compare une première fois deux versions, puis qu'on revient sur la page d'historique avec le bouton précédent du navigateur ; alors, le bouton "Comparer les versions sélectionnées" n'est plus utilisable (il est en mode "chargement" avec l'animation de chargement en dessous). Si on recharge la page, le bouton est à nouveau dans l'état "normal", et on peut de nouveau comparer des versions.

Note : j'ai le problème sur Firefox (40.0.3), mais tout fonctionne bien avec Chrome ou IE 11.

**Comment by GerardPaligot** [comment]
@artragis @pierre-24

**Comment by pierre-24** [comment]
@Situphen : confirme moi bien que cette discussion avait déjà eu lieu sur la PR à l'époque ?

**Comment by Situphen** [comment]
Oui, ça avait déjà eu lieu : _it's not a bug, it's a feature!_

**Comment by yapper-git** [comment]
Tout à fait, je trouvais également ce comportement anormal.
En réalité c'est la faute à un code JS ajouté pour éviter qu'un formulaire soit envoyé plusieurs fois…

**Comment by Situphen** [comment]
Du coup vu que c'est pas un bug, je ferme ! Si ça gène beaucoup d'auteurs on verra pour intégrer ça dans une prochaine version :)
