### ISSUE TITLE
Manque un &bull; dans le titre de la page d'édition de profil

### ISSUE THREAD

**Issue by gagath** [zestedesavoir/zds-site#2991]
Flemme de faire des phrases.

URL : `http://zestedesavoir.com/membres/parametres/profil/`
Correction à appliquer : "Mon profil Paramètres &bull; ZdS" -> "Mon profil &bull; Paramètres &bull; ZdS"

**Comment by WinXaito** [comment]
En effet, si tu souhaites t'occuper de cette issue tu peux, autrement je prends. 

Merci :)

**Comment by gagath** [comment]
Je passe, have fun.

**Comment by WinXaito** [comment]
Okay alors @Eskimon ou @pierre-24 si quelqu'un peut me l'attribuer, par contre je ne pourrai pas m'en occuper avant mercredi/jeudi, m'enfin me semble pas que ça soit la chose la plus urgente :')

**Comment by Eskimon** [comment]
hello @WinXaito , je te la garde assigner ou je la relache pour qqun d'autre ?

**Comment by WinXaito** [comment]
Ohh autant pour moi j'avais complétement zapper ça, d'ailleurs je crois que j'en ai encore une autre attribué ? 

par contre ces temps j'ai vraiment beaucoup de boulot, donc quelqu'un d'autre peut prendre et si quand j'aurai le temps ce n'est toujours pas fait je m'en occuperai.

Vraiment désolé

**Comment by pierre-24** [comment]
Voilà qui est fait, merci @poulp :)
