### ISSUE TITLE
Dépendances de dev nécessaires en prod

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#2993]
Actuellement, on est obligé d'installer les dépendances dans `requirements-dev.txt` en environnement de prod, à cause de `django-debug-toolbar` qui est nécessaire pour démarrer l'app. Soit il faut le bouger dans le `requirements.txt`, soit on se débrouille pour ne pas dépendre de `django-debug-toolbar` en environnement de prod.

Note: Ca serait cool que ça soit fait rapidement, je suis en train de revoir les scripts de MEP (cf. https://github.com/sandhose/zds-server-config), et j'aimerais bien ne pas avoir à installer les dépendances de dev :)

**Comment by pierre-24** [comment]
Comme dit sur IRC : https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L280 !

(ligne qui est AVANT l'import de `settings_prod.py`, donc forcément appliquée d'office).

Pourrait aussi expliquer certains problèmes avec RTD :)

**Comment by SpaceFox** [comment]
> Actuellement, on est obligé d'installer les dépendances dans requirements-dev.txt en environnement de prod, à cause de django-debug-toolbar qui est nécessaire pour démarrer l'app. Soit il faut le bouger dans le requirements.txt, soit on se débrouille pour ne pas dépendre de django-debug-toolbar en environnement de prod.

Ha ?

Il est installé là en prod ?

**Comment by sandhose** [comment]
Sur la nouvelle préprod en tout cas j'ai dû le faire, et sur mes tests sur des virtualenvs clean aussi. Donc je suppose que c'est aussi le cas en prod

**Comment by gustavi** [comment]
Je vote pour le mettre dans le **requirement.txt**, il peut être extrêmement utile pour débuger un site (c'est du vécu).

**Comment by Situphen** [comment]
> Je vote pour le mettre dans le requirement.txt, il peut être extrêmement utile pour débuger un site (c'est du vécu).

Sauf qu'il ne doit pas être en production car ~~il n'est pas assez sécurisé~~ il est fait pour le débogage et pourrait donner des informations confidentielles ! Je vote pour le laisser dans le `requirements-dev.txt` et changer le `settings.py` pour que ça ne bug plus.

**Comment by SpaceFox** [comment]
Ce genre d'outil n'a rien à foutre en prod.

**Comment by gustavi** [comment]
Il ne s'active que dans le cas où _DEBUG = True_ et dans ce cas là pas besoin de DDT pour balancer des infos sensibles.

**Comment by Situphen** [comment]
> Il ne s'active que dans le cas où _DEBUG = True_ et dans ce cas là pas besoin de DDT pour balancer des infos sensibles.

Et vu qu'en production `DEBUG = False` tout le temps, autant le laisser dans `requirements-dev.txt` ! ;)

**Comment by GerardPaligot** [comment]
Rien que le nom de la dépendance, je sais que c'est pas un truc que je veux voir en prod. Si les forks veulent faire du debug en prod, qu'ils le fassent mais on le fait pas sur l'instance de ZdS.

**Comment by SpaceFox** [comment]
> Il ne s'active que dans le cas où DEBUG = True et dans ce cas là pas besoin de DDT pour balancer des infos sensibles.

Merci donc de me confirmer que ça n'a pas sa place en prod, puisque ça ne serait jamais utilisé.

**Comment by WinXaito** [comment]
> Et vu qu'en production DEBUG = True tout le temps, autant le laisser dans requirements-dev.txt ! ;)

Euh en Prod on est en debug True ? C'est quoi l'utilité Oo, le but n'est pas justement de le mettre à false sur la Prod ?

**Comment by Situphen** [comment]
> Euh en Prod on est en debug True ? C'est quoi l'utilité Oo, le but n'est pas justement de le mettre à false sur la Prod ?

Copier/Coller :D Non, bien sûr on est à `False` :)

**Comment by WinXaito** [comment]
Ah ok me semblais bien xD

**Comment by GerardPaligot** [comment]
Quelqu'un avec les droits sur la prod pourrait vérifier qu'on n'a pas la dépendance `django-debug-toolbar` d'installé ?

**Comment by gustavi** [comment]
ping @SpaceFox @Un-Cornichon

**Comment by SpaceFox** [comment]
Oui, et ça doit être corrigé.

**Comment by Situphen** [comment]
@sandhose si tu pourrais vérifier que c'est bon histoire qu'on puisse fermer :)

**Comment by gllmc** [comment]
Je viens de vérifier : la dépendance est absente en bêta, mais présente en prod. Du coup, j'imagine qu'il n'y a plus de problème, mais que c'est resté installé en prod.
