### ISSUE TITLE
Envoi d'un mail non désiré lors de la création d'une réponse à un MP (doublon de #2905)

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#2994]
DOUBLON DE #2905

Lorsque j'ai répondu à un MP (celui sur la Licence PyCharm) j'ai automatiquement reçu un mail comme quoi SpaceFox (utilisateur qui avait posté juste avant moi) venait de répondre or ce n'est pas le cas. J'ai eu ce problème plusieurs fois aujourd'hui (23 septembre 2015).

Je vais essayer de chercher d'où ça vient.

**Comment by Situphen** [comment]
Je crois que c'est un doublon de #2905 ! :)

**Comment by gustavi** [comment]
Arf j'ai fait la recherche sur « mail » et non « courriel » ! Au temps pour moi, je ferme ça.
