### ISSUE TITLE
Enregistrer la version dans le `settings.py`

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#2995]
Je suis en train de revoir les scripts de MEP, et ça implique que l'instance ne soit plus un répo git... du coup, impossible d'extraire le nom de la version ni le numéro de commit depuis le répo.

Il faudrait donc pouvoir indiquer la version + éventuellement sha1 de commit dans le `settings_prod.py` (pas systématiquement, juste si on est pas dans un répo git)

**Comment by Situphen** [comment]
Ça n'a pas plutôt sa place dans le `setup.py` ?

Et pourquoi il faut que l'instance ne soit plus un dépôt Git ?

**Comment by GerardPaligot** [comment]
Ca me semble être une si mauvaise idée. Tu pourrais donner des informations supplémentaires sur le problème ?

**Comment by sandhose** [comment]
En gros, je télécharge un tar du tag en question, avec juste le code, et j'extrait ça dans un dossier différent à chaque version. Du coup pas de répo git, mais j'ai l'information sur le numéro de version au moment de la télécharger, et je peux l'injecter facilement dans le `settings_prod.py`.

**Comment by gustavi** [comment]
Pourquoi pas de git ?

Sinon on met en général un `__version__='n.m'` dans le `__init__.py`.

**Comment by motet-a** [comment]
D’ailleurs, avant de faire tout ça, je pense que ça serait bien de faire en sorte que le site puisse tourner en production sans le dépot Git (c’est à dire sans dossier `.git` à la racine), et du coup sans lire les informations du dépot pour afficher la version dans le footer. Ça implique d’avoir la version quelque part ailleurs, et si elle est dans un fichier Python c’est super facile de l’importer dans le `setup.py`. 

L’autre jour j’ai utilisé [warner/python-versioneer](https://github.com/warner/python-versioneer) pour faire ça, c’est un peu tordu et pas hyper évident à mettre en place mais ça marche pas mal (c’est intégré avec les tags de Git). [vhf/confusable_homoglyphs](https://github.com/vhf/confusable_homoglyphs) utilise ça, tout comme [motet-a/jinjalint](https://github.com/motet-a/jinjalint).

**Comment by vhf** [comment]
Pour moi le sha dans le footer n'a pas d'utilité. Actuellement on a une étape de build faite sur travis sur chaque tag, si on continue dans cette direction d'avoir des builds, y inclure le tag est facile.

Comme ça on ne dépend plus du tout d'un repo au déploiement, on a toujours le tag en footer, et on vire le sha ?

**Comment by artragis** [comment]
@vhf j'ai tendance à ne pas virer le sha, puisque sentry l'utilise pour gérer les release :)

**Comment by artragis** [comment]
@sandhose c'est pas réglé?

**Comment by Situphen** [comment]
Actuellement lors de la MEP on passe par le dépôt Git donc on n'a pas de problème à trouver le numéro de version ou le sha.
