### ISSUE TITLE
L'import de zip d'images nomme/légende mal les images

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#2999]
Lorsque l'on importe un zip contenant des images, le nom des images est pris sur le nom du fichier mais en gardant l'extension, c'est moche. Pour faire plus propre, l'extension doit-être supprimé et la légende doit-être une chaine vide plutot que none.

**Comment by pierre-24** [comment]
C'est "ma faute", c'est moi le dernier à avoir été chipoter là dedans. T'as des pistes de ce que pourrait être la légende, ceci étant dit ?

**Comment by Eskimon** [comment]
oui c'est corrigé ;)

**Comment by pierre-24** [comment]
Ok :)
