### ISSUE TITLE
Write CGU

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#30]
Pour lancer ZDS, il faut rédiger les conditions générales utilisateurs afin d'être crédible dès le lancement et ne pas passer pour des rigolos.

S'ils y'en a qui se sentent l’âme de commencer un brouillon, je l'intégrerai dans une page dédié qui sera disponible via le footer.

**Comment by Coy0te** [comment]
On a quelqu'un sur ce sujet ?

**Comment by cgabard** [comment]
peut etre en parler sur la ML ?

**Comment by firm1** [comment]
IL me semble qu'[Arius est dessus](http://zds.leomartinez.fr/issues/48#note-23) à voir avec lui

**Comment by Coy0te** [comment]
J'ai demandé sur la ML, on verra bien.

**Comment by cgabard** [comment]
Effectivement Arius le confirme

**Comment by firm1** [comment]
Un première version de la page [étant en ligne](http://preprod.zestedesavoir.com/pages/cgu), les évolutions feront l'objet d'une autre issue. Je ferme donc celle-ci
