### ISSUE TITLE
CGUs / Mentions légales

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#300]
Est-ce qu'on en a besoin ?
Que met-on dedans ?

**Comment by Coy0te** [comment]
A priori, des infos concernant : 
- l'association ZdS
- les licences & propriétés des contenus (tutos, articles)
- la responsabilité de l'admin du site vis à vis des contenus postés dans les forums
- la responsabilité de l'utilisateur vis ç vis des infos qu'il rend publiques dans les forums
- l'interdiction des multis
- l'interdiction de raconter des saloperies, etc.

Mais si je ne me trompe pas, on n'avait pas Arius sur le coup ? :)

**Comment by SpaceFox** [comment]
Maintenant que tu le dis, il me semble que si.

**Comment by cgabard** [comment]
peut etre le relancer sur la ML alors !

**Comment by SpaceFox** [comment]
Je fais ça.

2014-04-14 9:23 GMT+02:00 Christophe Gabard notifications@github.com:

**Comment by SpaceFox** [comment]
C'est fait, cf ici : https://docs.google.com/document/d/1WqYDM6MzRM-u9RBPuSuRrUbbjR4lhquo40tykgX6Yxo/edit?usp=sharing 

J'ai créé la page et collé la version actuelle dedans histoire qu'on ait une idée de ce que ça donne.

**Comment by Eskimon** [comment]
A continuer sur l'issue suivante je suppose : #614 

(et donc fermer celle-ci)

**Comment by SpaceFox** [comment]
Attention, les CGU ne sont pas à jour sur le site, il reste des [Informatiosn de contact] etc.

Le plus étrange, c'est que je suis **certain** que c'est une régression, puisque par exemple tous les liens vers les licences CC pointent vers les CC v3 alors que j'avais mis à jour avec la dernière version d'Arius, qui parle des CC v4. Idem pour la date de parution au JO etc.
Problème : je ne retrouve pas le commit dans lequel c'était fait.

Je suppose que c'était dans un truc qui a sauté lors de l'une des multiples manipulations du dépôt... ce qui est assez flippant, et m'énerve parce que j'y avais passé du temps sur ce merge de merde.

**Comment by Alex-D** [comment]
Peut-être mon merge qui a fait sauter tes modifs : j'ai quasi rien gardé des templates (comme je l'avais prévenu) et je n'ai pas été informé de ce merge.

Si tu retrouve ton commit, link-le ici je remettrais ça au propre.

**Comment by Eskimon** [comment]
Ca doit etre ce commit la je suppose (qui possede les liens V4)

https://github.com/zestedesavoir/zds-site/commit/82f8a831630f995c7ddc30a2896026c954ff1684

**Comment by SpaceFox** [comment]
Oui. Je ne comprends pas pourquoi je ne le voyais plas dans l'historique du
fichier hier.

**Comment by Alex-D** [comment]
C'est noté, je fais ça dans la foulée !

**Comment by Alex-D** [comment]
Voilà qui est fait !

**Comment by Eskimon** [comment]
Du coup il y a encore des choses à faire dans cette issue ?

**Comment by Alex-D** [comment]
Oui, il manque encore le numéro de la CNIL, l'hébergeur et tout.

**Comment by Alex-D** [comment]
J'ai rajouté OVH et son adresse ce qu'il fait qu'il ne manque plus que le numéro de la CNIL que l'on a pas. Je retire le tag "bloquant" car pour l'instant on ne peut pas faire mieux.

Je laisse ouvert pour penser à mettre le n° de la CNIL.

**Comment by SpaceFox** [comment]
Est-ce qu'on a légalement le droit de sortir sans ce fameux n° de CNIL ? Je ne crois pas, et je remets le tag "bloquant" tant qu'on ne m'aura pas prouvé que c'est facultatif.

**Comment by Alex-D** [comment]
MEP = MEP beta ou MEP publique pour toi ?

Pour la beta c'est pas bloquant dans tous les cas.

**Comment by SpaceFox** [comment]
Publique.

**Comment by Alex-D** [comment]
Ah ok, je voyais ça comme étant la MEP beta. Du coup ok, au temps pour moi.

La déclaration est en cours, on devrait avoir le numéro dans la semaine prochaine si tout va bien :)

**Comment by cgabard** [comment]
Eux d'ailleurs le bandeau sur les cookies ça va être bloquant aussi non ?
Le 6 juin 2014 00:28, "Alexandre Demode" notifications@github.com a écrit
:

**Comment by Fumble** [comment]
D'après la CNIL, on n'a pas le droit d'effectuer nos traitements sur le fichier de données en question tant qu'on n'a pas leur accord. Je ne sais même pas si on a le droit de constituer le fichier également mais passons.
Ils annoncent un délai de traitement d'une semaine. Avec un peu de marge et un jour férié, on devrait avoir une réponse mardi ou mercredi si ils tiennent les délais annoncés.
La balle est dans leur camp...

**Comment by Alex-D** [comment]
> Eux d'ailleurs le bandeau sur les cookies ça va être bloquant aussi non ?

Oui, il faut que je m'en occupe... c'est une belle connerie ce truc là. Ca me donne envie de passer par localStorage avec un hack JS ><" mais trop long à dev et flemme et pas spécialement utile.

Juste pour info : un cookie c'est genre quelques ko (4ko je crois). localStorage c'est 5Mo... niveau stockage d'infos y a carrément de quoi faire avec ça. Enfin bref, merci l'UE sur ce coup là \o/

**Comment by Eskimon** [comment]
A fermer s'il ne restait que le num de la CNIL :)
