### ISSUE TITLE
[beta 15.9] : le script de migration de la zep 12 semble mettre à jour le contenu des tout les tutoriels

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3008]
Le script de migration de la zep12, met à jour la date de dernière mise à jour du tutoriel.

Si techniquement certaines choses invisibles du tutoriel ont été mises à jour, le contenu du tutoriel, lui n'a pas pas changé. Le script de migration ne devrait donc pas changer les dates de dernières mise à jour, car ça donne l'impression que les tutoriels sont tout neuf, ce qui n'est pas le cas.

**Comment by pierre-24** [comment]
Que @artragis confirme, mais je pense que tu avais déjà soulevé le problème et qu'on y avait déjà répondu. Non ?

**Comment by artragis** [comment]
Je sais plus, je sais juste uqe les dates ont toujours été casse pied car
l'ancien module n'était pas cohérent (de manière historique, à cause de
vieux bugs qui n'ont pas été corrigés de manière rétroactive). Je pense que
là on a programmé de manière défensive, voilà tout.

Le 28 septembre 2015 18:01, Pierre Beaujean notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
Je confirme que si ce bug est bien présent, il est gênant (mais pas bloquant).

**Comment by DevHugo** [comment]
C'est drôle pour les articles, sur la page d'accueil, la date est correcte mais pas si on consulte l'article en question.

**Comment by artragis** [comment]
c'est la différence entre date de création et date de mise à jour que tu 
vois.

**Comment by DevHugo** [comment]
Je regarderais demain soir, si j'ai un peu de temps. J'en fait une affaire personnel !

**Comment by artragis** [comment]
@DevHugo  ?

**Comment by DevHugo** [comment]
C'est compliqué à corriger si tu veux reprendre vas y.

**Comment by pierre-24** [comment]
Hop :)
