### ISSUE TITLE
[beta 15.9] Erreur 500 lors d'une citation malencontreuse d'une réactions

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3009]
Lien incriminé : https://beta.zestedesavoir.com/contenus/reactions/ajouter/?cite=75912&pk=205

Pouf **erreur 500**.

On ne devrait jamais avoir d'erreur 500 dans la vraie vie.

**Comment by GerardPaligot** [comment]
Les identifiants sont corrects ?

**Comment by pierre-24** [comment]
C'est corrigé, à priori :)
