### ISSUE TITLE
Ajouter des test unitaires de récupération sur toutes les URLs "get"

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#301]
Aujourd'hui la plupart des tests unitaires ne concernent que la création et la récupération des pages.
L'idée est d'ajouter des tests pour l'affichage des pages, afin qu'une évolution ne casse pas l'affichage sans qu'on soit au courant.

Vérifier le code retour de la page et 2-3 données importantes devrait suffire.

**Comment by firm1** [comment]
@SpaceFox : J'ai vu que la tache t'es assignée. De mon coté, je pense que je vais être obligé d'en faire (des test) sur les urls pour vérifier pas mal de conneries (en guest, membre et staff).

Du coup je te propose cette issue comme lieu d'échange pour savoir les tests sur lesquels tu es en train de bosser.
En ce qui me concerne, j'en suis aux urls des **tutos**, tu peux donc me les laisser.

Je reviens sur cet issue si je m’apprête à toucher à autre chose.

**Comment by SpaceFox** [comment]
Facile : j'ai poussé ma branche :
https://github.com/Taluu/ZesteDeSavoir/tree/issue_301
Si ça t'arrange tu peux même bosser dessus.

Jusqu'ici j'ai fait :
- Members
- Forum
- Et en prime la correction d'un bug que j'ai trouvé en faisant Forum (un
  truc deprecated)

Le _gros_ manque, c'est Articles - mais là il faudrait des tests plus
généraux, et c'est relativement compliqué.

**Comment by firm1** [comment]
> Facile : j'ai poussé ma branche : 

Ah excellente idée. Je pense que je travaillerai dessus aussi. Après les tutos du coup je prend les articles.

**Comment by SpaceFox** [comment]
> Ah excellente idée.

Réflexe du boulot où seul le serveur *origin *est sauvegardé :)

**Comment by firm1** [comment]
normalement, il ne manque plus que des tests sur les urls de galleries.

**Comment by firm1** [comment]
Terminé
