### ISSUE TITLE
[beta 15.9] La beta est lancée en mode debug=true

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3010]
Sur la beta, django est lancée en mode `debug=True`, ce qui fait que les erreurs 500 ne s'affichent pas comme dans la vraie vie.

En cas d'erreur 500 on arrive a lire des informations potentiellement privées en plus du fait que ça ralenti pas mal la beta

**Comment by SpaceFox** [comment]
Argh.

**Comment by pierre-24** [comment]
@Eskimon et @sandhose ?

**Comment by Eskimon** [comment]
ok c'est remis à False. Pour des trucs comme ca @firm1 un MP aurait été aussi efficace plutot que de polluer le bugtracker.

**Comment by GerardPaligot** [comment]
C'est tendu comme un string ici ! \o/
