### ISSUE TITLE
[beta 15.9] : les urls en beta n'ont pas de redirection permanentes sur les bonnes urls

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3011]
En testant les liens suivant : 
- https://beta.zestedesavoir.com/contenus/beta/779/p/
- https://beta.zestedesavoir.com/contenus/beta/779/q/
- https://beta.zestedesavoir.com/contenus/beta/779/a/

On tombe à chaque fois sur le même tutoriel sans que l'url ne change.

Toutes ses urls devraient rediriger vers "https://beta.zestedesavoir.com/contenus/beta/779/la-programmation-en-c-moderne/" qui est la vraie url de beta.

**Comment by artragis** [comment]
Je peux le tuer?

Tu nous a fait le même coup la dernière fois.

Non seulement c'est une chose que TU as demandée, mais en plus OSEF puisque les béta ne sont PAS référencée.

**Comment by firm1** [comment]
> Non seulement c'est une chose que TU as demandée

J'ai demandé que les anciennes urls de beta soit dirigée vers les nouvelles adresses de la beta, ça c'est fait.

Mais il me semble que c'est une demande de la spec que toutes les urls à base de `/id/mauvais-slug` redirige vers `/id/bon-slug` de manière permanente. D'autant plus que c'est le comportement qu'on a sur les urls offline. Pour le coup c'est incohérent

**Comment by artragis** [comment]
on n'a ce comportement que sur les url online car... elles sont sensibles au slug. La béta ne l'est pas mais comme je le disais OSEF : le SEO importe peu pour la béta.

Outre le fait que tu nous avais dit que c'était incohérent qu'on lance vers les vraies urls à l'époque. bref. (je prends @pierre-24 comme témoin)

**Comment by pierre-24** [comment]
Je confirme qu'on a déjà eu ce débat, qu'on t'as déjà répondu pourquoi c'était pas possible et qu'on a déjà dit pourquoi OSEF du SEO.

**Comment by GerardPaligot** [comment]
Par curiosité (sans animosité parce que je constate que c'est tendu entre vous et @firm1), on pourrait connaitre les raisons techniques pour lesquelles ce n'est pas possible ?

**Comment by artragis** [comment]
Bah en soit c'est possible, ça a été changé parce que firm1 trouvait ça 
incohérent avec la prod actuelle (qui est insensible au slug). Moi j'y 
peux rien.

**Comment by firm1** [comment]
> ah en soit c'est possible, ça a été changé parce que firm1 trouvait
> ça incohérent avec la prod actuelle (qui est insensible au slug).

Je veux des sources de cette affirmation. :)

**Comment by pierre-24** [comment]
[Tout est là](https://github.com/artragis/zds-site/issues/353) :)

**Comment by artragis** [comment]
Bonj je refais l'historique avec preuve car j'ai un peu médit quand même, désolé pour ça @firm1.

Donc tout commence avec la détection d'un bug : nous ne supportons pas les urls de béta telles qu'on les a dans le premier module : 

https://github.com/artragis/zds-site/issues/305

Comme ils s'agit ici d'un problème de compatibilité, je prends donc le comportement de la prod actuelle comme référence : seule la PK compte.

Du coup firm1 lance cette issue : https://github.com/artragis/zds-site/issues/353

où nous lui expliquons pourquoi ce n'est pas un bug mais une vraie fonctionnalité en fonction de ce que faisait l'ancien module (on est en mode "compatibilité", je rappelle).

Donc l'issue actuelle n'en est pas une ! Elle a déjà été réglée et le comportement justifié.

**Comment by firm1** [comment]
Ah JUSTICE RETABLIE ... je prefere ça.

Mais le problème de l'issue reste pour moi un bug. On peut decider de ne
pas le corriger (parce qu'il est pas grave) mais c'est quand meme un bug.

**Comment by artragis** [comment]
un bug de l'ancien module qu'on doit mimer pour être compatible.

**Comment by SpaceFox** [comment]
> Mais le problème de l'issue reste pour moi un bug. On peut decider de ne pas le corriger (parce qu'il est pas grave) mais c'est quand meme un bug.

Non, si c'est un comportement volontaire, ça ne peut pas être un bug. Et à partir du moment où on décide de ne pas le corriger (décision volontaire, pas « OSEF on attend que quelqu'un se bouge ») ça devient de facto une fonctionnalité.

**Comment by pierre-24** [comment]
Sur l'argument "on fait comme en prod", c'est bien une fonctionnalité (issue d'une observation logique : le slug est pas fixé et le lien du premier message sur le forum beta doit toujours fonctionner). Une possibilité serait "simplement" de retirer le slug, comme ça tout le monde est content.

**Comment by artragis** [comment]
du coup on peut fermer?

**Comment by artragis** [comment]
@GerardPaligot @pierre-24 ?

**Comment by GerardPaligot** [comment]
@SpaceFox semble ok avec vous. Je ferme.
