### ISSUE TITLE
[beta 15.9] Erreur 500 lors d'une citation malencontreuse d'une réaction saison 2

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3012]
Attention ce bug n'est pas un doublon de  #3009 (l'exception levée est différente).

Lien incriminé : https://beta.zestedesavoir.com/contenus/reactions/editer/?message=736718&pk=12

Pouf **erreur 500**.

On ne devrait jamais avoir d'erreur 500 dans la vraie vie.

**Comment by pierre-24** [comment]
Pour celui là, on est bon aussi =)
