### ISSUE TITLE
[beta 15.9] : la recherche ne fonctionne pas

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3013]
Une [recherche sur le terme HTML](https://beta.zestedesavoir.com/rechercher/?q=HTML) ne renvoit aucun résultat sur la beta. Un problème d'infra j'imagine.

On ne peut donc pas la tester

**Comment by artragis** [comment]
apprendre à lire... @Eskimon n'a pas eu le temps del a configurer.

**Comment by firm1** [comment]
Ah j'ai lu en grosse diagonale :( ... bon bah à fermer dès que c'est fait.

**Comment by GerardPaligot** [comment]
Nous en sommes où dans la mise en place de la recherche ? Il ne reste plus que ça à tester si je comprends bien

**Comment by pierre-24** [comment]
Oui. Mais faut arriver à mettre @sandhose et @DevHugo dans la même conversation IRC ;)

**Comment by DevHugo** [comment]
Je vais lui envoyer un mp.

**Comment by DevHugo** [comment]
Sandhose, à fait le nécessaire, la recherche fonctionne, merci à lui !

**Comment by artragis** [comment]
<3 peut être une release ce week-end alors @Eskimon (en ~vacances~
indisponibilité, non?) @spacefox @sandhose

2015-10-09 16:47 GMT+02:00 Hugo Courtecuisse notifications@github.com:

**Comment by DevHugo** [comment]
Il est pas la Eskimon avant la semaine prochaine, il me l'a redit dans le MP.

**Comment by SpaceFox** [comment]
Quant à moi, je reviens dimanche soir.

**Comment by artragis** [comment]
donc @sandhose (qui a déjà permis le test de la zep-12 donc il sait faire
une release non?)

2015-10-09 17:49 GMT+02:00 SpaceFox notifications@github.com:

**Comment by sandhose** [comment]
Je saurais faire, mais j'ai pas d'accès prod

**Comment by artragis** [comment]
release = preprod.

**Comment by sandhose** [comment]
Effectivement, j'ai répondu un peu vite

Du coup ouais, j'ai le temps ce Week-end s'il le faut

**Comment by GerardPaligot** [comment]
D'après ce que je vois sur la beta, la recherche fonctionne. On peut fermer non ?

**Comment by DevHugo** [comment]
Ouai.

**Comment by DevHugo** [comment]
Pourquoi tu me fait peur comme ça @sandhose  ? ^^

**Comment by artragis** [comment]
ah ah

2015-10-28 9:55 GMT+01:00 Hugo Courtecuisse notifications@github.com:
