### ISSUE TITLE
[beta 15.9] Incohérence entre les règles de validations du formulaire et l'import d'un contenu

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3014]
Scénario:
- Je crée un article
- J'essaye de créer une section dont le nom est "...", on me répond "ce titre n'est pas valide"
- Je crée donc une section dont le nom est "suspens"
- Je télécharge l'archive
- Je modifie le manifest.json pour mettre comme titre de la section "..."
- J'importe cette version du contenu
- L'import accepte de changer le titre par "..." alors que le formulaire me l'a refusé ... _strange_

Je taggue en bug

**Comment by pierre-24** [comment]
@artragis, on avait statué là dessus, non ?

**Comment by artragis** [comment]
Oui : si tu changes juste le titre, pas grave, c'est le slug qui compte.

**Comment by GerardPaligot** [comment]
@firm1 Est-ce que le slug a changé ou il est resté suspense ?

**Comment by artragis** [comment]
S'il avait été changé, ça aurait lancé une erreur.

**Comment by firm1** [comment]
J'ai pas regardé le slug par la suite (je ferais ça lors de ma prochaine
serie de test). Mais le fait que le formulaire d'import accepte un titre
qui est refusé par le formulaire de creation constitue dejà une
incoherence. Je e pense pas que se soit la seule, car ça ressemble a des
duplicate de code ou a des catch mal placés quelque part.

**Comment by pierre-24** [comment]
Y'a pas d'incohérence ! Tu as toi même demandé (le lien dans 30 secondes) à pouvoir changer le slug à la main dans l'archive sans que ça ne plante. Ce qu'on a fait. Désolé si on fait confiance au slug que tu as indiqué dans l'archive et qu'on ne s'amuse pas à vérifier chaque titre pour voir si c'est cohérent. Ce qui compte C'EST QUE LE FICHIER EXISTE !

**Comment by pierre-24** [comment]
[lien et tout ça](https://github.com/artragis/zds-site/issues/368#issue-105244195). Tu passes ton temps à signaler des choses que tu as déjà signalé, @firm1. Les signaler ici ne va pas me faire changer d'avis et tu perd ton temps. Si tu as des VRAI trucs à raconter, là je t'écoute.

**Comment by firm1** [comment]
Arf ... ce n'est pas la peine de s'enerver. Relis bien mes message s'il te
plait.

Le lun. 28 sept. 2015 19:45, Pierre Beaujean notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
Ce que soulève @firm1 ici n'est pas la possibilité de changer le slug ou non mais de changer le titre dans les différentes possibilités d'édition d'un tutoriel (à savoir l'édit par le site ou l'édit par l'import). Là dessus, il y a bien une _incohérence_ puisque d'un côté c'est possible, de l'autre non. Par contre, nous pouvons discuter si oui ou non c'est un comportement voulu ou pas.

PS : Be cool. Je sais que les vagues de test de @firm1 sont lourdes pour les développeurs concernés mais vous êtes hyper agressif sur chaque issue. Donnez simplement les sources de vos affirmations et nous irons de l'avant ! :)

**Comment by SpaceFox** [comment]
À noter que cette incohérence n'est pas _forcément_ un bug. Les cas où on peut faire des choses différentes sur un élément E à l'aide des commandes A et B sont légion (à commencer par les formulaires d'admin Django) et peuvent être légitimes (l'une des commandes n'est accessible que par des utilisateurs avancés).

**Comment by pierre-24** [comment]
Mais c'est pas un bug, c'est une fonctionnalité !

_Namely_ : en édition sur le site, l'auteur n'as pas le choix de son slug, il est obligé de prendre ce que le système lui donne, et il se trouve que le système se base sur le titre (on pourrait très bien se baser sur un nombre aléatoire ou un hash du texte, osef) : forcément, il existe des titres qui génèrent des slugs vide (tout comme un extrait vide générerait toujours le même hash et finirait donc par se faire jeter aussi)

En import, l'auteur a le choix de son slug et fait ce qu'il veut tant qu'il respecte les règles (=unicité du slug). Tant mieux pour lui si il tient absolument à appeler son extrait "...", eh bien il peut. RIEN ne l'interdit.

**Comment by artragis** [comment]
Oui et non.
On l'a djéà expliqué : sur l'interface de tutoriel, que nous n'avons pas 
changé, nous calculons le slug à partir du titre.
Sur la partie import, que chacun peut regarder comme il veut, on utilise 
le rasoir d'ockam : comme le slug est fourni, on laisse la personne 
choisir le slug, notamment car cette personne aimerait sûrement éviter 
de faire des fichiers qui s'appellent le-projet-nanosatellite-est-un 
projet-extremement-ambitieux-vous-pourriez-nous-donner-quelques-chiffres-pour-qu’on-se-représente.md 
et voudront sûrement question-4.md
Donc non.

**Comment by artragis** [comment]
Juste pour préciser : mon exemple est tiré de la vie réelle.

**Comment by pierre-24** [comment]
> Juste pour préciser : mon exemple est tiré de la vie réelle.

... Un peu _cheatée_ quand même puisque c'est notre propre script de migration :p

**Comment by SpaceFox** [comment]
Donc, c'est pas un bug, je ferme. À rouvrir proprement si y'a une vraie demande d'évolution ici.

**Comment by artragis** [comment]
Bah non. C'est un article qui existe vraiment en prod, si l'article 
était créé avec la zep-12 sur le site il aurait ce nom de fichier là. 
Quand l'utilisateur lambda rédige sur le site, il s'en fiche. Quand il 
rédige chez lui c'est sûrement son désire de modifier les slugs. Ou au 
contraire de garder des fichiers "mal" nommés alors qu'il change le titre.

**Comment by firm1** [comment]
Pour info, une fois que le titre de mon article a été modifié via importation avec "...", je ne peux plus le modifier via l'interface en ligne, je tombe sur une erreur 500.

**Comment by artragis** [comment]
Yep, ça c'est un bug différent. Apparamment il cherche à slugifier le 
titre à un moment donner lors du renommage. @pierre-24tu t'en occupes?

**Comment by SpaceFox** [comment]
C'est un bug différent, il faudrait rouvrir un vrai ticket…

**Comment by Situphen** [comment]
Par contre, cette fonctionnalité est sympa mais elle risque de demander plus de boulots aux validateurs qui vont devoir vérifier que les slugs ne sont pas insultants, si ? Car si quelqu'un créé un tutoriel avec un conteneur nommé "Super titre", ce dernier aura un slug "super-titre". S'il importe une archive avec un nouveau slug "quelque-chose-d-insultant", le titre ne changera pas ? Or, le slug n'est pas super voyant.
