### ISSUE TITLE
[beta 15.9] deux types de sommaires affichés sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3015]
Sur mobile, on a deux types de sommaires adfichés lorsqu'on consulte un chapitre de tutoriel. [celui ci par exemple](https://beta.zestedesavoir.com/tutoriels/641/arduino-premiers-pas-en-informatique-embarquee/744_la-communication-avec-arduino/3426_generalites-sur-la-voie-serie/).

Screenshot : 

![28 septembre 2015 182853 gmt 0200](https://cloud.githubusercontent.com/assets/6066015/10141879/343c3abc-660f-11e5-8af9-b73835410a40.jpg)

**Comment by artragis** [comment]
pourquoi toomuch : on parle pas du même sommaire.

si tu penses qu'un autre mot doit être choisi, peux-tu le proposer stp?

**Comment by firm1** [comment]
C'est normal qu'on ait deux types de sommaires (celui du chapitre et celui
du tutoriel) affichés sur mobile ?

**Comment by GerardPaligot** [comment]
C'est le comportement actuel de la prod ([pour preuve](https://zestedesavoir.com/tutoriels/537/arduino-premiers-pas-en-informatique-embarquee/744/la-communication-avec-arduino/3426/generalites-sur-la-voie-serie/)).

Donc pas lié à la bêta et encore moins un bug. Au pire, une évolution.

**Comment by SpaceFox** [comment]
C'est pas un bug donc je ferme. À rouvrir proprement si tu veux une évolution.

**Comment by Situphen** [comment]
Personnellement je trouve ça même super cool qu'on ait deux sommaires ! Le premier permet de naviguer entre les titres de la page où tu es (avec des ancres). Le deuxième permet de naviguer dans tout le tutoriel. Je trouve logique de séparer les deux, non ? (Surtout que le deuxième à souvent une taille assez grande.)
