### ISSUE TITLE
[beta 15.9] Erreur dans le MP de mise en bêta

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#3018]
[Comme reporté sur le forum](https://zestedesavoir.com/forums/sujet/4149/la-beta-cest-plus-fort-que-toi/?page=2#p75401) : 

> Juste un p'tit détail que je viens de remarquer, car je n'ai pas encore eu le temps de faire tout le tour, mais dans le MP de mise en bêta, on a :
> 
> > Bonjour ,
> 
> Or, l'espace entre le « bonjour », et la virgule n'a pas lieu d'être. ^^

**Comment by artragis** [comment]
Le bug est ici que le user n'est pas bien imprimé on doit donc oublier de le passer dans le dictionnaire.

**Comment by pierre-24** [comment]
C'est pour ça que j'ai taggé "facile", c'est probablement une connerie du genre

**Comment by pierre-24** [comment]
Voilà :)
