### ISSUE TITLE
On ne peut plus éditer un article dont le titre est "..."

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#3020]
[Comme reporté ici](https://github.com/zestedesavoir/zds-site/issues/3014#issuecomment-143838726) : 

> Pour info, une fois que le titre de mon article a été modifié via importation avec "...", je ne peux plus le modifier via l'interface en ligne, je tombe sur une erreur 500.

À tester aussi avec les parties/chapitres/extraits.

**Comment by artragis** [comment]
hum ce qui est étrange c'est qu'il parle de titre de l'article dnas une issue qui parle de titre de section. Théoriquement le titre de l'article ne peut pas être ... car il y a des vérifications de partout pour l'article/tuto. Par contre pour les sections/chapitres/parties on laisse faire donc il faut regarder dans l'interface de modification si on fait pas n'imps avec le slug ou slugify(title).

**Comment by pierre-24** [comment]
Finalement, c'est [ce commit](https://github.com/pierre-24/zds-site/commit/a7d44241969bf75d382fc6df02e5ca14aebb5b43) (qui ratisse vachement large), qui en aura eu raison : on ne peut finalement plus importer une rachive avec le titre "..." !
