### ISSUE TITLE
Mise à jour de la toolbar de l'éditeur

### ISSUE THREAD

**Issue by Thunderseb** [zestedesavoir/zds-site#3021]
Coucou, 

J'ai fait une mise à jour du script editor.js ( https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/editor.js ). Voici ce qu'il y a de neuf : 
- ajout d'un bouton pour insérer un code inline
- ajout d'un bouton + sous-menu avec les smileys
- ajout d'un bouton + sous-menu avec des caractères spéciaux (du genre guillemets français et majuscules accentuées)
- pour les boites de dialogue image et lien, les champs ont le focus
- ajout d'une class CSS "zform-button-useless" sur certains boutons moins utiles dans l'optique des les masquer avec des media-queries CSS pour rendre le truc un peu plus responsive

Comme y'a deux nouveaux boutons, y'a deux nouvelles images à ajouter dans les CSS (fichier + icônes donné). 

Vlà le zip avec les fichiers à intégrer : 

http://s.sdlm.be/zestedesavoir/editor.js-29-09-2015.zip

**Comment by Situphen** [comment]
Cool, j'essaye de regarder ça ce soir ! :)

**Comment by Thunderseb** [comment]
Btw, je ferai une autre màj car je compte intégrer, dans la modale d'insertion d'image, un moyen de parcourir la galerie. 

Je prévois aussi la possibilité d'afficher/masquer certains boutons et de changer leur ordre. Mais ce sera pour après. Le code est déjà prévu pour (l'ordre est défini par défaut dans `zForm.buttons`).

**Comment by Situphen** [comment]
En gros tu comptes développer la ZEP sur l'éditeur ? :)

**Comment by Situphen** [comment]
J'ai transposé le code de ton archive dans celui de ZdS, ce qui donne [ça](https://github.com/zestedesavoir/zds-site/compare/dev...Situphen:update-editor).

J'ai fait :
- copier/coller du code JS de l'éditeur
- copier/coller du CSS dans le fichier SCSS (les deux nouveaux icônes)
- création d'une règle pour cacher les boutons qui ont la classe `zform-button-useless`

Je me suis permis de faire quelques petits changements :
- suppression des espaces inutiles (ligne vide ou fin de ligne)
- transformation de quelques tabulations perdues dans le code en espaces
- traduction de certains commentaires en anglais (je ferais les derniers plus tard)

Par ailleurs, j'ai vu d'après ton code que tu supportes IE ? ZdS ne support pas IE donc ce n'est pas la peine de te casser la tête. (Je n'ai néanmoins pas supprimé le code actuel spécial IE car je sais que ça représente du boulot en plus.)

Peux-tu écrire un message dans le sujet de la ZEP sur l'éditeur pour parler des modifications que tu as codé et que tu comptes coder ? Notamment des boutons a cacher sur mobile qui, je pense, méritent un débat pour savoir lesquels cacher ! :)

**Comment by DevHugo** [comment]
Merci, j'attend ces nouvelles fonctionnalisées avec impatience ! Surtout pour les images et la gallerie !

**Comment by GerardPaligot** [comment]
> En gros tu comptes développer la ZEP sur l'éditeur ? :)

Je connais pas la ZEP sur l'éditeur mais si la ZEP se contentait de rajouter des boutons dans l'éditeur actuel, je serais déçu. :)

**Comment by DevHugo** [comment]
ça allait plus loin, de mémoire, c'était, upload d'image automatique (déplacer dans le textarea), à la GitHub quoi, les packs de smileys, et d'autres trucs que j'ai oublié.

**Comment by artragis** [comment]
dis @sandhose pourquoi la PR n'est pas mise en place?

**Comment by artragis** [comment]
heu c'était @Situphen

**Comment by Situphen** [comment]
Euh, très bonne question !

**Comment by SpaceFox** [comment]
Hop, c'est mergé !
