### ISSUE TITLE
Erreur 500 lors de l'inscription en cas d'indisponibilité d'un serveur de mail

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3022]
Lorsqu'on essaye de s'inscrire sur le site ET que le serveur de mail n'est pas disponible, on se prend une erreur 500 (ça arrive sur la beta actuellement qui n'a pas de serveur mail).

Un try/catch oublié dans le module membre ?

**Comment by pierre-24** [comment]
Vu que justement, la bêta n'as pas de serveur mail, j'ai du mal à séparer cette cause là et un oubli qui serait légitime. Je laisse investiguer qui de droit avec les accès qui vont bien.

**Comment by GerardPaligot** [comment]
On ne devrait jamais avoir une erreur 500 mais c'est pas lié à la release actuelle, vous avez d'autres choses à faire plus urgentes. :)

**Comment by gustavi** [comment]
Alors c'est une 500 qui doit faire planter complètement l'application puisque c'est l'erreur 500 avec Clem en gros et non celle avec l'interface du site qui apparait. De plus, ça n’apparait donc pas dans Sentry.
