### ISSUE TITLE
[beta 15.9] L'abonnement aux contenus ne marche pas comme prévu

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3023]
Sur la beta quelqu'un a posté un message dans les commentaires de l'[article Demo de Arius](https://beta.zestedesavoir.com/articles/81/article-demo/). Je reçois dans mes notifications les nouveaux messages postés dans cet article alors que : 
- Je ne suis pas auteur de cet article
- Je n'ai pas validé cet article
- Je n'ai pas posté de commentaire à cet article

J'aimerai donc savoir comme j'ai pu être abonné aux commentaires de cet article sans le vouloir.

ça ressemble à un bug car je n'ai pas vu de règle dans la documentation qui décrit ce type d'abonnement.

**Comment by GerardPaligot** [comment]
C'est bizarre comme bug. Sauf énormité dans le code, est-ce que ça serait pas une mauvaise manipulation dans la copie des données de la prod ?

**Comment by pierre-24** [comment]
Ce bug est apparu à un moment (mais avec beaucoup plus d’ampleur, j'avais 60 notifications). On a du supprimer énormément des objets correspondants via le script de migration ([ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/management/commands/migrate_to_zep12.py#L364-L371)), mais le code tient énormément de la magie noire. Il est probable qu'il ne soit pas tout à fait correct.

Ceci étant dit, l'article d'Arius a été posté **après** la migration, si je ne m'abuse, donc la cause est peut-être à chercher ailleurs.

**Comment by GerardPaligot** [comment]
Bon alors on peut écarter la mauvaise manipulation sur la copie des données. :)

**Comment by pierre-24** [comment]
Bon, y'a effectivement un code hyperactif quelque part, j'ai une notif alors que j'ai seulement visité [cet article](https://beta.zestedesavoir.com/articles/837/binouse/?page=1#p76870). Ça m'as l'air d'une putain de régression, en plus :(

**Comment by artragis** [comment]
je sais pourquoi : on marque automatiquement l'article comme lu dès qu'on le visite. Il faut donc y ajouter une condition : si l'article est déjà lu.

**Comment by pierre-24** [comment]
... Hein ?

**Comment by artragis** [comment]
Va dans DisplaySingleOnlineContent: elle se termine par mark_read. Voilà 
ta cause.

**Comment by pierre-24** [comment]
Aaaah, ok :)

**Comment by pierre-24** [comment]
Ok :)
