### ISSUE TITLE
[beta 15.9] Les commentaires modérés dans les contenus ne sont pas si modérés que ça

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3024]
[Ce message](https://beta.zestedesavoir.com/articles/81/article-demo/?page=1#p76864) a été caché dans les commentaires de l'article. Normalement un utilisateur non staff ne devrait pas pouvoir le visualiser.

Cependant, si je vais sur [cet url](https://beta.zestedesavoir.com/contenus/reactions/ajouter/?cite=76864&pk=180) je peux voir le message qui est censé être caché.

It's a bug car on devrait avoir au moins une 403

**Comment by GerardPaligot** [comment]
J'ai une erreur 404 de mon côté.

**Comment by firm1** [comment]
Peut être parce que je suis l'auteur du message ?

**Comment by Situphen** [comment]
Perso, j'ai :

```
> ....
Source: [boubou](/articles/81/article-demo/?page=1#p76864)
```

**Comment by GerardPaligot** [comment]
Ah, bizarrement j'ai la même chose que @Situphen maintenant. J'ai du faire une mauvaise manipulation.

**Comment by pierre-24** [comment]
Toutafé, c'est un bug.
