### ISSUE TITLE
[beta 15.9] Absence de la date de publication dans le pdf d'un article publié

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3025]
J'ai publié [un article](https://beta.zestedesavoir.com/articles/837/binouse/), le pdf a été généré mais il ne contient pas de date.

It's smells like a bug

**Comment by pierre-24** [comment]
_It does_. Ceci dit, est ce que tu pourrait donner le _markdown_, qu'on voit d'ou qu'il vient le bug ?

**Comment by firm1** [comment]
Je crois qu'on ne peut plus telecharger les markdown depuis le site.
D'ailleurs ça ressemble a une regression aussi.

Le mar. 29 sept. 2015 19:06, Pierre Beaujean notifications@github.com a
écrit :

**Comment by pierre-24** [comment]
> Je crois qu'on ne peut plus telecharger les markdown depuis le site. D'ailleurs ça ressemble a une regression aussi.

Logiquement, [seuls les admins et les auteurs](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_published.py#L197) peuvent, ce qui, si je ne m'abuse, est _iso_-prod.

**Comment by pierre-24** [comment]
Après, [cette condition](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/base.html#L80) passe sa vie à me clamser entre les doigts.

**Comment by firm1** [comment]
Ah je le vois le markdown. je te sors le code quand tombe sur un pc

Le mar. 29 sept. 2015 19:16, Pierre Beaujean notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
Je confirme le bug avec [ce tutoriel](https://beta.zestedesavoir.com/articles/838/merci-de-le-valider/).

Archive dispo ici : https://www.dropbox.com/s/srhz9qudv8olm2k/merci-de-le-valider.zip?dl=0

**Comment by pierre-24** [comment]
Mouais. À mon avis, on est encore en train de confondre date de publication et de modifications. Voir pire, un bug idiot : la date est intégré mais on oublie le `save()` qui va bien.

**Comment by DevHugo** [comment]
C'est pas moi et ma modification à la con qui ont tout cassé ?  Faudrait regarder de ce cote, je crois me souvienir que la date était la avant.

**Comment by pierre-24** [comment]
ça vaudrait presque la peine de rajouter quelque part dans le T.U. de validation un test qui vérifier la présence de la date à la bonne ligne.

**Comment by DevHugo** [comment]
C'est facile en plus à tester unitairement

**Comment by DevHugo** [comment]
Je regarde ce week-end

**Comment by artragis** [comment]
@DevHugo ?

**Comment by DevHugo** [comment]
J'ai pas oublié, j'ai juste pas trouvé comment faire

**Comment by artragis** [comment]
Ok merci du rapport.

**Comment by DevHugo** [comment]
@GerardPaligot  Tu te rapelle comment tu as créé le tutoriel ? L'archive est plus dispo =(. Surtout comment tu l'as validé ? as tu coché la case, "modification majeur".

**Comment by GerardPaligot** [comment]
@DevHugo Sans doute une version majeur puisque c'était la première validation. De toute façon, j'ai laissé les valeurs par défaut.

Archive à nouveau dispo.

**Comment by pierre-24** [comment]
J'arrive pas à reproduire ce bug en local o_O

**Comment by DevHugo** [comment]
Si tu coche pas la case "modification majeur", ça produit une erreur, mais dans la méthode « publish_content », c'est un peu le bordel avec les dates de publications et la update_date. On devrait faire un point sur ce sujet.

**Comment by pierre-24** [comment]
Je suis d'accord !

**Comment by DevHugo** [comment]
J'écrirais un mp, demain, dans la journée.

**Comment by DevHugo** [comment]
C'est fait, je vous est envoyé un mp récap. 

Pour que ça marche, il faut mettre à jours le champ pubdate avant le render_to_string dans la méthode publish_content. C'est intiment liés à la maniére dont on gére les dates, et donc de ce ticket.

https://github.com/zestedesavoir/zds-site/issues/3008#issuecomment-145213305

**Comment by pierre-24** [comment]
Bon, je ferme, on confirmera au prochain test ;-)
