### ISSUE TITLE
Le message de proposition de correction contient du makdown trop chargé

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3026]
Lorsque quelqu'un me propose des corrections sur mon article, je reçois un MP avec un message des correctifs.

Le problème c'est que ce message possède beaucoup de retour à la ligne, et donc quand on cite le fameux message on se retrouve avec plein de retour à supprimer.

Un problème vraiment mineur, mais ça fait toujours du bien quand le message est bon.

**Comment by pierre-24** [comment]
Je pense qu'on est sur une évolution, à ce niveau là, non ?

**Comment by artragis** [comment]
Je pense aussi, ça serait bien qu'on enlève le tage "beta 15.9" pour que ça nous facilite le travail de débug.

**Comment by pierre-24** [comment]
Fait :)
