### ISSUE TITLE
[beta 15.9] Aucun PDF généré

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3027]
Il n'y a aucun PDF généré pour cet [article](https://beta.zestedesavoir.com/articles/81/article-demo/).

**Comment by pierre-24** [comment]
Je ne sais pas exactement quand il y a été publié, mais il est possible qu'il aie été publié avec la génération des PDFs désactivés. Puis, on parle de _pandoc_, là ;)

Vu que le PDF a été généré [pour cet article là](https://beta.zestedesavoir.com/articles/837/binouse/), je ne m'inquiéterai pas outre mesure :)
