### ISSUE TITLE
[beta 15.9] Le titre des articles ne semble pas versionné

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3028]
Scénario : 
- Je crée un article
- Je demande la publication
- L'article est publié par quelqu'un d'autre
- Je modifie le titre de la version brouillon
- Le titre est modifié aussi en ligne sans revalidation : ça c'est pas bien

It's smells like a bug.

**Comment by GerardPaligot** [comment]
C'est pas déjà en prod ce comportement ?

**Comment by firm1** [comment]
Nope.

Le mar. 29 sept. 2015 18:52, Gérard Paligot notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
Je confirme après un rapide test. C'est bien une régression.

**Comment by pierre-24** [comment]
> Le titre est modifié aussi en ligne sans revalidation : ça c'est pas bien

... Partout ?

**Comment by firm1** [comment]
paltou sur la version online.

Le mar. 29 sept. 2015 19:11, Pierre Beaujean notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
Sur un contenu migré pré ZEP (je sais pas si c'est important), je ne rencontre pas le bug.

Mes tests ont été effectués sur cet [article](https://beta.zestedesavoir.com/articles/102/zeste-de-savoir-passe-en-version-1-7/). Sur mon brouillon, j'ai rajouté gaston à la fin du titre pour avoir : Zeste de Savoir passe en version 1.7 gaston

**Comment by artragis** [comment]
le titre de l'issue est incorrect : le titre est bel et bien versionné.
ensuite, pour ce qui est du titre affiché, c'est franchement étrange : théoriquement le titre ne peut être changé qu'à la publication, ça sent l'erreur dans les templates.

Le titre modifié apparait sur quelles pages online?

**Comment by GerardPaligot** [comment]
Je confirme plus ou moins ce bug.
- Mon contenu a été validé : https://beta.zestedesavoir.com/contenus/838/merci-de-lavoir-valide/
- J'ai changé son titre de "Merci de le valider !" à "Merci de l'avoir validé"
- Le titre dans la version publiée n'a pas changé.
- Par contre, dans la liste des tutoriels, c'est le nouveau titre qui est utilisé.

J'ai donné les droits à @pierre-24 et @artragis sur le tutoriel.

**Comment by artragis** [comment]
Donc c'est pas vraiment un bug, non. Pour le lecteur c'est bien le premier
titre qui est affiché, non?

Le 30 septembre 2015 10:29, Gérard Paligot notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
Si, il y a bien un bug. 

Dans la liste [ici](https://beta.zestedesavoir.com/), tu vois le nouveau titre alors que ça ne devrait pas.

**Comment by artragis** [comment]
Donc ça c'est un bug de template. Merci d'avoir bien qualifié le bug.

Le 30 septembre 2015 10:34, Gérard Paligot notifications@github.com a
écrit :

**Comment by artragis** [comment]
à fermer puisque tu as mergé. @Situphen

**Comment by Situphen** [comment]
A oui, merci
