### ISSUE TITLE
[beta 15.9] L'auteur ne follow pas automatiquement son topic de beta

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3029]
Lorsqu'un auteur met sont contenu en beta, un sujet est crée. C'est une bonne chose.

Le problème vient du fait que ce topic n'est pas follow automatiquement par l'auteur.

es una regresión.

**Comment by pierre-24** [comment]
_Si_

Bon, [c'est étonnant](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_contents.py#L1358-L1362), mais peut-être que je me suis planté quelque part (en plus, je pensais que ce comportement était testé unitairement :'( )

**Comment by firm1** [comment]
Comme je le craignais, ainsi que @GerardPaligot dans la PR de correction, cette issue n'est pas corrigée en RC3.

Je la réouvre donc.

La preuve en screen (on me propose encore de suivre mon propre topic) :

![follow-down](https://cloud.githubusercontent.com/assets/6066015/10480704/f561bc68-726b-11e5-83a6-5bf2497dbb4d.PNG)

**Comment by pierre-24** [comment]
M'enfin, [que fait cette ligne de code, alors](https://github.com/zestedesavoir/zds-site/pull/3033/files#r40820893) ? :o

**Comment by pierre-24** [comment]
EDIT : non, [celle là](https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/forums.py#L149) ?

**Comment by GerardPaligot** [comment]
@pierre-24 Tu as vraiment testé quand tu as fais la QA ?

**Comment by pierre-24** [comment]
Vraiment vraiment. Peut être que j'ai pas fait attention, mais je suis certain d'être tombé dans un cas ou c'était ok.

**Comment by artragis** [comment]
ce qui me soule c'est que c'est totalement impossible au vue de ce qu'on fait qu'il ne soit pas "suivi".

En fait il est "partiellement suivi". Si un autre utilisateur poste sur le topic, vous aurez bien une notif. Par contre dans le menu latéral, on l'a pas et ça je comprends pas pourquoi car là ça dépend pas de nous ce bout de code.

**Comment by GerardPaligot** [comment]
J'ai regardé un peu le code :
1. Je ne comprends pas bien cette [condition](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_contents.py#L1330).
2. La classe `ManageBetaContent` est grosse, elle aurait au moins mérité d'être découpé en méthode.
3. Du coup, tu es passé à côté d'une répétition de code [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_contents.py#L1359-L1362) et [là](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_contents.py#L1414-L1417). Ce qui pourrait expliqué le succès de la QA par @pierre-24.

Pas bien d'accuser les autres modules ! :)

**Comment by Situphen** [comment]
[Voilà la gestion au niveau du _template_](https://github.com/zestedesavoir/zds-site/blob/dev/templates/forum/topic/index.html#L186). Vu le code de `Topic.is_followed()`, ça m'a l'air correct !

**Comment by artragis** [comment]
la duplication de code est sûrement en cause. Faudra voir à détacher 
tout ça.

**Comment by SpaceFox** [comment]
Corrigé par #3111
