### ISSUE TITLE
Cannot visualize offline article

### ISSUE THREAD

**Issue by Ge0** [zestedesavoir/zds-site#303]
J'ai enlevé la publication d'un article de test que j'avais rédigé.

Quelqu'un avec les droits suffisants peut-il accéder à http://preprod.zestedesavoir.com/articles/off/17/mon-article et me dire ce qu'il voit ?

**Comment by cgabard** [comment]
Moi j'ai une erreur django. Je ne sais pas si j'ai les droits pour mais dans tous les cas il devrait y avoir au moins une erreur dédié

**Comment by Ge0** [comment]
Je pense donc que tu as les droits... Tu étais connecté ?

**Comment by cgabard** [comment]
oui

Christophe.

**Comment by firm1** [comment]
J'ai détecté cette erreur, je l'ai corrigé ce matin en local avant de
sortir de la maison, je pousse la correction quand je rentre.
Le 14 avr. 2014 13:28, "Christophe Gabard" notifications@github.com a
écrit :

> oui
> 
> Christophe.
>

**Comment by firm1** [comment]
Ah mais non, je viens de regarder l'erreur de plus près et en fait l'erreur vient de moi. Une précédente PR pour laquelle javais oublié de nettoyer la preprod. Je t'ai viré ton article pour le coup manuellement. Du coup le bug ne devrait plus exister.

N'hésite pas à ré-ouvrir si tu rencontres le même problème ailleurs.
