### ISSUE TITLE
[beta 15.9] Accès aux contenus non publiés des contenus

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3030]
Scénario :
- Demandez à un membre de vous mettre les droits d'écriture sur une galerie d'un contenu **publié**.
- Cliquez sur "Aller à l'article lié à cette galerie"
- Constatez que vous pouvez visualiser le contenu dans sa version non publiée alors que vous n'êtes pas auteur.

**Remarque :** Vous avez accès à la version non publiée du contenu mais uniquement avec le contenu publié. Si la version brouillon et publiée diverges dans leur contenu, vous ne pouvez accéder au contenu que par le code sha de la version publiée.

**Comment by pierre-24** [comment]
Bug, clairement, mais mineur, donc :)

**Comment by GerardPaligot** [comment]
Complément d'information : Pour reproduire le bug, pas besoin de passer par la galerie. Il suffit d'accéder à n'importe quel contenu directement dans sa version non publiée, ça passera.

**Comment by pierre-24** [comment]
Donc il y a clairement une condition un peu trop laxiste au niveau [du mixin](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/mixins.py#L16).

**Comment by pierre-24** [comment]
Plus précisément, [c'est là que ça coince](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/mixins.py#L115)

**Comment by Situphen** [comment]
Merci à @artragis ! :)
