### ISSUE TITLE
[beta 15.9] Erreur 500 lors de la création d'un article

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3031]
Scenario :
- Je vais sur la page de creation d'un article
- Je saisi dans la case titre "££"
- Je selectionne la categorie Android
- Dans le message de suivi je note "£"
- Pouf **erreur 500**

On ne devrait jamais avoir d'erreur 500 dans la vie.

**Comment by pierre-24** [comment]
Oooooh non, pas unicode, pas encore, pitiééééé :'(

**Comment by GerardPaligot** [comment]
A noter que le message de suivi n'a aucun impact sur le bug. C'est le titre "££" qui cause l'erreur 500.

**Comment by artragis** [comment]
étrange. c'est comme si le forum n'avait pas fait son taf

**Comment by pierre-24** [comment]
> étrange. c'est comme si le forum n'avait pas fait son taf

Le forum ?

**Comment by artragis** [comment]
le form... comme formulaire. je sais même pas si c'est l'autocorrect qui 
a fait ça... désolé.

**Comment by pierre-24** [comment]
Je viens de tester en local avec `€€`. Ce qui est bizarre, c'est que l'article est bien créé, mais l'erreur arrive après (c'est "slug invalide").

**Comment by artragis** [comment]
peut être un conflit d'algo de slug quelque part
c'est pas impossible que € soit transformé en e et £ en l dans un algo 
et pas dans l'autre.

**Comment by pierre-24** [comment]
Pas con du tout, ça.

**Comment by pierre-24** [comment]
... Bordel, t'avais raison. Je vais systématiquement mettre `from uuslug import slugify` dans notre module, comme ça on sera tranquille.

**Comment by pierre-24** [comment]
Donc, ça, c'est bon.
