### ISSUE TITLE
Mauvaise URL dans le partage d'un contenu

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3034]
Scénario :
- Rendez-vous sur un contenu publié.
- Tentez de partager par Twitter par exemple.
- Constatez que l'URL utilisée est celle de la preprod et non pas de la beta. La preprod pointe toujours vers la beta mais c'est pas top.

Priorité minimale et je suis pas certain que c'est spécifique à la release actuellement déployée.

**Comment by Situphen** [comment]
A mon avis, ~~si je me souviens bien du code que j'ai écris~~ [j'ai vérifié, c'est ça], c'est un problème venant des URLs configurées dans `settings_prod.py` ! :)

**Comment by artragis** [comment]
peut-on fermer?

**Comment by GerardPaligot** [comment]
Si l'URL est bonne oui, sinon non. Mais j'enlève le tag beta 15.9. C'est pas lié.

**Comment by Eskimon** [comment]
C'est corrigé, un artefact des vieux jours dans le settings_prod.py sur le serveur de beta. Tout est ok maintenant.

La prod' n'était pas touché par ca car n'a pas besoin d'override ce paramètre.
