### ISSUE TITLE
[beta 15.9] On a acces a l'url d'édition d'un commentaire qui n'est pas le notre

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3035]
Meme si vous n'êtes pas Andr0, si vous allez sur ce lien (en etant connecté) https://beta.zestedesavoir.com/contenus/reactions/editer/?message=76870&pk=837

Vous verez que l'interface vous dit que vous editez ce message en tant que modérateur (alors que je suis connecté avec un compte non staff)

Un bug donc

**Comment by GerardPaligot** [comment]
Je confirme la régression par rapport à la prod (qui renvoie une 404 au lieu d'une 403 mais c'est plus trop un problème :)).

**Comment by Situphen** [comment]
Je confirme aussi !

**Comment by pierre-24** [comment]
J'ai proposé une correction :)

**Comment by pierre-24** [comment]
OK ici !
