### ISSUE TITLE
[beta 15.9] Il est possible de mettre à un tutoriel un titre plus long que la limite imposée et des 404 s'en suivent

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3040]
La limite imposée au titre d'un tutoriel est censé être de [80 caractères](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/models/models_database.py#L54). Mais il est assez simple de surpasser cette limite. Comment faire ?
- Télécharger l'archive zip
- Modifier le fichier manifest.json dans lequel on met un titre de plus de 80 caractères.
- Importer une nouvelle version du tutoriel
- On se retrouve avec un tutoriel dont le titre est aussi long qu'un bras

L'autre effet pervers c'est que le tutoriel est devenu inutilisable, on a des 404 de partout à l'intérieur.

**Comment by pierre-24** [comment]
Haw. Ennuyeux :/

**Comment by pierre-24** [comment]
Presque réglé.

Je me suis souvenu un peu trop tard que la limite ne s'appliquait pas sur les titres d'articles à la base. Sauf qu'il y a le découpage à la migration, ben par exemple l'interview d'@artragis ne passera plus :/

**Comment by artragis** [comment]
le découpage ne parle que des titres de sections et ça c'est pas limité 
mon cher.

**Comment by pierre-24** [comment]
[c'est pas ce que dit ton T.U.](https://github.com/zestedesavoir/zds-site/pull/3046/files#diff-a90794a50efe5a1136e025c8c311adcbR628) !?!

**Comment by artragis** [comment]
mon TU sert juste à montrer que si on n'envoie pas un string ça envoie 
un BadManifestError (si si, c'est bien un BadManifestError, pas un 
InvalidSlug)

**Comment by artragis** [comment]
Du coup tu peux fermer @pierre-24

**Comment by pierre-24** [comment]
Je viens de tester, et en effet :)
