### ISSUE TITLE
Les slugs devrait être générés d'eux même à l'import d'une archive

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#3041]
Comme nous l'as fait remarqué, _très gentiment_ thizanne alias Zéphyr, ça ne sert à rien de choisir les slugs soit même. Pourquoi donc ne pas les faire choisir au moment de l'import ?

(voilà qui devrait faire plaisir à @firm1 )

**Comment by Eskimon** [comment]
Ah j'me disais bien que les remarques et le style de Zéphyr ressemblait vachement à celle de thizanne...

**Comment by pierre-24** [comment]
T'as même pas idée :'(

**Comment by SpaceFox** [comment]
Il me semblait qu'on avait déjà eu cette discussion et qu'il en était sorti qu'on devait pouvoir choisir ses slugs ?

**Comment by pierre-24** [comment]
Toutafé.

Bon, je te passe les détails, mais il semblerai que ...

> (09:29:30 PM) thizanne: c'est vraiment la zdsite aigüe ce patch

que

> (09:29:48 PM) thizanne: 2 ans de discussions, 6 mois d'implémentation pour arriver à un résultat qui est le contraire de ce qu'il fallait

que

> (09:31:44 PM) thizanne: je veux porter plainte pour publicité mensongère, c'est presque pire que le précédent

que

> (09:55:54 PM) thizanne: votre interface n'est pas conçue pour rendre service aux auteurs, elle est conçue pour développer ensemble

et que

> (09:59:00 PM) thizanne: dommage que pdp soit mort
> (09:59:07 PM) thizanne: au moins dessus y'avait cette fonctionnalité
> (09:59:26 PM) thizanne: vous devriez envisager d'en reprendre le code pour zds, à elle seule elle vaut tous les ajouts que vous avez fait imho

Bref.

C'est tagué "évolution" et non pas "bug", donc ça sort du _scope_ de bugfix actuel.

**Comment by SpaceFox** [comment]
Je rappelle à tout hasard que ce n'est pas parce que quelqu'un crie fort qu'il a raison.

Ses revendications, comme toutes les autres, sont à étudier la tête froide et à trier. D'autant plus que ce genre de fonctionnalité n'était pas le cœur de la ZEP-12, ce me semble.

**Comment by SpaceFox** [comment]
D'autre part, depuis quelques semaines après le fork, la licence de PdP est
passée à  AGPL ( de mémoire), ce qui nous interdit de reprendre leur code.
Le 30 sept. 2015 07:27, "Pierre Beaujean" notifications@github.com a
écrit :

**Comment by artragis** [comment]
Mais on est totalement d'accord cher @SpaceFox . On lui a expliqué que c'était pas le but, mais il a entendu le mot magique "import" et s'est dit que _sa fonctionnalité_ avait été introduite.

Notons que cette fonctionnalité, bien que pratique, va au contraire de ce que fait zds jusqu'à présent : un seul fichier md qui contient tout. Perso, je me vois mal écrire un tutoriel complet (moyen ou big) dans un seul fichier.

Mais bon, comme c'est pratique... on le fera plus tard. Mais thizanne a confondu ses désirs et la réalité.

**Comment by Eskimon** [comment]
_/ignore_

Date: Tue, 29 Sep 2015 22:27:01 -0700

**Comment by SpaceFox** [comment]
Bah il a quitté le site…
