### ISSUE TITLE
[beta 15.9] Erreur 500 lors de l'import d'une archive modifiée

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3042]
Scénario: 
- Je télécharge l'archive d'un tutoriel
- Au niveau du titre du tutoriel, je le remplace par `["titre1", ""]` 
- Je réimporte.
- Pouf **erreur 500**

On ne devrait jamais avoir d'erreur 500 dans une vie

**Comment by pierre-24** [comment]
Argh. C'est tordu, ça. Est ce qu'on peut vraiment se prémunir de toutes les horreurs que l'auteur pourrait faire subir au JSON ?

Bon, après, il suffit de faire des _check_ de type, ça à l'avantage de cadenasser notre spécification  :p

**Comment by GerardPaligot** [comment]
> se prémunir de toutes les horreurs que l'auteur pourrait faire subir au JSON ?

En tout cas, se prémunir des erreurs 500.

**Comment by SpaceFox** [comment]
Y'a des outils de validation de JSON - genre, comme les DTD en XML ?

**Comment by pierre-24** [comment]
Bah, dans notre cas, c'est pas hyper complexe à mettre en place. Juste qu'il faut décidément qu'on fasse attention à la fonction d'import, il y a moyen de faire rentrer les pires horreurs :p

**Comment by artragis** [comment]
il existe les schéma json, mais je ne sais pas s'il existe une lib qui le fait en python.

**Comment by GerardPaligot** [comment]
[Premier résultat](https://pypi.python.org/pypi/jsonschema). Ca me semble une bonne idée de l'intégrer dans ZdS.

**Comment by artragis** [comment]
Ok, évolution aussi car c'est quand même du boulot pour peu finalement.
Je suis en train d'écrire un fix pour ce bug et #3040 car finalement c'est un bug qui a la même cause.

**Comment by pierre-24** [comment]
Pourquoi pas. Par contre, je connais pas les performances du bouzin, mais je propose à priori que de l'intégrer au moment d'importer une archive : à priori, le manifest interne est cohérent avec ce qu'on attend de lui?

**Comment by artragis** [comment]
je dis pas le contraire, mais c'est long d'écrire un schéma json (et rébarbatif en plus). D'autant plus qu'on a pas mal de disjonction et une structure récursive.

**Comment by firm1** [comment]
En tout cas si on pouvait plus generalement appliquer directement les regles de validation du formulaire en ligne sur l'import via json, on eviterai pas mal d'incohérence entre les deux entrées et on minimiserait le risque d'erreur 500

**Comment by artragis** [comment]
Je suis tout à fait d'accord @firm1

**Comment by pierre-24** [comment]
Ok :)
