### ISSUE TITLE
[beta 15.9] La documentation de la ZEP-12 n'est pas toujours vraie

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3043]
Dans la doc de la ZEP 12, plus précisément dans le paragraphe relatif au [fichier manifest](http://zds-site.readthedocs.org/fr/latest/back-end/contents_manifest.html#version-2-0) , Le texte dit : 

> 1. `children` : tableau contenant l’architecture du contenu. **Obligatoire**

Dans la réalité cet attribut n'est pas obligatoire, puisque le système accepte un json sans cet attribut.

La question existentielle : est-ce la doc qui est fausse ou est-ce le système qui beug ? Telle est la question.

**Comment by pierre-24** [comment]
Mmmh ... Je dirais la doc qui est fausse. Je pense qu'à ce moment là, on avait simplement pas envisagé un contenu vide, ce qui a, il faut le reconnaître, assez peu d'intérêt ^^

**Comment by firm1** [comment]
On dirait que la doc est aussi fausse sur le morceau qui dit :

> 1. `type` : Le type de contenu, vaut “TUTORIAL” ou “ARTICLE”. Obligatoire

Lorsque je met une autre valeur à type qui n'est ni `tutorial` ni `article`, le système a l'air d'accepter tout de même. Il faudrait le préciser aussi dans la doc

**Comment by pierre-24** [comment]
ça par contre, je me souviens d'un `then, assume tutorial`, mais ça a du se perdre :p

**Comment by Situphen** [comment]
Je viens de tester et effectivement si on met rien, il met Tutoriel par défaut. Par contre, j'ai beau fouiller dans le code, je n'ai pas trouvé de `then, assume tutorial` ! Peut-être que c'est Django qui le fait via `save()` vu que [le champ en base de donnée](https://github.com/zestedesavoir/zds-site/blob/6ed07f0d83233df16cd40934eca1c4bb30f8df7d/zds/tutorialv2/models/models_database.py#L97) n'a que deux valeurs possibles (`TYPE_CHOICES`) ?

**Comment by pierre-24** [comment]
Non, en fait, [il est caché là](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/utils.py#L734), ou il est initialisé par défaut à `"TUTORIAL"`, et [changé uniquement si le champ `type` est défini dans le manifest](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/utils.py#L742).

**Comment by Situphen** [comment]
Voilà, j'ai fait une PR ! Il n'y a pas d'autres coquilles à corriger ?

**Comment by pierre-24** [comment]
Il semblerait que non :)
