### ISSUE TITLE
[beta 15.9] erreur 500 : la zep12 n'aime pas l'espace

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3044]
Scénario : 
- Je télécharge l'archive de mon tutoriel
- Je modifie le chemin de mon introduction en remplaçant dans le json `"introduction.md"` par `"intro duction.md"` (notez l'espace que j'ai rajouté)
- Je renomme aussi le fichier physique
- je zippe le tout et je réimporte
- BIM : **error 500**

Les erreurs 500 ne devraient pas faire partie de la vie.

**Comment by pierre-24** [comment]
Étonnant, je viens de le faire. On est d'accord que la valeur du champ `introduction` correspondait bien un chemin existant, nan ?

**Comment by firm1** [comment]
oui le chemin existait bien.

**Comment by artragis** [comment]
Bug non reproductible. Peux-tu envoyer l'archive que tu as tenter de soumettre à mon pseudo arrobase gmail.com

**Comment by GerardPaligot** [comment]
Je confirme. J'ai suivi le scénario et je n'ai pas obtenu une erreur 500.

**Comment by artragis** [comment]
quelqu'un pour fermer donc?

**Comment by GerardPaligot** [comment]
Peut-être laisser la possibilité à @firm1 de donner des informations complémentaires.

**Comment by firm1** [comment]
z'avez tenté de reproduire sur la beta ? si oui, peut être que j'ai testé autre chose en même temps qui provoquait la 500.

je refais un essai au cas ou dans la journée et je vous fait un retour

**Comment by GerardPaligot** [comment]
Je fais tous mes tests uniquement sur la bêta.

**Comment by firm1** [comment]
Je confirme que ça marche bien sur la beta avec les espaces. Je pense que j'ai du tester un autre cas verollé en parallèle.

Je ferme donc cette issue.
