### ISSUE TITLE
[beta 15.9] 404 sur l'historique des versions

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3045]
> **Note :** Je ne sais pas exactement l'élément déclencheur de ce bug alors je vous donne toutes mes manipulations.

Scénario :
- Créez un article vide et demandez sa validation.
- Validez le.
- Modifier son titre.
- Tentez de vous rendre dans l'historique des versions à partir de la version non publié.
- Constatez l'erreur 404.

URL incriminé : https://beta.zestedesavoir.com/contenus/838/merci-de-le-valider/?version=3eeba47707798e8add5d5bf4e65531ebeffebbc0

**Comment by pierre-24** [comment]
je confirme:/

**Comment by GerardPaligot** [comment]
Complément d'information :

Il y a un truc très chelou ! 
1. Mon article est publié, il y a donc une version du tutoriel "figé" (https://beta.zestedesavoir.com/articles/838/merci-de-le-valider/)
2. La version publiée me propose d'aller sur la version hors ligne (https://beta.zestedesavoir.com/contenus/838/merci-de-le-valider/?version=3eeba47707798e8add5d5bf4e65531ebeffebbc0)
3. Et cette même version me propose d'aller sur le brouillon (https://beta.zestedesavoir.com/contenus/838/merci-de-lavoir-valide/)

Whaaaaaaaat ?!

Donc je peux accéder à l'historique à partir de la version du point 3 mais pas du point 2.

**Comment by pierre-24** [comment]
Clairement un problème de slug. Solution à mon avis la plus courte, employer le slug utilisé pour "aller à la version brouillon".
