### ISSUE TITLE
[beta 15.9] L'import d'un contenu ne supporte l'ANSI

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3047]
Lorsqu'on essaye d'importer une archive qui contient des fichier encodé en ANSI, le menu import nous rejète et demande de l'UTF-8

Mon pauvre bloc note sous windows lui m'enregistre pourtant mes documents au format ANSI.

Pour plus d'accessibilité il faudrait supporter l'ANSI.

**Comment by SpaceFox** [comment]
Non. On ne va pas s'amuser à supporter différents formats d'encodage.

Et personne n'édite sérieusement avec le bloc-notes de Windows, qui par ailleurs est parfaitement capable d'enregistrer en UTF-8 (ainsi que en « unicode » et « unicode big endian », quoique cela puisse dire).

**Comment by pierre-24** [comment]
Puis en plus, le problème est intrinsèque à python 2 : ça a déjà été l'horreur de lui faire bouffer de l'unicode de bout en bout, python 2 est trop rigide pour qu'on fasse grand chose d'autre.

**Comment by SpaceFox** [comment]
Quel que soit le langage en fait, gérer proprement du multi-encodage est
une horreur sans nom et peut exploser les données à la moindre erreur.
Le 30 sept. 2015 19:10, "Pierre Beaujean" notifications@github.com a
écrit :
