### ISSUE TITLE
Recherche avec aucun résultat sur les premières pages mais seulement sur les suivantes

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#3050]
J'ai fait [une recherche avec "est"](https://zestedesavoir.com/rechercher/?q=est) sur la production et je me suis retrouvé avec aucun résultat sur les pages 1 à 4 mais de 5 à 3193 il y en a.

Ping @DevHugo

**Comment by SpaceFox** [comment]
Tu es tombé sur un cas très particulier : les pages 1 à 4, c'est des résultats staff que tu ne peux pas voir donc on les masque (pour des raisons techniques, on ne peut pas aujourd'hui demander à solr de les filtrer).

Comme ton critère de recherche est très très très vague, au lieu d'avoir quelques résultats en moins dans la page, il te manque des pages entières…

**Comment by Situphen** [comment]
C'est ce dont je me doutais. Y a-t-il un moyen de ces résultats soient cachés avant la génération de la pagination ?

Après, comme tu l'as dit c'est un critère de recherche très vague, donc le bug n'est pas super gênant.

**Comment by SpaceFox** [comment]
Faut vérifier mais de mémoire, non.

**Comment by DevHugo** [comment]
Ça semblerais être liés au résultat du staff, mais j'arrive pas à reproduire en local. Je créé des sujets en zone staff et j'ai la bonne pagination.

J'ai pas vraiment d'idée comme ça, je sais pas si ça fait longtemps qu'on a le souci ou pas. Sinon on revient à l'ancienne méthode qui était de trié dans le template.

**Comment by DevHugo** [comment]
C'est surement dans ces lignes [la](https://github.com/zestedesavoir/zds-site/blob/dev/zds/search/views.py#L37), peut-être que en passant à la nouvelle méthode (avec la version supérieure de Haystack), on va implanter du coup une autre méthode qui elle sera avant le calcul de la pagination.

Si on veut débugger, le souci doit-être en beta aussi donc suffit d'aller sur l'interface admin de Solr ou réinterroger l'api pour savoir quels sont ces résultats.

**Comment by WinXaito** [comment]
Petit up de ceci car le bug est toujours présent.

[Up de Olybri](https://zestedesavoir.com/forums/sujet/5008/certains-termes-de-recherche-donnent-25-pages-de-resultats-vides/?page=1#p92271)

**Comment by DevHugo** [comment]
Je regarde si avec la nouvelle version de Haystack on a le souci mais j'ai pas avancé depuis

**Comment by DevHugo** [comment]
On est bon quelqu'un peut fermer ? @Situphen
