### ISSUE TITLE
Incohérence dans les images gif de la galerie

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3056]
Serveur : Prod
Version :  v15.7-gaston/2da6a20
Système : OS X
Navigateur : Google Chrome Version 45.0.2454.101 (64-bit)

Scénario :
- Rendez-vous dans une galerie.
- Soumettez une image du type "GIF".
- Constatez que l'image en prévisualisation est un GIF mais que les URLs markdown sont des JPG.
- Constatez aussi que l'image GIF est tout à fait utilisable.

**Comment by Eskimon** [comment]
Je prend j'ai trouvé !

**Comment by GerardPaligot** [comment]
Merci à @Eskimon !
