### ISSUE TITLE
"Contacter tous les auteurs" lors de la béta ou de la version publique

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#3057]
Depuis le forum zds : 

> Bonjour bonjour !
> 
> Je me disais qu'il pourrait être pratique d'avoir un bouton, qu'on soit auteur ou lecteur, pour envoyer un MP à tous les auteurs d'un contenu (tutoriel ou article) particulier. Un tel bouton apparaîtrait en haut du tutoriel, au niveau de la liste des auteurs, ou alors à gauche, dans le menu.
> 
> Merci.

Petit avis technique : 

> La fonctionnalité existe quand on a les demandes d'aide alors pourquoi pas la dupliquer sur l'interface de rédaction du tuto.

**Comment by GerardPaligot** [comment]
Je taggue facile parce que pour un contributeur régulier, ça ne posera pas problème mais pour un débutant total, il y a quand même un petit défi. A prendre en compte !

**Comment by Eskimon** [comment]
PS : La "bonne" place sera dans la sidebar

**Comment by Vayel** [comment]
Jeter un coup d'oeil ici : https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_contents.py#L1443

**Comment by Anto59290** [comment]
Je veux bien m'en occuper
