### ISSUE TITLE
Quelle est la licence du logo ?

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#306]
Tout est dans le titre :)

**Comment by Alex-D** [comment]
Faut demander à MaxRoyo qui n'est pas ici. Et au frère d'Andr0 qui l'a retouché (sauf s'il s'en fou).

Il faudrait néanmoins qu'il soit protégé pour une identité unique assurée (principe même d'un logo).

**Comment by firm1** [comment]
Selon les retours de MaxRoyo, le logo est sous licence CC-BY.

**Comment by ChantyTaguan** [comment]
MaxRoyo vient de me recontacter. Il demande qu'on modifie la licence pour CC-BY-NC-SA. Apparemment, il nous a répondu un peu vite la fois passée.

**Comment by SpaceFox** [comment]
Je corrige ça.

**Comment by SpaceFox** [comment]
Corrigé directement sur la branche de la bêta.
