### ISSUE TITLE
[beta 15.9] Clem qui migre les tutoriels est inconnue au bataillon

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3062]
Dans l'historique d'un tutoriel qui a été migré, on se rend compte qu'il y'a deux commit qui sont effectués. Le premier commit est celui de zds qui fait un "Nettoyage pré-migratoire ", puis un commit de Clem qui fait la "Migration version 2".

Le problème c'est que 
- dans cet historique "zds" n'est pas un utilisateur connu sur le site (il serait préférable que ce soit Clem qui fasse les deux commits)
- Le lien Clem ne pointe pas vers son profil utilisateur zds, mais vers une adresse mail, alors que Clem est un membre de ZdS. Ce qui laisse à pensé que le commit n'a pas été fait avec l'id de Clem, mais avec son pseudo.

Un léger petit bug donc.

**Comment by pierre-24** [comment]
Mouairf. [on commite un peu bourin](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/management/commands/migrate_to_zep12.py#L221), en fait, dans le cas de la migration, [c'est par pure chance que ça tombe sur Clem](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/utils.py#L966) (tout ça parce qu'on a décidé de mettre l'_username_ à la place du _pk_ >.> )

**Comment by Eskimon** [comment]
Ok !
