### ISSUE TITLE
[beta 15.9] petite coquille dans le code

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3063]
En zieutant un peut le code, sur [cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/models/models_database.py#L352),on peut lire ceci : 

``` python
attrs = [
            'pk', 'authors', 'authors', 'subcategory', 'image', 'creation_date', 'pubdate', 'update_date', 'source',
            'sha_draft', 'sha_beta', 'sha_validation', 'sha_public'
        ]
```

Les plus vigilents auront remarqués qu'il y'a deux fois le "authors" dans la liste. Je suppose que c'est un effet de la fatigue ?

**Comment by artragis** [comment]
pour ce genre de code, tu as le droit de faire une PR plutôt que d'ouvrir une issue.

**Comment by Eskimon** [comment]
@artragis restons sympa, tout le monde n'a pas accès à une machine pour faire des PR, donc il est toujours bon d'avoir un retour _même pour des trucs trivials_ plutôt que de passer à côté de quelque chose.

**Comment by pierre-24** [comment]
Non, mais là, il peut passer direct par GH. Soit, la PR est là, et objectivement, y'a rien à tester (sauf si vous voulez TOUT tester :p )

**Comment by Eskimon** [comment]
Pour passer par GH il faut un fork à jour sur GH...

**Comment by artragis** [comment]
pas si sûr. Le système te permet de bien faire les choses (il wrappe autour
de checkout -b .. upstream/release

mais bon pas grave pierre a déjà tout fait.

2015-10-13 11:31 GMT+02:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
J'ai pas compris :( Mais si tu sais comment garder un fork GH à jour ca m'intéresse vivement :)

**Comment by firm1** [comment]
> Pour passer par GH il faut un fork à jour sur GH...

C'est bien mon problème aussi et je n'ai pas bien compris la manip de @artragis mais si il sait comment faire ça m'interesse aussi.

**Comment by pquentin** [comment]
En fait on peut éditer directement chaque fichier sur GitHub. Je pense que c'est ce que proposait @artragis. Et ci-dessous, voilà comment reproduire ce que fait GitHub quand on édite un fichier sur un répo sur lequel on ne peut pas commiter.

L'idée est de créer une nouvelle branche locale avec un nom plus ou moins descriptif (patch-1 vs patch-attrs-typo). En supposant que la remote se nomme origin, on peut faire :

```
git fetch origin  # pour être sûr d'avoir les derniers commits
git checkout -b patch-1 origin/dev  # pour avoir les derniers commits dans la branch patch-1
```

Et là il est possible de travailler sur patch-1, de pusher sur son fork, et de créer une pull request depuis l'interface GitHub.

**Comment by firm1** [comment]
Peut-être je n'ai pas précisé mes contraintes, mais je pense qu' @artragis les connais.
1. j'ai les droits pour commiter sur le depot officiel (mais ce n'est pas ce qu'il faut faire) et du coup la méthode de @pquentin ne marche pas
2. j'ai un fork qui n'est pas du tout syncro avec l'upstream et que je ne veux pas écraser car il y'a des branches dessus qui m'interesse.

Comment je fais depuis github pour faire les modifs ? J'ai déjà cherché, mais ça n'a pas l'air d'être possible. 

Conclusion : j'ai crée l'issue pour que ça ne soit pas perdu :)

**Comment by artragis** [comment]
> j'ai un fork qui n'est pas du tout syncro avec l'upstream et que je ne
> veux pas écraser car il y'a des branches dessus qui m'interesse.

C'est ça que jen e comprends pas. Mon fork n'est pas non plus syncro avec
upstream : ma branche dev est totalement hors de date.

Maintenant la contrainte "1" est la clef du problème : comme tu as les
droits de commits, ils ne te propose pas automatiquement de passer sur ton
fork. Il faut donc qu'à un moment ou à un autre, tu fasses un

git fetch upstream
git checkout -b unebranche upstream/dev
git push origin unebranche

Cela ne détruira pas ton fork.

**Comment by firm1** [comment]
Et comment on fait pour taper ces commandes git depuis github ?

**Comment by artragis** [comment]
pas possible.

C'est là qu'est le problème en fait : comme tu as les droits de commit, y'a
pas automatiquement de création d'une nouvelle branche chez toi (quoi que
c'est peut être possible d'une manière ou d'une autre)

**Comment by firm1** [comment]
Donc on revient au problème de départ ... pour ce genre de situation la
meilleure chose que je peux faire c'est une issue.

**Comment by Eskimon** [comment]
hop cadeau pour @Emeric54 qui nous rejoins :)

**Comment by pierre-24** [comment]
... S'aurait été avec plaisir, mais je l'ai déjà réglé :p

**Comment by GerardPaligot** [comment]
Oh l'autre ! Il fait le travail des nouveaux contributeurs ! :o

**Comment by Eskimon** [comment]
Ok
