### ISSUE TITLE
Enlever les TODO dans le code

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3064]
Les [TODOs](https://github.com/zestedesavoir/zds-site/search?l=python&o=desc&q=TODO&s=indexed&utf8=%E2%9C%93) dans le code c'est le meilleur moyens de les oublier.

Il faudrait idéalement les retirer en procédant de l'une des deux manières suivantes : 
- soit corriger le bug/evolution
- soit créer les issues correspondantes

**Comment by pierre-24** [comment]
Pourquoi c'est tagué "beta 15.9", alors que c'est loin d'être récent pour certrains TODO ?

**Comment by SpaceFox** [comment]
C'est pas de la bêta, c'est de la vie de code normale.
