### ISSUE TITLE
[beta 15.9] Présence des fonctions inutilisées dans le code

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3065]
La fonction `def change_type` a été insérée dans le code de la ZEP12, mais n'[est pas utilisée](https://github.com/zestedesavoir/zds-site/search?utf8=%E2%9C%93&q=change_type). On ne sait pas non plus comment elles vont être utilisées plus tard (d'autant plus que je ne pense pas qu'elle puisse être utilisée en l'état).

Il faudrait éviter de surcharger le code avec des fonctions qu'on utilise pas.

**Comment by Eskimon** [comment]
Ok
