### ISSUE TITLE
[beta 15.9] problème de vocabulaire entre le code et l'IHM

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3066]
Il y'a un décalage de vocabulaire entre le code et l'interface homme machine.

En regardant le code introduit par la zep12, on remarque que certaines fonction, classes, ... utilisent encore le terme `Extract` et pourtant au sein de l'IHM on n'utilise plus que le terme `Section`.

Il faudrait donc remplacer les notions dans le code pour un dev qui débarque dans le code connaissant le site, il risque d'être un peu perdu car il doit mapper dans sa tête.

Il faut corriger les éléments de docs qui vont avec.

**Comment by firm1** [comment]
Pour le problème de vocabulaire, je remarque aussi que dans [ce fichier](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_published.py) on retrouve la terminologie `Reaction` et `Note` pour ce qui concerne les commentaires d'un tutoriel/article.

Avant la terminologie Note correspondait aux Tutos et la terminalogie Reaction correspondait aux Articles. Maintenant que les deux terminologies ont fusionnées, il faut harmoniser en utilisant qu'un seul terme. Reaction ou Note ? Il faut choisir

**Comment by pierre-24** [comment]
Si on veux jouer à ça, le terme `Container` ne veut rien dire (il n'est employé nul part dans l'interface) et il y a une faute à `licence` (en anglais "correct", on dit ["license"](https://en.wikipedia.org/wiki/License), d'ailleurs [l'objet du même nom porte la même faute](https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/models.py#L151)). Et puis `Content` ne réfère à rien, puisqu'on a maintenu la séparation (artificielle) entre article et tuto.

Mais c'est pas tout. `FeaturedRessources` ([ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/featured/models.py#L9)) estr très pauvrement traduit par "une", _because_. On a aussi les classes `UserGallery` ([ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/gallery/models.py#L42)) auquel l'interface ne fait jamais référence et donc le nom devrait probablement être `GalleryOwner` ou à la limite `GalleryAccessRight`, la classe `Comment`, qu'on aurait du s'appeler `Post` et définir `ForumPost` et `ContentPost`, `ReadPost` et consoeur. Les MPs, qui en anglais doivent se traduire `pm`, alors que le module ne porte pas ce nom là. Tant que je suis dans ce coin là, on traduit `PrivateTopic` par "message privé", alors que non, bien entendu, c'est "private message", et petit bonus avec la fonction `never_privateread()` ([ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/mp/models.py#L239)) qui ne veut strictement rien dire (on croirait entendre parler du mode privé d'un navigateur, ici). On pourrait encore parler de `intervention` ([ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/templatetags/interventions.py)), jamais employé comme tels ...

Bref. Une fois encore, pourquoi nous et pourquoi maintenant ?

D'ailleurs, tu nous à reproché de ne pas être cohérent avec notre doc. [Eh bien si, cette fois-ci, on est en phase](http://zds-site.readthedocs.org/fr/latest/back-end/contents.html#des-extraits).

**Comment by Eskimon** [comment]
J'arrive après la bataille mais merci de rester sympa entre vous les gars, comme une belle équipe <3 . S'il y a besoin de faire échapper un peu de pression ou de crever des abcès (ce qui est très sain !) alors zou sur les MP (avec moi en copie si vous voulez un médiateur).

**Comment by pierre-24** [comment]
Y'a pas réellement de "problème", c'est juste que je regrette d'avoir ce genre de remarques après-coup, c'est (très)¹⁰⁰⁰ frustrant (et impossible à régler avec juste des _find_/_replace_)

**Comment by firm1** [comment]
Je n'avais pas remarqué que cette issue avait été fermée. Je ne l'avais pas tagguée en bug parce que c'était pas un bug donc pas prioritaire, mais ça me semble utile tout de même.

L'incohérence touche aussi le manifest, dans le sens ou quelqu'un d'habitué à l'IHM doit faire un petit mapping dans sa tete pour faire le lien entre les choses qu'il voir sur l'ihm et ce qu'il voit dans le manifest.

**Comment by pierre-24** [comment]
Il doit le faire aussi pour "container" qui n'est employé nulle part. L'argument est valide, mais une fois encore, est-ce vraiment là le problème ?

(rappellons [que certaines personnes n'aiment pas nos manifests](https://github.com/zestedesavoir/zds-site/issues/3041#issuecomment-144285386), de toute façon)
