### ISSUE TITLE
[beta 15.9] du code dupliqué dans le modèle

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3067]
En comparant [ce bout](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/models/models_database.py#L571) de code à [celui-ci](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/models/models_database.py#L685) on constate qu'il s'agit du même bout de code.

``` python
        reversed_ = ''

        if self.is_article():
            reversed_ = 'article'
        elif self.is_tutorial():
            reversed_ = 'tutorial'
```

Il aurait donc tout intéret à être rangé dans une fonction à appeler par les autres, ça simplifiera aussi les choses le jour ou on aura un autre type de contenu.

**Comment by Eskimon** [comment]
Ok
