### ISSUE TITLE
[beta 15.9] précision sur le mimetype markdown

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3068]
D'après le [morceau de code](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_published.py#L170) suivant : 

``` python
    mimetypes = {'html': 'text/html',
                 'md': 'text/plain',
                 'pdf': 'application/pdf',
                 'epub': 'application/epub+zip',
                 'zip': 'application/zip'}
```

On pourrait croire que le le mimetype markdown est `text/plain` et pourtant dans la réalité le mimetype mardkwon est `x-markdown`

**Comment by pierre-24** [comment]
C'est, au mieux, [une recommendation](https://datatracker.ietf.org/doc/draft-ietf-appsawg-text-markdown/). Le même argument tient pour les fonctions `moz-` et `webkit-` vs leurs équivalents dans la "vraie" norme dans le CSS.
