### ISSUE TITLE
[beta 15.9] harmonisation des typo des alertes

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3069]
Dans les messages d'alertes, on retrouve encore des phrases introduitent par la zep 12 qui ne respectent pas la norme des autres alertes du projet (les phrases doivent se terminer par un point par exemple).
- [exemple 1](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_published.py#L622)
- [exemple 2](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_contents.py#L348)
- [exemple 3](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_contents.py#L391)
- [exemple 4](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_contents.py#L681)

**Comment by firm1** [comment]
On notera aussi [cette phrase](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_contents.py#L355) qui n'est pas internationnalisée

**Comment by pierre-24** [comment]
Norme _de facto_, alors. Comme dit auparavant, on ne peut pas avoir connaissance de quelque chose qui n'est pas écrit.

**Comment by Eskimon** [comment]
Ok
