### ISSUE TITLE
Augmenter la longueur des titres

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#3072]
Dans le débat sur "quel titre choisir", il est ressorti que les titres sont trop courts. Il va donc falloir augmenter la longueur, mais jusqu'à quel point ?

**Comment by finkiki** [comment]
Tout est déjà trop gros sur ZdS ! Ce serait moi, je diviserais tout en 2, niveau taille et police.

**Comment by artragis** [comment]
??

**Comment by GerardPaligot** [comment]
@finkiki heureusement que ça ne dépend pas que de toi alors :)...

**Comment by firm1** [comment]
Moi je suis constamment en zoom 90% sur zds, mais j'avoue que j'ai de bons yeux

**Comment by Emeric54** [comment]
Vu le tag `Back`, je suppose que l'on parle de la taille en nombre de caractères ?

**Comment by artragis** [comment]
OUI

**Comment by Situphen** [comment]
J'ai modifié le texte et le titre pour qu'il n'y ait pas de confusion.

**Comment by Emeric54** [comment]
Oui, car apparemment il y a eu des confusions au-dessus.

A combien faudrait-il monter ?

On est 80 caractères actuellement. On peut peut-être monter à 100, ou 120.

**Comment by gasche** [comment]
Le fait que les tags et le titre soient dans le même champ est un gros problème actuellement, car la limite de longueur s'applique aux deux. J'ai voulu créer un topic aujourd'hui et j'ai du retirer un tag pour avoir la place de mettre mon titre.

À defaut d'augmenter la longueur maximale des titres (je ne vois pas de bonne raison de ne pas le faire; les gens savent qu'un titre court est en général préférable, même si la limite est plus haute il n'y aura pas beaucoup de titres trop long), il faudrait au moins séparer ça en deux champs différents de formulaire, car c'est agaçant de ne pas pouvoir mettre les tags qu'on veut.

**Comment by GerardPaligot** [comment]
En fait, j'ai développé ça et ça sera dans la v21 :

<img width="979" alt="capture d ecran 2016-11-12 a 21 11 10" src="https://cloud.githubusercontent.com/assets/1913901/20240594/a08be2ca-a91c-11e6-90f4-37af009ae032.png">

**Comment by Karnaj** [comment]
On peut fermer ce ticket ?

**Comment by pierre-24** [comment]
Anéfé :)
