### ISSUE TITLE
Le validateur perd le droit de validation lorsque la version change

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#3076]
Comme dit dans le titre,
- Un auteur passe son contenu en validation ;
- Un valido le réserve ;
- L'auteur met à jour la version en validation ;
- Le validateur recoit un MP pour le prévenir, mais doit re-réserver le contenu.

Il serait probablement plus pratique de garder le validateur et d'envoyer un MP pour le prévenir. Non ?

C'est tout con à faire :)

**Comment by artragis** [comment]
La zep-12 ne règle pas le pb?

**Comment by pierre-24** [comment]
Non, on est resté _iso_-prod sur le sujet, même si j'avais effectivement émis l'idée à un moment : 

![screenshot from 2015-10-13 11 44 52](https://cloud.githubusercontent.com/assets/7889675/10451351/e65979d0-719f-11e5-9c2d-5b4f2b26987f.png)

Mais comme je dit, il suffit de repasser l'objet `Validation` à `PENDING_V` au lieu de `PENDING` et le tour est joué :)

**Comment by Vayel** [comment]
Les validateurs se sont-ils plaints à propos de cela ? @SpaceFox @ArnaudCalmettes @firm1

**Comment by artragis** [comment]
Oui, je m'en suis plaint.

**Comment by GerardPaligot** [comment]
Je remonte cette issue. Cette évolution ne couterait pas grand-chose à développer, semble même plutôt trivial à développer et améliorait grandement un aspect de la validation.

En ce moment, j'ai un contenu en validation. C'est pénible de devoir prévenir mon validateur que j'ai mis à jour le contenu et qu'il doit à nouveau se le réserver (d'ailleurs, ça doit être pénible aussi pour lui).

**Comment by artragis** [comment]
Il est déjà prévenu automatiquement.

mais effectivement la correction est triviale Pierre l'a déjà donnée 
d'ailleurs.

**Comment by Vayel** [comment]
Du coup, je m'intéresse à [cette méthode](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_validations.py#L98) et j'aurais quelques questions : 
- La création d'un objet `Validation`, c'est bien pour déplacer la version du contenu dite en validation ? Ne peut-on pas plutôt mettre à jour l'objet `old_validation`, s'il existe ?
- A quoi sert https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_validations.py#L106 ?
- Et https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_validations.py#L107 ?
- Et https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_validations.py#L120 ? Je veux dire, pourquoi renseigner le validateur de la nouvelle version en validation si elle n'est pas réservée par défaut ?

Merci.

**Comment by artragis** [comment]
> a création d'un objet |Validation|, c'est bien pour déplacer la 
> version du contenu dite en validation ? Ne peut-on pas plutôt mettre à 
> jour l'objet |old_validation|, s'il existe ?

Non, c'est pour gareder l'historique qu'on fait un nouvel objet, mais le 
principal problème c'est que le statu actuellement est mis à PENDING au 
lieu de PENDING_V

> https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_validations.py#L106

à renseigner la date dans l'historique

> Et 
> https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_validations.py#L107 

à enregistrer les modifs en bdd

> Et 
> https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_validations.py#L120 
> ? Je veux dire, pourquoi renseigner le validateur de la nouvelle version 
> en validation si elle n'est pas réservée par défaut ?

En fait c'est un bug de la version 1 du module qu'on a copié comme ça on 
est compatible mais surtout parce que comme ça on copiait/collait le 
code :p C'est là qu'il faut mettre PENDING_V au lieu de PENDING

**Comment by Vayel** [comment]
D'accord, merci.

**Comment by Vayel** [comment]
Par contre, il va falloir que je modifie les tests aussi, non ? https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/tests/tests_views.py#L1992

**Comment by artragis** [comment]
oui, en effet :p

**Comment by Vayel** [comment]
Par contre, [cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/tests/tests_views.py#L1995) me paraît étrange étant donné qu'on a fait `validation.validator = old_validator` dans la vue.

**Comment by Vayel** [comment]
Etrangement, Travis ne bronche pas pour #3168.
