### ISSUE TITLE
Les auteurs de tutos ne sont pas historisés

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3078]
Les auteurs de tutos sont attaché au tuto dans son ensemble.

Donc, si un auteur A a écrit une version 1 d'un tuto (publiée), et qu'il ajoute un auteur B pour préparer une version 2, ce nouvel auteur est crédité sur la version 1 _y compris en sur la version publiée_.

Un auteur ne devrait être crédité que sur les versions à partir du moment où il a été ajouté au tuto.

Exemple avec [ce tuto](https://zestedesavoir.com/tutoriels/971/apprendre-un-jeu-de-strategie/) que j'ai écrit seul mais auquel j'ai ajouté Javier pour une v2. Javier se retrouve en co-auteur de la v1.

**Comment by artragis** [comment]
Bien reçu. Notons que grâce au modèle de la zep-12, le temps de correction de ce bug ne dépassera pas la demie heure et que le plus long risque d'être le temps d'écriture du TU.

**Comment by Eskimon** [comment]
Et ça c'est beau ! (petit larme)

**Comment by pierre-24** [comment]
Moi, j'ai quand même l'impression que c'est dans le _scope_ de la ZEP-08, non ? (parce que versionner les auteurs, c'est rajouter une ligne dans le manifest, toussa ... ?!?)

**Comment by Eskimon** [comment]
Nop, la zep-8 c'est plutôt "Comment githubiser nos repos" (accès externe, accès tiers etc...)

**Comment by GerardPaligot** [comment]
> Bien reçu. Notons que grâce au modèle de la zep-12, le temps de correction de ce bug ne dépassera pas la demie heure et que le plus long risque d'être le temps d'écriture du TU.

Versionner les auteurs ne prendrait que 30 minutes ? Ca semble quand même utopique (mais je peux me tromper).

**Comment by artragis** [comment]
Non pierre ! ne te firminise pas ! Il ne s'agit pas de "versionner" les
auteurs mais de "figer leur état" lors de la publication. Je rappelle que
nous avons un objet appelé "PublishedContent" qui "fige l'état des choses
lors de la publication", il suffit donc d'ajouter les auteurs à "l'état des
choses" et tout roulera.

2015-10-13 18:57 GMT+02:00 Eskimon notifications@github.com:

**Comment by pierre-24** [comment]
aaaah, j'avais pas compris ça comme ça :p

**Comment by GerardPaligot** [comment]
A mon avis, @SpaceFox ne parlait pas spécifiquement de la version publiée.

**Comment by SpaceFox** [comment]
Oui et non. Afficher les vrais auteurs du moment sur la version publiée est le minimum, avoir les vrais auteurs partout est un bonus appréciable.

**Comment by artragis** [comment]
pour revenir là dessus : 
- chaque commit (donc changement dans le code) est lié à son auteur dans l'historique des tutos
- pour que l'auteur apparaisse dans la liste des auteurs, il faut qu'il soit (encore) inscrit sur le site

En fait l'idée de ne "figer les auteurs que pour la version publique" permet de dire au publique "dans al version que vous regardez, il y a eu ces auteurs là". Ce qu'il se passe en coulisse, avec un nouveau coauteur par exemple, c'est totalement différent et seul les auteurs doivent avoir accès à cette info. Comme dit au dessus, cette info se trouvera dans la liste affichée sur la version brouillon (car cette version n'est pas liée à un publishedContent) et dans la liste des commits.

Donc d'un point de vue "UX" on a "l'impression" que les auteurs sont "historisés" mais leur évolution ne l'est que lorsque le contenu est publié. Je pense donc vraiment qu'on est dans le cadre d'un simple ajout dans la bdd.

Par contre, perso, je ne considère pas ça comme un bug mais comme une évolution, à voir donc.

**Comment by artragis** [comment]
J'aimerai savoir si la solution que je propose est validée histoire que je m'attèle au dev.

**Comment by pierre-24** [comment]
Moi ça me semble tenir la route :) (j'espère qu'on est pas en train de réintroduire des choses en BDD qu'on voulais éviter).

**Comment by gustavi** [comment]
Fixé dans #3199

**Comment by firm1** [comment]
Je réouvre cette issue. Car je suis tombé sur le tutoriel d'[introduction à ruby](https://zestedesavoir.com/tutoriels/634/une-introduction-a-ruby). Dans sa version publique on voit Dominus en tant qu'auteur, alors que le tutoriel n'a jamais été publié avec lui comme auteur.

La dernière date de publication date de Juin 2015 et Dominus n'a été rajouté à la rédaction de ce tutoriel que très récemment.

**Comment by artragis** [comment]
Tu es prié de fermer l'issue : dominus a été ajouté car il était auteur 
au moment où la maj a été faite.
Je ne peux pas deviner qui était auteur avant qu'on fasse la maj.

**Comment by pierre-24** [comment]
Je suis d'accord avec @artragis sur celle là.

**Comment by firm1** [comment]
Ah, effectivement. Je pensais qu'il y avait un historique des ajouts/sorties à la rédaction.

**Comment by artragis** [comment]
Non, c'est d'ailleurs en ça que ma PR génère une évolution en terme de 
fonctionnalité :p
