### ISSUE TITLE
Éliminer les TODO

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#308]
Traquer les TODO dans le code et dégager tous ceux qu'on peut.

**Comment by cgabard** [comment]
S'aider de [ce lien](https://github.com/Taluu/ZesteDeSavoir/search?q=TODO&ref=cmdform&type=Code)

**Comment by artragis** [comment]
J'ai voulu en corriger un ou deux, mais je n'ai pas le droit de "push" (peut être suis-je un peu trop noob avec git, pour l'instant j'ai créé une branche en local, j'ai fait mes commit et je voulais pusher sur origin nom_de_la_branche_identique_que_local pour ensuite faire une PR de cette branche là vers la master).

**Comment by firm1** [comment]
La commande suivante ne marche pas ?
`git push origin nom_de_la_branche_identique_que_local` 

Sinon, est-ce tu certain que ton dépot pointe sur ton fork ? car si tu l'as cloné avant l'ouverture du dépot, il doit encore pointer sur le fork

**Comment by artragis** [comment]
C'est le problème en effet, il pointait vers Taluu, j'ai tenté de le faire pointer sur celui-ci directement et c'était une mauvaise idée apparemement.

**Comment by ShigeruM** [comment]
As-tu déclarer le dépôt principal en tant que "upstream" de ton dépôt local ? Tu peux le faire avec :

`git remote add upstream https://github.com/zestedesavoir/zds-site.git`

Il faut le faire après avoir forké le dépôt principal puis cloné ton fork en local.

Ensuite, pour récupérer les dernières modifs d'upstream vers le local :

`git checkout dev` (tu te places sur la branche dans laquelle tu vas merger dans quelques instants)
`git branch` (pour vérifier que t'es sur la bonne branche !)
`git fetch upstream` (ça ça ramène les modifs sans toutefois modifier les fichiers locaux)
`git merge upstream/dev` (et là tu merges la branche dev de l'upstream dans la branche dev de ton dépôt local)

Et enfin pour faire tes modifs et en faire une PR :

`git checkout dev` (tu te mets sur la branche dev locale pour repartir de celle-ci, vu qu'on vient de la mettre à jour)
`git branch nom_nouvelle_branche` (création de la branche locale)
… tes modifs...
`git add mon_fichier`
`git commit` (ou `git commit -a` et pas besoin de l'étape d'avant)
`git push origin nom_nouvelle_branche` (là tu pousse la nouvelle branche vers ton fork)

Et la PR se fait directement depuis Github, sur la page de ton fork (en se mettant sur la branche que tu viens de pousser).

**Comment by ShigeruM** [comment]
Ah bah apparemment t'avais pas besoin de tout ça, tu as fait ta PR. Tant pis, si ça peut servir pour d'autres...

**Comment by artragis** [comment]
En fait il fallait quand même la partie avec le upstream.
J'avais aussi fait une erreur et avais changé l'url vers lequel pointait le dépôt et donc ça merdait.
Merci en tout cas.

**Comment by Alex-D** [comment]
Je viens de check, les TODO du front sont en fait des TODO qui attendent de nouvelles fonctionnalités du back globalement.
- diff sur les articles, que j'ai rapporté dans #1443
- métadonnées sur l'utilisateur (sanctions, IP), dans #1444

Il reste donc : design de l'export des tutoriels en HTML ; et ça c'est vraiment du front, faut faire joujou avec le CSS.

**Comment by firm1** [comment]
Je serais plutot d'avis de transformer tout les TODO dans le code par des issues (pour le suivi de ce qu'il faut faire) ou des PR (pour les corriger).

Y'a un paquet d'issues cachés là dedans.

**Comment by SpaceFox** [comment]
C'est un exemple de résolution de cette issue :)

**Comment by gustavi** [comment]
Pour j'ai ouvert plein d'issues mais il en reste (pas le courage pour ce soir).

Si certains ont du courage, voici ce qui me reste à regarder sur un grep : 

```
zds/forum/feeds.py:        # TODO: Use cached Markdown when implemented
zds/forum/views.py:        # Staff actions using AJAX TODO: Do not redirect on AJAX requests
zds/forum/models.py:        # TODO These prints is used to debug this method. Remove them later.
zds/article/urls.py:                       # TODO: Handle redirect
zds/mp/views.py:    # TODO: Clean that up
zds/gallery/models.py:    # TODO rename function to get_users_galleries
zds/utils/paginator.py:    # TODO: Rewrite this garbage, someday

```

**Comment by cgabard** [comment]
Plop, quelqu'un a le courage pour finir ça ?

**Comment by artragis** [comment]
Allez, je m'y mets ce soir. sauf pour la

Staff actions using AJAX TODO: Do not redirect on AJAX requests

je me sens pas trop de la faire celle-là.

2014-12-08 18:04 GMT+01:00 Christophe Gabard notifications@github.com:

**Comment by cgabard** [comment]
Aide toi du lien que j'ai donné tout en haut. Pour les régler tu as 3 choix : 
- C'est facile : tu fix le code
- C'est pas déconnant mais un peu long : tu fais un ticket correspondant et tu vire le TODO du code
- C'est pas réaliste a court terme (ex: Ajax parce que de toute façon il y en a pas), tu vire juste le commentaire.
