### ISSUE TITLE
Désactiver la génération des PDFs

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#3080]
Aujourd'hui, si le tutoriel à publier est trop gros, la publication peut rater parce que le PDF met trop de temps à être généré (générant un _timeout_). On a déjà une option pour désactiver la génération de PDFs (dans la config), mais il serait bien de rajouter une case à cocher à la génération, exprès pour gagner du temps sur des trops gros tutos (les PDFs pouvant être générés à postériori via `generate_pdf`).

**Comment by gustavi** [comment]
Dans quels cas exactement ? Tu as des exemples ?

**Comment by GerardPaligot** [comment]
Il faut alors prévoir un autre bouton pour générer le PDF.

**Comment by artragis** [comment]
> Il faut alors prévoir un autre bouton pour générer le PDF.

ou un tachecron.

**Comment by artragis** [comment]
Ou mieux : créer un mode "watchdog" sur la commande "generate pdf" qui observe la création des dossiers dans contents-public.

**Comment by pierre-24** [comment]
Merci @artragis pour ça :)
