### ISSUE TITLE
Certains TU sont envahissants

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#3081]
Certains TU sont du genre à prendre leurs aises... Par exemple celui testant les galleries ira joyeusement virer toutes mes galleries crée par les utilisateurs... (les dossiers des galleries restent mais pas les images)... C'est gênant... (heureusement que les TU sont pas lancés en prod' :-° )

**Comment by pierre-24** [comment]
Aw, ça explique des choses. Pour régler ça, c'est facile, il suffit de rajouter [ce genre de ligne](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/tests/tests_feeds.py#L27) :)

**Comment by Eskimon** [comment]
je test...

**Comment by Eskimon** [comment]
Bon je comprend pas pourquoi tout semble rentrer dans l'ordre...

**Comment by Eskimon** [comment]
Mais je garde ouvert car ce serait quand même plus propre de faire comme ca

**Comment by motet-a** [comment]
Il me semble que tous ces problèmes ont été corrigés depuis le temps, non ?
