### ISSUE TITLE
[beta 15.9] Le sous-titre d'un article ne "semble" pas versionné

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3086]
Environnement : RC3

Scénario : 
- Je crée un article avec un titre et une description (la description contient "beau gosse")
- Je demande la validation de mon article
- ce dernier se voit publié
- je vais dans la version brouillon de mon article
- je modifie la description 
- **BIM** : la description brouillone apparait direct sur la page d'accueil.

Dans un monde idéal, ce qui est affiché devrait passer par le processus de validation, et là c'est plutot une regression.

**Comment by Eskimon** [comment]
Sais tu si en RC2 ca faisait ca aussi ?

**Comment by firm1** [comment]
Non, je l'avais pas testé celui là en RC2, mais on avait déjà le même bug pour le titre en RC2

**Comment by artragis** [comment]
C'est noté régression, mais, est-ce qu'en prod ça fait pareil?

**Comment by artragis** [comment]
note : c'est bien une régression. Minime mais quand même.

**Comment by Eskimon** [comment]
En prod' tout marche correctement.

Je suppose que le fix sera similaire à celui du titre (ce ticket : #3028 )

**Comment by artragis** [comment]
Ca dépendra, mais possible.

**Comment by pierre-24** [comment]
Voilà aussi :)

**Comment by firm1** [comment]
Suite [au déploiement de la RC-4](https://zestedesavoir.com/forums/sujet/4149/la-beta-cest-plus-fort-que-toi/?page=4#p79369) je constate que ce bug n'est pas corrigé.

Il suffit de voir la différence de sous titre sur la home et dans [la version publique de ce tutoriel](http://beta.zestedesavoir.com/articles/837/binouse-fraiche/)

Dans le doute je réouvre donc

**Comment by SpaceFox** [comment]
Attention, il n'a jamais été prévu de corriger les données cassées par les précédents tests !

@firm1 peux-tu vérifier que le bug est _vraiment_ présent et que ce n'est pas un artefact d'un ancien test ?

**Comment by firm1** [comment]
Testé sur un [nouveau tuto](http://beta.zestedesavoir.com/articles/893/title-of-my-life/) et le bug est vraiment présent Oo

**Comment by artragis** [comment]
quand as-tu modifié le sous-titre? après la release?

2015-10-27 11:08 GMT+01:00 firm1 notifications@github.com:

**Comment by artragis** [comment]
c'est pas possible ça. J'y comprends plus rien. Pourtant tout a été vérifié
20 fois.

@pierre-24?

**Comment by firm1** [comment]
> quand as-tu modifié le sous-titre? après la release?

après la release, j'ai crée l'article après le message de @SpaceFox ci-dessus

**Comment by artragis** [comment]
Oui j'ai vu, je répondais au message tandis que vous étiez en train de
discuter.

2015-10-27 11:32 GMT+01:00 firm1 notifications@github.com:

**Comment by artragis** [comment]
Bon, je sais comment gérer le bug, c'est la bonne nouvelle : il s'agit
simplement d'un template pas à jour.

Par contre, ce template, ç afait 3 fois que je le modifie, ce qui signifie
qu'il y a eu des merges bien foireux quelque part.

**Comment by artragis** [comment]
en fait ma PR n'a tout simplement pas été mergée !

**Comment by SpaceFox** [comment]
J'ai comme l'impression qu'il faut arrêter de faire des rebase s'ils ne
passent pas tout seuls…

**Comment by SpaceFox** [comment]
Si c'est la #3091, on a pourtant bien :

> pierre-24 merged commit c8fcec7 into zestedesavoir:release-15.9 2 days ago

**Comment by artragis** [comment]
pr ici #3123

**Comment by pierre-24** [comment]
Pouf on referme.
