### ISSUE TITLE
Augmenter la taille des fenêtres modals 

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#3087]
Via Thunderseb sur le forum:

> Serait-il possible d'augmenter, ou de rendre resizable, ou de mettre un overflow sur les fenêtres modales ? Quand il y a beaucoup de contenu, il déborde et on n'y a plus accès (à moins de modifier avec F12). Ca se passe fréquemment dans l’administration (image en exemple dans les motifs de refus/acceptation des tutos). Les formulaires de refus et d’acceptation sont aussi concernés, il sont trop étroits dans leur fenêtre modale. 

![d63d94e0-d886-4f3f-a4e7-3b5b50c2c647](https://cloud.githubusercontent.com/assets/8223773/10480161/e49d7848-7268-11e5-844e-c05a22d04285.png)

**Comment by Situphen** [comment]
Et aussi faire en sorte que s'il y a trop de texte, une _scrollbar_ s'affiche !

**Comment by pquentin** [comment]
(Je pense que c'est ce qu'il entendait par "overflow": "overflow: scroll".)

**Comment by gustavi** [comment]
Fixé par @sandhose dans #3284.
