### ISSUE TITLE
erreur 500 lors d'une edition malencontreuse de commentaire saison 3

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3088]
Version beta-RC3

Url incriminée : http://beta.zestedesavoir.com/contenus/reactions/ajouter/?cite=76865&pk=83

Pouf **erreur 500**

On ne devrait jamais avoir d'erreur 500 dans le meilleur des mondes

**Comment by GerardPaligot** [comment]
De l'information complémentaire ? Les pks sont valides ? Le message est masqué ? ...

**Comment by firm1** [comment]
J'ai pris une url au pif valide et j'ai changé la pk. Je ne sais pas si la pk existe quelque part.

**Comment by artragis** [comment]
non en fait l'erreur a changé par rapport à avant (le bug "initial" est corrigé, mais deux corrections de bugs (citer un commentaire masquer) se sont fait de l'ombre.

l'erreur 500 arrive sur une pk qui n'existe pas en bdd, on devrait avoir une erreur 400 et non une 500. Je regarde ça ce midi.

**Comment by artragis** [comment]
/!\ ce bug n'est pas propre à la béta, il est présent en prod.

**Comment by firm1** [comment]
Avec quelle url tu arrive à le reproduire en prod ?

**Comment by GerardPaligot** [comment]
Je n'arrive pas à reproduire en prod non plus.

**Comment by artragis** [comment]
https://zestedesavoir.com/articles/message/nouveau/?article=321&cite=7776555

**Comment by GerardPaligot** [comment]
Ok, `pk` était `article`. Je retag en conséquence.

**Comment by Eskimon** [comment]
Ok
