### ISSUE TITLE
Forum : alerte sur son propre message

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#309]
Il semble impossible d'alerter son propre message. Ça peut sembler logique mais je me demande si cette contrainte a un grand intérêt. Je pense aux modos qui voudront alerter les autres d'une intervention particulière, par exemple.

Si on garde cette contrainte (en fait ce n'est pas bien grave), il faudrait au moins un message d'erreur indiquant "Vous ne pouvez pas signaler votre propre message". En l'état ça fait un peu bizarre de faire une action et de n'avoir aucun retour.

**Comment by cgabard** [comment]
Mouais, perso je ne vois pas de probs à l'autoriser

**Comment by firm1** [comment]
Hmm, normalement, c'est pas logique, mais bon j'autorisera

**Comment by SpaceFox** [comment]
Ca m'est arrivé une ou deux fois, genre pour dire "à surveiller" ou autre
(ou pour troller...)

2014-04-15 15:31 GMT+02:00 firm1 notifications@github.com:

**Comment by ShigeruM** [comment]
Voilà. Donc plutôt qu'un message d'erreur, ce serait pas mal de faire
sauter cette contrainte. :-)

**Comment by firm1** [comment]
C'est fixé, merci
