### ISSUE TITLE
[beta 15.9] la date de dernière mise à jour d'un contenu publié ne représente pas la réalité

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3090]
Version beta-RC3

J'ai un tutoriel déjà publié. Je vais dans la version brouillon, je le modifie. Sans demander de validation de mon contenu, la date de dernière mise à jour visible sur le tutoriel est la date de dernière mise à jour de la version brouillon.

Je suis persuadé d'avoir déjà noté ce bug, mais je ne le retrouve pas.

En attendant c'est une regression par rapport à la prod. Et ce n'est pas très bon pour notre **SEO**, car n'importe quel auteur de contenu, peut mentir à Google en lui faisant croire que son contenu se met très souvent à jour. Car cette date remonte directement dans notre sitemap

**Comment by artragis** [comment]
> Je suis persuadé d'avoir déjà noté ce bug, mais je ne le retrouve pas.

tu l'avais noté sur la migration, et là ça a été corrigé. Je regarde ça ce midi.

**Comment by pierre-24** [comment]
Voir MP avec @DevHugo , @artragis  :)

(il FAUT qu'on rajoute une info de temps à `PublishedContent` et qu'on l'utilise, c'est la seule manière de s'en sortir)

**Comment by artragis** [comment]
OK je regarde ça.

Le 14 octobre 2015 12:58, Pierre Beaujean notifications@github.com a
écrit :

**Comment by DevHugo** [comment]
Je suis overbooker en ce moment. J'aimerai vous aider ...
OK je regarde ça.

Le 14 octobre 2015 12:58, Pierre Beaujean notifications@github.com a
écrit :

**Comment by pierre-24** [comment]
Voilà :)
