### ISSUE TITLE
[beta 15.9] Certains messages d'erreurs sont en anglais

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3093]
Un bug pas très grave au final, mais un bug quand même.

Lorsqu'on essaye d'importer un contenu dont le titre est trop long on a ce message d'erreur "**Title must be a string of less than 80 chars**".

L'avoir en Français serait idéal.

![english-town](https://cloud.githubusercontent.com/assets/6066015/10483616/a46755c4-7280-11e5-80c9-c5ffb8872b1e.PNG)

**Comment by firm1** [comment]
Je suis tombé aussi sur un "**manifest is not well formated**" sur la même page.

**Comment by artragis** [comment]
On sait, je propose qu'on le mette en évol.

**Comment by GerardPaligot** [comment]
Je ne suis pas des masses pour le mettre évol. Afficher de l'anglais pour avertir un utilisateur (potentiellement que francophone) de sa faute, c'est pas cool.

**Comment by artragis** [comment]
Alors @Eskimon peut le proposer aux jeunes fruits zestueux.

**Comment by Eskimon** [comment]
Ca marche, je me garde ca sous le coude :) ( @Emeric54 si tu nous lit ;) )

**Comment by artragis** [comment]
tu as pu comprendre @Emeric54 ?

**Comment by artragis** [comment]
@Emeric54 @Eskimon ?

**Comment by pierre-24** [comment]
Sinon, on reprend à notre compte :p 

(ou la ZEP-12 sortira pour noël 2017, à ce train)

**Comment by Emeric54** [comment]
Désolé, je n'ai pas eu le temps de regarder. Donc prenez la si vous souhaitez, ce sera plus rapide.

**Comment by pierre-24** [comment]
Voilà, c'est bon.

**Comment by firm1** [comment]
Je constate aussi ici que le ticket n'est pas entièrement corrigé. Il me reste encore le message en anglais qui dit : 

> _manifest is not well formated_

Comme précisé plus haut.

**Comment by SpaceFox** [comment]
Dans tous les cas ce problème n'est pas bloquant.

**Comment by GerardPaligot** [comment]
Allez, je me met dessus. Je fais une passe sur toutes les strings du module. PR soon.

**Comment by GerardPaligot** [comment]
PR done #3126!

**Comment by pierre-24** [comment]
Et re-hop :-)
