### ISSUE TITLE
[beta 15.9] erreur 500 lors de l'ajout d'une image a mon tutoriel

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3095]
Scénario : 
- je crée un tutoriel avec un titre et une catégorie
- je vais sur "editer" pour mettre une image a mon tutoriel
- je rajoute l'image ci-dessous (qui ne fait que 176Ko)
- pouff **erreur 500**

Au vu de la fonctionnalité cassé, je poserait bien un tag bloquant par ici. A vous de voir

![erreor500](https://cloud.githubusercontent.com/assets/6066015/10488859/f5c83d9c-729a-11e5-9d0d-0c0e0b0a2adf.PNG)

**Comment by artragis** [comment]
c'est bloquant et la faute est un peu bête : 

``` python
img.slug = slugify(self.request.FILES["image"])
```

manque un path quelquepart...

**Comment by Eskimon** [comment]
Résolu
