### ISSUE TITLE
Erreur 500 sur l'API 

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#3096]
Bonjour,

en allant sur l'URL https://zestedesavoir.com/api/membres/1237/ avec mon navigateur (Firefox) **aucun problème**.

Par contre quand j'essaye avec la librairie URLConnection de java et bien j'obtient une erreur 500.

Je le post ici plutôt que dans le forum java car sur des sites normaux tel que google aucun problème et si je prend cette URL qui provient de l'API de GitHub j'ai également aucun problème. (https://api.github.com/users/winxaito).

Mon code java:

https://gist.github.com/WinXaito/d0557ad607d8bf4e89ee

Résultat avec l'url de GitHub:

```
Authority : api.github.com
Default port : 443
Host : api.github.com
Port : -1
Protocol : https
ContentType : application/json; charset=utf-8

RESULT:{"login":"WinXaito","id":8223773,**...**}
```

Résultat avec l'URL de zds:

```
Authority : zestedesavoir.com
Default port : 443
Host : zestedesavoir.com
Port : -1
Protocol : https
ContentType : text/html; charset=utf-8

RESULT:
<!DOCTYPE html>
<html class="no-js enable-mobile-menu wf-active" lang="fr">
<head>
    <meta charset="utf-8">

    <title>
        Erreur 500 &bull;  Zeste de Savoir
    </title>
    **...**
</body>
</html>
```

**Comment by DevHugo** [comment]
Je sais pas si c'est encore utile mais au cas ou quelqu'un tombe sur le même souci.

Enfait, il te manque un header dans ta requête, le header "Accept" qui te permet de spécifier sous quel format tu attend que le serveur te retourne les données. Par exemple, si tu veux du xml, tu dois lui mettre la valeur "application/xml", si tu veux du json, c'est "application/json".

Ça pourrait donner ça: [https://gist.github.com/DevHugo/97533ebc50817b5fee6a](https://gist.github.com/DevHugo/97533ebc50817b5fee6a) 

Le diff: 

``` java
11c12
<                       URL url = new URL("https://api.github.com/users/winxaito");
---
>                       URL url = new URL("https://zestedesavoir.com/api/membres/1237/");
21c22,24
<                               URLConnection urlConn = url.openConnection();
---
>                               HttpURLConnection urlConn = (HttpURLConnection) url.openConnection();
>                                 urlConn.setRequestProperty("Accept", "text/html,application/xhtml+xml,application/xml");
> 
```

**Comment by aesteve** [comment]
ça devrait pas renvoyer une 500. 

406 à la rigueur.

**Comment by DevHugo** [comment]
~~Je suis assez d'accord.~~

Edit: Enfait, je suis pas d'accord, voir la réponse plus bas

**Comment by WinXaito** [comment]
Ah merci ! 

J'essayerai ça quand j'en aurai le temps, merci.
Du coup, selon la suggestion de aesteve, on réouvre une issue pour le `500 -> 406` ou je garde celle-ci ouverte ?

**Comment by DevHugo** [comment]
Comme tu le souhaite, si on garde celle là, faut changer au moins le titre.

**Comment by DevHugo** [comment]
Excuse moi, j'ai écrit une connerie, l'api renvoi bien un 406 quand le header accept est incorrect.
![406](https://cloud.githubusercontent.com/assets/6099338/12088201/6957db36-b2d9-11e5-875c-ec7d3e302a8c.png).

Quand le header n'est pas spécifié, l'api renvoi une erreur 500 comme on a vu au-dessus.

Si on regarde la [RFC](https://www.ietf.org/rfc/rfc2616.txt) (norme) à la page 100:

> If no Accept header field is present, then it is assumed that the client accepts all media types. 
> If an Accept header field is present, and if the server cannot send a response which is acceptable
> according to the combined Accept field value, then the server SHOULD
> send a 406 (not acceptable) response.

Si on suit la documentation RFC à la lettre, on devrait renvoyer le contenu sous un format que le serveur rest choisi.

J'en appelle au gourou de la secte des API. @GerardPaligot. Puis nos deux dtc, @SpaceFox ou @Eskimon. Je vous invoque ^^ !

Question: Dans le cas ou le client ne précise pas d'entete «Accept», doit-on: 
- Renvoyer la réponse en JSON. (RFC)
- Renvoyer une erreur 406, c'est de la faute du client
- Ne rien changer, laisser l'erreur 500.

**Comment by aesteve** [comment]
:+1: 

La plupart des API choisissent un mime-type arbitrairement, le plus souvent JSON d'ailleurs.

Après je trouve pas ça délirant de renvoyer une 406.

Mais pourquoi on parlait d'erreur 500 plus haut alors ?

**Comment by DevHugo** [comment]
Aujourd'hui, si tu ne spécifie pas le header « Accept », le serveur renvoi une 500. 
Si tu spécifie un header mais que la valeur n'est pas correcte, le serveur renvoi une 406.

**Comment by GerardPaligot** [comment]
Quand j'avais dev la chose, j'avais été lire cette [documentation de DRF](http://www.django-rest-framework.org/api-guide/renderers/#ordering-of-renderer-classes) qui dit : s'il n'y a aucun en-tête "Accept", DRF utilisera le premier format renseigné [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L225) et si on spécifie un format non supporté, DRF lance une exception [NotAcceptable](http://www.django-rest-framework.org/api-guide/exceptions/#notacceptable) qui se concrétise par un code HTTP 406.

Du coup, je ne sais pas pourquoi on obtient une erreur 500. Faudrait l'erreur complète.

**Comment by gustavi** [comment]
Les logs via [Sentry](https://sentry.sandhose.fr/zeste-de-savoir/backend/group/259/) :

```
TypeError: 'NoneType' object is not callable

Stacktrace (most recent call last):

  File "django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework_extensions/etag/decorators.py", line 37, in inner
    kwargs=kwargs,
  File "rest_framework_extensions/etag/decorators.py", line 64, in process_conditional_request
    response = view_method(view_instance, request, *args, **kwargs)
  File "rest_framework_extensions/cache/decorators.py", line 43, in inner
    kwargs=kwargs,
  File "rest_framework_extensions/cache/decorators.py", line 64, in process_cache_response
    response.render()  # should be rendered, before picklining while storing to cache
  File "django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "rest_framework/response.py", line 59, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "rest_framework/renderers.py", line 657, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "rest_framework/renderers.py", line 603, in get_context
    raw_data_patch_form = self.get_raw_data_form(data, view, 'PATCH', request)
  File "rest_framework/renderers.py", line 542, in get_raw_data_form
    serializer = view.get_serializer(instance=instance)
  File "rest_framework/generics.py", line 109, in get_serializer
    return serializer_class(*args, **kwargs)
```

**Comment by GerardPaligot** [comment]
Nous n'avons aucune occurrence à notre code mais `serializer_class(*args, **kwargs)` pourrait être une indication puisque nous avons un usage de la spécification des serializers [un peu à notre manière](https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/api/views.py#L193) (bien qu'on ne devrait pas devoir spécifier un serializer par défaut à mon sens).

PS : Comment pouvons-nous obtenir un accès au sentry de ZdS ?

**Comment by gustavi** [comment]
Faut que tu demandes à @sandhose (et c'est réservé aux dev à causes des données sensibles tkt)

**Comment by motet-a** [comment]
`curl -i https://zestedesavoir.com/api/membres/1237/` retourne désormais une 200, et `curl -i -H 'Accept: invalidcontenttype' https://zestedesavoir.com/api/membres/1237/` retourne une 406 avec `{"detail":"L'en-tête « Accept » n'a pas pu être satisfaite."}`. Tout me semble bon.
