### ISSUE TITLE
Gets last answer of a topic

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#31]
Je suis en train de revoir et de comprendre le module forum du projet. Puis, dans la class `Topic`, je tombe sur cette méthode :

``` python
def get_last_answer(self):
    '''Gets the last answer in the thread, if any'''
    last_post = Post.objects.filter(topic__pk=self.pk).order_by('-pubdate').all()[0]

    if last_post == self.first_post():
        return None
    else:
        return last_post
```

Je ne comprends pas pourquoi cette méthode renvoie `None` si le dernier message est égal au premier. Je suppose que c'est pour éviter de faire le test autre part mais ce n'est pas logique. Pour moi, si une méthode annonce de renvoyer le dernier poste, il renvoie le dernier poste, même si c'est le premier.

Willard, tu sais me dire pourquoi tu as fais ce test ?

**Comment by Coy0te** [comment]
Dans son implémentation, un topic n'ayant qu'un post (c-a-d le texte du topic lui-même) est logiquement considéré comme un topic qui n'a pas de réponse, d'où le fait que la  méthode get_last_answer() renvoie `null` dans ce cas.

**Comment by GerardPaligot** [comment]
My bad, c'est logique vu comme ça. :)

Thanks.
