### ISSUE TITLE
[beta 15.9] recherche : le contenu indexé n'est pas réindexé lors d'une mise à jour du contenu

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3101]
Voici le contexte : j'ai [un article](https://beta.zestedesavoir.com/articles/837/binouse-fraiche/) qui a été publié pour la première fois le 30 septembre. Il a subit des mises à jour et a été republié plus tard avec un autre sous-titre.

Le problème ici est que malgré que ça fait longtemps qu'a eu lieu la 2e  publication, l'information n'a toujours pas été réindexée dans la recherche. (cf [ce lien](https://beta.zestedesavoir.com/rechercher/?q=binouse)). On voit bien la différence de sous-titre entre mon premier lien et le second.

Quelque chose semble donc clocher au niveau du script qui indexe le contenu. Pour l'instant je n'arrive pas a qualifier correctement le bug (mobile toussa), donc je ne sais pas si le problème est uniquement sur le sous-titre ou il est généralisable à l'ensemble des métadonnées.

Quoiqu'il en soit : _es una regresión_

**Comment by pierre-24** [comment]
Ben ... 

Moi j'ai "ça fait du bien" comme sous titre : 

![screenshot from 2015-10-15 19 37 37](https://cloud.githubusercontent.com/assets/7889675/10522203/43abc950-7374-11e5-9514-7d58e1048f79.png)

Or, c'est également ton sous-titre, si je suis bien : 

![screenshot from 2015-10-15 19 38 47](https://cloud.githubusercontent.com/assets/7889675/10522240/79571dac-7374-11e5-931b-070e17904684.png)

Alors que c'est pas le sous-titre sur la PA : 

![screenshot from 2015-10-15 19 40 28](https://cloud.githubusercontent.com/assets/7889675/10522258/9ac41ada-7374-11e5-8022-5ecb7fa2401b.png)

Donc, je pense que la recherche n'est pas en cause et que le problème est à chercher ailleurs ;)

**Comment by firm1** [comment]
Ah en effet c'est le meme bug que celui en cours de correction. Je ferme donc :)
