### ISSUE TITLE
Résolution d'alerte : message de Clem mal formaté

### ISSUE THREAD

**Issue by gagath** [zestedesavoir/zds-site#3103]
Je viens de recevoir un message de résolution d'alerte de Clem, cependant celui-ci a un problème de formatage : il manque au moins un saut à la ligne dans le début du message (ou alors il y a une majuscule en trop au niveau du "vous").

Il pourrait également être intéressant de mettre un lien sur le pseudo de la personne dont on a signalé le message, à voir selon les besoins.

![bug_clem](https://cloud.githubusercontent.com/assets/989521/10558301/f9a2700e-74ca-11e5-9613-0bf1e07cc517.PNG)

**Comment by Situphen** [comment]
> Il pourrait également être intéressant de mettre un lien sur le pseudo de la personne dont on a signalé le message, à voir selon les besoins.

Est-ce réellement nécessaire ? Franchement, je ne pense pas. Au pire, il y a le lien vers le message du sujet.

**Comment by pierre-24** [comment]
Voilà qui est réglé.
