### ISSUE TITLE
Aucun résultats visibles lors d'une recherche

### ISSUE THREAD

**Issue by Emeric54** [zestedesavoir/zds-site#3105]
Lors d'une recherche, par exemple « c++  ou « c », aucun résulats visibles par un utilisateur normal ne sont affichés sur les premières pages.

![capture](https://github-cloud.s3.amazonaws.com/assets/11984858/10565158/2710dd32-75ca-11e5-8bc7-b22b977e3d7f.PNG)

Une solution provisoire, proposée par Spacefox, pourrait être d'indiquer que les résulats sont invisibles.

**Comment by Situphen** [comment]
Déjà reporté par #3050 mais merci quand même ! :)
