### ISSUE TITLE
Masquer les sujets fermés sur la page d'accueil

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3107]
Actuellement les sujets de forum fermés apparaissent quand même sur la page d'accueil. Il serait intéressant de faire que ce ne soit pas le cas.

**Comment by Eskimon** [comment]
Grosso modo il faudra rajouter un exclude sur is_locked ici : https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/managers.py#L62

Je marque que je prend pour laisser à un débutant.

**Comment by Eskimon** [comment]
Et voila, bon boulot !
