### ISSUE TITLE
Forum : +1/-1 sur son propre message

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#311]
Pas gravissime : on peut cliquer sur +1 ou -1 sur son propre message. Ça ne met pas vraiment +1 ou -1 (pour le coup c'est logique) mais ça recharge la page quand même. Le top serait que ces boutons soient désactivés sur ses propres messages.

**Comment by firm1** [comment]
C'est fixé.

merci

**Comment by Alex-D** [comment]
Dans mon intégration, ça n'est pas du tout comme ça. Je l'intégrerais donc différemment dans ma refacto. Ce genre de chose pourra donc réapparaître si je me foire :/
