### ISSUE TITLE
[beta 15.9]  La dernière réponse dans les forums renvoit sur la mauvaise page

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3115]
Je suis un membre **nouvellement inscrit**, je vais sur un forum et je clique sur le lien "Dernière réponse" d'un topic que je n'ai jamais consulté, le lien me renvoit sur la même page sur laquelle je suis déjà (c'est à dire l'accueil du forum).

PS : le bug ne se produit pas avec un ancien compte
PS 2 : le bug n'est pas reproductible en prod

**Screen**

![corrompues](https://cloud.githubusercontent.com/assets/6066015/10611882/882dea1c-774e-11e5-9660-0cff7b1a86ca.png)

**Comment by pierre-24** [comment]
Et voilà :)
