### ISSUE TITLE
Faire un test de charge

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#312]
Parce que si on tombe le 1er jour, ce serait con :)

Test de charge : 
- En lecture / écriture si possible
- En lecture seule si trop compliqué, mais il faudra des données bidon pour remplir (faire les tests de charge sur une base vide...)
- Possibilité de valider les utilisateurs à la main ?
- Prévoir de nettoyer la base après coup

**Comment by Alex-D** [comment]
Nettoyer la base : je dirais plutôt, faire une base séparée, voire un environnement séparé similaire à l'environnement de prod. Non ?

**Comment by SpaceFox** [comment]
Théoriquement oui, mais vu qu'on ne sera pas encore en prod, on aura déjà
l'environnement. Je me plante ?
Pour la base, ce peut être une instance séparée. C'est vrai que c'est
simple à mettre en place avec Django.

Ah, et il me faudra les accès complets à la machine, ne serait-ce que pour
la surveiller.

Le 16 avril 2014 16:34, DEMODE Alexandre notifications@github.com a écrit
:

**Comment by geoffreyc** [comment]
En soit on a pas de "prop" pour le moment, donc on peut très bien utiliser
le serveur de prod pour ça, au moins on sait que les résultats seront
accurate (j'ai oublié le mot francais).

2014-04-16 15:34 GMT+01:00 DEMODE Alexandre notifications@github.com:

**Comment by SpaceFox** [comment]
"Précis" :)
"Prop" c'est une abréviation pour "pré-production" ?

**Comment by geoffreyc** [comment]
c'est "prod" avec un "p" parce que j’écris sans me relire :D

2014-04-16 15:48 GMT+01:00 SpaceFox notifications@github.com:

> "Précis" :)
> "Prop" c'est une abréviation pour "pré-production" ?
>

**Comment by firm1** [comment]
> Prévoir de nettoyer la base après coup

Normalement, il suffit de créer une bd dédiée aux tests ainsi il suffira de poser sur le serveur un fichier setting_prod.py qui modifie des variables telles que : la connexion à la bd, le dossier des tutos, le dossier des media, le dossier des articles, et ça devrait suffire pour obtenir un "environnement isolé". une fois les tests de charges passés, on renomme juste le settings_prod.py et on est sur une base propre.

> Ah, et il me faudra les accès complets à la machine, ne serait-ce que pour
> la surveiller.

De quoi auras-tu besoin exactement ? fais moi une liste et je te file tout ça par mail.

PS : tu compte utiliser quoi comme outil pour les tests de charges ? j'avais justement envie de me faire la main sur multi-mechanize.

**Comment by SpaceFox** [comment]
Je comptais utiliser jMeter, parce que c'est le seul que je connais et
maîtrise :)

Mais si tu veux jouer avec autre chose, fais-toi plaisir !

Par contre si je le fais ce sera la semaine prochaine.

**Comment by firm1** [comment]
> Je comptais utiliser jMeter, parce que c'est le seul que je connais et
> maîtrise :)

Bon choix (normal c'est du java). Je vais tout de même faire joujou avec autre chose :)

> Par contre si je le fais ce sera la semaine prochaine.

No problem.

**Comment by SpaceFox** [comment]
Question importante : y'a une protection quelconque anti-flood sur ce VPS ?
Je sais que sur certain t'as des protections qui s'activent si trop de
traffic arrive / ils consomment trop de puissance etc...

Ce serait con de se faire couper l'accès parce qu'on a fait un test de
charge !

**Comment by Alex-D** [comment]
Sauf erreur de ma part tout est là, troisième colonne : http://www.ovh.com/fr/vps/vps-classic.xml
Et plus précisément là : http://www.ovh.com/fr/anti-ddos/

**Comment by geoffreyc** [comment]
Je sais que sur les dedies on peut desactiver la protection DDOS, je
suppose que c'est possible sur les VPS aussi. Apres le serveur en lui meme
a pas encore de firewall de type fail2ban ou csf de ce que j'ai pu voir,
firm1 peut confirmer?

2014-04-16 16:27 GMT+01:00 DEMODE Alexandre notifications@github.com:

**Comment by SpaceFox** [comment]
De ce que j'ai vu de la doc d'OVH, on ne devrait pas avoir de surprises de
ce côté là. Il faudrait jouer avec des paquets louches (sur les couches 3
ou 4 OSI) pour se faire tacler.

**Comment by SpaceFox** [comment]
Bon, pour éviter de se prendre la tête et avoir des tests impossibles à
maintenir, voici ce que j'ai commencé à faire :
- Tests en lecture seule pour commencer (je sais, c'est pas génial mais
  il faut un début à tout)
- Sur une base / schéma spécifique
- Avec des fixtures qui vont bien (pour enregistrer des centaines
  d'utilisateurs / milliers de posts), elle-mêmes générées et paramétrables
  (en python)

Le but est de garantir déjà que ça va tenir en lecture.
D'ailleurs, on a un moyen de rentrer facilement genre 100 tutos dans la
base ?
Le début est présent dans la branche "jMeter"

Dans une v2 je rajouterai une petite proportion de gens qui écrivent
(surtout des posts en fait) pour voir.

Si quelqu'un a des idées plus intelligentes, qu'il fasse signe :)

**Comment by firm1** [comment]
> Si quelqu'un a des idées plus intelligentes, qu'il fasse signe :)

Je ne sais pas si c'est forcément judicieux de faire des tests en se basant sur des fixtures (entre autre parce qu'elle ne sont pas trop maintenables). 

J'aurai réutilisés les factories des tests pour pousser directs dans la bd. Et du coup en se basant dessus, on arrive à charger tout ce qu'on veux automatiquement ( tuto, forums, membres, post).

mais bon, en gros, je peux te fournir un script de génération de tutos bidons qui les charge direct dans la bd (avec le git en dessous et tout) genre cette nuit.

P

**Comment by SpaceFox** [comment]
> J'aurai réutilisés les factories des tests pour pousser directs dans la
> bd. Et du coup en se basant dessus, on arrive à charger tout ce qu'on veux
> automatiquement ( tuto, forums, membres, post).

On peut utiliser ces factories en dehors des tests ?
Si oui, c'est plus intelligent que les bouts de scripts que j'ai fait hier
alors (qui font grosso merdo la même chose mais par l'intermédiaire de
fichiers de fixtures).

> mais bon, en gros, je peux te fournir un script de génération de tutos
> bidons qui les charge direct dans la bd (avec le git en dessous et tout)
> genre cette nuit.

Ce serait génial.

**Comment by firm1** [comment]
> Ce serait génial.

J'ai fait un [premier jet à l'aveugle](https://github.com/Taluu/ZesteDeSavoir/commit/18d931d8f0c0e071cf09f32086f6b13d01926653). Mais c'est pour donner un ordre d'idée, et au cas ou je n'ai pas le temps par la suite.

**Comment by firm1** [comment]
Comme promis, j'ai travaillé un peu plus sérieusement sur le sujet. Je me suis un peu emmelé les pinceau avec git, et du coup je n'ai pas pu faire mieux que de te le poser sur [cette branche](https://github.com/Taluu/ZesteDeSavoir/tree/features-load-testing-data) en fechant la tiennte.

Tu verras dans le readme, la section [Pour les robots](https://github.com/Taluu/ZesteDeSavoir/tree/features-load-testing-data#pour-robots) tu as la documentation sur le chargement

**Comment by SpaceFox** [comment]
OK merci !

**Comment by SpaceFox** [comment]
J'aurai les résultats définitifs ce soir, mais de ce que j'en vois maintenant :
- On est pas terrible sur l'unitaire : quelle que soit la charge serveur, nos pages sont relativement longues à charger. S'il y a un effort à faire, c'est sur ce point.
- Par contre, on tient les 60 visiteurs simultanés sur mon test sans ralentissement exagéré du site.

60 visiteurs simultanés, ça a l'air de rien comme ça, mais ça veut dire environ 8 pages (avec toutes les ressources associées) par seconde. En supposant un pic quotidien de 10x la moyenne (chiffre standard), ça fait 0.8 pages par seconde en moyenne sur la journée, 2900 par heure, 70 000 par jour et un peu plus de 2 000 000 par mois.

Pour comparaison, le SdZ en 2012 c'était 16 000 000 de pages vues par mois.

Sachant qu'on a fait aucune optimisation et que le serveur n'est pas un foudre de guerre, on a de la marge de ce côté :)

**Comment by firm1** [comment]
Juste pour signaler a ceux qui lirait ton analyse que tes tests ont été
fait sur la preprod qui est moins puissante que la prod.

**Comment by Alex-D** [comment]
Il me semble que Geoffrey a rajouté un vCore et que donc c'est la même puissance. Non ?

**Comment by geoffreyc** [comment]
Justement j'ai egalisé les deux serveurs avant les tests

**Comment by SpaceFox** [comment]
Pas tant que ça en plus. Les tests de robustesse ont été fait sur 3 coeurs.
La RAM ne rentre pas en ligne de compte, j'ai du monter à 300 Mio
d'utilisation.

**Comment by SpaceFox** [comment]
Du coup, tout ça c'est fait.

**Comment by SpaceFox** [comment]
Je rouvre : il nous en faut un nouveau avant la sortie publique.

Est-ce que quelqu'un serait capable de m'installer la préprod à l'identique de la prod ? Ce serait génial !

**Comment by geoffreyc** [comment]
Bon, j'ai tenté de te mettre tout ce en preprod, mais quand on se connecte,
on se prend ca a la gueule:

[image: Inline image 1]

**Comment by geoffreyc** [comment]
![errorzds](https://cloud.githubusercontent.com/assets/5312097/3293379/716f21a6-f59a-11e3-93e9-4c532ae8d70f.png)

**Comment by Alex-D** [comment]
Est-ce que tu as bien :
- migré la BDD
- mis à jour le projet (je suppose que oui, mais on sait jamais)
- vérifié la validité des données dans la BDD ?

**Comment by geoffreyc** [comment]
Oui
Oui
C;est un dump de la db live

2014-06-16 22:18 GMT+01:00 Alexandre Demode notifications@github.com:

**Comment by Alex-D** [comment]
Ca m'avait fait ça à un moment parce que ça trouvait pas le topic relatif à une alerte qui du coup n'avait pas son topic lié par foreign key. Mais là ça n'a pas l'air d'être ça....

**Comment by Alex-D** [comment]
Hey ! Où est-ce qu'on en est à ce niveau ?

Je viens de faire un tour sur la preprod, le footer n'affiche pas la version. J'imagine donc que le back n'est pas à jour : est-ce que tu as bien `pip install -r requirements --upgrade` ? Y a eu pas mal de changements dernièrement, notamment sur le parseur Markdown.

**Comment by geoffreyc** [comment]
Je m'y re-penche ce soir si j'ai le temps, de toute facon je veux repartir
de zero su la preprod pour que ce soir vraiment preprod === prod

2014-06-20 13:56 GMT+01:00 Alexandre Demode notifications@github.com:

**Comment by Alex-D** [comment]
Niquel alors ! N'oublies pas tous nos joujous du front :D

**Comment by SpaceFox** [comment]
J'ai besoin que la #1042 soit résolue pour corriger celle-ci.

**Comment by Eskimon** [comment]
Problème de BDD réglé, tu peux avancer @SpaceFox :)

**Comment by SpaceFox** [comment]
En fait maintenant on s'en fout, le passage en prod l'a fait pour nous :)

Il me semble que @gustavi voulait en refaire un pour prouver que PostgreSQL est en fait mieux que MySQL, mais du coup ça concerne plus la #413. Je ferme donc celle-ci.
