### ISSUE TITLE
[beta 15.9] erreur 500 lors de l'import d'une article s02e03

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3122]
Scénario : 
- Je télécharge l'archive d'un article
- J'ouvre le manifest.json
- Pour un extrait je modifie le contenu de slug et de title en remplaceant leurs valeurs par la chaine `.........................................................................................................................................................................................................................................................................................................................................`
- je ré-importe l'article et **BIM** erreur 500

On ne devrait jamais avoir d'erreur 500 dans la vie

**Comment by SpaceFox** [comment]
On l'avait pas corrigé celui-ci ?!

**Comment by firm1** [comment]
C'est une arlésienne aussi.

J'ai envie de dire qu'un TU nous eviterait pas mal de saisons sur ce genre de bug. :-°

**Comment by SpaceFox** [comment]
Tant que j'y pense : tu peux gagner du temps en ne mettant plus les phrases comme « On ne devrait jamais avoir d'erreur 500 dans la vie », tout le monde le sait.

**Comment by artragis** [comment]
est-ce bloquant?

**Comment by artragis** [comment]
(ps : le TU existe)

**Comment by GerardPaligot** [comment]
Le cas est super limite. J'estime pas ça bloquant.

Par contre, pourquoi le TU n'échoue pas ?

**Comment by SpaceFox** [comment]
Ce n'est pas bloquant du tout, et si le TU existe il devrait planter sur ce cas.

**Comment by artragis** [comment]
parce qu'il est unitaire : il vérifie bien qu'on envoie une exception dans
ce genre de cas...

2015-10-27 11:53 GMT+01:00 Gérard Paligot notifications@github.com:

**Comment by GerardPaligot** [comment]
Il vérifie qu'une erreur 500 est lancée ?

**Comment by artragis** [comment]
Non, il vérifie que la fonction qui traite le manifeste envoie une exception.

**Comment by GerardPaligot** [comment]
@firm1 Impossible de reproduire ton bug en local en suivant ta procédure puis en la modifiant un peu pour tenter d'y parvenir.

**Comment by firm1** [comment]
Hmm, je viens de le reproduire.

Voici mon manifest

``` json
{
    "object": "container", 
    "slug": "zeste-de-savoir-vous-souhaite-une-bonne-annee-2015", 
    "title": "Zeste de Savoir vous souhaite une bonne annee 2015", 
    "introduction": "introduction.markdown", 
    "conclusion": "conclusion.m", 
    "children": [
        {
            "object": "extract", 
            "slug": "petit-bilan-de-lannee-2014", 
            "title": "Petit bilan de l'annee 2014\n\n", 
            "text": "petit-bilan-de-lannee-2014.md"
        }, 
        {
            "object": "extract", 
            "slug": ".........................................................................................................................................................................................................................................................................................................................................", 
            "title": "......................................................................................................................................................................................................................................................................................................", 
            "text": "les-bonnes-resolutions-de-la-communaute-pour-2015.md"
        }
    ], 
    "version": 2, 
    "description": "Quelles sont les bonnes resolutions de la communaute pour la nouvelle annee ?", 
    "type": "ARTICLE", 
    "licence": "CC BY"
}
```

**Comment by artragis** [comment]
Etant donné qu'un fichier ne peut pas avoir autant de caractères dans son nom (c'est ça l'erreur), ce bug n'en est pas un. Il faut avoir l'esprit tordu pour aller volontairement faire ce faux manifest. 

Il faut juste capter une exception de type IOError quelque part dans le code. Mais là c'est vraiment pas bloquant.

**Comment by SpaceFox** [comment]
Je rajoute qu'obtenir un tel manifeste tient de la volonté de faire n'importe quoi, et que donc la solution qui consiste à envoyer chier l'utilisateur avec un message de type « manifeste invalide » est parfaitement valide.

**Comment by firm1** [comment]
Tout à fait. Un message d'erreur clair, mais pas d'erreur 500

**Comment by pierre-24** [comment]
Ah. En gros, c'est python qui nous envois balader 

```
IOError at /contenus/importer/5/test-1/
[Errno 36] File name too long
```

Chouette.

**Comment by Eskimon** [comment]
et revoila
