### ISSUE TITLE
[beta 15.9] le nouveau contenu publié ne semble pas indexé par la recherche

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3124]
J'essaye tant bien que mal de retrouver un article qui a été publié il y'a 10 jours sur la beta.

Dans la recherche (en spécifiant que je ne cherche qu'un article) je tape donc les mots clés "[market design](http://beta.zestedesavoir.com/rechercher/?q=market+design&models=article)" , "[femme](http://beta.zestedesavoir.com/rechercher/?q=femme&models=article)", "[voisin](http://beta.zestedesavoir.com/rechercher/?q=voisin&models=article)" ... mais rien a faire, impossible de retrouver [ce contenu](http://beta.zestedesavoir.com/articles/207/devez-vous-quitter-votre-femme-pour-celle-du-voisin/) qui a été publié en RC3 une seule fois.

Je vais peut être attendre (j'ignore le timing du cron) pour voir si l'article publié en RC4 apparait dans le recherche ([car pour le moment ce n'est pas le cas](http://beta.zestedesavoir.com/rechercher/?q=Title+of+my+life)).

**Comment by artragis** [comment]
y a-t-il un cron sur la béta @Eskimon @sandhose ?

**Comment by sandhose** [comment]
Oups.

![image](https://cloud.githubusercontent.com/assets/1549952/10758308/fa21db1c-7cb0-11e5-9d83-2e3be2d626c6.png)

J'avais pas testé le cron en question à l'installation, et j'avais bêtement copié-collé celui que j'avais sur mon serveur (qui avait pas les même chemin d'installation). Normalement, c'est réglé, plus qu'a attendre que ça réindexe

**Comment by firm1** [comment]
super ça fonctionne mieux
