### ISSUE TITLE
[beta 15.9] avec zero reaction sur un article le lien ne dirige pas au bon endroit

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3125]
Lorsqu'un article n'a aucune réaction, le lien sur la home page devrait rediriger vers la fin de l'article (début des commentaires en fait). Ce n'est pas le cas.

Par exemple dans le cas d'un article de la beta, le lien sur le nombre de réactions la home : `https://beta.zestedesavoir.com/articles/207/devez-vous-quitter-votre-femme-pour-celle-du-voisin/#reactions` au lieu d'être `https://beta.zestedesavoir.com/articles/207/devez-vous-quitter-votre-femme-pour-celle-du-voisin/#comments`

**Comment by pierre-24** [comment]
Voilà qui est fait, merci @GerardPaligot  :)
