### ISSUE TITLE
Pas de bouton pour supprimer une section dont le contenu est vide

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3128]
Scénario :
- Je cree un tutoriel
- J'ajoute une section (je rempli juste son titre, pas le contenu
- J'ajoute une deuxième section (juste le titre aussi)
- J'ajoute pareillement une troisième section

Lorsque je reviens sur la page de mon tutoriel, pour chaque bouton, j'ai un bouton pour déplacer et éditer la section mais je n'ai pas le bouton pour le supprimer.

**Comment by pierre-24** [comment]
Si par "section", c'est bien les anciens extraits que tu entends, _I'm unable to reproduce the bug_ : 

![screenshot from 2015-10-27 19 58 19](https://cloud.githubusercontent.com/assets/7889675/10769218/291ada8e-7ce5-11e5-872c-8dcf8f2dfe53.png)

Est ce que tu sais me rajouter sur le tuto sur la bêta ou tu fais ça ?

**Comment by firm1** [comment]
Je fais ça depuis un mobile. Peut-être que les boutons sont visibles en
effet sur PC.

Le mar. 27 oct. 2015 20:01, Pierre Beaujean notifications@github.com a
écrit :

**Comment by pierre-24** [comment]
_Edit : j'ai rien dit, mauvaise issue._

**Comment by pierre-24** [comment]
![screenshot from 2015-10-27 20 49 03](https://cloud.githubusercontent.com/assets/7889675/10770583/5584e31a-7cec-11e5-8e5f-e34de379b98a.png)

En fait, c'est tordu, c'est du front : le bouton est caché derrière le message. Aucune idée de comment gérer ça, c'est du front.

**Comment by artragis** [comment]
le bug existe en prod on dirait en plus.

**Comment by artragis** [comment]
Bon, c'est une certitude, le bug se produit en prod, c'est un problème de front.

Par contre on notera que la zep-12 a inversé l'ordre des bouton edit/déplacer/supprimer.

Bref pour ce bug, merci d'enlever le tag [beta 15.9].

@firm1   @Eskimon @sandhose

**Comment by firm1** [comment]
Le tag beta est parti.
