### ISSUE TITLE
Modifier les suggestions de la barre de recherche

### ISSUE THREAD

**Issue by Emeric54** [zestedesavoir/zds-site#3131]
Les suggestions de la barre de recherche restent inchangés depuis des semaines (« Mathématiques, UDK, HTML, Java, PHP ».) Il serait bon qu'elles soient choisis aléatoirement via les différentes catégories du site ([voir ici](https://zestedesavoir.com/forums/sujet/4422/modifier-les-suggestions-de-la-barre-de-recherche/), sujet sur le forum).

**Comment by GerardPaligot** [comment]
Est-ce vraiment nécessaire de faire une requête en base supplémentaire rien que pour ça ?

**Comment by Emeric54** [comment]
Je pensais procéder comme pour les citations de Clem, avec un simple fichier texte.

**Comment by GerardPaligot** [comment]
Ca serait bizarre parce qu'on aurait des catégories en base de données et dans ce fichier. Il faut alors maintenir ces 2 sources de données. Je ne suis pas contre cette évolution mais faut trouver une meilleure solution.

**Comment by Emeric54** [comment]
J'ai repris _catégories_ du post initial sur le forum. Mais l'on peut tout simplement parler de _suggestions_, pas forcément des catégories du forum. Cela pemettrait de donner simplement un peu de dynamisme.

**Comment by SpaceFox** [comment]
J'aime bien l'idée. Pour éviter de noyer le serveur avec des requêtes inutiles, on pourrait très bien imaginer mettre cette info en cache et la changer, par exemple, tous les jours - ou même toutes les heures.

**Comment by Emeric54** [comment]
Pourquoi pas si c'est nécessaire. Mais pour des requêtes de ce genre, est-ce que ce l'est vraiment ? (_Je n'en ai aucune idée_)

**Comment by SpaceFox** [comment]
Oui et non : un aller-retour à la BDD est en soi peu coûteux, mais ici c'est facile à éviter.

En fait, la requête elle-même est très rapide, mais l'enrobage (préparation, envoi au SGBD, traitement du résultat) est relativement coûteux.

**Comment by Emeric54** [comment]
D'accord. Donc dans ce cas, il serait préférable de mettre l'info en cache (?)

> Pour éviter de noyer le serveur avec des requêtes inutiles, on pourrait très bien imaginer mettre cette info en cache et la changer, par exemple, tous les jours - ou même toutes les heures.

Qu'entends tu par _cette info_ ? La liste des catégories ?

_(PS : Désolé pour toutes les questions)_

**Comment by WinXaito** [comment]
> Qu'entends tu par cette info ? La liste des catégories ?

C'est en effet ce qu'il sous entendait selon moi :) Mais moi  je dis pourquoi pas !

**Comment by Eskimon** [comment]
Pourquoi du cache, pourquoi ne peux t-on pas faire exactement comme pour les citations de Clem' qui fonctionne sur ce système ?

**Comment by SpaceFox** [comment]
Les citations sont prises dans un fichier et sont fixes. L'idée de base, si j'ai bien compris, c'est d'aller chercher les exemples dans les tags existants sur le site.

**Comment by Emeric54** [comment]
Pour mieux prendre un main le code de ZdS, je me suis fait un petit système comme pour les citations de Clem' : 5 suggestions sont choisises aléatoirement dans un fichier texte à chaque chargement de la page. Du coup, ça permet également également d'inclure des suggestions autres que des catégories. Mais le problème est qu'en cas de d'ajout d'une nouvelle catégorie, le fichier ne sera pas automatiquement mis à jour. Mais est-ce vraiment nécessaire ?

**Comment by WinXaito** [comment]
Au pire on peut imaginer un petit script mis en cron 1 fois par jour qui update le fichier non ?

**Comment by Emeric54** [comment]
Avec la solution actuelle, on est parti sur une liste de suggestions, et non une liste des catégories du site (d'ailleurs, les catégories ne sont pas toutes inscrites).

Je ne sais pas si c'est vraiment nécessaire, l'ajout de nouvelles catégories sur ZdS n'est que peu fréquent.

**Comment by pierre-24** [comment]
Voilà :)
