### ISSUE TITLE
[v12] les anciennes alertes de modération n'ont pas été migrées

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3132]
Comme le montre le screen suivant, les anciennes alertes sur les comms d'un article pointent sur la version `/oldarticles/`.

![capture d ecran de 2015-10-30 07-45-47](https://cloud.githubusercontent.com/assets/6066015/10840029/fb0b2020-7eda-11e5-9a4c-c1f6402504d0.png)

**Comment by pierre-24** [comment]
"Logique" (enfin, relativement).

Ceci dit, est ce qu'il y a réellement matière à correction, sachant qu'à priori on ne compte pas revenir en arrière ?

**Comment by Eskimon** [comment]
> Ceci dit, est ce qu'il y a réellement matière à correction, sachant qu'à priori on ne compte pas revenir en arrière ?

Yep je me pose la question de la pertinence. À priori une fois ces alertes résolues tout ira bien :) Je ferme donc, inutile de perdre du temps sur des corrections qui ne pourront toute façon pas se reproduire ensuite.
