### ISSUE TITLE
Le suivi des articles ne fonctionne plus si on y a pas réagi

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#3133]
Sur la page d'acceil, le lien de la bulle des commentaires renvois systématiquement à la première réaction, indépendamment du fait qu'on aie déjà lu des commentaires ou pas, ce qui est une régression (plutôt pénible sur les articles à plusieurs pages de commentaires :p )

**Comment by Eskimon** [comment]
à fermer ici :)
