### ISSUE TITLE
"Dans le futur" sur l'historique des tutoriels

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#3135]
Lorsqu'on effectue une modification, on peut voir apparaitre que la modification a été effectuée dans le futur : 

![screenshot from 2015-10-30 08 30 10](https://cloud.githubusercontent.com/assets/7889675/10840541/9934cf62-7ee0-11e5-84f6-f76b2e6ac36a.png)

(on dirait un bug ... De changement d'heure :o )

**Comment by pquentin** [comment]
(Pardon, c'est corrigé avec F5, pas de souci d'image.)

**Comment by Eskimon** [comment]
Sinon une idée de pourquoi ce bug ?

**Comment by pierre-24** [comment]
Absolument aucune. Peut être que le format de stockage de la date côté Git est pas exactement le même, mais à priori, c'est [filtre de date appliqué sur timestamp](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/view/history.html#L110), comme d'hab' ... Ou presque : 

```
{{ commit.authored_date|humane_time:commit.author_tz_offset }}
```

Et je me souviens plus exactement ou est la PR originale, mais je crois que ce `commit.author_tz_offset` avait été ajouté pour une bonne raison. Le test, maintenant, c'est d'attendre le changement d'heure aux USA pour voir si le système est pas simplement en train de s’emmêler les pinceau.

**Comment by yapper-git** [comment]
J'ai testé en local et en réalité la date de commit ne correspond pas à la date si je committe à la main dans le dépôt via la commande git commit.
Il y a une différence, voici que j'obtiens avec git log:

> Commit depuis la ligne de commande (via git commit) :
> Tue Nov 3 **17**:48:11 2015 **+0100**
> 
> Commit généré par Django (via gitpython) :
> Tue Nov 3 **18**:48:11 2015 **+0200**

Je suppose que le fuseau horaire est incorrect lors d'un commit via gitpython dans le code de ZdS mais je ne sais pas à quel niveau ça coince…

**Comment by pierre-24** [comment]
Le code de Gitpython est très pénible à lire. Ceci dit, on peut trouver [ici](https://github.com/gitpython-developers/GitPython/blob/master/git/objects/commit.py#L102-L105) : 

> ```
> :note:
>        Timezone information is in the same format and in the same sign
>        as what time.altzone returns. The sign is inverted compared to git's
>        UTC timezone."""
> ```

Le code [semble indiquer aussi que](https://github.com/gitpython-developers/GitPython/blob/master/git/objects/commit.py#L81-L83) : 

> ```
>     :param authored_date: int_seconds_since_epoch
>        is the authored DateTime - use time.gmtime() to convert it into a
>        different format
> ```

Bref, ?!?

**Comment by pquentin** [comment]
Notons quand même que "Tue Nov 3 17:48:11 2015 +0100" est la même heure que "Tue Nov 3 18:48:11 2015 +0200". C'est même "Tue Nov 3 16:48:11 2015 +0000", soit "2015-11-03T16:48:11Z" au format [ISO 8601](https://xkcd.com/1179/).

Comment est-ce que vous parsez la date ensuite : aware ou native ? Est-ce que la date actuelle utilisée pour la comparaison est une datetime aware ou native ? Je veux bien étudier le code si on me dit où regarder.

**Comment by pierre-24** [comment]
Le code [est là](https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/templatetags/date.py#L72) et fait appel à la fonction un peu plus haut dans le fichier :)

**Comment by pquentin** [comment]
Pour commencer, [un bug dans GitPython](https://github.com/gitpython-developers/GitPython/issues/362) (que j'ai pu diagnostiquer grâce à @yapper-git) lui fait croire que les commits sont fait en UTC+2 alors que le serveur est passé en UTC+1.

Ceci dit, le timestamp devrait être correct même si GitPython corrige son bug. Ce qui est bizarre, c'est que utcfromtimestamp() n'a pas d'info de timezone, donc la date ne peut pas être bonne : une date UTC sera interprétée comme une date UTC+1. C'est-à-dire qu'un commit fait maintenant sera interprété comme une heure dans le futur.

Deux questions :
- Est-ce que ce même code fonctionnait avant le passage à l'heure d'hiver, ou est-ce que c'est récent (genre lié a à la ZEP-12) ? Si le bug vient d'apparaître, mon explication n'est pas logique : on aurait du être deux heures dans le futur pendant l'heure d'été.
- Est-ce que le serveur est bien en UTC+1 ?

**Comment by pierre-24** [comment]
Il me semble que le bug m'as frappé récement, et pas cet été, mais je testais en général en local.

**Comment by pierre-24** [comment]
(ceci dit, ça le fait en local aussi maintenant, donc à mon avis, c'est lié au changement d'heure o_O )

**Comment by yapper-git** [comment]
Je n'avais pas repéré le bug avant. C'est moi qui ait fait la PR pour modifier le diff des tutos (incorporé à la ZEP-12) mais je n'avais pas rencontré ce bug. Il me semble pourtant avoir testé avec des tutoriels modifiés récemment et j'ai dû d'ailleurs soustraire le fuseau horaire pour cela sauf erreur…

En tout cas en local j'ai le même problème et je suis bien sur le fuseau horaire de Paris au niveau du système.

De plus je pense qu'il serait bien de mettre à jour la version GitPython utilisée par ZdS : https://github.com/zestedesavoir/GitPython (ou de passer à pygit2 ;-))

**Comment by pquentin** [comment]
Oui @yapper-git ce bug n'a pas du apparaître avant le changement d'heure.

J'ai le même problème avec la dernière version de GitPython. Non seulement y'a le bug de +0200 au lieu de +0100 mais il semblerait GitPython me renvoie ensuite une mauvaise date, décalée d'une heure : le bug ne serait pas dans ZdS. Je n'ai pas pu investiguer davantage.

**Comment by pquentin** [comment]
Je ne sais pas si vous avez vu, mais du coup j'ai essayé de corriger le problème dans la PR #3158. Je suis pas trop au point niveau contribution à ZdS, à vous de me dire ce que je peux améliorer.

**Comment by yapper-git** [comment]
Je ne suis pas non plus un régulier contributeur de ZdS mais je peux te dire qu'il manque la partie _QA_ dans ta PR.

**Comment by pierre-24** [comment]
Merci @pquentin (et puis en plus, ça a permis à gitpython de s'améliorier). Concernant le passage éventuel à pygit ...Y'a une histoire de python3.
