### ISSUE TITLE
On peut commenter sur les anciennes versions des articles

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3136]
# voir [ça](https://github.com/zestedesavoir/zds-site/issues/3136#issuecomment-168430901) avant de fermer

Cf ce message https://zestedesavoir.com/oldarticles/332/la-ligne-editoriale-officielle-de-zeste-de-savoir/?page=6#p83705 qui n'est pas repris sur la nouvelle version de l'article : https://zestedesavoir.com/articles/222/la-ligne-editoriale-officielle-de-zeste-de-savoir/?page=5#p82654

**Comment by pierre-24** [comment]
"Normal", on a rien bloqué. Donc à priori, les gens suivent des anciennes notifs (même si j'ai le souvenir qu'elles aie été migrée). Donc à priori, ça va ce calmer, mais on peut toujours bricoler avec un .htaccess.

**Comment by SpaceFox** [comment]
Corrigée pour le code, mais on laisse les tables pour l'instant (cf la discussion de la PR).

**Comment by GerardPaligot** [comment]
@SpaceFox Cette issue sera fermée quand les tables seront supprimées aussi ?

**Comment by SpaceFox** [comment]
Oui.

**Comment by artragis** [comment]
elles sont fermées
