### ISSUE TITLE
Un tutoriel sans date de publication

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3137]
[ce tutoriel](https://zestedesavoir.com/tutoriels/334/panda3d-et-heightmap/) n'a pas de date de publication et se retrouve relegué à la fin de la liste des tutoriels.

**Comment by artragis** [comment]
désolé, mais là on ne peut rien faire à part demander @SpaceFox d'aller dans la bdd lui mettre une date de publication en 2014.

**Comment by SpaceFox** [comment]
Je veux bien, mais dans l'historique de validation, il n'est jamais considéré comme validé. @Eskimon c'est toi qui t'en étais chargé, tu l'avais validé ou non ?

**Comment by gustavi** [comment]
PING @Eskimon et @SpaceFox

**Comment by Eskimon** [comment]
> tu l'avais validé ou non ?

Dans mes souvenirs ouaip j'avais validé et tout s'était bien passé. Du coup je sais pas pourquoi ce bug serait apparu. S'il faut je fouillerais dans mes mails pour retrouver la date de publication

**Comment by gustavi** [comment]
Je clos ici car c'est un bug qui n'est plus d'actualité. Impossible à reproduire. Si quelqu'un y arrive on ré-ouvre mais je n'y crois pas.
