### ISSUE TITLE
Mise en bêta : permettre d'ajouter un commentaire au message auto-publié

### ISSUE THREAD

**Issue by Deuchnord** [zestedesavoir/zds-site#3138]
Hello,

J'aurais une petite suggestion à faire pour la fonctionnalité de mise en bêta des tutos : en effet, lorsque l'on met en bêta un tuto ou que l'on met à jour un tuto déjà en bêta, un message est automatiquement publié sur le forum dédié, ce qui est une excellente chose.

Cependant, j'aurais apprécié pouvoir ajouter un commentaire personnalisé pour ajouter par exemple une remarque ou un changelog à l'adresse des bêta-lecteurs du tuto, afin d'éviter de devoir éditer le message en question.

**Comment by Eskimon** [comment]
Doublon je pense ;)

https://github.com/zestedesavoir/zds-site/issues/2532
