### ISSUE TITLE
disparition de l'article lorsque publication mineure

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#3139]
Il semblerait que lorsqu'on fait une mise ajour mineure (donc décocher la case "majeur") l'article disparaisse.

**Comment by pierre-24** [comment]
Ah, c'est ennuyeux. Un problème de MàJ de date ?

**Comment by pierre-24** [comment]
Ah, non, je sais ce qui c'est passé : l'article a changé de nom avec la MàJ. Donc a créé un nouveau objet `PublishedContent` (le slug ayant changé), sans `publication_date`. C'est pervers ;)

**Comment by pierre-24** [comment]
Namely, il suffit de rajouter la date de publication éventuelle [là](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/utils.py#L648).

**Comment by artragis** [comment]
pas impossible. ou de condition dans le template (il y a un truc genre {%
if date... %}

2015-10-30 10:28 GMT+01:00 Pierre Beaujean notifications@github.com:

**Comment by artragis** [comment]
je pense que c'est bloquant et appelle un hotfix.

**Comment by SpaceFox** [comment]
100% d'accord avec le chaudcorrectif.

**Comment by pierre-24** [comment]
+1, j'osais pas le proposer :p

**Comment by artragis** [comment]
il est possible que ça soit à cause de ça : https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/utils.py#L647 on recrée un PublishedContent sans lui donner de publication_date.

**Comment by pierre-24** [comment]
C'est ce que je disais plus haut.

**Comment by Eskimon** [comment]
C'est tout good :)
