### ISSUE TITLE
Clicking instead of hovering menues?

### ISSUE THREAD

**Issue by Ge0** [zestedesavoir/zds-site#314]
Il me semblait que les menus du haut se déroulaient au **survol** de la souris et non pas au **clic**. Ou alors ma mémoire me fait défaut...

Du coup, question : l'obligation de cliquer sur les menus pour les dérouler est voulue ou pas ? Pourquoi ne pas dérouler les menus au survol ? Ça engendrerait des bogues ou quelque chose du genre ?

**Comment by SpaceFox** [comment]
Avis personnel :

> Pourquoi ne pas dérouler les menus au survol ?

Parce que c'est pourri les menus au survol.
Pourquoi c'est pourri ?
- Parce que ça t'oblige à garder la souris dans le "tunnel" du menu (si
  tu sors, il se ferme). Ce qui peut être très chiant selon la forme du menu
- Parce que si tu le survoles par mégarde, il s'ouvre. D'autant plus
  chiant que le menu est grand
- Parce que le survol n'existe pas sur mobile

**Comment by Ge0** [comment]
Ok.

**Comment by SpaceFox** [comment]
Ce n'était qu'un avis personnel, peut-être que nos graphistes/ergonomes ont
de vrais arguments qui contrent les miens :)

2014-04-17 11:16 GMT+02:00 Geoffrey R. notifications@github.com:

**Comment by firm1** [comment]
Pour encore plus de précision, relatons l'histoire ...

A l'époque on pouvais choisir dans ses paramètres d'utiliser les menus au survol ou au clic, c'était proposé en option. Jusqu'au jour ou le design d'Alex-D est arrivé avec la seule possibilité d'avoir du clic, et donc on a viré le paramètre en question.

Actuellement le front-end qui est en place nous permet de ré-offrir les deux possibilités (clic et survol) au choix. Je ne l'ai pas mis en place parce que depuis le temps personne ne s'est plaint du défilement au clic (même si je suis partisan du survol) et que le design d'Alex-D ne sait pas s'adapter au survol.

Mais si la demande se fait sentir, c'est quelque chose qui peut être solutionné en donnant le choix aux utilisateurs tout en sachant que sur mobile le défilement se fera au clic de toute façon.

**Comment by Alex-D** [comment]
Vu que c'est moi qui l'ai codé comme ça dans le design final je peux répondre très simplement :
un menu déroulant au survol est un enfer pour l'accessibilité.

Rien que ça, ça suffit.

**Comment by Ge0** [comment]
D'accord. Je trouvais juste plus pratique la configuration du survol, peut-être une question d'habitude.

Perso ça me fatigue de cliquer au niveau des menus mais ça n'engage que moi. C'est tout ce que j'aurai à dire.

**Comment by firm1** [comment]
> un menu déroulant au survol est un enfer pour l'accessibilité.

c'est pour ça qu'un bon compromis serait un menu au survol pour plus de rapidité d'un coté et un menu au clic de l'autre pour l'accessibilité. 
En sachant que l'option par defaut est le clic

Conclusion : tout le monde est content ?

**Comment by Alex-D** [comment]
Un menu au survol est autrement plus complexe à concevoir qu'un menu au clic : code différents, events différents, faut jouer avec des timers réglés au poil...

Je dirais : oui, mais pas maintenant. C'est gadget/confort donc on verra dans une version ultérieure.

**Comment by firm1** [comment]
> Je dirais : oui, mais pas maintenant. C'est gadget/confort donc on verra dans une version ultérieure.

On est d'accord, donc l'idée n'est pas à abandonner car elle me semble bonne/efficace pour une certaine population.

**Comment by coma94** [comment]
Coucou!
Je m'incruste juste pour apporter un peu plus de partisans au survol !
En réalité, le survol ce n'est pas ce qui m'intéresse le plus, mais ce que je trouve peu pratique avec le clic c'est que pour aller à la liste des forums il faut cliquer, _bouger la souris_, cliquer.
 Alors que pour ma part je passe systématiquement par la liste des forums, du coup je trouve le menu au clic chiant.
Voilà, après je suis d'accord sur le "sans urgence", mais c'est une gêne pour moi dans l'etat actuel :)

**Comment by Alex-D** [comment]
- Tu as une interface tactile : le survol ne fonctionne pas.
- Tu navigues à la tabulation : ça ne fonctionne pas (alors que là, avec focus, y a moyen de faire quelque chose : le clic déclenchant un focus sur l'élément).
- Trouves moi un site connu avec un menu déroulant au survol, tu peux chercher : Google, Facebook, Twitter : tout est au clic. Et vu la taille des menus sur ZdS, il vaut mieux.
- Au survol, tu dois bouger la souris, attendre, bouger la souris. Est-ce vraiment pire/mieux ?

A mes yeux c'est un truc complètement secondaire qu'on fera si on a le temps pour les hipsters qui le voudront mais qui du coup se seront habitués à cliquer sur le menu et qui donc ne mettront pas la fonctionnalité. Cf menu au clic sur SdZ v3 : il y avait genre 500 personnes qui avaient activé l'option au clic (c'était survol par défaut).

Note aussi que l'état actuel n'est pas l'état final. Là il y a clic menu principal, clic sous-menu, clic sur le lien. Dans la version finale ça sera simplement clic menu, clic lien. Ca réduit déjà d'un clic, et je trouve ça suffisant personnellement.

**Comment by geoffreyc** [comment]
Je crois que ce qu'il voulait dire, c'est qu'un menu au survole, si tu
cliques sur "forums" ca t'apporte a la liste des forums directement. La il
faut cliquer sur forums, descendre la sourie jusqu'a "tout les forums" pour
enfin être amener a cette page.
Pour moi le premier parents d'un menu devrait être cliquable (entant que
lien).

Comme grand site qui utilise les menus au survole, je sais pas si tu as
deja entendu parler d'amazon, petit site de vente pour "hipsters" ?

2014-04-17 11:15 GMT+01:00 DEMODE Alexandre notifications@github.com:

**Comment by coma94** [comment]
Mon voisin du dessus a bien résumé, et je suis à 100% dnaccoed avec lui sur le premier parent cliquable.
 Je m'étais peut être mal exprimé.

Tes arguments Alex sont tout à fait valides et je n'ai d'ailleurs rien contre le faut que cette issue soit fermée.
C'est simplement mon utilisation à moi qui fait que je préfère le survol. Je n'utilise tout simplement pas le menu déroulant, je suis resté au temps du "clic sur le bouton forum", et c'est tout.
Mais bon, je suis bien conscient que ce n'est pas la navigation "normale".

**Comment by Alex-D** [comment]
Je comprends que ce soit un peu chiant de cliquer deux fois pour accéder à la page. Mais en même temps la page voit son contenu résumé dans ce menu déroulant (à part les derniers posts et autres). Du coup je ne trouve pas ça gênant.

Après on peut faire en sorte que la flèche soit l'élément qui ouvre le menu, mais c'est relou à utiliser...

@geoffreyc : Essayes de naviguer à la tabulation sur Amazon, tu m'en diras des nouvelles ;) Une des règles en accessibilité, c'est que tout contenu doit être accessible au clavier. Une page "callback" n'équivaut pas à son menu déroulant. Un display: none; sur un élément masque le menu, il n'est pas visible par les liseuses des aveugles/mals voyants/... par conséquent, cela signifie qu'un valide peut profiter d'un menu déroulant tandis que les autres non.

**Comment by geoffreyc** [comment]
Ya pas mal de solution pour rendre un menu au survol accessible au clavier,
c'est pas forcement un argument valable.

2014-04-17 11:39 GMT+01:00 DEMODE Alexandre notifications@github.com:

**Comment by geoffreyc** [comment]
example
http://uablogs.missouri.edu/interface/demo/keyboard-accessible2/

2014-04-17 11:45 GMT+01:00 geoffrey compagnon speedking34@gmail.com:

**Comment by SpaceFox** [comment]
> Comme grand site qui utilise les menus au survole, je sais pas si tu as deja
> entendu parler d'amazon, petit site de vente pour "hipsters" ?

L'exemple d'Amazon est intéressant, parce qu'ils ont réussi à éviter :
- Le menu qui s'ouvre alors que tu voulais faire autre chose : le menu
  est positionné de telle manière que tu ne peux pas le survoler par mégarde.
- Le menu qui se ferme alors que tu voulais accéder à un élément : il
  n'y a qu'un seul niveau, et il fait toute la largeur du menu principal,
  donc tu n'as pas à suivre un "tunnel invisible" tordu

Dans ce cas, le menu au survol peut être intéressant, mais c'est délicat à
maîtriser.

**Comment by firm1** [comment]
Entendons nous quand même.

Tout le monde est d'accord pour dire que la navigation au clic est cool. Personne ne refuse l'idée.

Cependant, d'un autre coté, on demande de donner aussi la possibilité d'avoir la navigation au survol pour ceux qui en ont envie (personnellement, ça se résume à un quart d'heure de dev pour moi avec le design temporaire actuel). 
La question donc que j'ai envie de poser, est pourquoi est-ce que ce serait mauvais de proposer une alternative à la navigation au clic ? A part l'argument de la difficulté de dev (argument non recevable cf. @geoffreyc ) je ne vois pas d'inconvénient à le proposer.

Notons que pour ceux qui naviguent généralement sans souris (juste le touchpad de l'ordinateur), cliquer pour ouvrir et pour fermer les menus c'est juste anti-ergonomique.

Donc en quoi proposer les deux solutions serait mauvais ?

**Comment by SpaceFox** [comment]
> Donc en quoi proposer les deux solutions serait mauvais ?

AMHA en rien, tant que le menu _par défaut_ est accessible (au clic, ou au
survol bien gaulé).

**Comment by Alex-D** [comment]
En fait, ça fait 10 messages que tout le monde est d'accord j'ai l'impression. L'idée est de laisser le clic par défaut, et de proposer une option pour le membre qui le souhaite de passer au survol.

J'ai parlé avec des spécialistes en accessibilité (étant en stage dans une boite dont c'est la spécialité) visiblement les deux se valent en accessibilité tant que le menu est accessible à la touche tabulation.

En clair, ça se résume à une question d'ergonomie. Pour le coup, sur les supports tactiles on oubli le survol, tandis qu'avec un touchpad on préférera (selon les dires de firm1) un survol.

Le soucis du survol c'est que si on le fait, il faut bien le faire, et bien le faire c'est pas juste mettre .on('hover', ouvrirMenu()). C'est mettre des délais qui se reset et tout le tralala.

**Je résume, et à mon avis clos ce débat pour l'instant : on implémentera cette option ultérieurement.**

**Comment by firm1** [comment]
Pour info, sur le design actuel, j'ai ré-activer le paramètre qui permet de choisir si on veut un affichage au clic ou au survol. Il est par défaut au clic, mais vous pouvez le modifier ensuite dans [vos paramètres](http://preprod.zestedesavoir.com/membres/parametres/profil), pour ceux qui, comme moi, ressentent le besoin.

Tout le monde a le choix, tout le monde est content.

**Comment by coma94** [comment]
<3
