### ISSUE TITLE
[v12] Les liens vers les anciens exports des tutoriels sont cassés

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3141]
Il n'y a pas de redirection permanente entre les anciens liens des exports et les nouveaux. Par exemple lorsqu'on recherche le tutoriel [arduino en pdf depuis Google](https://www.google.fr/search?client=ubuntu&channel=fs&q=zeste+de+savoir+programmer+en+java&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=f2AzVsWPCayx8wfm666IAw#channel=fs&q=arduino+zeste+de+savoir+pdf) on tombe sur un lien qui nous renvoit une 404.

Les robots de Google risquent de se prendre pas mal de 404 s'ils repassent pas là.

**Comment by artragis** [comment]
si seulement l'ancien module avait été bien codé...

**Comment by artragis** [comment]
apparemment google a géré les choses et a compris que ça avait été déplacé, le lien que propose google est le bon. A fermer?

**Comment by gustavi** [comment]
Chez moi c'est bon aussi.

**Comment by gustavi** [comment]
C'est réglé mais j'aimerai accord de @SpaceFox avant de pouvoir fermer.

**Comment by SpaceFox** [comment]
Je ferme :)
