### ISSUE TITLE
Impossible de commenter si quelqu'un a commenté entre-temps

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3144]
**Scénario**

Je veux commenter un article (ça le fait sans doute avec les tutos, mais j'ai pas eu le cas), mais le temps que je rédige mon pavé, quelqu'un d'autre a posté.

**Comportement attendu** 

Comme sur les forums, j'ai un avertissement, mon message, et les derniers messages postés.

**Comportement observé**

J'ai une fenêtre de rédaction de commentaire sans avertissement ni les derniers messages postés. Mon commentaire est bien dans la fenêtre de rédaction. Si j'essaie de le poster, rien ne se passe (je reviens vers cette même fenêtre). Il faut copier le message, retourner sur les commentaires de l'article et le re-poster à la main.

**Comment by artragis** [comment]
@pierre-24 tu sais comment gérer ça?

**Comment by pierre-24** [comment]
Dans les grandes lignes, oui, m'enfin faudra que je me penche dessus.

**Comment by Eskimon** [comment]
De retour à la normale :)
