### ISSUE TITLE
[V12][Staff] Accès à la version hors-ligne d'un tuto

### ISSUE THREAD

**Issue by Thunderseb** [zestedesavoir/zds-site#3145]
Le lien permettant de voir la version offline d'un tuto ( exemple sur la version en-ligne ici : https://zestedesavoir.com/tutoriels/344/redorer-votre-blason-sur-google-search-bases-de-reputation/ ) retourne une erreur 404. 

Idem si je veux afficher l'historique de validation. 

Je pense que c'est parce que l'auteur a changé le titre du tutoriel (et donc l'url). Quoi qu'il en soit, ce n'est pas normal :p

**Comment by artragis** [comment]
en effet. Le diagnostique semble bon.

**Comment by firm1** [comment]
Je taggue en bloquant vu l'impact.

**Comment by pierre-24** [comment]
L'un de vous deux (vous êtes staff) pourrait vérifier qu'il s'agit bien d'un changement de titre ? Juste pour que je passe pas 20 ans à chercher ;)

**Comment by firm1** [comment]
> L'un de vous deux (vous êtes staff) pourrait vérifier qu'il s'agit bien d'un changement de titre ?

Justement je n'arrive pas à le savoir puisque le lien de l'historique renvoit une 404. Mais je pense effectivement que le titre à changé.

**Comment by pierre-24** [comment]
Un truc me chipote. Si je prend [cet article en bêta](https://beta.zestedesavoir.com/articles/180/sortie-de-python-3-5/), grâce à mes pouvoirs d'admins prêté par Eskimon, je peux accéder à sa version _offline_, et je vois qu'il a été renommé à postériori ([voir là](https://beta.zestedesavoir.com/contenus/180/sortie-de-python-3-5-test/)), donc la procédure que vous me décrivez.

Au delà de ça, est ce que ça le fait sur TOUT les articles/tutos ou juste sur celui là ?!?

(à priori, sur la bêta, j'ai aucun problème à accéder aux version _offline_)

**Comment by Eskimon** [comment]
Je remonte la question de pierre : 

>  est ce que ça le fait sur TOUT les articles/tutos ou juste sur celui là ?!?

**Comment by pierre-24** [comment]
Bon, si j'ai pas plus d'infos, le ticket va trainer là _at vitam eternam_ :-°

(surtout qu'on c'est fait engueuler comme quoi on laissait des tickets bloquant ouverts, toussa ...)

**Comment by Eskimon** [comment]
Engueuler est ptet un peu fort tu crois pas ?

**Comment by pierre-24** [comment]
Ben @GerardPaligot avait pas l'air très content :'(

**Comment by GerardPaligot** [comment]
Les robots n'éprouvent aucune émotion. Du coup, il n'y a pas de souci. ^^

**Comment by Eskimon** [comment]
Pas de nouvelles sur le comportement du problème ?

**Comment by pierre-24** [comment]
_nada_ de mon coté :-°

(et irreproductible par ailleurs)

**Comment by Eskimon** [comment]
Bon au vu des réactions et de l'importance su bug j'enleve le bloquant...

**Comment by gustavi** [comment]
@Thunderseb du nouveau là dessus ? Pour moi ça a été corrigé avec la ZEP-12 mais il me faut confirmation :)

**Comment by Thunderseb** [comment]
Ca semble marcher, je n'ai plus de 404 sur le lien que je donne dans le 1er post.

**Comment by gustavi** [comment]
\o/
