### ISSUE TITLE
Vérifier les requêtes SQL faites par les différentes pages

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3149]
J'ai l'impression que depuis la MEP de la v12, le serveur SQL prends sensiblement plus de requêtes qu'avant. Mais comme ça coïncide avec une période de forte activité, j'ai du mal à dire si c'est normal ou pas.

Il faudrait donc vérifier ça en local, en commençant par ce qui a été modifié dans cette release (donc à priori les pages tuto / article). Il y a peut-être (ou pas) un lien avec #3134.

Aucune urgence, mais si on peut améliorer les performances, tout le monde sera content :)

**Comment by pierre-24** [comment]
C'est probable, même si je me souviens que @artragis avait fait énormément de "magie noire" à ce sujet (historiquement, ces améliorations dans le code provenait d'amélioration qu'il avait fait sur la ZEP-12). À mon avis, on doit avoir des données qu'on oublie de `prefetch()` quelque part, comme d'habitude :)

**Comment by artragis** [comment]
D'après le graphique des slowquery j'ai tendance à penser que la zep-12 en a introduite une. Peux-tu essayer de voir s'il n'y en a pas une qui passe souvent au sujet de : 
- publishablecontent
- contentread
- contentreaction

**Comment by DevHugo** [comment]
Faut prendre en compte la recherche aussi, maintenant que tous est stocké en base de données.
