### ISSUE TITLE
"Aucune conclusion"

### ISSUE THREAD

**Issue by coma94** [zestedesavoir/zds-site#316]
Lorsque l'auteur ne remplit pas la conclusion ou l'intro d'un tuto, il est écrit "Aucune conclusion/introduction.".
Je trouve que ça fait assez artificiel d'ajouter ça à la fin. Étant donné que c'est envisageable de ne pas mettre de conclusion volontairement, ça ne serait pas mieux de ne rien écrire du tout ?

**Comment by SpaceFox** [comment]
Je suis d'accord : si l'auteur décide de ne rien mettre, on ne met rien.

**Comment by firm1** [comment]
Le terme aucune conclusion est juste à titre informatif et c'est la raison pour laquelle on ne le voit que en mode hors ligne.

Lorsque ton tuto est publié, plus rien n'est affiché. En gros, c'est pour faire remarquer à l'auteur qu'il n'a pas encore rempli la case "conclusion" sur une partie/chapitre/tuto.

**Comment by SpaceFox** [comment]
Alors pourquoi pas, à condition que ce soit clair que c'est une indication
qui ne sera pas reportée sur le tuto visible au public :)

**Comment by firm1** [comment]
Une idée de comment préenter ça sur la forme ? Je pense à le mettre en gris pour signifier qu'il ne s'agit nullement de contenu. Est-ce que ça pourrait pallier au problème ?

**Comment by Coy0te** [comment]
Si on veut un peu plus explicite que du gris, on peut placer le texte dans une balise `<abbr>`, qui au survol affiche un texte du genre "Vous n'avez pas écrit de conclusion dans ce chapitre".

_Edit : saloperie de bouton "close and comment"..._

**Comment by cgabard** [comment]
Une couleur différente est déjà un minimum et si genre tu le met entre crochet, moi ça me semblerait assez logique.

**Comment by coma94** [comment]
Je trouverai ça bien aussi une autre couleur + crochets.
Mais.. En l'état, ce tuto est bien en ligne non ? http://preprod.zestedesavoir.com/tutoriels/23/securisez-vos-mots-de-passe-avec-lastpass/
(scrollez à la fin)

**Comment by firm1** [comment]
> Mais.. En l'état, ce tuto est bien en ligne non ? http://preprod.zestedesavoir.com/tutoriels/23/securisez-vos-mots-de-passe-avec-lastpass/
> (scrollez à la fin)

En effet, je viens de fixer le bug.

Et plus généalement, j'ai fixé l'issue aussi en offline. J'affiche carrément ça dans une boite de type info pour faire la différence. [Exemple](http://preprod.zestedesavoir.com/tutoriels/off/23/securisez-vos-mots-de-passe-avec-lastpass/) (scrollez au bout)

Je peux donc fermer l'issue.
