### ISSUE TITLE
Le header du site devrait être fixe pour simplifier la navigation

### ISSUE THREAD

**Issue by charlesfire** [zestedesavoir/zds-site#3160]
Le header du site devrait être fixe pour simplifier la navigation. On pourrait ainsi accédé à la navigation principale du site même en lisant un tutoriel ou en navigant dur le site.
La même idée pourrait être appliqué à la sidebar.

**Comment by SpaceFox** [comment]
Cette idée est à discuter sur les forum, parce qu'il peut y avoir un certain nombre d'arguments contre (la place occupée en hauteur, par exemple). Le cas du mobile est aussi à vérifier.

**Comment by pquentin** [comment]
Il faut aussi faire attention aux liens internes : c'est pas complètement trivial de faire en sorte que les titres (par exemple) soient juste en dessous du header, et pas cachés par le header.

**Comment by charlesfire** [comment]
De mon côté, je suis parvenu à rendre le header fixe sans cacher de partie importante du site. En fait, en restant dans le haut de la page, on ne pouvait pas faire la distinction entre le site normal et le site modifier. Par contre, je ne suis pas parvenu à obtenir le même résultat avec la sidebar. Ayant testé avec plusieurs résolutions, je puis affirmer que les modifications que j'ai testé n'affectaient pas la version mobile du site. Toutefois, n'étant pas encore parvenu à setup le serveur de mon coté pour faire des tests, je n'ai pu tester qu'en modifiant le site déjà rendu dans le navigateur...

Edit : Il faudra donc demander l'avis de la communauté... Dans le cas d'un refus, je ferai un script Tampermonkey pour obtenir le même effet...

**Comment by WinXaito** [comment]
ça rejoint l'issue concernant un bouton "Top" pour mobile qui pourrait être discuter pour version PC.

Concernant un header fixe, je suis moyen pour. Après on peut imaginer en "option" pour chaque utilisateur mais c'est un peu une usine à gaz pour pas grand chose

**Comment by artragis** [comment]
@vhf @sandhose ça fait un an que ça existe, on abandonne?

**Comment by Situphen** [comment]
Si jamais beaucoup de membres réclament la fonctionnalité on peut en faire une option dans les paramètres, sinon il est toujours possible de se faire un script Tampermonkey ou Greasemonkey. Donc je ferme.
