### ISSUE TITLE
Accès rapide vers le sujet de la bêta

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3163]
Aujourd'hui, pour accéder au sujet créé pour la mise en bêta de son contenu, hormis à la mise à jour de la version d'un beta, il faut obligatoirement retrouver le sujet dans la liste des sujets du forum "Contenu en cours de rédaction" ou dans la liste des sujets suivis.

Il pourrait être très pratique d'avoir un accès rapide vers ce sujet directement à partir de la sidebar de son contenu en cours de rédaction.

Je tag facile mais il y a plusieurs règles à respecter :
- Ce lien n'est visible que par les auteurs du contenu, voire aux membres du staff aussi (à discuter).
- Ce lien n'est visible que sur la version hors ligne, voire que sur la version en bêta du tuto (à discuter).
- Il est possible qu'il n'y a pas l'information à partir des templates, il faut donc du dev back pour la récupérer.

**Comment by Vayel** [comment]
En fait, ça existe déjà sur la version bêta du contenu : http://beta.zestedesavoir.com/contenus/beta/822/3163/

Mais il semblerait que le lien ne soit présent que sur les contenus créés après la ZEP-12.

**Comment by GerardPaligot** [comment]
J'ai parfois le lien aussi mais pas tout le temps. Je connais pas trop la règle d'affichage. Je pensais que c'était lors d'une mise en bêta seulement qu'il affichait le lien vers le sujet dans l'encadré orange.

**Comment by Vayel** [comment]
Ah oui, c'est bizarre. La présence du lien n'a pas de rapport avec la date de création ou de mise en bêta (avant ou après la ZEP-12).

**Comment by GerardPaligot** [comment]
Bien, après des recherches dans les sources, le lien devrait être affiché dès lors qu'un sujet existe.

Je passe donc l'issue en BUG.

**Comment by GerardPaligot** [comment]
D'ailleurs, j'enlève le tag facile parce que je ne suis pas certain que ça l'est.

**Comment by pierre-24** [comment]
> J'ai parfois le lien aussi mais pas tout le temps. Je connais pas trop la règle d'affichage. Je pensais que c'était lors d'une mise en bêta seulement qu'il affichait le lien vers le sujet dans l'encadré orange.

En fait, en checkant un peu les sources, il y a un oubli : ce lien ne s'affiche pas dans les parties/chapitres, et c'est à mon avis ça qui doit te perturber. Régler ça est facile, édition de la template correspondante et zou.

Au delà de ça, ledit message ne s'affiche que quand on consulte le contenu sous ça version "bêta", donc à priori pas quand on se promène dans son historique. Si c'est ça que tu souhaite (donc l'avoir "à gauche"), c'est relativement facile aussi, puisque les contenus on un champ vers le sujet bêta en BDD, et encore une fois, il "suffit" d'éditer la template.

Tu peux remettre facile :) (ou j'ai pas compris)

**Comment by GerardPaligot** [comment]
> En fait, en checkant un peu les sources, il y a un oubli : ce lien ne s'affiche pas dans les parties/chapitres, et c'est à mon avis ça qui doit te perturber. Régler ça est facile, édition de la template correspondante et zou.

A la racine de mon contenu, je ne vois pas le lien. Par contre, mon tutoriel est un moyen tuto donc je suis au niveau d'une partie automatiquement (je suppose) mais il m'est arrivé de voir le lien. Donc, je sais pas trop où donner de la tête.

> Au delà de ça, ledit message ne s'affiche que quand on consulte le contenu sous ça version "bêta", donc à priori pas quand on se promène dans son historique. Si c'est ça que tu souhaite (donc l'avoir "à gauche"), c'est relativement facile aussi, puisque les contenus on un champ vers le sujet bêta en BDD, et encore une fois, il "suffit" d'éditer la template.

D'après la 2ème règle à respecter que j'ai marqué dans mon premier message : 

> Ce lien n'est visible que sur la version hors ligne, voire que sur la version en bêta du tuto (à discuter).

Ca me semble pertinent de le mettre uniquement dans la version en bêta. Mais, maintenant que tu re-soulèves la question et que j'y repense, le lien devrait être affiché sur toutes les versions après la mise en bêta (version en bêta comprise) puisque tu places rarement une version en bêta sans y contribuer après.

> Tu peux remettre facile :) (ou j'ai pas compris)

C'est justement parce que je n'y comprends rien que je ne prends pas la responsabilité de placer le tag facile. :)

**Comment by Vayel** [comment]
> Mais, maintenant que tu re-soulèves la question et que j'y repense, le lien devrait être affiché sur toutes les versions après la mise en bêta (version en bêta comprise) puisque tu places rarement une version en bêta sans y contribuer après.

Est-ce que ça ne risque pas de prendre de la place pour rien ? Je veux dire, on peut y accéder assez rapidement en cliquant sur "Voir la version bêta" puis "Voire le sujet".

**Comment by GerardPaligot** [comment]
@Vayel Le sujet de ce ticket est justement que le lien "Voir le sujet" n'existe pas chez moi. :)

**Comment by Vayel** [comment]
Ouep. Mais ce que je veux dire, c'est que je ne suis pas sûr que ce soit utile d'afficher le lien ailleurs que sur la version bêta (affichage actuellement pas toujours fait).

**Comment by GerardPaligot** [comment]
Je ne sais pas pour toi mais pour moi, voici comment je gère mes tutoriels :
1. Je rédige mon tutoriel.
2. Je passe mon tutoriel en bêta.
3. Je modifie le tutoriel avec les retours de la communauté ou les miens.

A l'étape 2, mon tutoriel offline est la version en bêta. Normalement, j'aurais aucun problème pour accéder au sujet puisque le lien devrait m'être proposé (j'utilise le conditionnel partout parce que le bug concerne son absence).

A l'étape 3, mon tutoriel offline est une version plus récente que celle que je propose actuellement en bêta. Le lien ne m'est donc plus proposé alors que je contribue directement à des retours faits sur mon tutoriel en bêta.

Ce n'est pas pratique et je suis obligé de resoumettre mon tutoriel en bêta pour accéder au lien.

**Comment by Vayel** [comment]
> Ce n'est pas pratique et je suis obligé de resoumettre mon tutoriel en bêta pour accéder au lien.

Nop, tu peux cliquer dans la sidebar sur "Voir la version bêta". Tu auras alors le bandeau orange "Cette version est en bêta", suivi normalement du lien vers le sujet correspondant.

**Comment by GerardPaligot** [comment]
Autant te dire que si moi je n'y ai pas pensé alors que je suis au fait de la technique, je vois mal un auteur lambda y penser.

Ceci dit, pour donner des infos complémentaires au bug et en sachant que la toute dernière version de mon contenu est en bêta :
- Si je consulte mon tutoriel par la liste de mes contenus avec une URL du type : https://zestedesavoir.com/contenus/839/developper-et-publier-une-app-android-material-design/, je n'ai pas le lien vers le sujet.
- Si je consulte mon tutoriel par l'URL de la bêta mais sur le même commit que le point précédent, j'ai le lien vers la beta (https://zestedesavoir.com/contenus/beta/839/developper-et-publier-une-app-android-material-design/).
