### ISSUE TITLE
Message de MAJ d'un contenu lors de la 1è publication

### ISSUE THREAD

**Issue by Vayel** [zestedesavoir/zds-site#3165]
- Créer un tutoriel
- Le publier
- Recevoir le message de Clem indiquant que la _mise à jour_ du tutoriel a été publiée

Autrement dit, lors de la première publication, on reçoit [ce message](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/messages/validation_accept_update.md) au lieu de [celui-ci](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/messages/validation_accept_content.md).

**Comment by Emeric54** [comment]
En effet.

Pourtant, [ce](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_validations.py#L406) n'est pas bon ?
