### ISSUE TITLE
L'utilisateur décalé n'est pas dans la doc

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3166]
Suite à une PR de @firm1, nous avons un utilisateur avec des identifiants décalés dans nos fixtures mais il n'est pas [documenté](https://github.com/zestedesavoir/zds-site#données-de-test).

**Comment by pierre-24** [comment]
[Si](https://github.com/zestedesavoir/zds-site/blob/dev/doc/source/back-end/member.rst#les-membres-dans-les-environnement-de-test-et-de-développement), c'est juste un oubli dans ce fichier là (ce fichier m'était complètement sorti de la tête quand je l'avais dit  à @firm1, donc c'est ma faute)

**Comment by GerardPaligot** [comment]
@pierre-24 Je me doutais qu'il devait y avoir de la documentation dans ce coin là mais j'utilise que le README donc j'ai fais un pif quand je me suis authentifié et heureusement, ça suit la même logique que les autres comptes (decal/decal).

**Comment by pierre-24** [comment]
Ah, mais je cherche pas à me justifier, c'est clairement un oubli :)
