### ISSUE TITLE
Page profil: Dernier sujets crées

### ISSUE THREAD

**Issue by coma94** [zestedesavoir/zds-site#317]
Les liens des vers des "Dernier sujets crées" ne pointent pas vers lesdits sujets mais vers la page du profil (cf http://preprod.zestedesavoir.com/membres/voir/bidon).

**Comment by Alex-D** [comment]
Testé et approuvé :)

**Comment by SpaceFox** [comment]
Pourquoi "Closed" ? Tu l'as corrigé ?

2014-04-18 10:46 GMT+02:00 DEMODE Alexandre notifications@github.com:

**Comment by Alex-D** [comment]
Heu... @firm1 viens juste de le corriger en effet. Et j'ai testé, et c'est bien corrigé, donc je ferme. Y a-t-il le moindre soucis avec cette procédure ?

**Comment by firm1** [comment]
> Y a-t-il le moindre soucis avec cette procédure ?

Nope, merci.

**Comment by SpaceFox** [comment]
> Y a-t-il le moindre soucis avec cette procédure ?

Non, mais prévenez de manière claire dans le ticket que ça a été corrigé.
Là j'ai cru que tu disais que tu confirmais le bug, et que tu t'étais
planté de bouton (y'en a un "commenter et fermer").

**Comment by Alex-D** [comment]
Quoi de plus claire que la référence directe vers le commit de bugfix automatiquement ajoutée par Github ? Enfin bref, c'est corrigé \o/

EDIT : Un robot viens de m'expliquer que ceux qui suivent via les mails n'ont pas les références de commit, d'où le quiproquo. Je m'en excuse :)

**Comment by SpaceFox** [comment]
> Quoi de plus claire que la référence directe vers le commit de bugfix
> automatiquement ajoutée par Github ?

C'est pas dans les mails, donc invisible sans aller sur le site :S

Le 18 avril 2014 10:52, DEMODE Alexandre notifications@github.com a écrit
:

**Comment by Alex-D** [comment]
En effet... tout comme les éditions du coup tu n'as pas vu mon petit
message d'amour =D
