### ISSUE TITLE
La prévisualisation n'affiche pas les formules

### ISSUE THREAD

**Issue by Deuchnord** [zestedesavoir/zds-site#3170]
Hello,

Les formules mathématiques ne s'affichent pas lors de la rédaction ou de l'édition d'un message sur les forums et les MP.

En effet, lorsque j'écris une formule mathématique et que je prévisualise, j'obtiens ça :
![Capture du problème](https://cloud.githubusercontent.com/assets/7600265/11020763/80c9ac3a-862a-11e5-9fe2-af074d5e1f6f.png)

Il serait pratique que le résultat de ce code soit affiché, c'est à dire ici ![Résultat attendu : racine carrée de 1764 égale 42](https://cloud.githubusercontent.com/assets/7600265/11020771/e1fd3080-862a-11e5-9713-cb1534cc3a42.gif), ne serait-ce que pour vérifier que l'on obtient bien le résultat attendu (en particulier qu'il n'y a pas d'erreur de syntaxe).

**Comment by Situphen** [comment]
Il faut changer [cette ligne-ci](https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/ajax-actions.js#L306).

Actuellement, `$$\sqrt{1764} = 42$$` est transformé par le serveur en :

```
<div class="mathjax-wrapper"><mathjax>$$\sqrt{1764} = 42$$</mathjax></div>
```

tandis que `$\sqrt{1764} = 42$` est transformé en :

```
<span>$\sqrt{1764} = 42$</span>
```

Cela est problématique car la condition `$(data).find("mathjax").length > 0` ne prend pas en compte les formules _inlines_ `$`. Elle devrait être remplacé par `$(data).find("$").length > 0`.

[Pour info, cette condition sert à ne pas lancer MathJax lors de la prévisualisation à tous les coups mais que quand il y en a besoin car ça demande pas mal de calcul aux ordinateurs.]
