### ISSUE TITLE
Les derniers sujets suivis cette semaine ne le sont pas forcément.

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3172]
A l'heure ou je poste cette issue, on est lundi et dans mes sujets suivis j'ai des sujets suivis de : 
- aujourd'hui : normal
- hier (dimanche) : normal
- cette semaine : il y'a un problème de vocable ici. Car "cette semaine" à commencée en fait aujourd'hui. Le code lui veut plutôt parler des "7 derniers jours".

Donc j'ignore la bonne façon de faire ici ? renommer le "cette semaine" ou modifier le comportement pour n'avoir que ce qui s'est passé cette semaine ?

Mais dans tout les cas l'affichage ne correspond pas à la réalité. Au vu du code, le problème est aussi présent pour "Ce mois" qui devrait plutôt s'appeler "Les 30 derniers jours" pour être cohérent avec la réalité.

**Comment by pierre-24** [comment]
Le renommage me semble moins casse tête, d'autant que je vois pas vraiment l'intérêt de pas avoir sa liste du mois dernier qui disparait le premier :)

**Comment by SpaceFox** [comment]
+1 pour le renommage. Du coup ça devient normalement « facile ».

**Comment by gustavi** [comment]
Et pour « Cette année » je mets quoi ? « Les 365 derniers jours » c'est pas génial ... (et en plus c'est 360)

**Comment by SpaceFox** [comment]
Y'a la place pour des phrases comme « 1 semaine glissante », « 1 mois
glissant », « 1 an glissant » ?

2015-11-24 11:32 GMT+01:00 Laville Augustin notifications@github.com:

**Comment by gustavi** [comment]
Oui mais c'est pas génial je trouve. Après c'est subjectif !

Le code est comme ça : 

``` python
const = {1: "Aujourd'hui", 2: "Hier", 3: "Cette semaine", 4: "Ce mois-ci", 5: "Cette année"}
```

**Comment by SpaceFox** [comment]
Ou alors on remplace le dernier item par « plus ancien ».

Le 24 novembre 2015 11:38, Laville Augustin notifications@github.com a
écrit :
