### ISSUE TITLE
[v12] : le titre d'un tutoriel en zone validation ne semble pas versionné

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3174]
Scénario : 
- Je crée un tutoriel avec pour titre "ok"
- Je l'envoi en validation le titre du tutoriel dans la zone validation est bien "ok"
- Je modifie le brouillon de mon tutoriel en changeant le titre par "bonjour"
- Je vais en zone validation le titre a changé dans la liste il s'appelle maintenant "bonjour"
- mais quand je clique sur ledit tutoriel en validation il a bien le titre "ok"

C'est perturbant pour le valido que je suis :)

**Comment by pierre-24** [comment]
En effet. C'est probablement parce qu'on charge la version brouillon et pas la version en validation.

**Comment by pierre-24** [comment]
Ah, fait ch***, c'est encore plus con que ça : on se sert juste de la BDD pour afficher le titre (en mode "pas besoin de se taper la lecture du manifest pour ça" ... Ben si).
