### ISSUE TITLE
La recherche indexe aucun nouveau contenu

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#3175]
Bonjour,

On peut voir que la recherche n'indexe pas les contenus depuis la zep-12. En effet, les articles "La ligne éditoriale officielle de Zeste de Savoir" et "Les injections SQL" ne sont pas trouvable depuis le moteur de recherche.

Nous pouvons nous demander, si la tache cron a été mise à jours car aucune erreur n'est remontée.

**Comment by firm1** [comment]
Je rajoute le tag infra puisque ça marchait bien en beta.

**Comment by DevHugo** [comment]
Je pense qu'on a oublié de mettre à jours la tache cron car les autres articles/tutoriels sont disponible.

**Comment by Eskimon** [comment]
Je viens de vérifier, en tout cas solr est bien en marche. Je vérifie la tache CRON...

**Comment by DevHugo** [comment]
Copie la ici, comme ça on vérifie

**Comment by Eskimon** [comment]
```
zds@vps192382:~$ cat /etc/systemd/system/zds-index-solr.timer
[Unit]
Description=Reindex SOLR Timer

[Timer]
OnCalendar=*:30:00
Persistent=true

[Install]
WantedBy=timers.target
zds@vps192382:~$ cat /etc/systemd/system/zds-index-solr.service 
[Unit]
Description=Reindex SOLR Service

[Service]
Type=oneshot
User=zds
Group=zds
ExecStart=/opt/zdsenv/bin/python /opt/zdsenv/ZesteDeSavoir/manage.py index_content --only-flagged
ExecStart=/opt/zdsenv/bin/python /opt/zdsenv/ZesteDeSavoir/manage.py update_index
```

**Comment by Eskimon** [comment]
Bon je prend la responsabilité de ma bouletitude. L'ensemble des choses pour le cron était bien la, mais le timer n'avait pas été lancé... Je viens de le lancer, on vérifie dans un peu plus de 30 minutes si tout est good...

**Comment by DevHugo** [comment]
Ok. Merci Eskimon

**Comment by DevHugo** [comment]
On est bon, je ferme !
