### ISSUE TITLE
[Forum] Champ de texte déplacé

### ISSUE THREAD

**Issue by coma94** [zestedesavoir/zds-site#318]
Le champ texte est mal placé, que ça soit en répondant à un sujet ou en répondant. Je sais que c'est le design temporaire, mais bon, je poste quand même.
Firefox 28 sous windows 7. (J'ai essayé sous chrome et pas de problème).

![nouv-sujet](https://cloud.githubusercontent.com/assets/627451/2740509/9af5eeb4-c6d4-11e3-8876-2bcb2242c40d.png)
![repondre](https://cloud.githubusercontent.com/assets/627451/2740510/9af902ac-c6d4-11e3-8ad0-5d74e0c77bab.png)

**Comment by coma94** [comment]
Toujours présent chez moi.

**Comment by firm1** [comment]
C'est définitivement fixé.

Merci, je ferme.
