### ISSUE TITLE
Une erreur (d'encodage ?) empêche d'utiliser l'API sur la bêta

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#3190]
Lorsqu'on essaye de s'autentifier via l'API, c'est impossible, on obtient une erreur 500 :  

```
Stacktrace (most recent call last):

  File "django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "braces/views/_forms.py", line 22, in dispatch
    return super(CsrfExemptMixin, self).dispatch(*args, **kwargs)
  File "django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "oauth2_provider/views/base.py", line 170, in post
    url, headers, body, status = self.create_token_response(request)
  File "oauth2_provider/views/mixins.py", line 124, in create_token_response
    return core.create_token_response(request)
  File "oauth2_provider/oauth2_backends.py", line 106, in create_token_response
    headers)
  File "oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "oauthlib/oauth2/rfc6749/endpoints/token.py", line 100, in create_token_response
    request, self.default_token_type)
  File "oauthlib/oauth2/rfc6749/grant_types/resource_owner_password_credentials.py", line 101, in create_token_response
    if not self.request_validator.authenticate_client(request):
  File "oauth2_provider/oauth2_validators.py", line 166, in authenticate_client
    authenticated = self._authenticate_basic_auth(request)
  File "oauth2_provider/oauth2_validators.py", line 58, in _authenticate_basic_auth
    encoding = request.encoding or 'utf-8'
  File "oauthlib/common.py", line 412, in __getattr__
    raise AttributeError(name)
```

L'erreur ressemble à ce qui est reporté là : https://github.com/idan/oauthlib/issues/363 ... Et semble avoir été corrigée. Reste à savoir si on utilise la dernière version de oauthlib.

**Comment by pierre-24** [comment]
(chez sentry, [c'est par là](http://sentry.sandhose.fr/zeste-de-savoir/backend-1/group/280/))

**Comment by pierre-24** [comment]
[Ce commentaire](https://github.com/idan/oauthlib/issues/363#issuecomment-125600336) dit explicitement qu'il "suffit" de passer à django-oauth-toolkit 0.9.0 [là](https://github.com/zestedesavoir/zds-site/blob/dev/requirements.txt#L29). Ça vaut un bêtafix ?

**Comment by GerardPaligot** [comment]
C'est bizarre. Pourquoi en local ça fonctionne ? Et il me semble que ça fonctionne chez certaines personnes (ping @Eskimon).

**Comment by pierre-24** [comment]
En local, ça fonctionne nickel, peut-être que c'est lié à postman ?

Tient, au fait, Sentry nous dit [que tu as déjà eu l'erreur](http://sentry.sandhose.fr/zeste-de-savoir/backend-1/group/280/events/8282/)  :)

**Comment by GerardPaligot** [comment]
Tout à fait mais je pensais que ça venait de moi parce que Eskimon parvenait à se connecter.

**Comment by pierre-24** [comment]
Ah. Faut voir si @Eskimon utilise pas autre chose que postman :o

**Comment by Eskimon** [comment]
J'avais juste fait le test de la doc' pour récupérer mes tokens mais c'est tout. http://zds-site.readthedocs.org/fr/latest/api.html?highlight=api#recuperer-les-tokens-d-authentification

**Comment by GerardPaligot** [comment]
@pierre-24 Il utilise curl.

**Comment by Eskimon** [comment]
si l'un d'entres vous passe me voir sur IRC on pourra essayer avec la beta pour mettre à jour le package oauth et voir si ca change quoi que ce soit :)

**Comment by pierre-24** [comment]
Résultat des tests : mettre à jour la librairie, ça fonctionne très bien pour moi. Par contre, du coup, ça file une 500 au reste du site :'(

(erreur qui me semble bizarement être celle-ci : http://sentry.sandhose.fr/zeste-de-savoir/backend-1/group/282/ )

**Comment by GerardPaligot** [comment]
C'est bizarre. Je ne peux pas tester au boulot (IP toussa toussa) mais avant d'aller me coucher hier soir, je n'avais aucune erreur 500 (testé sur /api/mps/ et /api/mps/:id/).

PS : On retrouve quelque part les identifiants de ce Sentry ?

**Comment by GerardPaligot** [comment]
Je passe quand même cette issue en bloquante. Il faut éclaircir ce point sinon pas de release.

**Comment by GerardPaligot** [comment]
J'aurais tendance à tag "infra" ici. Je test à longueur de temps ZMessenger en local et je n'ai jamais aucun problème. 0 erreur 500 depuis que je développe l'application.

Le bug semble donc survenir que sur le serveur de preprod.

**Comment by pierre-24** [comment]
Pareil, jamais de soucis en local. Ceci dit, on ne communique pas exactement pareil avec nos infrastructure en local et "dans la vraie vie".

**Comment by GerardPaligot** [comment]
> Ceci dit, on ne communique pas exactement pareil avec nos infrastructure en local et "dans la vraie vie".

Qu'est-ce que tu veux dire ?

**Comment by pierre-24** [comment]
Ben par exemple, perso, je m'amuse pas à mette un pare-feu/authentification avec `.htaccess` entre mon pc et mon GSM pour tester, alors que c'est le cas sur la bêta. De plus, autant je contrôle ce qui se passe sur mon pc (au niveau des `locale` par exemple), autant je sais pas ce qui se fait sur la bêta/prod'. Pire, je fais tellement de QA qu'il suffit que j'aie "installé un truc" via `pip` pour ladite QA et que je l'aie pas enelvée, donc je suis pas iso-prod, toussa ...

(ceci n'est absolument pas une critique : je dis juste que perso, j'ai pas de serveur sur internet pour tester et que tout ce fait en local, d'où un biais)

**Comment by GerardPaligot** [comment]
Non, tu confirmes simplement que c'est très certainement un problème d'infra.

**Comment by pquentin** [comment]
(pip-sync pour l'iso-prod niveau pip)

**Comment by GerardPaligot** [comment]
@gustavi Je te vois super chaud sur le projet pour l'instant alors si tu as une idée à propos de cette issue, ça serait génial. Elle est bloquante pour la release en cours.

**Comment by gustavi** [comment]
Je regarde ça dans le WE !

**Comment by gustavi** [comment]
Alors j'ai plusieurs questions : 
- Est-ce qu'on a un TU là dessus ? Si ce n'est pas le cas il en faut absolument un, on va déjà voir s'il passe et sur quels env (local, CI et preprod).
- Est-ce que les tests actuels passent en preprod ?
- Est-ce qu'on peut déployer une instance avec la dernière version en preprod ?

**Comment by Eskimon** [comment]
J'ai mis a jour le package oauth hier en version 0.9 sur la preprod et apparemment tout se passe bien... Bref, on dirait bien qu'une simple PR pour la version fera le boulot

**Comment by GerardPaligot** [comment]
@gustavi L'authentification est faite par une librairie externe. Si on s'amuse à faire les TUs des autres, ça va le faire moyen.

@Eskimon Tu avais pas déjà fais cette manipulation ?

**Comment by pquentin** [comment]
@GerardPaligot du coup c'est pas un TU mais un test d'intégration pour vérifier que ZdS utilise la librairie correctement. C'est pas "faire les TUs des autres".

**Comment by gustavi** [comment]
@GerardPaligot je parlais juste d'avoir un TU pour voir dans les tests si ça passe. Un simple test tout bidon histoire qu'on se rende compte quand on casse tout ;)

Je confirme que sur la beta tout va bien pas une 500 depuis que @Eskimon a fait la màj.

**Comment by Eskimon** [comment]
@GerardPaligot si je l'avais faite, mais a la même époque on avait aussi l'auto complétion et d'autres trucs bizarres qui étaient passé... Du coup je sais pas trop quoi penser...

Qqun a tester la reproducabilite du bug sous jacent ou pas ?

**Comment by GerardPaligot** [comment]
> Qqun a tester la reproducabilite du bug sous jacent ou pas ?

Bug pas reproductible en local.

**Comment by Eskimon** [comment]
En preprod je voulais dire

**Comment by gustavi** [comment]
Corrigé dans #3236.
