### ISSUE TITLE
[v14] Autocompletion des membres dans les choux

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#3192]
Sur la v14 l'autocompletion des membres est complètement dans les choux, il n'est plus possible de sélectionner un pseudo et c'est très gênant. J'ai testé ca sur la création de MP ou l'ajout d'un auteur à un tuto et on a les mêmes symptômes. Ce problème n'existe pas sur la prod'.

**Comment by pierre-24** [comment]
@GerardPaligot : l'API des membres ?

**Comment by artragis** [comment]
Info technique : la requête ajax se prend une 403.

**Comment by Eskimon** [comment]
> Info technique : la requête ajax se prend une 403.

Probablement chez toi car l'API est bloqué de ton côté. Par contre chez moi ca marche pas quand même.

**Comment by Eskimon** [comment]
Normalement l'API des membres est accessible par tous tout le temps sur la beta (et l'API des MP soumise à filtre IP, et le reste du site soumis au htpass)

**Comment by Eskimon** [comment]
Bon apparemment c'est possible que ce soit le front qui soit dans les choux vu qu'on a plus d'icones pour l'éditeur de texte... je vais refaire la release en logguant bien tout je pense...

**Comment by Eskimon** [comment]
RAS sur le déploiement, je vois pas d'où vient le problème...

**Comment by GerardPaligot** [comment]
On sait me rediriger vers la requête front qui est faite sur l'API ?

**Comment by Situphen** [comment]
Je viens de tester sur la béta et en effet l’auto-complétion est morte, mais ça a l'air d'être l'affichage et non pas les requêtes (qui ont un code 200). Je ne sais pas pourquoi car normalement ni le code JS ni les vues ont été changées. Par ailleurs, les smileys aussi ne s'affichent plus alors qu'ils sont encodés en base64 dans le code (S)CSS. Bizarre bizarre cette histoire !

Pour information, le fichier JS gérant l'auto-complétion est [ici](https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/autocompletion.js).

**Comment by GerardPaligot** [comment]
Bon, si le code retourné est un code 200. Inutile pour moi de regarder plus loin. :)

**Comment by GerardPaligot** [comment]
J'ai testé l'autocompletion et on peut clairement se dire que ce n'est pas un problème d'API. La recherche est faite et renvoyée au front mais elle n'est pas bien gérée. On a un gros bug d'affichage. J'ajoute le tag front.

**Comment by artragis** [comment]
Je pense que c'est la génération du front qui a foiré.

**Comment by pierre-24** [comment]
Qu'est ce qui te fait dire ça ?

**Comment by artragis** [comment]
l'éditeur de texte sans image. et deux trois trucs qui ne fonctionnent 
plus dans le js alors que personne n'y a touché.

**Comment by Eskimon** [comment]
Je déploie une RC3, on verra bien si ca corrige le souci

**Comment by Eskimon** [comment]
Bon le front semble un peu mieux marcher, mais l'auto-complétion n'est toujours pas revenu comme elle le devrait.

**Comment by GerardPaligot** [comment]
0 intervention de développeurs fronts. Pour avancer, ça me semble nécessaire.

ping @sandhose et @Situphen (@Alex-D :-°)

**Comment by Fulbert** [comment]
Chez moi les noms s'affichent mais ils ne sont pas cliquable. Les requêtes fonctionnent bien sur des URL vers https://beta.zestedesavoir.com/api/membres/?search=eski (200).

**Comment by sandhose** [comment]
note: si on me mentionne pas, je risque de pas voir ce genre de tickets

Donc, le problème vient du faire que la réponse côté serveur d'un coup s'est transformée de `pk` en `id`

Forcément, comme c'est ce champ qui était [utilisé pour la sélection](https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/autocompletion.js#L228), ça marche moins bien .-.

PR ouverte: #3210
