### ISSUE TITLE
Problème de style avec les sommaires des moyens tutoriels

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3194]
Sur mon moyen tutoriel, on peut constater un rendu différent entre la version hors ligne et publié.

Publié
<img width="530" alt="capture d ecran 2015-11-15 a 00 16 26" src="https://cloud.githubusercontent.com/assets/1913901/11166316/9a2e1db0-8b2e-11e5-9d7e-c6ac6757a973.png">

Brouillon
<img width="489" alt="capture d ecran 2015-11-15 a 00 20 03" src="https://cloud.githubusercontent.com/assets/1913901/11166320/a5a93be8-8b2e-11e5-92a3-169ae88b19ea.png">

**Comment by pierre-24** [comment]
Ah, je me disais aussi qu'il y avait un problème :o

**Comment by pierre-24** [comment]
Ok :)
