### ISSUE TITLE
Rendre le message d'explication pour les archives plus clair

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#3196]
Il a été noté sur le forum que lors de l'import des tutoriels (archives) le message `Pour importer des images, veuillez spécifier la seconde archive. Les motifs ![légende](archive:chemin/vers/image.extension), référant aux images stockées dans l'archive, seront remplacés par les URLs générées par le site.` n'était pas suffisamment clair pour les personnes peu habituées.

Il serait sûrement adéquat de trouver une formule plus fluide et moins ambiguë. En effet la personne avait compris que `archive:chemin/vers/image.extension` signifiait simplement "chemin/vers/image.extension se trouve dans l'archive" et pas "il faut faire précéder le code de `archive:`".

**Comment by pierre-24** [comment]
Toutafé. Ne jamais me laisser rédiger un message  :p
