### ISSUE TITLE
Créer un bot pour faire des MP aux membres

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#320]
L’intérêt du bot étant  :
- d'envoyer un message de bienvenue à l'inscription
- d'envoyer un MP lors d'une sanction
- d'envoyer un MP lorsqu'une alerte a été traitée par un Modo
- etc.

**Comment by coma94** [comment]
Et souhaiter les anniversaires ? :-°

**Comment by Alex-D** [comment]
Il faudrait voir ça comme un service je pense. Ainsi via un singleton, n'importe où on pourrait envoyer un MP via le triplet id_membre, titre, message.

N'est-ce pas là le moment (encore une fois) de faire naître une mascotte (clem' ?) pour ce type de message ?

**Comment by Coy0te** [comment]
Et de prévoir des MPs auxquels il est impossible de répondre, si ce n'est pas déjà le cas.

**Comment by firm1** [comment]
Le service d'envoi de message privé a été mis en place.

La signature du service est : `send_mp(author, users, title, subtitle, text, send_by_mail=True)`, la dernière option permet de désigner si un mail doit être envoyé à l'utilisateur. Il est positionné à True par défaut.

Je ferme.
