### ISSUE TITLE
Rediriger directement vers le brouillon à partir de la version publiée d'un contenu

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3200]
Salut ~~les gars~~,

J'aurais aimé connaitre la différence entre la version hors ligne et brouillon d'un contenu ?

Voilà, c'est tout parce que je ne comprends pas bien.

ping @artragis @pierre-24

**Comment by artragis** [comment]
bah en fait tu prends la version hors-ligne, tu l'appelles version
brouillon et paf, tu as la version brouillon.
C'est un truc qui a toujours existé, c'est pas unifié et c'est dommage mais
j'avoue qu'on y a pas pensé sur le coup.

Le 17 novembre 2015 10:51, Gérard Paligot notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
Malheureusement non, sur une version publiée, si je vais sur la version hors ligne (à partir des raccourcis dans la side bar), je n'arrive pas sur la version brouillon. Pour y aller, je dois encore utiliser un raccourci dans la side bar pour m'y rendre.

Ce process n'a jamais existé avant à ma connaissance.

**Comment by pierre-24** [comment]
Ben le coup, c'est que la version "brouillon", c'est la dernière en date, alors que la version "hors-ligne", c'est la même que la publiée (comprendre le même `sha`) mais dans l'interface d'édition.

**Comment by artragis** [comment]
c'est si compliqué que ça? genre pas du tout intuitif là oO

Le 17 novembre 2015 11:36, Pierre Beaujean notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
@pierre-24 Ok, je comprends la différence. Par contre, @artragis résume bien la situation. C'est juste contre intuitif. Moi je m'en fous de la version hors ligne de la version publiée. Je veux direct arrivé à mon brouillon.

**Comment by pierre-24** [comment]
Ça semble logique, je crois qu'on a gardé ça par rétro-compatibilité :)

**Comment by GerardPaligot** [comment]
Bien, je renomme l'issue et je tag large. J'ai presque été tenté de placer le tag "Facile" mais je ne connais pas assez le module des tutos pour savoir si c'est réellement simple.

**Comment by Karnaj** [comment]
Dans la version actuelle, la redirection vers la version hors-ligne se fait également à partir des parties et des chapitres, or il peut y avoir eu un remaniement dans la version brouillon (parties/chapitres supprimés). Il se passe quoi dans ces cas-là ? Je pense qu’il faudrait avoir une redirection vers le brouillon du tutoriel et non vers celui du chapitre et ce même si on est dans un chapitre. Et il faudrait aussi rajouter ce comportement pour n’importe quelle version du tutoriel (pour le moment, dans une version non publiée, on n’a le lien vers le brouillon que dans la page principale du tutoriel et pas quand on est dans un chapitre ou une partie).

**Comment by pierre-24** [comment]
Et voilà :)
