### ISSUE TITLE
Alertes «Gradient has outdated direction syntax » lors du build front

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3208]
Voici les alertes en question : 

```
autoprefixer: /home/augustin/.virtualenvs/zds/zds-site/assets/scss/main.css:1492:7: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".
autoprefixer: /home/augustin/.virtualenvs/zds/zds-site/assets/scss/main.css:1743:5: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".
autoprefixer: /home/augustin/.virtualenvs/zds/zds-site/assets/scss/main.css:2225:7: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".
autoprefixer: /home/augustin/.virtualenvs/zds/zds-site/assets/scss/main.css:2409:9: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".
autoprefixer: /home/augustin/.virtualenvs/zds/zds-site/assets/scss/main.css:3126:7: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".
```

Les logs complets ici : http://paste.awesom.eu/YCHX

Les version de node et npm : 

```
 npm -v && node -v
3.4.1
v5.1.0
```

**Comment by Situphen** [comment]
C'est connu par moi et @sandhose depuis quelques temps déjà. Ça doit être une syntaxe CSS qui a changé. Les navigateurs supportent toujours notre code actuel et je n'ai pas réussi à trouver où changer quoi.

**Comment by gustavi** [comment]
C'est dans les 'grandient' niveau background et autre. Je m'en serai bien occupé mais j'ai peur de tout casse.

Autre chose, vous avez une solution pour que gulp affiche la bonne ligne du bon fichier pour les erreurs comme cela ?

**Comment by Alex-D** [comment]
Tu peux chercher comme un bourrin dans tous les fichiers SCSS et remplacer tout les "to left" par des "right" et ça devrait rien changer visuellement mais tu devrais avoir un code plus propre :)
