### ISSUE TITLE
[Forum] Anti-spam sur l'édition d'un post

### ISSUE THREAD

**Issue by coma94** [zestedesavoir/zds-site#321]
La protection anti-spam de 15 minutes empêche également d'éditer notre dernier post pendant 15 minutes.

**Comment by firm1** [comment]
J'ai vu [ou se trouve le bug](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/forum/forms.py#L93). Mais ce n'est pas le genre de chose que je peux corriger en ligne comme ça sans tester.

Je m'en occuperai quand je serai sur un pc de dev, si quelqu'un ne l'a pas fait d'ici là.

**Comment by firm1** [comment]
elle est fixée, donc je ferme
