### ISSUE TITLE
Bug - Impossible de dérouler les menus au survol

### ISSUE THREAD

**Issue by SuperFola** [zestedesavoir/zds-site#3212]
| Q | R |
| --- | --- |
| Correction de bugs ? | oui |
| Nouvelle Fonctionnalité ? | non |

Il n'est pas possible de dérouler les menus de ZdS au survol de la souris, même si l'option "Dérouler les menus au survol" est cochée sur votre profil (https://zestedesavoir.com/membres/parametres/profil/).

Ca à l'air d'être en lien avec [ceci](https://github.com/zestedesavoir/zds-site/blob/e382d5dc04f5b252f3d377da75abb57a180acb57/assets/scss/components/_accessibility-bar.scss) et [ceci aussi](https://github.com/zestedesavoir/zds-site/blob/e382d5dc04f5b252f3d377da75abb57a180acb57/assets/js/dropdown-menu.js).

J'ai pu remarquer que les valeurs de `self.fields` (surtout `hover_or_click` en fait) dans le `UserProfile` ne sont jamais utilisées.

Je suis déjà dessus ^^

**Comment by GerardPaligot** [comment]
Une issue est déjà créée https://github.com/zestedesavoir/zds-site/issues/661
