### ISSUE TITLE
Couleur du bouton de recherche sur la home

### ISSUE THREAD

**Issue by Fumble** [zestedesavoir/zds-site#3213]
Ce vert fait un peu tâche quand on survole le bouton de recherche sur la page d'accueil:
![recherche](https://cloud.githubusercontent.com/assets/634461/11459974/8a5bf89c-96e3-11e5-89e2-b144b35b7649.png)

**Comment by GerardPaligot** [comment]
Il y a pas un sujet sur les forums pour discuter des détails comme ça ? C'est plutôt avec la communauté qu'il faut voir ça.

PS : Je me rappel très bien @Situphen qui venait me voir à ce sujet et lui dire que c'était dégeux le vert. Il l'avait changé, puis il l'a remit. Allez savoir pourquoi.

**Comment by Emeric54** [comment]
Le sujet est [ici](https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/).

**Comment by Fumble** [comment]
Hmm... Je pensais que c'était un bug dans une classe CSS et non une couleur mise en connaissance de cause.

Sinon, je dois t'avouer que j'ai plus tendance à passer directement par GH que par le forum des bugs.

@Emeric54 : merci je vais mettre ma remarque dessus.

**Comment by Situphen** [comment]
Je ne sais pas si c'est vraiment un détail. C'est très moche et en page d'accueil.

> PS : Je me rappel très bien @Situphen qui venait me voir à ce sujet et lui dire que c'était dégeux le vert. Il l'avait changé, puis il l'a remit. Allez savoir pourquoi.

Oo ?? Euh, si tu as des logs je veux bien ! :) Si j'ai dis ça, que Toutatis crache sa colère sur moi ! Je ne pense pas avoir mis du cette couleur sur ce bouton en page d'accueil. Et je suis d'accord qu'ici c'est moche. Après, je n'exclus pas avoir milité pour ce vert autre-part mais je pense que c'était pour autre chose. ;)

**Comment by sandhose** [comment]
C'est en fait un souci de priorité de propriétés CSS, puisque le bouton est censé [être gris](https://github.com/zestedesavoir/zds-site/blob/dev/assets/scss/pages/_home.scss#L256). Suffit de rajouter un `!important`, et c'est bon (dans l'absolu j'aime pas les `!important`, mais en l'occurence, la propriété qui override a vraiment trop de sélecteurs, et il faudrait rajouter un truc type `:not(.link)` ou `:not([disabled])` pour que ce sélecteur reprenne la priorité...)

**Comment by SpaceFox** [comment]
Corrigé et mergé.
