### ISSUE TITLE
Impossible de faire une demande de màj de validation quand on ajoute un auteur

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3228]
Pour reproduire : 
- Créer un tuto vide et le publier
- Ajouter un auteur

À partir de là l'auteur n’apparaît pas sur la version publiée (ce qui est normal) mais il est impossible de faire une demande de validation.

La comportement doit être le même avec les articles.

**Comment by artragis** [comment]
heu c'était un bug qui venait sûrement de la PR que tu as mergé fallait pas la merger (sauf si le bug existe en prod)

**Comment by gustavi** [comment]
Il est impossible de tester ça en prod et je ne vois pas comment la PR que j'ai mergée a pu modifier ça (du moins après une relecture du code c'est correct et ça ne touche pas à la validation).

**Comment by GerardPaligot** [comment]
On peut tester le process en bêta ? Si c'est reproductible, pas de problème. Sinon, @gustavi faut y aller molo dans les merges.

**Comment by artragis** [comment]
je pense que c'est le merge qui l'a ajouté, faut voir en prod/beta ce qu'il se passe mais on est typiquement dans un pb d'intégration et comme j'ai modifié l'intégration dans ma PR c'est pas impossible.

**Comment by gustavi** [comment]
Je teste ça de suite, faut juste me filer les droits sur la preprod.

**Comment by GerardPaligot** [comment]
Les effectifs sont réduits dans cette période de fin d'année. @artragis comme tu sembles présent, tu serais testé rapidement grâce à tes droits de staff ?

**Comment by artragis** [comment]
faudrait qu'on me donne le scénario complet et qu'on me dise surquel 
serveur je dois le faire.

**Comment by artragis** [comment]
j'ai pas les droits de staff sur la béta

**Comment by Eskimon** [comment]
> j'ai pas les droits de staff sur la béta

Maintenant oui :)

**Comment by artragis** [comment]
>  À partir de là l'auteur n’apparaît pas sur la version publiée (ce qui est normal) mais il est impossible de faire une demande de validation.

je viens de comprendre...
not a bug, a feature : s'il n'y a pas eu de changement, pourquoi devrait-on valider quelque chose?

**Comment by gustavi** [comment]
Parce que si tu veux ajouter un auteur (par exemple parce que c'est un tuto que tu as importé d'un autre site et qu'un des auteurs ne s'est inscrit qu'après la publication) tu peux le faire mais ça n’apparait pas en prod. Une modification de contenu est nécessaire.

**Comment by artragis** [comment]
oui, mais le cas arrive-t-il souvent?

**Comment by Eskimon** [comment]
Yep je pense un peu comme artragis : Ce cas va se reproduire tellement rarement face au "j'ajoute un auteur qui va faire des modifs"... J'ai bien peur que ce ticket soit mort-né...

**Comment by Vanadiae** [comment]
Ping @artragis : ticket je cite "mort-né"
