### ISSUE TITLE
Documenter Sentry

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3229]
On a aucune documentation là dessus, ça serait bien d'en avoir.

**Comment by motet-a** [comment]
Après c’est quand-même un outil interne dont les données ne peuvent pas être dévoilées au public. Et Sentry est mis à jour fréquemment. Donc si on documente l’interface de Sentry telle qu’elle est actuellement, ça risque de ne pas intéresser grand-monde et de devenir obsolète rapidement.

**Comment by artragis** [comment]
@sandhose comme sentry est propre à notre installation de prod, je suis favorable à clore ce ticket.
