### ISSUE TITLE
[Smileys] Ne pas les parser si caractère adjacent avant et/ou après

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#323]
Actuellement, la version texte d'un smiley est remplacée par son équivalent en image même si elle touche du texte à gauche et à droite. Exemple gênant : 
=> http://preprod.zestedesavoir.com/tutoriels/45/gerez-vos-codes-source-avec-git/#6-annuler-un-commit-effectue-par-erreur  (chercher le texte "avant-avant-dernier commit", et vous comprendrez)

En résumé, il faut interpréter les trucs du genre `^^`, `:)` et compagnie uniquement s'ils sont au moins précédés d'un espace ou de rien, et surtout pas quand ils touchent directement un caractère. 

Idéalement, même règle à mettre en place pour le caractère suivant directement un smiley.

**Comment by cgabard** [comment]
Indeed, je vais metre a jour ça dès que j'ai 5 min

**Comment by firm1** [comment]
Résolu, donc je ferme.

Merci.

**Comment by firm1** [comment]
Quoique, le problème est toujours localisé [ici](http://preprod.zestedesavoir.com/tutoriels/off/45/gerez-vos-codes-source-avec-git/#6-annuler-un-commit-effectue-par-erreur)

a coté de la chaine `avant-avant-dernier commit`

**Comment by Coy0te** [comment]
Ici aussi, le bug est toujours là : 
=> http://preprod.zestedesavoir.com/forums/sujet/17/nouveau-sujet?page=1#p122

**Comment by SpaceFox** [comment]
C'est pas juste un problème de cache ?

2014-04-27 19:03 GMT+02:00 Coyote notifications@github.com:

**Comment by firm1** [comment]
Nope pour l'instant les forum et les tutos en off ne sont pas encore en cache. Je le desactive en dev, mais en prod le cache sera activé partout.

**Comment by firm1** [comment]
Bon bah cette fois ci le bug est fixé de manière un peu "sauvage". C'est à dire que si on mets de `^^` le caractère disparaît.

Oh rage, oh désespoir, ... :)

**Comment by cgabard** [comment]
Comment ça ?

**Comment by Coy0te** [comment]
> Comment ça ?

`Bug^^.` devient `Bug.` !

**Comment by cgabard** [comment]
Elles commençent a me brouter ces regexp... Je vais regarder ça dans la journée

**Comment by Coy0te** [comment]
Pas de violence, c'est (bientôt) les vacances ! :)

**Comment by firm1** [comment]
bon bah je crois que @cgabard a besoin de repos. ça marche pas encore

**Comment by cgabard** [comment]
ça fait quoi ? Toujours la même chose ? 

Le truc est que je n'ai pas d'instance locale pour tester là...

**Comment by Coy0te** [comment]
Ça dégage le smiley.

N.B : tu as le résultat en live ici si tu veux (mon post contient le texte  `Bug^^.` ) : 
=> http://preprod.zestedesavoir.com/forums/sujet/17/nouveau-sujet?page=1#p122

**Comment by cgabard** [comment]
Haaaaaaaa putain je viens de comprendre ! Ça n'a rien a voir avec les smileys ! C'est la mise en exposant qui match même si il n'y a pas de caractères à l'intérieur ! Mes codes de smileys fonctionnent depuis un moment en réalité...

**Comment by Coy0te** [comment]
LOOOOL. Indeed : 
=> http://preprod.zestedesavoir.com/forums/sujet/17/nouveau-sujet?page=1#p122

Mais tu as tout de même récemment corrigé le bug des smileys, car avant c'était bien un smiley qui se pointait en plein milieu du texte, alors que maintenant c'est juste le coup de la mise en exposant qui déconne.

**Comment by cgabard** [comment]
oui oui il y avait le bug des smileys mais sur ton post s'est un autre bug

**Comment by firm1** [comment]
Bon on est d'accord pour dire que le bug est résolu ?

Etant donné que zmarkdown utilise le `^` dans sa syntaxe pour les exposants, il faut les échapper dans un texte, ou les mettre dans des balises code. On va donc considérer que c'est au tuto de mateo sur git (suscité) d'être bien parsé.

**Comment by cgabard** [comment]
Non attend, normalement un Bug^^ ne devrait pas être parsé, si par les smileys, ni par la mise en exposant

**Comment by cgabard** [comment]
Tu as mis sur la préprod ma correction ?

**Comment by firm1** [comment]
> Tu as mis sur la préprod ma correction ?

Normalement oui

**Comment by cgabard** [comment]
Fuck, ça deconne encore donc.

**Comment by firm1** [comment]
> Non attend, normalement un Bug^^ ne devrait pas être parsé

bah pour moi, Bug^^ signifie qu'un mec a essayé de mettre du vide en exposant. et c'est normal que ça arrive pour moi.

**Comment by firm1** [comment]
Parce que si j'écris : 2^2^ => ça doit être parsé

**Comment by cgabard** [comment]
Oui mais il suffit de dire qu'il doit y avoir au moins un caractère entre le debut et la fin de la mise en exposant. Normalement ça devrait le faire là.

**Comment by firm1** [comment]
ça marche bien en effet

**Comment by cgabard** [comment]
Il a été un peu pénible ce bug

**Comment by firm1** [comment]
C'est rigolo, Simple IT a le même bug que nous, sauf que nous l'avons corrigé.

Leur tuto git : http://fr.openclassrooms.com/informatique/cours/gerez-vos-codes-source-avec-git

chercher la chaine : "avant-avant-dernier commit"

**Comment by cgabard** [comment]
Je peux leur proposer la regexp qui convient du coup :D

**Comment by firm1** [comment]
> Je peux leur proposer la regexp qui convient du coup :D

Non parce qu'ils risquent de peter autre chose

**Comment by Coy0te** [comment]
> Non parce qu'ils risquent de peter autre chose

Raison de plus pour leur proposer... :-\*
