### ISSUE TITLE
La documentation de solr doit être mise à jour

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3233]
La page en question : 

Ma version est 4.10.4 et les changements notés sont : 
- l'url d'accès à solr
- sous Linux on peut détailler un peu, en particulier installer via un packe manager (solr est dans l'AUR sous Arch par exemple)
- sous Linux on peut le lancer avec `systemctl`
- `python manage.py build_solr_schema > %solr_home%/example/solr/collection1/conf/schema.xml` me paraît ne plus être d'actualité (je change quand je trouve le path exact)

**Comment by artragis** [comment]
à fermer, zds n'est pas compatible avec cette version il me semble, c'est même un des travaux en cours de @DevHugo

**Comment by DevHugo** [comment]
Pour l'instant, j'ai la tête sous l'eau, avec le travail donc compter pas trop sur moi.

Je ne m'avancerais pas sur le fait qu'on soit pas compatible avec la dernière version de Solr, c'est possible qu'on le soit ou peut-être pas  (par-contre la dernière version de Haystack, on n'est pas compatible, c'est sur).

Sur la prod, la version officiellement supporté est la 4.9.1. On peut transformer le ticket pour faire une maj sur la dernière version de Solr. Dans ce cas la, il faudrait aussi modifier le update.md.

Le dernier point me paraîtrait surprenant, je pensais qu'on pouvait se passer du schema.xml que dans la version 5.X mais je te crois sur parole. Ce schema, nous permet de passer la recherche en français cad d'appliquer les flitres français sur les mots. Par défaut, c'est en anglais, il faudrait donc voir comment on peut changer ça, si on ne passe plus par le schema.xml.

**Comment by gustavi** [comment]
Je ferme car doublon de #3310
