### ISSUE TITLE
Forum - Pouvoir retourner à la liste des sujets facilement sur mobile

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#3234]
[Proposé par Ishimaru Chiaki sur le forum](https://zestedesavoir.com/forums/sujet/848/fil-dariane-sur-mobile/?page=1#p11704) :

> C'est peut-être plutôt trivial mais je trouve quand même qu'il manque le fil d'Ariane sur mobile. Par exemple, je consulte un sujet dans le forum des bugs, mais si je veux ensuite voir les autres sujets du même forum, je dois soit …
> - faire "Précédent" avec le bouton du mobile. Du coup, le sujet fraîchement consulté n'est pas marqué comme lu. Et on ne peut pas utiliser cette méthode si on est entré dans le topic via une notification.
> - passer par le menu de gauche, ensuite aller dans "Forums" puis entrer dans ladite section, ce qui est plus long, car deux requêtes de page plutôt qu'une.

Je propose donc que quand on est sur un sujet du forum, il y ait un lien "retour à la liste des sujets" dans le menu en version mobile.

**Comment by artragis** [comment]
peut être marqué comme "facile" car le template est assez clair sur la manière d'ajouter le lien.

**Comment by firm1** [comment]
Je réouvre ici car l'issue n'a été corrigé qu'à moitié.

Lorsqu'on est en mode connecté on a bien le bouton "revenir à la liste des sujets", mais en mode non connecté ce bouton n'est pas présent.

Il faudrait donc l'avoir pour tout le monde.
