### ISSUE TITLE
Pas de prévisualisation de sa biographie

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3237]
Lorsqu'on édite son profile (https://zestedesavoir.com/membres/parametres/profil/) il n'est pas possible de prévisualiser sa biographie alors que c'est le cas ailleurs lorsqu'on a du Markdown.

**Comment by GerardPaligot** [comment]
C'est plus une évolution qu'un bug.

**Comment by pierre-24** [comment]
Voilà qui est fait :)
