### ISSUE TITLE
impossible de cocher « Se souvenir de moi » sur certains mobiles

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3243]
Via le [forum](https://zestedesavoir.com/forums/sujet/4848/impossible-de-cocher-se-souvenir-de-moi/) : 

> J'ai remarqué qu'il met impossible de cocher la case pour garder ma connexion active. Lorsque je clique dessus, la case ne se coche pas. Je vois cependant le focus apparaître sur la case à cocher avant de disparaître (à moins que ce soit l'etat active). 
> 
> Je suis avec chrome sur un nexus 5
> Source:[grugru](http://zestedesavoir.com/forums/sujet/4848/impossible-de-cocher-se-souvenir-de-moi/?page=1#p89840)

Les cas : 
- nexus 5 + Chrome
- oneplus one + chrome
- LG G2 avec Chrome,

Ça ne touche pas tous téléphones.

**Comment by Chaoxys** [comment]
Salut, même problème pour moi avec un Galaxy S5 mini.
