### ISSUE TITLE
Mettre à jour un logo de contenu en brouillon le fait automatiquement sur la version en ligne

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3246]
... mais ça propose à nouveau une validation. On a donc un comportement contradictoire. Ça reste néanmoins pas super important.

**Comment by GerardPaligot** [comment]
Doublon de https://github.com/zestedesavoir/zds-site/issues/754

**Comment by gustavi** [comment]
@GerardPaligot fail dans le lien ;)

**Comment by GerardPaligot** [comment]
Bien vu. C'est modifié.
