### ISSUE TITLE
Suggestions de recherche en double

### ISSUE THREAD

**Issue by Vayel** [zestedesavoir/zds-site#3252]
Dans la barre de recherche sur la page d'accueil apparaissent des suggestions (de simples termes). Mais parfois, certains apparaissent en double. Par exemple : 

```
Cobol, Linux, Droit, Android, Android
Histoire, Windows, UDK, Windows, Django
```

Merci.

**Comment by gustavi** [comment]
Ça vient de cette ligne là https://github.com/zestedesavoir/zds-site/blob/dev/zds/pages/views.py#L48

Il faut juste changer la méthode pour enlever les index utilisés quand on fait du random.

**Comment by Vayel** [comment]
On peut probablement s'inspirer de ça : http://stackoverflow.com/questions/6494508/how-do-you-pick-x-number-of-unique-numbers-from-a-list-in-python

Edit : ah mince, c'est déjà ce qui est fait. --'

**Comment by Emeric54** [comment]
Non, en fait c'est déjà corrigé, et ce sera pour la prochaine version. 

J'avais tout bêtement mis deux mots identiques dans le [fichier](https://github.com/zestedesavoir/zds-site/blob/dev/suggestions.txt) contenant la liste des suggestions. Normalement, il y a seulement des problèmes avec _Windows_, _Android_ et _Astronomie_. 

Du coup, je suppose que l'on peut fermer ?

**Comment by Vayel** [comment]
Ce sont effectivement les mots avec lesquels j'ai rencontré des doublons.

**Comment by GerardPaligot** [comment]
Limite, avoir "Android, Android, Android, Android, Android" n'aurait pas été bien dérangeant. :-°

**Comment by Vayel** [comment]
Je te mets au défi de me faire un screenshot avec un tel affichage. :P
Edit : ah non, c'est pas possible, vu que le mot n'apparaît que deux fois dans le fichier.

**Comment by Emeric54** [comment]
Oh, vous savez, tout est possible... :-)
![](http://zestedesavoir.com/media/galleries/2674/2fee032d-fb7c-43c8-a941-f08d7bebd686.png)

Au fait @GerardPaligot, on ne devrait pas plutôt écrire _Androïd_ ?

**Comment by Eskimon** [comment]
Nop, sûrement car en anglais les tréma n'existent pas (je suppose)

Date: Tue, 22 Dec 2015 12:35:29 -0800

**Comment by Emeric54** [comment]
Justement, si on souhaite repasser ça en bon français, je me posais la question.

**Comment by SpaceFox** [comment]
Ce serait alors « Androïde » mais on ne traduit pas les marques (ce qui pourrait néanmoins être drôle).

**Comment by Emeric54** [comment]
Au passage, j'en profite pour mettre ça ici. Si par malchance, on tombe sur les 5 suggestions les plus longues, voilà ce que ça donne : 

![](http://zestedesavoir.com/media/galleries/2674/fa6e89f3-a768-4371-a511-60f1034a67bb.png)

L'affichage n'est pas top. Mais d'un autre côté, ça a tellement peu de chances d'arriver...
