### ISSUE TITLE
Uniformiser la gestion des tags

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3253]
**CETTE ISSUE EST À PRENDRE EN COMPTE APRÈS LA ZEP-25**

Lors de la ZEP-25 il a été décidé de séparer les tags des titres de contenu. Dans un second temps il faudra uniformiser cela avec les forums.

https://zestedesavoir.com/forums/sujet/2378/zep-25-categorisation-des-articles-et-tutoriels/?page=5#p90644

**Comment by GerardPaligot** [comment]
Pourquoi cette issue est créée ici si ça rentre dans le cadre d'une zep ?

**Comment by gustavi** [comment]
C'est hors ZEP, ça vient après la ZEP-25.

**Comment by GerardPaligot** [comment]
Doublon https://github.com/zestedesavoir/zds-site/issues/2388
