### ISSUE TITLE
Timeout sans publication lors de la validation d'un gros tuto

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#3254]
Tout est dans le titre, le site pars en timeout lorsqu'un valido essaie de publier un tutoriel assez gros (en l’occurrence : Arduino). Ce qui est ennuyant c'est que ca ne génère rien du tout, ni le pdf ni l'html ou autre et que le contenu n'est pas mis à jour (pré-ZEP-12 ca partait aussi en timeout mais le contenu en ligne était mis à jour). Du coup à l'heure actuelle le tuto Arduino (et surement d'autre) ne peut plus évoluer :( .

(je tag en bug mais ca frole la regression)

**Comment by gustavi** [comment]
Est-ce que l'on sait ce qui génère cette grosse latence ?

**Comment by Eskimon** [comment]
Je dirais la public pandoc pdf

**Comment by pierre-24** [comment]
Solution possible : https://github.com/zestedesavoir/zds-site/issues/3080

**Comment by pierre-24** [comment]
#3260 aura un impact positif là dessus ;)
