### ISSUE TITLE
Pas d'avertissement si quelqu'un a écrit un commentaire avant le sien

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#3256]
J'étais en train d'écrire le premier commentaire d'un article. Je l'envoie et là je m'aperçois que quelqu'un a écrit et posté un commentaire avant le mien. Normalement j'aurais du être prévenu par le serveur que quelqu'un a écrit un commentaire que je n'ai pas vu !

**Comment by artragis** [comment]
Very strange, on a bien tout ça qui est en place pourtant @pierre-24

**Comment by pierre-24** [comment]
Plutôt, oui. Gros problème, c'est que c'est assez difficile à mettre sous forme de T.U.

**Comment by Eskimon** [comment]
> Plutôt, oui. Gros problème, c'est que c'est assez difficile à mettre sous forme de T.U.

Ca dépend. La vue nous retourne pas l'ensemble des messages à afficher ? Si oui suffit de regarder qu'on est bien à n au lieu de n+1

**Comment by poulp** [comment]
Je viens d'essayer mais j'arrive pas à reproduire en local. Peut être plus de précision sur l'article en question.

**Comment by artragis** [comment]
Je pense que depuis le temps ça a été corrigé silencieusement. Faudra vérifier sur la béta quand elle sera up

**Comment by gustavi** [comment]
Je confirme.
