### ISSUE TITLE
Un nouveau message dans un MP crée une notif

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3259]
A partir de l'API, si vous créez un nouveau message dans une conversation, une notification sera créée sur le site.

**Comment by gustavi** [comment]
En fait je crois que ça fait pareil sur le site sauf que ça charge la page donc ça désactive la notification. Dans ce cas là il faut retirer le tag `API`.

**Comment by GerardPaligot** [comment]
Ah oui tiens, j'avais pas vu la chose comme ça. C'est sans doute le cas, je retire le tag.

**Comment by GerardPaligot** [comment]
Ah tiens, il se pourrait bien que la ZEP-24 ait corrigé ce bug.

**Comment by SpaceFox** [comment]
« Corrigé par mégarde » :)

**Comment by GerardPaligot** [comment]
En fait, je suis certain que je corrige ce bug. Je ne génère plus de notif pour l'auteur quand un utilisateur poste un message : https://github.com/zestedesavoir/zds-site/blob/dev/zds/notification/receivers.py#L208-L210

**Comment by gustavi** [comment]
Je confrme après un test !
