### ISSUE TITLE
Lien vers le sujet de la bêta-zone pas toujours présent

### ISSUE THREAD

**Issue by Nodraak** [zestedesavoir/zds-site#3267]
Dominus Carnufex [raporte](https://zestedesavoir.com/forums/sujet/5020/lien-vers-le-sujet-de-la-beta-zone-pas-toujours-present/) que :

> Depuis la mise en place de la ZEP-12, sur les contenus en bêta, il y a un lien vers le sujet du forum associé. En revanche, si l’on passe par « Mes articles » ou « Mes tutoriels » (voyez la légère différence dans l’URL), le lien n’est plus présent. C’est quand même dommage.

Je m'en occupe.

**Comment by Nodraak** [comment]
97854509d048decaf080255b6537d92737507b53

**Comment by Nodraak** [comment]
J'arrive à reproduire le bug avec la version actuellement en prod (v15.0-noel/8f1d710) mais pas avec la plus récente (dev/f182e99).

[Cette pull-request](https://github.com/zestedesavoir/zds-site/pull/3258/files) a surement corrigé l'incohérence.

**Comment by pierre-24** [comment]
Toutafé, je m'en étais occupé :)
