### ISSUE TITLE
Pagination : le paramètre page_size peut être ignoré

### ISSUE THREAD

**Issue by aesteve** [zestedesavoir/zds-site#3268]
Reproducer :

GET `/api/membres?page=2`

Retourne 10 résultats

Puis :

GET `/api/membres/?page_size=100&page=2`

Retourne toujours 10 résultats.

D'après @DevHugo ça semblerait être un problème de [cache](https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/api/views.py#L26).

Effectivement il faut toujours inclure l'intégralité des paramètres de la requête dans la clef du cache.

(et éventuellement certains headers qui peuvent changer la tronche de la réponse)

**Comment by GerardPaligot** [comment]
Effectivement, `page` est dans la clé et sans doute pas `page_size`.

**Comment by aesteve** [comment]
D'ailleurs je comprends pas bien comment fonctionne le cache.

https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/api/views.py#L38-L40

Le bearer est un paramètre implicite à toute mise en cache ?

Parce que (j'ai pas encore essayé) mais si je fais GetMyDetails pour un utilisateur, puis pour un second utilisateur dans un interval de temps relativement court, faudrait pas qu'il me renvoie les infos du premier.

T'aurais une doc @GerardPaligot que je puisse consulter ? Merci :)

**Comment by GerardPaligot** [comment]
Tu trouveras ton bonheur ici : http://chibisov.github.io/drf-extensions/docs/.

**Comment by GerardPaligot** [comment]
> Le bearer est un paramètre implicite à toute mise en cache ?
> Parce que (j'ai pas encore essayé) mais si je fais GetMyDetails pour un utilisateur, puis pour un second utilisateur dans un interval de temps relativement court, faudrait pas qu'il me renvoie les infos du premier.

Ooooh ... ça expliquerait [un problème récent](https://zestedesavoir.com/forums/sujet/4361/zmessenger/?page=3#p91163) que j'ai eu avec un projet basé sur l'API.

**Comment by aesteve** [comment]
Yep.

http://chibisov.github.io/drf-extensions/docs/#key-constructor

``` python
    user = bits.UserKeyBit()
```

**Comment by AmarOk1412** [comment]
Je ferme, https://zestedesavoir.com/api/membres/?page_size=100&page=2 retournant bien 100 résultats :)
