### ISSUE TITLE
Requêtes lentes sur la page d'accueil des forums

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3269]
La page d'accueil des forums fait des requêtes identiques pour **chaque** forum, dont celle-ci qui provient de [zds/forum/models.py in get_last_message(147)](https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/models.py#L142) :

``` sql
SELECT 
    `utils_comment`.`id`,
    `utils_comment`.`author_id`,
    `utils_comment`.`editor_id`,
    `utils_comment`.`ip_address`,
    `utils_comment`.`position`,
    `utils_comment`.`text`,
    `utils_comment`.`text_html`,
    `utils_comment`.`like`,
    `utils_comment`.`dislike`,
    `utils_comment`.`pubdate`,
    `utils_comment`.`update`,
    `utils_comment`.`is_visible`,
    `utils_comment`.`text_hidden`,
    `forum_post`.`comment_ptr_id`,
    `forum_post`.`topic_id`,
    `forum_post`.`is_useful`
FROM
    `forum_post`
        INNER JOIN
    `forum_topic` ON (`forum_post`.`topic_id` = `forum_topic`.`id`)
        INNER JOIN
    `utils_comment` ON (`forum_post`.`comment_ptr_id` = `utils_comment`.`id`)
WHERE
    `forum_topic`.`forum_id` = 2
ORDER BY `utils_comment`.`pubdate` DESC
LIMIT 1
```

Problèmes :
1. Le `order` oblige à un tri complet sur une table temporaire, car le critère de tri, bien qu'étant indexé, n'est pas sur la 1ère table de la liste de jointures (cf http://dev.mysql.com/doc/refman/5.5/en/internal-temporary-tables.html)
2. Pourquoi trier par dates alors qu'on a un champ d'ordre en la personne de `position` ?
3. Cette requêtes (et d'autres moins longues) est faite pour chacun de nos forums.
4. Dans le code, `.all()[0]` pourrait être remplacé par `.first()`, non ?

Ceci ralentit sensiblement l'affichage de cette page. On pourrait améliorer la requête SQL (mais je ne sais pas comment), ou dénormaliser cette information en stockant l'ID du dernier message directement dans la table des forums.

**Comment by artragis** [comment]
ça passe peut être par ceci : 

``` python
    def get_last_message(self):
        """
        :return: the last message on the forum, if there are any.
        """
        return Comment.objects.select_subclasses("post").filter(topic__forum=self).order_by('-pubdate').first
```

Vous trouverez l'inspiration [ici](http://django-model-utils.readthedocs.org/en/latest/managers.html#inheritancemanager).

Vous vous demandez peut-être pourquoi je ne me suis pas chargé moi-même de faire la modif? Car c'est exactement à ce moment là qu'il devient nécessaire de migrer cette méthode vers le ForumManager, ce qui entraînera immédiatement pas mal de changements dans le code.

**Comment by artragis** [comment]
la requête en plus d'être lente était fait plusieurs fois par forum. J'ai retiré les duplicata.

De plus aujourd'hui elle ne se base plus tout à fait sur cette requête (on a la liaison last_message qui est utilisée).
