### ISSUE TITLE
Amélioration des MP de résolution d'alerte

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#327]
GG @firm1 pour l'amélioration de la gestion des alertes, tout roule.

Deux petites évolutions à prévoir :
- personnaliser/contextualiser le titre du MP reçu par un membre lorsqu'une [alerte qu'il a postée est résolue](https://github.com/Taluu/ZesteDeSavoir/issues/71). Sinon, un membre qui poste pas mal d'alertes va vite se retrouver avec une chiée de MPs qui s'appellent tous "Résolution d'alerte" dans sa boîte de réception...
- empêcher de pouvoir répondre au MP. Actuellement ça peut porter à confusion : un membre pourrait croire qu'il répond au mec qui a résolu son alerte, alors qu'en fait non, ça partira directement dans la boîte "trou noir" du compte de la mascotte.

**Comment by Alex-D** [comment]
D'ailleurs, ma vision des choses à la base était d'utiliser les notifications pour centraliser ça, plutôt que des MP...

Car actuellement, les notifications ne servent qu'à "Mes Interventions" si on rapporte ça au SdZv3. Or je voyais vraiment ça comme une centralisation des notifications diverses et variées.

Est-ce que le système de notifications actuel est assez souple pour gérer ça du coup ? Même s'il faut que je revois le design, ça ne me dérange pas car pour le coup ça serait vraiment le rôle des notifs.

**Comment by Coy0te** [comment]
Sauf changement du code depuis la dernière discussion sur ce sujet (et sauf erreur de ma part), non le système actuel n'est pas assez souple. Mais ça reste une bonne idée d'utiliser les notifs, il faudrait s'en occuper dans une prochaine itération.

**Comment by firm1** [comment]
> personnaliser/contextualiser le titre du MP reçu par un membre

Je ne suis pas trop pour. Parce qu'en contextualisant le titre du MP, on noie le reste des MP (importants). Donc c'est plus simple quand on a un titre de MP dédié à la résolution, on sait tout de suite qu'il ne faut pas cliquer dessus si on est un ultra-alerteur.

> empêcher de pouvoir répondre au MP

Une sorte de lock du MP ? Je suis plutôt d'accord avec cette proposition.

> D'ailleurs, ma vision des choses à la base était d'utiliser les notifications pour centraliser ça, plutôt que des MP

Sur le papier ça sonne bien, mais dans la pratique c'est moins fonctionnel que les MPs. Pourquoi ?
- une résolution d'alertes peut s'accompagner d'un message plus ou moins long pour expliquer le pourquoi. Mettre ce message dans la zone de notif serait juste inenvisageable à cause de sa taille plus ou moins variable.
- si je suis un ultra-alerteur, la zone "tout mes notifications" sera juste noyée par le reste. Ce qui n'est pas très pratique
- la zone de notification seule ne permet pas d'expliquer qui, pourquoi et qu'est ce qui a été résolu précisément, pour celà, il faudrait une autre page dédié au détails des notifications liées aux résolutions d'alertes.

En gros, la zone de notification c'est bien quand on a pas trop d'infos à donner, mais pour le reste, les MPs c'est mieux, et quand on pourra filtrer dans les MPs, ça sera encore meilleure.

> Sauf changement du code depuis la dernière discussion sur ce sujet, non le système actuel n'est pas assez souple.

Le système de notification a toujours été souple pour la simple et bonne raison, que c'est juste un tag à rajouter dans la pile. Mais sa vaudrais dire qu'il faut prévoir de conserver toutes les alertes faites sur le site en base, même lorsqu'elle sont résolue. Chose que je trouve inutile personnellement.

**Comment by cgabard** [comment]
> >  empêcher de pouvoir répondre au MP
> 
> Une sorte de lock du MP ? Je suis plutôt d'accord avec cette proposition.

Que ce passe t'il actuellement si lors d'un MP entre 2 personnes l'une d'elle l'a supprimé ? Sur le Sdz cela rayait le nom du participant et si l'auteur etait le seul participant d'un MP, il ne pouvait plus répondre sur le MP. Du coup cette impossibilité de répondre était simulé en supprimant directement le message provenant de la mascotte. Du coup le mec est seul participant et ne peut pas répondre.

**Comment by firm1** [comment]
> Que ce passe t'il actuellement si lors d'un MP entre 2 personnes l'une d'elle l'a supprimé ?

Actuellement, si il ne reste plus qu'une personne dans un MP, tu peux encore continuer à t'écrire à toi même et/ou rajouter quelqu'un d'autre dedans. Mais tu as raison, si on considère qu'un MP tout seul ne devrait pas être alimenté, il suffit lors de l'envoi du MP de virer en même temps la mascotte de la conversation, et ça sera nickel.

**Comment by Alex-D** [comment]
Vu le nombre d'informations que tu me dis là, en effet les MP sont mieux adaptés du fait qu'on puisse les supprimer déjà.

Après une chose que je me demande c'est : pourquoi prévenir un alerteur qu'un modo est passé ? Est-ce réellement utile ?

**Comment by cgabard** [comment]
+1 Alex. J'ai des doutes sur l'utilité. Ou alors il faut ajouter une option pour ne plus les recevoir car un membre actif qui fait régulièrement des signalements se retrouverait rapidement spammé

**Comment by firm1** [comment]
> Après une chose que je me demande c'est : pourquoi prévenir un alerteur qu'un modo est passé ? Est-ce réellement utile ?

C'est surtout pour instaurer dès maintenant un workflow de base, qui, dans une prochaine itération, permettra de donner d'autres informations à l'alerteur (l'évolution du karma par exemple).

**Comment by Alex-D** [comment]
Hum... ok, donc ça changera assez rapidement a priori.

Dans ce cas, je propose de former le titre du MP comme tel : [Alerte résolue] {{titre-du-topic}}
Sinon ça va être le bazar.

**Comment by firm1** [comment]
> Dans ce cas, je propose de former le titre du MP comme tel : [Alerte résolue] {{titre-du-topic}}
> Sinon ça va être le bazar.

+1
