### ISSUE TITLE
Problèmes de requêtes SQL « cachées » dans les templates

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3270]
On a un certain nombre de méthodes sur nos modèles qui provoquent des requêtes SQL quand on les utilise, sans que quoi que ce soit indique au créateur de template que ceci existe.

Si ça permet en général d'avoir un code à peu près clair, c'est catastrophique pour les performances puisqu'on se retrouve à faire des requêtes dans des boucles sur les pages sans même le savoir. Même si les requêtes elle-mêmes sont légères, le temps de les préparer et de les traiter ne devient plus négligeable.

On devait trouver des solutions pour éviter ça.

Exemples :

**templates/misc/message.part.html** --> **zds/utils/templatetags/profile.py in liked(60)**
`{% if user|liked:message.pk %}voted{% endif %}"`
Provoque

``` sql
SELECT (1) AS `a` FROM `utils_commentlike` WHERE (`utils_commentlike`.`user_id` = 72 AND `utils_commentlike`.`comments_id` = 8611) LIMIT 1
```

**templates/misc/message.part.html** --> **zds/utils/templatetags/profile.py in disliked(65)**
`{% if user|disliked:message.pk %}voted{% endif %}"`
Provoque

``` sql
SELECT (1) AS `a` FROM `utils_commentdislike` WHERE (`utils_commentdislike`.`user_id` = 72 AND `utils_commentdislike`.`comments_id` = 8611) LIMIT 1
```

**templates/misc/message.part.html** --> **zds-site/zds/forum/models.py in antispam(416)**
`{% if cite_link and not topic.is_locked and not topic.antispam %}`
Provoque

``` sql
SELECT `utils_comment`.`id`, `utils_comment`.`author_id`, `utils_comment`.`editor_id`, `utils_comment`.`ip_address`, `utils_comment`.`position`, `utils_comment`.`text`, `utils_comment`.`text_html`, `utils_comment`.`like`, `utils_comment`.`dislike`, `utils_comment`.`pubdate`, `utils_comment`.`update`, `utils_comment`.`is_visible`, `utils_comment`.`text_hidden`, `forum_post`.`comment_ptr_id`, `forum_post`.`topic_id`, `forum_post`.`is_useful` FROM `forum_post` INNER JOIN `utils_comment` ON ( `forum_post`.`comment_ptr_id` = `utils_comment`.`id` ) WHERE (`forum_post`.`topic_id` = 697 AND `utils_comment`.`author_id` = 72) ORDER BY `utils_comment`.`position` DESC LIMIT 1
```

Et ce sans que rien n'indique que `topic.antispam` fait une requête, contrairement aux précédents.

… et il y en a plein d'autres. Le pire étant sans doute :

**templates/forum/base.html** --> **zds-site/zds/forum/models.py in last_read_post(296)**
`{{ topic.last_read_post.get_absolute_url }}`
Cette méthode lance en réalité cette requête (ici reformattée) :

``` sql
SELECT 
    `forum_topicread`.`id`,
    `forum_topicread`.`topic_id`,
    `forum_topicread`.`post_id`,
    `forum_topicread`.`user_id`,
    `forum_topic`.`id`,
    `forum_topic`.`title`,
    `forum_topic`.`subtitle`,
    `forum_topic`.`forum_id`,
    `forum_topic`.`author_id`,
    `forum_topic`.`last_message_id`,
    `forum_topic`.`pubdate`,
    `forum_topic`.`is_solved`,
    `forum_topic`.`is_locked`,
    `forum_topic`.`is_sticky`,
    `forum_topic`.`key`,
    `forum_forum`.`id`,
    `forum_forum`.`title`,
    `forum_forum`.`subtitle`,
    `forum_forum`.`image`,
    `forum_forum`.`category_id`,
    `forum_forum`.`position_in_category`,
    `forum_forum`.`slug`,
    `forum_category`.`id`,
    `forum_category`.`title`,
    `forum_category`.`position`,
    `forum_category`.`slug`,
    T6.`id`,
    T6.`password`,
    T6.`last_login`,
    T6.`is_superuser`,
    T6.`username`,
    T6.`first_name`,
    T6.`last_name`,
    T6.`email`,
    T6.`is_staff`,
    T6.`is_active`,
    T6.`date_joined`,
    `utils_comment`.`id`,
    `utils_comment`.`author_id`,
    `utils_comment`.`editor_id`,
    `utils_comment`.`ip_address`,
    `utils_comment`.`position`,
    `utils_comment`.`text`,
    `utils_comment`.`text_html`,
    `utils_comment`.`like`,
    `utils_comment`.`dislike`,
    `utils_comment`.`pubdate`,
    `utils_comment`.`update`,
    `utils_comment`.`is_visible`,
    `utils_comment`.`text_hidden`,
    `forum_post`.`comment_ptr_id`,
    `forum_post`.`topic_id`,
    `forum_post`.`is_useful`,
    T9.`id`,
    T9.`password`,
    T9.`last_login`,
    T9.`is_superuser`,
    T9.`username`,
    T9.`first_name`,
    T9.`last_name`,
    T9.`email`,
    T9.`is_staff`,
    T9.`is_active`,
    T9.`date_joined`,
    T10.`id`,
    T10.`title`,
    T10.`subtitle`,
    T10.`forum_id`,
    T10.`author_id`,
    T10.`last_message_id`,
    T10.`pubdate`,
    T10.`is_solved`,
    T10.`is_locked`,
    T10.`is_sticky`,
    T10.`key`,
    T11.`id`,
    T11.`title`,
    T11.`subtitle`,
    T11.`image`,
    T11.`category_id`,
    T11.`position_in_category`,
    T11.`slug`,
    T12.`id`,
    T12.`title`,
    T12.`position`,
    T12.`slug`,
    T13.`id`,
    T13.`password`,
    T13.`last_login`,
    T13.`is_superuser`,
    T13.`username`,
    T13.`first_name`,
    T13.`last_name`,
    T13.`email`,
    T13.`is_staff`,
    T13.`is_active`,
    T13.`date_joined`,
    `auth_user`.`id`,
    `auth_user`.`password`,
    `auth_user`.`last_login`,
    `auth_user`.`is_superuser`,
    `auth_user`.`username`,
    `auth_user`.`first_name`,
    `auth_user`.`last_name`,
    `auth_user`.`email`,
    `auth_user`.`is_staff`,
    `auth_user`.`is_active`,
    `auth_user`.`date_joined`
FROM
    `forum_topicread`
        INNER JOIN
    `auth_user` ON (`forum_topicread`.`user_id` = `auth_user`.`id`)
        INNER JOIN
    `forum_topic` ON (`forum_topicread`.`topic_id` = `forum_topic`.`id`)
        INNER JOIN
    `forum_forum` ON (`forum_topic`.`forum_id` = `forum_forum`.`id`)
        INNER JOIN
    `forum_category` ON (`forum_forum`.`category_id` = `forum_category`.`id`)
        INNER JOIN
    `auth_user` T6 ON (`forum_topic`.`author_id` = T6.`id`)
        INNER JOIN
    `forum_post` ON (`forum_topicread`.`post_id` = `forum_post`.`comment_ptr_id`)
        INNER JOIN
    `utils_comment` ON (`forum_post`.`comment_ptr_id` = `utils_comment`.`id`)
        INNER JOIN
    `auth_user` T9 ON (`utils_comment`.`author_id` = T9.`id`)
        INNER JOIN
    `forum_topic` T10 ON (`forum_post`.`topic_id` = T10.`id`)
        INNER JOIN
    `forum_forum` T11 ON (T10.`forum_id` = T11.`id`)
        INNER JOIN
    `forum_category` T12 ON (T11.`category_id` = T12.`id`)
        INNER JOIN
    `auth_user` T13 ON (T10.`author_id` = T13.`id`)
WHERE
    (`forum_topicread`.`user_id` = 72
        AND `forum_topicread`.`topic_id` = 2972)
ORDER BY `utils_comment`.`position` DESC
LIMIT 1
```

Qui en plus oblige à un « full table scan » de la part de MySQL…

---

Je ne sais pas quelles sont les bonnes pratiques Django, mais je suis assez surpris de voir le template taper directement sur le modèle SQL. Ne devrait-on pas fournir au template une représentation déjà intégralement construite ?

**Comment by pierre-24** [comment]
>  Ne devrait-on pas fournir au template une représentation déjà intégralement construite ?

Si. Après, @artragis a déjà fait énormément de trucs dans ce sens là, donc il "suffit" de continuer :)

**Comment by gustavi** [comment]
Une solution pour profile serait de ne plus utiliser de O2O entre User et Profile mais d'utiliser une surcharge de Use : https://docs.djangoproject.com/en/1.9/topics/auth/customizing/#substituting-a-custom-user-model

C'est assez violent.

**Comment by SpaceFox** [comment]
Non mais ça, on a déjà essayé, c'est à peu près impossible.

**Comment by gustavi** [comment]
Alors on n'a aucune autre option/

**Comment by artragis** [comment]
C'est lorsqu'on fait la requête qu'on doit jouer avec le chargement des
entités.

ZDS sous utilise clairement les manager, il serait temps qu'on les utilise
plus et mieux.

2016-01-04 10:07 GMT+01:00 Laville Augustin notifications@github.com:

**Comment by SpaceFox** [comment]
@gustavi je ne vois pas le lien entre tes remarques et le problème que je soulève.

@artragis tu as un lien vers la doc de ce dont tu parles ?

**Comment by GerardPaligot** [comment]
En quoi les managers aideront au problème soulevé par spacefox ?

Je pense que le problème est bien plus complexe. Aujourd'hui, pour une vue avec son template donné, on consolide plus ou moins bien partout tout ce qu'il faut pour que le template se suffit à lui même (je dis bien plus ou moins) mais il y a certaines choses inévitables dans les templates parents.

Par exemple, pour tout ce qui est notification et message privé, nous n'avons pas les infos et nous faisons plusieurs requêtes (souvent les mêmes) pour les récupérer. C'est un exemple mais il en existe plein d'autres à plusieurs niveaux de couche dans les templates.

Aussi, nous envoyons aux templates les objets provenant de la base directement et nous appelons des méthodes dessus tout naturellement parce qu'elles sont disponibles. Il faudrait complexifier ce que nous envoyons aux templates pour faire ces requêtes dans les vues (la plus optimisée possible) et ne plus appeler des méthodes qui fait des requêtes dans les templates (sauf cas inévitable).

Une idée pourrait être :
- Faire un nettoyage dans les méthodes. Certaines méthodes sont dans un modèle alors qu'elle n'a rien à y faire. Par exemple, le profile est bourré de méthodes qui n'a rien à voir avec lui et qui se contente de faire des requêtes avec d'autres modèles.
- Renommer les méthodes qui font des requêtes SQL en préfixant la méthode par `sql_` (ou autre chose). Au moins, on serait conscient de faire 1 ou plusieurs requêtes. Après, ça sera plus moche à l'usage ...

**Comment by artragis** [comment]
@spacefox : pour le lien
https://docs.djangoproject.com/en/1.9/topics/db/managers/#django.db.models.Manager

basiquement, le manager c'est ce qu'on utilise dans l'attribut .objects

Nous n'utilisons les managers que de manière simpliste (et en plus non
systématique) comme on peut le voir [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/managers.py).

Ces derniers, associés aux autres possibilité de model_utils (qui est une
dépendance du projet à cause de plein de truc qu'on utilise), on peut faire
de très belles choses qui rendent le truc plus expressif, testable et
performant.

**Comment by gustavi** [comment]
@SpaceFox au temps pour moi j'ai lu un peu vite.

@GerardPaligot mettre du SQL dans le code c'est assez sale et vraiment pénible à maintenir.

**Comment by GerardPaligot** [comment]
> @GerardPaligot mettre du SQL dans le code c'est assez sale et vraiment pénible à maintenir.

Je n'ai nullement proposé d'écrire des requêtes SQL dans le code.

**Comment by artragis** [comment]
> En quoi les managers aidera au problème soulevé par spacefox ?

la suite de ton message donne la réponse à cette question.
- l'organisation : éviter qu'un modèle fasse des choses qu'il ne doit pas
  faire
- une méthode du manager = une méthode qui fait du SQL, même pas besoin de
  préfixer
- simplifer les méthodes qu'on a dans les templatetags
- faire les bons précalculs (style ajouter des .extra pas piqués des
  hannetons comme on peut le voir dans la gestion du comptage des
  commentaires pour les articles)

Le 4 janvier 2016 à 10:36, Gérard Paligot notifications@github.com a
écrit :

**Comment by aesteve** [comment]
Y'a pas l'équivalent dans Django du `ModelAndView` de SpringMVC ? Ou de la `contextMap` qu'on retrouve dans d'autres frameworks ?

C'est-à-dire un objet (une simple map/dictionnaire) qui stocke les données dont a besoin le template. Le plus souvent (bis) ces map sont possibles à mettre en cache pour un contexte donné (le contexte peut ou ne peut pas dépendre de l'utilisateur). La complexité est de générer ledit objet côté serveur, mais une fois généré on peut le stocker en cache et surtout on a la garantie que le template ne peut pas "par inadvertance" appeler des méthodes coûteuses.

(ça peut aussi être des objets "creux" si besoin i.e. une classe `Person` avec `firstname` `lastname` comme attributs).

Si jamais ça peut aider / mettre sur une piste.

**Comment by GerardPaligot** [comment]
@aesteve Ce que tu décris semble être déjà le cas actuellement. Nous ne faisons que donner un contexte (qui est une simple map) à nos templates. Cependant, les valeurs dans ces maps sont des objets sur lesquels tu peux appeler des méthodes déclarés dans le modèle. C'est simplement qu'il faudrait rajouter plus d'info dans ces maps pour ne plus devoir faire des appels de méthodes dans nos templates.

**Comment by aesteve** [comment]
Ou renvoyer de "purs" objets et non plus des objets instrumentés / lazy loadés. (mais c'est très difficile à faire il faut encapsuler tous les objets du modèle et court-circuiter le lazy loading, ce qui pose également des problèmes).

Faut renvoyer un objet qui n'est qu'une "vue" (au sens figuré mais potentiellement au sens propre) de la BDD dans ce cas. Je l'ai déjà fait, c'est vraiment pas drôle à coder :( mais en termes de performances c'est quasiment le must. 

J'espère que Django dispose d'une autre solution.

**Comment by artragis** [comment]
pour celle sur les forums je m'en occupe, elle ne devrait plus être présente depuis un bon bout de temps donné que j'avais fait le travail dessus.
