### ISSUE TITLE
Uniformiser « commentaire » et « réaction »

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3271]
On a commentaire de partout mais à quelques endroits c'est [réaction](https://github.com/zestedesavoir/zds-site/search?utf8=%E2%9C%93&q=r%C3%A9action&type=Code). Ça serait bien d'uniformiser ça.

**Comment by pierre-24** [comment]
C'est pas une ZEP, ça ?

**Comment by gustavi** [comment]
Euh non, pas vraiment, il s'agit juste de changer 2 ou 3 chaines de caractères ^^

**Comment by pierre-24** [comment]
Aaah, my bad, je croyait que tu parlais du nom des modèles :-)

**Comment by gustavi** [comment]
Corrigé dans #3278 par @Vayel.
