### ISSUE TITLE
Améliorer load_fixtures

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3272]
Voici mes remarques pour la commande : 
- Il serait bien d'avoir une commande `help` qui affiche les message d'aide
- Les message d'aide manque d'infos (sur la partie contenuv2)
- Le v2 est pénible, est-ce que c'est nécessaire de le garder maintenant qu'on a virer le reste ?
- Les galeries prennent un temps fou, il faut en faire moins par utilisateur
- Pas assez de contenu publié pour les tutos et articles. Quand je veux 200 contenus publiés il me faut 620 contenus au total. Il faudrait que le nombre publié soit au moins de 50% car c'est avec ces données qu'on travaille.
- **Les contenus n'ont pas de date de publication**.

**Comment by pierre-24** [comment]
> Il serait bien d'avoir une commande help qui affiche les message d'aide

Oui <3

> Le v2 est pénible, est-ce que c'est nécessaire de le garder maintenant qu'on a virer le reste ?

Probablement pas.

> Pas assez de contenu publié pour les tutos et articles. Quand je veux 200 contenus publiés il me faut 620 contenus au total. Il faudrait que le nombre publié soit au moins de 50% car c'est avec ces données qu'on travaille.

Très sincèrement, j'ai choisi les nombres à pouf, on peut imaginer un paramètre pour ça :-)

**Comment by gustavi** [comment]
Je changerai 

``` python
    percent_contents_in_validation = 0.4
    percent_contents_with_validator = 0.2
    percent_contents_public = 0.3
```

par 

``` python

    percent_contents_in_validation = 0.2
    percent_contents_with_validator = 0.1
    percent_contents_public = 0.6
```

**Comment by pierre-24** [comment]
Pourquoi pas. Objectivement, j'ai pas spécialement d'argument pour ou contre ^^ (à part que ça fait pas 100% dans un cas comme dans l'autre :p )

**Comment by gustavi** [comment]
J'ai pas regardé le détaille mais j'ai supposé que le reste c'était du brouillon ;)

**Comment by pierre-24** [comment]
_it makes sense_ ;)
