### ISSUE TITLE
Le bacula-fd n'est pas en autostart sur la prod

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3277]
Donc, au moindre redémarrage (volontaire ou non) on perds la sauvegarde…

**Comment by GerardPaligot** [comment]
C'est quoi un bacula-fd ?

**Comment by SpaceFox** [comment]
Le process client de la sauvegarde, cette issue est surtout là pour que j'oublie pas de le faire ce soir.

**Comment by Eskimon** [comment]
Du coup "tu l'as fait ce soir" ?

**Comment by SpaceFox** [comment]
Ouais, en fait c'était iptables qui foutait la merde. Et merci à @Un-Cornichon pour l'aide à la résolution :)
