### ISSUE TITLE
Chargement depuis cdn.mathjax.org : uniquement si c'est nécessaire

### ISSUE THREAD

**Issue by aesteve** [zestedesavoir/zds-site#3289]
cf. [ce message de Dominus](https://zestedesavoir.com/forums/sujet/5086/truc-qui-charge-indefiniment-sur-les-forums/?page=1#p93570)

Il semblerait qu'une requête soit faite vers `cdn.mathjax.org` pour tous les sujets du forum même si celui-ci ne contient pas de formule mathématique. Tandis que pour les tutoriels, cette requête n'est faite que si le tutoriel contient bien une formule.

Dans les deux cas (forums & tutos) `MathJax.js` est chargé (j'ai vérifié) mais il semblerait qu'il y ait quand même une différence de traitement en ce qui concerne cette requête à destination de `cdn.mathjax.org`.

Il faudrait donc voir s'il existe dans le code une référence directe à cette ressource supplémentaire et si on peut s'en affranchir ou pas.

**Comment by artragis** [comment]
Elle est aussi chargée sur la page d'accueil alors que cette page n'a aucune mathématique à afficher.

On peut très sûrement faire un truc qui fonctionne avec ça.

**Comment by pierre-24** [comment]
Chaiplu si le LaTeX est toujours autorisé dans les titres (auquel cas ça se justifierai), mais comme c'était le cas à l'époque, c'était logique. Au delà de ça, bof, dans le sens ou un navigateur un minimum intelligent tapera ça en cache et on sera tranquille (raison pour laquelle ce genre de "bug" est assez difficile à détecter, vu qu'il faut forcer le nettoyage du cache pour avoir le soucis, Dominus a juste "pas eu de chance"). 

**tl;dr:** comme vous voulez, mais ça me semble pas gravissime.

**Comment by aesteve** [comment]
Je suis d'accord que c'est pas dramatique du tout. Mais ça me semble être un bon "good first bug" : 
- pour jeter un oeil aux templates et comment certaines ressources sont chargées conditionnellement.
- parce que le risque de tout casser est relativement mesuré
- parce que ça se teste bien : un topic avec une formule de maths se charge bien / un topic sans formule ne fait pas d'appel au cdn, c'est binaire, c'est facile

Du coup j'y jetterai un oeil quand même à l'occasion.

**Comment by gustavi** [comment]
La solution au problème : créer un block `extra_css` si ce n'est pas déjà le cas et ajouter l'info dedans sur les bonnes pages.

**Comment by pierre-24** [comment]
> Mais ça me semble être un bon "good first bug" [...]

Toutafé. Si t'es motivé, je t'en prie :)

**Comment by Anto59290** [comment]
La PR en question semble avoir été mergée, on devrait pouvoir fermer ce ticket.
