### ISSUE TITLE
[Forum] Ordre des sujets suivis

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#329]
Je suis en train de refaire les templates du forum et je vois que les sujets suivis sont divisés en deux groupes : 
- non-lus
- lus

Et qu'ils sont affichés d'abord tous les non-lus et ensuite les lus. Je ne trouve pas ça très judicieux. Un ordre chronologique global serait préférable selon-moi. En l'état actuel, tu ne peux pas laisser couler un topic dans ta liste des sujets-suivis, tu es obligé de "Ne plus suivre" ou d'aller le lire.

Si quelqu'un a un avis sur la question ça m'intéresse, car pour le coup ça me semble étrange comme façon de rendre les choses.

**Comment by SpaceFox** [comment]
Sur la préprod actuelle, j'ai bien les topics dans l'ordre chronologique.

**Comment by firm1** [comment]
Alex avait bien raison. Le problème est desormais resolu (voir le commit precedent pour l'exemple).

Merci je ferme
