### ISSUE TITLE
Mettre à jour l'installation de NodeJS

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#3294]
Il faudrait mettre à jour les instructions pour installer NodeJS. Je crois qu'actuellement elles sont désuètes car il faut NodeJS v4. @sandhose, j'ai raison ?

S'aider de [la documentation de NodeJS en anglais](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)

**Comment by aesteve** [comment]
:+1: 

Je l'ai fait récemment sur une nouvelle machine, je suis passé par [ici](https://github.com/nodesource/distributions) (c'est exactement la même commande)
