### ISSUE TITLE
Meta-ticket : les pages les plus sensibles de ZdS en terme de performance

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3296]
Les pages (techniques) les plus vues sur ZdS sont :
1. L'affichage d'une page de contenu (~34% des pages affichées)
2. L'affichage d'un sujet du forum (~27% des pages affichées)
3. La page d'accueil (~17% des pages affichées, et en général le premier contact avec le site)
4. L'affichage d'un forum (~8% des pages affichées)

Pourquoi cette liste ? Pour deux raisons :
1. Si on veut améliorer nos performances, c'est sur ces pages que doit porter l'effort
2. On doit faire attention en modifiant ces pages de ne pas provoquer de grosse régression en performance

Issues existantes en lien en rapport avec celle-ci : 
- Requêtes lentes sur la page d'accueil des forums #3269
- Vérifier les requêtes SQL faites par les différentes pages #3149
- Requêtes dans le fichier des Slow Queries MySQL #2964

**Comment by firm1** [comment]
Pour compléter le ticket, dans l'optique de définir (s'il le faut) une priorité, la vitesse à laquelle sont chargées certaines de ces pages (stats munin du mercredi 13/01/2016 entre 10h et 22h).

> L'affichage d'une page de contenu

| Type | Nom du contenu | Temps moyenne de chargement | Temps min de chargement | Temps max de chargement |
| --- | --- | --- | --- | --- |
| Bigtuto | Photoshop | **0.33** sec | 0.22 sec | 4.96 sec |
| Minituto | - | **0.63** sec | 0.49 sec | 2.05 sec |

> L'affichage d'un sujet du forum

| Topic | Temps moyenne de chargement | Temps min de chargement | Temps max de chargement |
| --- | --- | --- | --- |
| Les petits pixels | **0.69** sec | 0.55 sec | 1.88 sec |

> La page d'accueil

| Temps moyenne de chargement | Temps min de chargement | Temps max de chargement |
| --- | --- | --- |
| **0.38** sec | 0.27 sec | 1.17 sec |

> L'affichage d'un forum

| Forum | Temps moyenne de chargement | Temps min de chargement | Temps max de chargement |
| --- | --- | --- | --- |
| Accueil des forum | **0.63** sec | 0.16 sec | 2.00 sec |

**Comment by SpaceFox** [comment]
Je ne comprends pas trop où tu veux en venir, mais soit.

**Comment by firm1** [comment]
ça concerne surtout le point qui dit:

> Si on veut améliorer nos performances, c'est sur ces pages que doit porter l'effort

Je rajouterais donc : si on n'a pas le temps de temps de porter l'effort sur ces 4 pages et qu'il faut en choisir, il vaut mieux se concentrer sur l'affichage d'un minituto et/ou d'un sujet de forum en priorité par rapport autres.

**Comment by SpaceFox** [comment]
Plus exactement, l'effort devrait se porter sur les pages dans l'ordre du premier message, puisqu'elles y sont triées par importance d'impact.

Il me semble aussi que depuis la ZEP-12, afficher un mini-tuto, une page de big-tuto et un article, c'est la même chose (@artragis, tu confirmes ?)

**Comment by artragis** [comment]
en terme de process, oui. Mais l'impact sur les perfs sera globalement :
- Article <=> fort (car l'article a en plus beaucoup de messages en moyenne
  et de votes)
- Mini tuto <=> au pire comme pour l'article, au mieux comme pour le moyen
  tuto
- Moyen/Big tuto <=> faible, avec un impact encore plus faible pour les
  bigs tuto

Pourquoi les demandes de perfs vont-elles à l'inverse de la taille des
contenus?
- plus un contenu est petit, plus il a de discussion sur sa page
- quand un contenu est monopage il se tappe à lui tout seul tout le process
  bdd ET tout le process demandeur d'IOPS pour afficher le contenu (bien que
  celui-ci doit pouvoir être mis en cache, c'est pour ça que la zep-12 a été
  faite)

VOilà

**Comment by artragis** [comment]
Etat des perfs après la v16:

| Page désirée | Moyenne sur les dernière 48h | Moyenne sur le dernier mois | Moyenne sur l'année | variation /mois | variation /année |
| --- | --- | --- | --- | --- | --- |
| Accueil | 320ms | 360ms | 400ms | -12% | -20% |
| Accueil des forums | 470ms | 530ms | 540ms | -11% | -12% |
| Catégorie de forum | 450ms | 520ms | 720ms | -14% | -37.5% (grosse baisse lors du changement de serveur, seconde baisse lors de la v16) |
| Un topic | 610ms | 680ms | 880ms | -10% | -30% (grosse baisse lors du changement de serveur. A peine visible avec la v16) |
| Un big tuto | 230ms | 290ms | 440ms | -20% | -48% (grosse baisse lors du changement de serveur mais réelle baisse avec la v13 puis la v16) |
| Un minituto | 430ms | 600ms | 640ms | -29%(v16powa) | -33% |
| Un article | 640ms | 1220ms | 1030ms | -48%(la v12 avait fait foiré un truc) | -38% |

**Comment by artragis** [comment]
Le ticket n'est plus à jour et on a un monitoring qui est pas dégueu sur les pages importantes. On peut peut être faire mieux mais faudra avoir un ticket par cas.
