### ISSUE TITLE
Modale disproportionnée à la suppression d'un MP

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3298]
Lorsqu'on veut supprimer un MP, la modale affichée à l'utilisateur est disproportionnée.

Informations supplémentaires :

Chrome 47.0.2526.111 (64-bit)
OS X Mavericks

![capture d ecran 2016-01-14 a 22 20 58](https://cloud.githubusercontent.com/assets/1913901/12337957/7395b834-bb0d-11e5-9396-54be3be7a673.png)

**Comment by gustavi** [comment]
Tu as bien build le front ? Chez moi ça passait bien.

**Comment by GerardPaligot** [comment]
Mouhaha ... euhm. :-°
