### ISSUE TITLE
MP author can be added as a participant

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#33]
Un auteur peut s'ajouter en tant que participant à son propre MP, du coup : 
- il apparait deux fois dans la liste des participants du MP
- il est notifié deux fois du même MP dans le menu MP en haut à droite du site

@dralliw, voir le MP que j'ai fait sur le site  : 
=> http://zestedesavoir.com/mp/4/test?page=1

**Comment by SpaceFox** [comment]
Je songe à une grande campagne sur les contraintes d'unicité ^^

**Comment by GerardPaligot** [comment]
Plus moyen de s'ajouter à un MP https://github.com/Taluu/ZesteDeSavoir/pull/35.

**Comment by firm1** [comment]
@GerardPaligot : il reste encore un bug à ce niveau. J'ai fais une MEP de ton pacth sur le site, et tu peux voir que j'ai [encore réussi à m'ajouter à la conversation](http://zestedesavoir.com/mp/7/test-final-apres-mep?page=1).

Pour le faire, il m'a suffit de majouter dans la liste des destinataires de mon propre message. Je pense que tu vois ou corriger ce bug.

Merci pour ton boulot.

**Comment by GerardPaligot** [comment]
Ok, fail. Je m'en occupe.

**Comment by SpaceFox** [comment]
Pour moi, le problème c'est juste qu'on a un champ "auteur" en plus du
champ "participants".

2013/12/23 Gerard notifications@github.com

**Comment by SpaceFox** [comment]
Du coup je vois deux solutions (je ne maîtrise pas assez Django pour les
implémenter et de toutes façons je ne l'ai pas encore installé) :
1. Le champ "auteur" est utile, du coup il faudrait f

**Comment by SpaceFox** [comment]
PUTAIN DE GMAIL !

... il faudrait faire une vérification quand on ajoute un participant : si
c'est l'auteur, on refuse.
1. Dégager le champ auteur, l'auteur est un participant comme les autres.

**Comment by GerardPaligot** [comment]
@SpaceFox Je m'étais fais une réflexion similaire lorsque j'avais relu le module du forum. Mais `author` a un sens puisque sinon, on ne peut pas savoir qui est l'auteur du topic et donc, qui peut modifier les informations du premier poste pour le forum et les participants pour les MPs.

**Comment by firm1** [comment]
@SpaceFox  dans l'absolu je suis d'accord avec toi, mais la distinction a été crée à l'origine uniquement pour gérer les droits sur le MP.

Si l'auteur devient un participant comme tous les autres, tout le monde peux tout faire dans le MP et ça peut devenir chiant.

Pour moi l'auteur est celui qui a les droits sur le MP, il peut ajouter des membres, supprimer des membres, etc. Ce que n'importe qui d'autre ne doit pas être censé faire

**Comment by firm1** [comment]
@GerardPaligot 

> puisque sinon, on ne peut pas savoir qui est l'auteur du topic et donc, qui peut modifier les informations du premier poste pour le forum et les participants pour les MPs

En fait, si c'est le cas, on peut toujours savoir qui est l'auteur du premier post en faisant `get_first_post().author` ce qui m'avait amener à créer ce champ est bel et bien le problème de droit.
On peut aussi faire une table qui gére les droits dans un MP pour corriger ce problème, mais je trouvais ça trop hard

**Comment by GerardPaligot** [comment]
@dralliw Ouaip mais ça fait pas mal de requêtes en plus alors que c'est quelque chose qui va devoir être utilisé très régulièrement.

**Comment by firm1** [comment]
Oui et c'est pour toutes ces raisons que malgré moi j'ai fais la distinction author/participants.

**Comment by firm1** [comment]
Bon bah, @GerardPaligot nous a fait un bon fix. C'est mergé, c'est en ligne. Je ferme.

**Comment by Taluu** [comment]
Sinon, avoir le champ author, oui... Mais qui est en fait une FK vers la table des participants. En plus d'avoir tous les membres du MP dans une seule table (et pas un truc fragmenté), on a une liaison auteur => participant, qui lui donne donc des droits supplémentaires... ?

**Comment by firm1** [comment]
@Taluu je ne sais pas si c'est la fatigue, mais j'ai du mal à comprendre ce que tu dis. Tu peux me l'écrire d'une façon plus technique ?

**Comment by Taluu** [comment]
En gros, on aurait une one to many entre la table des sujets de MPs (un champ author, original_participant, ...) vers la table des participants, qui elle-même a une relation many to one vers la tables des users.

En somme, ça permettrait d'avoir _tous_ les participants dans la table, et ne pas exclure l'auteur... Empêchant ainsi via une unique key (ou un truc du genre) un doublon dans la table des participants.

Par contre, ça peut risquer de faire une jointure de plus pour les opérations générales, donc au final, je ne sais pas  si ça vaut pas mieux que de faire un contrôle à l'arrache comme c'est fait actuellement...

**Comment by firm1** [comment]
> Par contre, ça peut risquer de faire une jointure de plus pour les opérations générales,

C'est justement là que j'avais un doute. C'est bien ce que je pensais, on jouera avec des jointures alors qu'on peut se permettre de gérer ça comme c'est fait actuellement, conceptuellement pas propre, mais optimale.
