### ISSUE TITLE
Améliorer l'aide Markdown

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3300]
Une idée piquée à GitLab : au lieu d'afficher un bouton « Afficher l'aide Markdown » (sur lequel on est obligés de cliquer pour avoir une aide quelconque) sous les boutons de zones de rédaction en Markdown, on affiche :

> Truc Markdown : Ici une astuce Markdown aléatoire sur une ligne

(Exemple : `Markdown tip: Make a horizontal line using three or more hyphens ---, asterisks ***, or underscores ___`)

Le « Markdown » de « Truc Markdown » est un lien vers la doc complète.

Il faudrait évidemment imaginer une liste de trucs à afficher.

Avantages : On affiche directement un conseil, on peut apprendre des trucs à tout le monde, ça donne plus envie de cliquer que juste « Afficher l'aide ».

**Comment by Vayel** [comment]
Est-ce que ça ne risque pas d'embêter ceux n'ayant pas besoin de ces conseils ?

**Comment by SpaceFox** [comment]
Non, c'est comme le « Attach files by dragging & dropping or ￼ selecting them. » sur Github. En fait même quelqu'un qui utilise souvent le markdown peut apprendre des trucs peu connus, en fonction de ce qu'il y a dans les conseils.

**Comment by Eskimon** [comment]
Je suis très pour cette evo !

**Comment by pierre-24** [comment]
ça peut toujours être sympa :p

**Comment by Situphen** [comment]
Je plussoie aussi !

**Comment by Anto59290** [comment]
Quitte à s'inspirer on peut directement regarder la source ici : https://gitlab.com/gitlab-org/gitlab-ce/commit/9c0229732aee0edeac0896d6a62faea8a449199c . On y trouve nottament la liste des conseils ;)

**Comment by Anto59290** [comment]
A noter que en faisant cette modif cela rend obsolete #2014 et #3354. Je veut bien m'en occuper si @Situphen est ok.

**Comment by Situphen** [comment]
Go go go alors ! ;)
