### ISSUE TITLE
MAJ le certificat HTTPS de la bêta

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3303]
Le certificat HTTPS de la bêta est arrivé à expiration… le 15/01/2016. Évidemment je fais mon déploiement le 16/01/2016 à 00:05…
1. Pourquoi on le découvre maintenant ? Normalement on est prévenus non ?
2. Qui a les accès pour le renouveler ?

Ping @Un-Cornichon @Ge0

**Comment by gustavi** [comment]
On a pas un wildcard ?

**Comment by DevHugo** [comment]
Faudrait voir si on peut utiliser [let's encrypt](https://letsencrypt.org/) dans le futur

**Comment by SpaceFox** [comment]
> On a pas un wildcard ?

Qu'on me corrige si je dis une connerie, mais de mémoire un certificat wildcard coûte une blinde.

> Faudrait voir si on peut utiliser let's encrypt dans le futur

Il faut y réfléchir. @Un-Cornichon avait l'air de dire qu'il y avait quand même quelques inconvénients.

**Comment by WinXaito** [comment]
> > Faudrait voir si on peut utiliser let's encrypt dans le futur
> 
> Il faut y réfléchir. @Un-Cornichon avait l'air de dire qu'il y avait quand même quelques inconvénients.

Lesquelles ?

**Comment by gustavi** [comment]
@SpaceFox oui, ne vaudrait-il pas demander un coup de pouce à Gandi là dessus ? cf. https://www.gandi.net/soutient/. On sait jamais, ça peut passer.

**Comment by SpaceFox** [comment]
On a déjà essayé lors du changement de serveur, et on a jamais eu de réponse :(

**Comment by gustavi** [comment]
Je suis pour une relance, ça ne mange pas de pain ! Un message sur Twitter en mode « Eh Gandi, on est une asso qui permet de partage de connaissances librement, vous proposez quoi pour nous ? On vous a envoyer une demande écrite mais pas de nouvelle :/ » ça peut le faire. Enfin bref, je pense qu'o peut creuser là dessus.

**Comment by DevHugo** [comment]
Jamais utilisé let's encrypt en production mais sur mon serveur perso, ça marchait bien. Ça reste un service en beta donc normalement c'est dangereux de l'utiliser en production.

**Comment by GerardPaligot** [comment]
@Un-Cornichon @SpaceFox Comment débloquer cette issue ? Elle est plus que urgente puisqu'elle est la source principale du blocage actuel vers la prochaine release.

**Comment by SpaceFox** [comment]
J'en ai aucune idée, les membres du bureau n'ont pas les infos pour le certificat ou ne répondent pas…  peut-être qu'il faudrait utiliser let's encrypt, au moins pour débloquer.

**Comment by GerardPaligot** [comment]
Je suis assez pour l'usage de Let's Encrypt sur la bêta. Le projet semble soutenu par [beaucoup de monde](https://letsencrypt.org/) (dont notre [hébergeur](https://letsencrypt.org/2015/12/21/ovh-sponsorship.html)), le projet est [open-source](https://github.com/letsencrypt/letsencrypt) et en plus, dispose d'une [grosse suite de tests, d'une doc, d'un build au vert sur Travis](https://github.com/letsencrypt/letsencrypt#links), etc.

C'est sans doute pas la meilleure idée pour de la production mais notre serveur de bêta n'est pas sujet aux mêmes contraintes.

**Comment by DevHugo** [comment]
Attention avec les soucis de [hsts](https://fr.wikipedia.org/wiki/HTTP_Strict_Transport_Security)

**Comment by Fumble** [comment]
Et manque de pot, le membre du Bureau qui répond assez rapidement, c'est celui qui a le moins d'info...

SpaceFox, si tu valides l'utilisation de Let's Encrypt, considère que c'est bon pour le Bureau. On ne va pas rester bloqué 3 plombes en attendant que les deux autres se réveillent.

**Comment by Eskimon** [comment]
En tant que membre du CA et CdP (pour le moment  ^^ ) je donne aussi mon aval pour cette décision :)

**Comment by SpaceFox** [comment]
Le certificat est renouvelé, merci @Ge0 :)
