### ISSUE TITLE
Le lien dans les mails (mp) est erroné

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3306]
**À VÉRIFIER POST ZEP-24**

Il ne renvoie plus au dernier message mais seulement au sujet de la conversation.

@GerardPaligot vous corrigé ça dans la ZEP-24 ?

**Comment by GerardPaligot** [comment]
Si tu parles du mail envoyé à la création d'un MP, ça a toujours été le cas.
Si tu parles du mail envoyé lorsqu'un nouveau message est posté dans un MP et que tu as renseigné dans tes paramètres que tu voulais recevoir des mails à chaque nouveau message, j'en ai aucune idée.

Dans la ZEP, je vérifie simplement qu'un mail est envoyé mais je l'envoie de la même manière que post ZEP-24 et avec les mêmes infos.

**Comment by GerardPaligot** [comment]
Après, c'est à tester quand même si c'est corrigé dans ma PR.

**Comment by gustavi** [comment]
OK merci, en fait je pense que c'est un souci de la méthode qui récupère l'URL ou un problème de contexte. En tous cas c'est simple à corriger si quelqu'un veut faire ça.

Au passage on a encore des fonctions sans aucun commentaire :/

**Comment by GerardPaligot** [comment]
Le bug tu te relèves est bien dans ce cas là n'est ce pas ?

> Si tu parles du mail envoyé lorsqu'un nouveau message est posté dans un MP et que tu as renseigné dans tes paramètres que tu voulais recevoir des mails à chaque nouveau message, j'en ai aucune idée.

**Comment by gustavi** [comment]
Quand je reçoit un email je n'ai pas le bon lien en fait.

**Comment by GerardPaligot** [comment]
Je viens de tester :
- A la création d'un MP, le lien pointe vers le premier message de la conversation.
- Quand un nouveau message est posté, le lien pointe vers le message en question.

Donc, corrigé dans ma PR.

**Comment by GerardPaligot** [comment]
Mail reçu à la création :

```
Bonjour admin,


user vous a envoyé un message privé sur Zeste de Savoir.

Pour le lire, cliquez ou recopiez l'url suivante : http://127.0.0.1:8000/mp/1/titre/messages/?page=1#p1


Cordialement,

L'équipe de Zeste de Savoir
```

Mail reçu à un nouveau message :

```
Bonjour user,


admin vous a envoyé un message privé sur Zeste de Savoir.

Pour le lire, cliquez ou recopiez l'url suivante : http://127.0.0.1:8000/mp/1/titre/messages/?page=1#p2


Cordialement,

L'équipe de Zeste de Savoir
```

**Comment by gustavi** [comment]
OK, je laisse ouvert et on check ça dans la ZEP-24 :)

**Comment by GerardPaligot** [comment]
Je rajoute cette issue dans ma PR ZEP-24.

**Comment by gustavi** [comment]
Mergé dans ZEP-24.
