### ISSUE TITLE
Renommer les variables nommées « type »

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3309]
Parce que `type` est une fonction par défaut.

**Comment by Situphen** [comment]
D'après (la documentation](https://docs.python.org/2/library/keyword.html), la liste est disponible dans `keyword.kwlist`. Mais `type` n'en fait pas parti (que ce soit pour Python2 ou Python3).

**Comment by gustavi** [comment]
Au temps pour moi, il s'agit d'une fonction et non d'un mot clé, j'ai rédigé mon message un peu rapidement.

https://docs.python.org/3/library/functions.html#built-in-functions

**Comment by Situphen** [comment]
On renomme les "type" par quoi ?

**Comment by gustavi** [comment]
En général on met `type_`.

**Comment by artragis** [comment]
publishable_content_type peut être sympa aussi :p

**Comment by gustavi** [comment]
C'est un poil plus long :p

**Comment by gustavi** [comment]
Ça a été corrigé au fur et à mesure ici, ce n'est plus pertinent.
