### ISSUE TITLE
Changer la documentation de la recherche avec la PR de spacefox

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#3310]
Cette partie de la documentation est fausse et nécessite d'être ré-écrite: 

> « Aujourd'hui, l'indexation est réalisée toutes les trentaines de minutes, sur le serveur de production. 
> Tout le contenu est ré-indexé à chaque fois, ce qui prend 100 pourcents du processus toutes les 5 
> minutes. Des solutions sont présentes dans la documentation d'Haystack (en), sans qu'on puisse 
> réellement les appliquer. »

**Comment by pierre-24** [comment]
A disparu :)
