### ISSUE TITLE
On reçoit deux emails lors d'une inscription

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#3312]
Salut,

J'avoue je ne plus me souvenir du comportement avant mais il me semble que c'était pas le cas avant Aujourd'hui, on reçoit au moins deux mails quand on s'inscrit:
- Le mail de confirmation d'inscription
- Un mail pour nous signaler  que l'on a un mp de Clem.

Le deuxième mail est t-il vraiment nécessaire ?

**Comment by Emeric54** [comment]
Ça ne me choque pas.

De plus, le mail pour signaler que l'on a un MP de Clem n'est envoyé qu'une fois que l'inscription a été validée.

**Comment by GerardPaligot** [comment]
Que dit le MP de Clem ?

**Comment by GerardPaligot** [comment]
Après une rapide recherche dans le code, est-ce que tu pourrais me confirmer la procédure :
1. Le membre fait son inscription. Il reçoit un e-mail pour confirmer.
2. Le membre consulte ses mails et confirme son inscription.
3. Le membre a créé son compte, nous lui envoyons un MP de bienvenue et le même message par mail.

Si telle est la procédure, cela me semble l'usage courant.

**Comment by DevHugo** [comment]
Il t'en manque un dans la troisième étape.

Tu as trois messages, si tu compte le MP. 
- Tu as le MP de bienvenue ; 
- Un mail pour te prévenir que tu as un nouveau MP ; 
- Un mail de bienvenue.

Les deux mails en questions reçu en plus lors de l'inscription: 

> « Bonjour Nope,
> 
> Vous vous êtes inscrit sur Zeste de Savoir et nous vous en remercions. En étant membre de notre 
> communauté, vous aurez la possibilité de rédiger des tutoriels et des articles que vous pourrez 
> ensuite publier et ainsi de rendre vos connaissances accessibles au plus grand nombre. Vous 
> pourrez également échanger avec les autres membres sur nos forums !
> 
> Il ne vous reste plus qu'à activer votre profil ! Pour ce faire, visitez ce lien.
> 
> A très bientôt !
> 
> Cordialement,
> 
> L'équipe Zeste de Savoir » 

Deuxième mail: 

> « Bonjour Nope,
> 
> Clem vous a envoyé un message privé sur Zeste de Savoir.
> 
> Pour le lire, cliquez ici.
> 
> Cordialement,
> 
> L'équipe Zeste de Savoir »

**Comment by Emeric54** [comment]
Du coup, que proposerais-tu ?

C'est vrai que le mail de validation peut être un peu répétitif avec le MP de Clem, mais encore une fois, je ne trouve pas ça trop dérangeant.

**Comment by GerardPaligot** [comment]
En fait, la méthode `send_mp` possède une argument `send_by_email`. Il suffit de retrouver la bonne invocation vers cette méthode et de changer le paramètre de `True` à `False`. Mais je n'ai pas le temps de le chercher. :)

**Comment by Emeric54** [comment]
Ok. J'essaie de PR ça ce soir, si ça convient à tout le monde bien sûr (?).

**Comment by GerardPaligot** [comment]
Fais toi plaisir ! ^^
