### ISSUE TITLE
[beta][v16][rc1] L'affichage d'une partie d'un contenu public est cassé

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3315]
Version : 16-RC1
### lien

https://zestedesavoir.com/tutoriels/757/la-fabrication-numerique/1079_arduino/
### screen

![good-beta](https://cloud.githubusercontent.com/assets/6066015/12481973/17738320-c04d-11e5-966a-379d0585f3d3.PNG)
### lien

https://beta.zestedesavoir.com/tutoriels/714/la-fabrication-numerique/1079_arduino/
### screen

![bad-beta](https://cloud.githubusercontent.com/assets/6066015/12481979/260c8fb2-c04d-11e5-9d28-55ae5ae71b8f.PNG)

Comme on peut le voir sur la version beta, l'affichage ne va pas en s’arrangeant.

_It's smell like a regression_

**Comment by sandhose** [comment]
Problème côté templates, le markup est pas le même: http://imgur.com/a/crqcP

A priori, c'est ce commit le fautif (à vérifier, c'est vraiment chelou): https://github.com/zestedesavoir/zds-site/commit/2238c21ee9d2b1f56e5067abffaf975f3ddeed40

**Comment by pierre-24** [comment]
Tordu, j'était convaincu d'avoir QA ça correctement (mais c'était bien une PR d'artragis)

**Comment by artragis** [comment]
ça va être chaud à corriger ça.

**Comment by artragis** [comment]
> Comme on peut le voir sur la version beta, l'affichage ne va pas en s’arrangeant.

Bon, pour revenir sur cette petite phrase je voudrai quand même qu'on réfléchisse un peu à ce uqe c'est que "s'arranger". 

Actuellement passer de la page "sommaire général" à la page "partei" impose un changement de style fort dans la présentation des titres. Sur la béta on a une certaines cohérence.

Attention, je ne nie pas qu'il y a un bug : les titres sont trop gros. Mais là je trouve qu'on a été dans le sens de l'unification et non d'une régression. Pire c'est exactement ce vers quoi on **voulait** aller quand j'ai pris en charge ce bug.

Perso j'enlèverai le tag "régression" et mettrais "bug". Je vais tenter de voir avec @sandhose pour voir pourquoi alors qu'on a tout fait pour unifier les tags html on se retrouve avec des trucs qui ont des tailles différentes.

En attendant @GerardPaligot et @pierre-24 vous qui êtes les nouveaux chefs de projets, pensez vous qu'on soit dans une régression du point de vue UX (pdv firm1) ou dans une unification buggée (pdv moi même)

**Comment by pierre-24** [comment]
> Pire c'est exactement ce vers quoi on voulait aller quand j'ai pris en charge ce bug.

Sans vouloir défendre Firm1, c'est effectivement ce qu'on voulait pour le sommaire des **moyen**-tutos, or le screen est issus du sommaire d'un big-tuto (pas de celui de la partie d'un big tuto), et du coup ... L'ancien affichage était bien le bon, c'est donc bien une régression :)

Il serait juste bon de faire des rapport de bugs plus explicites :)

**Comment by GerardPaligot** [comment]
Hormis le problème de front évident dans les titres et les liens soulignés d'office, ta question @artragis est légitime. Par contre, j'ai peur que tu ne proposes pas de revenir à un affichage [prod](https://cloud.githubusercontent.com/assets/6066015/12481973/17738320-c04d-11e5-966a-379d0585f3d3.PNG) quand on consulte un big tutoriel.

Grillé par @pierre-24. :)

**Comment by artragis** [comment]
D'où ma question. Si vous pensez qu'on doit garder l'affichage prod pour
les big tuto on agira en conséquence, j'ai juste pas envie de me casser la
tête ou d'embêter les devs front pour développer un truc dont on n'a pas
envie à la fin.

Le 28 janvier 2016 à 14:04, Gérard Paligot notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
Je te confirme. Pour les bigs tutos, on garde le visuel actuel de la prod. Pour les moyens tutos, on propose le visuel que tu proposes de la bêta.

**Comment by sandhose** [comment]
Ca me parait assez incohérent niveau UX comme choix, en plus du fait que AMHA, la visualisation d'un conteneur reste une vue très peu utilisée par les utilisateur (ça sert en gros dans le fil d'ariane ; je pense pas qu'un utilisateur lambda clique sur une partie directement au lieu de directement sur le chapitre)

**Comment by SpaceFox** [comment]
Personnellement je préfère la cohérence de l'expérience utilisateur à un affichage iso-prod.

**Comment by firm1** [comment]
J'ai l'impression que tout le monde ne comprend pas le problème. Si je fais
un récap ça donne :
- Aujourd'hui en prod on a :
  - Pour les big tuto :
    - le sommaire du tuto s'affiche sur **2** colonnes
    - le sommaire d'une partie s'affiche sur **2** colonnes [c'est ce
      cas qui est concerné par mon ticket]
    - le sommaire du chapitre est dans l'introduction.
  - Pour les moyens tuto:
    - le sommaire du tuto s'affiche sur **1** colonnes ('fin c'est
      censé etre ainsi car il y'a un bug dessus pour les tutos online)
    - le sommaire d'un chapitre s'affiche dans l'introduction
  - Pour les minitutos:
    - le sommaire du tuto s'affiche dans l'introduction.

Le truc bien avec l'affichage du sommaire sur 2 colonnes c'est qu'on n'a
pas besoin de scroller sur les petits écrans et c'est pour cela que pour
moi le comportement idéal serait de rester sur 2 colonnes. Pour moi,
uniformiser l'UX signifie rester sur 2 colonnes pour les sommaires. Les
sommaires sur 1 colonnes (dont j'ai du mal a voir l'intéret) sont apparus
avec l'arrivée des moyens tuto (jusqu'ici ça ne faisait pas parti de l'UX)
