### ISSUE TITLE
[Beta v16] Il manque des commandes pour prendre en compte le timer solr

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3316]
Il semblerait que la modification de la commande d'indexation solr ne soit pas prise en compte, parce que le timer systemd n'a pas été redémarré ou que sais-je.

Mis à part le fait que ce soit plus lourd à écrire et plus chiant à modifier, on a vraiment une bonne raison d'être passé aux timers systemd à la place des tâches cron pour cette fonctionnalité ?

**Comment by artragis** [comment]
@DevHugo 

PS @SpaceFox : si fix je peux créer, il faut que je mette ça où dans le code?

**Comment by SpaceFox** [comment]
Dans le update.md

**Comment by firm1** [comment]
@SpaceFox tu penses que cette issue est liée au fait que je ne retrouve pas le dernier tuto publié (les date en php) via la recherche sur le beta ?

**Comment by SpaceFox** [comment]
Ton tuto a été publié quand ?

**Comment by SpaceFox** [comment]
Pas la moindre idée.

**Comment by firm1** [comment]
**Publié : lundi 25 janvier 2016** donc après la mise en beta

**Comment by DevHugo** [comment]
Tu parle de quel tuto exactement ?

**Comment by firm1** [comment]
De [celui-ci](https://beta.zestedesavoir.com/tutoriels/216/gerer-les-dates-avec-php/)

**Comment by artragis** [comment]
Pourtant @SpaceFox je vois des trucs dans le [update.md](https://github.com/zestedesavoir/zds-site/blob/release-v16/update.md#indexation-delta-des-forums).

**Comment by SpaceFox** [comment]
Ouais, je pige pas. Faudrait scruter les logs.

**Comment by artragis** [comment]
Du coup ça peut être fermer @SpaceFox ?

**Comment by GerardPaligot** [comment]
Mise à part l'issue sur le déplacement des sections d'un tutoriel, cette issue est la dernière concernée par la v16.

@SpaceFox Que faut-il faire ici ? Qui est compétent pour répondre à ta question sur ton premier message ?

**Comment by SpaceFox** [comment]
Apparemment en fait ça marche : j'ai bien le mot à la con que j'ai mis dans un forum, et le tuto publié cet après-midi en bêta est bien indexé. Étrange…
