### ISSUE TITLE
[beta][v16][rc1] nombre de contenus en validation incohérent

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3317]
Version 16 RC1.

Sur la beta, lorsque je filtre pour avoir les contenus réservés, j'en ai 19 (cf [lien](https://beta.zestedesavoir.com/validations/?type=reserved)). Lorsque je filtre pour avoir les contenus non réservés en validation, j'en ai 27 (cf [lien](https://beta.zestedesavoir.com/validations/?type=orphan)). Ce qui ferais normalement un total de **46** tutoriel en validation.

Cependant, lorsque j'annule mon filtre (cf [lien](https://beta.zestedesavoir.com/validations/)) j'ai bien un total de 49 contenus.

Le problème n'existant pas en prod, je taggue comme régression.

**Comment by artragis** [comment]
Sur la béta, les contenus en question sont les suivants : 

```
/contenus/441/configurer-une-bibliotheque-sous-windows-avec-mingw-ou-code-blocks-en-langage-c/?version=791cbc33d4031ab98e246901f44daf16c3c2dcac'
 '/contenus/450/introduction-aux-graphiques-en-python-avec-matplotlib-pyplot/?version=d7e35d6dc99ccbf931c4152aa15bb3db7e9a48ba'
 '/contenus/388/utiliser-proprement-lecriture-mathematique-en-latex/?version=0bec5b8121ac133ed2e8d879d5ec249fd8cd929f
```

Ce sont tous sans exception des tutos de Karnaj. Ce sont les seuls tutos de Karnaj en validation sur la beta.

**Comment by artragis** [comment]
Le bug n'existe plus après synchro. Possiblement un reste d'un vieux test qui avait mis la bdd dans un sale état.

**Comment by artragis** [comment]
@Eskimon 2beClosed

**Comment by GerardPaligot** [comment]
Peut-être une confirmation de @firm1 ?

**Comment by firm1** [comment]
Je veux bien confirmer, mais le problème est que [j'ai une erreur 500 dans la zone de validation](https://github.com/zestedesavoir/zds-site/issues/3351). D'après ce que tu dis @artragis tu n'a pas l'erreur 500. Tu pourrais aller le confirmer sur l'issue ?

**Comment by SpaceFox** [comment]
En tous cas je confirme qu'en tant que superutilisateur, j'en ai une aussi.

**Comment by artragis** [comment]
je l'ai !

2016-02-04 16:20 GMT+01:00 SpaceFox notifications@github.com:

**Comment by Emeric54** [comment]
Du coup, on peut aussi fermer ici @Situphen.

**Comment by artragis** [comment]
On attend confirmation de firm1
Mais pour cela il faut qu'une RC3 soit lancée

**Comment by Emeric54** [comment]
Ah oui, oups...

**Comment by artragis** [comment]
comme la rc3 est sortie, on peut y jeter un coup d'oeil please?

**Comment by firm1** [comment]
Le bug est corrigé dans la RC3.

Merci @artragis
