### ISSUE TITLE
[beta][v16][rc1] Les contenus extra (pdf, epub, etc.) ne sont pas générés lors de la 2nde validation

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3318]
Version 16 RC1.

Scénario de test : 
- Je publie un tutoriel pris en zone de validation (J'ai pris celui sur les bases de la prog)
- Le tutoriel est réservé, publié.
- Je modifie le sous-titre du tutoriel et redemande sa validation (2 min après la première publication)
- Je le réserver puis publie une fois de plus le tutoriel sans cocher la case maj majeur, donc en version mineure
- Le tutoriel est publié cette fois, mais après 5 min, toujours pas de signe d'un pdf ni epub, etc.

**Comment by artragis** [comment]
le watchdog est-il lancé?

**Comment by SpaceFox** [comment]
Oui :

```
zds@vps41247:~$ pstree -npa
systemd,1 -z      
[...]
  └─python,30835 manage.py publication_watchdog
      ├─{python},30842
      ├─{python},30843
      ├─{python},30844
      └─{python},30845
```

**Comment by artragis** [comment]
hum, strange.

et le settings_prod met bien la policy à watchdog? (je sais que c'est une question con mais je préfère éviter de perdre du temps)
et le watchdog directory est bien configuré (je sais plus si je l'ai mis dans le update celui-là)?

ensuite, c'est bien **tous** les extra qui ne sont pas générés, ou bien seulement le pdf? (on sait jamais parfois le pdf ne peut pas être généré pour des raisons de syntaxe.)

**Comment by firm1** [comment]
> ensuite, c'est bien tous les extra qui ne sont pas générés, ou bien seulement le pdf?

J'ai la réponse à celle-ci. C'est bien tous les extras qui ne sont pas générés. Alors qu'il a été généré à la première validation.

**Comment by artragis** [comment]
Je vais regarder plus avant.

**Comment by artragis** [comment]
j'ai la vague impression que c'est parce que le fichier de publication n'est pas supprimé la première fois.

@SpaceFox  : tu peux faire un ls du dossier watchdog-build (en supposant que tu n'as pas changé les settigns pour ça)

**Comment by SpaceFox** [comment]
```
zds@vps41247:/opt/zdsenv/ZesteDeSavoir$ grep policy zds/settings_prod.py
ZDS_APP["content"]["extra_content_generation_policy"] = 'WATCHDOG'
zds@vps41247:/opt/zdsenv/ZesteDeSavoir$ ls -lah watchdog-build/
total 12K
drwxr-xr-x  2 zds zds 4,0K janv. 21 15:06 .
drwxr-xr-x 21 zds zds 4,0K janv. 21 14:11 ..
-rw-r--r--  1 zds zds  256 janv. 21 15:09 les-bases-de-la-programmation
```

**Comment by artragis** [comment]
@firm1 c'est bien le tuto "les base de la programmation" que tu as tenté 
de publier?

**Comment by GerardPaligot** [comment]
@artragis Oui : https://beta.zestedesavoir.com/tutoriels/515/les-bases-de-la-programmation/
