### ISSUE TITLE
[beta][v16][rc1] modale mal affichée lors de la supression d'une gallerie

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3319]
Version : 16 RC1
Navigateur : Firefox 43
OS : Windows
Zoom : 100%

Scénario de test : 
- Je vais dans une de mes gallerie
- Je clique sur supprimer une galerie
- Voici le rendu

![bug-gallerie](https://cloud.githubusercontent.com/assets/6066015/12482902/76d57db4-c052-11e5-92bf-42123849eaaf.PNG)

**Comment by artragis** [comment]
surtout elle vient d'où cette modale? En prod je n'ai pas.

**Comment by GerardPaligot** [comment]
Elle a été rajoutée dans la nouvelle release. Raison pour laquelle c'est un bug et non pas une régression. :)

**Comment by artragis** [comment]
Ok.
Bon, j'ai la vague impression que c'est parce que le texte "Supprimer la gallerie?" n'est pas mis dans un bloc de texte (p) ni même un label.

SOit dit en passant cette checkbox devrait être invisible ! au moins on aurait juste le bouton "supprimer" pour nous.

**Comment by Eskimon** [comment]
Quand un texte est invisible il me semble que c'est parce que la chaine n'est pas internationalisé. Ou ce situe cette checkbox/formulaire/chaine dans le code ?

**Comment by SpaceFox** [comment]
Corrigé.
