### ISSUE TITLE
[beta][v16][rc1] Les images de l'éditeur JS sont bloqués par la sécurité coté serveur

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3320]
Version : 16 RC1
Navigateur : Firefox 43
OS : Windows
Zoom : 100%

On voit sur le screen ci-dessous que les images de l'éditeur ne s'affichent pas parce qu'elle sont bloqués par la sécurité coté serveur (en tout cas c'est ce que me dit ma console JS).

![security-bug](https://cloud.githubusercontent.com/assets/6066015/12483231/05e707ba-c054-11e5-8726-bf2a62bbf462.PNG)

**Comment by firm1** [comment]
J'ai exactement le même problème pour visualiser le captcha, ce qui m'empêche de m'inscrire sur le site.

**Comment by GerardPaligot** [comment]
Si le bug est avéré, cela commence à devenir bloquant (en partant du principe que l'infra beta == prod).

**Comment by SpaceFox** [comment]
Je confirme le bug, et en rajoute un : pour moi ce captcha devait être désactivé par défaut.

**Comment by Emeric54** [comment]
Pourtant, dans les `settings`, `USE_CAPTCHA` est bien à `False` ?

**Comment by artragis** [comment]
il est fort probable que le settings_prod soit le même que celui qu'on a utilisé pour tester le captcha à l'époque, c'est donc simplement ça qu'i lfaut changer.

on a un problème dans la définition de la csp : d'une part une des directive est fausse et d'autre part on dirait que certaine simages sont interdites.

**Comment by Eskimon** [comment]
J'avais effectivement laisse la captcha a true en preprod et false en produit afin qu'il soit testable tout le temps en preprod.

**Comment by sandhose** [comment]
J'ai ouvert une PR pour fixer les icônes de l'éditeur, et modifié la conf CSP pour le captcha. Je ferais un recap du header final pour la CSP avant la MEP ; faut encore tester tous les trucs type video & autre

**Comment by artragis** [comment]
comme c'est mergé, ça peut être fermé non?

**Comment by GerardPaligot** [comment]
Comme la PR semble être attachée à cette issue et que la QA a été OK. Oui.
