### ISSUE TITLE
[beta][v16][rc1] Déplacer un extrait d'un contenu publié rend le tutoriel indisponible pour de bon

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3328]
Version : le problème arrive au moins sur la v16-RC1 (qui est actuellement en béta), vous comprendrez que je ne vais pas essayer de le reproduire en prod pour tester.

C'est assez complexe à reproduire, mais dans la suite je vais noter en gras les points commun entre mon cas et le cas de yoch qui ont permis de reproduire le bug.

Prérequis : 
- Avoir un contenu au format **tutoriel** et **mini-tuto**
- Ce contenu doit être **publié**

Scénario : 
- Allez dans le menu "Mes tutoriels"
- Sélectionnez le tutoriel qui correspond aux prérequis
- Scrollez jusqu'à la **2e section** et cliquez sur "Déplacer"
- Dans la modale le choix proposé est "Monter", **ne le changez pas**, cliquez simplement sur le bouton "Déplacer"
- Pouf ... une 404
- Le vrai problème c'est qu'une fois qu'on obtient cette 404, on ne peut plus accéder à son tutoriel en mode rédaction.

Je note en bug, car je ne sais pas si c'est reproductible en prod. Je n'ai pas assez d'élement pour savoir s'il est bloquant ou pas.

**Comment by artragis** [comment]
je n'arrive pas à reproduire le bug en local.

**Comment by artragis** [comment]
Non plus sur la béta.

**Comment by artragis** [comment]
Je relance : @GerardPaligot et moi-même n'arrivons pas à reproduire, y a-t-il d'autres cas svp qu'on puisse diagnostiquer?
@firm1 le tuto que tu as utilisé pour tester existait-il sur la béta **avant** la release ou bien est-ce un nouveau tuto de test? Dans le premier cas il se peut que ça soit un tuto qui avait détecter une erreur dans une ancienne béta, on n'a pas fait de resync entretemps.

**Comment by GerardPaligot** [comment]
Est-ce qu'on peut disposer d'une archive sur laquelle on rencontre le problème quand on lance le scénario ?

**Comment by firm1** [comment]
> @firm1 le tuto que tu as utilisé pour tester existait-il sur la béta avant la release ou bien est-ce un nouveau tuto de test?

Le tuto existait avant la release.

Pour info, yoch a eu [le même problème](https://zestedesavoir.com/forums/sujet/5181/et-ce-fut-la-v16-et-les-testeurs-testerent/#p95427).

@GerardPaligot je ne peux plus télécharger l'archive en question puisque j'ai une 404 en allant sur le tutoriel.

**Comment by GerardPaligot** [comment]
@firm1 Oui mais tu nous dis savoir reproduire le tuto non ?

> Prérequis :
> - Avoir un contenu au format tutoriel et mini-tuto
> - Ce contenu doit être publié

**Comment by artragis** [comment]
même si je n'en suis pas sûr, il est probable que ces tutos soient victimes
de nos anciens tests et soient dans un état déjà bien instables.

**Comment by firm1** [comment]
@GerardPaligot non justement, les prérequis sont les conditions dans lesquels le bug est arrivé. Mais effectivement l'un des prérequis semble être que les tutos aient été publiés avant la release. Peut-être qu'on est dans le cas décris par @artragis  (tutos instables), mais je n'ai aucune idée de la véracité du truc.

Idéalement il faudrait faire une copie de la prod sur la beta et refaire les tests.

**Comment by artragis** [comment]
@spacefox, si un jour tu as une vingt-cinquième heure dans ta journée?

**Comment by artragis** [comment]
Bon apparemment quelqu'un a reproduit ça en prod bien que je ne comprenne pas comment car la prod est peu verbeuse quant aux erreurs 404.

**Comment by artragis** [comment]
on peut réessayer svp? maintenant que c'est isoprod, l'hypothèse de on a tout fait cassé avant ne pourrait plus être retenue.

**Comment by GerardPaligot** [comment]
Pensez à télécharger l'archive avant de rouler le scénario. Cela pourrait peut-être permettre de répéter le bug en local.

**Comment by firm1** [comment]
Après la synchro de la prod <-> préprod au niveau datas, j'arrive toujours à **reproduire le bug** sur le même tuto. Impossible de savoir, si le problème vient de la v15 ou de la v16 (je n'ose pas tester en prod directement).

Mais cette fois çi, j'ai pensé à sauvegarder l'archive de mon tuto avant de tout casser : [comment-reussir-votre-entretien-dembauche-dump.zip](https://github.com/zestedesavoir/zds-site/files/117629/comment-reussir-votre-entretien-dembauche-dump.zip)

Je précise mon scénario de test :  
- Je vais dans mes tutoriels
- Je sélectionne mon tutoriel (qui je précise est déjà publié)
- Je clique sur "déplacer" sur la 2ème section
- Je clique sur le bouton "Déplacer" (c'était bien le choix 'monter' qui m'était affiché)
- BIM la 404 qui me rend mon tutoriel indisponible pour la rédaction.

Je commence à me demander si on devrait pas le tagguer en bloquant

**Comment by SpaceFox** [comment]
> je n'ose pas tester en prod directement

Heureusement.

C'est bloquant, en effet.

**Comment by artragis** [comment]
et comme on n'a pas de log, je sais même pas ce qui a lancé l'erreur 404...

**Comment by firm1** [comment]
Est-ce que quelqu'un arrive a reproduire mon problème avec l'archive que j'ai linkée ci-dessus ? ça permettrait d'identifier la cause du souci.

**Comment by artragis** [comment]
nope.

@spacefox: (ou toute personne qui a les droits, dont @firm1 je crois) as-tu activé les logs sur la béta?

De même peux-tu nous donner le résultat de : 

```
cat manifest.json
ls
```

lorsque tu es dans le dépôt du tutoriel (celui de contents-private).

**Comment by artragis** [comment]
Bon suite à un test avec sandhose, note à moi même pour régler le problème : 
- dans tous les mixins qui sélectionne object faire un "repare auto" du sha_draft en cas de problème : en effet c'est ça qui cause l'indisponibilité, le sha a été supprimé à un moment
- trouver dans la branche de déplacement ce qui peut causer une suppression du sha.

Notons que vue la non répétabilité du bug avec un nouveau tuto, je pense que c'est parce que ce dernier a de gros problèmes à la base. Du coup la procédure de reparation devrait suffire.

**Comment by artragis** [comment]
Le bug n'est pas corrigé.

Et le pire c'est qu'on ne comprend toujours pas pourquoi il arrive dans ce cas très précis.

**Comment by artragis** [comment]
@firm1 @sandhose @SpaceFox @GerardPaligot je vais faire une première PR qui aura pour but de mettre des vrais messages d'erreur pour les http404 et du logging. Comme ça on pourra comprendre comment le bug a lieu.

**Comment by artragis** [comment]
bon on a réussi à trouver ce qui rendait le tuto indisponible : 

lorsqu'on déplace une section dans un minituto (et je suppose une partie dans un autre type de tuto) et que le tuto possède un titre avec un apostrophe le slug est changé à cause des conflits d'algorithme de slugification il semblerait.

Je vais donc modifier le "force update slug" pour que ça n'arrive plus dans le cadre d'une maj.

**Comment by GerardPaligot** [comment]
@artragis Congrats! J'ai hâte d'avoir la PR pour finaliser notre release et enchainer sur la suivante !

**Comment by GerardPaligot** [comment]
Enfin corrigé, on voit le bout de cette release !
