### ISSUE TITLE
[beta][v16] Impossible de dépublier un article

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3329]
Prérequis:
- être staff

Scénario: 
- Je vais sur l'article suivant : https://beta.zestedesavoir.com/articles/180/sortie-de-python-3-5/
- je tente de le dépublier (j'ai bien renseigner le motif de dépublication)
- lorsque je valide la dé-publication, j'ai une 404

On regardant l'historique de l'article, l'un des auteurs après publication, à modifié le titre de la version brouillon (cette modification n'a pas encore été publiée).

**Comment by Eskimon** [comment]
Ca mériterait presque d'être tagué bloquant ca (presque)

**Comment by artragis** [comment]
@gustavi : c'est un bug présent depuis la v12, pas une régression.

By the way j'ai un fix qui arrive.

**Comment by firm1** [comment]
La PR qui corrige cette issue a été mergée dans dev plutot que dans la branche de release. Ce qui fait que le correctif n'a pas été déployé dans la RC2.

Je réouvre ici ( à fermer quand le correctif sera sur la bonne branche)

**Comment by gustavi** [comment]
Merci @firm1. J'avoue que les autres PR étaient OK et que j'ai oublié de vérifier celle-ci. Je serai plus vigilent à l'avenir.

En tous cas c'est corrigé.
