### ISSUE TITLE
Pouvoir prévisualiser introduction et conclusion lors de la rédaction de contenu

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#3333]
[Reporté par Dominus Carnufex sur le forum](http://zestedesavoir.com/forums/sujet/5206/pas-de-previsualisation-pour-les-intros-et-conclusions/?page=1#p95703) :

> Ouais, j’abuse un peu en qualifiant ça de bogue. Mais il est assez pénible de ne pas avoir de prévisualisation lors de la rédaction des intros et conclusions de tutos/articles et parties/chapitres d’iceux, ça rend la relecture beaucoup plus difficile (je viens encore de laisser passer une faute, et bien sûr, je ne m’en suis rendu compte qu’après la mise à jour de la bêta, alors ça m’énerve… ^^ ).

**Comment by pierre-24** [comment]
Grâce à @Anto59290, c'est bon :)
