### ISSUE TITLE
Code de suivi Google Analytics

### ISSUE THREAD

**Issue by ChantyTaguan** [zestedesavoir/zds-site#3335]
Hello,

J'ai un avertissement dans Google Analytics : 

**Code de suivi manquant**
Aucun code de suivi valide n'a été trouvé pour l'URL par défaut http://zestedesavoir.com/ de la propriété ZDS Site. Veuillez vérifier que les balises de vos pages comportent une version compatible du code de suivi.

**Comment by Eskimon** [comment]
Ping @spacefox

**Comment by vhf** [comment]
Euh, c'est pas parce qu'il se retrouve inséré dynamiquement seulement dans le cas où la cookie-banner est accepté ou un truc du genre ? @sandhose

**Comment by ChantyTaguan** [comment]
En tout cas c'est très récent comme problème.

**Comment by SpaceFox** [comment]
J'ai l'impression que c'est depuis que j'ai remis le code de suivi de la
Webmaster Console (qui d'ailleurs ne sors que des chiffres douteux…)

Le 26 janvier 2016 à 14:14, ChantyTaguan notifications@github.com a écrit
:

**Comment by gustavi** [comment]
Ça ne vient pas du code en lui même car pas de modif depuis plusieurs mois

**Comment by GerardPaligot** [comment]
C'est pas un bug grâce cette issue ? L'avertissement est toujours présent @ChantyTaguan ?

**Comment by ChantyTaguan** [comment]
Yep, l'avertissement est toujours là !

**Comment by gustavi** [comment]
Quelqu'un  a une idée ? Je pense que ça vient d'une config côté GA plutôt que du code qui n'a pas bougé (ou alors ce souci est très vieux).

@ChantyTaguan tu peux nous donner plus d'info avec ce que décrit https://support.google.com/analytics/answer/6006306?hl=fr#trackingcode ? Il se peut que ce ne soit que quelques pages qui soient concernées.

**Comment by gustavi** [comment]
@ChantyTaguan ?

**Comment by gustavi** [comment]
OK je crois avoir compris ce qui se passe ici : GA ne détecte pas le code de suivit car on ne l'affiche que lorsque les cookies ont été acceptés. Ça vous semble correct ?

**Comment by AmarOk1412** [comment]
@gustavi fixé ça ?
