### ISSUE TITLE
[API] Imposer une limite aux endpoints de recherche

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3337]
Je propose de limiter les endpoints de recherche aux requêtes de >= 3 char.

Donc ceci devrait pas passer : /api/membres/?search=a

mais ça oui : /api/membres/?search=aaa

Et refléter ça dans le frontend, par exemple dans l'autocomplétion de destinataire de MP.

**Comment by GerardPaligot** [comment]
Quel code HTTP devons-nous renvoyer en dessous de 3 caractères ?

**Comment by aesteve** [comment]
Je mettrais une 400.

**Comment by vhf** [comment]
Ou 413.

**Comment by AmauryCarrade** [comment]
> Ou 413.

413 Payload Too Large n'est, je trouve, pas très cohérent pour une requête trop _petite_ ; 400 me semble plus logique, ou 412 en effet (ci-dessous).

**Comment by SpaceFox** [comment]
412 sinon.

**Comment by aesteve** [comment]
413 non. **Request entity** too large. C'est pas "ce que tu me demandes de faire est trop balaise" mais "ce que tu m'envoies est trop balaise" (exemple : un stream, un byte-range, ...). Là, ce qu'il envoie est compréhensible, mais entraîne trop de traitement. Vaut mieux une 400 (qui explicite clairement : ce que tu m'envoies DANS la requête n'est pas bon et je vais te dire pourquoi) qu'une 413 qui porte à confusion.

412 : mouais/non.

On l'utilise généralement plutôt pour les headers de la requête https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.13
Donc ça porte à confusion aussi. 

Un truc pas trop trop mal foutu : http://racksburg.com/choosing-an-http-status-code/

**Comment by vhf** [comment]
400 va pas trop parce que le serveur comprend correctement la requête.

La RFC de 412 dit que ça s'applique aux cas où les headers spécifient une condition que le serveur ne peut pas remplir.

413 je me suis planté, il s'agit d'une requête trop grande, pas d'une réponse trop grande.

Je propose 403 : le serveur a pigé la requête mais refuse d'y répondre. Et l'authentification n'aide pas, et il ne faut pas réessayer : https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.4

**Comment by aesteve** [comment]
Ça me choque pas que le serveur renvoie une 400 pour se protéger même s'il a compris la requête. 

C'est souvent le cas notamment quand on envoie une chaîne alors que le backend attend un int par exemple. Pourtant la requête est bonne, en soit, c'est du JSON bien formaté.

Là on peut considérer que le serveur ne comprend pas. Quoi, une chaîne de 3 caractères ? Je sais pas, chez moi un champ de recherche ça fait 4 caractères ou plus.

Aussi, 400 ça veut dire, pour un client : ce que tu as envoyé n'est pas correct. (et après le message d'erreur aide). Je pense pas qu'il faille chercher midi à 14h non plus.

Après, 403 ça ne me choque pas non plus. Mais perso si en tant que client je fais cette requête et je prends une 403, le premier truc que je vais faire c'est refaire un login et regarder mes permissions. Si dans la liste de permissions y'a "effectuer une recherche" je soumets un ticket au développeur de l'API, sans chercher plus loin.

**Comment by vhf** [comment]
@aesteve Cette histoire de permission c'est plutôt 401 il semblerait.

> 403: The request was a valid request, but the **server is refusing to respond to it**. Unlike a 401 Unauthorized response, **authenticating will make no difference**.

Et la RFC https://tools.ietf.org/html/rfc2616#section-10.4.4 suggère d'y inclure la raison, histoire d'expliquer au dev son erreur.

**Comment by aesteve** [comment]
401 c'est que tu essaies d'accéder à une ressource qui nécessite authentification alors que tu n'es pas authentifié.

403 : tu es authentifié, mais le serveur considère que tu n'as pas les permissions nécessaires pour effectuer l'action.

Quand je parlais de me relogger, c'était pour regarder le contenu de la requête de login (qui généralement donne les permissions associées : ex : "faire une recherche").

Après si tu tiens à une 403 vas-y. Je trouve juste que c'est tout sauf clair. Là où une 400 fait tilt dans la tête de 90% des développeurs "ah tiens j'ai envoyé de la merde". 403 ça fait tilt : "ah tiens j'ai pas le droit ? wtf".

**Comment by vhf** [comment]
Merci pour les explications !

Moi c'est égal. 400 ou 403. @SpaceFox qui choisira. :)

**Comment by AmauryCarrade** [comment]
Je trouve (avant je pensais, maintenant je suis convaincu) également que 400 est un meilleur choix. Après, la décision finale ne me revient pas :) .

**Comment by Anto59290** [comment]
Quid des gens ayant un pseudo de deux caractères comme notre ami ici : https://zestedesavoir.com/membres/voir/Sy/ ?

**Comment by GerardPaligot** [comment]
A mon avis, tu n'as pas vraiment besoin de l'autocompletion pour ce membre. :)

**Comment by Anto59290** [comment]
Certes, mais ca veut dire que l'api (en filtrage recherche) ne renvoit jamais les membres dont le pseudo est de deux caractères. Dans l'autocomplétion ce n'est pas un problème, mais _in fine_ c'est exclure des membres de la recherche sans raison. Que ce passe t il si une application tierce fait des appels sur l'API ZdS.

**Comment by Arnaud-D** [comment]
Pour moi, on devrait pouvoir chercher n'importe quelle longueur, justement pour confirmer qu'un membre dont on pense connaître le pseudo existe bien, même si son pseudo est court.
