### ISSUE TITLE
Mieux ordonner les membres dans la recherche de l'API

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#3338]
Alors que je trollais @GerardPaligot à l'instant, j'ai découvert que quand on utilise l'autocomplétion sur `Andr`, eh bé on tombe pas sur `Andr0`, mais sur une partie 10 derniers inscrits contenant les lettres `a`, `n`, `d` et `r` dans leur pseudo

![](http://i.imgur.com/bFMlHxU.png)

Il faudrait que l'ordre dans la recherche soit sensible à la casse + mieux ordonné au niveau de si les lettres sont pas dans l'ordre. Typiquement, **a**lexa**ndr**a n'aurait pas dû passer avant `Andr0`

Pour moi, pour la recherche `Andr`, ça aurait dû être ordonné dans ce sans la: `Andr*` -> `andr*` -> `*Andr*` -> `*andr*` -> `*a*n*d*r*`

Donc en gros, si ça match avec le début de la chaine, c'est plus haut dans les résultat, et si en plus la casse correspond, c'est encore plus haut dans les résultats. En dernier, quand même garder du fuzzysearch. Mais à la fin, quoi.

**Comment by GerardPaligot** [comment]
Pour information, voici ce que donne la documentation de DRF à propos du filtre pour la recherche :

> The search behavior may be restricted by prepending various characters to the search_fields.
> - '^' Starts-with search.
> - '=' Exact matches.
> - '@' Full-text search. (Currently only supported Django's MySQL backend.)
> - '$' Regex search.
>   Source: [DRF](http://www.django-rest-framework.org/api-guide/filtering/#searchfilter)

Si aucune de ces recherches ne convient, il faudra développer notre propre filtre de recherche (ou étendre l'existant pour renseigner notre propre caractère).

**Comment by Arnaud-D** [comment]
Je ferme comme doublon de #6460.
