### ISSUE TITLE
Redimensionner les images des unes

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3339]
Aujourd'hui on a des images 400x400 alors qu'on les affiche en 228x228. Il faut un filtre avec solr,pour les afficher comme il faut.

cf https://gtmetrix.com/reports/zestedesavoir.com/dr5PCyFF

**Comment by pierre-24** [comment]
Tu veux dire "pillow", non ?

(mais je suis d'accord sur le principe)

**Comment by gustavi** [comment]
Je parlais de ça https://pypi.python.org/pypi/easy-thumbnails

Au temps pour moi, j'utilise une alternative sur mes projets persos

**Comment by pierre-24** [comment]
Oui, c'est ça qu'on emploi aussi (pillow est en dessous :) ).

**Comment by SpaceFox** [comment]
Corrigé et mergé.
