### ISSUE TITLE
[V16] [RC1] Les liens des sujets suivis sont cassés

### ISSUE THREAD

**Issue by AmauryCarrade** [zestedesavoir/zds-site#3340]
Les liens pointant vers les sujets suivis pointent vers la page courante et non le sujet suivi. Après vérification, l'attribut `href` est vide.

Je parle des liens ci-dessous, que l'on peut par exemple [retrouver ici](https://beta.zestedesavoir.com/forums/).

![Liens des sujets suivis](http://raw.carrade.eu/s/1453906624.png)

L'URL semble correctement retrouvée côté vue, ça ressemble à un problème de template ?
Je n'ai pas creusé beaucoup plus (le fait que je ne connaisse encore pas très bien Django et le code de ZdS n'aidant pas).

**Comment by pierre-24** [comment]
Je confirme, et c'est bien pénible :p

**Comment by artragis** [comment]
Hum, je crois savoir d'où ça vient. 
Je regarde au plus vite (donc demain).
