### ISSUE TITLE
La désinscription ne permet pas de supprimer les clées de l'api

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#3350]
Lorsque un membre se désinscrit, il serait bien de supprimer ses clées d'api.

**Comment by artragis** [comment]
@SpaceFox @andr0 bloquant non? possiblement faille de sécurité?

**Comment by GerardPaligot** [comment]
@artragis Tu peux un peu développer et expliquer en quoi cela pourrait être bloquant et/ou une faille de sécurité ?

**Comment by DevHugo** [comment]
C'est pas bloquant, au pire on peut révoquer à la main les clées donc ça serait plus pratique de le faire automatiquement. C'est tout.

C'est pas vraiment une faille de sécurité, tu peux rien accéder de plus. C'est juste que si le mec commence à faire nawak, on lui supprime ses clés manuellement.

**Comment by GerardPaligot** [comment]
Merci à @gustavi et @DevHugo !
