### ISSUE TITLE
[beta][v16][RC2] erreur 500 dans la zone de validation des contenus

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3351]
ça me parait vraiment bizarre, mais en tant que staff (et **superuser** ), en allant sur le lien : `https://beta.zestedesavoir.com/validations/` je me prend une erreur 500.

J'ignore si c'est à cause de la récente synchro des données prod vers beta qui aurait été mal faite, ou à cause d'un bug dans le code. Mais dans le doute, je taggue large on elèvera les tags quand on aura éliminé des possibilités.

**Comment by SpaceFox** [comment]
Même type de compte, même comportement ici.

**Comment by Situphen** [comment]
Merci @artragis :)
