### ISSUE TITLE
[beta][v16][rc2] Les vidéos sont bloquées par la sécurité coté serveur

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3352]
C'est un peu le même problème que l'issue #3320

En allant sur l'article : https://beta.zestedesavoir.com/articles/895/pourquoi-devons-nous-changer-de-televiseur-en-2016/ on ne voit pas la vidéo provenant de dailymotion. La console JS de mon navigateur me dit : `Content Security Policy: Les paramètres de la page ont empêché le chargement d'une ressource à https://www.dailymotion.com/embed/video/x36awni (« default-src https://beta.zestedesavoir.com »).`

**Comment by SpaceFox** [comment]
Sérieusement : je vais arrêter d'accepter les bidouilles qui permettent de « améliorer la sécurité » si elles n'ont pas de raison réelle et sérieuse d'exister. OK, on a une meilleur conf sur le HTTPS que certaines banques, mais en attendant on a beaucoup trop de merdes à cause de ça.

**Comment by artragis** [comment]
Depuis la dernière modif de @sandhose (qui annule la CSP), c'est reviendu.

**Comment by SpaceFox** [comment]
Parfait, merci @sandhose !
