### ISSUE TITLE
Marge à droite sur mobile sur le profil d'un membre

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#3353]
Bug disponible en production sur [mon profil](https://zestedesavoir.com/membres/voir/Situphen).

Rien n'est meilleur qu'une bonne image :

![tmp_8184-screenshot_20160204-235650-412675595](https://cloud.githubusercontent.com/assets/6664636/12832586/1da0632c-cb9b-11e5-98ec-e71d145fb6b8.png)

**Comment by gustavi** [comment]
Plus d'infos ? Tel, navigateur, versions ?

**Comment by Situphen** [comment]
Bug présent sur Firefox v44 sur Android
Bug non présent sur Chrome (dernière version) sur Android

**Comment by Situphen** [comment]
Je n'arrive plus à le reproduire, je ferme.
