### ISSUE TITLE
Le bouton "Afficher l'aide Markdown" s'affiche en double

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3354]
Version : v15.1
Navigateur : Chrome 48.0.2564.103 (64-bit)

---
1. Rendez-vous sur l'éditeur.
2. Coller (CTRL+V) du texte provenant de votre presse papier.
3. Constatez qu'un nouveau bouton "Afficher l'aide Markdown" s'affiche.

**Comment by Situphen** [comment]
Je ne réussi pas à reproduire le bug sur _Chromium_ 48.0.2564.82 (64-bit) sur desktop !
- Quel était le contenu de ton presse-papier ?
- Sur quelle page s'était ?
- Sur desktop ou mobile ?

**Comment by GerardPaligot** [comment]
Par exemple, tu crées un nouveau sujet et dans l'éditeur **vide** (sinon, le bug ne se reproduit pas), tu copies/colles ce que tu veux (moi, c'était "Test").

**Comment by Anto59290** [comment]
Pas moyen de reproduire ici non plus, c'est étrange. Peux tu donner plus de précision ? Ca se produit encore sur Chrome 49 ?

**Comment by gllmc** [comment]
Rendu obsolète par la nouvelle aide Markdown.
