### ISSUE TITLE
Mauvais affichage des forums sur mobile

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3359]
![image](https://user-images.githubusercontent.com/15378830/29638691-4ac16f38-8858-11e7-8c86-099d986d01c5.png)

(Contenus en cours de rédaction)

Firefox Android 44.0 - Samsung Galaxy S5 mini

*EDIT (motet-a) : J’ai mis l’image directement dans le Markdown*

**Comment by AmarOk1412** [comment]
Le second truc qui me choque en regardant comme ça c'est les chiffres, on ne sait absolument pas à quoi ils correspondent, je serais d'avis pour les enlever sur mobile.
