### ISSUE TITLE
[beta][v16][rc3] les contenus extras (pdf, epub, etc) ne sont plus générés à la publication

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3361]
J'ai publié le tutoriel [Des tableaux de variations et de signes avec LaTeX ](https://beta.zestedesavoir.com/tutoriels/439/des-tableaux-de-variations-et-de-signes-avec-latex/) sur le serveur de beta, mais malheureusement après plus de 5 minutes, la génération du pdf/epub/html ne s'est pas faite.

**Comment by GerardPaligot** [comment]
@artragis Comment ça se fait que cette régression soit possible ? Qu'est ce qu'il en est par rapport à ta précédente correction (https://github.com/zestedesavoir/zds-site/issues/3318) ?

**Comment by artragis** [comment]
le watchdog a-t-il été remis en route? Parce que comme il a été modifié si ça a pas été remis avec la RC3 moi je peux rien faire.

**Comment by GerardPaligot** [comment]
Alors pingons @SpaceFox ! :)

**Comment by GerardPaligot** [comment]
Sinon, je ne sais pas comment est déployé nos releases, mais il n'y a pas moyen d'intégrer la gestion de watchdog dans un script de release quelconque ? Histoire de ne plus devoir y penser à chaque release.

**Comment by artragis** [comment]
@spacefox a un script.

**Comment by SpaceFox** [comment]
J'ai suivi scrupuleusement les releases notes, et il n'y était pas question de relancer quoi que ce soit pour le déploiement de la RC3… La ligne `python manage.py publication_watchdog &` était déjà présente avant, donc je ne l'ai pas rejouée.

J'ajoute : 
1. que j'ai un doute sur la fiabilité de cette commande,
2. que le script est à ZdS et pas à moi et que donc il peut être PR comme le reste
3. qu'il n'a pas vocation à faire autre chose que du déploiement

**Comment by GerardPaligot** [comment]
> que j'ai un doute sur la fiabilité de cette commande,

Pour dire vrai, moi non plus mais nous avons mergé la fonctionnalité watchdog, il n'est donc plus vraiment question de douter de cette commande.

> que le script est à ZdS et pas à moi et que donc il peut être PR comme le reste

Nous sommes bien d'accord. **Je pense que l'objet de cette issue se situe sur ce point précis !** Je ping notre contributeur le plus compétent pour faire un truc un peu robuste (penser quand le service est déjà lancé, toussa, toussa) @artragis

**Comment by SpaceFox** [comment]
> Pour dire vrai, moi non plus mais nous avons mergé la fonctionnalité watchdog, il n'est donc plus vraiment question de douter de cette commande.

Je doute de la fiabilité de la _commande_, pas de la fonctionnalité. Pas exemple, je ne suis pas certain du tout que le processus soit conservé après la fermeture de la session qui l'a lancé…

**Comment by artragis** [comment]
Ah? je pensais naïvement qu'à chaque release on rejouait le scénario 
complet, ce qui explique donc notre principal problème.

PS : du coup il faudra ajouter la commande suivante : supprimer tous les 
fichiers présents dans le dossier watchdog-build.

**Comment by artragis** [comment]
Attendez, on m'a dit que tout allait être mis dans un service (ping 
@sandhose). Au pire, un screen fera tout à fait l'affaire !

**Comment by artragis** [comment]
@sandhose a fait un service.

Peux-tu juste faire une PR pour mettre ça dans les release note stp?

Le bug est réglé.

**Comment by artragis** [comment]
si @GerardPaligot ou @firm1 peuvent refaire le test puis fermer ça serait cool.

**Comment by GerardPaligot** [comment]
@artragis Je ne dispose pas des droits pour me publier malheureusement.

**Comment by artragis** [comment]
on peut fermer svp?

**Comment by GerardPaligot** [comment]
Toutafé, la [PR](https://github.com/zestedesavoir/zds-site/pull/3365) pour rajouter de la doc au service watchdog a été mergé. Je ferme.
