### ISSUE TITLE
[beta][v16][rc3] Typo dans l'entête d'un tutoriel avec plusieurs auteurs

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3362]
Lorsqu'on consulte un tutoriel avec plusieurs auteurs ([celui-ci](https://beta.zestedesavoir.com/tutoriels/757/la-fabrication-numerique/) par exemple), dans l'entête d'un tuto, on voit marqué "Auteur s : " avec un espace non justifié entre "Auteur" et "s".

Il faudrait supprimer cet espace

**Comment by GerardPaligot** [comment]
J'ai rajouté le tag "Facile". ^^

**Comment by gustavi** [comment]
C'est corrigé.
