### ISSUE TITLE
[beta][v16][rc3] Dans les commentaires des articles, l'affichage des +/-1 est aléatoire

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3363]
Navigateur Firefox 43
OS Windows 7

Je fais mon test sur ce [commentaire de Javier](https://beta.zestedesavoir.com/articles/895/pourquoi-devons-nous-changer-de-televiseur-en-2016/#p93139) en beta son équivalent en prod est [ici](https://zestedesavoir.com/articles/895/pourquoi-devons-nous-changer-de-televiseur-en-2016/#p93139).

Quand je plussoie le commentaire sur la beta, tout de suite après, j'ai ce rendu : 

![before-drama](https://cloud.githubusercontent.com/assets/6066015/12977577/d013071e-d0cb-11e5-8ff2-00f384cde146.PNG)

Ce qui est normal.

Par contre, lorsque j'actualise mon navigateur, sur le même commentaire, j'ai ce rendu (comme si je n'avais pas plussoyé le commentaire).

![after-drama](https://cloud.githubusercontent.com/assets/6066015/12977582/d6ce4eba-d0cb-11e5-9c0e-eb80c45bc143.PNG)
- Le problème n'est pas présent en prod
- Le problème ne se produit pas sur le forums

**Comment by SpaceFox** [comment]
[Cette version de Firefox n'est plus supportée](https://fr.wikipedia.org/wiki/Mozilla_Firefox#Historique_et_notes_des_sorties).

**Comment by firm1** [comment]
J'ignorai que le version 43 de firefox n'était plus supporté.

Bon bah j'ai le même bug sur le version 44 (ce qui est normal, vu que le problème se trouve dans les templates et pas forcément coté css/js)

**Comment by GerardPaligot** [comment]
Je confirme la regression sur Chrome version 48.0.2564.103 (64-bit).

**Comment by artragis** [comment]
Hum étrange, on n'est pas sensé avoir touché aux +/- dans cette release.

**Comment by gustavi** [comment]
Si on commence à plus supporter les versions "anciennes" de FF ça va être la merde. cf http://www.w3schools.com/browsers/browsers_firefox.asp

**Comment by firm1** [comment]
> Si on commence à plus supporter les versions "anciennes" de FF

La version 43 c'est quand même l'avant dernière version à l'heure actuelle de FF. Donc pas si vieux que ça :-°

**Comment by gustavi** [comment]
C'est bien ce que je disais !

**Comment by GerardPaligot** [comment]
Je ne pense pas que Spacefox voulait dire qu'on ne supportait plus cette version de FF, il semble simplement avoir vérifié si cette version de FF était encore maintenue par Mozilla ou pas.

@sandhose pourra le confirmer mais nous supportons toujours la version 43 de FF.

**Comment by SpaceFox** [comment]
La règle, **depuis le 1er jour**, c'est que si c'est plus supporté par l'éditeur, il n'y a plus de MAJ de sécurité et que c'est dangereux de naviguer avec un tel navigateur. Et que donc il n'y a aucune raison valable de naviguer avec ça, et donc qu'on ne va pas s'amuser à corriger des bugs **spécifiques** aux navigateurs périmés, qui sont de toutes façons condamnés à court terme.

Si ça vous fait chier de MAJ toutes les 6 semaines (ce qui est compréhensible), il y a les versions LTS/ESR pour ça.

PS : je contredis donc @GerardPaligot : c'est pas supporté par l'éditeur = ce n'est plus supporté par nous. Dans le sens où on ne corrige pas de bug spécifique à une telle version. Et donc que tout test fait avec une version non supportée ne sert à rien parce qu'on ne sait pas d'où vient le bug.

**Comment by gustavi** [comment]
Oui mais @SpaceFox faut se dire que la majorité des utilisateurs ont une version pas à jour de leur navigateur. Je suis OK pour qu'on dégage le support de IE & co. mais là on parle quand même de FF 43 ! Faut penser à toutes les entreprises, administrations, écoles, etc qui ont pas forcément du LTS et encore moins une version à jour.

**Comment by SpaceFox** [comment]
Je vais poser la question dans l'autre sens : combien de bugs spécifiques à une version non-supportée on a eu depuis le début du projet ?

**Comment by gustavi** [comment]
On règle ça avec la v18 ou pas @sandhose ?

**Comment by sandhose** [comment]
Oui
