### ISSUE TITLE
Les extensions des images sont perdues quand elles sont importées en groupe

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3366]
> Salut
> 
> J'avais plusieurs images a importer dans un article. J'essaie d'utiliser les miniatures ("Miniature + lien vers taille normale"). Quand j'importe les images une par une, pas de probleme.
> 
> [![](http://zestedesavoir.com/media/galleries/2910/cb49f8e8-9ef4-43cc-8aff-68bda1830dd8.png.120x120_q85_crop.png)](http://zestedesavoir.com/media/galleries/2910/cb49f8e8-9ef4-43cc-8aff-68bda1830dd8.png)
> 
> Pour importer plusieurs images, j'a cree un zip puis j'ai fait "Importer une archive". Les images sont bien crees dans la galerie et les miniatures correspondent bien aux images. Par contre, les images taille reelles ont perdu leur extensions ".png".
> 
> [![](http://zestedesavoir.com/media/galleries/2910/eedec6c0-6019-4433-a2de-09f124538410.nazara-02.120x120_q85_crop.png)](http://zestedesavoir.com/media/galleries/2910/eedec6c0-6019-4433-a2de-09f124538410.nazara-02)
> 
> Du coup, lorsque l'on clique sur la miniature, cela telecharge le fichier, mais n'affiche pas l'image. Si j'ajoute l'extention ".png" a ce fichier, l'image s'ouvre correctement (donc pas de probleme de fichier zip ou png corrompu).
> 
> Il semble que ce soit juste un probleme lors de la creation du nom du fichier image (l'image de depart s'apelle "nazara-xx.png" par exemple. Avec l'import une par une, l'image importee devient "cb49f8e8-9ef4-43cc-8aff-68bda1830dd8.png". Avec une archive, l'image devient "eedec6c0-6019-4433-a2de-09f124538410.nazara-02").
> 
> Merci

Source:[gbdivers](http://zestedesavoir.com/forums/sujet/5364/importer-une-archive-dans-la-galerie-dimages-supprime-les-extensions/?page=1#p98433)

**Comment by artragis** [comment]
il semblerait que l'erreur vienne d'ici : https://github.com/zestedesavoir/zds-site/blob/dev/zds/gallery/views.py#L463
