### ISSUE TITLE
Ajouter un thème sombre alternatif

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3372]
Proposition qui nous viens du [forum](https://zestedesavoir.com/forums/sujet/5055/un-mode-dark-pour-les-cours/) : 

> Je viens vous suggérer une petite idée, qui pourrai arranger plusieurs personnes, même si ça reste du gadget. En fait, serai-t-il possible de développer une fonctionnalité permettant de consulter les cours mais avec un fond sombre, en effet, moi personnellement je suis plus à l'aise avec un cours sur fond sombre, je trouve le blanc assez éblouissant, et gênant au bout de plusieurs heures.

Dans la suite du sujet on a quelques exemples assez agréables.

**Comment by Eskimon** [comment]
Ce ticket existe déjà, en mode zombie.... https://github.com/zestedesavoir/zds-site/issues/584 (donc doublon)

**Comment by Eragonfr** [comment]
Comment gérer ça? back-end ou front-end? via un script en js ou côté serveur en python? les préférences stockés en bdd ou dans un cookie?

**Comment by pierre-24** [comment]
Instinctivement, une idée me vient, mais je sais pas ce qu'elle vaut. On rajoute, en fonction de la préférence de l'utilisateur [une classe sur le body](https://github.com/zestedesavoir/zds-site/blob/dev/templates/base.html#L135). Puis, on s'amuse à redéfinir des choses

```css

body.theme-darker {
  background: #222;
}

body.theme-darker #sidebar {
  background: #244;
}

// etc
```

Par contre, gardons bien en tête quelques petites choses:

1. Une fois que c'est rajouté dans le code, c'est officiellement maintenu. 
2. Je suis plus sur si toutes les couleurs sont belles et bien définies TOTALEMENT dans un fichier à part (parce que ça rendrait les choses plus simples évidement). Sinon, c'est évidement un pré-requis.
3. Ça ouvre techniquement la porte à d'autres thèmes (sauf décision contraire). Voir #4771 :) (qui contient une base de ce que je propose, d'ailleurs)

**Comment by artragis** [comment]
les couleurs sont définies dans `assets/scss/variables/_colors.scss`

**Comment by pierre-24** [comment]
Oui, mais je crois me souvenir qu'il y avait encore des couleurs en dur qui trainait dans le code, d'où ma remarque ;)

**Comment by firm1** [comment]
Le fait de supporter ça, pousse a tester forcément toutes les PR sur le front sur 2 thème a chaque fois. Ça peut faire du boulot en plus mine de rien.

**Comment by pierre-24** [comment]
... À condition de chipoter le CSS. Parce que sinon, si le thème est bien fait, il devrait pouvoir s'adapter comme le vrai ^^

**Comment by Eragonfr** [comment]
Normalement un test sur le thème "white" doit être équivalent à un test du thème "dark"

**Comment by nils-van-zuijlen** [comment]
La seule chose que le thème "dark" doit changer, c'est les couleurs. Comme ça, il ne devrait pas y avoir de problèmes de compatibilité. La seule chose, c'est qu'à chaque modification des classes du thème clair, il faudra voir si le thème sombre a bien réagi et lui appliquer aussi ces modifications.

**Comment by firm1** [comment]
oui c'est ce que j'entendais par "il faudra tester les 2 thèmes a chaque changement du css". Pour le coup, mon avis n'est pas fixé là dessus

**Comment by nils-van-zuijlen** [comment]
Quand je dis "voir si le thème sombre a bien réagi", c'est juste de regarder un coup la page quand il est activé.

**Comment by Situphen** [comment]
Maintenir un thème sombre au thème clair actuel va demander beaucoup de boulot en plus ! Si vraiment ça intéresse des membres pourquoi pas, mais pour éviter la catastrophe je pense qu'il faut poser une condition : le thème sombre ne modifie **que** les variables des couleurs. Et un pré-requis c'est déjà de variabiliser toutes les couleurs actuelles, mais probablement d'écrire en dur les couleurs de fond par-ci et par-là (on utilise pour l'instant très souvent les couleurs par défaut du navigateur)

**Comment by artragis** [comment]
On ne le fera pas à cause de la difficulté technique, deplus on est zombie depuis 2 ans?
