### ISSUE TITLE
[beta][v16][rc3] les modales sur mobile ont perdu leur marge

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3377]
OS : Android
Navigateur : Firefox 44

Les marges des modales ont disparuent comme on peut le voir sur les screens.
### prod

![tmp_16893-screenshot_2016-02-16-18-37-35-552614848](https://cloud.githubusercontent.com/assets/6066015/13085112/ee8ac7a8-d4dc-11e5-9f96-2dfa981103ea.png)
### beta

![tmp_16893-screenshot_2016-02-16-18-36-09-659868498](https://cloud.githubusercontent.com/assets/6066015/13085130/fb55b4ac-d4dc-11e5-8098-742449b295bf.png)

**Comment by GerardPaligot** [comment]
@sandhose Tu sais mettre cette issue en priorité haute dans ta todo list ? Faut vraiment qu'on envoit notre release.

**Comment by GerardPaligot** [comment]
Merci à @orandin pour le fix, je ferme.
