### ISSUE TITLE
Switch the DBMS

### ISSUE THREAD

**Issue by Ge0** [zestedesavoir/zds-site#338]
On est présentement sur sqlite3, mais on n'a pas dit qu'on utiliserait postgreSQL à l'avenir ?

Quelqu'un a-t-il reconsidéré la question avant moi ?

**Comment by SpaceFox** [comment]
On est sur SQLite 3 en prod ?!
Si oui, il faut basculer sur postgreSQL (ou MySQL ou tout autre vrai SGBD).

2014-04-28 18:28 GMT+02:00 Geoffrey R. notifications@github.com:

**Comment by Ge0** [comment]
Il me semblait que c'était évident.

@geoffreyc tu veux bien t'occuper d'installer un Postgres ? Si besoin je peux te donner un coup de main, et un vrai coup de main cette fois-ci. :o)

**Comment by geoffreyc** [comment]
On est deja sous postgres AFAIK sur le prod (et la preprod aussi?) Firm1
confirm?

2014-04-28 17:33 GMT+01:00 Geoffrey R. notifications@github.com:

**Comment by geoffreyc** [comment]
Le "settings_prod.py":

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'zdsdb',
        'USER': 'zds',
        'PASSWORD': '******',
        'HOST': 'localhost',
        'PORT': '',
    }
}

2014-04-28 17:33 GMT+01:00 Geoffrey R. notifications@github.com:

**Comment by Ge0** [comment]
Ah c'est donc uniquement sur la préprod qu'y a sqlite ?

**Comment by geoffreyc** [comment]
Non non la preprod utilise ce fichier aussi

2014-04-28 17:36 GMT+01:00 Geoffrey R. notifications@github.com:

**Comment by firm1** [comment]
Comme la dit @geoffreyc ci-dessous, zds utilise une base de donnée postgresql en production comme en préproduction (sinon on aurait pas les performances actuelles).

En local on garde une base sqlite pour s'assurer que les contributeurs n'aient pas besoin d'installer un vrai sgbd pour pouvoir contribuer, mais ce n'est pas envisageable en environnement de production.

Donc voila, il y'a donc un fichier que seul celui qui se connecte sur le serveur peux voir, et c'est transparent pour tout le monde.

Voili, voilou. Je ferme donc l'issue.
