### ISSUE TITLE
Travis est au rouge sur le projet

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3381]
Pour une raison inconnue, Travis n'est plus au vert sur le projet zds-site. 

Plus d'info sur l'erreur, rendez-vous sur le [build travis](https://travis-ci.org/zestedesavoir/zds-site/builds/110236942).

**Comment by pierre-24** [comment]
Mmh, ça coince sur du pdf, mais ça viens pas de nous : https://travis-ci.org/zestedesavoir/zds-site/jobs/110236944#L246 ... Faut aller râler sur le CTAN :o

**Comment by pierre-24** [comment]
(ouais, en fait c'est pire que ça, juste avant, il dit qu'il peut pas accéder aux miroirs du CTAN)

**Comment by GerardPaligot** [comment]
Merci @pierre-24 ! :)
