### ISSUE TITLE
Problème d'intégrité de notre BDD

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3382]
Via Sentry on a quelque chose d'assez inquiétant : 

https://sentry.sandhose.fr/zeste-de-savoir/backend/issues/360/

```
IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`zdsdb`.`tutorial_tutorial`, CONSTRAINT `gallery_id_refs_id_343d69dd` FOREIGN KEY (`gallery_id`) REFERENCES `gallery_gallery` (`id`))')
(27 additional frame(s) were not displayed)
...
  File "django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
```

**Comment by pierre-24** [comment]
Parce que je touche plus grand chose depuis un certain temps, ça a abouti, cette histoire de virer tuto/article pré-ZEP12, au final ? Parce que ça m'as l'air directement lié :o

**Comment by pierre-24** [comment]
(ping @artragis )

**Comment by artragis** [comment]
Ouai je pense qu'on a un problème avec la V16 car on a ajouté les auteurs (on = moi) dans le published content. Faut prévoir que tous les objets soient supprimés.
D'ailleurs il se peut que le cas qui nous intéresse date de très longtemps puisque là ce sont les galleries qui merdent.

**Comment by gustavi** [comment]
Doublon de https://github.com/zestedesavoir/zds-site/issues/3448
