### ISSUE TITLE
Impossible de retrouver mon tutoriel après tentative d'ajout d'un auteur

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3383]
J'ai essayé d'ajouter un auteur à [mon tutoriel](https://zestedesavoir.com/tutoriels/391/comment-reussir-votre-entretien-dembauche/), et en validant sur le bouton, je me suis pris une 404 et maintenant je n'ai plus accès à la version brouillon de mon tutoriel (je me prend une 404 sur la version brouillon).

ça semble lié à la problématique que j'ai eu pour les déplacement avec la V16.

**Comment by GerardPaligot** [comment]
Malheureusement, c'est même bloquant puisque tu ne peux plus accéder à ton contenu pour y contribuer.

**Comment by pierre-24** [comment]
J'attend que Sentry nous dise quelque chose, mais j'ai peu d'espoir, si c'était une 404 :/

**Comment by Emeric54** [comment]
Malheureusement, un problème qui me semble similaire chez moi : en voulant valider les modifications que j'ai apportées sur un article, je me suis pris une 404. Depuis, je me prends également une 404 lorsque j'essaye d'y accéder.

**Comment by Emeric54** [comment]
Un bug similaire sur le forum : https://zestedesavoir.com/forums/sujet/5440/404-sur-un-tuto-en-redaction/

**Comment by gustavi** [comment]
Bon on passe à un stade ARCHI-BLOQUANT là. Je suis dessus, n'hésitez pas à passer sur IRC ou à commenter ici si vous avez une idée.

**Comment by gustavi** [comment]
Liste de ce qui peut créer un erreur 404 :    
- pk invalide  
- pas de `versioned` associé  
- slug invalide  

cf `zds.tutorialv2.mixins.SingleContentViewMixin`.

**Remarque importante** : tous les contenus avec des 404 contiennent une « ' » dans leur titre. Hasard ? Je creuse.

**Comment by gustavi** [comment]
OK je confirme.

Avant v16 : linterface-dadministration-avec-django

Après v16 : l-interface-d-administration-avec-django

**Comment by artragis** [comment]
putin c'est toujours ce putin de bug.
Je ne sais pas d'où il vient mais il a fait mal avec les déplacement. Maintenant il fait mal avec les auteurs.

**Comment by pierre-24** [comment]
Oh nooooooooooooooooon, pas (encore) ce bug ! Comment, c'est encore possible ? On a mis à jour `uuslug` ?

**Comment by GerardPaligot** [comment]
@pierre-24 Malheureusement oui. Par contre, @gustavi a émit une piste intéressante à travers cette [méthode](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/utils.py#L628-L652) qui utilise `uuslug` ou `django` pour générer un slug (et ce, pour des soucis de compatibilité je suppose).

L'avis d'un connaisseur sur ce module serait une bonne indication.

D'après une analyse de @artragis, il semblerait bien aussi que la cause est une "désynchronisation" des slugs entre le repo (niveau système de fichier) et le slug enregistré en base de données. @gustavi propose cette [commande](http://paste.awesom.eu/3CKH) pour tout remettre d'équerre mais elle est à tester.

**Comment by pierre-24** [comment]
> et ce, pour des soucis de compatibilité je suppose

Toutafé: tout un moment, le slug de Django et le slug généré par `uuslug` n'étaient pas exactement les même au niveau des apostrophes, justement. Alors évidement, si le responsable d'`uuslug` a décidé de changer ça en cours de route, eh bien c'est chiant ;)

Pour ce qui est de la commande de gustavi, à priori oui, sauf que j'aurais plutôt vu une solution à base de `os.move()`, puisque dès qu'on va redemander un slug, l’erreur va nous retomber dessus. De plus, on ne sais pas encore si ce bug se traduit aussi sur les conteneur/extraits.

C'est la m*** :p

**Comment by GerardPaligot** [comment]
Il n'y a eu aucune mise à jour de `uuslug`. Par contre, il est possible que dans un cas précis, vous utilisez le générateur de slug de django alors que vous devriez utiliser `uuslug`.

**Comment by DevHugo** [comment]
Il m'a l'air bizarre ce uuslug: https://github.com/zestedesavoir/zds-site/blob/42875047d7f94e330033474f93186b739c1bc121/zds/tutorialv2/models/models_database.py#L26 .

Pas un expert dans le domaine mais quelqu'un peut regarder rapidement ? pas de pc, semaine de partiel !

**Comment by artragis** [comment]
Pourquoi bizarre?

2016-02-22 17:02 GMT+01:00 Hugo Courtecuisse notifications@github.com:

**Comment by DevHugo** [comment]
Car on utilise slugify (from uuslug import uuslug vs from uuslug import slugify) , d'habitude:
- https://github.com/zestedesavoir/zds-site/blob/42875047d7f94e330033474f93186b739c1bc121/zds/tutorialv2/models/models_versioned.py#L15
- https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_contents.py#L44
- https://github.com/zestedesavoir/zds-site/blob/dd8e28affc05f023dd1dda4d1a5f230c82a61d46/zds/tutorialv2/utils.py#L15

**Comment by artragis** [comment]
Bah voilà on l'a trouvé le bug \o/ merci l'ami !

2016-02-22 17:35 GMT+01:00 Hugo Courtecuisse notifications@github.com:

**Comment by GerardPaligot** [comment]
@DevHugo Je suis content que tu restes quand même dans les parages. :-°

**Comment by pierre-24** [comment]
Je veux pas casser votre joie, mais vous êtes sûr, sur celle là ? (magnifique usage de l'accent circonflexe, ici, #réformeOrthographe)

Parce que sur ce fichier, `uuslug` est utilisé [là](https://github.com/zestedesavoir/zds-site/blob/42875047d7f94e330033474f93186b739c1bc121/zds/tutorialv2/models/models_database.py#L140), comme il me semble qu'il doit l'être (uuslug appelant `slugify`, mais se permettant d'abord un _check_ en base de donnée pour vérifier qu'il est unique). Non ?

Après, y'a ce [`if kwargs.pop(...)`](https://github.com/zestedesavoir/zds-site/blob/42875047d7f94e330033474f93186b739c1bc121/zds/tutorialv2/models/models_database.py#L139) dont je me souviens pas, donc peut être qu'il y a à creuser par là.

**Comment by artragis** [comment]
Le kwargs.pop vient du bugfix durant la béta.

Le 22 février 2016 à 17:57, Pierre Beaujean notifications@github.com a
écrit :

**Comment by DevHugo** [comment]
Je suis pas sur d'avoir bien compris ton point de vue @pierre-24 si je te l’interprète mal toutes mes excuses. 

Si on regarde cette ligne [là](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_contents.py#L1646), on voit que quand on bouge une partie, on ne passe pas dans le if qui cause des soucis (celui que tu vient de citer) et du coup ça marche ce qui à fait passer la QA.

Mais dans les autres cas, [ajout d'un auteur](https://github.com/zestedesavoir/zds-site/blob/42875047d7f94e330033474f93186b739c1bc121/zds/tutorialv2/views/views_contents.py#L1705) et [validation](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_validations.py#L400), on met pas le slug le `force_slug_update` à False et du coup, on passe dans le if et du coup souci.

Après j'ai rien testé donc euh j'affirme rien ^^, je donne juste mon avis théorique sur une question :p. 
(La bonne différence entre pratique et théorie <3)

**Comment by pierre-24** [comment]
Quand on lit le code source de `uuslug`, [on voit ici qu'à la fin, y'a un appel à `slugify`](https://github.com/un33k/django-uuslug/blob/master/uuslug/uuslug.py#L2) (avec des options). Or je viens de faire le test, quand on met à jour ses _requirements_ depuis une version d'il y a deux mois, le module `python-slugify` est mis à jour (ça doit être une dépendance, par contre, parce que c'est pas explicitement un module appelé dans [nos _requirements_](https://github.com/zestedesavoir/zds-site/blob/dev/requirements.txt). Quand on va regarder [dans le code de `python-slugify`](https://github.com/un33k/python-slugify) (qui est du même auteur, donc je vote pour une dépendance de uuslug), on trouve [ce commit bizarre](https://github.com/un33k/python-slugify/commit/27d35f8810dd2816561044a9658eb19310d7e109), effectué le 13 janvier de l'an de grâce 2016 et qui change étrangement le comportement qu'on est en train de décrire. Et quand on fait ça, on tombe [sur le changelog](https://github.com/un33k/python-slugify/blob/7044d7a7c32388d557506cec4e174e8050c5666c/CHANGELOG.md#120) ou l'auteur nous explique sans préambule qu'il a cassé la rétro-compatibilité, rien que ça. 

Donc j'avais raison (de manière détournée), c'est bien du côté de `uuslug` que c'est pas juste et pas du nôtre. Il est temps d'étriper [un33k](https://github.com/un33k) :-°

**Comment by pierre-24** [comment]
Et là, c'est cadeau pour @SpaceFox, l'erreur de **un33k**, elle est [ici](https://github.com/un33k/django-uuslug/blob/master/setup.py#L17). Regardez moi ce _magnifique_ plus grand ou égal sur le numéro de version :-° (et j'ai vérifié, c'est le cas pour nous aussi dans la version 1.0.3).

**Comment by artragis** [comment]
ah, donc en fait mon fix n'était bien qu'un fix du symptôme.
Et on remarquera que du coup python-slugify n'est pas versionné selon le principe de versionnage sémentique. Et donc on peut dire que mes craintes  sur les maj de django uuslug ne sont pas infondées !

**Comment by pierre-24** [comment]
Yep. Bon, on fait quoi, du coup ?

**Comment by artragis** [comment]
On met le mot clef qui nous intéresse partout où il n'y a aucun 
changement possible dans le titre du tutoriel.
En plus d'être 100 fois plus idiomatique, ça nous évitera ce genre de 
surprise.

Et une fois le hotfix en prod faudra que spacefox exécute la commande 
proposée par @gustavi il me semble et qui permet de tout remettre les 
slugs à bien.

**Comment by pierre-24** [comment]
Pas sur. Ce que fait la commande de gustavi, c'est remettre l'ancien slug. Je pense que c'est une mauvaise idée (à moins d'être certain de mettre cet "force_slug_update" vraiment partout). Au contraire, je préconise une commande qui fait l'inverse, à savoir passer sur tout les tutos et faire des `os.move()` pour que le slug BDD corresponde au système de fichier et surtout à ce nouveau slugify (ça vaudrait la peine de metrre à jour `uuslug` dans les _requirement_ aussi, du coup). 

Dans le même temps, il faudrait gentiment dire à un33k que c'est pas bien ce qu'il a fait ;)

**Comment by SpaceFox** [comment]
Putain… j'essaie de faire un truc diplomatique demain midi ou après-demain
soir.
Le 22 févr. 2016 19:11, "Pierre Beaujean" notifications@github.com a
écrit :

**Comment by DevHugo** [comment]
Bon ba ça serait bien de changer les requirements vite fait, comme ça cela ne créé pas de nouveau souci.

**Comment by artragis** [comment]
effectivement le fix commande de @gustavi + ajout d'une ligne 
python-slugify=1.4.0 dans le requirements.txt devraient suffire

**Comment by pierre-24** [comment]
ça peut marcher. Après, faut bien noter quelque part pourquoi cette ligne a été rajoutée et pourquoi il ne faut absolument pas l'enlever :o 

(j'aime pas cette idée de figer une vieille version comme ça, vu le bordel que c'est avec Django, mais c'est effectivement la solution la plus facile).

**Comment by DevHugo** [comment]
Moi non plus mais si il faut faire un truc pour réparer vite fait ……

**Comment by artragis** [comment]
"cette ligne" tu parles de laquelle? (on a évoqué au moins trois lignes 
de codes différentes dans notre discussion)

**Comment by pierre-24** [comment]
Python-slugify==1.0.xx

**Comment by GerardPaligot** [comment]
@pierre-24 Tu sembles bien maitriser le sujet. Tu crois qu'il serait possible que tu t'occupes de ce bug ? :)

**Comment by GerardPaligot** [comment]
PS : @pierre-24 tu as peur de ping le mainteneur de uuslug pour dire qu'il fait du caca ? ^^

**Comment by pierre-24** [comment]
> PS : @pierre-24 tu as peur de ping le mainteneur de uuslug pour dire qu'il fait du caca ? ^^

Pas forcément, mais si je dois m'adresser à lui, il serait sympa pour lui que ce soit en anglais (imagine être pingué dans une discussion en chinois :p )

> @pierre-24 Tu sembles bien maitriser le sujet. Tu crois qu'il serait possible que tu t'occupes de ce bug ? :)

Je peux essayer, mais en soit, pas grand chose à faire. J'espère juste qu'effectivement, il "suffit" de fixer la version de `python-slugify` pour y arriver.

**Comment by artragis** [comment]
et de rere,dre la bdd cohérente (ou alors on laisse @spacefox faire ça à 
la main sur les deux/trois tutos cassés)

**Comment by pierre-24** [comment]
Voilà qui est fait !
