### ISSUE TITLE
Envoi d'un message lorsqu'un validateur réserve un contenu

### ISSUE THREAD

**Issue by Emeric54** [zestedesavoir/zds-site#3385]
Petite évolution qui pourrait être sympa (elle a d'ailleurs déjà été demandée à plusieurs reprises sur le forum) : lorsqu'un validateur réserve un contenu, il pourrait être sympa d'envoyer un MP de Clem au auteurs pour les prévenir que leur contenu a été pris en charge. Ca peut notamment être intéressant lorsque le processus de validation s'étale sur une longue période.

**Comment by pierre-24** [comment]
J'ajoute que c'est facile à faire :)

**Comment by Emeric54** [comment]
Tout à fait ; si l'idée convient à tout le monde, je m'en occupe !

**Comment by pierre-24** [comment]
C'est corrigé, @GerardPaligot a juste oublié de fermer :)
