### ISSUE TITLE
Problème sur la recherche lors d'un retour à la page précédente

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3386]
Pour reproduire le bug et voir de quoi il s'agit : 
- Aller sur la page des forums ou d'un topic
- Chercher via la barre de recherche en haut à droite (http://i.imgur.com/GaCYpqQ.png) puis appuyer sur ENTER
- Faire précédent
- Essayer à nouveau de faire une recherche via cette barre : **impossible** !

Testé sous FF 42.0

**Comment by MatthieuLepers** [comment]
J'ai trouvé d'où provient ce bug, on peut le retrouver dans le fichier all.js qui se situe dans le dossier dist/js/ , ce bug est dû à l'ajout de 'e(n).addClass("disabled")' ligne 7 colonne 14980.

**Comment by Situphen** [comment]
Euh, c'est pas pour rien qu'il y a cette ligne dans le code, je crois que c'est la seule manière d'éviter #1504 ! [Voir aussi https://github.com/zestedesavoir/zds-site/pull/2952#issuecomment-127414417]

**Comment by gustavi** [comment]
On fait quoi du coup ici ?

**Comment by Situphen** [comment]
@Sandhose a proposé une solution sur la PR

**Comment by pierre-24** [comment]
A tester, en fait ;)

**Comment by artragis** [comment]
je ne sais pas si la béta est à jour mais en effet, le bug est toujours présent.

**Comment by pierre-24** [comment]
À jour ou pas, j'y ai pas touché, donc OK :)

On Feb 5, 2017 4:32 PM, "artragis" <notifications@github.com> wrote:

je ne sais pas si la béta est à jour mais en effet, le bug est toujours
présent.

**Comment by vhf** [comment]
Non la beta n'est pas à jour, faudra attendre la release pour ça. :)

**Comment by Anto59290** [comment]
Je n'arrive pas a reproduire en prod, ça semble fixé, non ?

**Comment by gllmc** [comment]
Je ne reproduis le problème ni sur Chrome, ni sur Firefox, je pense que c'est résolu.
