### ISSUE TITLE
Image de l'éditeur flou

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#3387]
Bonjour,

je ne sais pas si ça a déjà été rapporté ou si sa sera corrigé dans la ZEP de l'éditeur, mais les images de l'éditeur son flou chez moi et ça pique un peu les yeux...

![zds_flou_1](https://cloud.githubusercontent.com/assets/8223773/13197233/7455c7e0-d7e7-11e5-8017-2c1bc14749b6.PNG)

**Comment by WinXaito** [comment]
Ping @sandhose 

Il me semble que les images de l'éditeur ne sont pas de bonne qualité, et vraisemblablement encore pire après la génération du sprite.

https://github.com/zestedesavoir/zds-site/blob/dev/assets/images/sprite/zform-math.png

**Comment by A-312** [comment]
Oui les images sont flou, il faudrait les remplacer une par une.

http://www.famfamfam.com/lab/icons/silk/

**Comment by motet-a** [comment]
Il faudrait utiliser une police d’icône ou du SVG. Voir #4100. On peut fermer ça ?

**Comment by artragis** [comment]
je ferme pour #4100
