### ISSUE TITLE
Clore automatiquement la béta d'un article à la publication

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#3389]
Bonjour,

à l'heure actuelle, lorsqu'on publie un contenu qui est en béta, cette dernière n'est pas close.

Ce comportement est très adapté aux tuto assez gros car leur rédaction peut continuer par la suite.

A l'opposé pour un article qui est souvent un oneshot, c'est pas très adapté. L'idée serait donc de créer un cas particulier qui, en cas de publication d'un article, ferme la béta.

**Comment by artragis** [comment]
à tager backend/évolution/facile

**Comment by Vayel** [comment]
Quel est l'intérêt de fermer le sujet de bêta ?

**Comment by artragis** [comment]
- enlever l'article de la liste des demandes d'aide
- éviter à un topic qui ne sert plus à rien d'être déterré par un troll
- et remercier gentiement (même si automatiquement) mes personnes qui ont
  participé à la béta.

**Comment by pierre-24** [comment]
Pourquoi pas une pitite case à cocher dans la modale d'envoi en publication ?

**Comment by artragis** [comment]
why not.

2016-02-23 9:26 GMT+01:00 Pierre Beaujean notifications@github.com:

**Comment by Vayel** [comment]
> éviter à un topic qui ne sert plus à rien d'être déterré par un troll

Dans l'idée, ce sujet contiendrait toutes les remarques relatives à un contenu, qu'elles soient faites avant ou après la publication : 

> Le sujet de bêta contiendrait ainsi les remarques des relecteurs et des validateurs. On peut étendre le concept en y intégrant les remarques intervenant après la publication. En somme, ce sujet rassemblerait toutes (la grande majorité des) les remarques concernant le contenu, et ne pourrait donc pas être fermé une fois la publication franchie. (ZEP-41)

**Comment by artragis** [comment]
Mais du coup on parle d'autre chose : ce n'est pas que le sujet qui pose
problème : c'est le fait que la béta reste active.

Ajoutons que post-publication nous avons non seulement les discussions sous
le tuto ET le bouton signaler une erreur.

**Comment by Karnaj** [comment]
Je prends.

**Comment by Karnaj** [comment]
Une petite correction doit être faite. Maintenant, à chaque fois qu’un article est revalidé (correction mineure par exemple), un nouveau message est rajouté à la discussion de la bêta pour indiquer qu’elle est fermée ([ici](https://zestedesavoir.com/forums/sujet/7097/le-metro-d-de-lyon/) par exemple). Ce serait mieux qu’il n’y en ait pas.

Il faut rajouter la condition `not topic.is_locked` à [cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_validations.py#L433) et rajouter un test pour ce cas.

**Comment by pierre-24** [comment]
Merci :)
