### ISSUE TITLE
[Front] Page "Mon compte" nommé "Mon profile"

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#3390]
Reporté sur le forum par [AliK](https://zestedesavoir.com/membres/voir/AliK/):

> Bonsoir à vous,
> 
> Quand je vais dans les Paramètres de mon compte, en cliquant dans le menu à gauche sur "Mon Compte" (modif du MdP), la page sur laquelle est titrée "Mon Profil", idem sur l'onglet, et non "Mon Compte" (ce qui serait plus logique, surtout qu'une page Mon Profil existe déjà). D'ailleurs vu qu'on modifie juste le mot de passe sur cette page, pourquoi ne pas passer le pseudo et courriel sur cette page aussi ? Au moins le titre Mon Compte aura plus de sens :)
> 
> Bonne soirée !

**Comment by Situphen** [comment]
Voir https://github.com/Emeric54/zds-site/issues/1

**Comment by WinXaito** [comment]
Yep, du coup je ferme ? (C'est lié à une autre issue sur ZdS ou il l'a juste sur son fork ?)

**Comment by Emeric54** [comment]
Il y a en effet du ménage à faire. Je pense qu'une issue peut être ouverte sur le dépôt ZdS, elle sera plus visible que sur mon fork.

**Comment by SpaceFox** [comment]
Corrigé et mergé.
