### ISSUE TITLE
Pas de limite du nombre de caractères sur la recherche

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3393]
Aujourd'hui on peut faire des recherches sans limitation dans le nombre de caractères. Il faut une limite, je pense qu'entre 64 et 256 c'est bien.

**Comment by GerardPaligot** [comment]
Pourquoi ?

**Comment by gustavi** [comment]
Pourquoi quoi ?

La limite ? Aujourd'hui tu peux envoyer une requête avec 500Mo de caractères. Ça me parait pas être vraiment quelque chose à faire.

**Comment by Situphen** [comment]
Tu veux limiter comment ? Si tu veux limiter le nombre de caractères que l'utilisateur peut rentrer dans la barre de recherche, j'en vois pas l'intérêt car il suffit d'ouvrir la console pour l'enlever (ou d'utiliser un logiciel/script).

Si c'est côté serveur, oui pourquoi pas. Après la recherche utilise une méthode GET, donc ça passe par l'URL et la taille d'un lien est limité je crois (j'ai testé sur Google au bout d'un moment j'ai une erreur 400).

**Comment by gustavi** [comment]
Une limitation front est une bonne chose mais comme tu l'as dit inutile si on utilise une console ou autre.

Côté back ça me semble nécessaire.

**Comment by squik** [comment]
bonjour je suis du groupe d'étudiants j'ai partiellement corrigé le front avec le maxlength , il me reste que la barre de recherche avec le {{ form.q }} dans le templates/search/search.html qui me pose un problème, je ne sais pas où le modifier de plus c'est le seul qui est touché par l'url ,on pourrait envoyer une page d'erreur quand le get donne un requête de plus de 256 caractères. 

merci d'avance pour votre aide.

**Comment by gustavi** [comment]
Si il y a un « maxlenght » côté Django alors au niveau du champs rien à faire, c'est généré automatiquement.

**Comment by pierre-24** [comment]
Mmmmh, j'ai peut être oublié ça :)

**Comment by Situphen** [comment]
Bon, il y a bien le `maxlength`qui bloque à 150 caractères ! Si je l'enlève avec la console et que j'envoie le formulaire j'ai une belle erreur 403 (*edit :* précision, avec + de 150 caractères) ! :D

**Comment by pierre-24** [comment]
Oui mais dans le paramètre ?q=qqch, on peut mettre n'importe quoi, nan?

**Comment by gllmc** [comment]
En ce qui me concerne, j'ai bien une 403 avec 151 caractères (ou plus), mais pas avec 150.

[Exemple avec  151 caractères](https://beta.zestedesavoir.com/rechercher/?q=https://beta.zestedesavoir.com/rechercher/?q=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)

**Comment by pierre-24** [comment]
Donc a priori, c'est bon (151 vs 150, on va pas chipoter, si ?)

**Comment by artragis** [comment]
@vhf tu peux clore du coup?

**Comment by pierre-24** [comment]
Pas besoin :)

**Comment by gllmc** [comment]
> 151 vs 150, on va pas chipoter, si ?

Même pas besoin puisqu'on a le comportement attendu. 150 étant la limite, il est normal qu'on ait une erreur à partir de 151, je me suis mal exprimé. ;)

**Comment by Situphen** [comment]
Si on pouvait avoir un message au lieu d'une 403 ce serait cool ! Mais bon, c'est déjà pas gênant en l'état actuel car une personne lambda ne touchant pas à la console n'aura jamais cette erreur.
