### ISSUE TITLE
Répétition inutile dans le code

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3394]
La ligne concernée https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/views.py#L675

**Comment by GerardPaligot** [comment]
Pourrais-tu expliquer la répétition inutile dans le code ?

**Comment by artragis** [comment]
je pense qu'il faudrait modifier cette condition en : 

``` python
form = LoginForm()
if next_page is not None:  # if the user was visiting some page before the registration
    form.helper.form_action += "?next=" + next_page
```

Ce genre de chose peut tout à fiat se faire dans une microPR sans passer par un ticket.

**Comment by gustavi** [comment]
Exactement. Je sais, mais j'avais pas d'env de dev sous la main donc j'ai préféré poster ici pour ne pas l'oublier.

**Comment by orandin** [comment]
Oh le joli code dupliqué! :-) 
Si personne ne s'en occupe, je proposerai une PR ce soir.

**Comment by gustavi** [comment]
Tu peux grouper avec ça https://github.com/zestedesavoir/zds-site/issues/3309 ;)
