### ISSUE TITLE
Message sur la page d'inscription incorrecte

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3395]
Sur la page d'inscription, lorsqu'on est connecté on a « Vous êtes déjà connecté. » au lieu de « Vous êtes déjà inscrit. ». Il faudrait aussi ajouter une "box" orange ou rouge, à voir (note : voir /membres/connexion/).

Voir aussi le message ci dessous

**Comment by Situphen** [comment]
A noter aussi que la page d'inscription n'a pas de titre et qu'elle a "Membres" dans le fil d'ariane (contrairement à la page de connexion qui n'en a pas)

**Comment by bszczapa** [comment]
Pour le "Membres" dans le fil d'ariane, c'est mieux de le mettre sur la page de connexion ou de l'enlever de l'inscription ?

**Comment by gustavi** [comment]
De le mettre sur la page de connexion pour être cohérent avec les URL
