### ISSUE TITLE
Paginer la page de l'historique des versions d'un contenu

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3396]
Aujourd’hui cette page affiche tout l'historique ce qui peut provoquer des soucis au niveau du script JS (via @Vayel sur le [forum](https://zestedesavoir.com/forums/sujet/5462/lhistorique-des-versions-mouline/?page=1#p100053)).

**Comment by SpaceFox** [comment]
Corrigé et mergé, merci !
