### ISSUE TITLE
[Beta v17] Instructions incompréhensibles dans la mise en bêta

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3399]
Dans les instructions de MAJ j'ai ces 2 lignes :

> # CORS
> 
> Supprimer les informations CORS de nginx.

C'est inutile parce que je n'ai pas la moindre idée de ce que c'est, et @gustavi (qui a fait le commit) non plus.

Si quelqu'un a une idée, qu'il fasse signe.

Notez qu'on a réussi à ouvrir un bug avant même de déployer la bêta. Normalement je devrais tout bloquer, mais je vais parier sur le fait que c'est mineur…

**Comment by gustavi** [comment]
Comme je l'ai dit pour moi il y a des instructions relatives à CORS dans les paramètres de nginx à supprimer.

**Comment by sandhose** [comment]
Donc, virer `add_header Access-Control-Allow-Origin *;` de `/etc/nginx/conf.d/zds_headers.conf`

**Comment by DevHugo** [comment]
On en [parlait ici](https://github.com/zestedesavoir/zds-site/issues/2666) pour le détail.

**Comment by GerardPaligot** [comment]
@SpaceFox Tu es parvenue à quelque chose grâce aux instructions de @sandhose ?

**Comment by SpaceFox** [comment]
Non, je ne m'en suis pas occupé. Dans tous les cas, je dois avoir une PR avec les instructions dans le update.md.

**Comment by GerardPaligot** [comment]
@sandhose Puisque tu sembles maitriser le sujet, tu serais faire cette petite PR quand tu as 2-3 minutes dans un train ? :)

**Comment by GerardPaligot** [comment]
Done ici.
