### ISSUE TITLE
Formulaire d'ajout d'une remarque (karma) éronné

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3400]
Côté front on a le symbole « \* » rouge qui indique que le champs _Commentaire_ est requis mais il est possible d'ajouter une remarque sans commentaire.

2 options : 
- C'est côté front qu'on a un mauvais affichage;
- C'est côté back et on check mal si le formulaire est valide (je penche pour ça).

**Comment by MatthieuLepers** [comment]
Il n'y a pas que celà, il est possible via l'édition html de changer l'intervalle pour la valeur de karma ajoutée (defaut [-100, 100]). De ce fait, il est possible de mettre -200 à un membre. Et effectivement c'est un oubli de vérification côté back.
