### ISSUE TITLE
[beta 17] Impossible de répondre

### ISSUE THREAD

**Issue by La-source** [zestedesavoir/zds-site#3401]
Bonjour,

Je suis en train de tester la beta 17, je me suis rendu sur le forum Dev Zone, j'ai pu créer un nouveau sujet sans problème, En revanche j'ai tenter de répondre dans plusieurs sujet et je me retrouve systématiquement avec une erreur 500.

**Comment by artragis** [comment]
Pourrais-tu dire exacement quel sujet? car là où j'ai tenté, j'ai réussi à poster.

**Comment by La-source** [comment]
https://beta.zestedesavoir.com/forums/sujet/2251/zep-24-refonte-et-enrichissement-des-notifications/?page=7#p99141
https://beta.zestedesavoir.com/forums/sujet/5413/uuslug-zds/?page=1#p99316

Cependant, comme vu avec les MP je me dit que c'est probablement lié au
serveur mail, il suffit qu'il y aie une personne abonnée au notification
par mail dans un sujet donné pour faire planter la possibilité de répondre
du coup.

2016-02-25 13:48 GMT+01:00 artragis notifications@github.com:

**Comment by SpaceFox** [comment]
La solution la plus simple à court terme est sans doute de demander à Django de rediriger les mails vers un fichier à la place du SMTP.

**Comment by artragis** [comment]
@spacefox : tu pourrais aussi créer la branche release-v17 qu'on puisse
faire d'éventuels fix?

2016-02-25 14:26 GMT+01:00 SpaceFox notifications@github.com:

**Comment by SpaceFox** [comment]
Re-pingue moi ce soir :)

**Comment by pierre-24** [comment]
> La solution la plus simple à court terme est sans doute de demander à Django de rediriger les mails vers un fichier à la place du SMTP.

Le problème, c'est que ça empêche les inscriptions à priori :/

**Comment by SpaceFox** [comment]
Sur la bêta, on s'en fout un peu non ? Au pire, on peut  valider les
inscriptions à la main si on veut vérifier ce process.

Le 25 février 2016 à 17:46, Pierre Beaujean notifications@github.com a
écrit :

**Comment by pierre-24** [comment]
> Sur la bêta, on s'en fout un peu non ? Au pire, on peut  valider les inscriptions à la main si on veut vérifier ce process.

Ok avec ça.

**Comment by gustavi** [comment]
Est-ce que c'est fixé ?

**Comment by La-source** [comment]
Nope, toujours impossible de répondre à un des sujets.

**Comment by artragis** [comment]
J'ai la vague impression que pour tester, firm1 t'a mis en lecture seule; Seulement comme ce dernier a détecté un bug, il n'est pas improbable que cela te gène dans ta propre navigation sur la béta.

@gustavi il faut qu'on comprenne pourquoi @La-source a ce bug. Si c'est une erreur 500, elle doit être sur le sentry or je n'ai rien qui soit lié à lasource sur le serveur du coup pour l'instant à part analyser à la main les logs, je ne vois pas comment faire.

Est-ce que tu pourras un jour passer sur la canal irc #zds-dev @La-source comme ça on pourra se synchroniser.

**Comment by gustavi** [comment]
Je pense que ça vient du fait que les mails ne partent pas.

**Comment by artragis** [comment]
C'est pas impossible en effet.

**Comment by GerardPaligot** [comment]
L'envoi d'e-mail n'a jamais fonctionné sur la bêta mais n'a jamais généré une erreur 500 non plus.

**Comment by artragis** [comment]
Si, ça en a généré parfois.

**Comment by GerardPaligot** [comment]
Je n'ai jamais rencontré l'erreur en tout cas (pourtant, j'ai déjà tenté de m'inscrire sur la bêta, de poster des messages et des réactions).

Pour info, j'obtiens des erreurs 500 aussi quand je tente de répondre aux [sujets cités](https://github.com/zestedesavoir/zds-site/issues/3401#issuecomment-188783287) par @La-source.

**Comment by artragis** [comment]
C'est bien l'envoi de mail qui fait chier son monde;

**Comment by DevHugo** [comment]
Si je poste dans mon sujet, ça va, mais pas dans [l'autre](https://beta.zestedesavoir.com/forums/sujet/2251/zep-24-refonte-et-enrichissement-des-notifications/?page=7#p99141)

**Comment by GerardPaligot** [comment]
@Un-Cornichon @sandhose @SpaceFox Est-ce que l'un de vous pourrait configurer à minima ce serveur de mail pour pouvoir confirmer ou infirmer les suppositions faites sur cette issue ?

**Comment by SpaceFox** [comment]
Attention, les vraies adresses sont encore en place en bêta. Ceci doit être pris en compte avant de toucher au serveur mail de la bêta.

**Comment by gustavi** [comment]
@SpaceFox Il a été décidé d'utiliser le "serveur console" non ?

**Comment by SpaceFox** [comment]
Oui, c'est juste pour éviter les problèmes que je re-précise.

**Comment by SpaceFox** [comment]
Normalement c'est fait, les mails en bêta partent vers un fichier par mail dans `/opt/zdsenv/mails_beta/`.

Je voulais mettre `find /opt/zdsenv/mails_beta/ -type f -mtime -7 -exec rm {} \;` dans un crontab pour nettoyer les mails de plus d'une semaine toutes les nuits, mais il semblerait qu'on ait pas de crontab sur la bêta…

**Comment by GerardPaligot** [comment]
Un grand merci @SpaceFox. Il n'y a plus d'erreur 500 pour les cas cités par @La-source.

Je ferme donc. :)
