### ISSUE TITLE
Le sitemap renvoit une date fausse

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3403]
Version touchée 16 (et 17).

Si on regarde dans le [sitemap.xml](https://zestedesavoir.com/sitemap-articles.xml) des articles en allant tout au bout, on retrouver la chaine xml suivante:

``` xml
<url>
<loc>https://zestedesavoir.com/articles/1062/zeste-de-savoir-passe-en-version-16/</loc><lastmod>2016-02-25</lastmod>
<changefreq>weekly</changefreq>
<priority>1</priority>
</url>
```

Ce qui signifie donc (pour n'importe quel robot google qui consulte ce fichier) que l'article de passage à la v16 a été publié (ou mise à jour publiquement) aujourd'hui 25/02/2015. Ce n'est pourtant pas vrai.

La dernière date de mise à jour publique e l'article date du 19/02/2015 comme on peut le voir sur l'[article en question](https://zestedesavoir.com/articles/1062/zeste-de-savoir-passe-en-version-16/). 

La date du sitemap affiché est donc celle de mise à jour du brouillon et non celle de la mise à jour publique.

**Comment by DevHugo** [comment]
C'est résolu, il faut fermer
