### ISSUE TITLE
Erreur 403 pour la page des apis dans la v17.

### ISSUE THREAD

**Issue by MrCirdo** [zestedesavoir/zds-site#3404]
Sur l'url des api (en ce moment : https://beta.zestedesavoir.com/api/), chez certains utilisateurs le serveur renvoie une erreur 403. Elle provient d'un certain nginx.
![capture d écran 2016-02-25 a 23 17 31](https://cloud.githubusercontent.com/assets/7924454/13336389/ff93339c-dc15-11e5-8728-ef16a66c3761.png)

L'erreur se produit que nous soyons connecté ou non.

**Comment by DevHugo** [comment]
Bizarre car /membres/ marche bien

**Comment by artragis** [comment]
Il me semble que c'est volontaire : la béta utilisant des donénes réelles, si l'api possédait une faille sur la béta, en l'ouvrant à qui le veut, on se retrouverait avec des fuites.

**Comment by pierre-24** [comment]
Oui, mais alors, comme le dit DevHugo, pourquoi [/api/membres/](https://beta.zestedesavoir.com/api/membres/) est-il accessible ? Je crois surtout que c'est Django-rest qui cafouille, là, non ?

**Comment by pierre-24** [comment]
(et techniquement, j'avais demandé à @Eskimon de me rajouter dans la liste des personnes autorisées. Peut-être que c'est plus le cas)

**Comment by pierre-24** [comment]
D'ailleurs, tant qu'on en est a se rendre compte que l'API ne fonctionne plus:

![screenshot from 2016-02-26 08 04 39](https://cloud.githubusercontent.com/assets/7889675/13345535/d4fc96b0-dc5f-11e5-9019-c46b8e6c914a.png)

@GerardPaligot ?

**Comment by GerardPaligot** [comment]
Ne vous prenez pas la tête, les pages sous `/api/` sont protégés par IP côté serveur parce que l'entête du token d'authentification vers le serveur de bêta est le même pour l'en-tête d'authentification de l'API.

Je ferme du coup. :)
