### ISSUE TITLE
Bug sur le nombre de pouces verts

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3405]
Sur les commentaires d'un article : 
- Avant : http://i.imgur.com/sA8JEEX.png
- Après : http://i.imgur.com/isecbw9.png

C'est moi ou ce bug a déjà été corrigé 25 fois ?

**Comment by SpaceFox** [comment]
Plus que ça, je crois…

**Comment by Situphen** [comment]
Prod ou béta ?
Quelle URL ?
Quel navigateur ?

**Comment by gustavi** [comment]
Prod, FF 44.0.2 (ArchLinux), https://zestedesavoir.com/articles/77/premiere-zep-developpee-sur-zeste-de-savoir/#p81092

**Comment by Situphen** [comment]
J'ai pas le bug, ce serait spécifique à certains membres ?

**Comment by gustavi** [comment]
Je fais plus de tests demain

**Comment by Croal** [comment]
Où en sont les tests ?

**Comment by WinXaito** [comment]
J'ai aussi le bug 

Je clique sur le pousse vert (Message de Spacefox), il augmente de 1 en ayant la couleur vert. Ensuite après actualisation il n'y plus la couleur verte et si je clique dessus il se supprime et prend la couleur verte à ce moment la (Couleur inversé).

Win10 / FF Dev 47.0a2 (2016-04-04) / Prod même page que @gustavi

**Comment by gustavi** [comment]
Corrigé en v18.
