### ISSUE TITLE
Rendre les url de la galerie compatibles avec HTTPS

### ISSUE THREAD

**Issue by Vayel** [zestedesavoir/zds-site#3410]
Actuellement, quand on charge une image dans la galerie, on nous fournit un code de la forme `![None](http://zestedesavoir.com/media/galleries/...)`.

Ne serait-il pas préférable d'avoir `![None](/media/galleries/...)` ?

**Comment by Vayel** [comment]
https://github.com/zestedesavoir/zds-site/blob/dev/templates/gallery/image/edit.html#L50

**Comment by gustavi** [comment]
`{{app.site.url}}` à supprimer.

**Comment by SpaceFox** [comment]
Corrigé et mergé :)
