### ISSUE TITLE
[Beta v17] Apparemment il manque des migrations

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3429]
Extrait du log de déploiement :

```
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

**Comment by GerardPaligot** [comment]
Cela est survenue uniquement avec la RC2 ou les RC précédentes étaient touchées aussi ?

**Comment by SpaceFox** [comment]
Je ne sais plus. En lançant les migrations on devrait le voir.

**Comment by SpaceFox** [comment]
Y'a un truc que je pige pas là…

``` console
(zdsenv)spacefox@azathoth:~/dev/django/zds-site$ python manage.py makemigrations
Migrations for 'default':
  0005_auto_20160309_2056.py:
    - Alter field email on code
```

Genre il manque un champ dans Django ?!

**Comment by GerardPaligot** [comment]
C'est marrant, on avait déjà eu ce problème (et tu avais eu la même réaction qu'aujourd'hui ^^) : https://github.com/zestedesavoir/zds-site/issues/2892

**Comment by DevHugo** [comment]
C'est à l'air d'être de la faute à [python-social-auth](https://github.com/omab/python-social-auth/issues/622). C'est fixé dans la 2.13, on a la [2.09](https://github.com/zestedesavoir/zds-site/blob/dev/requirements.txt#L4)

PS: [twitter](https://github.com/omab/python-social-auth/pull/853) ça vous rapelle quelque chose ?

**Comment by gustavi** [comment]
Cette dépendance nous fait vraiment chier. Il faudrait créer un test qui check les migrations via Travis.

L'idéal serait le lancer la commande `python manage.py makemigrations` et de vérifier la sortie.

**Comment by GerardPaligot** [comment]
Bien, j'ai un peu regardé ce qu'il en était pour cette issue.

D'abord, je confirme les propos de @DevHugo. C'est bien dans la dépendance `python-social-auth` qu'il manque un fichier de migration et c'est bien corrigé dans une nouvelle version (sauf que c'est la version 2.14 et non pas la 2.13 comme en témoigne le [tag du commit concerné](https://github.com/omab/python-social-auth/commit/663a174db194b1cc46effcaa4a2dc45d41d0d8e3)).

Cecit étant dit, j'ai 2 problèmes :
1. Dans votre virtualenv, vous disposez des sources des dépendances à la localisation suivante : `~/.virtualenvs/zdsenv/lib/python2.7/site-packages/`. Dans ce dossier, vous trouverez le dossier `social` regroupe toutes les sources de la dépendance `python-social-auth` et qui correspond donc bien aux [sources de son repo](https://github.com/omab/python-social-auth/tree/master/social). Cependant, si je me localise dans le dossier des migrations concernées par notre problème sur le [repo](https://github.com/omab/python-social-auth/tree/master/social/apps/django_app/default/migrations) et que je compare avec les sources de mon virtualenv, j'avais un fichier de migration supplémentaire (`004_*.py`). Je ne sais pas comment cela a pu se produire mais je voulais le signaler au cas où le virtualenv de la bêta ou de la prod avait le même problème.
2. Je n'ai pas trouvé le moyen de mettre à jour les sources de ma dépendance `python-social-auth` pour supprimer les fichiers de migration supplémentaire qui figuraient uniquement sur mon virtualenv local et pas sur le repo de la bibliothèque. Hors, cette commande pourrait être utile au cas où d'autres contributeurs ou la prod/bêta auraient le problème.

Sinon, le fix est vraiment trivial puisqu'il suffit de mettre à jour la bibliothèque.

**Comment by SpaceFox** [comment]
Alors du coup je ne pige pas, parce que la dépendance est déjà sensée être à jour : https://github.com/zestedesavoir/zds-site/blob/v17-RC2/requirements.txt#L4

**Comment by SpaceFox** [comment]
Corrigé, merci @GerardPaligot
