### ISSUE TITLE
[beta][v17] passer a Django 1.8.11

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3430]
La version qui s'apprete a partir en prod est deja obsolète au niveau securité. Elle utilise django 1.8.9 qui a encore certains problemes de sécurité.

On pourrait en profiter pour deployer django 1.8.11

**Comment by GerardPaligot** [comment]
C'était dans l'intention de @SpaceFox de passer à Django 1.8.11 mais elle n'était pas encore déployée sur pypi avant [hier soir](https://pypi.python.org/pypi/Django/1.8.11).

**Comment by SpaceFox** [comment]
[Sans commentaire](https://github.com/zestedesavoir/zds-site/tree/v17-RC2).

**Comment by SpaceFox** [comment]
(J'aimerais quand même comprendre comment tu en es arrivé à cette conclusion @firm1 ).

**Comment by firm1** [comment]
Ah, c'est la branche dev qui m'a troublé j'imagine

**Comment by SpaceFox** [comment]
^^ OK
