### ISSUE TITLE
[Beta v17] Erreur 413 à l'import d'une archive

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3431]
Serveur : Beta
Version : v17-RC2/288ac78
Système : OS X
Navigateur : Google Chrome Version 48.0.2564.116 (64-bit)

Scénario :
- Créez une archive qui contient que des images.
- Tentez de l'importer dans une galerie.
- Constatez une erreur 413 Request Entity Too Large.

J'ai hésité à rajouter le tag bloquant mais la fonctionnalité est out.

**Comment by SpaceFox** [comment]
Quelle taille l'archive ?

**Comment by GerardPaligot** [comment]
1,2 Mo et l'archive s'importe bien en prod (d'où le tag régression).

**Comment by SpaceFox** [comment]
Ça ressemble à un défaut de config de la taille max d'une requête Nginx.

**Comment by GerardPaligot** [comment]
C'est tout à fait possible, la page d'erreur n'était pas une venant de Django mais de Nginx. Je te laisse savoir si ce bug est pertinent ou pas du coup.

**Comment by SpaceFox** [comment]
Oui, pour pouvoir tester correctement ce genre de fichiers.

**Comment by gustavi** [comment]
Les deux configurations sont identiques sur la beta et la prod. C'est donc un bug. Je cherche.

**Comment by gustavi** [comment]
Sur les tutoriels ça me semble OK pour les upload, à confirmer avec des gros tutoriels (> 1Mio).

**Comment by GerardPaligot** [comment]
C'est sur les galeries (cf. le scénario).

**Comment by GerardPaligot** [comment]
Puisque le problème est de l'infra et déclaré comme bloquant, je ping les personnes compétentes pour y jeter un oeil. La release aurait déjà du être faite.

@Un-Cornichon @SpaceFox @sandhose

**Comment by SpaceFox** [comment]
Sauf que apparemment c'est pas de l'infra, si je comprends bien ce que dit @gustavi [ici](https://github.com/zestedesavoir/zds-site/issues/3431#issuecomment-193694071) ?!

**Comment by GerardPaligot** [comment]
@gustavi Tu as les accès serveur ?

**Comment by GerardPaligot** [comment]
Ceci dit, ça reste bizarre. La page d'erreur est clairement une Nginx et pas Django.
![capture d ecran 2016-03-11 a 22 46 37](https://cloud.githubusercontent.com/assets/1913901/13716402/26e82b48-e7db-11e5-8cea-5b91fd514773.png)

**Comment by GerardPaligot** [comment]
Nouvelle info qui me fait dire que c'est un problème d'infra, je n'ai aucun souci à l'import de mon archive sur une instance locale.

**Comment by SpaceFox** [comment]
Bon, je vais re vérifier ça alors.

**Comment by SpaceFox** [comment]
Bon j'ai trouvé, c'est la règle de taille des requêtes qui était mal placée en bêta.

**Par contre**, je trouve que les configurations nginx sont différentes en bêta et en prod [très au-delà de ce qui est indiqué dans les instructions de mise à jour](https://github.com/zestedesavoir/zds-site/blob/v17-RC2/update.md#actions-à-faire-pour-mettre-en-prod-la-version-17).

Pour moi seules ces différences sont légitimes :
1. Nom de domaine différent
2. Nom des fichiers de certificats SSL différents
3. Contrôle d'accès HTTP

Est-ce que quelqu'un peut m'expliquer tout le reste ?!

**Comment by SpaceFox** [comment]
Par exemple, le fichier mentionné ici n'existe pas en prod : https://github.com/zestedesavoir/zds-site/blob/v17-haïku/update.md#cors

**Comment by GerardPaligot** [comment]
Comme dit souvent, il faudrait versionner dans un dépôt Git (à part) la configuration des serveurs. Cela éviterait ce genre de souci.
