### ISSUE TITLE
[v16] On a perdu la date de réservation d'un contenu

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3432]
Environnement : prod

Depuis la v16, dans la [zone de validation](https://zestedesavoir.com/validations/) (comme le montre la capture ci-dessous) on ne sait plus à quelle date à été réservée un contenu.

![validationnes](https://cloud.githubusercontent.com/assets/6066015/13671528/af332fd6-e6d0-11e5-934e-1aed9502fe62.PNG)

**Comment by Anto59290** [comment]
Sur une installation toute propre le problème ne se produit pas (ou en tout cas je n'ai réussi a le reproduire)

**Comment by gustavi** [comment]
@artragis @SpaceFox @firm1 @Fumble vous pouvez vérifier sur des contenus récents ?

**Comment by SpaceFox** [comment]
J'ai les 2 cas.

2016-03-30 11:33 GMT+02:00 Laville Augustin notifications@github.com:

**Comment by firm1** [comment]
Je confirme j'ai aussi les 2 cas. Je n'arrive pas a savoir dans quel cas on a la date et dans quel cas on ne l'a pas.

**Comment by gustavi** [comment]
Première demande de validation / demande de mise à jour ?

**Comment by Anto59290** [comment]
Si sur un contenu sans date de resa, vous operez une annulation de resa puis a nouveau une resa ? Quel est le résultat ?
Je teste demain pour essayer de déterminer un critère pour reproduire le bug. ;)

**Comment by Anto59290** [comment]
@firm1 @SpaceFox Est-il possible d'avoir du feedback sur ce bug ? Est-il toujours présent en prod ? Si oui avez vous reperé un schéma ou ça se reproduit ?

Pour ciblage : 

- Quel type de contenus sont concernées (tuto, article, mixte?)
- Cela se produit sur une première validation / re-validation d'un contenu déja en ligne ?
- Si vous annulez la réservation et que vous re-réservez sur un contenu buggé, le bug se produit-il à nouveau ? 
- Le bug se produit quelque soit le validateur ? Il y a t il des validateurs pour qui ça ne marche jamais / toujours ?

Merci ;)
