### ISSUE TITLE
Message d'information erroné à la dépublication d'un article

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3433]
Lorsque je dé-publie un article j'ai un message erroné qui me dit que mon "tutoriel à été dépublié".

![deltaplanage](https://cloud.githubusercontent.com/assets/6066015/13671918/e91ef368-e6d2-11e5-8d07-d902f6be652f.PNG)

**Comment by SpaceFox** [comment]
Bêta ou prod ?

**Comment by firm1** [comment]
J'ai testé en beta, mais je pense qu'il doit être aussi en prod. Je ne peux
juste pas faire ce genre de test sur la prod directement.

**Comment by gustavi** [comment]
Je peux corriger ça en ZEP-13

**Comment by orandin** [comment]
Ce n'est pas le seul message erroné étant donné que les articles utilisent les templates des tutoriels. J'ai corrigé ça sur mon fork https://github.com/orandin/zds-site/commit/a631137c135f90a663c8bb3cb636ecf1cb510ff1. Je fais un PR sur la branche dev ?

**Comment by SpaceFox** [comment]
Oui.

Le 11 mars 2016 à 15:23, Simon Delberghe notifications@github.com a écrit
:
