### ISSUE TITLE
Problème pour builder le front

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3435]
Bonjour,

Alors que j'essayais de me refaire une install locale de ZdS, je suis tombé sur un souci au niveau du build du front. 

J'ai une ubuntu 15.10 et au moment du npm run gulp build j'ai cette erreur : 

``` bash
[06:55:58] Error: PluggableError: lwip not found.
    at formatError (/opt/zds/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/opt/zds/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/opt/zds/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /opt/zds/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/opt/zds/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/opt/zds/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:36:10)
    at Gulp.Orchestrator._runTask (/opt/zds/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/opt/zds/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/opt/zds/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /opt/zds/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

le npm-debug.log

``` log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'gulp', 'build' ]
2 info using npm@2.14.20
3 info using node@v4.4.0
4 verbose run-script [ 'pregulp', 'gulp', 'postgulp' ]
5 info pregulp zds-site@0.2.0
6 info gulp zds-site@0.2.0
7 verbose unsafe-perm in lifecycle true
8 info zds-site@0.2.0 Failed to exec gulp script
9 verbose stack Error: zds-site@0.2.0 gulp: `gulp "build"`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid zds-site@0.2.0
11 verbose cwd /opt/zds
12 error Linux 3.14-2-amd64
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "gulp" "build"
14 error node v4.4.0
15 error npm  v2.14.20
16 error code ELIFECYCLE
17 error zds-site@0.2.0 gulp: `gulp "build"`
17 error Exit status 1
18 error Failed at the zds-site@0.2.0 gulp script 'gulp "build"'.
18 error This is most likely a problem with the zds-site package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp "build"
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs zds-site
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls zds-site
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

J'ai cherché un peu je suis tombé sur @WinXaito qui a déjà eu le souci [ici](https://github.com/zestedesavoir/zds-site/issues/2944#issuecomment-125320396) et propose une correction [là](https://github.com/zestedesavoir/zds-site/issues/2944#issuecomment-125982744). Malheuresement je ne vois pas sa correction sur le dépot, je me demande donc si le problème vient de moi ou d'ailleurs.

**Comment by firm1** [comment]
ça a l'air d'être [un problème récurrent](https://zestedesavoir.com/forums/sujet/3146/cloud9-pour-jouer-avec-zds/#p65513).

J'ai beau essayer, je ne trouve pas de solution qui marche sans devoir modifier le Gulpfile.js

**Comment by Situphen** [comment]
J'ai une Kubuntu 15.10 avec Node.JS v4.3.2 et npm v2.14.12 sans aucun problème pour générer le front sur `upstream/dev` (avec branche et dépendances Node.JS à jour) !

Est-ce que la correction de @WinXaito fonctionne pour toi ?

Note : @WinXaito et @Vayel utilisaient tous les deux Node.JS v0.1x

**Comment by WinXaito** [comment]
Je me rappelle de ça, (Et surtout du faite que j'ai mis 30sec à faire la modif et 6h à faire la QA, mais bref passons).

J'ai simplement décrit les modifs il n'existe pas de version modifié sur un dépôt.

Node JS en est peut-être la cause, mais il me semblais avoir télécharger une version plus récente sans passer par un dépôt, je ne sais plus trop, ça date un petit peu quand même :p

**Comment by firm1** [comment]
Comme précisé dans la log j'ai `npm :2.14.20` et `node: v4.4.0` avant de tester la modification de @WinXaito je voulais savoir si c'est normal d'avoir le souci. Je vais tester la modif du Gulpfile.js dans ce cas ce soir.

**Comment by WinXaito** [comment]
Du nouveau @firm1 ?

**Comment by gustavi** [comment]
J'ai le même souci depuis que je suis passé à node 6

Les logs : 

```
\_o<  make build-front                      
npm run build

> zds-site@0.2.0 build /home/augustin/.virtualenvs/zds/zds-site
> gulp build

(node:21385) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:21385) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:21385) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[14:57:42] Using gulpfile ~/.virtualenvs/zds/zds-site/Gulpfile.js
[14:57:42] Starting 'sprite'...
[14:57:42] 'sprite' errored after 9.59 ms
[14:57:42] Error: PluggableError: lwip not found.
    at formatError (/home/augustin/.virtualenvs/zds/zds-site/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/home/augustin/.virtualenvs/zds/zds-site/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/home/augustin/.virtualenvs/zds/zds-site/node_modules/orchestrator/index.js:264:8)
    at /home/augustin/.virtualenvs/zds/zds-site/node_modules/orchestrator/index.js:275:23
    at finish (/home/augustin/.virtualenvs/zds/zds-site/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/home/augustin/.virtualenvs/zds/zds-site/node_modules/orchestrator/lib/runTask.js:36:10)
    at Gulp.Orchestrator._runTask (/home/augustin/.virtualenvs/zds/zds-site/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/augustin/.virtualenvs/zds/zds-site/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/augustin/.virtualenvs/zds/zds-site/node_modules/orchestrator/index.js:134:8)
    at /home/augustin/.virtualenvs/zds/zds-site/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:159:18)

npm ERR! Linux 4.5.1-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE
npm ERR! zds-site@0.2.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zds-site@0.2.0 build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zds-site package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zds-site
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zds-site
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/augustin/.virtualenvs/zds/zds-site/npm-debug.log
Makefile:55: recipe for target 'build-front' failed
make: *** [build-front] Error 1
(zds)
[augustin @ laptop-aug-arch] ~/.virtualenvs/zds/zds-site git:(zep-13-b)
\_o<  npm -v
3.8.7
(zds)
[augustin @ laptop-aug-arch] ~/.virtualenvs/zds/zds-site git:(zep-13-b)
\_o<  node -v
v6.0.0
```

Le fichier de debug : http://paste.awesom.eu/n2JG

**Comment by SpaceFox** [comment]
Node 6 est officiellement pas stable, pourquoi l'utiliser ?

2016-04-30 15:07 GMT+02:00 Laville Augustin notifications@github.com:

**Comment by gustavi** [comment]
Parce que c'est dans mon package manager : 

```
community/nodejs 6.0.0-1 [installed]
    Evented I/O for V8 javascript
```

Qu'entends-tu par « pas stable » ?

**Comment by SpaceFox** [comment]
« Pas stable » :
http://www.nextinpact.com/news/99628-node-js-6-0-nombreuses-nouveautes-mais-pas-encore-stable.htm

2016-04-30 15:32 GMT+02:00 Laville Augustin notifications@github.com:

**Comment by sandhose** [comment]
Comme pour genre, tous les problèmes de front sur les 6 derniers mois, c'est _juste_ `lwip` qui est mal compilé, **pas** à cause d'une version de node pas stable. Go regarder [la doc de `node-gyp`](https://github.com/nodejs/node-gyp#installation) (le système de build pour les modules natifs dans node) pour vérifier que les pré-requis sont OK (pas besoin d'installer `node-gyp`, c'est fait automatiquement ; juste vérifier que les pré-requis sont bon), et éventuellement la [doc de `lwip`](https://github.com/EyalAr/lwip#installation), même si elle donne pas trop d'info, puisque `lwip` requiert rien comme dépendance, à part que `node-gyp` fonctionne correctement.

Les deux raisons les plus communes de pourquoi ça marche pas, c'est soit il manque un compilateur (`gcc` ou autre), ou c'est le mauvais qui est installé (il faut une certaine version de Visual Studio sur Windows, cf le lien de la doc de `node-gyp`) ; soit c'est parce que `python` = `python3` sur certains systèmes, sachant que node-gyp demande un python 2 ; pareil, go regarder la doc de `node-gyp`.

**Comment by sandhose** [comment]
Oh, my bad, node 6 a quand même cassé des choses, dont [`lwip`](https://github.com/EyalAr/lwip/issues/249) (pas encore fixé) et [`node-sass`](https://github.com/sass/node-sass/pull/1498) (fixé, mais les changements sont pas encore fait dans `gulp-sass`, donc faudra encore attendre) ; donc, en attendant que ces dépendances soient mises à jour, comme dit dans notre doc : **Utilisez la LTS de Node, à savoir la v4**

**Comment by SpaceFox** [comment]
Je dirais même qu'on va rester sur la LTS de Node tant qu'on a pas de bonne raison de faire autrement.

**Comment by sandhose** [comment]
Bah, mettre à jour les dépendances, voir chercher à en dégager certaines (genre, lwip qui fait ch*er depuis le début) pour quand même fonctionner avec les nouvelles versions, tant que ça casse pas la LTS, on peut le faire, nan ?

**Comment by SpaceFox** [comment]
Dans la mesure où le site de Node.js lui-même me recommande d'utiliser la v4 et pas la v6, je ne vois pas bien pourquoi on se ferais chier à maintenir une double compatibilité ?

**Comment by WinXaito** [comment]
Je n'ai pas trop suivi, mais si y a un moyen de dégager lwip c'est cool, car il est relativement chiant.

**Comment by Situphen** [comment]
Passer à PostCSS (#3305) je crois, tu confirmes @sandhose ?

**Comment by sandhose** [comment]
Non, `node-sass` pose quasi aucuns problèmes, vu qu'ils fournissent des binaires pré-built sur la plupart des plateformes, et donc y'a en général aucun problème avec ; `lwip` sert pour `sprity` qui génère les sprites, mais vu qu'on a maintenant un Makefile, c'est plus simple d'utiliser d'autres outils, éventuellement en python pour générer le sprite, et donc virer lwip, au profit d'outils comme [`glue`](http://glue.readthedocs.io/en/latest/index.html), qui repose sur `Pillow`, qu'on installe déjà de toutes façons.

**Comment by sandhose** [comment]
Notre stack front ne dépend plus de `lwip` depuis #3818. Elle supporte maintenant les deux dernière LTS de node, à savoir la v4 et la v6. @firm1: peux-tu confirmer que ça a réglé ton problème ?

**Comment by gustavi** [comment]
up @firm1

**Comment by firm1** [comment]
Je ne pourrais malheuresement pas reessayer ça avant un bon moment du coup si personne n'arrive a reproduire, on pzut supposer que c'est corrigé.

**Comment by AmarOk1412** [comment]
@gustavi je pense que c'est bon ici alors :)

**Comment by pierre-24** [comment]
Je pense aussi :)
