### ISSUE TITLE
[v17] Impossible d'afficher la documentation de l'API

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3440]
Serveur : Prod
Version : v17-haïku/8cb7666
Système : OS X
Navigateur : Google Chrome Version 48.0.2564.116 (64-bit)

Scénario : 
1. Rendez-vous sur la page de la documentation de l'API.
2. Tentez de dérouler la documentation des membres et des messages privées.
3. Constatez que rien n'est déroulé.

J'hésite même à tagguer bloquant puisque la fonctionnalité est out.

**Comment by DevHugo** [comment]
C'est surement de l'infra, vu que en local ça marche.

**Comment by gustavi** [comment]
Voici ce que j'ai dans mes logs console JS : http://i.imgur.com/ov48Jx1.png

**Comment by GerardPaligot** [comment]
En effet, aucun problème en local. Cela dit, je doute qu'il y a eu des changements dans la configuration du serveur de prod. @SpaceFox Tu confirmes ?

**Comment by SpaceFox** [comment]
J'ai juste dégagé l'en-tête CORS.

**Comment by GerardPaligot** [comment]
Ca serait abusé qu'il y ait un lien. :)

**Comment by DevHugo** [comment]
Excusez-moi, c'est ma connerie, plus qu'à trouver une solution pour le mettre que sur certaine url.

**Comment by GerardPaligot** [comment]
C'est ta connerie ? Quelle est la modification qui a engendrée cette régression ?

**Comment by DevHugo** [comment]
C'est moi qui est proposé de supprimer l'entête cors

**Comment by GerardPaligot** [comment]
C'est certain que c'est ça qui cause le bug ?

**Comment by DevHugo** [comment]
Ça [remarche](https://zestedesavoir.com/api/#!/membres), je pense que c'était l'entête cors.

**Comment by GerardPaligot** [comment]
Je dirais même plus !

Ca remarche mieux que mieux ! https://github.com/zestedesavoir/zds-site/issues/2286

Je ferme.

**Comment by A-312** [comment]
Ca ne fonctionne plus ?

**Comment by gllmc** [comment]
@A-312 : cf #4082.
