### ISSUE TITLE
[v17] Content-Type à application/json, obligatoire

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3441]
Serveur : Prod
Version : v17-haïku/8cb7666
Système : OS X
Navigateur : Google Chrome Version 48.0.2564.116 (64-bit)

Prérequis : Des clés d'API.

Scénario :
1. Avec vos clés d'API, tentez de vous connectez. ([documentation pour récupérer ses clés d'authentification](http://zds-site.readthedocs.org/fr/latest/api.html#recuperer-les-tokens-d-authentification))
2. Constatez que la réponse du serveur est la suivante :

``` json
{
  "error": "unsupported_grant_type"
}
```

**Comment by GerardPaligot** [comment]
Bien, après quelques recherches, je vais nuancer.

Il est possible de se logguer mais uniquement quand on spécifie un `Content-Type` à `application/json`. Sinon, notre backend n'est pas capable de récupérer le `grant_type` spécifié dans la requête.

Ce n'est plus bloquant mais c'est gênant. Encore plus quand on sait que le [backend que nous spécifions](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L561), `JSONOAuthLibCore`, comporte des [incompatibilités avec DRF](https://github.com/evonove/django-oauth-toolkit/issues/296).

**Comment by firm1** [comment]
De mon coté, je n'arrive pas à accéder à mon token avec ou sans le content-type. Que je sois sur une console REST depuis mon navigateur ou via curl.

Voici la liste de mes essais (logiquement c'est l'essai N° 2 qui devrait fonctionner).

``` http
curl -H "Content-Type: application/json" -X POST -d "client_id=<mon_id>&client_secret=<mon_secret>&grant_type=password&username=firm1&password=<mon_mot_de_passe>" https://zestedesavoir.com/oauth2/token/
```

``` http
curl -H "Content-Type: application/x-www-form-urlencoded" -X POST -d "client_id=<mon_id>&client_secret=<mon_secret>&grant_type=password&username=firm1&password=<mon_mot_de_passe>" https://zestedesavoir.com/oauth2/token/
```

``` http
curl -X POST -d "client_id=<mon_id>&client_secret=<mon_secret>&grant_type=password&username=firm1&password=<mon_mot_de_passe>" https://zestedesavoir.com/oauth2/token/
```

Toujours le même message d'erreur : `"error": "unsupported_grant_type"`. 

Du coup j'aimerai bien savoir comment tu arrives à te connecter.

**Comment by GerardPaligot** [comment]
Le contenu de ta première requête n'est pas en JSON. :)

**Comment by firm1** [comment]
Ouais mais j'ai aussi essayé la premiere requete avec le contenu en json sans succès non plus. D'ou ma question

**Comment by GerardPaligot** [comment]
Voici une requête `curl` possible :

``` bash
curl -X POST -H "Content-Type: application/json" -d '{
    "username": "admin",
    "password": "admin",
    "grant_type": "password",
    "client_id": "CLIENT_ID",
    "client_secret": "CLIENT_SECRET"
}' "http://localhost:8000/oauth2/token/"
```

Je viens de tester en local et ça passe. :)

**Comment by firm1** [comment]
J'ai compris, on ne peut pas simplement remplacer les doubles quotes par des quotes simples en json et donc mon format n'était pas valide. 

Merci de ton coup de main

**Comment by DevHugo** [comment]
Quelques remarques:
 - La commande suivante passe sans probléme, on n'a plus vraiment besoin du header "content-type".
```bash
curl -X POST -d '{
    "username": "admin",
    "password": "admin",
    "grant_type": "password",
    "client_id": "CLIENT_ID",
    "client_secret": "CLIENT_SECRET"
}' "http://localhost:8000/oauth2/token/"
```

MAIS si on exécute la requête suivante donnée par la documentation qui est incorrecte: ` curl -X POST -d "client_id=CLIENT_ID&client_secret=SECRET_ID&grant_type=password&username=admin&password=admin" https://zestedesavoir.com/oauth2/token/`, on obtient `{"error": "unsupported_grant_type"}`.

Du coup, une question se pose, retourner l'erreur `{"error": "unsupported_grant_type"}` est t-il suffisant ? 

De toute les manières, il faut corriger la documentation.

**Comment by philippemilink** [comment]
La situation décrite dans le message précédent est toujours la même (fonctionne avec avec formatage des paramètres type JSON, mais pas avec un formatage "inline"). Cependant, je ne vois pas qu'est-ce qu'il faut corriger dans la documentation, c'est déjà la première commande (correcte) qui est dans la [doc](https://docs.zestedesavoir.com/api.html#recuperer-les-tokens-d-authentification). 

Issue à fermer ?
