### ISSUE TITLE
[v17] Impossible de répondre à un message privé à partir de l'API

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3442]
Serveur : Prod
Version : v17-haïku/8cb7666
Système : OS X
Navigateur : Google Chrome Version 48.0.2564.116 (64-bit)

Scénario :
1. Fournissez-vous de tokens d'authentification et récupérez l'identifiant d'un message privé.
2. Faites une requête depuis l'API pour poster un nouveau message dans ce message privé.
3. Constatez une erreur 403.

**Comment by GerardPaligot** [comment]
A quelle milestone doit être attachée cette issue ?

**Comment by SpaceFox** [comment]
Celle dans laquelle elle est passée en prod (v17 donc).
