### ISSUE TITLE
Indication du nombre de sujet créer éroné

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#3444]
Bonsoir, 

j'ai remarqué que sur le profil de [Devock](https://zestedesavoir.com/membres/voir/Devock/) si on se rend à gauche dans "Forum -> Sujet créer [3]" et bien on a l'indication _Aucun sujet n'a été créé par devock._

Donc je me demandais d'où sortais se _Sujet créer [3]_.

**Comment by AmauryCarrade** [comment]
Probablement des sujets dans une section à accès restreint.

**Comment by SpaceFox** [comment]
Je confirme. Comme la question a été posée plusieurs fois, ce serait pas mal de mettre un bloc « Sujet privé/inaccessible » au lieu de simplement supprimer le résultat.

**Comment by Croal** [comment]
Où se trouve la page qui correspond à {% url 'topic-find' usr.pk %} ?

**Comment by Croal** [comment]
Je tente ma première contribution à Zeste de Savoir. Ma correction est-elle correcte ?

**Comment by gustavi** [comment]
Merci @Croal pour cette première contribution :)
