### ISSUE TITLE
[prod] Too many connections

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3447]
Serveur : Prod
Version : v17-haïku/8cb7666

Dans la soirée du 16 mars vers 23h30, la plateforme Zeste de Savoir n'était plus disponible avec l'erreur suivante :

```
OperationalError: (1040, 'Too many connections') 
```

Tout est revenu à la normale après quelques minutes mais il doit bien y avoir un problème derrière et cela ne semble pas être la première fois que ce problème survient.

**Comment by SpaceFox** [comment]
> cela ne semble pas être la première fois que ce problème survient.

Qu'est-ce qui te fait dire ça ?

Parce que ce genre de gag est ultra visible sur Munin et très longtemps après (graphe mysql connections), et il n'y a rien qui ressemble à ça. Sauf peut-être en aout, mais c'était le moment où  le serveur faisait n'importe quoi.

Ici, et d'après journalctl, le plus probable est qu'OVH ait merdé en rendant les accès disques impossibles pendant plus de 120 secondes, ce qui déclenche des protections dans le noyau.

**Comment by GerardPaligot** [comment]
> Qu'est-ce qui te fait dire ça ?

@sandhose

**Comment by gustavi** [comment]
On a ce problème régulièrement pendant les MEP (ça fait une ou deux exception en général).

EDIT : @SpaceFox a raison dans le message d'après, _my bad_

**Comment by SpaceFox** [comment]
Heu… je suis à peu près sûr que non. « MySQL has gone away » c'est
crédible, mais pas « Too many connections »
Le 17 mars 2016 08:51, "Laville Augustin" notifications@github.com a
écrit :

**Comment by SpaceFox** [comment]
Et je répète : ce problème est ultra visible sur le graphe des connexions
MySQL sur Munin : la zone jaune (nb max de connexions atteint par le
serveur depuis son démarrage, nombre déclaré par le serveur lui-même)
atteint le max de la zone grise (nombre max de connexions autorisées par le
serveur). Et y reste jusqu'au redémarrage de MySQL, ce qu'on ne fait oas
tous lcs 4 matins.

**Comment by gustavi** [comment]
https://docs.djangoproject.com/en/1.8/ref/settings/#conn-max-age, à voir si ça peut aider

**Comment by SpaceFox** [comment]
Quel rapport ?
Le 17 mars 2016 09:07, "Laville Augustin" notifications@github.com a
écrit :

**Comment by firm1** [comment]
Je viens de tomber sur cette erreur en prod.

**Comment by SpaceFox** [comment]
On a des alertes automatiques pour ça @firm1 :)

J'ai pas accès à la prod d'ici, mais sur Munin on voit que les temps d'accès disque se sont encore envolés au même instant…

**Comment by gustavi** [comment]
@SpaceFox j'ai eu des retours comme quoi ça pouvait éviter ou du moins réduire ce genre de problème.

Aujourd'hui si je comprends bien, lorsque la DB n'est pas accessible niveau disque toutes les requêtes de Django sont mises en attente et lorsque ça redevient accessible tout part d'un coup ? Dans cas là, si tu mets un _timeout_ de 60s par exemple sur les requêtes ça peut fixer une partie du problème. À voir si c'est vraiment ça.

**Comment by SpaceFox** [comment]
On a déjà un timeout de 600 secondes sur ces requêtes.  Et quoi qu'il en soi, l'application n'a pas besoin de réglage pour gérer des cas aussi délirants que « le noyau se met en protection parce que les disques sont inaccessibles ».

**Comment by frecco75** [comment]
Bonjour,
Je me permets de participer à votre petite discussion bien que ne connaissant que vaguement votre projet, mais avez-vous mis en place un pool de connexion ?
Quelques pistes : http://www.askthepony.com/blog/2011/07/django-and-postgresql-improving-the-performance-with-no-effort-and-no-code/

**Comment by SpaceFox** [comment]
Normalement oui : https://github.com/zestedesavoir/zds-site/issues/2391

**Comment by artragis** [comment]
depuis le passage à gandi, on en a eu ou pas?

**Comment by gustavi** [comment]
Non. À fermer une fois le passage chez Gandi validé par le CA.

**Comment by gustavi** [comment]
Ce problème est résolu !
