### ISSUE TITLE
Désinscription impossible 

### ISSUE THREAD

**Issue by thepolienist** [zestedesavoir/zds-site#3448]
Bonjour,

Lorsque je me désinscris, je peut me reconnecter à mon compte qui existe toujours... La première fois que j'ai cliqué sur le bouton pour me désinscrire il n'y a pas eu d'erreur mais depuis je tombe sur une erreur 500 qui ne fait que me déconnecter...

Il semblerait que cette erreur ait déjà été rencontrée #2062 .

Merci !

**Comment by DevHugo** [comment]
Salut

On pourrait avoir l'heure et la date à lequel tu as tenté de te désinscrire ? C'est pour retrouver l'erreur dans les fichiers de log. 
Si tu ne peux pas nous donner une fourchette, peux tu retenter de te désinscrire et nous donner l'heure ou tu as tenté de te désinscrire ? 

Merci d'avance.

**Comment by thepolienist** [comment]
re,

Nouvelle tentative de désinscription: 1H31-1H32 (21/03)

**Comment by DevHugo** [comment]
@sandhose @SpaceFox @Eskimon @GerardPaligot on a besoin de connaitre l'erreur sur l'outil pour avancer !

**Comment by SpaceFox** [comment]
Dans les logs non ? Il n'y a pas d'erreur sur Munin.

Personnellement je n'y ai pas accès avant ce soir.

2016-03-21 8:43 GMT+01:00 Hugo Courtecuisse notifications@github.com:

**Comment by gustavi** [comment]
@DevHugo parle très certainement du Sentry !

Et il n'y a rien dedans, aucune 500 sur les 2 derniers jours. Toutefois @sandhose il faut que tu remettes ton certificat HTTPS à jour

**Comment by DevHugo** [comment]
> Dans les logs non ? Il n'y a pas d'erreur sur Munin.
> 
> Personnellement je n'y ai pas accès avant ce soir.

Oui, désolé, comme j'utilise pas les outils au quotidien, j'ai du mal avec les noms.

> Et il n'y a rien dedans, aucune 500 sur les 2 derniers jours. 

Saperlipopette

@thepolienist On peut avoir ton pseudo sur ZDS si c'est pas indiscret ?

**Comment by sandhose** [comment]
Noté, je le fais dans la journée

**Comment by thepolienist** [comment]
@DevHugo polien, tout simplement
Toujours une erreur 500 au nouvel essai de 13:24

**Comment by gustavi** [comment]
@sandhose je soupçonne le certificat SSL d'empêcher le bon envoi des erreurs.

**Comment by thepolienist** [comment]
![Capture du problème](http://img15.hostingpics.net/pics/235579video.gif)

Si ça peut vous aider...

**Comment by DevHugo** [comment]
ce qui est bizarre c'est que ça marchais avant. Je me suis désinscrit, y'a pas longtemps.

**Comment by gustavi** [comment]
Merci @thepolienist mais il va falloir aller regarder les logs. On revient vers toi quand on a plus d'informations.

**Comment by sandhose** [comment]
J'ai renouvelé mon certificat, et le worker sentry avait planté, donc je l'ai relancé

**Comment by DevHugo** [comment]
J'ai tenté de me désinscrire et ça marche en local, donc à moins d'avoir une stacktrace, ça va être chaud à débug.

**Comment by thepolienist** [comment]
Parfois, en me reconnectant, j'obtiens dans firebug : 

`"NetworkError: 405 METHOD NOT ALLOWED - https://zestedesavoir.com/membres/desinscrire/valider/"`

**Comment by DevHugo** [comment]
@sandhose @firm1 @Eskimon vous avez pas d'erreur qui remonte ?

**Comment by thepolienist** [comment]
Je suis condamné à rester inscrit ^^ !
Nouvel essai le 02/04 à 12:21 , toujours erreur 500...

**Comment by DevHugo** [comment]
Désolé, c'est pas de la mauvaise volonté, c'est juste qu'on à aucune idée du pourquoi et donc c'est très difficile à résoudre sans avoir au moins l'erreur détaillé et les lignes concernées.

@sandhose @SpaceFox @firm1 vous pouvez refaire un tour sur l'outil pour voir si vous avez rien eu comme erreur le « 02/04 à 12:21 »

**Comment by gustavi** [comment]
```
IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`zdsdb`.`tutorial_tutorialread`, CONSTRAINT `user_id_refs_id_438ed1dd` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`))')
  File "django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "zds/member/views.py", line 431, in unregister
    User.objects.filter(pk=current.pk).delete()
  File "django/db/models/query.py", line 537, in delete
    collector.delete()
  File "django/db/models/deletion.py", line 309, in delete
    query.delete_batch(pk_list, self.using)
  File "django/db/models/sql/subqueries.py", line 41, in delete_batch
    self.do_query(self.get_meta().db_table, self.where, using=using)
  File "django/db/models/sql/subqueries.py", line 26, in do_query
    self.get_compiler(using).execute_sql(NO_RESULTS)
  File "django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
```

**Comment by DevHugo** [comment]
@artragis @pierre-24 `tutorial_tutorialread`, c'est une table pré-zep 12, qui sert plus, c'est ça ? (remplacé par tutorialv2_contentread).

Le commentaire liés à l'ancienne table `tutorial_tutorialread`:

``` python
    """Small model which keeps track of the user viewing tutorials.

    It remembers the topic he looked and what was the last Note at this
    time.

    """
```

**Comment by artragis** [comment]
en effet.

**Comment by thepolienist** [comment]
@DevHugo Bien sur, je comprend parfaitement ;) .
Si vous avez déjà une erreur c'est au moins une piste, bon courage pour débuger...

**Comment by DevHugo** [comment]
C'est le moment de virer les tables pré zep12, je pense. Un admin pourrait nous fournir la liste des tables sur la base de données de prod pour que je puisse faire un script permettant de supprimer les tables en trop ?

thepolienist, merci :p

**Comment by artragis** [comment]
ça sera réglé lors de la mise en place de la v18 ça. Peut-on l'inclure dans la milestone svp?

**Comment by DevHugo** [comment]
Faut faire le script pour supprimer les anciennes table pre-zep12.

**Comment by GerardPaligot** [comment]
Comment ça se fait que cette issue sera réglée ?

**Comment by artragis** [comment]
Elle est due à la présence des anciennes tables pré-zep12 . En les
supprimant, plus d'issue.

2016-05-02 13:46 GMT+02:00 Gérard Paligot notifications@github.com:

**Comment by GerardPaligot** [comment]
Merci @artragis

**Comment by thepolienist** [comment]
Un petit passage juste pour dire que j'ai put me désinscrire, merki ;) .

**Comment by GerardPaligot** [comment]
@thepolienist Content que le problème soit résolu mais c'est bien dommage de voir un membre quiter Zeste de Savoir. :)
