### ISSUE TITLE
Problème d'affichage lorsque le menu est trop long

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3457]
Via le [forum](https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=36#p103284) : 

> J'ai effectivement le même problème, quand l'intro du tuto est assez courte pour que ces boutons se retrouvent assez haut.
> Leur z-index les fait passer au-dessus de l'overlay du menu principal (ils ont un z-index: 1 d'appliqué qui n'est pas forcément utile).

Voir les images sur le forum.

**Comment by SpaceFox** [comment]
J'ai presque envie de dire qu'ici, le vrai problème, c'est la taille du menu :p

**Comment by gustavi** [comment]
Ça sera corrigé ZEP-25 mais autant corriger ça aussi :) Sur des écrans plus petits on peut potentiellement avoir ça.

**Comment by orandin** [comment]
>  (ils ont un z-index: 1 d'appliqué qui n'est pas forcément utile)

Voir https://github.com/zestedesavoir/zds-site/pull/3207 pour comprendre pourquoi le z-index a été défini à 1.

**Comment by WinXaito** [comment]
Il n'est pas possible d'augmenter le z-index sur le menu ?

**Comment by Situphen** [comment]
Plus d'actualité avec le nouveau menu, je ferme.
