### ISSUE TITLE
Liens erronés sur « Mes tutoriels » ou « Mes contenus »

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3459]
Via [Mewtow](http://zestedesavoir.com/forums/sujet/5384/mes-tutoriels-les-filtres-renvoient-une-404-sur-la-seconde-page/?page=1#p98814) : 

> Dans la liste des tutoriels du profil ("Mes tutoriels"), cliquer sur un filtre (en validation, bêta, toussa) ne fonctionnent que sur la première page de tutoriels. Quand on le fait sur la seconde page, le filtre renvoie une erreur 404. Je ne sais pas si le problème survient sur la liste des articles qu'on a rédigé, faute d'avoir assez d'articles pour faire la vérification (j'y travaille).
> 
> Il est évident que ce bug est loin d'être bloquant et je dois certainement être le seul à être en capacité de le remarquer.

Pour reproduire : 
- avoir assez de contenus pour en avoir sur 2 pages
- aller en page 2
- sélectionner un filtre
- => 404

Cela vient du tempaltetag qui garde la `page=2`.

**Comment by artragis** [comment]
ok, il y a donc un append_to_get de trop quelque part.
