### ISSUE TITLE
Installer un outil de surveillance serveur

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#346]
Avant la MEP (idéalement pour la beta publique), installer un outil de monitoring du serveur. Genre Munin.

**Comment by SpaceFox** [comment]
Au fait, j'ai un Munin perso, je peux rajouter ce serveur à la liste si vous voulez.

**Comment by Alex-D** [comment]
Je ne sais pas bien ce que c'est, mais ça ne peux pas faire de mal donc pluzin :)

**Comment by SpaceFox** [comment]
Un début de doc ici : https://github.com/Taluu/ZesteDeSavoir/wiki/Surveillance-du-serveur-avec-Munin

Je fais des tests sur la préprod pour l'instant.

**Comment by SpaceFox** [comment]
Ça a  l'air de tourner sur la PRP.
Si tout va bien je fait la même sur la prod demain.

**Comment by SpaceFox** [comment]
Si quelqu'un pouvait me filer les accès à la prod que j'y installe ça aussi, vu que ça fonctionne correctement sur la préprod, ce serait parfait :)

**Comment by SpaceFox** [comment]
Voilà, c'est fait.
Pour ceux que ça intéresse, les graphes sont ici : http://sd-41281.dedibox.fr/munin/ (section zestedesavoir.com - les autres c'est mes serveurs, vous pouvez regarder mais y'a rien de passionnant)
Login et mot de passe : si vous avez déjà accès aux serveurs, vous les connaissez :)

J'ai pas configuré les surveillances PostgreSQL mais celles MySQL.
Notez que tout en bas dans le groupe "zds" on a des métriques qui surveillent l'application elle-même. On pourrait en rajouter facilement si on voulait.
