### ISSUE TITLE
 Pas de mail pour les résolutions d’alerte 

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3461]
Via [Dominus Carnufex]([Dominus Carnufex]%28http://zestedesavoir.com/forums/sujet/5678/pas-de-mail-pour-les-resolutions-dalerte/?page=1#p103879%29) sur le forum : 

> Lorsque l’on signale un message, et que le signalement est traité, le staff a la possibilité de nous laisser un message de « résolution d’alerte », lequel nous est transmis par le biais d’un MP de Clem. Or, contrairement aux autres MP, celui-ci ne génère pas l’envoi d’un mail, même quand les bonnes options sont cochées.
> 
> J’en profite pour dire que je trouve cette dénomination très « brutale » : j’utilise quasi systématiquement cette fonctionnalité pour signaler un sujet qui n’est pas dans le bon forum, il n’y a aucune « alerte » là dedans. ^^

**Comment by Emeric54** [comment]
Comme je l'ai dit sur le forum, ce n'est pas un bug, c'est volontaire. Il faut juste statuer pour savoir si ces mails doivent être envoyés ou non. Si ils doivent l'être, alors ce sera un simple _booléen_ à changer.

**Comment by gustavi** [comment]
Sinon on peut rajouter une option dans les paramètres d'un membre.

**Comment by Emeric54** [comment]
Ça me semble un peu lourd pour ces simples MPs, qui ne sont pas vraiment importants. A la limite, cette conversation devrait peut-être avoir lieu sur le forum, histoire que tous les membres puissent donner leur avis.

**Comment by GerardPaligot** [comment]
J'aurais une question : Est-ce qu'il ne serait pas plus pertinent de générer une notification ? La seule chose qu'on perdrait, c'est le message du membre du staff mais est-ce important ?

Après, c'est sans doute une question à poser sur les forums.

**Comment by Emeric54** [comment]
J'approuve @GerardPaligot.

Une seule chose : une alerte peut parfois être inutile. Dans ce cas, le message du membre du staff est important, afin de le signaler au membre qui l'a émise.

**Comment by GerardPaligot** [comment]
> Une seule chose : une alerte peut parfois être inutile. Dans ce cas, le message du membre du staff est important, afin de le signaler au membre qui l'a émise.

Tu as un exemple ?

**Comment by Emeric54** [comment]
> Tu as un exemple ?

Imaginons qu'un utilisateur signale un topic, pour `x` raison. Si finalement la raison `x`  n'est pas valable, le staff ne changera rien au topic. L'utilisateur qui a émis l'alerte recevra alors une notification de résolution, mais rien n'aura changé. Il pourra donc penser que son alerte a été ignorée. 

Avec la possibilité d'un MP, le membre du staff pourra expliquer que la raison `x` n'est pas valable, et pourquoi.

J'espère que j'ai été compréhensible :smile:

**Comment by GerardPaligot** [comment]
Bien vu. Du coup, c'est vraiment à discuter avec la communauté et ne fait pas l'objet de cette issue. :)
