### ISSUE TITLE
 Erreur de dépendance dans la documentation d'installation 

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3463]
Via le [forum]() : 

> Il me semble que la doc d'installation de Zds est erronée pour l'installation sous linux : http://zds-site.readthedocs.org/fr/latest/install/backend-linux-install.html . Dans le paragraphe sur les packets il est demandé d'installer libjpeg62-turbo, en revanche la commande en dessous pour Ubuntu reference toujours libjpeg8, la commande ne fonctionne donc pas (sous Debian). Il suffit de changer le nom du paquet pour que ca roule.

**Comment by informaticienzero** [comment]
Je m'en occupe.
