### ISSUE TITLE
Travis ne build plus pour une raison obscure

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#3464]
[Travis](https://travis-ci.org/zestedesavoir/zds-site/jobs/118791898) échoue sur le `test_humane_time (zds.utils.templatetags.tests.tests_date.DateFormatterTest)`.

**Comment by GerardPaligot** [comment]
Tiens, il a pas capté le changement d'heure. ^^

**Comment by GerardPaligot** [comment]
@pquentin Par hasard, tu aurais une idée pour ce problème ? Tu sembles être à [l'origine](https://github.com/zestedesavoir/zds-site/commit/f45a539b07050f37be563fb240108e86bca26df8) du test (et d'une grande réflexion vu le message du commit).

**Comment by DevHugo** [comment]
Y'a pas à dire, c'est compliqué les dates et heures ! =°)

**Comment by pierre-24** [comment]
Mouais. On est parti pour avoir un souci à chaque changement d'heure, comme ça :o

**Comment by pquentin** [comment]
Mais non mais non @pierre-24. La dernière passe a amélioré beaucoup de choses. Je vais voir pour le test d'ici sept jours.

**Comment by DevHugo** [comment]
Vous avez rien compris c'est une feature, comme ça, les devs seront enfin comment avancer leurs horloges de leurs pc !

**Comment by gustavi** [comment]
Fixé dans #3468
