### ISSUE TITLE
JS manquant

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#347]
404 sur le JS /static/js/newsletter.min.js

**Comment by firm1** [comment]
ça a été corrigé aujourd'hui, du coup je pense que ce n'est pas dans ta branche de test

**Comment by SpaceFox** [comment]
J'ai tiré une nouvelle branche de tests depuis "origin/release-beta-1.0",
si ça peut aider.

**Comment by firm1** [comment]
Ah en effet, je en sais pas pourquoi il cherche ce js. Celui utilisé c'est le `http://zestedesavoir.com/static/js/newsletter.js`

**Comment by SpaceFox** [comment]
Corrigé (directement sur la branche, faut pas déconner) --> fermé
