### ISSUE TITLE
Optimiser Travis

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3472]
Vois le travail commencé sur #3180

**Comment by SpaceFox** [comment]
https://github.com/zestedesavoir/zds-site/pull/3180 ?

Et c'est probablement pas de l'infra, sauf si par miracle modifier quelque chose _sur nos serveurs_ améliore Travis :)

**Comment by gustavi** [comment]
Oui, on ne va pas laisser cette PR ouverte indéfiniment, autant créer un ticket, ça lui donnera peut-être plus de visibilité.

**Comment by vhf** [comment]
Bon, j'en ai marre. Il faut régler ça.

**Comment by GerardPaligot** [comment]
Je ferme avec plaisir.
