### ISSUE TITLE
L'interface d'admin des tutos v2 n'est pas utilisable

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3477]
L'interface d'admin des tutos v2 n'est pas utilisable, pour les raisons suivantes :
- Aucune recherche possible
- Contenus, Contenus publiés et Validation : seuls le nom est affiché dans la liste
- Notes sur un contenu : la liste affiche n'importe quoi (un truc technique visiblement)
- À l'édition d'un élément (Contenu, Contenu publié, Notes sur un contenu, Validation), les selects (simples et multiples) chargent l'intégralité des données liées. C'est au mieux inutilisable (select avec l'intégralité des membres ou tous les contenus), au pire dangereux pour le serveur et le navigateur (select avec **toutes** les images du site). De mémoire, Django a une option pour utiliser un champ avec auto-complétion à la place d'un select.

**Comment by pierre-24** [comment]
Autant pour le deuxième et troisième point il suffit de modifier les méthodes `__unicode__()` (ou leurs penchants, `__str__()`), même si je vois pas trop comment rendre ça plus évident (à priori c'est le titre qui est affiché), autant pour le reste, je sèche.

**Comment by gustavi** [comment]
Je sais comment faire, je vais essayer de m'en occuper.

**Comment by gustavi** [comment]
Note : je corrigerai ça quand #3387 sera mergé.

**Comment by vhf** [comment]
#3881

**Comment by Anto59290** [comment]
Des choses ont du bouger de ce côté la depuis #4146 . @SpaceFox : depuis ton premier message des choses se sont-elles améliorées ou c'est resté tel quel ?

**Comment by vhf** [comment]
#4146 n'est pas en prod. ;)

**Comment by gllmc** [comment]
Actuellement, il me semble que le dernier point a été corrigé, mais pas le reste. C'est assez facile à faire : il faut mettre à jour `list_display` et `search_fields` sur les classes d'admin, je peux m'en occuper ?
