### ISSUE TITLE
Favicon manquante

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#348]
Le site cherche à accéder à /favicon.ico, qui n'existe pas.

**Comment by SpaceFox** [comment]
Il n'y a toujours pas de favicon, mais au moins il n'essaie plus d'y accéder. Bizarre...

**Comment by SpaceFox** [comment]
Du coup ça devient une evol : ajouter une favicon :)

**Comment by Alex-D** [comment]
Y a déjà : 
https://github.com/Taluu/ZesteDeSavoir/blob/release-beta-1.0/assets/images/favicon.ico
et
https://github.com/Taluu/ZesteDeSavoir/blob/release-beta-1.0/assets/images/favicon.png

Donc je ne pige pas le soucis là.
Sauf peut-être qu'il faille déplacer le fichier à la racine plutôt que dans /images/

**Comment by SpaceFox** [comment]
Aujourd'hui sur la bêta, la favicon n'est référencée nulle part dans le
code de la page. Du coup il ne va pas la chercher.

**Comment by Alex-D** [comment]
Louche. Je la rajoute alors.

**Comment by SpaceFox** [comment]
Commité, mergé --> fermé !

**Comment by SpaceFox** [comment]
Corrigé --> fermé
