### ISSUE TITLE
[v17.1] Elément "select" dépasse d'une modale

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3481]
Serveur : Prod
Version : v17.1-haïku/0871cf8

Contexte : Je tente de déplacer des sections dans un article avec certains titres un peu long.

<img width="443" alt="capture d ecran 2016-04-01 a 19 14 02 1" src="https://cloud.githubusercontent.com/assets/1913901/14214554/f3526186-f83d-11e5-9904-f7ee505d368d.png">

**Comment by Anto59290** [comment]
je prends

**Comment by gustavi** [comment]
Des nouvelles @Anto59290 ?

**Comment by Anto59290** [comment]
Je regarde ca de suite ;)

C'est corrigé, j'envoi la PR quand j'ai une vraie connection internet ;)
