### ISSUE TITLE
Doit t-on pouvoir récupérer un token à partir de l'API, si on est banni ? 

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#3487]
Bonjour,

Je me posais la question de savoir, si c'était une bonne pratique de pouvoir récupérer un token, si on est banni sur le site ?

**Comment by GerardPaligot** [comment]
Tu peux récupérer ton token mais tu ne pourras rien en faire. Donc, est-ce important ?

**Comment by DevHugo** [comment]
On est parfaitement d'accord, que si on récupère le token, on pourrais faire aucune action à part de la consultation, ce qui est possible avec le site.

C'était vraiment une question ouverte, et j'ai pas de position sur le sujet. C'est juste que j’assimilais dans ma tête la connexion sur le site et la récupération de token. Ce qui pour moi, c'était deux actions équivalentes et du coup, si on pouvait pas se connecter, on pourrait pas récupérer son token.

Comme je trouve pas trop d'autre argument, c'est très bien comme ça aussi.

**Comment by gustavi** [comment]
Les discussion de ce genre c'est bien, sur le forum c'est mieux ;)

Comme je l'ai dit avant : banni => plus d'accès à l'API.

**Comment by DevHugo** [comment]
J'ai suivi tes conseils, j'ai créé un sujet sur le forum pour en [discuter](https://zestedesavoir.com/forums/sujet/5743/doit-t-on-pouvoir-recuperer-un-token-a-partir-de-lapi-si-on-est-banni/).

**Comment by DevHugo** [comment]
Euh c'est loin d'être résolu, faut faire le code toussa.
