### ISSUE TITLE
[v18] Erreur dans le message de la ZEP-25

### ISSUE THREAD

**Issue by Emeric54** [zestedesavoir/zds-site#3490]
Petit bug pas bien grave, mais le MP reçu suite à la ZEP-25 contient ceci : 

> Bonjour {0},

Bien sûr,`{0}` devrait être remplacé par le pseudo de l'utilisateur.

**Comment by SpaceFox** [comment]
Et « d'aléger » --> « d'alléger ».

**Comment by Emeric54** [comment]
`+` les liens donnés vers les articles et les tutoriels donnent sur une 404.

**Comment by Emeric54** [comment]
La correctif d'@artragis est passé, on peut fermer ici.

**Comment by Emeric54** [comment]
J'ouvre à nouveau cette issue car le message n'est toujours pas bon : au lien d'y voir notre pseudo, nous sommes tous nommés Taurre : 

> Bonjour Taurre,

Si on ne veut plus s'embêter avec ce pseudo, on l'enlève tout simplement, et on laisse le simple bonjour.
