### ISSUE TITLE
Liste des tutoriels pas bien affichée sur la home

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3492]
Serveur : Bêta
Version : v18-RC3/ffa18f8
Système : Mac OS X El Capitain
Navigateur : Safari Version 9.0.3 (11601.4.4)

Scénario :
- Rendez-vous sur la page d'accueil.
- Constatez que les tutoriels ne sont plus bien formatés comme sur la prod.

<img width="589" alt="capture d ecran 2016-04-04 a 17 14 52" src="https://cloud.githubusercontent.com/assets/1913901/14252888/95d152c6-fa89-11e5-9020-d1a36f143a04.png">

**Comment by gustavi** [comment]
C'est normal.

**Comment by GerardPaligot** [comment]
C'est normal ?

**Comment by gustavi** [comment]
=> IRC

**Comment by WinXaito** [comment]
Personnellement je trouve mieux comme ça,  
les articles on aussi été formaté de la même manière ?

Car si on regarde, actuellement sur la Prod les articles et tutos ne sont pas indiquer de la même manière. (Indication date, auteur et nombre de commentaire).

**Comment by GerardPaligot** [comment]
Je ne peux pas me rendre sur IRC pour l'instant. Mais, dans tous les cas, ça casse la home, à la fois **par rapport à la spec réfléchie avec la communauté** et par rapport avec **la liste des articles** qui est un cran moins nombreux.

**Comment by SpaceFox** [comment]
La théorie, c'est qu'on était sensés avoir :
- Affichages des tutos et des articles identiques
- Le bloc de pub pour rédiger qui change de colonne (sous les articles) pour garder 5 tutos en une

**Comment by WinXaito** [comment]
Mais ta capture est faite sur un PC ou un téléphone portable (Car lors de mon commentaire j'ai fais comme si tu étais sur portable), mais après réflexion j'ai peut-être tort.

Dans le cas ou j'aurais tort, y aurait moyen d'avoir une deuxième capture plus global pour voir ce qui est cassé ?

**Comment by gustavi** [comment]
Le premier point c'est fait. Pour le bloc de pub je ne l'ai pas fait.

**Comment by sandhose** [comment]
Il y a déjà eu des discussions par rapport à ces blocs. Mon principal argument contre, c'est que _article != tutoriel_

Maintenant, je ne suis pas du tout contre (au contraire !) uniformiser le format "grand" de ces blocs. C'est à dire que l'on garde ce qui a été fait pour que les blocs soient similaires quand ils sont grand, mais de **garder un format `mini`** comme on a sur la version actuelle pour 4 des 5 tutos.

Pourquoi ?
1. La place. On peut mettre plus de tutos avec le bloc bleu en dessous sans problème
2. L'aspect global. 2 listes strictement identiques et symétriques, c'est triste. Avec ces 4 tutos "mini" et le bloc bleu, c'est moins régulier et moins monotone. Il s'agit de la home, tout de même !
3. `tutoriel != article`. Même si techniquement, c'est le cas, ca reste pas la même chose. Pour moi, un tutoriel, c'est intemporel ; un article ça peut être vachement plus lié au moment, et amène souvent au débat/à la discussion. 
   Donc pour moi, se passer de l'information de la date de publication et du nombre de commentaires sur un tutoriel sur les quatre de la homepage (la plupart des commentaires sur les tutoriels, c'est pour signaler une typo ou pour féliciter l'auteur pour son contenu).

Reste le souci des tags qui sont du coup plus compliqué à mettre en avant sur ce format la. Pour moi c'est pas si grave que ça, parce que les tags sur les tutoriels sont plutôt utilisé dans l'autre sens. C'est à dire "je cherche un tutoriel sur le C, je vais regarder le tag correspondant". Ou alors, "il était chouette ce tutoriel, voyons ce que je peux trouver de similaire".

Maintenant, ce n'est que mon avis, je sais que vous n'êtes très sûrement pas tous d'accord avec ça, mais pour moi, garder des formats mini, c'est mieux autant niveau design global qu'UX.

**Comment by sandhose** [comment]
btw le problème des liens bleu est à résoudre et sera vite fixé ; je le ferai, ou indiquerai à @gustavi comment faire

**Comment by SpaceFox** [comment]
@sandhose L'idée c'était justement de se débarasser de ces formats mini…

Et j'ai déjà répondu à tous tes arguments, que je réfute, sur le topic que je n'ai pas le temps de retrouver mais qui est sur ZdS. En l'état, ce n'est pas le lieu pour refaire ce débat.

**Comment by pierre-24** [comment]
En attendant, ça fait un trou dans la liste des articles pas très esthétique, format mini ou pas. Si vous tenez à l'employer, ben ... Mettez les tags les plus utilisés, par exemple :)

**Comment by SpaceFox** [comment]
Le débat s'est fait [sur ce topic](https://zestedesavoir.com/forums/sujet/3495/commentons-la-zep-04/?page=1), puis a tenté d'être continué séparément [pour les non-connectés](https://zestedesavoir.com/forums/sujet/3593/page-daccueil-des-non-connectes-problematique/) et [pour les connectés](https://zestedesavoir.com/forums/sujet/3597/page-daccueil-des-connectes-problematique/), sans très grand succès.

Dans tous les cas, [je rappelle les tenants et aboutissants d'une page d'accueil](https://zestedesavoir.com/forums/sujet/3495/commentons-la-zep-04/?page=2#p64695).

**Comment by sandhose** [comment]
Il s'agit donc bien d'un débat qui n'a pas abouti, et qui semble ne plus intéresser grand monde depuis 6 mois.

Je veux bien qu'il y ait eu à un moment une demande par quelques personnes juste après la sortie de la ZEP-04, mais pour moi, **ça ne justifie pas un tel changement.**

**Comment by SpaceFox** [comment]
Pour moi, les 3 principaux problèmes qu'a l'accueil actuel en bêta, c'est :
1. La surcharge en informations des blocs. En dégageant les heures de publication, voire en simplifiant l'affichage de la date qui est ultra-long (vendredi 19 septembre 2019 --> le 19/09/2019), qui fait que l'information primordiale (le titre du tuto/article) est noyé dans la masse). On peut éventuellement imaginer supprimer le compteur de messages sur les tutos.
2. Les liens en bleus qui attirent l'œil (ils devraient être en orange comme sur l'accueil actuel)
3. Le déséquilibre des colonnes

Parce que c'est les 3 problèmes qui la rendent difficile à lire ou franchement bancale.

Tout le reste, c'est du détail par rapport aux progrès que pourraient faire cette page d'accueil si on avait de vraies compétences en ergonomiques à déployer dessus, ce que - à ma connaissance - personne n'a dans l'équipe.

---

Le débat n'a pas aboutit parce qu'il n'était pas vraiment géré et portait sur tous les sujets à la fois, hein.

D'autre part, la page d'accueil actuelle montre des faiblesses ergonomique, et ce n'est pas parce que c'est pas beaucoup demandé qu'il n'y a rien à améliorer. Cf par exemple les textes de présentation en mode déconnecté. En particulier, le manque de dates sur les tutos masque l'activité sur la page d'accueil, et la double colonne (avec les demi-blocs en largeur) fait que certains tutos sont invisibles (ceux de la colonne au milieu), on a plusieurs témoignages en ce sens. À commencer par le mien. J'ai essayé d'avoir des chiffres factuels via l'outil de heatmap de Google Analytics, mais impossible de le faire fonctionner, si quelqu'un y arrive… Ça permettrait aussi de répondre au cas d'usage des tags, qui à l'heure actuelle _sont_ utilisés, si j'en crois les URLs correspondantes dans GA.
