### ISSUE TITLE
Incohérence dans les tags les plus utilisés

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3493]
Serveur : Bêta
Version : v18-RC3/ffa18f8
Système : Mac OS X El Capitain
Navigateur : Safari Version 9.0.3 (11601.4.4)

Scénario :
- Regardez la liste des tags les plus utilisés dans le menu des tutoriels.
- Cliquez sur "Tous les tags" et constatez que les tags les plus utilisés ne sont plus les mêmes.

<img width="134" alt="capture d ecran 2016-04-04 a 17 26 53" src="https://cloud.githubusercontent.com/assets/1913901/14253186/c3701d88-fa8a-11e5-82a4-c6d1fed9e24d.png">

<img width="865" alt="capture d ecran 2016-04-04 a 17 27 01" src="https://cloud.githubusercontent.com/assets/1913901/14253192/c8aafbb0-fa8a-11e5-86cd-6802e5c0c939.png">

**Comment by pierre-24** [comment]
2 possibilités :
1. On compte aussi dans le non publié (peu probable) ;
2. On compte aussi les machins avec `redirect=True` (plus probable).

**Comment by GerardPaligot** [comment]
@artragis Ta PR (https://github.com/zestedesavoir/zds-site/pull/3533) corrige cette issue aussi ?

**Comment by artragis** [comment]
Nein.

2016-04-25 18:11 GMT+02:00 Gérard Paligot notifications@github.com:

**Comment by artragis** [comment]
Ou peut-être que si. Faut avouer que je l'avais pas vue celle-là.

2016-04-25 18:15 GMT+02:00 francois dambrine artragis@gmail.com:

**Comment by GerardPaligot** [comment]
Le sujet me semble assez lié. Ca mériterait peut être d'intégrer cette issue à ta PR (sauf si c'est vraiment très différent bien sûr).

**Comment by gustavi** [comment]
J'essaye de fixer ça quand @artragis a corrigé #3533 s'il ne le fait pas dedans

**Comment by artragis** [comment]
Il est fort probable que ma PR ait corrigé le problème. A tester donc.

**Comment by GerardPaligot** [comment]
Issue pas corrigée ici. 

Si nous allons dans le menu des tutos ou des articles, on aura les tags les plus utilisés dans ces 2 sections. Par exemple, j'ai un seul tuto publié avec le tag "Bla" et 2 articles publiés avec le tag "Bli", j'aurais la liste :
- Bla
- Bli

> **Attention :** J'ai la même liste (dans le même ordre) dans le menu des articles alors que je devrais avoir l'inverse.

Et quand je clique sur "Tous les tags", j'ai tous les tags de tous les contenus confondus. J'ai rien contre mais alors il faudrait le marquer. On s'attend à avoir tous les tags des tutoriels.

**Comment by gustavi** [comment]
Je laisse ça à @artragis, le fix est presque le même que dans son autre PR

**Comment by artragis** [comment]
On sait et ça a été demandé comme ça.

pour le "tous les tags" si ça dérange vraiment c'est deux mots à changer.
Pour la liste, c'est plus complexe, mais bon.

**Comment by GerardPaligot** [comment]
@artragis Ca été demandé où ? Si ça a vraiment été demandé, il faut changer pour quelque chose du genre "Tous les tags des contenus", ça sera moins perturbant.

**Comment by artragis** [comment]
Dans la spec de la zep sur le forum.
Je suis d'accord pour changer l'intitulé.

Le 27 avril 2016 à 10:27, Gérard Paligot notifications@github.com a écrit
:

**Comment by GerardPaligot** [comment]
L'issue a oubliée d'être fermée ici. Merci @artragis en tout cas.
