### ISSUE TITLE
[beta v18] Pas de menus déroulants sur les articles

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#3494]
Question de logique : si il y a un menu déroulant pour les tutos listant les catégories, puisque ça a été uniformisé, il sera logique que ce soit le cas pour les articles aussi. Non ?

**Comment by GerardPaligot** [comment]
Je me suis fais la réflexion aussi et je pense même que c'est dans la spec de la ZEP-25.

**Comment by sandhose** [comment]
Est-ce que cette évolution ira encore dans la v18, ou on se dit qu'on release la v18 ASAP, et que la v19 suivra juste après ?

**Comment by SpaceFox** [comment]
Vue la tête de la v18, ça va prendre je pense au moins 2 semaines avant qu'elle sorte.

**Comment by gustavi** [comment]
Je vais faire cette issue. C'est un truc qui a foiré sur le rebase, désolé.
