### ISSUE TITLE
Incohérence dans le nombre de contenus spécifié pour un tag

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3495]
Serveur : Bêta
Version : v18-RC3/ffa18f8
Système : Mac OS X El Capitain
Navigateur : Safari Version 9.0.3 (11601.4.4)

Scénario :
- Rendez-vous sur la [liste des tags](https://beta.zestedesavoir.com/contenus/tags/).
- Prenons comme exemple la catégorie "cds" et constatez 25 contenus spécifiés.
- Cliquez sur le tag et constatez qu'il n'y a que 16 contenus.

**Comment by pierre-24** [comment]
Je crois qu'il s'agit du même type d'erreur que dans  #3493 : [ici, on oublie le `redirect=False`](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_published.py#L675) :)

**Comment by pierre-24** [comment]
(non, c'est un peu en dessous, mais bref, c'est l'idée)

**Comment by gustavi** [comment]
@pierre-24 : c'est quoi cette histoire de redirect ? Ça sert à quoi ?

Une autre question, on a quelque chose d'assez grave sur la beta : 

```
>>> PublishedContent.objects.filter(content_public_slug="les-promesses-en-javascript")                                       
[<PublishedContent: Version publique de "Les promesses en JavaScript">, <PublishedContent: Version publique de "Les promesses
en JavaScript">]                                                                                                             
```

**Comment by pierre-24** [comment]
Pas de panique, c'est normal :)

[C'est en fait `must_redirect`](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/models/models_database.py#L574) (_my bad_).

Ben en fait, quand on a annoncé qu'on cassait le SEO, on c'est fait démonter en bonne et due forme. Du coup, pour éviter les ennuis, on a mis ce machin là en place pour les tutos qui ont été créé avant la ZEP-12.
1. Avant la ZEP-12,  article et tutos étaient séparés dans des tables distinctes, avec un `pk` donné ;
2. Forcément, comme ont a remis tout dans la même table, les `pk` ne correspondaient plus (mais le slug restait le même) ;
3. Du coup, on a rajouté cette astuce là, avec un objet en `must_redirect=True` qui contient l'ancien `pk` (avant ZEP-12) et "redirige" sur le nouvel objet (en `must_redirect=False` et avec le bon pk). Ça vaut ce que ça vaut.
4. Cette astuce sert aussi quand le slug d'un contenu change entre deux publications (exemple typique, un article est renommé pour des causes éthiques).

Du coup, les `PublishedContent` existent en plusieurs exemplaire pour un contenu donné (tous pointent sur le même `PublishableContent`, évidement), mais il n'y en a qu'un seul qui a `must_redirect=False` et qui correspond à la dernière version publiée en date. Et il faut tenir compte de ça, évidement :)

**Comment by gustavi** [comment]
Merci @pierre-24, je corrige ça de suite.

**Comment by artragis** [comment]
Le pire c'est que ça je l'avais dit dans la revue de code initiale...

**Comment by gustavi** [comment]
J'avais compris le contraire @artragis :/ Désolé, c'était pas clair, ça l'est maintenant :)
