### ISSUE TITLE
[v18] J'ai perdu mes sujets suivis

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3498]
Version : 18
OS Windows
Navigateur Firefox

Alors qu'une synchro a été faite entre la prod et la beta, je ne retrouve plus mes sujets suivis dans la page https://beta.zestedesavoir.com/forums/ comme on peut le voir sur la capture ci-dessous (il ne me reste plus qu'un sujet suivis au lieu de beaucoup plus)

![suivis](https://cloud.githubusercontent.com/assets/6066015/14254805/a75c8ac6-fa91-11e5-9852-d5dc2d60547b.PNG)

**Comment by GerardPaligot** [comment]
Je confirme le bug chez moi aussi. C'est étonnant, c'était un cas testé en local. Je regarde ça dès que possible.

**Comment by SpaceFox** [comment]
@GerardPaligot des nouvelles sur ce ticket ? Vu qu'il empêche de tester une des grosses nouveautés, j'aimerais qu'il soit corrigé pour pouvoir demander à tout le monde de tester sur la bêta.

**Comment by GerardPaligot** [comment]
Le bug est identifié. Je bosse dessus.

**Comment by GerardPaligot** [comment]
Bien, PR done.

**Comment by Emeric54** [comment]
Du coup, on doit pouvoir fermer ici. @GerardPaligot

**Comment by firm1** [comment]
Je réouvre cet issue, car autant j'ai récupéré certains sujets suivis, autant il y en a qui ne sont pas là dans dans la sidebar des sujets suivis. Il suffit d'aller sur ce lien : https://beta.zestedesavoir.com/forums/notifications/ et voir la différence entre les sidebar et le reste des notifs

**Comment by GerardPaligot** [comment]
Ouais. Pour information, le bug n'est plus le même. Les sujets sont bien suivis mais la liste des sujets suivis retournés ne sont pas les bons. A mon avis, le bug est semblable à celui de ta dernière ici (à savoir, https://github.com/zestedesavoir/zds-site/issues/3536).
