### ISSUE TITLE
[beta v18] C'est possible de créer un tag vide

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#3503]
En bossant sur le design de la page des tags, j'ai malencontreusement laissé une virgule à la fin de la liste des tags, ce qui a eu pour effet de créer un tag vide.

ping @gustavi

**Comment by Emeric54** [comment]
@gustavi, vu ton commit, tu t'en occupe ?

**Comment by gustavi** [comment]
Oui, juste un souci de rebase. Ça vient soon.
