### ISSUE TITLE
Possibilité de changer les tags après publication

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#3504]
Le champ des tags peut être modifié après publication, et la modification est prise en compte immédiatement. Pareil il me semble pour les catégories. Je suis pas sûr que ce comportement soit voulu.

**Comment by GerardPaligot** [comment]
Ce bug est aussi présent pré version 18.

**Comment by artragis** [comment]
Oui, c'est un "bug" déjà présent, mais je ne sais pas combien il est souhaitable. N'oublions pas qu'on a déjà eu besoin de faire ça dans la vie réelle.

**Comment by gustavi** [comment]
Bug ou pas ici ?

**Comment by vhf** [comment]
Feature, not bug.
