### ISSUE TITLE
[beta v18] IntegrityError: (1062, "Duplicate entry '138-69582' for key 'utils_commentvote_user_id_3ea65e81563eda03_uniq'")

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#3505]
https://sentry.sandhose.fr/zeste-de-savoir/backend-1/issues/442/

```
IntegrityError: (1062, "Duplicate entry '138-69582' for key 'utils_commentvote_user_id_3ea65e81563eda03_uniq'")
(24 additional frame(s) were not displayed)
...
  File "django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
```

**Comment by GerardPaligot** [comment]
Du contexte ?

**Comment by sandhose** [comment]
Les votes sont censé êtres uniques niveau `(user, post)`. La, il semblerait qu'on a un problème de concurrence entre deux workers qui fait qu'il y a quand même eu une entrée en double dans la DB. J'ai pas encore regardé en détail, je rapporte juste l'erreur qu'on a eu sur sentry

**Comment by GerardPaligot** [comment]
@sandhose Tu as dans l'intention de corriger ça avant la mise en prod ? Sachant que la bêta est bien moins utilisée que la prod et que nous avons réussi à obtenir l'erreur, j'ai peur d'une potentielle mauvaise surprise sur la prod.

**Comment by sandhose** [comment]
Après, j'ai aucun moyen de reproduire le bug, et il s'est produit qu'une seule fois, donc je sais pas trop :x

**Comment by GerardPaligot** [comment]
Bien, j'ai un peu regardé comment on aurait pu arriver à cette erreur et c'est pas simple.

Nous avons cette méthode :

``` python
def set_user_vote(self, user, vote):
    """ Set a user vote (like, dislike or neutral) """
    if vote == 'neutral':
        CommentVote.objects.filter(user=user, comment=self).delete()
    else:
        CommentVote.objects.update_or_create(user=user, comment=self,
                                             defaults={'positive': (vote == 'like')})

    self.like = CommentVote.objects.filter(positive=True, comment=self).count()
    self.dislike = CommentVote.objects.filter(positive=False, comment=self).count()
```

Cette méthode est l'unique méthode qui fait une modification sur le modèle `CommentVote`, ça limite le champ de recherche et la méthode se comprends assez aisément. Si nous réfléchissons un peu sur la méthode, on peut avoir tendance à penser que la méthode `update_or_create` ne fait pas son taff correctement.

Voici l'implémentation de cette méthode :

``` python
    def update_or_create(self, defaults=None, **kwargs):
        """
        Looks up an object with the given kwargs, updating one with defaults
        if it exists, otherwise creates a new one.
        Returns a tuple (object, created), where created is a boolean
        specifying whether an object was created.
        """
        defaults = defaults or {}
        lookup, params = self._extract_model_params(defaults, **kwargs)
        self._for_write = True
        try:
            obj = self.get(**lookup)
        except self.model.DoesNotExist:
            obj, created = self._create_object_from_params(lookup, params)
            if created:
                return obj, created
        for k, v in six.iteritems(defaults):
            setattr(obj, k, v)

        with transaction.atomic(using=self.db, savepoint=False):
            obj.save(using=self.db)
        return obj, False
```

Autrement dit, il tente de récupérer l'objet. S'il y arrive, il renvoit l'objet sinon il crée l'objet. Dans tous les cas, il fait une sauvegarde dans une transaction atomique (il en fait une aussi dans `_create_object_from_params`).

Conclusion : J'aurais bien quelques hypothèses qui stoperait l'exécution d'une requête pour en continuer une autre et amener à l'erreur mais est-ce que nous voulons aussi nous protéger contre l'usage de méthode interne à Django ? Ca commence à aller loin. D'autant plus que nous parlons des votes et la seule répercussion qu'il pourrait y avoir, c'est de ne pas permettre à un utilisateur de voter 2 fois sur un même commentaire (chose que nous voulons).

**Comment by gustavi** [comment]
Pour le coup je pense qu'on a une issue qui n'a peut-être pas lieux d'être. Si jamais c'est bien une issue je pense fortement que c'est notre code qui n'est pas bon et non celui de Django. Je pense qu'il faut tester plus en détails sur la beta lors de la 18-RC5.

**Comment by gustavi** [comment]
Jamais reproduit ici donc je ferme.
