### ISSUE TITLE
[v18] Les liens vers le flux rss d'une catégories/tags n'est pas disponible

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3508]
Le lien incriminé : https://beta.zestedesavoir.com/contenus/?category=autres

En allant sur ce lien, on ne peut pas cliquer sur le flux rss qui apparait en bas à gauche. Le lien vers le flux est inexistant.

Le problème concerne les deux types de flux. Il s'agit peut-être d'un oubli coté template/front. Dans le doute je taggue large.

**Comment by firm1** [comment]
Le problème est le même pour tous les contenus aussi.

**Comment by GerardPaligot** [comment]
Doublon https://github.com/zestedesavoir/zds-site/issues/3496
