### ISSUE TITLE
Utiliser l'autocomplétion pour le champ des tags quand on édite/créé un contenu

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#3509]
Actuellement, on a le problème que le champs des tags quand on édite un tutoriel, on risque d'avoir des tags en double, parce qu'on ne va pas entrer exactement le même nom de tags. Par exemple, `PHP7 != PHP 7`, et ça génère deux tags différents. C'est déjà le cas de `c++` et `c plus plus`.

Maintenant, ca pourrait être relativement facile d'ajouter de l'autocomplétion dessus, suffit d'un endpoint où on peut rechercher un tag avec une réponse en JSON comme pour les membres. Ca minimiserait les chance de tags "en double", puisque l'autocomplétion suggérerait les tags déjà existants.

**Comment by Anto59290** [comment]
Apres l'autocompletion de membres je pense pouvoir realiser ca de manière efficace, je prends donc. A venir dans pas longtemps si tout roule.

**Comment by Situphen** [comment]
Merci @Anto59290 !

**Comment by Anto59290** [comment]
Merci les gars !
