### ISSUE TITLE
[v18] Lien dans le fil d'ariane des contenus non clicacle

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3510]
L'url incriminée est la suivante : https://beta.zestedesavoir.com/contenus/

Le lien montré dans la capture d'écran ci-dessous n'est pas un lien puisqu'il n'y a pas de lien derrière et il n'est donc plus clicable.

![no-clicable](https://cloud.githubusercontent.com/assets/6066015/14284478/05b751bc-fb48-11e5-8e68-9d6e709021b4.PNG)

ça ressemble à un oubli.

**Comment by GerardPaligot** [comment]
Doublon https://github.com/zestedesavoir/zds-site/issues/3496
