### ISSUE TITLE
[v18] Les boites s'emboitent dans l'editeur markdown

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3513]
Version 18
Navigateut Firefox
OS : Android 6

En essayant de selectionner un smiley ou un code depuis l'editeur JS je n'arrive plus a fermer les boites sans reactualiser mon navigateur sur mobile. Ce qui me fait perdre le contenu de ma saisie en cours.

Voici un aperçu du problème.
![screenshot_20160405-194945](https://cloud.githubusercontent.com/assets/6066015/14292503/a8bd970c-fb68-11e5-9cbc-1b1b3b4ac47a.png)

**Comment by artragis** [comment]
Reproduit sur firefox + windows

**Comment by Emeric54** [comment]
Le correctif est passé, on peut donc fermer ici. @sandhose
