### ISSUE TITLE
[Membre] Profil inaccessible lors de la présence de caractères spéciaux

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#352]
Certains membres tels que @drien n'ont pas accès à leur profil, probablement à cause du caractère "@" dans l'URL

Il serait bon d'y ajouter l'id de l'utilisateur, comme partout ailleurs sur le site.

**Comment by Alex-D** [comment]
Il semblerait que tous les textes affichés contenant des caractères spéciaux fassent bugguer la page, et que cela ne vienne pas de l'URL (ou pas uniquement de là).

**Comment by firm1** [comment]
C'est corrigé.
