### ISSUE TITLE
[beta v18] C'est possible de créer deux tags avec le même slug

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#3535]
Par exemple, utiliser le tag `python` et `python?` ;  ça sera deux tags distincts, mais avec le même slug. Du coup, erreur 500: https://beta.zestedesavoir.com/contenus/?tag=python

**Comment by GerardPaligot** [comment]
@gustavi Tu confirmes que c'est bon suite à ton merge ?

**Comment by gustavi** [comment]
@GerardPaligot qui me laisse même pas le temps de fermer les issues ^^
