### ISSUE TITLE
[v18] Les invités peuvent voir le bouton suivre ce contenu

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3545]
Lorsqu'on est en mode invité sur un article ([celui-ci](https://beta.zestedesavoir.com/articles/1214/magasins-mise-a-disposition-dequipement-scientifique/) par exemple) on voit le bouton "suivre ce contenu" qui forcément ne fonctionne pas puisqu'on est invité.

Il ne faut l'afficher que lorsqu'on est connecté.

**Comment by GerardPaligot** [comment]
Bien vu, normalement l'héritage dans les templates auraient du cacher les blocs actions aux utilisateurs invités mais je suppose que cet héritage ne couvrait pas les templates des tutos.
