### ISSUE TITLE
[v18] Les votes positifs sont encore anonymes

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3547]
Aujourd'hui les votes positifs, contrairement aux votes négatifs sont anonymes quand on survolent les pouces verts.

Pour comprendre le bug, allez sur ce message : https://beta.zestedesavoir.com/forums/sujet/5766/nuits-debout-votre-avis/?page=4#p105466 (à l'heure ou je crée l'issue il y a 2 votes positifs et deux votes négatifs).

On voit clairement en survolant les votes négatifs qui sont les opposant à ce message, mais on ne peux pas savoir (en survolant les votes positifs cette fois) qui sont les partisans de ce message. Le problème est général sur l'ensemble du topic et ailleurs aussi.

En résumé les votes positifs ne sont pas désanonymises

**Comment by pierre-24** [comment]
Pas d'accord, je viens de voter positif [là](https://beta.zestedesavoir.com/forums/sujet/5766/nuits-debout-votre-avis/#p105343) et je suis bien comptabilisé ET visible.  Ou j'ai pas compris ^^

**Comment by pierre-24** [comment]
(et [là](https://beta.zestedesavoir.com/forums/sujet/5766/nuits-debout-votre-avis/#p105347), y'a Spacefox aussi).

**Comment by SpaceFox** [comment]
Ce sont 2 votes anonymes.

Je viens de dé-voter et re-voter, et maintenant on voit 1 vote anonyme et le mien.

Les votes positifs (postérieurs à la date de mise en bêta) sont donc bien désanonymisés.

**Comment by firm1** [comment]
Bizarre, ça veut dire que c'est la clé de limitation des votes négatifs dans le settings_prod.py n'a pas été prise le même jour que celle des votes psotifs.

**Comment by SpaceFox** [comment]
Il n'y a qu'une clé.
