### ISSUE TITLE
Nettoyer l'index de recherche quand un contenu change de structure

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#3549]
[Voir le cas qui s'est produit](https://zestedesavoir.com/forums/sujet/5848/erreur-404-en-suivant-un-lien/)

Étant donné que c'est au niveau de la recherche, je suppose que le contenu en question a déjà été publié, non ?

Quand un contenu change de structure (exemple, il passe de big-tuto à moyen-tuto), les URLs changent forcément. Ce qui donne des liens morts dans la recherche.

**Comment by DevHugo** [comment]
Faudrait confirmer mais je pense qu'ils ont créé un autre tutoriel, peut-être que mon script d'indexation est trop con pour supprimer les anciens tutos

**Comment by gustavi** [comment]
Est-ce que ajouter `reindex_content` (`zds.search.utils`) [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/publication_utils.py#L23) corrigerai le problème ?

**Comment by DevHugo** [comment]
Normalement lors de la publication du contenu, le flag must_reindex est mis à [True](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/publication_utils.py#L123).

Quand la commande [index_content](https://github.com/zestedesavoir/zds-site/blob/dev/zds/search/management/commands/index_content.py) passe elle appelle la fonction `reindex_content`.

**Comment by pierre-24** [comment]
Bon, ça, c'est bon. C'est testé et tout.
