### ISSUE TITLE
Problème d'affichage sur les votes

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3551]
Il vaut se rendre sur [cette page](https://zestedesavoir.com/forums/sujet/5853/petite-questions/#p106549) et on a ça :

![Humm ...](http://i.imgur.com/lFQODvU.png)

Il n'y a pas de vote appliqué et je ne suis pas le seul avec ce bug.

**Comment by sandhose** [comment]
Problème de concurrence des votes, déjà résolu avec la désanonymisation dans la v18

**Comment by gustavi** [comment]
Je laisse ouvert jusqu'à la v18 pour être sûr, tellement de problèmes avec ces votes.

**Comment by artragis** [comment]
Si c'est résolu, pourquoi on laisse ouvert alors qu'on est en train de courrir après la fin de cette release?

**Comment by gustavi** [comment]
Parce qu'on a apas vérifié sur la beta/prod si c'était OK. Combien de fois on a corrigé ce bug des votes ? Je crois @sandhose mais on est jamais à l’abri d'un problème, autant être prudent.

**Comment by artragis** [comment]
Le problème semble réglé sur la béta. On peut fermer siouplet
