### ISSUE TITLE
Problème lors de la suppression de contenus avec le même nom

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3553]
Via le [forum](https://zestedesavoir.com/forums/sujet/5862/quand-un-article-et-un-tuto-ont-le-meme-nom-la-suppression-cause-des-404/?page=1#p106668) : 

> Quand un article et un tutoriel ont le même nom, supprimer l'un semble aussi supprimer aussi l'autre, ou tout du moins le rend inaccessible avec une belle erreur 404. Cela vient de m'arriver avec un de mes tutoriel, quand j'ai décidé de migrer un article pas encore paru en tutoriel à grand coup de copier-coller. En supprimant l'article, le tutoriel est devenu inaccessible : il est toujours présent dans la liste des tutoriels, mais j'obtiens une 404 quand j'essaie d'y accéder. A noter que la galerie n'a pas disparue et est toujours liée au tutoriel, pas à l'article (qui a bien été supprimé sans problème).
> 
> C'est le genre de bug qui fait dire "Aie".

**Comment by gustavi** [comment]
Après un test en local impossible de reproduire. De même que sur la prod. Je vais voir avec Mewtow si c'est du vieux contenu.

EDIT : c'est pas du vieux contenu. C'est donc vraiment un bug.

**Comment by artragis** [comment]
J'ai la vague impression que cela est dû non seulement à un problème de nom mais aussi de slug, comme si il avait créé un article et un tuto avec le même slug. Je pense que cela est dû au fait qu'il en a importé un depuis l'archive tiré de l'article initial.

Faudra que je revérifie car j'ai rien trouvé de probant dans le code sinon un manque de factorisation.
