### ISSUE TITLE
Notification persistente et un MP n'est pas arrivé

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#3555]
Hello tout le monde !

Je suis victime d'un bug récemment, et je suis presque persuadé que c'est une régression (car j'avais fait parti de ceux qui avait codé le truc à la base si ma mémoire est bonne :D )

Voilà le truc. J'étais dans un groupe (CA) et donc je pouvais poster dans des fofos privés (CA et staff). N'étant plus membre du CA depuis la dernière AG, j'ai logiquement été enlevé de ce groupe. MAIS j'avais une notif' à lire dans un des fofos privés. Lors de mon changement de groupe, cette dernière aurait du partir mais pourtant elle reste là (et me mène vers une 403 évidemment).

Aussi j'aurais du recevoir un MP pour me dire que j'avais changé de groupe et dans quelle groupe je suis maintenant mais je n'ai rien reçu...

Voili voilou, bon courage les coupains !

(PS: version 17.1 à l'heure d'écriture de ces lignes. Je n'ai toujours pas viré la notif persistante si vous voulez que je fasse des tests, mais je compte réussir à la dégager dans le courant de la semaine en cliquant sur la croix de désabonnement du sujet (je pense que ca marchera...))

**Comment by GerardPaligot** [comment]
Est-ce que le fait de passer par l'espace admin ne bypasse pas la lecture des notifications actives et la réception du MP ? Si oui, je me demande si la personne qui t'a retiré tes droits n'est pas passé par là (cc @SpaceFox je suppose).

**Comment by Eskimon** [comment]
Ca serait sympa si un super-admin pouvait me remettre puis enlevé du groupe Staff et CA via la bonne interface (celle de mon profil) car sinon les notifs commencent a s'accumuler, il va falloir que je me desinscrive a la main de chaque sujet, c'est naze ^^

**Comment by firm1** [comment]
Je t'ai rajouté puis supprimé du groupe CA via la bonne interface cette
fois.

Visiblement ça a été fait via la mauvaise interface (celle de django) la
premiere fois.

Je ne sais pas du coup qui d'autre est dans ton cas, mais il faudrait
corriger pour tout les autres aussi.

**Comment by Eskimon** [comment]
Ca a corrigé les soucis pour moi. Du coup je ferme ce ticket qui n'a pas vraiment de raison d'être :)
