### ISSUE TITLE
Créé des webhooks pour l'api des messages

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#3556]
Salut à tous,

Je pensais à un truc ça serai sympa de faire des webhooks pour l'api des mp, une appli s'enregistre comme quoi elle veut être prévenue sur telle adresse qu'il y'a un message qui est arrivé. Zeste de savoir envoit un POST sur l'url.

**Comment by GerardPaligot** [comment]
Tu parles de webhook, de push notification ou des 2 ? Parce que les webhooks pour ZdS, j'en vois pas trop l'utilité, contrairement aux pushs.

**Comment by DevHugo** [comment]
Un peu des deux, je pensais que faire des notifications était quand même compliqué, faire un serveur de notification, c'est quand même assez chiant (faut en place des websockets et tout). 
Je me disais qu'on pourrait mettre en place, un système de webhook, c'est vachement plus simple et après libre au dev de mettre en place leurs serveurs de notifications si ils veulent. Comme ça on peut mettre le notre un peu plus tard et pas ralentir les autres devs externes.

Le serveurs de notifications, c'est le mieux mais en attendant des webhooks, c'est bien aussi.

**Comment by gustavi** [comment]
Comme d'habitude : discussions et suggestions => forums.

**Comment by gustavi** [comment]
À discuter sur le forum. Et surtout attendre les prochaiens versions de Django.
