### ISSUE TITLE
Impossible de créer une nouvelle base sous Postgresql

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#356]
Si je crée une nouvelle base sous Postgresql depuis le refactoring des scripts de création de table, j'obtiens :
- Soit une erreur sur la création d'une FK (articles --> util, util pas encore créé), sans doute à cause de ça : http://andrewingram.net/2012/dec/common-pitfalls-django-south/
- Soit, si j'essaie de forcer l'ordre de création (exemple : `python manage.py migrate member` puis `python manage.py migrate mp`) j'obtiens une erreur `duplicate key value violates unique constraint, DETAIL: Key (id)=(1) already exists`, sans doute à cause de ça : https://www.vlent.nl/weblog/2011/05/06/integrityerror-duplicate-key-value-violates-unique-constraint/ 

Résutlat : on ne peut plus créer de nouvelle base ZdS sous Postgresql... ce qui est ennuyeux, puisque c'est notre SGBD.
C'est un bug spécifique à Postgresql : le script fonctionne nickel sous Sqlite ou MySQL.

**Comment by firm1** [comment]
Ah je vois, il me semble qu'il faut d'abord faire `python manage.py migrate utils` avant de faire le reste. Car utils est l'app dont dépend tout le monde.

**Comment by SpaceFox** [comment]
Ca ne suffit pas, c'est le point n°2 :)

**Comment by firm1** [comment]
J'ai pourtant réussi a créer un base vierge sur la prod hier.

A étudier.

**Comment by SpaceFox** [comment]
A priori en mettant les applications dans le bon ordre ça marche... je confirme et corrige ça.

**Comment by SpaceFox** [comment]
Commité, corrigé, je ferme :)
