### ISSUE TITLE
Supprimer les « warning » lors de la génération de la documentation

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3560]
Actuellement (`sphinx==1.3.6`) j'ai : `build succeeded, 17 warnings.` et avec la dernière version de sphinx j'en ai 3 de plus. La majorité est corrigeable facilement.

Il y a un « warning » qui n'est pas à corriger ici mais dans une PR à part, cf https://github.com/zestedesavoir/zds-site/issues/3561

**Comment by AmarOk1412** [comment]
@artragis cette issue n'est plus d'actualité je pense :)
