### ISSUE TITLE
Le modèle « Category » existe deux fois

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3561]
Et ça c'est pas vraiment une bonne pratique. J'ai trouvé ça en générant le doc : 

```
/home/augustin/.virtualenvs/zds/zds-site/zds/utils/models.py:docstring of zds.utils.models.SubCategory.get_parent_category:None: WARNING: more than one target found for cross-reference u'Category': zds.utils.models.Category, zds.forum.models.Category
```

Il va falloir penser à en renommer un.

**Comment by nils-van-zuijlen** [comment]
À quoi sert `zds.utils.models.Category` d'ailleurs ? Sa docstring est tout sauf explicite.

**Comment by gllmc** [comment]
Ce sont les catégories des publications.
