### ISSUE TITLE
Le titre des pages de validation n'est pas correcte

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3563]
Lorsque je me rends sur les pages : 
- https://zestedesavoir.com/validations/?type=article
- https://zestedesavoir.com/validations/?type=tuto

Le titre (contenu dans la balise `<title>`) de la page est `Validation . Validation . Zeste de Savoir`

Je suppose que le deuxième "Validation" que l'on voit dans le titre devrait être "Tutoriel" ou "Article"

**Comment by GerardPaligot** [comment]
Préfère une capture pour ce genre de choses. Tout le monde ne peut pas utiliser tes liens.

**Comment by firm1** [comment]
Voilà mon capichef :dancer: 

![noice](https://cloud.githubusercontent.com/assets/6066015/14885964/921dc42a-0d4e-11e6-8cca-fc3d2383602b.PNG)
