### ISSUE TITLE
[Forum] Antispam inefficace pour la première réponse à un sujet

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#357]
Lorsque l'auteur d'un sujet se répond lui-même, l'antispam ne fait pas son travail. Dans les autres cas ça a l'air de fonctionner.

**Comment by SpaceFox** [comment]
Je prends.
Je suppose un effet de bord de `last_answer` sur un forum qui répond `None` s'il n'y a qu'un post (ce qui avait été fait pour corriger un autre bug, mais je ne sais plus du tout quoi...)

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé
