### ISSUE TITLE
Requirement de dev nécessaires en run

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3570]
Ce if https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L287-L290 ne fonctionne pas : par défaut on est en debug, donc le système s'attends à avoir `debug_toolbar` d'installée.

**Comment by gustavi** [comment]
Deux choses : 
- c'est le cas car un serveur de prod ne doit en aucun cas être en `DEBUG=True`
- si jamais on décide qu'on peut avoir `DEBUG=True` en cas de tests sur une version de prod alors il faut l'ajouter dans `requirements.txt`.

**Comment by firm1** [comment]
En fait je pense que les propos de @SpaceFox ici c'était pour dire que le code du fichier `settings.py` rend la `debug_toolbar` necessaire pour installer une prod alors que c'est une dépendance qui est par nature une dépendance de dev.

Une solution correcte pour cette issue serait de simplement déplacer [le fameux bloc](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L287-L290) à la fin du fichier ([après cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L583) donc).

On reste sur un mode par défaut en `DEBUG` pour la dev, mais dès lors qu'on a un `settings_prod.py` qui surcharge le `settings.py` pour une conf de prod, la `debug_toolbar` devient facultative. ça devrais donc permettre d'arriver à ce qu'on veut.
