### ISSUE TITLE
Les confs nginx (et gunicorn ?) de la bêta et de la prod sont TOUJOURS différentes

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3572]
… et ça fait littéralement **des mois** qu'on me promet que ça va être corrigé.

J'en ai marre, je viens _encore_ de perdre environ une heure à cause de ça.

Je décide donc une grève : je ne touche plus aux environnements de prod et de bêta tant que ce n'est pas réparé. C'est non négociable, j'ai déjà été beaucoup trop sympa sur ce point.

Ça inclus le déploiement de la v18. En admettant qu'on ait quelque chose à déployer un jour.

**Comment by gustavi** [comment]
Ça concerne qui cette issue ?

**Comment by GerardPaligot** [comment]
Je suppose @sandhose
