### ISSUE TITLE
erreur 500 quand on répond + notif à soie même

### ISSUE THREAD

**Issue by La-source** [zestedesavoir/zds-site#3576]
Bonjour,

Depuis ce matin j'ai remarqué que lorsque je répond à un sujet je me chope à chaque fois une erreur 500, le message est bien enregistrer mais du coup cette erreur est étrange.

Par ailleurs, je reçois une notification pour le message que je viens de poster.

![auto notif](https://cloud.githubusercontent.com/assets/10511322/14950190/1e827240-1050-11e6-814c-9d1b099e33db.PNG)

**Comment by GerardPaligot** [comment]
Salut @La-source,

Toute la plateforme semble instable ce matin. Un peu tout le monde se prend des erreurs 500 pour un peu près n'importe quoi.

**Comment by gustavi** [comment]
Bonjour,

Nous sommes au courant pour les 500, on est dessus. Pour le reste c'est connu.

Merci du retour (à l'avenir préfère toutefois le forum ;) ).

**Comment by GerardPaligot** [comment]
> Merci du retour (à l'avenir préfère toutefois le forum ;) ).

Dans la mesure où ZdS est instable ...

**Comment by La-source** [comment]
Eu... je croyais que les bug devaient plutôt être traité sur github justement... chaque fois que quelqu'un poste un rapport de bug il est reporté sur github alors je me suis dit qu'autant directement le tapé au bon endroit.. non ?

**Comment by gustavi** [comment]
C'est pour filtrer, le bug est déjà connu https://github.com/zestedesavoir/zds-site/issues/3259
