### ISSUE TITLE
[v18][RC5] Impossible de lire un sujet

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3587]
En allant sur la beta, il m'est impossible de lire un sujet, ou tout simplement d'aller sur un forum. Je tombe sur une erreur 500 de nginx (et pas de django) comme si le serveur attendais une reponse pendant trop longtemps.

Les pages incriminées me font penser que le probleme se situe dans la liste des derniers sujets suivis que l'on affiche dans la sidebar.

Voila.

**Comment by GerardPaligot** [comment]
@sandhose @gustavi Il y a eu des problèmes dans la migration des notifications ? oO

**Comment by firm1** [comment]
Je précise que ça n'arrive qu'en mode connecté donc le problème vient bien des sujets suivis

**Comment by gustavi** [comment]
Pas à ma connaissance. Je serai dispo qu'à partir de lundi dans la journée, mon réseau ressmble à ça quand tout va bien : 

```
519 packets transmitted, 313 received, +24 errors, 39% packet loss, time 556362ms
rtt min/avg/max/mdev = 33.107/1873.261/11621.954/2680.270 ms, pipe 12
```

**Comment by GerardPaligot** [comment]
Pas d'inquiétude. Le problème a été identifié et est expliqué dans ma PR https://github.com/zestedesavoir/zds-site/pull/3594
