### ISSUE TITLE
[v18][RC5] le titre de la page de filtre des contenus par tag n'est pas correct

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3589]
Url : https://beta.zestedesavoir.com/contenus/?tag=windows

On voit dans la barre de titre le titre `<Tag: windows>` , comme le montre les captures ci-dessous.

![capture d ecran de 2016-05-07 11-10-11](https://cloud.githubusercontent.com/assets/6066015/15091277/49ed3760-1444-11e6-9147-a370dc8f1370.png)

![capture d ecran de 2016-05-07 11-10-52](https://cloud.githubusercontent.com/assets/6066015/15091282/6add009a-1444-11e6-952e-e812696b1117.png)

**Comment by orandin** [comment]
:information_source:  **Je prends**

**Comment by gustavi** [comment]
Ça aussi je l'ai déjà corrigé ... Des choses louches

**Comment by gustavi** [comment]
@orandin tu peux mettre à jour ta PR ?

**Comment by gustavi** [comment]
Tu peux faire d'une pirre deux coups avec https://github.com/zestedesavoir/zds-site/issues/3588 car c'est quasiment la même chose.

**Comment by GerardPaligot** [comment]
Merci @orandin !
