### ISSUE TITLE
[Forum] Désactiver l'anti-flood pour le staff

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#359]
Il serait plus que pratique de ne pas avoir d'antiflood quand on est staff.

**Comment by firm1** [comment]
Je ne suis pas d'accord.

**Comment by Alex-D** [comment]
Arrf, je pensais que c'était 24h, or ça n'est que 15 min. Sorry, je suis d'accord avec le fait que tu ne sois pas d'accord.
