### ISSUE TITLE
[v18][RC5] le bloc de présentation du site prend plus de place en hauteur qu'avant

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3590]
Le bloc de présentation du site, lorsqu'on est en mode déconnecté prend maintenant plus de place en hauteur. Pour les petits écran, c'est moins pratique, car les Unes deviennent moins visibles.

Cf. La capture animée ci-dessous.

![1462612674 4056animation3](https://cloud.githubusercontent.com/assets/6066015/15091309/c039a024-1445-11e6-98f9-5f1935a6429a.gif)

**Comment by GerardPaligot** [comment]
Cette évolution est voulue.

**Comment by SpaceFox** [comment]
Si c'est vraiment gênant, on pourrait peut-être diminuer la marge entre
l'en-tête et le début de la présentation ?

2016-05-07 12:17 GMT+02:00 Gérard Paligot notifications@github.com:
