### ISSUE TITLE
[v18][RC5] On a des tags en double dans la liste de tous les tags

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3591]
L'url à laquelle on observer ce phénomène est la suivante : https://beta.zestedesavoir.com/contenus/tags/

La capture d'écran suivante nous montre certains tag en double avec à chaque fois un seul contenu.

![capture d ecran de 2016-05-07 11-26-14](https://cloud.githubusercontent.com/assets/6066015/15091331/b63fbd64-1446-11e6-9b1f-56d4c118d958.png)

**Comment by DevHugo** [comment]
ça à l'air de se produire, quand le tag dépasse le nombre de caractères autorisé et que le tag à plusieurs contenu associé. ça créé un tag par contenu.

**Comment by GerardPaligot** [comment]
En fait, un même tag semble être créé plusieurs fois. Quand on clique sur un item, on obtient la surprise suivante :

![capture d ecran 2016-05-09 a 11 26 51](https://cloud.githubusercontent.com/assets/1913901/15108942/21fecb42-15d9-11e6-8b9a-c8fe6b2c4846.png)

**Comment by gustavi** [comment]
Je vais vérifier sur la nouvelle BDD propre mais c'est possible que ça soit lié à #3588 et à la correction que j'ai apporté. Je confirme ça soon.

**Comment by gustavi** [comment]
Fixé par @artragis
