### ISSUE TITLE
Revoir l'icône sur le page « Tous les contenus »

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3593]
La v18 met un peut plus en avant le concept de contenu, notamment grâce à la page : https://beta.zestedesavoir.com/contenus/

Avant on avait : 

[Tout les articles](https://beta.zestedesavoir.com/articles/) : 
![capture d ecran de 2016-05-07 11-51-27](https://cloud.githubusercontent.com/assets/6066015/15091457/0ddaef3c-144a-11e6-812e-acb6d0d37212.png)

[Tous les tuoriels](https://beta.zestedesavoir.com/tutoriels/) : 
![capture d ecran de 2016-05-07 11-51-20](https://cloud.githubusercontent.com/assets/6066015/15091459/151729e6-144a-11e6-9433-21f10918fd3c.png)

Maintenant on à en plus [Tous les contenus](https://beta.zestedesavoir.com/contenus/) : 
![capture d ecran de 2016-05-07 11-51-12](https://cloud.githubusercontent.com/assets/6066015/15091460/1ee3964e-144a-11e6-94e6-77904a9f64d8.png)

Comme on le voit dans la dernière capture, l’icône associée aux contenus est la même que l'icone des articles. Ce qui crée de la confusion dans mon esprit. Il faudrait (si on veut vraiment garder ce concept) avoir un élément visuel qui l’identifie clairement. Car on a du mal à savoir ou est-ce qu'on se trouve assez facilement.

**Comment by artragis** [comment]
même si cela est vrai, je propose de détagger cette issue v18 et de la résoudre dans le process de développement normal.

**Comment by GerardPaligot** [comment]
Elle rentre dans le cadre de la release v18 et sera sans doute comptée comme une issue encore ouverte lors de la release mais elle n'est en aucun cas bloquante pour la release.

**Comment by gustavi** [comment]
Justement ça sera corrigé après donc il ne faut pas la mettre ici non ?

Pour le coup je suis au courant, c'est même volontaire. Si quelqu'un veut me faire une icône c'est avec plaisir car c'est pas dans mes compétences (et c'est pas faute d'avoir demandé).

**Comment by Situphen** [comment]
Plus d'actualité avec la v25, je ferme
