### ISSUE TITLE
[Forum] Possibilité de voir le contenu d'un message masqué

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#360]
Il serait pratique de pouvoir voir le contenu d'un message modéré sans avoir à le rendre visible publiquement puis à le re-masquer.

Je pense que c'est de mon ressort dans les templates, et que c'est lié au front-end, donc pas urgent.

**Comment by coma94** [comment]
Je passe juste pour dire un gros +1, c'est chiant de ne pas pouvoir voir le contenu d'un message masqué sans l'afficher à tous.

**Comment by firm1** [comment]
F'xd
