### ISSUE TITLE
Corriger l'input de recherche sur la page d'accueil sur Safari

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3600]
Le problème est décrit sur [le forum](https://zestedesavoir.com/forums/sujet/5844/champ-de-recherche-avec-outline-par-defaut-rend-mal-sous-safari/) et la solution est [ici](https://github.com/zestedesavoir/zds-site/pull/3543#issuecomment-217457418).

**Comment by A-312** [comment]
Le problème est toujours d'actualité ?
