### ISSUE TITLE
Insérer un lien via le bouton de l'éditeur remet le scroll en haut de page

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3604]
Insérer un lien via le bouton de l'éditeur (sélectionner du texte, cliquer sur le bouton, indiquer l'URL, valider) remet le scroll en haut de page.

**Comment by WinXaito** [comment]
De mémoire c'est pour toutes les popups (Image entre-autres)

**Comment by LudovicDrtt** [comment]
ça me le fait aussi quand je charge un aperçu sur l'éditeur de section dans un tuto.

**Comment by GerardPaligot** [comment]
@gustavi Sur quoi tu te bases pour marquer l'issue comme "Facile" ?

**Comment by Situphen** [comment]
@LudoBike : alors, j'ai vérifié et effectivement lors de l'aperçu d'une section de tutoriel la page se recharge donc tu remontes en haut de la page. Je ne crois pas que ce soit un bug, l'aperçu des messages se fait en arrière-plan mais pas pour la rédaction de contenus.
