### ISSUE TITLE
Mettre le champ date de publication au type date sur la page des Unes

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3605]
> Dans la page pour insérer une Une (pour le Staff, donc), le champ date de publication mériterait à être de type date justement, sinon c'est galère de rentrer la date manuellement au bon format.

**Comment by Emeric54** [comment]
Sinon, on peut même utiiser un _datepicker_.

**Comment by firm1** [comment]
Les deux ne sont pas incompatibles.

**Comment by viki53** [comment]
Hello, avec la v18 j'ai l'impression que ça a tout cassé : on a un input `text` avec une date affichée au format français, mais impossible de l'enregistrer (en tout cas sur une édition pour mettre dans le passé).

**Comment by gllmc** [comment]
Corrigé par #4450.
