### ISSUE TITLE
Revoir la page de contact

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3609]
D'après ce qui a été décidé au CA du 12 Mai 2016, une évolution est à apporter sur la page de contact :
- Lister l'équipe communication ;
- Lister le bureau ;
- Pour chaque groupe, donner le responsable.

Voici les responsables :
- Equipe association : Kje
- Equipe communication : ShigeruM
- Equipe staff : Thunderseb
- Equipe technique : Andr0

**Comment by GerardPaligot** [comment]
@SpaceFox @firm1 @cgabard @gustavi @vhf 

Est-ce que l'un de vous pourrait fournir la liste des groupes présent sur ZdS pour permettre de développer cette issue ?

**Comment by gustavi** [comment]
J'ai pas les accès à ce niveau là.

**Comment by GerardPaligot** [comment]
Ah, je pensais que SpaceFox vous avait déjà donné ces accès. Bon alors, je ping uniquement les 3 premiers. :)

**Comment by firm1** [comment]
Les groupes existants sont : 
- bot
- CA
- Communication
- devs
- staffs
- stuff-anonymes

Le derniers, je crois qu'il ne devrait plus exister.

**Comment by cgabard** [comment]
Il faudrait donc rajouter un groupe "bureau" (et peut être mettre a jour la liste des dev)
