### ISSUE TITLE
[Alertes] La page "toutes les alertes" n'existe pas ou est inaccessible

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#361]
La page "toutes les alertes" n'existe pas ou n'est pas liée (pas de lien présent) dans le menu dans la logbox dédié aux alertes.

**Comment by SpaceFox** [comment]
En regardant rapidement, cette page n'existe pas _du tout_.

**Comment by Alex-D** [comment]
Il faudrait donc la créer. Car elle manque à l'appel.

**Comment by firm1** [comment]
En fait, que devrait contenir une telle page ?

Pour moi, on stocke déjà toutes les alertes dans la boite sur la home. S'il y'a 100 alertes, on y seront.

Etant donné que toute alerte traitée est supprimée de la base, on a donc pas d'historique des alertes cloturées. Donc ma question est : que devrait contenir une page "Toutes les alertes" en plus de ce qu'on à déjà ?

**Comment by Alex-D** [comment]
Proposer un affichage sur une page dédiée, notamment pour les mobiles; Et limiter le nombre de notifs/alertes sur la home me semble pas mauvais non plus (vers 20 ça me semble déjà bien).

**Comment by SpaceFox** [comment]
Je vois un truc qui m'étonne beaucoup sur cette ligne : https://github.com/Taluu/ZesteDeSavoir/blob/release-beta-1.0/zds/utils/models.py#L189

Si j'ai bien compris, un Comment peut avoir plusieurs Alerts, mais une Alert ne devrait avoir qu'un seul Comment. En tous cas, j'ai pas d'exemple en tête d'alerte pertinente sur _plusieurs_ messages.

Donc, à la place de cette relation, on devrait avoir quelque chose comme ça [juste après cette ligne](https://github.com/Taluu/ZesteDeSavoir/blob/release-beta-1.0/zds/utils/models.py#L27) dans Alert :

``` python
comment = models.ForeignKey(Comment)
```

Je préfère vous en parler avant parce que ça risque d'avoir des impacts non négligeables au niveau du modèle de données. Des objections ?

**Comment by Alex-D** [comment]
En effet, il faut : Comment - ManyToOne - Alert

**Comment by Alex-D** [comment]
FAIL... C'est l'inverse ><"

Comment - OneToMany - Alert. C'est mieux.

**Comment by SpaceFox** [comment]
Si j'ai bien compris, ça se matérialise par un model.ForeignKey en Django :
https://docs.djangoproject.com/en/1.6/ref/models/fields/#foreignkey

Du coup on est d'accord ?

**Comment by Alex-D** [comment]
Aucune idée pour le ForeignKey (mais vu le mot-clé ça me semble être ça). Mais complètement d'accord sur le principe en effet.

**Comment by SpaceFox** [comment]
Remplacé par la #476 , plus générique.
