### ISSUE TITLE
Les archives d’articles n’ont pas de dossier racine

### ISSUE THREAD

**Issue by lthms** [zestedesavoir/zds-site#3610]
Du coup, le contenu est à la racine, alors qu’on aurait pu s’attendre à ce qu’ils soient dans un dossier du nom du tuto (son slug ?).

De ce que j’en sais c’est une bonne pratique de mettre le contenu d’une archive dans un dossier.

Je n’ai pas vu d’issues à ce sujet, donc je me permets d’en créer une.

**Comment by pierre-24** [comment]
> De ce que j’en sais c’est une bonne pratique de mettre le contenu d’une archive dans un dossier.

Je ne sais pas d'où tu sort ça ^^

Ceci étant dit, je pense qu'on en avais déjà discuté à un moment, à cause du fait que Mac OSX fait ça par défaut. On peut changer ça, mais il faudrait assurer la rétrocompatibilité (ou @firm1 qui fait Zest'Writer va pas être content), et ensuite ça ne change pas grand chose ...

**Comment by firm1** [comment]
Ne vous inquiétez pas pour moi, Zest Writer saura s'adapter. On est assez
flexible.

Le ven. 13 mai 2016 18:11, Pierre Beaujean notifications@github.com a
écrit :

**Comment by pierre-24** [comment]
Soit ;)

Mais la question c'est ... Est ce que c'est réellement important ?

**Comment by firm1** [comment]
Oh bah je vois pas trop l'interet non plus, et perso ça me convient bien en
l'état

Le sam. 14 mai 2016 11:59, Pierre Beaujean notifications@github.com a
écrit :

**Comment by lthms** [comment]
> Je ne sais pas d'où tu sort ça ^^

Il me semblait, mais on m’a pourtant appris à me méfier des vraies fausses vérités générales. Il semblerait en effet que je me sois inventée celle là tout seul, désolé.

Donc je concluerai que je préfère personnellement. Ça permet de ne pas désarchiver le truc dans un dossier, mais bon finalement c’est juste de l’affect et que donc, vous pouvez juste ignorer ça si la solution courante vous va.

Désolé pour le dérangement.

**Comment by gustavi** [comment]
Pas de souci. Tu peux toujours faire ce genre de proposition sur le forum, c'est plus pratique ;)
