### ISSUE TITLE
[beta v18] L'URL mes tuto/articles dans les MP de migration ZEP-25 est invalide

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#3614]
Via https://zestedesavoir.com/forums/sujet/6064/on-ne-lattendait-plus-voici-la-v18/?page=1#p110019

Même problème que pour le `Bonjour {0},`, l'URL de ces deux liens utilise le PK de l'utilisateur, qui est donc mal substitué [ici](https://github.com/zestedesavoir/zds-site/blob/release-v18/zds/tutorialv2/management/commands/migrate_to_zep25.py#L156)

Question à part, une raison de pourquoi ce message est pas dans un fichier à part ? Même si c'est juste pour une migration, c'est plus propre, nan ? :o 

ping @gustavi

**Comment by gustavi** [comment]
Parce que ça ne va servir qu'une fois donc osef.

**Comment by gustavi** [comment]
Il semblerait que la v18 soit OK. D'après le Sentry pas de bug relevé depuis la dernière RC.
