### ISSUE TITLE
Revoir l'ordre d'affiche des catégories du menu

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#3615]
Via https://zestedesavoir.com/forums/sujet/6064/on-ne-lattendait-plus-voici-la-v18/?page=1#p110015

Actuellement, les catégories `Autre` des différentes "grandes catégories" se trouvent en plein milieu de la liste, et ça fait bizarre. Dans l'idéal, elles devraient à chaque fois se trouver en bas de chaque liste.

**Comment by gustavi** [comment]
C'est car on affiche par ordre alphabétique. Il faut ajouter un champs `position` et classer avec, c'est pas vital pour la v18.

**Comment by DevHugo** [comment]
Tu peux tagger en facile, non ?

**Comment by GerardPaligot** [comment]
C'est pas si simple que ça (pour un débutant j'entends). Faut quand même mettre à jour un modèle existant ce qui veut générer un fichier de migration, avoir un script de migration des catégories existantes et puis, appliquer l'ordre selon la position de la catégorie dans le dropdown.

Pour nous, c'est simple. Je suis pas certain que ça soit pareil pour des nouveaux contributeurs.

**Comment by DevHugo** [comment]
Ok, tu as surement raison.

**Comment by gustavi** [comment]
@GerardPaligot a tout à fait raison. Je corrigerai ça et j'en profiterai pour apporter quelques améliorations par rapport à la ZEP-25.

**Comment by FanJiyong** [comment]
Salut à tous,

Bon y'a un PO feedback, du coup je répond : 

Oui c'est bizarre faudrait le mettre en bas de liste…  

facile ? pas facile ? au final vous avez la réponse ? 

La dernière réponse date de mai, est-ce qu'il vous manque des éléments pour pouvoir avancer ?
