### ISSUE TITLE
Erreur 500

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#3618]
Bonjour, il ne me semble pas avoir vu une issue la dessus d'aujourd'hui.

Depuis ce matin je j'arrive plus accéder au site, erreur 500.

**Comment by gustavi** [comment]
Bonjour, nous sommes au courrant rassure toi. Nous travaillons a résoudre le problème dans les plus brefs délais.

**Comment by WinXaito** [comment]
Merci, en passant vous avez déjà une idée du problème ?

**Comment by gustavi** [comment]
En partie, nous communiquerons sur les forums pour vous donner plus d'informations.

**Comment by Fumble** [comment]
Ceci dit, la catégorie VPS est rouge sur [la page des travaux d'OVH](http://travaux.ovh.net/). D'ici à ce que ce soit chez eux...

**Comment by gustavi** [comment]
Pour le coup le serveur était totalement HS depuis 40 minutes donc j'ai pris l'initiative de le reboot (ce qui a marché pour la panne de 12h41) sauf que là il ne répond plus du tout, @SpaceFox va le hard reboot des qu'il peut.

**Comment by SpaceFox** [comment]
Ce ne sera « jamais », le compte de l'asso n'a pas les droits pour hard reboot ou se connecter en console. Parce que si le compte de l'asso est celui de l'asso, le compte gestionnaire technique est un compte inconnu, je suppose celui de Devock…

**Comment by WinXaito** [comment]
Le site est à nouveau opérationnel, qu'est-ce qui a donc résolu le problème ?

**Comment by WinXaito** [comment]
> Parce que si le compte de l'asso est celui de l'asso, le compte gestionnaire technique est un compte inconnu, je suppose celui de Devock…

Ca sera réglé quand ce problème ?

**Comment by SpaceFox** [comment]
@cgabard la question est pour toi :)

**Comment by cgabard** [comment]
"Dès que possible"... Là on est en train de faire les démarches pour mettre a jour l'asso auprès de la prefecture. La première demande a été rejeter, sur des problèmes de "mise en page" des documents envoyé. J'étais en train de la refaire mais le site s'est foutu en maintenance.

Ils ont l'air de traiter ça vite, on peut espérer que ça soit fait rapidement. A partir de là on pourra lancer les démarches auprès d'OVH pour récupérer le compte avec un document officiel.

**Comment by WinXaito** [comment]
Cool :)
