### ISSUE TITLE
Les liens vers les images ne sont pas en HTTPS lorsqu'on importe une archive

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#3620]
Tout est dans le titre : 

Lorsqu'on importe un nouveau contenu ou qu'on met un contenu à jour avec archive et qu'on se sert de la fonctionnalité d'import d'image,

![Import d'archive](http://zestedesavoir.com/media/galleries/1426/981c8b17-c1b9-4b09-a75a-caf3ee8f0c50.png)

... Eh bien les liens insérés ne sont pas en HTTPS.

**Comment by ChantyTaguan** [comment]
Je prends :)

**Comment by GerardPaligot** [comment]
Merci pour le fix @ChantyTaguan ! :)
