### ISSUE TITLE
Erreur avec le captcha sur la page d'inscription

### ISSUE THREAD

**Issue by Fumble** [zestedesavoir/zds-site#3621]
Il est impossible de s'inscrire au site car le catcha sur la page d'inscription affiche ce message d'erreur:
 "ERREUR importante pour le propriétaire du site : Invalid domain for site key".

![captcha](https://cloud.githubusercontent.com/assets/634461/15452962/5fac5d1a-2001-11e6-8dc8-ddad668c40ce.png)

Problème rapporté par un membre [ici](https://zestedesavoir.com/forums/sujet/6115/inscription-impossible/).

**Comment by Emeric54** [comment]
Pourquoi le captcha est activé ? On ne devait pas l'utiliser uniquement en cas de flood ?

**Comment by Fumble** [comment]
Ca fait un problème 2-en-1 alors.
Pourquoi le catcha est affiché alors qu'il ne devrait pas et si jamais on est obligé de l'activer, il devrait fonctionner.

**Comment by GerardPaligot** [comment]
@SpaceFox

Pour ne plus faire apparaitre le captcha, il y a une option à placer dans le fichier `settings_prod.py`.
Pour le domaine, faut voir dans la configuration du module je suppose.

**Comment by Emeric54** [comment]
Oui, il faut juste que quelqu'un avec les droits vérifie la valeur de `USE_CAPTCHA` dans le `settings_prod.py`.

**Comment by SpaceFox** [comment]
C'est corrigé. Pour une raison inconnue, ça avait été activé…
