### ISSUE TITLE
Correction des frais d'adhésion à l'association

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3624]
Pour l'instant les frais d'adhésion à l'association sont inconnus (pour des raisons administratives). Cependant la [page d'adhésion à l'asso](https://zestedesavoir.com/pages/association/inscription/) indique toujours **20€** comme montant.

Il serait intéressant de préciser sur cette page que les frais d'adhésion sont pour l'instant inconnus. Il existe un paramètre pour régler cela (cf. [cette ligne du settings](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings.py#L415)).

L'idée serait donc lors du déploiement de la v18 de rajouter à la fin du fichier `settings_prod.py` le morceau de code suivant : 

``` python
ZDS_APP["site"]["association"]["fee"] = u"<em>(montant en attente de procédures administratives)</em>"
```

Si quelqu'un peut faire une PR pour rajouter cette instruction dans le `UPDATE.md`, GO !

**Comment by SpaceFox** [comment]
Pas besoin d'attendre le déploiement de la v18 pour faire la correction
normalement :)

**Comment by gustavi** [comment]
C'est corrigé :)

**Comment by firm1** [comment]
ça rendait mieux avec mes balises `<em>`  mais bon. Au moins c'est corrigé

**Comment by gustavi** [comment]
Elles ne passent pas comme il faut c'est pour cela que je les ai retirées ;)

**Comment by firm1** [comment]
Ah ok. bien joué donc.

**Comment by pierre-24** [comment]
sinon `{{machin|safe}}`. Mais soit :p

**Comment by gustavi** [comment]
Oui oui, j'ai juste pas envie de faire une PR juste pour ça ;)
