### ISSUE TITLE
[v18] Date incorrecte dans les notifications

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3628]
J'ai reçu une notification pour un topic que je suivais avant la v18.

Selon la notification elle datait d'il y'a 7h, sauf qu'en cliquant dessus, je suis tombé sur un message qui date d'il y'a 7 minutes. On peut le voir sur les screens ci-dessous.

**Notification avant le clic** : 

![capture d ecran de 2016-05-28 09-03-31](https://cloud.githubusercontent.com/assets/6066015/15625756/7d2d85ba-24b3-11e6-8537-0055b9ebc892.png)

**Notification après le clic** : 

![capture d ecran de 2016-05-28 09-03-48](https://cloud.githubusercontent.com/assets/6066015/15625757/81da4634-24b3-11e6-9cfd-22e48d7535e2.png)

Il faudrait retomber sur ce cas pour identifier facilement le bug. Si jamais j'ai une meilleur idée du truc j'édite le titre qui n'est pas très parlant.

**Comment by gustavi** [comment]
ping @GerardPaligot

**Comment by firm1** [comment]
Après visite du sujet, et après le post de quelqu'un d'autre, j'ai a nouveau la notification avec la mauvaise heure.

**La preuve en image** : 

![capture d ecran de 2016-05-28 09-09-58](https://cloud.githubusercontent.com/assets/6066015/15625767/0eccf000-24b4-11e6-8295-b2e2b0236328.png)

Pour information les **7h** correspondent à la date de la notification que j'avais **AVANT** la MEP de la v18. On dirait que les dates des notifications existantes n'ont pas été migrés par la MEP.

**Comment by GerardPaligot** [comment]
Ca risque d'être compliqué dans la mesure où il n'existait pas de date à une notification puisque pas d'objet. C'était une info calculé à chaque fois.

J'essayerais de voir ce que je peux faire mais je n'ai pas beaucoup de temps en ce moment et cela, jusqu'au 9 juin. Autrement dit, si quelqu'un d'autres veut être sur cette regression, qu'il ne s'en prive pas.

**Comment by GerardPaligot** [comment]
Juste une précision : Ca concerne que les notifications actives avant la MEP de la v18 + les nouvelles notifications sur ces sujets qui avaient des notifications actives ? Ou la portée est plus large ?

**Comment by firm1** [comment]
Si j'en crois ce que je vois. ça concerne **tous les topics que je suivais avant la MEP**.

Le problème est le même pour les notifications des contenus.

**Comment by GerardPaligot** [comment]
Et tu sais à quoi correspond ce 7h ? Et si c'est toujours 7h ?

**Comment by GerardPaligot** [comment]
Je ne comprends pas parce que à vue de nez, le code semble cohérent :
- Récupère le dernier message non lu du sujet suivi : https://github.com/zestedesavoir/zds-site/blob/dev/zds/notification/management/commands/migrate_subscriptions.py#L28
- Ou le dernier message : https://github.com/zestedesavoir/zds-site/blob/dev/zds/notification/management/commands/migrate_subscriptions.py#L30
- Affectation de la date du message à la date de la notification : https://github.com/zestedesavoir/zds-site/blob/dev/zds/notification/management/commands/migrate_subscriptions.py#L41

> Le problème est le même pour les notifications des contenus.
- Même chose pour les contenus : https://github.com/zestedesavoir/zds-site/blob/dev/zds/notification/management/commands/migrate_subscriptions.py#L113

**Comment by firm1** [comment]
Ah bah je viens d'inspecter et le public est plus restreint. le 07h correspond aux notifications que je n'ai pas lus **JUSTE AVANT** qui étaient activent avant la MEP.

Les anciens topics que je suivaient sont OK.

**Comment by ShiiFu** [comment]
J'ai eu le même problème aujourd'hui. J'ai lu toutes mes notifications ce matin et en début d'après midi je vois ceci : 
![notifications](https://cloud.githubusercontent.com/assets/10438692/15673510/7342a388-2737-11e6-823a-de34f9ccba65.png)
Et en cliquant dessus je vois bien le soucis de concordance des dates. (Si je marque non lu, la notification revenu a toujours la mauvaise date)
![notification1](https://cloud.githubusercontent.com/assets/10438692/15673523/92ec5bde-2737-11e6-82d3-b17ca1c49fa0.png)
et
![notification2](https://cloud.githubusercontent.com/assets/10438692/15673525/983ea15a-2737-11e6-803f-5dcb706512ae.png)

En cliquant sur toutes les notifications j'ai bien les bonnes dates.

Pour précision ce sont des sujets suivis depuis un moment (donc avant la MEP de ce week-end). Si vous avez besoin de plus d'informations n'hésitez pas.

**Comment by DevHugo** [comment]
/blague Je suis célèbre, je tiens à remercier tout d'abord ma mére sans qui … o/

Même souci qu’au dessus un sujet souscrit avant la MEP. Joseph poste dedans y'a 45 minutes, la date de la notification. J'ai l’impression que c'est la date de l'avant dernière notification pour le sujet.

![notification](https://cloud.githubusercontent.com/assets/6099338/15723819/6fd5b56a-2844-11e6-98f2-7ca187d72767.png)

**Comment by firm1** [comment]
> J'ai l’impression que c'est la date de l'avant dernière notification pour le sujet.

Dans mon cas ce n'est pas ça. Moi il me renvoit toujours a une notification trop vieille (difficile de l'identifier)

**Comment by cgabard** [comment]
Ce matin j'ai eu la meme chose qu'Hugo : Une notif mais la date était celle de l'avant dernier message (juste avant celui concerné par la notif)

**Comment by SpaceFox** [comment]
Je confirme que dans certains cas, la date de la notif est foireus.

2016-06-02 9:48 GMT+02:00 Christophe Gabard notifications@github.com:

**Comment by GerardPaligot** [comment]
Ok, je pense avoir compris le bug de cette issue :

La valeur `pubdate` d'une notification est enregistrée automatiquement à la sauvegarde d'une nouvelle instance du modèle ([comme en témoigne la déclaration du champ dans le modèle](https://github.com/zestedesavoir/zds-site/blob/dev/zds/notification/models.py#L290)) mais comme nous réutilisons la notification existante si elle existe, nous ne mettons pas à jour sa valeur à l'[envoi de la notification](https://github.com/zestedesavoir/zds-site/blob/dev/zds/notification/models.py#L132-L141).

Ceci est théorique parce que non testé (toujours pas le temps en ce moment) mais fait sens.

Pour corriger le bug, il faut simplement mettre à jour la valeur de `pubdate` avec la valeur de `content.pubdate` et pour tester, il suffit de générer 2 notifications pour un même contenu notifiable (pensé à renseigner une valeur manuellement à la première notification pour éviter d'avoir la même date si Django est un rapide dans l'exécution du test).

**Comment by gustavi** [comment]
v18.2 inc
