### ISSUE TITLE
Les votes négatifs pré-MEP n'ont pas été annonymisés

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3629]
Il me semblait déjà avoir relevé ce bug sur la bêta, mais ça n'a pas été corrigé on dirait. Mais les votes négatifs avant la MEP de la v18 sont tous visibles. Ils étaient censé être anonymes.

Les votes positifs ne sont pas affectés par le bug.

**La preuve en image**

![capture d ecran de 2016-05-28 09-19-44](https://cloud.githubusercontent.com/assets/6066015/15625829/a641432c-24b5-11e6-900f-d80856d62d09.png)

**Comment by GerardPaligot** [comment]
@sandhose Tu sais regarder ça rapidement ?

**Comment by gustavi** [comment]
Je check ça.

**Comment by GerardPaligot** [comment]
@gustavi Regarde du côté des identifiants à renseigner (dans le `settings`) pour bloquer l'affichage des votes à partir d'un identifiant donné.

**Comment by gustavi** [comment]
C'est bon de ce côté là. Ça ne peut pas être ça vu que ça n'affecte que les votes négatifs.

**Comment by GerardPaligot** [comment]
Le bug est donc plus complexe qu'il n'y parrait puisque tous les votes ne sont pas désanonymes.

**Comment by gustavi** [comment]
Corrigé.
