### ISSUE TITLE
Le suivi des topics par email n'a pas été migré

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3630]
Les topics que je suivais par email n'ont pas été migrés correctement. En allant sur un topic que je suivais par email avant la MEP, on me propose de le re-suivre par email, alors que je le suivais déjà par email.

Je suis obligé de me rendre sur chaque topic que je suivais par email pour refaire le suivi par email moi-même.

**Comment by GerardPaligot** [comment]
Pour cette issue, il faut :
- Utiliser l'attribut de `TopicFollowed` qui dispose toujours de toutes les données dans sa table.
- D'utiliser son attribut `email` : https://github.com/zestedesavoir/zds-site/blob/dev/zds/notification/models.py#L318
- De créer un nouveau script de migration (on va pas ré-appliquer le gros script, il est inutile maintenant).
- D'itérer sur tous les sujets suivis grâce à `TopicAnswerSubscription` (check la méthode dans son manager) et de récupérer son penchant dans `TopicFollowed`.
- Puis d'appliquer la modification.

Je le fais si j'ai du temps sur mon week-end. SInon, n'hésitez pas à corriger.
