### ISSUE TITLE
[v18] Erreur 500 sur un contenu

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3634]
Via [Sentry](https://sentry.sandhose.fr/zeste-de-savoir/backend-l7/issues/518/) : 

```
ValueError: La note doit exister ou l'utilisateur doit être l'un des auteurs.
  File "django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "zds/tutorialv2/mixins.py", line 420, in get
    follow.save()
  File "zds/tutorialv2/models/models_database.py", line 879, in save
    raise ValueError(_(u"La note doit exister ou l'utilisateur doit être l'un des auteurs."))
```

**Comment by artragis** [comment]
Je ne sais pas si c'est un bug a proprement parler : jusqu'à la v18 on disait que seul l'auteur pouvait suivre un tuto dès le début. La v18 a ajouté la capacité à suivre le tuto donc a priori, on peut le suivre dès le début.

Ceci dit on peut facilement le changer ça.

**Comment by artragis** [comment]
duplicata de #3640

**Comment by gustavi** [comment]
Pas sûr, on a pas la même exception

**Comment by artragis** [comment]
tout comme sur #3640 le bug est corrigé : bien que l'erreur ne soit pas la même l'idée vient d'une ancienne condition qui semble avoir été enlevée. DOnc là je dirais que c'est corrigé @gustavi @vhf

**Comment by artragis** [comment]
@gustavi @vhf
