### ISSUE TITLE
Nombre de messages postés par Clem incoherent

### ISSUE THREAD

**Issue by Nodraak** [zestedesavoir/zds-site#3637]
Sur [cette page](https://zestedesavoir.com/membres/voir/Clem/), on voit que Clem a posté 3 messages. Quand on clique [sur le lien](https://zestedesavoir.com/forums/messages/1/), il n'y en a plus.

Piste à confirmer : pourquoi [cette ligne](https://github.com/zestedesavoir/zds-site/blob/c73fa0704ed78f2676697c17c77ce24572f0ab03/zds/forum/managers.py#L115) n'apparait pas dans la condition au dessus ? J'imagine que Clem a la permission `forum.change_post` et la requete n'est donc pas filtrée comme il faut.

**Comment by GerardPaligot** [comment]
En fait, les sujets concernés sont dans le forum Staff. Forum dont tu n'as pas les accès.

**Comment by Nodraak** [comment]
Arf, je me doutais qu'on me cachais des choses comme ça ^^

J'imagine que le temps de dev et l'impact sur les perf rend la correction trop complexe pour être rentable.

**Comment by GerardPaligot** [comment]
C'est pas tellement ça. C'est plutôt : Est-ce que nous devons fausser le nombre de messages d'un membre sur cette page pour enlever les messags non visibles par le visiteur ou est-ce qu'il faut coller à la réaliter mais ne pas afficher les messages non visibles parce que le visiteur n'a pas les droits.

Personnellement, je préfère la seconde solution.

**Comment by Nodraak** [comment]
Hum. Mais dans ce cas, il vaut mieux peu être mettre un message "X messages non affichés".

Autant une différence de trois messages sur 100 ou 1000 messages ne se remarque pas, autant pour Clem ça surprend.

**Comment by GerardPaligot** [comment]
C'est tout à fait envisageable, même plus pertinent. :)
