### ISSUE TITLE
Améliorer la selecition d'une demande d'aide lors de la création/édition d'un contenu

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3638]
Voir le [forulm](https://zestedesavoir.com/forums/sujet/6169/deselection-recherche-aide-lors-de-creation-contenu/?page=1#p112264) pour les détails.

C'est assez simple à faire, il suffit de modifier le type de champs dans le formulaire via Django pour mettre des boites (avec sélection multiple) comme pour les contenus.

**Comment by AmarOk1412** [comment]
Je prends aussi cette issue si possible, je vois les modifications à faire (pour `helps` -> `widget=forms.CheckboxSelectMultiple()` et rajouter `.checkbox-new-content` au label

**Comment by pierre-24** [comment]
Ok, après trois tentatives :)
