### ISSUE TITLE
Les notifications ne sont pas supprimées à la suppression d'un MP

### ISSUE THREAD

**Issue by Deuchnord** [zestedesavoir/zds-site#3639]
Hello,

Suite à la réception de nombreux MP automatiques pour la mise à jour de mes articles, je les ai supprimés sans les ouvrir étant donné que j'en connaissais déjà la teneur.
Problème : les notifications sont restées, et impossible de les supprimer. Un clic dessus mène à une 404, et la notification ne disparaît pas :-/

**Comment by GerardPaligot** [comment]
Ah, bien vu ! Je n'avais pas prévu ce cas de figure.

Si quelqu'un corrige le bug avant moi : il suffit d'envoyer le signal qui marque un MP comme lu quand on quitte un MP.

**Comment by Deuchnord** [comment]
Du coup, il faudra peut-être voir pour supprimer les notifications rémanentes, je ne sais pas trop comment vous pourrez faire ça :-/

**Comment by GerardPaligot** [comment]
Tout à fait, il faut penser à développer un script de migration pour détecter toutes les notifications plus nécessaires.

**Comment by GerardPaligot** [comment]
J'ai un souci avec cette issue.

Après quelques tests en local, je ne suis pas parvenu à reproduire le bug. J'ai créé un message privé avec des participants et quand j'ai supprimé les MP (sans les lires) du côté des participants, la notification a disparu. J'ai fais la même chose en supprimant plusieurs messages privés d'un coup.

J'ai aussi vérifié si j'avais pensé à ce cas. Contrairement à ce que j'ai dis plus haut, j'avais bien prévu le coup. Quand la liste des participants est éditée, j'ai un `receiver` qui réagit et qui met à jour les notifications en conséquence.

Par contre, en écrivant ce message je me suis posé la question : "Mais si je suis seul dans le MP et que je supprime le MP sans lire la notification, que se passe-t-il sachant qu'il n'y a plus de participant ?". Dans ce cas là, ma notification persiste.

Donc, @Deuchnord est-ce que tu me confirmes que tu étais seul dans les MPs ?

**Comment by Deuchnord** [comment]
Je confirme, c'était des messages automatiques de Clem, à chaque fois j'étais seul dans les conversations
