### ISSUE TITLE
[v18] Impossible de suivre certains contenus

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3640]
Via Sentry [ici](https://sentry.sandhose.fr/zeste-de-savoir/backend-l7/issues/519/) et [là](https://sentry.sandhose.fr/zeste-de-savoir/backend-l7/issues/520/) : 

```
MustRedirect: /tutoriels/681/a-la-decouverte-des-algorithmes-de-graphe/
  File "django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "zds/member/decorator.py", line 27, in _can_write_and_read_now
    return func(request, *args, **kwargs)
  File "django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "zds/member/decorator.py", line 66, in dispatch
    return super(LoggedWithReadWriteHability, self).dispatch(*args, **kwargs)
  File "django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "zds/member/decorator.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)
  File "django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "zds/tutorialv2/views/views_published.py", line 660, in post
    self.public_content_object = self.get_public_object()
  File "zds/tutorialv2/mixins.py", line 362, in get_public_object
    raise MustRedirect(self.get_redirect_url(obj))
```

Le contenu en question (bug uniquement sur ce contenu dans les logs, à voir si ça en touche d'autres) : https://zestedesavoir.com/tutoriels/681/a-la-decouverte-des-algorithmes-de-graphe/

**Comment by artragis** [comment]
la cause est simple : historiquement on ne permet pas de suivre un contenu neuf. Seul les auteurs le peuvent.
En fait il suffit de supprimer le bout de code qui empêche les non auteurs de suivre un tuto. Par contre, il est fort probable qu'il y ait un test de ce comportement, donc faut aussi le virer.

**Comment by vhf** [comment]
Ce bug est très gênant.

Il est simple à reproduire, est présent _potentiellement_ sur tous les contenus (certains n'en souffrent pas mais je n'ai pas cherché à savoir lesquels bug et lesquels pas), et @artragis semble dire qu'il est simple à régler.

Cliquer ici : 

<img width="637" alt="screen shot 2016-07-24 at 15 09 41" src="https://cloud.githubusercontent.com/assets/2022803/17083961/b0d2d666-51b0-11e6-93f2-7e85dff1fe23.png">

produit une erreur 500, avec la stack trace mentionnée par @gustavi .

**Comment by artragis** [comment]
Simple à régler oui.

Simple à évaluer les effets de bords. Je n'en mettrai pas ma main à 
couper. Si on a fait ce choix, c'est peut être parce qu'on avait une 
bonne raison.

Maintenant, le mieux ça serait simplement d'enlever la condition et le 
test afférant (si test il y a). On regarde si travis passe puis on le 
met sur la béta.

**Comment by GerardPaligot** [comment]
@artragis Tu aurais un peu de temps pour nous pointer le ou les partie(s) du code concernée(s) ? Parce que je ne vois pas bien le rapport entre la souscription à un contenu et l'erreur donnée par @gustavi

**Comment by gustavi** [comment]
Après avoir passé pas mal de temps à debug ça je pense que ça sera corrigé en v20, à vérifier quand on on l'aura mise sur le beta.

**Comment by GerardPaligot** [comment]
@gustavi Toujours d'actualité sur la v20 en bêta. (:

**Comment by gustavi** [comment]
Je ne comprends pas d'où ça vient alors. Je vais voir plus en détail là.

**Comment by gustavi** [comment]
Alors j'ai réfléchis un peu au problème et j'ai une solution qui ne fixe pas spécifiquement ce problème mais qui par modification d'un comportement va le corriger. Je m'explique.

Aujourd'hui tous les `PublishedContent` au un `must_redirect` qui permet de rediriger `/contenu/<pk>/<ancien_slug>/` vers `/contenu/<pk>/<slug>/` si jamais le slug a changé entre deux versions.

Je pense qu'on peut se passer de toute cette partie redirection en dur dans le code et simplement rediriger `/contenu/<pk>/*/` vers `/contenu/<pk>/<slug>/`. Ça se fait super simplement dans le vue d'un contenu : on récupère le contenu avec le `pk`, on récupère le `slug` passé dans l'URL et s'il est différent du `slug` du contenu on fait une 302 vers la bonne URL. Du coup on enlève une partie chiante du code et on le simplifie sans casser me SEO.

Qu'en pensez-vous ?

**Comment by artragis** [comment]
ayant réussi à suivre un contenu sur la v20 je dirais que c'est résolu @vhf @gustavi
