### ISSUE TITLE
Ajouter un paramètre sur le chemin du template TeX pour Pandoc

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3646]
C'est ici https://github.com/zestedesavoir/zds-site/blob/97691b626292fcf45b45f0e08def0fa725ea0df2/zds/settings.py#L347

Il faut ajouter un paraètre facilement modifiable sans avoir besoin de réécrire la commande en entier.

**Comment by AmarOk1412** [comment]
@artragis, si tu peux fermer aussi ça.
