### ISSUE TITLE
Markdown/images : trop de crochets tuent les crochets

### ISSUE THREAD

**Issue by Deuchnord** [zestedesavoir/zds-site#3648]
En voulant résumer le contenu d'une capture d'écran dans la description d'une image, j'ai tronqué une partie du texte et signalé le troncage avec le _[…]_ usuel aux endroits adéquats.

Or, il semble que la présence multiple de crochets dans la description d'une image empêche Markdown de comprendre la présence de ladite image.

Petite démonstration pour que vous puissiez mieux visualiser.

``` markdown
![Clem tenta de s'agripper à quelque chose, mais elle [...] voltigea à l'autre bout de la petite pièce.](https://transfer.sh/bXOOf/screenshot-at-2016-06-06-10-38-08.png)

![Clem tenta de s'agripper à quelque chose, mais elle [...] voltigea à l'autre bout de la [...] pièce.](https://transfer.sh/bXOOf/screenshot-at-2016-06-06-10-38-08.png)
```

Résultat :
![screenshot at 2016-06-06 10 41 30](https://cloud.githubusercontent.com/assets/7600265/15816521/70687caa-2bd3-11e6-8826-300c5e7fdf84.png)

Il semblerait que Markdown perde pied à partir de deux paire de crochets.

**Comment by GerardPaligot** [comment]
Est-ce que tu pourrais reporter le bug directement sur le dépôt de notre parseur ? https://github.com/zestedesavoir/Python-ZMarkdown

Je ferme ici. :)

**Comment by Deuchnord** [comment]
Oups, désolé, j'avais pas vu qu'il y avait un dépôt spécifique au parseur ^^'
