### ISSUE TITLE
Impossible de signaler un message quand le message est masqué

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#3649]
Bonjour,

Il est impossible de signaler un message quand celui-ci est masqué. [Exemple](https://zestedesavoir.com/forums/sujet/6251/-/).

**Comment by Vayel** [comment]
Quel est l'intérêt de pouvoir le faire ?

**Comment by GerardPaligot** [comment]
Same que @Vayel

**Comment by cgabard** [comment]
Le cas arrive comme ici : L'auteur a écrit un message puis l'a totalement viré par édit et la masqué : il est impossible de signaler le message aux modérateur pour leur dire de le mettre a la corbeille

**Comment by gustavi** [comment]
Pas faux mais est-ce vraiment utile ?

**Comment by cgabard** [comment]
Bin on a aucun moyen de signalé le message... Ça arrive pas souvent et avec le nombre de modérateur qui traine c'est pas critique. Mais bon si tu veux un site parfait, ce serait logique.

Peut être que c'est surtout la possibilité de masquer le premier message d'un sujet qui n'est pas logique.

**Comment by vhf** [comment]
@cgabard On peut pas trop empêcher de masquer le premier message d'un sujet. Si on fait ça, les gens éditeront simplement leur premier message pour en enlever le contenu.

Je pense que c'est effectivement un truc à implémenter, l'alerte sur les messages masqués.

**Comment by vhf** [comment]
Est-ce qu'il ne suffit pas d'enlever cette condition : https://github.com/zestedesavoir/zds-site/blob/32ed04f815e25492728c3582c9002193c1e35958/templates/misc/message.part.html#L87 ?

**Comment by GerardPaligot** [comment]
Merci @vhf
