### ISSUE TITLE
Éditer le 1er message d'un topic devrait renvoyer sur la page "Édition du sujet".

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#3653]
Cela arrive de se tromper si on fait une faute ou autre...

Cf. [mon petit fail](https://zestedesavoir.com/forums/sujet/6271/hebergement-du-site/)

**Comment by firm1** [comment]
Hello, c'est bien possible d'éditer ton topic, c'est juste que la façon de faire n'est pas ergonomique.

Tu as un bouton dédié dans la sidebar (cf. la capture)

![edit](https://cloud.githubusercontent.com/assets/6066015/15935931/6cdbd490-2e69-11e6-90b6-ef3f4e6213f1.PNG)

**Comment by lypwig** [comment]
Ah oui,

En fait le problème niveau ergonomie, c'est que le bouton _Éditer le sujet_ sur le panneau de gauche n'a pas le même comportement que le bouton _Éditer_ au dessus du message :
![editer_topic](https://cloud.githubusercontent.com/assets/1665542/15937984/64510d42-2e71-11e6-827e-3da77b54882d.png)

Je comprend que ce bouton permet d'éditer le message, qu'il soit le début d'un topic ou pas. Mais lorsque le message est le premier du topic, je trouve que ce serait mieux que ce bouton redirige vers "Éditer le topic".

Qu'en pensez-vous ?
