### ISSUE TITLE
Texte incohérent au niveau des notifications

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3658]
> Salut,
> 
> Je n'ai plus de souvenir exact du texte avant les v18 et son nouveau système de notification mais actuellement, on a ça, que ce soit sur mobile ou bureau:
> 
> ![MP](https://zestedesavoir.com/media/galleries/449/e9d312be-8171-4b97-add9-80e8156a1c75.png)     ![Notif](https://zestedesavoir.com/media/galleries/449/133720f7-e1ff-4871-9d55-1026c551e266.png)
> 
> Deux problèmes:
> - Pourquoi a-t-on le texte "Aucune notification" dans un cas et "Aucune nouvelle notification dans l'autre"
> - Dans le cas des MP, j'avais le souvenirs d'un texte du genre "Toutes les conversations" ou un tuc du genre au lieu de "Toutes les notifications"
> 
> Il faudrait aussi vérifier le cas de la liste des alertes quand elle est vide. Par contre, il y a bien marqué "Toutes les alertes" pour aller au listing complet.
> Source:[Fumble](https://zestedesavoir.com/forums/sujet/6298/texte-incoherent-au-niveau-des-notifications/?page=1#p113756)

**Comment by malnuxstarck** [comment]
je m'en charge

**Comment by Situphen** [comment]
Merci @malnuxstarck !
