### ISSUE TITLE
Les tags les plus utilisés des forums sont triés par pk au lieu d'être triés par compte

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3665]
Les tags les plus utilisés sont mal triés. On s'attend intuitivement à un ordre qui correspond aux nombres de sujets liés à ce tag. Mais ce n'est pas le cas.

Après analyse, on voit qu'ils sont triés par pk des tags et non par nombre de sujets derrière ces tags. L'image ci-dessous (accompagné des chiffres) le montre bien :

![taggs](https://cloud.githubusercontent.com/assets/6066015/16083512/85583e90-3315-11e6-88f7-0bdb68a6cc81.PNG)

**Comment by gustavi** [comment]
Deux possibilités pour corriger ça : 
- Modifier le templatetag `topbar.py` et la requête monstreuse associée
- Utiliser https://docs.djangoproject.com/fr/1.9/ref/templates/builtins/#dictsort dans le template

**Comment by vhf** [comment]
`dictsort` n'est pas une option ici, parce qu'on a une liste d'objets `Tag` sans leur compte associé.

J'ai modifié le templatetag et refactoré le truc, c'était pas top.

La source du problème était un peu planquée. Le fonctionnement était : 
1. Récupérer une liste de pk des tags, ordonnés par popularité
2. Récupérer les tags dont la pk est dans la liste

Donc la requête `2.` fait genre `SELECT * FROM tags WHERE id IN (9, 5, 7, 2)`. Le résultat ne respecte évidemment pas l'ordre `9, 5, 7, 2`.

**Comment by firm1** [comment]
Je réouvre ici, car ce n'est toujours pas correct si je regarde la bêta actuellement.

On a le tag [java](https://beta.zestedesavoir.com/forums/sujets/tag/2/java/) avant le tag [arduino](https://beta.zestedesavoir.com/forums/sujets/tag/94/arduino/) alors que le le tags arduino à plus de sujets que celui de java.

**Comment by vhf** [comment]
#3816

**Comment by firm1** [comment]
Désolé, mais je ré-ouvre encore ici.

> si je regarde la bêta actuellement.
> 
> On a le tag [java](https://beta.zestedesavoir.com/forums/sujets/tag/2/java/) avant le tag [arduino](https://beta.zestedesavoir.com/forums/sujets/tag/94/arduino/) alors que le le tags arduino à plus de sujets que celui de java.

**Comment by vhf** [comment]
Non, l'ordre est correct.

Voici les 10 top tags avec leur fréquence : 

```
{'tags__title': u'bug', 'nb_tags': 448},
{'tags__title': u'python', 'nb_tags': 444},
{'tags__title': u'c++', 'nb_tags': 361},
{'tags__title': u'beta', 'nb_tags': 356},
{'tags__title': u'tutoriel', 'nb_tags': 346},
{'tags__title': u'suggestion', 'nb_tags': 338},
{'tags__title': u'php', 'nb_tags': 336},
{'tags__title': u'java', 'nb_tags': 204},
{'tags__title': u'arduino', 'nb_tags': 186},
{'tags__title': u'chimie', 'nb_tags': 160},
```

**Comment by GerardPaligot** [comment]
Je soupçonne que les contenus viennent mettre un peu la merde là dedans.

**Comment by firm1** [comment]
@vhf La c'est parce que tu comptabilise les tags des contenus avec. Dans l'onglet forum, on s'attend à avoir les tags les plus utilisés sur le forum, sinon ça n'a plus vraiment de sens.

**Comment by vhf** [comment]
Non @firm1. C'est le résultat de ceci, qui ne prend en compte que les topics:

``` py
from collections import defaultdict
from django.conf import settings

from zds.forum.models import Forum, Topic
from zds.utils.models import Tag
from django.db.models import Count
max_tags = 10
forums_pub = Forum.objects.filter(group__isnull=True).select_related('category').distinct().all()
forums = list(forums_pub)

cats = defaultdict(list)
forums_pk = []
for forum in forums:
    forums_pk.append(forum.pk)
    cats[forum.category.position].append(forum)

topbar_cats = []
sorted_cats = sorted(cats)
for cat in sorted_cats:
    forums = cats[cat]
    title = forums[0].category.title
    topbar_cats.append((title, forums))

tags_by_popularity = list(
    Topic.objects
    .values('tags__title', 'tags__pk')
    .distinct()
    .filter(tags__isnull=False, forum__in=forums_pk)
    .annotate(nb_tags=Count('tags'))
    .order_by('-nb_tags')
    [:max_tags])
print tags_by_popularity
```

**Comment by firm1** [comment]
Il doit y avoir un bug quelque part alors car comment tu explique qu'on ait plus de page en sélectionnant le tag arduino, qu'en sélectionnant le tag java ?

**Comment by GerardPaligot** [comment]
Pour information, voici [la requête qui liste tous les sujets d'un tag donné](https://github.com/zestedesavoir/zds-site/blob/release-v20/zds/forum/managers.py#L87-L92). On peut y voir un `exclude` mais je ne sais pas dans quelle mesure il peut impacter dans notre cas ci-présent.

**Comment by firm1** [comment]
Je ne pense pas que le exclude soit impactant ici car il concerne les forums privés ou non. Or je fais mes tests en tant qu'invité et le résultat est toujours pareil. Plus de page arduino que de page java

**Comment by vhf** [comment]
Oui, le exclude ne peut pas avoir d'impact.

Dans les top tags, on prend les tags des topics qui sont dans les forums _filter_ `group__isnull=True`. Dans la liste des topics d'un tag, on prend les topics qui sont dans les forums _exclude_ `group__isnull=False`. Ça revient donc au même.

**Comment by pierre-24** [comment]
Le `.annotate(nb_tags=Count('tags'))` peut pas fonctionner. Comme je le comprend, la requête fait en sorte que si un topic possède plusieurs tags, eh bien c'est ce nombre qui est ajouté à `nb_tags`. Du coup, si il n'y a qu'un seul topic et que ce topic porte les tags "machin, truc, et bidule", le code renverra 3 pour les 3. Et ça explique comment le tag chimie se retrouve dans les tags les plus utilisés pour le moment.

Le code correct, c'est, je crois,

``` python
tags_by_popularity = list(
        Tag.objects
        .annotate(count_topic=Count('topic__pk'))
        .order_by('-count_topic')
        [:max_tags + len(settings.ZDS_APP['forum']['top_tag_exclu'])])
```

Et ça va tout de suite mieux :)

PR _incoming_

**Comment by vhf** [comment]
Après moult péripéties… 👍
