### ISSUE TITLE
Problème de rendu des smileys dans une citation

### ISSUE THREAD

**Issue by Fumble** [zestedesavoir/zds-site#3668]
Tout est dans le titre et la capture d'écran qui suit.

![citation](https://cloud.githubusercontent.com/assets/634461/16163648/c032a818-34da-11e6-8928-0a207f001b85.png)

Testé sous Windows 10 64 bits avec Firefox 47 et IE 11.

Pour voir le problème en direct, ça se passe sur [ce topic](https://zestedesavoir.com/forums/sujet/6327/crypter-code-source/).

**Comment by gustavi** [comment]
@cgabard une idée ?

**Comment by cgabard** [comment]
Hum... Quand je regarde la source de mon message je ne vois pas de smiley dessus. Je soupçonne que j'ai fais un copier/coller du html dans l'éditeur et qu'il aurait remplacé l'image par un caractère unicode (sous chrome/linux je vois rien, sous FF je vois bien un caractère étrange).

Du coup je sais pas trop qui doit corriger ça.

**Comment by vhf** [comment]
Citer un message contenant des smileys fonctionne. Copier-coller des images, par contre, c'est pas top. :)
