### ISSUE TITLE
[Membre] Limiter la longueur de la signature

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#367]
La signature ne semble pas être limitée en longueur, il le faudrait. Dans l'absolu, ça doit rentrer sur une ligne.

Il y a la biographie pour s'exprimer longuement.

**Comment by SpaceFox** [comment]
Tant que je suis là-dedans, je prends aussi cette issue.

**Comment by Alex-D** [comment]
Fixé et corrigé
