### ISSUE TITLE
Sur le profil d'un banni, le bouton pour envoyer un MP est toujours présent

### ISSUE THREAD

**Issue by Emeric54** [zestedesavoir/zds-site#3672]
Sur le profil d'un banni, le bouton pour envoyer un MP est toujours présent, alors qu'il est par la suite impossible d'envoyer le message. Exemple [ici](https://zestedesavoir.com/membres/voir/phdphdphd/).

Il faudrait donc ne plus afficher cette option si le membre est banni.

**Comment by DevHugo** [comment]
Tu peux ajouter facile aussi ! ^^

**Comment by GerardPaligot** [comment]
Merci à @Karnaj pour la fonctionnalité !
