### ISSUE TITLE
Masquer la biographie des membres bannis définitivement

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3673]
Pour la simple et bonne raison que c'est presque toutjours fait (publicité, etc). Aucune raison de laisser ça et ça va faire moins de travail à la modération.

La laisser avec un message (« Cette biographie est masquée pour le publique car le membre est banni » par exemple) pour le staff.

**Comment by Situphen** [comment]
Seulement ceux bannis définitivement ou aussi ceux temporairement ?

**Comment by gustavi** [comment]
Définitivement pour moi.

**Comment by Karnaj** [comment]
@gustavi t’es toujours dessus ou je peux prendre ?

**Comment by GerardPaligot** [comment]
@Karnaj Tu peux prendre. :)

**Comment by Situphen** [comment]
Merci @Karnaj !
