### ISSUE TITLE
Modifier le comportement de la barre de recherche

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#3678]
Un exemple (il y en aurait bien d'autres) :

Je veux apprendre Python. Je tape _Python_ dans la barre de recherche : le tutoriel _Les bases de Python_ (qui est la réponse la plus évidente à ma recherche) apparaît en 9ème position, en bas de page (nécessité de scroller).

La plupart des propositions sont des messages dans les forums, qui n'aident en rien. Par exemple, ce message qui arrive en première position, ne m'aide pas à apprendre le Python :

> La version de python 1.23 ?

Les 8 premiers messages sont du même style.

Il me semble important de revoir l’algorithme de ranking de cette barre de recherche, **d'autant plus que c'est ce qui est mise ne avant sur la page d'accueil du site**.

Dans le mesure du possible on ne devrait pas avoir a utiliser le filtre dans la sidebar.

Cf. [ce topic](https://zestedesavoir.com/forums/sujet/6374/modifier-le-comportement-de-la-barre-de-recherche/)

**Comment by GerardPaligot** [comment]
Tout dépend de l'utilisateur. Personnellement, je recherche plus souvent un message dans les forums qu'un contenu.

**Comment by firm1** [comment]
Étant donné que sur la page d'accueil on affiche dans la liste des
suggestions, des mots clés relatifs aux contenu, j'aurai tendance a dire
moi aussi qu'il vaut mieux rediriger que vers des contenus.

Le mar. 21 juin 2016 12:49, Gérard Paligot notifications@github.com a
écrit :

**Comment by DevHugo** [comment]
Dans le même genre: https://github.com/zestedesavoir/zds-site/pull/2770.

Je pense perso qu'il faut donner la priorité au contenu, si le mot clé est dans le titre.

**Comment by GerardPaligot** [comment]
> Étant donné que sur la page d'accueil on affiche dans la liste des
> suggestions, des mots clés relatifs aux contenu, j'aurai tendance a dire
> moi aussi qu'il vaut mieux rediriger que vers des contenus.

Ce qui est renseigné en suggestion n'est pas du tout lié aux contenus. Ce sont des thématiques, elles ne sont liées à rien. D'ailleurs, c'est un fichier texte dans lequel on place des mots randoms.

**Comment by firm1** [comment]
Elle ne sont lié a rien au niveau des tables certes, mais quand
l'utilisateur voit "Html", "Php", "Java", "Android", .... il s'attend a
tomber sur les contenus qui parlent de ces thématiques et non pas sur les
posts dans le forum qui parlent de ces thématique.

Je ne sais pas si tu vois la nuance.

Le mar. 21 juin 2016 13:17, Gérard Paligot notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
Bien entendu mais je n'en ferais pas une généralité. Par exemple, pour mon usage strictement personnel et parce que c'est pas simple de récupérer la liste des sujets d'un tag, je renseigne "Android", "Java" et d'autres thématiques dans la barre de recherche pour récupérer les sujets associés.

C'est extrèmement rare que je recherche un contenu.

**Comment by firm1** [comment]
J'ai l'impression que ton cas est plutôt spécifique. Car tu peux simplement
cocher les case "sujet" et "post" dans la sidebar quand tu veux étendre ta
recherche.

Mais ça serait intéressant de créer un topic sur le site pour avoir plus
d'avis.

Le mar. 21 juin 2016 13:33, Gérard Paligot notifications@github.com a
écrit :

**Comment by pierre-24** [comment]
Bon, c'est bon. Pas parfait parce que ça crache plus les mini-tuto/article avant les moyen/Big, mais les contenus sortent en premier (en fonction du settings.py, *of course*)
