### ISSUE TITLE
Problème sur l'encart « STAFF »

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3679]
Sur mes MP : http://i.imgur.com/rLomYk2.png

Sur le forum : http://i.imgur.com/FcZWCQG.png

EDIT :  il faut en fait refacto tout ça.

**Comment by Situphen** [comment]
Est-ce que ça a une utilité dans la messagerie privée ? Je sais pas si c'est un bug, je dirais plutôt une évolution.

**Comment by gustavi** [comment]
Le problème c'est que je suis STAFF à un endroit mais pas à l'autre.

**Comment by firm1** [comment]
> Le problème c'est que je suis STAFF à un endroit mais pas à l'autre.

Attention tout de même. Tu es dans un cas particulier, ton badge staff sur les forums est du au fait que tu soit superuser et pas réellement dans le groupe staff.

Il faudrait vérifier avec un vrai "staff" aussi

**Comment by gustavi** [comment]
Je suis pas superuser, impossible de me connecter à l'admin.

**Comment by Fumble** [comment]
En tant que simple Staff, j'ai bien le badge de partout.

**Comment by WinXaito** [comment]
Reporter ici sur le forum. Selon le membre. Sur le profil de Gustavi il le voit aléatoirement avec et sans badge. 

https://zestedesavoir.com/forums/sujet/6385/apparition-de-lembleme-staff-sur-un-compte/

Désoler de ne pas mettre les images, un peu galère sur mobile.

**Comment by cgabard** [comment]
> Je suis pas superuser, impossible de me connecter à l'admin.

L'accès à l'admin de Django demande une action supplémentaire au statut de superuser : il faut cocher la case "Statut équipe" dans l'admin Django.

Je viens de le faire, tu devrais avoir accès à l'admin maintenant.

Le plus simple pour corriger ce bug est probablement de simplement te mettre dans le groupe "Staff" officiellement

**Comment by WinXaito** [comment]
> Le plus simple pour corriger ce bug est probablement de simplement te mettre dans le groupe "Staff" officiellement

Ouais, fin.. Faudrait mettre des guillemets sur le corrigé :p

**Comment by DevHugo** [comment]
En même temps, on a confiance en lui, il est pas dtc pas pour rien. Il a les accès à la prod donc bon être staff, ça change pas grand chose.

**Comment by gustavi** [comment]
En fait je ne tiens pas à être dans le groupe « STAFF » car ils sont chargés de la modération et de la validation ce qui n'est pas mon cas.

**Comment by gllmc** [comment]
Est-ce que le problème ne serait pas le même que #2985 ? Le badge de gustavi s'affiche maintenant sans problème (le problème n'a duré que quelques temps), ce qui est le même comportement que chez les nouveaux staffeux.

**Comment by pierre-24** [comment]
Voilà qui fonctionne, merci @GCodeur :)
