### ISSUE TITLE
Les auteurs sont mal transmis lors de la desinscription

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#3680]
Apparemment lorsqu'un auteur se désinscrit, les règles de transmission du contenu sont mal respectées.

Par exemple, ce tuto suite au départ de Mewtow : https://zestedesavoir.com/tutoriels/526/les-sols/

**Comment by gustavi** [comment]
Effectivement ! Solution : si contenu publié et auteur unique qui se désinscrit alors attribuer Auteur externe.

**Comment by Eskimon** [comment]
C'est plutôt une régression, ca "marchait" normalement ca (on avait pas des TU d'ailleurs à ce niveau là ?) (marchait entre guillemets car pas sur qu'on est trop testé en vrai situation vu le faible taux d'auteurs qui partent)

**Comment by firm1** [comment]
Je confirme que c'est une régression.

**Comment by SpaceFox** [comment]
Je confirme que ça a marché au moins avec les articles de Geo.

**Comment by pierre-24** [comment]
Le test unitaire méga-chiant à maintenir pour le vérifier est [là](https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/tests/tests_views.py#L425-L464), du coup je pige pas trop ce qui c'est passé.

**Comment by StaloneLab** [comment]
Je ne passe pas souvent par ici, mais je souhaiterais signaler qu'il serait cool de pouvoir choisir, lors de la désinscription, si l'on souhaite, ou non, laisser son pseudo comme auteur.

**Comment by pierre-24** [comment]
... Quelle serait la différence avec le fait de ne pas se désinscrire mais de plus venir, dans ce cas ?

**Comment by SpaceFox** [comment]
En fait on peut déjà : comme [expliqué dans le message de desinscription](https://github.com/zestedesavoir/zds-site/blob/dev/templates/member/settings/unregister.html#L45-L57), il suffit de demander au staff de rajouter le nom de l'auteur dans les tutos avant de se désinscrire.

**Comment by StaloneLab** [comment]
Au temps pour moi, dans ce cas, je ne savait pas que c'était possible.

**Comment by DevHugo** [comment]
Si on télécharge les pdf, on a encore le nom.
