### ISSUE TITLE
Popup ajout auteur qui bug sur mobile

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#3682]
Hello !

J'ai l'impression que la popup pour ajouter un auteur à un tuto bug sur mobile. Avec mon smartphone (One plus One , Android 6, chrome) elle ne s'affiche pas :(

**Comment by AmarOk1412** [comment]
Ça me semble réglé. Testé en version dev & locale sur Firefox OS, Android (Firefox, Nightly et Chrome) j'ai accès à la popup d'ajout.
