### ISSUE TITLE
Il ne devrait pas être possible de créer 2 tutoriels portant le même nom

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#3684]
Il est actuellement possible de créer 2 tutoriels portant le même nom, ce qui est déroutant car on ne sait pas réellement le quel on modifie. De plus, cela peut poser des problèmes pour les applications tierces qui téléchargent les tutos via l'API.

![](http://i.imgur.com/uwmddSL.png)

cc [le ticket associé sur Zest Writer](https://github.com/firm1/zest-writer/issues/131)

**Comment by pierre-24** [comment]
Moui. Le nom est le même, mais le _slug_ est différent, donc les contenus sont effectivement unique, donc du coté du stockage, on est bon (pareil pour les applications tierces). Un moyen de faire la différence, c'est bien entendu la date de création, quand elle est disponible (certes pas sur ZW, à priori).

Mais le débat est plus philosophique que ça, pour moi: quel est l'intérêt de créer deux contenus ayant le même nom ? À part une erreur, qu'est ce qui justifierai de faire coexister deux contenus du même nom, et du coup de pas s'y retrouver ?

**Comment by lypwig** [comment]
> Mais le débat est plus philosophique que ça, pour moi: quel est l'intérêt de créer deux contenus ayant le même nom ? 

Aucun, AMHA.

>  qu'est ce qui justifierai de faire coexister deux contenus du même nom, et du coup de pas s'y retrouver ?

Rien, AMHA

> À part une erreur

D'où ce ticket : éviter cette erreur.

**Comment by pierre-24** [comment]
> D'où ce ticket : éviter cette erreur.

Ben oui ... Mais je vois pas ce qui pousserai un utilisateur à le faire dans la "vraie" vie (au delà des tests, donc). Je suis pas contre l'idée (qui prend 3 lignes de codes+tests), je dis juste que ça fait un peu ... Inutile (surtout que quand il s'agit de développer, dieu sait combien de contenu "test" j'ai créé ...).

**Comment by WinXaito** [comment]
Et bien si le ticket est ouvert, cest que cela c'est produit. En l'ocurence sur Zest Writer

**Comment by lypwig** [comment]
[Oui](https://github.com/firm1/zest-writer/issues/131)

**Comment by pierre-24** [comment]
> Et bien si le ticket est ouvert, cest que cela c'est produit. En l'ocurence sur Zest Writer

Encore une fois, je suis d'accord ... Mais c'était dans le cadre de tests ^^

**Comment by lypwig** [comment]
[Pas ici](https://github.com/firm1/zest-writer/issues/159), par exemple.

Ci-dessus c'est un bug à corriger, mais il peut y en avoir d'autres du même style et le fait d’empêcher la création de contenus portant le même nom pourrait éviter des propagations d'erreurs. En l’occurrence, dans le ticket ci-dessus, l'API pourrait renvoyer un truc du style _erreur : un contenu portant le même nom existe déjà_.

**Comment by pierre-24** [comment]
> Pas ici, par exemple.

Oui, mais comme tu dis, c'est un bug. Cela ne peut (!) pas arriver sur ZdS (sauf si la BDD est corrompue). Et je vais même aller plus loin: autant sur ta machine, tu fais ta popote comme tu veux. Autant sur ZdS, ce qu'implique ce que tu veux, c'est que si deux auteurs différents créent un contenu nommé "le langage C", eh bien le deuxième va s'entendre dire qu'il n'as pas le droit parce que le contenu existe déjà. Sauf s'il l'appelle "Le langage C" (et avoue qu'il faut se concentrer un peu pour voir la différence quand tu ne sais pas ce que tu cherche).

Heureusement, on a "bien" (tout est relatif ^^) codé ça et on impose que le _slug_ (=le nom du dossier, en gros) soit unique. Chose que Firm1 ne peut d'ailleurs pas faire avec ZW, parce qu'il ne sais pas à priori quels sont les contenus déjà existant, d'ou le bug. Il doit "attendre" que le contenu soit uploadé sur ZdS une fois pour savoir quel est son _slug_. Pareil si le contenu change de nom.

**Comment by GerardPaligot** [comment]
Je viens juste signaler que moi j'ai 2 tutoriels avec le même nom et ça m'est utile. J'aimerais donc que ça reste possible.

**Comment by gustavi** [comment]
Exact, c'est pas un bug. Imaginons que l'utilisateur A crée un tutoriel « Le langage C » alors plus aucun utilisateur ne peut faire un tutoriel comme cela.
