### ISSUE TITLE
Possible de s'abonner deux fois à un sujet (et d'avoir une erreur 500 après)

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#3685]
Donc je trainais sur [ce sujet](https://zestedesavoir.com/forums/sujet/6452/link-rel-touches-dacces/) quand j'ai voulu le suivre. J'ai donc cliqué sur le bouton "Suivre ce sujet" sauf que le texte ne s'est pas actualisé donc j'ai réessayé en vain. J'ai rechargé la page pour voir et je suis tombé sur une erreur 500.

Plus récemment, j'ai eu deux notifs pour ce même sujet :

![Image des deux notifs](https://cloud.githubusercontent.com/assets/6664636/16547078/20405eb6-4161-11e6-9f99-92459c94e790.png)

J'ai demandé l'erreur renvoyé par Python sur le serveur @vhf, que voici (je n'ai gardé que la fin qui nous intéresse) :

```
Traceback (most recent call last):
  ...
  File "/opt/zds/zds-site/zds/utils/templatetags/interventions.py", line 31, in is_followed
    return TopicAnswerSubscription.objects.get_existing(user, topic, is_active=True) is not None
  File "/opt/zds/zds-site/zds/notification/managers.py", line 41, in get_existing
    user=user, is_active=is_active)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 338, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one TopicAnswerSubscription -- it returned 2!
```

Je crois donc que mes clics sur "Suivre ce sujet" ont créé deux `TopicAnswerSubscription` ce qui peut être problématique.

**Comment by vhf** [comment]
J'ai bien l'impression qu'il y aura plus d'erreur 500 quand #3650 sera en prod. Par contre reste le problème qu'on peut s'abonner 2x à un topic.

**Comment by GerardPaligot** [comment]
A mon avis, la double souscription vient de la latence de Zeste de Savoir qui a du permettre à @Situphen de retenter sa souscription avant que le front ne le bloque.

Il faut mettre une valeur unique au niveau de la base de données.

**Comment by GerardPaligot** [comment]
Merci @vhf

**Comment by vhf** [comment]
`django.db.utils.NotSupportedError: (1235, "This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'")`

https://github.com/zestedesavoir/zds-site/pull/3686/files#r71961864

**Comment by GerardPaligot** [comment]
Je referme, merci @vhf
