### ISSUE TITLE
[v19] Impossible de suivre un forum depuis mon smartphone

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3687]
Navigateur : Firefox 46
OS : Android
Smartphone : Samsung Galaxy S6 Edge 
Température extérieure : 22 degrés celsius :P

Scénario :
- Je me rend sur un forum depuis mon smartphone
- Je slide pour ouvrir la sidebar de gauche
- Je clique sur "suivre ce forum" -> le bouton se transforme en "Ne plus suivre le forum" (jusqu'ici tout va bien)
- Je refresh la page
- Je slide pour afficher la sidebar et je revois "Suivre ce forum" ce qui me fait penser que le forum n'a pas été suivi au premier clic.

Le problème survient aussi bien sur un forum public que sur un forum privé.

**Comment by GerardPaligot** [comment]
Uniquement sur mobile ?

**Comment by firm1** [comment]
Oui juste sur mobile.

Le mar. 12 juil. 2016 11:46, Gérard Paligot notifications@github.com a
écrit :

**Comment by AmarOk1412** [comment]
@firm1 toujours le cas ?

Je viens de tenter sur Android (Chrome/Firefox/Nightly) je n'arrive pas à reproduire.

**Comment by firm1** [comment]
ça a été corrigé dans la v20. Je ferme donc
