### ISSUE TITLE
[Tutoriels] Impossible d'importer un tutoriel

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#369]
Lorsque j'essaie d'importer un tuto, je rencontre une erreur. Je choisis bien le .tuto, le zip avec les images et je clique sur Importer, mais Chrome me renvoie "Page Web inaccessible" au bout de quelques secondes (Code d'erreur : ERR_CONNECTION_RESET).

Sur la pré-prod, ça avait marché sans soucis. L'importe était long (en même temps il y a beaucoup d'image) mais ne plantait pas.

**Comment by SpaceFox** [comment]
Si j'essaie avec une connexion de brute, j'obtiens "413 Request Entity Too Large

nginx/1.2.1"

**Comment by geoffreyc** [comment]
C'est le même soucis qu'on avait eu sur la preprod ? Si c'est ça je m'en
occupe

**Comment by SpaceFox** [comment]
Je suppose que c'est le même problème.

**Comment by geoffreyc** [comment]
Ca devrait etre bon, quelqu'un peut checker?

**Comment by ShigeruM** [comment]
J'ai réessayé d'importer mon tuto (Windows 8 débutants) et cette fois j'ai
une 502 bad gateway. Deux infos qui peuvent peut-être aider :
- ça a mouliné plus longtemps que tout à l'heure avant de planter ;
- je sais que ce tuto à la particularité d'avoir plus d'images que la
  moyenne.

**Comment by geoffreyc** [comment]
Tu aurais la taille des fichiers et ta vitesse dupload STP ?

**Comment by ShigeruM** [comment]
J'ai 25 Mo d'images pour une vitesse d'upload de 34.68 Mbps. Je viens de
refaire le test au boulot ce matin, j'ai toujours l'erreur 502.

**Comment by ShigeruM** [comment]
Je viens de tester avec le tuto "Monter son PC" : cette fois j'arrive à importer le tuto mais j'ai une 502 bad gateway quand j'essaie de la publier (après demande de validation).

**Comment by firm1** [comment]
J'ai configurer le Timeout sur le serveur et on a 600 s (5 min) de dispo pour un traitement désormais.

Cette issue est donc résolu.

**Comment by ShigeruM** [comment]
Ça fonctionne bien maintenant.
