### ISSUE TITLE
Proposer HTTP/2

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3692]
Ce serait une bonne idée.

**Comment by sandhose** [comment]
Bloquée par #3711

**Comment by SpaceFox** [comment]
Absolument pas @sandhose . On peut tout à fait proposer HTTP 1.1 sans TLS, et HTTP/2 sur HTTPS uniquement. Les deux sujets sont donc parfaitement décorrellés.

Cf http://textes.spacefox.fr et https://textes.spacefox.fr (dans cet ordre !) pour un exemple.

**Comment by vhf** [comment]
Testé sur la bêta, voici ma doc : 

``` diff
sudo aptitude -t jessie-backports install nginx openssl

# check nginx config
sudo nginx -t

ls /etc/nginx/sites-enabled/
# in each file, replace spdy with http2
-        listen 443 ssl spdy default_server;
-        listen [::]:443 ssl spdy default_server;
+        listen 443 ssl http2 default_server;
+        listen [::]:443 ssl http2 default_server;
sudo service nginx restart

# check that zds works on both https AND http
```

Par contre Chrome accepte pas. [Il semble](http://serverfault.com/a/733556) que ça soit la faute d'openssl **et de Chrome**. Firefox prend volontiers l'http2.

**Comment by SpaceFox** [comment]
Anéfé, mon serveur est sous Ubuntu et donc n'a pas ce problème.

2016-07-21 16:12 GMT+02:00 victor felder notifications@github.com:

**Comment by gustavi** [comment]
Pour moi niveau beta ça me semble OK, on peut mettre ça sur la prod ?

**Comment by vhf** [comment]
Yep, on peut faire ça lors de la MEP. Là en live c'est pas trop faisable.

**Comment by gustavi** [comment]
Je fais une PR avec les instructions soon. On inclue ça dans la v20 ou la suivante ?

**Comment by vhf** [comment]
Ouais @gustavi. Si tu fais une PR là-dessus, tu peux aussi faire ça dans `deploy.sh` stp : 

``` diff
# Restart zds
sudo systemctl restart zds.{service,socket}

+# clean the cache by restarting it
+sudo service memcached restart
+
# Exit maintenance mode
sudo rm $ENV_PATH/webroot/maintenance.html
```

**Comment by SpaceFox** [comment]
Oh, et c'est du Debian 8, donc `apt` (ou `apt-get`) et pas `aptitude`.
