### ISSUE TITLE
Sélection random dans le menu

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3695]
Serveur : Prod
Version :  v19-mangoustan/f7c21f7
Système : OS X
Navigateur : Google Chrome Version 51.0.2704.103 (64-bit)

Peu importe où vous vous trouvez, le menu "Article" est continuellement sélectionné.

<img width="888" alt="capture d ecran 2016-07-14 a 09 54 42" src="https://cloud.githubusercontent.com/assets/1913901/16832166/505c6b1c-49a9-11e6-82c3-2f541cd5ae91.png">

Je tag large. Je ne sais pas si c'est une mauvais génération du front suite aux récents problèmes serveurs ou si c'est un bug front.

**Comment by GerardPaligot** [comment]
Là je n'ai plus le bug mais plus rien n'est jamais sélectionné.

**Comment by WinXaito** [comment]
Sur Firefox je n'ai rien, mais sur chrome.... C'est **Tutoriels** qui est tout le temps séléctionné.

![zds_bug_13](https://cloud.githubusercontent.com/assets/8223773/16834751/99ce5f74-49b5-11e6-865a-3b74f79a96db.PNG)

Edit1: Et impossible de m'en débarrasser

**Comment by pierre-24** [comment]
Et si c'était un effet de cache ? (vraie question)

Parce que ça en a la gueule.

EDIT: et chez moi, rien n'est sélectionné.

**Comment by GerardPaligot** [comment]
Effectivement, la mise en cache récente du menu peut jouer là dessus. En fait, c'est sans aucun doute ça.

**Comment by WinXaito** [comment]
Sur Edge j'ai aussi **Tutoriels** qui est en permanence sélectionné. 

Cache effacé, rien de changé.

**Comment by pierre-24** [comment]
> Cache effacé, rien de changé.

Nan, le cache coté serveur ;)

**Comment by gustavi** [comment]
Oui c'est bien ça.

**Comment by WinXaito** [comment]
Ahh autant pour moi :p

**Comment by pierre-24** [comment]
Mmmh, je vois pourquoi ça a été fait, mais y'a pas moyen de réduire la "zone de cache" à juste les tags et les catégories ?

(Typiquement, [ça](https://github.com/zestedesavoir/zds-site/blob/dev/templates/base.html#L185-L333), c'est un peu fort ^^ )

**Comment by firm1** [comment]
C'est bien le cache coté serveur qui a été ajouté recemment.

Le jeu. 14 juil. 2016 11:33, Pierre Beaujean notifications@github.com a
écrit :

**Comment by WinXaito** [comment]
Oui, plus de problème pour ma part.

**Comment by WinXaito** [comment]
J'ai à nouveau le problème.

**Comment by vhf** [comment]
@WinXaito normal, rien n'a encore été entrepris pour résoudre cette régression.

**Comment by vhf** [comment]
PR introduisant la régression: #3607

**Comment by GerardPaligot** [comment]
Merci @vhf !
