### ISSUE TITLE
Les formules mathématiques ne fonctionnent pas sur les forums

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#3698]
En message de forum, les formules mathématiques sont sont pas interprétées (mais elles fonctionnent dans les tutoriels).

Pour reproduire, tapez ceci dans un forum :

```
$$x^2$$

bla $x^2$ bla
```

**Comment by vhf** [comment]
#3750 pour référence. Ça corrige peut-être ce bug.

**Comment by GerardPaligot** [comment]
La PR semble bien corriger le bug. :)

![capture d ecran 2016-07-31 a 22 09 42](https://cloud.githubusercontent.com/assets/1913901/17279026/8bbc8d48-576b-11e6-9640-124527196a9a.png)
