### ISSUE TITLE
Send Email when MP is send

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#37]
Je viens d'installer un serveur SMTP sur le serveur de prod. Et il faudrait donc envoyer un mail a chaque MP envoyé non lu.

**Comment by delphiki** [comment]
Dans quel cas un MP reçu serait lu ?

Un délai entre le moment où on poste le MP et le moment où le mail est envoyé ?

**Comment by firm1** [comment]
Il existe une table qui enregistre le dernier posts lu par un membre dans un MP. [Voici sont modèle](https://github.com/Taluu/ZesteDeSavoir/blob/master/zds/mp/models.py#L136)

L'idée étant que : 
- un MP à 10 messages (M1,M2,m3, ... M10)
- un utilisateur poste un message M11 dans un MP
- pour chaque participant à cet MP, on va voir si le dernier message lu correspond au message M10
  - si c'est bien le cas, on envoi le mail à ce participant
  - sinon on ne fait rien du tout

Le but étant que l'utilisateur ne soit pas spammé par les mails pour chaque nouveau message dans le MP.

**Comment by delphiki** [comment]
Ah oui, d'accord, j'avais pas pensé à ça, effectivement.

**Comment by firm1** [comment]
Cette feature a été implémentée. Je ferme.
