### ISSUE TITLE
[MP] Autocomplétion pour les pseudos

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#370]
À voir pour la prochaine beta : ajouter l'autocomplétion dans le champs "destinataires".

Un plugin tel que Select2 permettra de faire ça aisément à partir du moment où côté back on peut avoir un json avec la liste des membres qui correspond.

**Comment by Eskimon** [comment]
Est-ce que l'API ( [#471](https://github.com/Taluu/ZesteDeSavoir/issues/471) )pourrait pas servir a ca tant qu'a faire ?

**Comment by Alex-D** [comment]
Dans l'absolu, l'API doit servir aux +1/-1, au déplacement des parties d'un tuto, etc. Tout ce qui est dynamique et asynchrone niveau front.

L'issue est surtout là pour le côté front de la chose.

**Comment by Alex-D** [comment]
En fait, j'ai l'impression que rien dans le back ne me permet de faire une recherche par pseudo...

**Comment by firm1** [comment]
F'xd.

Merci à sandhose

**Comment by Eskimon** [comment]
J'aimerais rouvrir le ticket pour que l'autocompletion soit attendu aux autres cas:
- Ajout d'un auteur d'articles
- Ajout d'un auteur de tuto
- Ajout d'un membre dans un MP déjà commencé
- Autres cas que j'oublie ?

**Comment by sandhose** [comment]
> Autres cas que j'oublie ?
- Ajout d'un membre d'une galerie

Sinon ouais, je vais rendre le script plus flexible (adapter aux cas où l'on attends qu'un seul pseudo), et intégrer ça... Je vais essayer de faire une PR dans la soirée

**Comment by sandhose** [comment]
De toutes façons, il y a quelques améliorations à faire, comme limiter le nombre de résultats à afficher, et afficher les résultats les plus probants en premiers... M'en occupe ce soir, si j'ai le temps

**Comment by Alex-D** [comment]
Tout ce qui est codé côté JS doit être applicable à de multiples endroits par le simple ajout d'une classe ou d'un data-*

**Comment by sandhose** [comment]
C'est ce que je pensais faire... :+1: 

Je me demandais juste, plutôt avoir un seul attribut, avec les options en JSON (`<input data-autocompletion='{ "type": "multiple" }' />`), ou plusieurs attributs (plus verbeux, mais plus jolie ; `<input data-autocompletion data-autocompletion-type="multiple" />`) ?

**Comment by Alex-D** [comment]
`data-autocomplete` : english in the code, please :D

Ensuite, la première me semble mieux, car on peut par exemple donner l'url du JSON à taper, sous réserve que la forme du résultat soit toujours identique.

**Comment by sandhose** [comment]
> ... car on peut par exemple donner l'url du JSON à taper ...

Hein ? Pas compris.. :neutral_face:

**Comment by Alex-D** [comment]
On pourrais réutiliser le script pour autocomplete d'autres choses, les tags par exemple sur les tutos/articles ou ce genre de choses. Du coup il faudrait pouvoir changer l'URL du JSON à aller interroger via le HTML comme ça on a un truc souple :)
