### ISSUE TITLE
ZEP-09 : Sondages, questions à propos de l'API

### ISSUE THREAD

**Issue by Emeric54** [zestedesavoir/zds-site#3700]
Comme vous le savez peut-être, je suis sur le développement de la ZEP-09, les sondages. Comme conseillé par @vhf, j'ouvre une issue ici afin de faciliter les discussions.

J'ai une API fonctionnelle. Il faut que j'effectue une passe complète pour nettoyer le code, et donc par la même occasion, il faudrait que je structure proprement mon API, car comme @sandhose me l'a justement fait remarqué, pour le moment, ce n'est pas le cas. Je me tourne donc vers vous pour aller vers les meilleures solutions possibles.

Il y a encore plusieurs choses à faire (gérer le vote unique/multiple, la suppression d'un vote), mais le principal est là.

Pour le moment, l'API est composée de 3 vues :
- Récupération des infos sur un sondage -> GET sur `/api/sondages/[pk]`. Réponse :

``` json
{
      "pk": 1,
      "title": "Nancy ou Metz ?",
      "anonymous_vote": false,
      "type_vote": "u",
      "enddate": "2017-02-03T00:00:00",
      "choices":
      [
          {
              "pk": 1,
              "choice": "Nancy",
              "votes": 1
          },
          {
              "pk": 2,
              "choice": "Metz",
              "votes": 0
          }
      ]
  }
```
- Récupération de la liste des votants, si le sondage est non-anonyme -> GET sur `/api/sondages/choix/[choice_pk]`:

``` json
{
  "users": [
    {
      "id": 1,
      "username": "admin",
      "html_url": "/membres/voir/admin/",
      "is_active": true,
      "date_joined": "2016-06-06T15:38:31.846540",
      "avatar_url": "https://secure.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?d=identicon"
    }
  ]
}
```
- Vote -> `/api/sondages/vote/[pk]`, avec `pk` correspondant au choix associé.

On peut certainement, faire mieux, ce serait top si vous pouviez me conseiller.

Merci !

**Comment by GerardPaligot** [comment]
Je ne comprends pas où est la question.

**Comment by Emeric54** [comment]
Comment faire ça mieux, plus _proprement_ ?

**Comment by GerardPaligot** [comment]
Hormis la liste des utilisateurs qui devrait avoir un résultat comme toutes les autres listes de l'API, rien ne me choque.

**Comment by pierre-24** [comment]
J'ai quelques suggestions/questions:
- `startdate` : on ne sais jamais, ça peut être utile (sauf si tu me dis que c'est redondant avec la date de création du topic ... Mais on pourrait envisager de l'étendre pour les tribunes, par exemple).
- `type_vote` ? À quoi ça correspond ? Pourquoi `u` ? (je vais probablement te suggérer de mettre un truc plus explicite que "u")
- Est ce qu'on peut ne pas mettre de `enddate` ?

**Comment by Emeric54** [comment]
> startdate : on ne sais jamais, ça peut être utile (sauf si tu me dis que c'est redondant avec la date de création du topic ... Mais on pourrait envisager de l'étendre pour les tribunes, par exemple).

En effet, je vais ajouter ça.

> type_vote ? À quoi ça correspond ? Pourquoi u ? (je vais probablement te suggérer de mettre un truc plus explicite que "u")

Type du vote => unique ou multiple. C'est vrai que ce n'est pas très explicite. 

> Est ce qu'on peut ne pas mettre de enddate ?

C'est possible, sachant qu'il est possible de fermer un sondage manuellement à tout moment.

> la liste des utilisateurs [...] devrait avoir un résultat comme toutes les autres listes de l'API

Pas faux, je vais regarder de ce côté.

**Comment by vhf** [comment]
Salut ! Super, merci pour ton boulot.
- Précise quels verbes sont associés à quels endpoints ;)
- Pour le vote, plutôt `/api/sondages/<pk>/vote` ?
- Peut-on renommer `type_vote` en `poll_type`, puisque ça concerne le sondage et pas le vote ?
- Je vois `html_url`, `is_active`, `date_joined`, mais `startdate`, `enddate`. Possible d'uniformiser ça en ayant du `snake_case` partout ?

**Comment by GerardPaligot** [comment]
> Je vois html_url, is_active, date_joined, mais startdate, enddate. Possible d'uniformiser ça en ayant du snake_case partout ?

Je suppose que @Emeric54 s'est inspiré de `pubdate` qui est cohérent du coup.

**Comment by vhf** [comment]
Ok merci @GerardPaligot. Du coup @Emeric54, `start_date` et `end_date`. `pubdate` reste tel quel pour l'instant.

**Comment by GerardPaligot** [comment]
@Emeric54 Plus besoin de retours ? :)

**Comment by Emeric54** [comment]
> Peut-on renommer type_vote en poll_type, puisque ça concerne le sondage et pas le vote ?

Euh, j'aurais plutôt dit que c'est le vote qui peut-être unique ou multiple, non ?

---

Donc pour le vote on aurait : 
`PUT` ou `DELETE` sur `/api/sondages/<pk>/vote` avec un body de type `{ "choice":  1 }` ?

---

Je ne devrais pas tarder à ouvrir une PR sur le dépôt ZdS. Ce sera encore un WIP (quelques bugs à corriger + tout le front), mais ça me permettra d'avoir vos retours sur ma façon de faire les choses. Encore merci !

**Comment by sandhose** [comment]
## Endpoints

```
  Verbe URL                             Réponse    Description
==================================================================
    GET /sondages                       [Poll]     Liste des sondages accessibles par l'user (tous si admin ?)
   POST /sondages                       Poll       Crée un sondage
    GET /sondages/[pk]                  Poll       Récupération d'un sondage
    PUT /sondages/[pk]                  Poll       Modifie un sondage
 DELETE /sondages/[pk]                  -          Supprime un sondate
    GET /sondages/[pk]/votes            [Vote]     Liste des votants
   POST /sondages/[pk]/votes            Vote       Vote pour un utilisateur (défaut: utilisateur actuel, plus si admin ?)
    GET /sondages/[pk]/votes/[user id]  Vote       Récupération d'un vote ; valeur spéciale pour user: `self` ou `me` pour l'user actif
    PUT /sondages/[pk]/votes/[user id]  Vote       Modification d'un (de son) vote
 DELETE /sondages/[pk]/votes/[user id]  -          Suppression d'un (de son) vote
    GET /sondages/[pk]/choix            [Choice]   Liste des choix
   POST /sondages/[pk]/choix            Choice     Ajout d'un choix (à limiter à la création + admin)
    GET /sondages/[pk]/choix/[pk]       Choice     Récupération d'un choix
    PUT /sondages/[pk]/choix/[pk]       Choice     Modification d'un choix (à limiter à la création + admin)
 DELETE /sondages/[pk]/choix/[pk]       -          Suppression d'un choix (à limiter à la création + admin)
```

## Réponses

``` rust
Poll {
    pk:        Number,
    url:       String,
    title:     String,
    anonymous: Boolean,
    multiple:  Boolean,
    active:    Boolean,
    enddate:   String,
    choices:   [Choice],
    votes:     [Vote],
    votes_url: String
}
```

``` rust
Choice {
    pk:        Number,
    url:       String,
    title:     String,
    votes:     Number,
    votes_url: String,
}
```

``` rust
Vote {
    pk:         Number,
    url:        String,
    user:       User,
    user_id:    Number,
    user_url:   String,
    choice:     Choice,
    choice_id:  Number,
    choice_url: String,
}
```

---

Pour les endpoints de listes, il faut filtrer en param get (ex: `/sondages?user=me&active`)

Pour les autres, il faut voir quel champ on _expand_ de base, bien sûr réglable via paramètre GET

Par exemple, `Poll.votes` et `Poll.choices` ne _devraient_ pas apparaître en vue liste, mais peut-être en vue d'un seul sondage ; pareil pour `Vote.choice`, pas forcément visible dans les vues où l'information est déjà présente dans les contextes parents

Je pense qu'inclure à chaque fois 1 niveau de recursion par défaut, ça peut être pas mal
