### ISSUE TITLE
Problème d'affichage sur mobile sur la page d'un sujet qui n'est pas la dernière

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3701]
Via le [forum](https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=39#p115711)

Vu sur Microsoft Lumia 640 : 

![screen](http://img11.hostingpics.net/pics/402360wpss201606250002.png)

**Comment by AmarOk1412** [comment]
Salut,
Je souhaiterais me mettre à contribuer un peu plus au site ayant plus de temps cette année. Je souhaiterais donc prendre ce bug pour me faire la main. Cependant j'ai une petite question. 

Pour le moment voici ce que j'ai :
![3701](https://cloud.githubusercontent.com/assets/1888628/18811243/f4da61ce-8277-11e6-8cde-b0ed4e71977f.png)

Pour le moment j'ai fait un `overflow-y: hidden` dans __pagination.scss_ mais je ne pense pas que ce soit le fix le plus propre. Je pense que la plus logique serait d'enlever totalement _&.prev a_ et _next_. Le probleme décrit dans l'issue se présentant avec une résolution < 410 px en largeur. Pour ça je propose de rajouter un _media-mobile-small_, qui enleve les 2 fleches et avec un `overflow-y: hidden`  pour avoir le maximum de boutons utiles en bas. Qu'est-ce-que vous en pensez ?

J'en ai profité pour enlever le gros espace en bas, en rouge sur l'image (dans `_topic-message.scss`, il y avait une erreur tout en bas)

**Comment by GerardPaligot** [comment]
@AmarOk1412 Positionne toi dans un sujet avec assez de page pour afficher la flèche suivante et précédente, puis il faut parvenir à reproduire le bug sur une résolution d'écran similaire à celle du Lumia de @gustavi puisque le bug ne se reproduit pas partout. Cela sera difficile pour toi de corriger un bug que tu ne peux pas reproduire. (:

Concernant ta solution technique, je ne m'y connais pas assez dans le dev front. Faudra ping @sandhose ou @Situphen qui sont les personnes avec le plus de compétences dans ce domaine dans l'équipe.

**Comment by AmarOk1412** [comment]
@GerardPaligot J'arrive à reproduire le bug sans soucis (cf l'image de mon post), ma question était plutôt en rapport avec qu'est-ce-qu'il faut vraiment afficher lorsque la résolution est vraiment petite :)

**Comment by AmarOk1412** [comment]
Du coup, petite contrib du soir (j'en ferais une plus grosse la prochaine fois), je propose de mettre une flexbox à la place

**Comment by pierre-24** [comment]
Merci @AmarOk1412 pour le fix :)
