### ISSUE TITLE
Utiliser les touches d’accès usuelles pour faciliter la navigation

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3702]
Pour plus d'informations c'est [sur le forum](https://zestedesavoir.com/forums/sujet/6452/link-rel-touches-dacces/?page=1#p116617).

**Comment by FanJiyong** [comment]
Salut ! 

La navigation chez l'utilisateur à l'origine de cette demande se fait via un plugin. 

Le changement concerne l'ajout de l'attribut "rel", et c'est très bon pour le référencement et l'ergonomie / accessibilité. 

http://www.w3schools.com/tags/att_a_rel.asp 

Ça me semble pas très complexe et très important de mettre ça en place. 

Gros poutouxxxxx

**Comment by A-312** [comment]
https://developer.mozilla.org/fr/docs/Web/HTML/Types_de_lien Explication plus détaillée.
