### ISSUE TITLE
Uniformiser certains noms vers snake_case

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3703]
Exemples de code actuel :

``` py
context["is_staff"] = self.request.user.has_perm('forum.change_topic')
context['isantispam'] = self.object.antispam()
```

```
pubdate
```
### Note

Si vous faites du code review ou si vous développez un truc en vue d'une PR, veillez à ne pas introduire de noms qui ne seraient pas snake case. Il n'est pas nécessaire que vous changiez ceux existants à ce stade.

Exemple : Si vous touchez du code où il y a `pubdate`, n'ajoutez pas `enddate` mais `end_date`. Pas nécessaire de changer `pubdate` pour l'instant.

**Comment by motet-a** [comment]
C’est un truc qui est en train d’être fait au fur et à mesure, je pense qu’on est sur la bonne voie et qu’il n’y a plus besoin d’une issue ouverte pour se souvenir de ça :upside_down_face:
