### ISSUE TITLE
Uniformiser l'usage des quotes, utilisez des single quotes partout

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3704]
Par exemple avec https://github.com/zheller/flake8-quotes

Exemple de code actuel : 

``` py
            cleaned_data['pubdate'] = datetime.now()
        else:
            date = cleaned_data["pubdate"]
```
### Note

Evitez d'introduire des double quotes (`"`). Si vous reviewez, signalez les double quotes qui font partie du diff. Pas nécessaire de signaler les double quotes qui ne sont pas touchées par une PR.

On préfère toujours `'blah'` à `"blah"`, mais si la string contient `'` on préfère `"l'utilisateur"` à `'l\'utilisateur'`.

**Comment by vhf** [comment]
Un grand merci à @Eskimon qui a semble-t-il consacré quelques heures de vacances à cette tâche ingrate. 👍

**Comment by vhf** [comment]
J'ai cru que c'était terminé, au temps pour moi. :)

**Comment by Eskimon** [comment]
:D il me reste quelques modules. Sinon ça a pas pris tant de temps quand les bons outils sont mis en oeuvre (et je suis pas en vacances, j'ai juste des enfants qui se lèvent tôt :D )

**Comment by Eskimon** [comment]
Lorsque les deux dernieres PR seront mergées il faudra refaire une dernière passe car il reste 2/3 lignes qui sont passé au travers

**Comment by pierre-24** [comment]
Voilà voilà :)

**Comment by Eskimon** [comment]
Je fais une dernière PR qui ajoute flake8-quote au dépendance de dev + fais quelques derniers ajustements passé au travers des mails du filet

**Comment by vhf** [comment]
T'as la classe.

**Comment by Eskimon** [comment]
Plus qu'un merge et ce ticket sera fermable \o/

**Comment by pierre-24** [comment]
Et grâce au super-caribou, c'est bon :)
