### ISSUE TITLE
Documentation éparpillée

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3708]
Aujourd'hui, nous avons de la documentation à 3 endroits différents :
- [Read the Docs](http://zds-site.readthedocs.io/fr/latest/) pour toute la documentation (enfin, je le pensais) ;
- Le [wiki](https://github.com/zestedesavoir/zds-site/wiki) pour le script de la synchro de la bêta à la prod (aucune idée de savoir s'il est à jour) ;
- La [page GitHub](http://zestedesavoir.github.io/zds-site/#/) pour une documentation front (aucune idée de savoir si elle est à jour).

@sandhose pourrait me dire si la documentation front sur la page GitHub est encore utilisé et/ou mise à jour ? 
@gustavi ou @vhf est-ce que le script de synchro bêta/prod est à jour sur le Wiki et si on peut placer cette documentation dans Read the Docs ?

**Comment by gustavi** [comment]
Niveau Wiki le script est OK. Il a été mis là pour qu'on l'ai quelque part je pense.

J'avais oublié l'existance de http://zestedesavoir.github.io/zds-site/#/interface-utilisateur/icones

**Comment by sandhose** [comment]
> @sandhose pourrait me dire si la documentation front sur la page GitHub est encore utilisé et/ou mise à jour ?

Absolument pas à jour, je mettrais bien un truc en place type Astrum[1](http://astrum.nodividestudio.com/)
ou `postcss-style-guide`[2](https://github.com/morishitter/postcss-style-guide) pour de la doc front type styleguide, avec
snippets et tout ; à voir. (pour la question que je vois venir de
« pourquoi pas dans Sphinx », c'est juste non, c'est pas possible
simplement et proprement)

**Comment by pierre-24** [comment]
> pour la question que je vois venir de « pourquoi pas dans Sphinx », c'est juste non, c'est pas possible simplement et proprement

On en avait longuement débatu, et ça avait déjà été dit. Sauf que il semble quand même il y avoir une directive `raw` ([voir ici](https://groups.google.com/forum/#!topic/sphinx-users/d6gg86LnItY), et plus d'infos [là](http://docutils.sourceforge.net/docs/ref/rst/directives.html#raw-data-pass-through), entre autre la possibilité d'inclure arbitrairement un autre fichier). Bref, ce serait probablement du chipotage. 

Par contre, les deux liens que tu présentent ont de la gueule. Mais ... Ou les stocker ?

**Comment by sandhose** [comment]
> > pour la question que je vois venir de « pourquoi pas dans Sphinx », c'est juste non, c'est pas possible simplement et proprement
> 
> On en avait longuement débatu, et ça avait déjà été dit. Sauf que il semble quand même il y avoir une directive raw (voir ici, et plus d'infos là, entre autre la possibilité d'inclure arbitrairement un autre fichier). Bref, ce serait probablement du chipotage.

D'où mon « simplement _et_ proprement ».

> Par contre, les deux liens que tu présentent ont de la gueule. Mais ... Ou les stocker ?

Au final, c'est juste un set de fichier statiques à servir (c'est aussi le cas pour sphinx) ; du coup, je pense vraiment qu'on peut envisager un `docs.zestedesavoir.com` qui pointe sur un serveur (ça peut être le serveur de prod, hein) qui sert 2/3 fichiers statiques, updaté par travis lorsqu'on pousse un tag de release, et c'est bon

**Comment by pierre-24** [comment]
Alors autant rapatrier ce qui est sur ReadTheDocs avec, non ?

**Comment by vhf** [comment]
Pourquoi pas docs.zestedesavoir.com hébergé par github pages ?

**Comment by GerardPaligot** [comment]
Si nous partons dans l'idée de conserver une page dans le style de la [documentation front obsolète](http://zestedesavoir.github.io/zds-site/#/), on est en droit de se poser la question si nous conservons Read The Docs ou pas ? Est-ce que quelqu'un à connaissance d'une raison valable de l'utiliser plutôt qu'un autre outil ?

J'aimerais simplement avoir à un même endroit toute la documentation. L'outil qui est derrière n'est que du détail pour moi.

**Comment by pierre-24** [comment]
Je vois deux raisons évidentes, mais pas incontournables:
- C'est hébergé ailleurs. Donc indépendant de nos éventuels soucis de serveur.
- Le _build_ de la doc est à peu près automatique et géré de manière efficace (build par branche, re-fait à chaque _merge_, et ainsi de suite). Mais de toute façon, c'est une question à poser aussi si on part sur un outil comme ceux que propose sandose.

**Comment by GerardPaligot** [comment]
@pierre-24 Ce que tu proposes, c'est exactement ce que permet les pages GitHub aussi. On peut même imaginer stocker la documentation sur la branche `dev`, rajouter un hook qui écoute les merges sur dev pour builder la documentation automatiquement et placer les fichiers statiques sur une branche `gh-pages` pour les rendre accessible depuis l'URL de la documentation front obsolète actuelle.

**Comment by pierre-24** [comment]
Je sais ;)

**Comment by AmarOk1412** [comment]
Fixed http://docs.zestedesavoir.com/!
