### ISSUE TITLE
[MP] Ajouter un lien d'envoi de MP sur le profil

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#371]
Un lien sur le profil permettant d'avoir le champ "destinataire" auto-complété serait plutôt cool.

Ça concerne le front mais surtout le back (puisqu'il faut que le lien fonctionne).

**Comment by firm1** [comment]
Le lien fonctionne déjà, exemple : http://zestedesavoir.com/mp/nouveau?username=victor

Par contre, c'est un oubli dans le template

**Comment by Alex-D** [comment]
D'accord, je m'en occupe dans la branche intégration soon.

**Comment by geoffreyc** [comment]
Elle va être fun a merger cette branche d'intégration !

**Comment by Alex-D** [comment]
Elle va me prendre plusieurs heures à merger je pense oui, mais il faut ce qu'il faut.

**Comment by firm1** [comment]
Fixé.
