### ISSUE TITLE
Pas d'HTTPS partout ?

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#3711]
Y'a-t-il une raison qui explique pourquoi on a pas par défaut de l'HTTPS partout ? 

On a du code spé pour forcer ça sur les membres & sur certaines vues, ce qui implique d'ailleurs aussi d'avoir un paramètre dans le `settings.py` pour _ne pas_ forcer quand l'HTTPS est pas dispo (typiquement, en local), alors qu'on pourrait juste avoir nginx qui redirige tout, tout le temps, en HTTPS.

En plus, on a les header d'HSTS qui sont envoyés, qui forcent donc tous les clients qui ont loadé _au moins une fois_ une ressource en HTTPS chez nous d'être _tout le temps_ en HTTPS. Pour moi, ça a vraiment aucun sens qu'on continue à servir quoi que ce soit en HTTP

Dernier point, le SPDY et l'HTTP/2 fonctionnent qu'en HTTPS, donc passer en full-https, c'est aussi un gain de performance _dans la plupart des cas_ (je pense qu'on peut rien faire pour les gens qui trainent encore sur IE9).

J'en profite pour linker ce site: https://istlsfastyet.com/

**Comment by Situphen** [comment]
Il y a eu trois petites discussions a ce propos ([ici](https://zestedesavoir.com/forums/sujet/1463/suggestion-http-https-www-ou-pas/), [ici](https://zestedesavoir.com/forums/sujet/2626/forcer-le-https-pour-les-membres-connectes/) et #2040). Globalement tout le monde était d'accord pour forcer lors de la connexion et lorsque l'utilisateur est connecte mais il y avait un désaccord pour le forcer sur tout le site.

**Comment by artragis** [comment]
@vhf sur #3606 tu m'as dit que nginx forçait le https, donc on peut fermer?

**Comment by vhf** [comment]
Oui merci, bien vu @artragis !
