### ISSUE TITLE
Bug dans la pagination d'un (très) gros MP

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#3716]
Je suis membre d'un MP très long quelques centaines de pages. Depuis un moment déjà, la pagination/notification bugouille. En effet, les notifs ne nous emmène pas sur la bonne page lorsqu'un changement de page a eu lieu. au lieu de ca, on est emmené en haut de la page précédente. Il faut alors changer à la main de page (en scrollant comme un dingue pour vérifier qu'on rate pas une page).

J'ai l'impression que cela arrive quand on a un chevauchement de plusieurs nouveaux messages, certains à la fin de la page n et d'autres à la page n+1 (mais sans certitude, c'est juste une hypothèse).

Bref, chiant à reproduire.

**Comment by gustavi** [comment]
ping @GerardPaligot

**Comment by Maelan** [comment]
je confirme le bog (ainsi que plusieurs autres personnes). je l’ai constaté avec certitude dans le cas où le premier message non lu est celui qui provoque une nouvelle page. dans ce cas, le lien mène incorrectement à la page n−1 mais l’ancre est correcte (et ne mène à rien, du coup). Eskimon a l’impression que ça ne s’applique pas forcément qu’au premier message de la nouvelle page, mais je n’ai observé que ce cas depuis que je fais attention.

**Comment by gustavi** [comment]
Est-ce que vous avez un mp et un message en particulier pour que j'essaye de débug ça ? Je n'arrive pas à reproduire en dev :/

**Comment by Ymox** [comment]
Pour ma part, j'avais l'impression que c'était quand le dernier message non-lu arrivait dans les N premiers de la page suivante. Pourrait-ce être un calcul légèrement différent entre la "vraie" pagination et ce qui détermine sur quelle page on devrait se retrouver ?

##### Edit

Je pencherais pour N = 1, dès le deuxième "nouveau" message, c'est la bonne page qui semble être afichée. Est-ce que le calcul de la page tient bien compte des messages qui sont repris, donc un `+ 1` qui pourrait manquer ?

**Comment by artragis** [comment]
est-ce encore d'actualité?

**Comment by Ymox** [comment]
On vérifiera à l'occasion, mais il me semble qu'au dernier changement de page le 12 (donc un jour après le déploiement il me semble), malheureusement oui, c'était encore d'actualité.

**Comment by Ymox** [comment]
Bon, ça vient de me faire le coup. J'avais bien vu un message en fin de page, et la suite est arrivée (8 messages non-lus, tous sur la page suivante). En cliquant sur la notification, ça m'a dirigé vers l'avant-dernière page, donc celle qui comportait que des messages déjà lus.

**Comment by Ymox** [comment]
C'est toujours d'actualité avec la v28.1. Je rédigeais le message qui partait sur une nouvelle page, j'ai été redirigé vers l'avant-dernière page. J'ai eu le même comportement alors que j'éditais le message.

Est-ce que quelqu'un pourrait me pointer sur l'endroit où le calcul du numéro de page est effectué ?

**Comment by philippemilink** [comment]
Je viens de me pencher sur ce ticket. Je n'arrive pas à reproduire en faisant un échange de messages entre deux utilisateurs, jusqu'à ce que le dernier message envoyé fasse changer de page : dans ce cas, la redirection vers la dernière page fonctionne bien, pareil pour le lien de la notification chez l'autre utilisateur ou pour la redirection après avoir édité ce message.

Je n'arrive pas à identifier un commit en particulier qui aurait corrigé le bug sans qu'on s'en aperçoive, mais le module des MPs a eu droit à quelques grosses refactorisations ces derniers mois / années, donc c'est possible que ce soit dans ces changements-là.

Pour info, le numéro de page est calculé ici : https://github.com/zestedesavoir/zds-site/blob/44468ca0b4c3eb013fadb642ea29f69407507f7b/zds/mp/models.py#L387

S'il n'y a pas d'objection, je fermerais le ticket dans quelques jours.
