### ISSUE TITLE
[Droits] Erreur lors de la déconnexion depuis une page nécessitant des droits

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#372]
Il faut rediriger l'utilisateur vers la page d'accueil lors de la déconnexion, sinon il se mange une 403 sur les pages qui nécessitent des droits d'admin/other.

**Comment by firm1** [comment]
Pour moi ça n'a pas trop de sens. S'il se déconnecte, ce n'est pas pour se reconnecter direct.

Ce bug est un peu de la folie.

**Comment by Alex-D** [comment]
Tu n'as pas compris. Tu es sur une page d'admin. Tu clic sur déconnexion. Tu te mange une 403 : pas cool.

**Comment by firm1** [comment]
Si si je comprend bien.

En gros ça veut dire, tu es sur une page d'admin, tu te deconnecte et tu va
sur tu page de login ? Je trouve ça plus chelou.

**Comment by Alex-D** [comment]
Je parlais de la page d'accueil moi, la home, pas login.

**Comment by SpaceFox** [comment]
Corrigé, mergé --> Fermé :)
