### ISSUE TITLE
la fonctionnalité d’abréviation de l’éditeur est boguée

### ISSUE THREAD

**Issue by Maelan** [zestedesavoir/zds-site#3724]
(testé sur la version en production)

la fonctionnalité d’abréviation de l’éditeur (pour n’importe quel type de contenu) est intrusive et même boguée. cliquer sur le bouton remplace tout le contenu du message par un grossier « NaN », ce qui est assez moche en soi. le contenu est restauré lorsqu’on fait « valider », mais **pas** si on fait « annuler », provoquant la perte du message (heureusement récupérable par Ctrl+z).

par ailleurs, quand on valide, on est amené tout en haut de la page, ce qui est agaçant.

**Comment by Anto59290** [comment]
@gustavi Ce bug ressemble beaucoup au #3893 qui vient d'être fermé, non ?

**Comment by Karnaj** [comment]
C’est réglé en bêta.
