### ISSUE TITLE
Merge de la branche hotfix-v19 vers dev pas fait

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3726]
Pour éviter d'avoir un trop gros merge à faire et pour éviter de perdre des commits, la branche `hotfix-v19` aurait du être mergé dans `dev` suite à la release-v19.1.

Je tag bloquant parce que ça doit être fait urgemment avant la v20.

**Comment by vhf** [comment]
Yep bien vu. Faut même faire ça avant tout autre merge si possible.

**Comment by vhf** [comment]
Répondu trop vite avant de lire. Faut merger hotfix-truc dans dev, pas prod
dans dev. Ça revient presque au même mais je le dis quand même.

**Comment by GerardPaligot** [comment]
Tout à fait. J'édite.

**Comment by gustavi** [comment]
De mémoire c'est pas fait lorsqu'on fait la v20 ?

**Comment by vhf** [comment]
Nope, c'est sitôt que le hotfix est en prod. Ainsi on évite que son merge
dans dev fasse des conflits après d'autres merges dans dev. Le but étant la
parité ou plutôt une sorte de suivi environ chronologique des commits entre
dev et prod après chaque release. :)
