### ISSUE TITLE
Ajouter les votes (+1/-1) aux tribunes

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3729]
C'est plus une note qu'une issue : il faudra penser à ajouter les votes sur les tribunes quand le système aura été refacto.

Ne pas oublier d'ajouter ça dans `zds.tutorialv2.managers.PublishableContentManager.get_last_opinions()`.

**Comment by nils-van-zuijlen** [comment]
> quand le système aura été refacto

C'est prévu pour quand ?

**Comment by Situphen** [comment]
Je ferme car remplacé par le concept de claps #6094 je pense
