### ISSUE TITLE
[Forum] Ne plus suivre les sujets dont on a pas/plus les droits

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#373]
Un membre ayant accès au forum du staff, suit un sujet.
Lorsqu'il n'est plus staff (n'a donc plus les droits de lire ce sujet) il est tout de même notifié, et n'a visiblement pas la possibilité d'arrêter de suivre ce sujet.

Propositions personnelles :
- Cas rare donc pas urgent donc on laisse ça pour plus tard
- Le lien de désabonnement ne doit pas nécessiter de droits (si ce n'est être loggué) : solution simple et pas sale selon moi.

**Comment by SpaceFox** [comment]
(Tiens, un autre bug-OCR :D)

Une solution encore plus _user-friendly_ serait carrément de dégager tous les topics "privés" de la liste des topics suivis quand on déstaffe quelqu'un.
Cela dit, je crains que ce soit bien compliqué pour pas grand-chose... auquel cas la solution du désabonnement sans droits serait la plus simple.

**Comment by Alex-D** [comment]
Le soucis c'est que le "déstaffement" est un événement un peu particulier. En plus en l'occurence c'est un mec qui a réussi à poster dans un forum protégé. Si un jour on ferme un forum, on arrive dans le même cas.

**Comment by firm1** [comment]
Ceci a été géré par le fait d'unfollow ledit topic.
