### ISSUE TITLE
Lecture zen et commentaires

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3732]
Via le [forum](https://zestedesavoir.com/forums/sujet/6570/lecture-zen-et-commentaires/?page=1#p118265) : 

> Lorsqu’on lit un contenu (tutoriel ou articles) avec plus d’une page de commentaire avec la lecture zen, l’avertissement « **Attention**, vous n'êtes pas sur la dernière page de ce sujet, assurez-vous de l'avoir lu dans son intégralité avant d'y répondre » est présent. Puisque les commentaires ne sont pas présents en lecture zen, ce serait mieux de le supprimer. Voici un [article](https://zestedesavoir.com/articles/1432/retour-dans-le-passe-pour-zds/) et [un tutoriel](https://zestedesavoir.com/tutoriels/249/rediger-sur-zds/) pour voir le problème.

**Comment by malnuxstarck** [comment]
J'ai lu une solution dans le forum. Si on mettait la class en display: none elle va plus s'affiché moi je pense plutot qu'on doit regarder lorsqu'on clique sur lecture zen . on cache la classe  dans le cas contraire on l'affiche.

**Comment by Karnaj** [comment]
@malnuxstarck : en changeant le css de cette manière, on cache le bloc seulement dans le cas où on est en lecture zen.

Je prends.

**Comment by GerardPaligot** [comment]
Encore merci @Karnaj !
