### ISSUE TITLE
Caractère smiley inséré incorecte

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#3734]
Bonsoir,

Il ne me semble pas que ça aie déjà été dit, mais quand je souhaite insérer le smiley `>_<`, l'éditeur m'ajoute `&gt;_&lt;`

J'ai contrôlé tous les autres caractères, c'est le seul qui pose problème.

@cgabard

**Comment by vhf** [comment]
Yep. La raison est que les codes des smileys sont dans un attribut html, et doivent donc être échappés. Le problème est qu'ensuite on ajoute ces codes dans la textarea comme texte.

**Comment by rezemika** [comment]
Désolé de remonter ce vieux ticket, je voudrais juste signaler qu'il y a un autre problème avec ce même smiley. En effet, quand on le tappe manuellement en écrivant ">_<", le markdown l'interprète comme une citation et affiche donc "_<" dans un blockquote.

Il faudrait peut-être ne valider les blockquotes que si les chevrons sont suivis d'une espace ? Par exemple : 

`> Une citation.`

Et pas ceci : 

`>Une citation`

**Comment by gustavi** [comment]
\>\<

```
\>\<
```

**Comment by artragis** [comment]
#4388 @vhf

**Comment by nils-van-zuijlen** [comment]
On peut fermer cette issue, résolu par #4960

**Comment by gllmc** [comment]
Bien vu !
