### ISSUE TITLE
Google indexe nos pages de recherche

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3738]
En voulant vérifier quelque chose quant à l'efficacité de notre moteur de recherche interne, j'ai lancé une recherche sur Google avec `site:zestedesavoir.com` ([cette recherche](https://www.google.fr/search?q=site:zestedesavoir.com+myrath) pour être exact).

Et là, c'est le drame : dans les résultats de recherche je trouve :

```
https://zestedesavoir.com/rechercher/?q=été&page=940
```
1. Je ne pense pas qu'indexer nos résultats de recherche soit pertinent,
2. Je ne pense pas qu'indexer la 940ème page de résultats de recherche soit pertinent,
3. C'est relativement facile à corriger.

La première étape serait de rajouter le blocage de toutes les URL en `/rechercher/` dans le `robots.txt`.

Peut-être qu'il faudrait aussi rajouter des `nofollow` sur certains liens (qui mènent à la recherche), et vérifier qu'on ne demande pas explicitement l'indexation d'une page de recherche (par exemple via un sitemap mal configuré).

**Comment by SpaceFox** [comment]
PS : j'ai mis une priorité haute, parce que du coup c'est un fort risque de duplicate content et que ça devrait être facile à corriger donc y'a pas de raison que ça traîne. N'hésitez pas à corriger si vous n'êtes pas d'accord.

**Comment by vhf** [comment]
Je crois que du côté sitemap c'est OK mais je vérifierai. Le robots.txt
doit suffire, le nofollow semble superflu. Ça me semble aussi important
comme problème, bien vu.

**Comment by GerardPaligot** [comment]
Merci @vhf !
