### ISSUE TITLE
[Tutoriels] Le téléchargement aux formats HTML, EPUB et PDF ne fonctionnent pas

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#374]
Erreur interne au serveur lors de la tentative de téléchargement dans l'un de ces formats.

Les formats archive et MD ne sont pas affectés. Je soupçonne pandoc.

**Comment by SpaceFox** [comment]
Je ne sais pas si quelque chose a été fait, mais aujourd'hui ça fonctionne en prod.

Donc, je considère le sujet comme clos.
