### ISSUE TITLE
Sitemap pour /pages/

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3741]
Aucun [sitemap](https://zestedesavoir.com/sitemap.xml) ne donne nos pages [/pages/](https://zestedesavoir.com/pages/).

C'est pas top niveau SEO, vraiment pas top.
## Comment résoudre
1. Regarder comment les autres sitemaps sont générés.
2. Générer un sitemap similaire mais pour les pages.

**Comment by Emeric54** [comment]
Bien vu @vhf. Je prends.

**Comment by GerardPaligot** [comment]
Merci @Emeric54 !
