### ISSUE TITLE
Documenter l'utilisation des milestones

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3742]
Notre doc (read the docs) ne contient rien au sujet de l'utilisation des milestones, pourtant clairement je vois qu'on en utilise.

**Comment by GerardPaligot** [comment]
Cette issue est une bonne chose. Pour info, on utilise quotidiennement 3 milestones :
- Abandon / Ferme / Doublon / etc. : En toute sincérité, je ne sais pas trop pourquoi elle existe. A mon avis, c'est historique.
- Version n : On y regroupe toutes les issues (ou PR si la PR n'a pas d'issue) qui concerne la dernière release en date (dans sa version majeure, on en compte pas les hotfix).
- Version développement : On y regroupe toutes les issues (ou PR si la PR n'a pas d'issue) qui vont figurer dans la prochaine release.

**Comment by SpaceFox** [comment]
Tiens, j'étais persuadé que c'était écrit quelque part…
- « Abandon / Ferme / Doublon / etc. » fait ce que son nom indique, elle a surtout servi à faire du tri à une époque. @Eskimon tu confirmes ?
- Toute issue (ou PR s'il n'y a pas d'issue) dont la correction est mergée dans `dev` → « Version de développement »
- Toute issue (ou PR s'il n'y a pas d'issue) dont la correction est mergée ailleurs (la branche de release si c'est une correction de bêta, `prod` en cas de hotfix) → « Version N »

Ça permet de savoir ce que contient une version, et accessoirement de générer les rapports de release tels qu'on peut les lire dans les articles sur ZdS.

La « Version de développement » s'appelle comme ça parce qu'elle date du moment où on ne savait pas à l'avance quel serait le nom exact d'une release. Donc quand on lançait la release N, on renommait « Version de développement » en « Version N » et on créait une nouvelle « Version de développement ».

Maintenant que les numéros de version sont prédictibles, on peut se contenter de créer les milestones directement avec le bon nom. Cela dit, « Version de développment » a cet avantage que, pendant la période où il y a une release active, on voit immédiatement si on attribue ou non la bonne milestone, sans avoir à réfléchir au numéro de version.

**Comment by vhf** [comment]
Ok, merci.

J'ai ouvert #3747 avec une proposition et son pourquoi.
