### ISSUE TITLE
Supprimer model_name.py

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3744]
Cf. #3743, `zds/utils/templatetags/model_name.py` n'est pas utilisé, c'est du code mort.

Il faut le supprimer et en supprimer la doc : http://zds-site.readthedocs.io/fr/latest/front-end/template-tags.html#le-module-model-name

**Comment by DevHugo** [comment]
Je confirme que le fichier sert à rien. J'étais sur d'en avoir déjà discuté dans un ticket mais j'arrive pas à remettre la main dessus.

**Comment by GerardPaligot** [comment]
Thanks.
