### ISSUE TITLE
Limite des 15min après avoir posté

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#3749]
Bonjour,

Je suis tombé cette après-midi sur le poste de `pascal.ortiz` sur son cours python: https://zestedesavoir.com/forums/sujet/6598/decouvrir-la-programmation-avec-python/

Et ce qui m'a interpelé c'est `Il y a une heure, il y a 57 minutes, il y a 55 minutes`, car dans tous les cas on a pas les 15 minutes pour éviter le flood.

![capture](https://cloud.githubusercontent.com/assets/8223773/17102876/de50bace-527b-11e6-9f07-df84d45ff29a.PNG)

**Comment by GerardPaligot** [comment]
Ce cas présent est un peu particulier. Le sujet est géré par Zeste de Savoir lui même suite à des actions de l'auteur sur la mise en bêta de son contenu. A chaque nouvelle mise en bêta, un message est créé sur son sujet pour prévenir les membres.

Le flood n'a donc pas de raison d'être appliqué dans ce cas précis.

**Comment by WinXaito** [comment]
Ok je comprend mieux, si on y pense pas, rien ne le différencie. C'est juste étonnant que l'auteur aie décidé de les masquer.
