### ISSUE TITLE
Créer des icones pour le nouvel affichage des notifications

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3751]
Quand vous listez la liste des notifications (anciennes et nouvelles), on aimerait bien des icones qui donnerait un visuel quand au type de la notification.

**Comment by FanJiyong** [comment]
Avez-vous la liste exhaustive de ces alertes ?

Le mer. 21 déc. 2016 à 23:43, victor felder <notifications@github.com> a
écrit :

**Comment by Anto59290** [comment]
Ca fait l'objet d'un ticket aussi ;) https://github.com/zestedesavoir/zds-site/issues/3770

Dans un commentaire il est écrit ça : 
subscription_type c'est : forum, topic, privatetopic, publisablecontent.
type c'est : topic, post, privatepost, contentreaction.

Donc je suppose que l'on peut recevoir des notifs pour les forum, un topic, un mp et un contenu (article / tuto / TL)

**Comment by FanJiyong** [comment]
Yop, 

En résumer il y a comme icônes a faire : 
- Forum
- Topic
- MP
- Article
- Tuto
- TL

Questions : 

- Quelle différence entre "Forum" et "Topic" au niveau des notifications
- Les MP rentre aussi dans le cadre des notifications ?

**Comment by Anto59290** [comment]
Les Mp je dirait que non (de mémoire) puisqu'il vont dans leur propre menu.

Pour les "différences" je vérifie ça sur une version de test et je revient vers toi.

**Comment by FanJiyong** [comment]
![161223_icon_type](https://cloud.githubusercontent.com/assets/15154100/21456332/9083b29c-c927-11e6-8e48-bddd198116e8.png)

**Comment by Anto59290** [comment]
Et dans le menu de notifs tu juge ça pertinent (la cloche) ?

**Comment by FanJiyong** [comment]
Oui du coup on garde la même choses, sauf qu'ils sont blanc. (j'ai juste plus de notifs pour une maquette :p)

**Comment by Anto59290** [comment]
Ca roule. Je met ça sur ma liste alors. Tu peux envoyer un PSD/AI/SVG avec les icônes ?

**Comment by FanJiyong** [comment]
et voilà !

[icones_notif.zip](https://github.com/zestedesavoir/zds-site/files/671038/icones_notif.zip)

**Comment by GerardPaligot** [comment]
Il y a le ping aussi ! (:

**Comment by FanJiyong** [comment]
Quelle contexte ?

Le ven. 23 déc. 2016 à 18:13, Gérard Paligot <notifications@github.com> a
écrit :

**Comment by GerardPaligot** [comment]
@FanJiyong <- Celui ci 

En gros, dans tous les commentaires (forums et contenus), tu pourras pinger quelqu'un pour créer une notification chez le destinataire vers le commentaire sur lequel il a été pingé.
