### ISSUE TITLE
Notification persistante

### ISSUE THREAD

**Issue by qwertygc** [zestedesavoir/zds-site#3762]
Bonjour,

Je vais vous remonter un petit bug, j’ai évoqué sur un [autre topic](https://zestedesavoir.com/forums/sujet/6637/notification-non-voulu-et-persistante/), mais vu que c’est pas exactement le même problème, je préfère ouvrir un [topic dédié](https://zestedesavoir.com/forums/sujet/6661/notification-persistante/), ainsi qu’une issue Github.

J’ai voulu m’abonner à un [topic](https://zestedesavoir.com/forums/sujet/6652/recap-communautaire/). Bien dirons-nous. Le problème est que :
1. Je peux pas me désabonner de ce topic (quand je clique sur se désabonner, bah rien, alors que sur d’autres topics, je trouve un comportement normal).
2. J’ai une double notification persistante (qui veut pas partir, c’est pénible), voir image ci-dessous.
3. Quand je veux répondre à ce topic, erreur 500, pas de problèmes avec les autres topics.

![](https://zestedesavoir.com/media/galleries/2245/1ac60d6b-e051-460e-b23c-f6263cf59ea0.png)

Mais je vois constamment la tête de mon loup préféré, donc ça adouci ma souffrance :p

Merci de votre travail les gens, et bonne chance pour la résolution !

**Comment by GerardPaligot** [comment]
Merci @qwertygc du rapport de bug.

@sandhose @vhf @gustavi Nous avons un souci avec le Sentry de la prod puisqu'il n'y a aucune exception qui semble correspondre à la 500 de @qwertygc. En fait, il n'y en a plus depuis 2 mois.

Serait-il possible de le remettre en état pour récupérer la stack ici ?

**Comment by vhf** [comment]
Hmm @GerardPaligot je serais pas surpris qu'en effet Sentry ne signale plus rien depuis la prod.

@sandhose comment est configuré Sentry ? Que lui faut-il comme accès ? Quels services ? Bref tout ça.

**Comment by vhf** [comment]
Bon c'est pas le cas @GerardPaligot . Le dernier event Sentry depuis la prod date d'il y a environ 1j.

Faudrait vraiment réparer les notifications.

La 500 de @qwertygc vient probablement du fait qu'il a une double notif sur ce topic. Du coup le `get()` retourne 2 objets au lieu d'un seul, donc 500.

**Comment by GerardPaligot** [comment]
@vhf On ne doit pas voir le même Sentry. Moi je regarde celui de [Production / Backend](https://sentry.sandhose.fr/zeste-de-savoir/backend/searches/1/) et la dernière erreur remontée date de 3 mois.

Ou alors, je ne sais pas utiliser cet outil, chose possible. :-°

**Comment by vhf** [comment]
@sandhose tu peux me passer admin sur le Sentry, que je change ça ?

**Comment by GerardPaligot** [comment]
Normalement, si tu es authentifié avec GitHub, tu as les droits automatiquement (de mémoire).

**Comment by vhf** [comment]
Nope, je suis 'membre' et je ne peux donc pas te donner accès au projet 'Gandi' du Sentry, encore moins supprimer 'Prod' et renommer 'Gandi' en 'Prod'.

**Comment by vhf** [comment]
Voilà @GerardPaligot c'est réglé.

**Comment by GerardPaligot** [comment]
La procédure pour reproduire le bug a été expliquée sur ce [message](https://zestedesavoir.com/forums/sujet/6638/notification-dun-sujet-non-accessible/?page=1#p120032).

**Comment by qwertygc** [comment]
Si je clique sur suivre le topic, j'ai ce message : 

![](https://zestedesavoir.com/media/galleries/2245/de14878f-deaa-4878-9447-9423c910bcbc.png)

HS, mais comment vous avez eu le badge zds member ?

**Comment by Situphen** [comment]
> HS, mais comment vous avez eu le badge zds member ?

C'est un groupe sur Github, ça donne les droits de merge et de gestion des PRs/tickets. C'est le CDP ou le DTC qui gère les membres du groupe je crois.

Edit de gustavi : c'est exact ;)

**Comment by vhf** [comment]
@GerardPaligot Est-ce que tu as une piste pour débugger ça ? Une idée d'où on devrait regarder ?

**Comment by gustavi** [comment]
Bon j'ai identifié le problème. Lorsqu'un lis un sujet pas encore lu on a https://github.com/zestedesavoir/zds-site/blob/dev/zds/notification/receivers.py#L52 qui est appelé. Donc à ce moment on vérifie si l'utilisateur à une notification liée au sujet (il s'est abonné spécifiquement à ce sujet) ou une notification liée à un abonnement au forum du topic du sujet.

Donc le problème c'est que si on est abonné au forum A et qu'on déplace un sujet de A vers B, lorsqu'on va le lire (on a eu une notification car on est abonné à A) on va vérifier si on s'est abonné au sujet (donc non) et si on c'est abonné au forum du sujet qui est maintenant B (donc non encore car on s'est abonné à A).

Solution 1 : lorsqu'on déplace le sujet de A vers B on supprime toutes les notifications de ce sujet des membres abonnés à A. Problème : on va se retrouver avec des gens qui ont reçu un mail pour une notification inexistante.

Solution 2 : lorsqu'on déplace le sujet de A vers B on fait en sorte de remplacer la notification via l'abonnement à A par une notification au sujet. Problème pour les sujets qui deviennent innaccessibles (forum privé).

Solution 3 : je prends si vous avez quelque chose de plus propre !

**Comment by vhf** [comment]
Solution 3 : lorsqu'on déplace le sujet de A vers B on update toutes les ~~notifications~~ souscriptions de ce sujet.

**Comment by GerardPaligot** [comment]
Pour rappel, voici comment fonctionne les notifications : Les membres **souscrivent** à des **contenus notifiables** et des notifications sont crées à partir des souscriptions créées par ces utilisateurs. Il est important de savoir qu'une notification **ne devrait pas exister** si elle n'a pas de souscription.

Second rappel, voici la procédure pour reproduire le bug : Plusieurs utilisateurs ont une souscription à un forum X mais pas (forcément) à un forum Y. Un sujet est créé par un membre sur le forum X mais un membre du staff déplace le sujet du forum X vers le forum Y. Lorsque le membre a créé le sujet dans le forum X, une notification a été créée pour tous les membres avec une souscription pour le forum X.

Pourquoi la solution 1 ? Mettre à jour la notification implique de créer une souscription non voulue pour les membres au forum Y. Je suis donc pour supprimer les notifications tout en sachant que déplacer un sujet est suffisamment rare pour tolérer des e-mails utiles (et encore, le lien reste valide).

**Comment by vhf** [comment]
Je propose d'ajoute un flag sur les notifications, genre `is_dead`. Une notification est valide quand elle n'est pas `is_dead`. Au lieu de supprimer les notifications comme dans la solution 1, on les passe en `is_dead`. Quand on affiche un sujet à un membre connecté et qu'on doit de toute façon faire un petit traitement pour marquer la potentielle notification comme `lue`, si la notif en question est `is_dead` on affiche un bandeau disant "ce sujet a été déplacé, blabla notification email blabla".

**Comment by GerardPaligot** [comment]
Ma solution est simple, bonne et acceptable. La solution de @vhf est chiante mais pourrait être meilleure si on la change un petit peu. Voici l'algo théorique qui devrait résoudre le bug pour la solution de @vhf :
1. Rajouter un champ boolean `is_dead` dans le modèle des notifications pour marquer une notification comme morte parce qu'elle n'est plus attachée à une souscription sur le bon forum.
2. 2 possibilités :
   1. Lorsqu'un membre du staff déplace le sujet d'un forum X suivi vers un forum Y non suivi, mettre le flag ìs_dead`à`True` pour signaler au système que cette notification est morte (paix à son âme).
   2. Lorsqu'un membre du staff déplace le sujet d'un forum X suivi vers un forum Y suivi **actif**, mettre à jour la souscription de la notification de la souscription de l'ancien forum au nouveau. (Vous êtes un héros, vous avez sauvé une notification).
3. 2 possibilités :
   1. Dans [la méthode receivers qui marque un sujet comme lu](https://github.com/zestedesavoir/zds-site/blob/dev/zds/notification/receivers.py#L52), faire une requête supplémentaire qui va récupérer toutes les notifications mortes de ce sujet et les marquer comme lue.
   2. Vous n'avez pas à vous soucier de la notification mise à jour, elle sera marquée comme lue automatiquement grâce à sa nouvelle souscription.

Maintenant, en ce qui concerne le script pour résoudre toutes les notifications persistantes, il suffit de récupérer toutes les notifications sur un sujet qui n'est pas dans son forum. En gros, un algo naif serait le suivant :

``` pseudocode
notif <- Récupérer toutes les notifs sur un sujet du système
si le sujet de la notification a un forum différent que le forum de la souscription de la notification:
  alors la notification est persitente et next
sinon next.
```

**Comment by GerardPaligot** [comment]
Pour information, voici une commande qui détecte les notifications persistantes :

``` python
class Command(BaseCommand):
    help = 'Remove all persistent notifications.'

    def handle(self, *args, **options):
        content_type = ContentType.objects.get_for_model(Topic)
        notifications = Notification.objects.filter(content_type=content_type, is_read=False).all()
        for notification in notifications:
            if notification.subscription.content_object != notification.content_object.forum:
                print notification # Persistent
                # notification.is_read = True
                # notification.save()
```

C'est sans doute un algo naif, n'hésitez pas à le signaler si vous avez mieux. :)

**Comment by vhf** [comment]
``` py
from django.contrib.contenttypes.models import ContentType
from zds.notification.models import Notification
from zds.forum.models import Topic
from django.db.models import Q
from django.db.models import F
notifications = Notification.objects.filter(Q(content_type=content_type) & Q(is_read=False) & ~Q(subscription__content_object=F('content_object__forum'))).all()
```

Trop beau pour être vrai, hélas. Merci pour la commande !

**Comment by GerardPaligot** [comment]
> Trop beau pour être vrai, hélas

Fonctionne pas ?

**Comment by GerardPaligot** [comment]
Ceci dit, vu la notification persistante du premier message, j'ai des doutes sur le fait que le sujet "Récap' communautaire" ai été déplacé ... :)

**Comment by tleb** [comment]
Ça a fonctionné pour moi en tout cas. Merci !

**Comment by firm1** [comment]
Ma notif a disparue. Merci
