### ISSUE TITLE
Google a indexé uploads.zestedesavoir.com comme un doublon de zestedesavoir.com

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3764]
Dans une recherche Google, je trouve https://uploads.zestedesavoir.com/membres/voir/SpaceFox/ en résultats (et plusieurs autres pages en uploads.zestedesavoir.com).

Pire : ce lien réponds et sert le même contenu que https://zestedesavoir.com/membres/voir/SpaceFox/

Plusieurs problèmes donc :
1. Ça réponds, ce qui me fait dire qu'il y a _au moins_ une erreur d'infra.
2. Ça sert _exactement_ la même chose que le domaine principal, et comme il n'y a pas d'URL canonique indiqué, ça crée de la duplication de contenu sur j'imagine tout le site.
3. C'est servi avec un certificat HTTPS foireux.

À ce niveau, je ne vois pas quoi faire de plus intelligent que de créer un certificat valide pour ces URLs et de les pointer via des redirections HTTP 301 vers les URLs normales. Cela dit, peut-être qu'il y a du contenu pour lesquelles ces URLs sont légitimes, mais je ne vois pas quoi…

**Comment by Situphen** [comment]
> Cela dit, peut-être qu'il y a du contenu pour lesquelles ces URLs sont légitimes, mais je ne vois pas quoi…

De mémoire c'était pour les tutoriels importés du SdZ, non ?

**Comment by gustavi** [comment]
Si c'est ça, ça n'existe plus depuis des mois.

**Comment by firm1** [comment]
les upload.zds.com sont des urls pour heberger des images de certains
tutoriels importés. Donc si on casse cette url, pas mal de tutoriel se
retrouverons sans images (c'est le cas du MOOC sur Arduino, et de pas mal
de cours importés de OC).

A mon avis il faudrait corriger la conf nginx pour que le domaine ne serve
pas les pages du site.

Le dim. 14 août 2016 12:27, Laville Augustin notifications@github.com a
écrit :

**Comment by vhf** [comment]
Bien vu, merci @firm1 . Le problème est plus vaste que ça. On a un tas de CNAME qui pointent et servent le site. `ftp.`, `smtp.`, `utils.`, `uploads.`, etc. C'est super mauvais. (Notez que je mets pas des liens parce qu'on veut pas que ce soit crawlé.)

Je suis pas expert en config nginx mais je suppose qu'il suffit d'ajouter les bons server names dans la config `zestedesavoir` et d'y ajouter un truc spécifique à `uploads.` pour qu'il ne serve pas d'html.

**Comment by vhf** [comment]
J'ai fait un dump de la DB de la prod et greppé `//uploads.zestedesavoir`, y'a que 11 résultats et ils sont dans des discussions à propos de l'utilisation potentielle de ce domaine.

Il n'est pas mentionné dans notre config nginx. Il ne sert donc rien d'autre que zestedesavoir.com, et on peut le virer sans trop se poser de questions.

J'ai fait une PR avec les changements.

**Comment by gustavi** [comment]
C'est changé sur la prod, ça le sera sur la bêta dans la soirée, merci @vhf.
