### ISSUE TITLE
[Membres] Cacher les adresses mail sur leur profil

### ISSUE THREAD

**Issue by Ge0** [zestedesavoir/zds-site#377]
Il est possible de voir l'adresse mail **de chaque membre** à condition d'être nous-mêmes connectés.

Il serait préférable de restreindre cette fonctionnalité au staff.

**Comment by Alex-D** [comment]
Je vais faire ça.

**Comment by Alex-D** [comment]
En fait, il y a déjà une option qui permet de cacher l'adresse email. Donc ce fix est inutile.

Par contre, ne serait-il pas judicieux de mettre l'affiche désactivé par défaut ?

**Comment by SpaceFox** [comment]
> Par contre, ne serait-il pas judicieux de mettre l'affiche désactivé par
> défaut ?

AMHA c'est même indispensable.

**Comment by Alex-D** [comment]
Je vais plutôt faire ça alors.

**Comment by Alex-D** [comment]
Fixé et mergé.
