### ISSUE TITLE
Documenter l'installation de MySQL en production

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3771]
Aujourd'hui on n'a absolument rien sur MySQL sur la production, ça serait bien d'ajouter un petit morceau de doc là dessus, au moins pour avoir le nom de la BDD et de l'utilisateur qui y accède afin d'avoir des scripts fonctionnels.

**Comment by SpaceFox** [comment]
On a besoin de ça dans les scripts ?
Normalement du moment que le settings_prod est cohérent avec la base, ça
marche non ?

Le 18 août 2016 9:08 AM, "Laville Augustin" notifications@github.com a
écrit :

**Comment by gustavi** [comment]
Script de syncro prod/beta. Sinon je suis d'accord.

**Comment by vhf** [comment]
Yep. Ce sera d'autant plus important après le passage à utf8mb4, puisque ça demande un tuning de la conf mysql assez conséquent. Je m'en occupe après la mep v20.

**Comment by GerardPaligot** [comment]
@vhf, @gustavi Ca semble fermeable cette issue non ? (:

**Comment by vhf** [comment]
Presque mais pas tout à fait. Laissons-la ouverte jusqu'à l'arrivée de la v20. Quand elle sera en prod faudra mettre à jour ici : https://github.com/zestedesavoir/zds-site/pull/3781/files#r75842737

pour refléter le passage à 5.6 et mettre à jour tous les fichiers de conf mysql depuis le makefile de la documentation.
