### ISSUE TITLE
Réserver son propre contenu crée un MP vide avec 2 fois le même utilisateur

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3776]
Pour reproduire, avec un utilisateur qui peut valider des contenus (admin par exemple via les fixtures): 
- Créer un contenu (article ou tutoriel)
- Demander la validation du contenu
- Réserver le contenu
- Aller dans ses MP

Bug en image : http://i.imgur.com/b73ojhz.png

**Comment by GerardPaligot** [comment]
Congrats, tu viens de gagner le premier usage du tag `P-Basse`. :)

Dans la vraie vie, c'est pas censé arrivé qu'un staff valide son propre contenu.

**Comment by Karnaj** [comment]
Dans ce cas, il faut faire quoi ? Interdire la réservation de ses propres contenus, ou ne pas envoyer de MP quand ça arrive ?

**Comment by Situphen** [comment]
~~Plutôt interdire la réservation de ses propres contenus je dirais, non ? Car ils ne sont pas sensés pouvoir publier un de leur contenu tout seul (si un Staff pète un cable et met un tutoriel nawak en page d'accueil, c'est bof)~~

(voir https://github.com/zestedesavoir/zds-site/issues/3776#issuecomment-241238357)

**Comment by SpaceFox** [comment]
Ne pas envoyer de MP. Réserver son propre contenu, c'est pratique pour
corriger des fôtes.

**Comment by Situphen** [comment]
> Réserver son propre contenu, c'est pratique pour corriger des fôtes.

Tu peux détailler ? Je comprends pas trop. :/

**Comment by gustavi** [comment]
Le jour où on ne peut plus publier ses propres contenus j'arrête la QA !

**Comment by vhf** [comment]
@Situphen imagine que @SpaceFox soit DTC de ZdS. Il écrit un article à propos de la dernière version de ZdS. Il le publie. Il voit qu'il y a une faute de frappe, il veut la corriger. Il la corrige. Quelle est la procédure idéale ? Soumettre sa correction de faute de frappe à validation, attendre des heures que quelqu'un réserve et valide, ou plutôt réserver lui-même le contenu pour valider immédiatement sa modification ? :)

**Comment by Situphen** [comment]
En y réfléchissant, je suis d'accord avec la proposition de @SpaceFox, réserver son propre tutoriel peut être très utile et puis si jamais un Staff pète un câble, il a 3600 autres manières de faire du site une poubelle xD (mais ça n'arrivera pas, <3 aux Staffeux) !

**Comment by Karnaj** [comment]
Et les autres messages (validation annulée, validation refusée), faut-il aussi ne pas les envoyer dans le cas où l’auteur est seul et qu’il est le validateur ?

**Comment by GerardPaligot** [comment]
Aujourd'hui, en parcourant les tests des contenus, je suis tombé là dessus : https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/tests/tests_views.py#L1889-L1906

On semble avoir spécifié que nous ne voulons pas s'auto-publier.

**Comment by vhf** [comment]
Effectivement @GerardPaligot , il faudra penser à enlever ce test.

**Comment by pierre-24** [comment]
Non, @GerardPaligot : malgré ce commentaire succin (et pas très explicite), un staff peut très bien s'auto-publier. Le test est plus là pour vérifier qu'on c'est pas foiré sur la gestion des droits et qu'un utilisateur lambda n'as pas le pouvoir d'un staff :)

**Comment by Karnaj** [comment]
@pierre-24 : il faudrait tester qu’un utilisateur non staff ne peut pas publier un contenu, pas seulement ses contenus, donc il faudrait tester la réservation et la validation avec un autre utilisateur non staff que l’auteur.

**Comment by pierre-24** [comment]
Ce qui est fait [juste en dessous](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/tests/tests_views.py#L1910) ;)

(j'ai assez bien betonné les tests à ce niveau là)

**Comment by Karnaj** [comment]
Non, il y a juste le test pour l’accès à la version en validation (`public cannot access a tutorial in validation` et `Same for guest`), il n’y a pas le test pour la réservation et la validation.

**Comment by pierre-24** [comment]
Anéfé, j'avais pas vu ;)
