### ISSUE TITLE
URGENT / BLOQUANT / SITE HS : Certificat HTTPS de prod expiré

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3779]
Le certificat HTTPS de prod a expiré. Et comme on a HSTS activé, toute personne ayant accédé au site au moins une fois en HTTPS est bloquée dehors sans aucun moyen de contournement.

Je ne comprends pas bien comment c'est possible que personne n'ait réagi, normalement les relances sont faites sur la boite mail de l'asso, et il devait y avoir au moins un MP à ce sujet.

Notez que je suis indisponible jusque ce dimanche midi.

**Comment by vhf** [comment]
J'ai réglé y'a ~10 minutes. J'ai pas accès à la boite mail de l'asso, j'ai reçu 0 email à ce sujet sur mon adresse email. On va continuer à voir comment améliorer le processus et la comm, mais pas ici, par MP.

J'ai mis en place letsencrypt, ça a pris 4-5 minutes. Il est renouvelé par un cron.

**Comment by SpaceFox** [comment]
C'est parce que vous n'avez pas accès à la boite mail que j'ai fait cette
issue en l'attribuant aux DTC et surtout que les relances ont été
transmises par MP. Si aucune de ces 2 actions ne vous envoie de mail, c'est
probablement un problème.

Le 21 août 2016 11:16 AM, "victor felder" notifications@github.com a
écrit :
