### ISSUE TITLE
Problème avec l'aspostrophe ( ' -> &#39; )

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#3782]
Bonjour,

Dans les MPs de clem, (ainsi que le message de Bienvenue sur Zeste de Savoir) si il y a une apostrophe `'` dans le pseudo on obtient : `&#39;`, ainsi que dans les sujets qui signale une mise à jour d'un tutoriel en bêta. 

https://zestedesavoir.com/forums/sujet/6775/pourquoi-la-vie-privee-est-important-navoir-rien-a-cacher-est-hors-sujet/

(Les mails semblent être ok).

**Comment by Karnaj** [comment]
Il faut utiliser `safe` dans les templates concernés. Il y a d’autres templates où il ne sont pas appliqués ([le message privé pour l’activation de la bêta](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/messages/beta_activate_pm.md) et [celui pour la réservation de contenu](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/messages/validation_reserve.md).

**Comment by Karnaj** [comment]
Je prends.

**Comment by gustavi** [comment]
@GerardPaligot tu peux ajouter @Karnaj dans les gens qu'on peut assigner stp ? :)

**Comment by GerardPaligot** [comment]
Invitation envoyée. Mes félicitations pour ta promotion @Karnaj. :)
