### ISSUE TITLE
La topbar a perdu son élément de contextualisation

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3783]
Navigateur : Firefox 45
OS : Windows Seven
Zoom : 100%

Il fut un temps, ou lorsqu'on était dans le forum, on avait une barre orangée qui soulignait le menu forum, idem pour les article et les tutoriels. ça permettait de voir d'un coup d'oeil ou on se trouve.

J'ai l'impression que ça n'existe plus (que ce soit en mode connecté ou pas). Je la trouvais assez pratique cette contextualisation.

**Comment by GerardPaligot** [comment]
duplicate https://github.com/zestedesavoir/zds-site/issues/3695 et donc corrigé dans la v20 ?

**Comment by firm1** [comment]
Ah j'aurai juré que l'autre issue avait été fixée avec la v19. Bon bah je ferme celle-ci
