### ISSUE TITLE
Beta test v20

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3787]
La v20 est en beta, ça fait longtemps qu'on l'attendait !

Malgré les vacances de beaucoup de devs, j'ai l'impression que c'est quand même une grosse release qui nous attend là !

@zestedesavoir/les-jeunes-pousses @zestedesavoir/les-bourgeons @zestedesavoir/pleins-pouvoirs : à vous pour les tests en live sur la beta ! 👯 

Si tout roule, on met ça en prod ce week-end :)

**Comment by vhf** [comment]
Rapport pour le jalon **[Version de développement](https://github.com/zestedesavoir/zds-site/milestones/Version de développement)** _()_

56 tickets sont compris dans ce jalon (0 ouverts et 56 fermés)

# Tickets toujours ouvert

Aucun ticket

# Tickets fermé

## Corrections de bug

| Ticket # | Titre | Label(s) |
| --- | --- | --- |
| [#3779](https://github.com/zestedesavoir/zds-site/issues/3779) | URGENT / BLOQUANT / SITE HS : Certificat HTTPS de prod expiré | C-Infra, P-Bloquante, S-Régression |
| [#3778](https://github.com/zestedesavoir/zds-site/pull/3778) | [ci skip] Répare la config des tests locaux | P-Haute, S-Régression |
| [#3777](https://github.com/zestedesavoir/zds-site/pull/3777) | Répare l'affichage des MPs | C-Front, P-Bloquante, S-Régression |
| [#3773](https://github.com/zestedesavoir/zds-site/pull/3773) | Corrige un import dans zds.notification.views qui casse Travis | C-Back, P-Haute, S-BUG |
| [#3757](https://github.com/zestedesavoir/zds-site/pull/3757) | Ordonne les tags par popularité | C-Back, S-BUG |
| [#3738](https://github.com/zestedesavoir/zds-site/issues/3738) | Google indexe nos pages de recherche | P-Haute, S-BUG |
| [#3736](https://github.com/zestedesavoir/zds-site/pull/3736) | Cache menu par fragments | C-Front, S-Régression |
| [#3733](https://github.com/zestedesavoir/zds-site/pull/3733) | Retire les avertissements en lecture zen | C-Front, S-BUG |
| [#3730](https://github.com/zestedesavoir/zds-site/pull/3730) | Correction du script de MEP | C-Infra, P-Haute, S-BUG |
| [#3728](https://github.com/zestedesavoir/zds-site/pull/3728) | Strip tags | C-Back, P-Haute, S-BUG |
| [#3722](https://github.com/zestedesavoir/zds-site/pull/3722) | Répare l'admin django pour les topics | C-Back, P-Haute, S-BUG |
| [#3714](https://github.com/zestedesavoir/zds-site/pull/3714) | utf8mb4 Script de migration & doc | C-Back, C-Infra, S-BUG |
| [#3713](https://github.com/zestedesavoir/zds-site/pull/3713) | Documente gunicorn pid et IP serveurs | C-Infra, S-Régression |
| [#3706](https://github.com/zestedesavoir/zds-site/issues/3706) | La réservation d'un contenu crée un MP sans le validateur | C-Back, Facile, S-BUG |
| [#3689](https://github.com/zestedesavoir/zds-site/issues/3689) | Les tests ne passent pas suivant la gitconfig utilisateur | C-Back, S-BUG |
| [#3688](https://github.com/zestedesavoir/zds-site/pull/3688) | Ajout des sitemaps au robots.txt | Facile, S-BUG |
| [#3685](https://github.com/zestedesavoir/zds-site/issues/3685) | Possible de s'abonner deux fois à un sujet (et d'avoir une erreur 500 après) | S-BUG |
| [#3668](https://github.com/zestedesavoir/zds-site/issues/3668) | Problème de rendu des smileys dans une citation | C-Front, S-BUG |
| [#3658](https://github.com/zestedesavoir/zds-site/issues/3658) | Texte incohérent au niveau des notifications | C-Front, Facile, S-BUG |
| [#3642](https://github.com/zestedesavoir/zds-site/issues/3642) | [v18] Un tag trop long provoque une erreur 500 | C-Back, S-BUG |
| [#3463](https://github.com/zestedesavoir/zds-site/issues/3463) | Erreur de dépendance dans la documentation d'installation | C-Documentation, Facile, S-BUG |
| [#2217](https://github.com/zestedesavoir/zds-site/issues/2217) | Impossible de se connecter à partir de Facebook | C-Back, S-BUG |

## Évolutions

| Ticket # | Titre | Label(s) |
| --- | --- | --- |
| [#3775](https://github.com/zestedesavoir/zds-site/pull/3775) | Ferme la bêta des articles à la publication | C-Back, S-Évolution |
| [#3774](https://github.com/zestedesavoir/zds-site/pull/3774) | Ajoute bouton « retour à la liste des sujets » | C-Front, S-Évolution |
| [#3759](https://github.com/zestedesavoir/zds-site/pull/3759) | Permet de signaler un message masqué | S-Évolution |
| [#3758](https://github.com/zestedesavoir/zds-site/pull/3758) | Supprime le bouton d’envoi de MP sur les profils bannis | S-Évolution |
| [#3747](https://github.com/zestedesavoir/zds-site/pull/3747) | Documente les milestones | C-Documentation, S-Évolution |
| [#3744](https://github.com/zestedesavoir/zds-site/issues/3744) | Supprimer model_name.py | C-Back, C-Documentation, Facile, S-Évolution |
| [#3739](https://github.com/zestedesavoir/zds-site/pull/3739) | Liste les notifications dans l'API. | C-API, S-Évolution |
| [#3709](https://github.com/zestedesavoir/zds-site/pull/3709) | Envoyer un sujet dans le bugtracker. | S-Évolution |
| [#3705](https://github.com/zestedesavoir/zds-site/pull/3705) | [ci skip] Ajoute editorconfig | C-Back, C-Front, Facile, S-Évolution |
| [#3699](https://github.com/zestedesavoir/zds-site/pull/3699) | Affiche la liste des notifications. | S-Évolution |
| [#3697](https://github.com/zestedesavoir/zds-site/issues/3697) | Nouveau MP : « Un des participants saisi est introuvable » ← lequel ? | S-Évolution |
| [#3696](https://github.com/zestedesavoir/zds-site/pull/3696) | Amélioration de la page de maintenance sur mobile | S-Évolution |
| [#3671](https://github.com/zestedesavoir/zds-site/issues/3671) | Changer le nombre de contenus par page | C-Front, Facile, S-Évolution |
| [#3645](https://github.com/zestedesavoir/zds-site/issues/3645) | Supprimer les fonctions des tutoriels du SdZ | C-Back, Facile, S-Évolution |
| [#3509](https://github.com/zestedesavoir/zds-site/issues/3509) | Utiliser l'autocomplétion pour le champ des tags quand on édite/créé un contenu | C-Back, C-Front, S-Évolution |
| [#3472](https://github.com/zestedesavoir/zds-site/issues/3472) | Optimiser Travis | S-Évolution |

## Non défini

| Ticket # | Titre | Label(s) |
| --- | --- | --- |
| [#3786](https://github.com/zestedesavoir/zds-site/pull/3786) | Résout le bug de notification lors du déplacement de sujet |  |
| [#3781](https://github.com/zestedesavoir/zds-site/pull/3781) | (doc) Ajout des fichiers de configuration de production | C-Documentation, C-Infra |
| [#3769](https://github.com/zestedesavoir/zds-site/pull/3769) | Update config nginx subdomains | C-Infra, P-Haute |
| [#3768](https://github.com/zestedesavoir/zds-site/pull/3768) | Corrige le bouton Valider des modales de l'éditeur |  |
| [#3767](https://github.com/zestedesavoir/zds-site/pull/3767) | Masque la biographie des membres bannis définitivement |  |
| [#3761](https://github.com/zestedesavoir/zds-site/pull/3761) | #3620 Fix url images import |  |
| [#3756](https://github.com/zestedesavoir/zds-site/pull/3756) | Correction (orthographe) |  |
| [#3755](https://github.com/zestedesavoir/zds-site/pull/3755) | Invalide le cache de l'API à chaque entrée dans la base | C-API, P-Haute |
| [#3753](https://github.com/zestedesavoir/zds-site/pull/3753) | Ajout de sitemap pour /pages/ |  |
| [#3750](https://github.com/zestedesavoir/zds-site/pull/3750) | update markdown version |  |
| [#3731](https://github.com/zestedesavoir/zds-site/pull/3731) | [ci skip] Adapation aux nouveaux tags | C-Documentation, P-Bloquante |
| [#3726](https://github.com/zestedesavoir/zds-site/issues/3726) | Merge de la branche hotfix-v19 vers dev pas fait | P-Bloquante |
| [#3698](https://github.com/zestedesavoir/zds-site/issues/3698) | Les formules mathématiques ne fonctionnent pas sur les forums |  |
| [#3694](https://github.com/zestedesavoir/zds-site/pull/3694) | Permettre de suivre les contenus d'un membre |  |
| [#3693](https://github.com/zestedesavoir/zds-site/pull/3693) | Correction d'un lien mort dans la doc |  |
| [#3691](https://github.com/zestedesavoir/zds-site/pull/3691) | Optimise les tests |  |
| [#3669](https://github.com/zestedesavoir/zds-site/pull/3669) | Faute d'orthographe dans le README. |  |
| [#3651](https://github.com/zestedesavoir/zds-site/pull/3651) | Remplacement de l'adresse d'OVH par celle de Gandi |  |

**Comment by GerardPaligot** [comment]
A annoncer sur le forum [Dev Zone](https://zestedesavoir.com/forums/communaute/dev-zone/).

**Comment by vhf** [comment]
Bien vu, je cherchais la démarche mais je la trouvais pas. 👍
