### ISSUE TITLE
[beta][v20] Numéro de version manquant

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3788]
Serveur : Beta
Version : v20
Système : Mac OS X
Navigateur : 52.0.2743.116 (64-bit)

Rendez-vous sur la page d'accueil et constatez que le numéro de version est manquant dans le footer.

![capture d ecran 2016-08-23 a 21 02 04](https://cloud.githubusercontent.com/assets/1913901/17905877/17357b80-6975-11e6-9476-80e44910f0c2.png)

**Comment by vhf** [comment]
Yep, on était en detached head. `g co release-v20` et c'est bon.
