### ISSUE TITLE
[beta][v20] Aucun forum dans le menu de la topbar

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3790]
Serveur : Beta
Version : v20/6bb2f75
Système : Mac OS X
Navigateur : 52.0.2743.116 (64-bit)

---

Avec un utilisateur connecté ou non, regardez le menu de la topbar des forums :

![capture d ecran 2016-08-23 a 21 13 48](https://cloud.githubusercontent.com/assets/1913901/17906327/1a0a7da4-6977-11e6-8695-7836e4ee236f.png)

Vide.

**Comment by GerardPaligot** [comment]
La cause ici est le type des catégories que nous envoyons au template `cats = defaultdict(list)`. Impossible de savoir comment nous pouvons itérer sur un `defaultdict`.

**Comment by vhf** [comment]
Bien vu, merci @GerardPaligot, PR dans 2min c'est facile.
