### ISSUE TITLE
[beta][v20] Liste des notifications, template cassé

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3791]
Cf. ici : https://beta.zestedesavoir.com/notifications/ en comparaison à https://zestedesavoir.com/forums/notifications/ , on a un template bien cassé.

**Comment by GerardPaligot** [comment]
Le front a-t-il été généré ?

**Comment by vhf** [comment]
Ah non, bien vu !

**Comment by GerardPaligot** [comment]
Je ne connais pas le process de MEP/B mais à une époque, c'était automatique.

**Comment by vhf** [comment]
Justement moi non plus je le connais pas, et c'est pas documenté.

Effectivement lors d'une MEP c'est automatique, c'est travis qui build le front. Là je sais pas. Je regarde.

**Comment by Situphen** [comment]
Normalement lors de chaque création de "release" sur GitHub (exemple : "v19.1-mangoustan"), Travis build le front et le met à disposition dans un tag (exemple : "v19.1-mangoustan-build"). Le script de MEP/MEB s'occupe de récupérer le front depuis le dit tag. https://github.com/zestedesavoir/zds-site/blob/dev/scripts/deploy.sh#L47

**Comment by vhf** [comment]
Merci @Situphen . La doc de ZdS dit juste que pour une release, on créé une branche qu'on met en beta. Rien à propos des tags, du coup voilà.

@gustavi tu pourras documenter le processus de mise en beta ? Je me rappelle vaguement un gist que t'avais ?

**Comment by SpaceFox** [comment]
Vous avez déployé quoi ? Normalement le script de build était conçu pour ne déployer que des tags, et vérifier tout seul que le tag avec le build du front était bien là.

**Comment by vhf** [comment]
J'ai tenté de suivre [la doc](https://zds-site.readthedocs.io/fr/latest/workflow.html#workflow-de-mise-en-production), mais j'ai eu énormément de peine. Elle dit de faire une branche de release, du coup j'ai fait une branche de release et j'ai mis le site sur la branche.

Tagger le commit de release n'étant mentionné que dans la partie de mise en production et ne voulant pas foutre en l'air la branche prod du repo, j'ai pas taggé. Du coup le front manquait. Après moult galères on m'a fait remarquer les tags `-RC#`. Seulement après j'ai pu utiliser le script, et tout est rentré dans l'ordre.

**Comment by gustavi** [comment]
@vhf ce qui me sert de memo https://gist.github.com/gustavi/e18c6f1925bad9f2cca093ec44281540
