### ISSUE TITLE
[beta][v20] Impossible de masquer ses messages

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3792]
Serveur : Beta
Version : v20/6bb2f75
Système : Mac OS X
Navigateur : 52.0.2743.116 (64-bit)

---
1. Rendez-vous sur l'un de vos messages.
2. Remarquez qu'il n'est plus possible de le masquer.

**Comment by Karnaj** [comment]
En rajoutant `can_hide = message.is_visible` à [cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/templates/forum/topic/index.html#L115) ça devrait marcher, non ? Ou `can_hide = true` (mais selon moi `can_hide = message.is_visible` est mieux).

**Comment by vhf** [comment]
Y'a plus simple, faut revert 2-3 changements que j'ai faits. Je m'en occupe.

Faut surtout avoir une suite de tests qui tiennent debout, ce genre de régression devrait pas se produire avec des tests.
