### ISSUE TITLE
[beta][v20] La recherche ne renvoie pas des résultats pertinents

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3796]
Serveur : Beta
Version : v20/6bb2f75
Système : Mac OS X
Navigateur : 52.0.2743.116 (64-bit)

---
1. Rendez-vous sur cette recherche : https://beta.zestedesavoir.com/rechercher/?q=Android&models=tutorial
2. Constatez aucun tutoriel sur Android alors qu'il en existe bel et bien.

**Comment by gustavi** [comment]
2 options : 
- On a cassé la recherche dans le code
- On a casse Solr

**Comment by vhf** [comment]
Je pense plutôt que utf8mb4 demande une petite option à changer quelque
part dans la recherche ou l'indexation.

**Comment by DevHugo** [comment]
J'ai comme l'impression que les résultat ne sont pas pertinent enfait. Si on coche les 3 autres cases on tombe sur les tutoriels [Android](https://beta.zestedesavoir.com/rechercher/?q=Android&models=tutorial&models=parts&models=chapters&models=extracts) [Android php](https://beta.zestedesavoir.com/rechercher/?q=Android+PHP&models=parts&models=chapters&models=extracts).

**Comment by firm1** [comment]
Histoire de préciser un peu mieux cette issue, le problème ne survient que sur des **tutoriels qui n'ont pas de sous-titres** comme [lui](https://beta.zestedesavoir.com/tutoriels/624/creez-des-applications-pour-android/), [lui](https://beta.zestedesavoir.com/tutoriels/272/introduction-aux-tests-android-avec-espresso/), [lui](https://beta.zestedesavoir.com/tutoriels/260/les-operations-bit-a-bit-et-le-branch-free-code/) ou encore [lui](https://beta.zestedesavoir.com/tutoriels/609/aller-plus-loin-dans-le-developpement-android-1/).

En gros le passage à MySQL5.6 ou un script de migration des tables à du changer le comportement des `NULL` de MySQL. J'imagine que @DevHugo saura trouver ou est-ce que dans le code on peut isoler le problème.

**Comment by DevHugo** [comment]
Pour confirmer faudrait que quelqu'un passe la commande `python manage.py index_conten`et `python manage.py rebuild_index`pour qu'on puisse debugger.

**Comment by vhf** [comment]
On dirait que tes commandes on réglé le problème @DevHugo . Tu veux quand même l'output ?

**Comment by DevHugo** [comment]
J'ai toujours rien, sur la requête de Andr0, [sur la beta](https://beta.zestedesavoir.com/rechercher/?q=Android&models=tutorial) alors  [qu'en prod, on a des résultats](https://zestedesavoir.com/rechercher/?q=Android&models=tutorial), j'ai loupé quelque chose ?

Donne toujours les output si ça te demande aucun effort, sinon je regarderais demain, si je peux reproduire avec une instance locale.

**Comment by vhf** [comment]
Etrange, j'ai presque le même résultat beta et prod : http://imgur.com/a/BJJVi (beta, prod)

Voilà les logs @DevHugo https://gist.github.com/vhf/8dbdbbdcab2c1afe58a173cc32e19a32

**Comment by firm1** [comment]
J'ai le même résultat que @vhf sur la beta

Le mer. 24 août 2016 23:05, victor felder notifications@github.com a
écrit :

**Comment by DevHugo** [comment]
ça doit être mon cache navigateur alors. en tous les cas, merci vhf.

**Comment by GerardPaligot** [comment]
Tout est rentré dans l'ordre pour moi aussi.

**Comment by DevHugo** [comment]
Je l'ai aussi maintenant, je sais pas trop quoi dire. Les logs ont l'air normaux et je sais pas pourquoi il a fallut relancer la commande d'indexation des tutoriels.
