### ISSUE TITLE
[beta][v20] Pas de pluriel pour le compteur d'abonnés

### ISSUE THREAD

**Issue by Emeric54** [zestedesavoir/zds-site#3797]
En se rendant sur un forum ou un contenu avec plusieurs abonnés, constatez que le mot « abonné » n'est pas au pluriel.

**Comment by vhf** [comment]
Est-ce que tu peux expliquer en quelques points dans ton ticket comment résoudre le problème ? (C'est un prérequis pour appliquer le tag `Facile`. ;) )
