### ISSUE TITLE
Create robot.txt file for improve SEO

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#38]
ZDS n'a pas encore de fichier robot.txt, qui est pourtant très important pour diriger les crawler et améliorer ainsi notre référencement sur le web.

L'idée est de montrer aux bots tous les tutos publié, et les messages sur le forum.

S'il y'a des pros du SEO dans la salle, c'est le moment.

**Comment by SpaceFox** [comment]
Un sitemap.xml surtout.

**Comment by SpaceFox** [comment]
Le robots.txt de OCR est édifiant à ce point de vue...

Extrait :

> User-agent: Mediapartners-Google
> Allow: /membres
> Allow: /mp/

**Comment by SpaceFox** [comment]
J'ai une sitemap sur : 
- Tutos
- Articles
- Catégories
- Forums
- Topics

Vous voyez autre chose ?

D'autre part le robots.txt est sensé être un fichier statique pas fourni par Django, mais situé à la racine (pas dans /statics donc). On a un dossier pour mettre ce genre de fichiers ?

**Comment by firm1** [comment]
> Le robots.txt de OCR est édifiant à ce point de vue...

Lol.

> D'autre part le robots.txt est sensé être un fichier statique pas fourni par Django, mais situé à la racine (pas dans /statics donc). On a un dossier pour mettre ce genre de fichiers ?

C'est à paramétrer sur le serveur ça. Etant donné que nginx s'occupe de tout ce qui est static (css, js, images, etc.) je vais lui demander de servir aussi le robot.

**Comment by SpaceFox** [comment]
C'est corrigé, PR et mergé : je ferme.
