### ISSUE TITLE
Un membre avec un username en grec renvoie des erreurs 500

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3800]
Serveur : Prod
Version : v19.1-mangoustan/1b066e0
Système : Mac OS X
Navigateur : 52.0.2743.116 (64-bit)

---

Une erreur a été remontée dans Sentry :

``` console
NoReverseMatch: Reverse for 'member-detail' with arguments '()' and keyword arguments '{'user_name': u''}' not found. 1 pattern(s) tried: ['membres/voir/(?P<user_name>.+)/$']
(8 additional frame(s) were not displayed)
...
  File "zds/member/views.py", line 106, in dispatch
    return super(UpdateMember, self).dispatch(*args, **kwargs)
  File "zds/member/views.py", line 131, in post
    return self.form_valid(form)
  File "zds/member/views.py", line 140, in form_valid
    return redirect(self.get_success_url())
  File "zds/member/views.py", line 246, in get_success_url
    return profile.get_absolute_url()
  File "zds/member/models.py", line 111, in get_absolute_url
    return reverse('member-detail', kwargs={'user_name': self.user.username})
```

Contexte :

URL : https://zestedesavoir.com/membres/parametres/user/
Méthode : POST
Username : ρττ
Identifiant de l'utilisateur : 4095

Sachant que l'URL `https://zestedesavoir.com/membres/voir/ρττ/` ne renvoit vers rien (et forcément). Je me demande si le pseudo tout en lettre grec ne poserait pas problème pour la _slugification_. C'est assez ennuyant puisque le bug pourrait survenir chez beaucoup de monde et rend la navigation **bloquante** pour ces membres.

Je tag pas bloquant mais c'est chiant quand même pour eux.

**Comment by vhf** [comment]
Non non, le pseudo en lettre grecques passe très bien. @gustavi est dessus et aura un fix sous peu.

**Comment by GerardPaligot** [comment]
D'où venait le bug ?

**Comment by vhf** [comment]
Je peux t'expliquer sur IRC si tu veux. Sinon faudra attendre la PR. :)

**Comment by firm1** [comment]
AMHA on peut fermer cette issue.

**Comment by vhf** [comment]
Yep, je confirme.

Le problème était que rotautau s'était renommé en string vide. Du coup plein de trucs plantaient. Le validateur était mal foutu. #3809 a corrigé ce problème.
