### ISSUE TITLE
[beta][v20]Possibilité d'éditer un message masqué

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#3804]
_A vérifier_

Il semble que sur le forum, on puisse éditer un message, qui a été masqué, en utilisant le lien direct vers l'édition du message.

`https://zestedesavoir.com/forums/message/editer/?message=******`

**Comment by GerardPaligot** [comment]
Quelle est la procédure pour reproduire ce comportement ?

D'après le code, il y a bien la protection qui oblige d'être l'auteur du message et de faire sa requête en `POST`.

**Comment by vhf** [comment]
@GerardPaligot on va tester ça sur la beta, perso ça m'étonnerait aussi mais comme dit @A-312 c'est à vérifier, il croit avoir observé ça mais n'est pas sûr. Dès que je déploie le hotfix qui re-permet de masquer les messages, on teste.

**Comment by vhf** [comment]
@A-312 peux-tu stp essayer ce lien, qui permet d'éditer un message que t'as écrit et que j'ai masqué : https://beta.zestedesavoir.com/forums/message/editer/?message=120899

Si tu peux pas, on peut fermer ce ticket.

**Comment by GerardPaligot** [comment]
@vhf Moi en tout cas, je ne peux pas.

**Comment by gustavi** [comment]
Un staff peut mais c'est normal non ?

**Comment by Karnaj** [comment]
J’ai essayé [ici](https://beta.zestedesavoir.com/forums/sujet/6770/test/?page=1#p120890), j’arrive à accéder au lien, et j’ai réussi à éditer mon message.

**Comment by A-312** [comment]
Je pense avoir réussi

**Comment by Karnaj** [comment]
Lorsqu’on masque le premier message d’un topic, on peut aussi l’éditer grâce au bouton « Éditer le sujet ».
