### ISSUE TITLE
Connexion via réseaux sociaux

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#381]
Avec l'arrivée de choses telles que la connexion anonyme de Facebook, est-ce qu'il ne faudrait pas penser à l'implémenter par la suite ?

C'est une suggestion d'un testeur en privé.

**Comment by SpaceFox** [comment]
Je sais pas. Sur OCR, on a commencé à voir les problèmes que ce genre d'outil peut soulever :
- Comptes à moitié remplis
- Accès irrécupérables quand le compte source est perdu ou supprimé

Plus bien sûr, le fait qu'on aie aucune garantie que le service soit pérenne.

**Comment by Alex-D** [comment]
Est-ce qu'on ne pourrait alors pas permettre de lier un réel compte à un tel système pour obtenir une connexion "one-click" ?

**Comment by SpaceFox** [comment]
Ça me paraît déjà plus propre.
Après, tout ça n'est que mon avis.
