### ISSUE TITLE
Impossibilité de s'abonner par mail à un contenu

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3811]
@GerardPaligot normal ça ?

**Comment by GerardPaligot** [comment]
Ca n'a jamais été possible. C'est une évolution.

**Comment by FanJiyong** [comment]
Salut, 

1. Etre notifier de quoi ? des nouveautés sur un contenu ?
2. Ok, réutiliser l'iconographie de l'enveloppe qu'on utilise déjà sur le forum. 
3. Est-ce qu'on aurait pas tendance a faire ça aussi pour les "catégories" et les "tags" ?

**Comment by EGabbro** [comment]
Salut,
Pour être train de (finir) d'implémenter ça, je peux répondre.
Un peu partout, il y a deux boutons de suivi : suivre et suivre par mail. Mais pas sur les contenus (seulement "suivre"), ce ticket a donc pour but d'homogénéiser la situation. ;)
On sera notifié des nouveaux commentaires sur le contenus (pas du reste, je crois ; le comportement sera le même que le suivi par notification, mais par mail) ; l'icône (et le gros du code) est commun avec le suivi par mail des membres et des sujets.
Pour les catégories et tag, pourquoi pas, mais c'est je pense un autre problème : il n'est pas possible de suivre cela du tout actuellement ; là, on peut suivre, mais pas par courriel.
Gabbro.

**Comment by FanJiyong** [comment]
Salut, 

Ouais c'est ce que j'ai vu aussi. Que du suivi des nouveaux commentaire pas du contenu ? C'est ce que fait le premier lien ? 

> (pas du reste, je crois ; le comportement sera le même que le suivi par notification, mais par mail)
J'aimerais qu'on soit 100% de la fonctionnalité histoire d'être sur du terme qu'on utilise, afin que ça ne soit pas trompeur pour l'utilisateur.

Sur le forum ça me semble limpide, mais ici pour du contenu beaucoup moins.  

> Pour les catégories et tag, pourquoi pas, mais c'est je pense un autre problème : il n'est pas possible de suivre cela du tout actuellement ; là, on peut suivre, mais pas par courriel. 

Tu as raison ! On verra ça dans une autre évolution.

**Comment by Anto59290** [comment]
Pour le suivi des tags c'est note ici : #1264

**Comment by FanJiyong** [comment]
Yop yop, 

ça va dans le même sens : 
https://zestedesavoir.com/forums/sujet/7464/sabonner-aux-mises-a-jour-dun-tuto/

Du coup ça me conforte dans l'idée qu'il faut faire évoluer cette fonctionnalité et permettre aux personnes qui le souhaite, de suivre discussion et évolution d'un contenu (Mise a jour, Ajout etc.). 

- Soit dans un premier temps on fait un bouton qui permet de suivre discussion et évolution d'un contenus et attendre des retours utilisateurs pour effectuer des changements. 

- Soit on part directement dans une solution où il est possible de suivre soit discussion, soit l'évolution, soit les deux.

**Comment by pierre-24** [comment]
Et voilà qui est fait, merci @EGabbro !
