### ISSUE TITLE
[beta][v20] Les forums dans la topbar ne semblent pas triés comme prévu

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3812]
L'affichage des forums dans la sidebar est censé être régie par un paramètre position stocké dans la base. Sur la beta la catégorie communauté apparait avant la catégorie savoir, ça ne me semble pas normal.

**Comment by vhf** [comment]
Tu parles bien de l'ordre des catégories dans la topbar, pas de l'ordre des forums, c'est ça ?

Si oui j'observe comme toi la différence entre la beta la prod. Par contre j'ai pas trouvé dans le code où cet ordre (`Category.position`) était utilisé. Je veux bien que quelqu'un retrouve le code en question, sinon c'est pas une régression.

On peut implémenter ça, c'est juste que j'ai pas l'impression que c'était prévu comme ça. Avant on créait un `dict(category: [forums])`, maintenant on créé le même `dict` en passant par un `defaultDict`. Dans le traitement y'a pas de différence, au final dans les 2 cas on passe un `dict` au template, et un `dict` ne préserve pas l'ordre des clés. Du coup si quelqu'un avait prévu d'afficher les catégories dans la topbar en se basant sur `Category.position`, je pense que ça a jamais été implémenté.

**Comment by firm1** [comment]
> Tu parles bien de l'ordre des catégories dans la topbar, pas de l'ordre des forums, c'est ça ?

Yep c'est bien ça.

> Du coup si quelqu'un avait prévu d'afficher les catégories dans la topbar en se basant sur Category.position, je pense que ça a jamais été implémenté.

Je me souviens d'une PR qui implémentait ce fonctionnement justement, mais elle doit dater de 2015. Mais je peux t'assurer que c'était voulu

**Comment by vhf** [comment]
D'accord. En tout cas ça fait des lustres que c'est plus dans le code. Ou alors c'était pas implémenté correctement dans la PR initiale. J'ai pas trouvé de trace de ça en tout cas. Je prépare une PR.
