### ISSUE TITLE
[beta][v20] Un membre ne peut pas voir ses propres abonnés

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3813]
Serveur : Beta
Version : v20-RC2/99bee1d
Système : Mac OS X
Navigateur : 52.0.2743.116 (64-bit)

---
1. Connectez-vous et rendez-vous sur votre profil.
2. Constatez que vous pouvez pas voir le nombre de personne qui sont abonnés à votre actualité.

Reporté depuis ZdS : https://zestedesavoir.com/forums/sujet/6789/la-v20-mesdames-messieurs-attention-les-velos/?page=1#p121800

**Comment by gustavi** [comment]
Note : je n'ai pas ce problème en étant Staff

**Comment by vhf** [comment]
Effectivement en Staff je peux voir, par contre je trouve pas très cool l'affichage. C'est sous "Actions" alors que c'est pas actionnable, et c'est "Il y a" alors que ça pourrait être "Vous avez".

<img width="296" alt="screen shot 2016-08-27 at 16 53 31" src="https://cloud.githubusercontent.com/assets/2022803/18028144/ec9c8e86-6c76-11e6-8201-989ca25db00e.png">

**Comment by Karnaj** [comment]
Si on ne peut voir que le nombre d’abonnés des autres (à moins d’être staff), c’est parce qu’on utilise le template qui s’en occupe dans [cette condition](https://github.com/zestedesavoir/zds-site/blob/dev/templates/member/profile.html#L197).
