### ISSUE TITLE
Des boutons de la sidebar peuvent se superposer

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3817]
Lorsque vous êtes sur un format d'appareil assez petit (tablette en mode paysage), les boutons avec un long titre n'applique pas une ellipse mais se place sur la ligne du dessous, donc sur le bouton en dessous.

Il faudrait donc les soumettre à une règle qui ajoute "...".

![capture d ecran 2016-08-28 a 09 23 55](https://cloud.githubusercontent.com/assets/1913901/18032405/0ea1047a-6d04-11e6-8d51-7f9a736f9728.png)

**Comment by Situphen** [comment]
Alors ce qui se fait actuellement c'est utiliser les classes `.wide` et `.screen` ([ici](https://github.com/zestedesavoir/zds-site/blob/dev/assets/scss/base/_helpers.scss#L70)) pour cacher une partie du texte sur mobile.

Par exemple, sur le profil des membres il y a `Paramètres <span class="wide">de mon compte</span>` ce qui donne "Paramètres de mon compte" en grand écran et "Paramètres" sur les plus petits écrans.

**Comment by Emeric54** [comment]
C'est corrigé. Merci @pierre-24 et @Situphen !
