### ISSUE TITLE
Optimiser le format de la date sur la page d'accueil pour les mobiles

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3820]
Sur la page d'accueil, sur un mobile (testé avec un Samsung Galaxy S5 mini), la date des contenus (tutoriels et articles) prend énormément de place ce qui cache des informations comme le montre ce _screen_ http://i.imgur.com/DMP6IqS.png.

Il faut l'optimiser avec une date spécifique pour mobile et le template filter date de Django. JJ/MM/AA àHHhMM me semble un bon format (voir ce qui est utilisé pour les forums sur cette même page).

**Comment by AmarOk1412** [comment]
Surtout qu'en plus les derniers sujets sont bien gérés avec le `format_date:True`

**Comment by Emeric54** [comment]
Merci @Anto59290 !
