### ISSUE TITLE
Proposer des sujets similaires au visiteur

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3824]
Salut,

Quand je lis un sujet sur ZdS, je suis obligé de revenir sur la liste des forums pour trouver quelque chose d'autre à lire. Sur StackOverflow par exemple, on a un petit truc sur le côté qui nous permet de lire d'autres sujets en lien avec celui qu'on était en train de lire. Ça permet de découvrir des choses si on est juste là pour visiter, ou bien trouver plus de réponses si on cherche à résoudre un problème.

Les sujets proposés seront juste les — disons — 10 premiers résultat d'une recherche avec les mêmes tags que le sujet en cours de lecture.

Voilà pour moi ça serait une feature utile, au moins pour les suggestions de sujets, dites-moi ce que vous en pensez.

Sujet: https://zestedesavoir.com/forums/sujet/6811/proposer-des-sujets-similaires-au-visiteur/
_Envoyé depuis Zeste de Savoir_

**Comment by GerardPaligot** [comment]
Je sens que je vais adorer cette fonctionnalité ! <3 (l'envoi de ticket depuis ZdS)

**Comment by pierre-24** [comment]
C'est typiquement [lié à ça](https://zestedesavoir.com/forums/sujet/1082/zep-15-navigation-a-facettes-a-travers-le-site/) ;)

**Comment by pierre-24** [comment]
L'histoire de faire avancer le machin, je dirais que si ma PR sur elasticsearch passe, ce ne sera plus qu'une question de quelques dizaines de lignes à taper, les recherches à facettes étant [déjà disponibles](http://elasticsearch-dsl.readthedocs.io/en/latest/faceted_search.html) (encore que j'ai pas compris ou ils voulaient en venir).

**Comment by A-312** [comment]
[Ici](https://github.com/zestedesavoir/zds-site/pull/2318) la recherche de sujet similaire à la création du sujet semblait être problématique.

**Comment by pierre-24** [comment]
Oui, mais avec ES, y'a moyen de faire des trucs "plus proprement", à priori :)

**Comment by AmarOk1412** [comment]
Je remonte. @artragis tu peux m'assigner ça ?

**Comment by artragis** [comment]
C'est implémenté

**Comment by A-312** [comment]
@artragis ce n'était pas à la création mais à la lecture

**Comment by artragis** [comment]
Je clos pour deux raisons:

- on n'est pas prêt d'implémenter ça
- on se concentre sur les tutos/articles, qui eux, ont une features de suggestions
