### ISSUE TITLE
Empêcher de up/downvoter des messages masqués

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3825]
Pouvoir voter des messages masqués n'a aucun intérêt.

**Comment by Karnaj** [comment]
C’est déjà en place en bêta (par exemple [ce message](https://beta.zestedesavoir.com/forums/sujet/6769/test-sur-tag/#p120899)). Par contre, il faudrait enlever le bouton « Signaler ».

**Comment by vhf** [comment]
Cool, super, merci !

Pour le 'signaler', cf. #3649 ;)
