### ISSUE TITLE
[Membre] Déconnexion, faille CSRF

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#383]
La déconnexion s'effectue via un simple lien. Une image ayant l'url de déconnexion insérée n'importe où dans le site déconnectera tous ceux qui passeraient par là.

Ca peut être problématique sur un topic à modérer...

**Comment by SpaceFox** [comment]
Serait-il possible d'avoir un **bouton de formulaire** à la place d'un lien pour la déconnexion ? (quelqu'en soit l'aspect)

Pourquoi ?
Parce que l'action HTTP GET est sensé être "sure", donc ne pas provoquer d'effet de bord.
C'est tellement vrai que Django refuse de proposer sa protection anti-CSRF sur des actions GET : https://docs.djangoproject.com/en/1.6/ref/contrib/csrf/ (ce en quoi je suis parfaitement d'accord avec eux : ça poserait plus de problèmes que ça n'en résoudrait).

Il faudrait donc transformer le lien de déconnexion en "bouton de déconnexion dans un formulaire envoyé via POST" et aussi **s'assurer que l'action de déconnexion ne répond pas au GET**.
Github fait exactement ça, si quelqu'un veut un exemple d'implémentation.

S'il le faut, je peux faire tout ce ticket sauf le design.

**Comment by Alex-D** [comment]
le design n'est pas ouf, faut juste remplacer le lien par un bouton en clair non ?

**Comment by SpaceFox** [comment]
Je sais pas à quel point ça peut exploser le truc en fait :D
Et comme je ne pige absolument rien au design de ce site... (l'autre jour
j'ai voulu faire une modif CSS, j'ai pas réussi).

2014-05-01 23:11 GMT+02:00 DEMODE Alexandre notifications@github.com:

**Comment by Alex-D** [comment]
Au pire, fais une branche, gère la déco proprement, on verra pour faire le design après ;)
Au pire encore, s'il faut attendre mon design c'est pas très grave.

**Comment by SpaceFox** [comment]
Bon je pars là-dessus.

**Comment by SpaceFox** [comment]
À toi de jouer @Alex-D : sur la branche issue_383_csrf_deco

**Comment by Alex-D** [comment]
Je te laisser tester et merger.

**Comment by SpaceFox** [comment]
OK, je finis mon bug et je regarde ça.

2014-05-02 0:37 GMT+02:00 DEMODE Alexandre notifications@github.com:

**Comment by SpaceFox** [comment]
Done.
