### ISSUE TITLE
[beta][v20] Erreur 500 lors de l'inscription avec un pseudo contenant un emoji

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3831]
Procédure de reproduction : 
- Aller sur [la page d'inscription](https://beta.zestedesavoir.com/membres/inscription/)
- saisir comme pseudo : 👉👉👉👉👉
- remplir les autres champs de manière normale
- cliquer sur "Valider mon inscription"

S'apercevoir qu'on a une erreur 500.

On peut se poser la question de la pertinence d'un emoji dans le pseudo, mais on a pas le droit de renvoyer une erreur 500 pour autant.

**Comment by SpaceFox** [comment]
Il faudrait aussi tester le cas des emojis dans le mot de passe.

**Comment by GerardPaligot** [comment]
L'erreur remontée depuis Sentry est la suivante :

``` console
OperationalError: (1267, "Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='")
(20 additional frame(s) were not displayed)
...
  File "zds/utils/decorators.py", line 16, in _https_required
    return func(request, *args, **kwargs)
  File "zds/member/views.py", line 259, in dispatch
    return super(RegisterView, self).dispatch(*args, **kwargs)
  File "zds/member/views.py", line 270, in post
    if form.is_valid():
  File "zds/member/forms.py", line 168, in clean
    self.validate_username(username)
  File "zds/member/validators.py", line 32, in validate_username
    elif User.objects.filter(username=value).count() > 0:
```

**Comment by vhf** [comment]
Yep, tout ceci est déjà corrigé ici : #3809 

QA bienvenue. :) [edit]En fait pas besoin de QA cette PR avant que @gustavi prenne en compte les commentaires qui y sont.[/edit]

On a décidé de pas autoriser l'utf8mb4 dans les pseudos et les mots de passe (et tous les autres champs stockés dans `auth_user`). La PR en question valide ceci.
