### ISSUE TITLE
Intégrer le module Nginx PageSpeed de Google ?

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3834]
Je ne sais pas si c'est vraiment une bonne idée, je signale surtout qu'il existe : https://developers.google.com/speed/pagespeed/

**Comment by gustavi** [comment]
Pas d'avis spécial là dessus.

En tous cas c'est exactement ce dont j'avais besoin pour un autre projet donc merci @SpaceFox :)

**Comment by sandhose** [comment]
Pour l'avoir testé il y a quelque temps, ça me paraît plus une excuse pour ne pas faire attention aux perfs en utilisant ce module. En gros, ça convertit toutes les images en webm à la bonne taille pour les navigateurs qui le supporte, minifie HTML/CSS/JS (déjà fait dans notre cas), plus 2/3 autres opti très mineures. Je pense que nos plus gros problème niveau taille des pages, c'est les images insérées par les utilisateurs où l'on ne contrôle pas la taille, comme par exemple les avatars, les images insérées dans le forum, et les unes. Dans ces trois cas, pagespeed ne servira à rien, puisqu'il ne réécrit pas les images externes. 

Ça servirait éventuellement pour les images insérées dans le forum depuis une galerie sans utiliser une thumbnail, mais je pense que ça devrait être quelque chose qu'on gère nous-même, un peu comme github le fait (une image externe dans un commentaire GH est uploadée sur le cdn de github, resizé au passage, et c'est l'image redimensionnée qui est affichée, avec un lien vers l'image full-size).

**Comment by SpaceFox** [comment]
Si on met cet outil en place, il faut faire gaffe à ce que l'URL `/mod_pagespeed_statistics` ne soit **pas** accessible au public.

**Comment by artragis** [comment]
ping @sandhose comme tu es master of infra, peux-tu prendre une décision qu'on voit s'il faut clore le ticket?
