### ISSUE TITLE
Bar d'outils de l'éditeur dédoublée

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3835]
> Lorsque je fais une nouvelle ligne et je colle tu texte dans n'importe quelle zone de texte sur le site (commentaire, tuto, nouveau sujet etc.) la barre d'outil est doublé et ça peut devenir embêtant :
> 
> Si on fait 5-6 copier coller, on se retrouve avec une page entièrement remplie d'outils entre le texte et le titre.
> 
> ![error double outil](https://zestedesavoir.com/media/galleries/3179/fbccf2fa-99a1-4dcd-b92a-d9881a757ab4.png)
> 
> PS:je suis sous safari version 9.13 et je n'ai pas réussi à reproduire le bug dans d'autres navigateur

Source:[d3m0t3p](https://zestedesavoir.com/forums/sujet/6883/bar-doutils-dedoublee/?page=1#p123127)

**Comment by WinXaito** [comment]
N'avais-tu pas déjà eu ce soucis avec chrome ? Je me rappelle avoir vu une issue de toi sur le même sujet.

Edit: Non en fait c'était le bouton [Aide markdown] qui se dédoublais (Et qui d'ailleurs est toujours open). C'est probablement lié https://github.com/zestedesavoir/zds-site/issues/3354

**Comment by GerardPaligot** [comment]
@WinXaito Tu ne rêves pas. J'avais reporté le bug sur [ZdS](https://zestedesavoir.com/forums/sujet/1406/modification-de-lediteur-avec-des-copiercoller/) et une [PR](https://github.com/zestedesavoir/zds-site/pull/2055) avait été faite par @Situphen.

**Comment by Situphen** [comment]
Diantre, j'ai bêtement [remplacé l'ancien code par le nouveau de Thunderseb](https://github.com/zestedesavoir/zds-site/pull/3238/files#diff-ac76f1d75eb777f747e6708b19d31b78L111) sans faire attention et j'ai donc enlevé le bug que [j'avais moi-même corrigé](https://github.com/zestedesavoir/zds-site/pull/2055/files) ! Je fais une PR pour corriger ça !

**Comment by vhf** [comment]
Cf. #3861
