### ISSUE TITLE
[beta][v20] S'inscrire/se connecter/chercher avec un emoji provoque une 500

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3836]
Serveur : Beta
Version : v20-RC3/d3fd8af
Système : Mac OS X
Navigateur : 52.0.2743.116 (64-bit)

---
1. Rendez-vous à la page d'inscription et renseigner un pseudo du type : 👚 test
2. Remplissez les autres champs.
3. Soumettez le formulaire.
4. Constatez une erreur 500.

Note : Vous pouvez reproduire la même erreur en tentant de vous connecter avec le même pseudo ou en faisant une recherche sur le pseudo d'un membre.

**Comment by firm1** [comment]
On aurait pu ré-ouvrir celle-ci #3831 . Mais oui je confirme que le bug n'est pas corrigé.

**Comment by GerardPaligot** [comment]
Bien vu, j'avais zappé ton issue. Sorry.

**Comment by vhf** [comment]
Ça me surprend. @gustavi t'as une idée du pourquoi ?

J'ai jeté un oeil et le champ username de RegisterForm doit passer par validate_zds_username qui doit refuser les emojis...

**Comment by GerardPaligot** [comment]
Pour information, la recherche d'un membre provoque aussi une 500.

Scénario :
1. Rendez-vous sur un MP.
2. Cliquez pour ajouter un membre.
3. Recherchez avec un emoji (🐙 par exemple)
4. Soumettez et constatez la 500.

Erreurs :

``` console
OperationalError: (1267, "Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='")
(19 additional frame(s) were not displayed)
...
  File "zds/mp/views.py", line 172, in dispatch
    return super(PrivateTopicAddParticipant, self).dispatch(request, *args, **kwargs)
  File "zds/mp/views.py", line 184, in post
    participant = get_object_or_404(Profile, user__username=request.POST.get('username'))
```

``` console
OperationalError: (1267, "Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation 'like'")
(23 additional frame(s) were not displayed)
...
  File "rest_framework_extensions/cache/decorators.py", line 62, in process_cache_response
    response = view_method(view_instance, request, *args, **kwargs)
  File "zds/member/api/views.py", line 101, in get
    return self.list(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 42, in list
    page = self.paginate_queryset(queryset)
  File "rest_framework/generics.py", line 172, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "rest_framework/pagination.py", line 206, in paginate_queryset
    self.page = paginator.page(page_number)
```

Premier message de l'issue édité.

**Comment by vhf** [comment]
Ce qui m'embête le plus c'est qu'on a un test pour ça : https://github.com/zestedesavoir/zds-site/pull/3809/commits/478ee609b38480efc20b87414322043546163d97 et il passe.

**Comment by vhf** [comment]
Je pense qu'on a besoin d'yeux supplémentaires ici. On a un test, il est bon, il passe, mais sur la beta ça passe pas. Et je sais pas pourquoi.

Je vais mettre le tag bloquant, parce que faire une RC avec ce bug n'a pas de sens.

**Comment by GerardPaligot** [comment]
Tu sais donner un pointeur vers le test ?

**Comment by vhf** [comment]
Ici : https://github.com/zestedesavoir/zds-site/issues/3836#issuecomment-246980773

**Comment by vhf** [comment]
Toujours pas bon. Il va falloir ajouter le test ailleurs.

**Comment by GerardPaligot** [comment]
Si tu fais pas un reset de la base, ça me semble normal. Ta PR permettait simplement de ne pas pouvoir s'inscrire avec des emojis (faut ajouter le check dans le rename de son pseudo d'ailleurs) mais s'il y a déjà des emojis dans les pseudos, les requêtes font forcément cracher en rencontrant les emojis.

**Comment by vhf** [comment]
C'est pas ça @GerardPaligot . Il manque plein de validation et de nettoyage à plein d'endroits. A d'autres la logique est pas correcte. Un reset de la base ne sert à rien puisqu'il n'est pas possible que la table auth_user contienne de l'utf8mb4, sa collation étant utf8.

Regarde ici : https://github.com/zestedesavoir/zds-site/blame/release-v20/zds/member/validators.py#L89

Ça empêche correctement de s'inscrire avec un pseudo utf8mb4. Mais 5 lignes plus haut il y a une requête qui va provoquer une erreur 500.

Idem dans l'API des membres. Il faut trouver un moyen de ne pas passer l'utf8mb4 à MySQL, sinon par exemple [ici](https://github.com/zestedesavoir/zds-site/blame/release-v20/zds/member/api/views.py#L101) ça va planter. Et là j'ai besoin de ton aide.

**Comment by SpaceFox** [comment]
Il me semblait qu'on avait moyen de faire comprendre l'utf8mb4 à MySQL
maintenant ?

Le 19 octobre 2016 à 15:22, victor felder notifications@github.com a
écrit :

**Comment by vhf** [comment]
Oui SpaceFox, c'est tout à fait ça. Mais par sécurité (car cette table est gérée par django) et parce qu'on compte pas autoriser les pseudo utf8mb4, on a décidé de laisser `auth_user` en `utf8` au lieu de la passer à la moulinette. C'est une vieille décision, et je crois qu'elle ne se justifie plus, tout du moins elle ne justifie pas les ennuis à répétition qu'elle nous cause. J'ai d'ailleurs depuis découvert que les gens qui ont décidé d'utiliser django avec un mysql tout-utf8mb4 n'avaient aucun souci avec cette table. Et nos tests passent sur travis sur une DB MySQL 5.6 entièrement créée en utf8mb4.

Je reviens en arrière. PR dans 30 secondes.

**Comment by vhf** [comment]
Et ça fonctionne. Parfait. Et on n'a pas besoin d'y ajouter une RC.

<img width="504" alt="screen shot 2016-10-19 at 15 38 42" src="https://cloud.githubusercontent.com/assets/2022803/19520941/38e205ea-9612-11e6-86cf-e9d3bbd3aa13.png">

QA super facile sur la bêta, instructions : https://github.com/zestedesavoir/zds-site/pull/3874
