### ISSUE TITLE
gandi.zestedesavoir.com est indexé par Google

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3837]
Je ne sais pas comment ni pourquoi, ni ce qu'on peut faire pour l'interdire.

Pire : ça tombe sur une erreur HTTPS (forcément).

Il me semblait avoir signalé un problème de ce tonneau, mais je ne le retrouve pas et ce n'est pas corrigé.

PS : comment reproduire ? Faites une recherche dont vous êtes à peu près sûr qu'elle tombera sur ZdS, et observez.

**Comment by vhf** [comment]
C'était corrigé, oui, comme en atteste la config nginx `prod_redirect` visible ici : https://zds-site.readthedocs.io/fr/latest/install/deploy-in-production.html.

Le problème c'est que cette redirection marchait très bien tant que le certif était valide. Aussi, Google est censé prendre en compte cette redirection et virer les URLs d'origine de son index. Par contre là il peut plus vu que le certif qu'on avait a expiré, et qu'en créant un nouveau certif personne a pensé qu'on aurait besoin de certifs autres que pour zestedesavoir.com.

Du coup pour corriger c'est simple, faut créer des certifs pour tous les domaines du prod_redirect et attendre que google fasse son travail. Ces redirections marchent bien d'ailleurs.

**Comment by vhf** [comment]
Voilà.

**Comment by vhf** [comment]
Le ticket auquel tu pensais était celui-ci : #3764

**Comment by SpaceFox** [comment]
Ha, c'était pas le même sous-domaine. Merci !

**Comment by vhf** [comment]
Yep, c'était un autre, mais ils avaient tous été corrigés en même temps y'a un mois. Et ça a bien fonctionné jusqu'à cette histoire de certificat qui a échu.
