### ISSUE TITLE
[beta] Le fichiers robots.txt n'est pas accessible

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3840]
Rendez-vous sur l'url : http://beta.zestedesavoir.com/robots.txt , on obtient un 404. Alors qu'en production, l'url http://zestedesavoir.com/robots.txt est bien accessible.

**Comment by gustavi** [comment]
C'est corrigé, je ne sais pas d'où ça venait, probablement lorsque le venv de la beta a été refait.
