### ISSUE TITLE
[beta] réserver un contenu m'envoi un MP, mais je ne reçoit pas d'alertes

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3842]
Scénario : 
- Je vais dans la liste des contenu en validation
- Je réserver un tutoriel
- On peut remarquer que d'après la topbar, je n'ai aucun message "non-lu" dans ma messagerie
- Si je clique sur "Toutes les conversations" je m'aperçois que j'ai une conversation crée, et non lue.

Le comportement n'est donc pas cohérent. Réserver le contenu devrait me générer une notification ou si la notification n'est pas générée, la conversation devraient être marquée comme lue. Il ne faudrait pas un comportement à mis chemin entre les deux.

**Comment by GerardPaligot** [comment]
C'est bizarre parce que ce test passe :

``` python
# reserve the article
validation = Validation.objects.filter(content=article).last()
result = self.client.post(
    reverse('validation:reserve', kwargs={'pk': validation.pk}),
    {
        'version': validation.version
    },
    follow=False)
self.assertEqual(result.status_code, 302)

# Check that the staff haven't a notification for its reservation and the private topic should be read.
self.assertEqual(0, len(Notification.objects.get_unread_notifications_of(self.user_staff)))
last_pm = PrivateTopic.objects.get_private_topics_of_user(self.user_staff.pk).last()
self.assertTrue(never_privateread(last_pm, self.user_staff))
```

La méthode `never_privateread` est très mal nommée mais elle vérifie qu'un MP a été lu depuis le dernier message posté.

**Comment by pierre-24** [comment]
Bon, il reste ça. 

Basiquement, je confirme:

![screenshot from 2016-10-20 08 20 20](https://cloud.githubusercontent.com/assets/7889675/19548312/16013d2a-969e-11e6-9826-062a92b9691f.png)

(j'ai même pas eu la notif pour le MP de base des fixtures "comment devenir staff", c'est pour dire)

**Comment by pierre-24** [comment]
Par contre, ça marche quand on s'envois des MPs, et l'auteur dont le tuto a été réservé a bien la notif. C'est pas simplement une option quelque part qui désactive la notif pour l'auteur du MP, une connerie du genre?

**Comment by GerardPaligot** [comment]
@pierre-24 Le bug ne se situe pas forcément sur l'absence de notifications. Soit nous générons une notification pour l'auteur et le(s) autre(s) personne(s) concernée(s), soit nous ne générons pas de notification et nous marquons la conversation privée comme lue.

Mon test était censé démontrer que le second cas était déjà le cas mais, vu ta QA et celle de firm1, mon test ne doit pas être correct puisque la conversation privée est belle et bien marquée comme non lue.

> (j'ai même pas eu la notif pour le MP de base des fixtures "comment devenir staff", c'est pour dire)

Ca c'est normal. Les signaux n'interceptent pas les fixtures basiques.

**Comment by pierre-24** [comment]
> Ca c'est normal. Les signaux n'interceptent pas les fixtures basiques.

Oui, c'est ce que je me suis dit par après :-)

**Comment by pierre-24** [comment]
arrêtez moi si je me trompe, mais donc on a ceci

```
    return PrivateTopicRead.objects \
        .filter(privatepost=privatetopic.last_message, privatetopic=privatetopic, user=user) \
        .count() == 0
```

Dans [`never_privateread`](https://github.com/zestedesavoir/zds-site/blob/release-v20/zds/mp/models.py#L325-L327). Or, il se trouve que quand je regarde dans l'admin, j'ai pas de `PrivateTopicRead` associé à ces MP de réservation. Donc ça explique que ces messages soient affichés comme non-lu. Et aussi que le test pointé par @GerardPaligot passe. 

Or, à priori, [`send_mp()`](https://github.com/zestedesavoir/zds-site/blob/release-v20/zds/utils/mps.py#L14) ne fait rien pour faire apparaître ces `PrivateTopicRead`. On considère juste qu'en procédure classique d'un envoi de MP, l'auteur sera redirigé vers le MP, ce qui générera le _read_ de toute façon. Donc comme ça a été conçu, on devrait avoir la notification. Et là, on se "perd" dans le module des notifs, que je connais pas du tout :/

**Comment by pierre-24** [comment]
(mais à priori, on [rentre par ici](https://github.com/zestedesavoir/zds-site/blob/release-v20/zds/notification/receivers.py#L240))

**Comment by pierre-24** [comment]
Et du coup, à priori, ça coince [là](https://github.com/zestedesavoir/zds-site/blob/release-v20/zds/notification/receivers.py#L261) : 

``` py
    subscription_list = PrivateTopicAnswerSubscription.objects.get_subscriptions(post.privatetopic)
    for subscription in subscription_list:
        if subscription.user != post.author:
            send_email = by_email and (subscription.user.profile.email_for_answer or post.position_in_topic == 1)
            subscription.send_notification(content=post, sender=post.author, send_email=send_email)

```

Et plus particulièrement sur la ligne `if subscription.user != post.author:`. Si je pige bien, l'auteur ne recoit pas ses propres notifs, ce qui est logique normalement, mais pas ici.

**Comment by GerardPaligot** [comment]
Tu as tout super bien compris. Pour moi, le receiver ne doit pas être modifié parce que dans tous les autres cas, on ne doit pas notifier l'auteur et raison pour laquelle, je pense qu'on doit faire en sorte que la conversation soit lue et pas générer une notif. (:

**Comment by GerardPaligot** [comment]
Et bien vu pour le test, je suppose qu'il suffirait de le modifier dans ce sens alors :

``` python
# reserve the article
validation = Validation.objects.filter(content=article).last()
result = self.client.post(
    reverse('validation:reserve', kwargs={'pk': validation.pk}),
    {
        'version': validation.version
    },
    follow=False)
self.assertEqual(result.status_code, 302)

# Check that the staff haven't a notification for its reservation and the private topic should be read.
self.assertEqual(0, len(Notification.objects.get_unread_notifications_of(self.user_staff)))
last_pm = PrivateTopic.objects.get_private_topics_of_user(self.user_staff.pk).last()
# PrivateTopicRead.objects.filter(...).count() doit être différent de 0
self.assertFalse(never_privateread(last_pm, self.user_staff))
```

**Comment by pierre-24** [comment]
C'est ce que je me disais aussi. Maintenant, est ce que je gère ça dans `send_mp()` (limite en rajoutant un paramètre optionnel à `False` pour rien casser) ou à la source dans la vue de validation ?

Pour moi, ça me semble logique qu'un auteur dde MP a lu son propre message, donc je serai pour générer le `PrivateTopicRead` par défaut, mais si ça n'as pas été fait, c'est qu'il y a une raison ... Qui m’échappe ;)

**Comment by vhf** [comment]
J'ai jamais été validateur du coup j'ai 2 questions pour ce ticket : 
1. Est-ce que j'ai bien compris la situation ? Ma compréhension est que le validateur qui réserve un tuto reçoit un MP de confirmation, mais que ce MP n'est pas accompagné de la notification habituelle pour un MP.
2. Est-on proche d'avoir un patch pour ça ou est-ce que vous pensez que ça va encore prendre une semaine ?

Merci !

**Comment by pierre-24** [comment]
Pour le (1) → oui. Et pour le (2), je te _patche_ ça dès que je suis certain de la marche à suivre (donc en fait j'attend que @GerardPaligot réponde à ma question, sauf si est encore plus motivé que moi et qu'il _patche_ dans la foulée). Quelque soit la réponse, ça devrait pas faire plus de 10 lignes.
