### ISSUE TITLE
[beta][v20] Le compteur du nombre de réponses à un MP ne fonctionne pas

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3843]
Aller sur l'url : https://beta.zestedesavoir.com/mp/ 

Vous pouvez remarquer que le nombre de réponses n'est pas visible. On voit à chaque fois "réponse" sans savoir combien de réponses.

Regarder ce qui est fait en prod par exemple : https://zestedesavoir.com/mp/

**Comment by vhf** [comment]
https://github.com/zestedesavoir/zds-site/pull/3814/files#diff-df0bd34eb4f91b11451f1fc9cc20df54R58

:-°

**Comment by pierre-24** [comment]
Done !

**Comment by firm1** [comment]
Désolé je ré-ouvre ici car ce bug n'est pas corrigé dans la RC4.

**Comment by vhf** [comment]
C'est moi où il manque "simplement" l'affichage du nombre ici : https://github.com/zestedesavoir/zds-site/blob/release-v20/templates/mp/index.html#L58 ?

**Comment by pierre-24** [comment]
Bien vu, on dirait.

**Comment by pierre-24** [comment]
C'est bon:

![screenshot from 2016-10-20 17 11 57](https://cloud.githubusercontent.com/assets/7889675/19565774/5c3620fe-96e8-11e6-9469-643b40175de7.png)

Merci @GerardPaligot !
