### ISSUE TITLE
[beta][v20] Le bouton de signalement d'un MP existe, mais ne fait rien

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3844]
On est pas censé pouvoir signaler un MP, mais en allant dans une conversation privée, je vois le bouton "Signaler" sur un MP. Je tente de le suivre et voir ou cela me mène, et pouf, page blanche.

Donc je dirais que le front à oublié de faire sauter le bouton.

**Comment by GerardPaligot** [comment]
Corrigé.
