### ISSUE TITLE
[beta][v20] Sur mobile on perd de l'information dans la zone de notifs

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3847]
En allant dans la zone de notification sur mobile (firefox) je ne retrouve pas l'information sur la date d'arrivée des notification.
Pourtant en prod actuellement on a bien la date (même sur mobile).

Voici le screen que j'ai.

![tmp_12136-screenshot_20160920-081131-810323503](https://cloud.githubusercontent.com/assets/6066015/18659348/4d7517be-7f0a-11e6-964c-0c2de25a3cf2.png)

**Comment by GerardPaligot** [comment]
Merci @AmarOk1412
