### ISSUE TITLE
Labels page de recherche

### ISSUE THREAD

**Issue by EtienneR** [zestedesavoir/zds-site#3848]
Sur la page de [recherche](https://zestedesavoir.com/rechercher), à gauche, la liste des filtres ne contient pas de label.

Ce serait bien que la liste des mots soit "cochable" :)

**Comment by DevHugo** [comment]
Je suis pas sur d'avoir tout compris, tu parle des labels dans le code ? Si oui, ça été [corrigé par un collectionneur de canard](https://github.com/zestedesavoir/zds-site/pull/3839), que je remercie !
Sinon les cases devrait être cochable, sous chrome et windows, ça marche bien. Sous quel OS et navigateur,  es-tu ?

![capture](https://cloud.githubusercontent.com/assets/6099338/18690286/ab3f32ca-7f8d-11e6-8c41-4e423978e85f.PNG)

**Comment by EtienneR** [comment]
Oups désolé, je n'avais pas vu cette issue (pas encore intégrée dans la béta).

**Comment by DevHugo** [comment]
Pas de souci. Faut que je fasse la QA de la PR, je vais faire ça dans la semaine.
