### ISSUE TITLE
gcc et redhat-rpm-config pas installé par make

### ISSUE THREAD

**Issue by tleb** [zestedesavoir/zds-site#3859]
gcc est nécessaire pour installer le back mais n'est pas installé par le make (`make install-fedora` dans mon cas). Nécessaire pour la librairie python `cairocffi`.

Il manque aussi `redhat-rpm-config` (comme dis avant, je suis sur fedora, c'est spécifique à rpm) sinon on a une erreur : `gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory`.

**Comment by vhf** [comment]
Ok merci ! Tu fais une PR / veux faire une PR mais a besoin d'aide / préfère qu'on s'en occupe ?

**Comment by tleb** [comment]
Je vais envoyer la PR. Juste une info : c'est bien `gcc` pour debian et ubuntu ou ça a un autre nom ?

**Comment by vhf** [comment]
Cool ! `build-essential` pour debian et ubuntu. Ça inclut probablement 1-2 trucs pas indispensables mais c'est mieux comme ça.

**Comment by tleb** [comment]
Done. Il ne faudrait pas mettre chaque dépendance à une ligne, dans le même style que ce qui se fait d'habitude dans les Dockerfiles ?

**Comment by vhf** [comment]
Merci !

Ça dépend, tu parles de formattage ? Si oui, on préfère souvent 

```
RUN apt-get install \
    foo \
    bar
```

à

```
RUN apt-get install foo bar
```

pour des questions de propreté du diff.

Si tu veux pas parler du formattage mais de ça par exemple :

```
RUN apt-get install foo
RUN apt-get install bar
```

ou dans un Makefile

```
install:
    apt-get install foo
    apt-get install bar
```

c'est une mauvaise pratique. Dans le cas du Dockerfile, il va créer une image intermédiaire par RUN. Dans le cas du Dockerfile _et_ du Makefile, ça va :
1. être plus lent
2. ne pas prendre en compte les dépendances entre les packets. (Ici, si par exemple `foo` dépend de `bar` ou l'inverse, une des deux commandes sera un noop.)

Dans le cas qui nous intéresse, ces dépendances sont censées changer tous 3 ans, donc le diff n'est pas un problème. Je préfère un Makefile un peu plus compact. Aussi, ça facilite les comparaisons entre les lignes.
