### ISSUE TITLE
[Membre] Afficher le badge sur le profil

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#386]
Aucun badge n'est actuellement affiché sur le profil, il semble intéressant de l'afficher.

Cette issue sera corrigée pour la prochaine beta.

**Comment by SpaceFox** [comment]
Badge genre "staff" je suppose ?

**Comment by Alex-D** [comment]
Exactement.

**Comment by firm1** [comment]
Bon bah il est fixé.

**Comment by Alex-D** [comment]
Je la réouvre en retirant le tag beta, car il faudra que je vérifie ça sur la branche intégration.

**Comment by Alex-D** [comment]
A priori c'est fait dans la branche intégration suite au merge... mais la page profil est à refaire, cf #152
