### ISSUE TITLE
Documenter le support navigateur du front-end

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3862]
Il faut qu'on sache quels browsers on supporte. Sauf erreur @sandhose sait, mais il est le seul.

C'est extrêmement important, ça devrait aller sans dire. On n'a pas assez de contributions front-end, et si on dit à chaque personne qui veut y contribuer de choisir ses propres navigateurs, on fonce droit dans le mur.

**Comment by SpaceFox** [comment]
Aux dernières nouvelles, c'était « au moins les navigateurs supportés par leurs éditeurs, le reste en bonus pour les motivés mais c'est pas officiel ».

**Comment by vhf** [comment]
> au moins les navigateurs supportés par leurs éditeurs

Il y a une liste quelque part ? Et comment restreint-on cette liste ? Par exemple [Yandex Browser](https://browser.yandex.com) est supporté par son éditeur, mais peine à dépasser les 0.1% d'usage global, et hors des régions russophones c'est probablement 25 ou 50x moins que ce 0.1%.

J'ai l'impression qu'il serait préférable de se baser par exemple sur le 99e centile en France ([exemple](http://browserl.ist/?q=%3E1%25+in+FR))

**Comment by SpaceFox** [comment]
Dans les navigateurs raisonnablement utilisés ^^

On a une idée d'où viennent les données de ton site ? Parce que selon les sources, les 1 % ont tendance à être assez variables.

**Comment by vhf** [comment]
Elles viennent de [caniuse](http://caniuse.com/usage-table), la source étant [statcounter](http://statcounter.com).

**Comment by motet-a** [comment]
(Je déterre)

Le 99<sup>ème</sup> percentile me semble très bien. Ça veut dire qu’on retire le support d’IE 10, ce qui est une bonne nouvelle pour nous ([même IE 11 est loin d’être facile](https://github.com/zestedesavoir/zds-site/issues/4465)…).

**Comment by artragis** [comment]
il me semble que la doc est complète à ce propos, non,
