### ISSUE TITLE
Il manque un bout de documentation sur l'installation (?)

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#3865]
Bonjour!

Comme ça faisait longtemps, j'ai tenté de réinstaller ZdS aujourd'hui. J'ai donc [suivi la documentation donnée ici](http://zds-site.readthedocs.io/fr/latest/install/backend-linux-install.html), et je me suis retrouvé bêtement bloqué. Parce que pour moi, il manque l'introduction [écrite ici](https://zestedesavoir.com/forums/sujet/324/comment-contribuer-comprendre-comment-suivre-le-workflow/). Est ce que ça ne serait pas intéressant de le rajouter dans ladite doc ?

**Comment by Emeric54** [comment]
Pourquoi pas. Même si ça peut sembler évident, on a déjà vu certains nouveaux contributeurs se retrouver coincés, ne sachant pas où commencer. Donc oui, je pense que ça peut-être intéressant d'ajouter ce passage dans la doc.

**Comment by pierre-24** [comment]
Me suis rendu compte après que [c'était ici](https://github.com/zestedesavoir/zds-site/blob/dev/CONTRIBUTING.md) (en grosse partie), et pas sur ReadTheDoc. Donc ... Chaipa. 

Le mot d'ordre, ici, c'est "on fait pas de la documentation pour des outils". Et je crois que c'est pour ça que ça y est pas.

**Comment by vhf** [comment]
Je pense qu'il faut que le contenu du contributing soit sur readthedocs et que le contributing.md doit juste contenir un lien vers la bonne page readthedocs. Volontiers une PR en ce sens. Je vois pas ça comme de la doc sur un outil, plus sur notre workflow.
