### ISSUE TITLE
Publier la documentation technique sur ReadTheDocs.io

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#3866]
Je trouves cela bien utile, par ailleurs il n'est pas nécessaire d'avoir les fichiers ResT de la doc sur le dépôt GH, il suffit de bien configurer le fichier `conf.py`.

C'est ce que j'ai fait [ici](http://zest-writer.readthedocs.io/fr/master/build/rst/javadoc.html) (et comme du coup maintenant je sais bien faire ce genre de trucs, je veux bien prendre le ticket :-) ).

**Comment by vhf** [comment]
La documentation est sur read the docs. Ou alors j'ai pas pigé. J'ai pas non plus compris l'idée du `conf.py`.

**Comment by lypwig** [comment]
Je parle de la documentation générée par les docstrings du code python. Le conf.py est un fichier de configuration (mais on peut aussi mettre un peu de code dedans) qui est interprété par Sphinx et permettant de générer la documentation.

**Comment by vhf** [comment]
D'accord. Si ça cohabite bien avec notre doc actuelle pourquoi pas. Tu nous fais un exemple en PR ? Ce sera aussi l'occasion de les relire, un bon nombre sont incompréhensibles.

**Comment by Situphen** [comment]
Ce n'est pas déjà ce qu'il y a [ici](http://zds-site.readthedocs.io/fr/latest/back-end-code.html) ?

**Comment by lypwig** [comment]
Ah ben si, c'est exactement ça. Je n'étais pas tombé dessus. :-)
