### ISSUE TITLE
"Cette réponse m'a aidé" sur un commentaire écrit par l'OP 

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#3867]
Comme la proposition semble être largement adoptée [sur le forum](https://zestedesavoir.com/forums/sujet/7093/cette-reponse-ma-aide-sur-un-commentaire-ecrit-par-lop/), j'en fais un ticket pour assurer le suivi.

**Comment by pierre-24** [comment]
Merci @AmarOk1412 :)
