### ISSUE TITLE
"make fixtures" ne fonctionne pas

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#3868]
Par exemple:

``` bash
(zdsenv)pbeaujea@chim13-cptrx04 ~/Devels/zds-site $ make fixtures
make: `fixtures' is up to date.
```

... Probablement parce que "fixtures" est aussi un dossier à la racine et que donc `make` va pas chercher dans ces règles à lui. Solution la plus simple : renommer la commandes (et éditer [la doc](http://zds-site.readthedocs.io/fr/latest/utils/fixture_loaders.html) qui ne parle pas de `make`, d'ailleurs)

**Comment by tleb** [comment]
J'ai trouvé [ça](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html). Je ne connais pas vraiment make, mais ça fonctionne : si on ajoute `.PHONY: fixtures` dans le fichier, la commande que tu as donné fonctionne.

D'ailleurs, cette commande n'est même pas mentionné dans le help du make.

Et il y a un point en trop dans [la commande](https://github.com/zestedesavoir/zds-site/blob/dev/Makefile#L78). En l'enlevant, ça fonctionne _as expected_.

Personne n'a d'objection, j'ajoute ça à #3860 ?

**Comment by tleb** [comment]
Pas de retour, c'est que c'est bon, j'ajoute à #3860 ?

**Comment by pierre-24** [comment]
Personne a rien à dire, et c'est moi qui te l'ai proposé, donc vas-y. Limite, renomme ta ZEP en "amélioration du Makefile" :)

**Comment by poulp** [comment]
Je viens de tester et tout marche très bien

**Comment by tleb** [comment]
Parfait, c'est que la PR est bonne. On peut fermer l'issue ?

**Comment by pierre-24** [comment]
oui ! (20 ans plus tard :p )
