### ISSUE TITLE
Ajouter une petite étoile devant les sujets/forums suivis

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#3869]
Ce serait pratique et sympa. :-) L’icône se situerait au même niveau que _topic en post-it_ et _réponse trouvée_, je pense à un truc comme ça :

![Sujets suivis](http://i.imgur.com/W4qFf0P.png)

![Forums suivis](http://i.imgur.com/SPCThjr.png)

Voir [le topic associé](https://zestedesavoir.com/forums/message/editer/?message=127319) sur le forum sur le forum.

**Comment by pierre-24** [comment]
Et c'est passé, merci @AmarOk1412 :)
