### ISSUE TITLE
[Articles] Les ancres des commentaires ne sont pas bonnes

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#387]
Il y a un soucis d'intégration je pense qui fait que les ancres des commentaires ne sont pas bonnes (il me semble qu'il manque carrément les ids en fait).

**Comment by ShigeruM** [comment]
Sur la Home, quand il y a 0 ou 1 réaction à un article, le lien "Aucune réaction" (ou "n réaction") ne renvoie pas vers les réactions. Par contre à partir de 2 réactions postées ça à l'air ok (outre le problème d'ancre relevé dans cette issue).

Ça ne semble pas être exactement le même bug mais je me suis dit que c'était assez proche pour être mis dans la même issue.

**Comment by firm1** [comment]
Les 2 bugs précédemments signalés sont fixé -> mergé
