### ISSUE TITLE
Erreur javascript sur certaines pages d'une instance locale

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#3870]
Comme indiqué [ici](https://zestedesavoir.com/forums/sujet/7151/erreur-javascript-systematique-sur-une-version-locale-de-zds/):

> [...] Dès que je me rend sur une page qui emploi du javascript (genre n'importe quel sujet de forum ou n'importe quel tuto/article en brouillon), Firefox et Chrome me lâchent une erreur du genre `Uncaught Error: Syntax error, unrecognized expression: [href=#qqch]:first`.  J'ai fait mes petites recherches, et [j'arrive sur cette discussion](https://github.com/jquery/jquery/issues/2824) ou en gros, on dit que l'expression devrait être `[href="#qqch"]:first` (si je comprend bien).

avec

> ```
> $ node -v
> v4.6.0
> $ npm -v
> 3.10.8
> ```

**Comment by GerardPaligot** [comment]
ping @sandhose C'est sans doute lié à ton refacto.
