### ISSUE TITLE
[beta][v20] Nombre de réponses dans le forums non affichées

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3876]
On a un petit souci avec le nombre de réponses à un sujet dans le forum qui ne sont pas affichés.

Voir sur ce lien : https://beta.zestedesavoir.com/forums/communaute/bug-suggestions/ voici ce que l'on obtiens :

![reponses-fauses](https://cloud.githubusercontent.com/assets/6066015/19553397/68f2df28-96b4-11e6-9f0b-e6d89e330a6b.PNG)

Je pense qu'il y'a une régression là.

**Comment by pierre-24** [comment]
C'est bon:

![screenshot from 2016-10-20 17 12 43](https://cloud.githubusercontent.com/assets/7889675/19565804/76f90582-96e8-11e6-91a7-6d895c5a6bab.png)
