### ISSUE TITLE
Plus de "border-collapse" ?

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#3879]
Si je prend [le dernier tuto en date](https://zestedesavoir.com/tutoriels/1294/des-bases-de-donnees-en-python-avec-sqlite3/fonctionnalites-de-base/), voilà ce qu'on obtient:

![screenshot from 2016-10-20 16 46 33](https://cloud.githubusercontent.com/assets/7889675/19564851/30a8f4fa-96e5-11e6-974a-0bbd4897c119.png)

Et maintenant, lorsqu'on l'importe sur une version locale (à jour sur dev, bien entendu, et avec `make build-front`):

![screenshot from 2016-10-20 16 46 33](https://cloud.githubusercontent.com/assets/7889675/19564893/506939c6-96e5-11e6-9e18-3d5784a31d9e.png)

(regardez le code et le tableau)

Comme on peut le voir, le `border-collapse: collapse` à disparu. Si c'est un choix, alors OK, mais personnellement, je trouve ça moche (et ça me dérange depuis hier, mais j'arrivais pas à trouver ce que c'était).

Ping @sandhose :)

**Comment by pierre-24** [comment]
Le `border-bottom: 1px solid #ddd` a disparu aussi, je pense.

**Comment by vhf** [comment]
(Pardon pour la confusion sur le titre du ticket.)

**Comment by pierre-24** [comment]
Pas de soucis. Mais j'ai testé sur la bêta, le front est bon, donc c'est récent :)

**Comment by pierre-24** [comment]
Rien vu quand tu as remis la branche de release dans dev ?

**Comment by vhf** [comment]
Niveau CSS non. Les quelques conflits sont documentés par le commitlog du merge. Peux-tu préciser la question ?

**Comment by pierre-24** [comment]
Ben le problème, c'est que je sais pas trop quoi chercher. En tout cas, même si on dirais que c'est apparu après la v20, le commitlog ne donne pas d'infos (donc y'a pas eu de conflit).

**Comment by pierre-24** [comment]
Bon, personne n'as ce problème, en fait ? Je dois être sur un bug bizarre, du coup o_O
