### ISSUE TITLE
[Membre] Améliorer le formulaire d'inscription

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#388]
Certains membres suggèrent de retirer la répétition du champ "mot de passe" au profit d'un bouton "Afficher le mot de passe" qui permettrait de vérifier ce que l'on vient de taper.

Personnellement, je trouve ça plutôt bien. Des avis ?

**Comment by SpaceFox** [comment]
J'aime bien, mais c'est complètement pas standard sur PC. A voir la
faisabilité.

**Comment by Alex-D** [comment]
Sur PC avec Windows 8 et Internet Explorer 9+ je crois, il y a un oeil sur tous les champs de type password.

**Comment by SpaceFox** [comment]
Oui, mais c'est du spécifique IE.

**Comment by Alex-D** [comment]
Certes, mais Firefox a l'air de s'y mettre ^^
Cf : https://twitter.com/stopsatgreen/status/461088559898701824

**Comment by firm1** [comment]
Je ne suis pas pour une telle feature ... l'expérience a montré que les gens ne savent pas ce qu'ils ecrivent

**Comment by geoffreyc** [comment]
Je préfère qu'un bot me confirme que j'ai mal tapé mon mot de passe, plutôt
que d'avoir a vérifier moi mémé a chaque fois de peur de me gourer et de
pas pouvoir me connecter par la suite. Surtout que me forcer a rendre mon
mdp visible c'est pas cool, surtout si je suis dans un endroit publique ou
peuplé.

2014-05-02 16:50 GMT+01:00 firm1 notifications@github.com:

**Comment by Alex-D** [comment]
On abandonne l'idée alors ? J'avoue ne pas avoir été totalement convaincu à la base.

**Comment by ShigeruM** [comment]
Gros +1 Geoffrey ! Ce n'est pas parce que c'est à la mode qu'on doit le
faire aussi, surtout si c'est pourri.
