### ISSUE TITLE
Mettre en place des classes d'admin pour certains modèles

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3881]
Quand on modèle a une clé étrangère vers un modèle qui a beaucoup d'entrées (> 250), le serveur crash parce qu'il doit charger trop de données. Une requête par entrée dans la clé étrangère.

Si on ouvre l'admin pour éditer un topic et qu'il y a 10'000 messages sur les forums, vu qu'un topic référence un message, il y aura donc plus de 10'000 requêtes.

C'est facile à régler, on peut s'inspirer de ce que j'ai fait ici : https://github.com/zestedesavoir/zds-site/pull/3722

Sans ça, l'admin est inutilisable. Si vous avez des doutes sur un modèle, demandez ici et je vous dirai c'est nécessaire ou pas. Mais a priori dès qu'on a une clé vers un modèle qui a plein d'entrées, c'est nécessaire.

**Comment by vhf** [comment]
Les pages d'admin qui posent problème sont :
- forum/post
- gallery/usergallery
- gallery/image
- member/karmanote
- member/profile
- member/ban
- member/tokenregister
- member/tokenforgotpassword
- mp/privatetopic
- mp/privatetopicread
- mp/privatepost
- notification/subscription
- notification/notification
- pages/groupcontact
- tutorialv2/publishablecontent
- tutorialv2/publishedcontent
- tutorialv2/contentreaction
- tutorialv2/validation
- utils/alert

Il faut se concentrer sur l'élimination du chargement de FK lorsque la table de FK a plus que quelques centaines d'entrées.

Généralement le problème dans ces modèles est que le modèle pointe sur un utilisateur. Du coup il y a une requête par utilisateur.

C'est pire quand ça pointe sur un message du forum, un truc 'souscriptable', un contenu, etc.

**Comment by gustavi** [comment]
Je rajouterai qu'ajouter la ligne pour la recherche à ces classes serai **très pratique** :)

**Comment by pierre-24** [comment]
Je peux me tromper, mais j'ai l'impression que ta modification pour les topics a réduit le nombre de choses affichées par l'administration. Par exemple, moi, j'ai ça : 

![screenshot from 2016-12-25 17 50 12](https://cloud.githubusercontent.com/assets/7889675/21472120/c5c0e994-caca-11e6-93a7-6a6615baaf95.png)

Alors que je devrais avoir le topic, l'auteur, etc ...

**Comment by vhf** [comment]
Bien vu, merci @pierre-24 .

**Comment by pierre-24** [comment]
... Sauf que je vois pas l'erreur, puisqu'à priori, t'as bien généré l'admin comme il fallait o_O

**Comment by Anto59290** [comment]
J'ai regardé un peu pour m'occuper de ce ticket. Il me semble qu'une classe comme cela fait l'affaire : 

```py
class PostAdmin(admin.ModelAdmin):
    raw_id_fields = ('author',)
```

J'ai l'impression que si l'on ne renseigne pas la variable `fields` il continu avec tous les champs. Est-ce que ça vous va si je précise juste les `raw_id_fields` comme dans mon exemple ?

**Comment by pierre-24** [comment]
Ben essaye et on verra :)

**Comment by Anto59290** [comment]
J'ai essayé et ça marche. Ma question en fait c'était plutôt : y a-t-il une bonne raison de pas faire comme ça ?

**Comment by vhf** [comment]
Pas que je sache @Anto59290 ! Je me réjouis que ça soit réglé cette histoire. 👍

**Comment by pierre-24** [comment]
Et voilà, @Anto59290 a été plus rapide que moi :p
