### ISSUE TITLE
« Se souvenir de moi » ne semble pas avoir une très bonne mémoire

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3891]
J'ai l'impression que le bouton « Se souvenir de moi » a la mémoire courte (une petite semaine), je suis obligé de me reconnecter _beaucoup_ plus souvent que sur la plupart des sites. Peut-on augmenter cette valeur ?

**Comment by WinXaito** [comment]
Hm il me semble que c'est bien plus long pour moi, genre 2-3 mois. Ou alors j'ai l'impression que le temps passe vraiment lentement :p

**Comment by SpaceFox** [comment]
C'est un comportement que je retrouve sur différents ordinateurs et navigateurs, c'est pour ça que j'ai supposé que ça venait du site.

C'est Opera et Vivaldi, dernières versions, sur Ubuntu 16.04 et Mint (la dernière, je sais même pas le numéro de version).

**Comment by pierre-24** [comment]
J'ai la même impression que @SpaceFox ...

**Comment by vhf** [comment]
Chez moi c'est environ 2 semaines. @SpaceFox tu veux combien de temps ?

On n'override pas le [défaut](https://github.com/django/django/blob/1.8/django/conf/global_settings.py#L472), donc ce sera vite réglé.

**Comment by SpaceFox** [comment]
Un mois, c'est un classique non ?

**Comment by WinXaito** [comment]
J'aurais été persuader que c'était plus... je me fais sûrement des idée

**Comment by vhf** [comment]
Ça me va. Une PR sur update.md pour pas qu'on oublie ?

**Comment by vhf** [comment]
Je ferme, ce sera pris en compte au prochain redémarrage du site.
