### ISSUE TITLE
Annuler la pop-up Abréviation de l'éditeur md remplace le contenu par NaN.

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#3893]
- se rendre sur le forum ou sur un contenu en rédaction ;
- dans la barre d'outils de l'éditeur, taper n'importe quoi ;
- cliquer sur le bouton 'Abreviation'.

Le contenu présent dans la fenêtre d'édition est remplacé par 'NaN'.

**Comment by AmarOk1412** [comment]
Hmm d'ailleurs, on a un Abbréviation et un Abréviation dans la popup
![2016-10-28-17 51 53-screenshot](https://cloud.githubusercontent.com/assets/1888628/19823568/4a0efc7a-9d37-11e6-8ea2-6488206fc33a.png)
