### ISSUE TITLE
[beta][v20] Incohérence dans les tags autorisés entre contenus et forums

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3894]
On ne peut pas renseigner d'émojis dans les tag d'un contenu, mais c'est autorisé dans les tags de forum.

J'ai l'impression que c'est pour se sauver d'un problème technique, mais niveau expérience utilisateur, ça manque de cohérence.

**Comment by vhf** [comment]
Tu as un exemple de sujet de forum avec emoji comme tag ? Parce que ça devrait pas être possible de mettre des emojis dans les tags des sujets, du coup ça me surprend beaucoup. En tout cas faudrait qu'on puisse reproduire le bug dont tu parles pour le considérer comme un vrai bug.

**Comment by firm1** [comment]
Ce sujet [par exemple](https://beta.zestedesavoir.com/forums/sujet/6788/tagatest/) possède un tag avec des emojis

**Comment by vhf** [comment]
Je serais très surpris que ces vieux (1993) caractères passent pas comme tags de contenus. Je vais voir ça.

**Comment by vhf** [comment]
Je confirme, ça passe comme tag de contenu. Pour moi il n'y a pas d'incohérence.

**Comment by SpaceFox** [comment]
À noter que tout tag contenant un emoji récent (exemple 🦊) est supprimé sans aucun avertissement ! Exemple : https://beta.zestedesavoir.com/forums/sujet/6793/tete-de-renard/

**Comment by vhf** [comment]
Yep @SpaceFox, ça en revanche c'est un problème. Pas bien difficile à régler, mais si c'est le seul problème de la RC5 on réglera ça dans la prochaine release. Le fix sera de réutiliser les nouveaux validateurs de tags qui sont en place sur les contenus : https://github.com/zestedesavoir/zds-site/pull/3875

Issue #3895

**Comment by firm1** [comment]
Je ferme donc ici. Ce sont les nouveaux emojis qui ne tournent pas
