### ISSUE TITLE
Mettre à jour les dépendances

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3898]
Corvée pour les motivés : https://requires.io/github/zestedesavoir/zds-site/requirements/?branch=dev

**Comment by LudovicDrtt** [comment]
Juste le truc c'est de mettre les versions à jour dans les fichiers de vérifier que les tests passent bien ?

**Comment by vhf** [comment]
@LudoBike c'est pire que ça malheureusement.

Idéalement, pour chaque dépendance faudrait voir si y'a rien de suspect dans le changelog. Respecter semver. Vérifier que les dépendances des dépendances respectent aussi semver.

**Comment by SpaceFox** [comment]
À noter que dans la liste y'a Djange 1.8 -> 1.10, ce qui est loin d'être
trivial

Le 28 oct. 2016 2:29 PM, "victor felder" notifications@github.com a
écrit :
