### ISSUE TITLE
Categories of tutorials

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#39]
Hello,

Je me suis un peu penché sur les templates pour voir comment ça fonctionnait. J'ai donc compris comment on pouvait récupérer les catégories des forums sur toutes les pages (et je dois dire que c'est plutôt élégant).

Par contre, je me pose beaucoup de questions sur les catégories des tutoriels. Sur cette [page](https://github.com/Taluu/ZesteDeSavoir/blob/master/zds/utils/templatetags/topbar.py). Nous pouvons y voir deux imports :

``` python
from zds.forum.models import Category as fCategory
from zds.utils.models import Category as Category
```

Le premier correspond aux catégories des forums et le second aux catégories des tutoriels. J'aurais aimé savoir pourquoi une partie des tutoriels est gérée dans le module `utils` et non pas dans `tutorials`.

Cela ne doit-il pas faire l'objet d'un gros refactoring ?

**Comment by firm1** [comment]
La réponse à ça c'est que d'un coté la catégories de forums ne serviront qu'aux forums, et donc le choix de les mettre dans l'app forum est justifié. De l'autre coté, les catégories de tutoriels, devront servir aussi pour les Articles, et peut-être autre chose en fonction de l'évolution du site. Du coup, j'ai jugé plus efficace de les ranger dans utils plutôt que tutorial.

**Comment by GerardPaligot** [comment]
Si j'ai bien compris, les articles seront intégrés dans les forums de ZdS. Si les catégories doivent être partagées, ça sera sans doute plutôt avec les forums qu'avec les tutoriels.

Ceci dit, je préfère ré-intégrer les catégories des tutoriels dans le module des tutos (d'intégrer les sous-catégories au passage) et de faire un import en cas de besoin.

Qu'en penses-tu ?

**Comment by firm1** [comment]
> Si j'ai bien compris, les articles seront intégrés dans les forums de ZdS

Euh non, pas vraiment. Les Articles ont droit, tout comme les tutos à un module spécial pour la création des articles, avec possibilité de rédaction à plusieurs (communautaire toussa) et la rédaction doit être versionné, les articles doivent être validés, par le staff pour être publié, etc.
Le coup des Articles qui apparaissent dans les forums, on l'a [épluché sur le redmine](http://zds.leomartinez.fr/issues/11#note-13) et ça a été adopté dans un semblant de démocratie :-) qu'on fait un module dédié.

De toute façon, si on fait des sous catégories pour les tutos, il me semble évident qu'on utilisera aussi ses cous catégories pour les Articles, ne serait-ce que pour la précision de rangement.

**Comment by GerardPaligot** [comment]
Ok, je comprends l'idée mais notre module `utils` risque de devenir énorme si nous y mettons toutes les classes et ressources communes. N'existe-t-il pas un moyen plus propre de faire partager la chose ?

Sinon, l'idée de déplacer la classe `Catégory` dans le module `tutorials` n'empêche en rien un module dédié.

**Comment by firm1** [comment]
> Ok, je comprends l'idée mais notre module `utils` risque de devenir énorme si nous y mettons toutes les classes et ressources communes. N'existe-t-il pas un moyen plus propre de faire partager la chose ?

C'est vrai que pour le coup j'utilise utils pour stocker les trucs communs à plusieurs app (catégories, licences, Alertes, etc.). Il n'y a pas vraiment façon de gérer ça proprement hormsi créer une app dédiée pour stocker ça.

> Sinon, l'idée de déplacer la classe `Catégory` dans le module `tutorials` n'empêche en rien un module dédié.

Le problème avec cette idée, serait que dans le module Article, il faudra à chaque fois faire appel au module Tutorial (pour ses catégories), ça crée une forte dépendance entre les deux, comme si un Article avait besoin d'un Tutoriel pour fonctionner et surtout on pourrait penser que les catégories sont la propriété des Tutos et que les Articles viennent juste voler ce qui ne leur appartient pas. En les mettant dans un module séparé (et donc neutre) on ne crée aucune dépendance entre les Articles et les Tutos directement.

**Comment by GerardPaligot** [comment]
Il y avait une idée d'OC qui consistait à voir les articles comme des mini-tutos. En soit, ce n'est pas une mauvaise idée. Quasiment rien ne distingue un article d'un mini-tuto hormis son contenu. Il faudrait donc réfléchir à cette forte dépendance pour voir si elle se serait pas intéressante justement.

**Comment by firm1** [comment]
Dans ma tête, je vois vraiment les Articles différemment des tutos. Les Articles sont un peut les News de la V3. Et si aujourd'hui on couple fortement la notion d'Article et de Tuto, et que demain la communauté commence à demander des outils dédié aux Articles (système de votes pour publication d'un Article, commentaire sur les Articles en cours de validation, etc.), on sera se retrouvera un peu coincer à faire des rustine sales.

**Comment by GerardPaligot** [comment]
Bon, au risque de paraitre vraiment incompétent, ne serait-il pas possible d'étendre les classes du module des tutoriels pour y intégrer les concepts des articles ? Ca nous permettrait de lier les articles au tuto tout en y ajoutant proprement des données.

**Comment by firm1** [comment]
> ne serait-il pas possible d'étendre les classes du module des tutoriels pour y intégrer les concepts des articles ?

C'est possible, mais ça ne me semble pas propre conceptuellement parlant.

On pourrait se demander, pourquoi ne fait-on pas l'inverse, c'est à dire, intégrer dans le module des articles les catégories et les étendre dans le module des Tutos ?
L'idée de gérer la ressource Catégorie à part, permet justement de rendre les deux modules complètement indépendant l'un de l'autre et donc nous donne plus de flexibilité quant aux évolutions futures.

**Comment by GerardPaligot** [comment]
Ok, va pour le module commun mais faudrait créer un module dédié.

**Comment by GerardPaligot** [comment]
Convaincu par le module commun et avec l'ajout des sous-catégories (https://github.com/Taluu/ZesteDeSavoir/pull/42), on peut fermer cette issue.
