### ISSUE TITLE
L'envoie de mail ne fonctionne pas sur la beta

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#3901]
Sur la beta, l'envoi de mails ne fonctionne pas.

C'est problématique surtout si on veut utiliser la fonction "J'ai oublié mon mot de passe".

**Comment by SpaceFox** [comment]
En fait elle fonctionne, mais le backend est configuré pour écrire les mails envoyés sur le disque. On avait  sans doute fait ça à des fins de debug et on a jamais remis une conf qui envoie réellement des mails.

**Comment by lypwig** [comment]
Pour moi c'est un peu chiant car je ne peux pas tester la beta. :/

Je rencontre régulièrement un problème pour me connecter (et non je ne viens pas de changer mon pw sur la prod, je l'ai changé juste une fois il y a genre 2 mois).

**Comment by artragis** [comment]
@vhf @gustavi il me semble que ça a été corrigé non?

**Comment by nils-van-zuijlen** [comment]
Je up, y'a sans doute moyen de corriger ça en même temps que #5041 si c'est juste une question de configuration.

**Comment by Arnaud-D** [comment]
Je pense qu'il faut que la bêta n'envoie pas de mails à qui que ce soit.

Par exemple, si quelqu'un testait quelque chose sur la bêta et que je recevais une notification par mail depuis la bêta en conséquence, je considèrerais ça comme un bug.

D'autres avis ? SInon, je pense qu'on peut fermer ce ticket.
