### ISSUE TITLE
[v20] Erreur 500 dans la liste des tutoriels en mode non connecté

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3902]
Je suis tombé sur une erreur 500 en allant va sur cette url en étant non connecté au site : https://zestedesavoir.com/tutoriels/

Etant donné que les robots nous indexes par là, je me dis que c'est a prendre en priorité.

**Comment by firm1** [comment]
Par contre je n'arrive pas à la reproduire. Donc à voir.

**Comment by pierre-24** [comment]
Y'a Sentry qui crache que MySQL ce casse la gueule sur cette page.

**Comment by vhf** [comment]
Je vais me permettre de fermer, rouvrez si ça se reproduit svp.

D'après Sentry c'était pile pendant que je rebootais MySQL, du coup c'est pas étonnant, il y a 3-4 requêtes qui se sont pris une 500 à ce moment puisque MySQL était down.

**Comment by SpaceFox** [comment]
T'as dû tomber au moment du redémarrage de MySQL.

2016-10-27 15:19 GMT+02:00 firm1 notifications@github.com:
