### ISSUE TITLE
Notification persistante dans la V20

### ISSUE THREAD

**Issue by rezemika** [zestedesavoir/zds-site#3904]
Il y a un peu plus de deux mois, je m'étais abonné au fil "Hier, je sort enfin... Pour le pire ?". Ce faisant, je recevais naturellement une notification à chaque nouveau message sur ce fil.

Or, une de ces notifications a été reçue en triple et ne disparaissait pas après lecture, celle se rapportant au message de "Mr phacochère" que voici : [https://zestedesavoir.com/forums/sujet/6821/hier-je-sort-enfin-pour-le-pire/?page=2#p122139](https://zestedesavoir.com/forums/sujet/6821/hier-je-sort-enfin-pour-le-pire/?page=2#p122139). J'ai cru comprendre que le masquage de ce message avait posé problème.

Ainsi que je le décrivais sur le forum ([ici](https://zestedesavoir.com/forums/sujet/6836/erreurs-500-lors-dun-clic-sur-une-notification/)), ces notifications étaient généralement fonctionnelles, mais elles me renvoyaient aussi parfois sur une erreur 500. Ce problème apparaîssait également après une suppression des caches, ou depuis un autre ordinateur.

La V20 étant sortie, ce problème apparaît toujours, à la différence qu'il n'y a plus qu'une seule notification (toujours vers le même message), et qu'elle ne renvoie plus d'erreur 500. Elle persiste toujours après une suppression des caches, ou depuis un autre ordinateur.

**Comment by artragis** [comment]
je m'en occupe
