### ISSUE TITLE
Tutoriels "fantômes" dans la liste personelle des tutos

### ISSUE THREAD

**Issue by rezemika** [zestedesavoir/zds-site#3906]
En me rendant sur la page recensant mes tutoriels, j'ai constaté que plusieurs d'entre-eux apparaissent toujours après que je les ai supprimés. Leurs encadrés et leurs tags sont toujours affichés, mais j'ai une erreur 404 en cliquant dessus. Ce phénomène se produit pour trois de mes tutoriels. Il persiste après une suppression des caches, sur un autre ordinateur, et ce depuis plusieurs versions du site.

Pour les deux premiers ("Puissances, exposants et racines carrées" et "Qu'est-ce qu'une fonction mathématique ?"), leur suppression fut volontaire. Je cliqua sur le bouton de suppression, confirma et fut redirigé vers la liste des tutoriels, où ces derniers apparaissaient toujours.

Pour le troisième ("Introduction au TI-Basic"), la suppression fut accidentelle. Il s'agissait au départ d'un mini-tuto, que je voulais transformer en moyen-tuto. J'ai donc téléchargé une archive de sauvegarde, et ai voulu supprimer les différentes parties. J'ai donc cliqué sur la première partie dans le sommaire, et ai cliqué sur le bouton "Supprimer". La page s'est alors rechargée, et j'ai eu une erreur 404. Je suis retourné à la liste des tutoriels, où ce dernier apparaissait toujours, sans être accessible. Je n'ai heureusement rien perdu grâce à l'archive que j'ai téléchargé, et j'ai pu recréer un nouveau tuto pour l'importer.

Voici les liens des tutoriels en question, récupérés depuis la page "Mes tutoriels" :
- [https://zestedesavoir.com/contenus/557/puissances-exposants-et-racines-carrees/](https://zestedesavoir.com/contenus/557/puissances-exposants-et-racines-carrees/)
- [https://zestedesavoir.com/contenus/560/quest-ce-quune-fonction-mathematique/](https://zestedesavoir.com/contenus/560/quest-ce-quune-fonction-mathematique/)
- [https://zestedesavoir.com/contenus/1523/introduction-au-ti-basic/](https://zestedesavoir.com/contenus/1523/introduction-au-ti-basic/)

**Comment by artragis** [comment]
Salut, te souviens-tu du message qui était affiché (succès/erreur)?
Ces tutoriels dataient de quand?

@vhf peux tu regarder ce qu'il se passe sur les tutoriels 557, 560 et 1523?

**Comment by rezemika** [comment]
Salut.

> te souviens-tu du message qui était affiché (succès/erreur)?

Malheureusement, non. Ce problème est apparu pour la dernière fois en mi-septembre, mais il ne me semble pas qu'il y ai eu une différence manifeste par rapport à une erreur "normale", si je puis dire. Désolé de ne pas pouvoir être plus précis.

Voici tout de même les dates que je peux donner pour ces tutos :
- 557 : Créé et envoyé en bêta le 18 septembre 2015. Je n'ai pas la date de suppression, mais ce fut bien après.
- 560 : Créé le 20 septembre 2015, envoyé en bêta le 11 décembre 2015. Je n'ai pas la date de suppression, mais ce fut le même jour que le 557.
- 1523 : Créé et envoyé en bêta le 11 septembre 2016. Erreur apparue le 12 septembre 2016.

**Comment by artragis** [comment]
Ok pour les deux premiers, tu as le lien vers les topic de béta?

**Comment by rezemika** [comment]
Bien sur, les voici : 
- 557 : [https://zestedesavoir.com/forums/sujet/4051/puissances-exposants-et-racines-carrees/](https://zestedesavoir.com/forums/sujet/4051/puissances-exposants-et-racines-carrees/)
- 560 : [https://zestedesavoir.com/forums/sujet/4822/quest-ce-quune-fonction-mathematique/](https://zestedesavoir.com/forums/sujet/4822/quest-ce-quune-fonction-mathematique/)
- 1523 : [https://zestedesavoir.com/forums/sujet/6904/introduction-au-ti-basic/](https://zestedesavoir.com/forums/sujet/6904/introduction-au-ti-basic/)

**Comment by rezemika** [comment]
Le sujet a été remonté sur le forum ([ici](https://zestedesavoir.com/forums/sujet/8896/tuto-supprime-encore-dans-la-liste-personelle/)) par @alliocha1805 qui est sujet au même problème. J'en profite pour remonter le ticket idoine.

**Comment by Situphen** [comment]
@rezemika Toujours d'actualité ?

**Comment by rezemika** [comment]
Salut, oui je viens de vérifier, les trois tutos concernés sont toujours là.

PS : Je vous présente mes excuses pour ma presque disparition, j'ai eu pas mal d'ennuis qui se sont plus ou moins enchainés... :/

**Comment by Situphen** [comment]
Pour les 3 tutoriels dont tu parles, leur contenu sur le disque du serveur était bien supprimé, mais pas leur entrée dans la base de données donc je l'ai fait manuellement. Je suppose que le bug n'est plus d'actualité et je n'ai pas pu reproduire donc je ferme.
