### ISSUE TITLE
Inscription / renvoi de confirmation / mot de passe oublié

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3907]
Echanges avec un membre par email, on a visiblement plusieurs problèmes dont certains graves et urgents. Voici un résumé retravaillé de l'échange : 

> Je viens de tenter de m'inscrire sur votre site Zeste de Savoir et je n'ai pas reçu le courriel de confirmation...
> 
> J'ai tenté, via l'interface de renvoi du courriel de confirmation, mais il semble y avoir un bug dans cette interface car lorsque j'y spécifie mon nom d'utilisateur (**) ou mon courriel (**),
> 1. aucun courriel d'activation n'est envoyé et
> 2. l'interface me spécifie que le nom d'utilisateur ou le courriel sont déjà utilisé. (Comme s'il s'agissait d'une tentative d'inscription...)
> - Je confirme que le courriel n'a pas non plus atterris dans mon dossier Spam, et
> - j'ai tenté l'inscription avec une autre adresse courriel et a produit le même problème.
> 
> J'aimerais également vous mentionner un deuxième bug au niveau de la page de récupération de mot de passe oublié. ("https://zestedesavoir.com/membres/reinitialisation/").
> Lorsque j'entre mon courriel et que je confirme le formulaire, je suis dirigé vers une page titrée: "Erreur 500", où on me dit que je viens de découvrir un bug et l'on me prie de vous le signaler ainsi que le moyen de le reproduire.

Je peux pas regarder ça ce soir, est-ce que quelqu'un peut tenter de reproduire chaque étape et raconter ici ? Est-ce que quelqu'un peut investiguer au moins un de ces bugs et expliquer ?

@gustavi tu peux aussi regarder vu que t'as accès aux serveurs ?

**Comment by artragis** [comment]
le mail a été refusé par le serveur mail. Et a causé la 500. Par contre c'est le serveur final qu iest en cause.

**Comment by vhf** [comment]
Donc gmail refuse nos emails ? C'est un problème, si c'est le cas.

En fait c'est pas ça. Aucun email sort de notre serveur depuis le redémarrage.

**Comment by rezemika** [comment]
Je viens d'essayer de créer un compte sur beta.zestedesavoir.com avec une adresse Gmail (sous le pseudo 'reze.mika'), je confirme que rien n'a été reçu, ni dans la boite de réception, ni dans les spams. De plus, quand je cliques sur le bouton d'inscription via Google+, j'arrives sur une erreur 404 "redirect_uri_mismatch" :

`The redirect URI in the request, https://beta.zestedesavoir.com/complete/google-oauth2/, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/38548450822-q99dii7fvoq6t4mlgfs60q2eg24c3ul3.apps.googleusercontent.com?project=38548450822 to update the authorized redirect URIs.`

Pour lapage de récupération de mot de passe, je peux accéder sans erreur à la récupération par email, mais je ne reçois rien non plus. Même chose en passant par la récupération par pseudo.

**Comment by pierre-24** [comment]
Si jamais, `{u'**@gmail.com': (451, '4.3.0 <noreply@zestedesavoir.com>: Temporary lookup failure')}`. Ça peut pas être bon, ça.

**Comment by Emeric54** [comment]
> Je viens d'essayer de créer un compte sur beta.zestedesavoir.com avec une adresse Gmail (sous le pseudo 'reze.mika'), je confirme que rien n'a été reçu, ni dans la boite de réception, ni dans les spams.

La bêta n’envoie pas de mails, et ça a été configuré volontairement.

**Comment by pierre-24** [comment]
Chaipas si c'est lié, mais MySQL arrête pas de claquer.

**Comment by vhf** [comment]
Réglé par @sandhose, merci beaucoup, j'ouvre un autre ticket pour les autres problèmes.
