### ISSUE TITLE
Erreur 404 sur un tutoriel

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#3908]
J'ai créé un tutoriel nommé `test` il y a quelque temps, aujourd'hui il est en 404.

L'URL (non publique) est : https://zestedesavoir.com/contenus/1413/test-7/

**Comment by gustavi** [comment]
Alors j'avais proposé une solution pour virer tous ces problèmes liés aux slugs et au redirections foireuses via `must_redirect` : on redirige tout /contenus/<pk>/<n_importe_quelle_str>/ vers /contenu/<pk>/<slug>/. Ça permet de ne pas casser le SEO, d'éviter les problèmes comme celui-ci et de simplifier le code.

**Comment by pierre-24** [comment]
?? (je comprend pas le problème à la base, en fait)

**Comment by Situphen** [comment]
Je ferme car le bug des slugs modifiés a été corrigé.
