### ISSUE TITLE
[v20] MySQL provoque régulièrement des erreurs 500

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3909]
@firm1 avait créé une [issue](https://github.com/zestedesavoir/zds-site/issues/3902) plus spécifique sur le même bug qu'il avait rencontré sur la liste des tutoriels mais le bug semble plus généraliste. Encore hier soir, j'ai reçu à plusieurs reprises des mails de Sentry m'informant que MySQL s'était foutu la mal.

Je tag haute mais ça pourrait limite être bloquant tellement ça arrive souvent. Par contre, je ne sais pas si c'est de l'infra ou du back. Dans le doute, je tag rien à ce niveau là.

``` console
OperationalError: (2006, 'MySQL server has gone away')
(11 additional frame(s) were not displayed)
...
  File "django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
```

**Comment by vhf** [comment]
J'arrive toujours pas à prendre ce problème au sérieux. Qu'est-ce qui te fait croire qu'il ne s'agit pas de redémarrage de MySQL ?

**Comment by vhf** [comment]
Bon, je suis quand même allé voir, voici les redémarrages : 

```
Oct 27 15:15:13 gandi systemd[1]: Started MySQL
Oct 27 16:57:05 gandi systemd[1]: Started MySQL
Oct 28 00:07:39 gandi systemd[1]: Started MySQL
Oct 28 00:18:48 gandi systemd[1]: Started MySQL
Oct 28 01:31:47 gandi systemd[1]: Started MySQL
Oct 28 01:32:43 gandi systemd[1]: Started MySQL
```

Est-ce que tu peux m'indiquer les erreurs qui se sont produites en dehors de ces redémarrages, ou fermer ce ticket ?

**Comment by pierre-24** [comment]
Pas besoin de le prendre comme ça non plus ^^ 

@GerardPaligot  ne peut évidement pas être au courant des heures tests, forcément. Objectivement, j'ai vu les erreurs Sentry dans ma boite mail ce matin, j'ai "paniqué" aussi.

**Comment by vhf** [comment]
Bah je le prends comme un problème important s'il y a quelque chose de pas normal, parce qu'effectivement ça peut être grave. Du coup je me penche volontiers sur les erreurs qui se sont produites en dehors des redémarrages de mysql, et s'il n'y en a pas je pense vraiment qu'on peut fermer ce ticket.

**Comment by gustavi** [comment]
C'est toujours lors d'un redémarrage, c'était moi pour le coup. Du coup pour moi l'issue n'en est pas vraiment une.

**Comment by vhf** [comment]
Top, merci à tous, je ferme.
