### ISSUE TITLE
Ajout d'un install-archlinux dans le Makefile

### ISSUE THREAD

**Issue by LudovicDrtt** [zestedesavoir/zds-site#3910]
Pour les utilisateurs de la distribution ésotérique, et surtout parce que c'est bien pratique d'avoir qu'une seule commande à taper pour l'installation. 

Cela évite aussi d'installer les bibliothèques de python3 à la place de python2.

**Comment by LudovicDrtt** [comment]
J'ai fini les modifs sur le Makefile et je vais écrire la doc qui va avec.

**Comment by pierre-24** [comment]
T'as trouvé ce qui n’allait pas avec le front, du coup ?

**Comment by LudovicDrtt** [comment]
Nop j'ai tous recommencé et en faite le seul problème c'est que j'avais installer les lib pour python3 vu que c'est ce qu'il y a par défaut sur Arch

**Comment by pierre-24** [comment]
aaah, ok. Voilà qui est mieux :)

**Comment by LudoBike** [comment]
Il faut écrire un test pour les makefiles ?
