### ISSUE TITLE
Renvoi email confirmation du compte

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3912]
Sur cette page : https://zestedesavoir.com/membres/validation/

Quand on entre un email ou pseudo, le formulaire n'est pas validé : "Cette adresse de courriel est déjà utilisée", du coup le mail ne part pas.

**Comment by DevHugo** [comment]
C'est juste le message qui est pas clair, il affiche cette erreur quand le compte est déjà validé. 

[Voir ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/views.py#L320)

**Comment by vhf** [comment]
J'ai pas l'impression @DevHugo . Le compte que j'ai testé n'est pas actif.

**Comment by DevHugo** [comment]
Il passe par [ce validateur](https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/forms.py#L432), alors qu'il devrait pas. Faut faire attention car les deux formulaires: mots de passe oublié et pas de courriel d'activation utilise le même formulaire.

**Comment by vhf** [comment]
Voilà, il est là le problème, merci @DevHugo !

**Comment by AmarOk1412** [comment]
En fait si il doit passer par ce validateur. C'est juste qu'il devrait faire un `check_username_available=False` au validate, comme pour les password, je prend.
