### ISSUE TITLE
Problème du futur

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3914]
Screenshot après un 'edit' tout à fait normal : 

<img width="326" alt="screen shot 2016-10-28 at 21 12 09" src="https://cloud.githubusercontent.com/assets/2022803/19819114/79bb1bd6-9d53-11e6-8b97-5e5608762c00.png">

**Comment by tleb** [comment]
Ça vient [d'ici](https://github.com/zestedesavoir/zds-site/blob/caec43a6f8d56f23fd3f13298aef5d3567cd8c84/zds/utils/templatetags/date.py#L47-L48). Tu as eu ça sur ta propre instance ou sur la prod ? C'est sûrement un problème de datetime sur le système ou de timezone non ?

Cette nuit, on rajoute une heure, c'est pas lié à ça si ?

**Comment by vhf** [comment]
J'ai eu ça sur la prod. Je pense que la v20 est beaucoup trop rapide. Qui peut faire une PR avec un `sleep` aléatoire sur chaque page, pour régler ce problème ?

Sinon non, je pense pas que ce soit lié au changement d'heure.

**Comment by pierre-24** [comment]
> "Je pense que la v20 est beaucoup trop rapide"

Celle là, je la note :)

**Comment by LudovicDrtt** [comment]
Qui aurait cru que cette condition allait être vrai un jour :D

**Comment by vhf** [comment]
Rebelotte avec les alertes : 

<img width="220" alt="screen shot 2016-10-30 at 12 23 35" src="https://cloud.githubusercontent.com/assets/2022803/19836288/ca4574e0-9e9b-11e6-8e44-3c378f278fb6.png">

**Comment by lypwig** [comment]
Je vous confirme que ça vient pas du changement d'heure, quand on actualise la page de suite après, on a _il y a xx secondes_.

**Comment by pierre-24** [comment]
Bon, je propose que si `-2 < delta <2`, on mette "maintenant", une connerie du genre.

**Comment by lypwig** [comment]
Ouep

**Comment by vhf** [comment]
Je me demande s'il suffirait pas de supprimer [cette ligne](https://github.com/zestedesavoir/zds-site/blob/caec43a6f8d56f23fd3f13298aef5d3567cd8c84/zds/utils/templatetags/date.py#L45) pour résoudre le bug.

**Comment by azze-r** [comment]
En local, il m'est impossible de reproduire le bug, il ne survient qu'en prod apparement : 

Quand j'édite un message du fofo en local : 
`" Édité par user il y a une seconde "`

Quand j'édite un message du fofo sur zds en prod : 
`"Édité par Boblinux Dans le futur"`

**Comment by SpaceFox** [comment]
Je rajoute que le problème se pose aussi quand on ajoute un commentaire sur un membre en tant que staff. Là, j'ai droit à : 

> Remarques sur cet utilisateur ({note}) :
> - {note} dans le futur par SpaceFox : {commentaire}

**Comment by vhf** [comment]
Si vous arrivez à répliquer sur la beta, j'ai un fix en tête.

**Comment by vhf** [comment]
Ce bug est désormais une feature.

**Comment by pierre-24** [comment]
Toute cette issue est une énorme faille dans la réalité ;)

**Comment by SpaceFox** [comment]
Mais qu'est-ce que la réaleté ?

**Comment by SuperFola** [comment]
Et si en fait cela venait de ceci : 
```py
if getattr(value, 'tzinfo', None):
    now = datetime.now(LocalTimezone(value))
else:
    now = datetime.now()
```

Un if sur la localTimeZone, comme juste après y a un `now = now - timedelta(microseconds=now.microsecond)` ca pourrait jouer non ? Léger décalage entre une heure locale et ... une autre x)

edit : après des tests plus appronfondi, je dirais que ca vient du module datetime lui même

Pour preuve : 

```py
import time
import datetime as d

n = lambda: d.datetime.now()
i = 0
while i <= 60:
    ddn = n()
    print(ddn, ddn - d.timedelta(seconds=ddn.second)
    time.sleep(1)
    i += 1
```

`n()` avance en secondes, mais pas quand on fait la soustraction avec le timedelta, ce qui fait qu'on est dans le futur par rapport à `n()`

Si je me trompe pas, ce comportement serait généralisé aux autres attributs `days` et `microseconds` ce qui cause le bug. Faut que je zieutte la source de `datetime` histoire de voir

**Comment by tleb** [comment]
*Semi-HS : pour faire des tests sur les datetimes, génère en une et une seul par tour de boucle, là t'en génère trois différentes et ça peut fausser tes résultats. Et tu as créé une boucle infini là vu que tu n'incrémentes pas `i`.*
