### ISSUE TITLE
Compteur d'abonnés disparaît quand on clique sur suivre

### ISSUE THREAD

**Issue by tleb** [zestedesavoir/zds-site#3917]
- "Suivre le sujet (3 abonnés)"
- Clique sur le bouton
- Bouton devient "Ne plus suivre le sujet"
- Il faut refresh la page pour avoir "Ne plus suivre le sujet (4 abonnés)"

On ne peut pas envoyer le compteur dans la requête AJAX qui est faite ?

**Comment by vhf** [comment]
Si si, on pourrait. Actuellement on retourne `{follow: true}` en cas de succès, il pourrait retourner `{follow: true, count: #}` à la place.

**Comment by tleb** [comment]
OK, j'ai passé un peu de temps pour comprendre la structure des forums niveau back, je suis maintenant au point. :smile: 

Par contre, niveau front, j'aimerai bien avoir des retours de ceux qui connaissent le projet pour savoir comment faire ça proprement : [ici](https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/ajax-actions.js#L69), on a un toggleText, cool, mais il faut le modifier si on veut avoir le nombre d'abonnés. Je vois pas trop comment faire pour ne pas dégueulasser le code et pour ne pas avoir de phrase dans le front. Le mieux que j'ai trouvé, c'est de mettre la phrase abonné et la phrase non abonné dans deux `data-` avec un placeholder pour le nombre et un autre `data-` avec l'état. On toggle l'état et on change la phrase à chaque requête AJAX. (Edit, en me relisant, je réalise que je suis probablement pas très clair, mais bon, ma solution n'est probablement pas la meilleur de toute façon.)

Quelqu'un peut poke ceux qui connaissent bien le front svp ? Je connais pas encore bien l'équipe. :stuck_out_tongue:

**Comment by vhf** [comment]
@tleb je peux aider là dessus en début d'après midi.

**Comment by vhf** [comment]
Ok je te propose ceci.

https://github.com/zestedesavoir/zds-site/blob/c15cbda88293d5753c1d7fa4380bb23e56dfe713/templates/notification/subscription_count_template.html#L14 là tu mets `subscriber_count` dans un `span` avec pour `id` `subscriber_count`.

et là https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/ajax-actions.js#L56 tu récupères le `subscriber_count` depuis `data` et tu mets sa valeur dans le `span`.

**Comment by tleb** [comment]
Tellement plus simple, en effet. Je vais faire ça, merci.

**Comment by pierre-24** [comment]
Et voilà, merci @tleb :)
