### ISSUE TITLE
Double participant dans un MP de réservation

### ISSUE THREAD

**Issue by Emeric54** [zestedesavoir/zds-site#3921]
Victor a dû valider lui-même le dernier article annonçant [l'article annonçant](https://zestedesavoir.com/articles/1438/nouvelle-version-nouvelle-version/) nos dernières versions. Or, lorsqu'un validateur réserve un contenu, un MP est automatiquement envoyé par le valido aux auteurs. Le problème se trouve ici : victor se retrouve deux fois dans les participants.

![alt](http://img15.hostingpics.net/pics/135389Capture.png)

En temps normal, un auteur n'est pas censé publier lui-même son contenu. Toutefois, ça reste un bug.

**Comment by Emeric54** [comment]
Un des des victor est donc le validateur, et l'autre l'auteur. Toutefois, [ce bloc](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_validations.py#L273) de code devrait permettre de ne pas se retrouver avec des participants en double.

``` py
authors = list(validation.content.authors.all())
if validation.validator in authors:
    authors.remove(validation.validator)
if authors.__len__ > 0:
    send_mp(
        validation.validator,
        authors,
        ...
)
```

**Comment by vhf** [comment]
Yep, il devrait. Et il le fera probablement à l'avenir. Sauf que ce code est pas en prod. ;)

(J'ai lu le lien que t'as donné et je me disais "tiens t'as raison, c'est curieux", et après j'ai vu que c'était dev, j'ai mis prod dans l'URL et paf !)

Du coup merci d'avoir investigué, je pense qu'on peut fermer : https://github.com/zestedesavoir/zds-site/pull/3864
