### ISSUE TITLE
Les tests unitaires ne passent plus depuis le changement d'heure

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#3924]
Bonjour,

Le test unitaire `"test_humane_time"(ligne 118)` dans le fichier `"zds-site/zds/utils/templatetags/tests/tests_date.py"` ne passe plus à cause du changement d’horaire !

`Cause: AssertionError: u'jeudi 01 janvier 1970 \xe0 01h00' != u'jeudi 01 janvier 1970 \xe0 00h00'`

[Exemple de build qui ne passe plus.](https://travis-ci.org/zestedesavoir/zds-site/jobs/171775668)

**Comment by pierre-24** [comment]
Donc [ce test là](https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/templatetags/tests/tests_date.py#L105).

**Comment by pierre-24** [comment]
Voir #3468 pour l'implémentation du machin. Ceci dit, sur ma petite machine localisée en belgique (et à priori à la bonne heure).

```
>>> import datetime
>>> t = datetime.datetime.fromtimestamp(42)
>>> print(t)
1970-01-01 01:00:42
```

Ce qui est pas logique: on est plus en heure d'été, donc on rajoute plus une heure o_O

**Comment by pierre-24** [comment]
Et si on faisait fausse route, en fait ?

Pourquoi est ce que epoch+42, ça fairait autre chose que 1h00 et 42 secondes le 1 janvier 1970 ? Autrement dit, qu'est ce que l'heure d'été a a voir avec tout ça ?

En fait, ce test un peu bizarre provient de [là](https://github.com/vhf/zds-site/commit/f45a539b07050f37be563fb240108e86bca26df8) (de manière légitime). Sauf que @pquentin a fait du zèle, je crois ;)

M'enfin je dis ça, et dans 6 mois, rebelote. [Mais j'y crois](http://www.commitstrip.com/fr/2016/01/14/a-story-about-timestamp-and-timezone/).

**Comment by pquentin** [comment]
Je suis dans le fuseau horaire Indian/Reunion, et voilà ce que ton code donne pour moi :

```
>>> import datetime
>>> t = datetime.datetime.fromtimestamp(42)
>>> print(t)
1970-01-01 04:00:42
```

Ça veut dire qu'au timestamp 42, il était 1h du matin à Paris et 4h du matin à l'île de la Réunion. Et ça ne dépend effectivement pas du fuseau horaire au moment où on exécute le code, donc ce test était effectivement mauvais, désolé. Il aurait fallu mocker le temps pour s'assurer que cet test était valide.

(Je suis désolé pour ce test, mais je suis toujours aussi fier du reste du code, de la pull request à GitPython et de mon message de commit que j'ai trouvé limpide un an après l'avoir écrit. Donc ça valait le coup de faire du zèle.)
