### ISSUE TITLE
[Notifications] Les liens mènent toujours vers la page 1

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#393]
Malgré un nombre de réponses important, les liens mènent vers la page 1 plutôt que la page concernée (la seconde par exemple).

**Comment by SpaceFox** [comment]
Je prends.

**Comment by SpaceFox** [comment]
En fait, on a deux notions : `TopicRead` et `TopicFollowed`. Le premier conserve le dernier post lu, pas le second.
Le problème vient du fait que l'affichage des topics suivis ne se base **que** sur `TopicFollowed`, donc envoie toujours sur "le topic", donc sa 1ère page.

Question subsidiaire : est-ce qu'à partir d'un ID de post, on a un moyen simple d'accéder à sa page dans le topic ?
J'ai l'impression que non, et du coup on rejoint l'issue #406.

**Comment by firm1** [comment]
> Le problème vient du fait que l'affichage des topics suivis ne se base que sur TopicFollowed

Pas uniquement là dessus.

La zone de notification est normalement traitée via ce [bout de code](https://github.com/Taluu/ZesteDeSavoir/blob/release-beta-1.0/zds/utils/templatetags/interventions.py#L32). Qui fait appel a des methodes de la classe TopicRead.

> est-ce qu'à partir d'un ID de post, on a un moyen simple d'accéder à sa page dans le topic ?

D'emblée comme ça je dirais [cette méthode](https://github.com/Taluu/ZesteDeSavoir/blob/release-beta-1.0/zds/forum/models.py#L260)

**Comment by SpaceFox** [comment]
> La zone de notification est normalement traitée via ce bout de codehttps://github.com/Taluu/ZesteDeSavoir/blob/release-beta-1.0/zds/utils/templatetags/interventions.py#L32.
> Qui fait appel a des methodes de la classe TopicRead.

Justement non : ça c'est la zone en haut, pas celle à gauche.
La zone en haut a des notifs qui marche, mais celle à gauche n'est basée
que sur les topics suivis (on suit par défaut tout topic sur lequel on
poste) donc n'a pas les IDs de posts donc ne peut pas envoyer sur la bonne
page.

**Comment by firm1** [comment]
> pas celle à gauche.

Autant pour moi, le titre de l'issue et le message principal laissait penser le contraire.

> donc n'a pas les IDs de posts donc ne peut pas envoyer sur la bonne
> page.

Quelque chose me dit qu'en remplaçant sur [cette ligne](https://github.com/Taluu/ZesteDeSavoir/blob/release-beta-1.0/templates/forum/base.html#L37), lui :  `{{topic.get_absolute_url}}` par lui `{{topic.first_unread_post}}` ça a des chances de fonctionner.

**Comment by SpaceFox** [comment]
Théoriquement par `{{ topic.first_unread_post.get_absolute_url }}`. Mais théoriquement seulement, parce que le `topic.first_unread_post` n'a pas l'air de fonctionner comme prévu : ça me renvoie systématiquement au 1er post du topic :(

**Comment by firm1** [comment]
Du coup, c'est lui qu'il faudrait corriger (le contenu du try certainement).

**Comment by SpaceFox** [comment]
Corrigé et mergé.

**Comment by SpaceFox** [comment]
Apparemment soit j'ai merdé quelque part, soit y'a eu collision avec autre chose, mais les liens du menu de gauche ne sont plus en gras lorsqu'il y a de nouveaux messages non lus.

Comme c'est quelque chose qui marchait avant que je corrige, je considère que j'ai merdé et je rouvre ce bug.

**Comment by SpaceFox** [comment]
En fait, la classe CSS (`topic_read` ou `topic_unread`) est bien la bonne, je ne sais pas pourquoi `topic_unread` ne mets plus le lien en gras.

Si quelqu'un qui connaît l'intégration CSS peut jeter un œil, ce sera plus efficace que si j'y passe des plombes pour trouver où est un problème que je ne saurais pas corriger :S

**Comment by firm1** [comment]
C'était effectivement un bug css.

Donc c'est résolu.
