### ISSUE TITLE
Affichage de cases vides dans un tableau MD

### ISSUE THREAD

**Issue by AmarOk1412** [zestedesavoir/zds-site#3934]
cf ce sujet : https://zestedesavoir.com/forums/sujet/7244/cases-vides-dans-un-tableau-markdown/

Le tableau suivant est mal rendu :
> +-----+-------+-------+-------+-------+-------+
> |     | case1         | case2         | case3 |
> +-----+-------+-------+-------+-------+-------+
> |     | case4 | case5 | case6 | case7 |       |
> +=====+=======+=======+=======+=======+=======+
> |  X  |    X  |   X   |   X   |   X   |   X   |
> +-----+-------+-------+-------+-------+-------+

**Comment by GerardPaligot** [comment]
Ca semble être un ticket pour le projet Python-ZMarkdown plutôt.

**Comment by firm1** [comment]
Effectivement, et il a été [crée](https://github.com/zestedesavoir/Python-ZMarkdown/issues/107) là bas, donc on peut fermer ici
