### ISSUE TITLE
Correction du bug sur le smiley "gd" alias "pinch"

### ISSUE THREAD

**Issue by Croal** [zestedesavoir/zds-site#3939]
Le smiley "gd" alias "pinch" est victime d'un bug qui l'empêche de s'afficher.

**Comment by Croal** [comment]
Je prend !

**Comment by pierre-24** [comment]
ça marche. N'oublie pas de créer une branche, cette fois :)

**Comment by Croal** [comment]
D'ac (-: !

**Comment by Croal** [comment]
Et cette fois, je PR vers prod ou dev ? @pierre-24

**Comment by Emeric54** [comment]
Vers `dev`. 👍

**Comment by Croal** [comment]
**Problème résolu**. Tout est bon !

**Comment by gustavi** [comment]
Voir https://github.com/zestedesavoir/Python-ZMarkdown/issues/131
