### ISSUE TITLE
[v20][prod] Recherche down

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3941]
Rendez-vous sur ce [lien](https://zestedesavoir.com/rechercher/?q=android&models=tutorial) et constatez qu'il n'y a aucun résultat alors qu'il existe plusieurs tutoriels android.

**Comment by vhf** [comment]
Quand ça concerne un problème en prod, tu peux pinger ceux qui y ont accès @GerardPaligot .

Ping @gustavi . Tu peux aussi envoyer un email à zds-tech@googlegroups.com

**Comment by GerardPaligot** [comment]
On pourrait avoir un groupe GitHub pour ça ?

**Comment by firm1** [comment]
ça ressemble fortement à https://github.com/zestedesavoir/zds-site/issues/3796

**Comment by GerardPaligot** [comment]
Bien vu @firm1. D'ailleurs, j'ai bien des résultats sur la bêta.

**Comment by firm1** [comment]
En fait c'est pire que ça, là recherche est vraiment pétée de partout. On dirait que solr n'est pas demarré. Il y'a eu un reboot du serveur c'est peut être ça la cause

**Comment by vhf** [comment]
C'est probablement suite au reboot de cette nuit (à 00h00). Je viens de relancer la recherche sur la prod, je vous tiens au courant. J'étais pas dispo jusqu'à maintenant.

**Comment by vhf** [comment]
C'est réglé.
- Effectivement solr ne tournait pas. Je sais pas pourquoi.
- J'ai activé le démarrage automatique de solr lors du boot.
- btw @gustavi cf. http://unix.stackexchange.com/a/209368 , on en aura besoin a priori, à tester sur la beta

**Comment by vhf** [comment]
FYI @GerardPaligot , @zestedesavoir/infrastructure est désormais le groupe de gens qui ont accès à l'infra. Exprès pas nommé ça `dtc` ou autre, vu que si on a des sysadmins ils en feront partie. ;)

**Comment by GerardPaligot** [comment]
Super, merci.
