### ISSUE TITLE
[prod] la recherche d'un chapitre mène vers une 404

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3942]
En cliquant sur ce lien : https://zestedesavoir.com/rechercher/?q=Le+toki+pona+dans+une+coquille+de+noix&models=chapters

On obtient 2 résultats qui nous mène vers une 404.

**Comment by GerardPaligot** [comment]
La recherche semble indexer les mauvaises URL non ?

**Comment by firm1** [comment]
On dirait bien oui

**Comment by vhf** [comment]
J'ai lancé un `rebuild_index`, ce qui supprime intégralement l'index et réindex tous les contenus, et tout s'est bien passé.

Est-ce que nos URLs ont changé ces derniers mois ? Ou plutôt la méthode genre `get_absolute_url` des contenus peut-être ?

Pour documenter cette issue, voici comment reproduire le bug : 
- Effectuer cette recherche : `https://zestedesavoir.com/rechercher/?q=Le+toki+pona+dans+une+coquille+de+noix&models=chapters`
- Résultat retourné : 
  - `https://zestedesavoir.com/tutoriels/748/tout-savoir-sur-le-toki-pona/1017_partie-unique/4209_le-toki-pona-dans-une-coquille-de-noix-12/`
- Résultat attendu : 
  - `https://zestedesavoir.com/tutoriels/748/tout-savoir-sur-le-toki-pona/le-toki-pona-dans-une-coquille-de-noix-1-2/`

J'ai plus l'impression que la recherche ne génère pas les bonnes URLs pour les contenus, plus qu'elle n'indexe pas les bons contenus.

**Comment by DevHugo** [comment]
Deux idées comme ça.
- Si ton intuition est bonne, l'erreur devrait se [situé là](https://github.com/zestedesavoir/zds-site/blob/dev/zds/search/utils.py#L100). Comme ça, je vois pas de truc choquant mais ça peut-être un peu vicieux.
- Les url était bonne lors de l'indéxation de la validation officiel de l'article mais n'ont pas été mise à jours correctement lors de la seconde validation.

Si tu as accés à la prod regarde dans la table SearchIndexContainer, quel url à le container, ça pourrait peut-être aider à débugger.

**Comment by artragis** [comment]
ça sent le tutoriel qui a changé de forme après le passage de la zep12. C'est étrange néanmoins que ce bug ait lieu.

**Comment by artragis** [comment]
Ce n'est plus d'actualité car on ne peut plus chercher sur les chapitres.
