### ISSUE TITLE
"Recevez un courriel" lors des réponses aux MPs n'envoie pas d'email

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3944]
Je propose : 

* Logger l'exception ici : https://github.com/zestedesavoir/zds-site/commit/a84535b5472a5a24b35b469267606d02b889b8f3#diff-1af03a20d7374ee52c71d2f7adee8eabR141
* Ajouter un test unitaire pour ça, ici : https://github.com/zestedesavoir/zds-site/commit/a84535b5472a5a24b35b469267606d02b889b8f3#diff-5d12128c5fbeba8aee6b3e0a51898989R11
* Corriger le bug. J'ai pas de piste.

**Comment by Anto59290** [comment]
@vhf Est-ce que tu as un contexte plus précis sur comment reproduire? Sur une install neuve le mail part bien (enfin dans la console, mais on le voit passer). J'ai créé deux utilisateurs et celui qui a l'option de cochée recoit bien le mail pour les réponses.

**Comment by vhf** [comment]
@Anto59290 Non j'ai pas plus de contexte. Il semble que ça ne fonctionne que rarement et surtout très aléatoirement en production.

**Comment by AmarOk1412** [comment]
@vhf @Anto59290 Je viens de regarder vite fait cette issue. En fait, c'est pas aléatoire et je pense comprendre d'où vient l'issue. Dans `zds/notifications/models.py`, l'objet **SingleNotificationMixin** qui s'occupe d'envoyer le mail avec : 
```python
            if send_email and self.by_email:
                self.send_email(notification)
```

Le probleme c'est que self.by_email est désactivé dans `zds/notifications/managers.py` à l'envoi d'un mail (ou activé). Du coup, self.by_email vaut faux une fois sur 2.

J'essaye de faire un patch ce soir.

**Comment by Anto59290** [comment]
Je crois que ça a été mergé ici ;)
