### ISSUE TITLE
"1 réponse" mais "Aucune réponse" suite à la création d'un thread 

### ISSUE THREAD

**Issue by Fumble** [zestedesavoir/zds-site#3946]
Bug rapporté depuis le forum par Pierre de Vésian 

Bonsoir,

Je ne sais pas si ça a déjà été remonté, mes recherches ne l'ont pas indiqué. Il semble y avoir un problème de compteur lorsque l'on crée un thread sur le forum, la liste de la catégorie de forum indique qu'il y a une réponse, mais juste à droite qu'il n'y en a pas. Soit il faut transformer ce 1 en 0, soit le mot "réponse" à gauche n'est pas adapté à sa fonction.
Ce n'est pas bien grave comme bug, mais ça picote un peu lors de la création d'un thread.

![3eaa5dca-5996-499b-b036-d9cd40cf8bb9](https://cloud.githubusercontent.com/assets/634461/20042531/c00d6556-a47b-11e6-8ba7-9e8a921f5f39.png)

PS de Fumble: c'est aussi valable après qu'il y ait des réponses Je pense que l'intitulé devrait être "n message(s)" au lieu de réponses et si pas de réponse, on garde "Aucune réponse" à la place de la date du dernier message.

Lien du sujet: https://zestedesavoir.com/forums/sujet/7298/1-reponse-mais-aucune-reponse-suite-a-la-creation-dun-thread

**Comment by gllmc** [comment]
Salut !

J'avais remarqué ce bug également, mais il me semble qu'avant la v20, c'était bien le nombre de réponses qui était indiqué.

**Comment by ghost** [comment]
Dans tous les cas, même si c’est le nombre de réponses qui est effectivement rapporté, il y a un problème, puisqu’il n’y en a en fait aucune, quand « 1 réponse » est indiqué.

**Comment by Fumble** [comment]
Cela reste quand même plus logique d'avoir "1 message" + "Aucune réponse" plutôt que d'avoir "0 réponse" + "Aucune réponse" car c'est un peu redondant.

Et si on quelqu'un a déjà répondu, on aura "2 messages" + "Dernière réponse il y a XXX par YYY" (ou "Dernière réponse le XXX par YYY" si c'est plus ancien).

**Comment by gustavi** [comment]
Corrigé dans #3947, merci @Fumble !
