### ISSUE TITLE
Dans le menu, afficher les tags les plus utilisés en fonction du type déroulé.

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#3948]
Actuellement les tags les plus utilisés dans le menu ne sont pas spécifiques au type déroulé.

Comme j'en parlais [ici](https://zestedesavoir.com/forums/sujet/7250/venez-tester-les-tribunes/?page=2#p129490), ce serait que ce soit le cas (mais au final cela ne concerne pas que les Tribunes).

Par exemple, considérons ces chiffres :

|                               | Tutoriels | Articles | Tribunes | Tous | % tous |
| ----------------------------- | --------- | -------- | -------- | ---- | ------ |
| Nb de contenus tagés `Python` | 80        | 80       | 0        | 160  | 76%    |
| Nb de contenus tagés `Clem`   | 0         | 0        | 8        | 8    | 4%     |
| Nb total de contenus          | 100       | 100      | 10       | 210  | 100%   |

Ici, 80% des Tribunes sont taggées `Clem` et 0% des Tribunes sont taguées `Python`.

Pourtant, dans le menu Tribunes :

- on aura en tête le tag `Python` (car 76% de tous les contenus sont tagués `Python`), alors que si on clique dessus on aura rien, vu qu'il y a aucune Tribune tagguée `Python` ;
- on ne verra pas du tout le tag `Clem`, car il ne présente que 4% des contenus, alors qu'il est super pertinent pour les Tribunes.

**Comment by pierre-24** [comment]
Voilà qui est réglé :)
