### ISSUE TITLE
Impossibilité de se connecter

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#395]
Bug remonté par le membre elyppire933 :

Est-ce normal d'avoir une Internal Server Error depuis hier lorsque je souhaite me connecter ?
Si je supprime les cookies de ZdS je peux de nouveau afficher le formulaire de connexion, mais dès que je m'authentifie l'Internal Server Error me bloque l'accès au site.

Ce qui est bizarre, c'est que certains arrivent à poster des messages, cela ne semble donc pas une erreur massive.

**Comment by firm1** [comment]
Je soupçonne un problème avec vos compte.

Shig, pour reproduire le bug, est-ce que je peux avoir tes identifiants de connexion ?

**Comment by ShigeruM** [comment]
Moi je n'ai pas le bug, c'est Adrien et elyppire933 qui l'ont. Je fais un
mail avec tous ces gens.

**Comment by ShigeruM** [comment]
Identifiants passés en privé.

**Comment by firm1** [comment]
Bon le bug est fixé.

Vous pouvez prevenir ceux qui étaient impacté.

merci

**Comment by geoffreyc** [comment]
C'etait donc quoi? ((par simple curiosité)

**Comment by firm1** [comment]
L'explication du bug est notifié dans le commit précédents (visible sur
github).
