### ISSUE TITLE
Les heures ne dépendent pas du fuseau horaire local

### ISSUE THREAD

**Issue by AmarOk1412** [zestedesavoir/zds-site#3952]
Lorsqu'on est dans un fuseau horaire différent de celui de Paris, les heures des messages du forum/MP/etc sont à l'heure de Paris.

Ce serait plus logique de le voir selon l'heure où est la personne.

**Comment by pquentin** [comment]
C'est connu. Pour corriger le problème, il faudrait commencer par stocker toutes les dates en UTC (https://github.com/zestedesavoir/zds-site/pull/3930#issuecomment-257265912) et activer la gestion des fuseaux horaires dans Django. Ensuite ce serait "juste" un setting à rajouter: https://docs.djangoproject.com/en/1.10/topics/i18n/timezones/#selecting-the-current-time-zone

**Comment by pierre-24** [comment]
Oui. Après, @AmarOk1412  demande à "voir selon l'heure où est la personne", donc non pas chipoter l'heure côté Dajngo, mais pas un chipotage en JS (ou j'ai pas compris ^^ )

**Comment by SpaceFox** [comment]
Attention à ce que l'implémentation choisie n'interdise pas toute forme de cache, ce serait dommage.

**Comment by pquentin** [comment]
@pierre-24 En fait Django est capable de renvoyer les dates dans des fuseaux horaires différents selon un setting défini par les utilisateurs. Ils disent qu'on ne peut pas déterminer automatiquement le fuseau horaire de quelqu'un, donc il faut lui demander. (Je ne sais pas à quel point c'est vrai, surtout avec JS.)

Supposons qu'il faille effectivement demander : ça ne s'appliquera qu'aux gens qui ont changé leur fuseau horaire manuellement. Sûrement très peu de gens. En plus les dates "humaines" du type "il y 5 heures" devraient normalement rendre inutiles une telle information. J'imagine qu'on peut fermer, mais qu'il faudrait un ticket "stockons les dates en UTC".

**Comment by motet-a** [comment]
> En plus les dates "humaines" du type "il y 5 heures" devraient normalement rendre inutiles une telle information. J'imagine qu'on peut fermer, mais qu'il faudrait un ticket "stockons les dates en UTC".

Je plussoie.

Par contre, je suis vraiment contre le fait de s’occupper des fuseaux horaires côté serveur. Déjà parce que l’implémentation est trop compliquée (il faut rajouter un réglage, ça risque d’être la pagaille niveau cache), et ensuite parce que les utilisateurs n’aiment pas les trucs à régler.

Je pense que le plus simple est de faire comme GitHub : 

 - Dans le HTML généré côté serveur, on met toujours tout au format “JJ MMMM (YYYY)” (par exemple “2 septembre” ou “3 octobre 2015”), sans l’heure, en prenant soin d’englober le tout dans une balise `<time>` avec un attribut contentant la date et l’heure UTC avec une précision à la seconde près ;

 - Ensuite, un petit bout de JS passe sur tous les `<time>` en mettant des dates relatives partout (on obtiens donc des choses comme `il y a trois jours`). Ce même bout de JS prend soin de rajouter des attributs `title` pour avoir des infobulles avec une date et une heure absolue, “traduites” dans le fuseau horaire de l’utilisateur (parce qu’on connais toujours le fuseau horaire côté client).

**Comment by artragis** [comment]
que faire ici?

**Comment by pquentin** [comment]
Il reste "passer les heures en UTC", mais si on a survécu jusque-là, alors on peut aussi fermer. :)
