### ISSUE TITLE
Lien de confirmation d'inscription non clicable

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#396]
Visiblement il s'agit d'une balise <a> manquante [ici](https://github.com/Taluu/ZesteDeSavoir/blob/dev/templates/email/confirm_register.html#L10)

**Comment by Alex-D** [comment]
Je dirais plutôt deux lignes plus bas : 
https://github.com/Taluu/ZesteDeSavoir/blob/dev/templates/email/confirm_register.html#L12

**Comment by firm1** [comment]
En effet

**Comment by SpaceFox** [comment]
Non vu parce que 90% des clients mails sont intelligents et rajoutent le
lien tout seuls :D

2014-05-02 14:05 GMT+02:00 firm1 notifications@github.com:

**Comment by firm1** [comment]
Fixé -> mergé.
