### ISSUE TITLE
On peut se suivre soi-même via la publication d'un contenu

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#3961]
Pas sur que ce soi réellement un bug, mais,

+ S'inscrire en tant que nouvel utilisateur ;
+ Constater sur la page de profil que "Vous avez 0 abonné" (tristitude/20)
+ Créer un tuto, le faire publier ;
+ Constater que  "Vous avez 1 abonné"  ... Et que le validateur ne suis pas le tuto.

Dans un sens, c'est logique: pour recevoir les notifs concernant son (ses) propre(s) contenu(s), il faut y être abonné. Mais du coup, on est en pratique abonné à soi même, donc ça fausse un peu le compteur. Donc pour moi, faut juste faire "-1" au compteur si on a publié quelque chose (ou enelver l'auto-suivi dans le `count()`), et c'est bon (et du coup, je sais qui sont mes deux autres abonnés ;) )

**Comment by GerardPaligot** [comment]
Pourquoi le compteur est faussé ? Si je me suis moi-même, il y a bien un abonné (même si c'est moi). Et limite, je préfère voir le bouton "Se désabonner" pour ne plus être notifié de mes propres publications si je le désire.

**Comment by pierre-24** [comment]
Aussi, le résultat est le même. Je me demandais surtout d'où venait cet abonné mystérieux ;)

**Comment by artragis** [comment]
Du coup j'ai envie de dire que comme c'est un comportement voulu, faut le fermer non?
Pour l'instant on peut pas faire beaucoup mieux.

**Comment by pierre-24** [comment]
> Du coup j'ai envie de dire que comme c'est un comportement voulu, faut le fermer non?

Ça a beau être un comportement "voulu", ça dépend comment tu fixera #3954 :)

**Comment by Anto59290** [comment]
@pierre-24 @artragis Que faut-il faire ici ?

**Comment by pierre-24** [comment]
Bwah, du coup rien. Vu que le *fix* n'as pas enlevé ce comportement, c'est plus un bug mais une *feature* :)
