### ISSUE TITLE
Colorer les liens réervés au staff dans les menus

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#3963]
C'est pas grand chose et ça va pas être visible pas beaucoup de monde, mais ça serait vachement plus agréable. :-)

**Comment by GerardPaligot** [comment]
Tu pourrais donner un peu plus d'info ? J'ai aucune idée de quoi tu parles rien qu'en lisant ton ticket. (:

**Comment by lypwig** [comment]
En gros un truc comme ça :

![](https://i.imgur.com/dBAc0F9.png)

![](https://i.imgur.com/AH3sBTq.png)

Idem pour la page d'un membre ou d'un article. Ça rend le menu plus clair et on voit direct les action qu'on fait en tant que staff ou non.

**Comment by gllmc** [comment]
Merci @artragis !
