### ISSUE TITLE
Le lien du forum dans le fil d'ariane ne redirige pas à la page 1

### ISSUE THREAD

**Issue by delphiki** [zestedesavoir/zds-site#397]
Quand on est sur une page >1 d'un forum (ex. : http://zestedesavoir.com/forums/communaute/bug-suggestions/?page=2) et qu'on clique sur le nom du forum dans le fil d'ariane, il faudrait qu'on soit redirigé vers la page 1 du forum en question, et pas que l'action ne fasse rien.

Vu que ça a l'air d'être fait en JS, ça serait plus lié au front.

**Comment by delphiki** [comment]
Faudrait que j'arrive à le mettre sur le forum, mais impossible de poster...

**Comment by Alex-D** [comment]
En fait, le fil d'ariane actuel est plutôt sale au niveau du code (comme tu le dis il y a un semblant de JS qui n'a en fait pas lieu d'être).

Un autre soucis, si tu es sur la page 1, ergonomiquement le lien vers la page 1 n'a pas lieu d'être (puisque lié à la page courante). Sur les autres pages c'est en effet justifié.

Du coup : est-ce qu'on met le lien partout ? Nul par comme actuellement ? Ou avec une condition ?

**Comment by firm1** [comment]
Fixé donc.
