### ISSUE TITLE
Documentation incorrecte pour l'installation sur Windows

### ISSUE THREAD

**Issue by Nautigsam** [zestedesavoir/zds-site#3972]
En essayant d'installer ZDS sur ma machine Windows, j'ai relevé quelques erreurs dans la documentation :

- Dans la doc du [processus d'installation](http://zds-site.readthedocs.io/fr/latest/install/backend-windows-install.html), l'adresse de setuptools est mauvaise, le projet a été déplacé sur GitHub et la bonne adresse est ``https://bootstrap.pypa.io/ez_setup.py``.
- Dans le README, la commande pour récupérer les données de fixtures ne marche pas à cause de la wildcard. La bonne commande devrait être ``python .\manage.py loaddata (dir .\fixtures\*.yaml)``.

Je me l'assigne, la PR arrive.

**Comment by GerardPaligot** [comment]
Ce sont les seuls problèmes que tu as rencontré sur Windows ?

**Comment by Nautigsam** [comment]
Oui, tout est bon à part ça. L'instance se lance bien.

**Comment by GerardPaligot** [comment]
C'est plutôt une très bonne nouvelle alors parce que ça fait longtemps que nous n'avons plus de contributeurs sous Windows. Ravi de te compter parmi nous ! ^^
