### ISSUE TITLE
Photo de profil par défaut

### ISSUE THREAD

**Issue by Nautigsam** [zestedesavoir/zds-site#3974]
Actuellement, si un utilisateur n'a pas de photo de profil, tous les espaces où devrait apparaître la photo sont vides, ce qui est assez bizarre :

https://framapic.org/WsjVnIdGcUty/Wcx9yxPsiB62.PNG
https://framapic.org/CVdzQQufraVB/poRNe3UMZ7HC.PNG

Peut-être devrait-on avoir une photo de profil par défaut, comme partout ailleurs (Facebook, Google, Skype, etc.)

**Comment by tleb** [comment]
C'est sur une instance local de ZdS ça, non ?

Il me semble que des avatars sont générés pour les nouveaux sur la prod.

**Comment by WinXaito** [comment]
Si je ne dis pas de bêtise, pour les nouveaux membre un avatar aléatoire est généré par Gravatar. comme Github.

**Comment by Nautigsam** [comment]
Pourquoi on ne fait ça qu'en prod ?

**Comment by GerardPaligot** [comment]
On ne fait pas ça que en prod. Sur ma version en locale, des avatars sont aussi générés.

**Comment by tleb** [comment]
P-ê que c'est parce que c'est un compte généré par les fixtures ?

**Comment by GerardPaligot** [comment]
Sans doute pas, mes comptes générés par des fixtures ont aussi des avatars générés.

**Comment by Nautigsam** [comment]
Ah au temps pour moi, c'était un problème lié à HTTP/HTTPS. Etant donné que j'utilise l'extension HTTPS Everywhere, ça devait perturber le chargement de l'image sur Gravatar.
