### ISSUE TITLE
L'indexation des Topics ne marche plus

### ISSUE THREAD

**Issue by Nautigsam** [zestedesavoir/zds-site#3975]
Quand j'essaye d'indexer les fixtures avec ``python manage.py rebuild_index``, j'obtiens cette erreur : ``haystack.exceptions.SearchFieldError: The model '<Topic: JS vs jQuery>' combined with model_attr 'subtitle' returned None, but doesn't allow a default or null value.``.
Après un peu d'investigation, il s'avère que le topic en question n'a pas d'attribut "subtitle". Pourtant, il est marqué comme "null=True" dans le modèle.
Je n'ai pas le temps de faire une PR tout de suite mais je me l'assigne.

**Comment by DevHugo** [comment]
C'est uniquement avec les données de test. Il me semble.  Tu peux pas le reproduire en tant que membre de base.

Faudrait tester le cas ou tu met que None comme sous titre, si tu as le temps.

**Comment by vhf** [comment]
Si c'est un problème de fixture, faut régler les fixtures. Ajouter simplement un sous-titre vide dans les fixtures.

**Comment by Nautigsam** [comment]
Comme vous pouvez le voir [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/models.py#L169), le modèle est configuré avec "null=True" mais pas l'[index](https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/search_indexes.py#L16). Peut-être qu'il faudrait avoir pareil pour l'un et l'autre avant de modifier les fixtures.

**Comment by Nautigsam** [comment]
Up.

**Comment by DevHugo** [comment]
C'est quoi la question ?

Oui, y'a une incohérence on est tous d'accord. 

Le premier point est de corriger cette incohérence entre l'index et le modèle. Il faut aussi généré le fichier de migration correspondant pour la base de donnée (`python manage.py makemigrations`).

Le deuxième point est de corriger les fixtures.

Le troisième point est de savoir si on peut reproduire le souci en tant qu'utilisateur. Si oui, il faut fournir un script de migration pour mettre à jours les données dans la base de données de prod. 

Tu es un peu obligé de faire les trois points ensemble (dans la même pr) car sinon tu va pas pouvoir appliquer, je pense, le fichier de migration de la première étape.

**Comment by Situphen** [comment]
On n'utilise plus django-haystack et l'indexation des topics fonctionne bien avec elasticsearch donc je ferme.
