### ISSUE TITLE
Membre banni : mobile vs pc

### ISSUE THREAD

**Issue by finkiki** [zestedesavoir/zds-site#3977]
J'ai été banni il y a quelques jours. Malgré ça je reste connecté sur la version mobile (pas sur la version pc) et je peux continuer à envoyer des messages privés. Un admin m'a fait passer du groupe "Banni" au groupe "Dead" sans aucun effet visiblement : je peux toujours envoyer des messages privés.
Un membre banni devrait être automatiquement déconnecté.

**Comment by DevHugo** [comment]
On peut pas dire que tu sois rancunier ^^ . C'est en cours de résolution: [https://github.com/zestedesavoir/zds-site/pull/3976](https://github.com/zestedesavoir/zds-site/pull/3976).
