### ISSUE TITLE
Mettre à jour la liste des langages avec coloration syntaxique du site.

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#3984]
La liste des langages mis en exemple sur le site date un peu : 

HTML, CSS, Javascript, PHP, JavaFX, ColdFusion, Actionscript 3, Perl, SQL, XML, C, C++, C#, Java, Delphi, Python, Ruby, Pascal, Visual Basic, VB.NET, Bash, Diff, Erlang, Scala, Groovy, PowerShell, Autre

Je pense qu'un petit nettoyage ne ferai pas de mal. Je propose de virer ColdFusion, Actionscript 3, Delphi, Pascal, Visual Basic que je n'ai jamais vu sur le forum et datent un peu. Il est peu probable qu'un débutant vienne avec un problème là dessus. J'ai aussi des doutes sur JavaFX, Erlang, Scala, Groovy. 

En parallèle on peut en rajouter. Je pense en particulier à arduino qui est populaire sur le forum, notamment auprès des débutants et nouveaux. On pourrait aussi rajouter Haskell qui est assez utilisé par les membres.

On peut avoir la liste des langages supportés [sur le site de pygments](http://pygments.org/docs/lexers/).  Ce qui doit être inséré dans le markdown est le champ `Short`.

NB: J'en profite pour parler d'un ménage et virer les anciens mais en vrai le plus important pour l'ergonomie et le bien du forum est l'ajout d'arduino dans la liste.

**Comment by cgabard** [comment]
Au passage c'est probablement un issue facile pour un débutant qui veut se balader un peu dans le code.

**Comment by malnuxstarck** [comment]
Je m'en charge :D

**Comment by firm1** [comment]
>  JavaFX, Erlang, Scala, Groovy

Je ne sais pas pour Erlang, mais JavaFx, Scala et Groovy me seraient utile. Ce sont des technos vivantes et modernes.

Est-ce que ça nous coute quelque chose de supporter le trop de langage ?

**Comment by cgabard** [comment]
La question n'est pas de virer leur support mais de la liste de l'interface.

Si tu lis bien ma phrase, je ne les classes pas dans les vieux langages. Le but n'est pas de virer le support. Il est déjà possible de colorer l'arduino, simplement il n'est pas dans cette liste.

Fondamentalement on peut pas mettre tous les langages supportés (il y en a trop, cf la doc de pygments). Une liste trop pleine est pour moi plus compliqué pour les utilisateurs, en particulier les débutants qui viennent sur le site. La majorité des power-user n'utilisent probablement pas cette boite à outils.

J'ai rien contre le fait qu'on laisse ces 3 là (j'ai bien dit "j'ai des doutes sur...", mon avis est moins tranché) mais je pense qu'un peu de ménage améliorerai la visibilité. Sérieusement plus personne ne fait du VB6 ou ColdFusion.

Comme je l'ai dit **le plus important est d'ajouter arduino**. Mais la liste étant longue, on peut en profiter pour simplifier cette interface.

**Comment by firm1** [comment]
Ah, je crois que je n'avais pas bien compris ton issue. En fait l'idée est de modifier la liste qui est présente dans l'éditeur js. Je pensais que tu voulais le virer dans le markdown.

Je suis pour du coup, désolé.

**Comment by cgabard** [comment]
Oui, j'ai fait l'issue que pour l'éditeur js. Côté mardown c'est pigments
qui gère et j'ai aucune raison de les virer.

Non c'est vraiment pour l'éditeur, lui donner un petit coup de jeune à la
liste et rajouter ceux qui sont réellement utilisés sur le site.

**Comment by Fumble** [comment]
Je tiens à mon Delphi (et Pascal aussi du coup) !!! Çà peut être utile si quelqu'un a un problème avec l'installateur InnoSetup aussi. Mais je t'accorde que c'est très peu utilisé sur le fofo.

**Comment by cgabard** [comment]
Encore une fois, ça n'enlève pas le support du zmarkdown, juste de l'
interface. Après si tu y tiens on peut garder le Delphi mais garder les
deux à peu de sens

**Comment by WinXaito** [comment]
Mais il serait bien d'indiquer tous les langages disponibles  (ou au moins une liste plus complète que celle de l'éditeur) dans le poste de l'aide Markdown, car de mémoire on ne retrouve cette liste nul part.

**Comment by tleb** [comment]
> car de mémoire on ne retrouve cette liste nul part

Nul part sur ZdS. ~~Je pense qu'ajouter un lien sur l'article sur la rédaction en Markdown vers [le lien](http://pygments.org/docs/lexers/) posté par @cgabard est le plus simple. Ça évite de devoir tenir à jour la liste.~~

Edit : la liste est déjà cité, comme on peut s'y attendre, [ici](https://zestedesavoir.com/tutoriels/249/rediger-sur-zds/#6-4780_code).

**Comment by WinXaito** [comment]
Oui enfin on a un lien vers la liste, je trouve pas ça très pratique...

**Comment by tleb** [comment]
Je passe mon tour pour update la liste à chaque modif de pygments. :worried:

**Comment by Fumble** [comment]
Vu la longueur de la liste, mieux vaut garder le lien plutôt que de surcharger la page avec une liste de 10000 langages.

**Comment by cgabard** [comment]
D'autant qu'elle change à chaque version de pygments.

Ceci dit le plus important est l'éditeur pour les débutants et nouveau.
Pour les habitués ils peuvent trouver plus facilement. Les nouveaux doivent
trouver facilement ce qu'ils cherchent. D'où le fait que j'insiste pour
Arduino qui est très populaire par les nouveaux

**Comment by cgabard** [comment]
Une bonne petite modif serait que sous la liste il y ai un champ texte qui permet de trouver un langage par auto-completion.

Ce serait pas si compliqué, je peux faire une commande Django qui serait lancé à la mise en prod et qui produirait la liste des langages dispo de façon statique en js. Il y aurait juste à faire un peu dev js pour faire une recherche dedans.
