### ISSUE TITLE
Les fichiers statiques n'ont pas de header Expires

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#399]
Les fichiers statiques n'ont pas de header Expires, donc on fait systématiquement une requête au serveur pour savoir s'ils ont été modifiés.

Il faudrait leur mettre une date d'expiration dans un futur raisonnablement lointain.

**Comment by SpaceFox** [comment]
Dites, les gens qui font du design (soit @Alex-D pour la version future et @firm1  pour la version courante), vous avez des contraintes sur les dates d'expirations ?

Si je mets 1 an sur tout le contenu de /statics/, ça vous va ?

**Comment by Alex-D** [comment]
Au début, il faut mieux prévoir une courte durée, car on va beaucoup mettre
à jour je pense...

**Comment by firm1** [comment]
Tout pareil qu'Alexandra.

**Comment by SpaceFox** [comment]
Définis "courte durée" ?

**Comment by Alex-D** [comment]
Ah bah clairement au début faut mettre 1 semaine à tout casser...

Est-ce que django permet de suffixer le nom du script genre "main.v5.css"
qui ira chercher "main.css" ? Si oui, du coup tu peux mettre 1 an, sinon, 1
semaine.

**Comment by firm1** [comment]
> Est-ce que django permet de suffixer le nom du script genre "main.v5.css"

On va éviter de versionner les css.

De toute façon ça se paramètre via nginx, donc, je propose qu'on démarre carrément sans header-expire (ou sur 3 jours) et on l'étend au fur et à mesure à 1 semaines, puis 1 an.

Ce sont des paramètres nginx, donc ça se change de manière transparente.

**Comment by Alex-D** [comment]
Je proposais simplement une alternative pour éviter les "héé le design bug
là" - "vide ton cache" - "ah ouais c'est bon".

Donc j'ai même tendance à dire : au début, 1 jour.

**Comment by SpaceFox** [comment]
1 jour sur statics et media, c'est fait.

On étendra au fur et à mesure de l'avancée du design, l'important est qu'on ne recharge pas systématiquement ces pages (ou au moins qu'on ne fasse pas systématiquement une requête pour vérifier si elle a changé ou non).
