### ISSUE TITLE
[tribunes] Gestion des auteurs des billets

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3996]
#3993 

Reproduire : 

1. Créer un billet, y ajouter Clem comme auteur, publier le billet
2. S'enlever des auteurs
3. On est toujours dans les auteurs, mais le billet n'est plus listé dans ses billets

**Comment by AmarOk1412** [comment]
D'ailleurs c'est moi ou ça marche aussi pour les tutos/mps ?

EDIT: je confirme pour moi ça se fait sur MP/Tutos (articles aussi je suppose) ce qui en soit est moins génant vu que c'est pas public en premier temps contrairement aux billets

**Comment by artragis** [comment]
C'est commun à tous les contenus : lorsqu'un contenu est publié, un "snapshot" est réalisé. C'est donc une vraie décision que de dire : 

- est-ce que quitter la rédaction <=> quitter la version publique (repentance etc.)
- est-ce que quitter la rédaction <=> je ne serai plus considéré comme auteur des futures versions?

À vous les studios.

**Comment by pierre-24** [comment]
Et revient à la discussion sur le *versionning* de certaines informations ;) (les auteurs, en l’occurrence)

**Comment by artragis** [comment]
bah pour le coup les auteurs sont versionnés, car ça embêtait les gens 
qu'ils ne le soient pas...

**Comment by vhf** [comment]
Fermé par #4039
