### ISSUE TITLE
ImportError with GeoIP

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#40]
Hello,

La version actuelle sur la branche `master` ne fonctionne pas, il manque la dépendance `GeoIP` : `ImportError: cannot import name GeoIP`.

Sur Mac, j'ai du installer la dépendance grâce à la commande `brew install geoip` mais j'en ai aucune idée pour les autres plateformes.

Faudrait le rajouter dans les dépendances pré-requis.

**Comment by firm1** [comment]
C'est cheulouh.

C'est [censé être inclus](https://docs.djangoproject.com/en/dev/ref/contrib/gis/geoip/) dans django normalement. En tout cas chez moi (ubuntu) et sur le serveur de prod (debian) je n'ai pas eu besoin d'installer quoique ce soit.

Surtout que le code `from django.contrib.gis.geoip import GeoIP` laisse penser qu'il est déjà dans django de base.

J'ai du mal a voir en google le problème de surface sur google.

**Comment by GerardPaligot** [comment]
Oui, effectivement. Faudrait tester sur Windows pour voir si ça fonctionne ou pas.

**Comment by firm1** [comment]
+1

**Comment by GerardPaligot** [comment]
Je re-ouvre l'issue :
- Alex a le problème d'import sur Windows.
- Cela veut dire que les futurs contributeurs ont de grandes chances de l'avoir aussi.

**Comment by firm1** [comment]
Je pense que c'est l'occasion de lire la doc [de ce coté](https://docs.djangoproject.com/en/dev/ref/contrib/gis/install/#windows) pour installer ce qu'il faut.

**Comment by GerardPaligot** [comment]
Ouaip, il est dessus. Faudrait juste penser à gérer son installation pour les futurs contributeurs. Au moins indiquer le lien vers la documentation.

**Comment by Alex-D** [comment]
Plop ! J'ai bien entendu lu la doc, mais c'est vraiment compliqué pour pas grand chose.

Je propose du coup d'utiliser pygeoip qui est en python pur, tandis que django-geoip est un wrapper pour geoip C (langage C).

https://pypi.python.org/pypi/pygeoip/

Je ne sais pas ce que tu en pense @firm1 mais ça me semble judicieux.

Par ailleurs, un peu HS mais dans le même ordre : fabric ne veut pas s'installer chez moi.

**Comment by cgabard** [comment]
Sur arch j'ai dut aussi installer a part.

Après l'avantage de la version C est évidemment es perfs. Mais si les 2 ont une interface commune, on peut tenter d'inclure la version python si la version c n'est pas dispo

**Comment by Alex-D** [comment]
Sinon, plus simplement désactiver la GeoIP (pas spécialement important en dev) sur Windows (si la lib est pas installée quoi).

**Comment by firm1** [comment]
J'ai tendance en général à préférer les package conseillés officiellement par Django. Du coup, je pense qu'on restera sur GeoIp.
Si son installation est bien documenté ça ne devrait pas poser de problème. Je comptais sur le prochain dev qui installerait ça sur Windows pour décrire la procedure d'install, mais quelque chose me dis qu'il va falloir que je switche dessus pour la documenter proprement.

A terme on aura un script qui installe automatiquement toutes les dépendances, donc ça devrait aller, pas la peine de désactiver ça.

**Comment by Alex-D** [comment]
Mettons nous d'accord :
1. Je suis un dev
2. Je suis sur Windows
3. Tu n'es pas obligé de prendre le melon, chacun ici sait faire une doc de procédure d'install, encore faut-il qu'on y arrive nous même

C'est la même procédure, à part que GeoIP n'est pas installé sur Windows et que fabric bug également. Donc il n'y a pas de doc à faire, simplement utiliser des libs multiplateformes.

Donc, moi ce que je constate c'est que quand je cherche sur le web, il est conseillé d'utiliser pygeoip qui est en python est donc forcément multiplateforme et non-dépendant de l'API C.

**Comment by firm1** [comment]
Tu m'avais l'air de dire que c'est assez compliqué à installer sur Windows, raison pour laquelle je me dit qu'il faut donc documenter pour le jour le code sera ouvert.

Après pygeoip vs geoip, je n'ai pas trop d'avis à part qu'il y'en a une qui est référencé dans la doc django officielle et l'autre non. On peut aussi changer de package, mais bon, si GeoIp suffit amplement, est-ce que c'est une priorité ?

**Comment by cgabard** [comment]
Quels sont les probs de geoip sous windows ? C'est quoi qui t'a bloqué dans la procédure d'installation ?

**Comment by firm1** [comment]
Comme je l'ai mentionné, quand j'aurai un PC de dev windows à ma disposition (pas avant cette nuit). Je m'occuperai de faire un doc propre dédiée aux spécificités de Windows & MAC. Il n'y aura donc plus de problème bloquant à ce niveau. En attendant, on peut toujours utilisé le patch de @cgabard .

**Comment by firm1** [comment]
C'est fixé, c'est mergé, donc je ferme.
