### ISSUE TITLE
Les fichiers statiques ne sont pas gzippés

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#400]
Les JS et CSS ne sont pas gzippés.
Par contre, le HTML l'est.

**Comment by SpaceFox** [comment]
C'est fait.

**Comment by firm1** [comment]
Hmm, sur la prod on dirait que c'est pas gzippé. C'est pourtant gzippé sur la preprod.

**Comment by Alex-D** [comment]
Déplacé en interne.
