### ISSUE TITLE
Le compte des messages modérés prend en compte les messages automasqué

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#4001]
Il y a pleins de cas dans la vie de zds où une personne peut masquer un de ses messages (exemple : un tutoriel en béta test, on peut vouloir marquer certaines mise à jour de béta pour plus de lisibilité). Pourtant ces messages sont comptabilisés comme "modérés" dans le profile.

**Comment by vhf** [comment]
Merci à tous !
