### ISSUE TITLE
Ajouter un bouton au menu messagerie pour envoyer un MP

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#4008]
Actuellement, pour envoyer un MP il faut d'abord cliquer sur le bouton de messagerie, puis *toutes les conversations*, puis *Nouvelle conversation*.

Pour simplifier cela, on pourrait ajouter un bouton au menu de messagerie pour envoyer un message privé. Je pense à quelque chose comme ça :

![](http://i.imgur.com/BG6ADbh.png)

**Comment by malnuxstarck** [comment]
Salut ! Est ce que tu peux poster sur le forum suggestions , beaucoup de mondes pourra ainsi donner un avis . Merci :) [Ici](https://zestedesavoir.com/forums/communaute/bug-suggestions/)

**Comment by Emeric54** [comment]
@malnuxstarck Étant donné que c'est une bonne idée d'évolution, ce n'est pas nécessaire.

**Comment by vhf** [comment]
Je vais créer un tag "PO review" pour que le PO ait un point d'entré sur le repo. Ce fonctionnement est sujet à modification, et le nom du tag aussi. Ce poste est nouveau et on ne sait pas encore quel le sera le meilleur moyen de collaborer. Pour le moment on va faire comme ça.

**Comment by lypwig** [comment]
> Salut ! Est ce que tu peux poster sur le forum suggestions , beaucoup de mondes pourra ainsi donner un avis . Merci :) Ici

Ah oui, [bonne idée](https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=39#p115114) ;)

> Je vais créer un tag "PO review" pour que le PO ait un point d'entré sur le repo. Ce fonctionnement est sujet à modification, et le nom du tag aussi.

Comprend pas.

**Comment by vhf** [comment]
Sur ZdS, nous avons décidé d'avoir un PO, ça a été discuté ici : https://zestedesavoir.com/forums/sujet/7185/frankenstein-nous-guette/

Pour qu'il puisse prendre ses fonctions en douceur, j'ai créé un tag que j'ai nommé `PO feedback`, comme tu vois entre mon dernier commentaire et ton dernier commentaire. Le nom de ce tag est sujet à modification. Le fonctionnement de la collaboration entre PO et DTC est également sujet à modification.

**Comment by lypwig** [comment]
Aaaah mais faut lui trouver un autre nom à ce type là, moi PO ça me fait direct penser à Post Original (aka OP en anglais), du coup je comprenais plus rien... (d'ailleurs [j'avais proposé RIP](https://zestedesavoir.com/forums/sujet/7185/frankenstein-nous-guette/?page=3#p129304) :P)

**Comment by FanJiyong** [comment]
Yop yop, 

Ok sur le principe. 

Par contre pour moi le bouton n'est pas bien placé. 
1. Je pense que le bouton "toutes les conversations" doit rester en bas. 
2. Je pense qu'il serait préférable d'ajouter une icônes sur ce nouveau bouton 
3. Je mettrais bien ce bouton en haut, en face de "Messagerie privée"

Y'a pas de message sur le forum qui concerne cette fonctionnalité. Tu t'en charge Roipoussiere ? ou OSEF ?

**Comment by lypwig** [comment]
> Y'a pas de message sur le forum qui concerne cette fonctionnalité.

[Si](https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=39#p115114).

**Comment by FanJiyong** [comment]
Pardon mais je parlais d'un topic à part… comme c'est une nouvelle fonctionnalité de ce menu il me semblais pas mal d'éviter de flooder "Les petits pixels... " et de "présenter"/avoir un retour, sur cette nouvelle fonctionnalité, à la communauté :)

**Comment by FanJiyong** [comment]
Comme je disais plus haut, je trouve que le placement de la proposition ci-dessus n'est pas bon. 

Dans le but de faire avancer cette fonctionnalité, je reviens vers vous avec une nouvelle, proposition de placement et déclinaison en version : full text;  full icone; text image.

![161212_nouveau_mp_img](https://cloud.githubusercontent.com/assets/15154100/21102670/5ac19382-c07f-11e6-8620-c3ff553f0136.png)
![161212_nouveau_mp_txt](https://cloud.githubusercontent.com/assets/15154100/21102671/5ac219a6-c07f-11e6-86bd-c69a48eba7b6.png)
![161212_nouveau_mp_img_txt](https://cloud.githubusercontent.com/assets/15154100/21102672/5ac28f30-c07f-11e6-906c-1b2edd45029c.png)

En attentes de vos retours.

**Comment by lypwig** [comment]
J'aime bien la première avec l’icône.

**Comment by cgabard** [comment]
Pareil perso, c'est compact et compréhensible

**Comment by malnuxstarck** [comment]
On y va pour le premier 😊

**Comment by Anto59290** [comment]
@FanJiyong Si tu héberge le picto quelque part je m'en occupe. Ping moi quand c'est bon ;)

**Comment by FanJiyong** [comment]
@Anto59290 et voilà :)
[icone_new_mep.zip](https://github.com/zestedesavoir/zds-site/files/657299/icone_new_mep.zip)

edit : ok pour l'icone mais n'oubliez pas de mettre une tooltip svp.

**Comment by Anto59290** [comment]
Bien reçu. Je note pour le tooltip.

**Comment by FanJiyong** [comment]
Ca serait possible a terme de garder les notifications dans le menu qui s'ouvre ?
Ca a déjà était proposé ? 

C'est un peu anti-ergonomique le double clique pour pouvoir revoir une ancienne notification. 

C'est une question ouverte hein, tout changement dans ce sens fera l'objet d'une nouvelle issue.

**Comment by Anto59290** [comment]
Tu veux dire afficher les anciennes notifs dans le menu déroulant ? Oui c'est probablement possible. Après je trouverais ça un peu déroutant. Par exemple sur GH ça fonctionne pareil que sur ZDS : 

- 1 clic = nouvelles notifs
- en naviguant on à accès aux autres notifs.

**Comment by lypwig** [comment]
> Ca serait possible a terme de garder les notifications dans le menu qui s'ouvre ?

Gros +1. Par contre on pourrait afficher les anciennes notifs dans une autre couleur, genre un semi transparent ou un peu grisé.

Je proposais également [ici](https://zestedesavoir.com/forums/sujet/7546/petite-suggestion-concernant-les-notifications/#p134786) de pouvoir marquer les notifs comme non-lues.

**Comment by FanJiyong** [comment]
> Tu veux dire afficher les anciennes notifs dans le menu déroulant ? Oui c'est probablement possible. Après je trouverais ça un peu déroutant. Par exemple sur GH ça fonctionne pareil que sur ZDS 

Ouais mais même sur GH ça me gave (ouais carrément). Je fait peut-être une catachrèse de cette fonctionnalité, mais j'apprécierais vraiment de pouvoir revenir sur issue, après avoir réalisé une maquette ou réfléchi murement à la problématique…

> en naviguant on à accès aux autres notifs.
Ha bon ? Moi j'ai plus rien après. 

> Gros +1. Par contre on pourrait afficher les anciennes notifs dans une autre couleur, genre un semi transparent ou un peu grisé.

Sans revenir totalement sur la couleur, ce bleu a cette endroit est pour moi une hérésie totale !… en blanc ça aurait peut-être était mieux. A voir. 

> Je proposais également ici de pouvoir marquer les notifs comme non-lues. 

Oui totalement. 

Pour moi tu as : 
- Marquer comme lu/non lu (soit l'ensemble / soit sur une notif a voir) 
- Créer une nouvelle conversation. 
- Supprimer (lié a une notification)

**Comment by Anto59290** [comment]
Pour moi ce ticket a atteint son objectif depuis le merge et peut donc être fermé. Si nouvelle itération il doit y avoir sur ce menu déroulant je pense que ça aurait ça place dans un nouveau ticket (avec une maquette, si possible).
