### ISSUE TITLE
last_visit dans GET /api/membres/

### ISSUE THREAD

**Issue by tleb** [zestedesavoir/zds-site#4009]
Pourquoi es-ce qu'il n'y a pas de champ `last_visit` dans `GET /api/membres/` ? C'est pourtant une info publique qui est accessible sur la page de profil. C'est disponible pour `GET /api/membres/mon-profil/`.

**Comment by DevHugo** [comment]
@pierre-24 @tleb , on peut fermer le ticket, je pense !

**Comment by pierre-24** [comment]
de fait :)

**Comment by DevHugo** [comment]
Merci !
