### ISSUE TITLE
Les fichiers statiques devraient être sur leur propre sous-domaine

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#401]
Les fichiers statiques devraient être sur leur propre sous-domaine :
- Meilleure séparation
- Pas de cookies sur le domaine des fichiers statiques

**Comment by geoffreyc** [comment]
Cotes Nginx c'est simple a faire, cotes django c'est tout aussi simple ou
pas?

2014-05-02 13:26 GMT+01:00 SpaceFox notifications@github.com:

**Comment by SpaceFox** [comment]
Il me semble de mes premières lectures de la doc Django, que celui-ci est
conçu pour ça.
Mais ça reste à vérifier.

**Comment by SpaceFox** [comment]
Ressources :
https://docs.djangoproject.com/en/1.6/howto/static-files/
https://docs.djangoproject.com/en/1.6/howto/static-files/deployment/

**Comment by SpaceFox** [comment]
Je suppose du coup que les issues #399 et #400 sont liées à celle-ci : une fois sur leur sous-domaine propre, les ressource statiques pourraient être plus finement configurées.

**Comment by cgabard** [comment]
Encore d'actualité ?

**Comment by firm1** [comment]
> Encore d'actualité ?

Oui

**Comment by Situphen** [comment]
Si je résume, il faut :
- créer le sous-domaine `static` ;
- lors d'une prochaine MEP, configurer `settings_prod.py` et _nginx_ pourque ça fonctionne.

Est-ce qu'il ne faudrait pas aussi créer un sous-domaine pour `media` ?

**Comment by firm1** [comment]
> Est-ce qu'il ne faudrait pas aussi créer un sous-domaine pour media ?

Mauvaise idée. On a des urls existantes qui contiennent ce média dans leur nom

**Comment by Situphen** [comment]
> > Est-ce qu'il ne faudrait pas aussi créer un sous-domaine pour media ?
> 
> Mauvaise idée. On a des urls existantes qui contiennent ce média dans leur nom

Redirection ?

**Comment by firm1** [comment]
> Redirection ?

Pas si évident que tu peux le penser avec les urls relatives.

**Comment by Situphen** [comment]
Bah relative ou non, ce n'est pas l'url qui compte, c'est la requête. et quand `zestedesavoir.com/media` arrive sur le serveur, il la redirige vers `media.zestedesavoir.com`, non ?

**Comment by firm1** [comment]
En théorie oui, mais en pratique il faudra je pense vérifier dans le code si on a pas quelque chose qui fait des vérification là dessus. Là comme ça en tête je pense à l'import des tutoriels externe avec images ou encore le cas de l'url des avatars.

**Comment by ghost** [comment]
Ne pas oublier qu'en cas de sous domaine différent, pour le HTTPS, il faut que le certificat soit valide. Le fait d'avoir un sous-domaine différent est beaucoup utilisé, mais dans le cas où c'est le même serveur qui sert le contenu static et le contenu dynamique, j'ai du mal à voir l'intérêt si ce n'est cette augmentation des coûts.

**Comment by artragis** [comment]
encore d'actualité? c'est vrai que ça serait énorme pour les pefs de zds ça.

**Comment by SpaceFox** [comment]
@Un-Cornichon je suppose que nos certificats HTTPS actuels ne sont pas valides pour les sous-domaines ?

**Comment by ghost** [comment]
Effectivement @SpaceFox, pour ça il faudrait prendre des certificats de type wildcard, et c'est tout de suite plus le même budget. Chez Gandi on est par exemple à 120€.
Je me permets cependant de réafirmer mes doutes vis à vis de la nécessité d'un sous domaine pour les contenus statics, puisque ceux ci sont servis par le même serveur que les contenus dynamiques. J'ai du mal à voir l'usage et la meilleur séparation que ça apporte par rapport à un ndd.tld/static/.

**Comment by SpaceFox** [comment]
Le principal avantage, si tu n'as qu'un serveur, c'est que tu ne te trimbales pas les cookies sur les statics. Mais c'est tellement mineur par rapport aux certificats que c'est inutile de se lancer là-dedans, alors je ferme.
