### ISSUE TITLE
Notification persistante

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#4011]
Bonjour,

Je n'ai pas retrouver l'issue du problème, donc j'ouvre celle  ci pour être sûr que j'ai été "victime" du même bug.

Un sujet à été créer  (https://zestedesavoir.com/forums/sujet/7416/probleme-de-securite-sur-le-tutoriel-creez-une-api-rest-avec-symfony-3/) et j'ai été notifier car je suis abonné au forum en question, et comme le sujet mène sur une 403, ma notification me pars plus...

**Comment by artragis** [comment]
en cours de correction sur #3954

**Comment by pierre-24** [comment]
À priori ok :)

**Comment by WinXaito** [comment]
@vhf Vous avez touché quelque chose ? (Aujourd'hui ou hier je ne sais pas), car ma notification persistance a disparu.

**Comment by vhf** [comment]
J'ai supprimé toutes les notifs persistantes sur la prod il y a 2h.
