### ISSUE TITLE
[Préparation py3] Préparer nos classes de modèles pour qu'elles aient un __str__

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#4013]
Utilisation de `__future__.unicode_literals` et de `@python_2_unicode_compatible`.

Cela permettra d'adoucir la migration vers py3 et c'est pas compliqué à faire.

Merci de me l'assigner. (@vhf @gustavi )

**Comment by artragis** [comment]
2 be closed @pierre-24

**Comment by pierre-24** [comment]
*Just* ;)
