### ISSUE TITLE
Tutoriel sans auteur

### ISSUE THREAD

**Issue by rezemika** [zestedesavoir/zds-site#4014]
Le tutoriel sur la formation du système solaire semble être dépourvu d'auteur. Dans le tuto en lui-même, la ligne listant les auteurs est vide, et aucun n'apparait non plus quand on le regarde depuis la liste des tutos.

Voilà le lien : https://zestedesavoir.com/tutoriels/378/la-formation-du-systeme-solaire/

![capture d ecran_2016-11-25_14-45-46](https://cloud.githubusercontent.com/assets/1690660/20627114/51baedba-b31e-11e6-8989-03d9c21d7e8c.png)

![capture d ecran_2016-11-25_14-45-31](https://cloud.githubusercontent.com/assets/1690660/20627102/37c9c408-b31e-11e6-82cb-0d797d8bb010.png)

**Comment by artragis** [comment]
Existant [ici](https://github.com/zestedesavoir/zds-site/issues/3680) et corrigé pour la v21 (à ajouter dans "version de développement" @vhf.
