### ISSUE TITLE
Tests super longs à se lancer; utiliser pytest ?

### ISSUE THREAD

**Issue by gasche** [zestedesavoir/zds-site#4018]
## Le contexte

Sur ma machine un test de `zds/gallery/tests/tests_views.py`
échoue. J'aimerais comprendre le problème mais pour cela j'ai besoin
de pouvoir lancer les tests souvent pour voir ce qui se passe.

(De manière générale c'est important que les tests soient facilement
lançables et un peu adaptables/spécialisables/configurables par les
contributeurs infréquents qui ne comprennent pas la vue d'ensemble du
code du site ou Django.)

## L'existant

Les seuls conseils que je trouve en jouant avec "make" c'est `make
test`, qui lance `python manage.py test`. Ça ne dit pas comment faire
pour lancer juste un des tests possibles, mais j'ai cherché un peu et
on peut faire

```
python manage.py test zds.gallery.tests.tests_views
```

... sauf que c'est toujours super long. Du coup je mets l'option de verbosité `-v 3` et je vois

```
Checking '/home/gasche/Prog/zds-site' for fixtures...
No fixture 'initial_data' in '/home/gasche/Prog/zds-site'.
[...]
Checking '/home/gasche/Prog/zds-site' for fixtures...
No fixture 'initial_data' in '/home/gasche/Prog/zds-site'.
Running migrations:
  Rendering model states... DONE (19.291s)
  Applying contenttypes.0001_initial... OK (0.009s)
  Applying auth.0001_initial... OK (0.036s)
  Applying admin.0001_initial... OK (0.020s)
  [...]
  Applying utils.0003_auto_20150414_2256... OK (0.234s)
  Applying utils.0004_auto_20151229_1904... OK (1.334s)
  Applying utils.0005_commentvote... OK (1.322s)
  Applying utils.0006_auto_20160509_1633... OK (0.416s)
  Applying utils.0007_auto_20160511_2153... OK (0.412s)
  Applying utils.0008_auto_20161112_1757... OK (1.745s)
  Applying utils.0009_auto_20161113_2328... OK (0.255s)
Running post-migrate handlers for application auth
Adding permission 'auth | permission | Can add permission'
Adding permission 'auth | permission | Can change permission'
Adding permission 'auth | permission | Can delete permission'
[...]
test_fail_member_no_permission_can_edit_gallery (zds.gallery.tests.tests_views.EditGalleryTestView) ... ok
test_fail_member_read_permission_can_edit_gallery (zds.gallery.tests.tests_views.EditGalleryTestView) ... ok
[...]
test_success_new_image_write_permission (zds.gallery.tests.tests_views.NewImageViewTest) ... ok

----------------------------------------------------------------------
Ran 37 tests in 7.920s

OK
Destroying test database for alias 'default' (':memory:')...
```

19 secondes pour créer les modèles (je ne sais pas trop ce que c'est
et à la rigueur ça m'est égal), c'est super long! Au total le test
prend 51 secondes, dont on dirait seulement 8 secondes en vrai tests
et tout le reste en migration de données. J'aimerais pouvoir itérer
sur le code pour comprendre ce qui se passe (genre mettre des print de
débug à la sale etc.) et lancer le code rapidement, donc le test ne
devrait pas prendre plus de quelques secondes.

## Recherche

En cherchant sur Google je trouve une discussion reliée sur
StackOverflow:
[Django Unit Testing taking a very long time to create test database](http://stackoverflow.com/questions/36487961/django-unit-testing-taking-a-very-long-time-to-create-test-database)

Il y a deux réponses qui donnent des recommandations différentes. La
première conseille d'utiliser `pytest`, alors j'ai fait `pip install
pytest` (il me met pytest 3.0.4) et puis

```
DJANGO_SETTINGS_MODULE=zds.settings_test_local pytest --nomigrations zds/gallery/tests/tests_views.py
```

et là c'est instantané en comparaison: le test tourne en
6 secondes. (Sans l'option `--nomigrations` c'est à nouveau aussi
lent.) D'après la réponse on peut aussi mettre ces options dans un
fichier `pytest.ini` que je serais heureux de contribuer si ça vous
semblait être une bonne solution.

La deuxième solution proposée, qui est de la forme
`MIGRATION_MODULES = DisableMigrations()`, ne marche pas sous ma
machine: si je rajoute ça dans les settings locaux ça échoue avec
l'erreur suivante:

```
AttributeError: 'Settings' object has no attribute 'OAUTH2_PROVIDER_APPLICATION_MODEL'
```

## Et maintenant ?

Est-ce qu'il y a une autre façon de rendre les tests moins
horriblement lents qui est moins invasive ? Est-ce que le fait de
faire tourner des migrations à chaque test local est essentiel ?
Sinon, est-ce que j'essaie de proposer une pull-request qui met
`pytest` dans les dépendances et qui configure tout bien et utilise
`pytest --nomigrations` à la place de `python manage.py test` dans les
cibles de test du Makefile?

**Comment by pierre-24** [comment]
Y'a [d'autres options](http://pytest-django.readthedocs.io/en/latest/database.html), mais effectivement, pourquoi pas :) @vhf ?

**Comment by gasche** [comment]
Quand tu dis "d'autres options", qu'est-ce que tu as en tête ? J'ai essayé de jouer avec `--reuse-db` mais chez moi ça n'accélère rien du tout, comme `--keepdb` côté `manage.py test`.

J'enverrai une PR quand j'aurai du temps.

Sinon, pas lié, mais si vous avez un avis à donner sur le topic [Organiser un défi ou sprint "première contribution au code de ZdS" ?](https://zestedesavoir.com/forums/sujet/7440/organiser-un-defi-ou-sprint-premiere-contribution-au-code-de-zds/).

**Comment by pierre-24** [comment]
> Quand tu dis "d'autres options", qu'est-ce que tu as en tête ? J'ai essayé de jouer avec --reuse-db mais chez moi ça n'accélère rien du tout, comme --keepdb côté manage.py test.

Ben ça m'as l'air de juste accélérer quand on lance plusieurs fois le même test, comme dans une situation ou tu crée ou corrige un test par essais-erreur :) (donc pas forcément à mettre dans `make`, quoique).

**Comment by gasche** [comment]
Non, ça n'accélère pas sur ma machine, les migrations ont toujours lieu même la deuxième fois. Est-ce que ça marche chez toi ou c'est juste ce que dit la doc (moi aussi j'y ai cru) ?

**Comment by pierre-24** [comment]
Je dis ça totalement sans avoir testé ;)

**Comment by SpaceFox** [comment]
Ça a fonctionné, je me suis servi de --keebdb entre autres pour pouvoir
vérifier l'état final de la base après des tests.

2016-11-28 17:46 GMT+01:00 Gabriel Scherer <notifications@github.com>:

**Comment by vhf** [comment]
Salut @gasche ! Pour lancer les tests en local seulement sur certaines apps, y'a une doc sommaire ici : https://zds-site.readthedocs.io/fr/latest/utils/tox.html?highlight=tox#les-tests-back-end (J'ai pas testé, je lance les miens plutôt comme ça : `python manage.py test --failfast --settings zds.settings_test_local zds.tutorialv2`)

On est super ouverts à n'importe quelle PR accélérant les tests. C'est très important et c'est un point qu'on néglige actuellement, aucun doute.

J'ai toujours pas publié la roadmap des grands chantiers de choses idéales, mais ce ticket me la rappelle. Notamment parce que se débarrasser de pandoc serait un grand pas en direction d'avoir une suite de tests qui passe bien en local.

**Comment by gasche** [comment]
En fait j'ai commencé à préparer une pull-request pour `pytest` mais, alors que `pytest .../test_foo.py` marche pour pas mal de test, lancer tous les tests avec `pytest` échoue avant d'arriver aux tests (`--nomigrations` ou non); je ne suis pas allé plus loin pour l'instant.
