### ISSUE TITLE
MathJax nous fait télécharger une masse de JS

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#402]
MathJax nous fait télécharger une masse de JS (500 ko pour 11 JS), y compris sur la home (!)

Une première approche serait de ne l'activer que sur les pages où il y en a _potentiellement_ besoin (topics, articles, tutos).

Une meilleure approche (mais qui me paraît très compliquée) serait de ne l'activer que sur les pages où il y en a _effectivement_ besoin. Mais comment déterminer ce besoin ?

**Comment by firm1** [comment]
Il faudrait aussi discutter de l'intéret de [toutes les extensions MathJax actuelles](https://github.com/Taluu/ZesteDeSavoir/blob/dev/templates/source.html#L360).

**Comment by Alex-D** [comment]
Il faudrait tout simplement télécharger les fichiers nécessaires et les mettre sur notre serveur. Après quoi il suffit de passer dans la moulinette de compression déjà en place (en tous cas sur la branche intégration).

**Comment by SpaceFox** [comment]
Pas la peine : les fichiers sont sur un CDN, minifiés et gzippés. Là où on
a besoin de les télécharger, on ne peut pas faire mieux.

**Comment by Alex-D** [comment]
Si, on peut les unifier.

1 requête c'est mieux que 11. Sauf si je me trompe bien sûr.

**Comment by cgabard** [comment]
Sinon il y a aussi la possibilité d'utiliser autre chose que matjax, en particulier produire des png de l'equation en passant par tex.

**Comment by Alex-D** [comment]
Le serveur va prendre cher...

**Comment by cgabard** [comment]
Bin je ne sais pas, je rajoute une possibilité... Apres le serveur prendrait cher, oui, mais une seule fois, a la génération ! Apres une fois en cache, tu t'en fout...

**Comment by amorison** [comment]
Surtout, le résultat est pas terrible : non vectoriel, accessibilité moins bonne pour les non-voyants, pas la possibilité de chopper le code TeX pour l'utilisateur...

**Comment by Alex-D** [comment]
Je pensais en effet au TeX non récupérable en soi, tu pointes là d'autres points importants.

MathJax n'est pas mauvais, il faut juste concaténer toutes les extensions ou quelque chose comme ça.

**Comment by firm1** [comment]
Si j'en crois [ceci](http://progdupeu.pl/forums/sujet/417/accessibilite-de-pdp-aux-lecteurs-decran?page=1)

> Le site qui à ce jour rend les formules mathématiques les plus accessibles n'est autre que wikipedia. Peut-être que vous pouvez vous en inspirer.

Par simple curiosité, quelqu'un sait comment Wikipedia le fait ? C'est pas du Tex par hasard ?

**Comment by cgabard** [comment]
Chez moi Wikipedia c'est une image + le code tex dans le alt !

**Comment by cgabard** [comment]
> MathJax n'est pas mauvais, il faut juste concaténer toutes les extensions ou quelque chose comme ça.

Je pense déjà comme le dit firm1 qu'il faut virer les extensions inutiles !

**Comment by Alex-D** [comment]
On peut passer sur du PNG + alt alors, moi ça me va. En effet, à coup de cache ça devrait le faire largement je pense.

**Comment by amorison** [comment]
Sur Wiki, l'accessibilité n'est garantie que parce que le code n'est pas transfo automatiquement en PNG... (http://fr.wikipedia.org/wiki/Aide:Formules_TeX) 

Mais Mathjax est accessible directement sans bidouillage de notre part.
http://www.mathjax.org/resources/articles-and-presentations/accessible-pages-with-mathjax/

Après, ce n'est que mon avis, faites comme vous voulez. Mais je trouve ça un peu dommage de se priver du vectoriel...

**Comment by Alex-D** [comment]
Bon, j'ai regardé la doc, j'ai regardé les forums, et j'ai analysé ce que fait tout ce bouzin.

Le résumé de l'histoire : 
- Le CDN est très bien configuré, c'est donc un peu long la première fois, le reste du temps c'est rapide puisque le cache est réglé à fond
- Les JS sont chargés à moins de 1s du lancement du chargement de la page en moyenne (quand c'est pas la première fois)
- La totalité des extensions, sur ma connexion pourrie se charge en mois d'une demie-seconde, ce que je trouve acceptable sachant que c'est asynchrone et que ça ne bloque en rien la navigation
- Le plus long à charger c'est le "core" mais ça on ne peut pas faire mieux

Ma conclusion c'est qu'on ne peut rien faire de mieux qu'actuellement, à part éventuellement virer des extensions potentiellement inutiles qui nous feront gagner quelques ko au premier chargement, mais rien de visible en tous cas.

Du coup, à part si vous avez une solution de fou qui sait détecter quand il y a besoin de MathJax qui alors va charger MathJax qui va lui même télécharger le core puis le core va DL les extensions (là ça va prendre des plombes et ça va être visible) je pense qu'on a déjà un fonctionnement optimal de la chose.

Les PNG sont une fausse solution : MathJax il est en cache, il sert partout. Les PNG il faudrait les charger à chaque utilisation de TeX, ce qui est beaucoup plus lourd au bout de quelques pages (voir une seule page d'un tuto mathématiques).

**Comment by SpaceFox** [comment]
OK, merci pour cette analyse. Je ferme, on réouvrira si on a un problème.
