### ISSUE TITLE
[v21] La sidebar est cassée sur mobile

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4020]
Téléphone galaxy S6
Navigateur : Chrome

La sidebar s'affiche maintenant dans la page. 

### screen

![screenshot_20161129-163148](https://cloud.githubusercontent.com/assets/6066015/20716196/b3a7cbac-b651-11e6-98f5-41d74e1cc0b6.png)

**Comment by WinXaito** [comment]
C'est comme si le JS avait disparu. (Car si on regarde bien, sur le site standard on a cet affichage la un court instant et ensuite le js remet tout en place). 

Et j'ai aussi testé pareil chez moi. (Chrome android [Edit: En fait j'ai le même tel que @firm1]).

(Ps: C'est nouveau "scaleway.zestedesavoir.com" ?)

**Comment by WinXaito** [comment]
Ah et pour ceux qui on `Edge`, je vous invite à testé la fonction d'émulation pour les Windows Mobile, c'est une catastrophe si on compare au site en Prod...
