### ISSUE TITLE
[v21] Mauvais affichage des topics

### ISSUE THREAD

**Issue by AmarOk1412** [zestedesavoir/zds-site#4022]
![Vu sur la beta](https://zestedesavoir.com/media/galleries/419/cae50898-d758-4df6-bed4-0caf68ebb538.png)

l'erreur est dans assets/scss/components/_topic-list.scss, par contre faut trouver une solution qui s'affiche bien pour la page forum et la page profil.

**Comment by pierre-24** [comment]
Y'a beaucoup de chances que ce sois du à l'histoire des étoiles pour le suivi, donc par là.

**Comment by AmarOk1412** [comment]
En fait sans les étoiles devant le sujet, le résultat était bon côté forum, mais pas tout à fait côté profil, c'est pour ça que repasser aux valeurs précédentes ne suffit pas ;) mais ouai clairement le bug des lignes vient de #3886

**Comment by vhf** [comment]
C'est curieux ces incohérences. Exemple annoté super moche ici : 

![screen shot 2016-11-29 at 21 33 52](https://cloud.githubusercontent.com/assets/2022803/20727981/e67f2ba4-b67b-11e6-9869-611a5d28ad3a.jpg)


ping @sandhose

**Comment by AmarOk1412** [comment]
Ok d'après @abdelaz3r le comportement était présent avant la v21 (mais la avec le changement, ça a empiré)

**Comment by sandhose** [comment]
ça a été introduit par #3886, avec <https://github.com/zestedesavoir/zds-site/commit/5616a77d539e3ac5d0b95492f7d45168ce057dee#diff-bd4bff66b6594772a0597ce6205214c2L184>. Je vais voir ce que je peux faire

**Comment by artragis** [comment]
Aujourd'hui, on a ça : 

![image](https://user-images.githubusercontent.com/1523653/29456231-18f9eed6-8415-11e7-950b-090531013c29.png)

**Comment by artragis** [comment]
rien dit, c'est toujours identique.

**Comment by artragis** [comment]
aujourd'hui on a ça : 
![image](https://user-images.githubusercontent.com/1523653/59267534-cad5f980-8c4a-11e9-8b12-73c2c93cacab.png)
