### ISSUE TITLE
Bouton de sauvegarde dans l'interface de rédaction de contenu

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#4026]
Suite aux discussions [dans ce sujet](https://zestedesavoir.com/forums/sujet/7418/extraits-et-chapitre) il semble qu'un bouton "Sauvegarder" permettant de sauver le contenu actuel d'une zone d'édition de contenu (non forum) serait fortement apprécié. Dans l’idéal de manière asynchrone pour éviter le rechargement de page et tout ce que ça implique (en particulier le redimensionnement de la zone d'édition).

**Comment by FanJiyong** [comment]
Yop yop,

C'est de la sauvegarde avec un historique ? 

Si y'a pas d'historique pour le moment je ne ferais ça que pour les parties avec un zone de texte. 

Il faut afficher un petit message pour dire que la sauvegarde est faites. : "Sauvegarde automatique : il y a 5 min" par exemple. 

Je propose de garder le bouton "Envoyer" pour le moment et de mettre ce nouveau message en face (a gauche du coup). 

En taille d'écran moins large je propose de mettre le bouton en dessous du champ.

**Comment by cgabard** [comment]
> C'est de la sauvegarde avec un historique ?

J'imagine qu'il faut créer un commit oui car il faut que ça reste dans l'historique si tu quitte la page.

Peut être que dans un monde idéal chaque appui sur ce bouton écraserai le commit précédent pour éviter un historique géant pour les cliqueurs compulsifs mais le plus important c'est de de sauvegarder, quitte a mettre un message de commit automatique.

**Comment by FanJiyong** [comment]
hum… un historique visible par l'auteur ou bien il n'a toujours que la dernière version ? 

Sinon faut prévoir les fonctionnalités et vues annexes…

**Comment by cgabard** [comment]
Je crois qu'on s'est mal compris... Actuellement quand tu valide ça enregistre les modifs sous forme d'un commit git. Pour ça il faut un message de commit (il y a un champ de texte pour le spécifier). Mais dans le cas présent, il faut faire simple : l'appui du bouton enregistre le contenu. La seule chose à rajouter coté UX c'est le bouton d'enregistrement.

Le reste ce sont les affaires des dev back.

**Comment by cgabard** [comment]
Actuellement il y a déjà un historique. Je propose juste de faire simple et que la sauvegarde mette un message par défaut type "modification de l'extrait..." Dans l'historique. Niveau interface ça fait un bouton à rajouter et l'affichage du popup de retour

**Comment by vhf** [comment]
Yep, bonne idée. On met ça dans la pile des trucs à faire, ok @FanJiyong ?

**Comment by FanJiyong** [comment]
![sauvegarde](https://cloud.githubusercontent.com/assets/15154100/20964977/2314a820-bc74-11e6-9e02-973c1f7e2939.png)

?

**Comment by Arnaud-D** [comment]
Corrigé par  #5865.

On fera un nouveau ticket si on veut étendre la fonctionnalité actuelle.
