### ISSUE TITLE
Aperçu effectué de façon asynchrone

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#4027]
Suite aux discussions [dans ce sujet](https://zestedesavoir.com/forums/sujet/7418/extraits-et-chapitre) il semble qu'un aperçu du contenu en rédaction qui serait fait de manière asynchrone (sans rechargement de page) serait vraiment apprécié.

**Comment by pierre-24** [comment]
A noter que ça se fait déjà pour les forums, donc c'est pas compliqué à copier ;)

**Comment by cgabard** [comment]
On peut se demander pourquoi c'est pas déjà le cas du coup... Bref

Le mer. 30 nov. 2016 19:27, Pierre Beaujean <notifications@github.com> a
écrit :

**Comment by FanJiyong** [comment]
Yop yop,

C'est de la sauvegarde avec un historique ? 

Si y'a pas d'historique pour le moment je ne ferais ça que pour les parties avec un zone de texte. 

Il faut afficher un petit message pour dire que la sauvegarde est faites. : "Sauvegarde automatique : il y a 5 min" par exemple. 

Je propose de garder le bouton "Envoyer" pour le moment et de mettre ce nouveau message en face (a gauche du coup). 

En taille d'écran moins large je propose de mettre le bouton en dessous du champ.

**Comment by EGabbro** [comment]
>A noter que ça se fait déjà pour les forums, donc c'est pas compliqué à copier ;)

L'aperçu des contenus fait un rendu des formules mathématiques, pas celui du forum. C'est une excellente raison pour ne pas copier tel quelle la version forum sur la version tuto. ;)

**Comment by pierre-24** [comment]
Maintenant, c'est le cas partout, en fait ;) (c'est pour la prochaine version aussi). Donc oui, on peut salement copier :p

**Comment by cgabard** [comment]
Ou de corriger celui du forum au passage

**Comment by pierre-24** [comment]
Mais je vous dit que c'est déjà fait :'( :  #3889 !

**Comment by cgabard** [comment]
Nos messages ce sont croisé, je repondai à gabbro

Le mar. 6 déc. 2016 16:25, Pierre Beaujean <notifications@github.com> a
écrit :

**Comment by Anto59290** [comment]
Je peux m'en occuper si on me laisse un peu de temps. Je suis en train de faire un peu de refacto pour les aperçu, dans l'ordre je vais proposer : 

- Ajout de l'aperçu sur la biographie (extension du système actuel au champ qui ne se nomme pas texte, positionnement plus souple de l'aperçu)
- Ajout de l'aperçu en intro et conclusion de contenu  (passage à un système acceptant deux champs d'aperçu dans la même page)
- Modification de l'aperçu des tutos pour éviter le rechargement.

Objectif de livraison pour Décembre (de cette année ^^).

**Comment by cgabard** [comment]
Fais le comme tu veux et dans l'ordre que tu veux. Garde en tête cependant que les améliorations sur l'éditeur de tuto/article sont beaucoup plus importante que pour les bio & co. Mais c'est le dev qui s'en occupe qui décide.

**Comment by Anto59290** [comment]
Ca arrive ce week-end normalement ;)

**Comment by pierre-24** [comment]
Et grâce à @Anto59290, c'est fait :)
