### ISSUE TITLE
Permettre d'ajouter des pièces jointes à un post

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#403]
On pourrait imaginer de pouvoir ajouter des pièces jointes à un post de forum.

Dans notre optique de forum d'entraide, ce serait un énorme plus, puisque ça permettrait par exemple d'y mettre des logs, des bouts de code, etc... sans avoir forcément à jouer avec les balises secret du forum.

Par contre ça poste des problèmes de stockage et de sécurité qu'il faut discuter.

**Comment by firm1** [comment]
Euh. Un peu dubitatif pour le coup.

Ne serait-ce pas mieux tout simplement un paste.bin interne ?

**Comment by SpaceFox** [comment]
J'y ai pensé, mais dans mes PJ je mets autre chose que des fichiers textes
(je pense à nos graphistes et associés là).

Si en plus ça nous permet d'éviter les liens vers les sites "d'hébergement
d'images" pourris de pub...

2014-05-02 14:55 GMT+02:00 firm1 notifications@github.com:

**Comment by firm1** [comment]
C'est bien pour ça qu'on a les galeries d'image non ?

**Comment by SpaceFox** [comment]
Ben ça dépend comment elles sont mises en valeur. Je te dis ce que j'en
pense dès que je peux tester :)

**Comment by cgabard** [comment]
Pour moi ça devrait mériter une Zep donc ticket a fermer tant que pas fait. Peut être faire un sujet sur le forum "idée de zep" pour lister ces idées qui mériteraient à être détaillés ?

**Comment by gustavi** [comment]
:+1: 

EDIT : fait ! https://zestedesavoir.com/forums/sujet/1876/idees-a-zep/
