### ISSUE TITLE
[v21] Bord en bas de la pagination

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#4033]
En prod:

![image](https://cloud.githubusercontent.com/assets/1549952/20866858/8d1fcf86-ba37-11e6-9bea-f8413b6173e0.png)

En beta:

![image](https://cloud.githubusercontent.com/assets/1549952/20866865/9da91f38-ba37-11e6-9719-2a90fa381af0.png)

**Comment by pierre-24** [comment]
Ok :)
