### ISSUE TITLE
Erreur 500 lors de la visite d'un tutoriel

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#4038]
Bonjour, 

J'ai des notifications persistantes liés aux sujets de l'article « Capitole du libre» lors de sa mise en béta. Mais maintenant, j'ai une erreur 500 quand je souhaite visiter l'article publié du [capitole du libre](https://zestedesavoir.com/articles/1648/retour-sur-le-capitole-du-libre/)

**Comment by gllmc** [comment]
De même pour moi avec [le guide du contributeur](https://zestedesavoir.com/tutoriels/705/le-guide-du-contributeur/).

**Comment by vhf** [comment]
Merci pour l'info ! Je parie que c'est l'exact même cas que #3918 et #3988.

Du coup ce sera réglé bientôt. Mais si vous voulez que ce soit réglé encore plus vite, vous pouvez aider à QA ces 2 PR : https://github.com/zestedesavoir/zds-site/pulls?q=is%3Aopen+is%3Apr+label%3A%22QA+svp%22+milestone%3AV21

Une fois qu'elles sont mergées, je fais une RC sur la beta et ça devrait être la dernière avant la mise en prod.

**Comment by DevHugo** [comment]
Dans les deux cas, c'était des auteurs ce qui n'est pas mon cas. Je sais pas si ça change grand chose mais en tout cas c'est pas les mêmes symptômes

**Comment by DevHugo** [comment]
Nouvelle piste: je me suis désinscrit du profil de `roipoussiere` (l'auteur de l'article inaccessible) et je peux maintenant accéder à l'article.

**Comment by pierre-24** [comment]
Je me souviens que dans ma QA des PRs susmentionnée, j'avais aussi testé le cas du membre suivant un auteur, et que ça passait. Dans le doute, c'est à confirmer sur la bêta, mais normalement on est bon.

**Comment by DevHugo** [comment]
Ok, mais du coup, le cas a été prévu pour les notifications persistante ?

**Comment by pierre-24** [comment]
normalement, oui :)
