### ISSUE TITLE
Changer la formulation du topic de beta des contenus.

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#4040]
Il y a un passage qui dit "j'ai dans l'objectif de proposer [un super contenu]". C'est pas français.

On peut mettre "j'ai l'objectif de", ou "j'ai pour objectif de", ou reformuler le tout. Mais "dans l'objectif de", ça passe pas ici. Ça passerait par exemple comme ça : 

* Dans l'objectif d'améliorer mon texte, je demande votre aide.
* Il est dans l'objectif des validateurs d'augmenter la cadence de publication.

Ou autre.

**Comment by gllmc** [comment]
C'est facile pour le coup, je m'en charge :)

**Comment by pierre-24** [comment]
Voilà. Aussi tôt dit, aussi tôt fait !
