### ISSUE TITLE
[v21] Incohérence temporelle (?) notification/subscription

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#4052]
Cf. https://sentry.sandhose.fr/zeste-de-savoir/beta-scaleway-backend/issues/765/

Probablement que c'est un cas qui se produira uniquement les premiers temps suivant la MEP v21.

La v21 règle le problème de génération de notifications doubles ou persistantes dues à des sujets fermés ou autres. Le problème est que lorsque ces notifications existent déjà, leurs souscriptions sont supprimées lors de la consultation de la notif persistante, les faisant disparaitre. Le problème est que parfois, la souscription est supprimée (?) avant que la notif soit marquée comme lue, du coup quand la notif est marquée comme lue, elle fait référence à une souscription inexistante et ça provoque une 500 à cause de la contrainte de base de donnée.

**Comment by artragis** [comment]
ah oui, c'est ça.
