### ISSUE TITLE
Définir une politique de log

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#4057]
Bonjour,

Actuellement, nous ne loggons que peu de choses. Cet état de fait est principalement dû à ces deux faits : 

- nous n'avons pas les moyens de faire de l'analyse de log
- jusqu'à aujourd'hui le client sentry n'était pas branché au logger zds du coup on pouvait logger ce qu'on voulait ça servait à rien

L'idée serait donc de définir des guidelines en matière de log pour qu'il y en ait plus qui soient remontés sur sentry et qu'on puisse traiter le plus d'info possible.

**Comment by pierre-24** [comment]
Intéressant, ça :)

Et ça prendrait quelle forme, en pratique ?

**Comment by artragis** [comment]
Ce que j'entends par politique de log contient la réponse à : 

- que log-t-on? Aujourd'hui, nous n'avons du log que lorsque des bugs bien relou ont eu lieu et que j'ai ajouté un log dans les cas d'erreur que je suis sensé avoir corrigé. Pourtant les bugs qui me gènent le plus personnellement ce sont les cas où on mène à un 404 : dans ces cas nous n'avons pas d'autre log que le nginx.log et du coup nous n'avons aucun contexte. On pourrait donc --si c'est vraiment souhaitable pour tous les devs-- définir que dès qu'on raise un HTTP404 on ajoute aussi un log de type warning comme ça on pourra, via la béta répliquer facilement le bug sans pourrir le sentry. Il y a sûrement d'autres exemples de choses à faire.
- comment log-t-on? sentry possède des capacités assez phénoménales en matière de filtrage des logs et des notifications. Aujourd'hui comme nous avons peu de log (uniquement les 500) dans sentry, et qu'on est plutôt efficace pour corriger les erreurs 500, je suis persuadé que personne n'utilise ces filtres. Proposer une regexp, un tag (car oui, sentry permet de tagger) ou une ligne à suivre pour que les filtres sentry soient utilisables me paraît nécessaires.
- quand log-t-on? Aujourd'hui sur la v21 j'ai activé le logger sentry uniquement sur les loggers qui descende de zds et en ERROR en indiquant à vhf que sur la béta on pouvait aussi s'amuser à mettre du warning pour avoir plus de contexte. Est-ce la chose à faire? Doit-on utiliser plus globalement le niveau warning et quand même activer ce niveau sur sentry? Ou bien doit-on se restreindre à ERROR ou FATAL?

**Comment by artragis** [comment]
défini par @Situphen lorsqu'il a pris la main sur les logs de prod avec ansible. Je clos.
