### ISSUE TITLE
Update raven

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#4058]
Sentry nous gueule dessus car on a la version 5.14 du client sentry. Il faudra vérifier que les versions plus récentes sont compatibles django 1.8 et mettre ladite version plus récente. 

Sentry est vraiment un bon outil pour comprendre le contexte d'un bug, cet upgrade peut vraiment s'avérer primordial pour la maintenance du site.

**Comment by sandhose** [comment]
Si au passage on peut configurer les releases côté Raven, ça serait top!

**Comment by artragis** [comment]
Jen e dis pas non. D'autnat qu'on peut faire un githook pour qu'au tagging un nouveau code de release soit créé.

**Comment by artragis** [comment]
mergé donc à clore @vhf @sandhose

**Comment by artragis** [comment]
en fait je pouvais le faire comme je l'avais ouverte :)
