### ISSUE TITLE
[v21] La recherche ne fonctionne pas

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4061]
Navigateur : Firefox
Version : v21-RC5
Lien incriminé : https://beta.zestedesavoir.com/rechercher/?q=entretien

En allant sur le lien ci-dessus on a aucun résultat dans la recherche.

Je soupçonne un problème d'infra. Mais on ne sait jamais.

**Comment by vhf** [comment]
Réglé.
