### ISSUE TITLE
[v21] L'interligne est plus faible qu'avant

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4062]
Navigateur  ; Firefox
OS : Windows
Niveau de zoom : 100%

Pour comprendre le mieux est d'observer l'image.

zone de rédaction d'un message de forum en **prod**

![edit-prod](https://cloud.githubusercontent.com/assets/6066015/21097311/3bd11008-c064-11e6-874d-61b3c8cd0e14.PNG)

zone de rédaction d'un message de forum en **beta**

![edit-beta](https://cloud.githubusercontent.com/assets/6066015/21097319/3fd97be0-c064-11e6-9e4e-14c5c410e8ce.PNG)

L'interligne sur la beta est moins élevé, ce qui fait que la zone de rédaction parait plus resserré, ce qui rend un peu difficile la relecture de son texte.

**Comment by sandhose** [comment]
Bien vu: c'est dû à un changement dans normalize.css (https://github.com/necolas/normalize.css/compare/4.2.0...master#diff-bb3dde41d97f19be8ab7b4780a915d5eR257) que j'avais pas anticipé quand j'ai bump les dépendances (https://github.com/zestedesavoir/zds-site/commit/57417947a8970868a50a7db153eb4f098e3ffd51#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R40)
