### ISSUE TITLE
[V21] Notification persistante toujours présente

### ISSUE THREAD

**Issue by WinXaito** [zestedesavoir/zds-site#4063]
J'ai eu un nouveau cas de notification persistante sur la beta.
J'en ai discuté avec @vhf sur IRC.

A première vu, cette notification serait du aux actions suivantes:

```
- Je créer un nouveau tutoriel
- Un staff le réserve
- Il le publie
- Il le dépubli (Sans que j'ai regardé la notification généré entre temps)
```

Et ceci devrait créer une notification persistante.

**Comment by artragis** [comment]
Merci, je vois très bien comment corriger ça. Je le fais de suite.
