### ISSUE TITLE
2 tutoriels au même titre : problème de slug et renommage repo

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#4065]
Du forum :

> Je résume :
> 
> * Un 1e tuto a été créé `/contenus/1657/comprendre-lexposition-en-photographie/`
> * Un 2e tuto a été créé avec le même titre : `/contenus/1658/comprendre-lexposition-en-photographie-1/` (notez le `-1` dans le slug, inutile ?)
> * Le 1e tuto a été supprimé.
> * Bug: le 2e tuto est devenu inaccessible - 404. Le repo du 2e tuto est `/opt/zds/data/contents-private/comprendre-lexposition-en-photographie`, ce qui n'est pas consistant avec son slug.
> * Renommer `/opt/zds/data/contents-private/comprendre-lexposition-en-photographie` en `/opt/zds/data/contents-private/comprendre-lexposition-en-photographie-1` rend à nouveau le 2e tuto accessible.
> 
> Hypothèse : le slug du tuto n'est pas géré correctement conjointement avec le slug du repo.
> 
> Hypothèse : le slug d'un tuto doit être unique à cause du stockage sur disque. Par contre il est inutile d'avoir un slug unique dans l'URL. Le comportement observé ici pourrait signifier que la logique est pile inversée : le slug observé est utilisé dans l'URL mais pas dans l'accès au repo.
> 
> Solution possible : préfixer les repos sur le disque avec la PK du contenu (et cesser de forcer l'unicité des slugs d'URL).
> 
> Autres remarques :
> 
> * `get_repo_path` a un paramètre inutile et très probablement buggé : `relative=False`

---

> Par défaut, lorsqu'un contenu est sauvé son slug est mis à jour. Ce qui est super dangereux, et il est très surprenant que ça ne cause un bug que maintenant. Il faudrait au minimum que lorsque le slug est modifié, le repo soit également renommé. https://github.com/zestedesavoir/zds-site/blob/cffb5551d2d30d4d5b39f02e3164151d5e0ebd74/zds/tutorialv2/models/models_database.py#L140-L145

**Comment by pierre-24** [comment]
Mouais. Je suis jamais chaud quand on annonce "cesser de forcer l'unicité des slugs" (y'avais plein de bonnes raisons à cela, y compris un débat de 5 pages). Surtout que cette partie là, elle est gérée par la BDD, donc c'est `django-uuslug` qui est censé faire le job (et qui à priori, le faisait convenablement jusque là), et que le slug du repo est censé venir de là. J'étais à peu près convaincu qu'on avait un test là dessus, mais vu que c'est `uuslug` qui était censé faire le job, je pense qu'on avait laissé tomber. D’ailleurs, si je reproduis stricto senso ce qui c'est passé, j'ai pas de bug, ce qui prouve rien, certes, mais montre que le système est quand même un minimum robuste.

Je pense que l'histoire est pas complète: il y a du y avoir du renommage quelque part, ou de l'import d'archive, ou un truc du genre. Parce que part défaut, ces cas de renommage passent [par là](https://github.com/zestedesavoir/zds-site/blob/cffb5551d2d30d4d5b39f02e3164151d5e0ebd74/zds/tutorialv2/models/models_versioned.py#L1195) et sont normalement gérés puisqu'on vérifie bien qu'on doit bouger dans le cas ou le slug à changé, et que dans les vues, ça passe [par là](https://github.com/zestedesavoir/zds-site/blob/cffb5551d2d30d4d5b39f02e3164151d5e0ebd74/zds/tutorialv2/views/views_contents.py#L294) (la vue d'édition) ou [par là](https://github.com/zestedesavoir/zds-site/blob/cffb5551d2d30d4d5b39f02e3164151d5e0ebd74/zds/tutorialv2/views/views_contents.py#L730) (la vue d'update par une archive), avec préférence pour la deuxième :)

**Comment by vhf** [comment]
@pierre-24 , je suis pas au courant du débat de 5 pages et j'en connais pas les conclusions.

Je veux bien qu'on m'indique l'utilité d'un slug unique dans ce cas précis, à part causer un bug très gênant.

C'est assez dangereux le `save` que j'indique.

**Comment by pierre-24** [comment]
Les pages de discussion sont les pages de la ZEP-12, et ça serait de la
torture de la torture que de t'envoyer les relire ^^

Bon, une des grosses idées de la ZEP-12, c'était d'éviter la BDD un
maximum, de manière à éviter tout les problèmes de versionnage (titre qui
change entre différentes versions, etc). D'où le manifest.json un peu
imbuvable, et ainsi de suite. Dans le même ordre d'idée, côté code, tout ce
qui est lié à la BDD est dans model_database et la majorité des trucs liés
à Git sont dans model_versionned.  J'avoue que c'est pas le choix le
meilleur dans le cas qui nous occupe, mais en général ça a bien marché, ce
pourquoi le changement de slug est découplé du déplacement de fichier. Ça,
à la limite, on peut changer, ça devrait pas casser grand chose, et si
c'est pour plus de stabilité, pourquoi pas (surtout qu'en vrai, c'est juste
un mv et une modification du manifest, si je dis pas de conneries)

EN ce qui concerne l'unicité du slug, au delà des aspects de stockage et
éventuellement des aspects esthétiques (parce que c'est quand même plus
simple de s'y retrouver avec des slugs que avec des nom de dossier qui sont
les pks), je pense que ce choix est un bon choix. Déjà parce que ça
n'oblige pas a connaitre le pk à priori, information qui n'est pas
disponible dans le manifest (pour des raisons évidentes). Ensuite parce que
ça me semble assez évident que si deux objets ont le même titre, il faut
bien les différencier d'une manière ou d'une autre (ACID, toussa), et
puisque on ne connait pas le pk à priori, le slug doit forcément être
différent (si c'est le "-1" qui te dérange, on peut toujours changer ça).
Puis c'est pas forcément parce que la manière de coder ça est pas la
meilleure que c'est un mauvais choix de design.

Évidement, y'a l'autre manière de penser: à quoi sert de donner un slug à
un contenu puisque à un certain point il va finir par recevoir un pk ?
C'est une position qui se défend, mais alors autant se débarrasser du slug
de contenu (et uniquement garder ceux des dossiers/extraits). Si l'unicité
du slug n'est plus obligatoire pour le stockage, alors clairement, le slug
ne sert à rien pour le contenu, en fait ^^ (mais alors n'importe qui peut
mettre n'importe quoi dans les urls, un peu comme pour les galeries).

Donc pour moi, soit on garde un slug unique et on change éventuellement la
méthode save() soit on s'en débarrasse parce que il sert à rien. Et dans
l'idée d'essayer d'etre un maximum indépendant de la BDD, il est évident
que je préfère la première :)
