### ISSUE TITLE
Le filtre des sujets par tag rend des doublons

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4068]
### Contexte

- Compte : staff et CA
- Navigateur : Chrome
- Version : RC6

### Problème

On obtient, pour le filtre des sujets pour un tag particulier un sujet en double

#### Prod

url : https://beta.zestedesavoir.com/forums/sujets/tag/2346/comm/

screen du résultat :

![capture d ecran de 2016-12-13 01-14-45](https://cloud.githubusercontent.com/assets/6066015/21122322/b3a224d8-c0d1-11e6-9e5c-7f418aabc62f.png)

 
#### Beta : 

url : https://beta.zestedesavoir.com/forums/sujets/tag/2346/comm/

screen du résultat : 

![capture d ecran de 2016-12-13 01-14-27](https://cloud.githubusercontent.com/assets/6066015/21122311/a72b3fbe-c0d1-11e6-89f7-f0b6ee2d8a49.png)

**Comment by artragis** [comment]
bien que je sois staff, je n'ai pas ce bug oO

**Comment by artragis** [comment]
pour vhf
![capture2](https://cloud.githubusercontent.com/assets/1523653/21159904/3a8e4f4c-c183-11e6-8548-d0d3bac2db03.PNG)

**Comment by vhf** [comment]
Pas réussi à reproduire le bug de @firm1 non plus.

**Comment by firm1** [comment]
vraiment bizarre car je reproduis encore

**Comment by cgabard** [comment]
Pour info je reproduis aussi

**Comment by cgabard** [comment]
Et le screen fait sur la beta à l'instant via le liens de @firm1 

![screencapture-beta-zestedesavoir-forums-sujets-tag-2346-comm-1481711996260](https://cloud.githubusercontent.com/assets/6103932/21178933/14d71f26-c1f2-11e6-9945-489b61822615.png)

**Comment by vhf** [comment]
Le problème ne semble toucher que les membres qui font partie de plusieurs groupes dans le cas où plusieurs de ces groupes donnent accès à certains mêmes forums privés. Concrètement : si vous êtes `CA` **et** `staff`, vous risquez de voir ça.

Ça devrait pas être très compliqué à régler.

**Comment by cgabard** [comment]
Et pas très impactant pour la majorité des users

Le mer. 14 déc. 2016 20:30, victor felder <notifications@github.com> a
écrit :

**Comment by vhf** [comment]
Yep. C'est pour cette raison que je me suis permis de faire la release malgré ce bug. Navré pour les staff qui sont dans le CA, mais ça aurait trop repoussé.

**Comment by Anto59290** [comment]
Je prends. Le but se reproduit aussi sur les derniers sujets créés par un auteur. Ca a vraisemblablement été introduit par #3949 .

**Comment by Situphen** [comment]
Merci @Anto59290 !
