### ISSUE TITLE
[v21] Problème d'affichage dans la sidebar d'un profil

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4069]
Navigateur : Chrome
Url : https://beta.zestedesavoir.com/membres/voir/Gabbro/

Screen de la sidebar.

![capture d ecran de 2016-12-13 01-18-38](https://cloud.githubusercontent.com/assets/6066015/21122393/21b341aa-c0d2-11e6-850c-9e45f51094a1.png)

Comme on peut le voir, à droite de "En validation" et "En rédaction" le background n'est pas harmonisé avec le reste.

**Comment by vhf** [comment]
Le problème vient d'ici : https://github.com/zestedesavoir/zds-site/commit/4aebba7d9ea23679b86616ceda11fefbc53babcd#diff-85a845569aeb14a414278156f2a201faR128
