### ISSUE TITLE
Limiter le nombre de requêtes SQL

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#407]
En réinstallant la debug_toolbar (qui marche très bien sous Windows, merci pour elle) pour regarder les bugs #393 et #406, je me suis aperçu que le site provoque un nombre complètement délirant de requêtes SQL :
- 65 requêtes sur la home en étant déconnecté
- 100 requêtes sur la home en étant connecté
- 110 requêtes pour la liste des forums en étant déconnecté 
- 177 requêtes pour la liste des forums en étant connecté 
- 152 requêtes pour une page (complète) de forum en étant déconnecté
- 286 requêtes pour la même page de forum en étant connecté

Alors c'est relativement rapide, donc je suppose qu'il y a un cache quelque part. Mais ça n'en reste pas moins complètement hallucinant.
Ça mériterait au moins de faire un test avec un vrai SGBD (genre pas Sqlite) pour savoir combien de ces requêtes arrivent jusqu'à lui.

**Comment by firm1** [comment]
La pluspart des requêtes doivent être localisables dans le header (zone de notifs, zone d'alertes, zones de messages).

Les requetes sur les forums sont du principalement au fait qu'on essaye de savoir pour chaque membre qui poste, quel est son statut (banni, ls, staff, etc.). ça peut aussi être dénormalisé (mais avec plus de difficulté pour les LS/BAN temploraires)

**Comment by SpaceFox** [comment]
Quelques ressources :
https://docs.djangoproject.com/en/1.6/topics/db/optimization/
https://docs.djangoproject.com/en/1.6/ref/models/querysets/#select-related

**Comment by Alex-D** [comment]
Je pense, à vue de nez que les relations définies dans l'ORM sont en Lazy par défaut, et il faut les forcer pour qu'elles soient faites sous forme de jointures;

**Comment by firm1** [comment]
Le Lazy est préférable dans la majeur partie des cas, sauf si on a vraiment envie de faire péter le serveur.

**Comment by Alex-D** [comment]
T'es conscient de l'impact de l'application du Lazy partout ?
Si on laisse le lazy, il faut forcer les jointures là où c'est nécessaire.

**Comment by firm1** [comment]
> T'es conscient de l'impact de l'application du Lazy partout ?

C'est le contraire qui serait effrayant

**Comment by Alex-D** [comment]
Je n'ai pas dit de mettre de l'auto-jointure partout, seulement là où c'est fait systématiquement.

**Comment by SpaceFox** [comment]
AMHA, ça nécessiterait surtout l'aide de quelqu'un qui a de l'expérience
dans ce genre de trucs.

Exemple : si j'ai bien compris ce que dit la doc et les requêtes que je
vois passer, on ne récupère que les données des posts de la page (le bloc
dans /ZesteDeSavoir/zds/forum/views.py ligne 105 ne correspond pas à une
vraie requête).
La requête réellement exécutée a une LIMIT qui correspond à la page
courante.

Par contre j'ai l'impression qu'à cause des lignes 137 et 138 du même
fichier on fait une requête par post présent dans la page pour en récupérer
les données...

Bref, tout ça est assez compliqué et délicat.

**Comment by Alex-D** [comment]
Je suis calé en SQL, mais pas en python/django.

Le res.append je pense que ça se contente juste de rebalancer le contenu du tableau posts dans la réponse.

Mais vu le nombre de requêtes il y a forcément un problème quelque part...

**Comment by SpaceFox** [comment]
> Mais vu le nombre de requêtes il y a forcément un problème quelque part...

Le problème, c'est que je ne sais même pas quelle proportion de ces
requêtes arrivent vraiment jusqu'au SGDB...

**Comment by Coy0te** [comment]
J'ai pas mal bossé sur ce genre de problématiques (affinage des requêtes SQL avec JPA, problématique identique à celle posée ici avec Django), je peux aider à défricher si besoin.

**Comment by SpaceFox** [comment]
Au vu des résultats des tests faits pour l'issue #413, en fait il n'y a pas de problème ici (soit il y a un cache, soit les requêtes sont tellement simples que non problématiques).

Il y a bien une question dans certains cas spécifiques, mais c'est le domaine des bugs #394 et #406 .

Du coup, je ferme celui-ci.

**Comment by SpaceFox** [comment]
Je ré-ouvre cette issue parce que les chiffres donnés par MySQL sont quand même flippant :

> [--] Up for: 11d 16h 1m 1s (23M q [23.044 qps], 61K conn, TX: 28B, RX: 9B)

23 millions de requêtes en 11 jours, soit une **moyenne** (24h/24, 7j/7) de 24 requêtes par seconde. C'est juste dément par rapport au trafic qu'on a.

**Comment by Alex-D** [comment]
En fait, y a 1 chinois sur 5 qui a réussi à passer outre le htaccess :D

Plus sérieusement : les jointures les gars ! Les jointures...

**Comment by Coy0te** [comment]
@SpaceFox et les devs back : je ne sais pas comment fonctionne Django, donc je n'ose pas mettre  les mains dedans, mais après survol de la doc ça m'a l'air de fonctionner derrière les rideaux à peu de choses près comme JPA. 

Par défaut, tout est en mode requêtes "une par une", et c'est sûrement pour ça que c'est du gros n'importe quoi au niveau des perfs. L'argument évoqué précédemment du genre "c'est des requêtes simples donc c'est pas grave si y'en a une pelleté", c'est ok en dev voire en Beta mais c'est absolument pas scalable à des conditions de prod. J'espère d'ailleurs que Django gère une succession de requêtes d'un même utilisateur dans la même session, sinon bonjour l'explosion des ouvertures/fermetures de connexions... D'ailleurs (oui, encore un "d'ailleurs"), est-ce qu'on a un pool de connexions MySQL activé ? Comment est-il dimensionné ? Ça m'intéresse et je peux aider sur ce point si besoin.

Pour en revenir aux requêtes, il faut examiner chacune des requêtes impliquant potentiellement des jointures, et décider de les activer (ou non, dans de rares cas).

**Comment by SpaceFox** [comment]
Je n'ai pas la moindre info là-dessus... Il nous faudrait l'avis et un peu de temps d'un connaisseur de Django.

Pour le pool de connexion, personnellement je n'ai rien configuré... j'ose espérer qu'il y en a un dans un coin !

**Comment by geoffreyc** [comment]
Je sais que dans pas mal d'app django, ya beaucoup d'erreurs du genre des
"select" dans les loops, etc. (a cause du ORM django qui rend ca super
simple a faire ...) ducoup je sais pas si c'est le cas ici, mais il
faudrait deja faire un tour peut partout pour voir si ya pas des endroits
ou on a oublié de faire des "prefetch_related par example. Avec un nombre
pareil de queries, ca m’entonnerait pas qu'on ait cette situation de
"select in a loop"

2014-06-16 20:54 GMT+01:00 Coyote notifications@github.com:

> requêtes impliquant potentiellement des jointures, et décider de les
> activer (ou non, dans de rares cas).

**Comment by firm1** [comment]
Ah cette issue aussi peut être fermée, Maintenant que les templates sont stables, j'ai passé un gros coup de balai dans les requêtes. Le nombre de requêtes a été réduit d'au moins 1/3 dans le pire des cas.

Voici [un résumé](https://github.com/zestedesavoir/zds-site/pull/1030#issuecomment-47931347) des nouvelles perfs : 

> Pour comparaison : Prod vs Preprod (qui est actuellement sur la PR 1030).
> 
> **NB : la préprod est ISO-PROD en terme de matériels et de logiciel. et la préprod a plus de topics dans le forum que la prod.**
> 
> | Pages | url | Temps de chargement prod | Temps de chargement préprod | Ratio |
> | --- | --- | --- | --- | --- |
> | Home | `/` | 1.012 seconds | 0.074 seconds | 13.67 |
> | Liste des catégories | `/forums/communaute/` | 1.234 seconds | 0.370 seconds | 3.33 |
> | Liste des forums | `/forums/communaute/bug-suggestions/` | 1.307 seconds | 0.622 seconds | 2.1 |
> | Un topic | `/forums/sujet/273/les-petits-pixels/` | 2.927 seconds | 0.710 seconds | 4.12 |
> 
> Donc la PR permet d'afficher les pages entre 2 et 13 fois plus vite avec la PR.
