### ISSUE TITLE
Afficher l'adresse email dans le profil

### ISSUE THREAD

**Issue by FanJiyong** [zestedesavoir/zds-site#4073]
Nous allons apporter quelques modifications dans la page paramètre -> pseudo et email

- Changement des labels : 
-- Mon Pseudo
-- Mon adresse email 

- Afficher 
-- Le pseudo du membre dans le champ "Mon pseudo"
-- L'adresse email du membre dans le champ "Mon adresse email"

- Déplacer l'option "Afficher mon adresse email publiquement" (paramètres ->https://zestedesavoir.com/forums/sujet/7555/afficher-mon-adresse-mail-sur-mon-profil/?page=1#p134983
 Mon profil ) en dessous du champ "Mon adresse email" (paramètre -> pseudo et email)

Maquette disponible : 
![161213_emailpseudo](https://cloud.githubusercontent.com/assets/15154100/21189123/ecb1bbec-c21d-11e6-9651-383e8fbe2309.png)

**Comment by Anto59290** [comment]
Je pense que ça a été mergé ;)
