### ISSUE TITLE
Ajout de tooltips sur les icônes de l'interface

### ISSUE THREAD

**Issue by FanJiyong** [zestedesavoir/zds-site#4074]
Salut à tous, 

Certaines de nos icônes, n'ont pas la chance d'avoir un petit label pour les accompagnées. 

Afin qu'elles se sentent moins seules (et accessoirement tendre vers meilleurs expérience utilisateur) nous allons ajouter des tooltips a ses icônes. 

- Icones dans le header
-- la bulle : Messagerie privée
-- la cloche : Notifications

- Sur le forum 
-- la Pin : Sujet mis en avant ou Sujet épinglé (?) 
-- La check : L'auteur a trouvé une solution à son problème
-- Cadenas : Sujet fermé
-- Étoile : Sujet suivi

**Comment by Anto59290** [comment]
A été mergé :)

**Comment by pierre-24** [comment]
Toutafé !
