### ISSUE TITLE
Page API bogué

### ISSUE THREAD

**Issue by tleb** [zestedesavoir/zds-site#4082]
> Sous Chrome, [la page décrivant l'API](https://zestedesavoir.com/api/) est bogué. Aucun bouton ne fonctionne et `Raw` amène sur une 500.
&mdash; [Posté ici](https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=42#p135429) et confirmé par GCodeur et Bat'

**Comment by sandhose** [comment]
Il y a une erreur 500 sur la génération des endpoints d'api-doc.

Erreur sur sentry:

https://sentry.sandhose.fr/zeste-de-savoir/backend-l7/issues/791/

```
ImportError: Failed loading extension 'markdown.extensions.headerid' from 'markdown.extensions.headerid', 'markdown.extensions.markdown.extensions.headerid' or 'mdx_markdown.extensions.headerid'
(11 additional frame(s) were not displayed)
...
  File "rest_framework_swagger/introspectors.py", line 128, in get_summary
    callback, html=True, docstring=description))
  File "rest_framework_swagger/introspectors.py", line 41, in get_view_description
    .VIEW_DESCRIPTION_FUNCTION(view_cls, html)
  File "rest_framework/views.py", line 51, in get_view_description
    return formatting.markup_description(description)
  File "rest_framework/utils/formatting.py", line 61, in markup_description
    description = apply_markdown(description)
  File "rest_framework/compat.py", line 173, in apply_markdown
    extensions=extensions, extension_configs=extension_configs

ImportError: Failed loading extension 'markdown.extensions.headerid' from 'markdown.extensions.headerid', 'markdown.extensions.markdown.extensions.headerid' or 'mdx_markdown.extensions.headerid'
```

**Comment by DevHugo** [comment]
ça marchait bien avant, c'est une régression.

**Comment by vhf** [comment]
ping @cgabard

**Comment by cgabard** [comment]
Ah merde, si je comprends bien rest_framework utilise markdown et du coup entre en conflit avec les modifs de notre version

**Comment by cgabard** [comment]
Je pense que le plus simple va être de publier le zmarkdown sur Pypi. le dossier d'import sera zmarkdown au lieu de markdown et les deux pourrons cohabiter sur le système sans soucis. Je vois pas trop d'autres solutions.

**Comment by sandhose** [comment]
Pour le coup, c'est `django-rest-swagger` qui utilise `markdown` [*s'il est présent*](http://django-rest-swagger.readthedocs.io/en/stable-0.3.x/misc.html?highlight=markdown#markdown) pour faire le rendu des docstrings en markdown. Du coup, on est même pas obligé de les faire cohabiter, il suffit de renommer le paquet `zmarkdown` pour qu'il soit pas chargé par `django-rest-swagger`.

**Comment by GerardPaligot** [comment]
Vous savez s'il y a une solution à court/moyen terme qui est envisageable ? Ce bug est assez pénible pour les utilisateurs des APIs.

**Comment by vhf** [comment]
Oui oui @GerardPaligot , cf le dernier ticket mentionné, sur ZMarkdown.

**Comment by lypwig** [comment]
Du nouveau ici ? J'aimerais me servir des API.

Et sinon en attendant, quelqu'un pourrait copier-coller ici la liste des requêtes des API ? :)

Edit : en fait je veux juste savoir si une API permet de C/R/U/D les messages sur le forum. Mais la liste de toutes les requêtes rendra service à d'autres. ;)

**Comment by gllmc** [comment]
> Edit : en fait je veux juste savoir si une API permet de C/R/U/D les messages sur le forum.

Pas encore, mais ça devrait venir : #4136 ! ;)

**Comment by tleb** [comment]
C'est pas un peu bloquant comme issue ? Ça empêche tout le monde d'utiliser l'API vu que j'imagine que peu de monde la connait par cœur (on peut aller voir les modèles au pire mais bon...).

Il y a quelque chose que je peux faire ? Ou c'est uniquement des modifications sur l'env de prod ?

**Comment by vhf** [comment]
Ça devrait être réglé ça. Kjé a renommé le paquet, cf https://github.com/zestedesavoir/zds-site/issues/4082#issuecomment-281164082

**Comment by tleb** [comment]
Merci :)
