### ISSUE TITLE
Le choix du type de contenu n'est plus pris en compte dans la recherche

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4083]
Il semblerait que le choix du type de contenu dans la recherche ne soit plus pris en compte. Si l'on coche des cases, le résultat reste inchangé et les cases sont décochées à l'envoi du formulaire. Pourtant, l'URL conserve la marque de ces choix (exemple : https://zestedesavoir.com/rechercher/?q=django&id_models_3=tutorial).

**Comment by DevHugo** [comment]
C'est une régression ça. ça marchait bien avant !

**Comment by DevHugo** [comment]
à mon avis, c'est [ça](https://github.com/zestedesavoir/zds-site/commit/c5dc46501dd13c06afab81b71075e698ce3d197b). Si tu remplace dans url par la variable models, ça marche. 

Par exemple: [https://zestedesavoir.com/rechercher/?q=django&models=tutorial](https://zestedesavoir.com/rechercher/?q=django&models=tutorial), marche bien.
