### ISSUE TITLE
Les filtres de la recherche ne fonctionnent pas

### ISSUE THREAD

**Issue by pimolo** [zestedesavoir/zds-site#4084]
Dans la recherche (`/rechercher`), cocher des filtres semble n'avoir aucune influence sur les résultats de la recherche.
Par exemple, si je cherche "javascript" et que je coche seulement "Tutoriels", je me retrouve quand même avec plein de messages de forum en première page, ce qui ne m'aide pas du tout à trouver des tutoriels autour de javascript.

De plus, mais il s'agit plutôt d'UX ici, je pense que les filtres sélectionnés doivent rester cochés sur la page de résultats, ce qui n'est pas le cas actuellement. Mais cela pourrait faire l'objet d'une autre issue.

**Comment by DevHugo** [comment]
Voir #4083 .

> De plus, mais il s'agit plutôt d'UX ici, je pense que les filtres sélectionnés doivent rester cochés sur la page 
> de résultats, ce qui n'est pas le cas actuellement. Mais cela pourrait faire l'objet d'une autre issue.

C'est liés au premier souci, ça coche les filtres sélectionnés, c'est prévu comme ça.
