### ISSUE TITLE
Séparer Clem de la barre de recherche

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#4090]
[Ce commit](https://github.com/zestedesavoir/zds-site/pull/3953/commits/f5417f637c6ade818254b54a280f7c94cc3a638a) associée a [cette PR](https://github.com/zestedesavoir/zds-site/pull/3953) donne la possibilité de masquer la barre de recherche.

Seulement sur [la feuille de style](https://github.com/zestedesavoir/zds-site/blob/81e80e52bb69b22539860f2bb03106fa6a76f3f6/assets/scss/pages/_home.scss#L210-L242), Clem est liée à la barre de recherche, donc Clem n'est plus affichée.

Cf. [topic sur le forum](https://zestedesavoir.com/forums/sujet/7616/alerte-enlevement-clem-a-disparu/).

**Comment by gllmc** [comment]
On peut probablement fermer cette issue maintenant qu'on n'a plus de raison de masquer la barre de recherche, non ?

**Comment by pierre-24** [comment]
Tout a fait :)
