### ISSUE TITLE
Ne pas permettre la validation d'une nouvelle image sans titre. 

### ISSUE THREAD

**Issue by FanJiyong** [zestedesavoir/zds-site#4092]
Bonjour tout le monde !

Aujourd'hui j'ai "découvert" une action (un peu) anti-ergonomique dans la galerie qui me semble pas très complexe à régler (d'un point de vue ergo). 

Usecase (en tant qu'utilisateur)

- Je vais dans (une de mes) galerie(s)
- Je vais chercher une image
- Je ne met pas de titre
- Je valide

La page recharge, je n'ai plus d'image dans le champ et aucun message pour me signalé que c'est un échec. 

Sur un point de vu technique, le comportement du formulaire est correct parce que je n'ai pas rempli les champs obligatoires. Par contre le rechargement sans message met en doute. 

Je propose de changer le comportement. 

Avec le même usecase que cité précédemment, Je propose :
- Désactive le bouton de validation tant que tous les champs requis ne sont pas renseigné 
- En hover du bouton désactive, (voir de la faisabilité) mettre en évidence les champs requis qui ne sont pas renseigné.

**Comment by Anto59290** [comment]
Salut @FanJiyong ,

Quelques questions : 

- Quand tu dit "Je vais chercher une image", ça veut dire que tu clicques sur l'action ajouter une image (dans la galerie) et que tu la sélectionne avec le champ Image ?
- Puis tu valide (sans titre) ?

En reproduisant (sur une version locale) je retombe sur la même page qui me dit comme message (en dessous du champ) : "Ce champ est obligatoire.". Par contre le champ sélectionner une image est bien vide chez moi. Peux tu confirmer que c'est ce que tu as aussi ? 

![captureimage](https://cloud.githubusercontent.com/assets/6287044/21425639/b8831cde-c84a-11e6-8e5a-1369b7c794a5.JPG)

Si on s'est mal comprit peux tu faire un gif de ton écran quand tu réalise la suite d'action qui mène au comportement à améliorer ? Merci !

**Comment by FanJiyong** [comment]
>Quand tu dit "Je vais chercher une image", ça veut dire que tu clicques sur l'action ajouter une image (dans la galerie) et que tu la sélectionne avec le champ Image ?
> Puis tu valide (sans titre) ?

Ouais c'est bien de ça que parle. 

> Peux tu confirmer que c'est ce que tu as aussi ?

Oui effectivement. 
J'avais bien vu les champs vide mais pas du tt ce message (en meme temps il apparait comme un champ info, pas comme une erreur).

**Comment by Anto59290** [comment]
Tout à fait. Maintenant que l'on est d'accord sur le comportement que l'on a aujourd'hui. Je propose une solution légèrement différente de ce que tu veux mais qui a le mérite d'être très facilement impémentable (enfin je pense :D ).

Je te propose de faire comme ce qui est fait ici : https://zestedesavoir.com/contenus/nouveau-tutoriel/
A savoir que si tous les champs * ne sont pas remplis, le formulaire te jette et te renvoi au champ non rempli. Voir exemple ci dessous.

![ergo-erreur](https://cloud.githubusercontent.com/assets/6287044/21429279/685d85c8-c85e-11e6-81e1-326401bade2a.jpg)

**Comment by FanJiyong** [comment]
Mise a part que c'est (vraiment) pas très beau, ça pourrait être une solution rapide. 

Ca prend vraiment longtemps à désactivé un bouton quand y'a pas les champs requis d'inscrit ?  *regard de puss in boots*

**Comment by Anto59290** [comment]
Je vais regarder. C'est pas *compliqué*, mais je pense qu'il faut rajouter un mécanisme en plus. Je ne pense pas que ce genre d'approche soit déjà utilisé dans Zds (ou alors je n'ai jamais vu où).

**Comment by FanJiyong** [comment]
Non je ne pense pas non plus que ça soit utilisé mais totalement possible
qu'on le réutilise sur certains formulaire.

**Comment by Anto59290** [comment]
C'est pour ça que je me dit qu'une fonction JS bien faite pour être utile ;)

**Comment by Situphen** [comment]
Je propose de rester sur le comportement adopté sur tout le site (j'ai vérifié c'est le cas pour les contenus comme le dit @Anto59290 ainsi que sur les forums), soit simplement ajouter l'attribut `required` sur ce champ (enfin, faire en sorte que Django le rajoute). Pourquoi rajouter du JS quand c'est très bien géré par les navigateurs modernes ? :)

**Comment by FanJiyong** [comment]
Je propose de ne pas rester sur le comportement actuel que l'on retrouve
sur tous le site. J'ai d'ailleurs ,(sans trop chercher) trouvé quelques
exemples où ce nouveau comportement pourrait apporter de la clarté sur des
éléments où il en manque.

L'attribu requiered donne un comportement différent selon le navigateur
utilisé et généralement c'est hyper moche, et pas toujours adapté au
contexte des formulaire que j'ai ciblé, et dont je mettrai la liste dans
cette issus prochainement

**Comment by Situphen** [comment]
Je n'arrive pas à reproduire le problème donc je suppose que ça a été réglé a un moment et je ferme. Si ce n'est pas le cas on rouvrira.
