### ISSUE TITLE
Tribunes libre : Bug affichage page d'accueil

### ISSUE THREAD

**Issue by josephcab** [zestedesavoir/zds-site#4094]
Les tribunes libres ne s'affichent pas automatiquement sur la page d'accueil après publication.

On peut par exemple constater que la liste des derniers billets ne contient que celui de victor, alors que entwanne et joseph en ont créé une.

**Pour constater le bug :**
 - Aller sur la page d'accueil
 - constater qu'il n'y a qu'une seule tribune libre
 - Aller sur la page des tribunes (cliquer sur ```Tous les billets```)
 - Constater qu'il y en a au moins 3

**Proposition de tag :**
 - Bug

**Comment by DevHugo** [comment]
C'est "normal", les tribunes publiées sur la page d'accueil doivent être validé par le staff manuellement. C'était principalement pour éviter qu'on est des tribunes sur la page d'accueil sur des sujets bizarre ou carrément bizarre :) !

Les conditions sont les suivantes pour apparaître sur la page d'accueil (ils faut que toutes les conditions soient réunies) : 

- La tribune a été approuvée par le staff;
- La tribune a moins de 15 jours ;
- La tribune a un ratio de votes de +10 minimum (ex1 : 3 négatifs et 12 positifs = -3 + 12 = +9 = PAS VALIDE ;ex2 : 5 négatifs et 16 positifs = -5 + 16 = +11 = VALIDE). (Pas encore en place)

Tu peux voir les specs [ici](https://zestedesavoir.com/forums/sujet/976/zep-13-tribune-libre/?page=4#p92499).

**Comment by josephcab** [comment]
très bien.
Dans ce cas, on peut passer l'issue en résolu.
Et merci beaucoup pour ces infos.
