### ISSUE TITLE
Subcategory of tutorials

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#41]
Hello,

J'ai tenté d'implémenter les sous-catégories pour les tutoriels mais je me suis cassé les dents toute la soirée d'hier. Pour une raison vraiment toute bête : Impossible de mettre à jour le schéma d'une classe (table) existante.

J'ai essayé pas mal de choses, notamment la suppression du fichier `base.db`, mais même si les champs semblaient exister dans la console python, impossible de créer les sous-catégories via l'espace admin.

Est-ce que quelqu'un (sans doute firm1) pourrait m'aider à comprendre ?

Au delà de ça, il faudrait penser à implémenter ces sous-catégories si ce n'est pas moi qui m'en occupe. :)

**Comment by firm1** [comment]
Pour mettre à jour le schémas de la bd, lorsque tu rajoute une classe ou un attribut de classe dans le modèle, il faut taper les commandes suivantes .

`python manage.py schemamigration <nom_application> --auto`
et
`python manage.py migrate <nom_application>`

Par exemple, si tu as implémenté les sous-catégorie dans `utils` tu dois faire : 
`python manage.py schemamigration utils --auto`
`python manage.py migrate utils`

**Comment by GerardPaligot** [comment]
Ouaip, j'avais déjà testé cette solution mais j'obtiens quand même une erreur. J'ai quand même re-essayé tes deux instructions à la suite en retirant le champ `image` de `Category` et en rajoutant un champ `slug`.

J'obtiens l'erreur suivante :

``` console
DatabaseError at /admin/utils/category/
no such table: utils_category
```

**Comment by firm1** [comment]
Tu dois mal t'y prendre quelque part.

Quand tu fais `python manage.py schemamigration utils --auto` , est-ce que tu as une erreur ? Quel est le message de retour ?

**Comment by GerardPaligot** [comment]
Ouaip, sinon ça fonctionnerait. :)

Voici mes étapes précises :

1/ Je modifie la classe `Category`.
2/ J'exécute la commande `python manage.py schemamigration utils --auto` et je fais les choix suivants :

``` console
 ? The field 'Category.image' does not have a default specified, yet is NOT NULL.
 ? Since you are removing this field, you MUST specify a default
 ? value to use for existing rows. Would you like to:
 ?  1. Quit now.
 ?  2. Specify a one-off value to use for existing columns now
 ?  3. Disable the backwards migration by raising an exception; you can edit the migration to fix it later
 ? Please select a choice: 3
 - Deleted field image on utils.Category
 ? The field 'Category.slug' does not have a default specified, yet is NOT NULL.
 ? Since you are adding this field, you MUST specify a default
 ? value to use for existing rows. Would you like to:
 ?  1. Quit now, and add a default to the field in models.py
 ?  2. Specify a one-off value to use for existing columns now
 ? Please select a choice: 1
```

3/ J'exécute la commande `python manage.py migrate utils` mais il ne fait rien :

``` console
Running migrations for utils:
- Nothing to migrate.
 - Loading initial data for utils.
Installed 0 object(s) from 0 fixture(s)
```

**Comment by firm1** [comment]
Dans le deuxième cas tu dois choisir l'option 2 pour spécifier la valeur par défaut des anciens lignes qui vont avoir un slug.

Si tu fais le choix 1, tu dois aller modifier ton model et rajouter une valeur par défaut aux champs avant de faire le schemamigration.

**Comment by GerardPaligot** [comment]
Ouaip, thanks. Je peux enfin bosser sur les catégories et les sous-catégories des tutoriels. Je fais un PR bientôt.
