### ISSUE TITLE
Notification datées du premier message et non du dernier

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#410]
Les notifications du forum, affichées dans la barre du haut, indiquent l'OP et non le dernier message posté comme on pourrait s'y attendre.

Idem pour les notifications de MP.

**Comment by firm1** [comment]
En es-tu certain ? car ça a été réparé [il y'a peu](https://github.com/Taluu/ZesteDeSavoir/pull/409).

**Comment by Alex-D** [comment]
Je n'ai pas le bug, je considère donc que c'est corrigé par le bugfix de SpaceFox.

**Comment by ShigeruM** [comment]
J'étais pourtant sûr de l'avoir revu juste avant de poster l'issue. Je dois
être fou.

**Comment by Alex-D** [comment]
Il se peut que la MEP soit différée de la correction du bug.
