### ISSUE TITLE
Les filtres de recherche ne fonctionnent plus

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#4101]
[Cette requête](https://zestedesavoir.com/rechercher/?q=test) et [cette requête](https://zestedesavoir.com/rechercher/?q=test&id_models_2=article) renvoient exactement les mêmes résultats, alors que pour la seconde, j'ai demandé uniquement les articles.

Les deux dernières modifications sont #4037 (mettre des unicodes partout par @artragis) et #4010 (fixer le *warning* sur BeautifullSoup par @gasche). Avant ça, la dernière modif date d'il y a 10 mois. Même si je vois pas trop pourquoi une des deux induirait ça.

**Comment by gllmc** [comment]
Salut :)

Ce n'est pas corrigé par #4086 ?

**Comment by pierre-24** [comment]
Bien vu :-°

**Comment by gasche** [comment]
Est-ce qu'on peut avoir des tests de régression pour ça ?

**Comment by pierre-24** [comment]
ça va être difficile, parce qu'il faut une instance de solr qui tourne quelque part. Je vois difficilement comment faire autrement (mais peut être qu'il y a moyen)
