### ISSUE TITLE
Staff : page d'utilisateurs avec la même IP → avec le même réseau en IPv6

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#4103]
En IPv6, une IP (routable) est unique par marche dans l'univers. Par contre, les FAI n'attribuent pas une IP par box, mais N sous-réseaux (N variant de 1 si le FAI est un rapiat à 256 s'il respecte les recommandations).

Donc, une meilleure chance de trouver les doublons serait de lister, dans le cas d'une IPv6, non pas les correspondance d'IP exacte, mais de sous-réseaux.

Ça se fait « facilement » (en excluant quelques cas pathologiques) : les sous-réseaux IPv6 font 64 bits (sur les 128 de l'adresse), il suffit donc de sélectionner toutes les adresses dont les 64 bits sont identiques, ce qui est très facile avec des IPv6 au format canonique (c'est la partie `2001:0db8:0000:85a3` de l'adresse `2001:0db8:0000:85a3:0000:0000:ac1f:8001`, donc les 19 premiers caractères).

**Comment by gllmc** [comment]
Donc finalement, il faut vérifier que l'on a affaire à une IPv6 et, si c'est le cas, rechercher les membres dont l'adresse IP commence par les 19 premiers caractères de l'IP ? Si ce n'est que ça, je devrais pouvoir m'en occuper. :)

**Comment by SpaceFox** [comment]
À vérifier si les IPv6 qu'on récupère sont au format canonique (on trouve
des :0000: dedans) ou compactées (c'est remplacé par ::). Dans le 1er cas
c'est un test direct, dans le second cas il faut trouver un moyen de les
rendre canoniques d'abord.

**Comment by Situphen** [comment]
**Indications pour résoudre ce ticket**

Il va falloir modifier la fonction `member_from_ip` du fichier Python `zds/member/views.py` ainsi que le fichier HTML `templates/member/settings/memberip.html`.

https://github.com/zestedesavoir/zds-site/blob/c4d3dd39c6a780054113d5185fb83bc82f6753be/zds/member/views.py#L1406-L1413

Il faut séparer les deux cas : 

- en IPv4, on souhaite rechercher les membres qui ont *exactement* la même adresse ;
- en IPv6, on souhaite rechercher les membres qui ont *exactement* la même adresse et les membres qui viennent du même réseau (c'est-à-dire pour l'adresse `aaaa:bbbb:cccc:dddd:eeee:ffff:aabb:ccdd` les membres dont l'adresse commence par `aaaa:bbbb:cccc:dddd:`). Les IPv6 sont stockées en base de données sous une forme compactée (par exemple `aaaa:bbbb:0000:0000:cccc:dddd:eeee:ffff` devient `aaaa:bbbb::cccc:dddd:eeee:ffff`) ce qui nous complique la tâche. Le plus simple est probablement d'utiliser la bibliothèque `ipaddress` (présente par défaut dans Python) et sa fonction `ip_network` ([voir la documentation](https://docs.python.org/3.5/library/ipaddress.html#ipaddress.ip_network)) pour trouver l'adresse IP du réseau de l'adresse IP du membre (par exemple pour `aaaa:bbbb:cccc:dddd:eeee:ffff:aabb:ccdd` il s'agirait de `aaaa:bbbb:cccc:dddd::`) et ensuite retirer le dernier ":".

Cela donne approximativement ce code : 

```py
# On recherche les membres qui ont exactement la même adresse IP
members = Profile.objects.filter(last_ip_address=ip_address).order_by('-last_visit')

if ':' in ip_address: # Si c'est une adresse IPv6
    # On récupère l'adresse réseau correspondant à cette adresse IP
    network_ip = ipaddress.ip_network(ip_address + '/64', strict=False).network_ip
    # L'adresse réseau se termine par "::", on enlève le dernier ":" pour récupérer les adresses IP de ce réseau
    network_ip = str(network_ip)[:-1]
    # On recherche les membres qui ont une adresse IP sur le même réseau
    network_members = Profile.objects.filter(last_ip_address__starts_with=network_ip).order_by('-last_visit')
```

Il faudra modifier le gabarit (fichier HTML) pour afficher la liste des membres qui ont exactement la même adresse IP (`members`) et ceux qui appartiennent au même réseau (`network_members`). Il serait bien d'écrire un paragraphe pour expliquer la différence entre les deux listes (car tous les membres du Staff ne connaissent pas forcément cette différence).

Ne pas hésiter à jouer avec le module `ipaddress` pour bien comprendre comme ça fonctionne et poser des questions si besoin !

**Comment by PetitMote** [comment]
Si personne n'est dessus, je vais me pencher dessus, mais je ne promets rien ^^

**Comment by PetitMote** [comment]
Comme vous pouvez le voir, la PR est en cours :slightly_smiling_face:  Quand vous dites que c'est prémâché, c'est bien prémâché quand même xD Mais merci beaucoup, c'est super cool, ça permet de débuter tout doucement dans ce bazar qu'est un gros projet, et sans ça j'aurais jamais réussi. Le plus dur a été de rédiger les tests ^^
