### ISSUE TITLE
[v22] Marquer notifications comme lues : 404

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#4106]
Bug introduit par #4079 (cc @GCodeur :) )

Le bouton "Tout marquer comme lu" présent ici : https://beta.zestedesavoir.com/notifications/
fait un `GET` sur https://beta.zestedesavoir.com/notifications/marquer-comme-lues/ , mais [`mark_notifications_as_read`](https://github.com/GCodeur/zds-site/blob/33f17d80c3bf25607e69f844457e20f5003d6c7c/zds/notification/views.py#L38) n'accepte que `POST`.

**Comment by gllmc** [comment]
Je suis un peu étonné car une requête `POST` est bien effectuée à l'origine. Cependant, celle-ci semble rediriger (via une 301, en plus !) vers la requête `GET`. Pourtant, rien dans la vue ne semble justifier ça et il n'y avait aucun problème en local...

![Capture](https://www.pixenli.com/images/1483/1483387612064693500.png)

**Comment by vhf** [comment]
Je suppose que ça redirige `/ton-url` vers `/ton-url/` ?

**Comment by gllmc** [comment]
En effet, c'est bien ça !

Du coup, j'imagine que mettre `marquer-comme-lues/` comme URL règlera le problème ?

**Comment by vhf** [comment]
Yep. 👍

**Comment by pierre-24** [comment]
C'est fait :)
