### ISSUE TITLE
[zep-13] : résoudre une alerte de tribune redirige vers le boruillon de la tribune

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4113]
Scénario : 

*Vous devez avoir les pouvoirs de staff*

- Allez sur un billet (j'ai essayé avec [celui-ci](https://beta.zestedesavoir.com/tribunes/1691/mon-premier-billet-edite/))
- Signaler le billet : observez que l'url est bien sous la forme `https://beta.zestedesavoir.com/tribunes/id/slug/`
- Résolvez l'alerte : observez que l'url est passé sous la forme `https://beta.zestedesavoir.com/contenus/id/slug/`

Ce n'est pas très grave, mais il serait plus logique de revenir sur la version publique du contenu après avoir résolu l'alerte (ne serait-ce que pour ne pas avoir l'impression pendant un cours instant comme celà a été le cas avec moi que j'ai supprimé les commentaires)

**Comment by artragis** [comment]
Fixed
