### ISSUE TITLE
[zep-13] : le lien de filtrage des tags de tribune ne doit pas filtrer sur l'ensemble des contenus

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4114]
Scénario : 

- Allez la liste de tous les billets : https://beta.zestedesavoir.com/tribunes/

On observer pas mal de billets, certains avec un tag comme celui-ci.

![tribunes-filtre](https://cloud.githubusercontent.com/assets/6066015/21605190/c6e023ba-d1a7-11e6-8add-df1679c908fb.PNG)

Si je clique sur le tag "thème", je suis redirigé ici : https://beta.zestedesavoir.com/contenus/?tag=theme

Le problème est donc que l'url de redirection étant l'url générale des contenus, et que c billet n'a pas été approuvé par le staff, je ne retrouve pas mon billet dans la suite de mon enchainement ce qui n'est pas normal.

La navigation dans l'environnement des billets devrait se suffire à elle même et on ne doit pas avoir des entrée qui nous bloquent.

**Comment by artragis** [comment]
Fixed avec le comportement débattu sur le forum.
