### ISSUE TITLE
[zep-13] Publier une mise à jour de son billet annule la mise en avant par le staff

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4115]
Scénario

- Créer un billet
- Publiez le
- (*en tant que staff*) faite en la promotion pour qu'il passe en home page
- (*vous avez remarquez une faute*) mettez à jour votre billet et republiez le
- Problème : Il a disparu de la page d'accueil

Je n'ai pourtant pas été prévenu de ce comportement lors de la deuxième publication. Cela signifie que je dois impérativement demander à un staff de mettre mon billet en avant (d'ailleurs je n'ai aucun moyen de savoir quel staff a promu mon billet).

Le problème que ça pourrait aussi engendrer est que, chaque fois que je corrige mon billet et qu'il doit être mis en avant, il remontera tout en haut de la home car la notion de publication mineure vs majeure n'existe pas pour les billets (certains pourrait essayer de tricher avec ce système)

**Comment by SpaceFox** [comment]
La disparition est volontaire pour éviter que n'importe quoi se retrouve en
une.

Concernant le second problème, c'est un souci de tri : le billets en une
devraient s'afficher par date de création ou à la limite de première
publication, et non par date de mise en avant ou de dernière modification.

**Comment by firm1** [comment]
> La disparition est volontaire pour éviter que n'importe quoi se retrouve en une.

Je m'attendais au fait que la version mise en avant reste en avant en attendant qu'un staff mettre en avant la version suivante (comme c'est fait aujourd'hui dans le schema brouillon -> publication d'un tuto). Une solution temporaire serait de rajouter un message pour l'expliquer aux auteurs afin qu'il ne soit pas surpris. 

> Concernant le second problème, c'est un souci de tri : le billets en une devraient s'afficher par date de création ou à la limite de première publication

J'aurai dit par date de première publication pour éviter l'effet du bloc instable.

**Comment by vhf** [comment]
> Je m'attendais au fait que la version mise en avant reste en avant en attendant qu'un staff

C'est effectivement le but.

**Comment by pierre-24** [comment]
Donc, que je suive : le comportement attendu est bien "la version sélectionnée du billet reste dans la liste tant que la nouvelle version n'est pas remise en avant ?"

**Comment by firm1** [comment]
> "la version sélectionnée du billet reste dans la liste tant que la nouvelle version n'est pas remise en avant ?"

Tout à fait

**Comment by artragis** [comment]
ça risque d'être chaud à faire. Je pense qu'on ne fera pas.
