### ISSUE TITLE
[zep-13] L'alerte de prévention de la promotion en article d'un billet n'est pas très claire

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4116]
Lorsqu'un billet est promu en article, par exemple [celui-ci](https://beta.zestedesavoir.com/tribunes/1689/billet-dela-mort/) on voit dans une alerte le texte suivant : 

"Ce billet a été promu en article qui est en cours de validation. "

Je ne comprend pas le sens de cette phrase. Il faudrait la reformuler, mais j'ai déjà du mal à comprendre ce que l'on souhaite exprimer ici.

**Comment by pierre-24** [comment]
Qu'un valido a déjà décidé que le billet méritait de passer au niveau supérieur. Qu'est ce que tu voudrait changer ?

(à noter que c'est visible uniquement pour le staff)

**Comment by firm1** [comment]
> Qu'un valido a déjà décidé que le billet méritait de passer au niveau supérieur. Qu'est ce que tu voudrait changer ?

Du coup ça ouvre plusieurs questions ?

- Est-ce que c'est uniquement le staff qui décide qu'un billet doit être promu en article ?
    - si oui : la phrase devrait plutôt être "Ce billet a été identifié par un membre du staff comme pouvant faire l'objet d'un article. Il est donc présent dans la zone de validation des articles."
    - si non : la phrase devrait plutôt être : "Ce billet a fait l'objet d'une demande de publication en tant qu'article. Il est donc présent dans la zone de validation en attente de prise en charge par un validateur."

**Comment by pierre-24** [comment]
Première option, donc :)

**Comment by artragis** [comment]
Fixed
