### ISSUE TITLE
[zep-13] La demande d'aide pour un billet ne fonctionne pas

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4118]
Dans la page d'édition d'un billet, il est possible de sélectionner un type d'aide (rédaction, correcteur, etc). Mais lorsqu'on coche et on enregistre, ça ne conserve pas l'information.

**Comment by SpaceFox** [comment]
Pour moi ça n'a pas de sens de demander de l'aide sur un billet.

**Comment by firm1** [comment]
Pour moi non plus, mais si l'option existe, j'imagine que ça a été demandé ?

**Comment by SpaceFox** [comment]
Ou qu'elle a oublié d'être enlevée ? J'ai l'impression qu'on essaie de rendre ces tribunes bien plus complexes que l'idée d'origine.

**Comment by vhf** [comment]
C'est pas censé être là. On l'a exprès enlevé de la création de billet parce que ça n'a pas de sens.

**Comment by artragis** [comment]
Fixed
