### ISSUE TITLE
[Membre] Possibilité d'uploader un avatar personnalisé

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#412]
Il a été demandé d'avoir la possibilité d'avoir un upload direct plutôt que l'usage d'un service tiers pour la gestion de l'avatar.

Personnellement, je trouve ça plus que secondaire, mais je le mets ici tout de même.

**Comment by ShigeruM** [comment]
Je remets ce que j'ai posté sur le forum, parce qu'aussi insignifiant que ça puisse paraître, c'est franchement chiant à la navigation :

Gravatar c'est sympa mais pour peu qu'on se connecte depuis un endroit où c'est bloqué, alors on n'a plus rien. Dans mes deux dernières boîtes, je ne sais pas bien pourquoi, j'arrive à aller sur le site Gravatar, mais la récupération des avatars depuis les sites qui utilisent le service ne passe pas. Du coup, ça a pour effet de voir la page "charger" indéfiniment (ou en tout cas jusqu'à ce qu'un timeout quelque part intervienne). J'ai le cas sur ZdS, sur PDP, sur Github... Et comme j'ai eu le cas dans deux boîtes différentes, je ne pense pas être le seul dans à avoir le problème, loin de là.

**Comment by coma94** [comment]
En fait on peut déjà, indirectement en utilisant la galerie.Il faudrait juste "lier" la galerie dans la page du profil.

**Comment by ShigeruM** [comment]
Oui on peut déjà utiliser un avatar uploadé sur le site, comme on peut utiliser n'importe quel service externe vu qu'on peut mettre une URL. Mais comme par défaut c'est Gravatar qui est utilisé, la plupart des avatars du site ne se chargent pas si Gravatar est bloqué. En fait je dis Gravatar, mais l'idée est la même avec tout service externe utilisé _par défaut_.

**Comment by SpaceFox** [comment]
Corrigé et mergé --> Fermé
