### ISSUE TITLE
[zep-13] le filtre de validation des billets ne fonctionne pas

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4123]
(*Il faut être staff pour cela*) 

Scénario : 
- Allez dans la zone de validation des articles : https://beta.zestedesavoir.com/validations/?type=article

Vous visualisez dans la *sidebar* quelque chose comme ça : 

![valid-trbuene](https://cloud.githubusercontent.com/assets/6066015/21639123/b95c50b6-d26e-11e6-8fa3-e368d55efeb9.PNG)

- Cliquez sur sur "Billet" et observez que vous avez de tout, comme si on avait demandé d'annuler le filtre.

L'url de cliquant sur le filtre est : https://beta.zestedesavoir.com/validations/?type=opinion
L'url de la validation des billets est : https://beta.zestedesavoir.com/validations/billets/

Donc je suppose que le problème est là.

**Comment by pierre-24** [comment]
En même temps, qu'est ce que cette page devrait renvoyer ?

**Comment by artragis** [comment]
@vhf / @DevHugo tu pourras vérifier? je sais que j'ai galéré lors du merge pour ce qui concerne les filtres. Normellement c'est ok, mais j'aimerais avoir le coeur net.

**Comment by artragis** [comment]
Validé, c'est OK
