### ISSUE TITLE
[zep-13] Message de suppression d'une galerie liée à un billet incorrect

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4124]
Scénario : 

- Allez sur un de vos billet (ou créez en un si vous n'en avez pas)
- Cliquez sur le lien "Allez à la galerie liée" dans la sidebar
- Cliquez sur "Supprimer la galerie" et confirmez

Le message d'erreur rapporté est : "La galerie « À propos des loups » ne peut pas être supprimée car elle est liée au **tutoriel** « À propos des loups »."

Notez le terme tutoriel dans le message en lieu et place de billet.

**Comment by artragis** [comment]
Fixed
