### ISSUE TITLE
[ZEP-13] Le MP de dépublication d'un billet évoque le système de bêta

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4125]
Lorsqu'un billet est dépublié, un MP est envoyé au membre concerné comme pour les autres contenus. Cependant, ce MP mentionne le système de bêta, qui n'existe pas pour les billets.

![Capture](https://www.pixenli.com/images/1483/1483545568072298600.png)

**Comment by artragis** [comment]
Fixed
