### ISSUE TITLE
[zep-13] La date de publication sur la page d'acceuil est incorrecte

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4126]
Lorsqu'un staff approuve un billet sur la *home*, au lieu d'afficher la date à laquelle il a été approuvé (et donc validé en une), on affiche la date à laquelle il avait été publié par le membre.

Voici le MP que j'ai reçu qui montre que mon billet a été publié le 04/01/2017 

![mp-tribune](https://cloud.githubusercontent.com/assets/6066015/21650737/498dfa68-d2a6-11e6-9a6c-6f09544979ac.png)

Et sur la page d'accueil on voit plutôt ceci (qui prétend que mon billet a été validé le 03/01/2017)

![billet-home](https://cloud.githubusercontent.com/assets/6066015/21650999/32b922d0-d2a7-11e6-8699-cbeec7eecd5f.PNG)

On pourrait donc se retrouver avec un tutoriel approuvé, mais qui ne passe pas sur la home parce qu'il avait été publié initialement par le membre depuis.

**Comment by pierre-24** [comment]
Y'a pas de champ "date de mise en avant". Donc forcément, on peut pas trier dessus. J'en rajoute un ?

**Comment by vhf** [comment]
@pierre-24 Oui, mais pas sur les billets stp.

Regarde le dernier point de la section *TODO* ici : https://github.com/zestedesavoir/zds-site/pull/3993

Cette table serait idéale pour avoir notamment le sha de la version choisie et un timestamp.

**Comment by pierre-24** [comment]
Je comprend pas ce que ça change de le mettre là et ... À vue de nez, à ce qui ressemble à un objet `Validation` :)

**Comment by vhf** [comment]
On s'est peut-être mal compris, tu veux le mettre où ce champ "date de mise en avant" ?

**Comment by pierre-24** [comment]
Eh bien:

+ actuellement, les billet, mis en avant ou pas, sont triés par leur `pubdate`. Cette `pubdate` n'est jamais mis à jour, car les billets sont publiés en "modification mineure" (pour éviter que les auteurs jouent avec pour mettre leur billet en avant, j'imagine).
+ Ça signifie que si un billet est créé il y a trois mois, subit plusieurs màj et mérite finalement d'être mis en avant, il y a des chance qu'il n'apparaisse jamais en page d’accueil.

Deux solution à ça, selon moi : 

+ Soit on rajoute un champ `date_picked` dans l'objet `PublishedContent`, et on trie sur ça sur la page d'acceil ;
+ Soit on met à jour la `pubdate` quand le billet est choisi, ce qui aura le même effet MAIS le remontera également dans la liste des billets de manière générale.

Non ? :)

**Comment by pierre-24** [comment]
Quand à tes trois derniers TODOs, dans ma tête, pour implémenter ça, il "suffit" d'éttendre [l'objet `Validation`](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/models/models_database.py#L916) en lui donnant de nouveau statuts (`PICKED`, `UNPICKED`, `MASK`, `UNMASK`, ...), en demandant à chaque fois la raison et en la stockant dans l'objet (alors qu'aujourd'hui, question validation, y'a rien qui se passe au niveau des billets)

**Comment by vhf** [comment]
Du coup tu es d'accord que ce champ `date_picked` dans `PublishedContent` est inutile puisqu'on aura aussi toutes les dates auxquelles un billet a été choisi et qu'il suffit de prendre la dernière ?

Pour l'histoire de l'objet Validation je préfère qu'on ne s'en serve pas ici. Ce serait une mauvaise abstraction. Les billets n'ont pas de validation, gardons la validation pour ce qui a une validation.

**Comment by vhf** [comment]
En fait je suis pas fondamentalement contre étendre Validation, mais dans ce cas il faut le renommer en je sais pas quoi et Validation pour les tutoriels et articles en héritera. 

StaffContentAction ou je sais pas,  toute suggestion bienvenue.

**Comment by pierre-24** [comment]
> Du coup tu es d'accord que ce champ date_picked dans PublishedContent est inutile puisqu'on aura aussi toutes les dates auxquelles un billet a été choisi et qu'il suffit de prendre la dernière ?

Le fait est que c'est déjà le cas pour la date de publication, qui existe elle aussi dans l'objet Validation. Maintenant, ce que tu propose donne une requête un peu tordue : `Validation.objects.get(status='PICKED').select_related('content').distinct().order_by('date_validation')` (ou un truc du genre), ce qui me rappelle un peu ce qui se fait pour la *topbar*, et qui est pas hyper-génial.

> En fait je suis pas fondamentalement contre étendre Validation, mais dans ce cas il faut le renommer en je sais pas quoi et Validation pour les tutoriels et articles en héritera.

Ben je vois pas, à part les statuts, ce qui changerai fondamentalement (au niveau des méthodes ou des champs) entre cet éventuel objet et l'objet [`Validation`](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/models/models_database.py#L916) déjà existant, à par éventuellement `date_proposition` et `date_reserve`, qui d'ailleurs ne sont remplis que quand les statuts sont `PENDING` et `PENDING_V`. Si tu trouve que ça ce justifie, soit, mais voilà.

D'autant que fondamentalement parlant, mettre un billet en avant EST (non ?) un acte de validation, défini comme tel dans le code et effectué en pratique par les validateurs :) Du coup, ça me semble pas déconnant d'étendre l'objet `Validation` pour ça.

**Comment by vhf** [comment]
Ton argument pour la requête se tient tout à fait. Du coup ajoute un champ `date_last_picked` ?

Pour la question de validation c'est pour moi une question sémantique. J'aimerais éviter au maximum les confusions, avoir le code le plus compréhensible possible. C'est pour ça que le code de la ZEP-13 n'utilise jamais pas le même champ lexical que les autres contenus à ce propos, et tout particulièrement évite les termes  "validation", "validé", etc.

Les concepts sont différents, leur implémentation peut être en partie commune mais dans ce cas il faut que l'abstraction utilisée par les deux ait un sens pour les deux. Du coup on ne devrait pas hériter d'un modèle nommé "Validation". On peut avoir une implémentation commune comme je disais, mais les billets n'étant pas soumis à validation (au sens utilisé dans le code et dans la doc et sur le site), le mot validation ne convient pas.

Le principe c'est que quasiment tous les billets seront 'choisis' et finiront en page d'accueil (du moins jusqu'à l'implémentation d'un système de vote par +1/-1). Seuls les billets "louches" ou borderline niveau CGUs du site seront "pas choisis" par le staff.

Pour logger ces actions, je dirais que l'action "choisir" un billet ne devrait pas requérir de "raison". L'action "dé-choisir" et l'action "pas choisir" devraient quant à elles requérir une raison.

**Comment by pierre-24** [comment]
> J'aimerais éviter au maximum les confusions, avoir le code le plus compréhensible possible. C'est pour ça que le code de la ZEP-13 n'utilise jamais pas le même champ lexical que les autres contenus à ce propos, et tout particulièrement évite les termes "validation", "validé", etc.

Je suis au regret  [de démentir](https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-f2064ec573e3eb343c9c83f99dc36109R643), même si je suis tout à fait d'accord que c'est pas clair, donc je suis  pour le changement à 150% (ça devrait être `PickOpinion`, en fait, et pareil pour le formulaire associé). Je note ça quelque part, parce que je m'étais justement fait la réflexion, mais que je croyais que c'était fait exprès (et du coup, j'ai "inventé" le terme ["invalidation"](https://github.com/zestedesavoir/zds-site/pull/4143/files#diff-eb19aab06dd17de7178922cad32beabbR1149), qui ne veut rien dire).

> Le principe c'est que quasiment tous les billets seront 'choisis' et finiront en page d'accueil (du moins jusqu'à l'implémentation d'un système de vote par +1/-1). Seuls les billets "louches" ou borderline niveau CGUs du site seront "pas choisis" par le staff.

Je vous laisse discuter de ça en interne, c'pas ma popote.

> Les concepts sont différents, leur implémentation peut être en partie commune mais dans ce cas il faut que l'abstraction utilisée par les deux ait un sens pour les deux. Du coup on ne devrait pas hériter d'un modèle nommé "Validation". On peut avoir une implémentation commune comme je disais, mais les billets n'étant pas soumis à validation (au sens utilisé dans le code et dans la doc et sur le site), le mot validation ne convient pas.

Ok. Mais je t'avoue que je vois pas comment l’appeler d'autre pour que ça garde du sens quand on le fait hériter à `Validation` :p

**Comment by pierre-24** [comment]
> Ton argument pour la requête se tient tout à fait. Du coup ajoute un champ `date_last_picked` ?

Yup :-)

**Comment by vhf** [comment]
Yep, il reste quelques erreurs à corriger quand on fera une grosse revue du code de la ZEP-13.

> Ok. Mais je t'avoue que je vois pas comment l’appeler d'autre pour que ça garde du sens quand on le fait hériter à `Validation`

Je propose l'inverse : un modèle qui englobe le 'choix' des billets et la 'validation' des articles. Je ne propose pas de faire hériter quoi que ce soit à Validation, je propose que Validation hérite d'un modèle plus général dont le choix des billets hériterait également. :)

**Comment by pierre-24** [comment]
C'est ce que je voulais dire, mais justement, j'arrive pas à trouver un nom
qui me satisfasse pour ce méga objet et qui ne comprends pas Validation :(

**Comment by vhf** [comment]
Je propose hmm

```
      ContentDecision
Validation        Picking
```

Comme ça on a un *validation workflow* et un *picking workflow*.

**Comment by pierre-24** [comment]
J'approuve :)

**Comment by artragis** [comment]
Normallement fixed.
