### ISSUE TITLE
[PAL] MariaDB VS PostgreSQL

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#413]
Suite à la dérive de l'issue #358 j'en arrive à la question suivante : 
Est-ce que le choix de PostgreSQL est justifié ? Et est-ce le meilleur choix dans notre cas ?

Je m'explique : je me disais que PostgreSQL était un bon choix, mais lorsque je m’aperçoit que les articles et tutos sont en fait gérés au format fichier (avec git et tout) il ne reste en gros que les membres, commentaires et forums dans la base. Il n'y a donc a priori pas de notion de transactions ni autres fonctionnalités poussées qui soit utilisées et nous n'avons pas nécessairement besoin de PostgreSQL. MariaDB semble du coup être une alternative plus légère et peut-être plus adaptée.

À chacun de donner son avis, tant que l'on tranche avant la sortie du site.

**Comment by SpaceFox** [comment]
>  Il n'y a donc a priori pas de notion de transactions qui soit utilisé et
> nous n'avons pas nécessairement besoin de PostgreSQL.

Sisi, y'a des transactions (c'est d'ailleurs moi qui les ai rajoutées),
dans les cas où une action affecte plusieurs tables à la fois.
Mais ce n'est pas un critère de choix, puisque MySQL les gère depuis au
moins la v5.0.

Je suis en train de tester PostgreSQL sur ma VM, j'avais déjà testé MySQL.

**Comment by SpaceFox** [comment]
> Je suis en train de tester PostgreSQL sur ma VM, j'avais déjà testé MySQL.

En fait je peux pas, à cause du bug #356 ...

**Comment by Alex-D** [comment]
Du coup, quid d'une migration vers MariaDB dès la fin de la BETA Fermée ?

**Comment by SpaceFox** [comment]
Pour le coup, il faudrait vraiment faire un test comparatif. C'est encore
le meilleur moyen de choisir.

2014-05-03 0:42 GMT+02:00 DEMODE Alexandre notifications@github.com:

**Comment by SpaceFox** [comment]
Premiers enseignements :
- En dev, le facteur limitant est Python, le SGBD n'a aucune influence (sauf peut-être en s'amusant avec Sqlite, mais je ne suis pas vicieux à ce point). C'est normal mais ça mérite d'être signalé, ça veut peut-être dire que le problème #407 du nombre de requêtes n'est pas si grave que ça
- Le cache qu'a activé @firm1 est efficace, je fais envion x2 sur les perfs :)
- Sans la moindre configuration et toujours en mode dev (autant dire que ça ne vaut pas grand-chose), PostgreSQL a l'air un poil plus rapide surtout sur les créations de posts. Par contre à "haute" charge on atteint un ralentissement généralisé plus vite. Ca nécessite un vrai test sur un vrai serveur (la PRP) demain.

**Comment by SpaceFox** [comment]
Correction : PostgreSQL a l'air un poil plus _lent_, sauf sur la création de posts, mais il a réussi à me caser plus de résultats pendant les 10 minutes du test.
Bref, c'est bizarre et on ne peut pas en tirer grand-chose ce soir, sauf qu'il n'y a pas une différence majeure en dev (et donc qu'on a pas un problème majeur avec la BDD).

**Comment by SpaceFox** [comment]
Messieurs, j'obtiens quelque chose de très étrange...

# Scénario

Comparaison MySQL / PostgreSQL, recherche des limites.

## Comportement des VU (Virtual Users)
1. Affichage de la home
2. Login
3. Affichage de la liste des forums
4. Affichage d'un nombre aléatoire de forums
5. Ajout d'un post dans l'un des forums
6. Déconnexion

Le tout avec des temps de réflexion variables selon l'action.

Les SGBD sont laissés avec leurs configuration par défaut.

## Charge envoyée

Tests de 10 minutes, rampe constante de 10 à 100 VU

# Première constatations

## Sur le comportement général de l'application

Globalement c'est pas ultime en préprod, on est rarement sous la demi-seconde, et fréquemment au-delà de la seconde de réaction.
Cela dit sachant que la préprod est une VM qui subit des lags (parfois un simple `tab` dans SSH suffit), c'est pas très surprenant.

Les temps de réponse restent fixes jusqu'à entre 30 et 60 VU, ce qui est bien mais pas top. C'est haut, mais c'est un nombre que j'espère atteindre un jour :)

## Sur le travail des bases de données

Les bases de données ne foutent rien. Vraiment. Une fois j'ai vu passer MySQL à 3% d'utilisation d'un CPU dans mon `htop`, c'est tout.

**Conséquence** : contrairement à ce qu'on avait craint, le fait qu'on voie passer des centaines de requêtes dans la debug bar n'est pas un problème en soit : soit ces requêtes sont tellement rapides qu'elles n'ont pas d'impact, soit elles sont en cache et n'atteignent jamais le SGBD.

## Sur le facteur limitant des performances

C'est à 100% le CPU, sur les processus Python.
D'ailleurs je pense qu'on devrait faire comme le conseille la doc de Gunicorn, et attribuer _(NB_CPU + 1)_ workers au lieu de _(NB_CPU)_ à Python.

On a aucune I/O disque, le réseau est très largement sous-utilisé et il reste des quantités énormes de RAM à disposition.

## Sur l'influence du SGBD

Si les SDBD ne foutent rien, ce n'est pas pour ça qu'ils n'ont aucune influence sur les résultats. Je suppose que la différence vient de la couche SGBD <---> Python.

Si je ne m'explique pas les résultats, ils sont parfaitement reproductibles :

### À faible charge

À faible charge les résultats sont pratiquement identiques.

PostgreSQL semble un poil plus réactif, mais d'une ce n'est pas franc, de deux on rentre dans les aléas provoqués par la VM.

### Dès que la charge monte...

L'application sous MySQL **se comporte beaucoup mieux** que l'application sous PostgreSQL.
Je suppose que la couche d'interaction consomme plus de puissance avec PostgreSQL qu'avec MySQL, peut-être est-ce une conséquence de la plus grande complexité de ce premier (qu'il faut gérer).

En tous cas les résultats sont là : 
- 3520 échantillons en 10 minutes avec PostgreSQL, 4470 avec MySQL
- Une médiane des temps de réponse à 3804 ms avec PostgreSQL, 2047 avec MySQL
- Une augmentation sensible de la latence des réponses vers 4 minutes / 50 VU avec PostgreSQL, contre 6 minutes / 80 VU avec MySQL
- Un plafonnement de l'envoi vers 900 ko/s (27 hits/s) avec PostgreSQL, contre 1,2 Mo/s (34 hist/s) avec MySQL
- Affichage de topic : plafonnement vers 3 à la seconde avec PostgreSQL, contre 4 avec MySQL

La conclusion est simple claire : dans l'état actuel des choses, **le serveur s'effondrera plus vite si on utilise PostgreSQL que si on utilise MySQL**

# Et ensuite ?

Je vais relancer une paire de tests, mais cette fois-ci "de robustesse" : même scénario, mais sur une durée longue (1h), avec un nombre de VU raisonnable et constant.

But de la manœuvre :  comparer les deux solutions en utilisation "normale" et vérifier que sur la durée, on a pas de surprise (même si c'est moins important que sur une application Java où il y a un serveur allumé en permanence qui peut crasher).

**Comment by geoffreyc** [comment]
A noter: la preprod est un container (openvz), similaire au vps de la
prodb(OVH utilise aussi des containers pour les vps). Niveau RAM on est
pareil pour les deux, je vais augmenter le vCores a 3 pour que ça soit
pareil que la prod aussi. Donc sache que niveau perfs, tu auras casi la
même chose en prod qu'en preprod.

**Comment by SpaceFox** [comment]
Nickel, tu me préviens quand c'est fini ?

**Comment by geoffreyc** [comment]
C'est fait c'est fait ;) peut un reboot serait requis

**Comment by SpaceFox** [comment]
Je reboote, puisque je ne vois pas le 3ème CPU :)

**Comment by SpaceFox** [comment]
T'es sûr de ton coup là ?
J'ai rebooté et je ne vois pas de changement :

```
root@server3:~# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz
stepping        : 9
cpu MHz         : 3400.006
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dts tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips        : 6800.01
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz
stepping        : 9
cpu MHz         : 3400.006
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 1
cpu cores       : 4
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dts tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips        : 6800.01
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
```

**Comment by geoffreyc** [comment]
Et maintenant ?

**Comment by geoffreyc** [comment]
Haha je changé la mauvaise VM :p c'est bon maintenant !

**Comment by SpaceFox** [comment]
Maintenant j'en vois 4. C'est normal ?

**Comment by geoffreyc** [comment]
Oui oui c'est a cause de mes gros doigts ! Je suis sur mon smartphone ^^
c'est bon pour de vrai!

**Comment by SpaceFox** [comment]
Yay nickel ! Merci de t'être emmerdé avec ton smartphone pour faire ça :)

2014-05-03 16:11 GMT+02:00 geoffreyc notifications@github.com:

> Oui oui c'est a cause de mes gros doigts ! Je suis sur mon smartphone ^^
> c'est bon pour de vrai!

**Comment by geoffreyc** [comment]
No soucis, au besoin je suis la ;)

**Comment by SpaceFox** [comment]
Haha, en fait mes résultats sont tellement bizarres que si j'en trouve le courage, j'en ferai un article :D

**Comment by SpaceFox** [comment]
# Scénario

Comparaison MySQL / PostgreSQL, robustesse

## Comportement des VU (Virtual Users)
1. Affichage de la home
2. Login
3. Affichage de la liste des forums
4. Affichage d'un nombre aléatoire de forums
5. Ajout d'un post dans l'un des forums
6. Déconnexion

Le tout avec des temps de réflexion variables selon l'action.

Les SGBD sont laissés avec leurs configuration par défaut.

## Charge envoyée

Tests de 1 heure. 60 Virtual Users (VU), montée en charge 1 minute, constant ensuite.

La VM avait cette fois 3 CPUs, Gunicorn a été lancé avec 4 workers.

# Résultats

## Limitations

La limitation est toujours le CPU / Python.

Cela dit, le tests est sous la limite de saturation du serveur : il n'a pas été ralenti par le matériel.
PostgreSQL a eu le temps de produire 30122 échantillons, MySQL 31427 (4% de différence).

## PostgreSQL vs MySQL

Le vainqueur est **MySQL**, sans aucun doute possible.

Tous les résultats suivants sont sur environ 2500 échantillons, sauf l'affichage de topics supplémentaires qui se fait sur 13500 échantillons.

En supposant que dans tous les cas PostgreSQL, qui est notre solution aujourd'hui, a une base 100 :

### En considérant les temps moyens

Le temps de réponse de MySQL va de 91% de celui de PostgreSQL (Home page) à 62-63% de celui-ci (Home des forums, déconnexion). Sur l'ensemble des requêtes, MySQL a un temps de réponse moyen de 84% du temps de réponse moyen de PostgreSQL.
- Forum 62%
- Disconnect    63%
- Login 67%
- Topic 72%
- New post  83%
- Login page    83%
- Additional topics 90%
- Home  91%

### En considérant les temps médians

Ce qui nous permet d'éliminer l'influence des lags : l'effet est encore plus visible : MySQL a un temps de réponse médian de 64% du temps de réponse médian de PostgreSQL.
L'effet est général, mais beaucoup dû à la déconnexion : MySQL sert 50% des déconnexions en 26 ms ou moins !
- Disconnect    12% (il n'y a pas d'erreur, on pase de 226 ms à 26 ms !)
- Forum 59%
- Additional topics 64%
- Login 64%
- Topic 66%
- New post  67%
- Login page    75%
- Home  86%

## Tentative d'explication

Je suppose toujours que la différence vient du composant qui fait la connexion entre Python et le SGBD. Dans les deux cas, les processus des SGBD ne font à peu près rien.

Je remarque en particulier les deux choses suivantes :
1. La consommation CPU moyenne est d'environ 85% avec PostgreSQL contre environ 60% avec MySQL.
2. Les I/O réseau sont d'environ 1 400 000 avec PostgreSQL contre environ 600 000 avec MySQL, soit moins de la moitié !

A noter que je ne sais pas exactement ce que sont ces I/O réseau. Ce ne sont pas les données reçues par jMeter, puisque celles-ci sont mesurées par ailleurs et stables à environ 1,1 Mo / seconde, quel que soit le SGBD (ce qui est logique, puisque dans les deux cas on a fait approximativement le même nombre de requêtes).

Je n'ai aucune explication de ce phénomène.
Mes recherches sur le net n'ont abouti qu'à des messages du style _"Il faut utiliser PostgreSQL parce que c'est mieux"_, comme d'hab sans aucune justification ni aucun test.

# Conclusion

À moins que quelqu'un ne trouve un réglage foireux dans un coin, la conclusion est claire : vue notre application, nous devrions utiliser MySQL.

**Comment by amorison** [comment]
J'ai juste une question de néophyte : on a une idée des barres d'erreurs sur ce genre de mesures ?

**Comment by SpaceFox** [comment]
En général, les écarts-types sont assez importants, surtout sur des VMs comme celle-ci qui peuvent être sujettes aux lags dus à des causes extérieures.

Sinon, tous les résultats sont ici : https://github.com/Taluu/ZesteDeSavoir/tree/tests-charge/tests/jMeter/Resultats

**Comment by SpaceFox** [comment]
PS : au cas où, toutes les bases sont en UTF-8, MySQL utilise exclusivement InnoDB comme moteur de stockage. PostgreSQL 9.1, MySQL 5.5, dernières MAJ Debian.

**Comment by firm1** [comment]
> Je suppose toujours que la différence vient du composant qui fait la connexion entre Python et le SGBD. 

Pour information quel connecteur utilise tu pour Mysql ?

**Comment by SpaceFox** [comment]
MySQLdb - en fait celui qui est recommandé dans la plupart des docs que
j'ai vues.
L'autre (dont j'ai oublié le nom) m'a joyeusement explosé à la gueule quand
j'ai essayé :)

**Comment by firm1** [comment]
> MySQLdb - en fait celui qui est recommandé dans la plupart des docs que
> j'ai vues.

**[Django doc a écrit](https://docs.djangoproject.com/en/dev/ref/databases/#mysql-db-api-drivers)**

> The Python Database API is described in PEP 249. MySQL has two prominent drivers that implement this API:
> - MySQLdb is a native driver that has been developed and supported for over a decade by Andy Dustman.
> - MySQL Connector/Python is a pure Python driver from Oracle that does not require the MySQL client library or any Python modules outside the standard library.
> 
> Both drivers are thread-safe and both provide connection pooling. The major difference is that MySQL Connector/Python supports **Python 3**.

**Comment by SpaceFox** [comment]
Si tu me fais fonctionner le "MySQL Connector/Python" sur la préprod, je veux bien relancer un test de charge.
Mais je soupçonne que notre différence de perfs vient aussi du fait qu'on utilise un driver natif avec MySQLdb.

**Comment by SpaceFox** [comment]
BTW la doc Django dit aussi :

> MySQL Connector/Python is available through two release branches: Generally Available (GA, currently 1.0.x) and Development (Dev, currently 1.1.x beta). The Django adapter is currently only available in the **Dev branch.**

**Comment by firm1** [comment]
Je faisais surtout référence à mon texte pour préciser que migrer sous Mysql nous interdit de migrer un jour sur Python 3. Est-ce qu'on veut vraiment ça ?

**Comment by SpaceFox** [comment]
C'est justement pour répondre à cette question que je proposais d'essayer
l'autre driver.

BTW, ça ne nous interdit pas de migrer "un jour" sur Python 3, mais nous
interdit de migrer "maintenant" sur Python 3. Or, "maintenant" on ne peut
pas (à cause de Git). Je suis d'accord que c'est pas vraiment une raison :
peut-être que python3-git sortira avant MySQLdb-python3 - et là on aura
l'air cons.
Mais soyons précis dans les contraintes :)

**Comment by firm1** [comment]
Peut-être que lorsque MysqlDb-python3 sortira les perfs auront diminués ?

Mais avec des SI on peut construire un temple doré :D

**Comment by SpaceFox** [comment]
Le plus étrange ça reste quand même que sur la préprod, on utilise
psycopg2, qui si j'en crois ce tableau
http://wiki.postgresql.org/wiki/Python est un driver natif.

**Comment by SpaceFox** [comment]
J'ai réussi à installer le driver, mais j'arrive pas à l'utiliser... test
en cours.

**Comment by SpaceFox** [comment]
Bon, résultat des courses :
- PostgreSQL est théoriquement meilleur, mais son connecteur (psycopg2)
  semble relativement lent, et j'ai la forte impression que personne ne le
  maîtrise correctement dans l'équipe.
- MySQL via le connecteur MySQLdb est le choix officiel de Django (le
  backend fourni par Django ne supporte _que_ ce connecteur), mais ne
  permet pas pour l'instant l'utilisation de Python 3. Aucune date visible
  dans le support de Python 3.
- MySQL via le connecteur Connector/Python nécessite l'utilisation du
  backend inclus dans le connecteur pour s'interfacer avec Django. Or :
  1. Ce backend nécessite une magouille pour fonctionner avec South
  2. Ce backend ne fonctionne pas avec South et Django 1.6 (erreurs
     "PendingDeprecationWarning: 'commit_unless_managed' is now a no-op.").

Alors, on fait quoi ?

**Comment by firm1** [comment]
> Alors, on fait quoi ?

Je n'ai pas de réponse à cette question, pour le moment

**Comment by SpaceFox** [comment]
J'ai fermé ça moi ? C'est une erreur, il nous reste une question en suspens.

BTW ça veut dire quoi "PAL" dans le titre ?

**Comment by Alex-D** [comment]
PAL = Parole au lecteur :)

**Comment by SpaceFox** [comment]
Bilan des courses :
- Je n'ai pas trouvé de point bloquant dans notre utilisation de MySQL à travers la doc.
- On a aucune requête lourde ou complexe
- La BDD ne fout globalement pas grand-chose, donc le SGBD en lui-même n'a pas grande importance.
- On est bloqué à Python 2 par le connecteur Git
- De toutes façons, d'après certains professionnels, Django-python3 n'est pas encore prêt pour la prod (Django 1.6 est la première à supporter officiellement python 3)
- Le connecteur Python-MySQL est _beaucoup_ plus efficace que le connecteur Python-PostgreSQL :
  - Cf tous les résultats ci-dessus
  - Cf les logs Munin : django-munin mesure les temps de réalisation complets de requêtes SQL via Django. Les deux serveurs ont approximativement la même puissance. Les temps moyens pour insert / select / delete sont de 34,72 / 2,64 / 7,57 ms pour PostgreSQL vs 1,55 / 0,567 / 1,67. Soit un rapport de x22,4 / x4,66 / x4,53 en faveur de MySQL
- Il semble clair que l'équipe en place maîtrise MySQL au moins aussi bien que PostgreSQL, quand ce n'est pas carrément mieux.

**Conclusion :** on migre à MySQL (et j'essaie de trouver le temps de faire un article là-dessus)
