### ISSUE TITLE
[zep-13] signaler une faute dans un billet crée le MP mais pas de notif

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4132]
Scénario : 

- Allez sur un billet publié
- Cliquez sur le bouton "Signaler une faute dans ce billet"
- Remplissez la zone de texte avec du texte ("test" par exemple)
- Cliquez sur Envoyer

Allez ensuite dans la [liste de vos MP](https://beta.zestedesavoir.com/mp/) et constatez que vous avez un message qui n'est pas lu, mais qui ne remonte pas dans vos notifications de messagerie. Si vous n'étiez pas allé dans cette zone, vous n'auriez jamais vu ce message non lu.

**Comment by pierre-24** [comment]
ça a du être réglé depuis, parce que j'arrive pas à reproduire : 

![screenshot from 2017-01-12 22 23 09](https://cloud.githubusercontent.com/assets/7889675/21908839/d09e7ddc-d915-11e6-95ed-3730c7601311.png)

(par contre, le MP ne cause pas de billet, donc ça je corrige)
