### ISSUE TITLE
[zep-13] Les billets sont absents de la recherche

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4133]
Il m'est impossible de retrouver un billet en passant par la recherche du site (cases cochées ou non)

**Comment by pierre-24** [comment]
"normal".

Je suis pas sur, vu comment la recherche est codée (puisque ladite recherche fait la différence entre article et tuto), que le moindre billet sois indexé. Ceci étant dit, ma PR sur Elasticsearch est quasi prête, et mon but (en tout cas c'est comme ça que je l'imagine) est d'attendre la ZEP-13 pour l'achever (justement pour tenir compte de cette histoire de "validatin"). Du coup, est ce que ça vaut la peine de ce casser le c\*\*\* pour qu'au final ma PR refasse le job ?

@vhf ?

**Comment by firm1** [comment]
Ce n'est pas dramatique si les tribunes sortent sans la recherche dessus je pense. ça peut arriver dans une autre itération. Mais je tenais quand même à noter le souci dans une issue, parce que sinon c'est oublié

**Comment by pierre-24** [comment]
~~J'me le met dans la liste de tickets de ma PR pour le garder de vue.~~ (bordel, moi et le français, pour le moment ... ça veut rien dire!)

Je le met dans la liste des *issues* résolues par ma PR afin d'y jeter un coup d'oeil de temps à autre.

**Comment by pierre-24** [comment]
Bon, au final, elastic est arrivé avant la ZEP-13. La question reste : on indexe les billets ? Tous? On discriminé sur la mise en avant ou pas ?

**Comment by vhf** [comment]
@pierre-24 question pour @FanJiyong à mon avis. :)

**Comment by artragis** [comment]
Question toujours d'actualité.

**Comment by pierre-24** [comment]
D'autant si on touche au bout !

**Comment by vhf** [comment]
Ok alors on indexe les billets, mais uniquement ceux publiés, et uniquement leurs versions actuellement en ligne. Partons sur un boost de 2 sur les billets en avant, et 1 sur les autres.

**Comment by artragis** [comment]
Done, thx @pierre-24
