### ISSUE TITLE
La publication d'un contenu pour la deuxième fois conserve les anciens auteurs

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4134]
Scénario : 

- créez un billet
- ajouter un auteur
- publiez le billet : observez bien que le billet est publié avec deux auteurs
- allez sur le brouillon de votre billet et modifiez l'introduction
- éditez le billet pour supprimer le deuxième auteur
- republiez ensuite le billet

**Problème** : la version publique du billet contient encore le 2nd auteur. Pas moyen de le faire partir donc.

**Comment by pierre-24** [comment]
Mmmh :s 

Je suis presque convaincu que c'est un problème général aux contenus, ça (*versionning*, toussa). À vérifier avec un autre type de contenu.

**Comment by firm1** [comment]
Bien vu, c'est général à tous les contenus, je supprime donc le tag zep-13

**Comment by artragis** [comment]
et c'est pas normal justement. le but est qu'à la republication si l'auteur n'existait pas il n'a pas à y être.

**Comment by firm1** [comment]
Oui oui, c'est pour ça que j'ai supprimé le tag zep-13 et gardé juste l'issue car le problème est général aux contenus

**Comment by Karnaj** [comment]
[Ça se passe ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/publication_utils.py#L127) je pense, on rajoute les auteurs à la liste d'auteurs, mais cette liste n'est pas forcément vide, elle contient les anciens auteurs si une version du tutoriel avait déjà été publié vu [comment on crée `public_version`](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/publication_utils.py#L100).

**Comment by artragis** [comment]
AH ok je comprends c'est une question de "version majeure" du coup.

**Comment by Karnaj** [comment]
Pourquoi ce serait lié à si c'est une mise à jour majeure ? On récupère la version publique (et donc les anciens auteurs) dans tous les cas non ?

PS : mais on peut tester, j'ai demandé la validation du tutoriel Ruby sur la bêta. Ce serait bien si quelqu'un pouvait le valider en mise à jour majeure pour qu'on voit si la mise à jour d'auteurs est prise en compte.

**Comment by artragis** [comment]
tu as raison @Karnaj ça ne change rien. Le retrait d'auteur est inopérant actuellement et c'est un vrai bug.

**Comment by Karnaj** [comment]
On peut rajouter le tag facile je pense. Il suffit d'utiliser `clear` sur la liste des auteurs avant le `for` normalement. Et de rajouter le test qui va bien.
