### ISSUE TITLE
Import d'une archive de tuto

### ISSUE THREAD

**Issue by Anto59290** [zestedesavoir/zds-site#4137]
Lorsque j'importe une archive de tutoriel (valide, à ma connaissance) j'obtiens l'erreur suivante : 

Le fichier "les-bases\la-photographie-numerique/introduction.md" n'existe pas dans l'archive.

Deux problèmes : 

- Le fichier en question existe bien...
- Mais Zds semble se mélanger les pinceaux entre slash et anti-slash.

L'archive peut être envoyé en MP si quelqu'un souhaite constater. Je l'ai réalisé avec l'outil de compression de windows. Ceci pourrait expliquer cela ?

**Comment by pierre-24** [comment]
Tu peux me l'envoyer que je regarde, mais effectivement, y'a des choses bizarres au niveau des "/" et "\\". La question étant : d'où provient cette archive ?

**Comment by Anto59290** [comment]
Je te fait parvenir ça durant le week end. L'archive vient de Zest Writer il me semble (à vérifier).

**Comment by Anto59290** [comment]
Ticket à clore. On a regardé de plus prêt avec @firm1 et le problème vient de Zest Writer. Il y un mélange entre / et \ dans le manifest produit par ZW. Ça induit donc Zeste de Savoir en erreur, mais on ne peut rien y faire.

**Comment by pierre-24** [comment]
Ok :)
