### ISSUE TITLE
Migrer de PostgreSQL à MySQL

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#415]
Suite aux résultats des tests faits dans l'issue #413 , il faudrait utiliser MySQL et non PostgreSQL dans les environnements de runtime.

(Oui, c'est bizarre d'écrire cette phrase _dans ce sens là_.)

**Comment by Alex-D** [comment]
Je suggère MariaDB plutôt que MySQL, car réellement libre et qui a vocation à se développer davantage que MySQL.

**Comment by SpaceFox** [comment]
Le jour où il sera dans les dépôts officiels de notre serveur :)

**Comment by SpaceFox** [comment]
(Et en supposant que MariaDB accepte les mêmes connecteurs Python que MySQL. Parce que dans le cas contraire, il faut que je refasse tous mes tests).

**Comment by Alex-D** [comment]
Pourquoi attendre que ce soit dans les dépôts officiels alors que c'est stable, testé et approuvé et que Debian a toujours 2 ans de retard ?

MariaDB est un fork de MySQL, à tel point que même la commande est "mysql". Après si vous préférez les trucs qui vont ne plus être maintenus des masses à des systèmes vivants et avec une communauté active, soit.

**Comment by Alex-D** [comment]
Les connecteurs seront strictement identiques puisque MariaDB se veut compatible avec toutes les interfaces MySQL.

**Comment by SpaceFox** [comment]
> Après si vous préférez les trucs _qui vont ne plus être maintenus_

Source ?

**Comment by SpaceFox** [comment]
Source aussi ?
Je me méfie énormément des "se veut compatible" alors que l'installation du
connecteur en question a nécessité les paquets de développement et lancé
une compilation.

Et oui, c'est le boulot du sysadmin de faire chier pour avoir des trucs
stables sur son serveur :)

2014-05-03 23:35 GMT+02:00 DEMODE Alexandre notifications@github.com:

**Comment by SpaceFox** [comment]
Stables et à jour niveau sécurité d'ailleurs : la liste de sécurité de
Debian ces dernières semaines est assez éloquente de ce point de vue là.
D'ailleurs, y'a eu une alerte sur MySQL pas plus tard que ce matin.

**Comment by Alex-D** [comment]
Bah écoute, restons sur MySQL et puis voilà. Pas envie de me prendre la tête, je m'occupe pas du back de toute façon.

**Comment by SpaceFox** [comment]
Puisque je suis dans un bon jour, je développe : on parle ici d'un serveur
de production. Le genre de bidule sur lequel on ne fait _aucune
*expérimentation,
qui doit tourner 24/24 7/7 sans aucune autre maintenance que *"Tiens, il y
a une MAJ de sécurité, il faut que je l'applique le plus vite possible"_ -
d'autant qu'on a personne à mettre à temps plein sur ce genre de
maintenance.
Les mots-clés dans ce cas là sont sécurité, stabilité et performance.

Autrement dit : pour choisir un composant qui sort du système standard (ici
les paquets standard Debian), il faut que ce composant ait un gain
important dans l'un de ces domaines là (sécurité, stabilité ou performance).
C'était par exemple le cas lorsque le JDK par défaut est devenu OpenJDK,
qui en version 6 avait des problèmes de stabilité connus par rapport au JDK
Sun/Oracle.

Ce n'est pas du tout une attaque personnelle, mais tu dois comprendre que, _en
aucun cas_, des arguments comme\* "*_réellement libre"_ ou\* "qui a vocation
à se développer davantage"\* sont valables pour changer une solution en
prod. Tu m'aurais dit _"MySQL va devenir payant"_ ou _"MariaDB fait x2 sur
les performances de l'application" *ou encore *"MariaDB supporte une
fonctionnatlité indispensable pour nous"_, là c'eut été des arguments
recevables.

De toutes façons, il me semble que MariaDB va être le choix par défaut dans
la prochaine Debian.

2014-05-03 23:42 GMT+02:00 DEMODE Alexandre notifications@github.com:

**Comment by Alex-D** [comment]
Ton argumentaire est un peu skyzo pour le coup, en gros si je suis ton raisonnement on met MySQL, et dans 3 mois quand la prochaine version de Debian sort, on passe sur MariaDB parce que ça sera le truc officiel sur Debian ?

**Comment by SpaceFox** [comment]
Si c'est 100% compatible, oui.

**Comment by SpaceFox** [comment]
(En attente de prise de décision dans la #415)

**Comment by SpaceFox** [comment]
Pour info, si on passe à MySQL, la dépendance à rajouter dans le requirements.txt est `MySQL-python` (on trouve plein de bizarreries sur le net)

**Comment by SpaceFox** [comment]
Vu comment ça se profile, j'ai installé le serveur MySQL sur la prod.
Le mot de passe root est le même que celui PostgreSQL, et pour l'instant il n'y a aucune base. La migration n'est pas encore faite, on a juste un serveur qui tourne à vide.

**Comment by SpaceFox** [comment]
Décision détaillée dans l'issue #413 : on passe bien à MySQL.

**Comment by geoffreyc** [comment]
Yop. Ca va arriver quand tout ca? Je suis entrain de paramétrer
postfix/dovecot et tout le bordel, et si on passe sous mysql, je
l'utiliserais comme bdd pour les comptes mails. Du coup, je peux installer
mysql sur le serveur?

2014-05-13 12:53 GMT+01:00 SpaceFox notifications@github.com:

**Comment by cgabard** [comment]
Oui vas y. je pense que le bon moment va etre a l'ouverture de la prochaine beta, pour le front. ça nous permetra de le tester dans un cadre restreins avant l'ouverture au publique

**Comment by SpaceFox** [comment]
> Du coup, je peux installer mysql sur le serveur?

MySQL _est_ installé sur le serveur :)

Je t'envoie le mot de passe par mail.

**Comment by firm1** [comment]
La produit a migré sur MySQL hier nuit.

Donc je ferme cette issue.

**Comment by Alex-D** [comment]
\o/

Ca va vite !
