### ISSUE TITLE
Faute d'orthographe dans le message automatique des tutoriels

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#4154]
Bonjour,

Pour : "J'ai commencé la rédaction d'un tutoriel au doux nom de « Introduction aux compute shaders » et j'ai dans l'objectif de proposer en validation un texte aux petits oignons. Je fais donc appel à votre bonté **sans limite** pour dénicher le moindre pépin, que ce soit à propos du fond ou de la forme. Vous pourrez consulter la bêta à votre guise à l'adresse suivante :",

On écrit : "sans limites" avec un S http://www.dicoz.fr/sans-limite-ou-sans-limites/

**Comment by gllmc** [comment]
En effet :)

Vous pouvez me l'assigner, je m'en occupe ce soir.

EDIT : finalement, je peux le faire maintenant.
