### ISSUE TITLE
Problème d'encodage pour les MP de Clem

### ISSUE THREAD

**Issue by Luthaf** [zestedesavoir/zds-site#4168]
J'ai reçu un MP de Clem à propos d'une alerte, et le titre du message est: ` (u"R\xe9solution d'alerte : [...]",)`. J'ai l'impression qu'un tuple est affiché directement, et qu'il y a un problème d'encodage quelque part.

Je ne crois pas que le problème touche les MP en général, juste ceux générés par Clem.

**Comment by gllmc** [comment]
J'avais déjà identifié ce problème sur la bêta avec la ZEP-13. C'était sur la prod cette fois-ci, j'imagine ?

Je pense que j'aurai le temps de regarder demain. Personnellement, j'ai l'impression que ça touche uniquement le MP de résolution d'alerte et pas tous ceux de Clem. :)

**Comment by Luthaf** [comment]
Yep, c'est sur la prod.

**Comment by gllmc** [comment]
Je pense que je vois le problème, vous pouvez me l'assigner, je ferai une PR demain.

**Comment by pierre-24** [comment]
Merci @GCodeur !
