### ISSUE TITLE
Mettre en place un minimum de cache

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#417]
Mettre en place un minimum de cache nous permettrait de gagner en rapidité (tenue en charge mais surtout réactivité, cette dernière n'est pas terrible aujourd'hui).

Ressources :
http://progdupeu.pl/tutoriels/152/mise-en-cache-intelligente-avec-django/
https://docs.djangoproject.com/en/1.6/topics/cache/

**Comment by SpaceFox** [comment]
Note : pour ne pas avoir à refaire le travail plusieurs fois, ceci devrait attendre l'intégration HTML de @Alex-D .

**Comment by GerardPaligot** [comment]
Cette issue est-elle réellement nécessaire ? Des efforts ont déjà été fait mais ce n'est pas une tâche qui sera à l'état fini un jour. Il faudra toujours faire attention à l'avenir sur ce point.

**Comment by Eskimon** [comment]
Plutôt d'accord avec @GerardPaligot , du coup je ferme
