### ISSUE TITLE
Utiliser la méthode update pour la désinscription

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4170]
Lors de la désinscription, on recherche actuellement tous les contenus postés par l'utilisateur pour les anonymiser un par un. Cela prend une requête pour chaque contenu, et, en plus, peut avoir des conséquences en terme de sécurité (voir #4167).

Il faudrait donc à la place, utiliser la méthode `update`. Exemple :

```python
KarmaNote.objects.filter(moderator=current).update(moderator=anonymous)
```

Vous pouvez me l'assigner, je devrais avoir le temps de me pencher dessus demain. :)

**Comment by pierre-24** [comment]
Et merci :l)
