### ISSUE TITLE
Dernier appel pour la v22

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#4173]
cc/ @zestedesavoir/les-bourgeons @zestedesavoir/les-jeunes-pousses 

J'aimerais lancer la release v22 dans la semaine. Parmi les PRs ouvertes (à part ES, pièce de résistance de cette release), y a-t-il des choses qu'on pourrait encore y inclure ?

Merci pour tout votre travail !

**Comment by gllmc** [comment]
Salut :)

En ce qui me concerne, il y a #4172 qui pourrait être utile pour optimiser la désinscription, mais rien qui ne relève de l'expérience utilisateur.

#4142 est aussi mergeable si quelqu'un fait la QA, mais ça ne concerne que les admins.

En tout cas, ça fera une belle release puisqu'il y a pas mal de petits changement assez sympas qui ont été codés. Pour la ZEP-13, ça ira dans la v23 du coup ?

**Comment by DevHugo** [comment]
Ouai, pour la ZEP, j'aurais jamais le temps de tout finir pour mercredi.

**Comment by artragis** [comment]
ça serait bien que l'interface des tutos soit intégrée, elle est 
facilement désactivable. Il suffit de faire quelques tests de base et 
les retours viendront après.

**Comment by vhf** [comment]
Ok. Alors je résume mon plan:

On tente de lancer la release mercredi au plus tard. Reste à y intégrer : 

- ~~ElasticSearch~~
- Idéalement l'interface de @artragis 
- ~~Eventuellement #4172~~
- ~~Eventuellement #4142~~

Lors de la mise en beta de cette release, on active les pings et l'interface d'artragis. Puis une période de beta idéalement courte genre 1 semaine si tout va bien.

**Comment by tleb** [comment]
Je n'ai pas envoyé de patch pour le bug d'alignement vertical du bouton Suivre/Ne pas suivre, pardon. Je fais ça ce soir tard ou demain matin tôt.

**Comment by DevHugo** [comment]
Tu as jusqu'à mercredi soir, sinon ça passe dans la release d'aprés, y'a pas de souci.

**Comment by tleb** [comment]
#4082 a été résolu ?

**Comment by Anto59290** [comment]
Si #4164 peut passer ça améliorerait un peu le menu. Sinon je pense que la PR sur l'interface de merge peut être QA, à voir si on à le temps de l'intégrer.

**Comment by vhf** [comment]
Pas pu m'occuper de la release. Je m'y colle ce week-end du coup, dès mon retour. Sauf s'il manque encore des trucs qu'il faudrait faire passer avec, auquel cas on peut encore un peu repousser.

**Comment by vhf** [comment]
Ok je suis de retour. @artragis on peut partir sans toi ou t'as une forte préférence pour retarder la release encore quelques jours ?

Ping @pierre-24 si t'as un avis ou si j'ai manqué un truc. J'ai rapidement fait un topo en passant sur mes notifs, mais j'ai peut-être raté un truc pendant mon absence.

**Comment by artragis** [comment]
On peut faire sans moi. limite on fera une version 23 rapidement après la 22

**Comment by vhf** [comment]
C'est fait.

**Comment by pierre-24** [comment]
Au vu [de la page de recherche](https://beta.zestedesavoir.com/rechercher/), je pense qu'il y a eu un truc avec la génération du CSS : sur le dernier tests en date de ES, la clem' de noël était présente sur la recherche (en plus du fait qu'il n'y a pas la marge entre le paginateur et la zone bleue, alors qu'elle y était). Me trompe-je ?

**Comment by vhf** [comment]
Bien vu. Aucune idée pour le CSS. Comme d'hab j'ai pas touché le front, il est buildé par Travis.

**Comment by Situphen** [comment]
Alors je ne sais pas pourquoi ce n'était pas dans le PR sur le recherche, mais les correctifs pour le front sont dans #4196 !

**Comment by pierre-24** [comment]
Voilà qui n'est pas logique: 

![screenshot from 2017-02-11 16 31 41](https://cloud.githubusercontent.com/assets/7889675/22854945/c04c7d98-f077-11e6-9665-c3040be9f69e.png)
