### ISSUE TITLE
Utiliser permission_required pour vérifier les droits

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4181]
Actuellement, un certain nombre de nos vues utilisent une condition pour vérifier que l'utilisateur a une permission particulière et lèvent une exception `PermissionDenied` si ce n'est pas le cas. Par exemple :

```python
@login_required
def la_vue(request):
    """Docstring"""

    if not request.user.has_perm('member.change_profile'):
        raise PermissionDenied

    # Le vrai code de la vue ici
```

Il est possible de faire mieux en utilisant le décorateur `permission_required` situé dans `django.contrib.auth.decorators`. Par défaut, ce décorateur redirige vers la page de connexion. Pour lever une erreur 403 à la place (ce qui est plus logique, puisque sinon on se retrouverait sur une page disant qu'on est déjà connecté), il faut rajouter le paramètre `raise_exception=True`. Enfin, on conserve le décorateur `login_required` pour qu'un utilisateur non connecté soit quand même redirigé vers la page de connexion (cf [la doc](https://docs.djangoproject.com/fr/1.10/topics/auth/default/#the-permission-required-decorator)). Notre exemple précédent (sans oublier d'importer les décorateurs) devient donc :

```python
@login_required
@permission_required('member.change_profile', raise_exception=True)
def la_vue(request):
    """Docstring"""

    # Le vrai code de la vue ici
```

En ce qui concerne les vues génériques, voir [la doc](https://docs.djangoproject.com/fr/1.10/topics/class-based-views/intro/#decorating-class-based-views).

@zestedesavoir/les-jeunes-pousses : je pense qu'on peut taguer ça en `Facile`. :)

**Comment by pierre-24** [comment]
Ok. Moi, à priori, je n'en vois plus :)
