### ISSUE TITLE
Permettre de mettre en bêta/prod BEAUCOUP plus souvent

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#4184]
Le fonctionnement actuel en version bloque le déploiement de tout un tas de connectifs / améliorations assez triviaux, parce qu'il faut attendre pour qu'ils soient déployés  que la version soit prête et testée, et que comme dans toute version, on voudrait bien que les fonctionnalités X et Y soient embarquées, et donc correctement testées, etc.

C'est long et apporte de la latence, mais c'est encore le processus le moins pire qu'on a trouvé avec nos outils et contraintes.

L'exemple inverse, ce serait une intégration continue dans laquelle **tout** ce qui est mergé sur `prod` est automatiquement déployé en prod. Sauf que ça pose d'autres problèmes, notamment dès qu'une version nécessite des opération manuelles pour être déployée.

Or donc voici qu'au boulot on utilise GitLab (une instance locale), qui vient avec une intégration continue assez géniale. Depuis quelques mois, cette intégration continue propose une fonctionnalité tout aussi géniale : **[les déploiement intégrés à l'intégration continue](https://docs.gitlab.com/ce/ci/environments.html)**

Ce sont des tâches d'intégration continue comme les autres (donc potentiellement des scripts Shell arbitraires), qui sont taggués comme « déploie la version en cours sur l'environnement X ». Et surtout, **on peut les lancer manuellement**.

En admettant qu'on trouve un outil d'intégration continue sur Github qui propose la même fonctionnalité, on pourrait tout à fait définir ce genre de tâches (actives, disons, sur la branche `prod` et/ou sur les tags), ce qui permettrait :

1. De déployer en 1 clic une version arbitraire sur la bêta ; 
2. De déployer en 1 clic une version arbitraire sur la prod (attention à qui on donne les droits d'appuyer sur ce bouton) ;
3. De gérer les cas particuliers en faisant un déploiement manuel.

Je pense que ça peut être un gros plus pour le déploiement de ZdS est éviter cet espèce d'effet tunnel qu'on a aujourd'hui.

Si vous voulez des détails supplémentaires sur le fonctionnement du truc et la théorie, n'hésitez pas !

**Comment by SpaceFox** [comment]
PS : En admettant qu'on trouve une solution qui fasse ça et qui ait grosso merdo les mêmes fonctionnalités que Gitlab CI, on peut bien entendu :

1. Lui faire faire tous les backups imaginables avant la MEP proprement dite, et
2. Lui faire mettre la page de maintenance pendant les opérations.

Puisqu'il s'agit ~~en gros~~exactement d'exécuter un ou plusieurs scripts arbitraires sur un ou plusieurs serveurs arbitraires.

**Comment by pierre-24** [comment]
Moi, l’intégration continue, je suis moyen chaud : pour rester concret, je dirais qu'au vu du nombre de RC de nos dernières *releases*, l'intégration continue est assez suicidaire. Et du coup, on peut pas se permettre, avec notre *coverage* actuel (pourtant pas mauvais, mais par exemple on a pas de tests *fronts*), de se reposer uniquement sur les tests, ce qui signifie intensifier la phase de QA, qui est déjà pas drôle à la base. Bref, dangereux.

Après, je suis assez *fan* de la fonctionnalité de GitLab CI en elle-même :)

**Comment by vhf** [comment]
J'ai réfléchi à tout ça et je pense que si j'avais une semaine de vacances ce serait jouable.

Petite note : 

> * De déployer en 1 clic une version arbitraire sur la bêta ;

Là aussi, attention à ne pas autoriser trop de gens à appuyer sur ce bouton. Les données sur la bêta sont généralement quelques jours/semaines derrière la prod. On peut pas se permettre de déployer du code sans être certain qu'il ne donne pas accès à la DB.
