### ISSUE TITLE
Indiquer que des contenus sont des archives

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#4185]
Une idée qui me vient de [ce topic](https://zestedesavoir.com/forums/sujet/7726/archive-des-contenus-du-sdz/) : il peut être intéressant d'indiquer qu'un contenu est une archive, donc non mise à jour, donc probablement obsolète.

Si l'idée vient du topic susnommé, j'y vois une application directe en restant purement dans Zeste de Savoir : certains de nos tutos ne sont plus mis à jour et sont déjà plus ou moins obsolètes. Le signaler explicitement permettrait au lecteur de prendre plus facilement du recul sur le sujet. En prime, ça améliorerait l'image de ZdS, parce qu'on indiquerait clairement les vieux contenus au lieu d'afficher sans gêne des contenus dépassés comme le font certains sites.

Techniquement, ce serait un booléen en plus associé au contenu. S'il est présent (il peut être mis par l'auteur ou la validation via une case à cocher), **toutes** les pages de ce contenu auraient un bandeau qui indiqueraient son état.

Dans un second temps on peut imaginer une page qui liste tous les contenus âgés de plus de X années depuis leur dernière MAJ, à destination des validateurs, pour qu'ils puissent les vérifier et y apposer le flag le cas échéant.

PS : pourquoi conserver ces vieux contenus ? Au moins pour ces raisons :

1. Parce qu'ils peuvent être intéressants quand on travaille sur un vieux projet.
2. Parce qu'ils ne sont pas forcément démodés, mais sont simplement vieux. Je pense notamment à des « actualités » qui datent mais qui contiennent plein d'informations intéressantes (cf les articles sur Rosetta, par exemple).

(Source : https://zestedesavoir.com/forums/sujet/7731/indiquer-que-des-contenus-sont-des-archives/?page=1)

**Comment by Eskimon** [comment]
Idée probablement naïve : Pourquoi ne pas *simplement* mettre un bandeau type "Ce contenu n'a pas été mis à jour depuis plus de [durée à définir], il peut-être obsolète" ? Il suffirait d'un simple test dans le template du coup non ?

**Comment by gllmc** [comment]
C'est en effet possible, et plus simple, mais je préfère quand même quand c'est fait à la main. Je pense que c'est assez rapide de traiter ça pour le staff, et ça permet d'éviter de marquer ainsi des contenus sur un sujet qui ne change pas rapidement (ex : une langue), tout comme on peut dire les choses avec certitude pour un vieux tutoriel qui est obsolète (sur un framework par exemple). :)

**Comment by SpaceFox** [comment]
@GCodeur a bien résumé mon idée :)

**Comment by gllmc** [comment]
Je suis partant pour tenter de faire la PR. Du coup, je vois ça sous la forme d'une option visible par le staff et l'auteur sous `Version brouillon` qui serait `Marquer obsolète` ou `Marquer non obsolète`.

Je propose également de désactiver automatiquement le bandeau lors de la validation d'une version majeure.

**Comment by pierre-24** [comment]
L'auteur aussi ? Pas que j'aie pas envie qu'un auteur ne puisse pas marquer son tuto comme obsolète, mais j'ai pas forcément envie qu'il le marque comme "plus obsolète" alors que le staff a décidé que si. Donc deux possibilités: soit c'est le staff qui gère tout, soit l'auteur a juste le droit de marquer et pas de démarquer. Non ?

**Comment by gllmc** [comment]
J'avais pensé à ça aussi. Effectivement on peut autoriser seulement l'auteur à marquer comme obsolète (un peu comme on fait pour le masquage des messages).

**Comment by firm1** [comment]
> Effectivement on peut autoriser seulement l'auteur à marquer comme obsolète

J'aurai dit d'autoriser que le staff. Car si l'auteur disparait du site, il faut que quelqu'un puisse declarer l'obsolescence.

**Comment by SpaceFox** [comment]
Je confirme, d'autant plus que généralement un tuto est obsolète justement parce que son auteur ne vient plus.

**Comment by gllmc** [comment]
On peut fermer. :)

**Comment by pierre-24** [comment]
Juste. J'oublie toujours un truc :(

**Comment by SpaceFox** [comment]
T'inquiète, j'oubliais tout le temps aussi :D
