### ISSUE TITLE
Supprimer le MP de résolution d'alerte supprime le message de résolution.

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#4190]
J'ai ce matin signalé un message [incomplet](https://zestedesavoir.com/forums/sujet/7944/probleme-de-carte-wifi-sur-mint/?page=1#p140638) (pour dire de répondre s'il n'était pas édité). Informaticienzero l'a 15 minutes plus tard résolu, et a répondu.

L'alerte résolue était sur le message originel. J'ai supprimé le message de Clem (car ça m’embête d'avoir 36 000 messages inutile). Le message d'alerte résolu (grisé) a disparu.

Pour reproduire,

- Signaler un message ; un message rouge apparait sous le message signalé ;
- Résoudre l'alerte ; un message grisé est maintenant sous le message signalé ;
- Supprimer le MP de Clem reçu (par celui ayant signalé) ; plus aucun message n'est présent sous le message signalé.

Reproduit sur la bêta.
                    

Sujet: https://zestedesavoir.com/forums/sujet/7945/supprimer-le-mp-de-resolution-dalerte-supprime-le-message-de-resolution/
*Envoyé depuis Zeste de Savoir*

**Comment by gllmc** [comment]
Je l'avais découvert et corrigé par #4172 au passage. ;)

EDIT : pour la précision, je l'ai découvert car la désinscription supprime ces MP, et donc reproduisait le bug. Du coup, j'en avais besoin pour que ma PR fonctionne.

**Comment by pierre-24** [comment]
Ok :)
