### ISSUE TITLE
Les certificats de la prod n'ont pas été renouvelé

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#4191]
Bonjour, 

Pour une raison inconnue les certificats n'ont pas été renouvelé, alors que ça devrait être automatique, si on utilise let's encrypt.

**Comment by WinXaito** [comment]
Je confirme, impossible de rejoindre le site sur Chrome mobile ...

**Comment by WinXaito** [comment]
C'est apparement bon

**Comment by SpaceFox** [comment]
C'est peut-être la même blague que sur mon serveur perso : le certificat
est renouvelé automatiquement, mais la conf nginx n'est pas rechargée, donc
le renouvellement n'est pas actif.

**Comment by vhf** [comment]
Aucune idée du pourquoi. J'ai effectivement rechargé nginx dès que j'ai appris le problème, et ça a résolu le problème. Le certificat avait été correctement renouvelé.

**Comment by DevHugo** [comment]
On le saura pour la prochaine fois ^^. C'est le vendredi 12 mai 2017 à 01:45, ça va être un peu plus compliqué à redémarrer à cette heure là :p.

**Comment by vhf** [comment]
Notre cron est censé recharger nginx quand le certificat est renouvelé. C'est ça le plus surprenant.

**Comment by DevHugo** [comment]
Elle est paramétré comment ? au début, j'ai l’impression que c'est tous les deux mois mais y'a un ajout de quelques heures à chaque fois. Par-exemple, le dernier renouvellement, c'était le vendredi 10 février 2017 à 23:16:00 et le prochain est le  vendredi 12 mai 2017 à 01:45.

Si c'est redémarrer après le renouvellement, c'est vraiment bizarre.

**Comment by vhf** [comment]
`27 */12 * * * certbot renew --quiet --disable-hook-validation --post-hook "service nginx reload"`

**Comment by DevHugo** [comment]
Le plus drôle, c'est que ça marche sur la béta !
