### ISSUE TITLE
Notification persistante quand on est pingé sur un sujet dont on n'a pas les droits

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#4195]
Bonjour,

Procédure pour reproduire: 

- Créé un sujet avec un utilisateur ayant les droits sur le forum "corbeille", dans le message faire un ping sur un utilisateur n'ayant pas les droits sur le forum corbeille
- Mettre le sujet dans la corbeille sans lire la notification associé
- Noter que l'utilisateur ayant fait l'objet du ping à maintenant une notification persistante.

**Comment by vhf** [comment]
Pour clarifier le bug, il y a deux scénarios : 

1. Déplacement vers un forum auquel le pingé n'a pas accès
    1. Pinger X dans un forum 'public'
    1. Déplacer le sujet dans un forum non-public
1. Créer un ping dans un forum auquel le pingé n'a pas accès
    1. Pinger X dans un forum non-public

**Comment by artragis** [comment]
quel est le type de la notif générée par le ping svp?

**Comment by vhf** [comment]
`PingSubscription` @artragis

**Comment by artragis** [comment]
thx. Pour ce qui est du changement de forum, je vais régler le pb assez 
facilement. Pour la partie "pinger dans un forum non visible" je sais 
pas encore comment faire par contre. Je regarde.

**Comment by vhf** [comment]
Depuis que je suis plus dans le CA j'ai une notification persistante lors de chaque nouveau topic dans le forum CA.

**Comment by artragis** [comment]
ok, il faut donc aussi mettre un listener sur le changement de permission. ça va être beau.

**Comment by gllmc** [comment]
Lors du changement de groupe en fait. Je pense que tu peux ouvrir un nouveau ticket pour ça @vhf, car c'est un problème différent.
