### ISSUE TITLE
Empêcher l'autoping

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#4198]
Il est possible de s'auto-pinger. C'est assez inutile.

**Comment by WinXaito** [comment]
Oui mais pas autrement problématique, si ? ça peut permettre de mettre en évidence une liste d'utilisateur et de s'y mettre dedans.

**Comment by vhf** [comment]
Je comprends toujours pas l'intérêt. Si je mets @vhf, j'ai pas besoin de recevoir de notification, je sais ce que j'écris, non ?

**Comment by pierre-24** [comment]
Non, tant qu'on reçoit pas de notification. Pour autant, et comme ton
commentaire le prouve sur GH, le nom est quand même formaté :)

**Comment by vhf** [comment]
Oui oui il faut formater le nom. Par contre il ne faut pas pinger. Je ne parle que du ping. Se pinger soi même est inutile.

**Comment by WinXaito** [comment]
Ah je suis d'accord que l'on ne doit pas recevoir de notification (bien qu'elle soit lu directement) mais je suis pour qu'on garde le formatage du nom

**Comment by pierre-24** [comment]
Tout le monde est d'accord, donc ;)
