### ISSUE TITLE
Ne pas pinger dans les citations

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#4199]
Je pense qu'il serait préférable que les pings dans les citations ne soient pas pris en compte. Ça deviendra vite pénible sinon, à mon avis. Ping @FanJiyong un avis ?

Je suppose qu'il faut faire ça dans ZMarkdown. Ping @cgabard, un avis ?

**Comment by cgabard** [comment]
Oui il faut faire ça dans le markdown. Tu peux me faire une issue dans le
dépôt ?

**Comment by motet-a** [comment]
J’enlève le feedback, je pense que c’est tout décidé vu que la PR a été merge.
