### ISSUE TITLE
Documenter le ping dans la doc markdown 

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#4200]
Bonjour,

Penser à mettre le [tutoriel markdown](https://zestedesavoir.com/tutoriels/249/rediger-sur-zds/) à jours.

**Comment by AmauryCarrade** [comment]
Et ajouter une astuce les concernant dans #4078, éventuellement.

**Comment by artragis** [comment]
pas du ressort du bug tracker.
