### ISSUE TITLE
[v22] Un contenu sans date de publication donne un résultat blanc

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4201]
En faisant une [recherche sur le mot python](https://beta.zestedesavoir.com/rechercher/?q=python), il y a un résultat blanc, provenant de [ce tutoriel](https://zestedesavoir.com/tutoriels/334/panda3d-et-heightmap/), qui d'après @pierre-24 ne possède pas de date de publication.

À voir où est le vrai problème (et pourquoi ce tuto n'a pas de date de publication). :)

**Comment by pierre-24** [comment]
Deux choses ici, donc : 

+ D'une part, @vhf n'as peut être simplement pas relancé d'indexation (et je peux le comprendre), sauf que normalement, j'avais *commité* un fix, dont on ne sais pas si il a fait effet ou pas.
+ Quand au pourquoi de l'absence de date de publication, mystère et boule de gomme, mais [j'ai de bonne raisons de croire que ça ne se reproduira pas](https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-276800171). Je propose en fait de *fixer* ça à la main dans la BDD en prenant la valeur de la date de dernière modification.

Pas que j'aie pas envie de chercher, mais je suis presque certain qu'on a rien à craindre.

**Comment by vhf** [comment]
J'ai sync la bdd produit vers beta lors de la MEB et tout indexé.

**Comment by pierre-24** [comment]
Ah, f\*\*. Bon, je regarde ça quand j'ai deux minutes ;)

**Comment by vhf** [comment]
Dis-moi si je peux te fournir des infos @pierre-24

**Comment by vhf** [comment]
Bon j'ai décidé de régler le problème dans les données. J'ai pris la date de publication du publishable et l'ai mise sur le published, en prod et en beta. En beta, j'ai aussi flaggé "à réindexer".

Si c'est réglé dans ~30min quand le timer sera passé, je ferme l'issue et on perd pas de temps à tenter de régler ça.

**Comment by vhf** [comment]
Réglé par le timer.

**Comment by pierre-24** [comment]
Ok, cool, un grand merci :)
