### ISSUE TITLE
Bouton « comparer à la bêta » et « comparer à la version en ligne »

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#4205]
Je trouve que ce serait utile pour les auteurs d’avoir un bouton pour comparer la version actuelle d’un tutoriel à la version publiée, en bêta ou encore à la version brouillon. La page d’historique permet ça, mais quand les versions à comparer ne sont sur la même page, c’est plus embêtant (ça se fait en copiant à la main le numéro d’une des versions pour la comparer à l’autre). Je propose donc l’ajout d’un bouton pour comparer aux versions citées plus haut. Je vois ce bouton soit dans la page d’historique, soit dans le menu de gauche de la page du tutoriel. 
                    

Sujet: https://zestedesavoir.com/forums/sujet/7962/bouton-comparer-a-la-beta-et-comparer-a-la-version-en-ligne/
*Envoyé depuis Zeste de Savoir*

**Comment by gllmc** [comment]
Vous pouvez me l'assigner, je pense avoir le temps de m'en occuper ce soir. :)

**Comment by pierre-24** [comment]
Quelle efficacité :o
