### ISSUE TITLE
Mettre en place un bug tracker pour la bêta publique

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#421]
La gestion actuelle avec le forum est compliquée... il faudrait qu'on mette en place un bug tracker pour la bêta publique. Mais quoi ?
- On ouvre celui de Github ?
- On réutilise le redmine ?
- On demande un Jira (gratuit pour les projets open-source mais 2 semaines de délais) ?

C'est un choix au long cours qu'il faut réfléchir posément dès aujourd'hui.

**Comment by coma94** [comment]
Pour les devs le plus pratique n'était pas celui de github?
Si on a naturellement abandonné le redmine c'est bien pour ça non?

**Comment by SpaceFox** [comment]
Le plus pratique _aujourd'hui_ est clairement celui de Github. Mais je ne sais pas à quel point on peut l'ouvrir au public.

**Comment by Taluu** [comment]
Je pense qu'on peut l'ouvrir complètement, et laisser les gens faire leur reports ici. Après, c'est aux devs de filtrer... Et au pire utiliser les forums comme **support** pour les moins aguerris ? En tout cas, ce sera jamais que moins contre-intuitif de passer par "d'autres canaux" type twitter, etc, ou même redmine qui est quand même encore plus dev-centered que github...

**Comment by SpaceFox** [comment]
J'ai posté un retour d'expérience ici : http://zestedesavoir.com/forums/sujet/87/suggestion-bug-tracker?page=2#p1106

En gros, il nous faut un BT et pas un forum.

**Comment by Alex-D** [comment]
Github n'est pas un BT, mais si on filtre ça peut le faire.

Si on se tape une ruée de rapports de bugs comme sur la beta mais sur le Github on va mourir... ça reste assez orienté développeur, et le but selon moi est d'avoir des tickets précis une fois le bug compris et testé/confirmé.

**Comment by Alex-D** [comment]
Grafikart vient de me proposer ceci : https://trello.com/

En sachant que tout le monde n'a pas l'air d'accord sur la toile : http://garythegary.com/2011/11/10/why-trello-doesnt-work-for-bug-tracking/

**Comment by SpaceFox** [comment]
> En sachant que tout le monde n'a pas l'air d'accord sur la toile

Alors, restons sur l'un des 150 outils sur lesquels tout le monde s'accorde
à dire qu'ils sont nickels pour faire du BT ?

2014-05-12 2:16 GMT+02:00 DEMODE Alexandre notifications@github.com:

**Comment by cgabard** [comment]
Pour avoir utilisé trello au boulot, ce n'est pas du tout fait pour du BT et ce n'est pas l'objectif du produit.

**Comment by Alex-D** [comment]
Ok d'ac, je proposait ce qu'on m'a proposé, je ne connais pas Trello personnellement.

Du coup, est-ce que vous pourriez lister les BT que vous connaissez ?
- **Redmine** : moche, contre-intuitif pour un user lambda
- **Mantis** : ça l'air moche mais pas trop le bazar, je ne connais pas bien
- j'ai pu lire **Jira**, mais je ne connais pas, si quelqu'un a un/des avis

**Comment by cgabard** [comment]
Jira, qu'on a aussi utilisé au boulot, est tres puissant mais peu de personnes ont accrochés dans ma boite. Je pensais que c'etais pour le coté usine a gaz mais au final non puisque maintenant on est sous youtrack qui est pire.

Perso, j'ai peu d'avis sur la question. GitHub manque de fonctionnalités ce qui est genant. Tous les autres vrais BT en ont plus qu'on en aurat jamais besoin je pense, donc le choix m'importe peu perso.

Par contre si on peut trouver un truc qui permet de lier les comptes à ceux du site, ce serait le mieux.

**Comment by Alex-D** [comment]
Pour en revenir à Redmine, normalement ça peut se brancher sur un dépôt Git.

Aussi, j'ai souvenir que le SdZ avait fait un pont entre Redmine et le SdZ (ou je me trompe, ce qui est probable).

**Comment by firm1** [comment]
La question qu'il faudrait se poser c'est : "Est-ce qu'on cherche un Bugtracker pour le court terme ? Le moyen terme ou le long terme ?"

Pour le court terme : Mon avis reste le forum (en espérant que certains feront le transfert github)
Pour le moyen terme : Mon avis est une feature de ZdS qui permet (en cliquant sur un lien du forum) de créer un issue sur github automatiquement.
Pour le long terme : un outil simple (à la UserVoice) entre ZdS et github.

Mais encore une fois, je ne suis pas intransigeant, je me plierai à la volonté de la majorité dans la limite du raisonnable.

**Comment by Eskimon** [comment]
S'il le faut je peux me charger à court-terme de faire le transfert forum<->GH (en ajoutant ici et reportant sur le forum le # de l'issue).
C'est pas forcément le plus drôle et n'est pas viable à long terme, mais comme le projet m'intéresse, que je veux me rendre utile et que je ne pourrais pas forcément l'être au niveau du code ca sera déjà ca :D

Apres on en avait parlé mais il existe aussi l'API GH qui permet pas mal de chose...
Notamment ajouté des issues... Si on crée un compte GH lambda (clémentine ?) et qu'on fait un zoli formulaire sur ZdS, n'importe qui pourrait ajouter des issues. On pourrait faire en sorte que ces dernières est automatiquement le label "from ZdS" pour faire le tri rapidement...
[Ici la doc en parle](https://developer.github.com/v3/issues/#create-an-issue)

**Comment by AlexRNL** [comment]
Dans ma boite on utilise Bugzilla et Jira. Bugzilla est bien, mais son interface est assez rebutante, surtout pour les non développeurs.

Jira, j'aime assez, en particulier le moteur de recherche qui est très puissant (c'est du SQL like : JQL). L'interface est beaucoup plus ergonomique que celle de Bugzilla et devrait moins faire peur aux non-initiés.

À noter, il y a des versions de démonstration pour tester Bugzilla 4.4 [ici](https://landfill.bugzilla.org/bugzilla-4.4-branch/) et Jira 6.3 [là](https://jira.atlassian.com/browse/DEMO).

Le problème d'ouvrir le GitHub au public c'est qu'il risque d'y avoir énormément de "bruit" et que ça va polluer les bug de développeurs.

**Comment by cgabard** [comment]
Si on envisage jira il faudrait fortement envisager de passer a bitbucket
plutôt que github du coup car les deux viennent de la même boite et
s'interfacent bien (même si il me semble que jira peu être connecté a
github aussi)

**Comment by Alex-D** [comment]
Jira = Java = j'ai un peu de mal. Mais je le préfère à Bugzilla (j'ai testé vite fait il y a quelques jours avec un mec de ma boite).

Passer à bitbucket : non, certainement pas.

Pourquoi ? Parce qu'un mec comme moi, qui n'a pas encore de boulot, a besoin de Github comme complément de CV, si j'ai des projets tantôt sur Github, tantôt sur bitbucket, ça va être le bordel. 

Aussi, l'interface est moins pratique sur bitbucket de ce que j'avais pu tester il y a un petit moment.

**Comment by cgabard** [comment]
Sérieux que ce soit du java je m'en contrefou tant que ça marche. Et ton CV aussi je m'en tape sérieusement, tu as ton portfolio + ton CV pour indiquer les bon liens. Ce ne sont pas des arguments valable.

Je ne dis pas que je veux passer a bitbucket, je dis juste que ça s'interface bien avec jira. Et ton CV n'est pas un argument valide pour le rejeter

**Comment by SpaceFox** [comment]
> Jira = Java = j'ai un peu de mal.

Argument irrecevable. Tant qu'on a les compétences pour héberger un produit
ou l'utiliser, si c'est le meilleur, on le prends. On ne va pas se fermer
des portes parce qu'on "aime pas" un langage (ce qui est ridicule en soi
d'ailleurs).

> Pourquoi ? Parce qu'un mec comme moi, qui n'a pas encore de boulot, a
> besoin de Github comme complément de CV, si j'ai des projets tantôt sur
> Github, tantôt sur bitbucket, ça va être le bordel.

Je ne sais même pas quoi répondre à ça en fait...
Si on était partis sur Bitbucket dès le départ, tu aurais refusé de
travailler avec nous ?

**Comment by Alex-D** [comment]
Je parlais de Java en sécurité, en lourdeur, en ressources. Pas en tant que langage.

Pour bitbucket, non, mais maintenant qu'on est sur Github, ça me ferais suer de changer. Et aussi, à ce moment là j'avais plutôt insisté sur Github.

**Comment by Eskimon** [comment]
L'avantage de GitHub c'est aussi que c'est assez répandu et donc tu touches un plus grand public... Les gens connaissent l'outil, on un compte dessus, peuvent s'y repérer etc...

**Comment by SpaceFox** [comment]
> Je parlais de Java en sécurité, en lourdeur, en ressources.

LOL, tu parles de ta méconnaissance de Java quoi.

Par exemple, je suis effaré de la consommation de notre application ZdS par
rapport à ce que consomment mes projets pro en Java, côté CPU.
Sérieusement, si Django n'était pas aussi facile à programmer, je bennerais
ça vite fait niveau perfs.
Alors oui ça implique de consommer plus de RAM, mais ça OSEF : on en a des
masses maintenant. Que ton application te bouffe 50 ou 500 Mo de RAM c'est
pareil, de toutes façons t'as 3 Go.

Niveau sécurité, 95% des failles qui ont fait parler de Java étaient dans
le plugin navigateur - donc quelque chose qui ne nous concerne pas.
Des failles de sécurité, j'en vois passer plein au boulot. On s'est encore
pris deux attaques aujourd'hui. Personne ne cible Java - serveur. Personne.
Les failles applicatives, oui, par contre.

**Comment by Alex-D** [comment]
Github >>> ALL. Plus d'inscrits, plus d'outils, plus connu, plus d'habitué, plus de tout ce que vous voulez.

Bref, faites ce que je vous voulez, je me retire de ce débat et même des autres en fait. Mes arguments n'étant point recevables, inutile de les avancer.

**Comment by AlexRNL** [comment]
Jira se connecte visiblement aussi bien à GitHub que BitBucket via un [plugin gratuit](https://marketplace.atlassian.com/plugins/com.atlassian.jira.plugins.jira-bitbucket-connector-plugin).

**Comment by Coy0te** [comment]
> Bref, faites ce que je vous voulez, je me retire de ce débat et même des autres en fait.

Pour détendre un peu l'atmosphère (certains semblent tendus comme les strings de Magloire depuis quelques jours !), ta réplique m'a complètement fait repenser à ça : 
=> https://www.youtube.com/watch?v=riW0npHjQIw :D

**Comment by GerardPaligot** [comment]
Personnellement, j'ai une préférence pour GitHub. C'est une plate-forme que
j'apprécie et que j'ai l'habitude d'utiliser. Après, c'est vrai qu'il y a
sûrement une meilleure intégration entre Jira et BitBucket.

Par contre, est-ce que quelqu'un les connait (cette intégration) ? Si c'est
changé de plate-forme juste parce que c'est mieux intégré (sans plus de
détail), je ne pense pas que ça en vaut la peine. J'opterais donc pour
GitHub + Jira + plugin linké par Serpent Tout Nu.

**Comment by poulp** [comment]
Il y a aussi https://waffle.io/zestedesavoir/zds-site qui se branche avec github pour offrir une interface alternative

**Comment by firm1** [comment]
> Il y a aussi https://waffle.io/zestedesavoir/zds-site qui se branche avec github pour offrir une interface alternative

Je suis assez fan. Je pense même que je vais allez là bas pour organiser mes issues, c'est plus lisible.

**Comment by Taluu** [comment]
+1 pour waffle.io, c'est un service sympa

**Comment by Alex-D** [comment]
Je pense qu'on a notre solution :)

**Comment by Eskimon** [comment]
Je propose https://huboard.com/ qui a un peu de la gueule... (faudra la encore tweaké les labels)

**Comment by firm1** [comment]
Le titre de cette issue ne la rend pas bloquante beta publique ?

**Comment by SpaceFox** [comment]
Vu comme c'est parti, je passe ça en "v1.x".

**Comment by poulp** [comment]
ce ticket doit-il rester ouvert vu qu'il concerne la bêta ?

**Comment by Eskimon** [comment]
ahah "le ticket du grenier" :D tu as pas remué trop de poussiere en le ranimant ?
