### ISSUE TITLE
[beta][v23] Erreur 500 via opensearch

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4215]
Bonjour,

**Lien incriminé** : https://beta.zestedesavoir.com/rechercher/opensearch.xml

**Problème** : j'ai une erreur 500 en allant sur cette url.

**Comment by pierre-24** [comment]
Bien vu :) Voir [erreur sentry associée](https://sentry.sandhose.fr/zeste-de-savoir/beta-backend/issues/899/).

En gros, j'ai fait le con et j'ai oublié de migrer la template :)
