### ISSUE TITLE
[beta][v23] Le bouton marquer tous les messages comme lus ne semble pas faire le job

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4217]
Bonjour,

Prerequis : Il faut avoir des notifications venants du forums non lues

Scénario : 
- aller dans tous les notifications
- cliquez sur le bouton "marquer tout comme lus" de la sidebar
- vous avez bien un message de confirmation et le compteur est revenu à la normale dans la zone de notification
- revenez ensuite dans le forum
- constatez que dans la sidebar, dans les sujets suivis, vous avez encore du gras sur des items comme si le "marquage en lu" n'a pas eu d'effet dans cette zone

**Comment by gllmc** [comment]
En fait, ce comportement est normal car la fonction fait exactement ce qu'elle dit, c'est-à-dire qu'elle marque les notifications comme lues mais sans marquer le sujet comme lu.
À vrai dire, ça ne me choque pas particulièrement car il s'agit à mon sens de deux choses différentes. Si je marque tout comme lu (par exemple car je me suis absenté longtemps et que j'ai donc trop de notifications), je trouve logique d'être quand même redirigé vers le dernier message réellement lu si je clique sur un lien dans les forums (alors que si on marque aussi le sujet comme entièrement lu, ce ne sera pas le cas).

**Comment by firm1** [comment]
intuitivement je ne m'y attendais pas, et j'ai beau comprendre ta logique, ça reste déroutant pour moi.

**Comment by pierre-24** [comment]
Donc @FanJiyong doit trancher :)

**Comment by gllmc** [comment]
Comme dit sur [ZdS](https://zestedesavoir.com/forums/sujet/8104/notications-toutes-lues/#p142899), je prends. Je ferai ça dans le courant de la semaine et vous pouvez donc me l'assigner. :)

Au passage, on peut enlever les cartouches `v23` (v22 plutôt, non ?) et `beta` puisque ça passera visiblement dans la prochaine version.

**Comment by gustavi** [comment]
Corrigé, merci @GCodeur !
