### ISSUE TITLE
Upgrader OpenSSL pour prendre en charge ALPN (pour HTTP/2)

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#4220]
Sur la prod, on a une vieille version d'OpenSSL, qui prend en charge NPN, et pas ALPN. Le support d'NPN pour l'HTTP/2 a été drop dans chrome y'a un moment, et plus récemment dans firefox. On a donc pas d'HTTP/2 dans ces navigateurs.

ALPN est pris en charge avec `openssl>=1.0.2`. `openssl-1.0.2k` est dispo dans `jessie-backports` sur debian.

cf. <https://zestedesavoir.com/forums/sujet/8009/activer-http2-pour-zeste-de-savoir/>

**Comment by vhf** [comment]
Tu me fais une note dans `update.md` sur la branche de release stp ?

**Comment by vhf** [comment]
#4222
