### ISSUE TITLE
MAJ de la liste de fournisseurs de mails bloqués

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#4226]
Aimail a la bonne idée d'utiliser masse de noms de domaines…

Par exemple : http://fr.getairmail.com/zssutslk/qffE :

- `@abyssmail.com`
- `@boximail.com` (déjà utilisée sur ZdS par des comptes louches)
- `@eelmail.com`
- `@vomoto.com`
- `@pwrby.com`
- … et je suppose quelques zillions d'autres.

À voir ce qu'on peut faire dans ce cas.

**Comment by gllmc** [comment]
Je viens de tester en générant des adresses jusqu'à être bloqué. Il y avait en effet pas mal de NDD différents, mais certains se recoupaient avec les tiens ou apparaissent plusieurs fois, donc pas sûr qu'il y en ait tant que ça.

Même si on en ratera sans doute quelques uns, je propose déjà de faire une PR avec les domaines que tu as repéré plus d'autres que l'on pourrait trouver en testant (on peut créer une dizaine d'adresses toutes les heures il me semble).

J'ajoute déjà à la liste :

- `@imgof.com`
- `@6paq.com`
- `@anappfor.com`
- `@clrmail.com`

(Pour info, en faisant ces tests, il y avait une bonne moitié des domaines que tu avais déjà cité ou que j'avais déjà relevé.)

**Comment by tleb** [comment]
Deux autres que j'ai pu relevé avant d'atteindre la limite :

* `@zetmail.com` ;
* `@tafmail.com`.

**Comment by gllmc** [comment]
Je viens de faire trois nouvelles séries et je n'en ai trouvé qu'un nouveau qui est tout bêtement `@getairmail.com`. À moins que vous n'en trouviez de nouveaux, je pense qu'on peut faire la PR, non ?

Je récapitule :

- `@abyssmail.com`
- `@boximail.com`
- `@eelmail.com`
- `@vomoto.com`
- `@pwrby.com`
- `@imgof.com`
- `@6paq.com`
- `@anappfor.com`
- `@clrmail.com`
- `@zetmail.com`
- `@tafmail.com`
- `@getairmail.com`

Je peux m'en occuper.

**Comment by A-312** [comment]
Pourquoi vous ne bloquez pas aussi l'ip smtp du serveur, plutôt que le nom de domaine ?

En php j'utilisais la fonction [gethostbyaddr](http://php.net/manual/fr/function.gethostbyaddr.php) sur le nom de domaine pour récupérer le smtp.

Ensuite rien empêche de mettre un système de cache sur le NDD.

**Comment by vhf** [comment]
@A-312 dans quel but ?

**Comment by A-312** [comment]
J'ai copié la mauvaise ligne, je voulais dire cette fonction : [gethostbyname](http://php.net/manual/fr/function.gethostbyname.php).

getairmail.com à une liste très grande de nom de domaine, vous ne pouvez pas tous les logger, chaque semaine il y en a des nouveaux.

Alors que si vous faite ceci : 

```php
<?php

echo gethostbyname("getairmail.com")."<br>";


echo gethostbyname("abyssmail.com")."<br>";
echo gethostbyname("boximail.com")."<br>";
echo gethostbyname("eelmail.com")."<br>";
echo gethostbyname("vomoto.com")."<br>";
echo gethostbyname("pwrby.com")."<br>";
echo gethostbyname("imgof.com")."<br>";
echo gethostbyname("6paq.com")."<br>";
echo gethostbyname("anappfor.com")."<br>";
echo gethostbyname("clrmail.com")."<br>";
echo gethostbyname("zetmail.com")."<br>";
echo gethostbyname("tafmail.com")."<br>";
echo gethostbyname("getairmail.com")."<br>";

echo gethostbyname("yopmail.com")."<br>";
```

Vous allez obtenir l’ip du serveur mail : 

```
198.27.67.138
198.27.67.138
198.27.67.138
198.27.67.138
198.27.67.138
198.27.67.138
198.27.67.138
198.27.67.138
198.27.67.138
198.27.67.138
198.27.67.138
198.27.67.138
198.27.67.138
87.98.250.141
```

Il suffira donc juste d'une ligne pour blacklist les serveurs d'emails jetables (qui ont souvent une seul ip).

NB : Apparemment en python la fonction à le même nom "socket.gethostbyname".

**Comment by vhf** [comment]
Non, c'est pas comme ça que ça fonctionne, pour plusieurs raisons.

L'IP de l'hostname n'est pas souvent celle du serveur mail d'envoi ou de réception. Il n'y a pas de moyen simple d'obtenir les IPs des serveurs mail d'envoi ou de réception. Même si on avait ces IPs, il faudrait que la personne qui veut s'inscrire sur ZdS envoie un email à ZdS pour qu'on puisse vérifier si son fournisseur d'email est blacklisté ou pas.

[edit] Ok, quelqu'un qui pense avoir compris ton idée me l'a expliquée, je comprends mieux ce que tu veux faire.

**Comment by gllmc** [comment]
On peut fermer. :)
