### ISSUE TITLE
Mettre en place des tests unitaires pour les bugs déjà corrigés

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#423]
Lors de la bêta privée, on a corrigé une certaine masse de bugs, sans jamais écrire le moindre test unitaire à ce sujet.

Un certain nombre de ces bugs mériteraient d'avoir leur propre test pour éviter de les voir ressurgir, comme par exemple le #422.

**Comment by Taluu** [comment]
Et avoir comme commentaire du bug "fix #xxx", pour qu'on puisse s'y retrouver...

**Comment by artragis** [comment]
La partie "tutoriel" a été totalement unit testée par @firm1  @Eskimon  et moi.

**Comment by SpaceFox** [comment]
Je crois qu'il va falloir faire le point sur ce qu'on a et ce qui manque comme tests.

**Comment by gustavi** [comment]
J'ai un test qui permet de vérifier si les vues retournent bien render_template() (et qu'on a bien la version du commit en bas de page) : http://paste.awesom.eu/L2BZ. Je sais pas si ça vaut le coup.

**Comment by firm1** [comment]
Je ne sais pas, il faudrait le rajouter dans tous les tests de type get pour toutes les pages.

Je ne pense pas que ça vaille le coup.

**Comment by gustavi** [comment]
Dans une seule (celle d'accueil par exemple) ça permet de voir qu'on a pas cassé le render_template et que gitpython fonctionne bien.

**Comment by firm1** [comment]
ouais pourquoi pas.

**Comment by gustavi** [comment]
Je sais pas si cette issue est encore d'actualité. On est plus sur de la recommandation qu'un vrai problème. En général c'est plutôt bien fait (merci @Eskimon ).

**Comment by artragis** [comment]
Encore une victoire d'@Eskimon et des zest'meeting. Effectivement on peu
clore, je pense.

Le 8 novembre 2014 21:49, Laville Augustin notifications@github.com a
écrit :

**Comment by firm1** [comment]
plus de 80% de couverture, tout va bien. Je ferme

**Comment by Eskimon** [comment]
Si un jour j'ai du temps et pas de bugfix à faire je continuerais... mais d'ici là on a le temps :D
