### ISSUE TITLE
Recherche n'affiche pas toujours les tutoriels en premier

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#4231]
Hello les amis,

Comme tout le monde, je suis ravi de voir la recherche revenir sur la page d'accueil, encore plus au vu de la pertinence de ses résultats. Malheureusement, sur certaines recherches (et peut-être sur certaines reindexation), les premiers résultats affichés ne sont pas des tutoriels mais des messages de forum. Chose étrange puisque les priorités me semblaient être : Tutoriel > Article > Forum.

Hors, quand j'ai tapé "android" dans la recherche, j'obtiens que des messages de forum dans les premiers résultats : 

![capture d ecran 2017-02-28 a 22 51 40](https://cloud.githubusercontent.com/assets/1913901/23435896/eddc79b8-fe08-11e6-8665-005f795d5ddd.png)

**Comment by DevHugo** [comment]
Bizarre c'est pas du tout les mêmes résultat sur la béta : https://beta.zestedesavoir.com/rechercher/?q=android.

![](https://screenshotmachine.com/serve.php?img=beta-zestedesavoir-com-1024x768desktop-6156df.png)

**Comment by gllmc** [comment]
Même comportement en cherchant `Django` [ici](https://zestedesavoir.com/rechercher/?q=Django) et [là](https://beta.zestedesavoir.com/rechercher/?q=Django). Est-ce que #4224 aurait pu avoir un impact ?

**Comment by pierre-24** [comment]
> Est-ce que #4224 aurait pu avoir un impact ?

Possible. M'enfin j'ai décidément l'impression, comme je le disais sur l'article de la v22, que le *boost* pour les tags est trop puissant ([2 vs 1.5 pour le titre](https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/models.py#L395-L396)). Et quand bien même [c'est la même chose côté tutos](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/models/models_database.py#L878-L879), on dirait que c'est quand même les sujets qui gagnent.

**Comment by rezemika** [comment]
Je confirme également. J'ai effectué plusieurs recherches pour voir le comportement.

Forum en 1er : 

- django
- rest
- framework (un seul sujet, puis le tuto principal)
- contribuer (idéalement, devrait faire remonter le guide du contributeur)
- zeste de savoir (contrairement à zds, ironiquement)
- informatique
- programmation
- linux
- maths (contrairement à mathématiques)

Contenus en 1er : 

- java
- python
- astronomie
- interview
- chimie
- zds
- arduino (mais le tuto d'Eskimon n'est qu'en page 2)
- secourisme
- histoire
- économie
- pédagogie
- neurologie
- windows
- mac
- mathématiques

Aussi, quand je tapes "symfony", seul un article remonte, puis le forum. En revanche, quand je choisis aussi "Contenus publiés", pleins d'autres contenus apparaissent (notamment "Créez une API REST avec Symfony 3").

Je ne connais pas assez django pour connaître la complexité de cette manoeuvre, mais il serait peut-être utile de rajouter une variable booléenne pour les tutos qui les identifieraient comme étant adaptés aux débutants dans un domaine (ou le faisant découvrir), les faisant remonter en premier dans les recherches. Notamment pour les tutos sur "Créer un site web avec le framework Django" ou "Apprendre à programmer avec Python 3".

**Comment by pierre-24** [comment]
J'ai tenté un truc ;)

**Comment by GerardPaligot** [comment]
@pierre-24 Je ne sais pas si c'est prévu/possible facilement, mais est-il possible de baisser la pertinence d'un contenu s'il est marqué comme étant obsolète par le staff ?

**Comment by gllmc** [comment]
Très bonne suggestion à mon avis. Ça m'était venu en tête quand j'ai fait ma PR, puis j'ai oublié.

Pour info, c'est un simple booléen `is_obsolete` sur `PublishableContent`, donc je pense que ça doit être facile à faire. :)

**Comment by pierre-24** [comment]
Comme GCodeur a dit :)

**Comment by artragis** [comment]
Pour la partie is_obsolete, je vais ouvrir un autre ticket afin de garder le tracking clair

**Comment by pierre-24** [comment]
Y'en a pas déjà un avec cette idée ?

**Comment by artragis** [comment]
Pas que je sache mais maintenant on a #4263

**Comment by pierre-24** [comment]
En attendant, @GerardPaligot et @rezemika, vous pouvez tester [sur la bêta](https://beta.zestedesavoir.com/rechercher/?q=arduino) que le nouvel "ordre" est déjà plus en phase avec vos désir :)

**Comment by GerardPaligot** [comment]
Malheureusement pas totalement. Tu as bien des publications en premier mais ils sont pas tous au dessus :

<img width="1171" alt="capture d ecran 2017-04-03 a 10 45 32" src="https://cloud.githubusercontent.com/assets/1913901/24601858/cac28370-185a-11e7-826b-11e014f2e008.png">

<img width="1159" alt="capture d ecran 2017-04-03 a 10 45 42" src="https://cloud.githubusercontent.com/assets/1913901/24601867/cdedb614-185a-11e7-9759-86a9dbebe1af.png">

Je me permets de ré-ouvrir.

**Comment by gllmc** [comment]
Même problème en cherchant Django. Le tuto principal apparaît bien sur la première page, mais celui de gustavi est [sur la deuxième](https://beta.zestedesavoir.com/rechercher/?q=Django&page=2). :/

**Comment by pierre-24** [comment]
Je vois. En gros, le big-tuto est bien remonté comme je l'avais prévu, mais les topics sont toujours trop haut. Bon, pour ajuster ça, faut que j'attrape quelqu'un avec un accès à la bêta (au hasard @vhf) sur IRC et qu'on modifie ensemble deux ou trois truc pour voir ce que ça fait :)

**Comment by philippemilink** [comment]
Maintenant qu'on a migré d'ElasticSearch vers Typesense (#6475, vous pouvez tester sur beta.zestedesavoir.com), j'ai l'impression que les problèmes signalés dans ce ticket sont corrigés. Je clos, mais libre à vous d'ouvrir un nouveau ticket si vous constatez encore des choses bizarres :)
