### ISSUE TITLE
Utiliser localStorage pour retenir la frappe

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#4237]
Je crée un sujet technique pour implémenter une foncitonnalité souvent discutée et qui est remontée aujourd'hui sur le forum : https://zestedesavoir.com/forums/sujet/8117/champ-de-reponse-et-sujets-a-plusieurs-pages/

Ce que je propose, c'est qu'on fasse une sorte de plugin JQuery comme on l'a fait pour le karma qui permette d'utiliser le localStorage.

Voici le fonctionnement que je propose : 

- lorsqu'on détecte un éditeur de texte sur le site
- si ledit éditeur possède un texte à l'intérieur (parce qu'on est dans une fenêtre d'édition) alors on n'en fait pas plus
- sinon, regarder l'attribut "data-storage-id" (voir plus loin), s'il est existant alors regarder si on a un texte dans le localStorage qui soit associé au data-storage-id. Si c'est le cas, le mettre dans le sujet.
- lorsqu'on tape sur la zone de texte, alors retenir le texte
- lorsqu'on soumet (attention, ne pas confondre avec aperçu), retirer toute trace de la donnée associée au data-storage-id

**Comment by artragis** [comment]
@vhf, peux-tu m'assigner cette tâche si tu es d'accord avec elle?

**Comment by WinXaito** [comment]
Il me semble que Firefox le fait plus ou moins de base, ça ne risque pas de créer des soucis ?

**Comment by artragis** [comment]
S'il ne le fait que "plus ou moins", non, ça ne posera pas de soucis, je 
pense.

**Comment by motet-a** [comment]
Je pense qu’il faudrait juste prendre soin de limiter le nombre de textes mémorisés. Une simple liste triée par date de création devrait faire l’affaire.

Je ne sais pas si il y a vraiment besoin d’un attribut `data-storage-id`. On devrait pouvoir se débrouiller avec l’URL, non ?

**Comment by artragis** [comment]
pas con du tout le coup de l'url :)

**Comment by arobase-che** [comment]
Salut,

Où en est cette issue ? Quelqu'un se souvient où on doit tout recoder ?

**Comment by artragis** [comment]
la PR est prête à être qualifiée merci @motet-a pour le travail.
