### ISSUE TITLE
La publication d'une nouvel version d'un contenu suivi fait qu'on ne le suit plus

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#4238]
Bonjour,

Mon article sur les dinos a été publié. Je le suis (par défaut). J'ai fait une modification. Elle a été validée par un autre validateur. Je **ne** suis **plus** mon article. Reproduit sur la bêta (par auto-validation).

Pour reproduire :

- Faire valider un article ;
- Vérifier que vous (l'auteur) le suivez bien ;
- Modifier l'article ;
- Le faire revalider ;
- Constater que vous ne le suivez plus.

Gabbro.
                    

Sujet: https://zestedesavoir.com/forums/sujet/8155/la-publication-dune-nouvel-version-dun-contenu-suivi-fait-quon-ne-le-suit-plus/
*Envoyé depuis Zeste de Savoir*

**Comment by gllmc** [comment]
Il y a juste un point qui m'étonne, c'est que plusieurs modifications ont été apportées à [l'article sur la v22](https://zestedesavoir.com/articles/1747/zeste-de-savoir-continue-son-amelioration/) et que je lui suis toujours (et je n'ai pas souvenir de m'être réabonné). Est-ce que ça ne se produirait que dans des cas particuliers ?

**Comment by EGabbro** [comment]
Il a été validé 3 fois au total (d'après l'historique). Ça a très bien pu faire Suivi -> Plus de suivi -> Re-suivi. Donc finalement, tu suis bien l'article.

**Comment by gllmc** [comment]
Je viens de tester tout ça et je confirme ton analyse, il y a suivi à la première et la troisième publication, mais pas à la deuxième.

**Comment by pierre-24** [comment]
Ça a une gueule de `truc = not truc`, ça :)

**Comment by gllmc** [comment]
Je viens de jeter un œil au code et le problème me semble venir d'[ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/notification/receivers.py#L252). ;)

**Comment by AmarOk1412** [comment]
Ouai suffit de vérifier `if not NewPublicationSubscription.objects.get_existing(user, user):` avant. Je prends ;)
