### ISSUE TITLE
Internal Server Error lors d'une action de +1 / -1

### ISSUE THREAD

**Issue by Taluu** [zestedesavoir/zds-site#424]
cf [http://zestedesavoir.com/forums/sujet/91/bug-internal-server-error-sur-les-1-1](http://zestedesavoir.com/forums/sujet/91/bug-internal-server-error-sur-les-1-1)

A combiner avec #423, of course.

**Comment by firm1** [comment]
N'ayant pas lancé de testsuite avant mon dernier commit, j'ai introduit un bug.

C'est corrigé.
