### ISSUE TITLE
Token expiré = compte mort ?

### ISSUE THREAD

**Issue by Taluu** [zestedesavoir/zds-site#425]
J'ai fait la connerie de pas regarder dans mes spams, et de ne pas activer mon compte ;  une fois le token de validation expiré, on se retrouve avec un message "Vous n'êtes pas autorisé à vous connecter"

Soit.

Mais, une fois le mail retrouvé (grumbl), si le token d'inscription est périmé,  on a un message "Désolé, votre de jeton de confirmation a expiré, vous devez vous réinscrire." ; je pense pas que ce soit des plus pratiques...

A ce propos, que faire en cas de non activation ? Je pense que ne pas laisser l'utilisateur faire **quoique ce soit** en attendant qu'il valide son compte serait **beaucoup** plus judicieux que de le laisser vadrouiller le temps que son token soit actif, et faire ainsi un semblant de peine de mort...

**Comment by firm1** [comment]
Désormais, lorsqu'un jeton expire on peut le regenerer pour une heure encore.

ça règle donc ce souci.
