### ISSUE TITLE
CSRF input doublon

### ISSUE THREAD

**Issue by Monadologie** [zestedesavoir/zds-site#4253]
Bonsoir,

On note la présence de deux mêmes champs input pour un même formulaire sur la page de [connexion](https://zestedesavoir.com/membres/connexion/). Par ailleurs, le problème semble, _a priori_, unique ; ce dernier n'étant pas présent dans la page d'inscription.

En voici l'aperçu, `<input type="hidden" name="csrfmiddlewaretoken" value="x">` et `<input type="hidden" name="csrfmiddlewaretoken" value="x">`.

Si ce n'est pas urgent, je peux tenter de régler ce problème...

**Comment by Monadologie** [comment]
Veuillez m'excuser pour ce ... "doublon".

**Comment by gllmc** [comment]
Visiblement, il suffirait de supprimer [cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/forms.py#L67) pour résoudre le problème (c'est le seul formulaire où elle est présente). Je tague Facile. :)

**Comment by Monadologie** [comment]
@GCodeur Yep, j'ai aussi trouvé ça 👍 
Merci pour la confirmation.

**Comment by Monadologie** [comment]
Problème résolu !

**Comment by gllmc** [comment]
Merci pour ta PR, j'aurais le temps de la regarder ce soir !
Généralement, on préfère clore le ticket quand la PR est mergée (parce que si finalement on ferme la PR sans la merger par exemple, on aura perdu le ticket). ;)

**Comment by Monadologie** [comment]
Pas de problème !
Cependant, j'ai eu un léger problème avec cette dernière xD
Je te laisse regarder...

**Comment by gllmc** [comment]
Merci @Monadologie !
