### ISSUE TITLE
Sidebar de la page « Mot de passe oublié »

### ISSUE THREAD

**Issue by Monadologie** [zestedesavoir/zds-site#4257]
Bonjour,

On observe sur [cette](https://zestedesavoir.com/membres/reinitialisation/) page un block aside .sidebar mobile-menu-hide, inutile...

**Avant**![avant](https://cloud.githubusercontent.com/assets/21309645/24299545/db99b4d8-10a9-11e7-811b-225053dd7517.png)
**Après suppression du block et ce changement**
```
@media only screen and (min-width: 960px) (_main.scss:147)
.main .content-container {
    width: 100%;
    margin-right: 0;
} 
```
![après](https://cloud.githubusercontent.com/assets/21309645/24299663/339ae38c-10aa-11e7-8c7f-b5c798be921f.png)

Qu'en pensez-vous ?

**Comment by gllmc** [comment]
Personnellement, ce menu, même s'il est vide, ne me choque pas. Je trouve que ça permet de rester en adéquation avec le reste du design.

Et à la réflexion, pourquoi pas un lien de retour vers la connexion ?

![Retour à la connexion](https://zestedesavoir.com/media/galleries/3982/441bbab3-b441-486b-aec1-6011198eaf78.png)

**Comment by Monadologie** [comment]
Pourquoi pas :)

**Comment by Monadologie** [comment]
On part sur quoi du coup xD ?

**Comment by gllmc** [comment]
Personnellement, je pense que la meilleure solution d'un point de vue pratique est le lien de retour. Si tu veux faire une PR, n'hésite pas.

(De fait, il faudrait également y ajouter [cette page](https://zestedesavoir.com/membres/validation/).)

**Comment by Monadologie** [comment]
@GCodeur Pourrais-tu joindre le code que tu as utilisé dans l'image ?

**Comment by gllmc** [comment]
J'ai copié ce qu'on a sur les forums ([ici](https://github.com/zestedesavoir/zds-site/blob/dev/templates/forum/topic/index.html#L139-L141)). Si tu as besoin d'aide, tu peux passer sur [IRC](https://smoothirc.net/qwebchat/?channels=#zds-dev). :)
