### ISSUE TITLE
Token de validation expiré = banni

### ISSUE THREAD

**Issue by Taluu** [zestedesavoir/zds-site#426]
Il semblerait qu'on soit marqué en tant que "bani" (on a en tout cas cette étiquette) si le compte n'a pas été activé à temps.

Or, on est pas banni...

**Comment by firm1** [comment]
Normalement tu n'aurai pas du poster si ton compte était désactivé, donc actuellement tu apparais sur les forums comme banni a cause du bug, ce qui ne devrait pas arrivé. Donc ce n'est pas vraiment un bug pour moi.

**Comment by firm1** [comment]
J'ai isolé ces cas sous l'étiquette de "DOWN" (oui j'ai pas trouvé mieux, fallait que ça tienne en moins de 5 lettres).
