### ISSUE TITLE
Rendre compatible ZDS à Zotero

### ISSUE THREAD

**Issue by qwertygc** [zestedesavoir/zds-site#4261]
Une suggestion serait de mettre les [métadonnées nécessaires](https://www.zotero.org/support/fr/make_your_site_zotero_ready) pour rendre compatible ZDS à la citation dans Zotero.

**Comment by pierre-24** [comment]
Pourquoi pas, en effet.

**Comment by qwertygc** [comment]
Merci :-)

**Comment by rezemika** [comment]
J'ai du retard, mais ça me tente bien d'essayer. :)

**Comment by pierre-24** [comment]
Voilà qui est fait, merci @rezemika :)
