### ISSUE TITLE
[ZEP-13] Erreur 500 sur la page des alertes

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4265]
La page « Toutes les alertes » donne une erreur 500 sur la bêta quand il y a une alerte de billet. L'erreur est `'NoneType' object has no attribute 'id'`.

Je pense que c'est une erreur lors du rebase de la branche `zep-13-b` sur `dev` et donc #4241. La condition pour vérifier si l'alerte est sur un commentaire ou un billet a dû être perdue.

**Comment by artragis** [comment]
@GCodeur tu peux la fixer celle-là stp?

**Comment by gllmc** [comment]
OK, je ferai une PR dans la soirée.
