### ISSUE TITLE
Le groupe staff des fixtures n'a pas les bonnes permissions

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4266]
Actuellement, un groupe staff est créé par les fixtures [ici](https://github.com/zestedesavoir/zds-site/blob/dev/fixtures/users.yaml#L1). Cependant, les permissions qu'il se voit assigner ne sont pas les bonnes. Probablement car elles sont données via les `pk`, ce qui n'est pas viable (ils peuvent changer à tout moment et en plus, on n'a aucune idée de quelles permissions il s'agit en lisant les fixtures).

Il faudrait donc revoir les fixtures. L'idéal serait de trouver une meilleure solution que de mettre à jour les `pk`. ;)

**Comment by artragis** [comment]
est-ce toujours le cas @gcodeur ?

**Comment by pierre-24** [comment]
Oh que oui.

**Comment by gllmc** [comment]
Oui. En fait, je pense que la meilleure solution serait d'appliquer dynamiquement toutes les permissions en `change_` comme on fait pour les tests, mais je ne sais pas comment ça se fait.

**Comment by artragis** [comment]
Dupliqué dans un autre ticket où une solution meilleure a été trouvée
