### ISSUE TITLE
[ZEP-13] Quid des commentaires 

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#4267]
À un moment où à un autre, on pourra transformer un billet de tribune en contenu publié « normal » sur le site. 

[Est-il prévu de copier / déplacer les commentaires de ce billet sous le contenu ?](http://linuxfr.org/news/experience-s-de-teletravail#comment-1697027)

**Comment by pierre-24** [comment]
Mmmh, bonne question. Si on les déplacent, il faut les fermer de l'autre côté, sinon ça n'aurais servi à rien (je sais plus si dans la procédure de transformation, la tribune est retirée le cas échéant, donc je vais pas dire de conneries et m'abstenir)

**Comment by artragis** [comment]
Ça sent le débat à plein nez. Mais je pense que non. La tribune vit sa vie, l'article aussi.

**Comment by Situphen** [comment]
Up ? C'est possible de transformer un billet en article actuellement ? Si oui il faut régler cette question.

**Comment by gllmc** [comment]
C'est possible en effet. Je rejoins l'avis d'@artragis personnellement, je ne trouve pas ça forcément souhaitable.

**Comment by artragis** [comment]
je pense que les gens se contentent de la solution actuelle, je ferme.
