### ISSUE TITLE
[zep-13] Impossible de selectionner un besoin sur un article en passant par la création d'une tribune

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4268]
### Comment reproduire ?

1. Dans la liste de tous les billets, cliquez sur "nouveau billet", vous être renvoyé vers cette url : https://beta.zestedesavoir.com/contenus/nouveau-billet/
2. En remplissant le titre, je me rend compte que c'était un article que je voulais, et là, au niveau du type de contenu, je sélectionne "article"
3. On voit bien par la suite que je n'ai pas accès à la liste des besoins (rédacteurs, correcteur, etc.)

Le problème vient du fait que le bloc de demande de besoin dépend de l'url par laquelle on arrive (et donc du back-end). Sauf qu'e l'interface laisse la possibilité de changer le type de contenu.

Il y'a donc 2 solutions possibles : 

1. Masquer/afficher le bloc en JS en fonction du type sélectionné
2. Masquer la combobox type lorsque l'on clique sur "créer un billet"

Perso, je serais plutôt pour la deuxième option, qui a le mérite d’alléger un peu cette interface assez chargée.

**Comment by gllmc** [comment]
Je pense qu'on peut mettre ça en parallèle avec #4119. Si on crée une interface plus simple pour les billets, celle-ci deviendra spécifique aux tutoriels et aux articles et il n'y aura plus de problème.
Cependant, c'est à long terme. En attendant, il faut effectivement choisir une de tes solutions.

Remarque : le problème inverse existe aussi. Je viens de [créer un billet](https://beta.zestedesavoir.com/contenus/aides/?type=&page=1) avec une demande d'aide en choisissant « Nouveau tutoriel » (chose amusante, il est marqué comme tutoriel sur la page des demandes d'aide). M'est avis qu'on devrait rajouter une vérification back là-dessus.

**Comment by artragis** [comment]
Je pense que ça ne doit pas être corrigé en V1.

**Comment by Situphen** [comment]
La sélection des demandes d'aide a été déplacée ailleurs et n'est plus disponible lors de la création d'un contenu (quel qu'il soit) donc je ferme.
