### ISSUE TITLE
Aucun message lors de la réinscription

### ISSUE THREAD

**Issue by Taluu** [zestedesavoir/zds-site#427]
Lorsqu'on essaye de se réinscrire (suite à une non-activation du token... cf #425 et #426), par le passage du formulaire classique, et lors de la validation de celui-ci, on est redirigé sur celui-ci... Sans aucun message d'erreur ou de confirmation. Ou même un message quelconque.

**Comment by firm1** [comment]
Les messages d'erreur sont désormais visibles quand on se foire dans l'inscription (pseudo exisant, mail existant, mauvais password, etc.)
