### ISSUE TITLE
Dernier appel pour la v23

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#4278]
BOnjour à tous la Version 23 de zeste de savoir est sur le point de sortir

Elle ajoute plusieurs améliorations internes au code mais aussi : 

#Fonctionnalités 

- amélioration du reporting des bugs sur github #4249 #4246 
- amélioration de l'aide markdown #4078 
- Le ping?
- autocomplétion pour les nouveau messages #4236 
- LA ZEP 13

# bugfix

- badge staff mieux géré (ça va soulager les templates et la db ça :p)
- orthographe
- les tags populaires dans les tuto et articles
- et bien d'autres

Y a-t-il des tickets qu'il faut absolument mettre, je vois : 

- [x] #4104 par @artragis 
- [x] #4212 par @GCodeur 
- [x] #4275 (les depts)

**Comment by gllmc** [comment]
Bonne nouvelle !

En ce qui concerne, j'aimerais bien faire passer #4212 dans cette release. Normalement, il n'y a plus qu'à merger. Il y a #4277 aussi que je terminerai ce soir et qui devrait pouvoir passer (sauf s'il y a trop de problèmes).

En tout cas, ça va être une belle release ! :)

**Comment by Emeric54** [comment]
J'essaye de QA ce soir les PRs nécessaires.

**Comment by artragis** [comment]
#4277 faudrait mieux attendre, non? on va déjà pas mal toucher à la bdd, n'ajoutons pas du bruit, si possible.

**Comment by gllmc** [comment]
C'est possible aussi. Après, cette PR ne touche pas à un modèle existant, mais je comprends que tu puisses préférer attendre vu la taille de la release.

**Comment by artragis** [comment]
Sincèrement, je préfère attendre.

**Comment by SpaceFox** [comment]
La #4275 ? (au moins le 1er commit !)

**Comment by artragis** [comment]
J'attends la réponse de pierre pour elastic. Je mets ça dans la liste néanmoins.

**Comment by artragis** [comment]
TOut est fait, merci à tous.
