### ISSUE TITLE
Ajouter un compteur sur le nombre de billets en validation

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4279]
On ne le fera pas pour la v23, mais à l'avenir, il serait utile de rajouter le nombre de billets en validation dans le menu. Le nombre sur l'avatar serait alors la somme des tutoriels, des articles et des billets en validation.

(Par validation, on entend les billets en attente de choix par rapport à leur mise en avant. Il n'y a pas de validation à proprement parler.)

**Comment by gustavi** [comment]
Par "en attente de choix par rapport à leur mise en avant" tu veux dire que si un billet n'est pas mis en avant, il doit être compté ?

**Comment by gllmc** [comment]
S'il n'est pas mis en avant, mais aussi s'il n'a pas été ignoré, sinon il serait impossible de faire baisser le compteur sans mettre en avant des billets qui ne devraient pas l'être. ;)

**Comment by gustavi** [comment]
Je ne sais pas si c'est très pertinent.

**Comment by artragis** [comment]
Je clos car c'est déjà présent sur la v24

**Comment by gllmc** [comment]
@artragis : je me permets de rouvrir car je pense qu'il y a eu confusion. Le nombre apparaît bien sur les tutoriels et les articles, mais pas sur les billets (l'objet du ticket).

**Comment by pierre-24** [comment]
Voilà :)
