### ISSUE TITLE
Problème taille des avatar

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#428]
Les avatars apparaisent a plusieurs endroits. En particulier : 
- Dans les notifs,
- a coté des messages et commentaires,
- le notre a coté de la zone d'édition.

Sur ce dernier point il y a calirement un prob.

Déjà question style : sur le forum il semble plus grand que celui des messages juste au dessus : pourquoi ?

![i1](https://cloud.githubusercontent.com/assets/6103932/2876570/aa634998-d438-11e3-8a63-f927cee6576e.png)

Deuxième prob, dans les commentaires d'articles/tuto, la taille ne semble pas fixé du tout : 

![i2](https://cloud.githubusercontent.com/assets/6103932/2876569/aa5ddabc-d438-11e3-838b-d8b86d6cc9f3.png)

**Comment by firm1** [comment]
Pour le coup, c'est un problème de front-end.

Je suppose que tu es sous FF. je n'ai pas forcément vérifié que tout baigne dessus. Je vais fixer ça entre deux bug.

**Comment by cgabard** [comment]
Yep FF 28

**Comment by Alex-D** [comment]
Est-ce qu'il ne serait pas judicieux de vérifier que l'image uploadée/linkée ne soit pas trop grande ?

Car on pourrait se retrouver avec une page de 50Mo si un mec poste 5 fois avec une image de 10Mo...

**Comment by SpaceFox** [comment]
C'est un problème qui sera résolu tout seul si on joue correctement avec
l'issue des thumbnails (numéro jesaispluscombien, la flemme d'aller
vérifier sur Github).
Par contre ça impliquerait d'utiliser la fonctionnalité de thumbnails
partout, ce qui serait un peu lourd à l'écriture.
L'avantage c'est qu'on ne touche pas à l'image source, donc le jour où on
veut faire une MAJ du design, on a pas de problèmes de formats d'images.

À voir...

**Comment by Alex-D** [comment]
J'avais oublié les thumbnails, en effet ça retire la possibilité de flooder en poids la page. Je ne peux que plussoyer.
Du coup ce bug n'est qu'un demi-bug temporaire lié au design de la beta.

**Comment by firm1** [comment]
> Est-ce qu'il ne serait pas judicieux de vérifier que l'image uploadée/linkée ne soit pas trop grande ?

Le post principal parle des avatar, et les avatars actuellement sont uniquement gérés par lien (c'est à dire, non stockés sur le serveur) et donc on a pas d'upload à ce niveau (pour le moment).

Pour les autres images, le problème n'existe théoriquement pas aujourd'hui (parce que leur taille est limitée) et encore moins prochainement (lorsque la lib de thumbnail sera intégrée)

**Comment by Alex-D** [comment]
Selon le message de SpaceFox, j'avais compris que la lib de thumbnails serait applicable à tous types d'images, quelles qu'en soit leur provenance : possiblement les avatars (externes ou non).

Par ailleurs, on aurait les images en local, ça évitera les liens morts, même si ça va prendre quelques Mo sur le disque.

**Comment by firm1** [comment]
> Selon le message de SpaceFox, ...

le truc c'est que le message de Spacefox a été écrit après le tien (celui que j'ai cité), d'ou mon message. A moins que tu ais lu dans ses pensée :)

> Par ailleurs, on aurait les images en local, ça évitera les liens morts, même si ça va prendre quelques Mo sur le disque

On a déjà une issue sur les upload d'avatar en provenance du disque pour ça.

**Comment by Alex-D** [comment]
Est-ce qu'on ne pourrait pas considérer cette issue comme close ? Car en soi, dans ma version c'est déjà fait (en tous cas en CSS). Et la gestion des avatars distants et thumbnails sont déjà dans d'autres issues.

**Comment by SpaceFox** [comment]
AMHA il faut la laisser ouverte, ne serait-ce que pour penser à vérifier
que ce sera bien OK partout quand les diverses issues liées seront closes.

**Comment by Alex-D** [comment]
A l'heure actuelle, aucun bug de la sorte n'a été relevé, est-ce qu'on peut considérer cette issue comme close ?

**Comment by SpaceFox** [comment]
Pour moi c'est clos grâce au front d'@Alex-D, ce sera réouvert si le pb se représente.
