### ISSUE TITLE
[Tribunes] Pas moyen de valider un article issu d'une tribune

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#4284]
Étapes du test :

1. [x] Écrire et publier une tribune (sans contenu, seulement intro/conclusion, comme le feront pas mal de gens j'imagine)
2. [x] Passer la tribune en une.
3. [x] La convertir en article.
4. [x] Réserver l'article.
5. [ ] Valider l'article

Là rien ne se passe, l'article reste en validation. Si je réessaie, j'ai une erreur 500 et l'article est toujours en validation.

PS : ID sentry : b3955f27c56c40d5bb2faba2e51b0996

**Comment by artragis** [comment]
Il semblerait qu'il y ait des problèmes de doublons. enfin, surtout qu'il y ait des choses déjà présentes dans le filesystem.

**Comment by artragis** [comment]
Je valide que ça se passe comme ça.

**Comment by artragis** [comment]
Fixed
