### ISSUE TITLE
PDF des tutoriels

### ISSUE THREAD

**Issue by nils-van-zuijlen** [zestedesavoir/zds-site#4286]
Est-ce qu'il serait possible de générer un PDF du même style que le HTML téléchargeable pour les tutoriels?
L'avantage du PDF par rapport au HTML est que les informations de style et les images du tutoriel sont incluse dans un seul fichier.

**Comment by artragis** [comment]
On essaie de le faire grâce à pandoc + latex mais ça ne marche pas systématiquement (voire pas du tout ces derniers temps).

Du coup on a [un projet de réécriture complet du markdown](https://github.com/zestedesavoir/zmarkdown) pour créer nous même le PDF adéquat.

**Comment by AmarOk1412** [comment]
cf #3683

Mais en effet, c'est un des gros projets en cours. et ça avance de ce côté ;)

**Comment by nils-van-zuijlen** [comment]
Ah, ok.
Effectivement, ça n'a pas l'air simple.

**Comment by artragis** [comment]
Je clos car on a une tâche plus précise ici #4391 
pour un aperçu https://www.youtube.com/watch?v=cdJsptRdJnc
