### ISSUE TITLE
"Internal Server Error" Lors de l'edition

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#429]
On peut avoir des "Internal Server Error" lors de l'edition de message avec aperçu.
- Si je crée un sujet, clique sur edit, le modifie et valide : pas de soucis.
- Si je crée le sujet, clique edit, le modifie, clique sur aperçu puis valide l'edition: je me prend une "Internal Server Error"

**Comment by firm1** [comment]
Fixé.
