### ISSUE TITLE
[v23] Problème de sélection d'un titre lors de la création d'un nouveau sujet

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4290]
Navigateur : Firefox 52
OS : Windows

**Problème** : lorsque j'essaye de [créer un sujet](https://beta.zestedesavoir.com/forums/sujet/nouveau/?forum=1), je commence a saisir dans le titre "déploiement", je navigue au clavier (avec les flèches haut et bas) pour sélectionner la deuxième proposition. Lorsque je clique sur entrée, le texte affiché dans la zone de texte correspond à : `Créer un nouveau dépôt à partir d’un dossier d’un autre dé` alors que j'avais sélectionné `Déploiement d'une application avec WebDeploy`

**Comment by firm1** [comment]
Sinon, ça serait pas mal de limiter les choses de manière a ce que la recherche commence à partir de 3 caractères. En l'état, la recherche est active dès le premier caractère

**Comment by AmarOk1412** [comment]
@firm1 merci du signalement. J'ai le fix pour la première partie.
