### ISSUE TITLE
Cohérence HTTP / HTTPS dans la même page.

### ISSUE THREAD

**Issue by nils-van-zuijlen** [zestedesavoir/zds-site#4299]
Les images de (certains ?) tutoriels ne sont pas chargées en HTTPS, alors même que la page est demandée en HTTPS ce qui conduit à des warnings dans la console du navigateur :
```
Mixed Content: The page at 'https://zestedesavoir.com/tutoriels/870/des-interfaces-graphiques-en-python-et-gtk/1446_decouverte/5741_installation/' was loaded over HTTPS, but requested an insecure image 'http://zestedesavoir.com/media/galleries/2291/f75c16fe-5c63-45c4-b20b-65d27b9206ff.png.960x960_q85.png'. This content should also be served over HTTPS.
```

Je pense qu'il faudrait remplacer
```html
<img alt="" src="http://zestedesavoir.com/media/galleries/2291/f75c16fe-5c63-45c4-b20b-65d27b9206ff.png.960x960_q85.png">
```
par
```html
<img alt="" src="/media/galleries/2291/f75c16fe-5c63-45c4-b20b-65d27b9206ff.png.960x960_q85.png">
```
puisque les images sont affichées sur le site. Ainsi, le navigateur choisira le protocole qu'il préfère.

**Comment by nils-van-zuijlen** [comment]
P.S.: Je l'ai remarqué dans la v22, dans un tutoriel. Mais ce problème est peut-être général à toutes les images utilisateur.

**Comment by artragis** [comment]
Pour ce truc en particulier, tu peux contacter Wix pour qu'il modifie son tuto afin de mettre un https (ou simplement `/media/....` à chaque image. 

Pour éviter au plus ce genre d'erreur ça fait un petit moment que zds fournit par défaut des urls en `/media/...` pour les images des galleries. 

Sauf si tu découvres un cas vraiment génant, je vais fermer le ticket car on ne peut pas vraiment faire plus pour l'instant, trop de dépendances externes n'ont pas de https pour qu'on mette un autodupgrade.

**Comment by WinXaito** [comment]
>Sauf si tu découvres un cas vraiment génant, je vais fermer le ticket car on ne peut pas vraiment faire plus pour l'instant, trop de dépendances externes n'ont pas de https pour qu'on mette un autodupgrade.

Certes, mais on pourrait imaginer faire une regex qui contrôle si c'est une URL vers une galerie ZdS (Dans ce cas la -> `https`) ou autrement on averti l'auteur qu'il devrait essayer de fournir des images en `https`.

**Comment by artragis** [comment]
ça serait assez intrusif de faire ça dans les contenus.
