### ISSUE TITLE
I forgot my password

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#43]
Aujourd'hui, si quelqu'un perd son mot de passe, il n'a aucun moyen de la retrouver, ce qui est totalement con, puisque ça force à créer un multi juste parce qu'on a une mémoire de poisson rouge.

**Comment by GerardPaligot** [comment]
Je suis dessus mais juste une chose, comment faire pour configurer un serveur SMTP en lcoal avec Django ?

**Comment by firm1** [comment]
Normalement tu dois essayer de passer par un autre FAI. par exemple pour Gmail, tu peux rajouter ceci dans le settings.py

``` python
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'firm1@gmail.com'
EMAIL_HOST_PASSWORD = 'password-firm1'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
```

et tu peux tester l'envoi de l'email en console via : 

``` console
python manage.py shell
>>> from django.core.mail import send_mail
>>> send_mail('Mon mail de test', 'Mon super contenu de mail', to=['destinataire@tld.com'])
```

PS : N'oublie pas de virer tes paramètres de connexion gmail avant le commit.

**Comment by GerardPaligot** [comment]
Fonctionne toujours pas. J'ai une erreur du type : `SMTPAuthenticationError`. Tu n'as rien du accepter du côté de ton compte Gmail ?

**Comment by firm1** [comment]
Je ne l'ai pas trop utilisée cette solution en fait, moi je teste sur un vrai serveur directement.

Par contre, si tu as une `SMTPAuthentificationError` essaye avec le port 25 en activant le SSL. Typiquement ceci : 

``` python
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'firm1@gmail.com'
EMAIL_HOST_PASSWORD = 'password-firm1'
EMAIL_PORT = 25
EMAIL_USE_TLS = True
```

**Comment by GerardPaligot** [comment]
Nope, ça ne fonctionne toujours pas. J'ai essayé pas mal de trucs. Notamment la création d'un password spécifique pour une application du côté de mon compte Gmail mais rien n'y fait.

Cela dit, le mail devrait s'envoyer correctement puisqu'il coince uniquement à l'envoi en local. Faudra donc tester rapidement si l'envoi du mail se fait bien correctement ou non avant d'accepter le PR. Histoire de pas rester bloquer inutilement.

**Comment by firm1** [comment]
Bon bah la PR a été corrigée et mergée.

Je précise tout de même que la solution qui consiste à inclure ce bout de code dans les settings.py : 

``` python
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'monemail@gmail.com'
EMAIL_HOST_PASSWORD = 'mon-pass'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
```

Marche très bien, je l'ai utilisée pour tester cette PR.

**Comment by GerardPaligot** [comment]
Tu n'as rien dû faire du côté de ton compte Gmail ? Je ne comprends pas pourquoi ça ne fonctionne pas chez moi alors.

**Comment by firm1** [comment]
Rien de spécial du coté de gmail. Vérifie peut-etre dans les settings gmail tu as activé le SMTP ou TLS

**Comment by geoffreyc** [comment]
Peut etre ca?Certains FAI bloquent les ports SMTP, forcent les gens a
passer par leur propre serveur. Peut etre ca?

2014/1/5 Gerard notifications@github.com
