### ISSUE TITLE
[Forums] Le lien vers le dernier message d'un sujet n'est pas le bon

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#430]
Dans la liste des sujets, un sujet ayant déjà été lu n'affiche pas le lien vers le dernier message non-lu, mais réellement vers le dernier message.

Il faudrait, je pense, faire la différence.

**Comment by firm1** [comment]
C'est chose réglé désormais

**Comment by Alex-D** [comment]
Tu pourrais linker les commits car là moi je ne sais pas ce que tu as fait, et je ne peux pas l'appliquer dans ma branche :/

Ou alors indique l'issue fixée dans le merge, ça mettra un message ici.

Merci !

**Comment by firm1** [comment]
[Commit de correction](https://github.com/Taluu/ZesteDeSavoir/commit/8ba6d150831b1a2941d1398cad6a9166cdba68a6)
