### ISSUE TITLE
[Django 1.9] Utiliser les validateurs pour la taille des mots de passe

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#4300]
Tout est ici : https://docs.djangoproject.com/fr/1.10/topics/auth/passwords/#password-validation

Il faudra donc refaire les premières lignes de `zds/member/forms.py`. #4296 est un prérequis à cela.

**Comment by artragis** [comment]
Est-ce que ça aura un effet sur les mot de passe déjà existant?

**Comment by gllmc** [comment]
Très bonne idée, d'autant que je trouve les contraintes de ZdS trop souples (les 6 caractères notamment). :)

@artragis : il faudra faire attention à ne pas mettre les nouvelles contraintes sur le `LoginForm` pour permettre aux membres avec des mots de passe "obsolètes" de se connecter. Sinon je ne pense que ça pose problème.

**Comment by gustavi** [comment]
@artragis aucun changement.

@GCodeur c'est déjà pris en compte pour le changement de version de Django.

**Comment by artragis** [comment]
Ok, donc je te fais confiance.
