### ISSUE TITLE
[v23] 404 quand on tente de mettre en beta

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#4303]
Version : v23-RC1/d72827c
OS : Mac
Navigateur : Chome 57.0.2987.133

---

J'ai tenté de mettre mon tutoriel Android en bêta ([celui-ci](https://beta.zestedesavoir.com/contenus/609/aller-plus-loin-dans-le-developpement-android/)). J'ai eu une 404 à la confirmation et depuis, c'est mon tutoriel qui est placé en 404.

**Comment by GerardPaligot** [comment]
J'enlève le tag bloquant. Ca arrive que sur un de mes tutoriels.

Néanmoins, ça reste gênant.

**Comment by artragis** [comment]
@vhf faudra voir l'état du dépôt git associé au tuto ainsi que le slug qui est déclaré dans le manifest.json.

Mais ça me paraît excessivement bizarre cette histoire.

Surtout si c'est pas reproduit ailleurs.

**Comment by nils-van-zuijlen** [comment]
@vhf l'examen du dépot a-t-il porté des fruits ?

Par ailleurs, est-ce que #3906 n'aurait pas le même type de problème ? (C'est à dire un dépot git dans un état différent que la BdD ?

**Comment by vhf** [comment]
Non, honnêtement je saurais pas quoi regarder.
