### ISSUE TITLE
[v23] La promotion d'un billet en article fait perdre des icones

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4305]
J'ai publié un billet, il a été promu en article directement.

[Version publique du billet](https://beta.zestedesavoir.com/billets/1777/un-gros-troll-de-plus-sur-javascript/)
[Version publique de l'article](https://beta.zestedesavoir.com/articles/1799/un-gros-troll-de-plus-sur-javascript-1/)

On voit bien que la version article n'a plus d’icône, alors qu'elle existait sur le billet.

**Comment by artragis** [comment]
fix incoming.
