### ISSUE TITLE
[v23] La recherche sur les billets est kassay

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4306]
Lorsqu'on fait une recherche sur un billet, par exemple [celui sur le Troll JS](https://beta.zestedesavoir.com/rechercher/?q=Un+gros+Troll+de+plus+sur+Javascript&models=content), en cliquant sur le lien dans les résultats, on obtient une `404`

**Comment by pierre-24** [comment]
Vu qu'il s'agit d'une faute dans l'url (tribune à la place de billet), je dirais simplement qu'on a oublié de réindexer l'ensemble des résultats :) (ping @vhf ou @artragis, je sais pas qui s'en est chargé)

**Comment by artragis** [comment]
Ah, je savais pas qu'il fallait réindexer. Je mets ça dans le upgrade.

**Comment by pierre-24** [comment]
[ben ça y est, nan](https://github.com/zestedesavoir/zds-site/blame/release-v23/update.md#L1023) ?

**Comment by artragis** [comment]
Je ferme. Merci.
