### ISSUE TITLE
[v23] L'appel a voir la tribune de ... a disparu

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4307]
Suite a [ma déclaration de bug](https://zestedesavoir.com/forums/sujet/8407/v23-en-beta-une-petite-version-de-40-ticket/?page=3#p147201) sur le forum, un [fix a été initié](https://github.com/zestedesavoir/zds-site/pull/4289) et mergé, pour restreindre l'appel à voir les tribunes d'un membre aux billets.

Je suis surpris qu'il ne fonctionne pas en beta. Sur [ce billet](https://beta.zestedesavoir.com/billets/1785/la-congolexicomatisation-des-lois-du-marche/) par exemple, on devrait m'inciter à voir la tribune de rezemika.

**Comment by artragis** [comment]
Je comprends pas, d'autant que @gustavi a fait la QA.

**Comment by artragis** [comment]
Fixed.
