### ISSUE TITLE
[v23] L'ordre de tri des billets sur la page d'accueil est incompréhensible

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4308]
Hello,

Regardez cette capture (ce que l'on voit sur la page d'accueil) : 

![billets choisis](https://zestedesavoir.com/media/galleries/241/589868da-93fd-4165-91eb-eca4210fc8c1.png)

J'ai l'impression qu'il y a pas d'ordre. Pourquoi ?

Les dates de publications affichées sont disparates. On passe d'un billet publié il y'a 17h à un billet publié il y a 2 jrs, puis a un billet publié il y a 17h, puis à un autre billet publié il y a 1 jr. Si c'est voulu, je veux bien connaitre l'explication, mais en l'état ça ressemble à un bug.

**Comment by pierre-24** [comment]
La même explication que d'habitude. La date que tu vois est celle de publication, tandis que les billets sont triés par date de mise en avant. Je sais pas si afficher la date de mise en avant serait plus judicieux, note, mais si tu trouves que oui ...

**Comment by SpaceFox** [comment]
Comme je le disais sur les forums, on ne peut pas laisser en l'état, parce
que c'est incompréhensible.

Le 18 avril 2017 à 11:51, Pierre Beaujean <notifications@github.com> a
écrit :

**Comment by firm1** [comment]
J'aurai tendance a dire que sur la home page, on a même pas besoin d'afficher une date pour les billets. 

Parce qu'afficher la date de mise en avant sur la home va rapidement devenir déroutant lorsque l'on ira sur "tous les billets" (les dates seront effectivement celles de publications).

Donc en gros, je suggère de virer la date des billets mis en avant sur la home.

**Comment by artragis** [comment]
Ok, je fais ça dès que j'ai le temps.
