### ISSUE TITLE
[v23] Les tags sur les tribunes ne sont pas pertinents

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4309]
Voici la capture de la home page.

![](https://camo.githubusercontent.com/33c17af7fafa7c7c34d2419929220c261bfd4e81/68747470733a2f2f7a6573746564657361766f69722e636f6d2f6d656469612f67616c6c65726965732f3234312f35383938363864612d393366642d343136352d393165622d6563613432313066633863312e706e67)

Sur la capture ci-dessus, lorsque je clique sur le tag "humour", je suis redirigé [vers là](https://beta.zestedesavoir.com/contenus/?tag=humour) avec le gentil message "Aucun contenu disponible."

Niveau ergonomique ça ne me parait pas judicieux.

Plus généralement, les tribunes ne semblent pas accessibles par les tags sur la beta, mais dans l’affichage, on donne encore la possibilité au lecteur de cliquer sur les tags d’un billet. ça ressemble donc à un bug (probablement un oubli).

**Comment by artragis** [comment]
Cause : on met contenus au lieu de billets. fix incoming;
