### ISSUE TITLE
Lien de citation erroné

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#431]
Il manque l'adresse du site devant l'adresse de la citation.
Actuellement le lien contient quelque chose comme "http://forums/sujet/13/test?page=1#p307"

Il manque zestedesavoir.com/

**Comment by SpaceFox** [comment]
AHMA il ne manque pas l'adresse du site, mais il y a le "http://" en trop
(--> production automatique de liens relatifs).

Sous réserve que les liens relatifs fonctionnent quand on est dans une
sous-arborescence, bien sûre (il faut une balise <base> ou un truc du genre
dans les headers, non ?)

**Comment by Alex-D** [comment]
Non, les liens relatifs ont été interdits. Il FAUT mettre le lien absolu à cet endroit.

**Comment by SpaceFox** [comment]
> Non, les liens relatifs ont été interdits.

???

**Comment by cgabard** [comment]
Bin on m'a demdandé de mettre le `http://` systématiquement si il manquait sur les liens, ce qui revient à interdire les adresses relatives dans le markdown.

**Comment by cgabard** [comment]
cf : https://github.com/Taluu/ZesteDeSavoir/issues/137

**Comment by SpaceFox** [comment]
Ah OK, j'avais oublié ça. Du coup j'ai rien dit, et oui il faut le nom de
domaine :D

2014-05-05 17:09 GMT+02:00 Christophe Gabard notifications@github.com:

**Comment by firm1** [comment]
Fixé.
