### ISSUE TITLE
[v23] La promotion d'un billet en article fait perdre la source

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4311]
J'ai publié un billet, il a été promu en article directement.

[Version publique du billet](https://beta.zestedesavoir.com/billets/1777/un-gros-troll-de-plus-sur-javascript/)
[Version publique de l'article](https://beta.zestedesavoir.com/articles/1799/un-gros-troll-de-plus-sur-javascript-1/)

Dans les sources html du billet on peut voir que la source a été migrée et on aperçoit `<link rel="canonical" ... >`, mais aucune de cette mention dans l'article.

Je suppose donc que la source n'a pas été migrée.

**Comment by artragis** [comment]
je m'en occupe asap
