### ISSUE TITLE
[v23] Pas d'accès rapide dans la page de profil pour les billets

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4312]
Sur ma page de profil j'ai cette capture.

![acces-rapide](https://cloud.githubusercontent.com/assets/6066015/25139215/ed570baa-245c-11e7-908e-06965680de7c.PNG)

On a un lien d'accès rapide pour les tutoriels et article, sujets et cie, mais le lien pour les billets a été oublié.

**Comment by artragis** [comment]
dans la version 24
