### ISSUE TITLE
Alerter le staff en cas de fournisseur de mail inconnu et pouvoir le bannir facilement.

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#4313]
Il y a maintenant tellement de domaines de premier niveau (TLD) que les fournisseurs de mail-poubelle peuvent pratiquement générer des noms de domaines (NDD) à la demande ; autant dire que notre liste de blocage ne peut plus vraiment fonctionner.

Une idée serait donc de faire évoluer la fonctionnalité en étapes :

1. Quand un membre a validé (= a cliqué sur le lien de confirmation) un NDD d'email inconnu, une alerte est envoyée au staff pour qu'il puisse y jeter un œil.
2. Le staff dispose d'une interface qui lui permette d'ajouter facilement un NDD de mail à la liste des domaines bannis (avec une alerte s'il y a déjà plusieurs membres qui ont ce NDD dans la base, pour limiter les risques de bloquages de vrais fournisseurs par erreur.

Ça implique évidemment que notre liste soit transférée dans une table.

PS : c'est très facile de savoir si un NDD est propriété d'un fournisseur de mails-poubelle, il suffit de le chercher dans un moteur de recherche.

**Comment by gllmc** [comment]
Je prends, ça me paraît intéressant à faire (mais faudra quand même que je termine l'historisation avant). :)

Par un NDD d'e-mail inconnu, tu veux dire que le NDD est utilisé pour la première fois ?

**Comment by SpaceFox** [comment]
> Par un NDD d'e-mail inconnu, tu veux dire que le NDD est utilisé pour la première fois ?

Exactement.

**Comment by gustavi** [comment]
Une feature béton serait de pouvoir lister tous les membres utilisant ce NDD et donc pouvoir détecter facilement des bots/multis/whatever. Bon après ça se fait en 2 secondes via la console Django mais c'est toujours plus sympa quand c'est *user-firendly*.

**Comment by gllmc** [comment]
Reprise depuis IRC :

@GCodeur :

> Au fait SpaceFox, tu tombes parfaitement vu que je suis en train de m'occuper de #4313. je pense à un lien "Fournisseurs bannis" dans le footer et un lien "Nouveaux fournisseurs" dans le menu membre avec le nombre entre parenthèses, ça te va ?

@SpaceFox :

> GCodeur> pose plutôt la question sur le Github (il est là pour ça), mais pour moi coller un lien dans le footer est inutile

Mais où mettre la liste des fournisseurs bannis ? Un autre lien dans le menu membre ? Puisque j'ai distingué deux modèles : `NewEmailProvider` (un nouveau fournisseur) et `BannedEmailProvider` (un fournisseur banni).

**Comment by vhf** [comment]
@GCodeur On ne va pas l'afficher aux visiteurs.

**Comment by gllmc** [comment]
@vhf : Non bien sûr, je pensais à des liens qui ne s'affichent que si l'utilisateur courant est staff (comme quand on réserve le lien `Adhérer` aux membres).

**Comment by vhf** [comment]
Ok. Ça me semble quand même pas nécessaire. On n'a que 2 niveaux de "permissions" au niveau des "actions" sur le site : staff et pas staff.

Je pense pas que tout le staff doit pouvoir modifier la liste des providers interdits. Du coup pas nécessaire d'avoir une interface pour ça. On le fera depuis django admin et voilà. Il faut en revanche que le message de refus d'inscription soit sans équivoque, histoire qu'on n'ait pas de demandes du genre "j'arrive pas à m'inscrire, **pourquoi**"

**Comment by gllmc** [comment]
D'accord, j'avais pas compris la chose comme ça. En l'état, voici ce que j'ai fait :

- un modèle `NewEmailProvider` qui correspond à une alerte envoyée au staff et un modèle `BannedEmailProvider` qui correspond à un fournisseur interdit
- une interface listant les `BannedEmailProvider` avec un lien pour les enlever de la liste et un formulaire pour en ajouter un nouveau
- une liste des `NewEmailProvider` avec un lien `Approuver` (= enlève l'alerte) et un lien `Bannir` (= bannit le fournisseur et enlève l'alerte)

Du coup, par rapport au point 2, est-il pas nécessaire ou pas souhaitable (question vu qu'il est déjà codé) ?

Sinon, pour les liens, j'ai pensé qu'on pouvait se contenter du `Nouveaux fournisseurs` et mettre sur cette page un lien vers la liste des fournisseurs déjà interdits.

> Il faut en revanche que le message de refus d'inscription soit sans équivoque, histoire qu'on n'ait pas de demandes du genre "j'arrive pas à m'inscrire, **pourquoi**"

Yep, j'ai fait attention à ça.

**Comment by vhf** [comment]
Ah bah si c'est déjà fait garde-le. :)

Par contre je sais pas où mettre ça, j'ai pas de bonne idée là.
