### ISSUE TITLE
[v23] Erreur 403 lors de l'accès à la galerie liée à un contenu

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4314]
Sur la RC2 de la v23, lorsque je crée un contenu (testé avec un article et un billet), j'ai une erreur 403 lorsque j'accède à la galerie liée. Je pense que les droits ne sont pas ajoutés lors de la création du contenu.

Remarque : sur un contenu créé avec la RC1, je n'ai pas ce problème.

- [x] améliorer les tests pour qu'il y ait des assertion sur les galleries
- [x] check `ensure_author_gallery`

**Comment by artragis** [comment]
ok c'est ma modif de refacto qui a joué alors.
