### ISSUE TITLE
[v23] Certains tags ne fonctionnent pas sur les tribunes

### ISSUE THREAD

**Issue by rezemika** [zestedesavoir/zds-site#4317]
Sur la bêta actuelle (v23-RC2/ed0cf8f), quand je cliques sur certains tags de tribunes, il arrive que je tombes sur une page vide indiquant "Aucun contenu disponible.", alors que le tag est effectivement attaché à une tribune.

Cela se produit, à minima, avec les tags suivants : 

- ccc
- non
- programmation
- wtf
- humour
- test

Aussi, quand je cliques sur le tag "économie" d'une tribune ([celle-ci](https://beta.zestedesavoir.com/billets/1785/la-congolexicomatisation-des-lois-du-marche/) par exemple), seuls des articles apparaissent dans la liste renvoyée, aucune tribune. L'url "/contenus/" utilisée pour afficher les résultats étant assez généraliste, on s'attendrait à ce qu'elle renvoie aussi bien des articles que des tribunes (voire des tutos, puisqu'on les qualifie aussi de contenus).

**Comment by gllmc** [comment]
C'est corrigé par #4310, qui n'est pas déployée sur la bêta (cf ticket #4309). ;)
