### ISSUE TITLE
Le script de déploiement ne signale pas quand un tag n'existe pas

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#4322]
Le script `script/deploy.sh <tag>` fait comme si de rien n'était quand on tente de déployer un tag qui n'existe pas.

On a perdu 5min avec @artragis parce que comme un clown je tentais de déployer `V23-RC3` sur la beta. Le tag s'appelle en réalité `v23-RC3`. :trollface: 

Il vaudrait aussi la peine d'y ajouter un warning pour que la personne déployant le truc pense le cas échéant à réindexer les données d'ES.

**Comment by artragis** [comment]
Jez mets priorité haute, car la v24 sera une version de passassion.

**Comment by SpaceFox** [comment]
Le script de déploiement était volontairement minimaliste, tout en
interdisant de déployer de la merde. C'était volontaire en supposant que la
personne qui déploie est capable de comprendre pourquoi ça ne fonctionne
pas.
D'ailleurs, c'était un peu la même pour la conf HTTP (qui est devenu
imbitable, j'ai essayé de la repiquer pour un projet perso et j'ai
abandonné).

KISS les gens.

2017-04-27 22:07 GMT+02:00 artragis <notifications@github.com>:

**Comment by vhf** [comment]
Oui voilà ! Il était censé interdir de déployer de la merde, et pourtant une bête faute de casse, j'ai fait `deploy V23-RC3` au lieu de `deploy v23-RC3` déployait une version random, impossible de comprendre ce qui se passait.

Du coup là, ça ira nettement mieux.

Et franchement, c'est pas parce qu'on sait pas ce qu'on fait, et ça tu le sais. ;)

**Comment by SpaceFox** [comment]
C'est là où je ne pige pas alors, normalement il était censé s'arrêter en disant que le tag n'existe pas.
