### ISSUE TITLE
Changer l'icône des billets sur la page d'accueil

### ISSUE THREAD

**Issue by Fumble** [zestedesavoir/zds-site#4324]
Actuellement, l'icône des billets sur la page d'accueil est la même que celle des tutoriels.

![image](https://cloud.githubusercontent.com/assets/634461/25611948/2d30dc16-2f29-11e7-94a2-1279de7ca149.png)

Il faudrait peut-être la changer par une icône du genre bloc-notes ou post-it. Ou quelque chose qui rappelle un blog. Le journal étant déjà pris par les articles.

**Comment by Emeric54** [comment]
Je crois que quelqu'un a déjà réalisé une illustration, mais je ne m'en souviens pas de plus, ni de pourquoi elle n'a pas été utilisée...

**Comment by gllmc** [comment]
Voici pour l'image déjà faite : https://github.com/zestedesavoir/zds-site/pull/3606#issuecomment-242962177. ;)

**Comment by gustavi** [comment]
On avait convenu que cette image n'allait pas, c'est pour cela qu'on ne l'avait pas intégrée

**Comment by gllmc** [comment]
Sans icône approuvée, ce ticket n'est pas facile, j'enlève le tag. ^^

**Comment by A-312** [comment]
> 
> 
> Voici pour l'image déjà faite : [#3606 (comment)](https://github.com/zestedesavoir/zds-site/pull/3606#issuecomment-242962177). ;)

Celui là donc : ![687474703a2f2f73746f726167652e616c65782d642e66722f7a6573746564657361766f69722f74726962756e65732d6c69627265732e706e67](https://user-images.githubusercontent.com/18501150/50315779-5f3d7b80-04b4-11e9-8d7f-1a7dff23e378.png) ?

**Comment by A-312** [comment]
On part sur l'icone de : 
![image](https://user-images.githubusercontent.com/18501150/50315858-9ca20900-04b4-11e9-9ab9-a7e371cb5458.png) ?

Il faut juste trouver celle sans fond.

**Comment by A-312** [comment]
![v1](https://user-images.githubusercontent.com/18501150/50337101-672b0900-0510-11e9-9f19-d1b8b175b7d2.png)
![v1-2](https://user-images.githubusercontent.com/18501150/50337102-672b0900-0510-11e9-9c09-8eb475e33265.png)
![v2](https://user-images.githubusercontent.com/18501150/50337103-672b0900-0510-11e9-8f62-b7598ca9a474.png)
![v3](https://user-images.githubusercontent.com/18501150/50337105-67c39f80-0510-11e9-9d7d-23979797e356.png)
![v1-render](https://user-images.githubusercontent.com/18501150/50337114-701bda80-0510-11e9-95f2-0ac5affb85ab.png)
![v1-2-render](https://user-images.githubusercontent.com/18501150/50337116-701bda80-0510-11e9-9285-8cfdec0b7652.png)
![v2-render](https://user-images.githubusercontent.com/18501150/50337117-701bda80-0510-11e9-94cb-f500a741f061.png)
![v3-render](https://user-images.githubusercontent.com/18501150/50337119-701bda80-0510-11e9-90c3-cd67d7b6825e.png)

https://zestedesavoir.com/forums/sujet/8835/icone-par-defaut/?page=2#p195372

**Comment by A-312** [comment]
![9ccb6952-9131-435c-804e-9b897d906c52](https://user-images.githubusercontent.com/18501150/50344463-6489dd00-052b-11e9-9ff6-f1e83dadb697.png)

https://zestedesavoir.com/forums/sujet/8835/icone-par-defaut/?page=2#p195394

**Comment by A-312** [comment]
Je pense le faire

@artragis Je pourrais re-avoir la permission pour m'assigner (si elle existe encore) ?
