### ISSUE TITLE
Ajout du compteur de commentaires pour les billets sur la page d'accueil

### ISSUE THREAD

**Issue by Fumble** [zestedesavoir/zds-site#4325]
Il serait sans doute pertinent de rajouter la bulle du compteur de commentaires comme pour les articles:

![image](https://cloud.githubusercontent.com/assets/634461/25612116/bb0850dc-2f29-11e7-80ef-3c5cd46e697a.png)

![image](https://cloud.githubusercontent.com/assets/634461/25612121/c508b7d4-2f29-11e7-8976-7d83d0938751.png)

**Comment by gllmc** [comment]
Merci @rezemika !
