### ISSUE TITLE
Installation d'une version locale de ZDS pour Mac

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#433]
J'ai voulu remettre à jour une version locale de ZdS sur mon Mac mais j'ai quelques soucis. Je parviens à lancer le serveur mais je n'arrive pas à afficher une page du site. Je me suis alors tourné vers la documentation dans le README mais il semblerait que l'installation diffère sur Mac et sur Linux.

J'ouvre cette issue pour pouvoir ajouter l'installation sur Mac au README du projet et permettre aux développeurs sur OS X de contribuer au projet. Même si je ne pars pas d'une installation de 0, voici les problèmes que je rencontre :
- `pip` ne fonctionne pas sur toutes les commandes. J'alterne avec `easy_install` que je suis obligé de lancer en super utilisateur.
- Je suppose que mon `easy_install` fonctionne (aucune stack trace m'est présentée en tout cas) mais je n'arrive quand même pas à installer certaines des librairies mentionnées dans le fichier `requirements.txt`.
- Pour le moment, quand j'essaye d'afficher une page, j'ai l'erreur suivante :

``` console
AttributeError at /
'module' object has no attribute 'atomic'
```

Voilà. Je sais que les développeurs Mac ne se bousculent pas sur le projet et qu'il y a du taff avec la bêta mais si certains ont des idées à ce sujet, je suis preneur.

**Comment by firm1** [comment]
2 questions : 
- Est-ce que tu utilise virtualenv ?
  - Si non, je te conseille de l'installer vu qu'on en a fait un standard zds
  - Si oui, peux-tu nous donner le résultat de la commande 'pip freeze' une fois dans le bon environnement python ?

**Comment by GerardPaligot** [comment]
Nope, je n'utilise pas virtualenv. Je me rappelle que j'avais tenté de l'utiliser à l'époque mais sans succès.

Que veux-tu dire par un standard zds ?

**Comment by SpaceFox** [comment]
> Que veux-tu dire par un standard zds ?

Qu'on part du principe que tu l'utilise.

2014-05-05 23:14 GMT+02:00 Gerard notifications@github.com:

**Comment by firm1** [comment]
> Que veux-tu dire par un standard zds ?

C'est à dire qu'il est imposé pour installer zds dedans, étant donné tout ce qui peut polluer ton système, vaut mieux sandboxer zds. Tes problèmes d'install viennent du fait que tu as d'autres trucs qui rentrent en conflit.

Du coup, je te conseille d'installer : 
- easy install
- pip
- virtualenv

Et de créer un environnement dédié à zds. Normalement, à part lxml (que tu dois installer avec easy_install) tout devrait passer, même sur mac.

**Comment by GerardPaligot** [comment]
Bien, je vais me repencher sur `virtualenv`.

**Comment by GerardPaligot** [comment]
J'avais un ancien macbook sous la main et je me suis donc lancé dans l'installation d'une version locale de ZdS. Un environnement complètement clean, j'avais fais un format à l'époque.

Dans l'ordre, j'ai exécuté les commandes suivantes :

```
$ sudo easy_install pip
$ sudo pip install virtualenv
$ sudo pip install virtualenvwrapper
$ source /usr/local/bin/virtualenvwrapper.sh
$ mkvirtualenv zdsenv
(zdsenv) $ mkdir workspace-zds
(zdsenv) $ cd workspace-zds
(zdsenv) $ git clone https://github.com/Taluu/ZesteDeSavoir.git
(zdsenv) $ sudo easy_install lxml # Erreur.
(zdsenv) $ ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
(zdsenv) $ brew install libxml2
(zdsenv) $ brew install libxslt
(zdsenv) $ pip install lxml # Erreur.
```

L'erreur est : `error: command 'cc' failed with exit status 1`.

**Comment by firm1** [comment]
Pour toi, pour lxml, je suppose que tu dois faire comme dans la [doc](http://lxml.de/installation.html#macos-x)

**Comment by GerardPaligot** [comment]
Bien, j'ai fais pas mal de manipulations et je n'arrive toujours à rien. J'essaye de restituer mes commandes (utiles) le plus fidèlement possible :

```
(zdsenv) $ sudo port install py25-lxml # Tentative d'installation lxml
(zdsenv) $ sudo port build py32-pillow # Installation de pillow
(zdsenv) $ export CFLAGS=-Qunused-arguments 
(zdsenv) $ export CPPFLAGS=-Qunused-arguments
(zdsenv) $ sudo pip install lxml # Erreur
```

J'ai toujours la même erreur. Ce qui coince semble être `lxml`. Voici mon erreur un peu plus complète :

```
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/opt/local/include -I/opt/local/include/libxml2 -I/Users/Gerard/.virtualenvs/zdsenv/build/lxml/src/lxml/includes -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.macosx-10.9-intel-2.7/src/lxml/lxml.etree.o -w -flat_namespace

clang: error: unknown argument: '-mno-fused-madd' [-Wunused-command-line-argument-hard-error-in-future]

clang: note: this will be a hard error (cannot be downgraded to a warning) in the future

error: command 'cc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /Users/Gerard/.virtualenvs/zdsenv/bin/python -c "import setuptools, tokenize;__file__='/Users/Gerard/.virtualenvs/zdsenv/build/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PQVVPI-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/Gerard/.virtualenvs/zdsenv/include/site/python2.7 failed with error code 1 in /Users/Gerard/.virtualenvs/zdsenv/build/lxml
Storing debug log for failure in /Users/Gerard/.pip/pip.log
```

Si vous avez des idées ou pistes, je suis preneur.

**Comment by cgabard** [comment]
> sudo port build py32-pillow # Installation de pillow

Là tu ne dis pas de l'installer pour python 3.2 ? si c'est le cas il ne sera pas accesible a python 2 !

Pour l'autre erreur, il ne comprend pas un des arguments de la ligne de commande. Je pense que c'est dut au fait que le paquet est fait pour être compilé avec gcc et non clang.

Heureusement, tu ne semble pas être le seul et certains ont trouvés une parade : http://stackoverflow.com/questions/22313407/clang-error-unknown-argument-mno-fused-madd-python-package-installation-fa

**Comment by GerardPaligot** [comment]
Ok, l'installation de toutes les dépendances semblent fonctionner grâce à ton lien (bizarre, parce que j'avais déjà rajouté les flags mais ils n'étaient pas passés). Bon du coup, voici les commandes que j'ai lancé pour que ça fonctionne :

```
(zdsenv) $ sudo port build py27-pillow
(zdsenv) $ export CFLAGS=-Qunused-arguments
(zdsenv) $ export CPPFLAGS=-Qunused-arguments
(zdsenv) $ sudo -E pip install lxml
(zdsenv) $ pip install -r requirements.txt # Pour être certain que tout est installé.
```

Donc la dernière commande ne me crash plus d'erreurs et toutes les dépendances sembles installées. Ensuite, j'exécute les requêtes python habituelles pour initialiser la base de données du projet et le lancer :

```
(zdsenv) $ python manage.py syncdb
(zdsenv) $ python manage.py migrate
(zdsenv) $ python manage.py runserver
```

Mais lorsque je veux accéder au site (http://127.0.0.1:8080), il m'affiche dans mon navigateur :

```
A server error occurred.  Please contact the administrator.
```

Et dans ma console :

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 194, in __call__
    signals.request_started.send(sender=self.__class__)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/haystack/__init__.py", line 60, in reset_search_queries
    for conn in connections.all():
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/haystack/utils/loading.py", line 110, in all
    return [self[alias] for alias in self.connections_info]
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/haystack/utils/loading.py", line 98, in __getitem__
    self._connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/haystack/utils/loading.py", line 51, in load_backend
    return import_class(full_backend_path)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/haystack/utils/loading.py", line 18, in import_class
    module_itself = importlib.import_module(module_path)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/haystack/backends/solr_backend.py", line 18, in <module>
    raise MissingDependency("The 'solr' backend requires the installation of 'pysolr'. Please refer to the documentation.")
MissingDependency: The 'solr' backend requires the installation of 'pysolr'. Please refer to the documentation.
```

Sachant que `pysolr` est installé, je ne pige pas trop.

**Comment by firm1** [comment]
Peux tu donner le résultat de ta commande `pip freeze` biensur lancée depuis ta sandbox.

**Comment by GerardPaligot** [comment]
Ouaip, voici le résultat :

```
Django==1.6.4
GitPython==0.3.2.RC1
Markdown==2.4
Pillow==2.4.0
PyYAML==3.10
Pygments==1.6
South==0.8.4
async==0.6.1
bleach==1.2.2
coverage==3.7.1
crispy-forms-foundation==0.3.2
defusedxml==0.4.1
django-crispy-forms==1.3.2
django-debug-toolbar==1.2
django-discover-runner==0.4
django-dynamic-fixture==1.7.0
django-email-obfuscator==0.1.3
django-filter==0.7
django-guardian==1.2.0
django-haystack==2.1.0
django-oauth2-provider==0.2.6.1
django-pipeline==1.3.24
django-rest-swagger==0.1.14
django-simple-captcha==0.4.2
djangorestframework==2.3.13
factory-boy==2.2.1
gitdb==0.5.4
html5lib==0.95
httplib2==0.9
lxml==3.3.5
pygal==1.4.6
pygeoip==0.3.1
pysolr==3.2.0
pytz==2013d
shortuuid==0.4.2
six==1.6.1
smmap==0.8.2
wsgiref==0.1.2
```

**Comment by firm1** [comment]
Euh ... ta version de ZdS tu la tire de quelle branche ?

**Comment by SpaceFox** [comment]
Je suis en train de me dire qu'il faudrait passer la branche
"release-beta-1.0" en branche principale, on fait plein de conneries à
cause de ça...

2014-05-08 1:24 GMT+02:00 firm1 notifications@github.com:

**Comment by Alex-D** [comment]
+1 pour passer la branche principale en branche principale...

**Comment by GerardPaligot** [comment]
J'étais sur la branche dev mais le souci se présente sur la branche "release-beta-1.0" et "integration" aussi.

**Comment by GerardPaligot** [comment]
Bon, je ne comprends pas. Comme j'avais fais pas mal de tests sur mon ancien environnement, j'en ai créé un nouveau et j'obtiens une nouvelle erreur dans MathJax :

```
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/Users/gerard/.virtualenvs/zds/lib/python2.7/site-packages/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "/Users/gerard/.virtualenvs/zds/lib/python2.7/site-packages/django/middleware/common.py", line 71, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/Users/gerard/.virtualenvs/zds/lib/python2.7/site-packages/django/core/urlresolvers.py", line 596, in is_valid_path
    resolve(path, urlconf)
  File "/Users/gerard/.virtualenvs/zds/lib/python2.7/site-packages/django/core/urlresolvers.py", line 476, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Users/gerard/.virtualenvs/zds/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/Users/gerard/.virtualenvs/zds/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/gerard/.virtualenvs/zds/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/gerard/.virtualenvs/zds/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/gerard/Documents/workspace-django/ZesteDeSavoir/zds/urls.py", line 75, in <module>
    url(r'^tutoriels/', include('zds.tutorial.urls')),
  File "/Users/gerard/.virtualenvs/zds/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/gerard/.virtualenvs/zds/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/gerard/Documents/workspace-django/ZesteDeSavoir/zds/tutorial/urls.py", line 5, in <module>
    from . import views
  File "/Users/gerard/Documents/workspace-django/ZesteDeSavoir/zds/tutorial/views.py", line 39, in <module>
    from zds.member.views import get_client_ip
  File "/Users/gerard/Documents/workspace-django/ZesteDeSavoir/zds/member/views.py", line 22, in <module>
    from zds.utils.mps import send_mp
  File "/Users/gerard/Documents/workspace-django/ZesteDeSavoir/zds/utils/mps.py", line 9, in <module>
    from zds.utils.templatetags.emarkdown import emarkdown
  File "/Users/gerard/Documents/workspace-django/ZesteDeSavoir/zds/utils/templatetags/emarkdown.py", line 10, in <module>
    from markdown.extensions.zds import ZdsExtension
  File "/Users/gerard/.virtualenvs/zds/lib/python2.7/site-packages/markdown/extensions/zds.py", line 36, in <module>
    from .mathjax import MathJaxExtension
  File "/Users/gerard/.virtualenvs/zds/lib/python2.7/site-packages/markdown/extensions/mathjax.py", line 27
    (?<!\\)(?P<St>\$\$?)(.+?)(?<!\\)(?P=St)
     ^
SyntaxError: invalid syntax
```

**Comment by Alex-D** [comment]
C'est étrange comme syntaxe le ?< moi j'utilise ?: 
Peut-être que ça viendrait de ça... mais assez étrange quand même cette histoire.

**Comment by firm1** [comment]
Ah on tient le bon bout.

Il y'a un léger bug qui traine du coté de l'extension markdown en ce moment (je l'ai remarqué en appliquant la MAJ tout à l'heure sur la prod). Il faut rollback dessus.

En résumé fait ceci (depuis ta sandbox) et relance ton serveur : 
`pip install --upgrade git+https://github.com/zestedesavoir/Python-ZMarkdown.git@2.4-zds.2.8`

En attendant que zmarkdown soit corrigé.

**Comment by GerardPaligot** [comment]
Ok, ça fonctionne ! Super. :)

Bien, je vais commencer par enrichir le README pour expliquer la procédure d'installation sur Mac.

**Comment by firm1** [comment]
Cool.

**Comment by firm1** [comment]
Pour info, je viens de corriger le bug markdown. Donc pour tes prochaines MAJ tu peux t'en tenir à la commande : `pip install --upgrade -r requirements.txt`.

Il t'installe toutes les MAJ des dépendances (y compris zmarkdown). En fait, c'est même la commande qu'il faudrait donner officiellement.

**Comment by SpaceFox** [comment]
Doc publiée --> on peut fermer ici.
