### ISSUE TITLE
Possibilité de cacher l'aide markdown

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4334]
Bonjour,

L'aide markdown s'affiche avec une phrase aléatoire en bas de la zone de rédaction de message, dans un petit cadre coloré. Elle est bien visible, c'est certain. Mon problème, c'est que lorsque je navigue entre la zone de rédaction et la zone d'affichage de mon message, cette phrase aléatoire devient trop visible et me saute aux yeux à chaque fois. Du coup, j'aimerais pouvoir l'enlever, par exemple en cliquant sur une petite croix en haut à droite de l'encadré.

Est-ce que ce serait facilement réalisable et utile à d'autres personnes ?

**Ajout de GCodeur :** La solution retenue est d'ajouter un paramètre « Afficher l’aide Markdown dans l’éditeur » dans les paramètres du profil. Je m'en occupe.

Sujet : https://zestedesavoir.com/forums/sujet/8561/possibilite-de-cacher-laide-markdown/
*Envoyé depuis Zeste de Savoir*

**Comment by artragis** [comment]
done
