### ISSUE TITLE
Lien vers les commentaires des billets sur la page d'accueil

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#4336]
Les billets sont, comme les articles, des publications où les commentaires sont souvent intéressants. Je propose que sur la page d'accueil on affiche la bulle avec le nombre de commentaires et un lien vers eux, comme pour les articles.

**Comment by gllmc** [comment]
Déjà fait par #4328, ça arrivera donc en v24. :)

**Comment by Situphen** [comment]
Ah d'accord ! La prochaine fois je regarderai aussi dans les tickets fermés :D
