### ISSUE TITLE
Mise à jour mineure d'un billet ?

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#4338]
Cas de test :

1. J'ai un billet qui est validé pour affichage sur la home.
2. On me signale une coquille, je corrige.
3. Je publie la correction.
4. Conséquence : le billet n'est plus en une (vu qu'il a été modifié).
5. Je le re-valide pour affichage en une.

Comportement attendu :

- Le billet reprends sa place d'origine,
- Alternative : il y a une case à cocher qui permet soit de le laisser à sa place d'origine (modif mineure), soit de le repasser en haut (modif majeure).

Comportement obtenu :

- Le billet revient systématiquement en haut de la liste, c'est pas sympa pour les copains.

Il faudrait soit implémenter une « mise à jour mineure » des billets, soit les trier par date de _première_ publication en attendant d'avoir un tri plus intelligent.

**Comment by qwertygc** [comment]
trier par date de première publication : me semble la meilleure solution.
