### ISSUE TITLE
[Membre] Lien vers les sujets des forums privés sur les profils du staff

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#434]
Il faudrait masquer les liens vers les topics des forums nécessitant des droits que le visiteur n'a pas.

**Comment by firm1** [comment]
Fixé.

**Comment by Eskimon** [comment]
Je réouvre c'est revenu...

**Comment by firm1** [comment]
Plus de précision sur le lieu du bug ? un lien ou on peu le voir ?

**Comment by Eskimon** [comment]
http://zestedesavoir.com/forums/sujet/456/lien-dans-les-profils-inaccessibles/

Et je sais pas pourquoi tu l'as mentionné comme résolu oO

**Comment by firm1** [comment]
Ah je croyais que c'était le bug fixé par [cette PR](https://github.com/zestedesavoir/zds-site/pull/1041)

L'info qu'il manque, c'est par quel moyen on accède à ces sujets privés. Sur la page de profil, mais ensuite ? Moi quand je vais sur la page de profil d'un membre staff, dans se sujets crées, je ne vois rien dont je n'ai pas le droit

**Comment by Eskimon** [comment]
Oui via le profil et parce que tu es staff évidemment tu vois tout ;)

J'ai pas encore essaye de reproduire en local...

**Comment by SpaceFox** [comment]
J'ai essayé de le reproduire en local et je n'obtiens que des résultat normaux : quand je vais sur le profil d'un staff, je ne vois que les topics auxquels j'ai le droit d'accéder.

**Comment by SpaceFox** [comment]
PS : J'ai demandé des précisions sur le topic qui remontait le bug.

**Comment by SpaceFox** [comment]
OK, en fait ça concerne les sous-pages du profil, cf ici : http://zestedesavoir.com/forums/sujet/456/lien-dans-les-profils-inaccessibles/?page=1#p7162

**Comment by SpaceFox** [comment]
Je corrige ça.

**Comment by Eskimon** [comment]
C'est recorrigé je referme
