### ISSUE TITLE
Mettre à jour le CDN de MathJax

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4340]
Depuis un moment, on peut lire dans la console Javascript de ZdS le message suivant : 

> "WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips."

Ils conseillent soit de migrer vers cdnjs soit de s'autohéberger le plus tôt possible.

> We recommend switching to another CDN provider or your own copy of MathJax as soon as possible.

C'était censé couper le 30 avril, mais pour permettre aux clients de migrer, ils ont mis en place une redirection vers cdnjs, mais nul ne sait combien de temps ça va durer. Raison pour laquelle je taggue en priorité élevée.

**Comment by artragis** [comment]
bloquant.

**Comment by Theodicy** [comment]
Si j'ai bien compris, il suffrait de remplacer [ceci](https://github.com/zestedesavoir/zds-site/blob/dev/templates/base.html#L773) avec cela https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js ?

**Comment by artragis** [comment]
C'est ça !

**Comment by Theodicy** [comment]
Très bien !
Je prends.
