### ISSUE TITLE
L'option filtre disparait s'il n'existe pas de résultat

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#4343]
Salut, 

Si on va dans mes tutos ou mes article ou mes tribunes à gauche il y a l'option pour filtrer par :

-  En bêta  
-  En validation  
-  Publiés  
-  Brouillons  

Si on clique sur En beta alors qu'on a pas de tuto / article / tribune en beta le menu disparait. on a plus les choix sous l'onglet filtrer. Par conséquent on peut même plus enlever le filtre, il faut réactualisé la page.

Testé sous Safari / firefox  
 
avant:

![Avant filtre](https://www.zestedesavoir.com/media/galleries/3179/8adf27e7-a7e9-4ef0-9069-9b5d8860002c.png)  

après:

![Après filtre](https://www.zestedesavoir.com/media/galleries/3179/75f3d906-659d-4032-a6aa-e4a26b33fedf.png)

Le bug existe pour n'importe quel filtre tant qu'il n'existe pas de résultat.

Sujet : https://zestedesavoir.com/forums/sujet/8647/loption-filtre-disparait-sil-nexiste-pas-de-resultat/
*Envoyé depuis Zeste de Savoir*

**Comment by Theodicy** [comment]
À simple titre d'information, les images ne sont pas visibles _sur GitHub_...

**Comment by pierre-24** [comment]
Maintenant oui :)

**Comment by Theodicy** [comment]
Très bien, je jeterai un coup d'œil au code durant l'après-midi.

**Comment by Theodicy** [comment]
Bizarrement, je n'avais pas ce problème sur mon espace de développement ; seulement, dès que j'ai mis à jour le dépôt présent sur mon serveur, ce bug est apparu... Le bug est donc sûrement apparu il y a quelques semaines/mois suite à une PR ; ou plus généralement update.
