### ISSUE TITLE
Ajouter une note sur la ligne éditoriale lors de l'ajout d'un contenu

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#4348]
Comme discuté dans le forum Staff, afin de clarifier et rendre plus visible notre ligne éditoriale pour les auteurs, il serait bien de l’indiquer clairement en quelques lignes quand on crée un nouveau contenur, avec un lien vers [la page détaillée](https://zestedesavoir.com/articles/222/la-ligne-editoriale-officielle-de-zeste-de-savoir/).

![](https://zestedesavoir.com/media/galleries/2615/f86d61ac-f919-4bd4-bf8a-3596832d0ca3.png)

**Comment by gllmc** [comment]
Je m'en occupe. :)

**Comment by gustavi** [comment]
Corrigé dans #4351
