### ISSUE TITLE
Ajouter une note sur notre charte éthique dans la page de contact.

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#4349]
Nous recevons régulièrement des mails de demande de partenariat commerciaux. Dans la même lignée que  #4348, je pense qu'il serait bien de rajouter quelques lignes sur l'éthique de ZdS dans la page de contact. Par exemple :

*Vous pouvez joindre l'association par courriel via zestedesavoir@gmail.com. **À toute fin utile, sachez que nous refusons systématiquement toute forme de partenariat commercial.**
La personne responsable du groupe est : Kje.*

**Comment by gustavi** [comment]
Ça se fait en dehors du code du site selon moi, vu que cette partie est gérée via la BDD.

**Comment by gllmc** [comment]
Tout à fait : si le CA est d'accord, je pense qu'il faudrait qu'un admin s'en occupe et qu'on ferme cette issue.

**Comment by lypwig** [comment]
Ah ok, je ne savais pas je pensais que c'était en dur dans le code.

**Comment by lypwig** [comment]
[Résolu](https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=44#p151845)
