### ISSUE TITLE
Le curseur n'est pas en mode "lien" sur le bouton de déconnexion

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#4353]
Via le forum : https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=44#p151686

**Comment by lypwig** [comment]
J'ajoute l'image tant qu'à faire :

![](http://i.imgur.com/08ITFq6.png)

---

Et je pense que c'est lié, idem pour le menu hamburger en mode tablette :

![](http://i.imgur.com/RnhAV5A.png)
