### ISSUE TITLE
Possibilité d'enregistrer un message en brouillon 

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#4359]
> Il m’arrive d’écrire des messages sur le forum :
> 
> - que je voudrais reprendre plus tard avec un peu de recul ;
> - que je commence à un endroit et il me manque une info donc je voudrais le reprendre à un autre endroit ;
> - que je commence sur mon tel et je voudrais reprendre sur mon PC…
> 
> Bref, le fait de pouvoir enregistrer un message en brouillon afin de pouvoir le retrouver dans un menu type Mes brouillons en dessous de Mes billets serait super pratique, qu’en pensez-vous ? :)

cf. topic [ici](https://zestedesavoir.com/forums/sujet/8725/possibilite-denregistrer-un-message-en-brouillon/?page=1#p152078).

**Comment by Situphen** [comment]
Ça été implémenté, sauvegarde de l'éditeur dans le `localStorage`
