### ISSUE TITLE
Mauvais compte sur la home du forum

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#436]
Uniquement sur la home du forum je tombe sur un mauvais compte (là par exemple, je vois le forum comme Taguan, avec son avatar en haut, ses notifs...) par contre, quand je changes de page tout redevient normal.

**Comment by Alex-D** [comment]
C'est dû à la mise en cache, le revert a été effectué, normalement c'est poussé en prod d'après les retours récents des autres membres.
