### ISSUE TITLE
Le tag Résolu ne fonctionne pas correctement

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/zds-site#4360]
Lorsqu' on résous un sujet :

- le bandeau *Cette réponse a aidé l'auteur* n’apparaît pas ;
- l'icône associée n’apparaît pas sur le sujet dans la liste des sujets ;
- il n'est pas soumis au filtre de recherche *Sujets résolus* dans la liste des sujets.

En revanche il subsiste des sujets résolus tout a fait fonctionnels.

Donc le bug est peut-être apparu suite à la création de l'icône *Favori* ?

Pour tester :
- résoudre n'importe quel sujet du forum ;
- rechargez la page (le bandeau *Cette réponse a aidé l'auteur* n’apparaît pas) ;
- retournez sur la liste des sujets (pas d'icône) ;
- appliquez le filtre (le sujet n'y est pas).

**Comment by Anto59290** [comment]
Je n'arrive pas à reproduire le bug sur une instance locale de Zds. Il y a-t-il d'autres éléments particuliers qui permettrait un meilleur ciblage du bug (quel type d'utilisateur ? dans un forum privé ou public ? etc.)

**Comment by gllmc** [comment]
Je n'ai pas non plus réussi à reproduire, y compris sur ma branche `prod`.

**Comment by gustavi** [comment]
@roipoussiere tu peux donner des exemples de messages qui ne fonctionnent pas ?

**Comment by lypwig** [comment]
> @roipoussiere tu peux donner des exemples de messages qui ne fonctionnent pas ?

[Des goodies pour Zeste de Savoir ](https://zestedesavoir.com/forums/sujet/2839/des-goodies-pour-zeste-de-savoir/)

- le sujet est résolu (1er commentaire d'Eskimon);
- sur [la page du forum](https://zestedesavoir.com/forums/communaute/bar-smoothies/), l’icône *Résolu* n’apparaît pas sur ce sujet ;
- [après avoir appliqué le filtre](https://zestedesavoir.com/forums/communaute/bar-smoothies/?filter=solve), ce sujet n'est pas listé.

**Comment by Anto59290** [comment]
Sauf erreur de ma part le sujet n'est pas résolu. L'auteur a simplement cliqué sur cette réponse m'a aidé. Il y a deux fonctionnalité différentes : 
- Cette réponse m'a aidé --> mise en avant de la réponse
- Ce sujet est résolu --> Le topic apparait dans les filtre, l'icone est ajouté dans la liste

**Comment by lypwig** [comment]
Aaaah, je pensais que c'était la même chose, au temps pour moi.

Je trouve que c'est pas super clair, pourquoi ne pas fusionner ces 2 fonctionnalités ?

**Comment by gllmc** [comment]
Ça ne paraît pas être une bonne idée : un message peut très bien nous avoir aidé sans que l'on soit parvenu à résoudre complètement son problème.
Et il y a aussi tous les sujets autres que des questions (exemple : les stickers) où on peut mettre en avant des messages avec "Cette réponse m'a aidé" sans vouloir marquer le sujet comme résolu (ce qui n'a en général pas de sens avec ce type de cas).

**Comment by AmarOk1412** [comment]
+1 pour le WONTFIX, ça permet de mettre en avant une réponse de manière très visible.

On ferme ?
