### ISSUE TITLE
Supporter ElasticSearch 5.4+

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#4370]
Aujourd'hui cette version n'est pas supportée.

**Comment by pierre-24** [comment]
Y'a des changements bloquants ?

**Comment by gustavi** [comment]
Je ne sais pas du tout, j'ai juste mangé une 500.

**Comment by pierre-24** [comment]
Ah, c'était toi. Note, [vu l'erreur dont il s'agit](https://sentry.sandhose.fr/zeste-de-savoir/backend-l7/issues/941/) (aka "all shards failed"), je suis pas certain que ce soit du à la version. Est ce que Elasticsearch tournait convenablement ?

**Comment by gustavi** [comment]
Oui. Ça demande un peu de travail pour vérifier en bêta mais pas du tout une urgence.

**Comment by artragis** [comment]
je clos car doublon de #4420
