### ISSUE TITLE
Le version de l'API de Facebook utilisée ne sera plus disponible le 10 juillet

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#4376]
Potentiellement lié à https://github.com/zestedesavoir/zds-site/pull/4357

Plus d'informations soon.

**Comment by DevHugo** [comment]
On est le 6 juillet !  C'est bientôt, on peut faire quoi ?

**Comment by DevHugo** [comment]
@zestedesavoir/dtc

**Comment by artragis** [comment]
on n'a toujours pas de solution.

**Comment by artragis** [comment]
On peut toujours se connecter via fb.
