### ISSUE TITLE
Impossible de signaler mon propre message masqué

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#4379]
Ici : https://zestedesavoir.com/forums/sujet/481/your-desktop/?page=40#p153340

J'ai caché mon commentaire. L'interface me propose de "Signaler" celui-ci. Si je le fais et que je valide la modale, j'arrive sur une 403.

**Comment by AmarOk1412** [comment]
oooh joli, je confirme !

**Comment by artragis** [comment]
Comme je le disais sur IRC, je dirai qu'en soit ce n'est pas un bug. EN fait je serai plutôt d'avis de rendre indisponible le bouton de signalement de message masqué, sauf (peut-être) pour les modo.

De toute façon les alertes ne sont pas visibles sur un tel message.

**Comment by gllmc** [comment]
> De toute façon les alertes ne sont pas visibles sur un tel message

Je ne peux pas tester maintenant mais je suis quasiment persuadé que les alertes sont encore visibles après masquage. Sinon, ça devrait être corrigé histoire d'en garder la trace, non ?

**Comment by gllmc** [comment]
Merci @AmarOk1412 !
