### ISSUE TITLE
Site internet du profile inutile

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#438]
On peut le renseigner dans les paramètres mais il ne semble visible null part.

**Comment by Alex-D** [comment]
Faudrait le rajouter sur le profil a minima.

**Comment by SpaceFox** [comment]
Corrigé dans la PR #455 (c'est bizarre, y'a le numéro de l'issue dans le commentaire de la PR mais je ne le vois pas ici).

**Comment by Alex-D** [comment]
Non, le numéro de l'issue est dans le titre de la PR, pas dans le commentaire. Et à chaque fois firm1 fait pareil... et donc on a aucun lien qui est fait... pas très pratique.
