### ISSUE TITLE
API des membres : accès rapide pour savoir si un user existe

### ISSUE THREAD

**Issue by AmarOk1412** [zestedesavoir/zds-site#4382]
o/

Pour https://github.com/zestedesavoir/zmarkdown/issues/37, ce serait uber cool d'avoir la possibilité de savoir si un membre existe ou non.

En ce moment, il y a deux possibilités, mais les deux ne conviennent pas :

1. L'api membre avec search
2. Lien direct.

Le probleme :

https://zestedesavoir.com/api/membres/?search=a demande de parser les résultats jusqu'à trouver `<username>a</username>` => problème : **long**. (par exemple ici, cette ligne ne se trouve pas dans le json de base, trop de résultats)

https://zestedesavoir.com/membres/voir/a/. Problème : 
```
curl -I https://zestedesavoir.com/membres/voir/AmarOks
HTTP/2 301 
```
On obtient que des 301, que l'utilisateur existe ou non, du coup faut parser la page.

Idée :

Avoir https://zestedesavoir.com/api/membres/user/a, ou autre qui retourne 200 si l'utilisateur existe, 404 sinon.

**Comment by vhf** [comment]
A mon avis le moyen le plus efficace pour ça et peut-être le plus simple à mettre en place c'est de traiter les requêtes HEAD. DRF permet sauf erreur de faire des vues différentes pour les différents verbes HTTP.

Du coup on pourrait traiter le HEAD pour retourner 200 ou 404 si `… .exist()`
