### ISSUE TITLE
Migrer vers notre nouveau zmarkdown: PDF / LaTeX

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#4391]
Ce ticket pour la migration vers le nouveau zmarkdown, côté génération de PDF / LaTeX.

- [ ] Changer la méthode de compression pour que le fichier mimetype soit toujours en tête d'archive
- [ ] Fournir à l'équipe latex des exemple de la vraie vie
- [ ] Intégrer les css pour la coloration syntaxique (@sandhose) dans l'epub
- [ ] Améliorer nav pour que ça soit utile sur epub
- [x] Mettre à jour zmd (et donc la version sur yarn) pour que le travail réalisé par @Heziode sur le template latex soit importé
- [x] Débugger grâce au [validateur](http://validator.idpf.org) la génération des epubs

**Comment by artragis** [comment]
https://zestedesavoir.com/billets/2039/nouvelle-experience-on-continue-a-coder-en-live/
