### ISSUE TITLE
Pas de :hover sur les catégories de la sidebar des tribunes

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#4396]
Bonjour,

Si on suit la logique des autres éléments, il devrait avoir un effet :hover sur les titres.

![image](https://user-images.githubusercontent.com/18501150/27986728-1d406222-6403-11e7-8906-f2e139e3f545.png)

**Comment by A-312** [comment]
Avec la v25 les tutoriels c'est ok. Par conte les tribunes demande encore une modification.

**Comment by A-312** [comment]
Je prends.

**Comment by A-312** [comment]
Cet effet convient ?

![](http://i.imgur.com/vc2Z5Pq.png)

**Comment by artragis** [comment]
@A-312 est-ce ok sur la v25 pour toi?

**Comment by motet-a** [comment]
Le problème est toujours présent sur  la bêta @artragis.

Notez que c’est plus cohérent avec le reste au niveau des marges et du padding en rajoutant (à l’arrache, faites pas ça en prod’) ces propriétés CSS : 

```css
    padding-top: 0;
    margin-top: 20px;
    line-height: 30px;
    background: white;
```

![image](https://user-images.githubusercontent.com/15378830/29997134-dbf7e198-900b-11e7-96dd-5a74a7d83932.png)

**Comment by A-312** [comment]
Je n'ai pas la possibilité de faire le changement rapidement. J'avais fais une PR le jour même mais le rendu ne me convenait pas (si quelqu'un le fait avant, il n'y a pas de soucis).

**Comment by gllmc** [comment]
Personnellement, l'absence d'effet `:hover` ne me choque pas. Par ailleurs, ces éléments ne se comportent pas comme les autres : ce ne sont pas des liens, ils n'affichent qu'un menu déroulant.

**Comment by A-312** [comment]
~~Similaire à #4396 mais l'issue #4396 propose de rajouter un V.~~

Similaire à #932 mais l'issue #932 propose de rajouter un V.

**Comment by artragis** [comment]
tu as fait une erreur @A-312 on est déjà sur la 4396.

**Comment by A-312** [comment]
Effectivement #932

**Comment by artragis** [comment]
d'ailleurs, on remarquera que @shiningfm a fait une remarque très pertinente : 

> Je pensais m'en occuper, mais en quoi les solutions proposées arrangent les choses en matière d'accessibilité ? Concrètement, rajouter une image ou un effet au survol, je ne trouve pas ça pertinent pour une personne aveugle (ou autre).
>
> Il ne faudrait pas tout simplement spécifier des rôles WAI-ARIA ?

**Comment by A-312** [comment]
# Solution : 

Faire comme le sommaire des tutoriels : 

![image](https://user-images.githubusercontent.com/18501150/51996593-5aa5b300-24b5-11e9-9a72-f34663e6524e.png)

**Comment by Arnaud-D** [comment]
Avec l'arrivée de la bibliothèque, ce ticket semble obsolète. On ferme celui-là et on en refait un pour les billets ?

**Comment by A-312** [comment]
@Arnaud-D Regarde dans la liste des tribunes 😜

**Comment by A-312** [comment]
Ca marche aussi pour les billets non ? 🤔

**Comment by Situphen** [comment]
Je ferme ici car j'ai décidé de partir sur un nouveau ticket pour plus de lisibilité. #6176
