### ISSUE TITLE
Les certificats de production ont expiré

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#4399]
Bonjour,

Les certificats de productions ont expiré. Impossible de se connecter au site.

Liés à https://github.com/zestedesavoir/zds-site/issues/4191 ?

**Comment by SpaceFox** [comment]
À ce propos, est-ce que le HSTS a pour ZdS une autre utilité que nous péter
les noix quand le renouvellement du certificat a planté ?

Le 11 juil. 2017 11:43 AM, "Hugo Courtecuisse" <notifications@github.com> a
écrit :

**Comment by pierre-24** [comment]
le cron `cerbot` est-il mort ?

**Comment by vhf** [comment]
Pas mon job mais ok, j'ai fait.

**Comment by DevHugo** [comment]
Ouai, excuse, mais je ne savais pas qui mettre. Comme tu l'as fait la dernière fois. C'est qui les dtc maintenant ?

**Comment by gllmc** [comment]
@DevHugo : c'est artragis et gustavi maintenant.
