### ISSUE TITLE
Comment permettre le renouvellement des certificats sans casser la prod 

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#4400]
Bonjour,

ça fait deux fois d'affilé que le renouvellement des certifcats ce passe mal, comment peut-on améliorer notre processus actuel pour que ça marche ?

Cf: #4191 et #4399

Merci d'avance

**Comment by gllmc** [comment]
Il y a @vhf qui a rajouté un cron, ça devrait être bon donc.

**Comment by vhf** [comment]
Ouais mais non. C'est une solution crade. J'ai ajouté un cron qui de temps à autres reload nginx, parce que le hook de certbook censé le faire ne fonctionne pas.

La réponse à la question posée dans le titre est : en ayant un sysadmin pour s'occuper des serveurs. On en a pas.
