### ISSUE TITLE
[beta][v24] La recherche ne prend pas en compte les billets

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4412]
La recherche actuelle ne prend pas en compte les billets.

Si je cherche le terme ["lymphome"](https://beta.zestedesavoir.com/rechercher/?q=lymphome) , je n'ai qu'un seul résultat qui est celui du forum.

Et pourtant je devrais pouvoir au moins avoir [ces trois résultats](https://beta.zestedesavoir.com/billets/?tag=lymphome)

**Comment by pierre-24** [comment]
Régression, puisque [ici, ça fonctionne](https://zestedesavoir.com/rechercher/?q=lymphome). Ou bien la bêta n'as pas été réindexée :)

**Comment by artragis** [comment]
mmmh il n'est pas improbable que j'ai juste mal redémarré l'indexation, je regarde plus tard.

**Comment by artragis** [comment]
fixed
