### ISSUE TITLE
Erreur 500 lors de la publication d'un billet

### ISSUE THREAD

**Issue by rezemika** [zestedesavoir/zds-site#4414]
J'ai rédigé il y a quelques temps un article expliquant le principe des logiciels libres. Toutefois, manquant d'arguments pour une section "Critique", j'ai décidé de le convertir en billet. J'ai donc créé un billet, y ai importé les images utilisées dans l'article et ai copié le texte, avec juste quelques modifications mineures. Toutefois, au moment de la publication, j'obtiens une erreur 500.

Voici l'article concerné : [https://zestedesavoir.com/contenus/2040/quest-ce-quun-logiciel-libre/](https://zestedesavoir.com/contenus/2040/quest-ce-quun-logiciel-libre/)
Et voici le billet concerné : [https://zestedesavoir.com/contenus/2064/quest-ce-quun-logiciel-libre-1/](https://zestedesavoir.com/contenus/2064/quest-ce-quun-logiciel-libre-1/)

**Comment by pierre-24** [comment]
... Avec une erreur des plus étonnantes, soit dit en passant: https://sentry.sandhose.fr/zeste-de-savoir/backend-l7/issues/984/ : 

```
UnicodeError: URL u'https://commons.wikimedia.org/wiki/File:Richard_Stallman_-_F\xeate_de_l%27Humanit\xe9_2014_-_010.jpg' contains non-ASCII characters
```

Je te conseille donc, dans l'absolu, d'uploader cette image sur ZdS. Ça te permettra de débloquer la situation pour toi. Maintenant, ça reste un bug étonnant.

**Comment by rezemika** [comment]
> Je te conseille donc, dans l'absolu, d'uploader cette image sur ZdS. Ça te permettra de débloquer la situation pour toi. Maintenant, ça reste un bug étonnant.

C'est d'autant plus étonnant que c'est déjà fait. Voilà le markdown du billet à cet endroit.

```
Cet étudiant, c'est **Richard Matthew Stallman** (parfois appelé *rms*).

![Portrait de Richard Stallman en 2014. [Source](https://commons.wikimedia.org/wiki/File:Richard_Stallman_-_Fête_de_l%27Humanité_2014_-_010.jpg).](/media/galleries/4410/c1016bf1-a1de-48a1-9ef1-144308e8725d.jpg)

Quelques années plus tard...
```

Ça viendrait de l'URL du coup ?

**Comment by pierre-24** [comment]
Oh, c'est encore plus bizarre, ça. On dirait effectivement que ça provient du "ê" de l'URL. Sauf que c'est pas sencé le faire à cet endroit là o_O

**Comment by artragis** [comment]
il y a probablement un double pb : 

- le markdown initial est mauvais et fait planter le système
- à un moment donné l'utf-8 n'est pas géré.

Par contre là tout de suite, je suis pas sûr que ça vienne de la v24

**Comment by gllmc** [comment]
@artragis : le problème a eu lieu en prod, donc de toute façon, il n'y a rien de spécifique à la v24.

**Comment by rezemika** [comment]
Je viens de modifier l'URL et de publier le billet, mais j'ai téléchargé une copie de l'archive avant. Si ça peut vous être utile pour faire des tests, je la mets en pièce jointe. ;-)

**Comment by artragis** [comment]
rezemika, peux-tu m'envoyer l'archive par quelque media que ce fût? (mon pseudo @ gmail.com devrait fonctionner)

**Comment by rezemika** [comment]
@artragis : C'est fait, désolé pour le délai.

Si quelqu'un d'autre en a besoin, je la mets ici en pièce-jointe.

[quest-ce-quun-logiciel-libre-1.zip](https://github.com/zestedesavoir/zds-site/files/1220059/quest-ce-quun-logiciel-libre-1.zip)

**Comment by artragis** [comment]
PR en cours.
