### ISSUE TITLE
Erreur 500 indexée sur Google

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4415]
Ici : https://zestedesavoir.com/api/api-docs/api/membres

Notez que ça a été indexé par Google :

![image](https://user-images.githubusercontent.com/15378830/28756694-b9906402-7573-11e7-846a-4be0973fc246.png)

...parce que le serveur retourne étrangement le code 200 :

![image](https://user-images.githubusercontent.com/15378830/28756697-d565b3e4-7573-11e7-82d4-c2ae1d5dfa25.png)

**Comment by artragis** [comment]
Ok, merci, il y a ici deux bugs en un ticket : 

- l'indexation (il faudra l'ajouter en v24)
- l'erreur 500.

Pour la seconde, la v24 corrige déjà. Merci de la remontée.

**Comment by motet-a** [comment]
@artragis Du coup je renomme ça en « Erreur 500 indexée sur Google » ?

**Comment by artragis** [comment]
Oui, merci :)

**Comment by vhf** [comment]
Déployé.
