### ISSUE TITLE
Gulpfile, sprites et dépendances SCSS

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4416]
Bonjour,

En ce moment, je m’amuse un peu avec Docker, ça marche plutôt bien à part une chose assez embêtante.

On peut faire tourner un peu n’importe quoi avec Docker pour développer en local avec des volumes en lecture seule. Ils permettent à un conteneur de lire des dossier tels quels sur l’hôte sans pouvoir les modifier. Tant qu’il y a une séparation claire entre les dossiers des sources et les dossiers des choses compilées, tout ce passe bien.

Le seule problème ici, c’est le dossier `assets/`, qui contient des sources, des dépendances SCSS et des sprites générées par le Gulpfile.

Concernant les dépendances SCSS (uniquement `normalize.css`), [ça me semble facile](https://github.com/sass/node-sass#importer--v200---experimental) d’aller les chercher directement depuis `node_modules/`.

Concernant les sprites, il me semble possible de lancer spritesmith et imagemin dans le dossier `dist/images/` (ou alors avec `assets/images/` comme source et `dist/images/` comme destination).

Si vous êtes d’accord là-dessus, je m’en occuppe.

Merci :-)

**Comment by artragis** [comment]
ping @sandhose (mais perso ça me dérange pas, etj 'aime docker)

**Comment by motet-a** [comment]
Je m’en occuppe.

**Comment by pierre-24** [comment]
Voilà qui va te permettre d'avancer :)

**Comment by motet-a** [comment]
Merci !
