### ISSUE TITLE
La barre de recherche dans le menu se comporte étrangement sur mobile

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4418]
Il y a un `width: 14%;` un peu sale sur le bouton `+` :

![image](https://user-images.githubusercontent.com/15378830/28776555-58f726d8-75f7-11e7-9aeb-0cafc887e5e4.png)

![image](https://user-images.githubusercontent.com/15378830/28776561-5f04c2ce-75f7-11e7-8f5a-422fa195b0a7.png)

![image](https://user-images.githubusercontent.com/15378830/28776568-67faca5e-75f7-11e7-9f5c-23c8fffd3d26.png)

**Comment by AmarOk1412** [comment]
Je pense que le comportement voulu pour le coup c'est de laisser le boutton de la même largeur à chaque fois. Pas faire ce truc assez moche :)

**Comment by motet-a** [comment]
Je pense aussi.
