### ISSUE TITLE
Notification persistante de MP si suppr par l'autre participant

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#442]
Scénario : 
- Membre A envoie un MP à Membre B
- A supprime le MP avant que B n'ait eu le temps de le lire
- B se retrouve avec une notification impossible à supprimer car MP inaccessible (404).

Il n'est pas non plus possible de voir le MP supprimé par B (ça c'est peut-être un choix ?). Il n'est pas possible de supprimer le MP car le lien de suppression ne se trouve que sur la page du MP, inaccessible donc.

**Comment by firm1** [comment]
Ce n'était pas l'explication du bug, mais quoiqu'il en soit, il a été fixé
