### ISSUE TITLE
Problème d’affichage de tableaux en format mobile

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#4427]
[Vu sur le forum](https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=47#p158528):

> Quand la fenêtre est assez grande, pas de soucis, tout s'affiche bien.
> 
> ![Historique des éditions du message.](https://zestedesavoir.com/media/galleries/4138/fbd844da-3843-4536-bfd1-65a982ffbaa1.png)
> 
> Mais sur une fenêtre à largeur réduite, le tableau est tronqué, et les boutons pour voir / restaurer deviennent ainsi inaccessibles.
> 
> ![Tableau tronqué.](https://zestedesavoir.com/media/galleries/4138/1753149d-92eb-4f19-88d2-1f9a09a4955c.png)
> 
> Ce n'est pas de la plus haute importance.
> Quoique, je ne sais pas ce que ça peut rendre sur mobile.

**Comment by pierre-24** [comment]
Et, d'après @vhf, pareil sur la gestion des alertes:

![screenshot_20170802-110833](https://user-images.githubusercontent.com/7889675/28866705-09e62854-7774-11e7-9e5c-ca0c4b2c0444.png)

**Comment by motet-a** [comment]
Ça semble voulu puisque [ici](https://github.com/zestedesavoir/zds-site/blob/dev/templates/pages/comment_edits_history.html#L36) et [là](https://github.com/zestedesavoir/zds-site/blob/dev/templates/pages/comment_edits_history.html#L43) il y a un `class="wide"`.

**Comment by pierre-24** [comment]
C'est surtout que le dévellopeur a testé sur son pc, à mon avis ^^

**Comment by motet-a** [comment]
@pierre-24 C’est à dire ? Le `class="wide"` sur la dernière colonne veut dire « n’afficher que sur écran large » : 

https://github.com/zestedesavoir/zds-site/blob/dev/assets/scss/base/_helpers.scss#L72

Par « Ça semble voulu », je veut dire que ce n’est pas un bug, mais que le truc est conçu comme ça (mais je ne dis pas que c’est très bien conçu, un tableau n’est pas forcément le bon choix ici).

**Comment by pierre-24** [comment]
En effet.

Mais je pense que les gens aimeraient pouvoir y accéder aussi en format mobile :)

**Comment by motet-a** [comment]
Je pense aussi :smiley:

**Comment by artragis** [comment]
j'ai tendance à penser que ça n'est pas propre à la béta tout ça.

**Comment by vhf** [comment]
Ça ne l'est pas. Tu peux enlever la milestone v24. Comme je le disais, c'est pareil sur les alertes sur la prod.

**Comment by pierre-24** [comment]
Voilà qui est fait.

**Comment by rezemika** [comment]
Je m'en occupe. :-)

Quelles sont les pages affectées ? Seulement celle-ci ou toutes celles qui ont des tableaux avec des boutons ?

Edit : Ce n'est pas le même problème, mais je trouves que les boutons sont très "serrés" sur les petits écrans. Il faudrait peut-être ajouter du padding entre-eux ?

![](https://user-images.githubusercontent.com/1690660/28946380-d4b1fb62-78aa-11e7-986e-a678cbe2ccf9.png)

**Comment by motet-a** [comment]
@rezemika [Ici](https://github.com/zestedesavoir/zds-site/blob/dev/templates/pages/comment_edits_history.html#L36) et [là](https://github.com/zestedesavoir/zds-site/blob/dev/templates/pages/comment_edits_history.html#L43) il y a un `class="wide"`.

Mais pour corriger le problème correctement, je pense qu’il faut mieux remplacer tout le tableau par quelque chose de responsive.

Concernant les boutons, je pense que tu peux ouvrir une autre issue.

**Comment by rezemika** [comment]
Oui, ceux-là, je les avais bien repérés, mais je parlais des tableaux qu'on peut voir sur d'autres pages (surtout celles des validateurs il me semble).

Ok pour l'issue, je ferais ça dès demain.

**Comment by artragis** [comment]
@vhf @rezemika ça semble fixé, non?

**Comment by gllmc** [comment]
Je confirme que c'est fixé par #4446. :)
