### ISSUE TITLE
[Membre] L'email de bienvenue est envoyé en double

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#443]
Le message de bienvenue suite à l'inscription serait envoyé en double selon Javier

Sujet : http://zestedesavoir.com/forums/sujet/133/bug-message-daccueil-en-double?page=1#p813

**Comment by SpaceFox** [comment]
Je ne reproduis pas. Quelqu'un reproduit ou on considère que c'est une fausse manip de Javier ?

**Comment by Eskimon** [comment]
Idem, pas de reproduction chez moi... (sauf si le second mail met des heures à arriver, dans ce cas là je modifierais mon commentaire)

**Comment by firm1** [comment]
Personne n'a ce souci, j'en conclu que ce n'est pas/plus le cas.

Je ferme
