### ISSUE TITLE
Erreur à la publication d'un tutoriel

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#4434]
Voir https://sentry.sandhose.fr/zeste-de-savoir/backend-l7/issues/987/

```
IOError: /opt/zds/data/contents-public/le-langage-c-1
(6 additional frame(s) were not displayed)
...
  File "zds/member/decorator.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)
  File "zds/tutorialv2/mixins.py", line 253, in get
    self.public_content_object = self.get_public_object()
  File "zds/tutorialv2/mixins.py", line 142, in get_public_object
    object.load_public_version()
  File "zds/tutorialv2/models/models_database.py", line 645, in load_public_version
    self.versioned_model = self.content.load_version(sha=self.sha_public, public=self)
  File "zds/tutorialv2/models/models_database.py", line 345, in load_version
    raise IOError(path)

IOError: /opt/zds/data/contents-public/le-langage-c-1
```

**Comment by DevHugo** [comment]
ça serait peut-être intéressant de voir sur la prod, quel nom a le dossier.

**Comment by pierre-24** [comment]
Un quickfix serait de le marquer comme jamais publié auparavant dans la BDD. Mais n'empêche, je me demande ce qui a causé ça.

**Comment by DevHugo** [comment]
ça aurait pas des conséquences sur la redirection ?

**Comment by pierre-24** [comment]
Si, effectivement :/

**Comment by DevHugo** [comment]
Sinon, on peut se dire que c'est un moindre mal, pas de contenu est bien pire que pas de redirection.

**Comment by DevHugo** [comment]
Il a toujous été là le -1 à la fin ?

**Comment by pierre-24** [comment]
Ce tutoriel a déjà un long historique de *fails* multiples et variés. Je serais pas étonné que ce passé sois une des causes du plantage actuel.

**Comment by DevHugo** [comment]
Je pense que le plus simple c'est qu'un admin regarde l'historique GIT du tutoriel et le nom des différents fichiers avec les enregistrements dans la bases de données.

**Comment by pierre-24** [comment]
Bon, qui a accès à la prod, encore ? @artragis et @gustavi ?

**Comment by pierre-24** [comment]
Donc l'historique git n'as rien. Du coup, seconde solution (j'ai testé en local la faisabilité de la chose).

Pour @zestedesavoir/infrastructure, quand quelqu'un a 5 minutes:  dans la BDD, le publishablecontent au pk=755 (probablement situé à l'adresse https://zestedesavoir.com/admin/tutorialv2/publishablecontent/755/change/), ayant le slug "le-langage-c-1. Videz le champ "Sha1 de la version publique :" et "Version publiée :" (dans le bas). Ça enlèvera un le lien avec une éventuelle version publique qui pose problème (m'enfin pas trop, puisque le tuto a disparu des radars). Et ensuite il "suffira" de republier.
