### ISSUE TITLE
[MP] Texte indiquant l'édition illogique

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#444]
Le texte d'édition d'un MP est "Edité maintenant par " et il n'y a pas de pseudo après : c'est donc illogique.

Je propose de retirer "par" pour obtenir "Edité maintenant" car seul l'auteur du message peut l'éditer de toute façon.

Sujet : http://zestedesavoir.com/forums/sujet/134/bug-edit-dun-mp-manque-dun-placeholder?page=1#p815

**Comment by cgabard** [comment]
Je propose surtout de virer toute cette mention. L'edition n'est possible que si les autres membres du MP ne l'ont pas lu DONC ils n'en ont rien a carrer de savoir qu'il l'a rédigé ainsi directement ou suite a un edit. L'info n'a aucune pertinence.

**Comment by Alex-D** [comment]
C'est pas faux. +1

Après, dans ma version de l'intégration, tous les rendus de messages de TOUT le site sont factorisés en une seule et même template... donc la mention d'édition sera a priori affichée partout.

Je verrais, je pourrais faire un booléen pour afficher ou non cette mention.

**Comment by cgabard** [comment]
Du coup tu arrive a un autre problème : sur le forum cela peut être un staff qui édite et du coup la mention a du sens.

**Comment by Alex-D** [comment]
D'où l'option appliquée selon l'endroit où le template est utilisé :)

**Comment by firm1** [comment]
> Après, dans ma version de l'intégration, tous les rendus de messages de TOUT le site sont factorisés en une seule et même template

OMG ça va être bordelique avec les centaines de if a gérer en fonction des MP, forums, articles, tutos, etc.

**Comment by Alex-D** [comment]
Je gère le front, je le fais à ma sauce. J'ai dit factorisé, pas 1000 if partout.

Ca serait cool que chacun s'occupe de ce qu'il fait pour le faire bien. En l’occurrence, je ne te dis pas que ta gestion des formulaire est pourrie, pourtant c'est complètement bancale, mais je me concentre sur le front donc je me tais et j'interviendrais quand ça sera stabilisé. A prendre sans aucune méchanceté ni attaque, c'est un constat et un exemple qui fait suite à un certain ras-le-bol qu'on me dise très régulièrement "OMG tu fais du code trop compliqué ça va être le bordel".

**Comment by geoffreyc** [comment]
> A prendre sans aucune méchanceté ni attaque

Honnêtement ça doit être dur de le prendre autrement ! Faut vraiment que tu
arêtes de te braquer a chaque vois que quelqu'un dit quelque chose qui te
plaît pas, parce que ca plombe drôlement l’ambiance. J'ai personellement
vue aucune méchanceté ou critique dans ce que @firm1 a dit, simplement un
peut d’inquiétude sur la complexité du template en réunissant tout. Si tu
dis que c'est bon et que ce sera lisible, soit, on en reste la :)

2014-05-07 14:27 GMT+01:00 DEMODE Alexandre notifications@github.com:

**Comment by SpaceFox** [comment]
> En l’occurrence, je ne te dis pas que ta gestion des formulaire est
> pourrie, pourtant c'est complètement bancal

En l'occurrence, s'il y a quelque chose de "complètement bancal", c'est
_maintenant_ qu'il faut le signaler, parce que quand ce sera mis en prod ce
sera beaucoup plus chiant à corriger.

**Comment by Alex-D** [comment]
Tant qu'on dérive allons-y : chaque fois que je parle de factoriser les templates, j'ai droit à ce même type de remarque, c'est agaçant. Je sais ce que je fais, et je ne le fais pas pour le fun ou je ne sais quoi, je le fais parce que ce sera plus simple à maintenir, par ce que ça sera plus court et centralisé. Je peux sembler me braquer, mais il n'est pas plaisant d'avoir certaines remarques à répétition quand on sait ce qu'on fait. Si quelqu'un a envie de développer le front, qu'il me le dise et on s'organisera, à la base je pensais juste faire HTML/(S)CSS et que d'autrent intègrent ça. Mais a priori, personne d'impliqué dans le projet ne sait manipuler le moteur de template convenablement ce qui m'a amené à passer également sur la partie intégration SWIG (le moteur de template de Django si je ne dis pas de connerie).

Pour exemple : actuellement selon l'intégration temporaire il y a un template par module pour gérer les messages des tuto, des articles, des mp et du forum (et peut-être d'autres endroits encore). Moi j'ai pris le pari de ne faire qu'un fichier pour tout ça, ça permet d'avoir un seul fichier à changer au besoin et qui se répercute partout où la mise en forme/page est la même.

C'est ça que j'appelle de la factorisation. Pareil pour la pagination. 

---

Le soucis actuel des formulaire est que sa structure est définie par des helpers qui font appel au pack de template de base, à celui de boostrap, et qu'il y a peut-être des résidus de Foundation (là c'est une hypothèse). Aussi, certaines templates (notamment celle du formulaire d'édition du message) de la branche beta ont un formulaire en HTML ce qui est contraire au helper, du coup il y a une incohérence totale à ce niveau.

J'ai mon idée pour nettoyer ça : créer un TEMPLATE_PACK dédié à ZdS. Mais comme ça nécessite un peu de Python et autre, je gardais ça sous le coude pour un peu plus tard.

---

En somme : je passe, tout comme firm1 que je respecte malgré ce que peuvent laisser penser mes message, tout mon temps libre sur ZdS. Etant sur une branche séparée, on ne voit pas que j'avance. Aussi une refacto ne se voit pas, donc peut-être qu'on peut penser que je n'avance pas, mais je fais ce que je peux.

C'est difficile pour moi en sous-marin et d'avoir des remarques qui laissent douter de ses choix alors qu'absolument personne ne suit ce que je fais (à part un ou deux en privé et de loin, mais ça fait quand même plaisir).

Bref, en somme, je factorise, je ne suis pas fou : ça sera utilisable, merci d'arrêter de remettre en cause mes choix à chaque fois que j'en énonce un, ça me ferait bien plaisir. Par ailleurs, comme demandé tout est sur Github, ceux qui veulent voir peuvent voir, il suffit de changer de branche.

Pour finir le template en question est là : https://github.com/Taluu/ZesteDeSavoir/blob/integration/templates/misc/message.part.html

J'en suis personnellement satisfait jusqu'ici, elle fait son boulot et n'est pas plus complexe qu'un autre...

**Comment by firm1** [comment]
> Moi j'ai pris le pari de ne faire qu'un fichier pour tout ça

Justement, ma remarque était surtout là parce que j'imagine très clairement comment sera ton fichier. C'était de la simple prévention, pour t'éviter de partir sur une mauvaise voie. Mais si tu me dis que tu arriveras sans que ce ne soit bordelique, je te crois sur parole, et j'attend le résultat pour espérer que j'avais tord.

> En l’occurrence, je ne te dis pas que ta gestion des formulaire est pourrie

Pour moi on développe ce projet tous ensemble, rien n'est particulièrement à Moi dans ce projet. Je ne suis qu'un contributeur. J'ai bien des réserves sur certaines parties du codes, mais je ne considère juste pas ça comme prioritaire.

> je passe, tout comme firm1 [...], tout mon temps libre sur ZdS

Non, moi personnellement, j'ai autre chose à foutre en l'occurence.

> ça sera utilisable, merci d'arrêter de remettre en cause mes choix à chaque fois que j'en énonce un, ça me ferait bien plaisir

Il y'a une différence entre remettre en cause des choix et prévénir quelqu'un.

> J'en suis personnellement satisfait jusqu'ici, elle fait son boulot et n'est pas plus complexe qu'un autre...

**jusqu'ici** -> tu n'as pas encore tout vu :-)

**Comment by Alex-D** [comment]
Désolé d'avoir mal interprété cette prévention.

Et du coup, qu'est-ce que je n'ai pas vu ? Car chez moi ça tourne partout sur le site et tout fonctionne. Si tu me dis qu'il manque des choses je suis preneur, mais a priori j'ai tout mis (ou presque si on prends en compte l'idée de cette issue).

**Comment by firm1** [comment]
> Et du coup, qu'est-ce que je n'ai pas vu ? Car chez moi ça tourne partout sur le site et tout fonctionne.

je ne l'ai pas lu en détail, mais en faisant un Ctrl+F sur "{% if", on en est déjà à 22, alors qu'on ne gère pas encore le cas "si je suis dans un MP et que mon message est déjà lu, alors je ne peux pas editer", "si je suis dans un MP, masquer le message n'a pas de sens".

**Comment by SpaceFox** [comment]
Désolé, je continue le HS mais je ne peux pas ne pas réagir à ça.

> à la base je pensais juste faire HTML/(S)CSS et que d'autrent intègrent ça. Mais a priori, personne d'impliqué dans le projet ne sait manipuler le moteur de template convenablement ce qui m'a amené à passer également sur la partie intégration SWIG (le moteur de template de Django si je ne dis pas de connerie).

Je suis 100% d'accord pour dire que je fais très probablement de la merde
avec le moteur de templates, puisque c'est mon premier projet en Django.

Par contre, ce que je ne comprends pas, c'est :
1. Pourquoi je ne découvre ça que maintenant, et
2. Pourquoi n'avoir rien fait pour _nous_ améliorer, "nous" étant les
personnes qui ont fait de la merde avec le moteur de template.

Alex, tu découvres qu'on fait de la merde, OK, j'ai pas de problème avec
ça. Mais tu prends sur toi de repasser sur toute l'intégration. Ce qui est
noble et que je peut comprendre, mais qui est contre-productif : tu es déjà
très chargé en travail sans avoir à en rajouter. De plus, en procédant de
cette manière, tu ne nous permet pas (nous = toujours les mêmes) de
progresser. Autant dire qu'on va recommencer les mêmes conneries à la
moindre PR.
Alors que tu aurais pu :
- Nous indiquer ce qui merde
- Fournir les ressources pertinentes sur SWIG pour que nous puissions nous
  corriger
- Nous fournir directement certaines explications si tu n'as pas de
  ressources à nous proposer.

L'un dans l'autre je pense que ça ne t'aurait pas pris beaucoup plus de
temps que refaire tout ce que tu as refait ; et surtout c'aurait été un
excellent investissement sur l'avenir, puisque ça nous aurait permis, sinon
de faire le travail que tu as fait sur SWIG, au moins de ne pas refaire de
conneries dans l'avenir.

Le plus triste, c'est que sauf erreur de ma part, nous sommes en train de
développer un site de partage de connaissances.

Ce n'est vraiment pas à prendre comme méchanceté ni attaque, mais vraiment
sur ce coup là je ne comprends pas ta réaction.

**Comment by Alex-D** [comment]
À chaque fois j'ai eu comme réponse "c'est temporaire", donc j'imaginais que c'était voulu pour faire vite. Maintenant je ne peux pas deviner que certains ne savent pas l'utiliser.

Du coup, je vais finir ce que j'ai commencé, ça fera une belle base, et je vais tenter de m'orienter vers de la pédagogie envers les contributeurs comme tu le propose. Personnellement ça ne me déplairait pas, si on ne me dis pas "oui c'est temporaire" ou "je sais" de peur d'avoir honte (honte de quoi d'ailleurs ? je n'en sais rien en fait) ou je ne sais quoi.

En clair, je suis d'accord avec ce que tu dis. Seulement, à mes yeux il fallait une base saine pour que chacun puisse ajouter sa pierre à l'édifice.

Aussi, il me fallait avoir une certaine maitrise de l'intégration pour organiser ma répartition des divers blocs de design, ce qui n'était pas évident en partant de quelque chose d'un peu bancal.

Je retiens donc que je commenterais aussi pédagogiquement que possible les futures contributions liées aux templates et à l'intégration en général.

**Comment by SpaceFox** [comment]
> À chaque fois j'ai eu comme réponse "c'est temporaire", donc j'imaginais
> que c'était voulu pour faire vite. Maintenant je ne peux pas deviner que
> certains ne savent pas l'utiliser.

Je sais pas, personnellement je dissocie clairement "vite fait donc en
faisant des trucs pas très propres" et "mal fait parce que l'utilisateur ne
sait pas.

> Personnellement ça ne me déplairait pas, si on ne me dis pas "oui c'est
> temporaire" ou "je sais" de peur d'avoir honte (honte de quoi d'ailleurs ?
> je n'en sais rien en fait) ou je ne sais quoi.

Je ne crois pas que quiconque ait jamais dit ça dans l'équipe en fait. Au
contraire, il me semble ne pas avoir été le seul à regretter l'absence d'un
développeur Django expérimenté.

Tu parles aussi de partir sur des bases saines.
Pourquoi pas, mais en attendant, aurais-tu des billes sur les grosses
erreurs à éviter ou mieux, de bonnes ressources sur l'utilisation de ce
moteur de template ?

**Comment by firm1** [comment]
> Le texte d'édition d'un MP est "Edité maintenant par " et il n'y a pas de pseudo après : c'est donc illogique.

Juste pour préciser que j'en ai profité pour virer la mention "Edité blabla" dans la version temporaire, je ne sais plus dans quel commit
