### ISSUE TITLE
La taille de la police varie en fonction de la taille de la fenêtre

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4441]
Je pense que la taille de police devrait être la même quelle que soit la taille de l’écran et le niveau de zoom et qu’il ne devrait pas y avoir de _media queries_ qui la modifie comme ici : 

https://github.com/zestedesavoir/zds-site/blob/dev/assets/scss/layout/_content.scss#L415-L429

**Comment by A-312** [comment]
Toujours un problème ? Récemment on avait corrigé la taille sur Chrome

**Comment by Situphen** [comment]
> Je pense que la taille de police devrait être la même quelle que soit la taille de l’écran et le niveau de zoom

Je ne vois pas pourquoi on devrait se mettre cette contrainte. Pour moi, on doit adapter la taille de la police pour que la lecture soit la meilleure possible. Peut importe si les tailles sont les mêmes ou si elles sont différentes entre sur ordinateur et sur mobile. Les problèmes de taille doivent être réglés au cas par cas à mon avis.
