### ISSUE TITLE
[Galerie] Ajout du code pour embarque une image

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#445]
Il a été demandé l'ajout d'un champ présentant le code markdown associé à chaque image envoyée dans la galerie.

Ainsi on pourrait copier/coller le code directement dans les messages et avoir l'alternative sans la réécrire à chaque fois.

Pour le coup, ça relève exclusivement du front je pense, pas utile de le mettre dans la BETA courante.

Sujet : http://zestedesavoir.com/forums/sujet/136/suggestion-ajout-du-code-pour-embarque-une-image#p817

**Comment by ShigeruM** [comment]
Ça n'a rien à voir avec l'issue mais est-ce pertinent de mettre un lien
vers le forum de la bêta sachant que la base sera réinitialisée ?

**Comment by Alex-D** [comment]
Ca permet, au moins pendant la beta de pouvoir aller voir la conversation.
A priori, ça sera fait avant la fin de la beta ou peu après, du coup ça n'est pas vraiment un problème je pense.
