### ISSUE TITLE
Espace blanc sous le footer sur les petits écrans

### ISSUE THREAD

**Issue by rezemika** [zestedesavoir/zds-site#4453]
Sur les écrans de moins de 960px de large, il y a un espace blanc sous le footer quand la page est plus petite que l'écran. Il serait plus naturel de le mettre en bas de la page, comme sur les écrans plus grands.

![Une capture d'écran avec un écran simulé de 915x638px](https://user-images.githubusercontent.com/1690660/28995155-5b032c90-79e1-11e7-83a0-d990ce85e52b.png)

**Comment by pierre-24** [comment]
Notez que c'est aussi présent sur la page de recherche, par exemple

![screenshot from 2017-08-05 13 27 09](https://user-images.githubusercontent.com/7889675/28995169-d9371f04-79e1-11e7-8dcf-306270f8cfa9.png)

(et de manière générale sur toutes les pages un peu courtes et sans barre de gauche)

**Comment by motet-a** [comment]
La bonne solution est de reprendre le layout avec un `flex-grow: 1;` au centre pour pousser la barre du bas.

**Comment by motet-a** [comment]
La bonne solution est de reprendre le layout avec un `flex-grow: 1;` au centre pour pousser le footer en bas.

**Comment by motet-a** [comment]
Allez, je m’en occuppe.

**Comment by pierre-24** [comment]
Merci @motet-a =)
