### ISSUE TITLE
RTD ne builde plus notre documentation

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#4456]
Depuis début juillet,

![screenshot from 2017-08-05 16 39 56](https://user-images.githubusercontent.com/7889675/28996255-bb63fa54-79fc-11e7-9272-108bd4e4c4f2.png)

Voir, à priori, https://github.com/rtfd/readthedocs.org/issues/3006

**Comment by pierre-24** [comment]
@firm1 (parce que toi je pense que tu l'as) et/ou @zestedesavoir/infrastructure ... Y'a une question à laquelle je sais pas répondre sur rtfd/readthedocs.org#3006, y'aurais moyen de me donner temporairement l'accès au compte de zds sur rdt ou d'y répondre à ma place ?

**Comment by vhf** [comment]
Je ne sais pas comment s'y connecter, je n'ai pas d'identifiants.

**Comment by pierre-24** [comment]
M'en doutait un peu, et je suis quasi sur que @firm1 les as.

**Comment by firm1** [comment]
Normalement @vhf a réussi a récupérer les accès à Readthedocs.

**Comment by pierre-24** [comment]
Bon, j'ai essayé dans tout les sens (créer un nouveau projet, build avec ou sans virtualenv, tripoter des options du coté de RTD, tripoter des options du coté de notre `setup.py`), RTD ne VEUT PAS compiler notre documentation. Rien n'y fait.

**Comment by motet-a** [comment]
Du coup, on laisse tomber RTD ? C’est pas forcément la peine de perdre plus de temps avec.

**Comment by AmarOk1412** [comment]
Bah maintenant, les pages n'existent plus.

La question c'est on la laisse juste sur le github du coup ?
~~On remet en place le wiki ?~~

On fait la proposition de @vhf :
> Pourquoi pas docs.zestedesavoir.com hébergé par github pages ?

ça va permettre de régler https://github.com/zestedesavoir/zds-site/issues/3708

**Comment by pierre-24** [comment]
Chui pour tenter un test avec github page :)

**Comment by artragis** [comment]
Je vais voir d'ici la fin de la semaine si je peux pas lier le build au compte zds-bot.

**Comment by lypwig** [comment]
> So, now that I can check, this project and that one have the same configuration, and are based on the same github repo. The second one is just a fork of the first one. But the build of the first one systematically fails (no matter the version, the branch or the tag), while there is no problem with the second. And I really don't understand why.
[pierre24](https://github.com/rtfd/readthedocs.org/issues/3006#issuecomment-321340199)

C'est vrai que c'est super chelou...

**Comment by AmarOk1412** [comment]
Ok.
Alors je viens de foutre **gh-pages** sur https://amarok1412.github.io/ pour tester de mon côté.

Je vais tenter de traduire tous les `.rst` de *RTD* en `.md` pour le foutre sur la branche **gh-pages** ce week-end, revoir un peu la structure de la doc pour éviter les doublons, les trucs pas à jour, etc.

Ensuite faudra que @zestedesavoir/infrastructure redirigent https://docs.zestedesavoir.com vers https://zestedesavoir.github.io/zds-site/

On aura moins de documentation partout déjà. C'est cool que les choses cassent :D

(Note : faudra aussi passer de bower à yarn, mais je vais faire une issue à part dès que ça est prêt).

**Comment by motet-a** [comment]
Cool !

Du coup, tu vas retirer la partie de la doc générée automatiquement par le backend, non ?

Je pense que ça serait bien de construire la doc avec les assets de ZdS, histoire que le CSS soit à jour surtout. Mais ça risque de demander qu’on laisse la doc dans le dépot de ZdS.

**Comment by pierre-24** [comment]
On est obligé de repasser sur une doc en MD, et ne pas la faire générer par Travis ou une histoire comme ça ? (vraie question)

Parce que par exemple, on va perdre la "documentation technique du back" :(

**Comment by motet-a** [comment]
> On est obligé de repasser sur une doc en MD, et ne pas la faire générer par Travis ou une histoire comme ça ? (vraie question)

Vu comment est parti @AmarOk1412, oui. Sinon il faut s’y prendre autrement (par exemple, garder Sphinx, compiler un site statique et push tel-quel vers les pages de GitHub).

-------------------------

*[Let’s bikeshed now](http://bikeshed.org/).*

\<bikeshedding\>Personnellement, je préfère Markdown à reStructuredText. Je doute que la partie de la doc générée automatiquement par le backend soit très utile et très utilisée (dites-moi si je me trompe), je l’enlèverai, ça complique vraiment le build pour pas grand-chose. Mais je pense que je resterait avec Sphinx et RTD, je trouve que ça fait toujours un peu moins de choses à maintenir. Et on devrait facilement pouvoir construire un site static et déployer vers GitHub Pages avec.\</bikeshedding\>

**Comment by pierre-24** [comment]
Si je devais défendre Sphinx (et ReST) ici, je dirais les choses suivantes, dans l'ordre de l'importance que j'y attache:

+ Construction automatique de table des matières, des liens qui vont avec et d'une recherche.
+ *autodoc*. Moi ça m'arrive de l'utiliser,
+ Des éléments de syntaxe plus complet que markdown (par exemple, tout ce qu'on désigne par *blocs* dans notre markdown), mais c'est vrai qu'on les utilise assez peu.

**Comment by motet-a** [comment]
Note que l’on peut parfaitement utiliser Sphinx avec du Markdown, et ça marche super bien : https://github.com/motet-a/liblapin-tutorial

En fait, il y a juste un tout petit peu de reStructuredText pour la table des matière. Comme ça on garde le meilleur des deux mondes :upside_down_face:

**Comment by pierre-24** [comment]
Ah, ça, je dis pas. C'est justement pour ça que j'ai mis ReST lui même en troisième point, avant les deux premiers qui sont dû à Sphinx. Faudrait justement voir les cas ou ReST est pertinent par rapport à MD, mais comme @AmarOk1412 va passe dessus, il saura probablement répondre à ça :)

**Comment by pierre-24** [comment]
(à noter que certaines de nos docstrings sont pleines de ReST)

**Comment by firm1** [comment]
Pour la petite histoire, à l'époque le problème que l'on trouvait aux gh-pages c'était que, puisque tout ça était sur une branche séparée on ne pouvais pas dans une même PR mettre à jour le code et sa documentation. Aujourd'hui c'est pratique avec RTD pour s'assurer que l'on merge une fonctionnalité dans son ensemble (une fonctionnalité devant toujours être accompagnée de sa documentation).

**Comment by motet-a** [comment]
Je ne vois pas trop pourquoi tout changer en fait. À mon avis, c’est assez facile de laisser le dépot `zds-site` tel quel et de mettre un petit service qui compile la doc et qui commit le HTML dans un autre dépot, celui des gh-pages.

**Comment by AmarOk1412** [comment]
@pierre-24 mmh, en effet, je vais éviter d'aller trop vite.

Surtout sur ce point *Construction automatique de table des matières, des liens qui vont avec et d'une recherche*, perdre ça serait pas cool amha...

**Comment by AmarOk1412** [comment]
@pierre-24 j'ai vite fait regardé ce soir pour voir ce que j'allais faire. Je pense que je compte passer `sphinx` et `mkdocs` http://www.mkdocs.org/ pour les fichiers qui restent, compiler et publier sur le gh-pages.

Comme ça, ça permet de garder notre doc écrite, la doc générée pour le back-end, laisser les PR sur dev et garder la recherche (en plus, `mkdocs` a un thème `readthedocs`, ça sera comme si ça avait toujours compilé :) )

Pour la syntaxe, pas le temps de chercher plus que ça maintenant, mais si je peux rester au .rst je le ferais, sinon on risque de perdre 2/3 blocs. (à priori `mkdocs` ne supporte pas le `.rst`, à voir sur leur irc...)

**Comment by pierre-24** [comment]
Ok. Si jamais, il y a peut être quelque chose à creuser [par là](http://www.sphinx-doc.org/en/stable/ext/githubpages.html) (avec [cette extention](http://www.sphinx-doc.org/en/stable/ext/githubpages.html) qui rajoute automatiquement le `.nojekyll`, quoique ce soit ;) )

**Comment by motet-a** [comment]
Si ça fait juste un `touch .nojekyll`…

**Comment by AmarOk1412** [comment]
Ok alors des petites nouvelles vu que je n'ai pas eu le temps de compléter ça ce week end...

Mais au final, juste sphinx ça fonctionne (cf https://amarok1412.github.io/), pas besoin d'autre choses.

Bref l'idée au final, c'est dans un nouveau job Travis, on fait un `make html` qui nous donne notre site de docs (qu'il faut que je complète avec la doc éparpillée), puis ce job fait un petit `git add dossier`, `git amend` puis `git subtree split --branch build_doc --prefix target/doc/build` restera à push la branche `build_doc` sur `gh-pages`.

Comme ça @pierre-24 on garde les avantages de sphinx, et pour @firm1 on garde la docs sur master :)

**Comment by AmarOk1412** [comment]
Bon je suis enfin entrain de faire la PR, elle devrait apparaitre ce soir.

J'ai ajouté une page de doc venant du github-pages actuel, juste enlevé la partie du scss qui n'est plus à jour avec le gros travail des dernières semaines de @motet-a.

Pour le wiki, vu que les quelques pages qui y étaient ont été supprimées car inutiles, c'est fait :)

**Comment by AmarOk1412** [comment]
Fixed http://docs.zestedesavoir.com/!

**Comment by abdelaz3r** [comment]
J'ai ça :

```
La connexion n’est pas sécurisée

Les propriétaires de docs.zestedesavoir.com ont mal configuré leur site web. Pour éviter que vos données ne soient dérobées, Firefox ne s’est pas connecté à ce site web.

Ce site a recours à HTTP Strict Transport Security (HSTS) pour indiquer à Firefox de n’établir qu’une connexion sécurisée. Ainsi il n’est pas possible d’ajouter d’exception pour ce certificat.```

**Comment by pierre-24** [comment]
Faut qu'on demande un certif' a certbot, nan ?

**Comment by vhf** [comment]
Non. Vous devez attendre que vos DNS se mettent à jour.

**Comment by abdelaz3r** [comment]
Ok ok
