### ISSUE TITLE
Mauvais support des écrans très large

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#4458]
Bonjour,

En rapport avec ce message : https://zestedesavoir.com/forums/sujet/9077/alignement-horizontal-du-menu-principal/?page=1#p158725

Il faudrait améliorer le support des grands écrans en ajoutant des max-width.

Solution envisageable :

> `.main .sidebar { max-width: 420px; }`

A-312.

EDIT : J'ai édité mon issue, maintenant que la barre de menu est centré.

**Comment by artragis** [comment]
@motet-a ça dit quoi sur la v25?

**Comment by A-312** [comment]
Le problème semble ne plus être présent je ferme.
