### ISSUE TITLE
Problème d'affichage avec le bouton "Envoyer" (marge manquante)

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#4459]
Bonjour,

Une marge est manquante en dessous du bouton envoyer :

![Screenshot pris avec Firefox](http://i.imgur.com/G9xyS5K.png)

J'ai ce rendu pour Firefox et Chrome (dernière version, Windows).

A-312.

**Comment by motet-a** [comment]
Ouais, il y a des problèmes de marges comme ça un peu partout.
