### ISSUE TITLE
Sujets similaires -> target="_blank" manquant

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#4460]
Bonjour,

Dans les sujets similaires lorsqu'on créaient un nouveau sujet, il manque un `target="_blank"` pour les liens menant vers les catégories.

Pour les titres des sujets le `target="_blank"` y est (il s'agit donc du comportement correct).

Il faut donc ajouter un `target="_blank"` dans le template pour les catégories.

A-312.

**Comment by pierre-24** [comment]
(et on oublie pas de fermer l'issue, cette fois)
