### ISSUE TITLE
Boîtes de dialogue plutôt cassées sur IE 11

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4465]
![image](https://user-images.githubusercontent.com/15378830/29003225-f9054c62-7ab2-11e7-85a0-1e10102cca65.png)

**Comment by Situphen** [comment]
Je met en Priorité basse étant donné que IE est très peu utilisé par nos membres (d'après [le bilan en février 2017](https://zestedesavoir.com/articles/1717/zeste-de-savoir-en-2016-lannee-de-de-quoi-en-fait/#2-les-visiteurs-et-les-membres)) :

> Chrome est en hausse à 58,84 %, tout comme Safari à 7,19 %. Firefox continue sa descente aux enfers et tombe à 26,83 % ; et **tous les autres navigateurs sont sous les 2 %**.

**Comment by Situphen** [comment]
IE 11 n'est plus supporté
