### ISSUE TITLE
[v25] L’en-tête de la bibliothèque n’est pas toujours très joli

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4468]
Par exemple ici, sur [la bêta](https://beta.zestedesavoir.com/bibliotheque/sciences-de-la-nature/biologie/) avec Chrome simulant un iPhone 6 :

![image](https://user-images.githubusercontent.com/15378830/29004600-55dcf27a-7aca-11e7-9f42-79ccfd6ffddc.png)

**Comment by motet-a** [comment]
@abdelaz3r

**Comment by abdelaz3r** [comment]
Voilà j'ai fait un petit refactoring du CSS pour l'entête, pour que ce soit plus maîtrisable et surtout plus joli en mobile. J'ai aussi réduit légèrement la taille du titre principal (des gens ont fait la remarque sur le forum).

**Comment by pierre-24** [comment]
ça, normalement, c'est réglé :)
