### ISSUE TITLE
[MP] Titre de MP sans lettre

### ISSUE THREAD

**Issue by devock** [zestedesavoir/zds-site#447]
Si je mets pour titre de mp "..." (donc aucune lettre en somme), le système n'arrive pas à créer le slug, ce qui a pour conséquence de rendre le MP inaccessible alors qu'il existe bien (on a une erreur 404). 

Du coup, ça a pour conséquence de faire remonter de faux problèmes [comme le fait ShigeruM](http://zestedesavoir.com/mp/56/)...

Il faudrait avoir un espèce de slug par défaut dans ce cas là...

**Comment by firm1** [comment]
Fixé.
