### ISSUE TITLE
Le nombre de contenus affichés est incorrect

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4473]
Il est affiché sur la bêta qu'il y a 455 contenus validés alors qu'il y en a moins. D'après @pierre-24, les contenus servant à rediriger sont pris en compte, alors qu'ils devraient être exclus.

(Ce n'est pas un problème lié aux billets car si on les compte, on passe à 480 contenus).

**Comment by pierre-24** [comment]
Le problème va plus loin que ça, en fait ([vu ici](https://beta.zestedesavoir.com/bibliotheque/informatique/)):

![screenshot from 2017-08-07 00 09 30](https://user-images.githubusercontent.com/7889675/29007495-c0f15c88-7b04-11e7-82d3-5a6efaca7595.png)

(y'a deux fois le contenu OAuth2)

**Comment by pierre-24** [comment]
Ah, ben oui ... Y'a des contenus qui ont plusieurs catégories en même temps.

**Comment by AmarOk1412** [comment]
et ici :D @pierre-24

**Comment by pierre-24** [comment]
Oui :)
