### ISSUE TITLE
Le nom du site a disparu partout

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4474]
Le nom du site a disparu de tous les endroits où il est affiché : `title` des pages, footer, etc. Pour information, il s'agit du paramètre d'un `ZDS_APP` (`litteral_name`).

**Comment by motet-a** [comment]
Je crois que `litteral_name` a été renommé en `literal_name` récemment. Ça peut venir de là.

**Comment by gllmc** [comment]
En effet, certains endroits n'ont pas été mis à jour. Un coup de replace en viendra rapidement à bout, je m'en occupe.

**Comment by pierre-24** [comment]
C'est tout conement ça ? J'étais en train de me casser la tête pour rien :p

**Comment by motet-a** [comment]
Je pense que oui : https://github.com/zestedesavoir/zds-site/commit/d9794b1ab2d855e24bd3013befcfd4928508a8c8#diff-02280df5f63dd13cb1a7e40384d029f1R1060
