### ISSUE TITLE
L'affichage des contenus n'est plus dans le même ordre

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#4476]
Alors que ça devrait être du plus récent au plus vieux [ici](https://beta.zestedesavoir.com/bibliotheque/?subcategory=mathematiques&type=tutorial), c'est l'inverse :)

**Comment by pierre-24** [comment]
... Ce qui est bizarre, puisque y'a bien le `-pubdate` [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_published.py#L489)

**Comment by pierre-24** [comment]
Ah, trouvé.

**Comment by AmarOk1412** [comment]
la même ici @pierre-24

**Comment by pierre-24** [comment]
Oui :)
