### ISSUE TITLE
Le type de contenus n'est pas vérifié dans le niveau 4 de la bibliothèque

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4477]
Ce problème permet :

- d'afficher les billets en mettant `opinion`. [Exemple](https://beta.zestedesavoir.com/bibliotheque/?type=opinion&subcategory=mathematiques)
- de provoquer une erreur 500 en mettant n'importe quoi. [Sentry](https://sentry.sandhose.fr/zeste-de-savoir/beta-backend/issues/993/)

**Comment by vhf** [comment]
don't trust user input
