### ISSUE TITLE
Recherche par tag dans la bibliothèque

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4481]
Les tags sur les contenus ou dans le menu redirigent actuellement vers une URL de type https://beta.zestedesavoir.com/bibliotheque/?tag=zds, mais cela n'applique aucun filtre, il faudrait gérer cela (je pense qu'on devrait passer par le niveau 4).

**Comment by pierre-24** [comment]
Quasi fixée par erreur dans #4484 ... Donc je termine :-°

**Comment by AmarOk1412** [comment]
@pierre-24 fixé ici? Si oui on peut fermer.

**Comment by pierre-24** [comment]
Oui :)
