### ISSUE TITLE
Le lien de déconnexion dans le menu mobile ne marche pas avec IE

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4483]
Avec Microsoft® Internet Explorer™ 11 : 

![image](https://user-images.githubusercontent.com/15378830/29007320-ae216a0c-7b00-11e7-88ff-f5d78ebe3d65.png)

Le lien “Déconnexion” ne marche pas.

**Comment by motet-a** [comment]
C’est encore un autre problème endémique à Internet Explorer® : https://stackoverflow.com/questions/20658402/internet-explorer-issue-with-html5-form-attribute-for-button-element

**Comment by Situphen** [comment]
Je met en Priorité basse étant donné que IE est très peu utilisé par nos membres (d'après [le bilan en février 2017](https://zestedesavoir.com/articles/1717/zeste-de-savoir-en-2016-lannee-de-de-quoi-en-fait/#2-les-visiteurs-et-les-membres)) :

> Chrome est en hausse à 58,84 %, tout comme Safari à 7,19 %. Firefox continue sa descente aux enfers et tombe à 26,83 % ; et **tous les autres navigateurs sont sous les 2 %**.

**Comment by Arnaud-D** [comment]
Internet Explorer gravite aux alentours de 0,3% d'utilisation globale ([par exemple pour la France](https://gs.statcounter.com/browser-market-share/all/france)). J'ai jeté un oeil à des pays plus pauvres et où on pourrait s'attendre à des parts plus élevées, et ça n'est pas le cas.

C'est [même en fin de support](https://docs.microsoft.com/en-us/lifecycle/announcements/internet-explorer-11-end-of-support) y compris pour les organisations et supplanté par Edge de toute façon. Le résidu d'utilisateurs d'IE doivent être des gens qui naviguent depuis des machines obsolètes à leur travail.

Je pense qu'on peut fermer. N'hésitez pas à rouvrir si vous n'êtes pas d'accord.
