### ISSUE TITLE
Mélanges de `and` et de `or` trompeurs

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4486]
[Ici](https://github.com/zestedesavoir/zds-site/blob/dev/templates/member/profile.html#L577) et [là](https://github.com/zestedesavoir/zds-site/blob/dev/templates/member/profile.html#L326) dans `/templates/member/profile.html`. C’est un peu ambigu pour un être humain : 

```python
{% if perms.member.change_post and profile.get_post_count_as_staff > 0 or profile.get_post_count > 0 %}
```

```python
{% if usr == user or not perms.member.change_profile and profile.is_private %}
```

Par exemple : 

```python
> True or False and False
True
> (True or False) and False
False
> True or (False and False)
True
```

**Comment by gllmc** [comment]
En fait, dans les templates Django, il n'est pas possible d'utiliser les parenthèses et les `and` sont toujours évalués avant les `or`. Donc je ne sais pas si ça doit être corrigé.

**Comment by motet-a** [comment]
@gcodeur À la limite on peut mettre un `{% if` dans un autre `{% if` à la place des `and`. C’est plus verbeux mais c’est toujours plus clair.

**Comment by gllmc** [comment]
@motet-a : ce que tu décris est la solution si on veut que `or` soit pris en compte avant `and`, mais dans le cas contraire (exemples de ton ticket), cette solution ne marche pas. ;)

**Comment by motet-a** [comment]
Bon, il n’y a pas de solution simple du coup (peut-être faut-il changer des choses dans le controlleur ?). Merci !
