### ISSUE TITLE
Impossible de décocher "Se souvenir de moi"

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4492]
Bonjour tout le monde !

Je ne me suis pas connecté du week-end, mais je viens de remarquer qu'il n'est pas possible de dé-cocher "Se souvenir de moi" (en écho à [ce sujet](/forums/sujet/4848/impossible-de-cocher-se-souvenir-de-moi)) sur la page de connexion…

Rien de vraiment grave ni de bloquant, mais je voulais quand même le signaler ;)

Sujet : https://zestedesavoir.com/forums/sujet/9101/impossible-de-decocher-se-souvenir-de-moi/
*Envoyé depuis Zeste de Savoir*

**Comment by pierre-24** [comment]
Merci @rezemika :)
