### ISSUE TITLE
[v25] Changer le texte de la page d'accueil

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#4500]
Il y aurait peut être moyen d'améliorer un tout petit peu le texte d'accueil pour laisser sous-entendre que article et tutoriels sont rangés dans la "bibliothèque", non ?

**Comment by A-312** [comment]
> Zeste de Savoir : un site de partage de connaissances où vous trouverez, gratuitement et sans publicité :
des tutoriels de tous niveaux ;

A)

> Zeste de Savoir : un site de partage de connaissances où vous trouverez, gratuitement et sans publicité. La bibliothèque est composée :

B) 

> Zeste de Savoir : un site de partage de connaissances. Dans notre bibliothèque vous trouverez, gratuitement et sans publicité :
