### ISSUE TITLE
Certains contenus n'ont pas de temps de lecture estimé

### ISSUE THREAD

**Issue by rezemika** [zestedesavoir/zds-site#4501]
Tout est dans le titre, certains contenus n'affichent aucune estimation de leur temps de lecture. Voici la liste complète, générée à l'instant avec un script (il y en a 10 au total, tous des billets) : 

- https://zestedesavoir.com/billets/2063/anniversaire/
- https://zestedesavoir.com/billets/2044/geobreve-2-quelle-difference-entre-technopole-et-technopole/
- https://zestedesavoir.com/billets/1966/participer-a-une-videoconference/
- https://zestedesavoir.com/billets/1953/billet-signet-monsieur-phi/
- https://zestedesavoir.com/billets/1935/github-10-12-marty-mcfly-compter-les-smartphones-supprimer-vos-comptes/
- https://zestedesavoir.com/billets/1915/github-7-9-generateur-de-site-de-documentation-ascii-art-fair-analytics/
- https://zestedesavoir.com/billets/1914/et-le-plus-gros-depot-git-du-monde-appartiendrait-a/
- https://zestedesavoir.com/billets/1909/github-4-6-system-design-collection-o-rly-graphisme-geek/
- https://zestedesavoir.com/billets/1902/github-1-3-graphql-postgresql-programmation-fonctionnelle-l-systems/
- https://zestedesavoir.com/billets/1894/doc-python-en-francais/

**Comment by A-312** [comment]
Apparemment il n'aime pas que le temps soit inférieur à une minute.

**Comment by gllmc** [comment]
En soi, ça me choquerait d'afficher "Temps estimé : 0 minute", donc je pense que le comportement actuel n'est pas si mal que ça. On peut aussi afficher "moins d'une minute".

**Comment by A-312** [comment]
Je vote pour "moins d'une minute".

[Donc :](https://github.com/zestedesavoir/zds-site/blob/d9794b1ab2d855e24bd3013befcfd4928508a8c8/templates/tutorialv2/includes/tags_authors.part.html#L79)


        {% if online and reading_time %}
            {% trans "Temps de lecture estimé : " %}{{ reading_time | minute_to_duration:"long"}}
        {% elseif online %}
            {% trans "Temps de lecture estimé à moins d'une minute." %} :
        {% endif %}

On garde ":" ou on met "à" ?

**Comment by pierre-24** [comment]
"à" me semble bien.

**Comment by pierre-24** [comment]
Voilà :)
