### ISSUE TITLE
Mettre au pluriel "Voir la tribune de ...."

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#4511]
Bonjour,

Lors de la lecture d'un billet, le choix "Voir la tribune de ...." n'est pas claire. Et ne prend pas en compte le cas où l'auteur à plusieurs tribunes.

 - Rajouter cette phrase au pluriel ?
 - Modifier la phrase en : "Voir les autres tribunes de ....".

Le problème se trouve ici : [content_online.html#L231](https://github.com/zestedesavoir/zds-site/blob/2416d5ad8a0c87e0686851f04189bacdb8877eb9/templates/tutorialv2/view/content_online.html#L231).

Lorsqu’il y a plusieurs auteurs la liste se fait très longue : https://zestedesavoir.com/billets/2090/zeste-de-savoir-passe-en-version-24-1/ 

A.

**Comment by pierre-24** [comment]
"La" tribune est l'endroit ou un auteur publie "des" billets (sinon ça s'appellerait des tribunes) ;)

**Comment by A-312** [comment]
Ah ! Ce n'est pas claire... Je pensais que "une tribune" = "un billet".

Donc on reste sur la position actuelle ? Même si j'imagine que je ne suis pas le seul à faire cette erreur.

**Comment by vhf** [comment]
En français une tribune c'est un espace d'expression (au figuré), un lieu surélevé genre estrade (au sens propre). On s'y exprime (en écrivant des choses) ou on y prononce des discours.
