### ISSUE TITLE
[v25] La version mobile de la bibliothèque est trop longue

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#4513]
Bonjour,

Je viens ici car la version mobile de la bibliothèque est trop longue, la liste des catégories n'est pas des plus utile et cache le vrai contenu de la page (Sans parler du bug avec la largeur).

Suggestion : 
 - Mettre la liste des catégories dans le menu à gauche ;
 - Faire un slide gauche/droite ;
 - Afficher seulement les titres des catégories, et afficher le reste au clique dans l'idée d'[un menu accordéon](https://jqueryui.com/accordion/).

![screen avec Firefox, W10](http://i.imgur.com/aueWrfW.png)

**Comment by pierre-24** [comment]
Lié à #4482 ?

**Comment by A-312** [comment]
> Lié à #4482 ?

Seulement pour ce qui a entre parenthèse, ici je parle de la longueur (hauteur) de la page.

**Comment by motet-a** [comment]
C’est sur quel navigateur que ça fait ça ? Normalement toute la page doit s’adapter correctement à la largeur de la fenêtre, il n’y a pas besoin de mettre un défilement horizontal ou je ne sais quoi.

**Comment by A-312** [comment]
Ce rendu vous pertube (normalement la partie de droite avec le background noir, n'est pas accessible, le rendu à pris de façon strict le --fullpage.

Le vrai rendu est celui-ci : 
![image](https://user-images.githubusercontent.com/18501150/29239630-1f8991d2-7f53-11e7-8d13-e3ed4511e0c3.png)

Ce que je critique ici, c'est la partie "Domaines de savoir" qui est trop longue. Je ne parle pas du bug de largeur/horizontal, etc...

**Comment by pierre-24** [comment]
Bon, je reconnais qu'en mobile, on pourrait peut être faire disparaitre un ou deux contenus de chaque liste, et éventuellement les sous-catégories. Par contre, l'accordéon, je suis pas forcément pour.

Ping @abdelaz3r :)

**Comment by abdelaz3r** [comment]
Alors en fait, à mon avis, cette page doit (et va) beaucoup évoluer. Là on a mis uniquement ce qu'on a pour l'instant mais on aimerai à terme rendre cette page plus intéressante. Donc je suis pas spécialement pour faire beaucoup de développement (genre JS pour un accordéon) surtout si on fait des modifications par la suite.

**Comment by A-312** [comment]
Quand je parlais d'un accordéon c'était un simple effet "spoiler".
