### ISSUE TITLE
[v25] Ecran large (1920px) et fixed layout dans la bibliothèque

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#4514]
Bonjour,

Si je me souviens bien, il y a quelques années, la question du fixed layout a été de ne pas appliquer de taille fixe, et de laisser le choix de profiter de toute la largeur.

Je propose donc de reste sur cette continuité.

Sur la beta avec la bibliothèque :

![beta](http://i.imgur.com/xz3jmHp.png)

Actuellement sur la v24 : 
![v24 srevinu](http://i.imgur.com/elNZLdU.jpg)

**Comment by pierre-24** [comment]
Je disais donc ...

> Par ailleurs, le retour à un layout fixe est une volonté, pas une erreur, pour être raccord avec ce qui se fait ailleurs sur le site ( si @abdelaz3r peut confirmer ?)

**Comment by abdelaz3r** [comment]
Alors concernant ça, effectivement ça n'a jamais été officiellement validé.

Cependant, et suite à [cette discussion](https://zestedesavoir.com/forums/sujet/4856/discussions-sur-le-design-de-zestedesavoir/) (et plus précisément dans le section *A propos du design d'Alex-D*) qui posait les bases de la réflexion qui a mené ce choix, et au vue de l'aval important reçu (par les pouces verts), on a décidé de faire comme ça.

Comme tout dans zeste de savoir, on peut en discuter mais c'est évident que ce que tu proposes ne rentre pas du tout dans ce qui semble avoir été décidé.

**Comment by A-312** [comment]
Ils ont voté explicitement pour un fixed layout ? Quel est la taille de leur écran ?

**Comment by abdelaz3r** [comment]
Non comme tu peux le voir. Cepandant, pour la page d'accueil ce *fixed layout* avait remporté la partie et vu les 36 likes et les 2 dislikes (effectivement sur tout mon message) et la réflexion que je propose derrière (qui me semble pas trop déconnante) je suis partit sur cette proposition.

Maintenant rien ne t'empêche de refaire une demande et un débat. Moi je vais pas le faire, je considère (comme écrit dans mon post) que les avantages d'un *fixes layout* sont, pour la présentation de liste de contenu et de choses éditoriales, très importants (et relis bien mon message, il s'agit de pleins de truc).

**Comment by A-312** [comment]
Je souhaite un contenu de taille dynamique uniquement pour cette page/niveau. Ca risque d'être incohérent avec le reste ?

**Comment by abdelaz3r** [comment]
Complètement. Mais vraiment complètement (et je dis pas ça pour te faire chier ou être contre ta proposition). Mais ça tue totalement l'interface, la logique et la progression de cette UI/UX.

Du coup si vraiment tu sembles considérer ça comme essentiel je te propose : 

1. De proposer ceci sur le forum (et voir le débat qui vient), en sachant que perso, trouvant cela hérétique, je ne m'occuperai pas des modifications. Mais probablement que quelqu'un le fera.
2. De proposer sur le forum de revenir à un non*-fixed layout* sur toute la bibliothèque (qui me paraît déjà plus cohérant) mais que je ne soutient pas personellement.
3. Si tu sembles le seul affecté, de faire un user-script qui fait ce que tu veux.

**Comment by vhf** [comment]
Pour l'instant @A-312 on va rester sur un layout fixe, comme visible actuellement sur la beta.

**Comment by A-312** [comment]
En effet, je pensais juste à modifier le niveau 4. Mais si c'est incohérent autant ne rien faire.
