### ISSUE TITLE
[v25] Liste des catégories manquantes dans la liste de tous les tutoriels

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#4515]
Bonjour,

La liste des catégories est manquante dans la liste des tutoriels **dont pour la liste "tous les tutoriels"**. Sachant que j'ai choisi aucune catégorie, ne devrions-nous pas justement intégrer la liste des catégories pour affiner le choix/la liste ?

(Dans le cas où je fais Page d'accueil > Bibliothèque > "Accéder à tous les contenus..." > "Plus de tutoriel").

Sur la beta avec la bibliothèque :

![beta](http://i.imgur.com/xz3jmHp.png)

Actuellement sur la v24 : 
![v24 srevinu](http://i.imgur.com/elNZLdU.jpg)

**Comment by gllmc** [comment]
Le comportement est normal : pour afficher la liste des tutoriels d'une catégorie, il faut cliquer sur la catégorie puis sur "Plus de tutoriels dans ...". À plus long terme, il me semble qu'il est prévu de pouvoir affiner les filtres directement depuis le niveau 4 de la bibliothèque, ce qui permettra ce que tu proposes.

**Comment by pierre-24** [comment]
~~Par ailleurs, le retour à un layout fixe est une volonté, pas une erreur, pour être raccord avec ce qui se fait ailleurs sur le site ( si @abdelaz3r peut confirmer ?)~~

(*pas le bon sujet*)

**Comment by A-312** [comment]
@pierre-24 Le fixed layout c'est l'issue voisine : #4514

**Comment by pierre-24** [comment]
Bien vu :)

(note, pareil, c'est une volonté)

**Comment by abdelaz3r** [comment]
Exact

**Comment by vhf** [comment]
> Le comportement est normal : pour afficher la liste des tutoriels d'une catégorie, il faut cliquer sur la catégorie puis sur "Plus de tutoriels dans ...".

Yep. (Je fais un peu de ménage dans les issues histoire qu'on voit clairement ce qu'il reste à faire.)
