### ISSUE TITLE
Réécrire le CSS

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4524]
Bonjour,

Après avoir passé quelques jours à essayer d’améliorer 
doucement le CSS, je pense de plus qu’il ne serait pas
forcément si idiot de le réécrire complètement.

[Bon, je sais bien que ce n’est pas forcément une bonne idée.](https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/)

Comme je l’ai déjà dit, je trouve qu’il y a vraiment beaucoup
de choses assez vielles dans le SCSS (avec les `float: left`,
les pourcentages, le fait que `1rem` n’est pas égal à la taille
de la police par défaut, etc), c’est vraiment difficile à améliorer
et je trouve que ça empêche vraiment d’avancer rapidement.

Je propose de réécrire tout le CSS avec [Stylus](http://stylus-lang.com/), une alternative
récente à SCSS. J’ai regardé rapidement, ça me semble plutôt
bon (il faudrait juste préfixer les variables avec des `$` pour 
éviter les conflits avec des mots-clés comme `inherit`,
`initial`, `dotted`, ...).

Qu’en pensez-vous ?

**Comment by pierre-24** [comment]
"Quels sont les avantages de Stylus sur SCSS qui justifierais un tel changement ?" est la première question que j'ai envie de poser.

**Comment by motet-a** [comment]
@pierre-24 Je trouve que les avantages de Stylus sur SCSS sont quasiment que syntaxiques. Actuellement, je n’ai pas vu de choses possibles avec Stylus et pas possibles avec SCSS. Si je propose de réécrire le SCSS actuel, c’est pas pour le plaisir de changer de techologie, mais c’est parce je trouve que le *code* actuel mériterait d’être vraiment amélioré.

**Comment by pierre-24** [comment]
Je ne remet absolument pas en question le fait que le (S)CSS actuel aurait besoin d'un coup de ménage (quitte à le réécrire entièrement si tu te sens de porter ça sur la longueur). Je m'interroge juste sur le changement de techno, en fait.

**Comment by motet-a** [comment]
Ah OK 🙃. En fait j'ai à peine essayé Stylus, mais étant donné sa similarité avec SCSS on aura vite fait de tout traduire (concrètement il faut juste rajouter des points virgules, des accolades et quelques bricoles dans le genre).

**Comment by Situphen** [comment]
@motet-a Pour le changement SCSS -> Stylus, le problème n'est pas l'adaptation à la syntaxe mais plutôt le passage des outils SCSS->CSS aux outils Stylus->CSS. Actuellement notre stack pour builder le front tourne plutôt bien (avec Gulp et compagnie), passer à Stylus c'est risquer de ce casser la tête sur cette partie-là.
Réécrire tout le SCSS va te prendre **énormément** de temps, ne te complique pas encore plus la vie. Écrire en SCSS c'est franchement pas la mort, je pense que tu peux déjà faire la réécriture et une fois que ça c'est OK, faire le changement SCSS->Stylus. (J'insiste encore, pour la syntaxe c'est pas le plus compliqué, bien que probablement rébarbatif. C'est surtout au niveau logiciel que c'est risqué à mon avis.)

**Comment by motet-a** [comment]
@Situphen En fait, il n’y a presque rien à changer dans le Gulpfile. Il n’y a pas besoin de toucher PostCSS, il faut juste traduire `_sprite.scss.hsb` et remplacer `gulp-sass` par `gulp-stylus`. Et hop.

**Comment by pierre-24** [comment]
Je reste d'accord que le faire en deux étapes reste plus *safe*.

**Comment by A-312** [comment]
Stylus c'est sass sans les brackets et point virgule ?

**Comment by motet-a** [comment]
[En gros ouais](http://stylus-lang.com/).

**Comment by nils-van-zuijlen** [comment]
Tant qu'à le réécrire, autant le faire en intégrant #2003 !

**Comment by A-312** [comment]
Il ne faudrait pas refaire le nommage des class, si on refait quelques choses ? Et essayer de rendre l'usage plus "framework" avec une page d'exemple qui englobale tout le css non spécifique à un seul élément ?

Je ne sais pas si je suis claire dans mon explication.

**Comment by Situphen** [comment]
C'est possible, mais ça demande beaucoup de travail de penser le CSS en tant que *framework*, surtout qu'il y a d'un côté les anciennes pages (avec la barre latérale) et de l'autre les nouvelles pages (avec le bandeau bleu). Néanmoins si tu veux te lancer dedans, libre à toi !

Pour la page d'exemple, pourquoi pas. Par contre, sa place sera dans la documentation.

**Comment by A-312** [comment]
Je voudrais aussi en complément une page qui serve de vérification pour l'écriture du CSS, je ne sais pas si sur django on peut avoir une page uniquement pour la beta (dev) et soit absente sur la prod.

**Comment by Situphen** [comment]
Je ferme ce ticket car la PR #5922 a apporté de nombreuses améliorations et d'autres viendront dans le futur petit à petit. Je ne pense pas qu'une réécriture complète du CSS soit vraiment imaginable car serait un boulot vraiment trop important pour les contributeurs que nous sommes.
