### ISSUE TITLE
Erreur de balisage dans le menu principal

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4527]
Et voici un splendide `ul>ul` : 

![image](https://user-images.githubusercontent.com/15378830/29302912-89699e12-8188-11e7-8479-9563cf11e7b5.png)

Sur le MDN, [on peut lire ça à propos de `<ul>`:](https://developer.mozilla.org/en/docs/Web/HTML/Element/ul)

> Permitted content: zero or more `<li>` elements

Bon, si ça ne se produit que lorsqu’il n’y a aucun élément, on peut considérer ça comme mineur.

**Comment by Situphen** [comment]
Pas que pour les billets apparemment ! **À faire** : enlever les balises `<ul>` ou `</ul>` [ici](https://github.com/zestedesavoir/zds-site/blob/v24.2-Srevinu/templates/base.html#L223) [là](https://github.com/zestedesavoir/zds-site/blob/v24.2-Srevinu/templates/base.html#L227) [ici](https://github.com/zestedesavoir/zds-site/blob/v24.2-Srevinu/templates/base.html#L274) [là](https://github.com/zestedesavoir/zds-site/blob/v24.2-Srevinu/templates/base.html#L278) [ici](https://github.com/zestedesavoir/zds-site/blob/v24.2-Srevinu/templates/base.html#L326) [là](https://github.com/zestedesavoir/zds-site/blob/v24.2-Srevinu/templates/base.html#L330)
