### ISSUE TITLE
Alerter la différence entre billets et contenus validés

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#4530]
En rapport avec ce sujet : https://zestedesavoir.com/forums/sujet/9090/bandeau-pour-alerter-la-difference-entre-billets-et-contenus-valides-tutorielsarticles/

Pour rendre la différence entre billet/contenus validés plus visible une idée de bandeau/message a été proposé.

Selon le message d'ache, il suffirait d'ajouter [à la suite de ce fichier](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/includes/tags_authors.part.html#L84) : 
 - Une condition pour savoir si c'est le contenu est un billet et online ;
 - Le message proposé par Ache (voir ci-dessous) ;
 - Et créer une page qui explique la différence entre les deux éléments.

> Temps de lecture estimé : 9 minutes  
> Ceci est un billet d'expression libre. Voir la [différence entre un billet et un contenu validé](https://zestedesavoir.com/). 💬

J'ai légèrement modifié la proposition d'ache pour faire apparaître la notion de "contenu validé".

Bon vol,

A.

**Comment by artragis** [comment]
Je clos car la différence est déjà bien mise en avant.
