### ISSUE TITLE
logo-mobile@2x.png a été créé à partir d’une image JPEG

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4533]
...et c’est moche et ça se voit un peu :

![image](https://user-images.githubusercontent.com/15378830/29367698-101056d4-829e-11e7-8d94-b4ff9435a806.png)

Il faudrait le recréer proprement à partir d’une image vectorielle, avec un fond transparent.

**Comment by DevHugo** [comment]
https://github.com/zestedesavoir/documents-communication/tree/master/logo . Si ça peut t'aider ...

**Comment by A-312** [comment]
J'ai illustrator pour ouvrir les fichiers .ai si personne ne le fait avant.

**Comment by motet-a** [comment]
@A-312 Je n’ai pas Illustrator mais ça peut se faire avec Inkscape, il y a des SVG.

**Comment by A-312** [comment]
Si ça rend fidèlement la qualité, faisons ça.

**Comment by A-312** [comment]
format 512x512 (les png sont entrelacés) :

png transparent :
![icone_512entrelace](https://user-images.githubusercontent.com/18501150/29820044-5d269102-8cc3-11e7-91a4-5e3de7df4945.png)

png :
![icone_512e](https://user-images.githubusercontent.com/18501150/29820122-a6e26f6e-8cc3-11e7-8c1d-2086cc41e81d.png)



jpg :
![icone_512](https://user-images.githubusercontent.com/18501150/29820045-5ea66836-8cc3-11e7-95ac-018e43c272eb.jpg)

**Comment by motet-a** [comment]
D’ailleurs, il y a le même problème sur les `apple-touch-icon-*.png`.
