### ISSUE TITLE
Citer uniquement la sélection

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#454]
Le bouton citer ajoute au message en cours de rédaction la sélection du message suite au clic sur "Citer" du dit-message.

**Comment by ghost** [comment]
Je prends.

**Comment by A-312** [comment]
Je vais continuer à améliorer cette fonctionnalité : 
- Prendre en compte la position du caret dans le textarea.
- Il manque plus que de parser les tableaux en markdown.
- Ajouter des tests.
- Lors d'un coller, prendre en compte la mise en forme (event paste) pour avoir un format markdown directement.

PS : J'ai oublié de vérifier le "endContainer" (position de fin de la selection).

**Comment by ghost** [comment]
Deux exemples de rendu :

http://www.mergely.com/Uv0yk4Wf/
http://www.mergely.com/i4n4chlX/

**Comment by ghost** [comment]
Commit x6 à cause d'un bug...

**Comment by GerardPaligot** [comment]
Ceci rentre dans le cadre d'une ZEP. Inutile sur GitHub (et ne motive personne).
