### ISSUE TITLE
Les trois points de suspensions ne devrait pas s'afficher dans la recherche quand on est dans une catégorie bien précise

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#4541]
Cf: https://beta.zestedesavoir.com/bibliotheque/sciences-humaines-et-sociales/economie/

**Comment by motet-a** [comment]
Dans le *placeholder* de la barre de recherche tu veut dire ?

![image](https://user-images.githubusercontent.com/15378830/29496584-b27ebc0a-85d5-11e7-9226-950c1b0487ee.png)

**Comment by DevHugo** [comment]
Oui

**Comment by gllmc** [comment]
Personnellement, je ne trouve pas que cela soit un problème : je n’interprète pas ces points de suspension comme l'indication que ce n'est pas une catégorie précise, mais plutôt comme le fait que l'utilisateur est incité à taper quelque chose.
