### ISSUE TITLE
La page déborde horizontalement

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#4542]
Bonjour,

Sur une taille d'écran moyen, les boutons envoyer et apperçu ne sont pas visible. Uniquement sur firefox, tous les OS. Présent sur la béta, pas sur la prod.

![](https://user-images.githubusercontent.com/6099338/29496027-6c0a4cc2-85ca-11e7-9462-3903f1daa574.png)

Merci d'avance

**Comment by pierre-24** [comment]
Y'a un problème avec le redimensionnemnt, en fait.

**Comment by DevHugo** [comment]
Je suis pas sur de bien comprendre ce que tu veux dire ^^ , tu veux dire sur tout le site ?

**Comment by motet-a** [comment]
OK, c’est sans doute dû à mon bricolage du footer.

**Comment by Situphen** [comment]
En fait c'est tout le site qui est touché là, comme s'il y avait un max-width. En fait comme le dit @motet-a c'est son bricolage, et plus précisément le [`display: flex;`](https://github.com/zestedesavoir/zds-site/commit/9a07f4be69cec58b06c953991103e35c15394838#diff-24bb8a5cd0a83851fcb95c6775388516R68) qui est la cause !

**Comment by DevHugo** [comment]
C'est bizarre, ça marche sur chrome ! Les joies des implémentation différente par navigateur !

**Comment by Situphen** [comment]
Bon, c'est bizarre car je n'arrive pas à reproduire le bug en local (ceci dit mon installation locale de ZdS n'est pas vraiment tenue à jour :D ). Je veux bien qu'un d'entre vous essaie pour voir si c'est seulement moi ou pas :)

Vu que sur la beta le problème se résout quand j'enlève le `display: flex;` (et son équivalent `display: -webkit-box`) à `main-container` bah je fais une PR quand même.

**Comment by motet-a** [comment]
@Situphen Je m’en occuppe.

**Comment by Situphen** [comment]
@motet-a Tu résout le problème par *ajouter* `min-width: 0;` et effectivement ça fonctionne mais je préfère ma solution qui consiste à *enlever* `display: flex;` qui n'a pas l'air de servir :)

**Comment by motet-a** [comment]
@Situphen Oulà, je vois pas comment tu peux enlever le `display: flex;` du `.main.wrapper` sans tout casser :upside_down_face:

**Comment by Situphen** [comment]
Pas le `.main.wrapper` mais le `.main-container` ;)

**Comment by motet-a** [comment]
@Situphen Ouais ça se tient, mais la *sidebar* ne descend plus jusqu’en bas de la page dans ce cas (en fait, elle ne descend pas non plus sur la production, mais j’aime bien ça (et il me semble que @abdelaz3r aime aussi ça) donc bon…)

Puis personnellement, je trouve que `display: flex;` est toujours un peu plus simple que `display: block;` pour ce genre de choses quand on passe un petit peu de temps à corriger les petits caprices de Firefox (mais c’est subjectif hein).

**Comment by motet-a** [comment]
Bon en fait, comme me l’a signalé @gcodeur, ce bug ce présente aussi sur Chrome avec la page d’accueil : 

![image](https://user-images.githubusercontent.com/15378830/29496980-25093e2c-85df-11e7-9c02-0cb4f9a04300.png)

Le patch reste le même.

**Comment by Situphen** [comment]
@motet-a Ah d'accord bah du coup oui ça a un intérêt d'utiliser ta solution plutôt que la mienne :)

**Comment by A-312** [comment]
@motet-a Comme le premier screen de #4513 ? Je pensais que c'était lié à la page d'accueil et que ça allait être corrigé par abdelaz3r. Oups, je suis passé a côté. 🙄

**Comment by motet-a** [comment]
@A-312 Ouais, je crois que c’est bien ça.

(Je me demande encore comment j’ai pu ne pas voir un tel problème sur Chrome…)

**Comment by motet-a** [comment]
J’ai renommé l’issue vu que ça n’est pas propre à Firefox.

**Comment by nils-van-zuijlen** [comment]
Effectivement Safari à aussi ce problème.
