### ISSUE TITLE
Grosse panne

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4546]
Coucou,

Selon @artragis c’est juste que l’association n’a pas payé Gandi.

> Message originel :
> 
> Voilà plus de 30 minutes que je ne peut ni `ping` ni `curl` https://zestedesavoir.com depuis deux machines différentes à deux endroits différents et avec deux ISP différents. Et [à priori, ça ne vient pas de chez Gandi](https://status.gandi.net/).

**Comment by DevHugo** [comment]
Je confirme.

**Comment by pierre-24** [comment]
Ce qui est "marrant", c'est que la bêta est pas touchée (sinon, je confirme)

**Comment by motet-a** [comment]
@pierre-24 `whois` me dit que beta.zestedesavoir.com est hébergé chez Scaleway/Online.net alors que zestedesavoir.com est chez Gandi.

**Comment by pierre-24** [comment]
Mmmh. L'édit de @motet-a fait sens.

**Comment by DevHugo** [comment]
Si on a des problèmes de sous, je peux avancer de l'argent.

**Comment by motet-a** [comment]
@DevHugo En fait, je crois que c’est [plus un problème d’organisation qu’un problème de sous](https://beta.zestedesavoir.com/billets/1998/deboires-financiers-suite-et-fin/).

**Comment by nils-van-zuijlen** [comment]
Il y a un progrès :/ nginx renvoie une erreur HTTP 403 ...

**Comment by DevHugo** [comment]
![](https://rlv.zcache.com/its_something_meme_postcard-r048747b5c6b24a2381258f05fd149b78_vgbaq_8byvr_324.jpg)

motet-a > wait and see

**Comment by motet-a** [comment]
Merci aux réparateurs, ils ont réparé !
