### ISSUE TITLE
On ne peut plus suivre certains sujets

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4548]
1. Allez à https://beta.zestedesavoir.com/forums/sujet/9162/test/

2. Cliquez sur “Suivre ce sujet” dans la barre de gauche 
![image](https://user-images.githubusercontent.com/15378830/29508407-b6ee02d0-8654-11e7-977a-627f1ade9ec1.png)

3. Rien ne se passe parce que 403 : 

![image](https://user-images.githubusercontent.com/15378830/29508354-8bd44f5a-8654-11e7-854b-d8ad0207d773.png)

**Comment by pierre-24** [comment]
Mmh. Ça m'a tout l'air d'être un effet de #4529 :(

**Comment by gllmc** [comment]
Non, c'est un autre problème qui était déjà là avant : la vue est bloquée si le premier message est masqué. Je crois qu'il y a une issue là-dessus mais je ne la retrouve pas. :(
