### ISSUE TITLE
Erreur de connexion à Elasticsearch lors d'une recherche

### ISSUE THREAD

**Issue by entwanne** [zestedesavoir/zds-site#4549]
Bonjour,

En voulant utiliser la barre de recherche pour retrouver un sujet, j'ai été confronté à un bandeau « Impossible de se connecter à Elasticsearch ».

Pour reproduire : <https://zestedesavoir.com/rechercher/?q=toto>

![Impossible de se connecter à Elasticsearch](http://i.imgur.com/qkbvAe2.png)

**Comment by pierre-24** [comment]
Le service n'a problablement pas été démaré :) (dire que j'avais hésité à le mettre, ce message, parce qu'il est pas très joli)
