### ISSUE TITLE
[v25][beta] La zone de saisie pour la recherche dans la bibliothèque pas assez grande

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4552]
Navigateur : Firefox 52
OS : Windows
Image : 

![recherche](https://user-images.githubusercontent.com/6066015/29518849-5f1f1d4c-867b-11e7-8d6b-fac51bd71901.PNG)

Comme je le montre dans l'image, visuellement la barre de recherche ne rend pas top sur un écran de pc. La zone en bleu est plus large que la zone en rouge. ça donne un effet déséquilibré à la page. Il faudrait etendre la zone de saisie vers la droite de quelques pixels.

**Comment by firm1** [comment]
Je me permet de ré-ouvrir ce ticket qui n'a pas encore été corrigé.

**Comment by abdelaz3r** [comment]
Je fais

**Comment by abdelaz3r** [comment]
C'est fait.
