### ISSUE TITLE
[v25][beta] Le menu dans la topbar n'est vraiment centré

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4553]
Navigateur : Firefox 52
OS Windows

Voici ce que je vois sur la page d'accueil. J'avais une impression de désiquilibre au départ, j'ai essayer de mesurer pour vérifier mon impression t il s'avère que le menu de la top bar n'est pas centré.

![centrage](https://user-images.githubusercontent.com/6066015/29519316-453e134a-867d-11e7-8ba9-057842e8d2eb.PNG)

Comme on le voit dans l'image le cercle vert constitue le trop de largeur coté gauche. Il faudrait donc réparer le centrage.

**Comment by motet-a** [comment]
Et oui, bien vu ! Je sais comment régler ça, d’ailleurs le pied de page a exactement le même petit problème (je me suis dit que c’était assez mineur et que ça pouvait attendre :upside_down_face:).
