### ISSUE TITLE
[v25][beta] La recherche dans la biblio depuis une catégorie n'est pas fonctionnelle

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4554]
Procédure pour reproduire le bug.

- Allez dans les publications de la catégorie biologie ([ce lien](https://beta.zestedesavoir.com/bibliotheque/sciences-de-la-nature/biologie/))
- Vous voyez qu'un article qui a été publié s'appelle "le gaz sarin"
- Saisissez dans la zone de recherche "gaz" et cliquez sur rechercher
- Constater que vous n'avez aucun résultat dans la recherche.

Aide à la résolution : 

L'url après le submit du bouton ressemble à ceci : `https://beta.zestedesavoir.com/rechercher/?q=gaz&models=content&category=sciences-de-la-nature&subcategory=biologie` et si je supprime les derniers paramètre de la requête get, et donc cette url `https://beta.zestedesavoir.com/rechercher/?q=gaz&models=content` j'ai des résultats, donc je suppose que le moteur de recherche ne gère pas les paramètres `category` et `subcategory`

**Comment by pierre-24** [comment]
[Mais mais mais ...](https://github.com/zestedesavoir/zds-site/blob/dev/zds/searchv2/tests/tests_views.py#L863) ?!?

**Comment by gllmc** [comment]
J'ai l'impression que ça a été [corrigé](https://beta.zestedesavoir.com/rechercher/?q=gaz&models=content&category=sciences-de-la-nature&subcategory=biologie), non ?

**Comment by firm1** [comment]
Tout a fait. Je confirme que c'est corrigé
