### ISSUE TITLE
[v25][beta] Qui est autorisé à donner/supprimer des casquettes ?

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4555]
Suite à la lecture de [ce message](https://beta.zestedesavoir.com/forums/sujet/9161/les-nouveaux-smileys/#p160127) sur le forum, il semblerait que @EGabbro puisse supprimer/donner des badges.

Le truc c'est que moi aussi j'ai les droits pour faire ces actions. Donc je m'interroge.

Etant donné que j'appertiens aux groupes "devs" et "ca" et que @EGabbro appartient au groupe "staff" uniquement, est-ce que c'est documenté quelque part qui est autorisé à utiliser les casquettes ?

**Comment by EGabbro** [comment]
Si j'ai bien suivi, toute personne possédant les droits de modération peut changer la casquette d'un message parmi les casquettes disponible pour le membre.

Ainsi, je ne peux que placer « Staff » sur mes messages, mais je peux placer « devs » et « ca » sur les tiens, ainsi que « staff », « le Jacques Chirac du bulgur » ou « Équipe technique » sur ceux de victor.

Normalement, tu ne peux toi changer la casquette que de tes messages.

**Comment by firm1** [comment]
Ce que je voulais dire c'est que j'ai accès à la [liste des casquettes en cours de demande](https://beta.zestedesavoir.com/membres/casquettes/demandes/) et que j'ai les droits pour donner une casquette quelconque à celui qui en fait la demande.

Est-ce que toi aussi tu as accès à cette page des demandes de casquette ?

**Comment by pierre-24** [comment]
Anéfé, j'ai le droit d'accorder des casquettes, alors que ça ne devrait pas être le cas. Voilà qui me semble bloquant.

**Comment by EGabbro** [comment]
J'ai une 403 (droit insuffisant).

**Comment by firm1** [comment]
> J'ai une 403 (droit insuffisant).

Ah donc on dirait que c'est un droit accordé uniquement aux membres de l'équipe dev (ce qui me semble très bizarre).

Bref, comme dit @pierre-24 ça sent le bug bloquant.

**Comment by pierre-24** [comment]
Mmmh. C'est peut être issus d'un test de la part d'un dev qui a demandé de rajouter spécialement ça pour pouvoir jouer, et je m'excite pour rien. Ping @artragis ?

**Comment by gllmc** [comment]
Ce sont les groupes qui ont la permission `utils.change_hat` qui peuvent modifier les casquettes. J'ai demandé à @vhf de mettre ce droit au groupe `devs` sur la bêta pour pouvoir jouer. Pas de problème, donc. :)
