### ISSUE TITLE
La page de documentation de l'API est moins stylée qu'avant

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4556]
Navigateur: Firefox 52
OS : Windows

Sur la prod le fait que ce soit centré est plus joli je trouve.

### La page de doc de l'API sur la prod : 

![doc-api-prod](https://user-images.githubusercontent.com/6066015/29520638-37e0d688-8682-11e7-87ac-aa400567143a.PNG)

### La page de doc de l'API sur la beta

![doc-api](https://user-images.githubusercontent.com/6066015/29520600-fefcd7ae-8681-11e7-813b-93a98b6a199f.PNG)

**Comment by artragis** [comment]
pour info, voici la différence de style: 

quand c'est ok: 
![image](https://user-images.githubusercontent.com/1523653/29863302-884b93bc-8d6f-11e7-80b2-aa48377b9626.png)

quand c'est pas ok
![image](https://user-images.githubusercontent.com/1523653/29863322-9b890996-8d6f-11e7-8e20-90cc14538e01.png)


c'est une question de flex
