### ISSUE TITLE
[v25][beta] Une ligne blanche de pixel est apparue sur la page d'accueil

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4559]
Navigateur : Firefox52
OS : Windows

Image : 

![pixel-cache](https://user-images.githubusercontent.com/6066015/29521615-83fed0a2-8686-11e7-95a2-78d920d33c97.png)

Il y a une ligne blanche qui se situe entre la ligne orange et le le bouton "Tous les ..." qui fait un effet détaché que je trouve moins esthétique que ce que l'on a en prod aujourd'hui.

**Comment by motet-a** [comment]
Je crois que c’est dû à [ça](https://github.com/zestedesavoir/zds-site/commit/d9794b1ab2d855e24bd3013befcfd4928508a8c8#diff-3a105891d031d363e91c0046610e7700R60).
