### ISSUE TITLE
Ajouter une baseline "aléatoire"

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#456]
Ajouter une baseline, qui sortirait des jeux de mots avec Zeste.

Exemples :
- Zeste de Savoir, la connaissance sans pépins
- La connaissance, en français dans le zeste
- Partagez vos connaissances via notre traitement de zeste
- C'est le zeste qui sauve
- Sortez vos cahiers de zeste
- Un concentré de connaissances, sans ajout ni conservateur, sans zeste déplacé
- Faites un zeste envers votre prochain
- Ici, vous êtes libres de vos faits et zestes
- ZdS c'est la classe, tu peux pas zeste

(Je compte sur vous pour allonger la liste)

**Comment by Alex-D** [comment]
J'aime bien cette idée !

Faudra que je l'intègre au design par contre, mais j'ai déjà ma petite idée !

**Comment by SpaceFox** [comment]
Corrigé et mergé (merge #458 ) --> fermé.
