### ISSUE TITLE
[v25][beta] Impossible de trouver un billet sur la beta

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4560]
Je suis a la recherche du billet intitulé "une introduction aux fanfictions". Et pour celà je tape dans la recherche de la page d'accueil ["fanfiction"](https://beta.zestedesavoir.com/rechercher/?q=fanfiction&category=&subcategory=).

Je ne retrouve pas le fameux billet.

Si je fais la même [recherche sur la page d'accueil de la prod](https://zestedesavoir.com/rechercher/?q=fanfiction), j'ai des résultats.

**Comment by pierre-24** [comment]
Bon, ce serait pas plutôt un oubli (ou un bug) dans l'indexation ? Parce que ça me semble bizarre, objectivement.

Ping @artragis !

**Comment by pierre-24** [comment]
Mmh. partons sur [un bug](https://sentry.sandhose.fr/zeste-de-savoir/beta-backend/issues/919/), y'a Sentry qui dit que le code est pas content.

**Comment by pierre-24** [comment]
Encore que c'est récurent, et présent depuis longtemps. Y'aurait moyen de faire un `python manage.py index-all` ?

**Comment by artragis** [comment]
c'est clairement un pb d'indexation après un sync.
