### ISSUE TITLE
Un utilisateur peut poster deux fois de suite sur le même topic

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4569]
En parcourant la beta, je suis tombé sur [ce double message](https://beta.zestedesavoir.com/forums/sujet/6152/suivi-de-lassociation/?page=2#p160185) de @gcodeur 

Je ne sais pas comment il a réussi a poster ça, mais le fait est que ça semble possible au vu des résultats.

**Comment by gllmc** [comment]
J'étais sur un très mauvais réseau en postant ça, donc je suppose que la requête a été envoyée deux fois quasiment au même moment, ce qui fait que le test est passé deux fois.

**Comment by motet-a** [comment]
Ouais mais ça devrait être atomique et rejeter la deuxième requête, non ?

**Comment by firm1** [comment]
> ça devrait être atomique et rejeter la deuxième requête, non ?

oui

**Comment by gllmc** [comment]
En effet. Par contre, ce n'est pas lié à la v25 du coup. ^^

**Comment by motet-a** [comment]
Je viens de faire un essai à l’instant sur la beta, j’ai envoyé deux requêtes pour créer un message quasiment au même moment avec un petit script. La première est passée et j’ai eu une belle 500 sur la seconde.

C’était un POST vers `https://beta.zestedesavoir.com/forums/message/nouveau/?sujet=9161`.

**Comment by pierre-24** [comment]
Pour ceux qui y ont accès, [c'est probablement celle là](https://sentry.sandhose.fr/zeste-de-savoir/beta-backend/issues/1022/). 

``OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')``

À tes souhaits :)

**Comment by artragis** [comment]
encore d'actu?

**Comment by Situphen** [comment]
Je ne vois que deux occurrences de `(1213, 'Deadlock found when trying to get lock; try restarting transaction')` sur Sentry. Ça m'a l'air très peu courant donc pour moi on peut fermer.
