### ISSUE TITLE
[v25][beta] une recherche dans la bibliothèque nous fait trouver des éléments qui n'y sont pas

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4570]
Je vais dans la [bibliothèque](https://beta.zestedesavoir.com/bibliotheque/) (des contenus validés donc) et je saisi dans la recherche le terme "st honoré".

J'ai le malheur de voir afficher un billet (un contenu non validé) qui ne fait pas partie de la bibliothèque normalement.

**Comment by pierre-24** [comment]
En effet, "content" ne fait pas la différences entre contenus publiés ou pas. Mmh. Ça va pas être marrant à régler, il va falloir rajouter un truc [par là](https://github.com/zestedesavoir/zds-site/blob/dev/zds/searchv2/views.py#L170).

**Comment by gllmc** [comment]
Fixé par #4604.
