### ISSUE TITLE
[v25][beta] Certaines sous-catégories sont affichées même si on y trouve aucune publication

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4571]
En allant dans la bibliothèque, dans la [catégorie des SHS](https://beta.zestedesavoir.com/bibliotheque/sciences-humaines-et-sociales/) je constate que dans la liste des catégories affichées en bas, il y a la catégorie langue, qui ne contient pourtant aucune publication.

![langue-vide](https://user-images.githubusercontent.com/6066015/29565254-7b703eac-8745-11e7-8e8e-9decbd6d492b.PNG)

On ne devrait pas afficher les catégories sans contenu (c'est du bruit pour la navigation). Il faudrait se baser sur le même méthode de sélection que celle du menu de la topbar qui lui contient les bonnes catégories.

**Comment by pierre-24** [comment]
Pour le coup, je trouve que ça se discute. Autant pour le dropdown, y'a une optique de place (trop long dropdown = pas pratique sur petit écran), autant ici je trouve ça moins grave. Mais c'est mon avis.

**Comment by firm1** [comment]
Disons que j'ai du mal à voir l'utilité d'afficher une catégorie vide.

Pour celui qui cherche un contenu, il n'y verra que déception lorsqu'il cliquera dessus. Sans compter le fait que ça surcharge la page avec du bruit.

**Comment by artragis** [comment]
à fixer mais pas prioritaire, si on y arrive avant la release finale tant mieux, sinon on verra après.

**Comment by artragis** [comment]
pas réussi à gérer ça pour l'instant, dsl
