### ISSUE TITLE
[v25][beta] L'estimation du temps de lecture d'un chapitre est fausse

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4573]
Si on consulte le chapitre suivant : [Conteneurs](https://beta.zestedesavoir.com/tutoriels/954/notions-de-python-avancees/1-starters/1-containers/), le temps de lecture est estimé à moins d'une minute. Et on sait bien que c'est impossible de le lire en moins d'une minute.

L'information affichée est donc erronée. Je tag v25 parce que sur la v24 (prod) on affichait pas l'info dans les chapitres. Il vaut mieux ne rien afficher, que d'afficher une information fausse. L'idéal étant d'afficher la vrai info.

**Comment by A-312** [comment]
https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/includes/tags_authors.part.html#L79

readtime doit renvoyer nul ici.
