### ISSUE TITLE
Interdire 1 000 000 (un million) de mots de passe trop communs ?

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#4579]
Je ne sais pas si c'est vraiment une bonne idée, mais en tous cas on peut : https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/10_million_password_list_top_1000000.txt

**Comment by motet-a** [comment]
*(J’ai édité le titre parce qu’il n’y a que le top 1 million de mot de passe trop communs dans cette liste, c’est déjà pas mal :upside_down_face:)*

**Comment by nils-van-zuijlen** [comment]
Ça devrait pouvoir se faire assez simplement comme Django à déjà une fonctionnalité d'interdiction de certains mots de passe.
Malheureusement je n'ai pas les compétences pour le faire moi-même actuellement

**Comment by artragis** [comment]
je me permet de réserver, ça sera sujet à un petit livestream je pense.

**Comment by A-312** [comment]
Pense à prévenir suffisamment tôt si tu fais un stream. :)

**Comment by WhyCannotIPostAnonymously** [comment]
Est-ce que ce sera rétroactif ? (Moi je suis contre, mon mot de passe est dans cette liste… ;) )

**Comment by AmarOk1412** [comment]
@WhyCannotIPostAnonymously nop, sauf si tu veux changer de mot de passe logiquement.

Par contre je t'encourage pour le coup à le changer où d'utiliser un gestionnaire de mot de passe.

**Comment by A-312** [comment]
_avion_ y est 😢 Je pensais que c'était un super mot de passe. Je vais rajouter *312*, il sera plus compliquer comme ça 😀 

Ce ne sera pas long de vérifier tout ça ?

**Comment by motet-a** [comment]
> Ce ne sera pas long de vérifier tout ça ?

On peut vérifier si un texte est inclus dans une liste de *n* éléments avec un temps qui se rapproche plus de *O(1)* que de *O(n)* si la liste est indexée correctement (par exemple avec une *hash table* : https://en.wikipedia.org/wiki/Hash_table).

**Comment by nils-van-zuijlen** [comment]
Je pense qu'il faudrait implémenter #4300 avant, ça rendra l’implémentation de ce filtre plus facile.
Il ne faut pas que ce soit rétroactif, cependant, je pense qu'il devrait être possible de vérifier la sécurité des mots de passe des membres lors de leur connexion et de leur proposer de changer de mot de passe si besoin.

**Comment by motet-a** [comment]
Hey, pas si vite. Il y a beaucoup de choses à dire dans ce thread. Sur IRC, les gens ont pas mal disserté dessus. Je vais essayer d’en faire un résumé rapide.

Déjà, qu’est-ce qu’un mot de passe fort ? Si tout le monde a le même mot de passe “fort”, alors ce mot de passe devient “faible”. Peut-on donc lister les mots de passe forts ?

Ensuite, on peut très bien mettre un indication de force du mot de passe côté client, sur les formulaires d’inscription et de changement de mot de passe. Ça ne contraint pas, mais ça peut suffire pour informer l’utilisateur des risques et périls d’un mot de passe trop simple. 

Et enfin, contraindre la force du mot de passe pourrait peut-être nuire a certains nouveaux arrivants. Il peut être légitime d’utiliser un mot de passe bidon pour un compte bidon.

**Comment by nils-van-zuijlen** [comment]
> Peut-on lister les mots de passe forts ?

Non, c'est d'ailleurs une de leurs caractéristiques. Il est proposé d'utiliser une liste de mots de passe connus pour être faibles, afin de les interdire dans un souci de sécurité.

Je pense qu'une indication de la force du mot de passe serait la bienvenue dans le front, mais qu'elle ne serait pas suffisante pour s'assurer de la sécurité des comptes.

Enfin, il me semble qu'il vaut mieux ne pas créer de compte que créer un compte bidon. En effet, ces comptes bidons encombrent la base de données puisqu'ils ne sont utilisés qu'une seule fois. Il faudrait plutôt permettre aux "invités" ou "anonymes" de pouvoir poster des messages sur les forums.

**Comment by motet-a** [comment]
>> Peut-on lister les mots de passe forts ?
> Non, c'est d'ailleurs une de leurs caractéristiques. Il est proposé d'utiliser une liste de mots de passe connus pour être faibles, afin de les interdire dans un souci de sécurité.

Oups, je voulais plutôt dire “peut-on lister les mots de passes faibles” :upside_down_face: 

> Je pense qu'une indication de la force du mot de passe serait la bienvenue dans le front, mais qu'elle ne serait pas suffisante pour s'assurer de la sécurité des comptes.

Pourquoi ? Si Monsieur Dupont a un mot de passe faible, c’est plus son problème que le nôtre. Dans le pire des cas où il se fera piquer son compte, si il ne réinitialise pas son email, le voleur va poster des choses pas bien sur ZdS, se faire bannir¹ et lui piquer un autre compte d’un autre site sur lequel il aura utilisé le même mot de passe.

Je peux très bien mettre un mot de passe fort comme `oiquaemauw4oop9quoo7` qui passe les vérifications du backend, le laisser traîner n’importe où par mégarde et me faire piquer mon compte. Je peux aussi mettre un mot de passe faible comme `bateau` et ne pas me faire piquer mon compte parce que personne n’est intéressé par un compte quasiment vide n’ayant servi que pour trois messages sur le forum auxquels je ne tiens pas vraiment (ben oui, trouver des mots de passe par force brute ça prend des ressources, et donc de l’argent, tout le monde n’a pas que ça à faire — sans parler des systèmes à la fail2ban qui sont terriblement efficaces contre ça).

> En effet, ces comptes bidons encombrent la base de données puisqu'ils ne sont utilisés qu'une seule fois.

Il faudrait que quelqu’un qui touche à l’infrastructure le confirme, mais la place disque ne coûte plus grand-chose aujourd’hui. Le plus cher, c’est de loin les traitements des données. Puis la table des utilisateurs est petite (9K lignes) par rapport à d’autres comme celle des posts (150K lignes) par exemple.

¹ : Je pense qu’un individu malveillant a beaucoup plus vite fait de se créer un compte bidon que de piquer un compte existant

**Comment by A-312** [comment]
Par contre, il ne faut pas oublier que cette liste est principalement créé par des anglophones (pour ce que j'ai pu survoler).

**Comment by artragis** [comment]
Je pense que ça va être un won't fix, non?
