### ISSUE TITLE
Utiliser des espaces insécables dans les templates

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4584]
Parce que ça, c’est moche : 

![image](https://user-images.githubusercontent.com/15378830/29739820-ab73a6f2-8a47-11e7-9b0a-9ac3123939bd.png)

**Comment by vhf** [comment]
Tout ce qui passe par le markdown est déjà et sera encore ok de ce côté. Là je suppose que c'est du contenu qui passe par là… :(

**Comment by motet-a** [comment]
Oui, carrément. Je sais bien que tu as fait du bon travail avec zmarkdown :upside_down_face: 

C’est les templates qui posent problèmes.

**Comment by vhf** [comment]
Est-ce qu'on peut pas déjà passer les strings qui sont injectées dans ce template par le filtre markdown ? `foo|emarkdown` ou un truc du genre. Ça devrait résoudre le problème

**Comment by motet-a** [comment]
Je sais pas. Mais on devrait pourvoir le faire avec `sed` vu que `grep -r ' :' templates` et `grep -r ' ;' templates/` m’ont l’air de trouver ce qu’il ne va pas de manière très efficace.

**Comment by vhf** [comment]
Aaah je comprends mieux ce que tu veux dire. C'est des strings dans le code, pas du texte en base de donnée.

Dans ce cas oui. Je pense que tu peux faire une bonne regex en prenant que ce qui est dans les strings i18n, tout remplacer, et `git add --patch` pour ajouter que ce qui est ok. 👍
