### ISSUE TITLE
Utiliser des apostrophe typographiques dans les templates

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4585]
Constatez : `egrep -r "[[:alpha:]]'[[:alpha:]]" templates/`

Je pense qu’il faudrait faire une PR séparée pour le dossier `templates/pages/` parce qu’il y en a vraiment beaucoup dedans, et c’est un coup à faire pleins de conflits.

**Comment by rezemika** [comment]
Les deux PR ont été mergées, je pense qu'on peut fermer le ticket ?

**Comment by gllmc** [comment]
Tout à fait :)

**Comment by artragis** [comment]
pas vraiment, il en reste encore à merger.

**Comment by gllmc** [comment]
De quelle PR parles-tu @artragis ?

**Comment by artragis** [comment]
me suis trompé, j'ai supprimé mon commentaire :p

**Comment by gllmc** [comment]
Ah, j'avais pas vu car GH charge les commentaires en temps réel, mais pas les suppressions de commentaires, désolé :p
