### ISSUE TITLE
[beta][v25] L'icone de création d'un nouveau message n'est pas alignée/centrée

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4587]
Os : Android
Navigateur : Chrome 59

Contrairement a l'affichage en prod, l'icone de création d'un nouveau message en beta n'est plus centrée corrzctement.

### Capturr de la beta

![screenshot_20170828-101244](https://user-images.githubusercontent.com/6066015/29765135-44ab6d62-8bda-11e7-8c47-a81dffec06fc.png)

### Capture de la production

![screenshot_20170828-101253](https://user-images.githubusercontent.com/6066015/29765162-5690db8e-8bda-11e7-934f-1ab7948628f0.png)

**Comment by abdelaz3r** [comment]
Je viens de proposer une PR
