### ISSUE TITLE
Poster des messages sur les forums sans compte 

### ISSUE THREAD

**Issue by nils-van-zuijlen** [zestedesavoir/zds-site#4598]
Dans le ticket #4579 est sortie l'idée des comptes bidons.

Afin de simplifier la procédure de post de message et d'alléger la BdD de ces comptes à usage unique, je propose qu'il soit possible aux utilisateurs anonymes de poster des messages dans les forums, voire de créer des discussions dans ces derniers.

J'ai pensé à un formulaire à l'image de ceux de [PlanetCasio](http://www.planet-casio.com/Fr/forums/topic14939-1-Ameliore-ta-Graph-25+-Pro-E-meme-en-mode-examen.html).

**Comment by motet-a** [comment]
(Bon, les captchas du genre *« Résultat en chiffres de sept plus cinq : »* sont terriblement inefficaces)

**Comment by nils-van-zuijlen** [comment]
Je ne parlais pas du type de captcha, mais des informations demandées. Par
exemple, un utilisateur anonyme peut quand même utiliser un pseudo si il
n'est pas déjà utilisé, et son adresse mail est comparée à celles des
membres.

>

-- 
Nils Van Zuijlen



Hey, give me a click <http://justclick.re/> bro!

**Comment by gllmc** [comment]
@nils-van-zuijlen : l'ajout d'une telle fonctionnalité est loin d'être un point de détail et cela doit être discuté sur le forum. Je t'invite à créer un sujet dans le forum [bugs et suggestions](https://zestedesavoir.com/forums/communaute/bug-suggestions/) pour en parler. Je ne suis personnellement pas sûr que ce soit une bonne idée.
