### ISSUE TITLE
Our emails go into spam

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#46]
Il s'agit probablement d'un problème d'entêtes de nos emails, ou du fait que les emails soient formés de la même façon, ou encore parce que zds n'est pas très connus. Mais quelque soit la cause, ce qui est certains c'est que les emails envoyés par ZdS vont directement dans les spams.

De mon coté, ça m'est arrivé au bout du 3e mails pour me prévenir de l'arrivée d'un MP.

S'il y'a un spécialiste du mailing dans la salle, ce serait cool d'avoir une piste de résolution de ce problème.

**Comment by GerardPaligot** [comment]
J'ai demandé à mon coloc administrateur système s'il avait une idée pour ce problème. Il aurait peut-être une piste pour nous.

A première vue, il existe quelques organismes (comme [Spamhaus](http://www.spamhaus.org/sbl/)) qui maintiennent une black list des domaines pour les adresses e-mail. A partir d'un certains nombres d'e-mail délivrés plus ou moins rapidement dans le temps, du contenu identique entre ces mails ou d'en-têtes mal formés, ils les bloqueraient.

La procédure pour être dé-blacklisté est potentiellement lourde et, comme le processus de blacklist est automatique, ça n'enlève pas les risques de se refaire blacklisté à l'avenir. C'est pourquoi, c'est mieux d'utiliser des SMTP existants, reconnus par ces organismes comme Orange, OVH, SFR, Google et beaucoup d'autres. Il faut quand même faire attention aux filtres internes de ces solutions. Par exemple, le SMTP d'Orange est plus permissif que celui de Google.

La boite de mon coloc utiliserait un serveur de mail. Je lui ai demandé de se renseigner un peu plus mais c'est déjà un élément de réponse.

**Comment by SpaceFox** [comment]
De mémoire, y'a aussi une histoire d'enregistrements MX pour le domaine...
je ne sais plus exactement quoi, y'a un truc à creuser.

**Comment by geoffreyc** [comment]
Deja est-ce que les records SPF et DKIM sont bien paramétrés? d'apres
mxtoolbox ils ne le sont pas.

2014/1/8 SpaceFox notifications@github.com

> De mémoire, y'a aussi une histoire d'enregistrements MX pour le domaine...
> je ne sais plus exactement quoi, y'a un truc à creuser.
>

**Comment by firm1** [comment]
Les bonnes pratiques pour les mails, il y'en a des tonnes et des tonnes. Le MX n'est pas enregistré, les records SPF, DKIM non plus, et c'est possible de s'en sortir sans passer forcément par un tiers.

Mais, ce qui serait cool, c'est que quelqu'un s'en charge vraiment (et ça ne sera pas moi). ^^

**Comment by geoffreyc** [comment]
J'ai quelquea notions la dedans, donc si personne se porte volontaire je
pourrais éventuellement m'en charger. Mais bien sur si il a des experts la
dessus, je laisse la place.

2014/1/9 firm1 notifications@github.com

**Comment by cgabard** [comment]
Il nous faut un admin sys, c'est probablement le dernier poste clé dont personne ne s'occupait vraiment donc fais toi plaisir :)

**Comment by firm1** [comment]
> J'ai quelquea notions la dedans, donc si personne se porte volontaire je
> pourrais éventuellement m'en charger. Mais bien sur si il a des experts la
> dessus, je laisse la place.

Les experts n'existe que dans les film. :P

Concrètement, tu aurais besoin de quoi pour t'occuper de configurer le serveur ?

**Comment by cgabard** [comment]
> Les experts n'existe que dans les film. :P 

Dans les séries aussi

**Comment by geoffreyc** [comment]
Essentiellement d'un utilisateur avec les droits root (je suppose que le
serveur utilise sudo?). Quelle est la config du serveur actuelle ? (distro,
server mail, etc.)

2014/1/10 firm1 notifications@github.com

**Comment by firm1** [comment]
Adresse IP : 176.31.187.88
utilisateur : zds
mot de passe (à décoder en base64) : MTc2emVzdGU=
OS : Debian Wheezy
Serveur HTTP : Nginx
Serveur WSGI : Gunicorn
Serveur SMTP : Postfix
Base de donnée : PostgreSQL

Certains services (gunicorn et solr) sont contrôlés par supervisor, et il y'a quelques cron tab (indexation solr toutes les 30 min) paramétrés.

Autre chose ?

**Comment by geoffreyc** [comment]
C'est voulu que le DNS soit geré par OVH plutôt que directement sur le
serveur? Ou c'est une solution temporaire?
Pour commencer a paramétrer les mails j'aurais besoin d'avoir accès au
règlements des records DNS, ducoup soit il faut que j'installe BIND, soit
il me faudrait accès au panel OVH.

2014/1/10 firm1 notifications@github.com

**Comment by firm1** [comment]
> C'est voulu que le DNS soit geré par OVH plutôt que directement sur le
> serveur? Ou c'est une solution temporaire?

Pour le moment je ne vois que des inconvénients au fait de gérer les DNS sur le serveur. Mais s'il y'a des avantages, je suis tout ouïe.

Pour le Panel OVH faudra voir avec zingwai, c'est lié à des infos perso qu'on ne peut pas diffuser ici.

**Comment by geoffreyc** [comment]
Ouai non pas vraiment d'avantages, c’était vraiment pour savoir ou je
devrais faire mes modifs ;)

Je me tournerais vers zingwai donc !

2014/1/15 firm1 notifications@github.com

**Comment by geoffreyc** [comment]
DNS record a ajouter (DKIM):
mail._domainkey.zestedesavoir.com IN TXT "v=DKIM1; h=rsa-sha256; k=rsa;
p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDBBEXhlL7re7x3ISWdJ+9VOnnxYs4yKehCSuo0jTNmsjI9MmNd8pNUWckfI1mT5vucc66lC5OM3Swjpd5WMUkIVG+AKJ3a9Q5CDtmVvv38bAuedt6mcT01cKGzUCXX86Y9WZR72JkcgxgEhfruYgKW20n0exbWD+GOOD43nTPfWQIDAQAB"
;

2014/1/15 geoffrey compagnon speedking34@gmail.com

**Comment by geoffreyc** [comment]
DNS record a ajouter (SPF):
zestedesavoir.com.  IN TXT "v=spf1 mx a ptr ip4:176.31.187.88 ~all"

2014/1/15 geoffrey compagnon speedking34@gmail.com

**Comment by geoffreyc** [comment]
Il faudrait aussi changer les MX record en les pointant vers
zestedesavoir.com

2014/1/15 geoffrey compagnon speedking34@gmail.com

**Comment by firm1** [comment]
> DNS record a ajouter (DKIM):

Error : **Invalid subfield found in DKIM : h=rsa-sha256**

**Comment by firm1** [comment]
> DNS record a ajouter (SPF):

Check

Pour le reste, je te laisse t'en occuper

**Comment by geoffreyc** [comment]
En l'ajoutant en tant que TXT plutot que l'option DKIM de OVH ca devrait
passer ;)

**Comment by firm1** [comment]
D’où le "Pour le reste, je te laisse t'en occuper" :')

**Comment by geoffreyc** [comment]
Ca attendra zingwai alors :D

2014/1/15 firm1 notifications@github.com

**Comment by geoffreyc** [comment]
Note to self:
Google recoit les mail de zestedesavoir en IPv6, il faut rajouter
ip6:2001:41d0:52:100::/64 au SPF

2014/1/15 geoffrey compagnon speedking34@gmail.com

**Comment by geoffreyc** [comment]
BTW j'ai envoyé un email a zingwai, 'cest bien ca? zingwai@gmail.com

2014/1/15 geoffrey compagnon speedking34@gmail.com

**Comment by firm1** [comment]
Ce n'est pas le même email que j'ai. Mais patiente, c'est un homme très occupé, donc, faut patienter.

**Comment by geoffreyc** [comment]
Ah bah le system de creation de record SPF d'OVH
 ne permet pas d'ajouter des IPv6, et quand on essai d'ajouter le record
manuellement en TXT, ils l’empêche en nous forçant a passer par leur
generateur, genial !

2014/1/15 firm1 notifications@github.com

**Comment by geoffreyc** [comment]
Comment est paramétré le script d'envoi de mail pour l'app django? Les
mails envoyés directement via le terminal sont signés (dkim) mais les mails
venant du site ne le sont pas?

2014/1/15 geoffrey compagnon speedking34@gmail.com

**Comment by cgabard** [comment]
Quelqu'un a changé (retiré?) les droits à l'utilisateur qui execute le site ?

Le site est actuellement HS et, vu l'erreur, je mise sur un prob de droits

**Comment by geoffreyc** [comment]
Rien touché par rapport a ça personnellement. Le site etait toujours UP
quand j'ai arreté mes tests hier soir.

2014/1/16 Christophe Gabard notifications@github.com

**Comment by geoffreyc** [comment]
2014/01/16 10:46:23 [error] 1546#0: *4 connect() failed (111: Connection
refused) while connecting to upstream, client: 31.33.91.95, server:
zestedesavoir.com, request: "GET / HTTP/1.1", upstream: "
http://176.31.187.88:8001/", host: "zestedesavoir.com"

Nginx arrive pas a se connecter au serveur qui fait tourner l'app django je
suppose?

2014/1/16 geoffrey compagnon speedking34@gmail.com

**Comment by geoffreyc** [comment]
fixed, gunicorn etait offline

2014/1/16 geoffrey compagnon speedking34@gmail.com

**Comment by firm1** [comment]
J'ignore ce qui s'est passé sur le serveur, mais je viens de relancer gunicorn et ça va mieux.

Évitons de faire des config douteuses sur le serveur quand même.

**Comment by geoffreyc** [comment]
Ca avait rebuggé apres que je le relance ya 10 minutes?

2014/1/16 firm1 notifications@github.com

**Comment by geoffreyc** [comment]
gunicorn a eu l'air d'arreter de fonctionner vers 10h30, quelqu'un faisait
quelque chose a ce moment la?

2014/1/16 geoffrey compagnon speedking34@gmail.com

**Comment by firm1** [comment]
Je l'ai relancé 2 minute après toi. Mais avant, il était down a cause de trop d'erreur concernant le nombre de cpus.

Bref, problème réglé, mais vaut mieux prévénir si tu fais des modifs sur le serveur.

**Comment by geoffreyc** [comment]
J'ai rien touché qui aurait pu avoir un impact la dessus, tout ce que j'ai
changé c'est le .conf de postfix et installé opendkim.

2014/1/16 firm1 notifications@github.com
