### ISSUE TITLE
Ouvrir les astuces de l’éditeur dans des nouvelles fenêtres

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4607]
Quand l’utilisateur va cliquer sur “Envie d’en savoir plus ?” : 

![image](https://user-images.githubusercontent.com/15378830/29977514-e8a1278e-8f3d-11e7-9f72-974e4fff6cad.png)

…il peut avoir écrit du texte dans l’éditeur. Perdre ce texte peut être frustrant (certains navigateurs peuvent retrouver les contenus des formulaires quand on revient à une page précédente mais bof), je pense donc qu’il vaut mieux ouvrir la page d’aide dans un nouvel onglet.

**Comment by AmarOk1412** [comment]
Perso je suis contre forcer le fait d'ouvrir un lien dans un nouvel onglet. Les sites ne devraient pas faire ça, c'est à l'utilisateur de décider si il ouvre le lien dans un nouvel onglet (il a les options pour entre clic droit=>ouvrir dans un nouvel onglet/fenetre, ctrl-clic, etc).

Au pire des cas, une boite de warning pour confirmer, mais je pense que c'est pas nécessaire ici.

**Comment by motet-a** [comment]
Perso, je suis aussi généralement contre le fait d’ouvrir les liens dans des nouveaux onglets. Mais pour moi, ici c’est une exception justifiée : L’utilisateur peut très bien oublier d’ouvrir “manuellement” le lien dans un nouvel onglet et perdre son texte.

D’ailleurs, GitHub se comporte de la même manière avec ce lien en dessous de l’éditeur : 

![image](https://user-images.githubusercontent.com/15378830/29993104-abe49ebe-8fad-11e7-89d9-32d831c3fefd.png)

**Comment by motet-a** [comment]
(D’ailleurs, ouvrir des liens dans de nouvelles fenêtres peut ouvrir des failles de sécurité vu que par défaut, la fenêtre ouverte a accès à l’objet `window` de la fenêtre ouvrante et peut scrapper la page autant qu’elle veut)

**Comment by artragis** [comment]
Cosidérant qu'on a trop de choses à faire et que les principaux développeurs front sont contre, je ferme.
