### ISSUE TITLE
Readme : installation Windows

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#461]
Je mets ici les remarques liées au mode d'emploi d'installation du projet, vu que je refais une installation propre sur une autre machine.

Pour commencer : il faudrait retirer le lien vers le .msi de python : je suis sur une archi x64 et donc le .msi linké ne fonctionne pas.

---

En cours d'expérimentation, donc à prendre avec des pincettes...

Globalement, il faudrait changer le git clone pour la ligne suivante :

```
git clone https://github.com/Taluu/ZesteDeSavoir.git
```

pour 

```
git clone https://github.com/Taluu/ZesteDeSavoir.git --depth 1
```

Ca permet de ne télécharger que le dernier commit sans se taper tout l'historique en local.

**Comment by SpaceFox** [comment]
> Pour commencer : il faudrait retirer le lien vers le .msi de python : je suis sur une archi x64 et donc le .msi linké ne fonctionne pas.

Je suis sur une archi x64 et le .msi linké a marché sans aucun problème.

> Ca permet de ne télécharger que le dernier commit sans se taper tout l'historique en local.

Ben non : c'est intéressant d'avoir l'historique local, et après vérification, ça ne prends pas tant de place que ça (désolé @Taluu , je pensais vraiment dans l'autre message que c'était énorme, alor qu'en fait on est à moins de 100 Mo, soit moins de x2 sur le code de la branche courante).

**Comment by SpaceFox** [comment]
PS : par contre pour Python on devrait sans doute renvoyer vers la dernière 2.7 et non vers une version mineure précise.

**Comment by Alex-D** [comment]
Juste lier cette page là : https://www.python.org/download/releases/2.7.6/

Et pour donner un ordre d'idée, chez mes parents je n'arrive pas à cloner le dépôt complet, j'ai timeout après 1h de DL... alors je peux t'assurer que passer de 100+ Mo à 15-20Mo je dis oui.

On peut éventuellement le proposer à la limite. Mais bon, pas sûr que ce soit utile pour un dév de cloner toutes les branches s'il veut juste faire un fix. Pareil pour l'historique.

**Comment by Alex-D** [comment]
Ou celle là : https://www.python.org/download/releases/2.7/

**Comment by SpaceFox** [comment]
Pourquoi pas proposer l'option pour les devs qui ont une connexion lente ? Mais AMHA ce devrait être une _option_ qui ne dépend _pas_ de l'OS (i.e. une indication quelque part dans la doc).

D'autant plus que cette ligne est très liée à ton client Git ; si tu as Eclipse ou SourceTree (que je conseille sur Windows ou Mac OS d'ailleurs), tu téléchargeras par défaut tout le dépôt, ce qui est le comportement par défaut de Git.

**Comment by Alex-D** [comment]
Oui oui, complètement d'accord sur le fait que ça n'est pas lié à l'OS, mais flemme de faire une issue séparée.

Sinon en effet le comportement par défaut est de tout cloner, mais c'est plutôt lourd je trouve.

Mon client git : git dans la console. Sinon, Github Windows. Ou sinon, ungit.

**Comment by Alex-D** [comment]
Bon, j'ai tout réussi... si on ne prends pas en compte ma connexion qui va à 50kbps ça a été vite.

Du coup, la seule modif à apporter est le fameux .msi : la page de DL plutôt que le lien direct.

Je suis pour proposer aux futurs contributeurs la commande avec le --depth car ça marche bien si on a besoin que d'une branche ou deux, et en l’occurrence quand on patch un bug, pas besoin de cloner tout le projet. Maintenant si vous me dites que tout le monde utilise des outils qui clonent de toute façon tout le projet, alors il n'est pas utile de l'indiquer.

**Comment by SpaceFox** [comment]
Voilà, c'est fait.
