### ISSUE TITLE
On est redirigé vers la bibliothèque si on clique sur la catégorie d'un billet

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4611]
NB : le bug est aussi présent en prod d'où le non-tag "v25".

Lorsque je vais sur un billet ([celui-ci par exemple](https://beta.zestedesavoir.com/billets/1959/considerations-sur-le-domain-sharding/)) et que je clique sur sa catégorie "Développement Web", je suis redirigé vers les contenus de la bibliothèque.

Ce qui est incompatible avec le besoin d'isolation entre les contenus validés et les contenus non validés.

**Comment by A-312** [comment]
Je pense qu'il faudrait corriger la #4409 dans la foulée.
