### ISSUE TITLE
[v25][beta] Impossible de trouver un billet depuis la recherche

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4613]
Je cherche le terme "[lymphome](https://beta.zestedesavoir.com/rechercher/?q=Lymphome&category=&subcategory=&from_library=)" depuis la page d'accueil du site, je ne trouve pas la serie de billet de gabbro.

J'ignore si on est sur l'un des problème suivant : 

- en corrigeant le ticket #4570 , la PR a du casser la recherche dans les billets
- le ticket #4560 : qui semble être récurrent à chaque synchro de la base prod <-> beta

Dans le doute je crée un nouveau ticket.

**Comment by artragis** [comment]
> le ticket #4560 : qui semble être récurrent à chaque synchro de la base prod <-> beta

oui et c'est normal.

**Comment by firm1** [comment]
> oui et c'est normal.

Du coup si c'est aussi la cause de ce bug, tu peux fermer. Mais ça serait pas mal de faire une réindexation a chaque mise en beta pour m'éviter de vous déclarer des bugs de ce genre à chaque fois. Sinon ça biaise les tests

**Comment by artragis** [comment]
faut regarder mais c'est possible que #4570 a vraiment joué un rôle même si je ne vois pas trop comment pour l'instant.

le pb de la réindexation c'est que si tu réindexe 100% du site à chaque fois ça prend des plombes. mais genre c'est au minimum 30min et ça ne fait qu'augmenter à chaque synchro.

**Comment by motet-a** [comment]
C’est envisageable de faire tourner la bêta sur une infra un peu plus solide pour que la réindexation se passe plus vite (surtout que ça m’a l’air d’être un petit Scaleway actuellement :upside_down_face:) ? Si le site est utilisable pendant l’indexation, ça ne me semble pas idiot.

J’imagine qu’il y a aussi la possibilité de réindexer automatiquement la première nuit après le déployement de la bêta.

**Comment by firm1** [comment]
> le pb de la réindexation c'est que si tu réindexe 100% du site à chaque fois ça prend des plombes.

Oui il ne faut pas faire ça. Mais ça n'a pas grand chose a voir avec notre ticket je pense puisque  les tutos/articles sont indexés mais pas les billets (en sachant que je cherche toujours a chaque fois des billets assez vieux)

**Comment by artragis** [comment]
> je pense puisque les tutos/articles sont indexés mais pas les billets 

nope.

voici l'explication : pour indexer on utiliser un flag en bdd (must_index). Lorsqu'un tuto/article/billet est publié, le flag vaut true, une fois que la routine d'indexation est passée elle vaut false.

lorsqu'on synchro en béta, le flag est donc à false alors que dans l'ES de béta il n'est pas indexé.

**Comment by firm1** [comment]
Je ne suis pas certain d'avoir compris. Ce que je vois en beta c'est que les tutoriels, les articles sont [trouvable par la recheche](https://beta.zestedesavoir.com/rechercher/?q=sarin&category=&subcategory=&from_library=) (donc je suppose qu'il ont été indexés). Par contre je n'arrive a retrouver aucun billet, tout comme c'était aussi le cas avec #4560 .

J'ai donc l'impression qu'il y a un traitement différent entre les billets d'un coté et les articles/tutos de l'autre. Comment tu expliques ça ?

**Comment by artragis** [comment]
> Je ne suis pas certain d'avoir compris. Ce que je vois en beta c'est que les tutoriels, les articles sont trouvable par la recheche (donc je suppose qu'il ont été indexés).

c'est une question de date, s'il n'y a pas eu de NOUVEAU tuto/article entre deux synchro, tu n'auras pas de pb dans la recherche. 
Pour les billets les NOUVEAUX billets depuis la dernières synchro sont toujours présent (il en est de même pour les messages du forum d'ailleurs).

**Comment by firm1** [comment]
Je distingue 2 categorie de billet :

- Les billets qui n'ont pas bougés entre deux synchro prod -> beta
- Les nouvaux billets (ou ceux qui ont été modifié).

Selon ton explication, la premiere catégorie devrait être accessible via la recherche et pas la seconde. Mais justement aucun billet n'est accessible, c'est là que se trouve mon problème.

**Comment by abdelaz3r** [comment]
Je confirme, il y a effectivement des vieux billets (genre juin) qui sont pas indexés.

**Comment by artragis** [comment]
Oui c'est pour ça que ce bug est différent de #4560 à l'époque j'arrivais à trouver certains billets.

**Comment by gllmc** [comment]
Je vois assez mal comment #4604 aurait pu jouer un rôle, d'autant que j'arrivais à trouver des billets en local (j'ai testé avant de proposer la PR). Je pense que ça vaudrait le coup de lancer une réindexation pour voir ce que ça donne.

**Comment by gllmc** [comment]
[Problème résolu](https://beta.zestedesavoir.com/rechercher/?q=lymphome&category=&subcategory=&from_library=) par la réindexation, je ferme. :)
