### ISSUE TITLE
Accès au menu utilisateur depuis une fenêtre étroite

### ISSUE THREAD

**Issue by entwanne** [zestedesavoir/zds-site#4615]
Bonjour,

Je viens de remarquer un léger problème sur la v25, sur de petits écrans (enfin, en l'occurrence, un écran coupé en deux).

Sur la version actuelle comme sur la beta, quand la fenêtre est étroite, l'image de l'avatar en haut à droite disparaît.
Mais sur la v24, il reste la roue crantée pour accéder au menu utilisateur.
Ce n'est plus le cas sur la v25.

![v24.2 à gauche (actuelle), v25-RC3 à droite (beta)](https://zestedesavoir.com/media/galleries/4138/2826203f-3701-4684-9058-35d33dac3cb9.png)

Merci.

**Comment by gllmc** [comment]
La roue crantée sur mobile n'ouvre pas le menu utilisateur, mais est un lien direct vers son profil. ;)
Normalement, ce lien est présent en haut du menu dépliant, et un lien direct vers son profil ne me semble pas aussi important. Je pense qu'il serait plus souhaitable de pouvoir (avec la roue crantée ou l'avatar, peu importe) accéder au menu utilisateur comme sur desktop au lieu de l'avoir tout en bas du menu dépliant. Qu'en penses-tu ? (Mais ce serait plus en v26 du coup.)

**Comment by entwanne** [comment]
Ah, oui, c'est vrai que j'avais déjà constaté cette différence un peu gênante (je trouve), ça m'était sorti de la tête.

Mais, étant donné que techniquement il est possible d'avoir un menu sur petit écran (puisque c'est ce qui est fait avec le menu *sandwich*), je trouve qu'il serait adapté d'avoir un menu dans ce cas aussi.

**Comment by gllmc** [comment]
Par menu *sandwich*, tu entends celui activé par le bouton à gauche du logo ? Si oui, le menu membre est déjà présent en bas de celui-ci.

Je pensais plutôt à remettre la roue crantée, mais au lieu d'ouvrir le profil, elle pourrait afficher le menu membre comme c'est fait sur desktop (et on le vire du menu sandwich dans ce cas).

**Comment by entwanne** [comment]
Oui c'est ce que je voulais dire. Puisqu'il est possible d'afficher un menu (la preuve avec le menu en haut à gauche), autant ajouter aussi le menu utilisateur.

**Comment by A-312** [comment]
J'ai fais le même commentaire sur le forum, le menu utilisateur est manquant sur la v25. 😞

**Comment by A-312** [comment]
Pour corriger cette PR, 2 solutions : 

 - Ajour une roue crantée ;
ou :
 - Maintenir l'affichage de l'avatar.

Je pense que maintenir l'avatar pour garder le menu utilisateur correspond mieux à ce qu'on a actuellement.

**Comment by A-312** [comment]
@artragis je prends (je le fais en janvier)

**Comment by A-312** [comment]
Ah j'ai retrouvé l'issue ! Donc PR : #5251
