### ISSUE TITLE
Cliquer sur le pseudo du membre ayant résolu une alerte la ferme

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4616]
Lorsqu'une alerte est résolue, le nom du modérateur l'ayant résolue est affiché avec un lien vers son profil. Cependant, cliquer sur ce lien n'a pas l'effet attendu et ferme l'alerte à la place.

![Lien causant problème.](https://www.pixenli.com/images/1504/1504722869059687700.png)

**Comment by nils-van-zuijlen** [comment]
C'est dû à la façon dont les alertes sont fermées.
Les liens dans une alerte sont écoutés, leur action normale est annulée et ils ferment l'alerte.
Il faut voir si il n'y a pas une classe qui évite ce mécanisme (évite la sélection pour fermeture de l'alerte).
Si il y en a une, le tag Facile peut être ajouté.
