### ISSUE TITLE
[beta][v25] Cohérence du vocabulaire dans la topbar

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4627]
Sur [ce lien](https://beta.zestedesavoir.com/forums/) dans la topbar, sur la v25 on a décidé de passer "Forums" en "Forum" (au singulier).

Le travail a bien été fait pour les versions PC, mais pour les versions mobiles/tablette, on a oublier de changer le vocabulaire.

### Rendu de la version PC

![big-forum](https://user-images.githubusercontent.com/6066015/30536312-a0a978c0-9c65-11e7-9400-29febaf7c8ce.PNG)

### Rendu de la version mobile

![mini-forum](https://user-images.githubusercontent.com/6066015/30536325-aa131358-9c65-11e7-919f-a3f77d3c0b46.PNG)

**Comment by sandhose** [comment]
C'est aussi présent dans le `<title>` de la page. C'est vite fixé aussi par contre. On fait quoi ?

Exemple:

https://github.com/zestedesavoir/zds-site/blob/65a25baad3115d41c245c3d6b1e52b4c16fe792b/templates/forum/base.html#L10-L18

**Comment by artragis** [comment]
Faut mettre forums partout comme avant.
