### ISSUE TITLE
[beta][v25] Les marges à gauche dans la bibliothèque sont trop grandes

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4633]
Navigateur : Chrome
OS : Android

Attzntion c'est du pixel pzrfect, mais les marges a gauche sont au moins 2 fois plus grand que les marges a droite sur mobile sur ce lien : beta.zestedesavoir.com/bibliotheque/sciences-de-la-nature/

![20170918_190504](https://user-images.githubusercontent.com/6066015/30554415-ba82327a-9ca4-11e7-91b9-e726eecec6e0.png)

**Comment by motet-a** [comment]
Ouais, je trouve qu’il y a d’autres problèmes de marges un peu partout sur le site d’ailleurs.

**Comment by A-312** [comment]
En effet : #4547 et #4459 . C'est le soucis quand on refactorise le CSS.
