### ISSUE TITLE
Créer un TEMPLATE_PACK pour crispy

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#464]
La gestion des formulaire actuellement est relativement calamiteuse du fait qu'elle fait appel à des templates prédéfinies ce qui me permet à peu près 0% de marge niveau customisation du code généré. Le problème actuel est que plusieurs packs sont utilisés, rien n'est vraiment uniformisé, le pack foundation traine encore, etc.

J'ai fait des recherches et il se trouve qu'avec crispy il est possible de créer un TEMPLATE PACK (dans crispy [il y en a 4 par défaut](https://django-crispy-forms.readthedocs.org/en/latest/install.html#template-packs)). Et je ne parle ici que du code python et HTML (SWIG pour être précis) à faire. Le (S)CSS est déjà fait.

Voici un dépôt qui pourra permettre de s'inspirer : https://github.com/sveetch/crispy-forms-foundation

Le concept de ces packs est de créer des types de champs personnalisés du point de vue form-builder (en HTML on inventera rien). Ça permettra de créer des rendus adaptés, par exemple, on pourra avoir un champ de type "Editor" et qui sera chargé de charger une template qui fera un champ avec la classe qui va bien et tout et tout. J'espère que vous voyez tout l'intérêt de coder ce pack personnalisé.

Pour avoir une idée de base de la structure HTML d'un formulaire : http://zds.alex-d.fr/form.html

Il faut créer les types de champ suivants, je me chargerais de finaliser la template, mais si une base peut être faite, ça m'arrangerais :
- Field : regroupement de label et du champ en question, de façon à pouvoir formater ça comme je veux + affichage des erreurs sur les champs si possible ;
- Input : reprendre l'existant, ne pas se casser la tête, juste avoir un template associé ;
- Checkbox ;
- Button : un vrai <button> pas un <input type="submit"> soyons sémantiques jusqu'au bout ;
- Editor : c'est un textarea avec une classe spécifique
- Message : ça englobe l'éditeur, et d'autres trucs (genre l'avatar du membre, etc) il me faut juste un template que je me chargerais de fignoler ;
- Select : reprendre l'existant et me laisser un template ;
- SelectAutoSubmit : un select classique, mais avec une classe particulière et peut-être des autres choses, donc je préfère séparer ;

Si vous rencontrer d'autres types de champs, postez-les ici pour que l'on vérifie qu'ils sont bien utiles et bien employés.

Une fois cela fait : passer à l'issue #465 

Merci d'avance pour l'aide apportée !

**Comment by cgabard** [comment]
Ce ticket et le suivant ne sont plus d'actualités

**Comment by gustavi** [comment]
Alors on ferme !
