### ISSUE TITLE
Problèmes avec la zone de choix des smileys

### ISSUE THREAD

**Issue by Fumble** [zestedesavoir/zds-site#4640]
Quelques problèmes avec la zone de choix des smileys (quand on répond à un sujet du forum):

![smileys](https://user-images.githubusercontent.com/634461/30595654-1343620a-9d52-11e7-8662-28df0be2d274.png)

- Le smiley "en colère" entre entre l'ange et le démon n'est pas aligné.  
- Le smiley ninja qui se téléporte sur la gauche est aligné à droite dans la sélection  
- ~~Le bouton smileys dans l'éditeur est une clémentine mais le pack de smiley clémentine n’apparait pas (la case utiliser les anciens smileys est décochées sur mon profil)~~ Edit: il faut vider le cache du navigateur

De plus, la zone de choix des smileys est tronquée sur mon écran (1600x900) sur la page de création d'un nouveau sujet: limite droite du cadre de la zone invisible + problèmes d'alignements identiques à ceux du dessus + smiley en colère qui est rouge cette fois.

![smileys_tronques](https://user-images.githubusercontent.com/634461/30595679-222deea2-9d52-11e7-962a-02078dd316fb.png)

**Comment by motet-a** [comment]
> Le smiley "en colère" entre entre l'ange et le démon n'est pas aligné.

En fait, les nouveaux smileys sont arrivés, mais comme il y a une histoire un peu compliquée de cache, il faut normalement que tu fasse Ctrl+F5 (pour actualiser le site sans le cache) un coup sur la page.

> Le smiley ninja qui se téléporte sur la gauche est aligné à droite dans la sélection

Not a bug. C’est un nouveau smiley, et c’est nécéssaire pour son animation (enfin, tu peux en discuter avec les gens qui se sont occupés des smileys, mais je suis sûr que ça a été déjà discuté au moins une fois).

**Comment by A-312** [comment]
Ce n'est pas possible de faire une sorte de proxy pour définir le etag du cache ? Pour rajouter un prefix "old" ou "new", comme ça plus besoin de faire un CTRL+F5.

**Comment by A-312** [comment]
Idem à #4978 ?

**Comment by A-312** [comment]
@Situphen à fermer car déjà fixé.
