### ISSUE TITLE
L'alias tribune.zestedesavoir.com est mal réglé

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#4646]
> > (qui a d'ailleurs un alias [tribune.zestedesavoir.com](https://tribune.zestedesavoir.com)) et la bibliothèque.
> Source: [artragis](/articles/2108/la-25e-version-de-zeste-de-savoir/?page=1#p162761)
> 
> « Votre connexion n’est pas privée
> 
> Des individus malveillants tentent peut-être de subtiliser vos informations personnelles sur le site tribune.zestedesavoir.com (mots de passe, messages ou numéros de carte de crédit, par exemple). En savoir plus
> NET::ERR_CERT_COMMON_NAME_INVALID
> 
> […]
> 
> Le site tribune.zestedesavoir.com est actuellement inaccessible, car il utilise la technologie HSTS. Les erreurs réseau et les attaques sont généralement temporaires. Vous devriez donc pouvoir accéder à cette page plus tard. »
> 
> Je ne sais pas ce qui a motivé la décision de la création de cet alias (PS : qui renvoie sur la home, d'ailleurs), mais on a un problème de nom de domaine HTTPS, et on aura un problème de _duplicate content_ une fois celui-ci résolu, puisque les billets ne déclarent **pas** d'URL canonique (je viens de vérifier).
Source: [SpaceFox](/articles/2108/la-25e-version-de-zeste-de-savoir/?page=1#p162775)

**Comment by Situphen** [comment]
J'aimerais bien savoir ce qui a motivé la création de ce sous-domaine :) Je n'ai rien trouvé ni dans Bugs&Suggestions ni en Dev Zone. Si ça s'est discuté sur IRC, quelqu'un a des logs ? :)

**Comment by artragis** [comment]
Proposé et implémenté par @vhf

**Comment by vhf** [comment]
Ça n'a pas été implémenté à ma connaissance.

**Comment by artragis** [comment]
apparament l'adresse existe et va vers la racine du site.

**Comment by motet-a** [comment]
@Situphen @gcodeur [Voici une explication](https://zestedesavoir.com/billets/1931/le-point-sur-les-stats-des-billets/#p152453).

**Comment by SpaceFox** [comment]
Je ne vais pas débattre ici de la pertinence d'un sous-domaine (on est dans la pure considération de dev là), mais il me semble important que ce sous-domaine, qui commence à être écrit à plusieurs endroits sur le net et donc indexable par Google, soit **désactivé** tant qu'il n'est pas correctement implémenté – en particulier les _duplicate content_.

**Comment by SpaceFox** [comment]
C'est **URGENT** de dégager cet alias si on ne peut pas le corriger en prod très rapidement : Google a commencé à le référencer.

https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=49#p163978

**Comment by sandhose** [comment]
C'est bon, tout est redirigé, avec un certificat valide.

**Comment by SpaceFox** [comment]
Merci pour la correction rapide.

**Comment by firm1** [comment]
Chez moi, il redirige toujours vers `zestedesavoir.com`, je croyais que le but était qu'il redirige vers les billets ...

**Comment by SpaceFox** [comment]
Honnêtement ? De mon point de vue, c'est très bien comme ça.

La redirection vers les billets, ça implique d'isoler une partie du site et de gérer proprement des URLs canoniques pour éviter le duplicate content. Or, la logique d'avoir « un sous-domaine pour les tribunes » ne fonctionne vraiment que pour des devs, le visiteur standard se fiche complètement de l'URL du site qu'il visite, voire souvent ne sait pas ce que c'est (et c'est d'ailleurs le principe de fonctionnement de pas mal d'arnaques).

En l'état on peut se contenter d'ignorer ce sous-domaine tout en redirigeant proprement les pages indexées par mégarde sur leur vraie URL. Et éventuellement se pencher sur une solution fonctionnelle (dans les deux sens du terme) pour mettre les tribunes en avant.

**Comment by firm1** [comment]
Disons que du coup, je ne comprend pas pourquoi on ne supprime pas tout simplement ce sous domaine, puisqu'il redirige de toute façon vers la page d’accueil.

Il sera toujours temps de le recréer, quand on saura en faire une redirection propre vers les billets.

**Comment by SpaceFox** [comment]
C'était la solution rapide, mais @sandhose a eu le temps de faire la solution propre qui nous garantit de ne pas péter le référencement des pages en tribunes… qui auraient déjà été référencées (et il y en a).
