### ISSUE TITLE
Refaire tous les forumulaires en utilisant le nouveau TEMPLATE_PACK

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#465]
Prérequis pour cette issue : issue #464

Il faut revoir tous les formulaires (les forms.py de chaque module, en somme) de façon à utiliser UNIQUEMENT **notre** TEMPLATE PACK.

S'il vous manque un champ créez-le dans le TEMPLATE PACK, si vous n'êtes pas certains de l'utilité ou la valeur sémantique de ce champ, n'hésitez pas à créer une issue dédié pour qu'on en parle.

Une fois que j'aurais ajusté les différents templates de ce pack, la magie opérera et nous auront des formulaires tous jolis et complètement uniforme sur l'ensemble du site.

Merci d'avance pour l'aide apportée !

**Comment by cgabard** [comment]
Ce ticket et le précédent ne sont plus d'actualités

**Comment by gustavi** [comment]
Et on ferme ici aussi !
