### ISSUE TITLE
Mettre des espaces insécables à l’intérieur des guillemets français

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4664]
> Je rappelle qu’il y a après le guillemet ouvrant une espace insécable et une autre avant le guillemet fermant

[Source](https://zestedesavoir.com/articles/2071/introduction-a-lorthotypographie-1/#2-la-ponctuation)

À corriger à coup de `sed`.

**Comment by Heziode** [comment]
@motet-a tu t'en charge ? J'ai des instructions `sed` prêtes à corriger ça sinon.

**Comment by motet-a** [comment]
@Heziode Oups, je n’aurais pas dû m’assigner là-dessus, désolé. Fais-le si tu veut.
