### ISSUE TITLE
Changer les IOError en OSError

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4677]
Comme l’a [signalé](https://github.com/zestedesavoir/zds-site/pull/4674/files#r141799665) @pquentin, depuis Python 3, [IOError est un simple alias pour OSError](https://stackoverflow.com/a/29347946). Il serait donc bien de changer [les occurences de IOError](http://gtsearch.3.141.ovh/repository/zds?q=IOError) en OSError.

**Comment by viveksyngh** [comment]
Can you assign this to me ? I will do this.

**Comment by gllmc** [comment]
I can't assign this to you, because you're not in the organization, but you can create a pull request. Thanks for your help!

**Comment by gllmc** [comment]
Corrigé par #4685.
