### ISSUE TITLE
Certains espaces insécables sont mal utilisés

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4686]
Intégré par #4659.

Certains fichiers `.py` (modèles et formulaires notamment) contiennent des espaces insécables inclus avec `&nbsp;`. Le problème est que ces chaînes sont ensuite échappées par Django dans les templates, ce qui fait que le code est visible au lieu de l'espace.

**Comment by motet-a** [comment]
Il vaut donc mieux utiliser le caractère unicode plutôt que l’échappement `&nbsp;` :upside_down_face:

**Comment by gllmc** [comment]
Je suis en train de m'occuper de ça pour les chaînes en question, mais ce serait pas mal de faire ça ailleurs en effet. :)

Édit : j'ai tout fait finalement.
