### ISSUE TITLE
Export documents to pdf with pandoc

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#47]
Pour rendre le contenu de ZdS disponible en hors ligne, il faudrait pouvoir exporter le contenu en format Pdf.
Pandoc, sait très bien faire les conversion de fichiers markdown en pdf. L'idée est donc de créer les version pdf de chaque contenu lorsqu'il est publié.

La fonction à écrire est donc toute simple, il suffit de suivre les étapes suivantes : 
- Construire un unique fichier markdown qui rassemble tout le tutoriel dans un seul fichier
- passer la commande `pandoc mon-tuto-magique.md -o mon-tuto-magique.pdf`
## Ressources utiles

[Documentation Pandoc](http://johnmacfarlane.net/pandoc/README.html)

**Comment by cgabard** [comment]
J'y ai bien pensé aussi mais c'est plus compliqué que ça en particulier parce que notre markdown est plus complet que le markdown de pandoc. Il faut donc soit étendre pandoc pour supporter nos ajouts de syntaxes, soit faire un convertisseur d'un markdown à l'autre (typiquement une balise secret se transforme avec une info de style supporté par pandoc).

Bref c'est un peu plus compliqué que ce que tu sous entends. Et je pensais m'y pencher après les travaux en cours sur le markdown du site, quitte à ce que ce soit apres la sortie de la v1 du site

**Comment by firm1** [comment]
:-P 
En effet, j'ai dis que c'était simple, pas que c'était fait en 2 lignes.

On ne partage pas la même syntaxe que pandoc, et donc il faudra transformer notre markdown vers le marldown de pandoc pendant l'étape 1 (Construire un unique fichier markdown qui rassemble tout le tutoriel dans un seul fichier).

Après, ça ne presse pas du tout, c'est le genre de chose qui peut être fais plus tard, mais ça n'empêche pas qu'on se le note dans le bugtracker pour être sur que ça sera traité un jour. Donc dès que tu commences à bosser dessus, tu t'assigner la tâche, et on saura qu'il y'a quelqu'un dessus.

**Comment by cgabard** [comment]
Yep.

Après en réalité ce n'est pas des tonnes de choses à faire : Certaines syntaxes de notre markdown ont été choisies justement pour être compatible avec pandoc directement

**Comment by firm1** [comment]
J'y ai un peu réfléchi à cette issue, et je voyais un léger souci qui peut être embêtant.

Globalement, par défaut un big tuto est organisé selon l'arbre suivant : 

``` text
-Mon Tuto
    - Partie1
        - Chapitre1
            - Extrait1
            - Extrait2
        - Chapitre2
            - ...
    - Partie2
        - Chapitre1
            - ...
        - Chapitre2
            - ...
```

Dans chaque extrait, on peut écrire du contenu. Cependant, les titres sont représentés ainsi : 
`h1` => `#`
`h2` => `##`

Lors de la conversion en pdf, le nom des parties et chapitres auront quels titres puisque les h1, h2, sont déja occupés ?

**Comment by Coy0te** [comment]
Lors de la conversion zds_md -> pandoc_md, on peut éventuellement transformer les `#` et `##` des tutos en `####` et `#####`.

Maintenant ça ne marchera que pour les tutos actuels, c'est-à-dire ceux dans lesquels il n'y a que des `<titre1>` et `<titre2>` (vu que le zCode n'offrait pas plus). Si demain des gens se mettent à écrire des titre5 ou titre6 dans les tutos sur ZdS, cette astuce pourrie ne marchera plus.

**Comment by firm1** [comment]
En effet, on pourrait dire qu'on rajoute `##` devant tous les titres des big tutos (pour libérer les `h1` et `h2` pour parties, chapitres), et rajouter des `#` devant tous les titres des minit-tutos.

Sauf qu'il y'a aussi les cas ou les titres peuvent être écrit à coup de `##titre2##` ou encore sur une tuto C, tu peux avoir `## le préprocesseur \# ##`, ça risque d'être un peu corsé non ?

**Comment by cgabard** [comment]
Je peux probablement faire un hack pour virer les h5 et h6 du markdown du site : ça regle le prob pour les tuto et sur les forums de toutes façon il n'y a aucune raison d'aller si profond.

Il y a peut etre que pour les articles que ça peut etre genant, mais bon...

**Comment by cgabard** [comment]
@firm1 : Markdown autorise a mettre des # a la fin mais ils n'ont pas l'obligation d'etre présent ni du meme nombre qu'au début (il me semble)

Dans tous les cas, ça peut se détecter

**Comment by cgabard** [comment]
Le premier truc a faire est je pense d'empecher les titres 5 et 6 dans le markdown, le reste ça se gèrera au moment du parseur vers la syntaxe pandoc

**Comment by Coy0te** [comment]
Ça me paraît aussi la solution la moins chiante.

**Comment by firm1** [comment]
> @firm1 : Markdown autorise a mettre des # a la fin mais ils n'ont pas l'obligation d'etre présent ni du meme nombre qu'au début (il me semble)

Je ne sais pas pour le nombre de dièse à la fin. Mais je viens de me rendre compte qu'il est [aussi possible](http://www.zestedesavoir.com/forums/sujet/5/bug-articles?page=1#p25) de faire des titres avec la syntaxes `------` ou `====`

Je ne sais pas si c'est forcément une solution viable de faire ça dans le converseur md_zds -> md_pandoc. Je continue de réflechir, mais je tenais à partager mon souci.

**Comment by cgabard** [comment]
pandoc doit supporter aussi cette syntaxe, c'est inclus dans le markdown de base.

BTW, pour moi le convertisseur devrat comprendre la sémantique du document. Il détecte un titre 1 d'une forme ou une autre ? tres bien il est donc capable d'en extraire le texte et de générer un titre 3 avec... Je ne vois pas le prob. De toute façon le convertisseur ne pourrat pas forcément etre fait avec de simples regexp car certaines constructions du markdown sont assez complexe.

**Comment by cgabard** [comment]
Donc il faut juste éviter d'avoir un titre 5 à convertir en titre 7 innexistant. Une solution est de le bloquer à la rédaction.

**Comment by firm1** [comment]
> Il détecte un titre 1 d'une forme ou une autre ? très bien il est donc capable d'en extraire le texte et de générer un titre 3 avec ...

disons, que ça me semble vachement lourd de devoir convertir tous les titres avec leurs 4 syntaxe différente alors qu'on écrit en markdown, ça devrait être plus simple

**Comment by cgabard** [comment]
Tu voudrais faire l'inverse ? Interdire les titre 1 et 2  dans le md du site ? Juste dans la partie tuto ? ça peut se régler à coup de param ?

ça me semble moins perturbant pour les auteurs de leurs dire "vous avez le droits au titre 1 à 4" que "vous avez le droit aux titres 3 à 6" ...

**Comment by cgabard** [comment]
Apres @firm1 je compte de toute façon faire le convertisseur en m'inspirant fortement de python-markdown. En gros le reprendre mais virer la partie convertisseur vers html et l'adapter à "un autre markdown". Ça a plusieurs avantages : 
- Je part d'une base solide de parseur qui, je le sait, peut déjà parser le texte source (puisqu'il le fait vers le html)
- J'ai déjà toutes les regexp et structures logiques de fait
- Si il y a des limitations ou contraintes liés à notre parseur (genre des syntaxes qui entrent en conflit), les auteurs vont écrire leur markdown pour qu'il s'adapte au comportement du parseur et générer le rendu qu'ils veulent. Je m'assure ainsi d'avoir un convertisseur avec le moins d'erreur possibles
- A terme on peut essayer de mutualiser une partie du code

**Comment by firm1** [comment]
Ah non, ça serait con d'interdire les titre 1 et 2.

Vu que la doc de pandoc n'a pas l'air d'avoir des options pour gérer les titres, ça va se finir avec votre solution (rajout de dièse).

Du coup, ça fera un peu plus de taf pour toi que je ne le pensais. Dans ma tête fallait juste adapter nos extensions.

**Comment by cgabard** [comment]
"juste nos extensions" ça en fait 5-6 tout de même avec certaines un peu chelou à gérer, les box en particulier.

Le truc est que dans le md de pandoc, on peut injecter des styles type css. Mais je ne sais pas comment il convertit ça quand on le passe en latex pour faire le pdf (car les ebbok, à la limite, c'est du html)

**Comment by firm1** [comment]
Ok, tu penseras donc, à interdire les titre 5 et 6.

**Comment by dreherch** [comment]
N'est-il pas possible de faire un truc malin ? Du genre, pour un chapitre,
compter le niveau de titre le plus faible, et calculer un offset à
appliquer à tous les titres du chapitre ? Comme ça, ça marche quel que soit
le niveau de titre que l'auteur utilise, tout en gardant la hiérarchie de
l'auteur.

**Comment by Coy0te** [comment]
La structure d'un big-tuto est figée (idem pour les mini-tuto), l'offset est connu d'avance. 

Le seul souci, c'est de faire en sorte que la profondeur max autorisée pour les rédacteurs ne dépasse pas (profondeur max des titres en md - offset). D'où la proposition actuelle.

**Comment by dreherch** [comment]
En fait, tu ne sais pas si l'auteur va bien commencer son chapitre avec un
titre 3. Après, pour les auteurs qui font trop de niveaux de titres, ben à
part indiquer le max à la rédaction et réduire les niveaux de titre au max
supporté et faire un warning à l'auteur lors de la génération, je ne vois
pas trop quoi faire

**Comment by cgabard** [comment]
C'est ce qu'on disait, on empeche en markdown les titre 5 et 6 et basta, on est surs qu'on aura pas de prob plus tard, non ?

**Comment by ShigeruM** [comment]
Je me permets d'intervenir. Les titres 5 et 6 dans les tutos, docs, specs, etc. ça m'a toujours un peu gavé. J'ai le sentiment que si on doit aller si profond dans la structure du plan, c'est que le plan est mal gaulé. Et d'un point de vue purement pédagogique, je ne suis pas sûr qu'un lecteur suive facilement quand il est dans une sous-sous-sous-sous-partie. Bien sûr il y a des cas où ça peut être utile, mais c'est rare et dans tous les cas ça peut être traité autrement. Bref, si les titres 5 et 6 devaient disparaître, non seulement ça ne me choquerait pas, mais en plus ça éviterait aux auteurs de s'égarer dans des méandres de plans illisibles.

**Comment by cgabard** [comment]
Concernant cette issue, une fois le markdown du site fait, je compte m'y attaquer. Mais plutôt qu'attendre une version de-la-mort-qui-tue dans longtemps, je propose de faire une pré version rapidement. Pandoc est capable de prendre du HTML en entrée, utiliser celui générer par python markdown nous permettra d'avoir un premier convertisseur rapidement. Seule quelques extensions (ex vidéo) seront a légèrement modifié pour une production papier. 

Une fois cette première version, on Pourrat prendre plus de temps pour générer la conv depuis le markdown proprement

**Comment by firm1** [comment]
La conversion html de pandoc marche aussi avec MathJax ?

**Comment by cgabard** [comment]
pandoc dit juste qu'il peut prendre en entrée du html. Il dit aussi qu'en sortie il peut générer des balises pour mathjax. En entrée ce n'est pas très clair, ils ne fournissent pas d'exemple sur leur site. Cela fait peut etre partie des extensions qu'il va falloir travailler. Mais ça ne me choquerait pas qu'il y arrive.

**Comment by firm1** [comment]
Dans ce cas, je m'occupe de générer le html complet d'un tuto et de lancer la commande pandoc par dessus (lors de la publication d'un tuto/article) pour voir ce que ça donne déjà.

**Comment by cgabard** [comment]
Tu peux preparrer mais faudrait déjà que je fassse le décalage de titre : https://github.com/Taluu/ZesteDeSavoir/issues/85 

Sinon oui si tu pouvais me preparrer ça, ça me va. Ce serait cool, pendant le debug, d'avoir un bouton pour le re-générer à la demande (histoire que je n'ai pas a modifier tout un tuto et le faire valider pour tester)

**Comment by firm1** [comment]
Mes premiers résultats de conversion html -> pdf ne sont pas très probants.

Avec une simple `pandoc -s -r html alignement-memoire-et-endianess.html -o alignement-memoire-et-endianess.pdf`

je me prend une cette erreur.

``` console
pandoc: Error producing PDF from TeX source.
! Package pdftex.def Error: File `http://uploads.siteduzero.com/files/347001_34
8000/347667.png' not found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.111 ...uzero.com/files/347001_348000/347667.png}

```

Visiblement, il n'arrive pas à lire les images d'une url.

Des idées ?

**Comment by cgabard** [comment]
C'est un prob latex qui n'arrive pas a générer une image depuis une URL. Ça ne m'ettone pas. Tu peux me donner la ligne exacte dans le code latex ? Pour voir si on peut s'en sortir sans les télécharger localement

**Comment by firm1** [comment]
Je n'ai pas l'équivalent latex, puisque pandoc le fait implicitement quand je demande le passage HTML -> pdf

**Comment by Coy0te** [comment]
Si on suit les règles de validation que nous appliquions sur le SdZ, alors c'est pas un gros problème, dans le sens où les images des cours doivent être présentes en local pour qu'un cours soit publié.

**Comment by cgabard** [comment]
Du coup coyote tu as un cours complet en markdown avec images qu'on puisse tester ?

Firm1 : bah dit lui de produire du latex puis fait `pdflatex ton fichier.tex`

**Comment by Coy0te** [comment]
Non, les .tuto que j'ai importés sur ZdS contiennent tous des liens vers les images SdZ.

Après, j'ai déjà récupéré tous les .tuto que Ths a copiés sur le serveur de ZdS, et en principe ceux-là sont ok, car ils contiennent des liens relatifs vers les images. Maintenant, ça va être à la fonction d'import de ZdS de correctement manger les images que Ths a rangées dans des dossiers. Je ne sais pas si @firm1 a déjà pris en compte la structure des tutos copiés par Ths ou pas.

**Comment by cgabard** [comment]
De toute façon, j'ai cherché un peu, et on aura toujours le même prob. Même depuis markdown, le latex est toujours le même et pandoc ne va pas télécharger les images. Latex non plus. 

De là deux solutions : on modifie le latex (ce qui est possible, on peut injecter un template latex à pandoc) pour qu'il aille telecharger les images ou on assure a pandoc d'avoir toutes les images en locales

**Comment by Coy0te** [comment]
ZdS est HS ? Erreur python : "cannot determine numbers of CPU".

**Comment by cgabard** [comment]
firm1 dit qu'il n'a rien pousser dessus. Je miserais sur une question de droit utilisateur qui aurait été changé...

**Comment by SpaceFox** [comment]
C'est fait depuis longtemps !
Je ferme :)
