### ISSUE TITLE
Retirer tous les commentaires `# coding: utf-8` en haut des fichiers

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4700]
Ils ne servent plus à rien avec Python 3.

À faire avec `sed` ou autre (ne faites pas ça à la main hein).

**Comment by NullSilence** [comment]
Je m'en occupe.

**Comment by NullSilence** [comment]
Je n'ai pas les accès pour créer de nouvelles branches (Pour éventuellement faire un pull-request). Dois-je pousser directement mes changements sur la branche develop? Ou préférez-vous créer la branche issue4700 pour moi?

**Comment by motet-a** [comment]
En fait, il faut que tu *fork* le dépot pour que tu aie une copie personnelle avec un accès en écriture dessus. Ça sera le dépot “NullSilence/zds-site”. Ensuite, tu pourrais faire une *pull request* de ton dépot (NullSilence/zds-site) vers celui-ci (zestedesavoir/zds-site).

Plus d’infos : 

- https://help.github.com/
- https://help.github.com/articles/fork-a-repo/
- https://help.github.com/articles/proposing-changes-to-your-work-with-pull-requests/
