### ISSUE TITLE
API pour des clients externes

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#471]
Ne trouvant plus vraiment mon bonheur dans le projet principal, je me suis lancé dans le développement des APIs du projet (dans le but de développer une application Android native personnellement mais à qui veut de développer des clients sur d'autres plateformes).

Je crée cette issue pour pouvoir linker mes commits à une issue et pour pouvoir en discuter si vous avez des envies particulières, des remarques ou envie de contribuer sur la branche API.

**Comment by GerardPaligot** [comment]
Je rencontre déjà un problème dans la conception actuelle de certaines classes du projet. Je bosse sur l'API des utilisateurs et je veux donc pouvoir récupérer ses articles, ses tutoriels et ses posts sur le forum.

Actuellement, la classe `Post` étend la classe `Comment`. Le problème c'est que la classe `Comment` déclare l'attribut `author` et que cette classe est étendue par d'autres classes. Donc, dans mon API, lorsque je veux récupérer tous les postes, je suis obligé de vouloir récupérer tous les commentaires. Je me limite donc pas aux postes. C'est gênant.

Quelqu'un voit une solution plus élégante que d'enlever l'attribut de la classe `Comment` pour la descendre dans ses classes filles ?

**Comment by cgabard** [comment]
Je n'ai pas d'avis sur le prob en particulier mais je soutient l'idée d'une API.

**Comment by firm1** [comment]
> Donc, dans mon API, lorsque je veux récupérer tous les postes, je suis obligé de vouloir récupérer tous les commentaires

Euh, non pas vraiment. La relation d'héritage entre les deux, implique que lorsque tu cherche tous tes Posts, il te suffit de faire un truc du genre : `Posts.objects.all()` et normalement tu obtiens un queryset de tous les `posts` avec les attributs de Post et de Comment. En gros tu tapes sur la mère pour rentrer dans la fille (phrase à ne pas sortir de son contexte).

Ceci dit, pourrais-tu me dire exactement quelle techno tu utilises pour faire ces API ? Je dis ça parce qu'il existe déjà dans l'historique [une ébauche d'API](https://github.com/Taluu/ZesteDeSavoir/tree/c0dccfba29c76064e1e94656436a3c556b29072a/lbp/api) (valable pour le modèle à la PDP) qui pourrais être remaniée assez simplement. Il faudrait pour ça se baser sur [djangorestframework](http://www.django-rest-framework.org/)

**Comment by GerardPaligot** [comment]
> Euh, non pas vraiment. La relation d'héritage entre les deux, implique que lorsque tu cherche tous tes Posts, il te suffit de faire un truc du genre : `Posts.objects.all()` et normalement tu obtiens un queryset de tous les `posts` avec les attributs de Post et de Comment.

Ca dépend de ce que tu veux, ce n'est pas aussi simple. Si tu veux la ressource `Post` et donc que tu veux tous les posts de tout le monde, tu devrais faire :

```
class PostList(generics.ListAPIView):
    '''List all posts'''
    queryset = Post.objects.all()
    serializer_class = PostSerializer
```

Du côté de la vue et le `serializer` ressemble à :

```
class PostSerializer(serializers.ModelSerializer):
    author = serializers.Field(source='author.username')
    update = UnixDateField(source = 'update')

    class Meta:
        model = Post
        fields = ('id', 'text', 'topic', 'author', 'pubdate', 'update')
```

Je récupère tous les posts de tout le monde et j'utilise sans problème les attributs de la classe `Comment`. Aucun problème. Mais si tu veux tous les posts d'un utilisateur donné, `Post.objects.all()` n'a simplement rien à voir. La vue est tout aussi simple mais le `serializer` se passe au niveau de l'utilisateur :

```
class UserList(generics.ListAPIView):
    '''List all users'''
    queryset = User.objects.all()
    serializer_class = UserSerializer
```

```
class UserSerializer(serializers.ModelSerializer):
    articles = serializers.PrimaryKeyRelatedField(many=True, read_only='true')
    comments = serializers.PrimaryKeyRelatedField(many=True, read_only='true')

    class Meta:
        model = User
        fields = ('id', 'username', 'articles', 'comments')
```

Le `comments` que tu vois match avec le nom donné dans l'attribut `related_name` d' `authors` : `author = models.ForeignKey(User, verbose_name=' related_name='comments')`.

Conséquence : Je récupère tous les commentaires, pas uniquement les posts.

> Ceci dit, pourrais-tu me dire exactement quelle techno tu utilises pour faire ces API ? Je dis ça parce qu'il existe déjà dans l'historique une ébauche d'API (valable pour le modèle à la PDP) qui pourrais être remaniée assez simplement. Il faudrait pour ça se baser sur djangorestframework

Je ne suis pas fou. Je ne ré-invente pas la roue. J'utilise bien `djangorestframework` et j'ai été voir comment PDP faisait leur API. Cela dit, ce n'est pas super naturel comme façon de développer une API. J'ai donc été lire la documentation en entier.

> En gros tu tapes sur la mère pour rentrer dans la fille (phrase à ne pas sortir de son contexte).

Ca, je ne te promet rien !

**Comment by Taluu** [comment]
Le sujet m'intéressant, je poste juste pour suivre le sujet par mail.

> > En gros tu tapes sur la mère pour rentrer dans la fille (phrase à ne pas sortir de son contexte).
> 
> Ca, je ne te promet rien !

Moi non plus. :D

**Comment by firm1** [comment]
@Gerard : je te conseille vraiment de lire bien lire la doc (surtout la
partie sur les filtres), a l'époque c'est moi qui avait codé l'API pour pdp
et je me souviens que ce problème n'était pas un "problème".

**Comment by GerardPaligot** [comment]
J'ai un peu parcouru les [filtres](http://www.django-rest-framework.org/api-guide/filtering). J'ai peut-être mal compris (possible), mais je ne vois pas bien comment ça peut résoudre le problème.

**Comment by firm1** [comment]
Etant donné que cette issue n'est pas dès plus prioritaire, je ne vais pas m'y replonger tout de suite.

Mais quand j'aurai le temps de relire la doc, je te donnerai probablement une solution si tu ne l'as pas trouvée entre temps.

**Comment by GerardPaligot** [comment]
Sans te replonger dedans, les filtres permettent de filtrer une requête SQL en envoyant les éléments souhaités malgré les éléments mentionnés dans le `serializer`.

Un exemple venant de PDP :

```
class ForumFilter(django_filters.FilterSet):

    class Meta:
        model = Forum
        fields = ['category']

class ForumList(generics.ListAPIView):
    """
    List all forum.
    """
    queryset = Forum.objects.all()
    serializer_class = ForumSerializer
    filter_class = ForumFilter

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)
```

Je récupère juste la catégorie des forums lorsque je veux récupérer la liste des forums (contrairement à l'api pour accéder à un forum en détail qui est sans filtre).

Bien compris son fonctionnement ou ça ne se limite pas à ça ?

**Comment by firm1** [comment]
> Bien compris son fonctionnement ou ça ne se limite pas à ça ?

T'as du louper un truc, car étant donné que c'est moi qui ai developpé toute l'API de PdP, je sais bien que ce problème est solutionnable. Comment ? Faut relire la doc à tête reposée, c'est tout ce que je peux te dire là comme ça, je ne me souviens plus (ça doit bien faire 1 an).

**Comment by GerardPaligot** [comment]
Bien, je regarderais ça plus attentivement alors.

**Comment by Eskimon** [comment]
Je me met dans la loop car le sujet m'interesse pour refaire le notificateur sur chrome et du coup j'en profite pour demande a @GerardPaligot : "Comment ca se passe ? Tout va bien ?"

**Comment by GerardPaligot** [comment]
Je n'y ai pas travaillé depuis mon dernier commit. Faut que je me replonge dans la documentation, je n'ai pas le temps pour ça pour l'instant. Mais vu la simplicité de développement d'une API avec Django, ça sera fait.

**Comment by artragis** [comment]
Perso je me lancerai bien, par la suite (i.e dès août) dans une apli winphone.  Puisque zds devrait être libre etc, il serait peut être sympa qu'une organisation soit créée pour que : 
- l'API ait une réelle documentation
- les projets sur les différentes plateforme y soient gérées
- tout ce qui est aside du développement du produit principal soit géré (notamment markdown).

Si l'orga existe déjà, bah je me tais ^^

**Comment by SpaceFox** [comment]
Qu'entends-tu par "fondation" dans ce sens ?

**Comment by cgabard** [comment]
Je pense qu'on pourra penser a une page dédié sur le site et, pour les applis qui le souhaitent, mettre leur code sous l'orga github de l'asso, pour accorder un statut officiel a ces applis. 

Dans tous les cas c'est encore un peu tôt mais oui, pas d'Api sans doc. 

Hesitez pas a en parler

**Comment by artragis** [comment]
Je me suis gourré de mot, c'est "l'organisation github", mais apparemment y'a peu de membres dedans donc du coup j'en trouvais pas beaucoup mention. Mais comme j l'ai dit, je me tais.
Maintenant, plus qu'à démarrer un repos avec la doc et après je le forkerai et j'aiderai.

**Comment by geoffreyc** [comment]
Est-ce que le "framework" d'api utilisé permet la generation d'une
documenation semi-automatique? Ca serait pas mal si c'etait le cas, etj e
sais que certain le font.

2014-05-30 17:13 GMT+01:00 artragis notifications@github.com:

**Comment by ChantyTaguan** [comment]
Plop ! Au boulot, je suis en train de développer une API, et pour générer la doc, on utilise Swagger. Ca donne des doc franchement sympa, et c'est simple à utiliser. Et en plus, ça permet de générer des librairies clientes dans différents languages, et ça c'est quand même bien la classe !

Nous c'est pour une appli codée en java EE, mais de ce que j'ai vu, ça a l'air simple à intégrer avec Python : https://github.com/marcgibbons/django-rest-swagger.

**Comment by firm1** [comment]
Comme l'a précisé geoffreyc la lib utilisé qui permet de framework REST
possède un truc qui fait la génération automatique de documentations. Et
comme la mentionné taguan c'est bien swagger.

Il suffit d'aller voir la doc de l'API de PDP pour vous faire une idée.

**Comment by GerardPaligot** [comment]
Pour l'instant, la branche API (en local parce que j'ai pas encore pris la peine de cabler mon fork avec l'origin), affiche le résultat suivant à partir d'un navigateur :

![capture decran 2014-05-30 a 19 38 32](https://cloud.githubusercontent.com/assets/1913901/3134071/778e3454-e821-11e3-8169-8569223edc1f.png)

**Comment by Taluu** [comment]
S'il faut créer un repo pour ça (API,  App winphone, android, iphone,
whatever), n'hésitez pas à demander.

---

Baptiste Clavié - 06.88.68.10.16

http://github.com/Taluu

http://baptiste.clavié.net

2014-05-30 19:40 GMT+02:00 Gerard notifications@github.com:

**Comment by GerardPaligot** [comment]
L'API sera intégré au projet zds-site. Pour les autres projets fronts mobiles, c'est sans doute un peu trop tôt avant de créer quoi que ce soit.

**Comment by artragis** [comment]
Je plussoie, il faudra décider d'une véritable feuille de route pour les API avant de se lancer dans le développement des applications. Il faudra aussi leur donner une vraie plusvalue.

**Comment by cgabard** [comment]
Le projet est open source, a vous de nous pondre des appli si bien qu'on ai
envie de les utiliser !

**Comment by GerardPaligot** [comment]
La plus value, c'est clairement un mode hors connexion selon moi. :)

**Comment by cgabard** [comment]
Les notifs natives peuvent être chouette aussi

**Comment by GerardPaligot** [comment]
Tu entends quoi par là ? Des pushs notifications quand tu as une nouvelle notification, MPs ou alertes ?

**Comment by GerardPaligot** [comment]
Si oui, c'est une bonne idée mais faut savoir que ça demande une architecture supplémentaire côté serveur (qui ne devrait pas être lié au projet django zds-site). Il y a la solution de Google (GCM), Parse (basé sur GCM) et d'autres.

**Comment by cgabard** [comment]
C'est pas urgent et perso je ne sais pas trop comment tu dois faire ça mais
en tant qu'utilisateur, si j'avais des notifs quand je recevais un mp ou
des commentaires a un truc ou j'ai rédigé, oui je trouverai ça top classe.
Mais il y a sûrement plus urgent avant.

**Comment by GerardPaligot** [comment]
Non, non mais je trouverais ça trop classe et tu as des solutions simples pour mettre en place mais comme tu le dis, on y est très loin. Faut déjà avoir une API fonctionnelle.

**Comment by Eskimon** [comment]
En tout cas : "Prem's sur le Notificateur Chrome !" (Tout le code est déjà pret, j'ai plus qu'à refaire le parseur le temps qu'une API arrive !)

**Comment by cgabard** [comment]
Ça mérite de laisser le ticket d'ouvert alors que ça fait doublon avec la zep ?

**Comment by gustavi** [comment]
Non.

https://zestedesavoir.com/forums/sujet/622/zep-02-elaboration-dune-api/
https://zestedesavoir.com/forums/sujet/1365/zep-17-elaboration-de-lapi-des-membres/
