### ISSUE TITLE
[Suggestion] Assouplir la gestion des blocs spéciaux

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#4716]
Aujourd'hui nos blocs spéciaux sont quelque part entre [ce genre d'alerte](http://docdock.netlify.com/shortcodes/alert/) et [ce type de notice](http://docdock.netlify.com/shortcodes/notice/), dans le sens où ils n'ont pas d'en-tête mais ou l'icône est imposée par le type de bloc.

Ma proposition est d'ajouter [ce type de bloc](http://docdock.netlify.com/shortcodes/panel/), qui aurait les avantages suivants par rapport à l'existant :

- Possibilité d'avoir des blocs « neutres ».
- Possibilité de mettre un titre personnalisé.
- Possibilité de mettre un texte relativement long dans un bloc sans que ça rende toute une page multicolore (surtout utile avec un bloc neutre).
- Normalement facile de rajouter un type de bloc.

-----------

Retours du topic :

- Ce serait aussi une manière d'avoir les déjà évoqués blocs de type « Démonstration », « Théorème », « Définition », si possible numérotés.
- Les boites personnalisées auraient un choix limité de thème (au moins : les existants + « neutre »), le titre serait arbitraire.

Sujet : https://zestedesavoir.com/forums/sujet/9492/suggestion-assouplir-la-gestion-des-blocs-speciaux/
*Envoyé depuis Zeste de Savoir*

**Comment by artragis** [comment]
C'est plutôt un truc à gérer côté zmarkdown, bien qu'il n'y ai pas encore de ticket à ce propos dans le projet zmd.

**Comment by nils-van-zuijlen** [comment]
Ben, maintenant, il y a un ticket à ce propos ^^

**Comment by gllmc** [comment]
Vu que cela ne concerne que zmarkdown, je ferme le ticket ouvert ici. :)
