### ISSUE TITLE
Date de dernière connexion

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#472]
La date de dernière connexion semble être effectivement la date à laquelle le membre s'est connecté la dernière fois (validation du formulaire de connexion). Ce n'est donc pas un véritable bug en soit mais on s'attendrait plutôt à avoir la date de dernière visite du membre.

Je ne mets pas de flag facile/moyen/difficile car je ne me rends pas bien compte des implications. D'après ce que j'ai vu, c'est le champ last_login de la classe User qui est utilisé et il n'y a pas de champ prévu pour la date de dernière visite. Pour la dernière visite, il faudrait donc un champ dans la classe Profile, mais ça vaudrait dire qu'il faut toucher au modèle, faire en sorte que cette date soit enregistrée à chaque fois, etc. Bref, je ne me rends pas compte.

**Comment by SpaceFox** [comment]
Pour éviter de spammer la BDD avec des écritures permanentes, on pourrait mettre une limitation. Par exemple, on enregistre que si la dernière MAJ a plus de 10 minutes.

**Comment by firm1** [comment]
La tache est de type facile. La problématique est connue et solutionnée ici : http://stackoverflow.com/questions/18434364/django-get-last-user-visit-date

Ce qu'il appelle classe User, chez nous c'est la classe Profile.

En rajoutant une condition pour Save avec un delta de plus de 10 min et en plaçant l'intergiciel (middleware) avec le session-middleware ça devrait le faire de manière propre.

**Comment by SpaceFox** [comment]
Attention si tu rajoutes un champ dans la BDD, il ne faut pas oublier de
recréer le fichier de migration (on utilise "south" pour ce faire).

**Comment by SpaceFox** [comment]
Corrigé dans la PR #479 .

**Comment by viki53** [comment]
Apparemment c'est pas si corrigé que ça : http://zestedesavoir.com/forums/sujet/485/recherche-et-statistiques-sur-les-membres/?page=1#p5295 ;)

**Comment by firm1** [comment]
Si si, défaut de conf serveur que je viens de rétablir.

Merci.
