### ISSUE TITLE
[Forums] Filtre sur les forums pour les pages > 1

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#473]
Actuellement on ne peut pas naviguer sur les pages > 1 sur les forums sans que le filtre (sujets résolus / non résolus) soit réinitialisé.

Il faudrait que le filtre reste actif tant qu'on ne l'a pas réinitialisé à la main, ce qui implique un visuel quelque part indiquant les filtres actifs.

**Comment by firm1** [comment]
J'ai commencé un truc dessus. Donc je prend

**Comment by firm1** [comment]
fixé, et mergé, je ferme.
