### ISSUE TITLE
Réécriture des réglages

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4736]
Salut,

Le déployement sur la bêta d’hier a bien cafouillé comme il faut
à cause de l’import (traître) de `settings_prod.py` depuis
`settings.py`. Le moment est venu de reprendre ça.

## Proposition

Après quelques discussions avec Sandhose, je propose de
s’inspirer de [ce qui est fait sur djangoproject.com](https://github.com/django/djangoproject.com/tree/master/djangoproject/settings) :

```
zds
└── settings
    ├── base.py
    ├── dev.py
    ├── prod.py
    ├── [secrets.toml] (optionnel, pas *checked-in*)
    └── test.py
```

Dans `dev.py`, `prod.py` et `test.py`, on “étend” simplement
`base.py` avec un `from .base import *` en haut des fichiers. Il
n’y a plus de système qui importe automagiquement `prod.py` si il
est présent, donc si vous voulez utiliser `prod.py` à la place de
`dev.py`, vous devez manuellement exporter la variable
d’environnement `DJANGO_SETTINGS_MODULE=zds.settings.prod`.

`secrets.toml` n’est pas *checked-in* dans Git, libre à vous
d’avoir le votre si vous le désirez.

Vous pouvez aussi très bien avoir votre propre fichier de
configuration personnalisé dans le dossier `zds/settings/`. Il
faut juste que vous spécifiez manuellement que vous voulez
l’utiliser à la place de `zds.settings.dev` avec `--settings` ou
en exportant `DJANGO_SETTINGS_MODULE`.

Qu’en pensez-vous ? C’est possible d’exporter
`DJANGO_SETTINGS_MODULE=zds.settings.prod` sur la production de
manière sûre, étant donné qu’il me semble qu’il y a plusieurs
utilisateurs ? Vous pourriez éventuellement modifier le script
`venv/bin/activate` vu qu’il est sourcé, mais c’est un peu sale,
non ? Vous connaissez un meilleur moyen de faire ça ?

**Comment by motet-a** [comment]
Ah, autre chose : Je vais pouvoir tester ça facilement avec l’espèce de mini-préprod que j’ai faite récemment avec Docker. C’est un environnement bien différent par rapport à ce qu’il y a en prod et en bêta, mais je pense que ça peut beaucoup aider.

**Comment by Situphen** [comment]
@sandhose est que #2995 encore d'actualité ? Si oui, je pense que @motet-a pourrait l'intégrer dans ce ticket

**Comment by sandhose** [comment]
À long terme oui, à court terme, pas dans cette PR.

Si on peut avoir à terme juste à déployer des sdist/egg/wheel python, et chopper la version directement depuis ça, ça serait bien.

Vous saviez que ZdS est en [`0.2` selon le `package.json`](https://github.com/zestedesavoir/zds-site/blob/dev/setup.py#L27) et en [`1.7` selon le `setup.py`](https://github.com/zestedesavoir/zds-site/blob/dev/setup.py#L27) ? 🙃

**Comment by motet-a** [comment]
Il n’est déployé ni sur pypi ni sur npm donc c’est tout bidon.

**Comment by vhf** [comment]
Pour moi le sha dans le footer n'a pas d'utilité. Actuellement on a une étape de build faite sur travis sur chaque tag, si on continue dans cette direction d'avoir des builds, y inclure le tag est facile.

Comme ça on ne dépend plus du tout d'un repo au déploiement, on a toujours le tag en footer, et on vire le sha ?
