### ISSUE TITLE
Sécuriser les serveurs

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#474]
Aujourd'hui nos serveurs ne sont pas spécialement sécurisés, et se prennent déjà des tentatives de hack (cf le auth.log).

Autant dire que si on ne fait rien, le jour de l'ouverture au public, ça va être la fête du slip...

Une connexion par clé uniquement, une interdiction absolue de SSH sur root et un fail2ban me paraissent être un bon début.

**Comment by geoffreyc** [comment]
Yep c'est prevu (je prefere CSF+LFD perso plutot que fail2ban, le firewall
en plus est un bonus)
Connexion par clef je sais pas si c'est forcement nécessaire, mais
interdiction de root est aussi prevu bien entendu.

2014-05-10 13:30 GMT+01:00 SpaceFox notifications@github.com:

**Comment by SpaceFox** [comment]
J'y pense : on a une sauvegarde de la BDD en place ?
Sinon, j'imagine que ce serait pas mal à faire.

**Comment by geoffreyc** [comment]
Il faut aussi savoir qu'est ce qu'on met en place niveau backup. Le code
y'a gît, mais niveau fichiers statiques ( uploads etc.) il faudrait backupé
régulièrement. Pareil pour la bdd. Mais ça coûte des sous tout ça pour des
offsite backups.

**Comment by SpaceFox** [comment]
C'est clair... j'ai toujours en tête le modèle de Dedibox ou quand t'as un dédié, t'as quelques Go de sauvegarde offerts avec - mais on a pas un dédié...

**Comment by Eskimon** [comment]
Vous evaluez ca a quel poids un backup de la BDD ? J'ai aucune idée de l'ordre de grandeur de cela...

**Comment by cgabard** [comment]
C'est pas tant la db en fait que les tuto avec images qui vont prendre de la place

**Comment by geoffreyc** [comment]
C'est ça, c'est tout les fichiers 'en plus: qu'il faudra sauvé. Si on
tourné sous une VM a nous ça aurait été super simple, un snapshot tout les
soirs + upload chez deux trois personnes et basta. La il va faloir décider
exactement ce qu'on sauvegarde, et coder un script qui automatise tout ça.
Le 24 mai 2014 10:42, "Christophe Gabard" notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
> Si on tourné sous une VM a nous ça aurait été super simple

Le site ne tourne pas sur une VM ? Et puis un snapshot, c'est gentil mais toute l'install système c'est pas super utile de la sauvegarder.

**Comment by geoffreyc** [comment]
Au contraire c'est super utile. Je sais pas si tu gères un parc de VM, mais
faire des backups a coup de snapshots c'est super. Un truc a foiré sur le
serveur et on a besoin de tout remettre en marche pronto? Restore la
snapshot, et voilà.

Besoins de recuperer quelques dossiers/fichiers ? Hop tu lances une
nouvelle VM, et tu choisis ce que tu veux recuperer.

Le système en lui même pèse pas très lourd, quelques GB au plus, c'est pas
la plus lourd et c'est très utile d'avoir un vrai backup qu'on a juste a
restorer pour que tout remarche. Et au prix du GB, y'a pas a se gêner.

La prod tourne sur un vps OVH, on a donc aucun contrôle sur ce genre de
truc. Pas moyen de faire de snapshot ou de restorer a partir dune snapshot.
Le 24 mai 2014 21:17, "DEMODE Alexandre" notifications@github.com a écrit
:

**Comment by Alex-D** [comment]
Oui je saisi bien tout l'intérêt d'un backup par snapshot, mais faut les stocker, et là on a pas de stockage présentement.

Et OVH propose pas de pouvoir DL un backup ? Ou un accès à l'API d'OpenStack pour DL la VM ?

**Comment by geoffreyc** [comment]
Snapshot ou pas, il faut stocker la backup quoi qu'il en soit le problèmes
est le même.

Notre VPS ovh n'est pas l'offre cloud, on tourne pas sous openstack, le vps
est un container openvz
Le 24 mai 2014 22:33, "DEMODE Alexandre" notifications@github.com a écrit
:

**Comment by Alex-D** [comment]
Arf :/ Je pensais que c'était OpenStack derrière. Bon donc il faut faire un backup "fichier" des données sensibles.

**Comment by geoffreyc** [comment]
Yup, on en reviens donc a:

**Comment by Alex-D** [comment]
- dépôts git des tutoriels (est-ce qu'ils incluent les images ou non ? si non, les images associées)
- un dump de la BDD
- Les images uploadées par les utilisateurs

**Comment by Eskimon** [comment]
et tout ca pourrait pas se resumer a un gros tar du dossier de l'appli + un export bdd ? (et ensuite upload sur plusieurs ftp et compagnie...) ?

**Comment by firm1** [comment]
Tu l'as bien résumé Eskimon.
- une commande tar (du répertoire zestedesavoir)
- une commande dump
- un upload (FTP/dropbox/etc)

Tout ceci dans un script rajouté en cron tab c'est plié.

En terme de volumétrie : ça revient a ~ 4Go a sauvegarder une fois que tout
les tutos seront importés.
La question est de savoir ou est ce qu'on sauvegarde.

**Comment by Eskimon** [comment]
> La question est de savoir ou est ce qu'on sauvegarde.

Si il y a que ca en attendant de trouver une solution fiable je peux mettre à disposition un bout de mon ftp sur mon mutu (sur 100Go j'en ai qu'une dizaine de pris). La vitesse est pas phénoménale mais pour faire un backup pendant la nuit ca devrait suffir...

**Comment by cgabard** [comment]
Je pense que l'on peut avoir plusieurs espaces de stockage, ce serait même
le mieux

**Comment by Alex-D** [comment]
Au pire, j'ai un dédié bare metal (physique, pas une VM quoi) avec un truc comme 450Go de dispo et la connexion en 100Mbps et pas de limite de bande passante.

Je peux filer un accès SSH sur un compte dédié au backup de ZdS.

Je compte d'ailleurs faire un backup régulier du repo git, car Github c'est beau, mais on ne paye pas donc a 0 garantie.

**Comment by SpaceFox** [comment]
Au pire aussi, j'ai un "serveur" perso (PC chez moi) avec une connexion de
300 Mpbs en téléchargement et un disque dur externe avec plusieurs
centaines de Go dispo. Et une dédibox en Gigabit, avec là aussi un max de
place. Donc on pourra toujours s'arranger.

**Comment by Alex-D** [comment]
On peut faire de la répartition (ou duplication, je ne saurais dire le terme exact) histoire d'avoir au moins 2 serveurs de backup.

Par contre je ne sais plus trop ce qu'il y a comme système de sauvegarde, si quelqu'un a des noms à donner :)

**Comment by SpaceFox** [comment]
Tout dépend de ce qu'on veut avoir. Ca peut aller du simple rsync + cron à
des solutions comme Bacula. Mais vu ce qu'on a, des trucs comme Bacula me
semblent juste overkill.

**Comment by Alex-D** [comment]
Ouais t'as raison avec un simple rsync incrémental ça devrait être bien finalement :)

**Comment by Alex-D** [comment]
Maintenant que notre repo est publique, seules les discutions autour du développement y sont souhaitables. Je "déplace" ce thread en interne.
