### ISSUE TITLE
Les majuscules des noms de catégories sont mal gérées

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4743]
Actuellement, sur la page des [publications de ZdS](https://zestedesavoir.com/bibliotheque/autres/zeste-de-savoir/), il manque les majuscules dans le `placeholder` de la barre de recherche :

![Capture](https://www.pixenli.com/image/Gnby2eKH)

Ce problème est dû au fait que les catégories sont actuellement enregistrées avec une majuscule dans la base de données. Du coup, `lower` est appliqué dans les endroits comme la barre de recherche pour éviter d'insérer une majuscule en milieu de phrase. Cependant, ce comportement est problématique pour les noms propres, qui prennent une majuscule où qu'ils soient dans la phrase.

Selon moi, il faudrait procéder d'une autre manière :

- stocker dans la base des données les noms des catégories en minuscules, sauf pour les noms propres (donc `programmation et algorithmique`, mais `Zeste de Savoir`).
- dans une phrase, afficher simplement ce qui est dans la base.
- dans une liste de catégories, appliquer `capfirst` sur le nom de la catégorie.

**Comment by viki53** [comment]
Pourquoi appliquer des modifications à l'affichage, en fait ?

Une nom de catégorie étant un titre, autant laisser la majuscule partout (et donc plus besoin de `lower` ni `capfirst` derrière), non ?

**Comment by gllmc** [comment]
C'est discutable en effet, mais j'aime bien le fait d'avoir une minuscule pour un nom commun (exemple : « Recherche dans astronomie... »). Dans tous les cas, il faut faire quelque chose car le comportement actuel est incohérent pour les noms propres.

**Comment by viki53** [comment]
Le fait d'avoir une majuscule permet aussi de voir que c'est un titre, donc que ça correspond bien à la catégorie du même nom.

Plus une même chose est affichée de façon cohérente partout mieux c'est.

On est bien d'accord, le `lower` actuel est une mauvaise idée.
