### ISSUE TITLE
Indiquer les notifications dans le favicon du site

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4746]
Ça serait bien d’avoir un petit marqueur de notification dans l’icône du site. GitHub font ça maintenant et c’est vraiment joli.

![github-favicon-notification](https://user-images.githubusercontent.com/15378830/31964582-c4afba48-b904-11e7-9517-ef666e541d3d.png)

Bon après, tant que les notifications n’arrivent pas en “temps réel” c’est assez futile. Mais je pense qu’il peut y avoir pas mal de discussions sur comment rajouter ça à l’icône actuelle du site par exemple. Les avis sur le graphisme sont les bienvenus :upside_down_face:

**Comment by rezemika** [comment]
Si quelqu'un fait la favicon modifiée (je suis une bille en graphisme), je veux bien faire la PR. :)

**Comment by nils-van-zuijlen** [comment]
Voilà ce que je propose : 
![512 svg](https://user-images.githubusercontent.com/22444937/35072676-e0ed50d4-fbe5-11e7-8ad5-092ad79d34e4.png)
J'ai trouvé intéressant d'utiliser un citron comme indicateur.
