### ISSUE TITLE
Ajouter smiley v2 : ^(;,;)^

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#4752]
Bonjour,

Lors de l'issue #4404, il manquait le petit monstre ! Je l'ai en ma possession. Il faudrait le rajouter ici : [assets/smileys](https://github.com/zestedesavoir/zds-site/tree/dev/assets/smileys).

Il s'appelle "cthulhu".

![ctulumachin_hd](https://user-images.githubusercontent.com/18501150/32132530-8777c378-bbc5-11e7-90c2-ad6f0b05c625.png)
![ctulumachin](https://user-images.githubusercontent.com/18501150/32132531-8797e9f0-bbc5-11e7-9d17-0bdb8d4e89f7.png)

---

Vous voulez le voir de plus près ? C'est en bonus : :D 

![ctulumachin](https://user-images.githubusercontent.com/18501150/32132539-a731f5e4-bbc5-11e7-9201-a45a04c16228.png)

**Comment by Anto59290** [comment]
A fermer puisque la PR a été mergée
