### ISSUE TITLE
Typage statique via mypy

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4755]
Que pensez-vous de commencer à typer statiquement des parties des sources avec [mypy](http://mypy.readthedocs.io/en/stable/introduction.html) ?

Notez que ça ne veut pas dire du tout que les sources de ZdS vont être traduites en un espèce de Java illisible avec des noms de classe abstraites et d’interfaces génériques à rallonge après chaque paramètre de chaque fonction. On n’est absolument pas obligé de tout typer, je pense que l’idée est avant tout d’éviter les erreurs courantes en ne typant que ce qui n’est pas trop dur.

Ça permettrait aussi de simplifier certaines docstrings rébarbatives qui n’indiquent pas grand-chose d’autre que les types.

Évidemment ça demande de passer de Python 3.4 à Python 3.5 mais je ne pense pas que ce soit un problème.

**Comment by artragis** [comment]
> Mypy is still experimental. There will be changes that break backward compatibility.

en attendant, on peut ajouter des annotations dans les nouvelles fonctions qu'on créé, ça , ça ne me dérange pas.

**Comment by motet-a** [comment]
Ouais. Concernant la stabilité de mypy je pense que c’est OK. Déjà la [PEP 484](https://www.python.org/dev/peps/pep-0484/) a été publiée en 2014 (donc ça fait un paquet de temps), et après avoir fait un tour sur leur Gitter, on m’a dit que mypy serait quelque part entre la alpha et la bêta, donc même si la v1.0 va un peu casser des choses, il n’y aura pas de gros changements incompatibles par la suite : ils seraient déjà utilisés par des tas de projets sérieux de boîtes sérieuses et ils évitent déjà vraiment de casser les choses sauf nécéssité absolue.

En tout cas, tant qu’on n’utilise pas des fonctionnalités farfelues, on devrait pouvoir y aller les yeux fermés.

**Comment by motet-a** [comment]
Et concernant la migration, il va falloir y aller petit bout par petit bout dans tous les cas. Donc oui, l’idée serait de rajouter ça dans le nouveau code et de refactorer plus doucement le vieux code.

**Comment by motet-a** [comment]
![image](https://user-images.githubusercontent.com/15378830/32147181-6c1e4fb0-bce3-11e7-9394-23b1d66cd165.png)

Bon, Guido en personne a répondu à ma question :)
