### ISSUE TITLE
Faire un truc intelligent pour les `import json`

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4759]
Actuellement, on utilise soit `json` en dev, soit `ujson` en prod. Du coup, il y a des choses comme ça un peu partout : 

https://github.com/zestedesavoir/zds-site/blob/56c3126c0b5df20fd5344b20716ea6e93eb54641/zds/tutorialv2/tests/tests_views.py#L40-L46

Ça serait beaucoup plus joli de faire un fichier `zds/utils/json.py` avec ça dedans et de remplacer tout ça par des `import zds.utils.json`. Et il faudrait en profiter pour renommer les variables `json_reader` et `json_writer` en `json`, tout simplement.

Ah, et le deuxième `except` est assez imprudent, il faudrait le remplacer par un `except ImportError`.

**Comment by artragis** [comment]
faurait pas appeler le fichier json.py (pour pas écraser le module json de python) par contre effectivement, on peut faire un fichier d'utilitaire autour du json.

**Comment by motet-a** [comment]
Pas avec Python 3, non ? Il me semble bien que dans le dossier `zds/utils/`, `import json` va toujours importer le module `json` de Python alors que `import .json` va toujours importer le module `zds.utils.json`, non ?

http://pulkitgoyal.com/absolute-relative-imports

(Ça serait quand-même choquant que le système d’imports de Python 3 soit cassé à ce point :upside_down_face:)

**Comment by motet-a** [comment]
En fait, quand j’y pense, ceci explique peut-être les noms à rallonge un peu rébarbatifs de certains fichiers. (Mais bon, c’est un autre problème.)

**Comment by gllmc** [comment]
Voilà qui est fait, merci @artragis !
