### ISSUE TITLE
Le modèle d'alertes est complètement HS

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#476]
Le modèle d'alertes ne fonctionne tout simplement pas, et marche par mégarde sur les forums :(
- Le modèle de données permet d'avoir une même alerte sur plusieurs contenus, ce qui n'a aucun sens.
- Le menu de notification des alertes affiche le compte global d'alertes, mais n'affiche que les alertes sur les posts de forums
- Les alertes sur les articles semblent fonctionner, mais il faut retrouver à la main l'alerte sur les articles
- Les alertes sur les tutos semblent ne pas fonctionner du tout

Je propose de casser le truc et de refaire un système d'alertes qui fonctionnerait ainsi :
- Tous les "posts" sont des `utils.Comment` (posts de forums, commentaires de tutos, commentaires de forums, MPs, etc.). (déjà en place).
- Une alerte porte directement sur un `Comment`.
- Conséquence : une alerte ne peut pas porter sur autre chose (Titre d'un topic, contenu d'un tuto/article, etc.)
- Pour éviter les prises de tête avec l'introspection, le modèle de données est dénormalisé, et on a, à l'intérieur de l'alerte, l'information du type de contenu sur lequel elle porte (au lieu de remonter au Comment lié et de rechercher de quel type il est vraiment).
- Un `Comment` peut avoir de 0 à N alertes
- Une alerte porte sur un et un seul `Comment`
- Une alerte a obligatoirement une date de création
- Les alertes sont supprimées quand résolues
- Le menu "Alertes modération" montre les 10 alertes les plus récentes, quel que soit le type, et indique le nombre total d'alertes
- Une page liste toutes les alertes, quel que soit le type
- Pour que ça fonctionne, chaque `Comment` est accessible via une URL absolue

Attention : si je fais ça, à la migration, toutes les alertes seront perdues !

Des objections ?

**Comment by SpaceFox** [comment]
Ha tiens, les MPs ne sont pas liés aux `Comments`... Je peux le faire, mais là aussi ça implique de perdre tous les MP à la migration.

**Comment by Alex-D** [comment]
Je ne comprends pas ça : 

> Pour que ça fonctionne, chaque Comment est accessible via une URL absolue

Ca y est déjà non ? Ou tu veux dire : construire une URL qui va rediriger vers la bonne page avec la bonne ancre ?

Sinon, je suis plutôt d'accord.

Perdre les alertes : on s'en fou.

Perdre tous les MP : on s'en fou, c'est une beta... fermée qui plus est.

**Comment by SpaceFox** [comment]
> Ca y est déjà non ? Ou tu veux dire : construire une URL qui va rediriger vers la bonne page avec la bonne ancre ?

En fait, aujourd'hui, je n'ai pas de **garantie** que ça marche.
Si j'étais en Java, je collerais une méthode abstraite sur Comment (qui
n'est jamais utilisé seul) et qui me garantit que j'ai une méthode
get_absolute_url.

Je ne sais pas si je l'ai aujourd'hui et je ne sais pas si je peux la
forcer ; ou si il suffit qu'elle soit implémentée dans toutes les
sous-classes pour que ça marche si je fait (instance de sous-classe de
Comment).get_absolute_url().

**Comment by Alex-D** [comment]
Les méthodes abstraites n'existent pas en Python ?

**Comment by SpaceFox** [comment]
A priori, c'est pas vraiment dans la philosophie du truc :
http://stackoverflow.com/questions/4382945/abstract-methods-in-python

**Comment by Alex-D** [comment]
Bof, ça a l'air jouable quand même. Dans le cas présent, ça éviterais des oublis.

**Comment by Coy0te** [comment]
Point de vue conception, tout cela me paraît judicieux. 
Pour tout ce qui est framework django et python, l'aval de firm1 fera le plus grand bien. =)

Sinon, vu qu'a priori c'est pas dans ce que tu as prévu, la possibilité de filtrer les alertes par type de contenu sur lequel elles portent (articles, posts, mp, etc.) dans la page qui liste toutes les alertes, ça serait pas mal.

**Comment by coma94** [comment]
Pluzun.
Ça peut être pratique de pouvoir ne voir que le type d'alerte nous intéressant (je pense par exemple aux validos comme moi que la modération des forums n'intéresse pas trop)

**Comment by Alex-D** [comment]
Les filtres c'est quedal à faire une fois que le modèle est bien fait.

**Comment by SpaceFox** [comment]
Bon, j'ai MAJ le modèle.

C'était plus facile ce que je que je craignais. Par contre ce qui m'inquiète c'est que les tests continuent à passer alors que je n'y ai pas touché - pourtant les alertes sont bien testées. Je suppose que les tests vérifient l'existence de l'alerte mais pas son contenu ?

Reste à faire :
- La page de toutes les alertes (ça devrait être simple)
- Limiter le nombre d'alertes dans le menu de notifs
- Convertir les MPs au modèle "Comment". Là je sais pas si c'est vraiment pertinent, parce que ça a de gros impacts :
  - Ajout de données inutiles sur les MP (exemple : +1/-1, même si c'est pas intégré HTMLiquement)
  - Problématique des droits d'accès aux MP

**Comment by SpaceFox** [comment]
(Quoiqu'il en soit, si je tente la MAJ des MP, ce sera sur une branche séparée)

**Comment by Alex-D** [comment]
Selon moi, il ne faut pas toucher aux MP.

Les alertes sur des MP, si elles doivent exister, doivent être signalées sur le topic et non sur un message particulier. Ca reste mon point de vue.

**Comment by SpaceFox** [comment]
Pour le coup je ne saisis pas bien ta logique.
Le 11 mai 2014 01:42, "DEMODE Alexandre" notifications@github.com a écrit
:

**Comment by Alex-D** [comment]
Ma logique c'est que, si on doit pouvoir alerter les MPs, il faut alerter le thread, ainsi on donne accès aux membres qui en ont les droits (modos, etc) au topic en question.

En tous cas sur le SdZ c'était comme ça dans mes souvenirs, et ça me semble assez logique.

Si maintenant tu considère qu'un mec doit pouvoir alerter un message précis, why not. Mais ça veut dire que pour une même conversation on peut se retrouver avec n alertes.

**Comment by GerardPaligot** [comment]
Si des alertes doivent être faites sur des messages privés, je suis pour suivre la même logique que pour tous les autres `Comment`.

Par contre, ça risque d'être vraiment chiant en ce qui concerne la technique (permission) mais aussi légalement. Je ne suis pas un expert en la matière mais cela ne touche-t-il pas les droits sur la vie privée de nos membres ?

De plus, si ça rajoute des fonctionnalités inutiles pour les MP, je suis moins chaud.

> HTMLiquement

J'ai rigolé. :)

**Comment by SpaceFox** [comment]
En fait pour moi, fonctionnellement, un MP = un forum privé. Donc privé des
options qui n'ont plus de sens, comme les post-it ou les +1.
Du coup je ne vois vraiment pourquoi on ne pourrait pas en signaler un
message précis.

Plus généralement mes questions quant aux MP portent sur la vie privée et
la technique pure. Ces deux points font que toute modif des MP devra passer
par une phase de bêta **privée**.
Le 11 mai 2014 01:46, "DEMODE Alexandre" notifications@github.com a écrit
:

**Comment by Alex-D** [comment]
Sur le SdZ, un MP était privé tant qu'il n'était pas alerté. S'il était signalé, les modos y avaient accès.

Le bouton de signalement le précisait expressément genre "En signalant cette conversation privée, vous autorisez les modérateurs à lire l'ensemble de celle-ci.".

**Comment by SpaceFox** [comment]
D'un point de vue technique, un Comment contient les infos suivantes qui ne seront pas spécialement utiles aux MPs :
- Like
- Dislike
- Editeur (utilisateur qui a édité le message)
- Message d'édition
- Message masqué
- Raison du masquage

Si les intégrations FO ne sont pas mutualisées, c'est juste des champs en trop dans la base, ce dont on se fiche un peu (c'est pas comme si y'en avait 50 ou qu'ils étaient obligatoirement remplis).

Du coup le principal problème technique est bien cette histoire de droits d'accès, je suppose... à creuser.

**Comment by Alex-D** [comment]
Je ne comprends pas où est le soucis des droits d'accès. Un MP, c'est un thread, tu n'autorise que les participants SAUF si un des messages est signalé, auquel cas il faut autoriser le staff.

**Comment by SpaceFox** [comment]
> Du coup le principal problème **technique** est bien cette histoire de droits d'accès, je suppose... à creuser.

Je ne sais pas comment c'est géré, je ne sais pas quelles sont les implications de toucher à ça, je ne sais pas comment donner l'autorisation de lecture à quelqu'un qui n'est pas dans le MP, je ne sais pas comment les enlever une fois l'alerte résolue, je ne sais pas quelles peuvent être les failles et les risques de sécurités induits par ce genre d'ajouts. C'est en ça que c'est un problème. Et c'est pour ça que ça devra sans doute passer en bêta privée avant d'être mis en public.

**Comment by Alex-D** [comment]
Aah ok, je n'avais pas compris comme ça.

Ca a l'air simple à gérer, actuellement il y a ces lignes :

``` python
if not g_topic.author == request.user and not request.user in list(g_topic.participants.all()):
    raise PermissionDenied
```

Du coup, c'est qu'une question d'algo.

**Comment by firm1** [comment]
Alors, je vais essayer de faire court.

> Le modèle d'alertes ne fonctionne tout simplement pas, et marche par mégarde sur les forums

+1, elles sont stockée, mais pas forcément de la meilleure des manières.

> Je propose de casser le truc et de refaire un système d'alertes qui fonctionnerait ainsi : 
> - [...]
> - Pour que ça fonctionne, chaque Comment est accessible via une URL absolue

Tu l'as peut-être déjà remarqué dans tes recherches, faire des classes abstraites dans le modèles avec django ce n'est pas trop ça. Tout simplement parce que lorsque tu manipules tes objets, le polymorphisme à ce niveau est plutôt atypique. Je dis ça, parce que je l'ai essayé à l'époque, et pour moi ce n'était pas viable. Ceci dit, rien ne t’empêche d’insérer à chaque fois la méthode dans les classes filles et de l'utiliser en conséquence.

> - Une alerte porte directement sur un Comment.

Et c'est là que je deviens dubitatif, car comme tu l'as dis, ça revient à mettre dans la classe Alert une foreign_key de type id_comment. Cependant, pour retrouver à partir d'une alerte le type de commentaire (forum, article, tuto, etc.) lié, il m'est avis que tu risques de faire quelque chose de sale.

> Ha tiens, les MPs ne sont pas liés aux Comments...

Alors, a l'époque, j'ai fais le choix de séparer vraiment les MP qui sont vraiment privé, et les autres commentaires. Car je ne savais pas forcément jusqu'ou on allait aller, et qu'en combinant les deux, il y'a une énorme problématique de sécurité à gérer (référencement extérieur, visibilité des mps, recherches de commentaires, etc.). J'avais donc fait le choix de les isoler à l'époque, et aujourd'hui, je vois les deux (mp et commentaires) évoluer de façon différentes, avec des régles de gestions différentes. Donc je ne suis pas "encore" pour joindre les deux. Mais ce n'est qu'une avis.

**Comment by SpaceFox** [comment]
OK, merci pour tes réponses.

> Et c'est là que je deviens dubitatif, car comme tu l'as dis, ça revient à mettre dans la classe Alert une foreign_key de type id_comment. Cependant, pour retrouver à partir d'une alerte le type de commentaire (forum, article, tuto, etc.) lié, il m'est avis que tu risques de faire quelque chose de sale.

En fait, hier j'ai essayé en descendant les alertes au niveau des sous-classes de Comment. Eh bien en fait c'est 10x plus bordélique que la solution que j'ai trouvé, cf la branche issue_476_alerts que j'ai poussée hier soir, dont les modifications sont en fait plutôt simples.

La ligne de récupération des sous-classes https://github.com/Taluu/ZesteDeSavoir/blob/issue_476_alerts/zds/utils/models.py#L216 correspond dans les faits à cette requete :

```
SELECT [... plein de trucs]
FROM "utils_comment"
LEFT OUTER JOIN "article_reaction" ON ( "utils_comment"."id" = "article_reaction"."comment_ptr_id" )
LEFT OUTER JOIN "forum_post" ON ( "utils_comment"."id" = "forum_post"."comment_ptr_id" )
LEFT OUTER JOIN "tutorial_note" ON ( "utils_comment"."id" = "tutorial_note"."comment_ptr_id" )
WHERE "utils_comment"."id" = %s
```

Ce qui n'est pas déconnant et plutôt performant, d'autant que ces requêtes ne sont faites qu'en petit nombre et seulement pour les membres du staff.

Sinon pour les MP, je comprends bien ta logique.
Mais du coup, que décide-t-on ?
- On a pas d'alertes sur les MP ?
- On a un système d'alertes sur les MP, mais complètement parallèle ? (ce que je n'aime pas, ce serait à 90% de la duplication de code)
- On réintègre les MP comme des Comments et on blinde les tests ?

**Comment by Alex-D** [comment]
Mon avis est d'appliquer la solution 3 : réintégrer les MPs en Comments.

**Comment by coma94** [comment]
N'ayant pas été modo sur le sdz je me pose une question: est ce que
l’alerte MP était souvent utilisée ?

2014-05-11 14:52 GMT+02:00 DEMODE Alexandre notifications@github.com:

**Comment by firm1** [comment]
> Sinon pour les MP, je comprends bien ta logique.
> Mais du coup, que décide-t-on ?

Mon avis est : On a pas d'alertes sur les MP !

On peut déjà sortir  d'un MP si on a pas envie et/ou inviter un modo si besoin. Donc l'alerte MP, ne sert pas forcément je pense.

**Comment by SpaceFox** [comment]
> On peut déjà sortir d'un MP si on a pas envie et/ou inviter un modo si
> besoin. Donc l'alerte MP, ne sert pas forcément je pense.

Tous les protagonistes peuvent ajouter de MP ?

Sur le SdZ il me semble que les alertes MP servaient parce que seul le
créateur du MP pouvait y rajouter des gens (modulo les droits staff).
Si chez nous tout le monde peut, alors on a en effet pas besoin d'alertes
sur les MP et le sujet est clos.

**Comment by ShigeruM** [comment]
Les alertes MP sont utiles pour les cas où un membre envoie 15000 MP à un
peu tout le monde pour faire sa pub, demander de l'aide à tout va, ou pire
essayer de truander des gens. Bref, les envois en nombre.

Si on n'a pas les alertes de MP, il faudra au minimum surveiller un peu la
base (membres avec le plus grand nombre de MP envoyés...).

**Comment by Alex-D** [comment]
Après, l'option "ajouter un modo" on est 30... pas toujours dispo, alors
que s'il y a une alerte, il y aura quelqu'un pas loin.

Selon moi, dans le doute c'est un truc non prioritaire à faire par la
suite, mais ça serait bien de le faire.

Aussi actuellement, seul l'OP du MP peut ajouter des participants.

**Comment by SpaceFox** [comment]
> Selon moi, dans le doute c'est un truc non prioritaire à faire par la suite,
> mais ça serait bien de le faire.

Justement : on parle d'une solution qui casse tous les MP et nous oblige à
supprimer tous les MP si on l'implémente. D'où le fait qu'il faut décider
maintenant !

D'où ce débat.

> Aussi actuellement, seul l'OP du MP peut ajouter des participants.

Je viens de tester, ce n'est pas le cas (cf tes MP).
Ou alors je suis considéré comme l'OP de mes MPs d'alertes ?

**Comment by firm1** [comment]
Fix'd
