### ISSUE TITLE
Espace insécable avant un signe de ponctuation

### ISSUE THREAD

**Issue by Monadologie** [zestedesavoir/zds-site#4768]
Le Markdown n'ajoute pas les espaces insécables avant tout signe de ponctuation (point d'exclamation, point d'interrogation, point-virgule, etc.).

**Comment by Monadologie** [comment]
Je prends.

**Comment by artragis** [comment]
arrivera avec zmd.

**Comment by motet-a** [comment]
https://github.com/zestedesavoir/zmarkdown/tree/master/packages/typographic-question-mark

**Comment by motet-a** [comment]
Mais il reste encore un peu de travail sur cette nouvelle implémentation de zmarkdown et tout aide là dessus est la bienvenue.
