### ISSUE TITLE
Utiliser des managers

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#477]
Actuellement, certains fichiers du projet (les modèles et les vues généralement) sont vraiment immenses (on atteint facilement plus de 1000 lignes). A ce niveau là, je connais pas les bonnes pratiques du développement python mais en tant que développeur Java, ça m'horrifie.

Dans l'optique de diminuer le nombre de lignes et de retirer certaines responsabilités à quelques classes existantes, j'ai fais quelques recherches et je suis tombé sur ce [site](http://lincolnloop.com/django-best-practices/applications.html).

Les explications sont minces mais on a une indication des fichiers qu'on retrouve couramment dans un module Django et surtout un exemple d'utilisation des managers. J'aimerais avoir votre avis sur une potentielle intégration de ces managers dans notre projet.

**Comment by SpaceFox** [comment]
Je suis pour réduire ces fichiers immenses.
Je j'ai pas la moindre idée du comment.

Pour ce qui est des managers, j'en introduit un dans ma nouvelle branche
sur les alertes. J'ai j'ai peur que ce soit limité aux modèles, or il me
semble que nos longs fichiers sont des vues ?

**Comment by GerardPaligot** [comment]
C'est lié à tous les endroits où nous effectuons des requêtes SQL avec des filtres. Mais effectivement, jusqu'à présent, on a essayé de les concentrer au maximum dans nos modèles.

Donc oui, ça ne va pas réduire considérablement nos fichiers mais c'est déjà un premier pas dans ce sens. Il faudrait se renseigner sur d'autres pratiques parce que je trouve pas normal d'avoir des fichiers aussi immenses. Pour moi, c'est un indicateur d'un souci de conception.

PS : Le manager est une pratique utilisée dans Django comme en [témoigne la classe](https://github.com/django/django/blob/ff6ee5f06c2850f098863d4a747069e10727293e/django/contrib/auth/models.py#L257) `User`.

**Comment by SpaceFox** [comment]
Pareil, j'ai aussi du mal à imaginer que c'est normal.

**Comment by SpaceFox** [comment]
Les ressources que je vois concernant les vues tournent souvent autour de
ce genre de solutions :
http://stackoverflow.com/questions/1921771/django-split-views-py-in-several-files
La doc Django ne mentionne jamais ce problème.

Certains disent que c'est une mauvaise pratique.
J'ai l'impression qu'on est pas sensés avoir autant de code dans les vues
sans pour autant en être sûr.

**Comment by GerardPaligot** [comment]
J'y avais pensé. J'aurais espéré trouver une meilleure solution. Mais s'il existe que celle là, je suis pour l'utiliser parce qu'il est parfois difficile de s'y retrouver dans le fichier `views.py`.

**Comment by firm1** [comment]
Comme vous l'avez remarqué, l'utilisation des managers ne permettra pas de réduire la taille de nos fichiers, et on a tellement de cas différents a traiter que je pense même qu'en les utilisant on finira avec plus de code sous le coude.

Ceci dit, concernant la taille des fichiers, on a une masse de code, et c'est normal dans le sens ou le site fait beaucoup de chose, donc a un moment supprimer des lignes signifient supprimer des features.

Après si on veut les splitter convenablement, il y'a deux façon de faire : 
- A la Java : ou on a plein de fichiers qui font chacun une chose particulière
- Comme actuellement : ou on a quelques fichiers et pleins de fonctions.
- Entre les deux : ou tout ce qui ne concerne pas directement la view est mis dans un répertoire a part avec des conventions du le nom des fichiers pour se reperer d'un coup d'oeil.

Perso, je préfère la solution 3, mais je n'ai vraiment pas envie non plus de me retrouver avec plein de fichier partout. Il n'y a rien de mieux pour décourager le nouveau contributeur potentiel.

**Comment by GerardPaligot** [comment]
Je ne connais pas du tout les bonnes pratiques Django mais,
personnellement, voir un fichier de plus de 3k lignes, ça me décourage plus
que de répartir les choses dans différentes classes/fichiers avec leur
responsabilité chacune. Mais c'est peut-être parce que je suis un
développeur Java que je dis ça.

Donc le manager ne réduira pas le code mais centralisera une
responsabilité. Pour moi, c'est tout autant bénéfique.

**Comment by firm1** [comment]
Je crois que je vais devoir te citer quelques paragraphes de la [PEP-20](http://legacy.python.org/dev/peps/pep-0020/) (la philosophie python) : 
- Complex is better than complicated : **Le complexe est préférable au compliqué**
- Flat is better than nested : **les imbrications (de code ou de fichier ndlr) sont à éviter** 
- Special cases aren't special enough to break the rules : **les cas exceptionnels ne sont pas assez exceptionnels pour changer une règle**
- Although practicality beats purity : **Le coté pratique doit primer sur la pureté**

**Comment by SpaceFox** [comment]
Tant qu'on en est à citer la PEP-20, personnellement j'ai un faible pour celle-ci :
- Now is better than never.

**Comment by GerardPaligot** [comment]
> Le coté pratique doit primer sur la pureté

Rien que pour ce point, je ne serais jamais développeur python.

Sinon, je ne comprends pas si tu cites tout ça pour la taille des fichiers ou pour le manager qui est une bonne pratique django ?

**Comment by SpaceFox** [comment]
> Rien que pour ce point, je ne serais jamais développeur python.

Je pensais comme toi à une époque. Et depuis, j'ai découvert qu'on pouvait
faire "pratique" sans faire "dégueulasse, incompréhensible et impossible à
maintenir" ; et qu'au contraire "pur" est souvent synonyme de "perdre du
temps à sodomiser des diptère pour le plaisir"... du coup je sus plutôt
d'accord avec cette phrase de la PEP.
Plus généralement, j'ai déjà gagné du temps grâce à un code "pratique",
jamais grâce à un code "pur".

**Comment by cgabard** [comment]
De façon général je ne suis pas sûrs qu'il soit pertinent de rentrer dans un debat Java Vs Python. Déjà parce que ce n'est pas le lieu mais aussi et surtout parce qu'ils ont des philosophies radicalement différentes.

Dans tous les cas, faut être conscient qu'on est un GROS projet. Si on attend que chaque ligne est parfaite à l'espace pret, on ne le sortira jamais. Pour la v1 au moins, il faut être pragmatique. Ensuite on pourrat améliorer les choses.

**Comment by GerardPaligot** [comment]
Les choses s'améliorent sur ce point. Avec l'API, les managers sont apparus naturellement pour éviter la répétition du code. Cependant, cette issue est inutile puisqu'aucune PR se chargera d'utiliser les managers pour chaque requête (cela ne serait pas très pertinent d'ailleurs). Je ferme.
