### ISSUE TITLE
Faire en sorte que Travis regarde automatiquement si il ne manque pas des migrations

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4774]
@gcodeur a toujours la gentillesse et la patience de vérifier ça à la main à chaque PR parce qu’il y a toujours des étourdis comme moi qui n’y pensent jamais. Soyons gentils avec @gcodeur.

Je pense qu’un simple `./manage.py makemigrations --check` suffit.

**Comment by gllmc** [comment]
Il faudrait préciser comment faire pour ajouter le tag `Facile`, je l'enlève en attendant. :)

**Comment by motet-a** [comment]
Comme ça c’est bon ? :upside_down_face:

**Comment by gllmc** [comment]
Oui, c'est parfait :+1:
