### ISSUE TITLE
Déplacer l'action "Marquer comme résolu" pour le staff

### ISSUE THREAD

**Issue by Anto59290** [zestedesavoir/zds-site#4775]
Les membres du staff peuvent marquer un sujet comme résolu. J'aurais 2 remarques à ce propos.

##  Déplacer le bouton dans la zone de Modération

Tout d'abord, si ce n'est pas l'auteur du sujet qui marque le message comme résolu, il s'agit d'une action de modération : il convient donc de déplacer le bouton *Marquer comme résolu* dans la zone appropriée afin d'éviter les fausses manipulations de la part des membres du staff :

![Interface pour marquer comme résolu](https://zestedesavoir.com/media/galleries/3753/eff9bf80-5eed-4523-931a-2958dafa4d14.png)

- si le membre connecté est l'auteur du sujet : bouton *Marquer comme résolu* dans la zone *Action* ;
- si le membre connecté fait partie du staff et qu'il n'est pas l'auteur du sujet : bouton *Marquer comme résolu* dans la zone *Modération*.

Sujet : https://zestedesavoir.com/forums/sujet/9614/a-propos-des-sujet-marque-comme-resolu-par-le-staff/
*Envoyé depuis Zeste de Savoir*

**Comment by motet-a** [comment]
(Ça serait top de faire deux issues différentes :upside_down_face:)

**Comment by Anto59290** [comment]
Done: #4776
