### ISSUE TITLE
Faciliter les propositions de mises en une

### ISSUE THREAD

**Issue by Anto59290** [zestedesavoir/zds-site#4779]
Aujourd'hui pour proposer au staff la mise en une d'un sujet du forum deux possibilités existent :
- Poster un message dans le topic approprié
- Envoyer un message au staff (alerte ou MP)

Le but de ce ticket est de rendre plus simple la proposition de mise en une de sujets du forum. Pour ce faire l'idée est d'ajouter un lien "Proposer pour la mise en Une" dans la sidebar Partage du sujet. Au clic deux idées ont été proposées :

- Poster un message dans le topic (un peu comme pour la mise en bêta). Ce qui est cool c'est qu'on aurait les pouces pour appuyer une proposition d'un autre membre. En inconvénients on aura peut être plusieurs messages d'affilé pour un même topic à mettre en avant.
- Envoyer une "proposition" au staff, ces derniers ont une page récapitulant l'ensemble des demandes et peuvent aller voir le sujet en question. Si plusieurs membre proposent la mise en avant d'un même sujet, les demandes sont agrégées. Le staff peut ainsi facilement voir les demandes les plus populaires. **Avantages**: pas de flood sur le forum, on peut retirer le sujet du forum, plus clair pour le staff, plus évolutif. **Inconvénients** : plus complexe à mettre en place, pas de visibilité pour les membres de ce qui a été proposé.

Lien vers le sujet : https://zestedesavoir.com/forums/sujet/9647/les-contenus-mis-en-une/?page=2#p165875

**Comment by viki53** [comment]
Les propositions pourraient être faites en *upsert* avec plusieurs auteurs, ça permettrait de les remonter tout en ayant une idée de l'intérêt pour la mise en Une.

Et pour la Comm' ça fait plus qu'un clic sur un bouton pour valider la publication : les membres sont plus investis et on a moins de boulot, c'est tout bénéf' ! 😃

**Comment by Anto59290** [comment]
Salut @viki53 

J'ai du mal a comprendre ce que tu veux dire par la. Est ce que tu veux dire que dans la deuxième idée d'implémentation on aurait pour un topic à mettre en Une le pseudo des utilisateurs ayant demandé la mise en Unes (et donc leur nombres).  Par exemple si on est 2 a demander une mise en Une sur un même topic on aurait une ligne "Super Topic proposé par viki53 et Anto59290" plutot que une ligne "Super Topic proposé par Viki53" et une autre "Super Topic proposé par Anto59290" ?

**Comment by viki53** [comment]
Je verrais plutôt une seule ligne par contenu, avec la liste des utilisateurs l'ayant proposé au bout.

**Comment by Anto59290** [comment]
Ok, je crois que j'ai compris ce que tu voulais dire, je pensais aussi a quelque chose dans ce genre. Je vais clarifier un peu le ticket ;)

**Comment by motet-a** [comment]
Du coup, vous comptez créer un topic à la première proposition et modifier le titre à chaque fois que quelqu’un refait la même proposition ?

(Le seul truc qui me dérange c’est que ça va charger encore un peu plus la sidebar qui est déjà bien chargée. Mais je pense qu’il faudrait faire quelque chose de propre pour toute la sidebar, et ne pas se priver de cette fonctionnalité)

**Comment by Anto59290** [comment]
@motet-a : On ne s'est pas compris je pense. Si on utilise la proposition 1 on poste un message dans le topic dédié (comme c'est fait aujourd'hui à la main par certains membres). Si on utilise la proposition 2 la liste des proposition faites au staff ne passe pas par un topic. 

Je sais pas si c'est clair :p

**Comment by motet-a** [comment]
Ah OK. Mais à mon avis, il vaut mieux simplement mettre des +1 plutôt que de poster un message à chaque fois, non ?

**Comment by motet-a** [comment]
Ouais quoi que ça ne devrait pas flooder tant que ça. Oubliez ce que j’ai dit :upside_down_face:

**Comment by gllmc** [comment]
> Inconvénients : plus complexe à mettre en place, pas de visibilité pour les membres de ce qui a été proposé.

Par rapport à ce deuxième point, je pense que rien n'empêche de mettre cette page en accès public et n'activant les boutons de décision que pour l'équipe de com', ça me semblerait être une bonne solution en terme de transparence. :)

**Comment by Anto59290** [comment]
Yep ça parait pas mal ;)

**Comment by A-312** [comment]
J'espère que cette fonctionnalité sera utile à l'équipe du site.

~~Si les membres pouvaient proposer une image ça aiderait l'équipe de com'. La différence de format est problématique et fait perdre beaucoup de temps dans la plupart des cas.~~
