### ISSUE TITLE
Mascotte : Clem' la clémentine

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#478]
À une époque on avait une chouette proposition de mascotte, "Clem' la clémentine".

Ce serait vraiment sympa de la ressortir !

**Comment by firm1** [comment]
Pour Info : 

![wip-lama-002](https://cloud.githubusercontent.com/assets/6066015/2939414/204a5dc4-d946-11e3-9940-ddf8bef15aa9.jpg)
![wip-lama-clemy-001](https://cloud.githubusercontent.com/assets/6066015/2939415/204da02e-d946-11e3-8047-ddb2eb96d077.jpg)

**Comment by Alex-D** [comment]
J'ai envoyé un email privé à MaxRoyo, il n'a plus le temps mais m'a autorisé à reprendre la main dessus (ou quiconque le souhaite).

Pour l'instant je boost sur l'intégration. Si quelqu'un se sent de nous faire une Clementine funky, go.

**Comment by Alex-D** [comment]
Je propose vite fait ça en privé : ça vous tenterais de faire comme Github avec l'Octodoc ? C'est à dire proposer aux membres de nous envoyer leur version de notre mascotte (bien sûr il faudrait déjà qu'elle soit fixée pour nous).

Ça me paraît intéressant, on pourrait ainsi avoir une version pour l'erreur 403, 404, 500, ... et d'autres !

**Comment by SpaceFox** [comment]
J'aime bien l'idée.

**Comment by ShigeruM** [comment]
J'aime bien aussi.

Pour revenir à la mascotte en tant que telle, j'aime bien l'idée d'une
Clémentine qui se nommerait Clémentine mais qu'on appellerait "Clém". On
est tous en phase avec ça ?

**Comment by cgabard** [comment]
On peut pas demander aux beta testeurs si il y en a un motivé pour nous la faire ? Ou en recruter un autre ?

**Comment by ShigeruM** [comment]
> On peut pas demander aux beta testeurs si il y en a un motivé pour nous
> la faire ? Ou en recruter un autre ?

Ah oui super idée pour les bêta-testeurs ! En leur demandant s'ils ne
connaissent pas du monde qui pourrait nous aider là-dessus, histoire
d'élargir les possibilités.

**Comment by Alex-D** [comment]
Je n'ai pas trop le temps de la faire ni de m'occuper des gens et tout ça, mais par contre j'aimerais pouvoir filtrer un minimum en ce sens où ça doit garder une certaine cohérence et que ça colle avec ce qu'on a déjà : design et logo.

https://octodex.github.com/ : tout est vectoriel et on reconnaît clairement l'Octocat à chaque fois, c'est ça que je veux dire par "filtrer".

Aussi il faudra choisir la "Clem" officielle : celle qu'on utilisera sur la home par exemple, pour dire la phrase aléatoire (rappelez-vous Zozor à droite avec la bulle). Pour ça rien de plus simple : on donne jusqu'à la fin de la beta design (qui va arriver très bientôt) pour faire la Clem, on fait un topic où chacun post ses créa (et uniquement ses créa, pas de com etc) et on vote avec les +1/-1 pour celle qu'on veut. Suffira de faire les décomptes et on aura l'heureuse élue.

Bien sûr, je ne suis pas dieu et n'ai pas la science infuse, donc vous pouvez proposer autre chose si vous avez un moyen plus fun de voir le truc.

**Comment by ShigeruM** [comment]
Attendons déjà de voir si on a des retours, on verra alors comment les
départager. Si on a 2 ou 3 Clém, ce serait déjà génial.

**Comment by Alex-D** [comment]
En effet, je m'emballe peut-être un peut trop :-°
Du coup tu t'en charges Shig' ?

**Comment by Eskimon** [comment]
Et MaxRoyo ? Il t'a répondu un jour ou pas ?

**Comment by Alex-D** [comment]
Je l'avais dit je ne sais plus où mais oui il a répondu : il n'a plus le temps, il autorise qui veut à utiliser ou non ses idées (car à la base il me semble que l'idée du lama et de la clémentine c'est quand même lui).

Donc on est libres à ce niveau là, mais lui ne pourra pas nous aider a priori.

**Comment by Eskimon** [comment]
Sur Feu SdZ il y a Mogolecho qui avait fait [une illu' pour les JSdZ Strasbourg](http://fr.openclassrooms.com/forum/sujet/atelier-une-identite-visuelle-pour-les-jsdz?page=3#message-84417584) (auquel il s'est joint une fois ou deux)

Ca pourrait ptet l'intéresser je sais pas...

**Comment by cgabard** [comment]
Si vous avez des contacts graphistes, faites ! Transmettez. Toute aide est
bonne a prendre. La seule condition que j'imposerai c'est la licence : faut
pas qu'on soit emmerdé a terme, ni nos membres qui feraient des
détournement. Donc une cc-by serait cool

**Comment by geoffreyc** [comment]
Jiyong (qui a quand meme fait tout les zorors! :
http://www.jiyong.eu/folio/zozor/) serait peut etre assez gentil pour nous
faire ca? Il est tres fort a dessiner les fruits et legumes !
http://www.jiyong.eu/folio/images/fel/002.png

2014-05-14 17:02 GMT+01:00 Christophe Gabard notifications@github.com:

> Si vous avez des contacts graphistes, faites ! Transmettez. Toute aide est
> bonne a prendre. La seule condition que j'imposerai c'est la licence :
> faut
> pas qu'on soit emmerdé a terme, ni nos membres qui feraient des
> détournement. Donc une cc-by serait cool

**Comment by cgabard** [comment]
Si il est motivé, oui !

Christophe.

2014-05-14 18:05 GMT+02:00 geoffreyc notifications@github.com:

> Jiyong (qui a quand meme fait tout les zorors! :
> http://www.jiyong.eu/folio/zozor/) serait peut etre assez gentil pour
> nous
> faire ca? Il est tres fort a dessiner les fruits et legumes !
> http://www.jiyong.eu/folio/images/fel/002.png
> 
> 2014-05-14 17:02 GMT+01:00 Christophe Gabard notifications@github.com:
> 
> > Si vous avez des contacts graphistes, faites ! Transmettez. Toute aide
> > est
> > bonne a prendre. La seule condition que j'imposerai c'est la licence :
> > faut
> > pas qu'on soit emmerdé a terme, ni nos membres qui feraient des
> > détournement. Donc une cc-by serait cool

**Comment by SpaceFox** [comment]
Ce serait génial, d'autant plus que j'aime beaucoup son boulot
d'illustration et de déclinaisons !

Et je serais curieux de voir les réactions des patrons d'OCR s'il faisait
nos mascottes :D

**Comment by geoffreyc** [comment]
Je l'ai contacté, en espérant qu'il ai un peut de temps !

2014-05-14 17:07 GMT+01:00 SpaceFox notifications@github.com:

> Ce serait génial, d'autant plus que j'aime beaucoup son boulot
> d'illustration et de déclinaisons !
> 
> Et je serais curieux de voir les réactions des patrons d'OCR s'il faisait
> nos mascottes :D
>

**Comment by ShigeruM** [comment]
Ah putain Jiyong ce serait excellent !

**Comment by Alex-D** [comment]
Juste comme ça pour info, je lui ai demandé quelques conseils pour le design par courriel.

Donc je plussoie la possibilité Jiyong :D

**Comment by cgabard** [comment]
Pour référence : en cours par Jiyong

**Comment by Alex-D** [comment]
Ca a été fait, je ferme donc cette issue.

**Comment by Eskimon** [comment]
Il y aura moyen de voir l'ensemble des artworks quelques part ? (oui je suis curieux :D )

**Comment by ChantyTaguan** [comment]
T'as un bon aperçu là : https://www.facebook.com/profile.php?id=100005698441732

**Comment by Eskimon** [comment]
Alex-D

> Ca a été fait, je ferme donc cette issue.

Je ferme pour de vrai :D
