### ISSUE TITLE
Ajouter/supprimer un groupe devrait ajouter/supprimer la casquette correspondante

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#4780]
Aujourd'hui, les deux sont décorellés, ce qui rends la gestion des droits un peu pénible.

À moins que quelqu'un n'ait une bonne raison ou que ça prenne un temps déraisonnable à faire, je propose qu'ajouter un membre dans un groupe lui donne une casquette de même nom, et pareil dans l'autre sens.

**Comment by gllmc** [comment]
Ça arrive en v26 : #4624. :)

**Comment by SpaceFox** [comment]
Vous êtes géniaux :)
