### ISSUE TITLE
Erreur de balisage dans tutorialv2/view/content.html

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4783]
Je ne vois pas où ce `<li>` est fermé : 

https://github.com/zestedesavoir/zds-site/blob/afcc37add9df549fc5b4ec4fb64fc92ca5298944/templates/tutorialv2/view/content.html#L267

Ça serait top de découper ce template dans plusieurs fichiers.

(Problème trouvé avec [jinjalint](https://github.com/motet-a/jinjalint))

**Comment by nils-van-zuijlen** [comment]
Je prends la fermeture du `<li>`
Pour le découpage, il faudra quelqu'un de plus compétent.
