### ISSUE TITLE
Classification des tutos et articles par tags

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#480]
Comme on a des tutos et articles qui parlent de plusieurs sujet, l'idée est de ranger ces tutos et articles non pas dans des catégories mais avec des tags.

Idéalement la navigation dans ces tutos et articles se fait via des facettes. On aurait les facettes suivantes :
- Tags (multi-sélection possible)
- Type (Tuto court, tuto long, article)
- Auteur
- Difficulté
- Date

Idéalement ces facettes sont gérées avec Solr, qui est déjà notre moteur de recherche. Il est conçu pour ce genre de navigation.

La navigation est une navigation à facettes standard : affichage du nombre d'éléments dans chaque facettes, pas de facettes qui ne renvoient aucun élément.

D'un point de vue validation, l'auteur renseigne lui-même les tags qui l'intéressent.
Le validateur voir la liste _complète_ des tags : ceux qui existent déjà, et ceux que l'auteur créerait.
Le validateur peut donc compléter / modifier / supprimer les tags proposés par l'auteur pour qu'ils correspondent à la réalité du tuto et à l'orthographe des tags existants.

**Comment by firm1** [comment]
Hm, je n'ai pas forcément participé à la discussion sur le forum, mais je crois que je repasserai là bas pour donner un avis plus détaillé.
Mais je pense que l'option tags n'est pas envisageable pour la v1.

**Comment by Alex-D** [comment]
@GerardPaligot avait déjà codé un système de tags si je me souviens bien...

**Comment by GerardPaligot** [comment]
> @GerardPaligot https://github.com/GerardPaligot avait déjà codé un
> système de tags si je me souviens bien...

Euh ... non.

2014-05-12 1:53 GMT+02:00 DEMODE Alexandre notifications@github.com:

**Comment by Eskimon** [comment]
Ce ticket sera supporté par la [ZEP-15](https://zestedesavoir.com/forums/sujet/1082/zep-15-navigation-a-facettes-a-travers-le-site/)

**Comment by SpaceFox** [comment]
ZEP-15 et plein d'autres discussions… du coup je ferme le ticket qui ne sert plus à grand-chose.
