### ISSUE TITLE
Passez aux f-string, (après python 3.6)

### ISSUE THREAD

**Issue by AmarOk1412** [zestedesavoir/zds-site#4801]
See https://www.python.org/dev/peps/pep-0498/

**Comment by artragis** [comment]
Je pense que faire ça ne sert à rien sinon à générer encore une fois une nouvelle PR hyper grosse et de la magie dans notre code.
Nous utilisons un grand nombre de variables locales dans notre code, cela peut générer des bugs de type copier/foirer. En fait vue l'historique de zds, je dirais que ça va générer des bugs de ce type. (on copie un fstring d'une vue à l'autre sans se rendre compte que le type de la variable n'est pas le même entre les deux vues et à la fin on a un bug complexe à comprendre).

Sincèrement ce sucre syntaxique n'apporte rien.
