### ISSUE TITLE
Conflit entre plusieurs notes de "pied de page"

### ISSUE THREAD

**Issue by rezemika** [zestedesavoir/zds-site#4804]
Quand il y a plusieurs notes de "pied de page" (*footnote*, pas super adapté ici vu que les-dites notes sont en fait en pieds de sections) qui portent le même nom, seule la première est utilisable.

Ironiquement, c'est le billet ["Mais pourquoi ça bug?"](https://zestedesavoir.com/articles/2263/mais-pourquoi-ca-bug/#fn-source) qui m'a fait trouver ce comportement. Les deux premières sections possèdent toutes deux une note `source` (`#fn-source` une fois rendu en HTML). Or, vu qu'elles ont le même nom, si on clique sur la seconde, on arrive sur la note de la première section.

Ça risque de ne pas être évident à corriger. La meilleure approche que je vois consisterait à parser toutes les sections de chaque partie (vu qu'il ne peut y avoir plus d'une partie par page) pour trouver les doublons, et rajouter des suffixes au besoin (`source1` par exemple). Ou alors on met ça en wontfix, vu que ça n'arrive pas très souvent...

**Comment by motet-a** [comment]
Probablement lié à https://github.com/zestedesavoir/zmarkdown/issues/168 et https://zestedesavoir.com/forums/sujet/9280/references-non-uniques-dans-un-sujet/.

**Comment by Situphen** [comment]
Est-ce qu'il faut laisser le ticket ouvert ici étant donné que ça concerne le Markdown ?

**Comment by motet-a** [comment]
Je viens de relire ces choses et oui, ça concerne vraiment le Markdown. D’ailleurs, dans https://github.com/zestedesavoir/zmarkdown/issues/168 il y a une solution vraiment simple à ce problème.
