### ISSUE TITLE
Tutos : Le menu déroulant "déplacer" ne fait rien

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#481]
Le petit menu déroulant permettant de monter/descendre un "extrait" ne semble rien faire (ou alors je sais pas m'en servir...). J'ai uniquement l'option "monter" même si je suis sur une partie "du milieu" de selectionnable et il ne se passe rien. J'ai aussi en gris les options "déplacer avant" "déplacer après" mais elles ne sont pas sélectionnables...

**Comment by GerardPaligot** [comment]
Le menu déroulant se trouve dans le template `tutorial/view_chapter_common.part.html`. Le bouton de confirmation se trouve dans une balise `noscript`, il n'apparait donc pas aux utilisateurs avec le JS activé. Après demande auprès de notre lead front, il faut rajouter le JS manquant pour devoir simplement sélectionner un élément du menu déroulant en guise de confirmation.

Sinon, je m'interroge de l'utilité des options "Déplacer avant" et "Déplacer après", quelqu'un à une idée ?

**Comment by Eskimon** [comment]
> Sinon, je m'interroge de l'utilité des options "Déplacer avant" et "Déplacer après", quelqu'un à une idée ?

Je pense que c'est assez anecdotique... Dans un monde ideal, tu fais d'abord un plan qui tiens la route puis ensuite tu rediges le court... Donc en theorie ca devrait pas etre utilise trop souvent...

**Comment by GerardPaligot** [comment]
En fait, ma question portait sur l'action derrière ces deux possibilités du menu déroulant. :)

**Comment by Eskimon** [comment]
Si je dis pas de connerie c'est cense pouvoir deplacer les parties entre elles... genre :
- Partie 1
- Partie 2
- Partie 3

Si tu decides de faire "monter" partie 2 ca fait
- Partie 2
- Partie 1
- Partie 3

**Comment by GerardPaligot** [comment]
Je suis un peu rouillé en Django alors j'ai commencé à voir comment corriger ce bug et je tombe sur un problème. Après un peu de recherche, je viens solliciter de l'aide. Voici ce que je tente de faire :

```
    elif 'move' in data:
        try:
            new_pos = int(request.POST['move_target'])
        # Error, the user misplayed with the move button
        except ValueError:
            return redirect(extract.get_absolute_url())

        pos_extract_old = extract.position_in_chapter
        extract.position_in_chapter = new_pos
        other = extract.chapter.extracts()[new_pos]
        other.position_in_chapter = pos_extract_old

        other.save()
        extract.save()

        return redirect(extract.get_absolute_url())
```

Très simplement, je récupère la nouvelle position de l'extrait, sa positon actuelle et je fais un swap avec l'extrait concerné (`other`). Tout se passe bien, les valeurs `position_in_chapter` sont bonnes après le traitement mais `other.save()` ne semble pas sauvegarder mon extrait.

Quelqu'un aurait une idée ?

**Comment by firm1** [comment]
A vu de nez, ça me parait bon, sauf cette ligne `other = extract.chapter.extracts()[new_pos]` qui ne devrait pas être le cas. Vaut mieux faire le filtre tout simplement.

**Comment by GerardPaligot** [comment]
Effectivement, avec les filtres ça fonctionne bien. Je suppose que c'est parce que je suis lié à la base de données.

Par contre, j'étais étonné. Les modifications ont bien été faites en base de données mais elles ne se répercutent pas à l'affichage. Il semblerait qu'on se base sur l'ordre des extraits dans le manifest du tuto concerné.

Est-ce voulu ? Si oui, à quoi sert l'attribut `position_in_chapter` ?

**Comment by firm1** [comment]
> Il semblerait qu'on se base sur l'ordre des extraits dans le manifest du tuto concerné.

Biensur et c'est normal, donc voulu.

> Si oui, à quoi sert l'attribut position_in_chapter ?

Elle sert surtout de tampon d'une part et de référence du dernier état d'autre part

**Comment by GerardPaligot** [comment]
Très bien. Du coup, j'ai tenté de mettre à jour le repo comme on le ferait pour la suppression d'un extrait (par exemple) mais cette dernière fonctionnalité ne fonctionne pas non plus en fait. C'est-à-dire : Si on importe un tuto (testé avec un mini) et qu'on tente de supprimer un extrait, rien ne se passe.

**Comment by GerardPaligot** [comment]
En fait, la suppression se fait (et le déplacement aussi d'ailleurs) mais que lorsque je veux supprimer un autre extrait. Donc : Je supprime un extrait 1, rien ne se passe. Je supprime un extrait 3, l'extrait 1 se supprime. Je supprime un extrait 2, l'extrait 3 se supprime. Etc.

**Comment by cgabard** [comment]
Est ce que ce n'est pas un prob de cache du html qui serait évaluer avant la supression plutot qu'apres ?

**Comment by GerardPaligot** [comment]
Et le cache aurait un coup de retard ? Je ne sais pas, j'ai un doute. En tout cas, le bug est aussi présent sur la prod.

**Comment by cgabard** [comment]
Je ne sais pas, je propose. ça expliqerais pourquoi a chaque action tu vois l'action précédente mais c'est peut etre autre chose.

En fait il faudrait pouvoir désactiver le cache html en local (en meme temps je ne sais pas si il est activé)

**Comment by GerardPaligot** [comment]
Il y a un moyen de forcer un rafraichissement de la vue ?

**Comment by cgabard** [comment]
Aucune idée justement, @firm1 ?

**Comment by firm1** [comment]
Pour faire court l'actualisation a N+1 est un bug, n'hésite pas a le
corriger.
 Le 22 mai 2014 09:14, "Christophe Gabard" notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
Je passe pour dire que sur ma branche, le front fonctionne (via une modale) et que donc si ça bug, cela relève du back. Je laisse ouvert car je vois qu'il y a plusieurs choses liées à cette issues.

**Comment by Eskimon** [comment]
Ca fait partie des trucs corrigés dans la [PR #1001](https://github.com/zestedesavoir/zds-site/pull/1001)  non ?
