### ISSUE TITLE
Supprimer l'encouragement à contacter l'équipe pour ajouter une catégorie dans la page de création de contenu

### ISSUE THREAD

**Issue by EGabbro** [zestedesavoir/zds-site#4813]
Bonjour,

La page de création / édition de contenu (là il y a l'intro, conclusion, les tags, catégories, etc) contient la phrase 

« Sous catégories de votre contenu. Si aucune catégorie ne convient n'hésitez pas à en demander une nouvelle lors de la validation ! »

Version courte : je propose la suppression de la deuxième partie (ne laisser que 
« Sous catégories de votre contenu. »).

Version longue : Il s'agit de l'ancienne politique ; le menu étant devenu illisible, l'idée de la [ZEP 25](https://zestedesavoir.com/forums/sujet/2378/zep-25-categorisation-des-articles-et-tutoriels) (2015-2016) était de trouver des catégories assez généralistes et de gérer les rares restants avec les tags.

Aux dernières nouvelles, le principe actuel est « s'il y a de nombreux contenus, on crée une nouvelle catégorie ». Cette phrase [laisse à penser le contraire](https://zestedesavoir.com/forums/sujet/697/lopen-bar-a-smoothies/?page=153#p168577). Pour éviter tant la confusion des auteurs que de se retrouver à nouveau avec trop de catégories et donc un menu illisible, je propose la suppression de la deuxième phrase.

Si cela ne fait pas l'unanimité et qu'il est choisi de laisser la phrase, sachez qu'elle est présente dans l'interface des billets, qui ne sont pas soumis à validation.

**Comment by Anto59290** [comment]
Pas d'opposition franche et 6 personnes pour, ça semble bon pour tout le monde. D'un point de vue UX il semble  en effet logique de mettre le texte en accord avec l'usage.

Merci @EGabbro pour la création du ticket
