### ISSUE TITLE
Modifier la boite modale de publication d'un contenu

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#4817]
Quand on valide un contenu, il faut mettre un commentaire d'au moins 3 caractères d'en la boite modale de publication d'un contenu.

Actuellement, on a une erreur : 

> ['Votre commentaire doit faire au moins 3 caractères.']

Il faudrait que les crochets et les guillemets ne s'affichent pas.

Il serait bien de rajouter un `minlength=3` sur le `textarea` de la modale :)

**Comment by artragis** [comment]
je le tag en facile car : 

- ajouter le min-length sera assez facile, il suffit de toucher au template content.html
- pour retirer les crochets etc. il faudra soit modifier le moment où on affiche les erreurs dans le templates soit créer un templatetag qui fait globalement ça : 

```python
def display_error(errors):
    if isinstance(errors, (list, tuple)):
        return "\n".join(display_error(error) for error in errors)
    return errors
````

**Comment by nils-van-zuijlen** [comment]
Hum, pour avoir essayé, sans connaitre l'architecture des fichiers et leur contenu, **ce n'est pas facile**, enfin, du moins avec le peu d'informations que vous donnez.

De quel content.html s'agit-il ? De quel formulaire s'agit-il au sein de ce fichier ? Les formulaires ne seraient-ils pas générés automatiquement ?

**Comment by AmauryCarrade** [comment]
Je suppose que le `content.html` est [celui-là](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/view/content.html#L531) ; par contre en effet le formulaire est généré par django & crispy donc sauf erreur, il faudrait plutôt modifier l'attribut [par là](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/forms.py#L660-L669).

MàJ : et tant qu'à faire, il serait aussi logique d'ajouter la même chose à `AskValidationForm`, `CancelValidationForm`, `RejectValidationForm`, et `RevokeValidationForm`.
Et éventuellement un `max-length` à `NoteForm` (vaut `settings.ZDS_APP['forum']['max_post_length']`)

**Comment by nils-van-zuijlen** [comment]
Je prends, maintenant que la TODO list est claire

**Comment by nils-van-zuijlen** [comment]
Ouh là, plus je regarde le code, plus je trouve ça vieux.
Pourquoi est-ce qu'on fait les vérifications sur le texte "à la main" et qu'on n'utilise pas [les validateurs de Django](https://docs.djangoproject.com/fr/1.10/ref/forms/validation/#using-validators) ?

Certes, après tests manuels, ils donnent le même résultat visuel, mais ils devraient permettre une plus grande adaptabilité par rapport aux migrations.

**Comment by nils-van-zuijlen** [comment]
J'ai trouvé le pourquoi du comment de ce bug d'affichage.
Dans tous les autres formulaires standards, l'affichage des erreurs est géré automatiquement par le générateur de formulaires, puisque le formulaire est affiché lors des erreurs.
Cependant, ces formulaires étant dans des fenêtres modales, ils ne sont pas affichés en cas d'erreur et on affiche ces dernières à partir des messages dans [base.html](https://github.com/zestedesavoir/zds-site/blob/35c46e8efdf6e8ec653e8c33a8a8e6a3f3a58ac5/templates/base.html#L634). Elles s'affichent alors mal.
