### ISSUE TITLE
Notification vers sujet non accessible

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#482]
Lorsqu'on suit un sujet auquel on a plus accès (ex : déplacé dans la corbeille), on a voit toujours les notifications mais on ne peux plus y accéder.

Aujourd'hui on peut arrêter de suivre le sujet manuellement (cf une issue que je ne retrouve plus).
L'idée est de le faire automatiquement, mais ce n'est pas pressé, d'autant qu'en première approche c'est délicat à faire.

**Comment by firm1** [comment]
Dans le menu a gauche, normalement on un bouton (une croix) qui permet d'unfollow le sujet.

Il marche lui

**Comment by SpaceFox** [comment]
Yep, c'est ce que je dis ici :

> Aujourd'hui on peut arrêter de suivre le sujet manuellement (cf une issue que je ne retrouve plus).

Le message exprimé dans les forums était exactement celui-ci  : aujourd'hui on peut unfollow à la main, mais ce n'est pas super clair, et de toutes manières la perfection voudrait que ce soit fait automatiquement.

Mais encore une fois c'est une priorité basse.

**Comment by firm1** [comment]
Ce bug a été fixé complètement. L'unfollow est automatique désormais
