### ISSUE TITLE
L'historique des versions a des problèmes avec les accents

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#4824]
Depuis peu (c'était OK avant-hier), l'historique des versions a des problèmes d'affichage. Extrait :

> Le polonais Aleksander Wolszczan a bien d\xc3\xa9nich\xc3\xa 9 des exoplan\xc3\xa8tes en 1990, mais ce fut autour d'un pulsar (l'\xc3\xa9toile \xc3\xa0 neutrons [PSR B1257+12](https://fr.wikipedia.org/wiki/PSR_B1257%2B12)) et non d'une \xc3\xa9toile semblable au Soleil.

Les accents, et certains retours à la ligne, s'affichent à l'aide de `\`-machin-chouette. Cela le fait pour tous les contenus que j'ai testés, y compris d'autres auteurs. Cela a lieu dans les deux colonnes (avant-après).

Le texte du tuto, lui, s'affiche sans aucun problème.

Sujet : https://zestedesavoir.com/forums/sujet/9944/lhistorique-des-versions-a-des-problemes-avec-les-accents/
*Envoyé depuis Zeste de Savoir*

**Comment by rezemika** [comment]
Voici les fichiers concernés (pour vous économiser le temps de la recherche) :

- https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/view/diff.html
- https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/contents.py#L1271
- https://github.com/zestedesavoir/zds-site/blob/049390e2b6b3405dc6ac204d09dc4e105dd618e0/zds/utils/templatetags/htmldiff.py
