### ISSUE TITLE
Les sous-titres de sujets ne sont plus affichés correctement.

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#4828]
Problème rapporté sur [ce sujet](https://zestedesavoir.com/forums/sujet/10007/souci-daffichage-des-sous-titres/).

![Capture d'écran](https://zestedesavoir.com/media/galleries/321/cb3b1b60-9609-4635-9ea3-ce1b796d639d.png)

**Comment by Situphen** [comment]
C'est probablement lié à #4797 ... :-°

**Comment by Situphen** [comment]
Un autre problème avec les sous-titre a été signalé dans [ce sujet](https://zestedesavoir.com/forums/sujet/10041/probleme-daffichage-des-tags/) du forum mais la correction pour ce ticket corrige ça donc on n'a rien à faire (voir [mon message](https://zestedesavoir.com/forums/sujet/10041/probleme-daffichage-des-tags/#p170574) pour plus d'infos)
