### ISSUE TITLE
Visibilité de messages en zone Staff via recherche

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#483]
encore un problème de visibilité d’extraits de messages de la zone staff. Cette fois c’est par la fonctionnalité de recherche, [petite démo](http://zestedesavoir.com/rechercher/?q=supprimer+message&models=forum.post&models=forum.topic).

**Comment by firm1** [comment]
C'est fixé.

Merci pour le signalement

**Comment by Eskimon** [comment]
Je réouvre, apparemment l'issue est réapparu

http://zestedesavoir.com/forums/sujet/307/extrait-de-topic-des-staffs-visibles-depuis-la-recherche/

**Comment by Eskimon** [comment]
Si je ne m'abuse c'est juste la ligne
`{% load topbar %}`
qui manque dans
templates/search/search.html

Je ferais bien la PR, mais comme je peux pas tester en local je suis moyen chaud quand meme...

**Comment by Alex-D** [comment]
Rien à voir avec topbar :)

C'est le back qui ne filtre pas en fonction des rôles.

**Comment by Eskimon** [comment]
Ah ok... parce que justement j'ai cherché les différences via les commits, et seul l'include de topbar engrangeait quelque chose lié aux droits...

Ca entraine l'include de ca (qui vient du back) :

```
@register.filter('auth_forums')
def auth_forums(forums, user):
    auth = []
    for forum in forums:
        if forum.can_read(user):
            auth.append(forum)

    return auth
```

**Comment by Alex-D** [comment]
Sauf erreur de ma part : ça c'est pour la liste des forums dans le header (d'où "topbar").

**Comment by Eskimon** [comment]
Alors je donne ma langue au chat sur "où chercher" :D

**Comment by Alex-D** [comment]
La discussion continue là bas : #983 où la piste s'éclaire bien plus.

Le problème est strictement le même finalement : masquer les forums dont on a pas les droits.
