### ISSUE TITLE
Le bouton « Citer » n'insère plus la citation au bon endroit dans le message

### ISSUE THREAD

**Issue by entwanne** [zestedesavoir/zds-site#4832]
J'ai remarqué depuis quelques jours que le bouton « Citer » sur les messages du forum n'avait plus le même comportement qu'avant.

Quand le *textarea* est vide, il insère une ligne vide suivie de la citation, c'était l'inverse auparavant.
Et quand il n'est pas vide, la citation n'est pas insérée à la position du curseur (je crois que c'était le cas avant).

**Comment by Anto59290** [comment]
En relation avec #4711.

> Quand le textarea est vide, il insère une ligne vide suivie de la citation, c'était l'inverse auparavant.

En effet le comportement a changé, mais ça semble être voulu.

> Et quand il n'est pas vide, la citation n'est pas insérée à la position du curseur

Cf la PR #4711 . Chez moi ça insère bien la citation au niveau du curseur. Peux tu confirmer que chez toi ça ne fonctionne pas ? SI oui avec quel navigateur ?

**Comment by entwanne** [comment]
> En effet le comportement a changé, mais ça semble être voulu.

Hmm, soit, je trouve juste ça bizarre dans le cas d'un message vide, ayant l'habitude de placer la citation avant la réponse.

> Chez moi ça insère bien la citation au niveau du curseur. Peux tu confirmer que chez toi ça ne fonctionne pas ? SI oui avec quel navigateur ?

Ça fonctionne bien si le curseur est placé sur une ligne vide, pas si le le curseur est placé en fin de ligne (ni s'il est placé en milieu de ligne, mais là ce n'est pas censé fonctionner comme ça si j'en crois la PR citée).

Je tourne actuellement sur Chromium 57, mais lorsque j'ai rédigé le ticket hier soir j'avais sous la main une version plus récente.

**Comment by rezemika** [comment]
Je plussoie, il me semblait que ça insérait la citation au début avec deux sauts de lignes après quand le post était vide, mais ça le fait aussi de mon côté avec Firefox 58.0b14. Je regarderai demain pour trouver la cause de ce problème.

**Comment by rezemika** [comment]
Et voilà. Désolé pour le retard.
