### ISSUE TITLE
Markdown, espace insécable en code HTML au lieu de l'Unicode

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#4833]
[Reporté par Xalty](https://zestedesavoir.com/forums/sujet/10034/affichage-des-et-des-deux-points/)

Après une petite examination du code HTML généré :

> D'après le code-source, les espaces simples avant les deux-points et points d'interrogation/exclamation sont transformés en `&#x202F;` qui est une instruction HTML pour l'espace insécable. Alors que quand Xalty parle d'espace insécable, il s'agit de l'espace insécable en Unicode.

**Comment by Situphen** [comment]
> En fait, ce n'est pas un bug : c'est parfaitement volontaire.
> 
> En cas d'absence d'espace insécable avant `?!:`, le système ajoute une espace insécable **fine** (`NARROW NO-BREAK SPACE (U+202F)`)avant le caractère. Selon la police et le rendu exact de l'écran, elle peut être difficilement visible, d'ailleurs ce n'est pas la première fois que ceci est signalé.
> 
> Ici, deux possibilités :
> 
> 1. On garde la typographie « classique » et cette espace insécable fine ;
> 2. On la transforme en espace insécable normale.
> 
> À noter que de plus en plus d'éditeurs (de littérature, dans des livres papier) choisissent la solution 2. 

[Commentaire de SpaceFox](https://zestedesavoir.com/forums/sujet/10034/affichage-des-et-des-deux-points/?page=1#p170457)

**Comment by artragis** [comment]
si le comportement est attendu alors c'esdt impec.
