### ISSUE TITLE
Utiliser des ^ pour les dépendances dans le package.json

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4836]
`^1.2.3` veut dire “compatible avec 1.2.3”, alors que `1.2.3` veut dire “exactement la version 1.2.3”. Quand il y a des `^`, c’est un peu plus pratique pour les mises-à-jour avec Yarn. Et on n’a plus besoin de spécifier les versions exactes dans le package.json parce qu’il y a un `yarn.lock` maintenant.

Notez que par défaut, `yarn` tout comme `npm` mettent des `^`.

À faire une fois que #4835 est mergée.

**Comment by A-312** [comment]
Il me semblait (avoir lu et par expérience) qu'il fallait mieux mettre à jour manuellement que automatiquement.

**Comment by motet-a** [comment]
En fait le `yarn.lock` dans le dépot fixe les versions exactes. Si il y a `"foo": "^1.2.3"` dans le `package.json` et que la version fixée dans le `yarn.lock` pour `foo` est `1.3.5`, alors la `1.3.5` sera toujours installée, même si la `1.3.6` est sortie. Pour mettre à jour une dépendance, il faut forcément modifier le `yarn.lock`.

Quoi qu’il en soit, le problème est résolu puisqu’il y a maintenant des `^` partout dans le `package.json`. Je ferme le ticket.
