### ISSUE TITLE
[v26] les nouveaux contenus ne sont pas indexés

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4838]
[Ce lien](https://zestedesavoir.com/rechercher/?q=exoplan%C3%A8tes&category=&subcategory=&from_library=) ou encore [celui-ci](https://zestedesavoir.com/rechercher/?q=pedro+robot&category=&subcategory=&from_library=) devraient renvoyer respectivement un article et un billet dans la recherche.

Donc je soupçonne que le service d'indexation ne tourne pas sur le serveur.

**Comment by gllmc** [comment]
C'est probablement lié au changement du serveur de prod. @sandhose pourra vérifier ça.

**Comment by sandhose** [comment]
My bad effectivement. Fixé.

Je documenterais ce que j'ai fait sur la prod récemment à l'occas.
