### ISSUE TITLE
Messages (optionnels) de validation pour les articles et tutos

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#484]
nohar pense qu'il manque une feature importante à ce niveau : l'auteur d'un tuto/article doit être notifié lorsque son tuto/article est accepté ou refusé, avec le commentaire de la personne ayant validé l'ouvrage.

---

Mascotte : 
Pour faire une première liste j'ai besoin de textes a trou pour : 
- Prévenir le staff qu'un nouveau tuto est arrivé en validation
- Prévenir un membre que son tuto a été réservé par un valido, et que c'est donc celui-ci qu'il devra contacter si besoin
- Prévénir un membre que son tuto a été publié
- Prévénir un membre que son tuto a été rejeté (avec les raisons)
- Souhaiter la bienvenue aux nouveaux arrivants (j'ai poussé un truc hier s'y rapportant, mais je ne suis absolument pas convaincu du texte)
- ~~Souhaiter joyeux anniversaire a un membre~~ mais vu qu'on a pas les dates de naissances ...  :-°

---

Premiers jets de messages ici : http://zestedesavoir.com/forums/sujet/128/suggestion-messages-optionnels-de-validation-pour-les-articles-et-tutos#p770

**Comment by Coy0te** [comment]
Pas reçu de MP en refusant un tuto que j'avais proposé (moi-même) à la validation. Normal ou pas ?

**Comment by firm1** [comment]
Pas normal.

**Comment by firm1** [comment]
C'est bon cette fois, c'est sur le serveur
