### ISSUE TITLE
Nombreuses pages 404 indexées par Google

### ISSUE THREAD

**Issue by entwanne** [zestedesavoir/zds-site#4847]
Bonjour,

Depuis quelques temps je remarque en faisant des recherches sur Zeste de Savoir depuis Google que de nombreux résultats du domaine `docs.zestedesavoir.com` remontent, qui sont tous en 404, mais qui correspondent à des chemins valides sur `zestedesavoir.com` : [requête d'exemple](https://www.google.fr/search?q=toto+site%3Azestedesavoir.com).

Je ne sais pas à quoi est due cette erreur, s'il y a eu un jour un *canonical* mal placé, mais en l'état ça paraît pas mal contraignant pour le référencement du site et de ses contenus.

**Comment by gllmc** [comment]
Il me semble qu'il y avait eu un problème de configuration du proxy de la doc lors de la mise en place du nouveau serveur, donc ça vient sûrement de là et les liens devraient rapidement disparaître (par contre, ça a quand même été résolu il y a un certain temps maintenant et je trouve étrange qu'on retrouve toujours de tels liens).

**Comment by motet-a** [comment]
Il n’y a pas des infos là-dessus sur la Google Search Console ? (@sandhose ?)

**Comment by Situphen** [comment]
C'est a priori résolu donc je ferme.
