### ISSUE TITLE
Les tags dans les résultats de recherche ne pointent pas sur les bonnes pages

### ISSUE THREAD

**Issue by entwanne** [zestedesavoir/zds-site#4848]
Bonjour,

En me baladant dans [les résultats de recherche](https://zestedesavoir.com/rechercher/?q=python) depuis le moteur du site, j'ai remarqué que les liens des tags n'étaient plus corrects (probablement depuis la refonte « Bibliothèque »).
Ils pointent en effet vers des pages du type `/contenus/?tag=` (<https://zestedesavoir.com/contenus/?tag=python>), qui redirigent vers `/bibliotheque/`, perdant au passage le paramètre *GET*.

**Comment by entwanne** [comment]
Je me dis qu'il faudrait peut-être simplement remplacer `content:list` par `publication:list` dans [le *template* `publishedcontent.part.html`](https://github.com/zestedesavoir/zds-site/blob/dev/templates/searchv2/includes/publishedcontent.part.html#L59).
Je n'ai pas vraiment d'environnement sous la main pour tester si c'est bien ça.
En tout cas c'est la seule occurrence de `content:list` qui existe, et je ne trouve aucune url qui corresponde dans [urls_contents](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/urls/urls_contents.py), donc je pense que ça fallback sur [`publications:list`](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/urls/urls_contents.py#L152).

**Comment by rezemika** [comment]
J'ai testé en local : tu as raison, ça vient de bien de là. Je fais une PR. :)
