### ISSUE TITLE
Ajouter un champ facultatif "Raison de l'edit"

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#485]
Un champ "Raison de l'edit" sur un message de forum serait pas déconnant. Dans certains cas ça peut etre utile je pense... (j'ai pu découvrir çà récemment sur les forums d'OVH, j'ai trouve ça pas con...). Le "message d'edit" serait alors affiche discretement en pied/entete du post.

**Comment by Alex-D** [comment]
Moi j'aime bien l'idée, mais du coup on matérialisé ça par un simple texte ?
Et si on édite plusieurs fois ça se passe comment ?

**Comment by Eskimon** [comment]
> Moi j'aime bien l'idée, mais du coup on matérialisé ça par un simple texte ?

Ouai, a coté du champ "Edite par {pseudo}" qui deviendrait "Editer par {pseudo} : {raison}"

> Et si on édite plusieurs fois ça se passe comment ?

Je dirais que le dernier message écrase le précédent (ça sers à rien de garder un historique non ?)

**Comment by Coy0te** [comment]
Ça me semble sympa aussi, mais uniquement si seuls les auteurs des posts s'en servent.

Il ne faudrait pas que le Staff se serve de ça pour donner les raisons d'un éventuel edit, pour moi ça devra se faire via un message posté manuellement dans le sujet en question.

[Edit] Pourquoi je ne suis pas étonné de voir notre renard préféré proposer un truc concernant les éditions de post ? :D

**Comment by Eskimon** [comment]
En fait l’idée de base c'est justement que l'auteur du post puisse donner une raison de son edit du genre "faute d'ortographe" "Ajout d'infos" etc... et non pas juste que ca serve a l'admin :D

Et l’idée est de moi le caribou !!! (pompée sur une pratique des fofos d'OVH)

**Comment by firm1** [comment]
Pour moi c'est un champ en plus qui pourrait encore alourdir le formulaire.

Du coup je suis moins chaud.

**Comment by ShigeruM** [comment]
Et ça alourdit la présentation du post aussi. Je ne suis pas sûr que
l'utilité en vaille la peine.

**Comment by SpaceFox** [comment]
J'ai envie de dire KISS : quand on doit éditer le post d'un tiers, on
s'oblige à rajouter la raison de l'édit en bas. Pas besoin de champ
supplémentaire, c'est juste une bonne pratique.

**Comment by firm1** [comment]
Et du coup, quelqu'un voit encore un intérêt a cette feature ?

**Comment by SpaceFox** [comment]
Pas moi.

2014-05-20 17:14 GMT+02:00 firm1 notifications@github.com:

**Comment by Alex-D** [comment]
Autant côté formulaire ça alourdi, autant côté affichage/rendu j'avais la place pour l'afficher.
Peu m'importe techniquement parlant.

Perso j'ai tendance à écrire la raison de l'édit en dur si nécessaire.

**Comment by Coy0te** [comment]
Pareil, je suis pour expliciter les raisons d'un edit à la main.

**Comment by Eskimon** [comment]
Bon du coup on reste KISS et on clos ? Zou ! Une issue / débat en moins :)
