### ISSUE TITLE
Message pour prévenir le staff qu'un nouveau tuto vient d'arriver en validation

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#486]
Il manque un message pour prévénir le staff qu'un nouveau tuto vient d'arriver en validation (avec le texte qu'a écrit l'auteur à destination des validos)

**Comment by Alex-D** [comment]
Dans l'absolu, il faudrait utiliser le système de notifications.

**Comment by firm1** [comment]
Fixé (cf. PR  #504 )

**Comment by Eskimon** [comment]
Dans la version actuelle, je n'ai jamais vu de notifs lors d'une demande de valdiation (en local ou en prod). C'est normal ?
