### ISSUE TITLE
« Les identifiants fournis ne sont pas valides » si le compte n'est pas encore activé

### ISSUE THREAD

**Issue by ludovicm67** [zestedesavoir/zds-site#4861]
Bonjour,

Je viens de m'inscrire sur ZdS, et après avoir validé mon inscription, j'ai souhaité m'y connecter directement.
Je suis tombé sur une erreur _« Les identifiants fournis ne sont pas valides »_, comme on peut le constater sur la capture d'écran suivante :
![zds1](https://user-images.githubusercontent.com/9420561/35529272-d6265688-0530-11e8-9093-be773ab84e1a.png)

Cela peut porter confusion à l'utilisateur, l'idéal serait d'afficher dans ce cas précis un message lui précisant de bien vouloir activer son compte en cliquant sur le lien envoyé par mail.

**Comment by rezemika** [comment]
+1

C'est peut-être corrigé par la #4822, je regarde ça tout à l'heure.

Edit : J'ai pas pu trouver avec certitude l'origine de ce problème, mais il semble être toujours présent dans la branche de dev (j'avais le message "Mot de passe incorrect."). Apparemment, la fonction `authenticate()` retournerait `None` avec un utilisateur inactif (à confirmer).

**Comment by Migwel** [comment]
J'ai testé ceci localement et la PR #6273 fixe ceci
