### ISSUE TITLE
Ajouter les commentaires sur les billets/articles/tutos à l'activité d'un membre

### ISSUE THREAD

**Issue by entwanne** [zestedesavoir/zds-site#4865]
Bonsoir,

Dans la page de profil d'un membre, on peut accéder à un lien qui liste tous ses messages postés sur le forum.
Je trouve que, de la même manière, il serait intéressant de pouvoir lister les interventions des membres dans les commentaires de tutoriels/articles/billets.

Avec l'arrivée des tribunes, et les billets qui prêtent au débat, certains fils de commentaires pourraient s'apparenter à des sujets de forum. Et je pense que le même traitement devrait leur être accordé.

Merci.

**Comment by Arnaud-D** [comment]
Résolu par #5974.
