### ISSUE TITLE
Spawn de nouveau sujets à partir d’un autre

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#487]
(Simbilou)
L’idée est de pouvoir séléctionner des messages hors-sujets qui commence à former une discution cohérente dans un topic pour les déplacer dans un topic à part crée pour l’occasion. Ça à été discuté sur [progdupeupl](http://progdupeu.pl/forums/sujet/40/deplacement-de-hors-sujets) il y a un moment et bien que ne soit pas implémenté à ma connaissance, je trouve l’idée super. Ce serait évidement un outil reservé au staff.

---

Fonctionnement proposé :
- Les posts en HS sont simplement déplacés (attribués au nouveau topic)
- Un message est posté dans le nouveau topic pour prévenir du split

Comment sélectionner les messages à splitter ?

**Comment by Coy0te** [comment]
> Comment sélectionner les messages à splitter ?

Un clic sur un lien d'action staff (du genre "spawner") pourrait provoquer l'affichage : 
- d'une modale, demandant de choisir un sujet de destination existant ou bien d'écrire un titre de nouveau sujet ;
- puis de checkboxes sur chaque post du sujet, et l'apparition d'un bouton "Spawner" en bas de page. Au clic sur le bouton, les posts dont les checkboxes sont sélectionnées partent dans le sujet défini.

**Comment by Alex-D** [comment]
J'aime la solution proposée par Coyote, à ceci prêt que j'ajusterais ainsi : 
- Clic sur un bouton dans la sidebar "Diviser le sujet" ;
- On a une checkbox sur chaque message (décochée par défaut) et un bouton "Valider" qui apparaît ;
- Au clic sur le bouton "Valider" on a la fameuse modale avec :
  - un champ pour le titre du nouveau sujet ;
  - une boite de sélection pour choisir le forum de destination.

Ca change un poil, mais ça fait la différence je trouve :)

D'un point de vue back-end ça consiste du coup à récupérer des IDs de message, un titre et un ID de forum pour finalement créer un sujet et migrer les fameux messages. C'est pas si complexe que ça à mes yeux à ce niveau là. Le truc chiant ça va être les notifications et ce genre de choses.

**Comment by SpaceFox** [comment]
Le PB ici n'est pas le back-end mais le front-end. Avec des problématiques
bordéliques, du style :
- Que faire si les messages que je veux splitter sont à cheval sur
  plusieurs pages ?
- Que faire si le sujet fait déjà plusieurs dizaines de pages quand je veux
  le splitter ?

**Comment by Coy0te** [comment]
@Alex-D : effectivement l'ordre est plus naturel ainsi.

Pour répondre aux situations que @SpaceFox évoque, il suffirait probablement dans la modale d'afficher un radio pour choisir "nouveau sujet" ou "sujet existant" : 
- si nouveau sujet est choisi, alors un champ libre apparaît et le staffeux doit y entrer le titre du nouveau sujet qu'il veut créer ;
- si sujet existant est choisi, alors un champ libre apparaît et le staffeux doit y entrer l'id du sujet vers lequel merger les posts sélectionnés.

Pour le coup de l'id à saisir, ok ça fait un peu brut de décoffrage, mais ça évite d'avoir à taper dans le backend pour afficher des multiples selectboxes de forums/sujets existants. Et comme c'est uniquement le staff qui le fait, et qui plus est pas tous les 4 matins, d'après moi ça peut suffire.

Ça voudrait donc dire que si une discussion est sur plusieurs pages, il suffira au staffeux de cliquer sur le bouton "diviser" sur chaque page présentant un ou plusieurs posts à récupérer. Ça me paraît largement suffisant comme niveau d'intégration, pour un truc qu'on ne va utiliser que toutes les X semaines.

**Comment by Alex-D** [comment]
@Coy0te je pense que tu n'as pas saisi la problématique énoncée par @SpaceFox 

Si c'est ça qui vous chagrine : les IDs sont en auto-index je suppose, du coup sont croissants. Donc on peut donner l'id du premier message, l'id du dernier et récupérer l'ensemble pour les rebalancer sur un nouveau sujet.

Aussi, on pourra créer une vue dédié avec une vue "tassée" de tous les messages du topic ou un truc du genre...

On peut aussi imaginer un formulaire persistant de page en page jusqu'au clic sur "Valider" (y a ce qu'il faut côté front maintenant...)

Des solutions il y en a, il faudra juste trouver celle qui convient le mieux à tout le monde.

**Comment by SpaceFox** [comment]
> Si c'est ça qui vous chagrine : les IDs sont en auto-index je suppose, du
> coup sont croissants. Donc on peut donner l'id du premier message, l'id du
> dernier et récupérer l'ensemble pour les rebalancer sur un nouveau sujet.

Ça ne fonctionne pas : les IDs des messages sont partagés entre tous les
messages du forum, il faut une contrainte sur l'appartenance au sujet.
Au-delà de ça, il n'est pas toujours pertinent de switcher TOUS les
messages entre le message A et le message B.

**Comment by Coy0te** [comment]
@Alex-D : je pense que si, j'ai bien compris. 

Je proposais justement d'opérer le split manuellement (page par page, avec donc la possibilité d'envoyer des posts vers un sujet déjà existant), afin d'éviter la situation remontée par @SpaceFox dans son dernier message, c-a-d le cas où tous les posts de X à Y ne sont pas bons à prendre, mais seulement quelques uns dans le tas.

A partir du moment où c'est possible sur une page donnée d'une sujet de faire apparaître les checkboxes et la modale, je ne vois pas bien où est le problème. Je trouve ça moins chiant à faire que de devoir générer une vue "tassée" d'un topic ou un formulaire persistant, par exemple.

**Comment by Alex-D** [comment]
Heu... les IDs des messages, et forcément c'est couplé à l'ID du topic... ça me semblait implicite en fait.

Sinon, j'ai proposé d'autres solutions, notamment le formulaire persistant qui me semblent mieux. Du coup une réponse qu'à la première énoncée ça m'embête un peu ^^"

Je viens de piger la réponse de @Coy0te qui en gros consiste à migrer le topic en plusieurs fois, du coup pourquoi pas en effet.

**Comment by cgabard** [comment]
Pour moi ça devrait mériter une Zep donc ticket a fermer tant que pas fait. Peut être faire un sujet sur le forum "idée de zep" pour lister ces idées qui mériteraient à être détaillés ?

**Comment by gustavi** [comment]
Je ferme. https://zestedesavoir.com/forums/sujet/1876/idees-a-zep/ pour la suite des discussions.
