### ISSUE TITLE
Le compte du bot est-il essentiel au fonctionnement du site ?

### ISSUE THREAD

**Issue by rezemika** [zestedesavoir/zds-site#4872]
Je poste ce ticket suite à une remarque de @vhf sur la PR #4870.

Dans le projet, on trouve 7 fois la ligne suivante : 

```python
bot = get_object_or_404(User, username=settings.ZDS_APP['member']['bot_account'])
```

Cela pose la question : est-il souhaitable de lever une erreur 404 quand l'instance n'a pas de compte de bot ? Si ce compte est considéré comme essentiel, il faudrait vérifier sa présence au démarrage de l'instance, et non lever une 404. S'il ne l'est pas, il faudrait simplement réaliser les actions à réaliser et sauter les étapes qui nécessitent ce compte (l'envoi des MP).

En bref : compte du bot obligatoire ou pas ? Dans les deux cas, je veux bien faire une PR. :)

**Comment by gllmc** [comment]
Oui, le compte bot est essentiel au fonctionnement de l'instance, de mêmes que les comptes anonyme et auteur externe d'ailleurs.

On a déjà eu [des problèmes](https://zestedesavoir.com/forums/sujet/10038/impossible-de-se-desinscrire/) à cause de paramètres mal définis, donc une erreur au démarrage de l'instance serait très pertinent. ;)
