### ISSUE TITLE
Mauvais affichage des caractères de contrôle dans le diff entre deux versions d'un contenu

### ISSUE THREAD

**Issue by entwanne** [zestedesavoir/zds-site#4876]
Bonsoir,

Je viens de voir en travaillant sur un billet que la différence entre deux versions d'un contenu n'avait plus la même forme qu'avant.
Jusqu'alors, la vue présentait deux cadres côte à côte reprenant les différences ligne par ligne.

Il y a maintenant un problème d'affichage des caractères de contrôle qui fait que les retours à la ligne n'apparaissent plus tels quels, mais sous la forme de `\r\n` littéraux.
De la même manière, les accents disparaissent du diff, au profit de séquences telles que `\xc3\xa9`.

Ça n'est pas critique, mais ça complique beaucoup la lecture du diff.

**Comment by AmauryCarrade** [comment]
Déjà signalé par #4824 et corrigé par #4826 :) Il faut juste attendre la prochaine version. (Moi aussi j'attends, c'est vrai que c'est peu pratique.)

**Comment by entwanne** [comment]
Ok, merci, désolé pour le doublon.
