### ISSUE TITLE
Message de fin de sanction dédié

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#488]
Aujourd'hui, quand on se fait dé-sanctionner, on a un message du genre :

> Tu as été santionné par mascotte.
> 
> La sanction est de type Authorisation d'écrire, ce qui signifie que vous pouvez désormais poster sur les forums, dans les commentaires d'articles et tutoriels.

Ce qui est quand même particulièrement pas clair ("ta sanction est de ne plus avoir de sanction", heu...)

Je propose de faire donc des MP/mails dédiés pour les annulations de sanctions.

---

(nohar)

Au passage, il faudrait se mettre d'accord sur tutoiement vs. vouvoiement.

Je pense que pour les messages de sanction, il serait préférable de vouvoyer le membre histoire de mettre une distance neutre entre le site et le mec qui vient de mériter une sanction, d'autant que c'est un cas où le tutoiement peut être pris pour une familiarité agressive et/ou insultante, contrairement aux messages de validation. 

Dans tous les cas, il faut éviter de tutoyer ET vouvoyer le membre dans le même message.

**Comment by firm1** [comment]
Ce problème a été résolu, je vais de ce pas te sanctionner pour que tu vérifie le message.

**Comment by SpaceFox** [comment]
Je confirme, c'est corrigé, et le message est OK.
Je ne sais pas si c'était le fait d'une issue que j'ai pas retrouvée (possible) ou si c'était un effet de bord d'autre chose.

**Comment by firm1** [comment]
> Je ne sais pas si c'était le fait d'une issue que j'ai pas retrouvée (possible) ou si c'était un effet de bord d'autre chose.

Non je l'ai fixé en corrigeant un truc sur les tuto (puisque je tenais le fichier en main).
