### ISSUE TITLE
Mettre des indications de temps relatives ET absolues sur les messages

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#489]
Cf les deux pages de discussions ici : http://zestedesavoir.com/forums/sujet/79/suggestion-indication-de-temps-passe-depuis-la-derniere-reponse?page=1

(à lire jusqu'au bout !)

**Comment by firm1** [comment]
Notons que la solution qui avait l'air de plaire au plus grand monde était : 

**Alex-D a écrit**

> Je propose donc la solution suivante (qui a déjà été énoncée) :
> - En deçà d'une heure : "Il y a MM minute(s)"
> - Au delà d'une heure, mais aujourd'hui/hier : "Aujourd'hui / Hier, à HHhMM"
> - Au delà : "Le JJ MOIS ANNEE à HHhMM" ou le nom du jour à la place du déterminant "Le", ex : "Samedi 3 mai 2014 à 11h10"

**Comment by SpaceFox** [comment]
Non, c'est justement pour ça que je disais qu'il fallait lire jusqu'au bout...

**Comment by Alex-D** [comment]
Donc on part sur quoi ?

Moi ma proposition m'allait bien, elle avait l'air de plaire à tous sauf à toi en fait. On peut rajouter la tooltip avec l'information complémentaire pour contenter tout le monde.

Personnellement, ça me fait suer de voir "il y a 3 jours" ou "il y a 3 ans" car c'est complètement imprécis. Pour autant, une date absolue pour me dire un truc qui est arrivé il y a 5 minutes, je préfère avoir "il y a 5 minutes". Bref... si la tooltip complémentaire plait à tout le monde, on part là dessus.

**Comment by SpaceFox** [comment]
> On peut rajouter la tooltip avec l'information complémentaire pour
> contenter tout le monde.

C'est ce que je propose depuis le début... sauf qu'au début de la
conversation sur le forum, ça a soulevé des hauts cris en mode "non, les
trucs dans les tooltips c'est mal, supprimons plutôt complètement la
fonctionnalité".

Ensuite j'ai réexpliqué sur 2 pages pourquoi avoir systématiquement les
deux informations était indispensable.

Donc oui, ta proposition me va. A condition d'avoir les tooltips dessus.

**Comment by cgabard** [comment]
Moi aussi j'aime avoir les deux infos. Tant que j'ai les deux, l'implémentation je m'en fout.

**Comment by Coy0te** [comment]
La proposition d'Alex + tooltip me paraît très bien également.

**Comment by ShigeruM** [comment]
Idem, au final je me fous de comment ça apparaît, du moment qu'il y a les 2.

**Comment by geoffreyc** [comment]
Il faudrait vraiment que la date/heure absolue soit celle "par default" au
dela de quelques heures. C'est vraiment chiant en ce moment quand on doit
faire un calcul mental pour essayer de voir a quelle heure un message d'il
y a quelques jours a été rédigé.

2014-05-12 9:56 GMT+01:00 ShigeruM notifications@github.com:

> Idem, au final je me fous de comment ça apparaît, du moment qu'il y a les
> 2.

**Comment by Alex-D** [comment]
C'est exactement ce que je propose ;)

Cf la citation de moi par firm1 : https://github.com/Taluu/ZesteDeSavoir/issues/489#issuecomment-42781558

**Comment by geoffreyc** [comment]
Oui oui javai vue effectivement, je ne faisais qu'appuyer ce point.

**Comment by Alex-D** [comment]
Ca me va.

Par contre, il faudrait un dev back pour coder le filtre qui va bien pour effectuer ce traitement du coup.

Si une bonne âme souhaite se dévouer ça me ferais gagner un peu de temps :)

**Comment by SpaceFox** [comment]
Je prends ce soir.

**Comment by Alex-D** [comment]
J'imagine qu'il y a un filtre existant pour la date absolue, si vous le connaissez est-il possible de me le linker/donner son nom. Merci !

**Comment by firm1** [comment]
@Alex :

https://docs.djangoproject.com/en/dev/ref/templates/builtins/#date

Exemple : {{ value|date:"D d M Y" }}

**Comment by SpaceFox** [comment]
> J'imagine qu'il y a un filtre existant pour la date absolue, si vous le
> connaissez est-il possible de me le linker/donner son nom. Merci !

Heu, pourquoi faire si je te fais un filtre qui te donne la bonne date ?!

2014-05-14 14:58 GMT+02:00 firm1 notifications@github.com:

**Comment by Alex-D** [comment]
Pour le tooltip : on affiche toujours la date absolue dans le tooltip nan ? Ou alors le complémentaire, je ne sais plus à force de débattre.

Si c'est le complémentaire, alors j'utilise deux fois ton filtre du coup pas besoin du filtre date, mais dans le cas contraire il sera utile.

PS : Merci firm1 !

**Comment by SpaceFox** [comment]
Le complémentaire.

**Comment by Alex-D** [comment]
Ok d'ac, bon bah on oublie le |date alors (enfin merci quand même ça me servira peut-être ailleurs).

**Comment by SpaceFox** [comment]
Tu as un nouveau fichier date avec deux nouveaux filtres : `format_date` (pour l'affichage) et  `tooltip_date` (pour mettre dans les tooltips).

**Comment by Alex-D** [comment]
Merci bien, par contre je vais faire mon chieur :D

Ca serait cool d'avoir quelque chose d'un poil plus fin comme je l'avais dit bien plus tôt :
- En deçà d'une heure : "Il y a MM minute(s)"
- Au delà d'une heure, mais aujourd'hui/hier : "Aujourd'hui / Hier, à HHhMM"
- Au delà : "Le JJ MOIS ANNEE à HHhMM" ou le nom du jour à la place du déterminant "Le", ex : "Samedi 3 mai 2014 à 11h10"

Bon, dans l'absolu, j'ai les filtres du coup la modif est indépendante et s'appliquera partout.

**Comment by SpaceFox** [comment]
Ha oui, j'ai confondu avec un autre truc pour la gestion de la bascule.

Par contre ce qui m'emmerde dans le rendu, c'est que le texte du type "Samedi 3 mai 2014 à 11h10" est _beaucoup_ plus long que les textes courts de <= hier, surtout si on commence à taper dans le "Mercredi 25 septembre 2013 à 12h34".

Ça rend bizarre sur le design actuel du coup.

**Comment by Alex-D** [comment]
C'était un exemple, faut virer le nom du jour.

Il me faut le déterminent aussi "le 3 sept. 2013 à 12h34"
on peut imaginer que si c'est l'année courante on n'affiche pas l'année, pour alléger et éviter les confusions.

Du coup sur les topics consultés régulièrement on aurait "le 3 sept. à 12h34" ce qui est très correct.

**Comment by Alex-D** [comment]
Aussi, le texte rendu ne doit pas commencer par une majuscule, c'est dans le template avec les filtres que je gère cette majuscule au besoin. Ca permet de caser la date dans une phrase par exemple.

**Comment by SpaceFox** [comment]
Je croyais qu'on avait dit qu'on utilisait pas d'abréviations pour rester
accessibles ?

Sinon, je suis pour rester sur un truc le plus simple possible et éviter
d'avoir 50 formats différents - on en a déjà 3, c'est pas mal.

**Comment by SpaceFox** [comment]
La majuscule est dans le template actuel (filtre capfirst), sauf pour le
"Dans le futur", qui ne devrait jamais servir.

**Comment by Alex-D** [comment]
Il est vrai... donc bah "le 45 septembre 2013 à 12h56" qui est le plus long possible, ça va encore.

Ouep je parlais de capfirst et tout, niquel si y a pas de majuscule déjà là :)

**Comment by Alex-D** [comment]
Y a moyen de mettre un paramètre pour avoir "le 3/09/2013 à 12h30" ?

**Comment by SpaceFox** [comment]
Pour quoi faire ?

**Comment by Alex-D** [comment]
le 45 septembre 2013 à 12h56
le 3/09/2013 à 12h30

La différence de longueur est notable, et dans la liste des sujet, la colonne "Dernier message" a une largeur limitée, j'aimerais bien avoir la date relative malgré un format court quand la date est relativement ancienne, sans péter le design :)

**Comment by SpaceFox** [comment]
C'est une date absolue que tu m'as demandé là :)

Si à un endroit tu as _toujours_ besoin d'une date absolue, elle se gère
avec le filtre Django |date. Les filtres humanize et custom ne sont là que
pour gérer les cas particuliers impliquant des changements de formats
dynamiques et des dates relatives.

**Comment by Alex-D** [comment]
Non, je voudrais une date relative, mais qui lorsqu'elle est absolue (dans le dernier else) soit une date absolue courte et non longue.

**Comment by SpaceFox** [comment]
KISS ?

On pourrait hein. Mais là j'ai franchement l'impression qu'on va perdre
l'utilisateur.

**Comment by Alex-D** [comment]
Bon bah j'adapterais alors... faudra que je change mes largeurs pour tenir compte de ce cas extrême là.

**Comment by cgabard** [comment]
Je confirme vous m'avez déjà perdu

**Comment by Alex-D** [comment]
C'est fait sur ma branche.
