### ISSUE TITLE
Equations latex mal alignées

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#4898]
> Petit problème niveau équation $\LaTeX$ :
> 
> Cette formule (aussi stupide soit-elle) :
> ```latex
> \hat \theta_{MC} = \frac{\sum_{i = 1}^n P(Y_i | X = 1)}{\pi^3}
> ```
> 
> Devrait donné ça :
> $\hat \theta_{MC} = \frac{\sum_{i = 1}^n P(Y_i | X = 1)}{\pi^3}$
> 
> Et à la place j'obtient ceci :
> ![](https://framapic.org/6WwxUcZmwnea/60jecizhh8Mm.png)
> [Lien de l'image](https://framapic.org/6WwxUcZmwnea/60jecizhh8Mm.png)
> 
> La formule est décalé très à droite.
Source: [Heziode](/billets/2457/chronique-zest-of-dev-6/?page=1#p174862)

**Comment by Situphen** [comment]
J'ai regardé un peu et ça m'a l'air d'être un bug très bizarre !

1. le bug se produit pour moi sur la béta (avec Chrome et Firefox) mais pas en local (avec Chrome et Firefox)
2. le CSS n'a pas l'air d'être en cause (dans l'inspecteur de Chrome, je ne vois pas de différences dans le CSS entre la béta et en local)
3. le contenu de `.katex-html` sur la béta est différent de celui en local, et quand on copie le contenu de `.katex-html` de la version en locale vers la version béta (avec l'inspecteur de Chrome ou FF) le problème disparait

**Comment by Situphen** [comment]
J'ai pensé à mettre à jour zmarkdown en local chez moi et j'ai le bug, donc il vient probablement des dernières modifications d'un des modules de zmarkdown
