### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#49]
Je suis en train de bosser sur le dropdown des différents menus du header et je me rends compte d'une chose, le système de validation est identique à celui des tutoriels.

Pour récupérer la liste des articles à valider, ils font tous les deux exactement les mêmes requêtes. Est-ce que c'est normal ? Si oui, pourquoi répéter ce code ?

**Comment by GerardPaligot** [comment]
Ok, je viens de comprendre pourquoi il m'affichait pas les tutos en validation dans la zone de validation des articles et inversement pour la zone de validation des tutos.

Il y a une redondance de code assez phénoménal. Faut vraiment créer le module commun aux articles et aux tutos. Ce n'est vraiment pas beau.

D'ailleurs, je me pose une question. Devons-nous réellement faire une distinction entre les tutos et les articles dans la zone de validation ?

**Comment by firm1** [comment]
> Il y a une redondance de code assez phénoménal. Faut vraiment créer le module commun aux articles et aux tutos. Ce n'est vraiment pas beau.

Il y'avait un choix à faire, entre faire de la redondance d'une part et bourrer le code de if 'article' then ... J'ai opté pour la redondance. Au fond, les deux modules (articles et tutos) n'ont pas pour vocation de marcher de la même façon. Je n'aime pas mélanger deux truc fonctionnellement différent juste parce qu'ils ont un truc en commun. Après, perso, je ne sais pas si tu as vu le bordel que c'est de gérer proprement ça avec git (encore ce n'est pas fini) mais si tu veux t'y coller pour en faire un truc commun, et que le truc marche je ne dirais pas non, mais autant de dire, que c'est clairement le plus gros du travail.

> D'ailleurs, je me pose une question. Devons-nous réellement faire une distinction entre les tutos et les articles dans la zone de validation ?

Mon coté flexible me dit que si demain on décide d'appliquer une process de validation différent entre les tutos et les articles (mise en ligne par votes, corrections mineures, etc.) il ne faudra que quelques heures de dev en plus.

**Comment by GerardPaligot** [comment]
Globalement, je suis d'accord. Par contre, il y a deux gros inconvénients :

1/ Il n'est pas dit que la solution actuelle divergera. A partir du moment où les choses sont posées et fonctionnent, elles changent rarement dans son fonctionnement générale (même si les fonctions internes évolues).

2/ Du coup, au quotidien, il va falloir répercuter nos modifications à deux endroits différents. Cela peut donc causer deux fois plus de bugs. Ce n'est juste pas possible.

Après, je n'ai pas encore vu la gestion de ces ressources via Git et je sais que c'est un très gros travail. Mais ça me semble nécessaire d'y réfléchir tout en gardant à l'esprit que nous gardons quand même les deux modules `articles` et `tutorials`. On pourrait juste rajouter des modules communs (validation, par exemple) qui s'occuperaient des choses communes aux deux et à d'autres modules à venir.

J'arrive à la fin de mes PR. Ma rentrée est lundi. Si je n'ai pas trop de taff, je m'engagerais dans le refactoring conséquent de ces deux modules.

**Comment by firm1** [comment]
1/ Je n'ai personnellement pas envie de tomber dans les travers de SIT, qui développe des trucs tellements précis et fixes que lorsque la communauté demande une évolution, il faut attendre des mois, parce qu'au début ils se sont dit "rien ne divergera".

2/ Les deux modules étant assez indépendant, tu peux toucher à l'un sans causer du tort à l'autre.

Je ne suis pas contre les modules communs, mais il faut savoir quoi mettre en commun. Après quelque chose me dit, qu'une fois que tu seras rentré dans le code de ces parties, l'envie de faire du commun te passeras certainement.

Tu fournis déjà un excellent taf pour quelqu'un qui s'est mis à django très recemment.

**Comment by GerardPaligot** [comment]
Ouais, je commence à comprendre tes choix.

Alors, je laisse cette issue ouverte pour pouvoir en discuter quand l'un de nous voudra créer les modules en commun.

> Tu fournis déjà un excellent taf pour quelqu'un qui s'est mis à django très recemment.

Thanks. :)

**Comment by gustavi** [comment]
UP ! On en est où d'ici ? C'est encore pertinent ?

**Comment by Eskimon** [comment]
Je suppose que ca sera réglé avec la ZEP 12 qui unifiera le tout ?

**Comment by cgabard** [comment]
Si ça sera réglé par la zep-12, on ne va pas la fixer dans le code comme ça donc ce ticket peut être fermé.

**Comment by firm1** [comment]
Si on ferme l'issue on risque de l'oublier. Je suis d'avis de la laisser ouverte tant que c'est pas corrigé

**Comment by cgabard** [comment]
Bah non. Intrinsequement la zep-12 va la régler puisque c'est la même chose : rendre le code article et tuto identique. On risque pas d'oublier, sauf peut être de fermer le ticket.

**Comment by Eskimon** [comment]
Je cite la ZEP 12 :

> Dans cette nouvelle vision des choses, il faudrait que l'utilisateur puisse rédiger et assembler les extraits "comme bon lui semble" sur 4 niveaux de structures, qui définiraient ce qu'est le tutoriel/l'article :
> - Extrait seul : il s'agit d'un article
> - Plusieurs extrait rassemblés sous un même titre (chapitre ?) : il s'agit d'un mini-tuto
> - Plusieurs chapitre rassemblé sous un même titre (partie ?) : il s'agit d'un moyen-tuto
> - Plusieurs parties rassemblées sous un même titre : il s'agit d'un big-tuto

Donc c'est fermable d'après moi car intrinsèquement présent dans la ZEP-12
