### ISSUE TITLE
[v27][beta] Erreur 500 lors d'une connexion en passant par un topic

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#4901]
Prerequis : vous devez être déconnecté

Méthode de reproduction : 

- Allez sur un topic (toujours en mode déconnecté) : [celui-ci par exemple](https://beta.zestedesavoir.com/forums/sujet/10348/tuto-de-beta-pour-verifier-lexport-epubpdf/), mais ça marche avec d'autres
- Cliquez ensuite sur le bouton de login
- Entrez vous identifiants et validez

Une erreur 500 fait son apparition.

**Comment by rezemika** [comment]
C'est bizarre, j'arrive à reproduire ce comportement sur la bêta mais pas en local. Mais les deux n'en sont pas au même commit. La bêta est à `dev/d28279f` et je suis à `fix-4901/a9d83a7` (normalement le dernier commit sur `upstream/dev`.

**Comment by artragis** [comment]
déjà fixé par https://github.com/zestedesavoir/zds-site/pull/4897
