### ISSUE TITLE
Interdire les adresses email temporaires

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#491]
Cette liste ne devrait contenir qu'1 ou 2 noms de domaines tant qu'on est en bêta privée pour pouvoir faire des tests :)

```
@0-mail.com @20minutemail.com @30minutesmail.com @binkmail.com @discardmail. @emailsensei.com @emailtemporanea.net @filzmail.com @hmamail.com @jetable.org @mailcatch. @mailinator.com @mailnator.com @mailnesia.com @msh.mailslite.com @noclickemail.com @notsharingmy.info @pjjkp.com @privy-mail.com @prtnx.com @rtrtr.com @spam.la @spambog.* @trashmail.ws @yopmail.com
```

**Comment by SpaceFox** [comment]
PR #494  (Je pige pas dans quels cas les liens auto fonctionnent et dans quels cas ils ne fonctionnent pas moi...)

**Comment by Alex-D** [comment]
Le lien entre issues/PR se fait quand tu mets le #truc **dans le commentaire** et non dans le titre.

**Comment by firm1** [comment]
Donc c'est fixé.

**Comment by SpaceFox** [comment]
La liste **complète** des adresses mail bannies doit être mise en place avant l'ouverture.

**Comment by ShigeruM** [comment]
Il y a une liste assez conséquente [ici](http://pastebin.com/yCdyaRgr), pour compléter la liste présente dans la PR.

**Comment by Alex-D** [comment]
J'ai mis en place la liste indiquée par @ShigeruM 

Ca sera donc sur le serveur de prod au prochain pull.

**Comment by Eskimon** [comment]
A priori c'est tout bon d'après mon test en prod... je ferme :)
