### ISSUE TITLE
[beta v27]: les équations sont trop grosses et mal alignée verticalement

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#4915]
message : 

```
$\hat \theta_{MC} = \frac{\sum_{i = 1}^n P(Y_i | X = 1)}{\pi^3}$
```

résultat attendu: 
- police à la même taille que le reste du texte
- alignement verticcal sur le texte

résultat obtenu:

![alignemen](https://user-images.githubusercontent.com/1417570/37564825-f9fb7db2-2a9d-11e8-996a-f86b1b0f4573.png)

vu sur #4903

**Comment by vhf** [comment]
Pas réussi à reproduire en local:

<img width="759" alt="screen shot 2018-03-22 at 21 48 53" src="https://user-images.githubusercontent.com/2022803/37797717-de5990c8-2e1a-11e8-85b8-fba470dd44e3.png">

```md
Ceci est une équation: $\hat \theta_{MC} = \frac{\sum_{i = 1}^n P(Y_i | X = 1)}{\pi^3}$, joli non ?

### normal

$$\hat \theta_{MC} = \frac{\sum_{i = 1}^n P(Y_i | X = 1)}{\pi^3}$$

### display

$$
\hat \theta_{MC} = \frac{\sum_{i = 1}^n P(Y_i | X = 1)}{\pi^3}
$$
```

**Comment by AmauryCarrade** [comment]
Y'a moins de décalages, mais on note tout de même le trait de fraction manquant. Le bon rendu devrait être, pour cette formule particulière : 
![capture d ecran de 2018-03-27 17-40-00](https://user-images.githubusercontent.com/1417570/37978264-f156912a-31e5-11e8-8433-6df2d55f39fa.png)
