### ISSUE TITLE
Avoir un rappel des bases du Mardkown à côté des zones de rédaction

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#492]
L'idée est d'avoir un rappel des bases du Mardkown à côté des zones de rédaction (les grandes lignes + un lien vers le tuto).

Je sais qu'on a les boutons, mais c'est toujours utile pour ceux qui préfèrent éviter de jouer avec la souris, et je pense améliorera l'apprentissage du MD.

Le truc le plus important à y mettre est sans doute la gestion des sauts de ligne / paragraphes :)

**Comment by Coy0te** [comment]
S'inspirer de la textarea de [SO](http://stackoverflow.com) pour ça, éventuellement : 
- un premier lien dans la barre de boutons du genre `?`, qui provoque l'affichage d'une première barre d'aide ;
- un lien "Plus d'infos" qui renvoi vers l'article exhaustif.

**Comment by Alex-D** [comment]
Je m'en chargerais, j'ai déjà mon idée là dessus.

**Comment by SpaceFox** [comment]
Si tu pouvais exprimer ton idée que l'on puisse t'aider là-dessus, ce
serait parfait.

Tu as déjà une grosse masse de boulot, ce serait dommage qu'on ne puisse
pas t'aider à avancer !

2014-05-12 2:12 GMT+02:00 DEMODE Alexandre notifications@github.com:

**Comment by cgabard** [comment]
+1 SpaceFox d'autant que c'est une issue facile en soit. Dans tous les cas, ce serait bien d'expliciter, certains auront peut être des avis divergents

**Comment by Alex-D** [comment]
Là, c'est moins simple que vous ne le pensez j'ai l'impression, ça nécessite : du style (responsive) et du JavaScript.

Par contre, vous pouvez rédiger le mini guide. Il faut que ce soit assez concis avec la syntaxe de base.

En soi, les choses "simples" je les ferais très rapidement, si je mets du temps c'est que ça n'est pas _si_ simple.

Sinon, si vous voulez m'aider : #464 et #465

**Comment by SpaceFox** [comment]
Dans une v1, il faut se limiter à la demande : un rappel des bases du MD
dans une bête zone de texte. Un truc ultra-simple.

Le fonctionnement à la StackOverflow, il est génial, mais pour moi c'est
clairement quelque chose qui doit attendre une v2.

**Comment by cgabard** [comment]
Je comprend pas le besoin de JS justement : il y a déjà un editeur, le but de ce ticket est d'avoir un aide mémoire textuel. Pas un assistant en JS. Les deux sont différents pour moi.

Dans tous les cas, qu'elle que soit la solution choisie, je ne voit pas de raison de ne pas discuter de la solution que tu as choisis, certains auront peut etre des objections, légitimes ou non.

**Comment by SpaceFox** [comment]
D'autre part, Alex, les idées dans un projet - et d'autant plus dans un
projet libre - ça se partage. Pour deux raisons :
1. La pérennité. Si jamais tu tombes malade ou pire, ton idée sera perdue à
   jamais, et ce serait vraiment dommage.
2. La discussion. Peut-être qu'on a des objections à ton idée, et pour ça
   il faut la connaître. Sinon c'est un risque de refus de la PR, et ce serait
   dommage d'avoir fait le boulot pour rien.

Voilà pourquoi, dans tous les cas, partager ses idées, même si on pense en
faire la réalisation, est absolument indispensable.

**Comment by Alex-D** [comment]
Bon alors soyons clairs sur ce qu'on veut : 
- Un petit bouton rigolo tout gentil "Aide markdown" ;
- Quand on clic sur le bouton rigolo, hop ça affiche une petite boite d'info (oooh du JavaScript est nécessaire ici, la magie n'existe pas) ;
- Dans cette petite boite on aura donc un rappel mémoire (bah tiens, la petite boite rigolote elle a besoin de CSS : boom badaboom, faut aussi faire quelques lignes de SCSS... et faut que ce soit responsive : wowowow faut toucher à au moins 3 fichiers... tiens tiens !) ;
- Ce petit aide mémoire est très court mais permet d'avoir les bases, ainsi qu'un petit lien vers l'aide complète.

En somme, c'est tout ce qu'on a déjà dit sur le forum, mais aussi simple que cela puisse paraître ça nécessite un minimum de travail, le rendu aussi simpliste peut-il paraître.

**Comment by SpaceFox** [comment]
> Un petit bouton rigolo tout gentil "Aide markdown" ;

En fait même pas : pour moi, au moins dans une v1, l'aide est affichée,
point barre. Pas de dynamisme ni rien.

**Comment by Alex-D** [comment]
Non, bah c'est dégueulasse ça... Sauf si t'as une solution élégante à me proposer.

Mais tous les super-user auraient un truc inutile qui leur serait proposé.

Est-ce qu'on pourrait me screen l'exemple SO ? Je ne pense pas avoir de compte chez eux.

**Comment by Coy0te** [comment]
@ Tous : détendons-nous un peu le slip. C'est clairement pas une feature critique à réaliser pour la v1, et ça a été tagué **à juste titre** `evolution`. Donc on en discute, on explique ce qu'on veut, etc. Mais on ne le réalise pas, tant que la beta publique n'est pas lancée.

S'il faut trancher maintenant, pour moi dans la v1 on se contente d'un lien vers l'article exhaustif de Shig, c'est suffisant.

**Comment by Alex-D** [comment]
Ah en fait, c'est visible publiquement... :-° I'm a boulay. Donc sur SO c'est sympa, mais faudrait déjà qu'on ait un éditeur qui soit joli (je sais, j'y travail).

Un lien ça me semble pas mal en soi. On pourra mettre la mini aide dans une v1.1 à la limite.

NB : quand je dis _dégueulasse_, c'est pas agressif... désolé pour mon vocabulaire qui n'a peut-être pas la même signification pour chacun :/

**Comment by Alex-D** [comment]
@Coy0te : t'as cité un pseudo existant, dans un dépôt privé... J'espère que Github est assez intelligent pour ne pas le notifier, sinon le pauvre va se poser des questions XD

**Comment by SpaceFox** [comment]
> Non, bah c'est dégueulasse ça... Sauf si t'as une solution élégante à me
> proposer.
> Mais tous les super-user auraient un truc inutile qui leur serait proposé.

En même temps, on s'en fiche : c'est temporaire et si on la met à un
endroit qui n'est pas trop gênant, il suffira juste de ne pas la lire si on
sait déjà comment fonctionne MD.
Mon idée c'était un bloc comme le 1er bloc d'exemple sur wikipédia EN :
http://en.wikipedia.org/wiki/Markdown (mais adapté)

> Est-ce qu'on pourrait me screen l'exemple SO ? Je ne pense pas avoir de
> compte chez eux.

Pas la peine, la zone de rédaction est publique.

> S'il faut trancher maintenant, pour moi dans la v1 on se contente d'un
> lien vers l'article exhaustif de Shig, c'est suffisant.

Justement, non, AMHA ce n'est pas suffisant. En particulier, si on explique
pas au moins en 2 mots le coup des sauts de lignes, on va avoir des tas
d'incompréhensions.

**Comment by Alex-D** [comment]
Si quelqu'un est motivé à rédiger "le mini-manuel du Markdown" qui sera accessible à côté de la zone de saisi, en plus du lien vers l'article/page qui décrit tout, ça pourrait être sympa de l'avoir pour la beta :)

**Comment by Coy0te** [comment]
Il faudrait un truc qui respecte quel format, à la louche ? (combien de lignes, quelle largeur)

**Comment by Alex-D** [comment]
Format "optimal". Je pense qu'il faut faire un premier jet et ajuster ensuite. Je ne saurais dire le format qui serait préférable.

Sachant qu'ici on ne parle que des bases, ça ne devrait pas être très grand.

**Comment by Coy0te** [comment]
C'est pas si évident de faire un truc bref dans un format simple "pavé de texte". Rien qu'en se limitant à gras, italique, lien, citation, code, et saut de ligne, ça fait déjà bien long.

**Comment by SpaceFox** [comment]
AMHA si on ne doit en garder qu'un, et le mettre en premier, c'est les
sauts de lignes.

**Comment by Coy0te** [comment]
_Les simples retours à la ligne ne sont pas pris en compte. Pour aérer vos paragraphes, pensez à sauter des lignes ! Pour plus d'infos, consultez notre [guide d'utilisation](http://url_article)._

**Comment by Eskimon** [comment]
Et sinon une petite liste genre:

```
**gras**
*italique*
![texte de lien](url du lien)
> citation
+ liste a puces
```

**Comment by Alex-D** [comment]
Ca me paraît pas mal l'ensemble de vos propositions :)

La phrase de @Coy0te serait-elle réductible ? Car là c'est un peu long non ?

**Comment by Eskimon** [comment]
Ca donne quoi ca ?

![](https://dl.dropboxusercontent.com/u/18967337/temp/test.png)

**Comment by Alex-D** [comment]
J'aime bien le contenu, mais ça n'a pas sa place dans la sidebar : la sidebar est dédiée à la navigation et aux actions.

En bon français, je préfère "Entrée" à "Enter" :)

**Comment by Eskimon** [comment]
> En bon français, je préfère "Entrée" à "Enter" :)

Oups, déformation du pays !!

Sinon assez d'accord avec toi sur la sidebar en fait... J'voulais juste faire un essai mais j'ai pas trop réfléchi à la syntaxe...

(D'ailleurs à la place de "Syntaxe Markdown" plutot dire "Mémo Markdown" ca sonne plus sympa !)

Idée en vrac:
- Pourquoi pas la meme chose _sous_ la sidebar
- Pourquoi pas dans un (gros) tooltip sur un bouton dans la barre des trucs du wysiwyg
- Pourquoi pas sous la zone de redaction (mais que se passe t'il quand on passe en prévisualisation ?)

**Comment by Alex-D** [comment]
Sous la sidebar : sur la plupart des pages ça sera bien trop bas ou trop haut, mais jamais en face de la zone de saisie.

Pour moi c'est quelque chose qui doit être _directement_ lié à la zone de saisie, donc un bloc à côté de celle-ci. En dessous ça me semble peu judicieux. Pourquoi pas au dessus à partir du moment où on est en saisie.

**Comment by Alex-D** [comment]
Fait et visible sur la preprod

**Comment by cgabard** [comment]
Le bouton afficher/masquer l'aide markdown ne fonctionne pas chez moi
(FF/Ubuntu 14.04 64bits)

Christophe.

**Comment by ShigeruM** [comment]
Chez moi ça fonctionne mais il manque la phrase de Coyote : "Les simples
retours à la ligne ne sont pas pris en compte. Pour aérer vos paragraphes,
pensez à sauter des lignes !". Je ne vois pas bien comment la réduire, mais
en même temps il y a la place vu la taille du bloc qui s'ouvre quand on
clique sur le bouton...

2014-06-03 10:05 GMT+02:00 Christophe Gabard notifications@github.com:

**Comment by SpaceFox** [comment]
> Le bouton afficher/masquer l'aide markdown ne fonctionne pas chez moi

Idem sur Windows 8 / Chrome 35.

Et surtout pour moi il manque LA phrase importante sur le fonctionnement
des sauts de paragraphes.

**Comment by Alex-D** [comment]
J'ai oublié la phrase :-° manque de sommeil toussa.

Pour afficher/masquer, faut vider votre cache les loulous : c'est un combo CSS/JS donc si votre CSS est pas à jour, vous ne verrez rien fonctionner.

**Comment by SpaceFox** [comment]
Alors on a un problème de conf, le cache sur la préprod est sensé être
d'une heure sur la préprod. Justement pour éviter ce genre de problèmes.

**Comment by Alex-D** [comment]
En tous cas, chez moi ça fonctionne donc je ne vois que ça comme solution.

**Comment by SpaceFox** [comment]
Ha mais ça marche après refresh hein. Ce que je dis, c'est juste qu'on a un
problème de conf parce que je n'aurais pas du avoir à forcer le refresh.

2014-06-03 10:58 GMT+02:00 Alexandre Demode notifications@github.com:

**Comment by SpaceFox** [comment]
Il manque l'indication du fonctionnement des sauts de ligne dans l'aide, or c'est **la seule** aide _vraiment_ indispensable parce que incompréhensible pour les débutants.

**Comment by Coy0te** [comment]
Tu m'enlèves la réouverture de la bouche, j'allais faire la même remarque à l'instant !

**Comment by Alex-D** [comment]
Oups, je fais une PR soon :)

**Comment by Coy0te** [comment]
Par ailleurs, c'est un détail, mais est-ce que ça vaudrait pas le coup de `disable` le bouton de l'aide markdown pendant la période d'antispam de 15 minutes, de la même façon que les deux boutons envoyer et aperçu ?

**Comment by Alex-D** [comment]
Je ne vois pas pourquoi ça devrait être désactivé, ça n'est pas une action de formulaire.

**Comment by Coy0te** [comment]
C'est pas une action, certes, mais afficher une section d'aide pour un textarea qui est disabled, c'est pas spécialement _brainy_ non plus. 

Après c'est qu'un détail, si y'a que moi qui trouve ça un peu bête, ça ne m'empêchera pas de dormir. =)

**Comment by Alex-D** [comment]
Les actions sont indépendantes : tu peux ne pas pouvoir poster mais lire la doc MD et accéder à la doc complète, je ne vois pas le soucis.

**Comment by Alex-D** [comment]
Voilà, avec cette PR ça sera bon :)
