### ISSUE TITLE
Reset de mot de passe inactif

### ISSUE THREAD

**Issue by viki53** [zestedesavoir/zds-site#4926]
Petit bug (à confirmer) signalé via Twitter :

> Je n'arrive pas à modifier mon mot de passe, après avoir cliqué sur le lien dans l'email du mot de passe oublié, le formulaire ne semble pas s'envoyer.
https://twitter.com/nlavielle/status/981457319681765376

Si vous voulez bien y jeter un œil… :)

**Comment by Situphen** [comment]
J'ai moi-même testé en production et je n'ai pas eu de problème. Néanmoins le problème n'est toujours pas résolu ([d'après ce tweet](https://mobile.twitter.com/nlavielle/status/981642656517447680)). ~J'ai l'impression que c'est un compte créé via les réseaux sociaux car il y a [cette erreur Sentry](http://sentry.sandhose.fr/zeste-de-savoir/backend-l7/issues/1320/) qui est apparue et l'horaire colle avec le tweet.~ [Apparemment non](https://mobile.twitter.com/nlavielle/status/981789527512698880)

Vu le nombre de bugs avec la connexion par les réseaux sociaux, il serait bien à minima de ne plus proposer l'inscription par ce moyen, non ?

**Comment by AmarOk1412** [comment]
Possible de savoir l'extension du mail ? Peut-etre une regle de spam ? En tout cas ca a l'air de marcher.

**Comment by Situphen** [comment]
Je ne le connais pas malheureusement :/

**Comment by philippemilink** [comment]
Je pense qu'on peut fermer ?
