### ISSUE TITLE
Changer l'apparence quand on a plussoiyé

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#493]
(Kjé)
Actuellement, si un post a déjà quelques +1/-1 on ne peut pas savoir si nous même l'avons fait (ou alors j'ai raté quelque chose)

**Comment by Alex-D** [comment]
En fait, il me faudrait simplement pouvoir récupérer l'information du vote dans les templates. Si j'ai ça c'est bon.

Actuellement c'est juste le pouce qui a le plus de vote qui est mis en valeur : ce comportement est le comportement publique, mais pas celui d'un membre.

**Comment by Eskimon** [comment]
C'est résolu ca non ? On pourrait fermer ?
