### ISSUE TITLE
Installation ArchLinux - Ajouter un message pour inviter l'utilisateur à mettre sur système à jour si ce n'est pas le cas

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#4937]
En gros, si jamais on a déjà des paquets installés qu'on met à jour (et c'est quasi-obligé vu qu'il y a le groupe `base-devel`) on risque de casser des choses.

Plus d'informations dans la doc https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported

Une autre solution c'est de faire `-Syu` pour la màj du système en même temps mais c'est pas la meilleure solution selon moi.

**Comment by pierre-24** [comment]
Mmmh, tant que je suis dedans, qu'est ce que je peux faire dans #5001 ?

**Comment by gustavi** [comment]
Yes

**Comment by pierre-24** [comment]
... Oui, mais quoi ? :p

**Comment by gustavi** [comment]
Ok j'ai lu de travers ! En gros avant toute installation sur une ArchLinux il faut s'assurer qu'il n'y a pas de paquets à mettre à jour. Il y a une commande qui permet de savoir ça mais je n'ai pas de machine Arch sous la main de suite.

**Comment by AmauryCarrade** [comment]
En l'occurrence c'est `pacman -Qu` pour vérifier la présence de nouvelles versions (et uniquement ça), ou `pacman -Syu` pour mettre à jour tous les paquets (demande confirmation et ne fait rien s'il n'y a rien à mettre à jour, de toute façon).

**Comment by pierre-24** [comment]
C'est normal qu'il en profite pour mettre à jour des trucs du genre le noyau en passant ? :p

**Comment by pierre-24** [comment]
Bon, archlinux balance python 3.7, qui est pas compatible avec django 1.11 : https://code.djangoproject.com/ticket/28814 (`SyntaxError: Generator expression must be parenthesized`) ;)

Y'a moyen de forcer du python 3.6 ?

**Comment by AmauryCarrade** [comment]
>C'est normal qu'il en profite pour mettre à jour des trucs du genre le noyau en passant ? :p

C'est complètement normal, `-y` fait une mise à jour système (`-u` s'assurant que les bases de paquets soient à jour pour qu'il n'en manque pas), et les mises à jour ne sont jamais partielles sous Arch ([cf.](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported)), donc ça met tout à jour (noyau inclu si besoin est).

Mais ce n'est pas forcément très grave dans le sens que c'est généralement positif d'avoir un système à jour (Arch recommandant de toute façon de faire les mises à jour complètes régulièrement).

>Y'a moyen de forcer du python 3.6 ?

Y'a toujours le paquet `python36` sur l'AUR, sinon… avec pipenv ? ou en l'installant à la main (genre en le compilant ou avec le binaire). Je ne sais pas sinon, c'est pas trop dans l'esprit d'Arch de ne pas avoir les dernières versions ^^'

(C'est bizarre par contre, le ticket de compatibilité côté Django semble fermé / résolu ? Sauf si on est pas à jour nous)

**Comment by pierre-24** [comment]
Non, on est avec django 1.11, et à priori le ticket a l'air de concerner django 2.0

**Comment by AmauryCarrade** [comment]
Ah oui au temps pour moi, j'ai lu le ticket un peu vite, j'ai cru que ça concernait aussi 1.11

**Comment by gustavi** [comment]
En effet là on est pas trop compatible. La solution serait d'intaller un paquet via AUR. Après faut se dire qu'un utilisateur sur Arch n'utilisera certaienement pas un script qui fait tout pour lui (en tous cas c'est ce que je fais, c'est pas vraiment la philosophie de la distribution).

La solution que je vois mais qui ne me satisfait pas pour autant : vérifier si python3.6 est là, si ce n'est pas le cas demander à l'utilisateur de l'installer (via l'AUR en en compilant la version directement) puis de relancer le script.
