### ISSUE TITLE
Intégrer le bloc neutre à l'éditeur

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#4938]
Ajouter un bouton à l'éditeur qui permet d'ajouter un bloc neutre et de générer le texte suivant;

```
[[neutre|titre du bloc]]
|
```

**Comment by A-312** [comment]
Et se décider sur l'icône

**Comment by artragis** [comment]
Il faudrait vraiment le faire.

**Comment by A-312** [comment]
http://www.famfamfam.com/lab/icons/silk/

text_padding_bottom

**Comment by A-312** [comment]
text_padding_bottom : ![image](https://user-images.githubusercontent.com/18501150/64318253-f2263380-cfb9-11e9-8922-040655bb014c.png)

**Comment by philippemilink** [comment]
Je viens de le rajouter. Avant de faire ma PR, j'ai juste deux questions:
- la version Retina des images, on agrandit juste manuellement l'image ? (faudrait peut-être rajouter la réponse dans la doc)
- (par simple curiosité) où est / quel est le mécanisme qui préfixe toutes les sprites par `zform` dans le SCSS ?

**Comment by A-312** [comment]
Non retina c'est une image de taille original (en tout cas je fais toujours en sorte d'avoir la taille correspondante, et de rétrécir pour l'image normale)

**Comment by philippemilink** [comment]
Mais les icônes fournies sur le site http://www.famfamfam.com/lab/icons/silk/ sont de tailles 16x16, or les images Retina sont en 32x32... On fait comment si on ne les agrandit pas à la main ? (Je suis d'accord que niveau qualité ce n'est pas terrible...)

**Comment by A-312** [comment]
> Mais les icônes fournies sur le site http://www.famfamfam.com/lab/icons/silk/ sont de tailles 16x16, or les images Retina sont en 32x32... On fait comment si on ne les agrandit pas à la main ? (Je suis d'accord que niveau qualité ce n'est pas terrible...)

On utilise les originaux ou on prend quelque part d'autre

**Comment by philippemilink** [comment]
Les originaux de famfamfam sont disponibles quelque part ? Sinon où est-ce que je peux trouver ce genre d'icônes ?

**Comment by A-312** [comment]
![image](https://user-images.githubusercontent.com/18501150/66714410-cd8e5a00-edb6-11e9-9380-fdf42310802a.png)

Réutilise l'icone information `(i)` converti le en noir et blanc dessine un N : 

```
X_ X
XX X
XX_X
X_XX
X XX
X _X
```

En "_", tu mets le blanc en alpha 132 ceci équivaut à une transparence de 52%.

Pour effacer le i, suffit d'utiliser les couleurs d'a côté gauche/droite : 
![image](https://user-images.githubusercontent.com/18501150/66714443-3f66a380-edb7-11e9-8b43-cfa9f5fffc38.png)
![image](https://user-images.githubusercontent.com/18501150/66714469-910f2e00-edb7-11e9-80e1-7f6cc438ae96.png)
