### ISSUE TITLE
La compilation LaTeX dépend de chemins hardcodés

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#4939]
https://github.com/zestedesavoir/zds-site/blob/751d9930c4534acfef07a81c7cc5c47e5d105fd3/zds/tutorialv2/publication_utils.py#L382-L388

Est-ce vraiment nécessaire ? À aucun moment c'est garanti que c'est installé à cet endroit. Il y a un mécanisme de recherche de paquets dans latex pour ça, symlink des fichiers comme ça à l'arrache, c'est pas très beau.

C'est bloquant pour le déploiement.

cc @artragis

**Comment by sandhose** [comment]
Dans mes tests j'ai cloné latex-template en récursif dans `TEXMFHOME/tex/generic/`, et ça marchait™.

**Comment by artragis** [comment]
cf le projet latex-template, je n'ai fait que porter ce qu'ils demandaient
au départ on n'en avait pas beosin mais on a eu des pbs lorsqu'on est passé à lualatex.

**Comment by pierre-24** [comment]
Comme le dis @sandhose, c'est sencé fonctionner si tu met le .cls et le .lua dans `$TEXMFMACHIN`. Il faut juste, comme tu l'a dit, faire un `texhash` après.

**Comment by artragis** [comment]
il me semble que @vhf avait eu des soucis, c'est même pour ça qu'il avait ajouté cette copie. A l'heure actuelle, tout fonctionne, et le script d'installation est bon.

Si vous avez une solution qui marche bien partout je veux bien faire la revue, mais ça serait cool que ça ne ralentisse pas la release, ça fait vraiment longtemps que c'est dans les tuyaux là.
