### ISSUE TITLE
500 sur l'envoi d'un MP

### ISSUE THREAD

**Issue by finkiki** [zestedesavoir/zds-site#4943]
J'a essayé d'envoyer un MP sans titre et le site m'a renvoyé une erreur 500. J'ai actualisé et réessayé mais la même erreur est réapparue. Pourtant le message est quand même parti (j'en ait envoyé deux du coup)

**Comment by AmarOk1412** [comment]
Comment as-tu envoye un message sans titre ? Normalement, il te demande de remplir le texte field.

**Comment by firm1** [comment]
Je n'arrive pas non plus a reproduire le bug.

Comment as tu fait @finkiki ?

**Comment by artragis** [comment]
il faut qu'on soit face à un membre qui s'est inscrit sur les réseaux sociaux sans donner d'email mais dont le réglage "recevoir un mail lors des MP" est actif.

**Comment by nils-van-zuijlen** [comment]
Il faudrait donc éviter d'envoyer des mails aux utilisateurs qui n'en ont pas lors de l'envoi de MPs ?

Je prends.

**Comment by gllmc** [comment]
Exactement (pour toute notification en fait) :)

**Comment by nils-van-zuijlen** [comment]
Oui. C'est ça. Par contre, les notifications ne sont pas dans la doc :cry: . Ça va être compliqué.

**Comment by artragis** [comment]
@nils-van-zuijlen si tu as besoin de guidage pour les notifications, fais moi un signe, j'ai assez galéré en essayant de tout comprendre seul, du coup ça ferait plaisir si une autre personne savait toucher au module.
