### ISSUE TITLE
Page de recherche: Les tags de marche pas.

### ISSUE THREAD

**Issue by AmarOk1412** [zestedesavoir/zds-site#4945]
Pour reproduire:

1. Se rendre sur la page https://zestedesavoir.com/rechercher/?q=gpl&category=&subcategory=&from_library= (ou autre recherche)
2. On voit "La GPL, la licence des cornus", avec deux tags sur les cotes (zds/libre), cliquer sur l'un deux (ou autre sur la page)
3. On est redirige vers https://zestedesavoir.com/bibliotheque/ alors qu'on devrait voir la liste des contenus de ce tag pour au moins la categorie de contenu (tutoriel si c'en est un par exemple)

**Comment by artragis** [comment]
fixed on v27

**Comment by AmarOk1412** [comment]
Too fast :D
