### ISSUE TITLE
Absence de message d'erreur quand un staff tente de s'ajouter lui-même comme auteur

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#4948]
Quand un membre du staff tente de s'ajouter comme auteur du contenu d'un tiers, il se passe la chose suivante :

* le membre du staff n'est pas ajouté (fonctionnalité anti-abus),
* il n'y a pas de message d'erreur (bug).

L'absence de message d'erreur est très embêtante et la fonctionnalité anti-abus discutable. Je propose donc deux alternatives pour résoudre ce problème :

1. Rajouter un message d'erreur du type "Vous ne pouvez pas vous ajouter vous-même comme auteur en tant que staff."
2. Supprimer simplement la fonctionnalité anti-abus, et donc autoriser le staff à s'ajouter comme auteur si nécessaire.

Quelques détails en plus sont disponibles dans le [sujet du forum](https://zestedesavoir.com/forums/sujet/10586/sajouter-comme-auteur-a-un-contenu-en-tant-que-staff/) correspondant. Notamment, il semblerait que le compte admin ne soit pas non plus capable de faire ça.

**Comment by gllmc** [comment]
Je suis en faveur de la deuxième solution: je ne vois vraiment pas quel genre d'abus il pourrait y avoir.

**Comment by Arnaud-D** [comment]
Je suis aussi plutôt pour la deuxième solution. 

On dirait que tout se passe à la ligne 1758 du fichier zds/tutorialv2/views/contents.py : 

`if user.pk not in all_authors_pk and user != self.request.user:`

Pour être ajouté, un membre ne doit pas être déjà auteur (raisonnable) et ne doit pas s'ajouter lui-même. Ce dernier critère est redondant avec le premier pour les membres normaux, et empêche aussi les membres du staff de s'ajouter eux-mêmes.

Je pense que c'est quelque chose de relativement facile à corriger. Idéal pour de nouveaux contributeurs !
