### ISSUE TITLE
 Insertion du smiley >_<

### ISSUE THREAD

**Issue by GuimDev** [zestedesavoir/zds-site#4949]
On obtient `&gt;_&lt;`

Solution 1 : Modifier le code ici : https://github.com/zestedesavoir/zds-site/blob/4ae0431bbf199e318dd6f2b1301ac7b6adc40198/assets/js/editor.js#L132 Vérifier qu'il n'y a pas un bug/fail avec ">" et "<".

Solution 2 : On peut ajouter l'alias `X/` pour ce smiley et remplacer le code dans l'éditeur. https://github.com/zestedesavoir/zds-site/blob/56a5b2e8b524848efa2d328c0a46365a44c1d43e/zds/utils/templatetags/smileys_def.py#L26

**Comment by nils-van-zuijlen** [comment]
Je prends

**Comment by nils-van-zuijlen** [comment]
J'utilise la solution 2 car elle me semble plus facile à implémenter de façon fiable, et que taper `X/` est plus facile que `>_<`.

**Comment by pierre-24** [comment]
Pas fixé par #4960, comme indiqué [ici](https://github.com/zestedesavoir/zds-site/pull/4960#issuecomment-398427923) :)

**Comment by pierre-24** [comment]
[Là, par contre, c'est bon](https://zestedesavoir.com//forums/sujet/11010/doleances-sur-le-zmarkdown-de-la-v27/?page=3#p185558) :)

**Comment by nils-van-zuijlen** [comment]
Ben, pas tout à fait, le bouton insère toujours `&lt;_&gt;` en prod. Mais c'est effectivement bon sur la branche `dev`. :smiley:

**Comment by pierre-24** [comment]
Oui, mais là on peut rien y faire pour le moment ^^
