### ISSUE TITLE
Ajouter le smiley " :B " 

### ISSUE THREAD

**Issue by GuimDev** [zestedesavoir/zds-site#4950]
https://zestedesavoir.com/forums/sujet/10801/ajouter-le-smiley-b/?page=1#p181226

|    |                  Normal                   |                      HD                   |
|----|-------------------------------------------|-------------------------------------------|
| :B | ![19x27](https://i.imgur.com/wb9p8Z9.png) | ![38x54](https://i.imgur.com/lRZXqNb.png) |

**Comment by pierre-24** [comment]
Sera fermé quand la PR aura été faite côté zmarkdown :)

**Comment by pierre-24** [comment]
Euuuh ... Donc. Il-faut-d-abors-que-le-smiley-soit-releasé-avant-de-l'avoir. Donc il ne faut pas oublier d'aller faire un rappel là-bas: https://github.com/zestedesavoir/zmarkdown/pull/261 quand c'est fait :)

**Comment by artragis** [comment]
Done
