### ISSUE TITLE
Bouton de recherche non aligné pour la petite barre de recherche sur Safari

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#4956]
Bonjour,

Je viens rapporter un petit bug que j’ai remarqué sur Safari (11.1, macOS 10.13.4): le bouton de la loupe de la petite barre de recherche présente en haut du site n’est pas alignée avec le champ de recherche et le bouton de recherche détaillée. La capture d’écran montre le bug:Bug barre recherche Safari

![Bug barre recherche Safari](https://zestedesavoir.com/media/galleries/5176/4d940bbd-1e7a-4844-b1e1-d38e235a35c1.png)

Je n’ai pas remarqué le bug sur Firefox.

J’ai un peu regardé ce qui pourrait causer le bug et comment le réparer, mais j’avoue que je ne sais pas vraiment comment réparer le bug, sans casser l’affichage sur Firefox… (il faut dire que le front-end n’est pas vraiment mon point fort…)

J’aimerais bien me servir de ce bug comme occasion pour faire ma première contribution au code du site, m’initier un peu au workflow de ZdS. Donc si quelqu’un trouve la solution et qu’elle ne consiste qu’en une petite ligne à changer/ajouter dans le CSS et pouvait me la donner pour que je fasse la correction moi-même, que je fasse la pull-request et tout le process sur GitHub, ce serait très gentil 😄 
([le sujet que j'ai créé sur Zds](https://zestedesavoir.com/forums/sujet/10853/bug-bouton-de-recherche-non-aligne-pour-la-petite-barre-de-recherche-sur-safari/))

**Comment by Situphen** [comment]
Alors je n'ai pas de mac donc pas de Safari sous la main, mais d'une manière générale si tu as besoin d'aide pour contribuer n'hésites pas à me MP sur ZdS :)
