### ISSUE TITLE
[BETA] Smileys et underscore

### ISSUE THREAD

**Issue by nils-van-zuijlen** [zestedesavoir/zds-site#4958]
Le smiley >_< n'est pas converti en image sur la beta actuelle (beta de la v27).
Le bug est présent sur les forums et les commentaires des tutos.

De plus, il y a un conflit entre l'underscore présents dans ledit smiley et ceux utilisés pour l'emphase.

**Comment by artragis** [comment]
ok, faut faire une remontée sur le projet zmarkdown car c'est là que ça se règle.

**Comment by nils-van-zuijlen** [comment]
Le truc, c'est que le bug n'est pas présent dans les tutos en eux même.

**Comment by artragis** [comment]
quand tu dis "pas présent dans les tuto", c'est "pas présent dans les nouveaux tutos" ou "pas présent dans ceux déjà publiés"?

**Comment by nils-van-zuijlen** [comment]
Dans les nouveaux tutos. J'ai pas vérifié pour ceux déjà publiés.

**Comment by artragis** [comment]
Merci de la précision :)

**Comment by nils-van-zuijlen** [comment]
En fait, c'était parce que le smiley en question (`>_<`) n'était pas défini.
