### ISSUE TITLE
Erreurs serveur aléatoires

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#496]
Parfois j'ai des erreurs du serveur (impossible de savoir quoi, c'est l'erreur générique).

J'ai l'impression que ça arrive quand j'ouvre toutes mes notifications non lues chacune dans un onglet différent... ce serait alors un problème de charge / de simultanéité des actions...

Bref, ça implique d'aller jeter un œil aux logs (d'ailleurs, où sont-ils stockés ?) et sans doute de refaire un tir de charge pour voir si c'est un comportement reproductible.

**Comment by firm1** [comment]
Je n'arrive pas à reproduire.

Les logs serveurs sont dans /opt/zdsenv/logs/gunixxxx

Ou sur ce lien directement :
http://zestedesavoir.com/author-files/logguni.php

**Comment by Alex-D** [comment]
Ca m'arrive rarement, mais c'est totalement aléatoire. Ca m'est déjà arrivé en n'ouvrant qu'une seule page.

**Comment by geoffreyc** [comment]
J'ai vue ce quelques fois avec gunicorn, on dirait que ca depend sur quel
worker on tombe; si yen a 7, et qu'un "beug" (no se porque) on se retrouve
avec 1 chances sur 7 de se prendre une page d'erreur. Il faudrait relever
l'heure et la date de quand ca arrive pour voir les logs.

2014-05-12 10:06 GMT+01:00 DEMODE Alexandre notifications@github.com:

**Comment by firm1** [comment]
Ah moi aussi ça m'arrive mais je pensais que c'était le proxy du boulot.

Ceci dit, de plus, je ne sais pas si c'est à cause de mumin, mais quand je
réactualise je n'ai pas les images statiques (logo, notifications, etc.),
il faut réactualiser une deuxième fois.

Peut-être diminuer le nombre de worker ?

**Comment by Eskimon** [comment]
Idem, j'ai des "Internal Server Error" qui popup, souvent quand j'ouvre plusieurs onglets pour regarder mes notifs...

**Comment by vhf** [comment]
Toutes les erreurs se ressemblent, en voici un prototype : http://paste.awesom.eu/cbHH&ln

Ça semble être un bug de context-processor, je vais jeter un oeil et je vous invite à vous pencher vous aussi là-dessus.

Je serais curieux de savoir si le fichier settings.py fournit sur ce repo diffère du settings_prod en matière de template_context_processors et middleware_classes. (Puisqu'il semble impossible de reproduire ce bug localement sur le serveur de dev de django.)

**Comment by firm1** [comment]
Aucune divergences sur le contexprocessors  et sur les middleware dans le settings_prod.py 

Je vais tenter des trucs en prod cette nuit (quand les testeurs dormiront)

**Comment by Eskimon** [comment]
J'affine mon commentaire precedent (si ca peut etre utile ?) : 
J'ai frequemment cette erreur quand j'ouvre plusieurs notifications (a grand coup de clic molette) et en general le dernier onglet est une internal server error.
Par contre, si je fais la meme chose sur des pages (genre ouvrir trois forums) j'ai jamais de probleme.
Du coup, hypothese, est-ce possible que ce soit un acces bdd qui fasse ca ? (genre quand on va faire la supression de la notif et qu'on en fait plusieurs en peu de temps)

**Comment by SpaceFox** [comment]
> Du coup, hypothese, est-ce possible que ce soit un acces bdd qui fasse ca
> ? (genre quand on va faire la supression de la notif et qu'on en fait
> plusieurs en peu de temps)

Je me demande si la fonction qui fait ça est correctement gérée avec une
transaction. Je sais que j'en avais rajouté quelques-unes, mais pas partout.

**Comment by Alex-D** [comment]
Est-ce qu'il y a un pool de connexion de possible sur Django ? Ca permettrait d'avoir des accès concurrents gérés par la BDD non ? Peut-être me trompe-je complètement...

**Comment by cgabard** [comment]
Moi j'en ai déja eu juste en ouvrant un onlet sur la page d'acceuil

EDIT d'Alex : pareil ça m'arrive souvent.

**Comment by Eskimon** [comment]
Bon je crois que j'arrive a reproduire a 100%...
Si j'ai deux notifs, j'en ouvre avec un clic-molette et l'autre avec un clic normal. Si la première (molette) est en train de charger quand j'ouvre la seconde (normal), elle va a tout les coups crasher j'ai l'impression.

**Comment by SpaceFox** [comment]
J'arrive à la reproduire à coup quasiment sûr : le bug se produit quand on
ouvre **plusieurs topics** en parallèle et qu'il y a des **notifications à
mettre à jour** sur ces topics (typiquement, clic-molette sur les topics
avec des messages non lus).

Si on clique sur la seconde alors que la première n'est pas complètement
chargée, la première tombe en erreur.

S'il n'y a pas de notification à mettre à jour, tout fonctionne.

**Comment by firm1** [comment]
Je pense bien que la clé de la résolution se trouve [ici](https://docs.djangoproject.com/fr/1.6/ref/models/querysets/) plus précisément dans ce passage : 

> Si vous n’avez qu’une ligne à mettre à jour et que vous n’avez rien à faire de spécial avec l’objet modèle, l’approche la plus efficace est d’appeler `update()`, plutôt que de charger en mémoire l’objet modèle. Par exemple, au lieu de faire cela :
> 
> ``` python
> e = Entry.objects.get(id=10)
> e.comments_on = False
> e.save()
> ```
> 
> …faites ceci :
> 
> ``` python
> Entry.objects.filter(id=10).update(comments_on=False)
> ```
> 
> L’utilisation d’`update()` permet aussi d’éviter une situation de **concurrence** où le contenu en base de données pourrait être modifié dans le court intervalle entre le chargement de l’objet et l’appel à `save()`.

**Comment by Coy0te** [comment]
Si JPA pouvait s'inspirer de Django pour la partie ORM, ça serait vraiment, vraiment bien. =)

**Comment by firm1** [comment]
> Si JPA pouvait s'inspirer de Django pour la partie ORM, ça serait vraiment, vraiment bien. =)

Lorsqu'une technologie ne te convient pas ... va vers celle qui te convient. :-°

**Comment by GerardPaligot** [comment]
Si ça peut aider :

Sur la page pour afficher les membres :

http://zestedesavoir.com/membres : Internal Server Error
http://zestedesavoir.com/membres/ : Accès à la page.

**Comment by Alex-D** [comment]
Ca doit être un problème de routage ça, j'ai le même genre de soucis sur
Sf2, ExpressJS, et consorts.

**Comment by firm1** [comment]
ll a raison notre ami Alex-D problème de patterns dans le fichier des urls.

**Comment by SpaceFox** [comment]
Dans les fichiers des URLs, j'ai aléatoirement des / obligatoires à la fin, et aléatoirement des / interdits à la fin.

Comme dans les exemples Django **toutes** les URLs se terminent par des /, je me propose d'en rajouter partout où il en manque.

**Comment by SpaceFox** [comment]
Haha, y'a des reverse URL en dur dans le code !

**Comment by SpaceFox** [comment]
Tant que je suis dans les URLs : quelqu'un sait pourquoi j'ai des choses comme :

```
/articles/off/editer?article={pk}
```

au lieu de :

```
/articles/off/{pk}/{slug}/editer/
```

comme le voudrait la théorie et tous les exemples Django ? (exemple ici https://docs.djangoproject.com/en/1.6/topics/http/urls/#including-other-urlconfs)

**Comment by Alex-D** [comment]
Heuu faudrait éviter de changer ça tout de suite, car dans les templates
les URL sont construites par concaténation quand y a des paramètres
justement.

Donc si ça doit impacter le front, j'aimerais que ça attende le merge.

**Comment by Eskimon** [comment]
Si quelqu'un se charge de faire la modif proposé par firm1 [concernant la BDD](https://github.com/Taluu/ZesteDeSavoir/issues/496#issuecomment-43211002), j'aurais perso aucun  problème a reproduire le bug, j'arrive à le faire 100% du temps (si j'ai au moins deux notifs)

**Comment by SpaceFox** [comment]
Je le reproduit aussi à 100%... mais c'est chiant à tester chez soi, parce
que le bug n'est pas reproductible avec Sqlite !

Je suis déjà sur les modifs d'URL de cette PR, je fait aussi la modif
proposée tant que j'y suis histoire d'éviter des demi-issues :)

**Comment by cgabard** [comment]
Ce lien, fournit par une notif, m'a provoqué une Internal Server Error : http://zestedesavoir.com/forums/sujet/194/liste-de-nouveaux-beta-zesteurs?page=1#p1611

J'avai beau actualiser, ça ne passais pas. C'etait systématique.

j'ai dut virer le `#p1611` pour pouvoir le consulter.

Une fois la page chargé, le liens ne provoquait plus l'erreur.

**Comment by Eskimon** [comment]
Depuis les commits au dessus de ce commentaire, l'erreur a evolue (lorsqu'on ouvre les notifs rapidement a la suite).
J'essaie de poster plus d'infos quand je reproduis...

**Comment by Alex-D** [comment]
Dites moi juste une chose : j'ai cru voir que la session était stockée en BDD, est-ce le cas en prod ?

Si oui, il faudrait changer ça, et mettre les sessions en RAM, au risque de faire écrouler le site (cf SdZ v4).

Et c'est peut-être le problème de ces erreurs 500, d'où ma question ici.

**Comment by geoffreyc** [comment]
Je vois pas trop l'avantage (a l'heure actuel) de mettre les sessions en
memcached, apart ajouter de la complexité au site (il faut installer
memchached, parametrer tout le bordel, parametrer django, etc). Ca serait a
voir pour plus tard effectivement si on rencontre un succès monstre, mais
pour l'instant personnellement je n'en voit pas l'utilité, ca tourne tres
bien sur DB a l'heure actuel.

2014-05-21 11:22 GMT+01:00 DEMODE Alexandre notifications@github.com:

**Comment by cgabard** [comment]
D'autant que d'apres les derniers tests, la db est tres peu solicité. L'exemple du SdZ ne peut pas s'appliquer a nous : eux avaient déjà un trafic journalier tres important. Le notre est proche de 0 et ne va monter que progressivement.

**Comment by firm1** [comment]
Non mais Alex-D a raison sur le fond, la session est le truc qui prend actuellement le plus de temps en arrivant sur la home, et il faudrait le rediriger dans memcached.

Mias ça a déjà été dit dans l'issue concernant l'optimisation si je me souviens bien.

**Comment by vhf** [comment]
@geoffreyc faut pas exagérer non plus, memcached s'installe et se configure en maximum 5 minutes, et n'ajoute vraiment pas grand chose comme complexité au projet.

**Comment by Eskimon** [comment]
Pour revenir au sujet, voila l'erreur obtenue lorsque j'ouvre plusieurs notifs rapidement...
https://dl.dropboxusercontent.com/u/18967337/AttributeError%20at%20_forums_sujet_200_filtrer-par-meilleurs-likes_.html

**Comment by firm1** [comment]
Ouaip, comme je l'ai dit, je ne sais plus ou, dans le template, l'attribut `author` de `first_unread.author` n'est pas chargé. Je ne sais pas pourquoi car le `first_unread` provient de cette [fonction](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/forum/models.py#L208) qui ne renvoi forcément un post et son auteur (puisque select_related())

**Comment by firm1** [comment]
Et pour info, memcached est déjà installé sur le serveur, et il me suffit de trifouiller le settings_prod pour passer en cache les sessions.

**Comment by geoffreyc** [comment]
Si on fou les sessions dans memcached, ducoup il faudra plutot partir sur
le "django.contrib.sessions.backends.cached_db" qui ecrit les sessions dans
la DB et memcached en parallèle, pour éviter les problèmes de "persistance"
(je sais pas si ca se dit en francais?) de sessions quand memcached se
purge ou est redémarrer.

**Comment by Coy0te** [comment]
C'est un point de vue discutable, dans le sens où : 
- memcached ne plante pas/n'est pas redémarré tous les 4 matins ;
- on n'a pas vraiment d'infos à maintenir coûte que coûte en session.

Maintenant, si on tient à être aussi robuste qu'un site marchand, on peut utiliser un système de ce style : 
- lecture de la session depuis memcached. Si et seulement si échec, alors lecture depuis MySQL.
- écriture de la session dans memcached à chaque maj.
- écriture dans MySQL si et seulement si les données en cache n'ont pas été synchro depuis plus de 2 ou 3 minutes.
- mettre en crontab (ou trigger, ou autre équivalent) un script qui liste les sessions expirées dans MySQL. Pour chaque session retournée, vérifier dans memcached si elle est belle et bien expirée : si oui la supprimer, sinon la mettre à jour.

**Comment by Alex-D** [comment]
Continuons la discussion sur une issue dédiée, ça sera plus clair :)

Là : #576

**Comment by firm1** [comment]
C'est bon c'est fixé.

Merci a tous pour la participation

**Comment by SpaceFox** [comment]
On sait quel était le problème du coup ?

**Comment by firm1** [comment]
C'était un problème de concurrence de thread dans les templates. Du coup
j'ai canalisé les opérations bd en amont dans un filtre unique.

2014-05-24 13:28 GMT+02:00 SpaceFox notifications@github.com:

**Comment by SpaceFox** [comment]
OK. Ca semble être une meilleure idée, en effet.

En tous cas GG pour la correction !
