### ISSUE TITLE
Remise à zéro intempestive des abonnements à un forum

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#4961]
[Yoda a réussi à reproduire le bug](https://zestedesavoir.com/forums/sujet/10881/topic-de-test/) :

> Pour refaire le bug :
> 
> 1. créer un topic dans un forum A
> 2. masquez le premier message de votre topic
> 3. désincrivez-vous
> 
> le nombre d'abonné au forum et à votre topic tombe à zéro

> c'est plutôt la désinscription je pense.
> 
> Pour le forum sciences, je n'ai pas masqué mon premier sujet, la désinscription a suffit

**Comment by artragis** [comment]
Il se peut qu'en jouant avec les modèles pour la migration à django 2.1 (#5157 ) j'aie fixé le bug.

**Comment by artragis** [comment]
Partiellement en fait : on n'est plus désabonné des forums mais on l'est du sujet.

**Comment by Migwel** [comment]
Est-ce que ça se produit toujours? J'ai tenté de reproduire ça localement, sans succès

**Comment by artragis** [comment]
il se peut que les modifications dans les notifs pour la v30 ont en effet résolu des soucis, si tu ne reproduis plus, je vais fermer.
