### ISSUE TITLE
Plus d'accès à des parties d'un tutoriel en édition

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#4966]
Beau travail pour la v27 ... Mais j'ai trouvé un bug plutôt étrange, et non présent sur la bêta: les liens vers les parties en édition d'un tutoriel se voient agrémentées d'un `?version={%27url%27:%20%27https://github.com/zestedesavoir/zds-site/tree/63b85778549c6b0670f389b49f47388661f4cb83%27,%20%27name%27:%20%27v27-klaxon/63b8577%27}`. Voilà qui est ... Handicapant (il suffit de l'enlever pour retrouver son tuto, mais le *versionning* est un peu cassé, parce qu'on ne peut pas éditer, on renvois toujours vers la version "brouillon").

Bref, c'est un peu l'horreur, et ça le fait sur tout mes moyens/bigs tutos :o

Sujet : https://zestedesavoir.com/forums/sujet/10980/plus-dacces-a-des-parties-dun-tutoriel-en-edition/
*Envoyé depuis Zeste de Savoir*

**Comment by artragis** [comment]
une bonne nouvelle : le fix existe déjà

une mauvaise nouvelle : il n'est pas en prod car @sandhose  s'est trompé de sha1 au moment de tagger

**Comment by pierre-24** [comment]
Ah, ok :)
