### ISSUE TITLE
Les parties "a ne pas valider" sont affiche dans la beta

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#4969]
Pour une raison que j’ignore, il semblerait que les parties marquées comme « à ne pas valider » soient affichées dans la Beta. Est-ce normal ?

https://zestedesavoir.com/contenus/beta/947/utiliser-python-dans-autodesk-maya/

Ne serait-il pas plus pertinent de n’afficher en beta uniquement les parties marque comme « à valider ».

Sujet : https://zestedesavoir.com/forums/sujet/10998/les-parties-a-ne-pas-valider-sont-affiche-dans-la-beta/
*Envoyé depuis Zeste de Savoir*

**Comment by Karnaj** [comment]
@pierre24 a donné une solution possible. Dans le template, si `is_beta` on n'affiche les parties et les chapitres que si `can_edit` (et peut-être `is_staff` ?). À faire aussi dans le sommaire.

**Comment by artragis** [comment]
non, cette proposition doit vraiment être soumise à débat. Pour l'instant il vaut mieux la laisser de côté.

**Comment by artragis** [comment]
voir la PR de @Karnaj #4999

**Comment by artragis** [comment]
Voir #4968
