### ISSUE TITLE
Failles CSRF !

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#497]
Il y a un bonne pelleté de failles CSRF que je n'ai pas signalé jusque là, car ça implique des changements côté intégration.

Ce qui m'arrangerais grandement, c'est que ces corrections soient faites sur la branche d'intégration. En effet, merger les templates est impossible à l'heure actuelle entre la branche release et la branche integration.
## Forums, topic quelconque
- Marquer comme résolu
- Suivre ce sujet
- Verrouiller le sujet
- Marquer en Post-It
- Ne plus suivre ce sujet (dans la liste des sujets suivis)
- [NEW] +1/-1 en POST uniquement JS ou pas
## Tutoriels
- Dépublier (page d'un tuto/validation)
- Réserver (historique)
- Activer la beta (version offline)
- Supprimer ce tutoriel (version offline)

Peut-être y en a-t-il d'autres, mais déjà celles-là, ça sera pas mal.

Côté front, l'idéal est d'utiliser des buttons, si besoin d'infos sur certains éléments non-documentés (je pense aux modales) : ne pas hésiter à me demander.

**Comment by SpaceFox** [comment]
La correction est on ne peut plus simple : toutes ces actions doivent être
en POST et utiliser la protection anti-CSRF de Django. Ce qui implique :
1. L'action doit être marquée en POST only dans le code python (y'a un
   décorateur pour ça)
2. L'action doit être faite via un formulaire et pas via un simple lien. Cf
   par exemple la déconnexion.
3. Le formulaire doit contenir le jeton anti-CSRF. Y'a un tag pour ça.

Pour le reste, tout est dans la doc officielle, c'est l'affaire de 10
minutes par fonctionnalité (5 pour mettre en place, 5 pour tester).

**Comment by SpaceFox** [comment]
PS : si quelqu'un se pose la question : non, il n'est pas possible de
protéger un appel avec GET contre les CSRF.

Parce que c'est contraire à la logique du net : un appel GET doit pouvoir
être fait plusieurs fois de suites sans effets de bord. En gros, un appel
GET, c'est une lecture, point barrre.

**Comment by Alex-D** [comment]
Si on voulait faire parfait, ce genre d'opération devrait être fait en PUT selon HTTP.
Je ne sais pas si c'est envisageable.

**Comment by geoffreyc** [comment]
Au dernières nouvelles les navigateurs/HTML ne supportent rien d'autre que
get/post ?

**Comment by Alex-D** [comment]
Je ne sais trop dire, moi je fais tout ça en JavaScript asynchrone généralement. Sinon, pas de soucis, go faire du POST.

**Comment by geoffreyc** [comment]
[hs]Sans fallback pour les navigateurs sans JS?[/hs]

**Comment by Alex-D** [comment]
[HS] Je code des applications web complexes. Les fallback JS ne sont plus une norme actuellement, c'est même déconseillé de le désactiver. Je suis dans une entreprise d'accessibilité, et les sourds/mal voyants activent le JavaScript. [/HS]

**Comment by geoffreyc** [comment]
Fair enough! c'est bon a savoir.

2014-05-12 13:46 GMT+01:00 DEMODE Alexandre notifications@github.com:

**Comment by Alex-D** [comment]
Par contre, les navigos qui ne gèrent pas le JS du coup en effet c'est un peu chiant...
Toujours est-il qu'en effet, il faut utiliser POST du coup, et je suis déçu de ne pas avoir de GET/POST/PUT/DELETE ^^

**Comment by Alex-D** [comment]
Je viens de rajouter les +1/-1 à faire en POST également avec jetton et tout :)

**Comment by SpaceFox** [comment]
Je passe cette issue sur la Milestone 1.0, parce qu'il y a du taff back à faire pour chacune des URLs concernées.

**Comment by SpaceFox** [comment]
Y'aura aussi un certain nombre de `if request.method != "POST":` à remplacer par des `@require_POST`.

(PS : ceux où il n'y a pas de `else` bien évidemment !)

**Comment by ArnaudCalmettes** [comment]
Je passe en bloquant bêta publique.

Appel à volontaires, on a une issue prioritaire. :)

**Comment by SpaceFox** [comment]
Je prends.

**Comment by SpaceFox** [comment]
**Attention !**

La correction de ces failles va nécessiter de refaire du design _au mimimum_ sur tous les éléments suivants :
- Forum
  - Marquer comme résolu / non résolu
  - Suivre / ne plus suivre 
  - Être notifié / ne plus être notifié par mail
  - Fermer / rouvrir
  - Post-it / dé-post-it
  - Déplacer
- Posts
  - Masquer
  - Démasquer
  - Signaler
  - Message utile
  - +1/-1
- Forums
  - Dépublier (page d'un tuto/validation)
  - Réserver (historique)
  - Activer la beta (version offline)
  - Supprimer ce tutoriel (version offline)

Pourquoi ? Parce que toutes ces actions sont gérées avec des liens, donc des actions HTTP GET, et que la protection anti-CSRF ne fonctionne que sur des actions POST.

Ce que je ne comprends pas, c'est pourquoi toutes ces actions ont été implémentées de cette manière alors que l'on sait depuis le 1er mai et l'issue #383 que ce genre d'action doit être implémenté via des formulaires.

À moins que quelqu'un n'ait une combine pour faire cracher du POST à un lien `<a href=""` de manière facile, accessible et compatible avec le système anti-CSRF de Django.

**Comment by Alex-D** [comment]
Ca n'est pas un problème de devoir refaire le front. Sur les articles c'est déjà fonctionnel avec des forms et des boutons :)

Je peux aider celui qui voudra bien le faire (car pour le back perso je ne toucherais à rien, trop peur de tout péter).

**Comment by SpaceFox** [comment]
> Sur les articles c'est déjà fonctionnel avec des forms et des boutons :)

@Alex-D , de quelles fonctionnalités parles-tu ici ? Sur quelle page ?
Que ce soit sur la page de visualisation des articles ou sur la page de rédaction, je ne vois que des liens, pas des forms.

**Comment by Alex-D** [comment]
https://github.com/zestedesavoir/zds-site/blob/beta-0.2/templates/article/includes/sidebar_actions.part.html

Ici par exemple, c'est un bout de la sidebar. Il y a bien des liens, mais si tu regardes bien c'est un simple lien vers une ancre, l'ancre étant la boite modale qui elle est bien un form :)

Et je crois que j'ai prévu le cas design des form > button dans la sidebar (ne pas utiliser input type="submit" c'est non-sémantique, un input est une zone d'entrée de donnée, un bouton c'est... un bouton :D )

**Comment by firm1** [comment]
> Ce que je ne comprends pas, c'est pourquoi toutes ces actions ont été implémentées de cette manière alors que l'on sait depuis le 1er mai et l'issue #383 que ce genre d'action doit être implémenté via des formulaires.

Il aurait été plus efficace de mettre les formulaires avec une `action='get'` qu'on remplacerait juste par `action='post'` après. m'enfin, il est trop tard et visiblement ça va couter cher en temps.

@Alex-D as tu prévu le cas de mettre des form directement dans la sidebar ? au niveau des +1/-1 ? ce sont des actions qui doivent être réalisés en un coup sans passer par une boite modale.
Si tu as prévu le cas, peux-tu montrer un fichier d'exemple ? sinon (vu qu'on a pas encore de doc sur l'utilisation de ton design), il va falloir que tu repasses sur tout les templates et que tu remplace tous les liens de type `<a href="#"></a>` par `<form method='get' action="#"><button>ok</button></form>`

**Comment by Alex-D** [comment]
Autant dans la sidebar comme dit dans le précédant message, c'est prévu.

Autant les +1/-1 ça va être chiant en effet. L'AJAX est prêt lui (simple "GET" à changer en "POST").

A la limite, ce soir je repasse sur toutes les templates, je change tout en form GET, comme ça celui qui patchera le back n'aura qu'à changer comme tu le suggères (GET -> POST). 

Ca vous va comme ça ?

**Comment by firm1** [comment]
> A la limite, ce soir je repasse sur toutes les templates, je change tout en form GET, comme ça celui qui patchera le back n'aura qu'à changer comme tu le suggères (GET -> POST). 

C'est clairement un préréquis à la résolution de cette issue bloquante.

**Comment by Alex-D** [comment]
Okdac je fais ça dès que possible : peut-être dans la journée, peut-être ce soir. Vous verrez de toutes façon une PR arriver.

**Comment by geoffreyc** [comment]
> > (ne pas utiliser input type="submit" c'est non-sémantique, un input est
> > une zone d'entrée de donnée, un bouton c'est... un bouton :D )

L’intérêt du input type="submit" c'est quand même de de passer une valeur
au submit, je vois pas en quoi c'est "non-sémantique" ...

2014-06-16 8:42 GMT+01:00 Alexandre Demode notifications@github.com:

**Comment by Alex-D** [comment]
> c'est quand même de de passer une valeur au submit

Avec name et value ? Sachant Value est le nom d'affichage, ça fiche tout en l'air dès que tu veux changer le visuel or ça doit être indépendant du fonctionnement. C'est là que button est beaucoup mieux.

Or, le button peut aussi accueillir name et value, tout en aillant une valeur d'affichage séparée : https://developer.mozilla.org/fr/docs/Web/HTML/Element/Button

C'est pas sémantique au sens où un input, c'est une entrée pour l'utilisateur (un truc il peut écrire, check ou autre). Un button, c'est un bouton, c'est fait pour.

L'input submit c'est un vestige des premières version du HTML qui persiste malheureusement pour des raisons de rétrocompatibilité (ce qui est compréhensible).

**Comment by geoffreyc** [comment]
Donc d’après tes dires, l'input type="hidden" c'est pas sémantique non
plus? Ta définition d'une input m'a l'air très subjective ...

2014-06-16 9:13 GMT+01:00 Alexandre Demode notifications@github.com:

> button, c'est un bouton, c'est fait pour.

**Comment by sandhose** [comment]
La seule raison qui pourrait justifier l'utilisation d'`<input type="button" />`, au lieu de `<button>`, c'est... IE6. `<button>` a l'avantage de pouvoir inclure autre chose que du texte (une icone/image, par exemple), et d'avoir une value différente de ce qui est affiché. Je pense donc que la question ne se pose même pas, on utilise des `<button>` plutôt que des `<input type="button" />`. :blush:

**Comment by geoffreyc** [comment]
La n'est point la question, je suis tout a fait d'accord sur le fait
d'utiliser button vs input, je interrogée seulement sur la définition de
"non-sémantique" d'alex.

2014-06-16 9:35 GMT+01:00 Sandhose notifications@github.com:

**Comment by Alex-D** [comment]
Non sémantique != non valide, je pense qu'on est d'accords mais c'pour être sûr.

button apporte plus de sens que input, c'est logique et constatable : son nom indique que c'est un bouton tandis qu'on a pas cette information sur input type button/submit/reset/... donc on a davantage de sémantique :)

**Comment by SpaceFox** [comment]
Un impondérable m'empeche d'avancer sur ZdS avant vendredi soir. Je laisse donc ce ticket à qui veut.

**Comment by SpaceFox** [comment]
Bon, cette issue est plus compliquée à corriger que prévu, notamment parce que :
- La PR #965 n'est pas complète, il reste toujours au moins le lien sur le tableau de validation des tutoriels. À ce propos, un rappel : la protection CSRF ne fonctionne **que** sur du `POST`, ce qui implique que **tous** les appels à la page sont à faire en `POST` (et donc via un formulaire / en AJAX).
- La PR #966 ne gère pas les +1/-1
- Les systèmes de validation des tutos et des articles n'étant visiblement pas factorisés, il n'y a strictement rien de fait sur les articles

Du coup, la date de livraison prévue passe de "avant la soirée" à "ce soir tard au mieux, sinon ça risque de traîner jusqu'à lundi"

**Comment by SpaceFox** [comment]
J'ajoute que comme il n'y a aucune documentation, ce n'est pas facile de retrouver le lien entre le front et le back. 
Ce n'est pas un reproche mais un argument dans le sens de la création de cette documentation.

**Comment by Alex-D** [comment]
HS : ne pas citer l'issue dans les commits serait pas mal... c'est déjà dans une PR qui cible l'issue, je trouve ça suffisant. Là ça "flood" pas mal.

Je m'occupe de fix le karma mardi au plus tard.

**Comment by SpaceFox** [comment]
J'étais persuadé que ça faisait partie des pratiques recommandées ici : https://github.com/zestedesavoir/zds-site/blob/beta-0.2/CONTRIBUTING.md

Du coup j'ai vérifié, mais en fait non.

Par contre, on a dans ce fichier une ligne qui dit que les commits doivent être en anglais, et une autre qui dit que les commits doivent être en français...

**Comment by Alex-D** [comment]
Normalement c'est l'un ou l'autre avec une forte préférence pour le français (ça avait été longuement débattu)

**Comment by Ge0** [comment]
Hello,

Je sais pas si la correction des failles CSRF est responsable du dysfonctionnement des +1/-1, mais en tout cas ils ne fonctionnent plus. Dois-je créer une nouvelle issue ?

**Comment by SpaceFox** [comment]
Non c'est normal pour le moment

**Comment by Ge0** [comment]
Ok :)

**Comment by Eskimon** [comment]
Hop, PR mergé (https://github.com/zestedesavoir/zds-site/pull/1017) = issue fermé !! Bravo tout le monde, uen bonne chose de faite !
