### ISSUE TITLE
Le nombre de membres est absent

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#4970]
Bonjour,

Sur [cette page](https://zestedesavoir.com/membres/), le nombre de membre est absent chez moi (cf. image ci-dessous).

![Nombre de membres](https://zestedesavoir.com/media/galleries/5254/864502af-abda-416e-94ce-e128d0967d35.png)
Figure:Nombre de membres

C'est aussi le cas chez vous ou c'est juste moi ?

Sujet : https://zestedesavoir.com/forums/sujet/10999/le-nombre-de-membres-est-absent/
*Envoyé depuis Zeste de Savoir*

**Comment by nils-van-zuijlen** [comment]
N'essayez pas de savoir si ça vient du `paginator`, c'est le `blocktrans` qui fait foirer ça.
https://docs.djangoproject.com/en/1.10/topics/i18n/translation/#blocktrans-template-tag

**Comment by nils-van-zuijlen** [comment]
Et c'est [ce commit](https://github.com/zestedesavoir/zds-site/commit/6ac0018c98ae4253b97830fcc142fe5b98278229#diff-8df490c723e6542b06eabdd9c6e4f634) qui a introduit le problème.

Il faut quand même garder le `blocktrans`, c'est plus joli.

**Comment by rezemika** [comment]
Du coup il faudrait faire `{% blocktrans with paginator=paginator %}` (ou {% blocktrans with member_count=paginator.count %}`) si j'ai bien compris ?

**Comment by pierre-24** [comment]
Oui :)

**Comment by rezemika** [comment]
M'ok, je veux bien faire la PR (à moins qu'elle soit déjà prête ?). :)

**Comment by pierre-24** [comment]
Fait donc ;)

**Comment by rezemika** [comment]
Ça marche : #5000. Cinq mille ! \o/
