### ISSUE TITLE
Notification persistante lors de changements de droits/groupe sur le forum

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#4971]
Version : v27.1 (prod)

Reproduire : 

- Se connecter avec un compte A disposant de droits sur un forum privé (sur la prod, cela correspondait au forum du CA)
- Activer les notifications sur ce forum
- Avec un autre compte B créer un sujet sur ce forum
- Retirer l'accès du compte A au forum
- Constater la présence d'une notification persistente (erreur 403)

Informations de debug (sur la prod) : 

- Utilisateur : gustavi
- Sujet du forum en question : id = 10816 (Mardi 05 juin 2018)

Je ne la marque pas comme lue pour le moment si jamais vous avez besoin de vérifier des trucs en prod.

Comme ça je dirai qu'il y a peut-être un problème d'ordre de mixins mais j'ai pas regardé le code pour vérifier.

PS : désolé si c'est un doublon.

**Comment by artragis** [comment]
c'est étrange, ce bug est sensé être fixé.

**Comment by nils-van-zuijlen** [comment]
Peut-être en rapport avec #4972

**Comment by Situphen** [comment]
Je viens de vérifier en local sur `upstream/dev` et que ce soit pour l'abonnement au forum ou l'abonnement à un sujet, les notifications sont bien supprimées quand on est retiré du groupe qui a accès au forum, pas de notification persistante ! Je ferme donc le ticket.
