### ISSUE TITLE
Ping et e-mails

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#4974]
Reporté [là](https://zestedesavoir.com/forums/sujet/10673/la-v27-est-en-beta/?page=7#p184051) :

> Quand je tape une addresse gmail, par exemple `example@gmail.com`, ça pingue automatiquement un compte "gmail" inexistant.

Du côté de zmarkdown (https://github.com/zestedesavoir/zmarkdown/issues/243), il m'a été indiqué qu'il suffisait d'un changement de configuration (mais ne connaissant pas bien le module, je ne sais pas ou agir).

**Comment by artragis** [comment]
la conf est dans le projet zmd (packages/zmarkdown/config)

**Comment by pierre-24** [comment]
Certes. J'ai donc rien compris.
