### ISSUE TITLE
Centrer les smileys dans l'éditeur

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#4978]
Proposition pour centrer les smileys dans l'éditeur, ça rendrait bien mieux.

C'est une première issue assez simple, il suffit de centrer `.zform-subbutton-span-smiley`.

Le comportement est juste à vérifier sur plusieurs navigateurs.

![zds-editor-smiley-centered](https://user-images.githubusercontent.com/2736557/42938880-125288a8-8b54-11e8-849d-459927f20012.png)

**Comment by A-312** [comment]
Je prends :)
