### ISSUE TITLE
Bouton "précédent" sur les articles et billets

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#4979]
Coucou,

Avec la v27 sont apparus les boutons précédent et suivant sur les billets et articles. Cependant, le bouton précédent, au lieu d'amener à l'article précédent de l'auteur, amène à son tout premier article.

Par ailleurs, est-ce qu'il vaut mieux pointer vers la précédente publication de l'auteur, ou plutôt vers la précédente publication dans l'ordre chronologique ? Je ne sais pas ce qui vaut le mieux, mais j'ai été surpris de constater que c'était par auteur plutôt que par date.

Sujet : https://zestedesavoir.com/forums/sujet/11030/bouton-precedent-sur-les-articles-et-billets/
*Envoyé depuis Zeste de Savoir*

**Comment by Karnaj** [comment]
Salut,

Finalement il faut faire quoi pour corriger ce bug, faire le bouton précédent ramener au billet précédent de l'auteur, ou au billet précédent tout court ?

**Comment by artragis** [comment]
précédent tout court serait mieux.
