### ISSUE TITLE
[Tutoriel] La dévalidation ne fonctionne pas

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#498]
J'ai tenté de dévalider le tutoriel suivant, qui était validé et en ligne : 
http://zestedesavoir.com/tutoriels/6/presentez-des-diaporamas-avec-powerpoint/

Actuellement, je n'y ai pas accès avec une erreur interne (500 j'imagine). Pourtant sur la liste des tutoriels, il existe :
http://zestedesavoir.com/tutoriels/

Il y a ici plusieurs choses :
- d'une part, la page devrait renvoyer une 404
- d'autre part, le tuto ne devrait plus être listé

**Comment by firm1** [comment]
Ce tuto a planté à la publication (d'où la valeur de sa date de publication
à None). Le bug a déjà été corrigé depuis, et le tutoriel doit être
supprimé manuellement.

**Comment by Alex-D** [comment]
En effet, sur les autres ça fonctionne. Je ferme du coup.
