### ISSUE TITLE
Un auteur n'est plus abonné à son contenu s'il publie

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#4982]
Comme le titre l'indique, la publication d'un contenu par un membre de l'équipe ou d'un billet par l'auteur n’entraîne plus l’abonnement à celui-ci, et donc les notifications ne sont pas générées.

Sujet : https://zestedesavoir.com/forums/sujet/11038/je-ne-suis-pas-abonne-a-mon-propre-billet/
*Envoyé depuis Zeste de Savoir*

**Comment by artragis** [comment]
https://sentry.sandhose.fr/zeste-de-savoir/zds-site/issues/19/

**Comment by artragis** [comment]
bon en fait c'est l'unfollow qui ne marche plus bien.

**Comment by pierre-24** [comment]
Donc ici c'est bon ;)
