### ISSUE TITLE
Impossible de ne plus suivre un billet

### ISSUE THREAD

**Issue by rezemika** [zestedesavoir/zds-site#4984]
Je me suis abonné au billet [Ô Belgique, ô ... ](https://zestedesavoir.com/billets/2681/o-belgique-o/) peu après sa publication. Or, il m'est désormais impossible de ne plus le suivre. De même, j'ai cliqué sur "Être notifié par courriel", et il m'est impossible de l'annuler. Quand je clique sur les boutons correspondants dans la sidebar, rien ne se passe.

La même chose se passe sur le billet [Notification des failles de sécurité et droit pénal](https://zestedesavoir.com/billets/2568/notification-des-failles-de-securite-et-droit-penal/).

**Comment by A-312** [comment]
( O Belgique O a été republié ref : https://zestedesavoir.com/forums/sujet/11038/je-ne-suis-pas-abonne-a-mon-propre-billet/ )

**Comment by pierre-24** [comment]
Ça crée un bug de faire ça ? (si oui, désolé). 

Par ailleurs, tu t'es abonné le vendredi ou le samedi?

**Comment by artragis** [comment]
https://sentry.sandhose.fr/zeste-de-savoir/zds-site/issues/54/

**Comment by rezemika** [comment]
> Par ailleurs, tu t'es abonné le vendredi ou le samedi?

Hum, désolé, je ne sais plus vraiment...

Merci pour le fix @artragis !
