### ISSUE TITLE
Absence de miniature et de description sur TwitterCard

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#4986]
L'absence de miniature et de description se répercute sur la TwitterCard ce qui est assez bloquant qui a envie de cliquer sur lien gris ?

 - https://twitter.com/A312_zds/status/1022017785373904896
 - https://twitter.com/A312_zds/status/1014195933762945033

HTML attendu :  

    <meta property="twitter:image" content="http://zestedesavoir.com/static/images/favicons/512.c00dbe2ae399.png">

ainsi que : `
     <meta property="twitter:description" content="Zeste de Savoir est un site de partage de connaissances sur lequel vous trouverez des tutoriels de tous niveaux, des articles et des forums d’entraide animés par et pour la communauté.">`

HTML actuel : 

     <meta property="twitter:image" content="http://zestedesavoir.com/">

----------

Voir pourquoi ces lignes ne s'appliquent pas : https://github.com/zestedesavoir/zds-site/blob/5fa0a838cf5d5d718173c7f34d423e4136561f69/templates/base.html#L53-L57

**Comment by artragis** [comment]
je ne comprends pas ton "voilà pourquoi". TU peux être plus clair?

**Comment by A-312** [comment]
J'ai dis bien dis/écris "voir", je ne connais pas la raison. J'ai cherché sur la documentation pour comprendre ce moteur de template, j'ai essayé de chercher dans le controller mais je n'ai pas trouvé la raison.

Je ne connais pas le déroulement du code donc je ne peux pas plus aider.
