### ISSUE TITLE
[Articles] Ajouter la possibilité d'avoir un message lors du refus d'article

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#499]
Lorsque l'on refuse un article, c'est assez brutal actuellement.

Est-ce qu'un champ est déjà prévu pour accueillir un message de refus à la manière des tutoriels ? Si non, je pense qu'il serait assez intéressant de le faire, via une boite modale.

**Comment by SpaceFox** [comment]
Corrigé et mergé.
