### ISSUE TITLE
Blocs [[secret]] : remplacer le texte de la barre d'affichage par le titre quand il y en a

### ISSUE THREAD

**Issue by Ymox** [zestedesavoir/zds-site#4991]
J'aimerais proposer quelque chose, si c'est imaginable par la suite : pour les blocs, désormais on peut ajouter des titres. Est-ce qu'on pourrait faire en sorte que le texte par défaut de la barre "afficher/masquer" des blocs `[[secret]]` soit remplacé par le titre quand il y en a un ? Quitte à ajouter une "pointe de flèche" avec l’œil (ou remplacer ce dernier) pour indiquer que c'est un objet avec lequel on peut interagir.

Parce que pour ma part, mettre un titre à un bloc `[[secret]]` et que ce titre soit aussi secret, je ne vois pas trop l'utilité.

Message : https://zestedesavoir.com/forums/sujet/11010/doleances-sur-le-zmarkdown-de-la-v27/?page=3#p185242
_Repris depuis Zeste de Savoir_

**Comment by vhf** [comment]
Il faut surtout décider si on veut passer à [\<details>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details), [côté markdown](https://github.com/zestedesavoir/zmarkdown/tree/master/packages/remark-custom-blocks#usage-configuration-syntax).

Exemple : 

```md
<details><summary>mon titre</summary>
truc caché
</details>
<details>autre truc caché</details>
```

Résultat : 

<details><summary>mon titre</summary>
truc caché
</details>
<details>autre truc caché</details>
