### ISSUE TITLE
zmarkdown et zds

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#4992]
J'ai raté un truc ou il n'y a pas de doc associée à l'installation de zmd ? (j'ai trouvé `make zmd-install` par hasard, en fait)

**Comment by artragis** [comment]
ping @vhf

**Comment by vhf** [comment]
Merci pour le ping, je ne suis plus ce repo j'avais pas vu.

1. Je ne sais pas, c'est possible.
2. Si tu clones zmarkdown, tu es sur master, c'est pas pareil que la version installée ici, c'est pour ça. Je vais faire une PR pour mettre à jour.

**Comment by pierre-24** [comment]
Parfait ! 

Par contre, faut mettre la template ou pour que ça fonctionne, en fait ?

**Comment by vhf** [comment]
Si tu parles du template latex, il est ici : https://github.com/zestedesavoir/zmarkdown/blob/master/packages/zmarkdown/templates/latex-document.js#L31-L46

Si tu parles de la feuille de style, j'ai aucune idée.

Il y a des trucs là mais je pense que ça devrait être supprimé : https://github.com/zestedesavoir/zds-site/tree/dev/assets/tex

**Comment by Karnaj** [comment]
@vhf @pierre-24 Il faudrait aussi mettre à jour la doc d'installation du front pour indiquer la commande à utiliser, non ?

**Comment by vhf** [comment]
Volontiers @Karnaj, mais la doc du back, pas celle du front !

**Comment by Karnaj** [comment]
Indeed... J'ai pensé back, j'ai écrit front. ^^

**Comment by pierre-24** [comment]
> @vhf @pierre-24 Il faudrait aussi mettre à jour la doc d'installation du front pour indiquer la commande à utiliser, non ?

C'est pour ça que je faisais la remarque ;)

Par contre, me faut l'aide de @artragis, parce que comme je disais, je n'ai aucune idée doù ce met la template LaTeX et de comment l'installer convenablement :)

**Comment by artragis** [comment]
bah il faut mettre le template là où vous autres de l'équipe latex-template avez dit de le mettre.

**Comment by pierre-24** [comment]
aaah, dans `$TEXMF`. Bon, je vais me réattaquer à la doc, moi :p

**Comment by Situphen** [comment]
@artragis c'est déjà le cas avec https://docs.zestedesavoir.com/install/extra-zmd.html non ?
