### ISSUE TITLE
Mettre à jour un article/tuto en ligne sans le remonter dans la liste

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#500]
nohar :

Pour la validation d'un article, ce serait bien d'avoir un moyen de pouvoir mettre à jour la version en ligne sans que celui-ci ne soit remonté dans la liste, de façon à ce qu'une modification mineure (correction de typos, par exemple) ne casse pas la chronologie des articles.

Accessoirement ce serait bien d'avoir la même chose pour les tutoriels.

Sur le SdZ, ça prenait la forme d'une checkbox "modification mineure", dont le comportement était de ne pas remonter le tuto dans la liste des derniers tutos publiés, et de ne pas envoyer de MP d'acceptation à l'auteur.

**Comment by SpaceFox** [comment]
Et on félicite ShigeruM qui vient d'ouvrir la 500ème issue !

**Comment by cgabard** [comment]
:beers:

**Comment by GerardPaligot** [comment]
Je rêve où, en plus d'avoir ouvert la 500ème issue, notre @ShigeruM s'occupe aussi de la tâche ? En tout cas, elle lui est assignée et elle est en cours. ^^

**Comment by ShigeruM** [comment]
Je m'en occupe mais j'en chie. Je crois que si je ne trouve pas la
solution, je laisserai la main à quelqu'un qui connait mieux Django...

**Comment by GerardPaligot** [comment]
Oooh ... \* popcorn *

Non, non, on te regarde ! \o/

**Comment by Alex-D** [comment]
Une solution qui me vient à l'esprit serait un champ "last-major-update" qui ne serait mis à jour que quand la case serait cochée, et on trierait dessus pour l'affichage.

**Comment by ShigeruM** [comment]
Non j'ai trouvé autre chose, je m'en occupe demain.
Le 20 mai 2014 00:06, "DEMODE Alexandre" notifications@github.com a écrit
:

**Comment by Alex-D** [comment]
Oh ! Parfait alors :)

Est-ce que du coup tu as l'ancienne version du repo ou la nouvelle toute cassée depuis le nettoyage de @firm1 ?

**Comment by firm1** [comment]
Concernant cette issue, pour information. Actuellement les tutos sur la page d’accueil sont triés par date. Si on part du principe que chaque modification mineure ne doit pas faire remonter un tuto, pour moi ça signifie qu'une modification mineure n'est pas considérée comme "ayant le pouvoir de dire qu'un tuto a été MAJ".

Ce qui revient donc à dire que coté implémentation il faut : 
- dupliquer [ce bouton de publication d'article](https://github.com/Taluu/ZesteDeSavoir/blob/dev/templates/article/view.html#L79)
- attribuer au duplicata un attribut autre que `name="valid-article"`
- aller dans la view et dupliquer (ou factoriser) [cette condition](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/article/views.py#L483)
- le duplicata de la condition aura sensiblement le même code à l'execption de cette [ligne](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/article/views.py#L497) (mise à jour de la date e publication)

Après pour bien faire, il faudrait rajouter un tests juste [à ce niveau](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/article/tests.py#L65).

ça devrait normalement marcher et le même principe peut-être appliqué pour les tutos.

Voili, voilou, j'espère que ça orientera un peu.

**Comment by Alex-D** [comment]
Côté UI si on peut faire simple, c'est mieux. Par exemple là, je vois plutôt une checkbox dans la boite modale de confirmation de la publication qui dit si oui ou non on up l'article (cochée si jamais publiée, décochée par défaut sinon).

**Comment by SpaceFox** [comment]
> Par exemple là, je vois plutôt une checkbox dans la boite modale de
> confirmation de la publication qui dit si oui ou non on up l'article

C'est ce qu'on avait sur le SdZ (la case indiquait "modification mineure",
et ne remontait pas l'article si elle était cochée).

**Comment by ShigeruM** [comment]
Je comptais faire ça beaucoup plus simple aussi. En fait, j'avais deux
approches :

Première approche : un champ is_major dans Validation. En effet, je
considère que c'est la validation qui est mineure ou non. L'info doit donc
se trouver au niveau du modèle Validation et non Tutorial. Cela dit, je
n'arrive pas bien à requêter les "derniers tutos publiés" (méthode
get_last_tutorials()) car il faut joindre Tutorial.obects.... à Validation.

J'arrive bien à récupérer les derniers tutos qui sont liées à une
validation majeure, mais alors ça me ramène les tutos qui ont eu au moins
une validation majeure dans leur histoire...

Seconde approche : une date de publication majeure, au niveau de Tutorial
cette fois. Soit un nouveau champ "last_major_update", soit on réutilise le
champ "pubdate" qu'on ne met à jour qu'en cas de validation majeure. Pour
moi, c'est cette dernière solution la meilleure (on me l'a soufflée).

Quoi qu'il en soit, c'est au moment de la validation que le choix doit se
faire, donc dans valid_tutorial(request). A mon avis.

**Comment by ShigeruM** [comment]
Et pour le champ dans le front, je suis d'accord aussi qu'une checkbox au moment de l'acceptation du tuto est plus sympa. Pour ça, j'avais ajouté un champ dans ValidForm.

**Comment by firm1** [comment]
Bravo a Mister @ShigeruM qui a résolu la 500e issue.

Vous avez mérité une bière.
