### ISSUE TITLE
Erreur 404 après la publication de mon article

### ISSUE THREAD

**Issue by Songbird0** [zestedesavoir/zds-site#5013]
Hello,

[Mon article](https://zestedesavoir.com/articles/2728/la-version-stable-de-rust-1-28-est-desormais-disponible-2/) a été publié hier et apparaît désormais sur l'accueil du site, jusqu'ici aucun problème. Cependant lorsque je souhaite accéder à son brouillon, je remarque que le lien est mort. Le serveur me renvoie une erreur 404.

![404](https://user-images.githubusercontent.com/13397428/44373094-b4a65380-a4e7-11e8-98f2-70c4aadfd659.gif)

*Est-ce un comportement normal ? Si oui, pourquoi ?*

Merci d'avance !

**Comment by artragis** [comment]
Ce n'est pas normal. Je corrige ça ce soir ou demain sur la prod.

**Comment by Songbird0** [comment]
Entendu, merci à toi.




*Feel free to look at my github <https://github.com/Songbird0>!*
*Rust learning (up to date french resources)*
<https://github.com/ctjhoa/rust-learning/blob/master/fr_FR.md>

*Best regards.*

**Comment by artragis** [comment]
C'est reviendu.

**Comment by Songbird0** [comment]
Génial, merci !
