### ISSUE TITLE
Tous les articles du site affichent le premier article comme article précédent

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#5016]
Bonjour,

Sur tous les articles du site ([exemple](https://zestedesavoir.com/articles/223/les-arbres-phylogenetiques/)), la barre de navigation indique le [premier article du site](https://zestedesavoir.com/articles/1/bienvenue-sur-la-beta-de-zeste-de-savoir/) et pas le vrai article précédent.

Constaté à l'instant sur la prod et la bêta (v27.1), je n'ai pas encore fait de tests en local.

**Comment by firm1** [comment]
Ce bug est un doublon de #4979 et a été corrigé via la PR suivante : #4987 

Je ferme donc ici.
