### ISSUE TITLE
Bug d'affichage avec un thème noir

### ISSUE THREAD

**Issue by Urgau** [zestedesavoir/zds-site#5017]
Il faudrait forcer la couleur blanche sur la barre de recherche car elle se mets dans la couleur du thème (ici noir) et c'est pas très beau.

![screenshot_2018-08-22 zeste de savoir](https://user-images.githubusercontent.com/3616612/44456378-a26c0880-a600-11e8-8aa5-e37f88134f7f.png)

**Comment by nils-van-zuijlen** [comment]
Il faudrait d'ailleurs en profiter pour fix #2805 qui est liée.

**Comment by Arnaud-D** [comment]
Je considère que c'est redondant avec #2805 ; je ferme ici.
