### ISSUE TITLE
Message de prise en charge de contenu en validation

### ISSUE THREAD

**Issue by gllmc** [zestedesavoir/zds-site#5024]
Salut,

Même quand il y a plusieurs auteurs, le message envoyé quand un contenu est pris en validation est le suivant.

> Je viens de prendre en charge la validation de **ton** contenu

Ce serait cool d'avoir « votre » s'il y a plusieurs auteurs.

Sujet : https://zestedesavoir.com/forums/sujet/11194/message-de-prise-en-charge-de-contenu-en-validation/
*Envoyé depuis Zeste de Savoir*

**Comment by Karnaj** [comment]
Il faut donner le nombre d'auteurs en variable au `render_to_string` pour `validation_reserve.md` dans [ce fichier](https://github.com/zestedesavoir/zds-site/blob/master/zds/tutorialv2/views/validations.py). Puis, dans le fichier [`validation_reserve.md`](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/messages/validation_reserve.md), il faut utiliser ce nombre d'auteurs pour afficher « ton » ou « votre » (grâce à `pluralize` par exemple). 

`author {{ num_author|pluralize }}` placera un `s` s'il y a plusieurs auteurs. Ici, le mot pluriel est différent du mot singulier, on indique à `pluralize` les deux formes du mot entre guillemets séparés par une virgule. `{{ num_author|pluralize:"ton, votre" }}`.

**Comment by Arnaud-D** [comment]
J'ajoute aussi que le nombre d'auteurs peut être calculé avec `validation.content.authors.count()`.
