### ISSUE TITLE
Les anciennes balises SPOILER/SECRET ne fonctionnent plus

### ISSUE THREAD

**Issue by GuimDev** [zestedesavoir/zds-site#5026]
Par exemple : 

https://zestedesavoir.com/forums/sujet/835/zep-11-interface-de-statistiques-sur-les-tutoriels/?page=12

On a simplement un gros bloque ouvert.

**Comment by gllmc** [comment]
J'ai l'impression que ça ne concerne que les posts avec l'ancien zmarkdown (ce qui ne rend pas le bug moins problématique), merci du rapport !

**Comment by GuimDev** [comment]
Surement le javascript qui ne s'active pas.

**Comment by artragis** [comment]
Ce sont sûrement les classes CSS qui ne sont plus gérées.

**Comment by GuimDev** [comment]
artragis si tu regardes le html de la page, il manque la balise <a> au dessus du bloc spoiler. Je ne pense pas que le CSS soit généré en HTML donc sûrement du javascript.
```
<a class="spoiler-title ico-after view" href="#">Afficher/Masquer le contenu masqué</a>
```

**Comment by artragis** [comment]
> artragis si tu regardes le html de la page, il manque la balise au dessus du bloc spoiler. Je ne pense pas que le CSS soit généré en HTML donc sûrement du javascript.

le javascript réagit à partir d'un sélecteur du style `$('.class-du-spoiler')`. Les classes ayant changé avec zmarkdown, il se peut qu'on ait mal porté le truc.

**Comment by GuimDev** [comment]
Est-ce #4890 ? https://github.com/zestedesavoir/zds-site/pull/4890/commits/a20e9d4e4a2e5512b68cba32c2632545b02c4ef7#diff-27f15a8be564ebd970072418bfb93575R31

**Comment by Situphen** [comment]
Oups, my bad :/ J'ai bien pensé à garder l'ancien CSS mais j'ai remplacé bêtement l'ancien JS... Désolé :/

**Comment by A-312** [comment]
Ancien HTML : 
```
<div itemprop="text">
    <div class="spoiler">
        <div>
            <p>Coucou</p>
        </div>
    </div>
</div>
```
