### ISSUE TITLE
[MP] Ajouter option pour ne pas envoyer d'email lors d'une nouvelle réponse

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#503]
Relatif à [cette discussion](http://zestedesavoir.com/forums/sujet/29/suggestion-rapporte-mp-plusieurs-remarques).

Ca serait bien de rajouter une option dans le profil pour pouvoir désactiver l'envoi d'email lors de **nouvelles réponses** dans un MP (mais toujours envoyer un email si un nouvel MP arrive)

**Comment by firm1** [comment]
Fixé -> Mergé -> En prod.
