### ISSUE TITLE
Régler la confusion partie > chapitre > section

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#5030]
Bonjour,

Je suis entrain de rédiger un big-tuto et je suis perdu. Surtout quand à la création, il propose les 3 en même temps. :'( Je propose de régler le problème via la maquette ci-dessous. ~~(Dans ma tête les sections contiennent des chapitres qui contiennent des parties :lol: )~~.

![Maquette](https://i.imgur.com/lrBMiek.png)

[(Agrandir)](https://i.imgur.com/lrBMiek.png) *J'ai oublié de redimensionner mon navigateur, pour avoir un screen moins large.*

Bon vol.

Sujet : https://zestedesavoir.com/forums/sujet/11209/regler-la-confusion-partie-chapitre-section/
*Envoyé depuis Zeste de Savoir*

**Comment by A-312** [comment]
Prendre en considération : https://zestedesavoir.com/forums/sujet/11209/regler-la-confusion-partie-chapitre-section/?page=1#p187363

On peut faire ça :o ~~Je me suis donc planté dans la structure de mon bigtuto, je me disais bien que je n'étais pas obligé de faire une partie. :(~~

J'ai pensé à :

![](https://i.imgur.com/Iqz1SnU.png)

On affiche cette interface quand la partie est vide. Bien-sûr on remplace ce que j'ai copié/collé de la précédente image par :

1. Section A
2. Section B
3. Section C

Puis

1. **Premier chapitre** 
   Section A  
   Section B  
   Section C  
2. **Deuxième chapitre**
   Section A  
   Section B  
   Section C

**Comment by A-312** [comment]
@Situphen On souhaite quel padding ?

![image](https://user-images.githubusercontent.com/18501150/49819713-65c24980-fd76-11e8-8294-5240067a06cf.png)

**Comment by A-312** [comment]
PS : Je prends.

Ma progression : 
 - [Rendu contenu vide](https://user-images.githubusercontent.com/18501150/49820675-d8ccbf80-fd78-11e8-984c-8f2bc0106965.png) -> Je vais modifier encore un peu
 - [Rendu pour un minituto](https://user-images.githubusercontent.com/18501150/49820048-2c3e0e00-fd77-11e8-8f78-0b7c4689d8a1.png)

**Comment by Situphen** [comment]
> On souhaite quel padding ?

Je dirais le deuxième, pour être cohérent avec le reste du site web. Après ça se discute car ça prend plus de place. Tu en penses quoi toi ?

**Comment by A-312** [comment]
2ème ça correspond mieux à l'assemble du site et ça rend mieux pour le "rendu contenu vide" (screen ci-dessus)

@Situphen : Nouvelle partie en bleu ou en jaune ? J'avais mis bleu pour différencier les deux mais est-ce vraiment utile ?

![image](https://user-images.githubusercontent.com/18501150/49828035-20f4dd80-fd8b-11e8-855a-2e4a21a505de.png)
ou
![image](https://user-images.githubusercontent.com/18501150/49828060-34a04400-fd8b-11e8-8526-be81e51d650c.png)

**Comment by Situphen** [comment]
Je préfère le bleu à l'orange, on voit mieux la différence !

- Je propose de renommer "Nouvelle une partie" en "Ajouter une nouvelle partie" et de faire en sorte que le lien redirige vers la page pour créer une nouvelle partie (donc pas besoin du bouton "Ajouter" à droite et pas besoin non plus du bloc "Cliquer sur ajouter pour...")
- Dans la partie juste au dessus "Tuto : Partie", tu as mis des liens "Ajouter une partie", mais c'est plutôt "Ajouter une section" si je ne me trompe pas

**Comment by A-312** [comment]
> de faire en sorte que le lien redirige vers la page pour créer une nouvelle partie (donc pas besoin du bouton "Ajouter" à droite et pas besoin non plus du bloc "Cliquer sur ajouter pour...")

C'est déjà le cas mais c'était pour garder la cohérence avec en haut.


(Je note ce lien ici : https://docs.djangoproject.com/en/2.1/ref/templates/builtins/#complex-expressions , il risque de me servir pour la ma pr)

**Comment by A-312** [comment]
Garder le bloc "warning" permettait notamment de garder une cohérence avec les billets/articles : 

![image](https://user-images.githubusercontent.com/18501150/49861243-b62fba80-fdfb-11e8-87f2-68956f7ab2a5.png)

Je laisse comme ça on voit la finalisation à la PR ? Pour qu'on uniforme tout, ça prend 2 minutes à les enlever au pire.

**Comment by Situphen** [comment]
On verra ça sur la PR
