### ISSUE TITLE
Corriger le fonctionnement de l'aperçu du markdown

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5031]
![](https://i.imgur.com/ZaCtJxF.gif)

https://github.com/zestedesavoir/zds-site/blob/ae1f94d073ea2534b22c944814f94c6a5f840051/assets/js/ajax-actions.js#L282-L296

 1. Rajouter une nouvelle variable et condition, pour ne pas pouvoir flooder l'envoie via un attr data, une variable globale pourrait poser problème si on souhaite lancer un aperçu différent dans l'édition des tutos sur l'intro et la conclusion. Où en tout cas prévoir le cas à votre manière.

 2. Comprendre pourquoi on a besoin de cliquer deux fois sur le bouton aperçu. C'est peut-être previewDelay qui pose problème : https://github.com/zestedesavoir/zds-site/blob/ae1f94d073ea2534b22c944814f94c6a5f840051/assets/js/ajax-actions.js#L247 Différencier un aperçu auto et un aperçu manuel.

**Q/A** : 

Lors du Q/A simuler une connexion lente et une connexion ADSL (ça existe encore).

+ Essayer l'édition d'une partie / section  / édition du tuto en plus du forum.

**Comment by gustavi** [comment]
Peux-tu renommer l'issue avec un titre plus explicite ? Merci :)

**Comment by Situphen** [comment]
1. On peut flooder en appuyant plusieurs fois sur Aperçu mais on peut déjà le faire avec F5 ou wget ou curl. Je n'ai pas entendu de problème particulier lié à ça. Donc, quelle raison te pousse à proposer ça ? :)
2. Quand a-t-on besoin de cliquer deux fois sur Aperçu ? Sur le forum, personnellement 1 clic me suffit.
3. Pourquoi différencier un aperçu auto d'un aperçu manuel ?
4. Qu'appelles-tu une connexion lente ? Aussi, on ne pourra pas éviter tous les problèmes de chargement sur ces connexions :)

**Comment by A-312** [comment]
1. Ca me dérange et avant ce n'était pas comme ça.

2. Surtout quand j'édite mon tutoriel et je l'ai eu sur le forum aussi. Très récurent, et l'aperçu est vraiment lent plusieurs secondes alors que le chargement de la page se fait très très rapide (moins d'une seconde).

3. L'aperçu auto retarde un aperçu demandé manuellement :(

4. ~1 Mo/s

https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=52

**Comment by pierre-24** [comment]
Ça à l'air de ne déranger personne, mais je seconde la réponse de @A-312 pour le deux. C'est réellement lent de temps à autre (et j'ai la fibre à la maison, et je suis en éthernet dessus).

**Comment by gllmc** [comment]
Personnellement, je dois quasi-systématiquement appuyer deux fois sur mobile, quelle que soit la qualité de la connexion.

**Comment by A-312** [comment]
Même avec ma très bonne connexion c'est lent (~12Mbps), je dois appuyer plusieurs fois, c'est insupportable, ça n'a jamais était aussi désastreux. :(

**Comment by artragis** [comment]
Apparament @SpaceFox a trouvé une piste : je cite : 

> _(pour information, j'ai été obligé de remonter la liste des messages postés par @cepus pour retrouver cette conversation, ni le moteur de recherche interne ni Google ne m'ont aidé…)_
> 
> Je confirme que c'est précisément le test ici https://github.com/zestedesavoir/zds-site/blob/ae1f94d073ea2534b22c944814f94c6a5f840051/assets/js/ajax-actions.js#L298 qui pose problème : pour une raison X ou Y, le serveur était lent tout à l'heure (400 ms de ping sur une fibre sans charge), donc au lieu d'avoir :
> 
> 1. Survol du bouton → envoi de la requête
> 2. Réception de la réponse
> 3. Click → MàJ de l'aperçu
> 
> J'ai eu :
> 
> 1. Survol du bouton → envoi de la requête
> 2. Click → Rien parce que pas de nouvel aperçu
> 2. Réception de la réponse mais on en fait rien parce pas le bon évènement
> 
> Ça améliore vraiment la réactivité de façon perceptible de faire la requête au survol et pas au clic ?
Source:[SpaceFox](https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=52#p187584)

**Comment by SpaceFox** [comment]
Surtout, personnellement je ne comprends pas l'utilité d'un montage aussi tordu pour un bête bouton d'aperçu. Pourquoi ne pas simplement faire la requête au clic sur le bouton et afficher le résultat dès qu'on l'a ? Quitte à mettre un loader en attendant la réponse et un [debounce](https://lodash.com/docs/4.17.10#debounce) pour éviter les multi-clics par mégarde, pour éviter le plus gros des inconvénients.

Alors effectivement y'a des cas où la solution de la requête au survol sera plus réactive, mais : 

- Ça se joue à une poignée de millisecondes – l'intervalle entre le moment où la souris arrive sur le bouton et celui où le clic est activé –, le gain de latence dans le cas classique me semble minimal,
- De toutes façons quand il y a latence remarquable, elle est présente que l'on ait fait ce pré-chargement ou non.
- Ça évite les problèmes d'asynchronismes qui se marchent dessus,
- KISS. De mon point de vue et à moins que j'aie loupé quelque chose d'important, on est dans un cas de sur-optimisation.

**Comment by vhf** [comment]
Bon ben la PR est prête.

**Comment by pierre-24** [comment]
Voilà qui devrait être bon :)
