### ISSUE TITLE
La documentation linux et makefile illogisme

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5034]
Contrairement à la documentation Windows, celle de Linux ne contient pas le blabla `git clone https://github.com/zestedesavoir/zds-site.git` et machin.

On nous dis d'utiliser `make install-debian` mais pour ça, ça nous oblige deux choses : 

 1. On a dû au préalable installé git : 
 2. Pour utiliser la commande `make`, on a du au préalable installer build-essential.

Il faudrait donc rajouter un passage sur git clone + `apt-get install git build-essential`.

----

Et dernier point : Le makefile oblige d'avoir sudo d'installé, donc blabla sur sudo ? donc ` apt-get install sudo` et `usermod -aG sudo votre_nom_dutilisateur`

**Comment by A-312** [comment]
Il faut mettre à jour le passage sur virtualenv dans la doc et utiliser : `python3-venv`

Donc : 

    1. Installez python-venv : sudo apt-get install python3-venv.
    2. Puis créez l’environnement zdsenv avec : python3 -m venv zdsenv.

Et peut être ajouté python3-venv dans le makefile.

**Comment by A-312** [comment]
Je serais partant pour mettre le contenu de la section que j'ai faite ici plutôt que de la mettre dans un tutoriel

**Comment by pierre-24** [comment]
J'y ai travaillé ici: #5001. Donc voilà.

**Comment by A-312** [comment]
@pierre-24 Je peux fermer cet•te• issue ? (écriture inclusive je ne connais pas le genre d'issue lol).

**Comment by pierre-24** [comment]
Une ? :p 

Et oui.
