### ISSUE TITLE
Impossible d'arrêter de suivre certains (tous ?) contenus

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5037]
**Reproduction**

- S'abonner à un contenu
- Tenter de se désabonner et voir que le bouton ne bouge pas

**Exemples de contenus**

- [Un schtroumpf en Suède](https://zestedesavoir.com/billets/2718/un-schtroumpf-en-suede/)
- [L'astronomie depuis mon canapé](https://zestedesavoir.com/tutoriels/857/lastronomie-depuis-mon-canape/)

**Comment by gllmc** [comment]
À noter que les notifs par mail sont aussi concernées : impossible de les désactiver.

(Par contre le bouton bouge, mais c'est annulé quand on recharge.)

**Comment by artragis** [comment]
as-tu testé sur la béta?

**Comment by gllmc** [comment]
Je viens de tester et il n'y a aucun problème. Par contre je suis admin sur la bêta, ça a peut-être un impact. Il me semble qu'on a eu des bugs de ce type sur les forums qui ne touchaient pas le staff.

**Comment by nils-van-zuijlen** [comment]
J'ai testé aussi. J'ai le bug sur la prod, mais pas sur la beta.

**Comment by artragis** [comment]
Je clos, c'est donc bel et bien le problème corrigé [ici](https://github.com/zestedesavoir/zds-site/commit/b10f353daa3f7dbea5fc9f6ec628bd3734819722)
