### ISSUE TITLE
Ajouter mastodon dans le footer à côté de twitter

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5038]
Certaines personnes n'ont pas connaissance de l'existence, nous devrions mettre en avant notre Mastodon : ZesteDeSavoir@framapiaf.org dans le footer.

Pour le logo je peux en produire un au format voulu, j'ai repéré plusieurs images libres et sympas.

**Comment by artragis** [comment]
Si la com' est active sur ce réseau social là, oui, il faut le metre, tu as raison.

**Comment by A-312** [comment]
J'ai oublié de mettre le lien : https://framapiaf.org/@ZesteDeSavoir

**Comment by A-312** [comment]
Il faut ajouter 4 versions du .svg... ici : https://github.com/zestedesavoir/zds-site/tree/e20cc05bc4ee163786c136465019e2fc43407626/assets/images/sprite

**Comment by A-312** [comment]
~~@firm1 Je ne comprends pas la différence de nuance dans darken : https://github.com/zestedesavoir/zds-site/blob/dev/assets/scss/base/_forms.scss#L219-L242 Pourquoi ne pas définir une identique ?~~

**EDIT :** Je croyais que c'était une nuance de gris mais c'est la couleur du logo officiel. X/

Parcontre je ne comprends pas pourquoi elle ne s'active pas en :hover , le comportement actuel et le comportement voulu ? Où il faut afficher la couleur officielle ?

**Comment by firm1** [comment]
Le morceau de code que tu linke ne semble pas être utilisé ici. Si tu regarde bien, il faut un parent qui dont la classe est `.content-container` ou `.modals-container`, ce qui n'est pas le cas pour nous.

On dirait que c'est du code mort

**Comment by A-312** [comment]
Je supprime ?  Je l'ai factorisé pour rien x)

```
    @mixin btn-social($socialname, $color) {
        .btn-#{$socialname}:not(.link) {
            background: $color;

            &:hover,
            &:focus {
                background: darken($color, 10%);
            }
        }
    }

    @include btn-social("facebook", #3b5998);
    @include btn-social("twitter", #4099FF);
    @include btn-social("mastodon", #3088d4);
    @include btn-social("google-plus", #d34836);
```

**Comment by firm1** [comment]
si tu ne vois pas d'endroit ou il est appelé dans le code, tu peux supprimer oui.

**Comment by A-312** [comment]
J'hésite à faire #4100 en même temps :)

**Comment by nils-van-zuijlen** [comment]
Non, on a dit dans le CONTRIBUTING que les PRs doivent être atomiques = avec une seule fonctionnalité.

**Comment by A-312** [comment]
Dans le sens où j’intègre le SVG directement

**Comment by A-312** [comment]
j'ai pris : https://fr.wikipedia.org/wiki/Fichier:Mastodon_Logotype_(Simple).svg

Ce qui donne : 

![image](https://user-images.githubusercontent.com/18501150/50274118-b0aa2400-043c-11e9-9f5f-fb215c2cbff3.png)

**Comment by A-312** [comment]
![mastodon](https://user-images.githubusercontent.com/18501150/50275310-578fbf80-043f-11e9-946e-d0a6b3e52124.png)
![mastodon 2x](https://user-images.githubusercontent.com/18501150/50275311-578fbf80-043f-11e9-80af-3c28f77b8989.png)
![mastodon-blue](https://user-images.githubusercontent.com/18501150/50275312-58285600-043f-11e9-878e-f3beeeafb130.png)
![mastodon-blue 2x](https://user-images.githubusercontent.com/18501150/50275313-58285600-043f-11e9-988e-2903f030f8e2.png)
![mastodon-light](https://user-images.githubusercontent.com/18501150/50275314-58285600-043f-11e9-8e79-a94186e49124.png)
![mastodon-light 2x](https://user-images.githubusercontent.com/18501150/50275315-58285600-043f-11e9-94d7-c56ea553e11f.png)

**Comment by A-312** [comment]
![mastodon](https://user-images.githubusercontent.com/18501150/50276452-4300f680-0442-11e9-8769-eab91cb29712.png)
![mastodon 2x](https://user-images.githubusercontent.com/18501150/50276453-43998d00-0442-11e9-9587-bc10581b31df.png)
![mastodon-blue](https://user-images.githubusercontent.com/18501150/50276454-43998d00-0442-11e9-9693-010cc6499c57.png)
![mastodon-blue 2x](https://user-images.githubusercontent.com/18501150/50276455-43998d00-0442-11e9-972a-6a3b6d0ebe42.png)
![mastodon-light](https://user-images.githubusercontent.com/18501150/50276456-44322380-0442-11e9-9eca-8c529bd79dfe.png)
![mastodon-light 2x](https://user-images.githubusercontent.com/18501150/50276457-44322380-0442-11e9-827b-3195731d6048.png)
