### ISSUE TITLE
Ajouter le smiley :popcorn:

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5042]
https://zestedesavoir.com/forums/sujet/538/clem-sur-le-devant-de-la-scene/?page=17#p187805

Smiley : `:popcorn:`, quand j'ai fais mon issue des smileys clems v2, je suis passé a côté de ce smiley ! Caché à la 10-12eme page :(
 
![44x27](https://raw.githubusercontent.com/SimpleSoftwares/Clemojis/master/Popcorn%202018/popcorn_LD.png)

Magnifique travail de Piwit :) 

|    |                  Normal                   |                      HD                   |
|----|-------------------------------------------|-------------------------------------------|
| :B | ![44x27](https://raw.githubusercontent.com/SimpleSoftwares/Clemojis/master/Popcorn%202018/popcorn_LD.png) | ![92x54](https://raw.githubusercontent.com/SimpleSoftwares/Clemojis/master/Popcorn%202018/popcorn_HD.png) |

@Eskimon Si tu as une meilleure idée de tag, n'hésites pas :p Après tout l'idée est née de toi ;) 

Si quelqu'un d'autre a une meilleure idée, n'hésitez pas.

Ne pas oublier de PR le changement dans : https://github.com/zestedesavoir/zmarkdown/ comme : https://github.com/zestedesavoir/zmarkdown/pull/261

**Comment by A-312** [comment]
Et aussi ici : https://github.com/zestedesavoir/documents-communication/tree/master/emoticones

**Comment by pierre-24** [comment]
Bon, vu que pour le smiley :B on attend le prochain déploiement, autant faire une pierre (haha) deux coup, non ?

**Comment by A-312** [comment]
Plus qu'a Q/A @pierre-24 ;)

**Comment by pierre-24** [comment]
ça va être vite, QA, mais oui :p
