### ISSUE TITLE
Essayer l'éligibilité aux CII Best Practices

### ISSUE THREAD

**Issue by nils-van-zuijlen** [zestedesavoir/zds-site#5043]
Proposé [sur Mastodon](https://framapiaf.org/web/statuses/100634008418791259)

@roipoussiere@mastodon.tetaneutral.net
> Hello ! 👋
> Toi là, qui développe un super projet... le saviez-tu ?
> Tu as plein de conseils sur comment faciliter les contributions avec les CII Best Practises : https://bestpractices.coreinfrastructure.org/en ! \o/
> En gros tu répond à des questions et à la fin tu as un joli badge qui t'indique à quel point ton projet donne envie de contribuer (que tu pourra fièrement ajouter à ton dépôt)

@Eskimon@framapiaf.org
> @roipoussiere@mastodon.tetaneutral.net coucou @ZesteDeSavoir@framapiaf.org , ça donnerait quoi ?

@roipoussiere@mastodon.tetaneutral.net
> @Eskimon@framapiaf.org
> il faudrait qu'un dev prenne le temps de répondre aux questions (ça prend 10-15 minutes). 😛
> Mais oui ce serait top et ça vaudrait le coup d'écrire un billet de blog sur le sujet, si ça te tente 😉 
> @ZesteDeSavoir@framapiaf.org

Est-ce que quelqu'un qui connait bien le repo et son fonctionnement pourrait voir si on est éligibles ?

@Eskimon 
@roipoussiere

**Comment by pierre-24** [comment]
Faudrait voir dans le détail, mais en parcourant le document en diagonale, on semble éligible. Je peux regarder :)

**Comment by lypwig** [comment]
Il n'y a pas de critère d'éligibilité, tout le monde peut remplir le questionnaire et avoir son badge ! :P
Après si ton projet et pourri et que tu as une mauvaise note, c'est une autre histoire... mais je pense que zds s'en tire pas trop mal. :)

**Comment by artragis** [comment]
on n'a pas trop le temps.
