### ISSUE TITLE
Utiliser pm2 avec gulp watch

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5052]
Il faudrait peut être modifier la commande dans makefile par : 

` pm2 start gulp --name gulpWatch -- watch`

C'est peut-être plus adéquat d'utiliser pm2 pour éviter de bloquer le terminal ;)

Puis : `pm2 stop gulpWatch`

**Comment by A-312** [comment]
Ce n'est peut-être pas aussi simple, lorsqu'une erreur est détecté dans le JS ça fait planter entièrement planté pm2 et même zmd (à vérifier).

**Comment by vhf** [comment]
Ça me semble pas souhaitable que `gulp` se détache du terminal. C'est un outil de développement, comme le serveur de dev django ou autres.
