### ISSUE TITLE
Modifier [Résolu] par ✓

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5053]
Lorsqu'on lit plusieurs sujets Résolu, on se perd vite dans les onglets : 

![image](https://user-images.githubusercontent.com/18501150/45023066-f7af0d80-b035-11e8-9439-d0b7ee50269b.png)

Je propose donc de remplacer [Résolu] par ✓ pour avoir le premier mot du titre visible

**Comment by firm1** [comment]
Il me semble que ce [Résolu] dans le titre, c'est pour une question de SEO. ça permet au moteur de recherche de savoir que le post est solutionné.

Je ne pense pas que le caractère `✓` joue le même role

**Comment by A-312** [comment]
Ah ok :/ Je vais le `document.title.replace(/\[Résolu\]/, "✓")` avec un userscript alors. A moins qu'on peut le faire sur le zds dans onload ?

**Comment by firm1** [comment]
Je préfère que ce ne soit pas inclus dans zds perso. ça fera toujours un traitement JS en moins coté client.

**Comment by A-312** [comment]
On peut vérifier où le bien-fait de [Solved] ?

**Comment by firm1** [comment]
Je sais pas. Mais c'est la raison qu'on m'avait donné a l'époque.

**Comment by A-312** [comment]
Ca me parait gros quand même

**Comment by firm1** [comment]
ping @Alex-D ? Tu t'en souviens ?

**Comment by Situphen** [comment]
Personnellement je trouve ✓ bien moins compréhensible que [Résolu] dans les résultats de recherche

![screenshot_20180904_160915](https://user-images.githubusercontent.com/6664636/45036549-12e14380-b05d-11e8-93ad-299e4e947f84.png)
![screenshot_20180904_161008](https://user-images.githubusercontent.com/6664636/45036555-1674ca80-b05d-11e8-8877-cd11c893b670.png)

**Comment by A-312** [comment]
L'argument de Situphen se tien et je partage cet avis. N'hésitez pas à donner votre avis (je laisse ouvert, le temps d'avoir d'autres avis).

**Comment by Alex-D** [comment]
Je ne me souviens plus vraiment non désolé :/

J'ai fait quelques recherches et je trouve rien qui explique que l'une ou l'autre des solutions soient mieux d'un point de vue SEO.

Par contre, je déconseille le changement en JS côté ZdS : soit c'est fait côté serveur, soit il ne faut pas le faire. Google sait interpréter le JS maintenant et donc ça ne changera rien de le faire côté serveur ou côté client, si ce n'est du calcul inutile.

(Et je pouceenlairise l'argument de Situphen)

**Comment by artragis** [comment]
Je prends ma casquette de maitainer

En plus de l'avis assez détaillé de @sandhose , j'ai fait quelques recherches et je suis tombé sur cet itnerview https://www.arobasenet.com/2014/07/conseils-seo-de-google-concernant-forum-1085.html

En soi, ils ne disent pas "il faut mettre résolu" mais "il est conseillé de donner à l'admin la possibilité de changer le titre".

On y ajoutera que plusieurs outils de type "forum" utilisent eux aussi la marque "résolu" on notera que `(Résolu)` et `[résolu]` sont des marques courantes qu'on trouve dans les résultats google ainsi que dans les conseils des communautés basées sur les forums. Je drais que c'est une forme de *standard de fait*.

Je vais donc clore ce ticket, mais j'ai beaucoup apprécié le sujet qu'il a levé, merci pour ta participation @A-312 c'est super agérable que les sujet front-end et SEO bougent et ton implication est agréable !
