### ISSUE TITLE
scss : "DEPRECATION WARNING" avec LibSass

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5059]
`gulp css` : 

```
DEPRECATION WARNING on line 13, column 8 of /home/a312/zds/zds-site/assets/scss/main.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 14, column 8 of /home/a312/zds/zds-site/assets/scss/main.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 8, column 8 of /home/a312/zds/zds-site/assets/scss/zmd.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.
```

**Comment by pierre-24** [comment]
Lié à #4990 ;)

**Comment by A-312** [comment]
Pas du tout justement : 

Selon https://github.com/sass/node-sass/issues/2362#issuecomment-386259486, il faut remplacer : 

```css
@import "foo.css";
```

Will be transformed to

```css
@import url(foo.css);
```

**Comment by Situphen** [comment]
Comme je l'ai dit sur la PR, passer à `@import url(foo.css)` casse le CSS. Je me suis renseigné et il se trouve que finalement `node-sass` ne va pas déprécier l'import CSS tel qu'il l'est actuellement. Ils ont enlevé l'avertissement dans `node-sass@4.10`. On utilise `gulp-sass` qui utilise actuellement `node-sass@4.8` mais il y a une PR pour passer à `node-sass@4.11` donc dans pas trop longtemps on pourra mettre à jour `gulp-sass` pour enlever l'avertissement.

Lire https://github.com/sass/node-sass/issues/2362#issuecomment-396239814 pour plus d'informations

**Comment by Situphen** [comment]
Ce n'est plus d'actualité.
