### ISSUE TITLE
Les +1/-1 ne s'affichent pas en mode deconnecté

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#506]
Les +1/-1 ne s'affichent pas lorsque l'on est en mode déconnecté.
Est-ce voulu ?

**Comment by Alex-D** [comment]
Holà, 
C'est du front, le front ça se passe plutôt sur la branche intégration.

Merci :)

**Comment by GerardPaligot** [comment]
En passant, les contributions se font par PR. Là tu viens d'appliquer une modification directement sur la branche tirée sur le serveur de production sans l'accord de personne.

**Comment by SpaceFox** [comment]
> Merge branch 'release-beta-1.0' of github.com:Taluu/ZesteDeSavoir into
> release-beta-1.0

Heu, juste : plus. jamais. ça.

**Comment by Eskimon** [comment]
Arf j'étais justement en train de faire un mea culpa sur le forum :s

Désolé du bordel, je me suis un peu emballé :s (et j'ai pas trop réfléchi en me disant qu'étant sur un dépot privé GH me balancerait automatiquement sur une PR pour éviter les conneries...)

Le boulet du jour, le voila !

**Comment by firm1** [comment]
Yolo, no excitation.

Merci pour ton fix Eskimon. Une erreur ça arrive

**Comment by GerardPaligot** [comment]
Pas grave, il n'existe pas encore de gitflow de toute façon (ou du moins, il ne semble pas fixé) ... :)

@firm1 C'est pas un fix.

**Comment by Alex-D** [comment]
Nan, je pense que le prix du boulet du jour me revient, si ça peut te rassurer ><"

Sinon, ce bugfix est du front, du coup regarde sur la branche intégration quand c'est comme ça. Et a priori, c'est déjà fixé chez moi je pense.

**Comment by Eskimon** [comment]
Vous avez pas idée comment je me sens hyper con derrière mon PC là -_-' ...

Tellement habitué au process hyper verrouillé au taf que du coup jme suis pas posé plus de question que ca :(

> Sinon, ce bugfix est du front, du coup regarde sur la branche intégration quand c'est comme ça. Et a priori, c'est déjà fixé chez moi je pense.

Moi qu'étais tout content d'avoir solve un truc tout seul :D Tant pis, je me serais entrainé et vous aurais fait un entrainement pour les cas de panique :D

Sinon, du coup vous le justifiez comment le fait qu'on affiche pas les +1/-1 pour un lecteur déconnecté ?
