### ISSUE TITLE
Améliorer les linter et les formatters, abandonner codacy

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#5066]
- [x] abandonner codacy
- [ ] ajouter pylint + pylintrc
- [ ] s'assurer que jshint fonctionne bien (ou changer vers eslint)
- [ ] ajouter un check `git diff HEAD~1 --name-only | grep "\.py$" | xargs black -S -l 120 --check` pour s'assurer, petit à petit que les fichiers sont bien formattés

**Comment by Situphen** [comment]
Alors si je ne me trompe pas `git diff HEAD~1 --name-only` donne la liste des fichiers modifiés et `grep "\.py$"` permet de ne garder que les fichiers Python, mais je ne sais pas ce que fait `xargs black -S -l 120 --check` exactement. Peux-tu expliquer ? :)

**Comment by artragis** [comment]
black est un formatteur de python qui a été développé par facebook. Il permet de formatter le python tout en s'assurant que le formattage ne change pas l'arbre syntaxique. L'option "-l" permet de dire quelle est la longueur de ligne qu'on veut (88 par défaut), et -S permet de dire "on ne normalise pas les string" car black normalise avec des doubles guillemets.

L'option "check" permet simplement de dire "notifie moi s'il y a des changements à faire mais le les fait pas".

**Comment by nils-van-zuijlen** [comment]
Qu'est-ce qu'apporte black de plus que flake8 ? Surtout dans l'utilisation planifiée ?

**Comment by artragis** [comment]
flake8 est très lâche et surtout black est un formatter => il va donc uniformiser le format du code et réécrire le fichier.

**Comment by Situphen** [comment]
Je suis tombé sur [Prettier](https://prettier.io/), un *formatter* pour le JS.

Je me demande si lors du passage à Black (et potentiellement à Prettier) on ne devrait pas modifier tous les fichiers une fois pour toute. Car le problème avec la technique du `git diff ... --name-only | ...` c'est qu'on donne à Black le nom des fichiers, donc si tu modifies une seule ligne ou un seul bloc alors Back va se plaindre car le reste du fichier n'est pas bon. Aussi, ça ne modifie que la syntaxe donc ça ne devrait pas poser de gros soucis.

**Comment by artragis** [comment]
avant de passer à black faut qu'on abandonne 3.5 pour 3.6

**Comment by Situphen** [comment]
Ça n'empêche pas de réfléchir à l'utilisation de Black et Prettier mais tu as raison de le préciser. J'ai regardé et la bêta utilise Python 3.5 (idem pour la prod, je suppose) donc il va falloir changer ça. Au niveau des dépendances, ça ne pose pas de problème vu que je suis actuellement en Python 3.6.

**Comment by Situphen** [comment]
On utilise Black (pour Python) et ESLint (pour JS) depuis plusieurs mois sans soucis donc je ferme.
