### ISSUE TITLE
Impossible de se connecter après un mot de passe oublié

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#5068]
J'ai oublié mon mot de passe sur mon compte "Hugo". J'ai fait une demande pour le ré-initialiser, je reçois bien le mail, je rentre mon nouveau mot de passe, je valide et je tente de me connecter et j'ai une erreur mot de passe invalide.

**Comment by nils-van-zuijlen** [comment]
Est-ce que tu es connecté à la fin ? Malgré l'erreur de mot de passe invalide ?

**Comment by DevHugo** [comment]
Non, je ne suis pas connecté. Après je me suis inscrit depuis assez longtemps.

**Comment by nils-van-zuijlen** [comment]
Est-ce que quelqu'un peut vérifier les logs ?
@artragis @sandhose 
 Et est-ce que tu t'es inscris depuis les réseaux sociaux ? (Si tu t'en souviens, ou si possible, vérifier en BdD)

**Comment by DevHugo** [comment]
Bon j'ai réussi à reset mon compte depuis une autre session connecté ! 

J'arrive pas à le reproduire sur une instance locale donc je ferme
