### ISSUE TITLE
Clemoji v3

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5069]
Remplacer les smileys correspondants par nos Clemojis (version quasi-final) : 

[Clemoji - version non-final](https://user-images.githubusercontent.com/18501150/45574124-3bdcb200-b86f-11e8-93f5-d3ef412cc6b4.png)

 - [x] Support zmardown (ici : https://zestedesavoir.com/forums/sujet/11010/doleances-sur-le-zmarkdown-de-la-v27/?page=6#p189227 )
 - [x] Clemoji v3 entièrement adapté ([voir sur le forum](https://zestedesavoir.com/forums/sujet/538/clem-sur-le-devant-de-la-scene/?page=18#p189225)).
 - [x] Clemoji v2 adapté en v3 (trait plus épais).

**Comment by A-312** [comment]
~~Il y a du favoritisme parmi les smileys.~~

[clemoji_b](https://user-images.githubusercontent.com/18501150/45575944-8bbe7780-b875-11e8-862b-e122127ae5ba.png)


|    |                  Normal                   |                      HD                   |
|----|-------------------------------------------|-------------------------------------------|
| :B | ![clemoji_b_ld 19x27](https://user-images.githubusercontent.com/18501150/45576465-95e17580-b877-11e8-9928-a2813f90f271.png) | ![clemoji_b_hd 38x54](https://user-images.githubusercontent.com/18501150/45576039-e657d380-b875-11e8-9761-408e23a96fac.png) |

**Comment by A-312** [comment]
Ils sont tous là : https://github.com/zestedesavoir/documents-communication/blob/master/emoticones/clemoji/README.md

```text
👿 😀 😁 😂 😃 😄 😅 😆 😇 😈 😉 😊 😋 😌 😍 😎 
😏 😐 😑 😒 😓 😔 😕 😖 😗 😘 😙 😚 😛 😜 😝 😞
😟 😠 😡 😢 😣 😤 😥 😦 😧 😨 😩 😪 😫 😬 😭 😮
😯 😰 😱 😲 😳 😴 😵 😶 😷 🙁 🙂 ☺  🙃 🙄 🤐 🤑
🤒 🤓 🤔 🤕 🤗 🤢 🤣 🤤 🤥 🤧 🤨 🤩 🤪 🤫 🤬 🤭
🤮 🤯 🥰 🥳 🥴 🥵 🥶 🥺 ☹ 
```

[image](https://user-images.githubusercontent.com/18501150/45588676-b1e92380-b918-11e8-91e0-5e65c05d358a.png)

![image](https://user-images.githubusercontent.com/18501150/45588681-b7df0480-b918-11e8-8cd2-a0881ae049c1.png)


# Ready à coder !

PS : Je ne fais pas de back. PS 2 : Donc je cherche quelqu'un pour la suite. :')

## Emoji v2

On ne touche pas aux emoji v2, ni au .png pour le support des anciens messages. A part le ":B" qu'on passe en .SVG, on garde les autres emoji v2 en .png. La conversion .PNG => .SVG sera pour une autre PR. ;)

**Comment by A-312** [comment]
Peut-être prévoir d'ajouter cette règle CSS : 

```css
.smiley {
    vertical-align: baseline;
    margin-bottom: -4px;
}
```

**Comment by A-312** [comment]
- [ ] Ajouter une règle CSS spécifique au smiley souligné en rouge.

**Comment by A-312** [comment]
@artragis Ca avance tranquillement ça devrait arriver fin janvier.

**Comment by A-312** [comment]
https://zestedesavoir.com/forums/sujet/538/clem-sur-le-devant-de-la-scene/?page=20#p194016

Ça me prend beaucoup de temps à les enregistrer individuellement pour qu'ils aient le même format + même position.

**Comment by A-312** [comment]
\+ soit compatible à tous les lecteurs .svg.

**Comment by A-312** [comment]
Le 😕 aura l'alias `:-/`.

**Comment by A-312** [comment]
La liste est terminée : 

 - https://github.com/zestedesavoir/documents-communication/blob/master/emoticones/clemojiv3/README.md

Il faut rajouter la correspondance `:emoji:` -> `lienimage.svg`

+ Remplacer : `👿 😀 😁 😂 😃 😄 😅 😆 😇 😈 😉 😊 😋 😌 😍 😎 
😏 😐 😑 😒 😓 😔 😕 😖 😗 😘 😙 😚 😛 😜 😝 😞
😟 😠 😡 😢 😣 😤 😥 😦 😧 😨 😩 😪 😫 😬 😭 😮
😯 😰 😱 😲 😳 😴 😵 😶 😷 🙁 🙂 ☺  🙃 🙄 🤐 🤑
🤒 🤓 🤔 🤕 🤗 🤢 🤣 🤤 🤥 🤧 🤨 🤩 🤪 🤫 🤬 🤭
🤮 🤯 🥰 🥳 🥴 🥵 🥶 🥺 ☹ ` par l'équivalent en clemoji. ;)

**Comment by A-312** [comment]
@artragis L'emplacement des images te convient ?

**Comment by artragis** [comment]
?? je comprends pas la question.

**Comment by A-312** [comment]
@artragis https://github.com/zestedesavoir/zds-site/pull/5361#issuecomment-549924533

Pour les emojis qui ont une version actuelle en png, l'emplacement des svg convient ?

**Comment by artragis** [comment]
il faut les mettre dans le dossier smiley pas dans /svg/smiley
