### ISSUE TITLE
Espace de téléchargement affiché même en l'abscence de fichiers.

### ISSUE THREAD

**Issue by nils-van-zuijlen** [zestedesavoir/zds-site#5070]
Dans le billet https://zestedesavoir.com/billets/2813/le-photographe-non-materialiste/ (et peut-être d'autres), dans la sidebar, la zone de téléchargement est visible, bien qu'aucun fichier ne soit téléchargeable.

![image](https://user-images.githubusercontent.com/22444937/45576107-2919ab80-b876-11e8-9e81-1c424f930342.png)

**Comment by AmauryCarrade** [comment]
Le problème ne serait-il pas qu'il n'y a justement aucun fichier téléchargeable ? Même pas l'archive Markdown… Tous les contenus récents ont ce problème j'ai l'impression. J'aurais envie de dire « depuis le déploiement de la version 27 », mais je ne veux pas m'avancer sans preuve.

**Comment by nils-van-zuijlen** [comment]
Je pense que le problème est double. Abscence d'archive ET présence de la zone vide.

**Comment by artragis** [comment]
ça devrait être corrigé avec la v27.3

**Comment by artragis** [comment]
bon en fait il manquait le fait que si on n'a pas de download, alors on n'affiche rien.
