### ISSUE TITLE
Améliorer le bandeau sur l'utilisation des cookies

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5074]
Je propose principalement de transformer le "OK" en "J'accepte" et de transformer la phrase "Pour s'opposer à ce dépôt vous pouvez cliquez ici" en "Je refuse" qui sont plus clairs pour les utilisateurs.

Voilà le bandeau actuel :

![Bandeau actuel](https://user-images.githubusercontent.com/6664636/45929267-8638ef80-bf4f-11e8-95b8-2e672d4d1d1b.png)

Si vous êtes d'accord sur l'idée, je m'en chargerai.

**Comment by artragis** [comment]
C'est clairement rgpd compliant
:p

**Comment by Situphen** [comment]
Je propose aussi un nouveau texte : 

> Nous souhaitons déposer des cookies à des fins de mesure d'audience avec Google Analytics. Vous êtes libre d'accepter ou de refuser. En poursuivant votre navigation sur ce site sans exprimer votre choix, vous autorisez la mesure d'audience.

Et voici l'aperçu :

![Un aperçu de ce que je propose](https://user-images.githubusercontent.com/6664636/45931018-f489ac00-bf67-11e8-9813-18a47d26c974.png)

**Comment by artragis** [comment]
ça me va perso.

**Comment by AmauryCarrade** [comment]
Ce serait hors-scope d'ajuter les marges pour éviter que lorsque le bouton est à la ligne, il soit collé au bas (ce que je trouve assez disgrâcieux depuis un moment) ? Ainsi que donner la même taille à tous les boutons (chez moi les blancs sont plus petits — mais c'est potentiellement corrigé par Situphen vu que ça ne semble pas être le cas sur sa capture d'écran). Ainsi que de mettre un curseur de pointeur dessus (ce n'est pas le cas chez moi et c'est perturbant je trouve).

Sinon sur l'objectif initial de la PR… je trouve ça bien (et mieux). :+1:

**Comment by Situphen** [comment]
@AmauryCarrade Effectivement comme tu l'as deviné sur ma dernière capture d'écran j'ai commencé à jouer un peu avec le CSS pour que les boutons soient de la même taille et qu'ils aient tous un pointeur au survol de la souris ainsi qu'ajuster les marges.

**Comment by A-312** [comment]
Dommage que la bibliothèque n'a pas incorporé ce changement. 🤣

**Comment by Situphen** [comment]
@A-312 ?

**Comment by A-312** [comment]
Ce n'est pas EU-Banner ou quelque chose comme ça qu'on utilise ?

**Comment by Situphen** [comment]
On utilise EU-Cookies-Banner (quelque chose comme ça) pour gérer le JS, mais le texte et le CSS c'est à nous de le faire ! :)
