### ISSUE TITLE
Pagination manquante sur la liste des Unes

### ISSUE THREAD

**Issue by nils-van-zuijlen** [zestedesavoir/zds-site#5075]
Bonjour,

La pagination (bloc HTML) est manquante sur la liste des Unes. Je suis obligé de le faire manuellement en modifiant l'URL. https://zestedesavoir.com/mise-en-avant/?page=2

Bon vol,

votre avion favori.

Sujet : https://zestedesavoir.com/forums/sujet/11380/bug-pagination-manquante-sur-la-liste-des-unes/
*Envoyé depuis Zeste de Savoir*

**Comment by Situphen** [comment]
J'ai l'impression que [la vue qui liste les unes](https://github.com/zestedesavoir/zds-site/blob/dev/zds/featured/views.py#L21) prévoit déjà la pagination (il y a `ZdSPagingListView` et `paginate_by`) donc normalement il n'y a que le gabarit à modifier. Il faut : 

- Ajouter `{% include "misc/paginator.html" with position="top" %}` avant [cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/templates/featured/index.html#L35)
- Ajouter `{% include "misc/paginator.html" with position="bottom" %}` après [cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/templates/featured/index.html#L54)

Cela devrait suffire je pense.
