### ISSUE TITLE
Préparer la fin de Google+

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5079]
D'après SpaceFox dans [RIP Google+](https://zestedesavoir.com/forums/sujet/11409/rip-google/) sur le forum.

Il faudra : 

- [x] enlever le lien du footer
- [x] enlever le lien pour partager une publication
- [x] modifier les couleurs pour la connexion et l'inscription actuellement "Google+" par le design de Google car c'est pour tous les comptes Google d'après SpaceFox
- [x] s'assurer que les comptes ZDS liés à des comptes Google fonctionnent encore sans Google+

**Comment by Situphen** [comment]
À noter que l'on a 10 mois, donc c'est important mais pas urgent pour le moment :)

**Comment by finkiki** [comment]
Autant virer aussi facebook, c'est plus inutile qu'autre chose à mon avis...

**Comment by sandhose** [comment]
@finkiki étant donné qu'on a 1174 comptes liés à Facebook (2415 Google, 10 Twitter), j'aurais tendance à dire que non. Surtout que c'est pas très coûteux à maintenir.

**Comment by Eskimon** [comment]
Pourquoi tagger comme bloquant du coup ?

**Comment by Eskimon** [comment]
> 
> 
> @finkiki étant donné qu'on a 1174 comptes liés à Facebook (2415 Google, 10 Twitter), j'aurais tendance à dire que non. Surtout que c'est pas très coûteux à maintenir.

Apparemment c'est plus coûteux que ca en a l'air, étant donnée que le ticket #4376 traîne depuis cet été...

**Comment by helmasaur** [comment]
@artragis, je peux m'en occuper ?

**Comment by Situphen** [comment]
@Helmasaur Oui tu peux t'en occuper :)

**Comment by helmasaur** [comment]
Du coup, il faudrait savoir sur quelle couleur partir pour le bouton. En principe, elle devrait être blanche mais vu que le fond est gris clair, ça ne rend pas terrible.
