### ISSUE TITLE
Tris et filtres sur la page de toutes les issues

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#508]
La page de toutes les issues n'est pas paginée (je considère que même si on ne fout rien, on aura jamais assez d'issues pour rendre cette pagination obligatoire, donc KISS)

Idéalement on aurait des tris et des filtres sur le tableau ainsi produit, mais ça devient donc un taff purement FO (on a des trucs jQuery qui font ça je pense), et baisse de priorité. D'où cette nouvelle issue.

Note : cette issue doit attendre que la pages des alertes existe (issue #476) pour arriver...

**Comment by Alex-D** [comment]
En effet, très simple à implémenter.

**Comment by gustavi** [comment]
UP @SpaceFox ! C'est toujours d'actualité ? Si oui de quelle page parles-tu ?

**Comment by firm1** [comment]
Je sais pas ce que Github a fait, mais il parle de la page de toutes les alertes. Et c'est toujours d'actualité

**Comment by SpaceFox** [comment]
À l'usage, on s'en fout. Cette page est vue ~1 fois / mois…
