### ISSUE TITLE
Des sujets de la corbeille en suggestion de sujets similaires pour le staff

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5087]
[ache sur le forum](https://zestedesavoir.com/forums/sujet/11477/sujet-similaires-au-votre/) : 

> Coucou,
> 
> À la création d'un sujet, on nous propose des sujets similaires depuis le titre. 
> Je sais pas si c'est parceque je suis membre de la comm' mais on me propose des sujets de la corbeille ...
> 
> Je pense que c'est un oublie.
> 
> Pour s'en convaincre. Essayer de créer un sujet avec pour titre "Passeport" ou "Passport". :( 
> 
> À plus.

Je pense qu'on peut considérer ça comme un bug.

Pour régler ça, c'est dans [la vue `SimilarTopicsView`](https://github.com/zestedesavoir/zds-site/blob/dev/zds/searchv2/views.py#L24) que ça se passe.

**Comment by philippemilink** [comment]
Les sujets renvoyés par la vue `SimilarTopicsView` contiennent des sujets auxquels le membre peut accéder : https://github.com/zestedesavoir/zds-site/blob/33ff87577b3e217d7f87a3c3d05fa08188123d2d/zds/forum/models.py#L507

Je clos ce ticket en faveur de #6651, qui est plus général.
