### ISSUE TITLE
Indiquer clairement le titre de l'objet sur lequel porte une alerte

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#509]
Aujourd'hui quand on a une alerte, on a le lien vers son topic / tuto / article mais pas le titre de l'objet concerné (topic / tuto / article) dans le menu.

C'est possible, mais compliqué parce qu'il faut faire un traitement différencié selon le type de l'alerte, remonter au parent et en afficher le titre. Le tout dans un menu affiché sur toutes les pages pour les utilisateurs concernés.

Dans l'absolue, ça attend d'avoir un cache sur ce menu. En attendant c'est dommage, mais comme on a le lien direct ça devrait rester utilisable.

**Comment by Alex-D** [comment]
N'est-il pas possible de dénormaliser ? Une alerte étant éphémère ça ne devrait pas poser trop de soucis à mon avis.

NB : les alertes ne sont présentes que pour les staffeux, donc si optimisation il y a, c'est pour notre confort personnel.

**Comment by firm1** [comment]
Cette issue est fixée il me semble.

**Comment by Alex-D** [comment]
Je confirme. Par contre ça va poser des problèmes au merge. Je verrais ça.
