### ISSUE TITLE
Améliorer les pages "Sujets créés"/"Messages postés "d'un membre

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5092]
Le problème est assez évident, la recherche "Sujets créés"/"Messages postés" d'un membre est TRES longue.

Il faudrait transformer cette recherche en deux/trois pages : 

 - Page principale : Affiche la liste des forums mais en prenant en compte seulement les sujets postés par les membres : `https://zestedesavoir.com/forums/messages/3349/` + Mettre un lien dans la sidebar vers `/last/` ;
 - Page secondaire : Quand on clique sur la catégorie on obtient tous les messages correspondants : `https://zestedesavoir.com/forums/messages/3349/savoirs/programmation/` ;
 - Garder le format actuel, par ordre des derniers messages en : `https://zestedesavoir.com/forums/messages/3349/last/`.

**Comment by Situphen** [comment]
Je ne pense pas que ce soit la bonne solution. Pour moi, les deux pages listant les sujets créés et messages postés par un membre devraient seulement être une liste paginée en ordre décroissant comme actuellement (voire elles ne devraient pas exister). Ce qu'il faudrait, c'est améliorer le module de recherche pour pouvoir filtrer par membre, trier par ordre croissant ou décroissant, etc. C'est peut-être un peu utopique, mais ce serait amha la bonne solution.

**Comment by artragis** [comment]
@A-312 et @Situphen je parlerai de ce ticket dans le prochain zest of dev afin d'inviter les gens à voter soit sur la solution de A-312 soit celle de situphen.

**Comment by A-312** [comment]
Voir ma dernière édition de : https://zestedesavoir.com/forums/sujet/11947/centre-des-flux/?page=1#p197646

**Comment by artragis** [comment]
Zombie depuis lontemps et revivé dans une idée plus complète donc je clos pour nettoyer le backlog
