### ISSUE TITLE
Améliorer le temps de lecture lorsqu'il y a des tableaux

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5093]
Vérifier le temps de lecture avec des tableaux et réfléchir à une amélioration possible du système/calcul.

> Temps de lecture estimé : 43 minutes 

https://zestedesavoir.com/billets/2882/pareto-a-t-il-raison/

**Comment by Situphen** [comment]
En fait il faudrait améliorer le temps de lecture tout court ! Notamment revoir le nombre de mots par minute (si je ne me trompe pas) car plusieurs membres présents au JZDS Paris m'ont dit que le temps de lecture affiché était trop long par rapport à la réalité.

Aussi, il faudrait peut-être que l'auteur puisse mettre un temps de lecture à la main, qui remplacerai le temps de lecture estimé.

**Comment by AmauryCarrade** [comment]
Sur le Site du Zéro, l'auteur pouvait spécifier un temps non de lecture, mais _d'étude_. Et je trouve que ça a bien plus de valeur qu'un temps automatiquement calculé sur le nombre de mots, qui prend mal en compte les tableaux, pas du tout les images, etc.

Le système actuel peut servir comme solution si aucun autre temps n'a pu être estimé, mais proposer de spécifier un temps d'étude (et le libeller différemment s'il est spécifié, par exemple _temps d'étude_ versus _temps de lecture_ justement), serait une bonne idée, je trouve.

**Comment by artragis** [comment]
alors je rejoins @AmauryCarrade 
mon principal problème c'est que le temps de lecture est aujourd'hui le même pour un tuto et pour un article. Perso quand je lis un tuto, comme je sais qu'il faut que je m'investisse un peu, ça met toujours plus longtemps qu'un article et souvent ça met le temps proposé dans le tuto.

par contre c'est vrai que pour les billets et articles le temps actuel est un peu... long.

**Comment by artragis** [comment]
ALors pour info, le temps de lecture pourra avoir une meilleure estimation grâce aux améliorations portées à zmd. Il faut créer un publicateur spécifique qui va envoyer le fichier markdown à plat avec la bonne configuration dans la requête pour obtenir les stats. https://github.com/zestedesavoir/zmarkdown/tree/master/packages/zmarkdown#request-opts-values-1

**Comment by artragis** [comment]
Bad issue
