### ISSUE TITLE
Pouvoir ajouter à un contenu des membres en lecture seule

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5097]
@EtoileFilante voudrait pouvoir ajouter des membres en lecture seule à un contenu, ce qui permettrait de montrer le contenu à certaines personnes sans forcément mettre celui-ci en bêta.

Qu'en pensez-vous ?

**Comment by EtoileFilante** [comment]
CC #5297

**Comment by Situphen** [comment]
Permettre de générer un lien à durée limitée accessible par les non-membres qui pointe vers la dernière version brouillon du contenu. Présence d'un avertissement que c'est un contenu non-publié. Vérifier que ce n'est pas indexable par Google et co.

**Comment by Arnaud-D** [comment]
Essentiellement un doublon de #6092.
