### ISSUE TITLE
Enlever le surlignage du code HTML

### ISSUE THREAD

**Issue by nils-van-zuijlen** [zestedesavoir/zds-site#5099]
Salut !

Je propose d'enlever le surlignage bleu clair des lignes de code HTML, je trouve que visuellement ce n'est pas très beau et c'est inutile :

```html
<!DOCTYPE html>
<html lang="fr">
<head>

    <meta charset="utf-8">
    <title>Ce texte n'est pas surligné</title>

    <script>
      // Le code JS n'est pas surligné
    </script>

</head>
<body>

    <p>Some text</p>

</body>
</html>
```

Qu'en dites-vous ?

Sujet : https://zestedesavoir.com/forums/sujet/11582/sugg-enlever-le-surlignage-du-code-html/
*Envoyé depuis Zeste de Savoir*

**Comment by helmasaur** [comment]
**Copie de ma réponse sur le sujet du forum**

Sur [la démo](https://highlightjs.org/demo), il n'y a pas le surlignage. La classe créant ce problème est `hljs-tag`. Ne connaissant pas le fonctionnement de `Highlight.js`, je ne sais pas pourquoi c'est appliqué.

**Comment by Arnaud-D** [comment]
On n'a plus de surlignement sur la prod.
