### ISSUE TITLE
Transformation en lien des adresses mail dans les posts

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#510]
Dans un post, les adresses mail sont censées être transformées automatiquement en lien `mailto` à l'affichage.

Cependant, il semble y avoir quelques soucis : 
=> http://zestedesavoir.com/forums/sujet/115/suggestionrapporte-interdire-les-adresses-email-temporaires?page=1#p1264

A priori, une adresse mail incomplète du type `@mail.com` est transformée. Par ailleurs, le lien généré est foireux (`http://mailto:...`)

**Comment by cgabard** [comment]
Ok, même si pour le coup il aurait mieux valut le remonter dans Python-ZMarkdown.

**Comment by Coy0te** [comment]
Done.
=> https://github.com/zestedesavoir/Python-ZMarkdown/issues/17

**Comment by cgabard** [comment]
Thanks :D
