### ISSUE TITLE
Remarques sur les contributions mineures au code de zds

### ISSUE THREAD

**Issue by gasche** [zestedesavoir/zds-site#5100]
Salut à tous,

J'ai fait trois PRs mineures au code de ZdS le mois dernier (du refactoring, à voir aussi comme de la réduction de dette technique), pour avoir le plaisir de contribuer en faisant quelque chose de facile. Je trouve que votre processus n'intégration des changements n'est pas encore au point, donc je crée une issue pour en discuter.

(Évidemment, même dans "critique constructive" il y a toujours "critique"; je parle de choses améliorables, mais je ne dis surtout pas ça pour que les gens se sentent gênés ou démotivés. Globalement je trouve ça super de gérer ce site de façon ouverte et communautaire, et je suis très reconnaissant à la petite poignée de gens qui fait tourner les parties techniques de ce projet. Merci !)

## Le problème: les merges attendent trop longtemps

Le reproche principal c'est qu'il y a un temps très long entre le moment où on soumet un changement et le moment où il est intégré. Pour #5082, j'ai eu des retours très rapides de @artragis (super !), en deux jours la PR était dans un état mergeable... et j'ai du attendre 15 jours de plus pour que ce soit intégré. Pour #5084, j'ai eu pareil des retours utiles le lendemain, dans ma tête c'était prêt... et j'ai du attendre 23 jours de plus (hier) pour avoir à nouveau de l'action, et elle semble en passe d'être mergée maintenant.

Pour un contributeur occasionnel, ce n'est pas très motivant de devoir attendre autant. Déjà le premier réflexe c'est de se dire : j'envoie un premier truc, je vois comment ça se passe, et ensuite je continuerai mes contributions si ça s'est bien passé. Là j'ai envoyé deux trucs... et il ne se passe rien pendant deux ou trois semaines, donc moi je n'ai rien fait de mon côté. À l'époque j'étais dispo pour contribuer, maintenant je suis pris par le boulot, donc je ne ferai rien avant la prochaine poussée d'envie, alors qu'aurais pu continuer mes refactorings dans les jours qui ont suivi, si les premiers trucs avaient été mergés.

Un autre soucis lié est que quand vous revenez deux semaines après pour dire "maintenant c'est bon, tu peux rebaser ?", la personne a toute les chances d'avoir autre chose à faire à ce moment là, et de laisser traîner (alors que ça aurait été vite quelques jours après).

Pour des grosses contributions, ou des contributeurs fréquents, ces problèmes ne sont pas si importants: de toute façon quand on passe deux mois à retoucher une PR jusqu'à qu'elle soit bonne, on n'est pas trop sensible à un écart de quelques semaines. Quand on est habitué avec le processus, on a une intuition de ce qui va être accepté ou pas, et on n'a pas besoin d'attendre le merge final pour rebondir sur un truc. Mais la grande majorité des contributeurs commencent par faire un petit truc facile, donc il faut faire attention à leur expérience.

## Les causes: le processus de développement

La première cause qui vient à l'esprit, c'est le manque de main d'œuvre pour relire et intégrer des changements. Alors oui, évidemment, ça participe, mais à mon avis il est possible de faire mieux (d'intégrer les contributions faciles en seulement quelques jours, et pas quelques semaines) sans main-d'œuvre supplémentaire ou sans augmenter la charge de travail, juste en améliorant le processus de développement.

Votre documentation <https://docs.zestedesavoir.com/workflow.html> dit que vous suivez le "Git Flow". En pratique, pour ce que j'ai observé, vous ne respectez pas du tout le git flow.

Point un peu mineur, les PRs ne sont pas mergées dans la branche de développement `dev`, mais rebasées. Il suffit de voir [l'historique de la branche](https://github.com/zestedesavoir/zds-site/commits/dev), aucun commit de merge. Je pense que ce serait mieux de merger, parce que ça donne une plus grande lisibilité dans l'historique sur la structure des PRs qui sont entrées. Par exemple, en tant que non-expert du développement, je n'ai aucune idée de quelles sont les dernières PRs à avoir été mergées et dans quel ordre, alors que ça serait immédiatement visible si vous mergiez. C'est plutôt un détail et ça n'impacterait pas les temps de merge, mais je pense que ça rendrait le développement plus accessible aux nouveaux. (Dans le même genre : faites un effort pour inclure le numéro d'une PR ou d'un bug quand vous y faites référence, sinon les non-experts n'arrivent pas à suivre.)

Mais surtout, il n'y a pas de branches de release. Selon ce que j'ai observé en pratique, quand vous décidez de faire une release qui doit contenir certaines PRs par encore mergées (appelons-le "PRs principales"), vous arrêtez de merger tous les autres changements qui n'ont pas été prévus pour la release. (Si je comprends bien, c'est pour éviter que les PRs principales n'aient à gérer des conflits au moment du merge.) Du coup ça séquentialise tout, une PR de 100 lignes qui est triviale à relire et intégrer est bloquée pendant des semaines car une PR grosse et compliquée bloque toute la file. Pas terrible !

Le git flow indique que le développement de chaque PR se fait dans une branche à part, et que chaque PR peut être mergée dans `dev` dès qu'elle est prête. Quand on a prévu de faire une release, on fait une branche spécifique pour la release, et on peut facilement en retirer des "PRs mineures" dont on ne veut pas pour la release, ou y intégrer après-coup une "PR principale" qui n'était pas encore prête quand on a fait la branche (ou des fixes restants pour une PR mergée alors que la QA n'était pas tout à fait terminée). Ça permet de ne pas bloquer les merges dans `dev`, et d'intégrer les choses dès qu'elles sont prêtes.

Pour résumer : une PR très petite/mineure peut être traitée rapidement, et il faudrait le merger le plus rapidement possible. Pour cela, il faut partir du principe qu'une PR est mergée dès qu'elle est prête, et que ce sont aux autres PRs pas-encore-mergées de gérer le rebase. C'est précisément à ça que servent les séparations entre branches de features, de développement, et de release, donc autant s'en servir.
 
# A faire avant de fermer le ticket : 

- [ ] Je pense qu'il faudra mettre à jour la documentation concernant le workflow
- [x] Il faudrait peut-être lister les objectifs pour les prochaines versions dans le Wiki Github ou en créant des Projects GH

**Comment by artragis** [comment]
ping @sandhose 

à une époque on avait une différenciation 

- dev
- version_en_beta

faudrait-il repasser par là?

**Comment by gasche** [comment]
Pour moi, quand tu commences à te dire "ça c'est pour la beta de v35", il faudrait avoir une branche `release-v35` qui sert à contenir l'état courant de ce que comptes releaser à terme comme la v35. C'est tout à fait normal de merger un truc dans `dev` et de le remerger dans `release-v35` immédiatement après, ou de faire des `revert` sur v35 pour virer des merges dont on ne veut pas dans cette branche.

Un coût de ça c'est qu'il peut se poser la question de savoir: pour une feature prévue pour v35, est-ce que je fais la QA par-dessus v35 ou par-dessus dev ? Je dirais de faire la QA par-dessus dev, et de refaire une étape de QA simplifiée par-dessus v35 quand on y merge des choses ou juste avant la vraie release. (Plus on pousse la QA dans des tests unitaires qui sont faits automatiquements dans toutes les branches, moins la question se pose.)

**Comment by A-312** [comment]
> À l'époque j'étais dispo pour contribuer, maintenant je suis pris par le boulot, donc je ne ferai rien avant la prochaine poussée d'envie, alors qu'aurais pu continuer mes refactorings dans les jours qui ont suivi, si les premiers trucs avaient été mergés.

+1 - Ça serait bien de palier ce problème. Je le rencontre aussi quand je souhaite corriger des bugs sur le front mais pour respecter l'atomicité, je dois faire 2 PR, alors que je serais prêt à faire le changement dans la fouler. :(

**Comment by gasche** [comment]
Pour ton problème d'atomicité, mon conseil serait de te faire une branche de "bugfixes" avec un commit par bug, et ensuite de découper en PRs séparées (pour chaque commit ou grappes de commit, tu recrées une branche à partir de trunk et tu cherry-pick le(s) commit(s) en question). Tu peux continuer à corriger dans ta branches "bugfixes" (qui n'est jamais soumise en tant que telle) pendant que les PRs sont gérées.

**Comment by A-312** [comment]
> (pour chaque commit ou grappes de commit, tu recrées une branche à partir de trunk et tu cherry-pick le(s) commit(s) en question).

Je ne maîtrise pas cette partie, c'est comme expliqué ici : https://stackoverflow.com/questions/2816715/branch-from-a-previous-commit-using-git et ici : https://stackoverflow.com/questions/8483983/how-to-create-the-branch-from-specific-commit-in-different-branch/8491176 ?

**Comment by artragis** [comment]
je pense que les choses se sont bien améliorées ici. Peut-on fermer le ticket?

**Comment by Situphen** [comment]
Je trouve que tu as bien éclairci les choses dans le MP et dans [le Zest Of Dev 10](https://zestedesavoir.com/billets/2902/chronique-zest-of-dev-10/) !

- Je pense qu'il faudra mettre à jour la documentation concernant le workflow
- Il faudrait peut-être lister les objectifs pour les prochaines versions dans le Wiki Github ou en créant des Projects GH
- Réorganiser des Zest'Meetings (peut-être tous les mois car toutes les 2 semaines c'était probablement trop ambitieux)
- Peut-être utiliser plus l'assignement des tickets et des PRs ?
- Mettre le tag Zombie sur les PRs dont l'auteur n'est plus actif --> ça permet de bien distinguer les PRs QAtisable maintenant des autres PRs, et ça permet de relancer les auteurs ou de reprendre leur travail)
- Faire des versions chaque mois ou deux mois ? Versions + petites + fréquentes, on a + l'impression d'avancer :)

:)

**Comment by gasche** [comment]
Pour ma part je n'ai pas re-contribué au ZdS depuis ce ticket donc je ne peux pas juger de la situation actuelle. Si vous pensez que c'est effectivement amélioré, n'hésitez pas à fermer.

**Comment by artragis** [comment]
j'ai modifié le ticket initial pour mettre les deux premiers points en "tâche à faire".

pour les zest meeting, j'en ferai un en janvier, j'ai eu un mois de novembre difficile, impossible d'organiser ça, et là décembre est bien entamé.

pour les versions : si tu arrives à être suffisamment disponible pour pallier aux moments où sandhose n'est pas là, oui on pourra être bien plus réactifs.
