### ISSUE TITLE
Une reconnaissance officielle pour les relecteurs

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5102]
- Pouvoir lier des membres à des contenus en tant que relecteurs ou validateurs
- Mettre en valeur ces membres sur la page du contenu
- Lister les validations et les relectures sur la page de profil d'un membre
> [Ici](https://zestedesavoir.com/forums/sujet/10621/auteurs-quest-ce-qui-vous-motiverait/?page=5#p180674), je suggérais qu'il serait motivant pour les relecteurs de contenu (y compris les validateurs) d'avoir une reconnaissance officielle. L'objectif n'est pas de remettre une médaille ou de cajoler les egos (bien que ça pourrait être bénéfique à ZdS) mais de reconnaître **littéralement** le travail accompli.
> 
> Pour ma part, j'apprécierais pouvoir pointer vers ma page de profil et montrer lors d'une candidature à un projet/une entreprise le travail que j'accompli ici.
> 
> En pratique, cela pourrait se faire en ajoutant deux champs de métadonnées aux contenus : `validateur` et `relecteurs`.
> 
> Qu'en pensez-vous ?

Sujet : https://zestedesavoir.com/forums/sujet/11597/une-reconnaissance-officielle-pour-les-relecteurs/
*Envoyé depuis Zeste de Savoir*

**Comment by firm1** [comment]
Je prend ce ticket. J'ai déjà commencé pas mal de boulot dessus.

**Comment by A-312** [comment]
Si jamais, on a un mot à dire, j'aimerai proposer une mise en page des remerciements plus humain et sincère : 

> Un textarea comme "introduction" et "conclusion" ? Qui devra être rempli manuellement avant la publication permettant de faire un remerciement personnel et adapté à vos efforts pour éviter les malentendus. Quand un pseudo est @*ping* dans ce textarea, ça le détecte et l’ajoute en remerciement sur son profil.
> 
> Puis sur le profil rajouter un bloc "Remerciement" présenté comme un bloc "tuto" ou "article".

On a deux écoles de remerciement : 

 - Une simple liste : 
   > Merci à Pierre, Jack et Paul.

vs

 - Mon idée :
    > Merci à Pierre qui m'a relu plusieurs fois, jack m'a grandement aidé pour la correction de l'orthographe ! Paul à apporter les images, il fait un très beau travail pour illustrer ce tutoriel.

**Comment by firm1** [comment]
A propos des remerciements, je me demande s'il faut vraiment que ce soit des "remerciements". Je veux dire, à partir faire une liste a puce automatiques de personnes a remercier (en plus des potentiels remerciements personnels que l'auteur aurait envie d'inclure dans le contenu), je pense que ça ferai trop bloc formel.

Je pensais tout simplement à noter dans le tutoriels, en desous de "Auteur: firm1", le texte "Cet article à été relu par x contributeurs". Le "x contributeur étant un lien" qui ouvre une fenêtre modale avec la liste des contributeurs.

Plutot que d'avoir un long texte de remerciement que l'on saura de toute façon automatiquement généré, je préfère un lien qui ne prend pas de place et qui donne la même info.

**Comment by firm1** [comment]
C'est mergé, on ferme.
