### ISSUE TITLE
Utiliser pipenv ?

### ISSUE THREAD

**Issue by Vayel** [zestedesavoir/zds-site#5104]
[pipenv](https://pipenv.readthedocs.io/en/latest/) semble devenir le standard pour installer des applications Python. Peut-être cela vaut-il le coût d'y jeter un oeil ?

**Comment by pierre-24** [comment]
Tant qu'on pointe bien qu'il faut utiliser  `--ignore-pipfile` sauf mise à jour explicite, ça me va. Autrement, on retombe dans ce comportement étrange (de mon point de vue) ou les programmes de ce type (oui, npm, c'est toi que je vise, mais pipenv fait pareil) se permetent de mettre à jour le `.lock` au moindre `pipenv install`.

Ça permettrait aussi de se débarasser du `setup.py` qui n'est plus à jour (pour toute version de pip >= 10.0, si je dis pas de bétises), et qui ne sert de toute façon à rien (zds n'étant pas un programme qui s'installe ou une librairie, et on ne balance pas zds sur pypi).

**Comment by artragis** [comment]
On s'en sort sans pb avec pip, je nettoie le backlog. 

L'idée est intéressante mais elle va juste moisire encore des années avant d'intéresser qui que ce soit.

**Comment by pierre-24** [comment]
T'façon, pipenv n'est plus maintenu, et force une version de python :/

**Comment by Vayel** [comment]
Je suis personnellement passé à https://python-poetry.org/ (pour info).
