### ISSUE TITLE
Problème de compatibilité python 3.7

### ISSUE THREAD

**Issue by Vayel** [zestedesavoir/zds-site#5105]
Je suis sous Archlinux et j'ai suivi la procédure d'installation. Cependant, j'obtiens : 

```
$ source zdsenv/bin/activate
$ make zmd-start && make run-back
...
  File "/home/vincent/Documents/zds/zds-site/zds/settings/dev.py", line 1, in <module>
    from colorlog import ColoredFormatter
ModuleNotFoundError: No module named 'colorlog'
make: *** [Makefile:51: run-back] Error 1
```

J'ai donc installé ce module à la main (`pip install colorlog`). Mais j'obtiens alors : 

```
$ make zmd-start && make run-back
...
  File "/home/vincent/Documents/zds/zds-site/zdsenv/lib/python3.7/site-packages/django/contrib/admin/widgets.py", line 152
    '%s=%s' % (k, v) for k, v in params.items(),
    ^
SyntaxError: Generator expression must be parenthesized
```

Comme vous pouvez le voir, j'utilise Python 3.7.

Ma branche semble à jour : 

```
$ git log
commit 5c2d2847d44f930ded0d10ace746c5ac310c05c3 (HEAD -> master, upstream/master)
Author: Antoine Motet <antoine.motet@gmail.com>
Date:   Sun Nov 4 22:45:11 2018 +0100

    Réindente et corrige divers templates
    
    Fait avec https://github.com/motet-a/jinjalint.
    
    Alors comme il n’y a pas de “styleguide” précisement documenté, j’ai essayé
    de suivre le style utilisé un peu partout.
...
```

Merci !

**Comment by Vayel** [comment]
Apparemment, c'est normal : https://stackoverflow.com/questions/48822571/syntaxerror-generator-expression-must-be-parenthezised-python-manage-py-migra

Ce serait sympa de vérifier la version de Python à l'installation.

**Comment by pierre-24** [comment]
Oui, j'avais constaté ça à l'époque. Il faudrait qu'on passe à Django 2 pour régler le problème, semblerait :/

**Comment by artragis** [comment]
ok, je fais la branche release v28 dans la journée puis on commence le travail de django 2.x si ça commence à devenir intéressant d'investir du temps dans ça.

**Comment by artragis** [comment]
je ferme, on a une tâche pour django 2.x.
