### ISSUE TITLE
[v27.3] Pas de pseudo ni d'avatar sur les notifications de MP

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5106]
Depuis la v27.3, je n'ai plus le nom de l'utilisateur ni l'avatar qui s'affichent dans mes notifications de nouveau message privé. Par contre, je les ai bien avec l'extension Firefox ZDS-Notificateur.

![Capture d'écran](https://user-images.githubusercontent.com/6664636/48664707-15bbd400-eaa3-11e8-965c-0281935701fe.png)

Voici l'HTML qui pose problème : 

```html
<li>
    <a href="/mp/21703/la-v28-un-peu-dorganisation-pour-eviter-les-cafouillages-de-la-273/messages/?page=1#p90195">
        <img src="" alt="" class="avatar">
        <span class="username"></span>
        <span class="date">Il y a 27 minutes</span>
        <span class="topic">la v28, un peu d&#39;organisation pour éviter les cafouillages de la 27.3 </span>
    </a>
</li>
```

**Comment by AmarOk1412** [comment]
Hmm etrange, perso j'ai bien l'avatar et le titre (Firefox 65).

**Comment by Situphen** [comment]
Oui, ça m'étonne aussi ! Pourtant j'ai bien vérifié dans l'HTML reçu par mon navigateur avec Ctrl+U et pas seulement dans l'explorateur quoi. J'ai aussi bien pensé à faire Ctrl+F5 pour vider mon cache !

**Comment by artragis** [comment]
je le mets en bloquant pour la v28

**Comment by Situphen** [comment]
@artragis toi aussi tu as le bug ?

**Comment by artragis** [comment]
ping moi quelque part et je vérifierai.

**Comment by artragis** [comment]
bug vérifié.
