### ISSUE TITLE
Le rendu des maths est cassé

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#5111]
Bonsoir,

Après la mise à jour du markdown qui avait un peu perturbé les formules, voici que le rendu des maths est cassé. Regardez un peu :

$$ \mu \cdot \mathrm{d}l \cdot \frac{\partial^2 z}{\partial t^2 }(x,t) = T  \cdot \sin\theta(x+\mathrm{d} x,t) - T \cdot \sin\theta(x,t) ~~~~~~~~~~~~~(1) $$

$$ \int_0^1 \exp x \mathrm{d} x $$

On remarque différents problèmes :

* toutes les lettres sont en romain au lieu de l'italique (?!),
* les barres de fraction n'apparaissent plus (??!!).

J'ai l'impression que la tripaille derrière les formules a changé, du moins chez moi (Firefox 63 sous Linux Mint). En cliquant droit, je n'ai plus le petit menu sympathique où je peux visualiser le code LaTeX par exemple.

Heureusement, ça n'affecte pas les contenus publiés, mais c'est assez critique pour les auteurs de contenus scientifiques, honnêtement. Je cherche d'où ça vient exactement, mais si quelqu'un à la réponse, je suis preneur pour qu'on puisse corriger au plus vite.

Édit. : j'ai l'impression que les styles de KaTeX sont mal configurés, mais comme je connais mal, j'ai du mal à trouver pourquoi.

Sujet : https://zestedesavoir.com/forums/sujet/11615/le-rendu-des-maths-est-casse/
*Envoyé depuis Zeste de Savoir*

**Comment by artragis** [comment]
je ne comprends pas non plus nous n'avons pas changé la version de katex, car pour l'instant la 0.10 casse le rendu.

Après on put toujours voir mais bon.

**Comment by Arnaud-D** [comment]
Merci pour avoir remonté mon rapport de bug ici. :-)

J'ai fait quelques tests :
  
1. Cela ne semble pas venir de KaTeX en soi, puisque que mon exemple fonctionne avec le rendu du [site de KaTeX](https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22macros%22%3A%7B%22%5C%5Cf%22%3A%22f(%231)%22%7D%2C%22code%22%3A%22%5C%5Cmu%20%5C%5Ccdot%20%5C%5Cmathrm%7Bd%7Dl%20%5C%5Ccdot%20%5C%5Cfrac%7B%5C%5Cpartial%5E2%20z%7D%7B%5C%5Cpartial%20t%5E2%20%7D(x%2Ct)%20%3D%20T%20%20%5C%5Ccdot%20%5C%5Csin%5C%5Ctheta(x%2B%5C%5Cmathrm%7Bd%7D%20x%2Ct)%20-%20T%20%5C%5Ccdot%20%5C%5Csin%5C%5Ctheta(x%2Ct)%20~~~~~~~~~~~~~(1)%22%7D). Testé avec Chrome et Firefox, dans des versions récentes.
2. Sur la bêta, le rendu semble correct : [exemple](https://beta.zestedesavoir.com/forums/sujet/10686/test/).
3. Il y a des différences sur le style de la bêta et celui de la prod pour la même formule. Par exemple :
      * sur la bêta, rendu correct (notez le `mathit`) :
        `<span class="mord mathit" style="margin-right:0.13889em;">T</span>`
      * sur la prod, rendu incorrect (notez le `mathdefault`) :
        `<span class="mord mathdefault" style="margin-right:0.13889em;">T</span>`

Je penche donc sur un problème de configuration du serveur de prod ou quelque chose du même acabi.

Je continue à chercher, mais je pense que je vais bientôt être limité par ma méconnaissance du fonctionnement de ZdS.

**Comment by artragis** [comment]
Raah, ça ressemble vachement à un pb avec zmarkdown ping @vhf ça ressemble àc e qu'il se passe sur ma PR avec l'upgrade de rehype-katex

**Comment by vhf** [comment]
Quand ça : https://github.com/zestedesavoir/zmarkdown/pull/297 sera réglé, je déploierai sur la beta et si c'est bon sur la beta je mettrai ça en prod.

**Comment by Arnaud-D** [comment]
Comment peut-on avoir un problème de zmarkdown sur la prod et pas sur la bêta ?

**Comment by vhf** [comment]
@Arnaud-D La beta est souvent en avance sur la prod.

**Comment by vhf** [comment]
Déployé sur la beta. Mettez le CSS pour katex 0.10 sur la beta, allez tester là-bas et dites-moi si les maths sont correctes (katex 0.10). Il y a aussi des correctifs pour les tables ( https://github.com/zestedesavoir/zmarkdown/issues/290 ).

Si c'est bon je déploie en prod.

**Comment by artragis** [comment]
ok, on va devoir faire une 27.4 pour ça.

**Comment by pierre-24** [comment]
Alors, je sais pas si c'est nous ou côté KaTeX, mais sur [ce message](https://beta.zestedesavoir.com/forums/sujet/10686/test/?page=1#p179597) ... On devrait normalement avoir des lignes horizontales et verticales dans le tableau, comme démontré [là](https://katex.org/docs/supported.html#environments). En particulier, le dernier tableau du message est un copier-collé de l'exemple suivant:

![screenshot from 2018-11-23 15-32-44](https://user-images.githubusercontent.com/7889675/48948597-4b463e80-ef35-11e8-9590-a61d181f5f32.png)

Quand on regarde le code HTML, on voit qu'il y a bien des délimiteur (`<span class="vertical-separator" ...>` par exemple) qui sont ajouté. Je supose un problème de CSS :)

**Comment by pierre-24** [comment]
(au cas ou ça serait lié, Firefox/63.0, Ubuntu 18.10).

**Comment by artragis** [comment]
non mais ça marchera pas pour l'instant : on n' pas mis katex à jour sur la béta côté front. Je m'occupe de brancher et de faire ça ce soir.

**Comment by artragis** [comment]
salut tout le monde

si vous pouviez passer [sur la béta](https://beta.zestedesavoir.com/forums/sujet/10686/test/?page=1#p179599) pour tester les maths histoire qu'on puisse s'assurer que le nouveau katex fonctionne bien.

**Comment by Arnaud-D** [comment]
À première vue, ça marche bien pour moi.

**Comment by artragis** [comment]
ok, merci.
@vhf et @sandhose vous pouvez vous coordonner pour mettre à jour zmd sur la prod et mettre en place la v27.4? une fois que ça sera fait, je ferai un cherry-pick pour la branche master

**Comment by vhf** [comment]
Yep, ici il est plus simple de déléguer que coordonner.

@sandhose Lors du déploiement il faudrait faire ceci:

```sh
## as root

cd /opt/zmd
# on sait jamais
mv package.json package.json.bak
mv package-lock.json package-lock.json.bak

wget https://gist.githubusercontent.com/vhf/4036bfad7da9b5702d5a9d04b07f82e3/raw/f44f32d4ac114e9fd08b08847f6b54ed0119435f/package-lock.json
wget https://gist.githubusercontent.com/vhf/4036bfad7da9b5702d5a9d04b07f82e3/raw/f44f32d4ac114e9fd08b08847f6b54ed0119435f/package.json

npm install
service zmd reload
```
