### ISSUE TITLE
Balise youtube : Intégrer le chat lorsqu'il s'agit d'un live

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5115]
Balise youtube : Intégrer le chat lorsqu'il s'agit d'un live

Raison : L'utilisateur n'a aucun intérêt de reste sur zeste de savoir, s'il ne voit pas le chat.

http://lecerf.raphael.free.fr/index.php?diffuser-un-live-de-youtube-avec-son-chat-en-simultanee-sur-son-blog.html

**Comment by artragis** [comment]
à voir sur zmd du coup (composants: zmarkdown et remark-iframe)

**Comment by Situphen** [comment]
Ça a vraiment un intérêt ? J'ai jamais vu l'intégration d'une vidéo en live sur Zeste de Savoir, et je ne pense pas que ce soit très courant.

> L'utilisateur n'a aucun intérêt de reste sur zeste de savoir, s'il ne voit pas le chat.

Je pense que ça dépend beaucoup du type de live, certains n'ont vraiment pas besoin de chat. Et même s'il y en a besoin, je ne pense pas que ce soit problématique que l'utilisateur aille directement sur Youtube. Notre but n'est pas de garder à tout pris les utilisateurs sur ZdS. D'ailleurs, même en intégrant un chat sur ZdS je pense que l'utilisateur aura tout intérêt pour son confort d'aller directement sur Youtube.

Aussi, contrairement à une vidéo immuable, on ne contrôle pas ce qui est écrit dans le chat et il arrive très souvent que des personnes mettent des commentaires très borderline. On ne veut pas forcément voir ça directement sur ZdS...

**Comment by artragis** [comment]
Comme je le disais, ça peut être un élément à regarder du côté de remark-iframes. MAIS je pense qu'on ne l'ajoutera pas dans zds. 

Peux-tu créer un ticket dans zmarkdown pour qu'on puisse mettre cette fonctionnalité dans le plugin?

**Comment by A-312** [comment]
Il ne faut pas une partie css côté zds ?

**Comment by artragis** [comment]
on ne le mettra pas dans zds.
