### ISSUE TITLE
Améliorer l'historique d'édition sur le forum

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5116]
Bonjour,

L'historique d'édition d'un message n'est pas claire, aujourd'hui j'ai accidentellement remis la version originale d'un message. J'ai du m'y reprendre à 2 fois avant de remettre la bonne version.

Je propose de voir la version actuel et non la version "avant édition". Ca permet d'être plus compréhensible.

# Une édition :

Au lieu de :

 | Date | Éditeurs | Version avant édition
 | - | - | - 
 | Il y a 3 minutes | A-312 | (VOIR - RESTAURER - SUPPRIMER)

Remplacer avec :

| Dénomination | Date | Éditeurs | Action
| - | - | - | - 
Edition 1 | Il y a 3 minutes | A-312 | (Version disponible)
Etat orginal | Il y a 5 minutes | A-312 | (VOIR - RESTAURER - SUPPRIMER)

# Avec plusieurs éditions :

Au lieu de :

 | Date | Éditeurs | Version avant édition
 | - | - | -  
Il y a 3 minutes | A-312 | (VOIR - RESTAURER - SUPPRIMER)
Il y a 9 minutes | A-312 | (VOIR - RESTAURER - SUPPRIMER)
Il y a 13 minutes | A-312 | (VOIR - RESTAURER - SUPPRIMER)

Remplacer avec :

| Dénomination | Date | Éditeurs | Action
| - | - | - | - 
Edition 3 | Il y a 3 minutes | A-312 | (Version disponible)
Edition 2 | Il y a 9 minutes | A-312 | (VOIR - RESTAURER - SUPPRIMER)
Edition 1 | Il y a 13 minutes | A-312 | (VOIR - RESTAURER - SUPPRIMER)
Etat orginal | Il y a 15 minutes | A-312 | (VOIR - RESTAURER - SUPPRIMER)

**Comment by AmauryCarrade** [comment]
En terme d'interface d'historique d'édition, je trouve celle de GitHub très sobre et pratique.

> ![capture d ecran de 2018-11-26 15-39-18](https://user-images.githubusercontent.com/1417570/49021238-76799980-f192-11e8-86b4-4417b13a5b2b.png)

Une liste intégrée directement dans la page, _incluant la version courante_ (et ça je plussoie, c'est beaucoup plus clair !), et les autres éléments affichent un `diff` au clic, qui pourrait contenir pour nous le bouton de restauration/suppression (GitHub ne proposant que la suppression).

Aussi (et c'est quelque chose que je vois souvent sur ZdS) je trouve bien plus lisible le fait de présenter ces données de façon un peu moins tabulaire. Un peu comme le présente GitHub justement. Une interface n'a pas besoin d'être un clone de la base de données. Par exemple : 

Message modifié trois fois | Actions
-------|---------
Modifié par **A-312** il y a 3 minutes |	_(Version actuelle)_
Modifié par **A-312** il y a 9 minutes |	(VOIR – RESTAURER – SUPPRIMER)
Modifié par **A-312** il y a 13 minutes |	(VOIR – RESTAURER – SUPPRIMER)
Créé par **A-312** il y a 15 minutes |	(VOIR – RESTAURER – SUPPRIMER)

Du coup sur le concept de ce ticket je supporte complètement — et je me dis qu'on pourrait presque aller plus loin, si quelqu'un est motivé, et sans forcément trop d'efforts.

**Comment by Situphen** [comment]
> Aussi (et c'est quelque chose que je vois souvent sur ZdS) je trouve bien plus lisible le fait de présenter ces données de façon un peu moins tabulaire.

Je suis d'accord, mais il faut garder en tête que Github a des développeurs employés et nous on n'en a pas :D Ça reste beaucoup plus rapide de créer un petit tableau dont le CSS est déjà présent, que de créer une bulle au survol avec un design très personnalisé :) Surtout que l'édition ce n'est pas ce qui est le plus utilisé

**Comment by AmauryCarrade** [comment]
Ah mais je sais bien, d'ailleurs si tu lis bien je n'en parlais qu'en tant qu'inspiration. Et surtout, ce que j'appelle « de façon un peu moins tabulaire » c'est surtout l'idée de ne pas avoir peur de _rédiger_ des phrases dans les interfaces plutôt que de ne faire que des colonnes qui miment la structure de la base de données derrière. Et ça, ce n'est pas forcément quelque chose de compliqué. [S. Schoger (de RefactoringUI) mentionnait ce point d'ailleurs lui aussi](https://twitter.com/steveschoger/status/997125312411570176), bien qu'en en parlant d'une façon un peu différente.

Ma suggestion principale est sous forme semi-tabulaire, présentée à la fin de mon messsage, remplaçant les trois premières colonnes (dénomination / date / éditeur) par une phrase que je trouve plus claire et agréable à lire (« Créé/Modifié par X il y a Y »). GitHub fait une jolie popup bien intégrée à la page, grand bien lui fasse, je ne dis pas qu'on doit forcément faire pareil. :)

**Comment by A-312** [comment]
Le menu en dropdown ne serait pas à faire avec l'API ?
