### ISSUE TITLE
Travis n'utilise pas la même version de node que nous

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5143]
https://github.com/zestedesavoir/zds-site/blob/0ce8b98fca5972437cb234da1f5c82543eac100b/.travis.yml#L110

On utilise la 10.8.0

**Comment by artragis** [comment]
bien vu.

**Comment by Situphen** [comment]
D'une manière générale, est-ce qu'il ne faudrait pas que Travis CI utilise le même script d'installation que nous ?

**Comment by A-312** [comment]
Où utiliser le même fichier qui contient les numéros de version des dépendances

**Comment by A-312** [comment]
Pourquoi C-Front ?

**Comment by artragis** [comment]
misclick

**Comment by A-312** [comment]
Situphen : Si je souhaite utiliser le même script que le makefile, dois-je enlever la partie ci-dessous ?

----------

```
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
      - libmysqlclient-dev
      - language-pack-fr
      - unzip
      - oracle-java9-set-default
```
Ou dois-je seulement enlever unzip (--> #5144) et oracle-java9-set-default, et vérifier que le script les installe correctement ?

**Comment by A-312** [comment]
Pour jdk doit-on utiliser : https://github.com/sormuras/bach/blob/master/install-jdk.sh ? Comment installer jdk avec du code ?

**Comment by Situphen** [comment]
unzip est pris en charge par le script donc tu peux enlever je pense. Pour java 9, là encore si c'est installé par le script (à vérifier) tu peux l'enlever.

**Comment by A-312** [comment]
Nop mais il devrait : #5144

**Comment by A-312** [comment]
Nop mais il devrait : #5144 et https://docs.zestedesavoir.com/install/extra-install-es.html#installer-java-8

**Comment by Situphen** [comment]
Ok parfait. Par contre vu que tu utilises Debian testing d'après #5144 je préfère préciser : cette version peut être instable, donc quand tu rencontres un bug avec le script d'installation il faut regarder est-ce que c'est à cause d'un paquet par encore stable ou est-ce que c'est dû à une nouveauté de cette version. Si c'est un bug qui sera encore présent lors que la nouvelle version de Debian sera stable, alors il faut le corriger. Si c'est un bug dû à l'instabilité de cette version, la question se pose de corriger ou non le problème. :)

**Comment by A-312** [comment]
J'ai voulu suivre la doc mais ca ne fonctionnait pas. Alors j'ai voulu rajouter testing pour faire fonctionner tout ça mais rien, j'ai enlevé testing tout de suite après.

Je suis allé lire la doc d'elastic search qui indiquait minimum jdk8 ou plus.

J'ai donc pris l'initiative d'installer jdk11.

**Comment by pierre-24** [comment]
J'avoue être parti du principe que de nos jours, tout le monde avait le jdk8. Mauvaise idée ^^ (en plus, y'a un moment dans l'instal ou il faut selectionner le bon java, pensez y pour Travis)
