### ISSUE TITLE
elasticsearch : Problème lors de l'édition + nouveau mot

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5146]
Lorsqu'on édite et que le mot n'est pas stocké, elasticsearch ne se rafraîchit pas.

Sur mon espace de dev, il ne prenait pas le mot "avion" vous imaginez !? Parce que je ne l'avais pas assez floodé. 😢 

https://beta.zestedesavoir.com/rechercher/?q=lilicharacocoin&category=&subcategory=&from_library=

https://beta.zestedesavoir.com/forums/sujet/10687/testeditii/

**Comment by pierre-24** [comment]
J'ai [aucune idée du temps de refresh sur la bêta](https://zestedesavoir.com/forums/sujet/11757/elasticsearch-se-rafraichit-apres-de-combien-de-temps-sur-la-beta/) (ou le site, d'ailleurs). Ce que je peux te dire, c'est qu'une édition [marque l'objet](https://github.com/zestedesavoir/zds-site/blob/dev/zds/searchv2/models.py#L222) (sauf cas spécifique) et [qu'il faut ensuite lancer la commande avec `index_flagged` pour réindexer ce qui a été marqué](https://github.com/zestedesavoir/zds-site/blob/dev/zds/searchv2/management/commands/es_manager.py#L57-L73).

Je pense que dans ton cas, c'est juste une question de temps (et que si tu veux le refaire à la maison, il faut que tu le face manuelement, [voir documentation](https://docs.zestedesavoir.com/back-end/searchv2.html#indexer-les-donnees-de-zds)).

**Comment by A-312** [comment]
J'ai vérifié, l'édition est pris en compte : https://beta.zestedesavoir.com/rechercher/?q=TesteditII&category=&subcategory=&from_library=

**Comment by Situphen** [comment]
Problème résolu du coup ?

**Comment by A-312** [comment]
Nop toujours rien : https://beta.zestedesavoir.com/rechercher/?q=lilicharacocoin&category=&subcategory=&from_library= On devrait voir le sujet TesteditII

**Comment by A-312** [comment]
TODO : Vérifier que l'édition enregistre une demande de MAJ pour elasticsearch. (je ne sais pas à quoi ça ressemble)

**Comment by Situphen** [comment]
Ton sujet a bien été indexé par ElasticSearch car on peut faire une recherche sur le titre ou le sous-titre : https://beta.zestedesavoir.com/rechercher/?q=TesteditII

Par contre j'ai l'impression que le premier message du sujet n'est pas indexé. C'est probablement un problème dans le code, je pense pas que ça ait à avoir avec la bêta.

**Comment by A-312** [comment]
Ah tu sembles avoir raison, je ne trouve pas le mot [adipiscing](https://beta.zestedesavoir.com/forums/sujet/10690/jai-reussi-a-realiser-mon-chalipopopo/) si je le cherche.

**Comment by Arnaud-D** [comment]
Toujours d'actualité avec le passage à Typesense ?

**Comment by Situphen** [comment]
Ça ne semble plus être le cas, donc je ferme !

Si [je cherche « J’ai l’intention de m’acheter une tour qui me satisferait »](https://zestedesavoir.com/rechercher/?q=J%E2%80%99ai+l%E2%80%99intention+de+m%E2%80%99acheter+une+tour+qui+me+satisferait) dans la recherche, le troisième lien est bien [le premier message de ce sujet du forum](https://zestedesavoir.com/forums/sujet/17627/apprendre-a-evaluer-des-configs-gaming-doccasion/?page=1#p256970). (Les deux premiers liens devant car ce sont des contenus donc ils sont favorisés par le système de poids.)
