### ISSUE TITLE
[BETA]  `elasticsearch` erreur 403

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5148]
J'ai une erreur 403 quand je fais : https://beta.zestedesavoir.com/rechercher/?q=CHALIPOPO&category=&subcategory=&from_library=&models=&models=&models=

Je ne sais pas si c'est normal ou pas à vérifier.

**Comment by artragis** [comment]
bug connu (c'était un bug bloquant) il sera résolu lorsque "release_v28" sera en béta
