### ISSUE TITLE
Selenium ne devrait pas être nécessaire pour lancer le serveur

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5150]
Actuellement Selenium est nécessaire pour lancer le serveur alors qu'il n'est présent que dans les tests Python. Le problème provient des tests Python qui sont dans `zds/utils/templatetags/tests` et qu'il faut déplacer dans `zds/utils/tests` !

**Comment by artragis** [comment]
tu e sûr que c'est ce placement qui est la source du pb?

**Comment by Situphen** [comment]
Oui, j'ai testé en local (avec Vagrant et ansible on peut créer très simplement une VM configurée comme un serveur de production) et c'est grâce aux erreurs Django que j'ai pu trouver la source du problème :)

**Comment by artragis** [comment]
ok, je relierai la PR demain et je porterai le fix dans release_v28
