### ISSUE TITLE
Les données statistiques ne sont pas ordonnées

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#5152]
Sur la béta, demandez-moi l'accès au tuto "asp.netmvc"

- allez dans l'édition du tuto
- allez dans "voir les statistiques"
- regardez le graphique "global" 
![graphique](https://user-images.githubusercontent.com/1523653/50046788-b6ed7880-00a9-11e9-8b80-fcfc2999596a.PNG)

il serait bien que la ligne suive le court du temps.

**Comment by Eskimon** [comment]
Il aurait fallu me pinger pour que je vienne ici jeter un oeil ^^

Et je sais pas pourquoi ca fait ca :( j'ai jamais eu ce souci en test local. Une idée de pourquoi le local et la [pré]prod' pourrait avoir un comportement différent sur ce genre de chose ? (je veux dire, après tout c'est les memes lib' pour le front et la même version de python pour le back...)

**Comment by Eskimon** [comment]
Cay réparé, merci @Situphen pour la réactivité :)
