### ISSUE TITLE
Copier l'image/coller non fonctionnel

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#5154]
Connectez-vous

allez sur un message ou un contenu publié
cliquez droit sur un avatar puis "copier l'image"
dans la zone de commentaire faites "ctrl+v" ou clic droit + "coller".

# observé 

## sur windows + firefox

rien ne se passe, aucune erreur dans la console, pour le débugger, ça n'entre même pas dans la branche

## sur windows + edge

dans la console on a "0: Unable to get property 'length' of undefined or null reference"

cette erreur est lancée car la propriété `e.originalEvent.clipboardData.files` vaut `null`.

**Comment by Eskimon** [comment]
"Chez moi ça marche ™" (Firefox 64 win 10)

**Comment by Eskimon** [comment]
Idem, ca marche aussi sur Ubuntu 18 Firefox 64

**Comment by Eskimon** [comment]
(testé en faisant un "clic droit copier", puis un "clic droit coller", ainsi qu'avec un ctrl+v)

**Comment by artragis** [comment]
ok, je ne reproduis qu'avec edge https://beta.zestedesavoir.com/forums/sujet/10683/test/?page=1#p179615

**Comment by Situphen** [comment]
J'ai trouvé un ticket sur le bugtracker de Microsoft Edge et ce commentaire pourrait nous aider je pense : https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15823907/#comment-10

**Comment by Situphen** [comment]
```
console.log(e.originalEvent.clipboardData);
```

Firefox sur Linux : 

```
DataTransfer { dropEffect: "none", effectAllowed: "uninitialized", items: DataTransferItemList(2), types: (2) […], files: FileList(1), mozItemCount: 1, mozCursor: "auto", mozUserCancelled: false, mozSourceNode: null }
```

Edge sur Windows : 

```
[object DataTransfer]: {dropEffect: "", effectAllowed: "", files: null, items: Object, types: Object}
```

**Comment by A-312** [comment]
> ## sur windows + firefox
> rien ne se passe, aucune erreur dans la console, pour le débugger, ça n'entre même pas dans la branche

Rien ne se passe dans le sens qu'il y a aucune erreur et que tout fonctionne correctement ?

**Comment by Situphen** [comment]
Je viens de regarder et avec Edge sur Windows, on peut copier/coller des images dans l'éditeur de GitHub.

Ils utilisent une balise `<file-attachment>` qui englobe le `<textarea>`

**Comment by A-312** [comment]
~~Ca ne fonctionne pas sur firefox (win 10) quand je copie une image à partir du bureau ou d'un dossier. J'obtiens : `ev.originalEvent.clipboardData.length` vaut `undefined`, si~~ je copie une image à partir de firefox ça fonctionne.

Comment as-tu essayé @Eskimon ?

**Comment by Eskimon** [comment]
Comme dit plus haut, clic droit copier/coller. Mais seulement dans le navigateur, pas dans l'explorateur de fichier
________________________________

**Comment by A-312** [comment]
~~Sous firefox, "le bon côté" c'est que imgur et github ont le même soucis. Je n'ai pas trouvé de solution pour firefox.~~

**Comment by Situphen** [comment]
> je copie une image à partir du bureau ou d'un dossier

tu fais clic droit + copier sur le fichier ? ou tu l'ouvres dans un logiciel qui ouvre les images puis tu fais clic droit + copier ?

**Comment by A-312** [comment]
Oh! En faite sur chrome non plus, je pensais qu'on pouvait copier/coller une image en copiant un fichier...

Donc : Firefox Win 10 : Ok pour moi

**Comment by Eskimon** [comment]
Sous Ubuntu quand je fais ça ça copie juste le chemin du fichier, pas son contenu (et idem sous GitHub)
________________________________

**Comment by A-312** [comment]
Tu voulais faire quand ton fix @artragis ? J'ai peut être quelques choses pour faire une PR dans ~30min

**Comment by A-312** [comment]
[HS]Pourquoi tu ne vérifies pas le type de fichier en Javascript ? Au lieu d'envoyer un pdf au serveur^^"

Il faut faire comme [ça](https://github.com/A-312/chat-client/blob/master/javascript/chat.js#L140) : (file.type.indexOf("image") === 0)[/HS] ---> #5176

**Comment by A-312** [comment]
Je PR bientôt normalement, sous Edge il faut utiliser `items` et non `files`.
![image](https://user-images.githubusercontent.com/18501150/50226432-70e32e00-03a3-11e9-9682-ec787dc70764.png)

**EDIT :** Je suis le premier avion qui a volé sur le territoire paste d'Edge ! 
![image](https://user-images.githubusercontent.com/18501150/50227586-58c0de00-03a6-11e9-8738-6a6246aa5b25.png)
