### ISSUE TITLE
Erreurs 500 pour "Ajouter en Une"

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5156]
Sur certains contenus, "Ajouter en Une" renvoie une erreur 500

Sujet : https://zestedesavoir.com/forums/sujet/11676/ajouter-en-une/#p195045
*Envoyé depuis Zeste de Savoir*

**Comment by Situphen** [comment]
D'après Sentry, l'erreur est `MultipleObjectsReturned: get() returned more than one PublishedContent -- it returned 2!` et elle provient de [la ligne 69 du fichier `zds/featured/views.py`](https://github.com/zestedesavoir/zds-site/blob/c017e008e3e04908d4642e954b441c2f9f1b4423/zds/featured/views.py#L69) : `content = PublishedContent.objects.get(content__pk=int(content_id))`

**Comment by artragis** [comment]
forcément. Il faut donc : 

- ajouter le filtre `must_redirect=False`
- utiliser la combinaison `filter().first()` plutôt que `get()`

**Comment by Situphen** [comment]
@artragis tu peux m'expliquer pourquoi `content_pk` n'est pas unique ? :)

**Comment by artragis** [comment]
Tuto publié deux fois sous deux noms différents du coup on garde une trace de l'ancien objet `PublishedContent`.

Cela permet de créer la redirection quand une personne possède le vieux lien.

**Comment by arobase-che** [comment]
🎉 Je viens de reproduire l'erreur en local 🥳

Du coup, je m'en charge si ça dérange personne. Je pense pour une v29 donc j'ai le temps mais d'ici la fin du mois, j'aurais fini. Ça me permettra de mettre un petit pied dans le dev de zds (j'ai surtout fais zmarkdown pour l'instant).

À bientôt \o

**Comment by artragis** [comment]
impec, welcome

**Comment by A-312** [comment]
V28.1 si ça arrive dans moins d'un mois non ? Enfin je ne connais pas les dates de la v29 et v28.1

**Comment by artragis** [comment]
ya pas de date précise on est un peu comme Debian : Quand c'est prêt.

Laissons déjà le tempse à @sandhose de déployer la v28.

**Comment by A-312** [comment]
Ah j'avais cru que la v28 était en ligne.
