### ISSUE TITLE
Mettre le bouton des statiques sur la version en ligne

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5159]
Mettre le bouton des statiques sur la version en ligne des tutos car actuellement seulement sur la version brouillon.

**Comment by Situphen** [comment]
Seulement les auteurs et le staff ont accès aux statistiques, c'est donc cohérent que le bouton ne soit présent que sur la version en brouillon du contenu et non pas la version en ligne, à mon avis.

**Comment by artragis** [comment]
je valide, mais ça sera pour la v28.1

le truc @Situphen  c'est que les auteurs n'arrivent pas forcément sur le tuto via la version brouillon. Ils peuvent être sur la page des commentaires. C'est un peu de *ease of access*. Pas spécialement important dans un premier temps mais utile.

**Comment by A-312** [comment]
Oui comme l'a dit artragis je ne comprenais pas pourquoi je n'avais pas le bouton, avant de me dire "ça doit être sur la version brouillant".

**Comment by Situphen** [comment]
À la vue des commentaires du MP, je pense que ça devrait peut-être être en v28

**Comment by A-312** [comment]
Je m'en occupe
