### ISSUE TITLE
Sauvegarder les discussions utiles

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#516]
Aujourd'hui on a une paire de discussions utiles en cours sur la bêta (en particulier 2 ou 3 sur des issues)

Il faudra penser à les sauvegarder avant de passer à la bêta publique, ce serait dommage d'avoir à refaire les débats et/ou re-chercher des ressources :)

**Comment by firm1** [comment]
Vu l'état de la base beta, faudra tout simplement faire un snapshot de la bd et virer tout ce qui peut être inutile.

Au final il y'a plein de truc interessante sur cette beta.

**Comment by Alex-D** [comment]
Faire un serveur à l'arrache sur beta.zestedesavoir.com ? avec accès limité et tout ?

**Comment by geoffreyc** [comment]
Quezako?

**Comment by cgabard** [comment]
Vu qu'on fait une deuxieme beta, effectivement on a encore un peu de temps mais effectivement il suffit peut etre de faire un snapshot de la beta niveau base et, à la limite, la mettre sur la préprod les premieres semaines le temps de récupérer ce qui nous interesse

**Comment by SpaceFox** [comment]
Pas possible : je vais avoir besoin de la préprod pour faire des tests de
perfs dès que la branche d'intégration sera mergée.

**Comment by geoffreyc** [comment]
tant qu'on garde une copie de la DB quelque part ya pas de soucis si?

2014-06-02 12:43 GMT+01:00 SpaceFox notifications@github.com:

**Comment by firm1** [comment]
J'aimerai qu'on évite de discuter sur github (qui est maintenant
open-source) des trucs que le grand public ne peut pas faire.

C'est une tache a faire, mais on le référence au mauvais endroit.

**Comment by Alex-D** [comment]
Du coup dans la lignée de @firm1 je ferme ce ticket. Cette discussion doit avoir lieu en interne.
