### ISSUE TITLE
La liste des filtres a changé d'ordre pour les listes de contenus

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5164]
Dans la liste des contenus d'un utilisateur, l'ordre des filtres a changé : 

![Avant](https://user-images.githubusercontent.com/6664636/50146370-dc4dd280-02b3-11e9-9a09-cbdbb5030eb5.png)

![Après](https://user-images.githubusercontent.com/6664636/50146409-ee2f7580-02b3-11e9-8c88-ef170be56fe7.png)

Pages : 

- `https://beta.zestedesavoir.com/contenus/tutoriels/<pk de l'utilisateur>/`
- `https://beta.zestedesavoir.com/contenus/articles/<pk de l'utilisateur>/`

Vue en question : https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/contents.py#L1866

Gabarit en question : https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/index.html#L174

**Comment by artragis** [comment]
régression => bloquant car c'est un effet de bord non désiré d'un refacto.

**Comment by A-312** [comment]
Il faut remplacer :
```py
for filter_ in list(self.authorized_filters.keys()):
```

Par : 
```py
filterKeys = ['public', 'validation', 'beta', 'redaction']
for filter_ in filterKeys:
```

c'est bien ça ?

**Comment by artragis** [comment]
py35 => les dico ne sont pas ordonnés
py36 => les dicos sont ordonnées. 

le vrai fix consiste donc à utiliser `collections.OrderedDict` comme ça ça lisse les différences entre les versions, sans avoir à recréer des sous collections.
