### ISSUE TITLE
Le "+" sous l'avatar n'est pas centré sur Firefox

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5166]
Sous Firefox il est 1 pixel trop bas.

## Firefox : 

![image](https://user-images.githubusercontent.com/18501150/50149818-7b76c800-02bc-11e9-8fe1-8ee535a12b59.png)

## Chrome : 

![image](https://user-images.githubusercontent.com/18501150/50149836-86315d00-02bc-11e9-90aa-6d5934460335.png)

Bonne chance. 😅 

(Windows)
![image](https://user-images.githubusercontent.com/18501150/50149901-b7aa2880-02bc-11e9-93a4-cb0a27539d10.png)

**Comment by Situphen** [comment]
On n'est pas à un pixel près :)
