### ISSUE TITLE
Supprimer PHP du serveur

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#517]
Aujourd'hui il semblerait qu'on aie un serveur PHP sur la prod pour servir ceci : http://zestedesavoir.com/author-files/logguni.php

Il faudra penser à supprimer ce script une fois l'authentification HTTP supprimée, puis à supprimer complètement PHP (pas la peine de garder un truc très fréquemment attaqué si on ne s'en sert pas).

**Comment by Coy0te** [comment]
Pour info, il me semble que PHP est également utilisé pour servir les archives des tutos SdZ aux auteurs (pour import). Mais ça change rien à ta remarque, vu que c'est une feature qui ne restera là que temporairement.

**Comment by geoffreyc** [comment]
Pourquoi virer php? Ya aucun avantage a le désinstaller, et si aucunes
"location" nginx n'est paramétré pour l'utiliser il sera de toutes facons
"invisible" au monde extérieur. Je trouve assez bien d'avoir access a PHP
au besoin, si ya besoin de faire des petits scripts rapide etc.

2014-05-13 13:28 GMT+01:00 Coyote notifications@github.com:

**Comment by SpaceFox** [comment]
En fait j'avais en tête le foncitonnement de Apache.

Apache avec mod_php force un mode de gestion des threads Apache
sous-optimal par rapport au fonctionnement normal, d'où l'importance de le
supprimer (ou au moins le désactiver complètement) si on utilise pas PHP.

A vérifier ce que fait nginx de ce côté.

**Comment by geoffreyc** [comment]
En occurrence on utilise php-fpm (socket) et a priori il n'y aurai aucune
contre-indication a le laisser tourner dans le vide. Apres effectivement
tant qu'on a pas de scripts qui tournent, on peut tres bien faire
/etc/init.d/php-fpm stop.

2014-05-13 14:18 GMT+01:00 SpaceFox notifications@github.com:

> En fait j'avais en tête le foncitonnement de Apache.
> 
> Apache avec mod_php force un mode de gestion des threads Apache
> sous-optimal par rapport au fonctionnement normal, d'où l'importance de le
> supprimer (ou au moins le désactiver complètement) si on utilise pas PHP.
> 
> A vérifier ce que fait nginx de ce côté.
>

**Comment by Alex-D** [comment]
Déplacé en interne.
