### ISSUE TITLE
Le bouton "revenir à la vue globale" apparaît même sur les billets, articles et minituto

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#5174]
# Etapes de reproduction

- Ecrire un article
- le publier
- faire en sorte qu'il ait des données statistiques
- visiter la page de statistiques

# comportement observé

le bouton "revenir à la vue globale" apparaît

# comportement désiré

ce bouton n'apparaît pas. Il doit être réservé aux big/mid tuto quand on est dans une vue spécifique à une partie/chapitre

**Comment by A-312** [comment]
Il me semble que je sais faire.

EDIT 1 : 

C'est vraiment utile de faire : "faire en sorte qu'il ait des données statistiques" ?

(J'édite dans : 30min)
