### ISSUE TITLE
Ajouter les unités temporelles sur les graphs des stats

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#5175]
Cete amélioration est demandée par un auteur :  

>  Ce serait bien, aussi, de mettre les unités à côté du temps. Parce que là, j’ai 03:51, mais je ne sais pas si c’est min:sec ou sec:mil

**Comment by A-312** [comment]
Du js :heart: par contre je ne sais pas où ça se passe. Apparemment ici : https://github.com/zestedesavoir/zds-site/blob/ebd52c4be3e48d536cf87c9790b15bbe4e6e328e/assets/js/charts.js

https://www.chartjs.org/ Find. Je regarderais la doc.

Oh je vais m'amuser :D Je pense ajouter 2-3 trucs supplémentaires si ça ne me prend pas trop de temps

**Comment by nils-van-zuijlen** [comment]
~J'ai utilisé chart.js récemment, la gestion des dates se fait avec moment.js.~

~Après, c'est de la configuration à faire.~

Je n'ai pas regardé comment les dates sont gérées ici... En fait c'est fait sur le serveur.

**Comment by A-312** [comment]
Ca serait bien d'ajouter un disclamer sur le fait qu'un bloqueur de pub (réglé pour bloquer l'analytics) diminue les stats ;)

**Comment by A-312** [comment]
Le format actuel est "0:00:00" et non "0:00" comme indiquait ci-dessus (à moins que je n'ai pas cherché au bon endroit)

Ca se passe ici : https://github.com/zestedesavoir/zds-site/blob/ebd52c4be3e48d536cf87c9790b15bbe4e6e328e/zds/utils/templatetags/seconds_to_duration.py#L17

 code | result
-- | --
str(t) | Returns a string in the form [D day[s], ][H]H:MM:SS[.UUUUUU], where D is negative for negative t. (5)

https://docs.python.org/2/library/datetime.html

La solution est surement de faire comme ça : https://stackoverflow.com/a/3700138/2226755

Je ne pourrais pas tester mes changements :S Si quelqu'un pouvait faire la PR à ma place ?

**Comment by artragis** [comment]
comme c'est pour les stats on demandera à situphen un passage express sur la béta quand tu auras fait la PR.
