### ISSUE TITLE
Pourquoi utiliser yarn pour lancer gulp ?

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5179]
Pourquoi utilise-t-on yarn ? Alors qu'on pourrait utiliser directement gulp : 

    npm install --global gulp-cli

Et la doc est périmé : 

```
$ yarn run watch
yarn run v1.12.3
error Command "watch" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

> # Coder plus simplement avec ``watch``
>
> ``watch`` surveille les fichiers SCSS et Javascript lance la tâche ``build`` dès qu'ils sont modifiés. C'est très utile pour le développement car ça permet de ne pas avoir à relancer ``build`` manuellement. Pour lancer cette commande, faites ``make watch-front`` ou ``yarn run watch``. Pour arrêter cette commande, il suffit de presser ``Ctrl+C``.

**Comment by A-312** [comment]
Je voulais ajouter la commande speed et fixsftp dans la doc. :/

**Comment by Situphen** [comment]
C'est une question que je me pose aussi, je ne vois pas trop l'intérêt de Yarn. Je pense que c'est pour avoir le `yarn.lock`, mais ça ne sert pas à grand chose car rien n'est bloqué, Yarn le mettant à jour sans rien demander (à la Windows)

Concernant le raccourci `yarn run watch` (ou en plus court `yarn watch`, ce qui est assez surprenant je trouve) pour gagner un caractère, je l'ai inclus dans ma PR #5122 pour rester cohérent avec le reste.

**Comment by A-312** [comment]
Après #5299, je remplace `yarn` par `npm` :)

**Comment by artragis** [comment]
Un débat a eu lieu sur la PR, on garde yarn.
