### ISSUE TITLE
Les emails sont affichés en clair

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#518]
Il faut rendre ça brouillé pour les bots, sinon un mail qui traine se verra spammé assez rapidement.

Github le fait par exemple sur les profils : https://github.com/Alex-D

```
<a class="email js-obfuscate-email" data-email="%63%6f%6e%74%61%63%74%40%61%6c%65%78%2d%64%2e%66%72" href="mailto:{email}">{email}</a>
```

Il ne manque alors plus qu'un bout de JS pour que ce soit tout bien tout beau. Je ne sais pas si tu peux nous faire quelque chose d'équivalent, ou s'il faut plutôt faire un filtre dans les templates pour protéger ça, car du coup

**Comment by firm1** [comment]
Euh ... je ne comprends pas cette issue, les emails sont dores et déjà brouillés pour les bots. Si tu balance une requête http sur le serveur, tu aura un truc dans ce gout là : `<a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#121;&#111;&#117;&#114;&#64;&#101;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;">&#121;&#111;&#117;&#114;&#64;&#101;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;</a>`
Mais étant donné que les navigateurs sont intelligents, ils te rendent `<a href="mailto:your@email.com">your@email.com</a>`.

Je ne vois donc pas l'interêt de rajouter du JS ici, pour faire comme github, car il suffit d'aller lire le contenu de leur `data-email` pour avoir l'email en tant que bot.

**Comment by firm1** [comment]
Fixé.
