### ISSUE TITLE
Erreur 403 lors d'une recherche ciblée

### ISSUE THREAD

**Issue by rezemika** [zestedesavoir/zds-site#5182]
J'ai voulu faire une recherche (sur la prod, mais il se produit la même chose sur la bêta) pour le mot "récit" en filtrant pour avoir uniquement les "Contenus publiés". Or, j'ai obtenu une erreur 403. Voici l'URL produite : https://zestedesavoir.com/rechercher/?q=r%C3%A9cit&category=&subcategory=&from_library=&models=

**Comment by nils-van-zuijlen** [comment]
Ça a déjà été reporté dans #5107 et corrigé dans #5120

**Comment by rezemika** [comment]
Oh, au temps pour moi, désolé.
