### ISSUE TITLE
Permettre de cropper une miniature pour les tutos

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5190]
Pour faciliter le choix et le cadrage d'une miniature, il faut permettre au membre de pouvoir mettre au bon format leur miniature, lorsqu'il le souhaite (ajout d'un bouton qui affiche l'édition de l'image en cours d'upload).

J'hésite entre : [cropperjs](https://github.com/fengyuanchen/cropperjs) (plus personnalisable) et [Croppie](https://foliotek.github.io/Croppie/) (plus rapide à mettre en place, le CSS de base est très bien).

Je pense partir sur Croppie.

---------

'+ Ajouter une prévisualisation de la zesteCard (Miniature + Titre + Description + Tag).

![image](https://user-images.githubusercontent.com/18501150/50313830-edadff00-04ac-11e9-8167-63eda4b2d18a.png)

**Comment by A-312** [comment]
--> Il faudra surement attendre le refactoring de la création des tutos.

**Comment by artragis** [comment]
non, c'est un peu trop complexe pour le peu que ça apporte.
