### ISSUE TITLE
Impossible de télécharger l'archive d'un tuto en rédaction

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#5192]
# reproduction 

- créez un tuto 
- allez dans la version brouillon mais ne rédigez pas

# comportement observé

dans la side bar il n'y a pas le bouton pour télécharger l'archive

# comportement désiré

le bouton apparait et est fonctionnel

# notes

La régréssion vient sûrement du réfactoring du template de téléchargement des *extra_contents* pour la v27.3.

**Comment by entwanne** [comment]
Salut,

En attendant la résolution, je pose ça là si quelqu'un passe par ici comme moi à la recherche d'une solution pour télécharger l'archive d'un contenu en rédaction : l'url de l'archive zip est `https://zestedesavoir.com/contenus/telecharger/<id>/<slug>`
