### ISSUE TITLE
Fusion de blocs de citations consécutifs

### ISSUE THREAD

**Issue by rezemika** [zestedesavoir/zds-site#5194]
Je ne suis pas certain de savoir si cela provient du zMarkdown ou pas, mais quand, dans un message, on insère deux blocs de citation consécutifs, ceux-ci se retrouvent fusionnés lors du rendu. Cela se produit aussi bien en v27 que sur la bêta en v28.

```markdown
> Bonjour !
Source: Une personne.

> Au revoir !
Source: Une autre personne.
```

Ce qui donne ceci : 

![](https://user-images.githubusercontent.com/1690660/50395939-0ba68880-0767-11e9-865d-ad651fd3fa79.png)

À noter que le rendu est normal lorsqu'on sépare les deux blocs par un lien "vide", comme ceci : `[]()`.

**Comment by artragis** [comment]
J'ai créé un ticket sur zmd.

**Comment by A-312** [comment]
Ce n'était pas volontaire ?

**Comment by artragis** [comment]
vhf le dira sur zmd

**Comment by artragis** [comment]
Je clos car c'est la responsabilité de zmd
