### ISSUE TITLE
Impossible de cocher la case « recevoir un courriel lors de la réception d'un nouveau message privé »

### ISSUE THREAD

**Issue by entwanne** [zestedesavoir/zds-site#5195]
Bonjour,

Suite à la réception d'un message privé j'ai remarqué que je n'avais reçu aucun email pour me le signaler.

Étonné, j'ai regardé du côté des paramètres de mon profil et remarqué que la case « recevoir un courriel lors de la réception d'un nouveau message privé » n'était plus cochée.
J'ai tenter de la recocher puis de valider le formulaire, mais sans effet, elle reste inexorablement décochée.

**Comment by AmauryCarrade** [comment]
J'ai regardé vite, donc à tester plus profondément, mais j'aurais tendance à penser que c'est un problème d'affichage : la valeur `email_for_new_mp` n'est pas mise à jour dans les données initiales du formulaire ici :

https://github.com/zestedesavoir/zds-site/blob/9ee2198db14f0f6c8394dd6459122bd28a05b332/zds/member/forms.py#L260-L284

alors qu'elle est bien transmise :

https://github.com/zestedesavoir/zds-site/blob/1937b8622cc9b9333713045163c246d1f2647bd7/zds/member/views.py#L115-L130

mais elle semble bien être enregistrée dans le profil, au traitement, ici :

https://github.com/zestedesavoir/zds-site/blob/1937b8622cc9b9333713045163c246d1f2647bd7/zds/member/views.py#L155-L168

**Comment by nils-van-zuijlen** [comment]
@AmauryCarrade Ça doit être ça, je ne me souviens pas d'avoir modifié de formulaire dans la PR qui a ajouté cette feature.

Je prends la résolution du bug, mais il faudrait ajouter un test front pour que ça ne se reproduise pas, non ?
