### ISSUE TITLE
Le lien des tags d'un billet lors d'une recherche n'est pas bon

### ISSUE THREAD

**Issue by rezemika** [zestedesavoir/zds-site#5196]
Ça semble similaire au signalement #4409 : lorsqu'on fait une recherche qui renvoie à la fois des contenus (articles / tutos) et des billets, tous les tags ont une URL en "/bibliotheque/", qui ne marche donc pas pour les billets (cliquer dessus renvoie une liste vide, aucun billet n'y apparait).

Cela est vraisemblablement causé par ma PR #4852. J'aurai peut-être le temps de m'y coller demain (ou au pire dans la semaine).

**Comment by artragis** [comment]
est-ce toujours d'actualité sur la béta?

**Comment by rezemika** [comment]
Oui, je viens de tester, l'URL générée est toujours du type `https://beta.zestedesavoir.com/bibliotheque/?tag=<tag>`.

**Comment by A-312** [comment]
Je prends


(Pensez à faire  `python manage.py esanager index_all`, c'est assez utile pour voir les nouveaux résultats xD)

**Comment by rezemika** [comment]
Oups, désolé, j'avais un peu oublié mon compte Github (et j'ai eu quelques problèmes à côté, en plus des partiels). :/
