### ISSUE TITLE
Mettre en évidence lorsque "Cette réponse m'a aidé" ne nous appartient pas (modo)

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5201]
Il faudrait légèrement modifier la couleur des boutons (de façon très légère, une faible nuance bleu, vert ou orange) au bouton non légitime au modo (cad au bouton qui apparaisse en plus). Notamment pour ne pas valider une réponse sur un sujet qui ne nous appartient pas.

Notamment pour :

  - Les boutons sur les messages ; + commentaires
  - Remettre cette version ;
  - Cette réponse m'a aidé.

Suffirait simplement d'ajouter une règle CSS lorsque le sujet ne nous appartient pas.

**Comment by gllmc** [comment]
Plutôt qu'une règle CSS, je pense qu'il serait plus clair de modifier l'intitulé "Cette réponse m'a aidé". Par exemple, on pourrait mettre "Marquer comme utile" pour un modérateur qui n'est pas sur son propre sujet (et éventuellement mettre une fenêtre de confirmation).

À noter qu'on pourrait aussi remplacer, dans le cas d'un marquage par un modérateur, "Cette réponse a aidé l'auteur du sujet" par "[Pseudo] a marqué cette réponse comme utile". Un peu à l'image de ce qui se fait pour les sujets résolus (#4778). Reste à voir si cette modification justifie l'ajout d'une nouvelle jointure.

**Comment by arobase-che** [comment]
Et au passage rajouter une boite de confirmation non ?

**Comment by Situphen** [comment]
Avec le nouveau design des messages, il y a bien une différence entre "Cette réponse m'a aidé" en tant qu'auteur et en tant que modo, donc je ferme.
