### ISSUE TITLE
Connexion via Google+ impossible

### ISSUE THREAD

**Issue by Songbird0** [zestedesavoir/zds-site#5202]
Bonjour,

Après plusieurs tentatives (mobile + PC), je ne parviens toujours pas à me connecter via l'authentification Google.

Je reçois ce message d'erreur en premier lorsque je clique sur `Connexion via Google+`:

![image](https://user-images.githubusercontent.com/13397428/50493096-9fa07a80-0a1b-11e9-80f6-5c4830cb3d12.png)

Et celui-ci lorsque je refresh:

![image](https://user-images.githubusercontent.com/13397428/50493087-957e7c00-0a1b-11e9-8de3-5d842677ccdf.png)

Quelqu'un a déjà pu reproduire ce dysfonctionnement ?

**Comment by A-312** [comment]
Apparemment oui : https://zestedesavoir.com/forums/sujet/12139/erreur-interne-au-serveur-lors-de-la-connexion-avec-google/

**Comment by nils-van-zuijlen** [comment]
Sachant que Google + sera arrêté en avril, je ne pense pas nécessaire de résoudre le problème, si tant est qu'il y a un autre moyen de connexion pour ceux qui n'avaient que ça.

**Comment by nils-van-zuijlen** [comment]
Par contre, il serait intéressant de mettre une pop-up expliquant la nouvelle procédure lors du clic sur le bouton.

**Comment by A-312** [comment]
@nils-van-zuijlen Google + mais pas la connexion google^^

**Comment by Songbird0** [comment]
Salut @nils-van-zuijlen,

En réalité la connexion "via" Google+ hit l'API de Google pour authentifier l'utilisateur avec oAuth. Ca, ça ne changera pas.

**Comment by Songbird0** [comment]
Hello,

Je up ce thread pour savoir si quelqu'un aurait une piste, un élément de réponse concernant l'incapacité des utilisateurs, se servant de cette authentification, à se connecter au site. Étant totalement conscient que ça ne soit pas la priorité des devs, je veux bien tenter de régler le problème avec un peu d'aide de la part d'une âme charitable (parce que moi et le python + Django, ça fait douze malheureusement).

**Comment by A-312** [comment]
Il faudrait dans un premier temps, demander une clé Api (à Google) pour activer l'authentication sur ton espace de dev, la saisir dans tes settings puis essayer de te connecter.

L'erreur apparaîtra dans la console, tu l'as met ici et tu auras sûrement quelqu'un pour te dire où est le soucis.

Tu peux faire une demande ici : https://console.developers.google.com/apis/dashboard La génération sera immédiate

**Comment by Songbird0** [comment]
Ok, c'est noté.

edit: "mon espace de dev" ? Tu veux dire le fork @A-312  ?

Mouais bon, ça m'a l'air d'être un sacré bazar pour appliquer le processus d'installation sous Windows. Je monterai une VM sous Linux dans la semaine pour y jeter un oeil.

**Comment by A-312** [comment]
> "mon espace de dev" ? Tu veux dire le fork @A-312 ?

Oui c'est ça, ensuite tu modifies [dev.py](https://github.com/zestedesavoir/zds-site/tree/dev/zds/settings)

**Comment by Songbird0** [comment]
Petite mise à jour:

Bon pas moyen de boot une VM stable de mon côté, donc la place est libre. Sorry. ^^'

**Comment by artragis** [comment]
tu es sur quel environnement?

**Comment by Songbird0** [comment]
Je suis sous Windows 10, VirtualBox. J'ai testé QEMU, même problème.
Ce n'est pas la première fois que j'ai constaté l'instabilité des VM que je
lance, comme si les iso que je brûlais étaient corrompues ou pas de la
bonne architecture (32 bits pour une architecture 64 bits). Je n'ai pas
cherché plus là jusqu'à maintenant, puisque ça m'empêche littéralement de
faire des tests sous d'autres OS.

Je ne pense pas que ça soit le bon endroit pour en parler, toutefois.



*Feel free to look at my github <https://github.com/Songbird0>!*
*Rust learning (up to date french resources)*
<https://github.com/ctjhoa/rust-learning/blob/master/fr_FR.md>

*Best regards.*

**Comment by artragis** [comment]
Sinon j'ai MAJ la documentation pour utiliser zds sur windows.

**Comment by Songbird0** [comment]
Dans ce cas, ça change tout. J'irai voir, merci !



*Feel free to look at my github <https://github.com/Songbird0>!*
*Rust learning (up to date french resources)*
<https://github.com/ctjhoa/rust-learning/blob/master/fr_FR.md>

*Best regards.*

**Comment by artragis** [comment]
Ce n'est plus reproductible. Il faut dire que @Situphen a trouvé une des causes (une dépendances manquante)
