### ISSUE TITLE
Un membre devrait pouvoir signaler un message caché

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5203]
https://zestedesavoir.com/forums/sujet/11117/ne-plus-utiliser-anonyme/?page=4#p195842

Une personne avec les permissions staffs peut signaler un message caché alors qu'un membre ne peut pas.

Il faudrait changer la condition de ce bouton dans le template.

**Comment by gllmc** [comment]
À noter qu'il y a déjà eu pas mal de modifications sur ce point, cf notamment #4379, #4537, #3759 et #3649. Je pense que le problème vient surtout du fait que l'on a jamais vraiment défini si le signalement d'un message masqué était souhaitable ou non. ^^

**Comment by A-312** [comment]
Ah #4537 (2017) le masque volontairement pour les membres, alors qu'en 2016 (#3759) semble maitre le bouton volontairement.

@artragis tu as le même avis que sur #4537, cad laisser comme actuellement ? ou permettre au membre de signaler ?

Faut-il avoir le même comportement sur un sujet et un message ?

**Comment by artragis** [comment]
Perso je m'en fiche totalement. Comme c'est actuellement me va mais certains aimeraient qu'on revienne au comportement initial. 

Je garde l'issue car elle fait une bonne première issue mais c'est loin d'être prioritaire. D'ailleur j'aimerais vraiment que vous laissiez cette tâche aux nouveaux contributeurs.
