### ISSUE TITLE
Signaler une faute sur un billet

### ISSUE THREAD

**Issue by nils-van-zuijlen** [zestedesavoir/zds-site#5205]
> Salut, quand j'essaye de signaler une faute sur un billet (https://zestedesavoir.com/billets/2965/ma-cle-usb-ne-fonctionne-pas-dans-ma-voiture-voici-la-solution-1/), je tombe sur une Erreur 404 dès que j'appuie sur Valider...

La page 404 en question est https://zestedesavoir.com/contenus/reactions/typo/?pk=2965

Sujet : https://zestedesavoir.com/forums/sujet/11839/signaler-une-faute-sur-un-billet/
*Envoyé depuis Zeste de Savoir*

**Comment by Situphen** [comment]
Je confirme le bug

**Comment by artragis** [comment]
est-ce le cas pour tous les billets? il y a peu quelqu'un m'a signalé une faute sur le zest of dev 11

**Comment by Situphen** [comment]
Je viens d'essayer sur ton billet Zest of Dev 11 et ça fonctionne correctement. Pour le tutoriel de Héziode, l'erreur remontée est une 404, donc aucune trace sur Sentry :/

**Comment by pierre-24** [comment]
Y'a pas une manip genre un changement de slug qui ne serait pas passé ? (je dis ça parce que j'ai l'impression d'avoir déjà lu ce billet par le passé).

**Comment by artragis** [comment]
ça doit être un pb de slug en effet. à tous les coups il fait la gigue entre "blablala" et "blablala-1" en bdd alors que c'est juste "blablala" pour le git.

**Comment by nils-van-zuijlen** [comment]
Donc c'est techniquement en lien avec #4434 et #4303

Y-a-t-il d'autres cas ou on a eu ce problème ?

**Comment by artragis** [comment]
de moi_ns en moins mais ça arrive.

**Comment by Heziode** [comment]
Une piste possible:

Créer un contenu de type article, avec un nom précis, du genre **AAAA**.

Créer un billet du même nom: **AAAA**.

Supprimer l'article, mais publié le billet.

(c'est ce que j'ai dû faire pour le tuto en question)
