### ISSUE TITLE
[PDF] Le logo Zeste de Savoir est flou

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5208]
Sur la première page le logo Zeste de Savoir est flou.

**Comment by pierre-24** [comment]
Voir #5062 ... Pour le moment, c'est un peu difficile :)

**Comment by artragis** [comment]
won't fix

**Comment by A-312** [comment]
![image](https://user-images.githubusercontent.com/18501150/73597446-5844c180-452c-11ea-91be-fef0ce42375e.png)

**Comment by A-312** [comment]
![image](https://user-images.githubusercontent.com/18501150/73597465-7c080780-452c-11ea-9a65-be26f5ab4ee0.png)

**Comment by artragis** [comment]
tu peux faire une pR stp?

**Comment by A-312** [comment]
j'y travaille, j'ai du mal à générer l'image avec inkscape (je ne suis pas habitué à l'utiliser).
