### ISSUE TITLE
[PDF] Problème lien de la licence

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5209]
Sur la première page le lien de la licence peut être cassé : https://zestedesavoir.com/articles/pdf/2905/conferences-et-seminaires-scientifiques-a-paris-et-ailleurs.pdf (CC 0)

https://zestedesavoir.com/articles/pdf/2652/recap-communautaire-5.pdf ici aussi ? Ou c'est parce que c'est un vieux pdf ?

**Comment by artragis** [comment]
CC-0 n'a pas de lien apparament, et l'autre semble en droits d'auteur normal.

**Comment by pierre-24** [comment]
Le premier pdf, @artragis a réglé le bug. Quand au second, en effet, c'est étonnant, la CC-0 n'est "que" en version 1.0 (et pas 4.0, comme les autres) : https://creativecommons.org/publicdomain/zero/1.0/legalcode
