### ISSUE TITLE
[PDF] Police avec Empattement ? (serif)

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5210]
Sur la première page c'est volontaire de choisir une police avec serif ?

De plus les pseudos s'affichent plus "mal" que "bien", je ne les trouve pas très lisible.

![image](https://user-images.githubusercontent.com/18501150/50623336-e65b0c80-0f14-11e9-9e13-37a804d5306c.png)
![image](https://user-images.githubusercontent.com/18501150/50623361-3639d380-0f15-11e9-845c-d3b064212980.png)
![image](https://user-images.githubusercontent.com/18501150/50623406-de4f9c80-0f15-11e9-82f0-1d36d6a2773b.png)

**Comment by artragis** [comment]
ticket à ouvrir dans latex-template

**Comment by pierre-24** [comment]
En effet :)
