### ISSUE TITLE
Reporter l'option "--speed" à gulp pour make build-front

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5214]
Permettre de --speed avec make build-front

**Comment by Situphen** [comment]
Je ne pense pas que ce soit une bonne idée. Il faut que la QA se fasse sans `--speed` pour être sûr de ne pas avoir de problème donc je propose de ne pas toucher à `make build-front`. Si tu veux vraiment utiliser `--speed`, alors tu peux utiliser `make watch-front` qui lance de toute façon la tâche `build` avant de `watch`. :)

**Comment by A-312** [comment]
Ok :)
