### ISSUE TITLE
Ajouter Mastodon dans les liens de partage

### ISSUE THREAD

**Issue by nils-van-zuijlen** [zestedesavoir/zds-site#5216]
Après #5038, il faudrait ajouter masto dans les liens de partage de la sidebar aussi.

La complexité du process vient du fait qu'il faut demander son instance à l'utilisateur ou trouver un service qui le fasse.

**Comment by nils-van-zuijlen** [comment]
D'ailleurs, on peut en profiter pour virer G+, ou du moins pour y penser.

**Comment by helmasaur** [comment]
Je veux bien m'y coller. Si on est connecté sur une instance et qu'on accède à un compte sur une autre instance, il n'est pas possible de suivre ce dernier ?

EDIT : après test, j'ai l'impression qu'il suffit de mettre le lien https://framapiaf.org/@ZesteDeSavoir

**Comment by artragis** [comment]
Je pense qu'ici le but est d'ajouter un lien pour faciliter le **partage** des contenus sur mastodon.

**Comment by helmasaur** [comment]
Pourtant, le lien Twitter pointe vers https://twitter.com/ZesteDeSavoir

**Comment by artragis** [comment]
Non, on parle du lien de partage des contenus publiés.

Par exemple, sur le tuto pour la notation scientifique on a : `https://twitter.com/share?url=https://zestedesavoir.com/tutoriels/2970/la-notation-scientifique-des-nombres/&text=La%20notation%20scientifique%20des%20nombres`

**Comment by helmasaur** [comment]
Oh pardon, je n'avais jamais fait attention à ces liens. Je viens de comprendre. Je vais me renseigner concernant ce problème d'instance. Merci pour les explications !

**Comment by nils-van-zuijlen** [comment]
Je confirme qu'il s'agit bien d'ajouter le lien dans la zone de partage de la sidebar.

![](https://zestedesavoir.com/media/galleries/5772/4514ba10-be2b-46ae-ab3c-f168b4f9a080.png)

Le truc, c'est qu'il y a sans doute besoin d'une pop-up pour sélectionner son instance.

**Comment by artragis** [comment]
Ou alors trouver un service comme celui de diaspora*

**Comment by helmasaur** [comment]
J'ai trouvé ça pour dépanner : https://aly-ve.github.io/Mastodon-share-button. On pourrait s'inspirer du principe en attendant de trouver mieux !

EDIT : et ça aussi https://www.256kilobytes.com/content/show/4812/how-to-make-a-share-on-mastodon-button-in-pure-vanilla-javascript .
