### ISSUE TITLE
Problème avec le bouton "Cette réponse m'a aidé"

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5217]
([Reporté sur le forum](https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=55#p196620)) Sur certains messages, la bordure du bouton "Cette réponse m'a aidé" est décalée.

![Aperçu du problème](https://zestedesavoir.com/media/galleries/5669/dbfa7395-4d98-49a6-900e-8f95d5f2e2a9.png)

Il faut ajouter `box-sizing: border-box;` sur `topic-message .message .message-karma button.ico-after`, c'est-à-dire [cette ligne](https://github.com/zestedesavoir/zds-site/blob/502a88b41161ec7dbff0862e3d805db397caf366/assets/scss/components/_topic-message.scss#L308).

**Comment by helmasaur** [comment]
J'espère que cette fois-ci, j'ai fait le *pull-request* de la bonne façon. Désolé si ce n'est pas le cas :(

**Comment by nils-van-zuijlen** [comment]
Oups, ce n'est pas le cas !

**Comment by helmasaur** [comment]
C'est quoi qui ne va pas ?

**Comment by nils-van-zuijlen** [comment]
En fait, tu as fait la PR sur ton propre dépôt, pas sur celui de ZdS. La PR #5242 est la même, mais ouverte sur zestedesavoir/zds-site et pas Helmasaur/zds-site.

**Comment by helmasaur** [comment]
D'accord, je ferai attention la prochaine fois. Merci :)
