### ISSUE TITLE
Inverser l'ordre du tableau des historiques de validation

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5218]
Pour la page : https://zestedesavoir.com/validations/historique/xxxxxxxxxxxxxxxx l'ordre NOUVEAU -> ANCIEN serait plus logique

C'est à dire que NOUVEAU est indiqué en premier.

**Comment by Arnaud-D** [comment]
Cette modification se fait dans le fichier `templates/tutorialv2/validation/history.html`.

Il suffit normalement de remplacer : `{% for validation in validations %}` par `{% for validation in validations reversed %}`.
