### ISSUE TITLE
Vérifier les textes et en corriger l'orthographe

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#522]
Vérifier les textes et en corriger l'orthographe.

**Comment by Alex-D** [comment]
A faire sur la branche d'intégration, je pense.

**Comment by vhf** [comment]
Je veux bien relire et corriger, mais elle est où cette fameuse branche d'intégration ?

**Comment by geoffreyc** [comment]
https://github.com/Taluu/ZesteDeSavoir/tree/integration

2014-05-14 8:10 GMT+01:00 victor felder notifications@github.com:

**Comment by Alex-D** [comment]
Dans la looonnngue liste des branche, il y a la petite "intégration" qui se promène là.

Par contre je n'ai rien push depuis quelque jour (oubli...) et donc tu n'auras pas le truc tout à fait à jour, mais pour les corrections ça ne devrait pas poser de problème. Au pire les conflits seront pour moi :')

**Comment by SpaceFox** [comment]
> Dans la looonnngue liste des branche, il y a la petite "intégration" qui
> se promène là.

Il faudra faire un peu de ménage d'ailleurs, je pense qu'on en a une bonne
moitié qui ne sert plus à rien.

**Comment by vhf** [comment]
Hum, me semblait pourtant avoir bien fouillé cette longue liste de branches. Au temps pour moi.

**Comment by Alex-D** [comment]
Dans le doute tu as sur Github un champ de recherche quand tu déroule la liste des branches.

Ou sinon : `git branch | grep "integration"` et hop le tour est joué \o/

**Comment by cgabard** [comment]
> Dans le doute tu as sur Github un champ de recherche quand tu déroule la liste des branches.
> 
> Ou sinon : `git branch | grep "integration"` et hop le tour est joué \o/

Alex, sans trop m'avancer, je pense que @vhf sait se servir de git et de github hein !

**Comment by Alex-D** [comment]
Je disais ça au cas où ^^ on a vite fait d'oublier ce genre de petite feature pratique :)

**Comment by vhf** [comment]
Effectivement, je me sers de Github tous les jours. J'ai juste pas trouvé la branche d'intégration et m'en excuse.

Au passage Alex-D, je commencerais volontiers la relecture/correction mais j'ai encore et toujours ces problèmes d'EOL (CRLF vs LF) sur ta branche. Vu que c'est corrigé en un coup de cuiller à pot, je l'aurais volontiers fait et pushé, mais ça t'aurait fait des milliers de conflits, donc soit j'attends que tu push tes modifs et je corrige les EOL, soit tu push tes modifs et tu corriges les EOL. DIs-moi ce que tu préfères.

**Comment by Alex-D** [comment]
Je n'ai pas push le "patch" peut-être. Du coup, je te push ça se soir, attends pour l'instant sinon ça va encore tout casser =D

Chez moi tout est déjà corrigé en fait, j'ai juste oublié de push la dernière fois ><"

Merci en tous cas :)

**Comment by Coy0te** [comment]
Vu que c'est pas évident de le trouver ni de le savoir hors-contexte, le mot "Réservé" dans le template d'administration des tutos doit s'écrire "Réserver".

**Comment by Eskimon** [comment]
Du coup ca en est ou ca ? Car ca fait partie des choses sur lesquels mon niveau de noob pourrait probablement traiter, mais est-ce le moment le plus opportun ? (car tant que des choses vont bouger au niveau integration ca risque d'etre chiant a chaque commit...)

**Comment by Alex-D** [comment]
Tu peux corriger dans ma branche sans que ça pose trop de soucis.

Il y a une autre discussion je ne sais trop où autour de l’internationalisation et tout ça et ça rejoint ce sujet.

**Comment by Coy0te** [comment]
J'avais cru comprendre que Victor était sur le coup. Je pensais le faire aussi (avec mon niveau de noob en django, c'est un truc qui m'allait bien).

**Comment by Alex-D** [comment]
Dans l'absolu, vous pouvez avancer en parallèle, si vous commitez bien vos modifications régulièrement sur ma branche, ça va le faire.
Voire, créez une branche de correction chacun que vous venez PR sur la mienne petit à petit, histoire de rester propres et éviter de tout casser :)

**Comment by Eskimon** [comment]
Si on est plusieurs a la correction il va falloir s'organiser pour pas dupliquer le travail...

**Comment by Alex-D** [comment]
Y en a un qui fait le module tuto, l'autre article, l'autre forum. C'est pas du texte qu'il manque.

Par contre, il y a des textes dans les templates **et** dans les vues.

**Comment by vhf** [comment]
Je laisse volontiers ma place.

**Comment by Eskimon** [comment]
Bon allez, je me prends le module tuto, il faut bien commencer quelque part... Je fork la branche intégration et essairai de faire des PR régulières si je vois qu'il y a beaucoup de corrections à faire (et une seule grosse s'il y avait pas grands chose).

**Comment by Eskimon** [comment]
Voilà une première passe de faite sur les tutos. Il en reste peut-être mais j’espère pas...

Quelques remarques pour une harmonisation entre les corrections:

Accents sur majuscules sur la première lettre de la phrase: **É**diter
Points à la fin de phrase ? Faudrait trouver une règle...
Franglais : offline -> hors-ligne
beta -> bêta

**Comment by Eskimon** [comment]
Vu les differents merge qui ont eu lieu récemment, on peut continuer sur la branche dev ou il faut toujours faire ca sur "intégration" ?

**Comment by firm1** [comment]
branche dev.

**Comment by Eskimon** [comment]
Je sais pas si la version que je regarde sur la prod' est la bonne mais sur la capture suivante :

![capture du 2014-06-04 18 18 21](https://cloud.githubusercontent.com/assets/761168/3176297/030ef8de-ec04-11e3-96cb-455ed9e66ca2.png)

Le mot "Réservé" devrait s'écrire "Réserver" puisque l'article n'est pas encore réservé...

Je sais qu'il y avait eu discussion la dessus avec @Alex-D ;)

**Comment by Alex-D** [comment]
Ca se peut qu'on ait corrigé à un endroit mais pas un autre, y a beaucoup de pages ^^

Fais-toi plez' pour les corrections :)

**Comment by Eskimon** [comment]
Je profite de cette issue pour faire remonter les soucis lies a l'orthographe...

[Par cyril6789](http://zestedesavoir.com/forums/sujet/242/manque-un-mot/)

> il manque un mot dans le message :
> Ce sujet est résolu, l'auteur de ce sujet a trouvé une solution satisfaisant **A** son problème.

**Comment by Alex-D** [comment]
Non, c'est soit :

> satisfaisant son problème

soit

> satisfaisante à son problème

Ce qui est différent ; en plus il manquait un accent sur le `À` .

**Comment by Eskimon** [comment]
Perso je vote pour la deuxième 

> Ce sujet est résolu, l'auteur de ce sujet a trouvé une solution satisfaisant à son problème.

**Comment by Coy0te** [comment]
Et pourquoi pas simplement "Ce sujet est résolu, l'auteur de ce sujet a
trouvé une solution à son problème." ?

**Comment by ShigeruM** [comment]
+1 Coyote. "solution satisfaisant(e)" ça fait un peu pléonasme en fait.

**Comment by Alex-D** [comment]
Pourquoi pas en effet. Dans tous les cas, la syntaxe est bonne, que celui/celle qui le souhaite fasse une PR :)

**Comment by ArnaudCalmettes** [comment]
Le verbe "satisfaire" est transitif direct.

« Une solution satisfaisant à son problème » est tout sauf français. La formulation actuelle (« une solution satisfaisant son problème ») est tout à fait correcte grammaticalement parlant.

Sinon +1 pour « une solution à son problème ». C'est plus léger.

**Comment by firm1** [comment]
On dirait qu'elle est perturbante pour ceux qui ne maitrisent pas les
rouage de la langue française.

**Comment by Coy0te** [comment]
Si on veut éviter toute emmerde et toute répétition (résolu / solution, etc.), on écrit uniquement `L'auteur de ce sujet a trouvé une solution à son problème.` et c'est marre.

C'est clair, concis et efficace.

**Comment by Alex-D** [comment]
L'avantage de répéter résolu, c'est pour le SEO aussi.

**Comment by Coy0te** [comment]
"Résolu" étant déjà présent dans le titre de la page, je pensais que c'était suffisant. My bad.

**Comment by Alex-D** [comment]
C'est vrai que je l'ai remonté dans le titre... Du coup on prendre la solution :

> L'auteur de ce sujet a trouvé une solution à son problème.

Et ça convient à tout le monde ?

**Comment by ArnaudCalmettes** [comment]
Va pour ça.

**Comment by Alex-D** [comment]
Voilà qui est fait dans la PR

**Comment by Coy0te** [comment]
Faudra penser à mettre un "D" majuscule à "discussions, débats, ... " dans la description du forum "Bar à smoothies".

**Comment by Alex-D** [comment]
Ca c'est pas dans le code pour le coup, ping @firm1 :)

**Comment by 0hexit** [comment]
Si vous avez besoin d'un coup de main pour la correction, je suis présent. Il suffit de me dire quoi corriger. Je me suis déjà permis de faire une PR :)

**Comment by SpaceFox** [comment]
Ça a été fait non ?

**Comment by Alex-D** [comment]
Au moins partiellement. Je n'ai aucune idée de si tout a été relu ou non. Je pense qu'au pire les coquilles restantes nous seront signalées.

**Comment by 0hexit** [comment]
Oui, je pense que ça peut être fermé. S'il y a des fautes, elles sont de toute façon signalées et il y a toute de suite une PR.

**Comment by Eskimon** [comment]
ProTIp : Monitorer le sujet "Les petits pixels" qui généralement les vois apparaître.

**Comment by Ymox** [comment]
Yop,

J'utilise pour la première fois mon compte GitHub, donc je vais juste me permettre de faire mes propositions et signaler quelques corrections.

Pour le message à la première mise en beta :
"J'aimerai avoir…" -> "J'aimerai**s** avoir…"
"Si vous êtes interessé…" -> "Si vous êtes int**é**ressé…" (à deux endroits, lignes 615 et 675 de views.py)

Autrement, comment est choisi l'auteur du message dans le forum ? C'est celui qui a créé le tutoriel, c'est celui qui a demandé la mise en beta ?  
Quid des co-rédacteurs ? Il serait peut-être sympa de les mentionner aussi. ~~Je pense avoir inauguré le système, donc~~ je me permets de lier [le sujet](http://zestedesavoir.com/forums/sujet/1412/wamp-developper-avec-php-ajax-html-sous-windows/) où j'ai d'ailleurs apporté les corrections signalées ci-dessus et adapté pour y inclure mon camarade.

**Comment by Alex-D** [comment]
> Autrement, comment est choisi l'auteur du message dans le forum ? C'est celui qui a créé le tutoriel, c'est celui qui a demandé la mise en beta ?

Là tu peux ouvrir un sujet sur le forum, c'est plus tellement le sujet ici.
