### ISSUE TITLE
Pourquoi katex.min.css est en source externe 

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5221]
```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.0/katex.min.css" crossorigin="anonymous">
```

La bonne pratique serait de faire une copie en local et de l'utiliser, c'est voulu d'utiliser une ressource externe ?

**Comment by artragis** [comment]
> La bonne pratique serait de faire une copie en local et de l'utiliser

pourquoi "la bonne pratique"? l'avantage d'un cdn c'est que comme ça le fichier est dans le cache des gens.

**Comment by A-312** [comment]
Normalement un site est censé s'occuper de ses ressources soit même ou en tout cas tout faire de la même façon, mais je n'avais pas vu : "url(fonts/KaTeX_Main-Bold.ttf) " c'est donc mieux d'utiliser cloudflare à moins de rajouter la base de l'url.

**Comment by artragis** [comment]
ok, si tu as plus de ressources à ce propos ça m'intéresse.

**Comment by A-312** [comment]
Quand c'est sur un autre serveur c'est bien de savoir si c'est toujours la même version, et que le fichier ne va pas changer que ça soit d'un point de vue sécurité, accessibilité (en cas de suppression du lien) ou apparition de bug (changement sur cette version).

A voir si on ne devrait pas ajouter un script js pour prévenir de l'indisponibilité de cette ressource et adressé une version locale pour enlever le risque de suppression.

On pourrait ajouter integrity : https://w3c.github.io/webappsec-subresource-integrity/ ?

MDN : https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by A-312** [comment]
Niveau chargement, on a mieux quand même :

![image](https://user-images.githubusercontent.com/18501150/50815363-2ce9a600-131d-11e9-91e3-5618ed793d64.png)

Alors que main doit être 9 fois plus gros que katex.min.css

**Comment by Situphen** [comment]
Alors si je comprends bien le CDN ça permet que le navigateur n'aille pas chercher KaTeX sur Cloudfare si jamais l'utilisateur a déjà visité une page où il est utilisé. Je ne pense pas que ce soit le cas pour la majorité des utilisateurs, KaTeX ça n'est pas énormément utilisé.

Comme @A-312 le dit, on peut rencontrer des problèmes comme :

- Cloudfare indisponible ou très lentement
- le fichier qui a subitement changé (même si on peut utiliser *integrity* en effet)
- la version de KaTeX a été modifiée dans le `package.json` mais pas dans le `templates/base.html`

Par contre, si jamais on décide fournir nous même le JS par exemple avec un paquet NPM (actuellement on extrait le CSS d'un paquet NPM, on peut prendre le JS aussi), on peut potentiellement avoir des soucis si la dépendance NPM n'est pas fiable.

À voir ce qui est le plus fiable !

**Comment by A-312** [comment]
> Par contre, si jamais on décide fournir nous même le JS par exemple avec un paquet NPM (actuellement on extrait le CSS d'un paquet NPM, on peut prendre le JS aussi), on peut potentiellement avoir des soucis si la dépendance NPM n'est pas fiable.

Ce matin j'ai eu la même réflexion pour les libs dans gulp files qui dépendent d'un package require. Alors qu'il est conseillé d'upgrader soit même les libs (même jquery) pour avoir pleinement conscience des changements.

**Comment by Situphen** [comment]
KaTeX est maintenant en source interne.
