### ISSUE TITLE
SEO + Accessibilité : Ajouter un h1 à la page d'accueil

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5222]
Il parait que les bots aiment bien les h1, faudrait-il en ajouter un à la page d'accueil ?

**Comment by Situphen** [comment]
As-tu des sources concernant cette affirmation ? :P

Si mes souvenirs sont bons c'était vrai il y a quelques années mais est-ce encore le cas aujourd'hui ? Ajouter un `h1` à la page d'accueil n'a pas trop de sens car il n'y a pas un titre principal qui mériterait d'être mis en valeur. Je crois d'ailleurs que Google n'aime pas trop quand on bidouille le code source pour plaire aux robots alors que ça ne sert à rien pour les utilisateurs.

On est sans preuve de l'efficacité ou de l'intérêt de la chose, donc je m'y oppose. :)

**Comment by AAClause** [comment]
Je vote pour mais pour une autre raison (plus liée à l'accessibilité et peut-être plus personnelle en fin de compte) : étant aveugle, je suis utilisateur de lecteurs d'écran et j'avoue que je m'attends toujours à trouver un `h1` sur une page. Tomber sur un h2 directement me chagrine toujours un peu.
Bon après l'important est de conserver une hiérarchie cohérente dans l'utilisation des `h[1-6]`. Et à ce niveau j'ai rien à redire sur ZdS. :)
Sans compter que pour les pages d'accueil, nombreux sont les sites sans `h1`…

N.B. : pour faire court, avec un lecteur d'écran, faut s'imaginer dans une sorte de tampon virtuel dans lequel on peut sauter de type d'élément en type d'élément (titres de niveau, liens, boutons…) en plus de pouvoir naviguer comme dans un document classique (par caractère/mot/ligne/page).

**Comment by A-312** [comment]
@Andre9642 Tu utilises quoi comme logiciel ?

Il faudrait que j'essaye un lecteur d'écran pour pouvoir améliorer le site dans ce sens.

**Comment by AAClause** [comment]
@A-312 J'utilise essentiellement [NVDA](https://www.nvaccess.org/) sous Windows. J'ai par ailleurs une [plage braille](https://en.wikipedia.org/wiki/Refreshable_braille_display) (l'expérience utilisateur avec ou sans affichage braille n'est pas la même…).
Comme je l'ai dit précédemment, ZdS est plutôt bien niveau accessibilité, AMHA. Pour le moment, la seule modification que j'ai faite (via Greasemonkey/Tampermonkey) est de retirer les numéros de ligne (uniquement pour le rendu avec les lecteurs d'écran) dans les balises de code. J'ai pu faire cela aisément en ajoutant un attribut [aria-hidden](https://www.w3.org/TR/wai-aria-1.1/#aria-hidden) sur les balises `div` ayant pour `linenodiv` comme valeur de `class`.

**Comment by A-312** [comment]
@Andre9642 J'ai essayé NVDA mais je n'ai pas trop compris le principe, ça lit seulement ce qu'on a sous la souris ou il y a plus de fonctionnalité ?

**Comment by AAClause** [comment]
@A-312 j'admire cette volonté de tester !
En toute honnêteté, je pense que ça risque de t'être difficile de faire un test représentatif rapidement. L'utilisation d'un lecteur d'écran demande de connaître certains concepts qui ne sont pas très intuitifs pour un voyant.

> ça lit seulement ce qu'on a sous la souris où il y a plus de fonctionnalité ?

Alors déjà, dis-toi que je n'utilise pas la souris. J'effectue tout au clavier. Et du coup, oui, ça lit bien plus que sous la souris. :)
Pour avoir un aperçu de comment naviguer avec NVDA, je t'invite à consulter ces sections du guide utilisateur : [5. Naviguer avec NVDA](https://www.nvda-fr.org/doc/userGuide.html#NavigatingWithNVDA) et [6. Le mode Navigation](https://www.nvda-fr.org/doc/userGuide.html#BrowseMode).
Bon courage !

**Comment by A-312** [comment]
J'avais déjà voulu essayer mais je ne savais pas vraiment vers où m'orienter. Ce matin j'ai ressayé avec NVDA mais je n'avais pas saisi comment ça fonctionnait, je vais planifier de lire ça pour comprendre le principe (parce que faire de l’accessibilité sans connaitre le logiciel, c'est un peu une blague).

As-tu des sites qui t'ont surpris dans leur intégration (en bien) ?

**Comment by Situphen** [comment]
> Sans compter que pour les pages d'accueil, nombreux sont les sites sans `h1`

@Andre9642 Je pense que c'est une bonne chose, car les pages d'accueil n'ont presque jamais rien à mettre en titre principal. Dans le cas de Zeste de Savoir, la page d'accueil présente les différents contenus présents sur le site sur un même pied d'égalité, d'où la présence de `h2`. Quand tu arrives sur une page d'accueil, tu t'attends à avoir quoi en `h1` ? Le nom du site ? Il faudrait se renseigner mais il est peut-être possible d'utiliser un attribut `aria` pour "simuler" un `h1` sur la page d'accueil.

**Comment by AAClause** [comment]
@A-312 là, j'ai pas grand-chose qui me vient à l'esprit, je te fais signe si jamais.

@Situphen :

> Dans le cas de Zeste de Savoir, la page d'accueil présente les différents contenus présents sur le site sur un même pied d'égalité, d'où la présence de h2.

Oui, je comprends tout à fait.

> Quand tu arrives sur une page d'accueil, tu t'attends à avoir quoi en h1 ?

Lorsque c'est présent, c'est bien le titre du site qui est repris.

> Il faudrait se renseigner mais il est peut-être possible d'utiliser un attribut aria pour "simuler" un h1 sur la page d'accueil.

Oui, c'est possible. Cf. [role="heading"](https://www.w3.org/WAI/PF/aria/roles#heading) et [aria-level](https://www.w3.org/TR/wai-aria-1.1/#aria-level).
