### ISSUE TITLE
Ajouter un Splash Screen (pour Chrome)

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5223]
Apparemment c'est une nouvelle mode sur chrome de pouvoir définir la couleur de fond quand la page se charge : 

https://developers.google.com/web/tools/lighthouse/audits/custom-splash-screen

**Comment by Situphen** [comment]
Ce n'est pas parce que c'est une nouvelle mode qu'on doit la suivre. :P
Si j'ai bien lu c'est pour les *progressive web app*, donc il faut voir est-ce que ça apporte réellement quelque chose aux utilisateurs ? Je ne m'y oppose pas, mais ce n'est pas le plus urgent :)

**Comment by A-312** [comment]
Surtout que dans notre cas, il ne s'agirait que de la mettre un background gris

**Comment by artragis** [comment]
Du coup on met pas :)
