### ISSUE TITLE
Ajouter une couleur à la toolbar (Chrome, Android)

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5224]
Sur Android on peut choisir la couleur de barre d'adresse de Zeste de savoir. Je suppose que sur Android on part sur du bleu foncé ?

https://developers.google.com/web/tools/lighthouse/audits/address-bar

**Comment by Vanadiae** [comment]
ping @artragis. Déjà présent [ici](https://github.com/zestedesavoir/zds-site/blob/dev/templates/base.html#L33).

**Comment by A-312** [comment]
#3392
