### ISSUE TITLE
Lisser le scrolling avec passive: true

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5225]
Voir vidéo sur : https://developers.google.com/web/updates/2016/06/passive-event-listeners

https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

Le scrolling semble plus agréable.

**Comment by Situphen** [comment]
Ça a l'air assez sympa ! Par contre, est-ce que nous sommes concernés ? Je ne crois pas que l'on ait de *touch event listener*. :)

**Comment by A-312** [comment]
Ah ? Je pensais que c'était aussi le scroll par défaut

**Comment by artragis** [comment]
Du coup on fait quoi ici?

**Comment by Situphen** [comment]
Bah je ne pense pas qu'on soit concerné par la fonction car on n'a pas de *touch event* sur le site. Donc je ferme :)
