### ISSUE TITLE
Ajouter un chapitre

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5228]
J'ai oublié d'ajouter le bouton "Ajouter un chapitre" dans le conteneur d'une partie (probablement dans child.part.html)

![image](https://user-images.githubusercontent.com/18501150/51000996-ecfa0d00-152e-11e9-8826-ce05d2a84215.png)

**Comment by artragis** [comment]
Tu n'as pas besoin de créer une issue pour ça, il suffi que tu modifies ta PR.
