### ISSUE TITLE
Savoir si une image uploadée dans la galerie est utilisée

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5230]
Vu que maintenant il y a le drag'n'drop et que l'upload est très facile, il serait bien de faire un système qui détecte si l'image a été utilisé au moins une fois dans un sujet (à l'envoie), pour savoir si on peut la supprimer ou non et ainsi la supprimer sans remord. (J'avais déjà 8 images non utilisées sur un total de 13).

Pour les anciennes images (avant ce futur changement) : On peut soit mettre true -> utilisée, soit N/A pour non applicable.

**Comment by artragis** [comment]
Compliqué pour peu d'utilité.
