### ISSUE TITLE
Le drag'n'drop pour les images ne se fait pas à l'emplacement du curseur

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5231]
Il faudrait faire en sorte que le drag'n'drop se fasse à la position du caret si : 

 - Le curseur n'est pas dans un mot ; (vérifier la lettre avant et après)
 - Ou sinon : Seulement ligne vide ou fin d'une ligne (vérifier les caractères blanc à droite jusqu'au \n).

**Comment by Situphen** [comment]
Est-ce que c'est encore nécessaire étant donné qu'on est passé à EasyMDE ?
