### ISSUE TITLE
Erreur interne lorsque le tag est : "-" (un seul tiret)

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5236]
Dans la zone staff : https://zestedesavoir.com/forums/sujet/11298/aaaaa/

à 15:50

![image](https://user-images.githubusercontent.com/18501150/51428876-594cce80-1c09-11e9-97e2-611cb62daeb5.png)

(Si a l'occasion on peut déplacer le sujet dans la corbeille ;) )

**Comment by A-312** [comment]
On peut accéder à l'édition : https://zestedesavoir.com/forums/sujet/editer/?topic=11298 mais pas au sujet

------

https://zestedesavoir.com/forums/sujet/11298/-/ : 
![image](https://user-images.githubusercontent.com/18501150/51428885-6ec1f880-1c09-11e9-9341-2a328c369f9d.png)

**Comment by nils-van-zuijlen** [comment]
Je n'ai pas réussi à reproduire.

**Comment by artragis** [comment]
c'est pas le tag mais le titre qui compte

**Comment by nils-van-zuijlen** [comment]
Je veux dire, j'ai pas d'erreur sur le sujet de @A-312

**Comment by artragis** [comment]
Mois je l'ai.

**Comment by nils-van-zuijlen** [comment]
Ah, je l'ai maintenant. Je me demande ce qui a changé entre temps...

**Comment by nils-van-zuijlen** [comment]
C'est bien le tag, pas le titre, j'ai testé sur la béta.

Et c'est partiellement cohérent, le titre n'a pas d'importance dans l'url, du moment qu'il est présent.

Sinon, est-ce qu'on peut avoir les logs serveur de ces erreurs ?

**Comment by A-312** [comment]
> Ah, je l'ai maintenant. Je me demande ce qui a changé entre temps...

J'avais édité pour enlever le bug, quelqu'un a dû remettre la version fatale ;)

**Comment by firm1** [comment]
Ce bug n'est plus reproductible, on peut ferme le ticket ?
