### ISSUE TITLE
Incohérence des tags entre la bibliothèque et les billets

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5241]
Pour un même tag `un zeste de culture` on a : 

- `/bibliotheque/?tag=un-zeste-de-culture` ([lien](https://zestedesavoir.com/bibliotheque/?tag=un-zeste-de-culture))
- `/billets/?tag=un zeste de culture` ([lien](https://zestedesavoir.com/billets/?tag=un%20zeste%20de%20culture))

À noter aussi que pour les tags de la bibliothèque, le titre de la page est "Toutes les publications • Bibliothèque • Zeste de Savoir" et ne mentionne pas le tag.

**Comment by artragis** [comment]
C'est un bug. il faut appliquer le slug tout le temps.
