### ISSUE TITLE
Utilisez Vagrant pour faciliter le développement

### ISSUE THREAD

**Issue by Chamane** [zestedesavoir/zds-site#5243]
Je suis sous Windows et configurer un poste de développement sous Windows semble etre un casse tete

**Comment by Situphen** [comment]
Tu peux demander de l'aide à @artragis qui développe régulièrement sous Windows

**Comment by A-312** [comment]
Si tu suis la documentation c'est assez simple (et depuis là dernière fois que j'ai installé sous Windows, la doc a été amélioré il me semble). N'hésite pas à poser tes question ici ou sur le forum dans "Dev Zone" ;)

**Comment by nils-van-zuijlen** [comment]
Sinon, il n'y a pas une image Docker en fabrication ? Je crois avoir vu passer ça.

**Comment by A-312** [comment]
~~https://zestedesavoir.com/forums/sujet/5870/image-de-developpement-docker/ il y avait ça, je ne sais pas si il y a plus récent.~~

edit : Voir ci-dessous.

**Comment by nils-van-zuijlen** [comment]
Il y a #5012

**Comment by Chamane** [comment]
Merci beaucoup je tiens note
