### ISSUE TITLE
Problème d'installation ZdS sur Ubuntu

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#5244]
Bonjour,

J'essaye d'installer ZDS a nouveau sur mon PC (Ubuntu 18.04), la branche master.

Je suis la doc en lançant la commande `make install-linux-full` et j'ai l'erreur suivante : 

```bash
Traitement des actions différées (« triggers ») pour libc-bin (2.27-3ubuntu1) ...
* activating venv ``
./scripts/install_zds.sh: ligne 72: .//bin/activate: Aucun fichier ou dossier de ce type
!! no virtualenv, cannot continue

```

Est-ce qu'il y a moyen de m'aiguiller là dessus ?

**Comment by pierre-24** [comment]
Pour une raison qui m'échappe (ou peut être pas), la variaiable `$ZDS_VENV` est pas finie. Vu qu'elle est définie [via un `source`](https://github.com/zestedesavoir/zds-site/blob/dev/scripts/install_zds.sh#L31), je pense qu'on est face à un problème de chemin :/ (quand on exécute, on est dans le dossier parent, donc j'imagine que ça doit pas fonctionner).

Je propose 

```bash
cd scripts
./install_zds.sh +full
```

... Mais faut penser à régler ça.

**Comment by Situphen** [comment]
Possiblement une régression introduite par #5188, ping @A-312

**Comment by A-312** [comment]
~~$ZDS_VENV serait indéfini ?~~

edit: Ah c'est ce que dit @pierre-24.

**Comment by firm1** [comment]
Re,

Merci pour votre réactivité, je viens de récupérer la branche dev (avec les récentes updates de @A-312 ), et le problème n'est toujours pas avec ses apports. J'ai la  même erreur.

Le truc qui me permet de le faire marché, est matérialisé dans la PR linkée ci-dessus. 

EDIT : je viens de voir que la MR de @A-312 (https://github.com/zestedesavoir/zds-site/pull/5245)  devrait aussi fonctionner, mais elle est moins générique que ce que je proposais.

**Comment by A-312** [comment]
@firm1 La commande : `cd ~/zds/zds-site && source zdsenv/bin/activate` fonctionne ?

**Comment by firm1** [comment]
@A-312 pas sur d'avoir compris ta question. Tu veux que j'utilise cette commande depuis quel dossier ? je n'ai pas de dossier `zds` dans mon home. Tu veux que je mette cette commande dans un script ? si oui ou ?

**Comment by A-312** [comment]
Oups zds est un dossier perso. Si tu as encore le problème, exécute juste la commande : cd pour être dans la racine du repo, puis source.

    cd zds-site
    source zdsenv/bin/activate

J'ai peut-être eu le même bug sur debian, je voudrais savoir si l'activation de l'environnement fonctionne correctement.

**Comment by firm1** [comment]
Oui la commande marche. Sinon j'aurai fait un ticket pour ça.

**Comment by A-312** [comment]
> Sinon j'aurai fait un ticket pour ça.

Ah tu n'as plus aucun bug ? J'avais compris que ta PR ne corrigeait pas le problème
