### ISSUE TITLE
Les fixtures ne peuvent pas se génrer si zmd n'est pas démarré

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#5248]
Bonjour,

La commande `make install-linux-full` semble installer pas mal de truc et la dernière étape `make generate-fixtures` échoue car le serveur zmd n'est pas encore démarré.

Vu que le script ne le démarre pas, c'est normal, dans ce cas, il vaut mieux ne pas lancer les fixtures dans cette commande, ou démarrer zmd avant l'execution des fixtures.

Qu'est-ce qui serait mieux ?

**Comment by A-312** [comment]
Tu es sûr que ça vient de là ? Il me semblait ne pas avoir besoin de lancer django pour appliquer les fixtures.

De mémoire `make install-linux-full` fonctionnait bien quand j'avais essayé (ça me rajoutait en boucle les lignes des fixtures "besoin d'un rédacteur, graphiste, etc..." dans l'édition d'un tuto)

**Comment by firm1** [comment]
Yep, j'en suis sur. cf. le code de `make generate-fixtures`

```
generate-fixtures: ## Generate fixtures (users, tutorials, articles, opinions, topics...)
	python manage.py loaddata fixtures/*.yaml
	python manage.py load_factory_data fixtures/advanced/aide_tuto_media.yaml
	python manage.py load_fixtures --size=low --all
```

La dernière ligne ne fait pas que charger des fixtures au sens django, elle fait des vrais actions comme la publication d'un contenu, ce qui necessite de transformer le .md en .html via le moteur zmd.

**Comment by artragis** [comment]
C'est pas géré ça?

**Comment by A-312** [comment]
@artragis #5480 ?

**Comment by artragis** [comment]
Merci @A-312
