### ISSUE TITLE
Elasticsearch BETA et PROD résultat très différent

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5257]
Pourquoi les résultats sont aussi différents ? C'est problématique pour tester de prochaine futur PR sur la recherche si on n'a un résultat qui diffère. Ou en tout cas j'aimerais savoir pourquoi on a une différence.

https://beta.zestedesavoir.com/rechercher/?q=introduction+aux+systeme&category=&subcategory=&from_library=

https://zestedesavoir.com/rechercher/?q=introduction+aux+systeme&category=&subcategory=&from_library=

Ce qui me dérange le plus c'est le "Introduction aux systèmes distribués " manquant

**Comment by pierre-24** [comment]
Il faut déjà voir quand a été mis à jour la DB d'elastic sur la bêta (c'est probablement pas automatique et un peu long à faire, et j'ai pas souvenir d'une commande de dump). Donc je pense que c'est par là qu'il faut chercher.

**Comment by artragis** [comment]
comme toujours, à chaque fois qu'on synchro la béta, on a le statu "d'indexation" de la prod alors que la béta n'a pas encore indexé les choses. Il faudrait que quelqu'un fasse un index-all à chaque fois qu'on fait un changement sur la béta ou que ça soit intégré à https://github.com/zestedesavoir/ansible-zestedesavoir

En attendant ça se passera comme ça à chaque synchro prod => béta.

**Comment by pierre-24** [comment]
(sachant que `index-all` est une opération qui prend un certain temps)
