### ISSUE TITLE
Statistique ajouter un graph adapté de la Matrice BCG

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5259]
Pour les big/moyen-tuto mettre en évidence quels chapitres/parties sont les plus attractifs/attractives via la matrice BCG : 

Ça permettrait à un auteur de savoir quel partie améliorer, s'il souhaite améliorer quelques choses :) 

Part de marché = Nombre de vue total
Croissance du marché = Évolution du nombre de vue selon une période -> En baisse ou en augmentation 

Via : https://www.chartjs.org/samples/latest/scriptable/bubble.html

La matrice BCG, c'est ça : 

[![image](https://user-images.githubusercontent.com/18501150/52121597-76799800-2620-11e9-9d65-cd1b14bf3031.png)](http://chohmann.free.fr/strategie/matrice_bcg.htm)

**Comment by artragis** [comment]
Fais la proposition sur le MP aux auteurs, ça permettra de savoir si ça leur est vraiment utile qu'on ne perde pas de temps à travailler dans le vent.

**Comment by artragis** [comment]
Pas désiré par les auteurs
