### ISSUE TITLE
Les boites spoilers déconnent quand il y en a plusieurs par pages

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#526]
Demo ici : http://zestedesavoir.com/forums/sujet/189/forum-disponibles-a-la-sortie

Je ne sais pas si ce code JS est commun à celui de la branche integration

**Comment by Alex-D** [comment]
Ca n'est pas commun, du coup je vais fermer cette issue.

**Comment by SpaceFox** [comment]
Tu as résolu le problème ? Où est la PR ?
Le 14 mai 2014 16:13, "DEMODE Alexandre" notifications@github.com a écrit
:

**Comment by Alex-D** [comment]
1/ Il s'agit d'un bug front sur la beta
2/ Ma branche n'a pas ce bug, puisqu'elle n'a même pas encore le JS qui gère ça

Donc je considère que ce bug n'est pas à corriger. On peut éventuellement ouvrir une issue "Coder les boites secrètes sur la branche d'intégration". Mais si je faisais ça avec toutes les choses que je fais, ça serait bien le bazar.

**Comment by SpaceFox** [comment]
Eh bien on fermera quand ta branche sera poussé. En attendant le bug est toujours présent, donc laisser l'issue ouverte nous permet de savoir qu'il est présent sur la version _actuelle_ de la prod.

**Comment by Alex-D** [comment]
Si ça peut te faire plaisir... mais si on part là dessus on peut ouvrir 200 issues hein. Je ne vois vraiment pas l'intérêt, mais soit. Dans deux jours elle sera close et puis voilà.

**Comment by SpaceFox** [comment]
La règle est très simple : on ne clos une issue que lorsqu'elle est
réellement close en prod. Point.

S'il y a 200 issues qui ont été fermées alors que les problèmes sont encore
présents en prod, c'est 200 conneries (et ce ne serait pas la première
dégeulasserie sur ce projet). Mais je ne vais pas me retaper toutes les
issues pour les retrouver et les rouvrir.

C'est là que quelque chose d'un peu plus souple que "ouvert / fermé" serait
pratique.

**Comment by Alex-D** [comment]
Fait sur ma branche et visible en préprod.
