### ISSUE TITLE
La doc sur elasticsearch est fause (mauvaise traduction)

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5260]
La doc officielle dit : 

> Elasticsearch is built using Java, and requires **at least** Java 8 in order to run. 

Il faut donc comprendre "au moins" et non "obligatoirement la 8" contrairement indiqué ici : https://docs.zestedesavoir.com/install/extra-install-es.html

**Comment by pierre-24** [comment]
*my bad*, mais à l'époque ou je rédigeais cette partie de la documentation, la version 8 de Java commencais seulement à se répendre (d'où la procédure d'installation un peu tordue).

**Comment by A-312** [comment]
Oui ou ça a pu changer entre temps^^
