### ISSUE TITLE
Améliorer le lancement d'Elasticsearch dans makefile

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5262]
Cette ligne est troublante car le echo apparaît même quand il n'y a pas de problème : https://github.com/zestedesavoir/zds-site/blob/dev/Makefile#L79

Ou ça fait un double echo s'il y a une erreur

Par exemple : 

```make run-elastic
elasticsearch || echo 'No elasticsearch installed (you can add it locally with `./scripts/install_zds.sh +elasticsearch`)'
Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME
No elasticsearch installed (you can add it locally with `./scripts/install_zds.sh +elasticsearch`)
```

Comme indiquait dans #5144.

**Comment by Situphen** [comment]
Mettre `@` au début de la commande sur la ligne que tu as cité devrait résoudre le problème :)
