### ISSUE TITLE
Activer l'onglet check (via Travis) sur Github pour les PR

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5266]
Peut-on activer l'onglet check pour travis comme ici https://github.com/A-312/zds-site/pull/12/checks ?

Il suffit de choisir travis ici : https://github.com/marketplace/travis-ci Ca va utiliser travis.com au lieu de travis.org , il faudra donc peut etre désactiver travis.org.

**Comment by sandhose** [comment]
Le problème c'est que la migration travis-ci.org -> travis-ci.com est pas encore possible sans perdre l'historique des builds.

cf. https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by A-312** [comment]
Ah :/

**Comment by A-312** [comment]
Par contre : 

> Previous build history - your builds from before the migration to travis-ci.com will remain on travis-ci.org until the complete build- history migration (sometime in January 2019)

**Comment by A-312** [comment]
> Previous build history - your builds from before the migration to travis-ci.com will remain on travis-ci.org until the complete build- history migration (sometime in Q2 2019)

@artragis @Situphen Avons-nous le bouton [migrate](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#the-migration-steps) ?

**Comment by A-312** [comment]
@artragis @Situphen ping : https://travis-ci.com/organizations/zestedesavoir/repositories

**Comment by Situphen** [comment]
C'est maintenant fait.

**Comment by A-312** [comment]
![](https://media1.tenor.com/images/a789969395fbeab3011a2dd871b231ed/tenor.gif?itemid=3883045)

**Comment by arobase-che** [comment]
Un avion effectuant une danse nuptiale ?

**Comment by A-312** [comment]
Oui danse de la joie :D
