### ISSUE TITLE
Le ping ne fonctionne pas chez moi

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5269]
> Bonjour !
> 
> J'ai remarqué quelque chose d'étrange et assez embêtant, surtout si je ne suis pas le seul concerné. Les pings qui me sont adressés ne me sont pas notifiés, ce n'est que par coup de chance que je peux les voir.
> 
> La toute première fois ça a bien fonctionné, avec [ce message](https://zestedesavoir.com/forums/sujet/11704/erreur-403-lors-dune-recherche-sur-zds/?page=1#p194211) du 3 décembre 2018.
> 
> Mais depuis, il y a eu [ce message](https://zestedesavoir.com/forums/sujet/6642/geocaching/?page=1#p195999) le 29 décembre 2018 que j'avais raté, et aujourd'hui (4 février 2019) même chose avec [ce message](https://zestedesavoir.com/forums/sujet/12059/la-nouvelle-version-de-zds-et-vous/?page=1#p198571).
> 
> De même, je n'ai pas eu de notification pour mes pings dans les récap' communautaires 9 et 11, mais je ne sais pas si la fonctionnalité est activée pour le contenu des articles ?
> 
> Voilà, si vous avez des explications ou si vous êtes dans le même cas que moi je vous remercie d'avance ! :)
> 
> EDIT : Je viens de voir [la réponse](https://zestedesavoir.com/forums/sujet/12059/la-nouvelle-version-de-zds-et-vous/?page=1#p198582) de @entwanne qui donne peut-être la bonne explication, mais moi je n'ai même pas de trace dans ma liste de notifications.

Sujet : https://zestedesavoir.com/forums/sujet/12061/le-ping-ne-fonctionne-pas-chez-moi/
*Envoyé depuis Zeste de Savoir*

**Comment by Situphen** [comment]
@artragis Je t'ai pingé deux fois sur la bêta : 

- une première fois lors de la création d'un sujet ;
- une deuxième fois lors de l'édition d'un sujet du forum (différent que lors de la première fois).

Peux-tu vérifier sur la bêta que tu as bien reçu les pings ?

**Comment by artragis** [comment]
yep, les deux

**Comment by A-312** [comment]
A vérifier avec des pseudos qui finissent avec des chiffres

**Comment by artragis** [comment]
à combien est le max_ping_count en prod?
https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/models.py#L397

**Comment by Situphen** [comment]
15 d'après [la valeur dans le code](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings/abstract_base/zds.py#L210)

**Comment by artragis** [comment]
Voilà on a la raison du pourquoi moi j'ai été pingé : premier de liste alors que ceux qui sont après le 15ème rang ne le seront pas.

J'ai envie de dire "not a bug, a feature".

**Comment by artragis** [comment]
fait en 27.1
