### ISSUE TITLE
pip install "--force-reinstall" ?

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5272]
Doit-on ajouter "--force-reinstall" à pip ? Où on accepte que certaine dépendance des requirement-xxx.txt aient une version supérieure si le système à le programme en version plus récent.

(L'option permet de forcer l'installation dans l'environnement si le programme existe déjà).

Ping @artragis @Situphen

**Comment by Situphen** [comment]
Je n'y suis pas favorable, je préfère qu'on installe les dépendances telles qu'elles sont décrites dans le `requirements.txt`. Si on a besoin de mettre à jour une dépendance, alors il faut modifier le `requirements.txt` et faire une PR, c'est long mais c'est en partie grâce à ça que notre code est aussi stable. D'ailleurs, je ne pense pas que l'option `--force-reinstall` soit faite pour être utilisée à chaque fois. Si jamais on utilise systématiquement cette option on va avoir chacun des versions différentes des dépendances, ça va entraîner des situations où pour untel aura un bug et personnes n'arrive à la reproduire car sans le savoir on a pas la même version de X dépendance. :)

**Comment by A-312** [comment]
Effectivement 

Je suis allé relire la doc, j'avais lu/compris autres choses sur le fonctionnement de la commande mais en relisant [la doc](https://pip.pypa.io/en/stable/reference/pip_install/) à nouveau, je constate qu'hier j'avais lu/compris autre chose.
