### ISSUE TITLE
La comparaison des versions a perdu sa sidebar

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#5273]
## Étapes pour reproduire 

- prenez un tuto avec plusieurs éditions
- cliquer sur "comparer les versions"
- sélectionner deux versions

**Comportement observé**

la sidebar n'apparaît pas dans la page de comparaison des versions

**Comportement désiré**

La sidebar est là.

**Comment by philippemilink** [comment]
Je viens de regarder un peu ce bug... Et il semblerait que ce ne soit pas un bug ! En effet, c'est explicitement mis dans le code de la vue de ne pas mettre de sidebar: https://github.com/zestedesavoir/zds-site/blob/cb0eb357dc0d768f117512e41bbedf79dc3d7e65/templates/tutorialv2/view/diff.html#L22-L24

Ça a été introduit par le commit: https://github.com/zestedesavoir/zds-site/commit/03aa9be6e49e

Ça peut en effet paraître pertinent de ne pas mettre de sidebar sur cette page, puisque hormis qu'il n'y ait pas vraiment d'actions à proposer, il peut être pratique d'avoir de la largeur disponible pour afficher le diff...

**Comment by pierre-24** [comment]
C'était une question de place, aussi : le diff en deux colonnes ne rentre
pas avec sidebar.

**Comment by A-312** [comment]
Ca serait bizarre de forcer la sidebar mobile ?

**Comment by artragis** [comment]
Ok donc si c,st volontaire on peut transformer le bug en : 

- mettre un lien pour retourner à la rédaction du contenu
- faire en sorte que le diff prenne tout l'espace dispo. 

ça vous va?

**Comment by A-312** [comment]
oui autant pousser l'idée complétement en utilisant toute la largeur de l'écran

**Comment by philippemilink** [comment]
Pour l'occupation de toute la largeur c'est bon, mais pour le lien de retour, je ne sais pas quel adresse utiliser, puisqu'on peut arriver à la page de diff de plusieurs façons... Utiliser le referer serait une bonne façon de faire ?

**Comment by artragis** [comment]
>  je ne sais pas quel adresse utiliser

utilise la fonction `get_absolute_url`
