### ISSUE TITLE
Améliorer le <meta description> des forum/des contenus

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5274]
Mon fix de l'issue #5187 peut être amélioré, ce n'était pas le but premier de cette PR j'ai donc fait quelques choses de simple. En y repensant et suite au message de [Leeroy](https://zestedesavoir.com/forums/sujet/12099/seo-et-spam/?page=1#p199005) sur le forum : 

> revoyez la balise meta description qui la même sur toutes les pages (`<meta name="description" content="Zeste de Savoir est un site de partage de connaissances sur lequel vous trouverez des tutoriels de tous niveaux, des articles et des forums d’entraide animés par et pour la communauté.">`) ou est vide pour les tutos, alors que vous pourriez reprendre les x premiers caractères du premier post.

https://github.com/zestedesavoir/zds-site/blob/e7ff7912d2424523607308a566866012fb2e621e/templates/tutorialv2/view/content_online.html#L42

La description est bien mais on peut faire mieux, surtout pour les Tweets et le SEO. :)

**Comment by A-312** [comment]
Donc : 

Pour le forum on prend : 

La description du sujet + le début du sujet avec une REGEX pour enlever Bonjour/Salut, etc.... ;)

Du style : 

Pour un contenu : 

> Production, consommation, effet. — Chacune de nos actions consomme de l’énergie. Qu’il s’agisse de se déplacer, même à pied, de se chauffer, de produire...

Si je prends en exemple [ce tutoriel](https://zestedesavoir.com/tutoriels/2921/lenergie-et-la-pollution-en-france/) :

![image](https://user-images.githubusercontent.com/18501150/60565882-7ca5a900-9d65-11e9-9873-15643d9c18f6.png)

Pour un sujet sur le forum : 

> Ressources, tutoriels, etc... — J’aimerais partager avec vous cette banque de liens mise au point sur le cousin de ZdS : PdP. Quelques problèmes ayant affectés ce dernier, j’essaie de préserver...

Si je prends comme exemple [ce sujet](https://zestedesavoir.com/forums/sujet/2376/banque-de-liens/) : 

![image](https://user-images.githubusercontent.com/18501150/60566045-f89ff100-9d65-11e9-8af6-3b495aa9d443.png)

**Comment by artragis** [comment]
Pour être plus clair : on enlève les phrases style "bonjour tout le monde", puis on colle les 120 premiers caractères du message.

**Comment by A-312** [comment]
> est vide **pour les tutos**, alors que vous pourriez reprendre les x premiers caractères du premier post.

L'idée est valable aussi pour les contenus, j'ai mal nommé mon issue

EDIT : Ah! [Une petite souris est passé par là](https://github.com/zestedesavoir/zds-site/issues/5274#event-2175965180) ! 😝

**Comment by artragis** [comment]
Pour les tutos on a déjà des choses de faites logiquement.

**Comment by A-312** [comment]
Mais c'est assez léger de remettre "Site et association de partage de connaissances animé par sa communauté. Vous y trouverez des tutoriels et des articles de tous niveaux et des forums." quand il n'y a pas de description au contenu

Alors que : 
> Production, consommation, effet. — Chacune de nos actions consomme de l’énergie. Qu’il s’agisse de se déplacer, même à pied, de se chauffer, de produire...

Pourrait etre plus attirant que : 
> Production, consommation, effet.
