### ISSUE TITLE
SEO et forums : Amélioration possible

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5275]
> revoir la proportion et l’emplacement du contenu a indexé avec la proportion de contenu qu’on ne veut pas indexer (le premier contenu qui nous intéresse ne se situe que rarement avant la ligne 1000 et est précédé d’information totalement inutiles pour le référencement, voir identique dans toutes les pages, le menu général, "auteur du sujet", …) par exemple, faite la recherche "seo et spam zeste de savoir" et regardé le résultats 2
> 
> titre => Liste des forums • Forum • Zeste de Savoir
> lien => https://zestedesavoir.com/forums/
> descriptif => Développement Web. JavaScript, HTML, CSS, PHP, SQL, RoR, etc. 1371 11652. Il y a 13 minutes Il y a 13 minutes SEO et SPAM … 

https://zestedesavoir.com/forums/sujet/12099/seo-et-spam/?page=1#p199005

**Comment by artragis** [comment]
Quelques éléments : 

- mettre un `<nav>` sur la pagination, mettre les pages en elles-même en no-follow, on a déjà next/previous pour ça
- mettre un élément `<date>` plutôt que `span` sur les dates
- mettre un no-follow sur l'auteur
- ajouter un aria-hidden sur la `topic-members-short-date`
- trouver si on ne peut pas désindexer les nombre de message dans la page forum
- mettre un `<nav>` sur le aside du forum 
- mettre un `no-follow` sur les filtres de sujet (non-résolus/résolus/sans réponse)
