### ISSUE TITLE
Améliorer le rendu avec Pocket (getpocket.com)

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5278]
Pocket est intégré à Firefox et devient une fonctionnalité clé aux liseuses Kobo . Cependant nous avons quelques problèmes de rendu.

Je n'ai pas trouvé d'article, ni de documentation expliquant comment améliorer l'export mais je pense qu'on peut légèrement modifier le HTML pour avoir quelques choses de mieux. :) 

Pour : 

 - https://zestedesavoir.com/tutoriels/2970/la-notation-scientifique-des-nombres/
 - https://zestedesavoir.com/articles/2953/jai-mal-docteur/
 - https://zestedesavoir.com/billets/3026/configurer-et-securiser-votre-serveur/

J'obtiens :

![image](https://user-images.githubusercontent.com/18501150/52803247-f45a8c00-3081-11e9-8d19-3e7501202451.png)

Après une deuxième actualisation : 

![image](https://user-images.githubusercontent.com/18501150/52803991-67183700-3083-11e9-8c30-977a2101bd9d.png)

On a ni le titre, ni le bon logo. :(

Pour un contenu sans logo, il faudrait pouvoir obtenir : 

![image](https://user-images.githubusercontent.com/18501150/52803447-616e2180-3082-11e9-94f2-df044a7b92fa.png)

**Comment by philippemilink** [comment]
Effectivement, je n'ai pas trouvé de documentation à ce sujet sur le web.

Je leur ai donc envoyé un mail leur demandant s'ils pouvaient m'expliquer comment faire pour avoir de meilleurs rendus. S'ils ne répondent pas, je ferais des essais en regardant les balises meta importantes pour les articles (pas ceux de ZdS) qui ont un bon rendu.

**Comment by A-312** [comment]
Je suis tombé sur : https://blog.getpocket.com/2010/11/the-insane-new-article-parser/

**Comment by philippemilink** [comment]
> Je suis tombé sur : https://blog.getpocket.com/2010/11/the-insane-new-article-parser/

Mouais... l'article dit justement que si un article s'affiche mal dans Pocket, c'est la faute de Pocket et ça ne doit pas être celle de l'éditeur de contenu. En outre, ils ne veulent pas imposer des choses aux développeurs pour avoir un bon rendu.

Faudrait donc plutôt leur signaler que le contenu de ZdS pourrait être meilleur, pour qu'ils adaptent/améliorent leur parser...

**Comment by philippemilink** [comment]
Réponse du support:
> Thank you for reaching out to Pocket Support!
>
> Pocket currently does not have specific guidelines to share. I'd be happy to take a look at your site to see if there is anything we can do on our end to improve how it is shown in Article View.
>
> Feel free to send me a few example articles, and I'll take a look. The more examples you can provide the better. I see you shared the domain but specific articles from your end would be incredibly helpful. 

J'ai répondu avec les trois liens du message original de l'issue, en expliquant les éléments qui n'allaient pas quand on sauvegarde dans Pocket.

**Comment by philippemilink** [comment]
> Thank you for getting back to me!
>
> I was able to reproduce the issue you’ve found, and have filed a bug report so we can try and get it fixed for you.
>
> Thanks for taking the time to send us this report. I will get back to you when this is resolved!

**Comment by A-312** [comment]
:)

**Comment by artragis** [comment]
bah du coup on ferme :)
