### ISSUE TITLE
Les champs des formulaires s'affichent mal avec un thème sombre

### ISSUE THREAD

**Issue by Deuchnord** [zestedesavoir/zds-site#5279]
Hello,

Avec certains thèmes sombres sous Linux, les champs de saisie des formulaires prennent par défaut la même couleur que ceux du système, ce qui rend dans certains cas les formulaires de sites illisibles.

Il faudrait surcharger le background des champs de saisie des formulaire afin qu'ils s'affichent dans la couleur attendue (blanc ?).

- **Environnement de bureau :** GNOME Shell
- **Thème :** Adwaita Dark (préinstallé avec GNOME Shell)
- **Navigateur :** Firefox 65

---

# Quelques exemples

Le champ de recherche de la page d'accueil :

![Champ de recherche de la page d'accueil](https://user-images.githubusercontent.com/7600265/52897452-ee28f480-31d4-11e9-81ab-0e96f4e5838e.png)

Le formulaire d'authentification :

![Formulaire d'authentification](https://user-images.githubusercontent.com/7600265/52897458-06990f00-31d5-11e9-98d9-0899c5ec7d19.png)

Le formulaire de création de sujet sur les forum :

![Formulaire de création de sujet sur les forums](https://user-images.githubusercontent.com/7600265/52897462-16185800-31d5-11e9-917e-90b6a85b2b0a.png)

**Comment by A-312** [comment]
Il me semble que c'est couvert par #5137 de @NicolasStr. :)

**Comment by Deuchnord** [comment]
Bien vu, je l'avais loupé !
Merci :)

**Comment by A-312** [comment]
@Deuchnord Tu as aussi : https://addons.mozilla.org/fr/firefox/addon/owl/?src=search qui force le thème sombre, et ça fonctionne correctement :)
