### ISSUE TITLE
Les catégories de premier niveau ne sont pas cliquable dans le menu

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5281]
Par exemple : "Informatique" ou "Science de la nature" n'est pas cliquable dans le menu : 

![illustration - menu](https://user-images.githubusercontent.com/18501150/52919923-b66e9980-3307-11e9-8b5d-265f6aa6cb7a.png)

https://zestedesavoir.com/bibliotheque/informatique/
https://zestedesavoir.com/bibliotheque/sciences-de-la-nature/

**Comment by philippemilink** [comment]
Salut,

C'est bon pour les menus _Bibliothèque_ et _Forum_, en revanche pour les tribunes, il n'y a pas (tout du moins je n'ai pas trouvé !) de page qui permette de lister tous les billets d'une catégorie (seulement par sous-catégories). Je ne mets pas de lien aux catégories des tribunes ? 

(la même question se pose pour _Tags les plus utilisés_ dans le menu des forums)

**Comment by A-312** [comment]
Oui, on laisse les tags/tribunes

**Comment by Vanadiae** [comment]
PR déjà merge, peut-être fermer cette issue ?

**Comment by artragis** [comment]
Bien vu!

**Comment by Vanadiae** [comment]
Je peux te ping @artragis lorsque je trouve des tickets à fermer ? (Si ça peut t'éviter d'avoir à chercher :smile:)

**Comment by artragis** [comment]
si tu en trouves, oui. Normalement je vais pouvoir avancer un peu le nettoyage ce soir.
