### ISSUE TITLE
Diminuer le margin top du premier H1 dans un sujet

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5282]
Pour le premier h1 (.message-content > div:first > h1:first) il faudrait diminuer le margin-top qui est un peu excessif. :) J'imagine qu'il faut faire de même pour les h2, h3, h4...

ACTUELLEMENT :

![image](https://user-images.githubusercontent.com/18501150/53079691-3eff5c80-34f7-11e9-9e4c-3b31d26db7b1.png)

VOULU : 

![image](https://user-images.githubusercontent.com/18501150/53079742-63f3cf80-34f7-11e9-9fce-b9e33fba7dc5.png)

margin-top: 14px (comme le bottom)

**Comment by Vanadiae** [comment]
Je m'en occupe.
