### ISSUE TITLE
Ajouter un bouton pour enlever le filtre Publiés ou Brouillons

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5285]
Sur les pages qui liste les contenus ou billets, il faudrait ajouter un bouton permettant d'enlever le filtre. Car une fois qu'on clique sur "Publiés", il n'y a pas d'option pour l'enlever la seule possibilité et de revenir en arrière ou de modifier l'url de la page.

https://zestedesavoir.com/contenus/tribunes/3349/?filter=public
https://zestedesavoir.com/contenus/tutoriels/3349/

Quand un filtre est sélectionné (comme ci-dessous), on devrait pouvoir cliquer sur "Aucun filtre"/"Enlever le filtre"...

![image](https://user-images.githubusercontent.com/18501150/53172006-929ba400-35e4-11e9-8834-3e0888098110.png)

**Comment by philippemilink** [comment]
Salut,
J'allais commiter ce que je venais de faire par rapport à ce ticket, mais je me suis rendu compte que le bouton pour annuler le filtre n'était pas toujours utile, car il y a des cas où il y a uniquement les filtres _public_ et _bêta_ et où si on enlève le filtre, on revient à _public_ (les tutoriels d'un autre utilisateur que celui qui est connecté, par exemple). Avoir un bouton _annuler le filtre_ qui n'a pas d'effet dans ces cas-là est un peu bizarre...

J'ai un peu regardé dans quel cas c'était pertinent d'avoir un bouton pour annuler un filtre, et j'ai l'impression que c'est uniquement quand on est sur des les listes de l'utilisateur connecté (c'est-à-dire sur ses propres listes).

J'attends confirmation pour commiter en conséquence :smiley:

**Comment by A-312** [comment]
Je n'y avais pas pensé.

Solution 1 : Donc si on enlève le bouton "Annuler" lorsqu'il est inutile, on affiche les filtres seulement s'ils sont utiles pour la cohérence avec ce bouton "annuler" intelligent.

Solution 2 : Si on ne réfléchi pas à son utilité, on affiche le bouton annuler tout le temps sans se poser de question.

**Comment by sylafrs** [comment]
Oh, je n'avais pas vu l'issue, j'ai proposé une modification dans la PR #5297
Le truc est déjà fonctionnel, mais je peux y appliquer ce qui a été dit ici à savoir :

- Au lieu de l’appeler "Tous" (ce qui indique que l'on veut voir tous les contenus), l'appeler "Annuler"
- Dans ma solution, le "Tous" est en gras quand il n'y a pas de filtre, je peux aussi le retirer s'il n'est pas utile.

Dans ma PR on a un système de double filtrage :

![image](https://user-images.githubusercontent.com/967253/54028727-50f32780-41a6-11e9-93d4-d9051099fdf5.png)

(On peut par exemple choisir de voir tous les articles dont on est Auteur et qui sont en cours de validation)

Si on préconise la solution "Annuler", en faut-il un pour chaque filtrage ? ou un général ?

Je peux aussi faire un compte de résultats après filtrage à envoyer au gabarit pour qu'il n'affiche que les filtres utiles, comme proposé ici. (et si qu'un filtre disponible, enlever le groupe de filtres)
