### ISSUE TITLE
Améliorer le makefile et permettre d'installer zmd comme un dépôt git

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5286]
Améliorer la gestion de zmd permettrait de faciliter la participation à zmd car l'emplacement de l'installation et l'emplacement de zmd n'aide pas, ensuite si on définit un accès particulier dans le make, le changement ne tient pas si on travail sur zds-site....

Il faudrait pouvoir inclure zmd comme un dépôt git lors du dev et non comme une dépendance npm.

Il faudrait pouvoir : 

```
Vérifier si l'emplacement ../zmardown existe et l'option --force-dep-zmd ne soit pas définit
    cd zmd ../zmarkdown && npm run server
Sinon
    cd zmd/node_modules/zmarkdown && npm run server
```
A réfléchir si on garde `zmd/` pour le dépôt git ou si on utilise `../zmardown/`

https://github.com/zestedesavoir/zds-site/blob/5cbe342664afe6c8001e19ce15bbbf6256c5533f/Makefile#L67

**Comment by artragis** [comment]
vaut mieux pas faire ça.
