### ISSUE TITLE
Grosse incohérence dans la galerie avec le bouton supprimer

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5289]
![image](https://user-images.githubusercontent.com/18501150/53412772-8b9cd900-39ca-11e9-83f0-dccc0bf8d625.png)

Lorsqu'on est sur une image, l'action devrait être supprimer l'image au lieu de supprimer la galerie...

**Comment by philippemilink** [comment]
Le souci, c'est que ce menu _Actions_ représente toujours les actions relatives à la galerie (clique sur toutes les actions proposées pour voir). 

Pour palier à l'absence de possibilité de supprimer l'image depuis la page d'édition de l'image, je verrais plutôt un bouton rouge _Supprimer_ à gauche du bouton vert _Mettre à jour_.

Qu'en penses-tu ?

**Comment by A-312** [comment]
Je n'ai pas vraiment d'avis, pour moi on met une sidebar partout alors que les boutons pourraient se trouver à l'écran.

Il faudrait enlever toutes les actions liés à la galerie.

On devrait avoir :

Créer une image ;
Revenir à la galerie.

Mettre supprimer dans la page est le premier endroit où j'ai regardé, faute d'un bouton j'ai cliqué sur la croix dans la sidebar sans regardé... je voulais rapidement l'effacer car j'avais laisser mon mail...
