### ISSUE TITLE
Paramètre GET pour activer la miniature twitter en `summary_large_image`

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5291]
Ajouter une vérification `?twittercard=large` pour activer la twittercard en large dans le front.

Minimum : 300 x 157 idéal : 600 x 314

https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image.html

**Comment by philippemilink** [comment]
J'ai eu un peu de mal à comprendre ce que tu voulais avoir... Si j'ai bien compris: tu souhaiterais qu'en ajoutant `?twittercard=large` à l'URL, la meta `twitter:card` passe de `summary` à `summary_large_image`, avec en plus le lien de `twitter:image` qui contienne un lien vers l'image aux dimensions que tu as indiquées ?

Si c'est ça, je pense pouvoir le faire, ça ne me paraît pas trop difficile ! Si j'ai bien compris, il faut rajouter une ligne dans ce code: https://github.com/zestedesavoir/zds-site/blob/cb0eb357dc0d768f117512e41bbedf79dc3d7e65/zds/settings/abstract_base/zds.py#L35-L52
Mais comment les miniatures des images déjà présentes dans les galleries vont se générer ? Lors d'une migration ? Il faut le préciser quelque part ? (j'ai vu dans les anciens commit qu'apparemment non, mais je préfère demander, à la fois pour être sûr et comprendre comme ça fonctionne !)

**Comment by A-312** [comment]
Oui c'est bien ça

> Mais comment les miniatures des images déjà présentes dans les galleries vont se générer ? Lors d'une migration ? Il faut le préciser quelque part ? (j'ai vu dans les anciens commit qu'apparemment non, mais je préfère demander, à la fois pour être sûr et comprendre comme ça fonctionne !)

Aucun soucis, j'ai rajouté : `'social_network': {'size': (144, 144), 'crop': True},` sans trop me poser de question. ;)

**Comment by philippemilink** [comment]
Mais les dimensions de `social_network` ne correspondent pas à celles que tu as précisées !

Et ça ne répond pas vraiment à ma question: si on a besoin de rajouter une dimension dans la liste des miniatures, comment (quand) sont générées les nouvelles miniatures correspondant à cette dimension ?

**Comment by A-312** [comment]
Tu n'as pas compris ce que je voulais dire, lors [de ma précédente PR](https://github.com/zestedesavoir/zds-site/pull/5187/files#diff-a69f86956b546a99efd7ff6c01b41c2eR48) quand j'ai ajouté le format 228x228px j'ai juste eu besoin de rajouter cette ligne, le module s'occupe de tout derrière.

Donc là tu pourrais faire : `'social_network_large': {'size': (600, 314), 'crop': True},`

**Comment by pierre-24** [comment]
> si on a besoin de rajouter une dimension dans la liste des miniatures, comment (quand) sont générées les nouvelles miniatures correspondant à cette dimension ?

La première fois que l'image en question a besoin d'être utilisée (vraiment). C'est ce qui rend la chose facile à utiliser :)
