### ISSUE TITLE
Espaces insécables dans le titre des contenus à la Une

### ISSUE THREAD

**Issue by helmasaur** [zestedesavoir/zds-site#5292]
Il serait bien d'ajouter un filtre permettant de remplacer les espaces par des espaces insécable là où il faut. _Exemple : avant un point d'interrogation (cf. capture d'écran)._

<img width="228" alt="capture d ecran 2019-02-28 a 20 24 39" src="https://user-images.githubusercontent.com/873762/53592687-1af6e780-3b97-11e9-951b-054ae0d9f67c.png">

**Comment by A-312** [comment]
Il faudrait utiliser un [templatetag](https://github.com/zestedesavoir/zds-site/tree/dev/zds/utils/templatetags) pour qu'il soit directement utilisable sur le front sans difficulté, ça permettrait de l'ajouter partout où c'est necessaire

https://docs.djangoproject.com/fr/2.1/howto/custom-template-tags/

**Comment by helmasaur** [comment]
Je dois ajouter un fichier dans [templatetag](https://github.com/zestedesavoir/zds-site/tree/dev/zds/utils/templatetags) qui gérerait les espaces devant certains caractères ?

**Comment by A-312** [comment]
Oui comme un filtre : https://github.com/zestedesavoir/zds-site/blob/48004a01acb38ca51b21c5a5a70db6e1cc370fc0/zds/utils/templatetags/date.py

**Comment by Vanadiae** [comment]
~~je peux m'en occuper de celle là @Helmasaur si tu la sens pas (je m'étais assigné mais déassigné par manque de temps)~~ Nope, je serais pas là la semaine qui vient

**Comment by helmasaur** [comment]
J'ai essayé de m'assigner mais il me semble que je ne puisse pas. J'essaie d'apprendre donc je verrais ce que ça donne 😄 .

**Comment by helmasaur** [comment]
Le même problème existe pour les titres des sujets, et tutoriels. J'imagine que ça s'étend au billets et aux articles.

**Comment by A-312** [comment]
Concentre toi sur la Une comme je t'ai dis sur Discord, la majorité des titres sont en no-wrap

**Comment by helmasaur** [comment]
J'ai fait les tests pour ces cas là en fait. Donc autant faire les quatre modification ? Je pense que c'est les endroits principaux.

**Comment by A-312** [comment]
Fait une correction là ou il y en a besoin par contre attention de ne pas impacter la génération du slug dans l'url si tu modifies à l'envoie
