### ISSUE TITLE
[Suggestion] Donner un accès en lecture seule à un membre sur un tutoriel en cours de rédaction

### ISSUE THREAD

**Issue by sylafrs** [zestedesavoir/zds-site#5296]
Bonjour,

Etant en cours de rédaction d’un tutoriel j’ai l’habitude de le montrer à mes amis qui travaillent aussi dans le secteur pour recueillir leur avis afin de l’améliorer.

Aussi, je suis donc obligé soit :

- de leur montrer mon tuto sur mon compte avec moi à côté : meilleure solution courante, mais alors, si le tutoriel est grand et que l’on veut faire une passe entière, la personne est obligée de le faire d’un coup et pas en lecture tranquille chez elle.
- de leur demander de créer un compte (s’ils n’ont ont pas) et de les mettre en co-auteur temporairement (ce qui n’est pas vraiment le cas, et pourrait potentiellement être problèmatique)
- de créer un compte "test" à moi, le mettre en co-auteur temporairement (nope!)
- de leur donner mon compte temporairement (nope!)
- d’exporter le tuto d’une certaine manière et de leur donner l’export. (c’est embêtant, surtout si je fais des modifications)

Je pense que pouvoir assigner un certain membre en tant que "beta alpha-testeur", ou bien avoir accès à un lien public (avec date de péremption ou non) me permettrait d’éviter tout ces problèmes.

Merci :) ,
Sylafrs

Topic : https://zestedesavoir.com/forums/sujet/12179/suggestion-donner-un-acces-en-lecture-seule-a-un-membre-sur-un-tutoriel-en-cours-de-redaction/

**Comment by sylafrs** [comment]
Je tente de faire la feature moi-même aussi dans mon coin: je n'ai jamais utilisé Python ou Django du coup j'apprend à la dure :)

Du coup n'hésitez pas à faire la modif aussi de votre côté ^^

Mon dépot/ma branche : https://github.com/sylafrs/zds-site/tree/feature_tutorial_testers

Actuellement, j'ai la liste de testeurs qui semble marcher, le mp envoyé aussi, la lecture en mode read-only marche aussi. J'ai placé le tutoriel dans la liste des tutoriels du testeur et j'ai mis un filtre. (n'apparait pas sur les autres filtres)

Il faudrait que j'empêche un auteur de se trouver dans la liste des testeurs et que je retire un testeur de la liste s'il devient auteur.

Il faut que je teste davantage, je suis sur que j'aurai des problèmes :p

Il faut aussi que j'apprenne comment faire les tests unitaires, mais je vais me baser sur ce que je lis dans le code (comme pour ce que j'ai déjà fait) + google.

**Comment by sylafrs** [comment]
Si vous avez des conseils ou des remarques n'hésitez pas :)

**Comment by sylafrs** [comment]
fail :|

**Comment by sylafrs** [comment]
Etant donné qu'il a évolué, devrais-je faire un nouveau PR, ou garder le même ne pose aucun problème ?

**Comment by artragis** [comment]
Garde sur la même, ça permet de voir l'évolution, d'autant que ta PR initiale est de très bonne qualité.

**Comment by sylafrs** [comment]
ça marche, merci :)

**Comment by Arnaud-D** [comment]
Essentiellement un doublon de #6092.
