### ISSUE TITLE
[Home] Link to the last post on a topic with no answer

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#53]
Quand on publie un nouveau topic, il apparaît bien dans le bloc "Forums" de la home. 

Petit souci, le lien vers la dernière réponse postée (le chiffre "1" encadré et affiché à droite du titre/sous-titre du sujet) ne marche pas, il pointe vers la home.

Certainement une histoire de lien vers le firstPost/lastPost qu'a pas été bien gérée dans le cas d'un sujet sans réponse.

**Comment by firm1** [comment]
C'est bien un bug, certes, mais dans le design final, on n'affichera plus cette zone Forum sur la Home, du coup, pas la peine de corriger ce bug. :-P

**Comment by cgabard** [comment]
Tu corrige les bugs à la SimpleIT toi : "Un bug ? <clic-clic-clic> <supprimer le truc genant> Quel bug ? moi je ne vois pas de bug !"

**Comment by firm1** [comment]
:-P Non mais ce n'est pas un bug, vu que ce n'est pas une fonctionnalité voulue.

**Comment by cgabard** [comment]
Tu réponds encore à la SimpleIT : 

> Non mais ce n'est pas un bug,

Or il y a 3 jours : 

> C'est bien un bug, certes 

(bon ok c'est juste pour te faire chier)

**Comment by GerardPaligot** [comment]
Le lien est géré de la manière suivante :

``` python
{{topic.get_last_answer.get_absolute_url}}
```

Même si la fonctionnalité ne sera plus supportée avec le design final (bien que j'ai quand même des doutes à ce sujet), cela veut quand même dire qu'il y a un bug situé dans la génération de l'url pour la dernière réponse d'un topic. Il faut donc quand même corriger ce bug.

PS : Je trouve ça limite de faire des rapprochements avec Simple IT, mais bon. :)

**Comment by SpaceFox** [comment]
Plains-toi, c'aurait pu être un rapprochement avec IBM.
Là il aurait fallu 3 mois et 1 M€ pour corriger le truc, et ça aurait
nécessité 5 serveurs supplémentaires pour tourner.

**Comment by Coy0te** [comment]
Là où je bosse, on n'a pas de solutions IBM mais on affiche les mêmes délais & budgets pour les correctifs... Champagne ! :/

**Comment by cgabard** [comment]
Je propose qu'on laisse ouvert ce bug pour l'instant. C'est probablement un excellent bug à faire corriger par quelqu'un qui veut commencer avec Django et à contribuer au projet.

**Comment by firm1** [comment]
> Même si la fonctionnalité ne sera plus supportée avec le design final (bien que j'ai quand même des doutes à ce sujet)

Aux dernières nouvelles, dans le design final on a pas de forum sur la page d’accueil.

> cela veut quand même dire qu'il y a un bug situé dans la génération de l'url pour la dernière réponse d'un topic

Non, le "bug" vient du fait que le membre n'as pas encore lu le sujet, et du coup rien n'est renseigné dans la table ReadTopic. Donc bon ...

Vous pensez vraiment que je vais corriger ce bug (qui n'est pas un bug) et qui ne sera jamais utilisé ? Méditez sur [ces belles paroles simplitesques](http://i.imgur.com/SMI9Em8.png)

**Comment by Coy0te** [comment]
> Non, le "bug" vient du fait que le membre n'as pas encore lu le sujet, et du coup rien n'est renseigné dans la table ReadTopic.

On doit pas parler du même bug, moi je parlais bien du comportement décrit par Gérard. get_last_answer retourne `None`, donc l'appel à get_absolute_url ne marche pas.

**Comment by GerardPaligot** [comment]
> Aux dernières nouvelles, dans le design final on a pas de forum sur la page d’accueil.

Ce lien pourrait apparaitre autre part. Par exemple, sur la page /forums/ où le lien vers le topic renverrait à la dernière réponse (comportement normal à mon sens), même chose pour les notifications, etc.

Ceci dit, le bug ne se manifeste pas toujours. Par exemple, le topic [Bug] Articles ne souffre pas du bug.

**Comment by firm1** [comment]
Ah mais vous avez raison en fait, c'est un vrai bug ... honte à moi !

lapidez moi

**Comment by Coy0te** [comment]
> Ceci dit, le bug ne se manifeste pas toujours. Par exemple, le topic [Bug] Articles ne souffre pas du bug.

Comme décrit dans le bug, c'est juste pour les sujets sans réponses. :)

**Comment by GerardPaligot** [comment]
Oui, effectivement. Le bug est donc simple à identifier puisque `topic.get_last_answer` renvoie `None` s'il n'y a pas de réponses. :)

**Comment by Coy0te** [comment]
Ça aussi je l'ai déjà dit 3 messages plus haut... :p

**Comment by GerardPaligot** [comment]
Ca va hein ! :-°

**Comment by firm1** [comment]
Bon après avoir pris mon café, c'est un bug qui n'est pas un bug. Pourquoi ?

`topic.get_last_answer` est censé renvoyer la dernière réponse. Or, le post du PO n'est pas considéré comme une réponse. Donc, la fonction get_last_answer joue bien son rôle. Pour résoudre le problème il faudrait créer un autre fonction `topic.get_last_post` qui renvoi le dernier post (même s'il s'agit du first_post) pour que ça marche. Ce qui signifie qu'il faudrait créer une fonction spéciale pour la page d’accueil et à cet endroit là, donc, pas besoin de se fatiguer pour cela, car cette boite va disparaître avec le futur design ... CQFD !

**Comment by cgabard** [comment]
Sauf que comme l'a fait remarqué @GerardPaligot , une telle fonction serait utile ailleurs, en particulier sur le forum.

Typiquement dans une liste de forum on vois toujours un liens type "dernier message par Machin le ..." en face de chaque topic. En cliquant dessus c'est bien une telle fonction qui devrait etre appelé, non ?

**Comment by firm1** [comment]
@cgabard Si tu jettes un coup d'oeil [par là](http://zestedesavoir.com/forums/communaute/discussions-generales/), tu verras que c'est la même fonction qui est utilisée, et elle est sans faille ici. Pourquoi ? parce qu'elle fait ce qu'elle est censée faire.
Quand il y'a 0 réponses, il te dit qu'il y'a aucune réponse, alors que sur la home, quand il y'a 0 réponse, il te dit qu'il y'a "1 message". Ce qui est fondamentalement différent
