### ISSUE TITLE
generate-fixtures prevenir si zmd est éteint

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5300]
Lorsqu'on fait `make generate-fixtures` (notamment en dehors de install_zds.sh), il faut prévenir quand zmd n'est pas allumé ou l'allumer (et s'il n’était pas allumé, l'éteindre). :)

**Comment by A-312** [comment]
Je réouvre suite à mon test.

**Comment by A-312** [comment]
Je viens de relire entièrement l'issue. Je me suis trompé d'issue.

**Comment by A-312** [comment]
Je viens de relire entièrement l'issue, ce que j'attendais n'est pas vraiment couvert par l'issue. Je m'attendais à vérifier dans zds_install si zmd est allumé, on attend avant de continuer. Je vais ouvrir une autre issue.

**Comment by artragis** [comment]
En effet l'issue ne décrit pas ce problème là.

**Comment by firm1** [comment]
Effectivement, j'ai testé ce qui est décrit dans le ticket, et c'était bon. Si tu as un autre problème dans un autre script, il vaut mieux ouvrir un autre ticket @A-312

**Comment by A-312** [comment]
Quand j'ai créé cette issue `make generate-fixtures` était utilisé dans le script d'installation et en dehors.

> (notamment en dehors de install_zds.sh), 

Je pensais principalement en dehors du script d'installation mais aussi à l'intérieur.
