### ISSUE TITLE
Fixture : Corriger les erreurs de génération du markdown

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5303]
Nous avons un (nouveau) script travis et le script d'installation. Cependant lors de la génération des fixtures nous avons des erreurs provoqués par du markdown. Il faudrait : 

  - Corriger les erreurs qui apparaissent lors de la génération du markdown ; 
  - Ou les rendre plus présentable (convertir le json en text/plain) ; 
  - Ou faire un message en anglais : "Vous avez X erreurs de markdown dans les fixtures, voir fichier fixture_error.log pour plus d'informations".

**Comment by Vanadiae** [comment]
Je confirme qu'il y a beaucoup d'erreurs markdown en json lors de l'installation du site ou lorsqu'on fait `make generate-fixtures`.

**Comment by philippemilink** [comment]
Je n'ai aucun message d'erreur lorsque je fais `make generate-fixtures` (que des messages de DEBUG qui indiquent ce qui a été traduit). Comment vous obtenez ces messages d'erreurs ? (ou est-ce que cette issue est toujours d'actualité ?)

**Comment by A-312** [comment]
Tu n'as pas des messages qui dit "l'image wikipedia n'a pas été trouvé" par exemple ?

**Comment by philippemilink** [comment]
Non...

**Comment by A-312** [comment]
On ne peut pas les rater ça flood la console pourtant

**Comment by artragis** [comment]
c'est sur les contenus à tous les coups?

**Comment by A-312** [comment]
il me semble

**Comment by artragis** [comment]
Donc le seul fix qui est nécessaire, c'est d'aller dans les archives et de mettre https au lieu de http dans les liens wiki. Le reste n'est pas utile.

**Comment by Arnaud-D** [comment]
Je crois que c'est corrigé (peut-être par #6025). Quelqu'un peut confirmer ? Je n'ai pas de souvenir de à quoi ressemblent ces erreurs...

**Comment by philippemilink** [comment]
Je n'ai pas d'erreur en faisant `make generate-fixtures`, donc je ferme.
