### ISSUE TITLE
Tableau des messages postés par un membre tronqué sur mobile

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5304]
[Reporté sur le forum](https://zestedesavoir.com/forums/sujet/12307/bug-extrait-des-messages-postes-par-un-membre-pas-affiches-completement-android/)

Profil d'un membre > Messages postés ([exemple avec Situphen](https://zestedesavoir.com/forums/messages/273/))

Sur mobile, l'extrait des messages est tronqué et on ne peut pas faire défiler la page horizontalement. Pour résoudre le problème, il faut remplacer le `<div class="row">` actuellement autour de `<table>` par `<div class="table-wrapper">` dans [ce fichier](https://github.com/zestedesavoir/zds-site/blob/dev/templates/forum/find/post.html#L46).

**Comment by Vanadiae** [comment]
Je m'en occupe
