### ISSUE TITLE
Améliorer travis.yml

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5308]
Suite à #5299 : 

 - [x] Réfléchir si l'installation de texlive via install_zds est intéressante, on pourrait utiliser l'ancien script de travis.yml pour gagner du temps ;
 - [ ] Regarder si on peut mettre pip (folder zdsenv) en cache. :)
 - [ ] Modifier la teinte des `folder_travis` pour les rendre plus distinctif.
 - [x] Gérer le temps de chaque tache "folder_travis" en sh (pour qu'il s'affiche dans les logs à droite de la ligne) ; Il faut arriver à obtenir ceci : 

```
[0Ktravis_fold:start:install
[0Ktravis_time:start:2674c5f0
...
...
...
[0K[0;36mDone. You can now run instance with `source zdsenv/bin/activate`, and then, `make zmd-start && make run-back`
[00mtravis_time:end:2674c5f0:start=1555703130059288415,finish=1555703859843874408,duration=729784585993
[0Ktravis_fold:end:install
```

Pour afficher ceci aux taches personnalisées : 

![image](https://user-images.githubusercontent.com/18501150/56442608-b1bb6700-62f1-11e9-80df-c64658410b80.png)

**Comment by A-312** [comment]
- [ ] Regarder si on peut mettre pip (folder zdsenv) en cache. :)

**Comment by artragis** [comment]
la réponse est oui

**Comment by A-312** [comment]
@artragis Que doit on mettre en cache tout le répertoire ./zdsenv/ ?

**Comment by artragis** [comment]
Exactement

**Comment by A-312** [comment]
Je pense supprimer ce cache si .travis.yml ou ./script/* est modifié pour palier à tout soucis de MAJ du script.

**Comment by A-312** [comment]
Quelques changements supplémentaires :

 - [x] https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/bash/travis_fold.bash
 - [x] https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/bash/travis_time_start.bash
 - [x] https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/bash/travis_time_finish.bash

**Comment by artragis** [comment]
On va arrêter de jouer avec le feu sur travis je pense.
