### ISSUE TITLE
ZEP-3 : Page listant les tutos en cours d’écriture (ou termine)

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#531]
Ça pourrait être sympa d'avoir une page listant les tutoriels/articles en cours d’écriture, par qui ils sont écris et qu'elle est la date de dernière édition. Ainsi, si quelqu'un a une idée il peut éventuellement se renseigner pour rejoindre un auteur et participer avec lui.
## Voir la source pour le reste des idées

Source : http://zestedesavoir.com/forums/sujet/191/suggestion-une-page-listant-les-tutos-en-cours-decriture-ou-termine

**Comment by cgabard** [comment]
Oui même si je maintient : On doit pouvoir le désactiver.

J'aime beaucoup ta derniere proposition : plusieurs cases a cocher pour indiquer les besoins/envies de l'auteur, info qu'on peut réutiliser pour générer ces pages.

**Comment by Eskimon** [comment]
Tout ca c'est dans [la ZEP-3](http://zestedesavoir.com/forums/sujet/666/zep-03-page-resumant-les-tutos-en-redaction/) :)

**Comment by SpaceFox** [comment]
Corrigé, mergé, fermé !
