### ISSUE TITLE
Les quatre menus déroulants en haut à droite ne se déroulent plus sous firefox

### ISSUE THREAD

**Issue by Fumble** [zestedesavoir/zds-site#5310]
Salut,

Je viens de remarquer que les 4 menus déroulants ne se déroulent plus lors d'un clic sur eux: MP, notifications, alertes et profils.

Le problème est avec Firefox 66 sous Windows 10: l'erreur "Error: Permission denied to access property "apply"" apparait dans la console de Firefox lors du clic.

![image](https://user-images.githubusercontent.com/634461/56515950-73b08400-6539-11e9-92dd-94957d75c798.png)

Le problème n'est reproductible qu'avec FF sous Windows10. Edge fonctionne.

**Comment by Fumble** [comment]
Il semblerait que ce soir l'extension KeepassXC qui pose problème. Etrange...

**Comment by AmauryCarrade** [comment]
J'observe le même comportement depuis hier soir, la même extension KeePassXC étant installée. C'est pas super pratique :p

Par contre, je suis sous Firefox 67 (67.0b10 _developer edition_), sous ArchLinux.

**Comment by Fumble** [comment]
En fait sous Manjaro aussi ça bug. Problème similaire reporté upstream par d'autres utilisateurs: https://github.com/keepassxreboot/keepassxc-browser/issues/481
