### ISSUE TITLE
nvm ne s'ajoute que dans .bashrc

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#5311]
Et plus précisement, pas dans .zshrc.

Je parle des 3 lignes suivantes : 

```bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

2 possibilité : 

- C'est un bug chez nous, dans ce cas il faut le corriger
- C'est un "bug" chez nvm, dans ce cas un petit bout dans la doc d'installation ne ferait pas de mal.

**Comment by A-312** [comment]
Depuis quand ? Ton install est récente ? (à les dernières modifications de cette semaine ?)

**Comment by gustavi** [comment]
J'étais sur master et pas dev, au temps pour moi.
