### ISSUE TITLE
Probleme rendu LaTeX dans ZDs

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5315]
> Bonsoir tout le monde,
> 
> En relisant mon tuto sur shadertoy, j'ai remarqué que toutes mes formules mathématiques(qui s'affichaient pourtant correctement il y a quelque semaines) semblaient avoir été passées au mixer: les caratères sont positionnés au mauvais endroit et se superposent souvent avec texte alentours. J'ai essayé avec un autre navigateur, mais le problème persisite.
> 
> J'aimerais donc savoir si il y a eu des changements sur la manière dont les formules doivent etre encodées, ou si le problème vient de moi.
> 
> Merci beaucoup

Sujet : https://zestedesavoir.com/forums/sujet/12446/probleme-rendu-latex-dans-zds/
*Envoyé depuis Zeste de Savoir*

**Comment by artragis** [comment]
bug de zmd

**Comment by Situphen** [comment]
[Ce commit](https://github.com/Situphen/zds-site/commit/a98a617614381e2f4b6da0438e77b54509381415) corrige le problème sauf erreur de ma part. J'ai testé l'affichage de cette formule qui s'affiche mal en bêta et en prod : 

```
$$\begin{pmatrix} 1 & 0 & \cdots & 0 \\ 0 & 1 & & \vdots \\ \vdots & &\ddots & 0\\ 0 & \cdots & 0 & 1 \end{pmatrix}$$
```

**Comment by Situphen** [comment]
On vient d'avoir un retour comme quoi `$\sqrt{x}$` ne fonctionne toujours pas ! Ça utilise une balise `<svg>` filtrée par zmd.

**Comment by Situphen** [comment]
Résolu avec zmarkdown 5.14.1
