### ISSUE TITLE
Email pour les notifications

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#532]
Beaucoup de noob/personne en manque de temps aime utiliser les fonctions "me notifier par email lors d'une réponse". Pourquoi pas la rajouter ?

**Comment by cgabard** [comment]
pourquoi pas en effet

**Comment by firm1** [comment]
Pour ceux qui voudraient ce lancer, pour mettre cette fonctionnalité (me notifier par email lors d'une réponse a un sujet) en place il faudrait : 
- ajouter dans le modèle de donnée de [TopicFollowed](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/forum/models.py#L313) un champ [booléen](https://docs.djangoproject.com/en/dev/ref/models/fields/#booleanfield) du genre `email`. Ce champ sera mis à jour lorsque l'utilisateur aura sélectionné le fameux bouton "notifier par email" du topic.
- ajouter le template le bouton qui va bien du même acabit que le bouton [suivre/ne pas suivre ce sujet](https://github.com/Taluu/ZesteDeSavoir/blob/dev/templates/forum/topic.html#L38). Cependant le href du lien pour notifier par mail devra avoir un autre paramètre que `?solved=`. On pourrait prendre `{% url "zds.forum.views.edit" %}?topic={{ topic.pk }}&page={{nb}}&email=1`
- maintenant il ne reste plus qu'a modifier la view qui va bien, en rajoutant la nouvelle clé `email` comme c'est fait pour [solved](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/forum/views.py#L371)

PS: ne pas oublier comme précisé dans le readme de toujours faire une update migration du model (`python manage.py schemamigration app_name --auto`) quand celui-ci est modifié.

**Comment by cgabard** [comment]
Je crois que tu as oublié un point : envoyer l'email quand il y a un nouveau message
