### ISSUE TITLE
404 sur un tutoriel en rédaction suite à un renommage

### ISSUE THREAD

**Issue by entwanne** [zestedesavoir/zds-site#5320]
Bonjour,

En voulant adapter un billet en tutoriel, j'ai utilisé les fonctionnalités d'import/export du site.
Le billet avait pour *slug* `variables-scopes-et-closures-en-python` et celui généré pour le tutoriel a donc été `variables-scopes-et-closures-en-python-1`.
Préférant que le tuto adopte le *slug* canonique j'ai édité le titre du billet pour ajouter « (billet) » et édité ensuite le tutoriel sans rien changer.

Les *slugs* ont bien été modifiés, mais cela provoque une erreur d'accès au tutoriel en rédaction, qui pointe maintenant sur une page 404 : https://zestedesavoir.com/contenus/3157/variables-scopes-et-closures-en-python/
Il ne m'est pas possible de supprimer le tuto en question et donc de libérer le *slug*.

Merci.

**Comment by artragis** [comment]
attends tu veux dire que tu as enfin un cas de reproduction de ce bug qui nous casse les couilles depuis des plombres?

pour ton tuto, il est de nouveau accessible à l'ancien slug.

**Comment by artragis** [comment]
Parlé trop vite, y'a eu des erreurs plus importantes

**Comment by artragis** [comment]
bon on avait deux problèmes 

- changement des slugs non désirés
- le sha enregistré est celui du billet et non du tuto du coup ça merdait 

il est dispo ici https://zestedesavoir.com/contenus/3157/variables-scopes-et-closures-en-python-2/.

**Comment by artragis** [comment]
https://sentry.sandhose.fr/zeste-de-savoir/zds-site/issues/36/

**Comment by entwanne** [comment]
Tiens c'est amusant. Pensant que le tutoriel avait disparu (avant de le voir apparaître dans ma liste de tutos), je l'avais réimporté, ce qui lui avait généré pour *slug* `variables-scopes-et-closures-en-python-2`.
Ce qui veut dire qu'il y a eu pendant un moment deux tutoriels avec le même *slug*, je ne pensais pas que c'était possible.

**Comment by entwanne** [comment]
Hum, d'ailleurs je viens de supprimer celui que je pensais être le doublon et l'original est de nouveau en 404.

**Comment by artragis** [comment]
en bdd il n'y a plus que le billet.

**Comment by entwanne** [comment]
Alors c'est étrange parce que je l'ai toujours sur la liste de mes tutoriels (https://zestedesavoir.com/contenus/tutoriels/285/).

**Comment by artragis** [comment]
je checkerai ça demain du coup, mais j'ai plus rien dans les dossiers de contenus.

**Comment by entwanne** [comment]
Je l'ai importé à nouveau, ça a bien fonctionné et j'ai pu récupérer le slug `variables-scopes-et-closures-en-python` pour le contenu `3163`.

Mais j'ai toujours un `3157/variables-scopes-et-closures-en-python-2` pointant vers une 404 qui persiste dans la liste de mes tutos.

**Comment by artragis** [comment]
je supprimerai celui-là plus tard.

Avant ça je vais tenter de transformer ton cas de test en mode automatique pour que je puisse ensuite corriger tout ça.

**Comment by entwanne** [comment]
Ok, pas de problème, merci !

**Comment by artragis** [comment]
Je te propose de regarder l'avancement de #5342 pour voir où ça en est. En tout cas j'ai un test qui foire à cause du bug c'est cool.

**Comment by entwanne** [comment]
Salut,

Je vois que le ticket a été automatiquement fermé suite à la résolution du problème lié, mais j'ai de mon côté toujours dans mes contenus en rédaction un élément pointant vers une 404 : https://zestedesavoir.com/contenus/3157/variables-scopes-et-closures-en-python-2/
Est-ce qu'il nécessite une opération manuelle pour être supprimé ?

**Comment by artragis** [comment]
Alors le ticket a été clos car la résolution technique a été mergée dans dev, mais on n'a pas encore déployé le tout.

Pour le cas de ton tuto en 404 il faut que j'aille le retirer
