### ISSUE TITLE
Travis n'apprécie pas qu'on modifie uniquement /asset/

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5326]
Suite à mes modifications, mes conditions n'ont pas la logique pour supporter cette condition : https://github.com/zestedesavoir/zds-site/blob/3681389cf1350b51c272d2f6b2f4764e32492372/scripts/ci_turbo.sh#L20-L31

Ce qui entraine une erreur comme ci-dessous dans #5318 : 

```
> zmarkdown@5.13.0 server /home/travis/build/zestedesavoir/zds-site/zmd/node_modules/zmarkdown
> pm2 start -f server/index.js -i 3 --max-memory-restart 150M "--silent"
Traceback (most recent call last):
  File "manage.py", line 45, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 45, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 45, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
!! Cannot generate-fixtures (use `-data` to skip)
The command "./scripts/install_zds.sh --answer-yes --detect-os-version --travis-output $zds_install_argument" failed and exited with 1 during .
```
Source: https://travis-ci.org/zestedesavoir/zds-site/jobs/528968200

-----------

Il est donc nécessaire d'adapter la logique de code de : 

https://github.com/zestedesavoir/zds-site/blob/3681389cf1350b51c272d2f6b2f4764e32492372/scripts/travis_header.sh#L14-L35

**Comment by A-312** [comment]
@artragis Que dois-je faire si j'ai none dans le code ci dessous ? Dois je arrêter le script dès le départ et ne rien installer ?

https://github.com/zestedesavoir/zds-site/blob/3681389cf1350b51c272d2f6b2f4764e32492372/scripts/ci_turbo.sh#L27

**Comment by artragis** [comment]
je ne pense pas qu'il y ait besoin de s'en préoccuper.

**Comment by A-312** [comment]
@artragis Justement si : https://github.com/zestedesavoir/zds-site/pull/5318#issuecomment-490062465
