### ISSUE TITLE
Améliorer l'insertion des smileys dans l'éditeur

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5339]
> Salut les clem' ! :D
> 
> Prenons le cas de ce beau clemoji :D
> 
> Si j'écris : :D
> 
> Le clemoji s'affiche bien car il est en fin de ligne.
> 
> **Problème : ** si j'écris" (salut :D)", alors je serais obligé de rajouter un espace après le clemoji **à la main** et c'est bien ça le problème.
> 
> **Comportement attendu : **que lorsqu'on clique sur un clemoji dans la liste, ça écrive : " clemoji " (notez bien l'espace avant et **après** le clemoji) tel que si on met un clemoji depuis le menu, on puisse continuer à écrire sur la même ligne sans se soucier d'avoir oublié un espace après le clemoji.

Sujet : https://zestedesavoir.com/forums/sujet/12516/bug-clemoji-sans-espaces/
*Envoyé depuis Zeste de Savoir*

**Comment by Vanadiae** [comment]
Je m'en occupe dans la semaine selon si j'ai le temps, sinon un peu plus tard.

**Comment by Situphen** [comment]
Ce n'est pas urgent de toutes façons. N'hésites pas à demander de l'aide si tu as besoin ! :)

**Comment by Vanadiae** [comment]
Je pense que oui mais je ferai au fur et à mesure. Déjà j'ai réussi à installer le site en local, c'est déjà ça.
