### ISSUE TITLE
Contenu - Lien vers le brouillon depuis la bêta

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5340]
> Bonjour,
> 
> Depuis la version en bêta d'un tutoriel, le lien d'accès à la version brouillon est présent même si on n'a pas les droits. [Voir par exemple, la bêta du tutoriel C++](https://zestedesavoir.com/contenus/beta/822/la-programmation-en-c-moderne/).

Sujet : https://zestedesavoir.com/forums/sujet/12519/lien-version-brouillon-depuis-beta/
*Envoyé depuis Zeste de Savoir*

**Comment by A-312** [comment]
Pourrait être fait en même temps que #5277 sauf si quelqu'un le fait avant. ;)

**Comment by Vanadiae** [comment]
Je m'en occupe
