### ISSUE TITLE
Performances de LaTeX sur ZdS

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5341]
> Hello,
> 
> Ce matin j'ai voulu lire [cet excellent article](https://zestedesavoir.com/articles/2901/le-kilogramme-nouveau-est-arrive/) sur mon téléphone, un Huawei P8 qui n'est pas tout jeune mais qui tourne encore tout à fait correctement.
> 
> Sauf que quant je suis arrivé sur la page, j'ai eu une notification de _Processing math: XX%_ pendant plusieurs dizaines de secondes, et après une page qui laggue sérieusement (scroll non fluide, menu à peu près inutilisable).
> 
> Après investigation sur PC, je vois que l'article contient 143 formules mathématiques (plus exactement, 143 instances de la classe `inlineMath` dans le code HTML renvoyé). C'est beaucoup, visiblement trop pour un affichage sur un mobile pas trop puissant. D'où 3 questions :
> 
> 1. Il me semblait que le problème avait déjà été soulevé mais je n'ai pas retrouvé ça, est-ce le cas ?
> 2. Peut-on faire quelque chose à ce sujet ?
> 3. Tant que rien n'a été fait, peut-on demander aux auteurs de n'utiliser les balises LaTeX **que** pour les cas où c'est nécessaire ? Par exemple utiliser « tension _U_ » et non « tension $U$ » – c'est moins élégant mais ça évite de mettre le système de rendu à genoux en multipliant les formules.
> 

Sujet : https://zestedesavoir.com/forums/sujet/12522/performances-de-latex-sur-zds/
*Envoyé depuis Zeste de Savoir*

**Comment by A-312** [comment]
Au lieu de faire un `onload`, on devrait faire selon `onscroll`. Ou retarder chaque élément de X secondes, selon la position de la page.

**Comment by Situphen** [comment]
Je pense qu'on devrait surtout charger MathJax seulement sur les anciens contenus et messages, il faut réussir à mieux les détecter.

**Comment by A-312** [comment]
Il faudrait charger le JS dynamiquement.

**Comment by Situphen** [comment]
Fermé avec #5353
