### ISSUE TITLE
Insertion de tweet

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#535]
Vu qu'on peut ajouter des vidéos, ca serait sympa si on pouvait aussi ajouter des tweets ! Vivons 2.0 !
Bon bien sur, c'est loin d'être une priorité...
Au cas où, voici [la doc](https://dev.twitter.com/docs/embedded-tweets) !

---

http://zestedesavoir.com/forums/sujet/54/suggestion-insertion-de-tweet

Retenu par certains, rejeter par d'autres...

**Comment by Alex-D** [comment]
J'aime l'idée de base. Par contre en y réfléchissant, ça veut dire que ça nécessite du JavaScript et autre.

Du coup, non, je ne suis pas pour.

**Comment by geoffreyc** [comment]
Pourquoi?

2014-05-16 16:14 GMT+01:00 DEMODE Alexandre notifications@github.com:

**Comment by Alex-D** [comment]
Car ma vision des choses c'est qu'on ne charge que ce qu'on a besoin. On a pas besoin de 100ko de JS pour gérer des tweets. Donc on utilise les blockquote et un lien vers le tweet, pour moi c'est amplement suffisant.

Surtout que ça alourdi la syntaxe déjà bien complexe, pour finalement ne pas apporter grand chose.

**Comment by firm1** [comment]
Juste pour ma culture (je n'ai pas accès au lien de la doc au boulot), pourquoi faudrait su JS ?

Pour moi il suffit que le parseur markdwon crache une balise de type figure avec une classe tweet et du texte dedans, avec éventuellement un lien, pour que le css affiche de manière design le tweet.

**Comment by Alex-D** [comment]
Je pense que les gens qui ont proposé ça veulent afficher le tweet avec les outils de Twitter. Et pour gérer les trucs genre les boutons Fav, RT, etc ça utilise du JS.

Car j'ai envie de vous dire : si on le fait pour Twitter, pour quoi pas Facebook, Google+ et toute la tripoté ? Pour moi c'est inutile.

**Comment by firm1** [comment]
Euh, moi je veux pas tous les boutons twitter moi, je veux juste un design adapté. On peut faire pareil pour les autres je pense, il suffit de rajouter la bonne classe à l'élement figure. 'fin je trouve qu'on le fait déjà avec youtube, donc ...

**Comment by Alex-D** [comment]
Youtube ça importe l'information.

Utiliser blockquote + lien vers le tweet VS un truc dédié = la même chose.

Donc je ne vois pas l'intérêt. Après c'est plutôt une issue qui aurait sa place sur zmarkdown... ça dépend si @cgabard pense que c'est jouable sans que ce soit le bazar. Et si tout le monde (ou une grande partie) est d'accord avec ça.

Si ça doit se faire, alors il faudrait que ce soit une balise qui prenne le lien du tweet en paramètre, pour que le contenu soit récupéré depuis l'API Twitter et avoir une certaine intégrité de l'information.

Enfin bref, de toute évidence non prioritaire si c'est accepté.

**Comment by Eskimon** [comment]
Puisque j'avais proposé l'idée je vais apporter mes 2 sous...
Effectivement l'idée était d'apporter tout le bordel de Twitter avec...
La différence avec FB et G+ c'est que justement, FB et G+ non pqs ce genre de joli intégration et ne sont pas vraiment vecteur de "news" par ce biais (enfin perso, si je fais un peu de veille par Twitter, j'en fait pas du tout sur G+ et FB)...
Mais sinon on est d'accord : Papa Noel !

**Comment by Alex-D** [comment]
Non non, Facebook a fait une box du même type que Twitter à ce niveau là. Et ça m'étonnerais pas G+ ait la même chose ^^

Qui dit tout le bordel = non pour ma part. Je passe pas mon temps à opti tout pour que ça se charge vite pour que derrière on mette 100ko de JS pour 1 tweet toutes les 15 pages.

**Comment by cgabard** [comment]
en fait en soit si on est capable de se décider sur : 
- La syntaxe markdown pour ça
- Le html qui doit être généré

ça ne pose pas de probs "a priori"

Pour la syntaxe il y a plusieurs solutions. Celle que naturellement je préfererais serait de simplement reprendre celle de la vidéo. Alors on en profite pour la repenser et présenter en tant que balises "d'insertion de contenu" : Tu met un liens youtube, ça t'intessere la vidéo, tu met un liens tweeter ça t'interesse le tweet, etc. Cette syntaxe a le gros avantage de déjà être présente dans le markdown, on ne casse a priori pas grand chose et on évite de les multiplier. On regroupe aussi des sémantiques communes. Et a terme on pourrait étendre le principe comme insérer une carte google map si c'est un tel lien qui est place, les status FB public, etc. 

Donc niveau technique ça ne me fait pas du tout peur. Là ou par contre je vais repousser la mise en place c'est que outre le fait qu'il y a encore quelques bugs d'ouverts, il faut aussi penser que pour les exports pdf/ebook c'est une autre sortie qu'il faut générer. Ça ce n'est actuellement pas ou mal géré, même pour les trucs qu'on a déjà comme la video ou les boites d'infos. Cela me semble donc plus prioritaire.

**Comment by geoffreyc** [comment]
Ce bout de JS est tellement populaire qu'il doit être caché par 90% des
visiteurs avant meme de foutre le pied sur ZdS.

2014-05-16 16:45 GMT+01:00 DEMODE Alexandre notifications@github.com:

**Comment by Alex-D** [comment]
_Restons calme_ ><"

Un fichier JS, quel qu'il soit, en cache ou pas, il doit être exécuté, l’exécution ça bouffe du temps processeur, moins y en a (ou plus il est optimisé) plus le site est léger et rapide. Actuellement le site tourne sur mon HTC Wildfire : Android 2.2 ou 2.3 sans ralentissement particuliers.

Je ne fais pas des efforts d'un côté pour qu'on casse tout avec des features inutiles. Sinon à partir de là, je n'optimise plus rien et on s'en moque on part sur du "ça marche, osef, t'as qu'a avoir un ordi puissant et ne pas utiliser un navigo pourri".

---

C'est pas bête dans l'idée de l'insertion de média, mais du coup ça va mettre une blinde de JS/iframes partout... autant les vidéos j'en vois l'intérêt car il peut y avoir des tutos ou quoi qui s'en servent. Autant un Tweet, déjà je trouve l'intérêt limité. Un carte GMaps, vu la largeur des messages, t'as plus vite fait de cliquer sur le lien.

Aussi, ce genre de chose impose aux petites connexion de gros volumes à charger sans leur demander leur avis. J'suis pas certain qu'un utilisateur soit heureux de consommer 5Mo pour charger une page de notre site, juste parce qu'il y a une vidéo YT, un tweet et un lien vers GMaps.

**Comment by geoffreyc** [comment]
> > _Restons calme_ ><"

Tu t’engrènes tout seul la, on peut quand même avoir une discussion et une
différence d'opinion sans que tu chauffes ton slip.

> > Un fichier JS, quel qu'il soit, en cache ou pas, il doit être exécuté,
> > l’exécution ça bouffe du temps processeur, moins y en a (ou plus il est
> > optimisé) plus le site est léger et rapide. Actuellement le site tourne sur
> > mon HTC Wildfire : Android 2.2 ou 2.3 sans ralentissement particuliers.

Dans ce cas la il faudrait faire des tests pour voir l'effet que ca aurait
sur le site, réellement. Si ça ajoute 1 milliseconde a l'excecution de la
page, je pense qu'on peut se permettre de le mettre.

> > Je ne fais pas des efforts d'un côté pour qu'on casse tout avec des
> > features inutiles. Sinon à partir de là, je n'optimise plus rien et on s'en
> > moque on part sur du "ça marche, osef, t'as qu'a avoir un ordi puissant et
> > ne pas utiliser un navigo pourri".

Tu vas d'un extrême a un autre, c'est embêtant. C'est pas parce qu'on
discute de la possibilité d'ajouter une feature qu'on va tout de suite
casser tout tes efforts d'optimisation. Faut faire des compromis, ca veut
pas pour autant dire que le site va devenir une uzine a gaz si on integre
un truc qui te plaie pas.

2014-05-16 16:55 GMT+01:00 DEMODE Alexandre notifications@github.com:

**Comment by SpaceFox** [comment]
Personnellement, je m'en fous, j'ai Ghostery : tout ça est bloqué par
défaut.

Cela dit, j'aime pas intégrer des boutons de réseaux sociaux ou autres. Je
considère mes lecteurs assez intelligents pour copier / coller le lien tout
seuls s'ils le veulent.

**Comment by cgabard** [comment]
Je parlais de la réalisation, mais je ne donnais pas d'avis sur la question. Il y a toujours moyen de travailler la question, on peut tres bien l'autoriser sur les articles/tutos mais pas sur le forum et du coup passer par le process de validation qui va virer les abus.

Apres moi je m'en fout honnetement. Je le coderais si c'est validé mais tres honnetement je m'en tape, d'autant qu'on ne fera pas le support via twitter, l'interet sera plus limité que sur d'autres sites ;)

**Comment by Alex-D** [comment]
C'est pas parce que je ne suis pas d'accord ou que ça va casser mes
efforts. C'est un constat. Ce genre de chose a déjà nécessité une à deux
secondes de chargement sur une connexion classique, à cause des temps de
réponses énorme : c'est juste pas envisageable.

Filtrer par article tuto et tout ça devient compliqué pour pas grand chose
non ?

En fait, j'aimerais qu'on me trouve un avantage au JS intégré sur une
version HTML. Et un avantage à une balise spécifique par rapport à un
simple blockquote.

**Comment by cgabard** [comment]
En réalité il y a aussi la possibilité de le faire côté serveur, j'imagine
que via l'API tweeter on peut chopper le texte et l'auteur, non ?

Du coup on peut imaginer le faire automatiquement et créer une balise
d'auto citation. Avec un truc genre : `Source: ![http://twitter...]`

Le HTML généré est une balise citation standard (donc mieux intégré et plus
rapide) que le parseur aura construit tout seul...
Le 16 mai 2014 18:25, "DEMODE Alexandre" notifications@github.com a écrit
:

**Comment by Alex-D** [comment]
C'est exactement ce que je proposait en solution alternative un peu plus
haut.
Mais du coup faut bien protéger pour que API Twitter down = ZdS up quand
même.

**Comment by Alex-D** [comment]
Et @firm1 pensait à ça aussi si j'ai bien lu.

**Comment by ShigeruM** [comment]
Selon comment c'est fait ça peut être très chiant pour les (nombreuses)
personnes se connectant depuis le boulot, où les sites comme Twitter sont
bloqués. Ça fait des trous dans les pages, c'est lent et on a pas l'info
alors qu'avec un copié collé tout le monde est content.

Bref, mon avis c'est que c'est beaucoup d'énergie pour rien, voir pour pire
que mieux.
Le 16 mai 2014 18:38, "DEMODE Alexandre" notifications@github.com a écrit
:

**Comment by Coy0te** [comment]
Pareil que SpaceFox, je tourne avec Ghostery. Mais je trouve que si on peut le faire sans le truc qui pourrit le temps de cahrgement de page dans les endroits/pays où Twitter rame du cul, c'est pas plus mal (en Chine je détestais aller sur OC, principalement à cause des merdes Facebook et compagnie).

**Comment by firm1** [comment]
L'idée est qu'a partir du lien twitter, le serveur se charge de trouver le texte du tweet et le renvoi avec une classe css adéquate pour que le front l'affiche proprement et avec une belle présentation comme Alex sait le faire.

Donc que des avantages : 
- Pas de chargement de JS, 
- Le serveur ne souffre pas tout le temps (le html est mis en cache)
- Si twitter est bloqué au boulot tu peut quand même lire le tweet 
- Pour un article ça peut être interessant

Bref, que du bonheur. Le seul qui va devoir bosser un peu plus que les autres c'est @cgabard

**Comment by Alex-D** [comment]
Rendez-vous là bas pour la suite : https://github.com/zestedesavoir/Python-ZMarkdown/issues/24
