### ISSUE TITLE
Notification permanente suite à un retrait de permissions

### ISSUE THREAD

**Issue by nils-van-zuijlen** [zestedesavoir/zds-site#5356]
Bonjour,

J'ai une notification pour un message d'ache dans le calendrier des publications dans le forum Staff, mais je n'ai plus accès à ce forum comme je ne suis plus dans le staff. La notification est donc irrésoluble.

Lors d'un retrait de permissions, les notifications rendues inaccessibles ne sont pas supprimées.

Sujet : https://zestedesavoir.com/forums/sujet/12576/notification-permanente-suite-aun-retrait-de-permissions/
*Envoyé depuis Zeste de Savoir*

**Comment by A-312** [comment]
Selon le message de spacefox, ça marche aussi pour les nouvelles notifs (lors d'un nouveau message)

**Comment by nils-van-zuijlen** [comment]
Je confirme ce que dit spacefox, j'en ai une nouvelle.

**Comment by Situphen** [comment]
Bon, je pense qu'on peut considérer ça bloquant car c'est un problème qui touche une dizaine d'ex-staff et qui doit être assez chiant au quotidien.

@artragis Tu es d'accord ?

**Comment by Situphen** [comment]
Je pense qu'il y a moyen de s'inspirer de `_handle_private_forum_moving` ([lien](https://github.com/zestedesavoir/zds-site/blob/dev/zds/notification/receivers.py#L228)) car c'est le même problème. Au lieu de bouger un sujet d'un forum public vers un forum privé, on enlève l'accès d'un membre à un forum privé.

**Comment by artragis** [comment]
C'est pas bloquant, même si comme tu as déjà un fix de dispo ça sera probablement disponible à la prochaine release.
