### ISSUE TITLE
Cleanup des tickets

### ISSUE THREAD

**Issue by Vanadiae** [zestedesavoir/zds-site#5360]
À l'heure où j'écris ces lignes, il y a 272 tickets sur le repo dont certaines qui datent de 5 ans (oui oui 5). Je pense donc qu'il faudrait faire du ménage dans les 11 pages de tickets en vérifiant si elles sont encore d'actualité ou si elles peuvent être fermées. En cas de doute, faire un petit "On en est où ?" pour notifier ceux qui ont participé au ticket.

Le ménage de printemps ... En printemps. :smile_cat:

**Comment by artragis** [comment]
Merci de le rappeler, même si c'était dans ma todo list de juin.

Je ferme ce ticket pour ne pas polluer le backlog mais le ménage a débuté.
