### ISSUE TITLE
Accéler le build-front du makefile

### ISSUE THREAD

**Issue by Vanadiae** [zestedesavoir/zds-site#5363]
Lorsque qu'on lance `make build-front`, ça met au moins une minute à tout build avec gulp. À la ligne de build-front, il faudrait changer ça `yarn run build` par `yarn run build --speed`, réduisant le temps de build de gulp à ~7s.

**Comment by Situphen** [comment]
Je ne sais pas si c'est une bonne idée car l'option `--speed` n'est pas anodine. Elle désactive les différentes opérations qui réduisent la taille des fichiers CSS, JS et des images.

Actuellement cette option utilisée par la commande `make watch-front` (et indirectement par `make run`) prévue pour ceux qui travaillent sur le *front-end*. Tu peux faire des modifications de JS ou CSS puis voir le résultat presque instantanément en rechargeant la page web.

Faut-il utiliser cette même option pour accélérer la commande `make build-front` ? Je pense que cette commande est presque toujours utilisée lors de la QA des PRs qui touchent au *front-end*. Si on active l'option, ça veut dire que les opérations qui réduisent la taille des fichiers JS, CSS et des images ne seront pas testés. Travis ne peut pas détecter de bug *front-end* car on n'a presque pas de tests unitaires pour ça. S'il y a un problème, on risque donc de le découvrir en bêta ou en prod.

**Comment by Vanadiae** [comment]
Mais du coup quand je fais des tests, je peux activer l'option ou non? Du coup si j'ai des changements à faire sur le frobt, j'utilise make watch-front ?

**Comment by A-312** [comment]
Si je ne dis pas de bêtise : `npm run gulp watch -- --speed`

**Comment by Situphen** [comment]
Actuellement, `make build-front` est un raccourci vers `yarn run build` et `make watch-front` est un raccourci vers `yarn run watch --speed`. Si tu veux générer *une seule fois* le *front-end* en activant l'option `--speed`, tu as deux possibilités. Soit tu lances la commande `make watch-front` et tu l'arrêtes avec `Ctrl + C` une fois que le *front-end* a été généré, soit tu lances la commande `yarn run build --speed`. :)

Je pense que le choix d'utiliser `make build-front` pour la QA et `make watch-front` pour le développement correspond bien à nos besoins, et les deux pouces jaunes sur mon message ont l'air de conforter cette idée. Je t'invite à utiliser `make watch-front` quand tu code car ça fait gagner du temps ! N'hésite pas à commenter ce ticket ou à discuter avec nous sur Discord si jamais tu as un soucis avec ce choix. Je fermerai le ticket dans quelques jours si ce n'est pas le cas. :)

**Comment by Vanadiae** [comment]
Ok j'ai compris l'intérêt. En revanche je n'ai pas le lien discord. Je ferme le ticket.
