### ISSUE TITLE
Texte "Ajouter une section" surligné lors du hover, alors qu'il ne devrait pas l'être

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5366]
Bonjour,

Il manque `text-decoration:none;` sur le hover du bouton "Ajouter une section" 

![image](https://user-images.githubusercontent.com/18501150/60397920-991dc780-9b52-11e9-8fd8-9672d1b0b6eb.png)

**Comment by Vanadiae** [comment]
Texte "Ajouter une section" ~~surligné~~ **souligné** lors du hover, alors qu'il ne devrait pas l'être

**Comment by HSleymn** [comment]
Le problème est résolu ?
