### ISSUE TITLE
Export HTML non support de l'UTF-8

### ISSUE THREAD

**Issue by Vanadiae** [zestedesavoir/zds-site#5367]
**[Lien](https://zestedesavoir.com/forums/sujet/12672/bug-export-html-contenu-pas-en-utf-8/)** du sujet sur *Zeste de Savoir*.

Par exemple [ici](https://zestedesavoir.com/tutoriels/html/249/rediger-sur-zds.html) sur le sujet pour rédiger avec zmd, le rendu est affreux à cause d’un oubli de la balise meta utf-8 dans le header de la page.
# QA

* Se rendre sur la page d’un contenu publié
* Panel "Télécharger" > "HTML"
* Regarder comment sont formés les accents, etc.

# Comportement observé :

Les caractères UTF-8 sont remplacés par des choses ressemblant vaguement à `Ã©` ou bien `â€™Ã`
# Comportement attendu :

Tous les caractères sont bien rendus

**Comment by Situphen** [comment]
Je ferme étant donné que l'export HTML est partiellement retiré et le sera bientôt complètement.
