### ISSUE TITLE
Envoi de MP à un banni / compte supprimé

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#537]
- <del>Si un membre est banni, l'expediteur du MP n'est pas prévenu que le destinataire ne pourra pas lire le MP</del>
- Nouvelle question. Si un membre se desinscrit mais que j'avais un MP avec lui, que se passera t'il ? Mon MP arrivera t'il a bon port ? Le membre désinscrit sera t'il notifié/spammé du nouveau MP ?

---

http://zestedesavoir.com/forums/sujet/137/question-test-mp-a-un-banni

**Comment by firm1** [comment]
> Nouvelle question. Si un membre se desinscrit mais que j'avais un MP avec lui, que se passera t'il ? Mon MP arrivera t'il a bon port ? Le membre désinscrit sera t'il notifié/spammé du nouveau MP ?

Cette question sera réglée quand on saura quoi faire d'un désinscrit. 

Pour le point 1, je prend

**Comment by SpaceFox** [comment]
Point 1 mergé.

**Comment by Eskimon** [comment]
Pour le point 2 je suppose qu'on pourrait déclencher un truc pour que quand un membre se désinscrit, il parte aussi de tout ses MPs (comme si il clickait sur le bouton "Quitter le MP")

**Comment by firm1** [comment]
Il me semble que la question de la désinscription est plus large que ça.
Elle concerne tout contenu du site et du coup faudrait fermer celle ci et
en faire une plus générale.

**Comment by Alex-D** [comment]
La suite se passe dans l'issue plus globale #668
