### ISSUE TITLE
Renvoyer l'email de confirmation  et afficher une alerte à la connexion

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5371]
Bonsoir,

J'avais relevé le problème d'un compte zombie dans un autre [sujet](https://zestedesavoir.com/forums/sujet/12738/membre-inscrit-mais-inexistant). L'erreur venait d'un compte dont l'email n'a pas été validé. En fait, si le compte n'est pas activé par email, à la connexion, le message s'affichant est celui d'un des champs contenant une erreur. Impossible non plus de créer un nouveau compte avec le même email.

Ne faudrait-il pas afficher un message donnant l'information que le compte doit d'abord être activé avant d'être utilisé ? Si oui, il faudrait ajouter un lien permettant de renvoyer l'email de confirmation s'il n'a pas été reçu ou qu'il a été supprimé.

Sujet : https://zestedesavoir.com/forums/sujet/12740/email-de-confirmation-et-connexion/
*Envoyé depuis Zeste de Savoir*

**Comment by artragis** [comment]
Comme je le disais sur le forum, il faut trouver un moyen de proposer un lien pour envoyer un mail de confirmation. MAIS on ne changera pas le message d'erreur, il vaut mieux donner le moins d'info possible sur les formulaires de credentials, pour éviter une attaque par bruteforce.
