### ISSUE TITLE
 Profil et sécurité: rajouter un champ « Mot de passe »

### ISSUE THREAD

**Issue by arobase-che** [zestedesavoir/zds-site#5372]
Depuis ZdS:

> Bonsoir,
> 
> J'ai remarqué qu'il n'y avait pas de validation quand l'adresse email est modifié. Cela signifie que si quelqu'un passe sur l'ordinateur et modifie l'email, il pourra par la suite changer le mot de passe et prendre le contrôle du compte.
> 
> Aussi, ne serait-il pas judicieux de rajouter un champ de texte à remplir sur la page de la désinscription afin de prévenir les potentiels erreurs ?
Source: [Helmasaur](https://zestedesavoir.com/forums/sujet/12693/profil-et-securite/?page=1#p205342)

La correction semble simplement d'ajouter un champ « Mot de passe » sur les pages « Pseudo et courriel » et « Désinscription ».

**Comment by Situphen** [comment]
Si quelqu'un souhaite s'occuper de ce ticket, il est possible de s'inspirer de la PR qui a été fermée https://github.com/zestedesavoir/zds-site/pull/5373

**Comment by gustavi** [comment]
Vous pouvez vous inspirer de https://github.com/mattrobenolt/django-sudo
