### ISSUE TITLE
Ajout de champ personnalisé dans le profil (ZEP-7)

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#538]
Faire en sorte que l'utilsateur puisse ajouter des champs whatever dans son profil (GitHub, Steam, PSN, whatever.com ...)

**Comment by Eskimon** [comment]
J'en profite pour rajouter une idée...
En parsant le champ, on pourrait avoir une icone en fonction de ce dernier et une icone "défaut" si rien n'est trouvé :)

**Comment by Alex-D** [comment]
Le top serait deux champs :
- URL
- Réseau

Le réseau pourrait être pré-sélectionné automatiquement en matchant l'URL en JS (genre vite fait via le nom de domaine, sans avoir un truc méga précis non plus).

**Comment by Eskimon** [comment]
A quoi sert le truc réseau ? ça veut dire qu'il faut anticiper tout les réseaux possibles ?

**Comment by Alex-D** [comment]
Non, j'aurais dit une liste exhaustive + "autres" non ?
Ca reste un champ de texte avec quelques valeurs prédéfinie communes.

Ou alors, on gère tout à partir de l'URL et du coup vous faites joujou avec côté back pour retourner ce qu'il faut afficher.

**Comment by Eskimon** [comment]
Ce ticket sera pris en charge par la [ZEP-7](https://zestedesavoir.com/forums/sujet/709/zep-07-champs-personnalises-dans-le-profil/)

**Comment by SpaceFox** [comment]
Ce ticket a une ZEP, il ne sert plus ici.
