### ISSUE TITLE
Espaces manquantes dans les titres de page

### ISSUE THREAD

**Issue by Vanadiae** [zestedesavoir/zds-site#5382]
Bug introduit par la PR #5354.

Dans la structure d'un titre : `Nom du contenu &bull; Zeste de Savoir` et où il y a un `&bull;`, l'espace juste avant est retiré devenant : 

![discord_bug_titre](https://user-images.githubusercontent.com/48521955/62305846-01790500-b481-11e9-84cf-daab41b5c7bd.png)

Regarder du côté des templates dans les blocs `title` et `title_base` et rajouter un bloc trail en adaptant pour que le rendu soit le bon.

Penser à faire des tests pour le templatetag `trail`.

**Comment by artragis** [comment]
fixed en v28.2
