### ISSUE TITLE
Créer install_zds.bat pour installer zds en une seule commande

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5388]
Pour`install_zds.bat`, il faut exécuter à l'intérieur : 

 1. Télécharger (via curl) : 
        - getText : https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.20.1-v1.16/gettext0.20.1-iconv1.16-shared-32.exe
        - zlib : https://sourceforge.net/projects/gnuwin32/files/zlib/1.2.3/zlib-1.2.3.exe/download

 2. Installer : 
     - getText [comme indiquer dans l'aide](http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline) avec la commande suivante :
        ```
        gettext0.20.1-iconv1.16-shared-32.exe /silent
        ```
     - powershell si besoin et si `version < 3` (on récupère le numéro de version avec : `powershell -Command $PSVersionTable.PSVersion`).

3. On lance les commandes : 

    ```bat
    Start-Process -FilePath powershell -Verb RunAs -ArgumentList "Set-ExecutionPolicy RemoteSigned"
    pip install virtualenv

    virtualenv zdsenv
    zdsenv/Scripts/activate.ps1
    pip install --upgrade -r requirements-dev.txt

    # installer nvm puis s'attaquer au front-end + zmd (voir install_zds.sh) 
    # ...

    # Puis : 
    # https://docs.zestedesavoir.com/install/install-windows.html#suite-et-fin-de-l-installation
    ```

Doit-on en profiter pour utiliser [appveyor](https://www.appveyor.com/) en complément à travis pour ainsi vérifier l'installation et l'exécution sous Windows ?

**Comment by artragis** [comment]
> Doit-on en profiter pour utiliser appveyor en complément à travis pour ainsi vérifier l'installation et l'exécution sous Windows ?

non.
