### ISSUE TITLE
Transparence sur la validation

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#539]
Pour l'instant l'auteur n'a aucune visibilité sur la progression de la validation de son article/tuto. Il faudra ajouter des process à ce niveau...
J'en profite pour copier un joli paragraphe/idée de Javier : 

> PS : et si vous voulez en profiter pour faire une analogie avec la plantation, les agrûmes etc. Y'a de quoi se lâcher. En rédigeant tu plantes la graine, le validateur c'est le jardinier qui s'occupe de ton cours, en prend soin, etc. quand le tutoriel est à mâturation on le transplante (comment on dit pour les arbres déjà ??) ailleurs en plein milieu d'un parc. Evidemment il faut l'entretenir, l'élaguer, pour qu'il donne de beaux fruits sains que n'importe qui peut cueillir et manger. Il arrive un jour en fin de vie, abîmé par le temps, mais c'est pas grave, on peut faire une bouture et lui donner une seconde vie :) Et magie, ça se représente très bien sur un diagramme cyclique !

**Comment by firm1** [comment]
Pour le moment on peut déjà implémenter simplement l'envoi d'un message automatique a un auteur dont le tutoriel a été réservé par l'auteur.

Il suffit d'utiliser le service sens_mp associé a l'utilisateur bot et dans les paramètres, demande d'envoyer aussi un mail.

**Comment by Alex-D** [comment]
Est-ce qu'il est possible de sauver la progression de la validation de façon à proposer une visualisation graphique de la chose, et un texte qui dit "ça en est là" ?

**Comment by Coy0te** [comment]
Le problème avec cette approche, c'est qu'une validation n'est pas toujours linéaire.

**Comment by Alex-D** [comment]
N'est pas linéaire : est-ce que ça empêche d'avoir un "statut" ? Je ne dis pas de mettre "dans 3 jours t'auras une réponse" mais "la partie I a été lue", "machin a réservé la validation de ce tutoriel", ...

**Comment by firm1** [comment]
@Alex-D ce dont tu parles c'est ce que je décris [ici](http://zestedesavoir.com/forums/sujet/193/transparence-des-process-de-validation/#p1518)

Et donc ce ne sera pas pour une première version. D'ou mon message ci-dessus pour le minimum actuellement faisable.

**Comment by Coy0te** [comment]
C'est un long débat qu'on a déjà tenus maintes fois sur le SdZ. En quelques mots, voilà ce qui en est toujours ressorti : le fait est que personne n'a la même manière de valider, et qu'on souhaite éviter du mieux que possible l'envoi de faux signaux.

Donc pour éviter les prises de têtes et les sujets à la con du genre "mon cours a été lu à + de 80% depuis 3 jours et j'ai toujours pas reçu mon retour de validation", on a toujours opté pour... KISS : 
- si un auteur veut des infos sur l'avancement, il MP le valido et la discussion s'engage (ou pas) ;
- s'il s'en branle, il attend un MP éventuellement envoyé volontairement par le valido, ou simplement le retour de validation.

L'amélioration sur ZdS, c'est que l'auteur saura quand un valido s'attribuera/se désattribuera son tuto.

**Comment by Coy0te** [comment]
Maintenant si on veut en (re)discuter, je pense que c'est plus sage d'attendre la montée en puissance de ZdS côté public, et d'analyser comment se passe la validation au fil de l'eau. 

M'est avis que ça ne sert à rien d'affiner en amont des process sans avoir de nouvelles expériences sur lesquelles se baser.

**Comment by firm1** [comment]
@Coy0te je ne sais pas a qui tu réponds, donc dans le doute, je ré-expose mon raisonnement.

Si on donne le choix aux validateurs de pouvoir marquer chaque extrait comme "ok", est-ce que ça pose un problème ? si oui lequel ?

Je dis bien on donne le choix, car le valido n'est pas obligé de signaler s'il a lu tel ou tel extrait. Mais pour les validos qui valident par petit bout, il pourra facilement savoir ou il en est dans sa validation, et donc l'auteur pourra avoir un detail sur l'avancement. Pour le valido qui préfère valider tout un tuto d'un coup, ça reste possible, c'est juste que le suivi passera de 0% a 100% d'un coup au bout de x mois.

Donc, en résumé, je ne vois pas pourquoi ça ne serait pas envisageable pour zds.

**Comment by geoffreyc** [comment]
C'est un bon argument, mais ya aussi le fait qu'un utilisateur sera
beaucoup plus patient et compréhensif si il est prévenu assez régulièrement
de l'avancé de validation. Si un tuto prend assez longtemps pour être
validé (+ 2 semaines?) l'auteur aura plus tendance a patienter un peu plus
si il a eu quelques maj avant ca lui indiquant ou en etait sont tuto,
plutôt que si il y a eu silence radio pendant 2 semaines. Je pense qu'avoir
un truc du genre:
1. Tuto envoyé en validation ---> 2. Validateur assigné au tuto ---> 3. x/y
parties validées ----> 4. Tuto validé

Apres les messages du genre "mon cours a été lu à + de 80% depuis 3 jours
et j'ai toujours pas reçu mon retour de validation" il suffit de les
interdire sur le forums, sous peine de voir son tuto refuser.

2014-05-21 10:39 GMT+01:00 Coyote notifications@github.com:

**Comment by SpaceFox** [comment]
Pour moi, il est urgent d'attendre et de voir les retours de validations
réelles (ce qui implique qu'on aille chercher les retours des auteurs !)

Les processus de validation et comportement des auteurs comportent des
contraintes et des comportement qui sont complètement contre-intuitifs au
premier abord...

AMHA, le premier truc "additionnel" (i.e. pas strictement indispensable) à
développer sur une validation, c'est un formulaire de retour d'expérience
pour l'auteur : "Aidez-nous à améliorer la validation ! Qu'est-ce qui vous
a plu ? Qu'est-ce que vous voudriez améliorer ? Des suggestions ?"

**Comment by Coy0te** [comment]
> Si on donne le choix aux validateurs de pouvoir marquer chaque extrait comme "ok", est-ce que ça pose un problème ? si oui lequel ?

Aucun problème et c'est tout à fait envisageable, on est d'accord sur ce point. Je disais simplement qu'il ne s'agissait pas d'une discussion "nouvelle", et qu'avec la palanquée de trucs importants qu'il reste à faire, couplée à l'incertitude sur l'efficacité finale de ce système, on ferait probablement mieux d'attendre.

Bref, en deux mots, +1 SpaceFox.

**Comment by cgabard** [comment]
Je vais arriver avec un truc lié de loin a cette issue. SI je me souviens bien, le plus gros prob de l'epoque Sdz n'etait pas tant le manque de transparence que la durée de validation. Certains tutos prenant des semaines voir des mois avant d'etre validés, soit par manque de disponibilité des validateurs, soit par manque de compétences particulière.

Si mon analyse est bonne, ce ticket n'est pas urgent : tant qu'ont aura peu de tutos d'envoyés, ils seront globalement traités rapidement et le coté obscure ne genera pas. Celui-ci gene quand on ne sais rien ET que ça prend du temps.

A long terme une autre possibilité serait d'ouvrir en partie la validation qui permetrait de rendre le truc plus transparent et probablement plus rapide. En gros, pourquoi ne pas considérer la validation comme une PR (puisque techniquement la validation est une demande de merge dans une branche vers une autre) et de reprendre le fonctionnement de GH : 
- Tout le monde peut voir la PR et la commenter
- Seul un responsable du dépot (ici les validateurs) peuvent accepter le merge.

Cela pourrait permettre d'alléger le travail des validateurs puisque d'autres membres pourraient commenter et mettre le doigt sur les problèmes si aucun valido n'a le temps et/ou les compétences. Evidement le valido peu lui aussi commenter et de toute façon c'est lui qui aura le mot final.

Je me doute que ma proposition tranche radicalement avec ce qui se fait actuellement mais cela pourrait être interessant à tester au moins.

**Comment by Alex-D** [comment]
Ca serait un combo validation par validateurs X validation par pairs (SdZ X OCR) si j'ai bien suivi ?

**Comment by SpaceFox** [comment]
C'est une idée intéressante, mais j'ai peur qu'on se retrouve avec le même
problème que la bêta des tutos sur le SdZ : 95% des commentaires sont
complètement inutiles ou toxiques, de "il y a une faute là" dans un tuto
complètement incohérent à "c'est génial" devant un tuto qui est une merde
absolue.

**Comment by SpaceFox** [comment]
> Ca serait un combo validation par validateurs X validation par pairs (SdZ
> X OCR) si j'ai bien suivi ?

Y'a pas de validation par pairs sur OCR, c'est de la correction d'exos.

C'est différent, parce qu'un exo est beaucoup plus court, et qu'il est
beaucoup plus factuellement vrai ou faux.

**Comment by Alex-D** [comment]
Ah pardon, je suis plus rien de OCR j'avais cru comprendre ça ^^" je me disais bien qu'ils ne pouvaient pas avoir d'aussi bonnes idées.

**Comment by SpaceFox** [comment]
Ben même pas : leur idée est très bien pensée et à priori bien réalisée ;
il leur manque juste une combine pour ne pas prendre en compte les gens qui
"corrigent" n'importe comment.

**Comment by cgabard** [comment]
Je remonte cette issue pour reparler de mon idée : 

> C'est une idée intéressante, mais j'ai peur qu'on se retrouve avec le même problème que la bêta des tutos sur le SdZ : 95% des commentaires sont complètement inutiles ou toxiques, de "il y a une faute là" dans un tuto complètement incohérent à "c'est génial" devant un tuto qui est une merde absolue. 

Je pense que dans un premier temps, pour éviter cet effet, on peut très bien limiter cette fonctionnalité de "PR de validation" aux seuls personnes qui ont déjà publié du contenu sur le site. On peut en effet considérer que les auteurs font parties des personnes les plus pertinente pour commenter le travail de d'autres auteurs. En tout cas on évitera les commentaires des personnes tout a fait débutants.

**Comment by Alex-D** [comment]
J'aime bien l'idée !

En gros il n'y aurait que le staff + auteurs qui commenteraient si je suis bien ?

**Comment by cgabard** [comment]
Yep. Pour éviter le prob des gens qui prennent les tutos "en beta/demande de validation" comme argent comptant et/ou commentent inutilement, on rajoute les autres auteurs comme commentateurs. Ainsi on gagne un bon nombre de personnes comme commentateurs possibles, autant sur le fond que la forme. On gagne en ouverture et transparence et on garde les valido qui ont le dernier mot. Et le must c'est qu'on peut présenter ça comme de la validation par ses pairs, comme dans le monde de la recherche académique.

**Comment by Eskimon** [comment]
Ce ticket meriterait une ZEP a part entiere et sera en partie traite par les [ZEP-18](https://zestedesavoir.com/forums/sujet/1793/zep-18-amelioration-de-lergonomie-de-validation/) et [ZEP-20](https://zestedesavoir.com/forums/sujet/2042/zep-20-relecture-des-tutos-par-les-pairs/)

**Comment by GerardPaligot** [comment]
Si des ZEPs sont en cours sur le sujet, est-ce utile de garder ce ticket ?

**Comment by SpaceFox** [comment]
Non.
