### ISSUE TITLE
Special char of username in Admin Zone

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#54]
Actuellement, en s'inscrivant, on peut créer un pseudo qui contient des caractères spéciaux, des accents et tout le tralala. Cependant, il est actuellement impossible de modifier ces utilisateurs via l'interface d'admin.

Le fait est que django par defaut, n'autorise pas les caractères spéciaux dans les username. Du coup, il est impossible d'agir sur un username comme "GéoMl" dans la zone d’administration, pour le passer staff en l’occurrence.

C'est un problème, à résoudre.

**Comment by SpaceFox** [comment]
Django ne fonctionne pas en Unicode partout ?
Ou alors c'est une restriction américaine bizarre qui a été ajoutée
spécialement sur les usernames ?

**Comment by firm1** [comment]
Comme tu peux le [voir ici](https://docs.djangoproject.com/en/1.5/ref/contrib/auth/#django.contrib.auth.models.User.username), c'est une restriction exprès dans le modèle de django. 
Cependant, il accepte tout type de caractères, mais il refuse de manipuler les caractères spéciaux avec ses outils.

**Comment by SpaceFox** [comment]
Ben du coup je pige pas trop : selon ta doc _"__GéoMl"_ devrait être
accepté, puisqu'il ne contient que des caractères alphanumériques.

**Comment by firm1** [comment]
C'est ce que j'ai pensé aussi, jusqu'a me rendre compte que l'outil d'admin de django n'accepte pas le "GéoMl" à cause du "é" !

**Comment by firm1** [comment]
Du coup, je ne sais pas si les caractères accentués sont inclus dans ce qu'ils appelle "alpha numérique"

**Comment by SpaceFox** [comment]
Si c'est pas le cas, y'a juste un énorme bug dans leur doc >_<
J'ai checké vite fait, j'ai pas trouvé de définition claire de ce terme.

**Comment by dreherch** [comment]
Pas de bug dans la doc, pour un américain, alphanumérique c'est les
chiffres et les lettres, donc [A-Z][a-z][0-9]. Les caractères accentués ne
sont pas plus des lettres que les lettres grecques et cyrilliques.

**Comment by SpaceFox** [comment]
Pas d'accord.
Django est un projet d'envergure internationale, donc si la doc ne tient
pas compte des spécificités des langues autres que l'anglais, c'est qu'elle
est débuggée, point barre.
S'ils veulent parler des caractères alphabétiques ASCII, eh bien ils
indiquent "caractères alphabétiques ASCII".

**Comment by Coy0te** [comment]
On peut peut-être prendre le problème dans l'autre sens et n'autoriser que [A-Z][a-z][0-9] dans les pseudos.

**Comment by firm1** [comment]
> On peut peut-être prendre le problème dans l'autre sens et n'autoriser que [A-Z][a-z][0-9] dans les pseudos.

Si quelqu'un m'impose cette limitation sur un site, je gueule tous les jours

**Comment by geoffreyc** [comment]
Ca serait pas aussi simple que ca?
http://stackoverflow.com/questions/1214453/allowing-the-character-in-usernames-in-the-django-admin-interface

2014/1/6 firm1 notifications@github.com

**Comment by firm1** [comment]
> Ca serait pas aussi simple que ca?

A vue de nez, ça pourrait résoudre le problème. Je testerai quand je pourrai

**Comment by SpaceFox** [comment]
Bonne question Geo, il faut voir ce que Python inclut dans sa métaclasse
\w. Par exemple, en Java elle n'inclut que les lettres ASCII : "A word
character: [a-zA-Z_0-9]"

Personnellement j'autoriserais l'équivalent de \p{IsLatin} + les chiffres +
_ et - en Java. Je ne sais pas si Python dispose de cette classe - en mode
Unicode, cf
http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html
Voire directement \p{alnum} si elle existe et gère l'Unicode :
http://www.unicode.org/reports/tr18/#alnum

2014/1/6 geoffreyc notifications@github.com

**Comment by SpaceFox** [comment]
La combo Unicode + Regex, c'est quand même sale...

**Comment by firm1** [comment]
> La combo Unicode + Regex, c'est quand même sale...

+1 

Pour le reste, je regarderai quand j'aurai un pc de dev sous la main. C'est à dire, pas avant ce soir minuit.

**Comment by firm1** [comment]
J'ai testé ça la nuit dernière :

> Ca serait pas aussi simple que ca?
> http://stackoverflow.com/questions/1214453/allowing-the-character-in-usernames-in-the-django-admin-interface

Aucun résultat probant.

**Comment by SpaceFox** [comment]
J'ai vu une combine que je vais tester.

**Comment by SpaceFox** [comment]
OK, c'est complètement dingue...
J'arrive à passer à Django la regex que je veux. Je peux même autoriser tous les caractères si ça m'amuse... **tant qu'il n'y a aucun caractère non-ascii dans le tas**.
Même en forçant la regex en mode Unicode (avec re.UNICODE)

J'ai l'impression qu'il y a un _autre_ contrôle qui vérifie s'il y a des caractères non-ASCII dans le lot, c'est complètement bizarre (par exemple, `r'^.+$'` prends n'importe quoi, les espaces, etc... mais pas "é".
Le plus chiant c'est que :
- La regex par défaut est déjà sensée être en mode unicode
- Aucune des solutions "connues pour marcher" sur le net ne fonctionne.

**Comment by SpaceFox** [comment]
PS : Je confirme qu'il y a un contrôle supplémentaire : les espaces ne passent pas alors que selon la regex, ils devraient...

**Comment by SpaceFox** [comment]
Ha putain j'ai compris, c'est un coup en deux bandes.

Toutes les docs que j'ai trouvé concernaient l'UI de l'admin et avaient déjà un certain âge.
Sauf que... si l'UI accepte les caractères unicodes, maintenant il y a une validation de données **au niveau du champ dans la base**.
Qui est une regex qui _n'est pas_ compilée en mode Unicode !

``` python
class AbstractUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(_('username'), max_length=30, unique=True,
        help_text=_('Required. 30 characters or fewer. Letters, numbers and '
                    '@/./+/-/_ characters'),
        validators=[
            validators.RegexValidator(re.compile('^[\w.@+-]+$'), _('Enter a valid username.'), 'invalid')
        ])
```

La solution est donc très en fait assez simple (en théorie du moins...) :
1. Trouver la regex qui correspondrait à `[\p{IsLatin}0-9_-]+` en Python, sachant que Python ne gère pas cette classe Unicode. J'ai peur que `\w` avec Unicode soit trop large, et inclue en particulier les caractères cyrilliques.
2. MAJ ce putain de validator (comment ? quels impacts ?)
3. MAJ l'UI de l'admin (le lien de @geoffreyc ci-dessus fait très bien l'affaire)

Si on arrive pas à avoir `\p{IsLatin}`, je propose qu'on se contente d'ajouter tous les caractères accentués du français (puisque ce sera la langue du site).
Ce qui nous oblige quand même à MAJ la regex du validator.

Vu l'heure, ça attendra demain pour ma part.

Pour info ce validator est une nouveauté de la 1.5, ce qui explique qu'aucune doc sur le net "pour activer les caractères unicode dans les logins" n'en parle, puisqu'elles sont toutes assez vieilles.

Je me demande si une PR pour mettre en cohérence les comportements admin et bdd serait acceptée sur Django :)

**Comment by firm1** [comment]
Ah ouais j'en était arrivé presque aux mêmes conclusions que toi (a quelques details près). 

Globalement j'avais réussi a surcharger l'UI mais visiblement il fallait aussi surcharger le validator qui n'est rien d'autre que la fonction clean associés a ce champ. Mes dernieres tentatives (il y'a 2 mois) ont échoué, mais je pense qu'en lisant le code de la Form AbstractUser de plus près ça devrait le faire.

Faudrait faire des tests.

Mais je confirme cette issue c'est du tirage de cheveux.

**Comment by SpaceFox** [comment]
Ouais, en fait notre procédure d'inscription [fonctionne par mégarde](https://docs.djangoproject.com/en/1.5/ref/validators/#how-validators-are-run) : 

> Note that validators will not be run automatically when you save a model, but if you are using a ModelForm, it will run your validators on any fields that are included in your form.

Donc on a dans User des données qui ne devraient pas y être :(

Ce que je ne pige pas dans cette histoire c'est ça : 

``` python
class MyUserChangeForm(UserChangeForm):
    def clean_username(self):
#        return u'LOL' # fonctionne nickel, ça me force "LOL" comme username
        return u'é' # Plante, exactement comme s'il y avait une re-validation derrière

class MyUserAdmin(UserAdmin):
    add_form = MyUserCreationForm

admin.site.unregister(User)
admin.site.register(User, MyUserAdmin)
```

Si quelqu'un a une idée...

**Comment by cgabard** [comment]
Oui, le resultat doit être casté en string quelque part. Demonstration : 

```
cgabard@cgabard-MS-7821:~$ python2
Python 2.7.5+ (default, Feb 27 2014, 19:39:55) 
[GCC 4.8.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> str(u"LOL")
'LOL'
>>> str(u"é")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 0: ordinal not in range(128)
>>> 
```

**Comment by Coy0te** [comment]
@cgabard si j'ai bien lu, le problème que tu observes vient de `str()` : 
=> http://stackoverflow.com/a/9942885/401881

**Comment by cgabard** [comment]
Je n'ai pas de probs moi, j'illustrait juste à @SpaceFox pourquoi `u"LOL"` pouvait passer et pas `u"é"` justement a cause de ça et que ce n'est pas forcément a cause d'un filtre mais d'une conversion vers le type str quelque part

**Comment by cgabard** [comment]
Mais effectivement du coup un `.encode('utf-8')` peut eventuellement régler le prob

**Comment by Alex-D** [comment]
A priori tout ça a été réglé pendant la première beta non ?

**Comment by SpaceFox** [comment]
Absolument pas : c'est un problème django / python qui à ma connaissance
n'a aucune solution avec python 2.

**Comment by Alex-D** [comment]
Ok, j'avais cru car j'ai vu qu'@dri1 avait un @ dans son pseudo. So... it's open !

**Comment by SpaceFox** [comment]
Ce cas est-il toujours problématique ?

**Comment by zopieux** [comment]
> Absolument pas : c'est un problème django / python qui à ma connaissance
> n'a aucune solution avec python 2.

Je ne suis pas sûr de comprendre de quoi tu parles mais Unicode, bien que pénible quand on ne connait pas, fonctionne très bien en « Django / Python » même dans sa version 2.

Quelqu'un pourrait-il préciser le problème ? Si je comprends bien vous souhaitez passer outre la validation des caractères spéciaux et tout autoriser dans `username` ?

**Comment by Eskimon** [comment]
Non, ca parle plutot de la zone d'administration propre a Django (via /admin)

**Comment by Eskimon** [comment]
Comment gérer ce ticket ? Si c'est un problème python on ne peut rien y faire non (a part migrer sur python 3...) ? Est-ce réellement bloquant et quelles sont les opérations qui nécessite de passer par cette interface et leurs fréquences ? (passer un membre en staff, ajouter une catégorie, autre ?)

**Comment by firm1** [comment]
La seule raison qui justifie cette issue c'est qu'on ne peut pas rattacher
un utilisateur qui a un pseudo aux caractères bizarre a un groupe (staff,
dev, etc.) depuis l'admin de django.

Pour résoudre cette issue il faut donner la possibilité de rajouter un
utilisateur a un groupe depuis son profil. Ce qui revient techniquement à :
- rajouter un bouton "ajouter dans un groupe" et "enlever d'un groupe" dans
  le profil des membres et ce bouton ne doit être disponible que pour des
  super utilisateurs (qui ont accès a l'interface d'admin).

**Comment by Eskimon** [comment]
Allez je prends et je regarde si j'arrive a implementer l'idée de @firm1

**Comment by SpaceFox** [comment]
C'est OK ici ou on a encore des tests à faire ?

**Comment by firm1** [comment]
Fx'd
