### ISSUE TITLE
Transparence du logo PNG d'un tutoriel

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#540]
Il semblerait que lorsqu'on envoie une image PNG comportant de la transparence en tant que logo d'un tuto, la transparence de l'image est perdue et on se retrouve avec un fond noir à la place.

D'après mascotte, ça serait le redimensionnement de l'image d'origine qui dégage son canal alpha.

---

(Coyote) http://zestedesavoir.com/forums/sujet/173/bug-transparence-du-logo-png-dun-tutoriel?page=1

**Comment by firm1** [comment]
Pour information, pour corriger cette issue, il me semble qu'il suffit d'enlever la partie conversion RGB dans [cette partie du code](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/gallery/models.py#L132).

Vous pouvez regarder [cette doc](http://jlbicquelet.free.fr/scripts/python/pil/pil.php#transformation2) (en français) courte et rapide pour plus de détails sur l'utilisation de PIL.

**Comment by Eskimon** [comment]
En fait le bug est pire que prévu... dès qu'il y a de la transparence dans une image ca part en sucette complet...

```
Environment:


Request Method: POST
Request URL: http://zdsappserver/galerie/image/ajouter/34/

Django Version: 1.6.5
Python Version: 2.7.3
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps',
 'django.contrib.humanize',
 'south',
 'crispy_forms',
 'crispy_forms_foundation',
 'email_obfuscator',
 'pipeline',
 'haystack',
 'munin',
 'zds.utils',
 'zds.pages',
 'zds.gallery',
 'zds.mp',
 'zds.newsletter',
 'zds.article',
 'zds.forum',
 'zds.tutorial',
 'zds.member',
 'django.contrib.admin')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'zds.utils.ThreadLocals',
 'zds.middlewares.SetLastVisitMiddleware.SetLastVisitMiddleware')


Traceback:
File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/zdsenv/ZesteDeSavoir/zds/member/decorator.py" in _can_write_and_read_now
  39.         return func(request, *args, **kwargs)
File "/opt/zdsenv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/opt/zdsenv/ZesteDeSavoir/zds/gallery/views.py" in new_image
  245.             img.save()
File "/opt/zdsenv/ZesteDeSavoir/zds/gallery/models.py" in save
  135.                 image = image.convert('RGB')
File "/opt/zdsenv/local/lib/python2.7/site-packages/PIL/Image.py" in convert
  810.             del(new.info['transparency'])

Exception Type: UnboundLocalError at /galerie/image/ajouter/34/
Exception Value: local variable 'new' referenced before assignment
```

**Comment by firm1** [comment]
> En fait le bug est pire que prévu... dès qu'il y a de la transparence dans une image ca part en sucette complet...

Tu teste avec quelle image ? Parce que moi, j'essaye avec [celle là](http://upload.wikimedia.org/wikipedia/fr/9/9e/Google_Chrome_logo.png) et ça marche. Certes ça marche mal,  mais ça ne part pas en cacahuètes.

Ceci dit, on dirait que c'est un problème sur le serveur car sur windows la même image est nickel.

**Comment by Eskimon** [comment]
Tiens, avec ca:
https://dl.dropboxusercontent.com/u/18967337/moose_lg.png

SI j'essaie de l'ajouter dans une de mes galerie ca crash...
C'est ptet pas tout a fait le cas de base du ticket mais ca mérite d’être relevé...

**Comment by firm1** [comment]
Je pense qu'il s'agit d'un problème d'installation serveur (la prod est en
64 bits), car ton image passe en local.

**Comment by Eskimon** [comment]
> Je pense qu'il s'agit d'un problème d'installation serveur (la prod est en
> 64 bits), car ton image passe en local.

Chez moi (systeme 64 bits) ca crash aussi...

**Comment by firm1** [comment]
Tu es sous quel OS ?

**Comment by Eskimon** [comment]
Ubuntu 12.04 64 bits

**Comment by firm1** [comment]
Moi je suis sous windows là.

Mais pour linux il faut trouver la bonne combinaison de libs il me semble et faire les bons liens. La doc des prerequis à la lib est [ici](https://github.com/python-imaging/Pillow/blob/master/docs/installation.rst)

Je ferais des essais sur le serveur jusqu'a trouver la bonne combi

**Comment by Eskimon** [comment]
En fait après test c'est juste qu'il faut:
- Soit virer les deux lignes que tu as mis en évidence (perso je vois pas trop à quoi elles servent ici)
- Soit ajouter des cas (au moins "RGBA" et "P" pour les tests que j'ai pu faire)

**Comment by firm1** [comment]
> Soit ajouter des cas (au moins "RGBA" et "P" pour les tests que j'ai pu faire)

Cette solution est préferable. Mais quand tu rajoute ça, la miniature de ton image n'est pas chiadée comme sur la prod ?

**Comment by Eskimon** [comment]
Bah ca passe en import image pour la galerie indépendamment d'un tuto (j'ai pas testé dans ce cas la...). Je me suis contenté "betement" de triturer les lignes que tu avais mis en évidence.

**Comment by Eskimon** [comment]
Bon j'ai testé en créant un tuto bidon, ca passe en rajoutant 'RGBA' (pour les png "classique") et 'P' (pour les png alakon 8 bits comme mon caribou original posté plus tot)...
Si ca te convient je fais une PR avec ca...

**Comment by firm1** [comment]
Ok, tu regarderas à l'occasion (dans le repertoire média) si la thumb a été
chiadée

**Comment by Eskimon** [comment]
Ouai j'ai des thumb avec la bonne transparence étou

**Comment by firm1** [comment]
Joli ... go PR

**Comment by Eskimon** [comment]
Ok, tres vite !!

**Comment by firm1** [comment]
Beau travail, ça rend super bien désormais.

Merci, je ferme;
