### ISSUE TITLE
Les fixtures ajoutent un mail aux utilisateurs, fausse bonne idée

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5401]
Dans les fixtures, il faudrait laisser le champ email vide, au lieu de remplir le champ : 

![image](https://user-images.githubusercontent.com/18501150/62832128-3b3ccf00-bc2a-11e9-95a0-92df9c12299b.png)

Correction : ne pas mettre d'email.

**Comment by artragis** [comment]
Non il faut pas un champ vide (pour tester les notifs par mail) et y'a aucun besoin de changer.
