### ISSUE TITLE
Inscription, sécurité mdp

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#541]
Manque de sécu sur le mot de passe : on peut mettre son login, pas de limite min de taille apparemment, et on n'est pas obligé de mixer plusieurs types parmi minuscules, majuscules, chiffres et caractères spéciaux

**Comment by geoffreyc** [comment]
J'ai horreur des sites qui me forcent des restrictions sur le mot de passe
que je veux mettre.

2014-05-16 15:35 GMT+01:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
Je ne fais que rapporter les propos de mascotte sur ce point... Mais c'est vrai que pas bridé au moins la taille et la copie du pseudo lui-même c'est un peu juste non ?

**Comment by geoffreyc** [comment]
Moi je suis partisans de laisser l'utilisateur mettre ce qu'il veut. On
peut effectivement limiter la "taille" du mdp et vérifier si mdp != pseudo,
apres le reste je pense surtout que c'est pas notre "business"; si le
membre veut mettre "password" comme mot de passe, c'est son problème. Ya
pas vraiment de données importantes a securiser deriere ce mot de passe,
donc forcer des P@sS\/\/0rDs du gerne j'aime pas l’idée.

2014-05-16 15:44 GMT+01:00 Eskimon notifications@github.com:

**Comment by firm1** [comment]
Tu rigoles mais en ce moment mon mot de passe au boulot est : p@Ss2014

**Comment by Coy0te** [comment]
Au boulot, chez nous sur les réseaux internes la quasi totalité des mots de passe c'est root/root, admin/p@ssw0rd et compagnie...

**Comment by Eskimon** [comment]
Voici la branche qui va bien https://github.com/Taluu/ZesteDeSavoir/tree/fix_541

J'ai presqur fini (en bridant simplement la longeur du mot de passe a 6 car. et que le mot de passe soit différent du pseudo).
Il reste un truc que je vois pas comment faire...
Lorsque l'utilisateur veut réinitialiser son mot de passe, il est redirigé vers une page contenant les deux champs. Ca ca va. Par contre dans le formulaire on a pas l'utilisateur et je vois pas comment aller le chercher (pour véirfier mdp != pseudo)...
Si quelqu'un sait comment faire, qu'il le fasse et la pull request sera prête...

**Comment by GerardPaligot** [comment]
@Eskimon: Ton lien est mort (404). La branche a été mergée et l'issue résolue ?

**Comment by Eskimon** [comment]
Erf faudra voir avec @firm1 qui a fait un gros refactoring dans l'apres midi il me semble :s

**Comment by Alex-D** [comment]
Je pense qu'il faudra que tu repousses ta branche après le feu vert de @firm1 (il y a un soucis sur l'historique du projet et des bugs apparus suite à l'allègement du dépôt).

**Comment by Eskimon** [comment]
Erf ca ca tombe mal car j'ai viré pour resynchro endébut de soirée comme demandé par firm1... BOn ca va qu'il y avait pas trop de changement...

**Comment by firm1** [comment]
J'en suis tristement désolé, j'ai du retravailler sur le nettoyage du dépot. C'est vraiment dommage que ta branche soit perdue.

Pourrais-tu nous refaire une correction ?

**Comment by Eskimon** [comment]
Ouai c'est pas un probleme c'etait pas trop dur non plus donc ca ira ^^ (par contre il restera toujours le point "Comment recuperer l'utilisateur sur la page de reinit. du mot de passe)

**Comment by Eskimon** [comment]
Bon voila, j'ai repoussé [une branche](https://github.com/Taluu/ZesteDeSavoir/tree/fix_541) avec le début du fix...
Il reste une seule chose à faire, faire en sorte que le mdp soit différent du pseudo lors de l'action "mot de passe oublié". C'est le dernier test, écris en commentaire à la fin du code (le hasard fait bien les choses c'est à la fin du fichier uniquement modifié dans les commits). Le code marchera quand il y aura une variable "username" de peupler avec le pseudo.

J'ai fait en sorte que la taille minimum du mdp soit reglable via une simple constante au début du fichier (et c'est cette constante qui s'affiche dans les chaines de caractères d'avertissements).

Bref, plus qu'une bricole à faire et le code sera prêt pour une PR.

**Comment by firm1** [comment]
Bon bah j'ai complété et mergé tes commits. 

N'hésite pas a aller voir comment j'ai fait, c'est typiquement le genre de chose qu'il faudrait savoir faire pour d'autres issues.

**Comment by firm1** [comment]
PS : bon boulot

**Comment by Eskimon** [comment]
> PS : bon boulot

Merci :)

> N'hésite pas a aller voir comment j'ai fait, c'est typiquement le genre de chose qu'il faudrait savoir faire pour d'autres issues.

J'y compte bien !!

**Comment by Eskimon** [comment]
Je réouvre suite à une découverte...
Si l'utilisateur ne fournit pas de mot de passe (champs vides mais autres champs correctes) on a une erreur 500
Idem si l'utilisateur ne fournit pas d'adresse email (seul le champ email est laissé vide)

Par contre pour le champ username pas de souci...

Conclusion, faut des tests :D
