### ISSUE TITLE
Mettre à jour le script d'installation pour Debian 10

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#5418]
Voici ce que j'ai relevé :

- le paquet `realpath` n'existe plus, utiliser `coreutils`

Je pousserai une PR bientôt, après avoir tester l'installation complète depuis une machine totalement vierge.

**Comment by A-312** [comment]
@gustavi La solution la plus évidente serait d'installer realpath pour debian 10 [via un fichier debian10.txt](https://github.com/zestedesavoir/zds-site/tree/dev/scripts/dependencies) à moins de faire une function sh qui va utiliser realpath ou une alternative sous debian 10 mais changer complètement de commande me semble risqué.

**Comment by gustavi** [comment]
On parle du paquet qui fourni la commande, pas la commande en elle-même.
