### ISSUE TITLE
L'affichage de toutes les publications d'un membre n'est pas correct

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#5422]
Lorsque je vais sur la beta sur le profile de Abdelazer : https://beta.zestedesavoir.com/membres/voir/Abdelazer/

On voit dans les dernières publications qu'il y'a 4 publications. Si je clique sur "Voir tout", j'arrive [ici](https://beta.zestedesavoir.com/contenus/voir/Abdelazer/?filter=public), ça me montre les billets et les articles mais ça ne me montre pas les turoriels.

Ce lien devrait pourtant montrer uniquement les articles et tutoriels, pas les billets.

**Comment by artragis** [comment]
Le bug semble différent que ce que tu penses: il semblerait qu'un des tutos d'Abdelazer ait un état "étrange" (`tutoriels/672/reprenez-le-controle-de-vos-feuilles-de-style-avec-sass/`) en effet il est bien publié et a donc un PublishedContent enregistré en bdd MAIS il semblerait qu'il n'a pas de sha_public enregistré au niveau du PublishableContent. Or la requête pour compter les tutos utilise la première table, alors que celle pour produire la liste utilise la seconde.

Je ne retrouve ce bug sur aucun autre profile. Je vais donc regarder sur la bdd de la béta pour voir ce qui a pu causer le soucis, donc je me réserve le bug et je regarde ce soir.

**Comment by artragis** [comment]
C'est un bug déjà présent à l'heure actuel et voici à quoi il est dû : 

Abdelazer a publié avec matouche un tutoriel puis s'est retiré de la rédaction. Comme les auteurs sont aussi versionné il apparaît comme auteur du tuto quand on fait la recherche en partant de PublishedContent, mais pas quand on fait à partire de PublishableContent.

**Comment by Situphen** [comment]
Il va donc falloir choisir entre utiliser `PublishedContent` ou `PublishableContent` pour afficher la liste des contenus ainsi que le nombre de contenus. Là comme ça, je suis plutôt partant pour `PublishableContent` car ça affiche les contenus dont le membre est auteur en ce moment.

Si on veut vraiment être exact, il faudrait différencier dans la liste des contenus donc le membre est auteur depuis la création, ceux où il était auteur à la création mais est parti et ceux dont il n'était pas auteur à la création mais dont il a rejoint les auteurs.

@artragis Tu en penses quoi ?

**Comment by artragis** [comment]
Je pense que comme du point de vue du public les personnes sont auteurs il faut se baser sur le PublishedContent (ou au moins filtrer sur public_version__authors plutôt que sur authors) quand on cherche à afficher les contenus publics. 

Cependant, si tu n'as pas le temps c'est pas grave car c'est un bug qui existait avant la 28.2

**Comment by Karnaj** [comment]
Bonjour,

J'avais parlé d'un problème similaire [sur le forum](https://zestedesavoir.com/forums/sujet/7970/incoherence-tutoriels-publies-dun-membre/).

**Comment by firm1** [comment]
Corrigé par la PR ci-dessus.
