### ISSUE TITLE
[28.2] : problème de vocabulaire "tutoriaux"

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#5423]
Sur la page de profile, on a un problème de vocabulaire. On utilise le terme "tutoriaux" au lieu de "tutoriel".

Cf. https://beta.zestedesavoir.com/membres/voir/Arius/

Il faut harmoniser ce pluriel partout.

**Comment by StaloneLab** [comment]
C'est litigieux. Le mot anglais d'origine est *tutorial*, dont le pluriel francisé est *tutoriaux* ; le terme ensuite normalisé par l'Académie Française est *tutoriel*, dont le pluriel est *tutoriels*.

La seconde variante est utilisée le plus souvent, et gagne donc l'usage en plus de la règle, elle me semble alors à privilégier. Dans tout les cas, utiliser *un tutoriel*, *des tutoriaux* est une erreur, il faut choisir entre *el* -> *els* ou *al* -> *aux*.

D'aucuns dirons que le vrai terme est *didacticiel*, et je ne pourrais pas leur donner tort. Notons que le pluriel, régulier, de ce mot suit aussi celui de *tutoriels*, qui est donc une raison de plus pour le privilégier.

**Comment by A-312** [comment]
+1 tutoriels

**Comment by artragis** [comment]
Sur discord, ça a été décidé de mettre tutoriels.
