### ISSUE TITLE
[28.2] : Uncaught TypeError: Cannot read property 'scrollHeight' of undefined sur userprofile-bio.js

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#5425]
En allant sur page d'accueil de la beta : https://beta.zestedesavoir.com/ je constate dans la console JS, une erreur qui dit : "Uncaught TypeError: Cannot read property 'scrollHeight' of undefined
    at userprofile-bio.js:22"

Le seul endroit ou on a pas cette erreur dans la console, est sur une page de profile. J'en déduis donc que c'est un fichier js qui ne doit pas gérer le cas ou une classe/balise est absente.

**Comment by A-312** [comment]
https://github.com/zestedesavoir/zds-site/blame/dev/assets/js/userprofile-bio.js#L12

Il faut remplacer par : `if (!$bioContainer[0]) return;`
