### ISSUE TITLE
Le bloc neutre  :D

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#5427]
Bonjour à tous !

```markdown
[[neutre|Bloc neutre]]
| Je me demandais s'il est possible d'ajouter le bloc neutre dans la liste des blocs spéciaux pour rédiger sur ZdS ?
```
Pour l'instant, il n'est pas visible dans la liste proposée dans l'éditeur :

![ ](/media/galleries/8163/b2ccf7ed-7828-4b43-aa31-94b05903e0ab.png)

Ce serait cool. :ange:

Sujet : https://zestedesavoir.com/forums/sujet/12965/le-bloc-neutre-d/
*Envoyé depuis Zeste de Savoir*

**Comment by Arnaud-D** [comment]
Doublon de #4938.
