### ISSUE TITLE
Remplacer django-rest-swagger par drf-yasg

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5436]
Remplacer django-rest-swagger par drf-yasg car le premier est déprécié

**Comment by artragis** [comment]
je n'ai aps trouvé la notice qui dit que django-rest-swagger est déprécié

**Comment by Situphen** [comment]
C'est dans [le README.md](https://github.com/marcgibbons/django-rest-swagger/blob/master/README.md)

**Comment by artragis** [comment]
Ok j'ai commencé à le faire
