### ISSUE TITLE
Les descriptions vides sont affichées pour les contenus

### ISSUE THREAD

**Issue by nils-van-zuijlen** [zestedesavoir/zds-site#5445]
Les contenus ayant une description vide se voient afficher `None` sur la page d’accueil et dans la bibliothèque.

C'est sans doute une conversion depuis la base de données qui a changé.

Sujet : https://zestedesavoir.com/forums/sujet/13013/les-descriptions-vides-sont-affichees-pour-les-contenus/
*Envoyé depuis Zeste de Savoir*

**Comment by Situphen** [comment]
Très probablement une régression de #5364 qui a modifié la fonction `description(self)` de la classe `PublishedContent` dans le fichier `zds/tutorialv2/models/database.py`, fonction qui est utilisée pour afficher le sous-titre dans les vignettes des contenus.

**Comment by A-312** [comment]
~~Vous pouvez vérifier si le logo s'affiche correctement sur les tweets aussi ? J'ai testé sur mon portable appartement, ils n'ont pas d'icône.~~ EDIT: OK

**Comment by A-312** [comment]
La PR #5364 fonctionne pour les tutoriels mais pas pour les contenus. :(

**Comment by A-312** [comment]
La PR #5364 fonctionne pour les sujets sur le forum mais pas pour les contenus. :(
