### ISSUE TITLE
Ajouter des tests pour les twittercards

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5446]
Ajouter des tests unitaires qui vérifient que les metas existent et soit correctement définit pour les tweettercard.

 - Un seul élément de chaque type ;
 - Présence de l'image pour un contenu qui à une image ou pas, + lien ABSOLU (2 tests) ;
 - Présence du titre + vérifier le nombre d'espace -> voir PR récente qui corrige le bug des Discord card (2 tests) ;
 - Présence de la description + vérifier nombre d'espace -> idem ci dessus (2 tests)
 - Vérifier pour un contenu et un sujet sur le forum.

**Comment by A-312** [comment]
+ vérifier sur tuto normal et tuto d'un bigtuto
+ couvrir #5364 quand la description est vide pour un sujet ou un contenu.

**Comment by artragis** [comment]
à fusionner avec #5447
