### ISSUE TITLE
[Twittercard] Mauvais logo pour un tuto enfant d'un big-tuto

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5447]
Si je mets : https://zestedesavoir.com/tutoriels/2789/les-reseaux-de-zero/le-concept-et-les-bases/les-reseaux-presentation-generale/ sur twitter, le tuto à le logo par défaut de zeste de savoir (--> le favicon) alors qu'**il devrait avoir le logo du tutoriel** dans la twittercard.

**Comment by artragis** [comment]
Ajouter des tests unitaires qui vérifient que les metas existent et soit correctement définit pour les tweettercard.

 - Un seul élément de chaque type ;
 - Présence de l'image pour un contenu qui à une image ou pas, + lien ABSOLU (2 tests) ;
 - Présence du titre + vérifier le nombre d'espace -> voir PR récente qui corrige le bug des Discord card (2 tests) ;
 - Présence de la description + vérifier nombre d'espace -> idem ci dessus (2 tests)
 - Vérifier pour un contenu et un sujet sur le forum.

**Comment by A-312** [comment]
Fait partie des tutos
