### ISSUE TITLE
L'export à la demande ne fonctionne pas

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5448]
Plus précisement, l'export Markdown ne fonctionne pas quand on clique sur le bouton "Exporter le contenu" alors qu'il fonctionne lors de la publication.

**Comment by artragis** [comment]
ou plus précisément encore il met les titres et pas les textes.

**Comment by Situphen** [comment]
J'ai regardé le code pour voir d’où ça peut venir et il est possible que ce soit un effet de bord de #5381 qui ajoute `replace('\\', '/')` dans les fonctions `get-introduction`, `get-conclusion` et `get-text` lors de l'appel a `get_blob`, lequel renvoie `None` en cas de soucis. Ça peut aussi être un problème de chemin relatif ou absolu car avec le bouton `Exporter le contenu` on lance l'export du markdown depuis le fichier `zds/tutorialv2/api/views.py`. J'essaierai de continuer mes investigations dans la semaine.
