### ISSUE TITLE
Transformer les balises SPOILER en pure HTML avec SUMMARY et DETAILS

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5454]
https://www.alsacreations.com/article/lire/1335-html5-details-summary.html

Il faudrait avoir : 

``` HTML
<details><summary>TITRE</summary>
<div>
<p>CONTENU</p>
</div>
</details>
```
<details><summary>TITRE</summary>
<div>
<p>
CONTENU
</p>
</div>
</details>

RAISON : On aurait plus besoin de l'event "onclick"

## Attention lors du Q/A :

 - Vérifier la hiérarchie des `<p>` ;
 - Voir le comportement de #5416, si on corrige le soucis ou non ;
 - Ne pas oublier [le support pour l'ancien format](https://github.com/zestedesavoir/zds-site/issues/5026#issuecomment-445531971)

## 2ème étape : 

 - Modifier ZMD pour qu'il utilise directement  SUMMARY et DETAILS au lieu du format en div (= 2ème break change).

**Comment by artragis** [comment]
il suffit d'activer un flag dans zmd, ensuite si on gère bien les choses c'est qu'une question de classe CSS.

Par contre il faut absolument mieux styliser la chose car la flèche elle est moche.

**Comment by AmauryCarrade** [comment]
Attention que `<détails>` n'est pas supporté par Edge (et IE 11 mais je ne crois pas qu'on le supporte de toute façon). Il faudra peut-être un _fallback_.

**Comment by A-312** [comment]
Ah EDGE... :-/

**Comment by artragis** [comment]
edge est aujourd'hui sur chromium donc je dirais que c'est supporté. Tu as une source @AmauryCarrade ?

**Comment by A-312** [comment]
Ne fonctionne pas sous Edge 44

**Comment by AmauryCarrade** [comment]
Ma source c'est CanIUse. Mais effectivement quand Edge sera sous Blink cette remarque deviendra caduque.

**Comment by artragis** [comment]
edge est aujourd'hui sur chromium donc je dirais que c'est supporté. Tu as une source @AmauryCarrade ?

**Comment by Situphen** [comment]
Mise en place lors du passage à zmarkdown 11 avec #6276
