### ISSUE TITLE
Le bouton "Ajouter une section" renvoie vers une 404

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5455]
Explication : 

Le bouton est ici : https://zestedesavoir.com/contenus/2789/les-reseaux-de-zero/le-concept-et-les-bases/
404 : https://zestedesavoir.com/contenus/nouvelle-section/2789/le-concept-et-les-bases/les-reseaux-presentation-generale/

![image](https://user-images.githubusercontent.com/18501150/65884533-4d6cfb00-e399-11e9-92a8-f8f73d1f78fc.png)

**Comment by A-312** [comment]
J'ai mis en v29, vu que c'est l'interface des tutos et qu'on doit la revoir :)

**Comment by firm1** [comment]
Coucou @A-312, je n'arrive malheuresement pas a reproduire ce bug en local. J'ai téléchargé l'archive du tutoriel et importé en local.

Quand je clique sur le bouton "Ajouter un chapitre" je n'ai pas de 404.

Tu arrives encore a reproduire ?

**Comment by A-312** [comment]
oui quand je clique sur créer une section : https://beta.zestedesavoir.com/contenus/2789/les-reseaux-de-zero/le-concept-et-les-bases/

**Comment by A-312** [comment]
Il faudra faire attention, je crois que j'ai implémenté le bug en corrigeant le bug d'un bouton présent sur une autre pagr

**Comment by firm1** [comment]
Ah, je me suis laissé trompé par la capture d'écran qui est dans le ticket. La souris pointe sur "Ajouter un chapitre" alors que le bug c'est sur "Ajouter une section".

ça dois être facile a corriger ça.
