### ISSUE TITLE
Illogisme création/déplacement chapitre au niveau d'une partie

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5456]
Bonjour,

On peut déplacer un chapitre au même niveau qu'une partie mais on ne peut pas la créer directement à cet endroit (cad créer un chapitre frère à une partie).

![image](https://user-images.githubusercontent.com/18501150/65891353-a5f5c580-e3a4-11e9-9346-1f16b347680a.png)

**Comment by artragis** [comment]
un "chapitre" frère d'une partie c'est une partie. Rien d'illogique.

**Comment by A-312** [comment]
Ah ça le converti en partie ? :o  Je n'avais pas compris comme ça, donc c'est tout à fait logique !
