### ISSUE TITLE
"version: ^x.x.x" On laisse "^" pour les dépendances ?

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5458]
Certaines dépendances ont `^`, on le garde ou on l'enlève pour avoir des versions fixes ?

![image](https://user-images.githubusercontent.com/18501150/65896738-19e89b80-e3ae-11e9-9821-d4cc8a5fa473.png)

**Comment by arobase-che** [comment]
Le concept, c'est que les versions mineures ne devraient pas poser problème. Seules les versions majeures devraient poser problèmes.

Au contraire, je suis pour ajouter "^", là où c'est possible.

**Comment by A-312** [comment]
@arobase-che  Donc on doit les rajouter ?

**Comment by artragis** [comment]
"ne devraient pas"... sur zds-site on fait du pin strict.
