### ISSUE TITLE
3 caractères qui n'ont rien à faire dans le front

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5459]
https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/view/container.html#L272

"-->" ne devrait pas être présent, il faut donc les enlever.

![image](https://user-images.githubusercontent.com/18501150/65921210-e0ca1e80-e3e1-11e9-9c86-dee92ffcb44d.png)

**Comment by philippemilink** [comment]
Je prends !

**Comment by firm1** [comment]
Rapport de QA :

- Avant : 

![Capture d’écran de 2019-10-15 17-17-15](https://user-images.githubusercontent.com/6066015/66845053-afb82500-ef6f-11e9-8a48-f846b97e7d24.png)

- Après : 

![Capture d’écran de 2019-10-15 17-17-03](https://user-images.githubusercontent.com/6066015/66845105-c199c800-ef6f-11e9-9cf3-ecd300b68b3e.png)

**QA OK**
