### ISSUE TITLE
Question sur `content_online.html`

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5461]
Quand est-ce que ce passage s'active avec `{% if not content.has_sub_containers %} ` ? J'ai besoin de vérifier le CSS.

https://github.com/zestedesavoir/zds-site/blob/ded5ff94daf7eb3de2528b23a2b7715cb437849a/templates/tutorialv2/view/content_online.html#L182-L192

Je n'ai pas réussi à trouver la situation qui affiche ces lignes sur mon espace de dev.

**Comment by artragis** [comment]
cette condition vaut vrai dans le cas des minitutos, des articles, des billets et des tutos vides. au moment de leur publication.
