### ISSUE TITLE
[Undo #5347] Le bouton "Version brouillon" n'a rien à faire la

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5462]
Le bouton "-> Version brouillon" s'affiche quand on est déjà dans le brouillon...

Il faut revert #5347 et penser à corriger #5340.

![image](https://user-images.githubusercontent.com/18501150/65945571-932ad180-e434-11e9-9102-c6a4d526983f.png)

**Comment by A-312** [comment]
> c'est aux auteurs + aux staff en fait.
**Artragis**

**Comment by firm1** [comment]
C'est corrigé et mergé, on ferme.

**Comment by A-312** [comment]
@firm1 non, la PR corrige : #5459 😝

**Comment by firm1** [comment]
my bad
