### ISSUE TITLE
Impossible de déplacer une section dans un container s'il y a une section du même nom

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5463]
Bonjour,

Il est impossible de déplacer une section dans un container s'il y a une section du même nom, devrait on modifier le slug et faire nous même le déplacement ?

Attention si la PR est réalisé après #5460 , il faudra modifier le JS , c'est à dire lors du retour de l'ajax, il faudra modifier l'attribut data-slug de l'élément.

**Comment by artragis** [comment]
on peut simplement mettre un message d'erreur

**Comment by A-312** [comment]
A voir mais il faut changer le comportement actuelle (le message orange) n'est pas claire.

**Comment by artragis** [comment]
Drag and drop stoppé
