### ISSUE TITLE
Bug du bouton "banni" dans une fenêtre étroite

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5469]
![image](https://user-images.githubusercontent.com/18501150/66511441-389a1100-ead7-11e9-8de1-9f936b79202f.png)

https://github.com/zestedesavoir/zds-site/blob/e9405362115d279468fab7ec5bd37e2e89a9a011/assets/scss/components/_topic-message.scss#L497-L499

Ne s'applique pas car la classe "badge" est manquante à l'élément HTML, le sélecteur des règles css étant ".badge.push-badge {"

https://github.com/zestedesavoir/zds-site/blob/e9405362115d279468fab7ec5bd37e2e89a9a011/templates/misc/badge.part.html#L12

**Comment by philippemilink** [comment]
Je n'arrive pas à comprendre à quoi sert la classe badge:
https://github.com/zestedesavoir/zds-site/blob/e9405362115d279468fab7ec5bd37e2e89a9a011/assets/scss/components/_topic-message.scss#L488-L495
J'ai l'impression que cette classe n'est utilisée nulle part (et qu'elle est donc inutile).

Si quelqu'un confirme qu'elle est inutile, régler le bug passerait peut-être par un peu de refactoring...

**Comment by A-312** [comment]
Idem, code fantôme il me semble : https://github.com/zestedesavoir/zds-site/search?l=HTML&q=badge
