### ISSUE TITLE
Le lien auto dans le mail de réinit. du mot de passe est faux

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#547]
Lorsque je fais la demande de réinit de mon mot de passe je recois un mail. Tout va bien.
Dans ce mail il y a l'adresse de réinitialisation du mot de passe. Normal.
Cette adresse est proposé comme cliquable ou recopiable mais il n'y a pas de balise `<a>` a cliquer ...

**Comment by firm1** [comment]
Fixé -> mergé -> je ferme
