### ISSUE TITLE
Améliorer l'information des utilisateurs à propos des cookies

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5476]
[Discussion à ce propos sur le forum](https://zestedesavoir.com/forums/sujet/13102/veille-juridique-consentement-aux-cookies/)

- [x] Ne pas enlever la bannière de cookies tant que l'utilisateur n'a pas cliqué sur "Accepter" ou "Refuser"
- [ ] Améliorer la page "À propos des cookies" (détails sur le sujet du forum)

**Comment by Situphen** [comment]
Pour le premier point, il suffit de remplacer le premier code par le deuxième code dans le fichier `templates/base.html` (tout à la fin).

```html
    <script>
        new CookiesEuBanner(function(){
            // script Google Analytics
        });
    </script>
```

```html
    <script>
        new CookiesEuBanner(function(){
            // script Google Analytics
        }, true);
    </script>
```

Source : [Documentation de Cookies EU banner](https://alex-d.github.io/Cookies-EU-banner/#documentation)

**Comment by A-312** [comment]
> Ne pas enlever la bannière de cookies tant que l'utilisateur n'a pas cliqué sur "Accepter" ou "Refuser"

C'est désagréable les pop-up des cookies quand on va sur un nouveau site. On prend déjà en compte l'header DOT, ce n'est pas suffisant ? Surtout que les PRO pour ce point là, on choisi un navigateur déclarant le `DOT=1` dans chacun de leur header. Qui cible ce point ? Les personnes qui n'ont pas d'avis sur cette question ?

------

A la limite mettre une durée ? Comme le masquage après 2 heures.

**Comment by Situphen** [comment]
> C'est désagréable les pop-up des cookies quand on va sur un nouveau site.

Je suis d'accord et ça tombe bien car notre bannière n'est pas une popup ! Elle ne cache aucune information, ne prend pas la moitié de la page et s'intègre bien au design du site web.

> On prend déjà en compte l'header DOT, ce n'est pas suffisant ?

(Je suppose que tu parles du Do Not Track.) À part toi et moi, qui connait l'existence du Do Not Track ? Les développeurs front et les libristes, grosso modo. Le reste de la population, que ce soit Mr et Mme Michu ou les *millenials*, ne connaissent pas ce mot. Or, le Do Not Track n'est pas activé par défaut par Google Chrome, qui tient 64% du marché dans le monde et 58% en France (StatCounter).

> A la limite mettre une durée ? Comme le masquage après 2 heures.

Pourquoi faire compliqué ? D'ailleurs ça ne règle pas le problème du consentement, un utilisateur peut très bien ouvrir l'onglet, le laisser de côter et revenir dessus 2 heures et 1 minutes plus tard. Bon c'est un peu tiré par les cheveux, mais je pense que la solution qui est la plus simple et la meilleure pour l'utilisateur c'est qu'on lui laisse notre petite bannière avec deux boutons en évidence. Il lit les deux petites lignes (ou pas) et il clique sur un bouton, paf la bannière disparait.

**Comment by A-312** [comment]
> > On prend déjà en compte l'header DOT, ce n'est pas suffisant ?
> 
> (Je suppose que tu parles du Do Not Track.) À part toi et moi, qui connait l'existence du Do Not Track ? Les développeurs front et les libristes, grosso modo. Le reste de la population, que ce soit Mr et Mme Michu ou les _millenials_, ne connaissent pas ce mot. Or, le Do Not Track n'est pas activé par défaut par Google Chrome, qui tient 64% du marché dans le monde et 58% en France (StatCounter).

Ce n'est que les plus bricoleurs d'entre nous qui comprennent le mal de ces 🍪 et qui veulent les désactiver

**Comment by Situphen** [comment]
> Ce n'est que les plus bricoleurs d'entre nous qui comprennent le mal de ces 🍪 et qui veulent les désactiver

Tout le monde ne sait pas ce qu'est un cookie, effectivement, mais je pense qu'il y a des personnes qui savent vaguement ce qu'est un cookie, ce qu'est la mesure d'audience mais qui ne connaissent pas DNT. Et puis même si les gens ne connaissent pas ce qu'est un cookie ou la mesure d'audience, c'est à nous de leur expliquer via cette bannière et la page À propos des cookies.

**Comment by artragis** [comment]
C'est une obligation légale. y'a pas de débat à avoir : on ne peut pas faire de conscentement par défaut.

pour l'amélioration, je vais demander à Arius de passer pour nous fournir le texte à changer. 

Ca serait bien que ça passe en hotfix.

**Comment by A-312** [comment]
> C'est une obligation légale. y'a pas de débat à avoir : on ne peut pas faire de conscentement par défaut.

[ou pas...](https://www.cnil.fr/fr/solutions-pour-les-cookies-de-mesure-daudience)

**Comment by artragis** [comment]
Ta propre source dit : 

> Avant de déposer ou lire un cookie, les éditeurs de sites ou d'applications doivent :
>
> -  informer les internautes de la finalité des cookies
> -  obtenir leur consentement 
> -  fournir aux internautes un moyen de les refuser. 
>
La durée de validité de ce consentement est de 13 mois maximum. 
>
Les cookies nécessaires à la fourniture d’un service expressément demandé par l’utilisateur sont dispensés du recueil de ce consentement.

Donc il faut **recueillir le consentement** et la CJUE te dit que le **consentement** doit forcément être actif. DOnc si c'est une obligation légale.

**Comment by artragis** [comment]
PS: y'a quand même un GROS AVERTISSEMENT qui dit en plus que la page est obsolète... je te laisse deviner pourquoi.

**Comment by philippemilink** [comment]
On peut fermer maintenant, non ?

**Comment by Situphen** [comment]
> On peut fermer maintenant, non ?

Oui ! Le ticket était resté ouvert car lorsqu'on utilisait les cookies pour de la mesure d'audience on devait préciser certaines choses dans la page "À propos des cookies" mais à ma connaissance ce n'est plus le cas maintenant.
