### ISSUE TITLE
Augmenter légèrement la taille des équations de maths ?

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5477]
Dans [ce sujet du forum](https://zestedesavoir.com/forums/sujet/13104/limite-a-droite-avec-katex/?page=1#p209856), il y a une équation de maths avec des indices difficiles à lire. J'ai l'impression que nos équations sont affichées un peu plus petites que sur le site de KaTeX. Je propose qu'on augmente un peu la taille des équations de maths pour rendre leur lecture plus simples.

**Comment by Situphen** [comment]
# Pour les équations entre les paragraphes

Je pense que l'option 1 est la meilleure car l'option 2 est trop grande par rapport au texte (qui est en `font-size: 1.4rem`).

## Actuellement : `font-size: 1.4rem`

![image](https://user-images.githubusercontent.com/6664636/134769053-3599d91d-135b-4275-8e8e-6dc2b308a4e0.png)
![image](https://user-images.githubusercontent.com/6664636/134769111-2163dd48-28f2-4e43-9f7a-e5a5c59358be.png)


## Option 1 : `font-size: 1.6rem`

![image](https://user-images.githubusercontent.com/6664636/134769074-09b43328-cfa2-4c29-b1ab-72cc49c712b1.png)
![image](https://user-images.githubusercontent.com/6664636/134769181-8038411d-8782-45a2-91b3-3d69a97780de.png)


## Option 2 : `font-size: 1.8rem`

![image](https://user-images.githubusercontent.com/6664636/134769091-f8426527-5b86-4269-9cac-3d3e06b4ba04.png)
![image](https://user-images.githubusercontent.com/6664636/134769188-52a54b8d-1082-4478-8107-d2d531a73a05.png)

**Comment by Situphen** [comment]
# Pour les équations au sein d'un paragraphe ou d'une liste

Je pense qu'il faut rester comme actuellement car on est à la même taille que le texte (qui est en `font-size: 1.4rem` aussi) et que si on augmente ça va faire un peu tâche. De toute façon il ne devrait pas y avoir d'équations importantes au sein d'un paragraphe.

## Actuellement : `font-size: 1.4rem`

![image](https://user-images.githubusercontent.com/6664636/134769336-0be6b7a9-c1d6-4f37-8866-fab926893539.png)

## Option 1 : `font-size: 1.6rem`

![image](https://user-images.githubusercontent.com/6664636/134769346-5e360aca-8547-4ed6-b892-36246c698557.png)

## Option 2 : `font-size: 1.8rem`

![image](https://user-images.githubusercontent.com/6664636/134769359-24964b09-731f-4291-9837-03e61b3f6013.png)

**Comment by Arnaud-D** [comment]
D'accord, avec toi. Option 1 pour les équations *block*, qui améliore la lisibilité des petits caractères en indice, et rester comme actuellement quand c'est *inline*.

**Comment by Situphen** [comment]
**Instructions :**

- Pour les équations au sein d'un paragraphe ou d'une liste : rien ne change
- Pour les équations entre les paragraphes : on passe met `font-size: 1.6rem` au lieu de la taille par défaut

Dans le fichier `assets/scss/base/_content.scss` aux alentours de la ligne 580, ajouter ce code : 

```scss
.math-display {
    font-size: 1.6rem;
}
```

**Comment by Arnaud-D** [comment]
Et encore mieux, utiliser `$font-size-9`, qui vaut actuellement `1.6rem` ! Pour information, c’est défini dans le fichier `assets/scss/variables/_typography.scss`.
