### ISSUE TITLE
Impossible de signaler un sujet ne comportant qu'un message masqué en étant un simple membre

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5482]
Bonjour,

On ne peut pas signaler un message masqué en tant que simple membre. Je vois très bien pourquoi, mais cela a un effet de bord : on ne peut pas signaler un sujet qui ne comporte qu'un message masqué. Parce qu'on ne peut pas signaler un sujet.

Comme [là](https://zestedesavoir.com/forums/sujet/13123/algorithme-python/).

Bonne journée,  
Gabbro.

Sujet : https://zestedesavoir.com/forums/sujet/13127/impossible-de-signaler-un-sujet-ne-comportant-quun-message-masque/
*Envoyé depuis Zeste de Savoir*

**Comment by Arnaud-D** [comment]
Résolu par #5711.
