### ISSUE TITLE
Mettre a jour les fichiers GeoIP

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5486]
Il serait bien de mettre a jour les fichiers GeoIP en passant a GeoIP2 (ce qui d'ailleurs permet la geolocalisation des IPv6)

[Documentation Django du module a utiliser](https://docs.djangoproject.com/fr/1.11/ref/contrib/gis/geoip2/)
[Fichiers a telecharger](https://dev.maxmind.com/geoip/geoip2/geolite2/)

**Comment by Situphen** [comment]
En fait, je me demande si la géolocalisation à vraiment une utilité ou pas. J'ai beau réfléchir je ne vois pas vraiment de cas où c'est utile.

**Comment by firm1** [comment]
> En fait, je me demande si la géolocalisation à vraiment une utilité ou pas. J'ai beau réfléchir je ne vois pas vraiment de cas où c'est utile.

Elle est utile pour par exemple, faire des recoupements entre profils suspects. Parfois l'IP n'est pas très parlante et on s'en souviens moins facilement en cas de récidive.

**Comment by Situphen** [comment]
Si l'adresse IP est identique il y a la page pour voir tous les membres avec la même adresse IP et si elle est différente, rien ne dit que les deux IPs seront localisées dans la même ville. Enfin en tous cas si tu trouves que c'est utile alors gardons, seulement le Staff y a accès et il n'y a pas d'abus.
