### ISSUE TITLE
[Bug][Mineur] Formulaire d'édition après import d'un tuto

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#549]
Après import d'un tuto, il y a un petit souci dans le formulaire d'édition du tuto : on ne peut pas choisir mini-tuto/big-tuto dans le type de cours, le select est en mode `disabled="True"`.

Du coup, si par exemple on ajoute un logo au cours, et qu'on lui assigne une licence et des tags, et qu'on valide, on se fait jeter avec une erreur sur le champ "type de cours", précisant qu'il faut obligatoirement donner un type au cours. Et cette fois, le select est bien déroulable, ce qui n'était pas le cas avant d'avoir validé une première fois le formulaire.

Et c'est pareil à chaque nouvelle édition : la première fois qu'on arrive sur le formulaire d'édition du tuto, le select n'est pas utilisable. Il faut d'abord valider une première fois le formulaire, se faire jeter parce qu'on a pas choisi le type, et ensuite on peut y accéder... et faire nos changements.

**Comment by firm1** [comment]
fixé -> mergé -> je ferme
