### ISSUE TITLE
Finir l'intégration back du drag'n'drop des sections et parties d'un tuto

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5500]
Vu que j'ai fermé la PR car elle a été merge sur la branch de travail, j'ouvre cette issue pour ne pas oublier les modification qu'il reste à faire.

Finir l'intégration du BACK pour #5460 (ce qui est marqué en TODO dans le JS) c'est-à-dire : 

 - [x] Permettre de déplacer dans une partie vide (-> #5478 );
 - [x] Après avoir déplacé un élément les boutons "DEPLACER" disparaissent -> il faudrait mettre à jour la liste au lieu de faire disparaître les boutons **TOUTEFOIS** je conseille de faire  #5457 avant de s'attaquer à ce point, pour ne pas devoir s'y reprendre à deux fois ;
 - [x] Améliorer le retour du back, en retournant seulement {error:true/false, message: "le message"}

**Comment by artragis** [comment]
@firm1 je vais implémenter #5478 demain.

**Comment by A-312** [comment]
j'ai oublié : 

```js
// TODO : [BACK] Change slug if we have the same.
```

**Comment by artragis** [comment]
mmmh, il me semble que j'avais retiré ce point volontairement pour le décaler à 2019.1

**Comment by A-312** [comment]
Oh j'avais pas vu

> - [ ]  ~~Renommer le slug si slug identique dans la destination (-> 5463)~~ ;
