### ISSUE TITLE
Corriger l'affichage d'une ipv6 sur le profil

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5506]
Il faudrait corriger l'affichage de l'ipv6 (corriger le retour à la ligne) avec : 
`aaaa:aaa:aaaa:aaaa:aaaa:aaaa:aaaa:aaaa`

# Sur PC : 
![image](https://user-images.githubusercontent.com/18501150/68231312-196da100-fffb-11e9-9ffd-68f4c29a2aff.png)

# Sur mobile : 
![image](https://user-images.githubusercontent.com/18501150/68231323-1ecaeb80-fffb-11e9-9049-f33a4e8da2ef.png)

Il faudrait éviter le retour à la ligne sur PC et mobile (text-overflow et nowrap), sur mobile la ligne est coupée.

**Comment by helmasaur** [comment]
Il faut être modérateur pour avoir accès à cette information ?

**Comment by A-312** [comment]
rang staff

**Comment by Arnaud-D** [comment]
Je ne peux pas reproduire le problème décrit. Je pense que c'est corrigé par #5350 et en particulier [ce commit](https://github.com/zestedesavoir/zds-site/pull/5350/commits/afd0f3cdc2a67377859f92d6cdf44b6ddf6c5184) qui introduit le bloc "Présence".

Ça dépasse encore sur des écrans de moins de ~280 pixels de large (d'après un test rapide), mais ça devient excessivement rare de nos jours d'avoir des téléphones faits pour le web avec de tels écrans, a fortiori au sein de la population restreinte du staff. Pas la peine de s'en inquiéter avant que ça ne survienne effectivement.
