### ISSUE TITLE
Profil : Rajouter une balise bold (<strong>) sur les valeurs numériques

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5507]
Comme ceci : 

![image](https://user-images.githubusercontent.com/18501150/68231774-fee7f780-fffb-11e9-8782-51b1edcbb825.png)

Au lieu de : 
![image](https://user-images.githubusercontent.com/18501150/68231890-3ce51b80-fffc-11e9-8d3a-f0e4bf25f955.png)

**Comment by artragis** [comment]
on va mettre strong à la limite. Sinon un simple span + style.

**Comment by nils-van-zuijlen** [comment]
`<strong>` a un sens sémantique d'importance alors que `<b>` ou `<span class="bold">` n'en a pas. Il faut savoir si les nombres sont vraiment importants, ou si c'est simplement de l'esthétisme.

**Comment by A-312** [comment]
#TeamB

**Comment by artragis** [comment]
pour moi le but c'est vraiment de mettre l'emphase d'où strong. 
Sinon c'est span, pas b.
