### ISSUE TITLE
Profil : Rajouter une balise bold (<b>) sur les valeurs numériques

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5508]
Comme ceci : 

![image](https://user-images.githubusercontent.com/18501150/68231774-fee7f780-fffb-11e9-8782-51b1edcbb825.png)

Au lieu de : 
![image](https://user-images.githubusercontent.com/18501150/68231890-3ce51b80-fffc-11e9-8d3a-f0e4bf25f955.png)

**Comment by artragis** [comment]
pourquoi close?

**Comment by A-312** [comment]
@artragis J'ai eu une erreur 500, j'ai actualisé en pensant que mon formulaire n'était pas envoyé mais j'ai fais doublon avec #5507
