### ISSUE TITLE
Paquet 'realpath' inexistant dans ArchLinux

### ISSUE THREAD

**Issue by Titome** [zestedesavoir/zds-site#5512]
Bonjour à tous,

Content de faire mon 1er ticket et de contribuer à Zds :)

Je suis en train de faire l'installation pour ArchLinux mais le paquet `realpath` n'existe pas.
En effet, l'utilitaire `realpath` est fourni dans le paquet [coreutils](https://www.archlinux.org/packages/core/x86_64/coreutils/).
Qui est lui-même, inclus dans le paquet [base](https://www.archlinux.org/packages/core/any/base/) qui est installé normalement quand on installe ArchLinux ([procédure d'installation "officielle" du wiki d'ArchLinux](https://wiki.archlinux.org/index.php/Installation_guide#Install_essential_packages)).
Je ne sais pas si on peut installer ArchLinux sans le paquet `base`...

Je vois 2 solutions :
- Supprimer purement et simplement la dépendance `realpath` en considérant qu'il est installé via le paquet `coreutils` qui est lui-même installé par la paquet `base` installé lors de l'installation d'ArchLinux.
- Remplacer `realpath` par `coreutils` quitte à le réinstaller mais en ayant l'assurance qu'il soit là. Solution plus safe pour moi.

Qu'en pensez-vous ? Merci :)

**Comment by artragis** [comment]
Il suffit de mettre `coreutils` à la place de `realpath` [ici](https://github.com/zestedesavoir/zds-site/blob/dev/scripts/dependencies/arch.txt#L8).

Du coup c'est la seconde solution.

Merci pour ta participation ^^

**Comment by A-312** [comment]
@Titome Tu penses pouvoir faire la modification/PR ? (On ne souhaite pas rebuter les nouveaux contributeurs^^)

**Comment by Titome** [comment]
Affirmatif !

**Comment by A-312** [comment]
Corrigé dans #5440 

Il me semble que le Q/A a été fait, il faut juste la merge (il me semble). Ping @artragis

**Comment by Titome** [comment]
Corrigé dans la #5440
