### ISSUE TITLE
Coveralls: Le rapport semble être erroné

### ISSUE THREAD

**Issue by sylafrs** [zestedesavoir/zds-site#5513]
Chaque fichier semble être présent plusieurs fois avec des coverages différent et le rapport pour la pull request ne nous aide pas à savoir quel couverture a effectivement changé.

Peut-être suivre ces instructions : https://docs.coveralls.io/parallel-build-webhook ?

(https://github.com/lemurheavy/coveralls-public/issues/1133)

**Comment by sylafrs** [comment]
https://pypi.org/project/coveralls-check/

**Comment by sylafrs** [comment]
(La première référence est mauvaise, le raccourci de l'éditeur pointant sur les pull requests de mon fork et non du dépôt officiel ^^')

**Comment by sylafrs** [comment]
Ensuite, y'a des gens qui ont choisi de changer coveralls par codecov : 
https://github.com/Delgan/loguru/commit/21bb44a5e6c7b62d8059ab0a6ed7dc63e11ba6d3

https://codecov.io/

Je ne sais pas à quoi ça ressemble mais ça a l'air gratuit pour l'Open Source

**Comment by sylafrs** [comment]
Voici un exemple de dépot avec Codecov : https://codecov.io/gh/delgan/loguru/branch/master

**Comment by A-312** [comment]
Il y a des exceptions qui font qu'on ignore certain test dans certain PR pour accélérer le résultat de travis

**Comment by sylafrs** [comment]
ah, et ce serait ces optimisations qui rendrait coverage incorrect, du coup, puisque certaines parties ne sont plus couvertes :|

On aurait alors le même problème avec codecov..

Il faudrait tester la couverture de test avec un outil local plutôt qu'avec un outil en ligne avec webhook.. Je vais chercher un outil qui existe, quelqu'un en connait ici ?

**Comment by sylafrs** [comment]
Du coup, est-il utile de garder le webhook/l'appel à coverage ? il risque d'induire en erreur..

J'ai cru un moment donné que mes tests posaient problème..

Je vais tenter ça : https://docs.djangoproject.com/fr/2.2/topics/testing/advanced/#integration-with-coverage-py

Est-il possible de désactiver l'optimisation pour une session de test ?

------------

Edit: j'ai peut-être mal compris la réponse : c'est un truc random ou automatique dans les tests ou c'est un test modifié volontairement dans certaines PR ?
Parce que pour le coup, j'ai eu des rapports erroné sur deux commits fait à la suite alors qu'aucune PR n'a été mise à jour sur le site

**Comment by A-312** [comment]
Alors : 

 1. Travis exécute les scripts qu'on lui donne dans notre config ;
 2. Arrivez à cette ligne : https://github.com/zestedesavoir/zds-site/blob/97d449befa103f79ed6b29fc3866e6a6664fc5d2/.travis.yml#L79 il appelle `./scripts/travis_header.sh` ;
 3. Arrivez à la ligne 91 : https://github.com/zestedesavoir/zds-site/blob/97d449befa103f79ed6b29fc3866e6a6664fc5d2/scripts/travis_header.sh#L91-L93 il appelle `./scripts/ci_turbo.sh` ;
 4. https://github.com/zestedesavoir/zds-site/blob/97d449befa103f79ed6b29fc3866e6a6664fc5d2/scripts/ci_turbo.sh#L20

Mais normalement cette PR n'active pas l'optimisation, je me demande même si j'ai correctement implémenté coveralls et si avant il était correctement implémenté aussi.

**Comment by Situphen** [comment]
Coveralls fonctionne bien maintenant et on utilise Github Actions donc on n'ignore plus certains tests donc je ferme.
