### ISSUE TITLE
Prevenir quand un migrate est nécessaire

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5519]
Bonjour,

Je ne sais pas si c'est facile à faire mais pour les nouveaux contributeurs, il serait intéressant de prévenir (affichage un message qu'il est nécessaire de migrate) ou de faire automatiquement le migrate (`python manage.py migrate`) dans le but de simplifier l'accès au ZDS.

Bon vol,

A.

**Comment by artragis** [comment]
django le fait déjà;

**Comment by A-312** [comment]
ah bon j'ai rien vu ? :(

**Comment by artragis** [comment]
il te dit que ton modèle est pas à jour.

**Comment by A-312** [comment]
Si je comprends c'est une warning qui s'affiche en première ligne avant une dizaine de ligne du démarrage, et sans parler des logs de la première requête HTTP qui vont apparaître, ça me semble être peu visible.

**Comment by A-312** [comment]
![image](https://user-images.githubusercontent.com/18501150/79978070-943e5180-849f-11ea-80f0-f1bbe0081600.png)
Je ne suis pas encore assez remonté :
![image](https://user-images.githubusercontent.com/18501150/79978122-ab7d3f00-849f-11ea-89d8-d55536e4d40f.png)
Encore un peu:
![image](https://user-images.githubusercontent.com/18501150/79978178-c0f26900-849f-11ea-8a9f-fb5ebc0c6caf.png)
Trouvé:
![image](https://user-images.githubusercontent.com/18501150/79978212-d8315680-849f-11ea-8b3b-76e93c3bd524.png)

On fait difficilement plus agréable pour les nouveaux arrivants
