### ISSUE TITLE
Ajouter un panneau "Ces contenus pourraient vous intéresser"

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#5526]
Cette feature est une partie intégrante de la feature des "parcours". L'idée est ici de proposer aux gens un autre contenu qui pourrait intéresser.

Pour éviter les problème de pertinence (et parce que ça n'est pas réellement demandé par la communauté), ces propositions ne sont pas basées sur un automatisme, mais sur une vraie décision éditoriale.

Lorsqu'un validateur ou une personne de l'équipe de communication arrive sur **la version public** du tutoriel ou d'un article (pas les billets), il voit, entre le tuto, il voit un bouton "Ajouter une suggestion", qui le mène à une modale sur laquelle il trouvera un champ de recherche qui lui permettra de cherche puis sélectionner les contenus intéressants.

En dessous de ce bouton, (ou simplement entre le tuto et les commentaires pour les non staff) apparaissent 3 des suggestions sélectionnées, sélectionnées au hasard parmi la liste.

s'il n'y a pas de suggestion, alors on n'affiche rien.

En fonction de la difficulté à implémenter, on pourra ajouter la fonctionnalité suivante au formulaire de sélection : si la case "la suggestion est réciproque" est cochée, alors le tuto 1 sera suggérer sur le tuto 2 et le tuto 2 sur le tuto 1.

**Comment by firm1** [comment]
Question sur ce ticket.

> il voit un bouton "Ajouter une suggestion", qui le mène à une modale sur laquelle il trouvera un champ de recherche qui lui permettra de cherche puis sélectionner les **contenus** intéressants.

Les contenus ce sont :

- option 1 : les contenus validés
- option 2 : tous les contenus zds (tuto, article, billet)
- option 3 : tous les contenus voire externes (liens articles externes, youtube, etc)

Quelle est la bonne reponse ?

**Comment by artragis** [comment]
Tous les contenus "validés" : tuto, article, billets "choisis" (i.e dont on sait qu'ils respectent les règles). Ajoutons que cette fonctionnalité à pour but de garder les gens sur le site donc pas de contenus externes (on verra pour les parcours complets si on doit ou non ajouter ce genre de contenus)
