### ISSUE TITLE
Petit bug d'affichage quand on déplace une partie (effet disabled non voulu)

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5531]
Quand on déplace (avec le drag'n'drop) une partie "Section A" et "Section B" d'"ajouter un chapitre" devient surligné (à cause de l'attribut "disabled" qui s'ajoute), il faudrait corriger ça : 

![image](https://user-images.githubusercontent.com/18501150/69498687-fa23ae80-0eea-11ea-8e6c-a29bafb93069.png)

Résultat attendu : 

![image](https://user-images.githubusercontent.com/18501150/69498692-04de4380-0eeb-11ea-94ca-04d606c1953a.png)

Solution : Overwrite la règle "background" qui s'applique pour a[disabled].

**Comment by A-312** [comment]
Il faudrait déjà que le changement soit merge sur dev. 😖

**Comment by philippemilink** [comment]
Puisque le drag'n'drop pour réorganiser les contenus n'a pas été mergé, je ferme.
