### ISSUE TITLE
On ne peut pas déplacer un extrait dans une partie vide

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5538]
On ne peut pas déplacer (glisser) un extrait dans une partie vide pour faire un chapitre. :/
![image](https://user-images.githubusercontent.com/18501150/69672736-05b4d800-1099-11ea-89f1-6ea2deea2c7c.png)

On devrait pouvoir

Je n'ai pas réussi à le faire, j'avais commencé à faire quelques choses avec : 
```js
  const $content = $("#content > article > section[data-slug]")
  $content.find("> div.article-part[data-slug] > div.article-containers").each(function () {
    console.log($(this).children("div.article-part[data-slug]"))
    if (!$(this).children("div.article-part[data-slug]")[0]) {
      $(this).attr("data-children-type", "both")
    }
  })
```

**Comment by A-312** [comment]
La solution est de prévoir deux blocs et d'afficher/masquer un des deux dans onStart c'est a dire ajouter un bloque : 
`<ol class="summary-part" data-children-type="extract" data-slug="{{ child.slug }}">`
au dessous de : 
`<div class="article-containers" data-children-type="container" data-slug="{{ child.slug }}">`

dans child.part.html

La logique du code sera donc d'afficher le `ol` si on commence à déplacer un extract sinon afficher le `data-children-type="container"`.

EDIT : Petite difficulté quand il n'y a pas de `li` dans le ol, ça ne veut pas drag à l'intérieur (solution possible : mettre un min-height ?)

EDIT 2 : Ou modifier le html pour que le bloc "warning" soit dans une li.

**Comment by A-312** [comment]
Pas top comme idée (notamment si la partie devient vide) 🤔 Il faudrait utiliser une seule callback pour les deux types.

**Comment by A-312** [comment]
**(J'utilise les commentaires comme bloc-notes pour ma prochaine PR/mon prochain fix).**

Ou : https://github.com/SortableJS/Sortable/issues/790#issuecomment-197940317

**Comment by artragis** [comment]
Il faut que tu recommences de 0. utilise ton propre repo si tu as besoin d'une todo list. le backlog de zds est fait pour les features et bugs du repo pas de tes PR.

**Comment by A-312** [comment]
Ce problème n'a pas été corrigé dans la branche :confused:

**Comment by artragis** [comment]
la branche sera supprimée dès que tu auras cherry pick ce dont tu as besoin pour continuer. A l'heure actuelle ce projet est bancal, la solution technique proposée n'est pas bonne.
