### ISSUE TITLE
Notification persistante liée à la publication d'un billet

### ISSUE THREAD

**Issue by AmauryCarrade** [zestedesavoir/zds-site#5544]
En version `v28.2b-feve/ec79eed`.

J'ai une notification persistante vers un billet, notification provenant de moi-même (déjà ça c'est un peu étrange mais soit). Le contexte du billet est particulier : juste après sa publication, mais _avant_ de cliquer sur la notification et de visiter le billet, je suis allé sur la version brouillon me retirer des auteurs (car je n'avais rien fait).

Cela dit, [la version en ligne me compte toujours comme auteur (je suis dans la liste publique)](https://zestedesavoir.com/articles/3327/recap-communautaire-21-novembre-2019/).

![Oh ma belle notification](https://user-images.githubusercontent.com/1417570/70189692-42fe1300-16f4-11ea-94e2-a5bf9108aa76.png)

Une possibilité (à vérifier) : je me demande si je ne m'auto-suivais pas à une période (pour voir si ça marchait et c'est peut-être resté), donc potentiellement lié à ça. Donc potentielles étapes pour tenter de reproduire : 

1. On suit une personne.
2. Cette personne publie un contenu.
3. On reçoit une notification pour ça, vu qu'on est abonné⋅e. Mais on ne clique pas dessus.
4. Cette personne se retire des auteurs dans la version brouillon.
5. On clique sur la notification. Peut-être, alors, persiste-t-elle.

Peut-être lié à #4972.

**Comment by Situphen** [comment]
Je l'ai reproduit en bêta avec Amaury en suivant son protocole !

**Comment by AmauryCarrade** [comment]
On a testé avec @Situphen et c'est bien ça, on reproduit la persistance avec ces cinq étapes

![image](https://user-images.githubusercontent.com/1417570/70190646-bf91f100-16f6-11ea-8b42-1a36a9905b69.png)
