### ISSUE TITLE
[Bug][Mineur] Fil d'ariane foireux dans les forums

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#555]
Ça ne le faisait pas avant, donc je soupçonne un récent copier/coller foireux, mais par exemple le lien "Communauté" du fil d'Ariane sur cette page me renvoie au topic en cours au lieu de me renvoyer vers la catégorie de forum : 
=> http://zestedesavoir.com/forums/sujet/87/bug-tracker/?page=3

**Comment by SpaceFox** [comment]
Effectivement il n'y a plus d'URL renseignée ici dans ce bloc... je corrige.

**Comment by Alex-D** [comment]
C'est corrigé, je feme donc :)
