### ISSUE TITLE
Mettre à jour Elastic Search en 6.x puis en 7.x

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5554]
On utilise Elastic Search 5.x qui n'est plus maintenu, il faut donc mettre à jour en 6.x puis en 7.x

J'ai mis à jour l'installation d'Elastic Search sur [ma branche `elastic`](https://github.com/Situphen/zds-site/tree/elastic), mais je vous avoue que je n'ai pas la motivation pour me plonger dans Elastic Search et faire les changements nécessaires.

**Comment by A-312** [comment]
Pour ce qui est de travis et le script d'installation, surement le numéro de version de jdk : https://github.com/zestedesavoir/zds-site/blob/2c9f6c884550dc47d0529ff8cc1e51e8f98385fa/scripts/define_variable.sh#L24-L26

et (bien entendu) : 
https://github.com/zestedesavoir/zds-site/blob/2c9f6c884550dc47d0529ff8cc1e51e8f98385fa/scripts/define_variable.sh#L16

**Comment by Situphen** [comment]
Normalement JDK 11 fonctionne avec ElasticSearch 5, 6 ou 7. Il ne devrait pas y avoir besoin de le changer.

**Comment by A-312** [comment]
Bien ! Je pensais qu'on était à la limite basse du support

**Comment by Situphen** [comment]
Si quelqu'un souhaite s'occuper de ce ticket, il est possible de s'inspirer de la PR qui a été fermée

**Comment by philippemilink** [comment]
On est passé à Typesense #6475, le problème n'est donc plus présent ; je ferme.
