### ISSUE TITLE
Mettre à jour Factory Boy en 2.12.0 puis en 3.1.0

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5555]
Il y a plusieurs changements à faire dans les fichiers `factories.py`. Dans le cas où je n'aurais pas la motivation ou le temps pour finir tous ces changements, n'hésitez pas à reprendre mon travail depuis [ma branche `factory-boy`](https://github.com/Situphen/zds-site/tree/factory-boy).

**Comment by artragis** [comment]
est-ce vraiment utile en vra?

**Comment by Situphen** [comment]
D'après leur *changelog*, la version 2.12.0 ajoute le support de Python 3.7 et Django 2.1 et la version 2.12.1 (pas encore publiée) ajoute le support de Python 3.8 et Django 2.2.

Je pense que avec notre code actuel, ça ne pose pas de soucis de rester sur la version 2.8.1. Par contre, si on se met à utiliser des fonctionnalités spécifiques à Python 3.7/3.8 ou Django 2.1/2.2 alors il sera probablement nécessaire de mettre à jour.

En résumé, c'est pas urgent de mettre à jour tout de suite.
