### ISSUE TITLE
Améliorer le % de coverage du badge dans le README.md

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5558]
Dans le script travis, il faut ajouter une condition pour savoir si la branch est "dev", si oui, on fait tous les tests peu importe les changements. :)

**Comment by artragis** [comment]
en fait il faudrait faire tous les tests tout le temps.

**Comment by A-312** [comment]
https://coveralls.io/github/zestedesavoir/zds-site?branch=dev

![image](https://user-images.githubusercontent.com/18501150/71835763-a3e18800-30b2-11ea-8499-7e59e4cbd7c0.png)

 2. Il y a des tests pour tutorialv2/management/commands ?

![image](https://user-images.githubusercontent.com/18501150/71835778-af34b380-30b2-11ea-8d46-da60320f4793.png)

 3. Comment on lance les middlewares/tests ?

![image](https://user-images.githubusercontent.com/18501150/71835840-e0ad7f00-30b2-11ea-9c85-1021f49d9289.png)

 4. Les settings devraient elles être exclues ? 

![image](https://user-images.githubusercontent.com/18501150/71835868-fa4ec680-30b2-11ea-92ec-36e155926a1e.png)

 5. On est sûr d'avoir assez de test pour tutorialv2 ?

**Comment by artragis** [comment]
46.02%e views c'est vraiment étrange.

**Comment by A-312** [comment]
selenium n'est pas pris en compte

**Comment by artragis** [comment]
c'est fort dommage et anormal
mais même sans ça on a des tests assez complets sur tutorial v2 y'a une couille là.

**Comment by A-312** [comment]
Tu as vu : https://github.com/zestedesavoir/zds-site/pull/5561#issuecomment-571365765

**Comment by A-312** [comment]
@artragis As-tu vu https://github.com/zestedesavoir/zds-site/pull/5561#issuecomment-571365765 ?

**Comment by artragis** [comment]
oui
