### ISSUE TITLE
Ne pas accepter les pseudos avec des caractères Unicode invisibles

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5559]
Ne pas accepter les pseudos avec des caractères Unicode invisibles.

Il existe probablement des fonctions pour filtrer ces caractères là, ce qui permettrait d'éviter l'usurpation de pseudo.

**Comment by enzzc** [comment]
Il existe en effet une fonction de la lib standard en Python pour vérifier la catégorie Unicode d'un caractère, [`unicodedata.category`](https://docs.python.org/3/library/unicodedata.html#unicodedata.category), dont un tableau peut être trouvé ici : https://en.wikipedia.org/wiki/Unicode_character_property#General_Category

Ça pourrait faire un bon premier PR pour les contributeurs débutant !

**Comment by A-312** [comment]
> Il existe en effet une fonction de la lib standard en Python pour vérifier la catégorie Unicode d'un caractère, [`unicodedata.category`](https://docs.python.org/3/library/unicodedata.html#unicodedata.category), dont un tableau peut être trouvé ici : https://en.wikipedia.org/wiki/Unicode_character_property#General_Category
> 
> Ça pourrait faire un bon premier PR pour les contributeurs débutant !

Donc on autorise L*, N*, M*, S* ? Bien qu'on pourrait diminuer encore cette liste en virant certain modifieur.

On a vraiment besoin d'avoir plus que : A-z0-9 -_@éèœ... ?

**Comment by enzzc** [comment]
> Donc on autorise L*, N*, M*, S* ? Bien qu'on pourrait diminuer encore cette liste en virant certain modifieur.

Il faut voir, car si on n'accepte aucun Z*, alors on n'accepte pas non plus les espaces classiques.


> On a vraiment besoin d'avoir plus que : A-z0-9 -_@éèœ... ?

Je ne pense pas. En plus, vérifier ce petit ensemble est une solution assez simple et fiable, pas besoin de partir dans les filtres de caractères Unicode plus complexes.
Dans la pratique, tout le monde a un pseudo en alphabet romain sur ZdS.

**Comment by SpaceFox** [comment]
La solution des caractères invisibles est une étape simple mais ça n'est pas la plus sûre.

Le plus efficace, c'est de passer par un "squelette" : Unicode fournit des listes fde caractères ou suites de caractères que l'on peut confondre visuellement (cf les liens de cette doc : https://github.com/vhf/confusable_homoglyphs/blob/master/README.rst)

Partant de là, on peut "normaliser" le pseudo à un "squelette" : deux pseudo avec des caractères qui se ressemblent donnent le même squelette. Ce squelette n'est jamais affiché et ne sert jamais au login, par contre il est unique en base : on ne peut pas créer un compte si un autre a déjà le même squelette.

Ça permet de gérer simplement et définitivement tous les problèmes pseudo qui se ressemblent, sans avoir à interdire le moindre caractère.

Reste à voir comment on génère les squelettes : les outils Unicode pour JVM le font, je ne sais pas en ce qui concerne Python.

**Comment by SpaceFox** [comment]
PS : je trouverais très dommage de limiter les caractères possibles dans les pseudo _alors que la solution pour faire autrement existe_. Non seulement pour moi ça n'a plus de sens en 2020, mais en plus c'est contradictoire avec l'esprit d'ouverture de ZdS.

**Comment by enzzc** [comment]
> PS : je trouverais très dommage de limiter les caractères possibles dans les pseudo alors que la solution pour faire autrement existe. Non seulement pour moi ça n'a plus de sens en 2020, mais en plus c'est contradictoire avec l'esprit d'ouverture de ZdS.

Oui, ça serait sans doute dommage. Mais, il y a la question de savoir quelle complexité technique il faut être prêt à payer, et si ce prix est en adéquation avec la valeur que ça apporterait aux utilisateurs. 

Cela dit, la méthode des squelettes, que je ne connaissais pas, semble être une solution élégante et définitive.
