### ISSUE TITLE
Passer les URLs au Kärcher

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#556]
Les URLs sont gérées à peu près aléatoirement :
- Parfois on a des IDs
- Parfois on a des slugs
- Parfois on a les deux
- Parfois on a des paramètres de type "_query string_" (qui en général sont récupérés en GET sans aucun contrôle).

Bref, c'est l'anarchie... et réparer ça est un bazar innommable : il y a 80% des URLs à réécrire, et réécrire une URL qui a été "conçue" avec des _query strings_ nécessite de modifier **tous** ses appels !

D'un point de vue technique pure, l'idéal serait de ne jamais avoir de slug, mais c'est moyen pour l'utilisateur : il n'a pas la moindre idée de ce qu'il y a dans la page sans aller voir.

Du coup je sais pas trop...

**Comment by SpaceFox** [comment]
PS : puisque ça implique des changements d'URLs, c'est à faire idéalement avant l'ouverture au public.

**Comment by geoffreyc** [comment]
De manière générale, personnellement, j'utilise slug/id dans l'URL pour
afficher une page, et les query strings pour changer l'information sur
cette page. Par exemple , /forum/cat/général/ affiche la liste des posts
dans le forum, et /forum/cat/général/?page=2&solved=true afficherait la
page 2 des posts résolus .

**Comment by SpaceFox** [comment]
Et pour une action sur cette page ?

Si pour afficher un forum j'ai /forum/1/mon-forum/ (id / slug, c'est ce
qu'on a de plus fréquent aujourd'hui), tu aurais quoi comme URL d'édition
par exemple ?

**Comment by Alex-D** [comment]
Là encore : SEO bonjour. Changer l'ordre des paramètres est possible si on a des query strings, donc deux URLs (ou plus) pour le même contenu s'il y a plus d'un paramètre possible. Qui dit de multiples URLs pour un même contenu dit "duplicate content" c'est à dire que les moteurs de recherche vont désaprouver ce contenu car il ne sait pas quelle URL est la bonne.

Aussi, je suis partisant des URLs structurées, c'est à dire avec des "slugs" même si on met des IDs, il faut les mettre à la sauce /idForum-slugmachin/idTopic/trucbidul/actionid/param

Aussi, j'aimerais que cette refacto attende le merge plus que rapprochant de la branche d'intégration, car les changements dans les templates sont conséquents, et j'aimerais ne pas avoir à refaire la même chose que ce que vous auriez fait dans la branche principal (inutile de faire le boulot deux fois).

**Comment by SpaceFox** [comment]
C'est bien la première fois que j'entends dire que l'ordre dans les query
strings fait considérer que c'est 2 URLs différentes.
Tu as une source pour ça ?

Le problème des URLs structurées à rallonge, c'est qu'on a vite fait de
passer 50 paramètres redondants d'un pooint de vue technique.

**Comment by Alex-D** [comment]
http://moz.com/community/q/query-string-in-url-duplicate-content

Mots clés : "query string duplicate content" et tu trouveras ton bonheur si cette source ne te convient pas.

Chaque URL a son nombre de paramètres définis non ? Déjà en corrigeant les CSRF ça va dégager un bon nombre d'URLs à rallonge car tout passera en POST pour moi... peut-être que je me trompe, mais je vois ça comme ça.

**Comment by geoffreyc** [comment]
Je comprend pas le problème , si touts nos liens internes sont bien fait,
yaura pas de probleme d'ordre des query strings.

Et puis de toutes façons, AFAIK, ya pas de pénalité niveau Google pour du
duplicate content sur un même domaine, si ce n'est que Google nindex qu'une
des pages

**Comment by artragis** [comment]
Je pense que le query string c'est quand même assez étrange quand on a du slug à côté.
Pour ce qui est du SEO, les deux ont la même utilité, mais pour la navigation par historique le slug est à peu près 100 fois plus pratique, j'aurai donc tendance à le favoriser.

**Comment by firm1** [comment]
> - Parfois on a des IDs

Je ne trouve pas ça mauvais si les urls ne sont pas à destination des utilisateurs

> - Parfois on a des slugs

Je trouve ça pas mauvais quand les slug font déjà des kilomètres genre `/forums/nom_de_categorie/nom_du_forum/` et que les slug sont vérouillé en unique.

> - Parfois on a les deux

Je trouve ça aussi cool quand la page est destinée aux utilisateur et que le slug n'est pas unique.

> - Parfois on a des paramètres de type "query string" (qui en général sont récupérés en GET sans aucun contrôle).

Là c'est plus problématique et on rejoint plutôt l'issue [suivante](https://github.com/Taluu/ZesteDeSavoir/issues/497). Etant donné que ces urls n'interesse pas le SEO, on peut en faire ce qu'on veut.

Donc en gros, pour moi c'est pas si l'anarchie que ça, si on sait pourquoi on a tel ou tel url.

**Comment by Alex-D** [comment]
Les query strings ne me dérangent pas pour tout ce qui est formulaire accessible uniquement aux membres, et aux choses du style "page=X" ou encore des filtres.

Par contre, je reste persuadé qu'il y a des URLs publiques qui ont une forme étrangement non cohérente.

Je pourrais les remonter quand je retrouverais mon PC de dev ce soir si besoin.

**Comment by SpaceFox** [comment]
> Donc en gros, pour moi c'est pas si l'anarchie que ça, si on sait
> pourquoi on a tel ou tel url.

En tous cas j'ai toujours pas compris dans quel cas on a tel ou tel choix
d'URL.

**Comment by Eskimon** [comment]
On en est où sur cette issue maintenant que le front a été intégré ?  
S'il y a des choses simples à faire je peux m'y coller...

**Comment by Alex-D** [comment]
Là je pense que c'est chaud et que ça peut créer des bugs, faut y aller avec précaution.

**Comment by SpaceFox** [comment]
Néanmoins, si c'est à faire, c'est à faire **avant** la sortie publique... parce que les changements d'URLs aussi massifs une fois le site en prod, c'est une catastrophe niveau SEO (ou alors une catastrophe à gérer).

**Comment by Alex-D** [comment]
Ah oui clairement il faut le faire là dans les 10 jours.

**Comment by ArnaudCalmettes** [comment]
C'est à l'heure actuelle la dernière issue bloquante pour la bêta publique qui ne soit pas encore en cours de traitement. Est-ce qu'on sait quoi faire ? Si oui, qui prend ?

**Comment by vhf** [comment]
En résumé, que fait-on ? On passe tout en /:id/:slug/ ?

**Comment by Alex-D** [comment]
Ca dépend où, par exemple les pages ou les filtres, ça me semble compliqué de les passer comme ça. Mais tout le reste oui.

**Comment by ArnaudCalmettes** [comment]
Bon. Étant donné que : 
- nous sommes à la bourre pour clôturer la bêta privée,
- aucun visiteur ne nous a fait remarquer ce problème,
- et surtout que cette issue risque de demander un travail à la fois considérable et d'autant plus dangereux lorsqu'il est réalisé dans l'urgence,

Je passe cette issue en V2+. On va avoir besoin de temps pour tout faire proprement et sans précipitation.

En ce qui concerne les problèmes de SEO que ça implique, il me semblent relatifs étant donné, d'une part, que nos premiers visiteurs vont surtout venir d'OC, de la communication sur les réseaux sociaux et du bouche à oreilles, et d'autre part que nous n'avons aucun quota d'affichage de pub ou autres joyeusetés à nous imposer.

**Comment by Situphen** [comment]
Note : sera normalement réglé par [la ZEP 26](https://zestedesavoir.com/forums/sujet/2558/zep-26-rendre-les-urls-plus-coherentes/)

**Comment by GerardPaligot** [comment]
On a une ZEP de créer pour cette issue. Est-ce pertinent de la garder ?

**Comment by SpaceFox** [comment]
Non.
