### ISSUE TITLE
La vérification du pseudo ne fonctionne pas

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5563]
D'après le code de la fonction `validate_zds_username` du fichier `zds/member/validators.py`, le pseudo doit passer quelques tests pour pouvoir être accepté. Ces tests ne fonctionnent actuellement pas ! J'ai été en mesure de créer des pseudos avec des espaces avant et après sans soucis.

**Comment by firm1** [comment]
Je m'en occupe !
