### ISSUE TITLE
[EasyMDE] Le mode side-by-side de l'éditeur wysiwyg déclenche le plein écran

### ISSUE THREAD

**Issue by entwanne** [zestedesavoir/zds-site#5566]
Salut,

Je testais l'éditeur _wysiwyg_ sur la bêta et j'ai rencontré un comportement étrange avec le bouton « aperçu sur le côté ».

Lorsque je clique, je vois bien la zone d'aperçu apparaître brièvement à côté, mais juste après cela l'éditeur passe en plein écran. L'aperçu est toujours visible.

Si j'essaie à ce moment là de sortir du mode plein écran, cela fonctionne mais me désactive l'aperçu _side-by-side_.
En revanche si je demande juste à masquer l'aperçu _side-by-side_, l'éditeur reste en mode plein écran.

Aussi, je me demandais si ces boutons d'aperçu ne faisaient pas doublon avec celui déjà présent sous la zone d'édition. Est-il prévu à terme de le faire disparaître ?

**Comment by firm1** [comment]
Bonjour,

Merci pour le retour.

Ce ticket est un peu complexe dans le sens ou, on se base sur un outil (easy-mde) et le bug est dans cet outil là. Il est impossible de faire du side-by-side si on est pas en plein écran.

> Aussi, je me demandais si ces boutons d'aperçu ne faisaient pas doublon avec celui déjà présent sous la zone d'édition. Est-il prévu à terme de le faire disparaître ?

Le plan c'est de faire disparaître ce bouton définitivement par la suite.

**Comment by A-312** [comment]
La fonctionnalité a été ajouté à easymde : https://github.com/Ionaru/easy-markdown-editor/pull/196
