### ISSUE TITLE
(EasyMDE) L'éditeur n'efface pas le message après l'envoi du formulaire

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5589]
- Écrire un message
- Envoyer le message
- Attendre 15 minutes (la disparition de l'antispam)
- S'apercevoir que celui-ci est encore présent d'en l'éditeur
- (Alternative) Regarder le `localStorage` directement

**Comment by Situphen** [comment]
Je pense savoir d'où ça vient. EasyMDE sauvegarde le contenu de l'éditeur toutes les x secondes. Il supprime bien la sauvegarde du message lors de l'envoi du formulaire, mais réactive la sauvegarde au bout de x secondes si jamais le formulaire ne s'est pas envoyé. Le problème est que ce "x secondes" est le même dans les deux cas.

Pour ZDS, la valeur de "x" (`autosave.delay`) a été mise à 1 seconde ce qui permet de sauvegarder régulièrement le contenu de l'éditeur. Sauf que l'envoi du formulaire dure plus longtemps que ça donc EasyMDE considère que celui-ci ne s'est pas bien envoyé.

**Comment by Situphen** [comment]
C'est difficile de corriger ça de notre côté donc j'ai ouvert une PR du côté de EasyMDE : https://github.com/Ionaru/easy-markdown-editor/pull/139

**Comment by A-312** [comment]
On en est où maintenant que le fix a été appliqué ?

**Comment by Situphen** [comment]
> On en est où maintenant que le fix a été appliqué ?

J'attends que le responsable de EasyMDE publie une nouvelle version avec mon correctif. J'imagine qu'il préfère attendre les correctifs de firm1, ce qui ne devrait pas tarder !

**Comment by A-312** [comment]
Ca corrigera aussi le bug de l'édition ? (Car sans `localstorage.clear()`, c'est difficile d'éditer un message, on se retrouve avec un autre texte)

**Comment by Situphen** [comment]
> Ca corrigera aussi le bug de l'édition ?

Si tu parles du bug de l'édition de message sur le forum, non ce n'est pas corrigé par mon correctif. C'est dû à l'URL `/forums/message/editer/?message=214594` qui est enregistré dans le localStorage comme `/forums/message/editer/` (sans les paramètres GET) ce qui est problématique. Il faudrait créer un autre ticket. Une solution serait de prendre en compte ces paramètres GET (sauf `page=`).
