### ISSUE TITLE
Impossible de créer un nouveau sujet

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5594]
Impossible de créer un nouveau sujet

> Je crois par contre que je n'arrive plus à créer de sujet. Il ne se passe absolument rien quand je clique sur `Envoyer`. :(

[informaticienzero sur le forum](https://zestedesavoir.com/forums/sujet/697/lopen-bar-a-smoothies/?page=184#p214107)

**Comment by A-312** [comment]
An invalid form control with name='text' is not focusable.

**Comment by Situphen** [comment]
Ah bah tiens, Firefox n'affiche pas cette erreur !

Le formulaire ne s'envoie pas sur les pages où le `textarea` à l'attribut `required` car celui-ci est caché avec `display: none;`
