### ISSUE TITLE
[EasyMDE] La correction orthographique du navigateur ne fonctionne plus

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5595]
Avec le nouvel éditeur il n'y a plus de spellchecker. :/ Mais apparemment on pourrait en rajouter un en JS avec [Typo.js](https://github.com/cfinke/Typo.js), de ce que j'ai lu il utilise les standards de dictionnaires populaires (on peut donc trouver un dico fr). 

https://stackoverflow.com/questions/12343922/codemirror-with-spell-checker

**Comment by A-312** [comment]
Quitte à utiliser un outil, on pourrait peut-être cherche plus loin et même un correcteur grammatical, comme languagetool :
 - https://grammalecte.net/thread.php?prj=fr&t=41
 - https://languagetool.org/fr/

**Comment by arobase-che** [comment]
Je pense qu'on ne devrait pas rajouter un correcteur grammatical ça rajoute de la lourdeur aux pages en plus d'imposer le notre à celui de l'utilisateur.

Je pense qu'on devrait juste corriger l'intégration des outils qui fonctionnaient déjà.

**Comment by marin-m** [comment]
Salut,

Je vois un `spellchecker: false` ici : https://github.com/zestedesavoir/zds-site/blob/v29c-plume/assets/js/editor.js#L398

C'est peut-être ça ?

Bonne soirée,

**Comment by firm1** [comment]
Ce n'est malheuresement pas ça. Le spellchecker de easymde est un truc custom qui n'a rien a voir avec le spellchecker du natif (navigateur). C'est pour cette raison (et parce qu'il ne supporte pas le français aussi) que le spellchecker de easymde a été désactivé.

J'ai vu des zones codemirror qui permettent de laisser le spellchecker du browser, mais faut voir comment l'activer ici.

**Comment by A-312** [comment]
> J'ai vu des zones codemirror qui permettent de laisser le spellchecker du browser, mais faut voir comment l'activer ici.
J'ai vu un hack avec l'attribut content-editable mais je ne sais pas si c'est fiable

**Comment by A-312** [comment]
> Ce n'est malheuresement pas ça. Le spellchecker de easymde est un truc custom qui n'a rien a voir avec le spellchecker du natif (navigateur). C'est pour cette raison (et parce qu'il ne supporte pas le français aussi) que le spellchecker de easymde a été désactivé.
> 
> J'ai vu des zones codemirror qui permettent de laisser le spellchecker du browser, mais faut voir comment l'activer ici.

Si on remplace le fichier .dico par l'équivalent FR peut-être que ça devrait suffir, il me semple qu'easymde utilise ce packet quand spellchecker: true : https://github.com/sparksuite/codemirror-spell-checker ?

**Comment by A-312** [comment]
https://github.com/sparksuite/codemirror-spell-checker/pull/39

**Comment by firm1** [comment]
Pour information, lorsque la PR suivante (https://github.com/Ionaru/easy-markdown-editor/pull/143) sera mergée sur upstream, il suffira d'apperler l'éditeur avec les nouveaux paramètres:

```bash
var easyMDE = new EasyMDE({
...
inputStyle: "contenteditable",
nativeSpellcheck: "true"
});
```

**Comment by A-312** [comment]
C'était aussi simple pour ajouter le spellchecker ? 😳

**Comment by arobase-che** [comment]
Encore une fois. Ce n'est pas une bonne solution puisque ça casse Grammalect.

**Comment by A-312** [comment]
> Encore une fois. Ce n'est pas une bonne solution puisque ça casse Grammalect.

Même avec le fix du spellchecker natif ?
