### ISSUE TITLE
Tutorials need member's comments

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#56]
Aujourd'hui les tutoriels sont crées et publiés, mais on ne peut pas encore ajoutés des commentaires.

L'idée est de faire des commentaires par :
- Tutoriel
- Partie
- Chapitre
- Extrait

J'aimerai à moyen terme qu'on puisse faire des commentaires par ligne, comme c'est fait actuellement sur github par exemple. Les commentaires par lignes, seront détruits à chaque mis à jour d'une version du tuto.

**Comment by dreherch** [comment]
Quel est le but ? avoir des commentaires par chapitre, c'est pratique pour faire un retour un peu ciblé à l'auteur, mais pourquoi ligne par ligne ? Si c'est pour corriger des erreurs, on aura le système d'alertes/pull requests pour ça. Ca permet d'ailleurs de garder les alertes lors de la mise à jour.

**Comment by firm1** [comment]
Ces commentaires par lignes, sont en fait une extension des alertes. les avantages sont les suivants :
- Faire une alerte sur une ligne précises est déjà plus précis que sur un extrait tout entier
- En lisant le tuto, un utilisateur peut voir qu'il y'a un commentaire sur une ligne d'un tuto, et décide en cliquant sur un bouton de l'afficher et de lire des remarques qui ont été émises par un autre lecteur.
- Si une alerte a déjà été faite sur un point, plus la peine de la répéter.
- La beta-test est clairement plus organisée, puisque on fait des commentaires aussi sur des points précis.

**Comment by Coy0te** [comment]
L'affichage des commentaires des autres lecteurs dans la zone beta, c'est pas mal. Par contre, ça l'est pas du tout sur la version en ligne d'un cours, ça supposerait qu'on fasse confiance aux lecteurs pour ne pas écrire de la merde, ou alors qu'on pré-valide leurs commentaires.

**Comment by firm1** [comment]
> Par contre, ça l'est pas du tout sur la version en ligne d'un cours, ça supposerait qu'on fasse confiance aux lecteurs pour ne pas écrire de la merde, ou alors qu'on pré-valide leurs commentaires.

Je pensais à ne pas les afficher par défaut. En gros tu peux lire ton tuto, sans voir les commentaires. Mais avoir un petit bouton à gauche discret qui est présent uniquement à coté des lignes qui con été commentées et qui permet de lire l'intégralité des commentaires sur cette ligne. Après, tous ces commentaires doivent être modérables.

Après, bon ça reste une idée pour le moyen terme.

**Comment by firm1** [comment]
Je considère aussi cette issue comme terminée. Le commentaires pour le tuto sont suffisants.
