### ISSUE TITLE
Erreur visualisation profil ?

### ISSUE THREAD

**Issue by Ge0** [zestedesavoir/zds-site#560]
Je testais le site par hasard et, tombant sur mon profil : 

http://zestedesavoir.com/membres/voir/Ge0

Si vous n'obtenez pas l'erreur, j'ai ça : 

AttributeError at /membres/voir/Ge0

'WSGIRequest' object has no attribute 'user'

**Comment by SpaceFox** [comment]
D'où vient l'URL ?

L'adresse correcte est maintenant :
http://zestedesavoir.com/membres/voir/Ge0/

Si tu l'as tapée à la main, c'est normal que ça ne fonctionne pas.
Si tu as cliqué sur un lien, c'est qu'il reste une URL mal gérée quelque
part et c'est à corriger.

Cela dit, on a un vrai problème quand même : j'ai l'impression qu'on a un
middleware ou quelque chose qui nous empêche d'avoir les erreurs 404 qu'on
devrait avoir sur ces URLs.

**Comment by Alex-D** [comment]
Encore une fois, ça serait vraiment cool d'avoir une redirection 301 de l'un vers l'autre :/

**Comment by Coy0te** [comment]
C'est l'URL qui est sur le pseudo/logo d'un membre dans un post de forum, il lui manque le slash de fin. Pareil dans la liste des sujets et des forums, sur le nom du dernier posteur. Même problème dans les MP.

**Comment by SpaceFox** [comment]
> C'est l'URL qui est sur le pseudo d'un membre dans un post de forum, il
> lui manque le slash de fin.

Ha oui, je regarderai ça si personne d'autre ne l'a fait avant ce soir.

> Encore une fois, ça serait vraiment cool d'avoir une redirection 301 de
> l'un vers l'autre :/

Vu qu'aux derniers essais, l'option Django pour gérer ça automatiquement se
contentait de foutre la merde, j'aimerais bien une meilleure raison que
"parfois je rentre des URLs à la main" pour me convaincre de me battre avec
le système.

**Comment by geoffreyc** [comment]
Dans nginx :
rewrite ^(.*[^/])$ $1/ permanent;

Ca devrait suffire a rediriger constament toutes URL sans "/" vers sont
équivalent avec "/". J'essais ca maintenant.

2014-05-19 7:16 GMT+01:00 SpaceFox notifications@github.com:

> > C'est l'URL qui est sur le pseudo d'un membre dans un post de forum, il
> > lui manque le slash de fin.
> 
> Ha oui, je regarderai ça si personne d'autre ne l'a fait avant ce soir.
> 
> > Encore une fois, ça serait vraiment cool d'avoir une redirection 301 de
> > l'un vers l'autre :/
> 
> Vu qu'aux derniers essais, l'option Django pour gérer ça automatiquement
> se
> contentait de foutre la merde, j'aimerais bien une meilleure raison que
> "parfois je rentre des URLs à la main" pour me convaincre de me battre
> avec
> le système.
>

**Comment by geoffreyc** [comment]
Ca a l'air de marcher, je laisse le temps de tester ca plus profondément.

2014-05-19 9:01 GMT+01:00 geoffrey compagnon speedking34@gmail.com:

> Dans nginx :
> rewrite ^(.*[^/])$ $1/ permanent;
> 
> Ca devrait suffire a rediriger constament toutes URL sans "/" vers sont
> équivalent avec "/". J'essais ca maintenant.
> 
> 2014-05-19 7:16 GMT+01:00 SpaceFox notifications@github.com:
> 
> > C'est l'URL qui est sur le pseudo d'un membre dans un post de forum, il
> > lui manque le slash de fin.
> > 
> > Ha oui, je regarderai ça si personne d'autre ne l'a fait avant ce soir.
> > 
> > > Encore une fois, ça serait vraiment cool d'avoir une redirection 301 de
> > > l'un vers l'autre :/
> > 
> > Vu qu'aux derniers essais, l'option Django pour gérer ça automatiquement
> > se
> > contentait de foutre la merde, j'aimerais bien une meilleure raison que
> > "parfois je rentre des URLs à la main" pour me convaincre de me battre
> > avec
> > le système.
> >

**Comment by geoffreyc** [comment]
(FYI, C'est redirection 301)

2014-05-19 9:05 GMT+01:00 geoffrey compagnon speedking34@gmail.com:

> Ca a l'air de marcher, je laisse le temps de tester ca plus profondément.
> 
> 2014-05-19 9:01 GMT+01:00 geoffrey compagnon speedking34@gmail.com:
> 
> Dans nginx :
> 
> > rewrite ^(.*[^/])$ $1/ permanent;
> > 
> > Ca devrait suffire a rediriger constament toutes URL sans "/" vers sont
> > équivalent avec "/". J'essais ca maintenant.
> > 
> > 2014-05-19 7:16 GMT+01:00 SpaceFox notifications@github.com:
> > 
> > > C'est l'URL qui est sur le pseudo d'un membre dans un post de forum, il
> > > lui manque le slash de fin.
> > > 
> > > Ha oui, je regarderai ça si personne d'autre ne l'a fait avant ce soir.
> > > 
> > > > Encore une fois, ça serait vraiment cool d'avoir une redirection 301
> > > > de
> > > > l'un vers l'autre :/
> > > 
> > > Vu qu'aux derniers essais, l'option Django pour gérer ça automatiquement
> > > se
> > > contentait de foutre la merde, j'aimerais bien une meilleure raison que
> > > "parfois je rentre des URLs à la main" pour me convaincre de me battre
> > > avec
> > > le système.
> > >

**Comment by Alex-D** [comment]
Parfait !

C'est vrai que fait par ngix ça marche aussi :)

**Comment by SpaceFox** [comment]
Cela dit, j'aime bien avoir des justifications des règles potentiellement
casse-gueule qu'on met en place :)

**Comment by Alex-D** [comment]
Potentiellement casse-gueule ? Ca peut l'être en effet si ça s'applique à tous les chemins y-compris les ressources... mais si ce qui ne doit pas être touché est exclu, il ne devrait y avoir aucun problème.

La justification est dans le lien justifiant l'usage des slugs. C'est très conseillé. Des frameworks comme ExpressJS le font par défaut. Aussi, si jamais il y a un oubli d'un "/" dans le code, au moins ça ne plante pas. Je sens bien que tu vas me dire que l'arguments "les autres le font donc faisons-le aussi" n'est pas recevable, mais j'ai envie de dire, si tu cherches des explications complètes, Google t'aideras très très probablement.

**Comment by geoffreyc** [comment]
En soit ya rien de casse gueule. Si on garde la convention de toujours
avoir des URLs se finissant en "/", yaura aucuns soucis a rediriger les
URLs sans. Sur le coup je suis d'accord avec Alex quand il dit par exemple
que si quelqu'un tape l'adresse a la main et oublie le "/", c'est plus
agréable d’être redirigé sur la bonne page que sur une 404.

Et puis avec nos url la on simule une structure en dossier, et qu'en
general, "cd /home/me" et "cd /home/me/" ça ramène toujours au meme endroit.

2014-05-19 9:31 GMT+01:00 SpaceFox notifications@github.com:

**Comment by cgabard** [comment]
Perso ça ne me choque pas a condition que ce comportement est bien documenté

**Comment by SpaceFox** [comment]
> Perso ça ne me choque pas a condition que ce comportement est bien
> documenté

Ça ne me choque pas non plus si c'est justifié et documenté.

> Je sens bien que tu vas me dire que l'arguments "les autres le font donc
> faisons-le aussi" n'est pas recevable, mais j'ai envie de dire, si tu
> cherches des explications complètes, Google t'aideras très très
> probablement.

En effet, cet argument n'est pas recevable. "les autres" me disent qu'il
faut absolument utiliser PostgreSQL par exemple, parce que c'est mieux et
plus rapide que MySQL.

Quant aux explications plus complètes, une recherche rapide ne m'a pas
permis d'en trouver, j'ai seulement vu des "ça se fait".

> Aussi, si jamais il y a un oubli d'un "/" dans le code, au moins ça ne
> plante pas.

Ça, c'est peut-être le pire argument qui existe. Mettre un truc "parce que
comme ça si y'a un bug ça marche quand même", désolé, c'est juste
complètement irrecevable. C'est même un argument qui me pousse à mettre ce
genre de règle dans le serveur HTTP et pas dans Django : comme ça les devs
n'ont pas cette règle et y'a une chance qu'on évite ce genre de bugs.

Cela dit, OK pour mettre la redirection automatique, ne serait-ce que pour
conserver un principe de moindre surprise (l'utilisateur s'attends à ce que
zds/bidule renvoie vers zds/bidule/, de part l'arbo en dossiers).

2014-05-19 10:38 GMT+02:00 Christophe Gabard notifications@github.com:

**Comment by Alex-D** [comment]
Pour le coup du "ça plante pas en cas d'oubli" je parlais en prod oui, pas en dev... en effet en dev c'est mieux d'avoir un truc clean, mais dans le doute, au moins en prod ça fonctionne.

Ce qui est bien, c'est que tu es d'accord avec l'argument de @geoffreyc qui est strictement le même que le mien (à savoir : on tape l'url, ça redirige car c'est logique en soi : un slash à la fin ne doit pas faire planter le système) mais là tu es d'accord.

Personnellement, je trouve ça assez long de devoir justifier longuement et donner des exemples pour justifier la mise en place d'une chose qui semble relativement évidente (là je parle de façon générale, ça fait plusieurs points où il faut débattre pour délibérer que oui, il faut bien le faire).

**Comment by SpaceFox** [comment]
En fait, c'est une question de contexte (principalement) et de présentation
(un peu).

Quand tu l'as présenté, on avait essayé avec @firm1 un truc Django\* qui
pétait toute l'application*, et ta justification était "Parfois je vais
taper des URLs + d'autres raisons que je ne donne pas".
Donc, forcément, on ne s'est pas pris la tête et on ne l'a pas fait.

@geoffreyc arrive avec _une solution qui marche_ et une justification qui
est "Normalement une structure comme la nôtre ça marche comme ça". Du coup
j'ai envie de dire, puisque ça marche, laissons-le.
Mais je n'aurai aucun scrupule à le dégager si je constate des problèmes.

**Comment by firm1** [comment]
Fix'd
