### ISSUE TITLE
[EasyMDE] La zone de texte passe devant le menu mavigation en mode "aperçu à côté"

### ISSUE THREAD

**Issue by arobase-che** [zestedesavoir/zds-site#5603]
Bonjour,

# étapes pour reproduire

- Aller sur le forum
- Éditer un message
- Utiliser le nouvel éditer et passer en mode "aperçu à côté"
- déplier le menu des forums

# comportement observé

La zone de texte passe devant le menu navigation. Le rendant inutilisable.

![2020-01-21-053858_1920x1080_scrot](https://user-images.githubusercontent.com/2202307/72775950-98dd3a80-3c10-11ea-813a-026a9709be6b.png)

# Comportement désiré

Le menu passe bien au dessus de la zone de texte et de l'aperçu

**Comment by artragis** [comment]
c'est chaud car le z-index de codemirror est de 1, alors que celui du menu est de 100

**Comment by A-312** [comment]
Rajouter `z-index` à `0` pour son parent suffit

```js
.main-container {
  z-index:0;
}
```

ou pour `#content` mais `.main-container` serait plus approprié pour dire au navigateur : tu es moins propriétaires que ton éléments frères `.header-container`.

![image](https://user-images.githubusercontent.com/18501150/72829774-b2699b00-3c7f-11ea-82d1-107bcfb10460.png)

**Comment by artragis** [comment]
ça pète la vue plein écran de faire ça.

**Comment by A-312** [comment]
> ça pète la vue plein écran de faire ça.

Il faut donc ajouter une class au body quand on est en fullscreen, je ne vois pas d'autre solution pour avoir l'un ou l'autre. :/ ~~(à moins de faire un hack avec position:relative/absolute; mais c'est moche)~~

**Comment by artragis** [comment]
on peut probablement faire autrement.

**Comment by A-312** [comment]
Le menu doit être au dessus du textarea mais quand on a un full screen, le menu doit etre en dessous.

Je ne vois pas comment tu veux faire sans ajout de class css. 😕

**Comment by firm1** [comment]
Il me semble que ce bug est a présent corrigé.

Quelqu'un peut vérifier et fermer le ticket ?

**Comment by artragis** [comment]
Le bug ne concerne plus que le mode "aperçu à côté"

**Comment by artragis** [comment]
FIxé en v30
