### ISSUE TITLE
Nombre d'abonné(s) sur la page de profile

### ISSUE THREAD

**Issue by arobase-che** [zestedesavoir/zds-site#5605]
Bonjour \o,

Le nombre d'abonné sur la page de profile s'affiche bizarrement.

![2020-01-21-042947_1920x1080_scrot](https://user-images.githubusercontent.com/2202307/72777494-1c4d5a80-3c16-11ea-90e3-238e1b5de25a.png)

______

Une erreur au niveau du template ?

https://github.com/zestedesavoir/zds-site/blob/ca20c46a215187c49715954920bc60ad2ce1af65/templates/member/profile.html#L142-L146

Devrait être : 
~~~html
<span class="bold">{{ subscriber_count }}</span> abonné{{ plural }}
~~~

Non ?

**Comment by AmauryCarrade** [comment]
Non c'est un peu plus compliqué que ça ^^

Le bout de code que tu cites fonctionne très bien, c'est la bonne façon de traduire une chaîne acceptant un pluriel. Le soucis c'est que cette chaîne est dans un `captureas`, qui est utilisé dans le texte de base mais aussi dans l'attribut `aria-label`. La présence de HTML dans cet attribut casse l'affichage (car ça ferme la balise trop tôt). Ça se voit bien là : 

```html
<div class="sub-button static-button statistic" id="subscriber_count_combined" aria-label="<span class=" bold"="">4 abonnés"&gt;
    4
</div>
```

C'est probablement lié à la mise en gras des nombres de la page d'accueil.
Je vais envoyer une PR pour corriger ça, c'est assez simple.

**Comment by arobase-che** [comment]
> Non c'est un peu plus compliqué que ça ^^
> 
> Le bout de code que tu cites fonctionne très bien, c'est la bonne façon de traduire une chaîne acceptant un pluriel. Le soucis c'est que cette chaîne est dans un `captureas`, qui est utilisé dans le texte de base mais aussi dans l'attribut `aria-label`. La présence de HTML dans cet attribut casse l'affichage (car ça ferme la balise trop tôt). Ça se voit bien là : 

Je comprend bien. Il faudrait que j'étudie ça un peu.

Merci pour ton retour !
