### ISSUE TITLE
[EasyMDE] Problème de rémanance et auto-save

### ISSUE THREAD

**Issue by p1-mmr** [zestedesavoir/zds-site#5607]
Bonjour,

Comme demandé sur Discord, je duplique l'information ici :

Concernant les problèmes de rémanence, je ne sais pas si vous avez déjà noté, mais il y a aussi le cas où vous laissez traîner plusieurs onglets d'édition ouverts pour même contenu, mais avec des versions différentes du texte.

Lorsque ça survient, l'auto-save des anciens onglets continue à écraser le contenu des nouveaux (qui est du coup plus ancien que celui de la version en ligne).

En ce qui me concerne, je vais laisser ouverts moins d'onglets, mais je pense que pour résoudre correctement ça, il faudra à minima associer la fonction d'auto-save à un hash de la version en ligne de l'article, par exemple (pour savoir dans quel slot de localStorage, si ça repose sur ça, mettre la copie).

Un mécanisme de synchronisation des onglets, s'il n'y en a pas déjà, pour éviter que les onglets ne se battent entre eux, serait intéressant aussi.

Merci pour les upgrades en tous cas.

Bonne journée,

**Comment by A-312** [comment]
1) Il faudrait détecter quel onglet est actif/à le focus
2) Plusieurs solutions : 
      - Afficher un message "édition en cours dans un autre onglet" ;
        ou
      - Actualiser code mirror automatiquement en fonction de ce que l'autre onglet fait ? (<-- Est ce simple ?)

**Comment by marin-m** [comment]
Salut,

Je vois une ligne `uniqueId: window.location.pathname + "@" + this.getAttribute("name")` ici : https://github.com/zestedesavoir/zds-site/blob/v29c-plume/assets/js/editor.js#L378

Typiquement, il va falloir seeder ça avec les bons éléments d'information (les cas échéants : dernier sujet créé, ID du message en cas de modification, dernière modification du message, dernière modification de section ou chapitre du tutoriel, etc). Ou bien circonscrire l'URL à un chargement de page individuel (s'il faut vraiment mimer le comportement natif du navigateur, et s'il n'est pas possible de le reproduire seul à l'aide de la rémanence dans les `<textarea>`).

Bonne soirée,

**Comment by A-312** [comment]
> Salut,
> 
> Je vois une ligne `uniqueId: window.location.pathname + "@" + this.getAttribute("name")` ici : https://github.com/zestedesavoir/zds-site/blob/v29c-plume/assets/js/editor.js#L378

Le `this` retourne peut être le mauvais objet

**Comment by A-312** [comment]
@Situphen 
![image](https://user-images.githubusercontent.com/18501150/73142756-abcd9000-4092-11ea-84b9-8bc019cb69d3.png)

Il faut utiliser `href` au lieu de `pathname` ;)

(Message en réponse à: https://github.com/zestedesavoir/zds-site/issues/5589#issuecomment-578549258 )

**Comment by Situphen** [comment]
En prenant bien soin de virer le paramètre `?page=1` :)

**Comment by A-312** [comment]
@Situphen si jamais on veut bien faire les choses pour vérifier le `page` sans utiliser de regex: https://zestedesavoir.com/forums/sujet/11268/creation-dun-parser-de-querystring/ 😆

**Comment by A-312** [comment]
C'est vraiment souhaitable d'avoir une sauvegarde sir l'édition ? Quand je ferme l'édition, le plus souvent je veux revenir à zéro. Il faudrait rajouter un message d'alerte "attention ce n'est pas la version d'origine de la section/message mais une version autosauvegarder."

Car c'est le meilleur moyen pour faire disparaitre une partie qu'on pensait récupérer en ouvrant une nouvelle fenêtre (je parle en connaissance de cause, j'avais du rechercher mon paragraphe dans plus d'une vingtaine de changement, pour la remettre dans la section)

**Comment by Situphen** [comment]
Effectivement une solution serait de désactiver la sauvegarde automatique pour l'édition des messages (message du forum, commentaire, etc) mais ça ne résout pas le soucis pour les pages de rédaction de contenu ! :)

**Comment by arobase-che** [comment]
> C'est vraiment souhaitable d'avoir une sauvegarde sir l'édition ? Quand je ferme l'édition, le plus souvent je veux revenir à zéro. Il faudrait rajouter un message d'alerte "attention ce n'est pas la version d'origine de la section/message mais une version autosauvegarder."

Pour les messages du forum, c'est vraiment un truc utilisé.
Ça a été ajouté un jour, c'est pas pour rien.

Je pense perso que le nombre de problèmes causés par EasyMDE est trop
important et qu'il faudrait revert les changements. Revenir à l'ancien
éditeur et commencer une phase de test sur la béta.

**Comment by A-312** [comment]
> Pour les messages du forum, c'est vraiment un truc utilisé

@arobase-che il me semble que l'éditeur d'avant ne faisait pas de sauvegarde pour l'édition (ce que je critique ici)

**Comment by arobase-che** [comment]
> @arobase-che il me semble que l'éditeur d'avant ne faisait pas de sauvegarde pour l'édition (ce que je critique ici)

Tu veux dire une sauvegarde automatique quand on fait « éditer » un message ?

**Comment by A-312** [comment]
Oui d'ailleurs ça se mélange entre message...

**Comment by Situphen** [comment]
En fait je dirais qu'il y a deux soucis actuellement :

- le problème d'unicité : prendre l'URL et l'attribut `name` du `textarea` ne permet pas de représenter un unique contenu champ de texte, il faudrait prendre en compte certains paramètres GET voire POST (problème déjà présent sur l'ancien éditeur) ;
- la sauvegarde de fait toutes les secondes automatiquement et non plus lors d'une action de l'utilisateur comme c'était le cas avec l'ancien éditeur (événement `onchange` sur le `textarea`).

Il faudrait faire une PR à EasyMDE pour le 2e point. Une fois que ceci est fait, le 1e point perd en importance, même si il faudrait songer à améliorer ça quand même.

**Comment by arobase-che** [comment]
Du coup, je viens d'avoir le problème.
J'ai éditer un message. J'ai pas envoyé les modifications.

J'ai modifié une deuxième fois. J'ai envoyé les modifications.  
J'ai modifié une troisième fois c'était la première version non envoyé qui revenait.

:s Du coup, je peux pas revenir à la version en ligne.

**Comment by A-312** [comment]
@arobase-che `localstorage.clear()` ou avec les outils staffs

**Comment by A-312** [comment]
@Situphen c'est encore le cas ?

**Comment by Situphen** [comment]
Pour le deuxième point, oui. La sauvegarde se fait toutes les secondes au lieu se faire lorsque le contenu de l'éditeur est modifié. C'est chiant dans le cas où tu as deux onglets avec la même page d'ouverte, ce qui est enregistré sur la page où tu écris est écrasé par l'autre page.

**Comment by A-312** [comment]
C'est côté easymde ? En plus codemirror envoie bien des "onchange" quand quelques choses est modifié.

**Comment by Situphen** [comment]
Le mieux serait de modifier ça côté EasyMDE oui, ajouter une option pour enregistrer le contenu de l'éditeur lors des onchange et pas toutes les X secondes comme actuellement.

**Comment by firm1** [comment]
Pour suivi, voici la PR coté easymde : https://github.com/Ionaru/easy-markdown-editor/pull/182
