### ISSUE TITLE
Problèmes de liens dans le fil d'ariane

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#561]
Dans ce sujet : 

http://zestedesavoir.com/forums/sujet/204/les-regles-de-vie-sur-les-forums/

J'ai le fil d'ariane suivant : 

```
Accueil > Forums > Communauté > Discussions Générales > Les règles de vie sur les forums
```

le prob est que le nom du sujet ne mène vers rien (ça encore, pas trop genant) mais surtout que "Communauté" mène vers le sujet en cours (ce qui n'a pas de sens). Les autres ont l'air ok

**Comment by cgabard** [comment]
Idem quand je suis dans le forum DG, ce niveaux hierarchique mène sur DG

**Comment by Alex-D** [comment]
Le lien du sujet, c'est normal, surtout si t'es sur la page 1.

Par contre le lien de Communauté est fail ouaip, je regarderais ça dans ma branche aussi.

**Comment by SpaceFox** [comment]
Doublon de la #555, corrigée mais non déployée, je suppose.
Le 19 mai 2014 09:10, "Christophe Gabard" notifications@github.com a
écrit :

**Comment by cgabard** [comment]
Ha pardon
