### ISSUE TITLE
Profil : afficher un nombre pair de « derniers sujets créés » en mode desktop

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#5614]
Aujourd'hui il y a un trou. Non seulement ce serait plus joli, mais en plus en l'état ça laisse croire que la liste est incomplète et que l'utilisateur n'a créé que 5 sujets.

Et en plus ça devrait être facile, donc faire un bon « premier ticket ».

![](https://user-images.githubusercontent.com/5786268/73058178-6000c800-3e93-11ea-8ff8-f9e1a45b9cb8.png)

**Comment by artragis** [comment]
faut vérifier mais il me semble que c'est simplement un param de conf à changer du côté de l'infra. @Situphen

**Comment by Situphen** [comment]
Ce n'est pas un paramètre qu'on peut changer dans l'infra, c'est écrit en dur dans les paramètres de `zds-site` : `ZDS_APP['forum']['home_number']` dans le fichier `zds/settings/abstract_base/zds.py`.

**Comment by artragis** [comment]
on a des fichiers de conf toml non?, non?

**Comment by Situphen** [comment]
Oui, mais seulement pour certains paramètres, pas pour tous. Voir [cet exemple](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings/abstract_base/zds.py#L73) : `'fee': zds_config.get('association_fee', '20 €')`

**Comment by A-312** [comment]
~~Je me demande si on a un template en front qui utilise des settings, je crois que tout est en dur.~~ 🙁

**Comment by philippemilink** [comment]
> Oui, mais seulement pour certains paramètres, pas pour tous. Voir [cet exemple](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings/abstract_base/zds.py#L73) : `'fee': zds_config.get('association_fee', '20 €')`

Ce fichier de config toml n'existe pas pour les environnements de développement, si on ne l'a pas créé manuellement ?

**Comment by Situphen** [comment]
> Ce fichier de config toml n'existe pas pour les environnements de développement, si on ne l'a pas créé manuellement ?

Exactement, ce fichier sert seulement pour les serveurs de bêta et de production. Ça permet de mettre les bonnes clés secrètes et mots de passe (base de données, connexion via Facebook et Google, etc) ainsi que certains paramètres (comme les thèmes Noël et Halloween).
