### ISSUE TITLE
[EasyMDE] La position du curseur affichée ne s'actualise pas dans tous les cas

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5616]
Quand on clique à un endroit la position du curseur ne s’actualise pas, il faut obligatoirement écrire quelques choses pour que cette donnée s’actualise.

1. écrire un message:
    ![Positon correcte](https://user-images.githubusercontent.com/18501150/73120977-45068480-3f75-11ea-9ff5-42056006548a.png)
2. cliquer sur un autre endroit, observer que la position ne change pas:
    ![Position fausse](https://user-images.githubusercontent.com/18501150/73121005-a62e5800-3f75-11ea-9779-4eaac1cc697f.png)
3. écrire quelques choses on remarque que la position change à nouveau, la position devrait s'actualiser au click ou quand on se déplace au clavier (changement de position du curseur)

**Comment by firm1** [comment]
Pour le suivi de la PR coté upstream : https://github.com/Ionaru/easy-markdown-editor/pull/184

**Comment by A-312** [comment]
Tu ne devrais pas mettre `fix: zestedesavoir/zds-site#5616` ? Je me demande si ça marche 🤔

**Comment by firm1** [comment]
Ben ça ne sert pas a grand chose vu que ça fera l'objet d'une PR sur zds-site et c'est dans cette PR que j'indiquerai "fix blabla" pour ZdS.

**Comment by A-312** [comment]
Ca a été corrigé ? Il faut changer la version ?

**Comment by firm1** [comment]
Ça a été mergé coté upstream, il faut mettre a jour la version de easymde sur zds-site oui.
