### ISSUE TITLE
Adresse de contact

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#563]
Salut, j'ai reçu un MP qui me concerne mais n'ai aucun moyen d'y accéder vu que la bêta est fermée.

J'ai cherché un moyen de vous contacter mais n'en ai pas trouvé (IRC, mail, autre). Que faire ?

**Comment by AlexRNL** [comment]
Pareil de mon côté !

**Comment by cgabard** [comment]
Les nouveaux login/pass http sont **_/**_

**Édité par Eskimon pour cacher les logins maintenant que le dépôt est public !**

**Comment by firm1** [comment]
Ah désolé.

Les nouveaux identifiants sont :

login/password = **_/**_

**Édité par Eskimon pour cacher les logins maintenant que le dépôt est public !**

2014-05-19 13:51 GMT+02:00 Alex Barféty notifications@github.com:
