### ISSUE TITLE
Prévenir lors de l'édition d'une section qu'on édite la version sauvegardé en localStorage

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5630]
Certaine fois on ferme la page espérant récupérer la précédente sauvegarde (la version originale du message), il faudrait : 

 - Prévenir lorsqu'on édite (=> pas créer, j'ai bien dit "éditer") et qu'on a une version différente de l'originale. Cette présentation est sympa : https://codemirror.net/demo/panel.html
 - Ajouter un bouton pour dire : Je veux revenir sur la version originale

> C'est vraiment souhaitable d'avoir une sauvegarde sir l'édition ? Quand je ferme l'édition, le plus souvent je veux revenir à zéro. Il faudrait rajouter un message d'alerte "attention ce n'est pas la version d'origine de la section/message mais une version autosauvegarder."
> 
> Car c'est le meilleur moyen pour faire disparaitre une partie qu'on pensait récupérer en ouvrant une nouvelle fenêtre (je parle en connaissance de cause, j'avais du rechercher mon paragraphe dans plus d'une vingtaine de changement, pour la remettre dans la section)
> 
> _Originally posted by @A-312 in https://github.com/zestedesavoir/zds-site/issues/5607#issuecomment-580118401_

**Comment by arobase-che** [comment]
Dans la même idée.

En ouvrant deux fois la page d'édition d'un message et en confirmant une des deux modifications, sans fermer l'autre onglet. On se retrouve avec une édition incohérentes. La version affichée après une nouvelle édition est celle de l'onglet non envoyé plutôt que celle affichée.

C'est un peu confus alors je vais la refaire.

 - Ouvrir deux fois la page d'édition;
 - En modifier une (ou les deux) et envoyer une des deux versions modifiées;
 - Éditer à nouveau. C'est l'autre version qui s'affiche (celle non envoyée).


Pour le résoudre, j'ai compris finalement depuis le CS qu'il faut vider le message pour vider le localStorage.

**Comment by A-312** [comment]
@arobase-che C'est #5607

**Comment by arobase-che** [comment]
Ah zut !

Effectivement. Mais du coup corriger cette issue corrigera également #5607 non ?

**Comment by A-312** [comment]
Cette issue c'est pour informer si on a le message d'origine ou une sauvegarde et avoir un bouton pour récupérer la version d'origine

**Comment by A-312** [comment]
Et surtout ne pas perdre des données à cause d'un changement non voulu!
