### ISSUE TITLE
[EasyMDE] Citation de code barrée

### ISSUE THREAD

**Issue by arobase-che** [zestedesavoir/zds-site#5636]
Bonjour,

Citer un bloc de code le rend illisible.

Pour reproduire, il suffit d'écrire par exemple :

~~~~~md
> ~~~c
> int void() {
> 
> }
> ~~~
~~~~~

Dans l'éditeur. Le code est alors barré.

**Comment by artragis** [comment]
je pense que l'éditeur n'aime pas les code qui sont écrits avec `~~~`

**Comment by arobase-che** [comment]
En fait, je dirais plutôt que l'éditeur n'aime pas les doubles tildes.

~~~md
Ça ne *marche ~~pas bien* du tout~~.
~~~

Ce texte est en italique et barré. Or il ne devrait pas être barré.  
Si j'étais mauvaise langue, je dirais que l'éditeur n'aime pas le Markdown.

**Comment by pierre-24** [comment]
Moi, ça me fait surtout me demander si ils passent par un AST :/

**Comment by arobase-che** [comment]
Je pense que c'est la preuve que non. :/

**Comment by A-312** [comment]
https://github.com/codemirror/CodeMirror/tree/master/mode/markdown

**Comment by A-312** [comment]
https://codemirror.net/demo/simplemode.html

**Comment by firm1** [comment]
J'ai crée un ticket coté upstream (https://github.com/codemirror/CodeMirror/issues/6230) là ou se trouve le bug pour ce problème.

Quand le ticket sera fermé et releasé on pourra reprendre ce ticket.

**Comment by A-312** [comment]
Un moment ou un autre, on va devoir avoir notre propre config markdown pour supporter les blocs zmd 😕 

https://github.com/codemirror/CodeMirror/blob/99522244a9d3a7e790874d479216f9408b9c46c3/mode/markdown/markdown.js#L599-L620

**Comment by firm1** [comment]
> Un moment ou un autre, on va devoir avoir notre propre config markdown pour supporter les blocs zmd 

BIensur, mais en attendant que quelqu'un le fasse (surtout que ça va prendre du temps), si on peut corriger ce bug (puisque c'est un mauvais comportement dans le mode gfm) c'est déjà ça de pris.

**Comment by arobase-che** [comment]
4 ans maintenant, je clos, il n'y aura pas de progression immédiate. Si quelqu'un veut reprendre le sujet il peut le faire bien-sûr.
