### ISSUE TITLE
(EasyMDE) Revert EasyMDE

### ISSUE THREAD

**Issue by arobase-che** [zestedesavoir/zds-site#5637]
Bonjour,

Je propose de revert easyMDE, pour l'instant cette fonctionnalité n'est pas prête.

Elle est pratiquement inutilisable pour moi. Beaucoup trop de choses ne marchent pas.

La seule chose que je trouve intéressante est le fait que `*s*` soit en italique par exemple.

**Comment by pierre-24** [comment]
T'as déjà signalé le bug du "j'édite sur deux pages en même temps" dont tu m'as parlé hier ? :)

**Comment by arobase-che** [comment]
Non mais @A-312 à déjà signaler un problème similaire. #5630.  
Mais tu as raison, je peux en rajouter une couche.

**Comment by pierre-24** [comment]
EDIT: j'ai rien dit, je regardait la mauvaise issue pour une raison qui m'échappe.

**Comment by arobase-che** [comment]
Raison qui t'échappe: Je me suis planté en indiquant la mauvaise issue. ^^"
