### ISSUE TITLE
[Recherche] "Comment alerter les secours ?" non référencé

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5639]
Pour reproduire le bug : Chercher le titre du tuto 

![image](https://user-images.githubusercontent.com/18501150/74585793-28dc8d00-4fe1-11ea-9208-2dea4e8ffef0.png)
![image](https://user-images.githubusercontent.com/18501150/74585801-3560e580-4fe1-11ea-8e6f-3bf309c8afdd.png)

**Comment by artragis** [comment]
![image](https://user-images.githubusercontent.com/1523653/74588894-bbd8ef80-5000-11ea-8622-08912988fc18.png)
