### ISSUE TITLE
Handling IPv6

### ISSUE THREAD

**Issue by geoffreyc** [zestedesavoir/zds-site#564]
A l'heure actuel, entant que staff, on peut voir l'IP des membres. Est-ce que le system supporte les IPv6 (front et back) ? Vue que le serveur OVH est connecté v6, On risque tres certainement de tomber sur des gens qui si connecte en v6. Et si le system de sait pas enregistrer l'IP, ca serait dommage.

**Comment by SpaceFox** [comment]
Je suis connecté en double stack, et je confirme qu'aujourd'hui on ne peut
de toutes façons pas accéder à ZdS en IPv6 : la résolution DNS ne se fait
même pas :)

**Comment by geoffreyc** [comment]
Je vais régler ça tient.

2014-05-19 14:38 GMT+01:00 SpaceFox notifications@github.com:

> Je suis connecté en double stack, et je confirme qu'aujourd'hui on ne peut
> de toutes façons pas accéder à ZdS en IPv6 : la résolution DNS ne se fait
> même pas :)
>

**Comment by Alex-D** [comment]
Pour le front, pas d'inquiétudes, l'interface dédiée aux IPs n'est même pas encore faite, mais je pense à un bête tableau IP / Géolocalisation, donc il y aura largement la place.

Sinon +1 pour avoir le serveur+DNS en double stack.

Par contre, on afficherais IPv4 et IPv6 ou alors que des IPv6 (en convertissant les IPv4) ?

**Comment by SpaceFox** [comment]
Le problème c'est qu'à ma connaissance aujourd'hui il n'y a pas la place _dans
les champs de la BDD_.

> Par contre, on afficherais IPv4 et IPv6 ou alors que des IPv6 (en convertissant les IPv4) ?

Des IPv6 si le client est arrivé en IPv6, des IPv4 si le client est arrivé
en IPv4.

**Comment by geoffreyc** [comment]
> Le problème c'est qu'à ma connaissance aujourd'hui il n'y a pas la place _dans les champs de la BDD_.

C'est ce que je me demandais et ce pourquoi j'ai ouvert cette question. Il
faudrait donc voir et discuter de comment "upgrader" le model?

2014-05-19 15:51 GMT+01:00 SpaceFox notifications@github.com:

**Comment by Alex-D** [comment]
> Le problème c'est qu'à ma connaissance aujourd'hui il n'y a pas la place _dans
> les champs de la BDD_.

C'est rapide à modifier non ?

**Comment by Coy0te** [comment]
Sauf rares exceptions, y'a aucun intérêt à limiter au poil de cul près les tailles des champs _varchar-like_ dans une BDD. Prenez large !

**Comment by SpaceFox** [comment]
Surtout qu'ici les longueurs de champ sont parfaitement connues : 15
caractères pour une IPv4, 39 pour une IPv6 :)

**Comment by SpaceFox** [comment]
> Je vais régler ça tient.

Personnellement je ne résous toujours pas zestedesavoir.com en IPv6. C'est normal ?

**Comment by Alex-D** [comment]
Un reverse DNS donne :

```
zestedesavoir.com has address 176.31.187.88
zestedesavoir.com mail is handled by 1 vps41247.ovh.net.
zestedesavoir.com mail is handled by 2 redirect.ovh.net.
```

So ouep, it is narmol :)

**Comment by geoffreyc** [comment]
Ouep j'ai pas encore eu le temps, j'ai fini le boulot a 23h30 aujourd'hui
lol, gotta love heure sup'!

**Comment by SpaceFox** [comment]
Argh >_<

Pas de pb pour ma part, c'est juste que je pensais que c'était fait, d'où
mon étonnement :)

**Comment by geoffreyc** [comment]
Ca devrait etre en place (seulement le .com), tu me dirais ce que ca donne?
:)

2014-05-19 23:12 GMT+01:00 SpaceFox notifications@github.com:

> Argh >_<
> 
> Pas de pb pour ma part, c'est juste que je pensais que c'était fait, d'où
> mon étonnement :)
>

**Comment by Alex-D** [comment]
Selon cet outil : http://reverse-dns.outils-webmaster.com/index.php

L'IP est toujours IPv4

```
zestedesavoir.com has address 176.31.187.88
```

**Comment by Alex-D** [comment]
Si je le fais sur mon site par exemple, ça retourne ça :

```
alex-d.fr has address 37.187.237.201
alex-d.fr has IPv6 address 2001:41d0:52:cff::c9
```

**Comment by geoffreyc** [comment]
C'est ce putain de service DNS la la con de merde d'OVH qui marche jamais :/

Merci pour le test, je vais régler ça ... du moins essayer !

2014-05-20 14:12 GMT+01:00 DEMODE Alexandre notifications@github.com:

**Comment by geoffreyc** [comment]
On devrait être bon maintenant.

2014-05-20 14:14 GMT+01:00 geoffrey compagnon speedking34@gmail.com:

**Comment by Alex-D** [comment]
C'est good \o/

**Comment by geoffreyc** [comment]
Ils sont quand meme geniaux chez OVH, ils te proposent une jolie nouvelle
interface admin, qui marche a moitié ... Il faut se connecter a l'ancienne
interface pour que les DNS records soient pris en compte, c'est pas super
ca? :/

**Comment by firm1** [comment]
Merci geoffreyc

**Comment by geoffreyc** [comment]
Nginx écoute maintenant en tcp6 aussi.

firm1, le backend accepte les ipv6 maintenant ca y est?

**Comment by Alex-D** [comment]
Heu, chez moi je fais toutes mes manips sur le manager v6. Faut passer en mode expert pour avoir toutes les options, mais à part ça, j'ai jamais eu aucun problème.

**Comment by SpaceFox** [comment]
Je vous confirme qu'on accède parfaitement au serveur en  IPv6.

Tellement bien que je ne peux plus poster : l'application ne supporte pas l'IPv6, elle...

```
DataError at /forums/message/nouveau/
value too long for type character varying(15)
```

**Comment by geoffreyc** [comment]
haha, c'est pas très pratique

2014-05-20 18:53 GMT+01:00 SpaceFox notifications@github.com:

**Comment by SpaceFox** [comment]
Je m'occupe de corriger ça :D

PS : y'a pas moyen de dégager les putains de popup de smiley de merde qui déboulent sur Github  dès qu'on tape : ?

**Comment by Coy0te** [comment]
Tu me l'enlèves de la bouche... Je hais ce truc.

**Comment by firm1** [comment]
> Tellement bien que je ne peux plus poster : l'application ne supporte pas l'IPv6, elle...

Tu devrais donc pouvoir poster désormais.
