### ISSUE TITLE
Formulaire d'adhésion à l'asso. 

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#565]
Il y aurait besoin d'un formulaire (dans une page statique) permetant de faire une demande d'adhésion à l'asso, linké dans les autres pages parlant de l'asso, demandant les infos nom+prenom+mail+raison de la demande et le tout envoyant le formulaire sur la ML du CA de l'asso.

**Comment by Alex-D** [comment]
Je ne suis pas certain que le tag "page statique" soit approprié sachant qu'il y a un traitement derrière.

Je propose un bouton "Adhérer à ZdS" en haut à gauche de chaque page statique qui parle de l'asso.

**Comment by cgabard** [comment]
Vire le tag si ça te fais plaiz

Christophe.

2014-05-19 16:50 GMT+02:00 DEMODE Alexandre notifications@github.com:

**Comment by SpaceFox** [comment]
Je prends.

Je suppose qu'on ne l'autorise qu'aux membres ? Je ne vois pas le sens qu'il y aurait à être membre de l'asso sans être membre du site.

Si quelqu'un veut une protection anti-spam et a une idée de comment faire, je suis preneur (on pourrait stocker l'info "est membre ou a déjà fait une demande" dans le profil du membre, mais ça me semble inutile).

**Comment by firm1** [comment]
Corrigé -> mergé.

Je ferme.

**Comment by cgabard** [comment]
Je réouvre. Manifestement le serveur renvois une erreur "Une erreur est survenue" lorsque l'on essais.

Il serait pertinent d'ajouter un test au passage.

**Comment by cgabard** [comment]
Au passage un petit texte en haut du formulaire pour expliquer que pour adhérer a l'association, il fallait le remplir serait peut etre pertinent. Là ça fait un peu abrupte juste un formulaire sur la page.

**Comment by ShigeruM** [comment]
Dans la même idée, peut-être modifier le lien dans le footer de "Adhérer" à
"Adhérer à l'asso", afin de bien faire la distinction avec l'inscription au
site. Et au passage, ça rappelle qu'il y a une asso derrière le site.
Le 30 mai 2014 13:19, "Christophe Gabard" notifications@github.com a
écrit :

**Comment by firm1** [comment]
> Je réouvre. Manifestement le serveur renvois une erreur "Une erreur est survenue" lorsque l'on essais.

Pour info le bout de code à corriger est par [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/pages/views.py#L105)

Il faudrait enlever le try catch pour vérifier quel est l'erreur en vrai.

ça peut être plein de chose, le bout de code try catch est surtout pour ceux qui n'ont pas de serveur SMTP maison. Si jamais vous avez envie de tester en local avec vrai envoi de mail, il suffit de rajouter les variable suivantes (à adapter avec un vrai compte gmail) dans le settings.py

```
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'your-username@gmail.com'
EMAIL_HOST_PASSWORD = 'your-password'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
```

**Comment by cgabard** [comment]
Oui enfin a supposer que ce n'est pas notre serveur smtp qui déconne !

**Comment by firm1** [comment]
> Oui enfin a supposer que ce n'est pas notre serveur smtp qui déconne !

D'ou l'idée de proposer un test dessus. Normalement, tu peux tester qu'un email a bien été envoyé dans un test.

C'est par exemple ce qui est fait dans ce [test](https://github.com/zestedesavoir/zds-site/blob/dev/zds/mp/tests.py#L103)

**Comment by cgabard** [comment]
Vu que dernierement je ne reçois plus aucun mail du tout en provenance de
zds, comme les notifs mails de mp, je pense vraiment à un prob de smtp
serveur.

Christophe.

2014-05-30 13:32 GMT+02:00 firm1 notifications@github.com:

**Comment by geoffreyc** [comment]
Je peux confirmer que le site envoi maintenant des mails. Christophe, tu
pourrais me dire si cela a rectifier le problème du formulaire du coup?

2014-05-30 12:34 GMT+01:00 Christophe Gabard notifications@github.com:

**Comment by cgabard** [comment]
A priori le formulaire fonctionne, en tout cas je n'ai pas d'erreur.

Je fermerais si ça arrive bien sur la ML du CA

**Comment by geoffreyc** [comment]
D'ailleurs, +/- HS: Quand est-ce qu'on pourra "officiellement" faire partie
de l'assoc' ? c-a-d payer notre cotisation, etc. ?

On Fri, May 30, 2014 at 2:46 PM, Christophe Gabard <notifications@github.com

**Comment by cgabard** [comment]
Je ne sais pas. En fait pour le moment le compte bancaire n'est pas encore ouvert ce qui l’empêche. Je vais aller aux news

**Comment by cgabard** [comment]
Ok donc pour l'asso on est bloqué en attendant que notre President reçoive sa nouvelle carte d'identité :D 

Par contre pour l'issue, le mail n'est jamais arrivé sur le google group. Donc le mail semble perdu. 

Est ce que le fait que nos mails ont tendance à arriver dans les spam ne serait pas la cause ?

**Comment by firm1** [comment]
> Ok donc pour l'asso on est bloqué en attendant que notre President
> reçoive sa nouvelle carte d'identité :D

Quelle idée de voter un sans papier en tant que président.

> Par contre pour l'issue, le mail n'est jamais arrivé sur le google group.
> Donc le mail semble perdu.

Y'a pas moyen de retrouver dans les logs les traces de l'email ?

**Comment by cgabard** [comment]
J'ai récup les droits admin du groupe, j'essais de voir si ce n'est pas
dans l'user group que ça bloque

Christophe.

2014-05-30 16:03 GMT+02:00 firm1 notifications@github.com:

**Comment by cgabard** [comment]
Ok donc c'etait bien un prob de conf. En fait seul les membres du groupes pouvaient poster dedans, donc pas notre bot. Je vais l'autoriser et ça devrait régler le prob.

**Comment by cgabard** [comment]
Ok, le CA de l'asso reçoit maintenant bien les demandes, je peux fermer.

**Comment by Fumble** [comment]
Je confirme: j'ai bien reçu ton mail de test.

**Comment by cgabard** [comment]
Tu as même dut en recevoir 2 en fait :D

**Comment by Fumble** [comment]
En effet. :)
