### ISSUE TITLE
Les liens de flux rss sont incorectes

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#566]
Ils pointent vers example.com.

ex : `http://example.com/forums/sujet/206/encourager-lecriture-dune-conclusion-en-resume/?page=1#p1745` pour le dernier actuel

**Comment by Eskimon** [comment]
Chez moi ca pointe au bon endroit... Tu parles des liens qui sont dans la sidebar c'est ca ?

**Comment by cgabard** [comment]
Non les liens qui sont dans un flux. Ouvre un flux et clique sur le liens pour aller a u' des sujet cité

**Comment by Eskimon** [comment]
Bon apparemment c'est un setting en BDD du coup faut voir ce qui tourne en prod'...
https://docs.djangoproject.com/en/dev/ref/settings/#site-id
Met à la maison sur un serveur de test le setting en question est à "example.com" (ce qui donc logiquement fout la merde dans le RSS)
J'invoque donc le sysadmin ( @SpaceFox ? @firm1 ? ) pour aller vérifier les champs dans la table "django_site"...

**Comment by geoffreyc** [comment]
J'ai changer l'entrée dans la DB. C'est maintenant zestedesavoir.com. Firm1
doit aussi savoir le faire via le backend django. Ca devrait donc etre
fix'd :)

2014-05-19 18:58 GMT+01:00 Eskimon notifications@github.com:

**Comment by firm1** [comment]
It's fixed !

**Comment by cgabard** [comment]
Non désolé moi sur cette page : http://zestedesavoir.com/forums/flux/messages/rss/ j'ai toujours des liesn qui pointent vers example.com

**Comment by SpaceFox** [comment]
"Chez moi ça marche."

C'est pas un problème de cache ?

2014-05-20 15:16 GMT+02:00 Christophe Gabard notifications@github.com:

**Comment by cgabard** [comment]
Je suis persuadé avoir fait un ctrl+F5 avant, mais effectivement là ça semble Ok. Mais c'est louche

**Comment by cgabard** [comment]
Ok non je ré-ouvre : en fait en rafraichissant plusieurs fois, des fois c'est bon, des fois il y a des example.com

**Comment by Eskimon** [comment]
C'est bizarre quand meme parce qu'a part ce setting dans la BDD j'ai rien vu d'autre...
C'est possible que ce soit une histoire de cache ?

**Comment by geoffreyc** [comment]
Je pense que c'est gunicorn, je redémarre.

2014-05-20 14:31 GMT+01:00 Eskimon notifications@github.com:

**Comment by geoffreyc** [comment]
You can try again now :)

2014-05-20 14:32 GMT+01:00 geoffrey compagnon speedking34@gmail.com:

**Comment by Eskimon** [comment]
Hop hop hop petite surprise... chez moi le "nouveau message (RSS)" est bon, mais le "Nouveaux sujets (RSS)" donne des example.com... Idem pour vous ?

EDIT : Tu vas trop vite pour moi :D **Ça semble être rentré dans l'ordre chez moi...**

**Comment by geoffreyc** [comment]
J'ai le bon lien partout

2014-05-20 14:33 GMT+01:00 Eskimon notifications@github.com:

**Comment by SpaceFox** [comment]
Y'a pas un proxy dans ta boîte ?

2014-05-20 15:35 GMT+02:00 geoffreyc notifications@github.com:

**Comment by geoffreyc** [comment]
Who, me?

2014-05-20 14:36 GMT+01:00 SpaceFox notifications@github.com:

**Comment by SpaceFox** [comment]
Non, celui qui a des liens bizarres.

**Comment by geoffreyc** [comment]
Le fait que ca marchait defois et defois pas correspondrait bien au
problèmes des workers gunicorns qui se mettent pas a jour. En redémarrant
gunicorn normalement le problème est résolue?

2014-05-20 14:38 GMT+01:00 SpaceFox notifications@github.com:

> Non, celui qui a des liens bizarres.
>

**Comment by Eskimon** [comment]
Je confirme que ca marche chez moi...

**Comment by cgabard** [comment]
C'est bon aussi chez moi maintenant, merci tout le monde !
