### ISSUE TITLE
Valider un tutoriel

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#567]
Scénario :
- Connectez-vous avec le membre admin ;
- Importer un big tuto ;
- Demandez la validation du tutoriel ;
- Lancez la procédure de publication du tutoriel, une erreur est lancée :

``` console
AttributeError at /tutoriels/validation/valid/
'NoneType' object has no attribute 'iter'
Request Method: POST
Request URL:    http://localhost:8000/tutoriels/validation/valid/
Django Version: 1.6.5
Exception Type: AttributeError
Exception Value: 'NoneType' object has no attribute 'iter'
Exception Location: /Users/gerard/.virtualenvs/zds/lib/python2.7/site-packages/markdown/extensions/smartLegend.py in detect, line 41
Python Executable:  /Users/gerard/.virtualenvs/zds/bin/python
Python Version: 2.7.5
```

**Comment by firm1** [comment]
Je n'arrive pas à reproduire le bug.

Vérifie que tu as la dernière version de la branche dev à jour. Il me semble avoir poussé un fix sur la validation le samedi 17 mai.

Sinon, le problème doit être spécifique a un tuto. Et dans ce cas, faudrait donner le nom du tuto

**Comment by GerardPaligot** [comment]
J'ai tenté de publier le tutoriel J2EE de Coyote. Mon projet ZdS est à jour (clone récent du projet).

**Comment by firm1** [comment]
Tu tourne avec quelle version de release zmarkdown ?

**Comment by GerardPaligot** [comment]
Comment savoir ? La commande `pip freeze` ne me donne pas l'info.

**Comment by firm1** [comment]
par sécurité mets à jour ta version de markdown : `pip install --upgrade git+https://github.com/zestedesavoir/Python-ZMarkdown.git@2.4-zds.2.18`

**Comment by GerardPaligot** [comment]
Ca a duré un temps interminable à publier mais ça passe. Faut juste mettre à jour le fichier `requirements.txt` parce que j'avais fais un `pip install --upgrade` mais il référence la version `zds.2.17`.

**Comment by firm1** [comment]
Fixé.
