### ISSUE TITLE
SEO & Accessibilité : les images des unes et des cartouches de la page d'accueil n'ont pas de Alt

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#5674]
Lorsqu'on est sur la page d'accueil, les images des unes ainsi que des cartouches des tutos, articles et billets ont un attribut alt vide. Il faudrait mettre : 

- `illustration {{featured.title}}` pour les unes
- `logo de "{{content.public_title}}"` pour les cartouches de contenu.

**Comment by Arnaud-D** [comment]
Pour les unes, ça se passera dans `templates/featured/includes/featured_resource_item.part.html` et pour les logos de contenu, il y a un petit jeu de piste à suivre depuis `templates/home.html` pour descendre dans l'arborescence des inclusions.

**Comment by A-312** [comment]
C'est utile de mettre un attribut à ces images alors qu'elles ont un titre et une description plus claire ? Ca ne risque pas de lire deux fois la même chose au lecteur d'écran ?

Je veux dire : "Titre - Description - Illustration Titre"
