### ISSUE TITLE
Ajouter un outil de modération pour vérifier toutes les interventions d'un membre

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#5682]
Une fonctionnalité utile serait de pouvoir lister toutes les interventions d'un membre (commentaires, messages du forum...) pour vérifier si un membre ayant posté des messages suspicieux sur le forum l’a aussi fait sur des contenus.

Voir aussi [ce sujet du forum](https://zestedesavoir.com/forums/sujet/13878/geler-un-message/?page=2#p218560) avec une discussion tournant autour de ça.

**Comment by A-312** [comment]
Est couvert avec #5246 , normalement le centre des flux est destiné :
 - Nos participations ;
 - Les participations d'un membre précis ;
 - Les participations aux sujets/billets/tuto qu'on suit ;
 - Les participations/activités de l'ensemble du zds.

Il s'agirait donc d'un bouton : Être notifié en cas de changement ? 🤔

**Comment by Situphen** [comment]
> Il s'agirait donc d'un bouton : Être notifié en cas de changement ? :thinking: 

Si je comprends bien, il s'agit simplement de rajouter une page "Commentaires postés" accessible depuis le profil de chaque membre.

**Comment by A-312** [comment]
Par contre elle sera aussi invivable (= peu lisible) que "messages postés". :(

**Comment by Arnaud-D** [comment]
Je pense qu'on peut effectivement avoir une simple page avec la liste des commentaires. Si ce travail arrive avant le centre de notification, il pourra probablement être facilement réutilisé pour le centre de notification.

Si c'est imbitable, c'est pas grave, tant que ça fait son job. Souvent les spammeurs n'ont que quelques messages et commentaires, donc ça fera largement l'affaire pour le besoin de la modération.

**Comment by Situphen** [comment]
Et puis rien n'empêche d'améliorer l'affichage des messages sur ces pages-là, mais dans un autre ticket. :)

**Comment by Arnaud-D** [comment]
Essentiellement résolu par #5974.
