### ISSUE TITLE
Rendre le SPAM plus léger sur le forum

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5683]
Bonjour,

Ça fait longtemps que je n'ai pas fais de suggestion de front ! (Je suis en train de descendre toutes mes suggestions pour vider ma checklist !)

J'aimerais rendre le SPAM plus léger sur le forum : 

![](https://zestedesavoir.com/media/galleries/6585/df23b520-fda7-4cf2-b195-a305cfb45501.png)

Au lieu de :

![](https://zestedesavoir.com/media/galleries/6585/10bca984-1a9f-4c38-a146-555009d327b3.png)

Pour le staff il suffirait de rendre le lien cliquable pour afficher le message d'origine comme une balise spoiler. Qu'en pensez-vous ?

Bon vol,

A.

Sujet : https://zestedesavoir.com/forums/sujet/13699/rendre-le-spam-plus-leger-sur-le-forum/
*Envoyé depuis Zeste de Savoir*

**Comment by Situphen** [comment]
Ça améliorerait la lecture de certains sujets en effet !

Suggestions :

- "Un" au lieu de "1"
- "message de @pseudo" au lieu de simplement "message" ?

**Comment by Arnaud-D** [comment]
Il faudrait bien prendre compte les remarques sur le sujet du forum, notamment d'enrouler tous les messages masqués, indépendamment de la distinction modéré/masqué par l'auteur, et de permettre à tous de les dérouler pour avoir la liste (même s'il n'y a rien à lire).

**Comment by Arnaud-D** [comment]
Résolu par #5706.
