### ISSUE TITLE
Adapter l'affichage du forum pour les membres en lecture seule

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#5684]
Suite à une [discussion sur le forum](https://zestedesavoir.com/forums/sujet/13759/message-en-cas-de-lecture-seule/).

**Comportement observé :** en tant que membre en lecture, je peux remplir le formulaire de nouveau message, mais reçoit une 403 quand j'essaie de l'envoyer.

**Comportement souhaité :** en tant que membre en lecture seule, je ne vois pas le formulaire, mais vois un message m'indiquant que je ne peux pas poster, car je suis en lecture seule. La 403 existe toujours, mais il faut faire exprès pour la voir.

---

Pour résoudre le problème, ça se passe dans le template : `templates/misc/message_form.html` et on peut rajouter une condition avec `not user.can_write_now`.

Il faut aussi quelque chose de similaire pour les nouveaux sujets. Ça se passe ici avec une solution similaire : 

* `/templates/forum/topic/index.html`
* `templates/forum/category/forum.html`

**Comment by jeanlapostolle** [comment]
Je prends
