### ISSUE TITLE
[EasyMDE] problème de fullscreen

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5692]
La class `fullscreen` n'est pas appliqué sur la toolbar quand on essaye de mettre l'éditeur en plein écran sur le forum. 

![](https://user-images.githubusercontent.com/6664636/79016020-4572ec80-7b6e-11ea-8971-ea180bcf9783.png)

**Comment by artragis** [comment]
investiguer du côté de la fonction `EasyMDE.toggleFullScreen` et regarder ce qu'elle fait passer en fullscreen.

Le cas de reproduction réel c'est : 

- je vais sur un billet quelconque
- j'écris un truc
- je fais f5
- j'ouvre le mode fullsreen

c'est le message "La version actuelle du contenu provient d'une sauvegarde de votre navigateur. Vous pouvez revenir à la version originale (du serveur) avec CTRL+Z ou en cliquant ici."
qui génère le pb

**Comment by A-312** [comment]
Hypothèse : Le fullscreen doit être appliqué via un .prev()

**Comment by A-312** [comment]
https://github.com/Ionaru/easy-markdown-editor/blob/228fe91a7230cd2430112ca877e3c6b367f039ee/src/js/easymde.js#L312

Il faudrait PR un changement : `toolbarElements.parent`

**Comment by firm1** [comment]
On a une explication du pourquoi le bug n'est pas visible sur la prod, mais sur la beta/branche dev ?

**Comment by A-312** [comment]
> On a une explication du pourquoi le bug n'est pas visible sur la prod, mais sur la beta/branche dev ?

Tu n'as pas dû essayer avec le message qui dit "attention vous avez une sauvegarde", l'erreur est présente.

**Comment by firm1** [comment]
Je reprends la question du coup: **on a une explication du pourquoi on a pas le même comportement du fullscreen sur la prod et sur la beta** ?

### Sur la prod

Je vais là : https://zestedesavoir.com/forums/sujet/4035/exploration-craft/#p107578

J'ai ça : 

![Capture d’écran de 2020-04-15 15-29-47](https://user-images.githubusercontent.com/6066015/79342888-fb06bc80-7f2d-11ea-9bc6-a312f93b65bc.png)

Je clique sur l'icone : 
![Capture d’écran de 2020-04-15 15-30-29](https://user-images.githubusercontent.com/6066015/79342946-14a80400-7f2e-11ea-89ab-ef717358683f.png)


J'ai ça : 

![Capture d’écran de 2020-04-15 15-30-35](https://user-images.githubusercontent.com/6066015/79342954-183b8b00-7f2e-11ea-8596-919d57a87824.png)

### Sur la beta

Je vais là : https://beta.zestedesavoir.com/forums/sujet/4035/exploration-craft/#p107578

J'ai ça : 

![Capture d’écran de 2020-04-15 15-29-01](https://user-images.githubusercontent.com/6066015/79342798-e0ccde80-7f2d-11ea-884b-460b94b8aae0.png)

Je clique sur l'icone 
![Capture d’écran de 2020-04-15 15-28-01](https://user-images.githubusercontent.com/6066015/79342677-b844e480-7f2d-11ea-8812-1bcc1e975126.png)

J'ai ça : 

![Capture d’écran de 2020-04-15 15-28-28](https://user-images.githubusercontent.com/6066015/79342736-c72b9700-7f2d-11ea-80a5-1297ac13e255.png)

**Comment by A-312** [comment]
Il y a le textarea parallèle sur la bêta

**Comment by A-312** [comment]
ça aurait bien de dire que l'éditeur fonctionne correctement ici : https://github.com/Ionaru/easy-markdown-editor/pull/180 (= de faire un petit Q/A avec le script d'exemple)

**Comment by firm1** [comment]
> ça aurait bien de dire que l'éditeur fonctionne correctement ici

Je ne suis pas sur de savoir comment tester la PR de l'upstream, ça manque d'instruction de QA.

Sinon, pourquoi garder ce ticket ouvert du coup ? Le problème pointé est corrigé et donc on a plus de regression sur la branche de dev sur ce point.

**Comment by A-312** [comment]
Tu builds et tu essayes le fullscreen : https://github.com/Ionaru/easy-markdown-editor/tree/master/example
