### ISSUE TITLE
Ajouter le bouton "Signaler une faute" sur les pages de partie

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#5694]
Actuellement, on a le bouton sur le tuto complet ou sur en bas de la hiérarchie, mais pas au milieu.

Ce serait sympa de l'avoir partout, par exemple pour des fautes dans les intro/conclusions de partie.

Exemple de page : https://zestedesavoir.com/tutoriels/686/arduino-premiers-pas-en-informatique-embarquee/742_decouverte-de-larduino/

**Comment by philippemilink** [comment]
Vu le commentaire, ça a l'air d'être fait exprès:
https://github.com/zestedesavoir/zds-site/blob/0f91490fcefbe5587d097ad889830292ada1587f/templates/tutorialv2/view/container_online.html#L101-L104
Mais je suis d'accord qu'on devrait aussi pouvoir signaler une faute à cet endroit. Qu'en pensent les autres ?

**Comment by Arnaud-D** [comment]
Il n'y pas vraiment de raison de ne pas le mettre en fait.

Pour faire la modif, il y a deux choses à changer. D'abord, retirer la condition suivante du template :

https://github.com/zestedesavoir/zds-site/blob/0f91490fcefbe5587d097ad889830292ada1587f/templates/tutorialv2/view/container_online.html#L101-L104

Ensuite il faut modifier le template de signalement d'erreur, pour afficher "cette partie" au lieu de "ce chapitre" :

https://github.com/zestedesavoir/zds-site/blob/0f91490fcefbe5587d097ad889830292ada1587f/templates/tutorialv2/includes/warn_typo.part.html#L16-L17

Pour ce faire, `container.is_chapter` sera utile. Pour info, c'est défini [là](https://github.com/zestedesavoir/zds-site/blob/0f91490fcefbe5587d097ad889830292ada1587f/zds/tutorialv2/models/versioned.py#L786-L795).

**Comment by helmasaur** [comment]
Je veux bien m'y coller s'il n'y a personne dessus.
