### ISSUE TITLE
Erreur 404 dans la doc technique du back-end

### ISSUE THREAD

**Issue by mehdbnaleg** [zestedesavoir/zds-site#5709]
Salut,

Y a [ce lien](https://github.com/zestedesavoir/zds-site/blob/dev/doc/source/back-end.html) qui est mort dans les deux docs sur le back-end :
[ici](https://github.com/zestedesavoir/zds-site/blob/dev/doc/source/back-end-code.rst) et [la](https://github.com/zestedesavoir/zds-site/blob/dev/doc/source/back-end.rst). Faudrait recréer la page ou modifier le lien du coup.

Merci !

**Comment by Arnaud-D** [comment]
Je n'arrive pas à retrouver les liens morts avec tes explications. Tu pourrais indiquer les éventuels liens cassés depuis https://docs.zestedesavoir.com/ ?

**Comment by philippemilink** [comment]
La documentation de Zeste de Savoir n'est pas faite pour être consulté depuis le dépôt GitHub, mais depuis https://docs.zestedesavoir.com/.

Si tu consultes les deux pages depuis l'interface de GitHub, GitHub formate automatiquement les fichiers et génère les liens qu'il trouve dans les fichiers. Puisque les liens sont relatifs (dans ce cas), le formatage fait par GitHub génère des liens comme s'ils se trouvaient sur GitHub, au même niveau que la page actuellement consultée. Si tu vas sur https://docs.zestedesavoir.com/, les liens relatifs pointent vers des pages qui existent.

J'espère que c'est clair, je ferme le ticket puisque ce n'est pas un bug.
