### ISSUE TITLE
Cette réponse m'a aidé

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#571]
(Javier)

Juste changer le libellé du lien si la réponse est déjà en vert.
Genre "en fait cette réponse est totalement naze elle m'a pas aidé du tout"

http://zestedesavoir.com/forums/sujet/211/cette-reponse-ma-aide-libelle-si-reponse-deja-en-vert/

**Comment by Eskimon** [comment]
Jme la garde car c'est facile à faire je pense :D (à moins que @Alex-D ne l'est déjà réglé sur la branche intégration ?)

**Comment by Alex-D** [comment]
Yep en effet. Il y a un message qui va bien.

**Comment by Eskimon** [comment]
Ok, je ferme ! :D
