### ISSUE TITLE
Ajouter une marge aux blocs de code

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5710]
Actuellement, deux blocs de code côte-à-côte ne sont pas séparés visuellement. Il faudrait ajouter une marge entre les deux.

[Rapporté sur le forum](https://zestedesavoir.com/forums/sujet/13902/deux-morceaux-de-code-fusionnent-invonlontairement/)

**Comment by A-312** [comment]
Seulement entre deux blocs qui se suivent, donc: 

```css
bloc + bloc {
   margin-top:312px;
}
```

**Comment by Situphen** [comment]
Je sais que tu aimes ce nombre mais peut-être pas 312px ? :-° xD

**Comment by Arnaud-D** [comment]
Ceci devrait faire l'affaire : 

```
  + .hljs-code-div {
    margin-top:14px;
  }
```

imbriqué dans le style de la classe `.hljs-code-div`.

Ça se passe dans `assets/scss/base/_content.scss`.
