### ISSUE TITLE
Dissocier visuellement la bêta de la prod

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5712]
Il faudrait dissocier visuellement la bêta de la prod, par exemple en modifiant le logo sur la bêta par rapport à la prod.

[Sujet sur le forum](https://zestedesavoir.com/forums/sujet/13906/comment-sutilise-la-beta-de-zds/)

**Comment by A-312** [comment]
C'est vraiment nécessaire ? Je me suis jamais trompé

Un autre argument:
>Imaginons que je clique sur lien avec un hastag, ça me guide directement vers le bas de page et je ne vois pas que je suis sur la beta, donc c'est un peu inutile de changer le logo

(perso je vérifie toujours l'url des sites que je visite)

-------------------

J'aimerais que ça soit désactivable via localStorage si possible pendant 30min ou plus.
