### ISSUE TITLE
Corriger l'orthographe de la page "Désincription"

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#5715]
En tant que membre connecté, dans les pages des paramètres du profil, on a accès à la page désinscription. Il y a quelques petites fautes d'orthographes qui méritent d'être corrigées :

* Votre compte et tout ses détails => Votre compte et **tous** ses détails
* Vos galeries d’image => Vos galeries d’**images**

Ça se passe dans le template `templates/member/settings/unregister.html`.

**Comment by helmasaur** [comment]
On peut fermer ce ticket ?
