### ISSUE TITLE
Une grande partie des emojis SVG ne s'affichent pas correctement

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5718]
Exemple : 

```
 :)  :D  ;)  :p  :lol:  :euh:  :(  :o  :B  :colere2:  o_O  ^^  :-°  :ange:  :colere:  :diable:  :magicien:  :ninja:  X/  :pirate:  :'(  :honte:  :soleil:  :waw:  :zorro: 
```

Rendu sur la bêta : 

![image](https://user-images.githubusercontent.com/6664636/79392103-15af5480-7f73-11ea-9f76-8bd3c5c71abc.png)

Rendu sur la prod : 

![image](https://user-images.githubusercontent.com/6664636/79392124-1fd15300-7f73-11ea-8ac6-71432d9bcf04.png)

**Comment by A-312** [comment]
Quelques choses tronques les SVG animés aussi : https://raw.githubusercontent.com/zestedesavoir/documents-communication/master/emoticones/clemojiv3/svg/bounce.svg
https://beta.zestedesavoir.com/static/smileys/svg/bounce.svg

Tu pourrais vérifier le contenu du fichier dans le dossier static de la beta ? (dans mon instance de dev, c'est ok).

**Comment by A-312** [comment]
https://github.com/zestedesavoir/zmarkdown/pull/393

**Comment by StaloneLab** [comment]
Corrigé avec la version 8.3.0 de `zmarkdown`, en plus de l'ajout du remplacement emojis Unicode -> clemojis et de la correction des chemins des images.

**Comment by artragis** [comment]
On peut fermer ou pas du coup?

**Comment by A-312** [comment]
Il faut mettre à jour zmd

**Comment by Situphen** [comment]
En fait étant donné que zmarkdown est en `^8.2.0`, c'est la `8.3.0` qui est installée actuellement dans `dev`. Par contre je me demande si ça ne serait pas bien de fixer la version pour contrôler les changements.

**Comment by A-312** [comment]
> En fait étant donné que zmarkdown est en `^8.2.0`, c'est la `8.3.0` qui est installée actuellement dans `dev`. Par contre je me demande si ça ne serait pas bien de fixer la version pour contrôler les changements.

C'est toi qui vois (vu que c'est toi qui déploies)

**Comment by Situphen** [comment]
Pour le déploiement on n'utilise pas le dossier `zmd` du dépôt `zds-site`, la version de `zmarkdown` à déployer est configurée dans le dépôt `ansible-zestedesavoir`. Donc ma question concerne seulement `zds-site`. :)

**Comment by Arnaud-D** [comment]
Gulp optimise un peu trop les SVG animés. Quand on retire la ligne ci-dessous, ça marche beaucoup mieux.

https://github.com/zestedesavoir/zds-site/blob/e11ed24ebb9a53dddf0e2d3f60849d821cb0ebb8/Gulpfile.js#L146

Plus précisément, je pense que l'optimiseur enlève les éléments `hidden`, sauf que puisque c'est animé, ils ne restent pas `hidden` en permanence. Une solution serait de désactiver cette option : [removeHiddenElems](https://github.com/svg/svgo#what-it-can-do).

**Comment by StaloneLab** [comment]
> En fait étant donné que zmarkdown est en `^8.2.0`, c'est la `8.3.0` qui est installée actuellement dans `dev`. Par contre je me demande si ça ne serait pas bien de fixer la version pour contrôler les changements.

Du coup le bug reporté est bien réparé.
En ce qui concerne le pin, je pense qu'il peut être intéressant de faire quand même les bugfixes (8.3.x dans le `package.json`).
