### ISSUE TITLE
Impossible de signaler un MP

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5721]
Impossible de signaler un MP (il n'y a pas de bouton pour signaler)

**Comment by Arnaud-D** [comment]
Ça me paraît normal. Les MP sont prévus comme une conversation *privée*. Seuls les participants y ont accès. À mon avis, le staff n'a pas à y accéder et ça devrait rester comme ça.

Si un des participants veut signaler un comportement inapproprié, il peut toujours le rapporter au staff avec un MP. :-)

**Comment by A-312** [comment]
Ce n'était pas le cas à un moment ? Il me semblait qu'on pouvait signaler un mp

**Comment by firm1** [comment]
Ça n'a jamais existé sur le site la possibilité de signaler un mp.

**Comment by artragis** [comment]
On n'a jamais pu. Le message étant privé, on ne peut y accéder, c'est le principe.

**Comment by A-312** [comment]
Et ajouter un lien vers le signalement du profil ? :/

**Comment by Arnaud-D** [comment]
Ça me parait plus approprié de ne rien mettre. Avec le signalement, on peut difficilement mettre du contexte, et un modérateur aura besoin d'un aperçu de la conversation pour juger de la gravité et la réalité du problème. Pour cela, il pourrait être invité dans la conversation, ou être contacté en MP « à la main ».
