### ISSUE TITLE
Le bouton "Passe au mode compatibilité" n'est pas clair

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#5726]
Un bouton a fait son apparition dans le nouvel éditeur intitulé "Passe au mode compatibilité". Le problème avec ce bouton c'est qu'il n'est pas clair pour l'utilisateur, il a fallu par exemple que j'aille lire le code pour comprendre ce qu'il fait.

Il faudrait donc renommer l'infobulle de ce bouton pour le rendre plus parlant. Plusieurs propositions possibles : 

- "Utiliser une zone de texte sans mise en forme"
- "Utiliser une zone de texte plus accessible"
- etc.

**Comment by Arnaud-D** [comment]
Ce serait bien si le bouton changeait visuellement de statut entre "activé/désactivé". Chez moi ce n'est pas le cas, ce qui rend son effet quasi-invisible.

**Comment by A-312** [comment]
Duplication : https://github.com/zestedesavoir/zds-site/issues/5699

**Comment by Arnaud-D** [comment]
Apparenté mais pas tout à fait dupliqué à mon avis. L'autre ticket ne mentionne pas tout. On a au total :

* icône plus parlante,
* meilleure info-bulle,
* différence visuelle entre activé/désactivé.

Je suis partisan de garder ce ticket pour les améliorations visuelles et de réserver l'autre ticket au amélioration *local storage* et choix automatique selon le terminal utilisé. Ça vous va ?

**Comment by A-312** [comment]
> Apparenté mais pas tout à fait dupliqué à mon avis. L'autre ticket ne mentionne pas tout. On a au total :

Il faudrait peut être passer les éléments supplémentaires ici, sur l'autre issue

**Comment by Arnaud-D** [comment]
Ça me va aussi. Tu peux le faire s'il-te-plaît ?
