### ISSUE TITLE
Mettre à jour yarn.lock

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5733]
Cette PR aurait du mettre à jour le yarn.lock en plus du package.json: #5635 Comme vous le savez yarn.lock "verrouille" les sous dépendances en fonction du yarn.lock

Comment corriger cette issue ?

```
git checkout dev
git checkout -b fix1234
yarn install
git add yarn.lock
git push
```

**Comment by mehdbnaleg** [comment]
Je m'en occupe !

**Comment by philippemilink** [comment]
Résolue par #5755
