### ISSUE TITLE
Notifier normalement les MP de sanction

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#5746]
Actuellement, on envoie un MP et un email en cas de sanction (lecture seule ou bannissement). Cependant, ce MP n'est pas notifié comme les autres.

Il faudrait que ces MP soit notifiés normalement, comme tout MP.

Cela implique quelques modifications pas forcément évidentes avec les *subscriptions* du système de notification.

**Comment by Migwel** [comment]
D'après ce que je vois dans le code, on utilise la méthode `zds.mp.utils.send_mp` qui a un paramètre `direct` documenté comme:
```
    :param direct: send a mail directly without mp (ex : ban members who wont connect again)
```
Actuellement, quand on sanctionne un utilisateur, on envoie `direct=True`. Donc naïvement, je me dis qu'on pourrait simplement passer ça à False (et ça fonctionne effectivement localement).

Mais d'après le message original, ceci devrait impliquer des modifications pas forcément évidentes donc je me dis que je dois louper quelque chose

**Comment by Arnaud-D** [comment]
Ça avait été fait, mais ça posait un soucis au niveau de l'envoi des mails et a été *revert*. Plus d'infos dans [ce commentaire de PR](https://github.com/zestedesavoir/zds-site/pull/5669#discussion_r397492700).

La subtilité, c'est qu'il y a en fait deux emails dans l'histoire : celui de la sanction, qu'on doit pouvoir forcer (notamment si le membre est banni et ne peut pas se connecter), et celui de la notification (si direct=False, on fait une notif, et il y a des paramètres de profil pour envoyer un mail dans certains cas). Sauf que dans le code, j'ai l'impression que les deux sont un peu embrouillés, et donc pas forcément immédiat à gérer proprement.
