### ISSUE TITLE
[Refonte des tutos] Doit-on en profiter pour adopter Vue.JS ?

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5749]
Bonjour,

Sachant qu'on va refaire entièrement l'interface des tutos une question se pose : Doit-on en profiter pour adopter Vue.JS ?

Pour les autres pages existantes, on pourra attendre une prochaine refonte du site pour les passer à Vue.JS.

Bon vol,

A.

Voter +1 / -1

**Comment by artragis** [comment]
yo no sé

**Comment by firm1** [comment]
J'ai envie de dire que si ce qu'on veut faire dans la refonte demande des fonctionnalité de vuejs on peut y passer. Mais j'ai l'impression qu'on ne sait pas encore ce qu'on veut faire vraiment au niveau fonctionnel.

**Comment by A-312** [comment]
On accepterait d'avoir des fonctionnalités qui ne fonctionne plus si on n'a pas le JS d'activité ?

**Comment by A-312** [comment]
L'idée de départ est de mettre un de nouvelle techno pour aussi attirer les nouveaux contributeurs mais aussi pour avoir une techno récente, mais on se limite à quoi :
 - Seulement la nouvelle partie édition des tutos ;
 - Les nouvelles pages du site ;
 - Des nouveaux blocks du site ? Mélanger template HTML et bloc REACT dans une page ? Exemple d'usage dans une page : Les filtres ;

**Comment by A-312** [comment]
Un framework reactif pour les pages qui listent des choses (ex : liste de tutoriel, sujet...) avec des filtres qui met à jours le contenu de la liste sans changer de page peut mériter un framework réactif 🤔

**Comment by A-312** [comment]
Si vous faites le changement, il faudra virer gulp pour ne pas avoir des temps de build (watch) élevé lors du dev front.
