### ISSUE TITLE
Erreur lors du rejet d'un tutoriel non réservé / réflexion sur la réservation

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#575]
Lorsqu'un tutoriel est refusé sans avoir été préalablement réservé par un valido, on tombe sur une erreur : `'NoneType' object has no attribute 'username'`

Le problème vient de [cette ligne](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/tutorial/views.py#L285), qui permet de récupérer le pseudo du validateur qui a réservé le tuto. S'il n'y a pas eu réservation, il n'y a pas de valido, donc pas de pseudo, donc erreur.

Le problème se produirait aussi lors de la validation si on donnait le pseudo du valido dans le MP envoyé au membre. Ce n'est actuellement pas le cas mais ça serait sympa que ça le soit, au passage.

En soit, ce n'est pas vraiment un problème puisqu'on est censé devoir réserver un tuto avant de le rejeter/valider. Mais dans les faits ? Un ex-valido peut-il dire s'il arrive qu'on rejette/valide un tuto sans le réserver ? En l'état, on peut aussi rejeter/valider un tuto réservé par un autre valido. Est-ce un problème ou au contraire les habitudes des validos imposent-elles cette possibilité (je pense au cas où le valido a réservé un tuto et disparait pendant des mois (coucou Nathalya)).

Si on impose la réservation, alors il faut au minimum trapper l'erreur correctement ou mieux, ne pas permettre de valider/refuser un tuto sans l'avoir réservé au préalable.

**Comment by SpaceFox** [comment]
> Un ex-valido peut-il dire s'il arrive qu'on rejette/valide un tuto sans
> le réserver ?

Oui, c'est relativement fréquent pour les tutos de merde.

En fait le processus classique est quelque chose comme :
1. Je jette un oeil au tuto
2. S'il m'intéresse je réserve
3. Je valide / refuse

Mais parfois ça arrive que ça se transforme en :
1. Je jette un oeil au tuto
2. Je vois que c'est vraiment une grosse merde alors puisque je suis déjà
   dans l'interface, je refuse

Cela dit, la solution propre serait vraisemblablement d'empêcher l'action
sur un tuto non réservé, si on a la possibilité de dé-réserver dans le cas
où un valido est indisponible.

**Comment by ShigeruM** [comment]
La correction n'ayant pas l'air bien compliquée, je m'en chargerais bien. Mais comme je n'ai pas trop le temps en ce moment ça risque de ne pas être fait tout de suite tout de suite (pas dans les jours prochains en tout cas). Donc si ça n'urge pas (je ne pense pas, étant donné que ça ne concerne que le staff), je veux bien m'en charger. Si vous trouvez que c'est un problème urgent, alors je laisserai la place volontiers. :-)

**Comment by ShigeruM** [comment]
Merci pour ton retour.

> Cela dit, la solution propre serait vraisemblablement d'empêcher l'action sur un tuto non réservé, si on a la possibilité de dé-réserver dans le cas où un valido est indisponible.

Ça me semble ce qu'il y a de mieux à faire aussi. Ça rend le process un poil plus lourd mais c'est plus propre.

Ou alors forcer la réservation par le valido qui traite la demande au moment de l'acceptation/du refus, si le tuto n'était réservé par personne. Et par "forcer la réservation", j'entends indiquer le validateur dans l'objet Validation concerné.

**Comment by Coy0te** [comment]
My 2 cents : je trouve la proposition de Spacefox la plus adaptée. Réservation obligatoire, et avertissement au valido si le tuto a déjà été réservé par un autre.

**Comment by firm1** [comment]
Pour moi aussi la solution propre serait celle là : 

> Cela dit, la solution propre serait vraisemblablement d'empêcher l'action
> sur un tuto non réservé, si on a la possibilité de dé-réserver dans le cas
> où un valido est indisponible

**Comment by Alex-D** [comment]
@ShigeruM : tu as résolu tout ça via le fait que l'IHM oblige la réservation avant la validation non ?

Du coup je suppose qu'on peut fermer. Je te laisse le soin de le faire (au cas où j'oublie quelque chose).

**Comment by ShigeruM** [comment]
Cest pas que dand l'IHM non, mais les templates sont impactés en effet. La
dernière fois que j'ai vérifié, ce n'était pas en place sur la pré-prod.

Je regarderai à l'occasion, mais ça risque de pas être tout de suite...
Le 2 juin 2014 15:24, "Alexandre Demode" notifications@github.com a écrit
:

**Comment by Alex-D** [comment]
J'ai ptet ouillé dans un merge et ait peut-être oublié un endroit, mais j'ai souvenir de l'avoir fait au moins une fois (peut-être sur les articles seulement).

Je m'ajoute ça à la todo de ce soir.

**Comment by ShigeruM** [comment]
Je confirme, ce n'est pas en place pour les tutos sur la pré-prod.

Sur les articles c'est bon en revanche.

**Comment by Alex-D** [comment]
Ok j'ai oublié d'aller le mettre sur les tutos alors. Je m'en vais corriger ça :)

**Comment by Alex-D** [comment]
Normalement cette fois c'est bon, du coup. A réouvrir si ça n'est pas le cas, mais selon mes tests c'est fait.

**Comment by SpaceFox** [comment]
> Normalement cette fois c'est bon, du coup. A réouvrir si ça n'est pas le cas, mais selon mes tests c'est fait.

Non. C'est fait, ou ce n'est pas fait. Mais ce n'est pas "normalement" ou "selon mes tests" fait.

Si tu n'est pas sûr de ta PR (ça peut arriver pour diverses raison), tu attends qu'un tiers teste, et en attendant tu ne ferme pas le ticket.

**Comment by firm1** [comment]
Je confirme que c'est bon.
