### ISSUE TITLE
Améliorer le fil d'Ariane pour les articles ou tutos d'un auteur donné

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#5750]
Actuellement, quand on visualise les articles/tuto/billets d'un membre, ils sont listés sous "Tutoriels"/"Articles" etc. Le fil d'Ariane est ainsi "Accueil > Tutoriels > Tutoriels de ...".

En faisant des tests avec une personne nouvelle sur le site, on était d'accord pour dire qu'on s'attendrait (en tant qu'auteur du moins) à revenir plutôt vers son profil que vers tous les tutos ou articles. On aurait un fil d'Ariane de la forme "Accueil > Profil de ... > Tutoriels de ...".

**Comment by A-312** [comment]
@Arnaud-D  Duplication à : https://github.com/zestedesavoir/zds-site/issues/5091 ?

**Comment by Arnaud-D** [comment]
Oui, je n'ai pas cherché assez longtemps.

**Comment by A-312** [comment]
~~Je connais la plupart des issues donc ça aide^^'~~
