### ISSUE TITLE
Le titre du sujet n'est pas sauvegardé

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5753]
A défaut du contenu, le titre du sujet n'est pas sauvegardé avec le contenu… Ce qui est un poil pénible :(

![image](https://user-images.githubusercontent.com/18501150/80424846-d40f9980-88e2-11ea-9b10-5bf5caf36981.png)

https://zestedesavoir.com/forums/sujet/nouveau/?forum=17

**Comment by A-312** [comment]
(à l'occasion sauvegarder aussi le titre + sous-titre)

**Comment by Arnaud-D** [comment]
Doublon de #5811.
