### ISSUE TITLE
Vérifier que le serveur zmd est lancé avant certains tests ?

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#5759]
Quand on lance la suite de test avec `python manage.py test zds` sans lancer le serveur zmd auparavant, de nombreux tests échouent, ce qui est normal. Cependant, les erreurs qu'on obtient sont un peu cryptiques.

Est-ce que ce serait une bonne idée de faire des vérifications sur l'état du serveur *avant* de tenter de communiquer avec lui (et d'échouer), afin d'avoir des messages d'erreur un peu plus explicites ?

**Comment by A-312** [comment]
J'ai déjà demandé/insisté plusieurs fois sur ce point on m'avait répondu non que c'était assez claire. Vérifie avec artragis avant d'ouvrir une PR

**Comment by Arnaud-D** [comment]
Il y a désormais une [page de la doc](https://docs.zestedesavoir.com/guides/backend-tests.html) qui mentionne explicitement de lancer le serveur zmd avant de lancer les tests.

Je pense que ça fait une documenation suffisante. Au pire, on rouvrira un ticket ultérieurement si on change d'avis sur la question.
