### ISSUE TITLE
Sessions en mémoire plutôt qu'en BDD

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#576]
Je reprends ici une conversation qui fait davantage débat que ce que je ne l'imaginais. Elle commence ici : https://github.com/Taluu/ZesteDeSavoir/issues/496#issuecomment-43737864

Message initial :

Dites moi juste une chose : j'ai cru voir que la session était stockée en BDD, est-ce le cas en prod ?

Si oui, il faudrait changer ça, et mettre les sessions en RAM, au risque de faire écrouler le site (cf SdZ v4).

Et c'est peut-être le problème de ces erreurs 500, d'où ma question ici.

**Comment by firm1** [comment]
> Et c'est peut-être le problème de ces erreurs 500

Ce n'est pas la cause de nos fameuses erreur 500

**Comment by Alex-D** [comment]
C'est déjà ça. Par contre du coup, c'était plus lié à l'autre issue cette phrase ;)

**Comment by Alex-D** [comment]
Ca c'est fait, et j'ai mergé en intégration également. Je ferme.
