### ISSUE TITLE
[v29.1] Bandeau + Menu déroulant = Bug

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5772]
Lorsqu'il y a un bandeau, par exemple sur la bêta ou en local, les menus déroulants je fonctionne pas correctement sur mobile.

**Aperçu**

![Aperçu du soucis](https://user-images.githubusercontent.com/6664636/80823050-264f0400-8bdc-11ea-864a-0a0350360586.png)

**Comment by A-312** [comment]
`#very-top-banner` devrait être en dehors de `.page-container` (juste avant cet élément HTML). Ce qui permettra d'appliquer un `position: relative` à `.page-container`.

Un peu de doc pour comprendre le changement : 
https://developer.mozilla.org/fr/docs/Web/CSS/position
https://developer.mozilla.org/fr/docs/Web/CSS/top

Le fichier CSS en question : https://github.com/zestedesavoir/zds-site/blob/1a424ad41f57e7a537ee620a4d740aa918ee9130/assets/scss/base/_base.scss#L58

Le fichier HTML en question : https://github.com/zestedesavoir/zds-site/blob/22d91d9964a0a5a9171ed45249f55e9b841186af/templates/base.html#L165

**Comment by Situphen** [comment]
J'ai essayé ta solution et effectivement elle corrige bien le soucis indiqué mais elle introduit des régressions : le bandeau ne reste pas tout le long du scroll et le bandeau se superpose au menu hamburger sur mobile. À noter que si ta solution est choisie, il faut penser à déplacer aussi le bandeau des cookies et le bandeau d'accessibilité qui rencontrent le même soucis.

Je ne pense pas que ce soit un ticket Facile (en tous cas en l'état) donc j'ai enlevé l'étiquette et j'ai déplacé dans la catégorie "Pas si facile". :)

**Comment by A-312** [comment]
Tu as bien mis un `position:fixed;` à la bannière ?

**Comment by Situphen** [comment]
Actuellement c'est un `position: sticky` et ça fonctionne bien car `.page-container` prend bien la taille de toute la page. Si on déplace la bandeau en dehors, il faut faire en sorte que `body` ou `html` ou quelque chose comme ça, prenne bien la taille de toute la page (actuellement c'est seulement la taille de l'écran) et lors de mes essais je n'ai pas réussi. Enfin bon, je verrai si j'ai la motivation pour réessayer.

On peut imaginer en effet un `position: fixed` en ajoutant un `margin-top: 25px` (hauteur du bandeau) à l'élément juste après, mais ça ne fonctionne pas sur mobile, probablement à cause du menu sandwich ou quelque chose comme ça.

**Comment by A-312** [comment]
![image](https://user-images.githubusercontent.com/18501150/82411213-a517be00-9a71-11ea-9047-0a2bbc48e3b6.png)
![image](https://user-images.githubusercontent.com/18501150/82411229-ad6ff900-9a71-11ea-8af9-c5cae477d3c7.png)

J'ai ajouté un `padding-top: 25px` au body, déplacé `#very-top-banner` au dessus de `.page-container`, j'ai mis la bannière en `position: fixed` et j'ai augmenté le `z-index`, d'une valeur supérieur à `10`.

![image](https://user-images.githubusercontent.com/18501150/82411409-0475ce00-9a72-11ea-8e3e-129d1e63e9f2.png)

**Comment by Situphen** [comment]
Corrigé depuis quelques temps
