### ISSUE TITLE
Pouvoir importer une image sans drag & drop

### ISSUE THREAD

**Issue by Vanadiae** [zestedesavoir/zds-site#5774]
**Description du besoin**

Lorsque le drag & drop ne fonctionne pas ou que quelqu'un ne connaît pas cette fonctionnalité, donner la possibilité d'ajouter une image avec un bouton qui ouvre un sélecteur de fichier.

Exemple: Je suis toujours frustré quand ... le drag & drop ne fonctionne pas

**Description de la solution**

Ajouter un bouton "joindre une image" dans la modale pour ajouter une image (celle qui permet d'ajouter un lien vers une image) dans l'éditeur.

**Description des alternatives**

aucune

**Contexte additionnel**

à l'emplacement de URL: (avec la zone de saisie à droite), mettre une liste permettant de sélectionner entre "URL" ou "lien" et "Importer une image".

**Comment by A-312** [comment]
Similaire/duplicate à #4358
