### ISSUE TITLE
Le nombre de commentaires pour les tutoriels n'est pas affiché sur la page d'accueil

### ISSUE THREAD

**Issue by Vanadiae** [zestedesavoir/zds-site#5775]
**Description du bug**

Au niveau de l'icône des tutoriels récents, il n'y a pas la bulle avec le nombre de commentaire contrairements aux billets et articles.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Se rendre sur la page d'accueil du site
2. scroll jusqu'à "Derniers tutoriels"

**Comportement attendu**

La bulle avec le nombre est présente

**Capture d'écran**

![image](https://user-images.githubusercontent.com/48521955/80827477-51d5ec80-8be4-11ea-9ced-78e6dff9cff3.png)

A gauche (tutoriels), pas de bulles. A droite pour les articles, les bulles

**Informations techniques**

- OS: Fedora 32 (linux)
- Navigateur: Webkit et firefox
- Version/environnement de zds: prod

**Comment by Situphen** [comment]
De mémoire c'est un choix volontaire lors de la réalisation de la page d'accueil de ne pas mettre cette bulle avec le nombre de commentaires pour les tutoriels.

**Comment by Arnaud-D** [comment]
Oui, l'idée est que les articles et billets sont dans un certain sens plus *actuels* et appellent plus à l'interaction. Cependant, est-ce que c'est toujours une bonne idée ?

**Comment by Vanadiae** [comment]
Je comprends mieux du coup. Je ferme le ticket.
