### ISSUE TITLE
Envoyer un message lorsqu'un membre est retiré des auteurs d'un contenu

### ISSUE THREAD

**Issue by Karnaj** [zestedesavoir/zds-site#5778]
Un MP est envoyé lorsqu'on est ajouté à la liste d'auteurs, mais pas quand on est retiré.

**Comment by Migwel** [comment]
Ca m'a l'air assez simple à implémenter. Une suggestion quant au texte à utiliser ?

Ma suggestion: 

Titre: *Suppression de la rédaction du billet (de l'article, du tutoriel)*
> Bonjour {{ user }},
Vous avez été retiré de la rédaction du contenu « {{ title }} ».

Mais c'est peut-être un peu bref. Je ne suis pas non plus satisfait de "Suppression" mais mon cerveau bloque et ne trouve pas de meilleur substantif.

**Comment by Arnaud-D** [comment]
Salut, oui ça convient. "Retrait" semble convenir au lieu de "suppression". Tu peux peut-être aussi utiliser une formulation épicène du genre "Vous ne participez plus à la rédaction du contenu « {{ title }}".

**Comment by Arnaud-D** [comment]
Résolu par #6085.
