### ISSUE TITLE
Erreur 500 lors d'un changement de pseudo trop long

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5779]
[Reporté par Green sur le forum](https://zestedesavoir.com/forums/sujet/13906/comment-sutilise-la-beta-de-zds/?page=1#p220056) : 

> Salut,
> 
> Après un petit tour dans la bêta pour essayer de comprendre comment s'effectue un [changement de pseudo](https://zestedesavoir.com/membres/parametres/user/), j'ai découvert une erreur interne au serveur :
> 
> [![d](https://zestedesavoir.com/media/galleries/8601/8d9e16ea-32e8-49f0-9e8d-2cfa85120c85.png.120x120_q95_crop.png)](https://zestedesavoir.com/media/galleries/8601/8d9e16ea-32e8-49f0-9e8d-2cfa85120c85.png)
> 
> Pour générer cette erreur, il suffit de changer avec un pseudo très très long.  
> Par ailleurs, un pseudo comme **GreenGreenGreenGreenGreenGreenGreenGreenGreenGreen** est accepté et casse visuellement le CSS du site sur les messages forums.

D'après le Sentry l'erreur est : 

> DataError: (1406, "Data too long for column 'note' at row 1")

Lorsqu'on modifie le pseudo, une note de modération est créée sur le profil "ancien_pseudo s'est renommé nouveau_pseudo" et dans le cas présent le pseudo était trop grand donc la création de la note a échouée.

**Comment by philippemilink** [comment]
Comment est-ce qu'on règle ce problème ? Parce que, au final, deux problèmes sont rapportés ici:
- un pseudo trop long casse le CSS;
- changer son pseudo en un pseudo trop long provoque une erreur 500.

La façon la plus simple de régler les deux problèmes est de réduire la longueur maximale d'un pseudo (actuellement 150 caractères, défini dans le modèle `User` de Django).

**Comment by Arnaud-D** [comment]
Je n'ai pas réussi à reproduire la 500 en local, même si le pseudo semble tronqué. Sur la bêta j'ai réussi à reproduire.

Je n'ai pas de soucis avec une réduction de la longueur maximale des pseudos, mais je pense qu'il faudrait plutôt tronquer le pseudo à l'affichage que le limiter en back.
