### ISSUE TITLE
L'estimation du temps de lecture est ambigü

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#5780]
**Description du bug**

Lorsqu'on a un tutoriel (un big tuto, la plupart du temps), qui est assez long, on affiche l'estimation du temps de lecture comme "1jour 6heures" par exemple. Le problème c'est que pour le lecteur lambda "1jour" c'est un peu ambigü : est-ce une journée de travail normal (7h)? une journée astronomique (24h?) une journée "à la louche" (du réveil au couché)?

Techniquement nous avons simplement besoin de limiter notre conversion aux heures : dans le cas précédent 30h de lecture, pour un big tuto qui fait 600pages en PDF c'est une estimation normale (une page toutes les trois minutes sachant qu'on demande aux gens de tester etc. c'est plutôt acceptable) alors que 1jour 6h est ambigüe.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Prendre l'archive du tutoriel arduino
2. Le publier
3. Regarder l'estimation du temps de lecture
4. Constatez que c'est 1 jour 6h

**Comportement attendu**

L'estimation est de 30h.

**Informations techniques**

- Version/environnement de zds: versions 29.1 ou inférieures

**Comment by artragis** [comment]
Petit guide pour intervenir sur ce bug:

L'affichage de la durée est calculée à la ligne 118 du fichier `templates/tutorialv2/includes/tags_authors.part.html`

```django
 {% if online and reading_time and not is_part_or_chapter %}
            {% trans "Temps de lecture estimé : " %}{{ reading_time|minute_to_duration }}
        {% elif online and not is_part_or_chapter %}
            {% trans "Temps de lecture estimé à moins d’une minute." %}
        {% endif %}
```
La fonction qui est utilisée est `minute_to_duration` qui est définie dans `zds.utils.templatetags.minute_to_duration`.

On remarque que cette fonction appelle un filtre django appelé timesince. C'est ce dernier qui fait le calcul et impose que nous ayons forcément la journée.

L'idée serait de se passer de cette méthode pour n'afficher que le nombre de minutes et d'heures sauf si value > 24 * 60 où on ne garde que les heures.

**Comment by mehdbnaleg** [comment]
Salut ! J'aimerai m'occuper de cette issue, je peux ou est ce que c'est plus pour des membres qui commencent vraiment ?

**Comment by artragis** [comment]
Tu peux, fais toi plaiz

**Comment by helmasaur** [comment]
> Salut ! J'aimerai m'occuper de cette issue, je peux ou est ce que c'est plus pour des membres qui commencent vraiment ?

@ToxicScorpius Souhaites-tu toujours travailler dessus ? Je demande pour savoir si je peux t'attribuer la tâche. Ne t'en fais pas, si tu ne peux plus ou si tu ne veux plus, on peut supprimer l'attribution !

**Comment by helmasaur** [comment]
> On remarque que cette fonction appelle un filtre django appelé timesince. C'est ce dernier qui fait le calcul et impose que nous ayons forcément la journée.
> 
> L'idée serait de se passer de cette méthode pour n'afficher que le nombre de minutes et d'heures sauf si value > 24 * 60 où on ne garde que les heures.

Faut-il créer un nouveau filtre personnalisé ?

**Comment by artragis** [comment]
ça peut être une solution, en effet;

**Comment by helmasaur** [comment]
L'idée du filtre a été écartée car trop complexe pour rien.

Par ailleurs, il faudra réécrire [son test](https://github.com/zestedesavoir/zds-site/blob/42cb8ef05cb1ff047d0ad3839d8ad48a18a472e2/zds/utils/tests/tests_minute_to_duration.py).

**Comment by mehdbnaleg** [comment]
Je finalise le truc ou on laisse tomber ?

**Comment by Arnaud-D** [comment]
C'est toujours ouvert donc il est encore temps de finaliser. :-)

**Comment by lokasku** [comment]
Je suis confus, elle est toujours ouverte ?

**Comment by artragis** [comment]
oui car la PR de toxic n'a pas été mergée

**Comment by Arnaud-D** [comment]
Pour info, le travail de Toxic est en attente de reprise, donc n'importe qui peut reprendre ce sujet, quitte à s'inspirer de son travail.
