### ISSUE TITLE
Virer jQuery

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5786]
**Proposition**

jQuery est une bibliothèque assez complète dont on n'utilise qu'une seule partie des fonctionnalités. Aujourd'hui une grande partie des fonctionnalités que l'on utilise ont été intégrées au langage JS, l'utilité de jQuery est assez réduite.

Je propose que l'on essaie progressivement de se passer de jQuery au profit du JS "pur" (aka VanillaJS) :

1. en court terme, privilégier l'écriture des nouveaux codes JS en VanillaJS ;
2. en moyen terme, remplacer jQuery par [Svelte](http://sveltejs.com/) (4,1 Ko au lieu de 87,4 Ko) et des fonctions utilitaires si besoin (dans un fichier `utils.js` documenté par exemple)
3. en long terme, remplacer les notations `$` par du VanillaJS

Qu'est-ce que vous en pensez ?

**Comment by A-312** [comment]
(pour ceux qui regarde sur google, on parle de l'ancien Svelte (Svelte v1))

**Comment by Situphen** [comment]
Bon, j'ai commencé un peu la transformation vers Svelte sur ma branche `bye-jquery` ([voir le diff](https://github.com/zestedesavoir/zds-site/compare/dev...Situphen:bye-jquery)) mais je ne suis pas sûr que ce soit la bonne manière de faire. Il serait peut-être mieux de passer directement de jQuery à VanillaJS (sans passer par Svelte) fichier par fichier (en réécrivant le code car la manière de l'écrire n'est pas la même au fond).

**Comment by A-312** [comment]
@Situphen C'est l'une des raisons pour lesquels j'ai envie qu'on passe à un framework reactif, c'est que quitte à réécrire du code, autant utiliser quelques choses qui nous facilite la vie avec les futures fonctionnalités.

**Comment by Chamane** [comment]
Je suis parfaitement d'accord avec @A-312 je vote pour React dans le Frontend

**Comment by artragis** [comment]
Je clos le ticket on va s'organiser autrement. Il est clair que tout le monde veut virer JQ mais on va le faire petit à petit en mettant des objets propres à zds dans la boucle et sans nouvelle lib.
