### ISSUE TITLE
Le bouton "i" à un background blanc

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5792]
Je vois que ça sur mon PC, le bouton i à un background blanc au lieu de gris.

![image](https://user-images.githubusercontent.com/18501150/82243853-9382c900-9940-11ea-8479-4116d881c92e.png)

J'ai augmenté le contraste pour mettre en évidence la différence : 

![image](https://user-images.githubusercontent.com/18501150/82244156-1572f200-9941-11ea-9514-37677e48a9fa.png)

![image](https://user-images.githubusercontent.com/18501150/82244105-fd02d780-9940-11ea-9934-a8e4dbc22e81.png)

Il faudrait donc que le bouton `.easymde-dropdown` est la même couleur de fond que le background (`#fdfdfd`)

**Comment by artragis** [comment]
Dans le fichier `editor-new.scss` on a l'ensemble des classes que zds définit pour l'éditeur, notamment `.editor-toolbar`. C'est en tant qu'enfant de cette section qu'il faudra modifier le style.

**Comment by A-312** [comment]
Pas sûr que ça soit si facile que ça, car si on applique betement un background, ça efface la petite flèche en bas a droite

**Comment by artragis** [comment]
Il suffit de changer les couleurs du lineargradient qui est utilisé à la base

**Comment by helmasaur** [comment]
Je veux bien m'y coller.

Par ailleurs, faut-il modifier la couleur des symboles pour une plus grand chohésion avec le design du site. Même question pour le survol.

**Comment by A-312** [comment]
@Helmasaur https://github.com/zestedesavoir/zds-site/pull/5700

**Comment by helmasaur** [comment]
Tu t'occupes de ce ticket ? Ou est-ce que c'est pour me dire que pour l'apparence, c'est déjà en train d'être fait ?

**Comment by A-312** [comment]
Je ne produis plus rien, j'avais commencé quelques icônes avec l'éditeur en ligne [Gravit](https://designer.gravit.io/), ça peu peut-être t'aider.

**Comment by helmasaur** [comment]
En fait, le bouton ne devrait pas avoir de fond. Par contre, je ne sais pas d'où vient ce fond blanc. Est-ce que ça provient d'EasyMDE ?

![zds_i](https://user-images.githubusercontent.com/873762/87735266-54081a00-c7d5-11ea-8d69-676fbfe38a74.png)

**Comment by A-312** [comment]
@Helmasaur firm1 a utilisé un dégradé pour dessiner la flèche que tu vois en bas
