### ISSUE TITLE
Billets précédents et suivants : uniquement ceux choisis par le Staff

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5793]
[Discussion sur le forum](https://zestedesavoir.com/forums/sujet/14090/bug-dans-les-billets-recents/)

> Les billets écrits ne sont pas validés avant publication par le Staff, n’importe quel membre peut publier son billet quand il le souhaite. Par contre, les billets affichés sur la page d’accueil sont ceux sélectionnés par le Staff, ce qui n’a pas été le cas de "L’hygiènisme une bombe à retardement" pour l’instant.
> 
> Il serait à mon avis souhaitable et cohérent que les liens Précédent et Suivant en bas des billets ne proposent que les billets sélectionnés par le Staff.

Il faut ajouter dans le fichier `zds/tutorialv2/views/published.py` quelque chose comme : 

```py
if self.current_content_type == 'OPINION':
    queryset_pagination = queryset_pagination.filter(content__sha_picked=F('sha_public'))
```

au niveau des ces lignes : 

https://github.com/zestedesavoir/zds-site/blob/c4d3dd39c6a780054113d5185fb83bc82f6753be/zds/tutorialv2/views/published.py#L108-L117

Il faut ajouter au tout début du fichier `from django.db.models import F`.

**Comment by leroivi** [comment]
Je prends ;)

**Comment by HSleymn** [comment]
alors j'ai essayé de le régler, et si c'est bon, c'est réglé alors !

**Comment by leroivi** [comment]
Attention au test_opinion_link_is_not_related_to_the_author, il est à mettre à jour en conséquence

**Comment by Arnaud-D** [comment]
Pour info, ce travail est en attente de reprise, donc n'importe qui peut reprendre ce sujet, quitte à s'inspirer du travail déjà effectué.
