### ISSUE TITLE
Permettre la modification de l'introduction et conclusion d'un article "in place"

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#5795]
**Description du besoin**

Actuellement, le formulaire de nouveau contenu (et édition de contenu) est surchargé et un peu fourre-tout. Notamment, il contient l'édition de l'introduction et de la conclusion. Pour l'alléger, on peut sortir ces deux formulaires de là.

**Description de la solution**

Dans l'idéal, la solution serait une modification *inplace*. On a le texte de l'introduction sous les yeux, on clique sur un bouton et on a un éditeur qui vient prendre la place. Quand on valide, on revient sur l'affichage normal et on voit le résultat.

**Comment by A-312** [comment]
Des pistes pour le q/a et le dev : 

Pour l'éditeur : la difficulté en front sera de vérifier que l'ajout/chargement dynamique de l'éditeur fonctionne bien, et vérifier notamment les boutons spellchecker pour grammalect et antidote (je ne sais pas si mon code fonctionnera correctement. Certaine partie sont dans un onload).

Dans un second temps il faudra vérifier comment est géré l'autosauvegarde

**Comment by Vayel** [comment]
J'essaye un truc.
