### ISSUE TITLE
Modification de la miniature du contenu directement sur la page du contenu

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#5797]
**Description du besoin**

Actuellement, le formulaire de nouveau contenu (et édition de contenu) est surchargé et un peu fourre-tout. Notamment, il contient la modification de la miniature du contenu. Ce serait bien d'alléger en mettant ça a un meilleur endroit.

**Description de la solution**

J'imagine une solution un peu comme sur tous les sites qui ont des images de profil. On a l'image par défaut qui s'affiche toujours (ce n'est pas le cas actuellement), et on peut cliquer dessus ou sur un bouton pour la changer. On accède à un sélecteur de fichier, on choisit le fichier, on valide et on voit directement le résultat.

**Comment by A-312** [comment]
(Petite précision : Modification ou première upload de miniature)

**Comment by Arnaud-D** [comment]
Oui, c'est important de gérer aussi la première fois. Actuellement, on n'affiche même pas l'image par défaut, mais je pense qu'il faudrait la mettre vu qu'elle est affichée à de nombreux endroits sur le site de toute façon. Il n'y aurait alors plus vraiment de différence entre première fois et changement de l'image.
