### ISSUE TITLE
Markdown feature

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#58]
J'ouvre cette issue  pour discuter et répertorier les feautres demandées : changement de syntaxe, nouveau comportement, nouvelle extension, etc...

Une autre issue est ouverte pour répertorier les bugs connus dans le markdown du site : https://github.com/Taluu/ZesteDeSavoir/issues/57

Ici on se concentre sur les feature

La version en prod diffère legerement de ce qui avait été discuté, je vous laisse regarder le mini tuto rédigé par Shig à cet effet : http://zestedesavoir.com/forums/sujet/4/guide-du-markdown-de-zds

Actuellement n'est pas implémenté : 
- Les listes ordonnées autre que chiffre arabes

**Comment by cgabard** [comment]
Est ce que quelqu'un voit un interet pour les auteurs de pouvoir glisser des commentaires dans leurs textes : des trucs supprimés au parsage mais visible dans les sources ?

**Comment by SpaceFox** [comment]
Pourquoi pas, mais de mon point de vue c'est une priorité très basse.

**Comment by cgabard** [comment]
C'est que je viens de voir une extension qui faisait ça, je me disais que ça pourrait être utile. Mais n'etant pas vraiment auteur, je ne savais pas si il y avait un interet

**Comment by SpaceFox** [comment]
Le mieux est sans doute de poser la question sur le group, où on a pas mal
d'auteurs de tutos importants.

**Comment by firm1** [comment]
Moi perso, je vois bien un gros intéret mais, comme le dit Spacefox, la priorité est très basse. Donc, si ça te prend 15 min, pourquoi pas, mais si tu dois y passer une demie journée, je vois pas trop l’intérêt de t'y pencher tout de suite.

**Comment by ShigeruM** [comment]
Perso j'en ai déjà ressenti le besoin. Par exemple dans ces différents cas de figure :
- masquer temporairement des bouts de tutos qui ne sont pas très importants mais qui doivent être revus ;
- préparer des mises à jour du tuto pour des fonctionnalités à venir (exemple : les nouveautés Windows 8.1 dans un tuto Windows 8) ;
- laisser des indications pour le co-auteur.

Et d'autres surement. Dans tous les cas on peut faire ça, mais on fait mieux avec.

**Comment by Coy0te** [comment]
Pareil, je trouve que : 
- c'est pratique de pouvoir se caler des notes/TODO dans un chapitre, ou de masquer temporairement des extraits de cours au public ;
- c'est pas urgent et ça peut attendre plus tard si c'est chronophage à mettre en place / tester.

**Comment by cgabard** [comment]
J'ai vu une extension qui le fait, utilisant les commentaires html : `<!-- Commentaire pouvant etre inline et/ou multiligne -->`

Le prob, mais qui se posera quelque soit la syntaxe, c'est que ça risque de virer, aussi, ce texte qui serait présent dans des balises codes. Ce qui peut être gênant pour le(s) tuto(s) html et associé.

**Comment by ShigeruM** [comment]
Je ne pige pas. Pourquoi ça poserait un problème avec une syntaxe
spécifique du style (au hasard, c'est peut-être pas top) : <-tuto texte en
commentaire tuto-> ?

**Comment by cgabard** [comment]
En fait parser les syntaxes basé sur un template de debut et de fin sont difficiles à implémenter proprement avec Python-markdown.

L'extension en question passe en pré-processing et vire tout ce qui est entre `<!-- ... -->` à coup de regexp. Donc si tu parle de cette balise dans un bout de code, tu l'a dans l'os.

Faire une syntaxe specifique n'enlève pas le prob, simplement il est moins probable de trouver un texte `<-tuto ... tuto->` donc probablement plus acceptable.

**Comment by Coy0te** [comment]
Une notation du genre `<-offline ... offline->` me semble pas mal (éventuellement moins verbeuse, mais tout aussi explicite).

**Comment by cgabard** [comment]
Oui je pense que ça va finir par un truc du genre.

**Comment by firm1** [comment]
Je pensais à une feature, mais je ne sais pas si c'est markdownable.

C'est la possibilité de pouvoir mettre en surbrillance son code. 

par exemple je tape le code suivant dans mon cours : 

``` python
from os import path

print('yeah')
print('yeah--')
print('yeah---')
print('yeah--')

```

Je le modifie et j'ai envie de mettre en surbrillance dans le prochain code, les parties qui ont été modifiées. Un peut comme si je traçait au marqueur la ligne mise à jour. ça peut être utile dans les cours.

Est-ce que c'est possible de faire ça avec une syntaxe markdown du style.

``````
[1;4-5]
```python
from os import path

print('yeah')
print('yeah--')
print('yeah---')
print('yeah--')

``````

Qui mettrait en surbrillance les lignes 1, 4 et 5 ?

**Comment by Coy0te** [comment]
Si jamais c'est possible, prévenez-moi : c'est une info qui existe dans la balise `<code>` du zCode et que je peux récupérer lors de la conversion.

**Comment by cgabard** [comment]
Hum je regarderais ça demain. En soit il me semble que pygment le supporte donc pourquoi pas (au détail pret que pour moi ce sera plus facile que l'indicateur soit en dessous)

**Comment by cgabard** [comment]
Question au passage : est ce que permettre d'ajouter des légendes aux codes ne serait pas aussi pertinent ?

**Comment by cgabard** [comment]
Et aux vidéos ? Sachant qu'elles sont incluses via flash YouTube/dailymotion

**Comment by Taluu** [comment]
Pour le code, je verrais bien une spécification après le nom du langage (s'il est rpécié). Enfin je dis ça du moins pour les syntaxes GFM / Pandoc like, soit

``````
```lang:1:4-6:15
code
```
``````

Ca me semble assez intuitif, non ?

**Comment by cgabard** [comment]
Certes mais ça, ça m'oblige a soit : 
- recopier l'extension qui gère ça a part pour la modifier
- faire encore un vieux hook pas beau

Car ces balises de codes sont gérés avec une extension fournit avec le parseur. Je vais voir...

**Comment by Coy0te** [comment]
Pour les légendes des codes, si jamais y'a besoin, il y a un titre à certaines balises `<code>` du zCode aussi.

**Comment by cgabard** [comment]
Bon poure hightlight de lignes de codes, en effet pygment le permet mais les classes qui le gèrent dans markdown, pas du tout

**Comment by firm1** [comment]
Encore une autre feature qu'on pourrait voir sur le markdown, redonnez aux auteurs de citations un sens sémantique.

Actuellement, pour faire une citation, on écrit ceci:

``` text
**firm1 a écrit**
> Ta gueule 
```

Cette façon de faire à plusieurs défaut : 
- L'utilisateur doit saisir la partie `**firm1 a écrit**` a la main, et ça prend du temps
- Sémantiquement parlant, c'est faux de l'emphaser tel qu'on le fait.
- On ne peut pas agir spécifiquement sur le css des auteurs de citations différent de la mise en gras
- ...

bref, vous voyez le bordel.

Je me demande ci on ne peut pas avoir une syntaxe sémantique pour les auteurs de citations du style : 

``` text
![firm1]
> Ta gueule 
```

**Comment by cgabard** [comment]
Je suis plutot pour même si ça va me demander un hack pas beau...

Après est ce que c'est cette syntaxe la plus pertinent ? je ne sais pas... m'en fout

**Comment by Coy0te** [comment]
Encore pareil, faudra me prévenir si on change. =)
Dans le parseur zCode, j'ai construit les citations sur la syntaxe basée sur le gras.

**Comment by cgabard** [comment]
Bon Pandoc ne propose rien du tout à ce niveau donc proposés... En attendant je ferais la solution de firm1 mais on peut changer

**Comment by Coy0te** [comment]
Faut pas oublier non plus que le bouton "citer" va se charger de pré-remplir ce truc avec à peine 4 lignes de jQuery. 
Donc ok pour donner un sens sémantique à l'info, mais l'argument de la pénibilité ne tient pas vraiment.

Pour la syntaxe à choisir, perso je m'en fous aussi.

**Comment by GerardPaligot** [comment]
L'avantage d'utiliser le markdown n'est-il pas de pouvoir utiliser une syntaxe commune à un grand nombre de sites ? Je trouve qu'on se détache de plus en plus du markdown de base et qu'à force, on va arriver à quelque chose de vraiment différent.

Pour le cas présent, la solution de base ne m'a jamais gênée. Je suis d'avis de ne pas y apporter des modifications.

**Comment by SpaceFox** [comment]
+1 pour rester sur du standard.

On peut améliorer le truc pour avoir un lien vers le post avec une syntaxe
comme :

**[firm1 a écrit](http://zds.com/mon/post) :**

> Je ne trolle jamais

**Comment by firm1** [comment]
> Faut pas oublier non plus que le bouton "citer" va se charger de pré-remplir ce truc avec à peine 4 lignes de jQuery. 

Je parlais de pénibilité dans les cas ou tu veux écrire toi même à la main.

> L'avantage d'utiliser le markdown n'est-il pas de pouvoir utiliser une syntaxe commune à un grand nombre de sites ?

L'avantage est surtout d'avoir un langage léger qui permet de conserver une certaine sémantique dans le texte. Le markdown de base est très bien, mais il a des limites, et parfois il faut les combler.

> Pour le cas présent, la solution de base ne m'a jamais gênée. Je suis d'avis de ne pas y apporter des modifications.

Tel que les citations sont faites actuellement, il est sémantiquement faux.

Le truc le markdown de zds, c'est qu'il faut qu'à son lancement, toute la syntaxe soit spécifiée au maximum. C'est l'un des trucs qui devra rester stable pendant au moins 3 ans.

> On peut améliorer le truc pour avoir un lien vers le post avec une syntaxe [...]

Dans ce cas, tu considère le texte "a écrit" comme du contenu, ce qui n'est pas le cas.

C'est au parseur md -> html de décider s'il met "firm1 a écrit" ou "firm1 dit" ou encore "firm 1 témoigne".

L'intéret du markdown est surtout la séparation entre le contenu et le displayer.

**Comment by cgabard** [comment]
Pour info, la mise en evidence des lignes de codes, intervalle compris, va arriver. Ce support a été ajouté recemment dans le projet officiel. J'ai ajouté un support des intervalles que je vais proposer au projet officiel. En attendant le support est proposé en clonant le projet officiel et ajoutant un patch pour les intervalles.

Concernant les auteurs de citation, je n'ai rien fait ne sachant pas si tout le monde était d'accord et si tel est le cas, quelle syntaxe utiliser.

en attendant je met au propre et m'assure de ne pas faire planter le serveur.

**Comment by cgabard** [comment]
Je reviens ici pour poser une question concernant les video.

Actuellement il suffit de coller une url en brut pour qu'elle soit remplacé par un objet flash de lecture video. Cela a trois conséquences : 
- Il n'y a pas de syntaxe sémantique pour les vidéos
- On peut insérer des videos inline.
- La syntaxe n'est pas vraiment adapté pour gérer les legendes

De là plusieurs solution : 
- Si les videos inline sont un prob, je peux probablement l'empecher si tel est le cas et ne les transformer que lorsqu'elles sont isolées, avec la même syntaxe
- On peut autoriser les legendes à etre sous les vidéos si la syntaxe suivante ne gène personne : 
  
  ```
  blablabla
  
  http://www.youtube.com/watch?v=oE8qhT-MDC8
  video : Ma super legende
  
  blablabla
  ```
- On utilise la même syntaxe que les images pour les vidéos, et la place du champs alt est utilisé comme legende lorsque isolé : 
  
  ```
  blablabla avec une video inline ![](http://www.youtube.com/watch?v=oE8qhT-MDC8) (pourrait etre désactivé)
  
  ![Ma super legende](http://www.youtube.com/watch?v=oE8qhT-MDC8)
  
  blablabla
  ```
- On utilise une nouvelle syntaxe dédié.

J'aimerai bien des avis dessus...

**Comment by Coy0te** [comment]
Mon avis : 
- les vidéos inline, c'est un truc qui n'est pas censé se produire. Si quelqu'un le fait dans un forum, on s'en fout. Et si quelqu'un le fait dans un tuto, on le corrige en remplaçant par un simple lien (en syntaxe MD) vers la vidéo.
- perso, pour la syntaxe je trouve ça plus intuitif d'utiliser la balise image + alt pour les vidéos & légendes, que de laisser les liens au format texte brut dans le texte (avec la syntaxe des légendes comme nos tableaux et codes). Par ailleurs, je suis pas spécialement partant pour l'ajout d'une balise spécifique pour les vidéos.
- pour info, y'a pas de légende dans les videos des tutos SdZ, donc côté parseur peu importe la syntaxe adoptée.
- pour info toujours, y'a plus de 100 blocs `<video>` dans 25 tutos issus du SdZ.

Après, je sais pas si c'est chiant pour toi de modifier le comportement de la balise image pour qu'elle s'adapte aux cas des vidéos.

**Comment by cgabard** [comment]
> les vidéos inline, c'est un truc qui n'est pas censé se produire. Si quelqu'un le fait dans un forum, on s'en fout. 
> Et si quelqu'un le fait dans un tuto, on le corrige en remplaçant par un simple lien (en syntaxe MD) vers la vidéo.

Je mettrais le même comportement partout : pas de vidéos inlines qui seront remplacé par des liens

> perso, pour la syntaxe je trouve ça plus intuitif d'utiliser la balise image + alt pour les vidéos & légendes, que de laisser les liens au format texte brut dans le texte (avec la syntaxe des légendes comme nos tableaux et codes). Par ailleurs, je suis pas spécialement partant pour l'ajout d'une balise spécifique pour les vidéos.

Moi aussi, surtout que actuellement le alt des images sert de legende de figures si isolés. Je vais rajouter le support des legende direct (permetant de spécifier alt ET legende) mais en soit ce sera cohérent. Je peux éventuellement par soucis de cohérence aussi supporter la même syntaxe que tableaux et code pour les vidéo : Dans ce cas le champs dans les alt est ignoré.

> Après, je sais pas si c'est chiant pour toi de modifier le comportement de la balise image pour qu'elle s'adapte aux cas des vidéos.

Non ça va, le parse des images est fait tard. Si je n'autorise que du non-inline, je passe forcément avant. Je peux donc facilement transformer les balises qui m'arrangent avant, sans que la fonction classique pour les images ne s'en rende compte

**Comment by cgabard** [comment]
Je ferme cette issue, c'etait une mauvaise idée de tout regrouper, j'en fait des indépendantes à la place.

**Comment by cgabard** [comment]
Normalement j'ai fais des issues indépendantes pour tout ce qui doit etre fait. Si vous en voyez d'autres, créez en une et assignez moi !
