### ISSUE TITLE
Améliorer l'ergonomie de la gestion des auteurs d'un contenu

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#5800]
**Description du besoin**

Le menu sur la gauche des contenus est devenu difficilement gérable à cause de son grand nombre d'éléments. Une solution consiste à en extraire ce qui peut être mis ailleurs. Je pense en particulier qu'il est possible de mettre l'ajout et la gestion des auteurs directement dans la liste des auteurs.

Actuellement on a ça :

![État actuel](https://user-images.githubusercontent.com/35631001/82559359-ca8af180-9b6f-11ea-9d43-2d186345f349.png)

**Description de la solution**

Actuellement, on peut cliquer sur "ajouter un auteur" depuis la liste des auteurs. Ce serait bien si on pouvait aussi supprimer un auteur depuis cette liste. En faisant ça, les boutons du menu de gauche seraient inutiles. Je pense à une ergonomie un peu comme on a dans les clients mails modernes (gmail, outlook etc).

L'idée est donc de faire le boulot là : 

![Zone qui récupère tous les éléments nécessaires](https://user-images.githubusercontent.com/35631001/82559413-e098b200-9b6f-11ea-9d35-acad70a8a34e.png)

Il faudrait faire gaffe à ce que ça fonctionne correctement avec un grand nombre d'auteurs, même si c'est un cas marginal. Je ne sais pas si on plie la liste ou si on doit cliquer pour voir la liste complète ou quelque chose du genre.

**Comment by A-312** [comment]
Ne serait-il pas plus viable d'allouer du temps en premier à https://github.com/zestedesavoir/zds-site/issues/5498 ?

L'idée de #5498 était dans le long terme d'éviter que la barre de gauche soit utilisé comme un fourre tout. On a rarement besoin d'ajouter une personne pendant qu'on rédige, on peut revenir au tableau de bord du contenu pour gérer les auteurs.

**Comment by Arnaud-D** [comment]
Les deux idées mènent au même objectif et me semblent relativement indépendantes. Je ne sais pas si on peut vraiment prioriser.

L'idée générale d'avoir des contrôles *ad-hoc* au même endroit que là où l'information est affichée est de supprimer le besoin d'un menu dédié. Ça fait toujours un élément en moins dans la barre de gauche ou ailleurs.

**Comment by Arnaud-D** [comment]
Corrigé par #6586.
