### ISSUE TITLE
Soucis d'encodage dans l'export HTML des contenus

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5806]
Soucis d'encodage dans l'export HTML des contenus.

[Sujet sur le forum](https://zestedesavoir.com/forums/sujet/14120/republier-un-billet-pour-le-mettre-a-jour/)

**Comment by StaloneLab** [comment]
Il manque le `meta charset` dans l'entête du document ; le passer à utf-8 suffit à résoudre le problème.

**Comment by A-312** [comment]
Sinon l'header HTTP pourrait préciser que c'est de l'UTF8 soit via django, soit config nginx

**Comment by Vanadiae** [comment]
Sauf que si la personne enregistre la page, ça sera toujours cassé en local (avec l'entête HTTP).

**Comment by AmauryCarrade** [comment]
Le plus simple pourrait être de générer un vrai fichier HTML, avec les en-têtes qui vont bien, et notamment `meta charset`. Vu qu'actuellement il n'y a que le corps du `body`, et pas le reste (ce qui en fait un document invalide, d'ailleurs).

**Comment by Situphen** [comment]
Je vois personnellement deux possibilités : 

- on souhaite que ce soit un vrai export HTML du contenu (avec titre, auteur, date de publication, etc) auquel cas il faut effectivement un vrai document HTML avec les bonnes informations dedans ;
- on souhaite que ce soit simplement un export brut HTML du contenu (tel quel) auquel cas on peut très bien laisser le document tel quel.

**Comment by artragis** [comment]
troisième possibilité : on ne propose plus l'export html car : 

- on n'a pas le CSS
- on n'a pas les images
- tout sur une page c'est pas terrible en html

**Comment by Vanadiae** [comment]
Je ne pense pas que ça serait une grande perte que de virer le HTML. On a déjà l'EPUB et le PDF (ce qui est déjà pas mal à faire fonctionner correctement) et le HTML est affreux (cf le message d'@artragis).

**Comment by A-312** [comment]
> Sauf que si la personne enregistre la page, ça sera toujours cassé en local (avec l'entête HTTP).

Tu es sûr de ça ? Il me semble que si on fait enregistrer sous, ça enregistrera en utf8 aussi (normalement le meta HTML est facultatif (mais recommandé) si l'header HTTP est correctement configuré).

**Comment by Arnaud-D** [comment]
Du coup, on décide de retirer l'export HTML ou pas ?

**Comment by artragis** [comment]
ça me va perso

**Comment by artragis** [comment]
Pour retirer l'export HTML il suffit de supprimer

- le Publicator sur lequel on a le décorateur qui annonce que c'est un HTML (publication_utils)
- l'URL qui permet de télécharger l'export (urls/tutorial.py, urls/article.py, urls/opinion.py)
