### ISSUE TITLE
Lier des sujets du forum à des dépôts annexes

### ISSUE THREAD

**Issue by arobase-che** [zestedesavoir/zds-site#5807]
**Description du besoin**

Je contribue un peu à ZdS mais rarement (jamais ?) directement sur le dépôt principal `zestedesavoir/zds-site`. Du coup, je n'utilise pas la fonctionnalité `Lié à une issue GH` des forums.

Je suis toujours frustré quand j'ai un problème avec `zestedesavoir/zmarkdown` et que je ne peux pas utiliser cette fonctionnalité. 😛

**Description de la solution**

On pourrait avoir un champ de selection (selectbox) avec les différents dépôts de `zestedesavoir` et techniquement je pense que ça ne devrait pas être très différent ensuite. Certainement qu'en base, il faudrait rajouter (ou modifier l'actuel ?) un champ pour stocker l'information de liaison entre la  (ou/et une table).

**Description des alternatives**

L'alternative la plus simple est de ne rien faire. C'est pas une fonctionnalité très importante.

Voilà. Bonne journée les zesteux.

**Comment by philippemilink** [comment]
Résolu par la PR #6084
