### ISSUE TITLE
Mise à jour des miniatures des Unes

### ISSUE THREAD

**Issue by arobase-che** [zestedesavoir/zds-site#5808]
**Description du bug**

Lorsqu'on crée une `Une` et qu'on modifie son titre, celui-ci n'est pas mis à jour. On doit sauvegarder puis ensuite revenir sur la news pour voir le rendu.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Allez dans la section « Gérer les Unes »
2.  « Nouvelle Une » ou éditer une Une.
3. Modifier le titre de la Une (le premier champ)
4. Constater que celui-ci n'est pas mis à jour
5. Modifier le type (le deuxième champ) ou n'importe quel autre champ
6. Constater que la prévisualisation est bien mise à jour.

**Comportement attendu**

On s'attend à ce que le titre soit mis à jour. C'est important car un titre trop long où mal coupé à doit être modifier. C'est un peu embétant de devoir sauvegarder puis revenir dessus.

![news_bug](https://user-images.githubusercontent.com/2202307/82878227-80bd5500-9f3b-11ea-8bc0-ce2a55c64c00.png)

Voilà, c'est certainement rien.

**Comment by Situphen** [comment]
Changer `h3` en `h2` dans le fichier `assets/js/featured-resource-preview.js` devrait résoudre le soucis.

https://github.com/zestedesavoir/zds-site/blob/c4d3dd39c6a780054113d5185fb83bc82f6753be/assets/js/featured-resource-preview.js#L14

**Comment by leroivi** [comment]
Bonjour, j'aimerai prendre ce ticket
