### ISSUE TITLE
Typo dans le formulaire de connexion

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#581]
Le formulaire de connexion affiche :

> u uMot de passe oublié ?

**Comment by Eskimon** [comment]
C'est déjà corrigé dans la branche d'intégration.
Je laisse @Alex-D confirmer mais je pense qu'on peut fermer...

**Comment by firm1** [comment]
Il s'agit là plutôt d'une correction à faire dans les formulaires du backend.

C'est fait normalement ici : #595
