### ISSUE TITLE
Element HTML avec la même Id sur la page d'un contenu publié

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5810]
![image](https://user-images.githubusercontent.com/18501150/83149508-75fcee80-a0fa-11ea-8eff-e9d07da21002.png)

On a deux fois un élément avec la même id, l'id devrait être unique

Sur la prod : https://zestedesavoir.com/tutoriels/3324/introduction-a-la-visualisation-de-graphes-avec-visnetwork/

**Comment by philippemilink** [comment]
Précision: il faut être connecté avec les droits staff pour voir ce bug (ça vient du formulaire pour dépublier un contenu).

**Comment by Arnaud-D** [comment]
Le bug vient de la génération des formulaires par Django. Par défaut, il attribue des id aux champs en fonction de leur nom (voir [la doc dédiée](https://docs.djangoproject.com/en/3.0/ref/forms/api/#django.forms.Form.auto_id)). Or, certaines de nos pages ont plusieurs formulaires, dont certains ont des noms de champs identiques et se retrouvent donc avec le même id. Il faut donc configurer correctement les formulaires pour éviter que le nommage automatique se fasse de manière incontrôlée.

Pour ce faire, je vois deux solutions potentielles, que je ne sais pas départager :

- changer les configuration des auto_id directement dans les formulaires, ce qui me paraît un peu brutal et plus dur à maintenir (dans le sens ou il faudrait une convention ou s'assurer qu'il n'y a pas de doublons dans plein de fichiers), mais ça règle le problème à la source ;
- changer les configurations des auto_id dans les `get_context_data` des vues, ce qui permet d'avoir tous les préfixes sous les yeux pour une vue donnée et de gérer le problème des id seulement là où c'est nécessaire.

**Comment by philippemilink** [comment]
On peut aussi utiliser l'attribut `form_id` de [crispyforms](https://django-crispy-forms.readthedocs.io/en/latest/form_helper.html#helper-attributes-you-can-set). Il me semble que ça définit aussi le préfixe de tous les ids des champs. 

Sinon je pense que ta première proposition est la bonne, si on met comme préfixe le nom de la classe du formulaire, ce sera unique sur la page, tant qu'un formulaire n'est utilisé qu'une fois sur chaque page (ce qui me semble être le cas).

**Comment by Arnaud-D** [comment]
Je viens de vérifier et `form_id` n'est apparemment utilisé que pour donner un `id` à la balise `form`. La plupart de nos formulaires ont déja un `form_id` défini et la duplication se fait malgré tout.
