### ISSUE TITLE
Mauvaise class pour "Résolu par" dans l'encadré "Signalements du profil"

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5813]
Lorsqu'on est staff, et qu'on se rend sur un profil avec un signalement résolu, et qu'on souhaite cliquer sur le pseudo de la personne ayant résolu l'alerte, on supprime l'élément HTML au lieu d'ouvrir la page de profil du staff.

Ce qui est logique car l'élément HTML en question à la classe `close-alert-box`... Ce qui active le js suivant :

https://github.com/zestedesavoir/zds-site/blob/f7ac482a5481ab30528cf4aaf23aa0f88a24eaee/assets/js/close-alert-box.js#L10

https://github.com/zestedesavoir/zds-site/blob/e413960ab418b7a9872647df127362b504167c3f/templates/member/profile.html#L875

Il faudrait donc créer une nouvelle classe et ajouter la class au sélecteur css dans le fichier scss : 
https://github.com/zestedesavoir/zds-site/blob/2b5087b095fd77490e11694f0292aebd9f5e7cdc/assets/scss/components/_alert-box.scss#L18

**Comment by helmasaur** [comment]
Je n'ai pas trop bien compris. Il faut remplacer les `class` par celui que l'on vient de créer ? La seule chose que j'ai compris, c'est qu'il y a eu de la truanderie pour afficher ce texte à cette endroit 😛 !

**Comment by A-312** [comment]
Il faut enlever la class css qui sert de selecteur pour le code qui va supprimer l'alerte, ici "close-alerte-box"

**Comment by helmasaur** [comment]
Ça ne corrige pas le problème. Enfin si.

Le problème exposé dans ce ticket est bien corrigé mais cela engendre un nouveau. J'ai utilisé le terme « truanderie » en blaguant car mon hypothèse est que la classe `close-alerte-box` a été utilisée pour aligner ce texte à droite. J'imagine que c'est en principe utiliser pour la croix servant à fermer l'alerte.

Il faudrait bel et bien supprimer cette classe puis ajouter ces propriétés à `close-alert-box-text` (je ne sais pas à quoi il sert) ou à un nouveau :

```css
position: absolute;
right: 15px;
```

**Comment by A-312** [comment]
> Il faudrait donc créer une nouvelle classe et ajouter la class au sélecteur css dans le fichier scss :
> https://github.com/zestedesavoir/zds-site/blob/2b5087b095fd77490e11694f0292aebd9f5e7cdc/assets/scss/components/_alert-box.scss#L18

**Comment by A-312** [comment]
Ou directement utiliser `view-alert-box` au lieu de `close-alert-box`. 🤔

**Comment by helmasaur** [comment]
@A-312 Le remplacement de classe (`close-alert-box` par `view-alert-box`) a fonctionné 👍 .
