### ISSUE TITLE
Nouvel éditeur : erreur cryptique en cas d’envoi d’une image trop lourde

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#5818]
**Description du bug**

Avec le nouvel éditeur (pas testé avec l’ancien), si on glisse une image trop lourde (> 1 Mio) on obtient une erreur cryptique à base de « Erreur 400 » au lieu d’un message clair.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Allez sur le site
2. Connectez vous avec n’importe quel compte actif
3. Éditez un contenu
4. Glissez une image d’une taille > 1 Mio sur l’éditeur
5. Quand l’image a fini d’être envoyée, on obtient cette alerte JS :

![image](https://user-images.githubusercontent.com/5786268/84084968-d5a1a680-a9e4-11ea-8bdb-d60061ee6917.png)

**Comportement attendu**

On devrait avoir une alerte qui dit « Image trop grosse » avec la taille maximale autorisée.

**Informations techniques**

- OS: Linux Ubuntu 20.04
- Navigateur: Vivaldi (Chrome)
- Version/environnement de zds: production v29.1-plume/995bec5

**Comment by firm1** [comment]
Alors c'est rigolo, j'ai essayé sur l'environnement de prod actuellement, sur firefox et sur brave (chromium), j'ai bien un message d'avertissement.

![Capture d’écran de 2020-06-10 15-20-35](https://user-images.githubusercontent.com/6066015/84272648-ff1a1980-ab2d-11ea-8f93-bc7d6e678f06.png)

Je n'ai pas vivaldi, faudra que je l'installe pour vérifier

**Comment by SpaceFox** [comment]
C’est étrange, parce que Vivaldi c’est aussi chromium.

**Comment by SpaceFox** [comment]
@firm1 Tu as essayé sur un éditeur ancien ou moderne ? Sur un post de forum ou sur une section de contenu ?

Je n’ai testé que sur l’éditeur moderne dans une section de tuto.

**Comment by firm1** [comment]
J'ai testé sur le nouvel éditeur depuis un post de forum. 😅

A rester du coup dans les même conditions que toi.

**Comment by SpaceFox** [comment]
Ça permet déjà de voir qu’il y a une différence de comportements là où il ne devrait à priori pas y en avoir.

**Comment by artragis** [comment]
J'ai tenté sur le nouvel éditeur depuis les commentaires de l'article sur l'ordre des vêtements

![taille](https://user-images.githubusercontent.com/1523653/84303667-a6f80d00-ab57-11ea-9675-07747fb356bc.PNG)

**Comment by SpaceFox** [comment]
OK, alors après d’autres essais, ça n’est pas la taille mais quelque chose dans l’image elle-même qui fait planter. Et c’est quelque chose qui est présent dans la photo directement générée par mon smartphone.

![IMG_20200601_181631](https://user-images.githubusercontent.com/5786268/84312832-e62d5a80-ab65-11ea-837f-4ea7348c01c0.jpg)

**Comment by artragis** [comment]
ok je reproduis avec ton image

je n'arrive pas à savoir si c'est nginx ou zds qui fait ça

**Comment by firm1** [comment]
Je confirme que ça doit venir de nginx, car j'arrive a reproduire le problème avec cette image sur le serveur de beta (avec gunicorn + nginx), mais pas en local (`python manager.py runserver`)

**Comment by AmauryCarrade** [comment]
Je me demande si ça ne vient pas simplement du fait que la limite de la taille des requêtes côté nginx est inférieure ou égale à la limite de téléversement du site

La conséquence serait que nginx rejette directement les requêtes trop grosses, sans même demander son avis au site… d'où la réponse `400 Bad Request`.
Et je ne crois pas que le serveur de développement de Django ait une limite de taille de requêtes, donc le fichier est systématiquement transmis au site qui retourne un joli message.

Une solution pourrait être d'interpréter une réponse 400 comme un fichier trop gros, ou au moins de reformuler le message avec quelque chose du genre « Quelque chose s'est mal passé lors de l'envoi ; votre image est peut-être trop lourde ».
