### ISSUE TITLE
Pouvoir sauvegarder sans quitter l’éditeur

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#5819]
**Description du besoin**

Aujourd’hui quand on édite un bout de contenu, si on veut sauvegarder on doit « envoyer » l’extrait, et le ré-éditer.

Il serait très pratique d’avoir un bouton de sauvegarde qui n’oblige pas à quitter l’éditeur.

**Description de la solution**

Idéalement il faudrait :

1. Un bouton « Sauvegarder » (différent de « Envoyer ») qui ne quitte pas l’éditeur.
2. Que ce bouton soit accessible depuis le nouvel éditeur en mode plein écran ou édition/prévisualisation sans avoir à changer de mode.
3. Il faudrait trouver un vocabulaire clair pour différencier la sauvegarde-qui-quitte-l’édition (comme aujourd’hui) et la sauvegarde-qui-continue-l’édition (ce que je propos), mais j’ai pas d’idée là tout de suite.

**Comment by AmauryCarrade** [comment]
Certains sites ont ce genre d'option avec un bouton « Sauvegarder et continuer de modifier », et un autre « Sauvegarder et quitter » (ou encore, l'un d'entre eux juste “Sauvegarder”, qui est clair par contraste avec l'autre). C'est un brin long maia ça a le mérite d'être clair.

Sinon, je plussoie la fonctionnalité. Ça peut bien aller avec la modification sans rechargement des contenus.
