### ISSUE TITLE
Appliquer les changements des emotes ":magicien:" ":)"

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5820]
Bonjour,

il faudrait appliquer les changements d'@arobase-che sur zds-site : https://github.com/zestedesavoir/documents-communication/pull/39

**Comment by arobase-che** [comment]
Ça se fait comment ?

Du coté du site, il faut pull simplement ?

**Comment by A-312** [comment]
Oui (il faut commit et push) ici : https://github.com/zestedesavoir/zds-site/tree/dev/assets/smileys/svg

**Comment by philippemilink** [comment]
(je prends ce ticket)

Comment est-ce que la version PNG des smileys (celle qui est utilisée dans la liste déroulante de l'éditeur) est générée ? Manuellement ? Je convertis à la main le SVG en PNG à la dimension souhaitée ?

**Comment by Situphen** [comment]
Il ne faut pas toucher aux smileys PNG, ils n'ont pas ce soucis. Il faut simplement corriger les deux smileys SVG mentionnés plus haut ! :)

**Comment by philippemilink** [comment]
Euh... si, les PNGs ont aussi un sourire plus large que la nouvelle version des SVGs (donc il faut aussi les corriger, non ?)

**Comment by A-312** [comment]
> Euh... si, les PNGs ont aussi un sourire plus large que la nouvelle version des SVGs (donc il faut aussi les corriger, non ?)

@philippemilink Les clemojis en PNG sont en v2, alors que les svg sont en v3. Normalement le site, ne devrait plus utiliser les PNG donc c'est inutile de les changer.

Si tu veux vraiment changer les PNG, il faudrait changer tous les PNG v2 en v3 et convertir les SVG en PNG
