### ISSUE TITLE
Lien erroné dans un des guides de la documentation

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#5829]
**Description du bug**

Le guide [Lancer Zeste de Savoir sur Linux](https://docs.zestedesavoir.com/guides/run-linux.html) contient un lien erroné. 

**Comment reproduire ?**

1. Allez sur le guide [Lancer Zeste de Savoir sur Linux](https://docs.zestedesavoir.com/guides/run-linux.html) 
2. Cliquer sur "mettre à jour votre environnement de développement"
3. Constater qu'on est renvoyé sur la liste des guides au lieu du guide [Mettre à jour son environnement de développement](https://docs.zestedesavoir.com/guides/update-env.html)

**Comportement attendu**

On devrait être renvoyé vers : [Mettre à jour son environnement de développement](https://docs.zestedesavoir.com/guides/update-env.html)

La modif est à faire dans le fichier `/doc/source/guides/run-linux.rst`.

**Informations techniques**

- présent sur la branche dev

**Comment by jeanlapostolle** [comment]
Je prends

**Comment by AmauryCarrade** [comment]
Astuce @jeanlapostolle : si tu mets juste « fix #5829 », « fixes #5829 » ou « closes #5829 » dans le commit ou le texte de la PR, ça fermera automatiquement le ticket :) .
