### ISSUE TITLE
Besoin de scroller énormément pour accéder à la liste des messages privés sur mobile

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#5834]
**Description du bug**

Pour accéder à la lsite de nos messages privés sur mobile, en portrait, il faut scroller énormément pour que le lien apparaisse.

**Comment reproduire ?**

1. Connectez vous avec le compte admin sur mobile, en mode portrait
2. Lire tous les messages privés
3. Revenir à l'accueil
4. Appuyer sur l'icône des MP
5. Observer qu'il faut scroller fortement pour que le lien "voir toutes les discussions apparaissent"

**Comportement attendu**

Le lien "Voir toutes les discussions" apparait sur l'écran sans problèmes

**Capture d'écran**

Si possible, une capture d'écran qui explique le problème.
![image](https://user-images.githubusercontent.com/1523653/85221277-d0fccb00-b3b2-11ea-90e2-ceb42139fef3.png)

**Informations techniques**
Reproduisible sur desktop en réduisant le navigateur jusqu'à ce que la largeur fasse moins de 450px

**Comment by WinXaito** [comment]
Note que si on a activé le paramètre "Dérouler les menus au survol", le problème n'est plus présent. Nous sommes directement rediriger vers la pages des MPs (ce qui pourrait être un comportement plus pratique sur mobile).
