### ISSUE TITLE
Mode nuit

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#584]
Idee de la mascotte : ~~http://zestedesavoir.com/forums/sujet/199/mode-nuit/~~

En substance : Avoir plusieurs ton de design pour nuit, saison, events...

**Comment by gustavi** [comment]
404 sur le lien @Eskimon

**Comment by Axylium** [comment]
Normal, c'était un sujet de la bêta !

**Comment by Eskimon** [comment]
Normal mais dommage car du coup on a perdu toute trace de cette discussion...

**Comment by Alex-D** [comment]
L'idée n'était pas neuve, on sait très bien où on veut arriver. Globalement, c'est "juste" des changements de contraste pour passer de clair/foncé à foncé/clair.

Je ne l'ai pas fait jusqu'ici car secondaire et on avait beaucoup d'activité sur le front, s'il fallait maintenir deux déclinaison à chaque patch, ça aurait été un enfer ^^

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis presque an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.

**Comment by viki53** [comment]
Hello,

J'ai démarré un dark mode via un UserScript, si jamais ça peut donner une base de travail : 

C'est très primitif (j'ai repris quelques couleurs ZdS et improvisé d'autres), l'objectif étant juste de pas me faire brûler les yeux quand j'arrive sur l'onglet ZdS de nuit.

https://gist.github.com/viki53/6ca0ba05b5d1b903eae959f99eb24b1e

Je pensais faire un sujet sur le forum pour partager ça, mais je me dis qu'il vaut mieux le retravailler un mieux avant, voire l'intégrer directement à la base de code si possible.
