### ISSUE TITLE
La limite de caractères pour le message de modification d’un contenu est trop faible

### ISSUE THREAD

**Issue by Vanadiae** [zestedesavoir/zds-site#5840]
**Description du bug**

voir titre. Cela signifie que l'on ne peut pas être très précis dans le message pour ne pas dépasser cette limite. La limite semble être de 80 caractères.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Créer un tutoriel
2. éditer une partie
3. écrire le message de modification (en dessous de la zone de rédaction)
4. Remarquer que la limite est faible.

**Comportement attendu**

Une limite plus élevée (≥200 au moins).

**Comment by AmauryCarrade** [comment]
Ce problème est assez simple à corriger (je le marque donc comme facile).

Le nombre de caractères est limité par les deux formulaires acceptant un message de commit : [`ContainerForm`](https://github.com/zestedesavoir/zds-site/blob/d7c18e8d7e4df734f2b53e9e23270b7dbfe4be70/zds/tutorialv2/forms.py#L205-L214), qui est le formulaire parent de tous ceux qui ont une introduction et une conclusion ; et [`ExtractForm`](https://github.com/zestedesavoir/zds-site/blob/d7c18e8d7e4df734f2b53e9e23270b7dbfe4be70/zds/tutorialv2/forms.py#L433-L442), qui est celui de ceux permettant la modification d'une section.

#### `ContainerForm`

https://github.com/zestedesavoir/zds-site/blob/d7c18e8d7e4df734f2b53e9e23270b7dbfe4be70/zds/tutorialv2/forms.py#L182-L214

#### `ExtractForm`

https://github.com/zestedesavoir/zds-site/blob/d7c18e8d7e4df734f2b53e9e23270b7dbfe4be70/zds/tutorialv2/forms.py#L421-L442

Il faut modifier, dans ces deux formulaires, le nombre maximal de caractères autorisé pour le message de commit, par une valeur jugée pertinente. Il n'y a normalement rien d'autre à faire (si ce n'est potentiellement mettre à jour les tests si cette limite est testée), car l'implémentation sous-jacente effectuant le commit n'a pas de limite de taille (un texte de commit pouvant être très long, `git` n'en a cure).
