### ISSUE TITLE
Lien vers le flux Atom des nouveaux sujets de forum pointe sur celui des nouveaux messages de forum

### ISSUE THREAD

**Issue by Vanadiae** [zestedesavoir/zds-site#5841]
**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. aller sur https://zestedesavoir.com/forums/derniers-sujets/
2. faire défiler jusqu'à la section "Flux" de la barre latérale
3. copier le lien "Nouveaux sujets (atom)"
4. l'ajouter dans un lecteur de flux

**Comportement attendu**

fait apparaître les flux Atom des nouveaux sujets.

**Remarque**

Tous les autres flux pointent vers le bon flux.

**Comment by philippemilink** [comment]
Je n'arrive pas à reproduire le bug; pour moi les flux correspondent bien aux liens.

Tu peux préciser le problème ?

**Comment by Vanadiae** [comment]
Hum… il semblerait que ça corresponde correctement maintenant, mais il me semblait pourtant bien que ça n'était pas les bons correspondant au nom du bouton. 🤷️
