### ISSUE TITLE
Faute de frappe licence "CB-BY" => "CC-BY"

### ISSUE THREAD

**Issue by leroivi** [zestedesavoir/zds-site#5844]
**Description du bug**

Lors du choix de la licence d'un contenu, parmi les licences Creative Commons, la comboBox nous propose la licence "CB-BY" au lieu de "CC-BY"

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Se connecter avec un utilisateur
2. Accéder au menu "Mes tutoriels" sur le profil
3. Ajouter un "Nouveau tutoriel"
4. Compléter les champs pour avoir un contenu valide et créer le tutoriel
5. Accéder à la page du tutoriel
6. Cliquer sur "Choisissez la licence de votre publication !"
7. Dérouler la liste
8. Choisir "CB-BY" et Valider
9. Le contenu est licencié sous "CB-BY"

**Comportement attendu**

Le nom de la licence est CC-BY

**Capture d'écran**

![licence_cb-by](https://user-images.githubusercontent.com/10254817/86519151-57e08780-be38-11ea-831c-738e4e53d6bc.png)

**Informations techniques**

Présent sur la branche "dev", absent de l'instance en production

**Comment by AmauryCarrade** [comment]
A priori un problème dans les _fixtures_ de développement. Probablement assez simple à corriger, et peu critique pour le moment vu que la prod n'est pas impactée (les licences étant stockées dans une table de la base de données).

Par contre ce sera plus gênant quand on implémentera le sélecteur de licence “guidé”, qui s'appuiera probablement sur ces noms de licences.

D'ailleurs, les licences `CC BY-IO` et `CC BY-ND-SA` n'existent pas non plus (la première car il n'y a pas de clause “IO”, la seconde car elle n'aurait même pas de sens). Et il en manque. Bref, il serait bien de remplacer les _fixtures_ des licences par de vraies données.
