### ISSUE TITLE
Suivi des tutoriels en cours de lecture

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#585]
Une fonction qui est souvent demandé par les lecteurs d'autres sites est le suivi auto des tutos en cours de lecture. Par exemple, dans le profil (ou sur la home ?) on se retrouve avec un cadre du genre " vous avez récemment lu les zeste suivants :
- Machin, chapitre 2 : Comment faire un bidule
- Jardinage, chapitre 4 : La sexualité des fraises

Etc... avec un lien pour retourner la ou la lecture a été terminé...

http://zestedesavoir.com/forums/sujet/205/suivi-de-la-lecture-des-tutos/

**Comment by cgabard** [comment]
Ce ticket est prit en charge par la zep 06. on a aucun interet a garder ce ticket ouvert je pense. Ce n'est qu'une sous-partie de la zep 06. La zep n'étant pas validé -> A fermer

**Comment by gustavi** [comment]
Je ferme ici aussi.

**Comment by Eskimon** [comment]
Lien vers la ZEP 6 : http://zestedesavoir.com/forums/sujet/678/zep-06-favoris-et-autres-suivi-dactivite/
