### ISSUE TITLE
Possibilité de masquer le premier post d'un sujet

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#586]
Actuellement, c'est possible de masquer le premier post dans un sujet : c'est pas vraiment pertinent, si ?

A priori, la seule action possible sur un premier post devrait être de supprimer/déplacer le sujet complet.

**Comment by Alex-D** [comment]
J'avais remarqué le problème également. Il faut juste ne pas avoir le bouton "Masquer" sur l'OP (mais il faut que le back interdise l'action).

**Comment by geoffreyc** [comment]
Est-ce vraiment nécessaire d'interdire l'action? Si le bouton n'est pas la,
IMHO c'est suffisant, en sachant que seulement le staff peut le faire.

**Comment by Alex-D** [comment]
Non, l'auteur d'un post est autorisé à masquer ses posts. Donc si un relou veut masquer l'OP, même si le bouton n'est pas présent, il le peut.

Sinon, si on part sur ton principe, les CSRF n'existent pas (car oui, même si uniquement les staff ont accès à la fonctionnalité, suffit de faire péter le lien dans une image en signature et hop, c'est fini).

**Comment by SpaceFox** [comment]
> suffit de faire péter le lien dans une image en signature et hop, c'est
> fini

Non, puisqu'à court terme c'est un POST sur ce genre d'action.

**Comment by Alex-D** [comment]
Admettons, n'empêche que l'auteur a le droit de le faire sur ces messages, donc faut rajouter un petit check if message != OP dans le masquage.

**Comment by geoffreyc** [comment]
Au temps pour moi, je ne pensais pas que les auteurs pouvaient masquer,
dans ce cas la effectivement il faudrait mieux l'interdire.

2014-05-22 14:56 GMT+01:00 SpaceFox notifications@github.com:

**Comment by cgabard** [comment]
Les auteurs peuvent masquer leur propre sujet ?

**Comment by Alex-D** [comment]
Leur **messages** oui (pas sujet), il me semble que ça avait été gardé.

**Comment by firm1** [comment]
> Actuellement, c'est possible de masquer le premier post dans un sujet : c'est pas vraiment pertinent, si ?

On laisse déjà la possibilité a l'auteur d'un message d'éditer son message, donc si on ne l'autorise pas à le masquer il pourra quand même le faire.

Donc j'ai envie de dire pourquoi enlever cette possibilité ?

**Comment by Alex-D** [comment]
@firm1 : masquer l'OP c'est relativement absurde non ?

**Comment by firm1** [comment]
Essayer de l’empêcher en lui donnant la possibilité autrement me parait
tout aussi absurde.

2014-05-22 16:25 GMT+02:00 DEMODE Alexandre notifications@github.com:

**Comment by Alex-D** [comment]
Bon, donc on s'en moque.
