### ISSUE TITLE
Mettre à jour la version des technologies utilisées par zds-site

### ISSUE THREAD

**Issue by helmasaur** [zestedesavoir/zds-site#5860]
**Description du bug**

Plusieurs version de la même technologie sont affichés à divers endroits, notamment dans la documentation et les fichiers _package.json_.

**Comportement attendu**

Avoir la même version affichée partout (et si possible maintenir les fichiers à jour) pour une même technologie. Lire [ce sujet](https://zestedesavoir.com/forums/sujet/14325/versions-des-outils-utilise-par-zds) pour connaître les versions utilisés en cet instant.

**Comment by helmasaur** [comment]
D'après [cette documentation](https://cloud.google.com/appengine/docs/flexible/nodejs/runtime?hl=fr#nodejs_version), la version utilisé par défaut est la dernière LTS. En théorie, on n'a pas besoin d'indiquer cela :

```json
    "engines": {
    "node": "12.x"
}
```

Après, peut-être qu'il vaut mieux l'indiquer si le projet n'est pas mis à jour avant [la prochaine LTS (20 octobre)](https://nodejs.org/fr/about/releases).

**Comment by Arnaud-D** [comment]
Je ferme, car on enlève les références aux versions : https://github.com/zestedesavoir/zds-site/pull/6168 .
