### ISSUE TITLE
Bug graphique dans la page de profil sur Safari

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#5862]
Avec Safari (peut-être d'autres, mais sur Firefox c'est OK), il y a problème sur la page de profil d'un membre: le champ "Rechercher dans l'activité du membre" et "Inscription le ..." sont bizarrement superposés:

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/5911232/87175326-c611c800-c2d8-11ea-8355-7035d91a04f5.png">

**Comment by AmauryCarrade** [comment]
Est-ce que retirer `height: 50px;` dans `div.aside` (le parent de `aside.under-search` qui contient ce texte mal placé)  corrige le problème ? C'est testable dans l'inspecteur d'éléments si nécessaire, ~~mais je n'ai pas de Safari sous la main pour essayer~~.

MàJ : j'ai testé avec Gnome Web qui a le même moteur de rendu et ça corrige effectivement le problème. PR en approche.
