### ISSUE TITLE
Utiliser la version SVG des clemojis présents dans le menu de dans l'ancien éditeur

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5866]
Dans l'ancien éditeur les PNG des clemojis v2 sont encore utilisé ce qui peut créer une différence visuelle avec la preview des messages. Il serait intéressant d'utiliser les `svg` au lieu des `png`.

https://github.com/zestedesavoir/zds-site/blob/dcde330ad24c88af95b618ed2154c513f4ee14ab/assets/js/editor-old.js#L114-L144

**Comment by helmasaur** [comment]
Tu voudras t'en occuper @ToxicScorpius une fois que tu auras fini avec le ticket sur lequel tu travailles ?

**Comment by mehdbnaleg** [comment]
Je m'y colle ! Je me demande juste comment vérifier que tous les émojis sont bien en SVG lors de la Q/A ?
