### ISSUE TITLE
Gros soucis de performance autour des tutoriels (et articles je suppose)

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#587]
Je poste cette issue, car je trouve relativement exagéré le temps de réponse du système lors de la publication d'un tutoriel.

Tests effectués avec le tuto "Créez votre application web avec Java EE" de @Coy0te 

Pour demander la validation d'un tutoriel, il me faut entre 15 et 40 secondes, avec le proco qui tape des pointes à 70% et qui passe en boost à ~2.65GHz. Sur la prod, ça met quand même 4-5 secondes.

Le processus Python tourne à 30-35% de mon processeur (i5 M450 @2.40GHz) juste pour publier _un_ tutoriel. Cela me semble relativement exagéré. La RAM utilisée par python dépasse les 550Mo durant la publication. Celle-ci dure plusieurs minutes chez moi (au moins 5 bonnes minutes pour une publication qui n'est pas la première). Sur la prod je dépasse les 2 minutes : ça n'est pas possible.

Même si je suis conscient qu'il y aura du cache, que je suis sur Windows et tout ce qu'on veut, je trouve ça énorme. Et le disque n'est pas en cause, j'ai un SSD en 550Mbps symétrique qui est à peine utilisé pendant ces opérations.

Je ne connais pas les méandres de python, mais je propose :
- L'idéal serait de créer un thread pour la publication qui tournera pendant qu'une page de confirmation serait renvoyée, avec un message disant que le tutoriel est en cours de traitement, l'auteur est prévenu par MP de toute façon, Même si ça ne concerne que les validos, je trouve ça frustrant d'avoir une page qui tourne qui freeze, on ne sait pas trop si on peut la fermer car on ne sait pas où ça en est, etc. ;
- Pour la demande de validation, il me semble que c'est un simple traitement en BDD, au delà de la seconde, c'est long. Je ne sais pas trop ce qui ralenti le processus à ce point, mais je trouve ça relativement long.

Je trouve ça super étonnant que les traitement soient si lourds : que se passe-t-il lors d'une validation de publication ?

Dans la DjDT je vois ceci :

```
QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s ' - PARAMS = (u'1',)
```

qui met 179,00ms lors de la demande de validation. Un SELECT qui s'approche des 200ms c'est étrange (même si c'est SQLite et toussa).

**Comment by SpaceFox** [comment]
Attention, tout problème de perfs avec SQLite doit être re-testé avec un vrai SGBD : SQLite est plusieurs ordres de grandeur plus lent que PostgreSQL, surtout sous Windows.

**Comment by SpaceFox** [comment]
Par exemples, les 200 ms de ta requête sous Windows/SQLite sont habituels.

**Comment by Coy0te** [comment]
Question de noob : lors de la validation, y'a pas un traitement dans le repo git du tuto ? C'est peut-être ça qui prend du temps et pourrit les perfs.

**Comment by firm1** [comment]
> Pour demander la validation d'un tutoriel, il me faut entre 15 et 40 secondes, avec le proco qui tape des pointes à 70% et qui passe en boost à ~2.65GHz.

C'est pas pour rien que les vrais developpeurs ne bossent pas sur windows.

> Le processus Python tourne à 30-35% de mon processeur (i5 M450 @2.40GHz) juste pour publier un tutoriel

Compte le nombre de d'images dans son tuto, le nombres de gifs qu'il faut convertir en png, le nombre de page du tuto, le nombre d'extraits du tuto à passer de markdown vers html, l'ensemble du tuto a passer de markdown en pdf, l'ensemble du tuto a passer de markdown en epub, la génération de l'archive du tuto, etc. Et tu verras que c'est un miracle si tu arrive à le faire sous windows en moins de 5 minutes.

> L'idéal serait de créer un thread pour la publication

Confort de valido = v42

**Comment by Alex-D** [comment]
Je ne comprendrais jamais pourquoi un même programme serait 10x plus lent sur un OS que sur un autre... m'enfin soit.

Pour SQLite j'en conviens, d'où ma précision, juste que même en prod, c'est lent (peut-être que ça va s'améliorer avec MySQL et son pontage plus performant).

Par contre, pour une re-publication, je pense que ça serait bien de ne pas tout retraiter...

Il est vrai que c'est que pour les validos et qu'on s'en fou un peu du coup.

Pourquoi une page d'un tuto "la home d'un tuto" est si longue à s'afficher si le HTML est déjà généré à la validation ?

**Comment by vhf** [comment]
> Attention, tout problème de perfs avec SQLite doit être re-testé avec un vrai SGBD 

Attention également, tout problème de perf avec `DEBUG=True` doit être re-testé avec `DEBUG=False`. La différence est parfois de plusieurs ordres de magnitude (!!!).

**Comment by firm1** [comment]
@Alex : c'est pas pour rien que tout le monde s'entend pour dire que
Windows c'est de la merde pour les dev.
- Pour une republication tu dois tout régénérer donc ça prend aussi du temps
- Et comme la précisé victor, actuellement avec un Debug=True en prod les
  perfs sont biaisée. Et en local n'en parlons même pas.
  Le 23 mai 2014 11:06, "DEMODE Alexandre" notifications@github.com a
  écrit :

**Comment by Alex-D** [comment]
Bon ok, donc ce n'est du qu'à l'environnement de dev.
