### ISSUE TITLE
Plus de JavaScript dans le frontend ?

### ISSUE THREAD

**Issue by Chamane** [zestedesavoir/zds-site#5873]
Nous utilisons encore Jquery dans le frontend. A quand allons nous tourner vers plus de JavaScript dans le frontend ?
Allons nous préférer React à Angular si c'est le cas ? J'apprecierais contribuer

**Comment by AmauryCarrade** [comment]
Bonjour,

Je ne suis pas sûr de bien comprendre la remarque, étant donné que jQuery, c'est du JavaScript — certes, un peu ancien.

En terme d'évolution du front-end actuellement, nous avons deux réflexions en cours.

- Concernant l'interface en général, préférer petit à petit VanillaJS à jQuery, pour repartir sur une base plus moderne et _future-proof_ (#5786).
- Concernant l'interface de rédaction des contenus, VueJS est envisagé pour simplifier le travail, étant donné que la direction actuelle est de rendre l'interface de rédaction plus interactive, directe, et efficace. Cela dit, le travail n'a pas encore été commencé à ce niveau.

Il n'est pas prévu d'utiliser React ou Angular à l'heure actuelle, ni de passer _tout le site_ sur un framework réactif, car nous avons à cœur son accessibilité au plus grand nombre, y compris sur des vieux navigateurs. C'est pour cela que seule l'interface de rédaction de contenus est concernée par l'usage de frameworks JavaScript modernes et réactifs. Le reste du site devrait pouvoir fonctionner _a peu près_ sans Javascript fonctionnel — tant que ça ne demande pas trop d'effort de développement (nous sommes une petite équipe).

Dans tous les cas, si vous souhaitez contribuer, n'hésitez pas à en discuter avec nous, nous acceptons avec plaisir les nouveaux contributeurs ! Et si vous avez des remarques sur des parties de l'interface qui ne seraient pas assez dynamiques, de la même façon, n'hésitez pas à le partager.
