### ISSUE TITLE
Pinaillage sur le design de la modale d'export de contenu

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#5876]
**Description du bug**

Deux choses dans la modale d'export de contenu ne me plaisent pas visuellement.

- Le texte qui est justifié
- L'icone "en cours de traitement" des exports

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Allez sur le site '...'
2. Connectez vous avec le compte '....'
3. Allez sur la version publique d'un contenu que vous avez publié (dans mon cas c'est un article)
4. Cliquez sur export de contenu dans la sidebar le texte justifié ne rend pas spécialement beau je trouve: probleme 1
5. Cliquez sur demandez la génération de tous les exports : l'icone qui s'affiche à gauche de PDF, etc. n'est pas la bonne: problème 2

**Comportement attendu**

Idéalement le texte ne devrait pas être justifié et l'icone affichée ne devrait pas avoir ce point noir en bas à droite.

**Capture d'écran**

Problème 1 : le texte justifié

![Capture d’écran de 2020-07-17 13-22-54](https://user-images.githubusercontent.com/6066015/87781820-b2fb7c80-c831-11ea-82c6-28b6b0fe0506.png)

Problème 2 : l'icone

![Capture d’écran de 2020-07-17 13-23-32](https://user-images.githubusercontent.com/6066015/87781870-c3abf280-c831-11ea-9b3d-e8f6011a0489.png)

**Informations techniques**

- OS: Ubuntu
- Navigateur: Brave (Chromium)
- Version/environnement de zds: beta

**Comment by AmauryCarrade** [comment]
Merci ! Je vais regarder ça. L'icône est clairement à corriger : c'est simplement un soucis de _sprite_ qui dépasse, le conteneur étant trop grand pour l'icône d'attente. Pour le texte justifié, j'ai tendance à préférer ainsi (je trouve que c'est plus propre, plus équilibré) mais c'est certes une question de goût. Il n'y a actuellement pas vraiment de norme…

**Comment by Situphen** [comment]
> Il n'y a actuellement pas vraiment de norme…

Sur ZDS, la norme actuelle est de ne pas justifier. Personnellement dans ce cas précis ça ne me gène pas, mais si on veut être cohérent avec le reste du site effectivement il faudrait enlever la justification.

**Comment by AmauryCarrade** [comment]
Dans ce cas OK pour moi.
