### ISSUE TITLE
La demande d'aide sur un contenu ne déclenche rien

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#5878]
**Description du bug**

Cliquez sur un type d'aide dans la sidebar ne semble pas déclencher de demande d'aide.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Allez sur le site '...'
2. Connectez vous avec le compte '....'
3. Allez le brouillon d'un contenu (dans mon cas c'était le brouillon d'un contenu déjà publié)
4. Cliquez sur "Repreneur" dans la sidebar et contatez qu'un bref bouton check s'affiche à gauche du texte, puis disparait sans aucune forme de message.

**Comportement attendu**

J'aimerai que le clic sur ce bouton m'informe à minima que ma demande a été prise en compte et que je retrouve mon contenu dans la liste des contenus qui ont besoin d'une aide.

**Capture d'écran**

![Capture d’écran de 2020-07-17 13-36-01](https://user-images.githubusercontent.com/6066015/87782253-7aa86e00-c832-11ea-9719-ba76c075c38e.png)

**Informations techniques**

- OS: Linux
- Navigateur: Brave (Chromium)
- Version/environnement de zds: beta

**Comment by AmauryCarrade** [comment]
Le soucis c'est que l'URL de l'API n'a pas de `/` à la fin et que nginx ou django redirige vers la version avec un `/`, mais la version avec un `/` n'existe pas, ce qui fait qu'on se prend une 404.

**Comment by AmauryCarrade** [comment]
Je confirme que ce problème est bien corrigé en bêta.
