### ISSUE TITLE
Communication automatique sur les réseaux sociaux

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#588]
Quand on publie ou met à jour un tuto ou article, un post est crè automatiquement sur les différents réseaux sociaux, avec des comptes ZdS

**Comment by cgabard** [comment]
Oui, enfin sauf les mises à jours mineur

**Comment by SpaceFox** [comment]
Bien sûr.
Le 23 mai 2014 09:07, "Christophe Gabard" notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
Ca va vite être le bordel. Selon moi, les flux RSS sont là pour ça. Les sites qui font ça perso je les vire car y a aucune vie dans les messages.

Si vous avez des arguments à me proposer là dessus, je suis preneur, mais dans l'immédiat ça me tente pas.

A ce moment là on met IFTTT sur le RSS qui balance sur Twitter, FB et G+ et touche même plus aux comptes. J'ai déjà testé ce mode de fonctionnement et ça ne me plait pas tellement.

**Comment by SpaceFox** [comment]
Je ne me rappelle pas avoir dit que notre communication devait être
constituée _uniquement_ de messages automatiques. Bien sûr qu'il faut aussi
des vrais messages !

Par contre, voyons les choses en face : les RSS sont de moins en moins
utilisés, de plus en plus de gens suivent les actualités grâce aux réseaux
sociaux.
C'est pour ça qu'il me paraît primordial d'annoncer les créations et MAJ
majeures de tutos et d'articles sur les réseaux sociaux.

Comme on ne peut pas le faire faire par les validos, et qu'on ne peut pas
demander à l'équipe de communication de faire un bout de message pour
chaque tuto / article ; que de plus il n'y a pas de raison d'annoncer
_certains_ contenus uniquement, autant faire un système qui les balance
automatiquement tous.

On pourrait aussi prévoir un champ dans le formulaire de validation pour
personnaliser le message qui sera posté sur les réseaux.

**Comment by Alex-D** [comment]
En fait, j'ai peur que ça flood assez vite.

On ne pourrait pas partir sur une sorte de récap plutôt ?

**Comment by Alex-D** [comment]
> On pourrait aussi prévoir un champ dans le formulaire de validation pour
> personnaliser le message qui sera posté sur les réseaux.

Ca nous empêcherais d'utiliser des services comme IFTTT qui automatisent tout à partir du RSS, ou alors il faudrait créer un flux de sortie dédié à ce genre de système centralisés.

**Comment by Alex-D** [comment]
Aussi, avant de faire ça, il faut intégrer OpenGraph et les Twitter Cards dans les pages des articles/tutos. Ça n'est pas très long, mais nécessaire si on veut un rendu qui a de la gueule et les références correctes vers l'auteur et autre par exemple.

**Comment by SpaceFox** [comment]
Définis : IFTTT, OpenGraph, Twitter Cards.

J'ai l'impression que tu cherches beaucoup trop loin et compliqué là.

> Ca nous empêcherais d'utiliser des services comme IFTTT qui automatisent
> tout à partir du RSS, ou alors il faudrait créer un flux de sortie dédié à
> ce genre de système centralisés.

Je vois pas le problème si ça nous permet d'éviter de faire un truc trop
"automatique".

**Comment by Alex-D** [comment]
**IFTTT** : https://ifttt.com/
Service qui permet l'automatisation de la transmission d'un flux vers un autre, par exemple d'un RSS vers Twitter, d'un RSS vers une page Facebook, d'un RSS vers ...

**OpenGraph** : http://opengraphprotocol.org/
Protocol permettant à certains services d'identifier les informations importantes de la page pour construire un rendu cohérent. Ne pas se retrouver avec le logo du site comme illustration d'un article (ou de l'avatar de l'auteur) par exemple.

**Twitter Cards** : https://dev.twitter.com/docs/cards
En gros des balises meta à rajouter sur les pages pour que Twitter affiche : l'auteur, l'image, le lien, la description, etc. De façon très contrôlée.

OpenGraph et Twitter Cards ne sont pas directement liés à l'automatisation mais permettent de rendre un minimum attractif un truc automatisé.

**Comment by Coy0te** [comment]
J'ai du mal à imaginer que ça soit "le bordel" en publiant uniquement les parutions d'articles et tutos, moi ça me paraît une bonne idée.

Pour les MAJ de contenus par contre, pour moi ça doit être sur action d'un valido uniquement, via une checkbox du genre "Cette MAJ est massive, faire sa promotion sur les réseaux sociaux". Parce que y'a tout de même beaucoup de MAJ non mineure et qui ne méritent pas un tweet.

**Comment by cgabard** [comment]
Il ne faut pas oublier que jusqu'à preuve du contraire, il est peut probable qu'il y ai des tonnes de publications. Déjà quand on arrivera a un tweet automatisé par jour, c'est a dire une publication majeur par jour, je serais hyper content.

**Comment by ShigeruM** [comment]
+1 Christophe. Dans l'immédiat je ne suis même pas sûr qu'il y ait besoin
d'automatiser. En tout cas perso, ça ne me gêne pas de tweeter/facebooker
(etc.) les premières parutions à la main. Equipe Comm power, toussa.

Cela dit cette issue a tout son intérêt parce qu'on y viendra, bien sûr.

**Comment by Alex-D** [comment]
Je ne connais pas le rythme de parution, mais certains sites publient tout leurs contenus et je les vire car ça flood réellement le flux.

Dans notre cas je me trompe certainement vu vos retours.

---

Dans un futur proche on peut s'en charger à la main.

---

Dans un futur moins proche, il faudrait créer un flux de sortie qui fournirait le flux des messages à poster sur les réseaux sociaux, avec éventuellement un petit message personnalisé proposé par l'auteur/le valido. Ce flux serait fourni à un système tel qu'IFTTT (ou Buffer ou un autre si vous en connaissez un mieux) qui se chargera de publier un message sur tous les réseaux branchés dessus, a priori Twitter, Facebook, G+

**Comment by cgabard** [comment]
Oui enfin le flood sera très relatif, comme je le disais, ça va déjà prendre probablement plusieurs semaines apres la sortie avant qu'on ai une publication quotidienne de contenu.

Si on reste inférieur à 1 tweet par jour, j'ai du mal à penser que beaucoup considerent ça comme du flood.

**Comment by Alex-D** [comment]
J'ai vu trop grand d'un coup, désolé pour mon optimisme :D

Je me voyais déjà avec un tweet tous les 3 minutes...

**Comment by SpaceFox** [comment]
Je me demande si au final ça n'aiderait pas l'équipe com. @ShigeruM, @ChantyTaguan ?

**Comment by ShigeruM** [comment]
Si, je pense aussi que ça nous aiderait.

**Comment by ChantyTaguan** [comment]
Hello,

Yep, ça pourrait nous aider, mais il faudrait pouvoir modifier les messages selon le RS idéalement.

**Comment by ChantyTaguan** [comment]
Vu qu'on utilise buffer manuellement, on pourrait l'utiliser pour automatiser. Du coup, pas besoin de coder un truc pour chaque RS (par contre le texte envoyé devrait quand même pouvoir être différent).

https://buffer.com/developers/api

**Comment by gustavi** [comment]
Je travaille là dessus. Je vous tient informé mais ça va prendre un certain temps.

**Comment by viki53** [comment]
Le truc c'est que les messages sont vachement personnalisés pour chaque publication, pour éviter de copier-coller le titre bêtement avec le nom de l'auteur (on ajoute des mentions, on rend parfois le titre plus explicite/intéressant…).

Du coup si c'est vraiment automatique ça peut poser problème niveau qualité. L'idéal serait d'avoir des alertes quand c'est ajouté à Buffer pour pouvoir éditer à la main si besoin (et si c'est pas fait, ça publie quand même).

**Comment by gustavi** [comment]
Je vais voir ce que je peux faire !

**Comment by ChantyTaguan** [comment]
Je plussoie fortement viki53 ! Ce serait top d'ajouter automatiquement un message type à la file Buffer et d'avoir une alerte (MP ou autre) pour qu'on pense à aller modifier/adapter/enrichir le message type.

Une autre possibilité (mais ce n'est pas nécessairement mutuellement excluant), ce serait d'ajouter des champs lors de la validation, qui permettraient au validateur d'ajuster le message pour chaque RS.

**Comment by GerardPaligot** [comment]
@gustavi Tu as pu faire quelque chose ici ? :)

**Comment by gustavi** [comment]
C'est dans ma TODO list, je vais bosser dessus ASAP

**Comment by gustavi** [comment]
Laquelle des deux options proposées par @ChantyTaguan vous semble la mieux ? ping @SpaceFox

**Comment by ShigeruM** [comment]
Pour moi l'ajout automatique dans Buffer, qui nous laisserait le temps de modifier le post tout en publiant un message par défaut si on n’intervient pas, c’est top. Et si en plus on a une notification d’ajout dans le Buffer, c’est encore mieux. Vraiment, ça serait vraiment, vraiment top.

**Comment by gustavi** [comment]
@ShigeruM deux questions : 
- Quel texte par défaut ?
- Je peux facilement faire des notifications mais qui notifier ? On a un groupe « communication » ?

**Comment by ShigeruM** [comment]
Je dirais quelque chose comme ça :

[Tuto | Article] : Titre - Sous-Titre URL #tag1 #tag2

Avec le sous-titre uniquement si le tout ne dépasse pas les 140 caractères. Pour les tag, il faut enlever les espaces éventuels. Et on affiche autant de tags que possibles, toujours dans la limite des 140 caractères. La priorité allant aux tags par rapport au sous-titre (autrement dit, il est préférable d'avoir les 3 tags d'un tuto en hashtag plutôt que le sous-titre).

Par exemple, pour le dernier tuto publié, ça donnerait : 

> Tuto : Comment alerter les secours ? - Introduction aux bilans pour les profanes du secourisme http://url #MondeDuTravail

Et pour le dernier article :

> Article : Dessinons une spirale de Fibonacci - Cet article présente le processus de construction d’un algorithme de dessin de la spirale de Fibonacci http://url #Graphisme2D #Algorithmique

Mais comme là le sous-titre est trop long pour la limite des 140 caractères, alors on le fait sauter, mais on garde les hashtags :

> Article : Dessinons une spirale de Fibonacci http://url #Graphisme2D #Algorithmique

Ce n'est qu'une proposition, à voir si ça va à tout le monde bien sûr.

Et pour les notifications, il existe un groupe Comm sur ZdS il me semble.

**Comment by viki53** [comment]
Pas sûr que le sous-titre soit important, en tout cas pour Twitter.

Sur les autres plateformes pourquoi pas (et encore, il y a la preview du lien en général), mais bon…

**Comment by ShigeruM** [comment]
Si le sous-titre rentre, je crois qu'il est important au contraire, car souvent c'est un petit trait d'humour qui rend alors le post (tweet ou autre) plus vivant, plus humain. Et dans d'autres cas il apporte de l'information sur le contenu partagé, ce qui ne peut pas faire de mal. Cela dit ce n'est clairement pas la partie du message à mettre en priorité. On ne le met que s'il rentre.

Reste la question de la date de publication. Je n'ai plus les infos précises en tête mais l'impact est maximal quand le post est fait entre 12h et 14h ou entre 18h et 20h (à confirmer). Il serait donc pas mal de planifier le post au prochain de ces créneaux suivant la publication du contenu.

**Comment by Arnaud-D** [comment]
Plutôt un sujet pour l'équipe de communication avan d'être un sujet technique. Je ferme.
