### ISSUE TITLE
La licence est mal placée sur petit écran si le bandeau "Béta/dev" est visible

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#5881]
**Description du bug**

La licence des contenus est mal placée quand on navigue avec un écran peu large (< 1024 px) et si la bannière "Version bêta" ou "Version locale" est affichée.

**Comment reproduire ?**

Sur une version du site qui contient une bannière (la bêta ou votre version locale), allez voir un contenu avec licence (article, billet ou tutoriel) et réduisez la largeur de votre fenêtre (< 1024 px). Le texte affichant la licence du contenu est trop haut.

**Capture d'écran**

![Capture d’écran - 2020-07-18 à 22 44 02](https://user-images.githubusercontent.com/5911232/87861756-74f17c00-c949-11ea-88d9-28bab236dc7d.png)

**Source du problème**

Le problème vient de l'attribut CSS `top` qui ne prend pas en compte la hauteur de la bannière (25 px).

**Comment by AmauryCarrade** [comment]
J'ai prévu de retravailler la façon dont cette bannière est affichée, ce qui corrigera tous ces problèmes de positionnement (qui ont la même source que ceux des menus des notifications, du profil, etc.). J'ai même commencé en local.

En attendant, vu que ce problème ne se présente qu'en local et sur la bêta, j'estime qu'il n'est pas prioritaire.

Il faudra aussi regarder comment est positionnée la licence, car il n'y a absolument aucune raison d'utiliser un positionnement absolu ici. Il est de toute façon prévu d'également retravailler l'en-tête des contenus, ça pourra être traité à cette occasion.

**Comment by Arnaud-D** [comment]
Corrigé par #5886.
