### ISSUE TITLE
Utiliser black pour formater (automatiquement) le code Python

### ISSUE THREAD

**Issue by AmauryCarrade** [zestedesavoir/zds-site#5884]
### Description du besoin

Actuellement, on utilise `flake8` pour vérifier le style de code Python, contrôler qu'il est bon, compatible avec la PEP8, etc. Ça marche, mais ça implique de faire le formatage à la main, de chercher quelles sont les règles, etc. C'est donc assez peu pratique, _surtout_ quand on n'a pas l'habitude de suivre un style de code Python et qu'on n'a pas en tête les règles de `flake8`.

### Description de la solution

Je propose de passer à [`black`](https://github.com/psf/black/blob/master/README.md) pour gérer le formatage du code, son style, et la vérification de tout ça. `black` a plusieurs avantages.

- Il est compatible avec le style PEP8 (c'est tout de même essentiel).
- Il **n'est pas configurable**. C'est un avantage car ça assure une cohérence globale à tous les projets qui l'utilisent, et ça évite de pinailler sur la pertinence de telle ou telle règle. C'est comme ça, épicétou.
    - En réalité, il y a un seul point configurable, la longueur des lignes, que je recommanderais de garder inchangée (de mémoire, 120 caractères).
- Il a [un style de code clairement documenté](https://github.com/psf/black/blob/master/docs/the_black_code_style.md).
- Il **permet de reformater automatiquement le code Python**. C'est un gros gain de temps : plus besoin de s'embêter, on lui demande de formater et _voilà_ ! D'autant plus que `black` vérifie, par sécurité, que l'AST du code reformaté est équivalente à celle du code d'origine.
- Il a été conçu pour produire des `diff` concis, ce qui facilite la relecture du code et sa revue.

### Contexte additionnel

Pour passer à `black`, je propose ceci, dans une unique PR.

- [ ] Reformater tout le code de ZdS avec `black`, automatiquement, dans un gros commit.
- [ ] Mettre la configuration de `black` dans un fichier `pyproject.toml` ([comme recommandé](https://github.com/psf/black/blob/master/README.md#pyprojecttoml)), notamment la longueur des lignes.
- [ ] Modifier la CI afin d'utiliser `black` pour tester le code (`black --check` permet de vérifier que le code est correctement formaté sans le reformater automatiquement).
- [ ] Ajouter un `make format` (ou similaire) qui reformate le code automatiquement.
- [ ] Permettre d'ajouter cette commande en _pre-commit hook_, afin de formater le code automatiquement quand on _commit_, ce qui permet concrètement de ne plus avoir à y penser. Pour ce faire, on peut : 
    - ou bien expliquer comment faire dans notre documentation ;
    - ou bien ([comme ce que suggère `black`](https://github.com/psf/black/blob/master/README.md#version-control-integration)), utiliser [pre-commit](https://pre-commit.com) pour automatiser l'ajout du _pre-commit hook_ (cela dit, ça fait une dépendance de plus pour l'environnement de développement) ;
    - ou les deux.

Bien sûr, tout ceci n'est que proposition pour le moment. Qu'en pensez-vous ?

**Comment by artragis** [comment]
il faut lui demander de ne pas utiliser la rationalisation des string car elle est incopatible pep 8 (il met tout en double quote)

**Comment by AmauryCarrade** [comment]
La PEP8 n'impose pas d'utiliser uniquement des guillemets simples. En réalité, elle ne donne _explicitement_ aucune règle à ce sujet, si ce n'est la consistance et la lisibilité.

> In Python, single-quoted strings and double-quoted strings are the same. **This PEP does not make a recommendation for this.** Pick a rule and stick to it. When a string contains single or double quote characters, however, use the other one to avoid backslashes in the string. It improves readability.
> 
> For triple-quoted strings, always use double quote characters to be consistent with the docstring convention in PEP 257.
> — _[PEP 8](https://www.python.org/dev/peps/pep-0008/#string-quotes) (graisse ajoutée)_

De plus, je trouve que [l'argumentaire de black sur la préférence des guillemets doubles](https://github.com/psf/black/blob/master/docs/the_black_code_style.md#strings) fait sens. Notamment avec la présence importante d’apostrophes en français (argument d'ailleurs repris par la PEP8). Es-tu en désaccord ? À titre personnel, je suis loin d'être sectaire à ce niveau, mais j'admets ma préférence pour la vision de black.

**Comment by artragis** [comment]
En vrai personnellement ça me gave d'avoir à faire gaffe à ça. Mais bon, le truc c'est que ça fait cinq ans maintenant qu'on gonfle les gens à ne mettre que des guillemets simples alors je trouve dommage de changer ça alors que black a un flag pour ne pas changer les strings. 

Pour "compatible pep8" en effet, c'est plutôt "compatible flake8" car notre config de flake 8 impose la règle de "guillemet simple sauf s'il y a un apostrophe".

**Comment by AmauryCarrade** [comment]
> Mais bon, le truc c'est que ça fait cinq ans maintenant qu'on gonfle les gens à ne mettre que des guillemets simples alors je trouve dommage de changer ça alors que black a un flag pour ne pas changer les strings.

J'entends l'argument, mais est-ce que le fait qu'on s'est certes embêtés depuis le début avec ça (essentiellement car on n'avait pas de formatage automatique) est un réellement bon argument pour continuer à s'embêter alors qu'on pourrait juste le gérer automatiquement comme le reste (cf. le tout début de ton message, d'ailleurs) ? Ça ressemble fort à un biais d'engagement, et ces derniers ne sont qu'assez rarement justifiés, je trouve, si on y réfléchit bien. Certes il y a eu cet effort mais de toute façon c'est passé et ça ne pourra plus changer. Par contre, l'avenir peut être modifié, lui, et quelque soit le choix fait ça ne changera rien au passé mais ça pourra améliorer le confort à l'avenir.

Mais ce n'est que mon avis.

**Comment by artragis** [comment]
Ok, comme black formatte automatiquement, il faudra donc : 

- laisser ce formattage des string
- retirer la vérification des strings dans flake 8

**Comment by AmauryCarrade** [comment]
Ne pourrait-on pas _remplacer `flake8` par `black`_ (qui peut aussi faire la vérification, `black --check`) ?

`black` en mode vérification ne précise pas quels sont les problèmes, mais il reformate automatiquement de toute façon.
Ou alors on garde `flake8` par précaution (en adaptant la config), comme vous voulez là dessus, je n'ai pas d'opinion forte.

**Comment by Arnaud-D** [comment]
Je suis assez partisan de confier tout à `black`. Je pense qu'avoir un outil qui gère la question du formatage (choix des règles, vérification et mise en forme) c'est se simplifier la vie. 

Et si en plus on peut avoir la configuration du *pre-commit hook* intégré à la configuration de l'environnement du développement, je suis entièrement acquis à la cause, même si on a besoin d'une dépendance en plus.

**Comment by AmauryCarrade** [comment]
Je vois juste une potentielle difficulté : les PR créées avant la PR de reformatage complet et fusionnées après risquent, si elles touchent au code python, d'avoir pas mal de conflits lors du rebase.

**Comment by Arnaud-D** [comment]
J'ai testé un peu ce que donneraient le passage à black avec les paramètres par défaut et l'effet sur des PR existantes. Ma conclusion, c'est qu'on devrait allonger les longueurs de ligne par défaut pour être proche de l'actuel (~90 dans black, ~120 actuellement), mais que les conflits ne devraient pas être trop pénibles à régler.

---

Voilà ce que j'ai fait concrètement.

En local, j'ai reformaté `dev` avec `black`, puis j'ai tenté de faire le *rebase* d'une de mes PR actuelles (après avoir passé `black` dessus aussi). La plupart des conflits que j'ai obtenu sont triviaux ; ils concernent principalement des lignes qui ont été changées pour normaliser les guillemets, parfois c'est pour des retours à la ligne qui diffèrent un peu. Les deux sont faciles à résoudre, même s'il faut s'y prendre tranquillement et attentivement.

Comme on était sur des lignes à ~120, on a beaucoup de lignes un peu longues dans le code et le découpage à ~90 les rend *bizarre*. C'est pas qu'une question d'habitude.

Un exemple avec un commentaire en fin de ligne qui se fait *bizarroïder* :

```python
self.content.licence = (
    self.request.user.profile.licence
)  # Use the preferred license of the user if it exists
```

Là, c'est une chaîne pour l'internationalisation qui se fait *bizarroïder* :

```python
messages.error(
    self.request,
    _(
        "Vous devez choisir au moins une catégorie, car ce contenu est déjà publié."
    ),
)
```

**Comment by AmauryCarrade** [comment]
Merci pour ce test ! Je suis d'accord qu'allonger la longueur de la ligne pour rester cohérent avec ce qu'on fait aujourd'hui serait bien. En plus c'est une des seules options configurables de `black` donc autant en profiter :D .

Pour les commentaires, ça va inciter à les mettre avant la ligne plutôt qu'en fin de ligne, ce qu'est je trouve plus lisible, donc c'est plutôt une bonne chose à mon avis.

Sinon, c'est assez rassurant effectivement, que ça ne se passe pas trop mal pour fusionner derrière :) .
