### ISSUE TITLE
Section "Tribune libre"

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#589]
En plus des sections "Tutoriels" et "Articles", on pourrait rajouter une section "Tribune libre" (ou autre terme à trouver), un peu sur le modèle des [journaux de LinuxFR](http://linuxfr.org/journaux).

La structure est la même que les articles : texte de l'auteur + espace de discussion en-dessous.

L'idée est d'avoir une section d'expression avec une modération très rapide et limitée à l'élimination des sujets quasi-vides (même pas un lien) ou illégaux.

Quelle différence avec les forums ? En gros, les tribunes sont une présentation de quelque chose (une actualité par exemple), les sujets des forums sont des questions ou des débats.

Idéalement, on a un système de vote (+1/-1) sur la tribune elle-même, et il est mis en avant dans la liste, pour pouvoir repérer facilement les journaux "intéressants" des autres.

**Comment by cgabard** [comment]
Je soutiens cette idée, ne serait ce que pour un test. Les articles ne nous permetront pas de suivre l'actualité facilement, ce que peu nous apporter ce format.

**Comment by vhf** [comment]
+1

**Comment by Alex-D** [comment]
Ca m'a l'air intéressant bien que j'ai un peu de mal à saisir le truc.

En clair, n'importe quel membre balance son truc, y a pas de validation a priori, mais une modération a posteriori ?

Et en gros les divers éléments sont affichés dans un ordre basé sur le nombre de votes et la date de publication, c'est bien ça ?

**Comment by cgabard** [comment]
Pour moi il peut y avoir une validation a priori mais juste pour filtrer le
illégal et spam. Mais rien sur le fond.

Pour l'affichage par date mais modulé pas les votes. Par exemple un
éléments classique dans la liste aurait son titre, Pourquoi-Pas une icône
et les deux première ligne. Un élément avec beaucoup de -1 serait réduit a
son titre seul et légèrement grisé (et le score bien en rouge).

L'idée est que l'affichage montre clairement ceux qui semblent intéressant
et ceux moins, sans pour autant censurer.
Le 23 mai 2014 12:12, "DEMODE Alexandre" notifications@github.com a écrit
:

**Comment by ShigeruM** [comment]
C'est original et j'aime bien le principe de la tribune libre !
Le 23 mai 2014 13:01, "Christophe Gabard" notifications@github.com a
écrit :

**Comment by SpaceFox** [comment]
> Et en gros les divers éléments sont affichés dans un ordre basé sur le
> nombre de votes et la date de publication, c'est bien ça ?

Ils sont affichés dans l'ordre, mais le nombre de votes est très visible. Comme
ce qui est fait sur LinuxFR, dans l'esprit.

**Comment by firm1** [comment]
Super idée, et en plus ça occupera les kiwis.

Le seul problème que je vois est technique. La tribune libre devrait apparaître sur la home pour mettre en valeur. Et actuellement le design n'est pas vraiment fait pour ça.

Donc on se dit V-battements ?

**Comment by cgabard** [comment]
Oui, de toute façon il est trop tard pour l'ajouter pour la sortie. Une fois la v1 faite, la personne motivé pour le dev pourrat le faire et on passera par la zone préprod avant de l'inclure.

**Comment by SpaceFox** [comment]
> La tribune libre devrait apparaître sur la home pour mettre en valeur.

Sans y réfléchir plus que ça, j'aurais dit que même pas.

Au moins dans un premier temps, je me contenterais d'une entrée du menu
principal (Tutoriels / Articles / Tribune / Forums) ; et si vraiment ça
marche on peut songer à refaire le design de la home.

**Comment by Alex-D** [comment]
De toutes façon, le design de la home est à refaire. Le contenu présenté a changé, sa forme également, etc. Du coup il faudra la refaire après la v1, on pourra en profiter à ce moment là pour mettre les X tribunes les plus "intéressantes" ou les plus récentes.

La validation n'est pas nécessaire si nous avons par exemple un bouton "signaler" qui nous permet d'être rapidement avertis (si on ne le vois pas nous-même) que la tribune est illégale/spam/...

Moi j'aime bien l'idée en tous cas, mais v1.1

**Comment by cgabard** [comment]
il y a une zep pas encore validé à ce sujet, on devrait le fermer non ?

**Comment by gustavi** [comment]
Je ferme. 

https://zestedesavoir.com/forums/sujet/976/zep-13-tribune-libre/ pour la suite des discussions.
