### ISSUE TITLE
La nouvelle version de Grammalecte ne marche pas avec le nouvel éditeur

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#5893]
**Description du bug**

On ne peut plus utiliser Grammalecte avec le nouvel éditeur. Avec Grammalecte 1.11.0 (sortir le 23 juillet 2020), Firefox 78.0.2 et le nouvel éditeur, on obtient l'erreur suivante :

![image](https://user-images.githubusercontent.com/35631001/88339859-135f5200-cd3b-11ea-87b4-ceefb6b5e660.png)

Avec la version 1.10.0 ou l'ancien éditeur, pas de problème.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Aller sur une zone de texte (en étant connecté).
2. Écrire un peu de texte.
3. Cliquer sur le bouton Grammalecte (et donc avoir le plugin installé).
4. Voir l'erreur après un petit temps d'attente dans la fenêtre de Grammalecte

**Comportement attendu**

Il faudrait que ça marche comme avant. On obtient la fenêtre de correction avec le texte à corriger qui s'affiche.

**Capture d'écran**

La console JS me raconte ça :

```
moz-extension://b4f5cd49-b3cd-499e-84f8-33b1292cd160/content_scripts/editor.js
ReferenceError
line: 143
sText is not defined
```

**Comment by A-312** [comment]
~~Si tu as le courage, le workflow de grammalecte est : http://code.grammalecte.net:8080/timeline~~

J'ai vu : http://code.grammalecte.net:8080/info/09c163c343c51ce8 Peut-être en remplaçant `what` ça devrait fonctionner

Si c'est bien ça, par politesse, il faudrait dire à l'auteur de grammalecte qu'il doit mettre à jour l'exemple suivant dans la doc : http://code.grammalecte.net:8080/doc/trunk/doc/API_web.md Tu peux passer sur le forum, il répond en moins de 24h (pense à activer les notifications par email quand tu créais un sujet) https://grammalecte.net/forum.php?prj=fr

```js
node.addEventListener("GrammalecteResult", function (event) {
    const detail = (typeof(event.detail) === 'string') && JSON.parse(event.detail);
    if (detail.sType  &&  detail.sType == "text") {
        let sText = detail.sText;
        ...
    }
}
```

Par : 

```js
node.addEventListener("GrammalecteResult", function (event) {
    const detail = (typeof(event.detail) === 'string') && JSON.parse(event.detail);
    if (detail.sType  &&  detail.sType == "text") {
        let what = detail.what;
        ...
    }
}
```

**Comment by A-312** [comment]
Au besoin si tu as besoin de tester sur une plus petite application : https://gist.github.com/A-312/7abe2114c1590e740711886542c80173

**Comment by A-312** [comment]
@Arnaud-D As-tu le même problème si tu essayes avec Chrome ? Je n'ai aucun soucis avec chrome, si tu n'as pas de problème sur chrome, demande sur le forum de Grammalecte (artragis à un compte).

EDIT : OK chrome est encore en 1.10

**Comment by A-312** [comment]
Au besoin, il y a ce gist pour essayer la solution : https://gist.github.com/A-312/7abe2114c1590e740711886542c80173

**Comment by Arnaud-D** [comment]
Le problème semble résolu avec Grammalecte v1.11.1, qui a notamment corrigé le nom de variable en question. Je ferme.
