### ISSUE TITLE
Editeur Markdown JavaScript

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#59]
Le markdown c'est bien beau, mais nous avons bien vu qu'il n'est pas forcément suffisant de base, et nous avons été obligé de rajouter nos extensions fait maison. 

Cependant, un débutant moyen, n'a pas envie de lire un tuto pour écrire dans un premier temps un texte proprement. Il ne va pas chercher midi à quartorze heure pour savoir comment on insère une balise code si on ne le guide pas un peu, bref, le débutant à besoin d'un coup de pouce. C'est la raison pour laquelle ZdS a besoin d'un éditeur de Markdown Javascript.

J'ai donc un peu prospecté quelques solutions existantes, selon quelques critères, et j'en ai retenu certains. A vous de me dire ce qui irait le mieux avec ZdS et son avenir. 

Est-ce possible d'avoir notre propre éditeur Markdown, qui gère directement toutes nos extensions ? Je pense par exemple à la création des tableaux qui peut être chiante, ou encore l'upload automatique des images, etc.
## Markit up

[Démonstration](http://markitup.jaysalvat.com/downloads/demo.php?id=markupsets/markdown)
### Dépendances
- JQuery
### Points forts:
- Opensource
- Previsualisation JS
### Points faibles:
- Markdown simple
## EpicEditor

[Démonstration](http://epiceditor.com/)
### Dépendances
- NodeJS
- JQuery
### Points forts:
- Gère le markdown de base
- Previsualisation JS
- permet l'écriture en plein écran avec d'un coté la version md et de l'autre le rendu
- Le thème est modifiable
- Possibilité d'import de fichier
### Points faibles
- Je ne le connais pas assez pour en dire plus

**Comment by cgabard** [comment]
Déjà, je profiterais de l'espace dispo sur la version desktop sur le coté ou en dessous pour mettre un petit aide mémoire rapide des commandes de bases (gras, italique, images, liens, etc.) + un liens vers le tuto préparé par shig

**Comment by Thunderseb** [comment]
Vous voulez vraiment un truc tout fait ? Car un script d'insertion de part et d'autre du curseur suffit. J'en ai un déjà fait si besoin. 

Pour la preview faite en JS, je pense que ce n'est pas une super bonne idée, car il risque d'y avoir des différences avec le rendu que va faire le script serveur. Le mieux serait de faire un preview "AJAX", en cliquant sur un bouton "Preview". 

La preview au cours de la frappe ce n'est plus trop tendance. Et c'est inutile les 3/4 du temps.

**Comment by firm1** [comment]
> Vous voulez vraiment un truc tout fait ?

Non, l'idéal comme je l'ai dis dans mon message c'est d'avoir un truc fait maison. Vu que personne n'en parlais depuis , je me disais, que personne ne voulais s'y coller ... 'fin bref.

> Pour la preview faite en JS, je pense que ce n'est pas une super bonne idée, car il risque d'y avoir des différences avec le rendu que va faire le script serveur. Le mieux serait de faire un preview "AJAX", en cliquant sur un bouton "Preview".

Yop, je suis d'accord.

Conclusion : on peut compter sur toi pour nous pondre cet éditeur ?

**Comment by Coy0te** [comment]
@Thunderseb : tu l'as fait en jQuery ? :p  Si tu peux l'adapter pour gérer les balises info/question/etc. qu'on a rajoutées à la syntaxe markdown, c'est parfait.

**Comment by Thunderseb** [comment]
Ouais, il va gérer ça ^^ 
Et pas de jQuery.

**Comment by Alex-D** [comment]
Pour le design de l'éditeur (CSS), ne t'embête pas, je m'en charge :)
Sur mobile, pas d'éditeur, sinon c'est trop lourd.

PS : jQuery <3 (il est déjà inclus, si tu veux t'en servir, tu peux...)

**Comment by Thunderseb** [comment]
A moins que jQuery propose des fonctions pour manipuler les Range et les Selection, ça ne me sert à rien :p

**Comment by Alex-D** [comment]
Nop, il ne sait pas faire ça, malheureusement :(

**Comment by Coy0te** [comment]
Ths, par pure curiosité, t'as une idée de comment tu vas gérer les tableaux ?

**Comment by Thunderseb** [comment]
J'ai une vague idée. 

Par contre, j'ai lu je sais plus ou que le md dans les cellules faisait foirer, donc est-ce qu'on garde l'horrible syntaxe md pour les tableaux ?

**Comment by cgabard** [comment]
En fait sur le site on gère deux syntaxe de tableau. Typiquement : 

```
First Header  | Second Header
------------- | -------------
Content Cell  | Content Cell
Content Cell  | Content Cell
```

La plus simple, qui normalement doit interpréter le markdown a l'interieur mais ne permet pas de sauts de lignes dans les cellules ni de rowspan ou colspan

Pour résoudre ça, nous avons une deuxième syntaxe qui l'autorise mais qui est plus chiante à écrire : 

```
+-------+----------+------+
| Table Headings   | Here |
+-------+----------+------+
| Sub   | Headings | Too  |
+=======+==========+======+
| cell  | column spanning |
+ spans +----------+------+
| rows  | normal   | cell |
+-------+----------+------+
| multi | cells can be    |
| line  | *formatted*     |
|       | **paragraphs**  |
| cells |                 |
| too   |                 |
+-------+-----------------+
```

Je crois que colspan et rowspan ne fonctionne pas simultanément.

Dans les deux cas, le markdown doit bien être interprété à l'interieur

**Comment by firm1** [comment]
@Ths : l'idée est que l'éditeur JavaScript devra permettre aux membres de crée ou de modifier le tableau. Étant donné que la syntaxe est particulièrement chiante, il faudrait que pour 
- creer un tableau :
  - on clique sur le bouton tableaux
  - une div interne s'ouvre
  - on ajoute/supprime des colonnes/lignes/entêtes
  - en appuyant sur OK, le tableaux se forme avec son contenu.
- modifier un tableau:
  - on sélectionne  le tableaux de base
  - on a la fameuse div qui s'ouvre
  - on fait les modifs et le tableau est recrée.

Voilà en gros comment je vois ça.

**Comment by Thunderseb** [comment]
@firm1 : c'est comme ça que je l'envisageais aussi. Le plus gros du taff va donc être de décoder cette syntaxe pour permettre la modification d'un tableau déjà créé.

**Comment by firm1** [comment]
Je te conseille de regarder du côté de [Fox JS](https://github.com/jamesgpearce/foxjs)

**Comment by Thunderseb** [comment]
Oh, ça a l'air pas mal comme truc !

**Comment by Coy0te** [comment]
@Thunderseb : si tu peux l'adapter pour gérer la syntaxe propre à la ligne de header (bordure faite avec des `===`), alors tu tiens là un outil génial ! Avec leur système de map, doit y'avoir moyen de se débrouiller pour faire un truc qui nous correspond. C'est pas gagné pour autant, mais c'est déjà une grosse épine en moins.

**Comment by firm1** [comment]
Coucou THS,

T'es arrivé à quelque chose finalement ? J'aurai quelques trucs en plus à te demander, mais faudrait déjà que tu ais fini la base.

**Comment by Thunderseb** [comment]
Une base est faite. Je t'écoute ^^

**Comment by cgabard** [comment]
Une PR pour qu'on puisse en profiter ? :p

**Comment by Thunderseb** [comment]
Non, là j'ai juste une base "standalone" ( http://nayi.free.fr/tutoriels/zform/zestemd.htm ). Il reste bcp à faire avant.

**Comment by cgabard** [comment]
Tiens c'est marrant que tu ai utilisé cette syntaxe pour le code alors que c'est celle que je trouve la plus moche :p 

BTW je pense que @firm1 parlait surtout de la gestion des tableaux qui est la partie probablement la plus chiante !

**Comment by Thunderseb** [comment]
Je la trouve plus jolie moi ^^ . 
Mais en fait, je pense donner la possibilité à l'utilisateur de personnaliser tout ça, en enregistrant les préférences avec localStorage. Idem pour l'ordre des boutons de la toolbar

**Comment by cgabard** [comment]
Bonne idée. On peut aussi stocker ça côté serveur pour rendre le truc portable de machine en machines.

**Comment by Alex-D** [comment]
Juste envie de dire : KISS...
On me le répète souvent, mais là c'est d'autant plus vrai : quel intérêt à
la personnalisation d'un éditeur par chaque utilisateur ?

**Comment by SpaceFox** [comment]
+1 Alex.

Le 20 janvier 2014 19:31, DEMODE Alexandre notifications@github.com a
écrit :

**Comment by firm1** [comment]
> Une base est faite. Je t'écoute ^^

En fait comme l'a bien deviné @cgabard ma demande concernait plutôt les tableaux. J'attends de voir comment tu implémentes cette base.

Par contre, j'aurai beaucoup des remarques sur ce qui est fait actuellement (quelques détails). Tu préférés avoir des remarques tout de suite, ou tu as déjà prévu de changer certaines choses ?

Autrement, je t'encourage à intégrer ce qui es déjà fait sur le dépot du projet. ça permet de suivre assez simplement l'évolution choses et d'avoir des retours rapides. On est en phase de développement, pas besoin que ça marche à 100% pour passer. Dans ton cas, les fichiers à modifier sont assez simples : 
- [Editor.js](https://github.com/Taluu/ZesteDeSavoir/blob/master/assets/js/custom/editor.js) : le fichier qui centralise les fonctions de l'éditeur
- [editor.part.html](https://github.com/Taluu/ZesteDeSavoir/blob/master/templates/misc/editor.part.html) : le fichier qui contient les boutons à rajouter au dessus de chaque TextArea

Toutes les textarea destiné à utiliser ton éditeur on un id ="id_text", ça peut changer, donc il faudrait en faire un paramètres.

**Comment by Thunderseb** [comment]
@Alex-D : pas beaucoup. Mais ça ne mange pas de pain et c'est déjà plus ou moins codé

@firm1 : ce qu'il faudrait en plus c'est une class = "" sur chaque textarea. Les boutons sont générés par Javascript donc à part l'inclusion du fichier .js, il n'y a rien à faire dans le HTML (hormis virer ce qui existe comme boutons ^^ ).

**Comment by firm1** [comment]
> ce qu'il faudrait en plus c'est une class = "" sur chaque textarea. Les boutons sont générés par Javascript donc à part l'inclusion du fichier .js, il n'y a rien à faire dans le HTML (hormis virer ce qui existe comme boutons ^^ ).

Tu voudrais que je mette une classe vide pour les textarea ?

**Comment by Thunderseb** [comment]
Oui, mais pas vide. Mets un truc du genre class="editor_textarea" ou je ne sais pas quoi. Il me faut un attribut pour que mon script puisse détecter les textarea à "habiller". Je peux détecter tous les textarea (comme le script actuel), mais peut être qu'à l'avenir certains ne devront pas recevoir de barre d'outils.

**Comment by firm1** [comment]
Oki. Dans ce cas, tu peux supposer que la classe concernée s'appellera class="md_editor".

Je compte sur toi pour mettre à jour le fichier [Editor.js](https://github.com/Taluu/ZesteDeSavoir/blob/master/assets/js/custom/editor.js)

**Comment by Thunderseb** [comment]
Btw, les menus dropdown seront au clic, et non au hover. J'avais fait un truc tout joli en full CSS avec :focus, mais je me suis aperçu au dernier moment que Chrome ne gérait pas :focus correctement... J'adore les produits Google. Bref, je vais refaire du "on click" en Javascript. 

@firm1 : je vais encore fignoler un peu et je le PR ASAP.

**Comment by Thunderseb** [comment]
@firm1 : tu sais m'indiquer un fichier CSS que je peux utiliser pour skinner un peu l'éditeur ?

**Comment by firm1** [comment]
Techniquement c'est à @Alex-D de skinner ça, mais si tu veux faire un truc temporaire, je vais te mettre à dispo un fichier que tu pourra utiliser dans à peu près 5 min.

**Comment by firm1** [comment]
Voila, il est dispo [ici le editor.css](https://github.com/Taluu/ZesteDeSavoir/blob/master/assets/css/editor.css)

**Comment by Thunderseb** [comment]
Quelques nouvelles : j'ai un peu mis en forme : http://nayi.free.fr/tutoriels/zform/zestemd.htm 
Faudrait que quelqu'un mette à jour la page du site avec la syntaxe markdown, surtout au niveau des balises de code. 
C'est possible de faire une image cliquable en syntaxe markdown ?

**Comment by firm1** [comment]
_"Un monde merveilleux serait un monde dans lequel, tout les devs mettent leurs codes dans le même repo ... Mais le monde n'est pas merveilleux :-)"_

Sinon, quelques remarques : 
- Les H5, H6 n'existent pas sur ZDS.
- Il me semble que Alex avait des icones prêtes à intégrer à l'éditeur (mas ça lui ferait déjà du boulot en moins).
- Les boites de dialogues, pour être uniforme, doivent garder le même style que les boites (que l'on a pas encore vu) du site.
- Les customs blocks (question, info, etc.) doivent être dans une liste déroulante. On ne les utilise pas tous les 4 matins.
- Et pour finir, à titre purement personnel, je trouve que la syntaxe des codes avec les tildes est franchement degueu :-P

**Comment by Coy0te** [comment]
> C'est possible de faire une image cliquable en syntaxe markdown ?

`[![alt](/path/image.ext)](url)`

**Comment by firm1** [comment]
Pour les images, il ne faut pas trop se prendre la tête je pense. Elles ont pour vocation d'être envoyée en ajax au serveur et donc, il n'y aura qu'un champ de type file un peu comme sur OC

**Comment by Thunderseb** [comment]
@firm1 : j'ai PR ce que j'ai fait. En esérant que ça marche ^^ . 

Btw, je n'ai plus de compte (et impossible de m'inscrive à cause du bug (cf. le Google Group)). 

Edit : et je m’aperçois que j'ai édité sur la master et non la dev. Je vais aller dormir.

**Comment by firm1** [comment]
Oui, j'ai vu ça. Beau boulot.

Par contre, la preprod (qui pointe sur la branche dev) n'est pas encore équipée de serveur de mail. Etant donné que c'est quand même chiant à installer, j'ai bien envie que quelqu'un me file des ids/pass gmail à mettre à la place.

**Comment by cgabard** [comment]
Concernant la syntaxe, faut voir ça avec shigerum mais en effet :p

**Comment by ShigeruM** [comment]
Je m'en occupe rapidement...
Le 30 janv. 2014 07:56, "Christophe Gabard" notifications@github.com a
écrit :

**Comment by firm1** [comment]
Je le note ici pour THS, il faudrait penser à rajouter : 
- la construction/edition d'un tableau
- l'édition de code source (dans une box séparée qui supportera la touche tab)

**Comment by Thunderseb** [comment]
Je peux faire supporter tab directement dans le textarea aussi. 
Mais il me faut les syntaxes exactes des blocs de codes, avec surlignement, numérotation et tout. J'ai plus suivi les débats.

**Comment by Coy0te** [comment]
Début de bloc code sans langage : 

``````
``` (ou équivalent du genre ~~~)
``````

Début de bloc code avec langage (java pour l'exemple, voir avec @cgabard ou @firm1 pour la liste des langages supportés et leurs noms exacts) : 

``````
```java
``````

Début de bloc code avec langage et surlignage (plage de lignes et ligne seule) : 

``````
```java hl_lines="5-7 12"
``````

Début de bloc code avec langage et décalage de numérotation : 

``````
```java linenostart="13"
``````

Début de bloc code avec langage et surlignage et décalage de numérotation : 
_(Attention ici : a priori le surlignage doit être défini **avant** le décalage de numérotation)_

``````
```java hl_lines="17-22 34" linenostart="13"
``````

---

Fin de bloc de code sans légende : 

``````
    ```
``````

Fin de bloc de code avec légende : 

``````
    ```
    Code: Extrait de l'API de machin truc
``````

---

Enfin, pour ce qui est des tableaux, perso ça ne me choquerait pas si ça n'arrive que dans une seconde version de ton outil. C'est une feature chiante à faire, et je trouve que le site peut être lancé sans, à partir du moment où on a une police à chasse fixe dans le textarea pour créer des tableaux simples à la main.

**Comment by geoffreyc** [comment]
Utilise le serveur mail su serveur live pour la reprod non? Ca sert a rien
d'avoir 2 serveurs mail.

2014-01-30 firm1 notifications@github.com:

**Comment by Thunderseb** [comment]
J'ai patché le fichier editor.js sur dev pour le rendre compatible avec le code HTML des articles. Il devrait aussi fonctionner avec les autres zform (car les class et id ne correspondent tjs pas, mais le script le gère désormais).

**Comment by Alex-D** [comment]
C'est une très mauvaise idée à mon sens : c'est au HTML d'être unifié et non au JS de s'adapter à 15 situations.

**Comment by firm1** [comment]
Petit check-up sur cette issue.

Des nouvelles en ce qui concerne la gestion des tableaux ? C'est clairement une feature de confort à ne pas négliger.

**Comment by Coy0te** [comment]
Up, _une fois_ ?

**Comment by Alex-D** [comment]
Up pour les dev back : ça serait-il possible d'avoir une API pour la preview ? Histoire d'y mettre un coup d'AJAX plutôt que de rafraîchir la page.

Merci !

**Comment by cgabard** [comment]
Ce ticket a maintenant une zep qui lui correspond. Je propose de le fermer tant que la zep n'a pas aboutit. Ça sert a rien de garder un ticket pour attendre une zep pas encore validé.

**Comment by firm1** [comment]
Pas faux.

Je ferme.

**Comment by Eskimon** [comment]
Lien vers la ZEP : http://zestedesavoir.com/forums/sujet/1009/zep-14-refonte-de-lassistant-dedition-markdown/
