### ISSUE TITLE
Mélange de la bêta et de la version brouillon quand elles sont identiques

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5906]
**Description du bug**

Quand on prend un contenu dont la version en bêta et la version en brouillon sont identiques (ce qui est vérifiable sur la page « Historique des versions » `/contenus/historique/ID/SLUG/`) alors les pages `/contenus/ID/SLUG` et `/contenus/beta/ID/SLUG` sont identiques et mélange ce qui touche à la bêta (bandeau d'information comme quoi cette page est une version en bêta, etc) et ce qui touche à la version brouillon (lien pour éditer le contenu, rajouter des sections, chapitres, etc).

Ligne sur la page « Historique des versions » qui indique que la version bêta et celle en brouillon sont identiques.

![image](https://user-images.githubusercontent.com/6664636/89402896-d1a9b080-d717-11ea-8c5b-a0b28987da44.png)

Capture d'écran du bug : mélange de ce qui touche à la bêta et à la version brouillon quand les versions sont identiques

![image](https://user-images.githubusercontent.com/6664636/89403114-20efe100-d718-11ea-86e1-30af25494895.png)

**Comportement attendu**

La page `/contenus/beta/ID/SLUG` ne devrait pas avoir ce qui touche à la version brouillon (lien pour éditer le contenu, rajouter des sections, chapitres, etc) et la page `/contenus/ID/SLUG` ne devrait pas avoir ce qui touche à la bêta (bandeau d'information comme quoi cette page est une version en bêta, etc).

Capture d'écran de la page `/contenus/ID/SLUG`

![image](https://user-images.githubusercontent.com/6664636/89403338-6dd3b780-d718-11ea-8f65-08c19c17ce25.png)

Capture d'écran de la page `/contenus/beta/ID/SLUG`

![image](https://user-images.githubusercontent.com/6664636/89403476-a4113700-d718-11ea-8d84-aec3dfad506c.png)

**Informations techniques**

- OS: Tous
- Navigateur: Tous
- Version/environnement de zds: dev

**Comment by Arnaud-D** [comment]
J'ai jeté un œil rapidement, et c'est moins facile que ce que j'aurai espéré, du moins pour moi.

## L'état actuel

Le _template_ est utilisé pour afficher n'importe quelle version d'un contenu qui n'est pas la version publiée. C'est un assez gros morceau (~800 lignes), avec beaucoup de logique, et qui a grandi de manière assez organique.

Le _template_ fait appel à plusieurs types de logiques d'affichage qui dépendent :
- des droits du visiteur (`is_staff` ou `can_edit` par exemple) ;
- des états du contenu (`content.in_beta` ou `content.in_validation` par exemple) ;
- du type de contenu (`content.is_opinion` ou `content.requires_validation` par exemple) ;
- du _commit_ (par exemple `content.sha_draft == version` ou `validation.version == content.current_version`) ;
- et probablement d'autres petites choses.

Toute cette logique est bien compliquée et d'une complexité difficilement gérable pour un humain standard.

## Une idée de solution

Beaucoup de logique devrait être remontée dans le code pour garder le _template_ bête. Ce n'est pas trivial du tout vu la complexité du _template_, avec beaucoup de risques de casser l'affichage existant. Pour compenser, il y a de belles opportunités d'amélioration de l'interace à saisir.

Ce que je pense être une bonne idée n'est pas trivial à metttre en place. Les étapes seraient les suivantes :
- identifier les éléments d'interface (par exemple le bloc licence, les blocs d'édition des auteurs, les tags, tous les différents menus, etc.) ;
- pour chaque composant, identifier ses modes d'affichage intrinsèques (par exemple la licence a à la louche quatre modes : pas de licence définie et pas de boutons de modif, pas de licence définie et un bouton de modif, licence définie et pas de bouton de modif, licence définie et bouton de modif) ;
- avoir des sous-_template_ par composant si la gestion de l'affichage est assez complexe ;
- mettre à jour le code du _backend_ pour sélectionner les bons modes pour chaque élément en fonction de la page qui est demandée.

En plus de facilité la résolution du présent bug, ça pourrait aussi ouvrir la voie pour des améliorations comme #5499 et #5498, voire des choses plus ambitieuse (j'ai parlé d'[une telle idée sur le forum](https://zestedesavoir.com/forums/sujet/13980/refonte-complete-de-linterface-des-contenus/#p219628)).

**Comment by Karnaj** [comment]
Ce n'est pas vraiment grave que la page d'historique affiche que les versions sont identiques si elles le sont. Par contre, c'est au niveau de l'affichage du contenu qu'on veut pouvoir distinguer les choses. 

En plus de ce que propose @Arnaud-D, je pense qu'il faudrait avoir un *template* par mode, donc un pour le brouillon, un pour la bêta, un pour la version publiée et un pour une version quelconque (potentiellement le même que celui du brouillon ?). L'idée c'est que si les différents composants sont suffisamment séparés dans différents sous-*templates*, il n'y aura plus qu'à les rassembler pour chaque *template*. Ça simplifie certaines choses. 
Par exemple, je pense qu'on ne devrait pas avoir accès à des liens de modification lorsqu'on est sur la version brouillon. Il n'y a donc que sur ce *template* que ces liens apparaîtraient. Les autres versions auraient juste un lien « voir la version brouillon » disponible si on a les droits.

Et on ne va pas parler de la *sidebar* trop remplie, je crois qu'il y a d'autres *issues* qui traitent de son découpage. :)
