### ISSUE TITLE
Erreur test test_import_tuto

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#591]
Hello,

Je ne parviens pas à aller au bout des tests, je rencontre l'erreur ci-dessous :

```
matthieu@matthieu-ubuntu:~/Django/ZesteDeSavoir$ python manage.py test
Creating test database for alias 'default'...
..........................................................E......
======================================================================
ERROR: test_import_tuto (zds.tutorial.tests.BigTutorialTests)
Test import of big tuto.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matthieu/Django/ZesteDeSavoir/zds/tutorial/tests.py", line 373, in test_import_tuto
    follow=False)
  File "/home/matthieu/.local/lib/python2.7/site-packages/django/test/client.py", line 483, in post
    response = super(Client, self).post(path, data=data, content_type=content_type, **extra)
  File "/home/matthieu/.local/lib/python2.7/site-packages/django/test/client.py", line 302, in post
    return self.request(**r)
  File "/home/matthieu/.local/lib/python2.7/site-packages/django/test/client.py", line 444, in request
    six.reraise(*exc_info)
  File "/home/matthieu/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/matthieu/Django/ZesteDeSavoir/zds/member/decorator.py", line 39, in _can_write_and_read_now
    return func(request, *args, **kwargs)
  File "/home/matthieu/.local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/matthieu/Django/ZesteDeSavoir/zds/tutorial/views.py", line 2212, in import_tuto
    request.FILES["images"], "")
  File "/home/matthieu/Django/ZesteDeSavoir/zds/tutorial/views.py", line 1988, in import_content
    mapping = upload_images(images, tutorial)
  File "/home/matthieu/Django/ZesteDeSavoir/zds/tutorial/views.py", line 1923, in upload_images
    pic.save()
  File "/home/matthieu/Django/ZesteDeSavoir/zds/gallery/models.py", line 142, in save
    image.save(temp_handle, 'png')
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1468, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python2.7/dist-packages/PIL/PngImagePlugin.py", line 578, in _save
    red, green, blue = transparency
TypeError: 'int' object is not iterable

----------------------------------------------------------------------
Ran 65 tests in 38.935s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

Je ne comprends pas d'où peut venir l'erreur car je l'ai aussi suis sur la branche dev. J'ai bien sûr installé tout les requirements (+ les quelques install du travis.yml). Quelqu'un est déjà tombé là-dessus ? Quelqu'un aurait une idée ?

Je suis un peu bloqué pour envoyer ma PR du coup, car évidemment je rencontre aussi l'erreur sur ma branche.

Merci !

**Comment by Alex-D** [comment]
Je pense que tu peux quand même faire ta PR, tu n'ajoutes a priori pas de bug puisque ça bug déjà sur la branche dev.

**Comment by ShigeruM** [comment]
Je n'ajoute pas " priori" de bug ça me plait moyen quand même...

**Comment by Alex-D** [comment]
Le bug là concerne le test "test_import_tuto" donc l'import de tutoriel. Or ta modification n'est pas liée, du coup je considère que ça ne peut pas affecter le résultat de ce test.

Si tu préfères attendre, tu peux également, je dis simplement que c'est très certainement inutile d'attendre.

**Comment by cgabard** [comment]
Non mais Matthieu a raison. Oui a priori il prendrait peu de risque mais techniquement ce bug présent dans dev peut lui masquer des erreurs que sa modif a généré.

**Comment by firm1** [comment]
C'est un problème de librairie d'images.

Essaye de lancer les commandes suivantes : 
`sudo apt-get install libjpeg libjpeg-dev libfreetype6 libfreetype6-dev zlib1g-dev`

et ensuite ré-installe pillow avec la commande
`sudo pip install --force-reinstall pillow`

PS : tu joue tous les tests en 39 secs ? tu en a de la chance. Moi ça me prend en général 4 min

**Comment by ShigeruM** [comment]
libjpeg8 au lieu de libjpeg, libjpeg8 déjà installé
libjpeg-dev n'était pas installé chez moi

Edit : sorry, fausse manip, je prenais juste des notes et le message est parti... Je fais un retour plus précis tout à l'heure.

**Comment by firm1** [comment]
De toutes façon si ça foire encore, c'est certainement au niveau d'une librairie. je ne me souviens plus s'il y'en a une dans le style `libpng` sous ubuntu.

**Comment by ShigeruM** [comment]
Désolé pour mon précédent message, je prenais juste des notes dans gmail pour faire un retour et le mail est parti. Je ne me serais pas permis de balancer un message si sec...

Bref, je disais donc que je n'avais pas trouvé ibjpeg, maus que libjpeg8 est déjà installé. Les librairies qui me manquaient étaient les libjpeg-dev et libfreetype6-dev.

Le problème est toujours le même malheureusement. Je vais chercher une solution de ce côté là en tout cas. Merci !

**Comment by firm1** [comment]
> Désolé pour mon précédent message, je prenais juste des notes dans gmail pour faire un retour et le mail est parti.

Il était pas sec ton mail.

un truc qui me viens à l'esprit, pour t'aider, si tu essaye d'installer pillow (``) normalement au beau milieu de tous les logs qu'il te craches tu as un tableau en ascii art (d'environ 5 lignes) à l'intérieur dans la console qui ressort. Si tu peux afficher ici ce tableau, ça aiderait surement à voir ce qui manque.

**Comment by ShigeruM** [comment]
Ah c'est bon ! `sudo pip install --force-reinstall pillow` ne faisait rien alors j'ai fait `sudo pip install --upgrade pillow` et cette fois les tests passent :

```
matthieu@matthieu-ubuntu:~/Django/ZesteDeSavoir$ python manage.py test
Creating test database for alias 'default'...
.................................................................
----------------------------------------------------------------------
Ran 65 tests in 38.738s

OK
Destroying test database for alias 'default'...
```

Merci beaucoup firm1 !

**Comment by firm1** [comment]
Cool. N'hésite pas à renseigner la doc concernant les libs.

**Comment by Eskimon** [comment]
J'en profite pour rajouter quelques packages (ubuntu) qui empeche les tests:
texlive-xetex
ttf-mscorefonts-installer

Et probablement d'autres que j'avais déjà... faudrait faire un test sur une installation fraiche pour déterminer ce qu'il faut vraiment.

AJOUT : Je suis sur Ubuntu et pandoc est en version 1.9 quand il est à jour... et apparemment ca bloque pour faire les tests...

**Comment by ShigeruM** [comment]
Je vais essayer de faire une petite compil de tout ça pour compléter la doc.

**Comment by firm1** [comment]
> Je suis sur Ubuntu et pandoc est en version 1.9 quand il est à jour... et apparemment ca bloque pour faire les tests...

Ah ouais, c'est vrai ça. Il faut une version de pandoc > = 10.xxx sinon, il y'a un truc qui passe pas. Les paquets debian sont encore en 1.9, du coup il faut compiler (faut pas avoir peur du mot, c'est jste une ligne de commande a taper) pandoc soit même avec cabal. Plus d'info sur la doc en ligne d'install de pandoc.

**Comment by Alex-D** [comment]
Au pire, une fois que Travis sera revenu, on pourra faire une PR pour voir le résultat des tests en ligne non ? C'est pas forcément optimal ça peut aider ceux qui n'auraient pas tous les outils/libs nécessaires à faire les tests en local.

**Comment by cgabard** [comment]
Oui mais effectivement ce n'est pas optimal quand un truc comme `cabal
install pandoc` peut suffire (avec un `sudo apt-get install cabal-install`
juste avant)

Christophe.

2014-05-23 17:45 GMT+02:00 DEMODE Alexandre notifications@github.com:

**Comment by firm1** [comment]
> Au pire, une fois que Travis sera revenu, on pourra faire une PR pour voir le résultat des tests en ligne non ? C'est pas forcément optimal ça peut aider ceux qui n'auraient pas tous les outils/libs nécessaires à faire les tests en local.

Euh ... tester son code par des PR ? si on peut éviter de faire des commits du style "next try on travis" juste pour tester un truc, ça serait cool
