### ISSUE TITLE
Le premier message du sujet est replié quand il est masqué

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5916]
Quand le premier message d'un sujet est masqué, il ne devrait pas être replié, car c'est très déroutant !

**Comportement observé** ([sujet du forum](https://zestedesavoir.com/forums/sujet/14470/pourquoi-les-media-ne-parlent-pas-davantage-des-traffics-de-drogue/))

![image](https://user-images.githubusercontent.com/6664636/91095287-6723ca80-e65c-11ea-836e-695efdebd5c4.png)

**Comportement voulu**

![image](https://user-images.githubusercontent.com/6664636/91095385-920e1e80-e65c-11ea-9234-2478c8b46d7e.png)

**Comment by arobase-che** [comment]
Je précise un problème.

Le message « Un ou plusieurs messages ont été masqués » après 90 jours se retrouve derrière l'avertissement « Ce sujet est sans activité depuis plus de 90 jours. Êtes-vous certain de vouloir y contribuer ? ».

Une image :

![2020-08-26-111335_1920x1080_scrot](https://user-images.githubusercontent.com/2202307/91285258-47d88a80-e78d-11ea-929e-1172ff289ca1.png)

PS: Il reste possible de voir le message en cliquant sur les lettres qui dépassent...

**Comment by A-312** [comment]
> Je précise un problème.
> 
> Le message « Un ou plusieurs messages ont été masqués » après 90 jours se retrouve derrière l'avertissement « Ce sujet est sans activité depuis plus de 90 jours. Êtes-vous certain de vouloir y contribuer ? ».
> 
> Une image :
> 
> ![2020-08-26-111335_1920x1080_scrot](https://user-images.githubusercontent.com/2202307/91285258-47d88a80-e78d-11ea-929e-1172ff289ca1.png)
> 
> PS: Il reste possible de voir le message en cliquant sur les lettres qui dépassent...

En lien avec #5799 et #5907 car c'est avec les alert que ça pose soucis (voir explication que je fais en commentaire dans l'issue précédemment cité).

Pour corriger le problème, plusieurs solutions :
 - Reset le CSS plus efficacement ;
 - Forcer la priorité des règles CSS en ajoutant des class ;
 - Revoir au cas par cas la gestion du padding/margin
