### ISSUE TITLE
Ctrl+Entrée+Entrée envoie deux fois le formulaire, ce qui génère une erreur

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5926]
**Description du bug**

Lors de l'écriture d'un message sur le forum ou dans les commentaires, si on appuie deux fois sur Entrée lors d'un envoi avec Ctrl+Entrée (ce qui donne Ctrl+Entrée+Entrée) alors on a une erreur. Si on est rapide, il s'agit d'une erreur interne au serveur (`OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')`) sinon il s'agit d'une erreur 403 (car l'antispam empêche de poster deux messages à la suite en moins de 15 minutes). 

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Allez sur un sujet du forum
2. Écrivez un message
3. Appuyez sur Ctrl+Entrée+Entrée
4. Constatez l'erreur interne ou l'erreur 403

**Comportement attendu**

Le formulaire ne devrait être envoyé qu'une seule fois.

**Solution envisagée**

Lors de l'appuie sur Ctrl+Entrée, supprimer l'événement JS pour que le deuxième appui sur Entrée ne fasse rien.

**Comment by Arnaud-D** [comment]
Je n'arrive pas à reproduire. Il faut être particulièrement rapide ? Tu utilises quel navigateur ? C'est sur les deux éditeurs, nouveau et ancien ?

**Comment by Situphen** [comment]
Je n'arrive plus à reproduire non plus donc je ferme.
