### ISSUE TITLE
Utiliser un lib json plus performante que celle de la lib standard

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#593]
La lib json standard étant assez lente par rapport à d'autres telle que yajl et ultrajson, l'idée est de passer sur une de ces libs en fonction des benchmarks.

ultrajson me parait la plus rapide, mais j'ai bien peur que son utilisation en C ne la rende pas tout a fait portable. A vérifier, je n'ai pas cherché plus que ça.

L'idée étant, avec un `pip install ujson` de remplacer tout les `import json` par `import ujson` afin de gagner pleins de milli-secondes sur la rapidité d'ouverture des tutos/articles.

**Comment by cgabard** [comment]
Il me semble, de mémoire, qu'il existe des libs plus rapide, en C, mais avec une interface compatible avec la lib json de base.

Cela pourrait vraiment être une bonne idée. Si une telle lib s'appelle toto tu peux faire des truc genre : 

``` Python
try:
    import toto as json
except ImportError:
    import json
```

Ce type de code a le gros avantage de permettre d'utiliser une lib plus rapide si elle est dispo et faire un fallback sur la lib de base si non dispo dans l'environement courant. TU peux meme rajouter un print si tu veux prévenir l'user qu'il devrait l'installer.

Cela permetrait de garder le code facilement portable pour les dev, meme si la lib utilisé n'est pas dispo sur leur install tout en permetant à la prod d'utiliser une plus rapide.

La seule contrainte etant d'avoir la meme interface.

**Comment by firm1** [comment]
Visiblement ujson et yajl ne s'installe pas a coup de pip sur windows.

`unable vcvarsall.bat`

**Comment by cgabard** [comment]
On s'en fout, manifestement ujson a la même interface que le module JSON de
base. Donc met le try/except comme montre montré et il pourra être utilisé
sur la prod. Pour les windowsien le module intégré sera utilisé mais on
s'en fout

**Comment by cgabard** [comment]
Si tu veux je m'occupe de la pr
Le 23 mai 2014 23:04, "Christophe Gabard" christophe.gabard@gmail.com a
écrit :

> On s'en fout, manifestement ujson a la même interface que le module JSON
> de base. Donc met le try/except comme montre montré et il pourra être
> utilisé sur la prod. Pour les windowsien le module intégré sera utilisé
> mais on s'en fout

**Comment by firm1** [comment]
Je veux bien, étant donné que je ne peux pas tester.

**Comment by Eskimon** [comment]
Pour ujson, il faudra revoir quelques bricoles dans le code car "'indent' is an invalid keyword argument for this function" comme confirmé github.com/esnme/ultrajson/issues/82... On peut s'en passer je suppose (de indent, pas de json)

Si je vire les indent pour que ca passe quand même, je me prend des problèmes d'encodage : 'ascii' codec can't decode byte...

Enfin, pour ceux que ca intéresse voila [un petit comparo de perf' des libs json](http://www.blangdon.com/writing/about/fastest-python-json-library/)

**Comment by firm1** [comment]
Les problèmes d'encodages je ne sais pas vraiment d'où ils viennent.

Mais il faudrait que le code reste compatible avec avec la lib standard JSON. Sinon ça va être galère je pense pour ceux qui sont sous windows et qui ont pas visual studio.

**Comment by Eskimon** [comment]
beh le "indent" c'est juste pour faire plus propre non ? (ce qui au final n'est pas dramatique car les fichiers sont pas supposé etre lu par des humains)...

Par contre le "encode" c'est plus chiant... (et vu l'heure je chercherais plus tard pourquoi ca arrive...)

**Comment by firm1** [comment]
En fait le JSON est censé être lu a très long terme (dans une v42) par des humains.
Pour pouvoir travailler en hors ligne complètement et pouvoir modifier soit même l'emplacement de ses fichiers.

**Comment by Eskimon** [comment]
si @cgabard  veut je veux bien prendre le relais sur cette issue, ca m'a l'air a m'a porté...

**Comment by cgabard** [comment]
Fais toi plaiz

**Comment by Eskimon** [comment]
pour cette histoire d'indentation, apparemment c'est pour une raison de performance que ca a été omis dans l'implementation... du coup si on veut garder la perf, je suppose qu'il faudra mettre un traitement supplémentaire pour l'output "quand c'est nécessaire" (quand un humain en a vraiment besoin) ou alors laissé l'humain reformaté (avec un IDE pas trop con c'est vite fait; mais moins user-friendly j'en conviens)

**Comment by cgabard** [comment]
Et les autres lib que ujson ?

**Comment by Eskimon** [comment]
Bin d'apres le lien que j'ai posté un peu plus tot, c'est ujson qui ecrase les autres donc ce serait dommage de s'en passer... apres je veux bien tenter avec les autres aussi; c'est pas pour le temps que ca prend (si elles sont installables via pip)

**Comment by firm1** [comment]
S'il faut trancher dans les autres libs, il faut viser celles qui ont une meilleure capacité en lecture. Vu qu'on veut optimiser au max la lecture.

N'hésitez pas à refaire les tests chez vous pour tester toutes les libs (les bechns ont peut être évolués avec les temps)

**Comment by SpaceFox** [comment]
> N'hésitez pas à refaire les tests chez vous pour tester toutes les libs (les bechns ont peut être évolués avec les temps)

Ou alors tout simplement ne pas être cohérents avec notre utilisation de l'outil. Par exemple, _tout le monde_ recommande PostgreSQL à MySQL sur le net.

**Comment by Eskimon** [comment]
[Un autre bench qui date un peu (un an)](http://stackoverflow.com/a/15440843) mais en remet une couche en faveur de ujson...

Si vous voulez benchmarké allez-y, perso avec mon niveau python je vais perdre plus de temps qu'autre chose à trouver un script potable :dancer: 

EDIT : et contre ujson, il y a un souci avec de l'encodage et ca sera pas forcément trivial de passer à coté (et ca compromet fortement ujson, c'est un choix fait pas l'auteur pour cause de perf)

**Comment by Eskimon** [comment]
Bon dans le le doute j'ai une branche de prete en local avec un remplacement de json par simplejson (et fallback json comme vu plus haut). L'avantage de cette lib c'est qu'elle est nativement présente dans python (en tout cas chez moi) et a part l'import j'ai rien touché au code et les tests passent toujours !

Si quelqu'un se sent de faire un comparo pour me dire que ca vaut le coup je pousserais déjà ca !

**Comment by firm1** [comment]
Mes résultats de benchs (éxécutés chez moi en local sur ubuntu et sur un fichier json de la taille d'un big tuto) pour les libs sont les suivants : 

```
firm1@firm1-S300CA:~$ python benchs.py 
Average run time over 500 executions repeated 4 times
--------------------
Library: ujson
Version: 1.33
ujson.dumps(data): 0.267822027206 (total) 0.000133911013603 (per call)
ujson.loads(data): 0.279688119888 (total) 0.000139844059944 (per call)
--------------------
Fastest dumps: ujson 0.267822027206 (total)
Fastest loads: ujson 0.279688119888 (total)
--------------------
Library: simplejson
Version: 3.3.1
simplejson.dumps(data): 0.552911281586 (total) 0.000276455640793 (per call)
simplejson.loads(data): 0.310170173645 (total) 0.000155085086823 (per call)
--------------------
Fastest dumps: simplejson 0.552911281586 (total)
Fastest loads: simplejson 0.310170173645 (total)
--------------------
Library: jsonlib2
Version: (1, 3, 10)
jsonlib2.dumps(data): 0.59682226181 (total) 0.000298411130905 (per call)
jsonlib2.loads(data): 0.469572782516 (total) 0.000234786391258 (per call)
--------------------
Fastest dumps: jsonlib2 0.59682226181 (total)
Fastest loads: jsonlib2 0.469572782516 (total)
--------------------
Library: json
Version: 2.0.9
json.dumps(data): 0.381250143051 (total) 0.000190625071526 (per call)
json.loads(data): 0.875679016113 (total) 0.000437839508057 (per call)
--------------------
Fastest dumps: jsonlib2 0.59682226181 (total)
Fastest loads: json 0.875679016113 (total)
--------------------
Library: yajl
Version: None
yajl.dumps(data): 0.4362180233 (total) 0.00021810901165 (per call)
yajl.loads(data): 0.502627134323 (total) 0.000251313567162 (per call)
--------------------
Fastest dumps: jsonlib2 0.59682226181 (total)
Fastest loads: json 0.875679016113 (total)

```

**Comment by Eskimon** [comment]
Bon, je vais recloner mon depot qui est pas mal bordelique avec les recentes modifs du front...
Du coup voici une branche qui integre simplejson avec fallback json. https://github.com/zestedesavoir/zds-site/tree/fix_593_simplejson
A vous de voir si vous voulez la reprendre, jouer avec etc...

**Comment by Alex-D** [comment]
Tu l'as bench pour voir ?

**Comment by Eskimon** [comment]
Nop, jm'y connais pas vraiment pour faire un bench réaliste... firm1 a fait des tests juste avant, ca avait l'air mieux mais je veux pas conclure...

**Comment by firm1** [comment]
Bon, c'est fait.

J'ai fais la séparation entre les libs de lecture json et les libs d'écriture json. Ce qui m'a permis d'utiliser ujson pour la priorité en lecture avec un fallback sur simplejson qui à lui aussi un fallback sur json standard.

Etant donné que ujson ne supporte pas l'indent pour l'écriture, j'ai directement opté pour json standard qui selon mes benchs ci-dessus, est le plus rapide en écriture après ujson.

Donc voili, c'est en prod, et ça va plus vite qu'avant avec ujson.

**Comment by Eskimon** [comment]
Chapeau alors !!
