### ISSUE TITLE
[Travis] Tache "Run lint for backend" du job 3, non fonctionnelle ?

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5942]
C'est peut etre un faux call, par exemple sur : https://travis-ci.com/github/zestedesavoir/zds-site/jobs/394836366#L2128
https://travis-ci.com/github/zestedesavoir/zds-site/jobs/394649743#L2136

Le job 3 de travis "Run lint for backend" ne semble pas s'actionner (normalement non car artragis avait bien insisté sur le fait de rien mettre en quiet). Il faudrait que vous vérifiez si elle le lint s'exécute correctement

https://github.com/zestedesavoir/zds-site/blob/a4bec364d629c9e694d13231996f9bfe956f09a8/scripts/travis_script.sh#L32

![image](https://user-images.githubusercontent.com/18501150/95024721-34bab380-0685-11eb-8c66-16fe90e42f98.png)

Bon vol ;)

**Comment by Arnaud-D** [comment]
S'il n'y pas d'erreurs, ce qui doit arriver pour que les tests passent, la commande ne renvoie rien. Et pour avoir testé rapidement chez moi, la config trouve bien des erreurs quand il y en a. Donc j'ai l'impression que tout est normal.

**Comment by Situphen** [comment]
Je ne vois pas non plus de soucis, donc je ferme.
