### ISSUE TITLE
Pouvoir signaler un commentaire comme spam

### ISSUE THREAD

**Issue by arobase-che** [zestedesavoir/zds-site#5962]
**Description du besoin**

Désormais on peut signaler un message sur le forum comme spam. Ainsi on a une alerte s'il est modifié. Et c'est super cool ! Franchement, ça aide.
Ça serait vraiment idéal de pouvoir faire ça également pour les commentaires.

![pas_d'alerte](https://user-images.githubusercontent.com/2202307/95659420-3f5fc780-0b21-11eb-8240-06e320525ef1.png)

Ici, on a un commentaire suspect qu'on ne peut pas signaler comme spam potentiel.

Merci !

PS: Si jamais c'est simple, je devrais pouvoir m'en occuper en m'inspirant de ce qui a été fait ?

**Comment by AmauryCarrade** [comment]
Bonne remarque, ce serait en effet utile de pouvoir ajouter ça ça sur tous les messages. Je vais regarder quand je pourrai (peut-être demain) à quel point c'est simple, et si oui ajouter des pistes à ce ticket :) . Étant donné que les commentaires et les messages du forum utilisent le même modèle, je m'attends à ce que ne ce soit pas trop compliqué.

**Comment by arobase-che** [comment]
Merci ! 👍

**Comment by AmauryCarrade** [comment]
En fait c'était pas _si_ simple que ça, et je m'en suis chargé.
