### ISSUE TITLE
https://zestedesavoir.com/forums/flux/sujets/rss/ retourne une erreur 500

### ISSUE THREAD

**Issue by AmarOk1412** [zestedesavoir/zds-site#5983]
**Description du bug**

les rss des sujets ont l'air morts

https://zestedesavoir.com/forums/flux/sujets/rss/

**Comment by Situphen** [comment]
C'est un bug connu causé par le passage de l'heure d'été à l'heure d'hiver. On ne garde pas le fuseau horaire des dates en base de données, donc ça crée une ambiguïté qui cause une erreur interne. Normalement dans quelques jours ça devrait s'arrêter tout seul (les sujets et messages publiés le jour du changement d'heure ne seront plus dans les flux RSS). La solution sur le long terme est de prendre en compte le fuseau horaire dans le code : mettre `USE_TZ = True` dans les paramètres et modifier tous les : 

```py
import datetime

now = datetime.datetime.now()
```

en

```py
from django.utils import timezone

now = timezone.now()
```

[Voir la documentation de Django concernant les fuseaux horaires](https://docs.djangoproject.com/fr/3.1/topics/i18n/timezones/)
