### ISSUE TITLE
Il est possible de choisir un pseudo invalide

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5984]
**Description du bug**

Il est possible de choisir un pseudo un peu farfelu comme par exemple `https://viki53.eu` qui est dans certains cas invalide : la fonction `reverse_lazy('tutorial:find-tutorial', args=(profile.user.username,))` qui permet de retrouver l'URL `'tutoriels/voir/(?P<username>[^/]+)/$'` retourne une erreur `NoReverseMatch`.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Se renommer en `https://viki53.eu`
2. Aller sur son profil et constater l'erreur interne

**Comportement attendu**

Aucune erreur interne.

**Solution possible**

Il serait possible d'ajouter une petite vérification lors du changement de pseudo pour refuser les pseudos invalides : 

```py
try:
    reverse_lazy('tutorial:find-tutorial', args=(profile.user.username,))
except NoReverseMatch:
    # Refuser le pseudo
```

**Comment by AmauryCarrade** [comment]
Plutôt que cette idée de validation un peu tordue, ne serait-il pas plus pertinent de vérifier le pseudo [à l'aide du validateur qui va bien](https://docs.djangoproject.com/fr/3.1/ref/contrib/auth/#validators), et de s'assurer que ce validateur (qui serait également utilisé à l'inscription, donc) exclue bien les _slashes_ ?

**Comment by SpaceFox** [comment]
L’avantage de la solution proposée, c’est qu’elle garantit que le système va bien se comporter.

J’avoue que je suis dubitatif devant la description qui est faite de `UnicodeUsernameValidator` dans la documentation : tous les caractères bien formés sont des caractères Unicode (en supposant que le système tourne en Unicode pour les entrées-sorties). Du coup le validateur n’exclut pas grand-chose, et en particulier n’exclut pas l’exemple (qui n’utilise que des caractères ASCII d’ailleurs).

**Comment by Migwel** [comment]
Le problème semble vraiment venir du `/` non ? (en tout cas quand je reproduis ça, ça semble venir du slash). Dans le validateur existant, on interdit déjà l'utilisation de virgule donc on pourrait simplement ajouter une condition interdisant le slash ?

Si ça semble être une bonne idée, je peux faire ça.

**Comment by Situphen** [comment]
> Le problème semble vraiment venir du `/` non ? (en tout cas quand je reproduis ça, ça semble venir du slash). Dans le validateur existant, on interdit déjà l'utilisation de virgule donc on pourrait simplement ajouter une condition interdisant le slash ?
> 
> Si ça semble être une bonne idée, je peux faire ça.

C'est effectivement une solution donc tu peux faire ça ! :)
