### ISSUE TITLE
Les pseudos trop long débordent du profil

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5989]
**Description du bug**

Quand un pseudo est trop long, il déborde du profil ce qui n'est pas très esthétique et complique l'utilisation de la page.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Créer un compte avec un pseudo assez long (par exemple `kristinaltidor13kya`)
2. Aller sur son profil
3. Constater que le pseudo déborde

**Comportement attendu**

Le pseudo ne dépasse plus de l'écran (soit car de plus petite taille, soit car tronqué et sur plusieurs lignes).

**Capture d'écran**

Voici une capture d'écran sur mobile mais le soucis peut être aussi visible sur ordinateur potentiellement.

![Capture d'écran sur mobile](https://user-images.githubusercontent.com/6664636/98648956-3ee06980-2337-11eb-9935-e30d2cb376c1.png)

**Comment by mehdbnaleg** [comment]
J'aimerai participer, mais j'ai du mal a voir les modifications nécessaires. Je sais qu'il faut éditer `assets/scss/pages/_flexpages.scss` qui affecte le template `templates/member/profile.html`. Cependant, la seule solution que j'ai pu trouver est de réduire la taille de la police, ce qui ne serait pas souhaitable à mon avis. J'aimerai avoir une meilleure idée de ce qu'on veut vraiment faire, pour que je puisse trouver une solution adéquate.

Merci !

**Comment by Arnaud-D** [comment]
@ToxicScorpius Je pense qu'il y a des choses à explorer du côté de la propriété CSS [text-overflow](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow), notamment avec la valeur `ellipsis`.
