### ISSUE TITLE
Les big-tutos récents n'ont pas de temps de lecture estimé

### ISSUE THREAD

**Issue by AmauryCarrade** [zestedesavoir/zds-site#5995]
**Description du bug**

Les tutoriels récents affichent tous le même temps de lecture : « moins d'une minute ».

**Comment reproduire ?**

1. Aller sur un tutoriel récent (actuellement, les deux derniers semblent affectés, j'ai l'impression que ce sont ceux publiés depuis la v29 mais à confirmer).
2. Constater que le temps de lecture est de « moins d'une minute » au lieu d'un temps plus cohérent.

**Comportement attendu**

Le temps de lecture est cohérent.

**Capture d'écran**

![Exemple sur le tutoriel de la preuve de programmes C](https://user-images.githubusercontent.com/1417570/99922391-a7b0e400-2d30-11eb-9772-6bfddbaa9070.png)

**Informations techniques**

- Version/environnement de zds : production (v29)

**Cause suspectée**

Il semblerait que le temps de lecture ne soit tout simplement pas correctement stocké lors de la publication, pour une raison ou une autre. Mais que pour les tutoriels, ce qui est d'autant plus bizarre… les articles ne semblent pas affectés.

**Comment by Situphen** [comment]
La commande `python manage.py adjust_char_count --id {{ id_du_contenu }}` me renvoie `It got None letters.` pour « La programmation en C++ moderne » et « Introduction à la preuve de programmes C avec Frama-C et son greffon WP » respectivement un big tuto mis à jour le 31 août et un moyen tuto mis à jour le 7 septembre.

Il faut investiguer ce qu'il se passe dans la fonction `render_markdown_stats` de `zds/utils/templatetags/emarkdown.py` pour ces deux contenus.

**Comment by artragis** [comment]
problème de payload trop lourde?

**Comment by Situphen** [comment]
La commande `python manage.py adjust_char_count --id {{ id_du_contenu }}` fonctionne bien sur la bêta pour les gros contenus suivants :  

- «  Introduction à la preuve de programmes C avec Frama-C et son greffon WP »
- « La programmation en C++ moderne »
- « Arduino : premiers pas en informatique embarquée »
- « Le langage C »

Par contre, elle échoue pour « Les réseaux de zéro » avec cet avertissement : 

```
WARNING zds.tutorialv2.models.database could not get file /opt/zds/data/contents-public/les-reseaux-de-zero/extra_contents/les-reseaux-de-zero.md to compute nb letters (error=('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
```

@artragis @philippemilink À l'occasion, ce serait bien sur le serveur de prod de lancer la commande pour les contenus qui n'ont pas d'estimation de temps de lecture. Par contre, il faudra modifier la commande pour ajouter un `sleep()` de quelques secondes au moins pour éviter de surcharger le serveur ! 

Soit on lance la commande sur tous les contenus publiés : `/opt/zds/wrapper adjust_char_count`.
Soit on lance la commande seulement sur ceux qui n'ont pas d'estimation de temps de lecture : 

- Ouvrir le shell de Django `/opt/zds/wrapper shell`
- Lancer ce code dans le shell : 
  ```py
  from zds.tutorialv2.models.database import PublishedContent
  PublishedContent.objects.filter(must_redirect=False, char_count=None).count()
  ",".join(str(elem) for elem in PublishedContent.objects.filter(must_redirect=False, char_count=None).values_list("content_pk", flat=True))
  ```
- Lancer la commande `/opt/zds/wrapper adjust_char_count --id RÉSULTAT_DE_LA_COMMANDE_PRÉCÉDENTE`

**Comment by philippemilink** [comment]
Je retrouve ce ticket en triant mes vieux mails de GitHub liés à ZdS.

Je viens de lancer la commande pour calculer le nombre de caractères des publications des trois publications qui n'en avaient pas : 
- [Introduction à la preuve de programmes C avec Frama-C et son greffon WP](https://zestedesavoir.com/tutoriels/885/introduction-a-la-preuve-de-programmes-c-avec-frama-c-et-son-greffon-wp/) (tutoriel)
- [Ne loupez plus une publication : utilisez les flux RSS !](https://zestedesavoir.com/articles/2428/ne-loupez-plus-une-publication-utilisez-les-flux-rss/) (article)
- [Soyons curieux !](https://zestedesavoir.com/billets/3522/soyons-curieux/) (billet)

Ça a fonctionné pour les 3 contenus.

Sur la bêta, ça a aussi fonctionné pour le tutoriel "Les réseaux de zéro".

Les contenus récents (ceux listés sur la page d'accueil) ont bien un temps de lecture.

Je peux fermer ce ticket ?

**Comment by Situphen** [comment]
Il me semble aussi que ce problème a été corrigé et que l'estimation du temps de lecture fonctionne bien maintenant. Je ferme, on rouvrira plus tard si besoin.
