### ISSUE TITLE
Make an installation script for local

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#6]
If any user want to test local version of zds, it's too hard to install all libraries manually. For this reason, zds need a deployement script for local.

The script instructions are :
- install/update python, django, pip, requirement, etc.
- create local database (sqlite)
- init test data
- ...

**EDIT (gustavi) : le débat continue sur le forum : https://zestedesavoir.com/forums/sujet/1853/installation-dune-instance-locale-de-zds-en-une-ligne/**

**Comment by geoffreyc** [comment]
Alors j'ai une permiere version du script a faire essayer:
http://www.speedking.eu/zds/install.sh

1 - C'est une version 0.0.0.1, ya quelques trucs a rajouter, j'en suis conscient.
2 - Ca devrait marcher sur toutes les distros linux
3 - Pour le moment c'est un clone en https, donc faut rentrer ses logins github, je mettrais en place le ssh plus tard
4 - Le script met en place un virtualenv pour vous, la structure des dossiers: zds/zestedesavoir/{racine du repository}
5 - Si votre "python" ne pointe pas vers "python2.7", if faut lancer le script comme ca:
"sh install.sh /user/bin/python2.7" sinon le virtualenv sera créé avec le mauvais python
6 - feedback? :)

**Comment by geoffreyc** [comment]
PS: LINUX ONLY

**Comment by cgabard** [comment]
Je testerais un de ces jours sur mon arch à la maison...

Pour le point 5, si tu es sur du Linux only, tu peux utiliser dans ton script `/usr/bin/env python2.7` en lieu et place des python pour lancer la bonne version quelque soit le python par defaut

**Comment by cgabard** [comment]
Pour info sur mon ubuntu de boulot, ça deconne. En fait il semblerait que bien que mon python par defaut soit le 2, pip utilise le 3...

Apres j'ai un peu de mal a voir comment tu gère tes droits. pip, vu que tu ne précise pas `--user` va tenter d'installer virtualenv dans `/usr/local/lib/python2.7/dist-packages/` qui va necessiter les droits root. Mais si je lance le script avec un sudo, il va tout me faire avec cet user et je vais avoir mon environnement attribué à root, non ? ou j'ai loupé un truc ?

**Comment by geoffreyc** [comment]
Je pense que je vais revoir tout ca ce soir, vous êtes deux a avoir des
soucis au niveau de ça. Mon soucis semple etre qu'entant que simple user
sous debian, j'ai eu de base access a pip, ce qui ne semple pas être le cas
pour tout le monde.

2014-04-14 15:56 GMT+01:00 Christophe Gabard notifications@github.com:

**Comment by cgabard** [comment]
J'ai accès a pip (mais qui veut se lancer avec python3, ça je ne sais pas
si ce n'est pas moi qui ai fait de la merde quelque part dans mon install
au boulot).

Pour le reste, même quand je modifie pip par pip2, comme je le disais, il
tente de l'installer a un endroit protégé en ecriture. Rajouter un `--user`
pourrait peut être suffir

Christophe.

2014-04-14 17:01 GMT+02:00 geoffreyc notifications@github.com:

**Comment by cgabard** [comment]
Je teste et je te dis

Christophe.

2014-04-14 17:07 GMT+02:00 Christophe Gabard christophe.gabard@gmail.com:

**Comment by geoffreyc** [comment]
Thanks :)

2014-04-14 16:08 GMT+01:00 Christophe Gabard notifications@github.com:

**Comment by firm1** [comment]
> Mon soucis semple etre qu'entant que simple user sous debian, j'ai eu de base access a pip

Une distribution debian (ou autre linux) ne vient pas par défaut avec pip ni avec easy_install. 

Pour faire les choses proprement, il faudrait suivre les étapes suivantes : 
- si l'utilisateur n'a pas python installé, lui demander les droits et installer python 2.7
- si l'utilisateur n'a pas git, lui demander les droits et installer git
- installer easy_install et pip pour l'user
- installer virtualenv
- activer l'environnement sandboxé
- installer zds (vérifier le path de python si besoin pour lancer python à partir du bon fichier)

**Comment by cgabard** [comment]
Avec `pip2 install --user virtualenv` cela passe (il va au clone de dépot
en tout cas)

Christophe.

2014-04-14 17:15 GMT+02:00 firm1 notifications@github.com:

**Comment by cgabard** [comment]
et du coup je suis obligé de lancer virtualenv, à la ligne suivante, par
`python -m virtualenv ...` ce qui peut donner
`/usr/bin/env/python2 -m virtualenv ...` de manière portable

Christophe.

2014-04-14 17:20 GMT+02:00 Christophe Gabard christophe.gabard@gmail.com:

**Comment by cgabard** [comment]
Alors voici le script qui, a mon boulot, m'a permit de l'installer (Ubuntu 13.10 32b) avec virtual env

```
#!/bin/bash
clear
pyversion=""
if [ "$1" != "" ]; then
    pyversion="-p $1"
fi
dir="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
pip2 install --user virtualenv
/usr/bin/env python2 -m virtualenv --no-site-packages $pyversion zds
cd "$dir/zds"
. bin/activate
git clone "https://github.com/Taluu/ZesteDeSavoir.git" "zestedesavoir"
cd zestedesavoir
easy_install lxml
pip2 install -r requirements.txt
python manage.py syncdb
python manage.py migrate
python manage.py loaddata fixtures/users.yaml
python manage.py loaddata fixtures/forums.yaml
python manage.py loaddata fixtures/topics.yaml
python manage.py loaddata fixtures/mps.yaml
python manage.py loaddata fixtures/categories.yaml
```

**Comment by geoffreyc** [comment]
http://speedking.eu/zds/install.sh
Allez hop, nouvelle version, qui devrait mieux marcher. Le script commence
par chercher toutes les dépendances requises (python2.7 python-pip
python-dev build-essential libxml2-dev libxslt1-dev git) si il ne les
trouve pas, il s’arrêtera en proposant a l'utilisateur de les installer lui
même (en lui donnant la commande a exécuter).
En gros si le scipt ne trouve aucuns des programmes ci dessus, le script va
ouputer ca:
You will need to install the missing dependencies before carrying on. Run
the following command to install them:
apt-get install python2.7 python-pip python-dev build-essential libxml2-dev
libxslt1-dev git

J'ai fait ca pour eviter d'avoir des commandes "apt-get" dans le script en
lui même. L'utilisateur a la choix d'installer ca comme il veut, on lui
donne toutes les infos.

Apres avoir tout installer, le script devrait pouvoir passer au reste de
l'installation en le relançant. Plus besoin de passer la bonne version de
python en paramètre, 2.7 sera normalement utilisé automatiquement.

Ca a marché pour moi sous ubuntu 13.7 et debian 7.4 (clean install)

On Mon, Apr 14, 2014 at 5:47 PM, Christophe Gabard <notifications@github.com

**Comment by Ge0** [comment]
Ah navré, j'avais oublié de tester ton script hier soir @geoffreyc 

Ce soir sans faute (le nouveau cette fois ;p)

**Comment by firm1** [comment]
> ubuntu **13.7**

je suis le seul que [sa choque](http://doc.ubuntu-fr.org/versions) ?

**Comment by SpaceFox** [comment]
Pas moi, j'utilise Debian ou Mint Debian Edition :D

2014-04-15 15:26 GMT+02:00 firm1 notifications@github.com:

**Comment by geoffreyc** [comment]
Typo, c'est bien 13.10, j'ai mélangé avec debian 7, mes doigts ont fait ce
qu'ils voulaient.

**Comment by cgabard** [comment]
On en est où de cette issue ?

**Comment by firm1** [comment]
la dernière fois que j'ai essayé le script linux il marchait pas.

**Comment by cgabard** [comment]
Est ce que le script est encore necessaire ?

Christophe.

2014-05-22 10:48 GMT+02:00 firm1 notifications@github.com:

**Comment by firm1** [comment]
Je sais pas, c'est toujours bien d'avoir un script  lancer pour deployer tout le bousin. Mais il n'a jamais été nécessaire je pense.

**Comment by Eskimon** [comment]
Perso chez moi si le script se contentait de reprendre les étapes du readme se serait suffisant...

**Comment by geoffreyc** [comment]
C'est le que le script fait, en soit. Le dernier message en date ou je
demandais des retours n'en a point eu, je n'ai pas travailler dessus depuis.

**Comment by firm1** [comment]
En même temps, le script pour les linux user c'est un peu overkill quand même. Dans le readme, les instructions tiennent en quatre lignes (faudrait rajouter le chargement de fixtures).

@geoffreyc je sais plus a quel niveau ça merdait chez moi, mais ça merdait, je te fais un rapport de bug quand je le teste.

**Comment by geoffreyc** [comment]
@firm1 : Apres si sur linux c'est pas vraiment la peine (c'est vrai qu'au
final, c'est 4 lignes a suivre), autant pas se faire chier. Serait plus
utile d'en faire un pour windows, mais je ne m'y connais pas assez en bash
dos pour le faire.

2014-05-22 10:07 GMT+01:00 firm1 notifications@github.com:

**Comment by ShigeruM** [comment]
Suf erreur de ma part, il y a aussi les install dans le travil.yml à faire
avant de pouvoir lancer une instance locale.

J'ai eu à installer des trucs pour pandoc aussi (je vais créer un ticket à
ce sujet).

**Comment by Eskimon** [comment]
`<troll>`Pis tfacon faire du dev' sous windows :sifflote: ... `</troll>`

**Comment by geoffreyc** [comment]
J'ai envi de dire, tant que l'env est bien paramétré, linux oui windows,
pour taper du code, c'est kiff-kiff ^^

**Comment by firm1** [comment]
> Suf erreur de ma part, il y a aussi les install dans le travil.yml à faire
> avant de pouvoir lancer une instance locale.

Oui oui, faudrait préciser qu'il faut installer pandoc et texlive ainsi que les polices microsoft pour linux.

**Comment by ShigeruM** [comment]
Ah bah j'ai fait une issue pour texlive avant de voir ton commentaire,
désolé.

**Comment by gustavi** [comment]
On a pas un doublon avec https://github.com/zestedesavoir/zds-site/issues/1350 ? La discution semble plus aboutie là bas qu'ici.

**Comment by firm1** [comment]
Non non pas vraiment.

Ici on essaye de créer un script de déploiement pour une version locale. Là
bas, on parle de VM, containers, docs, etc.
Le 20 oct. 2014 12:33, "Laville Augustin" notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
En fait, si dans l'issue #1350 on opte pour la solution docker, cette tâche ci-présente n'aurait plus raison d'être.

**Comment by firm1** [comment]
Bah non justement docker c'est pour ceux qui ont les ressources materielles
pour installer un container.

Docker ne doit pas entraver le support d'installation de base.

**Comment by GerardPaligot** [comment]
Jusqu'à présent, nous sommes partis du principe que tous les contributeurs de Zeste de Savoir utilise virtualenv pour contribuer, la chose pourrait évoluer pour docker (s'il s'avère qu'il est "meilleur"). Dans ce cas (et, bien entendu, uniquement dans ce cas), cette issue n'aurait plus raison d'être.

> Bah non justement docker c'est pour ceux qui ont les ressources materielles pour installer un container.

Elles sont plutôt logicielles et elles sont minimes.

**Comment by firm1** [comment]
> Jusqu'à présent, nous sommes partis du principe que tous les contributeurs de Zeste de Savoir utilise virtualenv pour contribuer, la chose pourrait évoluer pour docker

La différence entre virtualenv et docker c'est que l'un consomme des ressources et l'autre non.

L'idée de l'issue actuelle c'est en gros de faire exactement ce qui est marqué dans la doc d'installation tout simplement. Dire que tu remplaces ça par docker, c'est supposer que Docker consomme rien en mémoire.

Virtualenv contrairement a docker n'intervient qu'en one-shot pour cloisonner ton environnement. Ils ne sont donc pas comparable ici selon moi.

**Comment by GerardPaligot** [comment]
L'idée derrière docker, c'est justement de consommer le moins possible (il consomme vraiment peu) contrairement à ses concurrents, les machines virtuelles. Mais on s'éloigne du sujet de cette issue.

**Comment by firm1** [comment]
Je connais bien Docker (je l'utilise même très souvent), mais le problème est là : 

> c'est justement de consommer le moins possible

Il consomme le moins possible, mais il consomme quand même. C'est bien pour ça que je sépare les deux, pour garder un support pour ceux qui n'ont pas les moyens de travailler avec docker (ou n'importe quel autre outil)

**Comment by GerardPaligot** [comment]
Avons-nous une idée d'une configuration minimale (hardware et/ou software) pour l'utilisation de docker ?

**Comment by Luthaf** [comment]
> Avons-nous une idée d'une configuration minimale (hardware et/ou software) pour l'utilisation de docker ?

Pour linux : un noyau récent (>3.8). Pour OsX et Windows, la config de VirtualBox (pour faire tourner la VM avec le noyau linux), et un téléchargement de 150M.

Les dépendances formelles sont listées là : http://docs.docker.com/installation/binaries/

Pour virtualBox, j'ai trouvé ça : http://stackoverflow.com/a/24204805, https://www.virtualbox.org/wiki/End-user_documentation

**Comment by Alex-D** [comment]
> Pour linux : un noyau récent (>3.8). Pour OsX et Windows, la config de VirtualBox (pour faire tourner la VM avec le noyau linux), et un téléchargement de 150M.

Ca me semble raisonnable.

**Comment by cgabard** [comment]
Bon on en est où ici ? Est ce toujours d'actualité ? Est ce que ça a avancé ?

Si quelqu'un a un truc proche du but, je propose qu'on laisse ouvert jusqu'à ce qu'il le finisse.

Sinon  on la traine depuis un temps très important et tout le monde semble avoir un avis différent. Du coup je proposerai de la fermer et d'attendre que quelqu'un prenne son courage a deux main pour faire une mini-zep sur le forum pour discuter ce qu'on veut et ne veut pas et faire une spec clair.

**Comment by firm1** [comment]
J'ai commencé [ça](http://zestedesavoir.com/forums/sujet/1853/installation-dune-instance-locale-de-zds-en-une-ligne/), ça compte ?

**Comment by cgabard** [comment]
Ok donc c'est encore en cours. Ta solution semble plaire, donc c'est en cours de résolution, ça me va.

**Comment by SpaceFox** [comment]
@firm1 ta solution a avancé en 9 mois ?

**Comment by GerardPaligot** [comment]
Oh le troll velu :D

**Comment by firm1** [comment]
J'étais enceinte, je m'y remets bientot :)

Le jeu. 1 oct. 2015 23:13, Gérard Paligot notifications@github.com a
écrit :

**Comment by Eskimon** [comment]
allez, encore le ping du mois qui s'est écoulé ^^ (je passerais presque cette issue en zombie tellement elle est vieille :D )

**Comment by Eskimon** [comment]
Bon, vu que la doc' d'install est suffisamment complète, je ferme ce ticket obsolète.
