### ISSUE TITLE
Contributions au projet

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#60]
Récemment, nous avons intégré notre première page officielle avec la page teasing. Tout le monde semblait vraiment content et enthousiaste. Tellement que les contributions autour de cette page pour des "modifications mineurs" ont incitées les membres du staff, sans mal, à contribuer directement sur la branche master.

Pour cette page, ce n'est pas bien grave. Ce n'est pas une page critique et elle n'est pas encore accessible au public. Par contre, ce n'est pas une pratique à encourager, très loin de là.

Je propose donc que nous commençons à mettre en place la structure finale du projet GitHub en créant les différentes branches (dev, stable, master) et affinant les permissions de chaque contributeur avec l'organisation créé par Talus, zeste-de-savoir. Ainsi, nous pourrions obliger que toutes les contributions se fassent par un PR.

Qu'en pensez-vous ?

**Comment by SpaceFox** [comment]
OK pour moi.

**Comment by Coy0te** [comment]
Pareil, comme ça on sera tranquille.

**Comment by Taluu** [comment]
Pour l'instant, le dépot n'est pas lié à l'organisation ; et je ne sais pas si on peut affiner les droits des contiributeurs de l'orga branches par branches (ça m'étonnerait mais j'y jetterai un oeil sinon).

Un guide de contribution devrait faire l'affaire, et une règle entre nous qui avons le droit de push devrait faire l'affaire je pense (basé sur la confiance oui) ? Au pire, revert un changement se fait sans difficulté

**Comment by GerardPaligot** [comment]
Il n'existe aucun moyen pour protéger un minimum la branche master ? Oui, globalement, nous fonctionnons sur la confiance. Mais les gens sont quand même tentés de ne pas créer une branche parce que la "modification est mineure". Au moins, si un mécanisme ferme cette possibilité, il n'y a plus de soucis.

Puis, personne n'est à l'abri d'une fausse manipulation. Chose arrivée récemment avec un revert commité sur la branche master.

Dans tous les cas, je pense que c'est nécessaire de commencer à intégrer la structure du projet Git.

**Comment by cgabard** [comment]
Je pense que c'est possible. Ça oblige probablement chaque contributeur a forker le projet pour faire la PR mais il me semble que c'est possible. Talus ?

**Comment by Taluu** [comment]
Si ca devait être apparement possible ; y'a déjà quelques forks qui trainent, ils restent pour le moment privés et ça n'a pas l'air d'impacter mon nombre de slots pour projets privés et ça n'a pas l'air de demander à débourser quoique ce soit pour ceux qui forkent...

Quand ce sera public, il faudra évidemment (à part les contributeurs core, et encore...) faire un fork et faire une PR associée.

**Comment by firm1** [comment]
L'idéal serait, lors de l'ouverture ou maintenant de retirer complètement
les droits d'ecriture sur la master et n'autoriser que la création de
branche, la création de PR et le merge de PR.

Je sais que [bitbucket](http://blog.bitbucket.org/2013/09/16/take-control-with-branch-restrictions/)
sait le faire plutôt bien, mais je ne connais pas vraiment Virgin pour
trouver l'équivalent.
Le 14 janv. 2014 12:18, "Baptiste Clavié" notifications@github.com a
écrit :

**Comment by firm1** [comment]
Bon bah, après l'adoption du gitflow, cette issue n'a plus lieu d'être.

Je ferme.
