### ISSUE TITLE
Centraliser la communication (annonces etc.)

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#600]
Bonjour à tous, 
ZDS c'est un beau projet, une association, pas de capitalisme etc.
Cool, mais cela n'enlève pas quelques nécessités en terme de communication.
- Comment un membre sait-il qu'il y a une évolution majeure dans le site? (i.e dès la page d'accueil)
- Création d'une newsletter
- Participation à d'éventuels événements numériques (ou IRL)?
- Les "sondages" ou plutôt les demandes d'opinion quant à une évolution,
- Les lettres d'escuses les jours où le serveur est down et que tout le monde est au taf

Ce ne sont que des exemples. Mais il va falloir gérer toute la charte de communication.
Sur quel sujet communiquez vous? Sur quelle page? Combien de temps?

Bref je pense qu'il faudrait prévoir un espace sur la page d'accueil pour montrer au minimum l'avancement du site et les actions de l'asso.
A moins que vous créiez un blog à côté, of course.

**Comment by ShigeruM** [comment]
Salut,

L'équipe Comm est actuellement composée de Geo, Taguan, Alex-D et moi-même. Cette équipe réduite permet notamment deux choses :
- savoir qui contacter pour les actions de comm à mener ou les problèmes à ce niveau (on ne se pose pas la question pendant 2 semaines pour savoir qui envoie telle ou telle comm) ;
- échanger rapidement entre les 4 membres de l'équipe.

Nous prévoyons de communiquer via 3 canaux principalement :
- Le site (encore heureux !) : nous y posterons régulièrement des articles sur le site et l'asso. La forme n'est pas définie précisément, je ne peux pas te dire si ce sera un "récap" ni même si sa fréquence sera figée. En tout cas ce canal devra être privilégié (on a un site, on communique via le site). Les derniers articles étant sur la home, la comm aura donc une place sur la home. On évitera quand même de poster davantage d'articles de comm que d'articles classiques (informatique, science, etc.). 
- Les réseaux sociaux : Twitter, FB, Google+, pour les news importantes, les nouveaux articles/tutos, etc.
- Les mails : pour les cas spécifiques (exemple récent : les invitations à la bêta) ou, bien sûr, pour répondre aux questions que l'on recevra via ce canal. L'adresse est sur la page "contact" du site : http://zestedesavoir.com/pages/contact/

En tout cas, il n'est pas prévu de place dédiée à la comm sur la home, mis à part les articles bien sûr.

Pour les autres questions :

> Création d'une newsletter

Nous n'avons pas encore parlé d'une newsletter, c'est à voir donc.

> Participation à d'éventuels événements numériques (ou IRL)?

Ça se fera comme ça s'est fait avec les JSDZ : spontanément et via les forums. Rien d'"officiel" prévu pour le moment. Il y aura bien sûr les AG de l'asso, mais ça ne concerna que les membres.

> Les "sondages" ou plutôt les demandes d'opinion quant à une évolution

Pour l'instant, c'est prévu sur les forums. Il y a une catégorie dédiée et elle devra être utilisée. Quand on aura 10 millions de membres et que Google et FB se battront pour nous racheter, on avisera. Mais dans l'immédiat le forum suffira largement.

> Les lettres d'escuses les jours où le serveur est down et que tout le monde est au taf

On fera un article si besoin. Je ne vois pas bien ce qu'on peut faire de mieux. On ne va pas faire un mail pour dire que ZdS est resté down 2 heures... Ceux que ça intéresse assez verront l'article sur le site, les autres s'en foutent.

Je laisse le soin aux autres commateux (jeu de mot pourri, désolé) de compléter/corriger tout ce que je viens de dire ! :) 

Merci d'avoir ouvert ce ticket en tout cas !

**Comment by Alex-D** [comment]
> Les lettres d'escuses les jours où le serveur est down et que tout le monde est au taf

On pourra faire parler Clem' sur l'accueil, comme sur le SdZ autrefois, agrémenter éventuellement d'un article :)

**Comment by artragis** [comment]
- Les réseaux sociaux : on ne peut pas faire autrement par contre c'est sûrement ce qui vous demandera le plus de temps. Surtout que votre cible a une mentalité qui pousse à l'utilisation de ces outils.
- Pour l'utilisation des articles : c'est ça qui m'a motivé à faire ce message. Sauf si j'ai tout faux sur votre politique éditoriale, les articles ce sont des "décryptages" des actualités informatiques, ce que certains appellent même des "articles de fond". Mélanger ça avec un article "bon bah on va avoir une nouvelle version qui corrige ce bug bien relou et puis ajoute une fonctionnalité de la mort qui tue à l'édition de tuto", c'est un peu contradictoire. Ou alors il faudra investir énormément de temps dans la création d'articles bien plus techniques qui décriraient la conception des solution retenue, un peu comme l'article de m@téo qui expliquait le choix d'un redmine à la belle époque (2010).

Sauf si bien sûr vous désirez implémenter une sorte de "mise en vedette" qui permettrait d'offrir à cette communication sa place propre dans la page d'accueil.

**Comment by ShigeruM** [comment]
Il ne faut pas non plus se tromper d'objectif : le site n'est pas fait pour
parler du site, mais pour être une plateforme de partage de connaissances,
avant tout. Je ne vois pas au nom de quoi on mettrait "en vedette" la comm
du site. D'autant que le dépôt sera public et que les modifications
pourront être suivies de très prêt par qui le voudra. Cela ne veut pas dire
que nous n'aurons pas besoin de communiquer, bien sûr, mais alors je répète
ce que j'ai dit tout à l'heure : nous pourrons utiliser les articles pour
cela.

Quant à la ligne éditoriale, je ne vois pas non plus pourquoi nous ne
pourrions pas avoir à la fois des articles de fond **et** des articles
donnant des news du site. Tout est une question de dosage finalement : si
95% des articles parlent de ZdS ou si ces articles sont un bête listing de
fonctionnalités ajoutées, alors il y aura un soucis. Sinon, encore une
fois, je ne vois pas de problème.

**Comment by artragis** [comment]
Ok, moi j'ai mes réponses, je suis content. Je vous laisse la main pour fermer l'issue.

**Comment by Alex-D** [comment]
Je pense que cette discussion sera à ouvrir (sur la communication en général) au besoin, sur le site dès sa beta/sortie.

Ici on parlera plutôt du dev du projet plutôt que du site et de l'asso dans leur usage.

**Comment by cgabard** [comment]
artagis : Concernant la pertinence de ces annonces sur les articles, je suis plutot de l'avis que ça va faire bizarre et peut etre brouiller un peu la ligne éditorial. Cependant je ne pense pas que ce risque/problème soit bloquant pour la sortie. En fait perso je verrais bien a terme ces "news" publié directement sur la potentiel Tribune libre #589

**Comment by firm1** [comment]
pluzin @cgabard

**Comment by ShigeruM** [comment]
+1 aussi, à terme.
