### ISSUE TITLE
Points à investiguer pour le passage à Django 3.2

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#6008]
[**Django 3.0**](https://docs.djangoproject.com/en/3.1/releases/3.0/)

![image](https://user-images.githubusercontent.com/6664636/102993715-f31c0500-451d-11eb-8dac-677e75b1f463.png)

![image](https://user-images.githubusercontent.com/6664636/102993744-029b4e00-451e-11eb-923d-6b5034bafb16.png)

[**Django 3.1**](https://docs.djangoproject.com/en/3.1/releases/3.1/)

![image](https://user-images.githubusercontent.com/6664636/102993974-74739780-451e-11eb-93b2-7c0722a81d48.png)

**Comment by artragis** [comment]
La seule dont je ne suis pas encore sûr de l'impact c'est la troisième le same-origin sur le referer-policy

**Comment by philippemilink** [comment]
Autre point à voir:
- ne pas afficher dans les logs de tests les backtraces des exceptions attendues (par exemple #6193, voir [la doc](https://docs.djangoproject.com/fr/3.2/topics/testing/tools/#exceptions))

**Comment by Situphen** [comment]
Je viens de finir la lecture en détails des notes de versions de Django 3.0, 3.1 et 3.2 (enfin).

- Il y a beaucoup de petits changements dans des fonctions ou des paramètres spécifiques à telle ou telle chose. Je pense qu'on verra au fur et à mesure si certains changements peuvent nous permettre d'améliorer des choses, personnellement je n'ai rien vu d'évident. Par exemple, la fonctionnalité relevée par @philippemilink plus haut est une de ces fonctionnalités peut-être utile.
- Il y a pas mal de nettoyage : suppression des dernières fonctions de Python 2, bibliothèque mieux maintenue pour Memcache, etc. Tant mieux !
- Il y a globalement une amélioration de la sécurité : vieilles fonctions de hashage dépréciées, augmentation du nombre d'itération pour les fonctions gardées, etc.
  - Il y a aussi les nouvelles valeurs par défaut pour les entêtes de requêtes `X-Frame-Options` (qui passe de `sameorigin` à `deny`) et `X-Content-Type-Options` (qui passe à `nosniff`). Je ne pense pas que cela changera quelque chose pour nous car ces entêtes sont déjà définies dans la configuration nginx pour chaque requête (dans [le fichier `ssl.conf`](https://github.com/zestedesavoir/ansible-zestedesavoir/blob/4ec26c8f93ec223ff53e33d7064c7a1d5c82aef0/roles/web/files/nginx/snippets/ssl.conf#L12)) donc je suppose que les valeurs de nginx écrasent celles de Django ? Cela dit, il serait probablement bien de mettre à jour cette configuration au même niveau que les valeurs par défaut de Django car je ne pense pas qu'elles nous posent un soucis particulier.
  - Concernant `SECURE_REFERRER_POLICY` qui définit l'entête `Referrer-Policy`, je pense que la valeur par défaut de `same-origin` est un bon choix. [Cette page de documentation](https://docs.djangoproject.com/en/3.2/ref/middleware/#referrer-policy) explique bien les différents choix possibles.

Selon moi, on est bon pour le passage à Django 3.2 avec quelques ajustements plus tard si besoin.
