### ISSUE TITLE
La very-top-banner finit par disparaître en scrollant sur les longues pages

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#6009]
**Description du bug**

La bannière tout en haut du site disparaît lorsqu'on scrolle vers le bas sur des pages longues.

**Comment reproduire ?**

1. Activez la bannière (allez sur la bêta, ou sur votre instance locale, par défaut une bannière est présente)
2. Allez sur sur une longue page (par exemple: https://beta.zestedesavoir.com/forums/derniers-sujets/)
3. Scrollez jusqu'à ce que vous "dépassiez" le contenu de la side-bar: la bannière disparaît

Problème observé sur Firefox et Safari, pas testé sur d'autres navigateurs.

**Comportement souhaité**

La bannière est toujours présente.

**Information complémentaire**

@AmauryCarrade nous a déjà donné une partie de l'origine de ce bug:
> En gros, le `body` a une hauteur limitée (malgré le fait que le contenu continue au delà), et le bandeau est en position `sticky` par rapport au `body`
Donc quand on passe “““sous””” le `body`, le bandeau disparaît car il “reste dedans”

**Comment by Situphen** [comment]
Corrigé par #6054 !
