### ISSUE TITLE
Forcer la limite de caractères pour le texte de masquage

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#6017]
Lorsqu'un modérateur masque un message, il précise la raison du masquage (par exemple, "Hors sujet"). Cette raison est stockée en base de données dans le champ `text_hidden` de la table `Comment` qui est limité à 80 caractères.

https://github.com/zestedesavoir/zds-site/blob/b351f2e91c3722dc7532c93d6259ac158d844859/zds/utils/models.py#L410

Cette limite n'est pas présente lors de la saisie de cete raison, ce qui peut causer une belle erreur interne si le modérateur est trop bavard. Il faut donc ajouter le bon attribut HTML à l'élément de cette ligne pour limiter à 80 caractères le message expliquant la raison du masquage : 

https://github.com/zestedesavoir/zds-site/blob/b351f2e91c3722dc7532c93d6259ac158d844859/templates/misc/message.part.html#L81

**Comment by Migwel** [comment]
@Situphen Ce bug est-il vraiment présent ? J'ai essayé de le reproduire localement, sans succès.


> sqlite> select id, text_hidden from utils_comment;                                                                                                                                                                 1|                                                                                                                                                                                                                 2|                                                                                                                                                                                                                 3|012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789                                                                                                                       4|                                                                                                                                                                                                                 5|                                                                                                                                                                                                                 6|01234567890123456789012345678901234567890123456789                                                                                                                                                               7|Flood, Troll, Hors sujet,Flood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetdddddddFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetddddddFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetdddlkhdslkdskdjsldkFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujet;slk;sdlkd;kFlood, Troll, Hors sujetFlood, Troll, Hors sujetFlood, Troll, Hors sujet


Ou je ne regarde pas au bon endroit ?

**Comment by Situphen** [comment]
Salut ! Alors effectivement le bug n'est pas reproductible localement car on utilise SQLite comme base de données mais sur la bêta ou la production c'est reproductible car on y utilise MySQL. :)
