### ISSUE TITLE
Les permissions du groupe staff dans les fixtures ne sont pas à jour

### ISSUE THREAD

**Issue by AmauryCarrade** [zestedesavoir/zds-site#6022]
En mettant à jour mes utilisateurs depuis les fixtures à l'aide de `dj loaddata fixtures/users.yml`, j'ai remarqué qu'il manque des permissions. Plus précisément, j'ai remarqué le manque de : 

- `utils.change_comment_potential_spam` (une permission récemment introduite par #6016) ; et
- `forum.change_topic` (plus surprenant, car c'est la permission de base qui donne actuellement les droits de modération et de gestion du site à l'équipe ; elle était correctement attribuée auparavant).
- 
Peut-être que l'ajout d'une nouvelle permission a changé des identifiants de ces dernières. Comme les fixtures utilisent de tels identifiants, ça a pu tout casser.

Il serait bien de voir si l'on ne peut pas dépendre d'autre chose que ces identifiants numériques, car si mon hypothèse est bonne, ça va casser à chaque fois qu'on créé une nouvelle permission…

**Comment by Arnaud-D** [comment]
Notons que #4266 évoque les mêmes problèmes. ^^

**Comment by AmauryCarrade** [comment]
Ah oui bien vu. J'ai identifié une solution native et propre pour faire ça : depuis quatre ans, Django a bien évolué !

**Comment by artragis** [comment]
Ok, je clos l'autre ticket car on a une meilleure solution ici.
