### ISSUE TITLE
(v30) Certains blocs secrets n'apparaissent pas

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#6043]
[Ymox, sur le forum](https://zestedesavoir.com/forums/sujet/11514/etat-de-la-beta/?page=2#p231423) : 

> Hello
> 
> J'aime bien aussi, l'accent apporté sur la lisibilité est vraiment un bon point à mon avis !
> 
> Petit détail : apparemment, les blocs secret sont (parfois ?) totalement masqués aux anonymes dans les sujets. Par exemple [ici sur la version 29.3b](/forums/sujet/836/foire-aux-questions-php/#p11425) et [ici sur la version 30](//beta.zestedesavoir.com/forums/sujet/836/foire-aux-questions-php/#p11425), la table de vérité n'apparaît pas sans être connecté sur la beta, alors qu'elle est dans le DOM. Es-ce qu'il s'agit d'un comportement voulu ? Histoire que je sache qu'il me faut revoir mes messages et tutoriels  :)

**Comment by artragis** [comment]
I'm on it
