### ISSUE TITLE
Drop de JQuery phase 2: Industrialisation - Gestion de Ajax

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#6046]
(Créé à la suite de #5786 )

La version 30 du site commence à virer JQuery dans plusieurs modules qui ne se servent globalement que du dom.

Cependant il faut comprendre que notre basecode se sert d'autres choses intéressantes de JQ : le ajax.

Globalement l'objet xhr est aujourd'hui commun à tous les navigateurs que nous supportons. Les polyfills de JQ ne nous sont pas utiles de ce fait. 

Le but de ce ticket est de trouver une solution technique qui soit satisfaisante pour : 

- Utiliser l'API fetch quand c'est possible car elle semble plus simple et maintenable, je n'ai aucune idée d'une potentielle atteinte aux perfs
- Avoir un objet d'utilitaire Ajax pour faire nos requêtes POST/PUT/DELETE quand on le peut sachant que pour les deux premier la payload peut être : 
   - un json buildé programmatiquement
   - une copie de `form.data` envoyée non encodée en JSON. 
-  Ces requêtes nécessitent qu'on mettent la valeur du cssrftoken qui est toujours récupéré de la même manière mais le code est dupliqué partout
- Une documentation

Ce ticket est donc un moyen de **préparer la migration** pas de l'opérer même si, pour fournir un exemple vous pouvez prendre un des fichiers du site et le migrer.

**Comment by Genroa** [comment]
fetch remplit très bien tous les besoins (et est standard partout), avec éventuellement quelques helpers maison pour simplifier l’écriture, et sa performance est bien supérieure à JQuery. Et si vraiment il faut plus, Axios fait bien le café. :)
