### ISSUE TITLE
Raccourcir l'URL de la page de profil

### ISSUE THREAD

**Issue by AmauryCarrade** [zestedesavoir/zds-site#6047]
Comme discuté dans #6032, l'idée est de modifier l'URL de la page de profil pour qu'elle soit `zestedesavoir.com/@pseudo`. C'est beaucoup plus propre et facile à partager que l'actuel `zestedesavoir.com/membres/voir/pseudo`.

**Comportement observé** : l'adresse de la page de profil d'un membre est `zestedesavoir.com/membres/voir/pseudo`.

**Comportement souhaité** : cette adresse est `zestedesavoir.com/@pseudo`. Les anciennes adresses fonctionnent toujours et redirigent vers les nouvelles.

## Comment faire ?

Pour changer cette URL, il y a deux étapes à suivre : 

1. changer l'URL proprement dite ;
2. créer une redirection de l'ancienne URL vers la nouvelle.

C'est relativement simple et accessible à un nouveau contributeur, mais il y a quelques pièges dans lesquels il ne faudra pas tomber, et il y a tout de même un peu de boulot, sans que ce ne soit insurmontable.

### Changer l'URL

L'URL vers cette page est actuellement définie ici.

https://github.com/zestedesavoir/zds-site/blob/04b299a65e4e1c668b274c39a1c9eba0b5727611/zds/member/urls.py#L50

On ne peut pas la garder ici, car toutes les URLs de l'app `member` sont préfixées par `/membres/`. Il faut donc retirer cette définition d'URL de ce fichier, et l'ajouter dans le fichier principal des URLs de ZdS, à savoir dans cette liste de `zds/urls.py` : 

https://github.com/zestedesavoir/zds-site/blob/04b299a65e4e1c668b274c39a1c9eba0b5727611/zds/urls.py#L83-L100

Il faudra importer la vue de la page de profil dans ce fichier, et ajouter une URL avec la bonne adresse. Au passage, on pourra utiliser [la syntaxe moderne de Django pour les URLs](https://docs.djangoproject.com/fr/3.1/topics/http/urls/#example), qu'est tout de même plus lisible.

Quelque chose dans cet esprit : 

```py
urlpatterns = [
  # ...
  path("@<str:user_name>", MemberDetail.as_view(), name="member-detail"),
]
```

Comme on ne change pas le nom de l'URL, tous les liens vers les pages de profil seront automatiquement mis à jour.

### Rediriger les anciennes URLs

Tous les liens seront mis à jour… du moins, ceux dans l'interface de ZdS ! Tous les autres (ceux écrit en dur dans des messages notamment, ou ceux sur d'autres sites que ZdS) resteront ancien. Il faut donc que l'ancienne URL continue d'exister, mais redirige vers la nouvelle de façon transparente.

Pour ce faire, il faut créer une vue de redirection. On va créer une vue toute simple prenant le pseudo en paramètre :

```py
def redirect_old_profile_to_new(request, user_name):
```

…et qui utilisera ce nom pour 

1. retrouver l'utilisateur concerné dans la base de donnée (on pourra [s'inspirer du code de `MemberDetail`](https://github.com/zestedesavoir/zds-site/blob/2bbe2fcb936e9207d396b6cd1029526b40a0f504/zds/member/views.py#L113)) ;
2. [rediriger vers la nouvelle page de profil grâce au raccourci `redirect`](https://docs.djangoproject.com/fr/3.1/topics/http/shortcuts/#redirect) (on prendra soin de préciser `permanent=True` car c'est une redirection permanente). On pourra directement retourner `redirect(user.profile)`, comme dans le premier des exemples donnés dans la documentation liée, car le `Profile` d'un utilisateur définit `get_absolute_url()`.

Ensuite, il ne restera plus qu'à ajouter, [dans le fichier de configuration des URLs de l'app `member`](https://github.com/zestedesavoir/zds-site/blob/04b299a65e4e1c668b274c39a1c9eba0b5727611/zds/member/urls.py#L46), cette vue de redirection : 

```py
urlpatterns = [
  # ...
  path("voir/<str:user_name>", redirect_old_profile_to_new, name="member-detail-redirect"),
]
```

### Tests ?

On pourra éventuellement ajouter un test vérifiant que l'ancienne URL redirige bien vers la nouvelle _avec une redirection permanente_, et uniquement dans le cas où l'utilisateur existe. Ce n'est pas critique, cela dit, je pense.

## Du côté de zmarkdown

C'est un peu séparé du travail côté ZdS (donc pas de souci si un débutant ou nouveau contributeur passe par là ! ce point ne sera pas à gérer), mais il faudra reconfigurer zmd pour qu'il génère la bonne URL de profil lorsqu'il fait le rendu HTML des pings.

**Comment by viki53** [comment]
Il faut donc prévoir une redirection permanente pour faciliter la mise en cache et le référencement.

---

Quid du format un peu folklorique de certain pseudos par contre ? Par exemple :
* Ceux qui commencent par un `@`
* Ceux qui contiennent un `@` (j'ai vu passer des adresses email en pseudo)
* Les URL (rappelons-nous de mon `https://viki53.eu` qui avait déjà tout cassé)
* On aura sûrement d'autres caractères qui risquent de tout péter

Est-ce que ce serait pas le moment de mettre à plat quelques règles pour les pseudos ?

---

Si on crée des URLs raccourcies pour les profils, est-ce qu'on en mettrait pas aussi en place pour le reste ? Typiquement des choses comme `/-{idTopic}` ou `/_{idBillet}`

**Comment by AmauryCarrade** [comment]
> Il faut donc prévoir une redirection permanente pour faciliter la mise en cache et le référencement.

Oui, c'est d'ailleurs mentionné dans le ticket ^^ .

> Quid du format un peu folklorique de certain pseudos par contre ?

Normalement, et vu que le `/` est interdit dans les pseudos, tout devrait fonctionner comme avant.

> Ceux qui commencent par un `@`
> Ceux qui contiennent un `@` (j'ai vu passer des adresses email en pseudo)

L'URL sera `/@@pseudo` ou `/@bla@blo`, ça ne pose pas de souci. Django va d'abord regarder si l'URL commence par un `@`, et si c'est le cas, considérer que ce qui suit (avec éventuellement un autre `@`) est le pseudo.

> Les URL (rappelons-nous de mon `https://viki53.eu` qui avait déjà tout cassé)

Sauf erreur de ma part, les pseudos ne peuvent plus contenir de `/`, donc ça ne pourra pas se reproduire.

> On aura sûrement d'autres caractères qui risquent de tout péter

Le seul caractère gênant est `/`, qu'est exclu des URLs grâce au formateur `str:` suggéré dans la piste d'implémentation, qu'accepte n'importe quelle chaîne ne contenant pas de `/`.

> Est-ce que ce serait pas le moment de mettre à plat quelques règles pour les pseudos ?

On pourrait en profiter pour revoir ça au passage, cela dit, je ne m'y oppose pas (et ça pourrait être pertinent dans certaines limites) mais je ne pense pas que ce soit un frein pour l'implémentation de ceci.

------


> Si on crée des URLs raccourcies pour les profils, est-ce qu'on en mettrait pas aussi en place pour le reste ? Typiquement des choses comme `/-{idTopic}` ou `/_{idBillet}`

Je ne suis pas bien sûr de saisir l'intérêt de faire cela. L'objectif pour la page de profil c'est d'avoir une adresse plus _sexy_ à partager, pour en faire une vraie page personnelle mettant en avant tes contenus etc. Ce qu'est beaucoup plus vendeur si on cherche à proposer une plateforme de publication à des gens, iels voudront pouvoir donner un lien avec tout ce qu'iels publient, c'est normal. Donc autant que ce lien soit propre et du même genre que les autres réseaux sociaux.

La nouvelle adresse serait donc bien l'adresse _principale_ de la page, et l'ancienne redirigerait vers la nouvelle. (Si jamais c'était pas clair.)

Par contre, je comprends moins la pertinence de faire de même, avec en plus un préfixe un peu cryptique, pour les contenus. Peut-être que quelque chose m'échappe, mais si une URL du style `zestedesavoir.com/@viki53` est très claire sur ce qu'elle abrite, quelque chose comme `zestedesavoir.com/-7864`, beaucoup moins. Donc je ne comprends pas l'idée, mais peut-être pourras-tu préciser ?

**Comment by viki53** [comment]
Ok, je vois mieux l'idée pour les pseudos. Pas trop de risque pour le coup, même si une remise à plat des règles de pseudos serait intéressante à prévoir (sans bloquer cette PR)

Pour le coup mon idée pour des contenus spécifiques est pas vraiment utile, c'est clair.

Mais pour des catégories/tags, ça pourrait être sympa !   
Dommage que les `#` soient pas envoyés au serveur, ça aurait pu faire `https://zestedesavoir.com/#python` 😁

**Comment by AmauryCarrade** [comment]
> Mais pour des catégories/tags, ça pourrait être sympa !

Effectivement, pouvoir liver vers tous nos contenus Python par un lien court pourrait être propre. À noter cela dit qu'on a déjà `https://zestedesavoir.com/bibliotheque/?tag=python` pour ça, ce qui n'est pas si pire. Je ne suis pas contre rendre l'URL plus propre cela dit.

**Comment by viki53** [comment]
Ça pourrait être raccourci en `/tag/python` par exemple, dans un premier temps. Par contre à voir si ça pourrait pas être compris comme incluant (ou non) les forums 🤔

**Comment by AmauryCarrade** [comment]
C'était un peu ma crainte, en réalité. Vu qu'on a divers éléments taguables.

Une autre solution serait, mais c'est plus ambitieux, d'avoir une page de tags plus riche et construite avec et des contenus, et le forum. Mais bon, c'est pas le même boulot.
