### ISSUE TITLE
Mettre a disposition pandoc dans des dépôts debian/ubuntu

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#605]
Aujourd'hui sur toutes les plateformes Linux, pour avoir la dernière version de pandoc (nécessaire pour zds) il faut compiler le paquet a la main.
La compilation se fait via l'utilitaire hashkell cabal. Le problème ici est que la compilation prend du temps (environ 10 min sur Travis). L'idée est donc de packager la dernière version de pandoc (1.10xx) et de le mettre a disposition de tous via les dépôts debian.

Bonus : pour bien faire faudrait que le dépôt soit au nom des zestedesavoir.

**Comment by SpaceFox** [comment]
La dernière version est la 1.12, depuis le 15 septembre 2013.

Elle est disponible dans Debian Jessie et Debian Sid, mais pas dans les
backport : https://packages.debian.org/search?keywords=pandoc
Je ne sais pas dans quelle mesure ça nous aide... mais si on peut utiliser
un paquet officiel Debian, ça me paraît plus propre que repackager notre
propre version.

**Comment by firm1** [comment]
Etant donné que je ne suis pas très au courant de toutes ces histoires de packaging, l'idée est au final de pouvoir installer rapidement et proprement pandoc sur la prod et sur travis.

Je ne sais donc pas si le paquet dans jessie ou sid peut nous aider.

**Comment by cgabard** [comment]
> La dernière version est la 1.12, depuis le 15 septembre 2013.

Oui enfin il y a eu un paquet de correction depuis. La derniere stable est la 1.12.4.2 qui est sorti le 14 Mai de cette année !

**Comment by cgabard** [comment]
Bon sinon dixit la doc il est facile de faire un executable sans dépendance, un simple fichier binaire. Ce serait peut etre la solution, non ?

**Comment by firm1** [comment]
Ça serait l'idéal mais serait-il multiplate-forme le binaire ? car il
faudrait qu'il s'installe en ligne de commande pour travis.
Le 26 mai 2014 09:18, "Christophe Gabard" notifications@github.com a
écrit :

**Comment by cgabard** [comment]
Non il sera forcément specifique a chaque OS. Cependant les windows et
MacOS on déjà des binaires dispo sur le site. Il n'y a donc que des
binaires Linux 32 et 64 bits à générer

Christophe.

2014-05-26 9:49 GMT+02:00 firm1 notifications@github.com:

**Comment by firm1** [comment]
Euh les binaires linux c'est un bien grand mot, ça dépend du noyau sur lequel tu compile.

'fin bref, si on peut récupérer le paquet dispo sous jessie ou sid, ça serait pas mal non plus. Mais je sais pas trop comment le faire.

**Comment by cgabard** [comment]
Justement su je comprend bien la doc, ce sont des exécutables autonome. En
gros tout est Linké statiquement. Du coup non la version a peu d'importance

**Comment by cgabard** [comment]
Mais effectivement le paquet debian pourrait être une autre solution

**Comment by Coy0te** [comment]
Le paquet pandoc 1.12.x qui existe sous Jessie (pareil pour sid) a plusieurs dépendances non résolues dans Wheezy (notamment la version requise de la libc6), du coup ça me paraît difficilement jouable de le reprendre tel quel sans trop ruiner le caractère "stable" de notre Wheezy.

Ce qu'il faudrait, c'est le recompiler avec Cabal sur une Wheezy 64bits, et éventuellement le packager et le déposer sur [backports](http://backports.debian.org/Contribute/).

**Comment by cgabard** [comment]
Avec les indications tout en bas de la page d'install :
http://johnmacfarlane.net/pandoc/installing.html

tu dois pouvoir rendre l'executable un minimum indépendant. Si quelqu'un
est motivé et sais comment faire un tel paquet...

Christophe.

2014-05-26 14:25 GMT+02:00 Coyote notifications@github.com:

**Comment by Taluu** [comment]
Sinon, on peut mettre en place [une politique de cache](http://docs.travis-ci.com/user/caching/) là dessus, non ?

-- edit : ouais nan c'est dispo que pour les répos privés apparement

**Comment by firm1** [comment]
Toujours personne pour packager ces paquets ? sniff sniff

**Comment by Eskimon** [comment]
J'ai compilé sur mon Ubuntu 12.04 comme indiqué sur la doc.. Du coup dans mon dossier `~/.cabal/bin/` j'ai les executables suivants:
- aeson-pretty
- hsb2hs
- json2yaml
- pandoc
- pandoc-citeproc
- yaml2json

C'est ca qu'il te faut ?

**Comment by firm1** [comment]
Euh, ce qu'il faudrait c'est que tu le package en .deb et que tu le pousse sur un dépot ppa.

Sinon, tu peux éventuellement rendre le fichier `pandoc` résultant de ta compil téléchargeable via wget. Je pourrai donc essayer de voir comment le mixer à travis.

**Comment by Eskimon** [comment]
> Euh, ce qu'il faudrait c'est que tu le package en .deb et que tu le pousse sur un dépot ppa.

Arf c'est ce qui me semblait

> Sinon, tu peux éventuellement rendre le fichier pandoc résultant de ta compil téléchargeable via wget. Je pourrai donc essayer de voir comment le mixer à travis.

Tu peux essayer de le recuperer via ce lien (en train d'uploader):
https://dl.dropboxusercontent.com/u/18967337/pandoc

**Comment by firm1** [comment]
> Tu peux essayer de le recuperer via ce lien (en train d'uploader):

Je vais essayer, cette nuit.

**Comment by firm1** [comment]
C'est bon le fichier compilé marche bien sur Travis. Merci à @Eskimon on passe d'une durée d'~ 30 min à 7-8 min de tests. C'est trop coule.

Je ferme

**Comment by Eskimon** [comment]
Et dire que ca a du me prendre genre 5 minutes pour faire l'executable :D on aurai pu gagner tant de temps before !!
Je peux le virer de mon dropbox, tu l'as copié autre part ?

**Comment by firm1** [comment]
> Je peux le virer de mon dropbox, tu l'as copié autre part ?

Nope, les liens pointes sur ton dropbox. Il doit y rester a vie.

**Comment by Eskimon** [comment]
> Nope, les liens pointes sur ton dropbox. Il doit y rester a vie.

Ah mais je viens de vérifier, tu plaisantais pas en fait !! Tu pourrais pas centraliser ca sur une seule dropbox (celui ou il y a les templates) ? ou carrément mettre ca quelque part sur le serveur ZdS ?

**Comment by firm1** [comment]
Le serveur zds peut down alors que dropbox ne downera jamais ('fin c'est
moins risqué).

Je te dirais quand j'aurai centralisé ça.

**Comment by ShigeruM** [comment]
Peut-être le Google Drive de l'asso alors dans ce cas ? Histoire de libérer
le Dropbox d'Eskimon... :-)

**Comment by Eskimon** [comment]
En fait ca me gene pas plus que ca, c'est pas pour la place que ca prend, mais si un jour je décide de faire du ménage et que je percute pas que c'est utile à d'autres...

**Comment by Alex-D** [comment]
Bah dans la GDrive y a moins de risques que ça saute je pense.

**Comment by firm1** [comment]
> Bah dans la GDrive y a moins de risques que ça saute je pense.

J'ai pas accès a Gdrive
