### ISSUE TITLE
Dépassement d'entiers signés

### ISSUE THREAD

**Issue by dianegolfouse** [zestedesavoir/zds-site#6061]
Bonjour,
Je m'excuse si ce n'est pas le bon endroit pour faire cette remarque...

Dans un des articles sur le language C, il est question de [dépassement d'entiers signés](https://zestedesavoir.com/tutoriels/755/le-langage-c-1/notions-avancees/les-limites-des-types/#les-entiers-sign%C3%A9s). Le comportement décrit me semble subtilement incorrect, ou en tous cas incomplet: le dépassement d'entier en C n'est pas seulement dépendant de la machine, mais un type d'Undefined Behavior (je ne connais pas la traduction française 🙂) !

Pour appuyer mes propos, voici un programme où le dépassement produit un comportement étrange et incohérent (en tout cas sur ma machine™) :
```c
#include <limits.h>
#include <stdio.h>

int main(void) {
    int x = INT_MAX;
    printf("INT_MAX + 1 = %i\n", x + 1);
    if ((x + 1) < 0) {
        printf("Overflow detecté\n");
    }
    return 0;
}
```

```
$ gcc -g main.c -o test -w -O3 && ./test
INT_MAX + 1 = -2147483648
```
Il me semble donc que le comportement décrit dans cet article est incorrect.

**Comment by entwanne** [comment]
Salut,

Le site Zeste de Savoir offre un formulaire spécialement dédié à la remontée d'erreurs sur les contenus, via le lien « signaler une faute » en bas des pages de tutoriel.

Maintenant, j'ai relu le paragraphe du tuto en question et il parle bien de comportement indéfini (qui se traduit par _Undefined behavior_) en cas d'_overflow_.

La suite décrit simplement ce qui peut se passer. Et dans ton cas le `-2147483648` qui apparaît montre que l'on est dans un cas où la valeur boucle.

Et peut-être qu'une optimisation fait que le compilateur applique une autre stratégie (saturation ou omission) sur ta condition ensuite. Il en a le droit puisque le comportement n'est pas défini.

**Comment by Taurre** [comment]
Bonjour,

Je vous remercie pour votre retour.

Je rejoins la réponse d'entwanne : le paragraphe précise bien qu'un dépassement de capacité lors d'une opération est un comportement indéfini (qui est bien la traduction d'*undefined behaviour* tel qu'utilisé par la norme). Il va simplement un peu plus loin en présentant les comportements possibles dans un tel cas (même si d'autres sont imaginables).

Concernant l'exemple donné, vous utilisez les optimisations aggressives de GCC (option -O3) qui peuvent typiquement supprimer des conditions si elles sont par exemple considérées comme « ne pouvant jamais se produire » ou précisément parce qu'elles produisent des comportements indéfinis. Je vous invite à refaire le test avec les optimisations désactivées (option -O0) pour voir si le comportement reste identique.

**Comment by dianegolfouse** [comment]
Merci pour vos réponse !

Je vois, j'imagine que j'ai été un peu paranoïaque 😁

De manière intéressante, le comportement du programme reste le même en remplaçant -O3 par -O0... j'imagine que gcc est un peu trop malin
