### ISSUE TITLE
Moyen-tuto ?

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#608]
Il me semblait que ça avait déjà été discuté mais je ne retrouve plus donc voila l'issue...

Quid de faire une catégorie de Moyen-tuto ? Aka équivalent à un tuto contenant un seul chapitre mais plusieurs "mini-tuto" ?

Ou alors ce genre de contenu est voué à devenir une série d'articles ?

**Comment by Alex-D** [comment]
Une série d'article ne me semble pas judicieux.

Je ne sais pas ce que cela représente niveau back de faire un "moyen-tuto". Je ne vois déjà pas trop pourquoi c'est si différent techniquement finalement.

**Comment by firm1** [comment]
> Je ne vois déjà pas trop pourquoi c'est si différent techniquement finalement

Pour te donner une idée, je dirais -> v42

**Comment by cgabard** [comment]
> Une série d'article ne me semble pas judicieux.

Pourquoi ? Au contraire ça permet de faire vivre le site avec des articles sortant régulièrement qui pourrait inciter des gens a revenir si ils ont bien aimé le premier épisode.

> Pour te donner une idée, je dirais -> v42

Arf, tanpis :)

**Comment by cgabard** [comment]
Pourquoi la fermer ? Que ce ne soit pas fait a court terme ne veut pas dire qu'on ne peut pas causer de son implémentation futur !

**Comment by Alex-D** [comment]
Sorry, fausse manip, +1 pour discuter.

**Comment by strangergwenn** [comment]
Je plussoie très vivement cette feature. Avoir 0 (mini), 1 (moyen?) ou 2 (big) niveaux de hiérarchie, en gros, ça revient à pouvoir écrire une "partie" de big-tuto de façon indépendante, dans les cas où le cours ne se prête ni à l'un ni à l'autre des modèles existants.

**Comment by cgabard** [comment]
Ce ticket est une sous partie de la zep 12, aucun interet de le laisser ouvert.

**Comment by Eskimon** [comment]
ZEP 12 : http://zestedesavoir.com/forums/sujet/846/zep-12-refonte-du-principe-des-tutoriels-et-articles/
