### ISSUE TITLE
Bannir un compte inactif

### ISSUE THREAD

**Issue by arobase-che** [zestedesavoir/zds-site#6081]
**Description du bug**

Il me semble qu'il est impossible de bannir un compte inactif.

**Comment reproduire ?**

Avoir un compte inactif. Allez sur sa page de profil. Le bannir n'a pas de bouton.

Je me trompe ou c'est un vrai problème ?

**Comment by Situphen** [comment]
À mon avis c'est un faux problème. Déjà car la plupart des comptes inactifs plus d'une heure le restent pour l'éternité, mais aussi car si jamais on voudrait vraiment en bannir un (je ne vois pas pourquoi mais bon) alors il suffit de demander à un administrateur de le faire via la page d'administration de Django.

**Comment by artragis** [comment]
je clos car ça n'a aucun intérêt en vrai.

**Comment by arobase-che** [comment]
Euh, on a le cas là en alerte.

La personne a inscrite 2 comptes, activé seulement 1, qu'on a banni. Et maintenant on est obligé d'attendre que le deuxième soit activé pour le ban également...

Du coup, administateur lit les alerte stp.

**Comment by artragis** [comment]
Oui car les gens qui font des alertes utilisent des systèmes automatisés sans vérifier ce qu'ils font.
Un compte non activé n'a pas à être banni, c'est du temps passé pour rien car la personne ne peut pas nuire à zds.

**Comment by Situphen** [comment]
> Du coup, administateur lit les alerte stp.

Difficile de prendre une décision quand il y a à la fois une alerte « à bannir : multi déjà ban » et une autre « Potentiel spam »... Moi ça ne me dérange pas de le bannir mais il faut que la demande soit claire et que ça ne me soit pas reproché derrière par d'autres membres du Staff. Et comme il n'y a pas de responsable Staff pour prendre une décision claire...
