### ISSUE TITLE
Échec de l'installation sous Linux sans compilateur Rust

### ISSUE THREAD

**Issue by enzzc** [zestedesavoir/zds-site#6082]
**Description du bug**

Échec de l'installation via `make install-linux` quand il n'y a pas de toolchain Rust, au moment de l'installation des paquets avec `pip`.

**Comment reproduire ?**

Sur un système frais qui n'a pas le paquet `cargo` installé, lancer `make install-linux` jusqu'à ce que `pip` s'occupe de `python-cryptography` (c'est une dépendance secondaire qui ne figure pas dans `requirements.txt`)

**Comportement attendu**

Le procédure aboutit.

**Informations techniques**

- OS: Debian 10
- Version/environnement de zds: `dev`, installation Python standard de la distribution

**Résolution du problème**

Très simple : à la main j'ai fait `apt install cargo`, puis la procédure d'installation peut aboutir.

(il faut cependant que je teste mieux, en l'indiquant dans `zds-site/scripts/dependencies/debian.txt` avant de relancer la procédure sur une base propre)

**Informations complémentaires**

Le problème est un classique depuis que cette lib intègre du code Rust : https://cryptography.io/en/latest/faq.html?highlight=rust#installing-cryptography-fails-with-error-can-not-find-rust-compiler

**Comment by philippemilink** [comment]
Tant qu'à faire, il faudrait aussi vérifier s'il ne faut pas ajouter ce paquet dans la liste des dépendances pour les autres systèmes gérés dans le dossier `zds-site/scripts/dependencies/`.

**Comment by arobase-che** [comment]
Je crois surtout qu'ils disent d'utiliser une version récente de `pip`.

**Comment by gustavi** [comment]
Je confirme avoir réglé le problème en mettant à jour pip (`pip install --upgrade pip`) dans mon venv et en relançant l'installation (Debian 10).

**Comment by enzzc** [comment]
Avoir une version récente de `pip` semble être une solution. Du coup, peut-être juste préciser dans la doc qu'il faut bien le mettre à jour dans le `venv` au lieu d'utiliser la version de base du système, et ça devrait aller.

J'ai trouvé, dans cet article, quelques éléments d'explication, que ce soit en Rust ou autre chose de compilable :

> Many packages—from NumPy to Cryptography—require compiling some code in C/C++/Cython/Rust/etc. to work. In order to save you the need to compile everything from scratch, maintainers can upload a compiled version of the code—”wheels”—to the Python Package Index. If pip sees a wheel that will work for your specific version of Python and operating system version, it will download it instead of the source code.
[...]
Here’s the problem: old versions of pip don’t support manylinux2010, and certainly not manylinux2014. The pip in Ubuntu 18.04 is too old, so it only knows about manylinux1
[...]
In order to get the latest and greatest packages, without compilation, you need to upgrade to a recent version of pip.
https://pythonspeed.com/articles/upgrade-pip/

Je suppose que la version de base de Debian 10 que j'avais, elle non plus, ne supportait pas encore `manylinuxXX`.

Je ferme le ticket à présent ?

**Comment by gustavi** [comment]
À fermer quand la doc et les scripts d'installation seront à jour je pense.
