### ISSUE TITLE
Zone d'édition en chasse fixe

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#61]
tout est dans le titre. Changer la police de la zone d'édition en casse fixe serait tres utile pour certaines extensions markdown, en particulier grid_table

**Comment by Coy0te** [comment]
En effet. Pour préciser un peu le cas des tableaux : 
- pour faire un tableau simple et court avec grid_tables, c'est indispensable d'avoir une police à chasse fixe ;
- pour faire un tableau long et/ou complexe avec grid_tables, c'est indispensable d'avoir un éditeur JS intelligent (bon courage ThS :D ). Pareil pour l'édition d'un tableau existant.

**Comment by Thunderseb** [comment]
Une solution hybride serait de ne faire que un éditeur de tableau, qui afficherait un système WYSIWYG juste pour le tableau. C'est pas trop complexe à gérer (l'édition se ferait à part, soit dans une popup soit dans une "div" modal. Par contre, faire un vrai éditeur WYSIWYG c'est VRAIMENT galère (genre TinyMCE).

**Comment by cgabard** [comment]
+1 pour l'éditeur externe pour les tableau

Ça n'enlève pas le besoin d'une casse fixe dans l'éditeur, ne serait ce pour quand on tape des codes

**Comment by Alex-D** [comment]
En fait, la chasse fixe, c'est à moi de la mettre dans tous les textarea finalement.

Dans l'absolu faudrait une classe spécifique pour que ThS puisse balancer l'éditeur dessus, et moi styliser correctement les champs concernés.

**Comment by cgabard** [comment]
Certes, je voulais surtout que 
1. Tu y pense
2. Firm1 me fasse un fixe rapide pour mes tests :p

**Comment by firm1** [comment]
Pour le fixe rapide, je ne promets rien. Faudra faire du copier/coller pour tester ça je pense.

**Comment by firm1** [comment]
Vous allez devoir utiliser pastebin.com si vous voulez faire des tests en attendant le front-end

**Comment by cgabard** [comment]
pfff NAZE

**Comment by Coy0te** [comment]
Firebug ou userscript, ça ira plus vite xD

**Comment by firm1** [comment]
Déjà fixé.

Je ferme.
