### ISSUE TITLE
Préciser quel doit être le scope du token GitHub

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#6100]
Sur la page https://zestedesavoir.com/membres/parametres/github/, il faudrait préciser quel est le scope minimal requis du token GitHub à générer.

**Comment by Arnaud-D** [comment]
Apparemment, vu que le dépôt est public, [`public_repo`](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes) serait suffisant. Quelqu'un pourrait confirmer ?
