### ISSUE TITLE
Bouton "citer" inutile dans un MP avec une seule personne

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#6104]
**Description du bug**

Ce n'est pas un bug en soi, plus un problème de logique dans l'intégration de l'interface.

Lorsqu'on est seul dans un MP (=> le correspondant est partie ou message d'un bot), on a encore le bouton citer alors que ce bouton ne sert à rien et ne fait rien (ce qui est assez troublant, je pensais pouvoir copier l'origine/le markdown du message avec).

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Aller sur un MP où on est seul (exemple : le message d'un bot) ;
2. Essayer de citer un message ;
3. Constater que ça ne fait rien.

**Comportement attendu**

Plusieurs comportements possibles : 

 - Ne pas avoir le bouton citer ; **(solution la plus simple?)**
 - Avoir un message quand on clique sur le bouton qui indique que le bouton "citer" n'a rien fait et peut-être inviter la personne à ajouter un destinaire au MP pour pouvoir utiliser le bouton ?
 - Citer le message dans une nouvelle conversation ? (C'est à dire créer un MP avec la citation `https://zestedesavoir.com/mp/creer/`) **A mon sens c'est la meilleure solution car elle permet de copier le markdown et de pouvoir facilement copier le message ailleur :)**

**Comment by Arnaud-D** [comment]
Salut,

Pour ma part, je suis partisan de **ne pas afficher le bouton**, puisqu'il ne fait rien. Ça fonction habituelle est en effet de mettre le message dans la zone d'édition, qui n'est pas affichée quand on est seul dans un MP.

Sinon, l'idée de pouvoir copier le markdown d'un message dans le presse-papier me paraît être potentiellement une bonne idée, mais c'est une nouvelle fonctionnalité.
