### ISSUE TITLE
Mettre à jour Chart.js

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#6113]
[Chart.js 3.2](https://github.com/chartjs/Chart.js) est disponible, il y a un peu de travail de migration à faire. Il faudrait en profiter pour supprimer la dépendance à jQuery du fichier `assets/js/charts.js`.

**Comment by artragis** [comment]
https://www.chartjs.org/docs/latest/getting-started/v3-migration.html
