### ISSUE TITLE
Corrections / précisions à apporter sur la procédure d'installation du projet

### ISSUE THREAD

**Issue by entwanne** [zestedesavoir/zds-site#6118]
Salut,

En février dernier je m'étais lancé dans l'installation du projet zds-site dans un environnement docker/debian pour travailler sur une PR.
J'avais été amené à faire quelques modifications à la procédure d'installation pour la mener à bien, donc je voudrais vous lister les différents points qui m'avaient posé problème, et discuter des corrections qui pourraient leur être apportées.

* La procédure présupposait l'installation des paquets `build-essential`, `sudo` et `libssl-dev` sous Debian. Je conviens qu'ils sont assez répandus et donc généralement installés, mais je pense que cela pourrait être précisé.
* Plus délicat, les changements récents sur `cryptography` font que Rust devient une dépendance à l'installation du projet, et devrait donc lui aussi être installé avant le début de la procédure (installation via `rustup` puis configuration du `PATH` par exemple).
* L'environnement virtuel créé lors de la procédure ne contenait pas le paquet `wheel`, ce qui la faisait échouer lors des installations de paquets pip. Ça pourrait être corrigé avec un `pip install wheel` avant de passer à la suite.
* Comme le backend tournait dans un docker, j'avais dû modifier la configuration pour écouter sur d'autres adresses, notamment ajouter `'*'` aux `ALLOWED_HOSTS` et préciser le domaine+port (`0.0.0.0:8000`) à la commande `runserver`.

Voilà, c'est tout pour moi, merci pour vos retours !

**Comment by philippemilink** [comment]
Je viens de faire une PR qui prend en compte tes remarques:
- je n'ai pas eu besoin de `libssl-dev` et `build-essential` est installé comme dépendance de `python3-dev` qui installé par le script d'installation de ZdS, donc pas besoin de l'installer explicitement avant
- problème avec Rust corrigé dans la PR
- ajouts des IPs autorisées pour le dev précisé dans la doc.
