### ISSUE TITLE
Licences

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#614]
- Fichier AUTHORS
- Lien vers pdp dans le readme
- licence CC-BY dans les CGU

**Comment by cgabard** [comment]
Au passage dans les CGU, il manque un h3 [ici](https://github.com/zestedesavoir/zds-site/blob/dev/templates/pages/eula.html#L184)

**Comment by Alex-D** [comment]
Si possible, ce qui touche au contenu, faites dès à présent les PR vers la branche `integration`.

Merci :)

**Comment by devock** [comment]
Quelqu'un s'occuper de cette issue svp ? Le code étant ouvert il faudrait remettre rapidement le fichier AUTHORS et le reste c'est à faire avant la beta. 

Merci merci !

**Comment by Alex-D** [comment]
Est-ce que 

> licence CC-BY dans les CGU
> a été fait ?

Je ne sais pas du tout comment présenter la chose, le reste est fait. A vot' bon cœur !

**Comment by cgabard** [comment]
Rajouter le logo en haut, tout simplement ?

Christophe.

2014-06-04 18:02 GMT+02:00 Alexandre Demode notifications@github.com:

**Comment by Alex-D** [comment]
Logo ajouté :)
