### ISSUE TITLE
S'assurer que la version de KaTeX est bien la même entre zds-site et zmarkdown

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#6140]
Il faudrait s'assurer que la version de KaTeX est bien la même entre zds-site et zmarkdown pour éviter de casser l'affichage des maths.

À mon avis l'idéal serait de vérifier avec Github Actions que la version de KaTeX dans `package.json` est la même que `zmd/node_modules/zmarkdown/package.json`.

**Comment by StaloneLab** [comment]
Pourquoi ne pas utiliser directement le KaTeX de ZMd depuis `packages/zmarkdown/node_modules/katex/dist/`, il y a le `katex.min.css` et le `katex.min.js` dedans, et comme ça on a tout le temps la bonne version.

**Comment by Situphen** [comment]
Il faudra s'assurer qu'on s'occupe bien de l'installation de zmarkdown *avant* la génération des fichiers front, mais bonne idée !
