### ISSUE TITLE
Le smiley ;) insère un smiley :)

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#6141]
Dans le nouvel éditeur, si vous utilisez le bouton dédié pour insérer un smiley clin d'oeil, un simple smiley sourire (`:)`) sera inséré dans le texte.

**Comment by Situphen** [comment]
Il faut modifier `:)` par `;)` dans le fichier `assets/js/editor-new.js` à cet endroit : 

https://github.com/zestedesavoir/zds-site/blob/01ee0fae1923e145deb354e88468306cb8278068/assets/js/editor-new.js#L613-L620

Il faut ensuite vérifier que ce bouton-ci donne bien le smiley clin d'œil et non pas le smiley sourire : 

![Capture d'écran du bouton pour avoir un smiley clin d'œil](https://user-images.githubusercontent.com/6664636/134715348-7a80814c-ee18-4e43-9298-937b609b4626.png)
