### ISSUE TITLE
Ne pas compter les messages masqués dans les billets

### ISSUE THREAD

**Issue by FougereBle** [zestedesavoir/zds-site#6145]
**Description du bug**

La page d'accueil affiche le nombre de commentaire dans la petite bulle en bas de chaque billets. Cependant, le nombre de commentaire masqué est pris en compte dans le nombre de commentaires. Il ne faudrait pas les prendre en compte.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Allez sur le site Zeste De Savoir
2. Poster un commentaire dans un billet
3. Voir sur l'accueil que le nombre de commentaire est de 1
4. Masquer ce commentaire sur le billet
5. Voir sur l'accueil que le nombre de commentaire est toujours de 1

**Comportement attendu**

Le nombre de commentaire ne doit pas prendre en compte les messages masqués.

**Informations techniques**

- OS: macOS
- Navigateur: Safari
- Version/environnement de zds: Production

**Comment by philippemilink** [comment]
Fermé avec #6156
