### ISSUE TITLE
Migrer sous Jinja2

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#617]
Dans une optique d'améliorer les performances globale de rendu des templates, il serait interessant de passer au moteur de rendu du template jinja2.

On peut voir sur les benchmarks réalisés sur [ce topic](http://stackoverflow.com/questions/1324238/what-is-the-fastest-template-system-for-python) que jinja 2 est clairement plus rapide que django template. Une page qui met  `352.68 ms` pour se charger avec Django template, met `36.38 ms` avec Jinja2, soit un gain de performance de ~90% du temps d’exécution.

Les impacts sur le code actuel seront au niveau des : 
- tags/filtres
- les fonctions appelés dans les templates

Un peu de documentation : 
- http://cramer.io/2008/03/29/using-jinja-with-django/
- http://jinja.pocoo.org/

**Comment by SpaceFox** [comment]
> http://cramer.io/2008/03/29/using-jinja-with-django/

Faites gaffe, ce lien a 6 ans et date d'une époque où Django balbutiait. A
voir si on a pas quelque chose de plus récent.

**Comment by zopieux** [comment]
Je n'ai pas eu l'occasion de tester l'intégration de Jinja2 avec Django, qui serait ici le principal sujet problématique. En revanche, je peux vous assurer que Jinja2 est à tous points de vue meilleur que Django. L'héritage est plus puissant, la syntaxe est plus riche et permissive. Saviez-vous par exemple qu'il est impossible de parenthéser des expressions logiques dans le `if` de Django ou de faire des appels de fonctions paramétrés ?

Cela demande un gros travail niveau templates mais je pense qu'il vaut le coup.

**Comment by Alex-D** [comment]
> Cela demande un gros travail niveau templates 

Si c'est plus permissif pourquoi il faudrait faire tant de changements que ça ?

**Comment by zopieux** [comment]
Je ne vois pas le rapport entre la forte expressivité de Jinja2 et le fait qu'il faille déployer de l'énergie pour convertir. D'un côté, c'est un fait, le langage de Jinja2 est plus puissant. Mais par ailleurs, il n'est pas identique à 100% avec celui utilisé par Django, il faut donc reprendre l'_intégralité_ des templates pour corriger les disparités.

**Comment by Alex-D** [comment]
> il faut donc reprendre l'intégralité des templates

J'arrête pas de le faire pour diverses refactos, je ne pense pas que ce soit insurmontable à faire.

**Comment by gustavi** [comment]
Je suis totalement pour, niveau performances c'est vraiment mieux.

**Comment by zopieux** [comment]
Je ne m'avancerai pas sur les performances sans avoir vu un benchmark, mais l'on y gagne nécessairement sur l'aisance d'écriture.

**Comment by Alex-D** [comment]
Mais pour moi, la priorité c'est d'optimiser le back avant de chercher du côté des templates.

**Comment by gustavi** [comment]
https://www.djangoproject.com/weblog/2014/oct/02/crowdfunding-multiple-template-engines-django/

**Comment by gustavi** [comment]
C'est aujourd'hui possible avec Django 1.8 : https://docs.djangoproject.com/fr/1.8/topics/templates/

**Comment by GerardPaligot** [comment]
@gustavi La PR Django 1.8 (https://github.com/zestedesavoir/zds-site/pull/3183) est en cours mais il y a une erreur mystique

**Comment by SpaceFox** [comment]
Ho, on peut se lancer dans ce chantier !

À noter que à priori on est pas obligés de tout migrer d'un coup : https://docs.djangoproject.com/en/1.8/topics/templates/

**Comment by artragis** [comment]
vue le gain de perf apporté par la v20 est-ce toujours pertinent @vhf ?

**Comment by vhf** [comment]
Oui vaguement. C'est hyper basse priorité, clairement. Outre les PR actuelles, faudrait certainement migrer vers la prochaine version de Django par exemple. :)

**Comment by gustavi** [comment]
jinja > templates Django de mon expérience. Avec la 1.10 l'utilisateur de jina est clairement possible et facilement. Je pense que la migration doit se faire petit à petit, sachant qu'il est maintenant possible d'utiliser les deux en même temps sans aucun souci.

Mais oui, c'est pas une priorité.

**Comment by pierre-24** [comment]
J'ai un peu joué avec jinja récement, et je me pose une question : est ce qu'il y a un système de *templatetags* comme avec Django ? On peut définir ses propres macro, mais sinon ?

**Comment by gustavi** [comment]
La réponse à ta question est : oui depuis la 1.10 (ou 1.11 j'ai un doute)
