### ISSUE TITLE
Amélioration du sommaire de la barre latérale des contenus

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#6176]
L'idée est d'améliorer un peu le sommaire qui est dans la barre latérale des contenus ainsi que la liste des catégories de billets. Si vous ne voyez pas ce dont je parle, regardez les captures d'écran plus bas !

Il va falloir agir principalement sur les titres `h4` de cette structure de code : 

```html
<aside class="sidebar">
  <h3>Catégories des billets</h3>
    <h4>Informatique</h4>
    <h4>Sciences de la nature</h4>
    <h4>Sciences humaines et sociales</h4>
    <h4>Autres</h4>
  </h3>
</aside>
```

**Ce que l'on a actuellement**

Dans le fichier SCSS `assets/scss/layout/_sidebar.scss` dédié à la barre latérale, deux bouts de code nous intéressent : 

- la partie commune aux sommaires et à la liste des catégories
  https://github.com/zestedesavoir/zds-site/blob/2378a7ca93110e20f3d0f180e67e692745fa2ebc/assets/scss/layout/_sidebar.scss#L86-L98
- la partie spécifique aux sommaires
  https://github.com/zestedesavoir/zds-site/blob/2378a7ca93110e20f3d0f180e67e692745fa2ebc/assets/scss/layout/_sidebar.scss#L453-L462

**Ce qu'il va falloir modifier**

Il va falloir : 

- ajouter une petite couleur bleue au survol des titres ;
  ```scss
   &:hover, &:focus {
       background: $color-sidebar-hover;
   }
   ```
- aligner un peu mieux le texte verticalement ;
  ```scss
  padding-top: $length-16;
  padding-bottom: $length-4;
  ```
- ajouter une petite bordure très fine entre les titres.
  ```scss
  border-bottom: $length-1 solid $grey-100;
  ```

**Captures d'écran**

![Sommaire du tutoriel Arduino](https://user-images.githubusercontent.com/6664636/134251007-caa16a9d-dc00-4e87-b761-fbbf55e04ba9.png)

![Catégories des billets](https://user-images.githubusercontent.com/6664636/134251056-4962fff7-debd-487a-9c4a-e943b562867f.png)

**Comment by jeanlapostolle** [comment]
Je veux bien tenter cette issue

**Comment by Situphen** [comment]
J'ai discuté avec @jeanlapostolle et il n'a pas le temps de travailler sur ce ticket en ce moment donc ce ticket est libre. N'hésitez pas à continuer le travail qu'il a commencé sur sa PR !
