### ISSUE TITLE
Lien erroné dans le MP d'ajout à la rédaction d'un contenu

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#6177]
**Description du bug**

Le second lien du MP que l'on reçoit lorsqu'on est ajouté comme auteur à un contenu mène vers une page 404.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Avec `user1`, créer un billet
2. Ajouter `user2` comme co-auteur du billet
3. Se connecter comme `user2`et consulter le MP reçu correspondant à l'ajout comme auteur au billet
4. Dans le contenu du MP, le second lien (_Il a été ajouté à la liste de vos contenus en rédaction **ici**._) mène vers une 404.

**Comportement attendu**

Je ne sais pas vraiment quel lien est attendu ici... La liste des contenus en cours de rédaction ?

**Comment by Arnaud-D** [comment]
Le message envoyé utilise ce template : https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/messages/add_author_pm.md

Le problème se situe dans le lien contenu dans le paramètre `index`. Il est initialisé à cet endroit : https://github.com/zestedesavoir/zds-site/blob/01ee0fae1923e145deb354e88468306cb8278068/zds/tutorialv2/views/authors.py#L48

On voit qu'on passe comme argument l'identifiant de l'utilisateur pour fabriquer l'URL, alors qu'on attend son pseudo, comme spécifié ici : https://github.com/zestedesavoir/zds-site/blob/01ee0fae1923e145deb354e88468306cb8278068/zds/tutorialv2/urls/urls_opinions.py#L40

Il faut donc remplacer `user.pk` par `user.username`.
