### ISSUE TITLE
Harmoniser l'encart "Contactez-nous" de la doc avec le nouveau nom du canal Discord des dév

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#6178]
**Description du bug**

L'encart « Contactez-nous » de la doc (voir https://github.com/zestedesavoir/zds-site/blob/dev/doc/source/includes/contact-us.rst) ne colle pas avec le nouveau nom du canal sur Discord.

**Comment reproduire ?**

Comparer la doc avec le nom du canal sur Discord.

**Comportement attendu**

Le nom dans la doc devrait être `développement-de-zds`.

----

Pour corriger ça, c'est facile : 

- changer le fichier précédemment mentionné ;
- générer la doc en local ;
- vérifier que tout va bien (par exemple l'encart en bas des guides devrait être bon).

Voilà un ticket idéal pour se mettre un pied sur le projet. :)

**Comment by ksauvee** [comment]
Je prends
