### ISSUE TITLE
Notifications sur des sujets auxquels on n'a plus accès

### ISSUE THREAD

**Issue by ChantyTaguan** [zestedesavoir/zds-site#6186]
**Description du bug**

Lorsqu'un nouveau sujet est créé dans le forum "Staff" ou lorsqu'une réponse est posté dans un sujet du forum "staff" auquel j'ai répondu, je reçois une notification. N'étant plus membre du staff, je n'ai plus accès aux forum staff et ces notification mènent donc à une 401.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. En temps que Staff, suivre le forum staff, ou un sujet de ce forum
2. Perdre les droits "staff"
3. Quelqu'un répond au sujet suivi ou crée un sujet
4. Notification reçue mais impossible à lire

**Comportement attendu**

On ne devrait pas recevoir de notifications pour un sujet de forum auquel on n'a pas accès

**Comment by SpaceFox** [comment]
Tiens, j’étais persuadé qu’il était corrigé depuis longtemps celui-là !

**Comment by ChantyTaguan** [comment]
@SpaceFox j'ai encore régulièrement des notifs sur des sujets staff...

Je prendrais bien le bug, je profite d'hacktober pour essayer de me remettre au développement python.

A priori je vois 2 manières de résoudre le problème : 

1. à chaque fois que des notifications sont émises suite à un nouveau post sur un sujet, ou suite à un nouveau sujet, on vérifie d'abord si l'utilisateur ayant souscrit au sujet/forum a bien accès au forum en question. Si oui, on crée la notification, si non, on désactive l'abonnement au sujet/forum ;
2. lors de la perte de droits donnant accès à un forum particulier (y e na d'autres que "staff" ?), on parcourt la liste des abonnement du membre et on désactive celles qui sont devenues caduques

L'avantage de la solution 1, c'est qu'elle est facile et rapide à mettre en place. Par contre ça va créer pas mal de vérifications de droits à chaque post/sujet créé. 

La solution 2 est plus propre, mais il faut prévoir de repasser sur tous les abonnements actuels pour désactiver ceux qui sont devenus caduques avant la correction.

**Comment by ChantyTaguan** [comment]
Ou alors ça a été corrigé via la solution 2 mais sans prendre en compte les abo déjà caduques, dont les miens ? A vérifier, j'ai pas encore trouvé à quel endroit du code les droits étaient gérés

**Comment by ChantyTaguan** [comment]
Ah ! C'est bien ça, la solution 2 est implémentée, on vire les abonnements caduques quand on retire un user d'un groupe. Mais les vieux abo qui trainaient avant ça sont toujours là !

**Comment by Situphen** [comment]
Effectivement, la solution actuellement implémentée empêche ce soucis de se produire mais n'a pas eu d'effet rétroactif sur les soucis déjà présents. Dans l'idéal, il faudrait créer un petit script ou une petite procédure pour lister les abonnements qui lient un membre à un objet qui lui est inaccessible pour résoudre pour de bon ce problème. En attendant j'ai effectué la technique de "t'ajouter puis te retirer juste après du groupe Staff" pour que tu résoudre le soucis pour toi.

**Comment by ChantyTaguan** [comment]
Ah, merci @Situphen !

Cela dit, en vérifiant le code de la correction, je pense qu'il manque le désabonnement au forum même. Je teste, et le cas échéant je rajoute ça. Avec aussi un ptit script pour virer les anciens trucs qui trainent.

**Comment by ChantyTaguan** [comment]
D'après mes tests, on est bien désabonné du forum même, mais je ne comprends absolument pas à quel endroit du code ça a lieu. Je vois bien le désabonnement aux sujets, mais je ne vois rien pour le forum. Je suis perplexe...

**Comment by Situphen** [comment]
Les deux types de désabonnement sont gérées dans la fonction `remove_group_subscription_on_quitting_groups` du fichier `zds/notification/receivers.py`. On crée une liste vide `subscriptions` et pour chaque forum, on ajoute dans cette liste l'abonnement au forum s'il existe (`NewTopicSubscription`), les abonnements aux différents sujets s'ils existent (` TopicAnswerSubscription`), puis on supprime tous les abonnements de cette liste.

**Comment by ChantyTaguan** [comment]
Ah punaise merci ! Mais du coup le code qui chipote aux abonnements dans `settings_promote` dans le fichier `zds/member/views.py`, il ne sert à rien ? Enfin il fait le taf une 2e fois pour les abonnements aux sujets quoi. Autant le virer.

**Comment by Situphen** [comment]
Oui en effet, on peut virer ce bout de code !

Ce serait bien d'ajouter quelques tests unitaires d'ailleurs pour s'assurer que ce bug ne réapparaisse pas dans quelques années, dans un nouveau fichier dans `zds/notification/tests/`. Il y a un petit guide sur l'écriture des tests dans la doc (https://docs.zestedesavoir.com/guides/write-backend-tests.html) et sinon tu peux t'inspirer des tests existants pour les notifications.
