### ISSUE TITLE
Barre de recherche dans un profil auteur

### ISSUE THREAD

**Issue by jeanlapostolle** [zestedesavoir/zds-site#6191]
J'ai l'impression de voir se "(prochainement)" dans la barre de recherche sur le profil d'un membre depuis pas mal de temps. 

Pour être clair, je parle de ce champ de recherche.

![image](https://user-images.githubusercontent.com/8135797/136819922-5656dc45-d9a0-4e9c-b18c-fb9afd4b99b3.png)

C'est assez perturbant de l'avoir et ça donne l'impression d'un site pas fini. (Oui je me suis fait avoir plusieurs fois à tenter de faire des recherches avec)

Ne vaudrait-il pas mieux supprimer l'affichage de cette barre en attendant que la fonctionnalité marche ?

**Comment by Arnaud-D** [comment]
Oui, mieux vaut supprimer ça selon moi. Ça ne risque pas d'arriver prochainement de tout façon.
