### ISSUE TITLE
Inclure la variante italique de la Web Font Merriweather

### ISSUE THREAD

**Issue by enzzc** [zestedesavoir/zds-site#6198]
**Problème**

ZdS utilise la Web Font Merriweather (distribuée via Google Fonts) pour les contenus rédigés (billets, articles, tutos). Le rendu du texte mis en italique est en réalité une manipulation graphique laissée à la charge du navigateur, les variantes italiques de la fonte ne lui étant pas disponibles.

Exemple du « faux » rendu italique chez moi :

![Rendu italique factice laissé à la charge du navigateur quand il n'a pas la variante italique de disponible](https://user-images.githubusercontent.com/13155263/138669034-a6808ac8-f56c-4f2f-9c5a-f60dc3586589.png)

La véritable Merriweather italique ressemble en réalité à cela :

![Notez le a qui n'est plus le même](https://user-images.githubusercontent.com/13155263/138669280-d071f3f7-9ba7-4a88-98f5-4c5837fa56b8.png)

**Solution**

Il suffit d'ajouter la variante italique dans la ligne HTML en charge d'inclure les fontes.

Version actuelle : https://github.com/zestedesavoir/zds-site/blob/d74ad28af458f08e7477c2f9d452721d5fd43c8e/templates/base.html#L102

Proposition de version alternative, en ajoutant les variantes `400italic` et `700italic` :

```html
<link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700|Source+Code+Pro:400,700|Merriweather:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
```

**Impact**

D'après mes calculs, la nouvelle feuille CSS générée par ces ajouts implique le chargement de **10 fichiers WOFF2** additionnels, pour un total de poids de **160.6 kB** en plus (non compressés, avec cache froid).

Il est possible de diviser par deux le poids et le nombre de fichiers WOFF2 à récupérer si l'on s'en tient à inclure seulement la variante `400italic` (pas de gras italique, donc), nous ramenant ainsi à 5 fichiers pour environ 80 kB (non compressé) lors du premier téléchargement avec un cache froid.

**Remarque**

Si l'idée vous tente, on peut labelliser cette _issue_ comme bon premier commit.

**Comment by Arnaud-D** [comment]
Au sujet de l'impact relatif de cette nouvelle ressource à télécharger (mais cachable), j'ai fait quelques tests. Les trucs massifs au téléchargement et pas vraiment cachables, ce sont les avatars, notamment ceux des pages de commentaires des contenus. Les plus gros font de l'ordre de 100 ko. Avec le cache, sur l'accueil, je télécharge moins de 50 ko (vs la page complète qui fait ~800 ko).

En bref, si on veut optimiser quelque chose, mieux vaut optimiser la taille des avatars que des polices cachables. Pas tellement de soucis à se faire pour ces quelques variantes de fonte en plus.
