### ISSUE TITLE
Afficher les liens vers les commentaires et messages du forum pour le staff sur le profil 

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#6204]
**Description du besoin**

Quand le staff banni un spammeur, il est utile d'aller regarder tous les messages du forum et commentaires sur les contenus afin de les masquer si nécessaire. Sauf qu'actuellement, le bannissement d'un membre a pour effet de cacher beaucoup des liens sur son profil, y compris pour le staff, et en particulier ceux permettant d'accéder à la liste des messages et commentaires.

**Description de la solution**

Ce serait plus pratique si le staff gardait un affichage de ces liens pour faciliter le travail de modération.

**Comment by Situphen** [comment]
Similaire à #6397

**Comment by philippemilink** [comment]
@Arnaud-D comme discuté [ici](https://github.com/zestedesavoir/zds-site/pull/6500#issuecomment-1563496719), est-ce que tu confirmes que ce que tu demandes dans ce ticket est déjà en place (même en prod) ?

**Comment by Arnaud-D** [comment]
Le comportement a changé : sur dev, même les simples membres peuvent désormais voir les liens en question pour un membre banni. En prod, le comportement a l'air d'être différent, ces blocs ne sont pas affichés pour un simple membre.

J'ai l'impression que les PR récentes sur l'affichage ont introduit de nouveaux comportements, potentiellement indésirables. Bref, on peut certainement fermer ce ticket, mais j'ai l'impression que l'affichage sur le profil est mal spécifié.

**Comment by philippemilink** [comment]
Ok, je ferme, rien ne nous empêche de faire par la suite un nouveau ticket si on trouve un comportement bizarre.
