### ISSUE TITLE
Impossible de MAJ une partie d'un tuto

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#621]
Impossible de mettre a jour une partie d'un tuto, on se prend une erreur 500...
Contexte :
Création d'un mini-tuto. Edition d'un extrait.
La création d'extrait s'est bien passée. Par contre l’édition ne marche pas au moment de la sauvegarde (traceback ci-dessous)

L'edition de l'intro du mini-tuto marche bien cependant.

```
Environment:


Request Method: POST
Request URL: http://zdsappserver/tutoriels/editer/extrait/?extrait=2347

Django Version: 1.6.5
Python Version: 2.7.3
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps',
 'django.contrib.humanize',
 'south',
 'crispy_forms',
 'crispy_forms_foundation',
 'email_obfuscator',
 'pipeline',
 'haystack',
 'munin',
 'zds.utils',
 'zds.pages',
 'zds.gallery',
 'zds.mp',
 'zds.newsletter',
 'zds.article',
 'zds.forum',
 'zds.tutorial',
 'zds.member',
 'django.contrib.admin')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'zds.utils.ThreadLocals',
 'zds.middlewares.SetLastVisitMiddleware.SetLastVisitMiddleware')


Traceback:
File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/zdsenv/ZesteDeSavoir/zds/member/decorator.py" in _can_write_and_read_now
  39.         return func(request, *args, **kwargs)
File "/opt/zdsenv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/opt/zdsenv/ZesteDeSavoir/zds/tutorial/views.py" in edit_extract
  1811.                     action="maj",
File "/opt/zdsenv/ZesteDeSavoir/zds/tutorial/views.py" in maj_repo_extract
  2430.             os.rename(old_slug_path, new_slug_path)

Exception Type: OSError at /tutoriels/editer/extrait/
Exception Value: [Errno 2] No such file or directory
```

**Comment by Eskimon** [comment]
Petit complement:

Voici le contenu des deux variables slug:

```
old_slug_path   
u'/opt/zdsenv/ZesteDeSavoir/tutoriels-private/68_la-transformee-de-hough/problematique.
new_slug_path   
u'/opt/zdsenv/ZesteDeSavoir/tutoriels-private/68_la-transformee-de-hough/--/problematique.md'
```

Il y a deux tirets dans le new, ca doit etre ca qui fait chier...

**Comment by firm1** [comment]
Ah bien vu.

Gros indice que tu as trouvé là, le bug vient bien de là.

**Comment by Taluu** [comment]
Je viens de rencontrer le problème, donc un +1 là dessus (merci la recherche :D)

**Comment by ShigeruM** [comment]
Je pense que le problème vient de la view edit_extract, à [cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L1806). Le chapitre n'ayant pas de slug puisqu'on est dans un mini-tuto, le chemin du fichier .md de l'extrait est directement dans le répertoire du tuto (chapter_tutorial_path). Donc on doit juste utiliser :

`chapter_part = os.path.join(chapter_tutorial_path)`

J'étais parti pour faire la PR mais je ne parviens pas à écrire le test qui va bien. En fait je ne comprends pas pourquoi les factories ne font pas exactement la même chose que les vues associées utilisées par le site (exemple : ChapterFactory et la vue add_chapter). Mais bref, c'est un autre problème ça.

**Comment by Coy0te** [comment]
Dans le design actuel, où sont les boutons d'édition correspondant aux parties / chapitres ? Sur la version hors-ligne d'un cours (http://zestedesavoir.com/tutoriels/off/76/le-protocole-bittorrent/), je n'ai trouvé que le bouton pour éditer intro / conclusion, rien concernant le contenu du cours.

**Comment by cgabard** [comment]
C'est peut être une régression du nouveau design ? Ce ne serait pas la première :p

**Comment by Coy0te** [comment]
C'est ce que je pense aussi, mais comme c'est vendredi matin et que j'ai pas les yeux en face des trous, je préfère poser la question avant de jeter des bûches à Alex ! :D

**Comment by Coy0te** [comment]
D'ailleurs pour préciser, je vous bien tout ce qu'il faut sur un tuto qui m'appartient. Toutes les fonctionnalités passent bien, **sauf le déplacement de partie**. La modale affichée est foireuse (le select contient des entrées "déplacer avant / après" qui restent grisées), et l'entrée qui s'intitule "Monter" (aucun entrée pour "Descendre" d'ailleurs) provoque une internal server error.

A côté de ça, voici un récapitulatif de ce qui déconne sur le tuto hors-ligne d'un autre membre. En tant que Staff je vois : 
- un bouton pour ajouter un extrait à un cours, et ça marche ;
- un bouton pour y ajouter un auteur, mais je me prends une 404 une fois que je valide la modale ;
- un bouton pour éditer intro / conclusion, et ça marche ;
- pas de bouton pour éditer / déplacer les parties.

Bref, y'a du travail.

**Comment by Alex-D** [comment]
Y a pas mal de choses de corrigées dans la PR #787 (notamment la modale de déplacement, qui ne fonctionnait pas sur la version précédente...)

En fait, ce qu'il manque ce sont les boutons en tant que staff c'est ça ? Si oui, je ne l'ai tout simplement pas prévu, et je n'ai pas souvenir que s'eut été présent dans la version "dev" précédente.

Faut attendre le pull de la prod pour recheck tout ça du coup. A priori, les droits des staff ne sont pas pris en compte pour afficher les boutons actuellement (j'en ai pas souvenir).

Edit : par contre, pour le coup, c'est deux choses différentes : le front et le back. Sur cette issue on parle du back (donc l'ajout d'auteur qui bug, c'est probablement du back) tandis que le reste c'est globalement du front. Ca serait pratique de pas tout mélanger :)

**Comment by Coy0te** [comment]
Différent ok, mais perso je ne sais pas "a priori" que le fail de l'ajout d'un auteur c'est du back ou du front. Pareil pour le déplacement de partie.

Le seul élément front dont j'avais la certitude, c'est l'absence des boutons.

**Comment by Alex-D** [comment]
Désolé, en effet je vois ça de mon point de vue, mais si on a pas la tête dans le code on ne peut pas savoir, désolé ^^"

Du coup le premier problème énoncé reste entier, l'ajout d'auteur fonctionne chez moi. Pourrais-tu préciser depuis quelle page tu effectues cette opération ?

> pas de bouton pour éditer / déplacer les parties.

Il me semble que le back n'a pas prévu ça. Que l'on me corrige si tel n'est pas le cas.

**Comment by Coy0te** [comment]
> Du coup le premier problème énoncé reste entier, l'ajout d'auteur fonctionne chez moi. Pourrais-tu préciser depuis quelle page tu effectues cette opération ?

Pour l'ajout d'auteur, sur n'importe quel tuto dont je ne suis pas l'auteur ça merde. Quand je rentre un pseudo dans la modale et que je valide, ça me renvoie vers l'URL `http://zestedesavoir.com/tutoriels/modifier/tutoriel/` qui donne une 404.

> Il me semble que le back n'a pas prévu ça. Que l'on me corrige si tel n'est pas le cas.

Ça s'affiche et ça marche pour les tutos dont on est auteur, donc il doit pas manquer grand chose pour que ça s'affiche et ça marche sur les autres tutos.

**Comment by Alex-D** [comment]
Ok d'ac, du coup j'ai une question aux devs back : est-ce qu'un co-auteur peut ajouter d'autres co-auteurs, où est-ce nécessaire l'auteur initial qui doit faire ça ?

Car du coup il faut adapter les templates si c'est la seconde possibilité.

**Comment by Coy0te** [comment]
Je ne sais pas pour les co-auteurs, mais un Staff doit pouvoir le faire, et ce n'est pas le cas actuellement.

**Comment by firm1** [comment]
Pour info.
Avant le merge integration un staff pouvait rajouter n'importe quel co-auteur, ainsi qu'en supprimer.
Un co-auteur pourvait aussi rajouter d'autres co-auteur etc.

**Comment by Coy0te** [comment]
Amélioration minime : maintenant il n'y a plus de 404 quand on essaie d'ajouter un auteur en tant que Staff sur un article dont on est pas l'auteur. Par contre, ça ne marche toujours pas. xD

**Comment by ShigeruM** [comment]
Si je comprends bien, de toute cette issue (qui a soulevé plusieurs problèmes différents) il ne reste plus que l'ajout/suppression d'auteur qui renvoie une 404 quand on est staff ? Je viens de faire une PR pour corriger ce problème.

**Comment by Taluu** [comment]
Fix lors du merge via c00bffc00973ae7fa1663b4885f25899ae20670b

**Comment by Taluu** [comment]
Je réouvre au cas où quelqu'un veut faire un dernier test de validation, et laisser ainsi genre @Eskimon ou @ArnaudCalmettes fermer s'ils jugent que c'est OK

**Comment by Eskimon** [comment]
Bon autant pour moi, on peut fermer.
