### ISSUE TITLE
[EPUB] Affichage problématique

### ISSUE THREAD

**Issue by okalm** [zestedesavoir/zds-site#6223]
Bonjour,

Juste pour signaler qu'il y a un problème d'affichage avec la version epub de la documentation sur le C, le PDF ne pose pas de problème (merci au passage), mais le epub est illisible malheureusement. J'ajoute une image qui sera plus parlante en précisant que toutes les pages s'affichent de cette manière du début à la fin.

![img_epub_c](https://user-images.githubusercontent.com/40634668/150141943-ce89faae-0765-4c44-88f6-5348b17fd907.png)

**Comment by Arnaud-D** [comment]
Tout ce qui est balises en dehors des titres est échappé, ce qui le fait évidemment apparaître en texte brut.

La dernière publication « saine » est celle-là, publiée fin août : [62 831 853 071 750 décimales de π. Et maintenant ?](https://zestedesavoir.com/articles/4016/62-831-853-071-750-decimales-de-p-et-maintenant/). Les publications postérieures ont le soucis et celles d'avant ne l'ont pas.

---

En testant, l'anomalie de génération apparaît avec le  [correctif de sécurité de septembre](https://github.com/zestedesavoir/zds-site/commit/a0c06d51fbab01f06154ab38edbe6533925168fc).

Plus particulièrement, il semble qu'il se passe quelque chose avec ces deux lignes ajoutées dans le correctif, puisque le problème n'apparaît plus quand on les enlève.

https://github.com/zestedesavoir/zds-site/blob/a0c06d51fbab01f06154ab38edbe6533925168fc/zds/utils/templatetags/emarkdown.py#L163-L164

---

Après un peu de lecture, je crois que je tiens un début de solution.

Django gère l'échappement automatiquement dans une certaine mesure, et arrive à suivre si les chaînes renvoyées par les filtres sont safe ou pas. On peut perdre cette information en cours de route, et je pense que c'est ce qu'il s'est passé avec l'ajout des `replace` à la suite de l'appel à `emarkdown`.

Il est possible si on est sûr de son coup de forcer le marquage comme safe avec [mark_safe](https://docs.djangoproject.com/en/4.0/ref/utils/#django.utils.safestring.mark_safe), et éviter ainsi à Django d'échapper tout ce qui ressemble à du HTML. Il y a plein une [page de doc intéressante à ce sujet](https://docs.djangoproject.com/en/4.0/howto/custom-template-tags/#filters-and-auto-escaping).

J'ai fait un test rapide en passant tout le retour de la fonction `epub_markdown` dans un `mark_safe` et ça semble résoudre le problème. Je ne suis pas sûr que c'est le meilleur choix, mais ça donne une direction dans laquelle continuer à investiguer.

**Comment by philippemilink** [comment]
Corrigé avec #6318.
