### ISSUE TITLE
Numéroter automatiquement la titraille (sections, parties, H1, H2…) en HTML

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#6228]
**Description du besoin**

Aujourd’hui, sur les pages HTML, les différents niveaux de titre (titres de section et de partie comme titres internes au contenu) ne sont pas numérotés. On a bien des liens directs qui sont très pratiques, mais rien de visuel.

Une numérotation visuelle me semblerait utile, d’autant plus que le contenu est long.

**Description de la solution**

Ajouter une numérotation automatique des différents niveaux de titres à travers tout le contenu, comme ce qui est fait aujourd’hui dans les PDF.

Je n’ai aucune idée de la difficulté technique : c’est fait dans les PDF mais je suppose que c’est une fonctionnalité de LaTeX qui la gère.

**Description des alternatives**

Ne rien faire est une alternative valable selon la complexité et les impacts, à discuter.

**Contexte additionnel**

_Rien ici_.

**Comment by entwanne** [comment]
À noter qu'il y a une numérotation qui existe sur les sections : on voit que les ancres HTML sont précédées d'un numéro correspondant à leur position dans la page.

**Comment by artragis** [comment]
Est-ce que ceci conviendrait?
![hierarchy](https://user-images.githubusercontent.com/1523653/180871521-eff33d6d-795c-470e-87c5-719c52485c07.png)

**Comment by AmauryCarrade** [comment]
Suite aux discussions dans la PR associée #6361, il a été décidé que la complexité technique en l'état actuel de notre CSS rendant l'implémentation particulièrement piégeuse, le mieux pour le moment était de ne rien faire. Voir la PR pour les arguments et les risques, mais en bref, il est assez délicat de gérer proprement tous les cas, et on a des risques de voir apparaître des 0.x un peu partout, dans les billets rédigés dans l'intro, ou plus grave encore, à des endroits aléatoires sur le site.

Je ferme donc, mais si Yuzu arrive à terme et que le CSS devient plus clean, ce qu'est l'un des objectifs principaux, c'est quelque chose qu'on pourra envisager à nouveau. Alors, il suffira de rouvrir ce ticket !
