### ISSUE TITLE
Update to remark@13

### ISSUE THREAD

**Issue by imhul** [zestedesavoir/zds-site#6236]
Do you have any plans to update to actual remark version?

**Comment by StaloneLab** [comment]
The migration is planned, but long, and we lack resources.

Please refer to https://github.com/zestedesavoir/zmarkdown/issues/416 for more information.

**Comment by Arnaud-D** [comment]
Je propose de fermer comme c'est un ticket pour zmd et pas directement pour zds-site. Des objections ?

**Comment by philippemilink** [comment]
Closing, since Stalone answered and as Arnaud-D mentionned (in French) this issue is about [zmd](https://github.com/zestedesavoir/zmarkdown) and not zds-site.
