### ISSUE TITLE
Certains boutons du nouvel éditeur ne fonctionnent pas

### ISSUE THREAD

**Issue by Nek-** [zestedesavoir/zds-site#6243]
**Description du bug**

Les smilies, et les blocs spéciaux ne fonctionnent pas sur le nouvel éditeur sur mon ordinateur.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Rédiger un contenu (constaté sur une édition de tuto);
2. Essayer d'ajouter un smiley ou un bloc spécial.

**Comportement attendu**

Ajout du bloc ou du smiley dans le contenu.

**Informations techniques**

- OS: macOS Monterey
- Navigateur: Chrome Version 98.0.4758.102 (Build officiel) (x86_64)
- Version/environnement de zds: production

Note: ça fait un moment que j'ai remarqué que ça déconnait, je me suis dit qu'il fallait bien le remonter un jour. J'ai pas vu d'autre tickets à ce sujet...

**Comment by Situphen** [comment]
Notre éditeur est une version modifiée de l'éditeur EasyMDE. Ce soucis a été corrigé chez eux (avec [cette PR](https://github.com/Ionaru/easy-markdown-editor/pull/285) pour les personnes curieuses) mais depuis on n'a toujours pas mis à jour la version de EasyMDE sur laquelle on s'appuie. Un des gros soucis actuellement c'est que l'on applique beaucoup de modifications par dessus EasyMDE au point que c'est compliqué de s'assurer qu'on ne casse rien lorsqu'on le met à jour.

**Comment by Situphen** [comment]
Corrigé par #6245 (ce sera donc en production dans la prochaine version)
