### ISSUE TITLE
Option sur le profil : masquer l'activité sur le forum / les commentaires

### ISSUE THREAD

**Issue by EtoileFilante** [zestedesavoir/zds-site#6254]
**Description du besoin**

En tant qu'auteur, il m'arrive de partager mes contenus sur Linkedin notamment. J'y invite mes contacts à aller lire mes contenus. Hors en étant sur mes contenus, en un clic on tombe sur mon profil où l'on voit des messages et sujets postés en 2014, qui sont en bonne partie liés à ma présence à des évènements IRL de ZdS. Je trouve ça embêtant d'avoir ça juste à côté de la liste de mes contenus qui sont la partie "sérieuse" de mon profil.

**Description de la solution**

Ce serait super d'avoir l'option de masquer la partie derniers sujets créés et activité sur le forum (voir même "commentaires publiés") sur son profil depuis nos paramètres utilisateur

**Comment by Migwel** [comment]
Ca m'a l'air relativement simple, je peux m'en charger.

Une suggestion pour le texte précis à utiliser ? Quelque chose comme "Masquer mes activités de forum sur mon profil" ?

**Comment by Arnaud-D** [comment]
Salut, je verrais bien une section "Visibilité des sections du profil" dans les paramètres du profil, qui aurait deux boutons :

1. Masquer l'activité sur le forum
2. Masquer l'activité dans les commentaires de publication

Cette section aurait aussi un paragraphe pour expliquer que cela reste visible par le staff à des fins de modération.

Le bouton 1. masque l'encart "Forum" *et* les derniers sujets créés. Le bouton 2 masque seulement la dernière ligne de l'encart "Contenu".

**Comment by Migwel** [comment]
Je vois l'idée mais est-ce qu'on ne rend pas ça plus complexe que nécessaire en offrant deux options si granulaires ? Je me trompe peut-être mais je pense que cette option ne sera utilisée que par un nombre très restreint d'utilisateurs. Et dans ces utilisateurs, j'ai du mal à voir quel cas d'utilisation voudrait qu'il soit important de cacher uniquement une des activités et pas l'autres.
Donc j'ai l'impression que ces deux options seront toujours soit cochées ensemble soit inutilisées ensemble.

**Comment by Arnaud-D** [comment]
Fais comme tu veux, les deux me semblent acceptables. ^^
