### ISSUE TITLE
Les chapitres non validés apparaissent dans les exports des contenus

### ISSUE THREAD

**Issue by entwanne** [zestedesavoir/zds-site#6265]
**Description du bug**

Je viens de constater que les exports de contenus (tous formats confondus a priori, je n'ai pas vérifié l'epub) contenaient les chapitres non validés (`ready_to_publish` à `False`) du contenu.

Le traitement semble différent suivant le format d'export, par exemple le markdown ne contient que la structure des chapitres en question (titres) tandis que le PDF contient aussi leurs contenus.

**Comment reproduire ?**

Simplement consulter [l'export PDF](https://zestedesavoir.com/tutoriels/pdf/2514/un-zeste-de-python.pdf) ou [Markdown](https://zestedesavoir.com/tutoriels/md/2514/un-zeste-de-python.md) du cours [Un zeste de Python](https://zestedesavoir.com/tutoriels/2514/un-zeste-de-python/) par exemple.

**Comportement attendu**

Les chapitres "Expressions rationnelles", "Un peu de réseau", "Plusieurs tâches en même temps", "Packaging", "Bases de données", "Les erreurs courantes en Python" et la partie "Exercices" ne devraient pas apparaître dans les exports.

**Capture d'écran**

![Export PDF](https://user-images.githubusercontent.com/2658945/159258854-7c80b983-3b40-4f16-b491-d288cbafc9fb.png)

![Export Markdown](https://user-images.githubusercontent.com/2658945/159258858-ab6acdee-6580-45bc-8d67-d910b5aec90f.png)

**Comment by Situphen** [comment]
J'ai trouvé le soucis pour l'export Markdown, c'était assez simple.

Pour l'export PDF, j'ai l'impression qu'on envoie bien une étiquette `ready_to_publish` à zmarkdown mais que celui-ci ne la prend pas en compte. Il y a donc deux solutions : 

- ouvrir un ticket côté zmarkdown pour que cette option soit prise en compte dans le futur ; 
- ou alors, ne pas envoyer les conteneurs avec `ready_to_publish` à `False` à zmarkdown.

Si on part sur la deuxième option, je pense que ces quelques modifications devraient suffire : 

```diff
diff --git a/zds/tutorialv2/publication_utils.py b/zds/tutorialv2/publication_utils.py
index e3aa5e84b..485b2cf61 100644
--- a/zds/tutorialv2/publication_utils.py
+++ b/zds/tutorialv2/publication_utils.py
@@ -414,7 +414,7 @@ class ZMarkdownRebberLatexPublicator(Publicator):
         replaced_media_url = settings.MEDIA_URL
         if replaced_media_url.startswith("/"):
             replaced_media_url = replaced_media_url[1:]
-        exported = export_content(public_versionned_source, with_text=True)
+        exported = export_content(public_versionned_source, with_text=True, remove_not_ready_to_publish=True)
         # no title to avoid zmd to put it on the final latex
         del exported["title"]
         content, metadata, messages = render_markdown(
diff --git a/zds/tutorialv2/utils.py b/zds/tutorialv2/utils.py
index 1f2b45cd2..2561b0fa9 100644
--- a/zds/tutorialv2/utils.py
+++ b/zds/tutorialv2/utils.py
@@ -696,7 +696,7 @@ def export_extract(extract, with_text):
     return dct
 
 
-def export_container(container, with_text=False):
+def export_container(container, with_text=False, remove_not_ready_to_publish=False):
     """Export a container to a dictionary
 
     :param container: the container
@@ -705,6 +705,10 @@ def export_container(container, with_text=False):
     :rtype: dict
     """
     dct = OrderedDict()
+
+    if remove_not_ready_to_publish and not container.ready_to_publish:
+        return dct
+
     dct["object"] = "container"
     dct["slug"] = container.slug
     dct["title"] = container.title
@@ -735,14 +739,14 @@ def export_container(container, with_text=False):
     return dct
 
 
-def export_content(content, with_text=False):
+def export_content(content, with_text=False, remove_not_ready_to_publish=False):
     """Export a content to dictionary in order to store them in a JSON file
 
     :param content: content to be exported
     :return: dictionary containing the information
     :rtype: dict
     """
-    dct = export_container(content, with_text)
+    dct = export_container(content, with_text, remove_not_ready_to_publish)
 
     # append metadata :
     dct["version"] = 2.1
```

**Comment by philippemilink** [comment]
Corrigé avec #6266 pour le Markdown et #6267 pour le PDF.

Merci d'avoir rapporté le problème !
