### ISSUE TITLE
Ajout de l'adresse postale dans le formulaire d'adhésion à l'asso

### ISSUE THREAD

**Issue by Fumble** [zestedesavoir/zds-site#627]
Je viens de recevoir un mail de test pour le formulaire d'adhésion à l'asso de la part de Christophe.
Il serait nécessaire d'ajouter les champs relatifs à l'adresse postale (deux lignes d'adresse + CP + ville + pays) pour l'adhésion d'un membre.

**Comment by cgabard** [comment]
Au passage, pour @SpaceFox qui a fait le formulaire, je me demande si l'adresse du mec comme "reply-to" est judicieux. 

Si on les reçoit sur la ML, il est censé y avoir un minimum de discussion, ne serait ce que des "Ok pour moi". Là on risque de lui envoyé aussi. Alors qu'en soit il est censé juste avoir la réponse final.

**Comment by SpaceFox** [comment]
J'y ai pas pensé tiens. Du coup, en effet c'est un peu débile :D

**Comment by Eskimon** [comment]
Je me met dessus si ca gene personne (c'est de mon niveau XD )

**Comment by firm1** [comment]
C'est fixé, et mergé.

Je ferme. Merci à notre caribou Français.
