### ISSUE TITLE
L'export Markdown des billets ne contient pas les sections

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#6281]
**Description du bug**

L'export Markdown des billets ne contient pas les sections des billets, seulement l'introduction et la conclusion. Très certainement lié à https://github.com/zestedesavoir/zds-site/pull/6266.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Créer un billet
2. Ajouter une section
3. Publier le billet
4. Exporter le billet au format Markdown, avec par exemple : `python3 manage.py export_markdown ${id_contenu}`
5. Consulter le fichier Markdown généré.

**Comment by philippemilink** [comment]
Si quelqu'un souhaite s'attaquer au bug, je joins le [patch](https://github.com/zestedesavoir/zds-site/files/8392944/test.diff.txt) qui contient déjà le test correspondant (c'est comme ça plus facile de tester la correction du bug ; il n'est pas complet et demande peu de refacto, mais c'est déjà un début pour tester facilement).

**Comment by Situphen** [comment]
Oups ! Je crois que la solution est d'effectuer ces modifications : 

```diff
---{% if child.ready_to_publish %}
+++{% if content.has_extracts or child.ready_to_publish %}
```
```diff
---{% if subchild.ready_to_publish %}
+++{% if child.has_extracts or subchild.ready_to_publish %}
```

Car soit il s'agit d'extraits (dernier niveau de conteneurs) et dans ce cas-là il n'y a pas d'étiquette `ready_to_publish`, soit il s'agit de conteneurs avec des sous-conteneurs et il y a l'étiquette `ready_to_publish`.
