### ISSUE TITLE
Factoriser adresse mail automatique

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#629]
Actuellement les mails auto sont envoyés depuis `noreply@zestedesavoir.com` et cette adresse est en dur a plusieurs endroits dans le code [cf ce liens](https://github.com/zestedesavoir/zds-site/search?q=noreply%40zestedesavoir.com&type=Code)

Il serait pertinent : 
- de factoriser ça en la declarant dans le setting.py
- de rajouter un avertissement juste au dessus qu'elle ne doit pas être changé sans prévenir le CA de l'asso (car la gestion du formulaire d’adhésion a besoin de la connaitre)

**Comment by Eskimon** [comment]
Ça devrait se faire assez vite, d'après GH il n'y a que 6 occurrences à bidouiller (mais d'après mon sublime text il y en a 7...).

**Comment by cgabard** [comment]
C'est pour ça que je vous avait mit le tag "facile"

**Comment by Eskimon** [comment]
La PR est mergé, je considère donc que c'est OK, je ferme :)
