### ISSUE TITLE
Erreur 500 à la création d'une galerie avec un slug vide

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#6294]
À la création d'une galerie, si on choisit un titre de galerie qui mène à un slug vide comme par exemple ":", on se prend une 500 au lieu d'un formulaire invalide avec une erreur explicite (ce qu'on a sur les tutos par exemple).

**Comment by Migwel** [comment]
Je vais essayer d'y jeter un oeil
