### ISSUE TITLE
manque des smiley bounce, popcorn, et cthulhu

### ISSUE THREAD

**Issue by NightProg** [zestedesavoir/zds-site#6305]
**Description du bug**

Il manque les smileys bounce, popcorn, et cthulhu.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Connectez vous sur votre compte sur zds.
2. Allez sur n'importe quelle topic sur le forum.
3. Cliquez le smiley heureux dans le nouvel éditeur.

**Comportement attendu**

normalement on doit voir les smiley bounce, popcorn, et cthulhu

**Capture d'écran**

<img width="65" alt="Capture d’écran 2022-05-12 à 20 18 14" src="https://user-images.githubusercontent.com/85784092/168142388-32523be0-7256-4360-b09b-b81d1e46eb4f.png">

**Informations techniques**

- OS: macos monterey 12.3.1
- Navigateur: Chrome v101
- Version/environnement de zds: production

**Comment by SpaceFox** [comment]
Note : le smiley Cthulhu étant à l’origine un _easter egg_, son absence peut être considérée comme normale.

^(;,;)^
