### ISSUE TITLE
Le code HTML des ePUBs est visible

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#6313]
Je ne sais pas si c'est un bug de zds-site ou zmd.

Créer un billet, le publier. L'export au format ePUB contient le contenu attendu, mais on voit les balises HTML (ce qui rend le fichier illisible).

Le bug est présent avec zmd 10 et 11.

**Comment by artragis** [comment]
y'a un "mark safe" qui a dû disparaître
