### ISSUE TITLE
Colorier les forums privés dans la liste des forums comme dans le menu déroulant 

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#6351]
Dans le menu déroulant du Forum, les forums privés apparaissent en orange, mais pas sur la page principale des forums, qui liste tous les forums.

Par cohérence, ce serait sans doute bien que les forums privés apparaissent également en orange sur la page des forums.

![image](https://user-images.githubusercontent.com/5911232/178106392-6caaee0c-9ffe-4b71-ab91-d0d7172490bd.png)

**Comment by Situphen** [comment]
**Aide**

Extrait du code HTML du menu déroulant : 

https://github.com/zestedesavoir/zds-site/blob/6e9ad77809d4180a650cc1792dd836ba8e792941/templates/header.html#L173-L177

Extrait du code SCSS du menu déroulant : 

https://github.com/zestedesavoir/zds-site/blob/0501c74a94dfc62579574efc8a3b893c50f7176a/assets/scss/components/_header-dropdown.scss#L96-L98

Code HTML de la page des forums : `templates/forum/index.html`
