### ISSUE TITLE
Sortir du dépôt Git les données GeoLite

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#6384]
Les données GeoLite, utilisées pour la géolocalisation des adresses IP des membres, doivent être mises à jour (la version actuellement utilisée date de 2020 et une mise à jour est proposée chaque semaine).

Cependant, ce fichier de données a une taille de 60 Mo, donc ce n'est pas vraiment une idée de mettre à jour simplement ce fichier, faire un commit et une PR : les dépôts Git vont grossir très vite si on met régulièrement à jour le fichier.

Il faut donc sortir ce fichier du dépôt : 
- [x] supprimer le fichier du dépôt
- [x] permettre l'utilisation du site si le fichier n'est pas présent (notamment pour l'environnement de dev)
- [x] mettre à jour les instructions d'installation pour indiquer comment récupérer le fichier et où le placer
- [x] mettre à jour https://github.com/zestedesavoir/ansible-zestedesavoir pour qu'il récupère et installe tout seul le fichier (il me semble que MaxMind met à disposition une API pour ce genre de choses)

**Comment by AmauryCarrade** [comment]
Il est en effet possible d'utiliser leur API, avec une clef d'API, pour télécharger la dernière version de la base de données. [La documentation est ici.](https://dev.maxmind.com/geoip/updating-databases?lang=en#directly-downloading-databases)

Peut-être faudrait-il stocker aussi quelque part la dernière date de mise à jour, afin de ne pas retélécharger le fichier à chaque fois, sauf si ce n'est pas un souci pour vous — et éventuellement prendre soin de ne pas le télécharger si exécuté en mode CI ?

**Comment by AmauryCarrade** [comment]
Le fichier étant lourd, peut-être serait-il également pertinent de songer à nettoyer l'historique du dépôt de ce fichier ? En fonction des conséquences que ça aurait, bien sûr (à éviter si ça peut avoir des conséquences louches, mais si ça permet de réduire le clone du dépôt de quelques centaines de Mio, ça peut valoir le coup).

**Comment by AmauryCarrade** [comment]
Autre solution que l'on peut considérer (à voir son coût et sa praticité, cependant) : utiliser GitLFS. Mais sachant que l'offre gratuite de GitHub est d'un Gio de stockage et d'autant de bande passante, ça me semble étroit (surtout la bande passante).

**Comment by Arnaud-D** [comment]
J'ai lié un ticket sur le dépôt Ansible, comme ça, on a la tâche là-bas. Ça évite d'avoir des tickets concernant deux dépôts ici. Je pense que c'est plus simple comme ça. :)
