### ISSUE TITLE
Mettre une image dans une autre balise md masque la légende

### ISSUE THREAD

**Issue by PetitMote** [zestedesavoir/zds-site#6391]
**Description du bug**

Définir une image centrée en markdown retire la légende. C’est également le cas pour un lien.

À noter que si l’image n’est pas dans une autre balise md, elle est centrée et la légende apparaît comme il faut. Par contre, avec le lien, elle passe à gauche et la légende disparaît.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Créer un contenu
2. Importer une image
3. L’insérer et la mettre dans un lien (type miniature + lien vers grande taille)
4. La légende n’est pas visible

**Comportement attendu**

La légende devrait rester visible, sous l’image.

**Capture d'écran**

![image](https://user-images.githubusercontent.com/81959473/189521539-7b2cfcd8-61fc-425e-a0c0-fc85065c137e.png)

**Comment by AmauryCarrade** [comment]
A priori, si ça vient de la galerie, alors le Markdown utilisé doit être similaire à ceci, je te laisse confirmer : 

```markdown
![La pseudo-légende](https://url.png)
```

Si oui, alors ce n'est **pas un bug**, car ce dont tu parles n'est pas la légende (contrairement à ce que laisse entendre l'interface de la galerie), mais le _texte alternatif_, qui n'a pas vocation à être affiché, sinon aux lecteurs d'écran.

L'affichage comme légende du texte alternatif n'est qu'une fonctionnalité palliative due au fait que beaucoup confondaient les deux. Pour rappel, la légende donne un contexte à l'image, l'enrichissant d'éléments supplémentaires, de sources, etc., quand le texte alternatif décrit l'image de la façon la plus précise possible, sans apporter aucun élément supplémentaire, de telle façon qu'une personne ne pouvant voir l'image (si la personne est malvoyante ou si l'image n'a pas chargé, par exemple) puisse la visualiser quand même. La légende peut contenir du markdown, quand le texte alternatif est purement textuel.

zmarkdown affiche le texte alternatif comme légende — et centre l'image — dans le cas, et uniquement le cas, où une image est seule dans son paragraphe, i.e. qu'elle est isolée du reste du contenu par au moins une ligne vide de chaque côté. Faire de l'image un lien, ou la centrer manuellement, brise cette règle, d'où la disparition de la légende.

C'est un comportement recherché et, à la limite, la question pourrait se poser de ne _pas_ afficher la légende tant qu'elle n'est pas explicitée (voir ci-dessous) — car un texte alternatif n'est pas une légende et, si bien rédigé, il sera par nature superflu à une personne en capacité de voir l'image. Afficher le texte alternatif comme légende pousse à mal renseigner ces textes alternatifs, les rendant peu pertinents pour les personnes en ayant vraiment besoin.

La bonne façon d'ajouter une légende à une image (une _vraie_ légende), [c'est d'utiliser l'attribut `Figure:`](https://zestedesavoir.com/tutoriels/249/rediger-sur-zds/#7-4781_medias), comme ceci : 

```markdown
![Le texte alternatif](https://url.png)
Figure: La légende de l'image
```

S'il en est, le bug ici n'est pas au niveau de zmarkdown, mais de l'interface de la galerie qui n'est peu claire et qui devrait parler de texte alternatif (et éventuellement, permettre d'ajouter une légende séparée, générant le bon extrait markdown complet). Je ferme donc, mais on pourra rouvrir dés fois qu'on veuille transformer ce ticket en un ticket pour le vrai problème.

_P.-S. Pour les demandes concernant le rendu du Markdown, [le bon dépôt pour ouvrir des tickets est celui de zmarkdown](https://github.com/zestedesavoir/zmarkdown). Je ne déplace pas car finalement, ça ne concerne pas zmd._
