### ISSUE TITLE
Impossible de mettre en bêta un contenu avec « Auteur externe » dans les auteurs

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#6392]
**Description du bug**

Lorsqu'on tente de mettre en bêta un contenu qui a un compte bot (par exemple, Auteur externe) dans les auteurs, une erreur interne est renvoyée. Cela est dû à une exception `NotReachableError` qui n'est pas gérée.

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Créer un contenu avec un compte bot comme auteur
2. Mettre en bêta ce contenu

**Comportement attendu**

Soit ignorer cette erreur, soit afficher un message dans lequel on demande à ce que « Auteur externe » soit enlevé des auteurs.

**Comment by philippemilink** [comment]
On peut ignorer l'erreur en ignorant l'auteur externe et s'inspirer de la PR #6356.

**Comment by philippemilink** [comment]
Et également faire le fix pour la route `contenus/enlever-auteur/{pk}/` qui soulève la même erreur lorsqu'on essaie d'enlever l'auteur externe d'un contenu (rapporté par Sentry).
