### ISSUE TITLE
Autoriser le staff à afficher les biographies des membres bannis

### ISSUE THREAD

**Issue by PetitMote** [zestedesavoir/zds-site#6397]
Hello,

**Description du besoin**

Il pourrait être pratique d’autoriser le staff à lire une biographie bannie. Dans le cas où un membre conteste son bannissement, on n’a plus accès au contenu qui nous a poussé à le bannir pour vérifier ce qui a motivé la décision. Je ne vois pas, comme ça, de grosse raison pour l’empêcher.

**Comment by Situphen** [comment]
Similaire à #6204
