### ISSUE TITLE
Commande tout en un pour relancer les workers

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#640]
Vu que je fais pas mal de tests sur le serveur de preprod, j'ai du taper pas mal de fois les commandes pour relancer le serveur et tout ça, donc j'ai créé un alias :

```
git pull && kill -15 `ps | grep gunicorn | cut -d\  -f1 | head -n1` && gunicorn_django --workers=4 --bind 178.32.53.245:8001 &
```

Sous le nom de `dj_restart` (même si ça update + restart... c'est très rapide et au moins ça met à jour).

Pour faire simple la commande fait dans l'ordre :
- Mise à jour du repo
- Tue le premier processus qui match "gunicorn" dans la liste des processus courants
- Lance gunicorn comme indiqué dans la doc
- Le `&` de la fin évite le Ctrl+Z pas spécialement utile

C'est pas optimal pour la prod car :
- Ca met à jour le repo mais ça met pas à jour les dépendances, risqué à ce niveau là.
- Je ne vois pas d'autres soucis, si vous en voyez faites m'en part :)

Je ne sais pas si ça vous plait ou non, je vous laisse l'ajouter ou non dans le deploy.md sachez simplement qu'il est disponible (ajouté dans le bashrc du root de la preprod)

**Comment by firm1** [comment]
Vaut mieux mettre la commande en question dans la doc de déploiement.

'Fin tu fais une PR quoi.
 Le 31 mai 2014 02:16, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by geoffreyc** [comment]
En sachant que ce ne s'applique qu'à la preprod vue que gunicorn n'est pas
lancé de cette façon la sur la prod ;)

**Comment by Alex-D** [comment]
Ok donc on s'en fou un peu du coup :D

Je ferme donc, c'est pas super utile.
