### ISSUE TITLE
Le message d'accueil est en dessous de Clem

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#6400]
**Description du bug**

Lorsque le message d'accueil est un peu trop long, l'accroche passe sous le logo de Clém :
![image](https://user-images.githubusercontent.com/5911232/194760015-3b44ea5c-9937-48d7-ac3f-11bacce1087a.png)

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Se connecter en tant qu'admin
2. Mettre un long message d'accueil : *Gérer les unes* > *Éditer le message d'accueil*
3. Comme données, on peut mettre : 
    - Accroche : `Information`
    - Message : `Site web en maintenance pendant 20 minutes ce dimanche 9 octobre à partir de 18 heures`
    - URL : n'importe quelle URL

**Informations techniques**
Firefox 102.3.0esr sur Debian

**Solution**

J'ai une solution en ajoutant [ici](https://github.com/zestedesavoir/zds-site/blob/dev/assets/scss/pages/_home.scss#L121) : 
```scss
.home-description .featured-message {
    z-index: 1;
}
```
Mais je ne sais pas si c'est la meilleure (on pourrait faire en sorte que le message n'aille jamais en-dessous/au-dessus de l'image, et reste à sa droite, par exemple). Je veux bien vos avis.

**Comment by Situphen** [comment]
Une solution meilleure de mon point de vue est de réduire simplement la largeur de `.home-description` quand on est connecté (c'est-à-dire quand il y a la classe `.connected`). Cela permet d'éviter de superposer du texte sur une image. Il faudrait donc remplacer `$length-768` par `$length-640` dans la ligne suivante.

https://github.com/zestedesavoir/zds-site/blob/893bc33962d9df22c49b45c210e669da59817a37/assets/scss/pages/_home.scss#L322
