### ISSUE TITLE
Incompatiblité avec Python >=3.10 de elasticsearch-dsl

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#6436]
**Description du bug**

Notre environnement de dév est incompatiblite avec Python >=3.10 pour ce qui tourne autour d'ElasticSearch, en particulier le package `elasticsearch-dsl`.

Le package `elasticsearch-dsl` utilise des choses du module `collections` qui ont été déplacées depuis belle lurette dans `collections.abc`. Jusqu'à présent, le package marchait avec les versions actuelles de Python parce que les noms étaient aussi exposés dans `collections`, mais ce n'est plus le cas depuis Python 3.10. Bref, le package est resté dans le passé et pas nous (ou tout du moins, moi :D).

**Comment reproduire ?**

Essayer de faire marcher les fonctionnalités liées à ElasticSearch dans un environnement de dév avec Python >=3.10. Les deux choses que j'ai vu dysfonctionner avec des erreurs dans les logs :

* la commande mentionnée dans la [doc](https://docs.zestedesavoir.com/install/extra-install-es.html?highlight=elasticsearch#indexation-et-recherche) pour l'indexation ;
* les fonctionnalités qui utilisent la recherche (genre les complétions automatiques pour la gestion des suggestions.

On se prend une erreur sur un import dans un fichier d'`eleasticsearch-dsl`.

**Informations techniques**

- OS: Ubuntu 22.04
- Version/environnement de zds: dernière version de dév avec les versions de requirements.txt et Python 3.10.6.

**Comment by philippemilink** [comment]
On est passé à Typesense #6475, le problème n'est donc plus présent ; je ferme.
