### ISSUE TITLE
Présence de suggestions indues dans « Ces contenus pourraient vous intéresser » 

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/zds-site#6437]
[Rapporté sur le forum](https://zestedesavoir.com/forums/sujet/16664/etrangetes-dans-ces-contenus-pourraient-vous-interesser/).

**Description du bug**

Dans la liste de suggestions apparaît une suggestion qui n'est probablement pas en base, une suggestion sur le contenu lui-même, mais dans sa version privée. Ça ne devrait pas arriver, vu qu'on ne veut suggérer que des publications publiques.

**Comment reproduire ?**

Aller sur [On a retrouvé π au beau milieu du hasard !](https://zestedesavoir.com/articles/3452/on-a-retrouve-p-au-beau-milieu-du-hasard/) et actualiser la page jusqu'à voir cette publication-même dans les suggestions dans la section « Ces contenus pourraient vous intéresser ».

Tout se passe comme si la publication était suggérée sur elle-même, mais en version privée.

**Comportement attendu**

On ne devrait pas avoir cette publication et jamais de liens privés en général. Ça reste à vérifier que ce n'est pas dans la liste par erreur. Sinon, ça veut dire que c'est très tordu, et lié à tous les liens qu'on peut faire dans nos modèles avec les versions publiques, privées, etc.

**Comment by philippemilink** [comment]
À regarder également lors de la résolution de ce ticket : s'assurer que les contenus dépubliés sont automatiquement retirés des suggestions dans d'autres contenus (c'est aussi ce qui a été relevé dans [le sujet sur le forum](https://zestedesavoir.com/forums/sujet/16664/etrangetes-dans-ces-contenus-pourraient-vous-interesser/#p247454)).

Au passage, on pourra inclure ce patch pour ajouter la gestion des suggestions dans l'interface d'administration de Django : 
```diff
diff --git a/zds/tutorialv2/admin.py b/zds/tutorialv2/admin.py
index c84ec1426..b6a46720e 100644
--- a/zds/tutorialv2/admin.py
+++ b/zds/tutorialv2/admin.py
@@ -9,6 +9,7 @@ from zds.tutorialv2.models.database import (
     ContentRead,
     PublicationEvent,
     ContentContributionRole,
+    ContentSuggestion,
 )
 from zds.tutorialv2.models.events import Event
 from zds.tutorialv2.models.goals import Goal
@@ -129,3 +130,4 @@ admin.site.register(ContentContributionRole, ContentReviewTypeAdmin)
 admin.site.register(HelpWriting)
 admin.site.register(Event)
 admin.site.register(Goal, GoalAdmin)
+admin.site.register(ContentSuggestion)
diff --git a/zds/tutorialv2/models/database.py b/zds/tutorialv2/models/database.py
index 3579cd81e..6afe21cec 100644
--- a/zds/tutorialv2/models/database.py
+++ b/zds/tutorialv2/models/database.py
@@ -1487,6 +1487,10 @@ class ContentSuggestion(models.Model):
     Content suggestion
     """

+    class Meta:
+        verbose_name = "Suggestion de contenu"
+        verbose_name_plural = "Suggestions de contenu"
+
     publication = models.ForeignKey(
         PublishableContent,
         null=False,
```
(et peut-être quelques changements supplémentaires). On pourrait aussi ajouter quelques suggestions dans les fixtures.


Je viens de regarder un peu. Pour info, voici ce qu'on a en base de données : 
```
>>> from zds.tutorialv2.models.database import ContentSuggestion
>>> sugg = ContentSuggestion.objects.filter(publication=3452)
>>> sugg
<QuerySet [<ContentSuggestion: <Suggest 'Lumière sur les Médailles Fields 2018' for content On a retrouvé π au beau milieu du hasard !, #65>>, <ContentSuggestion: <Suggest 'Les équations' for content On a retrouvé π au beau milieu du hasard !, #66>>, <ContentSuggestion: <Suggest 'Génération matérielle de nombres aléatoires ' for content On a retrouvé π au beau milieu du hasard !, #67>>]>
```
Donc le contenu qu'on consulte n'est pas dans la liste des suggestions. Le contenu *Génération matérielle de nombres aléatoires* n'a pas de version publique et ne devrait donc pas être affiché. En regardant [ça](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/includes/content_suggestion.part.html#L7) et donc [ce fichier](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/includes/content_item.part.html), je vois que [si le contenu n'a pas de version publique, il utilise une URL qui n'est pas forcément publique](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/includes/content_item.part.html#L22-L30). Donc je pense que je le problème est là.

**Comment by Arnaud-D** [comment]
Il y aurait pas  une deuxième couche au bug ? Parce que c'est aussi « On a retrouvé π au beau milieu du hasard ! » qui apparaît dans ses _propres_ suggestions. Je pense que quand on a une URL non publique, le template fait quelque chose de bizarre.

**Comment by philippemilink** [comment]
> Parce que c'est aussi « On a retrouvé π au beau milieu du hasard ! » qui apparaît dans ses propres suggestions.

Seulement dans le rendu de la page, pas en base de données.

> Je pense que quand on a une URL non publique, le template fait quelque chose de bizarre.

C'est ce que je dis dans le dernier paragraphe de mon précédent message.
