### ISSUE TITLE
Erreur sur la page de teasing

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#645]
Premier bug remonté par Twitter : la page de teasing semble renvoyer une erreur "value too long for type character varying(20)".

https://twitter.com/Phigger/status/472692555868807168

**Comment by Alex-D** [comment]
Erreur dans les longueurs des champs en BDD, je crois que c'est @SpaceFox qui avait réglé le soucis sur l'ensemble du reste du site.
