### ISSUE TITLE
L'autocomplétion dans les MP ne trouve pas correctement les membres

### ISSUE THREAD

**Issue by AngeloGu** [zestedesavoir/zds-site#6460]
**Description du bug**

La liste proposée en autocomplétion lors de l'ajout d'un membre dans un MP n'est pas pertinente

**Comment reproduire ?**

La liste des étapes qui permet de reproduire le bug :

1. Ouvrir un MP existant de votre boite de messagerie
2. Essayer d'ajouter un membre (exemple dans mon cas Arius)

La liste proposée est :
- AriusEless
- jacquesmariuskangitsi22
- Marius
- Marius DAAGOUE

Note : Je n'ai jamais discuté avec l'une des ces personnes 

**Comportement attendu**
Le membre Arius (si existe) devrait apparaitre en 1er position 

**Capture d'écran**
![bug mp](https://user-images.githubusercontent.com/66358798/217008163-6636b920-3b72-40db-a2af-e188a7100d45.jpg)
J'ai vérifier le premier est AriusEless (on ne le voit pas sur la capture)

**Informations techniques**

- OS: Windows 11 

- Navigateur: Firefox 109.0.1(64 bits)
- Version/environnement de zds: production

**Comment by Arnaud-D** [comment]
Voir aussi les infos données dans [#3338](https://github.com/zestedesavoir/zds-site/issues/3338).

**Comment by philippemilink** [comment]
Vérifier également quel est le comportement si le login contient un caractère accentué (par exemple : `é`).

L'API est la même que celle utilisée pour ajouter un auteur à un contenu, donc tester ça peut aussi être pertinent.

À voir si au lieu d'utiliser la recherche intégrée dans DRF, on ne peut pas utiliser le moteur de recherche (très bientôt Typesense).
