### ISSUE TITLE
Possible erreur 500 à la résolution d'une alerte sur un contenu qui n'est plus public

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#6478]
Rapporté par Sentry. J'ai eu du mal à comprendre comment le bug a pu se produire, mais j'ai réussi à le reproduire (d'une façon peut-être un peu tirée par les cheveux...).

**Comment reproduire ?**

1. Se connecter en tant que `user1`
2. Signaler un billet
3. Se connecter en tant que `staff`
4. Ouvrir la page du billet signalé dans deux onglets différents
5. Sur un des onglets, dépublier le billet
6. Sur l'autre onglet, résoudre l'alerte (ne pas recharger la page juste avant, le billet n'est en fait plus publié, c'est là qu'est l'astuce)

Une erreur 500 va alors apparaître. Elle provient d'ici : https://github.com/zestedesavoir/zds-site/blob/c06671c4901a95c30f31067c09d5e4526fd86575/zds/tutorialv2/views/alerts.py#L88
Le contenu n'a plus de version publique, donc plus d'URL publique, et `content.get_absolute_url_online()` renvoie alors `''`.

La correction de ce bug passe sans doute par la vérification si l'alerte est déjà résolue ou si le contenu signalé a bien une version publique : si l'une de ces conditions n'est pas remplie, une erreur 404 devrait être levée.

**Comment by Situphen** [comment]
> J'ai eu du mal à comprendre comment le bug a pu se produire

Il est possible que ça ait été un billet-spam signalé par quelqu'un et deux modérateurs ont souhaité le modérer en même temps.
