### ISSUE TITLE
Commentaires pour les validateurs : obligatoire ou pas ?

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#6487]
1. Créer un article ou un tutoriel
2. Demander la validation.

Dans la modale qui s'ouvre, on a la possibilité de saisir un commentaire pour les validateurs du contenu. On peut valider la modale sans rien saisir dans le champ pour le commentaire, mais la demande de validation n'est alors pas sauvegardée avec le message : *La validation n'a pas été demandée. Vous devez fournir un commentaire aux validateurs.* Ce message émane du [traitement des données saisies dans le formulaire](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/forms.py#L745-L747). Pourtant le champ du formulaire pour le commentaire n'a pas l'attribut `required=True` et dans la définition du modèle des objets `Validation`, [il n'y a pas nécessairement besoin d'un commentaire](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/models/database.py#L1270).

Ma question : est-ce que le commentaire pour les validateurs est obligatoire quand on demande une validation ?

Je voulais initialement passer le `required` du champ pour le commentaire à `True` et éviter qu'on valide le formulaire sans message, mais maintenant je suis confus...

**Comment by Arnaud-D** [comment]
Ça ne me paraît pas nécessaire de forcer à laisser un commentaire pour les validateurs. La présence du champ encourage déjà à le faire et ça me paraît suffisant.
