### ISSUE TITLE
Forme des liens sur la liste des forums & des topics

### ISSUE THREAD

**Issue by Taluu** [zestedesavoir/zds-site#650]
Après avoir vu sur la pre-prod le travail d'@Alex-D, je trouve dommage que les liens vers les forums / les topics soient classiques (bleu + soulignement au hover). Surtout si la description est comprise dans le lien, ce qui fait un soulignement sur plusieurs lignes, ce qui fait je trouve un poil dégueulasse (cet avis n'engage que moi ceci dit).

Avoir un truc similaire à la liste des articles sur la home serait mieux je pense ? Mais après les gouts et les couleurs...

**Comment by Alex-D** [comment]
Le home n'est pas accessible, il manque un hover/focus actuellement. Ca n'est donc pas vraiment une référence ^^

**Comment by Alex-D** [comment]
J'ai amélioré le rendu.

Bleu + soulignement = classique = tout le monde s'y retrouve. Le orange rend mal sur fond clair donc pas utilisable.

J'estime cette issue close du coup.
