### ISSUE TITLE
Mode Lecteur

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#659]
Rajouter un "mode lecteur" sur les tutoriels, et les articles, un peu comme le mode lecteur de Safari sur OSX. Ce mode masquerait header/footer/sidebar, tout en centrant le contenu.

---

**Exemple:**

_Mode normal:_
![Mode normal](https://dl.dropboxusercontent.com/u/9125817/shots/normal-mode.png)

_Mode lecteur:_
![Mode normal](https://dl.dropboxusercontent.com/u/9125817/shots/reader-mode.png)

**Comment by sandhose** [comment]
btw si l'idée vous conviens, je peux m'occuper de l'implémenter rapidos

**Comment by Alex-D** [comment]
Salut !

Merci pour l'idée, elle est très sympa, il me semble que l'idée avait déjà été évoquée, il y a peut-être même une issue sur le sujet (je ne saurais dire).

Cependant cela concerne le front et la version actuelle du front n'est pas celle qui sera celle de la v1 (j'y travail, tu peux la voir sur la branche integration).

Du coup, il sera judicieux d'attendre que cette branche soit mergée pour faire de telles améliorations. Aussi, j'estime que ceci est en priorité basse.

**Comment by sandhose** [comment]
Effectivement, je n'avais pas vu la branche intégration! (pour le coup, ça en jette au niveau de l'interface! :+1: )

Du coup, si je veux faire une PR, je suppose que je dois me baser sur cette branche la ?

**Comment by Alex-D** [comment]
Tu peux effectivement te baser sur la branche intégration.

Par contre, ça va nécessiter pas mal de réflexion malgré la simplicité du truc. Où mettre le bouton ? Il ne doit être disponible que sur les écrans d'ordi (_wide.scss) etc. Pour le bout de JS, fais un fichier dédié dans assets/js (c'est ensuite uni dans un fichier et compressé).

Dans tous les cas je t'aiderais sur la PR si besoin :) N'oublies pas de lire le CONTRIBUTING.md pour ne pas te faire taper sur les doigts :)

PS : merci pour le compliment sur l'UI :)
