### ISSUE TITLE
Faire apparaître la section Administration dans la version publique des contenus

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#6596]
La section *Administration* de la colonne de gauche des contenus devrait être présente sur la page affichant la version publique d'un contenu. Pour l'instant, c'est affiché sur la version brouillon.

C'est notamment le lien *Exports du contenu* qui me manque sur la version publique, d'ailleurs ce lien n'a sans doute pas sa place sur la version brouillon (on n'exporte pas les brouillons).

**Comment by Drulac** [comment]
Bonjour :grin: !

> d'ailleurs ce lien (_Exports du contenu_) n'a sans doute pas sa place sur la version brouillon (on n'exporte pas les brouillons).

Peut-être que la plateforme n'as pas ce but, mais il m'est arrivé de noter un cours sur la plateforme, puis de l'exporter (au stade de brouillon, du coup).

Cela peut être un usage qui pourrait amener la publication de certains cours sur la plateforme ?
