### ISSUE TITLE
Bandeau "Ce contenu est vide" inutile sur la page de validation

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zds-site#6602]
1. Se connecter en tant que `user1`
2. Créer un nouvel article avec seulement une introduction et une conclusion, sans section
3. Demander la validation de l'article
4. Voir la page de validation de l'article
5. Cette page affiche un bandeau "ce contenu est vide" (cf la capture d'écran) qui ne devrait pas être affiché (c'est inutile, et on ne le retrouve pas sur la version publiée)

![validation](https://github.com/zestedesavoir/zds-site/assets/5911232/c1dedfdb-9619-465b-9604-8c1bd71bf4d7)

**Comment by jpbelval** [comment]
J'aimerais prendre ce billet !

**Comment by philippemilink** [comment]
> J'aimerais prendre ce billet !

Pas de problème, on attend ta PR ! :) N'hésite pas si tu as des questions.

**Comment by jpbelval** [comment]
J'ai simplement retiré l'affichage du bandeau dès que l'utilisateur n'est pas en mode édition et plutôt en mode aperçu. J'ai l'impression que c'est le comportement attendu lorsque l'ont visualise l'article.

Je peux toujours préciser la condition au besoin. :)
