### ISSUE TITLE
Régression sur les métadonnées Schema.org des contenus

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#6604]
[Remonté depuis le forum](https://zestedesavoir.com/forums/sujet/17405/seo-cette-modification-de-html-est-elle-appropriee/) :

Les principales différences qui remontent, ce sont les attributs suivants qui ont été supprimées dans la nouvelle version :
- `itemscope itemtype="http://schema.org/Article"` sur la balise `article`
- `itemprop="license"` sur la balise `span`
-  `itemprop="name"` sur la balise `h1`
-  `itemprop="description"`  sur la balise `h2`

C'est une régression de #6457

**Comment by Arnaud-D** [comment]
La description n'en est pas une en pratique, c'est un sous-titre. À vérifier s'il n'y a pas une meilleure propriété (subheading existe ?). Et vérifier l'adéquation du reste au passage, évidemment. ^^

**Comment by Arnaud-D** [comment]
J'ai regardé un peu, et pour les tutoriels (et les articles aussi en général), ce type serait probablement le plus adapté : https://schema.org/Course
