### ISSUE TITLE
Navigation au survol

### ISSUE THREAD

**Issue by coma94** [zestedesavoir/zds-site#661]
La navigation dans les menus au survol ne fonctionne pas, même une fois l'option activée dans le profil.

**Comment by coma94** [comment]
PS: on ne peut plus mettre de labels nous-même sur les issues ?

**Comment by firm1** [comment]
> La navigation dans les menus au survol ne fonctionne pas, même une fois l'option activée dans le profil.

Sur la version actuellement sur la branche dev (équivalent de la prod et non la préprod), je navigue en ce moment en survol.

> PS: on ne peut plus mettre de labels nous-même sur les issues ?

La gestion du dépot principal est réservé à un ensemble restreint de personnes (plus efficaces pour la gestion des issues/pr/merges)

**Comment by coma94** [comment]
> Sur la version actuellement sur la branche dev (équivalent de la prod et non la préprod), je navigue en ce moment en survol.

L'issue était pour Alex, le bug est présent sur la preprod (donc la branche intégration si j'ai bien compris).

**Comment by firm1** [comment]
> L'issue était pour Alex

Ce n'était pas précisé dans ton message. Mais merci du coup pour le rapport

**Comment by Alex-D** [comment]
Le menu au survol est une chose relativement "complexe" à gérer proprement (ie : ne pas ouvrir les box à l'arrache, etc).

Je repousse ça à pendant/après la beta. Faudrait du coup que je masque l'option peut-être ?

**Comment by coma94** [comment]
Éventuellement oui, que ça ne soit pas considéré comme un bug oublié
pendant la beta.
Mais n'en profite pas pour oublier, j'y tiens à cette navigation moi :p (ce
n'est pas la première fois que je te fais chier avec il me semble..^^)

**Comment by Alex-D** [comment]
Bah c'est ici, je ne peux pas l'oublier :)

**Comment by ghost** [comment]
Fonctionnalité non intégré au front (Juste cette ligne : https://github.com/zestedesavoir/zds-site/blob/93abd4894706145228675ca9887e8eb230fd788f/templates/base.html#L167).

**Comment by SpaceFox** [comment]
On notera le nom particulièrement ambigu du paramètre d'ailleurs : il est
vrai quand c'est hover ou quand c'est click ?

2015-02-11 19:21 GMT+01:00 A-312 notifications@github.com:

**Comment by SpaceFox** [comment]
Ce bug a été remonté y'a quelques jours sur le forum.

**Comment by GerardPaligot** [comment]
Comme le mentionne récemment @Loodoor via son issue, c'est plus un bug qu'une évolution puisque l'option existe déjà. Je change le tag.

**Comment by Alex-D** [comment]
C'est une partie des choses que j'ai tenté de relancer via cette ZEP qui n'a pas attiré grand monde : https://zestedesavoir.com/forums/sujet/4491/zep-37-reorganisation-des-menus-deroulants-du-header/

**Comment by SuperFola** [comment]
Je remonte cette issue : les booléens python/js ne sont pas compatibles (True/true et False/false)

donc il faudrait plutôt un getter pour avoir une valeur js compréhensible

https://github.com/zestedesavoir/zds-site/blob/93abd4894706145228675ca9887e8eb230fd788f/templates/base.html#L167

sur cette ligne on aura soit data-is-hover="True" soit ="False" donc

j'ai modifié à la main le html, et en mettant ="false", ca fonctionne ! une fois sur deux, certes

**Comment by pierre-24** [comment]
Ou `truc = 'true' if machin else 'false'`

**Comment by vhf** [comment]
Ou `str(x).lower()`.

**Comment by pierre-24** [comment]
ET c'est enfin réglé :)
