### ISSUE TITLE
Une page de maintenance pour le site

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#665]
Actuellement quand le site est en maintenance il y'a aucune page pour dire que le site est en cours de maintenance. Pour le coup ça fait pas très propre.

**Comment by Alex-D** [comment]
Est-ce que ça doit être fait sur un code d'erreur particulier, un fichier en particulier ?

**Comment by Alex-D** [comment]
Je relance : est-ce que ça doit être un fichier indépendant, etc ?

Il faudrait davantage d'informations pour faire quelque chose :)

**Comment by sandhose** [comment]
Je pense que ça doit être un set de fichiers statiques indépendants (un peu comme la page de teasing), et que l'activation de la maintenance se fasse via Nginx (voir même automatiquement: si gunicorn a planté/est arrêté ou autre, que ça affiche cette page...)

**Comment by Alex-D** [comment]
Je vais partir là dessus et séparer la tâche Gulp dédiée. Limite je vais éditer la tâche de teasing pour la reprendre ici.

**Comment by Alex-D** [comment]
Voilà une maquette, dites moi ce que vous en pensez :

![](http://storage.alex-d.fr/zestedesavoir/zds-maintenance.jpg)

**Comment by Eskimon** [comment]
Moi zaime beaucoup !

**Comment by amorison** [comment]
pluzun !

**Comment by Taluu** [comment]
Do like.

**Comment by Alex-D** [comment]
J'vais éclaircir un peu le bleu suite à des retours sur IRC, mais globalement je vais donc partir là dessus.

**Comment by Alex-D** [comment]
En avant la QA \o/

**Comment by Alex-D** [comment]
Il faut que quelqu'un qui ait les droits sur le preprod fasse ses tests / configuration avec cette branche pour qu'on puisse valider la PR.

**Comment by Alex-D** [comment]
Ca a été mergé, c'est donc fermé désormais.
