### ISSUE TITLE
Ajouter une page « Accessibilité »

### ISSUE THREAD

**Issue by AmauryCarrade** [zestedesavoir/zds-site#6657]
Selon le RGAA, une page de déclaration d’accessibilité est obligatoire pour _presque_ ¹ tous les sites, même si aucun audit d’accessibilité n’a été réalisé.

Cette page sert à préciser que nous sommes conscient·es des problématiques, que nous sommes à l'écoute, et que nous prévoyons de le prendre en compte (j'ai en effet prévu, un jour, de réaliser un audit du site — mais j'attends de savoir si nous décidons de reprendre son identité graphique, ainsi que d’avoir le temps).

On peut prendre pour modèle [la déclaration d’Ara](https://ara.numerique.gouv.fr/accessibilite), outil non-audité, ou [le modèle général de déclaration d’accessibilité](https://accessibilite.numerique.gouv.fr/obligations/declaration-accessibilite/).

Si nous décidons de publier une telle page, il faudrait une page accessible depuis la page d'accueil (idéalement : dans le pied de page), avec le contenu suivant (qui peut être ajusté tant que le fond et la structure restent les mêmes).

> ## Déclaration d’accessibilité
> 
> L’association Zeste de Savoir s’engage à rendre son site internet accessibles conformément à [l’article 47 de la loi № 2005-102 du 11 février 2005](https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000037388867).
> 
> À cette fin, une attention est portée à l’accessibilité des mises à jour effectuées depuis décembre 2020 sur le site, date d'une reprise graphique de ce dernier, et des efforts de corrections ont été réalisés, parfois en coopération avec des personnes concernées volontaires.
> 
> Cette déclaration d’accessibilité s’applique au site web de Zeste de Savoir (`zestedesavoir.com`).
>
> ### État de conformité
> 
> Aucun audit n’a été encore effectué.
> Le site web Zeste de Savoir est **non-conforme** avec le référentiel général d’amélioration de l’accessibilité (RGAA).
>
> Cependant, un audit de conformité est prévu, bien qu’aucune date ne soit connue aujourd’hui.
> 
> ### Retour d’information et contact
> 
> Si vous n’arrivez pas à accéder à un contenu ou à un service, vous pouvez contacter le responsable du site internet ou son équipe de développement, pour être orienté·e vers une alternative accessible ou obtenir le contenu sous une autre forme.
> 
> - Contacter le Conseil d’Administration de l’association Zeste de Savoir, à l’adresse [association+accessibilite@zestedesavoir.com](mailto:association+accessibilite@zestedesavoir.com) ;
> - Contacter l’équipe de développement de Zeste de Savoir [sur GitHub](https://github.com/zestedesavoir/zds-site/issues/new).
> 
> ### Voies de recours
> 
> Si vous constatez un défaut d’accessibilité vous empêchant d’accéder à un contenu ou une fonctionnalité du site, que vous nous le signalez et que vous ne parvenez pas à obtenir une réponse rapide de notre part, vous êtes en droit de faire parvenir vos doléances ou une demande de saisine au Défenseur des droits.
> 
> Plusieurs moyens sont à votre disposition :
> - un [formulaire de contact](https://www.defenseurdesdroits.fr/nous-contacter) ;
> - la [liste des délégués de votre région](https://www.defenseurdesdroits.fr/fr/saisir/delegues) avec leurs informations de contact directs ;
> - un numéro de téléphone : le [+33 (0) 9 69 39 00 00](tel:0033969390000) du lundi au vendredi de 8h30 à 19h30 (coût d’un appel local) ;
> - une adresse postale [dans l’annuaire de l’administration](https://lannuaire.service-public.fr/autorites-independantes/1867f065-c823-4362-8d0f-8ca6b011a10f).

Le lien dans le pied de page pointant vers cette page devrait avoir le libellé « Accessibilité : non conforme ».

_¹ Notez qu'en tant qu'association avec un faible budget, nous n'avons pas, à date, d'obligation de publication d'une telle page — ni, plus généralement, de conformité — ; je trouve cependant que cela enverrait un message cohérent avec nos valeurs que de le prendre en compte (et de le montrer)._

**Comment by jpbelval** [comment]
Je peux m'en occuper!

**Comment by Arnaud-D** [comment]
D'acc, mais faut que tu te méfies de notre pied de page qui est plein à craquer. Je me demande s'il ne faudrait pas auparavant (ou en même temps) changer le format de notre pied de page pour adopter un format à colonnes comme on en trouve ailleurs.

Ce type de chose :
![image](https://github.com/user-attachments/assets/f6ddefb8-7cce-4b32-8bb6-0fc970efea66)

**Comment by jpbelval** [comment]
Je serais porté à vouloir le faire en deux temps. Présentement je crois que le pied de page peut accueillir un dernier lien avant d'être converti en colonnes:
![image](https://github.com/user-attachments/assets/d6f34269-d54e-470a-9263-f410b74df885)
Il semble encore y avoir un espacement raisonnable.

Pour la suite, il faudra réfléchir à une méthode alternative: où déplacer les réseaux sociaux et la version pour s'harmoniser avec des liens sur plusieurs colonnes, etc.
