### ISSUE TITLE
Mauvaise date de MP

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#666]
Dans le menu "Messagerie" (menu principal), la date indiquée est toujours celle de création du MP. Ce devrait être la date du dernier message.

**Comment by Alex-D** [comment]
Il m'avait été reporté bon nombre de soucis à ce niveau (la dernière réponse n'est visiblement pas toujours la bonne).

**Comment by Alex-D** [comment]
Après un test, j'ai la bonne date qui s'affiche, à savoir celle de la dernière réponse.

**Comment by Eskimon** [comment]
Chez moi c'est bien la date de dernière réponse qui s'affiche aussi

**Comment by Alex-D** [comment]
En fait, c'est la dernière réponse lue qui s'affiche. Et pas la dernière réponse vraiment.

**Comment by Coy0te** [comment]
Quand on est notifié d'une nouvelle réponse dans un MP,  c'est l'auteur et la date du créateur du MP qui s'affichent dans les notifs MP.

Par contre, une fois qu'on va lire le MP, la notif se "corrige" et c'est bien l'auteur et la date de la dernière intervention qui s'affichent.

**Comment by Alex-D** [comment]
En fait, pour moi les infos affichées de sont pas les bonnes.

Il faudrait la date de la dernière réponse et la liste des participants non ?

**Comment by firm1** [comment]
Pour précision, les bonnes pratiques du back-end voudrait que seul les
notifications (non lues) soient affichées dans cette zone de notif. Et pas
les déjà lu.

Le bug vient surrement de là.

**Comment by Alex-D** [comment]
Le principe de ces box c'est d'avoir un accès rapide aux activités récentes. Si tu vire les MPs lus, les notifs lues, etc. Y a plus rien dedans, et tu perds l'intérêt des notifications au sens "choses récentes".

Et le bug est fixé en local, je fais quelques tests et j'envoie.

**Comment by firm1** [comment]
Je me rends compte que la modification avait été appliquée pour les notifs
forum, mais pas pour les notifs MP.

Bref, on verra ce qu'on en fait.

Mais +1 pour les participants manquant.

**Comment by SpaceFox** [comment]
Je crois qu'on est pas d'accord sur la notion de "notification" alors.

Je suis d'accord avec @firm1 : les notifications ne devraient contenir _que_... ben des notifications en fait. C'est une question de vocabulaires : quand tu reçois une _notification_ c'est qu'on porte à ta connaissance quelque chose de nouveau, que tu ne connaissais pas.

Ca n'a donc linguistiquement aucun sens d'avoir des MP lus ou des notifs lues là-dedans.

**Comment by Alex-D** [comment]
Bon je les retire alors

**Comment by firm1** [comment]
Fixé cette fois pour de bon.

**Comment by Alex-D** [comment]
\o/
