### ISSUE TITLE
Afficher le statut de banissement sur la liste des utilisateurices par IP

### ISSUE THREAD

**Issue by AmauryCarrade** [zestedesavoir/zds-site#6664]
[Une proposition d’elyppire.](https://zestedesavoir.com/forums/sujet/7468/post-mortem-de-la-moderation/?page=48#p256775)

> Une fonctionnalité utile serait, dans la liste des membres par IP, d’afficher si le membre est banni.
> Cela permettrait de repérer en un coup d’œil les multis pas encore bannis (dans le cas bien sûr de spam évident).

**Comment by philippemilink** [comment]
C'est déjà fait dans #6629, ça va arriver dans la prochaine release.

**Comment by AmauryCarrade** [comment]
Ah, mon erreur, je n'ai vérifié que dans les tickets/PRs ouvertes, je me rends compte >_>

_my bad_
