### ISSUE TITLE
Page des alertes incomplète

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#667]
http://zestedesavoir.com/pages/alertes/

Cette page ne liste que les alertes du forum, il manque donc les alertes articles et tuto.

Sachant que ces informations sont dans le header, j'aimerais savoir si c'est du front ou du back, pour savoir si c'est à moi ou non de corriger ça.

**Comment by firm1** [comment]
Cette page liste surtout toutes les alertes DE TYPE MODERATION des forums,
articles, et tutos. Pour ce qui est de la validation des tutos/articles il
faut aller voir dans le menu adéquat.

**Comment by Alex-D** [comment]
Oui on est bien d'accords. Mais tandis que dans la dropdown en haut on a des choses en plus, sur cette page elle n'y sont pas. Donc il en manque ;)

**Comment by ArnaudCalmettes** [comment]
Ni un bug, ni une question : c'est une évolution post-V1. On pourra très bien fonctionner comme ça en attendant.

**Comment by Alex-D** [comment]
A l'heure actuelle, c'est bloquant : toute alerte sur les tutos/articles ne sont visibles que sur leurs messages respectifs.

En gros dans le bloc d'alertes du header, il n'y a que les alertes du forum pour l'instant (j'ai mon idée là dessus : faire des onglets pour chaque catégorie à l'intérieur même de la box) mais il faut que je prenne un peu de temps.

Après, c'est sûr que c'est pas super important sachant qu'on a le forum qui tourne, c'est le principal.

**Comment by ArnaudCalmettes** [comment]
C'est pas ce que j'appelle "bloquant". 

Cf la classif sur le forum.

Ça ne rend pas une feature publique inutilisable et ce n'est pas une faille de sécurité. (donc pas bloquant bêta)
Ça n'est pas visible. (donc pas bloquant V1)
Conclusion : c'est du post-V1.

**Comment by Alex-D** [comment]
Ok d'ac, va pour ça :)

**Comment by Eskimon** [comment]
Je viens juste pour discuter et parce que les issues se corrige bien tfacon...

Alex a ecrit:

> En gros dans le bloc d'alertes du header, il n'y a que les alertes du forum pour l'instant (j'ai mon idée là dessus : faire des onglets pour chaque catégorie à l'intérieur même de la box) mais il faut que je prenne un peu de temps.

Pourquoi pas un code couleur ? les lignes en rouge sont le fofo, en jaune les tutos et en orange les articles par exemple. Ca fait moins de clic...

**Comment by Eskimon** [comment]
Ca a été corrigé depuis le temps ? Sur ma version local fraichement pullé de master, j'ai bien une page toutes les alertes completes... donc ca semble ok !

Une sidebar avec des filtres et se serait nickel !!

**Comment by Alex-D** [comment]
> Ca a été corrigé depuis le temps ?

Aucune idée, mais en tous cas je n'ai pas intégrer les différentes catégories d'alertes dans le menu en haut.

**Comment by gustavi** [comment]
C'est plus d'actualité ici.
