### ISSUE TITLE
Gestion de la suppression de compte

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#668]
Il faut voir comment gérer la suppression de compte _globalement_
- quitter les MP
- passer les postes en "anonyme"
- que fait-on des tutoriels ? Retrait si d'autres auteurs, passage sur la mascotte si c'est le dernier ? Suppression du tutoriel ?

Pas mal de question à débattre qui font suite à l'issue #537

**Comment by firm1** [comment]
Je ferme celle-ci étant donné que c'est la même que la #818 et qu'il y'a déjà un début de discussion là bas.
