### ISSUE TITLE
[Teasing] Vérifier que l'adresse est valide, champ non vide, etc.

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#669]
Un ami a cliqué sur "OK" en laissant le champ vide, il est considéré comme inscrit. J'imagine du coup qu'il y a une case avec un email vide, or l'adresse devrait être validée (et donc non vide).

**Comment by Eskimon** [comment]
J'ai commencé à pusher des modifs...
En gros maintenant je renvoie les erreurs vers la page du formulaire
Par contre je ne comprend pas pourquoi, l'erreur est là (dans le source) mais ne s'affiche pas...
Bref, presque bon je pense...

**Comment by firm1** [comment]
Ton problème vient certainement du fait que le formulaire n'utilise pas les
champs de crispy_foundation et du coup tu renvois bien une erreur danses
source HTML mais elle ne s'affiche pas comme avec les autres formulaires
(ceux qui utilisent crispy_foundation).

Ne t'embête pas car la branche intégration sera mergée en soirée. Du coup
si l'erreur est dans le HTML ça devrait marcher.

Je te dis tout ça sans avoir vérifie (smartphone toussa) mais globalement
ça devrait être ça le souci

**Comment by Eskimon** [comment]
^^ J'ai encore tant de choses a apprendre :D

**Comment by Eskimon** [comment]
Du coup on peut fermer vu que la PR est mergé ?

**Comment by firm1** [comment]
ouaip

**Comment by Alex-D** [comment]
crispy_foundation -> out ! J'ai tout viré de foundation dans ma branche.
