### ISSUE TITLE
Les QCM dans les tutos

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#678]
Je ne me souviens plus de ce qu'on avait dit à l'époque, et je n'ai pas retrouvé d'issue à ce sujet : que deviennent les QCM des tutos importés depuis le SdZ ?

Est-ce qu'ils sont perdus, ou est-ce qu'ils sont stockés quelque part dans le repo git, mais simplement ignorés côté appli pour le moment ?

**Comment by cgabard** [comment]
Il ne me semble pas qu'il y ai quoique ce soit dans le back pour les gérer. Donc je pense qu'ils sont perdues.

**Comment by SpaceFox** [comment]
Je pense qu'elles sont perdues, et que ce n'est pas grave parce que ça ne
servait à rien.

Mais c'est vrai que c'est un peu dommage pour les auteurs.

**Comment by Alex-D** [comment]
Issue mort née :D

Je ferme du coup.

**Comment by cgabard** [comment]
Je ré-ouvre car le fait qu'il y ai une réponse a sa quesiton de base ne veut pas dire qu'on ne peut pas les remettre si besoin. Ça mérite en tout cas d'etre discuté.

En fait je pense qu'il faudrat ressortir ça quand on voudra aller plus loin avec le module de rédaction. Actuellement un tuto est une suite de fichiers markdown, chacun représentant un chapitre. A terme je pense qu'il serait interessant de permettre d'ajouter d'autres contenu que des paragraphes de textes. On peut passer à ces QCM mais aussi a d'autres exos interactifs. En fait pour moi la balise vidéo peut avoir le même sort, elle devrait servir, forum mis a part, pour rajouter des cours vidéos.

Donc on peut envisager deux approches possibles : 
- Les tutos ne sont pas que des suites de fichiers markdown mais peuvent etre aussi des vidéo, des exos, etc.
- On garde notre structure de fichiers basés sur le markdown pour structurer un cours mais on autorise une syntaxe pour chaque composant qui nous interesse : Les videos sont déjà dispo, on peut en rajouter une pour les QCM ou d'autres sortes d'exos.

**Comment by Alex-D** [comment]
On en avait déjà discuté je ne sais plus trop où. Et du coup tes questions diffèrent du topic initial et vaudraient une issue dédiée (s'il n'y en a pas déjà une).

Aussi, les exos interactive et tout le tralala, ça demande une blinde de dev, et globalement c'est compliquer d'obtenir un truc userfriendly pour l'auteur sans qu'il touche à du code.

On doit être en mesure de produire un exercice aussi aisément que du contenu texture si on veut être cohérents en fait. Autoriser n'importe qui à balancer du HTML/CSS/JS en brut par exemple, c'est pas une bonne idée : ça nécessite des compétences JS en validation pour vérifier que le JS n'est pas là pour foutre le brin.

Pour les vidéos, a priori ça avait pas l'air de motiver les troupes. Au pire, y a la possibilité de les intégrer via un lien YouTube/Dailymotion etc. Du coup ça reste du markdown derrière à mon sens.

Mais pour moi, tout ça devrait faire l'objet d'une issue et un d'un débat spécifique, là parlait des QCM.

**Comment by Alex-D** [comment]
Je rajouterais que les QCM ne servaient absolument à rien, je suis d'accord avec @SpaceFox là dessus.

**Comment by ArnaudCalmettes** [comment]
> Aussi, les exos interactive et tout le tralala, ça demande une blinde de dev, et globalement c'est compliquer d'obtenir un truc userfriendly pour l'auteur sans qu'il touche à du code.

Certes, mais ça ne signifie pas qu'on ne cherchera pas à faire quand même des évolutions dans ce sens à l'avenir. Une fois la V1 stable avec un set initial de features va se poser la question des évolutions, et pourquoi pas des innovations. Je passe l'issue en 2.0+.

**Comment by gustavi** [comment]
Je ferme ici car tout cela est repris dans la ZEP-10 : http://zestedesavoir.com/forums/sujet/822/zep-10-module-dexercices/
