### ISSUE TITLE
Support des @mentions

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#688]
Comme sur Twitter, GitHub, G+ et autre, supporter les `@mentions`, au moins sur le forum (ça peut également s'appliquer aux MP, aux articles et aux tutos)

On peut voir ça de deux façons: 
- Soit la mention est détecté au post du message, et la modifie en lien cliquable
- Soit la mention est traitée lors du parse markdown, et donc cela se passerais sous forme d'une extension MD. ( <- la solution que je préfère )

Ça se ferait à 3 endroits:
- le répo [Python-ZMarkdown](https://github.com/zestedesavoir/Python-ZMarkdown), avec une extension MD pour ces mentions
- lors du post des messages, pour détecter, corriger (au niveau de la casse), et notifier éventuellement l'utilisateur mentionné
- au niveau du client, pour avoir une mini-recherche lorsqu'on commence à taper `@...`, un peu comme [cette extension jQuery](https://github.com/jakiestfu/Mention.js/)

Pour la partie extension MD, rien de compliqué je pense, puisqu'il s'agit de transformer les `@[pseudo]` en `<a href="/membres/voir/[pseudo]">@[pseudo]</a>` (à moins que vous vouliez que ça check si l'utilisateur existe dans la BDD à chaque affichage, ce qui est à mon sens trop lourd à mettre en place, et un peu inutile...). Je pense pouvoir m'en occuper

Pour la partie client, rien de très compliqué non plus, puisqu'en plus, la recherche de membre avec réponse JSON a été faite y'a pas longtemps (cf. #677 ). De plus, le même code pourrait servir pour les destinataires de MP ( #370 ). Je pense également pouvoir m'en occuper

Pour le back, il faudrait parser les messages envoyer, pour détecter les mentions, rechercher dans la BDD si l'utilisateur existe (si c'est pas le cas, désactiver la mention d'une manière ou d'une autre), et lui dire qu'il a été mentionné, via une notification. Par contre, vu que je n'ai jamais vraiment touché au Python (j'ai quelques bases quand même), je préfère pas trop trop toucher au back, et laisser les pros s'en occuper :blush: 

PS: Je sais que normalement vous discutez de ce genre de features sur le forum de la bêta privée... Cependant, je n'y ai pas accès (du calme, c'est pas une demande d'accès que je fait la! :relaxed: ), et donc si vous trouvez que les issues GitHub sont pas faites pour proposez de nouvelle features (j'en ai encore 2/3 en têtes que je risque de proposer prochainement, avec bien sûr des PR derrière), dites le moi, j'attendrais la bêta publique pour pleinement contribuer :smile:

**Comment by cgabard** [comment]
J'ai rien contre.

On en avait déjà vaguement parlé et il me semble que les notifs ne nous semblaient pas specialement pertinent, surtout a cause des abus possibles. Mais bon, à voir.

Par contre niveau markdown : 
- En effet ce ne sera pas trop compliqué a faire
- On peut se débrouiller pour directement faire sortir la liste des pseudos cités, comme ça le back n'a rien à parser de plus

Pour le markdown, si cette issue est validé je peux m'en occuper ou te guider si tu veux le faire, comme tu le sens.

**Comment by Alex-D** [comment]
Je viens juste rajouter un petit avertissement : 

certains pseudos commencent par @ (@che, @dir1, etc) du coup, soit le truc gère bien ça (je ne vois pas comment, mais c'est probablement possible) soit faut interdire les "@" dans les pseudos.

**Comment by cgabard** [comment]
Si je comprend bien la PR, il propose la syntaxe suivante `@[pseudo]` donc certains pseudo peuvent effectivement foutre la merde mais pas ceux que tu cite

**Comment by sandhose** [comment]
C'est vrai que je n'y avais pas pensé... On peux toujours changer de délimiteur (mais je pense que personne ne soit vraiment pour un "+[...]" à la G+ :unamused: ), ou alors pour ce genre de pseudos (qui sont quand même très minoritaires), qu'on garde la même syntaxe, mais que du coup on ai des trucs genre `@@che`, ce qui est pas super esthétique... Après, pour que ça choque pas trop, on pourra toujours atténuer le premier "@" (comprendre: le mettre en gris-clair) pour bien distinguer le pseudo

**Comment by sandhose** [comment]
@cgabard Pour toi, quels sont les pseudos qui peuvent potentiellement foutre la merde ? Parce que la, en dehors de ceux que citais @Alex-D , je vois pas :confused:

**Comment by cgabard** [comment]
En fait je pensais que les crochets faisaient parti de la syntaxe que tu
proposait

**Comment by Alex-D** [comment]
> Après, pour que ça choque pas trop, on pourra toujours atténuer le premier "@" (comprendre: le mettre en gris-clair) pour bien distinguer le pseudo

Un bon compromis selon moi, si vous arrivez à matcher les users existants et tout (un petit #CCC pour être cohérent avec le reste :))

En gros le soucis que je relève c'est :
- un membre @dri1
- un membre dri1

Faut bien mettre le bon lien sur @@dri1 ou sur @dri1 : ça donne pas la même chose, vois-tu @cgabard ?

**Comment by Alex-D** [comment]
NB : je viens de voir le plugin que tu cites. Pour l'autocomplétition (s'il doit y en avoir une) y en aura déjà une pour les MP et tout ça (sans le @) ça sera peut-être possible de la réutiliser du coup. Mais pour l'instant le back a l'air cassé à ce niveau, donc j'attends que ça re-fonctionne :)

**Comment by cgabard** [comment]
J'ai bien compris, je pensais juste qu'il proposait une syntaxe avec  @ et
crochet.

On peut passer des paramètres au markdown, le cite peut très bien fournir
une fonction de callback qui valide le pseudo. Ainsi le markdown pourra
savoir que si tu écrit @dri1 et que l'utilisateur dri1 n'existe pas, il ne
doit pas faire de liens
Le 4 juin 2014 09:56, "Alexandre Demode" notifications@github.com a écrit
:

**Comment by sandhose** [comment]
Je pensais justement faire cette vérification au post du message, pour éviter de surcharger les requêtes vers la BDD pour rien... Du coup, si une des mention n'es pas valide, il suffirait je pense d'échaper l'`@` (et donc le remplacer par `&#64;`), histoire qu'elle soit plus reconnue par le parser

> Pour l'autocomplétition y en aura déjà une pour les MP

C'est ce que j'ai dit dans mon premier message ;)

**Comment by Alex-D** [comment]
Désolé, j'ai lu un peu vite :(

Sinon pour ton PS : les PR sont les bienvenues dès à présent, pas besoin d'attendre la beta :)

**Comment by sandhose** [comment]
Okay, je m'y mettrais dans l'après-midi je pense :smile:

**Comment by cgabard** [comment]
> Je pensais justement faire cette vérification au post du message, pour éviter de surcharger les requêtes vers la BDD pour rien... Du coup, si une des mention n'es pas valide, il suffirait je pense d'échaper l'@ (et donc le remplacer par &#64;), histoire qu'elle soit plus reconnue par le parser

Le markdown est coté serveur, il passe justement à ce moment là. Le plus simple et propre est je pense justement de le laisser régler ça. Car sinon tu vas : 
- Soit pré-parser le markdown pour les détecter et virer ceux qui ne te vont pas. Ce qui va poser des problèmes car il y aura plein de cas à gérer (ex : ta notation dans l'une des syntaxe de code, inline ou non doit etre ignoré.
- Soit faire le remplacement systématique dans le markdown puis re-parser le html généré pour re-virer ceux qui ne correspondent pas.

Bref, le markdown fait le parsing, c'est a lui de s'en occuper. Enfin a mon avis. D'autant que la liste des users ne change pas toutes les secondes, la fonction de callback peut tres bien etre faite avec un cache.

**Comment by sandhose** [comment]
Dans ce cas, je te laisserais t'occuper de toute cette partie vérification :smile: (parce que moi et le Python... Faudrait vraiment que je m'y mette un jour!)

**Comment by cgabard** [comment]
@sandhose : Je ne voudrais te faire perdre du temps, est ce que tu as autre chose sur lequel tu peux travailler ? En fait je ne voudrais pas qu'on se precipite pour que ce soit refusé.

En fait on en avait parlé tout au début du projet. Et ça n'a manifestement pas été retenu comme tu le vois. Mais je ne sais plus pourquoi. C'est peut etre simplement car a l'epoque il y avait plus urgent. Mais peut etre il y a t'il une raison plus profonde.

J'aimerai donc qu'on attende juste la journée pour décider, le temps que d'autres personnes interviennent. Mais pas beaucoup plus car on va approché de l'ouverture et à ce moment là les changements du markdown devront être plus rare car nécessiteront une migration de tout ce qui est déjà rédigé pour assurer la cohérence.

**Comment by Coy0te** [comment]
Je trouve que c'est une bonne idée de mettre en avant les pseudos de cette manière.

Après, pour le coup des notifs à générer, si jamais ça se fait je pense qu'il faudrait qu'elles s'intègrent différemment du reste des notifs : perso, ça me gênerait de voir des entrées "machin a parlé de vous ici" dans la liste de mes notifs de nouvelles réponses et sujets suivis, ça risque de générer du "bruit".

**Comment by cgabard** [comment]
Si notif il y a, il faut qu'elles puissent etre desactivable dans les
options en tout cas.

Christophe.

2014-06-04 13:17 GMT+02:00 Coyote notifications@github.com:

**Comment by sandhose** [comment]
@cgabard Je vois ce que tu veux dire... Mais je peux quand même me concentrer sur l'auto-complétion (qui concerne donc autant les mentions que les destinataires de MP, #370 ), qui agit uniquement côté front, et donc sans réelle influence sur le reste

@Coyote: Pour moi, je pense qu'il est important de pouvoir dire `poke @machin`, histoire que _machin_ voit le sujet... Après, je suis totalement d'accord avec @cgabard , il faut pouvoir désactiver ces notifs (soit de manière globale, soit avec un système de mute, genre "ne plus recevoir de notifs de ce sujet", ou "ne plus recevoir de notifs de cette personne"... Mais je suis conscient que cette 2è solution est beaucoup plus lourd à mettre en place...)

**Comment by Eskimon** [comment]
Faudra aussi anticiper le cas du "une personne cite se desinscrit" car dans ce cas tous les liens iront sur une 404...

**Comment by cgabard** [comment]
Ça c'est un poil plus compliqué à gérer si on ne garde pas trace de toutes les mentions le concernant.

On peut aussi faire une 404 dédié aux profile : "Cette personne n'existe pas où s'est désinscrit".

**Comment by sandhose** [comment]
> On peut aussi faire une 404 dédié aux profile : "Cette personne n'existe pas où s'est désinscrit".

Je suis d'accord, d'autant que des sites comme GitHub ou Twitter font la même chose il me semble pour les mentions qui ne correspondent à aucun utilisateur

**Comment by Alex-D** [comment]
> perso, ça me gênerait de voir des entrées "machin a parlé de vous ici" dans la liste de mes notifs de nouvelles réponses et sujets suivis, ça risque de générer du "bruit".

Pour moi c'est le rôle des notifications. Sachant que les sujets suivis tu les as sur le forum également, les notifs sont là pour dire "hé regarde y a un truc nouveau là bas".

Pour l'histoire de la désinscription, faudra virer le pseudo en fait, mais ça fait partie de l'issue #668

**Comment by viki53** [comment]
Hello, je débarque un peu comme un cheveu sur la soupe, mais un des problèmes sur Twitter par exemple est quand on poste du code qui utilise des arobases ou des adresses email.
Par exemple `@import` peut foutre la merde si un membre s'appelle import…

Mais j'aime l'idée de mentionner (et d'être notifié à l'occasion, histoire de suivre ce qui se dit — attention aux droits d'accès d'ailleurs).

**Comment by cgabard** [comment]
Techniquement le code on a pas ce prob car tu es censé le mettre dans les balises dédiés (inline ou non). Donc si il y a des problèmes parce que tu n'utilise pas le balisage du code, moi je n'y peut pas grand chose et pour le coup ça ne me choc pas.

**Comment by Alex-D** [comment]
+1 @cgabard 

Et ça sous entend qu'un membre "import" existe, c'est pas impossible, mais ça fait beaucoup de "si".

**Comment by Alex-D** [comment]
PS : You're welcome!

**Comment by SpaceFox** [comment]
> Et ça sous entend qu'un membre "import" existe, c'est pas impossible,
> mais ça fait beaucoup de "si".

Je peux te garantir qu'à partir du moment où en faisant @import tu
"pingues" le membre "import", tu as un petit malin qui va créer un compte
nommé "import" juste pour tester.

2014-06-04 16:47 GMT+02:00 Alexandre Demode notifications@github.com:

**Comment by cgabard** [comment]
Pour les adresses mails, elles sont parsés par ailleurs. Suffit de le faire apres. De toute façon je vais imposer je pense que le @ n'ai pas de caractère "classique" à sa gauche : tu n'as pas à faire de citation en plein milieu de mots.

Bref pour le moment je ne vois pas trop de soucis.

Apres je pense que dans un premier temps on acceptera tous les pseudos, ce sera au back de fournir une fonction pour pré-filtrer.

**Comment by Alex-D** [comment]
Genre comme tu viens de le faire ? :D

Dans tous les cas, comme dit @cgabard ce genre de truc sera dans des balises code.

**Comment by firm1** [comment]
En fait cette feature serait un genre de feature troll pour pinger plein de
membres et pourrir les notifs en un seul post ?

**Comment by Coy0te** [comment]
@firm1, c'est à ça que je pensais quand je disais "j'aimerais que si notif il y a, ça soit intégré ailleurs que dans les _vraies_ notifs".

**Comment by SpaceFox** [comment]
Il faut clairement des protections :
1. Si j'ai plusieurs mentions du même utilisateur dans un post, il n'est
notifié qu'une seule fois.
2. Il faut une limite de mentions dans un seul post (imposée, celle-ci).

**Comment by Alex-D** [comment]
Limite de mentions, je dirais 10.

> pinger plein de membres et pourrir les notifs en un seul post ?

Ces gens là sont à bannir/LS...

**Comment by cgabard** [comment]
on peut aussi envisager de "muter" quelqu'un. dans ce cas là je ne reçois plus de notifs de sa part

**Comment by Lamecarlate** [comment]
Je m'incruste un peu, le sujet ayant été évoqué de nouveau sur le forum. Et je me sens un peu concernée par un problème qui pourrait arriver : les gens qui ont un pseudo contenant un ou des espaces. Comment détecter ce genre de cas ?

Exemple. Sur ZdS, je suis Chaopale Lamecarlate : comment me mentionner ? "@Chaopale" ? Il pourrait y en avoir plusieurs (prénom seul ou bien prénom + un autre nom de famille). "@Chaopale Lamecarlate" ? Comment détecter que "Lamecarlate" fait partie du pseudo ?

C'est super d'avoir permis les pseudos à espace, mais c'est vrai que ça limite sur certains points...

Avez-vous une idée ?

**Comment by Eskimon** [comment]
Suffit que l'autocompletion fasse correctement son travail je pense... (et j'espere)

**Comment by viki53** [comment]
@Lamecarlate Tu n'as plus qu'à changer pour redevenir Akaiken :D 

@Eskimon : le problème c'est qu'il y a aussi un travail prévu côté back pour notifier, donc à moins d'avoir un genre de markdown spécifique (qui du coup permettrait de citer quelqu'un sans qu'il soit mentionné, mais alourdirait aussi le tout), ça risque d'être difficile…

**Comment by cgabard** [comment]
> Suffit que l'autocompletion fasse correctement son travail je pense... (et j'espere)

Non c'est pas si simple car là on parle du parsage du markdown.

Pour moi il faut que la syntaxe comprenne un engloblant (éventuellement optionnel).

Par exemple qu'on puisse faire : 

```
Hey salut @[Chaopale Lamecarlate]
```

Je ne vois pas trop d'autres solutions si vous voulez que le markdown le parse.

**Comment by Coy0te** [comment]
Faudra penser à empêcher le caractère "}" dans les pseudos... :-°

**Comment by Eskimon** [comment]
Pourquoi ? Pour si on prend ca comme delimiteur ? C'est pas tellement genant, suffit de bien prendre la derniere occurence.

Perso j'aime bien l'idee de "delimiteur facultatif" ca me parait elegant et fonctionnel

**Comment by firm1** [comment]
Moi non plus je ne vois pas pourquoi interdire des cacractère dans les pseudos si c'est techniquement faisable. Le délimiteur facultatif (s'il y'a des espaces dans le pseudo et donc a gérer par l'autocomplete) est une idée qui validerait le souci.

**Comment by Coy0te** [comment]
Arf, j'ai peut-être mal compris. Si un mec s'appelle "Bla} bla", il sera
pas pingable avec la notation @{...}, si ?

**Comment by viki53** [comment]
Ouais, il y aura bien un caractère à interdire. Voire 2, histoire d'être cohérent (si on interdit le fermant, autant interdire l'ouvrant).

J'hésite encore entre @[pseudo] qui rappelle les liens et @<pseudo> qui rappelle la notation des emails…

**Comment by cgabard** [comment]
On peut permettre d'échapper le caractère fermant, non ?

Genre ton mec on le pinguerai via `@{Bla\} bla}` et un mec appelé "Bla\}" on ferait  `@{Bla\\}`

**Comment by Eskimon** [comment]
> J'hésite encore entre @[pseudo] qui rappelle les liens et @ qui rappelle la notation des emails…

Les deux, avec les crochets facultatifs

**Comment by cgabard** [comment]
en fait il propose `@<pseudo>` mais tu rentre en conflit manifestement avec une syntaxe du markdown git

**Comment by viki53** [comment]
Effectivement, les `<>` coincent…

**Comment by Alex-D** [comment]
Personnellement, je vote pour `@Alex-D` et `@[Un nom composé]`. Ca rappelle les liens MD, et c'est très cohérent. Pour les caractères spéciaux, je pense qu'on peut se permettre de retirer les crochets, à défaut les échapper comme proposé par @cgabard

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis plus d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.

**Comment by GerardPaligot** [comment]
Cette idée est incluse dans la ZEP-24, elle n'est pas perdue mais inutile ici;

**Comment by pierre-24** [comment]
Par contre, sur celle-ci, on a déjà l'API des membres, ce qui est plutôt cool :)
