### ISSUE TITLE
Les listes de topics sont trop verbeuses

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#689]
Je pense qu'on peut faire beaucoup plus simple et tout aussi clair dans les listes de topic, qui sont aujourd'hui super verbeuses.
- A-t-on besoin de répéter "Créé par" à chaque ligne ?
- A-t-on besoin de répéter "Tags : " à chaque ligne ?
- A-t-on besoin de répéter " réponses" (dans "14 réponses") à chaque ligne ?
- A-t-on besoin de répéter "Dernière réponse " à chaque ligne ?

J'ai l'impression que le problème ici vient de la non-utilisation de headers à ce tableau, et que du coup on répète systématiquement des informations qui devraient être dans les headers.

**Comment by cgabard** [comment]
Je trouve dommage aussi que sur la liste des forums on ai juste "Dernier message + titre". Perso j'aime bien quand il y a l'auteur et surtout la date. C'est ultra pratique pour savoir si il y a des trucs de nouveaux. Beaucoup plus en tout cas que les 2 chiffres "nombre de sujets/nombres de messages" qui sont au mieux inutile, au pire préjudiciable au début où il y aura peu de messages. D'autant que sans header de tableau, on ne sais pas trop à quoi ils correspondent

**Comment by Alex-D** [comment]
> Je trouve dommage aussi que sur la liste des forums on ai juste "Dernier message + titre". Perso j'aime bien quand il y a l'auteur et surtout la date

C'est dans la todo :)

> Beaucoup plus en tout cas que les 2 chiffres "nombre de sujets/nombres de messages" 

Je peux les virer si ça va à tout le monde, je trouve pas ça méga top de toute façon

---

Parlons accessibilité. Imagine toi, 2 minutes, non voyant. Tu utilises alors un lecteur d'écran. Il ne sait que lire ce qu'il y a dans la page, avec l'intonation et tout qui va bien.

Si on suit tes remarques on a : 

"Bug menu machin. Ca bug, c'est chiant. SpaceFox il y a 6 heures. Bug, Front. 14. Il y a 4 heures par toto"

VS ma version : 

"Bug menu machin. Ca bug, c'est chiant. Créé par SpaceFox il y a 6 heures. Tags: Bug, Front. 14 réponses. Dernier message il y a 4 heures par toto".

> A-t-on besoin de répéter "Créé par" à chaque ligne ?

Je répond donc : oui.

Aussi, ce n'est pas un tableau car les données ne sont aucunement tabulaires (en tous cas, pour moi, y a pas de raison de faire un tableau ici, chaque ligne est indépendante). Par contre ma structure HTML n'est pas optimale actuellement, il manque un lien fort ligne par ligne, il faudrait que je fasse une liste (ul, voire ol).

**Comment by SpaceFox** [comment]
C'est une question de vision des choses : pour moi tu as clairement un
tableau, avec un topic par ligne, et des colonnes :
- Titre
- Auteur
- (Nombre de réponses)
- Auteur de la dernière réponse
- Date de la dernière réponse

En partant de là, on devrait pouvoir faire un tableau et utiliser les
headers qui vont bien non ?

Je n'ai rien contre l'accessibilité, bien au contraire. Par contre, est-ce
que ça doit se faire au détriment de 90% des utilisateurs ? Si on doit
conserver le "Dernier message", ne peut-on pas le masquer, pour éviter de
perdre systématiquement une ligne à cause de lui ?

**Comment by Alex-D** [comment]
On ne perd pas une ligne à cause de "Dernier message".

On a : 
- titre
- sous-titre
- auteur (tags, etc)

Donc on est bloqué par la présence du sous-titre (que je trouve inutile).

Je peux éventuellement masquer "Dernier message" mais comment sait-on qu'on parle du dernier message ? Avec un header ? Or ce ne sont pas des données tabulaires, donc y a pas de header.

Et non, y a un lien en ce sens où ils ont la même structure, mais les données ne sont pas liées. Un tableau ça contient des données que globalement tu peux comparer/etc. Là c'est pas le cas, c'est une simple liste.

Je ne vois pas trop ce qui gène dans la présence de toutes ces choses qui sont là pour aider à la compréhension. Un habitué trouvera ça peut-être lourd, un nouveau trouvera ça clair (j'espère).

Le nombre de réponses, c'est pratique pour voir les sujets "chauds".

Enfin, l'accessibilité ça ne touche pas que 10% des utilisateurs, ça touche 100%. Pas besoin d'être aveugle pour ne rien comprendre à la liste.

**Comment by SpaceFox** [comment]
Je suis pas convaincu du tout, mais voyons ce que vont en dire les
utilisateurs.

Attention avec les nombres de topics / de posts dans ces listes par contre
: si ce n'est pas dénormalisé, de doit être recalculé à chaque fois et
c'est lourd pour le serveur.

**Comment by ArnaudCalmettes** [comment]
> la présence du sous-titre (que je trouve inutile).

Je ne suis pas de cet avis. Le sous-titre correctement utilisé est un complément d'infos utile et précieux .

**Comment by Alex-D** [comment]
Ca je ne dis pas le contraire, mais 90% du temps il y en a pas ou il est inutile car mal utilisé.

Mais je suis complètement d'accord avec ta vision utopique de son usage :)

On en arrive quand même à : tel que c'est là, on ne peux pas réduire en hauteur "à cause" de ça.

Perso, la hauteur ne me déplaît pas actuellement.

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis plus d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.
