### ISSUE TITLE
Notifications HS

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#690]
Les notifications ne fonctionnent pas :
- La notification ne mentionne pas le topic ("Bidule a posté")
- La notification ne renvoie pas au bon post (je remettrai l'erreur exacte quand j'en aurai une nouvelle).

**Comment by cgabard** [comment]
Moi ce matin qui avait aussi une notif MP, les notifs forum avaient le nom et le liens du MP (si ça peut aider pour trouver le bug). Par contre le nombre correspondait bien à celles du forum avec les bons avatar

**Comment by SpaceFox** [comment]
Je parle des notifs du forum, au fait.

**Comment by cgabard** [comment]
Oui mais justement, les notifs de MP fonctionnent mais celles des forums pointent chez moi vers un MP. Je pense qu'il est là le prob. Et vous ne voyez pas ce phénomène, et donc des champs vides, car vous n'avez juste pas de notifs de MP

**Comment by SpaceFox** [comment]
Ahhh OK :)

**Comment by GerardPaligot** [comment]
Je lance une idée comme ça : On ne pourrait pas créer une app (module)
"notification" dans le projet pour gérer et centraliser l'ensemble des
notifications ? Ca permettrait de construire des notifications venant de
forums, des MPs, etc. et de pouvoir debugger cette fonctionnalité plus
facilement. Me semble que c'est plus ou moins éparpillée pour l'instant.

Voilà, c'est une idée. :)

**Comment by Alex-D** [comment]
C'est personnellement ce que je souhaitais au départ @GerardPaligot 

Mais a priori ça a été simplifié pour des questions de gain de temps et de complexité (pas utile pour le lancement du site quoi).

En tous cas, je suis pour :)

**Comment by Alex-D** [comment]
C'est réparé visiblement donc je ferme :)
