### ISSUE TITLE
Erreur de lien dans les sujets suivis

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#691]
Cas : j'ai de nouvelles interventions dans le menu "sujets suivis" (lien en gras).

Le lien ne renvoie pas vers le nouveau message, mais vers le message d'avant le nouveau message (PS : i.e. le dernier message lu, et pas le premier message non lus).

Il me semble que c'est une régression, parce que je crois avoir déjà corrigé ce problème (pas sûr à 100%)

**Comment by Eskimon** [comment]
Il me semble au contraire que c'etait comme ca avant (mais idem, pas sur a 100%)

**Comment by SpaceFox** [comment]
Je sais que ça a été comme ça à une époque. Est-ce que ça l'était hier... la question est là en fait, il faudrait remonter l'historique :D

**Comment by firm1** [comment]
Moi je suis sur que c'était comme ça avant. Car je l'avais implémenté ainsi
pour arriver sur le message a N-1 c'est a dire le dernier message lu.

**Comment by Alex-D** [comment]
Solved !
Pour moi c'est un bon comportement, on peut revoir un bout du contexte avant de continuer.

**Comment by SpaceFox** [comment]
J'ai créé cette issue justement pour en discuter. On ne peut donc pas la fermer juste "parce que c'était comme ça avant".

Personnellement, je ne comprends pas le comportement actuel.
Si j'ai une notification de nouveau message, je m'attends à tomber sur ce nouveau message. Pas sur le dernier message que j'ai _déjà_ lu.

**Comment by SpaceFox** [comment]
D'autre part, je confirme que c'est bien une régression.

Depuis [cette PR](https://github.com/zestedesavoir/zds-site/commit/7061fe923313246def336733146a068a90b6a4bc), le comportement de cette liste est le suivant :
- Si le topic est _déjà_ lu, on renvoie vers le dernier message lu.
- Si le topic _a des messages non lus_, on renvoie vers le _premier message non lu_.

**Comment by Alex-D** [comment]
Ah désolé, je retire les tags liés au bug alors.

C'est discutable le fait de tomber sur le bon message ou celui d'avant. Ca peut être pratique dans le cas où on veut recontextualiser. C'est ennuyeux quand on vient juste de lire le topic.

Du coup, je pencherais peut-être de ton côté.

La PR que tu cite ne touche que base.html, or ça bug en ce moment même et je pense que tu te base de ton côté sur la page qui liste toutes les notifs, qui n'a donc pas le même comportement (pas le même template).

**Comment by SpaceFox** [comment]
> Ah désolé, je retire les tags liés au bug alors.

Régression == bug.

> La PR que tu cite ne touche que base.html, or ça bug en ce moment même et je pense que tu te base de ton côté sur la page qui liste toutes les notifs, qui n'a donc pas le même comportement (pas le même template).

Non, je me base sur le menu de gauche.

**Comment by Alex-D** [comment]
Le menu de gauche n'est pas touché par la PR que tu link ^^

**Comment by SpaceFox** [comment]
Le titre `<h3>Sujets suivis</h3>` dans le bloc `{% block sidebar %}` c'est pas le menu de gauche ?!

**Comment by Alex-D** [comment]
My bad ! J'ai lu trop vite "base.html" or c'est bien "forum/base.html" donc ouep.

Je rajoute ça dans un prochain merge (j'essaye de corriger les notifs, le bug doit être similaire).

**Comment by Alex-D** [comment]
Mergé, et normalement en prod !
