### ISSUE TITLE
Mettre un tag sur la version pre-merge

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#692]
Je demande l'avis général : pensez-vous qu'il soit judicieux de mettre un tag sur la dernière version de la branche dev **avant** le merge de l'intégration ?

Personnellement, je trouverais ça très pratique, notamment parce que je vais revoir le coder régulièrement pour corriger les choses que j'aurais oublié pendant les merges.

**Comment by SpaceFox** [comment]
Mettre un tag sous Git ne coûte rien. Taggue donc si tu veux :)

**Comment by Alex-D** [comment]
Comment le nomme-je ?

(Faut passer obligatoirement par la commande git pour tagguer sur Github ?)

**Comment by firm1** [comment]
J'aimerai que nos tags soit liés à des déploiements de version, donc
vaudrait mieux qu'on evite de tagguer tout ce qu'on veut sous peine
d'embrouiller ceux qui débarquent.

**Comment by SpaceFox** [comment]
On est pas obligés de pousser les tags hein, ils peuvent rester en local
aussi.

Sinon j'y pense firm1, c'est l'occasion de faire une branche "release"
(puis "master" le jour venu).

**Comment by Alex-D** [comment]
Heu non @firm1 pour le coup j'aimerais un tag en ligne qui pointe vers la version avant le merge, c'est à dire un changement majeur. Car là c'est un peu la misère pour remonter l'historique et trouver ce que je veux rapidement.

**Comment by firm1** [comment]
> Sinon j'y pense firm1, c'est l'occasion de faire une branche "release"
> (puis "master" le jour venu).

Tout a fait, je le ferai ce soir quand j'aurai fini mes travaux/dernier
merges sur la prod.

**Comment by firm1** [comment]
> Heu non @firm1 https://github.com/firm1 pour le coup j'aimerais un tag
> en ligne qui pointe vers la version avant le merge, c'est à dire un
> changement majeur. Car là c'est un peu la misère pour remonter l'historique
> et trouver ce que je veux rapidement.

Si c'est juste pour toi, tu peux mettre dans tes bookmarks le lien de la
version d'avant merge.

**Comment by Alex-D** [comment]
J'aurais pensé que ça serait utiles à d'autres, mais ok, j'vais faire ça :)
