### ISSUE TITLE
Validation des tutoriels - dégagment du validateur

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#699]
N'importe quel staff peut virer son collègue validateur qui s'est réservé un tutoriel. Est-ce bien normal ? Je sais qu'on est entre gens civilisé mais quand même ! :D
Si oui, dans ce cas la sémantique "Se retirer" n'est pas tout a fait correct.
Si non, même remarque :D

Voici une capture d'écran pour illustrer le propos...
![](https://dl.dropboxusercontent.com/u/18967337/temp/valido.png)

**Comment by cgabard** [comment]
Je pense que c'est plutot bien car si un valido disparait de la surface de la terre, faut pouvoir prendre le relais. Les validos sont censé se parler, il n'y aura pas de soucis.

**Comment by Alex-D** [comment]
Ah en effet, j'avais la tête dans le code j'ai pas vu le contexte ^^

Par contre je pense que c'est nécessaire de pouvoir annuler la réservation : un valido réserve, comme à valider l'intro (exemple extrême) puis il part un mois en vacance. Un autre valido peut valider tout d'une traite et du coup vouloir récupérer le tuto pour le valider :)

**Comment by Eskimon** [comment]
Ca me convient, (surtout que le cercle des validateurs est pas non plus immense) mais dans ce cas la faudra juste changer le "Se retirer" pour un "Remplacer" ou un truc comme ca...

**Comment by Alex-D** [comment]
L'action serait plutôt "Annuler la réservation". Car le lien ne fait que ça, il ne remplace pas la réservation en cours.

**Comment by Alex-D** [comment]
Voilà c'est fait :)
