### ISSUE TITLE
Erreur 500 si je crée un article avec un nom deja existant

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#701]
Une erreur 500 est créée si je tente de créer un article avec un titre déjà existant.
Le problème vient de la création du dossier qui du coup existe déjà...

/zds/article/views.py ligne 368

Dans le cas d'un tutoriel ca passe par contre.

**Comment by ShigeruM** [comment]
En effet, côté tuto le répertoire créé contient la PK en préfixe, donc il n'y a pas de problème. Le soucis sur les articles peut simplement être corrigé an ajoutant la PK dans la méthode `get_path` (de la même façon que pour les tutos), seulement tous les articles déjà créés ne seront plus accessibles. Pour qu'il le redevienne, il suffit d'ajouter la PK au nom des répertoires.

A mon avis il faut le faire maintenant, pendant la bêta, car on n'a que 7 articles (en ligne en tout cas, mais il ne doit pas y en avoir des masses d'autres). En plus toutes les données vont être supprimées dans 2 semaines, alors de toute façon on n'aura plus le problème. Par contre ce serait gênant de devoir faire cette manip après l'ouverture au public.

J'aurais bien fait la PR mais je n'ai pas la possibilité de renommer les répertoires sur la Prod. Ou alors vous voyez une autre solution ?

**Comment by Eskimon** [comment]
J'approuve complètement l'idée ! @firm1 la balle est dans ton camp :D

**Comment by Eskimon** [comment]
Je réouvre, cette erreur existe toujours sur ma version locale !

**Comment by firm1** [comment]
bizarrement j'ai pu créer deux articles en local avec le même nom. Tu es sur de ta réouverture là @Eskimon ?

**Comment by Eskimon** [comment]
J'arrive a reproduire en local, mais je me demande si c'est pas juste la version local qui merdouille un peu... (genre si je crée deux articles avec le titre "Test" ca plante)

**Comment by Eskimon** [comment]
Bon j'ai rien dit, en prod' tout va bien donc c'est que c'est ma version local qui merdouille (SQLite je suppose ?)
