### ISSUE TITLE
Régression : il n'y a plus de robots.txt

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#702]
Le fichier robots.txt, créé dans l'issue #38, a disparu.

**Comment by Alex-D** [comment]
Sauf erreur de mes lunettes, il est ici : https://github.com/zestedesavoir/zds-site/blob/beta-0.2/robots.txt

Du coup, ça ne vient pas de moi.

**Comment by firm1** [comment]
F'xd.  C'était une configuration serveur non repliquée
