### ISSUE TITLE
Régression : les sitemaps.xml ne fonctionnent plus

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#703]
Les sitemaps.xml, créés dans l'issue  #38, ne fonctionnent plus.

**Comment by Alex-D** [comment]
Est-ce que ce bug a été résolu en même temps que le robot.txt ?

**Comment by firm1** [comment]
Nope.

**Comment by firm1** [comment]
Par contre, je me rends compte que c'est un bug de config serveur. En gros la redirection automatique qui a été mise sur toutes les urls qui ne se termine pas par `/` crée le bug.

Je n'arrive pas à trouver une solution propre de configuration serveur, donc je vais demander à @geoffreyc de s'en occuper

**Comment by geoffreyc** [comment]
Yup je vais voir ca

**Comment by geoffreyc** [comment]
Fix'd

Via:
if ($uri !~ . ){
    rewrite ^(.*[^/])$ $1/ permanent;
}

En gros, si l'url a une extension (.xml, .whatever) nginx ne redirige plus
vers "/". C'est la meilleur solution d’après moi.

2014-06-11 19:59 GMT+01:00 firm1 notifications@github.com:

**Comment by Alex-D** [comment]
Ca me semble être une excellente solution :)

**Comment by firm1** [comment]
Je confirme, there's back !
