### ISSUE TITLE
Questions quant aux choix de designs

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#705]
Je crée cette issue pour noter tous les choix de designs qui me paraissent étranges (Windows 7 / Firefox, sauf indication contraire).
1. Pourquoi tous les textes du footer sont en capitales ?

**Comment by SpaceFox** [comment]
1. Pourquoi y a-t-il des capitales aux endroits suivants :
   - Titres du menu de gauche
   - Items du menu principal
   - Items de niveau 1 dans les menus déroulants
   - Sur mon pseudo dans mon menu personnel (celle-ci horripile _vraiment_)
   - Titres de niveau 1 sur les menus déroulants de messagerie, notifications et alertes

Vous l'aurez compris, je n'aime pas les textes en capitales. Ça donne l'impression de crier et c'est peu lisible.

**Comment by Alex-D** [comment]
C'est une simple envie sur l'instant, ça rend mieux en ce sens où c'est "rectangle" et donc plus rectiligne / logique.

Si ça ne plait pas à d'autres, qu'ils se manifestent.

Et pour les titres, c'est simplement que si tu mets pas en majuscule (genre dans les dropdown) faut les agrandir, et y a plein d'items donc ça va augmenter la hauteur.

J'attends donc les retours d'autres personnes : à la limite, faudrait poster ça sur le forum plutôt qu'ici et reporter le lien :)

**Comment by SpaceFox** [comment]
Les tags se créent de la manière suivante : `[Tag]` et dans le titre ; or ils sont affichés de la manière suivante `#Tag` séparément du titre.

Si on veut que les utilisateurs s'en servent, ces tags devraient être affichés de manière à guider intuitivement l'utilisateur vers leur création, c'est-à-dire ainsi `[Tag]` avec le titre.

**Comment by Alex-D** [comment]
A part qu'en inline, [Tag] n'a aucun sens. Partout, les tags sont visualisés avec un #.

**Comment by SpaceFox** [comment]
> Partout, les tags sont visualisés avec un #.

C'est bien le problème que je soulève : les tags sont visualisés partout avec un # alors qu'ils se créent avec des [], ce qui est incohérent.

**Comment by geoffreyc** [comment]
D'où tu as vue que va avait aucuns sens? Pour moi [PHP] en début de titre
c'est très parlant
Le 4 juin 2014 21:31, "Alexandre Demode" notifications@github.com a écrit
:

**Comment by Alex-D** [comment]
@geoffreyc : c'est cohérent dans le titre oui. Mais pas lorsqu'il en est extrait je trouve. Mais le # n'est pas mieux. Mais je l'ai mis pour avoir quelque chose d'uniforme sur tout le site.

**Comment by SpaceFox** [comment]
> c'est cohérent dans le titre oui. Mais pas lorsqu'il en est extrait je trouve.

Là encore, pourquoi l'en avoir extrait, alors que c'est cohérent nativement dans le titre, et qu'en plus ça explique sans le moindre mot comment ça se crée ?

**Comment by GerardPaligot** [comment]
Etant un utilisateur de Twitter, j'ai tendance à préférer la syntaxe #Tag.
Ne pouvons-nous pas envisager l'inverse ? C'est à dire créer un tag avec un

# devant ou cela pose des problèmes ?

**Comment by geoffreyc** [comment]
Tant qu'il est en [ ] dans le titre, je pense pas que ça ai un si grand
impacte que ça si ils prennent une forme diffzrzntznt autre part.(imho)
Le 4 juin 2014 21:37, "Alexandre Demode" notifications@github.com a écrit
:

**Comment by Alex-D** [comment]
> Là encore, pourquoi l'en avoir extrait, alors que c'est cohérent nativement dans le titre, et qu'en plus ça explique sans le moindre mot comment ça se crée ?

Parce que c'est plus complexe à gérer au niveau du design et qu'il fallait faire vite car cette feature a été rajoutée récemment et ça n'était pas prévu dans le design initial.

**Comment by SpaceFox** [comment]
Il y a deux colonnes de chiffres dans la liste des forums, je n'ai pas la moindre idée de ce que ça peut être.

**Comment by Alex-D** [comment]
Y a des title dessus... c'était comme ça dans la version de dev, j'ai repris bêtement.

Une idée d'amélioration ?

**Comment by SpaceFox** [comment]
Oui, les supprimer. Aujourd'hui ça montre surtout qu'on est pleins de vide.

La place récupérée permettrait de remettre l'auteur et la date du dernier message (dans la dernière colonne).

**Comment by Alex-D** [comment]
Ok d'ac, je fais ça.

**Comment by SpaceFox** [comment]
Attends peut-être d'autres retours ^^

**Comment by Alex-D** [comment]
Je ne vois que moyennement l'intérêt de ces informations et elles vont être masquées sur mobile (plus tard), autant les retirer partout.

**Comment by firm1** [comment]
> Ne pouvons-nous pas envisager l'inverse ? C'est à dire créer un tag avec
> un # devant ou cela pose des problèmes ?

Le problème avec ça c'est que tes tags ne peuvent pas contenir des espaces.
Ce qui est visiblement chiant si tu veux faire un tag "site web"

Bref pourquoi ne pas donner un style particulier comme sur la version avant
ce design ?

**Comment by Alex-D** [comment]
Je m'auto-cite :

> Parce que c'est plus complexe à gérer au niveau du design et qu'il fallait faire vite car cette feature a été rajoutée récemment et ça n'était pas prévu dans le design initial.

So : soon.

**Comment by ShigeruM** [comment]
Je reviens sur les mot en capitales pour me manifester : je n'aime pas non
plus.
Le 4 juin 2014 23:17, "Alexandre Demode" notifications@github.com a écrit
:

**Comment by Alex-D** [comment]
Ok d'ac, je repasse tout ça en normal, j'avais déjà eu la même remarque sur masquer, signaler, etc. Ca sera pareil pour là je présume.

**Comment by Alex-D** [comment]
Je up pour dire que la PR #762 a retiré les majuscules des titres.

**Comment by firm1** [comment]
En parlant de choix de design, le fond gris derrière les images (et toute autre balise figure), je trouve ça bof.

ça rend mieux sans fond.

**Comment by Alex-D** [comment]
J'essayerais ça alors :)

**Comment by SpaceFox** [comment]
On a encore des trucs à faire ici ou on peut clore cette issue ?

**Comment by Alex-D** [comment]
It's good :)
