### ISSUE TITLE
Erreurs dans la page "À propos"

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#706]
La page "A propos" mériterait d'être revue, elle n'est plus à jour (ne serait-ce que parce qu'elle mentionne PostgreSQL).

**Comment by Eskimon** [comment]
Ok je m'en suis occupé, PR qui arrive bientot !

**Comment by Eskimon** [comment]
J'y ai rajouté l'image logo de ZdS et cette histoire de PostgreSQL / MySQL
