### ISSUE TITLE
Pagination des résultats de recherche

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#708]
La page des résultats de recherche n'est pas paginée.

Si on fait une recherche avec peu de mot clés, c'est pas pratique.

**Comment by Alex-D** [comment]
C'est fait ! Merci à @sandhose !

**Comment by firm1** [comment]
je réouvre parce que la pagination ne marche toujours pas.

En allant sur ce lien par exemple `/rechercher/?q=balise&models=forum.post`, si je clique sur "2" dans la pagination, j'ai une 404

**Comment by Alex-D** [comment]
En fait, tu viens de relever un problème généralisé : la pagination ne prends pas en compte les paramètres en GET de l'URL. Et ça, c'est de ma faute par contre.

Je crée une issue dédiée car ça n'est pas lié à celle-ci, mais c'est global.

**Comment by Eskimon** [comment]
Dites, je reouvre : http://zestedesavoir.com/forums/sujet/789/recherche/?page=1#p10721

**Comment by Alex-D** [comment]
C'est corrigé.
