### ISSUE TITLE
Pas de design sur la page de recherche

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#709]
De toute évidence, la page de résultats de recheche n'a pas été intégrée d'un point de vue HTML

De plus, il reste du franglais (_"Search In :"_).

![zds_page_recherche](https://cloud.githubusercontent.com/assets/5786268/3177502/de64a1b6-ec10-11e3-92a1-9eb63dcb1348.png)

**Comment by SpaceFox** [comment]
Idem pour la "recherche avancée", qui semble être la même page en fait.

**Comment by Alex-D** [comment]
Je n'avais pas solr pour tester du coup j'ai codé à l'aveugle, ça rend pas bien à l'aveugle :-°

**Comment by sandhose** [comment]
J'install solr de mon côté, et je m'occupe de ça!

@Alex-D Je suppose que je prends le style des topics ?

**Comment by Alex-D** [comment]
Yep !

**Comment by Alex-D** [comment]
Factorise autant que possible.

Essaye de balancer les filtres dans la sidebar peut-être. L'attribut `form` d'un champ (input, select, etc) permet de le lier au form du même id. Ca peut être pratique pour sortir les checkbox du form et les placer où tu veux dans la page.

**Comment by sandhose** [comment]
'tain je comprend pourquoi tu t'en es pas occupé: Solr est juste hyper chiant à configurer Oo

**Comment by Alex-D** [comment]
C'est fait ! Merci à @sandhose !
