### ISSUE TITLE
Résolution des alertes et actions associées

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#71]
#### Quelques idées au sujet des alertes

Il faudrait changer et compléter le mode actuel de résolution des alertes, c'est-à-dire : 
- arrêter de résoudre automatiquement toutes les alertes associées à un post lorsqu'il est édité par un membre du staff ;
- donner la possibilité aux membres du staff de résoudre manuellement et individuellement les alertes ;
- conserver la résolution auto des alertes associées à un post lorsqu'il est masqué ;
- envoyer automatiquement un MP à l'auteur d'une alerte lors de sa résolution pour lui annoncer (texte + lien vers le post alerté). Ce MP pourrait être issu d'un membre "invisible" dans la liste des participants pour empêcher la réponse au MP, ou éventuellement d'un compte "générique" (ZdS, Staff, Zeste de Savoir, etc.).

**Comment by Alex-D** [comment]
- +1
- +1
- +1
- Je ne suis pas d'accord d'empêcher le dialogue suite à la modération. Ou alors proposer le dialogue avec le modérateur concerné.

Sur le SdZ v3 c'était plutôt cette politique qui était adoptée : on modère et on propose d'ouvrir le dialogue en privé si le membre n'est pas d'accord.

**Comment by Coy0te** [comment]
Attention, je fais ici allusion à un MP à l'auteur de l'alerte, pour lui dire merci d'avoir signalé et lui montrer qu'on a agi en conséquence derrière (en gros pour assurer un suivi de son alerte quoi). Je ne parlais pas d'un MP au membre qui a été modéré. =)

**Comment by Alex-D** [comment]
Autant pour moi, je plussois tout du coup...

Cela m'amène à la question suivante : est-ce qu'un MP est envoyé au membre duquel le message est modéré ? Moi, j'y verrais plutôt l'utilisation des notifications.

**Comment by cgabard** [comment]
Oui, si c'est pour prévenir l'auteur de l'alerte, il peut recevoir une notif "votre alerte a été résolu, merci" plutôt qu'un mp

**Comment by Coy0te** [comment]
Une notif irait tout aussi bien, c'est pas faux.

Après, je n'ai que survolé le code, mais je pense que techniquement l'envoi d'un MP engendrera moins de travail pour le dev, dans le sens où une notif actuellement c'est probablement une entrée dans une table (topic, user, post), a priori ça colle pas avec ce cas de figure.

**Comment by cgabard** [comment]
Oui si c'est compliqué, un MP fera l'affaire

**Comment by Alex-D** [comment]
C'est un peu dommage d'avoir des notifs pas simples à utiliser. Ça serait
tellement plus pratique de les utiliser plutôt que de "flooder" la boite à
MP.

Maintenant on peut imaginer que ça viendra dans une future itération.

**Comment by cgabard** [comment]
Je pense qu'il n'y a que @firm1 qui peut répondre plainement à cette question. Mais je suis d'accord avec toi : si c'est simple, utiliser les notif, sinon il faudrat le prévoir a moyen terme

**Comment by Coy0te** [comment]
Ouep, vos remarques appellent effectivement à une autre évolution, pouvoir notifier d'autres événements que le simple ajout d'un post dans un topic. Par exemple :
- résolution d'une alerte dont on est l'auteur ;
- déplacement/fermeture d'un sujet dont on est l'auteur ;
- publication/refus d'un tuto ou d'un article dont on est l'auteur ;
- modération d'un post dont on est l'auteur ;
- etc.

En parallèle, certaines de ces actions pourront être accompagnées d'un MP d'explication.

**Comment by firm1** [comment]
Je suis entièrement d'accord aussi en ce qui concerne l'implémentation des features citées par Coyote. Ce sont tous des points qui étaient noté dans un coin de ma tête pour deuxième itération.

En ce qui concerne le fait de prévenir le membre modéré, je suis d'avis aussi qu'on en fasse une simple notification.

Plus généralement, que se soit compliqué ou pas en mettre en place, il ne faut surtout pas vous bloquer parce que ça serait "trop compliqué a mettre en place". C'est au devs de répondre au besoin, et non au besoin de s'adapter aux outils. ça prend le temps que ça prend, mais, on ne va pas décider de faire des MP au lieu des notifications sous prétexte que c'est plus facile à implémenter. 
En gros, n'hésitez pas à vous lacher sur les features, et si c'est possible ça sera implémenté.

**Comment by cgabard** [comment]
Oui @firm1 on notai juste que pour la premiere version, prevenir par MP pourrait etre suffisant en attendant de passer par les notifs si les modifs sont trop importantes

**Comment by firm1** [comment]
> arrêter de résoudre automatiquement toutes les alertes associées à un post lorsqu'il est édité par un membre du staff ;

Check

> donner la possibilité aux membres du staff de résoudre manuellement et individuellement les alertes ;

Check

> conserver la résolution auto des alertes associées à un post lorsqu'il est masqué ;

Check

> envoyer automatiquement un MP à l'auteur d'une alerte lors de sa résolution pour lui annoncer 

Check

je ferme donc cette issue.

**Comment by Coy0te** [comment]
GG !
