### ISSUE TITLE
Problème dans la pages membres

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#712]
La page qui liste les membres `/membres/` ne donne pas le vrai nombre de membres existants outre le fait qu'elle ne soit pas designée (manque de pagination)

**Comment by Eskimon** [comment]
Elle a un réel interet cette page ? Une fois qu'il y a plein de membres tu as une grosse liste pas tres utile...

**Comment by SpaceFox** [comment]
Il me semble qu'elle sert pour modérer. A confirmer par un / une ancien
modo.

2014-06-04 20:09 GMT+02:00 Eskimon notifications@github.com:

**Comment by firm1** [comment]
> Elle a un réel interet cette page ? Une fois qu'il y a plein de membres tu as une grosse liste pas tres utile...

D'ou l'idée de la pagination, comme c'était fait sur le design précédent

**Comment by Alex-D** [comment]
Pour les modos c'est utile, on peut spawnkill les trolls quand ils font plein de multis
Tu peux demander à zingwai et son record de 11 secondes je crois :D

**Comment by GerardPaligot** [comment]
Voir la liste des membres, je n'en vois pas l'intérêt. Faire une recherche
sur les membres, j'en vois déjà plus. :)

2014-06-04 20:59 GMT+02:00 Alexandre Demode notifications@github.com:

**Comment by Alex-D** [comment]
@GerardPaligot ça a un intérêt, au moins de voir les X derniers inscrits pour repérer les trolls/multi et tout.

**Comment by GerardPaligot** [comment]
J'inclus ça dans la recherche. Rechercher par IP, par date d'inscription,
par nom, etc.

**Comment by Alex-D** [comment]
Ah oui, vu comme ça... pourquoi pas.

**Comment by Alex-D** [comment]
A tester, merger et pousser en prod :)

**Comment by Eskimon** [comment]
Ca semble correcte :) Je ferme !
