### ISSUE TITLE
Profil : la "dernière IP" ne fonctionne pas comme prévu

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#713]
Dans le profil, on a un champ "Dernière IP" qui ne correspond présentement pas à l'IP avec laquelle je suis connecté.

**Comment by Eskimon** [comment]
Ca m'etonne pas que ca marche pas, j'ai l'impression que le seul endroit ou on met a jour ce champ c'est dans "register_view"...

**Comment by Eskimon** [comment]
On doit pouvoir fermer ce ticket je pense ?

**Comment by Eskimon** [comment]
J'aimerais rouvrir pour signaler qu'apparemment la mise à jour de la dernière heure de connexion n'est pas correcte non plus... cf : http://zestedesavoir.com/articles/1/rediger-sur-zds/?page=3#p2926

**Comment by Alex-D** [comment]
La dernière connexion c'est l'heure à laquelle tu es passé par le formulaire de connexion. Ca n'est pas la même chose que l'heure de la dernière activité sur le site.

Néanmoins ça serait cool que ce soit l'heure de la dernière activité qui soit affichée.

**Comment by Eskimon** [comment]
Ah bah je crois qu'on est plusieurs à s’être planté sur la sémantique du truc alors...

Et avoir le dernier passage sur le formulaire de connexion c'est très utile ? Parce qu'un type régulier (comme moi) n'y repasse jamais du coup...

**Comment by ShigeruM** [comment]
C'est une régression, ça avait été fait [ici](https://github.com/zestedesavoir/zds-site/pull/479).

Il suffit de remplacer `usr.last_login` par `profile.last_visit` dans le template et ce sera bon.
