### ISSUE TITLE
Profil : indication "Staff" sans design

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#714]
Quand on va voir le profil d'un staff, on a un texte "Staff" qui flotte à côté de son avatar, sans aucun design particulier (Win7/FF).

**Comment by Alex-D** [comment]
Le profil n'est pas totalement designé : il a été jugé non prioritaire lorsque j'ai souhaité avancé dessus, je n'ai pas travaillé son design du tout depuis (et pas intégré, de fait).

Ca viendra avec une priorité faible.

**Comment by SpaceFox** [comment]
Cela dit, je suppose que si quelqu'un a envie de se mettre dessus, qu'il se fasse plaisir :)

**Comment by Alex-D** [comment]
En fait, y a déjà une issue dessus : #152

**Comment by Alex-D** [comment]
Est-ce que je peux fermer cette issue en la considérant comme étant un doublon ? Histoire qu'on s'y retrouve.

**Comment by Alex-D** [comment]
Pas de réponse, je considère donc cette issue comme doublon à la #152
