### ISSUE TITLE
La page "pages" mériterait un peu d'attention

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#715]
La page "Pages" (accessible via le fil d'Ariane) mériterait un peu d'attention :

http://zestedesavoir.com/pages/

C'est... succin.

**Comment by Alex-D** [comment]
Comme tu dis : accessible via le fil d'Ariane : seul point d'entrée, et y a pas grand chose à dire. C'est plus pour le SEO et l'accessibilité qu'autre chose.

**Comment by Eskimon** [comment]
Ca vaut vraiment le coup de garder ca ouvert ?

**Comment by firm1** [comment]
Je pense que oui. Pour y penser

**Comment by Eskimon** [comment]
Mais vous voulez faire quoi comme design ? Des jolis boites avec une images a chaque fois ?

**Comment by firm1** [comment]
> Mais vous voulez faire quoi comme design ?

Je ne sais pas il faut voir avec @SpaceFox

**Comment by Eskimon** [comment]
Ce ticket arrivera a feter son anniversaire dans un mois et demi \o/, dernier commentaire il y a 6 mois...

Ca mérite franchement de rester ouvert ? Je pense vraiment que ce ticket ne sera **jamais** traité, tout simplement parce que personne a part les bots des moteurs de recherche ne va sur cette page, et le cas échéant verront qu'elle ne sert a rien et repartirons autre part...

**Comment by Eskimon** [comment]
Je laisse jusqu’à fin avril. S'il y a pas de nouvelles/décisions quand je reviens je fermerais.

**Comment by Situphen** [comment]
@SpaceFox : Tu voulais améliorer cette page comment ?

**Comment by SpaceFox** [comment]
En fait, je crois qu'on s'en cogne. Je ferme.
