### ISSUE TITLE
Erreur d'URL dans le lien "Voir la doc complet" (Markdown)

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#716]
Dans l'aide Markdown, on a un lien "Voir la documentation complète", qui renvoie vers l'URL `URL_A_METTRE`.

C'est pertinent, mais du coup il faut le faire :D

**Comment by Eskimon** [comment]
C'est facile, donc j'm'en charge !

**Comment by Eskimon** [comment]
J'ai rajouté cette page...
Du coup faudra faire gaffe que cet article reste bien a cette adresse...

http://zestedesavoir.com/articles/1/rediger-sur-zds/

(Je l'ai rajouté en dur, c'est pas très beau...)

**Comment by firm1** [comment]
Je pense qu'il faudrait rajouter une variable pour ça dans le settings.py
avec une valeur vide qui sera mise à jour dans le setings_prod.py

**Comment by Eskimon** [comment]
Je laisse @Alex-D faire, je vois pas comment passer de Django au js :(

**Comment by SpaceFox** [comment]
Ça rejoint donc mon commentaire sur la présence de cette chose dans un JS

> _<

2014-06-04 20:30 GMT+02:00 Eskimon notifications@github.com:

**Comment by Alex-D** [comment]
C'est temporaire, tout comme l'éditeur, tout comme pas mal de choses.

Pour bien faire il faudrait faire le TEMPLATE PACK pour avoir un champ dédié à l'édition MD et pouvoir lui coller le bouton d'aide et compagnie.

Du coup dépendant de la #464
