### ISSUE TITLE
Articles/Tutos : Le texte colle la bordure gauche

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#717]
Quand on a un écran pas gigantesque, le texte du tuto (titres compris) se retrouve collé à la colonne qui délimite le menu de gauche (Win7/FF)

Une marge serait la bienvenue.

**Comment by Alex-D** [comment]
+1 Prévu pour bientôt :)

**Comment by Alex-D** [comment]
Fait :)

**Comment by sandhose** [comment]
Testé en prod ; Fix'd :)
