### ISSUE TITLE
Regression : le contenu dus mini tutos a disparu

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#718]
Lors de la publication des minitutos, on ne voit que l'introduction et la conclusion, le contenu s'est envolé.

**Comment by Alex-D** [comment]
Il me semble qu'il y a une issue sur le fait qu'on ne peux pas éditer les extraits, peut-être est-ce lié ?

**Comment by Taluu** [comment]
Lorsqu'on visionne le tuto en mode hors ligne, les parties sont bien là...

Peut-être qu'il manque un petit quelque chose lorsqu'on valide : la sélection des parties à valider / publier ? En tout cas c'était comme ça sur le sdz...

**Comment by Alex-D** [comment]
Ou peut-être que mes templates sont pas tout à fait correctes ^^"
