### ISSUE TITLE
Impossible de télécharger un tuto en PDF

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#719]
Si j'essaie de télécharger un tuto (ici celui sur les représentations intervallaires) en PDF, j'obtiens cette erreur :

> IOError at /tutoriels/telecharger/pdf/
> [Errno 2] No such file or directory: u'/opt/zdsenv/ZesteDeSavoir/tutoriels-public/70_la-representation-intervallaire/la-representation-intervallaire.pdf'

Traceback :

```
Environment:


Request Method: GET
Request URL: http://zdsappserver/tutoriels/telecharger/pdf/?tutoriel=70

Django Version: 1.6.5
Python Version: 2.7.3
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps',
 'django.contrib.humanize',
 'south',
 'crispy_forms',
 'crispy_forms_foundation',
 'email_obfuscator',
 'pipeline',
 'haystack',
 'munin',
 'zds.utils',
 'zds.pages',
 'zds.gallery',
 'zds.mp',
 'zds.newsletter',
 'zds.article',
 'zds.forum',
 'zds.tutorial',
 'zds.member',
 'django.contrib.admin')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'zds.utils.ThreadLocals',
 'zds.middlewares.SetLastVisitMiddleware.SetLastVisitMiddleware')


Traceback:
File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/zdsenv/ZesteDeSavoir/zds/member/decorator.py" in _can_read_now
  21.         return func(request, *args, **kwargs)
File "/opt/zdsenv/ZesteDeSavoir/zds/tutorial/views.py" in download_pdf
  2569.             "rb").read(),

Exception Type: IOError at /tutoriels/telecharger/pdf/
Exception Value: [Errno 2] No such file or directory: u'/opt/zdsenv/ZesteDeSavoir/tutoriels-public/70_la-representation-intervallaire/la-representation-intervallaire.pdf'
```

**Comment by cgabard** [comment]
Oui en fait le truc est que la generation par pandoc plante, avant, et donc on ne sait pas pourquoi.

Ce qu'il faut faire en fait c'est loggué les erreurs de pandoc et permettre a l'admin de les consulter

**Comment by Coy0te** [comment]
Est-ce que ce tuto a été importé depuis un fichier datant d'avant ma dernière passe sur les tutos (il y a environ 10 jours), ou d'après ?

Si c'est avant, alors c'est peut-être juste un dollar non échappé qui traîne dans le tuto est qui fait planter la conversion PDF, ce bug avait été relevé par firm1 il y a un moment et c'est pour ça que j'avais dû re-parser les cours.

Si c'est après, alors c'est autre chose et si jamais ça concerne encore un élément de syntaxe dans les tutos convertis, prévenez-moi.

**Comment by Taluu** [comment]
Ce tuto n'est pas issu de l'importation (je l'ai créé from scratch), donc je doute que ce soit la cause du bug...

**Comment by cgabard** [comment]
il y a quoi dans ton tuto ? tu aurais un liens ?

Christophe.

**Comment by Taluu** [comment]
C'est celui sur la représentation intervallaire, cité par Spacefox : http://zestedesavoir.com/tutoriels/70/la-representation-intervallaire/

Pour le md, ou plutôt ce qui y correspond à peu près : https://github.com/Taluu/tutorial-sql-interval

**Comment by cgabard** [comment]
Sans le log pandoc, ça va etre compliqué

Christophe.

**Comment by Taluu** [comment]
Je te comprend, mais j'y ai pas accès, pour ça faut pinger ceux qui ont accès aux logs...

**Comment by geoffreyc** [comment]
Je ne connais pas assez pandoc, mais si quelqu'un me dit comment/ou trouver
les logs, je met ca en place.

**Comment by cgabard** [comment]
En fait le prob est qu'ils ne sont pas logué actuellement. C'est la
premiere étape necessaire pour résoudre ce bug

Christophe.

**Comment by geoffreyc** [comment]
Ca se fait a quel niveau? Pandoc meme, ou au niveau du code qui genere ca?

2014-06-05 10:04 GMT+01:00 Christophe Gabard notifications@github.com:

**Comment by cgabard** [comment]
Au niveau du code qui lance pandoc je pense, mais firm1 pourrait confirmer

Christophe.

2014-06-05 11:07 GMT+02:00 geoffreyc notifications@github.com:

**Comment by cgabard** [comment]
Ici précisément je pense :
https://github.com/zestedesavoir/zds-site/blob/ff17ad991e411fec13dc516c93f1ac3165c846ac/zds/tutorial/views.py#L2746

Christophe.

2014-06-05 11:26 GMT+02:00 Christophe Gabard christophe.gabard@gmail.com:

**Comment by geoffreyc** [comment]
Nice, je m'y penche ce midi pendant ma pose voir si je peux faire ca. Si
firm1 se manifeste et qu'il sait deja quoi faire, je lui laisse la main.

On Thu, Jun 5, 2014 at 10:29 AM, Christophe Gabard <notifications@github.com

**Comment by cgabard** [comment]
Je crois pas que os.system permet de récupérer le contenu de std in. Ou alors faut voir si il y a une option de pandoc pour ecrire les logs dans un fichier

**Comment by geoffreyc** [comment]
Sinon de facon plus simple, si je rajoute  "2>&1 | tee -a pandoc.log" (pipe
sterr et stout vers un fichier log) ?

2014-06-05 10:44 GMT+01:00 Christophe Gabard notifications@github.com:

**Comment by cgabard** [comment]
Oui mais chaque generation va ecraser le precedent log. Ça peut suffir pour
debuguer rapidement pour la sortie et nous laisser le temps de revoir une
version plus propre en effet.

Christophe.

2014-06-05 11:50 GMT+02:00 geoffreyc notifications@github.com:

**Comment by geoffreyc** [comment]
Non justement le -a fait en sorte que ça "append" a la suite si le fichier
existe :)

2014-06-05 11:04 GMT+01:00 Christophe Gabard notifications@github.com:

**Comment by geoffreyc** [comment]
Si quelqu'un a le temps de tester ca, moi je me peux pas n'ayant pas
d'environement de dev zds sur ma machine:
#773

2014-06-05 11:05 GMT+01:00 geoffrey compagnon speedking34@gmail.com:

**Comment by geoffreyc** [comment]
Tu peux ne pas close stp @Alex-D, l'issue n'est pas résolu

.La prod est maintenant a jour et les erreurs seront loggé, si quelqu'un
veut bien faire les actions nécessaire pour les générer :)

**Comment by Alex-D** [comment]
J'ai pas fermé oO ou alors j'ai fail... désolé.

**Comment by Taluu** [comment]
Ca a été autoclose par ton commit (car il comportait `fix #719`, au lieu de `ref #719` par exemple)

J'ai réouvert de toutes manières

**Comment by geoffreyc** [comment]
C;est bon a savoir, mes excuse pour l'accusation @Alex-D

**Comment by cgabard** [comment]
@geoffreyc : tu peux checker le log là ? J'ai dépublié et republié le tuto, normalement ça a dut lancer la commande à pandoc

**Comment by geoffreyc** [comment]
alors nous voici nous voila:

pandoc: Duplicate note reference `schema' "source" (line 768, column 1)
pandoc: Duplicate note reference`schema' "source" (line 362, column 1)
pandoc: Duplicate note reference `schema' "source" (line 768, column 1)
pandoc: Duplicate note reference`schema' "source" (line 362, column 1)
pandoc: Error producing PDF from TeX source.
! Missing $ inserted.
<inserted text>
                $
l.204 \begin{array} {lcl}

pandoc: Duplicate note reference `schema' "source" (line 768, column 1)
pandoc: Duplicate note reference`schema' "source" (line 362, column 1)
pandoc: Duplicate note reference `schema' "source" (line 768, column 1)
pandoc: Duplicate note reference`schema' "source" (line 362, column 1)
pandoc: Duplicate note reference `schema' "source" (line 768, column 1)
pandoc: Duplicate note reference`schema' "source" (line 362, column 1)
pandoc: Error producing PDF from TeX source.
! Missing $ inserted.
<inserted text>
                $
l.204 \begin{array} {lcl}

pandoc: Duplicate note reference `schema' "source" (line 768, column 1)
pandoc: Duplicate note reference`schema' "source" (line 362, column 1)

2014-06-05 15:43 GMT+01:00 Christophe Gabard notifications@github.com:

**Comment by Taluu** [comment]
Ca a du coup l'air d'être lié au problème du croisement des références. J'ai en effet deux références "schema", qui sont chacun dans deux parties différentes.

**Comment by Taluu** [comment]
(ca me gène pas de changer les réfs ceci dit)

**Comment by cgabard** [comment]
Oui manifestement il y a ce prob mais qui va etre dur a corriger à part une demande de mise a jour à la main tant que on ne passe pas par zmarkdown avant. 

Il doit y avoir aussi des $ non échappé manifestements.

**Comment by cgabard** [comment]
en fait non pas forcément. Ça doit etre dans la partie de notre syntaxe rajouté qui fait penser à latex qu'on est dans un environnement de math. Ça va etre pénible ça. On peut pas trop savoir où avant de voir le résultat final (et comment passer outre)

**Comment by firm1** [comment]
Pour debugguer, téléchargez la version markdown complète du cours et avec pandoc chez vous, tentez de le convertir en tex puis de tex en pdf.

**Comment by cgabard** [comment]
Oui mais firm1 le prob avec ça est qu'on utilise pas le meme code de concaténation que sur la prod ce qui est la source du prob là.

Maintenant on peut lire les logs a minima

**Comment by firm1** [comment]
'fin moi je vois que le PB vient d'un truc avec des dollars. Pas plus d'infos.
Ceci dit, faudrait clairement séparer la publication d'un tuto de la génération des fichiers

**Comment by cgabard** [comment]
Non pas forcément et en tout cas ce n'est pas ça qui bloque la génération du pdf a priori. Le truc avec le $ ne semble pas bloquant puisqu'il dit qu'il en insere un pour commencer un $ oublié (ce qui semble éttonant mais soit)

**Comment by Taluu** [comment]
D'ailleurs, `$` ne marche que pour les formules inline ; j'ai du utiliser `\\( ... \\)` pour les formules block.

J'ouvre un ticket sur zestedesavoir/Python-ZMarkdown

**Comment by Taluu** [comment]
Ceci étant dit, me semble que ca merdait avant même que je convertisse les formules inline en `$formule$`... donc devrait pas y avoir de `$` qui trainaient à ce moment.

**Comment by cgabard** [comment]
Il y a les deux. Tes formules expliques les warnings sur les $ (cf ma réponse sur l'autre issue). Mais le prob de ref doit aussi bloquer la génération.

**Comment by Taluu** [comment]
Je viens de convertir tous les `\\( ... \\)` en `$$...$$` (cf le commentaire de @cgabard sur zestedesavoir/python-zmarkdown#26).

Le pdf a l'air de passer. En gros, ca fail si on utilise la syntaxe pdp pour les balises de maths... ?

**Comment by firm1** [comment]
> En gros, ca fail si on utilise la syntaxe pdp pour les balises de
> maths... ?

En fait, la syntaxe officielle de zds c'est avec les $$ pour le multiligne.
C'est pour ça que le pdf ne se génerait pas. Donc en gros, problème résolu,
vous pouvez fermer.

Et ouvrir une issue pour interdire la syntaxe "de pdp" dans mathjax.

2014-06-05 18:04 GMT+02:00 Baptiste Clavié notifications@github.com:

**Comment by Alex-D** [comment]
> Et ouvrir une issue pour interdire la syntaxe "de pdp" dans mathjax.

Mathjax c'est côté front, du coup ça n'empêche pas l'utilisateur de le faire et de faire planter le truc. Il faudrait une sorte de message d'erreur pour dire que la syntaxe est incorrecte ou quelque chose du genre non ?

**Comment by cgabard** [comment]
En fait faut surtout que ça soit notre zmarkdown qui parse pour gerer ces
cas la, mais on le sait, par contre mathjax ne devrait pas déclencher
Le 5 juin 2014 21:47, "Alexandre Demode" notifications@github.com a écrit
:

**Comment by firm1** [comment]
> Mathjax c'est côté front, du coup ça n'empêche pas l'utilisateur de le faire et de faire planter le truc

Sur ce cas, l'utilisateur n'est pas censé mettre dans le code un dollar sans l'échapper. Du coup si on reprend le cas de Talus ici, il a mis des dollars dans son code sans les échapper et il pensait que c'était dans un bloc maths (parce que MathJax l'a interprété ainsi). Donc vu comme ça, un dollars dans le code sans échappement fait échouer la conversion, car ne respecte pas la syntaxe.

D'ou le fait que si on interdit a mathjax d'interpreter ça, l'utilisateur ne se laissera pas tromper.

**Comment by Taluu** [comment]
Je n'avais pas de `$` dans mon code. J'avais juste des `\\( .... \\)` au lieu de justement `$...$` et `$$....$$`.

En gros, c'est juste que mathjax (ou autre... ?) insère tout seul un `$`, mais n'arrive pas à insérer le fermant de son coté.

**Comment by firm1** [comment]
De ce que j'ai vu, le code qui a posé problème c'est celui ci : 

```
\\( \begin{array} {lcl}
    \text{borne droite} - \text{borne gauche} & = & 7 - 2 \\\ 
                                              & = & 5     \\\ 
                                              & = & 4 + 1 \\\ 
                                              & = & \boxed{2} \times 2  + 1
\end{array} \\)
```

[Regarde son rendu final en Latex](http://johnmacfarlane.net/pandoc/try/?text=des+n%C5%93uds+du+premier+niveau+du+sch%C3%A9ma%2C+celui+ayant+les+bornes+2+et+7+%3A%0A%0A\%28+begin{array}+{lcl}%0A++++text{borne+droite}+-+text{borne+gauche}+%26+%3D+%26+7+-+2+\+%0A++++++++++++++++++++++++++++++++++++++++++++++%26+%3D+%26+5+++++\+%0A++++++++++++++++++++++++++++++++++++++++++++++%26+%3D+%26+4+%2B+1+\+%0A++++++++++++++++++++++++++++++++++++++++++++++%26+%3D+%26+boxed{2}+times+2++%2B+1%0Aend{array}+\%29&from=markdown&to=latex) et tu verras qu'il est mal formé.

EDIT: 
Rendu : 

``` latex
des nœuds du premier niveau du schéma, celui ayant les bornes 2 et 7 :

\textbackslash{}(

\begin{array} {lcl}
    \text{borne droite} - \text{borne gauche} & = & 7 - 2 \\\ 
                                              & = & 5     \\\ 
                                              & = & 4 + 1 \\\ 
                                              & = & \boxed{2} \times 2  + 1
\end{array}

\textbackslash{})
```

**Comment by cgabard** [comment]
Bon comme je suis toujours abonné à ce sujet...

Talus a raison. en fait les parseur markdown ne reconnaissent pas les
délimiteurs de début/fin qu'il avait été utilisé. Il ne s'en était pas
rendu compte car mathjax de son coté le fait et donc la formule, par
chance, apparaissait bien. Cependant pendant le parsing de latex il tombait
sur \begin{array} qui est une commande de l'environement de math; Du coup
il faisait comme si il l'avait oublié et l'ajoutait tout seul. Mais comme
il n'y a pas de simbole de fin, ça déconne.

La solution est de ne pas utiliser cette syntaxe supporté par mathjax
uniquement et de virer son support dans la config. Et d'utiliser les
doubles dollars pour les formules multi lignes (ce qui n'est pas précisé
dans l'article de shig)

Christophe.

**Comment by firm1** [comment]
La PR référencée ci-dessus permet de ne plus montrer le lien de téléchargement si un format d'export est indisponible.

Donc techniquement l'issue est corrigée (si j'ai un lien de téléchargement alors on a plus d'erreur). 

En sachant que les tutos peuvent ne pas s'exporter pour plein de raisons (un caractère spécial non échappés, une URL d'image indisponible, etc.), la correction de l'export se fera sur le long terme.
