### ISSUE TITLE
Liens de connexions a la place de la zone d'édition

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#72]
Lorsque l'on est sur un message du forum, sans être connecté, rien ne s'affiche du tout a la place de la zone d'édition. Il serait pertinent pour engager le visiteur d'utiliser cet espace par un message type "inscrivez vous ou connectez vous pour répondre a ce message" avec les liens associés.

**Comment by firm1** [comment]
Cette issue est fixée, je ferme donc.
