### ISSUE TITLE
Les tags sur les tutos sont pratiquement invisibles

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#720]
Lorsqu'on visite un tuto, les tags auxquels il est attaché sont relégués en gris clair sur font gris très clair, en haut à droite. Autant dire qu'ils sont pratiquement invisibles.

Sans doute mériteraient-ils une meilleure mise en avant - sans pour autant les rendre fluorescents.

![zds_tuto_tags](https://cloud.githubusercontent.com/assets/5786268/3177849/950dc00c-ec14-11e3-96e1-4fa7a0155c09.png)

**Comment by Alex-D** [comment]
Les couleurs ont changé entre temps.

Je propose de renforcer le gris de leur texte vers quelque chose de plus foncé, est-ce que ça vous semble judicieux/suffisant ?

**Comment by Alex-D** [comment]
J'ai poussé un peu le contraste, faudra me dire si c'est mieux.

**Comment by Alex-D** [comment]
Des retours du coup ? Histoire de savoir si les modifs apportées sont suffisantes ou non.

**Comment by coma94** [comment]
Pour moi c'est mieux, mais je l'aurais bien vu avec la même valeur que le
bouton "zen mode", qui est juste en dessous.

2014-06-07 3:06 GMT+02:00 Alexandre Demode notifications@github.com:

**Comment by firm1** [comment]
> Pour moi c'est mieux, mais je l'aurais bien vu avec la même valeur que le
> bouton "zen mode", qui est juste en dessous.

pluzin partout

**Comment by Alex-D** [comment]
Je vais passer sur tous les coloris pour uniformiser dans ce cas.

**Comment by Alex-D** [comment]
C'est actuellement le cas en prod. J'invite à la réouverture en cas de besoin, il n'y eu aucun avis contraire, donc je ferme.
