### ISSUE TITLE
Mauvaise prévisualisation MD sur les commentaires de tutos

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#721]
Lorsqu'on lance une prévisualisation sur un commentaire de tuto, le rendu n'est pas le même que celui obtenu.

En particulier, la police appliquée lors de la prévisualisation est celle des textes longs (avec empattements), alors que celles utilisée dans le commentaire réel est celle des textes de forums (sans empattements).

**Comment by SpaceFox** [comment]
Même problème avec la citation, qui ne rends pas pareil sur la prévisualisation et une fois envoyé.

**Comment by Alex-D** [comment]
Corrigé :)
