### ISSUE TITLE
Le bouton "abréviation" ne semble pas fonctionner

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#722]
Exemple sur ce message : http://zestedesavoir.com/tutoriels/70/la-representation-intervallaire/?page=1#p2005

Il est sensé y avoir une abréviation sur "Abbréviation", mais je ne vois rien en FO.

Pourtant, il y a un truc dans le mardown (tout en bas du texte)... A creuser.

**Comment by Alex-D** [comment]
C'est un bug de front ? Si oui : tag front
Un bug de MD ? Si oui : tag markdown
etc.

Merci renard :)

**Comment by SpaceFox** [comment]
Je ne sais pas c'est un bug de quoi, d'où le "à creuser" et le manque de
tags...

2014-06-04 20:50 GMT+02:00 Alexandre Demode notifications@github.com:

**Comment by cgabard** [comment]
En fait non c'est pas vraiment un bug. La modal insere le markdown permetant de définir une abbréviation. Mais tu n'a pas inséré le texte déclanchant dans ton texte, c'est normal qu'il ne soit pas visible !

regarde mon exemple :  http://zestedesavoir.com/tutoriels/70/la-representation-intervallaire/?page=1#p2018

Bref je pense que tu pourras fermer

**Comment by Alex-D** [comment]
Je confirme que ça fonctionne bien. Ca serait _à la limite_ une vérification à faire dans l'éditeur pour sa prochaine version.

**Comment by SpaceFox** [comment]
Ben j'ai fait comme le reste : j'ai sélectionné le mot, j'ai choisi une
abréviation et j'ai cliqué sur "OK". Ca m'a donné ce que vous voyez là.

**Comment by cgabard** [comment]
Oui j'ai bien compris. C'est pour ça que je n'ai pas fermé. Mais c'est pas
un prob de markdown seulement de ce que doit faire la modale

**Comment by SpaceFox** [comment]
OK, c'est donc un bug front (le bouton ne fait pas ce qu'il devrait faire), je le taggue comme tel.

**Comment by Alex-D** [comment]
Priorité basse, ça fera partie de la réécriture de l'éditeur.

**Comment by firm1** [comment]
Fx'd
