### ISSUE TITLE
Impossible de désigner une image comme son avatar

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#724]
Dans les pramètres, c'est marqué : 

```
Choisir un avatar dans une galerie
Naviguez vers l'image voulue et cliquer sur le bouton "Choisir comme avatar".
Créez une galerie et importez votre avatar si ce n'est pas déjà fait !
```

Alors que dans la gallerie, on a pas le bouton "Chosir comme avatar"

**Comment by Eskimon** [comment]
Désolé @Alex-D j'ai vu que c'était à ma porté alors je l'ai vite fait rajouté...

**Comment by Alex-D** [comment]
Aucun soucis ! J'ai mergé, faut vérifier que ça fonctionne bien sur la prod.

**Comment by Eskimon** [comment]
Ok aussi en prod ! Je ferme :)
