### ISSUE TITLE
Regression : impossible d'importer un tuto directement depuis le serveur

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#725]
Avant on avait deux moyens d'importer un tuto. 
- En important le fichier .tuto
- En liant un tuto à un auteur en particulier

Maintenant, la deuxième méthode ne fonctionne plus.

**Comment by Alex-D** [comment]
Y a pas le tag front, est-ce le back ou le front qui coince ?

**Comment by firm1** [comment]
C'est un bug de front

**Comment by Alex-D** [comment]
Corrigé :)
