### ISSUE TITLE
Interface admin dédiée

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#726]
Je voulais intégrer l'affichage des données Google Analytics pour les auteurs de tutoriels (cf. #324 ). Il me faut donc intégrer tout le flow OAuth2 de Google (ce qui n'es pas un problème en soit). Le problème, est qu'il me fallait une interface pour connecter le compte Google Analytics à l'application... Et je me suis demandé "Et l'URL ? Je fout ça où ?"

En cherchant un peu, j'ai vu que le `/admin/` était utilisé par l'admin Django...

Ma proposition est simple: créer un module (si c'est bien comme ça que ça s'appelle avec Django) admin, avec dans `/admin/` un genre de dashboard/hub vers les différents outils (ça a pas besoin d'être beau, c'est juste la pour le concept), déplacer l'admin django vers `/admin/django`, et ainsi permettre plus tard de créer d'autres modules d'administration, avec des URLs cohérentes (en l'occurence, pour l'analytics, ça va sûrement être `/admin/analytics` )

Il y a aussi possibilité du coup de déplacer les outils d'administration de tutoriels et d'articles vers `/admin/tutoriels` et `/admin/articles` (au lieu de `/tutoriels/validation` et `/articles/validation` )

J'aimerais donc votre avis, et si quelqu'un peut mettre en place ce module `admin`, ça serais cool, étant donné que j'ai encore un peu de mal avec la structure de Django :-°

**Comment by Alex-D** [comment]
> Il y a aussi possibilité du coup de déplacer les outils d'administration de tutoriels et d'articles

J'approuve cette solution :)

**Comment by Eskimon** [comment]
Je ferme ici, la [ZEP-11](https://zestedesavoir.com/forums/sujet/835/zep-11-interface-de-statistiques-sur-les-tutoriels/) couvre plus largement la problématique, la discussion pourra avoir lieu la bas.
