### ISSUE TITLE
Erreur dans le fil d'Ariane des tutos

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#727]
Quand je vais sur la page "Tous les tutoriels" (a.k.a "Liste des tutoriels"), le fil d'Ariane dit :

> Accueil > Mes tutoriels > Liste des tutoriels 

Ce qui est factuellement faux, ce devrait être :

> Accueil > Tutoriels > Liste des tutoriels

**Comment by Alex-D** [comment]
C'est exact, problème d'héritage de vue.

**Comment by Alex-D** [comment]
Corrigé :)

**Comment by firm1** [comment]
Je réouvre, car le problème apparait lorsqu'on visualise les chapitres, les parties d'un big tuto

**Comment by Alex-D** [comment]
La refacto devrait avoir résolu tous ces soucis, à vérifier au prochain pull de la prod.

**Comment by Alex-D** [comment]
Cette fois c'est la bonne :)
