### ISSUE TITLE
Catégories de tutoriels disponibles mais vides

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#728]
Dans les catégories des tutoriels, on a plein de catégories vides et surtout qui le resteront pendant au moins un moment.

C'est assez néfaste en terme d'impression utilisateurs.

Il faudrait n'afficher les catégories que si elles contiennent au moins un tuto.

Ceci rejoint globalement l'issue #480.

**Comment by Alex-D** [comment]
Est-ce qu'on a un compteur de tuto par catégorie ? Si oui, c'est possible de tester ça dans les templates.

Le mieux ça reste de le faire en amont dans les vues.

**Comment by ArnaudCalmettes** [comment]
[Fixé par firm1](http://zestedesavoir.com/forums/sujet/246/jeux-videos/#p2487)
