### ISSUE TITLE
Les tags dans les tutos n'ont pas de lien

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#729]
Quand je clique sur un tag dans un tuto (ex : "#Mysql" dans l'exemple ci-dessous), je m'attends à voir tous les tutos avec ce tag, donc une liste d'au moins un tuto.

Or, ce lien a un href vide, donc rien ne se passe.

**Comment by Alex-D** [comment]
Cf les templates : je ne sais pas quelle url utiliser.

Je n'ai pas trouvé d'url dans les urls.py qui satisfasse cette fonctionnalité.

**Comment by Alex-D** [comment]
Voilà, normalement ça devrait fonctionner.

**Comment by firm1** [comment]
ça ne fonctionne pas !

**Comment by Alex-D** [comment]
Yep j'ai vu je suis dessus en même temps que la #727

Je fais une refacto des templates des tutos car c'est un peu le bazar.

**Comment by cgabard** [comment]
Une refacto des templates ? Encore ?

**Comment by Alex-D** [comment]
Ca factorise les tags et les auteurs dans une templates, ça centralise du coup les bugs possibles à ce niveau.

Ensuite, ça corrige plein de bugs (plusieurs issues concernée).

Donc j'appelle ça une refacto parce que ça touche plein de fichiers, mais c'est nécessaire.

**Comment by Alex-D** [comment]
Du coup, les tags devraient être corrigés dès le prochain pull de la prod.

**Comment by Alex-D** [comment]
Ca fonctionne :)
