### ISSUE TITLE
Connexion et NDD

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#73]
Quand je suis connecté à www.zestedesavoir.com, je ne le suis pas sur zestedesavoir.com (sans www).

Est-ce un bug, ou un truc dû à la conf htaccess temporaire ?

**Comment by firm1** [comment]
Ce doit être du à la config serveur.

Notre Admin Sys peut-il nous éclairer ?

**Comment by geoffreyc** [comment]
Il faut simplement décider de quel domaines utiliser (www/sans www) et de
faire un redirect en conséquence. Si on choisi de garder sans www, il
faudrait donc une redirection 301 du www -> non www pour éviter ce genre de
cas de figure.

2014/1/14 Geoffrey R. notifications@github.com

**Comment by SpaceFox** [comment]
Il vaut mieux faire l'inverse et garder www en domaine principal, car ça
permet de créer facilement des choses du style "le domaine
static.zds.comest sans cookies".

**Comment by cgabard** [comment]
Je réouvre car même si ce comportement est "normal" techniquement, il ne l'est pas pour l'utilisateur.

Si la solution de @geoffreyc convient a tout le monde, on pourrat la fermer une fois implémentée. Avant ça reste un bug en soit.

**Comment by SpaceFox** [comment]
À moins bien entendu que l'on puisse utiliser des cookies spécifiques à
zds.com sans qu'ils ne débordent sur static.zds.com (je ne sais plus...)

**Comment by Coy0te** [comment]
+1 pour le sans www par défaut.
Faudra pas oublier de rediriger également les .org, .fr, etc.

@SpaceFox , j'ai pas compris où est le problème avec les sous-domaines.

**Comment by Alex-D** [comment]
En gros SpaceFox redoute que les cookies du domaine soient accessibles dans les sous-domaines, alors que justement c'est le problème énoncer ici. Ne lui en voulons pas, c'est l'âge :-°

Je suis partisan du "sans www" car l'aire du www est dépassée, ça date de l'époque où on utilisait le répertoire www sur le serveur et donc le sous-domaine correspondait au dossier. Actuellement on fait ce qu'on veut, et sans www c'est plus court, plus beau, plus fun \o/

Bref, sur Apache, je sais comment on fait, mais pas sur ngix. En gros faut réécrire l'url www.zds.com vers zds.com, tout en prenant soin de bien garder ce qu'il y a derrière le NDD.

Pour info, sur Apache ça se passe comme ça :

```
<IfModule mod_rewrite.c>
    RewriteCond %{HTTPS} !=on
    RewriteCond %{HTTP_HOST} ^www\.(.+)$ [NC]
    RewriteRule ^ http://%1%{REQUEST_URI} [R=301,L]
</IfModule>
```

Voilà voilà :)

PS : je suis partisan également pour passer sur Apache plutôt que ngnix, car visiblement personne ne le connaît correctement.

**Comment by Coy0te** [comment]
> je suis partisan également pour passer sur Apache plutôt que ngnix, car visiblement personne ne le connaît correctement.

#### +1

**Comment by geoffreyc** [comment]
de tete:
location / {
    if ($http_host ~\* "^www.(.+)$"){
        rewrite ^(.*)$ http://%1$request_uri redirect;
    }
}

2014/1/15 DEMODE Alexandre notifications@github.com

**Comment by cgabard** [comment]
Je suis partisant d'utiliser celui que Geoffrey préfère car pour le moment c'est le seul admin sys

**Comment by Alex-D** [comment]
Je ne connais pas la config ngnix, mais le `location /` ça veut dire la racine ou bien tout ce qui en découle ?
Car du coup, dans le premier car c'pas bon, dans l'autre ça l'est :)

Faut rediriger aussi www.zds.com/toto vers zds.com/toto si tu vois ce que je veux dire. Simple question, histoire de ne pas avoir de surprise ^^

**Comment by SpaceFox** [comment]
Mon point c'était surtout d'éviter de faire l'habituel cookie "*.zds.com"
qu'on voit un peu partout.

Pour le reste, tous les serveurs HTTP du marché tiendront la charge sans
problème pendant des années, donc "ce que préfère Geo" me paraît une bonne
solution :D

Le 15 janvier 2014 11:07, Christophe Gabard notifications@github.com a
écrit :

**Comment by firm1** [comment]
En ce qui concerne Nginx vs Apache, je répète donc ce que j'ai [déjà dis par le passé](http://zds.leomartinez.fr/issues/48#note-19).

**firm1 avait écrit**

> étant donné que j'avais besoin d'un workflow (dev -> push) pour mettre en ligne ce que je développe, j'ai fais un bench rapide et je suis resté sur nginx. Si vous avez besoin d'apache, n'hesitez pas a faire l'install qu'il faut. Tant que mon workflow est en place et que le serveur tient la charge ça me va.

Les clés du serveur sont dispo pour tout le monde.

Pour ce qui est des redirections serveur, il faudrait rester sur zds.com tout simplement et redirigeant tout le reste dessus.

Et donc, @geoffreyc tu nous confirmes donc que tu t'en occupes ?

**Comment by geoffreyc** [comment]
Je suis sur le server atm mais je n'ai pas l'air d'avoir les perms
suffisantes pour overwriter /etc/nginx/sites-available/zestedesavoir

2014/1/15 firm1 notifications@github.com

**Comment by firm1** [comment]
Je viens de le chmoder en 664. ça devrais passer.

PS : je m'y connecte sur mon téléphone (pas évidant de configurer), donc vaut mieux que j'évite de faire du VI dessus.

**Comment by geoffreyc** [comment]
les perms sur le fichier sont "-rw-rw-r-- " ducoup en tant que user pas
dans le group root je peux que lire le fichier, pas le modifier.

2014/1/15 firm1 notifications@github.com

**Comment by geoffreyc** [comment]
Apres ca peut attendre que tu sois sur un pc, du ssh sur smartphone c'est
pas super pratique :D

2014/1/15 geoffrey compagnon speedking34@gmail.com

**Comment by firm1** [comment]
Non mais s'il faut attendre que je sois sur PC, tu risque d'attendre longtemps.

Tant que ça reste des lignes de commandes, ça va.

Je viens de rajouter zds au groupe root.

**Comment by geoffreyc** [comment]
Ca marche merci bien. Je ne peux par contre pas redemander nginx pour
prendre en compte les modifs du fichier config. (permission denied).

Ce serait peut etre plus simple d'installer sudo et de passer zds en sudoer?

2014/1/15 firm1 notifications@github.com

**Comment by firm1** [comment]
Un peu périlleux, mais je viens de le rajouter en sudoer.

**Comment by geoffreyc** [comment]
Merci bien !

Le ndd www.zestedesavoir.com redirige maintenant vers http://zeste...

**Comment by firm1** [comment]
Nice job.

Je ferme donc.
