### ISSUE TITLE
Les galeries ne sont pas designées

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#730]
D'évidence, il n'y a aucune intégration HTML sur les galeries.

Ici la vue d'une galerie, mais c'est pareil sur la liste et dans une moindre mesure sur la vue d'une image.

![zds_galerie](https://cloud.githubusercontent.com/assets/5786268/3178511/da5fa610-ec1a-11e3-815b-161ecab68d4d.png)

**Comment by sandhose** [comment]
I got this

---

Petite preview:
_Vue liste_:
![image](https://cloud.githubusercontent.com/assets/1549952/3245024/9bb7808c-f16e-11e3-82b9-aba95b281915.png)

_Vue grille_:
![image](https://cloud.githubusercontent.com/assets/1549952/3245065/147bc884-f16f-11e3-8cdc-902276c33946.png)

**Comment by firm1** [comment]
J'adore.

**Comment by SpaceFox** [comment]
+1

2014-06-11 15:58 GMT+02:00 firm1 notifications@github.com:

**Comment by sandhose** [comment]
Ça m'aurais arrangé ici d'avoir des thumbnail, j'utilise les images high-res la :+1: 

Mais bon, c'pas hyper urgent non plus! :smile_cat:

**Comment by sandhose** [comment]
Question: Est-ce qu'il faut gérer la pagination ? Si oui, environ combien d'images par pages ?

**Comment by firm1** [comment]
> Question: Est-ce qu'il faut gérer la pagination ? Si oui, environ combien d'images par pages ?

Faudra gérer la pagination oui, mais ça sera fait coté back-end. Il te renverra uniquement le nombre de galleries/images à afficher à chaque fois, donc théroriquement tu devrais juste rajouter la page pagination avec l'incrément sur `page=n`

**Comment by sandhose** [comment]
D'accord, donc je vous laisserai faire.

**Comment by Alex-D** [comment]
Pour la pagination, une fois le back fait y a plus qu'à include le template qui gère la pagination en fait (misc/pagination.part.html)

Va falloir qu'on réajuste pas mal de choses du coup, c'est pas accessible et il manque quelques trucs. Le vert alors que tout est bleu partout : bof, je ne sais pas ce que vous en pensez les autres ?

**Comment by firm1** [comment]
Maintenant que tu le dis Alex, je pense que le vert n'est pas la bonne
couleur en effet. Le bleu serait un meilleur choix.
Le 11 juin 2014 19:14, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
C'est fonctionnel et mergé. J'envoi ASAP quelques correctifs.
