### ISSUE TITLE
Améliorations générales sur les galeries

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#731]
Les galeries souffrent d'un certain nombre de manques / comportements étranges qui ne sont pas à proprement parler des bugs, mais qui laissent quand même l'impression que l'on (les développeurs) pas vraiment occupé. Ce qui, en ce qui me concerne, est parfaitement le cas.
- Un utilisateur peut créer plusieurs galeries de même nom. Pratique pour s'y repérer...
- On ne peut pas renommer une galerie

**Comment by poulp** [comment]
- On peut pas révoquer un utilisateur, ni changer ses droits (mais pour ça il faudrait un status du genre "créateur" ou "propriétaire")
- Il reste un todo pour l'edit d'image, l'ancienne instance physique n'est pas supprimée

**Comment by viki53** [comment]
Je rajouterai aussi que si les liens étaient des URLS (fournies après upload d'une image, pour le MD) complètes, ça éviterait pas mal de problème au copier-coller.

Et, tant qu'à faire, une version MD avec la miniature + lien vers l'originale serait pas mal à avoir…

**Comment by firm1** [comment]
> Je rajouterai aussi que si les liens étaient des URLS (fournies après upload d'une image, pour le MD) complètes, ça éviterait pas mal de problème au copier-coller.

C'est a dire ? Je n'ai pas bien compris.

> Et, tant qu'à faire, une version MD avec la miniature + lien vers l'originale serait pas mal à avoir…

En effet

**Comment by viki53** [comment]
Quand on upload une image dans une galerie, il y a des bouts de MD fournis pour insérer l'image dans un post/article/whatever. Sauf que l'URL est du style `/media/galleries/…` au lieu de commencer par `http://zestedesavoir.com/media/galleries/…`.

Du coup quand on utilise ça pour insérer un lien (en prenant le code de l'image et supprimant le `!` devant), l'URL est faussée et mène vers rien.

**Comment by firm1** [comment]
Ah ok, c'est plus compréhensible.

**Comment by firm1** [comment]
> Assigned #731 https://github.com/zestedesavoir/zds-site/issues/731 to @
> https://github.com/firm1firm1 https://github.com/firm1.

Pourquoi l'assigner ici ? Je ne m'en occupe pas. Il faudrait la laisser
vide pour que quelqu'un d'autre la prenne.
Le 3 sept. 2014 21:55, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
Parce que pour l'instant c'est toi qui t'en charge au niveau de l'import. C'est un peu compliqué d'exprimer "il y a quelqu'un partiellement sur le coup", mais du coup pourquoi pas laisser vide. C'est pas faux.

**Comment by Eskimon** [comment]
Hop, l'import est fait !

**Comment by gustavi** [comment]
Humm, un oubli ?

**Comment by Eskimon** [comment]
Je ferme ici et cree des tickets individuels pour les problèmes restants.
