### ISSUE TITLE
Textes explosés (avec des "u" au milieu)

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#732]
Suite au passage des outils de PEP-8 automatique (cf #574), on a plein de textes avec des "u" parasites qui trainent en plein milieu.

Ce n'est pas compliqué, mais ça implique de repasser sur **tous** les fichiers.

A priori ça ne peut arriver que dans les fichier .py

**Comment by Alex-D** [comment]
Y a peut-être moyen d'automatiser la chose ?

**Comment by Eskimon** [comment]
J'avais commencé à regarder, c'est un peu chiant à faire à la main mais pas impossible... Je pourrais continuer dessus si besoin...

**Comment by Alex-D** [comment]
A la limite : repasser pour l'orthographe en même temps (il peut rester des coquilles).

**Comment by Eskimon** [comment]
yep !

Qllez hop, jme l'assigne !

**Comment by Alex-D** [comment]
N'hésite pas à linker tes commits à cette issue, comme ça on fait une review au fur et à mesure :)

**Comment by Eskimon** [comment]
Mergé, on ferme ?

**Comment by Alex-D** [comment]
Yep ! Merci @Eskimon :)
