### ISSUE TITLE
Forum > Citer un message : perte de contexte

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#733]
Quand sur le forum, je fais "Citer un message", je me retrouve dans une page avec seulement "Répondre au sujet Bidule" pour titre et le formulaire de rédaction du message. Je ne vois plus les autres messages du topic.

Ceci est assez désagréable, parce qu'on perds tout le contexte autre que le message qu'on vient de citer.

Je vois deux solutions possibles à ce problème :
1. Afficher la citation dans le formulaire en bas de page du topic (celui qui est là "de base").
2. Conserver cette page, mais y afficher les X derniers messages du topic.

**Comment by Alex-D** [comment]
> Afficher la citation dans le formulaire en bas de page du topic (celui qui est là "de base").

Nécessite du JS, donc prévu mais pas pour tout de suite (cf #454)

> Conserver cette page, mais y afficher les X derniers messages du topic.

Au dessus ou en dessous le formulaire ? Il me semble que la version dev d'avant le faisait, tu pourrais me confirmer que le back envoi bien ce qu'il faut ?

**Comment by firm1** [comment]
La version d'avant le faisait déjà.
Le 4 juin 2014 21:22, "Alexandre Demode" notifications@github.com a écrit
:

**Comment by Alex-D** [comment]
> La version d'avant le faisait déjà.

Impec ! Je rajoute ça dans une des prochaines PR

**Comment by firm1** [comment]
Fx'd
