### ISSUE TITLE
Régression/Front : impossible d'ignorer un sujet suivi.

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#734]
Sous Firefox / Windows 7, on ne peut pas ignorer un sujet suivi.

En fait, on ne peut pas _cliquer sur la croix_ qui permet d'ignorer un sujet suivi : elle disparaît dès que la souris quitte le menu de gauche à proprement parler et donc arrive sur la fameuse croix.

**Comment by Alex-D** [comment]
Ah c'est gênant ça... Sur Chrome ça fonctionne, ça doit être une histoire de "pixel perfect"

**Comment by Alex-D** [comment]
Ce doit être corrigé, réouvre si ça n'est pas le cas.
