### ISSUE TITLE
Régression : impossible de créer un nouveau sujet depuis un sujet

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#735]
Dans chaque sujet, le premier item du menu de gauche est "Nouveau sujet".

Si je clique sur ce lien, il me renvoie vers cette URL : http://zestedesavoir.com/forums/sujet/nouveau/?forum=

Bien évidemment elle n'a aucune chance de fonctionner.

**Comment by Alex-D** [comment]
C'est normalement corrigé :)
