### ISSUE TITLE
Recherche automatique lorsqu'on crée un sujet

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#736]
Lorsqu'on crée un sujet, il y avait une fonctionnalité très intéressante qui permettait de trouver plus ou moins automatiquement les sujets résolus qui correspondaient à ce qu'on avait mis dans le titre.

Je ne sais plus exactement comment ça fonctionnait, mais je suis presque sûr de l'avoir vu marcher sur la prod. Aujourd'hui, plus rien.

**Comment by Alex-D** [comment]
C'est du front (JS) et le back (quand je l'ai testé il y a quelques jours) ne répondait rien, du coup je n'ai pas pu l'implémenter.

Je regarde ça prochainement et remonte le soucis si le back est toujours KO.

**Comment by Eskimon** [comment]
C'est certains ca marchait sur la vieille version, mais il y a eu un moment un composant responsable de cela (solr il me semble) a cessé de fonctionner ce qui rendait la fonction inexistante (@firm1 doit pouvoir confirmer)

**Comment by Alex-D** [comment]
Ah ok, si c'est dépendant de solr ça doit fonctionner du coup je vais pouvoir le réintégrer dans les prochaines PR :)

**Comment by Eskimon** [comment]
Je crois que c'est lié à cette PR (qui porte mal son nom) : https://github.com/zestedesavoir/zds-site/commit/3f58362b1dd7b7c5e76872492d8a8bd1eb1063c1

**Comment by Alex-D** [comment]
En effet, merci :)

**Comment by Eskimon** [comment]
@Alex-D tu crois que ca pourrait monter en priorité sur ta liste si c'est pas trop chaud a faire ? Ca pourrait être pratique pour limiter les doublons de rapport de bug pendant la beta :D

**Comment by Alex-D** [comment]
Ouep. Mais là je me concentre sur le bugfix. J'ajouterais la fonctionnalité ce soir :)

**Comment by Eskimon** [comment]
Ah bah j'avais prévenu, c'est que si tu as du temps :D Pas sur que ce soir tu sois plus pépère (sauf si tout le monde par en JZdS :D )

**Comment by ArnaudCalmettes** [comment]
Pas d'urgence. C'est vrai que c'est pratique, mais ça reste du Post-V1 à mes yeux (ça fera une très jolie nouvelle feature à annoncer après la sortie).

**Comment by SpaceFox** [comment]
C'est facile à remettre en place ce truc ? Parce que dans le genre "fonctionnalité qui tue", ça se pose là, et ça a fonctionné !

**Comment by Alex-D** [comment]
Faut remettre un bout de JS et surtout faire le design fluide qui va bien. C'est pas ultra compliqué en soit. Normalement le code back est toujours présent et fonctionnel.

**Comment by ghost** [comment]
Le code back est où ?

**Comment by Eskimon** [comment]
planque au fin fond des versions... je regarde

**Comment by Eskimon** [comment]
Voila, tout est la... https://github.com/zestedesavoir/zds-site/pull/580 (on constatera la difference de style avec les PR de l'epoque :D )

**Comment by ghost** [comment]
Merci, je prends.

**Comment by ghost** [comment]
![Imgur](http://i.imgur.com/TzvvdOJ.png)

J'améliore ça comment ?

**Comment by Eskimon** [comment]
Han, je souhaite élire A-312 comme "brute du debut de la semaine" avec toutes ses PR :D

Je me rappel plus comment c’était avant, mais voici deux choses qui me plairaient maintenant:
- "Sujets **résolu** similaire au votre"
- Mettre la liste sous le sous-titre, sinon ca perd une certaine "unité"

**Comment by ghost** [comment]
Il faudrait tester en preprod le retour de solr.

Je profiterai de ma PR pour supprimer ce fichier : 
- https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/find-solved-topics.js

**Comment by ghost** [comment]
Solr fonctionne bien sous windows, je finis ça se WE.

**Comment by SpaceFox** [comment]
Quelqu'un motivé pour reprendre ici ?

**Comment by GerardPaligot** [comment]
L'API des forums, ça serait cool avant de développer cette issue.

**Comment by pierre-24** [comment]
Ce serait même plutôt un pré-recquis obligatoire :)

**Comment by SpaceFox** [comment]
Comment ça a pu déjà fonctionner alors ?

**Comment by pierre-24** [comment]
Ben ... Y'a moyen autrement (faire des requêtes directement en BDD). Je trouve juste que ce serait plus simple à dévelloper avec l'API des forums :)

**Comment by SpaceFox** [comment]
OK, ça marche.

**Comment by artragis** [comment]
du coup on peut enlever le tag "régression" pour un truc qui date ... d'avant la v1?

**Comment by firm1** [comment]
Pour info ça marchait avant via l'api REST de solr qui indexe les sujets.
Donc l'API des forums n'est pas forcément  nécessaire  ici (et j'ai même
envie de dire qu'elle n'est pas souhaitable pour notre besoin)

**Comment by artragis** [comment]
Eh voilà merci @AmarOk1412

**Comment by GerardPaligot** [comment]
Trop bien ! Merci @AmarOk1412 !!
