### ISSUE TITLE
Impossible de lire les MP avec 1 seul message

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#737]
Les titres des MP dans [la liste des MPs](http://zestedesavoir.com/mp/) n'ont pas de lien vers le MP.
Le seul lien disponible est celui qui dit "Dernière réponse..." ... ce qui fait que quand le MP n'a qu'un seul message, on a aucun moyen d'aller le lire !

**Comment by Alex-D** [comment]
Etrange :/ Ajouté à ma todo !

**Comment by Alex-D** [comment]
Corrigé :)

**Comment by PtiLuky** [comment]
Moins important, mais il manque un accent ligne 92 : "apprêtez"
