### ISSUE TITLE
Détection de pseudo dans l'envoi de MP trop souple

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#738]
Comme dit dans l'issue #370, on a pas encore d'auto-complétion dans le champ "participants" des MP.

Donc aujourd'hui, ce champ permet de rentrer ce qu'on veut à la main.

Le problème est que la détection de membre est trop souple : elle accepte des correspondances non exactes.
Par exemple, si je tape `kjé`, mon MP est bien envoyé à `Kje`, ce qui n'est pas le comportement attendu.

Que se passe-t-il en cas de quasi-homonymes (imaginons qu'ici j'aie _aussi_ des membres nommés `kjé`, `kje` et `Kjé`) ?

**Comment by Alex-D** [comment]
Mon avis la dessus est que les homonymes doivent être proscris.

La souplesse est souhaitable à ce niveau à mon sens.

**Comment by Eskimon** [comment]
Je link la bas ca peut etre utile : https://github.com/zestedesavoir/zds-site/issues/862

**Comment by ArnaudCalmettes** [comment]
Mon avis c'est qu'il doit être possible de lister tous les pseudos correspondants, même avec cette reconnaissance souple, et que l'utilisateur doit pouvoir cliquer pour choisir à qui il veut effectivement envoyer son MP.

De cette façon, on reste indépendant de la politique de restriction des pseudos ou autre.

Conclusion, c'est une évolution et ça passe en v1.x

**Comment by Alex-D** [comment]
Du coup, c'est au back de changer un poil sa requête et de la rendre tolérante à la casse et aux accents. Le front resterait donc inchangé.

**Comment by Eskimon** [comment]
Ca serait cool si @sandhose passait regarder, vu que l'autocomplete c'est son bébé je crois... perso j'ai essayé mais je suis pas sur de bien avoir saisi comment il choppait les pseudo

**Comment by Alex-D** [comment]
C'est une requête vers le serveur, donc c'est le back qui répond par rapport à ce que l'utilisateur a saisi.

**Comment by Eskimon** [comment]
Ouai mais la seule requete que j'ai trouvé c'est ca : https://github.com/zestedesavoir/zds-site/blob/24161830d639169c7092c83e7f75d20c0c5f1ba9/assets/js/autocompletion.js#L278 et ca me parait mysterieux...

**Comment by Alex-D** [comment]
Sachant que c'est envoyé avec des headers XHR, c'est possible que ce soit testé côté back pour ne répondre que dans ce cas là.

**Comment by Eskimon** [comment]
Corrigé -> Mergé :)

**Comment by Eskimon** [comment]
Arf j'ai ptet fermé un peu vite... J'ai pas vérifié aves des accents...
