### ISSUE TITLE
Impossible de créer un article avec la catégorie "zds"

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#74]
La création d'un article de catégorie "zds" est impossible. Lorsqu'on choisit "zds" comme catégorie, on obtient l'erreur suivante :

insert or update on table "article_article_subcategory" violates foreign key constraint "subcategory_id_refs_id_173b0194"
DETAIL:  Key (subcategory_id)=(0) is not present in table "utils_subcategory".

J'ai testé avec quelques autres catégories, le problème ne se présentait pas.

**Comment by firm1** [comment]
Le bug est désormais fixé, je ferme
