### ISSUE TITLE
Liste des MPs, offset

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#743]
Dans la liste des MP (a partir du bouton du header) il y a un offset qui fait qu'on voit les messages à partir du 2nd messages...
En gros si dans ma boite j'ai les messages:
- A
- B
- C
- D

...dans la liste qui apparaît sur le bouton j'aurais
- B
- C
- D

Donc offset de 1 index

**Comment by Alex-D** [comment]
Tu pourrais dire quel est l'état de chacun des MP, s'il te plait ? (Lu, non-lu)

**Comment by Eskimon** [comment]
Tous lu !

**Comment by Alex-D** [comment]
Il doit y avoir un soucis avec la variable : `read_topics` issue du filtre `interventions_privatetopics`

**Comment by Alex-D** [comment]
C'est étrange car je n'ai pas le soucis (j'ai fait quelques tests pour voir, suite au correctif des MPs en MD).

**Comment by Eskimon** [comment]
Voila une capture d'ecran qui illustre le truc...
Dans la liste, le MP de Kje n'apparait pas...

![screenshot from 2014-06-05 11 07 24](https://cloud.githubusercontent.com/assets/761168/3185303/a2eb50b8-ec91-11e3-81a3-4bc306366e48.png)

**Comment by Alex-D** [comment]
Clairement un bug de back, je vous laisse corriger ça mon cher @Eskimon (ou quelqu'un d'autre)

**Comment by cgabard** [comment]
Je pense que c'est plus général que ça. Moi j'ai plusieurs Mp qui n'ont pas d'alertes correspondantes

**Comment by Eskimon** [comment]
Ou alors c'est juste que comme Kristo c'est un fantome bah c'est normal on le voit pas :ninja: :D

**Comment by Eskimon** [comment]
Est-ce que quelqu'un d'autres à un souci similaire ou c'est juste un bug qui s'est faufilé entre deux migrations (qui le rendrait donc caduque) ?

**Comment by firm1** [comment]
J'ai le même souci.

**Comment by sandhose** [comment]
![image](https://cloud.githubusercontent.com/assets/1549952/3220680/1dbe7062-f003-11e3-95f1-e4980115d544.png)
Je sais pas si c'est lié, mais il semblerait que d'après cette liste, je m'envoie des MP à moi même... x)

En plus, le MP de bienvenue devrait être en dernier, or la, il est en 2e dans ma liste...

**Comment by Eskimon** [comment]
Bon j'ai pu le bug depuis que j'ai des MPs recents qui ont dépassé celui qui voulait pas s'afficher... (est-ce possible que ce soit un probleme juste du a ce MP ?)

**Comment by Alex-D** [comment]
> Je sais pas si c'est lié, mais il semblerait que d'après cette liste, je m'envoie des MP à moi même... x)

Non, c'est l'auteur du dernier message qui s'affiche, c'est pas super logique, en effet.

Faudrait qu'on revoit un peu cette dropdown là je pense.

**Comment by Eskimon** [comment]
Etant donnée qu'ont ne voit plus les derniers messages mais qu'on a juste "Pas de nouveaux messages" d'affichés, est-ce encore pertinent de garder cette issue ?

**Comment by Alex-D** [comment]
Bah le bug est "corrigé" en quelques sortes. Du coup, ça n'a plus d'intérêt selon moi.
