### ISSUE TITLE
Combiner et minifier les JS custom

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#747]
Aujourd'hui dans le dossier "custom", on a pas moins de 16 fichiers JS différents :
1. accessibility-links.js
2. accordeon.js
3. close-alert-box.js
4. data-click.js
5. dropdown-menu.js
6. editor.js
7. find-solved-topics.js
8. karma-ajax.js
9. keyboard-navigation.js
10. markdown-help.js
11. message-hidden.js
12. mobile-menu.js
13. modal.js
14. select-autosubmit.js
15. spoiler.js
16. toggle-hidden-messages.js

Certains sont même tellement cours qu'ils contiennent plus de commentaires que de code.

Sur la home, avec les différents JS externes, on en arrive à télécharger 31 fichiers JS différents !
Il est donc indispensable de combiner tout ça et d'avoir une moulinette pour sortir une version minifiée du fichier commun.

Pour moi c'est d'autant plus incompréhensible qu'on parlait déjà de [combiner les fichiers Mathjax](https://github.com/zestedesavoir/zds-site/issues/402#issuecomment-42074596).

**Comment by Alex-D** [comment]
C'est "déjà fait" en fait, c'est juste que Pipeline ne doit pas être activé sur la prod. Je ne sais pas si c'est voulu ou pas. Mais en gros, c'est une variable de prod à changer ou un truc du genre.

La répartition est voulue et faite pour mieux s'y retrouver plutôt que d'avoir un fichier énorme (je trouve ça plus pratique pour avoir déjà expérimenter les deux).

**Comment by SpaceFox** [comment]
Tous mes tests sont fait du point de vue utilisateur.

Le constat est qu'ajourd'hui, en FO, on télécharge des tonnes de JS. Si la
technique pour avoir 1 JS minifié prends 2 lignes de conf, tant mieux :)

**Comment by Alex-D** [comment]
Juste que je ne sais pas paramétrer Pipeline pour ça, mais de mon côté j'ai tout configuré avec Pipeline (j'ai pas mis les fichier un par un dans le HTML en dur).

**Comment by firm1** [comment]
Fi'xd
