### ISSUE TITLE
Régression : les cases à cocher sont inutilisables

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#748]
Sous Chrome / Windows 7, les cases à cocher sont remplacées par un carré gris ou blanc, sans qu'on sache ce qui corresponde à "cocher" ou "décocher" dans l'histoire. Autrement dit, les cases à cocher sont à peu près inutilisables.

Ce bug n'était pas visible sous Firefox, qui a la bonne idée d'interdire les modifications de style sur ces cases à cocher.

Même remarque avec les radio boutons.

**Comment by Alex-D** [comment]
C'est déjà corrigé dans la PR #741 et son commit https://github.com/zestedesavoir/zds-site/commit/a7a9b2d2253f0cb8dd651421fa72372e5d4c3f38

Faut juste que ça soit poussé en prod, on ne m'as pas indiqué comment le faire, donc je ne peux pas le faire :)

**Comment by firm1** [comment]
Je confirme, c'est corrigé.
