### ISSUE TITLE
Edition d'article : message d'erreur de formulaire sur le choix de catégorie

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#75]
Lorsqu'on édite un article existant, le champ de choix de la catégorie est mis en rouge avec le message "Saisissez une liste de valeurs.", comme s'il avait été oublié.

**Comment by Coy0te** [comment]
A priori, c'est pareil pour les tutos. 
Et toujours a priori, ça ne marche pas si on choisit une catégorie dans la liste avant de sauvegarder l'édition, y'a une erreur python à la clef.

**Comment by GerardPaligot** [comment]
Vous pouvez me fournir l'erreur ? Je n'arrive pas à reproduire le bug chez moi. Quand j'édite la catégorie d'un article, il l'édite bien et ne me fait aucune erreur.

**Comment by firm1** [comment]
Je l'avais déjà corrigé dans un commit cette erreur.

Par contre, je n'ai pas fermé cette issue, parce que le champ restait toujours en rouge lors de l'édition. Mais ça c'était surtout un defaut de la lib crispy-foundation qui devrait se résoudre automatiquement avec le nouveau design.

**Comment by GerardPaligot** [comment]
Ok. Je ne vois aucun encadré rouge sur la branche dev par contre. Cette issue est donc résolue ?

**Comment by firm1** [comment]
Non mais le rouge du le verras surtout quand le design front-end sera fait
sur les formulaire. Car si tu analyse bien le code HTML, tu verras que le
champ catégorie est censé être affiché en mode alerte.

**Comment by GerardPaligot** [comment]
Le formulaire est géré entièrement par crispy. Donc l'HTML est géré dans article/forms.py. Pour les catégories, il y a :

```
subcategory = forms.ModelMultipleChoiceField(
    label = "Sous catégories de votre article",
    queryset = SubCategory.objects.all(),
    required = False
)
```

A mon sens, comme le champ n'est pas `required` (ce que je trouve déjà bizarre), il n'est pas censé être mis en alerte.

**Comment by firm1** [comment]
> n'est pas required (ce que je trouve déjà bizarre)

Le champ n'est pas required au même titre que la licence, étant donné que
tu peux créer un tuto sans forcément savoir ou tu veux le ranger.

> il n'est pas censé être mis en alerte.

Bah justement, le BUG est là. Il n'est pas censé, sauf qu'il est mis en
alerte. Il suffit d'analyser le HTML généré quand tu édite ton tuto/article
pour voir que le champ est labellisé en error.

**Comment by GerardPaligot** [comment]
J'ai une piste, je me charge de ce bug.

**Comment by GerardPaligot** [comment]
Le bug vient du gestionnaire de formulaires crispy. Un bug fixe (#179) a été apporté mais il est temporaire le temps que crispy règle le problème. Je ferme cette issue.
