### ISSUE TITLE
[Markdown] Sauts de lignes dans les alignements

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#76]
Actuellement les balises d'alignements ne sont possibles qu'un l'intérieur d'un même bloc. La possibilité d'avoir des lignes vides serait vraiment utile.

**Comment by cgabard** [comment]
A un petit bug identifié pret, j'ai une version locale qui fonctionne. Cela n'a été possible qu'en supposant que des alignements ne pouvaient être imbriqués.

**Comment by Coy0te** [comment]
Dans le cas d'alignements imbriqués, ça se passe comment, un seul alignement est interprété ?

**Comment by firm1** [comment]
En cas d'alignement imbriqué, je pense qu'il faudrait interpréter les deux et le html se chargera de s'afficher comme il faut.

**Comment by cgabard** [comment]
Tout dépend en fait. Si tu fais un centré dans un centré : 

```
->
a
->
b
<-
c
<-
```

Il va prendre les deux premieres fleches pour un alignement à droite. Les deux dernières seront recopiées tel quel dans la sortie.

etc.

**Comment by cgabard** [comment]
Bon le bug est corrigé en local.

**Comment by Coy0te** [comment]
Je viens de faire un test, en fait y'a **énormément** de tutos dans lesquels y'a des alignements imbriqués, les auteurs ont fait n'importe quoi.

Pour info, mon parseur ne traite pas les nœuds identiques imbriqués, à part pour les listes et les citations. En clair, une balise `<position>` qui elle-même est dans une balise `<position>` restera telle quelle dans le cours après passage du parseur.  Eh bien sur les 500+ tutos que j'ai en local, après conversion en markdown, il reste... 1972 occurrences de la balise, dans 30 tutos différents. 

Du coup, qu'est-ce que je fais : 
- je vire toutes les balises position qui sont filles d'une balise position ?
- ou je convertis toutes les balises position en md récursivement ?

Sachant que la seconde option rendra mal avec notre syntaxe md, je suis partant pour la première.

**Comment by SpaceFox** [comment]
Mon opinion personnelle sur la question, c'est que modifier l'alignement
n'a pas d'intérêt, donc qu'on peut le dégager :)

**Comment by cgabard** [comment]
De manière pragmatique : 
- Notre syntaxe ne supporte pas les alignements imbriqués
- Il y en a dans les tutos qu'on importe

donc deux solutions : 
- On change la syntaxe des alignements pour le permettre
- On vire les alignements imbriqués à l'import.

En fait la grande question est de savoir si il y a un interet a avoir des alignements imbriqués

**Comment by Coy0te** [comment]
Aucun intérêt. 

Perso, je serai presque d'avis de ne garder que les alignements centrés. L'alignement à droite, j'ai encore jamais vu un cas où c'est susceptible d'être utile et où ça rend bien.

**Comment by SpaceFox** [comment]
Question : existe-t-il des balises alignement utilisées pour gérer autre
chose que l'alignement des images ?
Parce qu'il me semble qu'on a dit que les images seules étaient
automatiquement centrées, et qu'on ne supportait plus les images flottantes.

Si c'est bien le cas, je pense qu'on peut tout simplement se passer
d'alignement.

Le 17 janvier 2014 11:20, Christophe Gabard notifications@github.com a
écrit :

**Comment by Coy0te** [comment]
C'est vrai que nos tableaux seront centrés, nos images aussi, nos vidéos aussi, les légendes qui vont avec aussi, nos balises de maths aussi... En fait je suis du même avis que SpaceFox, les alignements ne servent à rien.

**Comment by cgabard** [comment]
En fait une image isolé se voit transformé en figure avec caption. Du coup c'est au CSS de l'aligné. 

On peut d'ailleurs appliquer ce meme genre de raisonnements ailleurs. 

Il est vrai que les alignements n'ont aucun sens semantique.

**Comment by cgabard** [comment]
Comme vous voulez. Si quelqu'un voit un interet aux alignements autre qu'automatique géré par le CSS, qu'il le dise maintenant ou je vire les alignements dans la prochaine PR.

**Comment by firm1** [comment]
Autant dans le zcode l'alignement est utilisé pour les images. Autant si je veux aligner un texte (en mode poème centré) j'aurais besoin de ces balises.

**Comment by cgabard** [comment]
A la grande époque des debrief des JSDZ on utilisait l'alignement à droite pour y caller la bande son aussi

**Comment by Coy0te** [comment]
Du coup, je les vire du zCode à la conversion, mais on garde tout de même la syntaxe dans notre md ?

**Comment by SpaceFox** [comment]
Ça me paraît être la meilleure solution.

**Comment by firm1** [comment]
> Du coup, je les vire du zCode à la conversion, mais on garde tout de même la syntaxe dans notre md ?

+1

**Comment by cgabard** [comment]
Il me semble que c'est en prod, je ferme :)

**Comment by firm1** [comment]
Je me permets de réouvrir cette issue.

On a un petit problème d'[interprétation du contenu à l'intérieur des balise de centrage](http://zestedesavoir.com/tutoriels/10/les-maths-pour-tous/).

**Comment by cgabard** [comment]
Grrr.. Le tableau est correctement parsé si il n'y a pas de centrage ?

**Comment by cgabard** [comment]
Alors 2 commentaires.

1- Le tableau source est foireux, il ne fait pas la bonne taille.
2- Sur le forum c'est bien centré, meme avec ton tableau foireux (qui n'est du coup pas transformé) : http://zestedesavoir.com/forums/sujet/7/rediger-sur-zds?page=1#p64 (premier test avec centrage)

**Comment by cgabard** [comment]
Pourquoi le rendu dans l'article n'est pas le même, mystere

**Comment by cgabard** [comment]
Quand je recopie le début du tuto, il passe bien. Tu n'aurait pas un html en cache ?

**Comment by firm1** [comment]
Ah ouais désolé c'est ma faute. J'avais complètement zappé que pour les versions online, c'est le HTML des tutos qui est lu. 

Et vu que le HTML est généré a la validation du tuto, il fait refaire valider les tutos pour que le HTML soit régénéré.

Tu peux donc fermer l'issue.

**Comment by cgabard** [comment]
> Ah ouais désolé c'est ma faute. J'avais complètement zappé que pour les versions online, c'est le HTML des tutos qui est lu. 

Comment ce fait il que sur le bug des legendes précédent, le parseur python-markdown était tout de même appelé ? (puisqu'il faisait planter le serveur)

**Comment by firm1** [comment]
Ça faisait planté le forum pas les tutsi justement

**Comment by cgabard** [comment]
Ha ok

**Comment by Coy0te** [comment]
Ça plantait aussi pour la version offline des tutos, qui elle ne fait pas appel au cache.

Et en effet, ça ne plante plus maintenant, nickel.
