### ISSUE TITLE
Les "touches" n'on aucuns rendu

### ISSUE THREAD

**Issue by geoffreyc** [zestedesavoir/zds-site#764]
Comme on peut le voir dans le guide de  ShigeruM, le rendu du code de "touches" markdown n'a plus aucun rendu (si ce n'est qu'un changement de font). Il faudrait revenir a l'ancien rendu, qui lui ressemblait a des touches de clavier.

**Comment by Alex-D** [comment]
+1 j'ai vu ça hier également, je corrige ça sous peu.

**Comment by sandhose** [comment]
Fix'd, à fermer
