### ISSUE TITLE
Zen mode version mobile

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#765]
Le bouton zen mode de la version mobile ne fait rien. Il faudrait qu'il fasse son job ou au moins qu'il soit masqué.

Je sais que c'est loin d'être le seul problème sur mobile, mais c'en est un donc je le signal.

**Comment by Alex-D** [comment]
Ah, je pensais l'avoir retiré sur mobile mais j'ai oublié.

Le zen mode ne fait pas sens sur mobile de toute façon, à retirer.

**Comment by sandhose** [comment]
Corrigé! Plus qu'a merge #769

**Comment by Alex-D** [comment]
Validé :)

**Comment by Alex-D** [comment]
Je réouvre, Le bouton n'est pas visible alors que je rentre dans le cas de _wide.scss ... je n'ai pas ce qu'il faut pour corriger les assets sur la machine actuelle, si tu peux corriger ça @sandhose :)

En fait, le display block est pas au bon endroit ici : https://github.com/sandhose/zds-site/blob/f7389b3e7fab77ec78fe365dbb42764fc1eec196/assets/css/scss/_wide.scss#L244

Il est imbriqué dans &.zen-mode qui signifie que le zen-mode est **actif** du coup, quand il n'est pas actif le bouton ne s'affiche pas.

Faut sortir le display block de &.zen-mode (le mettre juste au dessus serait bien :))

**Comment by sandhose** [comment]
Effectivement, je vais corriger ca!

Par contre, j'ai vu que ce mode pourrait s'appliquer également aux tablettes, car le header et la navigations sont visibles...

**Comment by Alex-D** [comment]
Quelle navigation ? Sur tablette normalement, tu scroll à peine que tu vois plus le header et donc Zen mode ou pas, t'arrive au même résultat.

Le truc, c'est que sur ordi, pour quitter ce Zen mode, suffit de presser `Echap` alors que supports tactiles c'est plus compliqué de faire ça, du coup je ne préfère pas le mettre.

**Comment by firm1** [comment]
Je ne sais pas ce qui s'est passé, mais le Zen mode à quitté la prod

**Comment by Alex-D** [comment]
@firm1 : https://github.com/zestedesavoir/zds-site/issues/765#issuecomment-45218620

**Comment by Alex-D** [comment]
Fixé dans la #791. A fermer dès que c'est en prod et vérifé.

**Comment by Alex-D** [comment]
Vérifié et fonctionnel !

**Comment by firm1** [comment]
Bon, j'ouvre encore cette issue parce que je viens de tomber sur le bouton Zen Mode dans la page contact en mode PC.

Je me demande ce qu'il fait là.

**Comment by Alex-D** [comment]
C'est une page de contenu, du coup le bouton est présent.

Par contre ça s'affiche pas au bon endroit pour le coup... Faudrait l'afficher que sur les tutos/articles tu crois ?

**Comment by ShigeruM** [comment]
Oui à mon avis le zen mode ne doit être présent que pour les articles et
tutoriels.
Le 9 juin 2014 15:04, "Alexandre Demode" notifications@github.com a écrit
:

**Comment by Alex-D** [comment]
A tester en prod, ça ne mets plus le bouton que sur les pages qui en ont besoin :)

**Comment by Eskimon** [comment]
Je confirme tout roule !
