### ISSUE TITLE
Voir les diffs des différentes version d'un tuto

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#766]
Exemple : http://zestedesavoir.com/articles/historique/1/rediger-sur-zds/

Avant on pouvait voir les diffs des différentes versions des tutos/articles, maintenant on ne peut plus.

**Comment by Alex-D** [comment]
Il manque "juste" un lien sur le n° du commit c'est ça ?

**Comment by cgabard** [comment]
Perso je reouvrirai bien car me rendu est inutilisable. C'est très large et je n'ai même pas d'ascenseur horizontale. En gros ça ne sert a rien

**Comment by Alex-D** [comment]
On me donne un tableau ligne par ligne, c'est le bazar un peu comme truc à intégrer.

C'est pas prioritaire qui plus est.

Je réouvre mais c'est clairement pas pour tout de suite.

**Comment by Fumble** [comment]
Je remonte ce bug. Le diff est en effet décalé sur la droite et le tableau dépasse de l'écran de façon très importante. Il doit manquer au moins la moitié de la ligne si ce n'est plus.
OS: Windows 7 SP1 64 bits
Navigateur: Firefox 30

**Comment by Alex-D** [comment]
C'est connu, il n'y a juste aucun design. Ca viendra quand on aura du temps à y consacrer, le soucis c'est que c'est livré dans un tableau et qu'on doit se débrouiller pour que ça n'est pas l'air d'un tableau mais bien d'un diff ^^

**Comment by cgabard** [comment]
Bah techniquement les blocs de code sont comme ça aussi, avec des tableaux.
Je pense que c'est pour assurer le bon alignement et rajouter les infos sur
chaque ligne.

Après de mémoire c'est un truc fait rapidement depuis la lib standard, il y
a peut etre moyen de paramétrer la génération du diff. Faut creuser cette
page : https://docs.python.org/2/library/difflib.html
Le 15 juil. 2014 23:53, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by firm1** [comment]
ça c'est fait.
