### ISSUE TITLE
MP contenu non visible

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#767]
Lorsque l'on envoi un MP, le contenu n'est pas visible.
Je suppose que c'est une histoire de template et que ca sera regle en deux temps trois mouvements :D 

Une illustration pour voir le probleme:

![screenshot from 2014-06-05 09 52 43](https://cloud.githubusercontent.com/assets/761168/3184816/744d09ba-ec8a-11e3-8753-3dfc21065e8a.png)

**Comment by Alex-D** [comment]
Nop, c'est une histoire de back et c'est corrigé dans la PR : #763

J'suis allé dormir en pensant que les tests seraient passés ce matin mais ça a crash pendant l'installation souvent...

**Comment by Eskimon** [comment]
Ca fait des situations cocasses :D

![screenshot from 2014-06-05 10 48 31](https://cloud.githubusercontent.com/assets/761168/3185067/471f1358-ec8e-11e3-9695-8e5c6bbe3213.png)

**Comment by Alex-D** [comment]
L'idéal ça serait de vider les MPs après le merge.

**Comment by cgabard** [comment]
> L'idéal ça serait de vider les MPs après le merge.

Une seule fois ou systématiquement ?

**Comment by Alex-D** [comment]
Une seule fois. En gros là une fois mon correctif poussé en prod tous les MP qui datent d'avant ce correctif afficheront un message pour dire que le message date d'avant la correction (cf le fichier de migration).

Du coup, normalement c'est corrige :)

**Comment by cgabard** [comment]
Actuellement j'ai plein de MP vide, tant que ce n'est pas corrigé, aucune raison de fermer. Ne serait ce que pour éviter que quelqu'un le rapporte de nouveau

**Comment by Alex-D** [comment]
Ok d'ac, du coup si une bonne âme pouvait pousser ça en prod ça serait cool (faut pas oublier d'appliquer la migration).

**Comment by Alex-D** [comment]
En prod !

**Comment by Alex-D** [comment]
Juste pour prévenir : les anciens MP sont HS, il faut en créer de nouveaux pour que ça fonctionne.

**Comment by firm1** [comment]
> Juste pour prévenir : les anciens MP sont HS

Non, non, ça marche bien, j'ai tout réparé, suffit d'aller regarder vos MPS

**Comment by Alex-D** [comment]
Oh cool :)
