### ISSUE TITLE
Tutoriel perpetuellement en validation

### ISSUE THREAD

**Issue by Taluu** [zestedesavoir/zds-site#768]
Lorsqu'on a demandé une validation d'un tutoriel (exemple : mon tuto sur la RI), même si le tutoriel a été validé / accepté, il semble qu'il est toujours considéré "en validation", même s'il est en prod.

Du coup, si une modif est faite par la suite, on ne peut pas redemander une nouvelle validation...

**Comment by Alex-D** [comment]
Ca doit venir de mes conditions. Par contre lors de mes tests en local ça fonctionnait bien.

Tu pourrais me donner la procédure exacte suivie ? Car j'ai l'impression que le problème survient que dans certains cas.

**Comment by Taluu** [comment]
1. J'ai mis mon tutoriel en validation
2. J'ai validé le tutoriel en question (il est donc en ligne)
3. J'ai modifié deux trois trucs sur le tutoriel

Je peux pas redemander la validation, car il est "déjà en validation". Tout comme dans l'interface du staff, j'ai toujours le tuto dans la liste des tutoriels à valider (et qui m'est encore affecté du coup, vu que je l'avais reservé la première fois)

Je doute que ce soit vraiment lié au front ceci dit ?

**Comment by Alex-D** [comment]
S'il est publié, ça se peut que oui, car il y a pas mal "d'algo" dans les templates pour gérer ces affichages là.

Je vois ça très bientôt.

**Comment by SpaceFox** [comment]
Je t'avoue que la présence "d'algo" dans des templates a tendance à me
faire flipper, surtout s'il y en a "pas mal".

**Comment by Alex-D** [comment]
En ce sens où pour afficher les boutons y a pas mal de conditions, c'est pas du calcul, mais y a quelques tests quand même.

**Comment by Taluu** [comment]
J'ai l'impression que le bug s'est fixé de lui-même... Peut-être est-ce du au fait que j'ai du mettre le tuto en validation **avant** que @firm1 ait fini de bosser sur la prod ?

**Comment by Alex-D** [comment]
C'est possible... Bon du coup, c'est cool =D
