### ISSUE TITLE
[Markdown] Rendre grid_table moins sensible

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#77]
Actuellement les grid_table necessitent d'avoir des lignes vides avant et après le tableau pour être correctement parsé. 

Assouplir cette condition serait très pratique

**Comment by cgabard** [comment]
Corrigé en local

**Comment by Coy0te** [comment]
PR ! :)

**Comment by cgabard** [comment]
Ce soir !

**Comment by cgabard** [comment]
Il me semble que c'est en prod, je ferme :)

**Comment by firm1** [comment]
Je réouvre cette issue pour le problème suivant : 

Si j'essaye de saisir le tableau suivant, je fais planter le serveur (même bug qui fait planter [cette page par exemple](http://zestedesavoir.com/forums/sujet/5/bug-articles)).

```
+-----------------------------------------------------------------------------------------------------------------------+-------------+
|France France |6e |
+-----------------------------------------------------------------------------------------------------------------------+-------------+
|Belgique Belgique|6e primaire|
+-----------------------------------------------------------------------------------------------------------------------+-------------+
|Québec Québec |6e primaire|
+-----------------------------------------------------------------------------------------------------------------------+-------------+

Table:Equivalences des niveaux
```

Avec l'erreur : `global name 'legend' is not defined`

Le problème est dans [cette partie du code](https://github.com/Taluu/ZesteDeSavoir/blob/master/zds/utils/templatetags/mkd_ext/smartLegend.py#L197), ou la variable legend n'existe pas.

**Comment by Coy0te** [comment]
Je me demandais justement pourquoi j'arrivais pas à accéder en offline au tuto "Les maths pour tous"... J'ai ma réponse ^^

**Comment by cgabard** [comment]
J'étais pas réveillé hier...

Ok je vais te corriger ça. Le prob est que là a priori, il ne detecte pas que c'est une légende de tableau et ça ne va pas etre inséré comme caption du tableau (sinon il ne serait pas là).

Apres ma correction, essais de virer la ligne vide entre tableau et légende (même contrainte que pandoc, pas de lignes vides entre les deux)

**Comment by cgabard** [comment]
J'ai refais un patch à chaud...

**Comment by firm1** [comment]
Le patch à chaud m'[a l'air d'être assez refroidi](http://zestedesavoir.com/forums/sujet/5/bug-articles).

**Comment by cgabard** [comment]
Nouvelle tentative :p Là on devrait etre bon

**Comment by firm1** [comment]
[On est bon](http://zestedesavoir.com/forums/sujet/5/bug-articles).

Merci Docteur.

Je ferme.
