### ISSUE TITLE
Fiabilité Travis

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#770]
Travis a tendance à planter régulièrement pendant l'installation, ce qui nous prive de l’exécution des tests.

Exemples de tests échoués :

https://travis-ci.org/zestedesavoir/zds-site/builds/26814213
https://travis-ci.org/zestedesavoir/zds-site/builds/26812845
https://travis-ci.org/zestedesavoir/zds-site/builds/26809892
https://travis-ci.org/zestedesavoir/zds-site/builds/26808278

Je ne sais pas si c'est possible de lui dire que si ça plante, il faut relancer.

**Comment by cgabard** [comment]
Ce ne sont que des probs de connexions. Je ne suis pas surs qu'on puisse y faire grand chose. 3/4 concernent github qui ne semble pas répondre, l'autre c'est pip qui ne répond pas.

**Comment by Alex-D** [comment]
Oui je vois bien, mais ça n'est pas possible de lui demander de relancer en cas d'échec ?

**Comment by firm1** [comment]
> mais ça n'est pas possible de lui demander de relancer en cas d'échec ?

Non, il faut le relancer à la main via l'interface travis.
