### ISSUE TITLE
Utilisation d'un Task-runner pour le front

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#771]
## Proposition:

Utiliser un task-runner type [Grunt](http://gruntjs.com/)/[Gulp](http://gulpjs.com/) pour le front. Cela permettrait d'automatiser les tâche comme le build compass, les tests pour le front (s'il y en a un jour...), la vérification de la syntaxe ([JSHint](https://github.com/jshint/jshint/)), gérer les dépendances front correctement via [bower](http://bower.io) (et pas inclure les libs dans le répo...), et la minimification des fichiers JS pour la prod.
## Pourquoi ?

En bossant un peu sur le front, je me suis rendu compte que:
- Les fichiers compilés, et les fichiers sources se trouvaient au même endroit pour le front
- L'absence de tests, vérifications, et conventions de syntaxe pour le front (alors qu'il y a PEP-8 pour le back)
- Les fichiers compilés qui sont inclut dans le répo (c'est pas grave en soit, mais personnellement je préfère pas avoir des commits qui changent les sprites/le main.css, alors que ce ne sont que le résultat de la compilation compass...
- Les dépendances (jQuery, Modernizr, ...) sont incluses dans le répo, alors que cela n'as pas lieu d'être (enfin, c'est mon avis perso, et puis ça permettras par la suite de les mettre à jour, juste en modifiant la version dans le fichier de dépendances...)
## C'est compliqué ?

Je m'occupe de la configuration/mise en place. Le seul prérequis, est d'avoir _[NodeJS](http://nodejs.org/)_ d'installé (_>0.10_), avec _[Bower](http://bower.io)_ et _[Gulp](http://gulpjs.com/)_ (l'installation de ces derniers se résume à `[sudo] npm install -g bower gulp`)
Un fichier `package.json` contiendras toutes les dépendances de ces outils, et un fichier `Gulpfile.js` contiendra la configuration.
En gros, une fois que tout est installé, suffira de faire `gulp build:dev` pour générer une build de développement (donc non-minimifiée), et `gulp build:prod` pour générer une build pour la prod (minimifier, toussa toussa...)
J'ajouterais aussi des tâches type `gulp test`, qui vérifiera la syntaxe (_JSHint_) + éventuellement les tests (utile pour _Travis_), et `gulp watch` pour faire de la compilation à la volée pendant le développement.
## Et tout ca pour quoi ?

Au final, on aura un dossier `front/` (ou un autre nom), contenant toutes les ressources utiles, qui sera sur le répo, et un dossier `assets/`, qui sera crée dynamiquement par Gulp, et qui ne sera pas inclut dans le répo.

Je vais tout de suite m'y mettre, faire une PR, et vous me direz ce que vous en pensez

**Comment by cgabard** [comment]
+1

**Comment by Alex-D** [comment]
J'ai eu la flemme de le faire jusque là.

+1 pour Gulp.
+0.42 pour Bower (moins prioritaire)

Je ne sais pas si `front` est un bon nom par contre, `ressources` ou `statics`  serait plus adapté. Voire un sous dossier de assets genre `assets/prod/` pour les fichiers compilés, ce qui ne change pas la structure actuelle du coup.

> L'absence de tests, vérifications, et conventions de syntaxe pour le front

Ca va nécessiter de revoir un poil le code car il n'a pas encore été nettoyé à 100%.

## Par contre...

Il va falloir que tu mettes à jour la doc (le README) en conséquence pour Windows et Linux au minimum (comment installer les outils de gestions de deps, etc).

Merci d'avance et amuses toi bien :)

**Comment by Alex-D** [comment]
J'y pense : la concaténation des JS et CSS est faite par le back avec pipeline, du coup faut voir comment gérer ça (est-ce nécessaire ?).

Comme tu peux le voir, le JS est niquel pour la prod ici : http://zestedesavoir.com/static/js/main.js
Pareil pour le CSS ici : http://zestedesavoir.com/static/css/main.css

**Comment by sandhose** [comment]
En général perso j'utilise comme nom de dossier `app/` et `dist/`...

> J'y pense : la concaténation des JS et CSS est faite par le back avec pipeline, du coup faut voir comment gérer ça (est-ce nécessaire ?).

Je sais, et je proposais ça aussi pour justement bien séparer front et back... En soit, c'est pas hyper-utile, mais bon... En plus, actuellement, les fichiers JS sont définit dans `zds/settings.py`, ce qui est, à mon avis, pas leur place... La avec Gulp, on peut très bien choisir **tous** les fichiers JS du dossier (genre `assets/js/custom/*.js`)...

Je vais une fois voir de mon côté, et vous me direz ce que vous en pensez

**Comment by Alex-D** [comment]
Ah ouep, ça peut être vachement plus pratique de pas se coltiner de settings en effet :)
