### ISSUE TITLE
Ajouter une option "start numbering" dans les balises codes

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#78]
Permettre de faire commencer les listing à un numéro de ligne particulier nous permetrait d'être compatible avec le zcode à ce niveau

**Comment by cgabard** [comment]
Cette correction necessite obligatoire de modifier le code de python-markdown. Je tenterais une pull request sur le projet la concernant, sinon nous continuerons d'utiliser une version depuis les sources avec application d'un patch.

J'attend de voir l'avancement de la premiere PR avant d'en soumettre une nouvelle

**Comment by Coy0te** [comment]
Une idée de la syntaxe md adoptée ?

**Comment by cgabard** [comment]
Vu que pour mettre en evidence les lignes, le nom de pygment a été utilisé, je pense faire pareil : 
    ```python linenostart=1

**Comment by firm1** [comment]
En fait, je ne comprend pas vraiment cette fonctionnalité. Elle est censé permettre quoi ? je veux dire, afficher quoi ?

**Comment by cgabard** [comment]
Permettre que tes listings commencent la numérotation à la ligne 10 par exemple au lieu du 1

**Comment by Coy0te** [comment]
Ça fait trois fois que tu nous poses la question ! :D

**Comment by firm1** [comment]
xD , j'essaye de comprendre. C'est pas évident avec toutes ses issues (et vos explications en deux lignes :P ).

En gros, ça veut dire que si tu écris le code suivant : 

``` python
ageDeEricPraline      = 50
ageDeHenryWensleydale   = 20

# Test
if 0 > ageDeEricPraline > 150 or ageDeEricPraline > ageDeHenryWensleydale:
    print "l'age de Eric Praline est incorrect"

#echange : swap
ageDeHenryWensleydale, ageDeEricPraline = ageDeEricPraline,ageDeHenryWensleydale
print "age de Henry Wensleydale = %d , age de Eric Praline = %d" %(ageDeHenryWensleydale,ageDeEricPraline)
```

Avec un linenostart=8 

Tes lignes iront de 8 à 19 au lieu de 1 à 10 ?

**Comment by Coy0te** [comment]
Oui :)

**Comment by Thunderseb** [comment]
La syntaxe des blocs de code commence à devenir vachement dégueu :p

**Comment by firm1** [comment]
> La syntaxe des blocs de code commence à devenir vachement dégueu 

Ce sont des éléments qui restent optionnels. 

Ceci dit, @cgabard le serveur renvoi le warning suivant :  
`The ''force_lineos" config setting to the CodeHilite extension is deprecreated. Use "linenums" instead`.

ça te parle ?

**Comment by cgabard** [comment]
Yep je l'ai corrigé dans ma branche

**Comment by cgabard** [comment]
Des news : Ma PR sur python-markdown pour ajouter le support des intervalles avec l'option "hl_lines" n'est toujours pas passé. Il est plutôt pour mais il voudrait que je tente déjà de faire supporter ça directement dans pygment. Ça va me demander plus de temps (il y a une bonne trentaine de PR en attente sur pygment). Et ça nous obligera a attendre une nouvelle release de ce projet avant de l'avoir en support direct. Du coup on va probablement rester sur une version patché de python-markdown un petit moment.

En attendant, je lui ai annoncé mon envie d'ajouter aussi le support de linenostart et de la difficulité de le faire actuellement. En realité pour chaque option de pygment qu'on veut rajouter actuellement, il faut patcher python-markdown à deux endroit, faisant pleins de redondance. Je tente donc de lui proposer une modif plus large et plus générique pour régler ce genre de probs et qu'elles puissent, a minima, etre ajoutées avec des extensions. Dans ce cas là, on pourrait se passer de patch et juste forcer l'utilisation d'une version à jour

**Comment by cgabard** [comment]
Je fais une PR pour le supporter. pour le moment, l'option doit etre mise apres hl_lines si les deux sont spécifiés. Je fermerais quand ce ne sera plus necessaire

**Comment by cgabard** [comment]
normalement réglé pour la notation "fenced" (a la github). Pour la notation de code classique de markdown c'est beaucoup moins évident et je n'ai pas intention de le régler vu les probs que ça pose. je ferme donc, il est possible de le faire avec la notation fenced ce qui me semble suffisant.
