### ISSUE TITLE
Mise en place de JSHint

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#782]
Comme vous le savez peut-être, je suis en train d'intégrer Gulp dans le workflow front. Qui dit Gulp, dit JSHint. Du coup, il faudrait se fixer sur les options JSHint à mettre. Cela influe sur le style de code. La liste des options se trouve [ici](http://www.jshint.com/docs/options/), et voici ce que je propose:

``` json
{
  "browser": true,
  "camelcase": true,
  "eqeqeq": true,
  "indent": 2,
  "esnext": true,
  "globals": {},
  "jquery": true,
  "smarttabs": true,
  "trailing": true,
  "undef": true,
  "unused": true,
  "newcap": true,
  "quotmark": "double",
  "notypeof": true
}
```

Une fois que les options seront fixées, je m'occuperais d'adapter tous les scripts ;)

Voilà, la discussion est ouverte! :smile_cat:

**Comment by Alex-D** [comment]
> indent: 2

passes à 4, je sais que 2 c'est la norme, mais c'est illisible surtout pour le SCSS et les templates où y a des conditions, des blocs et tout.

> quotmark 

En JS j'ai tendance à utiliser les simples et ailleurs les doubles... bon courage pour mettre à jour les fichiers lors de ta PR :D

>   "smarttabs": true,

Si j'ai bien compris, à true ça veut dire qu'on autorise les mélanges tabs/espaces, si c'est le cas, faut le mettre à false. Sinon, je n'ai pas compris à quoi servait cette option.

**Comment by firm1** [comment]
Pour ma part, par rapport à la liste de sandhose, la seule chose que je
modifierai c'est le indent. Vaudrait mieux le passer à 4, pour les raisons
exposées par Alex-D

Sinon, y'a moyen d'integrer ça dans la vérification Travis (me suis pas
encore documenté) ?

**Comment by sandhose** [comment]
Ok pour l'indent ; pour le smarttabs, c'est vrai que c'est pas utile, donc je vais le virer
Pour le quotmark, j'dirais qu'en 1/4 d'H c'est fait ;)

@firm1 Je viens d'intégrer les tests gulp (qui inclura JSHint quand il sera mis en place) à travis (cf. #777 )
