### ISSUE TITLE
Sommaire absent dans les big tutos

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#785]
Le sommaire est absent dans les big tutos quand on se trouve dans une partie ou dans un chapitre précis.

**Comment by Alex-D** [comment]
En fait il est là, mais il bug, pourtant c'est exactement le même template qui est inclus.

Est-ce que le back expose la même chose du tuto depuis `tutorial` et `chapter.tutorial` ? Si oui, je ne comprends pas.

**Comment by firm1** [comment]
ça marchait avant, c'est tout ce que je peux te dire. Donc il te suffit de jetter un oeil aux anciens templates.

**Comment by Alex-D** [comment]
Le sommaire fonctionnera partout (édition, online, etc) dès le prochain pull.

**Comment by Alex-D** [comment]
Le sommaire est toujours HS, pourtant en local ça fonctionnait, faudra que je recheck ça...

**Comment by Alex-D** [comment]
Avec cette PR c'est testé et fonctionné à 200%. Une review rapide de @firm1 serait top, histoire d'être sûr que ce que j'ai fait n'est pas "mal".

**Comment by firm1** [comment]
Fx'd
