### ISSUE TITLE
Regression : Impossible de supprimer les MP par groupe

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#788]
Avant on pouvait selectionner une liste de MP et les supprimer en utilisant le bouton idoine.

Aujourd'hui, ça ne marche plus

**Comment by Alex-D** [comment]
Ouep je me suis trouvé un peu bloqué par le fait que le bouton de suppression est dans la sidebar, les cases à cocher dans le content et qu'il y a une boite modale de confirmation en plus de tout ça.

Je pense que je vais devoir mettre un peu de JS pour avoir quelque chose de propre.

**Comment by Alex-D** [comment]
Voilà qui est corriger ! A tester -> merger -> MEP.

**Comment by Eskimon** [comment]
C'est OK pour moi en local, je ferme !
