### ISSUE TITLE
Redirection vers la page visitée avant la connexion

### ISSUE THREAD

**Issue by AlexRNL** [zestedesavoir/zds-site#789]
Cela avait été soulevé dans le bug #91 mais il n'y avait pas eu d'action à ce sujet en particulier.

Je pense que ça serait appréciable de rediriger l'utilisateur qui vient de se connecter vers la page précédente.

Je m'en chargerai si j'ai le temps ce WE, et s'il n'y a pas d'objection :)

**Comment by firm1** [comment]
En fait il s'agit d'une regression. ça marchait avant le gros merge.

La solution pour fixer le bug, c'est de remettre [ce bout de code](https://github.com/zestedesavoir/zds-site/blob/b05a21f878a6aa8a438e45243fffdd6466fcbf8a/templates/source.html#L294) dans le lien du bouton connexion

**Comment by Alex-D** [comment]
Normalement fixé dans la PR #793
