### ISSUE TITLE
[Markdown] nouvelle balise video avec legende

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#79]
Actuellement les videos sont insérées grace à une URL. Ce comportement ne suit pas la philosophie markdown.

L'évolution proposé est de ré-utiliser la même syntaxe que la balise image et utiliser le champs dévolue au alt pour legende. Dans l'idéal et pour cohérence avec les autres legendes, il devrait aussi être permit d'utiliser la syntaxe "video : ..." en dessous pour préciser la legende. 

Enfin les videos ne devraient pas pouvoir être insérées inline.

**Comment by firm1** [comment]
J'approuve.

**Comment by Coy0te** [comment]
Déjà dit dans l'autre issue, mais pareil, j'approuve.

**Comment by cgabard** [comment]
Dans la prochaine PR, il y a déjà le support des legendes en externe. Je vais maintenant mettre en place la nouvelle syntaxe

**Comment by cgabard** [comment]
Apres reflexion, je pense que reprendre la syntaxe des images n'est pas le plus pertinent. Pour plusieurs raisons : 
- On prend le risque que le parseur la transforme en image si, par exemple, l'auteur se plante en écrivant l'url (écrire youtobe au lieu de youtube par ex)
- Si je force que les videos ne peuvent etre qu'isolées, une placé en inline sera considéré comme image.
- Utiliser le terme de champs alt des image comme legende n'est pas cohérent avec la syantaxe des legendes des autres éléments
- Permettre de mettre la legende aux deux endroits va m'emmerder pour l'implementation

Je propose donc d'utiliser une syntaxe proche mais sans le champ alt : 

```
!(http://www.youtube.com/watch?v=oavMtUWDBTM)
```

ou avec la legende : 

```
!(http://www.youtube.com/watch?v=oavMtUWDBTM)
Video : Ma legende
```

Vous en pensez quoi ?

**Comment by Coy0te** [comment]
+1 pour la légende en accord avec celles des autres blocs.

Ok pour la syntaxe à part entière.

**Comment by cgabard** [comment]
Implémenté dans un PR en attente, je ferme
