### ISSUE TITLE
Ajax implement on +1/-1 button

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#8]
Now, when you click on a button +1/-1, the topic page is refreshed. The goal is that when you click on, an ajax process is launched to check right of user, and refresh the counter.

**Comment by Coy0te** [comment]
On utilise jQuery pour l'Ajax ?

**Comment by Alex-D** [comment]
J'utilise jQuery dans mon intégration, donc j'ai envie de dire oui, ça sera carrément plus simple, il sera de toute façon déjà présent.

**Comment by Alex-D** [comment]
Pour dev ça, je tape sur la même URL que le non-AJAX et ça me retourne le nouveau total ? Ou je dois "simuler" le +1/-1 côté client ?

**Comment by firm1** [comment]
Tu tapes sur la même url oui, mais il faut refresh le contenu de [cette div](https://github.com/Taluu/ZesteDeSavoir/blob/dev/templates/forum/topic.html#L103)

**Comment by Alex-D** [comment]
T'es en train de me dire que la requête va retourner la page HTML et qu'il faut parser le HTML de cette page pour récupérer la nouvelle valeur ?

Sinon, côté back, il faut détecter si c'est une XHR et tu retourne du JSON dans ce cas : plus propre, plus léger, plus simple. Ca fait moins de calcul pour les deux parties.

**Comment by SpaceFox** [comment]
> Sinon, côté back, il faut détecter si c'est une XHR et tu retourne du
> JSON dans ce cas : plus propre, plus léger, plus simple. Ca fait moins de
> calcul pour les deux parties.

Alors il faut 2 URLs : une URL qui renvoie des formats différents selon le
contexte, ça pète toute forme de mise en cache.

Le 5 février 2014 17:38, DEMODE Alexandre notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
WTF ? On parle d'une page qui va faire une redirection je présume... il n'y a pas de cache sur du back qui fait une action d'écriture quand même ?

**Comment by firm1** [comment]
> T'es en train de me dire que la requête va retourner la page HTML et qu'il faut parser le HTML de cette page pour récupérer la nouvelle valeur ?

Quand je dis qu'il faut refresh, je parle bien de faire toute la tambouille send -> load -> json -> refresh.

A l'époque ou j'ai crée cette issue j'avais en tête que tu t'y connaissais assez pour le rajouter dans la vue. Mais soit, je m'en occuperait d'ici peu. en attendant, ça ne t’empêche pas d'implémenter ça comme si c'était déjà fait.

**Comment by Alex-D** [comment]
Tes phrases sont trop précises là où je comprends et vagues là où je n'y pige rien ^^

> que tu t'y connaissais assez pour le rajouter dans la vue.

C'est à dire ? Je galère avec Django, et chaque fois qu'on me parle de vue je pense au template... bref. 

Donc si je résume : je tape sur l'URL du lien, le serveur retourne du JSON (donne moi les noms des clés) et je refresh avec ça donc. Si c'est ça, c'est dans mes cordes (côté client).

**Comment by firm1** [comment]
Je vais donc modifier le back et te renvoyer un JSON avec deux clés nommées `upvotes` et `downvotes`.
Il faudra donc remplir les deux à chaque refresh coté client.

**Comment by firm1** [comment]
Bon, j'en ai profité pour te [mettre en dispo les clés back-end](https://github.com/Taluu/ZesteDeSavoir/commit/fedfaa3aa6d233067d4568f30901b9c226714dba).

**Comment by Alex-D** [comment]
La modif vaut aussi pour les commentaires des articles, ou autres endroits ?

**Comment by firm1** [comment]
Nope. Et je ne suis pas sur que ce soit une bonne chose de tout ajaxer. Faudrait avoir plus d'avis.

**Comment by SpaceFox** [comment]
Mon avis vaut ce qu'il vaut, mais je suis d'avis d'en mettre le moins
possible.

2014-02-05 firm1 notifications@github.com:

**Comment by firm1** [comment]
Apres reflexion, je crois que j'ai mal compris Alex. Il parlait sûrement de +1/-1 dans les articles, tuto et pas des commentaires en eux mêmes.

Pour lui répondre donc ... C'est non ce n'est pas encore valable la bas, mais je ferais le nécessaires avec les mêmes clés JSON.

**Comment by Alex-D** [comment]
AJAX bien utilisé vaut mieux qu'un site qui a besoin de recharger des pages toutes les 5 minutes.

En l’occurrence je ciblais juste les +1/-1 (ou système semblable) qu'il pourrait y avoir ailleurs que sur le forum.

EDIT : Ok d'ac, tu m'as bien compris cette fois :p

**Comment by firm1** [comment]
Fix'd
