### ISSUE TITLE
Regression : MP, impossible d'éditer un MP

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#801]
Il fut un temps ou on pouvait aditer son MP si personne ne l'avis encore lu.

Aujourd'hui on a plus le bouton adéquat. Pourtant le back-end le gère déjà.

**Comment by Alex-D** [comment]
Le soucis que j'ai rencontré c'est que je ne trouve pas la ligne qui me permet de savoir si quelqu'un a déjà lu le message ou pas.

**Comment by SpaceFox** [comment]
J'ai une question : pourquoi ne pas avoir demandé ?
Le 7 juin 2014 18:39, "Alexandre Demode" notifications@github.com a écrit
:

**Comment by firm1** [comment]
> Le soucis que j'ai rencontré c'est que je ne trouve pas la ligne qui me permet de savoir si quelqu'un a déjà lu le message ou pas.

Ce qui était fais avant, c'est que le bouton éditer était systématiquement mis là. Si quelqu'un avait déjà lu le MP le back renvoi un message pour expliquer pourquoi l'editer ne peut pas être fait.

**Comment by Alex-D** [comment]
Y aurait-il moyen d'avoir un test faisable en front. Perso je trouverais ça frustrant d'avoir un bouton qui dans 99% des cas sera inutilisable.

**Comment by firm1** [comment]
Même avec des tests en front, tu te retrouvera avec un bouton pas toujours utilisable. Car si tu n'as pas édité avant la lecture de l'autre coté, tu es bloqué.

Une première chose serait déjà de n'afficher ce bouton que pour le dernier message (car les autres sont forcément déjà lus).

**Comment by Alex-D** [comment]
Exact, du coup je vais faire ça.

**Comment by Eskimon** [comment]
Ca aussi se sera a fermer des que testé par quelqu'un :)

**Comment by Alex-D** [comment]
C'est pas ouf mon test... il est améliorable. Mais en gros tous les messages du dernier auteurs sont éditable.

**Comment by Alex-D** [comment]
J'ai une erreur 500 quand je clic pour éditer. Pour le coup ça semble être un soucis de back.

**Comment by Alex-D** [comment]
Un commit qui ne devrait pas être dans cette PR devrait patcher ce soucis. A tester à la prochaine MEP.

Manquait juste un "with" dans un template...

**Comment by Eskimon** [comment]
Le bouton d'edit est la (sur tout les messages) et fait une erreur 500 :(

**Comment by Alex-D** [comment]
Je regarde et corrige now :)

**Comment by Alex-D** [comment]
A vérifier par quelqu'un :)

**Comment by Eskimon** [comment]
Je sais pas si c'est lie mais: J'ai plus d'erreur 500 quand j'edite, par contre si je fais un edit, la page ne m'affiche pas l'edit... J'ai bien le "Edite il y a..." mais le contenu itself est toujours le meme... Par contre si je cite ou refais un edit je vois le vrai contenu !!

**Comment by Alex-D** [comment]
Ah, il manque un truc pour MàJ la version HTML du MD. C'est un correctif back que j'avais fait et testé pourtant. Il doit manquer une MàJ quelque part.

Je me met dessus.

**Comment by Eskimon** [comment]
Tout est bon, je ferme !

**Comment by Alex-D** [comment]
Halleluja \o/
