### ISSUE TITLE
Réorganiser quelques fichiers rendus moins lisible après le passage "PEP8"

### ISSUE THREAD

**Issue by mlorant** [zestedesavoir/zds-site#803]
Après l'application des règles PEP8, certains fichiers sont devenus moins lisibles et pourraient être améliorer en déplaçant simplement une ligne...
Par exemple, les fichiers `urls.py` (au hasard, [celui-ci](https://github.com/zestedesavoir/zds-site/blob/beta-0.2/zds/article/urls.py)): 

```
urlpatterns = patterns(
    '',

    url(r'^flux/rss/$', feeds.LastArticlesFeedRSS(), name='article-feed-rss'),
    url(r'^flux/atom/$', feeds.LastArticlesFeedATOM(),
        name='article-feed-atom'),

    # TODO: Handle redirect

    # Moderation
    url(r'^resolution_alerte/$', 'zds.article.views.solve_alert'),
```

(Notez la position du premier argument `''`). Cela laisse plus de place pour les arguments de `url()` (j'ai ici pris 79 caractères max., j'ai vu du 120 quelques part dans une autre issue). En bref, du détail mais rend la chose plus agréable à lire :)

**Comment by firm1** [comment]
ouaip au début on est parti sur du 79 max, mais on s'est rendu compte que c'est illisible, et du coup on a étendu a 120 chars.
