### ISSUE TITLE
Pourquoi les média de différentes tailles n'ont pas le même nom ?

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#809]
Je me demandais pourquoi les media de différentes tailles (medium, normal, et thumb) n'ont pas le même nom de fichier...

![image](https://cloud.githubusercontent.com/assets/1549952/3210962/965166a8-eef3-11e3-89d9-d43d38f57102.png)

Ça serait plus simple alors de changer la taille juste en changeant L’URL (d'ailleurs, est-il possible quelque part pour l'utilisateur de trouver l'URL pour les tailles medium et thumb ?)

Je suppose que c'est cependant compliqué à mettre en place pour les médias déjà uploadé, puisque tous les liens ne seront plus valides...

**Comment by SpaceFox** [comment]
AMHA c'est à gérer avec l'issue #256

**Comment by sandhose** [comment]
Quelqu'un a prévu de s'en charger ? L'issue date d'il y a 2 mois quand même...

En soit, je m'en suis rendu compte en voulant un peu bichonner la page des galeries (cf. #730 ), et du coup ça serais cool que quelqu'un s'en occupe, que je puisse afficher correctement les différentes tailles sur cette page...

**Comment by SpaceFox** [comment]
En fait, pour débloquer cette issue, il fallait attendre que le merge de la
branche d'intégration soit fait.
Je détaille les taches suivantes sur l'issue.

**Comment by geoffreyc** [comment]
La merge a ete faite ya quelques jours AFAIK ?

2014-06-08 11:30 GMT+01:00 SpaceFox notifications@github.com:

> En fait, pour débloquer cette issue, il fallait attendre que le merge de
> la
> branche d'intégration soit fait.
> Je détaille les taches suivantes sur l'issue.
>

**Comment by geoffreyc** [comment]
Haha fail, javais lue le "fallait" comme "faut", ma bad

2014-06-08 11:34 GMT+01:00 geoffrey compagnon speedking34@gmail.com:

> La merge a ete faite ya quelques jours AFAIK ?
> 
> 2014-06-08 11:30 GMT+01:00 SpaceFox notifications@github.com:
> 
> En fait, pour débloquer cette issue, il fallait attendre que le merge de
> 
> > la
> > branche d'intégration soit fait.
> > Je détaille les taches suivantes sur l'issue.
> >

**Comment by SpaceFox** [comment]
Certes, mais cette issue s'est mystérieusement retrouvée à la fois projetée
en "v2" et a perdu son tag "on peut la faire dès que l'intégration est
finie".
Ajoute à ça le fait que ni moi ni firm1 n'étaient très disponibles ces
derniers temps et elle n'a pas avancée.

**Comment by geoffreyc** [comment]
ouai non c'est moi qui avait mal comprit ton message, je pensais que tu
attendais toujours le merge ^^ Je ne critiquais en rien le fait que a avait
pas ete fait :D

2014-06-08 11:38 GMT+01:00 SpaceFox notifications@github.com:

> Certes, mais cette issue s'est mystérieusement retrouvée à la fois
> projetée
> en "v2" et a perdu son tag "on peut la faire dès que l'intégration est
> finie".
> Ajoute à ça le fait que ni moi ni firm1 n'étaient très disponibles ces
> derniers temps et elle n'a pas avancée.
>
