### ISSUE TITLE
Régression : impossible de poster sur mobile

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#812]
Galaxy S4 / Opera Mobile : le bouton "envoyer" du formulaire dans les topics n'apparait qu'en mode paysage.

**Comment by Alex-D** [comment]
Il passe dessous le bouton "Aide Markdown" en fait, du coup faut gérer plus finement ce bouton sur mobile.

**Comment by Alex-D** [comment]
Corrigé dans la #838, à tester en prod, sans oublier de vider le cache à ce moment là :)

**Comment by firm1** [comment]
Fixé mais a moitié.

Je crois que cette fois ci c'est un bug back sur le main-post.

A confirmer.

**Comment by Alex-D** [comment]
Tu peux me dire où/comment reproduire le bug pour que je vérifie ?

Merci :)

**Comment by Eskimon** [comment]
J'ai testé pour le souci initial (bouton cacher) en local et j'arrive à poster. @firm1 tu arrives à reproduire ton souci ?

**Comment by Alex-D** [comment]
Par contre ce qu'il serait bien, c'est de faire une issue par problème pour s'y retrouver. Le soucis initial est résolu, je vous laisse le loisir de créer une issue pour le back si nécessaire.
