### ISSUE TITLE
Regression : les filtres resolus/non résolus ont disparus

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#813]
C'était ultra pratique pour filtrer les topic résolu dans un forum et même pour la gestion des bugs c'était top.

Pourquoi a t-il disparu ? :'(

**Comment by Alex-D** [comment]
Parce que les templates ont été fork avant, et que j'avais dis que je ne pouvais pas tout surveiller pendant le refacto.

Comme toujours, si tu as le lien vers la version qui avait ces boutons, je suis preneur :)

**Comment by firm1** [comment]
[Merci](https://github.com/zestedesavoir/zds-site/blob/7e84bdc692fbd40c554a3a1063bd4cb8d28a4e17/templates/forum/details.html#L27)

**Comment by Eskimon** [comment]
Ca va etre a fermer aussi :)

**Comment by firm1** [comment]
Fx'd

**Comment by firm1** [comment]
Je réouvre ce ticket, car les filtres ont à nouveau disparus pour les utilisateurs non connectés.

**Comment by Alex-D** [comment]
Exact, je viens de comprendre pourquoi.

**Comment by Alex-D** [comment]
En attente de validation :)

**Comment by Eskimon** [comment]
A ete revalide et remerged, je referme :)
