### ISSUE TITLE
Ctrl/Cmd + Enter pour envoyer dans l'éditeur

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#814]
Pouvoir faire Ctrl/Cmd + Enter pour envoyer dans l’éditeur, un peu comme sur n'importe quel site (genre GitHub, Facebook, Twitter, ...)

**Comment by Alex-D** [comment]
Clairement pas prioritaire mais à garder dans un coin lorsque l'on aura avancé sur tout le reste.

**Comment by gustavi** [comment]
Corrigé et mergé ! Merci @Situphen !

**Comment by Eskimon** [comment]
Merci pour cette feature, c'est si pratique !

**Comment by Situphen** [comment]
Content que ça te plaise ! ;D
