### ISSUE TITLE
Citation et minicode

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#817]
Lorsque l'on cite un message qui contient plusieurs minicode, la partie cite place les citations comme des blocks au lieu de les garder inline.

Visible ici : http://zestedesavoir.com/forums/sujet/87/bug-tracker/?page=4#p2084

Le message de Kje est bon, ma citation est fausse (et spacefox confirme que le code de la citation est correct donc probleme de markdown ecarte).

Je ne sais pas si ca a toujours ete comme ca ou si ca buguait avant aussi...

**Comment by Alex-D** [comment]
Il faudrait que le markdown mette une classe sur la balise `<code>` pour qu'on puisse différencier un code multi-ligne légendé d'un code "mini".

**Comment by firm1** [comment]
> Il faudrait que le markdown mette une classe sur la balise <code> pour qu'on puisse différencier un code multi-ligne légendé d'un code "mini".

On avait pourtant pas besoin de ça avant. Il vaut mieux éviter de triturer le markdown (je trouve qu'on est déjà limite avec les bloc customs) pour des questions d'affichage.

**Comment by Alex-D** [comment]
Je verrais pour triturer le CSS alors. Avec l'opérateur "+" ou ">" on doit pouvoir faire quelque chose qui ne fonctionnera pas partout.

**Comment by Alex-D** [comment]
Ma PR n'a pas suffit... parce qu'il y a du `<code>` dans `<p>` du coup il faut que je prenne ça en compte...

**Comment by Alex-D** [comment]
Cette fois, j'ai bien tout vérifié, reste plus qu'à pousser et vérifier en prod, après quoi on pourra fermer cette issue.

**Comment by Alex-D** [comment]
Ca fonctionne bien (cf le lien de l'OP de cette issue) donc je ferme :)
