### ISSUE TITLE
Desinscription impossible

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#818]
Il est important, avant la sortie de la version public de pouvoir se désinscrire. Rien ne le permet actuellement. Cette issue est plus restreinte que #668 , je ne m'interesse pas à l'avenir du contenu, mais juste à la possibilité pour un membre de se désinscrire.

**Comment by firm1** [comment]
Techniquement on peut déjà de desinscrire en envoyant un mail au staff qui
fera le boulot.

Par contre je pense qu'il faut éviter de mettre en place une demie
desinscription. C'est a dire que la desisncription devra gérer les
problématiques de contenus présent sur le site.
Le 9 juin 2014 11:10, "Christophe Gabard" notifications@github.com a
écrit :

**Comment by cgabard** [comment]
Je suis staff et je ne vois pas comment je peux le faire.

**Comment by Alex-D** [comment]
En passant par la BDD :D

**Comment by cgabard** [comment]
Oui donc pas le staff, les admins c'est largement différents
Le 9 juin 2014 12:30, "Alexandre Demode" notifications@github.com a écrit
:

**Comment by ShigeruM** [comment]
Que faire du contenu des membres voulant se désinscrire ? Ce serait quelque chose comme :
- les posts sur le forum sont anonymisés ;
- les MP sont supprimés (le membre est retiré des MP et ses posts sont anonymisés) ;
- les tutos et articles sont attribués à un compte particulier (mascotte ?) mais le nom de l'auteur reste apparant
- etc ?

**Comment by Coy0te** [comment]
@ShigeruM : ton message a plutôt sa place dans l'issue #668.

Dans cette issue, je pense que l'important c'est de statuer si on a un moyen (quelconque) de désinscrire quelqu'un. Si oui, et qu'il est expliqué quelque part sur le site, alors l'issue est à clore.

**Comment by firm1** [comment]
> Dans cette issue, je pense que l'important c'est de statuer si on a un moyen (quelconque)

Actuellement pour désinscrire quelqu'un il suffit de faire la demande a quelqu'un qui a les pouvoirs et il le fera manuellement (le renommer anonyme et changer son mot de passe et son mail).

Mais l'issue reste ouverte pour débattre de l'automatisation de cette désinscription et des traitements à effectuer.

**Comment by geoffreyc** [comment]
Outre l'aspect technique de la chose, je pense qu'il faudrait laisser le
choix a l'utilisateur de ce qu'il veut laisser sur le site ou non. Une
série de "checkboxes" du genre

Effacer mes tutoriels?           [ ]
Effacer mes articles?            [ ]
Effacer mes tutoriels?           [ ]
Effacer mes messages?       [ ]
Effacer mes commentaires?  [ ]

Dans les cas des tutos/articles, on les effaces complètement. Dans le cas
messages/commentaires, on fait un mass update sur le contenu de tout les
messages du membre pour les effacer/remplacer par un texte indiquant
pourquoi il n'y a plus de contenu.

2014-06-11 15:21 GMT+01:00 firm1 notifications@github.com:

**Comment by cgabard** [comment]
Pour les tutos/articles, pourquoi pas, plutot, les masquer uniquement
(dévalider + status particulier) puis laissé le soit aux valido de voir ?
Car techniquement ils seront en CC-BY... et donc reprenable si on en a
envie, non ?

Christophe.

2014-06-11 16:29 GMT+02:00 geoffreyc notifications@github.com:

**Comment by Coy0te** [comment]
@geoffreyc  : je trouve assez improbable le fait de donner le choix au membre de supprimer ses messages/commentaires. L'anonymisation est le seul choix viable si on ne veut pas rendre le forum inutilisable.

**Comment by SpaceFox** [comment]
Je ne suis pas d'accord avec toi, @geoffreyc :
- Normalement les tutos et articles sont en CC. Donc le départ du membre et le retrait des tutos sont deux opérations différentes, la seconde est un pur problème éditorial.
- Les messages et commentaires sont à conserver pour que le forum reste lisible.

**Comment by firm1** [comment]
Moi je vois les options suivantes : 
- Tutoriels
  - Effacer : ici on les dépublie si l'auteur est le seul auteur, et on le vire de la liste des co-auteurs s'il y'a d'autres personnes
- Articles
  - Effacer : ici on les dépublie si l'auteur est le seul auteur, et on le vire de la liste des co-auteurs s'il y'a d'autres personnes
- Messages/Commentaires : 
  - cacher ses messages/commentaires : on cache tous les messages de l'utilisateur
  - anonymiser les messages/commentaires : on anonymise

**Comment by geoffreyc** [comment]
CC: spacefox

Niveau tuto/article, je comprend bien qu'ils sont en CC, mais veut on
vraiment donner l'image du "tanpis, on garde tes contributions, meme si
t'es pas content, parce que legalement on a le droit!" ? Perso je
préférerais laisser le choix au membre de si il veut le laisser ou pas.

pour les messages, "techniquement" (légalement?) si un membre en fait la
demande, on se doit de virer toutes ses contributions (mettre le message en
"anonyme" n'a pas vraiment l'air d'etre suffisant pour la CNIL). Ducoup je
vois pas de soucis a le proposer. Surtout qu'a l’époque sur le sdz on
l'avait vue plein de fois: un coup de script et les membres pouvaient
editer tous leurs messages pour les vider.

2014-06-11 15:36 GMT+01:00 Coyote notifications@github.com:

**Comment by SpaceFox** [comment]
OK pour laisser le membre demander la dé-validation de ses tutos / articles, mais pas pour coupler ça automatiquement avec la désinscription.

Souvent les désinscrtiptions sont du ragequit.
D'autre part, si tu es le seul à utiliser ton compte, ton tuto est normalement lu par plein de gens. Qui sont peut-être en train de le lire. Et si un tuto disparaît brutalement sans préavis, c'est aussi mauvais en terme d'image.

Pour moi la suppression des tutos doit être possible, mais c'est un vrai processus éditorial, dans lequel il doit y avoir une discussion avec les validos sur les raisons de la dévalidation et ce qu'on peut faire du tuto, pour respecter la volonté de l'auteur et le bien des lecteurs.

> mettre le message en "anonyme" n'a pas vraiment l'air d'etre suffisant pour la CNIL

Ça je demande une source. Un post de forum ou un commentaire, à moins d'être particulièrement long et compliqué, n'est même pas considéré comme une œuvre de l'esprit.

Par contre il faut que l'anonymisation soit réelle, en particulier qu'on ne puisse pas différentier les messages de 2 anonymes différents.

> cacher ses messages/commentaires : on cache tous les messages de l'utilisateur

Ça par contre pour moi c'est juste hors de question, parce que ça va rendre les forums où le membre a posté inutilisables.

**Comment by ArnaudCalmettes** [comment]
Est-ce qu'on peut encore considérer que cette issue est "bloquante bêta publique" si les utilisateurs ont quand même moyen de demander la suppression de leur compte à un admin ? 

Pour moi, c'est au pire "bloquant V1", et encore ça tient limite de la feature ("désinscription automatique") qu'on peut placer en Post-V1-mais-faudra-pas-trop-trainer-non-plus. Vous en pensez quoi ?

**Comment by cgabard** [comment]
Oui moi aussi. Tant qu'on a un moyen de le faire, ce n'est pas bloquant
Le 14 juin 2014 03:21, "ArnaudCalmettes" notifications@github.com a écrit
:

**Comment by ArnaudCalmettes** [comment]
OK, dans ce cas, je passe l'issue en "bloquant V1". On avisera après la bêta.

**Comment by SpaceFox** [comment]
Je propose qu'en v1 on indique dans le profil que pour l'instant pour se désinscrire il faut contacter un staffeux, et que qu'on fasse la vraie procédure au calme peu après la v1.

**Comment by Alex-D** [comment]
> il faut contacter un staffeux

On peut s'en contenter tant que c'est gérable (donc bien après la v1 je pense). Non ? Enfin je pense que c'est quelque chose d'assez complexe à implémenter (faut rien oublier)  et qui n'est pas super important face à d'autres modules cruciaux.

**Comment by ArnaudCalmettes** [comment]
OK. Va pour ça.

Du coup, pour la v1.0, indiquer dans le profil ou quelque part qu'il faut contacter un membre du Staff pour se désinscrire. Ensuite on passera cette issue en v1.x.

**Comment by Alex-D** [comment]
Dans les paramètres peut-être ?

**Comment by firm1** [comment]
Attention : contacter un staff c'est bien, mais le staff, ni personne
d'autre ne peut "anonymiser" (selon la définition vue en dev zone) les
topics actuellement.

Donc il faut quand même coder quelque chose.
Le 9 juil. 2014 23:06, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
@firm1 : t'avais réussi à le faire sur un compte pendant la beta non ?

**Comment by firm1** [comment]
Pas selon la définition de l'anonymisation qu'on a validé.
 Le 9 juil. 2014 23:51, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by gustavi** [comment]
UP ! Ça en est où ? Quelqu'un bosse dessus ?

**Comment by Eskimon** [comment]
> Quelqu'un bosse dessus ?

Pas a ma connaissance... Tu veux le faire ?

**Comment by gustavi** [comment]
Oui je peux.

voir mon post suivant.

**Comment by pierre-24** [comment]
Je dirais via staff, genre formulaire avec tout les choix que tu propose (qui me vont bien) qui balance un MP a qui de droit. Ça me semble bien pour tempérer des _ragequit_ éventuel. Après, faut voir si c'est légal ....

**Comment by Eskimon** [comment]
http://zestedesavoir.com/forums/sujet/444/cas-des-desinscriptions/

**Comment by gustavi** [comment]
Donc si je résume (selon @firm1 et approuvé par le reste du staff):

Anonymiser c'est :
- Que sur les messages postés :
  - au lieu du pseudo on lit "anonyme"
  - le staff peut encore éditer ces messages ou le masquer
  - lorsqu'on cite ce message, la source est anonyme
  - le message d'une source anonyme peut avoir aidé
  - on peut +1/-1 ce message
  - il n'y a plus de signature
  - l'avatar est une image par défaut pour tous les posts anonymes
  - on ne peut plus cliquer sur l'avatar pour consulter le profil
- Que :
  - l'adresse mail de l'ancien compte est libéré (actuellement deux membres n'ont pas le droit d'avoir la même email)
  - le pseudo peut-être utilisé par quelqu'un d'autre
  - le pseudo "anonyme" ne doit pas être un pseudo réservé

Ensuite questions : 
- Comment on s’anonymise ? (via un formulaire je suppose)
- Est-ce qu'il y a une validation du staff ?
- Quand est-il du profil ? Un message indiquant que ce compte a été supprimé suffit ?
- Comment gérer le fait qu'un compte est supprimé? Utiliser le champ _is_actif_ du modèle User peut être une idée mais en créer un autre pour éviter les conflits avec les nouveaux membres me semble mieux.
- Pour ce qui est du _Anonyme_ qu'on verra apparaitre dans le forums et autres, on gère ça dans le front ? Parce que si on change le pseudo, plus aucune trace pour le staff et on risque d'avoir des conflits.

Remarques personnelles : 
- _« le pseudo peut-être utilisé par quelqu'un d'autre »_ : est-ce vraiment une bonne idée ?

**Comment by firm1** [comment]
> Comment on s’anonymise ? (via un formulaire je suppose)

Je ne suis pas sur de saisir le sens de la question. J'ai envie de dire qu'on s'annonymise en se désinscrivant. Et la desinscription se fait via un bouton dans la page de profil, qui devrait ouvrir une boite modale, pour le valider.

> Est-ce qu'il y a une validation du staff ?

Je ne pense pas, ça devrait être automatique. Mais si le gars qui se désinscris a un tutoriel/article en ligne, ça pourrait être chouette de faire un MP au staff pour les avertir, ainsi qu'aux co-auteurs.

> Quand est-il du profil ? Un message indiquant que ce compte a été supprimé suffit ?

Le profil devrait renvoyer vers une 404 (même comportement que lorsque le compte n'existe plus).

> Comment gérer le fait qu'un compte est supprimé? Utiliser le champ is_actif du modèle User peut être une idée

Ce champ est déjà utilisé pour les membres inscrit, mais qui n'ont pas encore activé leur compte. Il faut donc utiliser autre chose. rajouter un champ dans le modèle profile par exemple.

> Pour ce qui est du Anonyme qu'on verra apparaitre dans le forums et autres, on gère ça dans le front ? Parce que si on change le pseudo, plus aucune trace pour le staff et on risque d'avoir des conflits.

Si on a un champ "is_anonyme" ou "is_alive" pour désigner un profile anonyme ou non, il suffit dans le template de rajouter une condition.

> « le pseudo peut-être utilisé par quelqu'un d'autre » : est-ce vraiment une bonne idée ?

Moi je trouve ça normal. Si quelqu'un se désinscrit du site et libère un pseudo, quelqu'un d'autre peut l'utiliser.

**Comment by gustavi** [comment]
@firm1 On peut laisser le choix à l'utilisateur pour qu'on ne puisse pas reprendre son pseudo. Personnellement je suis contre la ré-utilisation de mon pseudo et je pense qu'une majorité des gens le sont également.

Je pense également qu'il faut qu'un auteur puisse laisser son tutoriel comme l'a suggéré nohar : 

> Si on rattache le tutoriel à un compte neutre fait exprès pour ça (genre "Auteur externe") mais qu'on indique très clairement l'auteur du tutoriel au début de celui-ci, alors il n'y a pas violation de la licence ni du droit d'auteur puisqu'on reconnaît explicitement la paternité de l'auteur sur son œuvre.

Concernant les tutoriels/articles en beta/validation, est-ce qu'on fait la même chose que pour ceux publiés (cf http://zestedesavoir.com/forums/sujet/444/cas-des-desinscriptions/#p4363 ) ?

**Comment by gustavi** [comment]
ping @firm1 @ArnaudCalmettes 
- Voir message ci-dessus
- Pour pouvoir attribuer le pseudo d'un membre qui s'est désinscrit on doit forcement le remplacer en DB par une valeur. Laquelle ? « Anonyme » ?

**Comment by artragis** [comment]
auteur externe?

**Comment by gcaillaut** [comment]
Pourquoi remplacer le pseudo ? Désactiver l'utilisateur et traiter ce cas a l'affichage ne serais pas plus simple ?

``` python
if not user.is_active:
    pseudo = "Anonyme" # Ou ce que vous voulez
else:
    pseudo = user.username
```

**Comment by cgabard** [comment]
Conformément aux recommandations de la CNIL et la loi, on ne doit pas
masquer un utilisateur, on doit supprimer toutes les infos sur lui. Masquer
le fait qu'il est encore en base ne sera pas légal.

**Comment by gustavi** [comment]
Donc en gros on fait quoi ?

On change son pseudo par « Anonyme » en plus de virer tout les liens dans les templates ?

**Comment by firm1** [comment]
> Donc en gros on fait quoi ?

C'est plutôt simple, il suffit de faire une truc du style : 

``` python
#in views.py

username_for_kill='firm1'

# unlink all articles of user
# unlink all tutorials of user
# unlink all galleries of user

# unlink all posts of user
anonymous_topics = Post.objects.filter(username=username_for_kill).all()
for anonymous_topic in anonymous_topics:
    anonymous_topic.author=None
    anonymous_topic.save()

#delete user in database
Profile.user.get(username=username_for_kill).delete()
```

Ensuite
- modifier le model.py des posts, pour qu'il autorise les posts sans auteur (ne pas oublier de générer le fichier de migration)
- dans les templates, vérifier si un post n'a pas d'auteur, afficher annonyme.

**Comment by Eskimon** [comment]
Ca serait pas plus simple de creer un compte "anonyme" ? Au moins le modele reste coherent et on peut personnaliser ce compte simplement (en lui mettant une bio qui explique le role de ce compte, un avatar etc... le tout sans modifier les templates ni rien).

Faire la solution de linke a None ca me semble bugogene...

**Comment by firm1** [comment]
Eskimon, si on fait comme tu dis, on invalide certains trucs qui ont été acté à savoir : 
- on ne peut plus cliquer sur l'avatar pour consulter le profil
- le pseudo "anonyme" ne doit pas être un pseudo réservé

**Comment by SpaceFox** [comment]
PErsonnellement ça ne me pose pas de problème :
- Si le profil explique clairement qui est le membre "Anonyme", c'est mieux (par contre du coup il faut interdire de le connecter et de lui envoyer des MP)
- En réservant "Anonyme" on évite les petits malins qui feraient les cons avec ce pseudo

**Comment by gustavi** [comment]
Bon alors qu'est ce qui est décidé ?

C'est un peu compliqué de savoir ce qu'il faut faire sachant que tout le monde a un avis un peu différent, que selon l'endroit (github, IRC ou le forum) la définition de « Anonyme » change, etc (et c'est assez énrvant d'avoir passer 2h à coder une partie de la desinscription qui ne respecte pas les critères données après).

Serait-il possible d'avoir un définition **claire, précise et technique** de ce qui est appelé « Anonyme » ?

**Comment by firm1** [comment]
Les discussions fonctionnelles doivent être discuttées sur le forum. Si la [définition fonctionnelle de l'anonymat](http://zestedesavoir.com/forums/sujet/444/cas-des-desinscriptions/#p4358) qui a été donnée (et qui a été majoritairement validée) est remise ne cause, c'est là bas qu'il faut en parler pas ici.

**Comment by SpaceFox** [comment]
@gustavi attention, il y a eu des [modifications dans le fonctionnel](http://zestedesavoir.com/forums/sujet/444/cas-des-desinscriptions/#p15260) suite aux retours de @firm1.

J'espère que ça ne casse pas ton travail...

N'hésite pas à nous dire où tu en es !

**Comment by gustavi** [comment]
Je vais reprendre à 0, je pense m'en occuper début de semaine.

**Comment by SpaceFox** [comment]
OK

**Comment by SpaceFox** [comment]
Des nouvelles @gustavi ?

**Comment by SpaceFox** [comment]
Ping @gustavi ? C'est l'une des dernières issues de la v1.0 !

**Comment by gustavi** [comment]
Désolé mais j'ai pas eu le temps de fixer ça, le problème c'est que j'ai essayé de partir de ce que j'avais déjà fait mais ça cassait tout parce que plein de commits sont venus entre temps et que la définition d'anonymisation était vraiment différente de celle que j'avais compris.

Pas disponible pour la semaine qui arrive, je peux fixer ça le week-end prochain, sauf si queqlu'un a le courage de s'en occuper d'ici là.

**Comment by pierre-24** [comment]
On peut toujours en discuter jeudi !

**Comment by SpaceFox** [comment]
On commence à avoir pas mal de PR en attente sur `dev`. Du coup pour faire avancer les choses et comme c'est le dernier ticket, je propose de sortir cette issue de la v1.0 et de la faire dès que possible.

C'est bon pour tout le monde ?

**Comment by artragis** [comment]
ça me va ^^ ! Faudra le dire sur un article du site qu'on passe en V1 stable.

**Comment by Eskimon** [comment]
Mouai, moyen quand meme de retirer une demande légale pour nous arranger... A mon sens la v1 ne devrait pas etre V1 sans cette fonction...

**Comment by SpaceFox** [comment]
Pour moi la problématique est qu'on a plus que ce ticket dans la pile, qu'il n'est pas prêt d'être fait (dans le sens où on a même pas de PR pour ça, donc qu'on ne l'aura pas mergable avant au moins ce WE) et donc qu'il devient complètement bloquant pour "sortir" la v1.0 (je détaille après ce que je veux dire par là).

Aujourd'hui on ne peut rien faire de propre sur `dev` tant qu'on aura pas mergé `master` dedans et donc qu'on aura sorti la v1.0. Or, on a beaucoup de corrections / évolutions faciles qui peuvent être faites rapidement, et on a _déjà_ 6 PR en attente de merge. Le "bloquant" n'est donc pas une simple vue de l'esprit : on a _déjà_ des actions qui attendent cette sortie.

D'autre part, l'obligation légale en question est de pouvoir supprimer un utilisateur (ce qui n'est pas "se désinscrire soi-même" à ma connaissance, toute source sérieuse est la bienvenue). Aujourd'hui si on rencontre le cas, on peut le faire manuellement (sauf erreur de ma part). L'option existe, mais elle demande de passer par le staff ; il manque sans doute une phrase pour écrire ça dans le profil avec un lien vers le contact et un autre vers cette issue.
Donc en repoussant la sortie de la fonctionnalité "se désinscrire", on ne retire aucune demande légale.

Enfin, fonctionnellement on est en v1.0 depuis la sortie. Cette v1.0 technique n'était là que pour bloquer le processus de développement le temps d'avoir une base suffisamment stable. Or à moins que cette issue ait des implications que je ne maîtrise pas, elle n'est _pas_ nécessaire à la stabilité du socle technique et n'a été mise en v1.0 que parce qu'elle est urgente. Et cette urgence ne nécessite pas de faire attendre tout le reste du développement.

Pour moi les solutions que je vois sont :
1. On merge `master` dans `dev` pour pouvoir faire avancer `dev` le temps de finir cette issue sur `master`. Et on va avoir plein de problèmes parce que les 2 branches vont très vite diverger (6 PR au moment où j'écris ces lignes).
2. On continue à bloquer tout développement tant que cette issue n'est pas corrigée, soit jusqu'au WE prochain + le temps de QA au moins. Ici toute PR supplémentaire sur `dev` accroit le risque de conflits au moment de les merger.
3. On considère qu'on a aucun _besoin_ d'attendre et on fait avancer le schmilblick le plus efficacement possible en sortant cette issue de la v1.0 (moyennant une phrase dans le profil si besoin), et on sort une v1.1 dès que cette fonctionnalité est prête.

**Comment by Eskimon** [comment]
Ou **d**, la réponse d ;)

Perso la solution 3 me semble une "alternative minimum" viable. Un truc genre

> "Pour vous désinscrire, merci de contacter xxx ou yyy (ou Clem ?). Votre demande sera alors effective dans un delai de 48h."

Ca me semble le minimum syndicale de proposer et expliquer la démarche a l'utilisateur. Une solution automatique sera bien sur la bienvenu pour éviter la charge de travail aux super-utilisateurs.

**Comment by Coy0te** [comment]
Il me semble qu'on avait déjà proposé ça comme truc temporaire avec Alex,
et qu'à l'époque ça avait été acquiescé. Si oui, go go go :)

**Comment by firm1** [comment]
> D'autre part, l'obligation légale en question est de pouvoir supprimer un utilisateur [...]. Aujourd'hui si on rencontre le cas, on peut le faire manuellement (sauf erreur de ma part). L'option existe, mais elle demande de passer par le staff

Je crois que l'option n'existe malheuresement pas. Pour supprimer un utilisateur aujourd'hui il faut supprimer tous ses posts (cascading toussa). Ce qui me parait illogique.

Donc, je pense qu'avant de décaler cette issue, il faut trouver une solution de contournement au problème actuel.

**Comment by Alex-D** [comment]
Mergé par @SpaceFox s'en est donc terminé !

Il faudra être vigilent lors de la préprod et rouvrir en cas de besoin.

**Comment by SpaceFox** [comment]
J'ai oublié de préciser : merci de **ne pas toucher** ni aux tickets, ni à la milestone.

Je repasse sur tout pour avoir quelque chose de propre, donc ça va être très bizarre les minutes qui viennent. C'est normal et voulu.

**Comment by Eskimon** [comment]
En tout cas \o/ pour ce ticket !

**Comment by artragis** [comment]
Il faudra que pendant la période de release quelqu'un vérifie que les TU
testent tous les cas.
Actuellement, je n'ai pas eu le temps de coder le test qui check que le
topic de la béta est bien altéré.

**Comment by jcval** [comment]
Petit fix ortho à faire :

"Parmi" (modale de la dernière chance) ne prend pas de "s"

**Comment by Alex-D** [comment]
Voilà qui est corrigé :) Merci @Eskimon !
