### ISSUE TITLE
Gallerie, code MD d'ajout d'image

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#819]
J'avais coder un petit bout de truc pour avoir le code d'insertion markdown d'une image lorsque l'on upload cette derniere. Ce bout de code a ete perdu...

Voila le commit qui permettait cela : https://github.com/zestedesavoir/zds-site/commit/cc4dd6f2cef181f965649c390962ed2f3ac331bd

**Comment by Alex-D** [comment]
Merci !

Je remets ça en place sous peu :)

**Comment by Eskimon** [comment]
On va pouvoir fermer ceci :)
