### ISSUE TITLE
Redirection après connexion

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#820]
Quand je me connecte sur la prod, je suis redirigé vers l'URL `http://zestedesavoir.com/membres/connexion/?next=http://zdsappserver/`. Est-ce un comportement attendu ?

Le next me semblant un peu louche, je préfère poser la question.

**Comment by firm1** [comment]
> Est-ce un comportement attendu ?

Ouaip.

Est-ce qu'il y'a eu un bug à un moment pendant cette redirection ?

**Comment by SpaceFox** [comment]
L'URL dans le next me paraît vraiment bizarre : le client n'a aucune chance
de savoir ce qu'est ce "sdzsappserver". Si cette URL n'est pas à
destination du client, à quoi sert-elle ?

2014-06-09 13:21 GMT+02:00 firm1 notifications@github.com:

**Comment by Coy0te** [comment]
Aucun bug non. 

Tout comme SpaceFox, je trouvais simplement un peu bizarre que la chaîne présente dans le next ne soit pas un simple chemin relatif, ou alors la vraie URL complète.

**Comment by firm1** [comment]
> Si cette URL n'est pas à destination du client, à quoi sert-elle ?

En fait c'est l'url de la socket de l'application coté serveur. En gros elle désigné la home page. En local par exemple tu aurais `http://zestedesavoir.com/membres/connexion/?next=http://127.0.0.1:8000/`. Et donc au lieu d'afficher notre IP en prod, ceci explique celà

**Comment by Coy0te** [comment]
C'est pas envisageable de mettre `?next=` pour la home, `?next=/articles` pour les articles, etc. ?

Après, c'est du détail hein, tout fonctionne anyway. Je demande juste par curiosité, parce que je ne comprends pas pourquoi on a besoin de cette info dans l'URL.

**Comment by firm1** [comment]
C'est envisageable oui.

Je laisse l'issue ouverte du coup.
