### ISSUE TITLE
[Markdown] pas de cohérence entre citation et custom block 

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#83]
[truc qui ressemble à un bug](http://www.zestedesavoir.com/forums/sujet/7/rediger-sur-zds?page=1#p45) : 
- quand on cite une liste, on écrit un > puis un espace en début de ligne, puis le contenu, et ça ne casse pas même si on cite une liste. 
- quand on fait un secret/info/etc, on écrit un | puis un espace en début de ligne, puis le contenu, et là par contre ça casse si on englobe une liste. Ça ne casse pas si on vire l'espace après le |. Assez étrangement par contre, ça ne pose pas de problème quand on englobe un tableau, ça marche avec ou sans espace dans ce cas-là. C'est juste les listes qui merdent.

**Comment by firm1** [comment]
Il me semble que ça doit être la partie du code qui interprète le contenu des customs blocs qui doit merder.

**Comment by cgabard** [comment]
Oui et non. Je dois vérifier mais en fait il me semble que la regexp des citations dit explicitement qu'apres le `>` il peut y avoir un espace optionnel. Or dans les customs blocks, je n'ai pas fait ça. 

Faut juste que je vérifie mais normalement ça devrait suffir à régler le prob.

**Comment by cgabard** [comment]
@Coy0te : Tu peux me copier/coller ici des morceaux de codes pour illustrer le prob ? je ne suis pas surs de voir...

**Comment by cgabard** [comment]
Bon je ne suis pas surs d'avoir bien perçus le pourquoi du comment mais j'ai reproduit le fonctionnement des citations.

A venir dans la prochaine PR

**Comment by Coy0te** [comment]
Tu as toujours besoin d'exemples ou c'est bon ? J'avais fait un post dans le sujet de shig sur zestedesavoir.

**Comment by cgabard** [comment]
Tu testera sur la prod quand j'aurais fais la PR et que firm1 aurat poussé. A priori j'ai reproduit le comportement des citations

**Comment by cgabard** [comment]
Il me semble que c'est en prod, je ferme :)

**Comment by firm1** [comment]
J'ai du [fixer](https://github.com/Taluu/ZesteDeSavoir/commit/105e03bcb24a3264ed0010bc990e00233d4c6ba4) un truc qui bugait par ici, mais tout va bien maintenant.

**Comment by cgabard** [comment]
En effet
