### ISSUE TITLE
Aucune interface de modération d'un membre

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#836]
Je n'ai nulle part trouvé de bouton/interface dans l'ancienne version pour :
- ban / dé-ban
- LS / dé-LS
- historique des sanctions
- ...

Est-ce que ces fonctionnalités sont développées, si oui, où est-ce que cela se trouve dans les templates de l'ancienne version, car je ne trouve pas du tout.

Merci :)

**Comment by firm1** [comment]
Elles se cachaient [ici](https://github.com/zestedesavoir/zds-site/blob/b05a21f878a6aa8a438e45243fffdd6466fcbf8a/templates/member/base_read.html)

**Comment by Alex-D** [comment]
Oooh ! Excellent ! Je rajoute tout ça :)

**Comment by Alex-D** [comment]
A tester dans la PR #835

**Comment by Alex-D** [comment]
Du coup, ça c'est fait.
