### ISSUE TITLE
Impossible de changer les droits dans les galeries

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#839]
Je suis en train de m'occuper des galeries, et je me suis rendu compte qu'il est impossible de changer les droits de quelqu'un dans une galerie (genre, passer quelqu'un de "lecture" à "écriture", et vice-versa, ou carrément virer quelqu'un d'une galerie...)

Est-ce que c'est juste un manque côté front, ou ça a pas été encore prévu/fait côté back ? Si c'est uniquement côté front, je m'en occuperais pendant le design des galeries.

**Comment by firm1** [comment]
> je me suis rendu compte qu'il est impossible de changer les droits de quelqu'un dans une galerie

D'après une lecture rapide du code back, ce n'est pas implémenté. C'est probablement parce qu'il doit y avoir un rapport avec l'issue #256 qui va peut-être changer deux-trois trucs.

**Comment by sandhose** [comment]
Ok d'ac! Donc je laisse comme c'est pour le moment.

**Comment by Alex-D** [comment]
Est-ce que cette issue est vraiment nécessaire pour la V1 ?

Le front se limite, je pense, à une boite modale. Le principal du travail est au niveau du back, et du coup _we are bloqued_.

**Comment by firm1** [comment]
> Est-ce que cette issue est vraiment nécessaire pour la V1 ?

Je ne pense pas, surtout qu'elle est marquée evolution et donc casse le gel !

**Comment by poulp** [comment]
je m'en charge

**Comment by firm1** [comment]
> je m'en charge

Je me mets en placeholder pour que les autres comprenne que le truc t'es réservé

**Comment by SpaceFox** [comment]
Ça m'a l'air d'être corrigé ici, quelqu'un peut confirmer ? @poulp ?

**Comment by GerardPaligot** [comment]
Non, ce n'est toujours pas possible de changer les droits des autres personnes dans une galerie, ni d'en retirer. Les membres doivent se retirer eux même et doivent être ajouté par après avec le droit voulu.

Mais est-ce que nous voulons permettre aux membres de changer les droits des autres ?

**Comment by GerardPaligot** [comment]
J'ai un souci avec cette issue :
- Elle dispose du tag "BUG" et "Evolution" en même temps. Cela me semble clairement une évolution, je change ça.
- Une galerie n'est pas associée à une personne avec les "collaborateurs". Tous les membres disposent d'un droit de lecture ou d'écriture, mais c'est tout. Alors quelle politique pourrions-nous adopter pour donner les droits à quelqu'un de virer quelqu'un d'autre ? Quand il a les droits d'écriture ?
- Est-ce que nous voulons permettre aux membres de virer les autres ?

**Comment by gustavi** [comment]
Personnellement « _il est impossible de changer les droits de quelqu'un dans une galerie_ » je considère ça comme un bug.

**Comment by GerardPaligot** [comment]
Pas à partir du moment où il n'a jamais été question de donner ces droits à quelqu'un.
