### ISSUE TITLE
[Markdown] Nom et auteur du post des citations

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#84]
Il a été question de la possibilité de specifier avec les citations l'auteur du message. Doit on l'implémenter dans notre syntaxe markdown ?

[Edit Coyote] Pour préciser, vis-a-vis de l'existant en zCode actuellement on se contente de transformer une citation de type : 

```
<citation nom="renard">
    bla bla,
    bla.
</citation>
```

En : 

```
**renard a écrit :**
> bla bla,
> bla.
```

**Comment by Coy0te** [comment]
Est-ce qu'il y a un comportement/une syntaxe qui revient chez ceux qui ont fait des extensions au markdown pour ce cas-là ?

**Comment by cgabard** [comment]
Pas vraiment. D'autant plus que ceux qui font ça, le font en général pour des citations "de textes".

Donc ça peut donner des trucs comme ça : 

```
> Ma citation
> D'un mec connue
> -- <cite>Le mec connue</cite>
```

C'est donc plus insérer en dur le rendu que l'on souhaite obtenir

**Comment by firm1** [comment]
Il me semble plutôt judicieux d'utiliser cette balise `<cite>` pour rendre la source des citations plutôt que d'inserer en dure "source a écrit". Comme je l'ai déjà dit, on garde la portée sémantique. Et on peut au niveau du design faire quelque chose assez beau.

Et pour la syntaxe, si vous n'en trouvez pas, celle que j'ai déjà donnée reste d'actualité.

**Comment by cgabard** [comment]
La première question est de savoir si effectivement on veut cette sémantique

**Comment by Coy0te** [comment]
Perso, si on part là-dessus j'aimerais qu'on trouve une syntaxe pas trop loin des citations originales en markdown. Est-ce que c'est jouable de continuer avec la syntaxe du genre `Citation:nom de l'auteur` en fin de citation, comme on le fait déjà pour les tableaux et codes ? Ou c'est peut-être trop chiant avec les citations imbriquées ?

**Comment by cgabard** [comment]
Interessant, pourquoi pas. C'est juste dommage, la syntaxe ne permet pas vraiment d'indiquer le liens vers le passage concerné.

**Comment by Coy0te** [comment]
Pour moi, le but d'une citation c'est d'avoir tout dans un seul post. Si un lien devient nécessaire, alors on met un lien md, pas une citation. Du coup, ça me choque pas que l'on puisse uniquement préciser un texte et un auteur. Le truc un peu chiant par contre, c'est que quand un type change de pseudo le nom dans les citations ne change pas, mais bon c'est un edge case qu'on est pas forcés de gérer non plus, et puis ça serait un peu casse-couille d'avoir une syntaxe basée sur les id des auteurs juste pour éviter ça.

Sinon, il y avait bien un système de lien auto vers le passage original d'une citation sur la v3 du SdZ, mais ça merdait pas mal, à cause notamment des différents systèmes en place : commentaires de news, de tutos, post de forums... Le truc était basé sur un postId pour générer le lien, et du coup ça déconnait avec des citations de trucs pas issus des mêmes tables et portant les mêmes ids.

**Comment by cgabard** [comment]
> Il y avait bien ce système de lien auto vers le passage original d'une citation sur la v3 du SdZ, mais ça merdait pas mal, à cause notamment des différents systèmes en place : commentaires de news, de tutos, post de forums... Le truc était basé sur un postId pour générer le lien, et du coup ça déconnait avec des citations de trucs pas issus des mêmes tables et portant les mêmes ids.

Ça c'est pas mon prob en soit. Moi je disais juste que la syntaxe aurait put contenir le liens pour nous permettre de générer un truc equivalent à : 

```
**[Machin a écrit :](liens)**
> la citation
```

C'est au front, quand on clique sur le bouton "citer ce message" de mettre le bon liens. Ou au mec qui l'ecrit. Mais en soit ce n'est pas forcément en liens direct avec le zcode. Je reprend juste une idée proposée par Spacefox que je trouvait pertinente : dans presque tous les cas où on cite, c'est a partir d'un message en particulier. 

ça insitera aussi les gens a mettre leur source quand ils citeront quelque chose.

**Comment by firm1** [comment]
Je ne vois pas pourquoi on doit se sentir obligé d'utiliser les balises <cite>. On a pas besoin d'être aussi verbeux et ça n'as mas vraiment d'avantage.

Je continue de militer pour une syntaxe propre et simple avant le texte cité. Qui permet aussi d'inclure un lien (pour indiquer la source)

**Comment by cgabard** [comment]
> Je ne vois pas pourquoi on doit se sentir obligé d'utiliser les balises . On a pas besoin d'être aussi verbeux et ça n'as mas vraiment d'avantage.
> 
> Je continue de militer pour une syntaxe propre et simple avant le texte cité. Qui permet aussi d'inclure un lien (pour indiquer la source)

Oui @firm1 je préciser juste le type de sortie générer par cette balise mais en soit il faut effectivement que la syntaxe soit plus courte que ça si on l'implemente. Ce qui pose probleme avec la syntaxe de legende car je ne sais pas ou on peut placer le liens.

**Comment by firm1** [comment]
Pourquoi je prennent pas une syntaxe toute conne du style :

```
=[auteur]
> Aux âmes biens nées ...
>
```

En sachant qu'on peut écrire aussi

```
=[auteur](url_source)
> Aux âmes biens nées ...
>
```

**Comment by cgabard** [comment]
Pourquoi mettre un = ?

**Comment by firm1** [comment]
Pour différencier de la syntaxe du lien. On peut même ce qu'on veut (et qui arrange les autres syntaxes.)

En fait, mon code précédent devra donner en html : 

``` html
<strong>auteur à écrit</strong>
<blockquote>
Aux âmes biens nées ...
</blockquote>
```

et

``` html
<strong>auteur à <a href="url_source">écrit</a></strong>
<blockquote>
Aux âmes biens nées ...
</blockquote>
```

**Comment by cgabard** [comment]
> Pour différencier de la syntaxe du lien. On peut même ce qu'on veut (et qui arrange les autres syntaxes.)

Si tu veux le faire explicitement, ok. Mais en soit je peux me débrouiller sans.

**Comment by firm1** [comment]
Ah bah si tu peux te debrouiller sans, c'est encore mieux, je t'ai sous estimé

**Comment by Coy0te** [comment]
Tenez-moi au courant de la syntaxe adoptée au final. =)

**Comment by cgabard** [comment]
Je n'ai pas le choix de toute façon. Avec ta syntaxe il faut absolument que je passe avant le parsage des liens classiques pour qu'il n'interprete pas ça comme un = suivi d'un liens. Donc si je passe avant je peux faire un truc du genre "si syntaxe de liens juste avant un bloc citation, alors...".

Le seul prob va etre pour le cas ou un type veut réellement faire un liens avant la citation, là je n'ai pas de moyens de faire la différence. Le = peut se justifier ainsi.

**Comment by Coy0te** [comment]
Après, c'est pas courant de vouloir caler un lien sans ponctuation ni saut de ligne, juste avant une citation.

**Comment by cgabard** [comment]
Bin si, si tu veux indiquer la source mais avec un texte différent de celui que l'on génère automatiquement.

Je m'en fout un peu en fait, faut juste me dire ce qu'il faut utiliser

**Comment by Coy0te** [comment]
Ok, donc si la syntaxe de Willard est pas chiante à mettre en place, a priori c'est la plus adaptée.

**Comment by cgabard** [comment]
Je pense pouvoir l'utiliser.

Apres reste la question du html généré. Car le HTML propose l'attribut "cite" aux blockquote pour préciser la source : https://developer.mozilla.org/fr/docs/Web/HTML/Element/blockquote

du coup la syntaxe : 

```
=[auteur](url_source)
> Aux âmes biens nées ...
>
```

devrait générer : 

``` html
<strong>auteur à écrit</strong>
<blockquote cite="url_source">
Aux âmes biens nées ...
</blockquote>
```

non ?

**Comment by SpaceFox** [comment]
On a un moyen simple d'accéder à l'URL source avec cette syntaxe ?

Le 17 janvier 2014 13:50, Christophe Gabard notifications@github.com a
écrit :

**Comment by cgabard** [comment]
Bin c'est au CSS de gérer, non ?

Après si je me fit à ça : http://html5doctor.com/blockquote-q-cite/

il semblerait que le recommandé serait d'encapsuler le blockquote dans une figure et utiliser le figurecaption pour préciser auteur et source. Avec éventuellement l'utilisation de l'attribut cite en plus. Apres lecture cet attribut n'est pas censé etre vraiment utiliser sur le front.

**Comment by firm1** [comment]
> devrait générer :
> 
> ``` html
> <strong>auteur à écrit</strong>
> <blockquote cite="url_source">
> Aux âmes biens nées ...
> </blockquote>
> ```
> 
> non ?

Quand j'essaye ça dans une page, je ne vois aucun endroit ou cliquer pour avoir access à la source

**Comment by cgabard** [comment]
> Quand j'essaye ça dans une page, je ne vois aucun endroit ou cliquer pour avoir access à la source

En effet car le rendu de base des navigateurs ne l'utilisent pas. Mais j'imagine qu'un CSS perso le peu. Dans tous les cas je comprend bien ce que je vois, en fait le rendu devrait être plutot un truc du genre  : 

``` html
<figure>
<blockquote cite="url_source">
Aux âmes biens nées ...
</blockquote>
<figurecaption>-- <a href="url_source">auteur</a></figurecaption>
</figure>
```

**Comment by firm1** [comment]
Et je trouve ce rendu html interessant : 

``` html
<blockquote cite="http://www.imdb.com/character/ch0000672/quotes">
<p>You know the golden rule, don’t you boy? Those who have the gold make the rules.</p>
<footer>— <a href="http://www.imdb.com/character/ch0000672/quotes">Crazy hunch-backed old guy in Aladdin</a></footer>
</blockquote>
```

dont la source Markdown serait : 

``` text
=[Crazy hunch-backed old guy in Aladdin](http://www.imdb.com/character/ch0000672/quotes)
> You know the golden rule, don’t you boy? Those who have the gold make the rules.
>
```

**Comment by cgabard** [comment]
De ce que j'ai lu, le footer dans blockquote est toléré mais pas dans la norme. le gfigure/figurecaption est recommandé (ce qui doit arriver au meme résultat avec le css)

**Comment by firm1** [comment]
J'ai pas tout lu, mais en effet le resultat sera le même, et de ce fait, ton rendu html me sied tout à fait.

**Comment by Coy0te** [comment]
Quand y'a pas d'URL associée à une citation, je traduis en : 

```
=[Crazy hunch-backed old guy in Aladdin]()
> You know the golden rule, don’t you boy? Those who have the gold make the rules.
```

Ou : 

```
=[Crazy hunch-backed old guy in Aladdin]
> You know the golden rule, don’t you boy? Those who have the gold make the rules.
```

**Comment by cgabard** [comment]
Comme tu veux, je peux autoriser les deux si on veut

**Comment by Coy0te** [comment]
Moi je ne veux rien du tout, dis-moi ce qui est le plus logique et/ou ce qui t'arrange, et je le fais. =)

**Comment by cgabard** [comment]
J'ai pas encore codé ça, je m'en fout tres honnetement

**Comment by firm1** [comment]
Vu que vous avez du mal a vous décider, la deuixième proposition (et uniquement celle la) de Coyote me semble plus logique.

**Comment by cgabard** [comment]
sans parenthèse donc ? Ok ça ma va.

Reste la question du html. J'ai demandé à Alex de venir nous donner son avis

**Comment by Alex-D** [comment]
Après avoir lu en diagonale le débat, je confirme que cette solution est la bonne :
https://github.com/Taluu/ZesteDeSavoir/issues/84#issuecomment-32604027

A ceci près que les "--" sont de la mise en forme et il s'agit donc de CSS et non à mettre en brut dans le code.

Mais je confirme que le coup du footer est déprécié depuis un an à peu près si mes souvenirs sont bons.

**Comment by cgabard** [comment]
Pour la syntaxe, vu que toutes les legendes sont placés en dessous, pourquoi ne pas faire pareil ?

```
> Mon texte
Source : firm1
```

ou avec le liens : 

```
> Mon texte
Source : [firm1](http://LURLSource)
```

?

**Comment by cgabard** [comment]
Dans tous les cas je genererais comme indiqué ici : https://github.com/Taluu/ZesteDeSavoir/issues/84#issuecomment-32604027

**Comment by Coy0te** [comment]
J'allais déjà dans ce sens au début, je trouve ça plus logique ainsi.

**Comment by cgabard** [comment]
Normalement ça arrive dans la prochaine PR. En attendant que vous y trouviez un bug, je ferme
