### ISSUE TITLE
Ecrasement lors d'une édition simultanée

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#843]
Lorsque deux auteurs éditent un même extrait "en même temps", le dernier qui enregistre écrasera le texte de l'autre.

Or, vu l'issue #171 nous n'avons aucun outil de gestion de conflit. Et de toute façon, la conception actuelle de l'archi ne nous permet pas de remonter les conflits (puisque pas de branches).

L'idée la plus simple est de mettre un lock / message préventif pour que les contributeurs soient prévenus de la présence d'un autre membre sur le même extrait.

Le problème est encore plus important sur les articles puisque ça revient à être un simple extrait, donc le dernier qui save dégage toute modif qui aurait pu avoir lieu entre le début et la fin de son édition (temps de rédaction donc).

**Comment by artragis** [comment]
Mon idée serait d'ajouter un champ chaché au formulaire avec le hash du dernier commit à l'ouverture.
Si ce hash est différent lorsqu'on essaie de modifier, on dit "y'a un problème".

**Comment by pierre-24** [comment]
Comme @Alex-D l'as dit sur IRC, je suis pour l'idée d'un "une version plus récente existe", avec l'affichage de la version plus récente en question.

**Comment by Alex-D** [comment]
> Mon idée serait d'ajouter un champ chaché au formulaire avec le hash du dernier commit à l'ouverture.

C'est ce qui est fait sur les forums, MP, etc. pour dire "y a eu un message". Tu peux peut-être t'en inspirer :)

**Comment by artragis** [comment]
Je prends donc le dev à mon compte. Si @Eskimon  ou autre peuvent me mettre en assignee?
J'essaierai de rendre une copie vendredi.

**Comment by Alex-D** [comment]
Ca pourrait être intéressant d'afficher un diff entre la version qu'on tente d'enregistrer et la dernière version enregistrée, au moment où on a ce fameux message préventif :)

**Comment by artragis** [comment]
selon le temps que ça demande, je le ferai. C'est une idée que j'ai aussi. Et j'ai vu comment fonctionne les formulaires, ça devrait aller de ce point de vue. Mais j'ai envie de tester proprement.

**Comment by Alex-D** [comment]
Le système de diff est déjà utilisé (pas propre niveau style car je n'ai rien fait à ce niveau) pour les diff entre les versions. Je pense que tu pourras t'en inspirer sans trop te casser la tête :)

**Comment by artragis** [comment]
oui, c'est pour ça que je n'exclue pas la possibilité. Comme je sais que côté front tu as tout factorisé et que j'ai pu constater que côté back il n'y avait pas des choses monstrueuses à faire, je laisse cette possibilité ouverte, mais en soit elle risque d'être prise pour une évolution et comme on est en freeze, j'ai peur que ça passe pas.

**Comment by Alex-D** [comment]
J'avais oublié ce freeze... laisse de côté cette idée pour l'instant alors.

**Comment by firm1** [comment]
C'est bien comme ça que c'était imaginé : prévenir l'utilisateur que quelqu'un a déjà modifié le fichier qu'il essaye de modifier lui même.

Par contre il y'a une zone d'ombre dans la solution technique exposée ici. Si on par du principe que le **hash du commit** est la clé de vérification d'une mise a jour ou non, étant donné qu'un hash est crée a chaque modification de n'importe quelle contenu lié au tutoriel, on risque de se retrouver avec ce message d'avertissement même si quelq'un modifie un extrait différent du mien.

Cas pratique : mon co-auteur bosse sur la partie 1 et mon sur la partie 2, à chaque fois que je modifie un truc, il aura un message d'avertissement parce que le hash du commit à changé.

Partant de là on voit très vite la limitation imposé par le hash d'un commit.

La clé doit donc être lié aux introductions, conclusions et extraits. Dans l'idéal la clé doit être commune.

La dernière fois que j'y ai réfléchi, j'en suis resté aux possibilité suivantes (comme clé) :
- crée un champ update pour avoir la date de maj se baser dessus comme clé : l'inconvénient était qu'on rajoute des champs dans la bd alors que la vision a terme est de ne plus passer par la BD pour la gestion des tutoriels/articles.
- utiliser la date de mises à jour du fichier (introduction.md, conclusion.md, extrait.md) en regardant les propriétés du fichier : je ne sais plus si j'avais un inconvénient pour cette solution, mais je me suis posé une questions restée en suspens, qui est : "est-ce que la date reste interopérable en fonction de l'os ?"
- utiliser un hash md5 des fichiers commités : l'inconvénient était le temps de calcul de la somme md5 pour un fichier. La solution est valable, mais si on peut trouver mieux, pourquoi pas.

Concernant la visualisation du diff, j'aimerai bien que ce ne soit pas implémenté dans le cadre de cette issue, tant que les diff ne sont pas designé. ça foutrait en l'air l'expérience utilisateur pendant la rédaction.

**Comment by artragis** [comment]
Comme clef, j'avais deux idées dont une qui recoupe les tiennes :
- utiliser un hash md5 des fichiers commités 
- utiliser le dernier hash md5 du commit qui a changé le fichier en question.

Dans le premier cas, le calcul du hash md5 peut être lent, et encore, je ne vois pas trop le problème, puisqu'on est en écriture de tuto, être à 1 sec et 100 milième au lieu de 1 sec c'est pas grave, contrairement aux problématiques de navigation en lecture.

Dans le cas du "obtenir le dernier commit qui modifie", ça demande quand même une utilisation poussée de git et si on doit changer le système plus tard, ça risque de compliquer encore les choses, amha.

**Comment by firm1** [comment]
> Dans le cas du "obtenir le dernier commit qui modifie", ça demande quand même une utilisation poussée de git et si on doit changer le système plus tard, ça risque de compliquer encore les choses, amha.

C'est surtout que cette option en plus d'être plus lente que la première est necessairement plus complexe à dev et maintenir.

Pour la solution du hash md5, le fait qu'on soit en écriture en effet diminue les risques. Mais étant donné que je n'ai aucune n'idée du temps d'execution de ça (si c'est bien comme ça qu'on fait) : 

``` python
import hashlib
fichier = open("/my/file", 'rb')
    m = hashlib.md5()
    while True:
        d = fichier.read(8096)
        if not d:
            break
        m.update(d)
    print m.hexdigest()
```

Je ne sais pas trop. Si on est en dessous de 200ms je partirai bien la dessus en sachant qu'au pire, vu que la valeur n'est pas stockée, on peut changer ce paramètre si on trouve une meilleure soluce.

**Comment by artragis** [comment]
y'a pas une vraie méthode de hash md5 en python, style celle qu'on a en php?
au pire, on met un json temporaire à la racine du dossier des tutos avec tous les md5.
Mais ça m'étonnerait que ça prenne longtemps pour nos fichiers, ils ne sont pas si gros que ça.

**Comment by Alex-D** [comment]
> Mais ça m'étonnerait que ça prenne longtemps pour nos fichiers, ils ne sont pas si gros que ça.

Je pense aussi que ça devrait être assez rapide.

A en voir [ce topic](http://stackoverflow.com/questions/3431825/generating-a-md5-checksum-of-a-file), il n'y a pas de méthode Python dans lib standard pour faire un MD5 de fichier. Faut visiblement nécessairement se construire sa petite fonction.

**Comment by firm1** [comment]
> y'a pas une vraie méthode de hash md5 en python, style celle qu'on a en php?

Il faut creuser, et trouver la plus optimisée, là j'ai juste recopié le premier resultat google que j'ai trouvé.

> au pire, on met un json temporaire à la racine du dossier des tutos avec tous les md5

Si on peut limiter le nombre de fichier à lire ça serait génial je pense. faut juste que quelqu'un prenne un extrait et calcule sa somme md5, si le temps d'execution est négligeable on part là dessus.

**Comment by artragis** [comment]
A fermer.
