### ISSUE TITLE
Sidebar "vide" donne juste un carré gris bizarre...

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#845]
C'est pas un bug en soit, mais comme l'a remarqué [quelqu'un sur le forum](http://zestedesavoir.com/forums/sujet/240/affichage-bizarre-apres-linscription/), certaines pages comme celle après inscription ont une sidebar vide, qui donne du coup un carré gris pas très beau...

![image](https://cloud.githubusercontent.com/assets/1549952/3255141/d6089072-f205-11e3-9d41-06cd0e89adad.png)

**Comment by Alex-D** [comment]
Ah, il manque juste une classe et un block, suffit de regarder dans la page login par exemple.

Au passage : faut changer la phrase par

> Vous allez recevoir un email contenant un lien d'activation. Veuillez cliquer sur ce celui-ci avant de vous connecter.

**Comment by Alex-D** [comment]
Je prends.

**Comment by Eskimon** [comment]
Je confirme, ca roule !
