### ISSUE TITLE
Les images n'ont pas de limite en largeur

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#846]
Les images ne comportant pas de légendes sont simplement des balises `<img />`, sans la `<figure>` autour... Cela a pour conséquence de faire dépasser les images de la page, puisque le `max-width: 100%;` est uniquement [appliqué sur les images dans les figures](https://github.com/zestedesavoir/zds-site/blob/beta-0.2/assets/scss/_all-supports.scss#L1600). A corriger côté Markdown je suppose

**Comment by Alex-D** [comment]
Non, c'est du style pour le coup, donc front.

Faut simplement ajouter le max-width pour les images qui sont dans `.article-content`

**Comment by sandhose** [comment]
Mais _toutes_ les images sont pas censés être wrappé dans des figures ? C'est un peu bizarre que la structure change si il y a une légende ou non...

**Comment by Alex-D** [comment]
La figure permet sémantiquement (entre autres) de lier une figure à son titre.

Si tu mets tout dans des figures, les images inline ne le seront plus.

Du coup, c'est vraiment du front, simple changement dans le CSS à faire.

**Comment by sandhose** [comment]
Ok du coup je m'en occupe rapidos
