### ISSUE TITLE
Ajouter à la fin du message du premier post les réponses utiles

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#848]
http://zestedesavoir.com/forums/sujet/217/ajouter-a-la-fin-du-message-du-premier-post-les-reponses-utiles

Proposition de Clem:

> Je pense qu'il serait intéressant qu'en dessous du message principal, on ait des liens qui pointent vers les posts qui ont aidé l'auteur.
> 
> ça permets d'avoir le problème -> les solutions utiles -> et ensuite le reste de la discussion si besoin. je parle bien ici d'afficher juste les liens vers les messages pas tout le contenu.

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis plus d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.
