### ISSUE TITLE
[Markdown] Limiter les titres à 4 niveaux

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#85]
Pour réserver les h1 et h2 aux titres et soustitres de tutos, qui ne sont pas dans les textes markdown, il est necessaire d'interdire l'utilisation des h1 et h2 ailleurs.

Une question reste en suspend : Est ce que le décalage h1 dans markdown -> h3 html ne doit pes etre fait systématiquement ? Pour le rendu des tutos il le faudrat probablement, autant le garder sur le forum, non ?

**Comment by firm1** [comment]
Perso, je suis d'avis, que lors de la conversion markdown -> html sur tout le site, on effectue le mapping suivant : 

``` text
# -> <h3></h3>
## -> <h4></h4>
### -> <h5></h5>
#### -> <h6></h6>
```

Pour ce qui sera de la conversion markdown -> pandoc, on fera le mapping suivant.

``` text
Titre de Partie -> #
Titre de chapitre -> ##
# -> ###
## -> ####
### -> #####
#### -> ######
```

**Comment by cgabard** [comment]
Yep je suis pour aussi. Ça permet ainsi aussi de garder le même style et html si on veut générer une page contenant le tuto en entier.

Convertir systématiquement les # en h3, c'est facile, j'ai vu une extension qui faisait le decalge sytematiquement. Pour décaller de 2, il suffit de la charger 2 fois. Par contre pour empecher les titres 5 et 6, je n'ai pas encore regardé comment je peux faire

**Comment by Coy0te** [comment]
C'est pas jouable d'autoriser tout de même les 5 et 6 (sans les documenter dans notre notice markdown), mais de faire en sorte que leur rendu HTML soit du simple texte ?

**Comment by cgabard** [comment]
C'est à dire ? 

Si je fait juste faire le décalage, avec l'extension, il me semble qu'une 6 reste 6. On peut garder ce comportement. Sinon il faudrait, dans l'idéal que le texte `##### titre6` s'imprime tel quel dans le texte, sans etre parser.

**Comment by cgabard** [comment]
Je viens de checker en vitesse, et je pense que ça va être possible. En faisant un hook tout moche mais ça devrait passer.

**Comment by Taluu** [comment]
> Perso, je suis d'avis, que lors de la conversion markdown -> html sur tout le site, on effectue le mapping suivant :
> 
> ```
> # -> <h3></h3>
> ## -> <h4></h4>
> ### -> <h5></h5>
> #### -> <h6></h6>
> ```
> 
> Pour ce qui sera de la conversion markdown -> pandoc, on fera le mapping suivant.
> 
> ```
> Titre de Partie -> #
> Titre de chapitre -> ##
> # -> ###
> ## -> ####
> ### -> #####
> #### -> ######
> ```

Et faut aussi gérer le cas des soulignements :

``` markdown
Titre
====

Titre
------

Titre
~~

```

Etc ; c'est une spec du markdown après tout (que je trouve plus lisible que de prefixer par des `#` perso)

**Comment by cgabard** [comment]
@Taluu : Oui. En fait la convertion va se faire au niveau html : parcourir l'arbre et transformer h1 en h2, etc. Donc aucun soucis à ce niveau là.

Il faut juste rajouter le fait de l'empecher de convertir les titre 5 et 6 en syntaxe markdown vers les tags html

**Comment by cgabard** [comment]
Fonctionne en local.

J'ai enmpeché les titres 5 et 6 d'etre transformé mais le comportement precedent de python markdown etait normalement que `####### h7` devient `<h6># h7</h6>` alors que moi pour `##### h5` je produis `##### h5`

**Comment by cgabard** [comment]
Il me semble que c'est en prod, je ferme :)
