### ISSUE TITLE
[Articles] Mise à jour de l'article pour la validation

### ISSUE THREAD

**Issue by Taluu** [zestedesavoir/zds-site#850]
Lorsqu'on soumet un article en validation, il est figé. Du coup, si on apporte des modifications, qu'on aimerait inclure lors de la validation du dit article (ex : remarques du validateur), on doit virer son tutoriel de la validation, et le resoumettre à nouveau.

Je pense qu'un petit truc (bouton, lien, ...) pour "mettre à jour le tutoriel en validation à sa dernière version" serait un bon gros plus.

**Comment by Alex-D** [comment]
C'est pour ça qu'il avait été discuté d'avoir trois branches (ou deux) :
- brouillon
- validation
- en ligne

Et de profiter de la force des merges pour faire tout ce qu'il faut bien.

**Comment by Taluu** [comment]
Pas forcément besoin de 3 branches / version... 3 références vers des commits suffisent. Que ce soit un nom de branche, un commit particulier, un tag...

**Comment by firm1** [comment]
+1 Pour baptiste, cette fonctionnalité peut être implémenté à court terme
par le back, sans la gestion des branches dans un premier temps. Elle ne
ferait qu'écraser la référence vers le commit en validation.

**Comment by amorison** [comment]
À noter que le problème est le même pour les tutos, et que les membres non staff ne peuvent même pas virer leur tuto de la validation pour soumettre la nouvelle version.

**Comment by firm1** [comment]
Ça a été corrigé pour les tutoriels, il ne reste plus qu'a le faire pour les articles.

**Comment by gustavi** [comment]
C'est corrigé non ? cf http://i.imgur.com/B8Wg6fr.png

**Comment by firm1** [comment]
Je ne sais pas ce qui a été fait sur les articles de ce coté, mais le MAJ en validation des articles est buguée en ce moment. Je soupçonne donc que quelqu'un a rajouté le bouton, mais sans finir d'implémenter la feature.

Que faire de l'issue ? ça je ne sais pas

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by artragis** [comment]
Déjà opérationnel sur la ZEP 12.
