### ISSUE TITLE
Interface validation, lien profil auteur

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#851]
Dans l'interface de validation des articles (et des tutos ?), le lien sur l'auteur pointe vers le profile de l'utilisateur plutôt que sur l'auteur lui même.

**Comment by Coy0te** [comment]
Je confirme que le bug est aussi présent dans l'interface de validation des tutos.

Par contre (tant qu'on y est), un mini-truc à corriger uniquement sur la page de validation des articles, c'est le lien "Réservé" qui doit être remplacé par "Réserver".

**Comment by Eskimon** [comment]
Nop, l'orthographe est correcte (et debatu :D) car c'est comme si tu disais "Pris par..."
Ou alors on parle pas du meme (ce qui est arrive aussi dans les debats :D )

tu penses auquel sur cette image (qui est vieille et peut pas a jour avec la version actuelle) : ![](https://cloud.githubusercontent.com/assets/761168/3176297/030ef8de-ec04-11e3-96cb-455ed9e66ca2.png)

**Comment by Coy0te** [comment]
C'est un verbe d'action, l'article n'est pas encore réservé. Y'a rien de débattu, d'ailleurs on a déjà corrigé cette orthographe dans la page de validation des tutos. :p

[Edit] je parle du **lien** tout à droite, pas du titre de la colonne.

**Comment by Alex-D** [comment]
Bah en fait il devrait pas être lien... je vais voir ce que c'est que ce bins'

**Comment by Eskimon** [comment]
> [Edit] je parle du lien tout à droite, pas du titre de la colonne.

Je suis d'accord sur ce point.

**Comment by Alex-D** [comment]
Les pages étaient pas au top, c'est corrigé dans la PR ci-dessus (#851).

**Comment by Eskimon** [comment]
Je confirme le comportement sur ma version local, ca semble tout bon, je ferme :)

**Comment by Coy0te** [comment]
C'est déjà en prod, et en effet c'est tout bon ! :)
