### ISSUE TITLE
Mettre à jour côté client les dates relatives

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#853]
Rajouter sur toutes les dates relatives un attribut `data-timestamp` contenant le timestamp de la date, pour ensuite mettre à jour régulièrement (toutes les minutes ?) les dates côté client, avec un peu de JS. Du coup, les "Il y a une seconde" deviendront au fil du temps "Il y a 1/5/10 minutes", et ainsi de suite.

Je sais que ça relève un peu du "gadget", mais si vous êtes d'accord, je peux rapidement m'en occuper

**Comment by firm1** [comment]
ça peut être sympa mais si ça coute quelques chose en perf, je dis non tout
de suite.

**Comment by Alex-D** [comment]
Attendre AngularJS pour faire ça, avec les watch et tout ça sera fait en 3 secondes.

**Comment by sandhose** [comment]
Nan niveau perf ça demande à peu près rien... (Sauf si tu as > 1000 dates sur la même page, et encore...)

**Comment by sandhose** [comment]
Et ok, on attend Angular :)

**Comment by viki53** [comment]
Au passage, pas besoin de data-attribute, les dates devraient être dans des balises `<time>` avec un attribut `datetime`, donc accessibles directement ;)

**Comment by Alex-D** [comment]
C'est pas faux du tout ça ! Je pensais l'avoir mis mais j'ai du le rêver :-°

Faudra qu'on revoit ça @sandhose :)

**Comment by viki53** [comment]
Si vous voulez une fonction de date relative toute faite, c'est cadeau : http://www.meetmefree.eu/assets/js/v1-conversation.js (fin de fichier)

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis plus d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.
