### ISSUE TITLE
Article hors-ligne : lien vers la version en ligne

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#854]
Dans la page d'un article hors-ligne (et déjà publié), la sidebar ne propose pas de lien pour aller voir sa version en ligne, alors que ce lien est présent dans la sidebar des tutos hors-ligne.

Pourquoi cette différence existe-t-elle ?

**Comment by Alex-D** [comment]
Les interfaces ne sont pas les mêmes, du coup c'est un simple oubli :)

**Comment by Alex-D** [comment]
Je m'en occupe tout de suite.

**Comment by firm1** [comment]
Fixé.
