### ISSUE TITLE
Edition d'un commentaire de tuto

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#86]
Quand je suis dans les commentaires d'un tuto, et que je clique sur "Editer" sur [un de mes commentaires](http://zestedesavoir.com/tutoriels/9/3d-temps-reel-avec-irrlicht/?page=1#p49), la page d'édition s'ouvre bien, mais contient deux bugs : 
- un clic sur le bouton `Annuler` ne me renvoie pas à la page des commentaires, ça recharge juste la page d'édition du commentaire ;
- le fil d'Ariane rend un peu bizarrement (il indique "Forums", et il contient 4 séparateurs d'affilée, voir image ci-dessous).

![](http://sdz-upload.s3.amazonaws.com/prod/upload/ariane.png)

Par ailleurs, rien à voir, mais on n'a pas de droits de modération dans les commentaires de tuto ? Je peux masquer (??) et éditer mes propres commentaires, rien d'autre.

**Comment by Coy0te** [comment]
- Le bug du bouton annuler est bien résolu.
- Le fil d'Ariane est déjà un peu moins crade, mais il reste encore un double > >.
- La question sur les droits de modération dans la liste des commentaires d'un tuto tient toujours.

**Comment by firm1** [comment]
> Le fil d'Ariane est déjà un peu moins crade, mais il reste encore un double > >.

ça c'est parce que je n'ai pas encore redemarrer le serveur en prod. Je m'en occupe dès que je fixe un certain patch qui traine un ptit bug.

> La question sur les droits de modération dans la liste des commentaires d'un tuto tient toujours.

Je n'avais pas donné les droits suffisant au groupe staff. C'est réglé normalement.

**Comment by Coy0te** [comment]
> Je n'avais pas donné les droits suffisant au groupe staff. C'est réglé normalement.

En effet, ça marche. On ne peut pas masquer le premier commentaire d'un tuto par contre, mais ça j'imagine que c'est un relicat du fait qu'on a copié le système d'un sujet de forum, dans lequel c'est pas possible de masquer l'OP.

**Comment by firm1** [comment]
> mais ça j'imagine que c'est un relicat du fait qu'on a copié le système d'un sujet de forum, dans lequel c'est pas possible de masquer l'OP.

Bien vu, je vais faire un fixe global dans la soirée pour ça.

**Comment by firm1** [comment]
C'est bon tout est fixé, je ferme.
