### ISSUE TITLE
Desactiver lien d'activation une fois clique

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#861]
[Via Addel](http://zestedesavoir.com/forums/sujet/255/notification-de-bienvenue-recu-plusieurs-fois/)

Le mail de confirmation s'envoi bien, quand on clique sur le lien ça fonctionne et on reçoit bien le message de bienvenue de Clem. Mais si je clique plusieurs fois sur le lien du mail je reçois à chaque fois le même message de bienvenue et le mail qui va avec.

**Comment by ArnaudCalmettes** [comment]
Je place ça pour la milestone "bêta publique". Ça semble potentiellement dangereux.

**Comment by Eskimon** [comment]
Merge ! On ferme ici ou on attend que quelqu'un refasse un dernier test quand ce sera en prod ?

**Comment by Taluu** [comment]
Comme tu veux, j'étais prêt à fermer :)
