### ISSUE TITLE
Impossible d'envoyer un MP à un membre avec des virgules dans le pseudo

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#862]
En essayant d'envoyer un MP a un membre tel que `Gwenn, not banned yet` on a un message d'erreur, car la virgule est censé être le séparateur.

**Comment by Alex-D** [comment]
Il faudrait interdire les virgules dans les pseudos selon moi.

**Comment by sandhose** [comment]
+1, et les espaces aussi, car cela posera problème pour l'autocompletion

**Comment by Eskimon** [comment]
Bon, dans ces cas là il faudrait faire une petite liste des caractères interdit et ca pourrait vite etre reglé...

**Comment by Coy0te** [comment]
Les pseudos contenant des caractères à la con, c'est chiant à lire, rien que ça ça devrait être suffisant pour les interdire. Interdire la ponctuation me semble le minimum.

**Comment by Eskimon** [comment]
Donc si on devait lister:
,;:!?. (et l'espace)

**Comment by Coy0te** [comment]
Et les accolades, les crochets, les parenthèses, la barre verticale, les guillemets, les slashs... Après, je sais que tout le monde n'est pas de mon avis sur ce sujet, je préfère laisser les autres s'exprimer. =)

**Comment by Alex-D** [comment]
Bah, slash c'est gênant dans l'url du membre par exemple :D

Au pire on autorise juste : [a-zA-Z0-9_-]+

Non ?

**Comment by sandhose** [comment]
+1

Mais du coup rajouter quand même 2/3 caractères (l'`@`, par exemple ? Et je pense que le `.` on peut l'autoriser aussi)

**Comment by Coy0te** [comment]
Pour info, c'est là qu'on en avait parlé : 
=> https://github.com/zestedesavoir/zds-site/issues/54#issuecomment-31639643

Sur SO par exemple, ils interdisent certains caractères mais autorisent tout l'utf-8 (langues étrangères, etc.).

**Comment by Alex-D** [comment]
Ok donc on fait plutôt une blacklist qu'une whitelist.

On est donc à `,;:!?.\/ @.`

**Comment by SpaceFox** [comment]
N'oubliez pas les accents :)

2014-06-13 0:06 GMT+02:00 Alexandre Demode notifications@github.com:

**Comment by Alex-D** [comment]
A bannir ? Ou à autoriser ? Si c'est à autoriser vu qu'on partirai visiblement sur une blacklist du coup c'est bon.

**Comment by SpaceFox** [comment]
A autoriser. Nos messages se sont croisés.

2014-06-13 0:10 GMT+02:00 Alexandre Demode notifications@github.com:

**Comment by Eskimon** [comment]
Les espaces aussi foute la merde... http://zestedesavoir.com/forums/sujet/533/erreur-404-lors-de-lenvoi-dun-mp/

**Comment by Eskimon** [comment]
Apparemment l'ajout de l'utilisateur avec espace _après_ la création du MP fonctionne

**Comment by Eskimon** [comment]
En attendant un consensus, j'ai pris la décision d'interdire la virgule dans la création de compte parce qu'elle nous embêtera dans l'envoi de MP et qu'elle a peu de sens dans un pseudo (oui je sais décoration toussa, mais dans ce cas mettez vous d'accord pour trouver une solution pérenne)

Je rappel qu'on a deja des utilisateurs avec des espaces et des @

**Comment by firm1** [comment]
Il faudra scripter la migrations des comptes (changements des virgules,
etc. ) et renvoyer dans la foulée (toujours via script) le nouveau pseudo
en expliquant pourquoi on l'a changé.

**Comment by Eskimon** [comment]
> Il faudra scripter la migrations des comptes

Si la MEP ne tarde pas ce sera possible sans, aucun compte n'utilise de virgules pour le moment.

**Comment by Eskimon** [comment]
D'une maniere plus generale, il serait bon de statuer **rapidement** la dessus plutot que d'attendre que les problemes de pseudos bizarre nous tombe dessus. Je rappel que point de vue dev' c'est assez trivial et que donc ca fait un mois qu'on attend juste pour statuer sur ce qui passe ou non !

**Comment by Coy0te** [comment]
Est-ce qu'on peut demander à nohar de trancher ? 

Moi je veux bien réitérer ma position et reproposer qu'il faudrait interdire toute ponctuation, parenthèses, accolades et autres saloperies dans les pseudos, mais ça ne fera pas avancer le schmilibiliblic pour autant...

**Comment by firm1** [comment]
> Si la MEP ne tarde pas ce sera possible sans, aucun compte n'utilise de virgules pour le moment.

Je fais une MEP ASAP sauf si quelqu'un le fais avant moi. Mais je vais quand même écrire le script a coté, ça ne mange pas de pain et ça pourrait reservir.

> D'une maniere plus generale, il serait bon de statuer rapidement la dessus

Le seul souci technique insurmontable ici c'est la virgule dans le pseudo.

Je ne vois donc aucune raison valable d'interdire les autres caractères.

En résumé : interdiction de la virgule et c'est bon.

**Comment by Eskimon** [comment]
> En résumé : interdiction de la virgule et c'est bon.

Dans ces cas là cette issue est close... Je laisse @ArnaudCalmettes ou @SpaceFox trancher sur tout ca et fermer si nécessaire (sachant que cette histoire de virgule est réglé quelques messages plus haut)

**Comment by ArnaudCalmettes** [comment]
Conclusion, contentons-nous de blacklister `,;:!?.\/@.` (ainsi que les espaces).

**Comment by Eskimon** [comment]
Donc les pseudos comme @dri1 et Flori@n.B deviennent Adri1 et Florian.B ? Il va y avoir des déçus a cause d'une virgule :D On fait quoi de tout les caractères utf-8 bizarre comme ♾ ou ♥ ?

**Comment by amorison** [comment]
si c'est plus pratique de virer le `@` faites donc. Mais mettez moi un `a` minuscule alors svp. :p

**Comment by Alex-D** [comment]
Les espaces on peut les garder il me semble. Y a un bug dans le front, mais en dehors de ça, ça a l'air de fonctionne (y a un bug à l'inscription aussi).

**Comment by artragis** [comment]
d'après [ce diff](http://zestedesavoir.com/forums/sujet/623/mises-en-production-pendant-la-beta-publique/?page=2#p13181) ça a été corrigé.

**Comment by Eskimon** [comment]
Le bug a l'inscription je me demande si c'est pas du aux erreurs 500 qui traînait a ce moment la... Sur ma version locale j'en ai pas eu quand j'ai energistre un pseudo a espace (faudrait que je ressaie avec une base MySQL)

**Comment by SpaceFox** [comment]
On devrait garder les espaces, vu le nombre d'utilisateurs qui en ont !

Quelqu'un est sur ce bug sinon ?

**Comment by artragis** [comment]
Comme je suis rentré de vacances, je m'y mets dessus aujourd'hui. Merci de m'y assigner.

**Comment by artragis** [comment]
juste une chose : comme il y a eu pas mal de taffe dessus : quel est le bug en soit que je dois corriger?
- l'interdiction de s'inscrire avec des ,;/?. 
- l'envoie de Mp à une personne dont le nom est `blabla,blabla`
- l'envoie de MP à plusieurs destinataires dont l'un d'entre eux est `blabla,blabla`?

**Comment by Eskimon** [comment]
Pour les deux derniers points, ils ne peuvent pas arriver car on ne peut pas s'inscrire avec une virgule dans le pseudo.

**Comment by SpaceFox** [comment]
> Pour les deux derniers points, ils ne peuvent pas arriver car on ne peut pas s'inscrire avec une virgule dans le pseudo.

Du coup je ne comprends pas où est le bug ?

Est-ce qu'il ne faut pas se contenter d'interdire les virgules dans les pseudos, que ce soit à l'inscription comme au changement de pseudo ?

**Comment by artragis** [comment]
c'est ça que je me demande : aujourd'hui il y a eu des fix [ici](http://zestedesavoir.com/forums/sujet/623/mises-en-production-pendant-la-beta-publique/?page=2#p13181) ou [là](https://github.com/zestedesavoir/zds-site/issues/1294).

Du coup je ne sais plus trop de ce que je dois corriger. Personnellement je veux bien m'y mettre, j'ai du temps et maintenant que zds remarche sur windows, c'est opé. Mais j'ai l'impression que le bug est globalement corrigé et que seules les utilisations à la marge sont mal gérées.

**Comment by SpaceFox** [comment]
Ah ben tant mieux alors, contentons-nous de corriger les utilisations à la marge :)

**Comment by artragis** [comment]
Utilisation qui est?
A noter que les problèmes de front (auto complétion) ne sont pas inclus dans cette issue mais dans une toute autre.

**Comment by SpaceFox** [comment]
J'en sais pas plus que toi :(

**Comment by artragis** [comment]
Donc apparemment il n'y a plus rien à faire. On clos quitte à rouvrir quand un vrai bug arrivera?

**Comment by SpaceFox** [comment]
OK pour moi.
