### ISSUE TITLE
Page blanche apres "quitter la conversation"

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#863]
[Via addel]()

Le lien "quitter la conversation" renvoi vers une page blanche.

Il doit manquer une redirection apres l'action...

**Comment by Alex-D** [comment]
Il y a pourtant :

```
return redirect(reverse('zds.mp.views.index'))
```

C'est louche.

**Comment by Eskimon** [comment]
Avant de rapporter ici, j'ai teste et je confirme bien ce comportement...

**Comment by Alex-D** [comment]
Je ne remet pas en doute le test, mais l'illogisme du code par rapport au comportement attendu.

**Comment by Eskimon** [comment]
En local je reproduit ca me donne une erreur 405 (Méthode de requête non autorisée)...

**Comment by Eskimon** [comment]
Dit c'est normal que dans plusieurs formulaires je trouve un truc "mathod" au lieu de "method" ?

(Ca marche pas mieux en mettant method, mais au moins j'ai pu l'erreur 405)

**Comment by Alex-D** [comment]
Ca n'est pas normal non :(

Je vais faire un grep pour corriger ça.

**Comment by Eskimon** [comment]
erf, il n'y a que quelques occurence (et elles sont en prod aussi) dans les MP, mais ca change rien apparemment...

**Comment by Alex-D** [comment]
Après test en local, je n'ai pas d'erreur, juste que ça ne fonctionne pas : ça ne quitte pas la conversation :(

**Comment by ShigeruM** [comment]
Si il y a bien une 405. Mais du coup ça ne va pas plus loin et la view ne
fait rien.
Le 13 juin 2014 00:41, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
Vous testez en prod ou avec mon patch #888 ?

**Comment by ShigeruM** [comment]
Je parlais en local, mais je n'avais pas encore vu ton patch désolé.
Le 13 juin 2014 00:44, "Alexandre Demode" notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
Après test en local de cette issue, je n'ai aucune erreur du type 405 mais je suis toujours dans la conversation privée.
