### ISSUE TITLE
Pas de lien de regénération de token quand le token a expiré

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#864]
C'est certainement une regression, car avant le merge d'integration, sur la page d'activation d'un profil, si le token avait déjà expiré, on avait un lien pour le regenerer.
Aujourd'hui on nous propose juste de se réinscrire.

**Comment by Alex-D** [comment]
Voilà m'sieur !

**Comment by Eskimon** [comment]
Après mon test en local, ca plante...
J'ai bien la page me proposant de renvoyer le jeton, mais quand je click j'ai le droit à un "TemplateDoesNotExist at /membres/envoi_jeton/"

Du coup je change les labels de Front vers Back (puisque le souci de front est reglé)

Edit Alex : j'ai supprimé la stacktrace pour y voir plus clair :)

**Comment by Alex-D** [comment]
Juste avec ça : 

```
TemplateDoesNotExist at /membres/envoi_jeton/
```

Y en a assez : il manque une template :(

**Comment by firm1** [comment]
C'est fixé.
