### ISSUE TITLE
Articles en bêta visibles

### ISSUE THREAD

**Issue by jcval** [zestedesavoir/zds-site#866]
Les articles en cours de rédaction sont considérés comme "En ligne" dans le profil d'un membre. On peut en voir le titre, mais on ne peut pas en afficher le contenu (erreur 500).

EDIT : source : http://zestedesavoir.com/forums/sujet/256/articles-crees-par-un-membre/

**Comment by Alex-D** [comment]
Corrigé et en prod :)
