### ISSUE TITLE
Conservation d'objets en mémoire ?

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/zds-site#87]
Est il possible, avec Django, de conserver des objets en mémoire ? Avec des variables globales ?

Le truc est qu'actuellement, le convertisseur markdown -> html est reconstruit entièrement (parseur et toutes les extensions) à chaque demande de conversion alors qu'il ne conserve pas (ou peu) de variables d'etat (et qui peuvent être reset dans tous les cas).

On gagnerait en perf de ne pas systématiquement tout recharger

**Comment by firm1** [comment]
Dans les forums, la conversion d'un message écrit en markdown vers sont équivalent html ne se fait que lors de la création/edition du message. Pour l'affichage, il existe un [champ dédié](https://github.com/Taluu/ZesteDeSavoir/blob/master/zds/utils/models.py#L141) qui conserve le contenu en html et c'est celui là qui est utilisé pour l'affichage, donc plus de conversion lors de la lecture.

Cepdendant, étant donné que le markdown n'est pas encore stable, tout est encore recalculé, mais dès qu'on se stabilise, il faudra juste charger le contenu du champ html dans le template (5 sec).

**Comment by cgabard** [comment]
Ok !

**Comment by Coy0te** [comment]
C'est mieux, certes, mais ça ne change pas grand chose au fait que réinstancier un parseur à chaque fois qu'un mec envoie un post, c'est pas une super idée.

**Comment by cgabard** [comment]
Indeed. Du coup, possible ou non ? j'ai pas cherché ni tester remarque...

**Comment by Coy0te** [comment]
@firm1 : dans une appli Java EE, y'a un application scope pour caler les trucs qu'on a pas envie de recharger à foison. Le truc qui s'appelle settings dans django, c'est son équivalent ou ça a rien à voir ?

**Comment by firm1** [comment]
> C'est mieux, certes, mais ça ne change pas grand chose au fait que réinstancier un parseur à chaque fois qu'un mec envoie un post, c'est pas une super idée.

Hmm ... comment tu veux transformer le texte du monsieur en html si, lorsqu'il envoi un post, tu ne le converti pas ?  Re-instancier le parseur ne veut pas dire grand chose, vue que le parseur n'est qu'un ensemble de fonction.

**Comment by cgabard** [comment]
> Hmm ... comment tu veux transformer le texte du monsieur en html si, lorsqu'il envoi un post, tu ne le converti pas ? Re-instancier le parseur ne veut pas dire grand chose, vue que le parseur n'est qu'un ensemble de fonction.

Non mais là on crée pleins d'objets à chaque fois : tout le parseur et les extensions associés. Entre autre on recompile toutes les regexp pendant cette initialisation. Actuellement on l'utilise en mode fonction mais il est possible de créer un objet et de lui passer les différentes chaines à convertir via une methode. On éviterait de ré-initialiser à chaque fois.

**Comment by firm1** [comment]
Ah, stocker les les regxp déjà compilées du coup. C'est faisable oui, mais il faut trouver comment :-)

**Comment by cgabard** [comment]
Ce n'est pas que les regxp. Mais en gros tout le parseur pourrait etre conservé en mémoire évitant de le reconstruire.

**Comment by cgabard** [comment]
@Coy0te : Comment ton application scope de JEE gère les requetes concurentes ? En fait apres lecture cette pratique semble très fortement déconseillée car le serveur pouvant faire plusieurs appels systématiquements, on risque d'avoir des conflits : En gros que ce passe t'il si la methode parse() est appelé sur l'objet alors que l'objet est déjà en cours d'utilisation par un autre ?

**Comment by cgabard** [comment]
Ou alors il faut explicitement faire en sorte de locker l'objet en attendant. Pour le coup, j'attendrais bien de voir si des prob de perfs se posent avant de jouer à ça.

**Comment by SpaceFox** [comment]
En fait Java EE utilise un pool de connexions, et pour ce genre d'objets
soit tu as une instance par thread dans le pool, soit tu as un gros
*synchronize
*dessus (ce qui ne me paraît pas pertinent pour un parseur).
Donc tu crées ton objet quand tu lances le thread, et tu le réutilise pour
toutes les connexions du thread. Chaque thread ne traitant qu'une connexion
à la fois, pas de problème de concurrence.

Cela dit, la concurrence mal gérée est l'une des principale cause d'échecs
et de surconsommation des projets Java EE. J'ai vu des applications
mono-utilisateurs à cause de ça...

Le 15 janvier 2014 18:08, Christophe Gabard notifications@github.com a
écrit :

**Comment by cgabard** [comment]
Oui c'est ce que j'ai lu aussi. En gros la moins mauvaise chose est d'en faire un par thread. Mais le gain en devient minime vu que la génération ne sera faite qu'aux edition/création, pas aux lectures.

**Comment by SpaceFox** [comment]
Tout dépend de la charge et surtout du temps d'initialisation du parseur.
Si c'est 1 seconde à chaque fois, c'est toujours chiant d'attendre 1
seconde inutile pour poster...

Le 15 janvier 2014 18:18, Christophe Gabard notifications@github.com a
écrit :

**Comment by cgabard** [comment]
Je vais peut être instrumenter ça pour permettre a willy de le mesurer, on verra bien.

**Comment by SpaceFox** [comment]
Est-ce que cette question est toujours d'actualité ?

**Comment by Eskimon** [comment]
Plop, apres 2 mois d'utilisation du site, il faut laisser ce ticket ouvert ou pas ?

**Comment by cgabard** [comment]
Je pense qu'on peut fermer, ce n'est pas ce genre de chose qui semble être le goulot d'étranglement du code.
