### ISSUE TITLE
Indiquer la taille des fichiers téléchargeables

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#872]
[Via Jeekwiz](http://zestedesavoir.com/forums/sujet/268/indiquer-la-taille-des-fichiers-telechargeables/)

C'est qu'un détail mais ce serait bien d'afficher la taille des fichiers téléchargeables à coté du lien (PDF, HTML, EPUB, Archive).

**Comment by SpaceFox** [comment]
Si tant est qu'on dispose de cette taille à priori, ce dont je ne suis pas
certain.

**Comment by Eskimon** [comment]
Google me dit : os.path.getsize(path)

Apres je sais pas si les liens sont en BDD ou pas etc... car ca pourrait etre judicieux d'ajouter un champ pour la taille du fichier pour eviter de la recalculer a chaque affichage...)

**Comment by Alex-D** [comment]
Les fichiers sont générés à la validation, donc on peut mesurer leur taille :)

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis plus d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.

**Comment by pierre-24** [comment]
Raaah, c'est con, ça aurait pris 30 secondes à faire si je l'avais su ^^

**Comment by gustavi** [comment]
@pierre-24 je peux m'occuper de ça si tu n'as pas commencé ?

**Comment by pierre-24** [comment]
Je t'en prie ;)
