### ISSUE TITLE
Phrases aleatoires sur la home

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#873]
[Via Coyote](http://zestedesavoir.com/forums/sujet/267/retour-des-phrases-aleatoires/)

Où sont passés les petits slogans aléatoires affichés sur l'accueil ?

C'était sympa comme petite feature, même si ça manquait d'intégration. Maintenant qu'on a Clem, c'est pas envisageable d'intégrer ça dans une bulle de BD ou un truc du même genre ?

**Comment by Alex-D** [comment]
Les phrases sont revenues \o/
