### ISSUE TITLE
pas de design sur le premier message des pages suivantes

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#876]
Actuellement, quand on passe à la page suivante d'un topic , le premier message est en fait le dernier message de la page précédente, sauf qu'on arrive pas à le distinguer car il a le même design que les autres messages.

Avant, le message était "grisé" pour mettre en évidence le fait qu'il provient de la page précédente, il faudrait rétablir ce comportement.

**Comment by Alex-D** [comment]
Comment je peux tester que c'est un message dupliqué ?

Je dois le tester par rapport à page + position du message dans la page (genre au premier tour de boucle) ?

**Comment by firm1** [comment]
> Comment je peux tester que c'est un message dupliqué ?

solution : `class="{% if forloop.first and nb > 1 %}nom-de-classe-grisante{% endif %}"`

Pour l'explication, ici, tu teste si tu es dans le premier élément de ta boucle et si le nombre de pages est supérieur à 1.

**Comment by Alex-D** [comment]
Ok d'ac, ça me va :)

J'y planche de suite.

**Comment by Alex-D** [comment]
Fait : à MEP / tester

**Comment by Eskimon** [comment]
Sur ma version locale ca roule !

**Comment by Eskimon** [comment]
Je rouvre car je viens de voir que ce style n'est pas appliqué dans les réactions sur les articles (et les tutos ?)

On peut le voir ici http://zestedesavoir.com/articles/1/rediger-sur-zds/?page=2#p2778

**Comment by Alex-D** [comment]
En effet je n'ai pas considéré ces pages là :(

Je fais ça tout de suite.

**Comment by sandhose** [comment]
Fix'd pour les réactions des articles et des tutos; thx @Alex-D !
