### ISSUE TITLE
Nom de partie a surveiller

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#878]
Via [pierre_24](http://zestedesavoir.com/forums/sujet/272/erreur-sur-les-noms-des-extraits-fichiers-qui-secrasent/)

Lorqu'on teste la rédaction des tutos et qu'on ne réfléchis, on nomme un des extraits "introduction". Ce qui a pour effet d'écraser l'introduction du tuto telle que créée au moment de la création générale (celle ou on demande le titre, l'icône et etc). Je crois comprendre que c'est "tout" simplement parce que les fichiers markdown qui traînent derrière ont le même nom. N'empêche, c'est un cas à traiter pour éviter que ça ne se passe dans la vraie vie ;)

[EDIT:] du coup, je me tape une "Internal Server Error" quand je tente d'éditer les paramètres du tuto

**Comment by artragis** [comment]
assignez-la moi, je vous propose une PR demain soir au plus tard. Si vous désirez une solution plus tôt, alors tant pis ^^.

**Comment by Alex-D** [comment]
On ne fonctionne pas avec les assignements, mais simplement avec le fait que tu te propose, on considère que tu vas le faire :)

Si quelqu'un l'a fait avant toi et que c'est de qualité on prendra cette solution a priori.

**Comment by artragis** [comment]
Ok, alors je propose dès que j'ai sauf si vous avez avant, compris ^^.

**Comment by Eskimon** [comment]
Du coup j'ai mis le label "en cours", comme ca tout le monde voit que quelqu'un est dessus et je te met la pression na ! :D

**Comment by ArnaudCalmettes** [comment]
> On ne fonctionne pas avec les assignements,

Maintenant, si, et je vais de ce pas préparer un thread dans la dev zone pour en informer tout le monde.

Si on veut s'y retrouver alors que les échéances se pointent à grands pas, on doit pouvoir détecter en un coup d'oeil les issues bloquantes (comme celle-ci) qui n'auraient pas encore trouvé preneur (contrairement à celle-ci). 

J'assigne donc ce ticket à artragis au passage.

Edit: enfin, dès qu'il apparaîtra dans la liste des assignees possibles... En attendant c'est Eskimon qui tient lieu de _place-holder_ (ça sert à ça les caribous).

**Comment by artragis** [comment]
Le commit est prêt, j'ai juste un petit problème de liaison réseau entre ma VM de dev et internet. Dès que c'est résolu, je fais une pull request.

**Comment by firm1** [comment]
Je ré-ouvre cette issue, suite a ma remarque sur [cette PR](https://github.com/zestedesavoir/zds-site/pull/939/files#discussion_r13796173).

**Comment by artragis** [comment]
> @firm1 : effectivement je n'avais pas pris en compte de reslugifier le titre.
> Pour ce qui est des ID : cela signifierai qu'il faut ajouter le chapitre en bdd avant de faire le renommage, why not mais cela ne demande-t-il pas trop de changements?
> Ce bug sera résolu lorsque je publierai mon bugfix pour #913 (le problème généralisé).

Je pense qu'il faut vraiment merger les deux issues du coup car le bug est vraiment identique que ça soit des extraits ou des chapitres etc.

**Comment by firm1** [comment]
> Je pense qu'il faut vraiment merger les deux issues du coup car le bug est vraiment identique que ça soit des extraits ou des chapitres etc.

On n'est pas obligé de merger les issues je penses, car tu peux faire une PR pour plusieurs issues, tant qu'elles te sont assignées, personne n'y touchera.

En ce qui concerne la partie 

> Pour ce qui est des ID : cela signifierai qu'il faut ajouter le chapitre en bdd avant de faire le renommage

Un chapitre/partie ne change jamais d'ID en base. C'est pour ça que je préconise d'utiliser ce paramètre en ayant une arborescence ainsi : `/14_mon-tuto/241_ma-partie/168_mon-chapitre/4578_mon-extrait.md`
