### ISSUE TITLE
Rendu des expressions mathématiques

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#88]
Apparemment, y'a des éléments de syntaxe utilisés dans les expressions mathématiques dans les tutos SdZ qui ne passent pas sur ZdS. Ça vient de mathjax, ou de la syntaxe utilisée dans les .tuto ?

Exemple sur [cette page](http://zestedesavoir.com/tutoriels/10/les-maths-pour-tous/niveau-5/les-fractions-calculs-et-comparaisons/#4-multiplier-des-fractions). La plupart des expressions sont bien rendues, mais certaines déconnent, je sais pas trop pourquoi. Je pensais que c'était l'instruction `\color{}` ou `\align{}` qui faisait planter, mais apparemment c'est pas ça.

**Comment by cgabard** [comment]
mathjax les a bien détectées, elles sont bien formée. Il semble que c'est mathjax qui déconne. Reste a savoir pourquoi maintenant

**Comment by firm1** [comment]
J'en ai testé vite fait [ici](http://www.mathjax.org/demos/).

Et on dirait bien que MathJax merde un peu, après je ne sais pas si les expressions sont bien formés.

**Comment by Coy0te** [comment]
J'ai remarqué que celle là passait : 
`$\frac{9 \times 2}{\color{red}2\color{black} \times 2 \times 5}$`

Mais pas celle-là : 
`$\frac{9 \times \color{red}2\color{black}}{\color{red}2\color{black} \times 2 \times 5}$`

Donc a priori, ça vient quand même bien de l'usage de `\color{}`, qui semble pas être reconnu correctement selon sa position ou son nombre d'apparition dans une expression.

**Comment by cgabard** [comment]
color n'est pas standard mais a priori mathjax le supporte avec un truc genre : 

```
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({ TeX: { extensions: ["color.js"] }});
</script>
```

http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-extensions

**Comment by cgabard** [comment]
Ok je confirme : http://zestedesavoir.com/forums/sujet/7/rediger-sur-zds?page=1#p51

Pour utiliser les extensions on peut soit configurer pour la page dans son ensemble (mon commentaire précédent), soit la demander dans une equation. Ce que j'ai fait dans mon liens. L'ajouter permet de la parser.

@firm1 tu peux rajouter le bout de mon com precedent dans la conf de mathjax ?

**Comment by firm1** [comment]
Yeah, [l'erreur est fixée](https://github.com/Taluu/ZesteDeSavoir/commit/1a610eab8053bcad380581e1bcf2353c046f41c5). Merci @cgabard 

[La preuve](http://zestedesavoir.com/tutoriels/10/les-maths-pour-tous/niveau-5/les-fractions-calculs-et-comparaisons/#4-multiplier-des-fractions)

**Comment by cgabard** [comment]
Je ne sais pas d'ou viens le \usepackage{cancel} mais il semble déconner.

Bonne réactivité firm1

**Comment by Coy0te** [comment]
C'est du support efficace ça, à peine soumis que le bug est déjà corrigé. =)

**Comment by firm1** [comment]
> Je ne sais pas d'ou viens le \usepackage{cancel} mais il semble déconner.

Ah, merde, j'vais battu mon record de fermeture d'issue. pourtant

**Comment by cgabard** [comment]
essais d'ajouter cancel.js dans la liste des extensions. Mais je ne suis pas surs que ça change grand chose.

@Coy0te : c'est toi qui l'a ajouté ça ou c'etait dans les sources à la base ?

**Comment by Coy0te** [comment]
J'ai rien ajouté, c'était dans le tuto au format zCode.

Une fois l'extension cancel ajoutée à Mathjax, les `\cancel` vont sûrement fonctionner, mais  il faudra tout de même que je vire tous les `\usepackage` en début de formule mathématiques lors de la conversion zCode -> md, c'est bien ça ?

**Comment by cgabard** [comment]
Bin pas forcément, faut voir mais c'est possible.

**Comment by Coy0te** [comment]
Sinon, je remplace `\usepackage` par `\require`, et c'est réglé.

**Comment by cgabard** [comment]
Dans le cas présent, oui ça devrait marcher sans toucher à la config serveur.

**Comment by firm1** [comment]
Je viens de rajouter [une floppée](https://github.com/Taluu/ZesteDeSavoir/commit/ec02bd8344f0f837bbb79942170642a58dd91126) d'extensions, trouvées [ici](http://packages.ubuntu.com/quantal/all/libjs-mathjax/filelist), et ça merde toujours sur les `usepackage`

**Comment by cgabard** [comment]
Oui car usepackage est une syntaxe latex mais pas mathjax

**Comment by cgabard** [comment]
Pour les align il faudrat rajouter AMSmath

**Comment by firm1** [comment]
> Oui car usepackage est une syntaxe latex mais pas mathjax

Et du coup c'est quoi la bonne syntaxe Tex ?

**Comment by cgabard** [comment]
En gros pour cancel, le remplacer par `\require` suffirait si tu ne force pas son chargement.

**Comment by cgabard** [comment]
Mais là ce n'est pas resolvable en fait : mathjax ne supporte pas cette commande. 

Si tu conserve cancel dans les header, il faut que le `\usepackage{cancel}` soit viré des equations.

**Comment by firm1** [comment]
Je viens de faire des tests, en effet, @Coy0te va falloir que tu vire, tout ce qui ressemble à \usepackage{blabla} dans les tutos.

**Comment by cgabard** [comment]
Est ce que, pour nous prémunir de ce genre de trucs, on pourrait pas charger toutes les extensions dipspo ? Il y en a une qui fait ça !

Sinon quelqu'un prend son courage à deux mains et nous pond une mini extension pour mathjax qui fait ignorer la commande `\usepackage`

**Comment by firm1** [comment]
Etant donné que le problème vient des anciens tutos, vaut mieux que ce soit Coyote qui les vire (les \usepackage ).

**Comment by Coy0te** [comment]
C'est un usage assez rare dans les .tutos, je vais virer les occurrences de `\usepackage{color}` et `\usepackage{cancel}` dans les contenus des balises math.

J'ai repéré un tuto qui utilise pas mal de syntaxes maths assez exotiques, je vais l'importer sur ZdS pour voir à quoi il ressemble.

**Comment by Coy0te** [comment]
C'est bon pour les usepackage, je les ai virés via le parseur zCode. Mais y'a encore un joli tas de merdier qui fait déconner les balises maths, et franchement ça devient du cas par cas, pour certains cours où les auteurs ont fait un peu n'importe quoi avec la balise `<math>`. 

Je suis d'avis de laisser ça en l'état, et de rendre les formules compatibles à posteriori, là où ça a pète encore.

**Comment by firm1** [comment]
On dirait qu'il y'a des cas ou on a des balises `</math>` sans leurs équivalents `<math>` ? c'était déjà le cas dans les .tuto ?

**Comment by Coy0te** [comment]
Non, j'ai remarqué que le parseur HTML s'était chié dessus dans ce tuto, je ne sais pas encore pourquoi : il a cru que c'était des balises mere/fille, et a pris la première et la dernière balise math pour tout un groupe de balises, c'est bizarre.

**Comment by Coy0te** [comment]
Ouai, après tests il s'avère que c'est la méga-ligne de formule de maths qui fait déconner le parseur HTML à cet endroit du tuto, si je la raccourcis un peu ça passe sans problèmes... Bizarre bizarre.

**Comment by Coy0te** [comment]
J'ai corrigé le problème en échappant le contenu des balises maths, il s'agissait d'un enchaînement de <, / et > dans les balises maths qui posaient problème au parseur.

Je ferme l'issue, et la rouvrirait si lors de futurs tests je trouve d'autres éléments problématiques.

**Comment by ArnaudCalmettes** [comment]
Les environnement matrix et tableau sont insérés sans avoir besoin des \( \), et les expressions inline sont beaucoup trop grosses.

[Cf. ici](http://zestedesavoir.com/forums/sujet/235/test-math/?page=1#p3096).

**Comment by Alex-D** [comment]
J'ai un fix qui arrive pour ça.

**Comment by Alex-D** [comment]
Voilà, j'ai réduit à ~16px. Soit un chouilla plus qu'avant et beaucoup moins qu'actuellement (22px, beaucoup trop gros).

Impossible au niveau du code de faire la différence entre du code inline et du code "en gros", donc j'ai choisi une taille "passe-partout".

**Comment by Eskimon** [comment]
Durant la fin de la beta front, plus personne n'avait l'air de se plaindre de souci de taille sur ce sujet... On pourrait retester vite fait avec un nouveau batch de participant et fermer ?

**Comment by Alex-D** [comment]
Pour moi on peut déjà fermer, je ne peux rien faire de mieux actuellement.

**Comment by ArnaudCalmettes** [comment]
Pour moi aussi.
