### ISSUE TITLE
Ajouter un bouton "Retour en haut"

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#882]
Un bouton pour retourner tout en haut de la page dès lors qu'on a scrollé un peu.

A mettre en place uniquement sur le style wide (ordi bureau). Sur mobile ça va prendre de la place et le menu sur le côté est accessible (ou va l'être suite à des correctifs) tout le temps, donc pas utile de remonter.

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis plus d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.
