### ISSUE TITLE
Nombre de reactions sur articles

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#883]
[Via Jeekwiz](http://zestedesavoir.com/forums/sujet/271/ajouter-le-nombre-de-reaction-des-articles/)

Sur la page d'accueil du site, les articles sont accompagnés de la date et du nombre de réaction (en orange). Or sur la page dédiée aux articles on à le droit uniquement à la date. Il faudrait rajouter le nombre de commentaire.

**Comment by Eskimon** [comment]
Je veux bien essayé de m'en occuper :)

**Comment by Eskimon** [comment]
Ah bah en fait c'est super simple, suffit de copier le bout de code qui fait pareil sur la home !!

**Comment by Eskimon** [comment]
On a une raison de garder ça toujours ouvert ?

**Comment by sandhose** [comment]
Peut-être
