### ISSUE TITLE
[MP] Ajout d'un membre post création

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/zds-site#885]
J'ai trouver d'autres bricoles qui merdouille dans les MP...
- Si je crée un MP, je peux ajouter un membre apres la création du MP via le bouton "Ajouter un membre" -> Normal
- Par contre, dans un MP que je n'ai pas initié, le bouton va grisé la page mais la modale ne va pas arriver...

Donc dans le deuxieme cas :
- Soit il faut popup la modale
- Soit il faut cacher le bouton.

**Comment by Alex-D** [comment]
En effet, le comportement attendu et qu'on ne puisse pas ajouter de membre si on est pas l'OP.

**Comment by Alex-D** [comment]
Je prends.

**Comment by Eskimon** [comment]
Je confirme que c'est OK (en local), je ferme !
