### ISSUE TITLE
Lien dernier message sur les forums

### ISSUE THREAD

**Issue by ChantyTaguan** [zestedesavoir/zds-site#896]
[Voir discussion](http://zestedesavoir.com/forums/sujet/108/dernier-message/?page=1#p2394)

Lorsque l'on clique sur le lien "Dernier message" d'un topic, ça devrait nous amener au dernier message lu si on a déjà consulté le topic.
Pour l'instant, on arrive au dernier message tout court.

**Comment by Eskimon** [comment]
Lié a ceci pour la resolution... https://github.com/zestedesavoir/zds-site/issues/430

**Comment by Alex-D** [comment]
C'est corrigé, à tester, merge, MEP, et tout :)

**Comment by Alex-D** [comment]
C'est en prod.
