### ISSUE TITLE
Marquer comme non lu

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/zds-site#899]
Sur le design temporaire, il y avait sur chaque post un lien "Marquer comme non lu à partir d'ici" (fait dans la PR #595 semble-t-il). Je n'ai pas retrouvé l'issue d'origine, je crois qu'il n'y en avait pas.

C'était top.

**Comment by Alex-D** [comment]
J'ai eu vent de cette ajout.

Le **gros** soucis, c'est que le design initial ne prévoit pas ce bouton. Du coup, sur mobile notamment je n'ai pas la place de le mettre avec les autres "Masquer", "Citer", etc.

Du coup j'en arrive à la question simple mais nécessaire : où est-ce qu'on met ce bouton ? Et comment est-ce qu'on l'iconifie ?

**Comment by ShigeruM** [comment]
Ça je n'en sais rien. De toute façon ce n'est pas prioritaire. Et de toute façon encore, on est en période de gel. Donc t'as le temps de trouver une solution ergonomique et jolie ! ;)

**Comment by Alex-D** [comment]
En fait, je n'ai pas de solution, j'y ai déjà réfléchi mais je ne vois pas comment rentrer tout ça.

On a déjà, sur mobile

```
Pseudo, date
Cette réponse m'a aidé / +1 / -1 / Masquer / Editer / Citer / Signaler
```

Ça fait un sacré paquet de boutons l'air de rien.

PS : c'est une régression donc ça n'est pas gelé pour le coup je pense.

**Comment by firm1** [comment]
Moi je le trouvais pratique ce bouton (sinon je ne l'aurai pas implémenté me direz-vous).

Pour moi, il faut les caser ces boutons, n'importe ou, mais il faut les caser tous. C'est dommage de perdre une fonctionnalité parce que "ça rentre pas dans le design"

**Comment by Alex-D** [comment]
> Moi je le trouvais pratique ce bouton

Je n'émet aucun doute là dessus.

> C'est dommage de perdre une fonctionnalité parce que "ça rentre pas dans le design"

Je ne veux pas la perdre, c'est juste que c'est encore un truc qui arrive après la conception, donc c'est pas réfléchi pour. Donc me faudrait des idées :)

**Comment by gustavi** [comment]
Corrigé dans #1810 !
