### ISSUE TITLE
Non lu à partir d'ici remet les notifications

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#900]
@ShigeruM propose que lors que l'on clic sur le bouton "non lu à partir d'ici" (cf issue #899) la notification revienne dans le menu en haut.

Cette issue nécessite que la #899 soit en place je pense.

J'ai volontairement splité l'issue en deux car d'un côté c'est une simple régression tandis qu'ici c'est une nouvelle fonctionnalité.

**Comment by firm1** [comment]
Je n'ai pas compris grand chose a cette issue.

Le back-end de ce bouton est déjà implémenté et fait remonté l'issue dans les notification automatiquement. Donc ici pour moi il s'agit juste de placer le bouton avec le bon liens pour corriger l'isssue #899 et celle-ci (donc je ne vois pas a quoi elle sert)

**Comment by Alex-D** [comment]
On parle bien des notifications en haut à droite ? Si oui, tu peux fermer du coup.

**Comment by firm1** [comment]
> On parle bien des notifications en haut à droite ? Si oui, tu peux fermer du coup.

Ouaip, d'ou le tag regression sur l'autre issue, car ça marchait déjà ainsi avant.
