### ISSUE TITLE
Lien vers le dernier message erroné

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#902]
Je vais sur cette page : `/forums/` à coté de chaque forum j'ai un "Dernier message : ..."

Mais quand je clique sur le lien : que neni, il n'ya aucun lien

**Comment by Alex-D** [comment]
C'est pas logique du tout je viens juste de pousser un patch.

**Comment by Eskimon** [comment]
Ca me semble Ok en local, ca pointe bien sur le n-1 comme c'était avant :) je ferme !
