### ISSUE TITLE
Redirection failing once the user logs in?

### ISSUE THREAD

**Issue by Ge0** [zestedesavoir/zds-site#91]
J'ai navigué sur ZdS sans être connecté, et lorsqu'on me redirige sur le formulaire de connexion, une variable d'url **next** est précisée. Je devine qu'il s'agit de la page sur laquelle nous serons redirigés après connexion. Exemple :+1: 

> zestedesavoir.com/membres/connexion?next=/tutoriels/off/11/un-chat-en-phpajax/?version=983086e46579da7cfb3453d329d3554873abdc8f

Cependant, une fois correctement connecté, la redirection ne semble pas fonctionner ou, peut-être, n'a pas été développée. Je suis redirigé sur l'accueil à la place.

Quelqu'un pour s'en charger ou je me penche là-dessus ?

**Comment by cgabard** [comment]
> Quelqu'un pour s'en charger ou je me penche là-dessus ?

Bah toi tu veux t'en charger ? Les autres dev ont surement des trucs sur le feux donc fait le si tu te sent l'envie de le faire !

**Comment by Ge0** [comment]
Je vais étudier ça. :)

**Comment by firm1** [comment]
Je viens de push en prod la PR, par contre, il faudrait aussi que le bouton de connexion sur la home soit accompagné du next (ce n'est pas encore le cas.)

**Comment by Ge0** [comment]
En fait le next apparaît quand tu veux faire une action qui nécessite d'être loggué. Il y a plusieurs cas de figure comme pour le vote d'un message et d'autres cas que je n'ai pas encore relevés.
