### ISSUE TITLE
Changement de titre d'un chapitre

### ISSUE THREAD

**Issue by ArnaudCalmettes** [zestedesavoir/zds-site#913]
Bug rapporté par pierre_24 dans un rapport très détaillé [ici](http://zestedesavoir.com/forums/sujet/281/renommer-un-chapitre-cree-des-copies/?page=1#p2851).

Renommer un chapitre crée un doublon, et il devient impossible d'éditer l'intro et la conclusion du chapitre.

**Comment by artragis** [comment]
Ok, c'est lié à #878 . En fait que ça soit à la création ou au renommage, un tuto ou un chapitre ont un fichier markdown appelé "introduction" et un autre appelé "conclusion".
Lorsque j'arriverai à faire ma PR pour la #878 , on pourra vois si la "solution" que j'ai envisagée côté backend peut être généralisable. 
Tu peux déjà en voir un aperçu dans mon dépos au niveau des fichiers [models](https://github.com/artragis/zds-site/blob/issue_878/zds/tutorial/models.py) et [views](https://github.com/artragis/zds-site/blob/issue_878/zds/tutorial/views.py). Je ne peux pas faire une PR avec cette branche car il y a eu un merge foireux d'avec votre branche de dev.

**Comment by pierre-24** [comment]
Pour moi, ce que tu proposes à une bonne chance de fonctionner.

**Comment by artragis** [comment]
Je fais une PR ce soir pour les extraits. Si quelqu'un a le pouvoir de m'assigner à ce bug-ci, je regarderai quels sont les bugs possibles et donnerai un résultat d'ici mardi soir avec une forte chance que ça soit lundi soir.

**Comment by Alex-D** [comment]
Y a du monde sur cette issue, il faudrait quand même faire attention à pas corriger les choses corrigées par d'autres :(
