### ISSUE TITLE
Enrichir les fixtures

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#914]
Actuellement les fixtures ne sont pas suffisantes à réaliser les tests minimums.

Il serait vraiment très pratique d'avoir des sujets de forums avec plusieurs pages, de même pour les comentaires de tuto et articles.

Aussi, il serait pratique (si possible) d'avoir des articles et des tutos publiés et en cours de rédaction, de telle façon qu'il y ait assez d'articles/tutos publiés que ça déclenche l'affichage d'une pagination.

Il y a aussi un soucis actuellement avec les fixtures qui ne sont pas à jour par rapport aux nouvelles "normes" du Markdown.

**Comment by Eskimon** [comment]
Je veux bien m'occuper :) C'est vrai que ca serait bien utile pour gagner du temps pour pas mal de test !!

**Comment by Alex-D** [comment]
Surtout que perso j'ai 3 machines où je dev régulièrement, et je pense jamais à récupérer la BDD. Donc refaire les manips à chaque fois c'est assez lourd. Et il m'arrive de réinstaller l'env de dev : et hop faut recommencer :D

**Comment by Eskimon** [comment]
Avant que je commence et fonce tete baisse la dedans, il y a des trucs qui vous ferait plaisir a avoir ? (en terme de volume, de diversite etc...).

Parce qu'autant certains trucs peuvent etre rapide (a coup de boucle c'est vite fait de peupler un forum XD) que certains trucs ca sera a la main (pour des articles, tutos etc...) du coup si vous avez des exigences et pour eviter de faire plusieurs PR ca serait bien d'en avoir une petite liste :)

**Comment by Alex-D** [comment]
> a coup de boucle c'est vite fait

https://github.com/zestedesavoir/zds-site/tree/beta-0.2/fixtures

Vu ce dossier, j'ai pas l'impression qu'on puisse faire des boucles.

Sinon : 

**Forum**
- 50 sujets sur le forum
- adapter les catégories du forum par rapport à celles qu'on a en prod (ça m'aiderais pour le design)
- certains sujets avec 1, 2 réponses, d'autres avec 50, 100 réponses

**Articles**
- Avoir la possibilité de générer une 50ène de commentaire pour un article donné (ou prévoir un ID particulier, je ne sais pas)
- Avoir des contenus courts, longs, ayant tout type de contenu (code, balises question, info, warn, etc. citation, expressions mathématiques, etc) dans un dossier "articles" (comme le dossier tuto actuel, mais juste avec quelques .md qu'on peut recopier)

**Tutoriels**
- Renommer le dossier tuto en tutoriels
- Mettre le tutoriel Java EE de Coyote, car il est excellent pour tester : il y a tout dedans.

**Comment by Eskimon** [comment]
Pour les boucles on a du mal se comprendre ^^ je pensais faire un petit script qui va me creer le fichier de fixture avec tout le bordel dedans :) donc la boucle serait juste dans le script de generation, pas dans la fixture itself.

Ok pour le reste, je vais voir ce que je peux faire :) , j'essaie de faire ca bientot (ca sera probablement pas pret ce soir cependant, il y a quand meme pas mal de choses a faire pour une PR complete !)

**Comment by firm1** [comment]
> Avant que je commence et fonce tete baisse la dedans

Pour t'aiguiller un peu, ce travail a déjà été amorcé à l'époque dans le cadre des fixtures automatiques pour les tests de charges.

Ce que t'as besoin de savoir : 
- la branche concernée est la branche : [tests-charge](https://github.com/zestedesavoir/zds-site/tree/tests-charge)
- le fichier qui permet de charger certaines fixtures automatiques à coup de boucles est le suivant : [load-data.py](https://github.com/zestedesavoir/zds-site/blob/tests-charge/tests/fixtures/load-data.py)
- son entête contient la ligne `from django.conf import settings` qui permet de récupérer dans le [settings](https://github.com/zestedesavoir/zds-site/blob/tests-charge/zds/settings_prod.py) les variables de paramètres.
- Avec ça, il suffisait de lancer [ce script](https://github.com/zestedesavoir/zds-site/blob/tests-charge/load-testing.bat) pour créer toutes les données automatiquement. ça nous évite de se trimbaler dans le dépot avec des fixtures qui font 10Mo.

Donc, libre a toi de reprendre la même logique pour rajouter les tutos, des articles, les galleries, etc.

Le seul inconvenient est que nous le contenu sera en mode robot. Mais au moins les fixtures resterait maintenable sur le long terme.

N'hésite pas en cas de question

**Comment by sandhose** [comment]
Il faudrait suffisamment d'éléments pour remplir plusieurs pages de recherche (pour tester la pagination, qui ne marche pas à l'heure actuelle...)
Si tu veux, j'ai un stock d'images de chats pour les galeries (au moins une galerie avec +30 éléments serais le bienvenue, pareil, pour tester la pagination...)

**Comment by Alex-D** [comment]
Bah avoir plein de topics X plein de messages : t'auras de quoi avoir une pagination je pense :)

**Comment by Eskimon** [comment]
@firm1 cool, je regarderais ca en premier du coup et l'enrichirais de nouveauté :) Mais du coup ca veut aussi dire que chaque dev' devra régénérer les fixtures a l'install non ?

@sandhose je veux bien :) mais tu vois ca comment ? tu les heberges quelques part et les galeries ont des liens qui pointes dessus ? car on va pas s'amuser a trimballer des chats dans le git quand meme (ca va laisser des poils partout c'est chiant !)

**Comment by firm1** [comment]
> @firm1 cool, je regarderais ca en premier du coup et l'enrichirais de nouveauté :) Mais du coup ca veut aussi dire que chaque dev' devra régénérer les fixtures a l'install non ?

Aujourd'hui chaque dev est oibligé de faire ceci a chaque install de son environnement : `python manage.py loaddata fixtures/users.yaml fixtures/forums.yaml fixtures/topics.yaml fixtures/mps.yaml fixtures/categories.yaml`

Demain (avec tes modifs), il n'aura plus qu'a faire ceci à chaque install d'un environnement `python manage.py shell < tests/fixtures/load-data.py`

> Si tu veux, j'ai un stock d'images de chats pour les galeries

Si @Eskimon part de la base que je lui propose, il suffit d'avoir une image qu'il importera plusieurs fois avec des noms différents.

**Comment by Eskimon** [comment]
J'ai une base de prête permettant de charger des users et des fofos...
https://github.com/Eskimon/zds-site/tree/moar_fixtures

Vous voulez une PR pour en discuter plus simplement ou on parle ici si besoin ?

**Comment by firm1** [comment]
> Cela va créer les entitées suivantes (reglables dans le fichier dataloader.py) :

Un lien vers dataloader.py ne serait pas de refus.

> Chaque utilisateur a _CHANCES_TO_BE_STAFF_ % d'être Staff

Pourquoi donc ? il faudrait fixer un nombre d'utilisateurs staff et un nombre d'utilisateurs normaux. Et les login/pass doivent être donnés dans le readme.

> 3 categories de forum

Pourquoi seulement trois ? Quitte a paramétrer autant paramétrer aussi le nombre de catégories, qui sera fixé à 3 par défaut.

> fake.sentence()

En utilisant ceci pour les titres, il faudrait limiter la taille sinon, il risque d'injecter des topic avec une taille > 80 caractères

Pour finir, pourquoi supprimer les fixtures des tutos ? C'est eux qui permettent de lancer des tests d'import.

**Comment by Eskimon** [comment]
> Un lien vers dataloader.py ne serait pas de refus.

Zai oublié :(

> Pourquoi donc ? il faudrait fixer un nombre d'utilisateurs staff et un nombre d'utilisateurs normaux. Et les login/pass doivent être donnés dans le readme.

Pourquoi pas ? Ce sont tous des dummy donc on s'en fiche non ? J'ai rajouté un utilisateur staff "connu" si on veut jouer avec l'administration. Mais sinon je vois pas trop l'intéret d'avoir plein de trucs statiques si on s’embête a avoir un dynamique

> Pourquoi seulement trois ? Quitte a paramétrer autant paramétrer aussi le nombre de catégories, qui sera fixé à 3 par défaut.

Ouai c'est vrai. J'en ai fait 3 pour avoir un truc similaire à la prod', mais c'est vrai que ca pourrait/devrais etre étendu simplement.

> En utilisant ceci pour les titres, il faudrait limiter la taille sinon, il risque d'injecter des topic avec une taille > 80 caractères

Voui j'y ai pas repensé... et comme sqlite ne fait aucun controle le systeme m'a jamais taper dessus :D

> Pour finir, pourquoi supprimer les fixtures des tutos ?

Jvais les remettres en fait. J'voulais juste repartir sur un gros clean pour remettre les choses petits à petits (soit en dynamique, soit en statique) (les modèles ayant évolué depuis les premières fixtures)
C'est un travail de longue haleine (pour moi en tout cas ca prend un peu de temps (n00b)) mais je voulais présenter un WIP au cas ou les gars du front voulais jouer avec ca pour tester leur design.

**Comment by firm1** [comment]
C'est bon maintenant. o/
