### ISSUE TITLE
Accès aux tutoriels en béta impossible

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#926]
Via [Étoile filante](http://zestedesavoir.com/forums/sujet/321/tutoriels-en-beta-test/) : 

il est impossible d'accéder aux tutoriels en béta lorsqu'on est membre ou staff, y'a que les admins qui ont le droit (en tout cas en local, et confirmé par l'interventon d'Ariusi). Puisque j'ai identifié le bug et sa solution, je me propose, si vous me le permettez, de le régler (en plus, c'est pas très compliqué, en  lignes c'est fait, et faut bien que je débute par quelque part)

**Comment by GerardPaligot** [comment]
J'ai rajouté les tags qui vont bien. Tu sembles avoir une bonne piste expliquée sur les forums, ça devrait être assez simple. Par contre, assigne toi la tache (bizarrement, je ne peux pas le faire moi). Comme ça, on sait en un coup d'oeil qu'elle est prise par quelqu'un.

**Comment by pierre-24** [comment]
Je n'arrive pas à me l'assigner non plus. À mon avis, c'est parce que j'ai oublié de demander une autorisation à Sandhose/Alex-D/quelqu'un d'autre pour faire ce que je fait, je règle ça de suite.

Merci pour les tags (ça non plus je ne pouvais pas le faire) :)

**Comment by Eskimon** [comment]
> Je n'arrive pas à me l'assigner non plus

C'est des contraintes sur l'administration du GH. Je vais me l'assigner pour dire qu'elle est prise, je met le label "En cours" et je te laisse travaille :)

**Comment by pierre-24** [comment]
Merci bien :)

Bon, par contre, je me suis rendu compte que le problème était un peu plus important que ce que je ne pensais à la base. En effet, ce que propose actuellement le site, c'est un accès direct au tuto "offline", ce qui inclut tout le reste ("éditer", "ajouter" et ainsi de suite). Évidement, c'est pas la bonne solution.

Du coup, deux idées me viennent : 
1. Rattacher des nouvelles fonctions et des nouvelles URL (genre "/tutoriels/beta/%pk%/%slug%/" et ainsi de suite). À ce moment là, ce qui peut servir, c'est les templates de base de visualisation des tutos, avec limite un bandeau "ceci est une béta". Défaut, ça signifie aller chipoter des templates (entre autre la template de visualisation des tutos et la template qui donne les liens des tutos en béta pour donner les liens corrects) et j'ai cru comprendre que j'avais pas le droit de toucher à ça sans l'accord au moins d'@Alex-D
2. Modifier la template de visualisation de tutos "offline" pour qu'elle n'affiche pas les options "éditer" et ainsi de suite si le membre n'est ni auteur, ni staff. Si la première solution ne me plait pas parce que je doit chipoter des trucs auquel j'ai pas le droit de toucher, celle-ci me plait encore moins parce que c'est du bricolage qui n'as pas de sens.

Conclusion, je demande votre avis.

**Comment by cgabard** [comment]
Je réagi sur un truc seulement : si tu peux toucher a tout sans l'avis de personne. Il y a une phase de review puis de tests pour s'assurer que le code est propre et fonctionnel. Mais non il n'y a personne en particulier a prévenir. Si c'est Alex qui fait la review il fera des remarques. Mais il y en a d'autres qui peuvent s'en occuper, comme sandhose

**Comment by GerardPaligot** [comment]
Comme tu dis, la seconde solution est un peu du bricolage. Ca serait dommage d'en arriver là. Et comme le dit Christophe, tu as tout à fait le droit de toucher aux templates (projet open source toussa). Tu passeras juste par une review d'Alex-D.

**Comment by ShigeruM** [comment]
Ou par une review de quelqu'un d'autre.

**Comment by ArnaudCalmettes** [comment]
PS, hors sujet: Si vous avez besoin d'assigner un ticket à quelqu'un qui n'est pas encore dans la liste, prévenez-moi et je m'occupe de l'ajouter. ;)

**Comment by ArnaudCalmettes** [comment]
À la réflexion, je classifie ce bug en Bloquant bêta publique, puisqu'il rend une feature (la bêta zone des tutos) inutilisable.

Pour te répondre Pierre, les PR passent par une phase de QA (validation qualité) qu'on met en place depuis hier, pour valider qu'elles ne pètent rien fonctionnellement. Les reviews sur le code sont un peu plus informelles : je propose qu'on se débrouille/s'organise pour les faire sur le chan zds-dev sur (irc.smoothirc.net).

**Comment by pierre-24** [comment]
Hello,

J'ai avancé dans le machin, à mon avis je devrais plus en avoir pour trop longtemps. Juste quelques points qui mérite réflexion, selon moi : 
1. Est ce qu'on a le droit de commenter un tuto en béta ? Si oui, est ce que ces commentaires doivent disparaitre avec la publication ? Avec chaque nouvelle béta ? Autre ?
2. Dans le processus, on se promène avec un SHA qui correspond à une certaine version du tuto. L'auteur (ou les auteurs) peut (peuvent) avoir envie de mettre la béta à jour, pour ce faire, il doivent désactiver et réactiver la béta. Un bouton "mettre à niveau la béta" (ou un terme plus joli) ne serait-il pas plus pertinent ?
3. Comme ça a été discuté sur le forum, peut-être que les tutos en béta doivent passer dans une catégorie à part. Plusieurs manière de faire ça : à l'aide d'un tag, ou en dur dans le code. A voir, donc.

(pour le reste, [voilà ou j'en suis](https://github.com/pierre-24/zds-site/commit/cff9bb1b9d5db1ad0c8b1482a78e72d1cc13f1b7))

**Comment by Alex-D** [comment]
> 1. Est ce qu'on a le droit de commenter un tuto en béta ? Si oui, est ce que ces commentaires doivent disparaitre avec la publication ? Avec chaque nouvelle béta ? Autre ?

Très bonnes questions !

Il me semblait qu'il avait été décidé que seuls les staff + les auteurs auraient le droit de commenter un tutoriel en beta.

Pour moi, oui les commentaires en beta doivent être différents de ceux de la version en ligne. Faut bien garder en tête que les deux peuvent cohabiter : beta et publiée peuvent être activés en même temps ; ça pointe vers deux sha différents. A chaque beta : je ne sais pas trop, d'un côté on a envie de dire oui car certains commentaires seront dépassés, mais d'autres ne le seront pas, du coup c'est délicat. En conclusion mon avis serait de les laisser au cours de toutes les beta ; en tous cas  ne pas les retirer à la MàJ du sha de la beta.
1. J'aime l'idée ! Beaucoup plus pratique.
2. Mon avis est qu'il faudrait une page dédiée à lister les tutoriels en beta. Les tags et autres sont déjà utilisés et ont un sens.

**Comment by pierre-24** [comment]
> Il me semblait qu'il avait été décidé que seuls les staff + les auteurs auraient le droit de commenter un tutoriel en beta.

Ça me semble pas trop complexe à implémenter

> Pour moi, oui les commentaires en beta doivent être différents de ceux de la version en ligne. Faut bien garder en tête que les deux peuvent cohabiter : beta et publiée peuvent être activés en même temps ; ça pointe vers deux sha différents. A chaque beta : je ne sais pas trop, d'un côté on a envie de dire oui car certains commentaires seront dépassés, mais d'autres ne le seront pas, du coup c'est délicat. En conclusion mon avis serait de les laisser au cours de toutes les beta ; en tous cas ne pas les retirer à la MàJ du sha de la beta.

Ok. J'ai pas encore tout compris au système de commentaires, mais je vais voir ce que je peux faire à ce niveau là.

> J'aime l'idée ! Beaucoup plus pratique.

J'ajoute ça

> Mon avis est qu'il faudrait une page dédiée à lister les tutoriels en beta. Les tags et autres sont déjà utilisés et ont un sens.

Je préfère alors ouvrir une issue externe pour discuter de ça, l'histoire de pas faire n'importe quoi tout seul dans mon coin.

**Comment by Alex-D** [comment]
A noter : les auteurs = membres ayant au moins un tutoriel en ligne, pas en beta.

En résumé pour les commentaires, il doit y avoir deux flux : publié, beta. Le flux publié c'est pour la version publique du tuto. Le flux beta c'est pour que les auteurs puissent commenter le tutoriel et donner leur avis : ça n'a rien à faire en ligne vois-tu ?

**Comment by pierre-24** [comment]
Ah, non, t'inquiète, quand je disais que j'avais pas encore tout compris au principe des commentaires, je parlais du code, mais je suis en train de regarder à ça ;)
