### ISSUE TITLE
Passer les instructions d'installation dans le Wiki

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#927]
Passer toutes les instructions d'installation de l'environnement de développement dans le Wiki, pour une meilleure organisation.

Je peut m'en occuper s'il le faut, ça devrait être vite fait

**Comment by GerardPaligot** [comment]
On en avait discuté il y a un petit temps en interne. Ce qu'il en ressortait c'est la possibilité à n'importe quel contributeur de pouvoir installer l'environnement de développement sans connexion internet (et donc sans un accès avec un wiki pour la procédure d'installation).

Personnellement, je préfère aussi avoir la documentation sur le wiki. Si le contributeur n'a pas internet, il ne pourra de toute façon pas installer son environnement de développement. Mais c'est une décision qui a été décidé suite à un vote en interne.

**Comment by Alex-D** [comment]
C'est surtout que ça rend indépendant le dépôt de l'hébergeur et que t'as toute la doc en local.

Quand j'ai une connexion pourrie, je suis bien content d'avoir la doc du truc que je cherche en local. Par exemple, Gulp ne nécessite pas de connexion internet pour fonctionner. De même pour lancer une instance de ZdS localement.

Autant l'installation nécessite une connexion, autant ce qui suit : non.

Du coup je reste de l'avis de tout laisser dans le dossier doc ; c'est d'ailleurs ce que tous les projets open-source font.

**Comment by ArnaudCalmettes** [comment]
On ne peut pas les dupliquer sur le wiki, tout bêtement ?

Si quelqu'un veut lire le wiki plutôt que le doc d'install, et que c'est facile de lui donner la possibilité de le faire, ça ne mange pas de pain. Je ne vois pas pourquoi on devrait se l'interdir, en dehors du risque (maîtrisé) de désynchronisation entre les deux docs.

**Comment by Alex-D** [comment]
> désynchronisation

Gros risque tout de même non ?

**Comment by SpaceFox** [comment]
Question de noob : quelle est la différence pour l'utilisateur qui utilise le site Github entre "lire la doc écrite en markdown et mise en forme par Github" et "Lire le wiki" ?

En première approche, la principale différence que je vois, c'est que le Wiki oblige d'être connecté au net, et pas la doc - qui est téléchargeable mais non rendue en HTML si on la lit en local.

**Comment by Alex-D** [comment]
> quelle est la différence pour l'utilisateur qui utilise le site Github entre "lire la doc écrite en markdown et mise en forme par Github" et "Lire le wiki" ?

Tu as une navigation sur le wiki, pas dingue mais existante. Le wiki = il faut avoir les droits sur le repo pour le mettre à jour. La doc, tout le monde peut faire une PR et MàJ.

> le Wiki oblige d'être connecté au net, et pas la doc

C'est cette différence ainsi que des bonnes pratiques que l'on peut voir un peu partout qui me convainquent de ne pas utiliser le wiki pour ça en fait.

**Comment by ArnaudCalmettes** [comment]
Reste-t'il encore quelque chose à discuter sur cette issue ?

**Comment by Eskimon** [comment]
Je suis partisan d'une fermeture. Globalement l’idée est:

**Pour**
- Ca fait pus propre et moderne qu'un README ?
- Plus facile a modifier ?

**Contre**:
- Wiki non consultable en offline
- Risque de desynchronisation.

**Comment by cgabard** [comment]
Techniquement : 
- Les wiki github sont des dépots git comme les autres donc il est possible de les avoir en offline en clonant le dépot du wiki
- On peut faire de la navigation dans le readme en faisant des liens markdown relatif vers un autre document markdown.

Donc pour moi la seule vraie différence est que le README est affiché en ouvrant l'adresse du dépot, pas le wiki. La doc de base est donc beaucoup plus visible et me semble donc meilleur

**Comment by SpaceFox** [comment]
Vu qu'il semble y avoir un consensus sur "on garde la doc dans le README" (pas de réaction depuis 17 jours), je ferme.
