### ISSUE TITLE
Possibilité de voir les messages masqués d'un membre depuis son profil

### ISSUE THREAD

**Issue by ArnaudCalmettes** [zestedesavoir/zds-site#928]
[Remarqué par cshark ici](http://zestedesavoir.com/forums/sujet/306/un-bouton-nouveau-tuto-dans-la-section-des-tutoriels/?page=1#p3089).

En allant sur mon profil, il peut afficher les messages masqués de ce thread. Du coup, la feature n'est pas très logique.

Deux solutions possibles : 
- Soit on laisse le bouton "voir" sur les messages masqués pour les membres normaux (quitte à avoir une fonctionnalité "supprimer" pour le staff). Personnellement c'est l'option que je préfère.
- Soit il faut aussi masquer les posts masqués dans le profil du membre concerné.

Dans tous les cas ce n'est pas bloquant.

**Comment by pierre-24** [comment]
Pourquoi cacher quelque chose? J'veux dire, si on a vraiment un truc a effacer, il suffit d'éditer. Du coup, que tout le monde puisse voir me semble logique.

**Comment by Alex-D** [comment]
C'est surtout pour la modération pour le coup. Genre un gros flood ou autre, on masque les messages généralement. Du coup en suivant la proposition de nohar, plutôt que masquer on supprimerais radicalement ce type de messages.

**Comment by Eskimon** [comment]
A priori c'est fermé...

A priori seulement car on a pensé à un truc après coup : Cette correction devrait elle aussi s'appliquer sur les commentaires d'articles et tutos ? (je dirais oui)

**Comment by SpaceFox** [comment]
> Cette correction devrait elle aussi s'appliquer sur les commentaires d'articles et tutos ? (je dirais oui)

Pour moi, oui.

**Comment by Alex-D** [comment]
Pour moi, c'est pas du front du tout cette issue. C'est au back de retourner _strictement_ ce que le front doit afficher. Le tag est selon moi à retirer.

**Comment by firm1** [comment]
Je reviens sur cette issue. En fait, le masque des message via la page de profil a été fait pour les posts de forum surtout parce que via la page de profil, on ne peut consulter que les posts du forum.

![capture](https://cloud.githubusercontent.com/assets/6066015/3685435/0dd77420-130b-11e4-9956-0ff714707868.PNG)

On a pas de lien qui nous permet de consulter les commentaires des articles et commentaires. Et donc pas besoin de gérer leur masquage ou pas.

Cette issue est donc a fermer.
