### ISSUE TITLE
Envoie email impossible

### ISSUE THREAD

**Issue by tleb** [zestedesavoir/zds-site#929]
Le lien 'communication@zestedesavoir.com' sur la page 'Contact' ne fonctionne pas.
Je ne suis pas connecté.
Quand on envoie un email avec, on reçoit sa:

> Bonjour NOTRE_ADRESSE_MAIL,
> Il se peut que le groupe que vous avez essayé de contacter (com-zeste-de-savoir) n'existe pas ou que vous ne soyez pas autorisé à lui envoyer des messages. Voici quelques-unes des raisons possibles pour lesquelles votre message n'a pas pu être envoyé :
> - Vous avez mal orthographié le nom du groupe.
> - Le propriétaire du groupe l'a peut-être supprimé.
> - Vous devez être abonné avant de pouvoir envoyer des messages.
> - Ce groupe n'autorise pas l'envoi de message.
>   Si vous avez des questions sur ce groupe ou tout autre groupe Google, consultez le centre d'aide à l'adresse http://groups.google.com/support/.
>   Merci,
>   Google Groups 
> 
> ----- Original message -----
> X-Received: by 10.194.200.133 with SMTP id js5mr1076294wjc.1.1402840872806;
>         Sun, 15 Jun 2014 07:01:12 -0700 (PDT)
> Return-Path: <NOTRE_ADRESSE_MAIL>
> Received: from vps41247.ovh.net (www.zestedesavoir.com. [176.31.187.88])
>         by gmr-mx.google.com with ESMTP id iz18si224334wic.3.2014.06.15.07.01.12
>         for com-zeste-de-savoir@googlegroups.com;
>         Sun, 15 Jun 2014 07:01:12 -0700 (PDT)
> Received-SPF: softfail (google.com: domain of transitioning NOTRE_ADRESSE_MAIL does not designate 176.31.187.88 as permitted sender) client-ip=176.31.187.88;
> Authentication-Results: gmr-mx.google.com;
>        spf=softfail (google.com: domain of transitioning NOTRE_ADRESSE_MAIL does not designate 176.31.187.88 as permitted sender) smtp.mail=NOTRE_ADRESSE_MAIL
> Received: from localhost (localhost.localdomain [127.0.0.1])
>         by vps41247.ovh.net (Postfix) with ESMTP id 6B06A2BC30C4
>         for communication@zestedesavoir.com; Sun, 15 Jun 2014 16:01:12 +0200 (CEST)
> X-Virus-Scanned: Debian amavisd-new at vps41247.ovh.net
> Received: from vps41247.ovh.net ([127.0.0.1])
>         by localhost (vps41247.ovh.net [127.0.0.1]) (amavisd-new, port 10024)
>         with ESMTP id AFeKmPX92_8e for communication@zestedesavoir.com;
>         Sun, 15 Jun 2014 16:00:42 +0200 (CEST)
> Received: from SNT004-OMC1S20.hotmail.com (snt004-omc1s20.hotmail.com [65.55.90.31])
>         by vps41247.ovh.net (Postfix) with ESMTPS id 5623E2BC30C3
>         for communication@zestedesavoir.com; Sun, 15 Jun 2014 16:00:42 +0200 (CEST)
> Received: from SNT407-EAS272 ([65.55.90.8]) by SNT004-OMC1S20.hotmail.com with Microsoft SMTPSVC(7.5.7601.22701);
>          Sun, 15 Jun 2014 07:00:41 -0700
> X-TMN: [tC0wWtJScXAaobNsRGkrqs2xBlDahfuv]
> X-Originating-Email: [NOTRE_ADRESSE_MAIL]
> Message-ID: SNT407-EAS2725B8409B25FB64E8A3553EC170@phx.gbl
> MIME-Version: 1.0
> From: =?utf-8?B?VGjDqW8gTGVicnVu?= <NOTRE_ADRESSE_MAIL>
> To: "=?utf-8?Q?communication@zestedesavoir.com?="
>          communication@zestedesavoir.com
> Subject: =?utf-8?Q?Contact_communication?=
> Importance: Normal
> Date: Sun, 15 Jun 2014 14:00:14 +0000
> Content-Type: multipart/alternative;
>         boundary="_B8E8B06D-985A-4C73-978C-07587B564784_"
> X-OriginalArrivalTime: 15 Jun 2014 14:00:41.0169 (UTC) FILETIME=[31631410:01CF88A2]
> NOTRE_MESSAGE

**Comment by Alex-D** [comment]
> Vous devez être abonné avant de pouvoir envoyer des messages.

Je pense que le soucis est là. Faudrait qu'on ajoute le bot dans la liste des autorisés du groupe.

**Comment by ArnaudCalmettes** [comment]
Qui peut s'en charger de ça ? C'est l'affaire de 10 secondes a priori.

**Comment by SpaceFox** [comment]
Qui a accès à la gestion de cette liste ?

Si le bureau de l'association ne l'a pas encore, c'est le moment de leur
filer un double des clés :)

2014-06-28 15:34 GMT+02:00 ArnaudCalmettes notifications@github.com:

**Comment by Alex-D** [comment]
Tous les gens de la com y ont accès. Je les laisse faire ça.

**Comment by ShigeruM** [comment]
C'est une issue à tiroirs en fait.

1- Je viens de changer les paramètres pour permettre à n'importe qui d'écrire au google group com-zeste-de-savoir@googlegroups.com, tout en conservant le contenu de ce group privé. Ça fonctionne dans le sens où le group reçoit bien le mail. Le group peut même répondre à l'email. Mais ensuite la discussion s'arrête là : la personne ne peut plus répondre au group. C'est donc inutilisable pour une adresse de communication.

2- En écrivant à l'adresse communication@zestedesavoir.com, le mail arrive dans les spams du google group. Problème de configuration à ce niveau ? Pour ne pas louper le mail, il faut alors que le propriétaire du group (en l'occurrence le compte gmail ZdS) aille sur l'interface d'admin de Google group et autorise la "publication". Autant dire qu'il peut se passer un sacré bout de temps pour qu'on se rende compte que quelqu'un cherche à nous contacter.

3- Je pense qu'un Google group n'est tout simplement pas fait pour ça. C'est parfait pour une ML au sein d'un groupe restreint ou à l'inverse complètement ouvert, mais pas les deux à la fois comme ici. A mon avis on aurait tout à gagner à utiliser une adresse mail simple, gérée par la comm :
- soit le compte gmail de ZdS, déjà utilisé pour les différents envois de mails jusqu'à présent (les invitation aux bêta, les mails aux auteurs, etc.) ;
- soit un autre compte (comm-sdz@gmail.com par exemple) si on veut séparer les choses et s'éviter les potentiels spams dû à la diffusion sur une page publique de l'adresse mail dans un mailto.

Dans les deux cas on peut imaginer des redirection avec des belles adresses en @zestedesavoir.com.

Là tout de suite j'ai tendance à préférer conserver l'adresse gmail actuelle, gérée par l'équipe comm, pour tout y centraliser. C'est donc cette adresse qui serait utilisée dans la page Contact. Le Google Group resterait très utile, mais uniquement pour les échanges au sein de l'équipe comm (en tant que ML donc).

D'autres avis ?

**Comment by ArnaudCalmettes** [comment]
Ça me semble la bonne solution.

Au moins temporairement, en tout cas.

**Comment by Alex-D** [comment]
Je vote pour l'utilisation de l'adresse de communication actuelle. Evitons d'avoir 36 comptes différents.

> comm-sdz@gmail.com

comm-zds@gmail.com

Fix'd !

**Comment by geoffreyc** [comment]
Ya aussi l'option de pas passer par gmail dutout, et d'avoir une boite
directement sur le serveur. Avec l'avantage de pouvoir renvoyer des emails
a partir de (from:)comm@zestedesavoir.com

**Comment by vhf** [comment]
> Avec l'avantage de pouvoir renvoyer des emails a partir de (from:)comm@zestedesavoir.com

Note que tu peux aussi faire ça avec gmail.

**Comment by geoffreyc** [comment]
On peut sans avoir le "xxx@xxx.com on behalf of yyy.yyy.com ? (en gros que
le header "sender" soit pas l'adresse gmail?)

2014-06-29 20:18 GMT+01:00 victor felder notifications@github.com:

**Comment by Alex-D** [comment]
Oui, je le fais avec des domaines custom et ça fonctionne bien depuis GMail :)

**Comment by SpaceFox** [comment]
Reste à faire si je comprends bien : paramétrer l'adresse de comm pour utiliser comm-sdz@gmail.com .

Je suppose que c'est dans le fichier de conf.

C'est fait ce soir.

**Comment by geoffreyc** [comment]
Pour tout ce qui est redirection de mail ca se passe dans mysql.

2014-07-02 10:21 GMT+01:00 SpaceFox notifications@github.com:

**Comment by SpaceFox** [comment]
OK ça se passe dans MySQL, mais on fait comment ?

Est-ce qu'on est **certains** que la tâche à faire c'est rediriger communication@zestedesavoir.com vers comm-sdz@gmail.com ? Personnellement j'étais resté à "changer l'adresse dans le code" !

**Comment by firm1** [comment]
J'ai redirigé  communication@zestedesavoir.com vers comm-sdz@gmail.com

Sauf que comm-sdz@gmail.com n'existe pas !

**Comment by SpaceFox** [comment]
-zds pas -sdz :D

**Comment by firm1** [comment]
Oh kay

**Comment by firm1** [comment]
Je confirme l'adress  comm-zds@gmail.com n'existe pas. Qui était censé la créer ? fallait pas plutot rediriger vers l'actuelle boite générale de clementine pour tout centraliser ?

**Comment by SpaceFox** [comment]
Là, seule l'équipe de comm' pourra répondre.

**Comment by firm1** [comment]
> Là, seule l'équipe de comm' pourra répondre.

C'est leur boulot non ? je croyais que le but c'était de pas polluer la terre des agrumes.

**Comment by Alex-D** [comment]
Faut tout balancer sur zestedesavoir+communication@gmail.com

**Comment by ShigeruM** [comment]
> fallait pas plutot rediriger vers l'actuelle boite générale de clementine pour tout centraliser ?

C'est ça. Il n'existe qu'une adresse : zestedesavoir@gmail.com. On peut utiliser un alias zestedesavoir+communication@gmail.com si vous voulez.

Le but est bien de tout centraliser et d'éviter de créer un autre compte google. Comme c'est l'équipe comm qui gère la boîte mail actuelle, ça aurait fait sérieusement doublon.

**Comment by Ge0** [comment]
J'ai mis à jour la redirection de communication@zestedesavoir.com à zestedesavoir+communication@gmail.com. Elle fonctionne. On est bon ?

**Comment by ShigeruM** [comment]
Je viens de tester, c'est tout bon. Merci.

**Comment by Ge0** [comment]
On ferme l'issue du coup, non ?
