### ISSUE TITLE
error triggered while accessing private messages as a guest

### ISSUE THREAD

**Issue by Ge0** [zestedesavoir/zds-site#93]
Accédez à la page http://zestedesavoir.com/mp/ sans être connecté, vous aurez l'erreur suivante :

int() argument must be a string or a number, not 'SimpleLazyObject'

Si l'on part du principe qu'aucune erreur de ce genre ne doit apparaître en production (afin de ne pas afficher des informations plus ou moins sensibles) alors c'est à corriger. :P

**Comment by cgabard** [comment]
> Si l'on part du principe qu'aucune erreur de ce genre ne doit apparaître en production (afin de ne pas afficher des informations plus ou moins sensibles) alors c'est à corriger. :P

Indeed, Une 403 serait plus adapté

**Comment by cgabard** [comment]
En fait, dans l'idéal, une page demandant l'autentification serait le must

**Comment by firm1** [comment]
[Fixé et déployée](https://github.com/Taluu/ZesteDeSavoir/commit/914f2af3a88b06b89d36bfde4805efe316794e52).

Merci, je ferme.

**Comment by Ge0** [comment]
Putain tu m'as devancé @firm1.

**Comment by firm1** [comment]
La prochaine fois, dès que tu commence à bosser dessus, assigne toi la tache ou marque la en "In progress", je saurai que quelqu'un est dessus.

désolé de t'avoir coupé l'herbe, mais c'était trop facile :-)
