### ISSUE TITLE
Impossible regénérer jeton

### ISSUE THREAD

**Issue by tleb** [zestedesavoir/zds-site#930]
Je me suis inscrit, mais pour x raison je n'ai pas pu utiliser le jeton à temps: le site me dit que le jeton à expiré, je clique sur le lien pour en générer un nouveau, et je tombe sur une page 'Internal Server Error'. Impossible de me connecter.
Pseudo d'inscription: Forever

**Comment by Alex-D** [comment]
Il me semble qu'il y a un fix déjà en cours là dessus.

**Comment by Alex-D** [comment]
Celui là : https://github.com/zestedesavoir/zds-site/pull/917
