### ISSUE TITLE
Passer normalize.css en dépendance bower

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#933]
Actuellement, normalize est inclu brutalement via une copie locale. L'idéal serait d'arriver au même résultat mais en ayant normalize en tant que dépendance bower.

**Comment by sandhose** [comment]
A noter que la plupart des portages de normalize pour SCSS passent par Compass... Il faut donc utiliser [ce portage](https://github.com/hail2u/normalize.scss), qui ne nécessite pas compass :)
Je ferais ça demain rapidement :)

**Comment by Alex-D** [comment]
Au pire on peut mettre le version CSS brut non ?

**Comment by sandhose** [comment]
Pas possible d'import du CSS via SASS... Faut le charger dans une feuille de style séparée...

**Comment by Alex-D** [comment]
Du CSS, c'est du SASS. Donc il suffit de faire @import [le chemin]

non ?
