### ISSUE TITLE
Adapter les listes de topics aux mobiles

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#935]
Il faudrait rendre fluide le design de la liste des forums/topics/galeries/mp (tout ça se base sur le même code CSS).

**Comment by ArnaudCalmettes** [comment]
Qu'est-ce que t'entends par "fluide" ?
Si c'est juste "utilisable", alors oui, c'est bloquant V1. Si c'est "rapide", alors c'est effectivement pour la V1 mais pas bloquant. À l'heure actuelle, à part les infos qui se dégueulent les unes sur les autres, la navigation dans les listes de threads est tout à fait correcte pour une V1.

**Comment by Alex-D** [comment]
Fluide est le mot classe et français qui correspond au "responsive".

En l'état, c'est juste pas utilisable, donc il faut le rendre "responsive" pour que ce soit utilisable :)

> à  part les infos qui se dégueulent les unes sur les autres

C'est dommage d'avoir un site clean et juste cette page qui part dans tous les sens :)

**Comment by ArnaudCalmettes** [comment]
"pas utilisable" : si, ça l'est.

 C'est crade, mais utilisable. "Pas utilisable" c'est comme le bouton de notifications d'OC sur mobile, qui n'est pas cliquable depuis les 3/4 des pages, et qui t'oblige à taper directement l'url pour accéder à la page de notifs. 

Là, je peux toujours naviguer sur mobile sans problème, même s'il y a des glitches visuels. C'est ça la différence entre "utilisable" et "pas utilisable". Bon, après, je suis d'accord qu'il faut corriger l'affichage actuel parce qu'en l'état c'est pas V1-ready sur mobile, mais en dehors de ce glitch "trop visible", toute autre question d'optimisation est non-bloquante pour la V1.

**Comment by Alex-D** [comment]
Désolé, j'avais pas vu que j'avais fix le problème en fait =D

Avant ça se chevauchait de partout et c'était réellement inutilisable. Je viens de tester et en effet, sans m'en rendre compte j'ai rendu le truc potable :-°

**Comment by SpaceFox** [comment]
> Désolé, j'avais pas vu que j'avais fix le problème en fait =D

Du coup, c'est corrigé ou non ?

Si non, que reste-t-il à faire, qu'on puisse savoir que faire de cette issue ?

**Comment by Alex-D** [comment]
Non, du tout, mais je vais m'y atteler très bientôt, une fois que les issues importantes seront corrigées.

Tout est à vérifier et à ajuster sur mobile.

**Comment by SpaceFox** [comment]
Corrigé, mergé, fermé.
