### ISSUE TITLE
Corriger les bugs sur le navigateur natif d'Android sur l'accueil

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#936]
Les textes ne sont pas limités en largeur comme sous Chrome, du coup on peut scroller et ça casse toute la mise en page.

**Comment by SpaceFox** [comment]
Quelqu'un pour ce bug front ?

**Comment by Alex-D** [comment]
Si on refait la page d'accueil, ça ne sert à rien de corriger ce bug. Il n'est présent que sur le navigo natif d'Android.

Donc mon avis est d'avancer sur la nouvelle page d'accueil, l'intégrer et comme ça, cette issue on en parle plus.

Aussi, j'avais mis v 1.0, mais ça me semble pas important, ça peut être reporté à 1.x vu que ça ne bloque pas la navigation.

**Comment by SpaceFox** [comment]
Si tu le dis.

**Comment by poulp** [comment]
On laisse ouvert le ticket ou on laisse tomber avec la zep4 ?

**Comment by gustavi** [comment]
On ferme le jour où la ZEP-04 est validée. Pour le moment, ça reste un bug.

**Comment by Situphen** [comment]
Quelqu'un pour vérifier que ce bug est corrigé par #2646 ?

**Comment by SpaceFox** [comment]
La note de PR prétend que oui. Je fais quoi ? Je laisse ouvert ou je ferme ?

**Comment by Eskimon** [comment]
QQun a encore un navigateur internet legacy sur son Android ?

**Comment by SpaceFox** [comment]
Je devrais pouvoir tester sur un des téléphones du boulot, sauf qu'on a pas la moindre idée de la version d'Android en cause et donc que le bug n'a aucun sens.

**Comment by Eskimon** [comment]
Considère un Android kitkat pas trop récent (avant qu'il supprime le navigo legacy) mais a jour (pour que le composant WebView soit a jour)

https://developer.android.com/about/dashboards/index.html

**Comment by SpaceFox** [comment]
En fait, on va la faire à l'envers : les seules références à un browser Android qu'on a le dernier mois (1.19% des visites) c'est "Android browser 4.0". Donc il suffit de tester avec celle-ci - je suppose que ça correspond à un Android 4.0 ?

**Comment by Eskimon** [comment]
bah voila partons comme ca ^^

**Comment by SpaceFox** [comment]
Je n'ai plus de téléphone Android 4.0 au boulot, et même Genymotion ne propose plus d'image de ce type.

Est-ce que quelqu'un a encore ça dans un coin pour tester ?
Si non, on déclare que "tant pis pour les 1.19% des utilisateurs qui ont encore cette chose".

**Comment by Eskimon** [comment]
> Si non, on déclare que "tant pis pour les 1.19% des utilisateurs qui ont encore cette chose".

Pour moi on rentre dans le même cas que "Les gens qui utilisent IE8 ou un Firefox de 2010" donc oui.
