### ISSUE TITLE
Suppression d'une galerie entraîne suppression du tutoriel/article

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#937]
Lorsque l'on supprime une galerie et qu'elle est liée à un tutoriel, ce tutoriel là est supprimé au passage, sans aucun message préventif.

La solution partielle mais immédiate que j'ai trouvé est de rajouter une boite modale de confirmation : il n'y en a pas actuellement.

Par contre, est-ce que le comportement back est celui attendu ? Pour moi ça semble cohérent comme comportement. A la limite, il ne faudrait pas pouvoir supprimer une galerie si elle est liée à un tuto/article : c'est pour cela même que j'ai rajouté le tag Back.

Le soucis doit être le même pour les articles je présume : à vérifier/patcher au passage.

**Comment by ArnaudCalmettes** [comment]
Pour moi, la suppression de la gallerie devrait être interdite si le tuto existe encore, avec un message d'erreur qui explique qu'il faut supprimer le tuto pour supprimer la gallerie.

**Comment by Alex-D** [comment]
Il faudrait alors que :
- le back interdise ce cas
- dans l'idéal, le front soit informé via une variable que la galerie n'est pas supprimable et qu'on n'affiche pas la checkbox du coup.

**Comment by pierre-24** [comment]
+1 pour ta dernière proposition, Alex-D

**Comment by ArnaudCalmettes** [comment]
OK, faisons ça pour la V1.

**Comment by Alex-D** [comment]
Il a été signalé que la suppression de l'illustration du tuto entraînait également la suppression de celui-ci.

A mon avis il y a un lien en cascade à retirer. Sinon, il faut autoriser la suppression de cette image qui aura pour effet de simplement ne plus avoir d'icône pour le tutoriel.

**Comment by ArnaudCalmettes** [comment]
Pour moi c'est une issue indépendante
Bloquante bêta publique, celle là.

**Comment by Alex-D** [comment]
J'ai créé l'issue #941 pour l'icône du tuto/article.

**Comment by firm1** [comment]
Fixé
