### ISSUE TITLE
[Post] On peut poster un message "vide"

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#94]
Dans le forum ou les commentaires, c'est impossible de poster un message vide, mais c'est possible de poster un message ne contenant que des espaces.

Un petit `trim()` avant le check, côté front et côte back, ne serait pas de refus.

**Comment by firm1** [comment]
Je m'en occupe.

**Comment by firm1** [comment]
Le problème est résolu. Je ferme
