### ISSUE TITLE
Suppression de l'illustration d'un tutoriel/article supprime le tutoriel/article associé

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#941]
Lorsque l'on supprime l'illustration d'un tutoriel dans la galerie qui le contient, le tutoriel associé est supprimé.

Vaut également pour les articles je pense.

Etroitement lié à la #937

**Comment by GerardPaligot** [comment]
Je suis sur une bonne piste. Je prends.

**Comment by Alex-D** [comment]
Ca a été testé et mergé, je ferme donc.
