### ISSUE TITLE
Déplacer les tags des sujets devant le titre

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#944]
Il faudrait déplacer les tags des sujets devant le titre, en faisant attention à ne pas mélanger les liens (titre + description = un seul lien, tag = un lien par tag).

Pour autant il ne faut pas que la navigation à la tabulation soit dégradée.

**Comment by firm1** [comment]
Du nouveau ici ? ça serait vachement sympa d'implémenter ça.

**Comment by SpaceFox** [comment]
Corrigé, mergé, fermé.
