### ISSUE TITLE
Déplacement d'une partie : erreur 500

### ISSUE THREAD

**Issue by jcval** [zestedesavoir/zds-site#947]
Le bug se produit lorsque l'on essaie de descendre une partie alors que le tuto n'en contient qu'une seule. On obtient une erreur 500.

http://zestedesavoir.com/forums/sujet/335/deplacement-dune-partie-erreur-500/

**Comment by Alex-D** [comment]
C'est le template qui ne devrait pas permettre de descendre, par contre l'erreur 500 devrait être une 403.

Du coup je met en Front et en Back et je met en bloquant V1 car ça devrait être rapide à résoudre, libre à nohar de changer s'il le souhaite.
