### ISSUE TITLE
Uniformiser les pages statiques en leur contenu

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#948]
Le contenu des pages statiques n'est pas forcément très cohérent.

On signale sur le forum : 

> Sur les CGU :
> - manque une majuscule au point n°10
> - uniformiser entre conditions générales d'utilisation et Conditions Générales d'Utilisation

Je pense qu'il serait bon qu'une personne relise toutes les pages statiques pour uniformiser tout ce genre de petites choses.

**Comment by Eskimon** [comment]
plop @vulser peut etre ?

**Comment by jcval** [comment]
J'ai relu les GCU, c'est les deux seuls points que j'ai trouvé.

Pour les autres pages statiques rien à signaler. Peut être juste expliquer en deux mots sur la page "L'association" en quoi consiste l'adhésion. Là en l'état, tu tombe sur un formulaire et tu ne sait pas si à l'étape suivante on ne va pas te faire dégainer ta CB.

**Comment by Alex-D** [comment]
On était également d'accords en interne qu'il fallait préciser davantage cette page, mais c'est un peu resté sur le côté pour l'instant.

**Comment by 0hexit** [comment]
En relisant les CGU, j'ai remarqué quelques erreurs de plus : 
- Au point n°4, il est écrit : "Le membre est donc tenu de préserver la confidentialité de ces données et **à** supporter toutes les conséquences pouvant résulter de leur divulgation (qu'elle soit volontaire ou non)." Il faudrait mettre : "Le membre est donc tenu de préserver la confidentialité de ces données et **de** supporter toutes les conséquences pouvant résulter de leur divulgation (qu'elle soit volontaire ou non)." car "être tenu à" est toujours suivi d'un groupe nominal.
- Au point n°5.4, il manque un espace après la dernière virgule : "(nom, prénom, adresse email,...)" -> "(nom, prénom, adresse email, ...).
- Toujours au point n°5.4, j'aurais mis un point puisqu'on énonce une autre idée : "Le membre s'engage expressément à ne pas publier la photographie ou des informations privées d'une tierce personne, il s'engage par ailleurs à ne pas usurper l'identité d'un tiers et à respecter scrupuleusement les règles du site, les conditions inscrites dans le présent document ainsi que la législation en vigueur." -> "Le membre s'engage expressément à ne pas publier la photographie ou des informations privées d'une tierce personne. Il s'engage par ailleurs à ne pas usurper l'identité d'un tiers et à respecter scrupuleusement les règles du site, les conditions inscrites dans le présent document ainsi que la législation en vigueur."

Dans la page "À propos", il faudrait changer "tout celà" par "tout cela".

Dans la page "Association", il faudrait mettre "A la suite du changement" au lieu de "Suite au changement".

Dans la page "Contact", il faudrait changer "developpeurs" en "développeurs".

Voilà :)

**Comment by Alex-D** [comment]
Pour le coup, tu peux faire une PR, promis je ne fais pas les mêmes corrections en même temps :D

**Comment by Alex-D** [comment]
Faites des bisous à @vulser qui viens de nous corriger tout ça :)
