### ISSUE TITLE
Import d'un tutoriel depuis l'archive Markdown

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#949]
Actuellement, on peut télécharger une archive Markdown, mais on ne peux pas la réinjectée par la suite.

Il serait pratique de pouvoir envoyer l'archive (modifiée ou pas) pour mettre à jour son tutoriel.

**Comment by artragis** [comment]
Je réfléchis un peu à cette issue et plus ça vient et plus je me dis que finalement c'est une idée mal définie.
Actuellement comment fonctionne le workflow global pour un BT?
- je crée un big tuto en lui donnant un nom
- je crée un/des parties
- dans ces parties j'ajoute des chapitres
- dans ces chapitres j'ajoute des extraits.

Une fois qu'on a la structure, deux solutions s'offrent à nous et qui sont presque exclusives : 
- exporter le tuto et le continuer hors ligne pour ensuite faire du copier/coller
  - perte du versionnage
  - difficulité de faire de la coédition puisque du coup le membre n°1 qui édite hors ligne risque d'écraser une modif lors de son prochain CC
- éditer en ligne
  - on garde le versionnage et la coédition fonctionnelles à 100% 
  - on perd la possibilité de travailler hors ligne et la sécurité que ça apporte

Mais tu vas me dire "Qu'est-ce que ça a à voir avec l'issue de l'import markdown".
Importer un tutoriel ne pourra dans ton cas se faire qu'à un seul moment : lorsqu'il est créé.
Si la personne crée son tuto pour un autre site et veut l'importer sur le sdz elle est obligée de passer par le copier/coller.
Et comme nous on supporte le renommage des parties, faire un "import pour écraser" ne fonctionnera pas puisqu'il est possible qu'une partie ait été renommé par le coéditeur par exemple.
Sans compter que notre architecture n'est pas du tout normalisée par rapport à ce qui se fait à côté : 
- manifest.json qui risque d'évoluer au fur et à mesure que le site avance (j'ai déjà proposé d'y ajouter l'icône pour versionner cette dernière
- les fichiers introduction/conclusion
- la nécessité de nommer nos dépôts et fichiers markdown pk_slug.md

N'oublions pas que nous utilisons git. Git est un système distribué qui permet l'édition hors ligne.
A mon sens, le jeu des imports/exports ne doit se voir que sous l'angle de la mise à disposition au public du dépôt git.

**Comment by Taluu** [comment]
> A mon sens, le jeu des imports/exports ne doit se voir que sous l'angle de la mise à disposition au public du dépôt git.

Un gros +1, et ce que ce qu'on défend depuis un certain moment. Mais "v42" pour l'instant...

**Comment by Eskimon** [comment]
Question : L'évo de firm1 est maintenant mergée. Garde t'on le ticket ouvert pour les évo futures permettant par exemple l'import avec de nouvelles parties ?

**Comment by Alex-D** [comment]
Je pense que oui, il a dit lui-même ne pas résoudre complètement l'issue.

**Comment by Eskimon** [comment]
Je met ici un mot cle : ZEP-12 (pour me rappeler de revenir ici) . @pierre-24 @artragis vous confirmez que ca sera dedans ?

**Comment by pierre-24** [comment]
Hell yeah, et c'est même déja fait ;)
