### ISSUE TITLE
Question : tableaux et fenêtres modales

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#950]
Je ne comprends pas pourquoi les fenêtres modales sont des tableaux alors qu'il s'agit de données non-tabulaires.

Quelqu'un a-t-il une explication pour le noob que je suis ? Ça peut être utile pour la suite :)

**Comment by Alex-D** [comment]
Tu parles de quelles fenêtres modales ? Les miennes n'en sont pas, peut-être parles-tu des modales de l'éditeur ?

**Comment by Alex-D** [comment]
Je viens de regarder le code, je ne comprends pas ce que tu veux dire, je ne trouve nulle part des tableaux pour faire des modales :(

**Comment by SpaceFox** [comment]
OK, après vérification c'est moi qui n'avait pas les yeux en face des trous ce matin.

**Comment by Alex-D** [comment]
Tu me rassures :D

C'est niquel alors !
