### ISSUE TITLE
Les tests gulp ne sont pas lancés par travis

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#952]
Actuellement travis fait beaucoup de truc, il installe même node, npm, bower, ... mais il oublie de lancer les tests avec la commande `gulp test`.

La conséquence c'est qu'on a pas mal d'incohérences qui peuvent passer coté JS

**Comment by Alex-D** [comment]
Ping @sandhose

**Comment by firm1** [comment]
Oups, je crois qu'il sont fait par [cette ligne](https://github.com/zestedesavoir/zds-site/blob/beta-0.2/.travis.yml#L43) en fait.

Fausse alerte, désolé

**Comment by Alex-D** [comment]
Je confirme, cf ici : https://github.com/zestedesavoir/zds-site/blob/beta-0.2/package.json#L9

**Comment by sandhose** [comment]
Sachant que ces tests sont actuellement... vide... :-°

**Comment by pierre-24** [comment]
Sorry, ce commit ne concernait pas ce bug.
