### ISSUE TITLE
La pagination ne prends pas en compte les éventuels paramètres en GET

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#953]
Lorsque l'on fait une recherche ou que l'on applique des filtres, les paramètres sont passés dans l'URL. Le template de pagination actuel ne prends pas en compte ces paramètres.

Il faut donc rajouter les paramètres en GET existants dans l'URL des différentes pages.

Problème trouvé dans l'issue #708 mais qui touche tous les endroits où la pagination est utilisée.

**Comment by artragis** [comment]
Spacefox, attends deux secondes. Mon test n'a pas été aussi concluant que je ne le pensais. A peine ai-je rebuildé les outils front que la fenêtre modale de la recherche ne prenait plus en compte la requête.

**Comment by SpaceFox** [comment]
> _<

Je ne sais pas dé-merger...

**Comment by artragis** [comment]
Moi non plus mais comme je l'ai dit, c'est quand j'ai rebuildé les outils front que ça a merdé.
Il se peut que ça soit mon environnement qui merde plutôt que la PR de Alex.
A moins qu'il voit lui même qu'il y a une erreur.

**Comment by Alex-D** [comment]
> la fenêtre modale de la recherche

Je n'ai rien compris là.

**Comment by artragis** [comment]
tu lances une recherche où il y a beaucoup de résultat.
tu cliques sur les "..." et tu as une modale
cette dernière ne prend pas le paramètre ?q=tarecherche.

**Comment by Alex-D** [comment]
C'est un problème différent alors. Ca n'a pas été introduit par cette PR. Et cette PR corrige le templating.

**Comment by artragis** [comment]
Bah c'est juste que j'ai voulu bien faire hein, t'inquiète. Comme la PR parlait des "..."(puisqu'elle corrigeait 3 issues), bah j'ai signalé.
Et comme en plus le problème c'est que la boîte modale ne prend pas en compte le param ?q=tarecherche c'est lié.

**Comment by Alex-D** [comment]
Oui, mais du coup c'est du JS, c'est lié mais ça ne concerne pas le même endroit. Du coup, pas besoin de "dé-merger", ça n'introduit aucun bug :)

Juste qu'il y en a un qui est encore là.

**Comment by artragis** [comment]
Ok, effectivement pas besoin de démerger puisque le bug était là avant.
Par contre faut pas clore l'issue ^^. Je vais voir ce soir si je peux pas y toucher.
Faut-il mettre un CSRF à la modale ou pas?

**Comment by SpaceFox** [comment]
Est-ce qu'on a une ETA pour cette issue ?

**Comment by artragis** [comment]
ETA?

**Comment by SpaceFox** [comment]
Estimated Time of Arrival

2014-07-02 11:20 GMT+02:00 artragis notifications@github.com:

**Comment by artragis** [comment]
L'issue en elle même concerne :
le bug de la pagination en elle même
le bug des "...".
Le premier est terminé.
Le second le sera sûrement ce soir.

**Comment by artragis** [comment]
J'ai une copie à rendre. J'attends un review pour valider tout ça (notamment mon code JS qui est pas terrible, je pense) et le defreeze pour faire une PR : 
https://github.com/artragis/zds-site/tree/fix_modal_supension

**Comment by Alex-D** [comment]
Ta façon de faire n'est pas bonne du tout en fait. Je m'en charge ne t'inquiètes pas de ça. Il y a tout un tas d'issues back à régler ;)

**Comment by artragis** [comment]
J'aurai quand même aimé connaître la bonne façon.
Néanmoins, je suis rassuré, parce que sur irc quelqu'un m'a dit que pour lui mon code était "bon", et même moi je doutais de sa grande qualité. Mais j'avoue que j'ai trop peu l'habitude de twig...
Pour les issues back, je verrai ce que je peux faire quand la béta publique sera lancée, parce que là y'a pas mal de chose qui ne sont aps de mon ressort...

**Comment by SpaceFox** [comment]
Corrigé + mergé = fermé
