### ISSUE TITLE
Attention : Travis affiche des warnings

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#956]
Je ne sais pas si ça inquiète grand monde, mais Travis affiche des warning et ça m'inquiète.

Visiblement les erreurs concernent crispy, mais en regardant de plus près on se rend compte que le problème vient de l'interface entre la chaise et le clavier.

A analysant les builds de travis, je me suis rendu compte que le problème est apparu pour la première fois dans [cette PR](https://github.com/zestedesavoir/zds-site/pull/840) et plus précisément à partir de [ce commit](https://travis-ci.org/zestedesavoir/zds-site/builds/27322799).

PS : je classe ça en tant que regression.

**Comment by Eskimon** [comment]
J'en parlais il y a quelques jours:

http://zestedesavoir.com/forums/sujet/314/warning-dans-les-test-django/
