### ISSUE TITLE
Faire un template commun pour les courriels HTML

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#957]
Une base de template HTML m'a été suggéré pour les courriels : http://dl.free.fr/iVutn3W5l

L'idée serait d'avoir le logo et les mentions légales ou ce genre de choses autour de tous les courriels HTML.

Je m'adresse aux fous de la configuration des courriels : est-ce qu'on peut avoir un contenu différent entre text et HTML, sans se faire passer pour un spam et autre ?

**Comment by geoffreyc** [comment]
Techniquement, la plupart des filtres spam compare le texte du html et le
texte du "text" et si le contenu varie de beaucoup, des points sont ajoutés
au score SPAM.

Après ca dépend beaucoup du contenu. Si + de 50% du html == au text, on
devrait pas avoir de soucis.

2014-06-16 14:17 GMT+01:00 Alexandre Demode notifications@github.com:

**Comment by SpaceFox** [comment]
Cette idée n'a pas l'air de motiver quiconque depuis plus d'un an. Je la considère donc comme abandonnée, si ça intéresse quelqu'un, il suffit de ré-ouvrir.
