### ISSUE TITLE
Les invités ne peuvent pas faire de recherche

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#960]
La recherche est actuellement cassé pour les utilisateurs non connectés.

En allant sur cette page `/rechercher/?q=bienvenue` on a une erreur.

Indice : le bug ne se produit que lorsque la requete est censé retourner un résultat. Si il y'a pas de résultat (voir `/rechercher/?q=bienvenue+p%C3%A9p%C3%A9`), la page marche bien.

Je la classe en regression, car je soupçonne que le problèm est arrivé pendant [cette PR](https://github.com/zestedesavoir/zds-site/pull/909) et je suis certain que ça fonctionnait avant.

**Comment by Alex-D** [comment]
C'est assez louche, il n'a pas touché aux autorisations :(

**Comment by sandhose** [comment]
Je dirais même que c'est plus un bug de back que de front...

**Comment by firm1** [comment]
> C'est assez louche, il n'a pas touché aux autorisations :(

Quand tu regarde le diff de la PR que je cite, y'a pas mal de fichiers qui ont été crées dans le back. Pour le coup, il va falloir passer un coup derrière. 

Pour information pour @sandhose le template crée `htmltotext` existe déjà sous django sous le nom de `striptags`.

**Comment by sandhose** [comment]
> Quand tu regarde le diff de la PR que je cite, y'a pas mal de fichiers qui ont été crées dans le back. Pour le coup, il va falloir passer un coup derrière.

Pas vraiment, je crée un form et une vue custom pour Haystack, rien qui touche aux autorisations...

> Pour information pour @sandhose le template crée htmltotext existe déjà sous django sous le nom de striptags.

Pinaise je l'avais pas vu celui la!

**Comment by Alex-D** [comment]
Quitte à créer un filtre, crées en un qui utilise `<mark>` à la place de la classe "higtlight"

**Comment by firm1** [comment]
> Pas vraiment, je crée un form et une vue custom pour Haystack, rien qui touche aux autorisations...

ça ne touche peut-etre pas aux autorisations, mais si tu as zappé un `is_authenticated` quelque part, il y'aura un bug.
A l'instant ou un views.py est crée/modifié, c'est susceptible de créer un bug dans le back (et je pense que le bug vient de là).

'fin, normalement si tu postes le log de l'erreur que tu obtiens en local, on devrait pouvoir retrouver simplement la cause.

**Comment by sandhose** [comment]
J'arrive pas à reproduire le bug en local, la recherche en invité marche très bien chez moi... Tu es sur que c'est pas un problème avec solr ?

**Comment by firm1** [comment]
De ce que j'ai vu c'est pas que les invités qui ont se souci.

Il me semble que le bug vient de la pagination. Pour reproduire le bug
essaye de créer en local une pelletée de sujet sur le même theme, reindexe
les et lance la recherche dessus.

Je peux pas trop verifier, je n'ai pas d'outils de développement a ma
disposition.

**Comment by sandhose** [comment]
Nan je pense vraiment que le problème viens de Haystack, et de l'index solr... Par exemple, [cette recherche](http://zestedesavoir.com/rechercher/?q=test), qui comporte pourtant 16 pages de résultats marche très bien... Par contre, [la page 2 de cette même recherche](http://zestedesavoir.com/rechercher/?q=test&page=2) plante, alors que la [page 3](http://zestedesavoir.com/rechercher/?q=test&page=3) marche... Très, très bizarre...

**Comment by firm1** [comment]
En passant la prod en mode debug pendant 2 sec, j'ai réussi à capturer la stack.

Tu as oublié de vérifier que les objets ne sont pas None avant de les afficher.
Tu dois faire un gros `{% if result %}` avant de commencer à utiliser l'objet en lui même (Même si je ne vois pas pourquoi result serait null.). Idem pour `result.objet`, etc.

![stack](https://cloud.githubusercontent.com/assets/6066015/3298688/138e9b82-f605-11e3-98f3-50a65a683135.PNG)

**Comment by Eskimon** [comment]
Ca a l'air tout bon ca ! On ferme ?

**Comment by ArnaudCalmettes** [comment]
Ah bah oui, ça faisait 4 jours que l'issue était ouverte alors que la PR était mergée... J'aime bien les surprises quand elles vont dans ce sens-là.
