### ISSUE TITLE
Déplacer des extraits provoque une erreur 500 

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#962]
Comme dit sur [le site](http://zestedesavoir.com/forums/sujet/348/deplacer-des-extraits-provoque-une-erreur-500/), il y a un problème sur le changement de l'ordre des extraits : une erreur 500 est causée par une typo dans le nommage de la fonction `get_extracts` [ici](https://github.com/zestedesavoir/zds-site/blob/beta-0.2/zds/tutorial/models.py#L617). 

Une fois l'erreur 500 réparée, on peut se rendre compte que changer l'ordre est inopérant, de toute façon. 

En effet quoi qu'on fasse les extraits ne bougent pas.

**Comment by Alex-D** [comment]
Lié à la #947 mais différent.

A la limite, corriges partiellement la #947 côté back pour retirer la 500, ça sera déjà ça. Moi je vais m'occuper de disable "Descendre" et comme ça, ça fera une partie du problème de résolu.

**Comment by pierre-24** [comment]
Si @Alex-D c'est ocuppé du front, j'ai trouvé le problème dans le back, qui me permet de fixer l'issue #962 et la #947 par effet ricochet. 

Le problème ? L'ordre des extraits était récupéré sur la structure du `manifest.json`, qui n'était pas mis à jour quand on faisait un déplacement

La solution ? un coup de `maj_repo_extract()` approprié.

Du coup, PR.
