### ISSUE TITLE
Indicateurs supplémentaires Munin

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#963]
Aujourd'hui on surveille des paramètres très génériques à Django, les 2 plus intéressants étant sans doute les performances de la connexion à la BDD et le nombre d'utilisateurs inscrits.

On pourrait surveiller d'autres trucs, comme par exemple :
- Le nombre de tutos / articles / journaux (quand ils existeront)
- Le nombre de topics
- Le nombre de messages
- ... autre chose qui est récupérable simplement (une fois toutes les 5 minutes) et difficilement accessible via Google Analytics

Qu'en pensez-vous ?

(Evidemment, c'est pour une v42)

**Comment by firm1** [comment]
Il me semble que la [PR suivante](https://github.com/zestedesavoir/zds-site/pull/998) fait le boulot.

**Comment by SpaceFox** [comment]
Je confirme, c'est même en prod depuis un moment.
