### ISSUE TITLE
Forever alone dans les MPs

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#968]
Actuellement quand on est seul dans un MP, la zone de texte pour répondre est toujours disponible et donc on peut se répondre à nous même, ce qui ne devrait pas être le cas.

Je taggue en regression car ce comportement était implémenté avant le gros merge d'integration.

**Comment by Alex-D** [comment]
Ca doit être lié à l'antispam non visible je pense.

**Comment by Alex-D** [comment]
C'est mergé et en prod :)
