### ISSUE TITLE
Supprimer la page de teasing

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#976]
Pour être dans les clous, il faut ajouter un lien en bas des mails envoyés via la newsletter pour se désinscrire.

Aussi, il serait souhaitable d'avoir un lien du même genre renvoyant dans les options du membre pour qu'il puisse désactiver les notifs email.

**Comment by Eskimon** [comment]
Si c'est une contrainte légale il faudrait ptet voir a passer ça en bloquant V1 non ?

**Comment by firm1** [comment]
La contrainte légale s'applique à la newsletter, sauf qu'actuellement ZdS n'a pas de newsletter.

La page de teasing n'est pas une page de newsletter (même si on pourra l'utiliser pour ça plus tard)

**Comment by Alex-D** [comment]
A part que c'est indiqué comme tel : "S'inscrire à la newsletter pour être averti des nouveautés"

Du coup, même si on ne s'en sert pas comme tel jusqu'ici, il faut le prévoir.

**Comment by firm1** [comment]
> A part que c'est indiqué comme tel : "S'inscrire à la newsletter pour être averti des nouveautés"

on ne devrait pas l'appeler newsletter. 'fin bref, ce n'est pas bloquant

**Comment by SpaceFox** [comment]
La page de teasing n'a plus lieu d'être, donc cette issue non plus je suppose.

D'ailleurs, il faudra dégager la page de teasing qui est toujours disponible.

Je laisse l'issue ouverte pour régler ce dernier point.

**Comment by cgabard** [comment]
Plutot que de supprimer la page, il faudrait penser à la faire rediriger vers la home. C'est le premier résultat pour "zeste de savoir" sous google actuellement

**Comment by firm1** [comment]
Il faudrait aussi penser a supprimer (ou rediriger) la page http://zds.alex-d.fr/form.html qui est en 6e position des recherches google sur "zeste de savoir".

**Comment by Alex-D** [comment]
@cgabard, c'est ce que je disais dans l'issue. Je propose que ce soit fait par ngnix plutôt que dans le projet.

**Comment by SpaceFox** [comment]
> D'ailleurs, il faudra dégager la page de teasing qui est toujours disponible.

Ça c'est fait.

> Il faudrait aussi penser a supprimer (ou rediriger) la page http://zds.alex-d.fr/form.html qui est en 6e position des recherches google sur "zeste de savoir".

@Alex-D que peux-tu faire pour ça ?

**Comment by Alex-D** [comment]
Je supprimerais tout ça quand j'aurais un ordi en mettant une redirection vers ZdS

**Comment by Eskimon** [comment]
La page de teasing est parti et redirige bien, je ferme :)
