### ISSUE TITLE
[Tuto] Liens vers chapitres précédents et suivants

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/zds-site#98]
Les liens vers les chapitres précédents et suivants ne fonctionnent pas dans un tuto, ils pointent vers la page courante. Exemple : 
=> http://zestedesavoir.com/tutoriels/10/les-maths-pour-tous/niveau-5/les-nombres-relatifs/

Où les liens `« Priorités, développements et factorisations` et `Les fractions (calculs et comparaisons) »` posent ce problème.

**Comment by firm1** [comment]
[Bug corrigé](https://github.com/Taluu/ZesteDeSavoir/commit/dac938e62546e8729f788aaf931f696307cfd6c4).
