### ISSUE TITLE
Appliquer une longueur minimale à la justification d'un signalement de message

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#981]
Lorsque l'on signale un message, on peut ne pas justifier l'alerte.

Ca me semble peu judicieux, et ça peut être pénible pour les modérateurs de ne pas avoir un petit message qui explique rapidement le soucis.

**Comment by Eskimon** [comment]
Je prends !!

La limite a trois caractère ca devrait suffire non ? (genre le mec signal "Pub") ?

**Comment by Eskimon** [comment]
A ce propos : Si lors de la résolution le staffeux se contente de résoudre sans laisser de message, doit-on tout de même envoyer le MP de résolution (ça fait juste du spam inutile non ?)

**Comment by amorison** [comment]
Une solution pourrait être de pré-remplir ce champ avec un truc du genre "Merci pour ton alerte, c'est réglé !", et de laisser au modo le soin de personnaliser, non ?

**Comment by Alex-D** [comment]
Il faudrait éviter de tout mélanger, l'issue de base parle des alertes membre -> modo. Pas de la réponse, et c'est à mon avis le problème principal.

**Comment by Eskimon** [comment]
Assez d'accord @Alex-D , je me doutais que c'est ce qu'on allais me répondre, mais dans le doute (et gain d'un ticket) je proposais quand même :D

**Comment by Eskimon** [comment]
Je me demandais d'ailleurs, est ce que ça vaut le coup de s’embêter a faire un traitement côté back ou pas plus simplement mettre un contrôle sur l'input.

Parce qu'en sois c'est pas gênant si ça arrive vide, et c'est même contre productif de renvoyer le formulaire à l'utilisateur parce qu'il a rien écris non ? (car un signalement doit etre simple et rapide AMHA, donc s'il commence à nous revenir au nez après un traitement de back et donc un rechargement c'est pénible)

Du coup je propose un simple required + pattern :)

**Comment by vhf** [comment]
100% d'accord avec @Eskimon sur ce coup.

**Comment by Alex-D** [comment]
A part que si le formulaire est bien fait il vient du back donc required + pattern = forms.py. Mais maintenant que tu le dis, c'est peut-être bien un truc moche fait en HTML brut.

**Comment by Eskimon** [comment]
Pas de pot, [c'est un truc tout moche en dur](https://github.com/zestedesavoir/zds-site/blob/master/templates/misc/message.part.html#L69) (spa moi qui l'ai dit ^^)

**Comment by Alex-D** [comment]
Donc on dit qu'on limite au niveau du front only ?

**Comment by firm1** [comment]
La bonne pratique serait de faire ça en front ET en back. Au cas ou le required n'est pas géré sur un navigateur le back refusera qund même.

**Comment by Eskimon** [comment]
Ouai mais ca devient tout de suite plus chiant si on fait en back aussi, car renvoi de variable + réaffichage de la modale avec message d'erreur (pour au final juste un signalement qui ne concernera que les staff et dont un message vide n'est pas si dramatique).

J'en convient que la bonne pratique serait Back + Front cependant, mais dans ces cas la je vais passer la main car ca me demandera plus de temps que raisonnable pour le faire :)

**Comment by firm1** [comment]
> - réaffichage de la modale avec message d'erreur

J'avais pas conscience de ce point chiant, donc je dis ok pour la solution front toute simple

**Comment by vhf** [comment]
+1 @firm1

**Comment by Alex-D** [comment]
Disons que pour les alertes on s'en moque un peu si le message est vide, c'est pas bloquant. Donc la solution du front-only me va parfaitement.

**Comment by Eskimon** [comment]
Dans ce cas la PR sera la demain :)
