### ISSUE TITLE
Les sujets de la corbeille sont visibles dans la recherche

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#983]
A priori, les retours des membres indiquent que les sujets dans la corbeille sont visibles à travers la recherche. Je pensais que ça aurait été fixé avec la PR qui retirait les messages des forums staff et dev.

Ne serait-il pas possible de tester le droit nécessaire du forum hébergeant le sujet afin de déterminer s'il doit être retourné ou non par le moteur de recherche ? Je n'ai aucune idée de la façon de faire actuelle, c'est donc une simple suggestion.

**Comment by firm1** [comment]
Le problème avait déjà été fixé via ce [commit](https://github.com/zestedesavoir/zds-site/commit/bfb65a96843d3c6a936d87feb02ec679792d0eb9), c'est donc juste une regression à corriger sur les templates.

**Comment by Alex-D** [comment]
Hein ? Ce sont les templates qui filtrent les résultats ? C'est pas bon du tout ça, c'est au back de faire le filtrage.

Là ça veut dire par exemple que si tous les résultats de la page 1 sont dans le forum d'admin on peut se retrouver avec une page 1 vide. C'est pas du tout souhaitable.

**Comment by firm1** [comment]
> Hein ? Ce sont les templates qui filtrent les résultats ? C'est pas bon du tout ça, c'est au back de faire le filtrage.

Pour faire simple il y'a deux solutions : 
- le back fait le filtrage en faisant une bouble en plus sur tous les resultats
- le front filtre les resultats et on gagne en perf (pour la recherche qui est généralement très utilisée, ça ne me semble pas déconnant).

Que préfères tu ?

**Comment by Alex-D** [comment]
> le back fait le filtrage en faisant une bouble en plus sur tous les resultats

Et y a pas de moyen de filtrer sans faire une boucle en plus ?

**Comment by firm1** [comment]
> Et y a pas de moyen de filtrer sans faire une boucle en plus ?

Nope.

**Comment by SpaceFox** [comment]
La Théorie (avec un T majuscule), serait de faire faire le boulot par Solr :
- Solr sait si un topic est public ou non
- Le back lui passe l'info quand il fait la requête (en fonction du profil de l'utilisateur, renvoyer ou non les topics privés)
- Les résultats sont automatiquement bons

Conséquences :
- Il faut indexer l'information "topic public ou non"
- Les appels à Solr doivent être modifiés en conséquence

Avantages :
- Tout marche nickel : aucun problème de filtrage, de pagination, etc.
- On ne pourra jamais faire plus plus performant par un autre moyen

Inconvénient :
- Quel est le coût de développement d'une telle solution ?

**Comment by Alex-D** [comment]
Pour moi c'est à Solr de renvoyer la liste des résultats qu'on attend et non faire du filtrage un peu n'importe comment dans les templates.

Au passage, je clos la #483 qui est en fait un strict doublon. Il est inutile de garder deux issues identiques.

**Comment by firm1** [comment]
ça fait longtemps que cette issue traine et visiblement personne ne s'y collera a la solution propre. Vous êtes sur que vous ne voulez pas utiliser la solution du filtre en front en attendant ? Parce que pour le coup, on a une énorme faille de sécurité là.

**Comment by SpaceFox** [comment]
Je regarde ce que je peux faire.

**Comment by SpaceFox** [comment]
Corrigé temporairement, je passe l'issue à une version future.

**Comment by SpaceFox** [comment]
L'évolution ici, c'est d'implémenter une version propre de ce truc.

**Comment by Eskimon** [comment]
@DevHugo je peux t'assigner ça ?

**Comment by DevHugo** [comment]
Yes, c'est ma prochaine PR, ça arrive dans la semaine. J'ai déjà en local.

**Comment by pierre-24** [comment]
Je pense qu'on est finalement bon, ici, merci @DevHugo :)
