### ISSUE TITLE
Suggestions pour les champs d'édition (sujet topic, recherche, ...)

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#99]
Une amélioration possible et intéressante serait de faire des suggestions lorsqu'un utilisateur fait une recherche ou lorsqu'il crée un topic et qu'il renseigne son titre. Pour ce dernier cas, cela permettra de diminuer les topics sur un même sujet et d'aider l'utilisateur avant même qu'il pose sa question.

Cependant, techniquement, c'est un peu plus complexe. Je ne m'y connais pas trop sur ce point mais il me semble que ces recherches doivent se faire à la manière de requêtes big data. Nous devons récupérer la saisie d'un utilisateur (chaque nouvelle lettre dans le champ d'édition), l'analyser et faire une requête intelligente sur notre système sans surcharger notre serveur. Si la requête est coûteuse et que nous avons beaucoup de visiteurs, cela risque de ralentir notre ZdS.

J'ouvre donc cette issue pour en parler dans le but d'implémenter une solution optimisée pour notre système.

**Comment by cgabard** [comment]
Pour moi le "sur chaque lettre". Une recherche sur moins de 4-5 lettres ça ne sert a rien, la proba est trop faible de trouver. Donc déjà je lancerait la recherche qu'après le premier vrai mot (c'est a dire pas "le", "la", "comment",...).

**Comment by GerardPaligot** [comment]
Tu as tout à fait raison. Ce que je voulais dire, c'est qu'à partir du moment où nous commençons à faire des requêtes, nous allons devoir faire des requêtes à chaque lettre.

**Comment by Alex-D** [comment]
Pour moi l'optimisation, ça serait plutôt de faire une recherche à chaque mot-clé tapé. J'entends par mot clé tous les mots qui ne sont pas dans un "dictionnaire" de mots qu'on exclu (le, la, les, problème, ...).

A partir de là, on réduit pas mal le nombre de requêtes. Ensuite, il faut optimiser la requête de recherche, et donc les tables liées : indexer les titres + ne rechercher que dans le forum en question.

**Comment by SpaceFox** [comment]
On peut faire ça sans trop se prendre la tête si on inclus un vrai moteur
de recherche (Lucene, SolR, ...)

Le 19 janvier 2014 15:23, DEMODE Alexandre notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
> Pour moi l'optimisation, ça serait plutôt de faire une recherche à chaque mot-clé tapé. J'entends par mot clé tous les mots qui ne sont pas dans un "dictionnaire" de mots qu'on exclu (le, la, les, problème, ...).

Ca demande de maintenir une whitelist ou de développer une IA qui va, statistiquement, sauvegarder automatiquement plusieurs mots-clés. Le système devient alors complexe.

Je ne le connais pas mais est-ce que le moteur que nous utilisons pour faire des recherches ne pourrait pas nous aider ?

Edit : Grillé par SpaceFox. ^^

**Comment by Alex-D** [comment]
La whitelist ça serait côté client, un truc bidon qu'on met à la main, juste pour pas taper toutes les 3 secondes des requêtes sur des mots inutiles, en gros, côté client, ça ne lancerait pas de requête AJAX.

Je vois le côté front en même temps que le back moi, le soucis ne se pose pas que du côté de la BDD (SolR est en place je crois, on peut s'en servir, tant qu'il renvoi du JSON), mais également au niveau du réseau/client : si à chaque lettre tu tape une requête AJAX, c'est lourd...

**Comment by firm1** [comment]
Alors, après quelques benchs sur nos outils. Mes conclusions sont les suivantes : 
- Utiliser Ajax pour ça, est non envisageable, outre le fait que sur mobile ça sera juste imbuvable, sur PC, le serveur sera probablement down pendant la réindexation Solr (notre moteur de recherche actuel).
- Le seul moyen de tenir la charge (et encore, ce n'est pas très scalable), est probablement de ne faire qu'une seule recherche (en sortie du champ de saisie du titre du topic). Et là, se posera très certainement un problème ergonomique (afficher les résultats de recherche sans gêner la saisie).

En gros, cette feature a peu de chance de tenir sur notre pauvre VPS actuel d'après mes calculs.

**Comment by firm1** [comment]
Fixé -> mergée -> Je ferme.

Merci a tous.
