### ISSUE TITLE
Connexion à la validation du compte

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#990]
Comme [ça avait déjà été discuté ici](http://zestedesavoir.com/forums/sujet/243/validation-de-compte-connexion/) et [comme l'as rappelé btw03](http://zestedesavoir.com/forums/sujet/384/processus-dinscription-trop-penible/?page=1#p3695), il faut, après avoir cliqué sur le lien de validation de son compte, ce connecter, ce qui est un peu idiot. Ceci dit, je ne sais pas ce que ça implique coté code d'implémenter une telle proposition.

(d'autant que c'est pas urgent, mais ça n'as jamais été remonté jusqu'ici)

**Comment by Eskimon** [comment]
J'ai commencé à regarder vite fait et c'est pas si trivial qu'il n'y parait...

Est-ce qu'une solution acceptable pourrait etre :
- Dans un premier proposé l'atterrissage sur un formulaire de connexion pré-remplie avec le pseudo
- Plus tard dans le dev faire l'autoconnexion (qui pose un souci : l'utilisateur n'a pas le controle de la variable "rester connecté")

**Comment by Eskimon** [comment]
> Dans un premier proposé l'atterrissage sur un formulaire de connexion pré-remplie avec le pseudo

J'ai dans mes cartons une évo codé depuis un mois qui fait ca... Des que le freeze est vraiment levé je push !

**Comment by pierre-24** [comment]
Cool :)

**Comment by Eskimon** [comment]
ok, mon evo a ete merge !

Maintenant, est-ce qu'on garde ouvert en sachant que connecter automatiquement l'utilisateur n'est pas forcement un bon choix fonctionnel, car on ne peut pas savoir s'il veut oui ou non garder la session active ou pas...

(perso je fermerai le ticket...)

**Comment by Alex-D** [comment]
> car on ne peut pas savoir s'il veut oui ou non garder la session active ou pas...

Il y a un bouton de déconnexion pour ça au pire.

Et personnellement je fermerais aussi car le problème diffère selon moi.

**Comment by Eskimon** [comment]
Je laisse un DTC trancher (ping @SpaceFox / @ArnaudCalmettes )

**Comment by SpaceFox** [comment]
Je veux bien un résumé fonctionnel, parce que je ne suis pas certain de bien comprendre le choix là :)

**Comment by Eskimon** [comment]
Resume rapide:

AVANT: Quand le nouvel utilisateur valide son compte, il est invite a se connecter via un nouveau clic pour l'emmener vers le formulaire de connexion

APRES: Le formulaire de connexion est présenté sur la page "compte validé" avec le chanp de pseudo pre-remplie.

Question: Au lieu de presenter le formulaire, pourquoi ne pas carrément connecter le membre avec se souvenir de moi par defaut. Auquel cas il faut laisser ce ticket ouvert. Sinon on peut fermer le ticket.

Mes arguments en faveur du "c'est suffisant maintenant":
- On ne doit pas imposer a l'utilisateur la connexion (mais si dans 99% des cas c'est souhaite je pense)
- On ne doit pas imposer le comportement "se souvenir de moi" (meme s'il y a un bouton "se deconnecter")
- (Techniquement je ne sais pas faire la connexion automatique)

Donc en gros, on laisse ouvert si on veut implémenter la connexion auto a l'activation du compte, sinon on ferme.

**Comment by Alex-D** [comment]
Non, il ne faut pas connecter automatiquement l'utilisateur, car c'est un coup à ce qu'il ne se souvienne plus jamais de son mot de passe, et parce qu'il faut lui laisser le choix de la connexion pérenne ou non, malgré la possibilité de déconnexion. Ca va à l'encontre de l'ergonomie et de l'expérience utilisateur acquise par tous : tu valide ton compte, ça ne veut pas dire "je me connecte".

TL;DR : pour moi c'est OK, à fermer. Mais je ne suis pas un DTC ^^
