### ISSUE TITLE
Améliorer le comportement des béta-versions

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#991]
Ça avait déjà été discuté avec #926, mais l'issue traitait du fond du problème et non de ces suggestions. Comme le dit [Neabfi sur le forum](http://zestedesavoir.com/forums/sujet/383/tutoriels-en-beta/), il serait bien de : 
- Pouvoir retrouver tout les tutos en béta sur une seule page (quitte à également les retrouver dans le menu et ainsi de suite).
- Avoir la possibilité de commenter un commentaire en béta.

Pour la seconde proposition, j'ai un peu prospecté le code, ça va être plus difficile que ça n'en a l'air, parce que ce qui identifier un tutoriel, c'est uniquement son _id_, donc ça demanderait de rajouter un champ en plus aux `Note` pour tenir compte de cet état de fait. Et ce sans compter les notifications à rediriger au bon endroit.

Ceci dit, c'est pas urgentissime.

**Comment by firm1** [comment]
> Pouvoir retrouver tout les tutos en béta sur une seule page (quitte à également les retrouver dans le menu et ainsi de suite).

Possiblement un lien "Tous les tutoriels en beta" visible uniquement par les membres et qui renvoi vers la liste de tous les tutos en version beta.

> Avoir la possibilité de commenter un commentaire en béta.

Etant donné qu'on ne fera pas de review à la github avant au moins 23 versions, je proposerais bien le fonctionnement suivant : 
- Lorsqu'on mets en beta une version de notre tuto, un sujet est crée dans le forum beta
- On peut donc commenter la version beta
- Lorsqu'on arrête la beta sur une version de notre tutoriel, le sujet est question est locké
- Si on réactive la beta sur la même version, le sujet est dévérouillé
- Si on active la beta sur une autre version, un nouveau sujet est crée

Ainsi, les commentaires restent liées à une version de beta particulière.

**Comment by pierre-24** [comment]
Ça va générer un sacré bazar si l'utilisateur change un mot et bourine le bouton "passer en béta" à chaque fois, si un recrée un sujet. Je verrais plus un message dans le topic du genre "ce tutoriel a été mis à jour, [...]" et limite un lien vers le diff, si le diff est accessible aux _users_. Ça évitera au moins de polluer le forum dédié de topics (mêmes lockés). Enfin je pense.

**Comment by firm1** [comment]
> Je verrais plus un message dans le topic du genre "ce tutoriel a été mis
> à jour,

Maintenant que tu le dis, ce comportement irait très bien aussi.

Cependant le diff est pas accessible aux users.
Le 4 juil. 2014 08:49, "Pierre Beaujean" notifications@github.com a écrit
:

**Comment by Eskimon** [comment]
Corrigé, mergé toussa...
