### ISSUE TITLE
Les tags avec caractères spéciaux ne sont pas complets

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#994]
Ainsi que reporté par [btw03](http://zestedesavoir.com/forums/sujet/403/tag-contenant-un-caractere-non-alphanumerique/?page=1#p3741), utiliser des tags contenant des caractères non-alphanumériques provoque la disparition de ceux-ci (exemple, `c#` ou `c++`).

**Comment by artragis** [comment]
Je suppose qu'il faut chercher dans le code le moment où on passe le tag dans la moulinette `slugify`.
Je propose que cette issue me soit assignée.

**Comment by pierre-24** [comment]
C'est ce que je suppose aussi. J'ajoute que : 
- Y'a une fonction `get_tag_by_title()` [dans zds/forum/views.py:188](https://github.com/zestedesavoir/zds-site/blob/a885b01951c266f6053a0301fcaf8cd8dea4dc21/zds/forum/views.py#L188) dont il faut vérifier qu'elle fait bien ce qu'on lui demande
- Le moment ou le tag ce fait slugifier, c'est [un peu plus bas à la ligne 241](https://github.com/zestedesavoir/zds-site/blob/a885b01951c266f6053a0301fcaf8cd8dea4dc21/zds/forum/views.py#L241)
- Qu'il ne faut pas oublier que cette partie [reviend à la ligne 611](https://github.com/zestedesavoir/zds-site/blob/a885b01951c266f6053a0301fcaf8cd8dea4dc21/zds/forum/views.py#L611) quand on édite le post et qu'il advient que c'est le premier du topic (btw, question copie de code, y'aurais surement moyen de faire mieux à ce niveau là).

**Comment by artragis** [comment]
Comme je le disais, qu'on m'y assigne ^^
btw, merci pour ces précisions.
