### ISSUE TITLE
Erreur si message vide

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#995]
Comme reporté par btw03 [ici](http://zestedesavoir.com/forums/sujet/397/erreur-500-si-on-envoit-une-reponse-vide/) et [là](http://zestedesavoir.com/forums/sujet/396/erreur-404-si-on-envoit-un-commentaire-vide/), donner une réponse vide à un message entraine des erreurs incohérentes (500&404) alors qu'un simple "veillez entrer quelque chose suffirait". En plus du comportement en _back_, il serait intéréssant de rajouter un peu de JS coté _front_ pour empêcher l'utilisateur de cliquer sur le lien quand le champ est vide (mais j'imagine que ça viendra avec le nouvel éditeur et tout ça).

**Comment by Alex-D** [comment]
> il serait intéréssant de rajouter un peu de JS coté front

HTML5 introduit un attribut "required" qui permet de faire ça : donc c'est au back de le faire.

**Comment by pierre-24** [comment]
Oki. et pour la priorité de la chose ?

**Comment by Alex-D** [comment]
C'est simple à faire, autant le faire dès que possible. @ArnaudCalmettes fixera la date butoir s'il le souhaite, ça n'est pas mon rôle.

**Comment by Eskimon** [comment]
J'ai réglé le probleme dans le back sur le isvalid du form, par contre je comprend pas pourquoi ce dernier est codé en dur dans [https://github.com/zestedesavoir/zds-site/blob/master/templates/misc/message_form.html#L7](https://github.com/zestedesavoir/zds-site/blob/master/templates/misc/message_form.html#L7)

Du coup je rajoute aussi à la mano le required sur le form codé en dur ? (mais ca fait tout moche en rajoutant le cadre rouge lors du premier passage...). Un conseil à me donner @Alex-D ? :)

**Comment by firm1** [comment]
Fixé, merci @Eskimon
