### ISSUE TITLE
Quitter une conversation (MP) provoque une erreur 500

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#996]
Reporté par [btw03 ici](http://zestedesavoir.com/forums/sujet/401/quitter-une-conversation-cause-une-erreur-500/) : 

> si je clique sur "Quitter la conversation" pour ce MP, j'obtiens une erreur 500 "Internal Server Error", mais la conversation est bien supprimée. 

Edit : [ajout de btw03](http://zestedesavoir.com/forums/sujet/401/quitter-une-conversation-cause-une-erreur-500/?page=1#p3765) : 

> Je précise que je n'ai testé que le cas où je suis tout seul dans la conversation (ie une fois que j'ai quitté la conversation, il n'y a plus personne dedans).

**Comment by Eskimon** [comment]
Tout est réglé sur ce ticket :) Testé et tout est bon !

Merci @vulser pour les tests :)
